### ISSUE TITLE
Datagrid filter not working with fetched data

### ISSUE THREAD

**Issue by KatuGT** [mui/mui-x#10004]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Go to https://sizematch.net/Valve
2. Input data, you can use the one you see at the placeholder
3. try to use the filter

it does not just fail with Valve section, I just choosed that one because is the simpliest (visually talking)

### Current behavior 😯

I want to use the filter option to get just a sigle code, for example, but after writing, nothing happend. The data is fetched from my database.  I have done a "test" with fake data, and the filter do works but I cant find if there is a configuration on mine that make it fail

### Expected behavior 🤔

I want the filter just show the code I wrote on it

### Context 🔦

My table may be quiet big and when I have to edit some data it is really hard to find the code, this would be 100% not a problem if I caould just enter the code and proced to edit it.

Here is the test I did, te seonc table get the data just if you input at last two measurement, so it is the reseult of a search in this case, BUT I hace the "admin table" there the data comes directly from the databse, it include all the items of couse, and there the filter is not working any way
![ezgif com-video-to-gif](https://github.com/mui/mui-x/assets/38865485/130a8b8d-58be-48c8-bd02-b1429293ee20)

Columns config: https://github.com/KatuGT/sizematch/tree/dev/src/utils/ColumnConfig

There is the configuration from the two tables I use

Example user Datagrid
https://github.com/KatuGT/sizematch/blob/dev/src/app/Valve/ValveSearcher.tsx
` <DataGrid`
`            rows={searchResults}`
`            columns={columnValve}`
`            getRowId={(row) => row._id}`
`           initialState={{`
`             sorting: {`
`               sortModel: [`
`                  {`
`                   field: "code",`
`                   sort: "asc",`
`                 },`
`               ],`
`             },`
`             pagination: {`
`               paginationModel: { page: 0, pageSize: 5 },`
`             },`
`             columns: {`
`               columnVisibilityModel: {`
`                 status: false,`
`                 _id: false,`
`               },`
`             },`
`           }}`
`           pageSizeOptions={[5, 10]}`
`           sx={{`
`             color: "#fff",`
`             "& .MuiDataGrid-columnHeaders": {`
`               backgroundColor: "#020617",`
`             },`
`             "& .MuiDataGrid-row:nth-of-type(even)": {`
`               backgroundColor: "#1e293b",`
`             },`
`             "& .MuiDataGrid-cell:nth-of-type(n+3)":{`
`               justifyContent: 'center'`
`             }`
`           }}`
`           loading={isLoading}`
`           slots={{`
`             noRowsOverlay: () =>`
`               !params ? (`
`                 <GridOverlay>Nothing to show</GridOverlay>`
`               ) : (`
`                 <GridOverlay> No results</GridOverlay>`
`               ),`
`             noResultsOverlay: () => <div>No results</div>,`
`             loadingOverlay: () => <GridOverlay>Wait a second...</GridOverlay>,`
`           }}`
 `         />`
------------------------------
Admin table: https://github.com/KatuGT/sizematch/blob/dev/src/Components/TableAdmin/TableAdmin.tsx

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
   System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.200)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0        
    @mui/base:  5.0.0-beta.5
    @mui/core-downloads-tracker:  5.13.4        
    @mui/icons-material: ^5.11.16 => 5.11.16    
    @mui/material: ^5.13.6 => 5.13.6
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.6
    @mui/types:  7.2.4
    @mui/utils:  5.13.6
    @mui/x-data-grid: ^6.9.1 => 6.9.1
    @types/react: 18.2.12 => 18.2.12
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.1.3 => 5.1.3
```
</details>

**Comment by cherniavskii** [comment]
Hi @KatuGT
Could you provide a minimal reproduction example of the issue?
You can start with [this template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) or create one from scratch.
Thank you!

**Comment by KatuGT** [comment]
@cherniavskii Hello! it HAS to be with code using code sandbox? because the website is deployed and you can go to, for instance, to https://sizematch.net/Valve  Ar first, the table will be empty buy you can type 5 at the "A" input and 6 at "B" input and and you will get some result for testing

Thanks!

**Comment by cherniavskii** [comment]
@KatuGT I can reproduce it on your website, but cannot reproduce it with a minimal grid example: https://codesandbox.io/s/angry-babycat-zmq479?file=/Demo.tsx
This makes me think there might be something on your side that impacts the filtering.
We need a minimal reproduction example to confirm this is indeed an issue with the data grid.

**Comment by myarasi8** [comment]
Hello,

I don't know if I should submit a new bug or comment on this but I am experiencing the same issue. When I hardcode the columns like this I noticed the default filtering works:

![image](https://github.com/user-attachments/assets/3608ab53-43e3-49a5-a37f-da1702e0b6f3)

But when I fetch the column names from the database and provide the columns that way, it will display my table correctly but the filter isn't working:
![image](https://github.com/user-attachments/assets/3ba651b3-eacf-48be-9f12-3746ccf2d2ea)

Please let me know if this is the correct way to document this issue and let me what priority this bug will get.

Thank you very much.
