### ISSUE TITLE
[charts] Add support to event listeners (e.g. onClick)

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#10005]
# Summary

Currently, there's no way to listen to events to implement custom behaviors.
The event listeners should be applied to any chart elements (bar, point, axis, legend, etc.).

# Examples

https://api.highcharts.com/highstock/chart.events
https://recharts.org/en-US/examples/BarChartWithCustomizedEvent

# Motivation

Custom interactivity (cross-filtering e.g.).

**Comment by alexfauquette** [comment]
Fixed by #11411
