### ISSUE TITLE
[data grid] How to Pass custom arg to `valueGetter`?

### ISSUE THREAD

**Issue by andreskimlee** [mui/mui-x#10008]
### Order ID

72370

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Currently I am rendering my DataGridPremium like so 

```tsx
 <DataGridPremium
            columns={[
              ...genColumns(tableCellValues),
```

```ts
const genColumns = (tableCellValues: TableCellValues) => {
    /// console.log(tableCellValues) <-- here getting up to date tablecellValues
    const cols = currColumnHeaders.map((header) => {
     switch (header) {
        case EXT_PRICE:
          return genPriceColumn(
            header,
            currColumnHeaders,
            tableCellValues,
            batchSize,

          )
     }

```

```ts
export const genPriceColumn = (
  header: string,
  currColumnHeaders: string[],
  tableCellValues: TableCellValues,
  batchSize: number,
) => ({
  field: header,
  headerName: header,
  flex: 0.5,
  minWidth: 150,
  type: 'number',
  align: 'right',
  groupable: false,
  valueFormatter: ({ value }: any) => {
    if (!value) {
      return value
    }
    return currencyFormatter.format(value)
  },
  valueGetter: (params: GridValueGetterParams) => {
    // console.log(tableCellValues) <--- over here getting outdated version of object.
    const bomLineItem: BomLineItem = params.row as BomLineItem
    let price = 0

    if (
      !isEmpty(tableCellValues) &&
      bomLineItem.id in tableCellValues &&
      currColumnHeaders[ColumnIndex.PRICE_COL_IDX] in
        tableCellValues[bomLineItem.id]
    ) {
      const currPriceCellVal = tableCellValues[bomLineItem.id][
        currColumnHeaders[ColumnIndex.PRICE_COL_IDX]
      ] as PriceCellValue

      switch (header) {
        case UNIT_PRICE:
          price = currPriceCellVal.unitPrice
          break
        case EXT_PRICE:
          console.log(currPriceCellVal.extPrice)
          price = currPriceCellVal.extPrice
          break

        case EXCESS_COST:
          price = currPriceCellVal.isEstimated
            ? currPriceCellVal.estExcessCost
            : currPriceCellVal.excessPrice
          break
        case MISC_COST:
          price = currPriceCellVal.miscCost
          break
      }
    }

    return price
  },
})
```

genPriceColumn is essentially a factory method that generates the GridColDef for that column. The issue I am having is that genPriceColumn's valueGetter is getting an outdated version of tableCellValues, even though it is passed as an argument.

when I console log inside tableCellValues, it will have the most up to date values. However within my priceColumn fn, it will get reference to an outdated tableCellValues object. Not sure whether I have a JS issue (Maybe a closure bug?) or DataGridPremium has some kind of internal memoization strategy. What ends up occuring is on initial render, the table gets the sum value correct. However whenever there is a change to tableCellValues, the aggregation cell does not seem to update the value properly. 

Edit: The valueGetter is unable to get the correct up to date reference of tableCellValues. 

One thing that works is setting a key to be a stringified version of the tableCellValues to force a re-render but not the most ideal solution due to potentially additional renders

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
@andreskimlee if you can provide a minimal reproduction that would be great as it will help us understand the problem more clearly. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point.
That being said once you pass in the data to the grid the grid maintains it in an internal state so if you are referencing it from outside it's normal that the value will be outdated. If on the other hand, you are updating the original data source and the value is still not correct then I would advise you to use the grid `apiRef` to select it. Looking at your code you would need the `rows` data.
