### ISSUE TITLE
[docs] Demo LazyLoadingGrid crashes

### ISSUE THREAD

**Issue by muratmavlidov** [mui/mui-x#10010]
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LazyLoadingGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/row-updates/#infinite-loading
2. ??
3. demo *LazyLoadingGrid* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.11.1  |
| Netlify deploy | https://64d60e95a665f20007d289ec--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

**Comment by MBilalShafi** [comment]
@muratmavlidov Could you mention the reproduce steps or attach a video? The mentioned demo works fine for me.

**Comment by oliviertassinari** [comment]
Duplicate of #10047
