### ISSUE TITLE
[pickers] Field format do not respect format strings without padding

### ISSUE THREAD

**Issue by aki665** [mui/mui-x#10028]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-date-pickers-formating-error-hllj6y?file=/src/App.tsx

Steps:
1. Create a date or time picker
2. Give it a format string that does not include padding (e.g. H:mm for time)

### Current behavior 😯

Date and time pickers always show a zero before a single digit value, even if the provided format should not do so.

### Expected behavior 🤔

The picker should show to value in the format provided. See live example for expected formating and the pickers current formating

### Context 🔦

I'm trying to format date and time strings to match the Finnish format, that does not include padding, except for minutes.

### Your environment 🌎

Tested on Chrome and Firefox
<details>
<summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.188)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.10
    @mui/core-downloads-tracker:  5.14.4
    @mui/material: ^5.14.4 => 5.14.4
    @mui/private-theming:  5.14.4
    @mui/styled-engine:  5.13.2
    @mui/system:  5.14.4
    @mui/types:  7.2.4
    @mui/utils:  5.14.4
    @mui/x-date-pickers: ^6.11.0 => 6.11.1
    @types/react:  18.2.20
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  5.1.6
```
</details>

Note: this enviroment differs from the one where this feature is being developed, but the same issue is still present.

### Order ID or Support key 💳 (optional)

63464

**Comment by flaviendelangle** [comment]
Hi,

The doc about this behavior can be found [here](https://mui.com/x/react-date-pickers/adapters-locale/#respect-leading-zeros-in-fields)

**Comment by aki665** [comment]
Thank you. This "fixes" the problem I was having. I did not realize the picker needed to be given this prop.
