### ISSUE TITLE
[DataGrid] getRowElement returning null

### ISSUE THREAD

**Issue by lcoenenvisua** [mui/mui-x#10036]
### Order ID or Support key 💳 (optional)

64854

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi, 

It seems I cannot get the element using `getElementRow`. I tried passing an index and an id.  I keep getting 'null'

Reproduction:

https://codesandbox.io/s/vigilant-currying-l6hxfq?file=/demo.tsx

### Your environment 🌎

<details>

  System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: Not Found
    Safari: 16.5.2
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.10 
    @mui/core-downloads-tracker:  5.14.4 
    @mui/icons-material: ^5.11.9 => 5.14.3 
    @mui/material: ^5.13.6 => 5.14.4 
    @mui/private-theming:  5.14.4 
    @mui/styled-engine:  5.13.2 
    @mui/styles: ^5.14.4 => 5.14.4 
    @mui/system:  5.14.4 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.4 
    @mui/x-data-grid: ^6.9.0 => 6.11.0 
    @mui/x-data-grid-premium: ^6.11.0 => 6.11.0 
    @mui/x-data-grid-pro: ^6.9.0 => 6.11.0 
    @mui/x-license-pro: ^6.9.0 => 6.10.2 
    @types/react:  18.2.19 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 

</details>

**Comment by romgrk** [comment]
Can't reproduce:

![image](https://github.com/mui/mui-x/assets/1423607/aa7da394-a715-42c2-9dc4-6f07b201e759)

Make sure you're using a clickable element: https://codesandbox.io/s/unruffled-oskar-hccfk5?file=/demo.tsx
