### ISSUE TITLE
[data grid] boolean filter "is" uses string version of `true` for determining truthiness

### ISSUE THREAD

**Issue by snemvalts** [mui/mui-x#10049]
### Steps to reproduce 🕹

Link to live example on latest version: https://codesandbox.io/s/mui-x-issue-template-forked-s5nzdk?file=/src/App.tsx

### Current behavior 😯

1. First table shows generated data with 50-50 true false.
2. Second table ( with boolean filter value set to `true` (boolean)) shows rows where the value is `false`
3. Third table (with boolean filter value set to `"true"` (string `"true"`)) shows rows where the value is `true`

### Expected behavior 🤔

1. First table shows generated data with 50-50 true false.
2. Second table (with filter value set to `true` (boolean)) shows rows where the value is `true`
3. Third table (with filter value set to `"true"` (string `"true"`)) isn't either accepted as a value, or shows no rows.

### Context 🔦

Looking to use the built in filter for filtering by boolean.

Source of bug https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/colDef/gridBooleanOperators.ts#L15

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Command does not run with asdf for me. Browser: latest Chrome. Reproducible on latest MUI version in codesandbox provided.
</details>

### Order ID or Support key 💳 (optional)

72874

**Comment by romgrk** [comment]
@mui/xgrid Does someone have context why we're converting `boolean` values with `const valueAsBoolean = filterItem.value === 'true';`? It seems like a bug to me, but I'm afraid to break something if I fix it the way I think it should be.

**Comment by oliviertassinari** [comment]
The blame points to #1321. Maybe because in the UI, true is set as "true" in the value of the select.

*I'm coming from the xgrid GitHub team notification, I removed myself for the next time.*

**Comment by cherniavskii** [comment]
I think this diff should do the job:

```diff
diff --git a/packages/grid/x-data-grid/src/colDef/gridBooleanOperators.ts b/packages/grid/x-data-grid/src/colDef/gridBooleanOperators.ts
index 9c93a6232..1d636f746 100644
--- a/packages/grid/x-data-grid/src/colDef/gridBooleanOperators.ts
+++ b/packages/grid/x-data-grid/src/colDef/gridBooleanOperators.ts
@@ -8,11 +8,11 @@ export const getGridBooleanOperators = (): GridFilterOperator<any, boolean | nul
     {
       value: 'is',
       getApplyFilterFnV7: (filterItem: GridFilterItem) => {
-        if (!filterItem.value) {
+        if (filterItem.value == null) {
           return null;
         }
 
-        const valueAsBoolean = filterItem.value === 'true';
+        const valueAsBoolean = String(filterItem.value) === 'true';
         return (value): boolean => {
           return Boolean(value) === valueAsBoolean;
         };
```

**Comment by gitstart** [comment]
@romgrk @oliviertassinari @cherniavskii we would like to pick this up

**Comment by romgrk** [comment]
Sure this one should be easy.

**Comment by shaharyar-shamshi** [comment]
@cherniavskii @romgrk This seems to be stale with the above information in can I take this issue

**Comment by romgrk** [comment]
Sure, you can open a PR for this 👍
