### ISSUE TITLE
Delay processing initialState until loading loading state is false

### ISSUE THREAD

**Issue by colespencer1453** [mui/mui-x#10042]
### Order ID

61942

### The problem in depth 🔍

Hello! I am using version 6.0.1 of "@mui/x-data-grid-pro". 

We have been using it for a while and have a feature we support to save the last state of column ordering, filters, columnWidth, and column visibility by user. 

We have been storing this in local browser storage, but have decided to migrate this over to our database for simplicity and more control in case we need to roll an update and need to clear the user's settings.

An issue we are encountering is that previously with local storage the last state was immediately available on page mount so that when the component mounted it was correctly passed the initialState.

With storing it in our database we have to make an API call that isn't immediately available on page load and mount. This means that the initial value passed to initialState is null on page load and it isn't listening to updates to that value when the value is fetched from the database.

Our only current option is to conditionally render the data grid until that value has been fetched. However, this isn't as ideal as using the grids built in loading state.

I am wondering whether there is a small and easy change that could allow the data grid to not process or "listen" to the initialState until the loading state on mount is false. This may seem a little silly, but is logical to me. Also can see how there could be some difficult ordering issues with trying to initialize the grid and show the data. 

Overall just looking for guidance on best practice for how to handle this.

Below is the Grid component with some forwarded props. 

<details>
<summary>code</summary>

```tsx
<StyledDataGridPremium
        rows={rows}
        columns={columns}
        apiRef={apiRef}
        checkboxSelection
        cellModesModel={cellModesModel}
        onCellModesModelChange={handleCellModesModelChange}
        onColumnVisibilityModelChange={handleColumnVisibilityModelChange}
        onPinnedColumnsChange={handlePinnedColumnsModelChange}
        onColumnOrderChange={handleColumnOrderChange}
        onColumnResize={handleColumnResize}
        onCellClick={handleCellClick}
        loading={loading}
        processRowUpdate={processRowUpdate}
        slots={{
          toolbar: PerformanceGridToolbar,
          columnHeaderFilterIconButton: GridColumnHeaderFilterIconButton,
          footer: () => <PerformanceGridFooter selectionModel={rowSelectionModel} />
        }}
        slotProps={{
          toolbar: {
            apiRef,
            setFilterButtonEl,
            bulkActions,
            disableGridDateRangePicker
          },
          panel: {
            anchorEl: filterButtonEl
          },
          filterPanel: {
            logicOperators: [GridLogicOperator.And]
          }
        }}
        disableRowSelectionOnClick
        getRowId={getRowId}
        rowSelectionModel={rowSelectionModel}
        onRowSelectionModelChange={(newSelectionModel) => {
          setRowSelectionModel(newSelectionModel);
        }}
        initialState={initialState}
        getRowClassName={getRowClassName}
        isCellEditable={isCellEditable}
        pagination
        paginationMode="server"
        filterMode="server"
        paginationModel={paginationModel}
        rowCount={rowCount}
        pageSizeOptions={ROWS_PER_PAGE_OPTIONS}
        onSortModelChange={handleSortModelChange}
        onFilterModelChange={handleFilterModelChange}
        onPaginationModelChange={handlePaginationChange}
        aggregationModel={aggregationModel}
        onAggregationModelChange={(newModel) => setAggregationModel(newModel)}
        aggregationFunctions={aggregationFunctions}
        {...otherProps}
      />
```

</details>

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
Have you tried using `apiRef.current.setState(state)`?

**Comment by romgrk** [comment]
`.restoreState(state)` actually.

https://mui.com/x/react-data-grid/state/#save-and-restore-the-state
