### ISSUE TITLE
[DataGrid] Allow changing the footer label for total row count

### ISSUE THREAD

**Issue by hungmanhle** [mui/mui-x#10055]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently we are able to customize the label of the totalrows displayed in the footer by adding a `localeText` of `footerTotalRows`. However we are only able to change the label such that it displays as `label: totalRows`. I have a usecase where I'd like to be able to display it as `totalRows: label`.

Suggestion is to change `footerTotalRows` so it accepts a function that takes the totalRowCount and returns a string instead.

### Examples 🌈

Current behavior: 
![image](https://github.com/mui/mui-x/assets/6510778/275ebb1b-cc63-4de9-abe6-68edeaf21dfd)

What I would like:
<img width="884" alt="image" src="https://github.com/mui/mui-x/assets/6510778/b0816b94-3cc8-4ee3-ae54-233e25163d2f">

### Motivation 🔦

There is a use case where I'd like the number of rows to display as "total: COUNT invoices".

**Comment by romgrk** [comment]
The label is rendered here:

https://github.com/mui/mui-x/blob/003229083822fe6dbd44496ab162151eaa8f0739/packages/grid/x-data-grid/src/components/GridRowCount.tsx#L68

If you want to submit a PR to make that change it would probably be the fastest way to get this done.
