### ISSUE TITLE
[DataGrid] esbuild & terser no longer minifying, hide `eval` calls from bundlers

### ISSUE THREAD

**Issue by romgrk** [mui/mui-x#10056]
The issue raised by @peterhirn in https://github.com/mui/mui-x/issues/9771#issuecomment-1657959052

A quick exploration of what's going on: https://github.com/mui/mui-x/issues/9771#issuecomment-1680908511

**Comment by oliviertassinari** [comment]
> I think we can work around that by adding another real closure around and passing arguments instead of closure values.

I have tried this:

```jsx
const x = 1;

(() => {
  console.log(eval('x'));
})();
```

it prints something random: `"Symbol(react.responder)"` and esbuild doesn't minify the variables.

**Comment by yannours** [comment]
Hello there, I've faced it also using vitejs when building.

![Screenshot from 2023-08-31 15-17-15](https://github.com/mui/mui-x/assets/13019592/ea6f3540-1ebf-4df3-9152-86efa891ee06)

It cause issues with minifying

![Screenshot from 2023-08-31 15-20-32](https://github.com/mui/mui-x/assets/13019592/a7a01714-c122-4ae5-8d00-44801a70209e)

Hope it can add to the issue.

**Comment by romgrk** [comment]
I've opened #10329 to fix the issue. I've been able to reproduce & fix the issue for `vite`. I wasn't able to observe the issue for `webpack` or `esbuild`. If someone wants to provide more details for those bundlers please do so.

**Comment by romgrk** [comment]
I've merged the PR, it will be released next week. If there are still issues with other build tools, please re-open, but afaict the `eval` calls are hidden & handled properly now.

**Comment by jscott-resilient** [comment]
Hello everyone!

Within gridFilterUtils.ts the following line of code

```
// Fixes https://github.com/mui/mui-x/issues/10056
const global = (typeof window === 'undefined' ? globalThis : window) as any;
```

causes the following error with jest

```
/Users/projects/hub-app/node_modules/@mui/x-data-grid/node/hooks/features/filter/gridFilterUtils.js:15
    const global = typeof window === 'undefined' ? globalThis : window;
          ^

    SyntaxError: Identifier 'global' has already been declared

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@mui/x-data-grid/node/hooks/features/filter/useGridFilter.js:24:24)
```

would it be possible to rename this variable?

**Comment by romgrk** [comment]
Sure, that's something we can do. Just out of curiosity, did you report this to jest? Sounds more like a bug on their side.

**Comment by jscott-resilient** [comment]
No but I can let them know! Yeah does seem pretty weird, you can limit the scopes when using jest but global is set by default
