### ISSUE TITLE
[DataGrid] DataGrid Horizontal ScrollBar doesn't show using Vite+JS

### ISSUE THREAD

**Issue by marmundo** [mui/mui-x#10054]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Using official documentation, when I resize window width, scrollbar doesn't show.

Link to live example:
https://codesandbox.io/p/sandbox/fancy-grass-yp3lyd?welcome=true
Steps:
1. Start project using VITE+JS 
2. Install MUI and MUI-X DataGrid
3. Resize window to review responsive behaviour
4. DataGrid Horizontal ScrollBar doesn't show

P.S: Using create-react-app there isn't this bug.

### Current behavior 😯

DataGrid Horizontal ScrollBar doesn't show when window width is lower than datagrid with

### Expected behavior 🤔

Horizontal ScrollBar should appear.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browser: Chrome
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.11 
    @mui/core-downloads-tracker:  5.14.5 
    @mui/material: ^5.14.5 => 5.14.5 
    @mui/private-theming:  5.14.5 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.14.5 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.5 
    @mui/x-data-grid: ^6.11.1 => 6.11.1 
    @types/react: ^18.0.17 => 18.0.17 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
```
</details>

**Comment by romgrk** [comment]
If I manually switch the width of the `#root` element the scrollbar appears. It seems like this is a CSS issue. The grid will fill the width that you give it.

![image](https://github.com/mui/mui-x/assets/1423607/255cf8cd-9d27-4ab7-ad20-a8edd7c3e721)

Does that answer your question?

**Comment by marmundo** [comment]
I think it isn't because I used an official documentation example. It should work on CRA or Vite. I think it should be fixed on component or example should be altered to reflect your change.

**Comment by romgrk** [comment]
> I have a complex page which changing width to 100% on root element won't shows scrollbar.

Do you have a reproducible example of this issue?

**Comment by marmundo** [comment]
Is codespace example not enough to show that there is a problem on create a react app with vite and datagrid?

Using CRA there isn't such bug. You can check [here](https://mui.com/x/react-data-grid/column-definition/#system-ValueGetterGrid.js).


> > I have a complex page which changing width to 100% on root element won't shows scrollbar.
> 
> Do you have a reproducible example of this issue?

I added complex page [link](https://codesandbox.io/p/sandbox/fancy-grass-yp3lyd?file=/src/ListagemUsuario.jsx) but it load nothing because I access a API and I can't make token or url public.

On my project I added ```#root{width:100%}``` to index.css but it doesn't work.

**Comment by romgrk** [comment]
I'm sorry but I don't see a bug. The first codesandbox was missing the proper CSS to make the grid work like you wanted to. Adding it fixed the issue.

If I open the codesandbox links in your last message, I don't see anything and there seem to be errors logged to the console:

![image](https://github.com/mui/mui-x/assets/1423607/2489eae1-11e5-4a48-9691-730f6468e6d0)

**Comment by marmundo** [comment]
As I said before my page won't render properly because I consume a API that I can't make it public. 

I don't want to be insistent but can you explain why official example works on mui docs but I have to change CSS on the same example using vite?

If you don't mind you can compare code on Mui repository and mine.

Thanks

**Comment by marmundo** [comment]
> I'm sorry but I don't see a bug. The first codesandbox was missing the proper CSS to make the grid work like you wanted to. Adding it fixed the issue.
> 
> 
> 
> If I open the codesandbox links in your last message, I don't see anything and there seem to be errors logged to the console:
> 
> 
> 
> ![image](https://github.com/mui/mui-x/assets/1423607/2489eae1-11e5-4a48-9691-730f6468e6d0)
> 
> 
> 
> 

I'll add width 100% on parent container. I'll put here the result. I think it would worth see this behaviour difference in horizontal scroll on CRA and Vite.

**Comment by marmundo** [comment]
> > I'm sorry but I don't see a bug. The first codesandbox was missing the proper CSS to make the grid work like you wanted to. Adding it fixed the issue.
> > If I open the codesandbox links in your last message, I don't see anything and there seem to be errors logged to the console:
> > ![image](https://user-images.githubusercontent.com/1423607/261110713-2489eae1-11e5-4a48-9691-730f6468e6d0.png)
> 
> I'll add width 100% on parent container. I'll put here the result. I think it would worth see this behaviour difference in horizontal scroll on CRA and Vite.

It worked. My DataGrid is contained in <Grid item>. To work I changed to <Grid item sx={{ width: "100%" }}>

**Comment by romgrk** [comment]
:+1:
