### ISSUE TITLE
[DateRangePicker] Helper text positioning

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#10058]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open https://codesandbox.io/s/hardcore-currying-yvnr4k?file=/demo.tsx
2. Open the popup

### Current behavior 😯

The helper text is still visible, and the popup is centered

<img width="808" alt="Screenshot 2023-08-16 at 19 48 24" src="https://github.com/mui/mui-x/assets/3165635/0ab5f32d-4638-4e9c-b49d-15acbf1f6b4b">

### Expected behavior 🤔

Like with the `<DatePicker>` #7445

<img width="808" alt="Frame 1" src="https://github.com/mui/mui-x/assets/3165635/0b3cc389-0d2c-4dd3-a9df-170e02e344b4">

### Context 🔦

I noticed this in #9386.

### Your environment 🌎

v6.11.1

**Comment by LukasTy** [comment]
@oliviertassinari What about the `MultiInput` variant of the date range picker?
Would you still expect the popup to be `left` aligned? 🤔

**Comment by oliviertassinari** [comment]
> What about the MultiInput variant of the date range picker? Would you still expect the popup to be left aligned? 🤔

@LukasTy I think it should be the same, almost all the benchmark in https://www.notion.so/mui-org/Date-Range-Picker-component-271834fb7d274531a9c44286c1d23d9c do this.
