### ISSUE TITLE
Errors after column grouping implementation

### ISSUE THREAD

**Issue by DenisovKirill** [mui/mui-x#10067]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Hello!
I have a problem in my DataGridPremium component. Recently I implemented a column grouping feature and since then from time to time I get following errors.

![columnFieldsError-1](https://github.com/mui/mui-x/assets/22613538/781c2854-77db-4486-8034-9af6cdab82fd)
![columnFieldsError-2](https://github.com/mui/mui-x/assets/22613538/6d97e957-e702-489b-a478-a33af2823d04)
![computedWidthError-1](https://github.com/mui/mui-x/assets/22613538/62dfec0b-92f3-461c-9029-978062bb2c31)

![computedWidthError-2](https://github.com/mui/mui-x/assets/22613538/4295c5d0-0caa-46e1-a302-aa9d93c72873)

I removed all other features from my component but I still have these errors. In the most simplified form, my component looks like this

      <DataGridPremium
        experimentalFeatures={{ columnGrouping: true }}
        apiRef={apiRef}
        rows={rowsData ? rowsData.currentRows : []}
        columns={columns}
        columnGroupingModel={columnGroupingModel}
        loading={loading}
      />

    
Prop values for rows, columns and columnGroupingModel I get from server. This data changes often, but I prevent possible errors related to asynchrony. When I remove column grouping feature, the errors stops occurring.
Please advice what could be causing these errors?

### Your environment 🌎

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Not Found
  npmPackages:
    @emotion/react: ^11.9.0 => 11.11.1
    @emotion/styled: ^11.8.1 => 11.11.0
    @mui/base:  5.0.0-beta.11
    @mui/core-downloads-tracker:  5.14.5
    @mui/envinfo: ^2.0.9 => 2.0.9
    @mui/icons-material: ^5.8.0 => 5.14.3
    @mui/lab: ^5.0.0-alpha.83 => 5.0.0-alpha.140
    @mui/material: ^5.8.1 => 5.14.5
    @mui/private-theming:  5.14.5
    @mui/styled-engine:  5.13.2
    @mui/styles: ^5.8.0 => 5.14.5
    @mui/system: ^5.11.1 => 5.14.5
    @mui/types:  7.2.4
    @mui/utils:  5.14.5
    @mui/x-data-grid:  6.11.1
    @mui/x-data-grid-premium: ^6.11.1 => 6.11.1
    @mui/x-data-grid-pro:  6.11.1
    @mui/x-date-pickers: ^6.5.0 => 6.11.1
    @mui/x-date-pickers-pro: ^6.7.0 => 6.11.1
    @mui/x-license-pro:  6.10.2
    @types/react: ^18.2.15 => 18.2.20
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^5.3.5 => 5.3.11
    typescript: ^5.1.6 => 5.1.6
    
   I use Chrome 115.0.5790.111

### Order ID or Support key 💳 (optional)

53254

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!
