### ISSUE TITLE
[question] - How do I export more rows than I currently have on the DataGrid (using server side filtering)?

### ISSUE THREAD

**Issue by rodrigofariow** [mui/mui-x#10070]
### Order ID

54728

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi there! 👋 

I'm doing server-side pagination and filtering on this specific page:

https://github.com/mui/mui-x/assets/22502084/66b116b1-16e8-4376-af2e-97be41b42f60

As you can see, I first load 100 rows and every time the user scrolls to the last 100th row, I fetch another 100.

Since this is server side, and I might not have all the rows and never will since they can be hundreds of thousands, I can't use the standard client-side export feature (since it would only export the fetched rows so far).

### What I want to achieve:
When the user clicks an export button, I will fetch the server for a max of 2000 thousand rows on the background (respecting all the filters and sorting), but I don't want to populate the table with these.

It would be nice to have an API on DataGrid (e.g `exportRows()`) where I could send an array with the same structure as the prop `rows` and the `DataGrid` would export these with all the current columns, filters, sort, etc (as if those rows were actually on the table).

Is this something feasible with the current DataGrid architecture?
If not, do you have any suggestions on how to handle this problem?

Thank you in advance!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
Do you have a reproduction case?
Have you tested with the latest version that was released today?

Linked: #10045

**Comment by rodrigofariow** [comment]
Hi @romgrk ,
Thanks for the reply.
I haven't tested it but from my understanding it's fundamentally different from what I'm trying to achieve.

That issue solves an export that is purely based on client-side, which means all the data that can possibly be exported exists in `rows` prop, be it currently shown on the table or not.

The data I want to export **won't be available from `rows` prop for my use case.**
The reason is that I want the `rows` pro to only have the paginated data that the user fetched by scrolling down so far.

**However, on the export itself, I want to include more pages that I will fetch myself separately. This data is not accessible by any of the export methods because it won't be present in `rows` prop**

There might be a better solution to my problem but hopefully, this helps you better understand my reasons.

Happy to provide more information but it's not about a bug or anything, it's about solving a particular use case that may or may not require a new api.

**Comment by rodrigofariow** [comment]
I was able to solve this by getting the visible columns and doing some custom logic with `exceljs` to decide when to use `valueFormatter`, etc.

I was able to get pretty much everything I wanted, including the `computedWidth` of each column so I would say I'm sorted 👍 

It's probably best to not include such API if possible anyways.

Cheers!
