### ISSUE TITLE
[DataGrid] Getting "Uncaught TypeError: _apiRef$current.subscribeEvent is not a function" Error

### ISSUE THREAD

**Issue by Forzali** [mui/mui-x#10074]
### Order ID or Support key 💳 (optional)

63844

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

While using the MUI DataGridPro component, I'm encountering the above error message in a specific scenario. I have a few questions regarding the root cause of this error:

useGridApiRef Function: Should I ensure that I'm calling the useGridApiRef function correctly and using the returned apiRef object appropriately? Can I get assistance on how to use this function effectively to interact with the component?

Usage of subscribeEvent Function: Should I use the subscribeEvent function with the correct event name and context? If I am using it in the expected way, why might I still be getting this error?

MUI DataGridPro Version: I've looked at the documentation of the MUI DataGridPro version I am using, but is there a need for a specific update or change to resolve this error?

Code Snipped :
`useEffect(() => {
    apiRef?.current?.subscribeEvent("rowDragStart", (params) => {
      dragState.current = true;
    });
    apiRef?.current?.subscribeEvent("rowDragEnd", (params) => {
      dragState.current = false;
    });
  }, [apiRef]);`
  

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!

**Comment by Forzali** [comment]
Hello, first of all, I apologize for the delayed response. It might take me a bit of time to illustrate the situation you're describing with a codesandbox example, so I'll explain the exact situation first.

I don't always want to display the datagridpro component; I'm using conditional rendering. And if the datagridpro component isn't rendered, I'm encountering an error like this. Is there a way to resolve this? I don't want to display the datagridpro component all the time, only in certain situations.

If you'd like, I can provide an example to explain further. Thank you in advance for your assistance.

**Comment by Forzali** [comment]
Hello again, I'm providing an example related to codesandbox. In the example, when I change the value of `dataGridShow` to false, I encounter the error you see. After changing the value to "true," it works smoothly.

Codesandbox example: https://codesandbox.io/s/optimistic-dubinsky-wflf7s?file=/demo.tsx

**Comment by romgrk** [comment]
If the datagrid isn't mounted & initialized, then calling the `apiRef` methods is incorrect because it's not setup.

Fixed: https://codesandbox.io/s/nervous-maxwell-dps4zv
