### ISSUE TITLE
[DataGrid] Add density change event

### ISSUE THREAD

**Issue by aress31** [mui/mui-x#10080]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It seems like there is still no `onDensityChange` handler, listening for the entire state change is an overkill and will get triggered at every change and therefore to stick with the current logic of `variable` + `handler` I would love to see an `onDensityChange`.

### Motivation 🔦

Improving DX and providing more control over preference persistence.

**Comment by romgrk** [comment]
I would suggest that you keep listening to the state changes but only trigger your logic when specific parts of it change. This is flexible enough to cover all use cases, and is exactly what we do inside the grid to trigger targetted re-renders.

```tsx
// Select the parts of the state you care about
const selector = state => [state.a, state.b, state.c]

const cachedValues = useRef([])
useEffect(() => {
  return apiRef.current.subscribeEvent('stateChange', state => {
    const values = selector(state)
    if (!values.every((v, i) => v === cachedValues.current[i])) {
      // [insert save state code here]
      cachedValues.current = values
    } 
  })
}, [])
```

I don't like the idea of adding a prop for this specifically, it's too specific and doesn't have a significant advantage over using the implementation above. Does that solve your issue?

**Comment by aress31** [comment]
From an eqse of use and DX perspective I would stick pick the onDensityChange handler to remain consistent with all the other handlers.

**Comment by romgrk** [comment]
@mui/xgrid Any other opinions on adding a prop here?

**Comment by MBilalShafi** [comment]
@aress31 Thank you for using MUI X Data Grid and providing useful feedback. 😊 
The request you made makes sense and is already made previously in https://github.com/mui/mui-x/issues/5647
Fortunately it's already in our backlog and should be prioritized as some bandwidth is available.
Please feel free to checkout the discussion or hop in with your feedback on the mentioned ticket.

I'll close this one just to keep all the conversation on the same place.
Thank you.
