### ISSUE TITLE
[DataGrid] How to style Single Select options dropdown height in edit mode within the DataGrid

### ISSUE THREAD

**Issue by JaliyaMTC** [mui/mui-x#10083]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

Here I've used type : "singleSelect" for the column definition and it has more than 200 values in valueOptions.
The dropdown is expanding over the page
How to modify the styles (maxHeight and maxWidth) of the dropdown.

How to override the nested component styels :

<img width="422" alt="image" src="https://github.com/mui/mui-x/assets/83545254/f360d945-ed93-4b17-a313-cbde71e8477b">

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @JaliyaMTC 
Can you provide a reproduction example?
From what I can tell, the singleSelect dropdown is scrollable and shouldn't exceed the screen height, see this demo: https://codesandbox.io/s/pedantic-tess-yjtgpc?file=/Demo.tsx

**Comment by JaliyaMTC** [comment]
Hi @cherniavskii , from your demo how to limit the singleSelect Dropdown height to see  only five values?
<img width="143" alt="image" src="https://github.com/mui/mui-x/assets/83545254/4b950b25-959b-4df4-90db-3b46d2bf9ada">
 Here we can see 29 values , how to style the dropdown height with "max-height"
