### ISSUE TITLE
[pickers]: Unexpected error on pickers

### ISSUE THREAD

**Issue by Vinyl-Davyl** [mui/mui-x#10106]
index.js Uncaught SyntaxError: Unexpected token 'export' on datePickers even on latest updates "\node_modules\ (mui\x-date-pickers\internals\demo\index.js:1" reference

**Comment by noraleonte** [comment]
Hey! 👋 
Could you please provide a bit more context for what you are trying to do and where you encountered this error? 🤔 Thanks!

**Comment by Vinyl-Davyl** [comment]
been trying to use mui-x data pickers. but on use of the <DateContainer> wrapper for any of the internal component inside the wrapper. that error comes up for no reason. until the container is being commented out or i use an alternative. funny case scenario is when i uncomment the container. the container works as soon as i save, great. but on refresh on the browser. it breaks again. updated the library, cleared my cache. future threat to production. it was a NO. had to spend time compromising.

**Comment by flaviendelangle** [comment]
The wrapper is just here for demonstration purpose, you should probably not use it on your side.

**Comment by Vinyl-Davyl** [comment]
Yeah, I've figured it out now. Then the team should probably remove the wrapper component from the code section where we have the option to copy the code snippets, to avoid spreading unnecessary confusion around.

**Comment by LukasTy** [comment]
> Yeah, I've figured it out now. Then the team should probably remove the wrapper component from the code section where we have the option to copy the code snippets, to avoid spreading unnecessary confusion around.

We've considered this option before.
It all comes down to a couple of options:
1. Every time we need a consistent layout—we explicitly use `Stack` or `Box` components with specific `sx` styles applied to them;
2. We create an abstraction layer for that - the `DemoContainer` and/or `DemoItem`, where we consistently handle desired styles and layout to get a layout that we want for the demos;

The 2nd option does indeed have its drawbacks, especially when looking from the user's perspective and being confused as to what is the reason for those wrapper components.

- Would you go for the 1st option?
- Would having a comment before the `DemoContainer` explaining it's intent be a good enough middle ground?

**Comment by flaviendelangle** [comment]
Could we imagine moving `DemoContainer` and `DemoItem` to `@mui/x-date-pickers/demo` so that people could use it even if not advised?

**Comment by noraleonte** [comment]
I feel like exposing the `DemoContainer` and `DemoItem` defeats the purpose of the doc itself. There is already a bit of confusion among users who expect the pickers to only work with the other two components. Making them available would just prove that exact point and increase the confusion even more 🤔

**Comment by LukasTy** [comment]
I can only second Nora's opinion. IMHO, I see a couple of options to reduce the confusion:

-  Be more explicit about the intent of the `DemoContainer` by adding a comment where this component is used and add a `JSDoc` on the component itself;
- Use the direct components (i.e. `Stack`, `Box`, etc.) and the needed styling for each case;

1st option feels more correct in our current situation because we've already invested effort into fine-tuning the component as per the requirements, but 2nd option has the benefit of being clearer to the reader. 🤯 🤷

**Comment by noraleonte** [comment]
I can see a benefit in both options. 💯 But changing all the demos to use the direct components with essentially the same styling seems a bit over the top.. 🤯 
Would changing the naming of these components be an option? To something like `StyledBox` and `StyledStack`? That, in addition to Lukas' first solution, would probably be enough to suggest that we just use these components for displaying things in a certain way, and people don't *need* to use them to make the pickers work.

**Comment by Vinyl-Davyl** [comment]
> > Yeah, I've figured it out now. Then the team should probably remove the wrapper component from the code section where we have the option to copy the code snippets, to avoid spreading unnecessary confusion around.
> 
> We've considered this option before. It all comes down to a couple of options:
> 
> 1. Every time we need a consistent layout—we explicitly use `Stack` or `Box` components with specific `sx` styles applied to them;
> 2. We create an abstraction layer for that - the `DemoContainer` and/or `DemoItem`, where we consistently handle desired styles and layout to get a layout that we want for the demos;
> 
> The 2nd option does indeed have its drawbacks, especially when looking from the user's perspective and being confused as to what is the reason for those wrapper components.
> 
> * Would you go for the 1st option?
> * Would having a comment before the `DemoContainer` explaining it's intent be a good enough middle ground?

The first seems okay. @LukasTy I mean,  it's what most people would do.

**Comment by LukasTy** [comment]
> The first seems okay. I mean, it's what most people would do.

I do agree, but I'm not sure that it is the best solution for the current major.
Some users might have already gotten used to seeing those wrapper components and what they do.
For now, simply adding some JSDoc would already be an improvement IMHO.
As for a complete approach change, I'd say that it is a question for a major version. 🤔

**Comment by flaviendelangle** [comment]
The problem of the 1st option is the quality and visual consistency of the doc.
`DemoContainer` and `DemoItem` help us setting a coherent set of styles that works on all sizes of devices.

Maybe we could change the abstraction, but going back to hard-coding the styles on each demo would not be maintainable for me. 
The best approach could be to automatically apply the style to the component which loads the demo, that way people never see it and they just have a basic stack on there demo.

**Comment by Vinyl-Davyl** [comment]
> > The first seems okay. I mean, it's what most people would do.
> 
> I do agree, but I'm not sure that it is the best solution for the current major. Some users might have already gotten used to seeing those wrapper components and what they do. For now, simply adding some JSDoc would already be an improvement IMHO. As for a complete approach change, I'd say that it is a question for a major version. 🤔

Alright cool! Just hope the docs should show appropriate ways around on utilizing and using this new feature. 
I have no Issue here.

**Comment by noraleonte** [comment]
Hi, @matthiasprieth 👋 Sorry to hear about your issue

The `DemoContainer` and `DemoItem` are components we use internally to make sure the layout is consistent across our demos in the docs. They help us avoid overcrowding the code examples with the repeated use of `Box` and `Stack` components and allow users to focus on the actual demo. But that's all they do - layout. 
In essence, you don't need to use the `DemoContainer` and `DemoItem` in your code. You can build the layout wrapping the pickers in any way you want.

**Comment by matthiasprieth** [comment]
@noraleonte thank you! It would be really awesome to have such a description in docs. 🙏

**Comment by noraleonte** [comment]
@matthiasprieth We have a PR for something like that [here](https://github.com/mui/mui-x/pull/11271) 😉

**Comment by jorgegarba** [comment]
Still having the issue but in my case, I removed the use of DemoContainer component and it works fine =)
