### ISSUE TITLE
[DataGridPro] How to toggle filter panel programmatically in MUIx Data grid pro 

### ISSUE THREAD

**Issue by manu-058** [mui/mui-x#10100]
### Order ID or Support key 💳 (optional)

71855

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We want to introduce a shortcut key (  useHotkeys('alt+l', toggleFilterPanel)) to toggle the filter panel in MUIx Data grid pro. 
![z1](https://github.com/mui/mui-x/assets/38914354/a12c8024-b2d3-429f-8aad-a27cfb3714f0)

MUIX provides hook useGridApiRef() which has function showFilterPanel() & hideFilterPanel() but it doesn't have a function to toggle the filter panel,

Is there a way to know if the filter panel is open or close so that i can conditionally call the above functions.

Thank You

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @manu-058,
Here's a working demo: https://codesandbox.io/s/spring-smoke-dty78r?file=/Demo.tsx
Hope this helps!

**Comment by manu-058** [comment]
@cherniavskii ,
Thank you for the solution.
