### ISSUE TITLE
[TreeView] Scroll to programmatically selected tree item

### ISSUE THREAD

**Issue by bharatkashyap** [mui/mui-x#10113]
### Summary 💡

When selection is brought to a tree item programmatically, that page should scroll to that item in the tree view component.

### Examples 🌈

https://github.com/mui/mui-x/assets/3165635/561c3db6-3079-4799-b62a-61d4fea0453f

### Motivation 🔦

The TreeView component acts as a page hierarchy explorer for Toolpad with content often overflowing beyond its container. With this feature, the tree view component would scroll to the item currently selected in the page (and the tree itself as well)

**Comment by oliviertassinari** [comment]
I have added an illustration.

**Comment by flaviendelangle** [comment]
@bharatkashyap we discussed this issue this morning

Right now, I guess that you are controlling the selected items using the `defaultSelected` prop (renamed `defaultSelectedItems` in v7 btw).
If we added two imperative methods `apiRef.current.selectItem` and `apiRef.current.scrollToItem` (exact DX may vary), would it allow you to stop controlling the item and to fix the scroll problem you have?

**Comment by matteotrapani** [comment]
Hey! 
I have the same exact issue. I have a tree view that the user can navigate programmatically (by clicking on a button "go to details" of a different page), but I can't find a simple way to allow the autofocus on the tree view.

Is the solution proposed by @flaviendelangle going to fix it?

Thanks

**Comment by flaviendelangle** [comment]
It should yes
We should implement this feature in the coming weeks since we have several users asking for it :+1:

**Comment by tamnguyenvt** [comment]
You can set <TreeItem id={yourIdHere}/>  and use document.getElementById(yourIdHere).scrollIntoView()
