### ISSUE TITLE
[question] Data grid premium - The button to expand all the detail panels at once

### ISSUE THREAD

**Issue by HyoilKim** [mui/mui-x#10122]
### Order ID

67616

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I wonder whether there is a button to expand all the details in the header. The button should be located beside 'Order ID'
![image](https://github.com/mui/mui-x/assets/23691938/3c8f73d6-1b93-47b7-8cbc-3d42f6500ea2)

FYI, I've searched 'https://mui.com/x/react-data-grid/row-recipes/#one-expanded-detail-panel-at-a-time'.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
> expand all the details in the header.

Could you explain what details you are talking about?
Do you want a button to expand all the master-detail panels using one button?
The plus button beside `Order ID` in master-detail [demo](https://mui.com/x/react-data-grid/master-detail/) should already be able to expand a specific row.

**Comment by HyoilKim** [comment]
> By default, the Grid doesn't provide such a button but you can expand rows programmatically using available [apiRef methods](https://mui.com/x/react-data-grid/master-detail/#apiref).

Got it. I think a lot of users want the button to expand all rows. I'm looking forward to implementing it. Thank you

**Comment by MBilalShafi** [comment]
> Got it. I'm looking forward to implementing it

Perfect 🎉 

Since this question is answered, I'll close the issue now, feel free to reopen it if you have a similar thing bothering you again.
