### ISSUE TITLE
I'll like to be able to expand sub table for more than one column. (given that a row can only have one expanded sub table)

### ISSUE THREAD

**Issue by PatriceLoos** [mui/mui-x#10127]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I notice that only one column can be expanded in a given table, would it be possible to extend this functionality to multiple column?
![image](https://github.com/mui/mui-x/assets/9725591/79d0bef8-c83b-458d-8157-8d68d81a9c7e)

                

### Examples 🌈

to work around the problem

I can change the content of the extended table [ in the demo (see function DetailPanelContent) ]

`          <DataGridPro
                    density="compact"
                    columns={[
                    { field: 'name', headerName: selectedColumn, flex: 1 },
                    {
                        field: 'quantity',
                        headerName: 'Quantity',
                        align: 'center',
                        type: 'number',
                    },
                    { field: 'unitPrice', headerName: 'Unit Price', type: 'number' },
                    {
                        field: 'total',
                        headerName: 'Total',
                        type: 'number',
                        valueGetter: ({ row }) => row.quantity * row.unitPrice,
                    },
                    ]}
                    rows={rowProp[selectedColumn as keyof object]}   // here I can choose what data will be in the sub table...
                    sx={{ flex: 1 }}
                    hideFooter
                />`
                
                but I cant trigger the expand action without a click, 
                
                Is there a function I can call to trigger the expand, I tried calling functions:
                apiRef.current.setRowChildrenExpansion(id)
                and 
                apiRef.current.setExpandedDetailPanels([id])
                where apiRef = useGridApiContext();
                
but it didn't work, 

Thank you
                

### Motivation 🔦

showing more information from one table

**Comment by MBilalShafi** [comment]
Could you provide a minimal reproduction test case with the latest version? This would identify the request better. 👷
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!
