### ISSUE TITLE
[DatePicker] Unexpected behavior when inserting an invalid date after a valid date

### ISSUE THREAD

**Issue by jati91hg** [mui/mui-x#10124]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/inspiring-burnell-zrt2g3?file=/Demo.tsx

Steps:

1. Insert a valid date in the correct format (e.g. 23.08.2023, german format: DD.MM.YYYY)). The provided date will stay visible even when you click outside of the date field. 
2. Insert an invalid date (23.8.2023, zero in month is missing) via copy & paste
3. Now, when you click outside the datefield, the label will be shown. If you click on the date field itself again, the first valid date will be shown, but the valid date disappears again (and the label is shown) if you click anywhere outside of the field.

### Current behavior 😯

(See Step 3) The previous date is shown, but doesn't stay fixed when you click anywhere outside the field. instead, the label is shown again

### Expected behavior 🤔

In Step 3, I expected either

1. When you click on the field again after providing an invalid date after a valid one and after that click anywhere outside of the field, the first provided valid date stays visible inside the field

OR

2. When you click on the field again after providing an invalid date after a valid one, the format (TT.MM.JJJJ) will be shown as if you would insert a date for the first time

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
> Insert an invalid date (23.8.2023, zero in month is missing) via copy & paste

For this step, what are you focusing ?
The 1st section ? The last section ? All sections ?

If you could record a small video of your bug it would be great :ok_hand:
