### ISSUE TITLE
[docs] Demo PickersPlaygroundWrapper crashes

### ISSUE THREAD

**Issue by Camilo1318** [mui/mui-x#10128]
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20PickersPlaygroundWrapper%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-date-pickers/playground/
2. ??
3. demo *PickersPlaygroundWrapper* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.11.2  |
| Netlify deploy | https://64de1f261be56d0008a0fb81--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 |

**Comment by LukasTy** [comment]
Could you please provide more information on how to reproduce the issue?
- Does it crash after visiting the page? If yes, could you provide the error you see or a video of the error being thrown?
- Do you need to interact with the page to reproduce the issue?
- Does it happen in incognito mode and/or different browsers?
