### ISSUE TITLE
slotProps - panel - anchorEl types missing for mui-x-grid-pro

### ISSUE THREAD

**Issue by jbaccarelli-equinix** [mui/mui-x#10133]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

There is an data-grid demo/example in the project, located in docs/data/data-grid/filtering/CustomFilterPanelPosition.tsx

that shows how to use the anchorEl pattern to correctly place custom toolbar menus

```
slotProps={{
  panel: {
    anchorEl: filterButtonEl,
  },
  toolbar: {
    setFilterButtonEl,
  },
}}
```

This seems to not be replicated  in the types for mui-x-grid-pro

<img width="978" alt="Screenshot 2023-08-25 at 10 35 30" src="https://github.com/mui/mui-x/assets/102799139/c0b812f9-0eaf-40ed-95c9-a69ca6c74252">

I've tried cleaning and installing all of the project's dependencies multiple times, and searching in the cloned mui-x repo for the types, mui-x-grid-pro simply doesn't have the anchorEl props extended into `panel`

### Expected behavior 🤔

slotProps - panel - anchorEl works for mui-x-grid-pro the same as mui-x-grid

**Comment by MBilalShafi** [comment]
I couldn't [reproduce](https://codesandbox.io/s/datagridpro-basic-forked-68wx79?file=/src/App.tsx) the issue with the latest version of the Grid, could you provide a minimal reproduction test case with the latest version? This would identify the request better. 👷
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!

**Comment by jbaccarelli-equinix** [comment]
> I couldn't [reproduce](https://codesandbox.io/s/datagridpro-basic-forked-68wx79?file=/src/App.tsx) the issue with the latest version of the Grid, could you provide the environment details (`npx @mui/envinfo`) and a minimal reproduction test case with the latest version? This would help understand the issue better. 👷 A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!

I see that if i try to reproduce it withing mui-x it doesn't happen, im not really sure how we got it to not work on our project, maybe some type override somewhere, but i can see it's not a library problem. Thanks!
