### ISSUE TITLE
[pickers] With NVDA, openTo='year' cursor does not move

### ISSUE THREAD

**Issue by Valar05** [mui/mui-x#10141]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/funny-archimedes-rgc9q4?file=/Demo.js

Steps:
1. Enable NVDA screen reader (Windows specific)
2. Open the datepicker in Chrome (also happens in Firefox and Edge)
3. Attempt to move around the datepicker with the keyboard.  The screenreader will read off the options, but the cursor will not move.
4. Also, when navigating to the side, individual characters are read off as though they are separate buttons.  IE 2022 is read off as 2 2 0 2 if navigating left, and 2 0 2 2 if navigating right.

### Current behavior 😯

The cursor indicating the selected date does not move when NVDA is enabled.  Navigating sideways also behaves oddly by reading individual characters.

### Expected behavior 🤔

The cursor should move regardless of whether NVDA is enabled.  Navigating side to side should read the entire entry at once.

### Context 🔦

We are attempting to make our apps 508 compliant, and this has been flagged as an accessibility issue.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
Note - this is my machine.  However I have a mac, and thus no NVDA.  Can't run npx on the machine of the person that has NVDA.
```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/67800_1692887358564/bin/node
    Yarn: 1.22.19 - ~/.homebrew/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/67800_1692887358564/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.112
    @mui/core-downloads-tracker:  5.11.3
    @mui/material: ^5.11.0 => 5.11.3
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.2
    @mui/types:  7.2.3
    @mui/utils:  5.11.2
    @mui/x-date-pickers: ^5.0.10 => 5.0.13
    @types/react:  18.0.26
    react: ^16.13.1 => 16.14.0
    react-dom: ^16.13.1 => 16.14.0
    typescript: ^4.0.3 => 4.1.5
```
</details>

**Comment by LukasTy** [comment]
It looks like it could be directly related to #9916.
Resolving the linked issue could implicitly cover this problem.
