### ISSUE TITLE
[chart] Make item interactives

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#10159]
Feedback from the docs

> Expose click events for legend and data points.
> Would be useful to "click in" to a specific data set like togggling what's viewable in the chart.
sent from https://mui.com/x/api/charts/bar-chart/ (from section <|New API content design)>

The first step would be to have a simple way to get onClick event on items or legends

The second one would be to have controlled visibility. The google on click is available on Echarts. Not on Nivo or Rechart

**Comment by BobDenar1212** [comment]
Support Key: 76967

Hi @oliviertassinari 

We are very interested in this feature, would love to have it as soon as possible
