### ISSUE TITLE
Where is the "Cool Project" MUI X Treeview example?

### ISSUE THREAD

**Issue by salmanfazal01** [mui/mui-x#10167]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/

### Kind of issue

Unclear explanations

### Issue description

Under the MUI X link, there are a couple component demos. A fully functional Treeview component is displayed twice on the screen however, that exact example is not there on the docs.

![image](https://github.com/mui/mui-x/assets/15085416/753c6d1e-fdab-4cd9-9199-64289d46245a)

I am talking about this one with the tree branches/lines to the left. Where can I find this demo (even a Github example)?

### Context 🔦

Example component not available in docs

**Comment by flaviendelangle** [comment]
Hi, 
You can find the codebase from this examples [here](https://github.com/mui/material-ui/blob/a2214a797157feab5ddece7b2771899ec39977a0/docs/src/components/showcase/FolderTreeView.tsx#L179)

But I do agree that it would nice to add it to the doc at some point

**Comment by oliviertassinari** [comment]
Closing, I think this was answered. 

Nice to see we will also update the imports in https://github.com/mui/material-ui/pull/38261 👍
