### ISSUE TITLE
[DataGridPremium] DataGridPremium license is expired problem.

### ISSUE THREAD

**Issue by atillaaliyev** [mui/mui-x#10162]
### Order ID

49721

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi, 

![image](https://github.com/mui/mui-x/assets/6121871/bdc3a7f0-da12-4fb8-a684-e0551ea996a8)
![image](https://github.com/mui/mui-x/assets/6121871/8e086454-7d02-44e8-9b31-0acd2421b71b)

I use 5.17.17 version for MUI X.
[https://mui.com/x/introduction/licensing/#3-expired-license-key](https://mui.com/x/introduction/licensing/#3-expired-license-key)
"The annual license works forever in production with any version released before your license term ends."

I don't understand why I have watermark on DataGrid. I am using the version before the license expiration date.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @atillaaliyev 
Do you see the watermark in the production environment (`NODE_ENV=production`)?

**Comment by atillaaliyev** [comment]
No, I don't. I have seen localhost only.

**Comment by oliviertassinari** [comment]
It's expected, the license in localhost is expired.

**Comment by atillaaliyev** [comment]
Thank you.
If I have problem about this, I will re-open this issue.
