### ISSUE TITLE
DataGrid not updating Real Time Data after Field Edition.

### ISSUE THREAD

**Issue by 5Aliens** [mui/mui-x#10166]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Retrieving live data from my server and displaying on DataGrid (Unstable_Grid2)
2. Table is populated and I am able to change the values from my data array, it shows the correct information
3. Have 1 editable field
4. If I update that field the live data stops to update the table for that particular Row.

### Current behavior 😯

Real time data is not update in data grid after the server data update.

Using the examples from the docs. (https://mui.com/x/api/data-grid/grid-api/)

const useFakeMutation = () => {
  return React.useCallback(
    (update_sell) =>   
      new Promise((resolve, reject) => {
        
        setTimeout(() => {
          console.log(update_sell.user_sell)
          if (update_sell.user_sell === '') {
            reject(new Error("Error while saving user: name can't be empty."));
          } else {
            resolve({ ...update_sell, user_sell: update_sell.user_sell });
          }
        }, 200);
      }),
    [],
  );
};

  const mutateRow = useFakeMutation();

  const processRowUpdate = React.useCallback(
    async (newRow) => {
      // Make the HTTP request to save in the backend
      
      const response = await mutateRow(newRow);
      console.log(response)
      return response;
    },
    [mutateRow],
  );

I also can see in console that the server information is update but the DataGrid row information still with the original values (from when the user started to edit the field)

### Expected behavior 🤔

Data should flow and be displayed normally.

![image](https://github.com/mui/mui-x/assets/73311164/cfd0c629-c081-494f-9378-b06171f6dd2f)

### Context 🔦

base information is stored at 

const [properties, setProperties] = useState([]);

  useEffect(() => {
    setProperties(properties);
  }, [update]);

and it is retrieved from the server, but the field "Sell Test" is updated at the App.

Other fields should continue to be updated normally.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by 5Aliens** [comment]
Just adding one point. Im using value getter from params, if I get direct from my main source it works.

**Comment by MBilalShafi** [comment]
Could you provide a minimal reproduction test case with the latest version? This would help identify the request better. 👷
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!

P.S You don't necessarily have to provide example with real data. You can play around with dummy data and reproduce the same issue.
