### ISSUE TITLE
[question] With each click on the mui components, several duplicate style tags are added to the head

### ISSUE THREAD

**Issue by srbadni** [mui/mui-x#10163]
### Order ID or Support key 💳 (optional)

59340

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### The problem in depth 🔍

![Screenshot 2023-08-28 131252](https://github.com/mui/mui-x/assets/77675736/5c97c18e-0a06-4864-b3c6-2969f9afc75f)

as you can see, When some mui components are clicked, several style tags are appended to the head tag, and over time, we come across perhaps close to 100 style tags that are often duplicated, I mean, no matter what I scroll, they don't finish!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    chrome browser.
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.8
    @emotion/styled: ^11.10.6 => 11.10.8
    @mui/base:  5.0.0-alpha.127
    @mui/core-downloads-tracker:  5.12.2
    @mui/icons-material: ^5.11.11 => 5.11.16
    @mui/lab: ^5.0.0-alpha.121 => 5.0.0-alpha.128
    @mui/material: ^5.11.11 => 5.12.2
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/styles: ^5.11.11 => 5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.4
    @mui/utils:  5.12.0
    @mui/x-date-pickers: ^6.0.0 => 6.3.0
    @mui/x-date-pickers-pro: ^5.0.20 => 5.0.20
    @mui/x-license-pro: ^5.17.12 => 5.17.12
    @types/react: 18.0.28 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5

```
</details>

**Comment by MBilalShafi** [comment]
Could you mention which component you are facing the issue in? I tried [Data Range pickers](https://mui.com/x/react-date-pickers/date-range-picker/#basic-usage) and it appears to be working normally.

It'd be great if you provide a minimal reproduction test case with the latest version of the libraries. This would help identify the issue better. 👷
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/gld9nr?file=/Demo.tsx) may be a good starting point.

Thank you!

**Comment by LukasTy** [comment]
I can confirm that the component seems to work as expected, it lazily loads the required styles when necessary.
The `DateRangeCalendar` styles are loaded when the picker view is opened and transition styles are loaded when the first month change happens. After that, I can not detect any new style additions.

**Comment by LukasTy** [comment]
@srbadni Thank you for providing a video showcasing the issue and specifying the exact pain point.
The behavior you've shown is clearly not ideal, but I was unable to reproduce it.

Could you please provide a minimal reproduction example, where such behavior would be seen?
[I've tried](https://codesandbox.io/s/hungry-payne-h4w2n8?file=/Demo.tsx) adding two different icons from `@mui/icons-material` as slots on the DateRangePicker, but can only see a single style element for the `MuiSvgIcon`. 🤷
