### ISSUE TITLE
[data grid] Support asc_nulls_first and desc_nulls_last in sortingOrder

### ISSUE THREAD

**Issue by 2ndPINEW** [mui/mui-x#10173]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When defining GridCol, I would like to set it as sortingOrder: ['asc_nulls_first', 'desc_nulls_last'].
When clicking on a column to sort, I'd like the orderBy to toggle between asc_nulls_first and desc_nulls_last, and I want the arrows in the table headers to point in the specified direction."

### Motivation 🔦

When creating queries with a GraphQL client, being able to specify this in the field definition would eliminate the need for conditional branching in other parts, keeping the code streamlined and simple.

**Comment by MBilalShafi** [comment]
Are you looking for https://mui.com/x/react-data-grid/sorting/#custom-comparator to modify how the default sorting works in the Grid?
