### ISSUE TITLE
[pickers] Is there a way to add a custom header to the digital clock segment?

### ISSUE THREAD

**Issue by gabrielbuii** [mui/mui-x#10174]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Context 🔦

Is there a way to add a custom header for the digital clock segment in the DateTimePicker component? We received feedback from a few users who have mentioned they're having trouble distinguishing between the hour and minute columns. Essentially, we want to add a label above the hours and minutes.

**Comment by LukasTy** [comment]
Hello, have you tried [customizing the layout](https://mui.com/x/react-date-pickers/custom-layout/#dom-customization)?
Based on your use case, it might help you solve what you want. Essentially, you'd need to inject a component that you want right before the `{content}`.
If you only need it on the `desktop` picker variant, you should be able to achieve it using the `wrapperVariant` prop.
If you are using only the desktop variant of the picker and do not need the toolbar, you might try passing a custom component to that slot, although, such a solution is more hacky. 🤔

**Comment by gabrielbuii** [comment]
Ah, this sounds like a perfect solution for us! Thanks! We can close this issue:)
