### ISSUE TITLE
[datagrid] Recipe for extending GridApi with custom functionality

### ISSUE THREAD

**Issue by lauri865** [mui/mui-x#10198]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We make extensive use of the GridApi in our application, and have over time added custom methods to control the datagrid state (controlling anything from rowHeight to expansion level to toggling the totals row). We have found it convenient to place this functionality within the apiRef to make it available within custom and default Datagrid components. Maybe in some cases it would be also preferable for developers to override default methods.

### Examples 🌈

```typescript
const apiRef = useGridApiRef();

const [defaultRowHeight, setDefaultRowHeight] = useState<number | "auto">(rowHeight)
apiRef.current.setDefaultRowHeight = setDefaultRowHeight;

// apiRef properties seem to get reset on the first mount of datagrid, so we need to set them again after the initial mount to make them available
useLayoutEffect(()=>{
    apiRef.current.setDefaultRowHeight = setDefaultRowHeight;
}, []);

<DatagridPremium
    ...
    apiRef={apiRef} 
    ....
/>
``` 

### Motivation 🔦

I realize what we're doing may be a little hack-y, so it would be great to have an officially supported recipe for extending the apiRef in order for our custom implementations not to get broken randomly by future updates.

**Comment by MBilalShafi** [comment]
I am not sure if I understand the motivation behind extending the GridApi.
Is it,
1. To extend the API by adding custom methods which you can later access using `apiRef.current.customMethod` or
2. To override the internal API methods added by the grid

For 1, you could simply use the custom methods wherever needed without adding them to the `apiRef`.
For 2, it is not recommended as it may cause the grid to behave unexpectedly if factory methods are overridden improperly, you are provided with exposed props where it makes sense for the developers to override the methods via `slotProps` or component props in general.

Therefore, if you could expand more about the motivation, we may be able to assist you better.

Thanks
