### ISSUE TITLE
How do I update the logic of DataGrid X column to autosize to the size of the header text if it is larger than the column?[question] 

### ISSUE THREAD

**Issue by mkgoluba** [mui/mui-x#10225]
### Order ID or Support key 💳 (optional)

d73a68cb85237b9a8e97949809b901a5Tz01NjgwMSxFPTE3MDM5MTQ0NDA5MTcsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI=

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am using Material UI X DataGrid within my application and we are looking to do the following.

In a few of the DataGrids that we have created the text within the column header is longer than the column width so it does not show the column header text until we resize or set column initial width

As default, we need to update the logic of the DataGrid so that the column width is autosized to the size of the header text if it is larger than the column.

We are having difficulty finding the best way to do this. 

Could you please recommend the best way to go about this so that we don't have to set column initial width each time?

Is there a way to do this using the DataGrid API to do what I am expecting or a documented way to do this?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Does something like https://github.com/mui/mui-x/issues/1241 would work for you?

**Comment by MBilalShafi** [comment]
Not sure about an exact ETA, but since it's already in progress, I am guessing, it should land by the end of Q3 or early Q4.

**Comment by MBilalShafi** [comment]
Please subscribe to the linked issue if you want to follow along with the updates, I'll close this one to keep things from scattering in too many issues.
