### ISSUE TITLE
[question] Tree data - error if rows is empty array

### ISSUE THREAD

**Issue by Ol-Boiko** [mui/mui-x#10228]
### Order ID or Support key 💳 (optional)

-

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm using tree data and server side filtering, sorting. If there is no items after user implements filtering and rows=[] there is an error: MUI: No getTreeDataPath given.
![MicrosoftTeams-image (3)](https://github.com/mui/mui-x/assets/118899912/bdfb2b19-3a4b-48f9-98f7-c244d4983ac4)

Expected result - if rows=[] should render my component which I send to slots={{ noRowsOverlay: noData}}

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by Ol-Boiko** [comment]
Hi DanailH! Thank for replying! While I was trying to reproduce it in codesandbox, I saw that my error was because of my wrong actions. There is no error in Grid with accepting an empty array and drawing a component. The issue is resolved and can be closed
