### ISSUE TITLE
[ charts ] - pie center slot to display text in the middle of a pie chart

### ISSUE THREAD

**Issue by giladappsforce** [mui/mui-x#10222]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

piechart should have a slot for pieCenter and slotProps that have pieCenterLabel and other text props

### Examples 🌈

![Screenshot 2023-09-04 at 15 04 12](https://github.com/mui/mui-x/assets/114646525/125f5e06-6a8c-4d46-9a60-f48b5e9a6bab)

### Motivation 🔦

I'm currently building a BI screen for my company and want to display a pie chart with text inside :D

**Comment by LukasTy** [comment]
Closing as completed via https://github.com/mui/mui-x/pull/10220

**Comment by ievgen-klymenko-uvoteam** [comment]
I think this was unfinished yes?

It mark as `completed`,
but I try as in his image:
```
    slotProps: {
      pieCenter: {
        pieCenterLabel: 'AaaaFFAFFAFffff',
      },
```

not work :|

I am use last version of package. ^7.13.0
