### ISSUE TITLE
[question] in DataGrid how to highlight both the row and the master detail when hovering on any of them

### ISSUE THREAD

**Issue by GlutVonSmark** [mui/mui-x#10237]
### Order ID or Support key 💳 (optional)

54954

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have expandable rows in our table (master detail).

When we hover the row we need background-color to change also on the master details part 
and in reverse when we hover over master detail we want the row to also have the background-color changing

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hmm, that is an interesting one. I don't think there is an OOTB way to do this. This https://github.com/mui/mui-x/issues/9882 can be a good start but you would need to change/add styles to the master-detail conditinally. The thing is that there isn't an `onRowHover` prop on the grid. To do that you would need to pass your custom prop using the `componentsProp` prop. Something like this:
```
<DataGrid
  componentsProps={{
    row: { onMouseOver: handleRowOver },
  }}
/>;
```

**Comment by GlutVonSmark** [comment]
was wondering...is it possible to extract from the DataGrid the row currently being hovered over?

**Comment by MBilalShafi** [comment]
> is it possible to extract from the DataGrid the row currently being hovered over?

Isn't the solution posted above by @DanailH working for you? I think it should do the same!
