### ISSUE TITLE
[TreeView] Drag Drop 

### ISSUE THREAD

**Issue by s-iliyas** [mui/mui-x#10231]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We have Tree View Component which does what it should do and I love mui to make everything easy for me.

But I request you add drag drop of tree items as sorting or to other tree view.

### Examples 🌈

Best example:
https://ant.design/components/tree#components-tree-demo-draggable:~:text=TypeScript-,JavaScript,-import%20%7B%20Tree
Good Example:
https://www.grapecity.com/wijmo/demos/Nav/TreeView/Nodes/DragandDrop/react#:~:text=Drag%20and%20Drop%20(React)

ABove link has good example

**Comment by oliviertassinari** [comment]
Duplicate of #9686?

**Comment by s-iliyas** [comment]
@oliviertassinari Yes it is.
