### ISSUE TITLE
[TreeView] Add prop to TreeView component to control focused node

### ISSUE THREAD

**Issue by acherkashin** [mui/mui-x#10236]
Thank you for your work, guys! It makes my life much easier! 👍  

- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I would want to add a prop to TreeView to be able to set the currently focused node.  For example, we could have controlled `focusedNodeId` property which will control the currently focused node. 

Othewise, we could use [useImperativeHandler](https://reactjs.org/docs/hooks-reference.html#useimperativehandle) to expose `focus` method which is declared in `TreeView` control.

![image](https://user-images.githubusercontent.com/9947582/140026786-0799e220-00fa-40bf-bb45-4a9dc398e5cb.png)

## Motivation 🔦

We have the following use case. We have a drop-down and when you press "arrow down" inside a text box we show a tree view and the first node should be selected. Currently we select node via in following way `querySelect('...').focus()`, but it is not a react way.

**Comment by jasonterando** [comment]
+1 - Use case:  I have a button to add an item to treeview, would like to focus the item when added.  I've tried using `TreeView.selected` but it does not perform a focus.

**Comment by noraleonte** [comment]
Hey, @acherkashin @stuartrowe @jasonterando 👋 

Would exposing a method that allows you to set the focus on a specific node of the tree view solve your problem? We are considering implementing that as a solution, instead of exposing a `focusedNode` prop on the tree view to control the focus state.

The DX could look something like:

```js
const handleFocusChange=(nodeId)=>{
   // my behavior
   apiRef.current.setFocusedNode(nodeId)
}
```

**Comment by jasonterando** [comment]
> Hey, @acherkashin @stuartrowe @jasonterando 👋
> 
> Would exposing a method that allows you to set the focus on a specific node of the tree view solve your problem? We are considering implementing that as a solution, instead of exposing a `focusedNode` prop on the tree view to control the focus state.
> 
> The DX could look something like:
> 
> ```js
> const handleFocusChange=(nodeId)=>{
>    // my behavior
>    apiRef.current.setFocusedNode(nodeId)
> }
> ```

Yep, in my case, it would be helpful.  When manipulating the tree (duplicate node, add node, etc.) being able to explicitly set the focus would be helpful.  For the moment, I've fallen back to using select and managing that on click events (with multi-select false) as a workaround

**Comment by stuartrowe** [comment]
> Hey, @acherkashin @stuartrowe @jasonterando 👋
> 
> Would exposing a method that allows you to set the focus on a specific node of the tree view solve your problem? We are considering implementing that as a solution, instead of exposing a `focusedNode` prop on the tree view to control the focus state.
> 
> The DX could look something like:
> 
> ```js
> const handleFocusChange=(nodeId)=>{
>    // my behavior
>    apiRef.current.setFocusedNode(nodeId)
> }
> ```

I think that would be fine in our case too.
