### ISSUE TITLE
[DataGrid]: Select in datagrid cell is not accessible/searchable on first click

### ISSUE THREAD

**Issue by vishal-kadmos** [mui/mui-x#10247]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/affectionate-herschel-f6v7yq?file=/Demo.tsx

Steps:
1. Column named `Country` is rendered as expected with `renderCell`
2. Click on one of the select & hit keyboard to search for country say `USA`
3. Dropdown will not show searched/matched result highlighted. 
4. Close the select & open it again to search some country. Select component will highlights matched result.

Also tried with single select of cell example (_in sandbox demo_). Select works as expected if used outside grid cell. so assumption is it is happening due to grid cell click not making cell editable on single click
but after making cell editable on single click, issue still persist & warning is thrown as 

```
MUI: You have provided an out-of-range value `u` for the select component.
Consider providing a value that matches one of the available options or ''.
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.3.1
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.0.0/bin/yarn
    npm: 9.8.1 - ~/code/customer-portal/node_modules/.bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Edge: Not Found
    Firefox: 116.0.3
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.11
    @mui/core-downloads-tracker:  5.14.5
    @mui/material: ^5.14.5 => 5.14.5
    @mui/private-theming:  5.14.5
    @mui/styled-engine-sc: ^5.12.0 => 5.12.0
    @mui/system:  5.14.5
    @mui/types:  7.2.4
    @mui/utils:  5.14.5
    @mui/x-data-grid:  6.11.2
    @mui/x-data-grid-pro: ^6.11.2 => 6.11.2
    @mui/x-date-pickers:  6.11.2
    @mui/x-date-pickers-pro: ^6.11.2 => 6.11.2
    @mui/x-license-pro:  6.10.2
    @types/react: ^18.2.20 => 18.2.20
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^6.0.7 => 6.0.7
    typescript: ^5.1.6 => 5.1.6

```
</details>

### Order ID or Support key 💳 (optional)

52198

Help highly appreciated! thank you

**Comment by DanailH** [comment]
Hi @vishal-kadmos I think the problem occurs because you are using selects on both edit and normal cell mode so once you click on a cell you are not actually entering edit mode but you activate the normal `renderCell` select. The problem with this is that the focus is not on the select but on the grid cell. I would suggest you not use the select in the renderCell but utilize the editing API the grid has. Also when you use the `singleSelect` column type you can pass in `valueOptions` and use the built-in select of the grid and customize it to your preference.
