### ISSUE TITLE
MUI Pro plan, Pricing past 10 developers confusion

### ISSUE THREAD

**Issue by Arno-Sympower** [mui/mui-x#10244]
### Order ID or Support key 💳 (optional)

11111

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

At the pro plan It mentions:
"No additional fee beyond 10 devs."

Since there is no fee other than the $15 p/m/d, does that mean It's capped at 10 devs and free for more devs? Or does It just mention It so we don't have to expect extra cost beyond $15 for bigger / growing companies?

Also, we wonder a bit If we create a lock-in situation when MUI start to increase the pricing over time. Are there any pricing guarantees? 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

``` 
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here. 
```
</details>

**Comment by DanailH** [comment]
Hi @Arno-Sympower thanks for asking this. Unfortunately, this is not the right place to ask this as we use GitHub for triaging technical problems. IF you have a question related to the license or the pricing in general you can submit a request here: https://support.mui.com/hc/en-us/requests/new?tf_360023797420=mui_x
