### ISSUE TITLE
mui X date and time picker

### ISSUE THREAD

**Issue by martindevaprasad** [mui/mui-x#10249]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

I am trying to use the date and timepicker using MUI X but it is not working as expected. I thinks importing the demoContainer in not working

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
`DemoContainer` and `DemoItem` are components for our documentation demos.
You should never use them in your own codebase.
Closing the issue.
If you are still having problems, please provide a more detailed explanation and preferably a live reproduction example of the problem you are having. 🙏
