### ISSUE TITLE
[StaticDatePicker] Setting defaultCalendarMonth results in all MuiPickersDay outside that month to be missing

### ISSUE THREAD

**Issue by gurtajkhatra** [mui/mui-x#10246]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Version "@mui/x-date-pickers" - 6.12.1

I'm trying to use the `defaultCalendarMonth` prop to set the month to open my `StaticDatePicker` to - it successfully opens to that month by every day in that month is missing in the picker.

This is the current component:
```
<LocalizationProvider dateAdapter={AdapterMoment} adapterLocale={localeCode}>
        <StaticDatePicker
          value={value}
          defaultCalendarMonth={moment('2023-11-05 12:00:00', 'YYYY-MM-DD HH:mm:ss')}
          onChange={onChange}
          disablePast
          shouldDisableDate={shouldDisableDate}
          timezone={timezone}
          onMonthChange={onMonthChange}
          minDate={moment(minDate)}
          maxDate={moment(maxDate)}
          views={['day']}
          view={'day'}
          slots={{
            // Hide some default components we don't use
            toolbar: () => (<div />),
            actionBar: () => (<div />),
            switchViewButton: () => (<div />),
            switchViewIcon: () => (<div />)
          }}
        />
      </LocalizationProvider>
```

### Current behavior 😯

Currently the StaticDatePicker opens up to the `defaultCalendarMonth` without any days being rendered in the view. If I inspect the HTML, the actual MuiPickersDay do not even exist

![image](https://github.com/mui/mui-x/assets/8953472/1b5256bc-c46f-424d-a2a0-10b3fb6080e6)

### Expected behavior 🤔

I'm expecting to have all the MuiPickersDay at least visible in the UI

**Comment by SiarheiLazakovich** [comment]
I have same issue.
playground: https://codesandbox.io/s/dank-water-h9kjsd?file=/Demo.tsx
issues: partial display of the calendar and calendar show July instead September.
<img width="1340" alt="image" src="https://github.com/mui/mui-x/assets/10497370/9828995c-162c-4d7c-b6bf-5c8127aec30e">

**Comment by flaviendelangle** [comment]
Hi,

Thanks for your reproduction case!
We seem to have some timezone problem, and `dayjs` have a weird behavior where `value.startOf('month').startOf('month')` returns the previous month for UTC (`dayjs.tz('2023-09-01', 'UTC').startOf('month').startOf('month')` returns 1st of August).

**Comment by flaviendelangle** [comment]
For @gurtajkhatra, you are passing a `timezone` prop without following [the steps to make moment work with timezones](https://mui.com/x/react-date-pickers/timezone/#moment-and-timezone).
Not sure it causes your problem, but it's something you should adress.

And as Lukas said, we will need a reproduction case to help more.

**Comment by SiarheiLazakovich** [comment]
Hello @flaviendelangle,

I wanted to express my gratitude for your prompt response.

It appears that the issue has been reproduced for any IANA timezone where STD/DST is set to +00:00.
new playground with this issue: https://codesandbox.io/s/trusting-euler-4f7y3g?file=/Demo.tsx

Thank you once again for your assistance.

**Comment by flaviendelangle** [comment]
I suspect that it is related to #9653
I will have a look

**Comment by flaviendelangle** [comment]
I can confirm you that it is caused by https://github.com/iamkun/dayjs/issues/2373

If you can use `UTC` instead, it's great.
Otherwise, I would suggest you to upvote and comment the `dayjs` issue because I don't see any possible workaround on our side :/
