### ISSUE TITLE
No row with id #undefined found

### ISSUE THREAD

**Issue by gregs-corespaces** [mui/mui-x#10256]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

 "@mui/x-data-grid-premium": "6.12.1",
* Grid state has row grouping applied 
* GridColDef has custom filterOperator using the wrapped example for string type to obtain string value from the object graph.

### Current behavior 😯

When setting a value for this filter, following error received.

```
No row with id #undefined found
    at http://localhost:3000/static/js/bundle.js:404717:13
    at Object.getCellValue (http://localhost:3000/static/js/bundle.js:404778:31)
    at Object.getCellParams (http://localhost:3000/static/js/bundle.js:404737:34)
    at Object.fn (http://localhost:3000/static/js/bundle.js:401322:37)
    at filterItem2 (eval at buildAggregatedFilterItemsApplier (http://localhost:3000/static/js/bundle.js:401377:22), <anonymous>:8:25)
    at isRowMatchingFilters (http://localhost:3000/static/js/bundle.js:401474:102)
    at filterTreeNode (http://localhost:3000/static/js/bundle.js:377928:7)
    at filterRowTreeFromGroupingColumns (http://localhost:3000/static/js/bundle.js:377963:7)
    at http://localhost:3000/static/js/bundle.js:378407:99
    at Object.applyStrategyProcessor (http://localhost:3000/static/js/bundle.js:396396:12)
```
Appears to be a problem where the generated rowId for the grouped column is attempted to be used to lookup the row...  Error does not occur when the grouping removed OR, if the custom filterOperator is replaced with valueGetter.

### Expected behavior 🤔

previously, using  "@mui/x-data-grid-premium": "6.5.0", filtering was applied correctly without error.

### Context 🔦

attempting to upgrade from "@mui/x-data-grid-premium": "6.5.0" to "@mui/x-data-grid-premium": "6.12.1".  Am currently exploring if the workaround to use valueGetter is viable but since this appears to be a regression, am logging here.

### Order ID or Support key 💳 (optional)
73731

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!

**Comment by TiagoPortfolio** [comment]
@gregs-corespaces, I am having the same issue, did you manage to fix it?

**Comment by tnoetzel** [comment]
In my case, this was related to having aggregation turned on... seems like the aggregation "row" has an undefined ID?

**Comment by tnoetzel** [comment]
@romgrk - Possible to reopen this. [Here's a reproducible example](https://codesandbox.io/s/mui-filter-issue-vx5jd8?file=/movies.js).

Just filter on director...

**Comment by tnoetzel** [comment]
@romgrk - Bumping this
