### ISSUE TITLE
NPM error while installation

### ISSUE THREAD

**Issue by Karthikeya0189** [mui/mui-x#10266]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.run npm install

### Current behavior 😯

npm install is exiting with an error 407.

Error: 407 authenticationrequired - GET https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view

### Expected behavior 🤔

Successful installation

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates https://github.com/mui/material-ui/issues/38819

It will be solved on the core next release (on Monday / Tuesday).
Sorry for the inconvenience, until then I advise you to stay on the alpha.142 of the lab.
