### ISSUE TITLE
[MUIX Data Grid] Style Data Grid Footer Rows Per Page Menu Background and Text Color 

### ISSUE THREAD

**Issue by Muhammad-Sohail-AB** [mui/mui-x#10271]
### What's the problem? 🤔

I'd love to be able to customize the background and text colors of the rows per page menu under the paging section of the Datagrid Footer where you choose how many rows per page should be shown.

#### Examples
<DataGrid
        rows={rows}
        columns={columns}
        componentsProps={{
          basePopper: {
            sx: {
              "& .MuiPaper-root": { backgroundColor: "green" },
              "&.MuiDataGrid-menu .MuiPaper-root": { backgroundColor: "blue" }
// This is not working 
'& .MuiPaper-root MuiList-root': {
                  backgroundColor: 'orange',
                  padding: '2rem',
                },
            }
          }
        }}
      />

### Resources and benchmarks 🔗

Here is the code sandbox example to customize the style of the columns menu,. I'm trying to customize the footer rows per page menu but It is not working

https://codesandbox.io/s/datagrid-quick-start-forked-4lpjm?file=/src/App.tsx

**Comment by DanailH** [comment]
@Muhammad-Sohail-AB The grid uses the `TablePagination` component from the material-ui library internally so you can check how to customize that one here https://mui.com/material-ui/react-pagination/#table-pagination. In addition, you can check an example customization of the pagination here -> https://mui.com/x/react-data-grid/components/#pagination
