### ISSUE TITLE
[Datagrid] Focused cell causes row to shift by 1px if showCellVerticalBorder is enabled

### ISSUE THREAD

**Issue by lauri865** [mui/mui-x#10278]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/distracted-cartwright-7dxf55?file=/demo.tsx:940-962

Steps:
1. Focus on the first *non-pinned* cell of any row
2. Scroll right
3. When the virtualized column gets unmounted, the row shifts by 1px to the right

<img width="235" alt="Screenshot 2023-09-08 at 16 35 18" src="https://github.com/mui/mui-x/assets/3652743/76d59ea6-3ac0-44fd-9d51-9c5126daea05">

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by lauri865** [comment]
Simple fix would be to add `border: 0` to the focused cell that is kept mounted. In here:
https://github.com/mui/mui-x/blob/5dca1dfb5cec90ef057cdc9913d3a4f1a9bbee2d/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L338 
https://github.com/mui/mui-x/blob/5dca1dfb5cec90ef057cdc9913d3a4f1a9bbee2d/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L661

**Comment by gitstart-riptechnologies** [comment]
Would like to work on this

**Comment by gitstart** [comment]
would like to work on this.

**Comment by romgrk** [comment]
@gitstart Sure, you can open a draft PR whenever you want. Let us know if you need assistance.
