### ISSUE TITLE
restoreState does not respect columns sizes

### ISSUE THREAD

**Issue by joacub** [mui/mui-x#10309]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

restoreState does not respect columns sizes when having aggregations

### Current behavior 😯

columns size is been not respected in the restore state function.

### Expected behavior 🤔

columns size been respected when using function restoreState

### Context 🔦

muix

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) may be a good starting point. Thank you!
