### ISSUE TITLE
[charts] LineChart xAxis customization issue

### ISSUE THREAD

**Issue by abaspoor** [mui/mui-x#10303]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

`<LineChart
    xAxis={[
        {
            dataKey: "datetime",
            scaleType:'band',
        }
    ]}
    series={Object.keys(keyToLabel).map((key) => ({
        dataKey: key,
        label: keyToLabel[key],
        color: colors[key],
        showMark: true,
        yAxisKey: axis[key],
    }))}
    yAxis={[{ id: 'leftAxisId' }, { id: 'rightAxisId' }]}
    rightAxis="rightAxisId"
    dataset={MergedData}
    {...customize}
/>
`

i want rotate the text of xaxis 45 degree because my xaxis consist of datetime and its long string - to show better i want to rotate the text of x axis to 45 degree .. whats your solution ? thank you if u help me -- its for self development project - not for business

**Comment by giladappsforce** [comment]
I just encountered the exact same issue, I tried adjusting the xAxis slot props
```typescript
<LineChart
      xAxis={[{ data: [1, 2, 3, 5, 8, 10], slotProps: {
        axisTickLabel: {
          rotate: '30deg'
        }
      } }]}
      series={[
        {
          data: [2, 5.5, 2, 8.5, 1.5, 5],
        },
      ]}
      width={1000}
      height={300}
    />
```
But the propagation isn't working properly,
I can apply the same transformation to the parent slotprops:
```typescript
<LineChart
      xAxis={[{ data: [1, 2, 3, 5, 8, 10] }]}
      slotProps={{
        axisTickLabel: {
          sx: {
            rotate: '45deg'
          }
        }
      }}
      series={[
        {
          data: [2, 5.5, 2, 8.5, 1.5, 5],
        },
      ]}
      width={1000}
      height={300}
    />
``` 
But that style is applied to all axis labels and not just the xAxis one


![Screenshot 2023-09-11 at 13 39 03](https://github.com/mui/mui-x/assets/114646525/d36a161a-0882-4877-b403-0f53c556570e)

**Comment by noraleonte** [comment]
Hey, @abaspoor 👋 

Thanks for opening this! 
I am not entirely sure that this is the best approach, but one possible solution I see for this problem is to try and target the `tickLabel`s that are specifically located within the `MuiChartsAxis-directionX`, something like that: 

``` jsx
 <LineChart
      xAxis={[{ data: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }]}
      series={[
        {
          data: [2, 3, 5.5, 8.5, 1.5, 5, 1, 4, 3, 8],
          showMark: ({ index }) => index % 2 === 0
        }
      ]}
      width={500}
      height={300}
      sx={{
        "& .MuiChartsAxis-directionX": {
          "& .MuiChartsAxis-tickLabel": {
            rotate: "45deg"
          }
        }
      }}
    />
```

You can also check out the [API docs of the `ChartsAxis` component](https://mui.com/x/api/charts/charts-axis), because all the css class names that are available are listed there. Let me know if this helps 🤞

**Comment by abaspoor** [comment]
> 

Hi, Thank you my friend, yeah it rotate both yaxis and xaxis ticklabel , 
I’m trying to rotate just xaxis

**Comment by abaspoor** [comment]
hi , [noraleonte](https://github.com/noraleonte)

thanks it works appreciate

**Comment by xiang-1603** [comment]
items
: 
1
: 
0
2
: 
0
3
: 
0
4
: 
0
5
: 
0
6
: 
0
7
: 
0
8
: 
0
9
: 
0
10
: 
0
11
: 
0
12
: 
0
13
: 
0
14
: 
0
15
: 
0
16
: 
0
17
: 
0
18
: 
0
19
: 
0
20
: 
0
21
: 
0
22
: 
0
23
: 
0
24
: 
0
25
: 
0
26
: 
0
27
: 
0
28
: 
0
29
: 
0
30
: 
0
31
: 
0

I used on linechart but why start from 0, not 1 in xAxios.
What is solution? thank you

**Comment by nisidazza** [comment]
Hello, maybe someone here can help me with another customization issue:

The first image is my chart, the second what I am trying to achieve: adding some space between the axis line and the tick label.

![Image](https://github.com/user-attachments/assets/8f97ec4a-0228-4a83-ab21-40232c90935f)

![Image](https://github.com/user-attachments/assets/b90a0e90-401d-4c13-9ca5-16873fa724ef)

I have been trying different css classes but even if I was able to target a specific element my changes weren't applied. 

Help!! X(
