### ISSUE TITLE
[DataGrid] Columns with flex properties do not reflow for printing

### ISSUE THREAD

**Issue by ascagnelli-withluminary** [mui/mui-x#10304]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/nervous-joliot-9t9cxd?file=/Demo.tsx

Steps:

1. Create a `DataGrid`
1. Assign one or more column definitions a `flex` property greater than zero.
2. Trigger the "export to print" function (either via toolbar or via the `useGridApiRef` hook)
3. Resize the window, and note how the column widths when triggering "export to print" reflect the current width of the window.

Sample generated PDFs:

[wide-window.pdf](https://github.com/mui/material-ui/files/12562192/wide-window.pdf)

[medium-window.pdf](https://github.com/mui/material-ui/files/12562193/medium-window.pdf)

[narrow-window.pdf](https://github.com/mui/material-ui/files/12562195/narrow-window.pdf)

### Current behavior 😯

The rendered column widths match the underlying widths on the screen.

### Expected behavior 🤔

The column widths should reflow to the paper's viewport width.

### Context 🔦

This was found when attempting to create a table that would fill its viewport on screens while the user is also able to generate a printed copy.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.5.1
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: Not Found
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.9.3 => 11.10.5 
    @mui/base:  5.0.0-beta.4 
    @mui/core-downloads-tracker:  5.14.5 
    @mui/lab: ^5.0.0-alpha.134 => 5.0.0-alpha.134 
    @mui/material: ^5.14.5 => 5.14.5 
    @mui/private-theming:  5.14.5 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.14.5 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.5 
    @mui/x-data-grid:  6.9.1 
    @mui/x-data-grid-pro: ^6.9.1 => 6.9.1 
    @mui/x-date-pickers: ^5.0.15 => 5.0.15 
    @mui/x-license-pro: ^6.0.4 => 6.9.0 
    @types/react: 18.0.33 => 18.0.33 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 

```
</details>
Browsers tested: Chrome 116.0.5845.110, Safari Version 16.6 (18615.3.12.11.2)

**Comment by romgrk** [comment]
@cherniavskii Forgot to answer this one last week, could you take a look? I haven't looked at the printing code yet.

**Comment by cherniavskii** [comment]
Hi @ascagnelli-withluminary 
The data grid needs JS to resize the columns when the grid size changes.
As far as I can tell, running JS in the print window is not possible.
The measuring and resizing need to be done in advance, but we need to know the print window size.

This is the limitation of Print Export, at least its current implementation. I'm not sure we can overcome this somehow.

**Comment by budiirawan-pp** [comment]
@cherniavskii is there a workaround in the recent version? I attempt to show all table columns in the printing.
