### ISSUE TITLE
[DataGrid] Option to include all rows in csv export

### ISSUE THREAD

**Issue by austv99** [mui/mui-x#10314]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently when a csv is exported for the data grid, only the highlighted rows will be exported. Can there be a property in the `GridCsvExportOptions` interface that will allow for all rows to be included regardless of highlighted rows?

### Motivation 🔦

User may be confused that an exported csv only includes some rows without knowledge that it only exports the highlighted rows

**Comment by flaviendelangle** [comment]
We have a [doc section](https://mui.com/x/react-data-grid/export/#exported-rows) showing you a few selectors you might want to use for the export.
