### ISSUE TITLE
Renew my MUI license

### ISSUE THREAD

**Issue by niharullal-bain** [mui/mui-x#10323]
I have a MUI X Pro license that expired about 2 weeks ago and was wondering how to go about renewing it? Here is my order number: 
49936

Thanks,

Nihar Ullal

**Comment by joserodolfofreitas** [comment]
Hi @niharullal-bain, usually you should have received an email with the instructions to renew it; it may be in your spam folder.
Otherwise, you can directly go to https://mui.com/store/items/mui-x-pro/ to get a new license.

I hope this helps.
