### ISSUE TITLE
[question] When using gridDetailPanelExpandedRowIdsSelector in the valueGetter of a GridCol I get a type missmatch (GridStateCommunity is not assignable to GridStatePro)

### ISSUE THREAD

**Issue by StefanMeindlDatenKraft** [mui/mui-x#10331]
### Order ID

73709

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Here are my imports 

```
import {
  DataGridPremium,
  GridAggregationFunction,
  GridColDef,
  gridDetailPanelExpandedRowIdsSelector,
  gridDetailPanelExpandedRowsContentCacheSelector,
  GridPagination,
  GridPaginationModel,
  GridRenderCellParams,
  GridRowParams,
  GRID_AGGREGATION_FUNCTIONS,
  GRID_DETAIL_PANEL_TOGGLE_FIELD,
  useGridApiRef,
  useGridSelector,
  useKeepGroupedColumnsHidden
} from '@mui/x-data-grid-premium'
```

And here is the definition of my col:

```
  const columns: GridColDef[] = [
    ...,
    {
      field: GRID_DETAIL_PANEL_TOGGLE_FIELD,
      headerName: t('listPage.table.date') || 'Date',
      type: 'string',
      width: 300,
      valueGetter: (params) => {
        const expandedRowIds = gridDetailPanelExpandedRowIdsSelector(params.api.state)
        return expandedRowIds.includes(params.id)
      },
      renderCell: (params) => {
        return (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <CustomDetailPanelToggle id={params.id} value={params.value} /> <p>{params.row.date}</p>
          </Box>
        )
      }
    },
    ...
```

Diagnostics:
`Argument of type 'GridStateCommunity' is not assignable to parameter of type 'GridStatePro'. Type 'GridStateCommunity' is missing the following properties from type 'GridStatePro': columnReorder, columnResize, pinnedColumns, detailPanel [typescript] [2345]`

### Your environment 🌎

  System:
    OS: Linux 5.15 Alpine Linux
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.10.5 => 11.11.1 
    @emotion/styled: ^11.10.5 => 11.11.0 
    @mui/base:  5.0.0-beta.14 
    @mui/core-downloads-tracker:  5.14.8 
    @mui/icons-material: ^5.14.8 => 5.14.8 
    @mui/lab: ^5.0.0-alpha.143 => 5.0.0-alpha.143 
    @mui/material: ^5.14.8 => 5.14.8 
    @mui/private-theming:  5.14.8 
    @mui/styled-engine:  5.14.8 
    @mui/system: 5.14.8 => 5.14.8 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.8 
    @mui/x-data-grid: ^6.12.1 => 6.12.1 
    @mui/x-data-grid-premium: ^6.12.1 => 6.12.1 
    @mui/x-data-grid-pro: ^6.12.1 => 6.12.1 
    @mui/x-date-pickers: ^6.12.1 => 6.13.0 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.0 
    @types/react: ^18.0.26 => 18.2.18 
    react: ^18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.9.4 => 4.9.5 

I use Chromium but i guess that does not matter in this case

**Comment by romgrk** [comment]
We don't parametrize `GridColDef` with the grid state, but if you're using the premium package it's always safe to cast the state to `GridState` which you can import under that name from any of the community/pro/premium packages.

**Comment by flaviendelangle** [comment]
We recommend passing the `api` object directly:

```diff
-const expandedRowIds = gridDetailPanelExpandedRowIdsSelector(params.api.state)
+const expandedRowIds = gridDetailPanelExpandedRowIdsSelector(params.api)
```

I'd be curious to see if TS still complains.

**Comment by StefanMeindlDatenKraft** [comment]
> We recommend passing the `api` object directly:
> 
> ```diff
> -const expandedRowIds = gridDetailPanelExpandedRowIdsSelector(params.api.state)
> +const expandedRowIds = gridDetailPanelExpandedRowIdsSelector(params.api)
> ```
> 
> I'd be curious to see if TS still complains.

Yeah this produces the same error as before `Argument of type 'GridStateCommunity' is not assignable to parameter of type 'GridStatePro'.` But when i import GridState from the premium package and cast params.api.state it works `gridDetailPanelExpandedRowIdsSelector(params.api.state as GridState)`
