### ISSUE TITLE
[core] Improve GitHub template

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#10340]
As of today, creating a new issue leads to an annoying doubleheader, it takes vertical space that readers can skip.

<img width="426" alt="Screenshot 2023-09-14 at 19 47 59" src="https://github.com/mui/mui-x/assets/3165635/222e97d1-6233-4762-a407-20480b0af207">

What if we replaced this for a single header?

See how the lighthouse feels better: https://github.com/GoogleChrome/lighthouse/issues/15450.

<img width="581" alt="Screenshot 2023-09-14 at 19 49 10" src="https://github.com/mui/mui-x/assets/3165635/b950f486-a3d0-4361-9ac4-37d2c4d9cfe3">

I have seen Toolpad (@Janpot can't find which issue again) complain about this as well, so feels like we might  be able to improve this for the whole MUI org.

**Comment by romgrk** [comment]
I had proposed to remove the sections altogether with a bot that would run right after the issue is opened, I don't like the noise.

**Comment by oliviertassinari** [comment]
https://www.notion.so/mui-org/Github-Action-to-remove-issue-template-checkboxes-a1abe3824bf04bbf9dc62d876767fe92

**Comment by Janpot** [comment]
We could combine the headers as a short term solution and keep the notion page to shape a long term solution?

**Comment by romgrk** [comment]
It shouldn't be too long to write an action for that. I'll explore next week.

**Comment by romgrk** [comment]
Yes it was really trivial to write, see details in #10372.
