### ISSUE TITLE
[charts] Add a reference lines and areas component

### ISSUE THREAD

**Issue by wascou** [mui/mui-x#10351]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As a developper, I would like to have reference line and area components to easily help the reader of the chart to understand the data. 

### Examples 🌈

It can include the following examples:
- vertical and horizontal lines to materialize thresholds or limits
- areas to focus on or empty spaces
- reference data or curves

One of my example for a Scatter Chart:

![image](https://github.com/mui/mui-x/assets/807635/1e79d95f-c6ce-4e0d-891d-a0c4a16ca76d)

reCharts examples:

https://recharts.org/en-US/examples/LineChartWithReferenceLines
https://recharts.org/en-US/examples/LineChartNegativeValuesWithReferenceLines

### Motivation 🔦

Well it's a cool feature to integrate and not so difficult as there's not a lot of parameters. I did one for my project but I guess yours will be better.

**Comment by alexfauquette** [comment]
If you're building one, feel free to open a PR to add it in the library in a folder `packages/x-charts/src/ChartReferenceLine/` contributions are welcome

**Comment by wascou** [comment]
Ok, I can share my version. Any recommendations on contributing? guidelines? What about licensing?

**Comment by alexfauquette** [comment]
> What about licensing?

what is in `@mui/x-charts` is MIT license, so by contributing you accept the licence

> Any recommendations on contributing?

Not a lot:
- Ask in the issue if you have doubts or multiple ideas on the interface or edge case behavior to avoid discussing them after you start coding
- If you've already looked in the code base, each component has its own folder `packages/x-charts/src/<componentName>`

For more details on the pipelines, there is the [contributing](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md) file. But I can handle the scripts and other details

**Comment by alexfauquette** [comment]
Closing since the `ChartsReferenceLine` has been added

**Comment by josevsgeon** [comment]
what about reference area? like this: https://recharts.github.io/en-US/api/ReferenceArea/
in recharts, we can use it similar to reference line on almost any type of chart.

**Comment by alexfauquette** [comment]
@josevsgeon This issue is 2 years old. Could you open a new one explaining what is your usecase?
