### ISSUE TITLE
Unable to Use Local Characters (e.g., "İ", "Ş") in Material-UI DataGrid Filter

### ISSUE THREAD

**Issue by resatakks** [mui/mui-x#10377]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1.
2.
3.

### Context 🔦

I'm using Material-UI to create a DataGrid in my React-based application. However, I'm encountering an issue when trying to filter data using Turkish characters (e.g., "İ", "Ş").

Specifically, when attempting to filter data that contains Turkish characters, using uppercase "İ" or "Ş" letters for filtering doesn't work as expected, and I'm unable to get the desired results. It seems that the filtering process is not sensitive to Turkish characters.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by michelengelen** [comment]
closing this in favor of #10376
