### ISSUE TITLE
[Datagrid] RowIndexes are not stable, breaking memoization

### ISSUE THREAD

**Issue by lauri865** [mui/mui-x#10373]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. https://mui.com/x/react-data-grid/virtualization/
2. Focus first cell
3. Open inspector and scroll down, and notice how id and rowIndex get out of sync, and rowIndex for a particular rowId changes while you scroll.

### Current behavior 😯

When you scroll back up quickly, there's a whole bunch of rows that are forced to re-render, breaking memoization of them (essentially whatever hits the scrollable area gets reindex re-assigned on every single row being added back by virtulisation).

Caused by this PR: #7357 

### Expected behavior 🤔

RowIndexes should be kept intact regardless of whether the rows are kept in the DOM or not, the underlying data didn't change.

For inspiration, this is a good design for "sticky rows" virtualisation that doesn't manipulate indexes: https://tanstack.com/virtual/v3/docs/api/virtualizer#rangeextractor

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
No focused row in the DOM:
<img width="355" src="https://github.com/mui/mui-x/assets/13808724/b03438b0-c33a-4c7e-9f24-3987ac91b08d">

With focused row in the DOM:
<img width="349" src="https://github.com/mui/mui-x/assets/13808724/440ffbb3-3980-4a82-b8ff-39039eb3bf74">
> Notice the offset between `data-id` and `data-rowindex`.

@lauri865 Is this what you mean?

> When you scroll back up quickly, there's a whole bunch of rows that are forced to re-render,

I believe this only applies to a single row (the one that is focused). So it shouldn't impact performance much.

But yeah, there's no need to change the `data-rowindex` attribute for that row 👍🏻
