### ISSUE TITLE
Unable to Use Local Characters (e.g., "İ", "Ş") in Material-UI DataGrid Filter

### ISSUE THREAD

**Issue by resatakks** [mui/mui-x#10376]
- [X] I have searched the existing issues
- [X] I have tested the latest version

I'm using Material-UI to create a DataGrid in my React-based application. However, I'm encountering an issue when trying to filter data using Turkish characters (e.g., "İ", "Ş").

Specifically, when attempting to filter data that contains Turkish characters, using uppercase "İ" or "Ş" letters for filtering doesn't work as expected, and I'm unable to get the desired results. It seems that the filtering process is not sensitive to Turkish characters.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

Mui version 6.10

**Comment by cherniavskii** [comment]
Hi @resatakks 
I tried reproducing it using the demo from https://mui.com/x/react-data-grid/filtering/
It seems to work as expected:

<img width="544" src="https://github.com/mui/mui-x/assets/13808724/db9e51ff-34f0-43ea-843b-de1285edeb34">

Could you clarify the issue you're experiencing?

**Comment by resatakks** [comment]
Now after trying them all I realized
I don't have any problems with Turkish characters, even if I start the search with a capital I, there is no problem, but for example, I will search for the word "demir" or the word "DEMİR".
If I write IRON it definitely doesn't see it but this
If it was "İSMET" there would be no problem.
So if I use a capital I in the middle of the word, unfortunately it doesn't see it.
@cherniavskii  cherniavskii

> Hi @resatakks I tried reproducing it using the demo from https://mui.com/x/react-data-grid/filtering/ It seems to work as expected:
> 
> <img alt="" width="544" src="https://user-images.githubusercontent.com/13808724/268713196-db9e51ff-34f0-43ea-843b-de1285edeb34.png">
> Could you clarify the issue you're experiencing?

**Comment by cherniavskii** [comment]
Not sure I follow, could you demonstrate it in this demo https://codesandbox.io/s/pedantic-nash-73fnsl?file=/Demo.tsx?
Thanks!

**Comment by resatakks** [comment]
> Not sure I follow, could you demonstrate it in this demo https://codesandbox.io/s/pedantic-nash-73fnsl?file=/Demo.tsx? Thanks!
For example, let's say "DEMİR" is written in the row. If you search for "IRON" in the filter section, there is no problem, but if you search for "demir", it does not find it. Because in Turkish, if the lowercase i becomes larger, it turns into I, so the filter cannot see it. So, what I want to do is if there is "demir" in my records, put it in the filter with a capital letter. If I search for "DEMİR" you can see it, but if you try it this way you will see that it is not there. I am also a mui pro user, I really need the solution to this problem.

**Comment by resatakks** [comment]
> Could you check if what you describe is the same as #9817? There's a working demo in [#9817 (comment)](https://github.com/mui/mui-x/issues/9817#issuecomment-1658844963)


When I created a row and tried the solution in the topic you posted, I saw that my problem was solved.
https://codesandbox.io/s/quirky-sinoussi-hn97wj?file=/Demo.tsx:0-1487

But I have a request, I couldn't run it in my own component. I'm using a Class component.

I have a column structure like this

```
  <DataGridPro
      columns={this.props.config.columns}
```
      
I revised it as follows

   ```
 const columnsWithFilterOperators = this.props.config.columns.map((column) => {
      if (column.field === "text" && column.filterable !== false) {
        return {
          ...column,
          filterOperators: this.state.filterOperators.text, 
        };
      }
      return column;
    });


columns={columnsWithFilterOperators}
```

But for some reason it didn't work. I wrote the definitions etc. above, but I think I wrote the code in the column structure wrong. Can you help here?

**Comment by resatakks** [comment]
can u update? @cherniavskii

**Comment by cherniavskii** [comment]
If the column is of type `string`, you'll need to do this:

```ts
const columnsWithFilterOperators = this.props.config.columns.map((column) => {
 if (column.field === "text" && column.filterable !== false) {
   return {
     ...column,
     filterOperators: stringFilterOperators.map((operator) =>
       wrapFilterOperator(operator)
     ) 
   };
 }
 return column;
});
```

This is a workaround though, and I'm going to add support for this to the data grid soon.

**Comment by resatakks** [comment]
> If the column is of type `string`, you'll need to do this:
> 
> ```ts
> const columnsWithFilterOperators = this.props.config.columns.map((column) => {
>  if (column.field === "text" && column.filterable !== false) {
>    return {
>      ...column,
>      filterOperators: stringFilterOperators.map((operator) =>
>        wrapFilterOperator(operator)
>      ) 
>    };
>  }
>  return column;
> });
> ```
> 
> This is a workaround though, and I'm going to add support for this to the data grid soon.

Unfortunately it didn't work for me, I spent some time but it didn't work.

Thank you for your interest and effort, can you give an estimated date to add this to the table? It is really important for our business and I don't think we are the only ones experiencing this problem.
@cherniavskii

**Comment by cherniavskii** [comment]
@resatakks Sorry for the late reply, I've opened https://github.com/mui/mui-x/pull/10569 to address it
