### ISSUE TITLE
Detect "HappyDOM" in userAgent string in same way as "jsdom"

### ISSUE THREAD

**Issue by anthonyblond** [mui/mui-x#10374]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

**Summary**

Wherever there is code like `const isJSDOM = /jsdom/.test(window.navigator.userAgent);`, generalise it to use the `/jsdom|HappyDOM/` instead.

**Detail**

Currently there are several places in the code that have logic like the following (copied from `packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts`):

```
      // jsdom has no layout capabilities
      const isJSDOM = /jsdom/.test(window.navigator.userAgent);

      if (size.height === 0 && !errorShown.current && !props.autoHeight && !isJSDOM) {
        logger.error(
          [
            'The parent DOM element of the data grid has an empty height.',
            'Please make sure that this element has an intrinsic height.',
            'The grid displays with a height of 0px.',
            '',
            'More details: https://mui.com/r/x-data-grid-no-dimensions.',
          ].join('\n'),
        );
        errorShown.current = true;
      }
```

This relies on the jsdom testing environment using "Mozilla/5.0 (linux) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/{packageVersion}"  as its default userAgent string.

If using [vitest](https://vitest.dev/) with the default environment of [happy-dom](https://www.npmjs.com/package/happy-dom), instead, this won't work and the error is shown in tests.

[release v12.0.0.0](https://github.com/capricorn86/happy-dom/releases/tag/v12.0.0) of happy-dom has fixed an issue with its useragent string, and now uses "Mozilla/5.0 (X11; {process.platform} {process.arch}) AppleWebKit/537.36 (KHTML, like Gecko) HappyDOM/{packageVersion}" as its default. So changing the regex to `/jsdom|HappyDOM/` should be sufficient.

### Motivation 🔦

Make development of apps using mui-x (specifically in my case x-data-grid) with vite easier without workarounds.

I was going to just submit a simple PR specifically for `useGridDimensions.ts` in x-data-grid, but realised the same logic is used all across the library, so there might be a different pattern that needs to be implemented.

**Comment by cherniavskii** [comment]
I wonder if we can use the `process.env.NODE_ENV === 'test'` check instead.

But to be fair, I'm not even sure if this error is still necessary, as it seems like the grid works just fine if the parent doesn't have predefined dimensions set: https://codesandbox.io/s/amazing-nightingale-yl7c8s?file=/Demo.tsx

@mui/xgrid What do you think?

**Comment by romgrk** [comment]
That seems to be the only location in non-testing code where we check for jsdom. We should remove it.

![image](https://github.com/mui/mui-x/assets/1423607/44e6a8f6-ce8e-4495-89bc-a7a266ba5fcf)

**Comment by infantito** [comment]
I did a `patch-package` to the library, but setting the `environmentOptions` property is better.
