### ISSUE TITLE
[question] Is it possible to disable rowReordering for a single row

### ISSUE THREAD

**Issue by AlexCarlston** [mui/mui-x#10380]
### Order ID

73491

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello, I was wondering if it was possible to disable the drag and drop (rowReordering) for a single row. Specifically I would like the first two rows to not be draggable, and every row below it would be able to be drag and dropped.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @AlexCarlston 
Currently, it's not possible out of the box.

In most use cases reordering one row impacts the order of other rows, even if they cannot be reordered directly.
Could you provide more details about your use case?

**Comment by AlexCarlston** [comment]
Sorry for the rough diagram, the below picture is the use case. 

<img width="846" alt="Screenshot 2023-09-18 at 11 58 23 AM" src="https://github.com/mui/mui-x/assets/114952104/34ba4231-030f-4ada-ae46-bcdb475a0c5a">

**Comment by cherniavskii** [comment]
Could you clarify your expectations regarding rows that have reordering disabled?
Imagine that row 2 has reordering disabled, while rows 1 and 3 can be reordered:

<img width="174" src="https://github.com/mui/mui-x/assets/13808724/2811fb19-61eb-4ddd-820a-3e2908d2e79f">

What do you expect to happen when the user reorders row 3 and puts it between row 1 and row 2?

**Comment by AlexCarlston** [comment]
And in this example the icon would be remove for row 1 and 2

**Comment by MBilalShafi** [comment]
@AlexCarlston Just in case the rows you don't want to be dragged are always on top or bottom of the other rows, you could use [row pinning](https://mui.com/x/react-data-grid/row-pinning/), which disallows reordering for the rows that are pinned to top or bottom.

Here's an example: https://codesandbox.io/s/amazing-lovelace-swdghy?file=/Demo.tsx

**Comment by shboul1** [comment]
put this as a first column and change the if condition to match your case

import { GRID_REORDER_COL_DEF } from '@mui/x-data-grid-pro';

const columns = [
{
            ...GRID_REORDER_COL_DEF,
            renderCell: (params) => {
                if (params.row.id === 5) return null;
                return GRID_REORDER_COL_DEF.renderCell(params);
            },
 },
]
