### ISSUE TITLE
[datagrid] Multiple rows appear hovered at once

### ISSUE THREAD

**Issue by sandronominal** [mui/mui-x#10384]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
[screen recording](https://jam.dev/c/3d80da3e-3337-4ebd-9727-9f0cdb4ec7bc)
[code](https://codesandbox.io/s/bold-cookies-jgfs7v) and [preview](https://jgfs7v.csb.app/)

### Current behavior 😯

The DataGridPro's actions menu when clicked applies a `Mui-hovered` CSS class to that row. However, clicking on other row's menus also add the class without removing it from the previous row, leading to multiple rows with the Mui-hovered class. 

### Expected behavior 🤔

Clicking on other row's action menu should remove `Mui-hovered` from previous row.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

68065

**Comment by cherniavskii** [comment]
Thanks!
It's a bug indeed, I believe this PR solves it: https://github.com/mui/mui-x/pull/10252
