### ISSUE TITLE
DatePicker: Typescript error when trying to pass custom prop to slot component

### ISSUE THREAD

**Issue by oscar-b** [mui/mui-x#10389]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

```
<MuiDatePicker<DateTime>
	value={value}
	slots={{
		day: Highlight,
	}}
	slotProps={{
		day: {
			highlighted, // Type error
		}
	}}
/>
```

```
Type '{ highlighted: string[] | undefined; }' is not assignable to type 'SlotComponentProps<PickersDayComponent, {}, DayCalendarProps<DateTime> & { day: DateTime; selected: boolean; }> | undefined'.
  Object literal may only specify known properties, and 'highlighted' does not exist in type 'SlotComponentProps<PickersDayComponent, {}, DayCalendarProps<DateTime> & { day: DateTime; selected: boolean; }>'.
```

### Current behavior 😯

I get a type error trying to pass extra props to my custom Day component

### Expected behavior 🤔

A way to extend `SlotComponentProps`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Thank you for opening this issue! 🙏 
We already have it scheduled for grooming: https://github.com/mui/mui-x/issues/9775

In the meantime, I'm afraid that the only option that we can suggest is to use the `as any` or different way of casting the props to avoid the TS error. 😞
