### ISSUE TITLE
Mui-Data-Grid - Export Feature - If apply the filter on any column of table then export not working properly

### ISSUE THREAD

**Issue by raghu-aryan** [mui/mui-x#10387]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

```
How recreate the issue:

Steps:
1. Fetch all records and render on data-grid component.
2. Filter with any column till records, And unmount the filter component with click out side of filter.
3. Then Click to export button, And click on export in csv getting only 1 record.

```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  I am on mui/x-data-grid: 6.14.0
  I am using chrome 116.0.5845.188
```
</details>

**Comment by cherniavskii** [comment]
Hi @raghu-aryan 
Could you clarify what is the expected behavior?
Thanks!

**Comment by raghu-aryan** [comment]
Hi @cherniavskii,
Actually according to me.
Export the data which is rendered after apply the filter.

Thanks for replying

**Comment by cherniavskii** [comment]
It seems to behave exactly like you mentioned: https://codesandbox.io/s/lt9fzr?file=/Demo.tsx

<img width="1114" src="https://github.com/mui/mui-x/assets/13808724/3124e3de-e9cf-4556-b83d-90fa3302f46c">

Could you provide a minimal demo reproducing the issue?

**Comment by raghu-aryan** [comment]
```
Please try to export when records is more then 1 and filter has already applied.
That was seems in production mode mostly
```

**Comment by MBilalShafi** [comment]
Still working when the records are more than one and a filter is applied.

<img width="400" alt="image" src="https://github.com/mui/mui-x/assets/12609561/80b60220-c678-4317-9622-d655ec5aa06f">
<img width="400" alt="image" src="https://github.com/mui/mui-x/assets/12609561/b6ba9374-ab39-4830-927e-68f3a0876093">

As @cherniavskii said, we wouldn't be able to assist much unless you provide a minimal reproduction demo.
Let me know if that is possible.
