### ISSUE TITLE
Pro User - Unable to Set Different Heights for DataGrid Headers

### ISSUE THREAD

**Issue by Omrigotlieb** [mui/mui-x#10391]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am using the DataGrid component from MUI and I have a requirement to set different heights for the headers of the grid. However, I couldn't find a straightforward way to achieve this.

I tried using the headerClassName prop with the value 'my-super-theme--naming-group', but when I attempted to customize the height, it affected all the headers, not just the individual one I was targeting.

Expected Behavior:
I expect to have an option or a prop that allows me to easily set different heights for each header in the DataGrid without affecting all headers.

Current Behavior:
When I use the headerClassName prop and try to customize the height, it changes the height for all headers in the DataGrid, not just the specific one.

Steps to Reproduce:

Implement a DataGrid component.
Use the headerClassName prop with the value 'my-super-theme--naming-group'.
Try to set a different height for a specific header.
Observe that all headers' heights are affected.
Possible Solution:
Provide a prop or a CSS solution that allows users to specify the height of individual headers in the DataGrid without affecting the height of other headers.

![image](https://github.com/mui/mui-x/assets/26531194/b013fda5-05a9-4e3b-81a2-0cbf9ef6b425)
![image](https://github.com/mui/mui-x/assets/26531194/0d22ef6e-47f2-48a8-b901-b0339fb5c995)

**Comment by cherniavskii** [comment]
Hi @Omrigotlieb 
I believe the `columnHeaderHeight` prop is what you are looking for 🙂
It is mentioned in the [Density](https://mui.com/x/react-data-grid/accessibility/#density-prop) docs.
