### ISSUE TITLE
[DataGrid] Highlighting text when it changes in a cell

### ISSUE THREAD

**Issue by RazbezhkinAV** [mui/mui-x#10392]
### Order ID

70308

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a problem with the DataGrid
Cell `username` has an event for double-clicking. When the user double-clicks on the username cell, I set a new username.
But the new name is allocated as for copying.

One solution is to add a property ` user-select: none;` in my CSS file, but then the ability to highlight text is disabled, and I want to leave this function.

![image](https://github.com/mui/mui-x/assets/90248363/dbbdd0ec-1a5f-44e9-9fa4-9894196cb23d)

Example 
https://codesandbox.io/s/grid-mui-select-user-name-ywjpw7?file=/Demo.tsx:0-1214

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.31)

```
</details>

**Comment by cherniavskii** [comment]
I wasn't sure if it's possible to disable text selection on double click only, but then I found this answer on StackOverflow: https://stackoverflow.com/a/43321596
Seems to work with the data grid as well: https://codesandbox.io/s/grid-mui-select-user-name-forked-tlcq8h?file=/Demo.tsx

**Comment by RazbezhkinAV** [comment]
Thank you everything works as it should
