### ISSUE TITLE
Data grid- render table in master detail has "jumpy" behavior

### ISSUE THREAD

**Issue by barakgr-cyera** [mui/mui-x#10404]
### Order ID

67211

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm using data-grid premium and I want to render a table inside a table. 
The two tables have different columns and looks, and we figured out that the approach should be rendering the inner table using the “master detail” component (and not some sort of row grouping).

Our problem is that when expanding the outer-table row and opening the master detail (aka the inner table) we get a very “jumpy” behavior of the inner table. You know, first seeing only the headers and then the rest of the rows. We have all data in advance, there is no fetch happening. so it's only a matter of rendering..

If it matters: The cells contain not only text, but also contain logos/icons etc.

I can try and make a video of it later if it will be needed. Will just take more time because in order to post it here I'll need to create some mock anonymous data

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 13.5.1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: Not Found
    npm: 8.15.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: Not Found
    Safari: 16.6
```
</details>

**Comment by barakgr-cyera** [comment]
https://github.com/mui/mui-x/assets/97047211/1a41d49b-f87e-4480-aea3-6f096e3e8e22

**Comment by cherniavskii** [comment]
Hi @barakgr-cyera 
This looks bad indeed.
How many rows do the nested data grids render? Do you have virtualization disabled?

I cannot reproduce the issue with this demo: https://codesandbox.io/s/affectionate-danny-ddqrtq?file=/Demo.tsx

**Comment by barakgr-cyera** [comment]
Hi,
First I just want to say that the video was taken with throttling so the "jumps" will be seen easier, but it's not really slow.
We are rendering only 5 rows max.
Unfortunately I can't reproduce it on codesanbox (yes, I know you can't help much without it), but I did continue with research on my side:
I suspected redundant renders on my side, but I can't find them: In the component wrapping the inner table, if I render a simple text in div, it doesn't happen..
