### ISSUE TITLE
[DataGridPro] onRowSelectionModelChange resets resized columns

### ISSUE THREAD

**Issue by TheVamp** [mui/mui-x#10405]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/proud-waterfall-98gdjy

Steps:
1. alter width of columns
2. select one item in the list

### Current behavior 😯

the column width resets to the default value

### Expected behavior 🤔

the column width should stay as selected

### Context 🔦

I want to keep track of the selected items within the data grid and delete them at a later time. Therefore I used `onRowSelectionModelChange` to get selected items and store them in a state. 

To determine if I selected the correct rows for deletion, I need to resize the width in some cases. Selecting another item, will reset the column width and I need to resize the column again. It results in a bad user experience.

I tested this on the latest Firefox, Chromium and the latest mui-x version. I also tested this behavior in DataGridPro and DataGridPremium. In all instances it is the same as described above.

If this is an expected behavior, it might be useful to document this in the documentation, that the column width on resized objects should be tracked by the application via `onColumnWidthChange`.

Thanks for your help

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Linux 5.18 Fedora Linux 38 (Thirty Eight)
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 3.6.3 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Browsers:
    Chrome: Not Found
</details>

### Order ID or Support key 💳 (optional)

65779

**Comment by cherniavskii** [comment]
Hi @TheVamp 
It's not row selection that is causing the columns to reset, it's the fact that the `columns` array is recreated on each render.
When the reference changes, the grid resets the columns - this is expected behavior:

<img width="860" src="https://github.com/mui/mui-x/assets/13808724/9ae3b95b-6a72-4d8b-87cd-13eb8904495e">

In the demo you linked, moving `columns` outside of the component solves the issue: https://codesandbox.io/s/proud-waterfall-98gdjy?file=/Demo.tsx

**Comment by cherniavskii** [comment]
@DirKraft91 Yeah, this is more tricky. I've opened a proposal for this some time ago in https://github.com/mui/mui-x/pull/15041
What do you think about this?

**Comment by DirKraft91** [comment]
@cherniavskii looks good
