### ISSUE TITLE
What is the best way to customize styles for the DataGrid Filter panel

### ISSUE THREAD

**Issue by nessj1994** [mui/mui-x#10408]
### Order ID

70732

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am writing some custom filters with a date range for our data grid implementation. Because the date range uses multiple text fields it becomes too wide for the base width setting of the filter panel and causes some overflow scrolling. See the image below

![image](https://github.com/mui/mui-x/assets/9426931/e91a4761-195c-42cb-9bff-830bc16dd552)

I would like to alter the width of the panel to fit this without requiring my users to scroll.

Is there a way to customize this without going crazy and writing my own entire custom filter panel component just to customize the width styles? I saw some images in my search for an answer here in the issues where users had a very nice looking customization for theirs, but there wasn't any info on how they specifically achieved it.

Here is a quick screenshot of theirs image on that issue. 
![image](https://github.com/mui/mui-x/assets/9426931/7ff66c9c-8ae8-4a4a-9525-0f3854adae9a)

In this case I'm guessing they are potentially just making their own though given that it changes buttons styles and placements among other things. 

Thank you for any help that can be provided, even if it's as simple as telling me I have to make a custom component from scratch. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  
  Browser: Chrome version Version 116.0.5845.188
  
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1928.0), Chromium (117.0.2045.31)
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/base: ^5.0.0-alpha.91 => 5.0.0-alpha.91 
    @mui/core-downloads-tracker:  5.10.17
    @mui/icons-material: ^5.10.16 => 5.10.16
    @mui/material: ^5.8.6 => 5.10.17
    @mui/private-theming:  5.10.16
    @mui/styled-engine:  5.10.16
    @mui/system:  5.10.17
    @mui/types:  7.2.2
    @mui/utils:  5.10.16
    @mui/x-data-grid:  6.10.0
    @mui/x-data-grid-premium: ^6.10.0 => 6.10.0
    @mui/x-data-grid-pro:  6.10.0
    @mui/x-date-pickers: ^5.0.0 => 5.0.0
    @mui/x-license-pro:  6.10.0
    @types/react: ^18.0.15 => 18.0.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 5.1.6 => 5.1.6
```
</details>

**Comment by cherniavskii** [comment]
Hi @nessj1994
Could you try this demo? https://codesandbox.io/s/amazing-moon-lc9q58?file=/Demo.tsx
Is this what you are looking for?

**Comment by nessj1994** [comment]
> Hi @nessj1994 Could you try this demo? https://codesandbox.io/s/amazing-moon-lc9q58?file=/Demo.tsx Is this what you are looking for?

This does indeed accomplish my goal. Thank you very much.
