### ISSUE TITLE
[ DatagridPro : Question] : Its about Mui filtering column 

### ISSUE THREAD

**Issue by swathign-sbdinc** [mui/mui-x#10420]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://codesandbox.io/s/dawn-brook-8zgr3s?file=/demo.js
https://codesandbox.io/s/dawn-brook-8zgr3s?file=/demo.js

  **const nameArr = ["Automated", "Guided", "RoI"];
   const rows = [
    { id: 1, name: nameArr[0], quantity: 12, ppu: 35 },
    { id: 2, name: nameArr[1], quantity: 100, ppu: 42 },
    { id: 3, name: nameArr[2], quantity: 107, ppu: 45 }
  ];**

so here my question is i'm trying to filter the Name column using 3-dots menu and filter i will get 3 options
like
1.columns - Name
2.operator - contains (or anything which needs to be selected)
3.value - here i want to have a dropdown (with the **nameArr** values so that I can select and filter) instead a type search

Kindly help to achieve this

### Current behavior 😯

https://codesandbox.io/s/dawn-brook-8zgr3s?file=/demo.js

value field is only allowed to enter any text need a dropdown

### Expected behavior 🤔

value field should be dropdown

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @swathign-sbdinc 
Did you consider the [`singleSelect` column type](https://mui.com/x/react-data-grid/column-definition/#special-properties) for this use case?

Here's a working demo: https://codesandbox.io/s/elated-morning-6w2vt4?file=/demo.js
