### ISSUE TITLE
GridRenderCellParams example in the docs is incorrect [docs] 

### ISSUE THREAD

**Issue by vladmihaisima** [mui/mui-x#10431]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-data-grid/column-definition/#rendering-cells

### Kind of issue

Other

### Issue description

The code shown as example for render cell contains:

```renderCell: (params: GridRenderCellParams<Date>) => (```

which is now incorrect (I assume, that it is due to https://github.com/mui/mui-x/issues/5603 )

Note: if clicking on "Show code" the code is correct and uses: ``` (props: GridRenderCellParams<any, Date>) ```

### Context 🔦

Use the code examples in the documentation.

**Comment by cherniavskii** [comment]
Indeed, thanks!
