### ISSUE TITLE
GetRowId corrupted on filtering

### ISSUE THREAD

**Issue by xantos008** [mui/mui-x#10457]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Pre-requirements
1. uuid need to be installed

Input data

```
rows: [
        {
            name: 'John',
            lastName: 'Doe',
            type: 'Worrier',
            mustage: 'Yes',
        },
        {
            name: 'John',
            lastName: 'Doe',
            type: 'Dad',
            mustage: 'Yes',
        },
        {
            name: 'John',
            lastName: 'Doe',
            type: 'Papa',
            mustage: 'Yes',
        },
        {
            name: 'John',
            lastName: 'Doe',
            type: 'Mama',
            mustage: 'false',
        },
        {
            name: 'John',
            lastName: 'Doe',
            type: 'Baby',
            mustage: 'False',
        },
    ],
    columns: [
        {
            field: 'Name',
            headerName: 'User name',
            minWidth: 160,
            flex: 1,
        },
        {
            field: 'lastName',
            headerName: 'User last name',
            minWidth: 160,
            flex: 1,
        },
        {
            field: 'type',
            headerName: 'User role',
            minWidth: 160,
            flex: 1,
        },
        {
            field: 'mustage',
            headerName: 'Is have mustage',
            minWidth: 160,
            flex: 1,
        },
    ],
```

Add import of uuid

`import { v4 as uuidv4 } from 'uuid';`

And in render method of

```
return (
    <DataGrid rows={rows} columns={columns} getRowId={() => uuidv4()} />
)
```

### Current behavior 😯

If we use a quick filter or any of filters there would be an error

`No row with id #f811c738-ef68-4ced-ada8-4141e52d8214 found` where #f811c738-ef68-4ced-ada8-4141e52d8214 is auto generated by uuid.

Filtering calls getRowId function.

### Expected behavior 🤔

Filtering shouldn't re-create row's id (which is key in row models)

### Context 🔦

If we getch data from server and rows have no unique values to be defined as id, and no id field, we should use getRowId. But in that case filters would be broken.
As a suggestion there can be additional property to keep generated rowIds, and doesn't use function passed to getRowId in filtering.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
The output of `getRowId` for a given row should be the same irrespective of how many times it's called. It's purpose is to let the users specifiy any key of `rowData` as unique identifier if it's other than `id`.

I recommend generating IDs when generating `rowData`:

```tsx
const rows = [
  {
    id: uuidv4(),
    name: 'John',
    lastName: 'Doe',
    type: 'Baby',
    mustage: 'False',
  },
  ...
]
```

In the case of server-side data, you could either fetch original database IDs from the BE or generate random on the FE side before passing on the rows to the grid. If there's a property in the data returned from the row that you could use to uniquely identify a row, you could use `getRowId` to specify the property.

**Sidenote:** Reference to `getRowId` must be stable to avoid unnecessary renders and performance issues.

Let me know if that's solves your concerns.

**Comment by xantos008** [comment]
@MBilalShafi Well, this is what i do. On front-end side we have no access to back-end side. So transforming response by adding id property with auto-generated id do solves the issue. But this is not quiet what i am looking for. Basically, in previous versions, this wasn't the issue. And getRowId was working properly. Its was memorized since first render, and there was no need to create id field for data which have no unique idenifyers. So maybe this is becomes more like a feature, not a bug, to add something like use getRowId functionality as was before.

**Comment by romgrk** [comment]
> Basically, in previous versions, this wasn't the issue. And getRowId was working properly.

It may have worked but it had to be relying on undocument/unsupported behavior. The [doc](https://mui.com/x/react-data-grid/row-definition/#row-identifier) makes it clear that rows need an ID, that's not something we can work around easily in a performant way.

If you absolutely want to avoid modifying data, then you could add all your rows to a `Map<row, id>` and have your `getRowId` fetch the ID from that map. But I don't recommend it, it's going to be slow.

From what I understand here, I would not implement the change to allow identifier-less rows unless someone has a better case for the feature.

**Comment by bagoette** [comment]
This is listed as closed/completed, but the issue issue still exists for us in `v6.16.0`, so we need to stay on `v6.14.0`. Is this coming in a future release?

**Comment by romgrk** [comment]
This would be a `wontfix` case. You need to use the datagrid as described in the docs, and this means adding a stable ID for your rows. There is no way around having a stable ID, the grid makes the assumption that one exists throughout the codebase, and it is trivial to add one. If you don't have a row ID, use one of the ID generators such as `cuid`, `nanoid` or `uuid.v4`. You can even make it very very simple with a strictly monotonically increasing ID:

```typescript
let nextId = 1
function getId() { return nextId++ }
```

**Comment by bagoette** [comment]
> This would be a `wontfix` case. You need to use the datagrid as described in the docs, and this means adding a stable ID for your rows. There is no way around having a stable ID, the grid makes the assumption that one exists throughout the codebase, and it is trivial to add one. If you don't have a row ID, use one of the ID generators such as `cuid`, `nanoid` or `uuid.v4`. You can even make it very very simple with a strictly monotonically increasing ID:
> 
> ```ts
> let nextId = 1
> function getId() { return nextId++ }
> ```

Ok thanks! One of our pages has a complicated data grid with mixed filtering strategies (some server side, and some using data grid filtering), so we'll have to rethink the logic there.

**Comment by romgrk** [comment]
For your case I would suggest something like:

```ts
function getRowId(row) {
  row.id ??= cuid()
  return row.id
}
```
