### ISSUE TITLE
[question] MUI X Bar chart: is it possible to rotate/hide xAxis labels?

### ISSUE THREAD

**Issue by St1ko** [mui/mui-x#10463]
### Order ID or Support key 💳 (optional)

67005

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I want to display bar charts with a lot of records, the xAxis labels will start to overlap quite quickly. Is there a way to rotate the labels or hide every x-th label, so that the labels do not overlap? 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by yaredtsy** [comment]
hey @St1ko 

Yes, you can. You can add your own style by using the class name selector.
```
    [`.${axisClasses.bottom} .${axisClasses.tickLabel}`]: {
      transform: 'rotateZ(-45deg)',
    },
 ```
 demo: https://codesandbox.io/s/distracted-bartik-5nf433?file=/Demo.tsx

**Comment by alexfauquette** [comment]
As explained by @yaredtsy you can use CSS to manipulate the label. For hiding some tick labels, it is not yet feasible. The feature is in the backlog

**Comment by St1ko** [comment]
Thanks @yaredtsy and @alexfauquette

**Comment by timiles** [comment]
For anybody finding this post, there's now a better way to rotate labels:

```
    <BarChart
        xAxis={[
            {
                id: 'barCategories',
                data: ['My big name 1', 'My big name 2', 'My big name 3', 'My big name 4', 'My big name 5'],
                scaleType: 'band',
                tickLabelStyle: {
                    angle: -25,
                    textAnchor: 'end',
                    fontSize: 12,
                },
            },
        ]}
        series={[{data: [2, 5, 3, 4, 6],},]}
        width={500}
    />
```

(credit: https://stackoverflow.com/questions/78327811/vertical-barchart-labels-mui-x-barchart)
