### ISSUE TITLE
[DateRangePicker] - how use custom field like a button for { slot: { field: ButtonField } }

### ISSUE THREAD

**Issue by sabotag** [mui/mui-x#10469]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

For single Datepicker I see example 
[Link](https://mui.com/x/react-date-pickers/custom-field/#using-a-button)

single picker - for slot `field` passed ref for Popper in props 

but for range picker I dont see any refs:

[sandbox](https://codesandbox.io/s/musing-cherry-xc2kwj)

### Expected behavior 🤔

can anyone help provide example for range date picker and custom field?

**Comment by LukasTy** [comment]
Hello, thank you for opening this issue! 🙏 
The API for the range pickers is a bit different.
You could back-track the needed change when looking at the `BrowserField` component implementation in the `With the browser input` section [here](https://mui.com/x/react-date-pickers/custom-field/#using-another-input).

In essence, you only need to make the following change:
```diff
- ref={ref}
+ ref={props.InputProps.ref}
 ...
 // add this line to signal to the range picker to expose the props for a single input range picker
+ ButtonField.fieldType = "single-input";
```

**Comment by sabotag** [comment]
> Hello, thank you for opening this issue! 🙏 The API for the range pickers is a bit different. You could back-track the needed change when looking at the `BrowserField` component implementation in the `With the browser input` section [here](https://mui.com/x/react-date-pickers/custom-field/#using-another-input).
> 
> In essence, you only need to make the following change:
> 
> ```diff
> - ref={ref}
> + ref={props.InputProps.ref}
>  ...
>  // add this line to signal to the range picker to expose the props for a single input range picker
> + ButtonField.fieldType = "single-input";
> ```

Thanks, its work!
