### ISSUE TITLE
[TreeView] `Multiple` generic not inferred when `multiSelect` prop is missing

### ISSUE THREAD

**Issue by Methuselah96** [mui/mui-x#10473]
### Search keywords

treeview generic multiple

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://codesandbox.io/s/mystifying-easley-jflm86?file=/Demo.tsx

```ts
<TreeView
  onNodeSelect={(event, nodeId) => {
    // This should pass type-checking, but doesn't
    const shouldBeAString: string = nodeId;
    console.log(nodeId);
  }}
>
```

### Current behavior

There is a type error in the `onNodeSelect` prop because TypeScript thinks `nodeId` can be either a `string` or `string[]`, when in fact it can only be `string` because the `multiSelect` prop was not provided.

### Expected behavior

No type error.

### Your environment

tsconfig:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}
```

**Comment by flaviendelangle** [comment]
Thanks for the report, it will be fixed in the next release :+1:
