### ISSUE TITLE
[question] <DatePicker/> changes its value even though the value prop remains static.

### ISSUE THREAD

**Issue by john1625b** [mui/mui-x#10475]
### The problem in depth 🔍
order number: 72840 (premium)

note in the following code: the `onChange` isn't passed and the `value` remains a static value of "2022-04-18", but you can still select a value from the calendar and the change is reflected in the UI:

```
        <DatePicker
          label="Controlled picker"
          value={dayjs("2022-04-18")}
          // onChange={(newValue) => setValue(newValue)}
        />
```

https://codesandbox.io/s/mui-date-picker-3wnljf?file=/Demo.tsx:715-860

This situation poses a challenge. Suppose a network request fails when attempting to update a value. In that case, the user interface might still display the newly selected value, even though the backend did not successfully save this change. This discrepancy could lead to confusion and inaccuracies.

**Search keywords**: DatePicker, controlled, static value

**Comment by LukasTy** [comment]
Hello, I've noticed a duplicate issue outside of Priority support: https://github.com/mui/mui-x/issues/10476
Has this issue been opened by mistake?
If so, could you close it? 🤔

**Comment by john1625b** [comment]
@LukasTy sorry, its a duplicate.
