### ISSUE TITLE
Select Filter Operators in headerFilters

### ISSUE THREAD

**Issue by kharlaienko** [mui/mui-x#10482]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/63g9th?file=/Demo.tsx

Steps:
1. Create two or more columns
2. Set prop unstable_headerFilters
3. Click on select filter operators button
4. Click on select filter operators button on other column

### Current behavior

When you clicked on operators select then  click on other column operator select both of them close.

https://github.com/mui/mui-x/assets/55911912/8be9143c-d7cf-46e2-a84e-a9538aea8ab8

### Expected behavior

When you clicked on operators select then  click on other column operator select both expect to last clicked operator selector to be opened

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid, headerFilters

**Comment by MBilalShafi** [comment]
Thanks @kharlaienko for reporting the issue, I've opened a [PR](https://github.com/mui/mui-x/pull/10483) which should resolve it.
