### ISSUE TITLE
How can i change the placeholder 'Contains' in header filter

### ISSUE THREAD

**Issue by anastasia327** [mui/mui-x#10481]
### The problem in depth 🔍

![header](https://github.com/mui/mui-x/assets/85896274/8f03c8f6-c061-4633-ab13-600f5a8a8449)
I'm using data grid premium and in the headerFilterMenu i want to change the placeholder

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: data grid filtering
**Order ID**: #67465

**Comment by MBilalShafi** [comment]
Hey @anastasia327, thank you for using MUI X Data Grid.

If I understand correctly, you want to change the header filter placeholder for the text fields to a custom value, you can do so by passing on `slotProps.headerFilterCell.InputComponentProps.label`. `slotProps.headerFilterCell` is the way to override any default props of the header filter cell.

```tsx
<DataGridPremium
  {...otherProps}
  unstable_headerFilters
  slotProps={{
    headerFilterCell: {
      InputComponentProps: { label: "Filter" }
    }
  }}
/>
```

I tried to do that in this CSB example: https://codesandbox.io/s/amazing-chaum-g5hd66?file=/Demo.tsx:622-740

Let me know if that is something you are looking for?

**Comment by anastasia327** [comment]
this worked! Thank you!!

**Comment by anastasia327** [comment]
> Hey @anastasia327, thank you for using MUI X Data Grid.
> 
> If I understand correctly, you want to change the header filter placeholder for the text fields to a custom value, you can do so by passing on `slotProps.headerFilterCell.InputComponentProps.label`. `slotProps.headerFilterCell` is the way to override any default props of the header filter cell.
> 
> ```tsx
> <DataGridPremium
>   {...otherProps}
>   unstable_headerFilters
>   slotProps={{
>     headerFilterCell: {
>       InputComponentProps: { label: "Filter" }
>     }
>   }}
> />
> ```
> 
> I tried to do that in this CSB example: https://codesandbox.io/s/amazing-chaum-g5hd66?file=/Demo.tsx:622-740
> 
> Let me know if that is something you are looking for?

/

**Comment by tsdev-jpeg** [comment]
Hi, i'd like to know if changing the label can be done for specific columns filter?
For most i'd like to have one label, but for 2 different columns i'd like the filter to display something else. 
Is that doable?
