### ISSUE TITLE
[data grid] `onFilterModelChange` fires with stale field value

### ISSUE THREAD

**Issue by fatihcaliss** [mui/mui-x#10489]
### Steps to reproduce

Link to live example: [liveExample](https://codesandbox.io/s/amazing-feynman-rds2pk?file=/Demo.tsx)

Steps:
1. Click `commodity`column menu and than click to the filter  on panel dialog
2. Enter 'r' as a string value for filter
3. Now change the field`commodity` to `quantity`
4. You will see on the console that: the filterModel item field updated but value us stale.
<img width="1506" alt="Screenshot 2023-09-26 at 15 11 39" src="https://github.com/mui/mui-x/assets/93558245/625554de-4ffc-423a-9e24-cffc82c11424">

### Current behavior

As you will see when you follow steps to reproduce again, the value remains stale.

### Expected behavior

I expect both field and value to be updated whenever any item in `filterModel` is updated

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid filtering
**Order ID**: 67202

**Comment by romgrk** [comment]
We keep having bugs in that part of the UI/state. I think there is something wrong with our approach.

**Comment by gitstart** [comment]
@fatihcaliss @romgrk @zannager we would like to pick this up

**Comment by romgrk** [comment]
This has some complexity, you can pick it up if you feel confident but there are lots of edge-cases to consider for this. If you do pick it up, I suggest to:
 - Read the previous PRs that affected `GridFilterInputValue`, there's a lot of context
 - Open an empty PR discussing how you plan to fix it, so we can validate the approach before you do all the work. (`git checkout -b fix-filter-input-value && git commit --allow-empty -m 'empty commit'`)

**Comment by gitstart** [comment]
Here is the link to the PR @romgrk

https://github.com/mui/mui-x/pull/10691
