### ISSUE TITLE
[data grid] `singleSelect` with empty value option moved to the last

### ISSUE THREAD

**Issue by cbichis** [mui/mui-x#10493]
### Steps to reproduce

Hello,

When a field has a valueOption which is empty '' it's always moved as the last on the select.

We need so the select to maintain the order of items into select.

### Current behavior

Sample:
{
  field: 'myselect',
  type: 'singleSelect',
  valueOptions: [[value: '', label: '--pick--'], [value: 1, label: 'some option'], [value: 5, label: 'some other option']]
}

If changing the empty option to value: 0 then the order is correct (the empty option is displayed first). However, using 0 as empty option value is not OK on some cases.

### Expected behavior

Place empty option first

**Search keywords**: datagrid singleSelect
**Order ID**: 48905

**Comment by MBilalShafi** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot. 👷

A live example would be perfect. [This **codesandbox.io** example](https://codesandbox.io/s/funny-violet-hv6p8p?file=/Demo.tsx) _may_ be a good starting point as you can notice I can use `singleSelect` with an empty value just like you mentioned.

Thank you!

**Comment by michelengelen** [comment]
Hi @cbichis ... I have created a sandbox example [here](https://codesandbox.io/s/frosty-euclid-c2ysg4?file=/Demo.tsx) and I cannot reproduce the problem you are experiencing.

Could you maybe have a look and provide us with an example (either based on my example of on this [codesandbox](https://codesandbox.io/s/v98qkv?file=/Demo.tsx))?
