### ISSUE TITLE
[pickers] Date/Time/Date-Time Picker: Clear date with clear icon in Datepicker Textfield

### ISSUE THREAD

**Issue by DharmiVekariya** [mui/mui-x#10492]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Is it possible to have a clear value in Date, Time, and Date-Time Picker?

Purpose if we have a clear icon in the picker text field and by clicking it we can clear the date instead of removing each character. Also I am not finding anything in the documentation to customize the text field with keep default options and need both clear and picker open/close icon

### Examples 🌈

In version 5 we were able to achieve this by customizing TextField as in that version, renderInput props are there.  Check below

![image](https://github.com/mui/material-ui/assets/109334059/d2bd2fb8-72ae-48d4-821c-7d6cd251d480)

Check the below code for the same
![image](https://github.com/mui/material-ui/assets/109334059/0a98aa0b-c847-4de5-ae4c-2cb97bae1acb)

![image](https://github.com/mui/material-ui/assets/109334059/14b90a4b-d139-4178-a96e-65477e4993b7)

But in v6 renderInpur prop is deprecated and now have slotProps to apply textfield props in that. But if we apply clear then the default endAdornment icon is removed which is used to open and close.

So can you provide clear functionality within the component and if not possible then can you guide how can I achieve this?

**Search keywords**:

**Comment by flaviendelangle** [comment]
Hi,

This will be supported out of the box in the coming weeks (see https://github.com/mui/mui-x/pull/9095)

**Comment by Prince-Gizard** [comment]
Hello @flaviendelangle @noraleonte ! How i can try this functional in my project? Or this feature is not supporting in v6.19?

**Comment by LukasTy** [comment]
> How i can try this functional in my project? Or this feature is not supporting in v6.19?

Please check the [documentation examples](https://mui.com/x/react-date-pickers/date-picker/#clearing-the-value). 😉

**Comment by Prince-Gizard** [comment]
sorry for not being attentive @LukasTy
