### ISSUE TITLE
[Charts] If a chart is in a drawer, it's tooltip is not visible (it is below the drawer)

### ISSUE THREAD

**Issue by evgeniiarts** [mui/mui-x#10497]
### Steps to reproduce

Link to live example: 
https://codesandbox.io/s/recursing-oskar-73gcnt?file=/Demo.js

Steps:
1. Create a drawer from MUI
2. Place a chart in the drawer
3. Hover over a point within the chart: the tooltip will not appear. Yet if you inspect the elements tree in the browser, you will see that the tooltip does appear. But it does so below the drawer and is therefore not visible for the user.

I have set the opacity of the drawer to 0.5 so you can see that the tooltip is behind it.

### Current behavior

When a chart is used in a drawer, it's tooltip will show below the drawer's paper root.

### Expected behavior

The tooltip of a chart should be always visible regardless of it's parent component.

### Context

I have a use case where I have a table with data. The user can open the rows in order to see details and some data within a chart for each row.
I want my user's focus to be entirely on the chart, similar to the drawers we see in Google Cloud Console (when for example editing some data from a table - it opens in a drawer while the rest of the content is slightly greyed out with an overlay).
Therefore I have used a drawer for this purpose. So far I cannot figure out a fix - and maybe I should have used a custom Paper component with transition. But the drawer seemed very convenient at first because it looks like exactly the element I require.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Chrome and Codesandbox, not OS relevant
```
</details>

**Search keywords**: drawer, tooltip, chart

**Comment by alexfauquette** [comment]
Thanks for the report. I think it's similar to this issue about Popper: https://github.com/mui/material-ui/issues/19486

It needs a `slotProps` options to allow you to simply customize the popper
