### ISSUE TITLE
[Data Grid] Hide tooltip when row is not being displayed

### ISSUE THREAD

**Issue by rihernandeRI** [mui/mui-x#10499]
### What's the problem? 🤔

Is there any way to hide the validation tooltip when the row is not being displayed?
![image](https://github.com/mui/mui-x/assets/143653858/c6f406ff-789e-4cb4-834a-176ca56df9a2)
![image](https://github.com/mui/mui-x/assets/143653858/30a42c80-9379-4632-aac2-7961dc1d2cdd)

### What are the requirements? ❓

Hide the tooltip when the row is not being displayed

### Resources and benchmarks 🔗

This is the sandbox: https://codesandbox.io/s/amazing-cookies-zzvm6t

**Search keywords**:

**Comment by MBilalShafi** [comment]
One solution to this could be to keep the cell red but show the tooltip only on cell hover.
https://github.com/mui/mui-x/assets/12609561/31149910-c1a4-4d93-98df-e9717c332a95

I tried to do this in your attached example, here's the updated codesandbox: https://codesandbox.io/s/funny-jones-45xnwc?file=/Demo.tsx

Let me know if it works in your use case.

**Comment by rihernandeRI** [comment]
Thank you so much, that works for me!
