### ISSUE TITLE
[datagrid] Make quickfilter search by date

### ISSUE THREAD

**Issue by cannontechnology** [mui/mui-x#10496]
### Summary 💡

With the default settings, quick filter will only consider columns with types 'string','number', and 'singleSelect'.
Could you implement support for date types by something like the following which will search for any string value included in the date.
```
getApplyQuickFilterFn: (value) => {
        return (params) => {
          return params.value.includes(value);
        };
      }
```

### Examples 🌈

![image](https://github.com/mui/mui-x/assets/3844488/bde078c1-1f7b-4101-875b-da0c73ffbdb6)

### Motivation 🔦

End users expect to be able to search by date strings in the quick filter

**Search keywords**: datagrid quick filter date
**Order ID**: 74585

**Comment by romgrk** [comment]
Could you put that a reproducible case into a [codesandbox](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx)? I feel like it should be working, quickfilter is designed to work on formatted values.

**Comment by cannontechnology** [comment]
Sure will do. It does not work if type="date"

**Comment by cannontechnology** [comment]
Here you go @romgrk - The updated date is searchable via a quickFilterFn, however the created date is not (by default).
https://codesandbox.io/s/amazing-lederberg-xgrxhw

**Comment by romgrk** [comment]
@mui/xgrid Does someone have more context about why quickfilter doesn't work with dates as-is? Should it work?

**Comment by MBilalShafi** [comment]
@romgrk I don't know why we are deliberately [setting](https://github.com/mui/mui-x/blob/803b14e6908c597f61d3a93618ae5bfa4f94b55f/packages/grid/x-data-grid/src/colDef/gridDateColDef.ts#L53-L54) the applier function for `date` and `datetime` fields as `undefined`.

The default `string` function seems to work just fine: https://codesandbox.io/s/withered-smoke-zjx2kl?file=/Demo.tsx

**Comment by romgrk** [comment]
I don't know either. When I updated the v7 ones I didn't change the behavior of the filters, I just added the new appliers with the same logic as they had before.

**Comment by cannontechnology** [comment]
One thing that I just realized my solution affected sorting as that now seems to be treated as a string. So date/time fields are now sorted wrong. as a time of 9:33 is treated > 10:33.

**Comment by romgrk** [comment]
Do you have a codesandbox example?

**Comment by cannontechnology** [comment]
@romgrk - I deleted that last comment. That was a mistake on my end. This fix works great as is. Thanks!

**Comment by cannontechnology** [comment]
However, I'm having issues with a few of the premium imports with the latest release. For example:
Property 'getRow' does not exist on type 'GridApiPremium'.
`import { useGridApiRef } from "@mui/x-data-grid-premium";` will give me that error.
`import { useGridApiRef } from "@mui/x-data-grid";` no longer throws that error but then I can't access the premium features.

Type 'MutableRefObject<GridApiCommunity>' is not assignable to type 'MutableRefObject<GridApiPro>'.
  Type 'GridApiCommon<GridStateCommunity, GridInitialStateCommunity>' is missing the following properties from type 'GridApiPro': pinColumn, unpinColumn, getPinnedColumns, setPinnedColumns, and 6 more.
