### ISSUE TITLE
Exporting Not working for master/detail

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#10505]
### The problem in depth 🔍

Hello, 

As you can see here: https://codesandbox.io/s/ph2c4r?file=/Demo.js the values in the master/details doesn't print. How can I get this to work. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: export master detail
**Order ID:** 66765

**Comment by MBilalShafi** [comment]
@lisaWriteJava Thank you for using MUI X Data Grid.

Could you elaborate more on the problem you are facing? Sharing a screen record showing the issue will help.

For a test, I tried the codesandbox link attached in the issue and **Print** works for me in both Firefox and Chrome, the screenshots are attached!

Firefox:
<img width="400" alt="image" src="https://github.com/mui/mui-x/assets/12609561/c13ce241-7777-4002-9af8-2368b2566536">

Chrome:
<img width="400" alt="image" src="https://github.com/mui/mui-x/assets/12609561/db8db4d2-083e-4eaa-aa74-0951a0ccc5c7">

Thank you!

**Comment by lisaWriteJava** [comment]
I apologize, I sent the wrong sandbox, https://codesandbox.io/s/ph2c4r?file=/Demo.js is the correct one. So the first column doesn't export  the one with the +, it starts from order id.  I tried renderHeader and still it wouldn't export.

**Comment by MBilalShafi** [comment]
Ah ok so you mean the column with the `+` icons for expansion of the master detail panel, it's the intended behavior to not make it part of print export, as it couldn't be further interacted with so doesn't make a lot of sense to make it part of the exported table.

Let me know if you have further questions.

**Comment by lisaWriteJava** [comment]
ahh we had a client that wants to use that master detail (+) column to show/hide a component that may have a lot of data like hundreds of lines.  Since it wouldn't look well in a table, we were going to show/hide a card with this information but want to export the info with a print or excel export. Is this achievable. Maybe the approach to do it is wrong and if so what would be the best way to implement this?

**Comment by MBilalShafi** [comment]
Can you share a minimal demo of the current approach being used and the intended behavior in a codesandbox example, it will help us understand the issue and suggest a better solution.

**Comment by lisaWriteJava** [comment]
Here's a sandbox: https://codesandbox.io/s/zen-smoke-lmnccz?file=/Demo.js  I mocked up the first column (+) to show /hide details passed to it. I could make it a larger list but, it would be the same idea.

**Comment by MBilalShafi** [comment]
Following your example, I can export the card just fine (without the +/- icons which obviously don't make sense as they won't be interactive in the PDF/printed version)
<img width="881" alt="image" src="https://github.com/mui/mui-x/assets/12609561/5622e360-82f4-418f-a504-4e5530683222">

Are you having difficulties in getting a result similar to one I attached above?

**Comment by lisaWriteJava** [comment]
so what the user has asked is to be able to print the hidden data when I do an export. It can stay hidden in the table but be exportable.

**Comment by lisaWriteJava** [comment]
It is possible for the hidden data to be able to be exported on a csv or excel export?  It's not goign to be somethign they need to fetch but it's just so large it should be shown in the intial grid

**Comment by romgrk** [comment]
I don't think that we support that use-case. What do you mean by hidden data?

You've opened this issue as a Priority Support issue but haven't confirmed your support key. Is this a Priority Support issue?

**Comment by lisaWriteJava** [comment]
The support key is 66765. So when I say hidden data, I mean the data from details. I'd like that to be able to be exported also but not shown unless we click to show that data on the screen.

**Comment by romgrk** [comment]
It's not possible to do that for now, the hidden data from details panel is not data formatted in a way the datagrid can use, it's HTML. If you want to add that feature, I would suggest that:
 - You look into row grouping, and group the additional data that you want to export as children of each of your rows.
 - Write the export logic yourself, you'll be free to customize however you want.

**Comment by lisaWriteJava** [comment]
Great thanks so much. I appreciate the assistance. This is help greatly in explaining our strategy to the customer.

**Comment by romgrk** [comment]
:+1:
