### ISSUE TITLE
Columns are shrinked when drawer or dialog is opened

### ISSUE THREAD

**Issue by tomashlavac** [mui/mui-x#10509]
### Steps to reproduce

I tested new autosize feature but i encountered with this bug. When dialog or drawer is opened the columns are shrinked and won't expand back.

Link to live example: [(Demo)](https://codesandbox.io/s/pensive-clarke-v6hzm5?file=/src/demo.js)

![shrink](https://github.com/mui/mui-x/assets/104761043/b5a8fc1e-604e-4af1-81a3-4297ab8e8c8f)

### Current behavior

Columns are shrinked when drawer or dialog is opened

### Expected behavior

Columns should not shrink

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.6
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Edge: Not Found
    Safari: 16.6
```
</details>

Used broswer Chrome: 117.0.5938.92

**Search keywords**: datagrid autosize columns
**Order ID**: 69651

**Comment by MBilalShafi** [comment]
Hey @tomashlavac, thank you for using MUI X Data Grid and reporting the issue.
It seems to me more like an unstable reference issue than the issue with column auto size.

As per columns' documentation [page](https://mui.com/x/react-data-grid/column-definition/): 

> The columns prop should keep the same reference between two renders. The columns are designed to be definitions, to never change once the component is mounted. Otherwise, you take the risk of losing elements like column width or order. You can create the array outside the render function or memoize it.

So whenever a state variable changes by opening drawer or modal, the columns object is reinstantiated, and the grid is mounted again which triggers a disturbance/recalculation in the column autosizing.

I tried to move the `columns` and `rows` objects outside the component scope and it seemed to fix it.

Here's the updated code sandbox where it seems to work fine: https://codesandbox.io/s/dark-cloud-l736kf

Let me know if you have another issue around this.

Thanks!

**Comment by tomashlavac** [comment]
Hi @MBilalShafi,
it your example it looks it is working fine.
But I tried to move column definition and rows outside the component but it did not work.
I tried to make the example as close as possible to how we use it real app.
Here is example: [Demo](https://codesandbox.io/s/pensive-clarke-v6hzm5?file=/src/demo.js)
Am I doing something wrong ?

**Comment by MBilalShafi** [comment]
I guess you are wrapping the columns into the hook unnecessarily, I updated the CSB and it seems to work: https://codesandbox.io/s/rough-fog-2dx8hq

**Comment by tomashlavac** [comment]
In our app we have more than 20 formatters (price formatters, date formatters, ...) so it is necessary to wrap column definition to hook.

Quick recap:
- column definition inside component with or without useMemo is not working
- column definition outside component wrapped inside hook (with or without useMemo) is not working

I think this is bug. We are using DataGrid in more than 60 locations in app with column definition inside the component using useMemo and we have never encountered any problem.

**Comment by MBilalShafi** [comment]
@tomashlavac I'd appreciate if you update the codesandbox example I shared above with the use-case you mentioned depicting why a `colDef` without a `useMemo` (inside) is necessary.
