### ISSUE TITLE
datagrid pro infinite scroll with custom quick filter losing focus immediately after typing

### ISSUE THREAD

**Issue by lsajja-aprimo** [mui/mui-x#10501]
### Search keywords

quickfilter, search losing focus, datagrid search field losing focus

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://codesandbox.io/s/aged-cdn-jdmng3?file=/src/demo.tsx 
the live example doesn't have server side data loading so not able to see the issue. i am not sure how to do that

Steps:
1. type in filter(it loses focus immediately as the api is called)
2. filter model change event is fired
3.api is called and data is loaded

### Current behavior

typing in the quick filter toolbar immediately loses focus 

![datagrid focus lost 2](https://github.com/mui/mui-x/assets/131054216/99fed50d-5d6d-4653-9f23-1c6ddc4b18ae)

### Expected behavior

the focus should not lose after after each debounce

### Context

trying to add infinite scroll which loads data from the server in batches after reaching the onscrollend. along with this implementing quick filter where the text entered in the quick filter field is sent to server and the resulting data is loaded in the grid.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by lsajja-aprimo** [comment]
actually moving the custom component outside of the gird component fixed the issue

**Comment by diego-pellecer** [comment]
You could fix this by memoizing the Toolbar in order to prevent the re-rendering issue

`toolbar: useMemo(() => CustomToolbar, []),`
