### ISSUE TITLE
[data grid] Filter panel form fail to update when `filterModel` changes

### ISSUE THREAD

**Issue by nessj1994** [mui/mui-x#10511]
### The problem in depth 🔍

When calling my implementation of onFilterModelChange externally to the actual panel form, it fails to update. I can still see the badge change to match the appropriate number of filters, but the form itself doesn't update. To elaborate on what I mean by externally, we are working to create some custom "quick filter" buttons if you will to make life easier on our users. For a short example to demonstrate there is a button we've implemented to instantly show recently shipped orders. It applies a couple filters to show only orders that match our shipped status, and in particular that have a ship date within the last 60 days. See the image here: 

![image](https://github.com/mui/mui-x/assets/9426931/e181a110-3a92-428e-9b75-f7f82a61a2ed)

On the right hand side is the button labeled "Recent."
When clicking this it applies the filtering correctly. Some debugging has shown me that it does both enter the onFilterModelChange function correctly, and correctly applies the filterModel as stated above. The rows change and look accurate to the data we want to see, but for some reason the filter panel itself remains with our default date filtering only. This can be confusing for users. 

Note that in the following image it shows 4 filters being applied in the badge but only a single filter form line 

![image](https://github.com/mui/mui-x/assets/9426931/c7f476c4-2cf5-4b6d-89ad-de78e3b6a528)

I would expect given that the form update makes it into the onFilterModelChange function exactly the same way if I use the typical Add Filter button that our custom quick action buttons would properly update the form as well but clearly not. Am I perhaps missing some functionality I can call from my apiRef variable or something to update the filter panel when the model changes? Any examples that can be provided would be great. I will start working on a code sandbox example in case that's helpful as well. Thanks for any help that can be provided. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD

  Browsers:
    Chrome: Version 117.0.5938.89

  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0
    @emotion/styled: ^11.9.3 => 11.9.3
    @mui/base: ^5.0.0-alpha.91 => 5.0.0-alpha.91
    @mui/core-downloads-tracker:  5.10.17
    @mui/icons-material: ^5.10.16 => 5.10.16
    @mui/material: ^5.8.6 => 5.10.17
    @mui/private-theming:  5.10.16
    @mui/styled-engine:  5.10.16
    @mui/system:  5.10.17
    @mui/types:  7.2.2
    @mui/utils:  5.10.16
    @mui/x-data-grid:  6.10.0
    @mui/x-data-grid-premium: ^6.10.0 => 6.10.0
    @mui/x-data-grid-pro:  6.10.0
    @mui/x-date-pickers: ^5.0.0 => 5.0.0
    @mui/x-license-pro:  6.10.0
    @types/react: ^18.0.15 => 18.0.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 5.1.6 => 5.2.2
```
</details>

**Search keywords**: Filter Panel Form, filter model change
**Order ID**: 70732

**Comment by MBilalShafi** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by nessj1994** [comment]
I'm working on this. It's posing somewhat of a challenge to replicate though as our actual implementation is very server oriented. Given that I can't just hook a code sandbox up to our server's filtering and other functionality very easily it's not working quite the same. I'll post the link as soon as I get this to a reasonable state. Might take me another day or so.

**Comment by nessj1994** [comment]
https://codesandbox.io/s/data-grid-community-forked-kt97wv?file=/src/App.tsx

Perhaps this will be enough to diagnose? I can't get it to fully replicate our current functionality. Some of our code can't be implemented in a demo sandbox as easily because we use a server side filtering setup with some Redux thunks that act upon the filter model as it changes. Because of this it seems that the sandbox doesn't want to apply the Recent / Shipped filters like our actual codebase will. As mentioned the real codebase does at least apply the filters correctly, but leaves the form with a single initial date range filter row. However, the sandbox does clearly show in the console that it gets to the onFilterChange function, but fails to filter or change the form in this case. If this isn't enough let me know and I can keep trying to tweak. 

If necessary, I could also provide a login for our beta site as a live or even access to our code repo. My boss said it shouldn't be that big of a deal, but it might require some kind of NDA signed for the safety of our code and data at that point. I wasn't really sure how feasible that is. I know some organizations that provide commercial support will do this, but I'm not sure if that's how you guys tend to operate.

**Comment by nessj1994** [comment]
For what this is worth, I did manage to find a workaround for my use case. The documentation specifically recommends avoiding it except as a last resort, but it seems that if I add an apiRef to the QuickButtonPanel component and directly call apiRef.current.setFilterModel({data}) with the filter values I want everything updates correctly. If this is what you would advise that's fine. I feel like this working means I've messed up somewhere in my onFilterChange or something to cause it to not update properly. Wouldn't surprise me as I'm still learning new things about your API daily. If that is the case though I'd prefer to properly fix it rather than opting for the last resort option.

**Comment by MBilalShafi** [comment]
I'm glad you already figured out the way to fix the issue, I couldn't get your codesandbox example to work, though I suspect the issue might be related to not having the correct dependencies in the `React.useCallback` function `onFilterChange` due to which it always has the initial or outdated value of the variables it's using and the expected behavior is not achieved.

Could you try adding the dependencies and see if it fixes the problem or make the codesandbox example work? I'll be happy to have another look over it.

Thanks
