### ISSUE TITLE
[pickers] TimePicker closing on selection when closeOnSelect is false

### ISSUE THREAD

**Issue by airowe** [mui/mui-x#10512]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Current behavior

Like in https://github.com/mui/mui-x/issues/9081, I'm seeing my TimePicker close on `any` selection even when `closeOnSelect` is set to false.

### Expected behavior

The TimePicker should not close on selection if `closeOnSelect` is false.

### Context

We are allowing users to book appointments, and they need to be able to choose the hour, minutes, and AM/PM using a TimePicker.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.5.2
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: Not Found
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.17
    @mui/core-downloads-tracker:  5.14.11
    @mui/material: ^5.14.11 => 5.14.11
    @mui/private-theming:  5.14.11
    @mui/styled-engine:  5.14.11
    @mui/system:  5.14.11
    @mui/types:  7.2.4
    @mui/utils:  5.14.11
    @mui/x-date-pickers: ^6.15.0 => 6.15.0
    @types/react: ^18.0.28 => 18.2.23
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.5 => 4.9.5
```
</details>

**Search keywords**: timepicker closeonselect

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by cfbender** [comment]
@airowe I had the same issue using `useCallback` to generate a component in a hook. I refactored to `useMemo` and it seems to be working now: [Reproduction here](https://codesandbox.io/s/date-and-time-pickers-forked-rcz3qz?file=/src/App.tsx)

**Comment by airowe** [comment]
> @airowe I had the same issue using `useCallback` to generate a component in a hook. I refactored to `useMemo` and it seems to be working now: [Reproduction here](https://codesandbox.io/s/date-and-time-pickers-forked-rcz3qz?file=/src/App.tsx)

@cfbender Thanks for the response! I tried that in my scenario and looks like the underlying issue lies in the CoreUI template we're using. Closing this issue now.
