### ISSUE TITLE
[pickers] DesktopDateRangePicker InputProps only applied to Start Input

### ISSUE THREAD

**Issue by Pettor** [mui/mui-x#10546]
### Steps to reproduce

Link to live example: (required)
[Sandbox Link](https://codesandbox.io/embed/jovial-gagarin-jkzrkp?fontsize=14&hidenavigation=1&theme=dark)

### Current behavior

Only TextField with position `start` have the added `div` with text "test".

### Expected behavior

Both TextField with position `start` and `end`  should have the added `div` with text "test".

### Context

Attach icons to the end of both fields that open the calendar for each position.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (117.0.2045.43)
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1
    @emotion/styled: 11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.16
    @mui/core-downloads-tracker:  5.14.11
    @mui/icons-material: 5.14.9 => 5.14.9
    @mui/lab: 5.0.0-alpha.145 => 5.0.0-alpha.145
    @mui/material: 5.14.10 => 5.14.10
    @mui/private-theming:  5.14.11
    @mui/styled-engine:  5.14.11
    @mui/system:  5.14.11
    @mui/types:  7.2.4
    @mui/utils:  5.14.11
    @mui/x-data-grid: 6.16.0 => 6.16.0
    @mui/x-date-pickers:  6.16.0
    @mui/x-date-pickers-pro: 6.16.0 => 6.16.0
    @mui/x-license-pro: 6.10.2 => 6.10.2
    @mui/x-tree-view:  6.0.0-alpha.1
    @types/react: 18.2.23 => 18.2.23
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.2.2 => 5.2.2
```
</details>

**Search keywords**: DesktopDateRangePicker, InputProps

**Comment by LukasTy** [comment]
Thank you for reporting this issue! 🙏 
It looks like a regression that has been introduced in 6.13.0, probably with https://github.com/mui/mui-x/pull/10077/files
