### ISSUE TITLE
[pickers] Add previous and next year controls to date calendars

### ISSUE THREAD

**Issue by konrazem** [mui/mui-x#10566]
### Summary 💡

I would like to have another 2 icon buttons with double arrows to be able to navigate between calendar years. We have a case where the user needs to pick date ranges from many custom years (1989, 2022, ...). 

I know we can implement date input to provide custom dates, however, those arrows reduce much of our work. 

NOTE: It can be optional with some properties like disableYearsNavigation.

### Examples 🌈

![image](https://github.com/mui/mui-x/assets/19363700/866622d1-8ef4-4eb1-b299-3294313944fc)

### Motivation 🔦

User may want to move faster between calendar months. Those 2 arrow buttons allow to move ~12 x faster.

**Search keywords**: StaticDateRangePicker, DateRangeCalendar, date-pickers, mui-x, x-date-pickers-pro
**Order ID**: 46820

**Comment by LukasTy** [comment]
Thank you for the suggestion. 🙏 
[MD3 (Material You) also specifies](https://m3.material.io/components/date-pickers/specs) quick navigation between years in their spec for the `Docked` (Desktop) date picker.
We'll explore this option and the best way to introduce it. 👌

**Comment by LukasTy** [comment]
@konrazem Thank you for reminding me about this!
We did not get the chance to groom it yet.
The implementation of the MD3 features is not our top priority at the moment, hence, I doubt that we will be able to ship a solution for it in less than 6 months.
If you need it sooner, please feel free to implement it on your own. 😉

**Comment by LukasTy** [comment]
During the grooming, we decided to start with exposing a `calendarHeader` on the `DateRangePicker` as well as `DatePicker` so that it would be possible to override the header as per user needs.
The adoption of MD3 spec is a much broader topic that will also take more time than this addition.
