### ISSUE TITLE
MUI-X-Charts Not Building Properly in Next.js 12 Application 

### ISSUE THREAD

**Issue by johnsonav1992** [mui/mui-x#10565]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Create a Next.js 12 application
2. Download mui/x-charts all dependencies 
3. Create a chart and run production build

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: build error

**Comment by oliviertassinari** [comment]
Duplicate of #9826?
