### ISSUE TITLE
[datagrid] How to autosize columns on rows fetch

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#10578]
### The problem in depth 🔍

The [`autosizeOnMount` prop](https://mui.com/x/react-data-grid/column-dimensions/#autosizing) that works great when the rows data is available on grid mount.
But it's not obvious how to autosize columns when the rows are fetched asynchronously after the grid is mounted.

We need to document a recommended solution for this use case.

Here is what I tried:

### 1. Call `apiRef.current.autosizeColumns` when rows are fetched
https://codesandbox.io/s/lucid-roentgen-ynchfy?file=/Demo.tsx

Pros:
- The most obvious solution (see https://github.com/mui/mui-x/issues/10510)

Cons:
- Does not work - the grid has not rendered the rows yet, so calling `autosizeColumns` can only measure column headers.

### 2. Same as 1, but wrap `apiRef.current.autosizeColumns` with `setTimeout`
https://codesandbox.io/s/sad-pasteur-cdyscq?file=/Demo.tsx

Pros:
- It works

Cons:
- Column width jump

### 3. Use `ReactDOM.flushSync` + `apiRef.current.updateRows` (instead of `rows` prop) and `apiRef.current.autosizeColumns`
https://codesandbox.io/s/interesting-ben-vh9ndk?file=/Demo.tsx

Pros:
- It works
- No column width jump

Cons:
- Not an obvious solution

### 4. Render the data grid *after* the data is fetched and use the `autosizeOnMount` prop.

Pros:
- It works

Cons:
- Cannot show the data grid in the loading state while fetching the data
- Won't work on data refetch as the grid stays mounted. Changing the `key` will reset the grid state.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid autosize columns

**Comment by romgrk** [comment]
I think I'd favor adding a recipe for 3.

**Comment by michelengelen** [comment]
> I think I'd favor adding a recipe for 3.

Thought the same while reading ... it provides the most value, since there will be a "blank" state instead of no grid being rendered at all

**Comment by crestianiam** [comment]
I noticed that **Solution 3** suggests using ReactDOM.flushSync, but the official React documentation states that using flushSync is uncommon and can hurt the performance of your app. For this reason, I opted for **Solution 2**, which seems to work fine. Here's the code I used:
```
useEffect(() => {
    let outerTimeoutId: NodeJS.Timeout | null = null;
    let innerTimeoutId: NodeJS.Timeout | null = null;

    outerTimeoutId = setTimeout(() => {
        innerTimeoutId = setTimeout(() => {
            if (apiRef?.current) {
                apiRef.current.autosizeColumns(autoSizeOptions);
            }
        }, 200);
    }, 1000);

    return () => {
        if (outerTimeoutId) clearTimeout(outerTimeoutId);
        if (innerTimeoutId) clearTimeout(innerTimeoutId);
    };
}, [rows, apiRef, autoSizeOptions]);
```
This version better handles cases where the component gets unmounted, avoiding potential problems or errors caused by running timeouts after the component has been unmounted.

The timeout solution seems to work, but I've noticed that the outliersFactor factor doesn't seem to function correctly when rows.length is greater than pageSize. When I set pageSize to be greater than or equal to rows.length, the autosize seems to fix itself.
Has anyone encountered a similar issue? I haven't been able to fully debug it yet. In the meantime, I've set includeOutliers directly to true because, even with a factor of 4 which should be quite broad it didn't seem to adjust properly.

**Comment by ATSeeq** [comment]
I was struggling with the same issue for the past couple of days.
Having tried all the above solutions, there was always something amiss.
I ended up using the `autosizeOnMount`. Then to 'force' the grid to remount once the data is fetched, I provide the data grid with a new [key](https://react.dev/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key).

Are there any potential issues with this solution, that I might be overlooking?

**Comment by Duskfen** [comment]
Another solution I found for my usecase: 

using the new useDeferredValue from React 19:

```
  /** This has to be deferred so we can use it in the effect to autosize the columns after they are rendered and not before  */
  const deferredIsLoading = useDeferredValue(
    props.isLoading
  );

  useEffect(() => {
    console.log('fetchingstat changed');
    if (apiRef.current && !deferredIsLoading) {
      void apiRef.current.autosizeColumns();
    }
  }, [apiRef, deferredIsLoading]);

...
        <DataGrid
          loading={deferredIsLoading}
...
```
Here the `deferredIsLoading` is always a render behind `props.isLoading`
So when actual loading is finished, in the first render of the dataGrid the columns already get populated (however it is still in the loading state)
Immediately after that, `deferredIsLoading` changes and triggers the useEffect where the autoSizeColumns can already measure the real widths of the columns. 

This might not be intuitiv, but in my opinion better then using flushSync, setTimeout or mounting the grid after loading.


Note: This might not work when the loadingOverlay variant with rows is 'skeleton'. If you want to achive this, you might need to pass not `deferredIsLoading` to the dataGrid, but `props.isLoading`
