### ISSUE TITLE
[pickers] Days go blank when selecting date outside DST

### ISSUE THREAD

**Issue by tondi** [mui/mui-x#10579]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-blgysy?file=Demo.tsx

Steps:
1. Select 30th of October (end of Daylight Saving Time)
2. Observe days for October disappear and get `hiddenDaySpacingFiller` class name

https://github.com/mui/mui-x/assets/25098043/6c942ab3-2ee8-4dfc-8fcd-d7e3b0b30d28

### Current behavior

The days listed under October go blank and are getting `key="Mon Sep .."` instead of `key="Mon Oct"` and a class including `hiddenDaySpacingFiller`.

### Expected behavior

Days listed under October should not be given keys related to September but October, and should not include `hiddenDaySpacingFiller` class name. Days of October should be selectable.

### Context

Hello MUI X team! Many thanks for this awesome library. We are trying to allow users to select days outside DST in `Europe/London`. The issue seems to come from https://github.com/mui/mui-x//blob/master/packages/x-date-pickers/src/PickersDay/PickersDay.tsx#L112 and may be related to days rendering, because keys seem to be messed up when that happens.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.6
Chrome 117.0.5938.92
  
Not adding npm packages since it's reproductible on the provided live example
```
</details>

**Search keywords**: Pickers Moment Timezone blank days hiddenDaySpacingFiller

**Comment by alexfauquette** [comment]
Same issue with DayJS.

The issue seems to come from the fact if date is UTC we [early return 'UTC'](https://github.com/mui/mui-x/blob/16df383469802da1088a6c4cee13826787373af3/packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts#L241C2-L252)

Here is the moment where we move from dates in `Europe/London` to `UTC`

Same issue with Dayjs plus it bugs with daylight saving day #10584
