### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by laxmipsarva** [mui/mui-x#10585]
### The problem in depth 🔍

![Screen Shot 2023-10-04 at 4 06 36 PM](https://github.com/mui/mui-x/assets/1643813/1c386fa7-b3d3-4669-9591-f6611fcb21c7)
I was trying to click on chips in Column cells some how its not working. I am able to do cell click by including  onCellClick. I would like to click on elements inside cell

`<div style={{ height: 'calc(100vh - 300px)', width: '100%' }}>
        <DataGridPro
          {...data}
          initialState={data}
          headerHeight={36}
          disableSelectionOnClick
          slots={{
            toolbar: CustomToolbar,
          }}
          hideFooter
          onCellClick={handleColumnClick}
          sx={{
            '.MuiDataGrid-iconButtonContainer': {
              visibility: 'visible',
            },
            '.MuiDataGrid-sortIcon': {
              opacity: 'inherit !important',
            },
          }}
          sortModel={sortModel}
          onSortModelChange={(model) => setSortModel(model)}
        />
      </div>
`

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Enable click on Data grid column elements
**Order ID**: 75705

**Comment by MBilalShafi** [comment]
Also, it'll be helpful to add a more descriptive issue title, `[question]` doesn't provide much details 🙂
