### ISSUE TITLE
[Datagrid] Entering '0' or '-' in MUI DataGrid with 'number' column doesn't update the cell value on the first attempt

### ISSUE THREAD

**Issue by LondyF** [mui/mui-x#10582]
### The problem in depth 🔍

When using the MUI DataGrid with a column that has the type number, it appears that entering '0' or '-' in the cell does put it in edit mode, but the entered value won't be set. This results in users having to press '0' (or '-') twice when wanting to enter those values.

### Steps to Reproduce:

1. Create a MUI DataGrid (or[ use the demo sandbox](https://codesandbox.io/s/admiring-snow-dqx9pj). The `unit price` column has it type set to `number`) with a column configured with type: `number`.
2. Focus a cell in that column.
3. Try to enter '0' or '-'.

### Expected Behavior:
Entering '0' or '-' should set the value in the cell immediately.

### Actual Behavior:
Entering '0' or '-' only puts the cell in edit mode, but the value is not set until '0' or '-' is pressed a second time.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

System:
    OS: macOS 12.3
  Binaries:
    Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.4.0/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Edge: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.0
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.3
    @mui/core-downloads-tracker:  5.13.3
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/material: ^5.11.16 => 5.13.3
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/types:  7.2.4
    @mui/utils:  5.14.1
    @mui/x-data-grid:  6.10.1
    @mui/x-data-grid-premium: ^6.10.1 => 6.10.1
    @mui/x-data-grid-pro:  6.10.1
    @mui/x-date-pickers:  6.10.0
    @mui/x-date-pickers-pro: ^6.0.4 => 6.10.0
    @mui/x-license-pro:  6.10.0
    @types/react: 18.0.28 => 18.0.28
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5

    
</details>

**Search keywords**: datagrid editmode column
**Order ID**: 60466

**Comment by oliviertassinari** [comment]
@zannager A side note:

<img src="https://github.com/mui/mui-x/assets/3165635/270e69d1-fc7e-49f2-bdb6-cf38d37494ce" width="551">

We use the `plan: X` labels to signal what the plan the GitHub issue is about. We are not using it to signal what the plan of the user who opens the issue. Instead, we use the `support: X` labels for that use case:

<img src="https://github.com/mui/mui-x/assets/3165635/a27224ef-7024-4481-a6d3-604b47bfc973" width="793">
