### ISSUE TITLE
DataGrid filterOperators doesn't work with `getRowId`

### ISSUE THREAD

**Issue by matansec** [mui/mui-x#10598]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/eager-minsky-wt7xxv?file=/src/demo.tsx:584-599
(Try to filter on the Desk column)

Steps:
1. Create a custom filter for a column
2. Use `getRowId` on the table
3. Try to use the filter

<img width="544" alt="image" src="https://github.com/mui/mui-x/assets/92252542/aec90283-b1d7-4c12-ba89-057b69d3f2d6">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGrid filterOperators getRowId

**Comment by himacks** [comment]
I'm having this same issue here when using getRowId to redefine the default id for a column, when using a fitlerModel with custom filtering (in my case using dates), I get the same error. Here's a more detailed stack to help.

<img width="337" alt="Screenshot 2023-10-08 at 3 06 22 PM" src="https://github.com/mui/mui-x/assets/89958640/532afad3-f10e-4e79-9fe7-4a7e7eaa60f9">

**Comment by himacks** [comment]
Current work around is to use the getApplyFilterFnV7, the error happens when trying to use the params.

Here's a sandbox with the work around, getApplyFilterFn to null and use the getApplyFilterFnV7

https://codesandbox.io/s/reverent-wood-z3yh25?file=/src/demo.tsx:716-732
