### ISSUE TITLE
Data Grid jitter on vertical scroll (Intermittent)

### ISSUE THREAD

**Issue by andreskimlee** [mui/mui-x#10590]
### The problem in depth 🔍

https://github.com/mui/mui-x/assets/53020338/70ec5fad-91aa-4b11-92f7-6734ada571a6

I'm noticing some screen jittering (This happens randomly when there are many rows) during scrolling and this happens intermittently before it goes away by itself. It also happens at random intervals and is hard to reproduce. I have a tough time even getting this issue to  translate into the codesandbox template since our table is quite complex with but I was wondering if anyone ran into a similar issues?. For some more context we are using virtualization and i noticed this comment in the documentation

```
Row virtualization is limited to 100 rows in the DataGrid component.
```

Is this potentially the reason? We render hundreds of rows and i was wondering if we should be paginating by 100 for each. (Currently we render all rows without pagination)

Any insights will be super helpful.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.3
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Edge: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react:  11.10.5 
    @emotion/styled:  11.10.5 
    @mui/base:  5.0.0-alpha.103 
    @mui/core-downloads-tracker:  5.10.11 
    @mui/icons-material:  5.10.9 
    @mui/lab:  5.0.0-alpha.105 
    @mui/material:  5.10.11 
    @mui/private-theming:  5.10.9 
    @mui/styled-engine:  5.10.8 
    @mui/system:  5.10.10 
    @mui/types:  7.2.0 
    @mui/utils:  5.14.12 
    @mui/x-data-grid:  6.16.0 
    @mui/x-data-grid-premium:  6.16.0 
    @mui/x-data-grid-pro:  6.16.0 
    @mui/x-date-pickers:  5.0.6 
    @mui/x-license-pro:  6.10.2 
    @types/react:  18.0.24 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  4.8.4 
```
</details>

**Search keywords**: datagrid scroll jitter
**Order ID**: 72370

**Comment by romgrk** [comment]
> Row virtualization is limited to 100 rows in the DataGrid component.

That's not related and sounds like an outdated comment, I don't see any limit to rendered rows.

For your issue, it's not possible for us to debug further, we don't have enough to work from here. The first step would be to try to reproduce it consistently. If you can't reproduce it after modifying your code/removing features, that might tell us more about it. We'd also need to know which features you're using and how you're populating the grid.
