### ISSUE TITLE
[pickers] TimePicker disable text input

### ISSUE THREAD

**Issue by kundannetsetDemo** [mui/mui-x#10594]
### Steps to reproduce

TimePicker disable text input

### Current behavior

TimePicker disable text input

### Expected behavior

TimePicker disable text input

### Context

TimePicker disable text input

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: TimePicker disable text input
**Order ID**: TimePicker disable text input

**Comment by LukasTy** [comment]
Hello, have you tried making only the `field` `readOnly` if you want it to not have the interaction ability?
[Here is an example](https://codesandbox.io/s/clever-visvesvaraya-m6kn8x?file=/Demo.tsx).

**Comment by JerryWu1234** [comment]
I want to work on this issue.
But could you offer more information ?

**Comment by LukasTy** [comment]
> But could you offer more information about what I can do ?

We are waiting for exactly the same - understanding what are we missing to cover the authors use-case. 😉 
As it stands now, it's unclear if we are missing anything. 🤷
