### ISSUE TITLE
How to animate row entrance?

### ISSUE THREAD

**Issue by lukedukeus** [mui/mui-x#10622]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

This may already be possible, but I cannot figure out how to do it. I want new rows of my datagrid to expand as they are added, shifting old rows down gradually. The link shows the closest I could get, but it reserves space for the row according to the row height, then the row gradually fills it. Instead, I want the row to slowly grow and shift rows down. How is this possible?

### Examples 🌈

https://codesandbox.io/s/mui-animate-row-entrance-ftpmpw

**Search keywords**:

**Comment by romgrk** [comment]
That's not a feature that we support. It would require quite some work done on the virtualization logic to account for animation.

**Comment by lukedukeus** [comment]
If its that much effort, dont worry about it, just wanted to see if it was possible and there was something I was missing.
