### ISSUE TITLE
AdapterDateFns not exported from x-date-pickers

### ISSUE THREAD

**Issue by axeldvp** [mui/mui-x#10630]
[v6.16.1] Could not resolve "@mui/x-date-pickers/AdapterDateFns"

Works fine on 6.16.0

### Context

import { AdapterDateFns } from '@mui/x-date-pickers-pro/AdapterDateFns';

**Search keywords**: AdapterDateFns x-date-pickers

**Comment by alexfauquette** [comment]
Could you provide a reproduction of your issue?

I don't manage to reproduce it on codesandbox

https://codesandbox.io/s/late-monad-ljv56k?file=/Demo.tsx

**Comment by axeldvp** [comment]
I tried again, and now it works. Looks like there was a library conflict (after a git branch change / mui update). So sorry...
