### ISSUE TITLE
[pickers] Consolidate `export` strategy

### ISSUE THREAD

**Issue by michelengelen** [mui/mui-x#10632]
While working on #9226 @LukasTy pointed out that we do export components in 2 different ways:

```
export const DateCalendar = ...
``` 

... and ...

```
const DateCalender = ...

...

export { DateCalendar }
```

This is an inconsistency we can easily improve upon.

Thoughts @mui/explore ?

**Search keywords**:

**Comment by flaviendelangle** [comment]
The 2nd one is the one generated by `typescript-to-proptypes`
Not sure why, but you can't just migrate everything to the 1st one easily.
