### ISSUE TITLE
Data Grid Premium, Row grouping : How to conditionally change rows group background color ?

### ISSUE THREAD

**Issue by yessoufy** [mui/mui-x#10637]
### Summary 💡

Depending on the group data I want to change the t background color of the group
Example : 
We have this movements array : 
`  movements: [
            {
                "id": 15,
                "contractName": "CL00007762 - Firstname242 LASTNAME242",
                "contractType": "AAA",
                "subscriptionType": 101,
		"isConventionMissing":false,             
                "commissionAmount": 2.7               
            },
            {
                "id": 16,
                "contractName": "CL00007762 - Firstname242 LASTNAME242",
                "contractType": "LIFE",
                "subscriptionType": 101,
                "isConventionMissing":true, 
                "commissionAmount": 2.7                
            }
...
]`

We grouped data by contractType, contractName and subscriptionType :
` initialState={{
                    rowGrouping: {
                        model: ["contractType", "contractName", "subscriptionType"]
                    }
...}}`

In this example the property isConventionMissing can be true or false.
if one of the rows in the group has the isConventionmission property set to true we need to change the background color of the group
How do I do that?

Thanks

**Search keywords**: Data Grid Premium,Row grouping
**Order ID**: 73278

**Comment by romgrk** [comment]
You can use this prop: https://mui.com/x/api/data-grid/data-grid/#DataGrid-prop-getRowClassName

**Comment by yessoufy** [comment]
Thank you for your reply.
This function works well for a row but not for a group.
<img width="1193" alt="image" src="https://github.com/mui/mui-x/assets/147596938/bf8f0c26-f486-4449-991d-5a3d25a48848">

My goal is to change the color of the collapsed group and not just the one row in the group.

Thanks

**Comment by romgrk** [comment]
I think it should be possible to add a classname for group-level rows as well. You need to check if a children also matches the criteria you're checking for.

**Comment by yessoufy** [comment]
I think it's possible too, but how to do it?
because of the params.row object at the group level does not allow access to the children's information: 
<img width="655" alt="image" src="https://github.com/mui/mui-x/assets/147596938/f8cb4cbe-29f6-4258-950e-4886c1782ff8">

Thanks.
