### ISSUE TITLE
[pickers] When formatting a DatePicker Component with "DD MMM YYYY", default placeholder is "DD MMMM YYYY"

### ISSUE THREAD

**Issue by Sunk1st** [mui/mui-x#10641]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/peaceful-surf-3w9r4x

Steps:
1. Click on the Basic Date Picker
2. Notice that the placeholder shows DD MMMM YYYY

### Current behavior

Clicking on the Date Picker shows a placeholder of DD MMMM YYYY.

### Expected behavior

It should show DD MMM YYYY.

### Context

We are just trying to accurately show the correct date format in the placeholder.

### Your environment

We are using Google Chrome 118.0.5 on an Macbook Pro with chip Apple M1 Pro 

{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/runtime": "7.20.7",
    "@emotion/react": "11.10.6",
    "@emotion/styled": "11.10.6",
    "@krados-utils/ato-date-converter-ts": "0.2.0",
    "@krda/coord-handler": "1.3.0",
    "@krui/core": "5.1.2",
    "@krui/krados": "7.0.5",
    "@mui/icons-material": "5.11.16",
    "@mui/lab": "5.0.0-alpha.125",
    "@mui/material": "5.14.2",
    "@mui/styles": "5.11.16",
    "@mui/system": "5.12.0",
    "@mui/x-data-grid": "6.0.4",
    "@mui/x-date-pickers": "6.13.0",
    "@stomp/stompjs": "6.1.2",
    "@testing-library/react-hooks": "8.0.1",
    "@types/js-cookie": "3.0.3",
    "@types/luxon": "3.2.0",
    "@types/node": "18.15.11",
    "@types/react": "17.0.52",
    "@types/react-dom": "17.0.18",
    "@types/react-router-dom": "5.3.3",
    "@types/react-virtualized-auto-sizer": "1.0.1",
    "@types/react-window": "1.8.5",
    "@types/sockjs-client": "1.5.1",
    "date-fns": "2.29.3",
    "fontsource-roboto": "4.0.0",
    "js-cookie": "2.2.1",
    "luxon": "3.4.3",
    "markdown-to-jsx": "7.2.0",
    "prop-types": "15.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-router-dom": "6.10.0",
    "react-virtualized-auto-sizer": "1.0.7",
    "react-window": "1.8.8",
    "shell-quote": "1.7.4",
    "sockjs": "0.3.24",
    "sockjs-client": "1.6.1",
    "typeface-roboto": "1.1.13",
    "typescript": "4.9.4",
    "websocket": "1.0.34"
  },
  "paths": {
    "mainDir": "../build/resources/main",
    "staticDir": "../build/resources/main/static"
  },
  "scripts": {
    "start": "REACT_APP_PREVIOUS_SKYHOOK_VERSION=$(find ../release_notes/v* -type f -exec basename -s .md {} \\; | sort --version-sort | tail -n 2 | head -n 1) REACT_APP_SKYHOOK_VERSION=$(find ../release_notes/v* -type f -exec basename -s .md {} \\; | sort --version-sort | tail -1) HTTPS=true INLINE_RUNTIME_CHUNK=false PORT=3000 react-scripts start --ssl",
    "build": "NODE_ENV=production; REACT_APP_PREVIOUS_SKYHOOK_VERSION=$(find ../release_notes/v* -type f -exec basename -s .md {} \\; | sort --version-sort | tail -n 2 | head -n 1) REACT_APP_SKYHOOK_VERSION=$(find ../release_notes/v* -type f -exec basename -s .md {} \\; | sort --version-sort | tail -1) INLINE_RUNTIME_CHUNK=false react-scripts build",
    "postbuild": "mkdir -p $npm_package_paths_mainDir && rm -rf $npm_package_paths_staticDir && cp -r build/ $npm_package_paths_staticDir",
    "lint": "eslint '**/*.ts*'",
    "lintfix": "eslint --fix '**/*.ts*'",
    "journey": "cypress install && ELECTRON_ENABLE_LOGGING=1 cypress run --spec 'cypress/e2e/journey/**/*'",
    "perf": "cypress install && ELECTRON_ENABLE_LOGGING=1 cypress run --spec 'cypress/e2e/performance/**/*'",
    "cypress_install": "cypress install",
    "test": "react-scripts test",
    "test:journey": "ELECTRON_ENABLE_LOGGING=1 cypress open --config baseUrl=https://localhost:3000",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "proxy": "https://localhost:8443",
  "devDependencies": {
    "@testing-library/dom": "9.2.0",
    "@testing-library/jest-dom": "5.16.5",
    "@testing-library/react": "14.0.0",
    "@testing-library/user-event": "14.4.3",
    "@types/jest": "29.5.0",
    "cypress": "12.13.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "3.4.1",
    "prettier": "2.2.1",
    "react-scripts": "5.0.1",
    "ts-jest": "29.1.0"
  },
  "resolutions": {
    "@types/react": "17.0.3"
  },
  "jest": {
    "resetMocks": false,
    "transformIgnorePatterns": [
      "node_modules\\/(?!(@krados-utils|typeface-roboto))"
    ]
  }
}

**Search keywords**: MMMM, Date Formatting, mmmm, formatting

**Comment by JerryWu1234** [comment]
I want to work on this issue

**Comment by JerryWu1234** [comment]
there is very nice a entry point

**Comment by flaviendelangle** [comment]
Duplicates #9509

This is the expected behavior, the linked issues explains why and gives you a workaround to render `MMM` on your month section :+1:

**Comment by noraleonte** [comment]
@JerryWu1234 If you are interested in contributing, we mark the issues that we consider to be a good entry point with the [`good first issue`](https://github.com/mui/mui-x/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label. Feel free to check them out 🎉 
For the pickers we don't have a lot of those particularly, maybe [this one](https://github.com/mui/mui-x/issues/9311), but I encourage you to try and play around with our other libraries as well. 👍

**Comment by JerryWu1234** [comment]
> @JerryWu1234 If you are interested in contributing, we mark the issues that we consider to be a good entry point with the [`good first issue`](https://github.com/mui/mui-x/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label. Feel free to check them out 🎉 For the pickers we don't have a lot of those particularly, maybe [this one](https://github.com/mui/mui-x/issues/9311), but I encourage you to try and play around with our other libraries as well. 👍



> @JerryWu1234 If you are interested in contributing, we mark the issues that we consider to be a good entry point with the [`good first issue`](https://github.com/mui/mui-x/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label. Feel free to check them out 🎉 For the pickers we don't have a lot of those particularly, maybe [this one](https://github.com/mui/mui-x/issues/9311), but I encourage you to try and play around with our other libraries as well. 👍

thank you for helping.
I'm contributing to Muitooltap. also, I just want to get exposed to more different components, so whatever components
