### ISSUE TITLE
[data grid] Facing issues due to `disableExtendRowFullWidth` prop removed in v6

### ISSUE THREAD

**Issue by TrofinSorin** [mui/mui-x#10656]
### Steps to reproduce

Steps:

1. disableExtendRowFullWidth works in v5
2. disableExtendRowFullWidth was removed in v6
3. How can I achieve the same functionality with disableExtendRowFullWidth on v6?
On V6 with the removal of disableExtendRowFullWidth my table width is too big

### Current behavior

On V6 with the removal of disableExtendRowFullWidth my table width is too big

### Expected behavior

How can I achieve the same functionality with disableExtendRowFullWidth removed on v6?

### Context

Achieve the same functionality with disableExtendRowFullWidth removed on v6

### Your environment

npm: 6.14.17
@mui/x-data-grid": "^6.16.1

**Search keywords**: disableExtendRowFullWidth

**Comment by romgrk** [comment]
cc @mui/xgrid Not sure what that prop did, can someone answer this one?

**Comment by cherniavskii** [comment]
@TrofinSorin Can you clarify how was the `disableExtendRowFullWidth` prop useful in your case?
As far as I remember, it didn't impact the grid width.

**Comment by MBilalShafi** [comment]
@TrofinSorin Did you already have a look over the alternate suggested in the data grid v6 [migration guide](https://mui.com/x/migration/migration-data-grid-v5/#removed-props) by any chance?

**Comment by TrofinSorin** [comment]
Based on v5 documentation: If true, rows will not be extended to fill the full width of the grid container.

@cherniavskii It helped me so the table won't have a very big width when using flex: 1 in the column config.
@MBilalShafi I did, it says only that it's been removed.
