### ISSUE TITLE
[DateCalendar] Excessive empty space at the bottom of the calendar

### ISSUE THREAD

**Issue by sjdeak** [mui/mui-x#10662]
### Steps to reproduce

Hello , coming from https://github.com/mui/mui-x/pull/5073 , DateCalendar component also has same issue as DayPicker.

Link to live example: (required)

Reproduce Steps:
1. Go to MUI X official website https://mui.com/x/react-date-pickers/date-calendar/
2. Though October only have 5 weeks, there is still empty space at the bottom of the calendar view
![CleanShot 2023-10-13 at 11 52 28](https://github.com/mui/mui-x/assets/8575264/86405405-95e5-49dc-ae70-03d97fdc9b15)

### Current behavior

Though October only have 5 weeks, there is still empty space at the bottom of the calendar view

### Expected behavior

When a month only have 5 weeks rather than 6 weeks, should decrease the calendar height.

### Context

This is my app which uses <DateCalendar> you can there is a large margin between the DateCalendar and divider line.

![CleanShot 2023-10-13 at 11 55 56](https://github.com/mui/mui-x/assets/8575264/1d8eb95a-a686-4c0d-b385-4b14ac1df42c)

### Your environment

I checked the MUI X official website which uses latest version, the issue is still there.

**Search keywords**: calendar empty space

**Comment by flaviendelangle** [comment]
Thanks for your feedback

It's the expected behavior.
Even though October 23 have only 5 weeks, some months have 6 (e.g: December 23)
In our current design, we prefer to avoid layout shift by fixing the height rather than matching exactly the height of the content.

**Comment by sjdeak** [comment]
Thanks @flaviendelangle for the explanation, fully understood team's design consideration and I also agree we should keep layout align without shift, the problem is the last empty row looks weird and in some months users saw them and some months not, which is a misalignment. I proposed we could fill days of next months to fill the empty row when props `showDaysOutsideCurrentMonth` is enabled:


![CleanShot 2023-10-15 at 15 09 55](https://github.com/mui/mui-x/assets/8575264/d4ffb2dd-dd3e-4139-bf61-fd1ebc970aa1)

**Comment by sjdeak** [comment]
When reading your API doc, I found `fixedWeekNumber={6}` perfectly solve this issue, my issue is now fully solved, thanks for the reply!

**Comment by flaviendelangle** [comment]
Glad that you found a solution :ok_hand:
