### ISSUE TITLE
[question]: DatePicker crashes with "Cannot read properties of null (reading 'scrollTop')"

### ISSUE THREAD

**Issue by juiceo** [mui/mui-x#10690]
### The problem in depth 🔍

After upgrading to `@mui/x-date-pickers` version 6.16.2 (by following the [migration guide](https://mui.com/x/migration/migration-pickers-v5/)), all `DatePicker` components in our project crash when opening calendar, with the following error:

```
TypeError: Cannot read properties of null (reading 'scrollTop')
```
<img width="512" alt="image" src="https://github.com/mui/mui-x/assets/11797156/c29ceef1-9494-4ffa-8abe-f74412d9833c">

The `ErrorBoundary` there is our code, but the issue seems to be happening within the MUI component - maybe somehow related to the transition of the calendar dialog?

The issue also happens when just rendering an empty `DatePicker` without any props, so seems to me like some sort of issue with the component implementation. Help with this would be appreciated!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browser: Chrome

 System:
    OS: macOS 12.3
  Binaries:
    Node: 18.17.1 - ~/.nodenv/versions/18.17.1/bin/node
    Yarn: 1.19.0 - ~/code/rentle/rentle-monorepo/node_modules/.bin/yarn
    npm: 9.6.7 - ~/.nodenv/versions/18.17.1/bin/npm
  Browsers:
    Chrome: 118.0.5993.70
    Edge: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react:  11.11.1
    @emotion/styled:  11.11.0
    @mui/base:  5.0.0-beta.16
    @mui/core-downloads-tracker:  5.14.10
    @mui/material:  5.14.10
    @mui/private-theming:  5.14.10
    @mui/styled-engine:  5.14.10
    @mui/system:  5.14.10
    @mui/types:  7.2.4
    @mui/utils:  5.14.13
    @mui/x-data-grid:  6.16.2
    @mui/x-data-grid-pro:  6.16.2
    @mui/x-date-pickers:  6.16.2
    @mui/x-date-pickers-pro:  6.16.2
    @mui/x-license-pro:  6.10.2
    @mui/x-tree-view:  6.0.0-alpha.4
    @types/react:  17.0.36
    react:  17.0.2
    react-dom:  17.0.2
    styled-components:  5.3.6
    typescript: 5.1.6 => 5.1.6```
</details>


**Search keywords**: datepicker crash null scrollTop
**Order ID**: 54121

**Comment by LukasTy** [comment]
Hi @juiceo 
I've tried replicating your problem locally using `vite`, but couldn't reproduce any issue. 😞 
I'm sorry, but until you can provide a reproduction example, I'm not sure we can be of more help.

P.S. I've tried React v18 and v17 and dev and production builds. 🤔

**Comment by juiceo** [comment]
Alright, no worries 👍 

Seems like the issue disappeared after doing the following: 

- Upgrading to React 18.2.0
- Moving `LocalizationProvider` to just be defined once at the app root, instead of separately for each date picker

Soo a bit of a mystery this one still 😄 but I suspect that the fix here was the upgrade to React 18, rather than the LocalizationProvider change.
