### ISSUE TITLE
@mui/x-data-grid-pro: async valueGetter

### ISSUE THREAD

**Issue by raysantucci** [mui/mui-x#10692]
### The problem in depth 🔍

I have a dataset that is being displayed on the DataGrid using the "rows" property. The dataset contains most of the necessary information. But for a specific column on each row, the value will need to be retrieved and calculated by making an additional async request.

Is there a way to retrieve the value of a column for each row asynchronously as the grid data is being rendered, possibly in the valueGetter or renderCell method? Is there a best practice for updating a row column after the initial dataset is bound to the DataGrid?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: @mui/x-data-grid-pro: async valueGetter
**Order ID**: 53221

**Comment by cherniavskii** [comment]
Hi @raysantucci 
We discussed this in https://github.com/mui/mui-x/issues/5705, I've shared my thoughts in https://github.com/mui/mui-x/issues/5705#issuecomment-1206268762
Feel free to comment on that issue to keep the discussion in a single place 🙂
Thanks!
