### ISSUE TITLE
[x-date-pickers] Autocomplete/autocorrect has no feedback after correction - worse for screenreaders

### ISSUE THREAD

**Issue by kylane** [mui/mui-x#10698]
### Steps to reproduce

Link to live example: (required)
Use any example with a format dd/mm/yyyy or mm/dd/yyyy

Steps:
1. type "22" for the month
2. it is autocorrected to 02 - making it valid with no feedback to the user
3. screen readers read the input "two.. two.." but dont give any feedback to the user that it was changed

This could really post some legal issue as the input is being mutated on the fly with no feedback to the user - and is worse for screen readers as it doesnt provide any advise that its autocorrected their input.

### Current behavior

Typing "22" into the month field (which would be an invalid input) is autocorrected to "02" and is considered a valid input.

### Expected behavior

Typing 22 into the month field would trigger a validation error, offering advice on what was wrong, and what was expected.

### Context

I am trying to make it usable for people with screen readers, or arent touch typers and cant monitor the input as its being handled (instantly) by the component.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datepicker autocomplete

**Comment by LukasTy** [comment]
@kylane Thank you for opening this issue! 👍 
We are aware of this issue and are investigating the best solution to take in this regard.
We already have an issue to provide proper a11y support on fields: https://github.com/mui/mui-x/issues/6384
Also, there is an open RFC listing the compromises that might come with striving for better a11y support. 🙈 https://github.com/mui/mui-x/issues/10699

I'm closing this issue as a duplicate due to the existing #6384.
Feel free to follow the mentioned issue to be notified about the progress.

**Comment by kylane** [comment]
> @kylane Thank you for opening this issue! 👍 We are aware of this issue and are investigating the best solution to take in this regard. We already have an issue to provide proper a11y support on fields: #6384 Also, there is an open RFC listing the compromises that might come with striving for better a11y support. 🙈 #10699
> 
> I'm closing this issue as a duplicate due to the existing #6384. Feel free to follow the mentioned issue to be notified about the progress.

Thanks Lucas. Will be following, but feel free to reach our if I can help.

**Comment by kylane** [comment]
Hi guys - just to refresh this issue - have just upgraded to 7.2.0 for the Date Pickers - and still having the same issues above.

Would love to know if/when we can get this sorted?
