### ISSUE TITLE
DatePicker and DateRangePicker don't always display value passed

### ISSUE THREAD

**Issue by mrkesh** [mui/mui-x#10727]
### Steps to reproduce

[CodeSandbox link](https://codesandbox.io/s/mystifying-lamarr-259vhc?file=/src/App.js)

Steps:
1. Open the picker and choose a date in the middle of the week
2. Open the picker again and choose a date from the same week
3. Unlike the first time, selected date is not the first day of the week, it is the one user clicked.

### Current behavior

First time around, the selected date in the picker and in the textfield is the first day of the week. For instance, if you click on 19th October 2023, the selected day will become 15th October 2023 (which is the first day of the week according to my locale settings)

When we open picker again and select 19th October again, it won't move to 15th October but instead the 19th will be kept. However, if you choose a different week, the behaviour is as expected

### Expected behavior

Whichever date you select, it should always go to the start of the week or whichever value it is set. I believe that is the expected behaviour in controlled mode 

### Context

I have `DatePicker` and a `DateRangePicker` components where I need to move the clicked date to the start of the week. The fact the behaviour is consistent affects UI experience for users.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.5.2
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.70
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.8 
    @mui/core-downloads-tracker:  5.14.1 
    @mui/icons-material:  5.14.1 
    @mui/lab:  5.0.0-alpha.137 
    @mui/material:  5.14.1 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.14.1 
    @mui/types:  7.2.6 
    @mui/utils:  5.14.13 
    @mui/x-data-grid:  6.11.2 
    @mui/x-data-grid-pro:  6.11.2 
    @mui/x-date-pickers:  6.16.2 
    @mui/x-date-pickers-pro:  6.16.2 
    @mui/x-license-pro:  6.10.2 
    @types/react:  18.2.22 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  5.2.2 
```
</details>

**Search keywords**: date picker, pickers, datepicker controlled state

**Comment by LukasTy** [comment]
Thank you for opening this issue! 🙏 
It looks like the same problem as https://github.com/mui/mui-x/issues/10424 and just increases the incentive to work on it ASAP. 👌 
The underlying issue is that we are comparing if the previous value is equal to the newly provided one, before updating the  controlled value, which is not the most correct behavior on our end.
I'm closing this issue as a duplicate.
Feel free to follow the mentioned issue to get notified about it's progress.
