### ISSUE TITLE
[DataGrid] row's popup appears even when the row itself doesn't

### ISSUE THREAD

**Issue by rony-arnac** [mui/mui-x#10724]
Following this issue https://github.com/mui/mui-x/issues/5198, found another one

### Steps to reproduce

Link to live example: (required)

Steps:
1. Go here https://codesandbox.io/s/renderexpandcellgrid-demo-mui-x-forked-jzmnsw
2. Click on Column 3 cell's text
3. Scroll down

### Current behavior

Popup still visible even when the row is scrolled out of the viewport

### Expected behavior

Popup is closed /  disappears when scrolled out of viewport

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: popper popup visible
**Order ID**: 69416

**Comment by cherniavskii** [comment]
Hi @rony-arnac 
It seems like the issue is related to the custom cell renderer implementation, not the data grid itself.
Is there an issue with the data grid itself?
