### ISSUE TITLE
[DataGridPro] How to enable filtering up to seconds for datetime columns?

### ISSUE THREAD

**Issue by filipneculciu** [mui/mui-x#10736]
### The problem in depth 🔍

I'd like my datetime columns to allow the user to select up to the second when filtering, not just up to the minute. I couldn't find a good way to do this by searching the documentation; I think a custom filter might work, but it seems like overkill for such a basic requirement. 

I noticed the filter is rendered using an HTML datetime-local input (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) which allows for a "step" attribute, which you can set to 1 to get seconds input as well. But I couldn't find a way to set this property using the MUI API, I'm just defining a table and columns, not the input itself, so I don't see how I can pass inputProps. (I did find this in your API documentation: https://mui.com/x/api/data-grid/grid-filter-form/#GridFilterForm-prop-columnInputProps; but I'm not sure if it's relevant and I couldn't find any code examples for it).

### Your environment 🌎

Getting an error when running the command; but the environment is probably not very relevant for the question.

**Search keywords**: datagrid filter seconds
**Order ID**: 70895

**Comment by cherniavskii** [comment]
Hi @filipneculciu 
I've created this demo with a filter input with seconds support: https://codesandbox.io/s/intelligent-flower-st6tr4?file=/src/Demo.tsx

While you can select seconds, I believe internally the data grid ignores seconds when applying the filter.
Do you expect to only see the rows matching the exact seconds when applying the filter?

**Comment by filipneculciu** [comment]
@cherniavskii It seems to work fine for my needs. Not sure what you're referring to by "ignores the seconds", but I'm doing server side filtering, so as long as I have the seconds in the FilterModel, it's OK. Is there a way to apply this globally for all datetime columns?

**Comment by cherniavskii** [comment]
> I'm doing server side filtering

In this case it should be enough then 👍🏻
