### ISSUE TITLE
[pickers] "@mui/x-date-pickers" leads to build break on Node.js v21.0.0

### ISSUE THREAD

**Issue by jim-king-2000** [mui/mui-x#10732]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Clone the repro code from <https://github.com/jim-king-2000/bug>
2. `npm i && npm run build`
3. See the error message

And see nodejs/node#50269 for detail.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: @mui/x-date-pickers

**Comment by LukasTy** [comment]
Hello @jim-king-2000 
Thank you for creating this issue.
I've read through the linked node issue and don't really understand the intent of this issue.
They stated that the plan is to introduce the missing `navigator.userAgent` API at which point, this issue should either be no longer relevant or change drastically.
As for now, there is a suggested possible override if you insist on using Node 21, or just stick to using LTS versions (i.e. v20).

We can make a change in the code to avoid the mentioned problem, but that's not what the `Navigator` API spec defines, hence, I'm not sure if we should rush to such conclusion.

**Comment by jim-king-2000** [comment]
Thank you for the quick reply.

According to this comment: <https://github.com/nodejs/node/issues/50269#issuecomment-1772051570_>

> It's not, or shouldn't be, the responsibility of node to guarantee projects don't use faulty feature checks. 

I'm just wondering, does `LocalizationProvider` use faulty feature check?

**Comment by flaviendelangle** [comment]
The only usage of `navigator` I see that can be executed on the Node env is

```tsx
const mobileVersionMatches =
  typeof navigator !== 'undefined' && navigator.userAgent.match(/android\s(\d+)|OS\s(\d+)/i);
```

If this is the problematic code, then we could change the check with

```tsx
const mobileVersionMatches =
  typeof navigator !== 'undefined' && navigator.userAgent?.match(/android\s(\d+)|OS\s(\d+)/i);
```

To accept that `navigator` may not contain `userAgent`

Or the following if you find it more readable

```tsx
const mobileVersionMatches =
  typeof navigator === 'undefined' || !navigator.userAgent
    ? false
    : navigator.userAgent.match(/android\s(\d+)|OS\s(\d+)/i);
```

**Comment by LukasTy** [comment]
> I'm just wondering, does `LocalizationProvider` use faulty feature check?

It depends what they mean by `faulty`. 🤔 
If we are talking about `navigator` API, then it is used in a couple of places in the Picker's codebase.
In both of those cases, we are accessing the `userAgent` property, as per Web API spec, if navigator is present, it should always have `userAgent`.
Thus, I feel that Node should and probably will introduce it as the competitors (Bun and Dino) have also done it.

@flaviendelangle I'm not sure if we should rush monkey-patching issues caused by missing API in the runtime. 🤷

**Comment by flaviendelangle** [comment]
(comment updated)

**Comment by jim-king-2000** [comment]
> In both of those cases, we are accessing the userAgent property, as per Web API spec, if navigator is present, it should always have userAgent.

Great! You could post it to the original issue.

**Comment by jim-king-2000** [comment]
If adding `navigator.userAgent` will be a fix, I think we could stop here. I'll close the issue ASAP.

**Comment by jim-king-2000** [comment]
Close it since `node` will give a fix. If the same issue happens again, I'll reopen it.
