### ISSUE TITLE
Datagrid Pro Y-axis dimension keeps changing when apply 'styled'

### ISSUE THREAD

**Issue by Xinran-Ma** [mui/mui-x#10731]
### Steps to reproduce

Steps:
1. Create state `[hasScrollX, setScrollX]`
2. Create `const StyledDataGridPro = styled(DataGridPro)(({ theme }) => ({ /* empty here */ }));`
3. Create `const onResize = debounce(() => {
    if (apiRef.current.getRootDimensions()) {
      setScrollX(apiRef.current.getRootDimensions()?.hasScrollX ?? false);
    }
  });`
4. add `StyledDataGridPro` with `onResize={onResize}`

### Current behavior

The height of the data grid will be changed every 0.5 sec like shrink and expand. In React DevTools Profiler it says one of the re-rendering reasons is `DataGridProVirtualScroller`.
![Animation](https://github.com/mui/mui-x/assets/15189662/79c352e3-b449-4335-94b6-b72e962200e8)

### Expected behavior

The height of the data grid should keep steady without this 'shaking' behaviour.

### Context

This bug only happens when I apply `styled` function in step 2

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.18.0 - C:\Dev\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.8.1 - C:\Dev\nodejs\npm.CMD
  Browsers:
    Chrome: 118.0.5993.71
    Edge: Spartan (44.19041.3570.0), Chromium (117.0.2045.60)
  npmPackages:
    @emotion/react: ^11.8.2 => 11.11.1 
    @emotion/styled: ^11.8.1 => 11.11.0 
    @mui/base:  5.0.0-beta.16 
    @mui/core-downloads-tracker:  5.14.10 
    @mui/icons-material: ^5.14.11 => 5.14.9 
    @mui/material: ^5.14.11 => 5.14.10 
    @mui/private-theming:  5.14.10 
    @mui/styled-engine:  5.14.10 
    @mui/system:  5.14.10 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.10 
    @mui/x-data-grid:  6.15.0 
    @mui/x-data-grid-pro: ^6.16.0 => 6.15.0 
    @mui/x-date-pickers: ^6.16.0 => 6.15.0 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.2.22 => 18.2.22 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 
```
</details>

**Search keywords**: Datagrid Pro styled
**Order ID**: 73771

**Comment by cherniavskii** [comment]
Hi @Xinran-Ma 
Could you provide a minimal reproduction example?
You can start with this [template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx).
Thanks!
