### ISSUE TITLE
[DataGrid] Error thrown when clicking last row of the data starting from the 2nd page

### ISSUE THREAD

**Issue by zuhlke-rex** [mui/mui-x#10777]
### Steps to reproduce

This is a reproducible [codesandbox](https://codesandbox.io/embed/cocky-jones-l7mnvn?fontsize=14&hidenavigation=1&theme=dark)
1. Enable pagination and `unstable_cellSelection` in the DataGrid Premium.
2. Click next page.
3. Click on any cells of the last row.

### Current behavior

Exception thrown

<img width="729" alt="image" src="https://github.com/mui/mui-x/assets/18511059/5445465d-9003-4c2d-8d39-acab74bb521c">

### Expected behavior

Cell should be able to click without exceptions

### Context

Previous issue #10260 seems to be closed and inactive but I could produce the same error with different approach.

I would like to implement clipboard copy & pasting with client mode pagination so I could add new data in new rows and paginate. Without `unstable_cellSelection` I wouldn't able to achieve cell selection for copying / pasting.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid pagination cell selection unstable_cellSelection
**Order ID**: 76422

**Comment by MBilalShafi** [comment]
Thanks @zuhlke-rex for reporting.

I've opened a [PR](https://github.com/mui/mui-x/pull/10784) which should fix the issue.

**Comment by zuhlke-rex** [comment]
@MBilalShafi Thanks for the quick response! Looking forward to seeing the release.
