### ISSUE TITLE
[datagrid]  Unable to open aggregation drop down with keyboard commands in GridColumnMenu

### ISSUE THREAD

**Issue by Pernilla-tech** [mui/mui-x#10789]
### The problem in depth 🔍

You can find one of the demos here:  [https://mui.com/x/react-data-grid/aggregation]()

Problem: Try to navigate the menu and change the aggregation select.
Expected behavior: I expect to be able to change the aggregation function using only the keyboard.

Current behavior: The aggregation drop down only opens when clicking with the mouse, not when using keyboard commands.

![image](https://github.com/mui/mui-x/assets/77876755/403f557d-4664-4c70-9b9f-ae9c3363c9fe)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid, column menu, accessibility, aggregation
**Order ID**: 76650

**Comment by MBilalShafi** [comment]
Hey @Pernilla-tech, thank you for using MUI X Data Grid and reporting the issue regarding accessibility of the columns' menu.

Good thing is that this is already known and is in our backlog to be prioritized as some bandwidth is available. I am closing this issue to avoid duplication, please feel free to subscribe to the [original issue](https://github.com/mui/mui-x/issues/7216) for updates.
