### ISSUE TITLE
Data Grid  👍 There should be 'Done' - Button to leave filter 

### ISSUE THREAD

**Issue by theavitw** [mui/mui-x#10781]
### Summary 💡

MUI is such a great tool, helping all of the React developers seamlessly.
I am raising this issue to provide a better user experience.
Issue is-
Link : https://mui.com/x/react-data-grid/filtering/
After filtering in a data grid, the button for leavening the filter should be created instead of clicking outside the filter's area.

@jurecuhalev @gjoseph @pelotom @rosskevin @akandels 
Kindly share your views on this issue.I wanted to contribute to MUI-X with my full potential.

-- 
❤️ From Avit

### Examples 🌈

![Screenshot 2023-10-23 222747](https://github.com/mui/mui-x/assets/75948358/d5ede2f1-f4e7-4c4d-86e3-46b63d787bd7)

### Motivation 🔦

Community of MUI 

**Search keywords**: Feature Request

**Comment by MBilalShafi** [comment]
Hey @theavitw, thank you for using MUI X Data Grid and suggesting an improvement.

Just FYI, we are working on a new version of filter UI aiming to improve the usability and solve the problems it might currently have, I feel the new UI additions could be more suited to be done there. I'd appreciate it if you checkout the current progress and possibly leave some feedback on the [original issue](https://github.com/mui/mui-x/issues/6419) for the new UI design.

Thanks
