### ISSUE TITLE
Large data-set: Delete row => "No row with id # found"

### ISSUE THREAD

**Issue by egazarian** [mui/mui-x#10799]
### Steps to reproduce

Link to live example: [Codesandbox (fork from documentation example)](https://codesandbox.io/s/quirky-rui-ncv9jr?file=/src/Demo.tsx)

Steps:
1. Click on delete button fast.

### Current behavior

Clicking on delete button too fast trigger the "No row with id #1 found error" with large data-set.

### Expected behavior

No error should be triggered.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Tested on Chrome.
  System:
    OS: macOS 14.0
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Edge: Not Found
    Firefox: 119.0
    Safari: 17.0
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1 
    @emotion/styled: ^11.10.6 => 11.11.0 
    @mui/base:  5.0.0-beta.19 
    @mui/core-downloads-tracker:  5.14.13 
    @mui/icons-material: ^5.10.3 => 5.14.13 
    @mui/joy: ^5.0.0-beta.5 => 5.0.0-beta.10 
    @mui/material: ^5.11.12 => 5.14.13 
    @mui/private-theming:  5.14.13 
    @mui/styled-engine:  5.14.13 
    @mui/system:  5.14.13 
    @mui/types:  7.2.6 
    @mui/utils:  5.14.13 
    @mui/x-data-grid:  6.16.2 
    @mui/x-data-grid-premium: ^6.14.0 => 6.16.2 
    @mui/x-data-grid-pro:  6.16.2 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-date-pickers-pro:  5.0.20 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.0.0 => 18.2.28 
    react: ^18.0.2 => 18.2.0 
    react-dom: ^18.0.2 => 18.2.0 
    typescript: ^4.1.2 => 4.9.5 
```
</details>

**Search keywords**: No row with id # found large data-set delete row
**Order ID**: 75174

**Comment by egazarian** [comment]
Here a screen record:

https://github.com/mui/mui-x/assets/59256619/6ddd1141-16d3-4b80-8bb8-a58cb49fda25

**Comment by egazarian** [comment]
Checked again and noticed that the issue happens even with a 40 rows.

**Comment by cherniavskii** [comment]
I cannot reproduce the issue with the latest stable version of the data grid: https://codesandbox.io/p/sandbox/boring-euler-chtrhy
Feel free to reopen if you can still reproduce the issue.

**Comment by cstephens-cni** [comment]
I have this same problem I see tons of reports of this problem and no one seems to be able to really take it seriously.  @egazarian did upgrading fix the issue for you?

**Comment by romgrk** [comment]
If you have a reproduceable issue, please include the reproduction [code](https://mui.com/material-ui/getting-started/support/#bug-reproductions) and steps, we'll take a look.

**Comment by cherniavskii** [comment]
Interesting, I can reproduce the issue using the demo from https://github.com/mui/mui-x/issues/10799#issuecomment-1936281019
I think I didn't click fast enough back then to reproduce it.
I'll look into it.
