### ISSUE TITLE
datagrid persist toolbar's state not work

### ISSUE THREAD

**Issue by anasberkati12** [mui/mui-x#10792]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Current behavior

I want to persist my toolbar's state in localstorage and when I refresh I load my locastorage configuration instead of default one, I'v tried **useGridApiRef** but not work

### Expected behavior

When I load my page using F5 button, the column's order and sort should be loaded from localstorage.

### Your environment

not work for me

**Search keywords**: datagrid persist toolbar's state
**Order ID**: 66242

**Comment by MBilalShafi** [comment]
Hey @anasberkati12, thank you for using MUI X Data Grid.

It seems like you are looking for something like [this](https://github.com/mui/mui-x/issues/10508#issuecomment-1740628720). 

Let me know if it solves the problem you are facing. Or feel free to attach a minimum reproduction of problem on some live example.

This codesandbox [example](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) might be a good staring point.
