### ISSUE TITLE
[DataGridPremium] What would be the best way to show same row with different numbers under main row? 

### ISSUE THREAD

**Issue by bojanmitic** [mui/mui-x#10802]
### The problem in depth 🔍

I have row with some numbers that are sum of two numbers that I sum up manually and make this row. Now I want to open panel and show initial numbers with two additional rows(they should be collapsible). I tried with detail panel and I get data for column and row with params, but there we can render only react component, how I could render row there? Or alternatively I checked row grouping, but I will still need to show original row with all  data, not only grouping cell. 

 I'm using DataGrid premium. Here is image to better clarify my problem

![Screenshot 2023-10-25 at 15 48 42](https://github.com/mui/mui-x/assets/19996589/7154263e-cd5d-4863-b703-1fa7f9aaf678)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: How to render child rows with slightly different data
**Order ID**: 69131

**Comment by bojanmitic** [comment]
Hey @MBilalShafi,
Thank you for fast response. 

Both answers are valid. I decided to go with `treeData` solution. That works good. 

Since I don't need grouping column I removed it with `css`  like : 

```
	'[data-field=__tree_data_group__]': {
		display: 'none',
	}
```

I have 2 more questions:

1. Is there a better way to remove grouping column, since now I have some empty space at the end of the table (I'm 90% sure that removing that column causes empty space but might be because of some other calculations that we are doing in column width)?

2. What would be the best way to implement this empty row between main row and child rows with closing button? Is there any special features for this, or I could just add one more row between with button at the end?


Thank you in advance :)

**Comment by bojanmitic** [comment]
I found better way to hide the column. 

`apiRef.current.setColumnVisibility('__tree_data_group__', false);`

Thank you

**Comment by MBilalShafi** [comment]
Great, you could also use [`columnVisibilityModel`](https://mui.com/x/react-data-grid/column-visibility/#controlled-visible-columns) if you want to bind this to a state or something.

**Comment by bojanmitic** [comment]
Great, thank you 🙏 . 

This issue is resolved :)

**Comment by MBilalShafi** [comment]
Good to know, I'll close the issue in that case!
