### ISSUE TITLE
[TreeView] Module parse failed: Unexpected token (240:47) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by arnab2198** [mui/mui-x#10806]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

ERROR in ./node_modules/@mui/x-tree-view/node/TreeItem/TreeItem.js 240:47
Module parse failed: Unexpected token (240:47)
You may need an appropriate loader to handle this file type.
|   React.useEffect(() => {
|     if (mapFirstChar && unMapFirstChar && label) {
      mapFirstChar(nodeId, (contentRef.current?.textContent ?? '').substring(0, 1).toLowerCase());  -----> (SHOWING THE ISSUE HERE IN THIS LINE)
|       return () => {
|         unMapFirstChar(nodeId);
 @ ./node_modules/@mui/x-tree-view/node/TreeItem/index.js 6:16-37
 @ ./node_modules/@mui/lab/node/TreeItem/index.js
 @ ./node_modules/@mui/lab/node/index.js
 @ ./app/components/index.jsx
 @ ./app/helpers/Alerts/Alert.jsx
 @ ./app/helpers/index.jsx
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js

ERROR in ./node_modules/@mui/x-tree-view/node/TreeView/TreeView.js 78:63
Module parse failed: Unexpected token (78:63)
You may need an appropriate loader to handle this file type.
|   });
|   const props = (0, _extends2.default)({}, themeProps, {
     disabledItemsFocusable: themeProps.disabledItemsFocusable ?? false,  -----> (SHOWING THE ISSUE HERE IN THIS LINE)
|     disableSelection: themeProps.disableSelection ?? false,
|     multiSelect: themeProps.multiSelect ?? false,
 @ ./node_modules/@mui/x-tree-view/node/TreeView/index.js 6:16-37
 @ ./node_modules/@mui/lab/node/TreeView/index.js
 @ ./node_modules/@mui/lab/node/index.js
 @ ./app/components/index.jsx
 @ ./app/helpers/Alerts/Alert.jsx
 @ ./app/helpers/index.jsx
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.js

### Current behavior 😯

Whenever I am using the application in development mode it works fine, but while running the build with custom webpack/babel config the issue is occurring. It is creating a roadblock to use the production build. 

### Expected behavior 🤔

The issue should not occur

### Your environment 🌎

 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 14.16.0 - C:\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.11 - C:\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.2283.0), Chromium (118.0.2088.61)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.21
    @mui/core-downloads-tracker:  5.14.15
    @mui/envinfo: ^2.0.12 => 2.0.12
    @mui/icons-material: ^5.14.15 => 5.14.15
    @mui/lab: ^5.0.0-alpha.150 => 5.0.0-alpha.150
    @mui/material: ^5.14.15 => 5.14.15
    @mui/private-theming:  5.14.15
    @mui/styled-engine:  5.14.15
    @mui/styles: ^5.14.15 => 5.14.15
    @mui/system:  5.14.15
    @mui/types:  7.2.7
    @mui/utils:  5.14.15
    @mui/x-tree-view:  6.0.0-alpha.1
    @types/react:  18.2.32
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: 4.2.0 => 4.2.0

**Search keywords**:

**Comment by LukasTy** [comment]
Hello, it seems that your build process is having trouble parsing either [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) or [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operators.
Both of them seem to be available from node v14.
Could you confirm more details about your build process?
Is it by any chance targeting node versions earlier than 14?

Having a live reproduction example would help a lot. Maybe you could whip up a minimal reproduction repository with your setup that is causing the issue? 🤔

**Comment by flaviendelangle** [comment]
Both of those synthaxes are extensively used in `@mui/material` so I'm surprised that `@mui/x-tree-view` is the one throwing an error

**Comment by arnab2198** [comment]
> Hello, it seems that your build process is having trouble parsing either [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) or [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operators. Both of them seem to be available from node v14. Could you confirm more details about your build process? Is it by any chance targeting node versions earlier than 14?
> 
> Having a live reproduction example would help a lot. Maybe you could whip up a minimal reproduction repository with your setup that is causing the issue? 🤔

No, it's not targeting the node v14. I am running node v18. I am currently using a boilerplate - [React Boilerplate Github](https://github.com/react-boilerplate/react-boilerplate) || [React Boilerplate Official Site](https://www.reactboilerplate.com/)

I have upgraded react & react-dom to v18 & also the MUI to v5. Even though I am not using TreeView / TreeItem in my whole project (only using the LoadingButton from @mui/lab) still the error is showing. I have tried using the babel [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) or [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operators plugins but could not fix the issue.

**Comment by LukasTy** [comment]
@arnab2198 I've tried cloning the mentioned boilerplate and changing the `package.json` file to the one you provided, but after 15 minutes I couldn't make the installation complete. It finally failed saying that my system is not supported (Apple M1 Pro - ARM).
With all due respect, I suggest you forget about such legacy solutions that were not updated for 4+ years.
If you can provide a working repository that we can easily reproduce the problem with, we can look into the issue, but otherwise, it simply seems like an issue with a super old setup to me. 🤷
