### ISSUE TITLE
[charts] tick position displayed incorrectly in Safari

### ISSUE THREAD

**Issue by lhilgert9** [mui/mui-x#10808]
### Steps to reproduce

Link to live example: [mui.com](https://mui.com/x/react-charts/lines/#data-format)

Steps:
1. Use Safari

### Current behavior

In Safari
<img width="774" alt="Bildschirmfoto 2023-10-26 um 09 55 13" src="https://github.com/mui/mui-x/assets/77863078/e5dddf1b-abf0-4d58-881d-b48f4257537a">

### Expected behavior

Like in Chrome
<img width="774" alt="Bildschirmfoto 2023-10-26 um 09 52 29" src="https://github.com/mui/mui-x/assets/77863078/7b5cb036-9125-4d27-8063-ab43b25ae10f">

**Search keywords**: tick position, safari, charts

**Comment by alexfauquette** [comment]
Thanks for reporting this issue :+1:

Seems that Safari does not support the inheritance of `dominant-baseline`

https://webkit.org/blog/14390/release-notes-for-safari-technology-preview-174/

> Fixed dominant-baseline CSS property to be inherited ([265525@main](https://commits.webkit.org/265525@main))

Could you try to modify the DOM to add the `dominant-baseline="hanging"` to the `<tspan />`?

![image](https://github.com/mui/mui-x/assets/45398769/8d840d76-55a5-45ea-be9f-b1a1662fdd15)

**Comment by lhilgert9** [comment]
Thanks @alexfauquette, that worked. For the Y-axis it is `dominant-baseline=middle` which is not adopted. The question is should I fix the bug in the code [(ChartsText.tsx)](https://github.com/mui/mui-x/blob/master/packages/x-charts/src/internals/components/ChartsText.tsx) or should we just wait for the bug in the browser to be fixed in the next Safari update?

**Comment by alexfauquette** [comment]
It would be a pleasure to accept a PR to fix that bug. :+1:

If you do it, maybe adding a comment linking to this issue such that in one year we know this fix can be reverted could be a good idea

Don't hesitate to tag me in the PR if you do one
