### ISSUE TITLE
[charts] ChartAxisHighlight "line"-highlight is poorly visibility in dark mode

### ISSUE THREAD

**Issue by lhilgert9** [mui/mui-x#10818]
### Steps to reproduce

Link to live example: [https://mui.com/x/react-charts/lines/#data-format](https://mui.com/x/react-charts/lines/#data-format)

Steps:
1. Switch to "dark"-mode

### Current behavior

"line"-highlight stroke is "black"
<img width="1439" alt="Bildschirmfoto 2023-10-27 um 09 28 27" src="https://github.com/mui/mui-x/assets/77863078/8b507ff6-1081-46f2-9033-416c4cc0731f">

### Expected behavior

stroke should be "#fff" or "white"
<img width="1439" alt="Bildschirmfoto 2023-10-27 um 09 33 25" src="https://github.com/mui/mui-x/assets/77863078/06edea99-d26b-409a-a4a4-4ee6aa971449">

**Search keywords**: dark mode, highlight, charts

**Comment by lhilgert9** [comment]
I think the easiest solution is to implement a function
```ts
getStrokeColor(variant: AxisHighlight, theme: Theme)
```
like in [https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts) the `getBorderColor(theme: Theme)` funtion. Then we can change the stroke for both, "band" and "line", dynamically when dark/light mode is toggled.

**Comment by LukasTy** [comment]
@lhilgert9 Thank you for opening this issue and providing a suggestion. 😉 
I'll look into making the `path` a styled component that could hopefully be styled via `themeOverrides`. 🤞

**Comment by lhilgert9** [comment]
@LukasTy that sounds like a nicer solution. Let me know if I can help.
