### ISSUE TITLE
[pickers] Allow showing only the selected week numbers on the DateRangePicker text field

### ISSUE THREAD

**Issue by roelvdwater** [mui/mui-x#10823]
### Summary 💡

We are using the `DateRangePicker` component and would like to show the selected week numbers only. For example, when selecting the last three weeks of December, it should show `50 - 52`. Our users are interested in selecting entire weeks, which we have achieved by using the `shouldDisableDate` function, so they are also only interested in seeing the selected week numbers in the text field.

We are using `moment` and `AdapterMoment` on our `LocalizationProvider ` and according to [moment's format documentation](https://momentjs.com/docs/#/displaying/format/), `w` should be used as a token to get the week number. However, this does not work in the `DateRangePicker`. We have considered calculating the weeks ourselves and putting it in an escaped string, such as `[50 - 52]`, but only specifying an escaped string isn't supported as seen in [this issue](https://github.com/mui/mui-x/issues/10279) and from personal experience.

This [CodeSandbox](https://codesandbox.io/s/sharp-mountain-lk2nqd?file=/src/demo.tsx) can be used to reproduce the issue. When changing the format to for example `DD`, it does indeed show the day number, but `w` doesn't work to show the week number.

Could the tokens be expanded so we can also show the selected week number(s)?

### Examples 🌈

![image](https://github.com/mui/mui-x/assets/3884615/4acdccf0-3ac8-42c4-8234-fad5cca30c32)

### Motivation 🔦

The lack of this feature doesn't allow us to give our users only the information they are interested it.

**Search keywords**: daterangepicker weeknumbers

**Comment by LukasTy** [comment]
Hello, this looks like the same problem as https://github.com/mui/mui-x/issues/10279
Adding support for such unique tokens is not trivial.
WDYT, would having [such solution](https://github.com/mui/mui-x/pull/10307#pullrequestreview-1621574828) help you cover your use case? 🤔

**Comment by roelvdwater** [comment]
When talking about supporting the week number token, it'd be a feature on its own, but when talking about supporting formats only consisting of escaped characters, it would indeed be the same as #10279.

I have explored the example in the proposed change. Essentially what this does is adding support for a function to generate the shown value, is that correct? If that's the case, this would also be sufficient for our use case.

**Comment by LukasTy** [comment]
> I have explored the example in the proposed change. Essentially what this does is adding support for a function to generate the shown value, is that correct? If that's the case, this would also be sufficient for our use case.

The mentioned change basically adds the option to have a field without any interactive sections (empty).
And the linked exploratory example simply uses this fact by passing the formatted week numbers as an escaped `format`.

**Comment by roelvdwater** [comment]
> The mentioned change basically adds the option to have a field without any interactive sections (empty).
> And the linked exploratory example simply uses this fact by passing the formatted week numbers as an escaped `format`.

I see. I believe this would indeed cater for our use case.

**Comment by LukasTy** [comment]
Thanks for letting us know.
I'm closing this issue as a duplicate then.
Feel free to follow the linked issue to get notified when the solution is implemented.

Please feel free to re-open this issue or create a new one if the provided solution is not sufficient. 😉
