### ISSUE TITLE
[pickers] Clearing date is not working as expected

### ISSUE THREAD

**Issue by jalalbmnf** [mui/mui-x#10842]
### Steps to reproduce

https://mui.com/x/react-date-pickers/date-picker/

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Mui Datepicker

**Comment by jalalbmnf** [comment]
[

https://github.com/mui/mui-x/assets/53921355/84334565-81f7-46ad-8ccb-40efe216ec90

](url)

**Comment by LukasTy** [comment]
Hello @jalalbmnf 
Could you please clarify what you think is actually not working as expected? 🤔 

The section selection is working very similarly to how the [native date input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#basic_uses_of_date) behaves.

We also allow for both drag selecting and select all shortcut + delete clicking to clear the value.
Not to mention, that there is also an out-of-the-box option to enable additional `clearable` UI behavior.

All the options are showcased in the following video.

https://github.com/mui/mui-x/assets/4941090/df95b3ba-a90e-456c-b7b7-0cb751a26d38

**Comment by jalalbmnf** [comment]
Also is there any way to use a custom input component? Without slots or slotProps properties

**Comment by LukasTy** [comment]
> You can check the DatePicker component on Mui Datepicker documentation, when I click on to Delete key it just removes Day, Month and Year still there

And what would you expect to happen? 🤔 
Your video showcases proper behavior - you remove what is selected.
I've linked the native date input behavior, which is exactly the same.

I'm re-uploading a different video because, in the original answer, I posted an incomplete showcase video.

https://github.com/mui/mui-x/assets/4941090/3db80719-d855-4bf9-8fa9-ea1bcffef435



> Also is there any way to use a custom input component? Without slots or slotProps properties

No, there is no other option. Are you having problems with the slots approach? 🤔

**Comment by jalalbmnf** [comment]
> > You can check the DatePicker component on Mui Datepicker documentation, when I click on to Delete key it just removes Day, Month and Year still there
> 
> And what would you expect to happen? 🤔 Your video showcases proper behavior - you remove what is selected. I've linked the native date input behavior, which is exactly the same.
> 
> I'm re-uploading a different video because, in the original answer, I posted an incomplete showcase video.
> 
>  Screen.Recording.2023-10-30.at.15.22.22.mov 
> > Also is there any way to use a custom input component? Without slots or slotProps properties
> 
> No, there is no other option. Are you having problems with the slots approach? 🤔

I need to remove the date without a clear button, but I understand this thank you.

**Comment by jalalbmnf** [comment]
![Screenshot 2023-10-30 at 18 39 23](https://github.com/mui/mui-x/assets/53921355/838b8d71-2d68-4bd0-adfc-1b4c02331652)

**Comment by jalalbmnf** [comment]
![Screenshot 2023-10-30 at 18 41 39](https://github.com/mui/mui-x/assets/53921355/421c7d83-c735-49c9-bed6-6eeb46dd0892)

**Comment by jalalbmnf** [comment]
I copied this example from documentation but there is a error about `clearable`

**Comment by LukasTy** [comment]
@jalalbmnf Could you provide a live reproduction of the problem you are having?
A live example would be perfect. [This **codesandbox.io** demo](https://codesandbox.io/s/s52hsg?file=/src/Demo.tsx) _may_ be a good starting point.
Honestly, I'm most interested in the version of the package that you are using. 🤔 

I struggle to understand, why you could be having this typing issue if you are on one of the latest package versions. 🤷

**Comment by jalalbmnf** [comment]
Just it is not working with the `slots` property and I start to use `slotProps`, now everything is okay, thank you so much for your effort 🙏🏼

**Comment by kgregory** [comment]
There doesn't appear to be a way to clear a mobile date picker:

![mobileclearbutton](https://github.com/mui/mui-x/assets/3155127/fdf805e2-0bce-465b-ae95-e050fae6a90e)

Reproduction:

- View [Clearing the value](https://mui.com/x/react-date-pickers/date-picker/#clearing-the-value) on mobile
- There is no clear button after selecting a value

**Comment by LukasTy** [comment]
> There doesn't appear to be a way to clear a mobile date picker:

Such a feature was not tested and not implemented for mobile. If you would check the slots, you can see that the [`Mobile` Picker variants](https://mui.com/x/api/date-pickers/mobile-date-picker/#slots) do not have the `ClearX` slots as do the [`Desktop` counterparts](https://mui.com/x/api/date-pickers/desktop-date-picker/#slots). 😉 

Technically, it happens only because the `Mobile` pickers default to having the `readOnly` prop as true. If you would force it to `false`, then the behavior would be present, it just might not work as you would expect - the clearable button never disappears. 🤔 

To reliably add this behavior to mobile, we need to move away from the fact that the Input is in readonly state on Mobile Pickers.
We have a separate issue to tackle this.
I'll add a comment there to mention the fact that together with that proper `clearable` behavior has to be added as well. 👍

**Comment by kgregory** [comment]
> Such a feature was not tested and not implemented for mobile. If you would check the slots, you can see that the [`Mobile` Picker variants](https://mui.com/x/api/date-pickers/mobile-date-picker/#slots) do not have the `ClearX` slots as do the [`Desktop` counterparts](https://mui.com/x/api/date-pickers/desktop-date-picker/#slots). 😉

I see, I was only looking at [DatePicker > Slots](https://mui.com/x/api/date-pickers/date-picker/#slots), which has a corresponding [DatePicker Demo](https://mui.com/x/react-date-pickers/date-picker/), which is linked from the mobile and desktop specific API docs, that does not indicate that some behavior is specific to desktop.  Thanks for the clarification.

> To reliably add this behavior to mobile, we need to move away from the fact that the Input is in readonly state on Mobile Pickers.
> We have a separate issue (#7869) to tackle this.
> I'll add a comment there to mention the fact that together with that proper `clearable` behavior has to be added as well. 👍

Thanks again!  In the meantime, if anyone comes across this issue and wants something that works reasonably well, the `WrappedDatePicker` component in [this codesandbox](https://codesandbox.io/p/sandbox/wrappeddatepicker-pqdyd9) may be a suitable workaround for you.  It consistently renders the clear button for both desktop and mobile (if the datepicker is clearable).

**Comment by LukasTy** [comment]
Thank you for providing a temporary solution @kgregory.
I quickly tested your solution and wanted to let you know a couple of issues I noticed:
1. The clearable behavior does not respect `readOnly` and `disabled` props;
2. Consider avoiding the `stopPropagation` calls whenever possible.

**Comment by kgregory** [comment]
> Thank you for providing a temporary solution @kgregory. I quickly tested your solution and wanted to let you know a couple of issues I noticed:
> 
> 1. The clearable behavior does not respect `readOnly` and `disabled` props;
> 2. Consider avoiding the `stopPropagation` calls whenever possible.

Thank you!  This was biased toward my use case so I didn’t think to support those props.  I will update it.  I really appreciate you taking a look at this.

**Comment by lnhrdt** [comment]
> Thanks again! In the meantime, if anyone comes across this issue and wants something that works reasonably well, the `WrappedDatePicker` component in [this codesandbox](https://codesandbox.io/p/sandbox/wrappeddatepicker-pqdyd9) may be a suitable workaround for you. It consistently renders the clear button for both desktop and mobile (if the datepicker is clearable).

@kgregory I've come arcross this issue looking for something that works reasonably but the codesandbox link isn't working. Do you have a fresh link?

---

> > There doesn't appear to be a way to clear a mobile date picker:
> 
> Such a feature was not tested and not implemented for mobile. If you would check the slots, you can see that the [`Mobile` Picker variants](https://mui.com/x/api/date-pickers/mobile-date-picker/#slots) do not have the `ClearX` slots as do the [`Desktop` counterparts](https://mui.com/x/api/date-pickers/desktop-date-picker/#slots). 😉

@LukasTy that's so interesting it wasn't tested for mobile as it was developed! The DatePicker component [renders DesktopDatePicker or MobileDatePicker depending on the device it runs on](https://mui.com/x/react-date-pickers/date-picker/#available-components) so the current behavior is surprising. I wasn't able to find an open issue for this, would it help if I opened one?

**Comment by LukasTy** [comment]
@lnhrdt Thank you for a good observation. 🙏 
As mentioned here: https://github.com/mui/mui-x/issues/10842#issuecomment-1870298882 the clearable behavior is somewhat tied with the mobile `readOnly` behavior. Therefore, we have planned to have proper clearable behavior on mobile together with https://github.com/mui/mui-x/issues/7869.
You can just go ahead and follow that issue for updates. 😉

**Comment by lnhrdt** [comment]
Hey @LukasTy! Having forgotten the context in this issue, today I got tripped up again by the date picker clearable behavior's lack of support for mobile paired with the docs's implication that it is supported on mobile.

I don't have the bandwidth to help finish the implementation for mobile (still subscribed to #7869) but I thought I'd at least help tighten up your docs so other users (perhaps even my future self) can more easily understand the limitations of the clearable behavior. Check out #13786.

**Comment by LukasTy** [comment]
@lnhrdt Thank you for your contribution, that is a great idea. 👍 
I've re-prioritized grooming of the issue as well as added a `waiting for 👍` label to the relevant issue for good measure. 😃
