### ISSUE TITLE
[DataGrid] Customize `DataGridFIlterPanel`

### ISSUE THREAD

**Issue by LuisCarlosBarahona** [mui/mui-x#10849]
### Summary 💡

I don't know if it's a bug or a new feature request. I'm trying to include a new button inside the Filter Panel which is going to intercept the filter request and perform it just after click. Also, another button to reset the filter state to the initial state. I tried to pass the buttons component as children of the `GridFilterPanel` component but is not working. I don't know if it's possible to do this kind of customization on top of `GridFilterPanel`

### Examples 🌈

![image](https://github.com/mui/mui-x/assets/18559150/ea348568-ec2b-4331-acfa-25c1e366c604)

**Search keywords**: Filter Panel Customization Data Grid

**Comment by DanailH** [comment]
Hi, @LuisCarlosBarahona it seems that what you are trying to do is not supported with OOTB with the current implementation of the `GridFilterPannel` component. The allowed customizations can be found here: https://mui.com/x/react-data-grid/filtering/customization/#custom-filter-panel

That being said you can replace the entire `GridFilterPannel` with your custom implementation.

Another option is to use the existing filter operators but only provide your own custom `InputComponent` and add your buttons and functionality there. More on this can be found here https://mui.com/x/react-data-grid/filtering/customization/#custom-input-component

**Comment by LuisCarlosBarahona** [comment]
Thanks for your answer! I was exploring replacing the whole component, so you just confirmed my suspicions. Hope this component could be more flexible in the next versions. 😸 Since I've opened the issue, I'll close it with this comment. Feel free to re-open if needed.
