### ISSUE TITLE
[TreeView] Two different versions of @mui/x-tree-view being resolved

### ISSUE THREAD

**Issue by vadimka123** [mui/mui-x#10845]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Install @mui/lab and @mui/x-tree-view at the same time

### Current behavior 😯

Two different versions of @mui/x-tree-view being resolved
One is migrated and placed in package.json, other one from @mui/lab package

### Expected behavior 🤔

One version of @mui/x-tree-view

### Context 🔦

MUI: The TreeItem component was moved from `@mui/lab` to `@mui/x-tree-view`.', 'The component will no longer be exported from `@mui/lab` in the first release of **October 2023**.

Already the end of October 2023

**Search keywords**:

**Comment by vadimka123** [comment]
@alexfauquette , yes, exactly

**Comment by alexfauquette** [comment]
So the answer is just to wait for the tree view to be removed. might be done at the end of the week, to let us some time to be sure we don't miss something

**Comment by vadimka123** [comment]
now all good
