### ISSUE TITLE
[DataGridPro] Autosizing issues with row groups

### ISSUE THREAD

**Issue by rettoua** [mui/mui-x#10848]
### The problem in depth 🔍

I have a grouped grid and I wonder whether is there a way to make `autosizeOptions` to work for a grouped column? 
I've tried different options but still cannot make it work. Without grouping autosize works pretty well but if any of the column is grouped it doesn't work for that column.
Any help or advice is appreciated.
Here is a live example:
[https://codesandbox.io/s/async-sea-4r2smt?file=/src/Demo.tsx:945-960](https://codesandbox.io/s/async-sea-4r2smt?file=/src/Demo.tsx:945-960)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.0
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Edge: Not Found
    Safari: 17.0
  npmPackages:
    @emotion/react: ~11.11.1 => 11.11.1 
    @emotion/styled: ~11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.20 
    @mui/core-downloads-tracker:  5.14.14 
    @mui/icons-material: ~5.14.14 => 5.14.14 
    @mui/lab: ~5.0.0-alpha.149 => 5.0.0-alpha.149 
    @mui/material: ~5.14.14 => 5.14.14 
    @mui/private-theming:  5.14.14 
    @mui/styled-engine:  5.14.14 
    @mui/styles: ~5.14.14 => 5.14.14 
    @mui/system: ~5.14.14 => 5.14.14 
    @mui/types:  7.2.6 
    @mui/utils:  5.14.14 
    @mui/x-data-grid:  6.16.3 
    @mui/x-data-grid-premium: ~6.16.3 => 6.16.3 
    @mui/x-data-grid-pro:  6.16.3 
    @mui/x-date-pickers:  6.16.3 
    @mui/x-date-pickers-pro: ~6.16.3 => 6.16.3 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view: ~6.0.0-beta.0 => 6.0.0-beta.0 
    @types/react: ~18.2.21 => 18.2.21 
    react: ~17.0.2 => 17.0.2 
    react-dom: ~17.0.2 => 17.0.2 
    typescript: ~4.9.5 => 4.9.5 
```
</details>

**Search keywords**: datagrid
**Order ID**: 54867

**Comment by DanailH** [comment]
Hi @rettoua can you be more specific in what is your expectation? I tested your example and by swapping `expand: true,` with `incudeHeaders: true,` it seems to be doing what is intended.

**Comment by rettoua** [comment]
Hi @DanailH , I see no impact `includeHeaders` does. What I'm looking for is a way to autosize this
![image](https://github.com/mui/mui-x/assets/46964877/62b2c845-0b68-40bf-b8d2-6ff5275f750c)

**Comment by DanailH** [comment]
I stand corrected, I doesn't seem to be working with grouped columns. 
@romgrk do you know if this case is covered by a specific configuration of the `autosizeOptions`?

**Comment by romgrk** [comment]
No, looks like a bug.

**Comment by rettoua** [comment]
hi @DanailH , will it be fixed ?

**Comment by DanailH** [comment]
Hi @rettoua, I've made it for discussion. We will check it in the coming days and see when we will be able to ship a fix. I apologize for the delay.

**Comment by kl-ang** [comment]
Any solution yet? I need this autosize grouping column as well. Pro user here.
Or is there any alternative solution?

**Comment by kl-ang** [comment]
For those who facing this issue, I manually calculate the width as temp solution.
 ```
 const calculateMaxGroupingColumnWidth = () => {
    const groupingCells = document.querySelectorAll(
      '.MuiDataGrid-pinnedColumns .MuiDataGrid-row .MuiDataGrid-treeDataGroupingCell',
    );
    let maximumWidth = 0;
    groupingCells.forEach((cell) => {
      const htmlCell = cell as HTMLElement;
      const cellStyle = window.getComputedStyle(htmlCell);
      const cellPaddingLeft = parseFloat(cellStyle.paddingLeft);
      const contentCell = htmlCell.querySelector('.MuiBox-root:nth-child(1)') as HTMLElement;
      const contentCellStyle = contentCell ? window.getComputedStyle(contentCell) : null;
      const contentCellPaddingLeft = contentCellStyle
        ? parseFloat(contentCellStyle.paddingLeft)
        : 0;
      let contentCellChildrenWidth = 0;
      if (contentCell) {
        const { children: groupCell } = contentCell;
        for (let i = 0; i < groupCell.length; i += 1) {
          const child = groupCell[i] as HTMLElement;
          contentCellChildrenWidth += child.clientWidth;
        }
      }
      const totalWidth = cellPaddingLeft + contentCellPaddingLeft + contentCellChildrenWidth;
      if (totalWidth > maximumWidth) {
        maximumWidth = totalWidth;
      }
    });
    return maximumWidth;
  };
```

**Comment by romgrk** [comment]
I've opened the PR above. Do we need to release a fix for the 6.x version?

**Comment by romgrk** [comment]
We've merged a partial fix, let's keep this one open until it's fully fixed. The follow-up PR should be coming shortly.

**Comment by romgrk** [comment]
It seems to work properly on the latest release: https://codesandbox.io/p/sandbox/gracious-matan-rs5dg4?file=%2Fsrc%2FDemo.tsx%3A76%2C9
