### ISSUE TITLE
[question] Is DataGrid missing from available components to have style override applied?

### ISSUE THREAD

**Issue by karolis-666** [mui/mui-x#10853]
### The problem in depth 🔍

Trying to apply style overrides to `DataGrid` raises TS error `'MuiDataGrid' does not exist in type 'Components<Omit<Theme, "components">>'`

I noticed `node_modules/@mui/material/styles/createTheme.d.ts` `DataGrid` is not defined

My example of usage:
```
import { ThemeOptions } from '@mui/material';

const components: ThemeOptions = {
  components: {
    MuiDataGrid: {
      styleOverrides: {
        root: ({ theme }) => ({
          // overrides here
          fontSize: '12px',
        }),
      },
    },
  },
};

export default components;
```

Is it a bug, expected behavior or wrong use of style override for `DataGrid`?

### Your environment 🌎

  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (118.0.2088.69)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.19 
    @mui/core-downloads-tracker:  5.14.13 
    @mui/icons-material: ^5.14.0 => 5.14.13
    @mui/material: ^5.14.0 => 5.14.13
    @mui/private-theming:  5.14.13
    @mui/styled-engine:  5.14.13
    @mui/system: ^5.14.0 => 5.14.13
    @mui/types:  7.2.6
    @mui/utils: ^5.14.7 => 5.14.13
    @mui/x-data-grid:  6.16.2
    @mui/x-data-grid-premium: ^6.9.2 => 6.16.2
    @mui/x-data-grid-pro:  6.16.2
    @mui/x-date-pickers: ^6.12.1 => 6.16.2
    @mui/x-license-pro: ^6.9.0 => 6.10.2
    @types/react: 18.2.28 => 18.2.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.0.0 => 5.2.2

**Search keywords**: DataGrid overrides typescript
**Order ID**: 71014

**Comment by DanailH** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by karolis-666** [comment]
Sure! Here is an example [https://codesandbox.io/s/naughty-oskar-cqc6wp?file=/src/style-overrides.ts](url)

**Comment by DanailH** [comment]
Ah ok. Would this help https://codesandbox.io/s/unruffled-ardinghelli-gms9hz?file=/src/Demo.js

Otherwise, you can create a styled component passed on `DataGrid` and style it that way. More about this here: https://mui.com/x/react-data-grid/style/#custom-theme

Internally the styles are applied to the `GridRootStyles` component, not the `DataGrid` one.
