### ISSUE TITLE
How can we apply the custom design for x datagrid aggregation row/column?

### ISSUE THREAD

**Issue by zainalihashmi** [mui/mui-x#10851]
### The problem in depth 🔍

I noticed the param.aggregation property is available inside renderCell to render custom design for the cell but i can't apply different css class as cellClassName for the aggregation row e.g:

renderCell(params) {
    if (params.aggregation) {
      return <FooterCellComponent />;
    } else {
     return <CustomCellComponent />
    }
}

**Search keywords**: datagrid aggregation custom design
**Order ID**: 77611

**Comment by DanailH** [comment]
@zainalihashmi have you checked this example https://mui.com/x/react-data-grid/aggregation/#custom-rendering? You can pass your own custom `renderCell` component only for the cell that has an aggregated value.
