### ISSUE TITLE
[DataGrid] Auto filteration is not working on clicking 'GridToolbarFilterButton'

### ISSUE THREAD

**Issue by jsnewgen7** [mui/mui-x#10854]
### Steps to reproduce

1. Choose filter mode as server
2. Set gridToolbar
3. Set filter values that doesn't contain any input values
4. Click on 'Filter' option in Grid tool bar

### Current behavior

Filter option will show pre selected values but it won't filter data on the basis of the selected values, which shouldn't be the case.
Same scenario is working fine when we try to filter by choosing filter options from 'more' menu.
![Screenshot (183)](https://github.com/mui/mui-x/assets/149473096/d83c573f-6eeb-4b91-b616-9e132901ab95)

### Expected behavior

Data must be filtered on the basis of pre selected values

### Your environment

npm:
"@mui/x-data-grid": "^6.16.0",

**Search keywords**: GridToolbarFilterButton,toolbar

**Comment by DanailH** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!
