### ISSUE TITLE
Popper position is not centered

### ISSUE THREAD

**Issue by lokomass** [mui/mui-x#10852]
### Steps to reproduce

Here is a sandbox, with default component : https://codesandbox.io/s/inspiring-lucy-9m5997

### Current behavior

With latest version, popper position is not centered : 

![image](https://github.com/mui/mui-x/assets/7886368/8f907df1-b16c-42e3-855f-4ddb35a25762)

### Expected behavior

If you change versions of picker for 6.10.0 for example, position is good

![image](https://github.com/mui/mui-x/assets/7886368/a16382d9-bfc6-46a3-8d33-bf36a6abd53d)

### Context

I want a centered popper

### Your environment

react 17.2.0

**Search keywords**: date-range-picker popper

**Comment by LukasTy** [comment]
Hello @lokomass
We have quite recently fixed this inconsistency for the range picker to be aligned to the start of the anchor (input) as the regular pickers.
There currently is no clean way to change this behavior.
But we have already explored possible temporary workarounds in #10824.
[Here is](https://codesandbox.io/s/mutable-pine-jz8x5m?file=/src/Demo.tsx) an adaptation of the solutions mentioned in the linked issue to achieve the previous behavior of centering the popper.

I'm closing this issue as a duplicate.
Feel free to follow #10824 to get notified about its progress. 😉

**Comment by lokomass** [comment]
Hello thanks for reply
In your example, popper is not centered

**Comment by LukasTy** [comment]
> Hello thanks for reply In your example, popper is not centered

Sorry, I have initially simplified the example too much.
I've updated it to work correctly on the initial render as well. 😉

**Comment by lokomass** [comment]
Thanks for reply, do you know when fix will be release please ?
Thanks again
