### ISSUE TITLE
[data grid] Implement server-side data source in row grouping

### ISSUE THREAD

**Issue by MBilalShafi** [mui/mui-x#10859]
This issue covers the server-side row-grouping (based on the data source).
Feel free to upvote the issue to see it land faster.

**Comment by shusenshrestha** [comment]
Is there a status update on this feature?

**Comment by daniellepaquetteharvey** [comment]
We are considering buying the premium grid for our product, but this feature is required for us to move forward. Any update as to when it will be availablel @MBilalShafi please?

**Comment by MBilalShafi** [comment]
Hey @daniellepaquetteharvey,

The first implementation for the server-side data source is already in progress and is expected to land in Q2 2024 which will include:
- Filtering
- Sorting
- Pagination
- Loading plain data with data source
- Tree data lazy loading

The row-grouping use case is one of the use cases to follow after the first implementation. The expected availability of this feature would be around mid-Q3 2024. Let me know if it aligns with your timeline.

CC @shusenshrestha

**Comment by DanailH** [comment]
Hi @daniellepaquetteharvey thanks for the clarification. Unfortunately, we can't commit to a specific date. We plan on working on and potentially shipping this feature by the end of Q3 so it might happen in July but given that Q3 overlaps with the summer holidays mid or end of Q3 is more likely.

**Comment by daniellepaquetteharvey** [comment]
Of course, I understand. Let's keep in touch please.

**Comment by nabilashraf** [comment]
@DanailH Hi, can I know what would be the tentative date for the shipment of this feature as well as aggregation on server side. 

Thanks.

**Comment by MBilalShafi** [comment]
Hi @nabilashraf, This one is already in progress and will most likely be shipped by the end of Q3 as mentioned above.

Regarding aggregation, it has a considerably lower priority compared to [other features](https://github.com/mui/mui-x/issues/8179). Feel free to upvote the respective [issue](https://github.com/mui/mui-x/issues/10860) if you want the priority to be raised.

**Comment by nabilashraf** [comment]
> Hi @nabilashraf, This one is already in progress and will most likely be shipped by the end of Q3 as mentioned above.
> 
> Regarding aggregation, it has a considerably lower priority compared to [other features](https://github.com/mui/mui-x/issues/8179). Feel free to upvote the respective [issue](https://github.com/mui/mui-x/issues/10860) if you want the priority to be raised.

So I should keep in mind approximately after September. Confirming the exact date as this feature relies on us shipping a feature connected to this.

**Comment by yehudamakarov** [comment]
right now i have like 500 rows in about 5 groups. even with pagination enabled, the pagination is only considering the groups, not the child rows. is this what this issue is about?

is there any kind of work around?

**Comment by tommy-wl** [comment]
@MBilalShafi,

We’re using DataGridPremium with row grouping in our project, and some groups can contain a large number of child rows. To avoid loading all rows at once, we’d like to implement lazy loading or pagination within each group - ideally with a “Fetch more rows” button shown at the bottom of an expanded group.

We’re currently using unstable_dataSource with server-side grouping, and we fetch child rows on group expansion using groupKeys, which works well for the initial load. However, we don’t see any built-in support for:

- Detecting scroll within a group,
- Triggering incremental data fetches per group, or
- Adding a “Fetch More” button automatically.

Are there any plans to support pagination or lazy loading within grouped rows, or would you recommend a specific way to implement this using current APIs?

**Support ID: 96081**
