### ISSUE TITLE
[question] Inserting an id to a column header filter

### ISSUE THREAD

**Issue by Lioralon5** [mui/mui-x#10862]
### The problem in depth 🔍

I am using the unstable_headerfilters feature in my project.
I have 5 columns in my DataGridPro and all of them have the filter field and I want to add an id to each of them.
so for example the id for the first header filter will be: "headerFilter0", for the 2nd: "headerFilter1" and so on.
I know I can make my own custom header filter and, wrap it with a div and insert an Id, but I want to use the default one.
I was able to insert an id using the slots prop but the id was the same for all header filters.

Any help appreciated!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: unstable_headerfilters column filter id
**Order ID**: a8f8af7b889d6d97b189e8aa45bbe00dTz01NjA1NSxFPTE3MDI1NTU2NjA2MjAsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI

**Comment by MBilalShafi** [comment]
Hey @Lioralon5,
Could you provide more details on how you are inserting the ID and what's its use?
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) may be a good starting point. Thank you!

**Comment by Lioralon5** [comment]
Hey @MBilalShafi 
![image](https://github.com/mui/mui-x/assets/94195780/d587bd7c-3480-4e2b-a5cd-8ad743065152)
In this picture you can see the input fields I am talking about. They are activated with the "unstable_headerfilters" prop.

I am trying to insert an id to those elements:
![image](https://github.com/mui/mui-x/assets/94195780/7951456d-6844-4aa8-8d62-3c98fc18466a)

I was not able to recreate the case in the code sandbox because I am using the pro plan comonent "DataGridPro"

**Comment by MBilalShafi** [comment]
Thanks for the information.

You could use the `DataGridPro` in the codesandbox (only downside is, it will show watermark)
Could you try and update [this codesandbox example](https://codesandbox.io/s/datagridpro-starter-x3xjee) (uses Pro) with a minimal reproduction of your problem?

Also, do you intend to use the injected `id` for some DOM manipulation or testing or some other purpose?

**Comment by Lioralon5** [comment]
@MBilalShafi Thank you for th quick replys.
The id is requested by our QA team that need it for automated testing with selenium.
Here is the sandbox: https://codesandbox.io/s/datagridpro-starter-forked-cll3hw
I just added two props, one to activate the filters and the other to insert the id. But with this way each input field has the same id, and I want them to be unique (and consistent)

**Comment by MBilalShafi** [comment]
Just wondering if you could just use already available selectors to access the header filter cell, or is there a specific reason to use `id`?

For example:
`document.querySelector('[aria-rowindex="2"] [data-field="id"]')` would give you a header filter cell with the field `id`.

**Comment by Lioralon5** [comment]
@MBilalShafi You are right we can do that, we can use XPATH as well instead of id, but I was wondering if it's possible to insert an id directly to those elements?

**Comment by MBilalShafi** [comment]
I am not aware of another direct way to do it. You could [pass](https://mui.com/x/react-data-grid/filtering/header-filters/#customize-header-filters) your own header filter cell slot with the additional logic (reusing the original one with the custom changes could be a feasible idea)

**Comment by Lioralon5** [comment]
@MBilalShafi Yeah I thought about that, but how do I actually reuse the original one and just add an id prop to it?
