### ISSUE TITLE
Using colors with high frequency row updates

### ISSUE THREAD

**Issue by bbypls** [mui/mui-x#10872]
### Summary 💡

Using the high frequency row update example at https://mui.com/x/react-data-grid/row-updates/#high-frequency, how could we update the background color of a cell to show the user data is changing. If the value increases show one color, if it decreases show a different color.

Seems like TraceUpdates from https://mui.com/x/react-data-grid/performance/#visualization could be used but not sure how it could be applied on some select cells instead of all.

### Motivation 🔦

When using high frequency row updates I want to use color to show the user that data is changing.

**Search keywords**: high frequency color changes

**Comment by DanailH** [comment]
@bbypls This doesn't seem to be a bug report or general question about something that you are not sure if it's misbehaving. For those types of questions, you will be better off asking in StackOverflow. The GitHub issues are for regression or bugs.
