### ISSUE TITLE
[pickers] Add Month and Year calendar button slots

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#10874]
Created from: https://github.com/mui/mui-x/issues/4662#issuecomment-1779436068

We currently do not have any slots targeting `MonthCalendar` and `YearCalendar`; thus those components are pretty hard to style/override in a more complex manner.

The idea is to at minimum add `yearButton` and `monthButton` slots.

**Search keywords**:

**Comment by jansepke** [comment]
@LukasTy I would like to help here and was able to add a slot for the yearButton to `DateCalender` and `YearCalender` but the `PickersYear` component is currently not exported. What is required to export a component? I can see at least these todos:
* export component and types in index.ts
* add PropTypes
* add JSDocs to PropTypes and TS Types

**Comment by LukasTy** [comment]
@jansepke I'm sorry for the late reply.
Could you clarify which component you are trying to turn into a slot?
Is it the `PickersYear` or `PickersYearButton`?
IMHO, it would be great to make the `PickersYearButton` component a slot and then there does not seem to be a need to export it, because the only thing it does is application of a few styles. 🤔 
It could be styled via the `sx` prop or by passing a custom component.
What do you think?
