### ISSUE TITLE
[pickers] Datepicker rendered without the button in test environment

### ISSUE THREAD

**Issue by mor-stampli** [mui/mui-x#10876]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Link to live example:

Steps:

1.
2.
3.

### Current behavior 😯

I am running an app that uses MUI version 5
@mui/x-data-grid-pro: 5.7.0

i have very weird behavior.

1. instance that running chrome via macOs.
   - real pre prod env.
2.  instance running chrome via Ubuntu (chrome runs from terminal via "sudo google-chrome-stable --no-sandbox")
   - automation tests env.

first instance works great as expected.
for some reason,
DatePicker on the second instance instance is rendered with a different JSX.
picker calendar button is not rendered at all.

is there any special case for this environment ?
am i missing something?

<img width="1506" alt="Screenshot 2023-11-02 at 1 23 24 PM" src="https://github.com/mui/material-ui/assets/141311053/e79fa3f7-5695-4c2b-ad2a-338533cbf0fb">

<img width="1506" alt="Screenshot 2023-11-02 at 1 14 46 PM" src="https://github.com/mui/material-ui/assets/141311053/37ece369-b665-4752-b81d-02278b8f9612">

https://github.com/mui/material-ui/assets/141311053/c3804321-c5ff-4768-8446-9858434cd70a

### Expected behavior 🤔

i expect the DatePicker to rendered with the calendar picker icon button in all environments.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**:

**Comment by LukasTy** [comment]
Hello @mor-stampli 
It looks like you might have a problem with the Chrome launched this way not having the necessary `pointerPrecision`.
Could you please read [this documentation section](https://v5.mui.com/x/react-date-pickers/getting-started/#testing-caveats), apply the change and double-check if it fixes your problem?

P.S. We had the same issue on our end and have specified the necessary flag to avoid this problem.
https://github.com/mui/mui-x/blob/4295a7f78ef992293834c95f8ce80286b17e0558/test/karma.conf.js#L94

**Comment by mor-stampli** [comment]
@LukasTy thanks
your link with the suggestion solve the issue :)

**Comment by mor-stampli** [comment]
Hi @LukasTy ,
the solution is actually working when we run it directly from the local environment terminal,
but we also need to be able to run it via automation server.

could you please check if there is anything else we need in order to make it work ?

here you can see the code we have been try to run -> 

![image (4)](https://github.com/mui/mui-x/assets/141311053/413b8415-c2dc-4e35-b5e7-5c1da3113b93)

**Comment by LukasTy** [comment]
@mor-stampli In the https://github.com/microsoft/playwright/issues/7769#issuecomment-1205106311 I've mentioned that this setting needs to be passed via a `flag`, maybe there is an option in your used API to `addFlags` instead? 🤔 
I'm pretty sure that it's just a matter of the flag not being activated given the current way of setting it. 🤔

**Comment by dgodongm** [comment]
@LukasTy @zannager I appreciate a workaround being offered, but doesn't this point to an issue with the MUI DatePicker?

**Comment by LukasTy** [comment]
@dgodongm Why do you consider it an issue?
It is a limitation of the testing environment that can be remedied by providing a different `desktopModeMediaQuery` prop value in tests or making the test environment behavior closer to the "desktop" one (with a precise pointer). 🤔

**Comment by dgodongm** [comment]
@LukasTy Isn't it an issue that the DatePicker shows the mobile experience on a desktop environment? The workaround is also very non-intuitive and hard to discover. While the scenario might be unlikely to directly impact end-users, it's a common scenario for test automation.

**Comment by LukasTy** [comment]
> Isn't it an issue that the DatePicker shows the mobile experience on a desktop environment? The workaround is also very non-intuitive and hard to discover. While the scenario might be unlikely to directly impact end-users, it's a common scenario for test automation.

I'm not saying it is ideal, but the current default value of the prop controlling the toggle feels versatile, albeit slightly problematic. 🤔 
I don't think that relying on some arbitrary width or height would make more sense. 🤔 

@dgodongm Given that we have https://github.com/mui/mui-x/issues/10039, could you explore the suggested updated media query (`@media (hover: hover) and (pointer: fine)`) to see if it fixes the behavior on headless browsers in CI environment?
I wouldn't mind updating the default to it if it fixes CI and certain cases of improper reporting on devices. 🙈

**Comment by dgodongm** [comment]
@LukasTy I was able to workaround issue via the Chrome pointer setting (specifically using the Cypress config setting advised [here](https://github.com/mui/mui-x/issues/4845#issuecomment-2514844950)). 
If the media queries are not reliable on certain devices/environments, then perhaps there's not an obvious "fix". In the headless Chrome on Linux case, would this then not be a Chrome "bug"? 

I'd still argue that MUI's DatePicker is effectively a black box and the MUI documentation specifies certain behavior for mobile vs desktop. If there are limitations/quirks in certain cases, it'd be great if these could be documented along with possible workarounds (rather than living only in git issues). Thx for the help.

**Comment by LukasTy** [comment]
@dgodongm Were you able to discover [this section](https://mui.com/x/react-date-pickers/base-concepts/#responsive-components) in the docs? 🤔

**Comment by dgodongm** [comment]
@LukasTy This is great! Somehow I missed that in reviewing the DatePicker docs and it didn't come up when searching for solutions. The latter is probably my not choosing the right search terms. Perhaps the help doc could mention the symptoms of the headless browser scenario? Thx

**Comment by LukasTy** [comment]
@dgodongm Thank you for your suggestion. 👍 

P.S. I've tested the [updated media query](https://github.com/mui/mui-x/pull/15926/files#diff-ad2eb94cb4c75196d92810b38d94a7d91ea62f51d32e49a8b3321734b2627153R61) on headless chrome to confirm that it wouldn't change anything. 😉
