### ISSUE TITLE
[pickers] Calendar does not dynamically update when views change

### ISSUE THREAD

**Issue by Joee94** [mui/mui-x#10878]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/beautiful-http-npd2fn?file=/src/Demo.tsx

Steps:
1. Create a datepicker where the views array has the ability to change
2. Set the initial view to `year`
3. Enter a date
4. Change the view to start with `month`
5. Open the date picker
6. The datepicker opens onto year rather than month

### Current behavior

When changing views on the fly, although the TextField seems to change to the correct format of the new view, when you open the calendar it seems to default to the view set on first render.

### Expected behavior

I would expect the calendar to update to the correct view, in this case I would expect the month calendar to appear after changing the view.

### Context

I'm trying to create a DatePicker which has a select associated with it to pick the current view shown.
![Screenshot 2023-11-02 at 15 25 50](https://github.com/mui/mui-x/assets/3847039/6cfd6dd6-3fe5-4c38-a2dc-accc94df73f3)

### Your environment

Chrome used
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.5
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 119.0.6045.105
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.10.5 => 11.10.6 
    @mui/base:  5.0.0-alpha.120 
    @mui/core-downloads-tracker:  5.14.12 
    @mui/icons-material: ^5.8.4 => 5.11.11 
    @mui/lab: ^5.0.0-alpha.95 => 5.0.0-alpha.122 
    @mui/material: ^5.14.12 => 5.14.12 
    @mui/private-theming:  5.11.12 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.12 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.12 
    @mui/x-date-pickers: ^6.17.0 => 6.17.0 
    @types/react: 18.2.0 => 18.2.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components: ^5.3.6 => 5.3.8 
    typescript: ~4.9.4 => 4.9.5 

```
</details>

**Search keywords**: datepicker views dynamic

**Comment by LukasTy** [comment]
Thank you for creating this issue! 🙏 
I can confirm that the behavior is strange and needs to be investigated. 👍
