### ISSUE TITLE
[fields] Pasting in DateField on Safari can cause inconsistent UI state

### ISSUE THREAD

**Issue by sandkampderek** [mui/mui-x#10880]
### Steps to reproduce

You can try this out in Safari on the [DateField example page](https://mui.com/x/react-date-pickers/date-field/).

Steps:
1. Type a date into the field (I used 04/05/1990)
2. Select one of the date sections (I selected the month, 04)
3. Copy the value (I copied with right click, if it matters)
4. Paste the value into a different section that doesn't already have the same value (I pasted into the date section, currently 05)
5. See that the paste operation appears to do nothing
6. Blur the field. See that the field appears to have no value - you can see the placeholder text.
7. Focus the field again. See that the text input still has the value from before. However, the DateField doesn't think this value exists - if the form is submitted, the date value will be empty.

Interesting notes:
- If you paste the same value that already exists in the selected section, the bug is not triggered
- If you paste an entire date, no matter what section is selected, the bug is not triggered and the pasted date replaces the existing date in the input

### Current behavior

In Safari, when a date section is selected and a new, different value is pasted into the section, the HTML input retains its existing value, but the DateField thinks the value has been cleared, showing the input placeholder text on blur.

### Expected behavior

In Safari, when a date section is selected and a new, different value is pasted into the section, the new pasted content should replace the existing text for that section, and the DateField value should not be nulled out. If this results in an invalid date, then the typical validation behavior should occur.

### Context

We're trying to integrate this MUI date picker into our application. In particular, we're trying to support keyboard entry (i.e. DesktopDatePicker) on mobile devices such as iPhones. However, this behavior was seen in desktop Safari as well.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Safari Date picker paste empty inconsistent

**Comment by sandkampderek** [comment]
It looks like the root cause is that Safari ends up in [this condition](https://github.com/mui/mui-x/blob/b0cb729e8d77ae4c2ee36a35da2fe6b5e18214d5/packages/x-date-pickers/src/internals/hooks/useField/useField.ts#L221) on paste. But in my testing, Chrome doesn't follow that path. In Chrome, `event.nativeEvent.data` is null, but in Safari, it contains the string that was pasted (like '04')

**Comment by alexfauquette** [comment]
This issue can also be reproduced on Firefox
