### ISSUE TITLE
Project build issue

### ISSUE THREAD

**Issue by dipesh5399** [mui/mui-x#10892]
### Current behavior

I am using react + vite template. when I run yarn build command i got an error as following:
![image](https://github.com/mui/mui-x/assets/60647272/e84adf3b-9142-4e5c-a53d-6c2228ff2ca2)

not able to make build.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: react + vite template build issue

**Comment by LukasTy** [comment]
Could you please update your dependencies?
You are using the latest `x-date-pickers` package with an ancient `material` package. The oldest `@mui/material` package version supported by `@mui/x-date-pickers` is `5.8.6`, but please consider using the latest version.
