### ISSUE TITLE
Premium license key not allowing premium x-grid access

### ISSUE THREAD

**Issue by nadalton** [mui/mui-x#10891]
### The problem in depth 🔍

During our latest renewal, we upgraded from Pro to Premium. However, when replacing the license key and attempting to use x-grid premium, we receive the "MUI X License key plan mismatch" message. We have verified the new license key multiple times.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 PRO 5875U with Radeon Graphics
    Memory: 17.30 GB / 31.31 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.EXE
  Managers:
    pip3: 23.2.1 - ~\AppData\Local\Programs\Python\Python312\Scripts\pip3.EXE
  Utilities:
    Git: 2.42.0.
    Curl: 8.0.1 - C:\Windows\system32\curl.EXE
  SDKs:
    Windows SDK:
      AllowAllTrustedApps: Enabled
  IDEs:
    VSCode: 1.82.2 - C:\Users\ben.melcher\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.7.34031.279 (Visual Studio Professional 2022)
  Languages:
    Java: 20.0.2
    Python: 3.12.0
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.76)
    Internet Explorer: 11.0.19041.3570
```

"Depencies": {
    "@mui/icons-material": "5.14.3",
    "@mui/lab": "5.0.0-alpha.99",
    "@mui/material": "5.14.1",
    "@mui/styles": "5.14.1",
    "@mui/x-data-grid": "6.10.0",
    "@mui/x-data-grid-premium": "6.18.0",
    "@mui/x-date-pickers": "6.10.0",
    "@mui/x-license-pro": "6.10.0",
}
"peerDependencies": {
    "@mui/x-data-grid": "6.10.0",
    "@mui/x-data-grid-premium": "6.18.0",
    "@mui/x-date-pickers": "6.10.0",
    "@mui/x-license-pro": "6.10.0"
  },
</details>

**Search keywords**: x-grid premium
**Order ID**: 77853

**Comment by romgrk** [comment]
Can you provide a reproducible codesandbox? Check the link in the template below.

Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx) may be a good starting point. Thank you!

**Comment by nadalton** [comment]
Thank you romgrk. I'll have one of my engineers provide the example.

**Comment by nadalton** [comment]
This has been resolved and can be closed.

**Comment by bemelcher** [comment]
Hello romgrk.

I believe I have managed to solve the issue. I was exporting two slightly different xGrid elements and they both have the license auth logic. I must have missed updating the license key on the second element and it turns out that the lowest auth level that you have authorized with will take precedence.

I believe I have this fixed and I do not believe we need any further input.
