### ISSUE TITLE
The selectedSections prop on the MultiInputDateTimeRangeField is not working

### ISSUE THREAD

**Issue by bartlangelaan** [mui/mui-x#10898]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-xqjvmr?file=Demo.tsx

Steps:
- Click any of the 'day' or 'year' buttons
- The 'month' part is selected instead.

This example was [taken from the MUI docs](https://mui.com/x/react-date-pickers/fields/#control-the-selected-sections), from the "Usage with multi input range fields" part. The only thing changed was the usage of the DateTime instead of the Date component.

### Current behavior

Both props have no effect (changing the prop doesn't change the selected sections, and the onSelectedSectionsChange is not called when the selected sections are changed.

### Expected behavior

Everything works, just like the `MultiInputDateRangeField` component.

### Context

The `MultiInputDateRangeField` works perfectly and has a controlled example on the MUI docs. Just changing the component to a `MultiInputDateTimeRangeField` shows that it stops working.

### Your environment

I'm using Chrome but I expect this isn't working in any browser.

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: Not Found
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.22 
    @mui/core-downloads-tracker:  5.14.16 
    @mui/material: ^5.14.16 => 5.14.16 
    @mui/private-theming:  5.14.16 
    @mui/styled-engine:  5.14.16 
    @mui/system: ^5.8.0 => 5.14.16 
    @mui/types:  7.2.8 
    @mui/utils:  5.14.16 
    @mui/x-date-pickers: ^6.18.0 => 6.18.0 
    @mui/x-date-pickers-pro: ^6.18.0 => 6.18.0 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.2.34 => 18.2.34 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 
```
</details>

**Search keywords**: MultiInputDateTimeRangeField selectedSections onSelectedSectionsChange

**Comment by noraleonte** [comment]
Hey, @bartlangelaan 👋 
Thanks for reporting this 👍 I opened a [PR ](https://github.com/mui/mui-x/pull/10915) that will hopefully fix this issue 😁
