### ISSUE TITLE
[charts] Indicate that `min`/`max` can not be specified in `<ChartsXAxis/>`

### ISSUE THREAD

**Issue by wascou** [mui/mui-x#10905]
### Steps to reproduce

The following is not clear for me, neither in the documentation or through Axis examples.
I built a ResponsiveChartContainer with different sub elements including ChartXAxis and ChartYAxis.

### Current behavior

Specifying a min and max value in those don't work in ChartXAxis
Specifying a min and max in the xAxis value of ScatterPlot don't work either.

### Expected behavior

Setting a min or max should work

### Context

I need domain to align with 0 and the max of x and y.

### Your environment

```
<ResponsiveChartContainer
      height={500}
      series={[
        {
          data: serie.map((v: any) => ({
            x: v.x,
            y: v.y,
            ...v
          })),
          type: "scatter"
        }
      ]}
    >
      <ChartsXAxis
        axisId={DEFAULT_X_AXIS_KEY}
        min={0}
        max={123}
      />
      <ChartsYAxis
        axisId={DEFAULT_Y_AXIS_KEY}
        min={0}
        max={123}
      />
      <ScatterPlot
        xAxis={[
          {
               min: 0, max: 123
          }
        ]}
        yAxis={[
          {
               min: 0, max: 123
          }
        ]}
      />
    </ResponsiveChartContainer>
```

**Search keywords**: charts, xaxis, yaxis, domain

**Comment by wascou** [comment]
Obviously, I found the answer just publishing the issue. Answer is in the definition of xAxis in ResponsiveChartContainer.
Code is here: https://mui.com/x/react-charts/axis/#composition
Maybe an update on the documentation regarding this sentence : "It will provide all the scaling properties to its children, and allows you to use <XAxis/> and <YAxis/> components as children." I expected the ChartsXAxis component to override props from ResponsiveChartContainer.

**Comment by alexfauquette** [comment]
>  I expected the ChartsXAxis component to override props from ResponsiveChartContainer.

If it was doing so, the data display would not be aligned with axes and the all chart would be wrong  🙈

Would it solve the issue to remove `min`/`max` from the `ChartsXAxis` props?

**Comment by wascou** [comment]
Yes I guess. At least it let only one choice to people doing composition.

**Comment by alexfauquette** [comment]
@wascou Where did you find that you can provide `min`/`max` ?
I looked at the type definition, and they are not here. I typed `min` and the only proposed prop is `tickMinStep` 🤔
Same in the docs API, their is no mention of `min` for the `<ChartsXAxis />`

![image](https://github.com/mui/mui-x/assets/45398769/3339ef5e-75e8-4f73-ac26-2a13a62bbaa7)

**Comment by wascou** [comment]
Hi Alex, actualy it was in this example: https://mui.com/x/react-charts/axis/#axis-sub-domain
