### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by VermaNisha36** [mui/mui-x#10914]
### Related page

https://mui.com/x/react-date-pickers/getting-started/

### Kind of issue

Unclear explanations

### Issue description

After Installing x-datePickers package with full above mentioned steps , still giving this error , tried multiple times , Please resolve the issue ?

export 'AdapterDateFns' (imported as 'AdapterDateFns') was not found in '@mui/x-date-pickers' (possible exports: ArrowDropDownIcon, ArrowLeftIcon, ArrowRightIcon, CalendarIcon, ClearIcon, ClockIcon, DEFAULT_DESKTOP_MODE_MEDIA_QUERY, DEFAULT_LOCALE, DateCalendar, DateField, DatePicker, DatePickerToolbar, DateRangeIcon, DateTimeField, DateTimePicker, DateTimePickerTabs, DateTimePickerToolbar, DayCalendarSkeleton, DesktopDatePicker, DesktopDateTimePicker, DesktopTimePicker, DigitalClock, LocalizationProvider, MobileDatePicker, MobileDateTimePicker, MobileTimePicker, MonthCalendar, MuiPickersAdapterContext, MultiSectionDigitalClock, PickersActionBar, PickersCalendarHeader, PickersDay, PickersLayout, PickersLayoutContentWrapper, PickersLayoutRoot, PickersShortcuts, StaticDatePicker, StaticDateTimePicker, StaticTimePicker, TimeClock, TimeField, TimeIcon, TimePicker, TimePickerToolbar, YearCalendar, beBY, caES, clockClasses, clockNumberClasses, clockPointerClasses, csCZ, dateCalendarClasses, datePickerToolbarClasses, dateTimePickerTabsClasses, dateTimePickerToolbarClasses, dayCalendarSkeletonClasses, dayPickerClasses, deDE, digitalClockClasses, elGR, enUS, esES, faIR, fiFI, frFR, getDateCalendarUtilityClass, getDayCalendarSkeletonUtilityClass, getDigitalClockUtilityClass, getMonthCalendarUtilityClass, getMultiSectionDigitalClockUtilityClass, getPickersDayUtilityClass, getTimeClockUtilityClass, getYearCalendarUtilityClass, heIL, huHU, isIS, itIT, jaJP, koKR, kzKZ, monthCalendarClasses, multiSectionDigitalClockClasses, multiSectionDigitalClockSectionClasses, nbNO, nlNL, pickersCalendarHeaderClasses, pickersDayClasses, pickersFadeTransitionGroupClasses, pickersLayoutClasses, pickersMonthClasses, pickersSlideTransitionClasses, pickersYearClasses, plPL, ptBR, renderDateViewCalendar, renderDigitalClockTimeView, renderMultiSectionDigitalClockTimeView, renderTimeViewClock, roRO, ruRU, skSK, svSE, timeClockClasses, timePickerToolbarClasses, trTR, ukUA, unstable_useDateField, unstable_useDateTimeField, unstable_useTimeField, urPK, useClearableField, usePickerLayout, viVN, yearCalendarClasses, zhCN, zhHK)
<img width="960" alt="Screenshot 2023-11-06 182833" src="https://github.com/mui/mui-x/assets/71522685/75a1b328-52c8-4512-9dd7-6e7a3e022e76">

### Context 🔦

I wanted to use Datepickers , so installled this library and hence followed all steps , but getting this error

**Search keywords**: X-DatePickers Installation

**Comment by flaviendelangle** [comment]
`AdapterDateFns` is not exported from the root (to avoid bundling all the date libraries even for users not using it).

You can have a look at [this section of the Getting Started page](https://mui.com/x/react-date-pickers/getting-started/#render-your-first-component), or any other demo on the doc, the adapter is always imported from a nested endpoint (`@mui/x-date-pickers/AdapterDateFns`).

If you are not trying to import it from the root, we will indeed need a reproduction case :+1:

**Comment by VermaNisha36** [comment]
Hey team ,
The issue I experienced yesterday has been fixed by uninstalling dayjs and
switching to the moment library, which resolved the problem for me.
Surprisingly, when I attempted to use dayjs again, it worked without any
issues. It's possible that there was an installation problem that occurred
earlier.
Thank you for your quick response , I really appreciate it..
Regards
Nisha Verma
