### ISSUE TITLE
[l10n] Stop re-exporting `locales` from package root

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#10919]
We currently re-export locales from in the root `index` file so that they are available from both `import { frFR } from '@mui/x-data-grid'` and `import { frFR } from '@mui/x-data-grid/locales'`.
https://github.com/mui/mui-x/blob/947619da1c74dcffc15f79ae79c00a92a21f0fd1/packages/grid/x-data-grid/src/index.ts#L13

We should avoid root-level exporting as it doesn't solve any particular problem besides making the package seem bulkier.

Related to https://github.com/mui/material-ui/issues/39525

**Search keywords**:

**Comment by oliviertassinari** [comment]
> making the package seem bulkier

Very much agree, it doesn't help market https://bundlephobia.com/package/@mui/x-data-grid@6.18.6

![Screenshot 2024-01-04 at 17 42 48](https://github.com/mui/mui-x/assets/3165635/db815d61-c0ec-460a-a2b9-5ec186b993c1)
