### ISSUE TITLE
[pickers] Using `size` prop on `MobileTimePicker`

### ISSUE THREAD

**Issue by mfaridzia** [mui/mui-x#10925]
I have code like this:
```
<FormControl className='gap-2 mb-8' fullWidth>
  <FormLabel htmlFor='activity-date' className='text-sm' required>
    Completed Date
  </FormLabel>
  <MobileDatePicker format='dd/MM/yyyy' value={activityDatetime} />
</FormControl>

<FormControl className='gap-2 mb-8' fullWidth>
  <FormLabel htmlFor='activity-time' className='text-sm' required>
    Completed Time
  </FormLabel>
  <MobileTimePicker
    format='HH:mm'
    ampm={false}
    value={activityDatetime}
  />
</FormControl>
```

How to set the size(small | medium) like in other MUI components?

In Select component for example, i can set the size using _size_ props:
` <Select size='small' id='type' />`

Thanks

**Search keywords**:

**Comment by noraleonte** [comment]
Hey @mfaridzia 👋 

Thanks for opening this issue 💯 
The `MobileTimePicker` does not directly support a `size` prop like some of the Material UI components do. [Here ](https://mui.com/x/api/date-pickers/mobile-time-picker/)you have the full list of props supported by this component. 
I am also not entirely sure if you are trying to change the size of the TextField or the sizes of the entire component (calendar included) 🤔 
Changing the size of the `TextField` used for the picker is possible using `slotProps` like this: 
```
<MobileTimePicker
  label="Time"
  slotProps={{textField:{size:'small'}}}
/>
```
You can find the documentation of what `slotProps` are [here](https://mui.com/x/react-date-pickers/base-concepts/#overriding-slots-and-slot-props).
However, if you also want to change the styling of the calendar, you would have to customize the picker separately. 

Let me know if this helps 💯

**Comment by mfaridzia** [comment]
Thanks @noraleonte for your answer, i'm missed that part in MUI docs. Now it's work 👏
