### ISSUE TITLE
[Data Grid] QuickFilter lacks unicode normalization

### ISSUE THREAD

**Issue by wlee-vendelux** [mui/mui-x#10923]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/s/boring-pine-jwpxzk?file=/src/Demo.tsx

Steps:
1. There is a row with the name "Café"
2. Searching for "Cafe" doesn't show the row (note the é vs e)

### Current behavior

The "Café" row doesn't show when searching for "Cafe" (note the é vs e)

### Expected behavior

The "Café" row should show even when searching for "Cafe" (note the é vs e)

**Search keywords**: datagrid quick filtering filter unicode
**Order ID**: 69589

**Comment by romgrk** [comment]
This should solve your issue, feel free to reopen if it doesn't.

https://mui.com/x/react-data-grid/filtering/quick-filter/#ignore-diacritics-accents
