### ISSUE TITLE
"preProcessEditCellProps" callback not working while start editing with keyboard 

### ISSUE THREAD

**Issue by Sokheebjon** [mui/mui-x#10930]
### Steps to reproduce

 When editMode = "cell" while editing data grid cells  preProcessEditCellProps callback not working in while writing first letter when start editing with keyboard.

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx) may be a good starting point. Thank you!

You can also link directly to a documentation example instead.

**Comment by Sokheebjon** [comment]
[Screencast from 08-11-23 11:09:31.webm](https://github.com/mui/mui-x/assets/63077914/a43b26ef-32c4-444d-aa2b-320606601244)

If you look at video I wrote "12" to editable table "preProcessEditCellProps" callback should worked after I wrote "1" but it starts working after I wrote second letter. Here is the example link [Codesandbox link](https://codesandbox.io/s/amazing-edison-kp7mg7?file=/src/demo.tsx)

**Comment by atsoy** [comment]
@romgrk I know that this issue was created without any Order ID (e.g for Pro / Premium user), but as a MUI X Pro user i wanted to ask if you could share approximate ETA for the fix?

**Comment by cherniavskii** [comment]
This issue was fixed by https://github.com/mui/mui-x/pull/9205 and released in https://github.com/mui/mui-x/releases/tag/v6.18.3

v6.18.2: https://codesandbox.io/p/sandbox/jolly-river-xccj6q
v6.18.3: https://codesandbox.io/p/sandbox/solitary-moon-wptszx

**Comment by atsoy** [comment]
Thank you @cherniavskii !

**Comment by Sokheebjon** [comment]
Thank you @cherniavskii !
