### ISSUE TITLE
Customize a column before exporting to excel

### ISSUE THREAD

**Issue by oleksandrfomin5995** [mui/mui-x#10943]
### The problem in depth 🔍

Is there a way to customize a DataGrid column on the fly before generating an Excel file? 
For instance, I have a column that shows both a value and units of measurement but I only need to have the value in the Excel document, so the units need to be trimmed 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGrid Excel export
**Order ID**: 67193

**Comment by romgrk** [comment]
Have you looked at the documentation section? https://mui.com/x/react-data-grid/export/#customization
There are options to perform pre/post processing, would that solve your case?

**Comment by oleksandrfomin5995** [comment]
> Have you looked at the documentation section? https://mui.com/x/react-data-grid/export/#customization There are options to perform pre/post processing, would that solve your case?

That'll do it. Thank you!
