### ISSUE TITLE
MUI Data Grid performance issues under high load and frequent data changes 

### ISSUE THREAD

**Issue by tomaValer** [mui/mui-x#10952]
### The problem in depth 🔍

I am working on a React application dedicated to managing complex appearance objects, each comprising images (in base64 format) and metadata. The application can receive anywhere from a few to hundreds of appearances every second. The data is displayed using a grid, which was initially implemented using an HTML table. A key feature is the dynamic management of the data, where the grid maintains a cap of 400 appearances, and as new ones arrive, the oldest batch is pruned.

The transition to utilizing MUI Data Grid is aimed at leveraging its advanced features. However, during the migration, I encountered performance issues particularly when handling a high frequency of new appearances. Below are the specific challenges and questions:

# 1. Performance Degradation:

With the onset of even 10 appearances per second, the application's performance significantly degrades, becoming slow and nearly unusable, a contrast to the prior HTML table implementation which handled 100 appearances per second effortlessly.
I experimented with fetching all appearance objects from Redux, and alternatively, fetching only IDs and retrieving the object within the row, both without success.
Is there a recommended approach to optimize MUI Data Grid to handle this high-throughput, dynamic data scenario?
DataGridPro Configuration:

```
<DataGridPro
    getRowClassName={(params) => params.indexRelativeToCurrentPage % 2 === 0 ? 'MuiDataGridEvenRow' : 'MuiDataGridOddRow'}
    getRowHeight={() => 'auto'}
    showCellVerticalBorder
    showColumnVerticalBorder
    autoHeight
    {...props} 
/>
```
# 2. Adverse Impact on Other Grids:

During testing, a noticeable slowdown was observed in other components within my application utilizing Data Grid, albeit other non-MUI based components/screens operated normally.
Is there an underlying manager or singleton pattern within the MUI Data Grid that could potentially cause this performance degradation across multiple grid instances?
I am seeking guidance on best practices or configurations to mitigate the performance issues and ensure smooth operation even with a high frequency of new data entries. Additionally, insights on the impact on other grids within the application and how to isolate or prevent such cross-impact would be invaluable.

Code snippets, relevant documentation, or alternative implementation suggestions would be greatly appreciated to address the identified challenges.

Thank you in advance for your time and support.

### Your environment 🌎

browser used: chrome 
<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.17 
    @mui/core-downloads-tracker:  5.14.11 
    @mui/icons-material: ^5.14.3 => 5.14.11 
    @mui/material: ^5.14.5 => 5.14.11 
    @mui/private-theming:  5.14.11 
    @mui/styled-engine:  5.14.11 
    @mui/system:  5.14.11 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.11 
    @mui/x-data-grid: ^6.10.0 => 6.15.0 
    @mui/x-data-grid-pro: ^6.11.1 => 6.15.0 
    @mui/x-license-pro:  6.10.2 
    @types/react:  17.0.66 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.3 => 5.3.11 
    typescript: ^4.5.4 => 4.9.5 
```
</details>

**Search keywords**: data grid performance optimisation, data grid slowness
**Order ID**: 75959

**Comment by romgrk** [comment]
Have you read this entry of the docs? https://mui.com/x/react-data-grid/row-updates/#high-frequency

For further assistance, we'll need to see a reproducible case, it's hard to tell what's causing a slowdown without knowing your specific use-case. [This codesandbox.io template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx) can be used as a starting point.

**Comment by tomaValer** [comment]
I've been following the instructions in the [MUI Data Grid docs about row updates](https://mui.com/x/react-data-grid/row-updates/#high-frequency), and I'm stuck with some performance problems. Tried using throttleRowsMs but no luck.

### What I Did to Replicate My Setup:

Set up a simple Express server to send out events every few milliseconds.

Made a new React app with a hook that catches these events and sends them to Redux (batching with redux-thunk throttle middleware).

Added a basic MUI Data Grid Pro table to show the events from Redux:

```
const mapStateToProps = (state) => {
    const events = state.EventsStore.events;
    return { events };
}
```
### What I Found:

* First, I didn't limit the table height, so it wasn't using row virtualization. Fixing this in my test setup totally fixed the performance issue, even when dealing with loads of events (tried with 10/100 events a second).
* But when I tried the same fixes in my main app, it's still slow. Seems like the only thing affecting performance is the table component being connected to Redux which makes it re render, even though I used almost the same setup in my test app.

### My Question:

I'm still digging into why there's a difference between my test app and the main one, so I can't share the example yet. But in the meantime, is there a way to pull just one row's data from Redux instead of the whole table's data, using the table API? I think this could really help speed things up in my app.
I've read its possible to use a custom row component but then im loosing the column separation inside the row

**Comment by romgrk** [comment]
We can't tell why it's slow without a reproduction case, and simplifying you app so it's shareable in a codesandbox template is generally enough for you to find the cause of the issue by yourself, so I would advise to keep working on that.

I don't understand your question, can you clarify?

**Comment by tomaValer** [comment]
sure, what i will break down the question a bit.

**Current Implementation:**
Every time there is a Redux state update, the entire table data is fetched and passed to the DataGrid.
For each update, a pretty heavy operation is performed: extracting event IDs, fetching these from Redux, and then sending them to the DataGrid component using mapStateToProps.
The frequent arrival of events triggers a re-evaluation of mapStateToProps, causing performance bottlenecks.

**Assistance Requested:**

1. Is there a way to optimise this process by only sending new or changed rows to the DataGrid, instead of the whole dataset (rows prop)?
2. Alternatively, can the DataGrid be configured to receive only the row IDs, and then have each row fetch its own data (while maintaining the built-in column separation)?

**Comment by romgrk** [comment]
1. Sure, https://mui.com/x/react-data-grid/row-updates/#the-updaterows-method
2. Sure, https://mui.com/x/react-data-grid/column-definition/#value-getter, but this would make all the grid operations slightly slower.

Let me know if you need more assistance.
