### ISSUE TITLE
Prop type validation fail on PieChart

### ISSUE THREAD

**Issue by tabrath** [mui/mui-x#10989]
### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/p/sandbox/upbeat-gauss-2q9dz7)

Steps:
1. Add `innerRadius` and/or `outerRadius` to `series`
2. Set `legend.hidden` in `slotProps` to `true`

### Current behavior

* Warning: Failed prop type: The prop `dataIndex` is marked as required in `PieArcLabel`, but its value is `undefined`.
* Warning: Failed prop type: Invalid prop `innerRadius` of type `object` supplied to `PieArcLabel`, expected `number`.
* Warning: Failed prop type: Invalid prop `outerRadius` of type `object` supplied to `PieArcLabel`, expected `number`.
* Warning: Failed prop type: Invalid prop `cornerRadius` of type `object` supplied to `PieArcLabel`, expected `number`.

### Expected behavior

No warnings.

### Context

Specifying inner and outer radius and also hiding the labels.

This occurs after upgrading from 6.0.0-alpha.15 to latest stable.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.23 
    @mui/core-downloads-tracker:  5.14.17 
    @mui/material: 5.14.17 => 5.14.17 
    @mui/private-theming:  5.14.17 
    @mui/styled-engine:  5.14.17 
    @mui/system:  5.14.17 
    @mui/types:  7.2.8 
    @mui/utils:  5.14.17 
    @mui/x-charts: 6.18.1 => 6.18.1 
    @types/react: ^18.2.33 => 18.2.33 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 
```
</details>

**Search keywords**: x-charts piechart

**Comment by alexfauquette** [comment]
Thanks for reporting this issue. 

For context, when adding spring values to support animation, the component' props, the proptypes generator stoped working.

Then I removed those from `<PieArc />` but forget the `<PieArcLabel />` which are outdated

**Comment by alexfauquette** [comment]
Got fixed
