### ISSUE TITLE
Excessive white space in master detail panel in virtual scroll render zone

### ISSUE THREAD

**Issue by mdemougin** [mui/mui-x#10980]
### Steps to reproduce

This would take dozens of hours to produce as it's gated by username/password. I can execute a live demo over screen share if interested.

When using a master/detail panel there is excessive whitespace occupied by the virtual scroll render zone that I have not been able to erase using css.

### Current behavior

When you expand a the master detail panel in the following table

![image](https://github.com/mui/mui-x/assets/5830979/874e506f-f8df-4097-92e8-5d1057472627)

It expands with a lot of extra whitespace at the bottom of the panel. The only elements that contain this extra white space is the virtual scroll render zone which I cannot seem to affect. I removed the potential white space from the master-detail panel via height: fit-content, but that didn't change the whitespace.

![image](https://github.com/mui/mui-x/assets/5830979/156fe571-5112-4105-8155-c2a14ba17f82)

### Expected behavior

The next row of the table should be aligned against the detail row, minus border, margin, and padding.

### Context

I'm trying to display a UI without extraneous whitespace.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Using Chrome Version 117.0.5938.152 (Official Build) (64-bit)
  System:
    OS: Windows 10 10.0.20348
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (117.0.2045.60)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.10
    @mui/core-downloads-tracker:  5.14.4
    @mui/icons-material: ^5.14.7 => 5.14.7
    @mui/material: ^5.14.4 => 5.14.4
    @mui/private-theming:  5.14.4
    @mui/styled-engine:  5.13.2
    @mui/system:  5.14.4
    @mui/types:  7.2.4
    @mui/utils:  5.14.4
    @mui/x-data-grid: ^6.18.1 => 6.18.1
    @mui/x-data-grid-pro: ^6.18.1 => 6.18.1
    @mui/x-date-pickers: ^6.12.0 => 6.12.0
    @mui/x-license-pro: ^6.10.2 => 6.10.2
    @types/react: ^17.0.3 => 17.0.45
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.0.3 => 4.7.3
```
</details>

**Search keywords**: whitespace
**Order ID**: 72845

**Comment by romgrk** [comment]
It sounds like the `getDetailPanelHeight` might be returning an incorrect value.

If you need further assistance, make sure to provide a reproducible example. We don't know what features you're using and what custom CSS you might have, and the grid has a lot of moving parts. Unless you provide a reproducible example, it's unlikely we can help you more.

Please provide a minimal reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx) may be a good starting point. Thank you!

**Comment by mdemougin** [comment]
getDetailPanelHeight was indeed the culprit. We're displaying two different detail panels of varying height based on a conditional and they were setting the height to the same value regardless. I appreciate the assistance.
