### ISSUE TITLE
NextJS + x-charts = TypeError: Cannot read properties of undefined (reading '__emotion_styles')

### ISSUE THREAD

**Issue by Thinkscape** [mui/mui-x#10984]
### Duplicates

- [X] I have searched the existing issues

### Link to live example:
(can't deploy it because next will not build!)

### Code

https://github.com/Thinkscape/typeerror_emotion_styles

### Steps:

1. Create new, clean Next.js project (i.e. `bun x create-next-app`)
2. `bun install --save @mui/x-charts @emotion/react @emotion/styled @mui/material`
3. Use any component, i.e. `<PieChart />`

```tsx
"use client";

import { StyledEngineProvider } from "@mui/material";
import { PieChart } from "@mui/x-charts";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <StyledEngineProvider injectFirst>
        <PieChart
          series={[
            {
              data: [
                { id: 0, value: 10, label: "series A" },
                { id: 1, value: 15, label: "series B" },
                { id: 2, value: 20, label: "series C" },
              ],
            },
          ]}
          width={400}
          height={200}
        />
      </StyledEngineProvider>
    </main>
  );
}
```

### Current behavior 😯

```
 ⨯ node_modules/@mui/styled-engine/index.js (32:24) @ __emotion_styles
 ⨯ TypeError: Cannot read properties of undefined (reading '__emotion_styles')
    at __webpack_require__ (/__emotion_styles_bug/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/__emotion_styles_bug/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:8:71)
    at (ssr)/./src/app/page.tsx (/__emotion_styles_bug/.next/server/app/page.js:151:1)
    at __webpack_require__ (/__emotion_styles_bug/.next/server/webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)
```
<img width="1012" alt="image" src="https://github.com/mui/material-ui/assets/270528/43fd1eb6-3e45-4700-bb17-87511624b098">

### Expected behavior 🤔

Compile and execute.

### Context 🔦

Tried different workarounds, but it seems to fail with clean Next.js app, with or without tailwind/postcss.
I'm unable to use any of the x-charts components 😢 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: macOS 13.6.1
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @emotion/react: latest => 11.11.1
    @emotion/styled: latest => 11.11.0
    @mui/base:  5.0.0-beta.23
    @mui/core-downloads-tracker:  5.14.17
    @mui/material: latest => 5.14.17
    @mui/private-theming:  5.14.17
    @mui/styled-engine:  5.14.17
    @mui/system:  5.14.17
    @mui/types:  7.2.8
    @mui/utils:  5.14.17
    @mui/x-charts: latest => 6.18.1
    @types/react: ^18 => 18.2.37
    react: ^18 => 18.2.0
    react-dom: ^18 => 18.2.0
    typescript: ^5 => 5.2.2
```
</details>

**Search keywords**:

**Comment by flaviendelangle** [comment]
Seems to be related to https://github.com/d3/d3-interpolate/issues/58, the issue provide a solution

**Comment by alexfauquette** [comment]
Thanks for the reproduction example. Surprisingly, with `yarn` we got an error similar to #10989 but the compiling is ok 🤔

**Comment by Thinkscape** [comment]
>  is not everyone with NextJS and x-charts has this issue,

@flaviendelangle I recon not everyone is on Next 13/14 ? 
My repro is literally `create-next-app` vanila empty react app + x-charts installation. No custom config, no interop with other styling libs, just pure MUI and Next defaults.

**Comment by Thinkscape** [comment]
> Seems to be related to https://github.com/d3/d3-interpolate/issues/58, the issue provides a solution for Rollup that can probably be adapter for NextJS.

I disagree. Circular deps are allowed in Next apps, and Next+React themselves have circular deps (without any MUI components). I've only provided this snapshot because someone suggested it as diagnostic step.

Could you remove the `external dependency` tag @flaviendelangle ?
