### ISSUE TITLE
[data grid] Is there a way to make "tree data" field part of a column group?

### ISSUE THREAD

**Issue by fionaDawn** [mui/mui-x#11027]
### The problem in depth 🔍

Is there a way to make "tree data" field part of a column grouping? I have forked one of your examples and added `__tree_data_group__` as one of the children of "Internal" groupId but it's not being grouped.

Here's the forked sandbox link: https://codesandbox.io/s/serene-cori-4gqrfh?file=/demo.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.7.1
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-alpha.118 
    @mui/core-downloads-tracker:  5.14.11 
    @mui/icons-material:  5.11.9 
    @mui/lab:  5.0.0-alpha.120 
    @mui/material:  5.14.11 
    @mui/private-theming:  5.14.11 
    @mui/styled-engine:  5.14.11 
    @mui/styles:  5.11.9 
    @mui/system:  5.14.11 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.11 
    @mui/x-data-grid:  5.17.25 
    @mui/x-data-grid-pro:  5.17.25 
    @mui/x-date-pickers:  6.10.2 
    @mui/x-date-pickers-pro:  6.10.2 
    @mui/x-license-pro:  5.17.12 
    @types/react:  17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.7.4 
```
</details>

**Search keywords**: column grouping tree data
**Order ID**: 51218

**Comment by DanailH** [comment]
@fionaDawn thanks for raising this. I don't think we cover for that case. It sounds like an enhancement of the columns group feature.

**Comment by alexfauquette** [comment]
It's working with `v6.18.1`: https://codesandbox.io/s/hopeful-babycat-tf9swv?file=/demo.tsx

**Comment by fionaDawn** [comment]
you're right @alexfauquette thank you! Closing this issue now
