### ISSUE TITLE
[data grid] `apiRef.current.getRowWithUpdatedValues` not working when row edit is very fast

### ISSUE THREAD

**Issue by erezleviim** [mui/mui-x#11026]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Use `onRowEditStop` Prop. 
2. Create a function That gets row and event as params. console log apiRef.current.getRowWithUpdatedValues(row.id, "any")
3. try to edit fast and see that when you stop edit fast there a log with previous data.

### Current behavior

Im using onRowEditStop and processRowUpdate.
In my onRowEditStop function I'm using apiRef.current.getRowWithUpdatedValues() to validate the changed cells. It's working but I find that when I'm typing fast and commit change (less than a second) it is not working and returns the previous cell data. Then it affects processRowUpdate becuase the newRow is equal to previousRow. 

### Expected behavior

I need the apiRef.current.getRowWithUpdatedValues() to work always.
Another option is maybe to give the apiRef a function like validateRow to prevent from using the other functions but I think option 1 is necessary.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGrid ApiRef EditRow FastEdit EditCell

**Comment by DanailH** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!

That being said I think using debounce might solve your issue: https://mui.com/x/react-data-grid/editing/#with-debounce

**Comment by erezleviim** [comment]
> Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 . A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!
> 
> That being said I think using debounce might solve your issue: https://mui.com/x/react-data-grid/editing/#with-debounce

I updated the steps to reduce.

**Comment by DanailH** [comment]
@erezleviim I've asked for a reproduction using codesandbox so we can see the actual code. If you can do that that would be perfect. This is a requirement we have.

**Comment by erezleviim** [comment]
@DanailH Unfortunately it has been deleted so I don't have it.
But it just had a simple and minimal use of these funtions as described.

**Comment by DanailH** [comment]
I don't understand what has been deleated? You can recreate a bare minimum example of your usecase here and share it with us: https://codesandbox.io/s/datagrid-v6-quick-start-54iz1

**Comment by erezleviim** [comment]
I cant save it. so just add it to your App.tsx.
*It just an example for my using but i cant recover the bug.

import React, {useCallback} from "react";
import { DataGrid, GridRowsProp,GridRowParams, GridColDef, MuiEvent, GridRowId, useGridApiRef } from "@mui/x-data-grid";

const rows: GridRowsProp = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "XGrid", col2: "is Awesome" },
  { id: 3, col1: "Material-UI", col2: "is Amazing" },
  { id: 4, col1: "Hello", col2: "World" },
  { id: 5, col1: "XGrid", col2: "is Awesome" },
  { id: 6, col1: "Material-UI", col2: "is Amazing" }
];

const columns: GridColDef[] = [
  { field: "id", hide: true },
  { field: "col1", headerName: "Column 1", width: 150 },
  { field: "col2", headerName: "Column 2", width: 150 }
];


export default function App() {
  
const apiRef = useGridApiRef();

const triggerRowValidation = useCallback(async (rowId: GridRowId) => {
  const editableField = columns.filter(({editable}) => editable)[0].field;

  return await apiRef.current.setEditCellValue({
    id: rowId,
    field: editableField,
    value: apiRef.current.getRowWithUpdatedValues(rowId, editableField)[editableField]
  })
}, [apiRef. columns])

const handleRowEditStop = useCallback(async ({id: rowId}: GridRowParams, event: MuiEvent) => {
  if (event.key === 'Escape'){
    await triggerRowValidation(rowId) && apiRef.current.stopRowEditMode({id: rowId})
  }
}, [apiRef, triggerRowValidation])

  return (
    <div style={{ height: 300, width: "100%" }}>
      <DataGrid apiRef={apiRef} rows={rows} columns={columns} isCellEditable={true} onRowEditStop={handleRowEditStop}
      />
    </div>
  );
}
import React, {useCallback} from "react";
import { DataGrid, GridRowsProp,GridRowParams, GridColDef, MuiEvent, GridRowId, useGridApiRef } from "@mui/x-data-grid";

const rows: GridRowsProp = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "XGrid", col2: "is Awesome" },
  { id: 3, col1: "Material-UI", col2: "is Amazing" },
  { id: 4, col1: "Hello", col2: "World" },
  { id: 5, col1: "XGrid", col2: "is Awesome" },
  { id: 6, col1: "Material-UI", col2: "is Amazing" }
];

const columns: GridColDef[] = [
  { field: "id", hide: true },
  { field: "col1", headerName: "Column 1", width: 150 },
  { field: "col2", headerName: "Column 2", width: 150 }
];


export default function App() {
  
const apiRef = useGridApiRef();

const triggerRowValidation = useCallback(async (rowId: GridRowId) => {
  const editableField = columns.filter(({editable}) => editable)[0].field;

  return await apiRef.current.setEditCellValue({
    id: rowId,
    field: editableField,
    value: apiRef.current.getRowWithUpdatedValues(rowId, editableField)[editableField]
  })
}, [apiRef. columns])

const handleRowEditStop = useCallback(async ({id: rowId}: GridRowParams, event: MuiEvent) => {
  if (event.key === 'Escape'){
    await triggerRowValidation(rowId) && apiRef.current.stopRowEditMode({id: rowId})
  }
}, [apiRef, triggerRowValidation])

  return (
    <div style={{ height: 300, width: "100%" }}>
      <DataGrid apiRef={apiRef} rows={rows} columns={columns} isCellEditable={true} onRowEditStop={handleRowEditStop}
      />
    </div>
  );
}

**Comment by michelengelen** [comment]
@erezleviim I did paste your code into the template @DanailH provided, but there are some parts missing (especially how you implement the `DataGrid` and what props you use): https://codesandbox.io/p/sandbox/data-grid-community-forked-c2ph93?file=%2Fsrc%2FApp.tsx%3A45%2C9-45%2C26
Could you please go in, add the missing parts and share a link to that sandbox with us?
Only after that we are able to check what exactly isn't working for you.
Thanks 🙇🏼
