### ISSUE TITLE
latest @mui/x-date-pickers not working with Next.js 14.0.2

### ISSUE THREAD

**Issue by TheToughest** [mui/mui-x#11030]
### Steps to reproduce

Steps:
1. Create next app "npm create-next-app@latest"
2. Install date pickers module "npm i @mui/x-date-pickers@latest"
3. Create page with simple date picker component.
4. Start the app "npm run dev".
5. Enjoy the errors.

### Current behavior

When navigating to the page with the datepicker component you will encounter the following:
- "Module not found: Can't resolve '@mui/material/styles/alpha'"

### Expected behavior

Run without errors.

### Context

When upgrading form next.js 14.0.1 to 14.0.2 I started to encounter this error. 
Something probably got altered in the imports of mui which causes x-date-pickers to break.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Compatibility issues

**Comment by flaviendelangle** [comment]
Hi,

I can't reproduce your issue on my NextJS playground even after upgrading to `next@14.0.2`

Could you please provide a reproduction case?

**Comment by alexfauquette** [comment]
If the issue occurs when updating Next.JS, consider opening an issue in their repo linking to this one such that they can be aware if it's related to a problem on their side.

The v14.0.0 already broked the provider (see #10841) and got fixed by a Next.JS update

**Comment by TheToughest** [comment]
Ok so after a bit of investigating. For some reason my modularizeImports regex for mui breaks when upgrading next js from 14.0.1 to 14.0.2 which seems strange to me. Removing or altering it has resolved the issue. I'm sorry for the inconveniences causes I'll close the issue now.

**Comment by muhaimincs** [comment]
@TheToughest would you mind share your setup

**Comment by lefelaR** [comment]
/node_modules/@mui/x-date-pickers/AdapterDateFns/AdapterDateFns.js
Module not found: Package path ./_lib/format/longFormatters is not exported from package ...

**Comment by LukasTy** [comment]
@lefelaR I've tested `AdapterDateFns` on your mentioned next version and node 20 and both `dev` and `prod` builds pass without problems. 🤔 

Could it be that you are using `date-fns`@v3 with `AdapterDateFns`? 🤔 
In such a case, [please import](https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns) the adapter from `AdapterDateFnsV3`.

**Comment by kameshdhana** [comment]
> Ok so after a bit of investigating. For some reason my modularizeImports regex for mui breaks when upgrading next js from 14.0.1 to 14.0.2 which seems strange to me. Removing or altering it has resolved the issue. I'm sorry for the inconveniences causes I'll close the issue now.

@flaviendelangle 
I reverted back to 14.0.2 but still it doesn't work for me.

My package list is
```
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/icons-material": "^5.11.11",
    "@mui/material": "^5.11.12",
    "@mui/x-date-pickers": "^6.19.4",
    "date-fns": "^2.29.3",
    "dayjs": "^1.11.10",
    "next": "^14.0.1"
```

**Comment by LukasTy** [comment]
@kameshdhana Please provide a reproduction example so that we can investigate your problem.
I've tried a fresh next app install (with pages router) and pinned the package version to the ones you mentioned - the app is running without any problems... 🤷

**Comment by kameshdhana** [comment]
> @kameshdhana Please provide a reproduction example so that we can investigate your problem. I've tried a fresh next app install (with pages router) and pinned the package version to the ones you mentioned - the app is running without any problems... 🤷

I'm using app router. Is that an issue here?

**Comment by LukasTy** [comment]
> I'm using app router. Is that an issue here?

Your particular problem could hardly be related to the choice of router. 🤔 
It looks like either an incompatibility of packages or an ESM/CJS problem (`@mui` packages currently have problems working in pure ESM environments).

**Comment by muhaimincs** [comment]
How do you guys resolve this issue?

**Comment by kameshdhana** [comment]
> How do you guys resolve this issue?

I downgraded to next js version of 14.0.0
After this I'm no more getting this error.

**Comment by LukasTy** [comment]
@fayedbleh13 @stevengrimaldo Have you tried the latest v8 release?
With it, we introduced some package layout changes to support ESM/CJS better. 🤔

**Comment by WhoSV** [comment]
Hello everyone!

Does anybody was able to resolve this issue?

 `TypeError: _mui_material_useMediaQuery__WEBPACK_IMPORTED_MODULE_0__ is not a function

at useReduceAnimations (useReduceAnimations.js:16:26)
    at usePicker (usePicker.js:85:104)
    at useStaticPicker (useStaticPicker.js:63:69)
    at StaticDatePicker (StaticDatePicker.js:55:97)
    at react-stack-bottom-frame (react-dom-client.development.js:23864:20)
    at renderWithHooks (react-dom-client.development.js:5530:22)
    at updateForwardRef (react-dom-client.development.js:8646:19)
    at beginWork (react-dom-client.development.js:10862:18)
    at runWithFiberInDEV (react-dom-client.development.js:1520:30)
    at performUnitOfWork (react-dom-client.development.js:15133:22)
    at workLoopSync (react-dom-client.development.js:14957:41)
    at renderRootSync (react-dom-client.development.js:14937:11)
    at performWorkOnRoot (react-dom-client.development.js:14463:44)
    at performSyncWorkOnRoot (react-dom-client.development.js:16232:7)
    at flushSyncWorkAcrossRoots_impl (react-dom-client.development.js:16080:21)
    at processRootScheduleInMicrotask (react-dom-client.development.js:16117:7)
    at eval (react-dom-client.development.js:16251:13)

The above error occurred in the <ForwardRef(StaticDatePicker)> component.

React will try to recreate this component tree from scratch using the error boundary you provided, PagesDevOverlayErrorBoundary.`

It appeared when I updated @mui/x-date-pickers to `8.3.0` from `7.28.3`.
Also I have `next 15.3.1 and react 19.1.0`

I will really appreciate if somebody will give a hint how can I resolve it.
Thanks :)

**Comment by WhoSV** [comment]
@LukasTy Yep, I have latest `"@mui/material": "^7.1.0"`

**Comment by LukasTy** [comment]
@WhoSV Gotcha. 👌 
Does it happen with a freshly created Next project?
If not, could you create a minimal reproduction example where this problem would be reproducible? 🤔 
I suspect that you have a certain configuration, which is causing this behavior...

**Comment by WhoSV** [comment]
> [@WhoSV](https://github.com/WhoSV) Gotcha. 👌 Does it happen with a freshly created Next project? If not, could you create a minimal reproduction example where this problem would be reproducible? 🤔 I suspect that you have a certain configuration, which is causing this behavior...

Yep, will provide soon

**Comment by QAvetisyan-Sorenson** [comment]
> Hello everyone!
> 
> Does anybody was able to resolve this issue?
> 
> ```
> TypeError: _mui_material_useMediaQuery__WEBPACK_IMPORTED_MODULE_0__ is not a function
> 
> at useReduceAnimations (useReduceAnimations.js:16:26)
>     at usePicker (usePicker.js:85:104)
>     at useStaticPicker (useStaticPicker.js:63:69)
>     at StaticDatePicker (StaticDatePicker.js:55:97)
>     at react-stack-bottom-frame (react-dom-client.development.js:23864:20)
>     at renderWithHooks (react-dom-client.development.js:5530:22)
>     at updateForwardRef (react-dom-client.development.js:8646:19)
>     at beginWork (react-dom-client.development.js:10862:18)
>     at runWithFiberInDEV (react-dom-client.development.js:1520:30)
>     at performUnitOfWork (react-dom-client.development.js:15133:22)
>     at workLoopSync (react-dom-client.development.js:14957:41)
>     at renderRootSync (react-dom-client.development.js:14937:11)
>     at performWorkOnRoot (react-dom-client.development.js:14463:44)
>     at performSyncWorkOnRoot (react-dom-client.development.js:16232:7)
>     at flushSyncWorkAcrossRoots_impl (react-dom-client.development.js:16080:21)
>     at processRootScheduleInMicrotask (react-dom-client.development.js:16117:7)
>     at eval (react-dom-client.development.js:16251:13)
> 
> The above error occurred in the <ForwardRef(StaticDatePicker)> component.
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, PagesDevOverlayErrorBoundary.
> ```
> 
> It appeared when I updated @mui/x-date-pickers to `8.3.0` from `7.28.3`. Also I have `next 15.3.1 and react 19.1.0`
> 
> I will really appreciate if somebody will give a hint how can I resolve it. Thanks :)

Hello @WhoSV. Have you been able to fix this?

**Comment by Thebarda** [comment]
> > Hello everyone!
> > Does anybody was able to resolve this issue?
> > ```
> > TypeError: _mui_material_useMediaQuery__WEBPACK_IMPORTED_MODULE_0__ is not a function
> > 
> > at useReduceAnimations (useReduceAnimations.js:16:26)
> >     at usePicker (usePicker.js:85:104)
> >     at useStaticPicker (useStaticPicker.js:63:69)
> >     at StaticDatePicker (StaticDatePicker.js:55:97)
> >     at react-stack-bottom-frame (react-dom-client.development.js:23864:20)
> >     at renderWithHooks (react-dom-client.development.js:5530:22)
> >     at updateForwardRef (react-dom-client.development.js:8646:19)
> >     at beginWork (react-dom-client.development.js:10862:18)
> >     at runWithFiberInDEV (react-dom-client.development.js:1520:30)
> >     at performUnitOfWork (react-dom-client.development.js:15133:22)
> >     at workLoopSync (react-dom-client.development.js:14957:41)
> >     at renderRootSync (react-dom-client.development.js:14937:11)
> >     at performWorkOnRoot (react-dom-client.development.js:14463:44)
> >     at performSyncWorkOnRoot (react-dom-client.development.js:16232:7)
> >     at flushSyncWorkAcrossRoots_impl (react-dom-client.development.js:16080:21)
> >     at processRootScheduleInMicrotask (react-dom-client.development.js:16117:7)
> >     at eval (react-dom-client.development.js:16251:13)
> > 
> > The above error occurred in the <ForwardRef(StaticDatePicker)> component.
> > 
> > React will try to recreate this component tree from scratch using the error boundary you provided, PagesDevOverlayErrorBoundary.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It appeared when I updated @mui/x-date-pickers to `8.3.0` from `7.28.3`. Also I have `next 15.3.1 and react 19.1.0`
> > I will really appreciate if somebody will give a hint how can I resolve it. Thanks :)
> 
> Hello [@WhoSV](https://github.com/WhoSV). Have you been able to fix this?

Not the perfect workaround but I had to downgrade to the latest of @mui/x-date-pickers@7 :/

**Comment by LukasTy** [comment]
Have you checked this documentation section: https://mui.com/x/migration/migration-pickers-v7/#package-layout-changes?
Depending on your setup and the used `@mui/material` package version, you might need some extra setup steps.
