### ISSUE TITLE
[data grid] Row grouping on checkbox field does not render value

### ISSUE THREAD

**Issue by justin-wilxite** [mui/mui-x#11031]
### Steps to reproduce

Link to live example: (required) https://mui.com/x/react-data-grid/#premium-plan

Steps:
1. Group by "is filled" instead of "commodity"
2. The value in the grouping column for "is filled" is empty, it just displays " (100)"

### Current behavior

Checkbox columns appear to render an empty string in the grouping column when row grouping is enabled on them

### Expected behavior

I would expect them to render the checkbox icon like checkbox columns normally do

### Context

Row grouping on a checkbox field seems really useful but if you can't see the value you don't know whether you're looking at a "true" group or a "false" group

I did try a workaround adding a renderCell function, however this shows the custom rendered cell even on the group row, unlike other columns which don't show a value in the grouped row:

https://codesandbox.io/s/adoring-rgb-w5vk9p?file=/src/Demo.js

### Your environment

Tested on Firefox

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 6.1 Arch Linux
  Binaries:
    Node: 20.9.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.3 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.6 
    @mui/core-downloads-tracker:  5.14.13 
    @mui/icons-material: ^5.4.1 => 5.13.7 
    @mui/lab: ^5.0.0-alpha.73 => 5.0.0-alpha.135 
    @mui/material: ^5.14.13 => 5.14.13 
    @mui/private-theming:  5.14.13 
    @mui/styled-engine:  5.14.13 
    @mui/system:  5.14.13 
    @mui/types:  7.2.6 
    @mui/utils:  5.14.18 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-premium: ^6.18.1 => 6.18.1 
    @mui/x-data-grid-pro: ^6.0.4 => 6.18.1 
    @mui/x-date-pickers-pro: ^6.0.0 => 6.9.2 
    @mui/x-license-pro:  6.9.0 
    @types/react: ^18.2.0 => 18.2.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.4.2 => 4.9.5 
```
</details>

**Search keywords**: row grouping checkbox
**Order ID**: 78697

**Comment by DanailH** [comment]
It looks like a valid problem. It might also be related to the custom component used in the column.
