### ISSUE TITLE
[charts] Rendering a chart with an empty dataset throws an error

### ISSUE THREAD

**Issue by mhuggins** [mui/mui-x#11032]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/agitated-gould-tlj49f?file=/src/Demo.tsx

Steps:
1. Provide an empty `dataset`.
2. Provide a `series` value with a `dataKey` that can't be found due to no data available in the `dataset`.

### Current behavior

Throws an error:

```
TypeError
Cannot read properties of undefined (reading '1')
```

### Expected behavior

Renders empty chart, similar to when a dataset is not used & series data is empty.

### Context

I'm trying to render charts dynamically based upon user-defined filters.  When no data matches the filters that are applied, I want to render an empty chart.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  ```
  System:
    OS: macOS 14.0
  Binaries:
    Node: 20.3.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Edge: Not Found
    Safari: 17.0
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.21 
    @mui/core-downloads-tracker:  5.14.15 
    @mui/icons-material: ^5.14.15 => 5.14.15 
    @mui/material: ^5.14.15 => 5.14.15 
    @mui/private-theming:  5.14.15 
    @mui/styled-engine:  5.14.15 
    @mui/system:  5.14.15 
    @mui/types:  7.2.7 
    @mui/utils:  5.14.15 
    @mui/x-charts: ^6.18.1 => 6.18.1 
    @mui/x-data-grid: ^6.16.3 => 6.16.3 
    @types/react: ^18.2.31 => 18.2.31 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 
  Browser:
    Electron app (Chrome?) on macOS
  ```
</details>

**Search keywords**: chart data dataset empty

**Comment by alexfauquette** [comment]
Thanks for reporting this issue. Could you provide more context about what is inside the dataset, what is in the series, and how it articulates your need for user filtering?

For me, it makes sense to throw an error (even if it should be more explicit) when the key does not exist. If you want to avoid rendering a given series, maybe better to just don't define it. But might be because I don't have the correct usecase in mind

**Comment by mhuggins** [comment]
@alexfauquette Thanks for the quick response!  I've updated the sandbox with a simple filtering example [here](https://codesandbox.io/s/agitated-gould-tlj49f?file=/src/Demo.tsx).

> For me, it makes sense to throw an error (even if it should be more explicit) when the key does not exist. If you want to avoid rendering a given series, maybe better to just don't define it. But might be because I don't have the correct usecase in mind

My main argument against this is that when a `dataset` is *not* provided, and the data resides within the `series` itself, the same error is not encountered when an empty data array is given.

That all being said, I am able to work around this by checking whether there's data, and passing an empty array to `series` instead.  i.e.:

```tsx
const series = useMemo(() => filteredData.map(/* ... */), [filteredData]);
return <LineChart series={filteredData.length === 0 ? [] : series} /* snip */ />
```

**Comment by alexfauquette** [comment]
Ok, I agree that some code like that should work :+1:

```jsx
<LineChart
        xAxis={[{ dataKey: "name", scaleType: "point" }]}
        series={[{ dataKey: "earnings", label: "Earnings" }]}
        dataset={[]}
/>
```
