### ISSUE TITLE
[data grid] how to display an error message in a cell in a editable datagrid

### ISSUE THREAD

**Issue by essoufy** [mui/mui-x#11039]
### The problem in depth 🔍

Hello,
We want to be able to display an error message after the check of the entered data in a cell, but we didn't find how to do that.
We use the preProcessEditCellProps function to check the entered data like this : 
` preProcessEditCellProps(params: GridPreProcessEditCellProps) {
                const invalid = !isPositiveNumber(params.props.value)
                return { ...params.props, error: invalid }
            }`
If the data is invalid we want to display an error message, how we can achieve that ?

Thanks for your response

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: editable datagrid
**Order ID**: 73278

**Comment by DanailH** [comment]
Hi @essoufy I think you already checked this page: https://mui.com/x/react-data-grid/editing/#validation but to be sure I'm posting it again.

`The demo below contains an example of server-side data validation. In this case, the callback returns a promise that resolves to the modified props. Note that the value passed to props.error is passed directly to the edit component as the error prop. While the promise is not resolved, the edit component will receive an isProcessingProps prop with value equal to true.`

In the edit component, you can handle the error and notify the user. You can see an example of this here: https://mui.com/x/react-data-grid/recipes-editing/#conditional-validation

**Comment by essoufy** [comment]
Thank you, I already read this documentation, but I haven't found how to display an error message and not just block the backup.
Could you tell me which property should be used to display an error message?
Thanks

**Comment by MBilalShafi** [comment]
If I am able to understand your concern better I think https://mui.com/x/react-data-grid/editing/#validation is what you need, just try changing the `You?` field to one of the names above, you'll be able to see the error message in the field.
<img width="362" alt="image" src="https://github.com/mui/mui-x/assets/12609561/729184c2-0c85-4267-b122-83e121680227">
 
If that is not what you are looking for, please try to reproduce the error in this [codesandbox](https://codesandbox.io/s/c67h45?file=/src/Demo.tsx) example, and share the forked sandbox to help understand the need better.

Thanks

**Comment by essoufy** [comment]
Thanks
