### ISSUE TITLE
Is it necessary to enable inline styles in nonce when using DateTimePicker controls if the project is configured with CSP? I don't want to start any other plans?

### ISSUE THREAD

**Issue by FranklinLiu07** [mui/mui-x#11047]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Current behavior

errorMessage:
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-6axau6ipqp5'". Either the 'unsafe-inline' keyword, a hash ('sha256-nTv64G8UKVIXOpC06eRf6TiN+zisoNMOIi+f3CUJP/A='), or a nonce ('nonce-...') is required to enable inline execution.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: csp nonce DateTimePicker

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.
