### ISSUE TITLE
[data grid] Edit Mode in multiple cells

### ISSUE THREAD

**Issue by DanielxAsolvi** [mui/mui-x#11050]
### Order ID or Support key 💳

75612

### Search keywords

edit mode

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi, we want to achieve bulk edit behaviour. So the user is clicking edit and then editing cells that he want. And Then the user hit save button. 

We were able to prototype first step so user is clicking edit button all cells in name columns are switching to edit mode but after we end editing of cell We do not see where we can collect the user change. We want all cells in edit mode until user will click save but it is important when user is changing cell to collect changed data of the cell, we can see that onCellEditStop user is triggered but here we do not see new Value of the cell.

Can you advice to use how to achieve our goal? 

So to summarize:
1. User Is Clicking Edit button.
2. All cells in name columns are switching to edit mode and Save button will be displayed but disabled initially
3. When user end edit first cell and moved to second first cell will remain in edit mode but new value will be collected and save button will be enabled if newValue != oldValue.
4. After hitting Save all data will be send to api in prototype displayed in console.

Main question is how to collect data when we are in the situation when we are preventing from default behaviour in event onCellEditStop?

https://codesandbox.io/s/heuristic-moon-l2xjc4?file=/src/Demo.tsx

Another question is When I 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi @DanielxAsolvi have you checked our advanced cases for editing? We have a recipe regarding bulk editing - https://mui.com/x/react-data-grid/recipes-editing/#bulk-editing
Maybe this is something that can give you the answers you need? Let me know if this works for you.

**Comment by DanielxAsolvi** [comment]
Thanks
