### ISSUE TITLE
[data grid] Pinned Columns in Detail Panel Not Behaving as Expected (they are scrolling instead of being "pinned/sticky")

### ISSUE THREAD

**Issue by alikMLH** [mui/mui-x#11053]
### The problem in depth 🔍

I'm working with DataGrid Premium in a React application and facing an issue with the pinned columns in the detail panel.

**Issue Description:** In my implementation, the main DataGrid has expandable rows, each containing a sub-DataGrid in the detail panel. The main DataGrid has certain columns (specifically, 'status' and 'actions') pinned to the right. However, the corresponding columns in the sub-DataGrid (detail panel) are not staying pinned when scrolling horizontally—they scroll along with other columns.

**Parent component:**

const getDetailPanelContent = useCallback(
  ({ row }: GridRowParams) =>
    row.practiceAdmin?.length ? (
      <PracticeUserDetails
        practiceAdmin={
          loadedRows.find((item) => item.id === row.id)?.practiceAdmin
        }
        tableFiltersState={tableFiltersState}
      />
    ) : null,
  [density, queryClient, tableFiltersState, loadedRows]
);

const getDetailPanelHeight = useCallback(() => 'auto', []);

<DataGridPremium
  localeText={{
    noRowsLabel: 'No data',
  }}
  apiRef={apiRef}
  loading={practiceUsersListLoading || isFetching}
  rows={loadedRows || []}
  columns={renderPracticeUsersTableCols(
    handleOnRowStatusChange,
    handleRowAction,
    handleRowActionResetInvitation,
    handleRoleChange,
    deletePracticeAndUser,
    user!,
    tableFiltersState.columns?.orderedFields
  )}
  columnTypes={{
    [GRID_DETAIL_PANEL_TOGGLE_COL_DEF.type as string]:
      GRID_DETAIL_PANEL_TOGGLE_COL_DEF,
  }}
  initialState={tableFiltersState}
  groupingColDef={{
    hideDescendantCount: true,
  }}
  components={{ Toolbar: PracticeUsersTableToolbar }}
  componentsProps={{
    toolbar: {
      isFilterEnable: tableFilters && tableFilters?.items.length > 0,
      count: practiceUsersListData?.meta.itemCount || 0,
      onQuickSearch: debouncedQuickSearch,
      initialSearchValue: query,
      onAdd: handleOpenModal,
    },
  }}
  classes={{
    columnHeader: 'text-sm text-grayBlue !pl-4',
    cell: 'text-gray-800',
    main: 'bg-white rounded-[8px] border border-gray-400',
    root: '!border-0 !text-sm',
    row: 'hover:!bg-gray-50',
    pinnedColumns: '!overflow-visible',
    toolbarContainer: '!p-0',
  }}
  sx={{
    '& .MuiDataGrid-columnHeader:first-child .MuiDataGrid-columnSeparator':
      {
        display: 'none',
      },
    '& .MuiDataGrid-columnHeader': {
      paddingLeft: '16px',
    },
    '& .MuiDataGrid-columnHeader.MuiDataGrid-columnHeader--alignCenter:first-child':
      {
        paddingLeft: 0,
      },
  }}
  pinnedColumns={{
    left: [GRID_DETAIL_PANEL_TOGGLE_FIELD],
    right: ['status', 'actions'],
  }}
  rowThreshold={0}
  getDetailPanelContent={getDetailPanelContent}
  getDetailPanelHeight={getDetailPanelHeight}
  filterMode="server"
  onFilterModelChange={handleOnFilterModelChange}
  onRowsScrollEnd={handleOnRowsScrollEnd}
/>

 

**“Details” component:**

<DataGridPro
  columns={renderPracticeUserDetailsTableCols(
    tableFiltersState.columns?.dimensions,
    onRowStatusChange,
    deletePracticeUser,
    onPermissionChange,
    tableFiltersState.columns?.orderedFields
  )}
  rows={practiceAdmin || []}
  classes={{
    cell: 'text-gray-800',
    main: 'bg-white border border-gray-400',
    root: '!border-t-0 !border-l-0 !border-r-0 !text-sm',
    row: 'hover:!bg-gray-50',
    pinnedColumns: '!overflow-visible !z-100',
  }}
  sx={{
    '& .MuiDataGrid-columnHeader:first-child .MuiDataGrid-columnSeparator':
      {
        display: 'none',
      },
    '& .MuiDataGrid-columnHeader': {
      paddingLeft: '16px',
    },
    '& .MuiDataGrid-columnHeader.MuiDataGrid-columnHeader--alignCenter:first-child':
      {
        paddingLeft: 0,
      },
  }}
  pinnedColumns={{
    right: ['status', 'actions'],
  }}
  onCellEditCommit={handleOnCellEditCommit}
  hideFooter
  autoHeight
  headerHeight={0}
/>

 

**Attempts to Resolve:**

- Ensured that pinnedColumns configurations are consistent in both the main and detail DataGrids.
- Checked column definitions and custom styling.
- Despite these attempts, the issue persists. The pinned columns in the detail panel DataGrid don't stay fixed as they do in the main DataGrid.

**Questions:**

- Is there a known limitation or issue with pinned columns in detail panels of the MUI DataGrid?
- Are there any additional configurations or props that I might be missing to achieve the desired behavior?

Any guidance or suggestions to resolve this issue would be greatly appreciated.

 

Technical info (I can't switch to the latest version now, have to stay with the current one):

"@mui/x-data-grid-premium": "^5.17.23",
"@mui/x-license-pro": "^5.17.12",

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: detail panel pinned column scroll not sticky
**Order ID**: 78203

**Comment by DanailH** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by alikMLH** [comment]
https://codesandbox.io/s/data-grid-community-pinned-columns-in-detail-panel-fjd5fz

**Comment by alikMLH** [comment]
@DanailH I've provided the requested test case, can you, please, move this ticket forward?

**Comment by DanailH** [comment]
Thanks for the reproduction @alikMLH. What you are trying to do is not possible. What you provide in the details panel is an independent component from the original data grid instance. We can't control what you pass in the details panel.
If you are displaying rows it would be much better to use the row grouping feature from the data grid instead of the details panel. My advice is to convert your code to use row grouping and if the column pinning still misbehaves then it will be a valid bug and we will look into it.
You can check more about the feature here: https://mui.com/x/react-data-grid/row-grouping/

**Comment by DanailH** [comment]
if the only requirement for you is to have different cell components/logic for the nested rows you can always use `renderCell` in the column. There you can check if a cell is a specific cell that you want to alter, otherwise, you can return the default `GridCell` component. Even tho it doesn't exactly match your requirement we have a similar demo that implements a custom renderCell for the grouped rows: https://mui.com/x/react-data-grid/row-grouping/#grouping-rows-with-custom-cell-renderer

Again if the only difference is the cell content I would go with this approach.
