### ISSUE TITLE
[data grid] Can I Customize Checkbox Selection  in DataGrid Pro? 

### ISSUE THREAD

**Issue by bogdancbs** [mui/mui-x#11052]
### The problem in depth 🔍

I'm currently working on implementing the DataGrid Pro component in my project, and I'm looking for some guidance on a specific feature. I would like to know if there's a way to transform the checkbox in the header of the table into a dropdown with two options: "Select All on Page" and "Select All Pages" (similar to Google's approach). This would make it more user-friendly for handling large datasets.

I've been exploring the documentation and examples, but I haven't found a built-in feature for this. If anyone has experience with DataGrid Pro and knows how to achieve this functionality or has any suggestions on how to approach it, I would greatly appreciate your insights.

Thank you in advance for your help!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
npx: installed 2 in 5.674s

  System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 119.0.6045.106
    Edge: Chromium (119.0.2151.58)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.16
    @mui/core-downloads-tracker:  5.14.10
    @mui/icons-material: ^5.11.11 => 5.14.9
    @mui/lab: ^5.0.0-alpha.133 => 5.0.0-alpha.145
    @mui/material: ^5.14.0 => 5.14.10
    @mui/private-theming:  5.14.10
    @mui/styled-engine:  5.14.10
    @mui/styled-engine-sc: ^5.11.11 => 5.14.10
    @mui/styles: ^5.14.4 => 5.14.10
    @mui/system:  5.14.10
    @mui/types:  7.2.4
    @mui/utils:  5.14.10
    @mui/x-charts: ^6.0.0-alpha.6 => 6.0.0-alpha.12
    @mui/x-data-grid: ^6.0.1 => 6.15.0
    @mui/x-data-grid-pro: ^6.15.0 => 6.15.0
    @mui/x-license-pro:  6.10.2
    @mui/x-tree-view:  6.0.0-alpha.1
    @types/react:  18.2.22
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^5.3.9 => 5.3.11
```
</details>

**Search keywords**: checkboxSelection, checkboxSelection customization, checkbox selection
**Order ID**: 68255

**Comment by DanailH** [comment]
Hey @bogdancbs  thank you for raising this. Unfortunately, we don't support this customization out of the box, but you should be able to achieve this using a custom header renderer: https://mui.com/x/react-data-grid/column-header/#custom-header-renderer and providing your own component for the checkbox column. One problem might be that the checkbox column is considered "internal" but the field is `__checkbox__`, which you can access using `GRID_CHECKBOX_SELECTION_COL_DEF.field`
