### ISSUE TITLE
[Data-Grid] Allow GridFilterPanel remove all button supports custom text and start icon

### ISSUE THREAD

**Issue by FreakDroid** [mui/mui-x#11067]
### Summary 💡

In my current project, we need to change the word "Remove all" and the icon from the filter panel to another one. The current implementation of GridFilterPanel doesn't support this I can just show or hide this button.

```
            {!disableRemoveAllButton ? (
              <rootProps.slots.baseButton
                onClick={handleRemoveAll}
                startIcon={<rootProps.slots.filterPanelRemoveAllIcon />} // this also needs to be changed.
                {...rootProps.slotProps?.baseButton}
              >
                {apiRef.current.getLocaleText('filterPanelRemoveAll')} // this line needs to support any prop sent.
              </rootProps.slots.baseButton>
            ) : null}
          </GridPanelFooter>
```

Creating a new prop in the slot will probably help with that:

```
slotProps={{

            filterPanel: {
              filterFormProps: {
                removeAllButtonProps: {
                  text: 'My custom text'
                },
              }
            }
}}
```

### Examples 🌈

Current implementation:

![Screenshot 2023-11-17 at 12 30 46 PM](https://github.com/mui/mui-x/assets/5360335/16db8632-28d4-494d-8ed4-41741eba379e)

Expected:

![Screenshot 2023-11-17 at 12 31 49 PM](https://github.com/mui/mui-x/assets/5360335/5c45595f-0894-41ee-9368-cac0fb29439b)

### Motivation 🔦

Allows users to set any value as a text.

**Search keywords**: GridFilterPanel remove all
**Order ID**: 77137

**Comment by alexfauquette** [comment]
Text can be translated either in the theme or in the `localeText` prop

```jsx
 <DataGridPro
        {...data}
        localeText={{
          filterPanelRemoveAll: "My custom remove all"
        }}
/>
```


What is explained in the [localization page](https://mui.com/x/react-data-grid/localization/) can also be applied to adapt the english translation to your needs

**Comment by FreakDroid** [comment]
> Text can be translated either in the theme or in the `localeText` prop
> 
> ```js
>  <DataGridPro
>         {...data}
>         localeText={{
>           filterPanelRemoveAll: "My custom remove all"
>         }}
> />
> ```
> 
> What is explained in the [localization page](https://mui.com/x/react-data-grid/localization/) can also be applied to adapt the english translation to your needs
> 
> https://codesandbox.io/s/eager-cherry-l63lxr?file=/src/Demo.tsx
> 
> Does that solve your issue?

That solved my issue, but I have another question because I was updating the thread. 

Do you know how I can update the icon to this button? I saw filterPanelRemoveAllIcon will do it but I'm not sure how that works.

Thanks.

**Comment by FreakDroid** [comment]
I solved everything. 

Thanks for the help
