### ISSUE TITLE
Mui Drawer control hides the current screen in background completely in black rather than disabling it when it gets open from the button within mui grid

### ISSUE THREAD

**Issue by Dipali-arup** [mui/mui-x#11060]
### Steps to reproduce

Link to live example: (required)

Steps:
1. create react component having a button and drawer element
2. add component (created above) in the mui data grid
3. click on  the button and notice the behaviour that drawer opens from right but on the left side current screen becomes black

### Current behavior

click on  the button and notice the behaviour that drawer opens from right but on the left side current screen becomes black

### Expected behavior

when drawer opens, it opens above current screen making the current screen disabled

### Context

I'm trying to have a button added in mui data grid in each row and when user clicks on button in the datagrid row, it should open drawer from right hand side listing details

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.58)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.69 
    @mui/icons-material: ^5.0.0 => 5.3.1 
    @mui/material: ^5.4.1 => 5.4.3 
    @mui/private-theming:  5.4.2 
    @mui/styled-engine:  5.4.2 
    @mui/system:  5.4.3 
    @mui/types:  7.1.2 
    @mui/utils:  5.14.5 
    @mui/x-data-grid: ^5.10.0 => 5.17.26 
    @types/react: ^17.0.21 => 17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2
    typescript: 4.1.2 => 4.9.5
</details>

**Search keywords**: datagrid , drawer

**Comment by michelengelen** [comment]
Hi @Dipali-arup and thanks for raising an issue.
To fully assess the problem you are facing could you please provide a working example in a CodeSandbox for us? You can use [this template](https://codesandbox.io/s/q9wk9d?file=/src/Demo.tsx) as a starting point.
Thanks again! We really appreciate it! 🙇🏼

**Comment by Dipali-arup** [comment]
I have now added new action column in the grid. Clicking on "Platforms" button opes up drawer from right hand side but it covers remaining screen in black, Please see the behaviour in codesandbox: https://codesandbox.io/s/sad-noyce-7ttx38?file=/src/Demo.tsx

**Comment by cherniavskii** [comment]
Hey @Dipali-arup 
It seems like you render an open `Drawer` component for each action cell in the Data Grid.
You should either render drawers conditionally depending on the row ID that opened it or lift it up the component tree to make sure there's only one `Drawer` component.
