### ISSUE TITLE
Unable to update nextjs to 14.0.3 as @mui/material/styles/alpha module cannot be found

### ISSUE THREAD

**Issue by muhaimincs** [mui/mui-x#11072]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Link to live example:

Steps:

1. Update package.json 14.0.3
2. 
3.

### Current behavior 😯

Error to build

```bash
...
Failed to compile.

./node_modules/@mui/x-tree-view/TreeItem/TreeItem.js
Module not found: Can't resolve '@mui/material/styles/alpha'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mui/x-tree-view/TreeItem/index.js
./src/app/(dashboard)/t/tree.tsx


> Build failed because of webpack errors
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**:

**Comment by flaviendelangle** [comment]
Duplicates #11030

If the solution proposed in this issue does not fix your problem please comment on the original issue and we will have a look

**Comment by kameshdhana** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Steps to reproduce 🕹
> Link to live example:
> 
> Steps:
> 
> 1. Update package.json 14.0.3
> 
> ### Current behavior 😯
> Error to build
> 
> ```shell
> ...
> Failed to compile.
> 
> ./node_modules/@mui/x-tree-view/TreeItem/TreeItem.js
> Module not found: Can't resolve '@mui/material/styles/alpha'
> 
> https://nextjs.org/docs/messages/module-not-found
> 
> Import trace for requested module:
> ./node_modules/@mui/x-tree-view/TreeItem/index.js
> ./src/app/(dashboard)/t/tree.tsx
> 
> 
> > Build failed because of webpack errors
> ```
> 
> ### Expected behavior 🤔
> _No response_
> 
> ### Context 🔦
> _No response_
> 
> ### Your environment 🌎
> `npx @mui/envinfo`
> **Search keywords**:

Thanks for bringing this issue. Facing the same issue on my local with next version of 14.0.2-canary.25
