### ISSUE TITLE
[DataGridPro] When adding a Select tag  to my columnMenu in the slots I got the error: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by elprogramadorgt** [mui/mui-x#11097]
### Steps to reproduce

Link to live example: (required)

Steps:
1. clone https://github.com/elprogramadorgt/react-test
2. run pnpm dev
3. when you open the filter and change the option from Starts Width to any other you will get the error on the console

GridColumnHeaderItem.js:71 Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
    at GridColumnHeaderItem.js:71:30
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12

### Current behavior

I got this error: 
GridColumnHeaderItem.js:71 Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
    at GridColumnHeaderItem.js:71:30
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12

on the console when I click the three dots icon to open the menu on the table and I try to apply a different filter on the Select I got the error

### Expected behavior

No get the error.

### Context

I want to have my own filter UI.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGridPro, filter,  select

**Comment by michelengelen** [comment]
Hi @elprogramadorgt ... thanks for raising this issue.
Could you provide a codesandbox for us to see the issue in a live example.
You can use [this sandbox template](https://codesandbox.io/s/r2m58g?file=/src/Demo.tsx) as a starting point.
Thanks a lot!

**Comment by elprogramadorgt** [comment]
Hello @michelengelen, I added the code to that sandbox.

![Screenshot from 2023-11-20 08-46-25](https://github.com/mui/mui-x/assets/96149783/291931fa-e1f2-4bc7-816b-0567a1e783bb)

**Comment by cherniavskii** [comment]
@elprogramadorgt I cannot reproduce the issue.
Can you reproduce it in https://codesandbox.io/p/sandbox/quirky-firefly-67tl28?

**Comment by elprogramadorgt** [comment]
Hi @cherniavskii done, I just save the file, is there anything else I need to do ? like a commit or something ?


Add the following code inside the functional componente CustomColumnMenuComponent
`

 const [filterOption, setFilterOption] = React.useState("");

  const handleChangeOption = (event) => {
    setFilterOption(event.target.value);
  };

`

then this code
`  
<Select
            name="filterOption"
            value={filterOption}
            onChange={handleChangeOption}
            size="small"
          >
            <MenuItem value="startsWidth">Starts With</MenuItem>
            <MenuItem value="isEqual">Is Equal To</MenuItem>
            <MenuItem value="contains">Contains</MenuItem>
          </Select>
`
inside Box tag in line 66

**Comment by cherniavskii** [comment]
> I just save the file, is there anything else I need to do ? like a commit or something ?

Just share a link to the sandbox so I can open the same code as you do 🙂

**Comment by elprogramadorgt** [comment]
Hi @cherniavskii  I got this two links.

https://codesandbox.io/p/sandbox/quirky-firefly-67tl28?file=%2Fsrc%2FDemo.tsx%3A72%2C37

https://codesandbox.io/p/sandbox/quirky-firefly-67tl28?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp8h8l7700072067jkti6qmc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp8h8l7700032067yyt14n78%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp8h8l7700042067w5abb2w3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp8h8l8z000j20670muqkgjz%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp8h8l7700062067hyrrkrok%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp8h8l8z000j20670muqkgjz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_ONBOARDING%2522%252C%2522id%2522%253A%2522sandbox-onboarding%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522id%2522%253A%2522clp8h8l8z000j20670muqkgjz%2522%252C%2522activeTabId%2522%253A%2522sandbox-onboarding%2522%257D%252C%2522clp8h8l7700032067yyt14n78%2522%253A%257B%2522id%2522%253A%2522clp8h8l7700032067yyt14n78%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clp8h8l7700062067hyrrkrok%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp8h8l7700052067svixsmmr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clp8h8l7700062067hyrrkrok%2522%252C%2522activeTabId%2522%253A%2522clp8h8l7700052067svixsmmr%2522%257D%252C%2522clp8h8l7700042067w5abb2w3%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clp8h8l7700042067w5abb2w3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by cherniavskii** [comment]
@elprogramadorgt I can see the problem now, I had to close the column menu to reproduce the issue 👍🏻
