### ISSUE TITLE
[charts] Can't import Prop types from @mui/x-charts for BarChart

### ISSUE THREAD

**Issue by DaryaHaprova** [mui/mui-x#11099]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/mutable-hill-94wl39?file=/src/Demo.tsx

Steps:
1.  try to import types from "@mui/x-charts"
2.  get typescript error: Module '"@mui/x-charts"' has no exported member 'BarChartProps'

### Current behavior

Can't import types from "@mui/x-charts"

### Expected behavior

Can import types from "@mui/x-charts"

### Context

We have a wrapper component on top of BarChart and need import and reexport types.
We tried to reuse "@mui/x-charts" types, like BarChartProps, but have typescript errors.

I think it is because not everything is exported from BarChart in this file: https://github.com/mui/mui-x/blob/master/packages/x-charts/src/BarChart/index.tsx

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.58)
  npmPackages:
    @emotion/react:  11.11.1
    @emotion/styled:  11.11.0
    @mui/base:  5.0.0-beta.24
    @mui/core-downloads-tracker:  5.14.18
    @mui/lab:  5.0.0-alpha.135
    @mui/material:  5.13.6
    @mui/private-theming:  5.14.18
    @mui/styled-engine:  5.14.18
    @mui/system:  5.14.18
    @mui/types:  7.2.9
    @mui/utils:  5.14.18
    @mui/x-charts:  6.18.1
    @mui/x-data-grid:  6.17.0
    @mui/x-data-grid-pro:  6.17.0
    @mui/x-date-pickers:  6.16.0
    @mui/x-date-pickers-pro:  6.16.0
    @mui/x-license-pro:  6.10.2
    @types/react:  18.0.28
    react:  18.2.0
    react-dom:  18.2.0
    typescript:  5.0.4
```
</details>

**Search keywords**: prop types import export reexport charts

**Comment by michelengelen** [comment]
@DaryaHaprova thanks for raising this issue.
You are absolutely right: We currently do not export the `BarChartProps` from the `BarChart` index file.

For now please use this workaround: `import { BarChartProps } from '@mui/x-charts/BarChart/BarChart'`

```
import * as React from 'react';
import { BarChart } from '@mui/x-charts/BarChart';
import { BarChartProps } from '@mui/x-charts/BarChart/BarChart';

export default function BasicBars() {
  const props: BarChartProps = {
    xAxis: [{ scaleType: 'band', data: ['group A', 'group B', 'group C'] }],
    series: [{ data: [4, 3, 5] }, { data: [1, 6, 3] }, { data: [2, 5, 6] }],
    width: 500,
    height: 300,
  };
  return <BarChart {...props} />;
}
```

@alexfauquette should I assign this to you? Or I can take care of this as well.
