### ISSUE TITLE
Is it possible not to close previously opened groups when changing the data in useState?

### ISSUE THREAD

**Issue by kharlaienko** [mui/mui-x#11105]
### The problem in depth 🔍

https://codesandbox.io/s/mui-treedata-update-9rpsvj?file=/src/Demo.js

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

Order Id: 73714

**Search keywords**: datagrid,

**Comment by cherniavskii** [comment]
Hey @kharlaienko 

There are 2 options here.

1. If you do not need row state for anything else except the Data Grid - you can skip updating it - the Data Grid will update the row anyway.
https://codesandbox.io/p/sandbox/mui-treedata-update-forked-qrtf5t

2. If you do need to keep track of the row state and it could potentially change from the outside - you will have to use the `apiRef.current.updateRows` method (see https://github.com/mui/mui-x/issues/7771#issuecomment-1410218395 for more context).
https://codesandbox.io/p/sandbox/mui-treedata-update-forked-qgdx8c
