### ISSUE TITLE
[question] MUI DataGridPro Pagination with Infinite Scroll

### ISSUE THREAD

**Issue by amrutamangaonkar** [mui/mui-x#11108]
### The problem in depth 🔍

I am a MUI DataGrid Pro licensed user. I want to achieve pagination with infinite scrolling for my DataGridPro, I need to fetch data in pages while using infinite scrolling on the DataGrid. Every time I scroll down to fetch new data (scroll down to the end of the page), I need to set that as a new page. When I scroll up (towards the top of the grid) I need to detect the previously set page change to fetch the latest data on that particular page.

DevExtreme has something which could be a good example -
https://js.devexpress.com/React/Demos/WidgetsGallery/Demo/DataGrid/RemoteVirtualScrolling/MaterialBlueLight/

Are there any events or apis that I can use to achieve this behavior.

**Search keywords**: Pagination with Infinite Scroll
**Order ID**: 8813014139

**Comment by MBilalShafi** [comment]
Hey @amrutamangaonkar, thanks for using the MUI Data Grid.

Have you already checked the [infinite loading](https://mui.com/x/react-data-grid/row-updates/#infinite-loading) (row size unknown) and [lazy loading](https://mui.com/x/react-data-grid/row-updates/#lazy-loading) (row size known), do you have a specific use-case you can not achieve with these features?

We are also under development on a new centralized data source for server side data, feel free to check out the pre-release documentation [here](https://mui.com/x/react-data-grid/server-side-data/).

**Comment by amrutamangaonkar** [comment]
> lazy loading

Hi @MBilalShafi, Thanks for replying so quick. I tested the infinite loading and lazy loading features of the grid. In both the cases, we can fetch new data as we scroll down. For example, for infinite loading I can fetch the new data when scrolling down using onRowsScrollEnd and in case of lazy loading I can fetch the new data when scrolling down using onFetchRows. In both the cases, the new data can be fetched on the bottom of the page, which is great. In my case along with fetching new data as we scroll down I also want to fetch the latest data from the server when the user scrolls up.

 Basically, I am dealing with very dynamic server side data which will change from time to time and hence, when the user scrolls down or up, I want to detect a page change which can tell me that user has scrolled enough and has now reached to an another page (could be next or previous) so that I can make a call to server to fetch new data for that particular page. 

I wanted to know if there is a way to achieve any one of these:
1. With lazy load the onFetchRows could provide the firstRowToRender and lastRowToRender even on a scroll up.
2. With infinite loading if there is something like onRowsScrollTop to detect that user has scrolled above the current viewport.
3. Achieve virtual pagination which can help me assign pages when scrolling up or down in the grid. DevExtreme has something like this where we can provided virtual pagination to the grid while scrolling - https://js.devexpress.com/React/Demos/WidgetsGallery/Demo/DataGrid/RemoteVirtualScrolling/MaterialBlueLight/

**Comment by MBilalShafi** [comment]
1. I don't think it is supported by default, but you should be able to listen to the `renderedRowsIntervalChange` event and handle it as needed, I tried to listen to the event in this [example](https://codesandbox.io/s/laughing-wildflower-3flfmj) and it gets fired both when scrolling up and down. (You can see the original [handler](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid-pro/src/hooks/features/lazyLoader/useGridLazyLoader.ts#L129) for this event and add your use case as needed)
2. Same as lazy-loading, you should be able to listen to the `scrollPositionChange` event which works on both scroll-up and scroll down and add your custom logic to handle the cases for scroll up use cases. Here's a codesandbox example that listens to that event. Here's the [original code](https://github.com/mui/mui-x/blob/f05d727edfd0e4641127908a9175df6c44876397/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts#L35-L72) you can refer to while writing the custom one.

Let me know if it makes sense.

**Comment by amrutamangaonkar** [comment]
> 1. I don't think it is supported by default, but you should be able to listen to the `renderedRowsIntervalChange` event and handle it as needed, I tried to listen to the event in this [example](https://codesandbox.io/s/laughing-wildflower-3flfmj) and it gets fired both when scrolling up and down. (You can see the original [handler](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid-pro/src/hooks/features/lazyLoader/useGridLazyLoader.ts#L129) for this event and add your use case as needed)
> 2. Same as lazy-loading, you should be able to listen to the `scrollPositionChange` event which works on both scroll-up and scroll down and add your custom logic to handle the cases for scroll up use cases. Here's a codesandbox [example](https://codesandbox.io/p/sandbox/funny-firefly-wvpzmx?file=%2Fsrc%2FDemo.tsx%3A39%2C37) that listens to that event. Here's the [original code](https://github.com/mui/mui-x/blob/f05d727edfd0e4641127908a9175df6c44876397/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts#L35-L72) you can refer to while writing the custom one.
> 
> Let me know if it makes sense.

Thank you for responding with the solutions, I tried them they do trigger the scroll positions however it adds some level of complexity to my code as I have to maintain all the scrolling states with me and hence, something like virtual pagination would have made my work easier. Thank you again for your help.

**Comment by DanailH** [comment]
@amrutamangaonkar Unfortunately this current case is not supported. Lazy loading can be used to fetch already loaded data (if it has changed).
@MBilalShafi will this case be handled with the data source?

**Comment by MBilalShafi** [comment]
@amrutamangaonkar Would you mind explaining a bit how the attached [example](https://js.devexpress.com/React/Demos/WidgetsGallery/Demo/DataGrid/RemoteVirtualScrolling/MaterialBlueLight/) solves the scenario in question? I could not observe any data re-fetches on scroll up.

I'd be interested to know more about what you mean by virtual pagination here and how it solves your problem.

> @MBilalShafi will this case be handled with the data source?

Thb, I did not think in this direction previously as it looks like a corner case. For normal paginated data, we could simply invalidate the page in the cache that we want to re-fetch but for lazy loading, maybe we could achieve this behavior by:
1. Introducing an opt-in flag, which if `true`, will make the grid always get the data from the cache on the page change which includes scroll up too (acting on `renderedRowsIntervalChange` event for example)
2. Combine point no. 1 with the cache invalidation to achieve the mentioned behavior.

Wdyt?

**Comment by amrutamangaonkar** [comment]
> @amrutamangaonkar Would you mind explaining a bit how the attached [example](https://js.devexpress.com/React/Demos/WidgetsGallery/Demo/DataGrid/RemoteVirtualScrolling/MaterialBlueLight/) solves the scenario in question? I could not observe any data re-fetches on scroll up.
> 
> I'd be interested to know more about what you mean by virtual pagination here and how it solves your problem.
> 
> > @MBilalShafi will this case be handled with the data source?
> 
> Tbh, I did not think in this direction previously as it looks like a corner case. For normal paginated data, we could simply invalidate the page in the cache that we want to re-fetch but for lazy loading, maybe we could achieve this behavior by:
> 
> 1. Introducing an opt-in flag, which if `true`, will make the grid always get the data from the cache on the page change which includes scroll up too (acting on `renderedRowsIntervalChange` event for example)
> 2. Combine point no. 1 with the cache invalidation to achieve the mentioned behavior.
> 
> Wdyt?

@MBilalShafi  Basically virtual pagination helps us track page changes when user scrolls forward or backward in the grid. With the other grid they have provided way to set page size and the grid detects the page change while scrolling backwards and forward in the grid and fetches data from the datasource. Your suggestion is great, it will help us detect the page change and render data on scroll but I am looking to re-fetch data from the server, is that also something you are considering adding?  I also saw that the customDataSource is in development if something like auto row rendering could be hooked up with datasource, it will be a big win for us in future!

**Comment by MBilalShafi** [comment]
> it will help us detect the page change and render data on scroll but I am looking to re-fetch data from the server, is that also something you are considering?

Exactly, cache invalidation will result in a refetch. The plan is to add this support along with the [data source](https://github.com/mui/mui-x/issues/8179) in [server-side lazy loading](https://mui.com/x/react-data-grid/server-side-data/lazy-loading/) feature.

Please feel free to upvote and subscribe to the [issue](https://github.com/mui/mui-x/issues/10857) to keep updated about the specific feature you are interested in.

Thank you!
