### ISSUE TITLE
[data grid] Minor issues with row reordering when `disableColumnReorder` is true

### ISSUE THREAD

**Issue by cbn-falias** [mui/mui-x#11126]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-vtkki8?file=Demo.tsx
Reproducable with any datagrid where `disableColumnReorder={true}`

**Issue 1**
1. Start drag
2. Move mouse exactly between two rows in the first column (drag column)
3. 🐛 Drop is not allowed
![image](https://github.com/mui/mui-x/assets/66297925/d93f229e-0efe-413e-b3a4-c5582cbef351)

**Issue 2**
1. Start drag
2. Move mouse over drag-icon and wiggle around
3. 🐛 The cursor icon constantly changes (flickers)

### Current behavior

During a drag action the cursor flickers or falsely prevents dropping the row, when `disableColumnReorder` is active.

Another issue which might be also caused by that:
Applying a `padding` on the cells makes the whole "padding area" of the reorder cell invalid for drop.
```ts
<DataGridPro
  sx={{
    "& .MuiDataGrid-cell": {
      padding: '12px',
    },
  }}
  rowReordering
  disableColumnReorder
/>
```

### Expected behavior

Always a "valid to drop" cursor like it is when `disableColumnReorder` is false/unset.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 119.0.6045.160
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.72)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.11.1 
    @emotion/styled: ^11.10.4 => 11.11.0 
    @mui/base:  5.0.0-beta.19 
    @mui/core-downloads-tracker:  5.14.13 
    @mui/material: 5.14.13 => 5.14.13 
    @mui/private-theming:  5.14.13 
    @mui/styled-engine:  5.14.13 
    @mui/system:  5.14.13 
    @mui/types:  7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-pro: 6.18.1 => 6.18.1 
    @mui/x-date-pickers:  6.18.1 
    @mui/x-date-pickers-pro: 6.18.1 => 6.18.1
    @mui/x-license-pro:  6.10.2
    @types/react: ^18.0.26 => 18.2.21
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript: ^4.1.2 => 4.9.5
```
</details>

**Search keywords**: datagrid disableColumnReorder reorder

**Comment by cherniavskii** [comment]
Hi @cbn-falias 
I cannot reproduce the issue on MacOS:

https://github.com/mui/mui-x/assets/13808724/41c9c8cb-fcbf-4d55-913f-6838328c5959

Am I missing something?
It could also happen that this is a Windows-specific issue.

**Comment by cbn-falias** [comment]
Hi @cherniavskii,
thanks for testing it!
There are only 1-2px where you can't drop it but I have no Mac to test it.
Although in your recording you can already see that the "+" icon is vanishing several times.

To emphasize the issue I added some styling to the [live example](https://stackblitz.com/edit/react-vtkki8?file=Demo.tsx).
With `disableColumnReorder={false}` there is no issue with the drop area.


https://github.com/mui/mui-x/assets/66297925/8c0bac9e-6222-4029-aec1-a4d2467a3940

**Comment by michelengelen** [comment]
The issue is happening on macOS ... its just very subtle. As mentioned correctly it becomes more apparent when you add a padding to cells (like in the example above).

What I couldn't reproduce as well is the flickering when dragging over the svg.

**Comment by cbn-falias** [comment]
Out of interest I did also some investigation.
This could also be the culprit as it's always `disableDragEvents = false` as soon as column reordering is disabled.
https://github.com/mui/mui-x/blob/891cea1809e44f71a270dc3f512528b5db7717d7/packages/grid/x-data-grid/src/components/GridRow.tsx#L280-L285

**Comment by michelengelen** [comment]
Ok, just played around and it certainly seems like the culprit is the `disableColumnReorder` property.

@cherniavskii can you take a look into this?
