### ISSUE TITLE
[charts] Allow to adjust pie chart label positon (radius)

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#11127]
### Summary 💡

I would like the `PieSeriesType` object to accept `labelAnchorRadius` prop (or similar), that will adjust how far away from the center are the labels placed.

### Examples 🌈

Basically, see "Radial scale" in https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html#anchoring

### Motivation 🔦

Labels would fit better, if they are further away.

This will also potentially allow to place the labels outside of the pie

**Search keywords**: pie chart label position radius radial scale

**Comment by michelengelen** [comment]
Hi @MonstraG 
thanks for taking the time to post this feature request 🚀
I will forward this to our charts team. They will then assess the request and update this ticket. 
Thanks! We appreciate it! 🙇🏼

**Comment by MonstraG** [comment]
It feels like it's effectively `100%` vs `100px` for width/height, and I usually would expect for both to be supported, so how about
```
innerRadius: `${number}px` | number
```
(and a slightly more complex parsing)?

**Comment by alexfauquette** [comment]
In that case, maybe the opposit to stay coherent with the other metrics where the number is the px ones.

```js
innerRadius: number | `${number}%`
```

**Comment by MonstraG** [comment]
Yea, I did not look at which way is more common, that was just an example
