### ISSUE TITLE
unstable_headerFilters with DataGridPremium

### ISSUE THREAD

**Issue by sudologist** [mui/mui-x#11137]
### The problem in depth 🔍

unstable_headerFilters does not work with the premium version, it only works with the Pro version

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: unstable_headerFilters
**Order ID**: 61954

**Comment by sudologist** [comment]
Disregard

**Comment by cherniavskii** [comment]
Seems to work fine with `DataGridPremium`: https://codesandbox.io/p/sandbox/jolly-mirzakhani-pkf74n
