### ISSUE TITLE
[DataGrid] Horizontal Scrolling: Dual Scrollbars for Enhanced Table Navigation

### ISSUE THREAD

**Issue by JustinFransenBillyGrace** [mui/mui-x#11143]
### Duplicates

- [x] I have searched the existing issues

### Summary 💡

**Overview:**

In the current implementation of the MUI Table component, when dealing with a large number of columns, users are required to scroll to the bottom of the table to access the horizontal scrollbar. This can be cumbersome, especially in cases where the table contains a substantial number of rows, such as 100 or more.

**Proposed Feature:**

Introduce an additional horizontal scrollbar at the top of the table. This feature will enable users to scroll horizontally through columns without the need to navigate to the bottom of the table, significantly improving the ease of data exploration and interaction.

**Implementation Considerations:**

The additional scrollbar should be optional and configurable, allowing developers to enable or disable it based on their application's needs.
Care should be taken to ensure that the addition of this feature aligns with the existing design principles of MUI, maintaining a clean and unobtrusive user interface.
We believe this feature will significantly improve the usability of the MUI Table for many users, particularly those dealing with large sets of data, and look forward to any feedback or suggestions on this proposal.

### Examples 🌈

https://www.npmjs.com/package/react-double-scrollbar

### Motivation 🔦

**Problem:**

Users managing tables with numerous columns and rows currently face navigation inefficiency. To horizontally scroll through columns, one must first vertically scroll to the bottom of the table. This process can be time-consuming and diminishes the user experience, particularly when working with large datasets.

**Benefits:**

Enhances user experience by providing convenient access to horizontal scrolling.
Saves time and improves efficiency when managing large tables.
Facilitates quicker data analysis and navigation, especially in data-intensive applications.

**Search keywords**:

**Comment by romgrk** [comment]
You're likely using the datagrid incorrectly, there is no need to scroll to the bottom unless your grid container isn't fitter correctly. I would suggest to ensure your container is limited to the visible viewport, the grid can then display its scrollbar properly. Provide an [example](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx) if you require further assistance.
