### ISSUE TITLE
[pickers] Docs indicate PickersDay accepts a selectedDay prop but it doesn't appear to be true

### ISSUE THREAD

**Issue by ManuC84** [mui/mui-x#11169]
### Related page

https://mui.com/x/migration/migration-pickers-v5/#day-renderday

### Kind of issue

Other

### Issue description

The migration instructions seem to be wrong, I'm not getting any `selectedDay` prop, instead I'm getting a `selected` prop which accepts a boolean, how am I supposed to control the selected day then? 

```function CustomDay({ selectedDay, ...other }) {
  // do something with 'selectedDay'
  return <PickersDay {...other} />;
}

function App() {
  const [value, setValue] = React.useState(null);

  return (
    <DatePicker
      value={value}
      onChange={(newValue) => setValue(newValue)}
      slots={{ day: CustomDay }}
      slotProps={{
        day: { selectedDay: value },
      }}
    />
  );
}
```

### Context 🔦

I'm trying to migrate the `DateCalendar` to v6 

https://mui.com/x/migration/migration-pickers-v5/#day-renderday

In my old implementation I was passing the selected day like so: 

   ```
   renderDay={(day, _value, DayComponentProps) => {
          const props = dayFormatter(day);
          return <Day {...DayComponentProps} {...props} />;
   ```
          
 I'm confused about how to accomplish the same in v6 and the docs seem to be wrong.

**Search keywords**: selectDay renderDay

**Comment by ManuC84** [comment]
> Hi,
> 
> What's your use-case? Usually, to select a day you just pass a `value` to the `DatePicker`. In the migration guide you linked, `selectedDay` is a custom prop we added to demonstrate how a `CustomDay` component could receive data from the outside.

Thanks for replying. The use-case is so complex it would take too long to fully explain. However maybe you can help me with something. 

In the previous implementation I had my `renderDay` like so: 
```
        renderDay={(day, _value, DayComponentProps) => {
          const props = dayFormatter(day);
          return <Day {...DayComponentProps} {...props} />;
```

Now I'm trying to switch it to the new slots method like so: 

```
 slots={{
            day: (DayComponentProps) => {
              const props = dayFormatter(value as DateTime);
              return <Day {...DayComponentProps} {...props} />;
            },
          }}
```
I'm getting the `value` from the `onChange` as the docs say, but this is not working at all. What's the right way to do this in the new version?

**Comment by LukasTy** [comment]
> Do you happen to know what's the right way to do this in the new version?

Is there any reason why you are trying to access the `day` variable with a different name than in v5? 🤔 
It hasn't changed.
You can find an example of how to use the day slot and access the `day` in [this codesandbox](https://codesandbox.io/p/sandbox/nice-shape-w9pd8z?file=%2Fsrc%2FDemo.tsx%3A15%2C11).

P.S. Remember to [obey the general React rules](https://mui.com/x/react-date-pickers/custom-components/#recommended-usage) for the slot components in order to avoid issues.

P.P.S. Could you clarify what you are doing in the `dayFormatter` function?
Maybe we could suggest a better way to achieve the same result. 🤔

**Comment by ManuC84** [comment]
> obey the general React rules

Thanks a lot for the helpful reply Lukas. As I said before this implementation is too complex to explain and the repo is private so I can't share it. The `dayFormatter` function returns props we use to style the date calendar. These props used to get spread and passed to our custom `Day` component but now with the v6 changes I'm struggling to achieve the same result.

This is how my custom Day component is defined: 

` const Day = (props: DayProps) => {...`

And this is how the props look like: 

`type DayProps = PickersDayProps<DateTime> & CustomDayProps;`

 Is there any way to achieve the same as before e.g., passing the `dayFormatter` and the previously named `DayComponentProps` that we used to get from `renderDay` as spread objects the our custom `Day` component?

**Comment by LukasTy** [comment]
I'm sorry if I'm not seeing something, but I really don't understand what is the actual problem you are having. 🤔 
I've updated my previous codesandbox example with an example of what I imagine your code might be trying to achieve.
It seems to work without issues and the provided `title` is applied to the day elements.

By the way, if it's only the styling that you want to change, consider going for approaches that are more suited for that, like using the `sx` prop or theme overrides. 😉 

Without having a working example, where we can reproduce your problem, it's really hard to identify your problem. We are basically trying to guess at this point. 🙈

**Comment by ManuC84** [comment]
@LukasTy I understand that this is hard to understand without being able to check the entire implementation, but let's try to isolate an issue here that is independent of the specific scenario here. Previously, if we used `renderDay` we were able to do something like this: 

```
        renderDay={(day, _value, DayComponentProps) => {
          const props = dayFormatter(day);
          return <Day {...DayComponentProps} {...props} />;
```

And it would work just fine. Is there any way I can achieve the same with the new `slots` system?

**Comment by LukasTy** [comment]
> Is there any way I can achieve the same with the new `slots` system?

Doesn't the example in the codesandbox show how to do it with slots?
The only difference I see is that now the slot receives all the props in one object, instead of 3. 🤔

**Comment by ManuC84** [comment]
I hadn't seen the new changes in the codesandbox, let me try a few things and I will get back to you 👍

**Comment by ManuC84** [comment]
@LukasTy I think we can close this one. I haven't solved my problem yet, but this discussion helped me to understand how to use the v6 slots system better, now I need to fix some other issues on my end. I really appreciate all the help.

**Comment by LukasTy** [comment]
> this discussion helped me to understand how to use the v6 slots system better,

@ManuC84 I'm glad we were able to help you understand the concept and think of possible fixes to resolve your issue. 👍 
Consider reading [this page](https://mui.com/base-ui/guides/overriding-component-structure/) to better understand the slots mental model. 😉 

What was the main thing that you had problems understanding?
Maybe with enough constructive feedback, we could improve the documentation to avoid this confusion. 🤞 

I'm closing the issue. Please feel free to reopen it if you still experience problems. 👌

**Comment by ManuC84** [comment]
@LukasTy 

Hey! I'm dealing with this error currently after finishing the migration. 

![image (1)](https://github.com/mui/mui-x/assets/66978893/6592ebb0-f306-4134-9e57-fc6e5984fa75)

Does this ring a bell to you by any chance? I've done the migration as the docs say and I haven't altered any other part of the implementation, which worked fine before. Just in case this has come up before in your circles.

**Comment by LukasTy** [comment]
@ManuC84 That is a really interesting error you have encountered.
I haven't seen it. 🤷 

It would seem that your validation properties could be incorrect.
Have you migrated from v5 to v6?
Could it be that you are using plain date strings for some of the props (specifically validation props in this case)?
In v5 it was possible to provide an ISO date string for props and we'd try parsing it to the object of the relevant adapter, but [in v6 that's no longer done](https://mui.com/x/migration/migration-pickers-v5/#update-the-format-of-the-value-prop) and we require all props to be provided in the type of the adapter you are using.

Having at least a minimal reproduction example would really help! 🙏 
As you mentioned, it could be some sort of an edge case bug with the usage of different timezones if you are using that as well, that's why without a reproduction example we can only guess. 🤷

**Comment by ManuC84** [comment]
@LukasTy Thanks for the useful data, I will keep investigating based on this. By the way, I've migrated only the `@mui/x-date-pickers` package to v6, not all of MUI.

**Comment by ManuC84** [comment]
@LukasTy We finally could solve the issue. Just in case it's of any interest to you and the team, I had to pass `disableFocusListener` to this Tooltip implementation:

```
  if (tooltip) {
    return (
      <Tooltip
        disableFocusListener
        TransitionProps={{
          timeout: { appear: 200, enter: 200, exit: 0 },
        }}
        enterTouchDelay={0}
        title={tooltip}
      >
        <StyledDay {...props} />
      </Tooltip>
    );
  }
  ```
  
My team mate discovered this: 

> It looks to me like the onFocus listener was [renamed](https://github.com/mui/mui-x/pull/5820/files#diff-ed51fb35c17eca9a61a95b17f2b2e9180effee01a9819ca441aed26bd11cbbb5L46) (from onDayFocus to onFocus), so the Tooltip component is now trying to use it for itself (https://github.com/mui/material-ui/blob/v5.6.3/packages/mui-material/src/Tooltip/Tooltip.js#L573), but it’s not working because onFocus expects a focus event + a day, not just an event.
