### ISSUE TITLE
[charts] `labelStyle` prop not working

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#11172]
### Steps to reproduce

Link to live example: (required)

Steps:
1. https://codesandbox.io/p/sandbox/zen-https-3mhnlz?file=%2Fsrc%2FDemo.js%3A43%2C25

```jsx
      <ChartsYAxis label="Results" position="left" axisId="eco" labelStyle={{
        fontSize: 20,
        fill: '#ff00a2',
      }} />
```

### Current behavior

No customizations applied

<img src="https://github.com/mui/mui-x/assets/3165635/c3e573d2-34de-4c64-a4b5-53989a60579a" width="101">

### Expected behavior

No customizations applied

<img src="https://github.com/mui/mui-x/assets/3165635/821555e9-3329-4b8a-bff8-8bc0ea0635ee" width="168">

### Context

I tried to use https://mui.com/x/api/charts/charts-y-axis/#ChartsYAxis-prop-labelStyle but it didn't work, this changes makes it work

```diff
diff --git a/packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx b/packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
index 7b40a2bea..11c5b7bfe 100644
--- a/packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
+++ b/packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx
@@ -60,6 +60,7 @@ function ChartsYAxis(inProps: ChartsYAxisProps) {
     tickFontSize,
     label,
     labelFontSize,
+    labelStyle,
     tickSize: tickSizeProp,
     valueFormatter,
     slots,
@@ -110,6 +111,7 @@ function ChartsYAxis(inProps: ChartsYAxisProps) {
         angle: positionSign * 90,
         textAnchor: 'middle',
         dominantBaseline: 'auto',
+        // ...labelStyle,
       } as Partial<ChartsTextProps>['style'],
     } as Partial<ChartsTextProps>,
     ownerState: {},
```

now, to consider if the `labelStyle` prop API is needed in the first place, this works:

```jsx
      <ChartsYAxis label="Results" position="left" axisId="eco" slotProps={{
        axisLabel: {
          style: {
            fontSize: 20,
            fill: '#ff00a2',
          },
        },
      }} />
```

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: qed

**Comment by akamfoad** [comment]
> now, to consider if the labelStyle prop API is needed in the first place

Making `labelStyle` work in this release seems to be compliant with the advertised API, it can be deprecated like `labelFontSize` was deprecated for `labelStyle.fontSize` and get removed in next major version.

Opened #11180 to fix this issue for now.

**Comment by alexfauquette** [comment]
> now, to consider if the labelStyle prop API is needed in the first place, this works:

@oliviertassinari The text will effectively get this style. But if we add some logic about text placement, it will be broken. The reason is that I need to compute the text bounding box. And for that, I need to define a single way to pass style that can be reproduced easily.

For now, only the legend and the x-axes ticks have some logic based on text size (it avoids overlapping elements) But I prefer to have a standard way to say "For text customisation, use a style object"
