### ISSUE TITLE
[DataGrid] How to get row information on checkbox selection when you have custom id's

### ISSUE THREAD

**Issue by NckCode** [mui/mui-x#11204]
In my project, there's no unique field that can be used for _getRowID_ so I have created a custom ID for each row which is a combination of fields. The problem is when I click on the checkbox I use _onRowSelectionModelChange_ which returns the ID of the selected row. But how do I compare the ID with the custom ID? 

I checked the structure using _onRowClick_ to see where the ID is stored and it is outside of the row and column. All of the DataGrid value is coming through API and can be different each time so I don't have access to it. Does anyone have any idea how can I get the row value of the selected row in this case?

Here's an example of how where the ID is stored `{
column:...,
row:....,
id:...}`

**Search keywords**:

**Comment by michelengelen** [comment]
Hi @NckCode
Can you provide a working example of your problem in codesandbox? You can use this [template](https://codesandbox.io/p/sandbox/romantic-einstein-6xs4yd?file=%2Fpackage.json) as a starting point.

**Comment by NckCode** [comment]
https://codesandbox.io/p/sandbox/cool-clarke-ct6kxz?file=%2Fsrc%2FDemo.tsx%3A69%2C35
Here is a rough example of the problem I am facing when you click on the checkbox ID is returned and when you click on a row you can see where the ID is present.

**Comment by michelengelen** [comment]
@NckCode if I correctly understand your problem:
1. You have a set of data (rows) where you need to manually create IDs (`sys_id` + `field1`)
2. These IDs are then used for the datagrid
3. when you click/select a row you need to now the `sys_id` from your example, right?

**Comment by NckCode** [comment]
@michelengelen Not exactly

1. I have to set ID based on whether `is_primary` is true or not and then I combine those together
2. When the checkbox is selected ID is returned which is the combination of `is_primary` fields
3. I want to get the value of the entire row when its checkbox is selected in order to perform operations like delete 
4. I can get those values using `onRowClick` but that's not ideal

**Comment by michelengelen** [comment]
ok, so to generate a custom id you can do something like this:
```ts
let id = row[sys_id];
if (row[1].is_primary) {
  id = `${id}__${row[1].value}`;
}
...
```

That way you can deconstruct the `sys_id` value by splitting the string with the delimiter `__`:

```ts
const sysId = id.slice('__')[0];
```

---

For the other thing (getting all values of the selected rows) when performing a bulk action we do have a recipe for that: https://mui.com/x/react-data-grid/recipes-editing/#bulk-editing
Does that help you?

**Comment by NckCode** [comment]
@michelengelen Thanks, for the reference and the snippet for custom id's that helps. I couldn't find any reference for bulk operations that recipe helps a lot.
