### ISSUE TITLE
[question] Filtering values for array value columns

### ISSUE THREAD

**Issue by z0d14c** [mui/mui-x#11219]
### Order ID or Support key 💳

77204

### Search keywords

filter array value

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have a column (call it "labels") which has an array of values e.g. ["something", "banana", "apple"].

This should probably have a custom filter operator/selector that populates the "value" selector with a multi-select and filters on that. However, I don't have time to implement that right now. What I would like to do is allow the user to use the default filters (and quick filters) and just treat the value as a concatenation of all the values (e.g. the example with the above is "somethingbananaapple" so if the user types in "apple" it would filter appropriately). This isn't perfect but it seems like a reasonable stopgap until I can implement the multi-select.

However, I don't want to define a valueGetter because we have a custom output that needs the proper array value (and valueGetter will affect that). if anything, I want something like a filterValueGetter -- something that only applies to filters and nothing else, that I can use to combine the values as described previously.

Does this exist in any form or workaround currently?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by michelengelen** [comment]
Hey @z0d14c 
I think this should be feasible even without the need to add a new method, but to try and understand your problem in depth we would need an example. Could you provide us with a (minimal) working example? You can use [this template](https://codesandbox.io/p/sandbox/eager-morse-62zk74) as a starting point. 
Thanks! 🙇🏼
