### ISSUE TITLE
[DataGrid] Syntax for adding MUI elements to DataGrid columns.

### ISSUE THREAD

**Issue by JasonLMoffit** [mui/mui-x#11216]
### The problem in depth 🔍

Would like to seee an example of how MUI elements are added to DataGridPro columns/cell. For example graphs, Pills Typography etc.

**Search keywords**: DataGrid, Components, columns
**Order ID**: 78820

**Comment by michelengelen** [comment]
Hi @JasonLMoffit 
We do have a section about custom components for cell rendering in the docs. Check out [this section](https://mui.com/x/react-data-grid/column-definition/#rendering-cells).
I agree that we could maybe add recipes for more complex components for the `renderCell` method. @cherniavskii should we add a ticket under the recipe umbrella #9328?

**Comment by cherniavskii** [comment]
There's also [Custom columns](https://mui.com/x/react-data-grid/custom-columns/) page, where we can add more examples
