### ISSUE TITLE
[DataGrid] Boolean columns don't fallback to the standard render cell implementation

### ISSUE THREAD

**Issue by sidneibjunior** [mui/mui-x#11217]
### Steps to reproduce

[Link to live example](https://stackblitz.com/edit/react-uarbpf?file=Demo.tsx) 

Steps:
1. create a datagrid and define a column with the `boolean` type
2. add an empty function as a custom `renderCell` function to the boolean column definition 

### Current behavior

The boolean cell is rendered with the "yes" / "no" string.
![image](https://github.com/mui/mui-x/assets/3899718/117c830c-c949-448f-974a-2a509510adde)

### Expected behavior

Since the `renderCell` function is returning `undefined`, the standard datagrid render cell function should run and it should render the same as when no `renderCell` function is defined.
![image](https://github.com/mui/mui-x/assets/3899718/92264c86-8606-4746-98a3-b6cca5d52aae)

For other column types like `date` and `dateTime` it works. It seems that the bug is only when `type` = `boolean` or `actions`

### Context

I'm trying to implement a custom render cell and applying it to all cells. It returns "N/A" when the cell is not available based on some conditions. When the cell is available, I want to render the cell using the standard Datagrid cell renderers.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: renderCell

**Comment by michelengelen** [comment]
Hi @sidneibjunior 
The behavior is correct as it is. To explain this a bit:
1. when you define a function for `renderCell` it will execute that function. And it does that correctly.
2. The fallback for when the `renderCell` function is returning nothing is the `valueFormatter`.

The reason this works on the other fields is that it simply returns a string, but cannot do that with a boolean value. So we do have a default boolean `valueFormatter` in place that creates localized `yes` or `no` strings to output.
You can define that in a custom `valueFormatter` in the `colDef` of your data.

Is that about right @MBilalShafi ?

**Comment by simbahandiane** [comment]
@michelengelen I tried following the sample demo that you've provide but currently, for V7, it is not working.
