### ISSUE TITLE
[pickers] When I make my site live after uploading the build, it provides me the following error after opening app  "Cannot find module 'dayjs'" , however working fine on my localhost

### ISSUE THREAD

**Issue by hamza8amin** [mui/mui-x#11220]
### Steps to reproduce

Link to live example: (required)

Steps:
1. I installed the @mui/x-date-pickers as I am using the material UI in my app
2. Embedded the  DatePicker.
3. Working fine on localhost but when I upload the build, it show the following error on app "Cannot find module 'dayjs'"

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
OS: Windows 10 10.0.19044
CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Memory: 4.94 GB / 15.92 GB
Binaries:
Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
Managers:
Composer: 2.4.1 - C:\ProgramData\ComposerSetup\bin\composer.BAT
Utilities:
Git: 2.37.2. - /mingw64/bin/git
Curl: 7.84.0 - C:\Program Files\Git\mingw64\bin\curl.EXE
Virtualization:
Docker: 24.0.6 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
IDEs:
VSCode: 1.84.2 - C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
Languages:
Bash: 5.1.16 - C:\Program Files\Git\usr\bin\bash.EXE
Perl: 5.36.0 - C:\Program Files\Git\usr\bin\perl.EXE
PHP: 8.1.6 - C:\xampp\php\php.EXE
Browsers:
Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.72)
Internet Explorer: 11.0.19041.1566
```
</details>

**Search keywords**: days js

**Comment by LukasTy** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot. 🙏 
A live example would be perfect. [This **codesandbox.io** template](https://mui.com/r/x-issue-template) _may_ be a good starting point. Thank you!

One idea to double-check is if you have the `dayjs` library in the `dependencies` list.
Or are you using a different library to manage dates in your application?
P.S. It would have also helped if you provided the result of running `npx @mui/envinfo`.

**Comment by hamza8amin** [comment]
Response after hitting npx @mui/envinfo : 
  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 4.94 GB / 15.92 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE     
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD        
  Managers:
    Composer: 2.4.1 - C:\ProgramData\ComposerSetup\bin\composer.BAT
  Utilities:
    Git: 2.37.2. - /mingw64/bin/git
    Curl: 7.84.0 - C:\Program Files\Git\mingw64\bin\curl.EXE
  Virtualization:
    Docker: 24.0.6 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.84.2 - C:\Users\hp\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Program Files\Git\usr\bin\bash.EXE
    Perl: 5.36.0 - C:\Program Files\Git\usr\bin\perl.EXE
    PHP: 8.1.6 - C:\xampp\php\php.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.72)
    Internet Explorer: 11.0.19041.1566

**Comment by LukasTy** [comment]
> Response after hitting npx @mui/envinfo :

Could you please run it at the root of your project?
