### ISSUE TITLE
[DataGrid] How to completely hide a column in the columns menu

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#11227]
### Summary 💡

Just the way we are disabling username from getting hidden in the docs below - 

![image](https://github.com/mui/mui-x/assets/109504204/415bcc12-4812-4ce0-952a-68a1478137f8)

Is there some way that i can completely remove **username** and not just disable it from being hidden?

**Search keywords**: Datagrid column menu

**Comment by michelengelen** [comment]
Hi @noobDev31 and thanks for raising this issue.
I am not exactly sure how to completely remove the entry from the overlay, but looking at the `GridColDef` [interface docs](https://mui.com/x/api/data-grid/grid-col-def/) this behavior is incorrect (or the docs explanation is incorrect).

<img width="870" alt="Screenshot 2023-11-29 at 09 23 11" src="https://github.com/mui/mui-x/assets/32863416/b37c7f61-3c4e-4b0e-93ef-851e2c2dcf22">

@MBilalShafi what would be the correct way to target this?

**Comment by MBilalShafi** [comment]
@noobDev31 I think you are looking for [`slotProps.columnsPanel.getTogglableColumns`](https://mui.com/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel) prop, it handles the exact same use case.

Let me know if it resolves your issue.

**Comment by MBilalShafi** [comment]
That's what it does, check [this codesandbox](https://codesandbox.io/p/sandbox/dark-sunset-w3g6vf?file=%2Fsrc%2FDemo.tsx%3A1%2C1) for example.

I understand the example in the demo is a bit confusing i.e. in the above code snippet, it's showing to remove `id` column from togglable columns, while in the actual example (just below it) it's doing it for `['__row_group_by_columns_group__', 'status']`

**Comment by michelengelen** [comment]
Thanks @MBilalShafi

**Comment by noobDev31** [comment]
Thanks @MBilalShafi for updating the docs.

**Comment by noobDev31** [comment]
@MBilalShafi i had one small question is this functionality there on version  **"@mui/x-data-grid-premium": "~5.17.12"** ?

**Comment by MBilalShafi** [comment]
It was released in [v6.1.0](https://github.com/mui/mui-x/releases/tag/v6.1.0) and is available for this and the following versions.
