### ISSUE TITLE
[pickers] The input ref value take the previous value

### ISSUE THREAD

**Issue by lyquocphong** [mui/mui-x#11222]
### Search keywords

inputref

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

I have initialize the DatePicker component  like this

```jsx
const inputRef = useRef<HTMLInputElement>(null);

console.log(inputRef.current?.value);

const handleFieldChange = (fieldName: string, newValue: FieldValueType) => {
        if (value !== newValue) {
            setBackgroundColor('#fff8d9');
        } else {
            setBackgroundColor('unset');
        }

        onChange(fieldName, newValue);
    };
```

Steps:
1.  Select one day and you will see the first time the value is empty
2. After that select another day and you will see the value of ref is the previous one
3.

### Current behavior

The inputRef.current.value has value from previous value

### Expected behavior

When I select date in picker, the inputRef.current.value should have value is the selected date

### Your environment

**Comment by alexfauquette** [comment]
Could you provide a full reproduction example that we could experiement with?

Here is a starting point:
https://stackblitz.com/edit/react-ktczzv?file=Demo.tsx

**Comment by lyquocphong** [comment]
[https://stackblitz.com/edit/react-ktczzv-9n6rhk?file=Demo.tsx](url)

You can check the console that when first time it render it will said undefined, after you select date, it will said undefined and after second time if will render with empty string

**Comment by alexfauquette** [comment]
From what I see, it always return undefined

The `ref` is not necessary the input one. Here is a proper way to pass ref to the input

```jsx
slotProps={{
  textField: {
    inputRef,
  },
}}
```

The fact your ref is late is because you log the ref before the render occurs. So you read the HTML element before it get updated.

https://stackblitz.com/edit/react-ktczzv-ydpwf3?file=Demo.tsx

I don't see the point of using a ref to keep track of the value since you already have the `onChange` to do that. WHich simplify the state synchronisation.

**Comment by LukasTy** [comment]
I also wanted to mention that Picker components have a [top level `inputRef` prop](https://mui.com/x/api/date-pickers/date-picker/#DatePicker-prop-inputRef) that can be used to pass the ref directly to `input` component.
As Alex mentioned, your usage of ref seems a bit strange. 🤔 

Could you expand on what are you trying to achieve? Maybe we'll be able to help you come up with the most optimal solution for it. 🤞

**Comment by lyquocphong** [comment]
> I also wanted to mention that Picker components have a [top level `inputRef` prop](https://mui.com/x/api/date-pickers/date-picker/#DatePicker-prop-inputRef) that can be used to pass the ref directly to `input` component. As Alex mentioned, your usage of ref seems a bit strange. 🤔
> 
> Could you expand on what are you trying to achieve? Maybe we'll be able to help you come up with the most optimal solution for it. 🤞

I have also try the inputRef in the topLevel because I know that inside mui-x used useForkRef. But both case does not give me the right value.

As I mentioned that I do not want to use useState because I do not want the component rerender because of value selected. 

So my question is if I want to use ref to get value of the input element, how I can do that ? because with TextField in MUI, I can use ref so I thought I can use the same with DatePicker

**Comment by lyquocphong** [comment]
> From what I see, it always return undefined
> 
> The `ref` is not necessary the input one. Here is a proper way to pass ref to the input
> 
> ```js
> slotProps={{
>   textField: {
>     inputRef,
>   },
> }}
> ```
> 
> The fact your ref is late is because you log the ref before the render occurs. So you read the HTML element before it get updated.
> 
> https://stackblitz.com/edit/react-ktczzv-ydpwf3?file=Demo.tsx
> 
> I don't see the point of using a ref to keep track of the value since you already have the `onChange` to do that. WHich simplify the state synchronisation.
> 
> For showing error, ... did you see this docs section? https://mui.com/x/react-date-pickers/base-concepts/#overriding-slots-and-slot-props

I use onHandleChange because I want component rerender to log for you. My goal is I do not want the DatePicker to rerender at all. I do not know that after I select date from the picker and I do not have onChange handler, will DatePicker component rerender ?

**Comment by alexfauquette** [comment]
You can do that because when pressing a key in the textfield the input is controlled but the controlled value (the one after a render cycle is the same as the one typed by the user)

For pickers if pressing 2 when year is selected, the input values goes from `10/25/yyyy` to `10/25/2` to `10/25/0002`

You can reproduce similar behavior with a textfield with some internal logic:

https://stackblitz.com/edit/react-ktczzv-zi7smq?file=Demo.tsx
