### ISSUE TITLE
[DataGrid] Inconsistent event handler behavior with defaultMuiPrevented

### ISSUE THREAD

**Issue by noah-lee** [mui/mui-x#11232]
### Steps to reproduce

Reproduction:
https://codesandbox.io/p/sandbox/tender-morse-29g8pz?file=%2Fsrc%2FDemo.tsx%3A25%2C15-25%2C34

### Current behavior

Disabling the default behavior of DataGrid using `event.defaultMuiPrevented = true` behaves differently based on the event subscription method.

1) **Expected**: The first example passes the cellEditStop event handler as a prop to DataGrid (reference: https://mui.com/x/react-data-grid/events/#with-the-prop-of-the-event). The default behavior is correctly disabled on cell focus out.

2) **Issue**: The second example subscribes to the cellEditStop event using `apiRef.current.subscribeEvent`. The default behavior is not disabled on cell focus out. The same issue happens with subscribing with `useGridApiEventHandler`

### Expected behavior

It is expected that the default behavior can be disabled with all three event subscription methods: prop, `useGridApiEventHandler` and `apiRef.current.subscribeEvent`.

If the reproduction is the correct and expected behavior, the documentation should clearly indicate that disabling the default behavior can only work when passing the event handler as a prop to DataGrid.

### Context

The goal is to be able to prevent the default behavior while subscribing to the event from separate components; both inside (e.g. footer, toolbar, edit cell, etc.) and outside.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: Google Chrome
```
</details>

**Search keywords**: datagrid events

**Comment by michelengelen** [comment]
@noah-lee I did find a solution for your problem.
You can pass options to the `subscribeEvent` method to tell the event manager that this handler should run first. 

```
const handleCellEditStop: GridEventListener<'cellEditStop'> = React.useCallback(
  (params, event) => {
    console.log('reason', params.reason);
    if (params.reason === GridCellEditStopReasons.cellFocusOut) {
      event.defaultMuiPrevented = true;
    }
  },
  [],
);

React.useEffect(() => {
  // we can pass the options here
  return apiRef.current.subscribeEvent('cellEditStop', handleCellEditStop, { isFirst: true });
}, [apiRef, handleCellEditStop]);
```

The question remains though: Why does the subscribed events have lower priority than the ones passed into the props? Any ideas @mui/xgrid ?

cc/ @DanailH

**Comment by DanailH** [comment]
Nice one @michelengelen. I think the reason is the execution order for the callbacks from the `subscribeEvent` and the actual callback, but since there is a flag that might be enough.
