### ISSUE TITLE
License IFrame Appears even though I've paid for the license 

### ISSUE THREAD

**Issue by damiangreen** [mui/mui-x#11236]
### Steps to reproduce

Cant link to live example with my key

### Current behavior

I'm seeing this Iframe overlay 
![image](https://github.com/mui/mui-x/assets/1592820/a3af9805-6ffb-479f-b23f-e691f1c8305c)

For license information please see iframe-bundle.js.LICENSE.txt

Even though I have set `icenseInfo.setLicenseKey(`....

The behaviour seems a bit sporadic

### Expected behavior

No iframe overlay

### Context

means I cant click on Dom elements without deleting the Iframe element

### Your environment

 System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: Not Found
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.24 
    @mui/core-downloads-tracker:  5.14.18 
    @mui/icons-material: 5.14.9 => 5.14.9 
    @mui/lab: 5.0.0-alpha.144 => 5.0.0-alpha.144 
    @mui/material: 5.14.10 => 5.14.10 
    @mui/private-theming:  5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/styles: 5.14.10 => 5.14.10 
    @mui/system: 5.14.9 => 5.14.9 
    @mui/types:  7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-premium: 6.18.1 => 6.18.1 
    @mui/x-data-grid-pro:  6.18.1 
    @mui/x-license-pro: 6.10.2 => 6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react: 17.0.2 => 17.0.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.4.3 => 4.4.3 

**Search keywords**: License Key IFrame Overlay

**Comment by alexfauquette** [comment]
What make you think it's related to the license?

To inform about a wrong licence, we add a watermark, but nothing related to an iframe

**Comment by damiangreen** [comment]
Oops my mistake then. Must be completely related to MUI, This site has the same problem
https://qna-habr-com.translate.goog/q/1124000?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en

i'll investigate which package   is causing. Apologies

**Comment by alexfauquette** [comment]
No worries, good luck with your investigation
