### ISSUE TITLE
[pickers] Upgrading @mui-datepickers-pro from 6.2 to 6.18.x TypeScript

### ISSUE THREAD

**Issue by landlessfarm** [mui/mui-x#11256]
### The problem in depth 🔍

Hello - I've used MUI for some years and have never had to reach out, but I'm legitimately stuck here.  

When updating datepickers-pro from 6.2 to 6.18, my typescript setup fails(where it was fine before), suddenly throwing many errors like "[X] cannot be used as a JSX component".  I attempted to use 
```
"resolutions": {
  "@types/react": "^17.0.38"
}
```
and some other iterations of that approach, with no luck.   I've not been able to find anything further on the issue.  I'm using the mantis react template, but I've removed any extra files I'm not using.  Has anyone encountered this before, and can speak to what dependencies are likely causing the problem?  Even some support on where to look would be greatly appreciated. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  All on chrome at the moment
    System:
    OS: macOS 13.4.1
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Edge: Not Found
    Safari: 16.5.2
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base: ^5.0.0-alpha.126 => 5.0.0-alpha.126 
    @mui/core-downloads-tracker:  5.12.1 
    @mui/icons-material: ^5.14.16 => 5.14.16 
    @mui/lab: ^5.0.0-alpha.127 => 5.0.0-alpha.127 
    @mui/material: ^5.12.1 => 5.12.1 
    @mui/private-theming:  5.12.0 
    @mui/styled-engine:  5.12.0 
    @mui/system: ^5.12.1 => 5.12.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.0 
    @mui/x-data-grid:  6.16.2 
    @mui/x-data-grid-pro: ^6.16.2 => 6.16.2 
    @mui/x-date-pickers: ^6.2.0 => 6.2.0 
    @mui/x-date-pickers-pro: ^6.2.0 => 6.2.0 
    @mui/x-license-pro:  6.0.4 
    @mui/x-tree-view: ^6.17.0 => 6.17.0 
    @types/react: ^18.0.37 => 18.0.37 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.0.4 => 5.0.4 
```
</details>

**Search keywords**: datepickers, AdapterDateFns
**Order ID**: 77509

**Comment by LukasTy** [comment]
Hello, would you be able to provide a reproduction example in any form?
A codesandbox or a minimal repository would be best.
A few things to double-check:
- Have you upgraded both Pickers packages?
- Did you try upgrading Typescript?
- Is it happening on both dev and production builds?
