### ISSUE TITLE
Datagrid Premium: Autosize columns on the Expansion of a Group

### ISSUE THREAD

**Issue by DunhamPerry** [mui/mui-x#11262]
### Summary 💡

When presented with a grouped datagrid premium, when the use expands a group I would like the columns to autosize. Either that or a property such as `onGroupExpand` that will allow me to trigger a remount after setting the `isGroupExpandedByDefault` with the newly expanded row.

### Examples 🌈

After expansion. You can see the columns did not autosize on expansion.
<img width="1728" alt="Screenshot 2023-11-30 at 12 20 56 PM" src="https://github.com/mui/mui-x/assets/17463859/96a9678f-9fd9-473f-8367-7f68774448cd">

What I want it to look like.
<img width="1728" alt="Screenshot 2023-11-30 at 12 21 32 PM" src="https://github.com/mui/mui-x/assets/17463859/0bf78ba9-2391-4324-865c-d725e76a6934">
^ This was done by setting `defaultGroupingExpansionDepth={-1}`. But I don't want these groups to be expanded by default. I want the groups to be collapsed initially with the columns autosizing on expansion OR the columns being the autosized on load (albeit the data is hidden as the group is collapsed).

### Motivation 🔦

I want the user to be presented with an initially grouped Datagrid with all the groups collapsed. Upon expanding a group, the user sees the data autosized based on my `autosizeOptions`. I don't want the user to expand the group and then have to manually increase the width of each column. 

**Search keywords**: datagrid premium group expand expansion autosize column
**Order ID**: 78285

**Comment by michelengelen** [comment]
related to #11261 @cherniavskii ?

**Comment by cherniavskii** [comment]
Hi @DunhamPerry 
Is this the behavior you're looking for? https://codesandbox.io/p/sandbox/flamboyant-glitter-8n4fdr?file=%2Fsrc%2FDemo.tsx%3A37%2C38
I've used the `rowExpansionChange` event + `apiRef.current.autosizeColumns` method.

**Comment by cherniavskii** [comment]
We could add a demo to our docs.

**Comment by MBilalShafi** [comment]
Side note related to no response workflow:
I think auto-removing the `status: waiting for author` label on the issue reopen could be useful for avoiding accidental reclosing.
I can't think of a use case where this would cause any notable unwanted behavior. @cherniavskii what do you think?

**Comment by LukasTy** [comment]
@MBilalShafi 
In regards to re-adding a label on re-opened issue:
Should we need it? 🤔 
Maybe there is some other problem, but I think that a re-opened issue, which does not have a `waiting for author` label should not have been closed by the GH action. 🤷 
WDYT?

**Comment by cherniavskii** [comment]
> Maybe there is some other problem, but I think that a re-opened issue, which does not have a waiting for author label should not have been closed by the GH action. 🤷
WDYT?

I didn't remove the "waiting for author" label when I reopened the issue the first time, and this is why it got closed again 🙂
After I removed the label and reopened it, it's OK.

**Comment by cherniavskii** [comment]
> I think auto-removing the status: waiting for author label on the issue reopen could be useful for avoiding accidental reclosing like on this one.

Makes sense to me 👍🏻
