### ISSUE TITLE
DataGridPro: onRowEditStop is fired even when row is visually in edit mode (editmode="row"), when using conditional validation

### ISSUE THREAD

**Issue by atsoy** [mui/mui-x#11263]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/inspiring-dijkstra-g2h52p

Steps:
1. Double click on **isPaid** field in the 2nd row (Rent)
2. Check the box (validation requires the selected option in the **Payment Method** field
3. Click outside the Row / Table

### Current behavior

Row stays visually in the `mode: 'edit'`, but `onRowEditStop` callback is triggered

### Expected behavior

- Row stays visuablly in the `mode: 'edit'`
  - `preProcessEditCellProps` validation is still active
- Grid doesn't fire `rowEditStop` event, because of invalid field input 

### Context

There is a **SUBMIT** button, which should be disabled when user edits a row.
So when user starts editing, it fires `rowEditStart` event and sets disabled flag to `true`.
By finishing editing, `onRowEditStop` should set the disabled flag to `false`, and user is able to click on submit.

P.S: I might be wrong, but could it be related to #10930 ?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagridpro, onRowEditStop, conditional validation, switch row modes
**Order ID**: 62555

**Comment by michelengelen** [comment]
I can confirm that this is a bug. The `'rowEditStop'` event should not be fired when the row is still in edit mode.

@mui/xgrid Any idea how we could provide a workaround for @atsoy ?

**Comment by atsoy** [comment]
Thanks for the feedback @michelengelen , our current workaround built around `onRowModesModelChange` callback, we check if any row is in edit mode, if yes we disable the submit button, if not - enable.

_Caveats_: Because of this issue, button state jumps from disabled (`onRowEditStart`) to enabled (row is visually in edit mode, but `onRowEditStop` was triggered), and to disabled shortly after (`onRowModesModelChange` checks are processed). Which is not the best UX, but still ok from the functional perspective, until it gets fixed.


Example:
```tsx
        onRowModesModelChange={(rowModes, _event) => {
          const changedRows = Object.keys(rowModes);
          let disableButton = false;
          if (changedRows.length) {
            disableButton = changedRows.some(
              (currentRow) => rowModes[currentRow].mode === 'edit'
            );
          }
          setSubmitDisabled(disableButton);
        }}
```

**Comment by atsoy** [comment]
@DanailH as a MUI X Pro user I wanted to ask if you can share the information, when we could expect the fix for it?

**Comment by michelengelen** [comment]
@atsoy I did add this to our project board. It really depends on how tricky a fix will be. Additionally we are currently pretty busy with preparing the new major release. Nonetheless I will raise awareness with the team so we can at least have a look and estimate it.
