### ISSUE TITLE
[DataGrid] Multi-select in custom toolbar closes after choosing one item

### ISSUE THREAD

**Issue by mtr1990** [mui/mui-x#11274]
### Steps to reproduce

https://codesandbox.io/p/sandbox/datagrid-forked-kwl7lz?file=%2Fsrc%2FApp.tsx%3A70%2C11-70%2C19

### Current behavior

The Select menu closes automatically when only 1 item is selected

### Expected behavior

The Select menu closes automatically when only 1 item is selected

### Context

Customize select outside DataGrid Toolbar.
=> Select multiple items in one action

Customize select inside DataGrid Toolbar.
=> Not select multiple items in one action

**Search keywords**: auto close multiple select

**Comment by mtr1990** [comment]
Hi @michelengelen ,

Thanks for responding and providing a solution.

My aim is to get the values ​​from `MultiSelect ` and use this to filter data from the grid.

However, I don't know how to get these values ​​exactly with the desired behavior of selecting multiple items in one go.

The global state appears ready to do this. But it wouldn't be suitable in my case. Do you have any other ideas or solutions?

https://codesandbox.io/p/sandbox/datagrid-forked-spsjsc?file=%2Fsrc%2FApp.tsx%3A61%2C8

**Comment by michelengelen** [comment]
Hey @mtr1990 

So, when you need the values set in the `MultiSelect` component you can just pass a handler into the component that gets called in the `onClose` or `onBlur` method.

[Here](https://codesandbox.io/p/sandbox/datagrid-forked-spsvln?file=%2Fsrc%2FApp.tsx%3A58%2C12) is a working example, logging the selected names in the console when the select closes.

This is where you can then update the filtering with the [`apiRef`](https://mui.com/x/react-data-grid/filtering/#apiref) from the datagrid.
Let me know if you need more help with this.

Thanks! 🙇🏼
