### ISSUE TITLE
[dataGrid] Tooltip stays on the screen for a while even after the element has been scrolled up

### ISSUE THREAD

**Issue by AkankshaPushkarna** [mui/mui-x#11298]
### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/p/sandbox/tender-ptolemy-j3wg95?file=%2Fsrc%2FDemo.tsx%3A48%2C56)

Steps:
1. In a data grid, hover on an element visible on the screen that has tooltip.
2. While hovering on it, scroll the page so much so that the element is not visible
3. Observe that tooltip will stay for a while misplaced.

### Current behavior

tooltip seems to be missplaced for a while misplaced.

### Expected behavior

Tooltip should disappear as soon as mouse moves out.
![image](https://github.com/mui/mui-x/assets/16236462/d2c8ce1e-b1dc-4a81-9846-0bb10425c08e)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: tooltip

**Comment by cherniavskii** [comment]
Seems like it could be fixed with `disablePortal` https://github.com/mui/material-ui/issues/39901#issuecomment-1819086519

Here's the updated demo: https://codesandbox.io/p/sandbox/vigorous-shannon-fwqx27?file=%2Fsrc%2FDemo.tsx%3A12%2C6

@AkankshaPushkarna Is this the behavior you're looking for?

**Comment by sathish869** [comment]
Hi @cherniavskii  I am not able to open this link https://codesandbox.io/p/sandbox/vigorous-shannon-fwqx27?file=%2Fsrc%2FDemo.tsx%3A12%2C6


and I have created the sandbox project and you can access it with this link

https://codesandbox.io/p/sandbox/naughty-hugle-w4pf5l?file=%2Fsrc%2FradioButtonsComponent.jsx%3A90%2C71,
please have a look and help me to resolve this issue.
