### ISSUE TITLE
[DataGrid] Grid does not shrink properly on screen resize

### ISSUE THREAD

**Issue by tombryden** [mui/mui-x#11295]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/devbox/dark-bird-s7dhfg

Steps:
1. Open codesandbox link above
2. Resize screen and notice that when you expand the size, the datagrid expands, however when you try to reduce the size the datagrid does not reduce in size.
3. Comment `<Example />` in `App.tsx` and uncomment the lines below `WORKING (LONG TEXT)` comment
4. The datagrid now resizes properly
5. Comment the `WORKING (LONG TEXT)` code again, and uncomment the `WORKING (SHORT TEXT)` code below
6. Observe the datagrid not resizing properly, despite the only difference between the long text and short text version being the length of the paragraph

### Current behavior

The datagrid doesn't shrink consistently between the three scenarios above.

The short text & long text code is identical, apart from the length of the `<p>` text. I followed instructions from another issue which had the same problem seen here https://github.com/mui/mui-x/issues/8463#issuecomment-1496315707 - hence the attempt with using the instructions from this reply, although I would expect the shrinking behaviour to work with the simple scenario.

### Expected behavior

Datagrid should shrink consistently between all scenarios

### Context

Display a DataGrid with responsiveness when resizing the screen

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Chrome

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.0.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 119.0.6045.200
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.93)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.13
    @mui/core-downloads-tracker:  5.14.12
    @mui/icons-material: ^5.14.9 => 5.14.9
    @mui/lab: ^5.0.0-alpha.142 => 5.0.0-alpha.142
    @mui/material: ^5.14.12 => 5.14.12
    @mui/private-theming:  5.14.12
    @mui/styled-engine:  5.14.12
    @mui/system:  5.14.12
    @mui/types:  7.2.5
    @mui/utils:  5.14.19
    @mui/x-data-grid: ^6.18.2 => 6.18.2
    @types/react: 18.2.21 => 18.2.21
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.2.2
```
</details>

**Search keywords**: datagrid shrink resize

**Comment by michelengelen** [comment]
Hey @tombryden ... I can see that this is a bit inconsistent. We'll look into that.

In the meantime, did you try to use the components from our core package?
Here is a demo of how this could help you in achieving what you are aiming for: [Resize example](https://codesandbox.io/p/sandbox/condescending-wave-34m2lf?file=%2Fsrc%2FDemo.tsx%3A91%2C1)

I will have a look why that behaves differently.

**Comment by michelengelen** [comment]
Hey @tombryden ... Sry for the late reply. I have been looking into this issue this morning and I am not sure why the fix you found on the comment is not working for you.

It is working just fine for me: [resizing example](https://codesandbox.io/p/devbox/clever-dew-jw4vpf?file=%2Fsrc%2FApp.tsx%3A24%2C45)

I will close this issue now, but feel free to reopen if you need something else regarding this.

Thanks! 🙇🏼

**Comment by tombryden** [comment]
Thanks for looking into this, adding `overflow: hidden` seems to do the trick, looks like I put this in the wrong place.

**Comment by AlexanderKormilin** [comment]
Why is that closed?

the issue is totally still here, any plans on a valid solution, not a "overflow: hidden" shit?

**Comment by AlexanderKormilin** [comment]
@michelengelen

**Comment by AlexanderKormilin** [comment]
If you'd only know, how much id enjoy breaking your face right now, @michelengelen.

Do not fix a thing, ever. Just live knowing there is a people hating you, moron.

**Comment by AlexanderKormilin** [comment]
Had to spend more than an hour to roll back to V5 to make sure not shit spoken by the moroneous @michelengelen is ever in the project.

Youd better pray we are never going to be neighbours, scumbag.
And yes, i remember your name, and i will freaking spill it with shit you are every freaking time i will hear it.

Stupid, useless motherfucker.

**Comment by AlexanderKormilin** [comment]
And sure thing, v5 works just fine after some props and method name update.

JFYI: you're the most useless, stupid and shitty person i spoke with today, and im spoking to lots of shitty bastards.
I hope you will not make it to this morning, but in case you will - do not answer me, suck it silently, for your own piece.

**Comment by oliviertassinari** [comment]
As far as I understand this issue it's a userland misconfiguration of the use of flexbox. This seems to be enough to fix the issue:

```diff
       <div
-       style={{ flexGrow: 1, flexShrink: 0, flexBasis: 0 }}
+       style={{ flexGrow: 1, flexShrink: 0, flexBasis: 0, minWidth: 0 }}
         id="right"
       >
```

https://dfmcphee.com/flex-items-and-min-width-0/ explains why this happens. In more details: https://www.youtube.com/watch?v=cH8VbLM1958.

**Comment by mjlst** [comment]
Though this solution is a reasonable one, it looks and feels choppy. Are there any solution that solves this issue more smoothly/gracefully? It's been causing quite some issues using the latest version of MUI...

**Comment by vivere-dally** [comment]
It is easy to reproduce. For example the snippet above does not work. After you shrink and expand the first box, the Grid goes off the screen.

I guess redrawing it fixes the issue (in my case, I am presenting a grid with not much data - but for others this might be a deal breaker).

The other approaches that I found in github issue comments and on SO are just hacks that may or may not work.

This is a really simple use case and it feels like you have to hack it to work it your way.

```tsx
export default function Foo() {
    const [isOpen, setIsOpen] = useState(true)

    return (
        <Box sx={{ width: '100%', height: '100%', display: 'flex' }}>
                <Fab
                    color='primary'
                    aria-label='add'
                    onClick={() => {
                        setIsOpen(!isOpen)
                    }}
                >
                    do
                </Fab>
                <Box sx={{ width: '100%', height: '100%', display: 'flex' }}>
                    <Box sx={{ backgroundColor: 'red', width: isOpen ? 400 : 0 }}></Box>
                    <Box
                        sx={{
                            backgroundColor: 'blue',
                            flexGrow: 1,
                        }}
                    >
                        <DataGridPremium
                            // key={isOpen ? 1 : 2} -- rerender?
                            columns={[{ field: 'foo' }]}
                            rows={[{ id: 1, foo: '123' }]}
                        />
                    </Box>
                </Box>
           </Box>
    )
```

**Comment by oliviertassinari** [comment]
@vivere-dally Do you have reproduction where https://github.com/mui/mui-x/issues/11295#issuecomment-2232925715 doesn't work?

**Comment by vivere-dally** [comment]
@oliviertassinari yes, for the snippet above it does not work. But also important, the component is part of a large application. It is not just in a sandbox where it is the primary component. Other comments suggested that I should change all components from the grid float example to the root of the app. I am not wiling to make any other changes but in this component.
If I comment out the Grid in the example above, the flex behaves as expected.

**Comment by oliviertassinari** [comment]
@vivere-dally I would still be curious, It might be a matter of adding a width prop in the leaf.
