### ISSUE TITLE
[pickers] Use only IconButton to trigger DatePicker opening

### ISSUE THREAD

**Issue by johanndms** [mui/mui-x#11306]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

On the DatePicker it would be great to be able to turn off the TextField input completely - so ONLY show the calendar icon and if the user clicks it open the month calendar to pick a date.

### Examples 🌈

![datepicker-example](https://github.com/mui/material-ui/assets/16336986/31f93ca0-5231-4cf4-a35c-4490bf933ddf)

**Search keywords**:

**Comment by LukasTy** [comment]
Hello, have you checked the [documentation example](https://mui.com/x/react-date-pickers/custom-field/#using-a-button)?
Example shows a `Button` used as the trigger to open the picker.
In your case, you would basically need to replace `Button` with an `IconButton`.

Does that help with your case? 🤔

**Comment by johanndms** [comment]
Hello Lukias,

Thanks for the input and yes that would work but we don't seem to get it working with date-fns?

Thanks
Johann

**Comment by johanndms** [comment]
Hello Nora / Lukas,

Thanks got it working after some tinkering... Looks great and does the exact job we wanted!!

![Screenshot 2023-12-04 at 17 08 51](https://github.com/mui/mui-x/assets/16336986/bc527590-2cf9-4af9-944e-f2dd9861d4f9)

Looks great on mobile as well.

Thanks again for the quick assistance.

Johann
