### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by jnschultz** [mui/mui-x#11316]
### The problem in depth 🔍

Purchased new key today...

const x_license_pro_1 = require("@mui/x-license-pro");
x_license_pro_1.LicenseInfo.setLicenseKey('>MY_KEY_FROM_EMAL');

But still get 
 *************************************************************

MUI: License key expired.

Please visit https://mui.com/r/x-get-license to renew your subscription of MUI X.

*************************************************************

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 119.0.6045.200
    Edge: Spartan (44.19041.1266.0), Chromium (119.0.2151.97)

</details>

**Search keywords**: License expired
**Order ID**: 80102

**Comment by zannager** [comment]
@jnschultz can you please share your license key in x@mui.com. Thanks.
