### ISSUE TITLE
[charts] Is it possible to have a customised highlighted MarkElement for LineChart?

### ISSUE THREAD

**Issue by brnguyenn** [mui/mui-x#11326]
### The problem in depth 🔍

The goal is to have the highlighted mark visually different as well as the ability for an onClick event. e.g:

<img width="213" alt="Screen Shot 2023-12-07 at 2 47 55 pm" src="https://github.com/mui/mui-x/assets/56327032/72548fcf-6cc7-4d9f-bf26-981e231aee53">

**Search keywords**: MarkElement, LineChart
**Order ID**: 79128

**Comment by michelengelen** [comment]
> > If I am not mistaken it needs to be a path component, though. This essentially can take an onClick prop.
> 
> What make you think it needs to be a `path`?

I thought it had to be a `path` due to this type definition: https://github.com/mui/mui-x/blob/029d4c106455d2b3f62816663f4f179445dd4aec/packages/x-charts/src/LineChart/MarkElement.tsx#L91-L102

But when it can be any valid `svg` element its even better. Thanks for pointing that out

**Comment by brnguyenn** [comment]
Thank you for your replies @michelengelen and @alexfauquette
