### ISSUE TITLE
[docs] Missing Dependencies in "Charts - Getting Started"

### ISSUE THREAD

**Issue by tmchilvers** [mui/mui-x#11338]
### Related page

https://mui.com/x/react-charts/

### Kind of issue

Missing information

### Issue description

Hi! 

I was setting up my application to use the new **MUI Charts** components, but ran into an issue during installation.

<br>

**Problem**:
> The steps to install this library, according to the docs, is simply: `yarn add @mui/x-charts`. However, if you launch a local instance of the application after completing this step you will be given the following response (for those using Yarn Plug'n'Play):
> 
> `The Yarn Plug'n'Play manifest forbids importing "@mui/utils" here because it's not listed as a dependency of this package:`
> 
> which will then cancel launching the local instance.
> 

<br>

**Solution**:

> The solution I found is to also add the missing dependencies: `yarn add @mui/utils`.
> 
> Please add to the **Getting Starting** page of the Charts documentation the list of missing dependencies to prevent future developers from any confusion.

<br>

Thank you!

### Context 🔦

I was wanting to test out the new MUI Charts library in my application and was following along the docs instructions for setting up the library in my code environment.

**Search keywords**: charts dependencies

**Comment by LukasTy** [comment]
> wouldn't it be sufficient if we add `@mui/utils` to the list of dependencies?

It seems that we are missing a whole doc section about the peer dependencies. 🙈 
Something similar to [what we have](https://mui.com/x/react-date-pickers/getting-started/) for the Pickers.
