### ISSUE TITLE
[DatePicker] Opening a DatePicker throws an error and month change icon doesn't work

### ISSUE THREAD

**Issue by eusouoviana** [mui/mui-x#11354]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Just added an example from documentation:

```typescript
// ...

<LocalizationProvider dateAdapter={AdapterDayjs}>
  <DatePicker
    format="DD/MM/YYYY"
  />
</LocalizationProvider>
```

### Current behavior 😯

Short video: https://www.loom.com/share/e0a66f569e014620921aa63fefb98596

### Expected behavior 🤔

No errors should be presented. Also, moving from one month to another via UI must work.

### Context 🔦

Simple Next.js project.

### Your environment 🌎

```plain
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (119.0.2151.97)
  npmPackages:
    @emotion/react: 11.10.6 => 11.10.6
    @emotion/styled: 11.10.6 => 11.10.6
    @mui/base:  5.0.0-beta.26
    @mui/core-downloads-tracker:  5.14.20
    @mui/icons-material: 5.11.9 => 5.11.9
    @mui/lab: ^5.0.0-alpha.117 => 5.0.0-alpha.134
    @mui/material: 5.14.20 => 5.14.20
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.5
    @mui/types:  7.2.10
    @mui/utils:  5.14.20
    @mui/x-date-pickers: ^6.18.3 => 6.18.3
    @types/react: 18.0.28 => 18.0.28
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @eusouoviana 
I cannot reproduce any errors when changing the icons with the ones from the [core package](https://mui.com/material-ui/material-icons/?query=arrow).
Here is a little [demo](https://codesandbox.io/p/sandbox/fast-https-fgnlzp?file=%2Fsrc%2FDemo.tsx%3A11%2C11) of how that works.
Did you maybe use icons from a different package?

**Comment by LukasTy** [comment]
@eusouoviana Could you provide a minimal reproduction example?
That would help us a lot! 🙏 
It could be an interesting edge case when combining some form management library... 🤷 
Without a reproduction example, we can not help you, because everything that can be seen seems correct. 🙈

**Comment by eusouoviana** [comment]
Hi @LukasTy and @michelengelen,  
  
Thank you for your response. I will take some minutes this afternoon to upload the project to Google Drive and send the link publicly. It's small stuff. 

I literally copied the same code I am running (that's causing errors according to the video I sent), but I'll send the full code soon, so it may help.

Thank you for your time.
I'll send it soon.
