### ISSUE TITLE
[charts] Line chart highlight mark customisation

### ISSUE THREAD

**Issue by brnguyenn** [mui/mui-x#11368]
### Summary 💡

The props.mark allows customisation of the MarkElement however, we would also like to be able to customise the highlighted mark. This is the goal:

https://github.com/mui/mui-x/assets/56327032/e4363a07-6dc1-4d84-9bd1-d037d1e00194

### Examples 🌈

https://recharts.org/en-US/api/Area#activeDot

### Motivation 🔦

We would like to add an onClick to the highlighted mark and have a larger click area for users. We do have data where marks are closer together so would like the default (non highlighted mark) smaller

**Search keywords**: MarkElement, LineChart
**Order ID**: 79128

**Comment by alexfauquette** [comment]
I don't see the difference with the question you asked in #11326

**Comment by brnguyenn** [comment]
> I don't see the difference with the question you asked in #11326

Hey @alexfauquette, thanks for your reply. The question is the same but only second half of it was answered. It's possible to customise the MarkElement with an SVG however I'm not able to make the customisation for when it's highlighted. There doesn't seem to be any **isHighlighted** state passed through or a separate slot for a highlighted MarkElement (recharts has their components `dot` and `activeDot` customisable)

**Comment by michelengelen** [comment]
Hey @brnguyenn ... maybe we haven't been clear enough with our answers in #11326 

Please correct me if i am wrong @alexfauquette 

There are 2 slots available to customize:
1. `slots.mark` which is used to render the standard mark
2. `slots.lineHighlight` which renders an element above the mark

You probably want to use the second slot then to customize the highlighted state.

**Comment by brnguyenn** [comment]
> Hey @brnguyenn ... maybe we haven't been clear enough with our answers in #11326
> 
> Please correct me if i am wrong @alexfauquette
> 
> There are 2 slots available to customize:
> 
> 1. `slots.mark` which is used to render the standard mark
> 2. `slots.lineHighlight` which renders an element above the mark
> 
> You probably want to use the second slot then to customize the highlighted state.

Hey @michelengelen, I did misinterpret the replies. Thanks for the clarification
