### ISSUE TITLE
[DataGrid] Filterpanel resets state after every fetch

### ISSUE THREAD

**Issue by niallmcelvogue** [mui/mui-x#11384]
### Steps to reproduce

I've been unable to reproduce this issue on codesandbox using the MUI fake server.
https://codesandbox.io/p/sandbox/server-side-filter-issue-4ncr37?file=%2Fsrc%2FDemo.js%3A14%2C1

It looks similar to https://github.com/mui/mui-x/issues/8119 and https://github.com/mui/mui-x/issues/9580

### Current behavior

https://github.com/mui/mui-x/assets/70704176/aa490be4-c21e-48dc-b94e-cb9ad1a09a7a

After every key press, the filter field and value are used in a function to build a url to send to our server. Upon rendering the result, the filter panel loses focus and it's value. 

### Expected behavior

Filter panel should stay in focus and retain filter value.

### Context

I'm using a custom data grid
```
`export const ServerSideDataGrid = ({
  columns,
  handleOnFilterChange,
  rowCount,
  paginationModel,
  handlePaginationChange,
  data,
  automaticRowHeight }) => (
    <div style={{ maxHeight: '800px', minHeight: '200px', width: '100%' }}>
      <StyledDataGrid
        disableRowSelectionOnClick
        filterMode="server"
        onFilterModelChange={handleOnFilterChange}
        getRowId={getRowId}
        columns={columns}
        disableExport
        disableColumnSelector
        disableDensitySelector
        sx={{
          '.MuiTablePagination-displayedRows, .MuiTablePagination-selectLabel': {
            'margin-top': '1em',
            'margin-bottom': '1em',
          },
        }}
        rowCount={rowCount}
        slots={{ columnMenu: CustomColumnMenu, toolbar: CustomToolbar }}
        slotProps={{
          noRowsOverlay: (
            <Stack height="100%" alignItems="center" justifyContent="center">
              No rows in DataGrid
            </Stack>
          ),
          noResultsOverlay: (
            <Stack height="100%" alignItems="center" justifyContent="center">
              Local filter returns no result
            </Stack>
          ),
          filterPanel: {
            filterFormProps: {
              columnInputProps: {
                variant: 'outlined',
                size: 'small',
                sx: { mt: 'auto' },
              },
              operatorInputProps: {
                variant: 'outlined',
                size: 'small',
                sx: { mt: 'auto' },
              },
              valueInputProps: {
                required: true,
              },
              deleteIconProps: {
                sx: {
                  '& .MuiSvgIcon-root': { color: '#d32f2f' },
                },
              },
            },
            sx: {
              '& .MuiDataGrid-filterForm': { p: 2 },
              '& .MuiDataGrid-filterForm:nth-child(even)': {
                backgroundColor: (theme) => (theme.palette.mode === 'dark' ? '#444' : '#f5f5f5'),
              },
              '& .MuiDataGrid-filterFormLinkOperatorInput': { mr: 2 },
              '& .MuiDataGrid-filterFormColumnInput': { mr: 2, width: 150 },
              '& .MuiDataGrid-filterFormOperatorInput': { mr: 2 },
              '& .MuiDataGrid-filterFormValueInput': { width: 200 },
            },
          },
        }}
        getRowHeight={() => determineRowHeight(automaticRowHeight)}
        pageSizeOptions={[10, 15, 25, 50]}
        paginationModel={paginationModel}
        paginationMode="server"
        onPaginationModelChange={handlePaginationChange}
        rows={data}
      />
    </div>
);`
```

The component is then used like so 
```
`        <ServerSideDataGrid
          columns={columns}
          handleOnFilterChange={onFilterChange}
          rowCount={jobsCount}
          paginationModel={paginationModel}
          handlePaginationChange={handlePaginationChange}
          data={jobs}
        />`
```

```
The onFilterChange calls the fetch request function 
` const onFilterChange = React.useCallback((filterModelParams) => {
      // Here you save the data you need from the filter model
      if (filterModelParams.items[0]?.value) {
        loadJobs(paginationModel.page, paginationModel.pageSize,
          filterModelParams.items[0].field, filterModelParams.items[0].value);
      }
      setFilterModel(filterModelParams);
    }, []);`
```
    
The fetch URL is determined from the filter field and value.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.71
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.23
    @mui/core-downloads-tracker:  5.14.17
    @mui/material: ^5.14.17 => 5.14.17
    @mui/private-theming:  5.14.17
    @mui/styled-engine:  5.14.17
    @mui/system:  5.14.17
    @mui/types:  7.2.8
    @mui/utils:  5.14.17
    @mui/x-data-grid: ^6.18.1 => 6.18.1
    @types/react:  17.0.11
    react: ^16.8.6 => 16.14.0
    react-dom: ^16.8.6 => 16.14.0
    styled-components: ^6.1.1 => 6.1.1

```
</details>

**Search keywords**: FilterPanel focus lost

**Comment by michelengelen** [comment]
Hey @MBilalShafi ... could you help out here? 

From what I can see and by looking at the provided code it does seem like the datagrid might rerender in its entirety on every change to the `filterModel`. This would explain why the filterpanel disappears and has no value after the render.

@niallmcelvogue you are using the datagrid as a server side component, right? I am almost 100% sure that this is not possible, since it uses client state (reference for this is [this comment](https://github.com/mui/mui-x/issues/7599#issuecomment-1387483040) on a related issue). Did you try using it as a client component instead?

**Comment by niallmcelvogue** [comment]
@michelengelen Hi Michel, I'm not using the datagrid as a server side component. Apologies if the name is confusing, I do have a ClientSideDataGrid, but the only difference is I am using pagination on the server side component.

**Comment by niallmcelvogue** [comment]
@michelengelen Hi, I'm not using server side rendering for the datagrid. Apologies if the name is confusing, I have two datagrids, one for server side pagination and one for client side. But neither are using SSR

**Comment by michelengelen** [comment]
@niallmcelvogue from what I can see (as it is not behaving the same in the sandbox and therefor I cannot test it) the problem seems to be that the `ServerSideDataGrid` component does rerender every time the filter gets updated. This is a wild guess though without solid proof.

@MBilalShafi do you have any idea here?

**Comment by MBilalShafi** [comment]
Yeah I suspect the same i.e the data grid is re-rendering to the extent that it resets the `preferencesPanel` state and the filter panel gets reset. But we can not say this for sure unless we have a live reproduction.

@niallmcelvogue It'll be really helpful if you could provide a minimal reproduction example using codesandbox. It'll be really helpful to get to the root of the problem.

Thanks

**Comment by niallmcelvogue** [comment]
@MBilalShafi @michelengelen Thanks for the feedback. I tried to recreate the issue as close as possible here https://codesandbox.io/p/devbox/4ncr37?file=%2Fclient%2Fsrc%2FServerSideDataGrid.js%3A110%2C9 and it works fine. So I'll close this issue as it must be a problem with my implementation
