### ISSUE TITLE
[DateTimePicker] closeOnSelect={true} not working properly

### ISSUE THREAD

**Issue by slutske22** [mui/mui-x#11390]
### Steps to reproduce

Link to live example: [DesktopDateTimePicker](https://mui.com/x/react-date-pickers/date-time-picker/#basic-usage)

Steps:
1. Click the calendar icon to open the calendar day picker
2. Click days several times
3. the calendar will not close on select / on change the first time, you must click several times to make it close

This issue can be seen literally in the [DateTimePicker MUI Docs, basic usage example](https://mui.com/x/react-date-pickers/date-time-picker/#basic-usage).  See the gif below.

### Current behavior

The calendar popover does _not_ close when the user clicks on a day.  Docs state that `closeOnSelect={true}` is default behavior for the `DesktopDateTimePicker`, but with this prop omitted, or deliberately set to `true`, it still does not close on a day click.  See gif:

![Dec-12-2023 08-09-25](https://github.com/mui/mui-x/assets/52637023/f64135d1-3972-4d02-9c7f-ecd145c6c11c)

In the official docs example, the calendar only closes on the 4th click.  In my personal codebase, it only closes on the 2nd click (using @mui/material 5.14.18 and @mui/x-date-pickers 6.18.2)

### Expected behavior

I would expect the calendar popover to close when the user clicks on a day, the very first time they click on one.  I have delibately set `closeOnSelect={true}`, with no change.  I have tried variations of `closeOnSelect` with `onAccept` and `onChange`, with no positive results.

### Context

User should be able to open the calendar picker, click on the desired day, and have the popover automatically close and update the value

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: Not Found
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 119.0.6045.199
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.24 
    @mui/core-downloads-tracker:  5.14.18 
    @mui/icons-material: ^5.14.18 => 5.14.18 
    @mui/material: ^5.14.18 => 5.14.18 
    @mui/private-theming: ^5.14.18 => 5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/styles: ^5.14.18 => 5.14.18 
    @mui/system:  5.14.18 
    @mui/types: ^7.2.9 => 7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-date-pickers: ^6.18.2 => 6.18.2 
    @types/react: ^18.2.39 => 18.2.39 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.3.2 => 5.3.2 
```
</details>

**Search keywords**: datetimepicker, desktopdatetimepicker, dates

**Comment by LukasTy** [comment]
Hello and thank you for reporting this problem! 🙏 
It's an issue that we need to fix. 💯
