### ISSUE TITLE
[DataGrid] Get which row is in edit mode using the API?

### ISSUE THREAD

**Issue by DoubleDebug** [mui/mui-x#11408]
### The problem in depth 🔍

My data grid component looks something like this:
```jsx
<DataGridPro
   apiRef={apiRef}
   columns={columns}
   rows={rows}
   editMode="row"
/>
```

Using the apiRef, I want to find out which row is currently being edited.
I know this can be achieved using the `onRowEditStart` and `onRowEditStop` props, but I want to do it using the API.

Is this possible?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD   
  Browsers:
    Chrome: Not Found
    Edge: Chromium (120.0.2210.61)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base: ^5.0.0-beta.24 => 5.0.0-beta.24
    @mui/core-downloads-tracker:  5.14.18
    @mui/lab: ^5.0.0-alpha.153 => 5.0.0-alpha.153
    @mui/material: ^5.14.18 => 5.14.18
    @mui/private-theming:  5.14.18
    @mui/styled-engine:  5.14.18
    @mui/system: ^5.14.18 => 5.14.18
    @mui/types:  7.2.9
    @mui/utils:  5.14.18
    @mui/x-data-grid:  6.18.2
    @mui/x-data-grid-pro: ^6.18.2 => 6.18.2
    @mui/x-date-pickers:  6.18.2
    @mui/x-date-pickers-pro: ^6.18.2 => 6.18.2
    @mui/x-license-pro:  6.10.2
    @types/react: 18.2.38 => 18.2.38
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.2.2
```
</details>

**Search keywords**: datagrid row edit api
**Order ID**: 11111

**Comment by michelengelen** [comment]
Hey @DoubleDebug ... yes, that is possible, BUT the `onRowEditStart` and `onRowEditStop` handlers are there for a reason.

You basically have 2 options:
1. listen on state changes in `onStateChange` (again a event handler). This will run quite a lot though, so be careful with that: [demo](https://codesandbox.io/p/sandbox/dazzling-hooks-93xnqr?file=%2Fsrc%2FDemo.tsx%3A1%2C1-87%2C1)
2. Check the state with the `apiRef`. You can grab the `editRows` state object from the `apiRef`. `apiRef.state.editRows` will hold the data you are looking for. This is well should be handled carefully, since state updates quite frequently

**Comment by DoubleDebug** [comment]
@michelengelen Thanks for the quick reply!

This helps a lot. For anyone else dealing with the same problem, the `editRows` parameter is an object where the keys are row IDs that are currently being edited. For example:
```ts
const { editRows } = apiRef.current.state;
console.log(editRows);
// Output:
// {
//     "row-1": { ... }
//     "row-2": { ... }
// }
```
In this case, there are 2 rows which are currently being edited - rows 1 and 2.
However, it would be nice if the API had a function that returns this information. For example:
```ts
const rowModesModel = apiRef.current.getRowModesModel();
const editingRowIds = rowModesModel
                      .filter((row) => row.mode === GridRowModes.Edit)
                      .map((row) => row.id);
console.log(editingRowIds);
// Output:
// ['row-1', 'row-2']
```

**Comment by michelengelen** [comment]
Great to see that I could help you.
I will close this issue now. Feel free to reopen if we ca help you with something else on this matter!
