### ISSUE TITLE
Inconsistent Tooltips on `GridToolbarColumnsButton`, `GridToolbarFilterButton`,`GridToolbarDensitySelector`,`GridToolbarExport`

### ISSUE THREAD

**Issue by sterlingdcs-damian** [mui/mui-x#11413]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to https://mui.com/x/react-data-grid/components/#toolbar
2. Hover over columns , filters, denisty and export
3. Filters has a show filters tooltip position at the bottom, the others have no tooltips
![image](https://github.com/mui/mui-x/assets/140072768/0686295a-99f8-440d-babd-ad266f0083df)

### Current behavior

Inconsistent use of MUI Datagrid toolbar butotn tooltips

### Expected behavior

They either all have tooltips or none

### Context

I'll have to wrap the other 3 buttons with tooltips to achieve consistency

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: Not Found
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.24 
    @mui/core-downloads-tracker:  5.14.18 
    @mui/icons-material: 5.14.9 => 5.14.9 
    @mui/lab: 5.0.0-alpha.144 => 5.0.0-alpha.144 
    @mui/material: 5.14.10 => 5.14.10 
    @mui/private-theming:  5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/styles: 5.14.10 => 5.14.10 
    @mui/system: 5.14.9 => 5.14.9 
    @mui/types:  7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-premium: 6.18.1 => 6.18.1 
    @mui/x-data-grid-pro:  6.18.1 
    @mui/x-license-pro: 6.10.2 => 6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react: 17.0.2 => 17.0.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.4.3 => 4.4.3 

</details>

**Search keywords**: DataGrid toolbar buttons

**Comment by DanailH** [comment]
@sterlingdcs-damian thanks for reporting this. It's more or less a UX issue. The reason why the tooltip is there only for the `Filters` button is because when you have active filters the tooltip shows additional information regarding them (so that you don't have to open the filter panel to see what the active filters are). The other buttons don't have the need for that functionality.

**Comment by MBilalShafi** [comment]
We also had a related [issue](https://github.com/mui/mui-x/issues/10409) previously reported too, so we decided to wrap all the buttons in the Tooltip, the [PR](https://github.com/mui/mui-x/pull/11357) is already in review so this should be made consistent in v7.
