### ISSUE TITLE
[question] Is it possible to hide the button text for the MUI datagrid toolbar buttons (toolbarDensity, toolbarColumns, toolbarFilters, toolbarExport)

### ISSUE THREAD

**Issue by sterlingdcs-damian** [mui/mui-x#11416]
### Order ID or Support key 💳

73340
### Search keywords

DataGrid toolbar button `showButtonText` prop

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Our designer has requested that we show only the icons of these buttons `GridToolbarColumnsButton`, `GridToolbarFilterButton`, `GridToolbarDensitySelector` + `GridToolbarExport`

I've found a hacky workaround by passing this prop to the grid:
` localeText={{ toolbarDensity: '', toolbarColumns: '', toolbarFilters: '', toolbarExport: '' }}`
It would involve additional styling hacks to reduce the button width however.
         

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
All browsers
 System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: Not Found
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.24 
    @mui/core-downloads-tracker:  5.14.18 
    @mui/icons-material: 5.14.9 => 5.14.9 
    @mui/lab: 5.0.0-alpha.144 => 5.0.0-alpha.144 
    @mui/material: 5.14.10 => 5.14.10 
    @mui/private-theming:  5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/styles: 5.14.10 => 5.14.10 
    @mui/system: 5.14.9 => 5.14.9 
    @mui/types:  7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-premium: 6.18.1 => 6.18.1 
    @mui/x-data-grid-pro:  6.18.1 
    @mui/x-license-pro: 6.10.2 => 6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react: 17.0.2 => 17.0.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.4.3 => 4.4.3 

```
</details>

**Comment by DanailH** [comment]
Hi @sterlingdcs-damian the way to approach this is to construct your own toolbar (we export the root component) by only adding the buttons you want (all buttons are exported components as well).
You can find more about this here: https://mui.com/x/react-data-grid/components/#toolbar

**Comment by damiangreen** [comment]
I've actually done that. But that doesn't address the original question unfortunately.

**Comment by ak-mid** [comment]
Another ugly workaround via CSS

`
 <GridToolbarColumnsButton 
    slotProps={{
        button: {
            sx: {fontSize: 0, minWidth: '40px', '& span': { marginRight: 0 }}
        } 
    }} 
  />
`

I went with that one because I need to hide the button text dynamically and using `localeText` just doesn't seem right.
Of course using just CSS has accessibility issues so I would also prefer a `showButtonText` prop or whatever.

**Comment by aress31** [comment]
+1 for this feature, a `variant` prop should be added to choose either between `icon + text`, `text` or just `icon`.
