### ISSUE TITLE
[pickers] Support additional `endAdornment` on `<DatePicker />`

### ISSUE THREAD

**Issue by rgavrilov** [mui/mui-x#11425]
### The problem in depth 🔍

I want to add an error icon to a date picker, if I provide adornment for a text field slot - it removes "calendar" icon. How can I add an adornment without dropping the OOB one?

```
                <DatePicker<Date>
                    sx={{ width: '350px' }}
                    shouldDisableDate={shouldDisableDate}
                    disableOpenPicker={false}
                    onAccept={saveAnswerIfValid}
                    onChange={handleDateChange}
                    value={inputValue}
                    slotProps={{
                        textField: {
                            variant: 'standard',
                            InputProps: {
                                onBlur: () => {
                                    saveAnswerIfValid(inputValue);
                                },
                                endAdornment: validationError ? (
                                    <Tooltip title={validationError}>
                                        <InfoIcon color="error" />
                                    </Tooltip>
                                ) : undefined,
                            },
                        },
                    }}
                    minDate={minDate}
                    maxDate={maxDate}
                    views={resolutionViews[resolution]}
                />
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datepicker
**Order ID**: 52426

**Comment by michelengelen** [comment]
Hi @rgavrilov ... thanks for raising this. It is indeed not possible at the moment to achieve what you are trying to do. I'll let @LukasTy and @noraleonte have a look and see if we can include this into the next major version.

**Comment by noraleonte** [comment]
Hey! 👋 
Right now the pickers only support the `OpenPickerButton` as an `endAdornment`. I think for the simple pickers it should be doable by changing the `useDesktopPicker` to not only add the `OpenPickerButton` as an adornment, but also any other adornments passed for the same position 🤔 

Something like this (lightly speaking, checks are still needed):
```diff
- ...fieldProps.InputProps,
- ref: containerRef,
- [`${inputAdornmentProps.position}Adornment`]: (
-    <InputAdornment {...inputAdornmentProps}>
-       <OpenPickerButton {...openPickerButtonProps}>
-          <OpenPickerIcon {...innerSlotProps?.openPickerIcon} />
-       </OpenPickerButton>
-    </InputAdornment>
- ),
+ ...fieldProps.InputProps,
+ ref: containerRef,
+ [`${inputAdornmentProps.position}Adornment`]: (
+    <InputAdornment {...inputAdornmentProps}>
+       <OpenPickerButton {...openPickerButtonProps}>
+          <OpenPickerIcon {...innerSlotProps?.openPickerIcon} />
+       </OpenPickerButton>
+       {fieldProps.InputProps[`${inputAdornmentProps.position}Adornment`]} // with checks 
+    </InputAdornment>
+ ),
```

The only downside I see is that if the users pass an adornment like: `<InputAdornment>...</InputAdornment>` as an InputProp, the resulted DOM structure will be incorrect, having nested `InputAdornments` 🤔 🙈

**Comment by LukasTy** [comment]
Reopening this and putting it up for grooming as it doesn't seem that we needed any confirmation from the. 🤔

**Comment by flaviendelangle** [comment]
We decided to create a doc examples on how to do it correctly with the tools we currently provide, and then improve those tools if needs by
