### ISSUE TITLE
[DatePicker] `minDate` in DatePicker props enabling dates earlier than specified

### ISSUE THREAD

**Issue by imparvez** [mui/mui-x#11443]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/sweet-kapitsa-kxkd2v?file=%2Fsrc%2FDemo.tsx%3A23%2C7

Steps:
1. Implemented DatePicker and provide value and minDate props.
2. Setting the value as 6th June, 2023 and minDate as 5th June 2023, 
3. UTC is configured as preferred timezone.

### Current behavior

After passing the value and minDate props, ideally it should not enable any dates other than minDate but as per given example, it is enabling one date prior to minDate.
For eg:
value: 6th June, 2023
minDate: 5th June, 2023

4th June 2023 is also enabled

### Expected behavior

No other day prior to minDate should be enabled.
Works fine with normal timezone
https://codesandbox.io/p/sandbox/strange-saha-f679y2?file=%2Fsrc%2FDemo.tsx%3A11%2C47

**Search keywords**: minDate

**Comment by michelengelen** [comment]
Great that I could help you. I'll close this issue now.
Feel free to reopen if you have questions regarding this. Thanks! 🙇🏼

**Comment by imparvez** [comment]
@flaviendelangle but I think when working with UTC time standard, v6 date picker doesn't behave what it should be and for that reason @michelengelen has suggested to use `new Date(Date.UTC())`. Correct me if I'm wrong? Thanks

**Comment by LukasTy** [comment]
@imparvez I think that @flaviendelangle suggested avoiding the extra headache of re-creating date objects of different types if there is no need for that.
Consider just passing a string of the date to the `dayjs.utc` function in turn avoiding the intermediate `Date` object usage.

```diff
- dayjs.utc(new Date(Date.UTC(2022,3,17)));
+ dayjs.utc('2022-04-17');
```
