### ISSUE TITLE
[DataGrid] Pinning group by column with leafField results in incorrect behaviour

### ISSUE THREAD

**Issue by kavitang** [mui/mui-x#11458]
### Steps to reproduce

Link to live example: (required)
[https://react-2xihdm.stackblitz.io](https://react-2xihdm.stackblitz.io)
Editable URL -
[https://stackblitz.com/edit/react-2xihdm?file=Demo.tsx](https://stackblitz.com/edit/react-2xihdm?file=Demo.tsx)

Steps:
1. The grouping model is set in an effect (in our app this is done after data is fetched so cannot be initial state)
2. When grouping model is set we also want to pin the group by column

### Current behavior

1. Currently the Header of the column is incorrect, it should be the header of the leafField. It shows the group by column header instead.
2. Pinning the column results in duplicate columns with the group by column being repeated. This is resolved by pinning the `__row_group_by_columns_group_<col_field>` instead, but this seems like a bandaid and is not available in the docs.

### Expected behavior

1. It should show the header of the leafField in the pinned column
2. There should be no duplicate columns when pinning the group by column

### Context

We want to display values in the grouped column correctly and pin this. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Edge: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-beta.26
    @mui/core-downloads-tracker:  5.14.20
    @mui/material: ^5.14.20 => 5.14.20
    @mui/private-theming:  5.14.20
    @mui/styled-engine:  5.14.20
    @mui/system:  5.14.20
    @mui/types:  7.2.10
    @mui/utils:  5.14.20
    @mui/x-data-grid:  6.18.4
    @mui/x-data-grid-premium: ^6.18.4 => 6.18.4
    @mui/x-data-grid-pro:  6.18.4
    @mui/x-license-pro:  6.10.2
    @types/react: 18.2.8 => 18.2.8
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components:  5.3.6
    typescript: ^5.1.6 => 5.1.6
```
</details>

**Search keywords**: datagrid grouping and pinning
**Order ID**: 55516

**Comment by michelengelen** [comment]
Hey @kavitang ... sry for answering so late, but I had to reassure myself with the following:

This issue is loosely related to #11340 as you need to target the grouped column with `'__row_group_by_columns_group__'` instead of the name from the column definition.

Your updated `useEffect` should now look like this:

```tsx
const handleGroupingModelChange = React.useCallback((model: GridRowGroupingModel) => {
  setRowGroupingModel(model);
  if (model?.length) {
    setPinnedCols({
      left: ['__row_group_by_columns_group__'],
    });
  }
}, []);
```

I would propose a slight refactor though:

```tsx
const handleGroupingModelChange = React.useCallback((model: GridRowGroupingModel) => {
  setRowGroupingModel(model);
  setPinnedCols({
    left: model?.length ? ['__row_group_by_columns_group__'] : [],
  });
}, []);
```

For your second point you are using `mainGroupingCriteria` in your function for `groupingColDef`. This overrides the grouped column title.

https://github.com/mui/mui-x/blob/5a861e86f6def7f2321c4428f9b5dcc241245924/packages/grid/x-data-grid-pro/src/models/gridGroupingColDefOverride.ts#L14-L20

To fix this just change the returned value, or just use a memoized value (since we don't need the `params` anymore):

```tsx
const groupingColDefOverride = React.useMemo(
  () =>
    rowGroupingModel?.length
      ? {
          leafField: 'title',
          hideDescendantCount: true,
        }
      : {},
  [rowGroupingModel],
);
```

I did update your live example with these changes [here](https://stackblitz.com/edit/react-2xihdm-quhew3?file=Demo.tsx).

Is this what you were looking for?

**Comment by kavitang** [comment]
@michelengelen - Thank you! 

I think this should resolve it, but I would like to test this out with our app as we have multiple grouping columns enabled and I would like to try these settings with that. I will post back with an update later today with either any questions I may have or close this issue as completed.

**Comment by michelengelen** [comment]
Great ... let me know how it went for you.
Additionally we could maybe do a recipe for this.
I'll wait for your response first though. 👍🏼

**Comment by kavitang** [comment]
That seems to have resolved the issue! A recipe for this would be extremely helpful as the use of `'__row_group_by_columns_group__'` is difficult to locate otherwise.

Marking the issue as completed. Thank you!
