### ISSUE TITLE
[DataGrid] Is there a way to open DataGrid in full screen mode?

### ISSUE THREAD

**Issue by MaksymZup** [mui/mui-x#11455]
### The problem in depth 🔍

Is there somehow easy implementation of full screen Datagrid view with pressing one button and with do not need creating this functionality by myself?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid full screen

**Comment by michelengelen** [comment]
Hey @MaksymZup with `FullScreen`, do you mean like fullscreen video? Or just full screen inside the browsers viewport?

**Comment by MaksymZup** [comment]
@michelengelen like fullscreen video

**Comment by MaksymZup** [comment]
@michelengelen just full screen inside the browsers viewport

**Comment by michelengelen** [comment]
There is no OOB feature that does that, but IMO this would actually be really nice.
It would be great as a standalone feature or, if not feasible, as a recipe. I'll let the team decide on that.

@joserodolfofreitas WDYT?

**Comment by joserodolfofreitas** [comment]
It's an interesting use case; a customization example (perhaps using a toolbar button) would be the best to help with this pain point in the short term.

**Comment by michelengelen** [comment]
Hey @MaksymZup I took the time to build a sample [DataGrid with Full-Screen support](https://codesandbox.io/p/sandbox/relaxed-voice-lfjrfs?file=%2Fsrc%2FDemo.tsx%3A53%2C11). 

This is based on a [custom toolbar](https://mui.com/x/react-data-grid/export/#custom-toolbar), the material-ui [Modal component](https://mui.com/material-ui/react-modal/) and the `apiRef.current.exportState()` method (example usage [here](https://mui.com/x/react-data-grid/state/#restore-the-state-with-apiref)).

Please let me know if this is what you are looking for.

Thanks! 🙇🏼

**Comment by michelengelen** [comment]
@dkacper you would need to export the state again on closing the modal and updating the `main` grid with it. That shouldn't be a problem.

The idea with the portal would be good as well. That way you would not have a need of passing the state around
