### ISSUE TITLE
[DataGrid] capture `onKeyDown` for the filters and header filters

### ISSUE THREAD

**Issue by Myloc-KJN** [mui/mui-x#11456]
### The problem in depth 🔍

I'm using DataGridPremium with both normal filters and header filters (unstable_headerFilters). I'm using server-side data where I capture filter changes in the datagrid with onFilterModelChange, triggering API requests to my BE. The problem is that I have large amount of data and the BE can be slow.

To mitigate excessive backend requests, I aim to implement a scenario where user input filter values and then press the 'Enter' key while the filter is selected/highlighted. This 'Enter' key press should trigger the backend request.

I couldn't find any documentation explaining how to capture the onKeyDown event in my filters, nor any discussions on this issue. I'm exploring potential solutions and wondering if you're aware of any effective methods?

My initial thoughts, although uncertain if they will work, involve overriding the filter component and incorporating my own onKeyDown event there. Another consideration is implementing a global event listener. However, both solutions might pose challenges in integrating them seamlessly with the rest of the datagrid. I'd greatly appreciate it if you have alternative solutions or suggestions to address this issue

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 14.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 120.0.6099.110
    Edge: Chromium (120.0.2210.77)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.26
    @mui/core-downloads-tracker:  5.14.20
    @mui/icons-material: ^5.13.7 => 5.13.7
    @mui/lab: ^5.0.0-alpha.153 => 5.0.0-alpha.153
    @mui/material: ^5.14.20 => 5.14.20
    @mui/private-theming:  5.14.20
    @mui/styled-engine:  5.14.20
    @mui/system:  5.14.20
    @mui/types:  7.2.10
    @mui/utils:  5.14.20
    @mui/x-data-grid-premium: ^6.17.0 => 6.18.1
    @mui/x-date-pickers: ^6.18.3 => 6.18.3
    @types/react: ^17.0.39 => 17.0.39
    react: ^17.0.1 => 17.0.2
    react-dom: ^17.0.1 => 17.0.2
    typescript: ^4.6.3 => 4.6.3
```
</details>

**Search keywords**: datagrid filter onKeyDown
**Order ID**: 78662

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/p/sandbox/wonderful-robinson-vd552t) _may_ be a good starting point. You can find more templates [in our docs](https://mui.com/x/react-data-grid/).

Thank you! 🙇🏼

**Comment by Myloc-KJN** [comment]
Hi @michelengelen, I'm looking for suggestions or guidance on implementing the onKeyDown functionality for filters and header filters within Material-UI's DataGridPremium. Do you have any thoughts on how this can be achieved?

**Comment by michelengelen** [comment]
I am not sure if this is possible.
@MBilalShafi could you help out here?

**Comment by michelengelen** [comment]
Hey @Myloc-KJN there is one way to do what you are trying to achieve: Render custom components for the filtering inputs.

We do have a section on [custom header filter components](https://mui.com/x/react-data-grid/filtering/header-filters/#customize-header-filters), [custom filter input](https://mui.com/x/react-data-grid/filtering/customization/#custom-input-component) and [custom filter panel](https://mui.com/x/react-data-grid/filtering/customization/#custom-filter-panel) with examples. 

With this you can easily catch key events on your own.

Would this be sufficient for your use case?

**Comment by Myloc-KJN** [comment]
Hey @michelengelen thanks for the answer. The answer is sufficient, this was one of the routes I planned to go but thought maybe there is a better way sense I want all the standar components but just want to catch the keyDown.

**Comment by michelengelen** [comment]
In that case I will close this issue for now ... happy I could help! 
If you have more questions feel free to reopen or open another issue.
Thanks 🙇🏼
