### ISSUE TITLE
`hasEval` detection leads to CSP warnings and reports

### ISSUE THREAD

**Issue by tux21b** [mui/mui-x#11465]
### Steps to reproduce

1. Setup Content-Security-Policy that does not allow `'unsafe-eval'` (like `Content-Security-Policy: script-src 'self'`)
2. Visit a site that imports "@mui/x-data-grid"

### Current behavior

The `hasEval` detection added in https://github.com/mui/mui-x/issues/10056 is always automatically executed, even if the undocumented option `disableEval` is used. The `hasEval` detection runs an obfuscated version of `eval("true")` which gets blocked. This leads to CSP warnings in the browser, which are also reported via `Report-To`.

### Expected behavior

I would prefer if `eval()` isn't used at all, but if that's not an option, then it should not be used if `disableEval` is set to true. Doing the computation of `hasEval` lazily (and only if `disableEval` is not set) would solve the problem.

### Context

I'm trying to use the datagrid component in a secure way. Having Content-Security-Policy headers is highly recommended and disallowing arbitrary `eval()`s is the whole point of CSP. Having a report endpoint to catch possible security breaches (and errors within dev) is also recommended and having to continuously filter out false reports because of `eval("true")` within mui-x is really annoying and might hide more serious attacks or bugs.

**Search keywords**: datagrid csp eval

**Comment by oliviertassinari** [comment]
Does this connect back to https://github.com/mui/mui-x/pull/10329#discussion_r1327233747?

**Comment by tux21b** [comment]
> Does this connect back to [#10329 (comment)](https://github.com/mui/mui-x/pull/10329#discussion_r1327233747)?

I don't think so. The Content-Security-Policy doesn't mind if the eval is obfuscated via atob or if it was executed in a global scope or if it was re-assigned to another variable. It just forbids the usage of eval (unless `'unsafe-eval'` is explicitly set).

**Comment by romgrk** [comment]
Sounds good, we can evaluate `hasEval` lazily, so if `disableEval` is used it will never be evaluated.

**Comment by flaviendelangle** [comment]
> even if the undocumented option disableEval is used

Not directly the topic here but this prop is probably worth documenting since we had several feedbacks of people wanting to use it.
Having a clean doc section to link would make the process smoother

**Comment by reihwald** [comment]
I have the same issue as @tux21b and implemented a fix in #11516

**Comment by oliviertassinari** [comment]
> I don't think so. The Content-Security-Policy doesn't mind if the eval is obfuscated via atob or if it was executed in a global scope or if it was re-assigned to another variable. It just forbids the usage of eval (unless 'unsafe-eval' is explicitly set).

@tux21b Ah right, without `'unsafe-eval'` both eval and Function are blocked: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions.
