### ISSUE TITLE
[pickers] Is it possible to use pickers in .ASP net website .aspx pages?

### ISSUE THREAD

**Issue by deepaknsp11** [mui/mui-x#11460]
### The problem in depth 🔍

.ASP net website .aspx page support is possible? wanted to integrate date and time picker in .aspx web pages. Is it possible to install and integrate?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

.ASP net website .aspx page support is possible? wanted to integrate date and time picker in .aspx web pages. Is it possible to install and integrate?
</details>

**Search keywords**: .ASP net website .aspx page support is possible
**Order ID**: #15041

**Comment by michelengelen** [comment]
Hey @deepaknsp11 as long as your app/page can run react it can also use the components from MUI (Core and X). I do not have enough experience with ASP projects, so I would advice you to ask this on stackoverflow. The community there might be of more help to you in that regard!
