### ISSUE TITLE
I have the following order, when will I be able to download my license key?

### ISSUE THREAD

**Issue by mf-masashi-mori** [mui/mui-x#11485]
### The problem in depth 🔍

I have the following order, when will I be able to download my license key?
And how can I start using the product?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: license key
**Order ID**: 80794

**Comment by TinaDein** [comment]
Hi Masashi, we've fixed it - please check your inbox for the license key details. Have a great day!
