### ISSUE TITLE
[DateTimePicker] PickerField shows `0NaN` for year portion of formatted input field value when using Eastern Arabic numerals

### ISSUE THREAD

**Issue by nikkorn** [mui/mui-x#11488]
### Steps to reproduce

Steps:
1. Go to https://codesandbox.io/p/sandbox/infallible-wiles-3lggh6
2. Note that the DateTimePicker control input has a value of ٢١-'١٢-0NaN ١٢:١٣:٢١' when we expect a value of  '٢١-١٢-٢٠٢٣ ١٢:١٣:٢١'

### Current behavior

The formatted year portion of the DateTimePicker control input value is  '0NaN'

### Expected behavior

I definitely wouldn't have expected to see 0NaN in the input, I would have expected it to match the result of calling the following when the moment locale is "ar" which results in (what I hope) is the correctly formatted value using Eastern Arabic numerals.: 

moment("2023-12-21T12:13:21").format("HH:mm:ss DD-MM-YYYY") 

### Context

We are using the DateTimePicker extensively throughout our product and have recently added language support for ar-AE and this is causing issues.

### Your environment

"@emotion/react": "latest",
    "@emotion/styled": "latest",
    "@mui/material": "latest",
    "@mui/x-date-pickers": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "dayjs": "latest",
    "react": "latest",
    "react-dom": "latest",
    "typescript": "latest",
    "moment": "^2.29.4"

**Search keywords**: datetimepicker nan year arabic

**Comment by michelengelen** [comment]
@LukasTy I can confirm the bug.

The thing is, that the year is misinterpreted and the field tries to put it into the right position. which is wrong as well, since arabic is an RTL language.

**Comment by LukasTy** [comment]
Hello @nikkorn.
Could you confirm if you intend to use the Gregorian calendar and only need the Arabic localization? 🤔 
Because if you need a Hijri calendar, then it's a different topic, because [`moment-hijri` support](https://mui.com/x/react-date-pickers/calendar-systems/#hijri) is lacking for proper functionality of field components. 🙈

**Comment by nikkorn** [comment]
Hello @LukasTy 

Yes we intend to use the Gregorian calendar but our product supports a wide range of locales and will need to handle western and eastern Arabic numerals.

I have applied a value for `adapterLocale` but it doesn't resolve the issue.

Thanks

**Comment by LukasTy** [comment]
Thank you for confirming your situation. 🙏 
We'll discuss possible solutions and the best course of action. 👍
