### ISSUE TITLE
Can't close (delete) Data Grid column filter if type = 'singleSelect', operator = 'is any of'

### ISSUE THREAD

**Issue by magicxor** [mui/mui-x#11513]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/ecstatic-elion-7ckksh

Steps:
1. Open filters of the Country column
2. Set Operator = "is any of"
3. Click "X" (close button)

![image](https://github.com/mui/mui-x/assets/8275793/0a1ed52c-fe90-4d5e-bb7f-f4256df683f4)

### Current behavior

Filter panel doesn't close

### Expected behavior

Filter panel closes

### Context

I am trying to create an admin panel with basic functionality.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (120.0.2210.91)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.25
    @mui/core-downloads-tracker:  5.14.19
    @mui/icons-material: ^5.14.19 => 5.14.19
    @mui/lab: ^5.0.0-alpha.154 => 5.0.0-alpha.154
    @mui/material: ^5.14.19 => 5.14.19
    @mui/private-theming:  5.14.19
    @mui/styled-engine:  5.14.19
    @mui/system:  5.14.19
    @mui/types:  7.2.10
    @mui/utils:  5.14.19
    @mui/x-data-grid: ^6.18.2 => 6.18.2
    @types/react: ^18.2.39 => 18.2.39
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.3.2 => 5.3.2

```
</details>

**Search keywords**: datagrid singleSelect column filter can't be closed

**Comment by DanailH** [comment]
@magicxor the `X` button is not to close the panel but to remove/delete an active filter. Since you haven't set any filter you can't remove it. To close the pannel itself you can click outside of it.

**Comment by magicxor** [comment]
Hi @DanailH 

Thanks for the quick reply! However, I've noticed an inconsistency with the "X" button behavior. For 'string' columns with the "is any of" operator, the "X" closes the panel, but it doesn't for 'singleSelect'. I'm attaching a few videos to show this difference. I think ensuring consistent behavior across all filters would improve the user experience. Looking forward to your thoughts!

![name_is_any_of](https://github.com/mui/mui-x/assets/8275793/6918f86f-e95f-4e95-8798-584ac3d70910)
![bug_country_is_any_of](https://github.com/mui/mui-x/assets/8275793/588c8392-0de9-4145-ad16-94c73f51bfd1)
![country_is](https://github.com/mui/mui-x/assets/8275793/e72b466d-302c-4bfe-bdb4-daa82a703ca4)
![country_is_not](https://github.com/mui/mui-x/assets/8275793/efb248b3-a9e8-4645-8a35-c9b25e48af28)
