### ISSUE TITLE
[data grid] Input type number lets type non number.

### ISSUE THREAD

**Issue by FreakDroid** [mui/mui-x#11524]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/suspicious-torvalds-kjsq42?file=%2Fsrc%2FDemo.tsx

Steps:
1.  Open on Chrome the sample above
2. Click on three dots to open the filter panel. 
3. Select salary in the columns and try to type letters and it is not typing
4. Open on Safari or Firefox the sample above
5. Click on three dots to open the filter panel. 
6. Select salary in the columns and try to type letters and it is accepting letters

### Current behavior

In the filter panel when you have an input type number, it lets you type letters on Safari or Firefox. For MS Edge and Chrome, it is just letting you type numbers.

### Expected behavior

In all browsers, the input type number just lets type numbers.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.1.1
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Edge: Not Found
    Safari: 17.1

```
</details>

**Search keywords**: input number filter panel
**Order ID**: 77137

**Comment by DanailH** [comment]
@FreakDroid can you check your reproduction link - it doesn't seem to work.

**Comment by FreakDroid** [comment]
@DanailH I updated the link. Sorry for that I missed it.

**Comment by michelengelen** [comment]
@FreakDroid this is not a bug with our implementation, but rather the behavior of the browser specific input implementation.

You can easily check that if you just render this:

```
export default function NumberInput() {
  return <input type="number" />;
}
```

in Chrome (chromium browsers) it prevents entering text, in Safari (webkit) it doesn't.

---

@cherniavskii do we plan on using the [Number Input](https://mui.com/base-ui/react-number-input/) from Base UI in the future?

**Comment by FreakDroid** [comment]
> @FreakDroid this is not a bug with our implementation, but rather the behavior of the browser specific input implementation.
> 
> You can easily check that if you just render this:
> 
> ```
> export default function NumberInput() {
>   return <input type="number" />;
> }
> ```
> 
> in Chrome (chromium browsers) it prevents entering text, in Safari (webkit) it doesn't.
> 
> @cherniavskii do we plan on using the [Number Input](https://mui.com/base-ui/react-number-input/) from Base UI in the future?

@michelengelen thanks for your reply. Yes, I know about this issue but what I was thinking is that you said to use Number_input instead. Although this is not a blocker in our project, I will keep an eye on this topic.

**Comment by michelengelen** [comment]
> @michelengelen thanks for your reply. Yes, I know about this issue but what I was thinking is that you said to use Number_input instead. Although this is not a blocker in our project, I will keep an eye on this topic.

@FreakDroid Thanks for your understanding. I am not sure, but my guess is that it was not available when building the filter panel. So what would be best from that point onwards is to open up a feature request to replace the `<input type=""number />` with the NumberInput from baseUI.

I don't think that this is currently on our projects backlog.

**Comment by FreakDroid** [comment]
> > @michelengelen thanks for your reply. Yes, I know about this issue but what I was thinking is that you said to use Number_input instead. Although this is not a blocker in our project, I will keep an eye on this topic.
> 
> @FreakDroid Thanks for your understanding. I am not sure, but my guess is that it was not available when building the filter panel. So what would be best from that point onwards is to open up a feature request to replace the `<input type=""number />` with the NumberInput from baseUI.
> 
> I don't think that this is currently on our projects backlog.

@michelengelen do you know if to do this I need to create a custom filter panel? Or if you have an example would be useful.

**Comment by michelengelen** [comment]
@FreakDroid you can use the filter panel customization. Here is an example on a [custom input component](https://mui.com/x/react-data-grid/filtering/customization/#custom-input-component).
