### ISSUE TITLE
[data grid] Autosizing does not adjust when an individual column's width is set by the user

### ISSUE THREAD

**Issue by mkusold** [mui/mui-x#11530]
### Steps to reproduce

Link to live example: [codesandbox](https://codesandbox.io/p/sandbox/mui-datagridpro-example-forked-mwdndk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqpuostd00063b6l9xnjr2mu%2522%252C%2522sizes%2522%253A%255B89.60159362549801%252C10.398406374501988%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqpuostd00023b6le36oyhpx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqpuostd00033b6ltimaitwe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqpuostd00053b6l7pxp9q65%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqpuostd00023b6le36oyhpx%2522%253A%257B%2522id%2522%253A%2522clqpuostd00023b6le36oyhpx%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqpuostd00053b6l7pxp9q65%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqpuostd00043b6lee3l4ypp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqpuostd00053b6l7pxp9q65%2522%252C%2522activeTabId%2522%253A%2522clqpuostd00043b6lee3l4ypp%2522%257D%252C%2522clqpuostd00033b6ltimaitwe%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqpuostd00033b6ltimaitwe%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Open the demo. 
2. Then manually resize one of the columns
3. Note that the other columns do not adjust to fill in the space (see gif)

https://github.com/mui/mui-x/assets/5613706/e6b63a65-a7a5-4b0c-9416-8fcb03365bcc

Note I have tried several creative workarounds for this problem but I haven't gotten any to really succeed yet. I had attempted to record which column had been manually resized and then update the column definitions, but then I read that the table expects the column definitions to remain static throughout it's lifecycle.

I'd appreciate any help y'all can give. I'm reporting this as a bug because I think it should work this way, but perhaps it's more of a feature request.

### Current behavior

When a user manually shifts a column's width, the other autosizing columns remain whatever size they were on initial render and do not update.

### Expected behavior

I am expecting that when a user manually shifts a column, that the other columns that haven't been touched yet will automatically autosize to fill the remaining space (as it does on initial autosize)

### Context

I am building this for work and our users are complaining about column widths that aren't efficiently filling in the space. I'm having to set manual widths where possible but it doesn't look as good as I'd like.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
Using Chrome
```
  System:
    OS: macOS 13.0
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Edge: Not Found
    Safari: 16.1
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.27 
    @mui/core-downloads-tracker:  5.15.0 
    @mui/icons-material: ^5.15.0 => 5.15.0 
    @mui/lab: ^5.0.0-alpha.152 => 5.0.0-alpha.152 
    @mui/material: ^5.15.0 => 5.15.0 
    @mui/private-theming:  5.15.0 
    @mui/styled-engine:  5.15.0 
    @mui/system:  5.15.0 
    @mui/types:  7.2.11 
    @mui/utils:  5.15.0 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-pro: ^6.18.1 => 6.18.1 
    @mui/x-date-pickers:  6.17.0 
    @mui/x-date-pickers-pro: ^6.16.1 => 6.17.0 
    @mui/x-license-pro: ^6.6.0 => 6.10.2 
    @types/react: ^18.2.39 => 18.2.39 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 
```
</details>

**Order Id**: 62747
**Search keywords**: datagrid column resizing

**Comment by mkusold** [comment]
PS I added the order Id after I initially made the bug and now realize that probably effects the ability for GH to tag this properly as escalated. Please update with the pro tag if you can!

**Comment by DanailH** [comment]
@mkusold the autosizing feature does not work the way you expect it. It autosizes columns when you tell it to via `apiRef.current.autosizeColumns`. I'm curious as to what you expect to be the result when you resize a column. Maybe you can check the fluid width feature for the columns: https://mui.com/x/react-data-grid/column-dimensions/#fluid-width

**Comment by mkusold** [comment]
thanks for getting back to me. I think I was unclear whether you could combine autosize with flex. It appears that I can accomplish the results I'm looking for with these two together. 

I would say that what I was hoping autosize would do off the bat is to allow a user to resize a column and for the other columns to accommodate within a certain range of defined minwidths. Here's what I got working using flex as a reference for what I was hoping autosizing would do:

https://github.com/mui/mui-x/assets/5613706/97c98c92-39d6-4601-ba78-a4c83c6e9336

When I trigger autosize without these flex additions, It ends up overriding user defined column widths.

I'll close this out, but thanks for pointing me in the right direction
