### ISSUE TITLE
[charts] order of tooltip is not in the same order like a stacked bar chart

### ISSUE THREAD

**Issue by dohomi** [mui/mui-x#11544]
### The problem in depth 🔍

In my opinion the order of tooltip is not natural to read. I attach a screenshot, my client who is non-tech gets confused because the order of the stacked bar chart is in reversed order within the tooltip. I havent found an open issue which targets this problem.

Is there a solution to reverse the tooltip that the bar chart colors / items are in the same order within the tooltip?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.0
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.6.6 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 120.0.6099.129
    Edge: Not Found
    Safari: 17.0
  npmPackages:
    @emotion/react:  11.11.1
    @emotion/styled:  11.11.0
    @mui/base:  5.0.0-beta.24
    @mui/core-downloads-tracker:  5.14.18
    @mui/icons-material:  5.14.18
    @mui/lab:  5.0.0-alpha.153
    @mui/material:  5.14.18
    @mui/private-theming:  5.14.18
    @mui/styled-engine:  5.14.18
    @mui/system:  5.14.18
    @mui/types:  7.2.9
    @mui/utils:  5.14.18
    @mui/x-charts:  6.18.4
    @mui/x-data-grid:  6.18.1
    @mui/x-data-grid-pro:  6.18.1
    @mui/x-date-pickers:  6.18.1
    @mui/x-license-pro:  6.10.2
    @types/react:  18.2.38
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.3.2 => 5.3.2
```
</details>

**Search keywords**: chart reverse order tooltip
**Order ID**: 7bef5ee5e5f7911da8e5f428bfb34756Tz03NDAyOCxFPTE3MjU1MDU0NjUwMDAsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI=

**Comment by dohomi** [comment]
<img width="335" alt="Screenshot 2024-01-02 at 13 29 23" src="https://github.com/mui/mui-x/assets/489221/da3d55ee-d369-4d57-91a8-c99fae557428">

**Comment by michelengelen** [comment]
@alexfauquette is there a way to reverse it (other than a custom tooltip implementation)?

**Comment by alexfauquette** [comment]
The tooltip order is the order of the series definition. The order of the stack is defined by `stackOrder` https://mui.com/x/react-charts/stacking/#stack-order

The easiest might be to modifie the stack order by adding `stackOrder: 'reverse'` property to the first series

**Comment by dohomi** [comment]
great thanks

**Comment by mathilderv** [comment]
Hello @dohomi @alexfauquette
I'm facing the same issue, I've tried to add the `stackOrder: 'reverse'` parameter to the dashboard JSON config file, like so: 
<img width="580" alt="image" src="https://github.com/user-attachments/assets/e653549b-8a5e-436d-8b3a-52e60194490b">

Nothing changes on my chart. Is it the way we are supposed to apply `stackOrder: 'reverse'`? What am I doing wrong here?
Thanks

**Comment by alexfauquette** [comment]
@mathilderv I think you're on the wrong issue. The `@mui/x-charts` does not have `crossFilters` or `chart_configuration`

If you're effectively using `@mui/x-charts` could you open a new issue with a reproduction?
