### ISSUE TITLE
[pickers] Option for abbreviated or wide for month view 

### ISSUE THREAD

**Issue by fakhamatia** [mui/mui-x#11546]
### Summary 💡

I want to show full month name in month view, not abbreviated.
I'm using `6.16.0` but cant find this option in doc and source.

**Search keywords**: abbreviated month

**Comment by LukasTy** [comment]
Hello @fakhamatia, have you tried overriding the `dateFormats` on `LocalizationProvider`?
There is a `monthShort` format that is currently only used on the `MonthCalendar`.
That is not the most proper solution long-term, but one that should work for now, until we provide more extensibility in this regard.
```tsx
<LocalizationProvider
  dateAdapter={AdapterDayjs}
  dateFormats={{
    monthShort: 'MMMM',
  }}
>
```

**Comment by fakhamatia** [comment]
> Hello @fakhamatia, have you tried overriding the `dateFormats` on `LocalizationProvider`? There is a `monthShort` format that is currently only used on the `MonthCalendar`. That is not the most proper solution long-term, but one that should work for now, until we provide more extensibility in this regard.
> 
> ```tsx
> <LocalizationProvider
>   dateAdapter={AdapterDayjs}
>   dateFormats={{
>     monthShort: 'MMMM',
>   }}
> >
> ```

Yes, it works perfectly!

**Comment by LukasTy** [comment]
I'm glad to hear that it solves your problem. 🙌 
I'm closing this issue as we have an open issue (https://github.com/mui/mui-x/issues/10874) to introduce more slots for year and month calendars. 😉
