### ISSUE TITLE
[data grid] Enable grid selectors to access props

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#11549]
In some cases, grid selectors need to access not only the state but also:
- root props, e.g. `gridPageCountSelector` in https://github.com/mui/mui-x/issues/8450#issuecomment-1492454179
- `theme`, e.g. `gridVisiblePinnedColumnsSelector` in https://github.com/mui/mui-x/pull/10059#discussion_r1430423750

As a general solution to the problem, we need a mechanism for adding selected props to the grid state, as proposed in https://github.com/mui/mui-x/issues/8450#issuecomment-1861294626

**Search keywords**: 

## Scope

- A mechanism for adding selected props to the grid state
- Fix https://github.com/mui/mui-x/issues/8450

**Comment by romgrk** [comment]
I think we can close this, there is nothing to do for this at this point as all the other issues have been solved. We didn't use a general mechanism but the root props where added at places that made sense (`paginationModel` for the `rowCount`). If we ever need access to the root props we can open this again.
