### ISSUE TITLE
[DataGridPremium] renderHeader is not used in case of grouping

### ISSUE THREAD

**Issue by Bengya** [mui/mui-x#11552]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-raacw5?file=Demo.js

Steps:
1. The grouping column does not use the `renderHeader` prop even if you remove the `headerName` prop

### Current behavior

The header name for the grouping column is the `headerName` prop instead of the `renderHeader` prop. If the `headerName` is removed from the definition, the renderHeader is still not used.

### Expected behavior

If `renderHeader` prop is provided for the column definition, it should be used for the grouping column.

### Context

I am doing some custom actions/style and logic in the column header but when I am grouping based on a column, only the default name is displayed, instead of the custom render method.

If the `leafField` is used, the issue is the same, only the name is used in the column definiton.

I think something similar was solved in this commit:
https://github.com/mui/mui-x/commit/f83dc164472a3ceb5258be42327205139bcb84d1

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid grouping renderHeader

**Comment by michelengelen** [comment]
Hey @Bengya for the grouping column you can just use the `groupingColDef` prop. There is a section in the docs about this: [Custom grouping column](https://mui.com/x/react-data-grid/row-grouping/#custom-grouping-column)

**Comment by Bengya** [comment]
Thank you, yes I was able to use the `groupingColDef`'s `renderHeader` prop for this purpose, the issue can be closed :+1:
