### ISSUE TITLE
DataGrid: Missing Page Size Options in Pagination

### ISSUE THREAD

**Issue by 21Ovi** [mui/mui-x#11580]
### Steps to reproduce

**Environment Details:**
- Material-UI Version: [5.2.4]
- Material-UI x-Datagrid:[5.2.0]
- Browser: [e.g.,Firefox]

**Description:**
I encountered an issue related to the missing page size options in the DataGrid pagination.

**Steps to Reproduce:**
1. Open the page containing the DataGrid.
2. Scroll down to locate the DataGrid with pagination.
3. Observe that the page size options dropdown is missing.

**Expected Behavior:**
The DataGrid pagination should display a dropdown with page size options.

**Actual Behavior:**
The page size options dropdown is not visible in the DataGrid pagination.

### Current behavior

**Current Behavior:**

When navigating to the page with the DataGrid, the page size options dropdown in the pagination section is not visible. Instead, only the default page size is shown, and there's no way to change the number of rows per page.

this how my code looks:
![image](https://github.com/mui/mui-x/assets/92392084/589f7eb2-480f-4fab-870c-4d3f761cd49c)

and this is how the UI looks:
![image](https://github.com/mui/mui-x/assets/92392084/4d48d633-b0da-4512-9c84-ff1632d508b8)

### Expected behavior

I expected that when navigating to the page with the DataGrid, the pagination section would display a dropdown with page size options. This dropdown should allow users to select the number of rows to display per page, providing a more flexible viewing experience.

### Context

I am using the DataGrid component to display a paginated list of activities in my application. The ability to customize the number of rows per page is crucial for our users to manage their workflow efficiently. The missing page size options dropdown is impacting our users' ability to tailor the DataGrid display to their preferences, leading to a less user-friendly experience.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: material-ui, mui, DataGrid, DataTable, Table, Pagination, Rows per Page, Page Size Options, Bug, Issue, Problem, Error, pageSizeOptions, onPageSizeChange, handleChangeRowsPerPage, rowsPerPage

**Comment by 21Ovi** [comment]
After hours of debugging I understood that the prop pageSizeOption is very sensitive, so here I had dynamic data with columns so I was changing rows size and if anything went wrong, the rows per page dropdown disappears, I think team MUI should show this kind of error in console rather then just hide that thing away.

**Comment by xsevcika2** [comment]
@21Ovi - Have you tried setting the `initialState` property? I noticed that when I change `pageSizeOptions` to some custom values without setting `initialState`, the "Rows per page" dropdown disappeared.

I couldn't find it explicitly written anywhere, but in the sample code that's in the documentation, they did it like this:
https://mui.com/x/react-data-grid/pagination/#page-size-options

### Without the `initialState` setup:
<img width="300" alt="image" src="https://github.com/mui/mui-x/assets/25958497/9978421d-93f7-42b4-bf96-17edb7794464">

<img width="300" alt="image" src="https://github.com/mui/mui-x/assets/25958497/111c48f6-bd5a-4165-92a5-67f364e75ce9"> 

### With the `initialState` setup:
<img width="300" alt="image" src="https://github.com/mui/mui-x/assets/25958497/a32e3073-c5ba-48f1-b589-6fd3847d3944">

<img width="300" alt="image" src="https://github.com/mui/mui-x/assets/25958497/c2fba989-b082-49f0-b0d5-c3eee6fcfb07">

<img width="300" alt="image" src="https://github.com/mui/mui-x/assets/25958497/9ec31280-8209-4144-925c-87dc426f2e7a">

**Comment by Gregory-Han** [comment]
preview-587cd39a5889a.js:2 MUI X: The page size `4` is not present in the `pageSizeOptions`.
Add it to show the pagination select.
