### ISSUE TITLE
[charts] Horizontal bar chart tick labels are always cut off after 7 characters

### ISSUE THREAD

**Issue by khgiddon** [mui/mui-x#11591]
### Steps to reproduce

[Link to live example](https://codesandbox.io/p/sandbox/wispy-cookies-sg94y8)

Steps:
1. Copy the [horizontal bars example](https://mui.com/x/react-charts/bars/#system-HorizontalBars.js)
2. Change the tick labels - for example using "January" and "February" and "April is the cruelest month" or something longer. 

Note - [this issue](https://github.com/mui/mui-x/issues/10928) seems to cover long tick labels generally, but I opened this for a horizontal bar chart specific issue surrounding the positioning if the y-axis, and because 7 characters is not particularly "long."

### Current behavior

Left side of the y-axis is in a fixed position, resulting in the labels being cut off.
<img width="504" alt="Screen Shot 2024-01-06 at 10 23 19 AM" src="https://github.com/mui/mui-x/assets/45672945/df0186d3-e317-42fe-a17c-86bff0b77e9d">

### Expected behavior

The labels should take up as much space as necessary (right-justified) an the y-axis should adjust its position based on the spacing of the labels.

### Context

I am trying to use the horizontal bar chart, but this issue makes it impossible because labels cannot display.

[Someone else on StackOverflow](https://stackoverflow.com/questions/77725613/how-to-show-whole-y-axis-tick-label-in-mui-bar-chart-for-horizontal-layout) is also having the same issue.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: charts barchart

**Comment by iamzafar** [comment]
Is there a timeline for it to be fixed?

**Comment by khgiddon** [comment]
> You should be able to modify the space available on the left with `margin={{ left: 100 }}` if you need more for you labels

Thanks! This worked.

**Comment by Dikarabo-Molele** [comment]
> You should be able to modify the space available on the left with `margin={{ left: 100 }}` if you need more for you labels

Had the same issue on v6.19.4

This solution did the trick, however, I noticed a different behaviour on the mui docs site. Maybe documentation needs to be updated with this solution or the proposed way of addressing this issue?

**Comment by mrerdem** [comment]
Is there any chance for automatic left margin size? With current setup, manual calculation is a must I believe.

**Comment by fiepb** [comment]
I'm having the same issue here. From Y labels the margin trick works, but what do I do with barLabels when ploting big datasets?

<img width="418" alt="image" src="https://github.com/user-attachments/assets/c2148ad0-790a-4628-8692-fa0e1ef34031">

This dataset has 223 registers/categories with values that can go from 0 to 250.000 e.g.

Any solutions?

**Comment by mrerdem** [comment]
One solution for me was to manually use K, M, etc. coefficients to limit the width it needs. So 250000 -> 250K and so on.

**Comment by pablo-chinchilla-sl** [comment]
For anyone still trying to find a solution for this...

You can use `width` property in `yAxis` property. For example:
```
<BarChart
      dataset={dataset}
      yAxis={[{ scaleType: "band", dataKey: "month", width: "auto" }]}
      series={[{ dataKey: "seoul", label: "Seoul rainfall", valueFormatter }]}
      layout="horizontal"
      {...chartSetting}
    />
```

or

```
<BarChart
      dataset={dataset}
      yAxis={[{ scaleType: "band", dataKey: "month", width: 100 }]} //any numeric value
      series={[{ dataKey: "seoul", label: "Seoul rainfall", valueFormatter }]}
      layout="horizontal"
      {...chartSetting}
    />
```
Result using `auto` (this is from the example provided in the live example);
<img width="730" height="458" alt="Image" src="https://github.com/user-attachments/assets/d38c74a2-852e-4c9f-a1d0-054b69e97167" />

**Comment by alexfauquette** [comment]
Thanks for the update, the `width`/`height` porperties are v8 new features :+1:
