### ISSUE TITLE
[data grid] Overflow for rows

### ISSUE THREAD

**Issue by jonyfSaiflow** [mui/mui-x#11605]
### The problem in depth

In our design we wish to add a shadow around the table rows, this works well with the top and bottom shadows. I just add some spacing between the rows and viola!
The left and right shadows have been quite a challenge to implement, as there's an overflow: hidden container around the row list.

I have managed to make my shadows appear, on all sides and that had to 'kill' the horizontal scroll feature, which we knew was a setback. Now I'm adding the h-scroll. I managed to create something that almost works completely, I'm left stuck with a bit of overflow at all times. 
I have looked in the source code in mui-x in the version i'm using, and it seems that [this is the flag I need to affect](https://github.com/mui/mui-x/commit/3123d3aaf3b495717323af013bb848e893c879f6#diff-15c3b1f4a97dc49586e05c49c8da01f5f9d034b16f43e277725787c4be3c1f69R516): `needsHorizontalScroll`.

My issue: I always get overflow-x scroll with this solution. Is there any way around it? 🙏 

[Fork](https://codesandbox.io/p/sandbox/sleepy-maxwell-jw4ppd?file=%2Fsrc%2Fdemo.tsx%3A55%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr3ewsv000063b6h2wwr78zr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr3ewsv000023b6h2umvnhju%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr3ewsv000033b6hca5nj97r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr3ewsv000053b6hc41g6esl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr3ewsv000023b6h2umvnhju%2522%253A%257B%2522id%2522%253A%2522clr3ewsv000023b6h2umvnhju%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr3exdnf005k3b6hqfqxblmz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A55%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A55%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr3exdnf005k3b6hqfqxblmz%2522%257D%252C%2522clr3ewsv000053b6hc41g6esl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr3ewsv000043b6hmnzmz82e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr3ewsv000053b6hc41g6esl%2522%252C%2522activeTabId%2522%253A%2522clr3ewsv000043b6hmnzmz82e%2522%257D%252C%2522clr3ewsv000033b6hca5nj97r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr3ewsv000033b6hca5nj97r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browser: Arc, but this stands in chrome, and Mozilla FF
  System:
    OS: macOS 13.0.1
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Edge: Not Found
    Safari: 16.1
  npmPackages:
    @emotion/react: 11.10.5 => 11.10.5 
    @emotion/styled: 11.10.5 => 11.10.5 
    @mui/material: ^5.10.14 => 5.10.14 
    @mui/styled-engine-sc: ^5.10.14 => 5.10.14 
    @mui/x-data-grid: ^5.17.12 => 5.17.12 
    @mui/x-data-grid-pro: ^5.17.12 => 5.17.12 
    @mui/x-date-pickers: ^6.18.2 => 6.18.2 
    @mui/x-date-pickers-pro: ^6.18.2 => 6.18.2 
    @types/react: 18.0.25 => 18.0.25 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components: 5.3.6 => 5.3.6 
    typescript: ~4.9.5 => 4.9.5 
```
</details>

**Search keywords**: datagrid row overflow horizontal
**Order ID**: 79145

**Comment by michelengelen** [comment]
@romgrk could you have a look here? Considering you have been working on scrolling quite extensively lately! Thanks! 🙇🏼

**Comment by jonyfSaiflow** [comment]
Hi,
any help would be appreciated

**Comment by michelengelen** [comment]
Hey @jonyfSaiflow ... a quick fix for this is to just remove the padding on the virtualscroller element with:
``
sx={{
  "&.MuiDataGrid-root .MuiDataGrid-virtualScroller": {
    paddingLeft: 0,
    paddingRight: 0,
  },
}}
```

[Example](https://codesandbox.io/p/sandbox/frosty-rain-g82zcv?file=%2Fsrc%2Fdemo.tsx%3A80%2C13-86%2C13)

Does that help you?

**Comment by jonyfSaiflow** [comment]
Hi,
any help would be appreciated

**Comment by jonyfSaiflow** [comment]
> Hey @jonyfSaiflow ... a quick fix for this is to just remove the padding on the virtualscroller element with: `` sx={{ "&.MuiDataGrid-root .MuiDataGrid-virtualScroller": { paddingLeft: 0, paddingRight: 0, }, }}
> 
> ```
> 
> [Example](https://codesandbox.io/p/sandbox/frosty-rain-g82zcv?file=%2Fsrc%2Fdemo.tsx%3A80%2C13-86%2C13)
> 
> Does that help you?
> ```

No, I'll clarify, the design i'm trying to implement has shadows on each row. Shadow is rendered outside of an element, and because of virtualScrolling being very precise the rows don't have room for the shadow. Which is why I add the padding to virtualScroller.

There might be a different way to implementing what I want, which is having shadows on rows that don't get "cut" from right / left of the rows. And still keep the horizontal scroll in case the grid needs it.

edited my fork, made the shadow more apparent

**Comment by michelengelen** [comment]
@jonyfSaiflow that does indeed clarify it. I am not entirely sure that the design you are looking for is possible, at least not with the standard behavior.

I created a small example with a little hacky implementation using `::before` and `::after` of the rows: [row shadows](https://codesandbox.io/p/sandbox/suspicious-roman-y2l3vq?file=%2Fsrc%2Fdemo.tsx%3A61%2C1)

For this to be perfect you would still need to fine-tune the paddings of the rows, so that the checkboxes are aligned to the middle again, but it shows a possibility.

Let me know if this is sufficient for your use case!
Thanks!
