### ISSUE TITLE
[pickers] when using `clearable` field with DatePicker, selecting a date doesn't return focus to openPickerButton 

### ISSUE THREAD

**Issue by samanthaksanders** [mui/mui-x#11619]
### Steps to reproduce

Link to live example: 
https://codesandbox.io/p/sandbox/great-margulis-zl8rhk?file=%2Fsrc%2FDemo.tsx

Steps:
1. Make sure the field has no value selected
2. set `slotProps={{ field: { clearable: true } }}`
3. Use keyboard to trigger the calendar picker with the "Choose date" button
4. Select a date
5. Focus is not returned to openPickerButton

### Current behavior

When I am using a clearable date field with the DatePicker, upon selecting a date using my keyboard the current focus leaves the element and unexpectedly goes back to the body

### Expected behavior

When I am using a clearable date field with the DatePicker, upon selecting a date using my keyboard the current focus then goes back to the openPickerButton

### Context

We would like our DatePicker component to have the clear button by default. It makes it easier for the user to delete the field value. But because it unexpectedly moves return focus to body when selecting a date initially, we can't confidently use a clear button.

Once the field actually has a value, then return focus actually starts to work correctly (if you try to change that date again).

It also correctly returns focus to the button if you close it with the escape key. The issue appears when you actually select a date from the calendar grid

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Issue is replicated in MUI codesandbox link using `<DatePicker slotProps={{ field: { clearable: true } }} />`

```
System:
    OS: macOS 13.3.1
Browser
   Chrome: 120.0.6099.199
```
</details>

**Search keywords**: openPickerButton clearable returnFocus

**Comment by noraleonte** [comment]
Hey, @samanthaksanders 👋 

I can confirm that the focus is being set back to the `OpenPickerButton` correctly after the `ClearButton`'s first render. I will take a better look into the issue, and will update you once we have a solution!
