### ISSUE TITLE
[DatePicker] DatePicker behaves differently in UnitTesting

### ISSUE THREAD

**Issue by AdrianMetlenko** [mui/mui-x#11617]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/devbox/ns3qvf

Steps:
1. run "npm test"
2. 3 pass / 3 fail

### Current behavior

Testing the component with @testing-library/user-event > user.keyboard("0102") input returns a value of "10/02/YYYY"

### Expected behavior

Testing the component with @testing-library/user-event > user.keyboard("0102") input should return a value of "01/02/YYYY" - as occurs when user actually types

### Context

I am trying to write unit tests with a full coverage of valid/invalid user inputs into the picker.
Inconsistent behaviour between actual user input and testing inputs make this impossible.

### Your environment

  System:
    OS: macOS 14.2.1
  Binaries:
    Node: 21.1.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 10.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.119 
    @mui/core-downloads-tracker:  5.11.12 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/lab: ^5.0.0-alpha.129 => 5.0.0-alpha.129 
    @mui/material: ^5.11.12 => 5.11.12 
    @mui/private-theming:  5.15.3 
    @mui/styled-engine:  5.15.3 
    @mui/system:  5.15.3 
    @mui/types:  7.2.12 
    @mui/utils:  5.15.3 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-pro: ^6.18.1 => 6.18.1 
    @mui/x-date-pickers: ^6.18.0 => 7.0.0-alpha.7 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.0.28 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.9.5 

**Search keywords**: datepicker testing user input
**Order ID**: 74084

**Comment by michelengelen** [comment]
Currently the environment is not set up correctly. The testing throws errors.
Could you adjust that so we can test that? Thanks! 🙇🏼 

```
Warning: The current testing environment is not configured to support act(...)
```

**Comment by AdrianMetlenko** [comment]
Sorry for my misunderstanding - resolving the act() warning (which I missed earlier) also resolved this issue.

I will keep in mind that wrapping user events unnecessarily in act() can lead to unexpected results
