### ISSUE TITLE
[pickers] using `disableOpenPicker` prop with responsive DatePicker shows no dates in mobile calendar dialog

### ISSUE THREAD

**Issue by samanthaksanders** [mui/mui-x#11618]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/amazing-silence-ks3gq6?file=/src/Demo.tsx

Steps:
1. Use device toolbar to simulate mobile device (or alternately, look at the link on a device)
2. Click the input field to trigger the picker dialog
3. The dialog contains no days to select, only action buttons

<img width="1462" alt="Screenshot 2023-11-22 at 11 24 09 am" src="https://github.com/mui/mui-x/assets/1756527/7b199e66-ccf5-4c4b-8448-992c47ea537e">

### Current behavior

When using `<DatePicker disableOpenPicker />` on a device, I want to select a date from the calendar picker but there are no dates in the dialog to choose. The dialog only contains action buttons.

### Expected behavior

When using `<DatePicker disableOpenPicker />` on a device I want to select a date from the calendar picker. There should always be a list of days/months/years to select, as well as action buttons.

### Context

We want to be able to use the `disableOpenPicker` prop which should only effect the desktop version. Happy with the different behaviour on mobile, and know that disableOpenPicker won't do anything in that context. But it would be good if there were still some dates to pick 😄   

We are now using the DesktopDatePicker only instead, but would be good to be able to use the responsive version and the `disableOpenPicker` prop.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Issue is replicated in MUI codesandbox link using DatePicker, and simply adding disableOpenPicker

System:
    OS: macOS 13.3.1
Browser
   Chrome: 119.0.6045.159
```
</details>

**Search keywords**: pickers disableOpenPicker

**Comment by michelengelen** [comment]
Thanks @samanthaksanders for raising this issue.
I did add this to the board for the team to assess the issue and estimate it, but for the meantime you could do a workaround with a device detection like this:
[example with basic device detection](https://codesandbox.io/p/sandbox/sweet-bush-jl2m39?file=%2Fsrc%2FDemo.tsx%3A9%2C1)
