### ISSUE TITLE
[question] Nesting MUI X Data Grid

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11610]
I am trying to render a table using mui x data grid. How can I nest another table inside the parent table?
I can't use the Tree data feature and it renders rows as subcomponent, whereas I want to render entire table(similar to parent table) as subcomponent.
MUI X tree view is not useful as I am unable to create a child table as tree item inside the parent table.

**Search keywords**:

**Comment by evgeniiarts** [comment]
@kumar-pratiyush I guess this would solve your request, as the very first example shows how one data grid is nested in another using the Master Detail feature:
https://mui.com/x/react-data-grid/master-detail/

**Comment by kumar-pratiyush** [comment]
This works well. Thanks for the help!
