### ISSUE TITLE
Removed Watermark from DateRangePicker Component in MUI X (Pro)

### ISSUE THREAD

**Issue by patelanurag4** [mui/mui-x#11621]
### Steps to reproduce

Link to live example: (required)

Steps:
1.  Added following css:
 `color: transparent` property to `.MuiDateRangeCalendar-root > div`.
 

Here is the sandbox link for reference:
https://codesandbox.io/p/sandbox/date-range-tpjd6x?file=%2Fsrc%2Fstyles.css%3A5%2C1

### Current behavior

<img width="866" alt="image" src="https://github.com/mui/mui-x/assets/42891797/edfd2cee-2101-4e3f-821d-911b27d38f3e">

### Expected behavior

<img width="868" alt="image" src="https://github.com/mui/mui-x/assets/42891797/99f311f4-93be-4ecb-868a-67ddaaf1bdef">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: disabled watermark from pro plan MUI-X

**Comment by flaviendelangle** [comment]
Hi,

Not sure what you are trying to demonstrate here.
The main goal of the watermark is to help developer remember that they don't have a valid license.
It's not meant to be a good protection.
If you don't have a license, you are breaking our term of service, whether or not you are displaying a watermark in your application.

We could try to make the watermark more robust of course, but I don't think it's that important.

**Comment by patelanurag4** [comment]
I'll be fixing this issue. Please assign this to me.

**Comment by flaviendelangle** [comment]
If you have some idea to make the watermark more robust, feel free to open a pull request :+1:

**Comment by patelanurag4** [comment]
@flaviendelangle 

I have raised a PR for the following:  https://github.com/mui/mui-x/pull/11625

**Comment by cherniavskii** [comment]
See https://github.com/mui/mui-x/pull/11625#issuecomment-1883668656
