### ISSUE TITLE
[question] Bulk editing in MUI X Pro

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11632]
Is there a working example of bulk editing in MUI X Pro version? I tried using the same example as MUI X Premium by changing imports to Pro but Pro version does not support "unstable_cellSelection" and "experimentalFeatures={{ clipboardPaste: true }}" props. When tried using bulk editing without these props, unable to write anything while editing.

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @kumar-pratiyush ... there is a section on [bulk editing](https://mui.com/x/react-data-grid/recipes-editing/#bulk-editing). Its currently only possible with the feature the premium version provides.

**Comment by kumar-pratiyush** [comment]
Is there any way to implement bulk editing using Pro version?

**Comment by kumar-pratiyush** [comment]
> Hey @kumar-pratiyush ... there is a section on [bulk editing](https://mui.com/x/react-data-grid/recipes-editing/#bulk-editing). Its currently only possible with the feature the premium version provides.
> 
> I am sorry that this is not possible the way it is build in that demo.

Is there any way to implement bulk editing using Pro version?

**Comment by oliviertassinari** [comment]
Work done on this problem #12800.
