### ISSUE TITLE
date picker

### ISSUE THREAD

**Issue by Nandhakumar8698** [mui/mui-x#11631]
### Related page

https://mui.com/x/react-date-pickers/date-picker/

### Kind of issue

Unclear explanations

### Issue description

I was looking for … and it appears that …
  i use the mui date picker,after i select the date to update the state and console it,output comes like this,Mon, 08 Jan 2024 18:30:00 GMT but i selected date was,09.01.20204,it displayed one day befor date 

**Search keywords**: dayjs

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.
