### ISSUE TITLE
Apply the aggregation to lead to the undefined error in another column

### ISSUE THREAD

**Issue by EkaLinMan** [mui/mui-x#11630]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/charming-cray-vpfkks?file=%2Fsrc%2FDemo.tsx%3A23%2C44

Steps:
1. Apply the sum aggregation to the `gross` column

### Current behavior

It has the error of `Cannot read properties of undefined (reading 'toLocaleString')` in Line 23, which indicates that it is undefined in `test` column.

### Expected behavior

Because all the columns have their data, It should apply the sum aggregation successfully.
Also, I don't understand why I applied aggregation to the gross column, it had an error in another column,
Did I do something wrong? 
Thanks.

**Search keywords**: aggregation

**Comment by michelengelen** [comment]
Thanks @evgeniiarts ... Great explanation!

**Comment by Yuwan** [comment]
Hi @michelengelen @zannager ,
I make a similar sample code from @EkaLinMan but with some differences as my requirement
**Steps to reproduce**

1. https://codesandbox.io/p/sandbox/holy-wave-cl7hyg?file=%2Fsrc%2FDemo.tsx
2. apply the sum aggregation to the gross column

**Current behavior**
show 0 in the last row of the column `test` which there is no aggregation applied. 

**Expected behavior
I'd like to show the empty value as undefined for the last row of the `test` column. It should not affected by the `valueFormatter` while I didn't expect the aggregation work on it.

The solution I have now is to ignore by checking  the id,  such as below
```
  if (id === "auto-generated-group-footer-root") {
      return;
   }
```
but it makes my code verbose.
Any suggestion?

**Comment by EkaLinMan** [comment]
Thanks for [evgeniiarts](https://github.com/evgeniiarts) replyment.
[Yuwan](https://github.com/Yuwan)'s issue is what I encountered, of course, I can fix it with the empty check.
But it doesn't make sense the `valueFormatter` of the B column is invoked when the `aggregation` of the A column is enabled.
That's complicated for me because I need to write a `valueFormatter` to work for itself `aggregation` and to ignore the side effect caused by the other column's  `aggregation`.

**Comment by michelengelen** [comment]
@EkaLinMan and @Yuwan 
Your condition `if (isNaN(value))` is causing the problem here.
columns that are not aggregated and have no `valueFormatter` will not show anything. Only when providing a `valueFormatter` you need to check for the existence of a value:

```
valueFormatter: ({ value }) => {
  if (!value) return value; // OR: return null;
  if (isNaN(value)) {
    return 0;
  } else {
    return value.toLocaleString('en-US');
  }
},
```

**Comment by Yuwan** [comment]
@michelengelen Thanks for the reply,
the code snippet you provided did not work for me.
I expect to get `0` for the undefined cell in the normal rows ( normal row means the rows except for the last aggregation result) and would like to have `0` for the last row.
As you mentioned above, "columns that are not aggregated and have no valueFormatter will not show anything.", and is it possible that I have a column not aggregated (the` test` column in my sample) and the valueFormmater works only for the normal rows?

**Comment by michelengelen** [comment]
@Yuwan sure. You can just set the `aggregable` prop on the colDef to `false`

[Here](https://mui.com/x/react-data-grid/aggregation/#for-some-columns) is the respective part in the docs

**Comment by EkaLinMan** [comment]
Hi, [michelengelen](https://github.com/michelengelen), thanks for reply.

I knew the mechanism, I mean is it necessary to invoke `valueFormatter` for the last row that doesn't enable `aggregation` feature? Can you skip invoking the valueFormatter` when we don't select any `sum`, `avg` etc, even if the aggregable prop is true?

**Comment by michelengelen** [comment]
> Hi, [michelengelen](https://github.com/michelengelen), thanks for reply.
> 
> I knew the mechanism, I mean is it necessary to invoke `valueFormatter` for the cell in the auto-generated row that doesn't enable `aggregation` feature? Can you skip invoking the valueFormatter only for the cell in the auto-generated row if we don't select any `sum`, `avg` etc, whether the aggregable prop is true or not?

Yes it is. For a simple reason: You typically want the value in the aggregation to be formatted the same as the ones in the rows. And normally when there is no value thats sufficient. Only when you want to have a different return (in this case `0`) when there is no value at all you will run into problems, where you have to target the `id` in a separate clause as well.

**Comment by EkaLinMan** [comment]
I prefer: If we don't enable the aggregation feature for the columns, these columns should automatically display nothing in the aggregation row, no matter what mechanism behind it. This way is more intuitive to the developers.

Anyway, can you add a simple description for the [aggregation](https://mui.com/x/react-data-grid/aggregation/) or [value formatter](https://mui.com/x/react-data-grid/column-definition/#value-formatter) to avoid the issues that @Yuwan and I have ever met?
