### ISSUE TITLE
[DataGrid] Treedata expand/collapse does not trigger onRowClick-Event

### ISSUE THREAD

**Issue by GeiOoo** [mui/mui-x#11655]
### Steps to reproduce

Video: https://github.com/mui/mui-x/assets/29431488/c4fe3ae8-2661-4640-bde0-b8022c09ce3b
Link to live example: https://stackblitz.com/edit/react-qwvzzk?file=Demo.tsx

Steps:
1. Click the row anywhere to trigger this handle -> log in console appears
2. Click the collapse/expand button in the grouping column -> no logging in console

### Current behavior

The collapse/expand button does not trigger the onRowClick event.

### Expected behavior

The collapse/expand button should trigger the onRowClickEvent to also react to state changes on this row.

### Context

I have to save the current collapsed/expanded state of all grouping rows. This onRowClick event would be a solution for that since there is no separate event listener for state changes of row grouping collapse/expande.

If habe also posted a separate feature request for that: https://github.com/mui/mui-x/issues/11654

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.201
    Edge: Chromium (120.0.2210.121)
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.31 
    @mui/core-downloads-tracker:  5.15.4 
    @mui/icons-material: ^5.15.4 => 5.15.4 
    @mui/material: ^5.15.4 => 5.15.4 
    @mui/private-theming:  5.15.4 
    @mui/styled-engine:  5.15.4 
    @mui/system:  5.15.4 
    @mui/types:  7.2.13
    @mui/utils:  5.15.4
    @mui/x-data-grid:  6.18.7
    @mui/x-data-grid-pro: ^6.18.7 => 6.18.7
    @mui/x-date-pickers: ^6.18.7 => 6.18.7
    @mui/x-license-pro:  6.10.2
    @types/react: ^18.2.47 => 18.2.47
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.3.3 => 5.3.3
```
</details>

**Search keywords**: datagrid treedata group expand collapse row

**Comment by michelengelen** [comment]
Hey @GeiOoo ... we do have a section on the docs that (kind of) handles this already by subscribing a handler to the `'rowExpansionChange'` event: [Lazy loading children](https://mui.com/x/react-data-grid/tree-data/#children-lazy-loading)

The param in this is the node that gets expanded, so you can easily get the rowdata with `const row = apiRef.current.getRow(node.id) as Row | null;`

**Comment by evgeniiarts** [comment]
Hehe apparently I still have a lot to learn, thanks @michelengelen for pointing that out :)

**Comment by michelengelen** [comment]
> Hehe apparently I still have a lot to learn, thanks @michelengelen for pointing that out :)

don't worry ... that's a pretty advance use-case! :D

**Comment by flaviendelangle** [comment]
I think `onRowClick` is not called because of this `event.stopPropagation` https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx#L59

It was added in #https://github.com/mui/mui-x/pull/3929

**Comment by flaviendelangle** [comment]
@michelengelen I reopened it because it was unclear to me if we had to wait for user feedbacks on that one, feel free to re-close it if you want
