### ISSUE TITLE
[data grid] How do I get the count of filtered rows on initial load when I have an initial state?

### ISSUE THREAD

**Issue by wlee-vendelux** [mui/mui-x#11653]
### The problem in depth

https://codesandbox.io/p/sandbox/solitary-lake-5xrxzw?file=%2Fsrc%2FDemo.tsx%3A25%2C62

^ sandbox example. As you can see, when you load the page, `filteredRowCount` is 0 and is only updated once I click the button to refresh the state.

Ideally I'd like for the `DataGrid` to load initially with predefined states like `filterModel` and `sortModel` and then be able to get the filtered counts of the visible rows.

Is this possible?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
I used Google Chrome

  System:
    OS: macOS 13.5
  Binaries:
    Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
    npm: 9.6.4 - ~/.volta/tools/image/npm/9.6.4/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.199
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base: ^5.0.0-beta.20 => 5.0.0-beta.20 
    @mui/core-downloads-tracker:  5.12.0 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.126 => 5.0.0-alpha.126 
    @mui/material: ^5.12.0 => 5.12.0 
    @mui/private-theming:  5.12.0 
    @mui/styled-engine:  5.12.0 
    @mui/styles: ^5.12.0 => 5.12.0 
    @mui/system:  5.12.0 
    @mui/types:  7.2.6 
    @mui/utils:  5.15.3 
    @mui/x-data-grid:  6.18.6 
    @mui/x-data-grid-premium: ^6.0.0 => 6.18.6 
    @mui/x-data-grid-pro:  6.18.6 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-date-pickers-pro: ^5.0.20 => 5.0.20 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react: ^17.0.58 => 17.0.58 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ~4.9.5 => 4.9.5 

```
</details>

**Search keywords**: datagrid filter count initial load
**Order ID**: 69589

**Comment by evgeniiarts** [comment]
@wlee-vendelux I have created a minimalistic example, hopefully this can get you started:
https://codesandbox.io/p/sandbox/optimistic-archimedes-n9mwft

In the example, before attempting to show the row count, we make sure that the rows were loaded in the first place. And we also react to the change of the filter model so we get an accurate amount of rows which are visible after applying filters.
I have also included a filterModel in the example which you could expand to suit your needs.
https://mui.com/x/react-data-grid/filtering/#controlled-filters

**Comment by michelengelen** [comment]
Thanks @evgeniiarts ... Does this solve your issue @wlee-vendelux?

**Comment by wlee-vendelux** [comment]
Yes everything is good. Thank you @evgeniiarts and @michelengelen !
