### ISSUE TITLE
[data grid] event for popup open/close missing for pageSize popup

### ISSUE THREAD

**Issue by AkankshaPushkarna** [mui/mui-x#11657]
### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/p/sandbox/serene-cdn-rjl4xz)

Steps:
1. No event exposed for pageSize popup.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: data grid events

**Comment by michelengelen** [comment]
Hi @AkankshaPushkarna this is true. We do not expose an event like that.

Could you elaborate what you are trying to achieve/build? maybe we can help you with that.

**Comment by michelengelen** [comment]
BTW: you can always implement your own pagination and replace the default one. Here is a section about how to do that in the docs: [custom pagination](https://mui.com/x/react-data-grid/components/#pagination)
