### ISSUE TITLE
[question] I have a question about automatic data trimming.

### ISSUE THREAD

**Issue by won3545** [mui/mui-x#11663]
### The problem in depth

I have a question about automatic data trimming.

When I put into some data at row props, the data was shown without blank at the beginning

This is the example

![image](https://github.com/mui/mui-x/assets/16523985/ff483afe-4b5a-40ac-950f-bf5539c6772f)

I'm not sure it is a bug or intended action.

so, If you have any options to show the blank at the beginning, please let me know.

(I already tried to use valueGetter, valueFormatter, renderCell function)

Thanks.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid auto trimming
**Order ID**: 74635

**Comment by michelengelen** [comment]
Hey @won3545 ... the whitespaces get trimmed by CSS.

You can change the CSS with the `sx` prop on the datagrid component. Here is a little [example](https://codesandbox.io/p/sandbox/vigilant-mcclintock-dy4tzt?file=%2Fsrc%2FDemo.tsx%3A53%2C24).

I am not sure if this change might introduce issues when calculating the rendered dimensions though.
