### ISSUE TITLE
[pickers] `DateTimePicker` with hook form does not validate disablePast

### ISSUE THREAD

**Issue by bharatAscent** [mui/mui-x#11669]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-uxjp25?file=Demo.tsx
Steps:
1.Select today's Date in date time picker
2.Do not select time and close the picker

### Current behavior

It allows past time in date time picker

### Expected behavior

It should show error as it shows on date time pickers without hook form control

### Context

When using datetime picker without any form provider the disablePast & disableFuture validates the feilds. But with the use of hook form and yup it considers the date as valid even if it is of past.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: Not Found
    Edge: Chromium (120.0.2210.121)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.18
    @mui/core-downloads-tracker:  5.14.12
    @mui/icons-material: ^5.14.19 => 5.14.19
    @mui/lab: ^5.0.0-alpha.147 => 5.0.0-alpha.147      
    @mui/material: ^5.14.12 => 5.14.12
    @mui/private-theming:  5.15.3
    @mui/styled-engine:  5.14.12
    @mui/system:  5.14.12
    @mui/types:  7.2.12
    @mui/utils:  5.15.3
    @mui/x-data-grid: ^6.18.2 => 6.18.2
    @mui/x-date-pickers: ^6.18.2 => 6.18.2
    @mui/x-tree-view:  6.0.0-alpha.1
    @types/react:  18.2.41
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0

```
</details>

**Search keywords**: datetimepicker disable past validation

**Comment by noraleonte** [comment]
Hey, @bharatAscent 👋 

I am not sure I'm getting this entirely right 🤔 

Have you tried using the `onError` [callback](https://next.mui.com/x/api/date-pickers/date-picker/#date-picker-prop-onError)?

**Comment by bharatAscent** [comment]
Hello @noraleonte ,

Here is the quick explanation:
- When disablePast is used it validates the datetime picker with past value and shows the field as error.
- When added form validation using yup & react-hook-form and disablePast is used then with the past value the field is not shown as the error.

With the help of onError, I used the new error to manually insert it in case there is no form error.

Here is the updated Code: https://stackblitz.com/edit/react-uxjp25?file=Date.jsx

If there is a way to set the errors on form fields directly from internal Mui magic then it would be great.

For now, The onError callback helps.
