### ISSUE TITLE
[data grid] Row or column reordering doesn't work in Chrome 120 on Linux Wayland

### ISSUE THREAD

**Issue by cpouldev** [mui/mui-x#11660]
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-data-grid/row-ordering/

Steps:
1. Open the link in Wayland Chrome v120 (latest at the time of this issue)
2. Reorder a row or a column. Doesn't work
3. Open the same link in Wayland Firefox
4. Reorder a row or a column. Works as expected

https://github.com/mui/mui-x/assets/8311776/60eaf3e4-a6a5-4513-b18a-95167367ec13

### Current behavior

The dragged row when released,  jumps back to its original position thus the reordering doesn't happen. Console shows nothing, the `onRowOrderChange` event doesn't fire.

### Context

Tested on 2 devices with Wayland. On X11 Chrome/Chromium it works. You can enable the Wayland mode by starting chrome with `google-chrome --enable-features=UseOzonePlatform --ozone-platform=wayland`
### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: Linux 6.6 Fedora Linux 39 (Thirty Nine)
  Binaries:
    Node: 20.10.0 - /usr/bin/node
    npm: 8.18.0 - ~/.npm/bin/npm
    pnpm: 8.6.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.216
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/icons-material: ^5.15.4 => 5.15.4 
    @mui/lab: 5.0.0-alpha.160 => 5.0.0-alpha.160 
    @mui/material: ^5.15.4 => 5.15.4 
    @mui/styles: ^5.15.4 => 5.15.4 
    @mui/x-charts: 6.18.7 => 6.18.7 
    @mui/x-data-grid-pro: ^6.18.7 => 6.18.7 
    @mui/x-date-pickers: ^6.18.7 => 6.18.7 
    @mui/x-date-pickers-pro: ^6.18.7 => 6.18.7 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.47 => 18.2.47 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 5.3.3 => 5.3.3 
</details>

**Search keywords**: datagrid reordering chrome reorder
**Order ID**: 61387

**Comment by michelengelen** [comment]
@MBilalShafi do you have any idea why this does not work?

**Comment by romgrk** [comment]
Can't reproduce on Chrome 120 on wayland (archlinux). Is this a problem specific to the datagrid or is it also broken elsewhere?

Maybe test with this: https://codepen.io/Goldfsh/pen/zBbOqm

<img width="200" src="https://github.com/mui/mui-x/assets/1423607/3df1a168-f39b-4876-b34d-e3d7af043e60" />

**Comment by cpouldev** [comment]
Both of your links work as expected

**Comment by MBilalShafi** [comment]
I am also not able to reproduce it on Chrome Version 120.0.6099.216 on MacOS. It could've something to do with the OS you're on 🤔
Could you try another Chromium based browser and share the results?

**Comment by cpouldev** [comment]
I tried already brave and chromium in wayland mode, same issue. I use Sway as wayland compositor. As I mentioned earlier, on Firefox Wayland it works. For chromium based browser it works only on X11 (xwayland) mode.  

The first video shows a chromium browser in xwayland mode. It works as expected. The moving eyes mean that the cursor is moving through an X11 window. On a wayland window, the eyes won't move.

https://github.com/mui/mui-x/assets/8311776/baee655a-14ef-4cc4-b4f0-e0480c9ae49c

---

**This shows the broken behavior on Wayland mode.**


https://github.com/mui/mui-x/assets/8311776/90dd9ebc-05db-460d-bcfe-67bdc4df0ceb

**Comment by romgrk** [comment]
Not sure which interaction is causing this, and reproducing the bug on our side could be very time intensive (briefly reading the [arch docs on sway](https://wiki.archlinux.org/title/sway), there's quite a bit of configuration to get it up). Could you help us debug this by inspecting a few values with the devtools? With the chrome devtools open, press Ctrl+Shift+F to search for the string `End dragging row`, put a breakpoint at the `rowOrderChange` event following that and show us what values you have.

<details>
<summary>Example</summary>

![image](https://github.com/mui/mui-x/assets/1423607/fcbeb8ad-9bf6-4082-94a2-120b977f6c4b)

</details>

**Comment by cpouldev** [comment]
Sure. Unfortunately it didn't hit the breakpoint on `rowOrderChange` event.

https://github.com/mui/mui-x/assets/8311776/1b13500d-295a-4697-94d5-6250c38615d3

**Comment by romgrk** [comment]
Test this with FF & chrome, report what you see in the console: [mdn playground link](https://developer.mozilla.org/en-US/play?id=M%2FS3et1vfMUFcc7FEfcIez0Iw%2BsMBfhgnAg9ZMwoVx5LHWhp1xMbTFBGG4GWrwDJL4PnlUhj8R1kaCTq)

[Lots of chromium issues](https://bugs.chromium.org/p/chromium/issues/list?q=dropEffect&can=2) related to `ev.dataTransfer.dropEffect`, but none mentionning sway directly. We could probably find a different way to detect that the row is dropped outside the grid.

https://github.com/mui/mui-x/blob/e23779e5826e5344da5f014845e99b6e6cc31e22/packages/grid/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx#L173-L177

**Comment by romgrk** [comment]
@cpouldev Another test that might help us:
 - Breakpoint in the `dragstart` event above, look for the string "Start dragging row"
 - When it breaks, manually run `t.dataTransfer.effectAllowed = 'move'`
 - And shows values for the `dragend` handler (string "End dragging row")

**Comment by cpouldev** [comment]
MDN:

Left is chrome, right if FF


https://github.com/mui/mui-x/assets/8311776/82ee3f72-b5ad-47c8-8acd-25ddb2fd6ea6


Chrome:

```
dragStart: dropEffect = none ; effectAllowed = uninitialized
dragOver: dropEffect = none ; effectAllowed = move
...
dragOver: dropEffect = none ; effectAllowed = move
dragOver: dropEffect = none ; effectAllowed = move
drop: dropEffect = none ; effectAllowed = move
```

FF:

```
dragStart: dropEffect = none ; effectAllowed = uninitialized
dragOver: dropEffect = move ; effectAllowed = move
...
dragOver: dropEffect = move ; effectAllowed = move
dragOver: dropEffect = move ; effectAllowed = move
drop: dropEffect = move ; effectAllowed = move
```
---

> Breakpoint in the dragstart event above, look for the string "Start dragging row" ...


https://github.com/mui/mui-x/assets/8311776/645e1391-4070-4505-b599-a231ab5aa9b3

![image](https://github.com/mui/mui-x/assets/8311776/57345fcc-70ef-4664-8ca1-fa8c6dd8d9b6)

**Comment by romgrk** [comment]
Is this a newly release bug or does it happen for older versions of chromium?

Imho, considering that the bug only happens on chromium on a specific platform and that chromium behavior's differs from the spec, I'm tempted to mark this one as out-of-scope. I don't like the idea of introducing hacks in our codebase to fix bugs that need to be fixed upstream anyway.


@cpouldev Could you open an issue on chromium's tracker (crbug.com) and check with them what's the best resolution for this? This issue seems pretty similar to your report: https://bugs.chromium.org/p/chromium/issues/detail?id=1470718

**Comment by cpouldev** [comment]
I just tried chromium v117 and the issue exists. You are probably right, this has to do with wl-roots based compositors and chromium in wayland mode. Especially from the moment you tried too with your DE (which I believe is GNOME/KDE), the issue seems to be too isolated to setups as mine.

I'll open an issue there. Thanks

**Comment by cpouldev** [comment]
FYI on Chrome v132 issue does not appear anymore and I can dnd as expected
