### ISSUE TITLE
[data grid] Filter component oveflows grid (not responsive)

### ISSUE THREAD

**Issue by 9uifranco** [mui/mui-x#11674]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/xenodochial-tamas-qxspqn

Steps:
1. Open Datagrid filter on small screen

### Current behavior

Default filter component overflows grid on small screens.

![filter-datagrid](https://github.com/mui/mui-x/assets/108012699/fcafe7e5-4813-4d2e-95ca-db9f1c42ec18)

### Expected behavior

 Maybe the filter component should adjust its layout to prevent overflow issues on smaller screens.

### Context

I'm currently working on a project where we heavily rely on the data grid component and our application is designed to be responsive. When users try to utilize the filter component on the data grid in a mobile view, it overflows and doesn't provide an optimal user experience.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22622
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 119.0.6045.200
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.30
    @mui/core-downloads-tracker:  5.15.3
    @mui/icons-material: ^5.15.3 => 5.15.3
    @mui/material: ^5.15.3 => 5.15.3
    @mui/private-theming:  5.15.3
    @mui/styled-engine:  5.15.3
    @mui/system:  5.15.3
    @mui/types:  7.2.12
    @mui/utils:  5.15.3
    @mui/x-data-grid: ^6.18.7 => 6.18.7
    @mui/x-date-pickers: ^6.18.7 => 6.18.7
    @types/react: ^18.2.43 => 18.2.47
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.3.3
```
</details>

**Search keywords**: datagrid filter mobile responsive

**Comment by 9uifranco** [comment]
This was my workaround: https://codesandbox.io/p/sandbox/recursing-taussig-8cxh36

I added some styles using `slotsProps` props:

```javascript
<DataGridPro
  {...data}
  loading={data.rows.length === 0}
  rowHeight={38}
  checkboxSelection
  disableRowSelectionOnClick
  slotProps={{
    panel: {
      sx: {
        "& .MuiDataGrid-filterForm": {
          flexDirection: "column",
          gap: ".5rem",
          alignItems: "flex-start",
        },
        "& .MuiFormControl-root": {
          width: "100%",
        },
        "& .MuiDataGrid-filterForm .MuiButtonBase-root": {
          alignSelf: "flex-end",
        },
      },
    },
  }}
/>
```

**Comment by michelengelen** [comment]
Thanks @9uifranco ... it is indeed not ideal. If the solution you came up with works for you that's great. I am honestly not sure if we intended to support responsive behaviour for the filterpanel (or the data grid in general).

Your solution looks ok. One thing you could maybe do to increase the responsive feel to use a modal or fullscreen dialog and render the panel inside. You can use the `slots.panel` prop for that

**Comment by 9uifranco** [comment]
@michelengelen Thanks. Fullscreen dialog would be even better for my purpose. I'm just not sure how to properly customize Datagrid subcomponents... this is what I came up with:

I use the onClick of my custom filter button in `CustomToolbar` to toggle the filter dialog

```javascript

const [openFilter, setOpenFilter] = React.useState(false);

const handleClickFilterButton = () => {
  setOpenFilter(openFilter ? false : true);
};

const handleClose = () => {
  setOpenFilter(false);
};
  
<DataGridPro
  {...data}
  loading={data.rows.length === 0}
  rowHeight={38}
  checkboxSelection
  disableRowSelectionOnClick
  slots={{
    panel: () => (
      <FilterDialog open={openFilter} handleClose={handleClose} />
    ),
    toolbar: () => (
      <CustomToolbar handleClickFilterButton={handleClickFilterButton} />
    ),
  }}
/>
```

The bellow is my `CustomToolbar`. I initially attempted to utilize `<GridToolbarFilterButton />`, but it appears that I couldn't directly use the onClick prop, so I just used a regular button to make it work for testing purpose. Also, the onClick for `<GridToolbarColumnsButton />` is working, but it doesn't open the default Column Menu. Am I missing something here?

```javascript
function CustomToolbar({ handleClickFilterButton }: any) {
  const handleClickTest = () => {
    console.log("Button clicked");
  };
  return (
    <GridToolbarContainer>
      <button onClick={handleClickFilterButton}>My Filter</button>
      <GridToolbarFilterButton onClick={handleClickTest} />
      <GridToolbarColumnsButton onClick={handleClickTest} />
      <GridToolbarDensitySelector onClick={handleClickTest} />
      <GridToolbarExport onClick={handleClickTest} />
    </GridToolbarContainer>
  );
}
```

Link to live example: https://codesandbox.io/p/sandbox/lucid-thompson-mzz649

**Comment by michelengelen** [comment]
Hey @9uifranco great job already. 👍🏼 
To further improve this you can just use the `apiRef`. That makes things a lot easier. 
Here is an [example](https://codesandbox.io/p/sandbox/admiring-turing-wcqfp4?file=%2Fsrc%2Fdemo.tsx%3A84%2C30).

Let me know if this solves your issue. 🙇🏼
