### ISSUE TITLE
MUI X Pro Data Table Custom Pagination

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11685]
I am trying to implement custom pagination in Mui X Data table, but I am getting " Type '{ pagination: (props: any) => React.JSX.Element; }' is not assignable to type 'Partial<UncapitalizedGridProSlotsComponent>'. Object literal may only specify known properties, but 'pagination' does not exist in type 'Partial<UncapitalizedGridProSlotsComponent>'. Did you mean to write 'Pagination'?" error.  
The component code is below:

<DataGridPro autoHeight  editMode='row' disableColumnMenu rowHeight={25} slots={{ toolbar: GridToolbar, pagination: CustomPagination }} pagination initialState={{pagination: {paginationModel: { pageSize: preferences.pageSize, page: 0 }, }, }}unstable_ignoreValueFormatterDuringExport columns={colData} rows={rowData} rowThreshold={0}/>

function Pagination({ page, onPageChange, className,}: Pick<TablePaginationProps, 'page' | 'onPageChange' | 'className'>) {
  const apiRef = useGridApiContext();
  const pageCount = useGridSelector(apiRef, gridPageCountSelector);
return (
    <MuiPagination sx={{width:"100%", backgroundColor:"red"}} color="primary" className={className} count={pageCount} page={page + 1} onChange={(event, newPage) => {onPageChange(event as any, newPage - 1); }}/>
  );}

function CustomPagination(props: any) {
  return <GridPagination ActionsComponent={Pagination} {...props} />;
}

**Search keywords**:

**Comment by michelengelen** [comment]
Hi @kumar-pratiyush 
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. [This **codesandbox.io** template](https://mui.com/r/x-issue-template) _may_ be a good starting point. You can find more codesandbox templates in our [docs](https://mui.com/x/react-data-grid/).

Thank you! 🙇🏼
