### ISSUE TITLE
[question] Problems with Pinned columns hover delay

### ISSUE THREAD

**Issue by ezequielgalardi** [mui/mui-x#11691]
### The problem in depth

https://github.com/mui/mui-x/assets/100214450/0297af2d-78a7-41d0-8339-22e84755fa5d

As we can see on the pinning columns official demos, after reproduce the video in 0.25x. Demo url: https://mui.com/x/react-data-grid/column-pinning/#blocking-column-unpinning

When the user makes hover over the rows, the pinned columns have some delay to change the background color. This happens in the official demos, and when we are using more complex data-grids this bugs are more evident.

https://github.com/mui/mui-x/assets/100214450/b189f9c3-873c-4fc1-9e16-cffc54b11daf

Is this a known bug? 

Its there any workaround to avoid this behavior? 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 14.2.1
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.109
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.16 
    @mui/core-downloads-tracker:  5.14.10 
    @mui/icons-material:  5.14.9 
    @mui/lab:  5.0.0-alpha.145 
    @mui/material:  5.14.10 
    @mui/private-theming:  5.14.10 
    @mui/styled-engine:  5.14.10 
    @mui/styled-engine-sc:  5.14.10 
    @mui/system:  5.14.10 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.10 
    @mui/x-data-grid:  6.18.4 
    @mui/x-data-grid-generator:  6.18.4 
    @mui/x-data-grid-premium:  6.18.4 
    @mui/x-data-grid-pro:  6.18.4 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-date-pickers-pro:  5.0.20 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react:  18.2.22 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  4.9.5 
```
</details>

**Search keywords**: pinned columns hover delay
**Order ID**: 74611

**Comment by romgrk** [comment]
Will be fixed shortly when #10059 is merged, but only for the v7 version. The v6 layout makes this issue unsolvable.
