### ISSUE TITLE
[data grid] How can we use multiple custom column types in v7?

### ISSUE THREAD

**Issue by mbiggs-gresham** [mui/mui-x#11696]
### The problem in depth

We use dayjs data types for our date and date time columns. Changes were made in the datagrid a while back (reported in https://github.com/mui/mui-x/issues/8062) which meant we could no longer use dayjs objects for `date` and `dateTime` columns.

We worked around this by creating our own custom `date-dayjs` and `dateTime-dayjs` column types, but you've now taken that ability away too as part of https://github.com/mui/mui-x/pull/11270. 

I see there is now a `custom` type but how can i distinguish between a date or a datetime custom column type? It's becoming incredibly difficult to be able to use custom data types within the grid. We need a way to be able to distinguish between custom types. We don't use the built in filtering or sorting etc.  

Could an additional string prop be added for `customType` to `GridColDef` or something? Just some kind of ability to distinguish would be great. 

**Search keywords**: Custom column types
**Order ID**: 45466

**Comment by romgrk** [comment]
@cherniavskii We could maybe allow extending by doing something like this:

![image](https://github.com/mui/mui-x/assets/1423607/b6f14e62-a1bf-4e13-9478-c9b1d5da23c6)

**Comment by michelengelen** [comment]
@romgrk I did put this on the board for now ... your suggestion seems like a very good choice.
