### ISSUE TITLE
DateRangePicker not showing clear icon when the clearable slotProp is passed to the field

### ISSUE THREAD

**Issue by zsoltlongauer** [mui/mui-x#11704]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/thirsty-fast-62nmqd

Steps:
1. Create a date range picker
2. Pass the "clearable: true" prop to the "field" in the date range picker slotProps field
3. See that the fields do not display the clear icon

### Current behavior

A clear icon is missing on both datefields

### Expected behavior

A clear icon is present on both datefields

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: Windows 11 10.0.22000
  Binaries:
    Node: 21.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (120.0.2210.133)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.30
    @mui/core-downloads-tracker:  5.15.3
    @mui/icons-material: ^5.15.2 => 5.15.2
    @mui/material: ^5.15.2 => 5.15.3
    @mui/private-theming:  5.15.3
    @mui/styled-engine:  5.15.3
    @mui/system:  5.15.3
    @mui/types:  7.2.12
    @mui/utils:  5.15.3
    @mui/x-data-grid:  6.18.7
    @mui/x-data-grid-pro: ^6.18.7 => 6.18.7
    @mui/x-date-pickers:  6.19.0
    @mui/x-date-pickers-pro: ^6.19.0 => 6.19.0
    @mui/x-license-pro: ^6.9.0 => 6.10.2
    @types/react: ^18.2.13 => 18.2.13
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.6.4
</details>

**Search keywords**: daterangepicker date range picker clearable
**Order ID**: 69798

**Comment by LukasTy** [comment]
Thank you for opening this issue. 👍 
It is [documented](https://mui.com/x/react-date-pickers/fields/#clearable-behavior) that we currently do not support this feature on the `MultiInput` range fields.
Please feel free to [use the `SingleInputDateRangeField`](https://mui.com/x/react-date-pickers/date-range-picker/#use-a-single-input-field) to benefit from the `clearable` behavior on the range picker.

We also already have an issue (https://github.com/mui/mui-x/issues/11635) to add this support to the `MultiInput` fields. 😉
