### ISSUE TITLE
[data grid] Data grids with multiple filterable column headings

### ISSUE THREAD

**Issue by cdennington** [mui/mui-x#11711]
### The problem in depth

We have purchased the premium version of MUI data grid, and have been using it to create excel like web documents for departments within our business.

We have recently had a request come through to build what is essentially a grid within a grid. See the excel attached for examples, I have marked the worksheets within the document in red which include the tables we are trying to recreate.

As you can see these worksheets appear to have two separate grids one after each other or side by side, these need to be part of the same grid, the cells need to be editable and the headings, even if they are below rows of data need to have filters.

I've been able to achieve this using separate data grids, but the business requirement means they must be one.

I have also been able to achieve headings after rows of data by simply using the valueFormatter function and making normal cells display as headings, however I have then been unable to add filters to these headings which control the data below them, which is also a business requirement.

Can you tell me if there is a way to achieve grids within grids with multiple heading rows?

[TEST1 Distribution - 30_6_2023 (1).xlsx](https://github.com/mui/mui-x/files/13959608/TEST1.Distribution.-.30_6_2023.1.xlsx)

### Your environment

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.121)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.28
    @mui/core-downloads-tracker:  5.15.1
    @mui/icons-material: ^5.14.18 => 5.15.1
    @mui/lab: ^5.0.0-alpha.153 => 5.0.0-alpha.157
    @mui/material: ^5.14.18 => 5.15.1
    @mui/private-theming:  5.15.1
    @mui/styled-engine:  5.15.1
    @mui/system:  5.15.1
    @mui/types:  7.2.11
    @mui/utils:  5.15.1
    @mui/x-data-grid: ^6.18.2 => 6.18.5
    @mui/x-data-grid-premium: ^6.18.2 => 6.18.5
    @mui/x-data-grid-pro:  6.18.5
    @mui/x-date-pickers: ^6.18.2 => 6.18.5
    @mui/x-license-pro: ^6.10.2 => 6.10.2
    @mui/x-tree-view: ^6.17.0 => 6.17.0
    @types/react: ^18.2.38 => 18.2.45
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.3.2 => 5.3.3

**Search keywords**: datagrid multiple columns
**Order ID**: 79517

**Comment by michelengelen** [comment]
@cherniavskii I do not think we can provide such a use-case atm, even with pivoting, right?

**Comment by cherniavskii** [comment]
Hi @cdennington 
Which sheet are you referring to? "A-Income statement"?

> I've been able to achieve this using separate data grids, but the business requirement means they must be one.

Could you clarify this requirement? What problems is a single grid supposed to solve compared to two separate grids?

**Comment by cdennington** [comment]
@cherniavskii see sheet B3-Borrowing costs and B4-Business-related costs

The business requirement is to have one grid, this is for two main reasons, firstly they want to be able to filter from any of the headings and have that filter affect all of the data, secondly, they want the columns to line up.

Believe me I have tried to convince them that two grids could work just as well, but have been unsuccessful in my attempts.

I am currently looking into repurposing the component GridColumnHeaderItem within the RenderCell function

**Comment by cherniavskii** [comment]
> firstly they want to be able to filter from any of the headings and have that filter affect all of the data, secondly, they want the columns to line up.

Alright, I think this is doable.
For filtering, using [controlled filter model](https://mui.com/x/react-data-grid/filtering/#controlled-filters) would do the job.
It's also possible to synchronize horizontal scroll.
Here's a working demo: https://codesandbox.io/p/sandbox/wizardly-hopper-5p9czp?file=%2Fsrc%2FDemo.tsx%3A29%2C2

Is this what you're looking for?

**Comment by cdennington** [comment]
@cherniavskii the working demo has two data grids, this needs to be one single data grid.

Essentially, we need the data grid to look and feel like excel, where any cell can be a heading or data or anything, does that make more sense?

**Comment by cherniavskii** [comment]
@cdennington Yes, I was trying to cover your use case with two grids - this is why I asked about the requirements in https://github.com/mui/mui-x/issues/11711#issuecomment-1899149287.
What are other requirements that were not covered by the example provided?
