### ISSUE TITLE
[data grid] Trouble integrating DataGridPremium

### ISSUE THREAD

**Issue by sarvaiyaniravAD** [mui/mui-x#11718]
### The problem in depth

Hello,

 

Greetings!

 

We have recently acquired license for DataGrid Premium. We are trying to integrate it into our application but having trouble to integrate it. It is an urgent issue that we need to fix as we would need to start our SIT. 

Kindly take this issue as high priority and help us resolve the issues.

 

Thanks,

Nirav Sarvaiya

Mob: 9769371183

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.217
    Edge: Chromium (120.0.2210.133)
  npmPackages:
    @emotion/react:  11.9.0
    @emotion/styled:  11.8.1
    @mui/base:  5.0.0-alpha.77
    @mui/icons-material: ^5.14.3 => 5.14.3
    @mui/material:  5.6.2
    @mui/private-theming:  5.8.0
    @mui/styled-engine:  5.6.1
    @mui/styles:  5.8.0
    @mui/system:  5.6.2
    @mui/types:  7.1.3
    @mui/utils:  5.8.0
    @mui/x-data-grid: ^6.14.0 => 6.14.0
    @mui/x-date-pickers: ^5.0.0-alpha.1 => 5.0.0-alpha.1
    @types/react:  17.0.0
    react:  17.0.2
    react-dom:  17.0.2
    styled-components:  5.3.3
    typescript:  4.4.2

**Search keywords**: Datagrid installation
**Order ID**: 82024

**Comment by romgrk** [comment]
Could you describe the issues you're having?

**Comment by sarvaiyaniravAD** [comment]
We have recently opted the Premium license for MUi library. When I try to integrate it to my application I get the following issue;

RollupError: "default" is not exported by "node_modules/@oracle-cx-commerce/react-components/node_modules/prop-types/index.js", imported by "node_modules/@oracle-cx-commerce/react-components/styled/index.jsx"

We have already integrated the @mui/x-data-grid [version: 6.14.0] in our application

**Comment by romgrk** [comment]
The error above doesn't seem to originate from the datagrid.

> imported by "node_modules/@oracle-cx-commerce/react-components/styled/index.jsx"

There seems to be an import error in this file. If you still think it's an issue caused by the datagrid, please be much more specific about your setup, in particular how you're bundling (you seem to be using rollup), and the steps for us to reproduce your issue.
