### ISSUE TITLE
[question] Is it possible to have background vertical lines for bar chart

### ISSUE THREAD

**Issue by brnguyenn** [mui/mui-x#11710]
### The problem in depth

Hi,

I am trying to add the background vertical grey lines or the 'cartesian grid' to my bar chart.

Expectation:
![Expected](https://github.com/mui/mui-x/assets/56327032/3c35fa5a-e46f-40d5-85fe-f1f3149bb56b)

I am using this https://mui.com/x/react-charts/components/#scales as reference to draw to the lines however I am experiencing two issues.

1. The lines are going over the top of the bars
2. I am not sure how to retrieve all the tick values (0, 20, 40, 60) (it's hardcoded here)

Is there a better way to achieve this? Thanks!
![Current](https://github.com/mui/mui-x/assets/56327032/bdba4a6f-ae52-489c-8157-bdcf84016759)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: charts background grid
**Order ID**: 79128

**Comment by alexfauquette** [comment]
Not easily for now. A grid layout should arrive soon. At least it's in my backlog for the coming month.

> The lines are going over the top of the bars

This can be solved by reordering your components if you use composition

> I am not sure how to retrieve all the tick values (0, 20, 40, 60) (it's hardcoded here)

Not sure about how to do it properly (that's the main topic of creating a grid component)

The axes use `const xTicks = useTicks({ scale: xScale, tickNumber, valueFormatter, tickInterval });`
https://github.com/mui/mui-x/blob/master/packages/x-charts/src/ChartsXAxis/ChartsXAxis.tsx#L157

But I don't think it's exported. If it's an urgent need you can still copy it from [here](https://github.com/mui/mui-x/blob/master/packages/x-charts/src/hooks/useTicks.ts) If it can wait a bit, maybe better to wait for the grid creation

**Comment by brnguyenn** [comment]
Thanks @alexfauquette, we will wait for the grid creation
