### ISSUE TITLE
[data grid] Checkbox selection is keeping selection when filtering

### ISSUE THREAD

**Issue by experimarketing** [mui/mui-x#11726]
### Steps to reproduce

Link to live example: (required): https://codesandbox.io/p/sandbox/relaxed-knuth-npz6j7

Steps:
1. Click the checkbox in the top left to select all 10 items.
2. Apply a filter to filter for  2-3 items.
3. Uncheck the checkbox to unselect all items.
4. Check the checkbox again. 

### Current behavior

It selects items which don't pass the filter criteria. 

### Expected behavior

After you have applied the filter, cleared the checkboxes, and check them again, it should only select the filtered items.

That is the default behavior. But it seems to be an issue if apply the checkbox before the filter.

### Context

It just provides an inconsistent experience, which could introduce errors if someone doesn't notice that more is selected than filtered.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid checkbox selection
**Order ID**: 73295

**Comment by michelengelen** [comment]
Hey @experimarketing and thanks for raising this issue.
It is indeed incorrect behavior, so I will put this on eon the board so that we can fix this.
Thanks again! 🙇🏼

**Comment by jyash97** [comment]
@michelengelen can I take a look at this issue ?

**Comment by g1mishra** [comment]
@jyash97, I've already addressed and fixed the issue. If you don't mind, could I proceed with this issue?

**Comment by michelengelen** [comment]
@g1mishra feel free to open a PR with your solution. Looking forward to it!

**Comment by experimarketing** [comment]
Just one update on this that I noticed when I was using it again. This is likely the same issue, but wanted to mention this reproduction of the issue.

Steps:

1. Click the checkbox in the top left to select all 10 items.
2. Apply a filter to filter for 3 items.
3. Uncheck the checkbox to unselect all items.

The selection model now contains 7 rows selected, when it should have none selected.
