### ISSUE TITLE
[data grid] client side filtering for number type is not working

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#11722]
### The problem in depth

Datagridpro version: 6.18.7

Are doing something for the value of number, like formatting? Currently we are just populating the column definition with type number and the filter operators is not working.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid filter getGridNumericOperators
**Order ID**: 33625

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. [This **codesandbox.io** template](https://mui.com/r/x-issue-template) _may_ be a good starting point. You can find more codesandbox templates in our [docs](https://mui.com/x/react-data-grid/).

Thank you! 🙇🏼

**Comment by simbahandiane** [comment]
I'll close this now. I found that the issue was on my side.
