### ISSUE TITLE
[pickers] DatePicker Placeholder

### ISSUE THREAD

**Issue by MarcoRef3at** [mui/mui-x#11727]
### Summary

when implimenting datepicker without label I can only see the format as a placeholder but can't change that placeholder to anything else rather than adding a label that will shrink on writing 
but adding just a placeholder for empty value is not doable 

**Search keywords**: DatePicker Placeholder

**Comment by LukasTy** [comment]
Hello, could you confirm what is the exact problem you are having with the `placeholder` not working?
It does seem to be applied correctly [in this demo](https://codesandbox.io/p/sandbox/gifted-flower-2kp2n3?file=%2Fsrc%2FDemo.tsx%3A5%2C1). 🤔
