### ISSUE TITLE
[data grid] Broken calculation and display with `{ value: -1, label: 'All', }` pagesize option

### ISSUE THREAD

**Issue by kno-raziel** [mui/mui-x#11724]
### Steps to reproduce

Link to live example: (required)
[Datagrid condesandbox](https://codesandbox.io/p/sandbox/serverless-paper-5jt737?file=%2Fsrc%2Fdemo.tsx%3A36%2C41)
Steps:
1. In the results per page select the "All" option
2. Notice the text of the displayed rows is wrong, it says "100001–100000 of 100000" and is enabling the go to previous page button in the navigation.

 

### Current behavior

 text of the displayed rows is wrong, it says "100001–100000 of 100000" and is enabling the go to previous page button in the navigation
 
 
![Screenshot 2024-01-17 at 11 54 30 AM](https://github.com/mui/mui-x/assets/8211946/3aa14fb4-0dad-4e25-8565-d44bdca8aab2)

Error in console
![image](https://github.com/mui/mui-x/assets/8211946/9a35c031-ae8a-4b64-80aa-c3811a01c8d9)

### Expected behavior

 text of the displayed rows should say "1–100000 of 100000" and all the buttons in the pagination should be disabled

[Documentation says ](https://mui.com/material-ui/api/table-pagination/#table-pagination-prop-rowsPerPageOptions)

> Customizes the options of the rows per page select field. If less than two options are available, no select field will be displayed. Use -1 for the value with a custom label to show all the rows.

It works perfectly if instead of `-1` as the value for the ALL options we use the total number of items.

Like in this [codesanbox](https://codesandbox.io/p/sandbox/crazy-http-758gsw?file=%2Fsrc%2Fdemo.tsx)

![Screenshot 2024-01-17 at 12 12 24 PM](https://github.com/mui/mui-x/assets/8211946/9b71c6c2-bd0c-4a32-9036-e2fc49b2bc6d)

### Context

We are trying to have an option in "Results per page" select to display all the rows.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 14.2.1
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base: ^5.0.0-beta.4 => 5.0.0-beta.4 
    @mui/core-downloads-tracker:  5.14.11 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/material: ^5.13.2 => 5.14.11 
    @mui/private-theming:  5.14.11 
    @mui/styled-engine:  5.14.11 
    @mui/system:  5.14.11 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.11 
    @mui/x-data-grid:  6.18.6 
    @mui/x-data-grid-premium: ^6.18.6 => 6.18.6 
    @mui/x-data-grid-pro:  6.18.6 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.2.24 => 18.2.24 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    styled-components: ^6.1.1 => 6.1.8 
    typescript: ~5.0.2 => 5.0.4 
</details>

Chrome

**Search keywords**: datagrid pageSizeOptions

**Comment by kno-raziel** [comment]
I believe the issue is the logic in this line, it doesnt take in to account the use of `-1`

[https://github.com/mui/material-ui/blob/b6705ec218180021e2740d3b8244aca7f393a2ed/packages/mui-base/src/TablePagination/TablePagination.tsx#L229](https://github.com/mui/material-ui/blob/b6705ec218180021e2740d3b8244aca7f393a2ed/packages/mui-base/src/TablePagination/TablePagination.tsx#L229)

**Comment by michelengelen** [comment]
Hey @kno-raziel ... thanks for raising this.
I can confirm that this is a bug. Even more so as the doc clearly states that this approach is the way to go. Thanks again! 🙇🏼

**Comment by gitstart** [comment]
@michelengelen @kno-raziel we would like to pick this up

**Comment by MBilalShafi** [comment]
[Fixed](https://codesandbox.io/p/sandbox/frosty-farrell-r37h7j?file=%2Fpackage.json%3A10%2C38) by #11958
