### ISSUE TITLE
[data grid] How can I style header filter row?

### ISSUE THREAD

**Issue by Davidna92** [mui/mui-x#11720]
### Related page

https://mui.com/x/react-data-grid/filtering/header-filters/

### Kind of issue

Unclear explanations

### Issue description

I am using unstable_headerFilters in DataGridPro component,
The issue is I need to style the background color of the unstable_headerFilters row, but not the row of the headers columns above.
How can I achieve that?

**Search keywords**: header filters, MUI, DataGrid

**Comment by michelengelen** [comment]
Hey @Davidna92 ... easiest is to apply styles to it through the `sx` prop:

```
sx={{
  '& .MuiDataGrid-headerFilterRow': {
    // apply styles here
  },
}}
```

We currently do not have a section in the docs on how to apply styling to the header filters, so this is a bit hard to find out. What we do have is a list of class-names for each part of the data grid: [Classnames](https://mui.com/x/api/data-grid/data-grid/#css)

**Comment by Davidna92** [comment]
Its looks like when i do css to className:  headerClassName  and change the background color even if I added what you written here its will be stronger than it.
So how can I separate the two rows? one for filters (as you written) and second for the headers only

**Comment by michelengelen** [comment]
> Its looks like when i do css to className: headerClassName and change the background color even if I added what you written here its will be stronger than it. So how can I separate the two rows? one for filters (as you written) and second for the headers only

You can just use syntax similar to CSS in the `sx` prop:

```
sx={{
  "& .MuiDataGrid-columnHeadersInner": {
    background: "red",
    ".MuiDataGrid-headerFilterRow": {
      background: "yellow",
    },
  },
}}
```

This will do the trick.

**Comment by Davidna92** [comment]
Thanks for answering, I actually find out I can use also '.MuiDataGrid-columnHeader--sortable' to handle the headers

**Comment by michelengelen** [comment]
Thats great to hear. Then we can close this for now.
BTW: if you are searching for advice on usage you can also ask on Stackoverflow. We have an active community there as well. 👍🏼
