### ISSUE TITLE
[tree view] Changes made in TreeView are not instantly visible in the browser

### ISSUE THREAD

**Issue by ThisisMS11** [mui/mui-x#11736]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Set up a Vite React app.
2. Now try to use https://mui.com/x/react-tree-view/ in any component.
3. Make some changes and note that the changes are not instantly visible. 

### Current behavior

Any changes made to the treeview code are not being shown instantly. currently, I have to stop my development server and restart it from scratch only then are the changes visible, though if I make changes in another part of my code, those are instantly displayed in the browser like in the content of a normal div or so.
![image](https://github.com/mui/mui-x/assets/91526766/97bf5e97-b467-4a79-945e-84329452a813)
![image](https://github.com/mui/mui-x/assets/91526766/3e338996-4e10-4d9b-9034-de15e004cf3b)

Now I have commented out the content Treeitem but changes are not visible . 

![image](https://github.com/mui/mui-x/assets/91526766/57e738de-9d74-4219-92ce-6cb26bf85fd1)
![image](https://github.com/mui/mui-x/assets/91526766/b3c27260-4082-4e02-bb27-defab6cd2a39)

### Expected behavior

Changes should be reflected instantly.

### Context

I am trying to use Treeview in the sidebar of my react app.

### Your environment

<details>
  <summary><code>
"dependencies": {
    "@emotion/react": "^11.11.3",
    "@emotion/styled": "^11.11.0",
    "@mui/icons-material": "^5.15.5",
    "@mui/material": "^5.15.5",
    "@mui/styled-engine-sc": "^6.0.0-alpha.12",
    "@mui/x-tree-view": "^6.17.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "styled-components": "^6.1.8",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@types/react": "^18.2.43",
    "@types/react-dom": "^18.2.17",
    "@vitejs/plugin-react": "^4.2.1",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.55.0",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.5",
    "postcss": "^8.4.32",
    "tailwindcss": "^3.3.6",
    "vite": "^5.0.8"
  }
</summary>

```
  I am using Chrome.
```
</details>

**Search keywords**: treeview

**Comment by michelengelen** [comment]
This is very interesting. I just tried that on StackBlitz and installed it in a local vite app. There is no delay there when changing something. I will try with the next version as well, but in the meantime could you check if your hot module replacement is working correctly?

Thanks! 🙇🏼
