### ISSUE TITLE
[pickers] Using LocalizationProvider to Set Date Format, but with Different Language for Calendar Text

### ISSUE THREAD

**Issue by whneo97** [mui/mui-x#11747]
I have a use case for `DatePicker` and `DateTimePicker` that requires localization support for date formats using browser locales, and also localization support for text that is globally set based on a given language and should be independent of the formatting for displayed values. I am using `dayjs` and the corresponding adaptor to format the dates, but the localization also simultaneously sets the language to be of the same given locale. Doing so can lead the text in the calendar to be different than those in outside of the component.

Is it possible to achieve setting the locale for the date formatting shown in the `TextInput` and the language shown in the calendar text separately?

**Search keywords**:

**Comment by alexfauquette** [comment]
It's tricky, because it's dayjs that generate the date format and the name of months, days, ...

As far as I know it's not feasible to get the date format in french with name written in english (or any locale mixing)

What you can do is to manually set the date format according to the browser locale. But you can't use meta token such as `LT` otherwise dayjs will interpret them in its settings locale

**Comment by LukasTy** [comment]
@whneo97 Is [this](https://codesandbox.io/p/sandbox/magical-dawn-yhxv2y?file=%2Fsrc%2FDemo.tsx%3A10%2C43) something you are looking for?
A separate format from the locale.
As Alex has mentioned, getting the date format for a given locale is not trivial. We also do not publicly expose internals that would help with it.
Depending on how complex the format logic needs to be, maybe you can get away with the mentioned proposal? 🤔

**Comment by whneo97** [comment]
Hi @alexfauquette and @LukasTy , thank you for the prompt reply!

> @whneo97 Is [this](https://codesandbox.io/p/sandbox/magical-dawn-yhxv2y?file=%2Fsrc%2FDemo.tsx%3A10%2C43) something you are looking for?

This workaround solution was very similar to what I also eventually came up with. A caveat of doing this was that I have to omit `dayPeriod` since AM/PM can also show up as the native language of the `locale` set under `Localization.Provider` too (visible in the given demo when the locale is `zh-cn`), but I do understand that this is an inherent behaviour of Javascript dates when formatted in a given locale, which would be tricky (and maybe breaking of how the formats are defined themselves) to tweak. I suppose always dislaying the 24-hour time format in the input might resolve this for now, as I have not noticed any other similar observations or clashes with specifiers so far.

Thank you!

**Comment by LukasTy** [comment]
@whneo97 If you need meridiem, but want to change it's translation in places that are in control of the adapter, consider playing around with https://day.js.org/docs/en/customization/customization. 😉 

If our answers have resolved your problem, please consider closing the issue. 👍

**Comment by whneo97** [comment]
Okay thank you so much for the suggestion!
