### ISSUE TITLE
[data grid] Columns order do not match the column array

### ISSUE THREAD

**Issue by eschneor** [mui/mui-x#11744]
### Steps to reproduce

Link to live example: (required)

Steps:
1. I have a sort array of columns
2. I render each cell with custom data according to the column
3. I get them in jumbled order

### Current behavior

I don't get the columns in the same order as the `columns` array I send to the grid.

### Expected behavior

Get the columns in the same order as the grid get them

### Context

Probably this is due to not all the value renders while the columns rendered so these columns are generated in the end.
Any way to wait until the data is render, or another idea to prevent that issue?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Use Chrome
```
    System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.144)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.3
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.29
    @mui/core-downloads-tracker:  5.15.2
    @mui/icons-material: ^5.11.16 => 5.15.2
    @mui/lab: ^5.0.0-alpha.137 => 5.0.0-alpha.158
    @mui/material: ^5.11.14 => 5.15.2
    @mui/private-theming:  5.15.2
    @mui/styled-engine:  5.15.2
    @mui/system:  5.15.2
    @mui/types:  7.2.11
    @mui/utils:  5.15.2
    @mui/x-data-grid:  6.18.6
    @mui/x-data-grid-pro: ^6.9.1 => 6.18.6
    @mui/x-date-pickers: ^6.18.0 => 6.18.6
    @mui/x-license-pro:  6.10.2
    @types/react: ^18.0.29 => 18.2.46
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.0.2 => 5.3.3
```
</details>

**Search keywords**: datagrid

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. [This **codesandbox.io** template](https://mui.com/r/x-issue-template) _may_ be a good starting point. You can find more codesandbox templates in our [docs](https://mui.com/x/react-data-grid/).

Thank you! 🙇🏼
