### ISSUE TITLE
[data grid] How to keep column width after dynamic column update?

### ISSUE THREAD

**Issue by LeonSa2404** [mui/mui-x#11741]
### The problem in depth

I am building a datagrid with several columns of type "singleSelect". The value options are stored in a database for easy updating across multiple software products. Since the columns prop should not change across re-renders I declared the columns with the default type. After the value options have finished fetching I update the columns to the singleSelect type and apply the fetched value options. 
One problem I am facing right now is that the column widths reset to the default width once the updateColumns method gets called. Is this expected behaviour or a bug? I expect the updateColumns method to only change specified props. If it's indeed expected, how should a use case like this be handled to keep the column state and the initialState?

Live demo:
https://codesandbox.io/p/sandbox/mui-datagrid-load-value-options-example-fxx9dn

Steps to reproduce:
1. Reload the page
2. Change the column width
3. Wait for the updateColumns to be called (Happens 5 sec after page load)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid column width updateColumns dynamic valueOptions
**Order ID**: 65695

**Comment by michelengelen** [comment]
Hey @LeonSa2404 

There are 2 ways you can accomplish what you are looking for.

One is by getting the current column state in your update function (`dynamicContentColumns` in your example) and spread the current `colDef` from the state onto your new `colDef`. I updated your example with this approach: [working example](https://codesandbox.io/p/sandbox/mui-datagrid-load-value-options-example-forked-n6nx2k?file=%2Fsrc%2Fdemo.tsx%3A127%2C37).

The other method would be to store the width for each column in a ref and access it during the column update. You can achieve this with `onColumnWidthChange`.

**Comment by LeonSa2404** [comment]
Hey @michelengelen 

Thanks for the quick reply. I implemented your first solution and it works like intended. I could imagine that this use case will be regularly found in more complex projects. Maybe our example should be added to the docs? In my opinion the updateColumns method should also be mentioned in the columns section of the docs. I found it by chance.
