### ISSUE TITLE
[data grid] SingleSelect columns stopped getting the label correctly for "is any of" starting from `7.0.0-alpha.7`

### ISSUE THREAD

**Issue by rodrigofariow** [mui/mui-x#11755]
### Steps to reproduce

Link to live example: https://next.mui.com/x/react-data-grid/filtering/

You can see it clearly on your demos
Steps:
1. Select "Country" filter
2. Select "is any of" operator
3. Select a country

### Current behavior

The `value` is shown on the text input instead of the `label`:

![image](https://github.com/mui/mui-x/assets/22502084/b5a8a405-8d0b-42d4-a675-b1b0ac950e59)

### Expected behavior

In https://mui.com/x/react-data-grid/filtering/  (latest 6.x) you have the expected behaviour:

![image](https://github.com/mui/mui-x/assets/22502084/c7ffac4f-de63-48f7-9796-052483b9aed7)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid single select
**Order ID**: 79531

**Comment by cherniavskii** [comment]
@cherniavskii Sure, why not

**Comment by cherniavskii** [comment]
The regression is most probably coming from https://github.com/mui/mui-x/pull/11330

**Comment by gitstart** [comment]
@michelengelen @cherniavskii we would like to pick this up

**Comment by rodrigofariow** [comment]
Any news @cherniavskii @michelengelen ?

In understand it's considered a small regression but it's a regression that prevents us from keeping updates to latest alpha versions and slowly deal with breaking changes.

**Comment by michelengelen** [comment]
@rodrigofariow there is a PR currently open for this. We just did not have the time to look at it yet. I will see it through, ok?

**Comment by michelengelen** [comment]
@rodrigofariow the PR just got merged, so you can expect the changes to hit the new version by the end of the week! :shipit:
