### ISSUE TITLE
[data grid] Is there an option for column gap?

### ISSUE THREAD

**Issue by yasir095** [mui/mui-x#11774]
### The problem in depth

I'm trying to implement responsive DataGrid but on mobile the column resizes to accommodate the space. I have set the  minWidth param and using flex option. Is there an option for columnGap in DataGrid that I can use to give spacing between columns so that it is more readable on smaller screen. I know i can override header class and give padding but is there an option where you can just specify columnGap, just like you do in a css grid.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 13.6
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 17.0
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base: ^5.0.0-beta.13 => 5.0.0-beta.13 
    @mui/core-downloads-tracker:  5.14.7 
    @mui/icons-material:  5.8.0 
    @mui/lab: ^5.0.0-alpha.142 => 5.0.0-alpha.142 
    @mui/material: ^5.14.7 => 5.14.7 
    @mui/private-theming:  5.14.7 
    @mui/styled-engine:  5.14.7 
    @mui/system:  5.14.7 
    @mui/types:  7.2.6 
    @mui/utils:  5.14.14 
    @mui/x-data-grid: ^6.9.0 => 6.9.0 
    @mui/x-data-grid-generator: ^6.16.2 => 6.16.2 
    @mui/x-data-grid-premium: ^6.16.2 => 6.16.2 
    @mui/x-data-grid-pro: ^6.9.0 => 6.9.0 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^17.0.40 => 17.0.40 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.5 => 5.3.5 
    typescript: ^4.6.2 => 4.6.2 
```
</details>

**Search keywords**: column gap
**Order ID**: 79553

**Comment by michelengelen** [comment]
Hey @yasir095 ... sry to disappoint you, but there is no simple `columnGap` prop you can use. Stylistic adjustments can be made through the `sx` prop or through a custom theme.
We do have a section about this in the docs: [Style](https://next.mui.com/x/react-data-grid/style/).
