### ISSUE TITLE
[data grid] Custom Pagination Component

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11773]
Trying to add custom pagination component in Mui X Pro Data Grid  as slots={{pagination: CustomPagination}}, as adding it like this gives error "Type '{ pagination: (props: any) => React.JSX.Element; }' is not assignable to type 'Partial<UncapitalizedGridProSlotsComponent>'". 
Any solution how to remove this error or any other way to add the custom pagination component?

**Search keywords**:

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. [This **codesandbox.io** template](https://mui.com/r/x-issue-template) _may_ be a good starting point. You can find more codesandbox templates in our [docs](https://mui.com/x/react-data-grid/).

Thank you! 🙇🏼
