### ISSUE TITLE
[datagrid] Sticky header regression: lazy-loading demo

### ISSUE THREAD

**Issue by romgrk** [mui/mui-x#11784]
https://next.mui.com/x/react-data-grid/row-updates/#lazy-loading

<img src="https://github.com/mui/mui-x/assets/3165635/ead64e02-8449-4837-af08-18f1dfb9b88c" width="803">

From https://github.com/mui/mui-x/issues/10059#issuecomment-1904240392
            

**Search keywords**:

**Comment by oliviertassinari** [comment]
Duplicate of #11865

**Comment by oliviertassinari** [comment]
@michelengelen Is there a way to skip "How did we do" if the user is part of the GitHub organization?
