### ISSUE TITLE
[docs] Demo ComponentExplorerNoSnap crashes

### ISSUE THREAD

**Issue by LDK1009** [mui/mui-x#11797]
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20ComponentExplorerNoSnap%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-date-pickers/base-concepts/
2. ??
3. demo *ComponentExplorerNoSnap* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v6.19.1  |
| Netlify deploy | https://65aa3de966d87e000841284a--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by flaviendelangle** [comment]
Hi,

Could you please describe how you are interacting with the demo when it crashes?
What are you clicking / typing?
