### ISSUE TITLE
DataGrid seems to initialize twice (performance issue)

### ISSUE THREAD

**Issue by scamden** [mui/mui-x#11796]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/datagrid-huge-tree-shared-with-mui-4t99yx

Steps:
1. Go to code sandbox 
2. open app in it's own page
3. Start chrome's performance profileer
4. Click remount

### Current behavior

The stack shows two full init cycles 

<img width="893" alt="Screenshot 2024-01-23 at 1 54 26 PM" src="https://github.com/mui/mui-x/assets/1128856/2c7e6961-eba1-49ff-ba3e-cbdc3c6f5077">

### Expected behavior

One init cycle

### Context

Premium customer here trying to optimize the performance of our very large DataGrid instance. It seems the grid is doing twice the init work on mount and I'd love to cut that in half if possible!

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 58.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nodenv/versions/18.12.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.5.1 - ~/.nodenv/versions/18.12.1/bin/npm
    pnpm: 6.32.11 - ~/.nodenv/versions/18.12.1/bin/pnpm
  Managers:
    Cargo: 1.63.0 - ~/.cargo/bin/cargo
    Homebrew: 4.2.5 - /opt/homebrew/bin/brew
    pip3: 22.2.2 - ~/.pyenv/shims/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.40.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    VirtualBox: 7.0.8 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
  IDEs:
    VSCode: 1.85.1 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.19.2 - /opt/homebrew/bin/go
    Perl: 5.30.3 - /usr/bin/perl
    Protoc: 25.1 - /opt/homebrew/bin/protoc
    Python: 3.9.9 - /Users/scamden/.pyenv/shims/python
    Python3: 3.9.9 - /Users/scamden/.pyenv/shims/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.63.0 - /Users/scamden/.cargo/bin/rustc
  Databases:
    PostgreSQL: 14.10 - /opt/homebrew/opt/postgresql@14/bin/postgres
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2
```
</details>

**Search keywords**: datagrid performance mount
**Order ID**: Order id

**Comment by romgrk** [comment]
Looks like the example is using strict mode, read: https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode

I recommend to disable strict mode as the development benefits are often outweighed by the inconveniences.

**Comment by scamden** [comment]
Ugh! I'm sorry! I could have sworn I checked this without strict mode as well! You are 100% right. 

Updated the example to remove strict mode and it no longer runs twice:
<img width="794" alt="Screenshot 2024-01-24 at 7 51 48 AM" src="https://github.com/mui/mui-x/assets/1128856/8372d9a9-7a82-4fde-ad23-1331a59b5c68">

**Comment by scamden** [comment]
Side note while were here. Looking at the stack it's spending a lot of time filtering and sorting. If we turn off filtering it doesn't seem to change that stack. Is it possible to cut out that processing if we do our own sorting and filtering already?

**Comment by romgrk** [comment]
The filtering & sorting flags are UI-only disables. You can open a new issue with a description of the issue & the same live example. It makes sense that there shouldn't be any cost for those features if they're not used when the grid is mounted.
