### ISSUE TITLE
[charts] `LineChart` color improvement

### ISSUE THREAD

**Issue by maykmayk** [mui/mui-x#11818]
### Summary

I want to colorize my chart with a color if the numberData is > 0 and with another is its below 0.
As today I can't do this (i think)

Here's the code:

```tsx
import React from "react";
import { LineChart } from "@mui/x-charts/LineChart";

function Momentum(props) {
    const data = props.data?.content?.momentum?.main?.data
    console.log(data)

    let minutes = []
    let values = []

    data?.map((moment, index) => {
        minutes.push(moment.minute)
        values.push(moment.value)
    })

    return (
        <div className="w-full flex flex-col rounded-lg py-4 bg-white brd gap-4">
            <div className="text-center font-medium text-base px-4">Match Momentum</div>
            <div className="brd05"></div>
            <div className="relative">
                {/* <div style={{ background: `linear-gradient(to bottom, ${props.colorData?.home} 0%, ${props.colorData?.home} 50%, ${props.colorData?.away} 50%, ${props.colorData?.away} 100%)` }}> */}
                    <LineChart
                        axisHighlight={{
                            x: "none", 
                            y: "none",
                        }}
                        xAxis={[{ data: minutes,
                            min: minutes[0],
                            max: minutes[minutes.length-1],
                            hideTooltip: true  }]}
                        series={[
                            {
                                data: values,
                                area: true,
                                stack: "total",
                                showMark: false,
                            },
                        ]}
                        height={200}
                        leftAxis={null}
                        bottomAxis={null}
                        margin={{
                            left: 30,
                            right: 30,
                            top: 20,
                            bottom: 20,
                        }}
                    />
                {/* </div> */}
                <div className=" absolute w-full bottom-3 pt-4 flex justify-center h-full">
                    <div className="border border-dashed border-gray-200 relative h-full" />
                </div>
                <div className=" absolute w-full bottom-3 px-4">
                    <div className="border border-dashed border-gray-200 relative w-full">
                        <div className="w-full right-0 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-base flex justify-between">
                            <div className="w-fit px-2 py-0.5 bg-white rounded-full font-bold">
                                0'
                            </div>
                            <div className="w-fit px-2 py-0.5 bg-white rounded-full font-bold">
                                HT
                            </div>
                            <div className="w-fit px-2 py-0.5 bg-white rounded-full font-bold">
                                FT
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Momentum
```

**Search keywords**: Color LineChart

**Comment by alexfauquette** [comment]
There is a trick based on the gradient. Recharts uses it: https://recharts.org/en-US/examples/AreaChartFillByValue

The complex part is to find the correct threshold. To do that, you can define a component that will use `useXScale()`. See [here for docs](https://mui.com/x/react-charts/components/#scales)

The component would look like


```jsx
function ColorSwich({ threshold, color1, color2, id }) {
	const scale = useYScale(); // You can provide the axis Id if you have multiple ones
	const off = scale(threshold);

	return <defs>
		<linearGradient id={id} x1="0" y1="0" x2="0" y2="1">
			<stop offset={off} stopColor={color1} stopOpacity={1} />
			<stop offset={off} stopColor={color2} stopOpacity={1} />
		</linearGradient>
	</defs>
}

function MyChart(){
	// ....
	return <LineChart sx={{
		"& .MUIAreaElement-root": {
			fill: 'url(#swhich-color-id)'
		}
	}}>
		<ColorSwhich color1='red' color2='green' threshold={0} id='swhich-color-id' />
	</LineChart>
}
```

**Comment by maykmayk** [comment]
Thank you for the reply @alexfauquette 

Since i'm using React I adapted your suggested code, but the problem seems to be that the gradient isn't even showind. in the debug console there is the defs part but the color isn't changing from the basic light blue.
I'll send the code, maybe you can help me furthermore :)))

`import React from "react";
import { LineChart, useYScale } from "@mui/x-charts";

function Momentum(props) {
	const data = props.data?.content?.momentum?.main?.data;
	console.log(data);

	let minutes = [];
	let values = [];

	data?.map((moment, index) => {
		minutes.push(moment.minute);
		values.push(moment.value);
	});

	function ColorSwitch({ threshold, color1, color2, id }) {
		const scale = useYScale();
		const off = scale(threshold);

		return (
		<defs>
			<linearGradient id={id} x1="0" y1="0" x2="0" y2="1">
			<stop offset="0%" stopColor={color1} stopOpacity={1} />
			<stop offset={off} stopColor={color1} stopOpacity={1} />
			<stop offset={off} stopColor={color2} stopOpacity={1} />
			<stop offset="100%" stopColor={color2} stopOpacity={1} />
			</linearGradient>
		</defs>
		);
	}

	return (
		<div className="w-full flex flex-col rounded-lg py-4 bg-white brd gap-4">
		<div className="text-center font-medium text-base px-4">Match Momentum</div>
		<div className="brd05"></div>
		<div className="h-32 md:h-64 relative">
			<LineChart
			axisHighlight={{
				x: "none",
				y: "none",
			}}
			xAxis={[
				{
				data: minutes,
				min: minutes[0],
				max: minutes[minutes.length - 1],
				hideTooltip: true,
				},
			]}
			series={[
				{
				data: values,
				area: true,
				stack: "total",
				showMark: false,
				},
			]}
			leftAxis={null}
			bottomAxis={null}
			margin={{
				left: 30,
				right: 30,
				top: 20,
				bottom: 20,
			}}
			sx={{
				"& .MUIAreaElement-root": {
				fill: "url(#swhich-color-id)",
				},
			}}
			>
			<ColorSwitch color1={props.colorData?.home} color2={props.colorData?.away} threshold={0} id="swhich-color-id" />
			</LineChart>
			<div className="absolute w-full bottom-3 md:bottom-6 pt-4 flex justify-center h-full">
			<div className="border border-dashed border-gray-200 relative h-full" />
			</div>
			<div className="absolute w-full bottom-3 md:bottom-6 px-4">
			<div className="border border-dashed border-gray-200 relative w-full">
				<div className="w-full right-0 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-base flex justify-between">
				<div className="w-fit px-2 py-0.5 bg-white rounded-full font-bold font-sm md:font-base">0'</div>
				<div className="w-fit px-2 py-0.5 bg-white rounded-full font-bold font-sm md:font-base">HT</div>
				<div className="w-fit px-2 py-0.5 bg-white rounded-full font-bold font-sm md:font-base">FT</div>
				</div>
			</div>
			</div>
		</div>
		</div>
	);
}

export default Momentum;
`

**Comment by maykmayk** [comment]
fixed:

import React, { useEffect, useRef, useState } from "react";
import {
	AreaChart,
	Area,
	XAxis,
	YAxis,
	Label,
	ReferenceLine,
	Tooltip
	
  } from "recharts";

function Momentum(props) {
	const [chartDimensions, setChartDimensions] = useState({ width: 800, height: 200 });
	const chartContainerRef = useRef(null);

	useEffect(() => {
		const updateDimensions = () => {
		if (chartContainerRef.current) {
			const { width, height } = chartContainerRef.current.getBoundingClientRect();
			setChartDimensions({ width, height });
		}
		};

		window.addEventListener("resize", updateDimensions);
		updateDimensions();
		return () => {
			window.removeEventListener("resize", updateDimensions);
		};
	}, [props.data]);

	const data = props.data?.content?.momentum?.main?.data;
	console.log(data);

	let minutes = [];
	let values = [];

	data?.map((moment, index) => {
		minutes.push(moment.minute);
		values.push(moment.value);
	});

	const gradientOffset = () => {
		const dataMax = Math.max(...values);
		const dataMin = Math.min(...values);

		if (dataMax <= 0) {
			return 0;
		}
		if (dataMin >= 0) {
			return 1;
		}

		return dataMax / (dataMax - dataMin);
	};

	const off = gradientOffset();

	return (
		<div className="w-full flex flex-col rounded-lg pt-4 bg-white brd gap-4">
			<div className="text-center font-medium text-base px-4">Match Momentum</div>
			<div className="brd05"></div>
			<div className="h-32 md:h-64 relative" ref={chartContainerRef}>
				<AreaChart width={chartDimensions.width} height={chartDimensions.height -20} data={data} margin={{ top: 0, right: 20, left: -30, bottom: -20}}>
					<XAxis dataKey={"minute"} stroke="#e8e8e8" strokeWidth={4} strokeDasharray="0.0001, 9.85704" strokeLinecap="round" tick={false}/>
					<YAxis strokeWidth={0} tick={false}/>
					<ReferenceLine x={45} stroke="#e8e8e8"
						strokeWidth={4}
						strokeDasharray="0.0001, 9.85704"
						strokeLinecap="round"
						label={{ position: "bottom",  value: "HT", fill: "#000", fontSize: 14, offset: -5 }}
					/>
					<ReferenceLine x={0}
						stroke="#fff"
						strokeWidth={0}
						label={{ position: "bottom", value: "0'",  fill: "#000",  fontSize: 14, offset: -5, }}
					/>
					<ReferenceLine x={90}
						stroke="#fff"
						strokeWidth={0}
						label={{ position: "bottom",  value: "FT", fill: "#000", fontSize: 14, offset: -5 }}
					/>
					<defs>
						<linearGradient id="splitColor" x1="0" y1="0" x2="0" y2="1">
							<stop offset={off} stopColor={props.colorData?.home} stopOpacity={1} />
							<stop offset={off} stopColor={props.colorData?.away} stopOpacity={1} />
						</linearGradient>
					</defs>
					<Area type="monotone" dataKey="value" strokeWidth={0} fill="url(#splitColor)" fillOpacity={1} />
				</AreaChart>
			</div>
		</div>
	);
}

export default Momentum;

**Comment by alexfauquette** [comment]
Your fix is to use another library 😅

I made a working example in https://github.com/mui/mui-x/pull/11824

The trick I did not well understood is that the `offset` you provide to `<stop />` needs to be a ratio. In the code I proposed before I used absolute coordinate which of course overflow the 0-1 range
