### ISSUE TITLE
[data grid] Styling for clickable row

### ISSUE THREAD

**Issue by Zasheus** [mui/mui-x#11819]
### The problem in depth

Hey there, I'm currently using onCellClick prop to do an action based on specific rows (e.g id === 3). I want to style these rows to make it more obvious that they are clickable, is there a CSS or column definition I can set for this?

I've tried setting a custom CSS class name based on the same conditions for if a row is clickable. However, I have lots of grids and would like to avoid having to set this manually each time.

Thanks

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: clickable
**Order ID**: 75414

**Comment by michelengelen** [comment]
Hey @Zasheus ... thanks for raising this issue.
There are multiple ways to do what you are trying to do.
I guess the easiest and most reusable way is [this approach](https://stackblitz.com/edit/react-se7nfe?file=Demo.tsx). 
Let me know if this suits your use-case. Thanks! 🙇🏼
