### ISSUE TITLE
DataGridPremium's column auto size property doesn't work without using setTimeout function

### ISSUE THREAD

**Issue by mlelyakan** [mui/mui-x#11828]
### The problem in depth

I'm using DataGridPremium and I'd like to set grid column's width auto. Alhough I used to autosizeOptions property grid columns doesn't fit regarding to their contents. But when I wrap the code which is apiRef.current.autosizeColumns(autosizeOptions); to the setTimeout function it works. How can I resolve that issue without using setTimeout function? Thanks for your support.

Here is my codes;

    import { DataGridPremium, useGridApiRef } from '@mui/x-data-grid-premium';
    import React, { useEffect, useState } from 'react';
    import { setVariantTableColumns, setVariantTableRows } from '../../data/variantTableRender';

    const autosizeOptions = {
        columns: ["SYNM"],
        includeHeaders: true,
        includeOutliers: true
    };

    export const VariantTable = ({ data }) => {
        const [variantColumns, setVariantColumns] = useState([]);
        const [variantRows, setVariantRows] = useState([]);
        const apiRef = useGridApiRef();

    useEffect(() => {
        if (data && data.Layout) {
            const oColumns = setVariantTableColumns(data.Layout); // I'm getting the colums definition from that function
            if (oColumns) {
                setVariantColumns(oColumns);
            }
        }
        if (data && data.Data) {
            const oRows = setVariantTableRows(data.Data);
            if (oRows) {
                setVariantRows(oRows);
            }
        }
    }, [data]);

    useEffect(() => {
        if (variantColumns.length && variantRows.length) {
            **If I'm not use setTimeout function, grid columns width doesn't auto fit**
            setTimeout(() => {
                apiRef.current.updateRows(variantRows);
                apiRef.current.autosizeColumns(autosizeOptions);
            }, 3000);
        }
    }, [variantColumns, variantRows]);

    return (
        variantColumns.length && variantRows.length &&
        <DataGridPremium
            apiRef={apiRef}
            rows={variantRows}
            columns={variantColumns}
            density="compact"
            autosizeOnMount={true}
            autosizeOptions={autosizeOptions}>
        </DataGridPremium>
    );
    };

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGridPremium, autosizeOptions
**Order ID**: 82606

**Comment by romgrk** [comment]
You need to use `setTimeout`, auto-sizing needs rows to be rendered to work, and react renders asynchronously. Note that you use both the `rows` prop and the API `updateRows` function. The `rows` prop does the row update first, then you're repeating the operation in the `setTimeout` handler. You should be using only one of them. You can also use `ReactDOM.flushSync` to force react to work synchronously.

https://mui.com/x/react-data-grid/column-dimensions/#autosizing-asynchronously
