### ISSUE TITLE
[pickers] clearable for DateTimePicker

### ISSUE THREAD

**Issue by rejetto** [mui/mui-x#11827]
### Summary

I see we have clearable on DateTimeField but not DateTimePicker.
I hope we can have it.
Thanks

### Motivation

I want to be able to easily clear the field, as it's optional in my use case.

**Search keywords**: clearable DateTimePicker

**Comment by rejetto** [comment]
I want to share with other people that you can get the same functionality with this configuration

    slotProps: {
        actionBar: { actions: ['clear', 'cancel', 'today', 'accept'] }
    }

**Comment by michelengelen** [comment]
Hey @rejetto ... thanks for providing the info yourself.
I will close this issue now since your initial question is solved.
Feel free to reopen if or create a new issue when you encounter more problems! Thanks! 🙇🏼

**Comment by LukasTy** [comment]
Hello, I just wanted to clarify that the `DateTImePicker` has the same `clearable` behavior just as [the `DatePicker`](https://mui.com/x/react-date-pickers/date-picker/#clearing-the-value).
I'll bring your focus to the fact that on the Picker components, we did not add a top-level prop, hence, to achieve clearable behavior you need to do the following (same as for the `DatePicker`):
```
slotProps={{
  field: { clearable: true },
}}
```
