### ISSUE TITLE
[Treeview] Expand all parent nodes when adding child node id to the defaultExpanded property

### ISSUE THREAD

**Issue by doorman02** [mui/mui-x#11850]
### Summary

Is it possible to set the defaultExpanded to a child node id and the TreeView will expand all parent nodes before the child?

### Motivation

Easier usage for child nodes functionality

**Search keywords**: TreeView, Child node, expand

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @doorman02 ... afaik this is currently only possible when you set the parent IDs to open by default up to the top.

You would have to generate the path of all opened parents up to the node that you want to have opened and pass that to the `defaultExpandedNodes` prop. It can be done with a pretty simple recursive function.

I have created a small example [here](https://stackblitz.com/edit/react-z5g2mf?file=Demo.tsx).

Let me know if you have further questions. Thanks! 🙇🏼
