### ISSUE TITLE
[question]  unable to override icon in `GridToolbarExport` DataGrid

### ISSUE THREAD

**Issue by tshougrakpam** [mui/mui-x#11868]
### Steps to reproduce

Link to live example: (required)

```
<GridToolbarExport
              componentsProps={{
                button: {
                  startIcon: (
                    <IconButton>
                      <DownloadIcon />
                    </IconButton>
                  )
                }
            }}
            />

```

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: GridToolBarExport, DataGridPro

**Comment by michelengelen** [comment]
Hey @tshougrakpam ... You have to use `slotProps` instead for this to work.
Here is a quick example of how to use it: [Custom Export Icon](https://stackblitz.com/edit/react-gdytsc?file=Demo.tsx)

And please add a reproduction example to your next issue. That makes it a lot easier for us to help you! Thanks! 🙇🏼
