### ISSUE TITLE
Add support for date-fns@3.x

### ISSUE THREAD

**Issue by gdams** [mui/mui-x#11864]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Install @mui/x-date-pickers
2. Install date-fns@3.x
3. Observe build error

### Current behavior

@mui/x-date-pickers only works with date-fns@2.x

### Expected behavior

@mui/x-date-pickers should be bumped to work with date-fns@3.x

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.3
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 121.0.6167.85
    Edge: 121.0.2277.83
    Safari: 17.3
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.29 
    @mui/core-downloads-tracker:  5.15.6 
    @mui/lab: ^5.0.0-alpha.97 => 5.0.0-alpha.158 
    @mui/material: ^5.15.6 => 5.15.6 
    @mui/private-theming:  5.15.6 
    @mui/styled-engine:  5.15.6 
    @mui/system:  5.15.6 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.6 
    @mui/x-data-grid: ^6.19.1 => 6.19.1 
    @mui/x-date-pickers: ^6.19.0 => 6.19.0 
    @types/react: ^18.2.48 => 18.2.48 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  5.3.3 

```
</details>

**Search keywords**: date-fns

**Comment by LukasTy** [comment]
Date-fns v3 is supported and it's usage is documented [here](https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns).
