### ISSUE TITLE
[data grid] Invalid license key watermark when rendering multiple versions of Data Grid in a react project in different places. 

### ISSUE THREAD

**Issue by soodaws** [mui/mui-x#11871]
### The problem in depth

We have a React project where we use data-grid-pro v4 which uses data-grid-license v4(configured as per mui docs i.e. using setLicenseKey(v4 key) at the top of the DataGrid component). 

But this react project also has a dependency which renders data-grid-pro v6 and uses data-grid-license v6 license(configured as per mui docs i.e. using setLicenseKey(v6 key) at the top of the DataGrid component). 

In both the project and in the dependency we have explicit versions of the data-grid and the license-key set to their correct versions - v4 and v6 respectively in package.jsons. 

All works okay in the UI up until we render in the UI the v6 data grid, after that all our data grid components(both v4 and v6) start complaining about `Invalid license key` - we see the watermark on all the tables. 

This indicates that the project has gotten confused about the license key versions. Could you recommend a workaround/way to avoid this confusion. Thanks!

### Your environment

From the primary react project  - 

```
npx: installed 2 in 1.47s

  System:
    OS: Linux 5.10 Amazon Linux 2
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 117.0.5938.132
  npmPackages:
    @emotion/react:  11.7.0 
    @emotion/styled:  10.3.0 
    @mui/private-theming:  5.14.14 
    @mui/styled-engine-sc:  5.10.1 
    @mui/styles:  5.4.4 
    @mui/types:  7.2.6 
    @mui/utils:  5.14.14 
    @mui/x-data-grid-pro:  4.0.0 
    @mui/x-license-pro:  4.0.0 
    @types/react:  17.0.62 
    react:  17.0.2 
    react-dom:  17.0.2 
    styled-components:  5.3.11 
    typescript: ^4.4.2 => 4.5.2 
```

**Search keywords**: Invalid license key
**Order ID**: 74999

**Comment by soodaws** [comment]
Also, missed to add - We have purchased separate license key for both the v4 and v6 versions - we own both the project and the dependency.

**Comment by soodaws** [comment]
Update: moving the `LicenseInfo.setLicenseKey(MUI4_LICENSE_KEY)` inside our project's v4 DataGrid component as opposed to calling it on the top of the file seems to have solved this.

**This works -** 

```
import {
  DataGridPro as MuiDataGrid,
  DataGridProProps as MuiDataGridProps,
  GridCellEditCommitParams as MuiGridCellEditCommitParams,
  GridCellParams as MuiGridCellParams
  useGridApiRef,
} from '@mui/x-data-grid-pro';

const DataGrid: FC<DataGridProps> = ({ columns: initialColumns, apiRef: incomingApiRef, ...props }) => {
// Calling it outside the component definition
  LicenseInfo.setLicenseKey(MUI4_LICENSE_KEY);

 }
```

**This doesn't -** 


```
import {
  DataGridPro as MuiDataGrid,
  DataGridProProps as MuiDataGridProps,
  GridCellEditCommitParams as MuiGridCellEditCommitParams,
  GridCellParams as MuiGridCellParams
  useGridApiRef,
} from '@mui/x-data-grid-pro';

// Calling it outside the component definition
LicenseInfo.setLicenseKey(MUI4_LICENSE_KEY);

const DataGrid: FC<DataGridProps> = ({ columns: initialColumns, apiRef: incomingApiRef, ...props }) => {


 }
```

Couple of follow up questions now - 

1. Does this seem like a safe way to address the problem(from a production standpoint)
2. Should we also move the call to setLicenseKey in the dependency inside it's v6 DataGrid component similar to the above. 

Really appreciate your help.

**Comment by michelengelen** [comment]
Hey @soodaws ... If I remember correctly the v6 license should cover the v4 data grid as well.

This is maybe also why the first approach you mentioned in your last comment works. 🤷🏼 

Could you try to add the licensing info for v6 to the wrapping component like described in the docs and check if that solves. Please remove the v4 license from the codebase.

In the meantime I will ask the team for more details!

**Comment by michelengelen** [comment]
@soodaws I have some more info.
`LicensInfo` is a singleton. Thats why it gets mixed up when used more than once.
On the other topic: Unfortunately you will have to upgrade the v4 grid to at least v5.11.0 when you have purchased your license after May 13, 2022, since we changed the signature of the key. Here is the related page in the docs: [License key installation](https://mui.com/x/introduction/licensing/#license-key-installation)

If you need help upgrading please feel free to reach out!

**Comment by soodaws** [comment]
Thanks @michelengelen for getting back!

1. Even though we placed an order after May, 2022, we specially got a license key for our v4, since the engineering cost to upgrading to v5 was high for us. 

2. `This is maybe also why the first approach you mentioned in your last comment works.` -> Could you please expand on how this actually worked from an engineering standpoint? Are you saying that moving the v4 key inside the component somehow gave the v6 key from the dependency a chance to override this v4 key and hence no problem happened?

**Comment by michelengelen** [comment]
Ok, thanks for checking and that additional info.

My colleague @cherniavskii did provide me with a solution that should work for you (and I did not know about). We do have a separate licensing component that is exported from the licensing package called `Unstable_LicenseInfoProvider`. If you wrap your `v6` grid with it and use the `v4` license on the rest of the app (to support the `v4` grid) this should do the trick.

The only requirement is that you have to use `>=v6.10.2` for this to work.

Here is a short example of how that would look like: [Sandbox](https://codesandbox.io/p/sandbox/vibrant-hill-pyddpt?file=%2Fsrc%2FDemo.tsx%3A29%2C7)

Does that help you?

**Comment by soodaws** [comment]
Thanks, some clarifications on the sandbox - 

1. `If you wrap your v6 grid with it` -> So I'm assuming the sandbox is representing the v6 component. This line in the code, what is the invalid license key in this context - the v6 key?
```
// Invalid license key
LicenseInfo.setLicenseKey("YOUR_LICENSE_KEY");
```

2. In this code block in sandbox - what is the value of the key field, the v6 or v4? If it's v6, then both for point 1 and point 2, the key value is the same I'm assuming?
 
 ```
<Unstable_LicenseInfoProvider
      info={{
        key: "d0382b4582e75e6483d380786978c543Tz0wMDAwMCxFPTE3MzgzMjM4ODk0NzAsUz1wcmVtaXVtLExNPXN1YnNjcmlwdGlvbixLVj0y",
      }}
```

**Comment by michelengelen** [comment]
OK, so in that sandbox this should be the v4 ...

```tsx
LicenseInfo.setLicenseKey("YOUR_V4_LICENSE_KEY");
```

... and this the v6 key ...

```tsx
<Unstable_LicenseInfoProvider
   info={{
     key: "YOUR_V6_LICENSE_KEY",
   }}
/>
```

Then it should work

**Comment by soodaws** [comment]
Thanks for your prompt responses. Much appreciated! I will try this out. 

It would be helpful to know if my earlier fix  i.e. just moving the setLicenseKey inside the wrapped v4 dataGrid component - which seems to fix the issue - is it possible to get thoughts from your team on how safe that fix can be?

**Comment by michelengelen** [comment]
Sure @cherniavskii could you check if that's also a viable (and safe) approach?

**Comment by soodaws** [comment]
Edit: I had to put the license key inside both the wrapped component definitions - for v4 wrapped as well as v6 wrapped for it to work both ways. Seems to be working on local, going to test in production. But would love to hear @cherniavskii 's thoughts about this approach. 

Also, The sandbox approach did not work. `Unstable_LicenseInfoProvider` is not an exported member from `data-grid-premium`. We are using version `x-data-grid-premium-6.2.0`, bit still no luck.

**Comment by michelengelen** [comment]
Hey @soodaws I might have a solution for you. Could you send me your Key to michel@mui.com ? Thanks! 🙇🏼

**Comment by soodaws** [comment]
Sure, sent. Thanks!

**Comment by michelengelen** [comment]
Pushing this onto the board to think about a more profound licensing solution.

**Comment by soodaws** [comment]
Thanks Michel for your effort. 

1. We can live with the console error as long as the feature doesn't break in production. 
2. Our codebase makes extensive use of the DataGrid component - think about 50 different renders. 
 - Can you help me roughly estimate the time it would take for us to update from v4 to v5 - assuming that v5 and v6 will work well together. Will they? We would like to take this approach if the effort will be lower. 
- Can you help me roughly estimate the time it would take for us to update from v4 to v6 if moving to v5 won't solve it.

Thanks.  

I know

**Comment by michelengelen** [comment]
Hey @soodaws no problem. :D
To quickly answer your questions:

> 1. We can live with the console error as long as the feature doesn't break in production.

It won't break in production.

> 2. Our codebase makes extensive use of the DataGrid component - think about 50 different renders.

WOW! Impressive!
 
> * Can you help me roughly estimate the time it would take for us to update from v4 to v5 - assuming that v5 and v6 will work well together. Will they? We would like to take this approach if the effort will be lower.

I did ask our experts on this and am waiting for feedback. This is not something we typically do so it's hard to estimate for us as well. Also there is a bit of a blind spot, since implementations can be very specific and proprietary code doesn't help either! :D

> * Can you help me roughly estimate the time it would take for us to update from v4 to v6 if moving to v5 won't solve it.

We will do our best to estimate this as well. The same implications from above apply here as well though! :D

**Comment by michelengelen** [comment]
Hello again @soodaws ... Unfortunately it is not possible for us to estimate the effort to upgrade. This is mainly due to the fact that we do not know the implementation.

I did fiddle around with the LicenseProvider example a bit and the best solution (without upgrading the v4 grid) is to use the `Unstable_LicenseProvider` that is being exported from the `@mui/x-license-pro` package. The only thing you need to do is upgrade the version on your v6 grid to at least `>=6.10.2`. That should be doable without any changes to the existing code.

[LicenseProvider example](https://codesandbox.io/p/sandbox/pedantic-colden-m4v7pd?file=%2Fsrc%2FDemo.tsx%3A60%2C19)

This will get rid of the console errors as well.

--- 

If you want to try upgrading we do have a [migration guide](https://v5.mui.com/x/react-data-grid/migration-v4/) in the docs for both majors (`v4`->`v5` and `v5`->`v6`).

**Comment by michelengelen** [comment]
@soodaws did we solve your issue with this?

**Comment by soodaws** [comment]
Hey @michelengelen we went with the keeping keys inside components approach for now. We'll know in some time if it works properly in production or not. If it doesn't we're going to try this solution.

Many thanks for your help!

**Comment by MBilalShafi** [comment]
Sure @soodaws, please keep us posted!

**Comment by soodaws** [comment]
Ended up deploying to production with the previous strategy i.e. calling setLicenseKey within the each datagrid wrapper component definition as opposed to the top level of the datagrid wrapper file. 

Works fine. No console errors.

**Comment by michelengelen** [comment]
> Works fine. No console errors.

Good to hear ... I will close this for now. Please feel free to reopen when issues arise again. Thanks! 🙇🏼
