### ISSUE TITLE
[DataGridPremium] Print causes an error with Row Grouping

### ISSUE THREAD

**Issue by wladimir-k-m** [mui/mui-x#11872]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/muidatagridpremiumrowgroupingprinterror-4q7y8t?file=%2Fsrc%2FRowGroupingDataGrid.tsx

Steps:
1. Open the sandbox.
2. Click on "Export" -> "Print" -> "Cancel"
3. Get an Error: "MUI: The data grid component requires all rows to have a unique `id` property."

### Current behavior

Mui throws an error.

### Expected behavior

🤔

### Your environment

Tested browsers: Chrome, Firefox latest versions

**Search keywords**: RowGrouping, Export, Print

**Comment by michelengelen** [comment]
Hey @wladimir-k-m ... thanks for raising this issue. I can confirm that this is a bug!

If I recall correctly in order to print we render a simplified version of the current grid. This is probably where the error appears.

@cherniavskii could you have a look?

**Comment by cherniavskii** [comment]
Regression caused by https://github.com/mui/mui-x/pull/10084
