### ISSUE TITLE
[charts] Reverse order of chart axis

### ISSUE THREAD

**Issue by NerdCowboy** [mui/mui-x#11890]
### Summary

I have 2 horizontal bar charts side by side. For the right chart, I'd like to reverse the x-axis order to better help the eye flow down the page.

Here's what I'm trying to achieve:
![image](https://github.com/mui/mui-x/assets/757960/87146257-81b3-409c-a26d-b1d2b25b9350)

I can move the Y-axis to the right-hand side easily via the `rightAxis` prop, but it ends up being awkward since the x-axis still starts 0 at the left edge.
![image](https://github.com/mui/mui-x/assets/757960/e25aefe7-bb4c-4878-9123-6cd85465ec2e)

On other charting libraries, there's a `reverse` prop or something similar, but I'm not seeing anything that would allow me to do that here.the 

### Examples

[Nivo Bar chart - `reverse`](https://nivo.rocks/bar/#base-reverse)
[ChartJs `reverse`](https://www.chartjs.org/docs/latest/axes/cartesian/category.html#common-options-to-all-axes) 

**Search keywords**: axis, order, bar chart, reverse
**Order ID**: 70251

**Comment by michelengelen** [comment]
@alexfauquette Could you help here?

**Comment by alexfauquette** [comment]
Sounds to be a legitimate idea. I thaught using `xAxis={[{ min: 50, max: 0}]}` could do the job, but the `<ChartsBarPlot />` makes some assumption about the values order that are broken by this new behavior.

Then I opened #11899 to fix it. I stilll need to experiment a bit to make sure no other component would be broken with `reverse` set to true. And I need to document it
