### ISSUE TITLE
[data grid] range styling is being added to cells inside of the range instead of just the edges of the range

### ISSUE THREAD

**Issue by RyleySill93** [mui/mui-x#11891]
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/cell-selection/#customize-range-styling

<img width="1193" alt="image" src="https://github.com/mui/mui-x/assets/20671872/e118be25-9a0c-4be7-a1d7-64fcdaeadb8d">

### Current behavior

MuiDataGrid-cell--rangeBottom is being applied to a cell in the middle of the range. 

### Expected behavior

MuiDataGrid-cell--rangeBottom should only be applied to cells in the last row of the range.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid range styling
**Order ID**: 75803

**Comment by michelengelen** [comment]
Hey @RyleySill93 could you provide detailed steps you took to get to this bug?
If I try it is always correct:

<img width="2270" alt="Screenshot 2024-02-01 at 12 06 38" src="https://github.com/mui/mui-x/assets/32863416/6fcde474-82ce-4698-86bf-075cdcadf371">

Thanks! 🙇🏼

**Comment by RyleySill93** [comment]
@michelengelen I'm just clicking on that link and highlighting a range of cells using click and drag or shift + arrow keys. Tried with Chrome, Safari, and Firefox

https://github.com/mui/mui-x/assets/20671872/3359dbdf-8853-48d3-aed9-42399f296c71

**Comment by michelengelen** [comment]
Oh, yes ... now I can reproduce as well  ... it happens with all of the range classes.
Thanks for raising this issue. 🙇🏼 We will have a look.

**Comment by gitstart** [comment]
@michelengelen @RyleySill93 we would like to pick this up

**Comment by louisaaron** [comment]
We're experiencing this as well and are planning to roll out our grid-based feature in the next two weeks. @michelengelen are you able to provide an estimated timeline for this one? If beyond 2-3 weeks we'll probably go ahead and create our own internal fix. Thanks so much!

Support Key/Order ID: 85118

**Comment by romgrk** [comment]
Which grid version will you be using? Can you use the v7 releases? This should be straightforward to fix this week.

**Comment by louisaaron** [comment]
Thanks guys!
