### ISSUE TITLE
[pickers] convert moment month in datePicker to Farsi

### ISSUE THREAD

**Issue by naserrasoulii** [mui/mui-x#11896]
### Steps to reproduce

Hello  , 
im use datepicker and momentjs in mui-datepicker and convert locale to "fa" but use this not convert month to persian for example show "Bahman" Instead "بهمن" 
Consider this, the conversion is done but in English instead of Farsi

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datepicker

**Comment by michelengelen** [comment]
Hey @naserrasoulii ... could you provide a minimal working example of the issue you are facing in a codesandbox or stackblitz? That way its a lot easier for us to help you! Thanks! 🙇🏼 

cc @LukasTy
