### ISSUE TITLE
[data grid] FilterToolbar RemovaAll button does not have a reason onFilterModelChange

### ISSUE THREAD

**Issue by mantassadauskas** [mui/mui-x#11907]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/zealous-murdock-5mv8ld?file=%2Fsrc%2Fdemo.tsx%3A22%2C35
Steps:
1. Add filter
2. Press remove all button
3. Check console log

### Current behavior

`api.reason` is `undefined`

### Expected behavior

`api.reason` is defined as something, e.g. `removeAllFilters`, or whatever else, like with other actions.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: onFilterModelChange reason removalAll

**Comment by michelengelen** [comment]
Hey @mantassadauskas and thanks for raising this issue.
The fix for this can actually pretty straightforward.
Here is a diff that represents the necessary changes:

```diff
diff --git a/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx b/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx
index 6560dd9d1..1c1848407 100644
--- a/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx
+++ b/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx
@@ -212,7 +212,10 @@ const GridFilterPanel = React.forwardRef<HTMLDivElement, GridFilterPanelProps>(
         apiRef.current.deleteFilterItem(validFilters[0]);
         return apiRef.current.hideFilterPanel();
       }
-      return apiRef.current.setFilterModel({ ...filterModel, items: readOnlyFilters });
+      return apiRef.current.setFilterModel(
+        { ...filterModel, items: readOnlyFilters },
+        'deleteFilterItems',
+      );
     }, [apiRef, readOnlyFilters, filterModel, validFilters]);

     React.useEffect(() => {
diff --git a/packages/grid/x-data-grid/src/models/events/gridEventLookup.ts b/packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
index 9b26b4a94..8cc60d01c 100644
--- a/packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
+++ b/packages/grid/x-data-grid/src/models/events/gridEventLookup.ts
@@ -365,6 +365,7 @@ export interface GridControlledStateReasonLookup {
     | 'upsertFilterItem'
     | 'upsertFilterItems'
     | 'deleteFilterItem'
+    | 'deleteFilterItems'
     | 'changeLogicOperator'
     | 'restoreState';
   pagination: 'setPaginationModel' | 'stateRestorePreProcessing';
```

`deleteFilterItem` will provide the reason already, so there is no change needed for that one.

**Comment by shaharyar-shamshi** [comment]
@michelengelen I would like to pick up this issue but I want to propose the new filter type removeFilterItems instead of yours deleteFilterItems because I think it can be a bit confusing having both deleteFilterItem and deleteFilterItems as the options.

can you provide your input

```js
export interface GridControlledStateReasonLookup {
  filter:
    | 'upsertFilterItem'
    | 'upsertFilterItems'
    | 'deleteFilterItem'
    | 'changeLogicOperator'
    | 'restoreState'
    | 'removeFilterItems';
  pagination: 'setPaginationModel' | 'stateRestorePreProcessing';
}
```

**Comment by michelengelen** [comment]
> @michelengelen I would like to pick up this issue but I want to propose the new filter type removeAllFilterItems instead of yours deleteFilterItems because I think it can be a bit confusing and might be error prone having both deleteFilterItem and deleteFilterItems as the options.
> 
> 
> 
> can you provide your input
> 
> 
> 
> ```js
> 
> export interface GridControlledStateReasonLookup {
> 
>   filter:
> 
>     | 'upsertFilterItem'
> 
>     | 'upsertFilterItems'
> 
>     | 'deleteFilterItem'
> 
>     | 'changeLogicOperator'
> 
>     | 'restoreState'
> 
>     | 'removeAllFilterItems';
> 
>   pagination: 'setPaginationModel' | 'stateRestorePreProcessing';
> 
> }
> 
> ```

Works for me. Objections @cherniavskii ?
