### ISSUE TITLE
[charts] Add an option for an axis grid

### ISSUE THREAD

**Issue by Sozialarchiv** [mui/mui-x#11928]
### Summary

It would be nice if there would be an option to add an horizontal an vertical grid (gray lines in picture) to the axis:

![grafik](https://github.com/mui/mui-x/assets/17063042/e70caece-2252-436d-86e1-652364bbbfed)

I already did it as customized component. But it would be nice to have it as simple option.

**Search keywords**: axis grid

**Comment by michelengelen** [comment]
Thanks for raising this as well @Sozialarchiv ... @alexfauquette is working on providing a grid component already. I am not sure if he has already opened up a PR for that though. 

It's great that you have solved it for your use-case already. Looking nice! 👍🏼 
Thanks for your feedback! We really appreciate that!

**Comment by michelengelen** [comment]
Also loosely related to #11710

**Comment by Sozialarchiv** [comment]
> Also loosely related to https://github.com/mui/mui-x/issues/11710

On my workaround I had similar problems like #11710. 

First I also added the CartesianAxis as child of BarChart.

But since children in BarChart are always inserted into the SVG after BarPlot, the lines are above the chart as described in #11710.

https://github.com/mui/mui-x/blob/next/packages/x-charts/src/BarChart/BarChart.tsx#L183

![grafik](https://github.com/mui/mui-x/assets/17063042/f433d666-a50c-43ea-8466-414f65ab6a08)

I solved it by using customized component.

```tsx
<ResponsiveChartContainer  height={300}  xAxis={...} series={...}>
  <ChartsLegend />
  <CartesianAxis />
  <ChartsAxis />
  <ChartsTooltip />
  <BarPlot />
</ResponsiveChartContainer>
```

The second challenge (also mentioned in #11710) was the useTick/getTicknumber are private and cannot be exported.

In solved it like that:

```tsx
function CartesianAxis() {
    // Get the drawing area bounding box
    const { left, top, width, height } = useDrawingArea();

    // Get the two scale
    const yAxisScale = useYScale() as ScaleLinear<any, any>;
    const range = yAxisScale.range()

    const yOrigin = yAxisScale(0);
    const tickNumber = Math.floor(Math.abs(range[1] - range[0]) / 50)
    const yTicks = yAxisScale.ticks(tickNumber)
    return (
        <React.Fragment>
            {yTicks.map((value) => (
                <StyledPath
                    key={value}
                    d={`M ${left} ${yAxisScale(value)} l ${width} 0`}
                    color="secondary"
                />
            ))}
            <StyledPath d={`M ${left} ${yOrigin} l ${width} 0`} color="primary" />
        </React.Fragment>
    );
}
```

The example in docs https://mui.com/x/react-charts/components/#scales is helpful. 

However, it would be even more helpful if xAxis and yAxis were not both with pre-defined arrays.  

```
const xTicks = [-2, -1, 1, 2, 3];
const yTicks = [-2, -1, 1, 2, 3, 4, 5];
```

So if you could make an axis with tick intervals or an second example with tick intervals the doc would be more informative.

But of course a grid option for the axis component would be even better.

**Comment by alexfauquette** [comment]
The grid is on the road

https://github.com/mui/mui-x/pull/11034

**Comment by flaviendelangle** [comment]
Should we close this issue as a duplicate?

**Comment by alexfauquette** [comment]
@Sozialarchiv Feel free to subscript the to PR to get updates

**Comment by Sozialarchiv** [comment]
Thank you very much for the good and fast answer.
I will look forward to the feature.
I will create an pro account to honor your great work.
