### ISSUE TITLE
[data grid] Multiple subcomponents expand on expanding one of duplicate rows

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11929]
My data grid table has duplicate rows, all with detailpanelcontent subcomponents. When I expand one row to view the detailpanelcontent subcomponent, all the duplicate rows expand with it. It may be happening because all the rows are same. Is there a way to expand only one of the multiple duplicate rows instead of expanding all of them?

**Search keywords**:

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by kumar-pratiyush** [comment]
you can refer this sandbox https://codesandbox.io/p/sandbox/mystifying-tree-pdw4rh?file=%2Fsrc%2FDemo.tsx

**Comment by michelengelen** [comment]
It seems your sandbox is private. Could you please make it public? Thanks! 🙇🏼

**Comment by michelengelen** [comment]
Ok, I already had a hunch about this, but this confirms it. The `id` of a row needs to be unique. There is a lot of stuff going on in the background that needs this, so it will potentially break some things when 2 (or more) rows have the same `id`.

The expansion is also based on the `id` and therefore it will always open up all of the rows it finds with that `id`.

What you can do is to assign duplicate rows new `id`s

```
import {randomId} from '@mui/x-data-grid-generator';
const rows = [
  ...,
  {
    id: 2,
    // data for row 2
  },
  {
    id: randomId(),
    // copied data for row 2
  },
  ...
];
```

**Comment by kumar-pratiyush** [comment]
Is there any other approach in which we can keep the id same? It is necessary

**Comment by michelengelen** [comment]
One thing that comes to mind is giving the rows `id`s for the grid and a separate `orderId` (or whatever the property is that comes from your database). It is important to note that the `id` is being used internally for row operations.

Here is an example of that approach: [Custom row id](https://codesandbox.io/p/sandbox/mystifying-keldysh-gqgn9y?file=%2Fsrc%2FDemo.tsx%3A97%2C37)

**Comment by kumar-pratiyush** [comment]
The repo seems to be private

**Comment by michelengelen** [comment]
> The repo seems to be private

Sry about that ... here is a new [link](https://codesandbox.io/p/sandbox/mystifying-keldysh-gqgn9y?file=%2Fsrc%2FDemo.tsx%3A97%2C37&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls8qierw0006356h1p0b2d2v%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls8qierw0002356hboqtcn76%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls8qierw0003356hgkymj40s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls8qierw0005356hnypxwcbl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls8qierw0002356hboqtcn76%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls8qierw0001356htcrpmabs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls8wqr1v00023b6ikuxsmfvs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A97%252C%2522startColumn%2522%253A37%252C%2522endLineNumber%2522%253A97%252C%2522endColumn%2522%253A37%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls8qierw0002356hboqtcn76%2522%252C%2522activeTabId%2522%253A%2522cls8wqr1v00023b6ikuxsmfvs%2522%257D%252C%2522cls8qierw0005356hnypxwcbl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls8qierw0004356hhevkb44q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls8qierw0005356hnypxwcbl%2522%252C%2522activeTabId%2522%253A%2522cls8qierw0004356hhevkb44q%2522%257D%252C%2522cls8qierw0003356hgkymj40s%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls8qierw0003356hgkymj40s%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by kumar-pratiyush** [comment]
Thank you for your help
