### ISSUE TITLE
[question] How to set quickFilter value to DataGridPro

### ISSUE THREAD

**Issue by saeonny** [mui/mui-x#11931]
### The problem in depth

I created SearchBar outside of the table,
and i want to setquickSearch value with the input from the searchbox to multiple datagrids

i used apiRef but it only works with one datagrid 
How to apply quicksearchValue into multiple datagrids ?
[example](https://codesandbox.io/p/sandbox/quickfilteringgrid-material-demo-forked-lrdwgn?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls45b17o0007356hr2xqu7js%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls45b17n0003356hhjd782mz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls45b17n0004356hz7lszrkw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls45b17n0006356hyhgrvpk4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls45b17n0003356hhjd782mz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls45b17n0002356hwvgxl7bq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A29%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A35%252C%2522endColumn%2522%253A16%257D%255D%257D%255D%252C%2522id%2522%253A%2522cls45b17n0003356hhjd782mz%2522%252C%2522activeTabId%2522%253A%2522cls45b17n0002356hwvgxl7bq%2522%257D%252C%2522cls45b17n0006356hyhgrvpk4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls45b17n0005356htrtvrnkx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls45b17n0006356hyhgrvpk4%2522%252C%2522activeTabId%2522%253A%2522cls45b17n0005356htrtvrnkx%2522%257D%252C%2522cls45b17n0004356hz7lszrkw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls45b17n0004356hz7lszrkw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: setQuickFilterValue
**Order ID**: 83106

**Comment by michelengelen** [comment]
You can accomplish this without using the `apiRef` by just setting the `filterModel`. Here is a short example on who to do this: [Quickfilter on multiple grids](https://codesandbox.io/p/sandbox/quickfilteringgrid-material-demo-forked-s724ps?file=%2Fdemo.tsx%3A40%2C18)

Side note: The `apiRef` needs to be unique for each instance of the grid. If you absolutely need it on both instances you would need to create 2 separate refs and pass them to each of the instances.

**Comment by saeonny** [comment]
Hi actually i cant access the codesandbox: the quickfilter on multiple grids
