### ISSUE TITLE
[TreeView] Multiple empty children trigger expandable

### ISSUE THREAD

**Issue by swalker326** [mui/mui-x#11948]
https://github.com/mui/mui-x/blob/094abbc2ece29e41f50935783af25b4e7ab1838a/packages/x-tree-view/src/TreeItem/TreeItem.tsx#L190C3-L190C84

Repro: https://stackblitz.com/edit/stackblitz-starters-rbhnuk?file=src/App.tsx

In react having a single empty array as a child, creates a `children` array of `chiildren: []` so if you were to do something like:

```ts 
{children?.map(ch => <TreeItem {...ch} />} 
```

the children prop in the parent component would be `children: []` which would set expandable to false and not render the ExpandIcon

however if you do that twice say you have multiple nested arrays you want to render:

```ts
<TreeItem>
  {children?.map(ch => <TreeItem {...ch} />} 
  // Some different kind of objects that would require a wrapper components
  {differentChildren?.map(ch => <CustomTreeItem {...ch} />} 
</TreeItem>
```

The resulting children prop on the component is: `children: [Array(0),Array(0)]` which sets expandable to true, Rendering the icon on an empty TreeItem

Kind of a niche use case, but the exact one I've hit. 

Something like this could be added to the linked section:

```ts

 const isExpandable = (children) => {
    if (Array.isArray(children)) {
      // Check if the array is non-empty, or if it contains any non-empty array
      return (
        children.length > 0 &&
        children.some((child) => (Array.isArray(child) ? child.length > 0 : true))
      );
    } else {
      // Non-array, truthy values are considered expandable
      return Boolean(children);
    }
 };
const expandable = isExpandable(children);
```

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @swalker326 and thanks for raising this issue.
It is definitely a bug and not an easy one to catch! Thanks a lot!
Since this is a fairly easy fix I will make this a "good first issue".

Objections @flaviendelangle ?

**Comment by flaviendelangle** [comment]
We could indeed improve the `expandable` detection mechanism :ok_hand:

**Comment by michelengelen** [comment]
Its fairly easy to setup and run the package. We have everything documented in our [Contribution doc](https://github.com/mui/material-ui/blob/master/CONTRIBUTING.md)

⚠️ Please note that the doc mentions `pnpm` (mui-core already migrated), but mui-x did not yet migrate to it, so please keep using `yarn` for now.

If you need any help please feel free to reach out!

**Comment by flaviendelangle** [comment]
I would suggest to test with the react component, not just the utility function
That way we can make sure that it's consistent in scenarios like:

```tsx
<TreeItem>
  <React.Fragment />
</TreeItem>
```
