### ISSUE TITLE
[data grid] Remove the exports for license utils from the data grid folder

### ISSUE THREAD

**Issue by DanailH** [mui/mui-x#11942]
Currently, we can import the license utils from both the license package and from the data grid packages. It would be good to remove the exports from the data grid package so that there is only one place you can import the utils.

**Comment by oliviertassinari** [comment]
Should we maybe start with a deprecation and why v8 for a breaking change?

**Comment by LukasTy** [comment]
Good point.
At the very least, we'd have to deprecate it on v6 if we want to rush the removal. 🤔
