### ISSUE TITLE
[DataGridPremium] Fill the available height of the viewport

### ISSUE THREAD

**Issue by moyicat** [mui/mui-x#11950]
### The problem in depth

Similar request to https://github.com/mui/mui-x/issues/5451 opening a new one since that one seems to be quite dated.

In the example provided here: https://github.com/mui/mui-x/issues/5451#issuecomment-1180733326 the `.MuiDataGrid-root` element actually has a height of 3909px, so it's not actually respecting the given height of the parent container, but taking all the pixels of the page and push the page to become longer. And the scroll bar belongs to the entire page, so when you scroll, the column header get scrolled away.

<img width="517" alt="image" src="https://github.com/mui/mui-x/assets/2023450/a7389343-cdd2-4d11-81f8-6565b91fd805">

---

Now, compare that to this: https://codesandbox.io/p/sandbox/datagridprodemo-demo-mui-x-forked-gdjzy9?file=%2Fdemo.tsx
If I pass in a definitive height for the outer element to be `350`, the actual `.MuiDataGrid-root` now gets a `348px` in height, and the scroll bar is _inside_ the component, not on the entire page.
<img width="2307" alt="image" src="https://github.com/mui/mui-x/assets/2023450/237081bc-eadd-41b3-8fc9-9c9bef3d8407">

---

Is there away to have the MUI X component take the remaining height of the viewpoint, and limit itself without me passing in the absolute `px` or `vh` or a complicated calculation to its parent div?

In other words, is there a way to make this work: https://codesandbox.io/p/sandbox/datagridprodemo-demo-mui-x-forked-fnw8gt?file=%2Fdemo.tsx%3A23%2C14
So the line of text stays, the MUI X component takes 100vh - the height of the text, and has scroll bar _within_ it.

Let me know if I made my point clear enough. Thanks!

### Your environment

Browser: Chrome Version 121.0.6167.139 (Official Build) (arm64)

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.1.2
  Binaries:
    Node: 20.8.0 - /opt/homebrew/bin/node
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 121.0.6167.139
    Edge: Not Found
    Safari: 17.1.2
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0 
    @emotion/styled: ^11.10.0 => 11.10.0 
    @mui/base:  5.0.0-beta.27 
    @mui/core-downloads-tracker:  5.15.0 
    @mui/icons-material: ^5.15.0 => 5.15.0 
    @mui/joy: ^5.0.0-beta.18 => 5.0.0-beta.18 
    @mui/lab: ^5.0.0-alpha.156 => 5.0.0-alpha.156 
    @mui/material: ^5.15.0 => 5.15.0 
    @mui/private-theming:  5.15.0 
    @mui/styled-engine:  5.15.0 
    @mui/system:  5.15.0 
    @mui/types:  7.2.11 
    @mui/utils:  5.15.0 
    @mui/x-data-grid: ^6.18.6 => 6.18.6 
    @mui/x-data-grid-premium: ^6.18.6 => 6.18.6 
    @mui/x-data-grid-pro: ^6.18.6 => 6.18.6 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^17.0.37 => 17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.5.4 => 4.5.5 
```
</details>

**Search keywords**: autoHeight
**Order ID**: 80607

**Comment by michelengelen** [comment]
Hey @moyicat ... this is absolutely possible: [Example](https://codesandbox.io/p/sandbox/datagridprodemo-demo-mui-x-forked-xzhfzv?file=%2Fdemo.tsx%3A42%2C1)

1. Set `display: flex` on the wrapping container (`#root`)
2. Wrap the content you want to align in a `<Stack />`
3. add the props `flex={1}` and `sx={{ minHeight: 0 }}` (for the flex quirkiness)
4. Enjoy! :D

Anything else we can help you with? Just open a new issue!

Thanks! 🙇🏼

**Comment by moyicat** [comment]
Hey @michelengelen thanks for the quick response, the codesandbox example you shared is not public tho -- can you make it public?

**Comment by michelengelen** [comment]
Sry ... here is the updated link: [Example](https://codesandbox.io/p/sandbox/datagridprodemo-demo-mui-x-forked-xzhfzv?file=%2Fdemo.tsx%3A42%2C1)

**Comment by moyicat** [comment]
Hey @michelengelen thanks for the answer. While the example works, if I put the structure inside a `<Stack>` or a `<Box>` again, it immediately breaks.

Reading the code it makes me think that it will only work if from the element all the way to the body:
- Box needs to have height "100%"
- Stack needs to have min-height: 0

That's not really doable given the table can embedded anywhere in our application and it's hard to guarantee every `<div>` in the tree has these attributes.

Am I understanding it correctly? Is there a clean way to do it?

**Comment by michelengelen** [comment]
> Hey @michelengelen thanks for the answer. While the example works, if I put the structure inside a `<Stack>` or a `<Box>` again, it immediately breaks.
> 
> Reading the code it makes me think that it will only work if from the element all the way to the body:
> 
> * Box needs to have height "100%"
> * Stack needs to have min-height: 0

This is not entirely correct. The grid in itself has a flexible layout, which means it will collapse when the container does not "spread" for itself.

> That's not really doable given the table can embedded anywhere in our application and it's hard to guarantee every `<div>` in the tree has these attributes.

I am not sure why that should pose a problem. Could you give me an example?

> Am I understanding it correctly? Is there a clean way to do it?
> 
> Example how wrapping it up in any structure will break it again: https://codesandbox.io/p/sandbox/datagridprodemo-demo-mui-x-forked-s2zz25?file=%2Fdemo.tsx

Yes, that example will break again, since both `Stack` and `Box` are not limited by the viewport as per your initial request. But this would happen for **any** other big component as well.

Here you can see that even a very long text will make the container overflow the viewport:

<img width="2484" alt="Screenshot 2024-02-09 at 09 13 05" src="https://github.com/mui/mui-x/assets/32863416/14341a00-06d0-4454-a2f6-af5cdb829c0b">
