### ISSUE TITLE
[data grid] Apply different styles to grouping row when it is expanded and collapsed

### ISSUE THREAD

**Issue by yehudamakarov** [mui/mui-x#11952]
Although we have `.MuiDataGridPremium-row--detailPanelExpanded` to apply to the row when its detail panel is expanded...

I want to apply styles to **_grouping rows_** when they are open.

I also want to apply styles to the entire group only when it is expanded. (Imagine adding a round border and margins to the top and bottom when the group is expanded)

How can I go about doing this?

Is there a way to target this?

Maybe this is something that should be added if it is not there yet?

**Search keywords**:

**Comment by michelengelen** [comment]
It is possible with a bit of a hack using the `getRowClassName` prop on the data grid.

Here is an example of it: [custom grouped row class](https://codesandbox.io/p/sandbox/twilight-voice-5tqxdf?file=%2Fsrc%2FDemo.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsa6uvaw00073b6hauudjcnv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsa6uvaw00033b6hx7y0wynu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsa6uvaw00043b6hyfm3kdxi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsa6uvaw00063b6hvabrjwb2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsa6uvaw00033b6hx7y0wynu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsa6uvaw00023b6hgg7udm06%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clsa6uvaw00033b6hx7y0wynu%2522%252C%2522activeTabId%2522%253A%2522clsa6uvaw00023b6hgg7udm06%2522%257D%252C%2522clsa6uvaw00063b6hvabrjwb2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsa6uvaw00053b6h9v3c7t5z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsa6uvaw00063b6hvabrjwb2%2522%252C%2522activeTabId%2522%253A%2522clsa6uvaw00053b6h9v3c7t5z%2522%257D%252C%2522clsa6uvaw00043b6hyfm3kdxi%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsa6uvaw00043b6hyfm3kdxi%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

we are currently lacking a `onRowChildrenExpanded` handler. @cherniavskii do we plan on adding something like this in the future?

**Comment by yehudamakarov** [comment]
Amazing.

This example didn’t show the grouping; does the status change depending on the group expansion?

Will try soon.

**Comment by yehudamakarov** [comment]
ok way simpler than what I had going on, thank you. 
(thanks for showing me `&&&`)

(is `treeData` just to enable row grouping for this example?)

stellar!

**Comment by michelengelen** [comment]
> (is `treeData` just to enable row grouping for this example?)

Yes, that's enabling the row grouping!

Glad I could help! 🙇🏼
