### ISSUE TITLE
[data grid] Hide detail panel toggle when no subcomponent

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11968]
I want to show the subcomponent expand option or the detail panel toggle option only when there is data for subcomponent. Right now I can only hide the toggle button but the column is still there. How do I hide the entire column?

**Search keywords**:

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

For this case could you provide at least some screenshots with the desired behavior? The description you gave is not clear enough for us to help you!

Thank you! 🙇🏼
