### ISSUE TITLE
[DateTimePicker] Wrong tab indicator size

### ISSUE THREAD

**Issue by pascal-mormin** [mui/mui-x#11964]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   4.0.0-alpha.3  |
| material-ui          |  4.6.1       |

## Steps to reproduce

It seems there is a problem with TabIndicator size on DateTimePicker when opening dialog. I got this problem on my project but i can reproduce it on [material-ui pickers site's demo](https://v4-0-0-alpha-3.material-ui-pickers.dev/demo/datetime-picker).

1- Go to DateTime Picker basic usage example on the website 
2- Open the dialog

The tab indicator (120px) don't take all the first tab size (160px).
Switching to the hour size (2nd tab), tab indicator takes all the size.
Switching to the first tab tab indicator now takes all the size (160px)

## Expected behavior

Indicator takes all the tab width

## Actual behavior

Indicator dont take all the tab width when opening dialog.

## Live example

Try it on basic usage : [material-ui pickers site's demo](https://v4-0-0-alpha-3.material-ui-pickers.dev/demo/datetime-picker)

**Comment by croraf** [comment]
@oliviertassinari So this should be solved in MUI-5.0 and newer versions? And not solved in MUI-4?
