### ISSUE TITLE
[data grid] Filter is inconsistent with numbers

### ISSUE THREAD

**Issue by kumar-pratiyush** [mui/mui-x#11970]
When applying filter on a column that contains numbers but is of type string by default, it behaves weirdly. It filters the row only when the complete number is entered but it should start filtering as soon as the digits are entered

**Search keywords**:

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
