### ISSUE TITLE
[data grid] Hide column icon-separator for column resizable='false'

### ISSUE THREAD

**Issue by niralivasoya** [mui/mui-x#12017]
### Steps to reproduce

This is how normally icon separators look like when we set disableColumnResize={false}. That means it allows you to resize the column, and this is how it looks when we hover over the header:

<img width="828" alt="image" src="https://github.com/mui/mui-x/assets/32123446/9a0c8966-56bb-487d-b0de-a9e185562da3">

### Current behavior

I want to allow the resize column only for the first column and disable the resizable to others. So, it is not allowed to resize other columns except the first one. 

I want to hide the iron separator for other columns (where I set resizable to false). Ideally, we don't need an icon separator for those columns. 

### Expected behavior

How can I only show the icon separator for the resizable columns and hide it for others? How can I set the style? Any suggestions?

Thanks.

### Context

This is the demo link:

https://codesandbox.io/p/sandbox/column-resizable-78jz77

### Your environment

This is my current environment:
<img width="378" alt="image" src="https://github.com/mui/mui-x/assets/32123446/eb3f9078-95d0-4b5d-8b32-d38524edecde">

**Search keywords**: data-grid, column resize, hide icon speerator

**Comment by michelengelen** [comment]
Hey @niralivasoya 
This is relatively easy to do:

```
import * as React from 'react';
import { DataGridPro, GridColDef, gridClasses } from '@mui/x-data-grid-pro';

const rows = [
  {
    id: 1,
    username: '@MUI',
    age: 20,
  },
];

const getHeaderClassName: GridColDef['headerClassName'] = (params) => {
  console.log('params', params);
  return !params.colDef.resizable ? 'hide-resize-handle' : '';
};

const columns: GridColDef[] = [
  {
    field: 'id',
  },
  {
    field: 'username',
    width: 125,
    minWidth: 150,
    maxWidth: 200,
    resizable: false,
  },
  { field: 'age', resizable: false },
].map((column) => ({ ...column, headerClassName: getHeaderClassName }));

export default function ColumnSizingGrid() {
  return (
    <div style={{ height: 250, width: '100%' }}>
      <DataGridPro
        columns={columns}
        rows={rows}
        sx={{
          [`& .${gridClasses.columnHeader}.hide-resize-handle`]: {
            [`.${gridClasses.columnSeparator}`]: {
              display: 'none',
            },
          },
        }}
      />
    </div>
  );
}

```
You can use the `headerClassName` property on a `ColDef` to apply a className based on a param.
There is also a page in our docs about this: [Styling column headers](https://mui.com/x/react-data-grid/style/#styling-column-headers)

Let me know if you need anything else.
Thanks! 🙇🏼

**Comment by michelengelen** [comment]
@cherniavskii should we add a recipe for this?

**Comment by michelengelen** [comment]
Hey @niralivasoya ... while writing the recipe I found an easier way to do this:

```tsx
import * as React from 'react';
import { DataGridPro, GridColDef, gridClasses } from '@mui/x-data-grid-pro';

const rows = [
  {
    id: 1,
    username: '@MUI',
    age: 20,
  },
];

const columns: GridColDef[] = [
  {
    field: 'id',
  },
  {
    field: 'username',
    width: 125,
    minWidth: 150,
    maxWidth: 200,
    resizable: false,
  },
  { field: 'age', resizable: false },
];

export default function ColumnHeaderHideSeparator() {
  return (
    <div style={{ height: 250, width: '100%' }}>
      <DataGridPro
        columns={columns}
        rows={rows}
        sx={{
          [`& .${gridClasses.columnSeparator}`]: {
            [`&:not(.${gridClasses['columnSeparator--resizable']})`]: {
              display: 'none',
            },
          },
        }}
      />
    </div>
  );
}
```

I am still putting this into the recipe section, but wanted to notify you here as well.

**Comment by onejeet** [comment]
Simplest solution...

```
 '& .MuiDataGrid-columnSeparator:not(.MuiDataGrid-columnSeparator--resizable)': {
            display: 'none !important',
          },
```
