### ISSUE TITLE
[pickers] Console error about non-boolean attribute 'focused' when using `DatePicker` / `DateTimePicker` for custom columns in `DataGrid`

### ISSUE THREAD

**Issue by wlee-vendelux** [mui/mui-x#12018]
### The problem in depth

- [Go to the section on Custom Columns in the docs](https://mui.com/x/react-data-grid/custom-columns/#date-pickers)
- [Click on Edit in CodeSandbox](https://codesandbox.io/s/l66n48?file=/src/Demo.tsx)
- Double click any date or datetime cell to start edit mode
- Press the calendar icon to open `DatePicker` or `DateTimePicker`
- Check dev console for error

```
Warning: Received `true` for a non-boolean attribute `focused`.
If you want to write it to the DOM, pass a string instead: focused="true" or focused={value.toString()}.
```

**Search keywords**: datepicker datetimepicker datagrid non-boolean focused
**Order ID**: 69589

**Comment by michelengelen** [comment]
Thanks for raising this @wlee-vendelux
I am not sure where exactly this attribute comes from @LukasTy ... From a quick investigation I guess it is this line that add the `focused` attribute to the DOM:
https://github.com/mui/mui-x/blob/971a48d1b1ff25f718a48693d783f9744f83b001/packages/x-date-pickers/src/PickersTextField/PickersTextField.tsx#L120
Could it be that it gets passed down all the way to the `InputBase` component through props-spreading? 🤔

**Comment by flaviendelangle** [comment]
@michelengelen the component you linked does not exist in v6 and is not used by default in v7, it can't be the source of the problem

**Comment by michelengelen** [comment]
> @michelengelen the component you linked does not exist in v6 and is not used by default in v7, it can't be the source of the problem

It is not? I am sorry! I will investigate this tomorrow a bit deeper!

**Comment by flaviendelangle** [comment]
In v6 we are using `@mui/material/TextField` :+1:

**Comment by michelengelen** [comment]
Ok, I found the issue. The problem was that the WrappedGridEditDateInput got passed the `focused` prop, but it does not exist on `InputBase` which is being used in the demo.

You can change this by just removing `focused` from the props.

```tsx
function WrappedGridEditDateInput(props: TextFieldProps) {
  const { InputProps, focused, ...other } = props;
  return <GridEditDateInput fullWidth {...InputProps} {...(other as InputBaseProps)} />;
}
```

@flaviendelangle Thanks for pointing that out. I searched in the wrong place! 🙇🏼
