### ISSUE TITLE
Selecting minutes from clock breaks the DateTimePicker with format prop passed as "MM/DD/YYYY HH:mm"

### ISSUE THREAD

**Issue by dhruvmaindola227** [mui/mui-x#12034]
### Steps to reproduce

https://stackblitz.com/edit/react-wdgpib?file=Demo.tsx

Demo link

Steps:
1. use viewRenderers
2. pass format prop as MM/DD/YYYY HH:mm (breaking even for hh:mm)
3. select minutes from the clock

![image](https://github.com/mui/mui-x/assets/80943305/f25d28d6-e35d-46cb-a71e-268472964c18)

### Current behavior

Upon selecting minutes from the clock, the DateTimePicker breaks saying cannot read properties of undefined 'contentType'.
I tried with various formats. HH:mm:ss/ HH:mm/hh:mm/hh:mm:ss.

I tried with hh:mm a, then it works normally. I can tell there might be some usage issue on my end in this case. If anyone can guide me on this and why this is happening it will be of really a lot of help.

### Context

I had written a wrapper over the DateTimePicker and there was this use case to support 24 hour format but it was breaking.

### Your environment

date pickers version : **6.19.4**

**Search keywords**: minute selection, datetimepicker, format, contentType

**Comment by LukasTy** [comment]
Thank you for creating this issue @dhruvmaindola227 🙏 
Based on your approach, you seem to need a DateTimePicker with a 24-hour clock.
To force such behavior and avoid it depending on the user's locale, please set `ampm={false}`.
You include `ss` in the format, maybe you want the seconds view as well?
If that's the case, feel free to override the default `views` prop.
```tsx
views={['day', 'hours', 'minutes', 'seconds']}
```

Does that help you resolve your use case? 🤔
