### ISSUE TITLE
issue with grid cell selection and pagination

### ISSUE THREAD

**Issue by kasherburn** [mui/mui-x#12039]
### The problem in depth

I have added pagination to my grid with page size options 5,10,25 

<img width="461" alt="Screenshot 2024-02-12 at 10 49 03" src="https://github.com/mui/mui-x/assets/50017978/39c69740-7399-4938-a7ec-8fd6d7135fab">

<img width="610" alt="Screenshot 2024-02-12 at 10 50 30" src="https://github.com/mui/mui-x/assets/50017978/0d1bc997-724e-484f-b30b-e517cfe223b8">

whenever i click into the final row of any page except the first i get this error and the view breaks

helpers.js:88 Uncaught TypeError: Cannot destructure property 'id' of 'visibleRows.rows[(rowIndex + 1)]' as it is undefined.
    at useGridCellSelection.js:394:1
    at useGridPipeProcessing.js:92:1

any tips on how to resolve?

### Your environment

<details>
  <summary>Google Chrome Version 121.0.6167.160 (Official Build) (arm64)</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: grid cell selection
**Order ID**: 76498

**Comment by michelengelen** [comment]
Hi @kasherburn ,

Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

In the meantime I will try and look for the issue with a basic template!

**Comment by kasherburn** [comment]
H @michelengelen I have found its coming from this prop: unstable_cellSelection. I know this is an experimental feature. Has it been reported by other users?

**Comment by MBilalShafi** [comment]
Hello @kasherburn, I can't find a similar issue reported by another issue.

Did you manage to get a minimal reproduction test case for the issue you are facing as requested by @michelengelen? Please attach it here if you do or try to reproduce one in a live example for the team to debug the problem better.

Thanks

**Comment by kasherburn** [comment]
Apologies, I was a couple of versions behind. Updated the version and the bug has gone. @MBilalShafi @michelengelen will close this.
