### ISSUE TITLE
[data grid] Add Tooltip in column ONLY when '...' are displayed in the column

### ISSUE THREAD

**Issue by Aberkati** [mui/mui-x#12045]
### The problem in depth

I use x-data-grid-premium and I want to add Tooltip in every column that have a big string (a truncated text with 3 dots) but it not works, I've tried to make a condition in each column's string length but when i resize the column the tooltip is already there.

I want to add tooltip only when colulmn displayed '...' , but when I resize the column I want to hide tooltip when I hover tho column

### Your environment

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD    
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (120.0.2210.167)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.7
    @mui/core-downloads-tracker:  5.14.0
    @mui/icons-material: ^5.11.16 => 5.14.0
    @mui/material: ^5.12.1 => 5.14.0
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/system:  5.14.0
    @mui/types:  7.2.4
    @mui/utils:  5.13.7
    @mui/x-data-grid:  6.10.0
    @mui/x-data-grid-premium: ^6.10.0 => 6.10.0
    @mui/x-data-grid-pro:  6.10.0
    @mui/x-license-pro: ^6.10.0 => 6.10.0
    @types/react:  18.2.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0

**Search keywords**: DataGridPremium
**Order ID**: 66242

**Comment by michelengelen** [comment]
Hi @Aberkati,

Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
