### ISSUE TITLE
[data grid] Scroll restoration

### ISSUE THREAD

**Issue by marcpachecog** [mui/mui-x#12044]
### Summary

When utilizing the Datagrid with virtualization, it would greatly enhance the user experience to incorporate scroll restoration functionality. Currently, if a user navigates away from the page after clicking on a row, and then returns, they expect the Datagrid to maintain the same scroll position as before.

### Motivation

The absence of scroll restoration leads to a disorienting user experience, as users expect to seamlessly resume their interaction with the `DataGrid` upon returning to the page. Without scroll restoration, users may need to manually scroll to locate the previously selected row, resulting in frustration and inefficiency.

**Search keywords**: scroll restoration
**Order ID**: 77729

**Comment by michelengelen** [comment]
Hey @marcpachecog we do have the ability to scroll to certain indexes. There is an example in the docs: [Scrolling](https://mui.com/x/react-data-grid/scrolling/)

Or does this use-case not satisfy your needs? Let us know and we would love to help (ideally with a minimal reproduction in stackblitz or codesandbox)
