### ISSUE TITLE
[pickers] DateTimeRangePicker `disableFuture` disables Time in the Past

### ISSUE THREAD

**Issue by MarcusKuehn** [mui/mui-x#12048]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/quizzical-mclaren-2jd2gp

Steps:
1. Select date in the past.
2. Try to Select Time in the future.

### Current behavior

Not being able to select Time.

### Expected behavior

Being able to select all times for days that are in the past.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DateTimeRangePicker, disableFuture

**Order ID**: 85157

**Comment by MarcusKuehn** [comment]
Hello @LukasTy, unfortunately that does not solve my issue. Iam unsure whether you could access my CodeSandBox, because maybe it was private. Maybe I need to clarify my Problem with an example. 

Assume that today is 15.2.2024 14:00, now i want to select the 1.1.2024 13:00 as the start date. That is possible. But if I want to select the 1.1.2024 16:00, its not possible because the times after 14:00 are disabled. This also applies to the second date selection field.

**Comment by LukasTy** [comment]
Yes, I wasn't able to view the codesandbox initially.
Thank you for confirming the problem and sorry for not spotting it initially. 🙈 🙏 
The issue is clear and needs to be fixed. 👌

**Comment by shaharyar-shamshi** [comment]
@LukasTy I was looking into this issue and I found probable reason for this bug.

https://github.com/mui/mui-x/blob/0cd3b4f63afa8f4e3d4afd016a3e76d5b11d58b5/packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx#L233

over here we are matching the only time of past date with time of current date which obviously will disable the time of the date which is after current time.

proper logic should be 

```js
 if (
          disableFuture &&
          utils.getDate(valueToCheck) === utils.getDate(now) &&
          isAfter(valueToCheck, now)
        ) {
          return false;
        }
```

**Comment by shaharyar-shamshi** [comment]
@LukasTy are we proceeding with disableIgnoringDatePartForTimeValidation props or should we fix this issue

**Comment by shaharyar-shamshi** [comment]
@LukasTy if you can check the PR also confirm whether we should proceed to fix this or use disableIgnoringDatePartForTimeValidation prop

**Comment by shaharyar-shamshi** [comment]
@LukasTy if you can kindly check the PR also confirm whether we should proceed to fix this or use disableIgnoringDatePartForTimeValidation prop

**Comment by LukasTy** [comment]
@shaharyar-shamshi Thank you for being interested in solving this issue! 🙏 
Sorry for taking so long to reply, I was busy trying to finalize something else before the release. 🙈 

After doing some exploration and discovering https://github.com/mui/mui-x/issues/8520, it does not seem that your proposed solution is the correct one. 🤔 
If you don't mind, I'll take care of this one. 😉 
At the same time, it feels like we need to add the tests that were omitted with the initial DateTImeRangePicker implementation. 🙈

**Comment by shaharyar-shamshi** [comment]
> @shaharyar-shamshi Thank you for being interested in solving this issue! 🙏 Sorry for taking so long to reply, I was busy trying to finalize something else before the release. 🙈
> 
> After doing some exploration and discovering #8520, it does not seem that your proposed solution is the correct one. 🤔 If you don't mind, I'll take care of this one. 😉 At the same time, it feels like we need to add the tests that were omitted with the initial DateTImeRangePicker implementation. 🙈

Ohh no worries I was also assuming that  the proposed solution might not cover all cases.Do let me know if you need any help with the test cases I can help in writing the test cases and providing maximum coverage
