### ISSUE TITLE
[data grid] How to make scroll to row work in conjunction with expand detail panel 

### ISSUE THREAD

**Issue by 7ruth** [mui/mui-x#12053]
### The problem in depth

I am trying to make the row that is being expanded to scroll to the top of the table (top: 0 position), so the expanded detail panel takes up maximum amount of space in the table. 

I got scroll to correct row working without an issues, however when I put it inside a callback (onDetailPanelExpandedRowIdsChange) the scrolling seem to no longer work. I am assume propagation of the event stops somewhere but I am not enough of an expert or maybe there is a better callback to achieve the desired effect. 

Here is a codesandbox with an attempt: https://codesandbox.io/p/sandbox/scrollexpand-c7z3nk

If you press the scroll button at the top, it works fine. I also put the same scroll mechanism in to onDetailPanelExpandedRowIdsChange for a different row and it seems to no longer produce the desired effect. 

Guidance and feedback is appreciated

### Your environment

<details>

```
Browser:
    Brave
 System:
    OS: macOS 13.5
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 121.0.6167.160
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: ^11.7.1 => 11.10.4
    @emotion/styled: ^11.6.0 => 11.10.4
    @mui/base:  5.0.0-alpha.99
    @mui/core-downloads-tracker:  5.11.0
    @mui/icons-material: ^5.2.5 => 5.10.6
    @mui/lab: ^5.0.0-alpha.70 => 5.0.0-alpha.101
    @mui/material: ^5.2.6 => 5.10.7
    @mui/private-theming:  5.11.0
    @mui/styled-engine:  5.11.0
    @mui/styles: ^5.2.3 => 5.10.7
    @mui/system:  5.11.0
    @mui/types:  7.2.12
    @mui/utils:  5.15.3
    @mui/x-data-grid: ^5.17.8 => 5.17.9
    @mui/x-data-grid-generator: ^6.18.6 => 6.18.6
    @mui/x-data-grid-premium: ^5.17.9 => 5.17.9
    @mui/x-data-grid-pro:  5.17.9
    @mui/x-date-pickers: ^5.0.3 => 5.0.3
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.21
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.2.0 => 5.3.6
```
</details>

**Search keywords**: datagrid, expand, detail panel, scroll, scrollToIndex, getScrollPosition, gridPaginatedVisibleSortedGridRowEntriesSelector, scrollTo
**Order ID**: 12849

**Comment by MBilalShafi** [comment]
It's not working because `onDetailPanelExpandedRowIdsChange` is never getting fired. This event handler corresponds to the [master detail ](https://next.mui.com/x/react-data-grid/master-detail/)panels and not row-grouping rows. If you want to target this on the row expansion change, you can bind to the `rowExpansionChange` event that is thrown by the grid whenever a row is expanded or collapsed.

Here is the modified sandbox where I can see it working with the row expansion and collapse: https://codesandbox.io/p/sandbox/scrollexpand-forked-ycv9hc?file=%2Fdemo.tsx%3A38%2C5, let me know if you are looking for a similar result.

**Sidenote:** I can see that you are still using v5 of the Data Grid, I'd appreciate you upgrading to the latest [stable v6](https://mui.com/x/react-data-grid) or the [upcoming v7](https://next.mui.com/x/react-data-grid) to get the ton of performance improvements, bug fixes, and new amazing features. If you are facing any difficulties in the migration process, let me know and I'll try to assist you as much as I can.

Thank You!

**Comment by 7ruth** [comment]
Hello, sorry to bring this back. Previous modification to the sandbox with apiref.current.subscribeEvent was useful nudge in what seems the right direction but my sandbox wasn't initially set up to replicate my use case (sorry about that). I actually need the event to fire when 'detailPanel' is expanded. Looks like current event ("rowExpansionChange") doesn't fire when DetailPanelContent is expanded. 

Modified and updated codebox is here: https://codesandbox.io/p/sandbox/scrollexpand-forked-67q68h

Could you please suggest the correct event to use? (I couldn't find the correct even in the list of available events in 'gridEventLookup') 

Thank you!

**Comment by MBilalShafi** [comment]
Thanks for the explanation.

Would something like this work for you in that case: https://codesandbox.io/p/sandbox/scrollexpand-forked-kwwr76?file=%2Fdemo.tsx%3A17%2C9-17%2C20 ?

We have to use `setTimeout` to delay the execution of `scrollToIndexes` until the next render for it to work as expected.

**Comment by 7ruth** [comment]
Works great thank you for all your help!

**Comment by MBilalShafi** [comment]
Great, I'll close this issue in that case!

**Comment by 7ruth** [comment]
@MBilalShafi Sorry to keep re-opening this one up. I've added sort & filtering to columns. When index of sorted view isn't strictly sequential, the scrollTo doesn't to work. Is there a way to get a new index from sorter view using onFilterModelChange or some similar way? 

updated codebox with an example: https://codesandbox.io/p/sandbox/scrollexpand-forked-kwwr76?file=%2Fdemo.tsx%3A52%2C9-54%2C11

Steps to replicate the issue:
1. Click on Title column to sort in the opposite way from default
2. Click on first row "Aquaman" to expand it
3. Notice how scrollTo now throws up half way down the list due to Aquaman's original index being 23

Is there a way to ether make it scroll based on something other then index or a way to get new indexes after sorting and filtering?

Thank you for all your help so far.

**Comment by MBilalShafi** [comment]
Hey @7ruth, you could use the `gridSortedRowIdsSelector` to get the sequence of sorted rows and then find the corresponding index to scroll to.

I've tried to do that in this example: https://codesandbox.io/p/sandbox/scrollexpand-forked-kwwr76?file=%2Fdemo.tsx%3A39%2C32-39%2C56

Let me know if it solves the concern. 🙂

**Comment by 7ruth** [comment]
Works great, thank you for all your help on this request, wouldn't be able to get it done without your expert guidance!
