### ISSUE TITLE
Inline CSS Issue

### ISSUE THREAD

**Issue by rishab090** [mui/mui-x#12054]
### Summary

In our organization we are using @mui/x-data-grid for showing table data. Our VAPT team told to remove the 'unsafe-inline' directive in style-src header. After removing the 'unsafe-inline', it's not working and even after adding nonce value to <DataGrid />
component the issue is still persisted. Provide an option to remove all inline css. 

### Examples

```html
<div
      class="MuiDataGrid-columnHeader MuiDataGrid-columnHeader--sortable MuiDataGrid-withBorderColor customHeader"
      role="columnheader"
      tabindex="0"
      aria-colindex="1"
      aria-sort="none"
      aria-label="Sr. No."
      data-field="id"
      style="
        height: 56px;
        width: 60px;
        min-width: 60px;
        max-width: 60px;
       ">
```

Here the style come bydefault there should be a way to remove all inline-style so we can remove the 'unsafe-inline' in csp.

### Motivation

Provide a option or a prop to DataGrid disable inline-css.
eg. 
```jsx
<DataGrid inlineCSS={false} />
```

**Search keywords**: Inline CSS Issue, CSP Issue
**Order ID**: 111

**Comment by romgrk** [comment]
We use inline styles in a lot of places to set dimensions on elements. Using inline styles is the only way to make it work in some cases, for example dynamic row height. Considering that the risks for inline styles are very limited, I don't think we should provide that option.

**Comment by rishab090** [comment]
@romgrk  Thank You for the information. I'll connect with VAPT team regarding this.
