### ISSUE TITLE
[data grid] Editing Stops working when we apply alternate row coloring as per your styling example

### ISSUE THREAD

**Issue by fwaseem** [mui/mui-x#12051]
### Steps to reproduce

Link to live example: (required)

Steps:
1. We are using Premium Data Grid.
2. Open https://codesandbox.io/p/sandbox/infallible-firefly-gc6cgm?file=%2Fsrc%2FDemo.js
3. Please see the attached picture to see which demo i am talking about
![Bug](https://github.com/mui/mui-x/assets/101302385/afe2ad97-b6c7-4b11-934e-f48a6e0495db)

4.  Replace DataGrid with DataGridPremium
5. Double Click on any cell you will see cell editing in not working
6. Same behavior is with StripedRow demo in the same styling section

### Current behavior

Cell or Row Editing is not working after row background color in DataGridPremium.. Your demo is with simple community version.. it is working with this.. but premium version has some issue

### Expected behavior

Cell or Row Editing should work after row background color in DataGridPremium

### Context

..... 

### Your environment

Windows 11
Chrome lastes version

**Search keywords**: Data Grid Premium Row/Cell Editing
**Order ID**: 83914

**Comment by MBilalShafi** [comment]
@fwaseem Thank you for using the MUI Data Grid.

You should pass `editable: true` to the `useDemoData` hook to get column definitions with the editable flag set.
Here's a working example: https://codesandbox.io/p/sandbox/xenodochial-hellman-787fln?file=%2Fsrc%2FDemo.js%3A122%2C20

**Comment by fwaseem** [comment]
MBilalShafi.. Have you tried it with '@mui/x-data-grid-premium' (as per my original request). We are passing editable to required columns, but it is not working.

**Comment by fwaseem** [comment]
> @fwaseem Thank you for using the MUI Data Grid.
> 
> You should pass `editable: true` to the `useDemoData` hook to get column definitions with the editable flag set. Here's a working example: https://codesandbox.io/p/sandbox/xenodochial-hellman-787fln?file=%2Fsrc%2FDemo.js%3A122%2C20

Bilal.. Have you tried it with '@mui/x-data-grid-premium' (as per my original question). We are passing editable to required columns but it is not working.

**Comment by michelengelen** [comment]
@fwaseem it is working with the Premium Data Grid as well. 
Here is the [updated demo](https://codesandbox.io/p/sandbox/ancient-sun-gyr333) from @MBilalShafi 

If you could provide us with a minimal live example of your specific implementation we would be able to help you with that. I will reopen this, so you can provide us with one if you like! Thanks! 🙇🏼
