### ISSUE TITLE
What is the latest version I should be able to access with my license?

### ISSUE THREAD

**Issue by rfsmart-cgray** [mui/mui-x#12064]
### The problem in depth

We purchased a MUI X Pro license on June 3, 2022, which gave us access to v5.12.0.  Before the license expired, v6.6.0 was released.  Our license is not working for that version, and I would expect it would given the perpetual licensing model and maintenance and support.  Am I misunderstanding how it should work?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.3636.0), Chromium (121.0.2277.112)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.30
    @mui/core-downloads-tracker:  5.15.9
    @mui/icons-material: ^5.14.3 => 5.14.3
    @mui/lab: ^5.0.0-alpha.159 => 5.0.0-alpha.159
    @mui/material: ^5.15.7 => 5.15.9
    @mui/private-theming:  5.15.3
    @mui/styled-engine:  5.15.3
    @mui/system: ^5.15.7 => 5.15.9
    @mui/types:  7.2.12
    @mui/utils:  5.15.9
    @mui/x-data-grid:  6.1.0
    @mui/x-data-grid-pro: 6.1.0 => 6.1.0
    @mui/x-license-pro:  6.0.4
    @types/react: ^18.0.28 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.3.3 => 5.3.3
```
</details>

**Search keywords**: license upgrade v6
**Order ID**: 45096

**Comment by michelengelen** [comment]
Hey @rfsmart-cgray it seems like you should be able to use `v6.6.0` with your license. I would kindly ask you to open a support ticket for this [here](https://support.mui.com/hc/en-us/requests/new?tf_360023797420=mui_x). Thanks! 🙇🏼
