### ISSUE TITLE
Date Picker Size

### ISSUE THREAD

**Issue by XIAOAOAARON** [mui/mui-x#12060]
### Summary

Date Picker is not familiar with Size

### Examples

![image](https://github.com/mui/material-ui/assets/34054781/ae639bc5-5ea9-47c7-832a-7e05fa5e8efd)

**Search keywords**: Date Picker Size

**Search keywords**:

**Comment by LukasTy** [comment]
@XIAOAOAARON The Date Picker components do not have every prop from all the nested components exposed at top-level.
You can find all the available props on the [relevant API doc](https://mui.com/x/api/date-pickers/desktop-date-picker/#props).
In case of the `size` prop, I take it that you are looking into changing the size of the rendered `TextField`, in such case, please [check this documentation](https://mui.com/x/react-date-pickers/custom-field/#customize-the-textfield).
