### ISSUE TITLE
[pickers] popup jumps to the top left after selection if custom TextField slot is given

### ISSUE THREAD

**Issue by anthonyma94** [mui/mui-x#12063]
### Steps to reproduce

Link to live example: (required)
[Codesandbox](https://codesandbox.io/p/sandbox/cocky-haze-kx2gdw?file=%2Fsrc%2FApp.tsx%3A11%2C56&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsm4d4yh00062a66gcx8hxof%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsm4d4yh00022a66lcwvuvk4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsm4d4yh00032a66i6kukbwi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsm4d4yh00052a66fenujflo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsm4d4yh00022a66lcwvuvk4%2522%253A%257B%2522id%2522%253A%2522clsm4d4yh00022a66lcwvuvk4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsm4r8mg00022a66npoz9zln%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A56%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A56%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsm4r8mg00022a66npoz9zln%2522%257D%252C%2522clsm4d4yh00052a66fenujflo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsm4d4yh00042a66y6dap0ga%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsm4d4yh00052a66fenujflo%2522%252C%2522activeTabId%2522%253A%2522clsm4d4yh00042a66y6dap0ga%2522%257D%252C%2522clsm4d4yh00032a66i6kukbwi%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsm4d4yh00032a66i6kukbwi%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Create a DateTimePicker with a custom TextField slot
2. Click the UI to change date

### Current behavior

When using a custom TextField slot, the date selection box jumps to the top left after the first click.

### Expected behavior

Date selection box should stay as is.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 20.2.0 - /usr/local/bin/node
    npm: 9.6.6 - /usr/local/bin/npm
    pnpm: 8.6.1 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-alpha.116 
    @mui/core-downloads-tracker:  5.15.7 
    @mui/icons-material: ^5.14.18 => 5.15.7 
    @mui/lab: 5.0.0-alpha.118 => 5.0.0-alpha.118 
    @mui/material: ^5.14.18 => 5.15.7 
    @mui/private-theming:  5.15.7 
    @mui/styled-engine:  5.15.7 
    @mui/system:  5.15.7 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.7 
    @mui/x-date-pickers: ^6.19.4 => 6.19.4 
    @types/react: 18.2.24 => 18.2.24 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.3.3 => 5.3.3 
```
</details>

**Search keywords**: slot, TextField, DateTimePicker

**Comment by michelengelen** [comment]
This happens because the dialog losses the ref. Using a custom field is not as easy as just passing in a different component. We do have examples on our docs on how to use [custom fields](https://next.mui.com/x/react-date-pickers/custom-field/#using-another-input).

The example with the JoyUI field should be a good guide to add a material TextField.

@LukasTy should we maybe add recipes for material as well?

**Comment by LukasTy** [comment]
@anthonyma94 Please remember to [always pass a reference](https://mui.com/x/react-date-pickers/custom-components/#recommended-usage) to the slots property instead of creating an inline component.
It will force the picker to be remounted after every change.
