### ISSUE TITLE
[pickers] Enhancing User Experience: Introducing Month and Year Selection in Date-Pickers

### ISSUE THREAD

**Issue by bruns6077** [mui/mui-x#12075]
### Steps to reproduce

Link to live example: [Livedemo](https://mm4dfr.csb.app/)

**This feature should be reflected on all pickers which work with dates**

Steps:
1.  Open the DateRangePicker
2. Try to change the current month or the year

### Current behavior

Currently we can not change the current month or date at the pickers.

### Expected behavior

I would expect if i click on the Month to choose a month from a list.
I would expect if i click on the Year to choose a year from a list.

### Context

Choosing months or dates can be very important for users.

**Search keywords**: datepicker,timepicker,daterangepicker,picker,bug,ui,ux,month selection, day selection

**Comment by flaviendelangle** [comment]
Duplicates #4995

If I mis-understood and this issue does not cover your issue, feel free to tell me and I'll re-open it :+1:

**Comment by bruns6077** [comment]
> Duplicates #4995
> 
> If I mis-understood and this issue does not cover your issue, feel free to tell me and I'll re-open it 👍

This covers month selection, not month and year selection, sometimes the year can also bei really relevant to the user

**Comment by flaviendelangle** [comment]
Sorry, wrong issues :see_no_evil: 

#4546

**Comment by bruns6077** [comment]
@flaviendelangle 

yep thats the feature i would like to see, i can refer to ux of angular material:

https://material.angular.io/components/datepicker/overview

its a very clear and userfriendly way in my opinion
