### ISSUE TITLE
[data grid] Make Loading overlay states change based on data

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#12078]
### The problem in depth

Example: https://codesandbox.io/p/sandbox/elastic-star-66w5cs?file=%2Fsrc%2FDemo.js (from the overlay documentation)
I'd like for the loading overlay to disappear when there are rows instead of continuing to show the loading. When there aren't any rows, I'd like for a no rows indicator. Basically Show loading  initially but show no rows if nothing is received in rows. 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Chrome Browser
 
   System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 7.24.2 - ~/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.71
  npmPackages:
    @emotion/react: latest => 11.11.3 
    @emotion/styled: latest => 11.11.0 
    @mui/base:  5.0.0-beta.32 
    @mui/core-downloads-tracker:  5.15.5 
    @mui/icons-material: ^5.15.3 => 5.15.5 
    @mui/lab: ^5.0.0-alpha.159 => 5.0.0-alpha.161 
    @mui/material: ^5.15.3 => 5.15.5 
    @mui/private-theming:  5.15.5 
    @mui/styled-engine:  5.15.5 
    @mui/styles: ^5.15.3 => 5.15.5 
    @mui/system:  5.15.5 
    @mui/types:  7.2.13 
    @mui/utils: ^5.15.4 => 5.15.5 
    @mui/x-data-grid:  6.19.1 
    @mui/x-data-grid-generator: ^6.16.2 => 6.19.1 
    @mui/x-data-grid-premium: ^6.19.1 => 6.19.1 
    @mui/x-data-grid-pro:  6.19.1 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react:  17.0.75 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: latest => 6.1.8
```
</details>

**Search keywords**: loading overlay
**Order ID**: 66765

**Comment by MBilalShafi** [comment]
Since the data in the example is not coming from a server, showing loading doesn't make much sense, when you have some actual server binded to the data, you might have some loading state binded with the fetch function, you can pass it to the loading prop of the Grid.

```tsx
<DataGrid
  loading={dataLoading}
  {...otherProps}
/>
```

I've updated the example to add a 3 seconds delay on mount to simulate network latency: https://codesandbox.io/p/sandbox/inspiring-almeida-z5ct3t?file=%2Fsrc%2FDemo.js%3A27%2C29

Hope it helps.

**Comment by lisaWriteJava** [comment]
Thank you. This seems to be working as I expect. I'll give it a try in my real data next week to be sure but I think that this puts me on the correct path.

**Comment by lisaWriteJava** [comment]
I should have a definitive answer by this time next week if the ticket can stay open to confirm

**Comment by lisaWriteJava** [comment]
Hello, 

I was able to get some of the changes into my dev simulation and it doesn't' show the loading indicator initially.  The no data does go away once the data is loaded but it shows initially. Should the no rows overlay be removed from the slots?

Here's my sandbox example: https://codesandbox.io/p/sandbox/blue-field-432zlg?file=%2Fsrc%2FNotifications.js

**Comment by MBilalShafi** [comment]
@lisaWriteJava I can not access the linked codesandbox, maybe the sharing permissions are not set. Can you check?

**Comment by lisaWriteJava** [comment]
I'm sorry I've updated the permissions to public so you should be able to see now.

**Comment by michelengelen** [comment]
Hey @lisaWriteJava ... I have taken the approach from @MBilalShafi and created a simple showcase how this can be achieved. If you adapt that solution it shouldn't be a problem to create what you want: [Custom loading and no-rows overlays](https://stackblitz.com/edit/react-8kzpgt?file=Demo.tsx)

Let us know if that solves your issue! Thanks! 🙇🏼

**Comment by lisaWriteJava** [comment]
I updated the demo code I sent with your changes. and it still doesn't show the loading intially.  https://codesandbox.io/p/sandbox/blue-field-432zlg?file=%2Fsrc%2FDemo.js%3A84%2C1

I see yours workign but not sure what may be causing this.

**Comment by michelengelen** [comment]
Hey @lisaWriteJava ... your implementation was correct, BUT ... :P

You are passing in a conditionalized prop into the wrapping component `CommonGridRowActions`. And since `data` can be `null` it will only ever pass an empty array into it.

If you change from `rows={data || []}` to `rows={data}` it will work just fine.

```tsx
<CommonGridRowActions
  tableTitle={"Papabear Notices"}
  id={"papabearNotices"}
  stateId={"papabearNoticesGridState"}
  rows={data} // <= This is where the problem existed
  columns={papabearNotCols}
  handleSelectedItems={handleSelectedItems}
  ...
```

I hope this helps! 🙇🏼

**Comment by lisaWriteJava** [comment]
Hi, 

thanks for gettting back to me, I've updated https://codesandbox.io/p/sandbox/blue-field-432zlg?file=%2Fsrc%2FCommonGridRowActions.jsx to have the rows much like above


        rows={rows} 

I still see the no rows overlay and not the loading overlay.

**Comment by lisaWriteJava** [comment]
so the line I changed should be reverted?

**Comment by lisaWriteJava** [comment]
I've updated the code the https://codesandbox.io/p/sandbox/blue-field-432zlg?file=%2Fsrc%2FNotifications.js%3A39%2C10-39%2C14 and the notifications.js  to have 
rows={data} but it still only shows the no rows overlay

**Comment by michelengelen** [comment]
Well ... `rows` is never null, since you initialize the state with `[]` 

```tsx
const [data, setData] = useState([]);
```

Change it to 
```tsx
const [data, setData] = useState(null);
```

and it works

**Comment by lisaWriteJava** [comment]
So in the notification.js , if I change  const [data, setData] = useState([]); to  const [data, setData] = useState(null);
I get the following errors so I never see it work: 

```
TypeError
Cannot read properties of null (reading 'length')
    at createRowsInternalCache (https://432zlg.csb.app/node_modules/
mui/x-data-grid/hooks/features/rows/gridRowsUtils.js:48:28
    at rowsStateInitializer (https://432zlg.csb.app/node_modules/
mui/x-data-grid/hooks/features/rows/useGridRows.js:21:81
    at useGridInitializeState (https://432zlg.csb.app/node_modules/
mui/x-data-grid/hooks/utils/useGridInitializeState.js:11:35
    at useDataGridPremiumComponent (https://432zlg.csb.app/node_modules/
mui/x-data-grid-premium/DataGridPremium/useDataGridPremiumComponent.js:35:43
    at DataGridPremium (https://432zlg.csb.app/node_modules/
mui/x-data-grid-premium/DataGridPremium/DataGridPremium.js:23:72
renderWithHooks
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16305:18
updateForwardRef
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19226:20
beginWork
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21636:16
HTMLUnknownElement.callCallback
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4164:14
Object.invokeGuardedCallbackDev
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4213:16
invokeGuardedCallback
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4277:31
beginWork$1
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27451:7
performUnitOfWork
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26557:12
workLoopSync
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26466:5
renderRootSync
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26434:7
performConcurrentWorkOnRoot
https://432zlg.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25738:74
workLoop
https://432zlg.csb.app/node_modules/scheduler/cjs/scheduler.development.js:266:34
flushWork
https://432zlg.csb.app/node_modules/scheduler/cjs/scheduler.development.js:239:14
MessagePort.performWorkUntilDeadline
https://432zlg.csb.app/node_modules/scheduler/cjs/scheduler.development.js:533:21
```

**Comment by michelengelen** [comment]
Yes, because the grid expects an array, so to be 100% clear:
1. initiate the `data` state with `null` in notifications.js
2. pass data as is into the `CommonGridRowActions` (`rows={data}`)
3. get the loading state of the grid by checking for `null` (`const isLoading = rows === null`)
4. pass an array into `StripedDataGrid` by using a conditional (`rows={rows || []}`)
That way it works!

**Comment by lisaWriteJava** [comment]
Thanks It's working,

**Comment by michelengelen** [comment]
> Thanks It's working,

Great ... Fell free to open a new ticket when you encounter any other problems! Thanks! 🙇🏼
