### ISSUE TITLE
[charts] Axis min/max does not allow dynamic rescaling of the other Axis when that axis has no min/max set

### ISSUE THREAD

**Issue by synman** [mui/mui-x#12083]
### Steps to reproduce

Link to live example: https://next.mui.com/x/react-charts/axis/#axis-sub-domain

Use the min/max example and move the slider in either direction

### Current behavior

Using the MUI X scatterplot example you can see that the Y axis scaling does not dynamically change when the visible sample of X axis data is changed by using the xAxis min/max attributes.

### Expected behavior

If no min/max values are set for an axis, it should scale that axis to the min/max values available within the visible dataset.

### Context

Using the following chart as an example:
![Screenshot 2024-02-15 at 4 49 31 PM](https://github.com/mui/mui-x/assets/1299716/3554a276-c5d2-4c78-b1d6-cfa6a24ea3ec)

When you change the X axis min value value (decreasing the timeslice) to display specific just the more recent data, I'd like the chart to dynamically define the Y axis scale for the visible data rather than relying on the scale established for the entire dataset.  This is what happens today:
![Screenshot 2024-02-15 at 4 55 15 PM](https://github.com/mui/mui-x/assets/1299716/83f42ff3-9256-4943-b524-1fb8699e9321)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: macOS 14.2.1
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.160
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react: latest => 11.11.3 
    @emotion/styled: latest => 11.11.0 
    @mui/base:  5.0.0-beta.36 
    @mui/core-downloads-tracker:  5.15.10 
    @mui/icons-material: ^5.15.9 => 5.15.10 
    @mui/lab: ^5.0.0-alpha.165 => 5.0.0-alpha.165 
    @mui/material: ^5.15.9 => 5.15.10 
    @mui/private-theming:  5.15.9 
    @mui/styled-engine:  5.15.9 
    @mui/system: ^5.15.9 => 5.15.9 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.9 
    @mui/x-charts: next => 7.0.0-beta.2 
    @mui/x-tree-view: latest => 6.17.0 
    @types/react:  18.2.48 
    react: latest => 18.2.0 
    react-dom: latest => 18.2.0 
    typescript: latest => 4.9.5 
</details>

I'm using Chrome: 121.0.6167.160

**Search keywords**: min max chart

**Comment by synman** [comment]
perhaps this short video will help....  The xAxis data points are floats (0.1 scale) 

https://github.com/mui/mui-x/assets/1299716/c9b1b4b0-7d12-4164-858a-13d80bc1951b

So I can handle this myself if necessary by remove the older datapoints from the dataset I provide the chart, but this shifts a bit of heavy lifting to the consumer for what should be a pretty cool built-in feature.

**Comment by synman** [comment]
one last example before I turn it over to y'all to classify / prioritize / dismiss / etc.   This is the expected behavior:

https://github.com/mui/mui-x/assets/1299716/ab78e227-f703-42d4-80f9-a73925c76fc3

Here's that heavy lifting I was referring to:
* Build logic in backend service to limit sample size based on time offset
* Account for latency / lag introduced due to network time, processing, and rebinding
* Introduce a progress `indeterminate` or similar to block UI action while waiting (TO DO)

**Comment by alexfauquette** [comment]
Thanks for the feedback

Effectively, the `min`/`max` are for now a just a basic way to override the displayed range of element, and the easiest solution might be to compute y min/max client side according to the data and the x range.

This feature might be supported when adding the "Zoom on mouse" in the pro package

**Comment by michelengelen** [comment]
@alexfauquette should we just move this to the board then? 🤷🏼

**Comment by nihauc12** [comment]
would love to see the "zoom on mouse" feature, would allow me to switch from the currennt lib i use to muix one.
