### ISSUE TITLE
[pickers] Ineffective Date and Time Validation Despite minTime, maxTime, and disableIgnoringDatePartForTimeValidation Settings

### ISSUE THREAD

**Issue by bruns6077** [mui/mui-x#12084]
### Search Keywords

datetimepicker, validation, issue

### Latest Version

- [X] I have tested this on the latest version.

### Steps to Reproduce

Link to a live example: [LiveDemo](https://2dxhgn.csb.app/)

Steps:
1. Open the provided example.
2. Review the parameters.
3. Notice that setting `disableIgnoringDatePartForTimeValidation` to true appears ineffective.

### Current Behavior

Enabling `disableIgnoringDatePartForTimeValidation` should ensure the date portion is considered during validation. However, it appears to be disregarded. When accessing the picker, it's evident that dates prior to the specified `minTime` are not disabled as expected. Furthermore, both the parameter and the validation process require correction, as `disableIgnoringDatePartForTimeValidation` currently does not produce the intended effect.

### Expected Behavior

Setting a `minTime` or `maxTime` should result in the disabling of dates preceding the `minTime` and subsequent to the `maxTime`. Additionally, enabling `disableIgnoringDatePartForTimeValidation` is expected to incorporate the date into the validation process, taking both date and time into consideration.

### Context

I aimed to limit the date selection using `minTime` and `maxTime` and to utilize their validation capabilities. Regrettably, this approach has proven ineffective. I have implemented `disableIgnoringDatePartForTimeValidation` to no avail.

**Comment by flaviendelangle** [comment]
Hi,

Did you try using `minDateTime` and `maxDateTime`?
