### ISSUE TITLE
[data grid] Same column in different column groups

### ISSUE THREAD

**Issue by MiraHariri** [mui/mui-x#12089]
### The problem in depth

I have data:
```
data = [
  {
    id: "1",
    cost_2022: "20",
    variation_2022_2023: "10",
    cost_2023: "30",
    variation_2023_2024: "20",
    cost_2024: "50",
  },
  {
    id: "2",
    cost_2022: "10",
    variation_2022_2023: "20",
    cost_2023: "30",
    variation_2023_2024: "10",
    cost_2024: "40",
  },
];
```

I want to create groups:
```
group = [
  {
    groupId: "2022_2023",
    headerName: "2022 - 2023 Variation",
    children: [
      { field: "cost_2022" },
      { field: "variation_2022_2023" },
      { field: "cost_2023" },
    ],
  },
  {
    groupId: "2023_2024",
    headerName: "2023 - 2024 Variation",
    children: [
      { field: "cost_2023" },
      { field: "variation_2023_2024" },
      { field: "cost_2024" },
    ],
  },
];
```

where the field "cost_2023" exists in both groups

How is this doable?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Duplicate column group
**Order ID**: 78698

**Comment by michelengelen** [comment]
Hey @MiraHariri ... what component are you referring to? `TreeView`?

And could you please provide a minimal live example? That would help us a lot in understanding your problem! Thanks! 🙇🏼

**Comment by MiraHariri** [comment]
@michelengelen I'm referring to `columnGroupingModel`

`<DataGridPremium
            apiRef={apiRef}
            rows={[
  {
    id: "1",
    cost_2022: "20",
    variation_2022_2023: "10",
    cost_2023: "30",
    variation_2023_2024: "20",
    cost_2024: "50",
  },
  {
    id: "2",
    cost_2022: "10",
    variation_2022_2023: "20",
    cost_2023: "30",
    variation_2023_2024: "10",
    cost_2024: "40",
  },
]}
            columns={[
  {
    headerName: "ID",
    field: "id",
  },
  {
    headerName: "Cost 2022",
    field: "cost_2022",
  },
  {
    headerName: "Variation 2022 2023",
    field: "variation_2022_2023",
  },
  {
    headerName: "Cost 2023",
    field: "cost_2023",
  },
  {
    headerName: "Variation 2023 2024",
    field: "variation_2023_2024",
  },
  {
    headerName: "Cost 2024",
    field: "cost_2024",
  },
]}
columnGroupingModel={[
  {
    groupId: "2022_2023",
    headerName: "2022 - 2023 Variation",
    children: [
      { field: "cost_2022" },
      { field: "variation_2022_2023" },
      { field: "cost_2023" },
    ],
  },
  {
    groupId: "2023_2024",
    headerName: "2023 - 2024 Variation",
    children: [
      { field: "cost_2023" },
      { field: "variation_2023_2024" },
      { field: "cost_2024" },
    ],
  },
]}
  />`
  
  I have the field `cost_2023' is duplicated in the 2 groups
  
  This returned an error that a field can't be in multiple groups
  
  Is there a way to achieve this? or a workaround?

**Comment by michelengelen** [comment]
Hi @MiraHariri ... as the docs state:

```
:warning: a column can only be associated with one group
```

So, this is not possible and I am not aware of any workarounds for this. The only thing that you could do is probably duplicate that column, but from the structure of your data I would guess this can get out of hand if you scale this up, right?

**Comment by MiraHariri** [comment]
Okay, yes I had this option to duplicate data with different column names in mind, and it is doable. But thought if there is a way from the table would be better

Thank you @michelengelen

**Comment by michelengelen** [comment]
Yeah ... it would have been better. If we can help you with anything else please feel free to open up a new issue! Thanks! 🙇🏼

**Comment by MiraHariri** [comment]
Hello @michelengelen 
I found some issues in the solution that you provided previously

- The first issue is when you click on "Select All" from the table header, only the group rows will be selected and the children of the first group only. so I updated the code to fix this issue

`

  const arrayDiff = (
    arr1: GridRowSelectionModel,
    arr2: GridRowSelectionModel
  ) => {
    const diff = [...arr1]
      .filter((item) => !arr2.includes(item))
      .concat(arr2.filter((item) => !arr1.includes(item)));

    return {
      diff,
      id: diff[0],
      isNewBigger: arr1.length < arr2.length,
    };
  };

  const handleRowSelectionModelChange = (newRowSelectionModel: any) => {
    const diff: any = arrayDiff(rowSelectionModel, newRowSelectionModel);

    if (diff.diff.length > 1) {
      if (diff.isNewBigger)
        setRowSelectionModel([
          ...newRowSelectionModel,
          ...apiRef.current.getAllRowIds(),
        ]);
      else setRowSelectionModel([]);
    } else {
      if (apiRef.current.getRowNode(diff.id)?.type !== "group") {
        setRowSelectionModel(newRowSelectionModel);
        return;
      }

      const childRowIds = apiRef.current.getRowGroupChildren({
        groupId: diff.id,
      });
      let updatedRowSelectionModel: any = [];
      updatedRowSelectionModel = [
        ...new Set(
          diff.isNewBigger
            ? [...newRowSelectionModel, ...childRowIds]
            : newRowSelectionModel?.filter(
                (id: any) => !childRowIds.includes(id)
              )
        ),
      ];
      setRowSelectionModel(updatedRowSelectionModel);
    }
  };
`

- The second issue is when you select/unselect all the child rows 1 by 1, the parent row should be checked/unchecked automatically

- The third issue is when you do any action on the table, like change column sorting for example, the parent row will be unchecked while the child rows stay selected

**Comment by michelengelen** [comment]
Hi @MiraHariri ... well, we can definitely improve on this. On the other hand a built-in solution should be preferred. I will try to improve the workaround, but also add this to the board for the team to build a more profound solution. 💪🏼

**Comment by michelengelen** [comment]
Sry, this is the wrong issue ... the original issue was #12222 ... closing this again
