### ISSUE TITLE
[charts] labels are incorrect in RTL

### ISSUE THREAD

**Issue by samueltrevor** [mui/mui-x#12118]
### Steps to reproduce

Link to live example:
We could just look at the PyChart demo
https://mui.com/x/react-charts/pie/

Steps:
1. Set the direction of the settings to Right to Left

### Current behavior

The legend labels cover the the legend marks.
They also stay on the right.
![Screenshot_20240218-102809](https://github.com/mui/mui-x/assets/100048750/101ad386-4604-4647-ba03-82577b5f0f7e)

### Expected behavior

The legend should be all the way on the left with the marks before the label text

### Your environment

System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (121.0.2277.128)
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.32
    @mui/core-downloads-tracker:  5.15.6
    @mui/icons-material: ^5.15.6 => 5.15.6
    @mui/joy: ^5.0.0-alpha.84 => 5.0.0-beta.23
    @mui/lab: ^5.0.0-alpha.135 => 5.0.0-alpha.161
    @mui/material: ^5.15.6 => 5.15.6
    @mui/private-theming: ^5.13.7 => 5.15.6
    @mui/styled-engine:  5.15.6
    @mui/system:  5.15.6
    @mui/types:  7.2.13
    @mui/utils:  5.15.6
    @mui/x-charts: ^6.19.4 => 6.19.4
    @mui/x-date-pickers: ^6.11.2 => 6.19.0
    @types/react:  18.2.48
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.9.5

**Search keywords**: RTL

**Comment by alexfauquette** [comment]
Thanks for the feedback

If I understand well, with RTL the legend should be on the left (in addition to the marks being on the right on the legend text)

I take the opportunity to ask about RTL for the line chart, bar chart. I'm wondering if the x axis should be reverted

**Comment by samueltrevor** [comment]
Yes. That's right.
The problem appears on all charts.
