### ISSUE TITLE
[data grid] Include password protection and set a custom file name for the exported Excel file

### ISSUE THREAD

**Issue by lorin-monday** [mui/mui-x#12146]
### The problem in depth

I would like to add password protection to the exported Excel files. Does your package offer any functions, methods, or options for password protection during the export process? If not, I would appreciate any suggestions or guidance on how I can achieve this feature with your package.

Additionally, I would like to set a specific name for the exported files, preferably using the account name. Is it possible to incorporate this functionality using your package? If so, could you please provide some instructions or suggestions on how to implement this?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  @mui/envinfo@2.0.18

```
</details>

**Search keywords**: password excelfile
**Order ID**: 59343

**Comment by michelengelen** [comment]
Hey @lorin-monday ... I am not 100% sure if this is possible.
I guess your best shot at this is to use the [web worker approach](https://mui.com/x/react-data-grid/export/#using-a-web-worker).

@cherniavskii do you know if we can support it like this?

**Comment by shaharyar-shamshi** [comment]
@lorin-monday @michelengelen If I am not wrong we can use [customisation of exceljsPostProcess](https://mui.com/x/react-data-grid/export/#customization) to generate the password protected excel

code snipper which I think will work is

```
const postProcess = async (workbook: any) => {
  const worksheet = workbook.getWorksheet(1);
  
  // Set password protection for the worksheet
  worksheet.protection = {
    sheet: true,
    password: 'your_password_here'
  };

  return workbook;
};

```

**Comment by michelengelen** [comment]
Seems like the approach from @shaharyar-shamshi might just be what you are looking for @lorin-monday ... could you try that and let us know if that is a sufficient solution for your use case? Thanks! 🙇🏼

**Comment by kimhm93** [comment]
const exceljsPostProcess = (processInput: GridExceljsProcessInput) => {
          const worksheet = processInput.workbook.getWorksheet(1);
          const protect = worksheet?.protect("password", {});
          return protect ? protect : Promise.resolve() 
     };


I tried applying the code above by referring to the part that @shaharyar-shamshi mentioned and the typescript of x-data-grid-premium. But it didn't work.. Has anyone solved it by any chance??
