### ISSUE TITLE
[data grid] filter on invalid date

### ISSUE THREAD

**Issue by Myloc-KJN** [mui/mui-x#12153]
### The problem in depth

Hello,

I'm using server-side filterMode and have columns of `Date` type. I'm using the standard way of handling filters with `onFilterModelChange` as mentioned in the documentation: [React Data Grid - Filtering Server-Side](https://next.mui.com/x/react-data-grid/filtering/server-side/).

My problem is that the `onFilterModelChange` also triggers on invalid dates and that filtration on invalid dates gives the same `filterModel` as clearing the filter to the `onFilterModelChange`.

For example, if a user first filters on the date 2024-02-20, it gives the correct result:

![image](https://github.com/mui/mui-x/assets/71376158/06d6ec6e-191a-4353-9217-c156d1990339)

But if the user targets the year part of the filter and presses "0", it will filter on an invalid date 0000-02-20:

![image](https://github.com/mui/mui-x/assets/71376158/d624f887-0eba-4840-9863-702edd5bf069)

My `onFilterModelChange` will get the same `GridFilterModel` as if the user has cleared the filter, resulting in an unnecessary BE call. As soon as the user clicks away from the filter, the filter will auto-correct to 0001-02-20 and create another BE call. This can cause confusion for the user.

The auto-corrected date:

![image](https://github.com/mui/mui-x/assets/71376158/a4c1e9ea-d6f0-4eca-ab10-7fa1880ecc08)

My screenshots are from the documentation webbsite and can be recreated here: https://mui.com/x/react-data-grid/filtering/header-filters/

I'm wondering if there is any way to notice if the user has filtered on an invalid value like 0000-02-20 so that I can stop the BE call in my `onFilterModelChange`?

I have tried overriding the input to see if I can stop it in the `applyValue`, but it is the same in there. Filtration on 0000-02-20 gives me a blank filtration, so I cannot differentiate it from a clear of the filtration field:

```jsx
<GridFilterInputDate
      {...props}
      applyValue={gridItem => {
        console.log(props.item.value);
      }}
    />
```

### Your environment

<details>
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 14.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 121.0.6167.185
    Edge: Chromium (121.0.2277.128)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.26
    @mui/core-downloads-tracker:  5.14.20
    @mui/icons-material: ^5.13.7 => 5.13.7
    @mui/lab: ^5.0.0-alpha.153 => 5.0.0-alpha.153
    @mui/material: ^5.14.20 => 5.14.20
    @mui/private-theming:  5.14.20
    @mui/styled-engine:  5.14.20
    @mui/system:  5.14.20
    @mui/types:  7.2.10
    @mui/utils:  5.14.20
    @mui/x-data-grid-premium: ^6.17.0 => 6.18.1
    @mui/x-date-pickers: ^6.18.3 => 6.18.3
    @types/react: ^17.0.39 => 17.0.39
    react: ^17.0.1 => 17.0.2
    react-dom: ^17.0.1 => 17.0.2
    typescript: ^4.6.3 => 4.6.3

</details>

**Search keywords**: DataGrid Filter Date
**Order ID**: 78662

**Comment by michelengelen** [comment]
@MBilalShafi We could possibly enhance this with some kind of new validator for the date value. Something that prevents updating the filtermodel when the value is an invalid date.

WDYT?

**Comment by MBilalShafi** [comment]
We recently [added](https://github.com/mui/mui-x/pull/7069) support for Date objects in `filterModel` which could possibly have solved this issue too. When checking on the [v7 version](https://next.mui.com/x/react-data-grid/), I can not observe the `Invalid Date` being called in an `onFilterModelChange` callback anymore. @Myloc-KJN Could you check?

**Comment by Myloc-KJN** [comment]
@MBilalShafi Yes, I can confirm. When I tried the v7 beta version, it throws an invalid date error. So when that version goes live, I think I can resolve my problems. Thanks.

**Comment by michelengelen** [comment]
Great to hear that @Myloc-KJN ... I will close this issue for now, but feel free to reopen it when you encounter problems when implementing our solution. Thanks! 🙇🏼
