### ISSUE TITLE
GRID inline edit validation

### ISSUE THREAD

**Issue by Mimmo47** [mui/mui-x#12162]
### The problem in depth

In  a grid I have to edit some cells in a row, but the value must be validated for minimum/maximum length, data type, matching against a look-up table or an array, etc.
Is it possible?
Example: one of the columns contains a phone number and the new value must not accept alpha chars
Another columg contains Currency codes (USD, EUR, GBP, etc.) that should be checked aganst an array of allowed currencies.
And so on.
What shall I do to implement a valdation of this type?
Thanks

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Edit Validation
**Order ID**: Order 83077

**Comment by michelengelen** [comment]
Hey @Mimmo47 ... yes, it is possible. You can use the `preProcessEditCellProps` method from the column definition for this.

we do have a page on the docs with some examples here: [Validation docs](https://mui.com/x/react-data-grid/editing/#validation)
