### ISSUE TITLE
[data grid] How to do confirmation before pasting?

### ISSUE THREAD

**Issue by silvialeung-mh** [mui/mui-x#12165]
### The problem in depth

The use case is to pop up a confirmation dialog before pasting. 

At first. I tried to do something similar to the "Confirmation Before save" example in onClipboardPasteStart event but it seems to have a few issues.
1. It is not possible to prevent processRowUpdate event by setting defaultMuiPrevented to true in onClipboardPasteStart.
2. It is not possible to know the updating rows and fields with the function parameters of onClipboardPasteStart so I cannot use gridRef.current.updateRows() to trigger the update programmatically. 

Doing the confirmation logic in processRowUpdate is not possible because processRowUpdate is fired for each row while the confirmation popup should only be popped up once per paste operation.

Is there a way to accomplish this?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.7.1
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 7.33.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Edge: 121.0.2277.128
    Safari: 17.1
  npmPackages:
    typescript: 5.0.2 => 5.0.2 

```
</details>

**Search keywords**: Clipboard paste
**Order ID**: 70106

**Comment by michelengelen** [comment]
Hey @silvialeung-mh ... yes, you can achieve something like this if you prevent execution of `processRowUpdate` with a combination of `await`, `Promise` and events. I did play around with this a bit and this is what I came up with: [Paste operation Dialog](https://stackblitz.com/edit/react-qj2vj6)

This example is pretty basic, so you might want to extend it a bit and tailor it to your specific implementation! Let me know if this helps you! Thanks! 🙇🏼

**Comment by silvialeung-mh** [comment]
Hi @michelengelen , thanks for the quick response. I played around with the sandbox you have provided but it seems to have affected normal edit as it is now waiting for 'dialog-action' event and I am not sure where to dispatch it in normal edit flow (because onCellEditStop runs before processRowUpdate).

**Comment by michelengelen** [comment]
Ah, yes ... I am sorry. I did not check that beforehand. Sry! 🙇🏼 

As it stands the problem is that the `onClipboardPasteStart` method can only be used to implement side-effects, which is not what I would expect from an event-handler.

I would propose a solution for this to prevent execution based on the return value of `onClipboardPasteStart`, or even make the method a Promise that will only execute the paste on `resolve()` and otherwise abort, but it is a breaking change.

WDYT @MBilalShafi @cherniavskii ?

**Comment by cherniavskii** [comment]
Hi @silvialeung-mh 
I've opened a PR for it https://github.com/mui/mui-x/pull/12225
You can check out the demo here: https://deploy-preview-12225--material-ui-x.netlify.app/x/react-data-grid/clipboard/#events
Is this what you're looking for?

Also, do you need this for the v6 of the data grid?

**Comment by silvialeung-mh** [comment]
@cherniavskii Thank you. This will satisfy the current use case and it would be great if this feature can be included in v6
