### ISSUE TITLE
[charts] Issue with the Default Charts Axis Tooltip Content

### ISSUE THREAD

**Issue by Manikandasubramani** [mui/mui-x#12161]
### Steps to reproduce

Link to live example: (required)

Steps:
1. I have imported the <SparkLineChart /> from MUI
2. I am passing a list of integers (8 values in my case)
3. If i am showing the value as integers and having the scaleType as 'number' in xAxis, i can able to see all 8 datapoints in tooltip
4. But if i convert the values lets say in my case i am formatting the integers into comma separated strings using the "valueFormatter={(f)=>{ return `${f.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}` }}" it is showing the Warning in my console as "**Warning: Failed prop type: Invalid prop `axis.scaleType` of value `number` supplied to `DefaultChartsAxisTooltipContent`, expected one of ["time"].**"
5. And most importantly the last tooltip which the 8th data point is not showing in my case
6. But if i put the scaleType as 'number' and if i didnt convert my values to string, i can able to see the 8th tooltip and no warning either. 
7. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DefaultChartsAxisTooltipContent

**Search keywords**:

**Comment by michelengelen** [comment]
Hi @Manikandasubramani,

Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by Manikandasubramani** [comment]
Hi @michelengelen ,

Please find the issue here (https://stackblitz.com/edit/react-11fhh9?file=Demo.js).

In the first sparkline, we can see the tooltip for 8th data point. since the "scaleType" is number and the data were all integers.
But in the second sparkline, we cannot see the tooltip for the 8th datapoint since the "scaleType" is "time".. 

And if in change the scaleType for the second data point to number instead of time, i am getting a warning in my console as **"Warning: Failed prop type: Invalid prop axis.scaleType of value number supplied to DefaultChartsAxisTooltipContent, expected one of ["time"]"**

There are

**Comment by Manikandasubramani** [comment]
@michelengelen ,

So i am trying to include this sparkline as part of MUI table cell, in that i cant able to get that 8th tooltip..

Yes i have tried with "valueFormatter={(f) => { return toLocalString('e') }} ". And I have once more scenario "valueFormatter={(e)=>{return `${e}%`}}".. in this scenario also the same issue exists..

**Comment by alexfauquette** [comment]
`scaleType: 'number'` This does not exist. That's why you get the warning

```
Warning: Failed prop type: Invalid prop `xAxis[0].scaleType` of value `number` supplied to `CartesianContextProvider`, expected one of ["band","linear","log","point","pow","sqrt","time","utc"].
```

The available types are described here: https://mui.com/x/react-charts/axis/#axis-type

If you use `scaleType: 'utc'` or `scaleType: 'time'` the data should be `Date` objects

With `Date` objects it's working: 

https://stackblitz.com/edit/react-11fhh9-z7vrby?file=Demo.js

**Comment by Manikandasubramani** [comment]
@alexfauquette,

What if I just need integer values or numbers instead of dates in the tooltip as shown in the first sparkline (https://stackblitz.com/edit/react-11fhh9-z7vrby?file=Demo.js)

Could you please help with this scenario

Thanks

**Comment by alexfauquette** [comment]
> What if I just need integer values or numbers instead of dates in the tooltip as shown in the first sparkline

Could you define what you want for:

- what is the data input
- what the tooltip should display
- are points evenly spaced along x axis, or should they respect the `xAxis.data`

**Comment by Manikandasubramani** [comment]
I have to create a sparkline chart for each row in table based on 8 data points.
The data points are of 2 different scenarios like
  1. data1 = [12.5, 13.5, 15.6, 17.9, 11.0, 14.2, 22.0,14.5]
  2. data2 = [11000, 32435, 43345, 23211, 56445, 45645, 56767]

I just want to show the tooltip for all data points as 1, 2, 3, 4, 5, 6, 7, 8 as shown in my initial src that i shared

**Comment by Manikandasubramani** [comment]
I am getting this warning in my console

react-jsx-runtime.development.js:87 Warning: Failed prop type: Invalid prop `axis.scaleType` of value `point` supplied to `DefaultChartsAxisTooltipContent`, expected one of ["time"].

**Comment by alexfauquette** [comment]
Do you use v6.19.4 ?

If no, it's probably a proptypes bugs that got fixed

**Comment by Manikandasubramani** [comment]
Hi,

I just updated my @mui/x-charts package to the latest version (v6.19.5).. I am getting this issue on load 

SparkLineChart.js:74 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at SparkLineChart (SparkLineChart.js:74:1)

**Comment by Manikandasubramani** [comment]
The issue got fixed..

Thank you very much for helping.. :)
