### ISSUE TITLE
[data grid] Unable to print data containing image

### ISSUE THREAD

**Issue by Kamasah-Dickson** [mui/mui-x#12171]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Current behavior

On the preview page of the print I get an erorr because the mui data table contains and image

### Expected behavior

I should be able to print and preview data from the mui data grid table that contains images

### Context

I am building a project that allows users to print their data from the mui data grid table but am particular about when the data contains an image or logo

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Print mui data-grid table containing images

**Search keywords**:

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
