### ISSUE TITLE
[data grid] overflow issue when border is set to virtualScroller.

### ISSUE THREAD

**Issue by boldurean** [mui/mui-x#12176]
### Steps to reproduce

Link to live example: (required) [Devbox example](https://codesandbox.io/p/devbox/mui-data-grid-border-overflow-szr47v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsxbk67100063d5uumkcuemo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsxbk67100023d5uw26625nr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsxbk67100043d5uh5nj9c57%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsxbk67100053d5um4xjzu4e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsxbk67100023d5uw26625nr%2522%253A%257B%2522id%2522%253A%2522clsxbk67100023d5uw26625nr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxconzc00023d5uhawl2v7w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsxconzc00023d5uhawl2v7w%2522%257D%252C%2522clsxbk67100053d5um4xjzu4e%2522%253A%257B%2522id%2522%253A%2522clsxbk67100053d5um4xjzu4e%2522%252C%2522activeTabId%2522%253A%2522clsxbnzyz00ec3d5ua6q2wzm1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clsxbnzyz00ec3d5ua6q2wzm1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clsxbk67100043d5uh5nj9c57%2522%253A%257B%2522id%2522%253A%2522clsxbk67100043d5uh5nj9c57%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxbk67100033d5urc7lcoca%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsxbk734000td8f8hxx348uq%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsxbk67100033d5urc7lcoca%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Open devbox example
2. Remove border class from DataGrid -> classes -> virtualScroller
3. Notice horizontal scroll to dissapear

### Current behavior

There is a simple use case scenario where I want to separate toolbar from root (table body)  as well as footer. When I set the border around the content container it looks like virtualScroller container become narrower by 2px (exact scroll amount) but virtualScrollContainer and it's children doesn't update it's width and causes overflow and ofc horizontal scroll. Adding border to practically anything from "main" class down creates overflow.

### Expected behavior

Adding border to virtualScroller, virtualScrollerContainer should not cause overflow

### Context

Style table body separate from root

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browsers:

- Chrome: Version 122.0.6261.57 (Official Build) (arm64)
- Safari: Version 17.3.1 (19617.2.4.11.12)
- Firefox: 123.0 (64-bit)

 System:
    OS: macOS 14.3.1
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.14.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.57
    Edge: 121.0.2277.128
    Safari: 17.3.1
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/icons-material: ^5.15.8 => 5.15.10
    @mui/lab: 5.0.0-alpha.161 => 5.0.0-alpha.161
    @mui/material: ^5.15.7 => 5.15.10
    @mui/x-data-grid: ^6.19.3 => 6.19.4
    @mui/x-date-pickers: ^6.19.3 => 6.19.4
    @mui/x-tree-view: ^6.17.0 => 6.17.0
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
```
</details>

**Search keywords**: DataGrid overflow, virtualScroller overflow, horizontal scroll, border overflow.

**Comment by michelengelen** [comment]
@romgrk could you have a look at this please? Thanks! 🙇🏼

**Comment by romgrk** [comment]
Have you tried setting the border on the top/bottom elements instead of the virtual scroller? The scroller needs precise dimensions and the border affects them.

Also are you planning to migrate to v7? We're about to release it and the beta version is already available. It modifies the DOM structure substantially so if you plan to migrate, the solution for v6 would probably not work in v7.

**Comment by boldurean** [comment]
> Have you tried setting the border on the top/bottom elements instead of the virtual scroller? The scroller needs precise dimensions and the border affects them.

That's what I did and it seems more a hack rather than solution bc when quick filter is applied and there is 1,2 elements displayed & virtual scroller becomes half empty without borders it doesn't look right: 

<img width="1109" alt="Screenshot 2024-02-26 at 17 09 07" src="https://github.com/mui/mui-x/assets/64642760/a3ca9215-8cc6-4b14-8e4a-b784c2c33a16">
 
> Also are you planning to migrate to v7? We're about to release it and the beta version is already available. It modifies the DOM structure substantially so if you plan to migrate, the solution for v6 would probably not work in v7.

Wdm solution for v6 wouldn't be working with v7? I'm premium user and we will upgrade it to v7 if there is no major breaking changes.

**Comment by romgrk** [comment]
The DOM changes improved the UX and will allow us to be much more accessible for screen readers, so we advise to look into migrating to v7 if you can.

If that answers your question, you can close the issue. Feel free to reopen if you need more assistance.

**Comment by boldurean** [comment]
Thanks @romgrk, we will upgrade it once it's out of beta.

**Comment by boldurean** [comment]
Hi @romgrk just to mention that adding border to the main in v7 works as expected :)
