### ISSUE TITLE
[data grid] SingleSelect Horizontal alignment in Datagrid

### ISSUE THREAD

**Issue by sterlingdcs-damian** [mui/mui-x#12196]
### The problem in depth

In Mui data grid is there a way to align a column that has a `singleSelect`
We would like to left align it, but it seems to default to being centred
![image](https://github.com/mui/mui-x/assets/140072768/fcec8057-24ba-4b7b-bd11-dda0a4b98dde)

Column definition:
```
 {
        field: 'category',
        type: 'singleSelect',
        valueOptions: Object.values(OperationCategories),
        headerName: t({ id: 'category', message: 'Category' }),
        width: 220,
        editable: true,
        preProcessEditCellProps: required(),
      }
 ```

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>
  System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.15 
    @mui/core-downloads-tracker:  5.14.18 
    @mui/icons-material: 5.14.9 => 5.14.9 
    @mui/lab: 5.0.0-alpha.144 => 5.0.0-alpha.144 
    @mui/material: 5.14.10 => 5.14.10 
    @mui/private-theming:  5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/styles: 5.14.10 => 5.14.10 
    @mui/system: 5.14.9 => 5.14.9 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.7 
    @mui/x-charts: ^6.19.3 => 6.19.3 
    @mui/x-data-grid:  6.18.4 
    @mui/x-data-grid-premium: 6.18.4 => 6.18.4 
    @mui/x-data-grid-pro:  6.18.4 
    @mui/x-license-pro: 6.10.2 => 6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react: 17.0.2 => 17.0.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.4.3 => 4.4.3 

</details>

**Search keywords**: Data grid single-select align
**Order ID**: 73340

**Comment by michelengelen** [comment]
Hey @sterlingdcs-damian this is definitely possible.
You can pass in `MenuProps` into the `slotProps` that define this:

```
slotProps={{
  baseSelect: {
    MenuProps: {
      anchorOrigin: {
        vertical: 'bottom',
        horizontal: 'left',
      },

      transformOrigin: {
        vertical: 'top',
        horizontal: 'left',
      },
    },
  },
}}
```

Does this solve your use case?

**Comment by sterlingdcs-damian** [comment]
hey @michelengelen , thanks! 
looking a lot better now
![image](https://github.com/mui/mui-x/assets/140072768/493cf0b2-c4d3-426f-8c6d-8ad08a73cd01)
