### ISSUE TITLE
[docs] Demo QuickFilteringGrid crashes

### ISSUE THREAD

**Issue by EmilianoLam** [mui/mui-x#12199]
- [x ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20QuickFilteringGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-data-grid/filtering/quick-filter/
2. Press enter on any cell of the rating column, change the quantity using arrow keys, after every key press when changing quantity it will exit edit mode and when u enter again multiple times it will crash.
3. demo *QuickFilteringGrid* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v6.19.5  |
| Netlify deploy | https://65d86f8013bd59000842513a--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by michelengelen** [comment]
thanks @EmilianoLam ... I can confirm this bug.

Steps to reproduce:
1. enter edit mode on rating cell
2. change rating with arrows
3. exits edit mode after first arrow key (<- first bug)

Second bug:
1. enter edit mode on a value 5 or value 1 rating
2. go one up or down to reach value 0 (separate bug from `**Rating**` component here)
3. demo crashes with following error message (from local dev instance):
```
react-dom.development.js:22834 Uncaught TypeError: Cannot read properties of null (reading 'focus')
    at handleRef (renderEditRating.tsx:18:68)
    at setRef (setRef.js:20:5)
    at eval (useForkRef.js:24:60)
```

It seems that there are several problems here:
1. The edit mode stops whenever there is a change
2. the element with value 0 cannot be found
3. unrelated: the Rating component has a bug where pressing arrow down **increses** the value

**Comment by cherniavskii** [comment]
Fixed by https://github.com/mui/mui-x/pull/12335 and https://github.com/mui/mui-x/pull/12315
