### ISSUE TITLE
[data grid] Add option to `GridTooldbar` to remove export option or to `GridToolbarExport` to pass custom export function

### ISSUE THREAD

**Issue by nico-martinucci** [mui/mui-x#12198]
### Summary

The export button currently only exports the rows visible in the table, rendering it unusable for a table with server-side pagination. At a minimum it would be great to pass a `slotProp` to t`GridToolbar` to just not render this button, but it would be even better to pass a custom `onClick` to this button so I can handle the export myself.

**Search keywords**: data grid, export, server-side pagination, server-side filtering

**Comment by michelengelen** [comment]
Hey @nico-martinucci ... tbh I do not know if that is possible. I assume it is not, but would like to ask the team first.
 
@cherniavskii could you maybe provide some insight?

As for now: You can definitely handle the export yourself with a custom button inside a [CustomToolbar](https://mui.com/x/react-data-grid/export/#custom-toolbar). We do expose some export methods on the [apiRef](https://mui.com/x/react-data-grid/export/#apiref).



Would that be a valid solution for you?
