### ISSUE TITLE
[pickers] Could not resolve "dayjs" imported by "@mui/x-date-pickers"

### ISSUE THREAD

**Issue by sohail120** [mui/mui-x#12205]
### Your environment

import { DemoContainer } from "@mui/x-date-pickers/internals/demo";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";

export default function BasicDatePicker() {
  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DemoContainer components={["DatePicker"]}>
        <DatePicker label="Basic date picker" />
      </DemoContainer>
    </LocalizationProvider>
  );
}

**Search keywords**: @mui/x-date-pickers

**Comment by LukasTy** [comment]
Hello @sohail120, thank you for creating this issue. 👍 
Based on the given information it is unclear, what problem you are having.
Please provide a **minimal** reproduction test case with the latest version. This would help a lot. 🙏 
A live example would be perfect. [This **stackblitz** example](https://stackblitz.com/edit/react-4xfvmq?file=Demo.tsx) _may_ be a good starting point. Thank you!

**Comment by flaviendelangle** [comment]
Just to be sure, did you install `dayjs`? 

We are not installing the date libraries ourselves because we support several one and we don't want to force the installation of all of them.
