### ISSUE TITLE
[Datagrid v7] Error when resizing pinned columns

### ISSUE THREAD

**Issue by lauri865** [mui/mui-x#12209]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Open https://next.mui.com/x/react-data-grid/column-pinning/
2. Resize the pinned column
3. Check the console

### Current behavior

Spams the following error and breaks columnResize event:
```typescript
useGridColumnResize.js:517 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at updateProperty (useGridColumnResize.js:517:11)
    at updateWidth (useGridColumnResize.js:240:7)
    at useGridColumnResize.js:291:5
    at HTMLDocument.<anonymous> (useEventCallback.js:18:11)
```

It's due to this line:
https://github.com/mui/mui-x/blob/4ba146923be1ce483cf89bd0941236fe4991de73/packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx#L358

The following element does not exist in the DOM:
https://github.com/mui/mui-x/blob/4ba146923be1ce483cf89bd0941236fe4991de73/packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx#L417 

### Expected behavior

No error. Events working.

### Your environment

Publicly reproducible, no need for env.

**Search keywords**: Cannot read properties of null (reading 'style')

**Comment by romgrk** [comment]
Can't reproduce with any of the examples, can you clarify reproduction steps?

**Comment by romgrk** [comment]
Can't reproduce on linux with any browser. Let me check if someone else can handle it.

**Comment by lauri865** [comment]
Reproduced with Safari as well.

Here's the DOM with automatic scrollbars:
<img width="579" alt="Screenshot 2024-02-26 at 18 10 02" src="https://github.com/mui/mui-x/assets/3652743/b90eb0c2-f803-445a-b5c7-0a4f4483c60e">

Here's the DOM with scrollbars always shown:
<img width="588" alt="Screenshot 2024-02-26 at 18 07 15" src="https://github.com/mui/mui-x/assets/3652743/f003eb54-cc9e-493f-be8c-4a7d94d90780">

The first is missing the `div.MuiDataGrid-filler` in the DOM.
