### ISSUE TITLE
[data grid] Set column ordering for MUI DataGrid from view using apiRef.current.restoreState?

### ISSUE THREAD

**Issue by mehdi-heidari** [mui/mui-x#12212]
### The problem in depth

I have a problem with column ordering for MUI DataGrid as the following:
When I use apiRef.current.exportState to create a view and load it by apiRef.current.restoreState, it works without any problem (column ordering also works), however when I use apiRef.current.restoreState to load the saved views that I read from database everything works **except column ordering**.

I should add, to save a view I use the apiRef.current.exportState and store it in a database json field. 

### Your environment

//This works:
dispatch({
          type: "createView",
          id: my_id,
          label: my_label,
          value: apiRef.current.exportState()
        });
apiRef.current.restoreState(my_id)

// This one **NOT** working:
// my_view = read form database or local storage 
        dispatch({
          type: "createView",
          id: my_view.id,
          label: my_view.label,
          value: my_view.value,
      });
apiRef.current.restoreState(my_view.id)
// Everything **except** column ordering works 

**Search keywords**: Column ordering DataGrid view apiRef restoreState exportState
**Order ID**: 80663

**Comment by michelengelen** [comment]
Hey @mehdi-heidari did you try comparing the values you get from `localstorage` with the ones you export from the state?

Do something like this:
1. `const state = apiRef.current.exportState()`
2. store `state` to `localStorage`
3. grab the stored state from `localStorage`
4. compare both values

It works for me if I use the example code from [this docs page](https://mui.com/x/react-data-grid/state/#save-and-restore-the-state-from-external-storage).

Could you provide us with a live example of your implementation in codesandbox or stackblitz?
