### ISSUE TITLE
[Data Grid] noResultsOverlayLabel not visible after filtering when no absolute height is set

### ISSUE THREAD

**Issue by yannickokonek** [mui/mui-x#12210]
### Steps to reproduce

You can try out this issue directly on your documentation page on the first example
https://mui.com/x/react-data-grid/

Steps:
1. Click on "show code" in the first example
2. edit the height to be `100%` or remove the attribute all together
3. filter the table for something, that does not exist

### Current behavior

The space in the table where the `noResultsOverlayLabel` is shown has nearly zero height and can't be read

### Expected behavior

The height should be large enough to fit the no results text

### Context

I'm quite new to MUI, so if I just missused it, please tell me what I did wrong.  
I first encountered this bug on my own table, but couldn't find the source. Disabling all my css didn't solve the issue.
What fixes it is eiher
- use `autoHeight={true}` property on the MUI table (but we loose virtualization
- use a fixed height for the container 
The latter is not optimal in my case, since I do not know the available height on my site in advance, so I would like to use `100%`.
When using it on a non-empty table, this does work well, so I thought this should be possible.  

### Your environment

I'm using chrome, but it's the same on firefox.

**Search keywords**: "data grid", noResultsOverlayLabel, "empty table", "no results"
**Order ID**: 84664

**Comment by michelengelen** [comment]
That is to be expected. The data grid does need a container with intrinsic dimensions to work properly. Related docs can be found here: [Layout](https://mui.com/x/react-data-grid/layout/)

The grid can still be used inside a dynamic/fluid layout, e.g. using flex.

Its something not entirely logical at first if you are new to this. No worries.

If you need additional assistance feel free to reach out again! Thanks! 🙇🏼
