### ISSUE TITLE
[data grid] Can't remove Tooltip when text is not truncate in DataGridPremium

### ISSUE THREAD

**Issue by Aberkati** [mui/mui-x#12224]
### The problem in depth

I'm working on a DataPremium grid and I want to display truncate columns in a tooltip component, so when I resize a column and it's smaller than text size then the Tooltip component is displayed when I hover the colmn.

I have a [demo ](https://codesandbox.io/p/sandbox/pensive-murdock-rlshh8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt47u44o00072a68fowujf9b%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt47u44o00032a68mxfmal0f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt47u44o00042a68rco5fewm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt47u44o00062a68ilca9dnf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B65.40123738777882%252C34.59876261222118%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt47u44o00032a68mxfmal0f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt47u44o00022a6818vqc65q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clt47u44o00032a68mxfmal0f%2522%252C%2522activeTabId%2522%253A%2522clt47u44o00022a6818vqc65q%2522%257D%252C%2522clt47u44o00062a68ilca9dnf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt47u44o00052a68hektntzq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt47u44o00062a68ilca9dnf%2522%252C%2522activeTabId%2522%253A%2522clt47u44o00052a68hektntzq%2522%257D%252C%2522clt47u44o00042a68rco5fewm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt47u44o00042a68rco5fewm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)but it's not working 

What I want : display Tooltip only when the text is bigger than column size, and the column should be resizabe , so when the colum is bigger than the text there is no need to display Tooltip, hope it's clear, sorry for my english

### Your environment

 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD    
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (120.0.2210.175)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.7
    @mui/core-downloads-tracker:  5.14.0
    @mui/icons-material: ^5.11.16 => 5.14.0
    @mui/material: ^5.12.1 => 5.14.0
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/system:  5.14.0
    @mui/types:  7.2.4
    @mui/utils:  5.13.7
    @mui/x-data-grid:  6.10.0
    @mui/x-data-grid-premium: ^6.10.0 => 6.10.0
    @mui/x-data-grid-pro:  6.10.0
    @mui/x-license-pro: ^6.10.0 => 6.10.0
    @types/react:  18.2.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0

**Search keywords**: DataGridPremium
**Order ID**: 66242

**Comment by michelengelen** [comment]
> I've already searched on Stackoverflow but I did not found the solution for my problem. I think it's a DataGrid feature so that's why I contact you.. thank you

I do understand that this might be misleading ... especially the functionality you are trying to build is hard to do and a problem many devs have tried to solve before you.

you could try with a measuring approach:

```tsx
renderCell: (params) => {
  const textRef = React.useRef(null);
  const [isTruncated, setIsTruncated] = React.useState(false);

  React.useEffect(() => {
    if (textRef.current && textRef.current.scrollWidth > textRef.current.clientWidth) {
      setIsTruncated(true);
    }
  }, [params.row.firstName]);

  return (
    <div ref={textRef}>
      {isTruncated ? (
        <Tooltip title={params.row.firstName} placement="bottom">
          <p>{params.row.firstName}</p>
        </Tooltip>
      ) : (
        <p>{params.row.firstName}</p>
      )}
    </div>
  );
},
```

This example is not working, just as a starting point to understand what has to be done to measure the size of an element.

And on another note: measuring is always hard and you have to take into account the lifecycle of react components as well. At the very least it will have a big impact on the performance of the grid.
