### ISSUE TITLE
[data grid] Show All Button Return Empty Object in GridToolbarColumnsButton

### ISSUE THREAD

**Issue by Shudhanshu-Appnox** [mui/mui-x#12236]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Click on the Show All Button in GridToolbarColumnsButton
2. onColumnVisibilityModelChange returns an empty object in the Model params

### Expected behavior 

When clicking on the Show all columns the model params in onColumnVisibilityModelChange must return an object where all the columns must have the true value.

### Current behavior

When clicking on the Show all columns the model params in onColumnVisibilityModelChange return an Empty Object {}

### Context

In the Export Data, we want to have only those columns that are currently visible for that we are using the onColumnVisibilityModelChange props but in the case of the show all it returns an empty object.

### Your environment

<details>
  <summary><code>@mui/x-data-grid": "^6.18.5</code></summary>

```
 Used the Google Chrome 
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data Grid, GridToolbarColumnsButton, Show All
**Order ID**: #83077

**Comment by shaharyar-shamshi** [comment]
Hello @Shudhanshu-Appnox if you can provide some demo link of example it would be great help for us.

**Comment by shaharyar-shamshi** [comment]
> Hello @shaharyar-shamshi [Link](https://codesandbox.io/p/sandbox/column-visibility-model-change-forked-c9hchd?file=%2Fsrc%2FApp.tsx%3A25%2C80)

Can access I think you need to make it public

**Comment by michelengelen** [comment]
Hey @Shudhanshu-Appnox ... thanks for raising this issue. 🙇🏼 
I did put this on our board for the team to have a look.

**Comment by Shudhanshu-Appnox** [comment]
@shaharyar-shamshi I have made it public now

**Comment by Shudhanshu-Appnox** [comment]
Any Update?

**Comment by omer-pon** [comment]
Hi @Shudhanshu-Appnox , I am having the same issue while migrating from v5 to v6, I see this issue has been closed without providing a proper solution or an explanation.

@michelengelen , did your team have a look at this issue ? If not, please make this issue open.

**Comment by subashthiru3** [comment]
The onColumnVisibilityModelChange event returns an empty object when showing all columns using the columns option in the toolbar. I am still facing this issue

**Comment by abdulhafiz7156** [comment]
Me too, @subashthiru3
