### ISSUE TITLE
[data grid] Not able to have `headerName` for `togglePanel`

### ISSUE THREAD

**Issue by ajayaccuknox** [mui/mui-x#12261]
### Related page

https://mui.com/x/react-data-grid/master-detail/

### Kind of issue

Unclear explanations

### Issue description

So I have a table in the table I need to show the master details under the each row so I have used **toggleDetailPanel** in that I made it successful but the issue is _**I couldn't able to have a separate column name like headerName**_

### Context

So I have a table in the table I need to show the master details under the each row so I have used **toggleDetailPanel** in that I made it successful but the issue is _**I couldn't able to have a separate column name like headerName**_

**Search keywords**: headerName for togglePanel

**Comment by MBilalShafi** [comment]
Could you expand on what you're trying to achieve?
Do you want to add the `headerName` on the header cell of the toggle button (the one with blue border in the image below)?

![image](https://github.com/mui/mui-x/assets/12609561/f9ff1ecc-a915-4b5f-8637-246dcbacd54c)

**Comment by ajayaccuknox** [comment]
> Could you expand on what you're trying to achieve? Do you want to add the `headerName` on the header cell of the toggle button (the one with blue border in the image below)?
> 
> ![image](https://private-user-images.githubusercontent.com/12609561/308900255-f9ff1ecc-a915-4b5f-8637-246dcbacd54c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDYzMTAsIm5iZiI6MTcwOTIwNjAxMCwicGF0aCI6Ii8xMjYwOTU2MS8zMDg5MDAyNTUtZjlmZjFlY2MtYTkxNS00YjVmLTg2MzctMjQ2ZGNiYWNkNTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDExMjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OTIyYmNmYTkzOWRiZmRkMDAxMWU2NWIyMzUwYzNiMWY3YTBlNTY4YTgzODg3YWM5ZGFlMTMwM2U0ZDc1OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v-USoxOD8JWAsWCr9TWk55xlPHN-qsKJ-3Q5bbzycsA)

Yes exactly @MBilalShafi

**Comment by michelengelen** [comment]
@ajayaccuknox it is possible to render a custom header for the toggle column. You can use this section of the docs as a starting point: [Customizing the detail panel toggle](https://mui.com/x/react-data-grid/master-detail/#customizing-the-detail-panel-toggle)

What you have to do is:
1. use `GRID_DETAIL_PANEL_TOGGLE_COL_DEF` definition in your columns
2. spread the default definition and
3. overwrite the `renderHeader` method

example:
```tsx
const columns: GridColDef[] = [
  {
    ...GRID_DETAIL_PANEL_TOGGLE_COL_DEF,
    renderHeader: () => <div>Details</div>,
  },
  { field: 'id', headerName: 'Order ID' },
  { field: 'customer', headerName: 'Customer', width: 200 },
];
```

Just using `headerName` is not sufficient.

Let me know if this answers your question.

@MBilalShafi we could maybe add a recipe to show how that works. WDYT?
