### ISSUE TITLE
[charts] Is there a non 'band' scale type layout for bar charts?

### ISSUE THREAD

**Issue by mbond-SCW** [mui/mui-x#12269]
### The problem in depth

Hello!

I am working on a conversion from Recharts to Mui Charts and building out our Bar Chart presentational wrapper, with two primary use cases:  Categorical (standard bar chart stuff), and distribution along a range (binning/histogram).  For the second case, our original design used labels on the xAxis ticks in this style:
 
<img width="687" alt="Screenshot 2024-02-29 at 8 34 07 PM" src="https://github.com/mui/mui-x/assets/110430690/08ab1ce0-2b52-469c-bb38-8c5cec877e3f">

My question:
   Is there a configuration that allows the axis labels to be centered on the ticks for bar charts?  
   
   I have played around with the examples here (https://mui.com/x/react-charts/axis/), so I'm comfortable with a styling solution for simply moving the tick labels along the axis,  but I would prefer a less brittle solution if possible.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
All changes tested on Google Chrome

  System:
    OS: macOS 14.3.1
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 4.0.2 - ~/.asdf/installs/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.asdf/installs/nodejs/18.16.0/bin/npm
  Browsers:
    Chrome: 122.0.6261.94
    Edge: Not Found
    Firefox: 122.0
    Safari: 17.3.1
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.37 
    @mui/core-downloads-tracker:  5.15.11 
    @mui/icons-material: ^5.15.11 => 5.15.11 
    @mui/lab: ^5.0.0-alpha.166 => 5.0.0-alpha.166 
    @mui/material: ^5.15.11 => 5.15.11 
    @mui/private-theming:  5.15.11 
    @mui/styled-engine:  5.15.11 
    @mui/system:  5.15.11 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.11 
    @mui/x-charts: ^7.0.0-beta.4 => 7.0.0-beta.4 
    @mui/x-data-grid:  6.19.5 
    @mui/x-data-grid-premium: ^6.19.5 => 6.19.5 
    @mui/x-data-grid-pro:  6.19.5 
    @mui/x-date-pickers:  6.19.5 
    @mui/x-date-pickers-pro: ^6.19.5 => 6.19.5 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.58 => 18.2.58 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 
```
</details>

**Search keywords**: histogram axis ticks
**Order ID**: I'm filing this as a dev and don't have either of those things ^

**Comment by michelengelen** [comment]
AFAIK this is not possible OOTB for the BarCharts. 
@alexfauquette do you mind setting this as a new feature request or rather an enhancement?

**Comment by alexfauquette** [comment]
Maybe with hacky solution I would not recommend 🙈

> I am working on a conversion from Recharts to Mui Charts

@mbond-SCW Could you share the code of this bar chart? Because even with Rechart I don't see how you can get it without doing weird stuff. So not sure if it's a missing feature, or just I miss understand what the chart is doing

**Comment by mbond-SCW** [comment]
> @mbond-SCW Could you share the code of this bar chart? Because even with Rechart I don't see how you can get it without doing weird stuff. So not sure if it's a missing feature, or just I miss understand what the chart is doing

Most definitely!  It's actually the 'scale' property on their xAxis that moves the ticks/labels.

[Here's a recharts barchart sandbox with `scale='band'`](https://codesandbox.io/p/sandbox/simple-bar-chart-forked-f982zp?file=%2Fsrc%2FApp.tsx%3A10%2C10)

As an aside, there are some interesting side-effects that occur with their implementation (specifically hover/tooltip behavior, which *can* be fixed, but requires some finicky onMouseOver code), and it appears this was added more recently to the Recharts library (1.x versions of Recharts definitely didn't have this, since I checked on their demo components first, which use pre-2.x).

**Comment by alexfauquette** [comment]
Effectively, the behavior of mouse hover is a bit weird. Maybe we can get similar behavior by just modifying how ticks and tick label are placed without touching this notion of scale which is for now delegated to d3.js

![image](https://github.com/mui/mui-x/assets/45398769/0cbe3616-783b-4fa1-a1db-3aec6e39825f)

**Comment by alexfauquette** [comment]
The generation of tick/label position is done here for the band scale:

https://github.com/mui/mui-x/blob/e7694b34a459235d9335725532f23142bf339a1a/packages/x-charts/src/hooks/useTicks.ts#L74-L90

I propose to add the following properties to band scales, and adapt the computation of `offset` and `labelOffset` accordingly

- `tickPlacement?: 'start' | 'end' | 'middle' | 'extremities'`
- `tickLabelPlacement?: 'start' | 'end' | 'middle'`
