### ISSUE TITLE
[charts] Custom tooltip doesnt work with slots, only with deprecated axisContent and itemContent.

### ISSUE THREAD

**Issue by youngmoon715** [mui/mui-x#12268]
### Steps to reproduce

Link to live example: (required)
[Custom Tooltip with slots not working](https://codesandbox.io/p/sandbox/hopeful-wright-zn2rkq?file=%2FDemo.tsx)
[Custom Tooltip with deprecated itemContent working](https://codesandbox.io/p/sandbox/determined-dew-mkctjw?file=%2FDemo.tsx)

Steps:
1.  In the first link, see that `tooltip.slots.itemContent` or `axisContent` does not work.
2. In the second link, see that although `tooltip.itemContent` works, in the docs, it says deprecated. Currently this seems to be the only option of customization

### Current behavior

In the [doc](https://mui.com/x/api/charts/charts-tooltip/#slots), it says itemContent and axisContent props are deprecated, and instead we should use slots. However, currently the slots doesnt work.

### Expected behavior

Slots should work correctly when using custom elements.

### Context

Use the slots as the doc intended for tooltips.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: charts, tooltip, slots, deprecated

**Comment by michelengelen** [comment]
@alexfauquette it seems as if #9744 did introduce this.

```diff
diff --git a/packages/x-charts/src/BarChart/BarChart.tsx b/packages/x-charts/src/BarChart/BarChart.tsx
index 024947143..59a2aa919 100644
--- a/packages/x-charts/src/BarChart/BarChart.tsx
+++ b/packages/x-charts/src/BarChart/BarChart.tsx
@@ -148,6 +148,8 @@ const BarChart = React.forwardRef(function BarChart(props: BarChartProps, ref) {
     ...(hasHorizontalSeries ? ({ y: 'band' } as const) : ({ x: 'band' } as const)),
     ...axisHighlight,
   };
+
+  console.log('toolttip', tooltip);
   return (
     <ResponsiveChartContainer
       ref={ref}
@@ -197,7 +199,7 @@ const BarChart = React.forwardRef(function BarChart(props: BarChartProps, ref) {
       />
       <ChartsLegend {...legend} slots={slots} slotProps={slotProps} />
       <ChartsAxisHighlight {...defaultizedAxisHighlight} />
-      <ChartsTooltip {...tooltip} slots={slots} slotProps={slotProps} />
+      <ChartsTooltip {...tooltip} />
       <ChartsClipPath id={clipPathId} />
       {children}
     </ResponsiveChartContainer>
```

This solves the issue.
Can you confirm that this fix would solve it?

**Comment by alexfauquette** [comment]
For me the correct usage would be 


```diff
tooltip={{
  trigger: "item",
-  itemContent: CustomItemTooltipContent
}}
+ slots={{ itemContent: CustomItemTooltipContent }}
```

Maybe we need to clarify the docs
