### ISSUE TITLE
[data grid] CustomToolbar and loading overlay disappeared for no reason

### ISSUE THREAD

**Issue by catdalf** [mui/mui-x#12270]
I currently use 
```tsx
slots={{
  Toolbar: () => <CustomToolbar data={data} />,
  LoadingOverlay : LinearProgress,
}}
```
this code to make the CustomToolbar and loading overlay be displayed. And this was working without no problems yesterday. Today when i run the code i saw problems like these for this specific code chunk:

1.  property expected
2. ';' expected.
3. Expression expected.
4. Declaration or statement expected.
(These are PROBLEMS not ERRORS that doesn't make me cause to not run npm start in a successful way.

This is also another information about the problems that occured. When i copy and paste this information i see this:
```tsx
[{
	"resource": "48563ae0-4222-4440-bdcb-44a0504202c5",
	"owner": "typescript",
	"code": "1136",
	"severity": 8,
	"message": "Property assignment expected.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 8,
	"endLineNumber": 1,
	"endColumn": 9
},{
	"resource": "48563ae0-4222-4440-bdcb-44a0504202c5",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' expected.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 17,
	"endLineNumber": 3,
	"endColumn": 18
},{
	"resource": "48563ae0-4222-4440-bdcb-44a0504202c5",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 1,
	"endLineNumber": 4,
	"endColumn": 2
},{
	"resource": "48563ae0-4222-4440-bdcb-44a0504202c5",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Declaration or statement expected.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 2,
	"endLineNumber": 4,
	"endColumn": 3
}]
```

which were nonesense. Then i closed and opened the vscode cause i thought that this was something that could be solved like this. When i have done that the problems have disappeared but the buttons, density selectors etc. that i have created and have in my CustomToolbar have disappeared now i can not see them.

Could you please help about this?

Thanks 

**Search keywords**:

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by catdalf** [comment]
Turns out it was just an capital-lower case issue for toolbar "toolbar" should be used and instead LoadingOverlay, "loadingOverlay" should be used. Sorry for not checking documentation for usage of these first, This issue can be closed now.

**Comment by michelengelen** [comment]
Thanks for confirming this! Happy to help if you need any further advice!
