### ISSUE TITLE
[data grid] rowHeight={undefined} does not show "no rows" or loading

### ISSUE THREAD

**Issue by mlonn** [mui/mui-x#12273]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/elastic-glitter-67fd3x?file=%2Fsrc%2FDemo.tsx%3A20%2C9

Steps:
1. Supply undefined to the `rowHeight` prop to the DataGrid component

### Current behavior

Collapses the "No rows" and "Loading" state so it's not visible

### Expected behavior

The "Now Row" and "Loading" state should be visible

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: latest => 11.11.4 
    @emotion/styled: latest => 11.11.0 
    @mui/icons-material: latest => 5.15.11 
    @mui/material: latest => 5.15.11 
    @mui/x-data-grid: latest => 6.19.5 
    @mui/x-data-grid-generator: latest => 6.19.5 
    @types/react: latest => 18.2.61 
    react: latest => 18.2.0 
    react-dom: latest => 18.2.0 
    typescript: latest => 5.3.3 

```
</details>
Version 122.0.6261.69 (Official Build) (arm64)

**Search keywords**: DataGrid rowheight data grid row height

**Comment by michelengelen** [comment]
Correct me if I am wrong @romgrk or @MBilalShafi, but this seems like expected behavior to me. 🤔

**Comment by michelengelen** [comment]
For reference @mlonn ... this section of the code is responsible for setting the initial props:

https://github.com/mui/mui-x/blob/f42e9b7d789ab9bd0240081ab69639a47cc45758/packages/x-data-grid/src/DataGrid/useDataGridProps.ts#L107-L116

And when you pass in `rowHeight={undefined}` it will result in `themedProps.rowHeight` also being undefined and overwriting `DATA_GRID_PROPS_DEFAULT_VALUES.rowHeight`. It's a different story for `getRowHeight`. Per definition this method is used to set the `rowHeight` per individual row and the default content height (which is needed to render the `loading` or `no rows` overlay) is being calculated from the `rowHeight` prop

**Comment by mlonn** [comment]
@michelengelen Ok, I ran in to this issue with creating a wrapper component to `DataGrid` with a custom pagination component, with forwards the `rowHeight` prop, and the tables that did not define the rowHeight had it's `loading` and `no rows` not behave as I expeced

**Comment by michelengelen** [comment]
> @michelengelen Ok, I ran in to this issue with creating a wrapper component to `DataGrid` with a custom pagination component, with forwards the `rowHeight` prop, and the tables that did not define the rowHeight had it's `loading` and `no rows` not behave as I expeced

in this specific case you could just not forward the `rowHeight` prop or just define you own default value (default in our package is `52px` and the default content height for the overlays is `2 * rowHeight`).

**Comment by michelengelen** [comment]
> So the 'correct' version of my component would be
> 
> `rowHeight={rowHeight || DATA_GRID_PROPS_DEFAULT_VALUES.rowHeight}`

Basically yes, or just define your own!
