### ISSUE TITLE
[data grid] Flex columns causes column grouping headers to become un-aligned from their columns for some column resizes

### ISSUE THREAD

**Issue by ken-bimmel** [mui/mui-x#12290]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-cecf1r?file=Demo.tsx
Steps:
1. Create a DataGrid with the following column definitions:
   ```
   { field: 'field1', flex: 1 },
   { field: 'field2', flex: 1 },
   { field: 'field3', flex: 0 },
   ```
2. Create a grouping model as follows:
   ```
   [
          {
            groupId: 'Group1',
            children: [{ field: 'field1' }, { field: 'field2' }],
          },
          {
            groupId: 'Group2',
            children: [{ field: 'field3' }],
          },
   ]
   ```
3. Enable column grouping and provide the grouping model from above.
4. Take the right edge of the `field2` column and shrink it.

### Current behavior

Following the steps above will leave you with group headers that are mis-aligned. The header for the `Group1` group does not grow in size to reflect the growth of the `field1` column to fill the space left when `field2` was shrunk. Instead the header for `Group1` is the width of the `field1` and `field2` columns when the `field2` column was shrunk.

This leaves the header for `Group2` too far left and misaligned with the header for `field3`.

![image](https://github.com/mui/mui-x/assets/5448159/657a5d53-b796-4bb9-9088-8dfc8a150f17)

### Expected behavior

I would expect the header for `Group1` to resize to match the size of the `field1` and `field2` columns after the flex has resized them, so that all group headers remain aligned with their columns.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
MUI Data Grid Version: 6.19.5
MUI Material Version: 5.15.11
React Version: 18.2
Chrome Version 120.0.6099.225

</details>

**Search keywords**: column grouping, resize, alignment, flex, data grid

**Comment by michelengelen** [comment]
@MBilalShafi this is indeed a bit weird. The width calculation seems to be off, when `flex` and resized columns are used in conjunction. It might be that the flex calculation is done after the groups get updated.

Its reproducible with all columns having `flex: 1`:
1. decrease width of `field3` column
2. decrease width of `field2` column

It is reproducible in `v6` and `v7`

I will add this to the board!
Thanks @ken-bimmel for reporting this!

**Comment by arminmeh** [comment]
Hey @michelengelen is it fine if I take this one?
