### ISSUE TITLE
[data grid] How do I Export The Save State Item To LocalStorage

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#12291]
### The problem in depth

Ok,  I'd like to get this example: https://codesandbox.io/p/sandbox/shy-paper-8cngkv?file=%2Fsrc%2FDemo.js%3A180%2C27 from the examples to save to local storage. It never calls localStorage.setItem like this example https://codesandbox.io/p/sandbox/vibrant-johnson-5gzqgz?file=%2Fsrc%2FDemo.js%3A20%2C7-20%2C27

I got both of these from the documentation.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 7.24.2 - ~/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.71
  npmPackages:
    @emotion/react: latest => 11.11.3 
    @emotion/styled: latest => 11.11.0 
    @mui/base:  5.0.0-beta.32 
    @mui/core-downloads-tracker:  5.15.5 
    @mui/icons-material: ^5.15.3 => 5.15.5 
    @mui/lab: ^5.0.0-alpha.159 => 5.0.0-alpha.161 
    @mui/material: ^5.15.3 => 5.15.5 
    @mui/private-theming:  5.15.5 
    @mui/styled-engine:  5.15.5 
    @mui/styles: ^5.15.3 => 5.15.5 
    @mui/system:  5.15.5 
    @mui/types:  7.2.13 
    @mui/utils: ^5.15.4 => 5.15.5 
    @mui/x-data-grid:  6.19.1 
    @mui/x-data-grid-generator: ^6.16.2 => 6.19.1 
    @mui/x-data-grid-premium: ^6.19.1 => 6.19.1 
    @mui/x-data-grid-pro:  6.19.1 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react:  17.0.75 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: latest => 6.1.8 
```
</details>

**Search keywords**: localStorage
**Order ID**: 66765

**Comment by michelengelen** [comment]
Hey @lisaWriteJava what exactly are you trying to do? 
The first example you gave is not using `localStorage` at all, only internal state.

Please provide a more detailed explanation and, when possible, a minimal reproduction example.

**Comment by lisaWriteJava** [comment]
Yes, I'd  figure out how to change the 1st example to use localstorage instead of internal storage like the 2nd.

**Comment by michelengelen** [comment]
You just have to replace the usage of `useReducer` with using `localStorage`. 
But this specific problem is unrelated to our components. Please use StackOverflow for implementation specific questions like these.
