### ISSUE TITLE
[data grid] Column reordering drag and drop not working in mobile

### ISSUE THREAD

**Issue by joacub** [mui/mui-x#12310]
### Steps to reproduce

https://mui.com/x/react-data-grid/column-ordering/

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Columns

**Comment by michelengelen** [comment]
@mui/xgrid do we even support drag and drop for mobile on the data grid?

**Comment by joacub** [comment]
> @mui/xgrid do we even support drag and drop for mobile on the data grid?

yes you were supporting that.

**Comment by joserodolfofreitas** [comment]
It's unfortunately not supported. We have indeed a general problem to solve with drag'n'drop and touch screens at this moment, and there's already another issue with a related PR: https://github.com/mui/mui-x/issues/9330
The mentioned PR ended up buried under other requests, though, and we should definitely get back to it as soon as possible.

**Comment by romgrk** [comment]
Let's close this one as duplicate in favor of #9330.
