### ISSUE TITLE
[data grid] Horizontal Scrolling with the help of Keyboard in the DataGrid.

### ISSUE THREAD

**Issue by vks-dev** [mui/mui-x#12314]
I have a datagrid that I implemented in the project, that datagrid has some columns that are visible by default and some are invisible by default. When any of the column that is invisible set to visible then the width of the datagrid goes beyond the width of the viewport and I want to be able to scroll from one side to the other with the help of keyboard arrow keys with dynamic column visbility in mind. 

I already am using ```.getScrollPosition()``` and ```.scrollToIndexes({})``` but I think I am getting an error while converting the pixels that .getScrollPosition() returns into index values for .scrollToIndexes({}).

This is the entire logic that I'm using for the event listener and everything related to that:

```
  const visibleColumns = columns.filter(column => columnVisibilityModel[column.field])

  const columnWidths = visibleColumns.map((column) => column.width);

  const handleKeyboardScroll = (e) => {
    const { left } = apiRef.current.getScrollPosition();
  
    if (e.code === "ArrowRight") {
      const nextColIndex = findPrevColumnIndex(left, columnWidths);
      apiRef.current.scrollToIndexes({ colIndex: nextColIndex });
    } else if (e.code === "ArrowLeft") {
      const nextColIndex = findNextColumnIndex(left, columnWidths);
      apiRef.current.scrollToIndexes({ colIndex: nextColIndex });
    }
  };

  const findNextColumnIndex = (scrollLeft, columnWidths) => {
    let totalWidth = 0;
    for (let i = 0; i < columnWidths.length; i++) {
      totalWidth += columnWidths[i];
      if (totalWidth > scrollLeft) {
        return i;
      }
    }
    return columnWidths.length - 1;
  };

  const findPrevColumnIndex = (scrollLeft, columnWidths) => {
    let totalWidth = 0;
    for (let i = columnWidths.length - 1; i >= 0; i--) {
      totalWidth += columnWidths[i];
      if (totalWidth > scrollLeft) {
        return i;
      }
    }
    return 0;
  };
  ```

**Search keywords**:

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by vks-dev** [comment]
Ok, Let me clarify the details. I have a datagrid present in my porject as is in the pic below
![Screenshot 2024-03-05 094221](https://github.com/mui/mui-x/assets/68587409/c17dc9d1-94a3-4294-ab39-3e69d67d3adb)
and these are the columns that are present in that datagrid as you can see some of them are hidden by default and some are not.
![Screenshot 2024-03-05 094426](https://github.com/mui/mui-x/assets/68587409/c97e6f4f-8dda-4614-aeb4-6d5ff05f6ab5)
Now I want to be able to scroll through the datagrid using my keyboard as present in the below video

https://github.com/mui/mui-x/assets/68587409/00689698-46e3-44a9-a691-72729cdc6612

I have already implemented this feature in other datagrid's, which don't have the dynamic column visibility and it's working fine in them. Is there any in-built method or way I can use tho implement this functionality other than what I already used in above code?

**Comment by michelengelen** [comment]
We are already supporting navigating the grid with keyboard input. Just take this demo we have on the docs: [Scrolling](https://mui.com/x/react-data-grid/scrolling/)

You can navigate around the grid with arrow keys, change the column visibility, etc. with no impact to the keyboard capability.

**Comment by vks-dev** [comment]
Thank you, I got what I was looking for.

**Comment by michelengelen** [comment]
Ok, great to see that you found what you were looking for.
if you encounter issues please don't hesitate to open an issue again.
