### ISSUE TITLE
[charts] Pie chart sizing

### ISSUE THREAD

**Issue by revathy-blitz** [mui/mui-x#12333]
### Related page

https://mui.com/x/react-charts/styling/

### Kind of issue

Unclear explanations

**Search keywords**: piechart, size

**Comment by michelengelen** [comment]
I am not sure what you have been trying before, but it works pretty well for me.
Here is a little example of that: [Pie chart sizing](https://stackblitz.com/edit/react-5gs2jo?file=Demo.tsx)
