### ISSUE TITLE
[data grid] Export to Excel isn't working

### ISSUE THREAD

**Issue by chezkibotwinick** [mui/mui-x#12339]
### The problem in depth

Hi, 

I am experiencing an issue with the `DataGridPremium` component when attempting to export as Excel. While everything works as expected in my local environment, I encounter the following error in different environments:

<img width="826" alt="image" src="https://github.com/mui/mui-x/assets/98471178/a13db2c0-53de-4b74-a21a-e4dfa50f7091">

It seems that the component is trying to fetch data from the local environment for some reason. I came across a [previous issue](https://github.com/mui/mui-x/issues/9308) opened on this page, but it did not provide any steps for resolving the issue.

This error occurs both by using the `GridExcelExportMenuItem` and by using the `getDataAsExcel` api. 

I have tried different versions, including the latest, but the error persists.
I would greatly appreciate your assistance in resolving this issue.

Thanks

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Export to Excel
**Order ID**: 85670

**Comment by chezkibotwinick** [comment]
Hey, I accidentally closed this and it is still an issue. 
Can I please get assistance here? 
Thanks.

**Comment by michelengelen** [comment]
Hey @cherniavskii could you have a look at this? 

In the meantime could you provide us with a little more info on your setup and implementation @chezkibotwinick ? Also did you try manually installing `exceljs` as suggested [here](https://github.com/mui/mui-x/issues/9308#issuecomment-1593311474)?

**Comment by chezkibotwinick** [comment]
Hey @michelengelen. 

- I tried manually installing `exceljs` (version: `"^4.4.0"`) and still same error. 
- These are the `mui` dependencies I am using: 
   -  "@mui/material": "^5.13.0",
   - "@mui/system": "^5.12.3",
   -  "@mui/x-data-grid": "^6.4.0",
   - "@mui/x-data-grid-premium": "^6.4.0"
 
Both following implementation result in same error as I shared above: 
Regular: 
```
    <GridToolbarExportContainer>
      <GridExcelExportMenuItem />
      <GridPrintExportMenuItem />
    </GridToolbarExportContainer>
```

Using custom method: 
```

  const exportAsExcel = async () => {
    const workbook = await apiRef?.current?.getDataAsExcel();
    ...
  };

  <GridToolbarExportContainer>
    <MenuItem onClick={exportAsExcel}>Download as Excel</MenuItem>
    <GridExcelExportMenuItem />
    <GridPrintExportMenuItem />
  </GridToolbarExportContainer>

```

**Comment by chezkibotwinick** [comment]
@michelengelen thanks for looking into it and for your support :) 

I removed `x-data-grid` but the same error still occurs. 

Re setup - I am using React `"^18.0.14"`.

**Comment by michelengelen** [comment]
I am not able to reproduce this issue.
The setup I was using:
```
  "dependencies": {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.0",
    "@mui/material": "^5.15.12",
    "@mui/system": "^5.12.3",
    "@mui/x-data-grid-premium": "^6.4.0",
    "next": "14.1.3",
    "react": "^18",
    "react-dom": "^18"
  },
```
Ran a production build locally and I can export without a problem from it.
@cherniavskii maybe that helps for a further investigation.

BTW: @chezkibotwinick could you post the full stacktrace for the error you got from exporting? I am a bit baffled that it states that it occurs in `bootstrap:126` ... are you using bootstrap by any chance?

**Comment by cherniavskii** [comment]
Hi @chezkibotwinick 
What bundler do you use?

The issue _could_ be related to the usage of dynamic import:
https://github.com/mui/mui-x/blob/848f2a1d3c40a84aecec4d31e09b3b49cd47903c/packages/x-data-grid-premium/src/hooks/features/export/serializer/excelSerializer.ts#L26-L27
But I need a reproduction example to be able to investigate.

**Comment by cherniavskii** [comment]
@michelengelen 
> Ran a production build locally and I can export without a problem from it.

Yeah, it works fine with `next`: https://mui.com/x/react-data-grid/export/#excel-export

**Comment by chezkibotwinick** [comment]
@michelengelen I am not using `bootstrap` in my project. 

@cherniavskii using `webpack`.

**Comment by chezkibotwinick** [comment]
@michelengelen this is the trace: 
![image](https://github.com/mui/mui-x/assets/98471178/eddc030c-18dc-4983-8c36-c537e23ed689)

**Comment by michelengelen** [comment]
> But I need a reproduction example to be able to investigate.

Could you maybe create a sample repo that uses `webpack` with a minimal reproduction example for us? That would help us a lot. In the meantime I will try and setup a project with webpack myself
