### ISSUE TITLE
[charts] Add label for bar chart

### ISSUE THREAD

**Issue by holospice18** [mui/mui-x#12331]
### Summary

It is posible for Barchart to have inline text?
Maybe even just for `stackOffset : "expand"` since it use percentage 
Like on Pie chart
https://mui.com/x/react-charts/pie-demo/#piechartwithcustomizedlabel

### Examples

![image](https://github.com/mui/mui-x/assets/145089013/37b76abd-5464-4fb3-973f-3ac5b8dec9d0)

**Search keywords**: chart

**Comment by michelengelen** [comment]
Hey @holospice18 afaik know this is currently not possible ... at least not as a built in feature. So I did add this to our board as a feature request.

@alexfauquette do you know if we can provide a small workaround in the meantime?

**Comment by alexfauquette** [comment]
A work around would be to override the `bar` slot to also display text.

But a proper solution would be to render all those labels together like we do for pie chart.


By overriding `slots.bar` you would get this

```jsx
<rect/>// small rectangle
<text/>// text centered on the first rectangle but overflow
<rect/>// large rectangle which will hide the overflowing part of the previous text
<text/>// text centered on the second rectangle but overflow
```

here is a long term solution

```jsx
<rect/>// small rectangle
<rect/>// large rectangle
<text/>// text centered on the first rectangle but overflow
<text/>// text centered on the second rectangle but overflow
```

**Comment by bexoss** [comment]
+1 

IMHO, This is most important function in many charts use cases.

**Comment by thomasl04wapo** [comment]
> A work around would be to override the `bar` slot to also display text.
> 
> But a proper solution would be to render all those labels together like we do for pie chart.
> 
> By overriding `slots.bar` you would get this
> 
> ```js
> <rect/>// small rectangle
> <text/>// text centered on the first rectangle but overflow
> <rect/>// large rectangle which will hide the overflowing part of the previous text
> <text/>// text centered on the second rectangle but overflow
> ```
> 
> here is a long term solution
> 
> ```js
> <rect/>// small rectangle
> <rect/>// large rectangle
> <text/>// text centered on the first rectangle but overflow
> <text/>// text centered on the second rectangle but overflow
> ```

How do you override the `bar` slot? Is that using the `BarElement` component, then plugging that into `BarChart`?

**Comment by alexfauquette** [comment]
> How do you override the bar slot? Is that using the BarElement component, then plugging that into BarChart?

Here is an example https://stackblitz.com/edit/react-rcwehj?file=Demo.tsx
