### ISSUE TITLE
[data grid] White space when expanding GridToolbarColumnsButton 

### ISSUE THREAD

**Issue by samuelcastro** [mui/mui-x#12341]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Import DataGrid Pro
2. Click on GridToolbarColumnsButton

### Current behavior

A white space shows up when users click on GridToolbarColumnsButton

### Expected behavior

No white space

### Context

![Screenshot 2024-03-05 at 2 46 44 PM](https://github.com/mui/mui-x/assets/5281701/132b4a2d-db28-40ca-a83d-c2eb3155fe24)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Chrome

System:
    OS: macOS 13.5.1
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    npm: 10.2.3 - ~/Projects/my-project/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.94
    Edge: Not Found
    Safari: 17.3.1
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.3
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base: ^5.0.0-beta.23 => 5.0.0-beta.23
    @mui/codemod: ^5.15.11 => 5.15.6
    @mui/core-downloads-tracker:  5.15.6
    @mui/icons-material: ^5.15.11 => 5.15.6
    @mui/lab: ^5.0.0-alpha.152 => 5.0.0-alpha.152
    @mui/material: ^5.15.11 => 5.15.6
    @mui/private-theming:  5.15.6
    @mui/styled-engine:  5.15.6
    @mui/styles: ^5.15.11 => 5.15.6
    @mui/system:  5.15.6
    @mui/types:  7.2.13
    @mui/utils:  5.15.6
    @mui/x-data-grid: ^5.15.0 => 5.17.26
    @mui/x-data-grid-pro: ^5.15.0 => 5.17.26
    @mui/x-date-pickers: ^5.0.0-beta.3 => 5.0.20
    @mui/x-license-pro: ^5.15.0 => 5.17.12
    @types/react: ^18.2.60 => 18.2.48
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.3.3 => 5.3.3
```
</details>

**Search keywords**: GridToolbarColumnsButton

**Comment by michelengelen** [comment]
Hi @samuelcastro I cannot reproduce the described behavior ... could you please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
