### ISSUE TITLE
[data grid] right row border is not visible

### ISSUE THREAD

**Issue by yehudamakarov** [mui/mui-x#12340]
#### general info
see previous issues, but I cannot find a reliable answer.
- #4200 
- #7956
- #8790

my use case is rows that are spaced and with a round border. the right side of these bordered rows will be hidden.

#### The goal:
<img width="969" alt="Screenshot 2024-03-05 at 11 31 33 AM" src="https://github.com/mui/mui-x/assets/27930483/d6acb185-83d8-42d7-9717-ae3c470a1356">

#### The outcome:
<img width="170" alt="Screenshot 2024-03-05 at 11 35 47 AM" src="https://github.com/mui/mui-x/assets/27930483/f9f72f89-b2c9-4dfa-93ca-7743ea4f44da">
---
#### what you can try and how it falls short
- you can add `width: 'calc(100% - 2px)',` to the row **but** it doesn't work at random screen widths with `flex`
    - if you use `flex` for the columns, there is some pseudo cell added on some screen widths (mentioned above)
    - this again hides the border (and the outline if the cell is selected)
- you can try to add a right border to the last cell of a row
- etc.
##### either way...
- eventually the pseudo cell shows up
- is there any way around this? 

thanks

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
npx @mui/envinfo

  System:
    OS: macOS 14.2.1
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.94
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1
    @emotion/styled: 11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.24
    @mui/core-downloads-tracker:  5.14.19
    @mui/icons-material: ^5.14.18 => 5.14.18
    @mui/lab: ^5.0.0-alpha.153 => 5.0.0-alpha.153
    @mui/material: ^5.14.18 => 5.14.19
    @mui/private-theming:  5.14.19
    @mui/styled-engine:  5.14.19
    @mui/system:  5.14.19
    @mui/types:  7.2.10
    @mui/utils:  5.14.19
    @mui/x-data-grid: ^6.19.4 => 6.19.4
    @mui/x-data-grid-generator: ^6.18.3 => 6.18.3
    @mui/x-data-grid-premium: ^6.19.4 => 6.19.4
    @mui/x-data-grid-pro:  6.19.4
    @mui/x-date-pickers: ^6.18.2 => 6.19.0
    @mui/x-date-pickers-pro: ^6.19.0 => 6.19.0
    @mui/x-license-pro:  6.10.2
    @types/react: 18.2.33 => 18.2.33
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.2.2 => 5.2.2

```
</details>

**Search keywords**: border row right visible
**Order ID**: 83930

**Comment by michelengelen** [comment]
Hey @yehudamakarov could you try and replicate this in a codesandbox for us? A grid with demo data should be good, but please make sure that the styles from your implementation are applied. Thanks!

**Comment by michelengelen** [comment]
I did play around with it a bit and here is what I came up with so far: [Borderradius on rows](https://stackblitz.com/edit/borderradius-rows)

Looks as if the `calc` is working even with `flex` on the rows.

One thing that is still missing is the selected outline. That still seems a bit off. @romgrk any idea how to fix that?

**Comment by yehudamakarov** [comment]
@michelengelen in your example, if you add `'border': 0,` to the table styles you will see how on the right side, the rows don't have a border - and that is a working example for the problem (i believe)

**Comment by romgrk** [comment]
Does this work for you? https://stackblitz.com/edit/borderradius-rows-6pf44u?file=Demo.tsx

**Comment by yehudamakarov** [comment]
@romgrk that example looks like it was working really well. i will try to use that example on my end, and update here.
would love to have less to maintain in terms of css though, 🤔

**Comment by romgrk** [comment]
I realize that the CSS is not pretty, however I don't think we'd be modifying the grid for this feature. The layout calculations require pixel accuracy to layout the elements (rows & cells) at their correct locations, and we only consider borders in specific locations: between rows, and between cells. Including borders that can span around rows would add a lot of custom logic. The `::before` trick is by far the most maintainable approach to get the design you want.

**Comment by yehudamakarov** [comment]
I totally hear and love how there’s something that seems robust here. We can abstract this away in one place and use it as a base table somehow.

Thanks,
Yehuda Makarov

**Comment by yehudamakarov** [comment]
just leaving for reference:

> Does this work for you? https://stackblitz.com/edit/borderradius-rows-6pf44u?file=Demo.tsx

```
import * as React from 'react';
import { DataGrid, gridClasses } from '@mui/x-data-grid';
import { useDemoData } from '@mui/x-data-grid-generator';

const VISIBLE_FIELDS = ['name', 'country', 'isAdmin'];

export default function BasicExampleDataGrid() {
  const { data } = useDemoData({
    dataSet: 'Employee',
    visibleFields: VISIBLE_FIELDS,
    rowLength: 100,
  });

  const columns = React.useMemo(
    () => data.columns.map((column) => ({ ...column, flex: 1 })),
    [data]
  );

  return (
    <div style={{ height: 400, width: '100%' }}>
      <DataGrid
        {...data}
        columns={columns}
        sx={{
          border: 0,
          '--custom-padding': '12px',
          [`& .${gridClasses.virtualScrollerRenderZone}`]: {
            paddingTop: 'var(--custom-padding)',
            paddingBottom: 'var(--custom-padding)',
            gap: 'var(--custom-padding)',
          },
          [`& .${gridClasses.row}`]: {
            position: 'relative',
          },
          [`& .${gridClasses.row}::before`]: {
            position: 'absolute',
            content: '" "',
            height: '100%',
            border: '1px solid #e0e0e0',
            borderRadius: '4px',
            width: 'calc(100% - 22px)',
          },
          [`& .${gridClasses.cell}`]: {
            border: 'none',
          },
        }}
      />
    </div>
  );
}
```

**Comment by vicasas** [comment]
For those who need to apply borders to rows and achieve the desired design, you can use the following solution:

```tsx
row: {
  backgroundColor: '#FFF',
  '&.Mui-selected:not(.MuiDataGrid-scrollbarFiller)': {
  },
},
cellSkeleton: {
  '&:first-of-type': {
    borderLeft: '1px solid var(--DataGrid-rowBorderColor)',
  },
  '&:nth-child(2)': {
    borderLeft: 'none',
  },
},
cell: {
  borderTop: '1px solid var(--DataGrid-rowBorderColor)',
  borderBottom: '1px solid var(--DataGrid-rowBorderColor)',
  '&:nth-child(2)': {
    borderLeft: '1px solid var(--DataGrid-rowBorderColor)',
  },
  '&.MuiDataGrid-cellEmpty': {
    width: 1,
    height: 'auto',
    borderRight: '1px solid var(--DataGrid-rowBorderColor)',
  },
},
```

This adds a visual border to the entire row, applying borders to each cell where appropriate.

If your design requires rounded borders, the above solution still works but may have a small visual glitch:

The row extends to the last invisible cell (MuiDataGrid-scrollbarFiller), which causes the layout to break when a row is selected or hovered, as the styles collapse to the right, making the border misalign with the last element or cell in the row.

```tsx
row: {
  backgroundColor: '#FFF',
  borderRadius: 'var(--DataGrid-t-radius-base)',
  '&.Mui-selected:not(.MuiDataGrid-scrollbarFiller)': {
    borderRadius: 'var(--DataGrid-t-radius-base)',
  },
},
cellSkeleton: {
  '&:first-of-type': {
    borderLeft: '1px solid var(--DataGrid-rowBorderColor)',
    borderTopLeftRadius: 'var(--DataGrid-t-radius-base)',
    borderBottomLeftRadius: 'var(--DataGrid-t-radius-base)',
  },
  '&:nth-child(2)': {
    borderLeft: 'none',
  },
},
cell: {
  borderTop: '1px solid var(--DataGrid-rowBorderColor)',
  borderBottom: '1px solid var(--DataGrid-rowBorderColor)',
  '&:nth-child(2)': {
    borderLeft: '1px solid var(--DataGrid-rowBorderColor)',
    borderTopLeftRadius: 'var(--DataGrid-t-radius-base)',
    borderBottomLeftRadius: 'var(--DataGrid-t-radius-base)',
  },
  '&.MuiDataGrid-cellEmpty': {
    width: 1,
    height: 'auto',
    borderRight: '1px solid var(--DataGrid-rowBorderColor)',
    borderTopRightRadius: 'var(--DataGrid-t-radius-base)',
    borderBottomRightRadius: 'var(--DataGrid-t-radius-base)',
  },
},
```
