### ISSUE TITLE
[DataGridPro] Support columns reorder on mobile

### ISSUE THREAD

**Issue by ecl1ps** [mui/mui-x#1235]
Hi,

It seems columns can't be reordered (dragged) on mobile devices (with touch events). Or at least I couldn't find a way how to do it. Resizing works fine.

Specifically tested on Chromium-based browsers for android. It can be also replicated in desktop version of Chrome and Firefox in mobile emulation mode.

Tried on oficial example https://material-ui.com/components/data-grid/columns/#column-reorder.

Thanks for fixing it up!

**Comment by oliviertassinari** [comment]
@ecl1ps From what I recall from our work on this feature in #165, we ignored mobile. I wonder if the UX on mobile wouldn't be better solved by #839.

Could you expand a bit on why you need this support on mobile? It would help!

**Comment by ecl1ps** [comment]
Thank you for response.

Honestly it seemed as na obvious bug as I couldn't found any mention of it not working on mobile in the docs. And also that other similar functionality (at least from the UX point of view) column resize si working on mobile just fine. 

I can image using drag&drop to reorder columns on tablets without problems. On mobiles it would be more cumbersome.

At this moment this not an overly important feature for us. We are planning to create a standalone component (similar to #839) to configure columns and their order (#820 would be great to make it easier).

So maybe at least mention it in docs? Thanks!

**Comment by cherniavskii** [comment]
We will track this in https://github.com/mui/mui-x/issues/1235
