### ISSUE TITLE
[data grid] Can't save default column width given by user in assigned treedata, is any way to do it?

### ISSUE THREAD

**Issue by sludwikowski** [mui/mui-x#12350]
### Current behavior

Currently, with the tree view, the tree date column does not save its width if the user changes it, the same error occurs again after refreshing. 

### Expected behavior

I would like the treedata column to save its width when it is changed by a user similarly to what happens with other columns.

### Context

I want to target the width of the column to save, it is persistent with a large amount of data

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: treedatagroup, treedata, width, mui premium, mui datagrid, datagridremium

**Comment by michelengelen** [comment]
Hi @sludwikowski ... I did play around with our demos a bit and could build an example where the state gets stored in `localStorage` and reapplied on reload: [tree data state example](https://stackblitz.com/edit/react-gbnetw?file=Demo.tsx).

Would this suit your needs?

**Comment by sludwikowski** [comment]
Unfortunately no, I used the solution from this example in my case, but unfortunately it did not help :/ 
Overall, the state of the other columns is fine, the worst is just in the case of tree data.
![image](https://github.com/mui/mui-x/assets/87614396/88232435-b337-4939-8370-534d4853441a)

**Comment by michelengelen** [comment]
Well, it should work. Could you provide the code you applied for the state storage?
