### ISSUE TITLE
[data grid] How can I access a grouped row values in renderCell, like params.row.VALUE for a non-grouped row?

### ISSUE THREAD

**Issue by stivluc** [mui/mui-x#12355]
### The problem in depth

I used to create custom cells with renderCell(params) and accessing other columns values with params.row.COLUMN.

However, it doesn't seem to work for grouped-row, which make the data grid very empty.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  I tried with the latest version of MUI DataGrid Premium (v7.0.0) and earlier versions.
```
</details>

**Search keywords**: rendercell
**Order ID**: 80196

**Comment by michelengelen** [comment]
Hey @stivluc .. if you want to access values in the auto generated grouping row: its not possible.

For the rows that have been grouped under this auto-generated row you can access all values as before.

**Comment by michelengelen** [comment]
There is one addition to this: We do have row aggregation that works well with row grouping. Here is the [related docs](https://mui.com/x/react-data-grid/aggregation/#usage-with-row-grouping)

**Comment by stivluc** [comment]
Is there any existing workaround? I'd like to render a progress bar based on the sums of the grouped rows.

**Comment by MBilalShafi** [comment]
Hi @stivluc Can you expand more on what exactly you are trying to achieve, as for accessing the value for the grouped row, I think you can do that using `groupingColDef.renderCell` as depicted in this [demo](https://mui.com/x/react-data-grid/row-grouping/#grouping-rows-with-custom-cell-renderer), could that possibly satisfy your use-case?

If not, could you provide a live example close to what you are trying to achieve?
