### ISSUE TITLE
[data grid] Grid not getting state applied after retrieval from local storage

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#12366]
### The problem in depth

Hello, 

I have the following code which stores user created views to local state. I'm able to save and delete without issue but the problem is how do I get the state to be applied. I've added  apiRef.current.restoreState(stateFromLocal); after getting the state from the local storage but it never applies. I can see everything stored but it just will not apply to the grid. Please assist. My sandbox is below:

https://codesandbox.io/p/sandbox/savingandapplystate-xtc493

### Your environment

System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 7.24.2 - ~/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.71
  npmPackages:
    @emotion/react: latest => 11.11.3 
    @emotion/styled: latest => 11.11.0 
    @mui/base:  5.0.0-beta.32 
    @mui/core-downloads-tracker:  5.15.5 
    @mui/icons-material: ^5.15.3 => 5.15.5 
    @mui/lab: ^5.0.0-alpha.159 => 5.0.0-alpha.161 
    @mui/material: ^5.15.3 => 5.15.5 
    @mui/private-theming:  5.15.5 
    @mui/styled-engine:  5.15.5 
    @mui/styles: ^5.15.3 => 5.15.5 
    @mui/system:  5.15.5 
    @mui/types:  7.2.13 
    @mui/utils: ^5.15.4 => 5.15.5 
    @mui/x-data-grid:  6.19.1 
    @mui/x-data-grid-generator: ^6.16.2 => 6.19.1 
    @mui/x-data-grid-premium: ^6.19.1 => 6.19.1 
    @mui/x-data-grid-pro:  6.19.1 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react:  17.0.75 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: latest => 6.1.8 

**Search keywords**: state
**Order ID**: 66765

**Comment by michelengelen** [comment]
When receiving the state from `localStorage` is it in JSON format. You have to parse this to apply it with `apiRef.current.restoreState()`. Example:

```tsx
if (apiRef.current && stateFromLocal) {
  apiRef.current.restoreState(JSON.parse(stateFromLocal));
}
```

After that change it will work!

**Comment by lisaWriteJava** [comment]
Thanks this is working. 1 other question, how do I get the list of saved stated to update in the dropdown once I delete 1.

**Comment by michelengelen** [comment]
You have implemented a reducer for that... at least it does look like it.
Think of the reducer as your internal state. Now on unmounting the component (or navigating away) you should store the current reducer state to localStorage and retrieve it once you mount the component or navigate back to it.

But the details of this implementation are up to you and a good place to ask these kinds of questions would be StackOverflow. The community there can help you with that problem.

If the original issue is resolved please feel free to close the issue. Thanks! 🙇🏼

**Comment by lisaWriteJava** [comment]
Thanks, I thought that the support purchased was to assist with questions such as these. Sorry to trouble you.

**Comment by michelengelen** [comment]
> Thanks, I thought that the support purchased was to assist with questions such as these. Sorry to trouble you.

Typically you would be right, but the question you asked is unrelated to our components and more of a general react question. We do provide a demo on how to store and restore state from `localStorage`. With a slight variation on this you should be able to implement the desired behavior. Just use the methods described there and change the "point of contact" as well as the data flow to when you initialize/mount (and later unmount) your reducer.

Basically the place where you pass in `DEMO_INITIAL_STATE` you need to pass in the state you retrieved from `localStorage`.

Now for deletion you just need to update the List you pass the state from the reducer instead of the one from `localStorage`

```tsx
{Object.keys(state).map((label, index) => (
  <ViewListItem
    label={label}
    index={index}
    onDelete={handleDeleteView}
    onSelect={() => handleSetActiveView(label, index)}
  />
))}
```

This should be enough to fix the problem. You should think about separating the code as well. it is hard to navigate like this. Just as a tip! 👍🏼

**Comment by lisaWriteJava** [comment]
Thanks. I'm in the process of trying to filter out some stuff right now. It was much smaller when it started but the revisions things grew. Thanks again for your assistance. I think the confusion is this has so much code from the changes and no deletions.
