### ISSUE TITLE
Same column in different column groups Cont'd

### ISSUE THREAD

**Issue by MiraHariri** [mui/mui-x#12362]
### The problem in depth

This topic is already discussed on this issue: https://github.com/mui/mui-x/issues/12089
But I found some issues in the solution provided previously

The first issue is when you click on "Select All" from the table header, only the group rows will be selected and the children of the first group only. so I updated the code to fix this issue
const arrayDiff = (
   arr1: GridRowSelectionModel,
   arr2: GridRowSelectionModel
 ) => {
   const diff = [...arr1]
     .filter((item) => !arr2.includes(item))
     .concat(arr2.filter((item) => !arr1.includes(item)));

   return {
     diff,
     id: diff[0],
     isNewBigger: arr1.length < arr2.length,
   };
 };

 const handleRowSelectionModelChange = (newRowSelectionModel: any) => {
   const diff: any = arrayDiff(rowSelectionModel, newRowSelectionModel);

   if (diff.diff.length > 1) {
     if (diff.isNewBigger)
       setRowSelectionModel([
         ...newRowSelectionModel,
         ...apiRef.current.getAllRowIds(),
       ]);
     else setRowSelectionModel([]);
   } else {
     if (apiRef.current.getRowNode(diff.id)?.type !== "group") {
       setRowSelectionModel(newRowSelectionModel);
       return;
     }

     const childRowIds = apiRef.current.getRowGroupChildren({
       groupId: diff.id,
     });
     let updatedRowSelectionModel: any = [];
     updatedRowSelectionModel = [
       ...new Set(
         diff.isNewBigger
           ? [...newRowSelectionModel, ...childRowIds]
           : newRowSelectionModel?.filter(
               (id: any) => !childRowIds.includes(id)
             )
       ),
     ];
     setRowSelectionModel(updatedRowSelectionModel);
   }
 };
The second issue is when you select/unselect all the child rows 1 by 1, the parent row should be checked/unchecked automatically

The third issue is when you do any action on the table, like change column sorting for example, the parent row and their children will be unchecked while the child rows that are selected alone without their parent stays selected

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: checkboxSelection rowGrouping selectAll
**Order ID**: 78698

**Comment by MiraHariri** [comment]
Opened this issue by mistake, let's continue on the previous issue please [#12222)](https://github.com/mui/mui-x/issues/12222)

**Comment by MBilalShafi** [comment]
Alright, I'll close this one in that case.
