### ISSUE TITLE
[data grid] I need to double click in the grid on action items in order to fire the handler

### ISSUE THREAD

**Issue by johanndms** [mui/mui-x#12367]
### The problem in depth

Hi,

I've had this problem or behaviour for a while now but need to get it solved as some users are complaining now :-)

In the data-grid on the "actions" I need to click twice before the handler fires? So the "handleCheckin" below does not fire unless I click on the action icon twice.

https://github.com/mui/mui-x/assets/16336986/05c28350-884f-451b-bce5-8273d3192b5c

`{
            field: 'actions',
            type: 'actions',
            headerName: '',
            flex: 0.4,
            getActions: ({ row }) => [
               <GridActionsCellItem
                  onClick={() => handleCheckin(row.id)}
                  icon={<Iconify icon="icon-park-outline:check-in" width={28} />}
                  label="Check In"
               />,
            ],
         },`

I have searched and looked at your github repo and I have tried quite a few of the "suggested" solutions but it seems the issues persists?

Any pointer will be great!!

Thanks in advance for the help.

Kind regards,
Johann

### Your environment

System:
    OS: macOS 14.3.1
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 119.0.6045.123
    Edge: Not Found
    Safari: 17.3.1
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.13 
    @mui/core-downloads-tracker:  5.14.7 
    @mui/icons-material: ^5.14.7 => 5.14.7 
    @mui/lab: ^5.0.0-alpha.142 => 5.0.0-alpha.142 
    @mui/material: ^5.14.7 => 5.14.7 
    @mui/private-theming:  5.14.7 
    @mui/styled-engine:  5.14.7 
    @mui/system:  5.14.7 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.13 
    @mui/x-data-grid:  6.16.1 
    @mui/x-data-grid-pro: ^6.16.1 => 6.16.1 
    @mui/x-date-pickers: ^6.12.0 => 6.12.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.21 => 18.2.21 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 

**Search keywords**: Double click, fire action, double
**Order ID**: 70591

**Comment by johanndms** [comment]
Perhaps more helpful if you have the handler code as well.....

`const handleCheckin = useCallback(
      (eventId: number) => {
         console.log('FIRED........');
         router.push(paths.dashboard.checkin(eventId.toString(), selectedDate));
      },
      [router, selectedDate]
   );`

I have tried this not using useMemo for the column defs and useCallback for the handler - same results.

When I click the first time the console log "FIRED" doesn't appear so 100% it doesn't get to the handler.

Also replaced the code in the action to 

`<GridActionsCellItem onClick={() => console.log("FIRED")} icon={<Iconify icon="icon-park-outline:check-in" width={28} />} label="Check In" />`

but only after 2nd click does it display FIRED

**Comment by michelengelen** [comment]
Hey @johanndms ... without a minimal live reproduction we will have a hard time figuring out what is broken in your implementation.

As you can see from this [example on the docs](https://mui.com/x/react-data-grid/editing/#full-featured-crud) the actions col feature works just fine. I did even test it with your provided version and there is no bug on our end.

**Comment by amit-rai-sentinelehr** [comment]
@johanndms Is this issue solved as I am also getting the same issue ! Onclick is working fine but sometimes need to be double click to fire the event.
If you have got the solution please share 
Thank you.

**Comment by johanndms** [comment]
Hello,Yes I figured it out finally. I was using a sub component (styled button) inside the data grid columns and for some strange reason this was causing it. I embedded a similar style button directly not using it as a component and it worked / fixed the issue. So I recommend just trail and error by removing any styling or other code until you find the culprit Hope this help. On 9. 4. 2025, at 15:41, Amit Rai ***@***.***> wrote:﻿
  @johanndms Is this issue solved as I am also getting the same issue ! Onclick is working fine but sometimes need to be double click to fire the event.
If you have got the solution please share
Thank you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



amit-rai-sentinelehr left a comment (mui/mui-x#12367)
@johanndms Is this issue solved as I am also getting the same issue ! Onclick is working fine but sometimes need to be double click to fire the event.
If you have got the solution please share
Thank you.

**Comment by amit-rai-sentinelehr** [comment]
@johanndms Thank you so much. I have added a direct svg it is working now.

**Comment by johanndms** [comment]
Cool!!!On 10. 4. 2025, at 8:22, Amit Rai ***@***.***> wrote:﻿
  @johanndms Thank you so much. I have added a direct svg it is working now.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



amit-rai-sentinelehr left a comment (mui/mui-x#12367)
@johanndms Thank you so much. I have added a direct svg it is working now.

**Comment by mleister97** [comment]
News?
