### ISSUE TITLE
[charts] Tooltip displays the wrong information when the x-axis is reversed

### ISSUE THREAD

**Issue by dougludlow** [mui/mui-x#12371]
### Steps to reproduce

https://stackblitz.com/edit/react-5re4qw?file=Demo.js

### Current behavior

When you set the xAxis to `reverse: true`, the tooltip displays the item content as if it wasn't reversed

### Expected behavior

When you set the xAxis to `reverse: true`, the tooltip will also revserse.

### Context

<img width="741" alt="Screenshot 2024-03-07 at 2 05 46 PM" src="https://github.com/mui/mui-x/assets/733821/fb433ece-6415-4944-96ed-137497c5a1d8">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.3.1
  Binaries:
    Node: 20.4.0 - /opt/homebrew/opt/nvm/versions/node/v20.4.0/bin/node
    npm: 9.7.2 - /opt/homebrew/opt/nvm/versions/node/v20.4.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.112
    Edge: Not Found
    Safari: 17.3.1
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-alpha.96 
    @mui/core-downloads-tracker:  5.10.4 
    @mui/icons-material: 5.14.19 => 5.14.19 
    @mui/lab: ^5.0.0-alpha.98 => 5.0.0-alpha.98 
    @mui/material: ^5.10.3 => 5.10.4 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine:  5.10.4 
    @mui/styles: ^5.10.3 => 5.10.3 
    @mui/system: 5.10.4 => 5.10.4 
    @mui/types:  7.2.0 
    @mui/utils: ^5.10.3 => 5.10.3 
    @mui/x-charts: ^6.19.5 => 6.19.5 
    @mui/x-date-pickers: ^5.0.0 => 5.0.0 
    @types/react: 18.2.13 => 18.2.13 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.2.2 => 5.2.2 
```
</details>

**Search keywords**: chart tooltip reversed

**Comment by michelengelen** [comment]
Hey @dougludlow ... thanks for raising this issue.
I did add this to our board for the team to prioritize.
