### ISSUE TITLE
[data grid] Implementing Visual Feedback for Pasted Data

### ISSUE THREAD

**Issue by rsouilem** [mui/mui-x#12374]
### The problem in depth

I'm currently working on a project where I aim to provide users with visual feedback indicating which cells have been updated after pasting data into the MUI Data Grid. Is there a way to to detect various change events that occur within a given cell and subsequently trigger appropriate actions or visual feedback. (In this case I'm looking to make cells glow or visually highlight to denote changes)

Issue:
Despite extensive exploration, I have yet to find a suitable method to modify the CSS of cells upon pasting data or more generally detect and respond to change events within individual cells of the MUI Data Grid. I would greatly appreciate any guidance or suggestions on how to achieve this functionality effectively within the Data Grid.

Thank you for your assistance!

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>
```
System:
    OS: macOS 14.1.1
  Binaries:
    Node: 20.4.0 - /opt/homebrew/bin/node
    npm: 9.7.2 - /opt/homebrew/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @emotion/react: ^11.10.0 => 11.11.1 
    @emotion/styled: ^11.10.0 => 11.11.0 
    @mui/base:  5.0.0-beta.24 
    @mui/core-downloads-tracker:  5.14.18 
    @mui/icons-material: ^5.10.2 => 5.14.18 
    @mui/lab: ^5.0.0-alpha.144 => 5.0.0-alpha.153 
    @mui/material: ^5.10.0 => 5.14.18 
    @mui/private-theming:  5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/system:  5.14.18 
    @mui/types:  7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-data-grid:  6.17.0 
    @mui/x-data-grid-generator: ^6.16.2 => 6.18.1 
    @mui/x-data-grid-premium: 6.17.0 => 6.17.0 
    @mui/x-data-grid-pro: 6.0.1 => 6.0.1 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-date-pickers-pro: 5.0.20 => 5.0.20 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.0.17 => 18.2.37 
    react: ^18.1.0 => 18.2.0 
    react-dom: ^18.1.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2
```
</details>

**Search keywords**: copy paste
**Order ID**: 73406

**Comment by michelengelen** [comment]
Thanks for waiting @rsouilem ... I did play around a bit and found a possible solution for you problem. It is a combination of cell Styling and the [`processRowUpdate`](https://next.mui.com/x/react-data-grid/editing/#the-processrowupdate-callback) method.

Here is a live example of it: [Paste visualisation](https://codesandbox.io/p/sandbox/jolly-brattain-w33pyl?file=%2Fsrc%2FDemo.tsx)

This is the part that is important:
```tsx
const highlightCell = useCallback(
  (rowId: number, field: string) => {
    const cell = apiRef.current.getCellElement(rowId, field);
    cell?.classList.add('highlight-cell');
    setTimeout(() => {
      cell?.classList.remove('highlight-cell');
    }, 1500);
  },
  [apiRef],
);

const handleRowUpdate: DataGridProps['processRowUpdate'] = (newRow, oldRow) => {
  const changedFields = [];

  for (const key in oldRow) {
    if (newRow.hasOwnProperty(key) && oldRow.hasOwnProperty(key)) {
      if (newRow[key] !== oldRow[key]) {
        changedFields.push(key);
      }
    }
  }

  if (changedFields.length > 0) {
    changedFields.forEach((field) => highlightCell(newRow.id, field));
  }

  return newRow;
};
```

Does that help you?

**Comment by rsouilem** [comment]
This helped tremendously. I appreciate it a lot.
<img width="404" alt="Screenshot 2024-03-08 at 6 19 49 PM" src="https://github.com/mui/mui-x/assets/139749060/b661ba94-23cc-482d-acb9-acd9a53085d4">
