### ISSUE TITLE
[data grid] how to filter based on raw row data

### ISSUE THREAD

**Issue by RhysOnlyBetter** [mui/mui-x#12385]
### The problem in depth

I have a number of fields which are returned from the server using an ID `{thingId: string}`. I apply a valueGetter function to these to get the cell value I want to display `(value) => thingValuesMap.get(value).name`. This is important for export and works well with sorting and the quickFilter etc.

I'm now adding the ability to pass filters to my table component via queryParams, and need to filter by the raw thingId value. The only way I can find to do this is to make 'thingId' a hidden cell and make a new thingName cell which uses the valueGetter above. I'm wondering if this is the best approach? Ideally I would like to have a singe cell which can be filtered by both the raw cell value and the result of valueGetter.

If the best approach is to create 2 cells is there a simple way to make a 'phantom' cell which will never be shown in the UI? I'm currently using something like the below, but it's still shown in the 'hide column' modal.

` width: 0, sortable: false, disableColumnMenu: true, disableExport: true,`

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 13.4.1
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.112
    Edge: Not Found
    Safari: 16.5.2
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.38 
    @mui/core-downloads-tracker:  5.15.12 
    @mui/icons-material:  5.15.12 
    @mui/material:  5.15.12 
    @mui/private-theming:  5.15.12 
    @mui/styled-engine:  5.15.11 
    @mui/styled-engine-sc:  5.14.12 
    @mui/system:  5.15.12 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.12 
    @mui/x-codemod: ^6.9.0 => 6.9.0 
    @mui/x-data-grid:  6.19.6 
    @mui/x-data-grid-pro: ^6.19.3 => 6.19.6 
    @mui/x-date-pickers: ^6.12.0 => 6.19.6 
    @mui/x-date-pickers-pro: ^6.19.3 => 6.19.6 
    @mui/x-license-pro:  6.10.2 
    @types/react: 18.2.64 => 18.2.64 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    styled-components:  5.3.11 
    typescript: 5.3.3 => 5.3.3
```
</details>

**Search keywords**: valueGetter filtering rawValue
**Order ID**: 85984

**Comment by michelengelen** [comment]
Hey @RhysOnlyBetter,
I will try to answer your questions 1 by 1.

1. Filter by id:
Since you have a `valueGetter` function defined this is no longer possible, but you could change that to a `valueFormatter` function which is being used for displaying the cell value (when exporting as well)

2. Shadow col:
Yes, that would also be possible, by adding a filter function to `slotProps.columnsPanel.getTogglableColumns`. Here is the related docs section: [customize togglable columns](https://mui.com/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel)

> [!IMPORTANT]
> The naming for that slotProp got changed in `v7`
> `v6` => `slotProps.columnsPanel.getTogglableColumns`
> `v7` => `slotProps.columnsManagement.getTogglableColumns`

That way you can hide the col from the panel.

Does that help you?

**Comment by RhysOnlyBetter** [comment]
Thanks for the response @michelengelen. 

1. Unfortunately `valueFormatter` won't work for me since I need to sort and use the quick filter based on the formatted value. 
2. Thanks for the suggestion on `getTogglableColumns`, I'll add that to my original solution. 

Do you think it would be a reasonable feature request to add an option to `GridColDef` to shadow columns so this was a bit easier?

Thanks again for your help!

**Comment by michelengelen** [comment]
IMO the approach with the method provides a lot more freedom and customizability.

WDYT @mui/xgrid ? would adding a property to the coldef make sense?

**Comment by cherniavskii** [comment]
@RhysOnlyBetter 
> I apply a valueGetter function to these to get the cell value I want to display (value) => thingValuesMap.get(value).name

This makes sense to me.

> I'm now adding the ability to pass filters to my table component via queryParams, and need to filter by the raw thingId value.

How about adding a separate column and using [`columnVisibilityModel`](https://mui.com/x/react-data-grid/column-visibility/#initialize-the-visible-columns) to hide it?
Here is a working demo: https://stackblitz.com/edit/react-kms7xe?file=Demo.tsx,package.json
What do you think?

**Comment by RhysOnlyBetter** [comment]
@cherniavskii Thanks for the response, I thought that by adding `hideable: false` it would force the column to always be shown, which was the opposite of what I'm looking for. I think with a combination of your example and adding slotProps with 
```columnsPanel: {
    getTogglableColumns: (columns: GridColDef[]) =>
      columns.filter((col) => col.hideable).map((col) => col.field),
  },```
I have a solution I'm happy with.

Thanks again 😄

**Comment by RhysOnlyBetter** [comment]
For anyone who comes across this in the future, the above solution of creating a 'shadow' column isn't ideal because you will lose the 'filtered' icon on the cell header. A better & much simpler solution is to use a 'singleSelect' cell and give it options as `{value: thing.id, label: thing.label}[]`. This will automatically show the cell value as the label (& works with export & quick filter), but allow you to filter by the id. The only downside of this approach is that sorting will work on the id not the label, so you will have to create a custom `sortComparator`.
