### ISSUE TITLE
[pickers][DateTimePicker] not showing 2 in the hour category, but shows 3 twice and the first isn't selectable 

### ISSUE THREAD

**Issue by kyle-rachau** [mui/mui-x#12403]
### Steps to reproduce

Link to live example: (required)

https://mui.com/x/react-date-pickers/date-time-picker/

Steps:
1. any date time picker, even the demos on the mui site are broke 
2.
3.

### Current behavior

The hour category shows 12-1-3-3-4-5

### Expected behavior

The hour category shows 12-1-2-3-4-5

### Context

Select time from date time picker
![image](https://github.com/mui/mui-x/assets/82466384/d57baf49-886e-4226-a8a0-c36fbcb596ca)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DateTimePicker hour
**Order ID**: 39752

**Comment by kyle-rachau** [comment]
Yea that was my guess too.

**Comment by kyle-rachau** [comment]
It seems to work this morning. It must have just been a DST change.

**Comment by michelengelen** [comment]
Still ... I would like to investigate this, as this is clearly a bug, even if it only happens on a single day in the year. 🤔

**Comment by LukasTy** [comment]
This looks like a similar topic as https://github.com/mui/mui-x/issues/10783
I'll look into it, whenever I get back to finalizing the PR for DigitalClock. 👌

**Comment by flaviendelangle** [comment]
@LukasTy do you want to mark that one as duplicate?

**Comment by LukasTy** [comment]
> @LukasTy do you want to mark that one as duplicate?

Not sure that it can be treated as a duplicate. 🤔 
The mentioned one concerns the `DigitalClock` component, whereas this one is about `MultiSectionDigitalClock` and `TimeClock`. 🤔

**Comment by flaviendelangle** [comment]
If you think the two fixes will be handled independently then we can add this one to the board as well :+1:
