### ISSUE TITLE
[data grid] useResizeContainer Console Error when wrapping <div> is modified

### ISSUE THREAD

**Issue by dmarciano** [mui/mui-x#12412]
### Steps to reproduce

Link to live example: Click the **Edit in StackBlitz** icon under the **Predefined dimensions** section of [Data Grid - Layout](https://mui.com/x/react-data-grid/layout/)

Steps:
1. Modify the immediate parent `<div>` of the `<DataGrid>` component (e.g., add an extra whitespace between `{{` and `height`

### Current behavior

A `useResizeContainer` error is reported in the browser console:
![image](https://github.com/mui/mui-x/assets/20006727/eeb4aa25-0a89-460f-bc95-920c7874f5fd)

### Expected behavior

No console error has the `height` and `width` are defined

### Context

Remove/prevent false positive errors

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Version 120.0.6099.225 (Official Build) (64-bit)
    Edge: Version 120.0.2210.144 (Official build) (64-bit)
  npmPackages:
    @emotion/react: 11.11.4
    @emotion/styled: 11.11.0
    @mui/icons-material 5.15.12
    @mui/material 5.15.12
    @mui/x-data-grid 6.19.6
    @mui/x-datagrid-generator 6.19.6
    @types/react 18.2.64
    @types/react-dom 18.2.21
    react 18.2.0
    react-dom 18.2.0
    typescript 5.4.2
```
</details>

**Search keywords**: datagrid, useResizeContainer

**Comment by michelengelen** [comment]
This is not reproducible in my local instance, but on Stackblitz as described by @dmarciano.

I will add this to the board, but as this is possibly only happening on Stackblitz this might have a relatively low priority. Thanks for raising this anyways @dmarciano 🙇🏼

**Comment by shikha-mobibiz** [comment]
Facing same issue when using DataGrid

**Comment by romgrk** [comment]
If this only happens in stackblitz, this would be a stackblitz bug. I notice it only happens on HMR, but not when the page first loads. This makes me think that there's an issue with how the HMR update interacts with the DOM.

If someone can reproduce the issue locally, we could look into it.

**Comment by shikha-mobibiz** [comment]
> If this only happens in stackblitz, this would be a stackblitz bug. I notice it only happens on HMR, but not when the page first loads. This makes me think that there's an issue with how the HMR update interacts with the DOM.
> 
> If someone can reproduce the issue locally, we could look into it.

This is not link to stackblitz, I am also facing same issue on my local app.

**Comment by romgrk** [comment]
Can you provide a reproduction case? Please share it in a codesandbox.

**Comment by romgrk** [comment]
Unrelated issue, continue the discussion in the other issue you created.
