### ISSUE TITLE
[data grid] How to override HIDE ALL panel button ?

### ISSUE THREAD

**Issue by Aberkati** [mui/mui-x#12423]
### The problem in depth

I want to override the hide all button, the goal is to change it to Restore InitialiState and restore the initialState when pressed, not to disable all columns, there is a solution for this issue please ? 

[This is my demo](https://codesandbox.io/p/sandbox/sweet-jennings-lzgfkw?file=%2Fsrc%2FDemo.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clto4nsoq00073j6g4yja3qm5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clto4nsoq00033j6g3it4e6j6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clto4nsoq00043j6ggm4i4ktk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clto4nsoq00063j6grdbxxze5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.08227766008042%252C56.91772233991958%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clto4nsoq00033j6g3it4e6j6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clto4nsoq00023j6g0xrglgkj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clto4nsoq00033j6g3it4e6j6%2522%252C%2522activeTabId%2522%253A%2522clto4nsoq00023j6g0xrglgkj%2522%257D%252C%2522clto4nsoq00063j6grdbxxze5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clto4nsoq00053j6glvrykrgc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clto4nsoq00063j6grdbxxze5%2522%252C%2522activeTabId%2522%253A%2522clto4nsoq00053j6glvrykrgc%2522%257D%252C%2522clto4nsoq00043j6ggm4i4ktk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clto4nsoq00043j6ggm4i4ktk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 
Thank you

### Your environment

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD    
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (122.0.2365.80)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1 
    @emotion/styled: ^11.10.6 => 11.11.0 
    @mui/base:  5.0.0-beta.7 
    @mui/core-downloads-tracker:  5.14.0 
    @mui/icons-material: ^5.11.16 => 5.14.0         
    @mui/material: ^5.12.1 => 5.14.0 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2
    @mui/system:  5.14.0
    @mui/types:  7.2.4
    @mui/utils:  5.13.7
    @mui/x-data-grid:  6.10.0
    @mui/x-data-grid-premium: ^6.10.0 => 6.10.0
    @mui/x-data-grid-pro:  6.10.0
    @mui/x-license-pro: ^6.10.0 => 6.10.0
    @types/react:  18.2.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0

**Search keywords**: DataGridPremium
**Order ID**: 66242

**Comment by michelengelen** [comment]
Hey @Aberkati,
this is currently not possible without implementing a fully custom column visibility panel.

For `v7`, which will release next week, we redid the whole columnsManagement panel. It now includes a `Reset` button. You might want to check that out [here](https://next.mui.com/x/react-data-grid/column-visibility/)

Would that help in your use case?

**Comment by Aberkati** [comment]
Hi, When the v7 version will release ? thank you

**Comment by MBilalShafi** [comment]
Hey @Aberkati, the first stable release is expected by end of the current week.
