### ISSUE TITLE
[data grid] Parameters needed for custom column resize.

### ISSUE THREAD

**Issue by amrutamangaonkar** [mui/mui-x#12422]
### The problem in depth

I am a MUI Pro license user. I am working on customization of DataGrid Pro column width resize. I need to resize my grid column on keyboard events and mouse events. Since DataGrid does not have any out of the box column resize using keyboard, I had to write my custom keyboard event method for columns, this required maintaining flex of the columns and working on it. We are using flex in-order to fit the grid in the given space and distribute the columns equally. When I do a mouse resize I check the change in width through onColumnWidthChange event. The problem that I am facing is when column resizes I don't get the updated flex back or the old width which makes it difficult for me to calculate the updated flex value.

For example, this is what get back from resizeParams

```
{ colDef: { 
       aggregable: true,
       align: "left",
       computedWidth: 879,
       description: "Identifies the menu or its intended user.",
       editable: false,
       field: "menuName",
       filterOperators: (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}],
       flex: 0,
       .
       .
     }
}
```
Could we get the flex which comes back as 0 or a originalWidth (width before resizing) to calculate the new flex.

**Search keywords**: Parameters for custom column resize
**Order ID**: 8813014139

**Comment by amrutamangaonkar** [comment]
> Hi @amrutamangaonkar, Would this be something to fix your issue:
> 
> ```tsx
> import * as React from 'react';
> import { DataGridPro, GridColDef, GridToolbar, useGridApiRef } from '@mui/x-data-grid-pro';
> import { useDemoData } from '@mui/x-data-grid-generator';
> 
> const VISIBLE_FIELDS = ['name', 'rating', 'country', 'dateCreated', 'isAdmin'];
> 
> export default function BasicExampleDataGrid() {
>   const { data } = useDemoData({
>     dataSet: 'Employee',
>     visibleFields: VISIBLE_FIELDS,
>     rowLength: 100,
>   });
> 
>   const columnWidths = React.useRef<Record<GridColDef['field'], number>>(
>     data.columns.reduce((acc, column) => ({ ...acc, [column.field]: column.width }), {} as any),
>   );
>   const apiRef = useGridApiRef();
> 
>   return (
>     <div style={{ width: '100%' }}>
>       <div style={{ height: 400, width: '100%' }}>
>         <DataGridPro
>           {...data}
>           apiRef={apiRef}
>           slots={{ toolbar: GridToolbar }}
>           onColumnWidthChange={(params) => {
>             console.group(`widths for ${params.colDef.field}`);
>             console.log(`old: `, columnWidths.current[params.colDef.field]);
>             console.log('new: ', params.width);
>             console.groupEnd();
>             columnWidths.current[params.colDef.field] = params.width;
>           }}
>         />
>       </div>
>     </div>
>   );
> }
> ```
> 
> Here I do create a ref that holds an object `Record<GridColDef['field'], number>` with the current width values. Whenever o column got resized I do update the property where that column width was changed.
> 
> I understand that passing in the previous value would be more beneficial in this case, but this would be a nice workaround IMO.
> 
> Let me know what you think!

@michelengelen, Thanks for posting a workaround. In my case I am not setting individual width values, I am setting flex for equal distribution of column widths. With the following I don't get the current width back which I can refer to later when column width changes:

`const columnWidths = React.useRef<Record<GridColDef['field'], number>>(
    data.columns.reduce((acc, column) => ({ ...acc, [column.field]: column.width }), {} as any),
  );` 

Unless I am missing something important here, please let me know. Thank you.

**Comment by michelengelen** [comment]
> @michelengelen, Thanks for posting a workaround. In my case I am not setting individual width values, I am setting flex for equal distribution of column widths. With the following I don't get the current width back which I can refer to later when column width changes:
> 
> `const columnWidths = React.useRef<Record<GridColDef['field'], number>>( data.columns.reduce((acc, column) => ({ ...acc, [column.field]: column.width }), {} as any), );` Unless I am missing something important here, please let me know.
> 
> The limitation I am facing here is our grid is dynamic we don't know what container my grid will load in. So I cannot provide a specific width to either the grid or the columns. During keyboard resize if I increase the width, overall width of the grid increases making it overflow outside. Hence, I am restricted to using flex and adjusting flex value when user needs to resize the column. If you have any suggestions for this as well, let me know. Thank you.

Ok, I got you... this is a bit more tricky and I did take a while to find a solution, but here it is:

```tsx
import * as React from 'react';
import { DataGridPro, GridColDef, GridToolbar, useGridApiRef } from '@mui/x-data-grid-pro';
import { useDemoData } from '@mui/x-data-grid-generator';

const VISIBLE_FIELDS = ['name', 'rating', 'country', 'dateCreated', 'isAdmin'];

export default function BasicExampleDataGrid() {
  const { data } = useDemoData({
    dataSet: 'Employee',
    visibleFields: VISIBLE_FIELDS,
    rowLength: 100,
  });

  const apiRef = useGridApiRef();
  const cols = data.columns.map((column) => ({ ...column, width: undefined, flex: 1 }));
  const columnWidths = React.useRef<Record<GridColDef['field'], number>>({});

  React.useEffect(() => {
    columnWidths.current = cols.reduce(
      (acc, column) => ({
        ...acc,
        [column.field]: apiRef.current.getColumn(column.field).computedWidth,
      }),
      {} as any,
    );
    console.log('columnWidths', columnWidths.current);
  }, [apiRef, cols]);

  return (
    <div style={{ width: '100%' }}>
      <div style={{ height: 400, width: '100%' }}>
        <DataGridPro
          {...data}
          columns={cols}
          apiRef={apiRef}
          slots={{ toolbar: GridToolbar }}
          onColumnWidthChange={(params) => {
            console.group(`widths for ${params.colDef.field}`);
            console.log(`old: `, columnWidths.current[params.colDef.field]);
            console.log('new: ', params.width);
            console.groupEnd();
            // here you can then grab the 'old' width do calculations, etc. and
            // store the new values into the ref
            columnWidths.current[params.colDef.field] = params.width;
          }}
        />
      </div>
    </div>
  );
}
```

As you can see I am setting `flex: 1` on each column and removing the `width`, so this should be accurate. The problem is that with `flex` and no `width` we have to use the `apiRef` to get each column, where a method is available to get the `computedWidth`.

Does that work for you?

**Comment by amrutamangaonkar** [comment]
@michelengelen Thanks for sending this solution. This helps in getting the previous width.
