### ISSUE TITLE
[DataGrid] Redundant filler appears after changing columns total width

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#12431]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-7hjjpu?file=Demo.tsx

https://github.com/mui/mui-x/assets/13808724/19b85f6a-46e1-4195-a4c8-1f936a248d77

Same could happen on the grid resize (try resizing preview panel in the Stackblitz demo above)

### Current behavior

The filler appears even when there's no space left to fill.

### Expected behavior

The filler should not appear if there's a vertical scroll (there's no space left to fill)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: column resizing filler after last row

**Comment by mdimad7** [comment]
I'm still getting this bug where an empty filler is displayed even when there is no horizontal overflow of content in data grid
