### ISSUE TITLE
[data grid] MUI-X DataGrid rows not updating

### ISSUE THREAD

**Issue by RoseannePeeters** [mui/mui-x#12437]
### Search keywords

MUI-X DataGrid rows not updating

### Latest version

- [X] I have tested the latest version

I wanted to make my own custom component that will render with the slots prop of MUI-X DataGrid.
But I have a problem, when filtering the rowdata, rowData state it is not rerendering or updating the DataGrid.

The component holding the grid and state is App.js
The component holding the custom row is GroupedGridRow

### Steps to reproduce

Link to live example: [Codesandbox](https://codesandbox.io/p/sandbox/jolly-silence-ly2rsq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltpo2kh000063j6ha55lykzd%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltpo2kh000023j6h3hi1llev%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltpo2kh000033j6hj14hqu2f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltpo2kh000053j6hc36dubtp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltpo2kh000023j6h3hi1llev%2522%253A%257B%2522id%2522%253A%2522cltpo2kh000023j6h3hi1llev%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltpo2kh000053j6hc36dubtp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltpo2kh000043j6hk8dtad5d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltpo2kh000053j6hc36dubtp%2522%252C%2522activeTabId%2522%253A%2522cltpo2kh000043j6hk8dtad5d%2522%257D%252C%2522cltpo2kh000033j6hj14hqu2f%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltpo2kh000033j6hj14hqu2f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Click Filter Btn
2. Take for example vatnumber contains BE
3. As you can see it prints the filtered rows with the useEffect, but no rows appear, meaning the DataGrid is not updating

### Current behavior

No rows are showing

### Expected behavior

It should show 2 rows that were correctly filtered and put into state.

### Context

Custom filtering for my custom row component

### What have I tried

I have tried forceUpdating with the apiRef, console.logging if the state changes (it does), checking if my filter function works correctly (it does)

**Comment by RoseannePeeters** [comment]
> The problem you are facing here is that the internal filtering engine will still try to filter based on the operator used.
> 
> and since your row data is constructed to hold `{ id, oldData, newData }` it will never find the field it is looking for.
> 
> For this to work you would need to wrap the built-in operators and make them use your data structure. here is an explanation on how to do that: [wrap built-in operators](https://next.mui.com/x/react-data-grid/filtering/customization/#wrap-built-in-operators)
> 
> Basically make them do this: from
> 
> ```tsx
> value = row[field]
> ```
> 
> to
> 
> ```tsx
> oldValue = row.oldData[field]
> newValue = row.newData[field]
> // apply custom filtering here
> ```
> 
> I did update your example here, but only on the VAT column [here](https://codesandbox.io/p/sandbox/jolly-silence-ly2rsq)
> 
> For reference: this is how I override the `filterOperators` property:
> 
> ```js
> filterOperators: getGridStringOperators().map((operator) => {
>   const getApplyFilterFn = (filterItem, column) => {
>     const innerFilterFn = operator.getApplyFilterFn(filterItem, column);
>     if (!innerFilterFn) {
>       return innerFilterFn;
>     }
> 
>     return (params) => {
>       if (operator.value === "contains") {
>         const oldValue = params.row.oldData[column.field];
>         const newValue = params.row.newData[column.field];
> 
>         return (
>           innerFilterFn({ ...params, value: oldValue }) ||
>           innerFilterFn({ ...params, value: newValue })
>         );
>       }
> 
>       return innerFilterFn(params);
>     };
>   };
> 
>   return {
>     ...operator,
>     getApplyFilterFn,
>   };
> }),
> ```
> 
> Important
> 
> The function signature will change in `v7` from `(params: GridCellParams) => boolean` to `(value, row, column, apiRef) => boolean` (skipping the generic types here for readability)
> 
> Could you try implementing that and if you still encounter problems we can have another look!
> 
> **EDIT:** If you are using this approach you also do not need to hold the rows in state, but can rely on the data grid state instead.

Hi,

Thankyou so much for your quick response.
Will defenitely try this out on a project of mine.

However my requirements have changed and I switched to server side filtering and sorting.
With the same components in the codesandbox (groupedgridrow).
There is also a problem with this and rerendering like above:


Whenever I fetch new data from the server.
It seems like it rerenders sometimes but then there are always following problems:
It insert doubles even though the rows changed correctly and there are no doubles in that prop.
When going back to a state/rows that already happened it doesn't rerender


I would love to provide a codesandbox for this but I can't since its a custom backend which isn't online yet.

Could above described problem also be fixed with: [wrap built-in operators](https://next.mui.com/x/react-data-grid/filtering/customization/#wrap-built-in-operators)


Thanks In Advance,
Kind Regards,

**Comment by michelengelen** [comment]
> I would love to provide a codesandbox for this but I can't since its a custom backend which isn't online yet.

Could you try replicating this behavior with a fake server? You can use the example from the [Lazy Loading section](https://mui.com/x/react-data-grid/row-updates/#lazy-loading) as a starting point.

**Comment by RoseannePeeters** [comment]
> > I would love to provide a codesandbox for this but I can't since its a custom backend which isn't online yet.
> 
> Could you try replicating this behavior with a fake server? You can use the example from the [Lazy Loading section](https://mui.com/x/react-data-grid/row-updates/#lazy-loading) as a starting point.

Okay I will try, is it possible to do a fake backend server and frontend in 1 codesandbox?

**Comment by RoseannePeeters** [comment]
> Hey @RoseannePeeters ... you can use this example as a starting point: [Server side fiiltering](https://mui.com/x/react-data-grid/filtering/server-side/).

Thanks for the response but that was not what I meant.
To provide a sandbox to this issue, I made a custom backend in codesandbox that I want to use in the frontend codesandbox.

However I don't know if 2 codesandboxes can communicate with each other, what would be the endpoint of my backend?

Thanks for your response

**Comment by RoseannePeeters** [comment]
> well ... this is a bit tricky, but you can do that. When editing the sandbox you see that the preview window does have a URL in ti, right? That's basically what you can use in another codesandbox. This will look something like this: `https://<SANDBOX_ID>.csb.app/` Depending on the path you have set for your API in that sandbox you can then use it that way: `https://<SANDBOX_ID>.csb.app/api/update`
> 
> I did test this with a simple express server: [Server test](https://codesandbox.io/p/devbox/nifty-sid-dcq96s)
> 
> You can view the currently stored data with this link: [Current Data](https://dcq96s-8080.csb.app/data)
> 
> You can update it using this curl command:
> 
> ```shell
> curl -H "Content-Type: application/json" -X POST -d '{"username":"michel","data":"react-community-engineer"}' https://dcq96s-8080.csb.app/update
> ```
> 
> Not sure if there is a publicly supported way to connect 2 sandboxes though. You could arguably also just run backend and frontend in one box! 🤷🏼

Thankyou very much, will try this out and get back to you with my codesandbox :)

**Comment by ArtVolchara** [comment]
Hello. Before v7 version i passed extra data to each row (like error - my table is part of the form and should be validated together without binding to the fact if cell went to edit mode or not). In renderCell I took an error and displayed error in tooltip. In v7 this data inside the row is not updated (renderCell gets 'old row' and only value is updated). Any workarounds? How to implement such logic, when data entered the table may not be valid yet (empty cells and etc.) and user goes saving without entered edit mode. The only idea i have is put this errors in columns useMemo which is said would lead to perfomance issues due to columns recreation.

**Comment by ArtVolchara** [comment]
> The problem you are facing here is that the internal filtering engine will still try to filter based on the operator used.
> 
> and since your row data is constructed to hold `{ id, oldData, newData }` it will never find the field it is looking for.
> 
> For this to work you would need to wrap the built-in operators and make them use your data structure. here is an explanation on how to do that: [wrap built-in operators](https://next.mui.com/x/react-data-grid/filtering/customization/#wrap-built-in-operators)
> 
> Basically make them do this: from
> 
> value = row[field]
> to
> 
> oldValue = row.oldData[field]
> newValue = row.newData[field]
> // apply custom filtering here
> I did update your example here, but only on the VAT column [here](https://codesandbox.io/p/sandbox/jolly-silence-ly2rsq)
> 
> For reference: this is how I override the `filterOperators` property:
> 
> filterOperators: getGridStringOperators().map((operator) => {
>   const getApplyFilterFn = (filterItem, column) => {
>     const innerFilterFn = operator.getApplyFilterFn(filterItem, column);
>     if (!innerFilterFn) {
>       return innerFilterFn;
>     }
> 
>     return (params) => {
>       if (operator.value === "contains") {
>         const oldValue = params.row.oldData[column.field];
>         const newValue = params.row.newData[column.field];
> 
>         return (
>           innerFilterFn({ ...params, value: oldValue }) ||
>           innerFilterFn({ ...params, value: newValue })
>         );
>       }
> 
>       return innerFilterFn(params);
>     };
>   };
> 
>   return {
>     ...operator,
>     getApplyFilterFn,
>   };
> }),
> Important
> 
> The function signature will change in `v7` from `(params: GridCellParams) => boolean` to `(value, row, column, apiRef) => boolean` (skipping the generic types here for readability)
> 
> Could you try implementing that and if you still encounter problems we can have another look!
> 
> **EDIT:** If you are using this approach you also do not need to hold the rows in state, but can rely on the data grid state instead.


Hello. Before v7 version i passed extra data to each row (like error - my table is part of the form and should be validated together without binding to the fact if cell went to edit mode or not). In renderCell I took an error and displayed error in tooltip. In v7 this data inside the row is not updated (renderCell gets 'old row' and only value is updated). Any workarounds? How to implement such logic, when data entered the table may not be valid yet (empty cells and etc.) and user goes saving without entering edit mode. The only idea i have is put this errors in columns useMemo which is said would lead to perfomance issues due to columns recreation.
