### ISSUE TITLE
[data grid] an issue regarding singleSelect column

### ISSUE THREAD

**Issue by Youssef-8000** [mui/mui-x#12447]
Currently, i have a project where i need the to use singleSelect, and depending on what options i choose, a popup opens, where the user is promoted to enter some info that gets saved inside of a form. Now singleSelect has a behaviour i want to remove, but it seems like i can't find how to disable it/remove it. When I select an option there is a weird period where it shows the user what they have selected without saving it in the datagrid. and the user has to click anywhere on the screen for it to register the change in the datagrid. now that behaviour negatively impacts when my popup should appear. since when i choose an option the user has to click else where in the screen for the singleSelect to save the option in the datagrid. now i have been trying and searching for a solution to remove that behaviour but i can't find anything. so i need help if anyone knows how to do it.

here is an example from material ui themselves: 
https://codesandbox.io/p/sandbox/blue-sunset-6xxkr6?file=%2Fsrc%2FDemo.tsx%3A129%2C14

the behaviour i want to be remove 
![image](https://github.com/mui/material-ui/assets/118922319/24c12a45-d2c6-4008-9a42-cd7ace79c592)

I know this sounds like i should use type "actions", but i get my singleSelect options from my backend. and not all options are clickable. only certain ones with certain codes. and i want to have text next to the button not just an action button. what i have been doing is everytime the user choose an option in the singleSelect, it matches it with the codes that corresponds to the popup codes. if they match a popup appears otherwise the user selects their option without a popup.

Any help would be appreciated!

**Search keywords**: 

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @Youssef-8000 this is possible with a little "hack".

I did update your example [here](https://codesandbox.io/p/sandbox/blue-sunset-6xxkr6?file=%2Fsrc%2FDemo.tsx%3A129%2C14).

It works like this:
```tsx
const stopCellEditMode = React.useCallback(() => {
  if (cellEditRef.current) {
    const { id, field } = cellEditRef.current;
    apiRef.current.stopCellEditMode({ id, field });
    cellEditRef.current = null;
  }
}, [apiRef, cellEditRef]);

const handleCellEditStart = React.useCallback(
  (params: GridCellParams) => {
    if (cellEditRef.current) {
      stopCellEditMode();
    }
    cellEditRef.current = params;
  },
  [apiRef],
);

return (
  <div style={{ height: 300, width: '100%' }}>
    <DataGrid
      apiRef={apiRef}
      columns={columns}
      rows={rows}
      onCellEditStart={handleCellEditStart}
      slotProps={{
        baseSelect: {
          onClose: stopCellEditMode,
        },
      }}
    />
  </div>
);
```

`handleCellEditStart` just stores the currently edited cell in a ref and, if any other cell is currently in edit mode, stops editing the other one.

The `stopCellEditMode` is also being passed into `slotProps.baseSelect.onClose` that will get called when the select dropdown closes.

If you want to focus another cell, e.g. the one to the right, you can adjust the options of `apiRef.current.stopCellEditMode({ id, field })` to `apiRef.current.stopCellEditMode({ id, field, cellToFocusAfter })`, where `cellToFocusAfter` can have the options: `'none' | 'below' | 'right' | 'left'`

Does that fix your problem?

**Comment by Youssef-8000** [comment]
> Hey @Youssef-8000 this is possible with a little "hack".
> 
> I did update your example [here](https://codesandbox.io/p/sandbox/blue-sunset-6xxkr6?file=%2Fsrc%2FDemo.tsx%3A129%2C14).
> 
> It works like this:
> 
> ```tsx
> const stopCellEditMode = React.useCallback(() => {
>   if (cellEditRef.current) {
>     const { id, field } = cellEditRef.current;
>     apiRef.current.stopCellEditMode({ id, field });
>     cellEditRef.current = null;
>   }
> }, [apiRef, cellEditRef]);
> 
> const handleCellEditStart = React.useCallback(
>   (params: GridCellParams) => {
>     if (cellEditRef.current) {
>       stopCellEditMode();
>     }
>     cellEditRef.current = params;
>   },
>   [apiRef],
> );
> 
> return (
>   <div style={{ height: 300, width: '100%' }}>
>     <DataGrid
>       apiRef={apiRef}
>       columns={columns}
>       rows={rows}
>       onCellEditStart={handleCellEditStart}
>       slotProps={{
>         baseSelect: {
>           onClose: stopCellEditMode,
>         },
>       }}
>     />
>   </div>
> );
> ```
> 
> `handleCellEditStart` just stores the currently edited cell in a ref and, if any other cell is currently in edit mode, stops editing the other one.
> 
> The `stopCellEditMode` is also being passed into `slotProps.baseSelect.onClose` that will get called when the select dropdown closes.
> 
> If you want to focus another cell, e.g. the one to the right, you can adjust the options of `apiRef.current.stopCellEditMode({ id, field })` to `apiRef.current.stopCellEditMode({ id, field, cellToFocusAfter })`, where `cellToFocusAfter` can have the options: `'none' | 'below' | 'right' | 'left'`
> 
> Does that fix your problem?

Thank you for your response but it seems that the link you have provided does not include any of the changes. would you be able to provide a link with such changes as an example
?

**Comment by michelengelen** [comment]
Sure @zannager ... CodeSandbox behaves a little weird lately: [Example](https://codesandbox.io/p/sandbox/blue-sunset-6xxkr6?file=%2Fsrc%2FDemo.tsx%3A129%2C14)

**Comment by Youssef-8000** [comment]
> Sure @Youssef-8000 ... CodeSandbox behaves a little weird lately: [Example](https://codesandbox.io/p/sandbox/wild-bush-k53wzm)

Thank you so much it works perfectly as i imagined it, I have been looking for a solution for DAYS. It took me a little while to get it working with my current code since i'm using RenderCell on my singleSelect, but now it works Perfectly, and this shows me that i should not be scared to use apiRef. Though i never imagined what i wanted to be inside slotProps. If possible can you show me where i can find things like onClose property and other obscure props, because i looked over material UI documentation and i can't seem to find it. Also I will take a look into the slotProps Again, Thank You!

**Comment by michelengelen** [comment]
Yes of course ... you can find all APIs for the components on their respective API page: e.g. [Select Api](https://mui.com/material-ui/api/select/)

For the slots we do have this overview with their default components: [Slots API](https://mui.com/x/api/data-grid/data-grid/#slots)

**Comment by Youssef-8000** [comment]
Thanks, I will be going through them later. I will be closing the the issue post, since it has be resolved.
