### ISSUE TITLE
[data grid] Number cell formatter for aggregation

### ISSUE THREAD

**Issue by RomanMain** [mui/mui-x#12458]
### The problem in depth

When rendering a number into a cell, the table automatically adds a comma depending on the length of the number. We used `valueGetter` and cast that number to a string using the `toString()` method. It looked good, but when aggregation is enabled it doesn't work correctly. Unfortunately we can't use `valueFormatter` for our own reasons. Is there any workaround to set in the configuration so that these commas are not added by default? 
![Screenshot_2](https://github.com/mui/mui-x/assets/43311617/68e62280-5ced-449e-b8e1-bb2c3fd40212)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: number cell, formatter
**Order ID**: 82865

**Comment by michelengelen** [comment]
Hey @cherniavskii could you maybe have a look here?
Thanks!

**Comment by cherniavskii** [comment]
Hi @RomanMain 
The values have to be numeric for aggregation to work properly.
We're using `.toLocaleString()` in our default value formatter, which formats numbers depending on the browser locale.

> Unfortunately we can't use valueFormatter for our own reasons

Can you elaborate?

**Comment by RomanMain** [comment]
> Can you elaborate?

We parse data inside the table according to very different factors. We use `valueGetter` to get what we need (for example, we receive milliseconds from the server as dates, then convert to `new Date()` etc.), but the output needs to remain the same milliseconds. Inline editing is also included and there are many nuances there.

The question is, is there a simple way to display number type without this `.toLocaleString()` conversion?

**Comment by cherniavskii** [comment]
> The question is, is there a simple way to display number type without this .toLocaleString() conversion?

Yes, you can set `valueFormatter: undefined` – see this demo: https://stackblitz.com/edit/react-nwuvjm?file=Demo.tsx
