### ISSUE TITLE
[data grid] How can I use multi-sort for some columns and single-sort for others?

### ISSUE THREAD

**Issue by crscaballero** [mui/mui-x#12453]
### The problem in depth

I'm able to enable/disable the sorting feature by column or enable/disable the multi-sorting for the entire DataGrid, but I can';t find a way to enable multi-sorting for a few columns and just single-sorting for the rest

I've looked into the interfaces and doc without success

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: multisorting
**Order ID**: 78424

**Comment by michelengelen** [comment]
Hey @crscaballero,
Yes, that would be possible by using the [controlled sorting](https://mui.com/x/react-data-grid/sorting/#controlled-sort-model). Simply define which fields are allowed to be multi-sorted and apply the new sort model based on that. here is an example of that: [Controlled Multi-Sort](https://codesandbox.io/p/sandbox/hidden-thunder-xl369h)
Would that be a suificient solution for you?

**Comment by crscaballero** [comment]
Thank you, that was really useful
