### ISSUE TITLE
[data grid] How to pass valueOptions to custom component(AutoCompleteWithCheckBox) in filters

### ISSUE THREAD

**Issue by rajeshreddy-bheemireddy** [mui/mui-x#12455]
### The problem in depth

I am trying to pass options(valueOptions) to a custom input component,  currently, we need a custom Autocomplete when the operator selected is `isAnyOf`, rest of the SingleSelectOperators should work as a single-select drop-down, when I override the `isAnyOf` operator with my custom component I am not able to pass the options to it. The rest of the operators `is`, `isNot` are getting the options passed down. How do I pass options to my custom component? 

Below is a rough code snippet for my implementation.
Currently valueOptions are static, planned to pass dynamic options.

```
// This is not a fully functional code
const AutoCompleteWithCheckBox = props => {
  const { item, applyValue } = props;

  const [close, setClose] = useState(false);
  const handleClose = () => {
    console.log('handleClose');
    setClose(true);
  };

  return (
    <Autocomplete
      multiple
      value={item.value}
      filterOptions={(options, params) => {
        const filter = createFilterOptions();
        const filtered = filter(options, params);
        return [{ label: 'Select All...', all: true }, ...filtered];
      }}
      onChange={(event, newValue) => {
        applyValue({ ...item, value: newValue });
      }}
      options={valueOptions} // Need to pass the valueOptions to the Autocomplete
      disableCloseOnSelect
      onClose={handleClose}
      onOpen={() => setClose(false)}
      getOptionLabel={option => option.label}
      renderOption={(props, option, { selected }) => (
        <li {...props}>
          <Checkbox
          />
          {option.label}
        </li>
      )}
      style={{ width: 200 }}
      renderInput={params => (
        <Box >
        </Box>
      )}
    />
  );
};

const isSingleSelectOperator = () => getGridSingleSelectOperators()
  .map((operator) => {
    console.log('operator', operator);
    return {
    ...operator,
    InputComponent: operator.value === 'isAnyOf'
      ? AutoCompleteWithCheckBox
      : operator.InputComponent,
  };
});

const columns = [
    {
      field: 'name',
      headerName: 'Name',
      minWidth: 170,
      filterable: false,
    },
    {
      field: 'test',
      headerName: 'Test',
      minWidth: 90,
      type: 'singleSelect',
      valueOptions: [
        { label: 'test1', value: 'Test1' },
        { label: 'test2', value: 'Test2' },
        { label: 'test3', value: 'Test3' },
      ],
      filterOperators: isSingleSelectOperator(),
    },
  ];
```

### Your environment

  Don't forget to mention which browser you used.

     Using Chrome browser.

  Output from `npx @mui/envinfo` goes here.

   System:
    OS: macOS 13.3.1
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    Yarn: Not Found
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
  Browsers:
    Chrome: 121.0.6167.160
    Edge: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.9.0 => 11.11.1 
    @emotion/styled: ^11.8.1 => 11.11.0 
    @mui/base:  5.0.0-beta.13 
    @mui/core-downloads-tracker:  5.14.7 
    @mui/icons-material: ^5.8.0 => 5.14.7 
    @mui/lab: ^5.0.0-alpha.83 => 5.0.0-alpha.142 
    @mui/material: ^5.10.17 => 5.14.7 
    @mui/private-theming:  5.14.7 
    @mui/styled-engine:  5.14.7 
    @mui/system:  5.14.7 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.15 
    @mui/x-data-grid:  6.17.0 
    @mui/x-data-grid-premium: ^6.16.2 => 6.17.0 
    @mui/x-data-grid-pro: ^6.3.0 => 6.17.0 
    @mui/x-license-pro: ^6.0.4 => 6.10.2 
    @types/react: ^17.0.0 => 17.0.65 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.0 => 5.3.11 
    typescript: ^3.9.3 => 3.9.10

**Search keywords**: filter panel, Custom input component
**Order ID**: 75705

**Comment by michelengelen** [comment]
Hey @rajeshreddy-bheemireddy,

Could you please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by michelengelen** [comment]
Hey again @rajeshreddy-bheemireddy,

I have played around with it a bit and found a possible solution: [Example](https://codesandbox.io/p/sandbox/beautiful-https-2hdx56)

Could you try this and tell us if this is suficient for your use case?
Thanks! 🙇🏼

**Comment by rajeshreddy-bheemireddy** [comment]
> Hey again @rajeshreddy-bheemireddy,
> 
> I have played around with it a bit and found a possible solution: [Example](https://codesandbox.io/p/sandbox/beautiful-https-2hdx56)
> 
> Could you try this and tell us if this is suficient for your use case? Thanks! 🙇🏼

Tried this and working for my requirement, retrieving `valueOptions` from `useGridApiContext` helped resolve my issue. Thanks!
