### ISSUE TITLE
[data grid] Cannot set properties of null (setting 'scrollLeft')

### ISSUE THREAD

**Issue by Nick-Lucas** [mui/mui-x#12459]
### Steps to reproduce

The specific reproduction steps for this one are difficult, we believe it's due to a combination of using `useGridApiRef` in the parent component, filterModel props set to access state, and React Suspense for data loading. We are not overriding the header components so ref is still getting passed through, but the ref value for columnHeadersContainerElementRef is going null

Essentially when engaging a filter via a header dropdown, this error comes up and crashes the app. It's not consistently reproducible though

### Current behavior

The datagrid errors when applying filters via a header

### Expected behavior

The datagrid can apply filters without erroring

### Context

These are the erroring lines, they assume `columnHeadersContainerElementRef.current` is always set, but there seems to be some cases where it is not set, possibly due to a race condition when used within a suspended component which is showing a fallback.

https://github.com/mui/mui-x/blob/a518d0a2ecd8cd3ed66c60526681f0130e6dba50/packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx#L100

https://github.com/mui/mui-x/blob/a518d0a2ecd8cd3ed66c60526681f0130e6dba50/packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx#L261

Most likely these lines just need hardening to the possibility of the value not being set

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.12.1 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @mui/icons-material: ^5.15.7 => 5.15.9 
    @mui/material: ^5.15.7 => 5.15.9 
    @mui/styled-engine-sc: ^5.14.12 => 5.14.12 
    @mui/system: ^5.15.7 => 5.15.9 
    @mui/x-data-grid-premium: ^6.19.3 => 6.19.3 
    @mui/x-date-pickers-pro: ^6.19.3 => 6.19.3 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: 18.2.24 => 18.2.24 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components: 5.3.5 => 5.3.5 
    typescript: 5.3.3 => 5.3.3 
</details>

**Search keywords**: Cannot set properties of null (setting 'scrollLeft')
**Order ID**: 79244

**Comment by michelengelen** [comment]
@romgrk could you have a look at this? Thanks! 🙇🏼

**Comment by michelengelen** [comment]
@Nick-Lucas Even if it is difficult to reproduce, could you please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by Nick-Lucas** [comment]
Yes I'll have a look at a reproduction this afternoon. We've been seeing this error sporadically for a while and haven't been able to reliably reproduce in our app, but it's come up more reliably today. The datagrid's props validation also warns above the error that the `apiRef.current` value is null although a console log in our root component shows that on render it does have a value. This makes me think the cause is around react swapping out the ref value at some point during render and the datagrid has a race condition (root component is not remounting though, I checked this)

Last time this came up I did try patching the linked lines locally and recall the problem went away, so I suspect the fix is just to access scollLeft more safely then is currently being done.

**Comment by vsacom** [comment]
Just commenting that this ticket is somewhat related to another ticket; #12360, although there the first error comes from useGridColumnHeaders. 
Reproducible with Preact and DataGridPro. The error comes from the community-side code, which the DataGridPro-grid utilizes partially.

**Comment by Nick-Lucas** [comment]
Right I've managed a reproduction, though not 100% sure if it's the exact scenario since our application is fairly complex and uses react-query with tRPC for data loading.

[coresandbox](https://codesandbox.io/p/sandbox/kind-lichterman-26qwzh?file=%2Fsrc%2FDemo.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltsqutpa00073b6hogavunaa%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltsqutp900033b6hh0kj6iw7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltsqutp900043b6hjf5yay0y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltsqutp900063b6hyqdymokl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40.750759227159996%252C59.249240772840004%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltsqutp900033b6hh0kj6iw7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltsqutp900023b6hzy3m0c6c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cltsqutp900033b6hh0kj6iw7%2522%252C%2522activeTabId%2522%253A%2522cltsqutp900023b6hzy3m0c6c%2522%257D%252C%2522cltsqutp900063b6hyqdymokl%2522%253A%257B%2522id%2522%253A%2522cltsqutp900063b6hyqdymokl%2522%252C%2522activeTabId%2522%253A%2522cltsqutp900053b6hblvar7db%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltsqutp900053b6hblvar7db%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522cltsslzds01kk3b6ip7x1pqq2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cltsqutp900043b6hjf5yay0y%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltsqutp900043b6hjf5yay0y%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

The error does appear to be related to suspense, since React throws away renders and I suppose this may mess with availability of refs. The workaround (and I believe correct usage of suspense) is to wrap all the setState calls in onFilterModelChange in `startTransition`

It would be ideal to see the refs code hardened although this sandbox does demonstrate that react APIs can be used to prevent the issue

**Comment by romgrk** [comment]
I've tested the example above and I can't reproduce. Can you confirm which OS/browser versions you're using? Do you have any more details that could help us trigger it?

**Comment by Nick-Lucas** [comment]
Oops, sorry @romgrk I somehow managed to paste the original example link instead of the reproduction, I've updated the original link and here it is:

[codesandbox reproduction](
https://codesandbox.io/p/sandbox/mui-x-datagrid-issue-12459-tl2vy4?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltsqutpa00073b6hogavunaa%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltsqutp900033b6hh0kj6iw7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltsqutp900043b6hjf5yay0y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltsqutp900063b6hyqdymokl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40.750759227159996%252C59.249240772840004%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltsqutp900033b6hh0kj6iw7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltsqutp900023b6hzy3m0c6c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cltsqutp900033b6hh0kj6iw7%2522%252C%2522activeTabId%2522%253A%2522cltsqutp900023b6hzy3m0c6c%2522%257D%252C%2522cltsqutp900063b6hyqdymokl%2522%253A%257B%2522id%2522%253A%2522cltsqutp900063b6hyqdymokl%2522%252C%2522activeTabId%2522%253A%2522cltsqutp900053b6hblvar7db%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltsqutp900053b6hblvar7db%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522cltsslzds01kk3b6ip7x1pqq2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cltsqutp900043b6hjf5yay0y%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltsqutp900043b6hjf5yay0y%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by michelengelen** [comment]
@romgrk I can confirm the described behavior. However I am not able to find a solution for this atm. Could you have a look again?

**Comment by Nick-Lucas** [comment]
Yep I would agree with that. The good thing is if the datagrid doesn't crash then react will be able to warn about the need for startTransition, it's pretty good at warning when these cases do appear
