### ISSUE TITLE
[data grid] Misaligned pinned column header when nested in a parent with scrollbar

### ISSUE THREAD

**Issue by sydneyjodon-wk** [mui/mui-x#12451]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/datagrid-pinned-column-with-parent-scrollbar-gxv8p6?file=%2Fsrc%2FDemo.tsx%3A29%2C37

Steps:

1. Change user preferences to either always show scrollbars or automatically show based on mouse or trackpad (this was on a Mac) - for some reason this does not happen on the "when scrolling" setting
![Screenshot 2024-03-14 at 12 09 59 PM](https://github.com/mui/mui-x/assets/51122966/a956686b-a28b-464c-842a-2d593adea678)
2. Render a DataGrid with no vertical scrollbar inside a parent container that has a scrollbar (see link above)
3. See column header alignment for the pinned column (see screenshot below)

### Current behavior

Hello! 👋 

We are running into an issue with the alignment of pinned column header similar to [this issue](https://github.com/mui/mui-x/issues/10238) (see screenshot below), except it only happens when the DataGrid does not have a vertical scrollbar itself, but is rendered inside a parent container that does have a scrollbar.

![Screenshot 2024-03-14 at 12 13 00 PM](https://github.com/mui/mui-x/assets/51122966/510f1f05-eda3-4f8d-92ed-a6a24a702314)

This specifically happens on certain user preferences for scrollbars to always or automatically show (see Steps to reproduce section for more info).

It looks like an additional 15px of padding is being added to account for a scrollbar that isn't actually there:

![Screenshot 2024-03-14 at 12 15 35 PM](https://github.com/mui/mui-x/assets/51122966/c95a7537-4bf9-4bb1-9d6f-00a4aa4dcda7)

### Expected behavior

I would expect the divider for the header of the pinned row column to align with the rest of the cells in the column.

Thank you!

**Search keywords**: pinned column scrollbar, header alignment
**Order ID**: 82849

**Comment by romgrk** [comment]
Might be affected by #12376, let's test it again after today's release.

**Comment by michelengelen** [comment]
I cannot reproduce anymore. Could you check in your implementation as well @sydneyjodon-wk ?

**Comment by sydneyjodon-wk** [comment]
It looks like that fixed it! Thank you!!
