### ISSUE TITLE
Upgrade to AdapterDateFns Version 3

### ISSUE THREAD

**Issue by akhnaz** [mui/mui-x#12467]
### Summary

It should work like current AdapterDateFns, but using latest [Date-Fns Version 3](https://blog.date-fns.org/v3-is-out/).

### Examples

https://mui.com/x/react-date-pickers/date-picker/

### Motivation

I wanted to use 'Strings as arguments' for the value for the DatePicker (Controlled component).

**Search keywords**: AdapterDateFns

**Comment by LukasTy** [comment]
Hello @akhnaz 
It looks like a duplicate of https://github.com/mui/mui-x/issues/12144.
The correct usage is [documented here](https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns).
Or my assumption was incorrect and this is an actual problem with `AdapterDateFnsV3`? 🤔 

P.S. Have you noticed a console error that should be thrown in the development environment if you are trying to use `date-fns@v3` with `AdapterDateFns`?
Do you have any suggestions on how we could make it more clear? 🤔

**Comment by akhnaz** [comment]
Hi @LukasTy 
Sorry, my mistake, I overlooked how to use AdapterDateFnsV3 with the DatePicker. Now it works perfectly. Thanks for pointing it out and for your quick and really helpful reply.
