### ISSUE TITLE
[Charts] Barchart with empty dataset should render an empty chart

### ISSUE THREAD

**Issue by Janpot** [mui/mui-x#12462]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-vvrvzj?file=Demo.tsx

Steps:
1. open demo
2.
3.

### Current behavior

```
Error in /turbo_modules/@mui/x-charts@6.19.5/BarChart/extremums.js (22:36)
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

### Expected behavior

An empty chart is shown, as if `series={[]}`

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: empty barchart

**Comment by nivb52** [comment]
It seems you need at list one item in the array - 
```js
const dataset = [{}];
```
