### ISSUE TITLE
[data grid] onRowSelectionModelChange details return has incorrect type definitions 

### ISSUE THREAD

**Issue by austin5456** [mui/mui-x#12464]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/stackblitz-starters-31n5eg?file=src%2FGridRenderTracer.tsx,src%2FApp.tsx
Select a row and check the console.log output to see that it has both {reason, api}, the types don't list api as a possible return
( ignore the other tracing junk in that example, it was from previous testing )

Steps:
1.open the link
2.open the dev tools -> console
3.select a rows checkbox
4.observe the output in the console

### Current behavior

the `api` is returned as a sibling of `reason` in `details`, but the typings don't show that

https://github.com/mui/mui-x/blob/6549091440f6d13a8c48d6a89d3bf9fe5a77bfa0/packages/x-data-grid/src/models/props/DataGridProps.ts#L679

https://github.com/mui/mui-x/blob/6549091440f6d13a8c48d6a89d3bf9fe5a77bfa0/packages/x-data-grid/src/models/api/gridCallbackDetails.ts

### Expected behavior

it should match the typings

### Context

I might have to use the api from this return, I'm unsure if it is meant to be there so I don't want to extend the interface on my side for it to be later pruned and break my stuff

**Search keywords**: onRowSelectionModelChange, GridCallbackDetails

**Comment by michelengelen** [comment]
Yes, this is incorrectly typed.

This diff will fix that:
```diff
diff --git a/packages/x-data-grid/src/models/api/gridCallbackDetails.ts b/packages/x-data-grid/src/models/api/gridCallbackDetails.ts
index bf5bf45b5..e4a8f4cb4 100644
--- a/packages/x-data-grid/src/models/api/gridCallbackDetails.ts
+++ b/packages/x-data-grid/src/models/api/gridCallbackDetails.ts
@@ -1,4 +1,5 @@
 import { GridControlledStateReasonLookup } from '../events/gridEventLookup';
+import { GridApiCommunity } from './gridApiCommunity';

 /**
  * Additional details passed to the callbacks
@@ -8,4 +9,8 @@ export interface GridCallbackDetails<K extends keyof GridControlledStateReasonLo
    * The reason for this callback to have been called.
    */
   reason?: GridControlledStateReasonLookup[K];
+  /**
+   * GridApi that let you manipulate the grid.
+   */
+  api: GridApiCommunity;
 }
```

Since this is a fairly easy fix I will add the `good first issue` label

Thanks for raising this @austin5456
