### ISSUE TITLE
[pickers] Cannot display time with format without spaces like "HHmm" correctly

### ISSUE THREAD

**Issue by samchiu90** [mui/mui-x#12487]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-jjpkxw?file=Demo.tsx

Steps:

1. Set format="HHmm" in TimeField
2. Give it a defaultValue (15:30)

Version: 6.19.7

`dayjs` and `TimeField` are used in the example

`moment` and `DateTimePicker` also have this problem.

In [#10007](https://github.com/mui/mui-x/issues/10007) and [#10185](https://github.com/mui/mui-x/pull/10185) said it was fixed, but same problem on `dayjs` and `moment`

### Current behavior

It displays `15m30` 

### Expected behavior

It should display `1530`

### Context

Showing time with format `HHmm` in `DateTimePicker` with `Moment`

**Search keywords**: DateTimePicker TimeField HHmm format moment dayjs

**Comment by flaviendelangle** [comment]
:grimacing: The PR did not contain any test so hard to see if it worked and was broken or if it never worked.

In any case, I think the new PR solves the problem for all 4 adapters.
