### ISSUE TITLE
[DataGridPro] Component trace in console licence warning

### ISSUE THREAD

**Issue by Javaman44** [mui/mui-x#1248]
When i use trial version of XGRID i see warning message in console, but sometimes i see also a stacktrace

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
You can see the problem in the codesandbox: https://5mu30.csb.app/  when you refresh the page
![image](https://user-images.githubusercontent.com/9351983/111499415-349a0600-8743-11eb-9d35-cebe1bf646a3.png)

(for see source files => https://codesandbox.io/s/distracted-field-5mu30?file=/src/App.tsx)

## Expected Behavior 🤔
Only show licence warning 

## Context 🔦
I try to use XGrid for CRUD operation with react-hook-form

## Your Environment 🌎
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 15.0.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.0.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: latest
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @emotion/react: latest => 11.1.5
    @emotion/styled: latest => 11.1.5
    @material-ui/core: latest => 4.11.3
    @material-ui/data-grid: latest => 4.0.0-alpha.22
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/styles:  4.11.3
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: 4.0.0-alpha.22 => 4.0.0-alpha.22
    @material-ui/x-license:  4.0.0-alpha.21
    @types/react: ^16.9.53 => 16.14.2
    react: latest => 17.0.1
    react-dom: latest => 17.0.1
    typescript: ^4.0.3 => 4.1.3

**Comment by oliviertassinari** [comment]
@Javaman44 From what I understand, this is a React component trace. However, I can't reproduce it. Loading https://5mu30.csb.app/ does nothing for me.

**Comment by oliviertassinari** [comment]
Oh right, I get it now. Yeah, it's a bug. It should be easy to fix.

**Comment by oliviertassinari** [comment]
I would propose this solution:

```diff
diff --git a/packages/x-license/src/licenseErrorMessageUtils.ts b/packages/x-license/src/licenseErrorMessageUtils.ts
index ee4b7215..a63647d9 100644
--- a/packages/x-license/src/licenseErrorMessageUtils.ts
+++ b/packages/x-license/src/licenseErrorMessageUtils.ts
@@ -1,4 +1,4 @@
-function showError(message: string[]) {
+function logError(message: string[]) {
   console.error(
     [
       '************************************************************',
@@ -12,6 +12,16 @@ function showError(message: string[]) {
   );
 }

+function showError(message: string[]) {
+  if (process.NODE_ENV === 'test') {
+    logError(message);
+  } else {
+    setTimeout(() => {
+      logError(message);
+    });
+  }
+}
+
 export function showInvalidLicenseError() {
   showError([
     'Material-UI X: Invalid license.',
```

**Comment by oliviertassinari** [comment]
I'm giving up on the idea. I believe seeing the component stack trace is actually helpful, to find which component is triggering it. @Javaman44 Thanks for the feedback!
