### ISSUE TITLE
[TimePicker] AM/PM button does not have selected class for font style customization

### ISSUE THREAD

**Issue by vatan-qss** [mui/mui-x#12493]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Use timepicker component to show time picker clock.
2. Now after opening the timepicker pop up. Try to inspect it.
3. Now inspect the selected button from AM or PM whichever is shown selected.
4. The selected button does not contain any selected class which i can use to cusotmize the selected state of AM or PM button.

### Current behavior

As per current behaviour the timepicker am/pm button doesnot show any selected class on it because of which it is not possible to customize the selected state of these button.
<img width="950" alt="image" src="https://github.com/mui/mui-x/assets/59604211/df8c8dd5-4f48-4e75-9325-76b492b11b7a">
As per the above screenshot we are not able to update the font styles of AM button if we want to show different font color or font weight for selected state.
Same case happens with the PM button as well when it is in selected state. 

### Expected behavior

Expected behavior should be like, we should have a selected class for example like **Mui-selected** on the selected button, so that we can overwrite the styles by catching that class. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: AM PM css customization

**Comment by LukasTy** [comment]
Thank you for a great observation! 🙏 
The current solution is far from ideal and needs to be improved. 🙈 
I'm adding this issue to the board for grooming. 👌
