### ISSUE TITLE
[TreeView] Investigate if `aria-activedescendant` attribute is necessary

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#12494]
Created from: https://github.com/mui/mui-x/pull/12226#discussion_r1525135132

It looks like the `tree` role [is not listed](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-activedescendant#associated_roles) to support `aria-activedescendant` attribute.
W3C examples seem to confirm it by not having this attribute [in their examples](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-1a/).

To be confirmed with other libraries and checking the behavior after removing it.

**Search keywords**:

**Comment by flaviendelangle** [comment]
Found in https://www.w3.org/WAI/ARIA/apg/patterns/treeview/

> The tree role supports the [aria-activedescendant](https://w3c.github.io/aria/#aria-activedescendant) property, which provides an alternative to moving DOM focus among treeitem elements when implementing keyboard navigation. For details, see [Managing Focus in Composites Using aria-activedescendant](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_focus_activedescendant).

> If a component container has an ARIA role that supports the [aria-activedescendant](https://w3c.github.io/aria/#aria-activedescendant) property, it is not necessary to manipulate the tabindex attribute and move DOM focus among focusable elements within the container. Instead, only the container element needs to be included in the tab sequence. When the container has DOM focus, the value of aria-activedescendant on the container tells assistive technologies which element is active within the widget.

So, from what I understand, it was needed before, but no longer is

**Comment by LukasTy** [comment]
> So, from what I understand, it was needed before, but no longer is since we focus the item directly

Yes, makes total sense. 👍
