### ISSUE TITLE
Validation not working for MobileDatePicker& MobileTimePicker components

### ISSUE THREAD

**Issue by mazenadel19** [mui/mui-x#12497]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/sweet-moon-d4xl8x?file=%2Fsrc%2FDemo.js%3A45%2C10-45%2C26

### Current behavior

form is submitting and ignoring MobileDatePicker& MobileTimePicker which are required and have no value, required seems to be set successfully on the html

![image](https://github.com/mui/mui-x/assets/26392390/27136ebb-3188-4a8b-b76c-8a02fb89e865)

### Expected behavior

form shouldn't submit if there's no value for the MobileDatePicker or MobileTimePicker

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (122.0.2365.52)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.39 
    @mui/core-downloads-tracker:  5.15.13 
    @mui/icons-material: ^5.15.12 => 5.15.12 
    @mui/lab: ^5.0.0-alpha.167 => 5.0.0-alpha.167 
    @mui/material: ^5.15.13 => 5.15.13 
    @mui/private-theming:  5.15.13 
    @mui/styled-engine:  5.15.11 
    @mui/styles: ^5.15.13 => 5.15.13 
    @mui/system:  5.15.12 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.13 
    @mui/x-date-pickers: ^6.19.6 => 6.19.6 
    @types/react:  18.2.42 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  3.9.10 
```
</details>

**Search keywords**: MobileDatePicker, Validation

**Comment by LukasTy** [comment]
This is a side-effect of `Mobile` Pickers having the `readonly` prop.
We have a separate issue (https://github.com/mui/mui-x/issues/7869) for removing this prop.
@mui/explore WDYT, would it make sense to put the mentioned issue back to grooming and properly discuss, groom, and prioritize? Having it in "to explore" "Neverland" does not sound promising. 🙈 

In the meantime, if you are fine with a not-ideal solution, consider overriding the `readonly` prop with:
```jsx
<MobileDatePicker
  label="Mobile date"
  slotProps={{
      field: {
        readOnly: false,
    },
  }}
/>
```

**Comment by mazenadel19** [comment]
I gave the solution a try, and it worked like a charm! 
Thanks a bunch for your help, I'll go ahead and close this since I see you're already keeping an eye on the same issue elsewhere.
