### ISSUE TITLE
[data grid] "Using a web worker" sample crashes when printing

### ISSUE THREAD

**Issue by korpthidrandir** [mui/mui-x#12502]
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/export/#using-a-web-worker

Steps:
1. Using Chrome Version 122.0.6261.129 (Official Build) (64-bit)
2. Go to link
3. Click Export
4. Click Print
5. Wait
6. "Error code: Out of Memory"

### Current behavior

Browser crashes with out of memory

### Expected behavior

A print dialog with all 10k rows rendered

### Context

Testing the sample. Also we want to implement this feature in our product.

### Your environment

N/A

**Search keywords**: print
**Order ID**: 76650

**Comment by romgrk** [comment]
I can reproduce the issue.

**Comment by cherniavskii** [comment]
Hi @korpthidrandir 

First of all, I have to clarify that the "Using a web worker" sample demonstrates the Excel export with Web Worker.
For Print export, it looks like that 10k rows is too much for the Print export to handle.

What feature are you looking for?
