### ISSUE TITLE
Search bar is loosing focus on when we use custom multiselect component with filter model 

### ISSUE THREAD

**Issue by Abhisutar** [mui/mui-x#12528]
### Steps to reproduce

Link to live example: (required)

Steps:
1.  Code Sanbox Link - https://codesandbox.io/p/sandbox/customer-datagrid-with-custom-filters-6vf98m?file=%2Fsrc%2FApp.tsx
2. Check the search component it is loosing the focus .
3.  Also i am looking for multiselect component which  can be directly apply to the muix data grid table 

### Current behavior

I want to apply custom filters to muix data grid table using filter model but i am if i am applying it then seach component  is loosing its focus because it is  re-rendering the component - 

Code Sanbox Example -https://codesandbox.io/p/sandbox/customer-datagrid-with-custom-filters-6vf98m?file=%2Fsrc%2FApp.tsx

and also i want to apply Multi select component for the filter , currently muix data grid provides only singleselect component but i want to know if we can use multiselect component directly 

### Expected behavior

Custom filter should work with filter model and as well default search bar should work . It should not loose the focus 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: filter model , filter , muix multi select component

**Comment by romgrk** [comment]
Your code seems to be suffering from this issue: https://dev.to/borasvm/react-create-component-inside-a-component-456b

You should create the component outside the function and you can pass props to it via `slotProps={{ toolbar: { ... } }}`.
