### ISSUE TITLE
[data grid] Is it possible to support copyValueParser in DataGrid?

### ISSUE THREAD

**Issue by LesleyYiu** [mui/mui-x#12532]
### The problem in depth

Hello, I have some questions regarding the clipboard functionality in the DataGrid component. While using the DataGrid, I encountered a scenario where I needed to work with an object type value in one of the columns. I noticed that there is a `pastedValueParser` property available for customizing the parsing of pasted values. However, I couldn't find a corresponding built-in `copyValueParser` property for customizing the parsing of copied values.

Is it possible to add support for a `copyValueParser` property in the `GridColDef` interface or provide another solution to customize the parsing of copied values? This would greatly enhance the flexibility and extensibility of the DataGrid component when working with complex data types.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.19.1 - ~\AppData\Local\Volta\tools\image\node\18.19.1\node.EXE
    npm: 10.2.4 - ~\AppData\Local\Volta\tools\image\node\18.19.1\npm.CMD
    pnpm: 7.32.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: Not Found
    Edge: Chromium (122.0.2365.92)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/icons-material: ^5.15.0 => 5.15.0
    @mui/lab: 5.0.0-alpha.130 => 5.0.0-alpha.130
    @mui/material: ^5.15.0 => 5.15.0
    @mui/system: ^5.13.1 => 5.13.1
    @mui/x-data-grid: ^6.18.5 => 6.18.5
    @mui/x-data-grid-premium: ^6.18.5 => 6.18.5
    @types/react: 18.0.28 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.0.4 => 5.0.4
```
</details>

**Search keywords**: Clipboard copy
**Order ID**: 70106

**Comment by romgrk** [comment]
Have you tried configuring the [valueFormatter](https://mui.com/x/react-data-grid/column-definition/#value-formatter)?

**Comment by LesleyYiu** [comment]
Thank you for your prompt response. I have already experimented with the valueFormatter, but in my particular scenario, I would prefer to retain the original value unless making a copy

**Comment by romgrk** [comment]
You need to remove `ignoreValueFormatterDuringExport`, otherwise your JSON object is exported as-is, and string coercicion in javascript turns it into `[object Object]`. I'm not sure why you would want to avoid the value formatter if you're trying to control the exported value, if you think you have a use-case that isn't covered by the grid please give us more details.

**Comment by LesleyYiu** [comment]
ok, i will use `valueFormatter` with `renderCell ` to do it , thanks for your reply
