### ISSUE TITLE
[data grid] Client side filtering while filter mode is set to "server"

### ISSUE THREAD

**Issue by Nitzperetz** [mui/mui-x#12544]
### The problem in depth

Using "server" filtermode for DataGridPro I expect no filtering what so ever happen in the client side.
When using the filter panel and start typing a value in the filter - the data grid filters immediately the values that are currently presented and only then re-renders with the values from the server - since the values are different the grirs has different states and the presented data is different for a glance.

![image](https://github.com/mui/mui-x/assets/15967181/780429af-a6fc-46fa-ba5d-4bf045ae19ea)

I would like to understand how to disable the client side search.
I am using a custom DataToolbar with the builtin `GridToolbarFilterButton` component.

Thanks.
 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 14.3.1
  Binaries:
    Node: 20.6.1 - /opt/homebrew/bin/node
    npm: 9.9.2 
    pnpm: 8.6.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Edge: 122.0.2365.80
    Safari: 17.3.1
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4
    @emotion/styled: 11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.17
    @mui/core-downloads-tracker:  5.14.11
    @mui/icons-material: 5.14.11 => 5.14.11
    @mui/lab: 5.0.0-alpha.146 => 5.0.0-alpha.146
    @mui/material: 5.14.11 => 5.14.11
    @mui/private-theming:  5.14.11
    @mui/styled-engine:  5.14.11
    @mui/system: 5.14.11 => 5.14.11
    @mui/types: 7.2.4 => 7.2.4
    @mui/utils:  5.15.7
    @mui/x-data-grid: 6.19.3 => 6.19.3
    @mui/x-data-grid-pro: 6.19.3 => 6.19.3
    @mui/x-license-pro: 6.10.2 => 6.10.2
    @mui/x-tree-view:  6.0.0-alpha.1
    @types/react: 18.2.18 => 18.2.18
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```
</details>

**Search keywords**: DataGridFilterPanel, FilterPanel, filterFormProps
**Order ID**: 68140

**Comment by MBilalShafi** [comment]
Hey @Nitzperetz, I can not observe the mentioned behavior in the official docs [demo](https://mui.com/x/react-data-grid/filtering/server-side/) for the server-side filtering, it seems like you are using the custom filtering UI.

Could you provide a **minimal** reproduction test case with the latest version? This would help a lot 👷.

A live example would be perfect. You can find examples and guides on how to find templates in our docs with which you can provide examples for your specific use case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by Nitzperetz** [comment]
Hey @MBilalShafi , thank you for responding.
I am using the custom filtering UI.
Attaching a video of the behaviour - you can see for a glance client side filtering (1 row is presented), when the response from the server arrives (with no results) you can see no results.

https://github.com/mui/mui-x/assets/15967181/0da2d562-666e-4b9a-ab0d-9001112c8836

Am I missing anything?

**Comment by michelengelen** [comment]
Hey @Nitzperetz I can confirm that behavior you see and agree that there probably should not be any client side filtering when using the server filtering mode, except I do miss something important 🤔 

I will add this to our board for the team to have a look.

cc @MBilalShafi ^^

**Comment by Nitzperetz** [comment]
Much appreciated @michelengelen , @MBilalShafi

**Comment by Nitzperetz** [comment]
Hey Mui team. This issue turned out to be critical for us.
It creates data discrepancy - the most basic search ability simply doesn't work and the server data is ignored.


In the video you can see a simple exmaple - the rows property hold the value of `status:enabled` while the title in the cell that holds the status is "Active".
In this case the datagrid filters out the values eventhough the rows property is being passed from the server according to the documentation.

https://github.com/mui/mui-x/assets/15967181/cbcab2f3-d1ea-4772-9f76-7a0994235c2e

**Comment by Nitzperetz** [comment]
Hey Mui Team - after further investigation, we think the problem caused by our configuration mismatche, which makes this issue invalid.
Thank you for the quick response.
