### ISSUE TITLE
[DataGrid] How to type custom slots components with their props v7

### ISSUE THREAD

**Issue by pcorpet** [mui/mui-x#12546]
### The problem in depth

When trying to migrate our codebase to v7, we get stuck by strict typing of the `slots` prop. It used to be very flexible (too much indeed), and just checking the slot keys, while the component types given as slots were wide open (any props would work).

However with the new typing of `GridSlotsComponent`, for instance to set up a simple `toolbar` slot, this one needs to use a component that have for props `GridToolbarProps & ToolbarPropsOverrides`. However we use `DataGrid` in many places in our app, and the `ToolbarPropsOverrides` is not always the same: how would you type it properly?

Extract from our code:
```ts
interface EditToolbarProps {
	setRowModesModel: (newModel: GridRowModesModel) => void
	enableAdd: boolean
}
const slots = {
	toolbar: EditToolbar,
}

const MyTable = ({values}: MyProps) => {
	const [rowModesModel, setRowModesModel] = useState<GridRowModesModel>({})
	const slotProps = useMemo(
		() => ({
			toolbar: { setRowModesModel, enableAdd: values.every(v=> v.id !== 0) },
		}),
		[values]
	)
	...
	<DataGrid
			rows={values}
			columns={COLUMNS}
			editMode="row"
			getRowId={getRowId}
			disableColumnMenu
			autoHeight
			hideFooter
			slots={slots}
			slotProps={slotProps}
			rowModesModel={rowModesModel}
		/>
```

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 14.3.1
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.58
  npmPackages:
    @emotion/react: 11.11.3 => 11.11.3 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.14 
    @mui/lab: 5.0.0-alpha.169 => 5.0.0-alpha.169 
    @mui/material: 5.15.14 => 5.15.14 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.14 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.0.0 
    @mui/x-data-grid-premium: 7.0.0 => 7.0.0 
    @mui/x-data-grid-pro:  7.0.0 
    @mui/x-date-pickers: 6.19.7 => 6.19.7 
    @mui/x-license:  7.0.0 
    @types/react: 18.2.67 => 18.2.23 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.4.2 => 5.4.2 
```
</details>

**Search keywords**: Datagrid Typescript slots v7
**Order ID**: 79739

**Comment by vitalikda** [comment]
@pcorpet i've found this example, might be helpful to you as well 
https://github.com/mui/mui-x/blob/master/docs/data/data-grid/components/components.md?plain=1#L203C1-L208C2

**Comment by pcorpet** [comment]
Thanks Vitaly: this would affect the type for ALL toolbar slots in my app, whereas I have different types depending on DataGrid.

**Comment by pcorpet** [comment]
OK I'll do that. Thanks.
