### ISSUE TITLE
DataGrid Column types always never

### ISSUE THREAD

**Issue by nhibberd** [mui/mui-x#12560]
### The problem in depth

I'm in the process of upgrading from data-grid-pro v6 to data-grid-premium v7 and can't find a good solution to the `valueGetter` / `valueFormatter` `value: never` in typescript:

The underly types https://github.com/mui/mui-x/blob/0e1dce4afeaf0146e1260fdf71ffc78d582ca28d/packages/x-data-grid/src/models/colDef/gridColDef.ts#L44-L66 default `TValue = never` and expose `value: TValue`. The `GridBaseColDef` definition (doesn't expose that type parameter):
```ts
  valueGetter?: GridValueGetter<R, V, F>;
  valueFormatter?: GridValueFormatter<R, V, F>;
```

So all my code now is:
```ts
const columns: GridColDef<Rows[number]>[] = [
          {
            field: "custom_field",
            headerName: "Custom Field",
            width: 400,
            valueGetter: (value, row) =>
              renderCustomField(row.custom_field)
          }
]          
```

Where `value: never` and `row: Rows[number]`. Seems that I always need to specify the value argument but can never consume it easily? Not sure what I'm missing here

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
# using chrome

   System:
    OS: macOS 14.4
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v20.5.1/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.59
    Edge: Not Found
    Safari: 17.4
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.124 => 5.0.0-alpha.124 
    @mui/material: ^5.11.14 => 5.11.14 
    @mui/material-nextjs: ^5.15.0 => 5.15.0 
    @mui/x-data-grid-premium: ^7.0.0 => 7.0.0 
    @mui/x-date-pickers-pro: ^7.0.0 => 7.0.0 
    @mui/x-license: ^7.0.0 => 7.0.0 
    @types/react: ^18.2.41 => 18.2.41 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    styled-components: ^5.3.9 => 5.3.9 
    typescript: 5.3.x => 5.3.2 
```
</details>

**Search keywords**: gridcoldef data-grid typescript never
**Order ID**: 87184

**Comment by romgrk** [comment]
You can add the typing yourself:
![image](https://github.com/mui/mui-x/assets/1423607/69ac867f-7f3e-4827-83c3-6b0d1df61392)
Or just `value: string`

It wasn't possible to provide enough type safety for the changes we needed to do with the previous approach of using `any` everywhere. Let us know if that answers your questions.

**Comment by nhibberd** [comment]
It does, thanks

**Comment by visualjerk** [comment]
Are there plans to improve type safety for the definition in the future? The current approach is basically an even less safe way than using `as` and errors will only be visible at runtime.

Example:

```ts
type Row = { custom_field: string }
const columns: GridColDef<Row>[] = [
  {
    field: "custom_field",
    headerName: "Custom Field",
    width: 400,
    valueFormatter: (value: Date) => value.toLocaleDateString(), // ❌
  }
] 
```

**Comment by visualjerk** [comment]
Are there any plans to improve type safety for this case in the future? The current solution is basically a less safe version of casting with `as`.

Example:

```ts
type Row = { custom_field: number }
const columns: GridColDef<Row>[] = [
  {
    field: "custom_field",
    headerName: "Custom Field",
    width: 400,
    valueGetter: (value: string) => value.toUpperCase(), // ❌
  }
]
```

A userland workaround might be to add a definition helper:

```ts
// Helper
type SafeGridColDef<R extends GridValidRowModel, Key extends keyof R = keyof R, V = any, F = V> = Omit<GridColDef<R>, 'field'|'valueFormatter'|'valueGetter'> & {
  field: Key,
  valueFormatter?: GridValueFormatter<R, V, F, R[NoInfer<Key>]>;
  valueGetter?: GridValueGetter<R, V, F, R[NoInfer<Key>]>;
}

function createGridColDefFn<R extends GridValidRowModel>(): <Key extends keyof R = keyof R, V = any, F = V>(definition: SafeGridColDef<R, Key, V, F>) =>  SafeGridColDef<R, Key, V, F> {
  return (definition) => definition
}

// Usage
type Row = { custom_field: number }

const defineCol = createGridColDefFn<Row>()

const columns: GridColDef<Row>[] = [
  defineCol({
    field: 'custom_field',
    valueFormatter: (value) => value.toUpperCase(), // ✅ TS Error: Property 'toUpperCase' does not exist on type 'number'
  })
]
```
