### ISSUE TITLE
[data grid] How to implement a custom Filter Component (Modal)

### ISSUE THREAD

**Issue by Shudhanshu-Appnox** [mui/mui-x#12564]
### The problem in depth

I want to create my own custom Grid Filter Form and am currently not able to find any relatable or helpful document on it.
<img width="477" alt="Screenshot 2024-03-26 at 5 17 42 PM" src="https://github.com/mui/mui-x/assets/124690385/490597ee-474a-45e6-b4d9-265f9bdcb916">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: MUI Grid
**Order ID**: 83077

**Comment by Shudhanshu-Appnox** [comment]
Hi @zannager  can you please help me on this.

**Comment by Shudhanshu-Appnox** [comment]
Hello, @zannager will anyone reply to me on this I have to implement this.

**Comment by Shudhanshu-Appnox** [comment]
@oliviertassinari  Please help me on this as I'm not getting any active replies on this I need to implement this ASAP

**Comment by michelengelen** [comment]
Hey @Shudhanshu-Appnox I will have a look.

**Comment by michelengelen** [comment]
As far as I can see it currently is only possible when building a custom toolbar. What you basically need to do is provide a toolbar with a custom button that opens a modal where you render the `rootProps.slots.filterPanel` component.

To provide a working solution for this I need some more time though, since it is not that easy to accomplish.

@cherniavskii do you have any other idea on how to provide a custom solution?

**Comment by Shudhanshu-Appnox** [comment]
@michelengelen If possible can you share API docs for the FilterForm which I can use in my own custom component? 
For example to toggle the density of the Row we have an API called setDensity in the Grid Ref.

**Comment by michelengelen** [comment]
Hey @Shudhanshu-Appnox we do have an API overview in the docs for this component: [GridFilterForm API](https://mui.com/x/api/data-grid/grid-filter-form/)

With this you should be able to render the form (the content of the default filter panel) into your custom component

**Comment by michelengelen** [comment]
Hey @Shudhanshu-Appnox did you manage to build something or do you need some help with this?

**Comment by Shudhanshu-Appnox** [comment]
@michelengelen Hello, I was able to build the Filter but now I'm facing a strange issue when implementing the TextInput in the renderHeaderFilter. It looses focus on the first click and then on the second click it works fine. I have also checked the **Ticket** https://github.com/mui/mui-x/issues/3158. But not able to resolve the issue
