### ISSUE TITLE
[data grid] How to handle the onClose functionality of the filter panel

### ISSUE THREAD

**Issue by rajeshreddy-bheemireddy** [mui/mui-x#12575]
### The problem in depth

I am looking for a way to handle the onClose functionality of the filter panel, I do not want the filter panel to close when we click outside of the panel area, I want to close it when the user clicks on some `X` icon or on `Apply Filters` button. Attached is a screenshot of what I am trying to implement.
<img width="817" alt="filterPanelClose" src="https://github.com/mui/mui-x/assets/22893488/ee0416e5-82b1-4979-a750-81c03ca6f518">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
     Using Chrome browser.

  Output from `npx @mui/envinfo` goes here.
    System:
    OS: macOS 13.3.1
    Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    Yarn: Not Found
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
    Browsers:
    Chrome: 121.0.6167.160
    Edge: Not Found
    Safari: 16.4
    npmPackages:
    @emotion/react: ^11.9.0 => 11.11.1
    @emotion/styled: ^11.8.1 => 11.11.0
    @mui/base: 5.0.0-beta.13
    @mui/core-downloads-tracker: 5.14.7
    @mui/icons-material: ^5.8.0 => 5.14.7
    @mui/lab: ^5.0.0-alpha.83 => 5.0.0-alpha.142
    @mui/material: ^5.10.17 => 5.14.7
    @mui/private-theming: 5.14.7
    @mui/styled-engine: 5.14.7
    @mui/system: 5.14.7
    @mui/types: 7.2.4
    @mui/utils: 5.14.15
    @mui/x-data-grid: 6.17.0
    @mui/x-data-grid-premium: ^6.16.2 => 6.17.0
    @mui/x-data-grid-pro: ^6.3.0 => 6.17.0
    @mui/x-license-pro: ^6.0.4 => 6.10.2
    @types/react: ^17.0.0 => 17.0.65
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.0 => 5.3.11
    typescript: ^3.9.3 => 3.9.10

```
</details>

**Search keywords**: filter panel, onClose, onCloseFilterPanel, filter panel close
**Order ID**: 75705

**Comment by michelengelen** [comment]
Hey @rajeshreddy-bheemireddy afaik this is currently only possible if you change the props on the basePopper, which will affect all instances of it though.

As it stands now we cannot target the specific instance of it atm, right @romgrk ?

**Comment by romgrk** [comment]
No it's not possible, the click-away listener is implemented in `GridMenu.ts`. Same concerns as #12568.

**Comment by michelengelen** [comment]
In that case I will close this as a duplicate to #12568 ... Once we did clarify and rework the slots API for this (and other parts) this will naturally get resolved.

Please feel free to subscribe to that issue as we will provide a solution there once this is done! Thanks! 🙇🏼
