### ISSUE TITLE
[data grid] Adjust the width of Column Menu and filter modal of that filter option

### ISSUE THREAD

**Issue by Here2Huynh** [mui/mui-x#12570]
Duplicates
Similar to [this](https://github.com/mui/mui-x/issues/3686) but this answer seems to have changed. 
Also, have added on to this [feature request](https://github.com/mui/mui-x/issues/12446).

Latest version
I have tested the latest version. I am on "6.19.8". 

Summary 💡
I would like some help with adjusting the column menu and filter modal width so it can look better in mobile.

Examples 🌈
Currently, it looks like this. Which is not very mobile friendly.
<img width="496" alt="image" src="https://github.com/mui/mui-x/assets/36244137/f3fbed5f-325d-42e1-aec9-bc7d81b13111">

Even with the suggestion from this [ticket](https://github.com/mui/mui-x/issues/3686). The width of the popper is adjusted but not the whole modal component. Which extends to its default width as shown in the screenshot. 

<img width="617" alt="image" src="https://github.com/mui/mui-x/assets/36244137/08382be6-68c4-4c0c-aa3b-95666e0d66ea">

Code:
```tsx
<DataGridPro
  rows={[]}
  columns={columns}
  componentsProps={{
    columnMenu: {
      // sx: {
      //   backgroundColor: "orange",
      // },
    },
    basePopper: {
      sx: {
        "& .MuiPaper-root": {
          width: 100,
        },
      },
    },
  }}
/>
```

Motivation 🔦
Mobile responsiveness for data grid's option menu. 

Order ID 💳 (optional)
No response

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @Here2Huynh could you try setting the width property to `'100%'`, as simply adding `100` will use a width of 100px:

```diff
<DataGridPro
  rows={[]}
  columns={columns}
  componentsProps={{
    columnMenu: {
      // sx: {
      //   backgroundColor: "orange",
      // },
    },
    basePopper: {
      sx: {
        "& .MuiPaper-root": {
-         width: 100,
+         width: '100%',
        },
      },
    },
  }}
/>
```

**Comment by Here2Huynh** [comment]
Hi @michelengelen , tried it with `100%`. It just changes the popper's width not the over all component width.

This is easier shown in this screenshot with width at `50%`. 
<img width="447" alt="image" src="https://github.com/mui/mui-x/assets/36244137/cf799afa-ba00-4cf0-bd5b-a41f8852c356">

I think I am looking for a class name that encompasses the whole filter modal so I can select and change via CSS.
Unless possible, reorganize the layout similar to this [feature request](https://github.com/mui/mui-x/issues/12446) where it stacked as a column.

**Comment by michelengelen** [comment]
There is one way to apply custom styles to the filterPanel:

```tsx
slotProps={{
  filterPanel: {
    sx: {
      backgroundColor: 'rgba(0, 0, 0, 0.1)',
      padding: '5px',
      borderRadius: '4px',
    },
  },
}}
```

The filterPanel can take an `sx` prop as well, so you can easily style it that way and target any child classes there.

You can also target specific elements within with the `gridClasses` object that you can import from the datagrid package:

```tsx
import { gridClasses } from '@mui/x-data-grid';
...
<DataGrid
  ...
  slotProps={{
    filterPanel: {
      sx: {
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
        padding: '5px',
        borderRadius: '4px',

        [`& .${gridClasses.filterForm}`]: {
          backgroundColor: 'rgba(0, 0, 0, 0.1)',
          padding: '5px',
          borderRadius: '4px',
        },
      },
    },
  }}
/>
```

There are multiple classes that ca be used from that object.

Does that help in your case?

**Comment by Here2Huynh** [comment]
Ah, it's the `filterPanel` that I am looking for! Thanks, was able to get it working for me!
