### ISSUE TITLE
[Missing v7 artifact in npm] 

### ISSUE THREAD

**Issue by conbrad** [mui/mui-x#12580]
### The problem in depth

Error: Can't resolve '@mui/x-license-pro' and https://www.npmjs.com/package/@mui/x-license-pro?activeTab=versions doesn't show a v7 stable version published.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.59
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ^11.8.2 => 11.11.4
    @emotion/styled: ^11.8.1 => 11.11.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.14
    @mui/icons-material: ^5.5.1 => 5.15.14
    @mui/material: 5.15.14 => 5.15.14
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.14
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid:  7.0.0
    @mui/x-data-grid-pro: ^7.0.0 => 7.0.0
    @mui/x-date-pickers: ^7.0.0 => 7.0.0
    @mui/x-license:  7.0.0
    @types/react: 18.2.71 => 18.2.71
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.0.0 => 5.4.3
</details>

**Search keywords**: mui v7, v7
**Order ID**: 86019

**Comment by flaviendelangle** [comment]
:grimacing: That one is a big fail on our side @DanailH @joserodolfofreitas ...

@conbrad indeed our release script did not release the `x-license-pro` package and we did not catch the problem.
It will be released tomorrow or on Friday for the `7.0.1` release :+1:

**Comment by flaviendelangle** [comment]
@conbrad the package has been renamed `@mui/x-license` (to be coherent with `@mui/x-data-grid-premium`)

You can find more information on the [migration guide](https://mui.com/x/migration/migration-data-grid-v6/#update-the-license-package)

**Comment by LukasTy** [comment]
@conbrad how did you encounter the error you mentioned in the issue?
Do you have the `@mui/x-license-pro` package listed in your dependencies?
If this is the case, please rename the package, as Flavien mentioned.
And if it is, do you have a particular reason to list it yourself? Is your package manager complaining otherwise? 🤔

**Comment by flaviendelangle** [comment]
> And if it is, do you have a particular reason to list it yourself? Is your package manager complaining otherwise? 

Since we recommend people to import the license setter from `@mui/x-license-pro`, some bundler complain if you try to import a transitive dep.

**Comment by conbrad** [comment]
> @conbrad how did you encounter the error you mentioned in the issue? Do you have the `@mui/x-license-pro` package listed in your dependencies? If this is the case, please rename the package, as Flavien mentioned. And if it is, do you have a particular reason to list it yourself? Is your package manager complaining otherwise? 🤔

Hey, this worked thanks!
