### ISSUE TITLE
[data grid] Column definition flex doesn't work correctly with pinned columns

### ISSUE THREAD

**Issue by paulsukow** [mui/mui-x#12584]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-zdguze-gvcjve?file=Demo.tsx

Steps:
1. Set a column to have a flex value of 1 in the column def
2. With no columns pinned, the flex column will expand to fill the remaining width in the grid
3. Pin a column to the left side
4. The flex column will no longer expand to fill the remaining width. A div element with the class `MuiDataGrid-filler` will be present on the right side.

### Current behavior

With a column pinned and another column with a flex value, then flex column doesn't expand to fill the grid width. Instead a filler div element is present

### Expected behavior

With a column pinned and another column with a flex value, then flex column should expand to fill the grid width. 

### Context

The seems to be a regression in 7x. Version 6x worked fine.

In the following screen shot, the green column is pinned, the blue column has a flex value of 1, and the red column is the added div.

<img width="702" alt="image" src="https://github.com/mui/mui-x/assets/21179028/9799c2f7-6edd-46ec-ac32-9c231baabc81">

Here is the same grid with no columns pinned. The blue column now expands to fill the width
<img width="667" alt="image" src="https://github.com/mui/mui-x/assets/21179028/5dbddaf3-7817-42fc-99b7-6b543ec7d4a5">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: flex, pinned columns, autosizing

**Comment by michelengelen** [comment]
This seems like a regression that came from #10059. Do you know if thats correct @romgrk?

**Comment by michelengelen** [comment]
@paulsukow thanks for raising this. I have added it to our board to check it!

**Comment by romgrk** [comment]
Don't know where it came from. Can reproduce.

**Comment by cstephens-cni** [comment]
> For grouped and pinned cols I get a "Maximum update depth exceeded" when using a groupingColumnDef. If I remove the flex:1 no issues.

Just did a quick test the pinning may have nothing to do with it, not sure if others are having this issue.  I'm still exploring it.  It took me a bit to track down the issue to the flex setting.  I'm finding this during a migration from v6.

**Comment by beaktor** [comment]
I'm seeing the same issue @cstephens-cni. I have a DataGrid with a pinned column and using `flex` on that column (and other non-pinned columns). With the combination of the 2, I get a "Maximum update depth exceeded." I don't get that if I take out the `flex` or comment out the `initialState: { pinnedColumns: {...} }` definition.

**Comment by cstephens-cni** [comment]
@beaktor I was able to confirm using a simple MUIX grid that the combination alone is not why this is happening.  I have been unable to reproduce outside of my software stack.  I am basically ripping up my app to track down what the combination is.   I am using a wrapper around the MUIX Grid that was initially intended to abstract it so I could swap in another grid if we wanted to. So I have some increased complexity in my case.   I'm removing as much complexity as possible to track down a simple example to post.   If anyone is able to beat me to it, please do so.

**Comment by cstephens-cni** [comment]
oh also my issue I'm seeing I don't know if it's the same as the original ticket so we can split this off if it's a seperate (maybe related) thing.

**Comment by beaktor** [comment]
@cstephens-cni Interesting, we too have an abstraction component that sets a few options in a container. I started stripping out everything, but still in our environment. Bare minimum with a fixed-size DataGrid, just 1 column (with `flex: <number>`, no custom `renderCell`),  and the `pinnedColumns` initial state and I see the infinite loop.

This blows up if I add `flex: 1` to the column definition:
![image](https://github.com/mui/mui-x/assets/5374614/71ba73b2-8ac5-4a92-adbf-27fa299cb740)

![image](https://github.com/mui/mui-x/assets/5374614/d399cc8e-5a15-43e9-b3f5-603e8bcaffbb)
![image](https://github.com/mui/mui-x/assets/5374614/d7c4cda2-17c9-422f-bfe2-651fd1ef815b)

(Or if I leave `flex: 1` in and take out the `pinnedColumns` it's okay.)

If indeed this is a separate issue from OP, we can split this off. I see this in `17.2.0` and not in `6.19.5`.

**Comment by cstephens-cni** [comment]
@beaktor Created a new ticket for what we discussed.  Take a look and add any information you have.
