### ISSUE TITLE
[data grid] How can I prevent data grid rows from formatting on hover when the grid contains pinned columns?

### ISSUE THREAD

**Issue by benosmond** [mui/mui-x#12581]
### The problem in depth

I want to completely remove the hover styles from the premium data grid, which by default has a highlight on rows when they are hovered over. I've managed to achieve this by applying a `backgroundColor: 'inherit'` targeting `MuiDataGrid-row:hover`.

The problem I'm having is that the hover styles are still applied to cells that are part of a pinned column, and I am not sure why this is.

I've reproduced the issue in the below StackBlitz demo:
https://stackblitz.com/edit/react-3b1tdv?file=Demo.tsx

It's based directly on one of the MUI pinned columns demos.

My assumption is that there are different classes that apply to pinned columns, but any help figuring out what selectors to use to get the row highlight completely removed would be much appreciated.

**Search keywords**: hover, row, pinned column
**Order ID**: 82553

**Comment by michelengelen** [comment]
Hey @benosmond it is a bit clunky, but this would be the way to go for now:

```tsx
<DataGridPro
  sx={{
    [`& .${gridClasses.virtualScrollerContent} .${gridClasses.row}:hover`]: {
      [`.${gridClasses['cell--pinnedLeft']}, .${gridClasses['cell--pinnedRight']}`]: {
        backgroundColor: 'inherit',
      },
    },
    [`& .${gridClasses.row}:hover`]: {
      backgroundColor: 'inherit',
    },
  }}
  rows={rows}
  columns={columns}
  initialState={{ pinnedColumns: { left: ['name'], right: ['actions'] } }}
/>
```

Would that help you?

**Comment by benosmond** [comment]
@michelengelen not sure if something has changed with version 7, but I don't have `gridClasses[cell--pinnedLeft]`. I have stuff like `gridClasses['pinnedColumns--left']` though?

**Comment by michelengelen** [comment]
> @michelengelen not sure if something has changed with version 7, but I don't have `gridClasses[cell--pinnedLeft]`. I have stuff like `gridClasses['pinnedColumns--left']` though?

Not sure tbh ... I don't think they actually changed. Did you try using `gridClasses['cell--pinnedLeft']`?

> This did however, help me find a solution that works... rather than targeting `${gridClasses.row}:hover`, I selected `${gridClasses.row}.Mui-hovered` and added `backgroundColor: 'inherit'`... it works and there's no hover styles being applied whatsover now.

Great that you found a solution to your problem. I will go ahead and close this issue for that reason. Feel free to re-open if you encounter other issues, or simply open a new one! 👍🏼

**Comment by benosmond** [comment]
> Not sure tbh ... I don't think they actually changed. Did you try using `gridClasses['cell--pinnedLeft']`?

I did, and it gave me a TypeScript error saying that the property wasn't on the object. Potentially just TypeScript getting confused, but I tried dismissing the error by casting `'cell--pinnedLeft'` as a key of `gridClasses`, and it still didn't work. 

> Great that you found a solution to your problem. I will go ahead and close this issue for that reason. Feel free to re-open if you encounter other issues, or simply open a new one! 👍🏼

Thanks :) happy to close it, since this helped me find a solution to the issue.
