### ISSUE TITLE
[question] Annoying `MUI License Expired` watermark when support expires

### ISSUE THREAD

**Issue by sereyn** [mui/mui-x#12594]
### The problem in depth

I bought a lifetime license and I understand support and updates are limited in time, for my case it was:
```
Support and updates expiry date: Fri Feb 24 2023
```
The issue is the annoying watermark in the data-grid, only showing in development environment, it is not a good developer experience. Any way to make it disappear?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.1.1
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 8.19.4 - ~/Documents/code/qanswer-bundle/qanswer-ui/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.87
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @emotion/react: ^11.6.0 => 11.11.1 
    @emotion/styled: ^11.6.0 => 11.11.0 
    @mui/base:  5.0.0-beta.16 
    @mui/core-downloads-tracker:  5.14.10 
    @mui/icons-material: ^5.10.9 => 5.14.9 
    @mui/lab: ^5.0.0-alpha.105 => 5.0.0-alpha.145 
    @mui/material: 5.10.11 => 5.10.11 
    @mui/private-theming:  5.14.10 
    @mui/styled-engine:  5.14.10 
    @mui/system:  5.14.10 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.10 
    @mui/x-data-grid:  5.17.26 
    @mui/x-data-grid-pro: 5.17.26 => 5.17.26 
    @mui/x-license-pro:  5.17.12 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react: ^18.0.15 => 18.2.22 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.2.4 => 4.9.5
```
</details>

**Search keywords**: license expired watermark support
**Order ID**: 38422

**Comment by flaviendelangle** [comment]
Hi, the watermark should only be displayed if you are using a version of the software that is not supported by your license:

![image](https://github.com/mui/mui-x/assets/3309670/0cce4bfa-ec2f-497f-b19b-47796e3d23a8)

If you want to remove the watermark, you can either update your license with one that do support the version that you are using, or change the version for 5.17.25 which is the last version your license supports:

![image](https://github.com/mui/mui-x/assets/3309670/3a2e2a27-381e-4e10-a9cb-e38dc2258ad1)


I hope this answers your question
