### ISSUE TITLE
[charts] Highlighting not working in Scatter series with `number` ID

### ISSUE THREAD

**Issue by marvinruder** [mui/mui-x#12603]
### Steps to reproduce

Steps:
1. Fork the “Basics” example from https://mui.com/x/react-charts/scatter/#basics.
2. Add a `number` id to both series, like:

```ts
      series={[
        {
          id: 100,
          label: 'Series A',
          data: data.map((v) => ({ x: v.x1, y: v.y1, id: v.id })),
        },
        {
          id: 101,
          label: 'Series B',
          data: data.map((v) => ({ x: v.x2, y: v.y2, id: v.id })),
        },
      ]}
```

3. Hover over chart.

### Current behavior

All data points are faded. No data points are highlighted.

### Expected behavior

All data points are faded. The data point being hovered over is highlighted.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.6 Alpine Linux
  Binaries:
    Node: 21.7.1 - /usr/local/bin/node
  Browsers:
    Safari 17.4 (19618.1.15.11.12) on macOS 14.4 (build 23E214)
```
</details>

**Search keywords**: charts, highlighting, scatter

**Comment by marvinruder** [comment]
The issue appears to be in https://github.com/mui/mui-x/blob/7e2d2ece8ff55fc9f2c18c801268e36f3ddd4783/packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx#L112 where `Object.keys()` returns an array of strings even if the keys are `number`s.

**Comment by michelengelen** [comment]
Thanks for reporting this @marvinruder.
As you might have seen @alexfauquette did already add this to our board! 👍🏼
