### ISSUE TITLE
[data grid] Remove Empty String Option in MUI DataGrid SingleSelect Filter

### ISSUE THREAD

**Issue by hamzasial1911** [mui/mui-x#12611]
### Summary

The current implementation of the MUI DataGrid SingleSelect filter includes an empty string option alongside values, which may not align with user expectations. This enhancement aims to remove the empty value from the filter dropdown and empower users to manually add custom values for a more tailored filtering experience.

### Examples

<img width="504" alt="Screenshot 2024-03-28 at 9 45 36 AM" src="https://github.com/mui/material-ui/assets/80591014/fcbdd5bd-bf85-4e8f-b1fa-b89a5a301b76">

_**Current:**_
I am getting this empty value even after giving the: `optionalValues: ["Open","PartiallyFilled","Filled", "Rejected"]`

_**Expected**_ 
I dont want to see the empty value in the dropdown.

### Motivation

- Improve user experience by eliminating the empty string option in the SingleSelect filter.

- Enable users to manually add custom values, enhancing the filter's customization capabilities.

- Streamline the filtering interface by focusing on user-driven input without the distraction of an empty value.

**Search keywords**:

**Comment by michelengelen** [comment]
@mui/xgrid do we support this through some filter customization? I did try using `requiresFilterValue` on the FilterOperator, but that did not work.

**Comment by MBilalShafi** [comment]
Hi @hamzasial1911!

The purpose of the empty value is to allow the users to be able to clear the value from the dropdown.

You can change the behavior by customizing the component used as the `InputComponent` in the respective `colDef.filterOperators` entry.
I tried to do this in this example for the status column: https://stackblitz.com/edit/react-97fkmt

Let me know if this is what you are looking for.

**Comment by hamzasial1911** [comment]
@MBilalShafi Great work! This is exactly what I want.
