### ISSUE TITLE
[data grid} how to select all visible rows on a page

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#12625]
### Summary

I am reaching out to inquire about the possibility of implementing a Gmail-like functionality in Data Grid Pro to better align with my specific scenario. Currently, when working with a sizable dataset such as 500 records with a page size of 100, utilizing the select all feature across pagination selects all 500 records at once. However, this behavior does not fully meet my requirements.

Ideally, I would like the select all feature to function similarly to Gmail's functionality. Specifically, I envision that clicking on select all would only select the rows visible on the current page. Additionally, a prompt will be displayed, asking users if they wish to select all remaining rows beyond the current page.
![image (1)](https://github.com/mui/mui-x/assets/115474187/78bbd895-73f2-4869-b504-034177bbdbcc)

### Examples

![image (1)](https://github.com/mui/mui-x/assets/115474187/b5094351-ffdf-40f6-95c2-de7067142eba)

**Search keywords**: Gmail, Like, Functionality, Data, Grid, Pro
**Order ID**: 81584

**Comment by michelengelen** [comment]
Hey @mahammahmood .... as of now this is not easily done.
I do not think that there is a way to get the currently visible rows from the grid API.
Let me ask the team about this.

**Comment by cherniavskii** [comment]
Hi @mahammahmood 
I think it is possible thanks to the [`checkboxSelectionVisibleOnly`](https://mui.com/x/api/data-grid/data-grid-premium/#data-grid-premium-prop-checkboxSelectionVisibleOnly) prop.
Here is a working demo: https://stackblitz.com/edit/react-pjsler?file=Demo.tsx
Is this what you're looking for?

**Comment by mahammahmood** [comment]
This does indeed accomplish my goal. Thank you very much.
