### ISSUE TITLE
[data grid] Selection and filtering do not work together

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#12626]
### Summary

I am reaching out to inquire about a specific scenario regarding the selection behavior in Data Grid Pro. I have encountered an issue related to row selection and filtering functionality
![Screenshot (4)](https://github.com/mui/mui-x/assets/115474187/0c05a842-ede1-46b3-9101-ef0718cb9537)
![Screenshot (5)](https://github.com/mui/mui-x/assets/115474187/38eca3e7-897a-4d0f-be3b-79df424ee350)
.

Currently, when I select rows in Data Grid Pro and subsequently apply a filter to my dataset, the selection behavior seems to be affected. For example, if I initially select 2 rows and then apply a filter to the dataset, followed by selecting an additional 3 rows from the filtered results, the total number of selected rows is correctly calculated as 5.

However, upon clicking on the "Show Selected Rows" button, I expect to see all 5 selected rows, including those selected before and after applying the filter. However, the grid only displays the rows that were selected after the filter was applied, omitting the previously selected rows.

I would like to inquire if there is a way to modify the selection behavior to include all selected rows, regardless of whether they were selected before or after applying a filter. Essentially, I am seeking a solution that displays all selected rows when the "Show Selected Rows" button is clicked, regardless of any applied filters.

### Examples

![Screenshot (4)](https://github.com/mui/mui-x/assets/115474187/2e842a48-fd59-4330-b908-d8eb7ac1c0de)
![Screenshot (5)](https://github.com/mui/mui-x/assets/115474187/0d8a95d3-684f-427b-8b1d-a8b16838349a)

**Search keywords**: Data ,Grid , Pro,  Selection, Behavior
**Order ID**: 81584

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
