### ISSUE TITLE
Allow a DataGrid row to be wrapped in a Link

### ISSUE THREAD

**Issue by isaacna** [mui/mui-x#12621]
### Summary

Currently there doesn't seem to be an easy way to wrap an entire row in a `DataGrid` in a `Link`. You could use `onRowClick` + `useNavigate`, but that misses out on some of the behavior that a `Link` gives such as being able to open in new tab, cursor indications on hover, etc. I've also tried wrapping the individual cells in `Link`s, but this doesn't fill up the whole row space in the same way that using `onRowClick` does 

**Search keywords**: onRowClick

**Comment by michelengelen** [comment]
Hey @isaacna you can just wrap the default row with an `a` tag in the slots:

```
slots={{
  row: (params: GridSlotProps['row']) => (
    <a href={'https:mui.com'} target={'_blank'}>
      <GridRow {...params} />
    </a>
  ),
}}
```

But that will add some styling as well that you need to take care of as well.
Additionally it might impact rendering performance.
