### ISSUE TITLE
[data grid] QuickFilter is not filtering from master details

### ISSUE THREAD

**Issue by DTanmoy** [mui/mui-x#12620]
### Steps to reproduce

Link to live example: [Demo](https://codesandbox.io/p/sandbox/loving-nightingale-63chzp?file=%2Fsrc%2FDemo.tsx)

![Screenshot 2024-03-30 212227](https://github.com/mui/mui-x/assets/26085298/7c35e38e-7eb6-4a1c-be26-9d859b8a5484)

### Current behavior

![Screenshot 2024-03-30 212018](https://github.com/mui/mui-x/assets/26085298/3a4536e3-51c9-48ce-adfd-e4af119878f8)

### Context

The quick filter should filter from master table. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: QuickFilter, GridToolbar, GridToolbarQuickFilter

**Comment by DTanmoy** [comment]
Demo: https://codesandbox.io/p/sandbox/loving-nightingale-63chzp?file=%2Fsrc%2FDemo.tsx

**Comment by michelengelen** [comment]
Yes, that's intentional behaviour, since the filter does only search in row data and the master detail is an additional content block. which can vary based on rendering conditions.

**Comment by DTanmoy** [comment]
> Yes, that's intentional behaviour, since the filter does only search in row data and the master detail is an additional content block. which can vary based on rendering conditions.

Hi Thanks for the reply, could you hint me how to achieve this then ?

**Comment by michelengelen** [comment]
AFAIK this is not possible at all, since the detail panel is rendered on demand and the content is not saved somewhere, contrary to the rows, that are constantly held in the internal state.
With the state we can easily perform filtering algorithms, but this is simply not possible for the details I am afraid.

**Comment by DTanmoy** [comment]
> AFAIK this is not possible at all, since the detail panel is rendered on demand and the content is not saved somewhere, contrary to the rows, that are constantly held in the internal state. With the state we can easily perform filtering algorithms, but this is simply not possible for the details I am afraid.

Okay, Is there any chance to have this feature in upcoming releases?

**Comment by DTanmoy** [comment]
> as mentioned before this might prove to be impossible to do, since this would involve rendering every detail on every change in filtering. I can forward this to the team to see if someone has an idea, but I wouldn't expect a solution for this TBH

Okay sure, thanks for your input’s 🙂

**Comment by cherniavskii** [comment]
@DTanmoy As a workaround, you can add a hidden column with the stringified value of all the fields you want to be searchable.
Not sure how well it would scale in your case, but here's a working demo: https://stackblitz.com/edit/react-rkxf2t?file=Demo.tsx
What do you think?
