### ISSUE TITLE
[pickers][DatePicker] Toggle date selection when same date is clicked

### ISSUE THREAD

**Issue by ReaganS94** [mui/mui-x#12631]
### Summary

I am currently utilizing the StaticDatePicker component to create an interface where users can select and highlight multiple dates. However, I've encountered a limitation with the onChange event handler; it does not trigger when the same date is clicked consecutively. This behavior limits the ability to toggle a date's selection without first selecting a different date.

### Current Behavior:

When a user selects a date, it becomes highlighted. However, if the user clicks the same date again with the intention of deselecting it, the onChange event does not fire, and thus the date remains selected. To deselect, one has to choose a different date before toggling the original one.

### Desired Feature:

It would be highly beneficial for the StaticDatePicker to have an enhanced toggle functionality. Specifically, when a date is clicked, if it's already selected, a subsequent click should deselect it, ideally triggering the onChange event with a null value or similar indicator.

### Suggested Implementation:

Ideally, the onChange handler could be enhanced to detect a click on the currently selected date and respond by clearing that selection. This could be an optional behavior controlled by a prop, maintaining backward compatibility for users who rely on the current behavior.

### Motivation

This feature would significantly improve the user experience in scenarios where users need to select multiple non-consecutive dates and might change their selections frequently. It would allow for a more intuitive interaction pattern, akin to how users commonly expect toggleable options to behave.

**Search keywords**: StaticDatePicker, DatePicker, Date

**Comment by michelengelen** [comment]
Technically this would be possible when providing a function to the `onClick` method on the `day` slot:

```tsx
<StaticDatePicker
  defaultValue={dayjs('2022-04-17')}
  onChange={(...params) => console.log('change', params)}
  slotProps={{
    day: {
      onClick: (...params) => console.log('day click', params),
    },
  }}
/>
```

Although this feels a bit clunky tbh.
@LukasTy should we keep this on the board for discussion purposes?

**Comment by LukasTy** [comment]
@michelengelen your suggestion will hardly help, because the `onClick` callback does not receive anything to easily identify the clicked day.
We can indeed add this issue to the board and discuss possible solutions.

I see a couple of possible options:
- fire on change even when the changed value is equal to the previously selected (that's a BC) and let the user handle it on their end - if they want to toggle the value, they'd need to control the value and compare it with previously selected;
- add a prop (as suggested) to fire on change with the "same" (when value equals previously selected) value;

**Comment by LukasTy** [comment]
@ReaganS94 We discussed this topic a bit more and are proposing the usage of the suggested `slotProps.day.onClick` approach to handle this use case.
We would not want such behavior to be a default, given that it is not a standardly observed behavior, that might not be desired especially from `a11y` perspective.
[Here is](https://stackblitz.com/edit/react-4nwcla-tbp2ck?file=Demo.tsx) an updated demo using the available `data-timestamp` property to achieve a toggling behavior.
What do you think about it? Would it cover your usage cases?

All the other approaches have a much bigger impact and would require a flag to control it to reduce the impact. 🤔

**Comment by AgrYpn1a** [comment]
@LukasTy Hey thanks for taking time to handle this. While I no longer work on the project where this is needed, I believe this will be perfect for them and will let them know that this is handled. Thank you!

**Comment by shrinathaithal** [comment]
Based on your suggestion, if I trigger my `onClick` method on `slotProps.day.onClick`, is it a crime? 🤔 

```js
<MobileDatePicker
  onChange={handleChange}
  slotProps={{
    day: {
      onClick: (e) => {
        const clickedDay = e.target;
        handleChange(moment.unix(clickedDay.dataset.timestamp / 1000));
      },
    },
  }}
  {...pickerProps}
  {...styleProps}
/>
```

Recommended? Any holes I should be aware of?

**Comment by LukasTy** [comment]
> Recommended? Any holes I should be aware of?

@shrinathaithal What is your exact use case?
Given your example, I'd be worried about calling `handleChange` twice. 🤔

**Comment by shrinathaithal** [comment]
> @shrinathaithal What is your exact use case? Given your example, I'd be worried about calling `handleChange` twice. 🤔

Multi Date Picker. 
I have a Stackblitz for you if you got time. Ignore the noise, I know there's room (or entire house) for improvement 😆  

https://stackblitz.com/edit/react-vsaayg?file=src%2FApp.js,src%2FMultiDatePicker%2Findex.js

**Comment by LukasTy** [comment]
> Multi Date Picker. I have a Stackblitz for you if you got time. Ignore the noise, I know there's room (or entire house) for improvement 😆
> 
> https://stackblitz.com/edit/react-vsaayg?file=src%2FApp.js,src%2FMultiDatePicker%2Findex.js

Oh, that is some heavy modification. 😱 
Given that use case, I'd say that it is relatively safe to rely on it.
We try to never have any breaking DOM changes without a major release.
Just be aware that you are relying on DOM attributes for your data correctness and they can be tampered with—anyone can remove or change the `data-timestamp` to create an array of selected days they want.
Given this information, it is paramount that you have backend validation checking the validity of selection if that is important.
