### ISSUE TITLE
[data grid] Export to Excel and CSV only displayed Data (filtered and sorted)

### ISSUE THREAD

**Issue by Aberkati** [mui/mui-x#12634]
### The problem in depth

I want to be able to export in Excel and/or CSV only displayed Data, for example if I make a filter for 'Head of Engineering' and I get only the rows with this keywords, I want to be able to export results only, not all my data.

I've looked on the documentation but I didn't found a solution for my case..
thank you!

### Your environment

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD    
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (122.0.2365.106)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.4
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.14
    @mui/icons-material: ^5.11.16 => 5.15.14        
    @mui/material: ^5.12.1 => 5.15.14
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.14
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid:  6.19.8
    @mui/x-data-grid-premium: ^6.10.0 => 6.19.8
    @mui/x-data-grid-pro:  6.19.8
    @mui/x-license-pro: ^6.10.0 => 6.10.2
    @types/react:  18.2.72
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0

**Search keywords**: DataGridPremium
**Order ID**: 66242

**Comment by michelengelen** [comment]
This does work with the excel import as we have them on the docs!

Just as an example:
1. Use this [export demo](https://mui.com/x/react-data-grid/export/#excel-export)
2. filter `Job title` contains `'Head'`
3. get filtered results
4. export to CSV resulst in this:

```csv
Job Title,Recruitment Date,Contract Type
Head of Human Resources,12/09/2020,full time
Head of Sales,04/04/2017,full time
Head of Engineering,14/04/2016,full time
```

Excel does work accordingly.
Could you please re-check if your implementation is correct or support us with a working demo? Thanks!
