### ISSUE TITLE
[charts] Improve `sx` documentation

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#12633]
Feedback received:
`Chart components accept the sx props. From here, you can target any subcomponents with its class name.`
how?

from https://mui.com/x/react-charts/styling/#

**Search keywords**:

**Comment by derek-0000** [comment]
**Wondered If I can get this assigned? I started working on an example and wanted to know:**

- How many examples may it be enough to demonstrate the usage of `sx` for styling? 

I kinda feel that one may be enough. But wanted to make sure.

**Current wip:**

![image](https://github.com/mui/mui-x/assets/81263819/19ada192-f292-46a9-b0f2-3c8d0a0ea92f)

```JSX
import * as React from 'react';
import { BarChart } from '@mui/x-charts/BarChart';

export default function SxStylingTemplate() {
  return (
    <BarChart
      sx={{
        '& .MuiBarElement-root': {
          rx: 100,
          ry: 15,
          opacity: 0.5,
          fill: '#000000',
          stroke: '#00DD43',
        },
        '& .MuiChartsAxis-root': {
          '& .MuiChartsAxis-line': {
            stroke: '#FFDD43',
          },
        },
        '& .MuiChartsAxis-directionY > *:nth-child(2)': {
          stroke: 'red',
        },
        '& .MuiChartsAxis-directionY > *:nth-child(3)': {
          stroke: 'yellow',
        },
        '& .MuiChartsAxis-directionY > *:nth-child(4)': {
          stroke: 'yellow',
        },
        '& .MuiChartsAxis-directionY > *:nth-child(5)': {
          stroke: 'green',
        },
      }}
      xAxis={[{ scaleType: 'band', data: ['group A', 'group B', 'group C'] }]}
      series={[{ data: [4, 3, 5] }, { data: [1, 6, 3] }, { data: [2, 5, 6] }]}
      width={500}
      height={300}
    />
  );
}
```

**Comment by alexfauquette** [comment]
Yes, one demo might be enough

If you want to do it, consider using the class objects to generate the selectors. For example ``[`.${axisClasses.left} .${axisClasses.label}`]`` like in this example: https://mui.com/x/react-charts/axis/#fixing-overflow-issues

 I might rework some demo to use them instead of the hardcoded string such that `".MuiLineElement-root"`

**Comment by derek-0000** [comment]
Sure thing!
