### ISSUE TITLE
DesktopDatePickerProps<Date> error Type 'Date' does not satisfy the constraint 'never' in version 7.1.0

### ISSUE THREAD

**Issue by andylacko** [mui/mui-x#12640]
### Steps to reproduce

Link to live example: this doesn't need repro, it is bad implementation of typescript
Steps:
1. `DesktopDatePickerProps<Date>`
2. pickers.d.ts
<img width="893" alt="image" src="https://github.com/mui/mui-x/assets/7139923/c863b86c-aed8-428d-8bab-2cc98b89ec48">

### Current behavior

doesn't accept Date or any type except never

### Expected behavior

To accept javascript Date class as type

### Context

typescript

### Your environment

```
  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 21.7.1 - ~/Library/Caches/fnm_multishells/1738_1711985104552/bin/node
    npm: 10.5.0 - ~/Library/Caches/fnm_multishells/1738_1711985104552/bin/npm
    pnpm: 8.15.0 - ~/node_modules/.bin/pnpm
  Browsers:
    Chrome: 123.0.6312.87
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^5.4.3 => 5.4.3 
```

**Search keywords**: Type 'Date' does not satisfy the constraint 'never'

**Comment by CWThomson** [comment]
I'm also seeing the same issue. I simply took the Joy UI sample code for the date range picker ([JoyUI Sample Code](https://mui.com/x/react-date-pickers/custom-field/#system-JoyV6MultiInputRangeField.tsx)). I changed the date provider to be date-fns and used pro version (@mui/x-date-pickers-pro). 

As I was trying to create a standalone component I removed the wrapper components for JoyV6MultiInputRangeField as this is done elsewhere. 

I then removed the unused imports and the issue started appearing. By leaving the following unused import in the code, the issue goes away. If you remove it, the issue appears

`import { AdapterDateFns } from '@mui/x-date-pickers-pro/AdapterDateFnsV3';`

[Sample code](https://gist.github.com/CWThomson/96ff40cdb3412e7f79f7c3e3acfc421d)

**Comment by LukasTy** [comment]
> I then removed the unused imports and the issue started appearing. By leaving the following unused import in the code, the issue goes away. If you remove it, the issue appears

Which adapter and where are you using in your application?
Importing an adapter anywhere in your application will augment the declared module with relevant interface entry and make TS happy with the provided `Date` type.

TL/DR: I don't see a problem here, everything seems to work as expected. 👌 

Are you by any chance building a component library and there is no place where a `LocalizationProvider` with the appropriate `dateAdapter` is defined? 🤔

**Comment by CWThomson** [comment]
Thanks @LukasTy . I am building a component library and using tsup. Its in the build process this fails (Storybook works fine). Your explanation makes perfect sense. Storybook does initialize a LocalizationProvider with the AdapterDateFnsV3 adapter. As a component library, we leave the downstream app to be responsible for initializing the LocalizationProvider. Thanks for your help!

**Comment by LukasTy** [comment]
@CWThomson does your library only support `Date` (date-fns) only?
Otherwise, it would probably make sense to keep the generics on your side as well. 🤔 
If you specifically need TS to work with specific types, without using an adapter, maybe you could just declare the specific module yourself? 🤔 

https://github.com/mui/mui-x/blob/b7848b46fcde4d2473e93744b4c905c24b2a84fd/packages/x-date-pickers/src/AdapterDateFnsBase/AdapterDateFnsBase.ts#L121-L125

**Comment by CWThomson** [comment]
Our component library is for internal use only so we've standardized on date-fns. Thanks for the tips, may be a better approach to main flexibility.

**Comment by guicara** [comment]
I'm also seeing the same issue.

With MUI X v7 and date-fns

`TS2344: Type Date does not satisfy the constraint never`

Here is the code of my custom component, extending the default `DatePicker`:

```ts
export interface CustomDatePickerProps<
  TDate extends PickerValidDate,
  TEnableAccessibleFieldDOMStructure extends boolean = false,
> extends DatePickerProps<TDate, TEnableAccessibleFieldDOMStructure> {
  // custom properties here...
}
```

```tsx
function CustomDatePicker<TDate extends PickerValidDate, TEnableAccessibleFieldDOMStructure extends boolean = false>(
  props: CustomDatePickerProps<TDate, TEnableAccessibleFieldDOMStructure>,
) {
  return <DatePicker {...props} />
}
```

Usage:
```tsx
<CustomDatePicker<Date> // --> TS2344: Type Date does not satisfy the constraint never
  value={new Date()}
/>
```

**Comment by LukasTy** [comment]
@guicara I tried reproducing your problem, but wasn't able to trigger the mentioned error if `AdapterDateFns` or `AdapterDateFnsV3` is imported anywhere in the app. 🤷 
Could you provide a minimal reproduction case (a GH repo or StackBlitz demo) for us to explore?

A minor nitpick regarding your wrapped component types:
Are you building a component library?
Do you plan to have multiple date libraries/adapters used?
Do you plan to use Pickers with both the regular input as well as the [accessible DOM structure](https://mui.com/x/react-date-pickers/fields/#accessible-dom-structure)?
If not, consider statically defining your wrapped component interface:
```ts
export interface CustomDatePickerProps extends DatePickerProps<Date, false> {
  // custom properties here...
}
```

**Comment by flaviendelangle** [comment]
> It was working well before with MUI X v6, without this fix.

In v6, the type of the date was inferred from the props;
This mean that TypeScript was able to complain for the following code:

```tsx
// Invalid because `value` and `onChange` should have the same typing
<LocalizationProvider dateAdapter={AdapterDayjs]>
  <DatePicker value={new Date()} onChange={(date: Dayjs) => {}} />
</LocalizationProvider>
```

But it was not able to complain for the following code:

```tsx
// `value` and `onChange` are coherent, but they are not compatible with `AdapterDayjs`
<LocalizationProvider dateAdapter={AdapterDayjs]>
  <DatePicker value={new Date()} onChange={(date: Date) => {}} />
</LocalizationProvider>
```

Our solution was to limit the valid types for the date to the one supported by the adapter(s) you imported.

____

In your example, you are using `AdapterDateFns`, so the valid date is `Date`.

It seems that you are importing it outside of the typescript project used to check the file that throws an error.
Without more information it is hard to know why, this is probably related to how you application is structure and TS configured (and it can be configured that way for very good reasons).

You should be able to get rid of the error by adding a `import type {} from '@mui/x-date-pickers/AdapterDateFns'` to a file at the root of your application (`_app` on `Next.js` for example).

An even cleaner solution would be to add `"./node_modules/@mui/x-date-pickers/AdapterDateFns/index.d.ts"` to your `tsconfig.json` file, but this only works if you did not exclude all the `node_modules` (which is the case on `Next.js` and maybe in other frameworks...).

____

@LukasTy I do agree that a section in the migration guide would be a nice addition

**Comment by guicara** [comment]
Thank you for your help and replies.

The issue was on my side due to a wird dependencies issues between the app consuming the design system and the design system itself.

> Are you building a component library?

Yes

> Do you plan to have multiple date libraries/adapters used?

Yes

**Comment by fcpauldiaz** [comment]
@guicara I'm having the same issue, how did you fixed it?

**Comment by LukasTy** [comment]
I've moved the issue to our grooming board as we've agreed that adding a migration doc section about this would be beneficial.
@fcpauldiaz Have you read the whole discussion? I think that especially this comment: https://github.com/mui/mui-x/issues/12640#issuecomment-2039434173 should answer most of your questions.
If you are still experiencing issues, could you provide a minimal reproduction example or at least describe your setup in more detail? 🤔

**Comment by fcpauldiaz** [comment]
The 3 solutions proposed didn't worked for me, but I was able to fix it by importing the adapter without using in next.js.

```
import { AdapterDateFns as _ } from "@mui/x-date-pickers/AdapterDateFnsV3";
```

**Comment by LukasTy** [comment]
> The 3 solutions proposed didn't worked for me, but I was able to fix it by importing the adapter without using in next.js.
> 
> ```
> import { AdapterDateFns as _ } from "@mui/x-date-pickers/AdapterDateFnsV3";
> ```

@fcpauldiaz Which `date-fns` package version are you using?
If it is v3, then you should have tried
```ts
import type {} from '@mui/x-date-pickers/AdapterDateFnsV3';
```
Does that help?
Importing the whole adapter without explicitly using it seems a bit inefficient. 🤔

**Comment by fcpauldiaz** [comment]
this fixed the issue! thanks @LukasTy

**Comment by melmathari** [comment]
The solution:

1. Removed the generic type parameter from DatePickerProps<Dayjs>
2. Added the adapter import: import type {} from '@mui/x-date-pickers/AdapterDayjs'
3. Used React.ComponentProps to extract the props type directly from the component without needing explicit generics
4. Changed from interface to type for better composition with intersection types
