### ISSUE TITLE
[data grid] Module '"@mui/x-data-grid-premium"' has no exported member 'GridColDef'.

### ISSUE THREAD

**Issue by quintonlucyk** [mui/mui-x#12665]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Follow the docs and use https://mui.com/x/api/data-grid/grid-col-def/#:~:text=import%20%7B%20GridColDef%20%7D%20from%20%27%40mui/x%2Ddata%2Dgrid%2Dpremium%27%3B
2. Encounter ts issue: Module '"@mui/x-data-grid-premium"' has no exported member 'GridColDef'.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: x-data-grid-premium

**Comment by michelengelen** [comment]
I can import it just fine on my local instance.
Could you please provide a minimal reproduction in codesandbox or stackblitz for this?

**Comment by quintonlucyk** [comment]
Yeah. At the moment I have found it also un-reproducible. Must be something on our end. I"ll reopen if I have new info.

Thanks
