### ISSUE TITLE
[charts] Rendering a Bar Chart with an empty dataset throws an error

### ISSUE THREAD

**Issue by Euphorichuman** [mui/mui-x#12686]
### Search keywords

chart, barchart, dataset, empty, throw error

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

[Link to live example](https://codesandbox.io/p/sandbox/musing-aj-4wfff2)

Steps:
1. Open the live example
2. Run the code

### Current behavior

Throws an error:
```
TypeError
Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

### Expected behavior

It should render an empty chart similar like in the LineChart render when an empty dataset is provided.

### Context

I was trying to implement a dynamic dataset which can change when a series of filters are applied.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Fixed by #12708
