### ISSUE TITLE
[pickers] V7 LocalizationProvider not accepting AdapterMoment

### ISSUE THREAD

**Issue by bwnkmd** [mui/mui-x#12689]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Install latest v7
2. Using typescript
3. `<LocalizationProvider dateAdapter={AdapterMoment} />`

### Current behavior

Types of construct signatures are incompatible.
Construct signature return types 'AdapterMoment' and 'MuiPickersAdapter<Date, string>' are incompatible.
The types returned by 'date(...)' are incompatible between these types.
        Type 'DateBuilderReturnType<T, Moment>' is not assignable to type 'DateBuilderReturnType<T, Date>'.

### Expected behavior

Expect it to work with MomentAdapter

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  Don't forget to mention which browser you used.
Chrome
  Output from `npx @mui/envinfo` goes here.
System:
    OS: macOS 14.4.1
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.107
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4
    @emotion/styled: 11.10.4 => 11.10.4
    @mui/icons-material: 5.15.15 => 5.15.15
    @mui/lab: 5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: 5.15.15 => 5.15.15
    @mui/styles: 5.15.15 => 5.15.15
    @mui/system: 5.15.15 => 5.15.15
    @mui/x-data-grid-premium: 7.1.1 => 7.1.1
    @mui/x-date-pickers: 7.1.1 => 7.1.1
    @mui/x-date-pickers-pro: 7.1.1 => 7.1.1
    @mui/x-license: 7.0.0 => 7.0.0
    @mui/x-license-pro:  6.10.2
    @mui/x-tree-view: 7.1.1 => 7.1.1
    @types/react: 17.0.2 => 17.0.2
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.6.4 => 4.6.4
</details>

**Search keywords**: LocalizationProvider AdapterMoment
**Order ID**: 49270

**Comment by bwnkmd** [comment]
a step is missing, the issue is with
<LocalizationProvider dateAdapter={AdapterMoment}>

**Comment by LukasTy** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot. 🙏 
A live example would be perfect. StackBlitz demo or GitHub repo are the best options.

P.S. An unrelated suggestion: consider removing `@mui/x-license-pro: 6.10.2` from your dependencies. 😉

**Comment by michelengelen** [comment]
Just tested the example from [here](https://mui.com/x/react-date-pickers/adapters-locale/#with-moment) locally and on stackblitz. It works just fine for me, so it has to be something in your specific implementation.

Could you please provide a reproduction example as @LukasTy mentioned and keep your implementation specifics in as accurate as possible? Thanks!

**Comment by bwnkmd** [comment]
Hi

Yes i can see that it works in a small stackblitz project, ours are a big app.. ill dive in to or app that we just upgraded. Ill close this issue. 

PS. LukasTy, thx for the hint :)

**Comment by bwnkmd** [comment]
Working in a stackblitz project
