### ISSUE TITLE
[data grid] Labels that are defined outside of hooks should be type of `ReactNode` instead of `string`

### ISSUE THREAD

**Issue by xpy** [mui/mui-x#12699]
### Summary

There are labels inside the table, such as the label inside GridFilterOperator and the headerName inside the GridColDef. That are typed as string, this brings problems when using localization, since the localization function comes from a hook and then we would have to prop drill it.

Even though the GridFilterOperator label type is a string, the code allows a ReactNode: https://github.com/mui/mui-x/blob/b51d1526d4d821d2131a9bf87ff9dbf29a34c377/packages/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx#L577

Is there a reason those labels are typed as a string?

### Motivation

Filters and columns are most if the time configuration and they usually don't live inside hooks, 

**Search keywords**: GridFilterOperator GridColDef

**Comment by michelengelen** [comment]
Hey @xpy 
Thanks for bringing this up.
It is indeed strange that this got typed purely as `string`.
I will add this to our board so we can improve this.

Could you think of more examples where this might be a case?
