### ISSUE TITLE
[pickers] Move internal localization hook `useLocaleText` to Public API

### ISSUE THREAD

**Issue by kealjones-wk** [mui/mui-x#12691]
### Summary

You should move [useUtils](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/hooks/useUtils.ts) out of `internals` and allow consumers to use those hooks with their own custom components.

### Examples

When building my own component to replace `PickersActionBar` I am unable to localize the text content easily without just literally copy/pasting the internal [useUtils](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/hooks/useUtils.ts) into my repo.

### Motivation

I am trying to localize my custom slot components for date pickers.

**Search keywords**: useLocaleText, useUtils, useLocalization
**Order ID**: 82849

**Comment by LukasTy** [comment]
@kealjones-wk could you confirm if this is some other request additional to the one discussed, groomed, and planned in https://github.com/mui/mui-x/issues/12049#issuecomment-1953915199? 🤔 
To me, this looks like a duplicate issue at the moment. 🙈

**Comment by kealjones-wk** [comment]
Sorry for the delayed response i was away at a conference.

Fair enough that its a duplicate, I just wanted it to be explicit of the ask as that other ticket is solely limited to this request.

Also I was hoping that we could get some momentum behind this as pro/premium users because it is a large issue for my team that is actively working on DatePickers right now.

**Comment by michelengelen** [comment]
Got it @kealjones-wk ... I will add this to the board, so we can estimate and discuss this with the team! Thanks for the clarification.

**Comment by LukasTy** [comment]
Closing https://github.com/mui/mui-x/issues/12049 in favor of this more explicit issue.
We agreed to move `useLocaleText` hook to public API, preferably under `@mui/x-date-pickers/hooks`.
We agreed to add a section about using this capability/hook in the https://mui.com/x/react-date-pickers/localization/ page and link to an updated demo using it in https://mui.com/x/react-date-pickers/custom-components/#component, which should cover pain points mentioned in https://github.com/mui/mui-x/issues/12049.
