### ISSUE TITLE
[charts] Pie chart center label in 7.1.1

### ISSUE THREAD

**Issue by 3pleFly** [mui/mui-x#12695]
### Summary

Hello, you have already added center label for pie charts here:
https://github.com/mui/mui-x/pull/10220

However in version 7.1.1 these are not available... I have been looking for how to do this over the documentation and library files and have no found a solution... Am I missing something or was this feature trashed in version 7?

### Examples

https://github.com/mui/mui-x/pull/10220

### Motivation

My pie chart has an inner radius so that the center of it is empty, and I need to add a label there.
![image](https://github.com/mui/mui-x/assets/67366321/1e0997ae-e513-48c2-8ff4-092c3340f15a)

**Search keywords**: Pie chart center label

**Comment by alexfauquette** [comment]
What make you say it got removed?

It's still in the [docs demo](https://mui.com/x/react-charts/pie-demo/#piechartwithcenterlabel)

**Comment by 3pleFly** [comment]
> What make you say it got removed?
> 
> It's still in the [docs demo](https://mui.com/x/react-charts/pie-demo/#piechartwithcenterlabel)


Apologies I missed a key detail is that you can't import useDrawingArea from  '@mui/x-charts/hooks/useDrawingArea', which is mentioned in https://github.com/mui/mui-x/pull/10220 . That's what I was missing, since you can import it from "@mui/x-charts/hooks".
