### ISSUE TITLE
[data grid] DataGridPremium fails tro compile

### ISSUE THREAD

**Issue by deependrasingh17** [mui/mui-x#12694]
### Current behavior

I am first time user of DataGridPremium, when I am trying to use DataGridPremium in my react component below error occurs in VSCode terminal.
Failed to compile. 
./node_modules/@mui/x-data-grid-premium/node_modules/@mui/x-data-grid/components/columnSelection/GridHeaderCheckbox.js 108:25   
[1] Module parse failed: Unexpected token (108:25)
[1] File was processed with these loaders:
[1]  * ./node_modules/babel-loader/lib/index.js
[1] You may need an additional loader to handle the result of these loaders.
[1] |     onKeyDown: handleKeyDown,
[1] |     disabled: !isMultipleRowSelectionEnabled(rootProps)     
[1] >   }, rootProps.slotProps?.baseCheckbox, other));
[1] | });

### Expected behavior

App should compile without error.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: ./node_modules/@mui/x-data-grid-premium/node_modules/@mui/x-data-grid/components/columnSelection/GridHeaderCheckbox.js 108:25
**Order ID**: 87936

**Comment by michelengelen** [comment]
Hey @deependrasingh17 
Could you tell us your build setup? From this output alone it is basically a guessing game. 

My first guess would be that your babel setup cannot parse the [optional chaining operator (`?.`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). Check the documentation on the related babel plugin [here](https://babeljs.io/docs/babel-plugin-transform-optional-chaining)

Could you check that and get back to us if that does not fix it for you?

**Comment by michelengelen** [comment]
Seems related to #12612

**Comment by cherniavskii** [comment]
Closing in favor of https://github.com/mui/mui-x/issues/12612
Please take a look at https://github.com/mui/mui-x/issues/12612#issuecomment-2042808701
