### ISSUE TITLE
[data grid] Debugger pauses on caught exceptions: No row with id found

### ISSUE THREAD

**Issue by SherenL** [mui/mui-x#12704]
### Steps to reproduce

Link to live example: (required)

https://stackblitz.com/edit/github-v2hkyr?file=src%2FApp.js

Steps:
1.  Right click inspect and go to the sources tab
2.  Uncheck 'Pause on caught exceptions'
3.  Resume script execution (F8)
4.  Check 'Pause on caught exceptions'
5.  Click 'Update Rows' button

### Current behavior

Depending on the user’s selection, different sets of rows are loaded into the DataGrid. 

The program halts if the debugger’s “Pause on caught exceptions” option is enabled when these data rows are swapped with a new set of rows.

However, if this option is disabled, the program operates without any interruptions.

![issues_race_condition](https://github.com/mui/material-ui/assets/101408326/e297d80b-c7c6-4caa-98b3-a811d5257d2f)

### Expected behavior

Whether the "Pause on caught exceptions" option is ticked or not, the program should run without any issues. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (123.0.2420.81)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.21
    @mui/core-downloads-tracker:  5.14.15
    @mui/icons-material: ^5.14.15 => 5.14.15
    @mui/material: ^5.14.15 => 5.14.15
    @mui/private-theming:  5.14.15
    @mui/styled-engine:  5.14.15
    @mui/styled-engine-sc: ^6.0.0-alpha.3 => 6.0.0-alpha.3
    @mui/system: ^5.14.15 => 5.14.15
    @mui/types:  7.2.7
    @mui/utils:  5.15.11
    @mui/x-data-grid: latest => 6.19.5
    @mui/x-data-grid-premium: ^6.19.5 => 6.19.5
    @mui/x-data-grid-pro:  6.19.5
    @mui/x-license-pro:  6.10.2
    @mui/x-tree-view: ^6.0.0-beta.0 => 6.0.0-beta.0
    @types/react: 18.2.24 => 18.2.24
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: ^6.1.0 => 6.1.0
    typescript: 5.1.3 => 5.1.3
```

</details>

**Search keywords**: datagrid

**Comment by michelengelen** [comment]
Hey @SherenL ... why would the expected way to not pause on caught exceptions? That's the whole reason why this option exists.

I am not sure what your intention is. Could you elaborate?

**Comment by michelengelen** [comment]
One more thing: I tried to replicate the error you mentioned, but for me it never showed `No row with id found`

**Comment by SherenL** [comment]
Thank you for your replies and for letting me know it wasn't reproducible. I've added the script name to the 'ignore list' in the debugger and am able to continue using the debugger.

**Comment by SherenL** [comment]
Thank you for your replies and for letting me know it wasn't reproducible. I've added the script name to the 'ignore list' in the debugger and am able to continue using the debugger.

**Comment by SherenL** [comment]
Thank you for your replies and for letting me know it wasn't reproducible. I've added the script name to the 'ignore list' in the debugger and am able to continue using the debugger. Happy for this to be closed.

**Comment by SherenL** [comment]
Thank you for your replies and for letting me know it wasn't reproducible. I've added the script name to the 'ignore list' in the debugger and am able to continue using the debugger. Happy for this to be closed.
