### ISSUE TITLE
[data grid] Is it possible to aggregate data in DataGrid only by selected rows?

### ISSUE THREAD

**Issue by DenisovKirill** [mui/mui-x#12718]
### The problem in depth

Hello!
Please tell me if it is possible to aggregate data only by selected rows from the GridRowSelectionModel?

I tried to do something like this

```ts
import { GridAggregationFunction, GridRowSelectionModel } from '@mui/x-data-grid-premium';

export const customAggregationSum = (
  selected: GridRowSelectionModel,
  selectedColumnId: string,
): GridAggregationFunction<any, number> => {
  return {
    label: 'testSum',
    getCellValue: ({ row }) => ({
      id: row.id,
      col: row[selectedColumnId],
    }),
    apply: (params) => {
      const selectedValues = params.values.filter((value) => {
        if (value) return selected.includes(value.id);
        return null;
      });

      return selectedValues.reduce(
        (accumulator, currentValue) => accumulator + currentValue.col,
        0,
      );
    },
    columnTypes: ['number'],
  };
};
```

But I don't understand how can I pass selectedColumnId when use aggregation in multiple columns.

Thank you and have a great day!

### Your environment

<details>
  <summary>
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.106
  npmPackages:
    @emotion/react: ^11.9.0 => 11.11.4
    @emotion/styled: ^11.8.1 => 11.11.0
    @mui/base:  5.0.0-beta.38
    @mui/core-downloads-tracker:  5.15.12
    @mui/icons-material: ^5.8.0 => 5.15.12
    @mui/lab: 5.0.0-alpha.167 => 5.0.0-alpha.167
    @mui/material: 5.15.12 => 5.15.12
    @mui/private-theming:  5.15.12
    @mui/styled-engine:  5.15.11
    @mui/system: ^5.11.1 => 5.15.12
    @mui/types:  7.2.13
    @mui/utils:  5.15.12
    @mui/x-data-grid:  6.19.6
    @mui/x-data-grid-premium: ^6.11.1 => 6.19.6
    @mui/x-data-grid-pro:  6.19.6
    @mui/x-date-pickers: ^6.5.0 => 6.19.6
    @mui/x-date-pickers-pro: ^6.7.0 => 6.19.6
    @mui/x-license-pro:  6.10.2
    @mui/x-tree-view: ^6.17.0 => 6.17.0
    @types/react: ^18.2.15 => 18.2.64
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.1.6 => 5.4.2

  </summary>
</details>

**Search keywords**: selected rows aggregation
**Order ID**: 53254

**Comment by michelengelen** [comment]
Hey @DenisovKirill ... this is a bit complicated but you can accomplish this by using [controlled row selection](https://mui.com/x/react-data-grid/row-selection/#controlled-row-selection), [grid API](https://mui.com/x/api/data-grid/grid-api/) and [custom aggregation functions](https://mui.com/x/react-data-grid/aggregation/#create-custom-functions).

Here is a working demo of it: [Example](https://stackblitz.com/edit/react-oqc1hj?file=Demo.tsx)

**Comment by michelengelen** [comment]
@cherniavskii this approach is a bit complicated. Would it maybe make sense to add a new property to the aggregator definitions to only include (or maybe even exclude) selected rows?

**Comment by cherniavskii** [comment]
@michelengelen I've updated your demo to fix the initial aggregation model not working: https://stackblitz.com/edit/react-oqc1hj-zemza5?file=Demo.tsx

This solution makes sense to me.

I'm curious what is the use case?

**Comment by DenisovKirill** [comment]
Thank you!
That's what I need

**Comment by DenisovKirill** [comment]
Thank wou!
That's what I need
