### ISSUE TITLE
[data grid] Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by delciopolanco** [mui/mui-x#12728]
### Description.

Datagrid doesn't work with a custom Mui theme.

### Steps to reproduce

Link to example: [Github](https://github.com/delciopolanco/MuiDatagridExample)

Steps:
1. git clone https://github.com/delciopolanco/MuiDatagridExample.git
2. yarn install or npm install
3. yarn dev or npm run dev.

See implementation below:

```jsx
export const App = () => {
  const columns: GridColDef<(typeof rows)[number]>[] = [
    { field: 'id', headerName: 'ID', width: 90 },
    {
      field: 'firstName',
      headerName: 'First name',
      width: 150,
      editable: true,
    },
    {
      field: 'lastName',
      headerName: 'Last name',
      width: 150,
      editable: true,
    },
    {
      field: 'age',
      headerName: 'Age',
      type: 'number',
      width: 110,
      editable: true,
    },
  ];
  const rows = [
    { id: 1, lastName: 'Snow', firstName: 'Jon', age: 14 },
    { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 31 },
    { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 31 },
    { id: 4, lastName: 'Stark', firstName: 'Arya', age: 11 },
    { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
    { id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
    { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
    { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
    { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 },
  ];

  return (
    <Box sx={{ height: 400, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        initialState={{
          pagination: {
            paginationModel: {
              pageSize: 5,
            },
          },
        }}
        pageSizeOptions={[5]}
        checkboxSelection
        disableRowSelectionOnClick
      />
    </Box>
  );
};

export default App;
```

Error:

![image](https://github.com/mui/mui-x/assets/20881846/c45f88c8-b594-4bde-ace9-dfe0d4427802)

### Current behavior

It doesn't show the data grid, instead it throws an error like TypeError: Cannot read properties of undefined (reading 'type')
    at decomposeColor 

### Expected behavior

It should show the Datagrid the same as this: [example](https://codesandbox.io/p/sandbox/great-dream-t7ck8m?file=%2Fsrc%2FDemo.tsx) 

### Context

I'm trying to use DataGrid from Mui within my project.

### Your environment

<details>
  <summary><code>System:
   System:
    OS: macOS 14.2.1
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.107
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.15 
    @mui/material: ^5.15.11 => 5.15.15 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^7.1.1 => 7.1.1 
    @types/react: ^18.2.66 => 18.2.75 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.4.4  </code></summary>
    
    Chrome version: 122.0.6261.94

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Cannot read properties of undefined (reading 'type')

**Comment by michelengelen** [comment]
Hey @delciopolanco 
This is not an issue with the data grid, but with your implementation of the custom palette.
The Palette is defined as this:
https://github.com/mui/material-ui/blob/3cde1e701aeb28bac46dc01df20b5ca53a6d0b3c/packages/mui-material/src/styles/createPalette.d.ts#L110-L127

And the background property (`background?: Partial<TypeBackground>;`) is defined as this:
https://github.com/mui/material-ui/blob/3cde1e701aeb28bac46dc01df20b5ca53a6d0b3c/packages/mui-material/src/styles/createPalette.d.ts#L33-L36

This means that you cannot pass a hex colorcode into the background property. It needs to be an object respecting the type `TypeBackground`

**Comment by delciopolanco** [comment]
@michelengelen thanks for responding, it's working fine now.
