### ISSUE TITLE
[charts] tickLabelInterval does not work for left, right or y axes in barChart

### ISSUE THREAD

**Issue by JessePomerenk** [mui/mui-x#12725]
### Steps to reproduce

Link to live example: [Example](https://stackblitz.com/edit/react-c261at?file=Demo.tsx)

Steps:
1. Make a bar chart (would probably work in any chart)
2. set `tickLabelInterval: () => false` on `leftAxis`, `rightAxis`, or `yAxis`
3. OBSERVE: left and right tick labels still show
4. set `tickLabelInterval: () => false` on `topAxis`, `bottomAxis`, or `xAxis`
5. OBSERVE: top and bottom axis do not have tick labels

![Screenshot 2024-04-09 at 11 44 42 AM](https://github.com/mui/mui-x/assets/127802678/3bcff551-e633-4dc8-8c56-093a155875bd)

### Current behavior

Using `tickLabelInterval` on left/right/y axes does nothing

### Expected behavior

Using `tickLabelInterval` should work the same for left/right/top/bottom/x/y axes

### Context

We are drawing a right and top axis to have a nice boarder around the graph area.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 Chrome Version 123.0.6312.107 (Official Build) (arm64)
   System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    npm: 9.5.1 - ~/.asdf/installs/nodejs/18.16.0/bin/npm
    pnpm: 6.32.8 - ~/.asdf/installs/pnpm/6.32.8/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.107
    Edge: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.14
    @mui/icons-material: ^5.15.14 => 5.15.14
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.14 => 5.15.14
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.14
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-charts: ^7.1.0 => 7.1.0
    @mui/x-data-grid:  7.1.0
    @mui/x-data-grid-premium: ^7.1.0 => 7.1.0
    @mui/x-data-grid-pro:  7.1.0
    @mui/x-date-pickers:  7.1.0
    @mui/x-date-pickers-pro: ^7.1.0 => 7.1.0
    @mui/x-license:  7.0.0
    @mui/x-license-pro: ^6.10.2 => 6.10.2
    @types/react: ^18.2.74 => 18.2.74
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.4.4 => 5.4.4
```
</details>

**Search keywords**: tick chart tickLabelInterval y-axis
**Order ID**: SecureCodeWarrior Premium Plan

**Comment by michelengelen** [comment]
Hey @JessePomerenk and thanks for raising this issue.
I did label this as a bug, as it should work the same way it does on the horizontal axes.

cc @JCQuintas

**Comment by alexfauquette** [comment]
I've fixed a similar issue recently due to a props not passed to the `<ChartsYAxis />` #12592
