### ISSUE TITLE
[pickers][DateTimePicker] Programmatically disable OK action until an option is selected

### ISSUE THREAD

**Issue by teryn-trimble** [mui/mui-x#12727]
### Summary

When clicking the calendar icon in the DateTimePicker, it would be nice to programmatically disable the "OK" button until a date, hour, or minute is first selected and a date is able to be "accepted".

Right now, clicking OK without selecting a value just closes the popper, the same as clicking the calendar icon or clicking outside, which our users have complained about because they don't understand you have to pick a value first.

Ideally, this would be an additional slotProp option so that it could be conditionally used if needed.

### Examples

For example, the OK button would be disabled when I first open it, and then once I click on a date, the OK button would be enabled for them to "accept" the date they've chosen.
![image](https://github.com/mui/mui-x/assets/128737698/e93cdc6e-162d-4fb6-8c27-98b1c835ce0e)

### Motivation

Some of our users were confused that they had to select a date, or an hour in order to "choose" that date. The OK first works like a cancel/close rather than an accept. If they aren't familiar with our UI yet and see the current date "highlighted", they may assume that this is the date chosen for them without realizing they have to actually pick something.

Another possible use case would be that one date picker we allow you to clear the date, but on another we don't. In that case, it's sometimes preferable to make things "look" the same. Which in that case, we'd add the clear button on the second date picker, but disable it instead. That way the layout looks the same across both pickers but the action is disabled in the one where we don't want to let you clear it.

**Search keywords**: picker conditionally disable action
**Order ID**: 3012c2f783dce16e8e6ba9d0719f974fTz03OTAzNCxFPTE3MzE5NjEyNTYwMDAsUz1wcmVtaXVtLExNPXN1YnNjcmlwdGlvbixLVj0y

**Comment by michelengelen** [comment]
hey @teryn-trimble 
this would be possible right now with a [dom customization](https://mui.com/x/react-date-pickers/custom-layout/#dom-customization), but this does seem like a bit of overkill for a specific use case like this.
The problem with your approach is, that each action would need to receive a set of props that can get passed to the button its intended for. 
I will add this to the board so the team can have a look and estimate it properly.

**Comment by LukasTy** [comment]
Hello @teryn-trimble
I think that this is a very similar issue to https://github.com/mui/mui-x/issues/12049 where we agreed that we would not be expanding the customization of the action bar using additional props, but improve the customization examples and expose the missing piece (`useLocaleText` hook) publically.
I've played around with a [customization idea](https://stackblitz.com/edit/react-a4qwgu?file=Demo.tsx).
What do you think about it? Does it make sense and solve the problem?
If yes, I'd say that this is a duplicate issue and we just need to resolve the mentioned issue for this solution to be considered production viable.

**Comment by teryn-trimble** [comment]
@LukasTy 
It is a similar issue to #12049. I looked at the example you provided and it makes sense. I didn't even think about overriding the entire toolbar like that and taking in a new prop. It does solve our issue. Thank you!
