### ISSUE TITLE
[data grid] Double click column border to autosize grid column width not working.

### ISSUE THREAD

**Issue by mschaefer-gresham** [mui/mui-x#12733]
### Steps to reproduce

Double clicking a grid column to autosize it does not work most of the time. The below example is a fork from a grid example on the MUI website. With 5 rows the autosizing of 'Last name' does not work. But if you remove all but one column, then autosizing works. 

https://github.com/mui/mui-x/assets/94627216/79f65773-1807-4a52-bf11-c75f58586759

https://codesandbox.io/p/sandbox/thirsty-lovelace-cwwsp7?file=%2Fsrc%2FDemo.tsx%3A37%2C77

### Current behavior

Double clicking column border to autosize does not work.

### Expected behavior

It should work.

### Context

Trying to autosize a column based on the width of the data in this column's rows.

### Your environment

My example is a forked CodeBox from the MUI website.

**Search keywords**: autosize column width grid double-click
**Order ID**: 45466

**Comment by michelengelen** [comment]
Hey @mschaefer-gresham 
For this to always work you would need to pass `autosizeOptions` to the grid.

```tsx
autosizeOptions={{
  includeOutliers: true,
  includeHeaders: true,
}}
```

I am not 100% sure what kind of algorithm is used when the defaults, `includeOutliers: false` and `includeHeaders: false` are used, but this will make sure that the columns are always autosized to fit the content (when there is enough space for it)

**Comment by michelengelen** [comment]
@mschaefer-gresham does that fix your use case?

**Comment by mschaefer-gresham** [comment]
@michelengelen thank you. This appears to solve the issue.
