### ISSUE TITLE
[data grid][docs] Demo InitialFilters crashes

### ISSUE THREAD

**Issue by Kripton0810** [mui/mui-x#12740]
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20InitialFilters%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-data-grid/filtering/
2. ??
3. demo *InitialFilters* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v7.1.1  |
| Netlify deploy | https://660fc3e99f05800008d92905--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by alexfauquette** [comment]
I struggle to reproduce the crash. Could you do a recording such that we could see which interaction leads to the crash?
