### ISSUE TITLE
[charts] slots for PieArcLabelPlot defined in PieArcLabelPlotSlots but never passed down from PieChart

### ISSUE THREAD

**Issue by abeanater** [mui/mui-x#12756]
### Steps to reproduce

Link to live example: (required)
- defined here: [PieArcLabelPlotSlots](https://github.com/mui/mui-x/blob/aed8aeb903ef7d319419a7c50eb44286d547888d/packages/x-charts/src/PieChart/PieArcLabelPlot.tsx#L40)
- Should be passed in here: [PieArcLabelPlot](https://github.com/mui/mui-x/blob/aed8aeb903ef7d319419a7c50eb44286d547888d/packages/x-charts/src/PieChart/PiePlot.tsx#L120)

Steps:
1.  Try adding custom pieArcLabel component to slots prop of PieChart although defined in types its never propagated down into PieArcLabelPlot

### Current behavior

User expects to be able to use custom PieArcLabel component as its defined in the slots.  They add it but it doesnt work as its not passed into the PieArcLabelPlot component.

### Expected behavior

If you set pieArcLabel slot prop it should propagate down and use your custom label.

### Context

I was hoping to add functionality like different colors, rotating the text, etc of a pieArcLabel.  I expected to be able to use this slot but I could not. 

### Your environment

NA.  This is just from a code perspective. 

**Search keywords**: PieArcLabelPlotSlots, PieArcLabelPlot, slots

**Comment by JCQuintas** [comment]
Hi @abeanater, from a quick test it indeed looks like neither the `slotProps` nor the `slots` are being passed on. I'll look into it as soon as possible.

**Comment by abeanater** [comment]
@JCQuintas  Thanks for taking a look!  Yes it was both the `slotProps` in addition to the `slots`.  It looks like the PieArcLabelPlot is ready for it.  It just needs to be passed on down.
