### ISSUE TITLE
[pickers] Rendering Issue with MuiDayCalendar for November 2024 to March 2025

### ISSUE THREAD

**Issue by BrancoPT** [mui/mui-x#12764]
### Steps to reproduce

Link to live example: [(required)](https://alu-capsule-recycling.ch/visit/)

Steps:
1. Choose Language
2. Choose language visit
3. Choose november on datepicker

### Current behavior

The months are being displayed incompletely, with only a few days visible.

### Expected behavior

The months should be fully displayed, with all corresponding days shown.

### Context

I am experiencing an issue with the MuiDayCalendar component in my React application where the rendering of some months is showing unexpected behavior. Specifically, the months from November 2024 to March 2025 are not being displayed correctly:

November 2024: Only 3 days are displayed.
December 2024: Only 1 day is displayed.
January to March 2025: Similar issue, with a very limited number of days displayed.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Rendering Issue

**Comment by michelengelen** [comment]
Hey @BrancoPT 
I cannot reproduce the issue. I tried every combination of languages.
Just to narrow it down:

1. What timezone are you in?
2. Which time package are you using? Could it be dayjs?

For the future: A reproduction where we can check the code is best. Codesandbox or Stackblitz are our prefered ways as we can just run them from our docs examples.
