### ISSUE TITLE
Autocomplete popupIcon icon is turning down

### ISSUE THREAD

**Issue by FreakDroid** [mui/mui-x#12766]
### Steps to reproduce

Link to live example: [Demo](https://codesandbox.io/p/sandbox/naughty-monad-mwky6z?file=%2Fsrc%2FDemo.tsx%3A13%2C50)

Steps:
1. See the icon in the autocomplete
2. Click the autocomplete to search any value
3. See the icon turning down.

### Current behavior

In the autocomplete component the popupIcon (custom icon) is turning down when the autocomplete is opened.

Closed:
![Screenshot 2024-04-11 at 17 57 03](https://github.com/mui/mui-x/assets/5360335/e3e1e5db-3bf2-4e10-b071-37cf32dc44db)

Opened:
![Screenshot 2024-04-11 at 17 57 09](https://github.com/mui/mui-x/assets/5360335/b79255bd-0a98-42d4-ad27-4f5b9eaba04a)

### Expected behavior

If the icon is not an arrow, the orientation should be kept. Probably can we give to the user the option to decide whether to flip the icon or not.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Autocomplete custom icon
**Order ID**: 77137

**Comment by korkt-kim** [comment]
you can solve the problem like this way
```
export default function ComboBox() {
  return (
    <Autocomplete
      disablePortal
      id="combo-box-demo"
      options={top100Films}
      sx={{
        width: 300,
        "& .MuiAutocomplete-popupIndicator": { transform: "none" }, // added
      }}
      open={true}
      forcePopupIcon={true}
      clearIcon={<SearchIcon fontSize="small" />}
      popupIcon={<SearchIcon fontSize="small" />}
      renderInput={(params) => <TextField {...params} label="Movie" />}
    />
  );
}
```

**Comment by FreakDroid** [comment]
@korkt-kim Thanks for that this resolve my issue.
