### ISSUE TITLE
[data grid] Whats the preferred way to handle edit events?

### ISSUE THREAD

**Issue by camnealie** [mui/mui-x#12777]
### The problem in depth

Currently I'm attempting to upgrade my app from DataGridPremium v5 to v6. 

I built much of the apps logic around the v5 'onCellEditCommit' prop and pattern, where, onChange, it sends something like {field: 'qty', value: 2, id: xx}. I send that through to my backend, the fieldname, value and the rowID, it handles it, great.

I'm having trouble replicating that in v6. OncCellEditCommit has been deprecated, and I assume I'm supposed to be using 'OnCellEditStop' instead. The issue is, when that fires, it sends me the _old_ value, not the new one. 

If I do something like onCellEditStop = {(a,b)=>console.log(b.target.value)} sure, that gives me the value, but _only if the action that triggers the cell edit stop is an enter press_. If the onCellEditStop is fired by say, a user clicking away, then the new value isn't able to be retrieved. 

If I instead try capturing the change via apiRef.current.getRowWithUpdatedValues(a.id); I'm still getting the old value during this event.

It's driving me a little crazy. I want users to be able to edit specific columns (as defined in my columns definition), and I need to know exactly what changed and what it changed to. Whats the intended way of doing this? 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 18.19.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.7 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.122
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ^11.8.2 => 11.11.4 
    @emotion/styled: ^11.8.1 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.15 
    @mui/icons-material: ^5.15.15 => 5.15.15 
    @mui/lab: ^5.0.0-alpha.136 => 5.0.0-alpha.170 
    @mui/material: ^5.12.2 => 5.15.15 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  6.19.8 
    @mui/x-data-grid-premium: ^6.14.0 => 6.19.8 
    @mui/x-data-grid-pro:  6.19.8 
    @mui/x-date-pickers: ^5.0.3 => 5.0.20 
    @mui/x-date-pickers-pro: ^5.0.3 => 5.0.20 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.0.28 => 18.2.74 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.3 => 4.9.5 
</details>

**Search keywords**: DataGridPremium Onchange
**Order ID**: 72586

**Comment by michelengelen** [comment]
Hey @camnealie
The functionality you are looking for is [`processRowUpdate`](https://mui.com/x/react-data-grid/editing/#server-side-persistence)

With this you can handle updates and store them to your backend.

Does that solve your use case?

**Comment by camnealie** [comment]
I've got no idea how I missed that. Maybe I thought it only applied when
editMode="row"

Thanks, I've written a wrapper function to get out the information I need
from that. Sorted.

**Comment by michelengelen** [comment]
Great that this solved your problem.
I'll close this one then! ✨
