### ISSUE TITLE
[data grid] Column Grouping not working

### ISSUE THREAD

**Issue by justin1j** [mui/mui-x#12774]
### Steps to reproduce

Link to live example: (required)

https://codesandbox.io/p/sandbox/dazzling-aryabhata-r8m9wx?file=%2Fsrc%2FDemo.tsx

Steps:
1. Go to Column groups in MUI X grid doc
2. Pick any example 
3. Run in 3rd party code editor (Not example on the doc page)

### Current behavior

Column group is not displaying on the page

### Expected behavior

Column group should be visible on the page

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: column grouping

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @justin1j ... it does work for me locally and in Codesandbox or Stackblitz.
Could you maybe try to replicate and post an example here?
Thanks! 🙇🏼
