### ISSUE TITLE
[data grid] Accordian in DataGrid

### ISSUE THREAD

**Issue by richaDhingra** [mui/mui-x#12778]
### Summary

I need to add an accordian in the Data Grid using slots. I am having a DataGrid , which is listing the data correctly am looking for some way to add accordian in the row , so if we click row accordian opens and accordian data can be visible for the row clicked. I am trying to achieve this using slots
```tsx
<DataGrid
    columns={columns}
    rows={tableRows}                       
/>
```              

### Examples

I am aware using slots.row i can override the row, however I could not find any documentation, examples or issues which would showcase how I can add an accordian.

```tsx
<DataGrid
    columns={columns}
    rows={tableRows}
     slots={{
         row: (data) => {
           return <div>Hello</div>;
         }
    }}
/>
```

**Search keywords**: DataGrid Slots

**Comment by michelengelen** [comment]
Hey @richaDhingra 
From what I understand you can use the [Master Detail](https://mui.com/x/react-data-grid/master-detail/) feature for that. It will not wrap the row (which is not preferred) and instead add a section below that can be opened with a designated toggle column.

Inside you can render whatever you like, even accordions.

If you really need to add an accordion as a replacement for the row component you can also do that, but it is way more complicated and less performant. The approach you mentioned in your issues text is correct. Using `slots.row` would be the way to replace a row with something custom.

**Comment by richaDhingra** [comment]
@michelengelen Thanks for your reply , I have seen Master Detail feature and have planned to use that only.

One thing regarding the approach i wanted to workout i.e. using slots.row , if I use that it will override the current row component with a custom component and i won't be able to use data grid sorting feature on it. Is my understanding correct?

**Comment by michelengelen** [comment]
Yes, you are correct about the sorting. You would need to implement a custom sorting/filtering in that case

**Comment by richaDhingra** [comment]
@michelengelen  Thanks for confirming.
