### ISSUE TITLE
[data grid] Column Resize Issue when we've controlled selection

### ISSUE THREAD

**Issue by trineshl** [mui/mui-x#12773]
### Steps to reproduce

Run the code snippet below as it is...
Step 1: Resize any column.
Step 2: Select any other row.
You will notice that the column size returns to its initial state.
This is because the state is controlled by state.
However, the column should not be resized.

import * as React from 'react';
import { DataGrid } from '@mui/x-data-grid';
import { useDemoData } from '@mui/x-data-grid-generator';

function GetDataDefinition() {
  return [
    {
      field: 'name',
      headerName: 'Name',
      sortable: true,
      sort: 'asc',
      sortIndex: 2,
      filter: true,
      flex: 1.5
    },
    {
      field: 'email',
      headerName: 'Email',
      sortable: true,
      // resizable: true,
      filter: true,
      flex: 1.5
    },
    {
      field: 'created_on',
      headerName: 'Created On',
      // width: 250,
      sortable: true,
      // type: 'date',
      // resizable: true,
      sort: 'asc',
      sortIndex: 1,
      filter: true,
      customFieldType: 'datetime',
      flex: 1
    },
    {
      field: 'updated_on',
      headerName: 'Updated On',
      // width: 250,
      sortable: true,
      // resizable: true,
      filter: true,
      customFieldType: 'datetime',
      flex: 1
    },
  ];
}

function GetData() {
  return [
    {
      id: 11,
      name: 'Trinesh Lokhande',
      email: 'trineshlokhande@gmail.com',
      created_on: '2024-01-20T17:28:27.000Z',
      updated_on: '2024-01-20T17:28:27.000Z'
    },
    {
      id: 12,
      name: 'Alice Smith',
      email: 'alice.smith@example.com',
      created_on: '2024-02-14T10:00:00.000Z',
      updated_on: '2024-02-14T10:00:00.000Z'
    },
    {
      id: 13,
      name: 'Bob Johnson',
      email: 'bob.johnson@company.com',
      created_on: '2024-03-01T12:34:56.000Z',
      updated_on: '2024-03-01T12:34:56.000Z'
    },
    {
      id: 14,
      name: 'Charlie Brown',
      email: 'charlie.brown@yahoo.com',
      created_on: '2023-12-25T08:00:00.000Z',
      updated_on: '2023-12-25T08:00:00.000Z'
    },
    {
      id: 15,
      name: 'David Lee',
      email: 'david.lee@hotmail.com',
      created_on: '2024-01-10T15:23:11.000Z',
      updated_on: '2024-01-10T15:23:11.000Z'
    },
    {
      id: 16,
      name: 'Emily Jones',
      email: 'emily.jones@organization.net',
      created_on: '2024-02-29T18:57:00.000Z',
      updated_on: '2024-02-29T18:57:00.000Z'
    }
  ];
}

export default function ControlledSelectionGrid() {
  const { data } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 10,
    maxColumns: 6,
  });

  const [rowSelectionModel, setRowSelectionModel] = React.useState([]);

  return (
    <div style={{ height: 500, width: '100%' }}>
      <DataGrid
        checkboxSelection
        onRowSelectionModelChange={(newRowSelectionModel) => {
          setRowSelectionModel(newRowSelectionModel);
        }}
        rowSelectionModel={rowSelectionModel}
        columns={GetDataDefinition()}
        rows={GetData()}
      />
    </div>
  );
}

### Current behavior

Step 1: Resize any column.
Step 2: Select any other row.
You will notice that the column size returns to its initial state.
This is because the state is controlled by state.
However, the column should not be resized.

### Expected behavior

The column should not be resized.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Controlled Selection, Column Resize

**Comment by michelengelen** [comment]
Please provide a **minimal** live reproduction test case with the latest version. This would help a lot 👷.

You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by michelengelen** [comment]
@trineshl from a quick glance this might be the problem:
```
columns={GetDataDefinition()}
rows={GetData()}
```
This is because every time you change the selection and pass it back into the grid these functions will re-run and give the same values as before overwriting the internal state.

If you memoize those values they should not reset the state anymore.
