### ISSUE TITLE
[pickers] AdapterMomentJalaali breaks when selecting date

### ISSUE THREAD

**Issue by Amin-Fathi** [mui/mui-x#12794]
### Related page

https://mui.com/x/react-date-pickers/calendar-systems/

### Kind of issue

Unclear explanations

### Issue description

I need example with AdapterMomentJalaali  , when use this library i have bug, when open modal calendar and click on the day this day convert to 1 and then not work any thing.   [Example problem](https://stackblitz.com/edit/vitejs-vite-nw71cx?file=src%2FApp.tsx)

 ![Screenshot 2024-04-16 111738](https://github.com/mui/mui-x/assets/17098100/a255847d-a88d-473b-ae31-eb6bd38eb002)

@types/moment-jalaali": "^0.7.9",
"moment": "^2.30.1",
 "moment-jalaali": "^0.10.0",
"@mui/lab": "^5.0.0-alpha.169",
 "@mui/material": "^5.15.14",
 "@mui/x-date-pickers": "^7.2.0",

 <LocalizationProvider dateAdapter={AdapterMomentJalaali}>
     <DatePicker    />
 </LocalizationProvider>

**Search keywords**: AdapterMomentJalaali

**Comment by michelengelen** [comment]
@LukasTy I am lost on this one 🤷🏼 Could you maybe provide some info?

**Comment by LukasTy** [comment]
> I am lost on this one 🤷🏼 Could you maybe provide some info?

I haven't investigated it yet.
Firstly, does it work on v6? 🤔

**Comment by Amin-Fathi** [comment]
Build sample for this 
[https://stackblitz.com/edit/vitejs-vite-nw71cx?file=src%2FApp.tsx](https://stackblitz.com/edit/vitejs-vite-nw71cx?file=src%2FApp.tsx)

**Comment by LukasTy** [comment]
@Amin-Fathi @michelengelen I've tracked down that the issue started happening from [v6.4.0](https://github.com/mui/mui-x/releases/tag/v6.4.0).
So, it looks like a regression. 🙈

**Comment by flaviendelangle** [comment]
I guess the main suspect is #8735 then :cry:

**Comment by shahlamahdavi68** [comment]
I have exactly this problem !
By selecting a date, it is not possible to change it and it will not work.
