### ISSUE TITLE
ChartsGrid import doesn't work

### ISSUE THREAD

**Issue by hugovialleix-iq-invest** [mui/mui-x#12803]
### Steps to reproduce

Link to live example: I can't get you a link because my app crash if I do it...

Steps:
1. Import the ChartsGrid component : https://mui.com/x/api/charts/charts-grid/
2. Add the line : import { ChartsGrid } from "@mui/x-charts"; to my file
3. Get error : the requested module '/node_modules/.vite/deps/@mui_x-charts.js?v=90e34882' does not provide an export named 'ChartsGrid'

### Current behavior

I have an import error

### Expected behavior

Don't have an import error

### Context

I want to display ChartsGrid on a ResponsiveChart but I can't import the ChartsGrid module

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

System:
    OS: macOS 14.4
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.124 -> the browser i use
    Edge: Not Found
    Safari: 17.4
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.15 
    @mui/icons-material: ^5.15.8 => 5.15.15 
    @mui/material: ^5.15.7 => 5.15.15 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-charts: ^6.19.8 => 6.19.8 
    @mui/x-data-grid: ^6.19.3 => 6.19.10 
    @mui/x-data-grid-pro: ^6.19.6 => 6.19.10 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.2.43 => 18.2.79 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
</details>

**Search keywords**: ChartsGrid
**Order ID**: 86307

**Comment by alexfauquette** [comment]
You are using the v6.19.8 version of charts. And the grid was added in the v7.0.0-beta.3

Updating to v7.0.0 should fix your issue
