### ISSUE TITLE
[data grid] Style is not working as it should be on filters

### ISSUE THREAD

**Issue by Davidna92** [mui/mui-x#12807]
### Steps to reproduce

As you can see in my picture:
![image](https://github.com/mui/mui-x/assets/63794877/3f78c4f9-f4b3-4323-873f-d7615f3efd80)

its not looks like its should be in your documentation 
what am I doing wrong here?

and another question regarding the filters, is it not possible to add a third filter with an operator of (OR/AND)? its always disabled

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: filters, style

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼

**Comment by michelengelen** [comment]
I can see that and did already assume that from the issue body, but for us to see and fix that we need to know your implementation and the styles applied. Otherwise this is a pure guessing game.
So please provide a minimal reproduction example and we are happy to help you!
