### ISSUE TITLE
[data grid] Column header doesn't have vertical borders on hover anymore with v7.2.0

### ISSUE THREAD

**Issue by sampain** [mui/mui-x#12815]
### Steps to reproduce

In the docs: https://mui.com/x/react-data-grid/#mit-version-free-forever
1. Put your mouse on the header of the DataGrid.

### Current behavior

v7.2.2 doesn't have a vertical border in the header anymore.
![7 2 2](https://github.com/mui/mui-x/assets/62195413/d46e2b3e-b570-43a7-81ef-e09a2d8d2085)

### Expected behavior

v7.1.1 had a vertical border in the header on hover.
![7 1 1](https://github.com/mui/mui-x/assets/62195413/5977e2ab-7ee4-4fab-bdd0-ea42e12999bb)

### Context

The vertical border is a great visual cue to know where to put the mouse to resize the columns, especially when disableColumnMenu = true.

Here is the change in a snapshot from v7.1.1 to 7.2.0:
![image](https://github.com/mui/mui-x/assets/62195413/7563786f-8943-4dad-a8a0-3e153895356e)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browser used: Chrome

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (123.0.2420.81)
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4
    @emotion/styled: 11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.15
    @mui/icons-material: 5.15.14 => 5.15.14
    @mui/material: 5.15.14 => 5.15.14
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system: 5.15.14 => 5.15.14
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid: 7.2.0 => 7.2.0
    @types/react: 18.2.67 => 18.2.67
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.4.3 => 5.4.3

```
</details>

**Search keywords**: vertical border

**Comment by MBilalShafi** [comment]
Hey @sampain,

THanks for reporting. The issue has already been reported in https://github.com/mui/mui-x/issues/12788 and fixed. The fix should be available in the next release.

**Comment by sampain** [comment]
> Hey @sampain,
> 
> Thanks for reporting. The issue has already been reported in #12788 and fixed. The fix should be available in the next release.

Hi. My issue is not with the column separators. I don't see how this issue is related.
