### ISSUE TITLE
DatePicker AdapterLuxon start day of the week with Sunday

### ISSUE THREAD

**Issue by georgesglynn** [mui/mui-x#12821]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Hello! I am a dev at Southwest Airlines and we have absolutely LOVED using the MUI package for our team's application.

We are currently on V4, I am working towards getting us upgraded to V5. This particular issue has been around for us since early last year but now that the DatePicker is under the lab package and I am currently working on migrating our implementation with https://material-ui-pickers.dev/ to the lab package I figure this would be a good time to bring this up.

Today, if you use the DatePicker component with the AdapterLuxon component as the LocalizationProvider, the week by default starts with Monday.

I tried to look into the AdapterLuxon code myself to see if I could customize it directly for our use case but I could not figure it out. Any guidance on this would be greatly appreciated!

### Examples 🌈

Screenshots for clarity:
(AdapterLuxon)
![image](https://user-images.githubusercontent.com/16637813/149169403-04adcc0c-e7f5-493c-96dd-c4adf26afdba.png)

(AdapterDateFns)
![image](https://user-images.githubusercontent.com/16637813/149169556-e7b8fd19-ef73-42d6-9f80-b6b103c040ff.png)

### Motivation 🔦

Our customers require this calendar to start with Sunday, but this component provides no customization to change this. That is my feature request, to add a prop to the DatePicker component that would allow you to change the starting day of the week.

Today since we primarily use Luxon, we have to convert every Luxon date that interacts with this DatePicker component to DateFns and use the AdapterDateFns in order to have the calendar start each week with Sunday. It is a lot of overhead/messy work.

**Search keywords**:

**Comment by ZeeshanTamboli** [comment]
@flaviendelangle I've moved the issue to the MUI X repository. Could you verify if it's still relevant?

**Comment by LukasTy** [comment]
Closing as a duplicate of https://github.com/mui/mui-x/issues/10805, which is already resolved with https://github.com/mui/mui-x/pull/10964 and is released starting from `v7.0.0-alpha.3`.
