### ISSUE TITLE
[question] stopCellEditMode does not trigger onCellEditStop of Data Grid

### ISSUE THREAD

**Issue by keso003** [mui/mui-x#12823]
### The problem in depth

I use autocomplete on the renderEditCell and on change it will update the value of the cell being edited just like on the sample here [https://mui.com/x/react-data-grid/style/#striped-rows](https://mui.com/x/react-data-grid/style/#striped-rows) the column for the **Country** but as per checking it does not trigger the **onCellEditStop** after editing the column, 

I tried to check the sample link above and add a console log on the onCellEditStop  and it is the same it doesn't trigger the property, below is the fork from the link above 
[https://stackblitz.com/edit/react-nqtbqa-duq6eu?file=Demo.js](https://stackblitz.com/edit/react-nqtbqa-duq6eu?file=Demo.js)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.123 (Official Build) (64-bit)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/core-downloads-tracker:  5.15.15
    @mui/icons-material: ^5.6.2 => 5.6.2
    @mui/material: ^5.15.15 => 5.15.15
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/x-data-grid-pro: ^7.2.0 => 7.2.0
    @mui/x-license: ^7.2.0 => 7.2.0
    @types/react:  17.0.38
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.1 => 5.3.3
    typescript:  4.8.4
```
</details>

**Search keywords**: stopCellEditMode, onCellEditStop
**Order ID**: 87978

**Comment by keso003** [comment]
found the answer for this [https://github.com/mui/mui-x/issues/8037#issuecomment-1446245154](https://github.com/mui/mui-x/issues/8037#issuecomment-1446245154)

**Comment by zphr** [comment]
The bug(?) that onCellEditStop does not fire when the Country cell is edited is still in version 8.5.1 of mui-data-grid. Here is an updated demo: 
https://stackblitz.com/edit/react-nqtbqa-sutk9frq?file=Demo.js

Additionally even in other cells where onCellEditStop is called it is getting the old data. Is this supposed to be like that?
