### ISSUE TITLE
[data grid] Cell's content overflown when row height is auto

### ISSUE THREAD

**Issue by ithrforu** [mui/mui-x#12842]
### Steps to reproduce

Link to live example: (required)
[Codesandbox](https://codesandbox.io/p/sandbox/auto-height-testing-j62v4j?file=%2Fsrc%2FGridDynamicRowHeight.tsx%3A29%2C4).

Steps:
1. Narrow the "rating" column.
2. Toggle "Change auto height mode" button.

### Current behavior

1. When row height auto is false `MuDatGrid-Cell` have properties:
```
overflow: hidden;
white-space: no-wrap;
```
![image](https://github.com/mui/mui-x/assets/81531000/a82b50b6-dab6-442d-b681-e5189db891f6)
2. When row height auto is true `MuDatGrid-Cell` does not have these properties and cell's content overflows the cell:
![image](https://github.com/mui/mui-x/assets/81531000/cf4b9908-bc03-435d-b8d6-a94d26264685)

### Expected behavior

 When row **height auto is true** `MuDatGrid-Cell` **should use** `overflow: hidden;`.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: rowHeight, rowHeight="auto", overflow, cell overflow, MuDatGrid-Cell
**Order ID**: 58079

**Comment by michelengelen** [comment]
Hey @ithrforu,
I cannot reproduce this issue. The grid in your example works just as expected:

https://github.com/mui/mui-x/assets/32863416/3c8fec14-77a4-49be-900d-c95e346a0300

Which browser are you using and did you try this in a different browser?

**Comment by ithrforu** [comment]
Hey, @michelengelen. 

The bug is reproduced in 6.19.6 ([codesandbox](https://codesandbox.io/p/sandbox/auto-height-testing-j62v4j?file=%2Fpackage.json)) and it is ok on the 7.3.0 version.

You can close the issue, thank you!

**Comment by michelengelen** [comment]
Thanks for the confirmation! 👍🏻
