### ISSUE TITLE
[pickers] `DateTimePicker` ok button text is not changing for dark theme 

### ISSUE THREAD

**Issue by amitconnectwise** [mui/mui-x#12841]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Context

datepicker ok button text color is not visible for dark theme
![Screenshot (96)](https://github.com/mui/mui-x/assets/154223309/f408fdc5-0559-4e14-be26-6232dd7531ea)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datepicker ok button

**Comment by michelengelen** [comment]
Hey @amitconnectwise ... The Button inside the actionbar are using the material-ui [Buttton](https://mui.com/material-ui/react-button/) component, so they will be impacted by the global theming. The text is readable just fine on the default themes, so if you provide a custom theme for your application you need to adjust the colors of that by yourself.

You can also override the styling with the `sx` prop on the actionBar using the `slotProps` on the DateTimePicker component:
```tsx
<DateTimePicker
  label="Date time picker"
  slotProps={{
    actionBar: {
      sx: (theme) => ({
        '& .MuiButton-root': {
          color: theme.palette.secondary.main,
        },
      }),
    },
  }}
/>
```

Does that solve your problem?

**Comment by amitconnectwise** [comment]
Yes, this solves the issue.
Thank you for your advice.



Amit Chavan

Software Engineer II
        [cid:connectwise-horiz-master_1cc2a50b-cea3-4ffe-898e-9a008013e641.png]  <https://www.connectwise.com>


***@***.***   +1 800-671-6898



connectwise.com<https://www.connectwise.com>


[https://www.connectwise.com/globalassets/media/email-signatures/iconfacebook.png] <https://www.facebook.com/ConnectWise>       [https://www.connectwise.com/globalassets/media/email-signatures/iconlinkedin.png]  <https://www.linkedin.com/company/ConnectWise>      [https://www.connectwise.com/globalassets/media/email-signatures/icontwitter.png]  <https://twitter.com/ConnectWise>


[cid:500x100-colleagueemailsignature_368f3e18-6566-4f48-a1c4-bff1f5aefa47.jpg]<https://www.connectwise.com/theitnation/secure/cybersecurity-conference><https://www.connectwise.com/theitnation/connect-na><https://www.connectwise.com/theitnation/connect-na><https://www.connectwise.com/theitnation/connect-na><https://www.connectwise.com/theitnation/connect-na><https://www.connectwise.com/theitnation/secure/cybersecurity-conference><https://www.connectwise.com/theitnation/secure/cybersecurity-conference><https://www.connectwise.com/theitnation/connect-emea>
<https://www.connectwise.com/platform>

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by michelengelen** [comment]
Great ... glad we could help you! 🎉
