### ISSUE TITLE
[tree view] Handle onClick on a RichTreeView item

### ISSUE THREAD

**Issue by rgavrilov** [mui/mui-x#12850]
### The problem in depth

I would like to configure my RichTreeView using its `items` property and then supply a handler that would receive a selected item.

```
 <RichTreeView items={treeViewItems} slots={{ item: TreeItem2 }} />
```

My current solution is to capture and store in a state the focused item, and then use that state from inside onClick attached to the tree item using slotProps={ item: { ...

Notice that my item has two pieces of information I need, so I have to combine them into a single string and then parse it out:

```
                onItemFocus={(e, itemId) => {
                    const [calculator, assetId] = itemId.split('/');
                    if (assetId) {
                        setSelectedResult(results[calculator][assetId]);
                    } else {
                        setSelectedResult(undefined);
                    }
                }}
```

```
                slotProps={{
                    item: {
                        onClick: () => {
                            if (selectedResult) {
                                modal.show(selectedResult);
                                ...
```

I know I can render TreeItem2 children explicitly, but that is not as neat.

Ideally, I would like to have `onItemClick` handler, similar to onItemFocus, that would receive the whole `item` from the `items` collection.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: RichTreeView
**Order ID**: 52426

**Comment by michelengelen** [comment]
@flaviendelangle should we keep this issue open to track the implementation of an `onItemClick` handler? Or will it be tracked on #12839?

**Comment by michelengelen** [comment]
Ok, in that case lets add this to the board as a feature request! 👍🏼

**Comment by Cadogantes** [comment]
+1, getting just a string with id instead of a selected item is quite inconvenient

**Comment by flaviendelangle** [comment]
@Cadogantes does this [doc section](https://mui.com/x/react-tree-view/rich-tree-view/items/#get-an-item-by-id) solve your problem?

If not, could you describe it more in depth so that we can adress it properly?

If it does, I think we will close this issue :+1:

**Comment by Cadogantes** [comment]
Oh yes, this seems to be a solution! Thanks!
