### ISSUE TITLE
[data grid] Sorting Removes Filtering

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#12854]
### The problem in depth

If I filter this table, then sort on another column, the filtering disappears and all the rows reappears. This is the code sandbox link: 
https://codesandbox.io/p/sandbox/sortandfilter-3vgm33?file=%2Fsrc%2FEntityLink.jsx%3A2%2C37

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Chrome Browser

System:
OS: Linux 3.10 CentOS Linux 7 (Core)
Binaries:
Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
npm: 7.24.2 - ~/node_modules/.bin/npm
pnpm: Not Found
Browsers:
Chrome: 120.0.6099.71
npmPackages:
@emotion/react: latest => 11.11.3
@emotion/styled: latest => 11.11.0
@mui/base: 5.0.0-beta.32
@mui/core-downloads-tracker: 5.15.5
@mui/icons-material: ^5.15.3 => 5.15.5
@mui/lab: ^5.0.0-alpha.159 => 5.0.0-alpha.161
@mui/material: ^5.15.3 => 5.15.5
@mui/private-theming: 5.15.5
@mui/styled-engine: 5.15.5
@mui/styles: ^5.15.3 => 5.15.5
@mui/system: 5.15.5
@mui/types: 7.2.13
@mui/utils: ^5.15.4 => 5.15.5
@mui/x-data-grid: 6.19.1
@mui/x-data-grid-generator: ^6.16.2 => 6.19.1
@mui/x-data-grid-premium: ^6.19.1 => 6.19.1
@mui/x-data-grid-pro: 6.19.1
@mui/x-license-pro: ^6.10.2 => 6.10.2
@types/react: 17.0.75
react: ^17.0.2 => 17.0.2
react-dom: ^17.0.2 => 17.0.2
styled-components: latest => 6.1.8
```
</details>

**Search keywords**: filtering sorting
**Order ID**: 66765

**Comment by lisaWriteJava** [comment]
In sandbox it seems to work as expected but in our code base sorting on a column other than the filtered one the filter is removed.

**Comment by michelengelen** [comment]
@lisaWriteJava Your guess seems about right. That would be the most logical cause for the described behavior.

Could you try replicating this as minimal as possible in the sandbox? As you already mentioned the current one seems to work as expected, so we cannot help you with this until we see the implementation and bug happening.

**Comment by lisaWriteJava** [comment]
I think that I figured it out. I had set the initial sort, on sort change and filterPanel and filter model, once I removed those all went well.

**Comment by lisaWriteJava** [comment]
I'm continnuing to test to see if the issue happens again.

**Comment by michelengelen** [comment]
Ok, great! Thanks for letting us know! 👍🏻
