### ISSUE TITLE
[data grid] Blank Space when scrolling Horizontally and Vertically

### ISSUE THREAD

**Issue by agarg-solveda** [mui/mui-x#12866]
### The problem in depth

Hi Team,
We are facing an issue while scrolling in the data grid(DataGridPro) Horizontally and Vertically.

![image](https://github.com/mui/mui-x/assets/158030342/fc5bb8c0-2918-48fe-9ac2-e50758bb9696)

Our project is currently not in public space so can't provide the link. But a similar [bug](https://github.com/mui/mui-x/issues/3436) is already there. https://github.com/mui/mui-x/issues/3436

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: scroll issue, mui data grid empty cells on scroll
**Order ID**: 88539

**Comment by michelengelen** [comment]
hey @agarg-solveda ... which data grid version are you using?

Can you maybe provide a minimal reproduction for this? I cannot see this happening in our docs or sandbox examples, even with increasing the data set to ~100.000 rows

**Comment by agarg-solveda** [comment]
hey we are using "@mui/x-data-grid-pro": "^7.2.0",

Our project is in the development phase and not available in the public domain. Can I share the video recording of the error?

Is there any possibility of having the team call for a faster resolution of issue?

**Comment by michelengelen** [comment]
@agarg-solveda we do not do live debug sessions.

But I've got a few questions to narrow down the problem:
1. Are you using lazy loading of some sort?
2. is there an error thrown in console when this happens?
3. is it happening on a specific set of data?
4. are you using custom cell rendering or data alteration of some sort?
