### ISSUE TITLE
[pickers] How to display selected years in the toolbar format ?

### ISSUE THREAD

**Issue by hdale94** [mui/mui-x#12878]
### The problem in depth

Hello,

I was wondering if it's possible to display the selected years in the StaticDateRangePicker-component?

Currently, it only shows the selected month and day (Apr 17 - Apr 21), which is a bit problematic if the selected range spans across different years.

![Screenshot 2024-04-23 at 13 33 27](https://github.com/mui/mui-x/assets/77438639/7e06d081-41b8-4f1a-be42-d0a9a2043755)

https://mui.com/x/react-date-pickers/date-range-picker/

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: static date range picker
**Order ID**: 83335

**Comment by flaviendelangle** [comment]
Hi,

You can use the `toolbarFormat` of the `toolbar` slot to change the format used for this part of the UI.
It is demonstrated [here](https://mui.com/x/react-date-pickers/adapters-locale/#custom-toolbar-format) on a Date Picker but will work fine on range pickers are well.
