### ISSUE TITLE
[TreeView] Support parent / children selection relationship

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#12883]
# Related issues 

- #12802

# Current behavior

In the current implementation of the Tree View component (both `SimpleTreeView` and `RichTreeView`), selecting an item does not select its children and selecting all children of an item does not select its parent.

The behavior is exactly the same with checkbox selection.

**Selecting a parent (single select)**

![image](https://github.com/mui/mui-x/assets/3309670/fc24fb26-d25e-41f8-866e-7001f82e8aa5)

Model value: `"A"`

**Selecting a leaf (single select)**

![image](https://github.com/mui/mui-x/assets/3309670/7658a6af-7f84-4229-bcd4-09d5deb10571)

Model value: `"A1"`

**Selecting a parent (multi select)**

Here is what the result is when you click on `"A"`:

![image](https://github.com/mui/mui-x/assets/3309670/fc24fb26-d25e-41f8-866e-7001f82e8aa5)

Model value: `["A"]`

**Selecting a leaf (multi select)**

Here is what the result is when you click on `"A1"`:

![image](https://github.com/mui/mui-x/assets/3309670/7658a6af-7f84-4229-bcd4-09d5deb10571)

Model value: `["A1"]`

**Selecting all leaves of an item**

Here is what the result is when you click on `"A1"` then click on `"A3"` while pressing <kbd>Shift</kbd>:

![image](https://github.com/mui/mui-x/assets/3309670/a2be6126-5f2a-420e-91cf-df2c6b4f719d)

Model value: `["A1", "A2", "A3"]`

# Alternatives model

## Model contains the selected leaves and the parent selection is deduced from their descendants

Based on https://github.com/mui/mui-x/pull/11452#issuecomment-2009687309

The following model can only work in multi selection.
The idea here is to only apply the selection on the leaves and then deduce the visual selection of the parents based on the selection status of their descendants:

- every descendant selected: selected
- some descendant selected: partially selected
- no descendant selected: not selected

**Selecting a parent (multi select)**

Here is what the result is when you click on `"A"`:

![image](https://github.com/mui/mui-x/assets/3309670/a066dd89-f7bc-41eb-a8d7-7794aa7bb9dc)

Model value: `["A1", "A2", "A3"]`

**Selecting a leaf (multi select)**

Here is what the result is when you click on `"A1"`:

![image](https://github.com/mui/mui-x/assets/3309670/b306838b-223a-43f0-9512-de7744eb0fb4)

Model value: `["A1"]`

**Selecting all leaves of an item**

Here is what the result is when you click on `"A1"` then click on `"A3"` while pressing <kbd>Shift</kbd>:

Model value: `["A1", "A2", "A3"]`

![image](https://github.com/mui/mui-x/assets/3309670/3649a96f-f29f-439f-85ea-390642740f3d)

## Keep the model as is but visually select a children if one of its ancestors is selected

Based on https://github.com/mui/mui-x/pull/11452#issuecomment-2071989301

The following model can work in both single and multi selection.
The idea here is to visually select an item if it is selected in the model or if one of its ancestor is selected.

It might not work well with the checkbox where people probably expect the parent checkbox to change its status when selecting the children.

**Selecting a parent (single select)**

![image](https://github.com/mui/mui-x/assets/3309670/ff45cfb8-f7ed-4bba-a48d-b67573ff1c0d)

Model value: `"A"`

**Selecting a leaf (single select)**

![image](https://github.com/mui/mui-x/assets/3309670/7658a6af-7f84-4229-bcd4-09d5deb10571)

Model value: `"A1"`

**Selecting a parent (multi select)**

Here is what the result is when you click on `"A"`:

![image](https://github.com/mui/mui-x/assets/3309670/92229c84-bfe6-45e5-8a48-f81cfe18fc90)

Model value: `["A"]`

**Selecting a leaf (multi select)**

Here is what the result is when you click on `"A1"`:

![image](https://github.com/mui/mui-x/assets/3309670/7658a6af-7f84-4229-bcd4-09d5deb10571)

Model value: `["A1"]`

**Selecting all leaves of an item**

Here is what the result is when you click on `"A1"` then click on `"A3"` while pressing <kbd>Shift</kbd>:

![image](https://github.com/mui/mui-x/assets/3309670/a2be6126-5f2a-420e-91cf-df2c6b4f719d)

Model value: `["A1", "A2", "A3"]`

# Benchmarks

- https://johnnyreilly.com/mui-react-tree-view-check-children-uncheck-parents

**Search keywords**:

**Comment by flaviendelangle** [comment]
If you have other approaches that you saw on other Tree View (or similar component) I would be super interested.
When we will have a good understanding of what exists, we will be in a better position to decide what we want to implement (it might be several approaches and let people switch between them).

I still need to explore how the various approaches work with lazy loading (which we want to support eventually).

**Comment by LukasTy** [comment]
I'll just re-post the community members' suggested example: https://primereact.org/treeselect/#check
IMHO, it's a good role model checkbox selection behavior-wise.

Regarding our implementation, I think it should be highly flexible to cover various use cases.

**Comment by Aberkati** [comment]
> I'll just re-post the community members' suggested example: https://primereact.org/treeselect/#check IMHO, it's a good role model checkbox selection behavior-wise.
> 
> Regarding our implementation, I think it should be highly flexible to cover various use cases.

It's a very good example, hopefuly we get a similar with MUIX

**Comment by flaviendelangle** [comment]
> I'll just re-post the community members' suggested example: https://primereact.org/treeselect/#check

In term of behaviors, this looks a lot like 

If I understand correctly, with this approach you change the structure of the model to look something like "Model contains the selected leaves and the parent selection is deduced from their descendants" described above **BUT** with both the children and the parent represented in the model.

```js
{
    '0-0': {
        partialChecked: false,
        checked: true
    }
}
```

With this approach, if I understand correctly, the model describes what is selected (fully selected, partially selected or not selected) item by item without any parent / children relationship.
And the UI actions (clicking on an item, clicking on a checkbox, etc...) updates the model and selects children and/or parent based on the selection rule we want (might have some parent / children relationship, might not).


_____

That could be an interesting approach.
I'm not a huge fan of the shape of the model (having a boolean when not using checkbox and this two-properties object when using them) but this could be adapter.

One could say that this model structure is super flexible since it lets the model remain the same with different selection behaviors.
You always have the same model with every item selected and based on some prop you can change which item are added to the model when selecting an item.

The only weakness I can see is that if someone control the model, there is no guarantee that he passes a model value that is coherent with the selection mechanism in place in his app.
For instance, he configures the Tree View to automatically selects the children when selecting a parent. So when you click `A`, it calls the `onSelectedItemsChange` with `["A", "A1", "A2", "A3"]`.
But based on some external UI he updates `props.selectedItems` and passes `["A1", "A2", "A3"]` to the Tree View.
This would visually select `"A1"`, `"A2"` and `"A3"` which is a selection state you can never achieve through interactions with the Tree View.

As long as we agree that this is not a problem, this looks like a very flexible approach.

**Comment by flaviendelangle** [comment]
Side note, I am not a fan of array model at all (or performance reasons mainly).
So if the parent / children selection relationship is an opportunity to move to an object model I'm all in favor of doing it.

**Comment by joserodolfofreitas** [comment]
DataGrid is also aiming to [support this feature soon](https://github.com/mui/mui-x/issues/4248), so it'd be good for us to keep aligned on the DevEx.

**Comment by oliviertassinari** [comment]
(coming from seeing the tweet https://twitter.com/MUI_hq/status/1793654965996823022)

I suspect that the "Checkbox" selection should be a separate feature from "Selection". I mean to have a separate state. I can see the use case for end-users to check items, the items they want to delete, while having another item selected to be expanded on a right panel. 

If we benchmark from https://www.notion.so/mui-org/mui-x-Tree-View-component-c283f4a957474b79b293e994881b1ee8. 

It seems that those behaving like it (independent):

- https://ant.design/components/tree
- https://www.jqwidgets.com/react/react-tree/index.htm#https://www.jqwidgets.com/react/react-tree/react-tree-checkboxes.htm
- https://demos.telerik.com/kendo-ui/treeview/checkboxes
- https://ej2.syncfusion.com/react/demos/#/material/treeview/check-box
- https://www.igniteui.com/tree/drag-and-drop-single-tree
- https://examples.sencha.com/extjs/7.8.0/examples/kitchensink/#check-tree
- https://dgreene1.github.io/react-accessible-treeview/docs/examples-MultiSelectCheckbox

I see those with separate states, but where selection triggers checkbox selection and checkbox selection triggers selection:

- https://rsuitejs.com/components/check-tree/

I see those that have selection disabled when checkbox selection is enabled:

- https://js.devexpress.com/React/Demos/WidgetsGallery/Demo/TreeView/ItemSelectionAndCustomization/Light/

I see those that have checkbox selection meaning selection but selection still being independent.

- https://wwwendt.de/tech/fancytree/demo/#sample-select.html

I see behaving like in #11452:

- https://www.jstree.com/

**Comment by johnnyreilly** [comment]
Awesome to see this looks like it's getting given native support! If anyone wants to this behaviour now, it is hand rollable and I've documented it here:

https://johnnyreilly.com/mui-react-tree-view-check-children-uncheck-parents

Brilliant to see that this is likely to be obsolete very soon!

**Comment by johnnyreilly** [comment]
`defaultSelectedItems` is for uncontrolled components I think? My example is using the controlled component behaviour for selection. Do you want to try setting the initial state using `setSelectedIds` instead?

**Comment by flaviendelangle** [comment]
`defaultSelectedItems` is for un-controlled components
For controlled ones, you can use `selectedItems` and `onSelectedItemsChange`

**Comment by Skykingeagle** [comment]
> `defaultSelectedItems` is for un-controlled components
> For controlled ones, you can use `selectedItems` and `onSelectedItemsChange`

How would I limit these checkboxes to certain nodes? For example if I only wanted the checkbook selection to be true for the leaf nodes only, how would I be able to do that?

**Comment by flaviendelangle** [comment]
Right now we have no way of doing it easily.
The data grid has a [`isRowSelectable` prop](https://mui.com/x/react-data-grid/row-selection/#disable-selection-on-certain-rows) that we could replicate on the Tree View components to limit the selection to certain rows.

**Comment by johnnyreilly** [comment]
Just a heads up that I found and fixed a bug in my handrolled logic last night.  I've updated the [blog post](https://johnnyreilly.com/mui-react-tree-view-check-children-uncheck-parents) and the [StackBlitz](https://stackblitz.com/edit/mui-react-tree-view-check-children-uncheck-parents?file=Demo.tsx)

If anyone is curious as to the fix, see here:

https://github.com/johnnyreilly/blog.johnnyreilly.com/commit/f32576210635e53b10f4b596068b0f417fedda03

**Comment by johnnyreilly** [comment]
And one more fix! (previous code didn't walk the tree all the way to the top when reselecting from a leaf node). Blog post updated; fix is here:

https://github.com/johnnyreilly/blog.johnnyreilly.com/commit/908bdf0c9f42faa20ffe4119baf4be16fb51f6b9

**Comment by Aberkati** [comment]
> And one more fix! (previous code didn't walk the tree all the way to the top when reselecting from a leaf node). Again I've updated the [blog post](https://johnnyreilly.com/mui-react-tree-view-check-children-uncheck-parents) and the [StackBlitz](https://stackblitz.com/edit/mui-react-tree-view-check-children-uncheck-parents?file=Demo.tsx)
> 
> The fix for this issue can been seen in this commit:
> 
> [johnnyreilly/blog.johnnyreilly.com@908bdf0](https://github.com/johnnyreilly/blog.johnnyreilly.com/commit/908bdf0c9f42faa20ffe4119baf4be16fb51f6b9)

Great!! I'm trying to add a input field on top of this component to filter my nodes but seems to be hard, have you an idea how to achieve it please ? this an example demo link : https://stackblitz.com/edit/bgcued-tebqqr?file=src%2FApp.jsx,package.json
Thank you!

**Comment by Aberkati** [comment]
> `defaultSelectedItems` is for un-controlled components For controlled ones, you can use `selectedItems` and `onSelectedItemsChange`

Yes I've tried it and it works, but the problem is when I select a parent id as selected onmount his leaf are uncheked..
Please take a look here : 
![image](https://github.com/mui/mui-x/assets/62659391/db16ba21-c41e-4843-8d68-9e76ffa444ae)

**Comment by brammitch** [comment]
I stumbled across this issue while trying to implement this myself, so I thought I'd share a [minimal example](https://github.com/DevalexLLC/mui-tree-parent-child-indeterminate-checkbox-demo) of how I did it for a project.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/~/fork/github/DevalexLLC/mui-tree-parent-child-indeterminate-checkbox-demo?file=src%2FApp.tsx)

![image](https://github.com/user-attachments/assets/730336e9-7bd4-421b-91c1-c6e0c872a163)
