### ISSUE TITLE
[data grid] How to initialize empty rows like Google Sheets

### ISSUE THREAD

**Issue by louisaaron** [mui/mui-x#12886]
### The problem in depth

We're trying to initialize a datagrid with many empty rows, much like Google Sheets. Our grid is socketed so that live updates come through much like Google Sheets, but data is stored in rows in Postgres. We want to automatically generate a new row each time data is populated in an empty row (and to delete rows when a row becomes empty again).

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Initialize empty rows
**Order ID**: 85118

**Comment by DanailH** [comment]
Hey @louisaaron that's an interesting use case. Technically you can do that by providing the grid with empty rows. You would then need to update the rows you provide via the API - you can check an example of how to do that here: https://mui.com/x/react-data-grid/row-updates/#high-frequency

Regarding generating a new row each time data is populated in a new row - you can do that as well by appending a new empty [row to the row model](https://mui.com/x/react-data-grid/editing/#full-featured-crud)

**Comment by louisaaron** [comment]
Thanks!

**Comment by michelengelen** [comment]
@louisaaron does the proposed solution fit yur use-case? If so please feel free to close this issue! Thanks! 🙇🏼

**Comment by louisaaron** [comment]
We haven't had a chance to try it out yet but will close unless we have an issue. thanks
