### ISSUE TITLE
[data grid] Synk Vulnerability

### ISSUE THREAD

**Issue by satinder1624** [mui/mui-x#12887]
Hello I am getting a vulnerability error on Synk
@mui/x-data-grid-generator@5.17.26 › @mui/x-data-grid-premium@5.17.26 › exceljs@4.4.0 › archiver@5.3.2 › archiver-utils@2.1.0 › glob@7.2.3 › inflight@1.0.6

Can anyone tell how I can solve this issue?

Thank you

**Search keywords**:

**Comment by michelengelen** [comment]
@satinder1624 as @LukasTy we cannot do anything on our end. We just import and use the `exceljs` package which has the vulnerability. You can add the workaround provided by @LukasTy and ideally open an issue on the [exceljs repo](https://github.com/exceljs/exceljs) for them to update the dependency list or upvote the [existing issue](https://github.com/exceljs/exceljs/issues/2715).
