### ISSUE TITLE
[data grid] Sorting in not working when we click on up arrow icon

### ISSUE THREAD

**Issue by vikash-verma-egon** [mui/mui-x#12890]
### Steps to reproduce

Link to live example: (required)

Steps:
1.Go to grid click on top arrow.
2.click again don't move your mouse from arrow. do will sort in desc order
3.click again now it will be idle it will sort your grid in asc
4. click again now it will start working

### Current behavior

its not sorting the grid in asc order

### Expected behavior

It should sort

### Context

It is related to mui-grid-pro

### Your environment

npx @mui/x-data-grid-pro ^6.19.5

**Search keywords**: Sorting in not working when we click on up arrow icon
**Order ID**: 69943

**Comment by vikash-verma-egon** [comment]
https://github.com/mui/mui-x/assets/167959457/4e00238c-426b-4c1a-bab0-376943b56a52

Attached is the recording

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
