### ISSUE TITLE
[data grid] Grid menu component customisation

### ISSUE THREAD

**Issue by trbagley-gresham** [mui/mui-x#12902]
### The problem in depth

Is it possible to change the type of component that is rendered for menu poppers via a slot prop? The motivation is to have more control over where the menu is positioned by changing the _Popover_ to a _Popper_ and using the `anchorPosition` prop. I've tried passing a _Popover_ to `basePopper`, but trying to render `children` is problematic as they are wrapped by a transition in _GridMenu_.

Perhaps the changes discussed in the PR linked below will provide more flexibility?
https://github.com/mui/mui-x/issues/12568

**Search keywords**: menu popper slot
**Order ID**: 45466

**Comment by michelengelen** [comment]
This is still doable. Check out this demo.
Be aware that this is not production ready as the position gets updated even when the popper is open. Also you would want to only update the anchor element for specific use-cases (I guess).

[Popper placement on cursor](https://codesandbox.io/p/sandbox/strange-agnesi-8dgpvw)

Would that help in your case?

**Comment by michelengelen** [comment]
I assume this can be closed now.
Feel free to reopen if you encounter problems with this.
