### ISSUE TITLE
[data grid] Row does not get selected when clicking on action cell

### ISSUE THREAD

**Issue by dassoumyashree** [mui/mui-x#12911]
### Steps to reproduce

Link to live example: (required)

Steps:
1. click on any cell of the data-grid, the entire row will get selected and a background color will get applied on that selected row
2. now click anywhere inside grid action cells (where column type is 'action'), the row will not get selected and there will be no row highlight, means no change in background color for that row.

### Current behavior

clicking on cells of type 'action' does not select the row

### Expected behavior

like how on clicking on cells with other types the entire row gets selected and highlighted, action cells should also allow the same behaviour.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: gridactioncell, row selection

**Comment by michelengelen** [comment]
Hey @dassoumyashree and thanks for raising an issue here.
As far as I am concerned I would not expect the row to be selected when clicking inside an actions cell. Is there a specific use case you need this for?

WDYT @MBilalShafi ?
