### ISSUE TITLE
[data grid] pagination add jump input

### ISSUE THREAD

**Issue by langziyang** [mui/mui-x#12928]
### Summary

table pagination and datagrid pagination or signle pagtination.add textfiled call jump to page,

### Examples

![image](https://github.com/mui/mui-x/assets/2345387/64665880-afa0-49dd-8064-8ed079145b42)

**Search keywords**: jump to page

**Comment by michelengelen** [comment]
You would have to apply a custom pagination component.

Here is an example: [Custom pagination with goto page input](https://codesandbox.io/p/sandbox/quizzical-blackwell-y8tl22)

Does that help you?
