### ISSUE TITLE
[charts] Border radius on bar chart: alternative when bars are stacked?

### ISSUE THREAD

**Issue by nina-alin** [mui/mui-x#12947]
### Summary

Hello! 

On this page of your documentation, you give an example of applying border radius on the bar chart : https://mui.com/x/react-charts/bars/#border-radius. You also say: "[Stacking](https://mui.com/x/react-charts/bars/#stacking) won't look right with border radius." I tried with other ways, but always ended up with a disappointing result.

My use case is that I have stacked bars (2 or 3, depends on the data) and I want **only** the upper one to be rounded.

Do you have any alternatives?

### Examples

I'm looking for this result: 

![image](https://github.com/mui/mui-x/assets/56309556/a6eae50b-f29e-4967-99ab-7c0344d4122e)

**Search keywords**: bar slot border radius stacked

**Comment by michelengelen** [comment]
We are working on this in #12834 ... this should provide a more profound way of adding rounded corners to bar charts

cc @JCQuintas
