### ISSUE TITLE
[data grid] Column autosizing calculated on old data instead of new data

### ISSUE THREAD

**Issue by Frooons** [mui/mui-x#12940]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-e7tkn5?file=Demo.tsx

### Current behavior

The community version of data grid uses the old data set to set the `--DataGrid-rowWidth` css variable when using the autosizeColumns functionality, resulting in inconsistencies between the header and data rows.

**Row exceeds header length:**
<img width="350" alt="image" src="https://github.com/mui/mui-x/assets/6704122/d7c894da-d8c0-4453-a046-29449a543095">

**Header exceeds row length:**
<img width="176" alt="image" src="https://github.com/mui/mui-x/assets/6704122/c91171e0-894c-4500-89de-4e85d32fcbfb">

The pro version does set the `--DataGrid-rowWidth` based on the new data, as shown in the screenshot below. The pro version above the community version below, both using the same data but different widths:
<img width="283" alt="image" src="https://github.com/mui/mui-x/assets/6704122/7ea85c44-0d1a-4d08-b37d-8b37392d54ac">

### Expected behavior

The community version should also set the `--DataGrid-rowWidth` based on the new data just like the pro version does.

### Context

The live example is a fork of [autosizing asynchronously](https://mui.com/x/react-data-grid/column-dimensions/#autosizing-asynchronously) with extended data and the community version added below to the pro version, both use the same logic to retrieve the data and execute the autosizeColumns.

With the browser inspector open, clicking the refresh button I see the style attribute of the `MuiDataGrid-root` div refreshed immediately for the community version which is too soon. With the pro version the style attribute of the `MuiDataGrid-root` div is refreshed after the new data is loaded.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 125.0.6422.113
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.17 
    @mui/icons-material:  5.15.17 
    @mui/lab:  5.0.0-alpha.170 
    @mui/material:  5.15.17 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.4.0 
    @mui/x-date-pickers:  7.4.0 
    @types/react:  18.3.2 
    react:  18.3.1 
    react-dom:  18.3.1 
    typescript: >=5.4.5 => 5.4.5 
```
</details>

**Search keywords**: Autosizing

**Comment by romgrk** [comment]
I'm unable to reproduce an issue with the steps above, would it be possible to explain which steps to take to experience any of the issues you list?

**Comment by Frooons** [comment]
Please have a look at the example here https://stackblitz.com/edit/react-e7tkn5. After retrieval of the data the CSS var `--DataGrid-rowWidth` should be calculated and set based on the widest row. The pro version does this correctly but the community version sets the `--DataGrid-rowWidth` based on the widest row of the old data and not of the newly retrieved data. 

Some examples:

First data retrieval after opening the example, the header and hover backgrounds of the community version do not cover the "Branding", "Representative" and "Rating" columns on the far right:
<img width="491" alt="image" src="https://github.com/mui/mui-x/assets/6704122/688ac6e2-8f3d-4ab6-bab0-e5edc63961a9">

After clicking refetch data, 
either the widest row is smaller thus the header and hover backgrounds exceed the widest row (the row underline does not cover the full width)
<img width="327" alt="image" src="https://github.com/mui/mui-x/assets/6704122/76337273-fac3-4b38-b545-894f1956ee1f">

or the widest row is wider thus the header and hover backgrounds does not cover the "Rating" column on the far right:
<img width="258" alt="image" src="https://github.com/mui/mui-x/assets/6704122/20d465f0-35fb-42a6-b264-5dd7dcd6148b">

**Comment by romgrk** [comment]
Still can't reproduce, can you fill the env info section? You have the instructions in the top comment.

**Comment by Frooons** [comment]
I have added the env info section in the top comment

**Comment by romgrk** [comment]
@mui/xgrid Can someone on macOS take this one? Might have an impact.

**Comment by MBilalShafi** [comment]
> @mui/xgrid Can someone on macOS take this one? Might have an impact.

I'll check it out.

**Comment by MBilalShafi** [comment]
After a few tries, I was finally able to reproduce this error. It didn't reproduce so easily for me.

To reproduce I needed to meet these conditions:
1. Use one of Edge or Safari browsers
2. It only reproduces on a specific screen width (roughly when 4 columns are visible after `autoSize`) I needed to resize the window several times to reproduce.

When it reproduces, this `useEnhancedEffect` doesn't get triggered after the `autosizeColumns` action.
https://github.com/mui/mui-x/blob/7566a1d82682fbeaf294b98ee246de1b93966e3f/packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts#L306-L324

But since the `autosizeColumns` has already resized the individual columns, it yields a weird UX.

@Froons can you reproduce it consistently or on a specific screen width? Also which browser do use to reproduce it?

**Comment by Frooons** [comment]
@MBilalShafi To answer the first question, I am able to reproduce it consistently using Chrome and Safari where the table has to be wider than the screen width.
And for the second question, the issue does not reproduce for me anymore in the codesandbox!
