### ISSUE TITLE
[data grid] Column resizing not working with special characters in column names

### ISSUE THREAD

**Issue by cloudcode-hungary** [mui/mui-x#12954]
### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/p/sandbox/wild-surf-ygtjk6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvmizlgf0007356oyhqah7kd%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvmizlgf0003356o43irewy5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvmizlgf0004356o8aweeoi9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvmizlgf0006356oks6s70rv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvmizlgf0003356o43irewy5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvmizlgf0002356osegu262v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A55%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A55%257D%255D%257D%255D%252C%2522id%2522%253A%2522clvmizlgf0003356o43irewy5%2522%252C%2522activeTabId%2522%253A%2522clvmizlgf0002356osegu262v%2522%257D%252C%2522clvmizlgf0006356oks6s70rv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvmizlgf0005356o7z66vyny%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvmizlgf0006356oks6s70rv%2522%252C%2522activeTabId%2522%253A%2522clvmizlgf0005356o7z66vyny%2522%257D%252C%2522clvmizlgf0004356o8aweeoi9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvmizlgf0004356o8aweeoi9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Forked from here: [https://mui.com/x/react-data-grid/](https://codesandbox.io/s/33xpq2?file=/src/Demo.tsx)

Steps:
1. Add a column with a `"` character in the field name.
2. Try to resize the column.
3. No resizing happens, the console shows this error:

```
SyntaxError
Failed to execute 'querySelector' on 'Element': '[data-field="firstName="first_name""]' is not a valid selector.
```

### Current behavior

Not documented, no warning or error on the invalid column names.

### Expected behavior

```querySelector(`[data-field="${colDef.field}"]`)``` should be ```querySelector(`[data-field="${colDef.field.replace('"', '\\"')}"]`)```

There could be some more cases

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#escaping_special_characters

### Context

We have a very complex column management system, some columns contain very specific configuration of the data which is evaulated by the backend, e.g: `sales_statistics.$alias/order_created_date="this_week",warehouse="1,3"/quantity`

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v18.11.0/bin/yarn
    npm: 6.14.18 - ~/clouderp/node_modules/.bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.9.0 => 11.10.5
    @emotion/styled: ^11.8.1 => 11.10.5
    @mui/base:  5.0.0-alpha.116
    @mui/core-downloads-tracker:  5.11.7
    @mui/icons-material: ^5.6.2 => 5.11.0
    @mui/lab: ^5.0.0-alpha.81 => 5.0.0-alpha.118
    @mui/material: ^5.7.0 => 5.11.7
    @mui/private-theming:  5.11.7
    @mui/styled-engine:  5.11.0
    @mui/styled-engine-sc: ^5.7.0 => 5.11.0
    @mui/styles: ^5.7.0 => 5.11.7
    @mui/system:  5.11.7
    @mui/types:  7.2.3
    @mui/utils:  5.11.7
    @mui/x-data-grid:  6.3.0
    @mui/x-data-grid-pro: ^6.3.0 => 6.3.0
    @mui/x-date-pickers:  6.3.0
    @mui/x-date-pickers-pro: ^6.3.0 => 6.3.0
    @mui/x-license-pro:  6.0.4
    @types/react:  18.0.27
    react: 18.1.0 => 18.1.0
    react-dom: 18.1.0 => 18.1.0
    styled-components: ^5.3.5 => 5.3.6

Google Chrome - Version 124.0.6367.91
```
</details>

**Search keywords**: Column resize querySelector DomException escape

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @cloudcode-hungary ... thanks for raising this.

We could escape the `"` character here, so that it does not mess with the selector:

```diff
diff --git a/packages/x-data-grid/src/utils/domUtils.ts b/packages/x-data-grid/src/utils/domUtils.ts
index dd27e95e5..077314f30 100644
--- a/packages/x-data-grid/src/utils/domUtils.ts
+++ b/packages/x-data-grid/src/utils/domUtils.ts
@@ -68,7 +68,7 @@ export function getFieldFromHeaderElem(colCellEl: Element): string {
 }

 export function findHeaderElementFromField(elem: Element, field: string): HTMLDivElement {
-  return elem.querySelector(`[data-field="${field}"]`)!;
+  return elem.querySelector(`[data-field="${field.replaceAll('"', '\\"')}"]`)!;
 }

 export function getFieldsFromGroupHeaderElem(colCellEl: Element): string[] {
```

WDYT @romgrk ?
