### ISSUE TITLE
[data grid] Is there a way to update a single ColDef without triggering a re-render of every cell?

### ISSUE THREAD

**Issue by tomekpaszek** [mui/mui-x#12952]
### The problem in depth

Hi!
I'm customizing the grid in order to have column highlighting. The implementation seems pretty straightforward as I'm adding a custom field to the column definition (`highligted`) and updating the columns when needed. I use [updateColumns](https://mui.com/x/api/data-grid/grid-api/#grid-api-prop-updateColumns) to update a single column, however, that triggers a re-render of every cell. 
Is there a way to avoid that and only re-render the updated column? 

### Your environment

System:
    OS: macOS 14.4.1
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 124.0.6367.93
    Edge: 124.0.2478.67
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.26
    @mui/core-downloads-tracker:  5.15.11
    @mui/lab: 5.0.0-alpha.155 => 5.0.0-alpha.155
    @mui/material: 5.14.20 => 5.14.20
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid-pro: ^7.3.1 => 7.3.1
    @mui/x-license:  7.2.0
    @types/react: ^18.0.14 => 18.2.61
    react: ^18.2.0 => 18.2.0
    react-dom: ~18.2.0 => 18.2.0
    typescript: ^5.0.2 => 5.3.3

**Search keywords**: updateColumns render
**Order ID**: 78765

**Comment by tomekpaszek** [comment]
Hi,
Thanks for your reply. The way I'm using the DataGrid is to render a matrix of results with ~5000 rows and 30-100 column. There is maybe ~1500 cells rendered at a time. We use custom renderers and DataGrid does a great job with virtualization so there is no problems with performance when without the column highlighting. 
When issue comes when we're updating the columns with GridApi and that updating a single column would trigger a repaint of all visible cells. I don't see a need to repaint every cell in a case, where, let's say I only want to update the header of a column. 
If needed I can provide with a working example to clarify it.

**Comment by romgrk** [comment]
If you can provide an example that showcases a performance degradation, that would help us prioritize the issue. We have been working on performance optimization but we tend to focus on areas where the UX is noticeably affected. But yes in an ideal world the cells would not re-render when a column is changed.

**Comment by tomekpaszek** [comment]
Here is a live example: [link](https://codesandbox.io/p/sandbox/friendly-montalcini-yfkfvd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvp9gzpy00063b6n59f3j5c2%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvp9gzpy00023b6n5loszfba%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvp9gzpy00033b6nw5881dzl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvp9gzpy00053b6ntga5znak%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvp9gzpy00023b6n5loszfba%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvp9gzpy00013b6nr8ugrsg8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvp9gzpy00023b6n5loszfba%2522%252C%2522activeTabId%2522%253A%2522clvp9gzpy00013b6nr8ugrsg8%2522%257D%252C%2522clvp9gzpy00053b6ntga5znak%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvp9gzpy00043b6nlv4hblmc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvp9gzpy00053b6ntga5znak%2522%252C%2522activeTabId%2522%253A%2522clvp9gzpy00043b6nlv4hblmc%2522%257D%252C%2522clvp9gzpy00033b6nw5881dzl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvp9gzpy00033b6nw5881dzl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
Try hovering across the header titles and see the highlighted column lagging behind. It's not the case for the highlighted row.

**Comment by romgrk** [comment]
I have opened the PR linked above to fix the issue, but fwiw I think you should use the DOM APIs directly rather than changing the column. Add/remove an attribute like `data-column-hover` on mouse enter/leave, with `[data-column-hover] { background-color: grey; }`. I think react is too slow to deal with hover events in a satisfying manner. We used to go through react for pinned rows hover events in the past and I would sometimes see a bit of latency even on my fast laptop.
