### ISSUE TITLE
[fields] hitting "enter" on keyboard does not submit HTML form

### ISSUE THREAD

**Issue by davevanhoorn** [mui/mui-x#12964]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/devbox/nextjs-mui-datepicker-mgh2qy

### Current behavior

When focused on a `DatePicker` field, hitting `enter` on the keyboard won't submit a form

### Expected behavior

When focused on a `DatePicker` field, hitting `enter` should submit a form

### Context

It seems the following code in `useField.ts` ([here](https://github.com/mui/mui-x/blob/58f1859119c4df451bf80db1c40d40ce0c9c1db8/packages/x-date-pickers/src/internals/hooks/useField/useField.ts)) prevents users from submitting the form by hitting `enter`:

```
case event.key === 'Enter': {
  event.preventDefault();
  break;
}
```

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Browsers:
    FireFox 125.0.2
    Chrome 124.0.6367.91
  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 21.7.3 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 9.0.6 - /usr/local/bin/pnpm
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/material: ^5.15.15 => 5.15.15 
    @mui/material-nextjs: ^5.15.11 => 5.15.11 
    @mui/x-date-pickers: ^7.3.1 => 7.3.1 
    @mui/x-date-pickers-pro: ^7.3.1 => 7.3.1 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.74 => 18.2.74 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.4.4 => 5.4.4 
```
</details>

**Search keywords**: datepicker, accessibility, usability, enter, submit
**Order ID**: 66464

**Comment by LukasTy** [comment]
Thank you for reporting this problem. 🙏 
It looks like a regression as it is only happening on v6.
The code preventing the `Enter` default behavior is there for proper behavior on [accessible DOM fields](https://mui.com/x/react-date-pickers/fields/#accessible-dom-structure).

We will investigate how to achieve it without this unexpected BC.

**Comment by davevanhoorn** [comment]
> It looks like a regression as it is only happening on v6.

Thanks for the quick response @LukasTy. Just to prevent confusion when people read your comment, don't you mean `v7`?

**Comment by LukasTy** [comment]
> Just to prevent confusion when people read your comment, don't you mean `v7`?

Thank you for the confirmation.
I meant to say that this is only happening on v7 and wasn't the case on v6. 🙈 
I will edit my comment. 😉

**Comment by LukasTy** [comment]
Just a quick update on why there is no PR ready yet:
It's trivial to solve the problem for the v6 field (the one using an `input` element), but doing so breaks the [accessible DOM fields](https://mui.com/x/react-date-pickers/fields/#accessible-dom-structure) that needs some custom solution on how to handle the case...
In the worst-case scenario, we keep the issue on v7 behavior for now.
P.S. [React Spectrum](https://react-spectrum.adobe.com/react-spectrum/DateField.html) using the same behavioral approach also has the same issue. 🙈

**Comment by LukasTy** [comment]
@JCQuintas Thanks for the idea.
I wasn't aware of this API.
However, it feels pretty wrong doing such a thing on the component side. 🙈

**Comment by LukasTy** [comment]
> what are your concerns of doing this component side?

It feels error-prone and not something that a component itself should trigger.
Starting with the fact that simply having a form does not mean that clicking <kbd>Enter</kbd> will trigger a submit action, the form has to have a submit button...

I'll have this idea in mind for the v7 approach as a test (last-resort case), but for the v6 approach, we just need to remove the unwanted code. 👌

**Comment by JCQuintas** [comment]
Yeah I can see that, thanks for explaining :)

**Comment by LukasTy** [comment]
@JCQuintas I've double-checked and can confirm that using `requestSubmit` "works", but it has the anticipated behavioral difference to what you'd expect from the native browser form behavior.
It will **force** request a form to submit and that is "fine" on Firefox, but Safari and Chrome only submit a form on <kbd>Enter</kbd> click on a form having a "submit" button.

I think the best course of action is to fix the regression and keep the v7 behavior as is for now.
I'll open a new issue to explore the best solution for v7 behavior.

**Comment by JCQuintas** [comment]
Hum, didn't know about that, couldn't we just re-implement the behaviour, like

```tsx
      case event.key === 'Enter': {
        const form = event.currentTarget.closest('form');
        const submitButton = form?.querySelector(
          'button[type="submit"]',
        ) as HTMLButtonElement | null;
        if (submitButton) {
          if (form?.requestSubmit) {
            form?.requestSubmit();
          } else {
            submitButton.click();
          }
        }
        event.preventDefault();
        break;
      }
```

It is not very "react-y" but should do the trick

**Comment by LukasTy** [comment]
> Hum, didn't know about that, couldn't we just re-implement the behaviour

Sure, we can, but that comes with a behavior change on Firefox and "maybe" other browsers, where it submits the form regardless of the submit button's existence. 🙈 
I would prefer spending more time to see if we can't get closer to native date input implementation. 🤷
