### ISSUE TITLE
[data grid] `footerRowCount` slot does not override

### ISSUE THREAD

**Issue by TonyBrobston** [mui/mui-x#12974]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/charming-gauss-rt62xq?file=%2Fsrc%2FDemo.tsx

Steps:
1. Open the link above
2. Select at least one row
3. Observe that the `footerRowCount` says `x row(s) selected` rather than `This is a test`

### Current behavior

When I try to override `footerRowCount` nothing happens.

### Expected behavior

When I try to override `footerRowCount` I expect `x row(s) selected` to be overriden with the React I put in `slots` -> `footerRowCount`.

### Context

Our UX team is wanting conditionally change what we see in the left side of the pagination/footer.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: footerRowCount slots
**Order ID**: 80452

**Comment by michelengelen** [comment]
Hey @TonyBrobston 
This slot is not meant to overwrite the selection count. As it stands there is no slot available for this specific part of the grid.

The `footerRowCount` will overwrite the bottom right part of the grid.
<img width="232" alt="Screenshot 2024-05-03 at 11 06 09" src="https://github.com/mui/mui-x/assets/32863416/712ce8b3-1f53-4232-9787-3e544f6fe8e9">

I guess we could add a slot for that.

Let me add this to the board for an estimation. 👍🏼

**Comment by michelengelen** [comment]
Also take into consideration this comment: https://github.com/mui/mui-x/issues/12568#issuecomment-2023699285

**Comment by TonyBrobston** [comment]
> Hey @TonyBrobston This slot is not meant to overwrite the selection count. As it stands there is no slot available for this specific part of the grid.
> 
> The `footerRowCount` will overwrite the bottom right part of the grid. <img alt="Screenshot 2024-05-03 at 11 06 09" width="232" src="https://private-user-images.githubusercontent.com/32863416/327704682-712ce8b3-1f53-4232-9787-3e544f6fe8e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTc4NTEsIm5iZiI6MTcxNTIxNzU1MSwicGF0aCI6Ii8zMjg2MzQxNi8zMjc3MDQ2ODItNzEyY2U4YjMtMWY1My00MjMyLTk3ODctM2U1NDRmNmZlOGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAxMTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YzFlZmFlYTU0ZDU0Zjg2OGM1YTlhZWY5ODJkM2Y2MjJiMzQ5OGUyYWRlNjI2ZDdiMmNhMjVlYmUyZWEwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n3TPRE8OeLlIdE9rHWOz7Aov5_V8h5yZsqXL47qLPbY">
> 
> I guess we could add a slot for that.
> 
> Let me add this to the board for an estimation. 👍🏼

Ah, that makes sense. I guess I misinterpreted and now that I reread the name, that matches up.



> Also take into consideration this comment: [#12568 (comment)](https://github.com/mui/mui-x/issues/12568#issuecomment-2023699285)

I'm not sure how this relates? Are you saying something like `footerSelectedRowCount` won't be added right now because the pattern for slots needs clarified?

We went the direction of overriding the whole footer for now.

Thanks for the reponse.

**Comment by TonyBrobston** [comment]
> > > Also take into consideration this comment: [#12568 (comment)](https://github.com/mui/mui-x/issues/12568#issuecomment-2023699285)
> > 
> > 
> > I'm not sure how this relates? Are you saying something like `footerSelectedRowCount` won't be added right now because the pattern for slots needs clarified?
> 
> Yes, that's what I meant.
> 
> > Thanks for the reponse.
> 
> Happy to help! 👍🏼

Sounds good, thank you again.
