### ISSUE TITLE
[data grid] filter not returning correct results

### ISSUE THREAD

**Issue by imharrod** [mui/mui-x#12987]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Data contains a field called ScheduledTestDate which is a date field
2.Filter is written as "On or After 05/02/2024" AND second filter "On or Before 08/02/2024"
3.Result is returning rows with ScheduledTestDate of 04/09/2025

### Current behavior

The resulting display is not including the correct number of rows

### Expected behavior

Only records with a ScheduledTestDate between the two filters

### Context

the user clicks a buttion "Due in 90 days" and the code applies the filter.  The user should only see records within that 90 day range

### Your environment

I'm not set up to run these commands

**Search keywords**: datagrid filter

**Search keywords**:

**Comment by MBilalShafi** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find examples and guides on how to find templates in our docs with which you can provide examples for your specific use case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
