### ISSUE TITLE
[data grid] add a prop that disables header filters without hiding them

### ISSUE THREAD

**Issue by layerok** [mui/mui-x#12985]
### Summary

`DataGrid` exposes a new prop `disableColumnHeaderFiltering` that disables header filters without hiding them.

### Example of greyed out header filters during inline editing.
<img width="1071" alt="image" src="https://github.com/mui/mui-x/assets/18424848/b7657b5e-5c13-43f1-89ee-eee1418d533e">

### Motivation

When a user enters inline edit mode on a row, we want to make sure that they don't accidentally lose any unsaved changes. To do this, we want to disable actions that could lead to this result, such as filtering, sorting, row selection etc. These actions will become available when the user completes inline editing.

To disable sorting there is `disableColumnSorting`
To disable row selection there is `disableRowSelectionOnClick`
To disable column menu there is `disableColumnMenu`
But there is no prop to disable header filters without hiding them.

**Search keywords**: disable header filter prop without hiding
**Order ID**: 74777

**Comment by MBilalShafi** [comment]
In general, the props like `disableXXX` are supposed to turn off the specific feature in the Grid. For example, in the examples you provided, `disableColumnMenu` removes the column menu, and `disableColumnSorting` makes the column unsortable. This is the case for the features that are enabled by default.

Some features like header filtering are opt-in using props (e.g. `headerFilters` prop) and the prop needs to be passed when the feature needs to be enabled.

You could achieve the behavior you mentioned (disable editing of filter values but keep showing the filter cells) by providing the `slotProps.headerFilterCell.InputComponentProps`. I've tried to do that in this example: https://stackblitz.com/edit/react-9taqbx

Would that work for you?

**Comment by layerok** [comment]
Yeah, it will work, thank you.
