### ISSUE TITLE
[data grid] Unexpected cell text selection highlighting area in v7 in Chromium Browsers

### ISSUE THREAD

**Issue by wladimir-k-m** [mui/mui-x#13018]
### Steps to reproduce

Steps:
1. Select text in any cell in v7, e.g. here: https://mui.com/x/react-data-grid/layout/#predefined-dimensions
2. Notice the text selection area has the same height as the cell:
![image](https://github.com/mui/mui-x/assets/141158595/87fc57e5-53ec-451c-ad15-29cfbfd5d808)

In v6 the text selection area is as expected: https://v6.mui.com/x/react-data-grid/layout/#predefined-dimensions
![image](https://github.com/mui/mui-x/assets/141158595/457d1782-9e5a-4fea-84b6-cac5eb24c0e0)

### Expected behavior

The same minimum bounding box for text selection highlighting as in v6.

### Your environment

The issue seems to happen only in Chromium based browsers. Tested:
Chrome: Version 124.0.6367.119
Edge: Version 124.0.2478.80

It looks fine in Firefox.

**Search keywords**: data grid, text selection, text highlighting
**Order ID**: 83276

**Comment by michelengelen** [comment]
Hey @wladimir-k-m 
thanks for raising this issue. The adjusted area size comes from a change we introduced in d9ac050aea0b9a03a959a67e6a71c923d5562351. It was meant to increase performance of the cell rendering. Not sure about the performance implication of this specific change. That is something @romgrk would be best to answer here.

**Comment by michelengelen** [comment]
Just a quick question @wladimir-k-m: Does this prove to be a problem in your case?

**Comment by michelengelen** [comment]
OK, so it is basically a cosmetic issue (with a slight dent in a11y).
I will add this to the board, so we can check how to improve this.

**Comment by romgrk** [comment]
The change in cell structure is similar to what other grid components have. I have inspected a bit what the other components are doing to deal with text selection: most of them just don't allow native text selection. Any selection goes through grid cell/row selection: https://mui.com/x/react-data-grid/cell-selection/. It's just that we allow text selection when there is no row/cell selection.

The line-height is set to 100% height to vertically align text, if we can find an alternative to that we can remove the line-height.

**Comment by romgrk** [comment]
But other grids are also having the same behavior: https://ag-grid.com/react-data-grid/selection-overview/#cell-text-selection

It would be possible for users to re-add a wrapper using `renderCell`, but that has performance implications in particular for scrolling.

**Comment by wladimir-k-m** [comment]
Ok, thanks for the investigation @romgrk. If the visual change has performance implications I think it's better to leave it the way it is. You can close the issue.
