### ISSUE TITLE
[data grid] AutoHeight combined with scrollable body

### ISSUE THREAD

**Issue by httpete** [mui/mui-x#13023]
### Summary

Autoheight is great, keeping the footer hugged up near the rows when the page size changes. But if you resize the page / container, you lose the sticky grid header / footer and scrollable body of the grid as if it has an explicit height. 

You really want to be able to do both together. Right now, I use one or the other (autoHeight={true} or an explicit height (most often with a calc() css expression) 

There is a holy grail solution to this that can allow the grid to scroll properly in all cases, and keep the autoHeight working in concert.

**Search keywords**: height autoheight scrolling
**Order ID**: 79357

**Comment by michelengelen** [comment]
Hey @httpete 
thanks for raising this issue.
I will add this to the board, so the team can have a look!

**Comment by httpete** [comment]
Here is a visual to help understand it. In this dialog, autoHeight would have kept the footer right under the rows. 
But in cases where you had enough rows, and autoHeight pushed the footer down, you would not have the areas highlighted in red as fixed /sticky and allow the row container to scroll.

![image](https://github.com/mui/mui-x/assets/1200635/cbbbc7ea-c726-4f76-b70d-737c719a9ad0)

**Comment by svidskiy** [comment]
Are there any changes in this regard? This is very important

**Comment by svidskiy** [comment]
@michelengelen Are there any changes in this issue? This is very important

**Comment by cherniavskii** [comment]
Can you give [Flex parent container](https://mui.com/x/react-data-grid/layout/#flex-parent-container) a try?
It was released in https://github.com/mui/mui-x/releases/tag/v7.19.0
