### ISSUE TITLE
[data grid] Migrating Material UI v4 to v5 breaks some of the features

### ISSUE THREAD

**Issue by Preethi-Gunasekaran** [mui/mui-x#13047]
### The problem in depth

We are using React based Application that runs with Jsonforms combined Material UI V4 support.

Now we are trying to consume data-grid-premium for tabular display to enhance the performance of the table. Importing the licence key for the premium package forces us to upgrade the entire Material UI to v5.

Post upgrade with  Material UI V5 premium, we are seeing instantaneous crash with the pages that uses JSONforms.

Can you please help us with the possible change logs or compatible version.

- “@jsonforms/core”: “3.2.1”,
- “@jsonforms/material-renderers”: “^3.2.1”,
- “@jsonforms/react”: “^2.3.2”

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.2
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 2.15.12 - ~/Documents/AMD/console/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 124.0.6367.119
    Edge: Not Found
    Safari: 15.3
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^10.3.0 => 10.3.0 
    @mui/base:  5.0.0-alpha.83 
    @mui/core-downloads-tracker:  5.15.16 
    @mui/icons-material: ^5.15.16 => 5.15.16 
    @mui/lab: 5.0.0-alpha.84 => 5.0.0-alpha.84 
    @mui/material: ^5.15.16 => 5.15.16 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/styles: ^5.15.16 => 5.15.16 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^4.0.0 => 4.0.2 
    @mui/x-data-grid-generator: 4.0.0 => 4.0.0 
    @mui/x-data-grid-premium: ^6.0.0 => 6.19.11 
    @mui/x-data-grid-pro:  6.19.11 
    @mui/x-date-pickers: ^5.0.13 => 5.0.20 
    @mui/x-license: 7.2.0 => 7.2.0 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^17.0.0 => 17.0.80 
    react: 17.0.0 => 17.0.0 
    react-dom: 17.0.0 => 17.0.0 
    styled-components: 5.0.1 => 5.0.1 
```
</details>

**Search keywords**: MUI v4 to v5 with data grid
**Order ID**: 89199

**Comment by michelengelen** [comment]
Hey @Preethi-Gunasekaran Could you share the error you receive when the app crashes?
In the meantime I will try and reproduce it myself.

@brijeshb42 this kind of also falls into core territory. Could you maybe assist?

**Comment by michelengelen** [comment]
I just forked and installed the seed project. This works with material-ui v5 without problems (installed v5.13.0 per package.json file)

It uses these version:
```
"@jsonforms/core": "3.2.0",
"@jsonforms/material-renderers": "3.2.0",
"@jsonforms/react": "3.2.0",
```

I also tried installing DataGrid Premium (had to upgrade the material-ui version for this) and it still works just fine.

<img width="2594" alt="Screenshot 2024-05-08 at 12 09 54" src="https://github.com/mui/mui-x/assets/32863416/9990c518-7bad-4a61-a4fc-d130cbacde0c">

Could you try upgrading `@jsonforms/react` to v3.2.0?
