### ISSUE TITLE
[data grid] Why does hitting the 'd' key on the export menu on datagrid navigate menu items?

### ISSUE THREAD

**Issue by macnaughton** [mui/mui-x#13049]
### The problem in depth

Hitting the 'd' key when the Export menu is open on the datagrid causes the menu to navigate.  Why is this?

This can be reproduced directly on the MUI datagrid docs site:  

https://mui.com/x/react-data-grid/export/#excel-export

- click "Export"
- press the "d" key

I'm tracking down an issue where we are using a custom export dialog that loses focus any time the 'd' key is pressed.  This is causing issues with form fields when entering data.  While trying to track this down I went looking for anything that could be listening for keydown events, and noticed that the 'd' key causes focus to change to the "export" menu items and cycle through them.  I don't see this behavior with other grid toolbar items. 

### Your environment
Browsers: Firefox and Chrome

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: d key datagrid export

**Comment by macnaughton** [comment]
This may need to change to standard support instead of priority; I have a support key but it does not appear to be valid at that link.

**Comment by michelengelen** [comment]
> This may need to change to standard support instead of priority; I have a support key but it does not appear to be valid at that link.

^^ @oliviertassinari could you check if the page is still working?

**Comment by michelengelen** [comment]
@macnaughton this is expected behavior. It is basically as if you would have a select dropdown. entering `d` will select `Download ...` and hitting `p` will select `Print`.

**Comment by michelengelen** [comment]
we could probably improve on this @cherniavskii ... should we move this to the board?

**Comment by macnaughton** [comment]
Thanks for clarifying.  With this in mind I was able to create a workaround for my issue, feel free to close this or handle as you see fit!

**Comment by cherniavskii** [comment]
There isn't anything for the xGrid team to act on here.
For reference, a similar issue was reported in Material UI repo, and I agree with the suggestion in https://github.com/mui/material-ui/issues/16949#issuecomment-519914739
