### ISSUE TITLE
[charts][ChartsTooltip] Tooltip not working on mobile

### ISSUE THREAD

**Issue by wzdorowa** [mui/mui-x#13041]
### Steps to reproduce

Link to live example: https://mui.com/x/react-charts/tooltip/

Steps:
1. Open in mobile browser
2. Touch and move your finger on the chart

### Current behavior

Tooltip is not rendered

### Expected behavior

Tooltip renders and follows your finger

### Context

You can check how it works in recharts, repeat **Steps to reproduce** [here](https://recharts.org/en-US/examples/CustomContentOfTooltip) 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.3
  Binaries:
    Node: 22.1.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.1.0 - ~/node_modules/.bin/pnpm
  Browsers:
    Chrome: 124.0.6367.119
    Edge: Not Found
    Safari: 17.3
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.11 
    @mui/core-downloads-tracker:  5.14.5 
    @mui/icons-material: ^5.14.3 => 5.14.3 
    @mui/material: ^5.14.5 => 5.14.5 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-charts: ^7.3.1 => 7.3.1 
    @mui/x-date-pickers: ^6.11.0 => 6.11.0 
    @types/react:  18.2.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.1.6 => 5.1.6 
```
</details>

**Search keywords**: tooltip, mobile, touch

**Comment by michelengelen** [comment]
Thanks for raising this and you contribution!
We appreciate it! 💙
