### ISSUE TITLE
[data grid] how to update column header titles when switching language without reseting data-grid state

### ISSUE THREAD

**Issue by layerok** [mui/mui-x#13055]
### The problem in depth

I know that `columns` prop should keep the same reference between two rerenders to avoid loosing data grid state.
But If I don't update `columns` prop when switching language then column headers aren't translated. If I update `columns` prop then data grid state is reset. What should I do in this situation?

Link to [sandbox](https://codesandbox.io/p/sandbox/solitary-star-5kflq2?file=%2Fpackage.json)
#### Steps:
1. resize some column
2. change language

https://github.com/mui/mui-x/assets/18424848/c3513836-210d-46fe-a1cc-f54c6e2af806

**Search keywords**: i18next translation column language data grid
**Order ID**: 74777

**Comment by layerok** [comment]
well I found something

instead of doing this
```javascript
const { t } = useTranslation();
const columns = useMemo(() => [
  {
    field: "first_name",
    headerName: t("first_name")
  },
  {
    field: "last_name",
    headerName: t("last_name")
  },
], [t]);
```
I can do this

```javascript
const columns = useMemo(() => [
  {
    field: "first_name",
    renderHeader: () => <Trans i18nKey="first_name"/>
  },
  {
    field: "last_name",
    renderHeader: () => <Trans i18nKey="last_name"/>
  },
], []);
```

**Comment by layerok** [comment]
Title of a custom filter operator also don't update when switching languages.
But if you pass the `Trans` component instead of a simple string, it will update

```javascript
const { t } = useTranslation();
const columns = useMemo(() => [
  {
    field: "first_name",
    renderHeader: () => <Trans i18nKey="first_name"/>,
    filterable: true,
    filterOperators: [
      {
        value: "contains",
        getApplyFilterFn: () => null,
        // @ts-ignore
        label: <Trans i18nKey="header-operators.mode.contains"/>, // <-- it will update when switching languages
        // @ts-ignore
        headerLabel: <Trans i18nKey="header-operators.mode.contains"/>, // <-- it will update when switching languages
      },
      {
        value: "exact",
        getApplyFilterFn: () => null,
        label: t("header-operators.mode.exact"), // <-- it won't update when switching languages
        headerLabel: <t("header-operators.mode.exact"), // <-- it won't update when switching languages
      },
      // ... other filter operators
    ]
  },
  // ... other column definitions 
], []);
```

I had to use `ts-ignore` because typescript is unhappy about `Trans` being passed to a property that accepts only a value of type string

**Comment by michelengelen** [comment]
Hey @layerok ... 
Sry for the late reply. I had some time off.
It seems you solved your issue already.
Is there anything else we can help you with?

**Comment by layerok** [comment]
@michelengelen I am not satisfied with my solution
Firstly, I don't like using ts-ignore 
Secondly, I don't like using `renderHeader` because I can't just return translation in  the `renderHeader` callback
because then the `DataGrid` will render the unstyled header. I need to wrap it in some component first. And this wrapping makes column config larger and harder to maintain.
```javascript
renderHeader: () => <HeaderCell><Trans i18nKey="some-key"/></HeaderCell>
```
I think this problem requires solution at the library level
How I see a perfect solution
```javascript
const columns = useMemo([
  {
    field: 'title',
    headerName: () => t('title'),
    filterOperators: [
      {
        label: () => t('contains'),
        headerLabel: () => t('contains')
      }
    ]
  }
], []);

const apiRef = useGridApiRef();
  
useLayoutEffect(() => {
  const forceUpdate = () => {
    apiRef.current.forceUpdate();
  };
  i18n.on("languageChanged", forceUpdate);
  return i18n.off("languageChanged", forceUpdate);
}, [apiRef]);
  
return <DataGrid columns={columnsRef} />
```
but right now this is impossible because `headerName` doesn't accept callback values

```javascript
const columnsRef = useRef<ExtendedGridColDef[]>([
  {
    field: 'title',
    lazyHeaderName: () => t('title'),
    headerName: "",
  }
], []);

columnsRef.current.map((column) => {
  column.headerName = column.lazyHeaderName();
});

const apiRef = useGridApiRef();

useLayoutEffect(() => {
  const forceUpdate = () => {
    apiRef.current.forceUpdate();
  };
  i18n.on("languageChanged", forceUpdate);
  return i18n.off("languageChanged", forceUpdate);
}, [apiRef]);

return <DataGrid columns={columnsRef.current}

```
I guess this issue is becoming more of a feature request than a question

**Comment by layerok** [comment]
## Workaround #2

```javascript
const columnsRef = useRef<ExtendedGridColDef[]>([
  {
    field: 'title',
    lazyHeaderName: () => t('title'),
    headerName: "",
  }
], []);

columnsRef.current.map((column) => {
  column.headerName = column.lazyHeaderName();
});

const apiRef = useGridApiRef();

useLayoutEffect(() => {
  const forceUpdate = () => {
    apiRef.current.forceUpdate();
    apiRef.current.updateColumns(columnsRef.current);
  };
  i18n.on("languageChanged", forceUpdate);
  return i18n.off("languageChanged", forceUpdate);
}, [apiRef, columnsRef.current]);

return <DataGrid columns={columnsRef.current}/>
```

**Comment by michelengelen** [comment]
I am not sure where the problem is:
This does work for me.

```tsx
const translations = {
  first_name: {
    en: 'First Name',
    de: 'Vorname',
  },
  last_name: {
    en: 'Last Name',
    de: 'Nachname',
  },
};

export default function DataGridDemo() {
  const [lang, setLang] = React.useState<'en' | 'de'>('en');
  // dummy function to just return some values from an object
  const t = (key: keyof typeof translations) => translations[key][lang];

  const HeaderCell = ({ labelKey }: { labelKey: keyof typeof translations }) => (
    <div>{t(labelKey)}</div>
  );

  const columns = React.useMemo(
    () => [
      { field: 'id', headerName: 'ID', width: 90 },
      {
        field: 'firstName',
        width: 150,
        editable: true,
        renderHeader: () => <HeaderCell labelKey="first_name" />,
      },
      {
        field: 'lastName',
        width: 150,
        editable: true,
        renderHeader: () => <HeaderCell labelKey="last_name" />,
      },
    ],
    [t],
  );
...
```

Wouldn't this be sufficient?

This does work like as well when using:
```tsx
const columns = React.useMemo(
  () => [
    { field: 'id', headerName: 'ID', width: 90 },
    {
      field: 'firstName',
      headerName: t('first_name'),
      width: 150,
      editable: true,
    },
    {
      field: 'lastName',
      headerName: t('last_name'),
      width: 150,
      editable: true,
    },
  ],
  [t],
);
```

Is i18n not updating the `t` function on a language change?

**Comment by michelengelen** [comment]
I would need setup a dev environment with next for this. This might take until tomorrow though. Would that be ok?

**Comment by layerok** [comment]
> Is i18n not updating the t function on a language change?  

The problem is not with i18next but with `columns` prop.
`columns` prop must keep reference between two rerenders. Otherwise datagrid state will be reset
So putting `t` function into dependency array of useMemo is not an option.
```javascript
const columns = React.useMemo(() => [{ field: 'id', headerName: 'ID', width: 90 }], [t]);
```
If you don't put `t` function into the dependency array then the header won't be updated when the language changes
We can use `renderHeader` to workaround this problem, but I've already explained why I don't like this solution. And also what to do with filterOperators labels, they don't have a `renderLabel` property.

**Comment by michelengelen** [comment]
OK, thanks ... got it.
It does indeed look as if there is no satisfying solution (afaik) to this.
I will add this to the board and see what the team has to say about it.

**Comment by flaviendelangle** [comment]
You could probably use [apiRef.updateColumns](https://mui.com/x/api/data-grid/grid-api/#grid-api-prop-updateColumns) and pass the new headers, but it's not the prettier solution imaginable.

**Comment by layerok** [comment]
well, I found another workaround to this issue. I can simply reload the page after changing the language
