### ISSUE TITLE
 [pickers] when customizing date range picker the localization provider get null values

### ISSUE THREAD

**Issue by avAudc** [mui/mui-x#13054]
### Steps to reproduce

Link to live example: (required)

Steps:
1. use next.JS 13.5
2. customize actionbar and shortcuts
3. enjoy the mess
4. occurs on v6 and v7

### Current behavior

throws an error

### Expected behavior

not throws an error

### Context

customizing the date range picker to also have time pickers (useing mui's timePicker) at the action bar and be used as header filter

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  using chrome
  Output from `npx @mui/envinfo` goes here.
```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (123.0.2420.97)
  npmPackages:
    @emotion/react:  11.10.6
    @emotion/styled: ^11.10.5 => 11.10.6
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.14
    @mui/icons-material: ~5.11.16 => 5.11.16
    @mui/lab: ^5.0.0-alpha.132 => 5.0.0-alpha.150
    @mui/material: ^5.15.3 => 5.15.14
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.14
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid: ^6.12.0 => 6.12.0
    @mui/x-data-grid-pro: ^6.12.0 => 6.12.0
    @mui/x-date-pickers: ^6.8.0 => 6.8.0
    @mui/x-date-pickers-pro: ^6.8.0 => 6.8.0
    @mui/x-license-pro:  6.6.0
    @mui/x-tree-view:  6.0.0-alpha.1
    @types/react:  18.0.38
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: ^5.3.6 => 5.3.10
    typescript: ^4.1 => 4.9.5
</details>

**Search keywords**: DateRangePicker MUI X

**Search keywords**:

**Comment by noraleonte** [comment]
Hey @avAudc 👋 

Can you please provide a reproduction case for this 🙏 

> customizing the date range picker to also have time pickers

Have you tried using the[ Date Time Range picker](https://mui.com/x/react-date-pickers/date-time-range-picker/)?
