### ISSUE TITLE
[data grid] issue with using sx in GridToolbarColumnsButton 

### ISSUE THREAD

**Issue by SeemaShettyVk** [mui/mui-x#13057]
![Capture](https://github.com/mui/material-ui/assets/169273370/b948529d-bcd8-4024-a548-aca04e215781)

![image](https://github.com/mui/material-ui/assets/169273370/c8e55617-acbe-42db-b892-d045eab30bd2)

Hi,
I am trying to use sx in GridToolbarColumnsButton but I am not able to use sx directly with GridToolbarColumnsButton, so i tried slotProps but it's not working. Please help. 

**Search keywords**: 

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @SeemaShettyVk the correct way to use the `sx` prop in the `GridToolbarColumnsButton` component is this:

```
<GridToolbarColumnsButton slotProps={{ button: { sx: { margin: 2 } } }} />
```

> How can I inherit GridColDef. Please help me fix this.

That would be this:

```
type CustomColDef = GridColDef & { customProp: string };
```

Do you have anything else you need some help with?
