### ISSUE TITLE
[data grid] Stale Cache for filter items > 5

### ISSUE THREAD

**Issue by shengxyuri** [mui/mui-x#13063]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Filter as usual
2. After about 5 filters, the data is stale
3. Have to clear cache and refresh

### Current behavior

Current behaviour: no stale and can filter as per normal
1. Filter as usual
2. After about 5 filters, the data is stale

### Expected behavior

Expected behaviour: no stale and can filter as per normal

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: stale

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
