### ISSUE TITLE
[pickers] Add a default AM or PM to the time picker

### ISSUE THREAD

**Issue by Gabsop** [mui/mui-x#13078]
### Summary

The Time Pickers always defaults to AM when I the user selects the first value. The feature would be to add a default={"AM"} or default={"PM"} so that we can set the default to "PM" when a user is selecting a time

**Search keywords**: timepicker

**Comment by flaviendelangle** [comment]
Hi,

You can use the `referenceDate` prop to decide what date should be applied when you click on a section.
For your usecase, you can just put an hour that is above 12 and it will work.

See [this working example](https://stackblitz.com/edit/react-zl21cd?file=Demo.tsx)


By the way @LukasTy , when I do that, `12` ends up at the top of the list, not at the bottom :laughing: 

![image](https://github.com/mui/mui-x/assets/3309670/4fd2491c-1222-4a94-9f26-bb43cca6a9d8)
