### ISSUE TITLE
[data grid] slotProps ColumnsManagement is not working

### ISSUE THREAD

**Issue by saeonny** [mui/mui-x#13071]
### The problem in depth

Hello, I am using DataGridPro and I followed the instructions provided in the documentation for column visibility customization ([Customize the list of columns in columns management](https://mui.com/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-columns-management)) and disabling actions in the footer ([Disable actions in footer](https://mui.com/x/react-data-grid/column-visibility/#disable-actions-in-footer)).

However, in my project, when I try to utilize the 'columnsManagement' property within 'slotProps', I encounter an error as shown in the following image: 
![image](https://github.com/mui/mui-x/assets/25571363/eb5867ec-10e9-4e0b-8e22-58d4447a8e02)
Is this a bug?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

 Browsers:
    Chrome: Not Found
    Edge: Chromium (123.0.2420.97)
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.26
    @mui/core-downloads-tracker:  5.15.10
    @mui/envinfo: ^2.0.17 => 2.0.17
    @mui/icons-material: ^5.15.10 => 5.15.11
    @mui/lab: ^5.0.0-alpha.155 => 5.0.0-alpha.155
    @mui/material: ^5.15.10 => 5.15.10
    @mui/private-theming:  5.15.9
    @mui/styled-engine:  5.15.9
    @mui/system:  5.15.9
    @mui/types:  7.2.13
    @mui/utils:  5.15.9
    @mui/x-charts: 7.3.2 => 7.3.1
    @mui/x-data-grid:  6.19.2
    @mui/x-data-grid-generator: latest => 6.19.2
    @mui/x-data-grid-premium:  6.19.2
    @mui/x-data-grid-pro: latest => 6.19.2
    @mui/x-date-pickers: ^6.19.4 => 6.19.5
    @mui/x-date-pickers-pro: ^6.19.4 => 6.19.5
    @mui/x-license-pro: latest => 6.10.2
    @types/react: ^18.2.43 => 18.2.43
    react: latest => 18.2.0
    react-dom: latest => 18.2.0
    typescript: ^5.3.3 => 5.3.3
</details>

**Search keywords**: ColumnsManagement
**Order ID**: 83106

**Comment by saeonny** [comment]
In my  project 
![image](https://github.com/mui/mui-x/assets/25571363/8e0b9ab7-7c18-48f8-a3cd-02a815f572b9)
![image](https://github.com/mui/mui-x/assets/25571363/c1744450-7082-40ad-b98f-17474f00be10)

**Comment by michelengelen** [comment]
Hey @saeonny ... 
From your envinfo output I can see that you are using `v6`.
We recently changed the name of the `slotProp` from `slotProp.columnsPanel` (in `v6`) to `slotProp.columnsManagement` (in `v7`). So since you are looking at the `v7` it will show up as `columnsManagement`. But for your version you would need to use `columnsPanel`.

Here is the respective page in the `v6` docs: [Column visibility (v6)](https://v6.mui.com/x/react-data-grid/column-visibility/)

**Comment by saeonny** [comment]
Thank you so much its fixed by using columnsPanel !

**Comment by michelengelen** [comment]
Great ... I'll close this then! 👍🏼
