### ISSUE TITLE
[DataGrid] Unable to override default props/styling for Header

### ISSUE THREAD

**Issue by AdibChiguer** [mui/mui-x#13082]
I faced a problem with the default data grid color due to the style variables. I searched over the web to find out how to solve the problem, and after just a few tries, I found a solution. So, I just want to share this solution with whoever encountered it :

`
              "& .css-n3fyjk-MuiDataGrid-root": {
                "--DataGrid-containerBackground": theme === "dark" ? "#3e4396 !important" : "#a4a9fc !important",
              },
`

Just search for the class name of the variable and set the variable to the value you want. I hope that was helpful.

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @AdibChiguer this will probably not work for others, since the classes have generated unique identifiers. It is safer to use `gridClasses.root` instead:

```jsx
sx={(theme) => ({
  [`&.${gridClasses.root}`]: {
    '--DataGrid-containerBackground':
      theme.palette.mode === 'dark' ? '#3e4396' : '#a4a9fc',
  },
})}
```

On a side note: you don't need the `!important` this way as well
