### ISSUE TITLE
[pickers][DatePicker] change borderRadius of selected day for dateCalendar

### ISSUE THREAD

**Issue by ImamJanjua** [mui/mui-x#13083]
### Context

Hi, I am trying to change the borderRadius for the days which are been selected or like the todays day, but not working for me

```jsx
<DateCalendar
  {...props}
  slots={{
    leftArrowIcon: LeftArrowIcon,
    rightArrowIcon: RightArrowIcon,
  }}
  slotProps={{
    day: {
      sx: {
        "::selection": {
          borderRadius: "10px",
        },
      },
    },
  }}
/>
```

**Search keywords**: .

**Comment by LukasTy** [comment]
@ImamJanjua is [this](https://stackblitz.com/edit/react-2emg1e?file=Demo.tsx) something that you are looking for? 🤔 
Consider checking the [customization playground](https://mui.com/x/react-date-pickers/date-picker/#customization) for more examples. 😉

**Comment by ImamJanjua** [comment]
@LukasTy thanks man!

another thing, calendar is not responsive at all and appears to have fixed dimension, does it have something to do with the breakpoints?

https://github.com/mui/mui-x/assets/137432044/1f2a7427-2dbd-41d4-9922-89c4b1892d58

**Comment by LukasTy** [comment]
> another thing, calendar is not responsive at all and appears to have fixed dimension, does it have something to do with the breakpoints?

Yes, the calendar has a fixed width just as the material design suggests.
Do you have suggestions on how to make it responsive? 🤔

**Comment by ImamJanjua** [comment]
@LukasTy shouldn't u know that?  😄

**Comment by ImamJanjua** [comment]
@LukasTy does the calendar has breakpoints and can i acess and modify them?

**Comment by LukasTy** [comment]
> does the calendar has breakpoints and can i acess and modify them?

No, there are no explicit breakpoints that are used.
If you want to use the theme breakpoints, then access them and override the styles accordingly. 👍

**Comment by ImamJanjua** [comment]
@LukasTy why does something like do not work? Some like backgroundColor works correctly

```typescript

 const Root = styled("div")(({ theme }) => ({
    [theme.breakpoints.down("sm")]: {
      width: "200px",
    },
    [theme.breakpoints.up("md")]: {
      width: "300px",
    },
    [theme.breakpoints.up("lg")]: {
      width: "300px",
    },
  }));


 <Root>
        <Calender
        />
      </Root>
```

**Comment by ImamJanjua** [comment]
@LukasTy  thanks! 

do u may know how can change the view with custom header?

```typescript
const DateCalendar: React.FC<DateCalendarProps<Date>> = (props) => {

  const Header = () => {
    return (
      <div className="flex flex-row justify-center gap-8 ">
         {/* on press go to next month*/}
        <button>
          <ChevronLeft size={22} />
        </button>
          
          {/* on press go to today*/}
        <button>today</button>

        {/* on press go to previous month*/}
        <button>
          <ChevronRight size={22} />
        </button>
      </div>
    );
  };

  return (
    <ThemeProvider theme={theme}>
      <Calendar
        slots={{
          calendarHeader: Header,
        }}                   />
   
  );
};
```

**Comment by michelengelen** [comment]
> @LukasTy thanks!
> 
> do u may know how can change the view with custom header?
> 
> ```ts
> const DateCalendar: React.FC<DateCalendarProps<Date>> = (props) => {
> 
>   const Header = () => {
>     return (
>       <div className="flex flex-row justify-center gap-8 ">
>          {/* on press go to next month*/}
>         <button>
>           <ChevronLeft size={22} />
>         </button>
>           
>           {/* on press go to today*/}
>         <button>today</button>
> 
>         {/* on press go to previous month*/}
>         <button>
>           <ChevronRight size={22} />
>         </button>
>       </div>
>     );
>   };
> 
>   return (
>     <ThemeProvider theme={theme}>
>       <Calendar
>         slots={{
>           calendarHeader: Header,
>         }}                   />
>    
>   );
> };
> ```

see this #13116 ... is this issue resolved and can be closed @ImamJanjua?
