### ISSUE TITLE
[data grid] Export to Excel default Date format is "dd.mm.yyyy" and it's too difficult to override for the entire system

### ISSUE THREAD

**Issue by nycgavin** [mui/mui-x#13118]
### Summary

The current date format for export to excel feature on Data Grid Premium is dd.mm.yyyy, while this is suitable for Europe countries.  In the United States, the default format should be mm/dd/yyyy, and currently the only way to overwrite the default format is at the column style level.

```
<GridToolbarExport
  excelOptions={{
    columnsStyles: {
      // replace the dd.mm.yyyy default date format
      recruitmentDay: { numFmt: 'dd/mm/yyyy' },
      // set this column in green
      incomes: { font: { argb: 'FF00FF00' } },
    },
  }}
/>
```
this is too tedious because I will need to define a column style for all date columns in all data grid.

I wish to overwrite the default date and datetime style at the datagrid level, not at the column level.

**Search keywords**: excel export datagrid
**Order ID**: 51732

**Comment by michelengelen** [comment]
There is an option to pas this at the DataGrid level.
You can pass in the `excelOptions` into the `slotProps` like this:

```tsx
const excelOptions = {
  columnsStyles: {
    // replace the dd.mm.yyyy default date format
    recruitmentDay: { numFmt: 'dd/mm/yyyy' },
    // set this column in green
    incomes: { font: { argb: 'FF00FF00' } },
  },
};

export default function ExcelCustomExport() {
  return (
    <div style={{ height: 500, width: '100%' }}>
      <DataGridPremium
        rows={rows}
        columns={columns}
        slots={{ toolbar: GridToolbar }}
        slotProps={{ toolbar: { excelOptions } }}
      />
    </div>
  );
}
```

Is this a suitable solution for your use-case?

**Comment by nycgavin** [comment]
no,  you suggestion would require me to pass in the numFmt: 'mm/dd/yyyy' for every column that's a date format, I have hundreds of datagrid and thousands of columns in the application, so this doesn't make sense.

solved it using the exceljspostprocess function that runs after the excel export: 
```
slotProps: {
          toolbar: {
            excelOptions: {
              exceljsPostProcess: excelOptions.exceljsPostProcess,
            },
          },
        },

const exceljsPostProcess = ({ worksheet }: GridExceljsProcessInput) => {
  worksheet.eachRow((row) => {
    row.eachCell((cell) => {
      if (cell.numFmt === 'dd.mm.yyyy') {
        cell.numFmt = 'mm/dd/yyyy';
      }
      if (cell.numFmt === 'dd.mm.yyyy hh:mm') {
        cell.numFmt = 'mm/dd/yyyy hh:mm';
      }
    });
  });
};

export const excelOptions = { exceljsPostProcess };

```

**Comment by michelengelen** [comment]
OK, I did not know that you have such an extent of grids and data.
Nice solution you have there. It can be slightly improved:
```tsx
const exceljsPostProcess = ({ worksheet }: GridExceljsProcessInput) => {
  worksheet.eachRow((row) => {
    row.eachCell((cell) => {
      if (cell.numFmt.includes('dd.mm.yyyy')) {
        cell.numFmt = cell.numFmt.replace('dd.mm.yyyy', 'mm/dd/yyyy');
      }
    });
  });
};
```
