### ISSUE TITLE
[pickers] DateTimePicker doesn't show time picker

### ISSUE THREAD

**Issue by TaylorFoster-Informulate** [mui/mui-x#13117]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Install datepickers 
2. Literally just simply render <DateTimePicker /> - Code pulled right from your docs...
3. No time picker shows. 

```
<LocalizationProvider dateAdapter={AdapterDateFns}>
  <DateTimePicker />
</LocalizationProvider>
```

![Screenshot 2024-05-13 at 1 48 47 PM](https://github.com/mui/mui-x/assets/137106782/5e8509c2-8178-4c3d-874f-17ca3d2ef444)

### Current behavior

It literally just doesnt show a time picker

### Expected behavior

I would expect a time picker to show unless your documentation is just poor.

### Context

I just want to pick a date and time. This should be easy...

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datetimepicker bug

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.
