### ISSUE TITLE
[pickers][TimePicker] Minute range 56-59 cannot be selected

### ISSUE THREAD

**Issue by hth520** [mui/mui-x#13125]
### Current behavior

![Snipaste_2024-05-14_17-19-14](https://github.com/mui/mui-x/assets/66396060/af00fc41-3a44-4b61-ba85-57533a26c629)
When I wanted to select minutes 56-59, I found that the drop-down box had no options for me to choose from

### Expected behavior

56-59 minutes? Nobody's ever had that problem

### Context

56-59 minutes? Nobody's ever had that problem

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Minute 56-59 notSelected

**Comment by michelengelen** [comment]
Hey @hth520 you can adjust the steps with the `timeSteps` prop:

```jsx
<TimePicker label="Basic time picker" timeSteps={{ minutes: 1 }} />
```

This is not documented, is it @LukasTy? 🤔

**Comment by LukasTy** [comment]
@michelengelen @hth520 please find the documentation for `timeSteps` [here](https://mui.com/x/react-date-pickers/digital-clock/#time-steps).
The default is step to "5-minute" steps.
Technically, "60" minutes do not exist in time calculation, so, there are no more options to put after 55, so then next one would be 0 minutes on the next hour.
![Screenshot 2024-05-17 at 17 06 52](https://github.com/mui/mui-x/assets/4941090/b2267003-1209-4b55-8ece-a6fea11747ec)

Does that answer your question or do you see a problem with it? 🤔
