### ISSUE TITLE
[charts][BarChart] x axis labels being hidden when resizing

### ISSUE THREAD

**Issue by FrancisEgan** [mui/mui-x#13134]
### Steps to reproduce

https://codesandbox.io/p/sandbox/bold-meadow-pxmjj6

1. Resize browser window and make it smaller horizontally
2. Observe x axis label disappearing (from the DOM entirely)

### Current behavior

The x axis labels get hidden at certain points

![image](https://github.com/mui/mui-x/assets/5480317/c0f2c581-60c7-4e7c-a2fc-90ff6804c2f6)

### Expected behavior

x axis labels overlap, or wrap

### Context

If the <text> elements at least remained in the DOM then some workaround could be applied. The labels could be rotated to fit, for example. This is impossible when the <text> elements are no longer present on the DOM

### Your environment

System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4 
    @emotion/styled: 11.11.5 => 11.11.5 
    @mui/material: 5.15.17 => 5.15.17 
    @mui/x-charts: 7.4.0 => 7.4.0 
    @types/react: 18.2.38 => 18.2.38 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 4.4.4 => 4.4.4 

**Search keywords**: bar chart x axis labels

**Comment by michelengelen** [comment]
@alexfauquette correct me if I am wrong, but this is expected behavior.
The labels will get removed when there is not enough space to display them.

If you change the labels to '$1000-$1999', ..., '$x000-$x999' so very similar in length you can see that the chart tries to render only those that have enough space. It looks like it will also try to render the ones that make the most sense (e.g. not remove the middle one)

Can we maybe improve on this @mui/xcharts ?

**Comment by alexfauquette** [comment]
Exactly. The behavior is to start from the left part of the axis, and do not display label if it overflow with the previous one, and repeat the operation

You can see it in action here: https://mui.com/x/react-charts/axis/#text-customization
Modifying the font size of the x-axis label impacts how many label are visible

![image](https://github.com/mui/mui-x/assets/45398769/c1841f11-b2c4-412c-bd4f-615af52e6c66)
![image](https://github.com/mui/mui-x/assets/45398769/be6492bb-5cad-4241-8a11-b126c5174e52)

**Comment by alexfauquette** [comment]
You can use the [tickLabelInterval](https://mui.com/x/api/charts/axis-config/#axis-config-prop-tickLabelInterval) to override the default behavior.

Basically adding `tickLabelInterval: () => true` to the axis config will for it to render every tick label.

https://codesandbox.io/p/sandbox/elated-galileo-f452wk?file=%2Fsrc%2FApp.tsx%3A13%2C15
