### ISSUE TITLE
[data grid] How can I trigger a new row being added after the processRowUpdate callback? (Only after adding a new row, not editing an existing row)

### ISSUE THREAD

**Issue by Luis-Ramirez21x** [mui/mui-x#13135]
### The problem in depth

I'd like the grid to auto-add a new row with a random ID only when: 

-  a user adds a new row and then saves it to a db/server. 

It should not auto-add a new row when a row is edited. The new row should be autofocused on as well. 

Use case: 
Our users often have to perform a lot of data entry. If they could simply hit enter, and the current row would save and the next one would open that would be fantastic.
Currently users have to :
-input data 
-hit enter 
-tab to the add button 
-hit enter again

Ideally users just:
-input data 
-hit enter

Am I overlooking some event listener that's triggered after proccessRowUpdate? 
Thanks in advance! 

I've created a simplified [sandbox ](https://codesandbox.io/p/sandbox/brave-fog-2mpj3t?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw6vyasx00072v6l6dhki0el%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw6vyasx00032v6l7h4onbb6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw6vyasx00042v6ls9snaiyd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw6vyasx00062v6lg62wo332%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw6vyasx00032v6l7h4onbb6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6vyasx00022v6l3ym4498i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw6vyasx00032v6l7h4onbb6%2522%252C%2522activeTabId%2522%253A%2522clw6vyasx00022v6l3ym4498i%2522%257D%252C%2522clw6vyasx00062v6lg62wo332%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6vyasx00052v6lxz9esyqv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw6vyasx00062v6lg62wo332%2522%252C%2522activeTabId%2522%253A%2522clw6vyasx00052v6lxz9esyqv%2522%257D%252C%2522clw6vyasx00042v6ls9snaiyd%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw6vyasx00042v6ls9snaiyd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)from a combination of the [Server Side example](https://mui.com/x/react-data-grid/editing/#server-side-validation) and the [Full CRUD example](https://mui.com/x/react-data-grid/editing/#full-featured-crud)

This is what their flow currently looks like

https://github.com/mui/mui-x/assets/86748117/5b107d9b-9d33-4cac-87cc-62b79daf1cb1

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 124.0.6367.60
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base: ^5.0.0-beta.34 => 5.0.0-beta.34 
    @mui/core-downloads-tracker:  5.14.14 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/joy: ^5.0.0-beta.11 => 5.0.0-beta.11 
    @mui/lab: ^5.0.0-alpha.126 => 5.0.0-alpha.126 
    @mui/material: ^5.11.12 => 5.11.12 
    @mui/private-theming:  5.14.14 
    @mui/styled-engine:  5.14.14 
    @mui/system:  5.14.14 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.7 
    @mui/x-charts: ^6.0.0-alpha.15 => 6.0.0-alpha.15 
    @mui/x-data-grid:  6.6.0 
    @mui/x-data-grid-generator: ^6.6.0 => 6.6.0 
    @mui/x-data-grid-premium:  6.6.0 
    @mui/x-data-grid-pro: ^6.19.1 => 6.19.1 
    @mui/x-date-pickers:  6.16.2 
    @mui/x-date-pickers-pro: ^6.16.2 => 6.16.2 
    @mui/x-license-pro: ^6.6.0 => 6.6.0 
    @types/react:  18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.9.5 
```
</details>

**Search keywords**: Auto add row, processRowUpdate,
**Order ID**: 67382

**Comment by michelengelen** [comment]
Hey @Luis-Ramirez21x 
This is definitely possible.
Here is an example of what you want to accomplish: [DEMO](https://codesandbox.io/p/sandbox/silent-field-tlhh5x)
It will need some adjustments to fit your case, but this conveys the idea behind it.

Would that be a sufficient solution for you?

@cherniavskii another candidate for a new recipe?

**Comment by Luis-Ramirez21x** [comment]
@michelengelen Thank you for responding so quickly! I'm not able to access your demo, are you able to open up permissions on it? 

![Screenshot_20240515_104109](https://github.com/mui/mui-x/assets/86748117/bd42eae5-09e9-42f0-8202-12a67b743ec4)

**Comment by michelengelen** [comment]
@Luis-Ramirez21x  it should now be public ... sry for the confusion!

**Comment by cherniavskii** [comment]
@michelengelen Does it work for you? The focus doesn't move to the first column:

https://github.com/mui/mui-x/assets/13808724/b3f92dcb-a342-4902-8e2f-7add1e4da198

Passing `fieldToFocus` to `startRowEditMode` seems to be working: https://codesandbox.io/p/sandbox/friendly-sun-8n5ctg

**Comment by Luis-Ramirez21x** [comment]
@michelengelen  no worries, I can see the demo now. 

The demo is a close solution, but I encountered an issue with mismatching IDs when creating a new row and then retrieving the updated 'valid' row id from the server.

The process issue : 
1.  Create a new row with a random id and empty fields 
2.  Make a request to the server to save in the processRowUpdate callback
3.  The server responds with the saved instance (valid id and saved fields)
4.  I need to replace that row but the return for processRowUpdate is expecting the row with its old random id

Your demo did point me in the right direction though.  I added a few lines to process row update to get what I needed.


```
if (_newRow) {
        apiRef.current.updateRows([{ id: id, _action: 'delete' }]); //delete the new (random id) row
        apiRef.current.updateRows([{...response}]); //add the valid row from the server response
        handleAddRow();
        return {};
      }
```

Although I'm not sure if this is the most efficient way to do this. What do you think? 
Here's my working demo.

https://github.com/mui/mui-x/assets/86748117/95e47f42-5082-48f1-a220-b30bb560e15f

**Comment by Luis-Ramirez21x** [comment]
Sorry for the spammed comments. This seems to do the trick, just seems a bit slower than before probably not noticeable with a Prod build. 

```
if (_newRow) {
        apiRef.current.updateRows([{...response}]); //add the valid row from the server response
        handleAddRow();
        return {...oldItem, _action: 'delete'};
      }
```

**Comment by Luis-Ramirez21x** [comment]
Here's a simplified [sandbox](https://codesandbox.io/p/sandbox/tender-meninsky-k8gv87?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw6vyasx00072v6l6dhki0el%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw6vyasx00032v6l7h4onbb6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw6vyasx00042v6ls9snaiyd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw6vyasx00062v6lg62wo332%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw6vyasx00032v6l7h4onbb6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6vyasx00022v6l3ym4498i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw6vyasx00032v6l7h4onbb6%2522%252C%2522activeTabId%2522%253A%2522clw6vyasx00022v6l3ym4498i%2522%257D%252C%2522clw6vyasx00062v6lg62wo332%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6vyasx00052v6lxz9esyqv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw6vyasx00062v6lg62wo332%2522%252C%2522activeTabId%2522%253A%2522clw6vyasx00052v6lxz9esyqv%2522%257D%252C%2522clw6vyasx00042v6ls9snaiyd%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw6vyasx00042v6ls9snaiyd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of the above

**Comment by Luis-Ramirez21x** [comment]
Hey @michelengelen! 

![Screenshot_20240516_085321](https://github.com/mui/mui-x/assets/86748117/f89018f3-3d00-4027-831e-d6a281b8c9ad)
The following are `console.log(apiRef.current.getSortedRows())` of

1. When adding a new row and it's in editing-state 
2. After saving the row with your suggested implementation. 

The `id` looks to be set.
But returning just the response in processRowUpdate which calls `.updateRows()'` just adds the row because the `ids` are different as per the [docs](https://mui.com/x/react-data-grid/row-updates/#the-updaterows-method). 

So what happens is: 

1. The original new row is kept
2. The server response row is added 
3. The extra intended new rew is also added. 


I say all this to say that the previous code snippet provided seemed to do the trick. Now I just have to figure out what's affecting the focus state. I think this issue is good to close. 

Thanks for taking the time to help! 
You guys are doing great work and I'm very excited to use the Server Side DataGrid!

**Comment by romgrk** [comment]
I have tried the simplified sandbox linked above and I can't reproduce the flicker in the video. If you need further assistance, would it be possible to reproduce the issue in the sandbox?

I'm not sure if there is a way to always have an empty row at the bottom, but it should be possible to remove/add it in the same operation as the new server row is received, which should get rid of the flicker I think.

**Comment by Luis-Ramirez21x** [comment]
@romgrk 
Looks like the flickering issue was fixed in an update. I was on  `@mui/x-data-grid-pro:  6.19.1` 
and updated to `@mui/x-data-grid-pro: 7.4.0` 

That fixed the flicker issues I was having. It's working perfectly now :+1: !

**Comment by Luis-Ramirez21x** [comment]
If you could point me towards what that fix might've been that would be awesome, just out of curiosity 😁 .

**Comment by romgrk** [comment]
I don't know what fixed it, we changed a lot in v7. Let us know if there's anything else we can do, otherwise you can close the issue.

**Comment by Luis-Ramirez21x** [comment]
Hey @romgrk @michelengelen! 

I need your guidance once again. Turns out the flicker is still occurring.  
The issue seems to be when I add the `autoHeight` prop. 

See this updated [demo ](https://codesandbox.io/p/sandbox/tender-meninsky-k8gv87?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw6vyasx00072v6l6dhki0el%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw6vyasx00032v6l7h4onbb6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw6vyasx00042v6ls9snaiyd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw6vyasx00062v6lg62wo332%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw6vyasx00032v6l7h4onbb6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6vyasx00022v6l3ym4498i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw6vyasx00032v6l7h4onbb6%2522%252C%2522activeTabId%2522%253A%2522clw6vyasx00022v6l3ym4498i%2522%257D%252C%2522clw6vyasx00062v6lg62wo332%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6vyasx00052v6lxz9esyqv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw6vyasx00062v6lg62wo332%2522%252C%2522activeTabId%2522%253A%2522clw6vyasx00052v6lxz9esyqv%2522%257D%252C%2522clw6vyasx00042v6ls9snaiyd%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw6vyasx00042v6ls9snaiyd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).
Simply add a row and you'll notice the first row flicker. How can I get rid of this if I need to have all rows displayed?

**Comment by Luis-Ramirez21x** [comment]
i'll close and reopen in a sperate issue
