### ISSUE TITLE
[data grid] CTRL + A not working when using TextField into DataGrid Table  

### ISSUE THREAD

**Issue by saadiButt-1995** [mui/mui-x#13136]
### Steps to reproduce

Link to live example: (required)

Steps:
1. import { DataGrid, GridColDef, GridRowId } from '@mui/x-data-grid'
2. use DataGrid
3. use MUI TextField  into an column and try to write something in that field.
4. now, copy the text by using command ( CTRL + A )

### Expected behavior

CTRL + A should select the whole text in the input field while it is giving correct behavior when CAPSLOCK is on

### Your environment

<details>
  <summary><code>import { DataGrid, GridColDef, GridRowId } from '@mui/x-data-grid'</code></summary>

```
  Windows 11  on chrome browser 
  NextJS Sneat theme
```
</details>

**Search keywords**: DataGrid, Table, CTRL + A, text selection

**Comment by michelengelen** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find a examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
