### ISSUE TITLE
[charts] How to add horizontal layout for Responsive charts?

### ISSUE THREAD

**Issue by MainaMwangiy** [mui/mui-x#13142]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-zb9yvc-gyrtno?file=Demo.js and https://stackblitz.com/edit/react-nn5u1e-yjybdr?file=Demo.js
Steps:
1. Check two examples above and try to add `layout: 'horizontal'` property and it doesn't work. 

### Current behavior

https://stackblitz.com/edit/react-zb9yvc-gyrtno?file=Demo.js and https://stackblitz.com/edit/react-nn5u1e-yjybdr?file=Demo.js
charts are not adding horizontal layout when I add `layout: 'horizontal` on the code. 

The working code for horizontal layout only works for when we do not have a responsive chart i.e. one that uses ResponsiveChartContainer. Take a look at this example from the documentation. https://mui.com/x/react-charts/bars/#system-HorizontalBars.js

### Expected behavior

Looking for a way to add `layout: 'horizontal'` property on charts that are responsive and that are using ResponsiveChartContainer. When the chart is responsive, the property doesn't work. The documentation does not provide any other property for this. 

### Context

Need to have the following responsive charts in horizontal layout. 

1. Multi Line charts - line charts having more than one line data and is responsive
2. Combined Bar and Line charts
3. Bar Chart

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: horizontal layout muix charts

**Comment by michelengelen** [comment]
Hey @MainaMwangiy and thanks for opening this feature request.
I did add it to the board for the charts team to have a look. 👍🏼
