### ISSUE TITLE
[charts][PieChart] Unable to style default tooltip

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#13153]
### Steps to reproduce

Link to live example: (required)

Steps:
1.I have tried multiple ways to do the styling for the default tooltip of PieChart on the below sandbox but nothing works- 
https://codesandbox.io/p/sandbox/elegant-dirac-j7tjhx?file=%2Fsrc%2FDemo.tsx%3A38%2C19
2.
3.

### Current behavior

Can't change styling of PieChart default Tooltip.

### Expected behavior

Should be able change styling of PieChart default Tooltip.

### Context

Trying to achieve a design according a particular design system.

### Your environment

Can't change styling of PieChart default Tooltip.

**Search keywords**: MUI PieCharts
**Order ID**: xx

**Comment by michelengelen** [comment]
Could you make the sandbox public please?

**Comment by noobDev31** [comment]
thanks @michelengelen
