### ISSUE TITLE
[pickers] First date part is not automatically selected on Mac OSX

### ISSUE THREAD

**Issue by DASPRiD** [mui/mui-x#13177]
### Steps to reproduce

Link to live example: https://mui.com/x/react-date-pickers/date-picker/

Steps:
1. Go to https://mui.com/x/react-date-pickers/date-picker/
2. Click on the `Basic date picker` field

### Current behavior

On Mac OSX (both Firefox and Safari) it highlights/selects the entire field instead of just the `MM` part. Thus the user cannot enter the date manually, unless they click on the individual part again.

### Expected behavior

On focus it should select the first date part like on other browser/system combinations.

### Your environment

This issue was reported by a client. They are running Mac OSX (latest version) and tested both Safari and Firefox (latest version respectively). They tested with a clean profile, so no influence from any addons.

**Search keywords**: Mac OSX Safari Firefox DatePicker

**Comment by LukasTy** [comment]
Hello @DASPRiD, could you provide a video showcasing the issue or at least the exact steps to reproduce it?

I've tried it on MacOS 14.2.1 on Safari and Firefox and the behavior seems correct to me... 🤷 🙈 

https://github.com/mui/mui-x/assets/4941090/2116e11d-5790-498c-b5d5-a3fdd393921d

**Comment by DASPRiD** [comment]
When the client clicked within the field where the `DD` part is, it was working as expected. Clicking outside (right next to the `YYYY`) should trigger the issue. Let me see if I can get a video from them.

**Comment by DASPRiD** [comment]
https://github.com/mui/mui-x/assets/233300/5310b62b-f499-4604-a1e9-7450800aea07

**Comment by michelengelen** [comment]
@LukasTy I can reproduce this as well, but only when I hold the mouseclick for a short amount of time ... maybe when micromovement of the cursor is happening it will run into the drag-selection 🤷🏼

**Comment by LukasTy** [comment]
@DASPRiD @michelengelen I can also only experience this problem when moving the mouse during the click...
I'm not sure we can do anything about this as it is how OS/Browser/input works... 🤷 
There are multiple ways to interact with the Pickers. Users can focus the input using tabulation, they can also use the Calendar to select a preferred day. 🤔 

I would suggest trying the [accessible DOM structure](https://mui.com/x/react-date-pickers/fields/#accessible-dom-structure) field and check if you prefer that behavior better. 😉
