### ISSUE TITLE
Module parse failed: Unexpected token when upgrading from "@mui/x-data-grid" to "@mui/x-data-grid-pro" (Order Number : 89781)

### ISSUE THREAD

**Issue by pansuriyaimpexIT** [mui/mui-x#13170]
We are in the process of upgrading from @mui/x-data-grid version 5.17.18 to @mui/x-data-grid-pro version 7.3.2 in our React application. However, after following the steps in the documentation, we encountered the following error:

Module parse failed: Unexpected token (101:69)
You may need an appropriate loader to handle this file type.
|   if (column.valueParser) {
|     var parser = column.valueParser;
>     parsedValue = Array.isArray(filterItem.value) ? filterItem.value?.map(function (x) {
|       return parser(x, undefined, column, apiRef);
|     }) : parser(filterItem.value, undefined, column, apiRef);

Steps Taken

1. Babel Configuration: Suspecting the issue might be related to Babel configuration, I created webpack.config.js and babel.config.js files to configure Babel. Despite these changes, the error persists.
2. Babel Loader Upgrade: I upgraded the Babel loader to the latest version, but our React app requires Babel version 8.0.5, causing a version mismatch that prevents further upgrades.
3. Installed Plugins: I installed @babel/plugin-proposal-class-properties and @babel/plugin-proposal-optional-chaining to handle the optional chaining syntax, but the issue remains unresolved.

Environment:
Node Version: v16.17.0

**Search keywords**:

**Comment by LukasTy** [comment]
Hello @pansuriyaimpexIT, have you checked https://github.com/mui/mui-x/issues/12612 and the resulting addition to the [migration docs](https://mui.com/x/migration/migration-data-grid-v6/#drop-webpack-4-support)?
Are you still on Webpack 4 by any chance? 🤔

**Comment by walberleal** [comment]
update your react-scripts
