### ISSUE TITLE
[pickers] Add an Icon Picker component

### ISSUE THREAD

**Issue by TheOneTheOnlyJJ** [mui/mui-x#13206]
### Summary

I've recently come across the need to allow users to select arbitrary icons for display in chips. For stylistic consistency with the rest of the UI, I only want to allow them to select icons from the Material Icons selection, and specifically only the `outlined` style. Looking for a way to do this, I've realised that the icon browser from the [Material Icons](https://mui.com/material-ui/material-icons/) page on the official website is just the tool I need. Given that it's already there, I figured it may be possible to expose it as a library component.

The Icon Picker could take as arguments the icons, their display names, and their style/category tag(s). The radio button style/category selector menu on the left could be generated internally based on the icon categories provided. Multiple selection could be supported as well.

To use it with the current Material Icons, like on the official page, the `@mui/icons-material` package (or the Icon Picker's component module) could export a new utility function to generate the icon lists required as inputs for the Icon Picker. This function could take as arguments the style of the icons to be returned (one or more of `filled`, `outlined`, `rounded`, `two tone`, `sharp`). A way to obtain the desired display name text for each icon should also be provided. Maybe by having as a 2nd function argument a transformer callback that gets mapped to every icon name. This way, we could turn their names from camel case into natural human format, or any other format we desire.

### Examples

The official website icon browser (as of the opening of this issue):
![image](https://github.com/mui/mui-x/assets/63308694/810c1bce-81d7-4f09-8aef-05f1b08316c8)

### Motivation

There is no easy way to prompt a user to pick an icon (or more), while there already is such a component on the official Material UI website, on the Material Icons page. 

**Search keywords**: icon picker component material icons

**Comment by LukasTy** [comment]
Thank you for an interesting suggestion. 🙏 
The idea makes total sense, I'm just not sure which package/repository it should belong to.
I'm leaning towards this being a `@mui/lab` export; thus, this is more of a `mui/material-ui` repository issue.
WDYT @joserodolfofreitas @michelengelen?

**Comment by michelengelen** [comment]
@LukasTy this feels like it should be in the labs repo for exploration.
I can imagine there might be more functionalities we could be building this with (custom emoji picker, kaomoji pickers, fonts, etc.)
Interested on your opinion though @joserodolfofreitas

**Comment by TheOneTheOnlyJJ** [comment]
> @LukasTy this feels like it should be in the labs repo for exploration. I can imagine there might be more functionalities we could be building this with (custom emoji picker, kaomoji pickers, fonts, etc.) Interested on your opinion though @joserodolfofreitas

Upon further consideration, I believe it could be implemented as a general-purpose content picker, ingesting any kind of content through its arguments and offering callbacks that get applied to said content. For example, how to display the content, how to format the display name, how to handle content categories, what callback to run when selecting content, etc. It truly has the potential to handle a lot of use cases, but its complexity would be a lot greater than what I was initially imagining.

**Comment by LukasTy** [comment]
@TheOneTheOnlyJJ it feels like we are leaning towards a customizable [Autocomplete](https://mui.com/material-ui/react-autocomplete/) approach or something that [downshift](https://www.downshift-js.com/) provides. 🤔 
What features do you think the `Autocomplete` is missing to cover what you are imagining?

**Comment by TheOneTheOnlyJJ** [comment]
> @TheOneTheOnlyJJ it feels like we are leaning towards a customizable [Autocomplete](https://mui.com/material-ui/react-autocomplete/) approach or something that [downshift](https://www.downshift-js.com/) provides. 🤔 What features do you think the `Autocomplete` is missing to cover what you are imagining?

The main attraction of this picker over the current Autocomplete is the UI, as showing over 2100+ icons in a vertical dropdown menu is not ideal for UX. I feel like the Autocomplete is the best choice for when users have to select text, but it does not provide that good of an experience for visual content/media. For my use case, when the user wants to select an icon, the emphasis should be on the icons themselves, not as much on their names. I can even imagine turning this into a media gallery browser if we could support [Cards](https://mui.com/material-ui/react-card/) as selectable content. Being able to select the content size and number of columns would make it very flexible for different size emphasis of the content.

I forgot to mention this initially, but the icon browser from the official website recommends icons based on synonyms as well, which I do not see how to achieve with an Autocomplete component. The one from [Google's Material Icons page](https://fonts.google.com/icons) does the same, and is similar to the one from Material UI. Supporting this would greatly increase UX, especially given how icons can be described by many words different to their names.

Also of note is the way users can filter the content based on categories. In the one from the MUI website, there are radio buttons on the left to do this. In the Autocomplete, the groups are merely an indication as to what category of content you are currently browsing through while searching for your desired option, and there is no out-of-the-box way to exclude categories entirely from the selection options. Going even further into this, if we refer to the categories as content tags, we could even support nested tags through having a [Tree View](https://mui.com/x/react-tree-view/) with Checkbox selection enabled instead of the current Radio Buttons.

This kind of component would be very useful for a wide variety of use cases. Just while writing this reply I've come up with the following ideas for potential use cases:

- Video browser (like the YouTube browse page); Image browser; Audio browser (would go very well with [wavesurfer.js](https://wavesurfer.xyz/))
- Profiles/Friends list browser for social applications
- File explorer

If Cards are supported, the possibilities are truly endless, as any kind of compact displayable content could be made selectable by this component. Dashboards could make very good use of this. I believe there's enough feature area to cover that this could have features included in the paid plans.

**Comment by TheOneTheOnlyJJ** [comment]
Also, for my specific use case of selecting icons, even if I would use an Autocomplete component, I still have no way to import all the icons of a specific style at once. The utility function that returns all the icons from the icons package with optional specific styles only is still required to make this possible to implement. It is not feasible to write out thousands of imports by hand :)

**Comment by LukasTy** [comment]
Thank you for all the detailed input! 🙏 
I'm putting this issue into the `eXplore` team grooming list. 😉

**Comment by TheOneTheOnlyJJ** [comment]
> Thank you for all the detailed input! 🙏 I'm putting this issue into the `eXplore` team grooming list. 😉

This might be off-topic, but is this list public so we can see what the team is cooking a little earlier?

**Comment by LukasTy** [comment]
Sorry, no, only the [Public Roadmap](https://github.com/mui/mui-x/projects/1) is available for everyone. 😉

**Comment by TheOneTheOnlyJJ** [comment]
I would like to add an explicit example of how the utility function from the icons package I was talking about could look like:
```js
import { getIcons } from '@mui/icons-material';
import SvgIcon from '@mui/material/SvgIcon';

// Get all icons in all styles
let allIcons: Array<SvgIcon> = getIcons();

// Get all outlined icons
let allOutlinedIcons: Array<SvgIcon> = getIcons({ styles: [ 'outlined' ] });

// Get only filled and outlined icons
let filledAndOutlinedIcons: Array<SvgIcon> = getIcons({ styles: [ 'filled', 'outlined' ] });

// Get only filled icons with the "home" tag
// Should only return these icons: https://mui.com/material-ui/material-icons/?query=home
let filledHomeIcons: Array<SvgIcon> = getIcons({ styles: [ 'filled' ], tags: [ 'home' ] });

// Get all icons with the "home" tag, in all available styles
let allHomeIcons: Array<SvgIcon> = getIcons({ tags: [ 'home' ] });
```
With this kind of API, the Icon Picker component can pass its state as arguments to the `getIcons` function and fulfil my requirement. When the user would change the style option(s) or change the search word, the state would update and call the function again, and the Icon Picker would rerender to only display the new icons returned by `getIcons`.

Additionally, a function that allows getting all tags for a specific icon (maybe call it `getIconTags`) should also be available for flexibility (show the user the keywords/tags a specific icon can be found by), but this would require an internal ID for every icon to be passed as an argument to that function. I am not that accustomed to the internals of the icons package, so I do not know how difficult such an addition would be.

If this icons-related reply is out of topic here, feel free to move (or copy) this issue to the corresponding repository (`material-ui`).

**Comment by oliviertassinari** [comment]
Closing as won't fix.

**Comment by TheOneTheOnlyJJ** [comment]
> Closing as won't fix. The looks like a niche use case that has little intrinsic complexity to solve, so not relevant for MUI X. It looks like an AI model could easily solve this.

I agree with you. This issue was opened to address the pain point of importing and searching for the icons more than the icon picker itself.
Even with this rightfully closed, I still believe the icons package could receive an overhaul consisting of something similar to what I suggested in mui/material-ui#42450 and in mui/material-ui#42704.

**Comment by kekelele19851224-lgtm** [comment]
Star kaomoji cover every constellation vibe — from a subtle (✧) in an Instagram bio to a full (★_★) starstruck reaction. Whether you need kaomoji star decorations for an aesthetic Twitter reply, kaomoji stars framing a K-pop tweet, or stars kaomoji trailing a magical bio line, this collection covers all seven flavors.I highly recommend checking out
<a href="https://aikaomoji.com/sad-kaomoji/
">AI Kaomoji Generator</a>
