### ISSUE TITLE
[data grid] Page Size Options dropdown missing

### ISSUE THREAD

**Issue by Preefix** [mui/mui-x#13211]
### The problem in depth

Hey,

The dropdown for the page size options is not displayed. It renders a couple of times during the mount but disappears when the rows finished loading.

 

For pagination we use the following setup

![image](https://github.com/mui/mui-x/assets/112691741/12a04900-68ed-4121-9c14-4fd9bc8be580)

 
![image](https://github.com/mui/mui-x/assets/112691741/80cb6228-52b5-4b21-a443-6105b7be0865)

The **usePersistedState** is just a custom hook storing the provided value in the local storage. The current paginiation is also provided within the initialState of the Grid:

`
initialState={{
    pagination: {
       paginationModel
    }
}}
`

I exepct the paginiation dropdown to be visible or at least a console warning telling me why its not rendered.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4 
    @emotion/styled: 11.11.5 => 11.11.5 
    @mui/base: ^5.0.0-beta.4 => 5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.18 
    @mui/icons-material: 5.15.16 => 5.15.16 
    @mui/material: 5.15.16 => 5.15.16 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.3.2 
    @mui/x-data-grid-premium: 7.3.2 => 7.3.2 
    @mui/x-data-grid-pro:  7.3.2 
    @mui/x-date-pickers: 7.3.2 => 7.3.2 
    @mui/x-license: 7.2.0 => 7.2.0 
    @mui/x-tree-view: 6.17.0 => 6.17.0 
    @types/react: 18.2.55 => 18.2.55 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.4.5 => 5.4.5 
```
</details>

**Search keywords**: paginiation
**Order ID**: 83002

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
