### ISSUE TITLE
[data grid] Textfield with in renderCell not storing value

### ISSUE THREAD

**Issue by ashokReddy00931993** [mui/mui-x#13220]
### Steps to reproduce

Link to live example:
: https://stackblitz.com/edit/ashok-reddy?file=muidatagrid.tsx,index.html,index.tsx

Steps:
1.When user enter value of Mui textfiled with in a mui data grid cell then the enter value getting disappearing after cursor moved from the filed  

The following screenshot where user enter value : 
![image](https://github.com/mui/mui-x/assets/170495763/03dca546-d75a-4578-a9ac-e3466ff6e325)
The following screenshot shows where value was disappear after moved from the filed .

![image](https://github.com/mui/mui-x/assets/170495763/5c0b3b8c-d056-4943-92f6-b5c6b45d2ea6)

### Current behavior

When user enter the value in MUi textfiled with mui data grid cell ,it should be appear the user enter value in mui texfield with Mui data grid cell after cursor  was moved out from filed but it is disappearing with these attached code in provide as link to live example.

### Expected behavior

When user enter the value in MUi textfiled with mui data grid cell ,it should be appear the user enter value in mui texfield with Mui data grid cell after cursor  was moved out from filed.

### Context

 i was trying to run an example project with flow to demonstrate a bug in current version of react and mui data grid and attached as live example 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Material-UI | 5.15.6
React | 18.2.19
browser | chome
Muidatagrid | 7.1.1
react-hook-form| 7.51.2

</details>

**Search keywords**: mui data grid
**Order ID**: 2333

**Comment by michelengelen** [comment]
Could you please elaborate on what you want to achieve here? 
The cell does re-render when it loses focus, so any state inside will get lost.

If you can outline what your desired outcome is more precisely we can help you in achieving this!

**Comment by ashokReddy00931993** [comment]
How can we achieve suppose if user enter value then when it loses focus ...the enter value should appear in textfiled  it should disappear is there any way ? one more thing in live example  when user enter value it suppose to be invoke onchnage event even that is also not triggering ? can you try putting some console or alert   onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                // alert("enter")   ----> on enter value this suppose to be trigger but it was not happing ?

                setValue('value', e.target.value);

                onChange(e.target.value);
              }}
            **Note : My desire is here when i enter value then when it focus loses ,,i want to see the enter value in textfiled of value with mui data grid cell?**

**Comment by michelengelen** [comment]
This does sound like you want to have basic editing functionality, wich is already present.
Why would you want a custom input that does nothing but hold a value?
I don't understand the necessity for that.

You can add your [custom edit cell renderer](https://mui.com/x/react-data-grid/editing/#create-your-own-edit-component) if you need that.

**Comment by ashokReddy00931993** [comment]
it is my business requirements 
Why would you want a custom input that does nothing but hold a value? yes it should hold value to save backend service we want use only Custom mui textfiled to edit cell value here...
Note : we want MUI textfield to edit cell value,it is my business requirements .

**Comment by michelengelen** [comment]
In that case you can simply follow this to add a custom input component: [custom edit cell renderer](https://mui.com/x/react-data-grid/editing/#create-your-own-edit-component)

And this guide shows how you can support [server side persistence](https://mui.com/x/react-data-grid/editing/#the-processrowupdate-callback).

It is a very common use case and well documented.

**Comment by ashokReddy00931993** [comment]
In that case you can simply follow this to add a custom input component: [custom edit cell renderer](https://mui.com/x/react-data-grid/editing/#create-your-own-edit-component)? if i use this by default is it not showing edit Mui textfiled filed on double click it showing edit ? now how we can show it edit for default it?

**Comment by michelengelen** [comment]
You can use the [controlled edit mode model](https://mui.com/x/react-data-grid/editing/#controlled-model) for this.

Here is an [example](https://codesandbox.io/p/sandbox/agitated-flower-cv44dl)
