### ISSUE TITLE
[charts] LineChart doesn't draw graph on page load

### ISSUE THREAD

**Issue by Marius555** [mui/mui-x#13252]
### Steps to reproduce

Link to live example: (required)

``` 
"use client"
import { Box, Paper } from '@mui/material'
import { LineChart } from '@mui/x-charts/LineChart';
import { Typography } from '@mui/material';
import dayjs from 'dayjs';

const DoctorPay = ({ records }) => {
    const dates = []
    const amount = []

    records.map((item) => {

        const um = dayjs(item.Create).toDate()
        dates.push(um)
        amount.push(item.Amount)
    })


    return (
        <>
            <Paper sx={{ padding: "10px", display: 'flex', position: "relative", margin: "1rem", flexDirection: "column" }}>
                <Box>
                    <Typography sx={{ fontWeight: "600" }}>Payments</Typography>
                </Box>
                <Box sx={{ width: "100%", height: "100%", overflow: "hidden" }}>
                    <LineChart
                        disableLineItemHighlight
                        xAxis={[
                            {
                                data: dates,
                                scaleType: 'time'
                            }]}

                        series={[
                            {
                                data: amount,
                                area: true,
                                scaleType: "band",
                                // showMark: false,
                                label: "amount"
                            },

                        ]}
                        slotProps={{ legend: { hidden: true } }}
                        margin={{ top: 10, bottom: 20 }}



                        bottomAxis={{
                            disableLine: true,
                            disableTicks: true,
                        }}
                        leftAxis={{
                            disableLine: true,
                            disableTicks: true,
                        }}
                        grid={{ horizontal: true }}
                        height={155}


                    />
                </Box>
            </Paper>
        </>
    )
}

export default DoctorPay
```

### Current behavior

On page load LineChart doest draw lines, it have background, lines, labels, but it only draws lines when i hover or interact with chart in any way. on BarChart it works well, chart loads on page load thats what i  want.

### Expected behavior

https://github.com/mui/mui-x/assets/25990751/127a513a-d413-4c46-9b52-d02afe84f0bd

### Context

i want to draw line on page load 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: LineChart doesn't draw graph on page load

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
