### ISSUE TITLE
[data grid] GridHeaderCheckbox.js failed to compile x-data-grid after upgrading to v7

### ISSUE THREAD

**Issue by borjaevo** [mui/mui-x#13266]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Working x-data-grid v6 app
2. Upgrade to 7
3. Failed to compile

### Current behavior

Failed to compile due to missing loader or handler?

`./node_modules/@mui/x-data-grid/components/columnSelection/GridHeaderCheckbox.js 108:25
Module parse failed: Unexpected token (108:25)
You may need an appropriate loader to handle this file type.
|     onKeyDown: handleKeyDown,
|     disabled: !isMultipleRowSelectionEnabled(rootProps)
>   }, rootProps.slotProps?.baseCheckbox, other));
| });
| process.env.NODE_ENV !== "production" ? GridHeaderCheckbox.propTypes = {`

### Expected behavior

To compile and show the data-grid with the new resizing column features

### Context

I upgraded the library to have the resizing column feature not present in v6. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  I use Firefox. 
  System:
    OS: Linux 6.8 Pop!_OS 22.04 LTS
  Binaries:
    Node: 21.0.0 - /usr/local/bin/node
    npm: 10.2.0 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 124.0.6367.60
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.18 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/lab: ^5.0.0-alpha.123 => 5.0.0-alpha.123 
    @mui/material: ^5.15.14 => 5.15.18 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^7.0.0 => 7.0.0 
    @mui/x-date-pickers: ^6.18.6 => 6.18.6 
    @types/react:  17.0.73 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.0.0 => 18.0.0 
    typescript:  5.3.3 
```
</details>

**Search keywords**: GridHeaderCheckbox.js loader mui x-data-grid

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @borjaevo ... this looks like a duplicate (or strongly related to) #12612 

Could you try adding a solution as mentioned in this comment: https://github.com/mui/mui-x/issues/12612#issuecomment-2042808701

**Comment by borjaevo** [comment]
> Hey @borjaevo ... this looks like a duplicate (or strongly related to) #12612
> 
> Could you try adding a solution as mentioned in this comment: [#12612 (comment)](https://github.com/mui/mui-x/issues/12612#issuecomment-2042808701)

Im not sure what was the problem, but upgrading webpack seems to solve the problem.
