### ISSUE TITLE
[data grid] Upgrade v6 => v7 breaks existing styles applied

### ISSUE THREAD

**Issue by vishal-kadmos** [mui/mui-x#13265]
### The problem in depth

Updated Mui x Pro from v6 to v7 latest and it is breaking custom applied styles. 
This upgrade is breaking many classes applied. 
Example

1. `.MuiDataGrid-withBorderColor` is not applied to cells anymore in v7 (it is in v6) instead default rowBorderColor is applied
**v6**
<img width="1920" alt="Screenshot 2024-05-27 at 3 20 32 PM" src="https://github.com/mui/mui-x/assets/102800997/7bf4ff4d-93c6-4e62-8ff7-6480c3f8a604">

**v7**
<img width="1920" alt="Screenshot 2024-05-27 at 3 26 41 PM" src="https://github.com/mui/mui-x/assets/102800997/4de5bd83-2a34-4b0a-9a7c-4e2038429331">

2. Similar issue for columnHeaders changed structure breaking existing style overrides from v6
**v7**
<img width="1399" alt="Screenshot 2024-05-27 at 9 48 14 PM" src="https://github.com/mui/mui-x/assets/102800997/16b2e086-efb7-477f-8393-043563300c8f">

**v6**
<img width="1393" alt="Screenshot 2024-05-27 at 9 48 54 PM" src="https://github.com/mui/mui-x/assets/102800997/40fd217d-ca56-4bfa-8756-c7148d8c6df9">

3. slotProps overrides for popers not working within datagrid. Sample code below works fine for v6 but not working at all for v7.
```
 slotProps={{
          basePopper: {
            sx: {
              "& .MuiPaper-root": {
                boxShadow: "none",
                background: theme.custom.paper.background,
                border: `1px solid ${theme.custom.paper.border}`,
                borderRadius: "8px",
                padding: "8px",

                "& .MuiList-root": {
                  padding: 0,
                  display: "flex",
                  flexDirection: "column",
                  gap: "4px",

                  "& .MuiMenuItem-root": {
                    fontSize: theme.typography.label.fontSize,
                    minHeight: "34px",
                    borderRadius: "4px",
                    padding: "8px",
                    "&:hover": {
                      background: theme.custom.menuItem.hover,
                      outline: "none",
                    },
                    "& .MuiListItemIcon-root": {
                      minWidth: "24px",
                    },
                  },
                },
              },
            },
          },
        }}
```

Its pain to fix these working solutions just because of updates as documentation lacks the clarity. Like https://mui.com/x/api/data-grid/data-grid/#data-grid-classes-withBorderColor still shows withBorderColor class documentation.

Appreciate help here. thanks!

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.

npx @mui/envinfo
Need to install the following packages:
@mui/envinfo@2.0.19
Ok to proceed? (y) y

  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.8.0 - ~/kadmos/customer-portal/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 125.0.6422.78
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.18
    @mui/material: ^5.15.18 => 5.15.18
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid:  7.5.1
    @mui/x-data-grid-pro: ^7.5.1 => 7.5.1
    @mui/x-date-pickers:  7.5.1
    @mui/x-date-pickers-pro: ^7.5.1 => 7.5.1
    @mui/x-license:  7.2.1
    @types/react: ^18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.4.5 => 5.4.5

```
</details>

**Search keywords**: v7.5.1
**Order ID**: 52198

**Comment by michelengelen** [comment]
Hey @vishal-kadmos 
thanks for opening this issue.

going over your points:
1. we did a big rework of the rendering structure in v7. That is likely why the class is not applied to the cells anymore. (@romgrk could you check if re-adding the class could pose a problem)
2. Same goes for the headers. The rework made it necessary to remove the inner wrapper of the header row. Thats why style overrides might break here as well.
3. This is still working for me on the latest version 
<img width="1113" alt="Screenshot 2024-05-28 at 12 27 59" src="https://github.com/mui/mui-x/assets/32863416/debb582c-c3de-472c-8896-7d03a27ef3d4">

```jsx
slotProps={{
  basePopper: {
    sx: {
      "& .MuiPaper-root": {
        boxShadow: "none",
        background: '#CCCCCC',
        border: `1px solid #DDDDDD`,
        borderRadius: "8px",
        padding: "8px",

        "& .MuiList-root": {
          padding: 0,
          display: "flex",
          flexDirection: "column",
          gap: "4px",

          "& .MuiMenuItem-root": {
            fontSize: 12,
            minHeight: "34px",
            borderRadius: "4px",
            padding: "8px",
            "&:hover": {
              background: '#DDDDDD',
              outline: "none",
            },
            "& .MuiListItemIcon-root": {
              minWidth: "24px",
            },
          },
        },
      },
    },
  },
}}
```

If you need some help adjusting your styles feel free to let us know and we try our best to solve this issue for you. 👍🏼

**Comment by romgrk** [comment]
I didn't figure people would be using that class to override the border color :| It's been removed in a few places. I would suggest to target the elements that you want to customize directly. We are also using the CSS variable `--DataGrid-rowBorderColor` on the root element. It's not documented so not technically guaranteed to be stable, but we have no reason to change it so it should be.

To help with more elements it would help to have a reproduction sandbox of which styles aren't working.
