### ISSUE TITLE
[data grid] Filter accepting empty text with spaces

### ISSUE THREAD

**Issue by adisekar** [mui/mui-x#13285]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Open https://mui.com/x/react-data-grid/filtering/
2. In the first example, click the top FILTERS section
3. In the value, type just a space. Here although no text is present, the Filters shows a count 1, as some filter was applied.

### Current behavior

For empty text (just spaces) the filter count is changed, and considered as valid text

### Expected behavior

For empty text (space) the text should be trimmed, and only valid string should be shown as filter. 

### Context

Having filter count increase leads users to believe there are some filters applied which is misleading

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 Chrome Browser. can be reproduced in https://mui.com/x/react-data-grid/filtering/
```
</details>

**Search keywords**: data grid filter accepts empty text

**Search keywords**:

**Comment by romgrk** [comment]
Spaces are ignored for that particular operator but can be meaningful for other operators, so I think we should keep the behavior as it is.

**Comment by michelengelen** [comment]
Good point ... lets keep it that way.
Thanks for taking the time opening an issue @adisekar ... Greatly appreciated! 🙇🏼
