### ISSUE TITLE
vite build with vite-plugin-javascript-obfuscator will cause x-data-grid error:TypeError: e.current.state.rows.dataRowIds.at is not a function

### ISSUE THREAD

**Issue by lling1105** [mui/mui-x#13287]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Current behavior

vite dev mode everything is working well, but vite build with vite-plugin-javascript-obfuscator plugin, everything about mui is working well, only the DataGrid(@mui/x-data-grid) not working, console error shows "TypeError: e.current.state.rows.dataRowIds.at is not a function"

vite config as below
```javascript
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import obfuscatorPlugin from "vite-plugin-javascript-obfuscator";
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(),
    obfuscatorPlugin({
      include: ["src/**/*.jsx","src/**/*.js"],
      exclude: [/node_modules/],
      apply: "build",
      debugger: true,
      options: {
        // your javascript-obfuscator options
        debugProtection: true,
        // ...  [See more options](https://github.com/javascript-obfuscator/javascript-obfuscator)
      },
    }),
  ],
  server:{
    
  }
})
```

DataGrid codes as below
```javascript
<DataGrid
            page={categoryAndPage.page}
            rows={data?data:[]}
            columns={columns}
            paginationModel={categoryAndPage.page}
            selectionModel={selectedEventIds}
            checkboxSelection={categoryAndPage.selectedMenuItem==="unread"?true:false}
            disableSelectionOnClick
            disableColumnMenu
            pagination={true}
            paginationMode="server"
            rowCount={rowCount}
            onPaginationModelChange={(param) => {
                ...
            }}
            onRowSelectionModelChange={(ids) => {
                ...

            }}
```

### Expected behavior

vite build with vite-plugin-javascript-obfuscator to production working well.

### Your environment

"@mui/x-data-grid": "^7.3.2",
"vite": "^4.2.0",
"vite-plugin-javascript-obfuscator": "^3.1.0"

**Search keywords**: e.current.state.rows.dataRowIds.at

**Comment by romgrk** [comment]
If the datagrid works without the plugin, then the problem is the plugin and you should be filing the issue with them, not here. Please confirm if the build works well without the plugin.
