### ISSUE TITLE
[data grid] sorting is not working for DD/MM/YYYY and MM/DD/YYYY date format it is only working for YYYY/MM/DD.

### ISSUE THREAD

**Issue by Dhivagaran30** [mui/mui-x#13299]
### Steps to reproduce

Link to live example: [demo](https://codesandbox.io/p/sandbox/distracted-noyce-7wsgnq?file=%2Fsrc%2FDemo.js%3A18%2C29)

### Current behavior

sort happening only basis of date for example if have following date 
1. 01/06/2021
2. 01/06/2019
3. 01/02/2020
4. 02/06/2019  while ascending  the data what are all the date has 01 comes first which not comparing year. similarly for MM/DD/YYYY format date.

### Expected behavior

It should sort 2019 first and then 2020 and then 2021 etc.. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: sorting is not working for DD/MM/YYYY and MM/DD/YYYY date format it is only working for YYYY/MM/DD.

**Comment by michelengelen** [comment]
Hey @Dhivagaran30 the sandbox is not accessible. Could you make it public for us?
Thanks! 👍🏼

**Comment by Dhivagaran30** [comment]
@michelengelen have make it public now can you try it now.

**Comment by michelengelen** [comment]
@Dhivagaran30 you were sorting strings, thats why it felt off.
We do support dates as a column type.
For this to work with your date strings you need to add `type: 'date'` to the column definition and a `valueGetter` to convert the string into a valid date object that the grid can compare:

I have updated your demo [here](https://codesandbox.io/p/sandbox/infallible-davinci-7sms7h)

Column definition used:
```tsx
const columns = [
  {
    headerName: "createDate",
    field: "createDate",
    width: "400",
    type: "date",
    valueGetter: (value) => {
      const dateParts = value
        .split("/")
        .map((str: string) => parseInt(str, 10));

      // monthIndex starts at 0
      return new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
    },
  },
];
```

**Comment by Dhivagaran30** [comment]
@michelengelen Thanks
