### ISSUE TITLE
[data grid] Search and filters are not working on array values.

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#13291]
### The problem in depth

I have a column that contains a list of names on that column 
![Screenshot 2024-05-29 140310](https://github.com/mui/mui-x/assets/115474187/84773115-5c2d-4296-b48b-5ca083d43f81)
my search and filter is not working. 
when i search brandon it show no result found 
![Screenshot 2024-05-29 140409](https://github.com/mui/mui-x/assets/115474187/e860d4a9-bcc8-4d4d-8e0a-df2e207ae582)
Also my filter is not working on fieldEngineer
![Screenshot 2024-05-29 140606](https://github.com/mui/mui-x/assets/115474187/48ff518f-91d2-4a20-aef7-77e3d524e389)

```
export const locationRowsV2 = [
  {
    id: 0,
    locationId: 'FL04A',
        fieldEngineer: [
      {
        name: 'Brandon Williams',
      },
      {
        name: 'Matthew',
      },
    ],
  },
  {
    id: 1,
    locationId: 'MI101H',
    fieldEngineer: [
      {
        name: 'Olivia Thomas',
      },
    ],
  },]
 const columns: GridColDef[] = [
    {
      field: 'locationId',
      headerName: 'Location ID',
      minWidth: 120,
      maxWidth: 200,
      flex: 0.2,
      display: 'flex',
      renderHeader: () => {
        return (
          <>
            {loading ? (
              <Skeleton
                animation="wave"
                variant="rounded"
                width={100}
              />
            ) : (
              <Typography
                variant="subtitle2"
                fontWeight={600}
              >
                Location ID
              </Typography>
            )}
          </>
        );
      },
      renderCell: (params: any) => (
        <>
            <Box
              sx={{
                '& a': {
                  color: 'text.primary',
                  textDecoration: 'none',
                  fontWeight: '500',
                  '&:hover': {
                    textDecoration: 'underline',
                  },
                },
              }}
            >
            </Box>
        </>
      ),
    },
      field: 'fieldEngineer',
      headerName: 'Field Engineer',
      minWidth: 140,
      flex: 0.1,
      display: 'flex',
  renderCell: (params: any) => (
        <>
          <div>
            {params.value.map((user: any, index: number) => (
              <div key={index}>
                {user.name}
              </div>
            ))}
          </div> 
 </>
 ),
      renderHeader: () => {
        return (
          <>
            {loading ? (
              <Skeleton
                animation="wave"
                variant="rounded"
                width={100}
              />
            ) : (
              <Typography
                variant="subtitle2"
                fontWeight={600}
              >
                Field Engineer
              </Typography>
            )}
          </>
        );
      },
    },
 <StyledDataGrid
            rows={locationRowsV2}
            columns={columns}
   slots={{
              toolbar: CustomToolbar,
            }}
 toolbar: {}
/>
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faMagnifyingGlass,
} from '@fortawesome/pro-light-svg-icons';
export const CustomToolbar: React.FC<CustomToolbarProps> = ({}) => {
return (
  <GridToolbarQuickFilter
                    placeholder="Search"
                    variant="outlined"
                    size="small"
                    sx={{
                      width: '100%',
                      maxWidth: '300px',
                      '& .MuiInputBase-input': {
                        py: 1.375,
                      },
                      '&.MuiFormControl-root': {
                        pb: 0,
                      },
                    }}
                    InputProps={{
                      startAdornment: (
                        <InputAdornment position="start">
                          <FontAwesomeIcon
                            icon={faMagnifyingGlass}
                            color="palette.neutral[500]"
                          />
                        </InputAdornment>
                      ),
                    }}
                  />
  <GridToolbarFilterButton
                      ref={setFilterButtonEl}
                      slotProps={{
                        button: {
                          sx: { fontSize: '14px' },
                          onClick: () => {
                            setFilterActive(true);
                          },
                        },
                      }}
                    />
    )
}
```

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data, Grid, Premium, GridToolbarQuickFilter, column, Array, Values
**Order ID**: 91010

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by mahammahmood** [comment]
I have a 'Field Engineer' and 'Location Manager' column that contain lists of names. My search and filter functions are not working on these columns. Here is a live demo of my problem.
[https://codesandbox.io/p/sandbox/nervous-rui-lqmcxl?file=%2Fsrc%2FApp.js](url)
![Screenshot 2024-06-03 112721](https://github.com/mui/mui-x/assets/115474187/0081cd40-e955-4b7d-801c-55d2df76c092)

**Comment by mahammahmood** [comment]
I have a 'Field Engineer' and 'Location Manager' column that contain lists of names. My search and filter functions are not working on these columns. Here is a live demo of my problem.
https://codesandbox.io/p/sandbox/nervous-rui-lqmcxl?file=%2Fsrc%2FApp.js<https://github.com/mui/mui-x/issues/url>



--
[https://ci4.googleusercontent.com/proxy/Pks96Mc87XT_YhiEIQLRZTKd9Dzonpz94BPL5IibxqqZpgTEzirBgdLwcyaYWRDXYFZqAmy-YEcKT04pqJjDtLaf3jNF6g2vhXMstRr3dbfhr7MMXRal8Oy5doI96o1g6ft2=s0-d-e1-ft#https://d36urhup7zbd7q.cloudfront.net/a/8c29f953-a677-415a-87b2-6205c1e7353a.png]

Maham Mahmood
Analyst Software Engineer
+92-323-4898018
|
***@***.***<http://goog_94248817/>
www.getfieldforce.com<http://www.getfieldforce.com/>


________________________________

**Comment by michelengelen** [comment]
OK, now i get it. 
For this to work you need to adjust the filtering logic on that column. Here is the section of the docs that explains ho to do that in detail: [Custom filtering logic](https://mui.com/x/react-data-grid/filtering/quick-filter/#custom-filtering-logic)

I have updated your example so you can have a look in a live env: [DEMO](https://codesandbox.io/p/sandbox/agitated-haze-3fgnr4)

I will close this issue now as it is working as expected, with just a missing part of the implementation. Just remember: whenever you have some custom value structure in your columns the default filtering/sorting logic is not going to work without modification. 💪🏼
