### ISSUE TITLE
[data grid] add a "does not contain" filter

### ISSUE THREAD

**Issue by benjimac93** [mui/mui-x#13300]
### Summary

Similar to the 'contains' filter on Data Grid, we've had quite a few customers request an option for "does not contain" 

**Search keywords**: Filter contains
**Order ID**: 83665

**Comment by michelengelen** [comment]
Hey @benjimac93 
You can easily add your own filter to the columns by following this section in the docs: [Create a custom operator](https://mui.com/x/react-data-grid/filtering/customization/#create-a-custom-operator)

I do agree that we could possibly add a reversed contains filter.
Would there be any objections handling this as a feature request @mui/xgrid ?

**Comment by cherniavskii** [comment]
Yes, we miss some options for excluding the data, e.g. "does not contain" and "does not equal" 👍🏻

**Comment by cherniavskii** [comment]
We need to do some benchmarks here. Potentially, almost all of the filter operators can be negated, but should we add a new one for each of those? It doesn't seem right. How about adding a negation modifier that can be applied to any filter operator? E.g. a "Not" checkbox that would negate the filter operation.
