### ISSUE TITLE
[charts] `ChartsTooltip` often not working properly when assigning `innerRadius` in series and using `ResponsiveChartContainer`

### ISSUE THREAD

**Issue by b310L** [mui/mui-x#13302]
### Current behavior

[ChartsTooltip] often not work properly when assign innerRadius in series and using [ResponsiveChartContainer].
when i hover to [PiePlot] and assign innerRadius in series often tooltip not appear.

### Expected behavior

[ChartsTooltip] must appear when using innerRadius

**Search keywords**: ChartsTooltip innerRadius ResponsiveChartContainer

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
