### ISSUE TITLE
[data grid] `checkboxSelection` Issue

### ISSUE THREAD

**Issue by TEAGASC-DEV** [mui/mui-x#13306]
### Steps to reproduce

Link to live example: (required)

### Current behavior

HI,

I added checkboxes to my DataGridPro component but when I click on the checkbox it won't toggle. However, when I clicked on the row the checkbox will check. Here is the code that I use.

```tsx
<DataGridPro
    getRowId={(row) => row.id}
    rows={issueObject}
    variant="outlined"
    style={{ height: "fit-conent" }}
    experimentalFeatures={{ newEditingApi: true }}
    columns={columns}
    getRowClassName={(params) =>
        `super-app-theme--${params.row.status}`
    }
    checkboxSelection
    onRowDoubleClick={handleDoubleClick}
    hideFooter={false}
    rowHeight={35}
    sx={{
        "& .MuiDataGrid-virtualScroller::-webkit-scrollbar": { display: "none" },
    }}
/>
```

### Expected behavior

When Checkbox is clicked it should be checked or unchecked.

### Context

When Checkbox is clicked it should be checked or unchecked.

### Your environment

 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.9.3 - S:\Repos\React\node_modules\.bin\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (125.0.2535.67)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.4
    @emotion/styled: ^11.10.6 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.15
    @mui/icons-material: ^5.11.0 => 5.15.15
    @mui/material: ^5.11.12 => 5.15.15
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/styled-engine-sc: ^5.11.11 => 5.14.12
    @mui/styles: ^5.10.14 => 5.15.15
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid: ^6.0.1 => 6.19.11
    @mui/x-data-grid-generator: ^6.0.1 => 6.19.11
    @mui/x-data-grid-premium:  6.19.11
    @mui/x-data-grid-pro: ^7.5.1 => 7.5.1
    @mui/x-date-pickers: ^6.0.0 => 6.19.9
    @mui/x-date-pickers-pro: ^7.5.1 => 7.5.1
    @mui/x-license: ^7.2.1 => 7.2.1
    @mui/x-license-pro:  6.10.2
    @types/react:  18.3.0
    react: ^18.0.0 => 18.3.0
    react-dom: ^18.0.0 => 18.3.0
    styled-components: ^5.3.8 => 5.3.11

I am using Edge/Firefox on my local virtual desktop. However, it will not work in Chrome either when we pushed it to devop.

**Search keywords**: DataGridPro checkbox
**Order ID**: 91445

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by TEAGASC-DEV** [comment]
Michel,

If you can have a Teams call with me I can show it to you on the screen.

Thanks
Huk
________________________________

**Comment by michelengelen** [comment]
Please try to replicate the issue in a **minimal** live example.
Most of the time it will clear itself up when doing so.

Also we can have a look at the code that causes that behavior.
A live meeting will likely not help.
