### ISSUE TITLE
[data grid] customized sort tooltip flashes during server-side sort

### ISSUE THREAD

**Issue by hmkiesel** [mui/mui-x#13315]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/frosty-jasper-84sc88?file=%2Fsrc%2FDemo.tsx%3A67%2C13

Steps:
1. hover over the sort icon until the tooltip text appears
2. click on the sort icon
3. watch as the tooltip changes to indicate the sort direction changes, then flashes when the sorted data gets populated.

### Current behavior

the sort icon tooltip is flashing indicating the custom sort icon is getting re-rendered (?) when the rows prop changes, even though no props related to the sort icon are changed.

### Expected behavior

the sort icon only gets re-rendered once when the sort direction changes, and doesn't flash when rows are updated.

### Context

this will improve the user experience and performance, by preventing unnecessary re-renders and providing a smoother transition.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.61
  npmPackages:
    @emotion/react: latest => 11.11.4 
    @emotion/styled: latest => 11.11.5 
    @mui/material: latest => 5.15.19 
    @mui/x-data-grid-pro: latest => 7.6.0 
    @types/react: latest => 18.3.3 
    react: latest => 18.3.1 
    react-dom: latest => 18.3.1 
    typescript: latest => 5.4.5 
```
</details>

**Search keywords**: custom sort tooltip rerendering server side sort flashing

**Comment by michelengelen** [comment]
You need to memoize the components that get passed into the slots. 
In this case the components are all static so moving them into variables does the job.

I have [updated your example](https://codesandbox.io/p/sandbox/infallible-tamas-8xwrjv).

Since this fixes the described problem I will close this issue.
Feel free to reopen if you encounter more problems with it. Thanks!
