### ISSUE TITLE
[charts] Allow basic customization of Sparkline y-axis

### ISSUE THREAD

**Issue by marvinruder** [mui/mui-x#13316]
### Summary

Right now the scaling mechanism of the y-axis in sparkline charts is somewhat obscure to me, and there are no parameters that influence that scale. It would be great to at least have a way to set the min and max values on the y-axis.

### Examples

The following two sparklines have the same parameters except for color and dataset:

<img width="256" alt="image" src="https://github.com/mui/mui-x/assets/18495294/846afbb2-329c-4d82-8be4-146b5f7a4841">

(The numbers below the slider on the left show the min and max values in the datasets)

Both `svg`s have a height of 42px. The upper one’s line is 32px high, the lower one’s line is 14px high. Why? How are the min and max values of the y axis calculated?

### Motivation

I want my sparklines to fill the entire area made available to the `svg` element, i.e., the min and max values of the dataset should match the min and max values of the y-axis. A property for configuring those axis values would allow such customization.

**Search keywords**: sparkline

**Comment by alexfauquette** [comment]
> Both svgs have a height of 42px. The upper one’s line is 32px high, the lower one’s line is 14px high. Why? How are the min and max values of the y axis calculated?

Surprising that you don't have access to the y-axis config. That's definitely something we could fix.

The reason why the chart does not fill the entire space is the use of `.nice()` from D3js to define ranges. We use it it to ensure ticks will have nice values, but in your use case, the value varies between 189 and 267, I assume it extends the range to 100, 300 which leaves a lot of white space.

We coudl propagate the `yAxis` in sparkline, and add a parameter `skipNice` that would skip this step

**Comment by jisotalo** [comment]
+1 The min and max values for y-axis would definetely be an important feature! 

For example, if plotting percentage data (0...100%) now with dataset containing only small values (say between 0...20%), the plot scales between that range and user could get an idea of high values.

By setting y-axis to always be 0...100%, it would make more sense.

**Comment by alexfauquette** [comment]
The next release will allow you to specify the min/max of y-axis.

We are still thinking about what could be a good DX to take control of this `nice()` step

**Comment by alexfauquette** [comment]
@JCQuintas what do you think about this property?

```jsx
/**
 * Defines the axis scale domain based on the min/max values of series linked to it.
 * - 'nice': Uses the `.nice()` method from d3-scale to round the domain at human friendly values.
 * - 'strict': Set the domain to the min/max value displayed. No extras space is added.
 * - function: takes as an argument an array with the min/max displayed values, and return the domain.
domainDefinition?: 'nice' | 'strict' | ([Value, Value]) => [Value, Value]
```

**Comment by JCQuintas** [comment]
Seems promising. Not sure about the naming, maybe `domainRange`? `domainLimit`?

**Comment by alexfauquette** [comment]
Will go with `domainLimit` since `domainRange` mixes two notions of D3: domain (the values) and range (the px)

**Comment by alexfauquette** [comment]
If someone wants to pick this issue, here are the file of interest 

https://github.com/mui/mui-x/blob/master/packages/x-charts/src/context/CartesianProvider/computeValue.ts/#L169-L181
