### ISSUE TITLE
[pickers] Toolbar components are not using the set `timezone`

### ISSUE THREAD

**Issue by ghaerdi** [mui/mui-x#13319]
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-date-pickers/timezone/

Steps:
1. Go to https://mui.com/x/react-date-pickers/timezone/
2. Inspect page and Toggle device toolbar to simulate a mobile device
3. Scroll the overview sections where are the following two inputs
![image](https://github.com/mui/mui-x/assets/47613233/09cda80c-b76a-401c-8df0-fc295a85b9ec)
4. Select one of these inputs to open the time picker.
5. Select a time

### Current behavior

The displayed time in the time picker it's not the same as selected
In the next screenshot I selected 10 but it's showing 2.
![image](https://github.com/mui/mui-x/assets/47613233/40f738ff-7113-4e8b-9a10-8f7d4cf3c87f)

### Expected behavior

The displayed time in the time picker should be exactly the same as selected.

### Context

The current behavior it's confusing for the end user. I thought the issue was in my project only but I found the same issue in the documentation.

**Search keywords**: TimePicker timezone responsive mobile pad ipad

**Comment by michelengelen** [comment]
@ghaerdi thanks for opening this issue here.
I can confirm this. It does not happen when using the `renderTimeViewClock` renderer, so it likely is a bug with the `MobileTimePicker` component.

@LukasTy didn't we have an issue somewhere related to this already?

**Comment by LukasTy** [comment]
> LukasTy didn't we have an issue somewhere related to this already?

I vaguely remember seeing something similar, but I couldn't find the issue. 🙈 

On the problem itself—it's the Toolbar components that are broken.
TimeClock represents the time correctly, but `TimePickerToolbar`, `DateTimePickerToolbar`, as well as `DateTimeRangePickerToolbar` fail to use the `timezone`.

The issue is clear and needs to be addressed. Thank you for reporting @ghaerdi 🙏

**Comment by ghaerdi** [comment]
Didn't expect a quick response, thank you all. Looking forward when this is resolved

**Comment by Hawkhub** [comment]
Any temporary workaround coming to your mind? I couldn't figure a way to pass timezone prop to MobileTimepicker exclusively. But that seems to be interfering in the components logic anyways, and a bad solution

**Comment by LukasTy** [comment]
@Hawkhub I'm not sure if there is any quick workaround here.
The only thing would be to rebuild the Toolbar component with timezone support and pass it to the `toolbar` slot.

I'll spend some time exploring solutions to see how difficult the fix is. 😉

**Comment by flaviendelangle** [comment]
@LukasTy I just saw your message, I'm testing a solution :laughing:
