### ISSUE TITLE
[question] How does pagination work when the row elements are not static?

### ISSUE THREAD

**Issue by vivekrao1985** [mui/mui-x#13329]
### The problem in depth

I have a backend API that handles paging and returns rows based on input page size and page number. Right now I'm returning the total number of rows as part of the response. From the examples for data-grid, I only see a static array of rows being used that are created in memory. Basically setting the rows prop to an array of elements. I want to make this more dynamic. So if the backend responds with elements, page size, page number and total elements, I need to let data-grid know there are more elements to show and subsequently query the backend endpoint for the next page. What's the best way I can accomplish this?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Browser - Brave
  Need to install the following packages:
@mui/envinfo@2.0.19
Ok to proceed? (y) y


  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.10.8 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.16 
    @mui/icons-material: ^5.14.16 => 5.14.16 
    @mui/material: ^5.15.16 => 5.15.16 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system: ^5.14.18 => 5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^6.0.3 => 6.0.3 
    @mui/x-date-pickers: ^7.3.2 => 7.3.2 
    @types/react: 18.2.0 => 18.2.0 
    react: ^18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.4 => 5.0.4 
```
</details>

**Search keywords**: pagination
**Order ID**: 11111

**Comment by michelengelen** [comment]
We have a comprehensive guide on server-side pagination in our docs: [Server-side pagination](https://mui.com/x/react-data-grid/pagination/#server-side-pagination)

Specifically, you'll find what you need in the section about:

- `rowCount`: This tells the data grid the total number of rows available on the server.
- `estimatedRowCount`: This provides an estimate of the total rows (optional).
- `paginationMeta.hasNextPage`: This indicates whether there are more pages to load.
If you run into any problems with these features, please open a new issue.

For questions about specific implementations, consider joining our [community Discord server](https://discord.com/invite/tewQuNeUyS). The friendly community is always happy to help!
