### ISSUE TITLE
[charts] bar chart gradient color

### ISSUE THREAD

**Issue by theol93** [mui/mui-x#13324]
### Summary

Can we make bar chart color is gradient?

### Examples

<img width="184" alt="Screenshot 2024-05-31 at 16 05 49" src="https://github.com/mui/mui-x/assets/19249266/000ff5d0-d4a0-4e12-ba9f-e7c92764a4ad">

**Search keywords**: gradient bar chart

**Comment by michelengelen** [comment]
Hey @theol93 
This is currently not possible afaik, but will add this to the board.
Maybe the team can come up with something to allow for that!
Thanks for opening an issue! 🙇🏼

**Comment by alexfauquette** [comment]
Hi @theol93, could you explain your use-case for the color gradient?

Technically you can apply gradients with CSS but from your screenshot it seemed related to some data, so having the use-case could help to say if it's feasible or if we need to add a feature

**Comment by theol93** [comment]
Hello @michelengelen, @alexfauquette yes im trying to manage background colors passing my color to BarChart series color field, but when i trying to pass something like - color: `linear-gradient(#e66465, #9198e5)` i unfortunately got only black color.
<img width="121" alt="Screenshot 2024-06-03 at 18 19 47" src="https://github.com/mui/mui-x/assets/19249266/3399797f-48fe-44c7-8c58-39f5c644deee">

**Comment by alexfauquette** [comment]
Because SVG does not support this way of providing a gradient. Here are multiple solutions.

https://codesandbox.io/p/sandbox/silly-sanderson-9wywvm?file=%2Fsrc%2FDemo.tsx%3A11%2C42

Notice that color is use in SVG for the ploting and the legend (here gradients are ok) but for the tooltip which is in HTML, the gradient definition does not exist.

**Comment by theol93** [comment]
@alexfauquette thank you, it looks good!
