### ISSUE TITLE
Adding properties to CustomTreeItem for RichTreeView

### ISSUE THREAD

**Issue by jonslo** [mui/mui-x#13351]
### The problem in depth

Hi, I am building off the the File Explorer / TreeItem2 example from https://mui.com/x/react-tree-view/rich-tree-view/customization/#file-explorer.

Instead of extending the interface without additional props values, as in the example:
```
interface CustomTreeItemProps
  extends Omit<UseTreeItem2Parameters, 'rootRef'>,
    Omit<React.HTMLAttributes<HTMLLIElement>, 'onFocus'> {}
```

I would like to pass additional properties, as follows:
```
interface CustomTreeItemProps
  extends Omit<UseTreeItem2Parameters, 'rootRef'>,
    Omit<React.HTMLAttributes<HTMLLIElement>, 'onFocus'> {
  schemaTree: ExtendedTreeItemProps[];
  setSchemaTree: React.Dispatch<React.SetStateAction<ExtendedTreeItemProps[]>>;
}
```

However, I do not know how to properly pass my custom **schemaTree** and **setSchemaTree** properties when using the RichTreeView component:
```
<RichTreeView
    apiRef={apiRef}
    items={schemaTree}
    selectedItems={selectedItems}
    onSelectedItemsChange={handleSelectedItemsChange}
    slots={{ item: CustomTreeItem }}
    getItemId={(item) => item.path}
    getItemLabel={(item) => item.fieldName}
    defaultExpandedItems={['']}
/>
```

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.4.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.19 
    @mui/icons-material: ^5.15.10 => 5.15.19 
    @mui/lab: ^5.0.0-alpha.155 => 5.0.0-alpha.170 
    @mui/material: ^5.14.20 => 5.15.19 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^6.19.4 => 6.20.0 
    @mui/x-data-grid-generator: ^6.19.6 => 6.20.0 
    @mui/x-data-grid-premium: ^6.19.6 => 6.20.0 
    @mui/x-data-grid-pro: ^6.19.4 => 6.20.0 
    @mui/x-date-pickers: ^7.1.1 => 7.6.1 
    @mui/x-date-pickers-pro: ^7.1.1 => 7.6.1 
    @mui/x-license: ^7.6.1 => 7.6.1 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view: ^7.5.0 => 7.6.1 
    @types/react: ^18.2.43 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: ^5.3.3 => 5.4.5 
```
</details>

**Search keywords**: treeview custom customtreeitem richtreeview
**Order ID**: 91615

**Comment by flaviendelangle** [comment]
Hi,

You can use the `slotProps` prop which allow you to pass custom props to any slot.
It is documented for the [Date and Time Pickers](https://mui.com/x/react-date-pickers/custom-components/#overriding-slot-components) and we plan to prepare a better documentation in the coming weeks / months because we clearly lack it for the Tree View :+1:

**Comment by flaviendelangle** [comment]
You need to pass the name of the slot:

```diff
 <RichTreeView
     apiRef={apiRef}
     items={schemaTree}
     selectedItems={selectedItems}
     onSelectedItemsChange={handleSelectedItemsChange}
     slots={{ item: CustomTreeItem }}
-    slotProps={{ schemaTree, setSchemaTree }}
+   slotProps={{ item: { schemaTree, setSchemaTree }}
     getItemId={(item) => item.path}
     getItemLabel={(item) => item.fieldName}
     defaultExpandedItems={['']}
 />
```

You will probably still end up with a TS error because we don't support well un-expected props when you provide both a custom component and pass some custom props to it.
You can add an `as any` to fix that, but we know that it's not a good solution and we are looking for a better alternative for all the products that uses slots.

**Comment by flaviendelangle** [comment]
Awesome!

I'm closing the issue then
You can track the improvement of the doc regarding those topiccs in #13161

**Comment by DerInfloenzer** [comment]
Hi everyone
We've currently implemented a RichTreeView with the workaround provided in this post. Is there anything planned for the foreseeable future which mitigates the issue or influences the behaviour of the workaround?

**Comment by fabienbranchel** [comment]
> Excellent, thanks again [@flaviendelangle](https://github.com/flaviendelangle). The following worked!
> 
> ```
>  <RichTreeView
>      apiRef={apiRef}
>      items={schemaTree}
>      selectedItems={selectedItems}
>      onSelectedItemsChange={handleSelectedItemsChange}
>      slots={{ item: CustomTreeItem as any }}
>      slotProps={{ item: { schemaTree, setSchemaTree } as any }}
>      getItemId={(item) => item.path}
>      getItemLabel={(item) => item.fieldName}
>      defaultExpandedItems={['']}
>  />
> ```

I'm trying to implement a `RichTreeView` and I need to add custom function properties to my `CustomTreeItem`.

Trying as what you suggest like this : 

```
<RichTreeView
      items={items}
      apiRef={apiRef}
      slots={{ item: CustomTreeItem as any }}
      slotProps={{ item: { myfunc: () => console.log('myfunc') } as any }}
      isItemEditable
      expansionTrigger="iconContainer"
    />
```

`myfunc` is available through `CustomTreeItem`'s props but I have this ugly error in console : 

`hook.js:608 Warning: Invalid value for prop `myfunc` on <li> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.` 

How did you make it works on your side ?

**Comment by flaviendelangle** [comment]
You are forwarded your `myFunc` prop to the DOM and it complains because it doesn't know about this prop.
You should remove it from the props in your `CustomTreeItem`.
Something like:


```tsx
function CustomTreeItem() {
  const { myFunc, ...other } = props;

  // Render the Tree Item Root with "other" instead of "props"    
}
```

If this doesn't fix your problem, please open a new issue with a reproduction case 👍
