### ISSUE TITLE
[data grid] Filter layout issue in datagrid

### ISSUE THREAD

**Issue by kishanp1412** [mui/mui-x#13352]
### The problem in depth

I have issue with mui filter layout in datagrid , i checked the documentation but i am not able to get the filter layout same as docs so need help to get the filter layout same as docs in data grid , you can see the attachments i am not getting the layout perfectly 
![2024-06-03_10-49](https://github.com/mui/mui-x/assets/171536761/8095de05-1c0d-41a1-a79e-8c57f23303bb)
so please provide the solution to get the filter layout same as docs asap it's blocking our live website

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```Chrome</details>


**Search keywords**: Datagrid filter layout
**Order ID**: 88101

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by kishanp1412** [comment]
okay will check and get back to you

**Comment by kishanp1412** [comment]
still not able to get the filter layout const columns: GridColDef[] = useMemo(
    () => [
      {
        headerName: "ID",
        field: "id",
        flex: 0.5,
      
      },
      {
        headerName: "Quote To",
        field: "supplier_name",
        flex: 1,
        editable: true,
      }],[])    <DataGridPro
    columns={columns}
    rows={rows}
    rowHeight={38}
    checkboxSelection
    disableRowSelectionOnClick
    /> created again with simplest listing  but still i am getting this filter layout 
![image](https://github.com/mui/mui-x/assets/171536761/ab5bea01-cd23-4e4a-a4d7-2287b86c7a04)

**Comment by michelengelen** [comment]
Please try to replicate this in a codesandbox or stackblitz.
Without this we will not be able to help you.

**Comment by kishanp1412** [comment]
okay will do it

**Comment by michelengelen** [comment]
Thats relatively unlikely. It works with the same versions installed in a codesandbox:

<img width="2287" alt="Screenshot 2024-06-04 at 11 38 13" src="https://github.com/mui/mui-x/assets/32863416/ec0338cf-0e10-4772-a7cc-5c9291776925">

From the screenshot you provided my guess would be that there are some style overrides present in your project that affect the filter panel.

The best option here is to track down where the CSS changes come from.

**Comment by kishanp1412** [comment]
got it will check
