### ISSUE TITLE
Time Picker Placeholder Issue in @mui/x-date-pickers

### ISSUE THREAD

**Issue by sonu-mamsys** [mui/mui-x#13357]
### Steps to reproduce

1. Set up a TimePicker component with the placeholder using slotProps.
2. Open the time picker and close it without selecting any time.
3. Change the window size by dragging or by opening the browser console.
4. Observe that the placeholder changes to "hh:mm aa".
5. Notice that the placeholder issue persists.

### Current behavior

The placeholder changes to "hh:mm aa" under the specified conditions.
![image](https://github.com/mui/mui-x/assets/95623658/1af155e0-99c8-4717-b586-32849489b5bd)
![image](https://github.com/mui/mui-x/assets/95623658/33e52396-364e-4b40-99cb-53e823be3e77)

### Expected behavior

The placeholder should consistently remain as "Start Time" regardless of opening and closing the time picker without selection or changing the window size.

### Your environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
  Binaries:
    Node: 14.21.3 - /usr/bin/node
    npm: 6.14.18 - /usr/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.18 
    @mui/material: ^5.14.5 => 5.15.18 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-date-pickers: ^6.11.1 => 6.11.1 
    @types/react:  17.0.41 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 

**Search keywords**: bug

**Comment by LukasTy** [comment]
@sonu-mamsys Could you provide a reproduction example or at least a video of the problem happening? 🤔 
I've failed to reproduce it. 🙈 
[Here is](https://codesandbox.io/p/sandbox/frosty-tdd-ndndgp?file=%2Fsrc%2FDemo.tsx) a sandbox with my experiment.
