### ISSUE TITLE
[data grid] How to disable hover effect for datagrid column header?

### ISSUE THREAD

**Issue by sanlee13** [mui/mui-x#13364]
### The problem in depth

Hello,
I have a data gird where I am rendering a checkbox with the headerName. When I hover over the checkbox in the column header of that data gird I get a hover effect as show in the image below. I would like to disable this hover.

I have tried this in the checkbox:
```
headerName:  <Checkbox sx={{'&.MuiChekbox-root .MuiCheckbox:hover': {
                            backgroundColor:'inherit',
                          }}}
                      onChange={(event, checked) => myFunction(checked)}/>
```
I have also tried to add the css effect in the data grid column class:
```
sx={{ 
              '&.MuiDataGrid-columnHeaders .Mui-hovered': {
                backgroundColor: 'inherit',
              },
              '&.MuiDataGrid-columnHeaders:hover': {
                backgroundColor: 'inherit',
              }  
            }}
```
I have tried to apply it to the MuiDataGrid-columnHeaderTitleContainer and MuiDataGrid-columnHeaderTitle classes as well. 

![image](https://github.com/mui/mui-x/assets/114650117/2ee647da-cfc5-457f-9bfe-88fbc61c899b)

EDIT: Fixed typos

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: disable hover effect for datagrid column header
**Order ID**: 82571

**Comment by michelengelen** [comment]
Hey @sanlee13 ... thanks for opening an issue here.
Did you try using `renderHeader` instead of `headerName` (which is meant to be used to return a `string` which will then be rendered)

Here is some documentation for it: [Customize header renderer](https://mui.com/x/react-data-grid/column-header/#custom-header-renderer)

**Comment by sanlee13** [comment]
Hey @michelengelen,
Thanks so much for your help! This fix totally saved the day.  I learned something new today – `headerName` returns a string.  Definitely a rookie mistake on my part.  Really appreciate you taking the time to explain it!

**Comment by michelengelen** [comment]
No problem @sanlee13 ... always happy to help!
If you encounter any other issue please don't hesitate to open another issue. 👍🏼
