### ISSUE TITLE
[data grid] Cannot use data grid with react testing library

### ISSUE THREAD

**Issue by benparks1976** [mui/mui-x#13369]
### Steps to reproduce

As this problem occurs in the react test I'm not able to provide a live link. Instead I have attached react project including a test reproduces the issue. I hope this sufficient. 
[mui-repro.zip](https://github.com/user-attachments/files/15551838/mui-repro.zip)

Steps.
1. Create a component that uses the MUI data grid 7.6.1
2. Create a react test using the react testing framework
3. Run the test

### Current behavior

When the component is rendered by the react testing framework the following error is shown:

Error: Uncaught [TypeError: apiRef.current.state.rows.dataRowIds.at is not a function]

### Expected behavior

The error should not occur when rendering the MUI data grid component. 

When the same test is run with Mui data grid version 6.9.2 the problem does not occur.

### Context

Write unit tests for our components that use Mui data grid 7.6.1.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 14.20.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (125.0.2535.79)
</details>

**Search keywords**: react testing library with mui data grid

**Comment by michelengelen** [comment]
Hey @benparks1976 ... my colleague @JCQuintas noticed that you were using the old syntax.
If you change the code in your example to this it should work:

```tsx
import React from "react";
import Demo from "../demo";
import { render } from "@testing-library/react";

describe("when rendering the data grid", () => {
    it("should render the table columns", async () => {
        const {findAllByRole} = render(<Demo/>)

        const headers = await findAllByRole("columnheader")!;

        expect(headers[1].textContent).toBe("Serial number");
        expect(headers[2].textContent).toBe("Model name");
    });
})
```

Could you try that please?

**Comment by benparks1976** [comment]
Hi, thanks for the follow up. I tried your suggestion and I still got the same issue:

![image](https://github.com/mui/mui-x/assets/22930909/8bdedceb-a2a6-4d9c-8e41-737633afed1a)

**Comment by michelengelen** [comment]
It does work on my machine:
<img width="507" alt="Screenshot 2024-06-05 at 11 33 09" src="https://github.com/mui/mui-x/assets/32863416/7046e63c-7d84-48b0-beeb-282ded47a28c">

Did you try a fresh install?

**Comment by JCQuintas** [comment]
Hi @benparks1976, the tests are green on my side with the example code you provided. I've noticed you are using `node 14`, which doesn't support the `array.at()` function. I would suggest upgrading your node to a more recent version, `at` is available from `16.6`.

Otherwise you could also add a polyfill. eg: https://www.npmjs.com/package/array.prototype.at

**Comment by benparks1976** [comment]
Thanks @JCQuintas, this is the problem. Thanks all for your help.

**Comment by benparks1976** [comment]
Closing...

**Comment by TrinhNoBamBum** [comment]
I am using node 18 and still having the above problem, please help me
