### ISSUE TITLE
[datagrid] filter layout position 

### ISSUE THREAD

**Issue by kishanp1412** [mui/mui-x#13379]
### The problem in depth

need to change the filter panel postion at specific place 
![image](https://github.com/mui/mui-x/assets/171536761/33984ddf-da97-4e3e-9dad-217db0a86afe)
need to place at the position highlighted with red box , how to change the position i have tried but it's not placed out of the datagrid

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Datagrid filter pannel position
**Order ID**: 88101

**Comment by michelengelen** [comment]
Hey @kishanp1412 
We do have an example [here](https://mui.com/x/react-data-grid/filtering/customization/#customize-the-filter-panel-position) showing how you can customize the filter panel position.

It basically uses `slotProps.panel.anchorEl` to position it.
Could you try that?

**Comment by kishanp1412** [comment]
Thanks
