### ISSUE TITLE
Add a prop for setting a default staring value for Time Picker

### ISSUE THREAD

**Issue by Kii-Su** [mui/mui-x#13376]
### Summary

It would be very useful in some use cases to specify a default staring value for time picker.  Currently, when the time picker is opened, the default scroll point is always at midnight if value is empty. I would like to set the default value to a specific time, without affecting the actual value.

### Examples

**Current behaviour:**
When picker is opened, scroll point is at midnight.
<img width="495" alt="Screenshot 2024-06-05 at 10 40 17" src="https://github.com/mui/mui-x/assets/171771892/046050f6-04f0-49a3-b2a0-a985982caf09">

**Wanted behaviour**
When I open the picker, specific time would be offered by default instead of midnight, if no value is given. 
<img width="564" alt="Screenshot 2024-06-05 at 10 32 23" src="https://github.com/mui/mui-x/assets/171771892/2182673e-1e86-4956-b611-d51cf91c7901">

### Motivation

In many use cases, the user wants to select a time close to current time. 

**Search keywords**: default scroll point, time picker default scroll value, time picker default start value

**Comment by LukasTy** [comment]
Feel free to use the [referenceDate prop](https://mui.com/x/react-date-pickers/base-concepts/#reference-date-when-no-value-is-defined) to do that. 😉 
Closing the issue as the feature is already implemented.
