### ISSUE TITLE
[data grid] How to Use Render Cell for Default Group Column Without Affecting Its Functionality?

### ISSUE THREAD

**Issue by JahanzaibAbdullah** [mui/mui-x#13400]
### The problem in depth

Hi MUI X Support Team,

I am encountering several issues with the Data Grid Tree Data default column and need your assistance to resolve them:

1. **Header Name Customization:** I need to change the header name of the default column used for tree data. Despite my attempts, I am unable to find a way to achieve this.

2. **Styling and Customization with Render Cell:** I need to modify the styling and uplift the default view of the tree data to match my required design. To do this, I attempted to use the renderCell property. However, whenever I make any changes using renderCell, the tree data functionality ceases to work properly. Specifically, the data becomes static in the rows of the modified column and does not expand as expected however the default indentation of current tree is perfect that is provided by MUI X Component.

3. **Checkbox Selection Use Case:** I need to alter the functionality of the checkboxes. Specifically, when I select a parent node, it should automatically select all its child elements. Currently, this behavior is not implemented, and I need guidance on how to achieve this.

These issues are blocking my development process, and I would greatly appreciate your assistance in resolving them.

This image is from the developed code that I need to modify: 
![1](https://github.com/mui/mui-x/assets/153061039/35735f82-e2e9-4b86-aacd-1e2d433976b7)

This is the reference image of the required design I am trying to create. However, due to the issues mentioned above, I am unable to develop it:
![2](https://github.com/mui/mui-x/assets/153061039/a4b891d1-5f0e-42be-a68c-5396cee35840)

Thank you for your support. I look forward to your prompt response.

Best regards,
Jahanzaib Malik
 
```tsx
 type RowType = {
  hierarchy: string[];
  id: number;
};

const rowsTree: RowType[] = [
  {
    hierarchy: ['Site & Structural', 'RAD Center Information'],
    id: 0,
  },
  {
    hierarchy: ['Site & Structural', 'RAD Center Information', 'Verified RAD Center'],
    id: 1,
  },
  {
    hierarchy: ['Site & Structural', 'Structural Analysis'],
    id: 2,
  },
  {
    hierarchy: ['Site & Structural', 'Structural Analysis', 'Structural Analysis Received'],
    id: 3,
  },
  {
    hierarchy: ['Power', 'Power Design'],
    id: 4,
  },
  {
    hierarchy: ['Power', 'Power Design', 'Utility App Submitted'],
    id: 5,
  },
  {
    hierarchy: ['Power', 'Power Walk'],
    id: 6,
  },
  {
    hierarchy: ['Power', 'Power Walk', 'Power Walk Required'],
    id: 7,
  },
  {
    hierarchy: ['Lease', 'Legal Review'],
    id: 9,
  },
  {
    hierarchy: ['Lease', 'Legal Review', 'Lease Reviewed'],
    id: 10,
  },
  {
    hierarchy: ['Lease', 'Lease Execution'],
    id: 11,
  },
  {
    hierarchy: ['Lease', 'Lease Execution', 'Routed for Execution'],
    id: 13,
  },
  {
    hierarchy: ['Zoning & Permits', 'Zoning Jurisdiction Requirements', 'Type of Zoning'],
    id: 14,
  },
  {
    hierarchy: ['Zoning & Permits', 'Zoning Jurisdiction Requirements', 'Zoning Duration'],
    id: 15,
  },
  {
    hierarchy: ['Construction', 'Pre-Construction', 'GC Bid Date'],
    id: 16,
  },
  {
    hierarchy: ['Construction', 'Pre-Construction', 'GC WO Issued'],
    id: 17,
  },
  {
    hierarchy: ['Cost Tracking', 'Cost Tracking', 'Labour Cost ($)'],
    id: 18,
  },
];

const treeColumns: GridColDef[] = [];

const groupingColDef: DataGridPremiumProps['groupingColDef'] = {
  headerName: 'Hierarchy',
  minWidth: 400,
};

const getTreeDataPath: DataGridPremiumProps['getTreeDataPath'] = (row) => row.hierarchy;

return(
  <Box
    sx={{
      width: '100%',
      height: 'calc(100vh - 230px)',
      marginBottom: '8px !important',
    }}
  >
    <Card>
      <CardContent
        sx={{
          height: '100%',
          width: '100%',
          padding: 0,
          paddingBottom: '0px !important',
        }}
      >
        <div
          style={{
            height: 'calc(100vh - 232px)',
          }}
        >
          <StyledDataGrid
            treeData
            getTreeDataPath={getTreeDataPath}
            rows={rowsTree}
            columns={treeColumns}
            groupingColDef={groupingColDef}
            density={density}
            onDensityChange={(newDensity) => setDensity(newDensity)}
            sx={dataGridStylesListView}
            pagination={rowsTree.length > 20}
            initialState={{
              pagination: {
                paginationModel: {
                  pageSize: 100,
                },
              },
            }}
            disableVirtualization
            getRowClassName={(params) => `super-app-theme--${params.row.status}`}
            pageSizeOptions={[25, 50, 100]}
            checkboxSelection
            disableRowSelectionOnClick
            slots={{
              toolbar: () => (
                <CustomToolbar
                  loadingState={loading}
                  RowSelectionModel={false}
                />
              ),
              noRowsOverlay: CustomNoRowsOverlay,
              noResultsOverlay: CustomNoResultOverlay,
            }}
          />
        </div>
      </CardContent>
    </Card>
  </Box>
);
```

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data Grid Premium, Tree data, Render cell for default group column
**Order ID**: 91010

**Comment by michelengelen** [comment]
Hey @JahanzaibAbdullah 

Thanks for raising an issue here.
First of all: We do use github issues to track bugs/regressions and feature requests. If you need assistance building a custom implementation I would advice you to either aska question on StackOverflow or join the community on our official discord server. They are happy to help you with such requests.

Now to go over your problems:
1. Simply use the `gridColDef` property of the datagrid: `gridColDef={{ headerName: 'Select All' }}`
2. This one is a bit more tricky. We do have an example on how to accomplish something similar on the docs: [Custom grouping column](https://mui.com/x/react-data-grid/tree-data/#custom-grouping-column). I have adjusted the example to give you a head start in your implementation: [DEMO](https://codesandbox.io/p/sandbox/laughing-currying-3x7fgy)
3. This is pretty common request. There is a recent workaround you can use until we implement that feature OOTB: https://github.com/mui/mui-x/issues/13277#issuecomment-2142244288

This should resolve all of your issues. 👍🏼

**Comment by woodreamz** [comment]
We are facing the same issue, do you plan to fix this issue (point 2)? Customizing the grouping cell with `GridTreeDataGroupingCell` is working fine with the grouping mode but not with three data.
