### ISSUE TITLE
[data grid] Unable to use Multiple Filter option

### ISSUE THREAD

**Issue by saisannem97** [mui/mui-x#13408]
### The problem in depth

I am using DataGridPremium Version , but I am unable to see multiple filters option.i.e the ADD FILTER button  . Please check the screenshot below.

![ss](https://github.com/mui/mui-x/assets/147080551/4c55a177-84e4-4432-848d-dcb7d779c360)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: multiple filter not working for premium
**Order ID**: 87310

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by michelengelen** [comment]
@saisannem97 Could you please check if you have passed `disableAddFilterButton` and/or `disableRemoveAllButton` to the panel slotProps?

**Comment by saisannem97** [comment]
HI @michelengelen  , No I havent used those slotprops . Please check my code below
   <DataGridPremium
            checkboxSelection
            pagination
            paginationModel={paginationModel}
            onPaginationModelChange={handlePaginationModelChange}
            pageSizeOptions={[PAGE_SIZE]}
            onRowSelectionModelChange={handleSelectionModelChange}
            processRowUpdate={handleProcessRowUpdate}
            disableRowSelectionOnClick
            editMode="row"
            sx={{
              '& .MuiDataGrid-columnHeaderCheckbox .MuiDataGrid-columnHeaderTitleContainer': {
                display: 'none',
              },

              // '& .MuiDataGrid-columnsContainer': {
              //   backgroundColor:  '#fafafa'
              // },
              // '& .MuiDataGrid-iconSeparator': {
              // display: 'none',
              // },
              '& .MuiDataGrid-columnHeader, .MuiDataGrid-cell': {
                borderRight: `1px solid ${'#f0f0f0'}`,
              },
              '& .MuiDataGrid-columnsContainer, .MuiDataGrid-cell': {
                borderBottom: `1px solid ${'#f0f0f0'}`,
              },
              '& .MuiDataGrid-cell': {
                // color: colors.primary[100],
              },
              '& .MuiPaginationItem-root': {
                borderRadius: 0,
                color: colors.grey[200],
              },
              '& .MuiDataGrid-root': {
                border: 'none',
              },
              border: 0,
              '& .css-112ysrj-MuiButtonBase-root-MuiCheckbox-root.Mui-checked': {
                color: 'white',
              },
              overflow: 'hidden',
            }}
            slots={{
              pagination: CustomPagination,
              toolbar: CustomToolbar,
            }}
            loading={loading}
            rows={intialRows}
            localeText={{
              toolbarColumns: '',
              toolbarDensity: '',
              toolbarExport: '',
              toolbarFilters: '',
            }}
            columns={newColumns}
            getRowId={(row) => {
              return row.vendorName;
            }}
            density="compact"
            rowCount={rowCountState}
            paginationMode="server"
          />

**Comment by michelengelen** [comment]
Please try to recreate the problem you are facing with a live code example.
If I use the code you provided I can still use multiple filters.

Please also check if the buttons get rendered at all by viewing the elements in the developer console. Maybe they just get hidden there.
