### ISSUE TITLE
[data grid] Multi Column Sort Indicator Cut off when Column is narrow

### ISSUE THREAD

**Issue by httpete** [mui/mui-x#13406]
### Steps to reproduce

![image](https://github.com/mui/mui-x/assets/1200635/6f795e38-3c49-4286-82fc-722fbb8ada5c)

### Current behavior

This is easily reproducible on the demo page from MUI/DataGrid. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: column sort indicator
**Order ID**: 79357

**Comment by michelengelen** [comment]
@httpete thanks for raising this issue.
I am actually not too sure if we can do something about that.
Ideas @cherniavskii (and maybe @danilo-leal)?

**Comment by michelengelen** [comment]
@mui/xgrid thoughts?

**Comment by romgrk** [comment]
The width of the badge container would need to include the floating text. I think this is something that can only be fixed in the core, maybe there's already a bug report for this. Alternatively we could align the badge on the starting position of the text direction (left in LTR, right in RTL): https://mui.com/material-ui/react-badge/#badge-alignment

Not sure what's the best option.

**Comment by michelengelen** [comment]
@noraleonte would love to have your input on this design question. ^^

**Comment by noraleonte** [comment]
I wouldn't necessarily change the alignment of the badge 🤔 Feels a bit counter intuitive...
From what I see, adding a `marginRight` to the `iconButtonContainer` when the badge is visible could fix this, but I don't know the codebase well enough to anticipate any side effects of that 🙈 

> I think this is something that can only be fixed in the core, maybe there's already a bug report for this.
I think we could open one if there isn't... seems to me like a pretty common issue

**Comment by michelengelen** [comment]
I did add this to the board. 
Maybe we can come up with something collaboratively in the grooming session. 👍🏼
