### ISSUE TITLE
[data grid] Columns selection component losing anchorElement/scroll state

### ISSUE THREAD

**Issue by russ0133** [mui/mui-x#13436]
### The problem in depth

We are running everything on server side (filtering, hiding etc) and we have a custom toolbar component and a custom columnsPanel component. We have been going through an issue for quite some time where (I assume) when the data (rows, columns) state is re-rendered (for example, when hiding a column or reordering columns) the columnsPanel component is completely unmounted and mounted and thus leading us to lose the scroll state. (that on x-data-grid v5.17.26)

This was an issue which we largely ignored until we upgraded x-data-grid to v7.5.0 and now we not only lose the scroll state, but also the anchorEl state... I have a gut feeling that those bugs are related (or the same) and made worse in recent versions of datagrid.

https://github.com/mui/mui-x/assets/26175960/6cdbb010-52b5-4b79-aa88-26bd97820516

[Screencast_from_2024-06-07_19-00-00.webm](https://github.com/mui/mui-x/assets/26175960/c0ad188d-5a8c-4ab9-9f72-52e855e20f9c)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 9.4.0 - ~/.nvm/versions/node/v18.13.0/bin/npm
    pnpm: 9.2.0 - ~/.nvm/versions/node/v18.13.0/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.141
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/icons-material: ^5.15.16 => 5.15.18 
    @mui/lab: 5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: ^5.15.16 => 5.15.18 
    @mui/styles: ^5.15.18 => 5.15.18 
    @mui/x-data-grid: ^7.5.0 => 7.5.0 
    @mui/x-data-grid-pro: ^7.5.0 => 7.5.0 
    @mui/x-date-pickers-pro: ^6.20.0 => 6.20.0 
    @mui/x-license: ^7.0.0 => 7.2.0 
    @mui/x-tree-view: ^7.6.1 => 7.6.1 
    @types/react: ^18.2.79 => 18.3.2 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: ^5.4.5 => 5.4.5 

</details>

**Search keywords**: column selection, re-render
**Order ID**: 91870

**Comment by michelengelen** [comment]
Hey @russ0133 and thanks for opening an issue here.
I suspect this is due to the improvement we made on the header rendering.
Let me look into this.

@romgrk if you have any hint please feel free to comment as well! 👍🏼

**Comment by michelengelen** [comment]
@russ0133 in the meantime could you try to replicate this in a minimal live code example?
It looks like you have some customization regarding the placement and content of the columns panel in place, right?

Especially helpful would be to know if you memoize the panel in some way or not!

**Comment by russ0133** [comment]
> @russ0133 in the meantime could you try to replicate this in a minimal live code example? It looks like you have some customization regarding the placement and content of the columns panel in place, right?
> 
> Especially helpful would be to know if you memoize the panel in some way or not!

There's no memoization. And yeah, the component itself is inside a MUI Popper and we pass the ref to the button to the columns panel component, the anchorEl being the "Columns" button in the toolbar.

<Popper open={columnPanelVisible} anchorEl={popperAnchor}>

I've tried setting the anchorEl without the ref and instead through slotProps in <DataGrid> but with no success. Will try to get a minimal live code going and debug further. This seems to only happen when the server updates - if it's only on the frontend side, then it doesn't "remount" the component.

**Comment by russ0133** [comment]
Resolved the issue by not passing props directly to the toolbar function:

`toolbar: (props) => TableToolbar({ ...props, tableId, filterButtonRef, columnPanelRef })`

Instead passing the props on the slotProps in the DataGrid:

```
        slotProps={{
          toolbar: {
            setFilterButtonEl,
            tableId,
            filterButtonRef,.
            columnPanelRef,
          },
        }} 
```
        
 Also followed this codesandbox and instead of useRef, I'm using useState
 
 https://codesandbox.io/p/sandbox/old-forest-9dlvdd?file=%2Fsrc%2FDemo.tsx%3A12%2C31-16%2C2
