### ISSUE TITLE
[data grid] Bottom border doesn't reflect on pinned columns 

### ISSUE THREAD

**Issue by bojanmitic** [mui/mui-x#13443]
### The problem in depth

I have set borders on row element. However, bottom border is missing on pinned columns. Please see attachments
![Screenshot 2024-06-11 at 11 16 09](https://github.com/mui/mui-x/assets/19996589/d3e05106-0a7a-4c7d-a83a-74fb4852926c)
![Screenshot 2024-06-11 at 11 16 17](https://github.com/mui/mui-x/assets/19996589/99c65131-c9a0-4627-a2af-f60b9b543d81)

As you can see green border(top border) goes all the way, even through pinned columns, but bottom(black border) goes only on unpinned columns. Why and how to fix it? 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Bottom border on pinned columns
**Order ID**: 69131

**Comment by michelengelen** [comment]
Hey @bojanmitic ... it works for me: [DEMO](https://codesandbox.io/p/sandbox/magical-germain-dth4j3)

Which version of the grid are you using?

**Comment by bojanmitic** [comment]
We are updating packages, so this happened with version 7.6.1. Earlier version was 6.18.6 and it worked as it should. Not sure why this happens. :(

**Comment by bojanmitic** [comment]
Probably it's problem somewhere in our code

**Comment by michelengelen** [comment]
It might just be some kind of global styling ... If you could provide a reproduction I would be glad to assist.

**Comment by bojanmitic** [comment]
Sure, thank you. I think we can close this issue.
