### ISSUE TITLE
[data grid] Extra space on the bottom of grid when loading new records and scrolling back up

### ISSUE THREAD

**Issue by swensel** [mui/mui-x#13441]
### Steps to reproduce

I had filed a separate issue https://github.com/mui/mui-x/issues/13301 recently.  This bug is a different case.  

The grid that's having an issue is using the [infinite loading](https://mui.com/x/react-data-grid/row-updates/#infinite-loading) feature.  My team has noticed that when upgrading from `@mui/x-data-grid-pro` v5.12.0 to v7.5.1, that there's a lot of extra white space on the bottom of the grid, after loading new records and then scrolling back up.  We only notice this on v7.5.1, not on v5.12.0.  I've attached a video of the issue we are having with v7.5.1.

https://github.com/mui/mui-x/assets/6386584/039c36b2-cd3e-4c0a-bfc9-d34b24325ee1

This looks like a bug?

### Current behavior

There's a lot of extra white space on the bottom of the grid, after loading new records and then scrolling back up.

### Expected behavior

There shouldn't be extra white space on the bottom of the grid, after loading new records and then scrolling back up.

### Context

We would like to use the infinite loading feature and have there not be extra space on the grid when scrolling back up.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 125.0.6422.61
    Edge: 121.0.2277.128
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.7.1 => 11.11.4 
    @emotion/styled: ^11.6.0 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.19 
    @mui/icons-material: ^5.15.19 => 5.15.19 
    @mui/material: ^5.15.19 => 5.15.19 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^7.5.1 => 7.5.1 
    @mui/x-data-grid-pro: ^7.5.1 => 7.5.1 
    @mui/x-date-pickers: ^7.5.1 => 7.5.1 
    @mui/x-license: ^7.2.1 => 7.2.1 
    @types/react: ^17.0.1 => 17.0.80 
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    typescript: ^4.8.4 => 4.9.5 
```
</details>

**Search keywords**: extra space infinte loading
**Order ID**: 90881

**Comment by michelengelen** [comment]
Thanks for the reproduction demo @swensel ... @romgrk could you have a look please? Thanks!

**Comment by cherniavskii** [comment]
Hi @swensel 
I just realized you're passing the `rowHeight` prop to the row slot.
You should use [the `rowHeight` prop](https://mui.com/x/react-data-grid/row-height/) instead because the `row` slot is only _one of_ the places that use this information.
Here is a working demo: https://stackblitz.com/edit/react-gothse-mu4dc9?file=Demo.tsx
