### ISSUE TITLE
[data grid] Is it possible to add reusable DataGrid GridToolbar components that make use of slots and slotProps?

### ISSUE THREAD

**Issue by toddsmith-adsk** [mui/mui-x#13451]
### The problem in depth

I'd like to create reusable GridToolbar components that make use of slots and slotProps. That would require us to use interface declaration merging to extend classes such as GridBaseSlots, GridSlotProps, GridPremiumSlotsComponent, etc. Is this approach viable? We'd also like to add custom panels as part of these toolbar components that leverage the existing preferences panels.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (125.0.2535.92)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.17
    @mui/icons-material: ^5.15.17 => 5.15.17
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.17 => 5.15.17
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid:  7.4.0
    @mui/x-data-grid-generator: ^7.4.0 => 7.4.0
    @mui/x-data-grid-premium: ^7.4.0 => 7.4.0
    @mui/x-data-grid-pro:  7.4.0
    @mui/x-date-pickers: ^7.4.0 => 7.4.0
    @mui/x-license:  7.2.0
    @mui/x-license-pro: ^6.10.2 => 6.10.2
    @types/react: ^18.0.28 => 18.3.2
    react: ^18.2.0 => 18.3.1
    react-dom: ^18.2.0 => 18.3.1
    typescript: ^5.4.5 => 5.4.5
```
</details>

**Search keywords**: datagrid toolbar
**Order ID**: 86253

**Comment by michelengelen** [comment]
If I got this correctly it is the best approach indeed.
we have a section on the docs regarding [module augmentation](https://mui.com/x/react-data-grid/components/#custom-slot-props-with-typescript) as well.

**Comment by michelengelen** [comment]
If you have any other questions regarding this please don't hesitate to ask! 👍🏼
