### ISSUE TITLE
[TreeView] Can't type a space in an input rendered in the item

### ISSUE THREAD

**Issue by mosofsky** [mui/mui-x#13458]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to https://codesandbox.io/p/sandbox/mui-x-tree-view-7-5-0-space-bug-tmvrwz
2. In the blank <input> field try typing a space character
3. You should see a space but it does not show anything (other characters such as "a1" are accepted, no problem)
4. If you roll back to @mui/x-tree-view@7.4.0, the space character is possible to type without problem

Here is the essential code:

```
  const stopPropagationToPreventTreeItemFromGettingFocused = (
    event: React.MouseEvent | MouseEvent
  ) => {
    event.stopPropagation();
  };
```

```
      <SimpleTreeView>
        <TreeItem
          itemId="1"
          label={
            <input
              type="text"
              onClick={stopPropagationToPreventTreeItemFromGettingFocused}
              size={100}
            />
          }
        ></TreeItem>
      </SimpleTreeView>
```

### Current behavior

Typing space character does not do anything

### Expected behavior

Typing a space character should show a space

### Context

TreeView is being used for a file-explorer where the user can rename the file or the folder.

### Your environment

<details>
```
{
  "name": "react-typescript",
  "version": "1.0.0",
  "description": "React and TypeScript example starter project",
  "keywords": ["typescript", "react", "starter"],
  "main": "src/index.tsx",
  "dependencies": {
    "loader-utils": "3.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1",
    "@mui/x-tree-view": "7.5.0",
    "@mui/material": "5.15.19",
    "@emotion/styled": "11.11.5",
    "@emotion/react": "11.11.4"
  },
  "devDependencies": {
    "@types/react": "18.2.38",
    "@types/react-dom": "18.2.15",
    "typescript": "4.4.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": [">0.2%", "not dead", "not ie <= 11", "not op_mini all"]
}
```

Browser:  Chrome Version 125.0.6422.141 (Official Build) (arm64)
</details>

**Search keywords**: space 7.5.0

**Comment by flaviendelangle** [comment]
Hi,

Thanks for your feedback
Looks like the behavior change was introduced in #11452, now we also take into account the events fired from sub-elements of the item in our `onKeyDown`. 

Here is [the updated example with the fix](https://codesandbox.io/p/sandbox/mui-x-tree-view-7-5-0-space-bug-forked-g7z9mx?file=%2Fsrc%2FApp.tsx%3A49%2C1)

By the way, we are currently working on a built-in edition feature for our Tree View that should give you an easy and clean way to build a file-explorer.

**Comment by mosofsky** [comment]
Glad to hear there is a way to fix this

Can you check permissions for the URL you provided? I’m getting a 404

Thank you!

Sent from my iPhone

On Jun 12, 2024, at 2:13 AM, Flavien DELANGLE ***@***.***> wrote:

﻿

Hi,

Thanks for your feedback
Looks like the behavior change was introduced in #11452<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mui_mui-2Dx_pull_11452&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=_SIsTSZtdyKC7Sg3sfmFRFiAED14bjKQgLgAyx0cnjY&m=x5sZ0RWdvZ5ynhqlnEWl8B0cd78q2oQ0mi6ZMvQeNaeJrxUdVm4JJwpRr6LwcCBc&s=Ul53mRRNJFZZsMdDplh4PEcS1n5_byKE-dUBkM2APuk&e=>, now we also take into account the events fired from sub-elements of the item in our onKeyDown.

Here is the updated example with the fix<https://urldefense.proofpoint.com/v2/url?u=https-3A__codesandbox.io_p_sandbox_mui-2Dx-2Dtree-2Dview-2D7-2D5-2D0-2Dspace-2Dbug-2Dforked-2Dg7z9mx-3Ffile-3D-252Fsrc-252FApp.tsx-253A49-252C1&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=_SIsTSZtdyKC7Sg3sfmFRFiAED14bjKQgLgAyx0cnjY&m=x5sZ0RWdvZ5ynhqlnEWl8B0cd78q2oQ0mi6ZMvQeNaeJrxUdVm4JJwpRr6LwcCBc&s=kfB-fasJkO0D5rcJ4yyDzfd9eHiGDseoWeoWPsYt_xs&e=>

By the way, we are currently working on a built-in edition feature for our Tree View that should give you an easy and clean way to build a file-explorer.

**Comment by flaviendelangle** [comment]
The access should be fixed :+1:

**Comment by mosofsky** [comment]
Solution confirmed.  Thank you!
