### ISSUE TITLE
[data grid] Sorting with treeData does not seem to work

### ISSUE THREAD

**Issue by genepaul** [mui/mui-x#13469]
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/tree-data/#system-TreeDataDisableChildrenSorting.tsx

Steps:
1. Go to the link in above in the documentation
2. Notice that, under `Thomas`, the child rows are not in alphabetical order:

<img width="157" alt="image" src="https://github.com/mui/mui-x/assets/66479/27b09de4-5a28-4761-8fdb-9556f222dac2">

This occurs regardless of whether `disableChildrenSorting` is enabled.

### Current behavior

Does not seem to be sorting tree rows correctly. I can't seem to figure out why.

### Expected behavior

I would expect each same-level items in the tree to be sorted within them. So if you have the following hierarchy:

- Z
  - C
  - B
- Y
  - F
  - E
    - U
    - Q

Sorting ascending should result in the following tree:

- Y
   - E
     - Q
     - U 
  - F
- Z
  - B
  - C

Interestingly, when I pass a `sortComparator` to the `groupingColDef` and log out the values (`v1` and `v2`) passed to that function, a couple things I noticed:
- The `value` is different depending on whether the rowNode is a group or a leaf  (groups have a value of the number of children, and leaves have the path value)
- Not all rows are being compared. 

### Context

I'm trying  to create a grid with tree data, and wanting my users to be able to sort by the grouping column. I  set `sortable: true` on the `groupingColDef` to allow for this.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 14.4.1
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.8.1 - ~/Developer/component-library/node_modules/.bin/npm
    pnpm: 9.1.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.57
    Edge: 125.0.2535.92
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ^11.7.1 => 11.11.4 
    @emotion/styled: ^11.6.0 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.19 
    @mui/icons-material: ^5.11.16 => 5.15.19 
    @mui/lab: 5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: ^5.15.16 => 5.15.19 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.6.2 
    @mui/x-data-grid-premium: ^7.4.0 => 7.6.2 
    @mui/x-data-grid-pro:  7.6.2 
    @mui/x-date-pickers: ^7.0.0 => 7.6.2 
    @mui/x-date-pickers-pro: ^7.0.0 => 7.6.2 
    @mui/x-license: ^7.0.0 => 7.6.1 
    @types/react: ^18.2.79 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: ^5.2.2 => 5.4.5 
```
</details>

**Search keywords**: treeData sorting
**Order ID**: 0332927583

**Comment by michelengelen** [comment]
Hey @genepaul the sorting in this demo is not using the group field, but the `recruitmentDate`:

```tsx
const [sortModel, setSortModel] = React.useState<GridSortModel>([
  { field: 'recruitmentDate', sort: 'asc' },
]);
```

Sorting the grouping column is possible with the

**Comment by genepaul** [comment]
Ok, I see where my issue was, and I used the wrong example to demonstrate the problem. This is a problem with the integration between Aggregation and Tree Data, and may be a misunderstanding on my part of how we should do aggregation of the group column. What I'm trying to accomplish is allowing to set an aggregation on the Grouping column. When I do that, the grouping column's `value` gets set to the aggregated value for that group, rather than the grouping field information. This messes up the display of the grouping column, as well as the sorting. The values that get passed to the `sortComparator` become that aggregated value rather than the grouping key:

https://codesandbox.io/p/sandbox/nice-forest-98pwp4?file=%2Fsrc%2FDemo.tsx

Is what I'm trying to do even possible or recommended? I'm creating a component that wraps DataGrid and want to give my users the ability to create custom aggregations to show in the footer of the grouping column (like calculating the size at each level of the tree).

**Comment by michelengelen** [comment]
Yes, I think that is possible and we had a similar case a few weeks ago... I'll try to find it, but I know that @cherniavskii did come up with a solution for it, so he will know for sure.

**Comment by cherniavskii** [comment]
@genepaul Are you saying that you only want the top-level aggregation in the footer, but not for the grouping rows? Instead, the grouping rows should display the data from the corresponding field in the row itself.
Do I understand this correctly?

**Comment by genepaul** [comment]
Correct.

**Comment by cherniavskii** [comment]
Interesting, I believe It's the first time we're asked about this.

I think the [`getAggregationPosition` prop](https://mui.com/x/api/data-grid/data-grid-premium/#data-grid-premium-prop-getAggregationPosition) should help here.
In your case, you only want to aggregate the top-level rows (the ones with `null` parent):
```tsx
getAggregationPosition={groupNode => groupNode.parent === null ? "footer" : null}
```
Here's a working demo: https://codesandbox.io/p/sandbox/hopeful-shannon-l7f573?file=%2Fsrc%2FDemo.tsx%3A44%2C56&workspaceId=91a5c27a-eb18-443d-ad50-311c5bb7f22d

Out of curiosity, do you allow users to change the aggregation type for the column? What would happen if they select a different aggregation?
