### ISSUE TITLE
[pickers] How to change mui toolbar date text colour and max width to 1000

### ISSUE THREAD

**Issue by achoud444** [mui/mui-x#13462]
### Summary

I am using MUI Mobile date range picker with 2 calendars. I want to change the color of the toolbar date text and want to remove the max-width so it does not have horizontal scroll. 

Here is how it looks like right now
[![enter image description here][1]][1]
Here is the code

    const MyActionBar = ({
      onCancel,
      className
    }: PickersActionBarProps, onAccept: Function) => {
      return (
        <DialogActions className={className}>
          <Button onClick={onCancel} variant='contained'>Cancel</Button>
          <Button onClick={() => onAccept()} variant='contained'>Ok</Button>
        </DialogActions>
      );
    };
    
    const wrappedRenderDateRangeViewCalendar = (props: any) =>
      renderDateRangeViewCalendar({ ...props, calendars: 2 });
    
    export default function CustomMobileDatePicker({
    	open,
    	setOpenMobilePicker,
    	onAccept,
    	value,
    	onChange
    }: {
    	open: boolean;
    	setOpenMobilePicker: Function;
    	onAccept: Function;
    	onChange: Function;
    	value: DateRange<Dayjs>;
    }) {
    	const appTheme = useTheme();
    	return (
    		<LocalizationProvider dateAdapter={AdapterDayjs}>
    			<MobileDateRangePicker
    				open={open}
    				onClose={() => setOpenMobilePicker(false)}
    				onChange={(e) => onChange(e)}
    				value={value}
    				slots={{
    					textField: () => null,
    					fieldSeparator: () => null,
    					actionBar: (props) => MyActionBar(props, onAccept)
    				}}
    				slotProps={{
    					actionBar: { actions: ["cancel", "accept"] },
    					toolbar: { sx: { backgroundColor: appTheme.palette.primary.main } }
    				}}
    				maxDate={dayjs()}
    				viewRenderers={{
    					day: wrappedRenderDateRangeViewCalendar
    				}}
    				sx={{
    					'& .MuiPickersToolbar-root': {
    						color: 'white'
    					}
    				}}
    			/>
    		</LocalizationProvider>
    	);
    }

  [1]: https://i.sstatic.net/KnwMsMtG.png

**Search keywords**: How to change mui toolbar date text colour and max width to 1000

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by achoud444** [comment]
@michelengelen Thank you for your assistance. Here is the working example of what I did and what exactly I want.
https://codesandbox.io/p/sandbox/flamboyant-dubinsky-x3lvkn?file=%2Fsrc%2FDemo.tsx

**Comment by michelengelen** [comment]
got it ... here is an updated [DEMO](https://codesandbox.io/p/sandbox/festive-mestorf-pcqk4h?file=%2Fsrc%2FDemo.tsx%3A16%2C21)

**Comment by LukasTy** [comment]
You can also consider using more specific classes if you want more control over colors:
```ts
toolbar: {
  sx: (theme) => ({
    backgroundColor: "#455d7a",
    color: theme.palette.info.main,
    [`& .${pickersToolbarTextClasses.root}`]: {
      color: theme.palette.info.main,
    },
    [`& .${pickersToolbarTextClasses.selected}`]: {
      color: theme.palette.info.light,
    },
  }),
}
```

**Comment by achoud444** [comment]
@michelengelen Exactly this is what I needed. Thank you very much for the help.
I have one more question like can I change the title to something else "Select date range" to something else?

**Comment by michelengelen** [comment]
I don't think it is ... at the very least you would lose the ability to use translations ... @LukasTy is there a way to do this?

**Comment by LukasTy** [comment]
@achoud444 Of course, all the labels are stored in the localization, which you can override.
For the picker toolbars, try specifying this on the `LocalizationProvider`:
```
```

**Comment by achoud444** [comment]
Awesome!!! Thank you very much both of you.

**Comment by LukasTy** [comment]
I'm glad we could resolve your problems. 🙌 
I'm closing this issue as all the problems seem to have been resolved. 👌 

P.S. Feel free to check the [Translated components](https://mui.com/x/react-date-pickers/localization/) page and the linked translations interface for all available options.

**Comment by achoud444** [comment]
@LukasTy Right now the text is in Captial letters I want to make it in Small
What I can see `ROOT TOOLBAR TITLE
What I want `Root toolbar title`

```
localeText={{
  dateRangePickerToolbarTitle: "Root toolbar title",
}}
```

**Comment by LukasTy** [comment]
@achoud444 The uppercase style is coming from the `Typography` component.
If you need to override this, try adding the following style to the `toolbar.sx`:
```ts
[`> .${typographyClasses.root}`]: {
  textTransform: "unset",
},
```

**Comment by achoud444** [comment]
@LukasTy @michelengelen I have a question if you can answer please
 Is it better to use the sx property in MUI for styling components, or should I write the CSS in a separate file and override the CSS?

**Comment by LukasTy** [comment]
> Is it better to use the sx property in MUI for styling components, or should I write the CSS in a separate file and override the CSS?

@achoud444 I'd say that this is almost a "religious" question. 🙈 
If you prefer regular CSS declaration methods—feel free to use them, just be aware that you are responsible for adjusting classes if they ever change on the components. 😉 
CSS-in-JS methods provide a more robust API and have the capability to purge unused properties (if you override the property, that is already set on a component—it might be omitted in the final bundle).
You can learn about the performance topic of CSS-in-JS [here](https://mui.com/system/getting-started/usage/#performance-tradeoffs).
Be aware that if a component is already `styled` on our components, using sx will not impact the performance in a meaningful way, it's mostly a question for creating new components, where performance is better the closer we go to primitives.

P.S. MUI is working on [Pigment CSS](https://mui.com/blog/introducing-pigment-css/), which will mostly negate the performance problems, by extracting CSS at build time.
