### ISSUE TITLE
[data grid] all nodes are closing while row is being selected

### ISSUE THREAD

**Issue by agirgol** [mui/mui-x#13470]
I am using treedata in the DataGridPro table and keeping the row ids to perform operations based on the selected rows. But when retrieving the ids, the table nodes are closed. In other words, the nodes close in every line I select. What method should I follow so that the nodes do not close and remain as they are?

```tsx
import * as React from 'react';
import { DataGridPro, GridColDef, GridPaginationModel, GridRowId } from '@mui/x-data-grid-pro';
import axios from 'axios';
import CompanyClaimTableListTopBar from './CompanyClaimTableListTopBar';
import { Box } from '@mui/material';

interface Item {
  id: string;
  companyClaimCode: string;
  companyClaimName: string;
  status: number;
  level: number;
  upperCompanyClaimId: string | null;
}

const status = [
  {
    value: 0,
    label: 'Active',
  },
  {
    value: 1,
    label: 'Inactive',
  },
  {
    value: 2,
    label: 'Archive',
  },
  {
    value: 3,
    label: 'Cancel',
  },
];

const transformData = (
  items: Item[],
): {
  path: string;
  id: string;
  companyClaimCode: string;
  companyClaimName: string;
  status: number;
}[] => {
  items.sort((a, b) => {
    if (a.level !== b.level) {
      return a.level - b.level;
    } else {
      return a.companyClaimName.localeCompare(b.companyClaimName);
    }
  });

  const transformedData: {
    path: string;
    id: string;
    companyClaimCode: string;
    companyClaimName: string;
    status: number;
  }[] = [];

  const map: {
    [id: string]: {
      path: string;
      id: string;
      companyClaimCode: string;
      companyClaimName: string;
      status: number;
    };
  } = {};

  items.forEach((item) => {
    map[item.id] = {
      path: item.companyClaimName,
      id: item.id,
      companyClaimCode: item.companyClaimCode,
      companyClaimName: item.companyClaimName,
      status: item.status,
    };

    if (item.upperCompanyClaimId) {
      const upperItem = map[item.upperCompanyClaimId];
      map[item.id].path = `${upperItem.path}/${map[item.id].path}`;
    }

    transformedData.push(map[item.id]);
  });

  return transformedData;
};

function getStatusLabel(value: number): string {
  const statusObj = status.find((s) => s.value === value);
  return statusObj ? statusObj.label : 'Unknown';
}

const columns: GridColDef[] = [
  { field: 'companyClaimCode', headerName: 'Company Claim Code', width: 150 },
  { field: 'companyClaimName', headerName: 'Company Claim Name', width: 250 },
  {
    field: 'status',
    headerName: 'Status',
    width: 150,
    renderCell: (params) => getStatusLabel(params.value as number),
  },
];

export default function TreeDataGrid() {
  const [rows, setRows] = React.useState<{ path: string; id: string; companyClaimName: string }[]>(
    [],
  );
  const [loading, setLoading] = React.useState<boolean>(true);
  const [paginationModel, setPaginationModel] = React.useState<GridPaginationModel>({
    page: 0,
    pageSize: 5,
  });
  const [rowCount, setRowCount] = React.useState<number>(0);
  const [selectedRowIds, setSelectedRowIds] = React.useState<Set<GridRowId>>(new Set());

  const fetchData = async (page: number, pageSize: number) => {
    setLoading(true);
    try {
      const response = await axios.get('/api/CompanyClaims', {
        params: { page, pageSize },
      });
      const { items, count } = response.data;
      const transformedRows = transformData(items);
      setRows(transformedRows);
      setRowCount(count);
    } catch (error) {
      console.error('Failed to fetch data', error);
    } finally {
      setLoading(false);
    }
  };

  const handlePaginationModelChange = (newModel: GridPaginationModel) => {
    setPaginationModel(newModel);
  };

  const handleRowSelectionChange = (newSelection: GridRowId[]) => {
    setSelectedRowIds(new Set(newSelection));
  };

  const handleDelete = () => {
    const idsArray = Array.from(selectedRowIds);
    const requestBody = { ids: idsArray };

    axios
      .delete('/api/CompanyClaims', {
        data: requestBody,
      })
      .then((response) => {
        console.log('API Response:', response.data);
        fetchData(paginationModel.page, paginationModel.pageSize);
      })
      .catch((error) => {
        console.error('Error:', error);
      });
  };

  React.useEffect(() => {
    fetchData(paginationModel.page, paginationModel.pageSize);
  }, [paginationModel]);

  return (
    <Box>
      <CompanyClaimTableListTopBar
        numSelected={selectedRowIds.size}
        selectedIds={selectedRowIds}
        onDelete={handleDelete}
      />
      <DataGridPro
        treeData
        getTreeDataPath={(row) => row.path.split('/')}
        rows={rows}
        columns={columns}
        loading={loading}
        pagination
        paginationMode="server"
        rowCount={rowCount}
        pageSizeOptions={[5, 10, 20]}
        paginationModel={paginationModel}
        onPaginationModelChange={handlePaginationModelChange}
        checkboxSelection
        onRowSelectionModelChange={handleRowSelectionChange}
      />
    </Box>
  );
}
```

**Comment by michelengelen** [comment]
@agirgol We currently have no way of controlling the open/closed state of tree data.

The code you provided looks ok, but could you please try to replicate this in a codesandbox with a dummy server?
It would really help to see it in action.

**Comment by agirgol** [comment]
Of course, you can access it from the link below.[https://codesandbox.io/p/sandbox/treedata-h9zn94?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxczwlaq0006356jmsmr5gqi%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxczwlaq0002356jk64zcv8c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxczwlaq0003356jb3myq6nh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxczwlaq0005356jzaafucjb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxczwlaq0002356jk64zcv8c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxczwlap0001356jqu9h8v06%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clxczwlaq0002356jk64zcv8c%2522%252C%2522activeTabId%2522%253A%2522clxczwlap0001356jqu9h8v06%2522%257D%252C%2522clxczwlaq0005356jzaafucjb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxczwlaq0004356jaspebkbe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxczwlaq0005356jzaafucjb%2522%252C%2522activeTabId%2522%253A%2522clxczwlaq0004356jaspebkbe%2522%257D%252C%2522clxczwlaq0003356jb3myq6nh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxczwlaq0003356jb3myq6nh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D](url)

**Comment by agirgol** [comment]
Of course, you can access it from the codesandbox link below. [](https://codesandbox.io/p/sandbox/treedata-h9zn94?file=%2Fsrc%2Fcomponents%2FTreeDataGrid.tsx%3A3%2C15)

**Comment by agirgol** [comment]
Of course, you can access it from the codesandbox link below. [](https://codesandbox.io/p/sandbox/treedata-h9zn94)

**Comment by michelengelen** [comment]
Ah, now I get it.
So the problem is that you are controlling the `selectedRowIds`. The state update will trigger a rerender and since we have no controlled state for the opened/closed grouped rows in the tree data it will default to the initial state.
Not sure id we can do something about that atm.
@MBilalShafi do you have any idea if we can provide a workaround for that?

**Comment by cherniavskii** [comment]
@agirgol 

Move the `getTreeDataPath` definition outside of the component so it has stable reference:
```diff
+const getTreeDataPath: DataGridProProps<"getTreeDataPath"> = (row) => row.path.split("/");


<DataGridPro
-  getTreeDataPath={(row) => row.path.split("/")}
+  getTreeDataPath={getTreeDataPath}
```

Or wrap it with `useCallback`:

```diff
+const getTreeDataPath = React.useCallback<
+  DataGridProProps<"getTreeDataPath">
+>((row) => row.path.split("/"), []);

<DataGridPro
-  getTreeDataPath={(row) => row.path.split("/")}
+  getTreeDataPath={getTreeDataPath}
+
```

Working demo: https://codesandbox.io/p/sandbox/treedata-forked-tq5xhd?file=%2Fsrc%2Fcomponents%2FTreeDataGrid.tsx%3A121%2C5

**Comment by agirgol** [comment]
Thank you very much for your support. Your suggestions worked.

**Comment by cherniavskii** [comment]
@agirgol I've added a warning to the Tree Data docs in https://github.com/mui/mui-x/pull/13519, thanks for your feedback!

**Comment by agirgol** [comment]
Since my data template is not the same template, I used useCallback by changing it according to the data as follows.`const getTreeDataPath: DataGridProProps['getTreeDataPath'] = React.useCallback(
    (row: any) => {
      const pathArray = row.path.split("/");
      return pathArray;
    },
    []
  );` [https://codesandbox.io/p/sandbox/treedata-h9zn94](url)
