### ISSUE TITLE
[data grid] DataGrid inside Dialog doesn't show the full column list

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#13473]
### Steps to reproduce

Link to live example: (required) **https://codesandbox.io/p/sandbox/kind-roman-jqt8hy?file=%2Fsrc%2FApp.js%3A23%2C3**

Steps:
1.
2.
3.

### Current behavior

Datagrid inside the dialog doesn't show the full column list when it is placed at the end/bottom.
![image](https://github.com/mui/mui-x/assets/24405994/ada2e02e-8e4b-4cce-adb5-94cabd08202d)

Noticed taht the scroll bar is already at the end but the column full list isn't shown

### Expected behavior

The column list of the datagrid inside the dialog should be shown like if the data grid is not in dialog.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid, dialog
**Order ID**: 33625

**Comment by michelengelen** [comment]
Hey @simbahandiane the sandbox you shared is not public.
Could you change that so we can have a look? 
Thanks! 🙇🏼

**Comment by simbahandiane** [comment]
@michelengelen Can you try this [link ](https://codesandbox.io/p/sandbox/kind-roman-jqt8hy?file=%2Fsrc%2FApp.js%3A23%2C3&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxaqacsy0007356gvo9qqv6o%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxaqacsy0003356g0qwbzjor%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxaqacsy0004356gro35rx8p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxaqacsy0006356gx5uihdlf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxaqacsy0003356g0qwbzjor%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxaqacsy0002356ggq0rsb93%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A3%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxaqacsy0003356g0qwbzjor%2522%252C%2522activeTabId%2522%253A%2522clxaqacsy0002356ggq0rsb93%2522%257D%252C%2522clxaqacsy0006356gx5uihdlf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxaqacsy0005356gvbkz1iup%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxaqacsy0006356gx5uihdlf%2522%252C%2522activeTabId%2522%253A%2522clxaqacsy0005356gvbkz1iup%2522%257D%252C%2522clxaqacsy0004356gro35rx8p%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxaqacsy0004356gro35rx8p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A14.244791666666671%257D)and let me know if you can access it now?

**Comment by michelengelen** [comment]
Yes, it works.
I did check the underlying code for the panel and I think we could just change the default behavior.

```diff
diff --git a/packages/x-data-grid/src/components/panel/GridPanel.tsx b/packages/x-data-grid/src/components/panel/GridPanel.tsx
index a82b53b37..6109783f4 100644
--- a/packages/x-data-grid/src/components/panel/GridPanel.tsx
+++ b/packages/x-data-grid/src/components/panel/GridPanel.tsx
@@ -79,7 +79,7 @@ const GridPanel = React.forwardRef<HTMLDivElement, GridPanelProps>((props, ref)
     () => [
       {
         name: 'flip',
-        enabled: false,
+        enabled: true,
       },
       {
         name: 'isPlaced',
```

Should we just make this change @cherniavskii ?

**Comment by cherniavskii** [comment]
@michelengelen 

The flip was disabled in https://github.com/mui/mui-x/pull/837#discussion_r555295697. I believe the goal was to avoid this effect:

https://github.com/mui/mui-x/assets/13808724/24fe306a-9c5f-4e0c-8892-8304c15ace71

How about doing this instead?

```tsx
{
  name: 'flip',
  enabled: true,
  options: {
    rootBoundary: 'document'
  }
},
```

**Comment by michelengelen** [comment]
> @michelengelen
> 
> The flip was disabled in [#837 (comment)](https://github.com/mui/mui-x/pull/837#discussion_r555295697). I believe the goal was to avoid this effect:
> 
>  Screen.Recording.2024-06-14.at.17.24.29.mov 
> How about doing this instead?
> 
> ```tsx
> {
>   name: 'flip',
>   enabled: true,
>   options: {
>     rootBoundary: 'document'
>   }
> },
> ```

Yes, sounds good.
I have updated my diff.
Lets label this a good first issue

**Comment by simbahandiane** [comment]
@michelengelen  @cherniavskii We are currently in version 6. Is there any way that this fix can also be published on version 6? If it can't be, is there a work around that we can do for now?

**Comment by simbahandiane** [comment]
> @michelengelen @cherniavskii We are currently in version 6. Is there any way that this fix can also be published on version 6? If it can't be, is there a work around that we can do for now?

@michelengelen @cherniavskii A gentle follow up on this.

**Comment by romgrk** [comment]
I'll cherry-pick the PR on v6, but we recommend upgrading to v7, eventually bugfixes will not be published anymore on v6.
