### ISSUE TITLE
[data grid] Changing columnHeaders className not working as expected

### ISSUE THREAD

**Issue by fdebef** [mui/mui-x#13484]
### The problem in depth

In last project I used for changing column headers background color:

```
'& .MuiDataGrid-columnHeaders': {
  // currently unused, changed to container--top
  backgroundColor: 'rgb(69,153,236)',
  color: 'white',
},
```

But now this does not work, because the columnHeader classname is override with 
`'& .MuiDataGrid-container--top [role=row]': `
in the above div. 

So I have to change to color also for this className. This workaround works, but what has changed, why the columnHeaders is not enough? 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: macOS 14.5
  Binaries:
    Node: 21.4.0 - /usr/local/bin/node
    npm: 10.5.2 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 125.0.6422.142
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.19 
    @mui/material: ^5.15.18 => 5.15.19 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.6.2 
    @mui/x-data-grid-premium: ^7.5.0 => 7.6.2 
    @mui/x-data-grid-pro:  7.6.2 
    @mui/x-license:  7.6.1 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.66 => 18.3.3 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^5.2.2 => 5.4.5 
```
</details>

**Search keywords**: background color styling
**Order ID**: 78510

**Comment by michelengelen** [comment]
Hey @fdebef ... i am not sure why we did this change (@romgrk would be the best to answer this), but you can easily change the background color by using the CSS variable:

```tsx
const defaultTheme: Theme = createTheme({
  typography: {
    fontSize: 14,
    fontFamily: 'Roboto Condensed',
  },
  components: {
    MuiDataGrid: {
      styleOverrides: {
        root: {
          '--DataGrid-containerBackground': 'rgb(69,153,236)',
        },
      },
    },
  },
});
```

That being said: @mui/xgrid should we maybe export a constant similar to `gridClasses` for the variables to make them easier to override?

**Comment by romgrk** [comment]
We needed access to the color. The doc explains how to customize it here: https://mui.com/x/react-data-grid/style/#theme-header-and-pinned-sections

**Comment by fdebef** [comment]
A bit confusing compared to columnHeaders but OK .
But neither you, nor documentation talks about the color property. (color of header text). How would you change it. 

BUT!!!! Within playing with this stuff I think I've discovered the issue:
In version 6.8 you use the selector

`.MuiDataGrid-columnHeaders`

And so is it rescribed in documentation
https://mui.com/x/api/data-grid/data-grid/#DataGrid-css-MuiDataGrid-columnHeaders

But in 7.5 you switched to 
`.MuiDataGrid-columnHeader` (omitting the last s)

Is it intention or mistake?

**Comment by michelengelen** [comment]
We actually have both `columnHeaders` which is the container holding all headers and `columnHeader` which is a single header.

The color is defined on the root component, so a more specific selector should be easily able to overwrite that.

adding this will change the text color:
```tsx
[`& .${gridClasses.columnHeader}`]: {
  color: 'white',
},
```

I do agree though that we could improve the theming capabilities, since this change would not affect the icon buttons.

@romgrk is currently working on making the grid theme agnostic, so insight here is very valuable.

For now we would need to use more specific selectors to target the icon buttons, etc. separately.

**Comment by fdebef** [comment]
I have tried in Stackblitz, and it really works. There is something wrong with my project, maybe relating to this issue, too:
https://github.com/mui/mui-x/issues/13483#issuecomment-2168040129

Might it be the combination of Tailwind and Mui? I really want to stay on Mui DataGrid, but need other styling with Tailwind.

**Comment by michelengelen** [comment]
No, the combination of Tailwind and Mui X shouldn't be a problem.
We just recently (on a conference in Amsterdam) heard from users who effectively use both and it works great for them.

The only thing I could think if is the tailwind build-process.
But without knowing the setup it is hard to tell.

I will try and setup a project with it ... @joserodolfofreitas this might be another case to add as a how-to to the docs. WDYT?

**Comment by michelengelen** [comment]
@fdebef can you provide your setup specifics, so we can check that? Otherwise there isn't really that much we can do right now unfortunately.

**Comment by fdebef** [comment]
I'm stuck here. 
This is the [simpliest project](https://github.com/fdebef/MuiIssueTracker), where I experience different behavior in IntelliJIdea Ultimate (not working) and VS Code (working).
I've created very new project in IntelliJ and it behaves the same: 
Issue with columnHeader/s 
TypeScript type for Theme not working (another issue here)

I suggest to close this issue as it seems like it is not yours problem - in VS Code everything is working. A highly appreciate your effort to me, thank you very much.

**Comment by joserodolfofreitas** [comment]
> this might be another case to add as a how-to to the docs. WDYT?

Yes, for sure. 
In fact, styling the DataGrid with Tailwind is one of the most relevant examples we want to showcase.
