### ISSUE TITLE
[data grid] single click on IconButton inside data grid not works

### ISSUE THREAD

**Issue by agarg-solveda** [mui/mui-x#13480]
### The problem in depth

Clicking on the IconButton inside the Data Grid does not work in a single click. We have to click two times to execute the handler of the IconButton. We have also tried MuiButton and GridActionsCellItem and the behavior is the same. It requires a double click.
Attaching some code snippet screenshots and recording of issue.
![Screenshot from 2024-06-14 16-41-57](https://github.com/mui/mui-x/assets/158030342/72f9a892-a565-41e6-8533-a3380e3dd0ca)
![Screenshot from 2024-06-14 16-41-38](https://github.com/mui/mui-x/assets/158030342/3eec5da4-e2cd-4b79-b3f7-abb87c387bfc)

https://github.com/mui/mui-x/assets/158030342/dfffecc9-61e1-46a0-8062-1a9705c95a34

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: mui data grid, IconButton, GridActionsCellItem
**Order ID**: 88539

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by agarg-solveda** [comment]
Sure, I will share the code sandbox link with minimal use cases by 20th June, EOD
