### ISSUE TITLE
[data grid] Typescript of Theme of `MuiDataGridPremium`

### ISSUE THREAD

**Issue by fdebef** [mui/mui-x#13483]
### The problem in depth

I have some difficulties with styling Typescript, although I am importing 

```
import { createTheme, Theme } from '@mui/material/styles';
import { csCZ } from '@mui/x-data-grid-premium/locales';
import type {} from '@mui/x-data-grid-premium/themeAugmentation';
```

I still get Typescript error using MuiDataGrid component in createTheme options:

```
const theme: Theme = createTheme(
  {
    typography: {
      fontSize: 14,
      fontFamily: 'Roboto Condensed',
    },
    components: {
      MuiDataGrid: {
        styleOverrides: {
          root: {
            '& .MuiDataGrid-footerContainer': {
              minHeight: '32px',
              border: '0',
            },

```

The typescript definition in themeAugmentation seems like to be ok, but in the code it does not work. 

The typescript error is:
```
{typography: {fontFamily: "Asap Condensed", fontSize: number}, components: {MuiDataGrid: {styleOverrides: {root: {'& .MuiDataGrid-columnHeader.MuiDataGrid-withBorderColor':....
is not assignable to type
Components<Omit<Theme, 'components'>> | undefined
```

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: macOS 14.5
  Binaries:
    Node: 21.4.0 - /usr/local/bin/node
    npm: 10.5.2 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 125.0.6422.142
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.19 
    @mui/material: ^5.15.18 => 5.15.19 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.6.2 
    @mui/x-data-grid-premium: ^7.5.0 => 7.6.2 
    @mui/x-data-grid-pro:  7.6.2 
    @mui/x-license:  7.6.1 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.66 => 18.3.3 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^5.2.2 => 5.4.5 
```
</details>

**Search keywords**: typescript createTheme themeAugmentation
**Order ID**: 78510

**Comment by michelengelen** [comment]
Hey @fdebef I'll have a look shortly! 👍🏼

**Comment by michelengelen** [comment]
It seems to work quite well with my local instance:

<img width="1059" alt="Screenshot 2024-06-14 at 15 41 26" src="https://github.com/mui/mui-x/assets/32863416/d21ac13d-43d8-4e94-add7-d275bbab962f">

<img width="2787" alt="Screenshot 2024-06-14 at 15 41 29" src="https://github.com/mui/mui-x/assets/32863416/2120e984-493c-40cf-a813-bf57509cfe3e">

I'll have a deeper look later ... could potentiallly be next week though!

**Comment by michelengelen** [comment]
I could not find anything. @romgrk could you maybe also have a look?

**Comment by romgrk** [comment]
Could we get a [reproduction case](https://stackblitz.com/fork/github/mui/mui-x/tree/master/bug-reproductions/x-data-grid)?

**Comment by fdebef** [comment]
This is the [simpliest project](https://github.com/fdebef/MuiIssueTracker), where I experience different behavior in IntelliJIdea Ultimate (not working) and VS Code (working).
I've created very new project in IntelliJ and it behaves the same:
Issue with columnHeader/s
TypeScript type for Theme not working (another issue here)

I suggest to close this issue as it seems like it is not yours problem - in VS Code everything is working. A highly appreciate your effort to me, thank you very much.
