### ISSUE TITLE
[data grid] Microfrontend Host 'Each child in a list should have a unique "key" prop'

### ISSUE THREAD

**Issue by Miiiiii7** [mui/mui-x#13482]
### Steps to reproduce

Link to live example: https://github.com/Miiiiii7/microfrontend-react-vite

Steps:
1. Create a microfrontend with one remote app
2. On remote app use DataGrid
3. Run Host and it shows the error

### Current behavior

It shows a blank page and on console getting this error.

chunk-373CG7ZK.js?v=f5f622d5:519 Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at Tooltip2 (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:35737:17)
    at GridColumnHeaderTitle (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:22083:5)
    at div
    at div
    at div
    at div
    at GridGenericColumnHeaderItem (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:22167:7)
    at GridColumnHeaderItem (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:22275:5)
    at div
    at http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:1567:17
    at div
    at http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:1567:17
    at GridColumnHeaders (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:34816:7)
    at GridColumnHeaders2 (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:34834:5)
    at GridHeaders (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:18842:18)
    at div
    at http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:1567:17
    at GridTopContainer (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:18947:41)
    at div
    at http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:1567:17
    at div
    at http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:1567:17
    at http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:18909:26
    at GridVirtualScroller (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:19283:18)
    at div
    at http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:1567:17
    at GridRoot2 (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:21446:21)
    at GridContextProvider (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:28189:3)
    at DataGrid2 (http://localhost:5173/assets/__federation_expose_PokemonList-B1rxW7zH.js:37398:17)
    at div
    at div
    at PokemonList
    at App

### Expected behavior

It should open a page with a grid of pokemon list

### Context

Open Host app and visualize datagrid from remote app.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Used Browser: Chrome (126.0.6478.57)

  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: 126.0.2592.56
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.20 
    @mui/material: ^5.15.20 => 5.15.20 
    @mui/private-theming:  5.15.20 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.20 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.20 
    @mui/x-data-grid: ^7.7.0 => 7.7.0 
    @types/react: ^18.2.66 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: ^5.2.2 => 5.4.5 
```
</details>

**Search keywords**: DataGrid unique key

**Comment by michelengelen** [comment]
It works for me @Miiiiii7 

<img width="2743" alt="Screenshot 2024-06-14 at 15 22 27" src="https://github.com/mui/mui-x/assets/32863416/d40c539f-0721-4fa9-8ade-5a3e14036826">

Could you please try to provide reproduction steps that ensure that the error throws?
Thanks! 🙇🏼

**Comment by michelengelen** [comment]
That works for me as well (in my case the host opened on `http://192.168.2.33:5173/`)

Also your error message shows port `5173` 🤷🏼 

<img width="1272" alt="Screenshot 2024-06-14 at 15 56 24" src="https://github.com/mui/mui-x/assets/32863416/a565d3b1-0f23-4c75-8586-c0b70a6a0d4c">

**Comment by Miiiiii7** [comment]
@michelengelen this is the page error I get when I go to pokemons-home, run `npm run dev` after running the `npm run preview`on pokemons-list and open the port 5174
<img width="1435" alt="host error" src="https://github.com/mui/mui-x/assets/52251891/3e18a8c7-b58f-40ab-b3b0-cd1eb06e5b46">

This is the page without the DataGrid:
<img width="1434" alt="host without datagrid" src="https://github.com/mui/mui-x/assets/52251891/669b925f-70d7-4261-8ba1-436eadb30d43">

**Comment by michelengelen** [comment]
This is not a problem with the grid. This likely is a problem with the vite config.
From the error and a quick look at the docs it seems this is what you are looking for: https://github.com/originjs/vite-plugin-federation?tab=readme-ov-file#shared

**Comment by Miiiiii7** [comment]
@michelengelen I added the lib at shared dependencies on vite config and it solved the errors.
Thank you for your help!
