### ISSUE TITLE
[data grid] How to make different column names in the table header and in filters?

### ISSUE THREAD

**Issue by mimaxm** [mui/mui-x#13512]
### The problem in depth

We want to use column grouping.
The names of the groups must be different, but the names of the columns within the groups can be the same.
It looks fine in the table. But this creates a problem in the column manager and filters. Several columns with the same name appear there.
We need the ability to specify one name for the columns in the table header and another name for the column and filter manager.
For example, it would be nice to set the column name for the table header in "columnGroupingModel". And the column name specified in "columns" would be displayed in the column manager and in filters.
Or somehow make a display like this: "Name from "columnGroupingModel" (groupId)".

https://codesandbox.io/p/sandbox/stoic-lichterman-czkdcm
![columnNames](https://github.com/mui/mui-x/assets/66064167/c34b9a31-09a1-4024-8f89-c984c37ad1b7)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: grouped column title, header
**Order ID**: 72020

**Comment by michelengelen** [comment]
Hey @mimaxm we do not support this out of the box, but as a workaround you can use the `renderHeader` function on the column definition in combination with the `headerName` property.

The panels will use the `headerName`, whereas the column header will render from the `renderHeader` function.

[Example](https://codesandbox.io/p/sandbox/brave-ramanujan-4tg7qs?file=%2Fsrc%2FDemo.tsx%3A43%2C11)

**Comment by mimaxm** [comment]
@michelengelen This solution works for me, thanks!

**Comment by michelengelen** [comment]
Great! 👍🏻
