### ISSUE TITLE
[x-license] License of MUI X Premium license shows as MUI expired package version

### ISSUE THREAD

**Issue by sbitenc** [mui/mui-x#13514]
### The problem in depth

I purchased the license recently, and now upgraded to latest package and under my license it says:
```
Here is more information about your MUI X Premium license.

Development use, support, and updates expiry date:
Jan 11, 2025
```

However, mui datagrid says MUI expired package version.
Can you re-activate the license to work?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: MUI X Premium license shows as MUI expired package version
**Order ID**: 82010

**Comment by zannager** [comment]
@sbitenc can you please share the license key you are using in sales@mui.com? Thanks.

**Comment by sbitenc** [comment]
hi @zannager email with key sent to the sales email

**Comment by sbitenc** [comment]
Hi @michelengelen could this be looked into, it's blocking my production release?

**Comment by michelengelen** [comment]
Hey @sbitenc I did just try your key in a production environment and it does work just fine for me. Could you share with us how you registered the license key in code and what kind of setup you use? nextjs, SSR, browser and version, etc.

**Comment by sbitenc** [comment]
Hi, we use react, with vite. I'm using latest brave browser (the issue is browser agnostic), and the value is injected via `LicenseInfo.setLicenseKey(environmentConfig.REACT_APP_DATAGRID_PRO_KEY);`

But we get the expired license issue when done so (we're using env to inject it)

**Comment by michelengelen** [comment]
is the component you are injecting this a client component?

**Comment by sbitenc** [comment]
i'm injecting it right into the app. I'll see how to update the deprecated call first. But here's the code i have

```ts
import { mixpanelCookiesManagement } from '@/global/components/cookies-consent-dialog/helpers/mixpanel-cookies-management';
import { removeExpiredCookiesConsent } from '@/global/components/cookies-consent-dialog/helpers/remove-expired-cookies-consent';
import { LicenseInfo } from '@mui/x-data-grid-premium';
import { environmentConfig } from '../environment-config';
import './App.css';
import { AppContent } from './app-content';
import { AppWrapper } from './app-wrapper';
import { tracker } from '@/global/helpers/tracker';

tracker.init();
removeExpiredCookiesConsent();
mixpanelCookiesManagement();

LicenseInfo.setLicenseKey(environmentConfig.REACT_APP_DATAGRID_PRO_KEY);

export const App: React.FC = () => {
  return (
    <AppWrapper>
      <AppContent />
    </AppWrapper>
  );
};
```

**Comment by michelengelen** [comment]
let me quickly set up a vite project and test it there... 
In the meantime could you try and test [this approach](https://mui.com/x/introduction/licensing/#next-js-app-router)?

I think we should add a section on vite as well ... wdyt @joserodolfofreitas ?

**Comment by sbitenc** [comment]
I've changed from `import { LicenseInfo } from '@mui/x-data-grid-premium';`
to `import { LicenseInfo } from '@mui/x-license';`

And it seems to be working. I didn't add the use client though, but it looks good on local, i'm deploying right now to see if it works on stage. But otherwise it seems to fix the issue 🤞

**Comment by joserodolfofreitas** [comment]
> let me quickly set up a vite project and test it there... In the meantime could you try and test [this approach](https://mui.com/x/introduction/licensing/#next-js-app-router)?
> 
> I think we should add a section on vite as well ... wdyt @joserodolfofreitas ?

That sounds like a good idea, @michelengelen! Let's do it!

**Comment by michelengelen** [comment]
OK @sbitenc 
I just tested it with a production build and it works fine for me.
Sry for didn't noticing you were importing `LicenseInfo` from the premium package.
This should be marked as deprecated, is it not?

Did it work after importing from the license package?

**Comment by sbitenc** [comment]
Hi, yes that resolved the issue!

Thanks for the help!

**Comment by michelengelen** [comment]
Great that we could help! 👍🏼
