### ISSUE TITLE
[data grid] MuiDataGrid-filler doesn't hide after collapsing the grouped row in the Datagrid table (treeData)

### ISSUE THREAD

**Issue by gulicJan** [mui/mui-x#13524]
### Steps to reproduce

Link to live example: (required)

https://codesandbox.io/p/sandbox/focused-brown-lvhcqz?file=%2Fsrc%2FDemo.tsx

Steps:
1. Remove the height: 400 from the table wrapper
2. When you expand and then collapse the grouping row, the height of the table doesn't shrink anymore - was this planned for v7 version?

### Current behavior

When a grouping row is expanded and then collapsed the table height stays the same as it was when the table was expanded.

### Expected behavior

Table height should shrink to the initial (minimum) size.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: grouping datatree MuiDataGrid-filler
**Order ID**: 64163

**Comment by gulicJan** [comment]
> It works when you use the `autoHeight` prop. [Documentation](https://mui.com/x/react-data-grid/layout/#auto-height)

But we shouldn't use autoHeight in our specific case since that deactivates virtualization.

**Comment by michelengelen** [comment]
Using virtualization with a fully dynamic layout is contradictory. The grid needs to know the dimensions in order to calculate the visible rows and buffer zone for a performant virtualization. This is impossible when there is no intrinsic dimension available.
