### ISSUE TITLE
[pickers][DatePicker] tracking focus state prevents picker from opening when using openPickerIcon

### ISSUE THREAD

**Issue by fabiandecuveland** [mui/mui-x#13526]
### Steps to reproduce

[Link to live example](https://codesandbox.io/p/sandbox/kind-snowflake-xqgd4t?file=%2Fsrc%2FApp.tsx)

Steps:
1. focus input field
2. click open picker button

### Current behavior

picker doesn't open, only opens on a second click

### Expected behavior

picker opens on first click as well

### Context

The focus state is supposed to be tracked to control the opening of a tooltip for form validation feedback.

**Search keywords**: focus, onFocus, openPickerIcon

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @fabiandecuveland this because the Icon in your example has no stable reference.
If you extract it to its own component it will work as expected. I have updated your example [here](https://codesandbox.io/p/sandbox/competent-galois-jfrxcf?file=%2Fsrc%2FApp.tsx%3A7%2C40)

**Comment by fabiandecuveland** [comment]
> Hey @fabiandecuveland this because the Icon in your example has no stable reference. If you extract it to its own component it will work as expected. I have updated your example [here](https://codesandbox.io/p/sandbox/competent-galois-jfrxcf?file=%2Fsrc%2FApp.tsx%3A7%2C40)

Indeed, thank you very much!
