### ISSUE TITLE
[data grid] How can I customize the data grid toolbar while still receiving slotProps from the data grid?

### ISSUE THREAD

**Issue by filipneculciu** [mui/mui-x#13527]
### The problem in depth

I'd like to know how I can customize the grid toolbar for the DataGridPro while still receiving slotProps from the DataGrid. I found the example in your documentation; however the toolbar in that example doesn't accept any props, so it can't take any slotProps from the data grid. For example, this doesn't work:

`slotProps={{
                            toolbar: {
                                csvOptions: {fileName: "testName"},
                                printOptions: {disableToolbarButton: true},
                            },
                        }}`

For the moment, I need to re-order the buttons in the toolbar and pass variant attributes to some of them, but I'll probably need to add more buttons in the future.

One solution I found is copying and modifying the standard implementation of the GridToolbar; which for my version of the package (6.18.0) I assume is: https://github.com/mui/mui-x/blob/v6.18.0/packages/grid/x-data-grid/src/components/toolbar/GridToolbar.tsx

Is this permitted by my license? 

Of course, this means I'll need to keep the modified implementation in sync with yours whenever I update the library. If there is a better solution that doesn't require this extra maintenance, please let me know.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 22.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.56)

</details>

**Search keywords**: datagrid toolbar props customize
**Order ID**: 70895

**Comment by michelengelen** [comment]
Hey @filipneculciu 
You can fully customize the toolbar and the props if needed

TDLR: Here is a short [demo](https://codesandbox.io/p/sandbox/distracted-andras-7n83wg?file=%2Fsrc%2FDemo.tsx%3A15%2C30)

---

We have some documentation and an example about how to customize the toolbar here: [Custom Toolbar](https://v6.mui.com/x/react-data-grid/components/#toolbar) (The second part of that section covers customization)

As well as a section covering how to pass custom props to the slotProps: [Custom slotProps with TypeScript](https://v6.mui.com/x/react-data-grid/components/#custom-slot-props-with-typescript)

It is important to know that passing custom props will always work, but using module augmentation will also satisfy typescript.

**Comment by filipneculciu** [comment]
What I'm trying to do is to create a custom toolbar that works with all the preexisting props; I'm not trying to add my own yet (but thank you for the example, it will be useful in the future). For example, the demo code doesn't pass printOptions to the export. I have modified the example to work with printOptions: https://codesandbox.io/p/sandbox/trusting-wilson-429rh9?file=%2Fsrc%2FDemo.tsx%3A35%2C19 . If I didn't add them to `<GridToolbarExport />`, the prop wouldn't have worked and the print button would still be visible.

Since I don't want to modify the toolbar every time I add a new toolbar prop (from the preexisting ones), I think the most straightforward solution is to copy this file in my app and modify it: https://github.com/mui/mui-x/blob/v6.18.0/packages/grid/x-data-grid/src/components/toolbar/GridToolbar.tsx

If this is allowed by the license I can go ahead with this solution. If you would like to suggest an alternative, please let me know.

**Comment by michelengelen** [comment]
Hey @filipneculciu yes, you are free to copy and modify it as you wish.
I would recommend using a very stripped down version of it as a starting point so you are not doubling implementation that eventually ends up as dead code
