### ISSUE TITLE
[data grid] Incorrect table height if height is inherited

### ISSUE THREAD

**Issue by ithrforu** [mui/mui-x#13536]
### Search keywords

height="100%", flex-grow="1", flexGrow="1", table height, table flex height, inherited height

### Latest version
- [x] I have tested the latest version

###  Link to live examples:
- [6.2.0](https://codesandbox.io/p/sandbox/jolly-thompson-lklgr7)
- [6.2.1](https://codesandbox.io/p/sandbox/fancy-brook-n45f5h), [changelog](https://github.com/mui/mui-x/releases/tag/v6.2.1)
- [latest version](https://codesandbox.io/p/sandbox/busy-minsky-wvdrml)

### Current behavior

Table **does not adjust**  to page height if height is inherited (the entire page has scrolling): [latest.webm](https://github.com/mui/mui-x/assets/81531000/5aaefadb-3e7c-4358-b422-027228479774).

### Expected behavior

Table **adjust** to page height if height is inherited (only table has scrolling): [6-2-0.webm](https://github.com/mui/mui-x/assets/81531000/b203b34c-0d41-453d-a6b1-e47a1484b1d1).

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

72020

**Comment by michelengelen** [comment]
Hey @ithrforu the latest version link is not working (sandbox is not public) ... could you update that please? Thanks!

**Comment by ithrforu** [comment]
@michelengelen, hey! 
Thanks, I updated the [link](https://codesandbox.io/p/sandbox/busy-minsky-wvdrml).

**Comment by michelengelen** [comment]
This seems like a problem with the `Box` component.
When you remove the wrapping `<Box flexGrow={1}>` it works as expected: [DEMO](https://codesandbox.io/p/sandbox/grid-height-latest-forked-6n2hgv?file=%2Fsrc%2FMain.tsx%3A17%2C71)

@mnajdova WDYT?

**Comment by ithrforu** [comment]
Yes, but i need `<Box flexGrow={1}>` for another layout.

**Comment by michelengelen** [comment]
Ok, found a solution.
`<Box flexGrow={1} sx={{ minHeight: 0 }}>` works perfectly fine! :D

**Comment by michelengelen** [comment]
Not sure why ... let me check

**Comment by michelengelen** [comment]
probably due to #8091

**Comment by michelengelen** [comment]
but, since this issue is fixed (or at least with a reasonable workaround) I will close it here!

**Comment by ithrforu** [comment]
@michelengelen, yes, i watched #8091, but still don't understand the reason.

I'd like to figure it out.

**Comment by ithrforu** [comment]
@michelengelen, 👋
