### ISSUE TITLE
[data grid] How to put links on elements of a grouping column ?

### ISSUE THREAD

**Issue by Yuki-Yamashita-DTRA** [mui/mui-x#13544]
### The problem in depth

I am writing to ask about "Tree data" of Data Grid.
How to put links on elements of a grouping column? (or is it possible?)
I want to make the highlighted part of the attached file a link.
![スクリーンショット 2024-06-19 152335](https://github.com/mui/mui-x/assets/173265797/907fbb0c-7e68-49dd-8dc7-4f8c81257a9a)

(I can put links on other elements of columns)
I tried many different ways and read documents but can't resolved.

Is there a way to solve this?

### Your environment

System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.56)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.20 
    @mui/icons-material: ^5.15.20 => 5.15.20 
    @mui/material: ^5.15.20 => 5.15.20
    @mui/private-theming:  5.15.20
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.20
    @mui/types:  7.2.14
    @mui/utils:  5.15.20
    @mui/x-data-grid:  7.7.0
    @mui/x-data-grid-premium: ^7.7.0 => 7.7.0
    @mui/x-data-grid-pro:  7.7.0
    @mui/x-license:  7.7.0
    @types/react:  18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript:  4.9.5

**Search keywords**: Tree data
**Order ID**: 89624

**Comment by michelengelen** [comment]
Hey @Yuki-Yamashita-DTRA 
This is definitely possible with a custom grouping cell renderer. 
We have this section of the docs explaining on how to customize it: [Custom grouping column](https://mui.com/x/react-data-grid/tree-data/#custom-grouping-column)

**Comment by Yuki-Yamashita-DTRA** [comment]
Hi michelengelen !
Thank you for the information.
And we look like can be done.
On the other hand, there's one more thing I'd like to ask you about Column Menu of Tree data.
I can set sot function on Custom grouping column but can't set column menu.
If possible, could you please tell me how to write it?
```
const groupingColDef = {
  headerName: 'Hierarchy',
  sortable : true
  renderCell: (params) => <CustomGridTreeDataGroupingCell {...params} />,
};
```

If it's better to open another ticket I will so.

Thank you & Best Regards
Yuki Yamashita

**Comment by michelengelen** [comment]
@Yuki-Yamashita-DTRA Are you intending to hide the grouping column from the columns management panel?

You can customize the list of columns following [this part of the docs](https://mui.com/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-columns-management).

**Comment by michelengelen** [comment]
No, tree data grouping columns don't have the column menu.
This is because the grouping column is autogenerated and should not hold meaningful values.

As the original question is resolved I will close this.
If you need help with others or want to open a feature request to allow for the column menu to show in auto generated columns feel free to open a feature request issue! 👍🏼

**Comment by Yuki-Yamashita-DTRA** [comment]
Hi michelengelen.
Thank you for the answering.
I understand above.
And now we have no more question about this.
Thank you.

Yuki Yamashita.
