### ISSUE TITLE
[tree view] Support for enabling checkboxes only for leaf nodes

### ISSUE THREAD

**Issue by Skykingeagle** [mui/mui-x#13586]
Reference: https://github.com/mui/mui-x/issues/12883

While the parent / children selection relationship works with the checkBoxSelectionProp

Would there be any way to restrict the checkboxes for only leaf nodes?

Add a restriction for checkboxes to only appear on leaf nodes 

**Search keywords**: 

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @Skykingeagle ... I'll add this to the board for the team to have a look!
I guess this could be possible, but I'd like the teams opinion on that first.

**Comment by flaviendelangle** [comment]
You can achieve this a custom `TreeItem` component, here is a [basic implementation](https://stackblitz.com/edit/react-hshxwt?file=Demo.tsx)

Let me know if this solves your problem

**Comment by michelengelen** [comment]
> @flaviendelangle thanks for the example! We're using it like that too, but really dislike the `any` escape hatch usage in `slotProps={{ checkbox: { visible: !status.expandable } as any }}`. Is there a chance to get this properly typed and maybe supported a bit more elegantly out of the box?
> 
> In case it helps with prioritisation: we're a paying customer, our latest order number is 💳 #84512.

Hey @TheRealCuran ... could you open up a new ticket for that? We try to separate and track individually to better plan and implement in small batches! Thank you! 👍🏼

**Comment by TheRealCuran** [comment]
@michelengelen see #15674 for the new ticket. Though I think we could have done this here? Less cluttering can be very helpful too, for finding issues again.
