### ISSUE TITLE
[data grid] DataGridPremium not working with actions column type

### ISSUE THREAD

**Issue by jordanlun1** [mui/mui-x#13607]
### Steps to reproduce

Link to live example: [DEMO](https://codesandbox.io/p/sandbox/datagridpremium-errors-with-action-buttons-2ix6pe?file=%2Fsrc%2FApp.js%3A14%2C23)

DataGridPro works, DataGridPremium does not work. In the example you can toggle between the two by 
Steps:
1. Toggling the commenting in and out, the stuff on lines 2 and 3
2. Alter line 14 (Premium or Pro)

You will find that DataGridPro displays a couple of buttons in an actions column, and DataGridPremium throws an error and doesn't render. 

### Current behavior

![image](https://github.com/mui/mui-x/assets/48939720/3e540938-30cc-4eec-b5fd-20543642244e)

### Expected behavior

Should render some buttons the same as what DataGridPro does.

### Context

Provide some buttons along the row for various actions. If should look like the attached image
![image](https://github.com/mui/mui-x/assets/48939720/d0324cdb-21d4-4dee-ab14-4fb735ac7cf7)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.63
    Edge: Chromium (126.0.2592.68)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.20
    @mui/icons-material: ^5.15.20 => 5.15.20
    @mui/material: ^5.15.20 => 5.15.20
    @mui/private-theming:  5.15.20
    @mui/styled-engine:  5.15.14
    @mui/system: ^5.15.20 => 5.15.20
    @mui/types:  7.2.14
    @mui/utils:  5.15.20
    @mui/x-data-grid:  7.7.1
    @mui/x-data-grid-premium: ^7.7.1 => 7.7.1
    @mui/x-data-grid-pro: ^7.7.1 => 7.7.1
    @mui/x-date-pickers:  7.7.1
    @mui/x-date-pickers-pro: ^7.7.1 => 7.7.1
    @mui/x-license: ^7.7.1 => 7.7.1
    @types/react:  18.2.45
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript:  4.9.5

</details>

**Search keywords**: DataGridPremium action column type getActions
**Order ID**: 90883

**Comment by michelengelen** [comment]
With the correct props it's working for me @jordanlun1 ... could you check this [DEMO](https://codesandbox.io/p/sandbox/datagridpremium-errors-with-action-buttons-forked-l4qfxz?file=%2Fsrc%2FApp.js%3A14%2C32) please

**Comment by jordanlun1** [comment]
ok so I just needed field prop for the column. Thanks @michelengelen
