### ISSUE TITLE
[data grid] `CssBaseline`, `Stack` and adding a Border to a DataGrid causes the DataGrid to Infinitely expand Vertically

### ISSUE THREAD

**Issue by bethmaloney** [mui/mui-x#13617]
### Steps to reproduce

Link to live example: [sandbox](https://codesandbox.io/p/sandbox/to-delete-forked-gc2nzv?file=%2Fsrc%2FApp.tsx)

Steps:
1. Add `<CssBaseline />`
2. Add a `<Stack />`
3. Style a DataGrid to add a border `"& .MuiDataGrid-main": { border: "1px solid #d9d9d9" }`
4. Add a `<Box />` below the DataGrid in the stack

### Current behavior

The DataGrid slowly expands downwards.

### Expected behavior

The DataGrid shouldn't expand

### Context

Want to use a stack to layout a DataGrid with some other information. Added a border as our design has a border around the table but not the action buttons above.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.56)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.20
    @mui/icons-material: ^5.15.20 => 5.15.20
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.20 => 5.15.20
    @mui/private-theming:  5.15.20
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.20
    @mui/types:  7.2.14
    @mui/utils:  5.15.20
    @mui/x-data-grid:  7.7.0
    @mui/x-data-grid-pro: ^7.7.0 => 7.7.0
    @mui/x-date-pickers:  7.7.0
    @mui/x-date-pickers-pro: ^7.7.0 => 7.7.0
    @mui/x-license: ^7.7.0 => 7.7.0
    @types/react: ^18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.5.2 => 5.5.2
```
</details>

**Search keywords**: datagrid infinite border
**Order ID**: 83676

**Comment by michelengelen** [comment]
I cannot reproduce this locally or in a build version!
This has to be specific to the environment.

One thing I could identify is that the `Filler` gets updated infinitely with a +1 px height. Might be related to the border being applied, since the jumps in height increase if you increase the border width.

I'll add this to the board for a deeper investigation!

CC @romgrk

**Comment by bethmaloney** [comment]
[mui-expanding-grid.zip](https://github.com/user-attachments/files/15980274/mui-expanding-grid.zip)

@michelengelen I've attached a vite project that demonstrates the issue in a prod build (for me at least).

```sh
npm i
npm run build
npm run preview
```

Note that if you remove <CssBaseline /> the issue goes away.

**Comment by romgrk** [comment]
Removing `border` fixes the issue. The datagrid needs full control of its layout & dimensions to operate properly, so we can't support adding borders in some locations because it modifies the layout of the grid. It's preferable to either modify existing borders' color (e.g. to remove a border, make it transparent), or add borders via CSS that doesn't modify the dimensions (e.g. using floating `::after` elements and adding borders on them). Would it be possible for you to use a different styling method?

**Comment by bethmaloney** [comment]
What we're trying to do is add a border to the table but not the GridToolbar

EG
![image](https://github.com/mui/mui-x/assets/42630535/6296dce8-8ab5-403d-9aee-151be648546f)

We're doing something similar to the below at the moment

```tsx
const StyledDataGrid = styled(DataGrid)(() => ({
  "& .MuiDataGrid-main": {
    border: "1px solid #d9d9d9",
  },
  border: "0",
}));

function App() {
  return (
    <>
      <CssBaseline />
      <Box height={600} width="500px" ml={10}>
        <StyledDataGrid
          rows={rows}
          columns={columns}
          slots={{
            toolbar: GridToolbar,
          }}
        />
      </Box>
    </>
  );
}
```

If there's a more appropriate way of accomplishing the above happy to change it.

**Comment by romgrk** [comment]
Are you familiar with pseudo-elements? You can use them [like this](https://stackoverflow.com/a/10166321/6303229) to create a border without affecting layout.

**Comment by bethmaloney** [comment]
Thanks! I'll try that and let you know how I go.

**Comment by bethmaloney** [comment]
I ended up using `outline` instead which doesn't affect the layout and that resolved the problem. Thanks for all your help!

If I could make a suggestion. Consider updating the styling section of the DataGrid docs to mention that styling changes that affect the layout aren't supported.
