### ISSUE TITLE
[charts] line chart tooltip hover issue

### ISSUE THREAD

**Issue by MainaMwangiy** [mui/mui-x#13615]
### Steps to reproduce

Link to live example: (required)

Steps: Check this link- https://stackblitz.com/edit/react-udtkt5?file=Demo.js

### Current behavior

Currently it it does not hover on one single point. it shows the same value all through on hover when the points are different and have different dates and values for the dates. 

### Expected behavior

I should be able to hover for a single point. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: line chart tooltip

**Comment by michelengelen** [comment]
Hey @MainaMwangiy 
Thanks for reaching out here.

@JCQuintas could you help with this?

**Comment by JCQuintas** [comment]
Hi @MainaMwangiy, it seems your setup is a bit different than what we expect, so it is causing issues when rendering. I don't know exactly how you want your chart to look, but there are potentially two ways to solve your issue.

1. Change your `categories` array to be ordered. The X axis `scaleType: 'time'` requires values in ascending/descending order. https://stackblitz.com/edit/react-udtkt5-dynxub?file=Demo.js

Alternatively

2. If your `categories` is in the correct order you want to display. You can change the X axis `scaleType` to `'band'` and it will display correctly. https://stackblitz.com/edit/react-udtkt5-wxlw6x?file=Demo.js

**Comment by MainaMwangiy** [comment]
Hi @JCQuintas for the two suggestions and link for the solutions. They have fixed my issue. It seems ordering my categories in ascending/descending order fixes the issue. Thanks
