### ISSUE TITLE
[charts] labels on YAxis have wrong position when direction is RTL on barchart and line chart

### ISSUE THREAD

**Issue by ma7899** [mui/mui-x#13613]
### Steps to reproduce

Steps to reproduce
Link to live example:
in the bar chart demo page.
https://mui.com/x/react-charts/bar-demo

Steps:

Set the direction of the settings to Right to Left

### Current behavior

The yAxis labels cover the the legend yAxis line and they have wrong position.
but the legends are behaving correctly.
![image](https://github.com/mui/mui-x/assets/44114647/5ab4fdda-8b28-4edd-add5-de6bf5875624)

### Expected behavior

The labels should be in the same position as they are in LTR. (just at the left of the yAxis)

### Context

I am trying to create a dashboard in a website which has a language that is RTL.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```System:
OS: Windows 11 10.0.22621
Binaries:
Node: v20.13.1
npm: 10.5.2
yarn: 1.22.22
Browsers:
Chrome
npmPackages:
@emotion/react": "^11.11.4,
@emotion/styled": "^11.11.5,
@mui/material": "^5.15.20,
@mui/styled-engine-sc": "^6.0.0-alpha.18,
@mui/x-charts": "^7.7.0,
@types/react: 18.2.48
react: ^18.2.0 => 18.2.0
react-dom: ^18.2.0 => 18.2.0
typescript: 4.9.5
```
</details>

**Search keywords**: RTL, labels, x-charts, bar chart, line chart, chart,=

**Comment by ma7899** [comment]
This also happens in line chart

**Comment by michelengelen** [comment]
@ma7899 thanks for raising this issue.
I'll add it to the board!

**Comment by alexfauquette** [comment]
The reason is that `<text />` components have a wrong `textAnchor` in RTL. I'm adding a PR to fix that

**Comment by Amir-A-M** [comment]
For those who ended up here, and are not using MUI, you can fix this RTL/LTR alignment issue by adding the following CSS:
```css
// RTL
.apexcharts-yaxis-label {
    text-anchor: start;
}

// LTR
html[dir=ltr] .apexcharts-yaxis-label {
    text-anchor: end;
}
```
