### ISSUE TITLE
[LineChart] Latest version prints React warnings

### ISSUE THREAD

**Issue by Janpot** [mui/mui-x#13611]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/billowing-fog-39pdzs?file=%2Fsrc%2FDemo.tsx

Steps:
1. Open the [example](https://codesandbox.io/p/sandbox/billowing-fog-39pdzs?file=%2Fsrc%2FDemo.tsx)
2. Check the console

### Current behavior

It prints 
```
Warning: Unknown event handler property `onAreaClick`. It will be ignored.
...
```

and

```
Warning: Unknown event handler property `onMarkClick`. It will be ignored.
...
```

### Expected behavior

No warnings printed

### Context

Discovered because it broke the Toolpad tests during last renovate upgrade cycle: https://app.circleci.com/pipelines/github/mui/mui-toolpad/15000/workflows/7cb28836-1265-47b2-838d-9dc1d8376bf5/jobs/69929?invite=true#step-106-25841_89

Would recommend setting up the tests to catch these warnings by default.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: onMarkClick

**Comment by Janpot** [comment]
Additionally, the [stackblitz](https://stackblitz.com/run?file=Demo.tsx) is broken for that [demo](https://mui.com/x/react-charts/line-demo/#simplelinechart).

**Comment by alexfauquette** [comment]
The error got fixed today in #13609

But I keep the issue open until we add the testing script

**Comment by si-saaref** [comment]
I'm still facing this error..
Is the bug already got fixed or not?

**Comment by alexfauquette** [comment]
The fxed version should be published during the day
