### ISSUE TITLE
[fields] on Android: deleting the date template is possible and breaks the component

### ISSUE THREAD

**Issue by shirRefundco** [mui/mui-x#13620]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Implement the DateField component 
2. Open the page in mobile - android only 
3. focus on the MM for example, and the use the backspace and delete the "MM" successfully 

### Current behavior

When trying to delete the "MM/DD/YYYY" template of the dateField component from an android mobile, it deletes the template

### Expected behavior

There is no way to delete the template "MM/DD/YYYY" of the component 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 11.3.1
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.114
    Edge: Not Found
    Safari: 14.1

```
</details>

**Search keywords**: DateField Mobile

**Comment by michelengelen** [comment]
@LukasTy I don't have an android device at hand. Do you?

**Comment by LukasTy** [comment]
@shirRefundco Thank you for reporting this problem! 🙏 
It looks like a regression as this isn't happening on v6.

https://github.com/mui/mui-x/assets/4941090/aa9b5673-60de-49c3-80ea-3f839e257ec9

**Comment by LukasTy** [comment]
Android seems to be undecided as to what it should do with `Backspace` button. 🙈 
Given a numeric keyboard, it fires an event with the `key` of `Backspace`, but given a letter section—the `key` `Unidentified`.
This is related to https://github.com/mui/mui-x/issues/10399.
I'm looking into this problem further.
