### ISSUE TITLE
[data grid] How to get the total row count including children rows

### ISSUE THREAD

**Issue by dassoumyashree** [mui/mui-x#13638]
### The problem in depth

I am using the row grouping feature with mui premium. By default, the total row count is calculated based on a number of parent rows (top-level rows). I need a way to set the page row count based on the number of child rows. Is there any way to do that?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Page count to be set as number of child rows with row grouping

**Comment by DanailH** [comment]
Hi @dassoumyashree you can use the `getRowsCount()` API method from the `useGridApiRef()` hook to get the total number of rows. You can find more about it here: https://mui.com/x/api/data-grid/grid-api/#grid-api-prop-getRowsCount

This will work if your rows are all loaded. If you use a server-side loading strategy then you would need to use the `estimatedRowCount` method to pass in the row count. You can find more about it here: https://mui.com/x/api/data-grid/data-grid-premium/#data-grid-premium-prop-estimatedRowCount

**Comment by KenanYusuf** [comment]
After discussing with @DanailH, I am going to re-open this issue as we discovered that `getRowsCount()` does not update when rows are filtered. 

@dassoumyashree I am working on a recipe to help with this question, should have something to share soon.
