### ISSUE TITLE
[data grid] Can't scroll to end of dataset fast with paginationModel='server'

### ISSUE THREAD

**Issue by teddis** [mui/mui-x#13635]
I'm using DataGridPro and was loading the entire dataset up to 30-40K rows. Once loaded, one can scroll fast and effortlessly from the start to the end of the dataset leveraging the browser cache.

However, this is extremely slow in a production environment and was forced to switch to infinite scroll with server-side pagination, using RTK query API to fetch pages. The problem is now that while one can infinitely scroll, the scrollbar is constrained to the the currently loaded pages and a bit to scroll to the next page. I specify the rowCount to the actual total length of the data, but the scrollbar doesn't reduce to allow one to scroll quickly to the end or in-between. Must I also now include a pager to navigate through the entire set? Is it possible to achieve the desired behavior I've described?

**Search keywords**: 

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @teddis this should definitely be achievable.
@MBilalShafi could you take a look here please?

**Comment by teddis** [comment]
> Hey @teddis this should definitely be achievable.
> @MBilalShafi could you take a look here please?

Awesome. How?

**Comment by MBilalShafi** [comment]
Hey @teddis,

I think your request aligns more with the [row lazy-loading](https://mui.com/x/react-data-grid/row-updates/#lazy-loading) rather than [infinite loading](https://mui.com/x/react-data-grid/row-updates/#infinite-loading). 
The basic difference between lazy and infinite loading is the `rowCount` known and unknown. 
In the case of lazy-loading, since the row count is known, we can calculate the scroll height and render the full page due to which a user can scroll to any given subset of data that will be loaded lazily.

Have you been able to give a try to the lazy loading?

**Comment by teddis** [comment]
Yes thank you, lazy loading was the solution!

**Comment by teddis** [comment]
@MBilalShafi 

I'm running into some problems getting lazy loading to work flawlessly. I'm just going by this example code and doc: https://mui.com/x/react-data-grid/row-updates/#lazy-loading. Undoubtedly my problem is due to still being a React novice.

1. I'm seeing multiple duplicate identical requests to fetch rows, so there's some dependency issue going on here. I'm using debounce, so I'm still not sure what's wrong.
2. Filter and sort aren't working perfectly yet. Sometimes they work, but if there are no rows returned, the DataGrid gets into a state where canceling or clearly the sort/filter does not reset the DataGrid and subsequently fetches 0 rows. I have to remount the component to restart its use.
3. I'm seeing some replacement row id conflicts. I thought that I should clear rows when receiving onFilterChange and onSortChange events to avoid this, but I'm still seeing them. Should I just ignore for now with a try/catch?
4. Are there any robust examples or tutorials about how lazy loading works internally?
5. Is Lazy Loading unstable or still under development?

Behind the gun, hoping to release ASAP, but delays delays. :-) 

Thank you for your help.

**Comment by teddis** [comment]
No worries. I couldn't get the smooth reliable UX I was hoping for with lazy loading, so I opted to find a way just to load the entire 10MB dataset locally into the grid to avoid lazy loading etc entirely.
