### ISSUE TITLE
[data grid] changing data is slow

### ISSUE THREAD

**Issue by yoshrat** [mui/mui-x#13642]
### The problem in depth

My use case includes displaying a data table that in some cases should change it data ~10-30 times a second.
The data correspond to a video and when the video is played I want to dispaly the correct data for each frame.
I might have multiple such tables on screen each time.
My measurements shows that it takes 6-8 milli seconds, This cause my scenario to be unfeasible. 
The data itself is usually quite small, 

Is there a make updating data in DataGrid faster. maybe disabling some of the features and enabling them only when I pause the playing mode?

### Your environment

  System:
    OS: Windows 11 10.0.22000
  Binaries:
    Node: 22.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.6.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.2600.0), Chromium (126.0.2592.68)
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1
    @emotion/styled: 11.11.0 => 11.11.0
    @mui/base: ^5.0.0-alpha.127 => 5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.20
    @mui/icons-material: ^5.3.1 => 5.15.20
    @mui/lab: ^5.0.0-alpha.72 => 5.0.0-alpha.170
    @mui/material: ^5.14.5 => 5.15.20
    @mui/private-theming:  5.15.20
    @mui/styled-engine:  5.15.14
    @mui/styles:  5.15.20
    @mui/system:  5.15.20
    @mui/types:  7.2.14
    @mui/utils:  5.15.20
    @mui/x-data-grid:  6.20.1
    @mui/x-data-grid-premium: ^6.18.3 => 6.20.1
    @mui/x-data-grid-pro:  6.20.1
    @mui/x-license-pro: ^6.10.2 => 6.10.2
    @types/react: ^17.0.2 => 17.0.80
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: 5.2.2 => 5.2.2

**Search keywords**: performance, time,
**Order ID**: 78446

**Comment by KenanYusuf** [comment]
Hi @yoshrat

A couple of questions about your use case:
1. Which features of the data grid are you using? If you are only using it to display basic tabular data, the [Material UI Table](https://mui.com/material-ui/react-table/) may give you better results. If you need data grid functionality, can you provide a code sample or basic demo of how you are using the table?
4. Should the user actually see a change in the table 10-30 times a second? If not, you might benefit from throttling. See the [high frequency docs](https://mui.com/x/react-data-grid/row-updates/#high-frequency) for more information.
