### ISSUE TITLE
[charts] How to add min and max scaling on axis for bar charts to remove decimal scale values

### ISSUE THREAD

**Issue by MainaMwangiy** [mui/mui-x#13641]
### Steps to reproduce

Link to live example: (required)

Steps Check this link for the issue https://stackblitz.com/edit/react-k3t8s4?file=Demo.js

### Current behavior

Currently, having the scales if the value is 1, then the rest of the scales by default will have decimal scales. 
![image](https://github.com/mui/mui-x/assets/38659056/b6c45e58-2fce-48d3-9112-c1f6efe7d2a4)

### Expected behavior

Should have a `min` and `max` property for the scale or have a property for `decimal:  false` They are instances where the data you have cannot have decimals scales. 

### Context

My issue is really not related to https://github.com/mui/mui-x/issues/12083. I would like either have a min and max to set the min scale we have or max for the maximum to have. 

Alternatively, have a property for decimal = false when we don't the scale to have decimal scale values. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: axis bar charts scaling

**Comment by JCQuintas** [comment]
Hi @MainaMwangiy thanks for reaching out. To control the steps between each tick, you can use 

```tsx
        xAxis={[
          {
            tickMinStep: 1,
          },
        ]}
```

https://stackblitz.com/edit/react-k3t8s4-lpjhxp?file=Demo.js

**Comment by MainaMwangiy** [comment]
Thanks @JCQuintas That fixes my issue.
