### ISSUE TITLE
[DataGridPro] & .MuiDataGrid-columnHeaders is not working with @mui/x-data-grid-pro": ^7.1.1

### ISSUE THREAD

**Issue by SantyTaco** [mui/mui-x#13640]
### Steps to reproduce

Link to live example: (required)
This is the link to the live example: https://codesandbox.io/p/sandbox/amazing-leaf-5jp3sj

Steps:
1. Starting a react project
2. Downloading Mui Data grid pro
3. Trying to modify the column header background color
 sx={{
          "& .MuiDataGrid-columnHeaders": {
            background: "black",
            color: "white",
          },
        }}

### Current behavior

After add the sx style 
sx={{
          "& .MuiDataGrid-columnHeaders": {
            background: "black",
            color: "white",
          },
        }}
The grid columns header are not taking the color assigned

### Expected behavior

I expect the column header background color change to black.

### Context

Currently, in production env I am using "@mui/x-data-grid-pro": "^6.19.1" library and the style is working well, and the header column background color is black, but I have updated the library to @mui/x-data-grid-pro": ^7.1.1 and the background color is white even I have tried to change it in multiple ways.

Pic in prod:
<img width="1264" alt="Screenshot 2024-06-26 at 1 05 42 PM" src="https://github.com/mui/material-ui/assets/38363806/dd03d117-bf47-4ac6-8e18-1b602158425e">

Pic in dev:
<img width="1273" alt="Screenshot 2024-06-26 at 1 06 50 PM" src="https://github.com/mui/material-ui/assets/38363806/a1afa961-3987-448c-8dfe-d10f8f7dafbc">

Is possible to change the column header background color in the new version of data grid pro?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

This is my env info and I use Google Chrome
 System:
    OS: macOS 14.4
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.126
    Edge: Not Found
    Safari: 17.4
  npmPackages:
    typescript:  5.3.3 

**Search keywords**: & .MuiDataGrid-columnHeaders is not working

**Search keywords**:

**Comment by maramizo** [comment]
Not a solution, but a workaround can be using `.MuiDataGrid-columnHeader` instead.

**Comment by KenanYusuf** [comment]
Hi @SantyTaco,

You can set the column header background color via your theme:

```tsx
import { createTheme } from '@mui/material/styles';

const theme = createTheme({
  mixins: {
    MuiDataGrid: {
      // Headers, and top & bottom fixed rows
      containerBackground: '#343434',
    },
  },
});
```

See the documentation for more details https://mui.com/x/react-data-grid/style/#theme-header-and-pinned-sections

Hopefully this solves your issue, please let me know if you have any further questions on it.

**Comment by SantyTaco** [comment]
> Not a solution, but a workaround can be using `.MuiDataGrid-columnHeader` instead.

It works, thank you so much

**Comment by dipanshu914** [comment]
> Not a solution, but a workaround can be using `.MuiDataGrid-columnHeader` instead.

Thanks for providing this info , after my try finally this solution is work to change my Datagrid columns Header background color

- "& .MuiDataGrid-columnHeader": {
                        background: "red"
                    }
