### ISSUE TITLE
[data grid]: there is an issue with the design on the right side when dragging 

### ISSUE THREAD

**Issue by WhiteWolf-js** [mui/mui-x#13649]
### Steps to reproduce

Link to live example: (required)
action:dragging the last header column, the right design seems not fit
mine:![image](https://github.com/mui/mui-x/assets/83862709/92d9df55-7f1e-43b1-83f1-c33ded251e24)
official docs:
![image](https://github.com/mui/mui-x/assets/83862709/f06539f9-4a29-469d-aea7-32130745e82e)

### Your environment

https://codesandbox.io/s/3rt8ps?file=/src/Demo.tsx

**Search keywords**: drag

**Comment by romgrk** [comment]
I can't reproduce, could you clarify the reproduction steps?

**Comment by WhiteWolf-js** [comment]
![image](https://github.com/mui/mui-x/assets/83862709/ca56c56d-3867-4670-be61-e0b966d45aff)
What I mean is that the grid on the right side of the diagram box will disappear

**Comment by romgrk** [comment]
Please explicitly describe the steps you take to end at that state, or include a video demonstration.
