### ISSUE TITLE
[charts] Improve docs about how to pick the correct scaleType

### ISSUE THREAD

**Issue by CzarOfScripts** [mui/mui-x#13658]
### Steps to reproduce

Link to live example: [codesandbox.io](https://codesandbox.io/p/sandbox/graph-axis-name-pdk5gq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxyclvjy0006356ncbd4wkrq%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxyclvjy0002356nsm5xnurj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxyclvjy0003356n3b8r54ba%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxyclvjy0005356nljkbt9r1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxyclvjy0002356nsm5xnurj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxyclvjy0001356n39zmsbcu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clxyclvjy0002356nsm5xnurj%2522%252C%2522activeTabId%2522%253A%2522clxyclvjy0001356n39zmsbcu%2522%257D%252C%2522clxyclvjy0005356nljkbt9r1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxyclvjy0004356nitztyhhq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxyclvjy0005356nljkbt9r1%2522%252C%2522activeTabId%2522%253A%2522clxyclvjy0004356nitztyhhq%2522%257D%252C%2522clxyclvjy0003356n3b8r54ba%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxyclvjy0003356n3b8r54ba%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Set dataset 
2. Configure series 
3. Specify datakey for axies 
4. Specify different data for yAxis

### Current behavior

I apologize for the English, I use a translator and in general I don't really understand how to correctly formulate the problem and its solution, but after watching the demonstration I think the problem and what I was trying to achieve will be clear.

My task is to make custom Labels for yAxis, and the problem is that I can't create a point that will be between two "labels", i.e. there is a label "Mid Developer" which has a value of "300" and there is a "Senior Developer" which has a value of "600". If I want to create a point that has the value "350" (i.e. between the two labels), the point will simply not be drawn and the chart will break (the points will not connect).

In the variant where we do not specify explicitly (or specify all that we can have) what values will be in `data` for yAxis, then there is a separate "tick" for this value, which would not be desirable.

### Expected behavior

I wanted the point to be placed in between the "tick" without creating a new "tick" for itself.

### Context

I wanted the point to be placed in between the "tick" without creating a new "tick" for itself.

### Your environment

I'm use Google Chrome (126.0.6478.127)

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 21.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.81)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.19
    @mui/icons-material: ^5.15.19 => 5.15.19
    @mui/material: ^5.15.19 => 5.15.19
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-charts: ^7.6.1 => 7.6.1
    @mui/x-date-pickers: ^7.7.0 => 7.7.0
    @types/react: ^18.2.66 => 18.2.78
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.4.5
```
</details>

**Search keywords**: I'm sorry, it's hard for me to articulate the problem

**Comment by CzarOfScripts** [comment]
Component: LineChart

**Comment by alexfauquette** [comment]
Here is the solution: https://codesandbox.io/p/sandbox/graph-axis-name-forked-2ccmkc?file=%2Fsrc%2FApp.tsx%3A162%2C13

## 1. pick the correct scale

`scaleType: 'point'` is here for the case you have categories (you know your data will be in categories and **never** outside).

You need to accept any king of number. Then I would recommend to use the default scale (`scaleType: 'linear'`) you can simply do not specify a scale since it's the default one.

![image](https://github.com/mui/mui-x/assets/45398769/13ac2534-ee03-4625-a66d-b40e30480303)

## 2. fix the ticks

Now the axis is doing its best to show meaning full ticks. Since it goes from 0 to 1200 it is proposing 0, 200, 400, 600, 800, 1000, 1200.

But we have labels for 100, 300, 600, 800, 1000, 1200.

The solution is to specify in the axis definition `tickLabel={[ 100, 300, 600, 800, 1000, 1200 ]}` which forces the tick to be displayed at those values.

If that does solves your issue, please consider closing it

**Comment by CzarOfScripts** [comment]
@alexfauquette, Oh, thank you very much! I have some more questions though, why the line `axisHighlight={{ x: "none", y: "line" }}` is not drawn correctly for the points? Is it some kind of bug?

Is there any way to increase the distance between the "tickLabel"? I got it like this (the first and the second are quite close to each other):

![image](https://github.com/mui/mui-x/assets/78804737/0bdcd6f9-d9d9-4c35-914b-72b6acedba0c)

**Comment by alexfauquette** [comment]
> Ideally, I'd like to have equal distance between "tickLabel" despite the difference in values. This should work:

That does not sound feasible. Do have that you would need to create your own weird scale type. Where you can end up with moving for 0 to 100px represent an increase of 50, and moving from 100px to 200pc represent an increase of 236

You have two standard alternatives:

If the data does not represent something linear you can try the `'log'` or `'sqrt'` [scale type](https://mui.com/x/react-charts/axis/#axis-data)

The other option is to display all the tick and show labels only on the meaning full one




----
> `axisHighlight={{ x: "none", y: "line" }}` is not drawn correctly for the points

Your y-axis probably still have a `dataKey` and/or `data` property. The highlight will then only be visible for those values

**Comment by CzarOfScripts** [comment]
> If the data does not represent something linear you can try the `'log'` or `'sqrt'` [scale type](https://mui.com/x/react-charts/axis/#axis-data)

With `log` all the points moved to the upper left corner, and with `sqrt` it got even worse. Okay then, if it can't be fixed so easily, I'll have to leave it like that.


> Your y-axis probably still have a `dataKey` and/or `data` property. The highlight will then only be visible for those values

Yes, my axis has `dataKey="value"`, I removed that and now this line moves freely behind the cursor but is not "magnetic" to points. Is it possible to show it when hovering over any point?

**Comment by alexfauquette** [comment]
> Is it possible to show it when hovering over any point?

 Not for now. Those highlight lines are here to show axis values, and not points.
 
 To do it, you will probably need to use `useHighlighted` to know if an item is highlighted, and then render a custom line at this value
