### ISSUE TITLE
Leap year data grid date column filter cant be filled from left to right

### ISSUE THREAD

**Issue by BlastyCZ** [mui/mui-x#13654]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Live in country (Czechia) which used dd. mm. yyyy format for dates e.g. today is 28. 6. 2024
2. Try to filter by leap year date e.g. 29. 2. 2024

### Current behavior

It resets input

### Expected behavior

Filling desired date

### Context

I tried to filter by leap year date e.g. 2024/02/29

### Your environment

Development: Linux (Fedora) - Firefox 127.0.2
Production: Windows - Firefox 115.11.0esr

**Search keywords**: Leap year data grid

**Comment by MBilalShafi** [comment]
Hey @BlastyCZ,

I tried to filter by the mentioned date and it works fine for me in this [demo](https://mui.com/x/react-data-grid/#pro-plan).
![image](https://github.com/mui/mui-x/assets/12609561/50da518a-f26a-4c84-b0e7-885b1eb32f44)


Could you provide a reproduction using the latest product version? A live example would be fantastic! ✨

You can refer to our documentation that offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

**Comment by BlastyCZ** [comment]
I tried this demo before I posted issue. Bug occurs for me. 
I tried chromium - it works ok! **Firefox** is not.

Let me clearly describe all my steps:
1. Open the filter window
![image](https://github.com/mui/mui-x/assets/52929675/2b2d43dd-7910-47ea-983e-fda12f36fe73)
2. Fill day and month
![image](https://github.com/mui/mui-x/assets/52929675/1fb75328-25cd-47e4-a295-40cbacde59bc)
3. Fill first two number from year 2024
![image](https://github.com/mui/mui-x/assets/52929675/05ce68cb-d568-4e09-80e2-c349c2ca28e9)
4. Add third number of 2024 - after pressing 2, date is reset to clear state for no obvious reason
![image](https://github.com/mui/mui-x/assets/52929675/ae90e639-1737-4b4a-8f62-6a1039439c70)

**Comment by KenanYusuf** [comment]
@BlastyCZ please provide your environment details as part of the issue description - you mentioned the issue is occurring in Firefox, the version number and operating system are also important. Thank you!

**Comment by BlastyCZ** [comment]
I've added a description of the environment. I didn't expect it to be a browser-specific bug in the first place. The last version of DataGrid I tried is "7.8.0". The bug is still occurring.

**Comment by MBilalShafi** [comment]
Thank you @BlastyCZ for providing the reproduction steps and environment information. I can reproduce it on Firefox 127.0 on MacOS.

It seems to be an [issue](https://github.com/facebook/react/issues/26175) with Firefox itself though as you can observe in this codesandbox the similar behavior without using the Data Grid: https://codesandbox.io/p/sandbox/cold-dawn-ksmgb4

I am not sure if we can do anything on our side.
