### ISSUE TITLE
[fields] "Format" is still being used as MobileDatePicker input value, even after the dialog is closed

### ISSUE THREAD

**Issue by ignatiusreza** [mui/mui-x#13679]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/sad-firefly-c5ptqr?file=/src/Demo.js

Steps:
1. Click to open date picker dialog
2. Select on today's date
3. Click OK --> noticed that date picker value is updated correctly
4. Click a 2nd time to open date picker dialog
5. Click on "Clear" --> noticed that date picker value is mistakenly set to the string given as "format"

### Current behavior

Date picker input "value" is set to "format".

### Expected behavior

Date picker input "value" should be "null" (blank)

Alternatively, for `MobileDatePicker` (and `MobileDateTimePicker`), it might not be necessary for placeholder to be assigned as value when the input is focused. Since the expectation is for the user to pick the date (& time) via the date picker dialog.

### Context

We customized the default date picker actionbar, to enable user to "Clear" current value of the datepicker.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Reproducible in code sandbox, browser: Chrome.
</details>

**Search keywords**: datepicker format placeholder

**Comment by LukasTy** [comment]
@ignatiusreza Thank you for opening this issue.
The behavior indeed looks strange.
The different behavior of the `readOnly` flag, which is set on Mobile Pickers, causes this issue.

We'll look into this issue. 👍
