### ISSUE TITLE
Y Axis Min/Max value breaks formatting

### ISSUE THREAD

**Issue by josh-thompson13** [mui/mui-x#13680]
### The problem in depth

I can not add min/max attribute to my chart because I'm doing formatting. Is there a workaround?

`<LineChart
  width={500}
  height={300}
  series={[
    { data: pData, label: 'pv' },
    { data: uData, label: 'uv' },
  ]}
  xAxis={[{ scaleType: 'point', data: xLabels }]}
   yAxis={[{ min: 10, max: 10000 },{ valueFormatter: value => `${"$"?? ""}${value}${"K" ?? ""}` },
                            ]}
/>`

This chart will add the min/max but ignore the formatting.

NOTE: This next snippet of code demonstrated that if the format logic is added before the min/max logic, the chart ignores the min/max and keeps the formatting.

`<LineChart
  width={500}
  height={300}
  series={[
    { data: pData, label: 'pv' },
    { data: uData, label: 'uv' },
  ]}
  xAxis={[{ scaleType: 'point', data: xLabels }]}
   yAxis={[{ valueFormatter: value => `${"$"?? ""}${value}${"K" ?? ""}` }, { min: 10, max: 10000 },
                            ]}
/>`

### Your environment

Unlikely this will be necessary.

**Search keywords**: Min breaks format
**Order ID**: 1f5414cfd0e0c2e672b575010c5b1c1bTz05MTkzMixFPTE3NDkxODQxMDIwMDAsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI=

**Comment by alexfauquette** [comment]
Because you declare 2 axis

```jsx
<LineChart
  // ...
  yAxis={[
    { min: 10, max: 10000 }, // Axis 1 (the one used by default) with min/max
    { valueFormatter: value => ${"$"?? ""}${value}${"K" ?? ""} }, // Axis 2 with formatter not used by your chart
]} />
```

It should be something like

```jsx
<LineChart
  // ...
  yAxis={[
    { min: 10, max: 10000, valueFormatter: value => ${"$"?? ""}${value}${"K" ?? ""} }
]} />
```

**Comment by michelengelen** [comment]
@josh-thompson13 you are copying the license key every time you open an issue. Please use your order ID (91932) instead to prevent your license key from being stolen. Thanks!

**Comment by josh-thompson13** [comment]
> @josh-thompson13 you are copying the license key every time you open an issue. Please use your order ID (91932) instead to prevent your license key from being stolen. Thanks!

You might want to remove this comment then as people can see the edit history.
