### ISSUE TITLE
[tree view] failed to excute "querySelectorAll" on "Element"

### ISSUE THREAD

**Issue by spadeACE7** [mui/mui-x#13686]
### Steps to reproduce

failed to excute "querySelectorAll" on "Element": '[role="treeitem"]:not(*[id=":r0:"] [role="treeitem"] [role="treeitem"])'

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: SimpleTreeView

**Comment by noraleonte** [comment]
hey @spadeACE7 👋 
Could you please provide more information for what you are trying to achieve? A reproduction case in codesandbox or stackblitz  would also be really helpful 🙏

**Comment by jonnygong** [comment]
Same issue, reports in chrome, but not in edge
