### ISSUE TITLE
DataGrid ColumnHeader Border Changed from v6 to v7

### ISSUE THREAD

**Issue by avalyons-wk** [mui/mui-x#13694]
### Steps to reproduce

Link to live example: 
v7 example: https://codesandbox.io/s/dfntjc?file=/src/Demo.tsx
v6 example: https://codesandbox.io/s/9vpynd?file=/src/Demo.tsx

Steps:
1. Open the link
2. Look at the difference of the columnHeader border of each example

### Current behavior

v6's DataGrid columnHeaders had a border that was around every edge of the cell. v7 has a border that touches the sides and the top of the cell. 

### Expected behavior

There either should be a border around the whole cell for a columnHeader for v7 or documentation of the change of the border.

### Context

There was no documentation of this change from v6 to v7 for the columnHeader border changing. Is this an expected change?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.6.3
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.127

```
</details>

**Search keywords**: DataGrid Column Header

**Search keywords**:

**Comment by avalyons-wk** [comment]
<img width="216" alt="v6" src="https://github.com/mui/mui-x/assets/105390002/11549fd3-2c83-460f-b82b-b16b6b02b0a2">
<img width="230" alt="v7" src="https://github.com/mui/mui-x/assets/105390002/6e60f7c2-e13b-464c-be8d-52dae634783e">
v7's border doesn't have the bottom part to it.

**Comment by KenanYusuf** [comment]
Thanks for reporting the issue @avalyons-wk, there are a few glitches related to the focus outline on column headers that we are aware of. This one specifically is also noted on this issue: https://github.com/mui/mui-x/issues/11225

I will close this issue for now, and we can prioritise and track the progress of this on the other issue.
