### ISSUE TITLE
Grouping Columns in @mui/x-data-grid-pro Not working

### ISSUE THREAD

**Issue by muhammadusman619** [mui/mui-x#13706]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Current behavior

Data grid Pro is unable to work with the Columns grouping feature.

However its working in the MUI Data Grid version.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Grouping Columns

**Comment by KenanYusuf** [comment]
@muhammadusman619 please can you provide a reproduction of the issue you are seeing? You can use [our template](https://githubbox.com/mui/mui-x/tree/master/bug-reproductions/x-data-grid) to do this in CodeSandbox.

**Comment by muhammadusman619** [comment]
@KenanYusuf this is present in data grid pro i want to use, please let me know how to achieve this in data grid pro version

**Comment by KenanYusuf** [comment]
@muhammadusman619 You can see the column grouping documentation here https://mui.com/x/react-data-grid/column-groups/ for details on how to use the feature. Anywhere in the code examples you see the `DataGrid` component, you can replace with the `DataGridPro` component and it will work the same.
