### ISSUE TITLE
How do I stop the grid from issuing double fetchRows calls?

### ISSUE THREAD

**Issue by teddis** [mui/mui-x#13709]
### The problem in depth

I've converted to using Lazy Loading. Quite often the grid fetches rows twice which creates a flicker and delay for the user that badly slows down their workflow. I'm not sure how to debug this.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Chrome 
  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.18 
    @mui/icons-material:  5.15.18 
    @mui/lab:  5.0.0-alpha.170 
    @mui/material:  5.15.18 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.6.1 
    @mui/x-data-grid-pro:  7.6.1 
    @mui/x-license:  7.6.1 
    @mui/x-tree-view:  6.17.0 
    @types/react:  18.2.74 
    react:  18.3.1 
    react-dom:  18.3.1 
    typescript: ^5.5.2 => 5.5.2 
```
</details>

**Search keywords**: lazy loading fetchrows
**Order ID**: 91768

**Comment by romgrk** [comment]
Could you provide a [bug reproduction case](https://mui.com/material-ui/getting-started/support/#bug-reproductions)? You can fork any demo from the docs or paste your own code in [our template](https://githubbox.com/mui/mui-x/tree/master/bug-reproductions/x-data-grid).
