### ISSUE TITLE
Multiple checkbox selection restriction in @mui/x-data-grid-pro

### ISSUE THREAD

**Issue by muhammadusman619** [mui/mui-x#13705]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Multiple checkbox

**Comment by KenanYusuf** [comment]
@muhammadusman619 please can you fill out the issue description?

**Comment by muhammadusman619** [comment]
The issue is that i am using mui/x-data-grid-pro, and i want to use checkboxes to select rows based on the selection, now i have a usecase where i want to restrict to only one row selected on checkbox selection. the latest check should be considers and others should be unchecked.

**Comment by muhammadusman619** [comment]
This issue is present in data grid pro, and i want to use this feature in Pro version not this one.

**Comment by KenanYusuf** [comment]
@muhammadusman619 here is an example of the `disableMultipleRowSelection` being used on `DataGridPro`. https://codesandbox.io/p/sandbox/nice-easley-g26h6d

If you're still seeing an issue with this feature, please feel free to re-open this issue with a working reproduction example (you can fork the CodeSandbox above as a starter).

**Comment by muhammadusman619** [comment]
its not working in my case, should i share you the code here?

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
