### ISSUE TITLE
[data grid] QuickSearchToolbar loses focus for bad user experience

### ISSUE THREAD

**Issue by teddis** [mui/mui-x#13708]
### Steps to reproduce

Link to live example: (required)

I appreciate your requirement here but my connection data is private so I cannot expose it to the public. Setting someone up is a non-trivial process for a tester. I can spend time building a test case, but let me explain first what the problem is. Maybe it's easy to address?

Steps:
1. Use DataGridPro (am licensed)
2. Have a dataset 2,000-30,000 rows
3. Start typing in the QuickSearchToolbar

### Current behavior

I'm using lazy loading to better handle display of up to 30,000 user connections via Google Cloud SQL (Postgres). The problem is that QuickSearchToolbar has a debounce of 150ms that triggers an automatic search which can be slow. The focus is immediately lost so the user cannot complete entering his search criteria, and has to wait for the search to complete and click back in the search box to try to complete entering fast enough before the next debounce occurs. 
This wastes valuable time and make the experience frustrating to the point of uselessness.

### Expected behavior

Turn off automatic search and debounce. Do not trigger search automatically. Wait for the user to hit return to trigger searches. 

### Context

We use a DataGrid to display a user's LinkedIn connections (1 to 30,000). We want to make it possible for the user to _rapidly_ search and browse for people to apply desired configurations.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Chrome
System:
    OS: macOS 14.5
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.18 
    @mui/icons-material:  5.15.18 
    @mui/lab:  5.0.0-alpha.170 
    @mui/material:  5.15.18 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.6.1 
    @mui/x-data-grid-pro:  7.6.1 
    @mui/x-license:  7.6.1 
    @mui/x-tree-view:  6.17.0 
    @types/react:  18.2.74 
    react:  18.3.1 
    react-dom:  18.3.1 
    typescript: ^5.5.2 => 5.5.2 
```
</details>

**Search keywords**: QuickSearchToolbar

**Comment by arminmeh** [comment]
@teddis can you provide a code snippet that shows the props you are passing to the grid and the filter component (if you are using slot to customize it)?

**Comment by teddis** [comment]
Fortunately, I'm able to load entire user datasets into the client DataGrid for the best UX. This issue doesn't occur in this case (not infinite scrolling or lazy loading).
