### ISSUE TITLE
[data grid] Copy and Paste content from origin column cell selection to an another column doesn't maintain the sorting set 

### ISSUE THREAD

**Issue by rockmsc92** [mui/mui-x#13703]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/devbox/lck95j?file=%2Fsrc%2FDemo.tsx

Steps.
1. **SELECT all the cells** from code column and COPY it 
2. **SELECT all the cells** from content pasted column
3.  **PASTE** the copied content (you can see it into alert)

![bug_data_grid_premium_pasted_not_sorted](https://github.com/mui/material-ui/assets/160520008/24b7db7b-e50a-41f1-b9b2-183be8138108)

### Current behavior

The copy of cell values does not respect the order of values from origin column.

### Expected behavior

The copy of cell values mantains the order of values from origin column.

### Context

I'm copying the data from column to an other one.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: clipboard copy and paste data grid premium

**Search keywords**:

**Comment by KenanYusuf** [comment]
Thanks for the clear example and reproduction steps @rockmsc92.

Looks like it works as expected if you try and paste in the first cell, but not if you select all of the cells.

https://github.com/mui/mui-x/assets/9557798/2dae3fb7-bd9e-444e-adf4-1e52538693f3

**Comment by michelengelen** [comment]
@romgrk could you have a look at this please?
