### ISSUE TITLE
[charts] Axis Highlight on horizontal bar charts can't be band. It used to exist in v7.6.2. 

### ISSUE THREAD

**Issue by kalaounmohamad** [mui/mui-x#13704]
### Steps to reproduce

Link to live example: (https://mui.com/x/react-charts/bars/#bar-direction)

Steps:
1. There's no hover effect on the horizontal bar chart anymore

### Current behavior

https://mui.com/x/react-charts/bars/#bar-direction
Try to hover here

### Expected behavior

https://v6.mui.com/x/react-charts/bars/#layout
This is the hover that I had on v7.6.2 and I could customize it by modifiying the css of .css-1h2zijw-MuiChartsAxisHighlight-root

### Context

I want to be able to have a hover effect and customize it like a cursor pointer

### Your environment

I used Microsoft Edge.

System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.81)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.21
    @mui/docs: ^5.15.19 => 5.15.21
    @mui/icons-material: ^5.15.19 => 5.15.21
    @mui/material: ^5.15.19 => 5.15.21
    @mui/private-theming:  5.15.20
    @mui/styled-engine:  5.15.14
    @mui/styled-engine-sc: ^6.0.0-alpha.18 => 6.0.0-alpha.18
    @mui/system:  5.15.20
    @mui/types:  7.2.14
    @mui/utils:  5.15.20
    @mui/x-charts: ^7.6.2 => 7.8.0
    @mui/x-data-grid: ^7.6.2 => 7.8.0
    @types/react: ^18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    styled-components: ^6.1.11 => 6.1.11
    typescript: ^4.9.5 => 4.9.5

**Search keywords**: axis highlight, horizontal bar chart

**Comment by JCQuintas** [comment]
Indeed a regression, thanks for reporting 🙇
