### ISSUE TITLE
[data grid] Undefined property of `computedWidth` when toggling `checkboxSelection`

### ISSUE THREAD

**Issue by naimezeqiri** [mui/mui-x#13719]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-muktdz?file=Demo.tsx

### Current behavior

We have a data grid with two modes, one of the mode uses checkbox and the other does not. If we are in the mode with the checkboxes, scroll inside the grid, and then quickly switch to the mode without checkboxes, an error is thrown. The error indicates an undefined property of computedWidth. The issue occurs when these steps are performed quickly.

Steps:

- Create a button that toggles `checkboxSelection` between true and false.
- Navigate to dataGrid where checkboxSelection is true.
- Scroll through the DataGrid from top to bottom.
- Attempt to switch the `checkboxSelection` prop from true to false through the Button click.

![Screenshot 2024-07-03 at 13 48 32](https://github.com/mui/mui-x/assets/153606579/4dcf4f71-9b51-4139-81eb-018769319028)

![Screenshot 2024-06-27 at 12 32 44](https://github.com/mui/mui-x/assets/153606579/019c117c-7f1c-4c15-ad48-b6c0b1feb6aa)

### Expected behavior

The DataGrid should switch modes seamlessly without any errors.

### Context

This happens when we perform these steps quickly. It seems that there is not enough time to calculate the width before the mode switches, leading to the error.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Cannot read properties of undefined computedWidth
**Order ID**: 80452

**Comment by KenanYusuf** [comment]
Hi @naimezeqiri, thank you for raising the issue with a reproduction.

I have been able to replicate the issue you are describing on our [documentation example](https://mui.com/x/react-data-grid/row-selection/#checkbox-selection) too.

https://github.com/mui/mui-x/assets/9557798/ab648a62-6b49-4593-ae79-fe028d6986b6

I will add this to our project board for prioritisation.

**Comment by naimezeqiri** [comment]
Hi @KenanYusuf , thank you for your reply! This issue is causing a production problem on our end. Could you please provide a time for when this will be resolved?

**Comment by cherniavskii** [comment]
This seems to be a regression – I cannot reproduce the issue in v6: https://stackblitz.com/edit/react-5945yh-hign7s

@naimezeqiri I think we'll have a fix ready by the end of next week.
