### ISSUE TITLE
[charts] Have a color outline to a single stack bar for a single category

### ISSUE THREAD

**Issue by MainaMwangiy** [mui/mui-x#13716]
### Current behavior

I want to have a single category like Average to have a red outline like this. 
![image](https://github.com/mui/mui-x/assets/38659056/c5e18a13-682b-4caa-9f34-a8208deaa679)

### Expected behavior

Right now not sure what property to use to add a red outline on a stack bar like shown. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: charts bar chart black outline

**Comment by JCQuintas** [comment]
Hi @MainaMwangiy we currently don't support that use-case. The closest you can get currently is a border around all of the "stacks" by reimplementing the `Bar` element.

```tsx
export const Bar = styled(animated.rect, {
  name: 'MuiBarElement',
  slot: 'Root',
  overridesResolver: (_, styles) => styles.root,
})<{ ownerState: BarElementOwnerState }>(({ ownerState }) => ({
  fill: ownerState.isHighlighted
    ? d3Color(ownerState.color)!.brighter(0.5).formatHex()
    : ownerState.color,
  transition: 'opacity 0.2s ease-in, fill 0.2s ease-in',
  opacity: (ownerState.isFaded && 0.3) || 1,
  strokeWidth: 5,
  // This here, use your data instead of seriesA.data
  stroke: ownerState.dataIndex === seriesA.data.length - 1 ? 'black' : 'none',
}));
```

![Screenshot 2024-07-03 at 14 42 24](https://github.com/mui/mui-x/assets/9891233/4f1b3223-1dbc-48d9-9c14-d5f6821c4e48)

You can find the code here: https://stackblitz.com/edit/react-6fcijw?file=Demo.tsx

**Comment by MainaMwangiy** [comment]
@JCQuintas Thanks for the prompt response. But I am facing a challenge using it with ResponsiveChartContainer. I want to have the black outline as you gave above based on a condition like if Average is present, then it should have a black outline. Please check the example and use case I am using. (https://stackblitz.com/edit/react-xh8m58?file=Demo.tsx)

**Comment by JCQuintas** [comment]
You could try to pass categories as `ownerState` through the `slotProps` as shown here: https://stackblitz.com/edit/react-xh8m58-yzhwyy?file=Demo.tsx

**Comment by MainaMwangiy** [comment]
@JCQuintas Again, Thanks for the swift response. The solution has now fully fixed my issue. Thank you.

**Comment by MainaMwangiy** [comment]
@JCQuintas I am facing one more issue on this. If I have a lot of options with 0,1,2 values, then the black outline color gets clamped together. And the UI looks bad. Check attached example. Is there a way to only show the outline on the outer stack borders? Without having the strike tough lines that are from left to right on the stacks. 

What I am getting at the moment when I have may options. 
![image](https://github.com/mui/mui-x/assets/38659056/919246c3-02c1-451d-8d46-867e2ad1c160)

What I want to achieve 
![image](https://github.com/mui/mui-x/assets/38659056/8017d471-f822-4502-a9ee-6ffb880cc1a8)

Please let me know.
