### ISSUE TITLE
[DataGrid] Disable further sorting/filtering after row edit

### ISSUE THREAD

**Issue by DGeretz** [mui/mui-x#13728]
### Steps to reproduce

Link to live example: ([sandbox](https://codesandbox.io/p/sandbox/modest-maria-kqp7gd?file=%2Fsrc%2FDemo.js))

Steps:
1.edit the age of the first user to 1 by double clicking the cell

### Current behavior

2. when you press enter user ''disappears" as sort desc pushes it to the bottom

### Expected behavior

3. i feel that this shouldn't happen as it gives the user no time to double check their edit.

### Context

4. maybe allow a prop onEditSort or something similar to prevent this bad behavior

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: editing
**Order ID**: 71423

**Comment by arminmeh** [comment]
Hi @DGeretz, thanks for raising this.

There is a similar issue regarding editing and filtering.

My proposal is that the other issue becomes the one that addresses both.
I will close this one and ask you to follow/comment on #13711
