### ISSUE TITLE
[DataGrid] throws error "Unexpected Application Error! e.current.state.rows.dataRowIds.at is not a function"

### ISSUE THREAD

**Issue by elevenwin** [mui/mui-x#13722]
### Steps to reproduce

Code:

```
import { DataGrid } from '@mui/x-data-grid';
export default ()=>(
<DataGrid sx={{ height: '100vh', width: '100%', padding: '10px' }}
    columns={[
        {field:'name',headerName:'name', width: 120},
        {field:'age',headerName:'age', width: 120},
        
    ]}
    rows={[
        { id:1,name:'sam',age:12 },
        { id:2,name:'amy',age:15 }
    ]} />
)
```

Steps:
1. yarn build 
2. open on android's webview
3.page show:Unexpected Application Error!
e.current.state.rows.dataRowIds.at is not a function

### Your environment

<details>
package.json
  "dependencies": {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "@mui/icons-material": "^5.15.18",
    "@mui/material": "^5.15.18",
    "@mui/x-data-grid": "^7.8.0",
    "@mui/x-date-pickers": "^7.6.2",
    "@reduxjs/toolkit": "^2.2.5",
    "@types/crypto-js": "^4.2.2",
    "@types/node": "^20.14.9",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^9.1.2",
    "react-router-cache-route": "^1.13.0",
    "react-router-dom": "^6.16.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.18",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.2.1",
    "@typescript-eslint/parser": "^6.2.1",
    "@vitejs/plugin-react": "^4.0.4",
    "eslint": "^8.46.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.8"
  }
</details>

**Search keywords**: @mui/x-data-grid

**Comment by MBilalShafi** [comment]
Hey @elevenwin,

Could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by elevenwin** [comment]
[UI.zip](https://github.com/user-attachments/files/16103863/UI.zip)
it works on pc browser,but mobile browser.

**Comment by arminmeh** [comment]
Hey @elevenwin 

Can you provide a version of the browser and the webview it uses in which the grid does not load?

Thanks

**Comment by elevenwin** [comment]
![Screenshot_2024_0709_120305](https://github.com/mui/mui-x/assets/114123412/96a6f694-6aa3-486e-90f8-05e82459f648)
Debug or deploy the project (UI.zip) , access by google browser(The screenshot shows the browser version) .
The entire page is blank.

**Comment by arminmeh** [comment]
@elevenwin it looks like you are using unsupported version of the webview

You can check the [supported browser versions for the grid v7](https://github.com/mui/mui-x/blob/v7.0.0/.browserslistrc)

There are two possible solutions:
- Try to update the webview to the supported version
- Add a polyfill for the missing `at` method of Array instances

You can check all relevant information here
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
