### ISSUE TITLE
[pickers] DateCalendar Custom Header doesn't show dates for December-March

### ISSUE THREAD

**Issue by lamrhoang** [mui/mui-x#13721]
### Steps to reproduce

Link to live example: https://mui.com/x/react-date-pickers/custom-components/#component-4

Steps:
1.  View dates for December to March to see issue

### Current behavior

When clicking to months of December to March, dates are not shown correctly. For December, the dates are completely empty. For February 2025, it shows just the first date, but it is in the wrong place.

### Expected behavior

When clicking to months of December to March, the dates should be shown correctly.

### Context

I am using a custom calendar header for my current work so that users can see different dates.

**Search keywords**: DateCalendar, CustomCalendarHeader

**Search keywords**:

**Comment by LukasTy** [comment]
Hello @lamrhoang.
Thank you for creating this issue! 🙏 
I was unable to reproduce this issue locally or having set different time zones (Paris, Los Angeles).
Could you provide more information about your setup (timezone, browser, and OS)?
Providing a video showcasing the issue would also help. 🙏
