### ISSUE TITLE
[docs] Date Range Customization Playground does not fit on smaller screens

### ISSUE THREAD

**Issue by TheOneTheOnlyJJ** [mui/mui-x#13736]
### Related page

https://mui.com/x/react-date-pickers/playground/

### Kind of issue

Broken demo

### Issue description

![image](https://github.com/mui/mui-x/assets/63308694/0695f5f9-76d9-4c77-94c2-5015004ccfba)
As you can see, the date range component from the playground demo does not fit on smaller screens.
It is not possible to go to the next months on the picker, as only the Left Arrow Icon Button is visible.

### Context

Information for my screen is the following:
![image](https://github.com/mui/mui-x/assets/63308694/15088377-2277-4be7-a1ee-5f050dffb67c)

**Search keywords**: picker customization

**Comment by LukasTy** [comment]
Thank you for reporting this problem. 🙏

**Comment by TheOneTheOnlyJJ** [comment]
I've found it's because of "Static desktop mode". It may not be a bug after all, and just my option configuration mistake.

**Comment by LukasTy** [comment]
> I've found it's because of "Static desktop mode". It may not be a bug after all, and just my option configuration mistake.

It's not ideal—a horizontal overflow is desirable in this case. 😉

**Comment by TheOneTheOnlyJJ** [comment]
Also, note that the "Show days outside current month" option does not seem to apply. I don't know if it should be for side-by-side month pickers like that one. If it should apply, this may not be a docs issue.

**Comment by LukasTy** [comment]
> Also, note that the "Show days outside current month" option does not seem to apply. I don't know if it should be for side-by-side month pickers like that one. If it should apply, this may not be a docs issue.

That is the intended behavior.
https://github.com/mui/mui-x/blob/1ea2352847481238902cabbeffe85b1fbe34921f/packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx#L576
The UX/UI with multiple calendars and that property would be "strange". 🤔
