### ISSUE TITLE
[Data grid] column order model

### ISSUE THREAD

**Issue by karl-vernet** [mui/mui-x#13740]
### Summary

We desperatly need to control column order in DataGrid the same way filter, sort , etc is done. 
Issue #5704 is already describing the change we would like, it has been open for nearly a year and is from a pro licence, but is not solved yet.
Is there a chance this feature will be available in near future ?

**Search keywords**: controlled column order
**Order ID**: 76967

**Comment by KenanYusuf** [comment]
@karl-vernet please could you leave this as a comment on #5704? I have added a premium support label there to highlight the request further.

Closing as a duplicate.
