### ISSUE TITLE
[DataGrid] onRowClick does not work when custom row components are applied.

### ISSUE THREAD

**Issue by DaehyeongLee** [mui/mui-x#13744]
### Steps to reproduce

Link to live example: (required)

Steps:
1. I used DataGrid > slots property.
2. DataGrid > `slots={{ row: CustomRow }}` is applied.
3. DataGrid > `onRowClick={callMyFunction}` is applied.
4. CustomRow looks like this. `<GridRow {...props} onContextMenu={callMyContextMenu} />`

### Current behavior

DataGrid's onRowClick does not work.
And GridRow's onClick also doen not work.

### Expected behavior

DataGrid's onRowClick should operate normally even on GridRow with onContextMenu applied.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: GridRow, onRowClick

**Comment by arminmeh** [comment]
@DaehyeongLee 
Can you share your environment and provide more details about your custom `GridRow` component.

I have replicated the setup that you have described and I am getting the right console outputs for both event handlers
https://stackblitz.com/edit/react-rbpzvo-a1tqf2?file=Demo.tsx

**Comment by daehyeongLee-aladin** [comment]
> @DaehyeongLee Can you share your environment and provide more details about your custom `GridRow` component.
> 
> I have replicated the setup that you have described and I am getting the right console outputs for both event handlers https://stackblitz.com/edit/react-rbpzvo-a1tqf2?file=Demo.tsx

I was looking at the demo code you made me and found out it was a problem because I didn't put row information as a props in custom GridRow I made. Thanks for the reply!
