### ISSUE TITLE
[charts] Area Chart does not allow logarithmic scale

### ISSUE THREAD

**Issue by nickroh15** [mui/mui-x#13759]
### Steps to reproduce

Link to live example:[ (required)
](https://codesandbox.io/p/sandbox/react-charts-tcnj4m?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clumf50xd00073j6fto6kz0j7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clumf50xc00033j6f6pmpp2nt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clumf50xc00043j6f6kq4v0nt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clumf50xc00063j6f7w9oda3y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clumf50xc00033j6f6pmpp2nt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumf50xc00023j6fn8d67qm1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmuixcharts%252FBasicBars.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A31%257D%255D%257D%252C%257B%2522id%2522%253A%2522clumjnt0y00023j6f9c0meni5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A43%252C%2522startColumn%2522%253A49%252C%2522endLineNumber%2522%253A43%252C%2522endColumn%2522%253A49%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clumf50xc00033j6f6pmpp2nt%2522%252C%2522activeTabId%2522%253A%2522clumjnt0y00023j6f9c0meni5%2522%257D%252C%2522clumf50xc00063j6f7w9oda3y%2522%253A%257B%2522id%2522%253A%2522clumf50xc00063j6f7w9oda3y%2522%252C%2522activeTabId%2522%253A%2522clv6a2hrf00ky3j6g486wx939%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clv6a2hrf00ky3j6g486wx939%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clumf50xc00043j6f6kq4v0nt%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clumf50xc00043j6f6kq4v0nt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
Steps:
1. In the example you can see that the lines with 'area=true' are not rendered if the scale is set to 'log'

### Current behavior

When using a log Scale in conjunction with an area chart, the area is not displayed.

### Expected behavior

The Area should be displayed?

### Context

Working on a charting app, where I want to dynamically configure different charts, including line and area charts. The app should also support are charts with a log y-axis scale.

**Search keywords**: Line Chart Area Chart logScale logarithmic Scale

**Comment by JCQuintas** [comment]
Hi @nickroh15 it indeed looks like a bug. 

This seems to only affect `axis.type = log`, `sqrt` works fine.

We will add it to our list, thanks for reporting 💪

**Comment by alexfauquette** [comment]
The issue with area+log scale is that the area needs a baseline which is for now the 0. As you can guess having a 0 in a log scale can only cause troubles 😁

To make it work, you will need 2 part
- fix the min/max of the y-axis to ùmake sure it does not touch 0. In your example nothing get plot because the y-axis is asked to generate a log-scale that maps 0 -> 150 which is impossible.
- Add an area baseline in the definition of the log scale to let the area plot know which value should be used instead of the default 0

**Comment by alexfauquette** [comment]
>  I am not sure how I can define a "baseline" for my logScale

Sorry for the lack of clarity. This baseline does not exist. It's more a note for the person who will take care of this issue

After a second look, it seems we can solve the issue without introducing a new params.

In the following line, we do a distinction between areas and lines when computing the extremums.

https://github.com/mui/mui-x/blob/f4ff9f194a5cf2cab77c60cf56ac3257ec75813e/packages/x-charts/src/LineChart/extremums.ts#L44

We should modify this such that area with a log scale is treated the same way as a line.

I proposed a PR to fix that
