### ISSUE TITLE
[pickers] Bug when typing the value on input

### ISSUE THREAD

**Issue by KarineBrandelli** [mui/mui-x#13769]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/s/qzkwfj?file=/src/Demo.tsx

Steps:
1. Type the input value really fast (like you're accidentally hit the keyboard)

### Current behavior

I'm using the DatePicker component, and sometimes when I type a input value,
this bug happens, like the focus is beeing changed:

[bug.webm](https://github.com/mui/mui-x/assets/108953489/8b03144d-0af0-42db-81e7-28796673c84e)

I've tried the same 'fast typing' on the docs, and the same thing happens:

[docs.webm](https://github.com/mui/mui-x/assets/108953489/68c4f607-38d0-4444-8f76-0ed0f11b0ee0)

I know it's a really unsual bug, but maybe there's something to do about it?

### Expected behavior

Not to change the focus between slots.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: typing

**Comment by michelengelen** [comment]
Hey @KarineBrandelli and sry for the late reply.
I cannot reproduce the issue you are facing.
Could you please make very precise steps to what you are doing?

**Comment by LukasTy** [comment]
@michelengelen @KarineBrandelli This could have been an issue caused by a bug solved with https://github.com/mui/mui-x/pull/13779.
Could you double-check if you are experiencing the same problem with the latest package version?

**Comment by KarineBrandelli** [comment]
> Hey @KarineBrandelli and sry for the late reply. I cannot reproduce the issue you are facing. Could you please make very precise steps to what you are doing?

That's the thing, it only happens sometimes, and more likely when you kinda 'hit' the keyboard with a lot of keys at the same time.

**Comment by LukasTy** [comment]
@KarineBrandelli I've tried fast typing on docs and it does seem to react fine to it. 🤔 
Could you provide a more step by step guide on what you are typing to trigger it or maybe provide a video with the keys that are being pressed as in the video below?

https://github.com/user-attachments/assets/9d7892ea-7f6f-45ba-8882-442827d8fbf7

**Comment by KarineBrandelli** [comment]
> @KarineBrandelli I've tried fast typing on docs and it does seem to react fine to it. 🤔 Could you provide a more step by step guide on what you are typing to trigger it or maybe provide a video with the keys that are being pressed as in the video below?
> 
>  Screen.Recording.2024-07-22.at.15.20.19.mov

It's exactly how your typing, but not only on the year slot! Select the first slot, and then like 'hit' the keyboard until all the slots are filled (dummy I know 😩)

**Comment by michelengelen** [comment]
@LukasTy I did just try it again and also used throttling to simulate heavy load, but still could not reproduce that issue. 🤷🏼 
@KarineBrandelli could you give us some information on your setup, etc? What OS are you on, which browser were you using? Does it happen for colleagues as well?
