### ISSUE TITLE
[question] [pickers] How can I get access to the Pickers Adapter Utils for use with `usePickersTranslations`?

### ISSUE THREAD

**Issue by kealjones-wk** [mui/mui-x#13767]
### The problem in depth

#13657 Added `usePickersTranslations` which is awesome, but it didn't provide a public version of `useUtils` like was requested in #12691 

Access to the Adapter Utils is necessary to use at least 3 of the properties on LocaleText, see: `openDatePickerDialogue`, `openTimePickerDialogue`, and `clockLabelText`. There is currently no public way to get the utils for this argument that i know of. Is there some way that i don't know of?

**Search keywords**: useUtils, date pickers, localization, localeText, adapter, utils

**Comment by kealjones-wk** [comment]
Sorry didn't mean to do "Priority support"

**Comment by michelengelen** [comment]
@kealjones-wk is this issue fixed for you?
