### ISSUE TITLE
[question] GridToolbar Menu and basePopper positions

### ISSUE THREAD

**Issue by atsoy** [mui/mui-x#13766]
### The problem in depth

Demo: https://codesandbox.io/p/sandbox/sleepy-framework-3my88y

Trying to replace default baseButton with `CustomButton` and encounter following:

When toolbar buttons are moved to the right corner (as `CustomToolbar`), they are aligned correctly, but not the menus / basePopper.

Menus: by opening a menus it shows it in the top upper corner (basically x:0, y: 0). Where basePopper is being rendered on the same position, as with default baseButton (which is not overwritten).

Setting `placement` doesn't help. I'd like to place them accordingly to the button positions (basically below each of them).

Questions is: Am I missing something by trying to use it?

Look forward to hearing from you.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: toolbar, custom toolbar, styling, custom subcomponents, menu, column management
**Order ID**: 62555

**Comment by arminmeh** [comment]
You can also check this example on how to position the filter panel
https://mui.com/x/react-data-grid/filtering/customization/#customize-the-filter-panel-position

**Comment by atsoy** [comment]
Thanks for quick responses @romgrk @arminmeh. It helped a lot. I just wonder, when I would place multiple Toolbar button, like Filter and ColMgmnt, would they share the anchorEl? Since panel will accept first available, guess they will be anchored to the first available element, right?

**Comment by romgrk** [comment]
The panel is anchored to a different element, `#gridPanelAnchor` if I remember correctly. You can inspect the DOM to find it. I don't think it's configurable at the moment.

**Comment by atsoy** [comment]
Exactly, I've seen this in the DOM, was just not sure if it flexibele to configure, but now it's clarified. Are there any intentions to adjust it?

**Comment by romgrk** [comment]
It's not configurable, all toolbar buttons share the same anchor element. You could open a feature request for it. But could you clarify the use-case you're trying to solve? I feel like it should be possible to move the anchor using custom CSS (`top` and `left`), and it should be possible to align differently by passing the prop `slotProps={{ panel: { placement: 'bottom-end' } }}`.

**Comment by atsoy** [comment]
It's not critical one. Alternative way would be to basically create own components with separated anchor elements. Thanks for the support!
