### ISSUE TITLE
[pickers] DateRangePicker's slotProps for `calendarHeader` don't seem to work for multiple calendars

### ISSUE THREAD

**Issue by arudenkoofficial** [mui/mui-x#13774]
### The problem in depth

I'm using `DateRangePicker` from the `@mui/x-date-pickers-pro` package.
I'm trying to customize the header of the component displaying the month. According to the [Slot API documentation](https://mui.com/x/api/date-pickers/date-range-calendar/#slots), the `PickersCalendarHeader` should be rendered by default in the calendarHeader slot and that component seems to accept the `sx` prop.

Following [the documentation on customizing](https://mui.com/x/react-date-pickers/custom-components/#component-props-4) calendar component headers  I'm passing the following slotProps exactly the same way as in your documentation:
```
slotProps={{ calendarHeader: { sx: { border: '1px red solid' } } }}
```

However, this doesn't work for `DateRangePicker`, when it displays more than 1 calendar.
How can I customize the DateRangePicker header in the case of 2 or 3 months?
Link to the corresponding codesandbox with an example: [CodeSandbox Demo](https://codesandbox.io/p/sandbox/async-wood-mh83gr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyeby8ux00063b6mvknjejsm%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyeby8ux00023b6m52m9ftm2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyeby8ux00033b6mpheikbts%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyeby8ux00053b6mha3civ5x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyeby8ux00023b6m52m9ftm2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyeby8ux00013b6mwdt7x6ee%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clyeby8ux00023b6m52m9ftm2%2522%252C%2522activeTabId%2522%253A%2522clyeby8ux00013b6mwdt7x6ee%2522%257D%252C%2522clyeby8ux00053b6mha3civ5x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyeby8ux00043b6mwrsy9ntn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyeby8ux00053b6mha3civ5x%2522%252C%2522activeTabId%2522%253A%2522clyeby8ux00043b6mwrsy9ntn%2522%257D%252C%2522clyeby8ux00033b6mpheikbts%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyeby8ux00033b6mpheikbts%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
Thanks in advance for any help you can provide!
<img width="640" alt="Screenshot 2024-07-09 at 2 31 56 PM" src="https://github.com/mui/mui-x/assets/84877729/215dff62-de3d-423b-8299-654b8ac82e73">
<img width="473" alt="Screenshot 2024-07-09 at 2 31 32 PM" src="https://github.com/mui/mui-x/assets/84877729/f7f5ac12-5d32-4ac0-a76f-583d8190d34a">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
I'm using Chrome browser for development

System:
    OS: macOS 14.1.2
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Not Found
    Safari: 17.1.2
  npmPackages:
    @emotion/react: 11.11.3 => 11.11.3 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.0 
    @mui/icons-material: 5.15.20 => 5.15.20 
    @mui/lab: 5.0.0-alpha.171 => 5.0.0-alpha.171 
    @mui/material: 5.16.0 => 5.16.0 
    @mui/material-nextjs: 5.15.11 => 5.15.11 
    @mui/private-theming:  5.16.0 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.16.0 
    @mui/types:  7.2.14 
    @mui/utils:  5.16.0 
    @mui/x-date-pickers:  7.9.0 
    @mui/x-date-pickers-pro: 7.9.0 => 7.9.0 
    @mui/x-license: 7.9.0 => 7.9.0 
    @types/react: 18.2.48 => 18.2.48 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.5.2 => 5.5.2
```
</details>

**Search keywords**: DateRangePicker, slotProps, calendarHeader
**Order ID**: 93756

**Comment by LukasTy** [comment]
Hello @arudenkoofficial.
Thank you for opening this issue! 🙏 
There is a clear problem here that we need to fix. 👍
