### ISSUE TITLE
[data grid] data-grid is not working on old browser version, but why does the official demo run on the same browser? 

### ISSUE THREAD

**Issue by elevenwin** [mui/mui-x#13792]
### Your environment

Chrome 78.0.3904.96

**Search keywords**: browser version

**Comment by arminmeh** [comment]
Hi @elevenwin 

Can you add more details around the issue?
Which examples are working and how is your grid set up

Are there any differences in the data or props?

It would be great if you can provide a live example

Chrome 78.0.3904.96 is not officially supported by DataGrid v7. This does not mean that it will never work, it means that there might be some cases where certain browser features will be missing and the grid will not work (partially or completely)

Hope that this clarifies it a bit.

**Comment by elevenwin** [comment]
Demo:[MIT license (free forever)](https://mui.com/x/react-data-grid/#mit-license-free-forever)
import * as React from 'react';
import Box from '@mui/material/Box';
import { DataGrid, GridColDef } from '@mui/x-data-grid';

const columns: GridColDef<(typeof rows)[number]>[] = [
  { field: 'id', headerName: 'ID', width: 90 },
  {
    field: 'firstName',
    headerName: 'First name',
    width: 150,
    editable: true,
  },
  {
    field: 'lastName',
    headerName: 'Last name',
    width: 150,
    editable: true,
  },
  {
    field: 'age',
    headerName: 'Age',
    type: 'number',
    width: 110,
    editable: true,
  },
  {
    field: 'fullName',
    headerName: 'Full name',
    description: 'This column has a value getter and is not sortable.',
    sortable: false,
    width: 160,
    valueGetter: (value, row) => `${row.firstName || ''} ${row.lastName || ''}`,
  },
];

const rows = [
  { id: 1, lastName: 'Snow', firstName: 'Jon', age: 14 },
  { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 31 },
  { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 31 },
  { id: 4, lastName: 'Stark', firstName: 'Arya', age: 11 },
  { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
  { id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
  { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
  { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
  { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 },
];

export default function DataGridDemo() {
  return (
    <Box sx={{ height: 400, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        initialState={{
          pagination: {
            paginationModel: {
              pageSize: 5,
            },
          },
        }}
        pageSizeOptions={[5]}
        checkboxSelection
        disableRowSelectionOnClick
      />
    </Box>
  );
}

**Comment by arminmeh** [comment]
@elevenwin are you saying that this demo works or this demo does not work.
In the ticket you have stated that one grid (I assume your setup) is not working and the official demo does

You can use [this page](https://mui.com/x/introduction/support/#bug-reproductions) to generate live example

Once more, you are using a browser version that is not supported.
If the code execution does not reach parts of the code that is not supported by your browser, the grid will be working fine.

This might be the reason for your observation.

**Comment by elevenwin** [comment]
The offical demo can works on my mobile browser(access offcial site).
The copy of demo can works on pc browser,but mobile browser.
Same code,same mobile browser, but different result.why?

**Comment by arminmeh** [comment]
What is the error that you get?

**Comment by elevenwin** [comment]
No error info.But the page is displayed as blank.
Can you provide a demo for me to run?
The copy of demo can not work on mobile,but success access the demo on offcial site .

**Comment by arminmeh** [comment]
> Can you provide a demo for me to run?
What do you mean by this?

The demo is already provided, as you said it is working on our page.
If it does not work in your project I cannot help you if you do not share either error or create a live example with the setup that you have where we can reproduce the issue
