### ISSUE TITLE
[question] Possibility to save changes in data grid, like column sorting, hiding ordering. 

### ISSUE THREAD

**Issue by ternala** [mui/mui-x#13809]
### The problem in depth

I want to have the possibility to save the settings of columns reorder, change their visibility, or change sort. It would be really helpful for me. Is it possible to do it via Data Grid currently like some props? 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Datagrid saving state
**Order ID**: 83389

**Comment by arminmeh** [comment]
Hi @ternala 
I think that this is the [feature](https://mui.com/x/react-data-grid/state/#save-and-restore-the-state) you are looking for
