### ISSUE TITLE
[DataGrid] Printing large data set will crash the browser

### ISSUE THREAD

**Issue by zhangjianrencai** [mui/mui-x#13801]
### Steps to reproduce

Link to live example: (required)

Steps:
1. open [https://mui.com/x/react-data-grid/export/]
2. click the print button in the data grid

![image](https://github.com/mui/mui-x/assets/4982796/9246052b-cb10-4f81-a52b-57145e1ab565)

### Your environment

[https://mui.com/x/react-data-grid/export/]
</details>

**Search keywords**: print large data

**Comment by arminmeh** [comment]
Hi @zhangjianrencai 
Thanks for reporting this.
I have confirmed the issue and will put this directly on our board.

**Comment by arminmeh** [comment]
@zhangjianrencai 
I found the same issue already opened and added to our board
#13039 
So, I will close this one as a duplicate and ask you to follow and 👍 the other one so that it can be prioritized

Thank you once more for reporting this and for your patience
