### ISSUE TITLE
Date Calendar like an actual Outlook-ish calendar

### ISSUE THREAD

**Issue by thany** [mui/mui-x#13808]
### Summary

The DateCalendar has been given a bit of an unfortunate name, because with the name "calendar" one might hope it'd be an actual calendar, perhaps akin to a view that software like Outlook provides. Instead, it's actually a regular DatePicker except it isn't in a popup. This is fine, but not quite what we are looking for.

What we need is a month view such as what popular calendar applications provide, and I don't think the DateCalendar can do that without customisations so massive that might as well build one from scratch.

### Examples

Vuetify, another popular Material-like UI framework, has a component like the one we're looking for:
https://vuetifyjs.com/en/components/calendars/

Another example might be this one, which is outdated and doesn't come with the same level of top-notch support that we have come to expect from MUI 😘
https://github.com/rouftom/react-mui-scheduler

### Motivation

We are moving away from a Vue 2 application (finally) and are going to propose to the customer a total replacement with an all new tech stack, which is going to be based around Next.js. That means React, and our preference currently lies with MUI for mostly every other component. It's pretty awesome, you gotta admit 😊

That older Vue 2 application actually uses Vuetify (see examples), albeit an older version. Since the calendar component was available there, a part of the application was designed around this calendar component. The customers of the customer (end users) have come to expect there to be a month-view calendar akin to Outlook and the likes, and we would very much like to keep it as similar as possible.

**Search keywords**: calendar

**Comment by flaviendelangle** [comment]
Hi,

Usually what you are describing is called a Scheduler (if I understand your use case correctly) or sometime a Rich Calendar.
We have an issue to see how much the community would like to have it #1407.
Iit's a whole new component that will require a lot of work and will be independent from the pickers (new package). It's one of the good candidate for the future, we don't have any roadmap yet but I wouldn't be surprised it we start working on it in the 1st half of 2025 :+1: 

If you have any specific need, feel free to comment the issue I linked above, the more information we have the easier it will be for us to build the component the community wants and needs :pray:

**Comment by thany** [comment]
Of course, I understand it's quite an involved component to build. Not something you can knock out in a week or two. It's part of the reason we're looking for a ready-to-use one 😀

If our customer pulls through, 2025 is going to be a bit late, I think, so that means we'll have to look for an alternative. Or maybe it'll be just in time for us to betatest it. Who knows. Thanks anyway for your response, much appreciated!

**Comment by LukasTy** [comment]
@thany Thank you for the issue and the appreciation shown towards the MUI products. 🙏

Feel free to comment on the linked issue regarding any feature requests that are essential for you to adopt such a component. 😉 

I'm closing this issue as this seems like a duplicate.
