### ISSUE TITLE
[pickers] MUI DateRangePicker property "name" doesnt render

### ISSUE THREAD

**Issue by JoseFerDiverger** [mui/mui-x#13818]
### Steps to reproduce

Link to live example: [Example](https://codesandbox.io/s/3dk9fc?file=/src/Demo.tsx)

Steps:
1. Add DateRangePicker with "name" parameter to react code
<img width="470" alt="image" src="https://github.com/user-attachments/assets/6a4f19b1-f73b-4fe2-ae32-dabbf5796bf3">

2. Open browser javascript console

3. Check that parameter "name" doesnt exist in that component
<img width="832" alt="image" src="https://github.com/user-attachments/assets/5ad6ae60-b050-405b-a5c7-2fe1d491cf80">

This parameter exist in the api documentation and its used on our project, so with last update it was broken
<img width="845" alt="image" src="https://github.com/user-attachments/assets/217372c4-8490-4b06-a202-e59cbdd5c395">

### Current behavior

Can't get component by name

### Your environment

Production

**Search keywords**: daterangepicker

**Search keywords**:

**Comment by LukasTy** [comment]
@JoseFerDiverger Thank you for reporting this problem! 🙏 
The issue has been introduced with v7.0.0-beta.4.
Looking for the cause.

**Comment by LukasTy** [comment]
Here is the regression cause: https://github.com/mui/mui-x/pull/10649/files#diff-51686a4d64819c7725f329d4c9c06225ad0bc5345ce97d24ed3df8976433aa07L156.
