### ISSUE TITLE
[data grid] Resizing columns gets misaligned

### ISSUE THREAD

**Issue by abcd-ca** [mui/mui-x#13851]
### The problem in depth

I have a bunch of columns and enough rows that the pagination has multiple pages. I noticed today when setting the `minWidth: 0` on the `GridColumnDef` config (weird client request) that after resizing enough columns, where the whole set of columns is effectively more to the left (expected), that when I then scroll past the buffered rows, the new rows retain the original column alignment and are therefore offset from the rows that were originally in view before scrolling (unexpected). I was on MuiX 7.3.0 and upgraded to 7.10.0 after which the problem persisted.

<img width="1981" alt="image" src="https://github.com/user-attachments/assets/5dbee214-e645-4313-ba87-ac9744e93672">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 13.6.7
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
    pnpm: 9.4.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.15
    @mui/icons-material: ^5.15.15 => 5.15.15
    @mui/material: ^5.15.15 => 5.15.15
    @mui/private-theming:  5.16.1
    @mui/styled-engine:  5.16.1
    @mui/styled-engine-sc: ^6.0.0-alpha.18 => 6.0.0-alpha.18
    @mui/system:  5.16.1
    @mui/types:  7.2.15
    @mui/utils:  5.16.1
    @mui/x-data-grid:  7.10.0
    @mui/x-data-grid-pro: ^7.10.0 => 7.10.0
    @mui/x-internals:  7.10.0
    @mui/x-license:  7.10.0
    @types/react: ^18.2.75 => 18.2.75
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^6.1.8 => 6.1.8
    typescript: ^5.4.4 => 5.4.4
```
</details>

**Search keywords**: resize misalign minWidth
**Order ID**: 89501

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
