### ISSUE TITLE
[data grid] Check the grouped child rows on select of the grouped row

### ISSUE THREAD

**Issue by ashishchoudhary12** [mui/mui-x#13850]
### Steps to reproduce

I want to check the grouped child rows when the grouped row is selected. I've tried the solution mentioned [here](https://github.com/mui/mui-x/issues/4248#issuecomment-1074928601), but it didn't work. I also tried the approach discussed [here](https://github.com/mui/mui-x/issues/4270), but it didn't work either. Here's what I've tried so far:
https://codesandbox.io/p/sandbox/staging-bash-lmhs27?file=%2Fsrc%2FDemo.tsx

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Check the grouped child rows on select of the grouped row

**Comment by michelengelen** [comment]
Hey @ashishchoudhary12 ... it works as expected with Data Grid Premium: [DEMO](https://codesandbox.io/p/sandbox/charming-architecture-fzcgkh)

I have added a recipe PR so that we can provide a demo on the docs as well: #13856 

I will close this one in favor of #4248

**Comment by ashishchoudhary12** [comment]
@michelengelen Thank you it is working.. 
Once I checked how can I get the checked rows.
Like either by apiRef.current.something() or using some prop?
