### ISSUE TITLE
[data grid] CSV export adds malformed/buggy characters

### ISSUE THREAD

**Issue by arc-rajoriya** [mui/mui-x#13866]
### Steps to reproduce

Link to live example: (required)

https://stackblitz.com/edit/react-jc116w?file=Demo.tsx,package.json

Steps:
1. Simply add DataGridPremium
2. Add row data with pattern like: `Management Fees – Gross of Offsets, Waivers & Rebates): `
3. Download the csv and see the result, the column have data with pattern mentioned in 2nd point will come like this 
    `Management Fees â€“ Gross of Offsets, Waivers & Rebates):`

### Current behavior

On dowloading CSV the data we pass to row is not coming in same format.

Unexpected Data: `Management Fees â€“ Gross of Offsets, Waivers & Rebates):`

### Expected behavior

If our row have data in pattern like this `Management Fees – Gross of Offsets, Waivers & Rebates):` , so it should get downloaded with same format only.

Expected Data: `Management Fees – Gross of Offsets, Waivers & Rebates):` 

### Context

We are trying to render DataGridPremium with data, which have some pattern like  `Management Fees – Gross of Offsets, Waivers & Rebates):` 

So If I download/Export CSV user is expecting data will get download in same format as user is seeing on grid.

Grid:
![image](https://github.com/user-attachments/assets/a07bad28-f5ff-4f48-a59d-b225084ab536)

Unexpected:
![image](https://github.com/user-attachments/assets/d9d398fc-bb39-4d6a-850e-aa4af10481ae)

I have tested in v7, there also same issue happening. Shared the demo link above. Please check.

### Your environment

 System:
    OS: Linux 5.15 Amazon Linux 2
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.182
  npmPackages:
    @emotion/react:  11.11.4 
    @emotion/styled:  11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.19 
    @mui/icons-material:  5.15.19 
    @mui/lab:  5.0.0-alpha.170 
    @mui/material:  5.15.19 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  6.19.6 
    @mui/x-data-grid-premium:  6.19.6 
    @mui/x-data-grid-pro:  6.19.6 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-license-pro:  6.10.2 
    @types/react:  17.0.80 
    react:  17.0.2 
    react-dom:  17.0.2 
    typescript:  4.9.5 

**Search keywords**: CSV Grid Download
**Order ID**: 75570

**Comment by michelengelen** [comment]
Hey @arc-rajoriya export to CSV works just fine.
The reason you are seeing this strange character in your table is that your selected font has no character for it.
From your example you are using the `EN DASH` character with unicode `U+2013`, where a normal dash/hyphen is `U+002D`.

This is a screenshot of the export I am seeing in the editor:

<img width="1392" alt="Screenshot 2024-07-17 at 16 52 12" src="https://github.com/user-attachments/assets/6c56260c-39c4-4f9e-a0dc-95cb0a6cc899">

As this is working as expected I will close this issue, but please feel free to reopen. 
Thanks! 🙇🏼
