### ISSUE TITLE
[data grid] Save / Restore state with dynamic columns

### ISSUE THREAD

**Issue by e30alex** [mui/mui-x#13873]
### The problem in depth

Hello guys!  I'm using the data grid premium and I have an issue with saving and restoring the state for a table. This table is using dynamic columns. Based on some checks we are doing in a prev step, we can have 10 or 15, 20 columns. I'm saving the state for this table in localstorage, but after i'm changing the data from the prev step, and I have a different number of columns, the state is mixed up and the width for the columns is not correct. Do you have any advice on how can I handle this? Is there any option to save the state only for some columns? the ones that are fixed? and leave the dynamic ones with the default state?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 Google Chrome and Brave


  System:
    OS: macOS 14.3
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.182
    Edge: Not Found
    Safari: 17.3
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.5 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material: ^5.14.6 => 5.14.6 
    @mui/material: ^5.13.6 => 5.13.6 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.6 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.6 
    @mui/x-data-grid:  6.19.8 
    @mui/x-data-grid-premium: ^6.15.0 => 6.19.8 
    @mui/x-data-grid-pro:  6.19.8 
    @mui/x-license-pro:  6.10.2 
    @types/react: 18.2.45 => 18.2.45 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 
```
</details>

**Search keywords**: save restore state
**Order ID**: 93621

**Comment by michelengelen** [comment]
Hey @e30alex could you provide a minimal reproduction for your dynamic columns approach?
That way I can have a better look at what your requirements are!

**Comment by alexoancea-mtd** [comment]
Hey @michelengelen. Bellow is a minimal reproduction for our dynamic columns. Let's suppose we have two entities with a given startDate and endDate. Based on these dates we are displaying columns for each day. Day 1 -> value 1, Day 2 -> value 2 and so on.

`const calculateColumns = (
  startDate: Dayjs | null,
  endDate: Dayjs | null,
) => {
  const days = endDate.diff(startDate, 'day') + 1;

  let columns: GridColDef[] = [
    {
      field: 'name',
      headerName: "Name",
    },
    {
      field: 'brand',
      headerName: "Brand",
    },
    {
      field: 'tax',
      headerName: "Tax",
    },
  ];

  const columnGroupingModel: GridColumnGroupingModel = [];

  for (let i = 0; i < days; i++) {
    const date = startDate.add(i, 'day');
    const dateFormatted = date.format('DD');
    const dayFormatted = date.format('dd');
    const monthFormatted = date.format('MMM');
    const weekNumber = getWeekNumberByWeekStartDay(
      date,
      mediaPlanDetails?.weekStartDay ?? 1,
    );

    columns.push({
      field: `day${i + 1}`,
      headerName: `${dayFormatted}`,
    } as GridColDef);

    const currentWeekGroupModel = columnGroupingModel.find(
      (item: any) =>
        item.groupId === `month ${monthFormatted} week ${weekNumber}`,
    );

    if (!currentWeekGroupModel) {
      columnGroupingModel.push({
        groupId: `month ${monthFormatted} week ${weekNumber}`,
        headerName: `${date.format('MMM[,] YY')} - WK ${weekNumber}`,
        headerAlign: 'center',
        children: [
          {
            groupId: `${dateFormatted}`,
            headerAlign: 'center',
            children: [
              {
                field: `day${i + 1}`,
              },
            ],
          },
        ],
      });
    } else {
      currentWeekGroupModel.children.push({
        groupId: `${dateFormatted}`,
        headerAlign: 'center',
        children: [
          {
            field: `day${i + 1}`,
          },
        ],
      });
    }
  }

  columns = columns.concat([
    {
      field: 'cost',
      headerName: "Cost",
      type: 'number',
      width: 50,
    },
    {
      field: 'supplierName',
      headerName: "Supplier Name",
    },
  ]);
}`

**Comment by alexoancea-mtd** [comment]
@michelengelen why this issue was closed? I added the example 2 days ago and this was closed due to inactivity 15 hours ago :|

**Comment by michelengelen** [comment]
Sry... something seems to be off with the workflow. We'll have a look!

**Comment by michelengelen** [comment]
So, using a dynamic set of columns is tricky, since you would typically want to have a stable reference to improve performance. But this should still be feasible.

One possibility would be to use the `apiRef.restoreState` method from the grid.

(dummy code for showcasing the idea)
```tsx

// on load
const columns = calculateColumns(date1, date2);

// when columns are ready
useEffect(() => {
  // load from localstorage or some other place
  const previousState = ...
  
  // check if all columns are present in the loaded state
  ...

  // compose the new state
  const composedState = {
    ...previousState,
    ...addedState,
  };

  // restore the composedState
  apiRef.current.restoreState(composedState)
}, [columns, apiRef])

```
