### ISSUE TITLE
[pickers] dayjs with default timezone broke picker

### ISSUE THREAD

**Issue by IAluI** [mui/mui-x#13875]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-ztvxhd?file=Demo.tsx

Steps:
1. Set default timzone for dayjs
2. Picker is broken

### Current behavior

![image](https://github.com/user-attachments/assets/dac750ea-4076-49b8-8f1a-63a0ca532cff)

### Your environment

Stackblitz
Chrome 126.0.6478.128

**Search keywords**: dayjs, timezone, tz, setDefault

**Comment by LukasTy** [comment]
Hello @IAluI.
Thank you for creating this issue. 🙏 
It looks like a duplicate of dayjs problem with UTC-like timezones (0 offset): https://github.com/mui/mui-x/issues/9653.

I'm closing this issue as a duplicate. 😉
