### ISSUE TITLE
Add Audio Player/Waveform component

### ISSUE THREAD

**Issue by TheOneTheOnlyJJ** [mui/mui-x#13883]
### Summary

Along the lines of #13196, right now the only way to play audio in a MUI interface is to use the default HTML `<audio>` element, which does not conform to the Material Design guidelines. While the [official MD3 docs](https://m3.material.io/) do not cover audio players, nor are there any potential examples for us to base a component on, we could extrapolate from what I found in the docs regarding video players (#13196).

### Examples

Conforming to Material Design:
- material-ui-audio-player: [GitHub](https://github.com/Werter12/material-ui-audio-player?tab=readme-ov-file)
- vuetify-audio-player: [GitHub](https://github.com/WoodyDark/vuetify-audio-player)
- Material UI Design Audio Player: [CodePen](https://codepen.io/michael-zhigulin/pen/NGZGma)

Others:
- react-audio-player: [npm](https://www.npmjs.com/package/react-audio-player)
- reacgt-h5-audio-player: [npm](https://www.npmjs.com/package/react-h5-audio-player)
- react-music-player: [GitHub](https://github.com/lijinke666/react-music-player)
- reaplay: [GitHub](https://github.com/react-player/reaplay)
- react-use-audio-player: [npm](https://www.npmjs.com/package/react-use-audio-player) (while not a player in itself, parts of this may serve as inspiration)

### Motivation

In my app, I want to play both video (so I opened #13196) and audio (so I'm opening this).

I would like to have an audio player component that conforms to Material Design (especially MD3 once that lands).

Besides the default HTML `<audio>` [element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) features, the following should also be supported:

- [Material Icons](https://mui.com/material-ui/material-icons/) should be used for the individual controls (through [Icon Buttons](https://mui.com/material-ui/react-button/#icon-button)?).
- The individual controls themselves should be provided as individual options, and their order should be taken into account for maximum customizability.
- Support custom controls (along with custom icons). _Side note: I intend on integrating these custom functionalities with [howler.js](https://github.com/goldfire/howler.js#documentation) (an amazing library) to edit the sound in-place. The UX would be very smooth if this will be possible._
- The audio progress bar could either be based on the [Slider](https://mui.com/material-ui/react-slider/), the [Linear Progress](https://mui.com/material-ui/react-progress/#linear) or the progress bar seen in the video component from the MD3 documentation (see #13196 again). All could be supported for the best customization.

...and, last but not least, the cherry on the cake...

- Optional waveform audio progress bar.

Examples:
![waveform_examples](https://github.com/user-attachments/assets/aa301fd5-5f9e-40a4-a28c-2b07996f7b6c)

This could be done by integrating [wavesurfer.js](https://github.com/katspaugh/wavesurfer.js) (maybe through [wavesurfer-react](https://www.npmjs.com/package/wavesurfer-react)) in the component. However, given that these waveforms can be styled extensively, it may be more appropriate to leverage [Pigment CSS](https://github.com/mui/pigment-css) for better integration in the MUI environment. This would very likely require writing the waveform generator code from scratch. The complexities of this may require breaking the audio progress indicator down into its own separate component. Maybe code from the [Charts components](https://mui.com/x/react-charts/) could be reused here to a great extent.

Writing such a waveform generator from scratch would also allow for the inclusion of functionalities provided by some of the [wavesurfer.js plugins](https://wavesurfer.xyz/#:~:text=%F0%9F%A7%A9-,Plugins,-Regions%0ACreates%20clickable) in the default implementation, and make their visuals conform to Material Design as well. The plugins that could be incorporated like this are: [Regions](https://wavesurfer.xyz/examples/?regions.js), [Hover](https://wavesurfer.xyz/examples/?hover.js), [Envelope](https://wavesurfer.xyz/examples/?envelope.js), [Minimap](https://wavesurfer.xyz/examples/?minimap.js) and [Timeline](https://wavesurfer.xyz/examples/?timeline.js).

Having these features would make Material UI to be more accessible to music mixing/composing applications.

**Search keywords**: audio player players sound music wave form waveform

**Comment by oliviertassinari** [comment]
I'm closing to signal that it's unlikely. Still, the "waiting for upvotes" label is still applied, so up for considerations.
