### ISSUE TITLE
[data grid] Pivoting ETA

### ISSUE THREAD

**Issue by RomanMain** [mui/mui-x#13886]
### The problem in depth

Hello there. I'd like to clarify about the pivot functionality. Can we know the approximate delivery time for this functionality in the stable version? Since Q2 is over, when can we expect it? Thank you!

**Search keywords**: pivot, pivoting
**Order ID**: 82865

**Comment by michelengelen** [comment]
@joserodolfofreitas to answer this one! 🙇🏼

**Comment by joserodolfofreitas** [comment]
Hi @RomanMain, we're aiming for ASAP, but we're polishing pivoting panel UI and docs, and it's likely going to take until the end of August.
Please feel free to check the [preview](https://deploy-preview-9877--material-ui-x.netlify.app/x/react-data-grid/pivoting/) and [leave your feedback](https://github.com/mui/mui-x/pull/9877)!

**Comment by romgrk** [comment]
Subscribe to https://github.com/mui/mui-x/issues/214 for updates.
