### ISSUE TITLE
Pie Chart shows a slice for 0 value whenever the object representing a 0 is last in the array

### ISSUE THREAD

**Issue by rajatmaheshwari2512** [mui/mui-x#13887]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/jolly-tristan-gvxggh, https://codesandbox.io/s/divine-star-h7dn48?file=/src/Demo.tsx

Steps:
1. Set the last value to be 0, https://codesandbox.io/s/jolly-tristan-gvxggh
2. Test with setting anything but the last object value to be 0, https://codesandbox.io/s/divine-star-h7dn48?file=/src/Demo.tsx
3. The first shows a 0 slice while the second doesn't

### Current behavior

The pie chart is inconsistent as the position of the 0 value decides whether a 0 slice would be shown

### Expected behavior

The slice with the value of 0 shouldn't show up at all

**Search keywords**: pie chart

**Comment by alexfauquette** [comment]
The rendered components are correct. It's the SVG rendering that leads to this strange behavior.

If you look at the `<path />` of the main slice, it's the same as the correct one (in the other Demo)

![image](https://github.com/user-attachments/assets/0b8885b0-9fea-4c72-b023-dcdd8bf90b71)

As a proof, you can just remove the `<path/>` of the third slice, and the second one gets ok.
![image](https://github.com/user-attachments/assets/ee675a73-c877-447a-b462-7332f8dbf3cd)


I assume it's the SVG renderer which left some pixels for the empty path.

The only solution is to remove slice with value 0
