### ISSUE TITLE
[charts] BarChart legend overlaps charts area

### ISSUE THREAD

**Issue by ThomasDev28** [mui/mui-x#13898]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to https://mui.com/x/react-charts/bars/#animation
2. Pass ```Number of series``` value to 10
3. Check the second line of the legends

<img width="739" alt="Capture d’écran 2024-07-19 à 10 20 36" src="https://github.com/user-attachments/assets/a6d3e936-dd73-4f1f-a56e-caf7c454aef8">

### Current behavior

Currently the rendering of the component is only suitable for a single caption line no more

### Expected behavior

The rendering of the component should handle the case of a multi-line legend so that the legend does not encroach on the graph. Also being able to define the location of the legend location would be top ( ```'top' | 'bottom' | 'left | 'right'```)

**Search keywords**: @mui/x-charts

**Comment by michelengelen** [comment]
@JCQuintas could you help out here please?
I know that Legend placement could be adjusted, but could not find anything about increasing gap between the chart area and legend!

**Comment by JCQuintas** [comment]
related to this legend issue https://github.com/mui/mui-x/issues/13648

You can use something like `margin={{ top: 100 }}` to add a padding between the chart and legend for now. Though that is not very dynamic, it is the only solution right now.
