### ISSUE TITLE
[Feature Request] ColorPicker Component

### ISSUE THREAD

**Issue by adhbh** [mui/mui-x#13935]
Please try the example here : https://github.com/adhbh/react-color-selector 
This is being developed for an organisation. But can it be added as a new component in material-ui? 
If not this, the material-ui surely needs a ColorPicker component similar to this. 
Suggestions and critiques most welcome.

Here are some other designs: https://dribbble.com/search?q=material+colorpicker

<img width="404" alt="screen shot 2016-03-16 at 9 00 09 pm" src="https://cloud.githubusercontent.com/assets/6566723/14011033/142bd3de-f1c1-11e5-9645-746554c11f66.png">

**Comment by oliviertassinari** [comment]
Duplicate of #12059
