### ISSUE TITLE
[charts] "dataIndex" Property is not available to the "itemContent" Custom Charts Tooltip in an AreaPlot

### ISSUE THREAD

**Issue by halfacandan** [mui/mui-x#13945]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-hydnyg-2wsk15?file=Demo.js

Steps:
1. Create a ResponsiveChartContainer with 2 stacked data series
2. Add an AreaPlot
3. Add a ChartsTooltip with these properties
  - trigger = "item"
  - slots = {{ itemContent: formatTooltip }}
4. Log out the "props" that are sent to the "formatTooltip" function
5. Hover the mouse over either data series in the chart

The dataIndex property is not available. If I stringify the props passed to the "formatTooltip" function (shown below), nothing refers to the value on the x-axis which is being hovered over.

```json
{
    "itemData": {
        "type": "line",
        "seriesId": "auto-generated-id-1"
    },
    "series": {
        "id": "auto-generated-id-1",
        "color": "#2E96FF",
        "label": "set2",
        "type": "line",
        "area": true,
        "stack": "total",
        "data": [
            1,
            2,
            3,
            2,
            1
        ],
        "highlightScope": {
            "highlighted": "item",
            "faded": "global"
        },
        "stackedData": [
            [
                1,
                2
            ],
            [
                2,
                4
            ],
            [
                3,
                6
            ],
            [
                2,
                4
            ],
            [
                1,
                2
            ]
        ]
    },
    "sx": {
        "mx": 2
    },
    "classes": {
        "root": "MuiChartsTooltip-root",
        "table": "MuiChartsTooltip-table",
        "row": "MuiChartsTooltip-row",
        "cell": "MuiChartsTooltip-cell",
        "mark": "MuiChartsTooltip-mark",
        "markCell": "MuiChartsTooltip-markCell",
        "labelCell": "MuiChartsTooltip-labelCell",
        "valueCell": "MuiChartsTooltip-valueCell"
    },
    "ownerState": {}
}
```

**Example code**

```js
import * as React from 'react';
import Box from '@mui/material/Box';
import { ResponsiveChartContainer } from '@mui/x-charts/ResponsiveChartContainer';
import { AreaPlot, MarkPlot } from '@mui/x-charts/LineChart';
import { ChartsTooltip, ChartsXAxis } from '@mui/x-charts';

export default function SwitchSeriesType() {
  const formatTooltip = (props) => {
    console.log(props.dataIndex); // This is the index of the x-axis. It is undefined
    console.log(JSON.stringify(props)); // The props do not contain any reference to which x-axis value is being hovered over
  };

  return (
    <Box sx={{ width: '100%' }}>
      <div>
        <ResponsiveChartContainer
          series={[
            {
              label: 'set1',
              type: 'line',
              area: true,
              stack: 'total',
              data: [1, 2, 3, 2, 1],
              highlightScope: {
                highlighted: 'item',
                faded: 'global',
              },
            },
            {
              label: 'set2',
              type: 'line',
              area: true,
              stack: 'total',
              data: [1, 2, 3, 2, 1],
              highlightScope: {
                highlighted: 'item',
                faded: 'global',
              },
            },
          ]}
          xAxis={[
            {
              data: ['A', 'B', 'C', 'D', 'E'],
              scaleType: 'band',
              id: 'x-axis-id',
            },
          ]}
          height={200}
        >
          <AreaPlot />
          <ChartsXAxis label="X axis" position="bottom" axisId="x-axis-id" />
          <MarkPlot />
          <ChartsTooltip
            trigger="item"
            slots={{ itemContent: formatTooltip }}
          />
        </ResponsiveChartContainer>
      </div>
    </Box>
  );
}
```

### Current behavior

The "dataIndex" property is undefined in the "props" object which is passed to the custom tooltip function

### Expected behavior

The "dataIndex" property should be defined in the "props" object which is passed to the custom tooltip function

### Context

In the Item tooltip, I would like to have an option to visually highlight which of the series is currently hovered over by the user's mouse e.g. with emboldened text while also displaying all of the associated values from the other data series. This gives users a simple visual prompt which is not dependent on colour or pattern.

I have also raised a related feature request for the axisContent property: https://github.com/mui/mui-x/issues/13944

### Your environment

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 22.5.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.113)
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.4
    @mui/material: ^5.16.4 => 5.16.4
    @mui/private-theming:  5.16.4
    @mui/styled-engine:  5.16.4
    @mui/system:  5.16.4
    @mui/types:  7.2.15
    @mui/utils:  5.16.4
    @mui/x-charts: ^7.11.0 => 7.11.0
    @types/react: ^18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.5.3 => 5.5.3

**Search keywords**: ResponsiveChartContainer AreaPlot ChartsTooltip

**Comment by halfacandan** [comment]
Updates my step 3 in the steps to replicate the issue as I was referring to the wrong properties.

**Comment by michelengelen** [comment]
Thanks for raising this @halfacandan ... @JCQuintas could you have a look if we can provide a workaround? Otherwise this seems like an enhancement and can be added to the board.

**Comment by JCQuintas** [comment]
Hi @halfacandan, this is a known issue. You have to hover over the exact "circle mark" to get the `itemData.dataIndex`

Related to https://github.com/mui/mui-x/issues/12840
