### ISSUE TITLE
[pickers] DesktopDateTimePicker not responsive on mobile devices

### ISSUE THREAD

**Issue by devlabpjh** [mui/mui-x#13979]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Import and use the DesktopDatePicker component from Material UI.
2. Open the application on a mobile device or use a mobile device emulator.
3. Observe that the DesktopDatePicker is not responsive or does not display correctly.

### Current behavior

The DesktopDatePicker is not responsive on mobile devices, resulting in a poor user experience.
![image](https://github.com/user-attachments/assets/3e5a773d-b23d-45a9-9069-7f8d9a35e86b)

### Expected behavior

The DesktopDatePicker should adjust its UI to be usable on mobile devices, similar to how the MobileDatePicker behaves.

### Your environment

- Material UI version: [5.16.4]
- React version: [18.2.0]
- Operating session: [Android]
- Browser version: [Chrome 126]

**Search keywords**: DesktopDatePicker

**Search keywords**:

**Comment by arthurbalduini** [comment]
Hello @devlabpjh, 

I see the image you shared shows a `DesktopDateTimePicker` component, I'm renaming the issue for better clarity.

The `DesktopDateTimePicker` assures support for mouse input and is optimized for larger screens. 
Have you considered using the responsive (`DateTimePicker`) or mobile (`MobileDatePicker`) components?
Feel free to share as much info as you wish 🙂

**Comment by devlabpjh** [comment]
Hi @arthurbalduini,

I did try _DateTimePicker_ and _MobileDateTimePicker_ component, and it shows responsively on mobile devices screen. But I prefer digital clock on mobile devices rather than Time Clock, therefore I choose to use _DesktopDateTime_ picker because _DateTimePicker_, and _MobileDateTimePicker_ will automatically turn the time picker to Time Clock. Is there anyway to change the TimeClock to Digital Clock in mobile device?

**Comment by michelengelen** [comment]
Hey @devlabpjh you can choose the time view renderer based on the `viewRenderers` prop. Here is the section of the docs with a demo on how to do that: [Choose time view renderer](https://mui.com/x/react-date-pickers/date-time-picker/#choose-time-view-renderer)

**Comment by devlabpjh** [comment]
Hi @michelengelen, thank you! It works. Please refer the code below for the solution

```
      <DateTimePicker
        label="Select date and time"
        viewRenderers={{
          hours: renderMultiSectionDigitalClockTimeView,
          minutes: renderMultiSectionDigitalClockTimeView,
          seconds: renderMultiSectionDigitalClockTimeView,
        }}
      />
```
