### ISSUE TITLE
[data grid] Add row while filter is active 

### ISSUE THREAD

**Issue by soumya1118** [mui/mui-x#13983]
### Steps to reproduce

Link to live example: (required)

Steps:
1.click on the 3 dots (toolbar) for a column > select filter 
2. Now add a record using crud operations
3. New row does not appear when filter is on

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Datagrid, editing, filter

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by patbeqo** [comment]
+1
