### ISSUE TITLE
[data grid] `onRowSelectionModelChange` firing twice 

### ISSUE THREAD

**Issue by BrennanGlynn** [mui/mui-x#13980]
### Steps to reproduce

[Example Link](https://codesandbox.io/s/holy-sky-fxv86r?file=/src/Demo.js)

Steps:
1. Enable checkbox selection
2. Group rows
3. Override aggregationFunctions
4. Use controlled row selection with onRowSelectionModelChange and rowSelectionModel
5. Attempt to select multiple rows

### Current behavior

Clicking a grouped row results in two calls to onRowSelectionModelChange. The first one comes in as expected with the correct selected rows. The second time in it comes with an empty array.

### Expected behavior

I would expect that onRowSelectionModelChange would only fire once when selecting a grouped row.

### Context

I'm trying to render a component whenever one or more rows are selected. In order to do this I need access to the current selections length. I'm also using grouped rows with custom aggregation functions.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.183
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.17 
    @mui/icons-material: ^5.15.15 => 5.15.17 
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: ^5.15.15 => 5.15.17 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/styled-engine-sc: 6.0.0-alpha.18 => 6.0.0-alpha.18 
    @mui/styles: ^5.15.15 => 5.15.17 
    @mui/system: ^5.15.15 => 5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^7.2.0 => 7.3.2 
    @mui/x-data-grid-generator: ^7.9.0 => 7.9.0 
    @mui/x-data-grid-premium: ^7.7.1 => 7.7.1 
    @mui/x-data-grid-pro:  7.9.0 
    @mui/x-internals:  7.9.0 
    @mui/x-license:  7.9.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react:  18.3.1 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    styled-components: ^6.1.8 => 6.1.10 
```
</details>

**Search keywords**: onRowSelectionModelChange, grouping

**Search keywords**:

**Comment by michelengelen** [comment]
This is because the aggregation functions get spread onto a new object on every render. If you create a stable reference it does not happen anymore:

```diff
-       aggregationFunctions={{
-         ...GRID_AGGREGATION_FUNCTIONS
-       }}
+       aggregationFunctions={GRID_AGGREGATION_FUNCTIONS}
```
