### ISSUE TITLE
[fields] Provide DatePicker option to show the label at the top and the placeholder in the field, while empty and unfocused

### ISSUE THREAD

**Issue by MrChadMWood** [mui/mui-x#13995]
### Search keywords

DatePicker focus placeholder 

### Latest version

- [X] I have tested the latest version

### Summary

Take the following example:

Its a simple date picker for a "Start Date." The application allows updates to existing documents and accepts null values here to indicate that the user wants "No Change" to the start date.
```
import * as React from "react";
import { Dayjs } from "dayjs";
import TextField from "@mui/material/TextField";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";

export default function BasicDatePicker() {
  const [value, setValue] = React.useState<Dayjs | null>(null);

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DatePicker
        label="Start Date"
        value={value}
        onChange={(newValue) => {
          setValue(newValue);
        }}
        renderInput={(params) => (
          <TextField
            {...params}
            inputProps={{
              ...params.inputProps,
              placeholder: "No Change"
            }}
          />
        )}
      />
    </LocalizationProvider>
  );
}
```

**Current behavior:**
Out of focus:
![image](https://github.com/user-attachments/assets/9922549d-9f06-45b7-99b0-3cef68ff1852)

In focus:
![image](https://github.com/user-attachments/assets/7143b143-c001-48b6-a571-174528a180b1)

**Proposed Change:**
I'd like a way to influence the behavior of the date picker so that the "out of focus" state still has the DatePicker `label` at the top of the component, rather than inside the text field. Id also like the text field to display the placeholder while in this state.

The only difference between out of focus versus in focus by default, under this configuration, might be the transition of color from grey to blue.

**Comment by flaviendelangle** [comment]
Hi,

Our Date Picker should have the same behavior as a [TextField](https://mui.com/material-ui/react-text-field/).
Is this something you were able to achieve on the `TextField` and you feel is missing on the Date Picker?
Or is it something you did not try on the `TextField` but would like to have on the Date Picker?
