### ISSUE TITLE
[RFC] Cell mode UI

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#1399]
## Summary 💡

This RFC proposes a discussion on how the cell UI should look when on the view or edit mode.

## Motivation 🔦

1. The new UI introduced by #1321 doesn't look good when editing a cell in the last row:

<img src="https://user-images.githubusercontent.com/42154031/114311295-96405c80-9ac4-11eb-9eee-727e1f67f5fe.png" width="600">

2. Developers are limited to the height of the row when designing components to edit cells. For comparison, the default row height is 52px while the contained variant of a `TextField` is 56px.
3. It's not clear which cells are editable.
4. Users have to learn all the keyboard shortcuts to edit cells.
5. No support for touch devices (?). Using DevTools I can't edit cells by double-tapping them. A long-press might be the way to provide an app like experience.

## Proposed Solution 🧾

Taking as inspiration [this blogpost](https://uxdesign.cc/designing-tables-for-reusability-490a3760533) and the [Admin Columns Pro](https://www.admincolumns.com/inline-editing/) plugin for WordPress, I propose to move the edit cell to a Popover anchored to the view cell. By doing that, developers will be free to use any component without the height limitation. Also, it will be clear for the user which cell he/she is editing. Buttons for save and rollback will be placed to the side of the input. Clicking outside the popover should switch back to the view mode, discarding any changes. 

![image](https://user-images.githubusercontent.com/42154031/114316282-415b1100-9ad9-11eb-9953-3cde4b071a15.png)

To indicate editable cells, a pencil icon could displayed on each cell once the user hovers it. When navigating with the keyboard, the icon should be displayed when the cell is focused. Clicking it should enter the edit mode. On touch devices, this icon should be always visible.

![image](https://user-images.githubusercontent.com/42154031/114316033-276cfe80-9ad8-11eb-93d7-46b0a0c12868.png)

## Unresolved Questions ❓

- How this new UI "talks" with the row editing UI once it's implemented? Should we open a Popover with all inputs side to side or use a Dialog? With a Dialog developers can create another layout specifically for the row editing feature which could be a plus.
- Should the pencil icon be always visible, like in the screenshot above?

**Comment by dtassone** [comment]
For the row editing, I think that opening a dialog or popover is out of the scope of a dataGrid component.
Row editing should be inline editing IMHO.

Also here we are discussing the built-in editing approach only as users can override all these built-in events.

Some thoughts
- having an icon in each editable cell seems a bit overkill, especially when several columns are editable.
- Having row action is great to switch a row in inline editing
- Having an edit button in the toolbar could also work but slower in terms of UX
- Having a context menu or a menu that is displayed on cell focus
![image](https://user-images.githubusercontent.com/936978/114404827-5ce01d80-9ba6-11eb-8a14-8bddd86e4156.png)

- Switch a cell to edit mode on focus could also work well on touch device but would interfere with selection?
- When a cell is editing, having a button to save or cancel changes could work well in touch device
![image](https://user-images.githubusercontent.com/936978/114405043-92850680-9ba6-11eb-8585-165126b9e96c.png)

**Comment by m4theushw** [comment]
> For the row editing, I think that opening a dialog or popover is out of the scope of a dataGrid component.
Row editing should be inline editing IMHO.

I raised the idea of opening a Dialog for row editing because it gives more room. If we move the cell editing to a Popover, developers would no longer have the height limitation. Thus, they might want to use the same cell editing component for row editing.

> having an icon in each editable cell seems a bit overkill, especially when several columns are editable.

I though about showing it only on hover or focus. But what to do on touch devices?

> Switch a cell to edit mode on focus could also work well on touch device but would interfere with selection?

Not just would interfere with the selection but an user could mistakenly touch in a cell and start editing it.

**Comment by oliviertassinari** [comment]
> Motivation 🔦

Thanks for explaining all the problems the current solution has. This is how all RFCs and discussions should start, with a clear description of the problem(s) 👍.

I'm going to only comment on them because it's what probably matters the most. I think that:

1. Would reducing the dimension in edit mode to have some of the shadow self contained inside the cell solve the issue?
2. This is the UX tradeoff of the current solution. I do like how airtable solves this with an extendable pop-up.
3. Maybe this could be solved with a :hover effect?
4. I think that we already solve this primarily by using the same shortcuts as excel, the ones most people already know. And secondarily, by documenting them in the docs.
5. A longtap to start, <kbd>Enter</kbd> or blur to validate and exit, sounds enough.

**Comment by m4theushw** [comment]
> Would reducing the dimension of the cell in edit mode to have some of the shadow self contained inside the cell solve the issue?

This can be fixed removing the `overflow: hidden` added to the `.MuiDataGrid-viewport` div.

> This is the UX tradeoff of the current solution. I do like how airtable solves this with an extendable pop-up.

Interesting. To make something similar, we have to use a Portal to not be cut-out by the `overflow: hidden`.
![image](https://user-images.githubusercontent.com/42154031/114439087-f7d4f980-9b9e-11eb-8442-72bb2242e2f9.png)

> I think that we already solve this primarily by using the same shortcuts as excel, the ones most people already know. And secondarily, by documenting them in the docs.

I wouldn't assume that users will know that the same shortcuts from Excel are available, nor that they'll read the documentation. For someone with familiarity with spreadsheet apps that's acceptable, but I would rather to have buttons onscreen as well to target all audiences.

> A longtap to start, Enter or blur to validate and exit, sounds enough for a touch devices.

This was my idea too.
