### ISSUE TITLE
[data grid] Vertical sticky for column headers in a Data Grid with horizontal scroll

### ISSUE THREAD

**Issue by ternala** [mui/mui-x#13993]
### The problem in depth

How do I implement sticky for column headers in a Data Grid? It is necessary to implement sticking to the upper border of the page during vertical scrolling.

An important point, I have a horizontal scroll inside the DataGrid (element with class MuiDataGrid-virtualScroller)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: scroll horizontal sticky
**Order ID**: 83389

**Comment by michelengelen** [comment]
Hey @ternala ... I am sure that this is not possible atm with the way the sticky behavior is built within the grid container ... @romgrk WDYT?

**Comment by romgrk** [comment]
Not possible, if there's something else to add please continue the discussion in #7588.
