### ISSUE TITLE
Babel Configuration Issue: Optional Chaining Syntax Not Supported in MUI X Charts

### ISSUE THREAD

**Issue by LieuMai** [mui/mui-x#14016]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Install Chart
2. Add example code to create chart
3. Run npm install
4. Run npm start

### Current behavior

./node_modules/@mui/x-charts/esm/BarChart/BarElement.js
SyntaxError: /home/lpmai/app-client/node_modules/@mui/x-charts/esm/BarChart/BarElement.js: Support for the experimental syntax 'optionalChaining' isn't currently enabled (71:20):

  69 |   };
  70 |   const classes = useUtilityClasses(ownerState);
> 71 |   const Bar = slots?.bar ?? BarElementPath;
     |                    ^
  72 |   const barProps = useSlotProps({
  73 |     elementType: Bar,
  74 |     externalSlotProps: slotProps?.bar,

Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation.

### Context

I want to use Chart component but when I run `npm start`, I get the error.
I install Chart follow this document: https://mui.com/x/react-charts/getting-started/#installation

```
import * as React from 'react';
import { BarChart } from '@mui/x-charts/BarChart';

export default function ChartsOverviewDemo() {
  return (
    <BarChart
      series={[
        { data: [35, 44, 24, 34] },
        { data: [51, 6, 49, 30] },
        { data: [15, 25, 30, 50] },
        { data: [60, 50, 15, 25] },
      ]}
      height={290}
      xAxis={[{ data: ['Q1', 'Q2', 'Q3', 'Q4'], scaleType: 'band' }]}
      margin={{ top: 10, bottom: 30, left: 40, right: 10 }}
    />
  );
}
```

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.182
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.5 
    @mui/material: ^5.16.5 => 5.16.5 
    @mui/private-theming:  5.16.5 
    @mui/styled-engine:  5.16.4 
    @mui/system:  5.16.5 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.5 
    @mui/x-charts: ^7.11.1 => 7.11.1 
    @types/react:  16.8.23 
    react: ^16.12.0 => 16.12.0 
    react-dom: ^16.12.0 => 16.12.0 
```
</details>

**Search keywords**: chart

**Comment by LukasTy** [comment]
Hello @LieuMai.
Have you seen https://github.com/mui/mui-x/issues/13170#issuecomment-2118648318?
This looks like the same issue—an old development setup incapable of parsing modern syntax. 🙈 
What is your development setup like?

P.S. It looks like you are also on React 16.
You can use it at your own risk as it is not supported according to our peer dependency setup. 😉 
https://github.com/mui/mui-x/blob/3aa3069053520dc95bdd3d5c597d22cd9dbadd24/packages/x-charts/package.json#L60-L61
