### ISSUE TITLE
[charts] PieChart position

### ISSUE THREAD

**Issue by sshologin** [mui/mui-x#14032]
### Steps to reproduce

Link to live example: (required)

### Current behavior

I tried removing `cx`, `cy`, setting width, but it seems that it doesn't work at all. Maybe any props to center `PieChart`?

### Context

Is it possible to make `cx` and `cy` props to be calculated automatically, based on the width of the screen? The problem is that without those props the `PieChart` is not centered in the container

That's what I have now 
![Screenshot_3](https://github.com/user-attachments/assets/3a22a631-60ad-4af2-af2a-d131b613bbc0)

That's how it looks on `1200px`
![Screenshot_4](https://github.com/user-attachments/assets/359a29b2-a9b7-436d-919c-1ecf1b3b42a7)

Without `cx` and `cy` it looks like this
![Screenshot_6](https://github.com/user-attachments/assets/09df1bde-b58d-4457-864b-6f489e221736)

**Search keywords**: piechart

**Comment by michelengelen** [comment]
@JCQuintas could you take this one?

**Comment by JCQuintas** [comment]
Hi @sshologin , could you provide a code example using https://codesandbox.io/ or https://stackblitz.com/ ?

Otherwise you could try removing the margin to center the chart.

```tsx
    <PieChart
      ...
      margin={{ right: 0 }}
    />
```

We also have an issue already that is similar to this. Where we intend to allow positioning the chart in center/left/right. Which could be helpful in the future: https://github.com/mui/mui-x/issues/13787

**Comment by sshologin** [comment]
> Hi @sshologin , could you provide a code example using https://codesandbox.io/ or https://stackblitz.com/ ?
> 
> Otherwise you could try removing the margin to center the chart.
> 
> ```tsx
>     <PieChart
>       ...
>       margin={{ right: 0 }}
>     />
> ```
> 
> We also have an issue already that is similar to this. Where we intend to allow positioning the chart in center/left/right. Which could be helpful in the future: #13787

Seems like it was sort of bug, but I changed nothing and now it works really well, I really don't know what happened
![Screenshot_7](https://github.com/user-attachments/assets/4bc5bccd-436e-4f3e-8aad-b18f4424345b)

Margin right 0 is also good solution for me
````
                        <Box
                            sx={{
                                display: 'flex',
                                flexDirection: 'row',
                            }}
                        >
                            <PieChart
                                slotProps={{
                                    legend: { hidden: true },
                                }}
                                series={[
                                    {
                                        data: investments.map((investment) => ({
                                            id: investment.id,
                                            value: investment.value,
                                            label: investment.label,
                                            color: investment.color,
                                        })),
                                        paddingAngle: 2,
                                        cornerRadius: 5,
                                        highlightScope: {
                                            faded: 'global',
                                            highlighted: 'item',
                                        },
                                        cx: 130,
                                        cy: 100,
                                        innerRadius: 40,
                                        valueFormatter: (params) => {
                                            const percent =
                                                params.value / totalValue;
                                            return `${(percent * 100).toFixed(
                                                1
                                            )}%`;
                                        },
                                    },
                                ]}
                                width={270}
                                height={200}
                            />
                        </Box>
````

**Comment by JCQuintas** [comment]
Glad it worked for you. You can use `fade` and `highlight` instead to get rid of the deprecation warning
