### ISSUE TITLE
[pickers] Change the time tab to render a digital clock just like we have for Date Time Range Picker in mobile

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#14037]
### Latest version

- [X] I have tested the latest version

### Summary

I am trying to implement the StaticDateTimeRangePicker to have a digital clock for the Time tab like below -
![image](https://github.com/user-attachments/assets/8f873564-8ee8-46f1-b989-48e3db8bb50b)

Is it somehow possible to change it using the slots prop(I couldn't find anything)?

Like i see the DateTimeRangePicker does have the digital clock is it possible to have it?

![image](https://github.com/user-attachments/assets/32c35f88-29d0-4a5b-ad2e-8a733d13025f)

 

### Examples

Couldn't find any examples

### Motivation

Trying to find if there can be a feasibility for the given design.

**Search keywords**: StaticDateTimePicker

**Comment by arthurbalduini** [comment]
Hello @noobDev31, you should be able to customize the time view renderer based on the `viewRenderers` prop. You can find more informations about on [this section of our docs](https://mui.com/x/react-date-pickers/date-time-picker/#choose-time-view-renderer)

**Comment by noobDev31** [comment]
thanks @arthurbalduini
