### ISSUE TITLE
[pickers] Expired package version error 

### ISSUE THREAD

**Issue by developervarun** [mui/mui-x#14053]
### Latest version

- [X] I have tested the latest version

### The problem in depth

MUI Support team,

We are getting MUI Expired package version error on [Date Range Component](https://mui.com/x/react-date-pickers/date-range-picker/). 

Please look at the screenshots of our application UI and package.json file, which I've included below.

<img width="381" alt="date-range-component" src="https://github.com/user-attachments/assets/95bd8114-4281-45d4-8a27-cee790afe74d">

<img width="155" alt="Package-lock_MUI-defect" src="https://github.com/user-attachments/assets/18571b89-e2ed-44c3-b859-4cc884711077">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browser: Chrome latest version
```
```
Application: React 16
```
</details>

**Search keywords**: MUI Expired package version error on Date Range Component (PRO)
**Order ID**: 59921

**Comment by developervarun** [comment]
Any luck on this? We are stuck on the production release.

**Comment by michelengelen** [comment]
Hey @developervarun ... i will take a look

**Comment by michelengelen** [comment]
Hey @developervarun 
You have installed a version that is outside of your maintenance plan.
The last main-version you are able to use with your license is [v6.19.4](https://github.com/mui/mui-x/releases/tag/v6.19.4) or the [v7.0.0-beta.2](https://github.com/mui/mui-x/releases/tag/v7.0.0-beta.2) release from the same day.

If you intend to use newer versions you would need to update your license.
