### ISSUE TITLE
[data grid] TreeData `isAutoGenerated` depends on row order

### ISSUE THREAD

**Issue by landism** [mui/mui-x#14068]
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://codesandbox.io/s/solitary-bush-hpgx4v?file=/src/Demo.tsx

Steps:
1. Look at the browser tab.

### Current behavior

There is an "X" in the "Gap" column in the Thomas row (i.e., its GridGroupNode.isAutoGenerated is true).
It does seem to correctly fill in the data for the Thomas row, so maybe it just needs to go back and fix the id / isAutoGenerated field?

### Expected behavior

There is no "X" in the "Gap" column in the Thomas row (i.e., its GridGroupNode.isAutoGenerated is false).

### Context

I'm trying to implement `isGroupExpandedByDefault` for a tree view. The current implementation I have uses its argument's `id` to calculate the node's path.
I have worked around this issue by sorting `rows` by their path length before passing the into `DataGridPro` to ensure that parents appear before children. I'd be happy to hear if there's a better way to go about this!

My goals are 1) remove the workaround I've added to my code and 2) reduce the chances anyone else also has to spend a couple days debugging this behavior. Neither of these is particularly urgent.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 20.13.1 - /opt/homebrew/opt/node@20/bin/node
    npm: 10.5.2 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.88
    Edge: Not Found
    Safari: 16.4
```
</details>

I'm using Electron, not a regular browser, in case that's relevant.

**Search keywords**: isAutoGenerated, isGroupExpandedByDefault, GridGroupNode

**Comment by michelengelen** [comment]
this is indeed strange. Especially since in `isGroupExpandedByDefault` it is set to `true`.
What exactly are you trying to implement though? The functionality should be the same between Grouping and Treedata.

**Comment by vklymchuk** [comment]
I have the same issue and here is an expanded example for better understanding:
[codesandbox project](https://codesandbox.io/p/sandbox/festive-kate-klskrz?file=%2Fsrc%2FDemo.tsx%3A61%2C10)

As you can see in the console log the ID of the node has the wrong value

![image](https://github.com/user-attachments/assets/27b1c473-187f-4cc4-9225-3bb3ac0a24ae)

After sorting the rows array we have this result in the log and the id has the correct value

![image](https://github.com/user-attachments/assets/4f6e828e-a7ee-4b49-8910-e242993ebd06)


I'm using node ID in the isGroupExpandedByDefault for calculating expanded\collapsed rows and controlling them
