### ISSUE TITLE
[data grid] `AutoComplete` in HeaderFilter rerenders when initial input typing

### ISSUE THREAD

**Issue by emenni** [mui/mui-x#14071]
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/rough-browser-cyp6gj

Steps:

1. declare a custom header filter in a datagridpro header filter, it should show declare an Autocomplete as input

2. after rendering the component, start typing any value in the input box. 

### Current behavior

the header filter component rerenders after first word is typed. After this first rerendering, it works as expected

### Expected behavior

to not rerender when the first word is typed.

### Context

I need an datagrid with header filter with AutoComplete search feature

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
eed to install the following packages:
@mui/envinfo@2.0.19
Ok to proceed? (y) y

  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4 
    @emotion/styled: 11.11.5 => 11.11.5 
    @mui/icons-material: 5.15.21 => 5.15.21 
    @mui/material: 5.15.21 => 5.15.21 
    @mui/x-data-grid-pro: 7.8.0 => 7.8.0 
    @types/react: 18.2.38 => 18.2.38 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 4.4.2 => 4.4.2 

npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.8.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
npm notice Run npm install -g npm@10.8.2 to update!
npm notice 
```
</details>

**Search keywords**: datagrid headerfilter autocomplete

**Comment by michelengelen** [comment]
strongly related to #13977 

Please consider the same approach as mentioned in [this comment](https://github.com/mui/mui-x/issues/13977#issuecomment-2253386459).

please try that and get back here if that did not solve your issue.

**Comment by emenni** [comment]
Hi, 

 Thanks for replying. I could not test your proposed solution, but instead I solved it by providing the inputRef to the TextField ref, as I saw in one of the related answer. Thank you very very much
