### ISSUE TITLE
[data grid] I want the cell color to change to light green when pasting data from one cell to another

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#14077]
### Latest version

- [X] I have tested the latest version

### The problem in depth

I want the cell color to change to light green when pasting data from one cell to another, similar to how the color changes when editing a cell.

Here is a screenshot showing the cell color change when editing:

![Screenshot 2024-08-01 181544](https://github.com/user-attachments/assets/aa28e914-4299-4c39-97bd-5c31b59db852)

In this screenshot, when I copy the value 52 and paste it into another cell, I want the pasted cell's color to change in the same way as the cell color changes during editing.

![Screenshot 2024-08-01 181640](https://github.com/user-attachments/assets/5b18a991-0fed-4e82-92a8-d559aaf79ecd)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data, Grid, Premium, Copy, paste, eidt
**Order ID**: 91010

**Comment by michelengelen** [comment]
Hey @mahammahmood you can hook into the `processRowUpdate` function to process any updates happening on the rows.
Here is the [docs section](https://mui.com/x/react-data-grid/clipboard/#persisting-pasted-data) regarding this.
