### ISSUE TITLE
Add Chart components

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#1408]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

An umbrella issue to solve the data visualization problems.

## Examples 🌈

<img width="689" alt="Capture d’écran 2020-09-04 à 13 30 41" src="https://user-images.githubusercontent.com/3165635/92234730-d8604a80-eeb2-11ea-801b-9019e936b189.png">

## Motivation 🔦

The data grid will unlock a lot of interesting new use cases for the library. It should make Material UI resonate better with enterprise users. When it comes to handling a lot of data in an application, charting is the second most important component, after the data grid. I don't think that it's a direction we should take in the near future, it would require to onboard core team members will a different set of skills. However, I think that keeping track of the need for this, from our users (developers) will be interesting.

One of the most asked items in https://mui.com/blog/2020-developer-survey-results/#5-how-can-we-improve-material-ui-for-you.

Related issues:

- [ ] Sparkline #2902 simple data viz for high-density use cases. 
- [ ] Gauge: #2903 simple diagram to display one value in a bounded scale.

## Benchmark

- https://mui-org.notion.site/Chart-component-7b30cff4fdab4d2e8adbe0c796821f45 (public)

## Notion exploration page

https://www.notion.so/mui-org/Charts-component-3e93ffb9a40349e6a1b39ec34fce0775 (private)

## Requests

- https://mui.zendesk.com/agent/tickets/3908

**Comment by edazpotato** [comment]
One of the few downsides that I think MUI has is that it's hard to find a charting library that lets the developers easily customise it enough to make it fit in with the MUI components.
For example, lots of charting libraries have the option of a tooltip appearing when the user hovers their mouse over points/bars/etc in the chart, showing the exact value of that point/bar/whatever. This is a great feature, but when using MUI tooltips elsewhere in the app, the tooltips added by these libraries look out of place. 
If high-quality chart/sparkline components that match the rest of MUI and work with well the theming system were added to MUI X Pro, it would be enough to convince me to buy a Pro licence.

**Comment by tielushko** [comment]
If you guys are considering requests for feature, please add support for columnar data. I would love to be able to give a list of xValues and same sized list of yValues and have them be plotted on the chart 😄

**Comment by kedano** [comment]
> 

This is similar to Kusto right? 

It would be great if MUI supported chart rendering out of the box. Maybe with view integrations from the DataGrid table like columnar data format or Kusto results.

**Comment by tielushko** [comment]
@kedano not sure about Kusto, never worked with it. There is currently a scichart library that supports inserting vector data into the chart. As long as there is an option to move away from record-based data in the charts, it would be a library I would consider using.

**Comment by alexfauquette** [comment]
I think this issue yes because it's about adding charts in general.

For closing the two related issues spark line and gauge, we might way a bit
