### ISSUE TITLE
[tree view] do onContextMenu and scroll TreeItem to container's top position when the children tree height upper than parent container

### ISSUE THREAD

**Issue by 1uciuszzz** [mui/mui-x#14101]
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/muix-simpletreeview-bug-p46mc2

Steps:
1. expand all the children items
2. right click the second child item
3. the child item will scroll to the container's top

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.13.0
    @emotion/styled: ^11.11.0 => 11.13.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.5
    @mui/icons-material: ^5.14.15 => 5.16.5
    @mui/lab: 5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.14 => 5.16.5
    @mui/private-theming:  5.16.5
    @mui/styled-engine:  5.16.4
    @mui/system:  5.16.5
    @mui/types:  7.2.15
    @mui/utils:  5.16.5
    @mui/x-charts: ^7.2.0 => 7.11.1
    @mui/x-data-grid: ^7.2.0 => 7.11.1
    @mui/x-date-pickers: ^7.2.0 => 7.11.1
    @mui/x-internals:  7.11.1
    @mui/x-tree-view: ^7.2.0 => 7.11.1
    @types/react: ^18.2.33 => 18.3.3
    react: ^18.2.0 => 18.3.1
    react-dom: ^18.2.0 => 18.3.1
    typescript: ^5.2.2 => 5.5.4
```
</details>

**Search keywords**: bug

**Comment by michelengelen** [comment]
Thanks for reaching out! To better understand the problem you're facing, could you provide some additional information?

**Detailed Description:**
A more detailed explanation of the issue would be very helpful. What behavior are you expecting, and what's actually happening?

**Minimal Reproduction:**
If possible, creating a stripped-down test case that reproduces the issue would be fantastic. This helps us isolate the problem and diagnose it faster.

**Live Example**:
A live example (e.g., Stackblitz, codesandbox) showcasing the issue would be even better!

We have some resources to help you create a minimal reproduction:

**Support Documentation:**
[Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

---

Here are some additional tips:

**Clean Code:**
Focusing on clean and functional code with minimal dependencies will make it easier to identify the issue.

**Problem Clarification:**
Sometimes, the process of creating a minimal reproduction can even help you clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by 1uciuszzz** [comment]
ok, i change the link to live example, now we have an shared editor. please help fix it

**Comment by michelengelen** [comment]
Hey @1uciuszzz ... now i get it.
You can just use `scrollIntoView` for this purpose:

```tsx
onContextMenu={(e) => {
  e.preventDefault();
  e.stopPropagation();
  e.currentTarget.scrollIntoView({ block: 'start' });
}}
```

This will scroll the element into view and, when possible, also tries to scroll so far that the element will reach the top of the container!

Does this solve your use case?

**Comment by michelengelen** [comment]
One thing you should keep in mind though is that the way you open the contextmenu will now be a bit harder to do as the menu will open at the cursor position and when the element got scrolled away it loses its visual reference to it!

**Comment by 1uciuszzz** [comment]
oh, it is not solved my problem, but thank you, now i change the onContextMenu to onClick, maybe it will be solved in the future.

**Comment by michelengelen** [comment]
what exactly should be solved in the future?

It seems like you did find a solution:
- onClick scrolls the element
- onContextMenu opens the menu

Is there anything we should include?

**Comment by 1uciuszzz** [comment]
no, at the first i want open the menu with onContextMenu, but it scroll the item to top, now i open the menu with onClick.  i hope onContextMenu opens the menu without scroll behavior in the future.❤

**Comment by 1uciuszzz** [comment]
in the CSB, scroll behavior still happen
