### ISSUE TITLE
[charts] Allow passing `BarSeriesType | LineSeriesType` to `axisContent.series` without `getColor`

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#14103]
### Latest version

- [X] I have tested the latest version

### Summary

I have the following component:

```tsx
const yAxis: MakeOptional<AxisConfig<ScaleName, any, ChartsYAxisProps>, 'id'> = {
  id: 'y-axis',
  max: 100,
};

export const MyChart: FC<Props> = (myBarData) => {
  const barSeries: BarSeriesType[] = myBarData.map((data, index) => ({
    type: 'bar',
    data,
    label: getBarLabel(index),
    color: getColor(index),
    getColor: () => getColor(index), // for the tooltip
    stack: '1',
    stackOffset: 'none',
    id: index.toString(),
    valueFormatter: (value) => value + '%',
  }));

  const lineSeries: LineSeriesType = {
    type: 'line',
    data: average(myBarData),
    label: 'Average',
    color: 'blue',
    id: 'line',
    valueFormatter: formatAverage,
  };

  const xAxis: MakeOptional<AxisConfig<'band', any, ChartsXAxisProps>, 'id'> = {
    data: myBarData.map((data) => data.date),
    scaleType: 'band',
    id: 'x-axis',
    categoryGapRatio: 0,
    barGapRatio: 0,
  };

  return (
    <ResponsiveChartContainer series={[...barSeries, lineSeries]} xAxis={[xAxis]} yAxis={[yAxis]}>
      <BarPlot skipAnimation />
      <LinePlot skipAnimation />
      <MarkPlot skipAnimation />
      <ChartsXAxis position="bottom" axisId={xAxis.id} />
      <ChartsYAxis position="left" axisId={yAxis.id} />
      <ChartsTooltip
        slotProps={{
          axisContent: {
            series: [
              ...barSeries,
              { ...lineSeries, getColor: () => 'blue' },
            ] as ChartSeriesDefaultized<'bar' | 'line'>[],
          },
          popper: {
            placement: 'auto-start',
          },
        }}
      />
      <ChartsAxisHighlight x="band" />
    </ResponsiveChartContainer>
  );
};
```

I have problems typing `ChartsTooltip`'s `slotProps.axisContent.series`. 
Over some time, types for this changed 2 or 3 times, and once in a while I need to figure out what am I supposed to be putting here. 

Each time, I have to `ts-ignore` some crazy import. Last time ("@mui/x-date-pickers": "7.7.0") it was `ChartSeriesDefaultized<"bar" | "line">`  from `import type { ChartSeriesDefaultized } from "@mui/x-charts/models/seriesType/config";`

This time ("@mui/x-date-pickers": "7.12.0") it's unexported `ChartSeriesDefaultizedWithColorGetter`. 

Please, make the series prop accept unaltered `SeriesType`s

### Motivation

I'm just trying to declare `BarSeriesType` and `LineSeriesType` and pass them to the `ChartsTooltip`. But they secretly need `getColor` function, which 
(a) duplicates `color` property of the series
(b) if missing, just crashes without any typescript error

I don't want to remove `BarSeriesType` or `LineSeriesType` type declaration from my variables because they help me type the series objects, (like `valueFormatter` function).

I just want to be able to do this: 
`series: [...barSeries, lineSeries]`

**Search keywords**: ChartsTooltip axisContent series type ChartSeriesDefaultized

**Comment by michelengelen** [comment]
Hey @JCQuintas could you help out here? Thanks! 🙇🏼

**Comment by JCQuintas** [comment]
Hi @MonstraG your code doesn't work by simply copy/pasting, so I would have to guess a lot of what you want to do. Can you provide a working example using https://codesandbox.io/ or https://stackblitz.com/ ?

Overall you seem to be trying to use internal API's that you shouldn't be using, though I can't provide a reasonable alternative without a working example of what exactly you want to achieve.

**Comment by MonstraG** [comment]
Sorry, here is complete codesandbox, with all problems I'm facing:

https://codesandbox.io/p/sandbox/winter-sunset-ygvwqw

**Comment by JCQuintas** [comment]
You can check my inputs here:

https://codesandbox.io/p/sandbox/admiring-fast-q72ggn?file=%2Fsrc%2FDemo.tsx%3A85%2C28

I've created https://github.com/mui/mui-x/issues/14112 to address one of the secondary problems you mentioned. 

And you don't need to pass anything to the `ChartsTooltip` component unless you are using a custom one. If you need access to the series for any reason, you can use the `useSeries` hook inside your component, as long as the component is inside the `ResponsiveChartContainer`

**Comment by MonstraG** [comment]
Thanks, I really did not need to pass anything to `ChartsTooltip` after all.

Thanks for the #14112, kinda did not like `xAxis[0].id`, so I'll stay with my version for now.

I think this issue can be closed)
