### ISSUE TITLE
[question] [data-grid] Is it possible to disable column virtualisation independently of row virtualisation?

### ISSUE THREAD

**Issue by theobrasseurbentley** [mui/mui-x#14117]
### Latest version

- [X] I have tested the latest version

### The problem in depth

I am looking at Autosizing with the data-grid and noticed the warning about virtualisation at https://mui.com/x/react-data-grid/column-dimensions/#autosizing

I have also noticed the disableVirtualisation prop https://mui.com/x/api/data-grid/data-grid/#data-grid-prop-disableVirtualization. It will disable both row and column virtualisation.

Is it possible to disable column virtualisation independently of row virtualisation?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: column virtualisation autosizing
**Order ID**: 95099

**Comment by benosmond** [comment]
Being able to disable the virtualisation on each axis independently would be very useful. We have situations where we can have upwards of a thousand rows in a single grid, making row virtualisation very necessary, but only a handful of columns.

**Comment by romgrk** [comment]
It's not necessary to disable it, auto-sizing disables column virtualization while it takes the measures.

We have it here but I don't think there's a good use case for it: https://mui.com/x/api/data-grid/grid-api/#grid-api-prop-unstable_setColumnVirtualization
