### ISSUE TITLE
[tree view] RichTreeViewPro - You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by jensug** [mui/mui-x#14118]
### Steps to reproduce

Link to live example: (required)

Steps:
1. 
2.
3.

### Current behavior

Trying to install RichTreeViewPro.
Using "import { RichTreeViewPro } from '@mui/x-tree-view-pro'" to import it.
Recieving the following error:
"ERROR in ./node_modules/@mui/x-tree-view-pro/src/RichTreeViewPro/index.ts 3:7
Module parse failed: Unexpected token (3:7)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| export * from './RichTreeViewPro';
| export * from './richTreeViewProClasses';
> export type {
|   RichTreeViewProProps,
|   RichTreeViewProPropsBase,"

Followed by a bunch of error from the library code like 
"webpack compiled with 1 error and 1 warning
ERROR in node_modules/@mui/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.itemPlugin.ts:36:36
TS2339: Property 'canItemBeDragged' does not exist on type 'Partial<{}>'.
    34 |         externalEventHandlers,
    35 |       }): UseTreeItem2RootSlotPropsFromItemsReordering => {
  > 36 |         const draggable = instance.canItemBeDragged(itemId);
       |                                    ^^^^^^^^^^^^^^^^
    37 |         if (!draggable) {
    38 |           return {};
    39 |         }"

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Loader RichTreeViewPro

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Stackblit template](https://stackblitz.com/edit/react-c2dxnu?file=Demo.tsx) might be a good starting point.

**Comment by NICEMSO** [comment]
Build Error
Failed to compile

Next.js (14.2.5)
./node_modules/@mui/x-tree-view-pro/src/RichTreeViewPro/index.ts
Module parse failed: Unexpected token (3:7)
| export * from './RichTreeViewPro';
| export * from './richTreeViewProClasses';
> export type {
|   RichTreeViewProProps,
|   RichTreeViewProPropsBase,
This error occurred during the build process and can only be dismissed by fixing the error.

**Comment by jensug** [comment]
> Hi, Thanks for your contribution.
> 
> Could you provide a working reproduction, this [Stackblit template](https://stackblitz.com/edit/react-c2dxnu?file=Demo.tsx) might be a good starting point.

Hi, thanks for responding quicly. 

I was not able to recreate it with the Stackbit template because the RichThreeViewPro requires a pro license here. I will give it a try locally to find possible conflicting libraries.

Also thanks for creating the drag and drop feature. I've been waiting on it all summer as i was considering developing it myself.

**Comment by flaviendelangle** [comment]
> I was not able to recreate it with the Stackbit template because the RichThreeViewPro requires a pro license here.

If you don't provide a license, you will have a watermark and a console error but nothing that should prevent us from reproducing your issue :+1:

**Comment by jensug** [comment]
Late return here, but for some reason it is working fine now. So all is good :)

Thanks!

**Comment by michelengelen** [comment]
Great @jensug ... I'll reclose this then! 👍🏼
