### ISSUE TITLE
[core] Yarn PnP support

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#14114]
## The problem

MUI X packages have transitive peer dependencies: `@emotion/react` and `@emotion/styled`.
They are coming from [`@mui/system`](https://github.com/mui/material-ui/blob/562d6626ad34098a24b223a9ad79d4aa22143a52/packages/mui-system/package.json#L69-L70) and [`@mui/styled-engine`](https://github.com/mui/material-ui/blob/562d6626ad34098a24b223a9ad79d4aa22143a52/packages/mui-styled-engine/package.json#L56-L57).

This causes an issue with Yarn PnP: https://github.com/mui/mui-x/issues/13304
MUI X packages [should declare these peer dependencies for Yarn PnP to work](https://github.com/mui/mui-x/issues/13304#issuecomment-2264537673).
[Related article explaining why](https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0).

### Impacted packages

~All MUI X packages.~ Only Data Grid packages.

## The solution

Adding `@emotion/react` and `@emotion/styled` as optional peer dependencies to each MUI X package.

**Search keywords**:

**Comment by oliviertassinari** [comment]
Looks the same as https://github.com/mui/material-ui/pull/32623
