### ISSUE TITLE
[DataGridPro] Infinite loading onRowsScrollEnd intermittent issue not firing

### ISSUE THREAD

**Issue by eversadi** [mui/mui-x#14116]
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: (required)

https://codesandbox.io/s/s9zvh2?file=/src/Demo.js

video here

- https://www.awesomescreenshot.com/video/30225828?key=db66a35858cb4289fb5b9a044144afb0

Steps:
1. just scroll down to the end of the scroll load the data from the mui example 

### Current behavior

Data Grid onRowsScrollEnd event does not fire , it just stop at the bottom

### Expected behavior

Data Grid onRowsScrollEnd  should always fire once reach the end of the scrollbar

### Context

I wan't to have a table that can loads a data when the scroll position is at the bottom
[icy-paper-s9zvh2 - CodeSandbox.webm](https://github.com/user-attachments/assets/81b9b206-c2e2-437c-b9c1-1c11371bb6de)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: onRowsScrollEnd
**Order ID**: eversadi-1

**Comment by arminmeh** [comment]
Can confirm on [our own example](https://mui.com/x/react-data-grid/row-updates/#infinite-loading) as well.

Thanks for reporting @eversadi

**Comment by lukedukeus** [comment]
Just ran into this issue. I found that using `disableVirtualization` got rid of it, but then everything renders much slower. I found that I was also much more likely to run into this if I had complex logic for my `renderCell` method.

**Comment by arminmeh** [comment]
thanks @lukedukeus 
this helps reproduce the issue

**Comment by kfowler1337** [comment]
How do I know when this is released? Hit the same issue @arminmeh

**Comment by arminmeh** [comment]
@kfowler1337 
It has been released in [7.19.0](https://github.com/mui/mui-x/releases/tag/v7.19.0)
Are you using that version?

**Comment by efotin** [comment]
Will it be released for v6 premium?

**Comment by arminmeh** [comment]
@efotin 
Infinite loading was [re-worked for version 7](https://github.com/mui/mui-x/pull/8672)
so the change made here cannot be ported back.
since it is not a regression or a security issue, there is no plan to fix this on v6
