### ISSUE TITLE
[data grid] Can I add a custom header/footer to the print export in DataGrid Premium?

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#14133]
### The problem in depth

Can I add a custom header or footer to my DataGrid Premium print export?

Here is the live demo:
[Demo](https://stackblitz.com/edit/react-wgnwah?file=Demo.tsx)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data ,Grid , Premium, GridToolbarExport, GridPrintExportOptions
**Order ID**: 91010

**Comment by michelengelen** [comment]
You can customize the header (as you did in your example for the excel export) with the CSS `@media(print)` directive. It could look something like this:

```tsx
<DataGrid
  sx={{
    '@media print': {
      [`& .${gridClasses.columnHeader}`]: {
        backgroundColor: '#002672',
        color: '#FFFFFF',
      },
    },
  }}
  {/* ... */}
/>
```

Here is the section explaining it in the docs: [Modify the data grid style](https://mui.com/x/react-data-grid/export/#modify-the-data-grid-style)

Correct me if I am wrong @mui/xgrid that we currently cannot add custom elements to the print export, right?
