### ISSUE TITLE
[charts] Setting baseline for Area Chart

### ISSUE THREAD

**Issue by wildcat-cs** [mui/mui-x#14145]
### The problem in depth

I am trying to create an area chart that has a configurable baseline below 0 such that everything above the configured baseline will be shaded in as part of the "area".  I've searched the documentation and cannot find any way to set the baseline.

### Your environment

**Search keywords**: Area Chart baseline
**Order ID**: 85440

**Comment by michelengelen** [comment]
@JCQuintas can you take a look at this please?
Can we handle this as a feature request or maybe provide a workaround with combined charts?

**Comment by JCQuintas** [comment]
Yup this seems a bug 😅

**Comment by JCQuintas** [comment]
Hum, maybe it is a feature request instead. Having negative values is supposed to show something like:

![Screenshot 2024-08-09 at 13 44 16](https://github.com/user-attachments/assets/d36574f1-e74e-4a21-aabd-cf84d09cb7c3)

So we should probably add a `baseline` prop instead to control this. 🤔

**Comment by wildcat-cs** [comment]
Want to thank you both for getting on this so quickly.  And agree it's a feature not a bug, but I think a very useful feature in a few certain cases.

Thanks again.
