### ISSUE TITLE
[data grid] Is there a way to add borders to column groups?

### ISSUE THREAD

**Issue by genepaul** [mui/mui-x#14144]
### The problem in depth

I'm using DataGrid column grouping, and I'd like to put borders only on the outside of column groups, not between columns within groups. Here's a screenshot of how I have this in another table (not MUI DataGrid):

![image](https://github.com/user-attachments/assets/90688a69-fdf6-4e6e-8b4c-5c5d48c26ce3)

I tried to do this with DataGrid but had some problems. I can put borders on the  outside of the column group headings  (`filledGroup`), but figuring out which subcolumn is the first and last in its group is not that easy. I can inspect the `columnGroupingModel` on initial render, but if the user reorders columns I can't seem to get that to update.

Here's a codesandbox with setting the initial render:

https://codesandbox.io/p/sandbox/prod-violet-g4zqhl

I tried adding a `useEffect` that updates those class names when column order changes, but that started getting into issues of updating the `columns` array which was causing other difficulties. 

Any help  with this would be greatly appreciated.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
   System:
    OS: macOS 14.5
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.8.2 - ~/Developer/component-library/node_modules/.bin/npm
    pnpm: 9.6.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Edge: 127.0.2651.86
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.7.1 => 11.13.0 
    @emotion/styled: ^11.6.0 => 11.13.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.6 
    @mui/icons-material: ^5.11.16 => 5.16.6 
    @mui/lab: 5.0.0-alpha.173 => 5.0.0-alpha.173 
    @mui/material: ^5.16.5 => 5.16.6 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.6 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.12.0 
    @mui/x-data-grid-premium: ^7.4.0 => 7.12.0 
    @mui/x-data-grid-pro:  7.12.0 
    @mui/x-date-pickers: ^7.0.0 => 7.12.0 
    @mui/x-date-pickers-pro: ^7.0.0 => 7.12.0 
    @mui/x-internals:  7.12.0 
    @mui/x-license: ^7.0.0 => 7.12.0 
    @types/react: ^18.2.79 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: ^5.2.2 => 5.5.4
```
</details>

**Search keywords**: column group borders
**Order ID**: 0332927583

**Comment by KenanYusuf** [comment]
@genepaul I don't think there is a nice way to it with borders currently. We could look at adding some additional classes to column headers to help identify the start and end of groups if this is a popular request.

A quick and dirty solution I found using an after element: https://codesandbox.io/p/sandbox/thirsty-shamir-fjlmt3. There are likely limitations to this approach, though.

**Comment by michelengelen** [comment]
@KenanYusuf I know that @romgrk is probably against such an approach, as he is trying to reduce the amount of classes in the grid atm fro performance reasons ... But this can be further discussed in this issue 👍🏼

**Comment by romgrk** [comment]
I don't mind for headers, there's not that many of them displayed at once, unlike cells.

**Comment by genepaul** [comment]
@KenanYusuf - that example is great, except that I need the borders on the cells as well, and there doesn't seem to be a way  via CSS to differentiate cells that are in grouped columns from cells that aren't. 

Some class names would be helpful, but I realize that can pollute the DOM.

**Comment by romgrk** [comment]
I didn't realize you also wanted the borders in the cells, in that case I'd be a bit hesitatnt to add it in general. There can be hundreds of cells at once on screen, I would prefer to not add performance costs for those elements.

I realize it's a bit inconvenient just for styling, but I would suggest to add borders via javascript like you seem to have tried. The codesandbox you provided is just the generic template, if you can update it with what you already have we can assist with the implementation.

**Comment by genepaul** [comment]
So after looking at this again, I realized I could use `getCellClassName` and the `api` that is passed in to get what I need. Here's an updated sandbox that edits what @KenanYusuf provided and uses `getCellClassName` to determine the column position:

https://codesandbox.io/p/sandbox/14144-column-group-horizontal-borders-forked-9ctmlf

It feels a little hacky, but it seems to be the only option right now. This might be a performance issue so I'll probably do some testing with it, but it's the closest I've gotten to what I want.

Incidentally, it seems the TS types are incorrect. GridCellParams doesn't include `api` on it, but it seems that it actually is passed to it. Should I submit a separate issue for that?

**Comment by KenanYusuf** [comment]
> It feels a little hacky, but it seems to be the only option right now

Not ideal, but glad you found something that is working.

> Incidentally, it seems the TS types are incorrect. GridCellParams doesn't include `api` on it, but it seems that it actually is passed to it. Should I submit a separate issue for that?

You're right, looks like `api` is missing from that interface. A separate issue would be great, thanks @genepaul.

**Comment by michelengelen** [comment]
Hey @genepaul ... if you found a solution for this that suits your needs feel free to close this issue. Also if you want you can open a separate issue for the missing `api`, and if you don't just ping me ... i'll open it then! Thanks!

**Comment by genepaul** [comment]
Thanks for the help on this! I created #14190 for the GridCellParams issue.
