### ISSUE TITLE
[Your MUI X license key format isn't valid] 

### ISSUE THREAD

**Issue by Spikus** [mui/mui-x#14152]
### The problem in depth

Hello on run DataGridPremium i go error.

MUI X: Invalid license key.

Your MUI X license key format isn't valid. It could be because the license key is missing a character or has a typo.

To solve the issue, you need to double check that `setLicenseKey()` is called with the right argument
Please check the license key installation https://mui.com/r/x-license-key-installation.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Invalid license key.
**Order ID**: 9446

**Comment by michelengelen** [comment]
Could you please open a ticket regarding this in our [support tool](https://support.mui.com/hc/en-us/requests/new?tf_360023797420=mui_x&_gl=1*xn9vd9*_gcl_au*MTQ3MzQyNjQ1MC4xNzIyNjA5Nzkz*_ga*MjAyNzQ0NTg5OC4xNjkzODA4MjI1*_ga_5NXDQLC2ZK*MTcyMzIwODc5My41MjcuMS4xNzIzMjA4ODE4LjM1LjAuMA..)?
Thanks!
