### ISSUE TITLE
[charts] How do I turn off tooltip animations?

### ISSUE THREAD

**Issue by svidskiy** [mui/mui-x#14156]
### The problem in depth

How to make the tooltip not transition smoothly but appear next to the point? It should be fixed

https://github.com/user-attachments/assets/e1810e74-7a3a-42be-80a2-14e5f2cbde9f

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 11 10.0.22621
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.6 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.17 
    @mui/icons-material: ^5.15.17 => 5.15.17 
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.17 => 5.15.17
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.12.1 => 7.12.1
    @mui/x-charts-pro: ^7.0.0-alpha.0 => 7.0.0-alpha.0
    @mui/x-charts-vendor:  7.12.1
    @mui/x-data-grid:  7.3.2
    @mui/x-data-grid-pro: ^7.3.2 => 7.3.2
    @mui/x-date-pickers: ^7.4.0 => 7.4.0
    @mui/x-date-pickers-pro: ^7.4.0 => 7.4.0
    @mui/x-license:  7.2.0
    @types/react: ^18.2.66 => 18.2.79
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.4.5
```
</details>

**Search keywords**: charts tooltip
**Order ID**: 89766

**Comment by alexfauquette** [comment]
We could add to the Tooltip props a `anchorEl: 'mouse' | 'axis' | 'item'` plus the `placement: 'right-start' | 'top' | .....` to allow customizing this behavior

**Comment by svidskiy** [comment]
> We could add to the Tooltip props a plus the to allow customizing this behavior`anchorEl: 'mouse' | 'axis' | 'item'``placement: 'right-start' | 'top' | .....`

That would be great, because I believe it's a useful feature to pin tooltip (popper) near the point

**Comment by alexfauquette** [comment]
> I believe it's a useful feature to pin tooltip (popper) near the point

This specific behavior could not be done, because in you screenshot, it's an axis tooltip. So there are multiple points. So the tooltip would either bat at the dot for the bottom of the chart

**Comment by svidskiy** [comment]
> > I believe it's a useful feature to pin tooltip (popper) near the point
> 
> This specific behavior could not be done, because in you screenshot, it's an axis tooltip. So there are multiple points. So the tooltip would either bat at the dot for the bottom of the chart

Here's a vivid example of what I'm going to talk about. Is there a possibility to implement identical logic without implementing custom logic?

https://github.com/user-attachments/assets/762a0919-05d6-40c9-97c5-8be79965e9f9

**Comment by alexfauquette** [comment]
Currently, that would be somewhat hard. You would need to use the axis values, to get the closes on to the mouse position to then gat the coordinate by using axis scale. Quite a lot of computation
