### ISSUE TITLE
[charts] Customising sparkline highlight point

### ISSUE THREAD

**Issue by Manikandasubramani** [mui/mui-x#14168]
### Steps to reproduce

I have a sparkline chart from MUI for react as follows
```
import * as React from 'react';
import Stack from '@mui/material/Stack';
import Box from '@mui/material/Box';
import { SparkLineChart } from '@mui/x-charts/SparkLineChart';

export default function BasicSparkLine() {
  return (
    <Stack direction="row" sx={{ width: '100%' }}>
      <Box sx={{ flexGrow: 1 }}>
            <SparkLineChart
              data={[10, 20 , 30, 40, 0, -10, 25]}
              xAxis={{
                scaleType: 'point',
                data: [1, 2, 3, 4, 5, 6, 7, 8],
              }}
              height={100}
              width={600}
              showHighlight
            />
      </Box>
    </Stack>
  );
}
```

### Current behavior

If "showHighlight" is set to true, on hover of the sparkline chart, we can see a highlight coming on the chart on each xaxis point.

### Expected behavior

Q1: Is there a way to have those highlighted points always shown ?

Q2: IS there a possibility to show the highlighted points in different colors based on the xaxis value of that exact point

### Context

We are trying to have the highlighted datapoint always in the sparkline chart and as well to give a color different of each data point based on the data point value.. for ex., the highlighted data point in green is the y-axis value is >0 or in red if the value is <=0

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DefaultChartsAxisTooltipContent

**Comment by alexfauquette** [comment]
I'm not sure to fully get your expected behavior

By reusing some hooks provided to [create custom components](https://mui.com/x/react-charts/components/) I created an `<Indicator />` component that add a circle to your chart

https://codesandbox.io/s/awesome-dust-vpcqkk?file=/src/Demo.tsx

![image](https://github.com/user-attachments/assets/ddd0c567-58b2-49d0-8b3f-56f913845118)


Does it solve your issue?

**Comment by Manikandasubramani** [comment]
Yes, this is what i need.

But seeing the sandbox, you had given 2 <Indicators> is there a way to dynamically do it based on the data array which is being passed ?

**Comment by Manikandasubramani** [comment]
Hey @alexfauquette , I am getting this error "**export 'unstable_useLineSeries' (imported as 'unstable_useLineSeries') was not found in '@mui/x-charts/hooks' (possible exports: getValueToPositionMapper, useDrawingArea, useXScale, useYScale)**"., is this because of a version mismatch ?  My version is "**@mui/x-charts: ^6.19.5**"

**Comment by alexfauquette** [comment]
Two solutions:

- You update to the latest v7. The charts have nearly no breaking changes between v6 and v7: https://mui.com/x/migration/migration-charts-v6/
- You don't use this hook, and then you have to directly provide the y-value

**Comment by Manikandasubramani** [comment]
#2 worked out great.. Thank you very much.. :)

**Comment by soetji** [comment]
> Two solutions:
> 
> * You update to the latest v7. The charts have nearly no breaking changes between v6 and v7: https://mui.com/x/migration/migration-charts-v6/
> * You don't use this hook, and then you have to directly provide the y-value

Can you provide a working example for this in v8 without the hook?

**Comment by alexfauquette** [comment]
If that's not what you're looking for, please open a distinct issue


```ts
function Indicator() {
  const indexToHighlight = 3;
  const xAxis = useXAxis();
  const yAxis = useYAxis();

  const series = useLineSeries();

  const seriesData = series[0].data;
  const x = xAxis.scale(xAxis.data![indexToHighlight]) ?? 0;
  const y = yAxis.scale(seriesData[indexToHighlight]!) ?? 0;

  return <circle cx={x} cy={y} r={5} fill="red" />;
}
```

**Comment by soetji** [comment]
@alexfauquette Thanks for the example. I was wondering what you meant with the 2nd solution above. You said, "You don't use this hook, and then you have to directly provide the y-value"
