### ISSUE TITLE
[data grid] `onCellSelectionModelChange` not triggered when ctrl+dragging to select additional cells

### ISSUE THREAD

**Issue by skjalghodneland** [mui/mui-x#14184]
### Steps to reproduce

Link to live example: https://codesandbox.io/s/zealous-allen-jnpptr?file=/src/Demo.tsx
(This can also be replicated in the official example from [mui docs](https://mui.com/x/react-data-grid/cell-selection/). This sandbox is a slightly changed version of the one from mui docs that outputs the count of selected cells to make it easier to spot the issue)

Steps:
1. Enable cellSelection
(optional) Add some logic (for example logging) in onCellSelectionModelChange to see the issue
2. Select a singular cell, or a group of cells by clicking and dragging across multiple cells. You will see this get updated in your onCellSelectionModelChange.
3. Hold ctrl and select another group of cells by clicking and dragging across multiple cells
As you will see from onCellSelectionModelChange the selected cells will not be updated when you do step 3. If you proceed to select a singular additional cell by holding ctrl and clicking on a single cell the selected cells will update and contain all the cells you selected in step 2 and 3. 

Selecting one cell:
![image](https://github.com/user-attachments/assets/3f94dd94-9766-4db7-a216-1b66b8a21173)

Selecting multiple additional cells by ctrl+dragging:
![image](https://github.com/user-attachments/assets/dcbe23a9-5695-4737-ab52-fad07672bc42)
Note that the count has not updated.

Selecting one singular additional cell with ctrl+click, now the count updates
![image](https://github.com/user-attachments/assets/3c611be1-d43e-4dc6-baf9-e9bb81388bbd)

### Current behavior

onCellSelectionModelChange does not trigger when releasing the mouse after ctrl+drag selecting more cells after initial selection.

### Expected behavior

onCellSelectionModelChange should trigger when releasing the mouse after ctrl+drag selecting more cells, similar to how it does on the initial selection and when ctrl+clicking a singular cell. 

### Context

We wish to allow our users to select multiple cells and perform actions on these cells, and with this bug this process is not natural. In other software this UX is fairly standard, and the bug that the onCellSelectionModelChange does not trigger when using the grid in this way causes a disconnect between what is visually represented to the user as selected cells and what our code is aware of.

### Your environment

I'm not able to run this command on the sandbox, but the problem exists there as well where all the versions are latest. Below is from the software where we use this. Tested using Chrome.
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.15
    @mui/material: ^5.15.15 => 5.15.15
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid:  7.3.1
    @mui/x-data-grid-premium: ^7.3.1 => 7.3.1
    @mui/x-data-grid-pro:  7.3.1
    @mui/x-license: ^7.2.0 => 7.2.0
    @types/react: ^18.2.79 => 18.2.79
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.4.2 => 5.4.4
```
</details>

**Search keywords**: cellselection multiple cells onCellSelectionModelChange not triggering selectionmodel not updating
**Order ID**: 89129

**Comment by arminmeh** [comment]
Hi @skjalghodneland 
Thanks for reporting this.

I have made a PR to fix this issue

**Comment by skjalghodneland** [comment]
Thank you @arminmeh this seems to work perfectly!
How long do you think it will take for this to get merged to production? We need to decide if we want to push cell selection with this bug to our production code or wait for the fixed version to be available.

**Comment by arminmeh** [comment]
@skjalghodneland I have requested more people for a review
data grid is released every week (mostly on Thursday)

**Comment by skjalghodneland** [comment]
No chance this makes it in time for this week's release then since the PR has still not been approved? @arminmeh

**Comment by arminmeh** [comment]
@skjalghodneland the PR has been approved and should be merged once the build passes. This means that the fix will be released this week.

**Comment by skjalghodneland** [comment]
Thank you so much @arminmeh! Really appreciate the fast turnaround time on this, its very reassuring to know that reporting bugs here leads to a swift response from you and the rest of the mui-x team. Hope you have a great rest of your week!

**Comment by efotin** [comment]
> @skjalghodneland the PR has been approved and should be merged once the build passes. This means that the fix will be released this week.

Can it be merged to V6 premium?

**Comment by arminmeh** [comment]
@efotin 
I will soon make a PR to fix the same issue for v6
