### ISSUE TITLE
[data grid] Select/deselect all is not working as expected in data grid premium with row grouping

### ISSUE THREAD

**Issue by santhoshsis** [mui/mui-x#14196]
### The problem in depth

When we are using the select all and deselect all for the custom implemention of checkbox column for datagridpremium rowgrouping feature which was provided as a resolution for the issue ([data grid] Group Item With Checkbox Select Children #13277) https://stackblitz.com/edit/react-mqcgmm-qifpzb?file=Demo.tsx. Check by select all and deselect all feature it is not working as intended.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: select all and deselect all
**Order ID**: 88959

**Comment by michelengelen** [comment]
This will get implemented with the new release.
#13757 is targeting this exact behavior.
Would you be able to update to the latest version when we release tomorrow or friday?

**Comment by santhoshsis** [comment]
Sure, Can you please keep me posted when ever the new version is launched. Are there any specific steps that needs to be followed? @michelengelen

**Comment by michelengelen** [comment]
The new release should happen either today or tomorrow.
As long as you are on a pretty recent version there shouldn't be anything you need to take into account.
If you need help with the upgrade we can assist you once you attempt to do so.
