### ISSUE TITLE
[data grid] How to use `renderCell` on an actions column type

### ISSUE THREAD

**Issue by sydneyjodon-wk** [mui/mui-x#14194]
### The problem in depth

Hello 👋 

I'm trying to use `renderCell` on an `'actions'` column, but it doesn't seem to render the actions correctly (see [codesandbox example](https://codesandbox.io/p/sandbox/datagrid-action-col-type-with-rendercell-lkljqf?file=%2Fsrc%2FDemo.tsx)):

![Screenshot 2024-08-13 at 10 00 52 AM](https://github.com/user-attachments/assets/cb193ef4-601c-44e6-a415-24704234d914)

I used `params.colDef.getActions(params)`, but also tried just rendering `GridActionsCellItem`s in `renderCell` with the same result - is there a way to get `renderCell` to work without breaking the existing actions so that you can add more components in the cell with the actions?

Thank you!

### Your environment

See codesandbox: https://codesandbox.io/p/sandbox/datagrid-action-col-type-with-rendercell-lkljqf?file=%2Fsrc%2FDemo.tsx

**Search keywords**: getActions, renderCell
**Order ID**: 82849

**Comment by michelengelen** [comment]
Hi @sydneyjodon-wk ... you can just use the `GridActionsCell` component in your `renderCell`:

```tsx
renderCell: (params) => (
  <Stack>
    <GridActionsCell {...params} />
    <Typography>some text</Typography>
  </Stack>
),
```

This will render the actions as if it were just the default actions cell!
Does that fix your use case?

**Comment by sydneyjodon-wk** [comment]
Ahh yes! That's perfect! Thank you so much!
