### ISSUE TITLE
[pickers] How to extend type for `slotProps`?

### ISSUE THREAD

**Issue by svidskiy** [mui/mui-x#14217]
### The problem in depth

How can I extend the type for **field** inside **slotProps** and add a custom prop (**DatePicker**)? For example, **DataGrid** has specialized types that can be extended through declare:

```
declare module '@mui/x-data-grid' {
    interface ToolbarPropsOverrides {
        // Custom props here
    }
}
```

But there doesn’t seem to be anything similar for **DatePicker**.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.17 
    @mui/icons-material: ^5.15.17 => 5.15.17 
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: ^5.15.17 => 5.15.17 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.7 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-charts: ^7.12.1 => 7.12.1 
    @mui/x-charts-vendor:  7.12.1 
    @mui/x-data-grid:  7.3.2 
    @mui/x-data-grid-pro: ^7.3.2 => 7.3.2 
    @mui/x-date-pickers: ^7.4.0 => 7.4.0 
    @mui/x-date-pickers-pro: ^7.4.0 => 7.4.0 
    @mui/x-license:  7.2.0 
    @types/react: ^18.2.66 => 18.2.79 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.4.5
```
</details>

**Search keywords**: date pickers, pickers
**Order ID**: 89766

**Comment by michelengelen** [comment]
I am not sure if we support type augmentation currently.
@LukasTy is there a way workaround for that?

**Comment by LukasTy** [comment]
Currently, there is no way to provide type overrides for Pickers.
There is an issue (https://github.com/mui/mui-x/issues/9775) for adding the same option to the Pickers package.

In the meantime, you can try and see if overriding the original field prop type helps you achieve the desired result.
```ts
declare module '@mui/x-date-pickers' {
    interface DateFieldProps {
      myProp?: string;
    }
}
```
I'm closing the issue as a duplicate. 😉
