### ISSUE TITLE
[data grid] Copy & Paste on Cells using localize keyboard

### ISSUE THREAD

**Issue by rotembarsela** [mui/mui-x#14219]
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-data-grid/clipboard/

Steps:
1. Copy&Paste working using only English localization Keyboard
2. Using Hebrew for example will not work, because the function is looking for the "v" key, instead of the KeyC
3. inside packages\x-data-grid-premium\src\hooks\features\clipboard,
handleCopy func:
https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts
4. same thing for the paste shortcut,
![image](https://github.com/user-attachments/assets/246f041b-01aa-4bbe-b55d-0e03ee212157)

### Current behavior

English language localization - Copy&Paste work
Changing to other Language (Computer) - Copy&Paste fail

### Expected behavior

Copy&Paste work on all localizations

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: copy paste copy&paste keyboard cell cells x-data-grid-premium

**Comment by michelengelen** [comment]
Thanks for raising this and your PR.
We appreciate it when the community is actionable! 🙇🏼 

I left comments on the PR, but will leave it to the team to approve! 👍🏼

**Comment by oliviertassinari** [comment]
Oh wow, so https://github.com/mui/mui-x/pull/3660/files#r793084149 again?

**Comment by rotembarsela** [comment]
> What OS are you using? What are the properties values of `event` when you press the copy shortcut?

Tested that on Windows 11 and 10,
Keyboard layout: ENG/עבר,
Screenshot: (First is CTRL+C on ENG layout, second CTRL+C on HEB layout),
you can see that on the second attempt it is false instead of true, because it check the C key value, which is 'ב' on HEB layout
![image](https://github.com/user-attachments/assets/38b3f374-7e94-4463-b09c-c10cef26902e)
