### ISSUE TITLE
[data grid] Apply page level filtering once all filter are selected and click on button like 'Apply Filters'

### ISSUE THREAD

**Issue by rajeshreddy-bheemireddy** [mui/mui-x#14215]
### The problem in depth

1. I am currently trying to implement page-level filtering on DataGridPremium, I don't want the filtering to take place immediately once the user changes any filter options.
2.  I am already using CustomFilterPanel(which uses `GridFilterPanel`), and I am trying to find a way to implement this, I want the filtering to happen once the user clicks the `Apply Filters` button.
3.  I am ok to set the `filterMode='server' `, but I need a way to use the capability of the default Datagrid filtering once I click on the `Apply Filters` button.

I see the issue has already been raised as a part of this [link](https://github.com/mui/mui-x/issues/10938), can you please provide any workaround for this?

![filters](https://github.com/user-attachments/assets/649d288f-d42b-417b-a32b-c7394fad5ccd)
 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
    Using Chrome browser.

  Output from `npx @mui/envinfo` goes here.

  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.119
    Edge: 127.0.2651.98
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.9.0 => 11.11.4 
    @emotion/styled: ^11.8.1 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.15 
    @mui/icons-material: ^5.8.0 => 5.15.15 
    @mui/lab:  5.0.0-alpha.170 
    @mui/material: ^5.10.17 => 5.15.15 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/styles:  5.11.1 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  6.19.11 
    @mui/x-data-grid-premium: ^6.16.2 => 6.19.11 
    @mui/x-data-grid-pro: ^6.3.0 => 6.19.11 
    @mui/x-license-pro: ^6.0.4 => 6.10.2 
    @mui/x-tree-view: ^7.4.0 => 7.4.0 
    @types/react: ^17.0.0 => 17.0.80 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.0 => 5.3.11 
    typescript: ^3.9.3 => 3.9.10 

```
</details>

**Search keywords**: filter panel, datagrid, GridPanel filter, Apply Filters, Submit Filters, applyFilters
**Order ID**: 75705

**Comment by michelengelen** [comment]
Hey @rajeshreddy-bheemireddy ... as you already stated this issue has already been raised in #10938 

As stated by @cherniavskii [here](https://github.com/mui/mui-x/issues/10938#issuecomment-2072339569) building a custom filterpanel is very hard.

For these reasons I will close this as a duplicate
