### ISSUE TITLE
[x-license] @mui/x-license 7.12.1 not available

### ISSUE THREAD

**Issue by teddis** [mui/mui-x#14212]
### Steps to reproduce

Link to live example: (required)
I'm sorry, despite your requirement here, I'm in development on this version and can't get the @mui/x-license package to update to 7.12.1 to match @mui/x-data-grid-pro of same version.

Steps:
1. I update my package.json to reference 7.12.1 
2. Yarn install will not resolve @mui/x-license. It presents a form to pick a version only 7.12.0 is shown

### Context

I'm trying to upgrade to 7.12.1 Mui data-grid-pro

### Your environment

 System:
    OS: macOS 14.5
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.101
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @mui/private-theming:  5.16.4 
    @mui/styled-engine:  5.16.4 
    @mui/system: ^5.16.4 => 5.16.4 
    @mui/utils: ^5.16.4 => 5.16.4 

**Search keywords**: @mui/x-license 7.12.1
**Order ID**: 91768

**Comment by LukasTy** [comment]
Hello @teddis, could you clarify why you expect the `@mui/x-license` package to be on `v7.12.1`? 🤔 
Currently, the [latest released version](https://www.npmjs.com/package/@mui/x-license?activeTab=versions) is `@7.12.0`.
![Screenshot 2024-08-15 at 09 51 10](https://github.com/user-attachments/assets/474db9c2-5009-4f56-ac66-127d9f8473b3)
