### ISSUE TITLE
[pickers][DateRangePicker] selecting past date - how to force reset the value?

### ISSUE THREAD

**Issue by trgtrg** [mui/mui-x#14242]
### The problem in depth

This is related to https://github.com/mui/mui-x/issues/13535 but in the opposite way. The problem is that we should always start a new period, after one is selected. Motivation of this is that on changing the period we immediatly run a huge analytical query that lasts several seconds. So what happens:

1. Selected period is 01.07.2024 till 15.07.2024
2. User wants to change it to 15.06.2024 till 30.06.2024 and clicks on 15.06.2024
3. Instead of starting a new period selection it becomes 15.06.2024 - 15.07.2024 and we run a query which is not what user wants.
4. Finally he clicks on 30.06.2024 and we send the query that he really needs.

So it would be great if you add an option to customize this behaviour or provide a workaround. 

One of the examples mentioned in issue https://github.com/mui/mui-x/issues/13535 is https://rsuitejs.com/components/date-range-picker/ - it behaves exactly as we need, it always resets period on click.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.36 
    @mui/core-downloads-tracker:  5.15.14 
    @mui/icons-material: ^5.11.0 => 5.15.10 
    @mui/lab: ^5.0.0-alpha.112 => 5.0.0-alpha.165 
    @mui/material: ^5.15.14 => 5.15.14 
    @mui/private-theming:  5.16.0 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.16.0 
    @mui/types:  7.2.14 
    @mui/utils:  5.16.0 
    @mui/x-charts: ^7.9.0 => 7.9.0 
    @mui/x-data-grid: ^7.9.0 => 7.9.0 
    @mui/x-data-grid-pro: ^7.9.0 => 7.9.0 
    @mui/x-date-pickers: ^7.9.0 => 7.9.0 
    @mui/x-date-pickers-pro: ^7.9.0 => 7.9.0 
    @mui/x-internals:  7.9.0 
    @mui/x-license:  7.9.0 
    @types/react:  18.2.56 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 
```
</details>

**Search keywords**: date range picker, date range calendar, reset value, reset period
**Order ID**: 91749

**Comment by michelengelen** [comment]
Hey @trgtrg .. From what I get from your description is that you probably need a rangepicker that only fires your query execution when a full range is selected. Is that correct?

We actually have a callback that does that: `onAccept` ([Lifecycle on pickers: "onAccept"](https://mui.com/x/react-date-pickers/lifecycle/#lifecycle-on-pickers-quot-onaccept-quot))

This does fire when both values get selected and can be used to perform actions based on the selection.

Would that solve your use case?

**Comment by trgtrg** [comment]
As I understand, the first click on the past date will always increase the range, instead of starting to select a new range and it will fire onAccept anyway. But I don't need an increased range, I just want to select smaller one in the past.
![select-past-date](https://github.com/user-attachments/assets/17516365-070e-41d3-ac71-551f72b48315)

I need to achieve the same behaviour exactly like selecting the future date when it starts to select a new range.
![select-future-date](https://github.com/user-attachments/assets/816e0ac7-f862-4c91-ba96-4c9d201a472e)

**Comment by michelengelen** [comment]
So you want a [Week picker](https://mui.com/x/react-date-pickers/date-calendar/#week-picker) instead? Or basically a range picker that always selects a predefined range (e.g. 5 days) from the date you select?

Is that correct?

**Comment by trgtrg** [comment]
No I just want to start to select a new period in past. I do not need to select a week or any predefined period. Look at the example below I want to select 18 - 21, but in first selects 18 - 24, and only on the second click I achive the desired period.
![small-range-in-the-past](https://github.com/user-attachments/assets/a1ebaba4-eb5f-4c4f-a84c-2d717ba3ac5c)

**Comment by trgtrg** [comment]
It might be complicated to implement it this way, because at the moment we expect period to be without nulls. I think there should be a better way. Also the visual part of the component will still work like it gonna increase the range rather than select a new one.

As I see in DateRangePicker manual there is some way to choose between future and the past to increase or to start a new period. So I just need to start a new one every time.
![start-end](https://github.com/user-attachments/assets/9e1d3c72-bbeb-44b3-8984-23d4fbb05771)

**Comment by michelengelen** [comment]
So, even if you have a fully selected range and the start is focused you want to re-start the selection from scratch, right?

In this case you will definitely need a `null`/`undefined` value in `end`. But if your system does not support that you can still wrap the DatePicker and handle these things internally and only `onAccept` the values are being used in the implementation:

```tsx
import * as React from 'react';
import { Dayjs } from 'dayjs';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DateRange } from '@mui/x-date-pickers-pro/models';
import { DateRangePicker } from '@mui/x-date-pickers-pro/DateRangePicker';
import { Alert, AlertTitle, Box } from '@mui/material';

type WrappedDateRangePickerProps = {
  onAccept: (range: DateRange<Dayjs>) => void;
};

function WrappedDateRangePicker(props: WrappedDateRangePickerProps) {
  const [value, setValue] = React.useState<DateRange<Dayjs>>([null, null]);

  const handleValueChange = (newValue: DateRange<Dayjs>) => {
    if (value[0]?.isSame(newValue[0])) {
      setValue(newValue);
    }
    setValue([newValue[0], null]);
  };

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DateRangePicker value={value} onChange={handleValueChange} onAccept={props.onAccept} />
    </LocalizationProvider>
  );
}

export default function Demo() {
  const [selectedRange, setSelectedRange] = React.useState<DateRange<Dayjs> | null>(null);
  const handleAccept = (range: DateRange<Dayjs>) => {
    // do something with the range
    setSelectedRange(range);
  };

  return (
    <Box sx={{ displazy: 'flex', flexDirection: 'row' }}>
      <Box sx={{ flex: 2 }}>
        <WrappedDateRangePicker onAccept={handleAccept} />
      </Box>
      <Alert severity="info" sx={{ width: '100%', ml: 1, flex: 1 }}>
        <AlertTitle>Selected range:</AlertTitle>
        <p>
          {Array.isArray(selectedRange)
            ? `${selectedRange?.[0]?.format('YYYY-MM-DD')} - ${selectedRange?.[1]?.format('YYYY-MM-DD')}`
            : 'None'}
        </p>
      </Alert>
    </Box>
  );
}
```

**Comment by michelengelen** [comment]
Furthermore you can disable the day preview with `slotProps.day.isPreviewing`.

**Comment by LukasTy** [comment]
@trgtrg One can also consider [playing around with `rangePosition` controlling](https://stackblitz.com/edit/react-4nwcla?file=Demo.tsx) to force a desired behavior. 😉 
cc @michelengelen
