### ISSUE TITLE
[data grid] can't show header when no rows

### ISSUE THREAD

**Issue by KingWu** [mui/mui-x#14244]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Render datagrid without any data
2. DataGrid show no rwos
3.

### Current behavior

1. Render datagrid without any data
2. DataGrid show no rwos
3. Column disappear

<img width="1182" alt="Screenshot 2024-08-17 at 11 03 48 AM" src="https://github.com/user-attachments/assets/23e698ee-e81b-46bd-bde4-01aa73f6139d">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: no header

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
