### ISSUE TITLE
[data grid] How to properly optimize a table?

### ISSUE THREAD

**Issue by svidskiy** [mui/mui-x#14259]
### The problem in depth

How can I properly optimize the table? I'm getting more than 20 re-renders for each cell, and I have about 8 of them, which is not great in my opinion. I also added a switch, and it toggles with a delay of about ~150 milliseconds.

Conditionally, I have 8 cells and 50 rows; that would be 8000 renderers...

Example of my code:

```
export const SiteTable = ({ rows, ...rest }: SiteTableProps) => {
    const [selectedRows, setSelectedRows] = useState<GridRowSelectionModel>([]);

    const handleOnToggle = useCallback((id: GridRowId) => {
        setSelectedRows((prevSelected) => {
            if (prevSelected.includes(id)) {
                return prevSelected.filter((selected) => selected !== id);
            }
            
            return [...prevSelected, id];
        });
    }, []);

    const columns: GridColDef<SiteTableRow>[] = [
        {
            field: 'switch',
            headerAlign: 'center',
            align: 'center',
            width: 64,
            disableColumnMenu: true,
            sortable: false,
            resizable: false,
            renderCell: ({ id }) => <SwitchCell onToggle={() => handleOnToggle(id)} isSelected={selectedRows.includes(id)} />,
            renderHeader: () => <SwitchCell />
        },
        {
            field: 'site',
            headerName: 'Domain',
            headerAlign: 'center',
            align: 'center',
            flex: 2,
            disableColumnMenu: true,
            sortable: false,
            renderCell: ({ row }) => <SiteDomainCell domain={row.target_domain} />
        },
        {
            field: 'cost_micros',
            headerName: 'Cost',
            headerAlign: 'center',
            align: 'center',
            flex: 1,
            disableColumnMenu: true,
            sortable: false,
            renderCell: ({ row }) => <CostCell cost={row.cost_micros} />
        },
        {
            field: 'clicks',
            headerName: 'Clicks',
            headerAlign: 'center',
            align: 'center',
            flex: 1,
            disableColumnMenu: true,
            sortable: false,
            renderCell: ({ row }) => <ClickCell clicks={row.clicks} />
        }
    ];

    return (
        <Table
            columns={columns}
            rows={rows}
            paginationMode='server'
            disableRowSelectionOnClick
            getRowId={(row) => row.domain}
            rowSelectionModel={selectedRows}
            slotProps={{
                toolbar: {
                    toolbars: [
                        {
                            component: () => <TableDefaultToolbar />,
                            condition: () => selectedRows.length < 1
                        },
                        {
                            component: () => <TableSelectionToolbar />,
                            condition: () => selectedRows.length
                        }
                    ]
                }
            }}
            {...rest}
        />
    );
};
```

Delay:

https://github.com/user-attachments/assets/594f32f3-0865-49c3-b10f-ebc3f22e03dc

Rerenders:

https://github.com/user-attachments/assets/6a1a6e33-0bf0-4956-a2de-7320847bc537

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.17
    @mui/icons-material: ^5.15.17 => 5.15.17
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.17 => 5.15.17
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.12.1 => 7.12.1
    @mui/x-charts-vendor:  7.12.1
    @mui/x-data-grid:  7.3.2
    @mui/x-data-grid-pro: ^7.3.2 => 7.3.2
    @mui/x-date-pickers: ^7.4.0 => 7.4.0
    @mui/x-date-pickers-pro: ^7.4.0 => 7.4.0
    @mui/x-license:  7.2.0
    @types/react: ^18.2.66 => 18.2.79
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.4.5
```
</details>

**Search keywords**: data grid
**Order ID**: 89766

**Comment by michelengelen** [comment]
Hello @svidskiy,

Optimization can be challenging, but here are a few areas where you can make improvements:

**Summary:** I've created an [optimized demo](https://codesandbox.io/p/sandbox/clever-babbage-wsd6wf?file=%2Fsrc%2FDemo.tsx) using your example code for reference.

---

1. **Stable References for Column Definitions:** It's important to maintain a stable reference for your column definitions. Although building a custom selection column makes this more complex, it can still be achieved with appropriate use of the API.
2. **Stable References for Props:** Ensure that props have a stable reference. If possible, define anything outside the component. For cases where this isn't feasible, use memoization to maintain stability.
3. **Simplify `slots`/`slotProps` Usage:** Avoid overcomplicating the usage of `slots` and `slotProps`. Instead, conditionally return a toolbar based on the value obtained from the internal grid state, utilizing the API.

Let me know if you need further assistance.

**Comment by flaviendelangle** [comment]
@michelengelen we have optimization tips scattered across the doc

![image](https://github.com/user-attachments/assets/09691f1a-3ced-4945-8275-59e18bd22597)

![image](https://github.com/user-attachments/assets/0cd8fe61-f0e8-42f3-953e-124cba09e815)

![image](https://github.com/user-attachments/assets/d2eb44be-6de6-4b51-a332-6513b7da4b52)

(and a few others)

Maybe we could consider having a centralized page about performance instead (those callouts could link to it).

**Comment by michelengelen** [comment]
@flaviendelangle I had the exact same idea when writing that response ... Had written it down to open an issue later today 👍🏼

**Comment by svidskiy** [comment]
> Hello @svidskiy,
> 
> Optimization can be challenging, but here are a few areas where you can make improvements:
> 
> **Summary:** I've created an [optimized demo](https://codesandbox.io/p/sandbox/clever-babbage-wsd6wf?file=%2Fsrc%2FDemo.tsx) using your example code for reference.
> 
> 1. **Stable References for Column Definitions:** It's important to maintain a stable reference for your column definitions. Although building a custom selection column makes this more complex, it can still be achieved with appropriate use of the API.
> 2. **Stable References for Props:** Ensure that props have a stable reference. If possible, define anything outside the component. For cases where this isn't feasible, use memoization to maintain stability.
> 3. **Simplify `slots`/`slotProps` Usage:** Avoid overcomplicating the usage of  and . Instead, conditionally return a toolbar based on the value obtained from the internal grid state, utilizing the API.`slots``slotProps`
> 
> Let me know if you need further assistance.

I removed the custom logic for overriding the **rowSelectionModel**. Instead, I started using the grid API, and now it works instantly without unnecessary renders and without delays. Before, the processor was loaded up to 99%, but now it only goes up to 23% at most. Honestly, I don't know what it's related to since I don't have any complex logic; it was practically a minimal implementation

**Comment by michelengelen** [comment]
I get that @svidskiy, but even the smallest updates can cause a rerender of the complete grid. This does not only include the rendering of all rows, columns and wrappers, but also a lot of stuff in the virtualization, state and filtering.

The most important part is using a stable reference. This will improve the grid by a lot already.

Glad that it did work out for you.
I will create a new issue to include a dedicated section targeting performance optimization in the docs and link it here.

**Comment by michelengelen** [comment]
I did create the issue ... as it seems the performance improved quite a lot with little changes on your end @svidskiy I will close this issue now!
Thanks for raising it!
