### ISSUE TITLE
[data grid] Initial state for a checkbox using checkboxSelection

### ISSUE THREAD

**Issue by svidskiy** [mui/mui-x#14265]
### The problem in depth

How can you make a checkbox default to a true state and then change it to the opposite state when clicked?

[Implementation ](https://github.com/mui/mui-x/blob/b217a276988e3942be4c5a2776705b836fc00fdb/packages/x-data-grid/src/colDef/gridCheckboxSelectionColDef.tsx#L25) using a base checkbox, but any attempts to change the logic prevent modifying the checkbox.

My [example](https://codesandbox.io/p/sandbox/ex-cxx6df?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm012ugmx00063j6ixmwdfcik%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm012ugmx00023j6if6zsv08k%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm012ugmx00033j6ie0lfr32m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm012ugmx00053j6i00nrnyjt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm012ugmx00023j6if6zsv08k%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm012ugmw00013j6iujosp0qq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm012ugmx00023j6if6zsv08k%2522%252C%2522activeTabId%2522%253A%2522cm012ugmw00013j6iujosp0qq%2522%257D%252C%2522cm012ugmx00053j6i00nrnyjt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm012ugmx00043j6ivk8zx5k9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cm012ugmx00053j6i00nrnyjt%2522%252C%2522activeTabId%2522%253A%2522cm012ugmx00043j6ivk8zx5k9%2522%257D%252C%2522cm012ugmx00033j6ie0lfr32m%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm012ugmx00033j6ie0lfr32m%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.17
    @mui/icons-material: ^5.15.17 => 5.15.17
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170
    @mui/material: ^5.15.17 => 5.15.17
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.12.1 => 7.12.1
    @mui/x-charts-vendor:  7.12.1
    @mui/x-data-grid:  7.3.2
    @mui/x-data-grid-pro: ^7.3.2 => 7.3.2
    @mui/x-date-pickers: ^7.4.0 => 7.4.0
    @mui/x-date-pickers-pro: ^7.4.0 => 7.4.0
    @mui/x-license:  7.2.0
    @types/react: ^18.2.66 => 18.2.79
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.4.5
```
</details>

**Search keywords**: data grid
**Order ID**: 89766

**Comment by michelengelen** [comment]
you need to start with a fully selected `rowSelectionModel`.
IT is basically just an array with all IDs in it: `Row[id][]`

You can most likely get this with a simple mapping: 

```tsx
const initialRowSelectionModel = rows.map(row => row.id)
```

**Comment by svidskiy** [comment]
> you need to start with a fully selected . IT is basically just an array with all IDs in it: `rowSelectionModel``Row[id][]`
> 
> You can most likely get this with a simple mapping:
> 
> ```tsx
> const initialRowSelectionModel = rows.map(row => row.id)
> ```

Thank you, this is a working option
