### ISSUE TITLE
[data grid] How can i add multiple selection on filter with menu items

### ISSUE THREAD

**Issue by JahanzaibAbdullah** [mui/mui-x#14269]
### The problem in depth

**Hi MUI Team,**

I hope this message finds you well. I am currently implementing filters in a DataGrid table and encountered an issue that I believe could enhance the user experience if addressed.

**Issue:**

I am trying to apply multi-selection filters on specific columns, such as "status" or "priority," where the values are consistent across rows. Ideally, I would like the filter menu to allow me to select multiple values for a column in one go. However, the current functionality requires me to select the column repeatedly to apply multiple filters, which is not efficient and affects the user experience.

**Current Behavior:**

To filter by multiple values within the same column (e.g., status or priority), I have to interact with the column filter multiple times. This results in an inefficient process, especially when dealing with large datasets or numerous filters.

**Desired Behavior:**

The filter menu should provide a multi-select option when I click on a column header or filter button on toolbar. This would allow me to select multiple values at once, streamlining the filtering process and improving usability.

**Illustration:**

I have attached images that showcase the current behavior. The images represents the status quo, where multiple interactions are needed to filter by several values by selecting the same column again and again. 

![image](https://github.com/user-attachments/assets/b46f761d-0cc9-47d1-b638-134a59166fa1)

![image](https://github.com/user-attachments/assets/ec4002c1-9485-4eb1-86c7-51b9250131a0)

![image](https://github.com/user-attachments/assets/b09bb10e-ac1d-4989-b198-a7735de8dbbf)

**Impact:**

Implementing this feature would significantly enhance the DataGrid’s usability, particularly for users dealing with extensive datasets. It would reduce the time and effort required to apply complex filters, making the DataGrid more efficient and user-friendly.

I believe this enhancement aligns with MUI’s commitment to providing a seamless and powerful UI component library. I would greatly appreciate your attention to this matter and look forward to hearing your thoughts on this potential improvement.

**Best Regards,**
Jahanzaib Malik

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid - toolbar - filter
**Order ID**: 91010

**Comment by michelengelen** [comment]
Hey @JahanzaibAbdullah ... Would this help?

[DEMO](https://codesandbox.io/p/sandbox/sleepy-butterfly-q7qy87)

It is an example I built recently to showcase a custom filtering with complex values.
