### ISSUE TITLE
[data grid] `onColumnOrderChange` not triggered in Firefox because `event.dataTransfer` is null

### ISSUE THREAD

**Issue by DaryaHaprova** [mui/mui-x#14263]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-zvxe1b?file=Demo.js
Steps:
1. Try to reorder columns by drag and drop
2. check console
3. 'order change' - not logged
4. error -  event.dataTransfer is null
![Screenshot (347)](https://github.com/user-attachments/assets/a7d306d3-8853-46f8-89c2-2ea74648d846)
![Screenshot (348)](https://github.com/user-attachments/assets/39fcb309-7e5d-4fc0-be05-71a74a0e4d92)

### Current behavior

onColumnOrderChange  not triggered

### Expected behavior

onColumnOrderChange  triggered

### Context

I want to save columns order in local storage on change 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  I used Firefox - 129.0.1
 
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.98)

```
</details>

**Search keywords**: dataTransfer, Firefox, onColumnOrderChange

**Comment by michelengelen** [comment]
It seems like a but that got introduced in FF v129 ... it works in v128.
I am currently looking over the changelogs and bugzilla to find the cause for the change, but no luck so far.

**Comment by michelengelen** [comment]
I just tested it in v130 and nightly ... so it only appears in v129 ... 
Since v130 will release next month should we add a callout in the docs to inform users about this @mui/xgrid ?

**Comment by RajeshReddyM** [comment]
I experienced the same problem with version 129.0.1, but after updating Firefox this morning, it works fine with version 129.0.2.
