### ISSUE TITLE
[data grid] Issue with Korean Input in DataGrid Causing Duplicated Characters

### ISSUE THREAD

**Issue by sinrusia** [mui/mui-x#14275]
### Steps to reproduce

Set up a DataGrid component from Material-UI in a React project.
Define a column in the DataGrid that uses renderCell to render a TextField or input element.
Attempt to input Korean text using an IME (e.g., typing "고고").
Press the spacebar after typing a few characters.
Observe that the last character typed is duplicated.
Example:

```javascript
<DataGrid
  rows={[{ id: 1, prefix: '' }]}
  columns={[
    {
      field: 'prefix',
      headerName: 'Prefix',
      width: 100,
      sortable: false,
      disableColumnMenu: true,
      renderCell: (params) => (
        <input
          type="text"
          style={{ height: '25px' }}
        />
      ),
    },
  ]}
/>
```

When using the DataGrid component with an input element in the renderCell method, Korean text input via an IME results in character duplication when pressing the spacebar. For example, typing "고고" followed by the spacebar results in "고고 고고". This issue seems specific to the combination of Korean IME and DataGrid.

### Current behavior

When using the DataGrid component with a TextField or input element inside the renderCell method, typing Korean text with an IME leads to an unexpected behavior. Specifically, after typing a few Korean characters and pressing the spacebar, the last character or set of characters is duplicated. For example, if the user types "고고" and then presses the spacebar, the resulting text is "고고 고고". This duplication occurs consistently and disrupts the intended user input.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: macOS 14.5
  Binaries:
    Node: 21.6.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.120
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.21 
    @mui/icons-material: ^5.16.6 => 5.16.6 
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: ^5.15.19 => 5.15.21 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.6 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-data-grid: ^7.3.1 => 7.12.0 
    @mui/x-data-grid-pro: ^7.12.0 => 7.12.0 
    @mui/x-date-pickers: ^7.3.1 => 7.8.0 
    @mui/x-internals:  7.12.0 
    @mui/x-license:  7.12.0 
    @mui/x-tree-view: ^7.12.0 => 7.12.0 
    @types/react:  18.3.3 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    typescript:  4.9.5 

```
</details>

**Search keywords**: DataGrid, IME

**Comment by michelengelen** [comment]
@KenanYusuf could you have a look here?

**Comment by KenanYusuf** [comment]
@sinrusia are you able to provide a reproduction of this issue, please? A codesandbox or even a screen recording of the issue would be helpful.

**Comment by cherniavskii** [comment]
Hi @sinrusia 
We don't recommend rendering inputs in `renderCell` – we have the Editing feature specifically for editable cells – see [Editing docs](https://mui.com/x/react-data-grid/editing/).
When in non-editing mode, the keys like Space, Arrow keys, etc. are used for keyboard navigation around the Data Grid – this is why you see the behavior you describe.
