### ISSUE TITLE
[pickers][TimePicker] `minutesStep` prop not reflecting in UI intervals

### ISSUE THREAD

**Issue by Nithinmon-D** [mui/mui-x#14272]
### Current behavior

**Scenario 1:**

- The picker shows time intervals in 5-minute increments instead of 1-minute increments.
- Manually entering the time using the arrow key and number keypad allows you to set the minutes in 1-minute increments (1, 2, 3, 4, etc.).

**Scenario 2:**

- The picker still shows time intervals in 5-minute increments, despite explicitly setting minutesStep to 1.
- Manually entering the time using the arrow key and number keypad works as expected, allowing you to set the minutes in 1-minute increments.

### Expected behavior

- When rendering the TimePicker with the default settings, the minutesStep should be 1, so the picker should show time intervals in 1-minute increments when clicking on the picker icon.
- When rendering the TimePicker with minutesStep={1}, the picker should show time intervals in 1-minute increments when clicking on the picker icon.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: TimePicker

**Search keywords**:

**Comment by arthurbalduini** [comment]
Hello @Nithinmon-D, 
I couldn't reproduce the described behaviors. Could you please share an example or a video of the issue ?

**Comment by Nithinmon-D** [comment]
> Hello @Nithinmon-D, I couldn't reproduce the described behaviors. Could you please share an example or a video of the issue ?

import * as React from 'react';
import { DemoContainer } from '@mui/x-date-pickers/internals/demo';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { TimePicker } from '@mui/x-date-pickers/TimePicker';

export default function BasicTimePicker() {
  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DemoContainer components={['TimePicker']}>
        <TimePicker label="Basic time picker" minutesStep={1} />
      </DemoContainer>
    </LocalizationProvider>
  );
}
![image](https://github.com/user-attachments/assets/0da3f7a4-2035-41a2-8afb-e29a800e92e4)

since the minuteStep is 1 the interval should be 1, 2, 3, .... but instead it is 0, 5, 10.....

**Comment by arthurbalduini** [comment]
Hello @Nithinmon-D,
Thanks for the details. If I understand your issue correctly, to achieve such behavior you must set the `timeSteps` prop to have the step interval you wish. In that case, you would set it like: 
```
<TimePicker
  timeSteps={{ minutes: 1 }}
/>
```
Let us know if it doesn't solve your needs.

**Comment by Nithinmon-D** [comment]
> Hello @Nithinmon-D, Thanks for the details. If I understand your issue correctly, to achieve such behavior you must set the [`timeSteps`](https://mui.com/x/api/date-pickers/time-picker/#time-picker-prop-timeSteps) prop to have the step interval you wish. In that case, you would set it like:
> 
> ```
> <TimePicker
>   timeSteps={{ minutes: 1 }}
> />
> ```
> 
> Let us know if it doesn't solve your needs.

tx its worked

**Comment by LukasTy** [comment]
Given this confusion, I think that we should unify the behavior of `minutesStep` and `timeSteps` and deprecate/drop the `minutesStep` prop in favor of one option for similar/same thing.
I have added this idea to the v8 preparation issue.

**Comment by jondalee-hub** [comment]
FWIW, I ran into the same need, same confusion, same fix.
