### ISSUE TITLE
[core] Project classic gets deprecated, migrate

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#14270]
### Steps to reproduce

https://github.com/search?q=org%3Amui+https%3A%2F%2Fgithub.com%2Fmui%2Fmui-x%2Fprojects%2F1&type=code

### Current behavior

Link to https://github.com/mui/mui-x/projects/1

<img width="804" alt="SCR-20240820-lydn" src="https://github.com/user-attachments/assets/dcc6b72e-a6b8-4e1b-8a81-c0cee93cb7b1">

### Expected behavior

Link to https://github.com/orgs/mui/projects/35

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by michelengelen** [comment]
@oliviertassinari with these 2 PRs we should be fine, right?

**Comment by oliviertassinari** [comment]
@michelengelen Yes, as far as I know 👍
