### ISSUE TITLE
[data grid] In column filter dropdowns

### ISSUE THREAD

**Issue by bkolubenka** [mui/mui-x#14288]
### The problem in depth

How to setup in column filter dropdowns. for now we should fill out filter manually.

      1. How to get values from dropdown?
      2. Also can be multiple values selected from drodown?

![image](https://github.com/user-attachments/assets/1f8484b6-609b-47ce-8538-2e20fc96cca0)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: dropdown, filter
**Order ID**: 83454

**Comment by michelengelen** [comment]
Hey @bkolubenka ... this is a very similar issue to #14269 
I did recently built a demo that uses a multiselect in the filter: [DEMO](https://codesandbox.io/p/sandbox/sleepy-butterfly-q7qy87?file=%2Fsrc%2FDemo.tsx)

This should showcase how this is done easily! 👍🏼 

I'll close this one as duplicate! Thanks!
