### ISSUE TITLE
Filtering and Sorting Not Working Correctly for Text Columns in DataGrid Using renderCell

### ISSUE THREAD

**Issue by Kanish-PP** [mui/mui-x#14283]
### Steps to reproduce

**Steps to Reproduce:**
Use the provided code below to initialize a DataGrid with text columns and a renderCell function for custom rendering.
Attempt to sort or filter the data in any of the text columns (Task, Status, Category, Description).

**reproduceable example:** 
[https://codesandbox.io/p/sandbox/filtering-example-not-working-lvz9mp](https://codesandbox.io/p/sandbox/filtering-example-not-working-lvz9mp)

```
import React, { useState, useEffect } from 'react';
import { DataGrid, GridToolbarQuickFilter, GridToolbar } from '@mui/x-data-grid';

// Mock dropdown columns and options
const dropdownColumns = ['Status', 'Category'];

// Function to get dropdown options for specific columns
export const getOptionsForColumn = (column) => {
  switch (column) {
    case 'Status':
      return ['Pending', 'In Progress', 'Completed', 'Cancelled'];
    case 'Category':
      return ['A', 'B', 'C'];
    default:
      return ['Yes', 'No'];  // For boolean columns
  }
};

// Determine column type based on the options
const getColumnType = (column) => {
  const options = getOptionsForColumn(column);
  return options.length === 2 ? 'boolean' : dropdownColumns.includes(column) ? 'singleSelect' : 'text';
};

// Function to determine cell class based on value (optional)
const getCellClassName = (params) => {
  if (params.field === 'Status') {
    switch (params.value) {
      case 'Pending':
        return 'cell-pending';
      case 'In Progress':
        return 'cell-in-progress';
      case 'Completed':
        return 'cell-completed';
      case 'Cancelled':
        return 'cell-cancelled';
      default:
        return '';
    }
  }
  return '';
};

// Custom Toolbar to use the Quick Filter outside of the grid
function MyCustomToolbar(props) {
  return (
    <React.Fragment>
      <GridToolbarQuickFilter />
      <GridToolbar {...props} />
    </React.Fragment>
  );
}

// Mock Data
const mockData = [
  { id: 1, Task: 'Task 1', Status: 'Pending', Category: 'A', Description: 'This is task 1' },
  { id: 2, Task: 'Task 2', Status: 'In Progress', Category: 'B', Description: 'This is task 2' },
  { id: 3, Task: 'Task 3', Status: 'Completed', Category: 'C', Description: 'This is task 3' },
  { id: 4, Task: 'Task 4', Status: 'Cancelled', Category: 'A', Description: 'This is task 4' },
  { id: 5, Task: 'Task 5', Status: 'Pending', Category: 'B', Description: 'This is task 5' },
  { id: 6, Task: 'Task 6', Status: 'In Progress', Category: 'C', Description: 'This is task 6' },
  { id: 7, Task: 'Task 7', Status: 'Completed', Category: 'A', Description: 'This is task 7' },
  { id: 8, Task: 'Task 8', Status: 'Cancelled', Category: 'B', Description: 'This is task 8' },
  { id: 9, Task: 'Task 9', Status: 'Pending', Category: 'C', Description: 'This is task 9' },
  { id: 10, Task: 'Task 10', Status: 'In Progress', Category: 'A', Description: 'This is task 10' },
];

const DataGridExample = () => {
  const [rows, setRows] = useState([]);
  const [columns, setColumns] = useState([]);

  useEffect(() => {
    // Initialize columns and rows
    const cols = Object.keys(mockData[0]).map((key) => ({
      field: key,
      headerName: key.replace(/_/g, ' '),
      editable: dropdownColumns.includes(key),
      flex: 1,
      minWidth: 150,
      align: 'left',
      type: getColumnType(key),
      valueOptions: dropdownColumns.includes(key) ? getOptionsForColumn(key) : [],
      cellClassName: (params) => getCellClassName(params),
      renderCell: (params) => {
        if (params.field === 'Task') {
          return (
            <div style={{ cursor: 'pointer', color: 'blue' }}>
              {params.value}
            </div>
          );
        }
        if (params.field === 'Status' && dropdownColumns.includes(params.field)) {
          return params.value;
        }
        return params.value;
      },
    }));
    setColumns(cols);
    setRows(mockData);
  }, []);

  return (
    <div style={{ height: 600, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        checkboxSelection
        hideFooter
        disableRowSelectionOnClick
        slots={{
          toolbar: MyCustomToolbar,
        }}
      />
    </div>
  );
};

export default DataGridExample;

```

### Current behavior

**Actual Behavior:**
Sorting does not work as expected for text columns when renderCell is used or for the column type text.
Filtering does not filter out rows based on the expected values for text columns.
Clicking on filter on shows this,(another example) even though the column is a text i cant find any other operation except 'is'
![image](https://github.com/user-attachments/assets/1b70b8db-175f-4132-b456-fbc0d3a93e57)

And search bar should work like a filter but only working for non text columns

### Expected behavior

**Expected Behavior:**
Sorting: Clicking on the column headers should sort the data correctly.
Filtering: Using the Quick Filter should filter the rows based on the input value, including text columns.
And search bar should work like a filter for all columns

### Context

**Description:**

I am experiencing an issue with filtering, searching and sorting in the DataGrid component from @mui/x-data-grid. Specifically, the filtering and sorting functionality is not working as expected for columns with text data, particularly when using the renderCell method and for the columns with type text.

### Your environment

   "@emotion/react": "^11.13.0",
    "@emotion/styled": "^11.13.0",
    "@mui/icons-material": "^5.16.7",
    "@mui/material": "^5.16.7",
    "@mui/system": "^5.16.7",
    "@mui/x-data-grid": "^7.12.1",

**Search keywords**: filter, sort , search, text type, rendercell

**Comment by MBilalShafi** [comment]
@Kanish-PP The `Task` column is not being sorted or filtered properly because its type is being resolved by `getColumnType` as `boolean`. I've modified your codesandbox example and changed its type to `string` which fixed the problem.

Here's the updated codesandbox: https://codesandbox.io/p/sandbox/filtering-example-not-working-forked-xqzs2j

Let me know if it solves your issue.

**Comment by Kanish-PP** [comment]
it solved thanks
