### ISSUE TITLE
[charts] line charts not rendering on page load, only on mouse over

### ISSUE THREAD

**Issue by Firgrep** [mui/mui-x#14291]
### Steps to reproduce

Link to live example: (required)

https://github.com/Firgrep/graph-test

`git clone https://github.com/Firgrep/graph-test.git`

Steps:
1. npm i
2. npm run dev
3. go to localhost:3010 and observe (try refresh and mousing over to see difference)

### Current behavior

Line chart does not render on page load (but the bar chart renders as expected). Only renders when I mouse over the line chart.

### Expected behavior

To render on page load, just as in the documentation. 

### Context

Running in a next.js server. Not sure if that's an issue here. I have tried to turn the whole page "use client" but that didn't make a difference. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

Browser: Chrome

  System:
    OS: Linux 6.6 Arch Linux
  Binaries:
    Node: 20.15.0 - /usr/bin/node
    npm: 10.8.1 - /usr/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/core-downloads-tracker:  5.16.7
    @mui/material: ^5.16.7 => 5.16.7
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.13.0 => 7.13.0
    @mui/x-charts-vendor:  7.13.0
    @types/react: ^18 => 18.3.3
    react: ^18 => 18.3.1
    react-dom: ^18 => 18.3.1
    typescript: ^5 => 5.5.4
```
</details>

**Search keywords**: charts

**Comment by michelengelen** [comment]
@JCQuintas I can reproduce this in the repo shared here, but not in our implementation (playground). Could you have a look?

**Comment by JCQuintas** [comment]
Related to https://github.com/mui/mui-x/issues/13477, https://github.com/mui/mui-x/issues/12873, https://github.com/mui/mui-x/pull/12892

It seems there is an issue with line animation in some cases. We need to take a closer look into it.

**Comment by michelengelen** [comment]
I'll move it to the board! Thanks! 👍🏼
