### ISSUE TITLE
[x-license] MUI Missing license key

### ISSUE THREAD

**Issue by TOMTADEV** [mui/mui-x#14290]
### The problem in depth

Why the data grid have MUI X missing license key appear?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: license
**Order ID**: 85516

**Comment by michelengelen** [comment]
This error means there is no license key being passed to the license package to verify it.
Could you re-check how you pass it into the function?

```tsx
LicenseInfo.setLicenseKey('YOUR_LICENSE_KEY');
```

If you use a secret or variable please also check if the value is not `undefined`
