### ISSUE TITLE
[data grid] State change in component when `groupingColDef` and `pinnedColumns` leads to mis-render in Group column

### ISSUE THREAD

**Issue by pechersky** [mui/mui-x#14298]
### Steps to reproduce

[Link to live example: (required)](https://react-2xihdm-7p5dji.stackblitz.io/)
[Editable link ](https://stackblitz.com/edit/react-2xihdm-7p5dji?file=Demo.tsx)

Steps:
1. Have a DataGrid with `treeData`, `getTreeDataPath`, `groupingColDef`, and a pinned column.
2. Change the state of the component
3. See that the group column has take on the value of the pinned column, and moved back to the left.

### Current behavior

Currently, on my and coworkers' machines, this results in a mis-aligned and wrong value Group column:
![image](https://github.com/user-attachments/assets/888a2938-c749-4b4c-8bd3-5f10bb38aad4)

### Expected behavior

The pinned column should stay where it is as well as the group column, and the data grid state should change without affecting the group column.

In the live example, this is the behavior:
![image](https://github.com/user-attachments/assets/aeb1e493-cdd8-4715-82e9-6929501735f4)

### Context

We want to allow users to pin columns and also via a toggle, change some state such that the group column displays different text -- for example, the row index.

It's not clear to me why the minimal example fails on our machines but works in the stackblitz example.

### Your environment

<details>
  <summary><code>npx @mui/envinfo </code></summary>

```
Google Chrome: 127.0.6533.120 (Official Build) (64-bit) (cohort: Stable) 

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.7 
    @mui/icons-material: ^5.16.7 => 5.16.7 
    @mui/lab: ^5.0.0-alpha.173 => 5.0.0-alpha.173 
    @mui/material: ^5.16.7 => 5.16.7 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.7 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.13.0 
    @mui/x-data-grid-premium: ^7.13.0 => 7.13.0 
    @mui/x-data-grid-pro:  7.13.0 
    @mui/x-internals:  7.13.0 
    @mui/x-license:  7.13.0 
    @mui/x-tree-view: ^7.13.0 => 7.13.0 
    @types/react: ^18.3.4 => 18.3.4 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript:  5.3.3 

```
</details>

**Search keywords**: Row grouping, Tree data, Column pinning
**Order ID**: 93920

**Comment by pechersky** [comment]
Yes, the exact same example is broken. We've tried also the same example on a coworkers brand new environment and it was broken there too.

**Comment by michelengelen** [comment]
can you provide your setup details? Or ideally a repo with the minimal setup so we can check if this also happens with our systems?

**Comment by rjdirisio** [comment]
Hi, I set up a repo with a working example that reproduces the bug:
https://github.com/rjdirisio/mui-state-change-14298

One can clone and run this the following way:
```bash
$ npm -v
9.6.7
$ npm install -D typescript && npm i && npm start
```

**Comment by pechersky** [comment]
Yes, [this repo ](https://github.com/rjdirisio/mui-state-change-14298) reproduces the bug, Also with a build via `npm run build`.

**Comment by michelengelen** [comment]
Thanks ... @KenanYusuf could you have a look?

**Comment by KenanYusuf** [comment]
Hi @pechersky

It looks like the issue is caused by the column definition not being stable between renders. 

There are more details on the [column definition docs](https://mui.com/x/react-data-grid/column-definition/), but most importantly this callout:
> The columns prop should keep the same reference between two renders. The columns are designed to be definitions, to never change once the component is mounted. Otherwise, you take the risk of losing elements like column width or order.

Try moving the column definition out of the component, or memoize it:
```tsx
const columnDef = React.useMemo(
  () =>
    columns.map((col) => ({
      field: col,
    })),
  []
);
```

Let me know if you're still seeing the issue after this.
