### ISSUE TITLE
[data grid] How to setup clickable value (like links) in input field

### ISSUE THREAD

**Issue by bkolubenka** [mui/mui-x#14301]
### The problem in depth

Looking best way to setup links for values in input forms. How to properly setup editable and clickabe fields as well?

![image](https://github.com/user-attachments/assets/f7f63004-e242-4a75-bbd4-92050d64d773)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: clickable
**Order ID**: 83454

**Comment by michelengelen** [comment]
Can you please elaborate on what you want to achieve?
If you just want to render a link you can use the `renderCell` function on the column definition: [Rendering cells](https://mui.com/x/react-data-grid/column-definition/#rendering-cells)
