### ISSUE TITLE
[charts] Missing `themeAugmentation` in pro plan

### ISSUE THREAD

**Issue by lhilgert9** [mui/mui-x#14304]
The `themeAugmentation` is missing in the pro plan of the charts. It would be nice if the pro plan exports its own `themeAugmentation` that extends the community plan and implements the augmentation for the pro components. If that's okay, I could implement that too.

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @lhilgert9 ... feel free to open a PR with a proposal! Any contribution is highly appreciated! 👍🏼
