### ISSUE TITLE
[data grid] Remove `indeterminateCheckboxAction` prop

### ISSUE THREAD

**Issue by MBilalShafi** [mui/mui-x#14300]
Remove the prop `indeterminateCheckboxAction` and make `select` the default behavior.

Context: https://github.com/mui/mui-x/pull/14247#discussion_r1728468668

**Comment by oliviertassinari** [comment]
> Do we want to deprecate the indeterminateCheckboxAction prop in v8 and agree on select as the expected behavior?

👍 I would go straight to change the default value and remove the prop in v8. See https://youtu.be/tRsxLLghL1k?si=sRhbVRHVLRR83pMX&t=574.

**Comment by marvelsrp** [comment]
I want to draw attention to the erroneous [aria-label](https://github.com/mui/mui-x/blob/cdccf7d33bd09df0ded5be34407ddf3e1bfb80be/packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx#L128). It depends on [isChecked](https://github.com/mui/mui-x/blob/cdccf7d33bd09df0ded5be34407ddf3e1bfb80be/packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx#L129C7-L129C16), but is correctly related by [checked](https://github.com/mui/mui-x/blob/cdccf7d33bd09df0ded5be34407ddf3e1bfb80be/packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx#L132C11-L132C18).

**Comment by oliviertassinari** [comment]
@marvelsrp Can you open a new issue or a PR? It looks broken indeed, but it's off topic here.

**Comment by oliviertassinari** [comment]
@marvelsrp This is now fixed under the MUI X v8 release line.

**Comment by MBilalShafi** [comment]
> @marvelsrp This is now fixed under the MUI X v8 release line.

Adding, I'll soon port the fix to v7 as well.
