### ISSUE TITLE
[charts-pro] Dependency local workspace reference causes runtime errors on ``createAxisFilterMapper``

### ISSUE THREAD

**Issue by PatoGuereque** [mui/mui-x#14314]
Hello,

I noticed the following issue while trying to use the new zoom feature on charts-pro.

The following import is using a relative path to x-charts, rather than using ``@mui/x-charts``. 

```ts
import { getScale } from '../../../../x-charts/src/internals/getScale';
```
https://github.com/mui/mui-x/blob/b321b4076a977148d8f23cfd57e49906df4534b8/packages/x-charts-pro/src/context/CartesianProviderPro/createAxisFilterMapper.ts#L12C27-L12C39

This causes errors when resolving dependencies

Error: 
```
✘ [ERROR] Could not resolve "../../../../x-charts/src/internals/getScale"

    node_modules/@mui/x-charts-pro/context/CartesianProviderPro/createAxisFilterMapper.js:2:25:
      2 │ import { getScale } from '../../../../x-charts/src/internals/getScale';
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Link to live example: [CodeSandbox](https://codesandbox.io/p/sandbox/mui-datagrid-template-forked-dc3rsf)

I believe I'd need to sign a CLA if I were to open a PR, even though it's a 2-3 line patch. Am I correct?

Regards,
Pato

**Search keywords**: x-charts-pro
**Order ID**: 96664

**Comment by LukasTy** [comment]
Hello @PatoGuereque. 
Thank you for being so quick to adopt new features! 🙏 
We are sorry that this issue got passed our checks. 🙈 

> I believe I'd need to sign a CLA if I were to open a PR, even though it's a 2-3 line patch. Am I correct?

Yes, that is the case, I've opened a PR to avoid the extra hassle for such a small fix. 👍
