### ISSUE TITLE
[data grid] Numbers and booleans are returned as strings when filtering in a DataGrid

### ISSUE THREAD

**Issue by victorct-tradeengage** [mui/mui-x#14327]
### Steps to reproduce

Link to live example: [link](https://codesandbox.io/p/sandbox/thirsty-browser-lm7cjg?workspaceId=bdadc1c4-71b6-49af-9206-c8b4b14580f7&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm08yie7m00073b6ir4p4hwmz%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm08yie7m00033b6ilxiqsqqs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm08yie7m00043b6ijz4va2uf%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm08yie7m00063b6i9rkyjp0v%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm08yie7m00033b6ilxiqsqqs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm08yie7m00023b6i63aprs7b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A23%257D%255D%257D%255D%252C%2522id%2522%253A%2522cm08yie7m00033b6ilxiqsqqs%2522%252C%2522activeTabId%2522%253A%2522cm08yie7m00023b6i63aprs7b%2522%257D%252C%2522cm08yie7m00063b6i9rkyjp0v%2522%253A%257B%2522id%2522%253A%2522cm08yie7m00063b6i9rkyjp0v%2522%252C%2522activeTabId%2522%253A%2522cm08ynzs300153b6i0c1g1muk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm08yie7m00053b6i1pm8321k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm08ynzs300153b6i0c1g1muk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm08yie7m00043b6ijz4va2uf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm08yie7m00043b6ijz4va2uf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Create A Datagrid with one column being a number or a boolean
2. Filter the column.
3. console.log the `filterModel`, using `onFilterModelChange`
4. The value for that field, inside the `filterModel` is a string, not a number or a boolean.

### Current behavior

Numbers and booleans are being returned as strings when filtering a DataGrid

### Expected behavior

Numbers and booleans must be returned as numbers or booleans when filtering a DataGrid

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

- System:
  - OS: macOS 14.0
- Binaries:
  - Node: 19.5.0 - ~/.local/share/nvm/v19.5.0/bin/node
  - npm: 9.3.1 - ~/.local/share/nvm/v19.5.0/bin/npm
  - pnpm: Not Found
- Browsers:
  - Chrome: 127.0.6533.120
  - Edge: Not Found
  - Safari: 17.0
- npmPackages:
  - @emotion/react:  11.11.1
  - @emotion/styled:  11.11.0
  - @mui/base:  5.0.0-beta.40
  - @mui/core-downloads-tracker:  5.15.15
  - @mui/icons-material: ^5.14.11 => 5.14.11
  - @mui/lab: ^5.0.0-alpha.148 => 5.0.0-alpha.150
  - @mui/material: ^5.14.11 => 5.15.15
  - @mui/private-theming:  5.15.14
  - @mui/styled-engine:  5.15.14
  - @mui/system:  5.15.15
  - @mui/types:  7.2.14
  - @mui/utils:  5.15.14
  - @mui/x-data-grid:  7.3.1
  - @mui/x-data-grid-generator: ^7.3.1 => 7.3.1
  - @mui/x-data-grid-premium: ^7.6.1 => 7.6.1
  - @mui/x-data-grid-pro:  7.3.1
  - @mui/x-date-pickers: ^6.17.0 => 6.17.0
  - @mui/x-license: ^7.2.0 => 7.2.0
  - @mui/x-tree-view:  6.0.0-alpha.1
  - @types/react: ^18.0.14 => 18.0.14
  - react: ^18.2.0 => 18.2.0
  - react-dom: ^18.2.0 => 18.2.0
  - typescript: ^4.7.4 => 4.7.4
 </details>

**Search keywords**: number, filter, string, DataGird
**Order ID**: I have a license key for the premium, not can share the email if needed, not sure how to get the OrderID

**Comment by victorct-tradeengage** [comment]
This actually applies the same with booleans

**Comment by michelengelen** [comment]
Confirmed @victorct-tradeengage ... @cherniavskii could this be related to the recent changes for the localStorage issue?

**Comment by k-rajat19** [comment]
This happens with dates too, internally we are converting those string values into the other types (using `valueParser` property in colDef) before applying the filter operator to them.
@cherniavskii should we use that `valueParser` more at the top level ?  and update the value types in the filter model, then we also don't need to parse the values internally again. 
happy to send PR for that

**Comment by romgrk** [comment]
We should use the parser when it makes sense, probably in the input component change handler. Feel free to send a PR for this.
