### ISSUE TITLE
[charts] BarChart horizontal now breaks the series value passing

### ISSUE THREAD

**Issue by whsmacon** [mui/mui-x#14332]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Context

<img width="831" alt="image" src="https://github.com/user-attachments/assets/e9715ac2-8612-4320-af77-77af0b5a621f">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: barChart horizontal

**Comment by alexfauquette** [comment]
I confirm the regression. That's because the tooltip looked for axis with `index` set to `undefined` to know if the band scale is on the x-axis or y-axis. But we recently moved from `undefined` to a value of `-1`

I opened a PR to fix it
