### ISSUE TITLE
[pickers][DateTimeRangePicker] Polish locale from dayjs breaks datetime format in DateTimeRangePicker since v.7.10.0

### ISSUE THREAD

**Issue by oskarkk** [mui/mui-x#14334]
### Steps to reproduce

Link to live example:
Correct in 7.9.0: https://codesandbox.io/p/sandbox/mui-daterangepicker-format-issue-7-9-0-jg2c5f
Incorrect in 7.10.0: https://codesandbox.io/p/sandbox/mui-datetimerangepicker-format-issue-7-10-0-6hdc22
Incorrect in 7.14.0: https://codesandbox.io/p/sandbox/mui-datetimerangepicker-format-issue-latest-cdnst2

The issue appears when using polish locale:

```
      <LocalizationProvider
        dateAdapter={AdapterDayjs}
        adapterLocale={dayjs.locale("pl")}
      >
        <DateTimeRangePicker<Dayjs>
          value={[dayjs("2020-02-02T00:00:00"), dayjs("2020-02-03T00:00:00")]}
          slots={{ field: SingleInputDateTimeRangeField }}
          sx={{ "& .MuiInputBase-root": { width: "250px" } }}
        />
      </LocalizationProvider>
```

### Current behavior

On x-date-pickers version >= 7.10.0 the picker displays date in format `02 00:00 – 03 00:00`, not showing month and year.

### Expected behavior

On x-date-pickers version <= 7.9.0 the picker was working correctly displaying format: `02.02.2020 00:00 – 03.02.2020 00:00`

### Your environment

Version that works:
    "dayjs": "1.11.13",
    "@mui/material": "5.16.7",
    "@mui/x-date-pickers-pro": "7.9.0"

Version that doesn't work:
    "dayjs": "1.11.13",
    "@mui/material": "5.16.7",
    "@mui/x-date-pickers-pro": "7.10.0"

**Search keywords**: locale, dayjs
**Order ID**: Order 80141

**Comment by arthurbalduini** [comment]
Hello @oskarkk,

Thanks for reporting it and providing complete information and examples. I can confirm it is a bug, probably coming from #13743 
We will investigate the solution and try to push a fix as soon as possible.

**Comment by arthurbalduini** [comment]
While we work on the fix, attributing the `format` prop perhaps works for you as a workaround:

```
<DateTimeRangePicker<Dayjs>
    value={[dayjs("2020-02-02T00:00:00"), dayjs("2020-02-03T00:00:00")]}
    format="DD/MM/YYYY HH:mm"
    slots={{ field: SingleInputDateTimeRangeField }}
    sx={{ "& .MuiInputBase-root": { width: "250px" } }}
/>
```
