### ISSUE TITLE
[tree view] TreeItem2DragAndDropOverlay - Error: MUI: Unsupported `var(--palette-primary-dark)` color.

### ISSUE THREAD

**Issue by mtr1990** [mui/mui-x#14349]
### Steps to reproduce

use `<CssVarsProvider/>` for base example

https://mui.com/x/react-tree-view/rich-tree-view/ordering/#only-trigger-the-reordering-from-a-drag-handle

### Current behavior

<img width="417" alt="xx-1" src="https://github.com/user-attachments/assets/c6840f89-f4b3-47a2-8b04-82865998ffd0">

to my knowledge the `alpha` function will not support vars so this could be the cause of the error
![xxx](https://github.com/user-attachments/assets/97a15050-72a5-456b-8af1-f1dac3d8393f)

https://github.com/mui/mui-x/blob/master/packages/x-tree-view/src/TreeItem2DragAndDropOverlay/TreeItem2DragAndDropOverlay.tsx

### Expected behavior

No error with`TreeItem2DragAndDropOverlay`

**Search keywords**: TreeItem2DragAndDropOverlay

**Comment by michelengelen** [comment]
Hey @mtr1990 ... I can confirm this bug and will add it to the board!
Thanks for opening it! 👍🏼

**Comment by kzimins-arvatosystems** [comment]
Btw could be `TreeItem2DragAndDropOverlay` also exported from pro package as well?

**Comment by flaviendelangle** [comment]
#14913  fixes the import issues on the pro package
