### ISSUE TITLE
[data grid] How to change the variant of selects in the boolean filter panel

### ISSUE THREAD

**Issue by troysatchell-wk** [mui/mui-x#14354]
### The problem in depth

When accessing the slotProps and changing `baseSelect` to a variant of `outlined`, the label for the select in the filter panel doesn't render properly if it is a boolean column type. Is this the right way to change the variant for the select?
[SandBox](https://codesandbox.io/p/sandbox/baseselect-filter-panel-issue-3z6m5r)
```
        slotProps={{
          baseFormControl: {
            variant: "outlined",
          },
          baseSelect: {
            variant: "outlined",
          },
        }}
```

<img width="717" alt="Screenshot 2024-08-26 at 1 39 57 PM" src="https://github.com/user-attachments/assets/176ccf1e-62cc-4337-a250-cb6d430773e9">

### Your environment

See the [SandBox](https://codesandbox.io/p/sandbox/baseselect-filter-panel-issue-3z6m5r)

**Search keywords**: baseSelect variant
**Order ID**: 82849

**Comment by troysatchell-wk** [comment]
@dosu Even with the `notched` property set to true the baseSelect Label still appears out of place 
See [Sandbox](https://codesandbox.io/p/sandbox/baseselect-filter-panel-issue-3z6m5r?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0ba7gnp00073b6j1i89o2w1%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0ba7gno00033b6jc2hfrejy%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0ba7gno00043b6jb3z5xr1k%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0ba7gno00063b6j6p0048lj%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0ba7gno00033b6jc2hfrejy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0ba7gno00023b6jshpkz599%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0ba7gno00033b6jc2hfrejy%2522%252C%2522activeTabId%2522%253A%2522cm0ba7gno00023b6jshpkz599%2522%257D%252C%2522cm0ba7gno00063b6j6p0048lj%2522%253A%257B%2522id%2522%253A%2522cm0ba7gno00063b6j6p0048lj%2522%252C%2522activeTabId%2522%253A%2522cm0ba7rak00143b6jkqbn2t1i%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0ba7gno00053b6jgq81cnra%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0ba7rak00143b6jkqbn2t1i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0ba7gno00043b6jb3z5xr1k%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0ba7gno00043b6jb3z5xr1k%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

<img width="1436" alt="Screenshot 2024-08-28 at 10 00 19 AM" src="https://github.com/user-attachments/assets/5b240264-948c-4745-ae70-c7438b29264e">

**Comment by michelengelen** [comment]
Hey @troysatchell-wk and sry for the late reply.
To change the variant of the select input in the filter panel you can just use `slotProps.filterPanel.filterFormProps` ... there you have options for `deleteIconProps`, `logicOperatorInputProps`, `columnInputProps`, `operatorInputProps` and `valueInputProps`


The related section of the docs is [Customize the filter panel content](https://mui.com/x/react-data-grid/filtering/customization/#customize-the-filter-panel-content)
