### ISSUE TITLE
[data grid] New row not visible when filter is set

### ISSUE THREAD

**Issue by MacHankus** [mui/mui-x#14361]
### Steps to reproduce

Link to live example: [[(required)](https://codesandbox.io/p/sandbox/add-record-with-filters-xhkxrn)](https://codesandbox.io/p/sandbox/add-record-with-filters-xhkxrn)

Steps:
1. Add Filter 
    Select column name. Select Operator. Provide value. Click somewhere to hide filter panel.
2. Add record.
    Click `Add Record` button. 
 
After this steps you can see that new row doesn't appear anywhere. You can see new record only if filter is off.

I didn't find any information about `how new row should behave`. Is it any tip to make new rows always visible with or without filters ? I know that probably filters are doing its job and new row is filtered out , but the question is why ? From the business side the row is added as soon as we click `save` not before so filters should not affect new rows. We can update rows when filters are set but we cannot add new rows.

### Current behavior

New row is not visible when filter is set

### Expected behavior

New row should be visible when filter is set ?

### Context

I want to add new row and set cell values based on visible rows. Right now i need to open second browser tab with filtered values to browse them and keep open browser tab without filters to add rows.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Chrome 127.0.6533.122
```
</details>

**Search keywords**: New row not visible when filter is set

**Comment by MacHankus** [comment]
If it comes to first example how can i set `currentFilterState.filteredRowsLookup[newRowId] = true;` properly ? Should I maintain filterModel  by my own while doing this or can i just update filteredRowsLookup and  not bother about maintaining filterModel ?
Is there any example of this code with actual DataGrid instance ?

**Comment by michelengelen** [comment]
Hey @MacHankus ... what you are trying to do is probably not possible.
We can currently exclude columns from the filtering, but not rows.

Thinking about this there might be a way. But first: Do you need this for all columns, or just for specific ones? 

I am asking because the workaround would include adjusting the applyfilter functions for the operators and would essentially remove the `isEmpty` operator in general.
