### ISSUE TITLE
[data grid] Column reorder does not work on tablet/mobile

### ISSUE THREAD

**Issue by lucal-mms** [mui/mui-x#14362]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/affectionate-star-kfd8qj
(Example from official docs: https://mui.com/x/react-data-grid/column-ordering/)

Steps:
1. Open link
2. Open rendered component in a new window 
![image](https://github.com/user-attachments/assets/31bb101b-2db7-4eed-8295-e1e7e0e76a6e)
3. Press F12 and select tablet/mobile view mode
4. Try to reorder columns by dragging the headers but nothing happens, no icon is present for reordering via an icon

### Current behavior

When trying to drag-and-drop columns on mobile/tablet to reorder them, nothing happens.
There is no icon present to reorder by dragging that icon either.

I even went as far as to clone the source code to try and see and there's an icon for column reorder that's not used:

![image](https://github.com/user-attachments/assets/afdca9c8-b85d-499d-812a-4f890570b2a1)

Found in filegridIconSlotsComponent.ts .

### Expected behavior

Column reorder should work on tablet/mobile too.
Either add an icon which can be dragged/dropped by the user via tap hold, or add the possibility to drag-and-drop column headers like on bigger devices (laptop/desktop).

### Context

One of the reasons we chose and paid  forMUI PRO was because of this feature.
We have several users that use the app on tablet/mobile in landscape mode for quick access of data on the go (in meetings for example, when you don't have your laptop on hand).

**Search keywords**: column reorder tablet mobile
**Order ID**: 89922

**Search keywords**:

**Comment by lucal-mms** [comment]
There should be an out-of-the-box solution for this!
Every other functionality already works on tablet/mobile

**Comment by michelengelen** [comment]
This feature is currently not implemented.
Do we plan to built this @cherniavskii, given the tree view now has the drag and drop ready?

**Comment by wingbui** [comment]
Yes, this feature should be added to drag columns on touch screen such as tablets. I temporarily used Ag-Grid because it supported drag-and-drop column on touch screen. The downside is Ag-Grid package is quite heavy. I will switch back to MUI when this feature is implemented for touch screen.

**Comment by michelengelen** [comment]
Since this touches the same problem as #9330 I will close this as a duplicate.
Please consider upvoting it to increase visibility. 👍🏼
