### ISSUE TITLE
[x-license] License of MUI X Premium license shows as MUI expired package version

### ISSUE THREAD

**Issue by enricpr** [mui/mui-x#14371]
### The problem in depth

Using "@mui/x-data-grid-pro": "4.0.2" in a component library which works fine when imported in the main React app that uses Create React Apps.

When migrating to Vite, Data Grid is working but now it says the product is unlicensed.

The license is set in the components library inside a custom DatGrid component:
```jsx
import { LicenseInfo } from '@mui/x-data-grid-pro';

const DataGrid: FC<DataGridProps> = props => {
  LicenseInfo.setLicenseKey(process.env.REACT_APP_X_GRID_LICENSE_INFO!);`
```
  

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.1
  Binaries:
    Node: 22.0.0 - ~/.nvm/versions/node/v22.0.0/bin/node
    npm: 10.5.1 - ~/.nvm/versions/node/v22.0.0/bin/npm
    pnpm: 9.7.0 - ~/.nvm/versions/node/v22.0.0/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.122
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @mui/x-data-grid-pro: 4.0.2 => 4.0.2 
    @mui/x-license-pro:  4.0.2 
    @types/react: ^17.0.5 => 17.0.11 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.9.4 => 4.9.4 
```
</details>

**Search keywords**: vite unlicensed product x-license
**Order ID**: 18623

**Comment by enricpr** [comment]
@dosu Next.js is not being used like in the examples provided

**Comment by enricpr** [comment]
@dosu Settings the license outside the component function, in this case App, makes it available in this component but not to the rest of the components where the tables are rendered

**Comment by enricpr** [comment]
@dosu the problem is that it was working correctly when the license was set in a components library that is installed through yarn when the main app was using react-scripts. After migrating to Vite, the license is not being set anymore

**Comment by enricpr** [comment]
@dosu when setting the key in index.jsx and doing a LicenseInfo.getKey(), it returns the correct key, but the tables still show the unlicensed message

**Comment by enricpr** [comment]
@dosu by setting
`NODE_ENV: JSON.stringify(process.env.NODE_ENV)`
in vite.config.ts, the `process.env.NODE_ENV` is set correctly to development/production

**Comment by michelengelen** [comment]
Hey @enricpr ... It would be great if you could share a minimal reproduction repository with us so that we can actually run it and check whats going wrong there!
