### ISSUE TITLE
[Data grid] - How to reset filter explicity or using apiRef?

### ISSUE THREAD

**Issue by ashishchoudhary12** [mui/mui-x#14385]
### Summary

I have two buttons here. ButtonOne and ButtonTwo on which I am adding the columns. 
When I apply filter on name and switch to ButtonTwo I want to reset the filter which ever I applied. Can I do that?
[Please check here](https://codesandbox.io/p/sandbox/objective-zeh-nmlzly?file=%2Fsrc%2FDemo.tsx%3A254%2C1)

**Search keywords**: How to reset filter explicity or using apiRef?

**Comment by michelengelen** [comment]
Hey @ashishchoudhary12 ... you can just use the `apiRef` for this task.

Here is a quick demo: [Unsetting filter via `apiRef`](https://codesandbox.io/p/sandbox/pedantic-hertz-w92yyq)

This should do the trick!

**Comment by ashishchoudhary12** [comment]
Hi @michelengelen, I’m having trouble locating the reset code in the link you provided. I can’t seem to find it. Could you help me out?

**Comment by michelengelen** [comment]
> > Here is a quick demo: [Unsetting filter via apiRef](https://codesandbox.io/p/sandbox/pedantic-hertz-w92yyq)
> 
> Hi @michelengelen, I’m having trouble locating the reset code in the link you provided. I can’t seem to find it. Could you help me out?

For some reason it did not save it:

[DEMO](https://codesandbox.io/p/sandbox/pedantic-hertz-w92yyq)

**Comment by michelengelen** [comment]
Glad it worked for you!
