### ISSUE TITLE
[data grid] Visual indicator for editable cells/rows

### ISSUE THREAD

**Issue by jnagy-citco** [mui/mui-x#14389]
### The problem in depth

I am a designer and noticed that when we look at the grid for indicating to the user that certain fields are editable the cursor changes to the Text Cursor Icon (https://mui.com/x/react-data-grid/editing/) – however, it changes to the Text Cursor Icon even when the field is non-editable.  **Is this an actual bug or just a bug in your demo?**  

Users should know what fields are editable and I am thinking to modify the grid to show an edit icon on hover so that the user knows what cells are editable - if there isn't another way with the out of the box MUI X version.  Similar to what Sales Force Lightening does https://www.lightningdesignsystem.com/components/data-tables/#Edited-cell-(unsaved)
 
### Your environment

Using Chrome

### Context

https://mui.zendesk.com/agent/tickets/21927

**Search keywords**: Editing MUI X Grid
**Order ID**: 87931

**Comment by michelengelen** [comment]
Hey @jnagy-citco ... where exactly do you see the edit-cursor appearing?

If you refer to this:
<img width="206" alt="Screenshot 2024-08-30 at 10 57 33" src="https://github.com/user-attachments/assets/63da5d97-b857-4ace-a1f6-7168a05e0001">

It is the standard text selection cursor/caret.

We typically do not change the cursor based on the editable property of the cells.
Although this might be a good idea for a recipe/feature.

**Comment by oliviertassinari** [comment]
This issue is tricky, but I agree, it sounds like a customization question, if not all the cells are editable, then leaving a visual clue sounds great:

https://github.com/user-attachments/assets/0a989ea0-4efb-46fd-b2aa-ea92ff39dae4
