### ISSUE TITLE
[data grid] Implementing a Custom Filter for MUI DataGrid

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#14399]
### The problem in depth

I am currently working on a project where I’ve designed a custom filter view for filtering the data displayed in the DataGrid. Instead of using the default filtering functionalities provided by MUI DataGrid, I want to use my custom filter UI and have the DataGrid display data based on the selected filters from this custom view.

Could you please let me know if it’s possible to apply a custom filter logic to the DataGrid using an external custom filter component? If so, I would appreciate any guidance or examples on how to integrate my custom filter selection with the DataGrid so that the displayed data updates accordingly. 

Here is the UI of my custom filter 
![Screenshot 2024-08-30 155519](https://github.com/user-attachments/assets/69f93aca-e6a8-4b00-a729-5c02725dc526)
![Screenshot 2024-08-30 155611](https://github.com/user-attachments/assets/23586286-2125-4f48-b55d-b934733b9778)
![Screenshot 2024-08-30 163720](https://github.com/user-attachments/assets/9453e3ce-9b80-4f56-9dc5-611341152b45)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data, Grid, Premium, Custom, Filter
**Order ID**: 91010

**Comment by michelengelen** [comment]
What you want is a [controlled filterModel](https://mui.com/x/react-data-grid/filtering/#controlled-filters).

Since your filter panel is custom you just have to make sure that the parameters used match the ones from the datagrid.
