### ISSUE TITLE
Newly bought key does not cover x-tree-view-pro: MUI X: Component not included in your license.

### ISSUE THREAD

**Issue by JSHSJ** [mui/mui-x#14412]
### The problem in depth

Hi there,

we just bought a PRO license for our developers, so we could use the newly added reordering in x-tree-view-pro.
We set it up as explained in your Licensing page, but the component has the overlay say:
`MUI X: Component not included in your license.`

In the console the error is also thrown.

Logging with `console.log(LicenseInfo.getLicenseKey());` shows, that the correct license key has been added.

Is there any way to debug this? 

Thanks in advances,
kind regards
Joshua Stübner

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 14.6.1
  Binaries:
    Node: 18.18.2 - ~/.local/share/nvm/v18.18.2/bin/node
    npm: 10.8.2 - ~/.local/share/nvm/v18.18.2/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.86
    Edge: 128.0.2739.54
    Safari: 17.6
    Firefox: 129.0.2 <-- current browser
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1
    @emotion/styled: 11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.0
    @mui/material: 5.15.21 => 5.15.21
    @mui/private-theming:  5.16.0
    @mui/styled-engine:  5.15.14
    @mui/styled-engine-sc: 5.14.12 => 5.14.12
    @mui/system:  5.16.0
    @mui/types:  7.2.14
    @mui/utils:  5.16.6
    @mui/x-date-pickers: 7.14.0 => 7.14.0
    @mui/x-internals:  7.15.0
    @mui/x-license: ^7.15.0 => 7.15.0
    @mui/x-tree-view:  7.15.0
    @mui/x-tree-view-pro:  7.15.0
    @types/react: 18.3.3 => 18.3.4
    react: 18.3.1 => 18.3.1
    react-dom: 18.3.1 => 18.3.1
    styled-components: 5.3.3 => 5.3.3
    typescript: 5.1.6 => 5.1.6
```
</details>

**Search keywords**: MUI X: Component not included in your license, license
**Order ID**: 97202

**Comment by michelengelen** [comment]
Yes, @JSHSJ ... Could you open a ticket [here](https://support.mui.com/hc/en-us/requests/new?tf_360023797420=mui_x&_gl=1*7brds4*_gcl_au*MTQ3MzQyNjQ1MC4xNzIyNjA5Nzkz*_ga*MjAyNzQ0NTg5OC4xNjkzODA4MjI1*_ga_5NXDQLC2ZK*MTcyNTAyNjcxNy41NjguMS4xNzI1MDI2NzU0LjIzLjAuMA..)?
There we can look into your license and fix your problem with it!
Ideally you post your order id and received key with it!
Thanks!

PS: You can also mention me in the ticket and I'll have a look then.
