### ISSUE TITLE
[pickers] Date picker crash on mui.com

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#14422]
### Steps to reproduce

Steps:
1. Open https://mui.com/
2. Click on the next month button icon

### Current behavior

https://github.com/user-attachments/assets/1e38a1ed-28f5-4c32-842e-4c1719c46db7

### Context

https://x.com/bweston92/status/1829792875955028046

**Comment by michelengelen** [comment]
Seems related to the transition:
<img width="773" alt="Screenshot 2024-09-02 at 11 48 17" src="https://github.com/user-attachments/assets/b61e0093-481f-4997-b44f-9085a115a4dc">

**Comment by michelengelen** [comment]
The demos in the docs work... so it might be specific to some styles in this demo.

**Comment by arthurbalduini** [comment]
I did a quick investigation and there's a space being added to the SlideTransition classnames, perhaps involving the [overrideResolver](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DateCalendar/PickersSlideTransition.tsx#L47) on the styled component, but I'm not being able to evolve much futher than that. Does anyone have more insights about it ? @LukasTy @flaviendelangle 

<img width="1417" alt="Screenshot 2024-09-02 at 16 04 10" src="https://github.com/user-attachments/assets/f3beaafe-2e4b-4f7c-b11b-62628dacc730">

**Comment by alexfauquette** [comment]
If that can help, the older docs build with the bug I found is this one https://github.com/mui/material-ui/pull/43363

@romgrk could it be a unexpected side effect?

**Comment by romgrk** [comment]
Yes, @oliviertassinari has an open & approved PR to restore the behavior: #43537

**Comment by oliviertassinari** [comment]
Oh wow, I would have never expected an extra space to cause a bug like this. I guess something broken around https://github.com/reactjs/react-transition-group/blob/2989b5b87b4b4d1001f21c8efa503049ffb4fe8d/src/CSSTransition.js#L11. Too bad that this dependency seems unmaintained, we can't fix it there.

**Comment by romgrk** [comment]
We should also probably think about running mui-x tests in the core repo, it would make it more safe to refactor the core.

cc @mui/code-infra

**Comment by Janpot** [comment]
> We should also probably think about running mui-x tests in the core repo, it would make it more safe to refactor the core.

🙂 One could almost argue that X packages and @mui/material belong in the same repository.

**Comment by LukasTy** [comment]
Looks like the issue has been resolved with this fix: https://github.com/mui/material-ui/pull/43537 and is no loner present in the deployed documentation.
