### ISSUE TITLE
[question] How to integrate license key for production?

### ISSUE THREAD

**Issue by DTanmoy** [mui/mui-x#14464]
### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: MUIX license key
**Order ID**: 111111

**Comment by michelengelen** [comment]
[How to install the key](https://mui.com/x/introduction/licensing/#how-to-install-the-key)

☝🏼
