### ISSUE TITLE
[pickers] DateRangePicker supports month and year selection

### ISSUE THREAD

**Issue by bdz2022** [mui/mui-x#14461]
### Summary

hello there,

in DateRangePicker I can use 

```tsx
slotProps={{
  calendarHeader: {
    views: ['year', 'month'],
  }
}}
```

to show the view of year and month button, but the following month/year button's function doesn't work, can't do a month or year selection(Which works for DateTimePicker)
![image](https://github.com/user-attachments/assets/767ce5cf-645d-4130-b13d-d184521eb4b7)

Do you have any plan to add this function? thanks.

**Search keywords**: DateRangePicker month year view selection

**Comment by michelengelen** [comment]
@LukasTy any plans implementing this or do you know of a workaround for this?

**Comment by LukasTy** [comment]
Hello @bdz2022, thank you for being interested in this feature.
We have it planned (https://github.com/mui/mui-x/issues/4546) and plan to start working on it this year. 😉 

I'm closing this issue as a duplicate. 👌
