### ISSUE TITLE
[charts] Migrating `ResponsiveChartContainer` to `ResponsiveChartContainerPro` results in error

### ISSUE THREAD

**Issue by ZaidLinkEZ** [mui/mui-x#14460]
### The problem in depth

Hi, I'm currently using ResponsiveChartContainer and while migrating it to ResponsiveChartContainerPro, it's giving me errors that I'm unable to debug and resolve.

The error that I got was 
MUI X: Could not find the svg ref context.
It looks like you rendered your component outside of a ChartsContainer parent component.

Even though my component runs fine when it runs with ResponsiveChartContainer, gives the error when i swap ResponsiveChartContainer with ResponsiveChartContainerPro.

I'm using JavaScript and React-18.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: ResponsiveChartContainerPro MUI X Charts
**Order ID**: 95670

**Comment by michelengelen** [comment]
Hey @ZaidLinkEZ ... thanks for raising this!

@JCQuintas could you have a look please?

**Comment by JCQuintas** [comment]
Hi @ZaidLinkEZ, I can't really replicate this locally. Switching `ResponsiveChartContainer` by `ResponsiveChartContainerPro` doesn't throw any errors on my end.

Have you tried clearing you build cache? 

If that doesn't work, could you share an example repo where this happens?

**Comment by ZaidLinkEZ** [comment]
> Hi @ZaidLinkEZ, I can't really replicate this locally. Switching `ResponsiveChartContainer` by `ResponsiveChartContainerPro` doesn't throw any errors on my end.
> 
> Have you tried clearing you build cache?
> 
> If that doesn't work, could you share an example repo where this happens?

I tried clearing my cache and the error still persists. I'll create a duplicate of my chart component and share it.

**Comment by ZaidLinkEZ** [comment]
Hi @JCQuintas, sorry for the inconvenience, I checked my logs and it also gave an error

"MUI X: Component not included in your license.

The component you are trying to use is not included in the Pro Plan you purchased.

Your license is from an old version of the Pro Plan that is only compatible with the `@mui/x-data-grid-pro` and `@mui/x-date-pickers-pro` commercial packages.

To start using another Pro package, please consider reaching to our sales team to upgrade your license or visit https://mui.com/r/x-get-license to get a new license key."

I believe this is a issue of the license and not the actual implementation. Sorry for the inconvenience as this passed right by me and I didn't notice it after I dug deep.

**Comment by JCQuintas** [comment]
Hi @ZaidLinkEZ, yes, the old license only works for the `@mui/x-data-grid-pro` and `@mui/x-date-pickers-pro` packages. 

If you want to use the other pro packages you would need to upgrade the license. In some cases this can be done free of charge.

You can read more about the packages and pricing changes in our blog post https://mui.com/blog/mui-x-sep-2024-price-update/#pricing-for-small-teams
