### ISSUE TITLE
[charts] Is the RepsonsiveChartContainerPro capable of zoom and pan yet?

### ISSUE THREAD

**Issue by ZaidLinkEZ** [mui/mui-x#14472]
### The problem in depth

I'm using a RepsonsiveChartContainerPro, is the feature of pan and zoom available on it yet and if not, is it going to be added?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: ResponsiveChartContainerPro MUI X Charts
**Order ID**: 95670

**Comment by michelengelen** [comment]
I am not sure where the zoom and pan feature is located, but from what i can tell looking at the code it should be possible to use it in the responsive containers as well.

@alexfauquette anything to add?

**Comment by ZaidLinkEZ** [comment]
@alexfauquette, yes I didn't add the `<ZoomSetup />`, thanks for the reference in the sandbox. It wasn't in the documentation as well or maybe it was and it passed by me. I only added the `{ zoom: "true" }` property thinking it was enough. Thanks for the clarification.

**Comment by michelengelen** [comment]
Great that @alexfauquette could help you out!
I'll close this issue.
Thanks for your time everyone! 🙇🏼
