### ISSUE TITLE
[pickers] Remove the `PickersMonth` and `PickersYear` component and move their logic inside `MonthCalendar` and `YearCalendar`

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#14474]
Follow up on #13321

In v7, we introduced new `monthButton` and `yearButton` slots.
Now the `PickersMonth` and `PickersYear` are just super small wrappers on top of those slots.

This is a breaking change because it changes the theme entry (should be codemodable).

**Search keywords**:

**Comment by LukasTy** [comment]
Try reducing the DOM nesting by going with `grid` layout instead.
