### ISSUE TITLE
[license] Charts heatmap license problem

### ISSUE THREAD

**Issue by mwydra0206** [mui/mui-x#14488]
### The problem in depth

Hello MUI-Team,

we are started using the MUI-X Pro version this year and had a great experience so far. I am currently started into looking into the new Heatmap that is usable under the Pro license. But when adding it to the Project I get following watermark and I am not sure why. For charts I am on the newest version but I am not sure what the problem is :D 

![image](https://github.com/user-attachments/assets/69cafad5-6168-4be9-8ed4-35d19b44ca66)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 9.1.2 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Google Chrome 128.0.0.0
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.36
    @mui/core-downloads-tracker:  5.15.20
    @mui/icons-material: ^5.15.20 => 5.15.20
    @mui/lab: ^5.0.0-alpha.136 => 5.0.0-alpha.165
    @mui/material: ^5.15.20 => 5.15.20
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.12.1 => 7.15.0
    @mui/x-charts-pro: ^7.0.0-alpha.3 => 7.0.0-alpha.3
    @mui/x-charts-vendor:  7.15.0
    @mui/x-data-grid: ^6.19.3 => 6.19.4
    @mui/x-data-grid-pro: ^7.10.0 => 7.10.0
    @mui/x-internals:  7.10.0
    @mui/x-license: ^7.11.0 => 7.15.0
    @types/react: ^18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.4.5 => 5.4.5
```
</details>

**Search keywords**: charts heatmap license
**Order ID**: 94919

**Comment by michelengelen** [comment]
Hey @mwydra0206 please have a look at this section in the docs: [Component not included in your license](https://mui.com/x/introduction/licensing/#5-component-not-included-in-your-license). 

This blog post should shed some light over it as well: https://mui.com/blog/mui-x-sep-2024-price-update/

The license key you are using is not covering this product, but you can have it renewed or replaced with a new one if you reach out to the sales team! Thanks! 👍🏼

**Comment by mwydra0206** [comment]
Okay. Thanks for the quick reply 😊.
I will contact sales about this.
