### ISSUE TITLE
[license] Migration from Pro to Premium license 

### ISSUE THREAD

**Issue by sag1v** [mui/mui-x#14481]
### The problem in depth

Hello 👋

We are in the process of upgrading to a premium plan, and we have some concerns about a potential issue with license compatibility. We have integrated MUI as the primary framework of our Design System, supplementing it with several of our own components, including our ThemeProvider. For teams that utilize our Design System, using our ThemeProvider is mandatory—it acts as the essential "entry point" for the entire system.

As part of this process, we invoke the `LicenseInfo.setLicenseKey` function within the `ThemeProvider` module. Our question pertains to the status of our current license string after upgrading to the premium plan: Will we receive a new license key? Will the existing (current) key become obsolete? We are concerned that some of our consumers who continue to use earlier versions of our Design System with the old key might encounter the license watermark, despite us being fully compliant with our licensing obligations.

Thank you for addressing our concerns.

### Your environment

<details>
  <summary>npx @mui/envinfo</summary>

```
  System:
    OS: macOS 14.2.1
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 7.24.2 - ~/cloned_projects/fe-ui-core/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.72
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material:  5.11.16 
    @mui/material:  5.13.5 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/styles:  5.13.2 
    @mui/system:  5.13.5 
    @mui/types:  7.2.9 
    @mui/utils:  5.14.18 
    @mui/x-date-pickers:  6.20.2 
    @mui/x-date-pickers-pro:  6.20.2 
    @mui/x-license-pro:  6.10.2 
    @types/react:  18.2.6 
    react:  18.2.0 
    react-dom:  18.2.0 
```
</details>

**Search keywords**: micro frontend design system backward compatible license
**Order ID**: 93481

**Comment by michelengelen** [comment]
Hey @sag1v ... thanks for considering upgrading your plan. 

As for your concerns: as long as you ship the license together with the product there is no problem with it. All features of the premium plan cover the pro features.

You will indeed receive a new license key for the new plan. So changing that when you are going to implement premium features is mandatory. The existing key is not entirely obsolete, as it will still work in production environments.

So you should not need to worry about it and if you encounter any problems with the migration please dont hesitate to reach out!

**Comment by michelengelen** [comment]
I'll close this issue, but feel free to comment if you encounter problems and we will have a look! 👍🏼
