### ISSUE TITLE
[data grid] Console error when editing empty single select cell

### ISSUE THREAD

**Issue by rodolffoteles** [mui/mui-x#14507]
### The problem in depth

Hi,

When editing an empty single select cell, there is a warning message about the empty cell value not being among the available options. And when selecting one of the options, there is an error message about the state of the select component changing from uncontrolled to controlled. These console error/warning messages are visible using the demo on the 
"[Full-featured CRUD](https://mui.com/x/react-data-grid/editing/#full-featured-crud)" on the editing docs.

Is there a way to not have these messages when editing an empty single select cell?

**How to reproduce**
Demo: https://codesandbox.io/p/sandbox/5mn8gs
Click in "Add record". Check browser console. Click on the empty single select cell. Select an option. Check browser console.

![Editing](https://github.com/user-attachments/assets/8511afff-60a8-49eb-8543-2e0ec28b7e0f)

**Console messages**
<img width="480" alt="Captura de Tela 2024-09-05 às 15 18 31" src="https://github.com/user-attachments/assets/bd0f7e35-6751-44b2-84e3-cbbbafc9c4f1">
<img width="471" alt="Captura de Tela 2024-09-05 às 15 18 41" src="https://github.com/user-attachments/assets/8ab77c9c-4ed6-4e45-85b3-ada7acff51c4">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

System:
    OS: macOS 12.7.3
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.119
    Edge: 128.0.2739.63
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.0.2 
    @mui/icons-material: ^6.0.2 => 6.0.2 
    @mui/material: ^6.0.2 => 6.0.2 
    @mui/private-theming:  6.0.2 
    @mui/styled-engine:  6.0.2 
    @mui/system:  6.0.2 
    @mui/types:  7.2.16 
    @mui/utils:  6.0.2 
    @mui/x-data-grid:  7.15.0 
    @mui/x-data-grid-generator: ^7.15.0 => 7.15.0 
    @mui/x-data-grid-premium: ^7.15.0 => 7.15.0 
    @mui/x-data-grid-pro:  7.15.0 
    @mui/x-internals:  7.15.0 
    @mui/x-license:  7.15.0 
    @types/react: ^18 => 18.3.5 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 
    typescript: ^5 => 5.5.4 
</details>

**Search keywords**: datagrid editing

**Comment by michelengelen** [comment]
Hey @rodolffoteles and thanks for raising this!
There is indeed a bug in the example and we will take care of that shortly. 👍🏼
