### ISSUE TITLE
[data grid] Can't group by nested value in fields

### ISSUE THREAD

**Issue by maxd** [mui/mui-x#14520]
### Steps to reproduce

I want to group rows by the `model` column but `DataGridPremium` can't do this:

<img width="594" alt="Screenshot 2024-09-06 at 15 39 22" src="https://github.com/user-attachments/assets/d59a1a3e-27cb-410c-959b-14bb5dcd5360">

As you can see the `model` column is empty.

MVP for reproducing this problem: [link](https://stackblitz.com/edit/github-cikgxp?file=src%2Fdemo.tsx). The MVP is based on the first example from this [page](https://mui.com/x/react-data-grid/row-grouping/).

This happens because `DataGridPremium` can't extract values from fields in nested objects (e.g. from `device.model` and `device.serial_number` fields). Try to uncomment the `model` and `serial_number` fields in the `rows` array. When you make this you'll receive the error: `row.device is undefined`. If you fix this (e.g. replace `row.device.???` with `row.device?.xxx` in `valueGetter` methods) the grouping will work fine:

<img width="595" alt="Screenshot 2024-09-06 at 15 47 12" src="https://github.com/user-attachments/assets/e9b3f390-03a8-4b8f-8140-0281f94b64a1">

### Current behavior

The `DataGridPremium` can't group by field in nested objects i.e. it can group by `model` field in such `{model: "X"}` row but can't group by the same field in `{device: {model: 'x'}}` row when `valueGetter` extract this value.

### Expected behavior

The `DataGridPremium` should group by field in nested objects extracted with `valueGetter` method from column definition.

**Search keywords**: grouping by nested fields

**Comment by michelengelen** [comment]
@MBilalShafi could you have a look at this one? Thanks!

**Comment by maxd** [comment]
I have found the solution to this problem. The [groupingValueGetter](https://mui.com/x/react-data-grid/row-grouping/#using-groupingvaluegetter-for-complex-grouping-value) method should be defined for extract nested fields:

```typescript
...
groupingValueGetter: (_value, row) => row.device.model,
...
```

It's confusing. Is it possible to use the `valueGetter` method to extract nested fields if the `groupingValueGetter` method is undefined?

**Comment by flaviendelangle** [comment]
I went through all the discussions on the PR where I created the row grouping to find a reason not to fallback to `valueGetter` when `groupingValueGetter` is not defined, and I could not find any.

Not saying that we should change our behavior, just that remember a smart reason not to when we created this feature, it was just not discussed :+1:

**Comment by flaviendelangle** [comment]
> but I suppose it'll be better to mention in the documentation that the row grouping functionality uses the groupingValueGetter

It's documented [here](https://mui.com/x/react-data-grid/row-grouping/#using-groupingvaluegetter-for-complex-grouping-value)
Maybe the discoverability of this section is not good enough

**Comment by michelengelen** [comment]
We could possibly add a callout and a crosslink here: [Value getter](https://mui.com/x/react-data-grid/column-definition/#value-getter)
