### ISSUE TITLE
[question] How to enable 'linkOperator' in MUI Data Grid - Multi filters

### ISSUE THREAD

**Issue by MIT-Songphon** [mui/mui-x#14569]
### The problem in depth

How to enable 'linkOperator' in DataGrid multiple filter column
My project using DataGrid Pro https://mui.com/x/react-data-grid/filtering/multi-filters/

![Screenshot 2567-09-11 at 14 29 27](https://github.com/user-attachments/assets/f625523c-4a8c-41b9-980d-48a5c45898f6)

**Search keywords**: Data Grid - Multi filters
**Order ID**: unknown

**Comment by michelengelen** [comment]
Mixing operators for filter operations is not possible.
Its either `AND` or `OR`.
