### ISSUE TITLE
[data grid] baseCheckbox slot also overrides Column Chooser

### ISSUE THREAD

**Issue by httpete** [mui/mui-x#14567]
### Steps to reproduce

Link to live example: (required)

Steps:
1.
2.
3.

### Current behavior

I have overridden the baseCheckbox slot with a Radio component which works great in the Single Selection Grid mode. But it is completely unepected for baseCheckbox to override the Column chooser checkbox.  In my case, I only want the grid selection mechanism to be a radio, not the column chooser one.

![image](https://github.com/user-attachments/assets/d9b00e2c-35c7-4999-a177-3df1df17b2c7)

### Expected behavior

Should allow me a way to only override the gridRowSelection checkBox.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: mui baseCheckbox
**Order ID**: 79357

**Comment by k-rajat19** [comment]
Yeah, this is currently not possible, all checkboxes in the grid are controlled by a single `baseCheckbox` slot so if you override that it will be overridden everywhere.
You can try overriding [these](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/colDef/gridCheckboxSelectionColDef.tsx#L30-L31) properties as a workaround.  Also, read [this](https://mui.com/x/react-data-grid/row-selection/#custom-checkbox-column) section of docs for more info on how you can implement it.

**Comment by michelengelen** [comment]
Thanks for the answer @k-rajat19 ... both are valid points.

**Comment by httpete** [comment]
I tried, doesn't work for me. I still see the Checkbox in the Grid, even having pushed on to the columns:

```

  columns.push({
    ...GRID_CHECKBOX_SELECTION_COL_DEF,
    renderHeader: params => <div>addf</div>,
    renderCell: params => <div>addf</div>,
  });
  ```

**Comment by httpete** [comment]
I overrode the properties, but then the "single select" doesn't take on the radio. It just operates as a checkbox even though it is a radio.

**Comment by httpete** [comment]
My only workaround is to override the BaseCheckbox but then do this inside there. I found that the checkboxes in the grid rows have a ref, and the ones in the column chooser don't.

```
/*
 * Copyright: (c) 2024 Broadcom. The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This software and all information contained therein is confidential and
 * proprietary and shall not be duplicated, used, disclosed or disseminated in any
 * way except as authorized by the applicable license agreement, without the
 * express written permission of CA. All authorized reproductions must be marked
 * with this language.
 *
 * EXCEPT AS SET FORTH IN THE APPLICABLE LICENSE AGREEMENT, TO THE
 * EXTENT PERMITTED BY APPLICABLE LAW, CA PROVIDES THIS SOFTWARE
 * WITHOUT WARRANTY OF ANY KIND, INCLUDING WITHOUT LIMITATION, ANY
 * IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR
 * PURPOSE. IN NO EVENT WILL CA BE LIABLE TO THE END USER OR ANY
 * THIRD PARTY FOR ANY LOSS OR DAMAGE, DIRECT OR INDIRECT, FROM THE
 * USE OF THIS SOFTWARE, INCLUDING WITHOUT LIMITATION, LOST PROFITS
 * BUSINESS INTERRUPTION, GOODWILL, OR LOST DATA, EVEN IF CA IS
 * EXPRESSLY ADVISED OF SUCH LOSS OR DAMAGE.
 */

import { Checkbox, Radio } from '@mineral/core';
import { forwardRef, useLayoutEffect, useState } from 'react';

export const BaseRadio = forwardRef<HTMLButtonElement | null>((props, ref) => {
  if ('indeterminate' in props) {
    return null;
  }

  const [isSingle, setIsSingle] = useState(false);

  useLayoutEffect(() => {
    if (!ref) {
      return;
    }
    setIsSingle(true);
  }, [ref]);

  return isSingle ? (
    <Radio {...props} ref={ref} />
  ) : (
    <Checkbox {...props} ref={ref} />
  );
});

BaseRadio.displayName = 'BaseCheckbox';

~``

**Comment by michelengelen** [comment]
Well, in that case I would honestly go for a custom renderCell function in the column definition:

```tsx
import * as React from 'react';
import {
  DataGrid,
  GRID_CHECKBOX_SELECTION_COL_DEF,
  GridRenderCellParams,
  useGridApiContext,
} from '@mui/x-data-grid';
import { useDemoData } from '@mui/x-data-grid-generator';
import { Radio } from '@mui/material';

const CustomSelectionCell = (params: GridRenderCellParams) => {
  const apiRef = useGridApiContext();
  const isChecked = apiRef.current.getSelectedRows().has(params.row.id);
  const handleClick = React.useCallback(() => {
    if (isChecked) {
      return;
    }
    apiRef.current.setRowSelectionModel([params.row.id]);
  }, [isChecked]);
  return <Radio checked={isChecked} onClick={handleClick} />;
};

export default function DisableClickSelectionGrid() {
  const { data } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 10,
    maxColumns: 6,
  });

  const columns = React.useMemo(
    () => [
      {
        ...GRID_CHECKBOX_SELECTION_COL_DEF,
        renderCell: CustomSelectionCell,
        renderHeader: () => null,
      },
      ...data.columns,
    ],
    [data],
  );

  return (
    <div style={{ height: 400, width: '100%' }}>
      <DataGrid checkboxSelection disableRowSelectionOnClick columns={columns} rows={data.rows} />
    </div>
  );
}
```

**Comment by michelengelen** [comment]
if you want to be able to "unselect' a radio you can replace

```diff
  const handleClick = React.useCallback(() => {
    if (isChecked) {
-     return;
+     apiRef.current.setRowSelectionModel([]);
+     return;
    }
    apiRef.current.setRowSelectionModel([params.row.id]);
  }, [isChecked]);
```

**Comment by httpete** [comment]
So I found subtle differences when I did my own checkbox column in how the selection worked. What you want is clicking anywhere on the row, to highlight and select the radio (just like checkbox). If I clicked the radio directly, it wouldn't work. If I clicked the cell surrounding the radio, it wouldn't work. 

The hacky way I ended up with achieved a perfect result. I feel this should be standard behavior, because when you do single selection mode the proper affordance is a radio per row, not a checkbox per row. It does work correctly, but I get hit by our usability experts when it is single select checkbox.

I had to do a little css to hide the "select / deselect all" checkbox in the header when single selection mode.

Can you add this as a feature? Since we support both modes already single or multi, it seems that correcting the control with a radio is the right way.

**Comment by michelengelen** [comment]
Ok, the requirement that the rowClick should select a row is actually making this a lot easier:

```tsx
import * as React from 'react';
import {
  DataGrid,
  GRID_CHECKBOX_SELECTION_COL_DEF,
  GridColDef,
  GridRenderCellParams,
  useGridApiContext,
  useGridApiRef,
} from '@mui/x-data-grid';
import { useDemoData } from '@mui/x-data-grid-generator';
import { Radio } from '@mui/material';

const CustomSelectionCell = (params: GridRenderCellParams) => {
  const rowId = params.row.id;
  const apiRef = useGridApiContext();
  const [isChecked, setIsChecked] = React.useState(
    apiRef.current.getSelectedRows().has(params.row.id),
  );

  React.useEffect(() => {
    apiRef.current.subscribeEvent('rowSelectionChange', (newSelectionModel) => {
      setIsChecked(newSelectionModel.includes(rowId));
      console.log('rowClick', params.row.id, newSelectionModel);
    });
  }, [apiRef]);

  return <Radio checked={isChecked} />;
};

export default function DisableClickSelectionGrid() {
  const apiRef = useGridApiRef();
  const { data } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 10,
    maxColumns: 6,
  });

  const columns = React.useMemo(
    () => [
      {
        ...GRID_CHECKBOX_SELECTION_COL_DEF,
        type: 'custom' as GridColDef['type'],
        field: '__radio__',
        renderCell: CustomSelectionCell,
        renderHeader: () => null,
      },
      ...data.columns,
    ],
    [data],
  );

  return (
    <div style={{ height: 400, width: '100%' }}>
      <DataGrid apiRef={apiRef} columns={columns} rows={data.rows} />
    </div>
  );
}
```

Try this! :D
