### ISSUE TITLE
[docs] How to mock license for testing

### ISSUE THREAD

**Issue by nico-martinucci** [mui/mui-x#14568]
### Related page

https://mui.com/x/introduction/licensing/

### Kind of issue

Missing information

### Issue description

Any test I run that renders a MUI X component logs the following message:
```
*************************************************************

MUI X: Missing license key.

The license key is missing. You might not be allowed to use `@mui/x-date-pickers-pro` which is part of MUI X Pro.

To solve the issue, you can check the free trial conditions: https://mui.com/r/x-license-trial.
If you are eligible no actions are required. If you are not eligible to the free trial, you need to purchase a license https://mui.com/r/x-get-license or stop using the software immediately.

*************************************************************
```

This greatly muddles the testing output (since it prints for every test).

### Context

 It would be great to have clear documentation on how to mock this check to avoid this logging, or otherwise the ability to easily disable this in a testing environment.

**Search keywords**: mocking license testing muix

**Search keywords**:

**Comment by alexfauquette** [comment]
The error message is unclear. From what I know, there is no way to disable this message during the 30 days of the free trial permission.

The sentence "To solve the issue" does not mean "To remove the error message". It means "To know if you are allowed to use the package".

**Comment by cherniavskii** [comment]
Hi @nico-martinucci,
Why not use the license key in your test environment?

**Comment by nico-martinucci** [comment]
> Hi @nico-martinucci, Why not use the license key in your test environment?

This does not seem to work for me for some reason. I'm using vite/vitest, and have tried both top-level in `vitest.setup.ts` and in the `beforeAll` where I do other set-up mocking.
