### ISSUE TITLE
[charts] ChartsLegendPropsBase type is broken

### ISSUE THREAD

**Issue by VFritsch** [mui/mui-x#14561]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-ndxp8o?file=Demo.tsx%3AL41
Steps:
1. Import and add `<ChartsLegend/>` component
2. Add empty Array to `seriesToDisplay` property in `slotProps` -> `legend`
3. Object literal may only specify known properties, and 'seriesToDisplay' does not exist in type 'Partial<ChartsLegendPropsBase>'.

### Current behavior

Custom legend can't be used/displayed as `seriesToDisplay` property does not exist anymore.

### Expected behavior

`seriesToDisplay` property can be accessed again.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 22.5.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.7
    @mui/icons-material:  5.16.7
    @mui/lab: ^5.0.0-alpha.173 => 5.0.0-alpha.173
    @mui/material: ^5.16.7 => 5.16.7
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system: ^5.16.7 => 5.16.7
    @mui/types:  7.2.16
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.16.0 => 7.16.0
    @mui/x-charts-vendor:  7.16.0
    @mui/x-data-grid:  7.16.0
    @mui/x-data-grid-premium: ^7.16.0 => 7.16.0
    @mui/x-data-grid-pro:  7.16.0
    @mui/x-internals:  7.16.0
    @mui/x-license:  7.16.0
    @mui/x-tree-view: ^7.16.0 => 7.16.0
    @types/react: ^18.3.5 => 18.3.5
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript:  5.5.4
```
Browser used: Chrome - Version 128.0.6613.120 (64-Bit)
</details>

**Search keywords**: ChartsLegend, @mui/x-charts, seriesToDisplay

**Search keywords**:

**Comment by alexfauquette** [comment]
This look like a TS error.

In your reproduction, the error message come from the fact <ChartsLegend /> is not inside the `<PieChart />` so it does not have access to the context

This should let the code work

```diff
<PieCharts
  ... 
- />
+ >
<ChartsLegend ... />
+</PieChart>
```

AN the Typescript error message is something to fix on our side

**Comment by Samuel-Therrien-Beslogic** [comment]
Likely introduced here: https://github.com/mui/mui-x/pull/14392/files#r1764019386
