### ISSUE TITLE
[charts] LinePlot does not allow to use scaleType 'points'

### ISSUE THREAD

**Issue by mircowidmer** [mui/mui-x#14585]
### Summary

When I use `LineChart`, using the `scaleType` `point` works as expected:

```jsx
<LineChart
  width={500}
  height={300}
  series={[
    { data: pData, label: 'pv' },
    { data: uData, label: 'uv' },
  ]}
  xAxis={[{ scaleType: 'point', data: xLabels }]}
/>
```

When I use the `LinePlot` in a combined setup, I have no way of setting the `scaleType` to `point`.

See: https://mui.com/x/api/charts/axis-config/#axis-config-prop-scaleType

**Search keywords**: LinePlot ScaleType

**Comment by JCQuintas** [comment]
Hi @mircowidmer, it seems you are using composition. You can read more about it here: https://mui.com/x/react-charts/composition/

When using `LinePlot`, it **needs** to be inside a `(Responsive)ChartContainer` and all the props go in the `ChartContainer` itself, as that is the component that sets up all the necessary contexts we use internally. 

```tsx
    <ResponsiveChartContainer
      height={300}
      width={500}
      series={[
        {
          type: "line",
          data: [2, 5.5, 2, 8.5, 1.5, 5],
        },
      ]}
      xAxis={[
        {
          scaleType: "point",
          data: [1, 2, 3, 5, 8, 10],
        },
      ]}
    >
      <LinePlot />
    </ResponsiveChartContainer>
```

You can see it in action on this sandbox: https://codesandbox.io/p/sandbox/friendly-wing-tk8k95

**Comment by mircowidmer** [comment]
@oliviertassinari 

<img width="1487" alt="image" src="https://github.com/user-attachments/assets/56356b6f-dbfb-4649-9a4b-20783052f296">

The screenshot above is from the link you posted.

If I try to use the following segment:

```
<Box style={{width: '100%', height: '400px'}}>
  <ResponsiveChartContainer
    series={series}
    xAxis={[
      {
        id: 'exyear',
        data: dashboardStore.premiumTurnovers.map((premiumTurnover: DtoPremiumTurnover) => premiumTurnover.EXYEAR),
        scaleType: 'band',
      },
    ]}
    yAxis={[
      {
        id: 'prmin',
        scaleType: 'linear',
      },
      {
        id: 'turnover',
        scaleType: 'point',
      },
    ]}
    margin={{left: 100, right: 80}}
  >
    <BarPlot />
    <LinePlot />

    <ChartsXAxis position="bottom" />
    <ChartsYAxis
      label="Umsatz in CHF"
      position="left"
      axisId="turnover"
      sx={{
        [`& .${axisClasses.label}`]: {
          transform: 'translateX(-60px)',
        },
      }}
    />
    <ChartsYAxis
      label="Prämie in CHF"
      position="right"
      axisId="prmin"
      sx={{
        [`& .${axisClasses.label}`]: {
          transform: 'translateX(40px)',
        },
      }}
    />
    <ChartsTooltip />
  </ResponsiveChartContainer>
</Box>
```
I'll get the following error:
![image](https://github.com/user-attachments/assets/39afcb3a-94fc-4ae1-aec8-cebbdc2362b7)

**Comment by JCQuintas** [comment]
@mircowidmer can you provide a codesandbox with the current issue? 

It appears that it arrises from your specific implementation details, and without further information it is a bit hard to help you.

**Comment by JCQuintas** [comment]
You need to make your sandbox public :)

**Comment by mircowidmer** [comment]
Does it work now?

**Comment by JCQuintas** [comment]
@mircowidmer yeah it works

So for scales of type `band` and `point` you have to provide values for it, since they work as "distinct" values. The code below should work, but it might be the case that you don't want to use point, but `linear` instead.

```tsx
          {
            id: "turnover",
            scaleType: "point",
            reverse: true,
            data: data
              .map((premiumTurnover: any) => premiumTurnover.TURNOVER),
          },
```

As for the "circles", you can use `<MarkPlot/>` to render them. You can see them in use in the demos here: https://mui.com/x/react-charts/composition/#container-options

And also in the source code: https://github.com/mui/mui-x/blob/7120da2cdc72899efaf4ea5be0f13c292dce63f5/packages/x-charts/src/LineChart/LineChart.tsx#L144

**Comment by mircowidmer** [comment]
`<MarkPlot />` was all that was missing on the first look. Thank you!!
