### ISSUE TITLE
[pickers] DatePicker type input error

### ISSUE THREAD

**Issue by WhiteWolf-js** [mui/mui-x#14594]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/232c0ad3-87ad-4b24-909b-a490e5127b5a)
![image](https://github.com/user-attachments/assets/86d24860-09a4-4ac4-9e7d-36600a7ffba8)

The { maxDate} type I passed in is dayjs.Day.js ，but using ts checking there'is some error,But I think the type I am currently importing should be allowed

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datePicker

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by flaviendelangle** [comment]
I suspect that you have the problem described in [this doc section](https://mui.com/x/react-date-pickers/base-concepts/#typing-of-the-date).

If not, as @michelengelen said a reproduction case would help us a lot :+1:
