### ISSUE TITLE
[data grid] Id for ColumnMenuIconButton on datagrid 

### ISSUE THREAD

**Issue by DubbelF34140** [mui/mui-x#14595]
Hello I would like to know if this is possible and if so how to add a different id to each columnMenuIconButton via their field name ? 
![Image20240912122016](https://github.com/user-attachments/assets/75d266ca-964a-4214-9c6f-1d6fac20caeb)
on this button add one id for all field

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @DubbelF34140 ... not possible atm. 
The only way would be to build a custom cell renderer, but with that you would lose most of the built-in functionalities.

May I ask what your use case is?

**Comment by DubbelF34140** [comment]
This would be for the creation of automatic tests with robot framework in python which uses ids for this found among the buttons

**Comment by michelengelen** [comment]
The onlyu way to do that would be to use the `data-` attributes, but you cannot target the menu button with this.
