### ISSUE TITLE
[data grid] selecting cells by pressing keyboard arrows does not trigger onCellSelectionModelChange

### ISSUE THREAD

**Issue by Genomius** [mui/mui-x#14597]
### The problem in depth

Hello!

When you click on a cell with the mouse, the onCellSelectionModelChange function is triggered - everything is OK here.

If you hold down the shift key and click on the arrow key on the keyboard, the onCellSelectionModelChange function is triggered and the selected cells are returned - everything is OK here.

When you press the arrow key on the keyboard, the selected cell in the table changes according to the direction of the arrow of the pressed key, but the onCellSelectionModelChange function does not work.

Expected behavior:
when working with a table on the keyboard without using a mouse, if the selected cell changes, then in the onCellSelectionModelChange function you can get the current cell.

You can reproduce the problem here:
https://mui.com/x/react-data-grid/cell-selection/#controlled-cell-selection

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: onCellSelectionModelChange, keyboard

**Comment by michelengelen** [comment]
Hey @Genomius ... in your last example you would not keep on selecting cells, since you stop the selection mode (pressing an arrow key without modifier key `SHIFT`).

This will trigger the `onCellSelectionChange` callback with an empty object (`{}`) as the new selected cell model. 

Did you expect something else here?

**Comment by Genomius** [comment]
yes, you are right, the function returns {}.
is there any way I can get data about the selected cell when working with the keyboard?

> Hey @Genomius ... in your last example you would not keep on selecting cells, since you stop the selection mode (pressing an arrow key without modifier key `SHIFT`).
> 
> This will trigger the `onCellSelectionChange` callback with an empty object (`{}`) as the new selected cell model.
> 
> Did you expect something else here?

yes, you are right, the function returns {}.
can I somehow get data about the selected cell when working with the keyboard as when I left-click on it?

**Comment by michelengelen** [comment]
Yes ... you can select a cell with `SHIFT` + `SPACE` ... its also documented here: [Data Grid - Cell selection](https://mui.com/x/react-data-grid/cell-selection/)

**Comment by Genomius** [comment]
Thank you!
