### ISSUE TITLE
[charts] Chart Padding

### ISSUE THREAD

**Issue by ThreeCrown** [mui/mui-x#14590]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/chart-styling-issues-vjsvgy

Currently we are unable to access the ResponsiveChart Container to change properties through the slotProps.
I'm unsure how exactly we are supposed to access the chart padding and such for the actual chart. 
Currently, I am trying to remove the padding around the chart, because it doesn't display correctly when you set the height to 100px.

### Current behavior

At 100 px is squishes the whole chart to where you can only see the main xAxis line instead of the chart taking up 100% of it's container. perhaps a flex style to it would be more appropriate but I'm not sure how to properly manage the spacing or stylings because there are no classes and the slotProps do not seem to include it's container.

### Expected behavior

A flexible chart that takes up 100% of its wrapper  where we are setting the width and height.

### Context

A flexible chart that takes up 100% of its wrapper  where we are setting the width and height.

### Your environment

Doing this within code sandbox provided.

**Search keywords**: Chart Style Padding

**Comment by michelengelen** [comment]
Hey @ThreeCrown ... your Codesandbox is set to private. Could you make it public so we can have a look as well? Thanks!

**Comment by ThreeCrown** [comment]
@michelengelen I have marked it as unlisted so you should be able to view it now

**Comment by alexfauquette** [comment]
> I'm not sure how to properly manage the spacing or stylings because there are no classes and the slotProps do not seem to include it's container.


Effectively, this aspect is not handled by some CSS classes but by JS.

The `height`/`width` props set the dimension of the SVG component. And the `margin` prop defines the space between the "drawing area" (the rectangle defined by the axes) and the SVG border.

I can see in the codesandbox that you tried margin. with 0 values which left no space for axes. But with more gentle modification you could obtain something a bit better. For example with `margin={{ top: 10, bottom: 25, left: 30, right: 10 }}`

![image](https://github.com/user-attachments/assets/3c379ef7-9b0f-4a55-a7af-31ff5219e542)

I've added a border around the SVG such that margin are more visible.

Does that explanation helps you?
