### ISSUE TITLE
[data grid] Export to Excel or CSV Datagrid "Server"

### ISSUE THREAD

**Issue by TarasShyn** [mui/mui-x#14607]
### The problem in depth

I couldn’t find an exact solution to our problem. We're working with a vast dataset, (over 1k, and 10k) so we do the pagination, sorting, and filtering on the backend, utilizing the MUI Api on the front end. Still, when it comes to the export, we would like to omit pagination, meaning, we would like to export based on sorting and filtering only, so the Excel or CSV file contains the original dataset, currently based on our testing, we can export only what MUI received on each page, is there a way to handle the case that I described?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Excel, CSV, Export, Datagrid
**Order ID**: 97642
**Support ID**: 22307

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
