### ISSUE TITLE
[data grid] Continous height recalculation on paginated grid missing dimensions and auto height

### ISSUE THREAD

**Issue by KristiansenKA** [mui/mui-x#14636]
### Steps to reproduce

[Link to live example
](https://stackblitz.com/edit/react-9zyy1u-d86nrr?file=Demo.tsx)

Steps:
1. Render the data grid with pagination, no dimensions and auto height set to false
2. Make sure the grid overflows vertically
3. Make sure that the last step of pagination has less rows than the previous state to simulate a drop in height
4. Navigate to the last page

### Current behavior

The height seems to be calculated multiple times, simulating a slow transition of height decrease.

### Expected behavior

The height is recalculated once.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 128.0.6613.138
    Edge: 128.0.2739.79
    Safari: 17.5

Tested in Chrome
```
</details>

**Search keywords**: height recalculate

**Comment by michelengelen** [comment]
The grid does need a container with intrinsic dimensions to correctly calculate its own dimensions and the virtualization logic: [Layout](https://mui.com/x/react-data-grid/layout/)

This is "expected" behavior!
