### ISSUE TITLE
[pickers] Add support for date-fns v4

### ISSUE THREAD

**Issue by christopherschroer** [mui/mui-x#14635]
### Summary

Date-fns v4 has been released

https://blog.date-fns.org/v40-with-time-zone-support/

Pickers only support up to v3

### Motivation

This would allow developers to take advantage of the new time zone features provided by date-fns v4 without worrying about peer-dependency issues

**Search keywords**: Date-fns

**Comment by LukasTy** [comment]
Thank you for creating this issue. 👍 
We will be sure to include v4 in the peer dependencies. 😉 
As for the timezone support, that is a separate and way bigger topic that we have an issue: https://github.com/mui/mui-x/issues/10573 👍

**Comment by flaviendelangle** [comment]
Wow, I wasn't expecting `date-fns@4` before a long time :exploding_head: 

@LukasTy are you fine keeping the adapter named `AdapterDateFnsV3` until the alpha (where the name imprecision will go away), or do you want to re-export it, something like:

```ts
export { AdapterDateFnsV3 } from './AdapterDateFnsV3'
export { AdapterDateFnsV3 as AdapterDateFnsV4 } from './AdapterDateFnV3"
```

**Comment by LukasTy** [comment]
> Wow, I wasn't expecting `date-fns@4` before a long time 🤯

That's exactly my thoughts. 😆 That's why I didn't even think about another name for the adapter when we introduced it. 🙈 


> are you fine keeping the adapter named `AdapterDateFnsV3` until the alpha (where the name imprecision will go away), or do you want to re-export it, something like:

Yes, I would be completely fine with this compromise, unless we see too much confusion with it, then we can consider re-exporting it aliased. 👌
