### ISSUE TITLE
[data grid] Print export not working

### ISSUE THREAD

**Issue by bogdancbs** [mui/mui-x#14647]
### The problem in depth

Hello,

I am experiencing an issue with the built-in printing function of DataGrid Pro. When I click on the print button, the DataGrid Pro briefly collapses to output all rows, but the print preview window does not open as expected. Afterward, the table returns to its normal state without showing the print preview.

This behavior occurs specifically in Google Chrome, and it prevents the print dialog from appearing, on other browsers is ok.

Could you please assist in resolving this issue?

Thank you!

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Google Chrome
npx: installed 2 in 2.621s

  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.138
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.13.3
    @emotion/styled: ^11.10.6 => 11.13.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.7
    @mui/icons-material: ^5.11.11 => 5.16.7
    @mui/lab: ^5.0.0-alpha.133 => 5.0.0-alpha.173
    @mui/material: ^5.14.0 => 5.16.7
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/styled-engine-sc: ^5.11.11 => 5.14.12
    @mui/styles: ^5.14.4 => 5.16.7
    @mui/system:  5.16.7
    @mui/types:  7.2.16
    @mui/utils:  5.16.6
    @mui/x-charts: ^6.0.0-alpha.6 => 6.19.8
    @mui/x-data-grid: ^6.0.1 => 6.20.4
    @mui/x-data-grid-pro: ^6.15.0 => 6.20.4
    @mui/x-date-pickers: ^6.19.6 => 6.20.2
    @mui/x-license-pro:  6.10.2
    @types/react:  18.3.6
    react: ^18.2.0 => 18.3.1
    react-dom: ^18.2.0 => 18.3.1
    styled-components: ^5.3.9 => 5.3.11
```
</details>

**Search Keywords**: print in chrome, print not opening
**Order ID**: 68255

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
