### ISSUE TITLE
Unable to set minutesStep to 1-Minute Interval in DateTimePicker

### ISSUE THREAD

**Issue by hsengivc** [mui/mui-x#14646]
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/reverent-wind-t4pqpl?file=%2Fsrc%2FDemo.tsx%3A12%2C26

Steps:
1. set minuteStep={1} to datetimepicker

### Current behavior

Minute Interval Between Two Times is Set to 5 Minutes by default

### Expected behavior

Should Be Able to Set the Minute Interval to 1 Minute using `minutesStep={1}`

### Context

I am trying to set the minute interval to 1 minute so that each step in the time selector increments by 1 minute. However, it is showing a 5-minute interval even though I set `minutesStep={1}`

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: minutesStep, set minutesStep, minutesStep datetimepicker, minutesstep issue

**Comment by michelengelen** [comment]
Hey @hsengivc ... the `minutesStep` prop is there to restrict the time by 5 minutes steps regardless of the picker. What you want is achievable with the `timeSteps` prop. To render 1` minute intervals do this: `timeSteps={{ minutes: 1 }}`

**Comment by hsengivc** [comment]
Thanks @michelengelen , it works now..
