### ISSUE TITLE
[data grid] `apiRef.current.stopCellEditMode` don't work correctly with custom renderCell and renderEditCell on Enter click

### ISSUE THREAD

**Issue by laminesadiki** [mui/mui-x#14643]
### Context

I'm building a DataGrid table showing files and folders, permit to users to change the name for only the folders.
I want to build custom components for renderCell and renderEdit.  I achive that throw renderCell and  renderEdit property in the fileName field.

To switch between edit and view mode , I use `const apiRef = useGridApiContext();` with : 
- for renderCell component, I enable edit mode with `
apiRef.current.startCellEditMode({
         id: props.id,
         field: props.field,
      });
` 
- fort renderEdit component, I enable view mode and stop edit mode with `apiRef.current.stopCellEditMode({ id: props.id, field: props.field });`

I have a button (icon check) to do the switch between modes. but when I want to customize the Enter click keyboard, the switch mode don't work , but the console.log("click") printed.

I guess that the problem only with the Enter keyboard event.

### Current behavior

When I click on edit button, I can change the file name in the list with custom edit component, when I click via the Done (check icon) , I can return to view mode as expected. 
But with click on Enter button for the last item in the list, the Enter keyboard click does nothing.
the cell mode don't change to view mode using Enter Click only for last item. but work correctly for the above items. As mentionned in this demo video.

### Expected behavior
the last item should work correcly as the above items.

### Steps to reproduce

[Link to live example in CodeSandox](https://codesandbox.io/p/devbox/bug-edit-mode-with-renderedit-mfjvl4)

Video for reproducing the bug :
https://www.vidline.com/share/V0G2H2L3RA/296d71eaf9fb19b53c56633d12d96ab6

Steps:
1. Enter the codesandox
2. try to edit folder 1 , click Enter with keyboard (Will run correctly)
3. try to edit folder 3, click Enter (will not go correctly)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser Tested : Mozilla (Firefox) , Chrome
  System:
    OS: macOS 13.1
  Binaries:
    Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.18.1/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.138
    Edge: 118.0.2088.57
    Safari: 16.2
  npmPackages:
    @emotion/react: latest => 11.13.3 
    @emotion/styled: latest => 11.13.0 
    @mui/base:  5.0.0-beta.58 
    @mui/core-downloads-tracker:  6.1.0 
    @mui/icons-material: latest => 6.1.0 
    @mui/lab: latest => 6.0.0-beta.9 
    @mui/material: latest => 6.1.0 
    @mui/private-theming:  6.1.0 
    @mui/styled-engine:  6.1.0 
    @mui/system:  6.1.0 
    @mui/types:  7.2.16 
    @mui/utils:  6.1.0 
    @mui/x-data-grid: latest => 7.17.0 
    @mui/x-internals:  7.17.0 
    @mui/x-tree-view: latest => 7.17.0 
    @types/react: 18.2.25 => 18.2.25 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.2 => 5.0.2
```
</details>

**Search keywords**: data grid, stopCellEditMode, renderCell, renderEditCell, edit mode

**Comment by laminesadiki** [comment]
**UPDATE:** 
I see that the by removing the handleKeyDown event. there is a default event doing the same behaviour and it is not overrided. so, I think that overrinf the default event can fix the problem.

Now, the question , How Can I override the default Enter click event ?

**Comment by michelengelen** [comment]
This is not really a bug ... when you hit enter you are not stopping the edit mode at all.
For this to work you can just add this:
```tsx
if (e.code === 'Enter') {
   event?.preventDefault()
   console.log('Click Enter 8');
   handleDoneClick();
}
```

**Comment by laminesadiki** [comment]
thank you @michelengelen for your answer.
Yes, it work correctly now.
I just want to know more details why before I can't stop edit mode and what is the usage of event?.preventDefault() ?

**Comment by michelengelen** [comment]
So, its not super obvious, but what happens is that the edit mode actually stops, switches focus to the next cell and then starts a new edit mode. It all happens in a split second, so its not noticable.
The problem is with the second step here. When the focus switches to the next cell it automatically focuses the button inside and since the event bubbles up it will then trigger the 'onClick' method.
Why do you need that extra functionality to trigger `onKeyDown`? It works just as well without that.

**Comment by laminesadiki** [comment]
As I mentionned in the steps to reproduce above, also in the video attached here :
> ### Steps to reproduce
> 
> [Link to live example in CodeSandox](https://codesandbox.io/p/devbox/bug-edit-mode-with-renderedit-mfjvl4)
> 
> Video for reproducing the bug :
> https://www.vidline.com/share/V0G2H2L3RA/296d71eaf9fb19b53c56633d12d96ab6
> 
> Steps:
> 1. Enter the codesandox
> 2. try to edit folder 1 , click Enter with keyboard (Will run correctly)
> 3. try to edit folder 3, click Enter (will not go correctly)
> 

The bug only come for the last item folder 3, If you try to edit name , the Enter click will not work correctly.
but after adding event.preventDefault , its work fine.

**Comment by michelengelen** [comment]
So, is this resolved for you, or are you expecting something different?

**Comment by laminesadiki** [comment]
Yes, this is solved by adding event.preventDeault().
But I don't know why the default click on Enter works fine for the whole list of items without adding PreventDefault, but doesn't work with the last item in the list ?

**Comment by michelengelen** [comment]
> Yes, this is solved by adding event.preventDeault().
> 
> But I don't know why the default click on Enter works fine for the whole list of items without adding PreventDefault, but doesn't work with the last item in the list ?

Simply because there is no following cell, so it focuses the last one (which was just edited) and then starts editing mode again.

**Comment by laminesadiki** [comment]
Okaay, that explain the current behaviour.
thank you @michelengelen  for your answer and support.
As the problem is resolved, I will close this issue.
