### ISSUE TITLE
[charts] PieChart throws Uncaught DOMException when swiped on mobile layout in Firefox

### ISSUE THREAD

**Issue by mrerdem** [mui/mui-x#14654]
### Steps to reproduce

Link to live example: https://mui.com/x/react-charts/pie/

Steps:
1. Go to react pie chart page of MUI-X
2. Switch to mobile layout (on Firefox)
3. Enable touch simulation
4. Scroll the page vertically using the area with the pie chart
5. Repeat scrolling motion again (probably up to 3) if error is not thrown at first try

### Current behavior

Chart throws an error:
Uncaught DOMException: Element.releasePointerCapture: Invalid pointer id

and causes tooltip to stay permanently visible (only reproducable on Firefox for Android).

### Expected behavior

No error should be thrown and tooltip should become invisible after touch action is released.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: PieChart DOMException

**Comment by michelengelen** [comment]
Hey @mrerdem ... I have tried to reproduce the bug by following the steps you provided, but did not manage to do so. Could you maybe share a video of you forcing that bug? Thanks! 🙇🏼

**Comment by mrerdem** [comment]
It is definitely not clear in the video, but in my first try I could get the error in 5th swipe trial.
![Peek](https://github.com/user-attachments/assets/a32f0dd0-8070-43b5-9873-a6cdb9b4b59a)

The error at the 5th swipe is:
`Uncaught DOMException: Element.releasePointerCapture: Invalid pointer id
    NextJS 54
        onPointerLeave
        eB
        eH
        rh
        rh
        rm
        rS
        u4
        eD
        rS
        tZ
        tG
        rk
        ry
        rb
        rb
        hydrateRoot
        eE
        e
        x
        value
        I
        o
        u
        exports
        t
        exports
        ew
        eS
        e
        x
        value
        I
        o
        u
        promise callback*o
        u
        promise callback*o
        u
        promise callback*o
        u
        exports
        t
        exports
        eR
        eP
        78169
        promise callback*78169
        l
        <anonymous>
        O
        <anonymous>
        c
        <anonymous>
4330-993e7c78d57b2912.js:1
    NextJS 15
    forEach self-hosted:4288
    NextJS 39
`

**Comment by michelengelen** [comment]
Ok, I can reproduce now as well ... took me more tries and some swirling arouind on the pie chart area before it got that far. 

I'll add this to the board.

**Comment by alexfauquette** [comment]
Yes, to reproduce it, you need to touch down on one slice and touch up on another one. It's surprising that only firefox has this issue. can't reproduce it on chrome

**Comment by mrerdem** [comment]
A possible solution to #13885 could automatically solve this issue as well.
