### ISSUE TITLE
[data grid] Tree data children pagination

### ISSUE THREAD

**Issue by daviesgeek** [mui/mui-x#14663]
### The problem in depth

I'm trying to figure out how to properly paginate children rows when the grid is displaying tree data. It doesn't look like there's support for this use case. I have a case where I might need to support up to a few hundred children rows and those need to be paginated, as i can't fetch all of them at one time.
Is this 1) something that's supported and 2) if not, is this a use case that's on the roadmap for support? 3) if none of this, is there a good way for me to support this?

(I didn't think a live example super important, so didn't include one but i can if needed)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 14.5
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.138
    Edge: 128.0.2739.79
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1 
    @emotion/styled: ^11.10.6 => 11.11.5 
    @mui/base:  5.0.0-beta.24 
    @mui/core-downloads-tracker:  5.16.6 
    @mui/icons-material: ^5.8.2 => 5.14.18 
    @mui/lab: ^5.0.0-alpha.84 => 5.0.0-alpha.153 
    @mui/material: ^5.15.20 => 5.16.6 
    @mui/private-theming:  5.14.18 
    @mui/styled-engine:  5.14.18 
    @mui/styles: ^5.15.20 => 5.15.20 
    @mui/system: ^5.15.20 => 5.16.6 
    @mui/types:  7.2.9 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.12.1 
    @mui/x-data-grid-premium: 7.12.1 => 7.12.1 
    @mui/x-data-grid-pro:  7.12.1 
    @mui/x-date-pickers:  6.18.1 
    @mui/x-date-pickers-pro: 6.18.1 => 6.18.1 
    @mui/x-internals:  7.12.0 
    @mui/x-license:  7.12.0 
    @mui/x-license-pro:  6.10.2 
    @types/react: ^18.0.10 => 18.2.38 
    react: ^18.1.0 => 18.2.0 
    react-dom: ^18.1.0 => 18.3.1 
    typescript: ^4.7.2 => 4.9.5 
```
</details>

**Search keywords**: data grid, tree view, server side data, pagination
**Order ID**: 87473

**Comment by michelengelen** [comment]
Hey @daviesgeek ... we aren't currently supporting pagination of child rows.
@MBilalShafi do you know if we can provide a workaround for this?

**Comment by MBilalShafi** [comment]
Nested lazy-loading is planned for the future after the [root-level lazy-loading](https://github.com/mui/mui-x/issues/10857) is completed.
Here's the issue that covers this specific request: https://github.com/mui/mui-x/issues/14527
Feel free to share your requirements and (or) upvote the issue to see it land faster. 

> do you know if we can provide a workaround for this?

I don't think so there's a straightforward workaround for this in the userland as of now since we need to make some changes in the internal DOM structure before supporting that.

@arminmeh Should we set some groundwork in #13878 to help smoothen the work on #14527?

**Comment by daviesgeek** [comment]
Thank you both, appreciate the response

**Comment by MBilalShafi** [comment]
Closing in favor of #14527, subscribe to that one for updates.
