### ISSUE TITLE
[data grid] Column header get stuck with dragging styles

### ISSUE THREAD

**Issue by rodolffoteles** [mui/mui-x#14678]
### The problem in depth

Hi,

When dragging columns to perform the column reorder, sometimes the column header get stuck in the dragging state. The class `MuiDataGrid-columnHeader--dragging` is not removed even though the `columnHeaderDragEnd` event is emitted.

The most stable way I have to reproduce this is clicking and dragging on the edge of the menu icon button. The drag is suddenly aborted, even though I do not actually release the click, and the class is not removed.

**Demo:**
Reproducible on example of [the column ordering docs](https://mui.com/x/react-data-grid/column-ordering/). 

**Steps:**
1 - Click and drag the edge of the menu icon button on header
2 - See stuck header styles

**Recording:**
Video: 
https://github.com/user-attachments/assets/8edcf50b-0289-4dea-9768-a0819d43d9dc

Gif:
![Reorder](https://github.com/user-attachments/assets/734925df-6c61-4046-ba0a-a5e322322aea)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 12.7.3
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.138
    Edge: 128.0.2739.79
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.1 
    @mui/icons-material:  6.0.2 
    @mui/material: ^6.1.1 => 6.1.1 
    @mui/private-theming:  6.1.1 
    @mui/styled-engine:  6.1.1 
    @mui/system:  6.1.1 
    @mui/types:  7.2.17 
    @mui/utils:  6.1.1 
    @mui/x-data-grid:  7.17.0 
    @mui/x-data-grid-generator: ^7.17.0 => 7.17.0 
    @mui/x-data-grid-premium: ^7.17.0 => 7.17.0 
    @mui/x-data-grid-pro:  7.17.0 
    @mui/x-internals:  7.17.0 
    @mui/x-license:  7.17.0 
    @types/react: ^18 => 18.3.5 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 
    typescript: ^5 => 5.5.4 
</details>

**Search keywords**: data grid, column ordering

**Comment by k-rajat19** [comment]
Hi,
thanks for your feedback
I think dragging styles should be explicitly removed in this case, Currently, styles are removed by [0ms setTimeout](https://github.com/mui/mui-x/blob/master/packages/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx#L108-L110) but it seems like in this case it [got cleared](https://github.com/mui/mui-x/blob/master/packages/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx#L313) in `columnHeaderDragEnd` event before getting a chance to execute.
>The drag is suddenly aborted, even though I do not release the click, and the class is not removed.

And I think abortion of event in this case is bound to happen and I don't see anything that can be done about it.

**Comment by k-rajat19** [comment]
Here you can see improved behavior:
https://deploy-preview-14680--material-ui-x.netlify.app/x/react-data-grid/column-ordering/

**Comment by michelengelen** [comment]
Thanks for opening a PR @k-rajat19... I just assigned reviewers and triaged it. Should be picked up soon!
