### ISSUE TITLE
[pickers] Change "aria-label" of `DateTimePicker` button

### ISSUE THREAD

**Issue by raunakdeep** [mui/mui-x#14675]
### Steps to reproduce

Link to live example: (required)

go to https://mui.com/x/react-date-pickers/date-time-picker/ and try to change aria-label of button "choose date" to other like "choose new calendar date"

### Current behavior

aria-label change not supported 

### Expected behavior

aria-label change should support

### Your environment

https://mui.com/x/react-date-pickers/date-time-picker/

**Search keywords**: datetimepicker

**Search keywords**:

**Comment by michelengelen** [comment]
This works:
```tsx
<DateTimePicker
  label="Basic date time picker"
  slotProps={{ openPickerButton: { 'aria-label': 'Choose new calendar date' } }}
/>
```

**Comment by flaviendelangle** [comment]
I would suggest to override the `openDatePickerDialogue` localization instead.
Otherwise, you don't have another phrasing when their is a value.

**Comment by flaviendelangle** [comment]
Here is a [working example](https://stackblitz.com/edit/react-xg5pts?file=Demo.tsx)

```tsx
<DateTimePicker
  label="Basic date time picker"
  localeText={{
    openDatePickerDialogue: (date, utils, formattedDate) =>
      formattedDate
        ? `Choose new calendar date, selected date is ${formattedDate}`
        : 'Choose new calendar date',
  }}
/>
```
