### ISSUE TITLE
[data grid] Prevent scroll while in edit mode with cell selection enabled

### ISSUE THREAD

**Issue by FullStackDev0331** [mui/mui-x#14683]
### Steps to reproduce

Link to live example: (required)

(MUI DataGridPremium)
1:The datagrid jumps/scrolls when an editable cell is selected and the space bar is pushed.
2:How to add space in the text itself while in editing mode?

### Current behavior

The datagrid jumps/scrolls when an editable cell is selected and the space bar is pushed.
`unstable_onCellSelectionModelChange={handleCellSelectionModelChange}`
### Expected behavior

1:The datagrid jumps/scrolls when an editable cell is selected and the space bar is pushed.
2:How to add space in the text itself while in editing mode? It's currently scrolling.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Datagrid space key

**Comment by michelengelen** [comment]
Hey @FullStackDev0331 ... 

> The datagrid jumps/scrolls when an editable cell is selected and the space bar is pushed.

That's expected behavior. It works the same as if you were on a web page. Pressing `SPACE` will scroll down.

> How to add space in the text itself while in editing mode?

This works for me. No scrolling while in editing mode. Could you provide a more detailed reproduction scenario, or at best a live code reproduction?

**Comment by michelengelen** [comment]
> I would like it to behave like a spreadsheet. video(my project screen)

Hey @FullStackDev0331 ... There is no video .. and spreadsheets not really have a common ground in how those things work.

**Comment by FullStackDev0331** [comment]
@michelengelen 
sorry Michel
I sent the wrong video. 
In the spreadsheet, when I hold down the space key, a blank character is written.
The datagrid jumps/scrolls when an editable cell is selected and the space bar is pushed.
[Screencast from 09-20-2024 11:47:06 PM.webm](https://github.com/user-attachments/assets/9407bf4f-896a-426b-aa69-21861cedaf2f)
[Screencast from 09-20-2024 11:45:25 PM.webm](https://github.com/user-attachments/assets/12263795-3f2c-4ff4-acf5-01e7e30bf05b)

**Comment by FullStackDev0331** [comment]
@michelengelen cc @zenazn  @genepaul 
In the spreadsheet, when I hold down the space key, a blank character is written.
The datagrid jumps/scrolls when an editable cell is selected and the space bar is pushed.
How can we solve the above problem?

**Comment by MBilalShafi** [comment]
Hey @FullStackDev0331, I recently responded to a similar query, can you check if the solution mentioned [here](https://github.com/mui/mui-x/pull/8180#issuecomment-2376162929) could work for you?
