### ISSUE TITLE
[data grid] Bug rendering buttons with special characters in a custom Toolbar

### ISSUE THREAD

**Issue by fsilva-exadel** [mui/mui-x#14688]
### Steps to reproduce

Link to live example: [(required)](https://stackblitz.com/edit/react-btem8f?file=Demo.tsx)

Steps:
1. Create a custom toolbar with buttons where there are special characters (Example, testing (µg))
2.  In the image below, you can see the column header with special characters correctly rendered, while the button is not doing the same (Even though the button's description is correct in the HTML code).
![image](https://github.com/user-attachments/assets/5f454363-a0a0-4772-8aff-b6a2eb1fdcdf)

3. The live example shows the issue happening in the latest version
4. The code sample shown in the image is attached to support ticket #22469 (I couldn't implement using @mui/x-data-grid-premium using stack blitz).

### Current behavior

Buttons included in a custom Toolbar are not rendering  special characters (like µg) correctly

### Expected behavior

Buttons included in a custom Toolbar rendering special characters (like µg)

### Context

We've been using MUI datagrid (Premium) and implementing a custom ToolBar with buttons to do custom actions (hide columns, for example).

### Your environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.97 
    @mui/core-downloads-tracker:  5.10.5 
    @mui/icons-material: ^5.10.3 => 5.10.3 
    @mui/material: ^5.10.5 => 5.10.5 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine:  5.10.5 
    @mui/styles: ^5.10.3 => 5.10.3 
    @mui/system:  5.10.5 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.11 
    @mui/x-data-grid:  5.17.11 
    @mui/x-data-grid-premium: 5.17.11 => 5.17.11 
    @mui/x-data-grid-pro:  5.17.11 
    @mui/x-date-pickers: ^6.19.6 => 6.19.6 
    @mui/x-date-pickers-pro: ^6.19.6 => 6.19.6 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react: ^18.0.20 => 18.0.20 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.8.3

**Search keywords**: toolbar
**Order ID**: 85186

**Comment by michelengelen** [comment]
This is happening because the Button will transform the text.

adding a `sx` to change that the Button will render the Text correctly:

```tsx
const TestingToolbar = () => {
  const buttonLabel = "testing (ng/µL) (µg)";

  return (
    <GridToolbarContainer>
      <GridToolbarColumnsButton />
      <GridToolbarFilterButton />
      <GridToolbarDensitySelector />
      <Button
        key={`action-testing`}
        onClick={() => {
          alert("testing");
        }}
        sx={{
          textTransform: "none",
        }}
      >
        {buttonLabel}
      </Button>
    </GridToolbarContainer>
  );
};
```

check out this quick [DEMO](https://codesandbox.io/p/sandbox/sleepy-gagarin-c7qrf7)

**Comment by fsilva-exadel** [comment]
I tested and it worked. Thank you for your help.
