### ISSUE TITLE
[question] Do DataGrid and TreeView support Joy?

### ISSUE THREAD

**Issue by atillaaliyev** [mui/mui-x#14687]
### The problem in depth

I want to use Joy with DataGrid or TreeView. I have seen a discussion about it (especially DataGrid). However, I don't understand, did you solve this problem?
Thanks,

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Joy DataGrid, Joy TreeView
**Order ID**: 49721

**Comment by michelengelen** [comment]
I don't think so, but @romgrk (data grid) and @flaviendelangle (tree view) should know 100% if we do.

**Comment by flaviendelangle** [comment]
The Tree View have no official support for Joy UI.
You could re-create a Joy version using the [useTreeItem2 hook](https://deploy-preview-14551--material-ui-x.netlify.app/x/react-tree-view/tree-item-customization).

Joy UI development is currently on hold so the X components are not focusing on its support :+1:

**Comment by atillaaliyev** [comment]
I understood. However, I want to learn one thing , Will Joy be second class citizen for MUI-X ? I design ui library for my company based on Joy.  Should I be worried or is it temporary situation ?

**Comment by flaviendelangle** [comment]
MUI X is following the overall strategy of the company which is to hold Joy UI development until we have a clear vision on which place it will have inside the MUI ecosystem.

But this is a temporary solution. As soon as Joy UI development will resume, MUI X will work to have it integrated as first class citizen.

And note that we are not sleeping on this topic until we have a green light. One of our main ongoing topic is to make MUI X more design agnostic and easier to integrate with other design systems (provided by MUI or third party like AntDesign, Mantine, Shadcn or even your own in house design system). So when we will resume the work on Joy UI, it will be to provide a far superior experience than we could have brought to you some time ago (no bundling of `@mui/material` being an obvious one).

**Comment by MBilalShafi** [comment]
For Data Grid, as @flaviendelangle mentioned, the proper support should be possible after our components are design agnostic and this effort is already one of the main priorities for the team.

A while back, we did an experiment with the Joy UI which isn't perfect but could give you a starting point on some visual design compatibility with the Joy UI. Here's the demo: https://github.com/mui/mui-x/blob/d55b1215fb1705b11e8d2688793e51c1aeb3ccbb/docs/data/data-grid/joy-ui/GridJoyUISlots.tsx

A word of caution, this is just an experiment done a while back and may contain some outdated styling, please verify if it works as per your expectations if you want to use it.
