### ISSUE TITLE
[charts] Listener for X axis value in tooltip

### ISSUE THREAD

**Issue by ceyxasm** [mui/mui-x#14689]
### Steps to reproduce

Not exactly a new bug; but I want to be be able to update the value of a variable depending upon the value showed on a tool tip; for custom rendering of more info ( the info that needs to be rendered is not related to MUI-X

![image](https://github.com/user-attachments/assets/f56d0d8c-2a79-430e-9bae-873245188296)
For example here, hovering shows a tooltip with coordinates (5, 8.5) and I want to be able to update an internal state variable with these values. 
And I am not sure how exactly to do this.

If I have the time-stamp of the point being explored, I can generate and show more information about the time-stamp (ex: events that happened at that time) which could explain the corresponding value in Y-axis

**Search keywords**: interactive display,

**Comment by alexfauquette** [comment]
This will probably be related [#13852](https://github.com/mui/mui-x/issues/13852) For now, the issue is that you only have access to the context from inside the SVG. To see how, have a look a the newly released tooltip demo

https://mui.com/x/react-charts/tooltip/#overriding-content-2

**Comment by ceyxasm** [comment]
Thanks. 
This issue got solved using `onAxisClick` handler. Got all what I needed from it.
Closing.
