### ISSUE TITLE
[question]  Date columns with null values

### ISSUE THREAD

**Issue by zebamba** [mui/mui-x#14692]
### The problem in depth

I have specifics date fields with null values from the database.

The issue is date type columns only accepts Date object, I would like use date filters.

I don't think the solution is to have new Date(null) on valueGetter.

How do I work around as it breaks the Grid rendering or is there a way to have null values on date type columns?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Column date type
**Order ID**: 97176

**Comment by MBilalShafi** [comment]
@zebamba What UX do you intend to have when there's a `null` date?
Should it be similar to the one in this demo: https://mui.com/x/react-data-grid/#pro-plan? (try clearing a date in a Date column)

It'd be great if you could provide a live reproduction to better visualize the pain points with the current implementation. For example with using the `valueGetter`.

You could follow this guide to prepare the reproduction: https://mui.com/x/introduction/support/#bug-reproductions
