### ISSUE TITLE
DataGrid performance degrades during scrolling

### ISSUE THREAD

**Issue by chucamphong** [mui/mui-x#14708]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/devbox/suspicious-darkness-76qsnt

### Current behavior

Setting the default loadingOverlay in slotProps leads to performance issues in the DataGrid when scrolling.

```
MuiDataGrid: {
  defaultProps: {
    slotProps: {
      loadingOverlay: {
        variant: "linear-progress",
        noRowsVariant: "linear-progress",
      },
    },
  },
},
```

![image](https://github.com/user-attachments/assets/124821a5-62e4-46c6-b4a0-01cff00fce24)

When I configure it as shown below, it no longer seems to lag:
```jsx
<DataGrid
  // ...
  slotProps={{
    loadingOverlay: {
      variant: 'linear-progress',
      noRowsVariant: 'linear-progress',
    }
  }}
/>
```
![image](https://github.com/user-attachments/assets/a8c7ad0a-b423-4b35-b59c-ebadd3316f89)

### Expected behavior

Performance is not reduced when scrolling

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 22.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.1 
    @mui/icons-material: ^6.1.1 => 6.1.1 
    @mui/material: ^6.1.1 => 6.1.1 
    @mui/material-nextjs: ^6.1.1 => 6.1.1 
    @mui/private-theming:  6.1.1 
    @mui/styled-engine:  6.1.1 
    @mui/system:  6.1.1 
    @mui/types:  7.2.17 
    @mui/utils:  6.1.1 
    @mui/x-data-grid: ^7.18.0 => 7.18.0 
    @mui/x-internals:  7.18.0 
    @types/react: ^18 => 18.3.8 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1
    typescript: ^5 => 5.6.2
```
</details>

**Search keywords**: lag, scroll

**Comment by MBilalShafi** [comment]
@chucamphong I could not reproduce the issue on the attached devbox. Could you provide reproduction steps or (and) a video showing the reproduction?

**Comment by MBilalShafi** [comment]
I could not observe any significant frame drop in the above example (tested on a Macbook M1 Pro machine).

https://github.com/user-attachments/assets/bcc66c4b-064b-4f68-8cc5-15144500581f

Are there some extra steps needed before the scroll to achieve the frame drop? Moreover, are you using any CPU throttling during testing?

**Comment by romgrk** [comment]
Linked: https://github.com/mui/mui-x/issues/10033
