### ISSUE TITLE
DateRangePicker value is truncated on MAC

### ISSUE THREAD

**Issue by HJK181** [mui/mui-x#14736]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-n6enhx?file=Demo.tsx

Steps:
1. select a date range and see the input value to-date is truncated

### Current behavior

The selected input data range value is not fully visible on MAC but on different OS like Linux.

MAC:
![Bildschirmfoto 2024-09-26 um 10 19 53](https://github.com/user-attachments/assets/5a609d7e-fc61-4073-99f1-6a056f868146)
Linux:
![image](https://github.com/user-attachments/assets/c5d45a6b-d578-43d8-bf8c-fe87c8701932)

### Expected behavior

The complete value of the date range picker value is visible regardless of the OS

### Your environment

see the stackblitz package.json

**Search keywords**: DateRangePicker truncated MAC
**Order ID**: 85015

**Comment by flaviendelangle** [comment]
The input has the width of any regular input. It's default width is determined by the browser.
We are not enforcing any minimal width to avoid conflicting with the layout you are using.

Here is [an example using a flex container](https://stackblitz.com/edit/react-n6enhx-uctznx?file=Demo.tsx)

**Comment by HJK181** [comment]
> It's default width is determined by the browser.
This doesn't seem to be true, as for both screenshots Chrome was used. The difference is just the OS.

So you say it's just a coincidence that on Chrome, Firefox on Linux the width of the input is just wide enough to fit the complete input value?

**Comment by flaviendelangle** [comment]
> So you say it's just a coincidence that on Chrome, Firefox on Linux the width of the input is just wide enough to fit the complete input value?

Yes

> This doesn't seem to be true, as for both screenshots Chrome was used. The difference is just the OS.

The browser might have a default behavior based on some other attributes (device, OS, screen dimension).
But we are not applying any custom logic to make sure the width fits the content.
