### ISSUE TITLE
[data grid] Suggestion in dropdown of filter

### ISSUE THREAD

**Issue by bkolubenka** [mui/mui-x#14757]
### The problem in depth

We have some columns with a lot of values.  As per typing on filter value it's should get list of suggestions as dropdown. We want to implement same behavior as in autocomplete in in column data frid filters. for example for operator contains.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: dropdown, filter, data-grid
**Order ID**: 83454

**Comment by michelengelen** [comment]
Hey @bkolubenka ... you can customize the header filter with the `renderHeaderFilter` prop: [renderHeaderFilter method](https://mui.com/x/react-data-grid/filtering/header-filters/#renderheaderfilter-method)

Related to https://github.com/mui/mui-x/issues/14071
