### ISSUE TITLE
[data grid] Include group header name in the columns panel

### ISSUE THREAD

**Issue by Vagizova** [mui/mui-x#14751]
### Summary

when we have column groups, it is quite possible that within the groups there will be columns with the same names. In this case, in `columnMenuColumnsItem` these two (or more) variants will not differ at all, since in `columnMenuColumnsItem` there is no division into groups

### Examples

for example I have few params and their measured (and other) values. 

![Screenshot 2024-09-27 at 14 53 10 (1)](https://github.com/user-attachments/assets/009eb522-177d-40ac-be26-f30fcccabb57)

### Motivation

a clearer understanding of which columns will be hidden.

**Search keywords**: columnMenuColumnsItem headerName label

**Comment by MBilalShafi** [comment]
Thanks for the issue. I've added a `waiting for 👍` label to see demand for this and prioritize accordingly.
Please feel free to leave an upvote on the issue description.

**Comment by Vagizova** [comment]
I think this is easy to do on our side👌🏻
