### ISSUE TITLE
[pickers] The month in the toolbar is not capitalized when using Danish locale

### ISSUE THREAD

**Issue by anders-noerrelykke** [mui/mui-x#14773]
### Summary

The Danish localisation of `Datepicker` and `DateTimePicker` months presents the month name in all lowercase.
![image](https://github.com/user-attachments/assets/99028f8b-e901-4b33-b78b-f2e3e1302b53)
Although this is technically correct for mid-sentence month names, I would argue that this case would essentially be the start of a sentence/stand-alone word, why the month should be capitalized. It would be sufficient to be able to toggle this through an extra prop, as I agree that it makes sense to not always capitalize it.

English (US) version:
![image](https://github.com/user-attachments/assets/2c7de1d6-f221-4e20-a77e-4c99e412ec96)

### Examples

https://mui.com/x/react-date-pickers/localization/

![image](https://github.com/user-attachments/assets/22e7f491-3947-49e3-a2c7-8a8cf45f4cad)
(forgive my poor shop skills)

### Motivation

Generally overrides for selected locale names would be great - the documentation already have support for a lot of these modifications.

**Search keywords**: datepicker datetimepicker

**Comment by michelengelen** [comment]
Hey @anders-noerrelykke ... I can confirm that this is a "problem" with date-fns:

https://github.com/date-fns/date-fns/blob/6c70ac6d073ebe869e42795f5e71dfecf5abbea0/src/locale/da/_lib/localize/index.ts#L32-L45

Compared to other locales where the Month-names are capitalized (e.g. 'de'):
https://github.com/date-fns/date-fns/blob/6c70ac6d073ebe869e42795f5e71dfecf5abbea0/src/locale/de/_lib/localize/index.ts#L36-L49

**Comment by flaviendelangle** [comment]
We could decide to capitalize them using CSS, but I fear we could run into edge cases (it should support other alphabet correctly for example)

**Comment by anders-noerrelykke** [comment]
Hi Flavien,

I found a formatting workaround for this specific issue in `DatePicker`/`DateTimePicker` - this way it can be done without interfering with the remaining `date-fns` localizations:

 ```
slotProps={{
          ...
          calendarHeader: { sx: { textTransform: 'capitalize' } }
          ...
        }}
```

Leaving this here for anyone who might need it - thank you again for looking into this 😃

**Comment by anders-noerrelykke** [comment]
Hi Flavien,

I found a formatting workaround for this specific issue in `DatePicker`/`DateTimePicker` - this way it can be done without interfering with the remaining `date-fns` localizations:

 ```
slotProps={{
          ...
          calendarHeader: { sx: { textTransform: 'capitalize' } }
          ...
        }}
```

Leaving this here for anyone who might need it - thank you again for looking into this 😃

**Comment by michelengelen** [comment]
> We could decide to capitalize them using CSS, but I fear we could run into edge cases (it should support other alphabet correctly for example)

I thought the same thing. It's also hard to say if this is the default behavior in any other language, so it is probably best to stay with the string we get from the date packages.

@anders-noerrelykke solution seems good enough to justify not interfering with this.

@samuelsycamore should we add a little info box to this section to prevent any misunderstanding in the future? [With date-fns](https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns)

**Comment by flaviendelangle** [comment]
I'm not sure it's worth adding in the Date FNS introduction section
I would wait for a 2nd complain before adding it to the doc, and target [this section](https://mui.com/x/react-date-pickers/adapters-locale/#custom-toolbar-format) instead.
