### ISSUE TITLE
[data grid] Datasource receives old data

### ISSUE THREAD

**Issue by bukerok** [mui/mui-x#14793]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-tsvwe1?file=Demo.tsx

Steps:
1. Click "Change datasource"

### Current behavior

Error thrown because `getGroupKey` from new datasource returns nulls for old data. 

### Expected behavior

Old data not processed with new datasource props and error not thrown.

### Context

Use case: allow user to change columns for the grid with treeData view and request new data when columns changed. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

System:
    OS: macOS 14.6.1
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 8.19.2 - ~/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 129.0.6668.60
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4 
    @emotion/styled: 11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.15 
    @mui/icons-material: 5.15.15 => 5.15.15 
    @mui/lab: 5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: 5.15.15 => 5.15.15 
    @mui/private-theming:  5.16.5 
    @mui/styled-engine:  5.16.4 
    @mui/system:  5.16.5 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-charts: 7.11.1 => 7.11.1 
    @mui/x-data-grid:  7.18.0 
    @mui/x-data-grid-pro: 7.18.0 => 7.18.0 
    @mui/x-date-pickers: 7.3.2 => 7.3.2 
    @mui/x-date-pickers-pro: 7.3.2 => 7.3.2 
    @mui/x-internals:  7.18.0 
    @mui/x-license: 7.6.1 => 7.6.1 
    @types/react: 18.2.47 => 18.2.47 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.5.4 => 5.5.4 
</details>

**Search keywords**: DataGridPro, treeData
**Order ID**: 91929

**Comment by michelengelen** [comment]
@MBilalShafi After playing around with this a bit it seems @bukerok is absolutely right.
The `getGroupKey` method seems to receive the "old" data from the 1st dataSource. Not sure if we have thought of this before, but it seems like we should adjust this.

<img width="442" alt="Screenshot 2024-10-01 at 17 03 21" src="https://github.com/user-attachments/assets/2a52f382-40e0-4f90-ac53-6c48dc169e3b">

I simplified the code a bit: [DEMO](https://stackblitz.com/edit/react-tsvwe1-pbdgv6?file=Demo.tsx)

**Comment by michelengelen** [comment]
Thanks @MBilalShafi 💪🏼
