### ISSUE TITLE
[data grid] Excessive whitespace when scrolling to right 

### ISSUE THREAD

**Issue by djairhogeuens** [mui/mui-x#14816]
### Steps to reproduce

Link to live example: https://mui.com/material-ui/getting-started/templates/dashboard/

Steps:
Scroll to the right in the data grid

### Current behavior

For some reason, there is an excessive white space on the right of the data grid within it's container. You can see it when you scroll to the right in the data grid.

### Expected behavior

No possibility to scroll right if all content is displayed in the container. Wen scrolling to the right is allowed due to not all content being displayed in the container, the scroll should stop at the end of the table without any excessive whitespace.

### Your environment

Chrome Version 129.0.6668.60 (Official Build) (64-bit)

**Search keywords**: data grid, scroll

**Comment by romgrk** [comment]
@KenanYusuf I think you worked on something related to this recently, could you handle this one?

**Comment by KenanYusuf** [comment]
@romgrk I can take a look at this in a couple of weeks (occupied with mobile view work until then). If anyone wants to take a look at this before then, please feel free.

**Comment by kalyan90** [comment]
@romgrk I can try check on this issue, would I need to sign CLA?

**Comment by romgrk** [comment]
Not unless you touch a file inside the `*-(pro|premium)` packages, but layout bugs should be in the core (aka community) packages. Feel free to look into it. Open a draft PR if you want to take it, otherwise I'll look into it myself.

IME, that issue is caused by dangling/floating elements that poke outside of their container's width, usually in the headers container.

**Comment by kalyan90** [comment]
> Not unless you touch a file inside the `*-(pro|premium)` packages, but layout bugs should be in the core (aka community) packages. Feel free to look into it. Open a draft PR if you want to take it, otherwise I'll look into it myself.
> 
> IME, that issue is caused by dangling/floating elements that poke outside of their container's width, usually in the headers container.

@romgrk added a PR for this issue https://github.com/mui/mui-x/pull/14864. Thank you

**Comment by KenanYusuf** [comment]
Looks like this was solved with #14864 - thanks @kalyan90.
