### ISSUE TITLE
Export AdapterDayjs from @mui/x-date-pickers

### ISSUE THREAD

**Issue by shaikh-kamran** [mui/mui-x#14833]
### Summary

If i try to import AdapterDayjs from @mui/x-date-pickers, its throws error, whereas LocalizationProvider and DatePicker can be imported properly, on inspection i see AdapterDayjs is not import in main file.

Is there any reason for not importing AdapterDayjs?

### Examples

import { LocalizationProvider, AdapterDayjs, DatePicker } from '@mui/x-date-pickers';

Module '"@mui/x-date-pickers"' has no exported member 'AdapterDayjs'.ts

**Search keywords**: mui/x-date-pickers

**Comment by LukasTy** [comment]
Hello @shaikh-kamran.

> Is there any reason for not importing AdapterDayjs?

Yes, there is a reason—it's to support multiple date libraries (adapters) and have their dependencies as optional. 😉 
https://github.com/mui/mui-x/blob/52601483fbc978b1f3d0f99562b20d807889e06b/packages/x-date-pickers/package.json#L71-L99
If we exported them at the root, everyone would have to download all the supported adapters.

**Comment by shaikh-kamran** [comment]
@LukasTy When i build my react app and serve it on express, i am getting below error
`
export { AdapterDayjs } from "./AdapterDayjs.js";
^^^^^^

SyntaxError: Unexpected token 'export'
`
When i export it main file, it doesnt

**Comment by LukasTy** [comment]
> When i build my react app and serve it on express, i am getting below error

I'm sorry, but we can't help you without a reproduction example. 🤷 
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.
A live example would be perfect. [This guide](https://mui.com/x/introduction/support/#bug-reproductions) should be a good starting point. Thank you!
