### ISSUE TITLE
[docs] Pinning functionality dose not work for columns in docs example

### ISSUE THREAD

**Issue by masoud-keykha** [mui/mui-x#14850]
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/master-detail/#disable-detail-panel-content-scroll

Steps:
1. Click on any column menu
2. Click on Pin to left or Pin to right
3. Dose not work

Solution: Using pinnedColumns and onPinnedColumnsChange

Code:

  ```
const [pinnedColumns, setPinnedColumns] = useState({
    left: [GRID_DETAIL_PANEL_TOGGLE_FIELD],
  });

  const handlePinnedColumnsChange = useCallback((updatedPinnedColumns) => {
    setPinnedColumns(updatedPinnedColumns);
  }, []);

<DataGridPremium
{ ...props }
          pinnedColumns={pinnedColumns}
          onPinnedColumnsChange={handlePinnedColumnsChange}
 />
```

### Current behavior

With current behavior pinning dose not work  because pinnedColumns prop of data grid is staticky  GRID_DETAIL_PANEL_TOGGLE_FIELD

### Expected behavior

Works correctly all features of data grid

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: pin, pin to left, pin to right

**Comment by kalyan90** [comment]
DataGridPro pin columns is working fine. Just have to update the demo for Disable detail panel section. Have raised a PR for the same https://github.com/mui/mui-x/pull/14853
