### ISSUE TITLE
[data grid] Ability to combine by multiple logic operators and group them

### ISSUE THREAD

**Issue by victorct-tradeengage** [mui/mui-x#14869]
### Summary

Ability to combine logic operators and group them, supposing we have a table of Users with the following columns:
- State (ie: TX, KY)
- Onboarding Date
- Status

It would be amazing to filter all the Users whose State is TX and who Onboarded Before November 10 2023 or  State is KY and Onboarded before December 24, 2023. Currently is impossible to filter this way as all filter operators need to either be AND or OR. Ideally, the user has the ability to group the filters (ie:  `((State == TX AND Date < Today) Or (State == KY And Date > Today)  and Status == ACTIVE) )`

**Search keywords**: logic-operator, filters

**Comment by michelengelen** [comment]
Thanks for opening this @victorct-tradeengage 
I'll add this to the board for our team to have a look at it. 👍🏼

**Comment by michelengelen** [comment]
Closing this in favor of #14897 ... We will track progress on this (and other improvements there!)

**Comment by oliviertassinari** [comment]
> group them

Duplicate as #4217?
