### ISSUE TITLE
[DateRangePicker] Month and Year view

### ISSUE THREAD

**Issue by gabbi-pf** [mui/mui-x#14874]
### The problem in depth

We need to be able to set the view to year, month, and/or day in the Date Range Picker. As far as we can tell, this is possible with the Date Picker by changing the `view` property, but the Date Range components do not have the `view` property.
Can we enable this behavior ourselves in the Date Range components, in any way? If not, are you planning to support it?

Expected behavior:
Clicking on month/year in the header opens the year view. Selecting a year opens the month view, and selecting a month returns to the "normal" view of days in the month. See example of behavior in `<DatePicker views={["year", "month", "day"]}/>` [here](https://mui.com/x/react-date-pickers/date-picker/#views).

Current behavior:
The year/month in the header is not interactive and cannot be clicked when using any of the Date Range Pickers. 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.5.1 - ~\.nvm\versions\node\v20.5.1\bin\node.EXE
    npm: 9.8.0 - ~\.nvm\versions\node\v20.5.1\bin\npm.CMD
    pnpm: 9.4.0 - ~\.nvm\versions\node\v20.5.1\bin\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.98)
  npmPackages:
    typescript: ^5.4.3 => 5.4.3
```
</details>

**Search keywords**: view, date range picker, date range
**Order ID**: 60962

**Comment by flaviendelangle** [comment]
Duplicates #4546

You can find this issue to track our advancement on the topic, this is not yet supported but we plan to add support for it at some point

**Comment by gabbi-pf** [comment]
@flaviendelangle Do you think you could look at the question asked in the issue you referred us to? It seems mislabeled, and we would need an estimate to avoid replacing MUI X DatePickers in our applications.
