### ISSUE TITLE
[pickers][DatePicker] readOnly UX when focused

### ISSUE THREAD

**Issue by croraf** [mui/mui-x#14872]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/beautiful-montalcini-hzlc9p?file=%2Fsrc%2FDemo.tsx

Steps:
1. focus the readOnly DatePicker either with mouse or with keyboard

### Current behavior

Notice that date format is presented to the user and MM selected, suggesting the user that the field can be edited.

![image](https://github.com/user-attachments/assets/2659c8d6-1f90-476a-9f6c-d7a97aea16e0)

### Expected behavior

The date format should not be presented to the user if readOnly.

### Context

In shrinked version, only this should be adjusted (that the format is not presented to the user). 

But also there is a question what should happen with the non-shrinked label when the `readOnly` field is focused - should it shrink or not. (This is not concerning me specifically, because I use always shrinked labels).

There is some discussion about this here: https://github.com/mui/mui-x/issues/11802#issuecomment-1907923434

**Search keywords**: placeholder label DatePicker DateTimePicker readOnly disabled

**Comment by michelengelen** [comment]
Thanks for raising this @croraf ... I'll add this to the board. 👍🏼

**Comment by flaviendelangle** [comment]
I renamed #11802 which is talking about the same topic
Closing this one as duplicated
