### ISSUE TITLE
[data grid] Horizontal scroll buggy after vertical scroll

### ISSUE THREAD

**Issue by Lewis5989** [mui/mui-x#14879]
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/scrolling/
The website produces the same issue as i have in my project

Steps:
1. move the vertical scroll bar 
2. move the horizontal scroll bar
3. move the vertical scroll bar
4. click in the horizontal scroll bar area to make the scroll bar snap to a specific point  

### Current behavior

Instead of moving to the correct horizontal view of the table. The scroll bar indicator moves but the view of the table stays the same . If you click the bar to snap the position again in the same direction, the view will correct. 
However if you click on opposite sides of the scroll indicator, the view will stay the same and only the indicator will move.

### Expected behavior

The view of the table should move when the scroll indicator changes

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: horizontal scroll
**Order ID**: 89003

**Comment by michelengelen** [comment]
Hey @Lewis5989 ... I could not reproduce this issue.
Could you make a short screencapture of it showing what you did and post it here?
That would be helpful! Thanks!

**Comment by Lewis5989** [comment]
https://github.com/user-attachments/assets/bee13bc4-6441-44d6-8220-cd6ded0f63e3

**Comment by cherniavskii** [comment]
@Lewis5989 Thanks for the video!
I cannot reproduce this on MacOS, I'll give Windows a try.

**Comment by cherniavskii** [comment]
Can't reproduce it in Chrome on Windows 11


https://github.com/user-attachments/assets/11185cf7-c3c5-42e6-8ea8-b0d33e7fb0f5
