### ISSUE TITLE
[charts] Allow `dataset` to be used with `ScatterChart`

### ISSUE THREAD

**Issue by lgnbhl** [mui/mui-x#14875]
### Related page

https://mui.com/x/react-charts/scatter/

### Kind of issue

Missing information

### Issue description

There is no minimal reproducible examples using the 'dataset' parameter for ScatterChart and PieChart (like the basic example using BarChart). Learning how to use MUI X, I was not able to use the 'dataset' argument with ScatterChart and PieChart. 

Would it be possible to add an minimal example for ScatterChart and PieChart using the 'dataset' argument (similar to the basic example in the BarChart documentation)?

### Context

As a beginner in React, I tried to use the 'dataset' parameter with ScatterChart without success. Is it possible to fix this minimal example which is not working?

URL: https://codesandbox.io/p/sandbox/infallible-frost-67fcrp

```
<ScatterChart
    width={500}
    height={300}
    dataset={[
      { xVar: 1, yVar: 32 },
      { xVar: 2, yVar: 41 },
    ]}
    xAxis={[{ dataKey: "xVar" }]}
    series={[{ dataKey: "yVar", label: "Test" }]}
  />
);
```

**Search keywords**: ScatterChart using dataset parameter

**Comment by michelengelen** [comment]
@JCQuintas one for you? :P

**Comment by lgnbhl** [comment]
Thanks for your quick answer. Looking forward to be able to use the dataset parameter with the Scatter and Pie Charts.
