### ISSUE TITLE
[data grid] Disable cell selection on click

### ISSUE THREAD

**Issue by duytuan001** [mui/mui-x#14886]
### Summary

<img width="85" alt="Screenshot 2024-10-09 at 10 59 54" src="https://github.com/user-attachments/assets/91f20b4b-1f0e-4c8a-a467-e972a3e8e4b4">

The buttons in a cell do not work when clicked the first time, but the second time they work.

Can we turn off cell selection for columns with buttons?

**Search keywords**: cell

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
