### ISSUE TITLE
[data grid]  v7.19.0 No minimum height for DataGrid doesn't show "No rows" anymore

### ISSUE THREAD

**Issue by sampain** [mui/mui-x#14881]
### Steps to reproduce

To reproduce:
Remove all the rows in this demo: https://mui.com/x/react-data-grid/layout/#flex-parent-container

### Current behavior

With the use of a flex parent container without any minimum height, the "No rows" overlay has no height, making it invisible.
It also happen with any other overlays, the loading overlay also doesn't have any height if the Datagrid is empty.
![image](https://github.com/user-attachments/assets/6ba0ba8c-c61c-4748-b910-24b15ef845c5)

### Expected behavior

Before, with autoHeight, the "No rows" and loading overlay used to have 104px height.
See the V6 demo: https://v6.mui.com/x/react-data-grid/layout/#auto-height
![image](https://github.com/user-attachments/assets/fde11987-8010-403d-92ba-4bba82ca5069)
![image](https://github.com/user-attachments/assets/7993aa43-494a-4c8e-a3f1-8c1a25fff3f1)

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: autoHeight flex minimum height

**Comment by michelengelen** [comment]
You need to set a `minHeight` on the parent container as shown in this example: [Minimum and maximum height](https://mui.com/x/react-data-grid/layout/#minimum-and-maximum-height).

When `autoHeight` is enabled the overlays will take up the height of 2 rows ([Overlay height](https://mui.com/x/react-data-grid/layout/#overlay-height)).

If you encounter other problems with it please feel free to open another issue!

I'll close this one.

**Comment by sampain** [comment]
> You need to set a `minHeight` on the parent container as shown in this example: [Minimum and maximum height](https://mui.com/x/react-data-grid/layout/#minimum-and-maximum-height).
> 
> When `autoHeight` is enabled the overlays will take up the height of 2 rows ([Overlay height](https://mui.com/x/react-data-grid/layout/#overlay-height)).
> 
> Warning
> 
> the `autoHeight` prop is deprecated, so it is generally better to use the flex parent container approach to be future safe.
> If you encounter other problems with it please feel free to open another issue!
> 
> I'll close this one.

Having to set a minimum height to be able to see overlays doesn’t seem like a great solution to me.

**Comment by michelengelen** [comment]
> > You need to set a `minHeight` on the parent container as shown in this example: [Minimum and maximum height](https://mui.com/x/react-data-grid/layout/#minimum-and-maximum-height).
> > When `autoHeight` is enabled the overlays will take up the height of 2 rows ([Overlay height](https://mui.com/x/react-data-grid/layout/#overlay-height)).
> > Warning
> > the `autoHeight` prop is deprecated, so it is generally better to use the flex parent container approach to be future safe.
> > If you encounter other problems with it please feel free to open another issue!
> > I'll close this one.
> 
> Having to set a minimum height to be able to see overlays doesn’t seem like a great solution to me.

@cherniavskii this got introduced in #14614 ... is there a reason why we do not allow for the overlays to have a minimal height anymore?
