### ISSUE TITLE
Cancel and stop dragging upon escape key

### ISSUE THREAD

**Issue by dejanm22** [mui/mui-x#14892]
**Search keywords**: cancel dragging with escape key

**Comment by michelengelen** [comment]
Thanks for reaching out! To better understand the problem you're facing, could you provide some additional information?

**Detailed Description:**
A more detailed explanation of the issue would be very helpful. What behavior are you expecting, and what's actually happening?

**Minimal Reproduction:**
If possible, creating a stripped-down test case that reproduces the issue would be fantastic. This helps us isolate the problem and diagnose it faster.

**Live Example**:
A live example (e.g., Stackblitz, codesandbox) showcasing the issue would be even better!

We have some resources to help you create a minimal reproduction:

**Support Documentation:**
[Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

---

Here are some additional tips:

**Clean Code:**
Focusing on clean and functional code with minimal dependencies will make it easier to identify the issue.

**Problem Clarification:**
Sometimes, the process of creating a minimal reproduction can even help you clarify the problem itself!

Thanks for your understanding!
