### ISSUE TITLE
[pickers] Cannot compile in TypeScript with `skipLibCheck: false`

### ISSUE THREAD

**Issue by jcrang** [mui/mui-x#14895]
### Steps to reproduce

Link to live example: (required)

https://stackblitz.com/edit/react-5frnjq?file=tsconfig.json,Demo.tsx,node_modules%2F%40mui%2Fx-date-pickers-pro%2FDateRangePicker%2Findex.d.ts,node_modules%2F%40mui%2Fx-date-pickers-pro%2FDateRangePicker%2FDateRangePickerToolbar.d.ts

Steps:
1. Open DateRangePickerToolbar.d.ts

Make sure to have `skipLibCheck` set to false in `tsconfig.json`.

### Current behavior

TypeScript compiler errors shown under `import("luxon")` and `import("moment")`

![image](https://github.com/user-attachments/assets/2ced8b51-037e-4db7-9be5-7902ccdb793c)

### Expected behavior

No TypeScript compiler errors

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 22.9.0 - ~\AppData\Local\fnm_multishells\2744_1728469629967\node.EXE
    npm: 10.8.3 - ~\AppData\Local\fnm_multishells\2744_1728469629967\npm.CMD
    pnpm: 9.4.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: Not Found
    Edge: Chromium (128.0.2739.54)
  npmPackages:
    @emotion/react: 11.13.3 => 11.13.3
    @emotion/styled: 11.13.0 => 11.13.0
    @mui/core-downloads-tracker:  6.1.2
    @mui/icons-material: 6.1.2 => 6.1.2
    @mui/material: 6.1.2 => 6.1.2
    @mui/private-theming:  6.1.2
    @mui/styled-engine:  6.1.2
    @mui/system:  6.1.2
    @mui/types:  7.2.17
    @mui/utils:  5.16.6
    @mui/x-data-grid:  7.19.0
    @mui/x-data-grid-pro: 7.19.0 => 7.19.0
    @mui/x-date-pickers:  7.19.0
    @mui/x-date-pickers-pro: 7.19.0 => 7.19.0
    @mui/x-internals:  7.18.0
    @mui/x-license:  7.18.0
    @types/react: 18.3.11 => 18.3.11
    react: 18.3.1 => 18.3.1
    react-dom: 18.3.1 => 18.3.1
    typescript: 5.6.2 => 5.6.2
```
</details>

**Search keywords**: skipLibCheck luxon moment pickers

**Comment by flaviendelangle** [comment]
Hey
Thanks for your report
I can confirm that we have mention of all the date libraries on our bundle and that it's a clear regression..

**Comment by flaviendelangle** [comment]
Weirdly enough #14896 fixes it...

**Comment by flaviendelangle** [comment]
The fix should be released tomorrow or on Friday :+1: 
Until then, staying on version 7.18.0 or below should fix your issue :+1:
