### ISSUE TITLE
[license] New Pro plan license key failure

### ISSUE THREAD

**Issue by pflcl** [mui/mui-x#14905]
### Steps to reproduce

Link to live example: (required)

Steps:
1. tested offline- failed
2. tested- dev/test- failed
3. tested- PROD- failed

### Current behavior

package doesn't register with new key

### Expected behavior

package registers

### Context

install new license key

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: MUI X
**Order ID**: 99607

**Comment by michelengelen** [comment]
Hey @pflcl could you share how you implemented the key?
I just tried it locally and the key you posted in the internal ticket works as expected.
Also please share the output from `npx @mui/envinfo` .. This is pretty critical information we need to pin down the problem for you!

**Comment by michelengelen** [comment]
Ok, we can also handle this in the ticket system. 
closing this now
