### ISSUE TITLE
Pro Plan license not registering: 2024-16999

### ISSUE THREAD

**Issue by pflcl** [mui/mui-x#14904]
### Steps to reproduce

Link to live example: (required)

Steps:
1. tested offline
2. tested dev/test
3. tested PROD

All failed. Still shows paid pro license package unregisted after successful merge.

### Current behavior

key doesn't register

### Expected behavior

key registers

### Context

install new pro paid license key

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: MUI X
**Order ID**: 2024-16999

**Comment by michelengelen** [comment]
Duplicate of #14905
