### ISSUE TITLE
[pickers] Cannot compile in TypeScript with skipLibCheck: false in MUI 7.20.0

### ISSUE THREAD

**Issue by jcrang** [mui/mui-x#14924]
**Note**: this is the same issue as #14895; I believe that fixed the issue in DateRangePicker.d.ts but not DateRangePickerToolbar.d.ts

### Steps to reproduce

Link to live example: (required)

https://stackblitz.com/edit/react-jf96wz?file=Demo.tsx,index.tsx,node_modules%2F%40mui%2Fx-date-pickers-pro%2FDateRangePicker%2FDateRangePickerToolbar.d.ts

Steps:

1. Open DateRangePickerToolbar.d.ts

Make sure to have skipLibCheck set to false in tsconfig.json.

### Current behavior

TypeScript compiler errors shown under `import("luxon")` and `import("moment")`

![image](https://github.com/user-attachments/assets/f7d77e0a-d4f0-4f95-8313-1b68f11f6fd3)

### Expected behavior

No TypeScript compiler errors

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: skipLibCheck luxon moment pickers

**Comment by jcrang** [comment]
There was some discussion in #14896 on how to catch this issue earlier.

A possible solution would be to create an empty project with MUI-X and compile it with `skipLibCheck: false`. Is this something that would be possible in your current build infrastructure?

**Comment by flaviendelangle** [comment]
Damn... I missed this one :roll_eyes: 

I fixed it in `DateTimeRangePickerToolbar`
We definitely need to invest some time adding a check to the CI somehow

Opening a PR :grimacing:

**Comment by LukasTy** [comment]
How come this is a problem? 🤔 
We have specifically fixed it only in the `DateTimeRangePickerToolbar`. 🙈 
I've tested multiple times by building locally. 🤷 

___

Could there have been a problem with the release?
Have we tried local build?

**Comment by flaviendelangle** [comment]
I tried the Codesandbox build
But for me it only causes problem if you import the component, so if you only had `import {...} from '@mui/x-date-pickers-pro/DateTimeRangePicker'` then the `DateRangePickerToolbar` toolbar is never used and causes no problem to TS :/

I used the search of the IDE to check if I had other instances of `import()` but I guess I did something wrong..
I searched for it again and I can't find another other instances...

**Comment by LukasTy** [comment]
Nevermind. It's late Friday and I'm sick. 😆 
It's the difference of `DateTimeRangePickerToolbar` and `DateRangePickerToolbar`. 🤦
