### ISSUE TITLE
[question] DateTimeRangePicker onChange behavior

### ISSUE THREAD

**Issue by arjaym-dev** [mui/mui-x#14955]
### The problem in depth

Good day, i just have a question for using the dateTimeRangePicker below i will attach the demo for comparing the date range picker & date time range picker

- https://stackblitz.com/edit/react-ben8hy?file=Demo.js here's the demo for date range picker
- https://stackblitz.com/edit/react-jbybvk?file=Demo.js here's the demo for date time range picker

Date range behavior step to reproduce
- after selecting fromDate & endDate e.g Oct 1, 2024 - Oct 2, 2024
- then follow up another change you will notice it always start the change from startDate to endDate which is right

Date time range behavior step to reproduce
- after selecting fromDate & endDate e.g Oct 1, 2024 - Oct 2, 2024
- then follow up another change you will notice that the changes you made only applies on the endDate.

Is there any other way for the date time range behavior to be like whats on the date range ? I cant seems to find what to use from the api

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DateTimeRangePicker, Date range, mui-x
**Order ID**: 70493

**Comment by LukasTy** [comment]
Hello @arjaym-dev,
could you please update your given examples to be as minimal as possible to showcase the issue?
The problems I see with the existing examples:
1. Pickers are not closing.
2. CustomField does not have proper `fieldType` property set [as mentioned here](https://mui.com/x/react-date-pickers/custom-field/#use-single-input-fields-on-range-pickers).
3. DateTimeRangePicker has no time renderers. 🤷

**Comment by arjaym-dev** [comment]
@LukasTy Hello, here's a video to showcase the comparison of date range picker and date time range picker

https://github.com/user-attachments/assets/03482e8c-8136-4a6c-836d-e087847ae398


https://github.com/user-attachments/assets/8ed4cbea-2724-4cb2-abb7-fdfee5b63ced
