### ISSUE TITLE
[data grid]  Server tree data checkboxSelection style init

### ISSUE THREAD

**Issue by wang97111** [mui/mui-x#14954]
### Steps to reproduce

https://codesandbox.io/p/sandbox/sweet-shirley-gt5xtc?file=%2Fsrc%2FDemo.js%3A70%2C25

Steps:
1.  Server-side tree data Grid (checkboxSelection true configuration) init
2. checkbox shows the selected style

Here's a picture with effect:

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/f31e4bb3-5886-449d-92a7-0a5d045d5e08">

### Current behavior

checkbox shows the selected style

### Expected behavior

Checkbox shows unchecked style

Initialization is like this：
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/809fc5a8-484c-4edf-9564-f37f47af585a">

### Context

I'm sorry for asking such a rude question. I'm not sure if this is a style issue or a design issue.
Or how can I modify this part?

After initialization, I confirmed that rowSelectionModel is empty and the checkbox is displayed as selected. Will it mislead the user that a row has been selected?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Server-side tree data, checkboxSelection

**Comment by MBilalShafi** [comment]
Thanks @wang97111 for reporting the issue, it indeed is an issue when there are no children for a particular group node.
Raised a fix: #14956
