### ISSUE TITLE
[data grid] deleted row is not removed from rowSelectionModel

### ISSUE THREAD

**Issue by tillkrischer** [mui/mui-x#14964]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/vigorous-oskar-rhgzlp

Steps:
1. select row with checkbox
2. delete that row
3. row remains in `rowSelectionModel` despite `keepNonExistentRowsSelected={false}`

### Current behavior

- onRowSelectionModelChange does not get called
- the deleted row id stays in rowSelectionModel

### Expected behavior

- onRowSelectionModelChange gets called and removes the deleted row id
- like 7.18.0

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 22.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.9.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/material: ^6.1.3 => 6.1.3
    @mui/x-data-grid: 7.20.0 => 7.20.0
    @types/react: ^18.3.10 => 18.3.11
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.5.3 => 5.6.3

```
</details>

**Search keywords**: grid,rowSelectionModel

**Comment by arminmeh** [comment]
Confirmed that this is a regression.

Thanks for reporting @tillkrischer 
Fix PR should be there soon

**Comment by arminmeh** [comment]
PR is there
I like your sandbox example data, by the way 😆
