### ISSUE TITLE
TimeField slotProps startAdornment is missing

### ISSUE THREAD

**Issue by campsafari** [mui/mui-x#15007]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/vitejs-vite-mjdgy7?file=src%2FApp.tsx,src%2Fmain.tsx,package.json&terminal=dev
Steps:
1. Open the playground
2. Try to set startAdornment via slotProps.input

### Current behavior

Hence "InputProps" are marked as deprecated the recommended way of using slotProps.input does not support the "startAdornment" prop. 

### Expected behavior

slotProps.input should support "startAdornment"

``
<TimeField slotProps={{ input: { startAdornment: <AddAlarmIcon /> } }} />
``

### Context

I am trying to set the startAdornment prop on a TimeField via slotProps.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
```
   System:
    OS: Linux 5.0 undefined
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.4 
    @mui/icons-material: ^6.1.4 => 6.1.4 
    @mui/material: ^6.1.4 => 6.1.4 
    @mui/private-theming:  6.1.4 
    @mui/styled-engine:  6.1.4 
    @mui/system:  6.1.4 
    @mui/types:  7.2.18 
    @mui/utils:  6.1.4 
    @mui/x-date-pickers: ^7.20.0 => 7.20.0 
    @mui/x-internals:  7.20.0 
    @types/react: ^18.3.11 => 18.3.11 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^5.5.3 => 5.6.3 
```
</details>

**Search keywords**: TimeField

**Comment by flaviendelangle** [comment]
Duplicates #14284 :+1:
