### ISSUE TITLE
DataGridPro placement panel filter no works

### ISSUE THREAD

**Issue by 93carlosmesa** [mui/mui-x#15005]
### Steps to reproduce

Link to live example: (required)

Steps:
1. DataGridPro
2. Add SlotProps
3. Add panel =>    placement: 'top-end'

EX: slotProps={{
          panel: {
            placement: 'top-end',
            open: true,
          },
        }}

### Current behavior

Display the panel on the left.

### Expected behavior

It should show the panel on the right

### Context

The panel opens on the left side in version 7.20, while in version 6.X it worked fine.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGridPro; panel; placement

**Comment by MBilalShafi** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version and the version where it works fine? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.

Thanks for your understanding! 🙇🏼

**Comment by 93carlosmesa** [comment]
@MBilalShafi  Thank you very much for corroborating this, is there a temporary solution? Or should I wait until it is fixed?
