### ISSUE TITLE
How to trigger preProcessEditCellProps on click of save

### ISSUE THREAD

**Issue by achoud444** [mui/mui-x#15010]
### Summary

I am trying to make edit and save in mui datagrid cell. Here is the [link ](https://codesandbox.io/p/sandbox/cold-grass-x9cxjy?file=%2Fdemo.tsx).

Several thing are not working here. Please help with this.
1. Country is not changing.
2. On change of country I also want to change the vat based on country.
3. If the country is not selected then clicking on save it should throw error on the cell which its background as red.

**Search keywords**: How to trigger preProcessEditCellProps on click of save

**Comment by achoud444** [comment]
@MBilalShafi @michelengelen Can you please help here

**Comment by MBilalShafi** [comment]
> Country is not changing

You could use `singleSelect` column type instead of adding a `renderEditCell` for this purpose, it's built for the same purpose. Here's a list of all available column types: https://mui.com/x/react-data-grid/column-definition/#column-types

If you also want to show the tooltip for the error, you might duplicate the [GridEditSingleSelect](https://github.com/mui/mui-x/blob/b3700aeea386b28f3ec93393571270cb3c94e90d/packages/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx) component, add your functionality, and pass it as `renderEditCell` for the country column.

> On change of country I also want to change the vat based on country.

Using [`processRowUpdate`](https://mui.com/x/react-data-grid/editing/#the-processrowupdate-callback) could help achieve that.

> If the country is not selected then clicking on save it should throw error on the cell which its background as red.

The `colDef.preProcessEditCellProps` should do this. See answer to first point for adding the tooltip.

I tried to update your example to support these usecases, here's the updated example: https://stackblitz.com/edit/react-ct2cgh?file=Demo.tsx

Is this what you are intending to do?

**Comment by achoud444** [comment]
> If the country is not selected then clicking on save it should throw error on the cell which its background as red.

This is still not working.. Suppose I add a new row if you can see [here](https://stackblitz.com/edit/react-ct2cgh-qkchwy?file=Demo.tsx). On click of save I want to highlight the cells with red border (name and country). Can I do that?

**Comment by achoud444** [comment]
@MBilalShafi  Thanks for the reply

> If the country is not selected then clicking on save it should throw error on the cell which its background as red.

This is still not working.. Suppose I add a new row if you can see [here](https://stackblitz.com/edit/react-ct2cgh-qkchwy?file=Demo.tsx). On click of save I want to highlight the cells with red border (name and country). Can I do that?

**Comment by MBilalShafi** [comment]
The `baseInput` used in the default edit component doesn't seem to add a red outline for the column type `string` with failing validation, adding the following snippet seems to fix it:

```tsx
sx={{
  '& input[aria-invalid="true"]': {
    border: '1px solid #d32f2f',
    borderRadius: 1,
  },
}}
```

I added that and some more adjustments in this example: https://stackblitz.com/edit/react-ct2cgh-7rfu71?file=Demo.tsx
Is that closer to your required use-case?

**Comment by achoud444** [comment]
Thank you it works. @MBilalShafi 

One more thing if you answer please..

Here I am saving the details on the backend using `createDetails()` and then again fetching it using `fetchDetails()` and it is updating. However I do not want it to be returned from processRowUpdate because if I return it adds two rows with same details and if I return null it throws an error. So how can I deal with it?

```
const processRowUpdate = async (newRow: GridRowModel, oldRow: GridRowModel) => {
    try {
        if (JSON.stringify(oldRow) === JSON.stringify(newRow)) return oldRow;

        let updatedRow;
        if (newRow.isNew) {
            updatedRow = {
                name: newRow.name,
                country: newRow.country,
                vatCodeId: newRow.vatCodeId,
                isDelete: false,
            };
        } else {
            updatedRow = {
                id: newRow.id,
                name: newRow.name,
                country: newRow.country,
                vatCodeId: newRow.vatCodeId,
                isDelete: false,
            };
        }

        await dispatch(createDetails(updatedRow));
        await dispatch(fetchDetails());

        setSnackbar({
            children: newRow.isNew ? 'Added!' : 'Updated!',
            severity: 'success',
        });

        return;
    } catch (err) {
        setSnackbar({
            children: 'Failed to save VAT code. Please try again.',
            severity: 'error',
        });
        return oldRow;
    }
};

```

**Comment by MBilalShafi** [comment]
Glad it worked. I'll mark the issue as resolved in that case.
Feel free to reopen if you want to clarify another aspect around this.

**Comment by achoud444** [comment]
@MBilalShafi I am having one more issue here. If you can see [here](https://stackblitz.com/edit/react-ct2cgh-zz1ngp?file=Demo.tsx).
I am having two fields age and description. In the age array I have description as well so when I change the age on the onchange I am also changing the description. It works well for the parent but not for the detail panel content do you know why?
