### ISSUE TITLE
[TreeView] TreeItem2DragAndDropOverlay has no border/background style

### ISSUE THREAD

**Issue by kzimins-arvatosystems** [mui/mui-x#15017]
### Steps to reproduce

Related to #14969

css definition of border style is wrong
![image](https://github.com/user-attachments/assets/180f9630-a133-4c61-95a6-197c56c1af6a)
correct rgba syntax is `rgba(red, green, blue, alpha)`
![image](https://github.com/user-attachments/assets/b1b5eca7-8b97-4121-ba17-79d60a4e05af)

Same for action `make-child`
![image](https://github.com/user-attachments/assets/12147011-b7a2-4966-b229-917b794d9dfa)

### Current behavior

css is wrong

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: treeview, cssvars
**Order ID**: 80084

**Comment by LukasTy** [comment]
Thank you for opening this issue @kzimins-arvatosystems 🙏 
It is our oversight. 🙈 
For any `rgba` calls only `<color>Channel` can be used.

**Comment by wangkailang** [comment]
It seems to be an issue with the use of RGB variables. The format for RGB in CSS variables should be three comma-separated numbers, representing the red, green, and blue channels (values ranging from 0 to 255), such as `0, 72, 118`.

**Comment by kzimins-arvatosystems** [comment]
@LukasTy Hi!

After today's release, I'm still experiencing issues with styles (`rgba(hex / opacity)` and `rgba(rgb / opacity)` doesn't seem to be valid syntax):

![image](https://github.com/user-attachments/assets/5bf71c83-7c9e-472a-b5ac-063505db931c)
![image](https://github.com/user-attachments/assets/2216427b-c9c3-4e85-acde-62db04eed40f)

Also, `TreeItem2DragAndDropOverlay` is not exported from the pro package. I'm importing everything else from the pro package, so could this be the cause of the issue?

![image](https://github.com/user-attachments/assets/c8e79d39-9110-43c9-9e31-255df9ba530c)

**Comment by LukasTy** [comment]
Hello @kzimins-arvatosystems 
I'm sorry to hear you are still experiencing issues with this. 🙈 
That's my bad, I applied the fix on the master branch but forgot to cherry-pick it to the current stable release.
Is it blocking you, or can you wait for the next release this Thursday? 🤔 

> Also, `TreeItem2DragAndDropOverlay` is not exported from the pro package. I'm importing everything else from the pro package, so could this be the cause of the issue?

It is re-exported from `@mui/x-tree-view-pro` root. We do not re-create the folder structure on the commercial packages to re-export files from community package with the same path.
The import path shouldn't change anything, but feel free to import it from the pro package with the following line:
```ts
import { TreeItem2DragAndDropOverlay } from '@mui/x-tree-view-pro';
```

**Comment by kzimins-arvatosystems** [comment]
> Is it blocking you, or can you wait for the next release this Thursday? 🤔

No problem, I can wait, thanks for the reply!

> ```ts
> import { TreeItem2DragAndDropOverlay } from '@mui/x-tree-view-pro';
> ```

I tried, but got

![image](https://github.com/user-attachments/assets/30e3ac75-721e-4dc1-82a0-64b43d11f410)
Using latest version
![image](https://github.com/user-attachments/assets/c52c8bcc-00f0-4814-85bb-00f8498bbb87)

**Comment by LukasTy** [comment]
> I tried, but got

Once again, I'm sorry for causing confusion in this transition state, where we are preparing the `master` branch for v8.
The renamed `TreeItemDragAndDropOverlay` is exported from `@mui/x-tree-view-pro`:
https://github.com/mui/mui-x/blob/4c6b35fa8d8d53231c1524fa6fae8194bb9a9e76/packages/x-tree-view-pro/src/index.ts#L11

@flaviendelangle have we forgotten to export `TreeItem2DrangAndDropOverlay` from the pro package?
Should we fix it for v7? 🤔

**Comment by flaviendelangle** [comment]
Sure
We need to fix 1-2 things regarding doc gen but it's totally doable

**Comment by LukasTy** [comment]
> We need to fix 1-2 things regarding doc gen but it's totally doable

Will you take up this effort?
Or should I do it?
