### ISSUE TITLE
[DataGrid] Using row grouping, custom aggregation function and row selection model together is causing an infinite loop of re render.

### ISSUE THREAD

**Issue by himankad** [mui/mui-x#15052]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/devbox/g3zcnc

I have configure the code in a way to quickly replicate the issue

Steps:
1. Select any checkbox from the Datagrid
2. Check console logs to see an infinite loop of re-renders.

### Current behavior

After compiling row grouping, custom aggregation and onRowSelectionModel change together, if i proceed to select any checkbox, it causes infinite re renders.

Then i commented out the code where in onRowSelectionModelChange function i am updating the state. On doing so, everything worked fine but i need the onRowSelectionModelChange to play around with the selected data.

After this, i uncommented the onRowSelectionModelChange function and commented the aggregation model declaration in initial state, aggregation function attribute of the datagrid and everything worked fine again but i need the aggregation functionality as well

### Expected behavior

I expect to select any group or row from the datagrid and update my state accordingly based on new selection along with the ability of custom aggregation. 

### Context

I am trying to accomplish aggregated data from different groups and then i want to select the data (either a single row or an entire group) from grid and send the selected data to my API server.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Browser: 
     Chrome
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: latest => 11.13.3 
    @emotion/styled: latest => 11.13.0 
    @mui/icons-material: latest => 6.1.4 
    @mui/material: latest => 6.1.4 
    @mui/x-data-grid-generator: latest => 7.21.0 
    @mui/x-data-grid-premium: latest => 7.21.0 
    @types/react: latest => 18.3.11 
    react: latest => 18.3.1 
    react-dom: latest => 18.3.1 
    typescript: latest => 5.6.3 
```
</details>

**Search keywords**: datagrid, aggregation, row grouping
**Order ID**: 86259

**Comment by KenanYusuf** [comment]
Hi @himankad - thanks for providing the reproduction. 

It looks like the issue can be solved by keeping the `aggregationFunctions` value stable between renders with `React.useMemo`, or moving the object outside of the `AggregationCustomFunction` component. Here's an updated [demo](https://codesandbox.io/p/devbox/datagrid-15052-2gz566).

**Comment by himankad** [comment]
Hi @KenanYusuf , thanks for the reply. Can you please reshare the link to the demo

**Comment by KenanYusuf** [comment]
Sorry @himankad - try again.

**Comment by himankad** [comment]
Hi @KenanYusuf , in my application, i am having the following error now 

Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

![image](https://github.com/user-attachments/assets/226b0808-4804-4394-bbe5-ec178235ce03)

**Comment by KenanYusuf** [comment]
@himankad can you update the demo to reproduce that error? Hard for me to know what's causing it otherwise.

**Comment by himankad** [comment]
hi @KenanYusuf , i have the codesandbox link that you have shared to replicate the issue, the screen is still in infinite re render state and after some time you will see the "Maximum update depth" issue in the console log itself.

**Comment by KenanYusuf** [comment]
@himankad it is the same issue with `getAggregationPosition`, you need to make sure the function is stable between renders. You can use `React.useCallback` or move the function outside of the component. I have updated [the demo](https://codesandbox.io/p/devbox/datagrid-15052-2gz566).

**Comment by himankad** [comment]
Thank you so much @KenanYusuf , you are a savior. This really helped. Closing the issue now.
