### ISSUE TITLE
[data grid] Having issues exporting paginated selection model that includes nonexistent rows (CSV or Excel)

### ISSUE THREAD

**Issue by Spencer-Vega** [mui/mui-x#15050]
### The problem in depth

**I do not have a live example to this question.**

### Intro 
I am just wondering if what I am observing is the intended behavior for exporting a selection of rows when some of the selected data might not currently "exist". Or if there are additional actions that need to be done in order to make sure all selected rows, regardless of if they are in a different page, are present in the export download.

### Steps for reproduction
1. Table exists that is receiving paginated data from a server
   - Selection is enabled on the table (specifically using checkbox selection)
   - With `keepNonExistentRowsSelected` enabled
   - Enough data is contained that there are several pages
3. Within first page select 2 rows of data
   - These rows exist and are in the selection model
4. Paginate to second page
   - The rows on first page no longer exist but are still present in the selection model
5. Select 2 more rows of data on the second page
   - The rows on the second page exist and appear in the selection model in addition to the previous rows
6. While on page 2, select `Export` and then select either `CSV` or `Excel`

### (my) Expected Behavior
- File downloads with all data present from selection model (4 rows) 
- Selection Model still contains 4 rows

### Current Behavior
- File downloads with only data selected from second page (2 rows)
- Selection Model still contains 4 rows

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Current Browser: Chrome
--------------
System:
    OS: macOS 15.0.1
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.8.3 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 129.0.6668.103
    Edge: 130.0.2849.46
    Safari: 18.0.1
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.14 
    @mui/icons-material: ^5.15.14 => 5.15.14 
    @mui/lab: ^5.0.0-alpha.169 => 5.0.0-alpha.169 
    @mui/material: ^5.15.14 => 5.15.14 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.14 
    @mui/types:  7.2.18 
    @mui/utils:  5.15.14 
    @mui/x-data-grid: ^7.21.0 => 7.21.0 
    @mui/x-data-grid-premium: ^7.21.0 => 7.21.0 
    @mui/x-data-grid-pro:  7.21.0 
    @mui/x-date-pickers: ^7.21.0 => 7.21.0 
    @mui/x-internals:  7.21.0 
    @mui/x-license: ^7.1.1 => 7.21.0 
    @mui/x-tree-view: ^7.21.0 => 7.21.0 
    @types/react: 18.2.67 => 18.2.67 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components:  5.3.11 
    typescript: ~5.4.3 => 5.4.3 

```
</details>

**Search keywords**: export, export paginated selection
**Order ID**: 87625

**Comment by KenanYusuf** [comment]
Hi @Spencer-Vega. Currently, exporting server loaded rows is limited to the rows that are visible in the grid. If you would like to see this functionality prioritised sooner, please upvote (👍)  [this issue](https://github.com/mui/mui-x/issues/6036) and leave a comment with your use case.

**Comment by Spencer-Vega** [comment]
Okay, thank you!
closing.
