### ISSUE TITLE
[data grid] `onRowSelectionModelChange` is called when `treeData` is enabled and `rows` changes

### ISSUE THREAD

**Issue by goldst** [mui/mui-x#15068]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/hopeful-maxwell-dxvvlw?from-embed=&workspaceId=67e261df-ad7c-4156-98c4-4a0336fb54f4

Steps:
1. Open the console and click the button above the grid that says "add a row"

### Current behavior

Despite the row selection not changing, `onRowSelectionModelChange` is being called. See the console output.

### Expected behavior

`onRowSelectionModelChange` should not be called when changing rows, unless the row selection changes too. In the example, there should be no console output.

If it is technically impossible not to call `onRowSelectionModelChange` in this case, it should at least return the same array (not a new one with the same values) so I can easily check whether the row selection model changed.

### Context

This worked correctly in v7.18.0. It breaks in v7.19.0 and hasn't been fixed since.

We reset parts of our UI when the row selection changes. For this, we use `onRowSelectionModelChange`. We cannot compare the row selection array content with the previous content because of performance. There are too many selected rows.

This only happens when `treeData` is enabled.

### Your environment

<details>
  <summary><code>bunx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.6.0 - /mnt/c/Users/lgoldstein/AppData/Roaming/npm/pnpm
  Browsers:
    Chrome: 121.0.6167.85
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.42 
    @mui/core-downloads-tracker:  6.1.2 
    @mui/icons-material: ^6.1.2 => 6.1.2 
    @mui/lab: ^6.0.0-beta.10 => 6.0.0-dev.240424162023-9968b4889d 
    @mui/material: ^6.1.2 => 6.1.2 
    @mui/private-theming:  6.1.0 
    @mui/styled-engine:  6.1.0 
    @mui/system:  6.1.0 
    @mui/types:  7.2.15 
    @mui/utils:  6.1.0 
    @mui/x-data-grid:  7.21.0 
    @mui/x-data-grid-premium: ^7.21.0 => 7.21.0 
    @mui/x-data-grid-pro:  7.21.0 
    @mui/x-date-pickers:  7.21.0 
    @mui/x-date-pickers-pro: ^7.21.0 => 7.21.0 
    @mui/x-internals:  7.21.0 
    @mui/x-license: ^7.18.0 => 7.18.0 
    @types/react: ~18.3.11 => 18.3.11 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^5.6.3 => 5.6.3 
```
</details>

Reproducible in Chrome and Firefox.

**Search keywords**: onRowSelectionModelChange, treeData, rows, reference changes
**Order ID**: 95800

**Comment by MBilalShafi** [comment]
I'll take a look on this, it seems to be related to https://github.com/mui/mui-x/pull/13757 that got shipped in [v7.19.0](https://github.com/mui/mui-x/releases/tag/v7.19.0), technically it should also be there in v7.19.0 though.

**Comment by goldst** [comment]
Thank you @MBilalShafi for the quick response. Small correction to my description: in the description, I said that it broke in v7.18.0, but it broke in v7.19.0. I adjusted it.

**Comment by MBilalShafi** [comment]
Thanks @goldst for the clarification 👍 
That confirms my doubt that it's related to #13757.
