### ISSUE TITLE
[data grid] `onRowSelectionModelChange` firing twice

### ISSUE THREAD

**Issue by jkunwar** [mui/mui-x#15079]
### Search keywords

onRowSelectionModelChange

### Latest version

- [X] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/headless-microservice-x38xc6

Steps:
1. Use  getRowId={(row) => row.id}, instead of defining id field in the column definition
2. set filterMode="server"

### Current behavior

The `onRowSelectionModelChange` handler is triggered twice when trying to update any state within the handler, if `getRowId` is used to set the unique row ID and `filterMode` is set to 'server'. However, when `filterMode` is set to 'client', the handler is only triggered once.

### Expected behavior

`onRowSelectionModelChange` should be triggered only once.

### Context

The response data doesn't include an id field but uses a different key as the record identifier. I am using getRowId to assign the id field.

### Your environment

System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 130.0.6723.58
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.5 
    @mui/material: ^6.1.5 => 6.1.5 
    @mui/private-theming:  6.1.5 
    @mui/styled-engine:  6.1.5 
    @mui/system:  6.1.5 
    @mui/types:  7.2.18 
    @mui/utils:  6.1.5 
    @mui/x-data-grid: ^7.21.0 => 7.21.0 
    @mui/x-internals:  7.21.0 
    @types/react: ^18.3.10 => 18.3.10 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^4.9.5 => 4.9.5

**Comment by KenanYusuf** [comment]
Wondering if this is a regression from one of the following PRs:
- https://github.com/mui/mui-x/pull/14909
- https://github.com/mui/mui-x/pull/14972

@arminmeh @MBilalShafi anything spring to mind?

**Comment by MBilalShafi** [comment]
@KenanYusuf Kindly assign this one to me, I have another related issue that also concerns onRowSelectionModelChange. Will try to sort them out together.
