### ISSUE TITLE
[data grid] Sort by time order incorrect

### ISSUE THREAD

**Issue by xingyaoc-1999** [mui/mui-x#15078]
### Steps to reproduce

Link to live example: (required)
![IMG_20241024_112705](https://github.com/user-attachments/assets/52813481-a9db-4dd7-98f8-861807b57f6d)

Steps:
1.create two data with time as  2024-10-23T07:28:44.436Z and  2024-10-09T06:04:46.000Z
2.order the data by time 
3. find the order is wrong 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: order time

**Comment by KenanYusuf** [comment]
Hi @xingyaoc-1999 please can you provide a reproduction? You can fork a CodeSandbox/StackBlitz demo from the demos on the docs https://mui.com/x/react-data-grid/sorting/

**Comment by xingyaoc-1999** [comment]
I found the problem. It is not possible to convert a date to a string in the `valueGetter`, it needs to be done in the `valueFormatter`.
