### ISSUE TITLE
[data grid] `baseCheckBox` slot don't render indeterminate icon

### ISSUE THREAD

**Issue by tandao0909** [mui/mui-x#15080]
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-csxppk?file=Demo.tsx
Steps:
1. Define a custom CheckBox element base on the CheckBox 
2. Define it in the baseCheckBox slot of the DataGrid component

### Current behavior

Select a row in the rendered DataGrid, the header checkbox is not the ineterminate icon

### Expected behavior

I should see the indeterminate icon defined in the custom CheckBox

### Context

I want to change the checkbox of the DataGrid, preferably a rounder one

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
  System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    npm: 10.9.0 - /usr/local/bin/npm
    pnpm: 9.10.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.69

```
</details>
I use Firefox 

**Search keywords**: DataGrid baseCheckBox slots

**Comment by KenanYusuf** [comment]
Hi @tandao0909 looks like you just need to spread the checkbox props to the Material UI checkbox.

```diff
const CheckBoxRounded = (props: CheckboxProps) => {
  return (
    <Checkbox
      icon={<FavoriteBorderRoundedIcon />}
      checkedIcon={<CheckBoxRoundedIcon />}
      indeterminateIcon={<IndeterminateCheckBoxRoundedIcon />}
+     {...props}
    />
  );
};
```

Here's an updated demo https://stackblitz.com/edit/react-csxppk-bkycxd?file=Demo.tsx

Hope that's solved your issue, I'll close it for now and if you have any further questions feel free to re-open.
