### ISSUE TITLE
[data grid] Right border calculation on column group headers does not work for last column group header on `showColumnVerticalBorder`

### ISSUE THREAD

**Issue by hendrikpeilke** [mui/mui-x#15086]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-h9qpvr

Steps:
1. Make the demo window a smaller width than the whole table
2. Refresh the demo

### Current behavior

You can see an additional, not expected right border on the column group header to the right:

![image](https://github.com/user-attachments/assets/1d5070c3-690a-40e2-8097-aa79d2a19cf9)

### Expected behavior

The right column group header does not show an additional border, i.e. does not have the css class `...--withRightBorder`

### Context

trying to make a neat looking table with borders and column groups

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: Chrome 129.0.6668.101 (64 bit)
```
</details>

**Search keywords**: datagrid group header border showColumnVerticalBorder

**Comment by hendrikpeilke** [comment]
@KenanYusuf Thank you for the fix. It works great on my simplified example. But having more columns and groups, it does not work out anymore. 

I created a forked example with your fixed version here, using some filler columns and groups in between added to the original example: https://stackblitz.com/edit/react-h9qpvr-u62rjb 

Should I open a new issue for that or am I maybe missing something there?

**Comment by michelengelen** [comment]
Hey @hendrikpeilke it would be great if you could open a new issue. This is probably happening due to virtualization of the columns. I do noticed that the border also somehow disappears, so it would be great to look into this specifically

**Comment by hendrikpeilke** [comment]
After looking at the code more thoroughly, I guess the solution would be to use `visibleColumnGroupHeader.length` as `sectionLength` in https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L467

It would be similar to https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L310 where it refers to the length of the array, which is iterated over. It works there for the normal headers.

Also what is compared in the end in https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/utils/cellBorderUtils.ts#L3 is the index inside the section with the length of the section. Where the index is coming from the index inside the `visbileColumnGroupHeader` array, see https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L466, https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L445 and https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L415

It also makes clear why the simple case in https://github.com/mui/mui-x/issues/15086 works. Because `rowStructure.length` equals `visibleColumnGroupHeader.length` in that case, since all columns are visible.
