### ISSUE TITLE
[data grid] In grouped rows: How to determine value based on other columns' values

### ISSUE THREAD

**Issue by stivluc** [mui/mui-x#15083]
### The problem in depth

For some columns of my datagrid, the value depends on other columns' values, using
`valueGetter: (params) => params.row.quantity / params.row.total`

I need to calculate those values also on grouped row.

Current behavior: params.row.XXX returns undefined on grouped row

For the grouped rows, we can currently only display aggregations like sum, avg, etc. But an avg of progresses for example is totaly wrong because it depends on the sum of quantities.

![image](https://github.com/user-attachments/assets/58a36bef-2d6d-4a68-bbf4-7282a741f2ef)

Example here: 
Progress for 10/25/2024 should be (15,936 - 3384 - 567) / 15936 = 75% but it currently displays an average of the sums.

It should display the value according to the three columns right of it.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 22.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD  
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (127.0.2651.98)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.13.3
    @emotion/styled: ^11.10.6 => 11.13.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.7
    @mui/icons-material: ^5.11.16 => 5.16.7
    @mui/lab: ^5.0.0-alpha.126 => 5.0.0-alpha.173
    @mui/material: ^5.12.0 => 5.16.7
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-data-grid:  6.20.4
    @mui/x-data-grid-premium: ^6.19.6 => 6.20.4
    @mui/x-data-grid-pro:  6.20.4
    @mui/x-date-pickers: ^6.18.2 => 6.20.2
    @mui/x-date-pickers-pro: ^6.19.5 => 6.20.2
    @mui/x-license-pro:  6.10.2
    @types/react:  18.3.4
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript:  5.6.3
```
</details>

**Search keywords**: Grouped row aggregations
**Order ID**: 80196

**Comment by KenanYusuf** [comment]
Hey @stivluc please could you provide a minimal reproduction of your example? I have an idea for how to solve it with `renderCell`  but it would be useful to have an example with some sample data to work with.

**Comment by KenanYusuf** [comment]
@stivluc does this do what you're looking to achieve? https://codesandbox.io/p/sandbox/15083-row-group-derived-aggregation-cd8cx3

**Comment by stivluc** [comment]
It does!! Thanks a lot for your help I'll have to study this as it will be very useful all accross my app.

**Comment by KenanYusuf** [comment]
Glad to hear it @stivluc - let me know if you have any follow up questions.
