### ISSUE TITLE
[data grid] Edit cell not working on the detail panel content

### ISSUE THREAD

**Issue by achoud444** [mui/mui-x#15094]
### Summary

I am having one scenerio where I need to change another cell on change of a cell.

If you can see [here](https://stackblitz.com/edit/react-ct2cgh-zz1ngp?file=Demo.tsx).

I am having two fields age and description. In the age array I have description as well. So when I change the age on the onchange I am also changing the description. However It works well for the parent datagrid but not for the detail panel content.

**Search keywords**: Edit cell not working on the detail panel content

**Comment by michelengelen** [comment]
Hey @achoud444 ... please trim down your demo code to a __minimal__ reproduction. There is a lot of code that is irrelevant to show the issue you are facing, so please adjust accordingly!

**Comment by achoud444** [comment]
@michelengelen I have removed most of the redundant code from [here](https://stackblitz.com/edit/react-ct2cgh-zz1ngp?file=Demo.tsx).

My question is, If you can see I have two select for age on for parent and one for the detail panel so when i change the age in the parent it changes the description but when i change in the child table it does not.
