### ISSUE TITLE
[data grid] A form field element should have an id or name attribute

### ISSUE THREAD

**Issue by Vagizova** [mui/mui-x#15112]
### Steps to reproduce

Link to live example: [example](https://codesandbox.io/embed/knyp42?module=/src/Demo.tsx&fontsize=12)

Steps:
1. open console
2. you can see, there is a bunch of issues about checkboxes in selection columns

### Current behavior

Inputs do not have name or id attr, so i have hundreds issues in my console. It is annoying

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: row selection checkboxes

**Comment by michelengelen** [comment]
Hey @Vagizova ... I cannot reproduce the issue you are facing. The only two errors I can see are those about the resizeObserver and the strictMode (a CSB bug apparently)

Locally it does not even show a single one of those

Could you elaborate on the issue you are facing a bit or share screen recordings and screenshots?

**Comment by Vagizova** [comment]
@michelengelen Hey, sure! Here it is: https://codesandbox.io/embed/kyppc4?module=/src/Demo.tsx&fontsize=12 

https://github.com/user-attachments/assets/6c1ef0e9-358d-4009-a611-8027477c5b52

**Comment by michelengelen** [comment]
Thanks @Vagizova ... adding a name or id should be very straightforward ... let me check real quick.

**Comment by michelengelen** [comment]
OK< so a fix for that should be fairly easy:

```diff
diff --git a/packages/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx b/packages/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx
index 5bfadd9b9..6ff8fcf96 100644
--- a/packages/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx
+++ b/packages/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx
@@ -107,6 +107,8 @@ const GridCellCheckboxForwardRef = React.forwardRef<HTMLInputElement, GridRender
         ? isChecked && !isIndeterminate
         : isChecked;

+    const checkBoxId = `checkbox_${id}`;
+
     return (
       <rootProps.slots.baseCheckbox
         ref={handleRef}
@@ -119,6 +121,7 @@ const GridCellCheckboxForwardRef = React.forwardRef<HTMLInputElement, GridRender
         indeterminate={isIndeterminate}
         disabled={!isSelectable}
         touchRippleRef={rippleRef as any /* FIXME: typing error */}
+        id={checkBoxId}
         {...rootProps.slotProps?.baseCheckbox}
         {...other}
       />
diff --git a/packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx b/packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx
index f968f9108..e01280f54 100644
--- a/packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx
+++ b/packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx
@@ -145,6 +145,7 @@ const GridHeaderCheckbox = React.forwardRef<HTMLButtonElement, GridColumnHeaderP
         tabIndex={tabIndex}
         onKeyDown={handleKeyDown}
         disabled={!isMultipleRowSelectionEnabled(rootProps)}
+        id={'checkbox_header'}
         {...rootProps.slotProps?.baseCheckbox}
         {...other}
       />
```

I'll open this up as a good first issue.
