### ISSUE TITLE
[DataGrid] Scroll starts jumping back up when holding down arrow keys

### ISSUE THREAD

**Issue by lauri865** [mui/mui-x#15158]
### Steps to reproduce

Link to live example: (required)

Steps:
1. https://mui.com/x/
2. Hold down arrow key and wait a bit

https://github.com/user-attachments/assets/0caaae99-3706-44a3-878d-0835ed8e5fe9

### Current behavior

Scroll index jumps back up

### Expected behavior

Scroll continues smoothly and focused column should stay as the last one

### Context

Seems like a recent regression. As a side-nitpick - the last row position is imprecise even when it doesn't jump – sometimes up by a pixel, sometimes down.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: arrow keys navigation jump

**Comment by lauri865** [comment]
First introduced in v7.20.0

Probably #14888 @arminmeh?

**Comment by arminmeh** [comment]
@lauri865 thanks for reporting.
I have confirmed that this is a regression and will work on the fix
