### ISSUE TITLE
[data grid] DataGrid "no rows" overlay missing when autoHeight=true

### ISSUE THREAD

**Issue by ddolcimascolo** [mui/mui-x#15169]
### Steps to reproduce

Your own doc reproduces: https://mui.com/x/react-data-grid/layout/#overlay-height

### Current behavior

The overlay is not there

### Expected behavior

The overlay is there

### Context

Trying to make my own customers happy by not breaking their data grids because of a semver-minor update of a dependency :/

**Search keywords**: no rows overlay missing
**Order ID**: 31461 or 78178

**Comment by michelengelen** [comment]
Duplicate of #14881

**Comment by michelengelen** [comment]
Additional note: the [Auto height](https://mui.com/x/react-data-grid/layout/#auto-height) got deprecated with introduction of the [flex parent container](https://mui.com/x/react-data-grid/layout/#flex-parent-container) approach.

**Comment by ddolcimascolo** [comment]
Please reopen. I've changed nothing in my code and this is a regression. Moreover your doc exhibits the issue !

**Comment by ddolcimascolo** [comment]
@oliviertassinari @alexfauquette @romgrk @michelengelen Can you ahve a look and explain why this is closed?

**Comment by michelengelen** [comment]
@ddolcimascolo yes ... this regression got introduced recently. Sry for closing this too early. I'll have a look at it!

**Comment by michelengelen** [comment]
scratch that ... :/ ... found the culprit!

**Comment by ddolcimascolo** [comment]
Thanks a lot for confirming the issue and for your work on this.

Cheers,
David

**Comment by cherniavskii** [comment]
Thanks @GBvanDam 
I've opened https://github.com/mui/mui-x/pull/15202 to address the minimum overlay height.
