### ISSUE TITLE
[docs] Demo FullFeaturedCrudGrid crashes

### ISSUE THREAD

**Issue by bianchiale040502** [mui/mui-x#15174]
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20FullFeaturedCrudGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-data-grid/editing/#full-featured-crud
2. Deleted all records except one
3. Deleted last record
4. demo *FullFeaturedCrudGrid* crashes 
5. TypeError: Cannot read properties of undefined (reading 'id')

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v7.22.0  |
| Netlify deploy | https://671bb9b82a462c0008c22080--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by arminmeh** [comment]
Hi @bianchiale040502 
This issue was already [reported](https://github.com/mui/mui-x/issues/15145) and fixed in https://github.com/mui/mui-x/pull/15153
The fix will be released this week
