### ISSUE TITLE
[DataGrid] apiRef.current?.autosizeColumns is not a function

### ISSUE THREAD

**Issue by patekphilippe** [mui/mui-x#15173]
<img width="606" alt="Screenshot 2024-10-29 at 18 31 09" src="https://github.com/user-attachments/assets/411d5db4-3b38-4ca3-9db7-777813199fed">
<img width="625" alt="Screenshot 2024-10-29 at 18 57 21" src="https://github.com/user-attachments/assets/e5ee293d-b8db-4b89-aacb-3d2caa05b5ff">

According to the <a href="https://mui.com/blog/mui-x-v7/?_x_tr_hist=true">article</a> it was supposed to work for the community version. 

**Search keywords**:  DataGrid, autosizeColumns

Reported Data grid version: 7.22.0

**Comment by arminmeh** [comment]
Hi @patekphilippe 
Can you share a sandbox with the issue?
Our [example for autosizing](https://mui.com/x/react-data-grid/column-dimensions/#autosizing) uses community version of the grid and there are no errors that you have reported
