### ISSUE TITLE
[docs] Demo FullFeaturedCrudGrid crashes

### ISSUE THREAD

**Issue by shyamsunder91** [mui/mui-x#15193]
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20FullFeaturedCrudGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-data-grid/editing/#persistence
2. ??
3. demo *FullFeaturedCrudGrid* crashes
4. while deleting all rows in FullFeaturedCrudGrid
TypeError: Cannot read properties of undefined (reading 'id')

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v7.22.0  |
| Netlify deploy | https://671bb9b82a462c0008c22080--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by alexfauquette** [comment]
Thanks for reporting. This issue has already been fixed in #15153

The fix will be available tomorow
