### ISSUE TITLE
[data grid] Buttons not working with the Enter key when using Tree data.

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#15214]
### Current behavior

Selecting with `Space` key works, but not with `Enter`.

### Expected behavior

It should also work with Enter (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treegrid_role#enter)

### Context

Referenced by:
https://docs.google.com/spreadsheets/d/1jJBwkKY1a8a30usE_mvK0dRt86OIhSn89GQ8HZ48ZuI/edit?gid=300952947#gid=300952947

**Search keywords**: accessibility

**Comment by k-rajat19** [comment]
Hi @joserodolfofreitas and @KenanYusuf ,
I have opened PR to fix this accessibility issue, now the behavior is that the user can open/close rows with space and enter keys.
I initially thought that this should also be done in case of row grouping but I didn't find any guidelines for it https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowgroup_role
Please Feel free to share your thoughts on the PR.

**Comment by KenanYusuf** [comment]
@joserodolfofreitas Interestingly, there's nothing referenced in [developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treegrid_role#enter](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treegrid_role#enter) about the space key opening the child rows. Just enter.

> I initially thought that this should also be done in case of row grouping but I didn't find any guidelines for it [developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowgroup_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/rowgroup_role)

I suspect Enter should also open child rows on row groups, but I couldn't find anything supporting that either. Would be a usability improvement IMO. What do you think @joserodolfofreitas?

**Comment by MBilalShafi** [comment]
> I suspect Enter should also open child rows on row groups, but I couldn't find anything supporting that either.

From a usability perspective the users would expect a similar behavior for all the nested data, I'd be in favor of adding the same to row grouping too.
