### ISSUE TITLE
[data grid] Filtering Boolean Columns. Filter Model sends value = true, when false filter is selected.

### ISSUE THREAD

**Issue by AnastasiaEvgenia** [mui/mui-x#15225]
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-data-grid/filtering/

Steps:
1. First grid in documentation
2. Select filter in 'Is admin' column. First with is true. Second with is false
3. After selecting is false, you can see that displaying data are still the ones with true value.

![Screenshot_493](https://github.com/user-attachments/assets/4edf8ef8-ffdc-4d17-ba5f-4439a153f108)

### Current behavior

I debugged this issue in my app. Even if you select false, the filter model sends true.

Filter Model when is true is selected
![Screenshot_495](https://github.com/user-attachments/assets/0cb3b959-4183-4678-ba1f-e1c6552a0595)

Filter Model when is false is selected.
![Screenshot_496](https://github.com/user-attachments/assets/63450be4-56ba-4fe9-9b35-a8b3aea5b7ae)

Something could be wrong with the on change handler of the filter selection?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: boolean, column, filter, error in filter model

**Search keywords**:

**Comment by arminmeh** [comment]
Thanks for reporting @AnastasiaEvgenia 
I have confirmed the issue and will work on the fix

**Comment by arminmeh** [comment]
Root cause is the change made in
https://github.com/mui/mui-x/pull/14733

**Comment by k-rajat19** [comment]
Hi @arminmeh ,
the problem seems to be here `Boolean("false")` evaluates to `true`, sorry I didn't notice it while working on #14733 
I think the better approach to convert values to boolean type is  `String(value).toLowerCase() === 'true'` 
we should also probably need to check further that we are handling falsy values correctly or not :(
should I create a PR or are you willing to fix it yourself?

**Comment by arminmeh** [comment]
hey @k-rajat19 
if you have time, I would appreciate your help.
Otherwise, I will continue with it

**Comment by AnastasiaEvgenia** [comment]
Hi. Thank you for addressing this issue swiftly. 
Can you confirm that the solution will be released on Friday?

**Comment by arminmeh** [comment]
The plan is to have another release by the end of the week and the fix for this issue will be included.
