### ISSUE TITLE
[data grid] Copy paste error while copying string into date column?

### ISSUE THREAD

**Issue by KaralyosBela** [mui/mui-x#15256]
### The problem in depth

Hey! I have a problem with the date column copy paste.

In my old solution the formatting is correct when entering cell edit mode, but when i try to copy the row, it gives me the following error (look at gif). I created a better solution below.

![old](https://github.com/user-attachments/assets/a9feecd9-c064-4d98-8b39-dca6287c31ab)

Old solution:
```javascript
const handleDateField = (option: GridColDef, domainData: DomainData, field: Field, showTableCharms: boolean) => {
  option.type = 'date';
  option.filterOperators = getGridDateOperators();
  option.aggregable = false;

  option.renderCell = (params: GridRenderCellParams) => {
    const dateValue = dayjs(params.value as string);
    const dateLabel = params.value === TODAY_PLACEHOLDER ? formatDateDayjs(dayjs()) : formatDateDayjs(dateValue);

    if (dateValue.isValid() || params.value === TODAY_PLACEHOLDER) {
      return (
        <div title={dateLabel} style={metaFieldCellStyle(domainData, field.name)}>
          {dateLabel}
        </div>
      );
    } else {
      return (
        <div title={params.value as string} style={metaFieldCellStyle(domainData, field.name)}>
          {formatAsterisk(params.value, showTableCharms)}
        </div>
      );
    }
  };

  option.valueFormatter = (value) => {
    const dateValue = dayjs(value);
    if (dateValue.isValid()) {
      return formatDateDayjs(dateValue);
    } else {
      return value;
    }
  };

  option.valueGetter = (value) => {
    const dateValue = dayjs(value);
    const dateLabel = value === TODAY_PLACEHOLDER ? formatDateDayjs(dayjs()) : formatDateDayjs(dateValue);

    if (dateValue.isValid() || value === TODAY_PLACEHOLDER) {
      return dateLabel;
    } else {
      return value;
    }
  };
};

export default handleDateField;
```

This solution now has a working copy paste, but when i enter edit cell mode, the format is totally different. I could not find a way to fix this. I want the YYYY-MM-DD format when editing. 

![new](https://github.com/user-attachments/assets/211d84cf-46f2-48eb-a194-baab4c909919)

New solution:
```javascript
const handleDateField = (option: GridColDef, domainData: DomainData, field: Field, showTableCharms: boolean) => {
  option.type = 'date';
  option.filterOperators = getGridDateOperators();
  option.aggregable = false;

  option.renderCell = (params: GridRenderCellParams) => {
    const dateValue = params.value as Date;
    const dateLabel = dateValue ? formatDateDayjs(dayjs(dateValue)) : formatAsterisk(params.value, showTableCharms);

    return (
      <div title={dateLabel} style={metaFieldCellStyle(domainData, field.name)}>
        {dateLabel}
      </div>
    );
  };

  option.valueFormatter = (value) => {
    const dateValue = value as Date;
    return dateValue ? formatDateDayjs(dayjs(dateValue)) : value;
  };

  option.valueGetter = (value) => {
    if (value === TODAY_PLACEHOLDER) {
      return dayjs().toDate();
    }
    const dateValue = dayjs(value as string);
    return dateValue.isValid() ? dateValue.toDate() : null;
  };
};
```

Formatter function:
```javascript
export const formatDateDayjs = (date: dayjs.Dayjs, withTime = false): string => {
return withTime ? date.format('YYYY-MM-DD HH:mm') : date.format('YYYY-MM-DD');
};
```

I know that the problem is i want to copy a stringifed value into a date field, thats why i get the error, but i have no idea how to fix this.

Any idea how to fix this? Thanks in advance

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Don't forget to mention which browser you used.
    System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 22.5.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base: ^5.0.0-beta.26 => 5.0.0-beta.35
    @mui/icons-material: ^5.16.7 => 5.16.7
    @mui/lab: 5.0.0-alpha.141 => 5.0.0-alpha.141
    @mui/material: ^5.16.7 => 5.16.7
    @mui/x-data-grid-premium: ^7.20.0 => 7.20.0
    @mui/x-date-pickers:  7.21.0
    @mui/x-license: ^7.20.0 => 7.20.0
    @mui/x-tree-view-pro: ^7.20.0 => 7.20.0
    @types/react: 18.2.33 => 18.2.33
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: 5.3.6 => 5.3.6
    typescript: ~5.2.2 => 5.2.2
```
</details>

**Search keywords**: date, copy paste
**Order ID**: 86461

**Comment by KaralyosBela** [comment]
Hey @michelengelen ! I created a smaller code: https://stackblitz.com/edit/github-9f14mm?file=src%2Fdemo.tsx

The issues:
- When ignoreValueFormatterDuringExport is true, and I want to copy a whole row with checkboxes, ( get this error: cellParams.value?.toISOString is not a function. If I hide the date column and do the copy row, the size and color copied correctly with the formatted values.
- When ignoreValueFormatterDuringExport is false, and copying the row, with every column visible, the date is correctly copied, no error, but the size cell value is not copied with the formatted value. 

Is there a way to mark a column where I want the formatted value copied, and where i do not?

**Comment by michelengelen** [comment]
Hey @KaralyosBela ... thanks for providing a simple reproduction.

It is not possible to define columns where the `ignoreValueFormatterDuringExport` does not apply. However you can change the approach.

In addition to the `valueFormatter` we also have the [`valueGetter`](https://mui.com/x/react-data-grid/column-definition/#value-getter) function. This can be used as well to format the value. A downside is that this will make sorting by weight impossible. Here is the code to do that nevertheless: [valueGetter demo](https://github-9f14mm-9xtb9t.stackblitz.io).

The second approach would be to use a [`renderCell`](https://mui.com/x/react-data-grid/column-definition/#rendering-cells) instead of the `valueFormatter` function. This way you can keep the date value intact, but render a formatted date as well. [renderCell demo](https://stackblitz.com/edit/github-9f14mm-nqk9yt?file=src%2Fdemo.tsx).

Depending what your expected outcome is you can take one of these approaches.

Hope this helps!
