### ISSUE TITLE
[data grid] when the data grid list view is expected to become stable?

### ISSUE THREAD

**Issue by PraveenPeri** [mui/mui-x#15265]
### The problem in depth

Wanted to ask when the data grid list view is expected to become stable? https://mui.com/x/react-data-grid/list-view/#advanced-usage 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: List view in data grid
**Order ID**: 17223

**Comment by michelengelen** [comment]
I'll hook @joserodolfofreitas in here, but I guess this should be fully released with v8

**Comment by joserodolfofreitas** [comment]
Hi @PraveenPeri, nice to see your interest in this feature.
Please feel free to use it; the earlier we get feedback, the earlier we can start iterating to make it stable.

The feature is not battle-tested yet, but it is solid. We use the `unstable_` prefix primarily to signal that we may need to change the feature's API (based on user feedback).

**Comment by PraveenPeri** [comment]
@joserodolfofreitas Thanks for the response. We will begin using it soon.
