### ISSUE TITLE
[core] Missing @mui/system dependency with MUI v6

### ISSUE THREAD

**Issue by caelus-dev** [mui/mui-x#15267]
### Steps to reproduce

Hello!

I tried to upgrade from MUI v5 to v6. So as the official document stated, I just changed the `@mui/material` to the newest version and left everything else unchanged.
```
    "@emotion/react": "*",
    "@emotion/styled": "*",
    "@fontsource/roboto": "*",
    "@mui/icons-material": "*",
    "@mui/material": "^6.1.4",
    "@mui/x-date-pickers": "^7.21.0",
    "react": "^18.2.0",
```

However after changing the MUI v5 to v6, I got the following error: `@mui/system` is missing. 
```
[ERROR] Could not resolve "@mui/system/RtlProvider"
[ERROR] Could not resolve "@mui/system"
```

As @flaviendelangle suggested in another conversation, I checked if the `@mui/system` is installed with yarn info, and turned out `@mui/system` is totally missing. The yarn build also confirms the problem:
```
foo@workspace:. doesn't provide @mui/system (paa105), requested by @mui/x-date-pickers.
```

I tried `yarn explain peer-requirements` command, but it says:
`command doesn't support this warning type yet`

I also tried to clean the yarn cache, delete folders, use other pc but nothing solved the problem.

### Current behavior

`@mui/system` is not installed by `"@mui/material": "^6.1.4"`

### Expected behavior

`@mui/system` should be installed by `"@mui/material": "^6.1.4"`

**Search keywords**: dependency @mui/system

**Comment by LukasTy** [comment]
Hello @caelus-dev, are you using yarn >1 with the PnP module resolution mechanism?

This case is listed in [their FAQ](https://yarnpkg.com/features/pnp#how-can-i-fix-ghost-dependencies).

Creating a `.yarnrc.yml` file with the following contents fixes this issue.

```yml
packageExtensions:
  "@mui/x-date-pickers@*":
    dependencies:
      "@mui/system": "*"
```

We could list our packages in their known list to avoid this manual labor.
https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts
WDYT @mui/code-infra?

P.S. This applies to all the packages having the `@mui/system` peer dependency:
https://github.com/search?q=repo%3Amui%2Fmui-x+%22%40mui%2Fsystem%22%3A&type=code

**Comment by caelus-dev** [comment]
Hi @LukasTy , thank you for your answer!

> are you using yarn >1 with the PnP module resolution mechanism?

Yes, I use yarn 4.1.0 with pnp module, but I also tried the most recent yarn 4.5.1.

> Creating a .yarnrc.yml file with the following contents fixes this issue.

The yarn build no longer shows the error, but seems like the `@mui/system` package is still missing after setting the `packageExtensions`. Only workaround I found to put  `@mui/system` directly in the packages.json as dependency.

**Comment by LukasTy** [comment]
> The yarn build no longer shows the error, but seems like the `@mui/system` package is still missing after setting the `packageExtensions`. Only workaround I found to put `@mui/system` directly in the packages.json as dependency.

@caelus-dev Could you clarify what you mean by the package still missing? 🤔 
Where is it missing from?
What problems are you seeing?

**Comment by caelus-dev** [comment]
@LukasTy Sorry, that was my mistake. The `.yarnrc.yml` did not synchronized with the build pipeline config. So yes, putting your code snippet into the `.yarnrc.yml` solves the problem! Thanks!

**Comment by LukasTy** [comment]
I have created a PR on the yarn extensions side to possibly avoid the need for explicit declaration.
https://github.com/yarnpkg/berry/pull/6588
