### ISSUE TITLE
[data grid] Dynamic Header Generation Based on Column Count in MUI DataGrid

### ISSUE THREAD

**Issue by mahammahmood** [mui/mui-x#15278]
### The problem in depth

I'm using MUI DataGrid, and I want the header row in the Excel export to be dynamically generated, spanning across all columns. This header should display information such as the download timestamp and user info, with a custom background color. Currently, I need to set a fixed column count, so it doesn’t adjust dynamically based on the actual column count. Is there a solution to achieve this functionality?

Here is the live demo:
[https://stackblitz.com/edit/react-wgnwah?file=Demo.tsx](url)

![Screenshot 2024-11-05 123412](https://github.com/user-attachments/assets/fd6d9159-1cae-4e3a-b8fd-873afd36ba70)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: Data ,Grid , Premium, GridToolbarExport, GridExceljsProcessInput,
**Order ID**: 91010

**Comment by michelengelen** [comment]
You can [customize](https://mui.com/x/react-data-grid/export/#customization) the export with the `exceljsPreProcess` and `exceljsPostProcess` methods. This is based on the [exceljs](https://github.com/exceljs/exceljs#interface) package.

If you need assistance with this you should consider asking on StackOverflow or the community on our discord server.
