### ISSUE TITLE
[pickers] centering the Popper to the center of the window

### ISSUE THREAD

**Issue by isdisd2** [mui/mui-x#15291]
### Summary

how to set Popper's DatePicker position centered on the center of the window, similar to what MobileDatePicker does? MobileDatePicker does this automatically. Please add this option to DatePicker/DesktopDatePicker.
I can't use MobileDatePicker because I need a keyboard to enter the date. The keyboard is disabled in the mobile version.

### Examples

```tsx
slotProps={{
  popper: {
    placement: "center-center",
   },
}}
```

### Motivation

the 'placement' property, if set to "auto", sometimes places the popper outside the visible area of ​​the window.

**Search keywords**: center position DatePicker

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by LukasTy** [comment]
@isdisd2 could you clarify visually what you would like to achieve? 🤔 
`center` placement does not exist.
If you would like the "modal" experience, but have the option to edit the date with the keyboard, then feel free to follow https://github.com/mui/mui-x/issues/7869 and we could treat this as a duplicate at that point. 😃
