### ISSUE TITLE
[data grid] How to add a row in a grid with Server-side data?

### ISSUE THREAD

**Issue by creativecomposer** [mui/mui-x#15327]
### Background

In our React web application, we use the MUI DataGridPremium to Create, Read, Update, and Delete rows.
Since we have a large number of records, we want to use the `unstable_dataSource` prop, so that we could use the server-side filtering, sorting, and pagination.

Typically, without the `unstable_dataSource` prop, we could add rows as shown in the following example.

```jsx
import * as React from 'react';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import { randomInt, randomUserName } from '@mui/x-data-grid-generator';
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

const columns: GridColDef[] = [
  { field: 'id' },
  { field: 'username', width: 150 },
  { field: 'age', width: 80, type: 'number' },
];

let idCounter = 0;
const createRandomRow = () => {
  idCounter += 1;
  return { id: idCounter, username: randomUserName(), age: randomInt(10, 80) };
};

export default function UpdateRowsProp() {
  const [rows, setRows] = React.useState(() => [
    createRandomRow(),
    createRandomRow(),
    createRandomRow(),
    createRandomRow(),
  ]);

  const handleAddRow = () => {
    setRows((prevRows) => [...prevRows, createRandomRow()]);
  };

  return (
    <Box sx={{ width: '100%' }}>
      <Stack direction="row" spacing={1}>
        <Button size="small" onClick={handleAddRow}>
          Add a row
        </Button>
      </Stack>
      <Box sx={{ height: 400, mt: 1 }}>
        <DataGridPremium rows={rows} columns={columns} />
      </Box>
    </Box>
  );
}
```

### Question

Could you please explain how to add a row to the grid when the rows are fetched using `unstable_dataSource` prop?
It looks like the `rows` and `unstable_dataSource` are mutually exclusive. Therefore, we did not find a way to do this.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Browser: Chrome
  
$ npx @mui/envinfo
Need to install the following packages:
@mui/envinfo@2.0.29
Ok to proceed? (y)
                                                                                                                                                                                     
  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 129.0.6668.58
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/core-downloads-tracker:  5.16.7
    @mui/icons-material: ^5.14.8 => 5.15.3
    @mui/lab: ^5.0.0-alpha.162 => 5.0.0-alpha.162
    @mui/material: ^5.16.7 => 5.16.7
    @mui/private-theming:  6.1.3
    @mui/styled-engine:  6.1.3
    @mui/styled-engine-sc: ^5.12.0 => 5.14.12
    @mui/system: ^6.1.3 => 6.1.3
    @mui/types:  7.2.18
    @mui/utils:  5.16.6
    @mui/x-data-grid:  7.19.0
    @mui/x-data-grid-premium: ^7.19.0 => 7.19.0
    @mui/x-data-grid-pro:  7.19.0
    @mui/x-internals:  7.18.0
    @mui/x-license:  7.18.0
    @types/react:  18.2.47
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: ^5.3.11 => 5.3.11
    typescript: ^5.1.6 => 5.3.3
```
</details>

**Search keywords**: server-side
**Order ID**: 82117

**Comment by michelengelen** [comment]
Hey @creativecomposer you can use the `updateRows` method on the grid API. After adding it will be in the internal grid state and needs to be saved to the backend before refetching the rows again, otherwise the data in the new row will be lost.

here is an example of a click handler adding a row at the bottom: 
```tsx
const handleAddRow = React.useCallback(() => {
  const id = Math.random();
  apiRef.current.updateRows([{ id, desk: null, commodity: null }]);
}, [apiRef]);
```

[Demo on codesandbox](https://codesandbox.io/p/sandbox/serverside-add-row-82lx5l)

There are a few ways how you can safe the new row to the server as well:
- provide an action cell with a safe or discard button (as an example)
- immediately safe on row creation (in `handleAddRow`)
- safe on editing the values (e.g. using [`processRowUpdate`](https://mui.com/x/react-data-grid/editing/#the-processrowupdate-callback))

side note:
That being said, there is one more way, but that highly depends on your backend system: You could create a new row on your server by clicking the button and then refetch the whole set on success.

Did i miss something @MBilalShafi ?

**Comment by creativecomposer** [comment]
@michelengelen Thank you for your quick response. It works 👍 

I have a question about the newly added row:

The new row gets appended to the bottom of the table. Is there a way/trick to make the new row appear as the first row in the grid?
If the row appears at the bottom of the table, the user would have to scroll down in order to be able to find it. Therefore, if the new row appears at the top, we believe it would be helpful for the users that want to add a row and edit some cell data before saving to the back-end.

**Comment by michelengelen** [comment]
Currently I don't think that this is possible. It's a different story though if you would update the server data on creation directly and then refetch it to display ... then you could adjust the initial row-order to show the new ones first.

**Comment by michelengelen** [comment]
Another approach would be to mark them as new rows and scroll down to where they got inserted. That's definitely possible. 👍🏼

**Comment by creativecomposer** [comment]
@michelengelen Thank you for the clarification.
