### ISSUE TITLE
[DateCalendar] Display week number in ISO 8601 when using `props.displayWeekNumber`

### ISSUE THREAD

**Issue by danilafrolov** [mui/mui-x#15334]
### Summary

Currently we can display week number in `DatePicker` calendar by passing `displayWeekNumber={true}`. However, I didn't find a way to pass any options to indicate, which standard (or format) should be used.

### Examples

ISO 8601: 
> if 1 January is on a Monday, Tuesday, Wednesday or Thursday, it is in week 01. If 1 January is on a Friday, Saturday or Sunday, it is in week 52 or 53 of the previous year (there is no week 00). 28 December is always in the last week of its year.

Current implementation does not comply with IS0 8601: 
![image](https://github.com/user-attachments/assets/50bc312e-fe9a-4e2a-95d8-8a19f92fd933)

Considering the rules above, it should be week 53 of the previous year (2026), not the first week of 2027.
For example: http://www.whatweekisit.org/calendar-2026.html

![image](https://github.com/user-attachments/assets/a39b7e8b-9785-4178-859c-419c5eca2338)

### Motivation

It would be fine if I could choose which format should be used for week numbers. Currently, I have to customize calendar component and not use `displayWeekNumber` at all.

**Search keywords**: displayWeekNumber, week number, ISO 8601

**Comment by michelengelen** [comment]
Hey @flaviendelangle ... I was just looking into this as well and at least dayJs has a separate plugin that needs to be used for this: [`isoWeek`](https://day.js.org/docs/en/plugin/iso-week)

Haven't checked yet if the other libs need one as well to work correctly. 👍🏼

**Comment by danilafrolov** [comment]
Hi, @flaviendelangle 
Thank you for reply! 

We are using `date-fns` (`AdapterDateFns`).

**Comment by flaviendelangle** [comment]
I tried with `getISOWeek` on `date-fns` but it's not the behavior you are expecting:

![image](https://github.com/user-attachments/assets/28af26a5-5a16-424d-967f-543730051a75)

The behavior is exactly the same with the `isoWeek` of `dayjs`.

If you are able to get the behavior you want with `date-fns`, I can help you implement it inside our pickers.
But I'm not sure if that's doable on the date library side (which we have no control over :grimacing: )

**Comment by michelengelen** [comment]
@flaviendelangle if you use the iso start day of week it is the expected behavior i think! Will check when I am back at the desk!

**Comment by danilafrolov** [comment]
Probably `getISOWeek` is OK for me 😃 
It may be confusing since you have Sunday as the first day of the week.

**Comment by danilafrolov** [comment]
For example, it's current behaviour of `DatePicker`: 
![image](https://github.com/user-attachments/assets/5759a58f-8b8f-4d8b-a05d-84838ee48475)

And here is the custom calendar where I use `getISOWeek`: 
![image](https://github.com/user-attachments/assets/c2b88e22-2296-4281-a029-60da72e2c9aa)

Seems to be working as expected.

**Comment by flaviendelangle** [comment]
If `getISOWeek` is good for you, then you can override the adapter as follow:

```tsx
import getISOWeek from 'date-fns/getISOWeek';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';

class ExtendedAdapterDateFns extends AdapterDateFns {
  public getWeekNumber = (value: Date) => {
    return getISOWeek(value);
  };
}
```

**Comment by flaviendelangle** [comment]
[here is working example](https://codesandbox.io/p/sandbox/zealous-worker-96xy5x?file=%2Fsrc%2FDemo.tsx%3A19%2C27&from-embed=&workspaceId=836800c1-9711-491c-a89b-3ac24cbd8cd8)

**Comment by danilafrolov** [comment]
@flaviendelangle thanks a lot!

**Comment by flaviendelangle** [comment]
Your welcome :pray: 

Just in case, the adapter are public API but public API we don't encourage people to play with unless they need to.
I think overriding `getWeekNumber` is the best solution here but it should always be the last solution :+1:
