### ISSUE TITLE
[data grid] Row spanning not working correctly with pinned columns

### ISSUE THREAD

**Issue by lhilgert9** [mui/mui-x#15367]
Row spanning is not working correctly with pinned columns, as both cells have the same zIndex of 5.
Example (left column is pinned): 
<img width="944" alt="Bildschirmfoto 2024-11-10 um 18 57 06" src="https://github.com/user-attachments/assets/9b8daed5-c0cb-48cc-ab2a-50c9fd5da62e">

**Search keywords**:

**Comment by michelengelen** [comment]
@lhilgert9 thanks for opening an issue AND a PR! 👍🏼 🤩
