### ISSUE TITLE
[license] License Key Usage for testing/CI

### ISSUE THREAD

**Issue by B-Henize** [mui/mui-x#15376]
### The problem in depth

How should the license key be used for unit testing? Should we inject it or is there a “testing mode” for Pro/Premium?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: license key testing unit integration
**Order ID**: 100698

**Comment by michelengelen** [comment]
Hey @B-Henize ... no need to adjust for CI/Testing. Just use the key you have and inject it as you would with your application. 👍🏼 

Any other questions regarding this?
