### ISSUE TITLE
[data grid] `GridEditSingleSelectCell` does not work if the `valueOptions` are passed directly to it inside `renderEditCell`

### ISSUE THREAD

**Issue by sandeep-exe** [mui/mui-x#15381]
### Steps to reproduce

Link to live example: [Codesanbox](https://codesandbox.io/p/sandbox/kind-dhawan-l3wrsn?file=%2Fsrc%2FDemo.tsx%3A75%2C26)

### Current behavior

When defining columns, use `renderEditCell` to return a component to render during editing. Use `GridEditSingleSelectCell` within it and pass `valueOptions` to specify available options. Without this, nothing will be rendered inside the cell in edit mode.

### Expected behavior

`GridEditSingleSelectCell's` `valueOptions` should work within `renderEditCell` as well.

### Context

I have a similar scenario where selecting an option in one column updates the options and component in the next column. For example, if I select a list in Column A, Column B should display a dropdown; if I select a date in Column A, Column B should show a date picker.

While GridEditInputCell and GridEditBooleanCell work correctly, GridEditSingleSelectCell does not update as expected in this dynamic setup

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Amazon Linux 2
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.182
```
</details>

**Search keywords**: GridEditSingleSelectCell

**Comment by michelengelen** [comment]
Hey @sandeep-exe ... `GridEditSingleSelectCell` is not meant to be used like that. It grabs the valueOptions from the column definition to ensure everything is correct. 

So if no options are present it wont render at all

What you are trying to do is possible, but highly discouraged to do, as the column definition should ideally not change.

You could do something like updating the column type when selecting a value in `COL A`, but that would update `COL B` entirely.

If you absolutely need that I would advise to use the `string` type on the column and provide a custom edit cell rendering based on the selected value using the apiRef methods.

**Comment by michelengelen** [comment]
This kind of works, but you would need to force a rerender on each selection in the types column, otherwise the edit cell only updates when entering edit mode for it:
```tsx
{
  field: 'value',
  headerName: 'Values',
  width: 120,
  editable: true,
  type: 'singleSelect',
  valueOptions: [
    { label: 'True', value: true },
    { label: 'False', value: false },
  ],
  renderEditCell: EditCellRender,
},
{
  field: 'types',
  headerName: 'Type',
  type: 'singleSelect',
  valueOptions: () => Object.values(SUPPORTED_TYPES),
  width: 140,
  editable: true,
},
```

with this editing component:
```tsx
const EditCellRender = (props: GridRenderCellParams) => {
  const { row } = props;
  switch (row.types) {
    case SUPPORTED_TYPES.Number:
      return <GridEditInputCell {...props} type="number" />;
    case SUPPORTED_TYPES.Boolean:
      return (
        <GridEditSingleSelectCell
          {...props}
          valueOptions={[
            { label: 'True', value: true },
            { label: 'False', value: false },
          ]}
        />
      );
    case SUPPORTED_TYPES.Date:
      return <GridEditDateCell {...props} />;
    default:
      return <GridEditInputCell {...props} />;
  }
};
```

Would this work for you?

**Comment by sandeep-exe** [comment]
Yes, I know this kind of solves my issue (I even tired it), but my options are dynamic. For example, I could have another type, such as 'fruits,' where I need those options in the dropdown, and the list of fruits is coming from an API.

**Comment by michelengelen** [comment]
In this case building a custom editing cell renderer that does all of that for you might be the best shot. Out of the box we do not support such a use case as we typically aim for consistently columns.

This is a customization request outside of our support. If you need help building your feature I would advise to join the community on discord or post a question on StackOverflow. I'll close this for now.
