### ISSUE TITLE
[docs] "more details" link in introduction leads to private/empty notion.site page

### ISSUE THREAD

**Issue by ulrichstark** [mui/mui-x#15393]
### Related page

https://mui.com/x/introduction/#mui-x-vs-mui-core

### Kind of issue

Other

### Issue description

![image](https://github.com/user-attachments/assets/15af2c87-406a-4988-8a1b-a5d0cea734ff)
https://mui-org.notion.site/MUI-X-3f8ad249aeca430d81aae5dee947451a#f8e48daaf2fa4902b1415e3708560c0f

**Search keywords**: mui x more details link notion no access

**Comment by michelengelen** [comment]
Thanks @ulrichstark ... should be this page: https://mui-org.notion.site/MUI-s-products-a-brief-overview-9c5e8e11eb1247c3a124b446be7451cb

I'll open a PR to fix that! 👍🏼

**Comment by oliviertassinari** [comment]
Also reported in 

<img width="569" alt="SCR-20241212-bbzs" src="https://github.com/user-attachments/assets/ea6147f2-f1d3-4940-8509-cc4953ced33b" />

https://mui-org.slack.com/archives/C04U3R2V9UK/p1733879862542189

I have cherry-picked the change to the `v7.x` branch with: aabd99524
