### ISSUE TITLE
[pickers][DateTimeRangePicker] Issue with setting initial time values

### ISSUE THREAD

**Issue by JessArschoot** [mui/mui-x#15405]
### Steps to reproduce

Steps:
1. I have an DateTimeRangePicker with property referenceDate 
   - moment().hour(8).minute(0) .second(0)
2. When selecting the first date, time selection is giving me 00:00:00

### Current behavior

When I select the start date, the initial time is 00:00.

### Expected behavior

The initial time should be 08:00

### Context

I am working on a form that defines the work schedule for an employee using the MUI DateTime Range Picker. Typically, employees have fixed working hours, so we’d like to set default start and end times (e.g., 8:00 AM and 5:00 PM) when the date range is selected. However, we currently cannot set initial time values using the referenceDate prop.

Expected Behavior:

Ideally, I’d like to be able to specify default time values for the start and end of the date range. For instance:

Start Date: default time set to 8:00 AM.
End Date: default time set to 5:00 PM.
These defaults would pre-fill as initial times when the user selects a date range, reducing repetitive inputs. However, adjusting these initial times through the referenceDate prop is currently unsupported.

**Search keywords**: DateTimeRangePicker referenceDate
**Order ID**: 89609

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼
