### ISSUE TITLE
mui pro issue-  [DataGrid] Fix print export failure when hideFooter option is set

### ISSUE THREAD

**Issue by jason-pallet-track** [mui/mui-x#15403]
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-xezygx?file=Demo.jsx

Steps:

    Press 'Export'
    Press 'Print'

### Current behavior

An error is displayed in the console:

"
Error in /turbo_modules/@mui/x-data-grid@7.3.2/node/hooks/features/export/useGridPrintExport.js (136:23)
Cannot read properties of null (reading 'style')
"

### Expected behavior

Print all the rows that are in the datagrid and hide footer

### Context

Someone created this bug ticket and fixed the code few months ago. I checked its merged into main. But I still get the same problem for mui pro v7.22. I guess he fixed the issue in free version but not in pro or premium version?

Quote from https://github.com/mui/mui-x/pull/13034
I am trying to hide the footer in the print export. But hideFooter: true breaks the data grid. And when set to false, it works as expected.

This error appeared after updating to the latest version. Before I was using version 6.11.1 and it worked.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: print export

**Comment by iida-sh** [comment]
I encountered the same problem in free

**Comment by michelengelen** [comment]
@jason-pallet-track in your example you are using [v7.3.2](https://github.com/mui/mui-x/releases/tag/v7.3.2) which was released May 2nd 2024 and the linked PR where this gets fixed was merged Jun 26 2024, so the earliest you can use this bugfix is starting from [v7.8.0](https://github.com/mui/mui-x/releases/tag/v7.8.0)

It is working with the right versions. Closing! 👍🏼
