### ISSUE TITLE
[pickers] Date picker calender icon is not coming on chrome on windows 10 machine

### ISSUE THREAD

**Issue by smita-mui** [mui/mui-x#15433]
I am using 
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment'
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';

On a system with windows 10, calendar icon is not appearing. We are using latest version of chrome.

There is no issue on windows 11 machine.
Is it a known issue or I need any configuration update?

Please help.

**Search keywords**: 

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @smita-mui ... could you share a bit more information?
- Which browser are you using? 
- Which versions did you install?
- Is the error showing in the docs as well or only in your implementation?
- Some info and ideally a code reproduction in a sandbox would be great as well!

**Comment by smita-mui** [comment]
import TextField from '@mui/material/TextField';
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment'
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { useState } from 'react';

export const BasicDatePicker = ({ inputFormat, label, value, onChange, readOnly = false, ...props }) => {
  const [open,setOpen] = useState(false);
  return (
    <LocalizationProvider dateAdapter={AdapterMoment}>
      <DatePicker
        inputFormat={inputFormat ? inputFormat : "DD/MM/YYYY"}
        label={label}
        value={value}
        maxDate={props.maxDate ? props.maxDate : ""}
        minDate={props.minDate ? props.minDate : ""}
        onChange={(event) => onChange(event)}
        open={open}
        onClose={() => setOpen(false)}
        renderInput={(params) => <TextField
          {...params} error={params.disabled ? false : params.error}
          variant="standard"
          inputProps={{ ...params.inputProps, readOnly }}
          onClick={(e) => setOpen(true)}
          sx={{
            label: {color: "rgb(81, 81, 81)"},
            '.MuiInputBase-input': {
            
            },
            '.MuiInputBase-root': {
              width: props.width ? props.width : "17vw",
              '&:before': {
                borderBottom: '1px solid !important',
                borderColor: '#ccc !important',
              },
              '&:after': {
                borderBottom: '1px solid',
                borderColor: '#ccc !important',
              }
            },
          }
          }
        />}
        {...props}
      />
    </LocalizationProvider>
  );
}

**Comment by smita-mui** [comment]
This is my component. Its not giving any error, just calendar icon is not appearing to select the date on windows 10 and latest chrome version.

**Comment by smita-mui** [comment]
Hi, I am not using mobile picker variant.  Its DatePicker with below code:

export const DatePicker = /*#__PURE__*/React.forwardRef(function DatePicker(inProps, ref) {
  const props = useThemeProps({
    props: inProps,
    name: 'MuiDatePicker'
  });

  const {
    desktopModeMediaQuery = '@media (pointer: fine)',
    DialogProps,
    PopperProps,
    TransitionComponent
  } 

Means, we have everything on place. Can you confirm that the mui  (@mui/x-date-pickers": "^5.0.14") supports windows 10?

**Comment by michelengelen** [comment]
Hey @smita-mui ... I just tried this in browserstack on windows 10 and the latest Chrome (131) and it works as expected. There has to be some modification you made to the code or the environment that makes this bug appear.

Could you pease try this and see if the error persists:
1. Use another Windows 10 machine
2. Use another browser
3. Try the [demo on our docs](https://mui.com/x/react-date-pickers/date-picker/)

**Comment by LukasTy** [comment]
> What else you need to know about the device? Please let me know.

@smita-mui I mentioned in my comment, that it might be an "issue" with hardware (device) reporting incorrect pointer capabilities to the OS.
Windows versions should have nothing to do with this, but if the same device works as expected on Windows 11, in that case, Windows 10 with the combination of that particular hardware is to blame. 🙈 

If you could provide more information about the device (exact model, screen type, resolution), we could "guestimate" the probable cause more precisely. 😉
