### ISSUE TITLE
[data grid] Incorrect cell width calculation when using css border

### ISSUE THREAD

**Issue by DanielaDark** [mui/mui-x#15472]
### Steps to reproduce

Steps:
1. Open this link to live example: (https://codesandbox.io/p/sandbox/winter-cache-c9vdl3)

<img width="646" alt="SCR-20241119-bedg" src="https://github.com/user-attachments/assets/1df4c28c-e21e-4411-a142-29815c895775">

2. Either examine the css properties of cells or observe that the cell border (blue) on right side and bottom is not visible. 

### Current behavior

When adding css border to row and cell, cell width does not change. As a result cells are wider than provided width.
In provided example Table width is 600px. Row has 1px border, the width of row is 598px (correct behavior). 
There are 2 cells in a row, each with 1px border. First cell width 200px (incorrect, should be 198px). Second cell has flex = 1 property, calculated width 398px (incorrect, should be 396px).

### Expected behavior

When adding css border to row and cell, cell width is correctly calculated. Meaning cell width shrinks when cell border is added.

### Context

Our Style-Guidelines require that both rows and cells have borders. Rows when they are selected and cells when keyboard focus is applied, as example for keyboard navigation. Having both properties active is in our case not unusual.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browser used: Firefox

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: 130.0.6723.117
    Edge: Chromium (131.0.2903.51)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.4
    @emotion/styled: ^11.10.6 => 11.11.5
    @mui/base:  5.0.0-alpha.124
    @mui/core-downloads-tracker:  5.15.18
    @mui/icons-material: 5.11.16 => 5.11.16
    @mui/lab: 5.0.0-alpha.125 => 5.0.0-alpha.125
    @mui/material: 5.11.16 => 5.11.16
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/styles: 5.11.16 => 5.11.16
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid:  6.9.2
    @mui/x-data-grid-premium: 6.9.2 => 6.9.2
    @mui/x-data-grid-pro:  6.9.2
    @mui/x-license-pro:  6.9.0
    @types/react: ^18.0.26 => 18.3.2
    react: ^18.2.0 => 18.3.1
    react-dom: ^18.2.0 => 18.3.1
    typescript: 4.4.3 => 4.4.3
```
</details>

**Search keywords**: DataGrid width
**Order ID**: 99555

**Search keywords**:

**Comment by DanielaDark** [comment]
Thank you @samuelsycamore for your fast response!
No, unfortunately adding padding does not solve the problem. The problem is that the contents of the grid do not scale down correctly to fit in the grid. For me it looks like setting the "flex=1" property does not calculate correct cell width when row border is added.
Example both borders:
![grafik](https://github.com/user-attachments/assets/e4118977-1d36-4f5e-98fb-ec15ed321a36)
Example only row border.
![grafik](https://github.com/user-attachments/assets/eae16029-4f98-4ac0-b9de-63ea78c4a578)

P.S. Thank you for your hint about the second repo. Should I close this issue here and reopen it in the other repo?

**Comment by DanielaDark** [comment]
@michelengelen, you are absolutely right, that when only row gets a border, your provided styling works. When also cell gets a Border, it does not work properly.
```
export const CustomThemeOptions = createTheme({
  components: {
    MuiDataGrid: {
      styleOverrides: {
        row: {
          border: "1px solid red",
          boxSizing: "border-box",
        },
        cell: {
           border: "1px solid blue",
           boxSizing: "border-box",
        },
      },
    },
  },
});
```
Result:
![grafik](https://github.com/user-attachments/assets/d88b9bcd-e25d-449e-84eb-e6de4a4ae7ae)

**Comment by michelengelen** [comment]
> @michelengelen, you are absolutely right, that when only row gets a border, your provided styling works. When also cell gets a Border, it does not work properly.
> 
> ```
> export const CustomThemeOptions = createTheme({
>   components: {
>     MuiDataGrid: {
>       styleOverrides: {
>         row: {
>           border: "1px solid red",
>           boxSizing: "border-box",
>         },
>         cell: {
>            border: "1px solid blue",
>            boxSizing: "border-box",
>         },
>       },
>     },
>   },
> });
> ```
> 
> Result: ![grafik](https://private-user-images.githubusercontent.com/7094857/390714475-d88b9bcd-e25d-449e-84eb-e6de4a4ae7ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzE2MzgsIm5iZiI6MTczMzEzMTMzOCwicGF0aCI6Ii83MDk0ODU3LzM5MDcxNDQ3NS1kODhiOWJjZC1lMjVkLTQ0OWUtODRlYi1lNmRlNGE0YWU3YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDJUMDkyMjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjUwNWMyOWVhNzVkNTVmMmNmZGFmYjc3NjYyN2E3NWE4MGZiNGFhNWIyMzMzNjFlZTY1MjFhZDg1NzYzNzBiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wIZIUAoZi1mT_Ui16ufYWdkot15uP6AUEnIiMUP8YmE)

All right ... that's correct. we do calculate the width manually and apply it in our rendering process as a CSS variable ... I am not sure if we can change that behavior, so. the best course of action for you would be to use box shadow as a border.

**Comment by romgrk** [comment]
Sorry I missed this, yes the grid needs to do its own calculations for virtualizations, we can't allow borders that haven't been included in the calculations. You can also superimpose a `&::after { position: absolute }` element and apply the border on that one, that won't affect layout, but `box-shadow` or `outline` would be leaner.
