### ISSUE TITLE
[data grid] Slow performance of the mui x grid premium when scrolling with sticky columns

### ISSUE THREAD

**Issue by igortas** [mui/mui-x#15501]
### Current behavior

Mui x grid runs so slow on localhost (even  the performance is far better with production build. but still the problem is there), the scroll is laggish, and laggin when I have many colums and sticky headers (column >= 30 and sticky heeaders >=3)

### Expected behavior

I expect the grid to works smooth and not working slow and laggish

### Context

I'm trying to render table with dynamic number of columns >=40 with lazy loading and >=10.000 rows and sometimes with sticky headers >=3.
Optimization with useMemo, useCallback and stable references for some static objects outside of the components, not helping me at all.

### Your environment

  System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  Binaries:
    Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.6.0/bin/npm
    pnpm: 9.13.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.5 => 11.13.5 
    @emotion/styled: ^11.13.5 => 11.13.5 
    @mui/icons-material: ^6.1.7 => 6.1.7 
    @mui/lab: ^6.0.0-beta.15 => 6.0.0-beta.15 
    @mui/material: ^6.1.7 => 6.1.7 
    @mui/x-data-grid-premium: ~7.22.2 => 7.22.2 
    @mui/x-license: ^7.21.0 => 7.21.0 
    @mui/x-tree-view: ~7.22.1 => 7.22.1 
    @types/react: ^18.3.12 => 18.3.12 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^5.6.3 => 5.6.3 

**Search keywords**: grid, performance

**Comment by michelengelen** [comment]
Hey @igortas ... could you share your specific implementation? Or at least a stripped down version of it that shows the problem.

I am running a data grid premium on my localhost with 50_000 rows and 30 columns and cannot see major lags (slight banding when scrolling really fast, but thats to be expected).

So if you see any performance problems we can only help you when we can view the code you are trying to implement.

**Comment by igortas** [comment]
Hi @michelengelen 
Hard to reproduce, I have some wrapper on top of mui x grid, and is reused in many places so it has lots of props (some for simplicity are organized as objects).
As far as I can do some optimization I extracted some code outside of the components, or I'm using useMemo or useCallback, as explained per docs.

So I've tried everything to wrap in useMemo and useCallback, so I can prevent somehow cascade rerending, but for some reason x grid works slow, especially when scrolling, and the biggest problem I have for instances where I have >=40 columns and 4-5 sticky columns (worst thing is that sticky columns are components with heavy logic).

Can u take a look at the wrapper(some code was removed and move to the components where they use the shared instance, but really nothing help). 

If, the code above the x grid is somehow problematic, what can u suggest to be done....

```
const initialState = {
  density: "compact" as GridDensity,
};
const groupingColDef = {
  minWidth: 200,
  hideDescendantCount: true,
};
const autosizeOptions = {
  includeHeaders: true,
  expand: true,
};

export const MuiTable = <T,>({
  data,
  rowId = "",
  columns = [],
  clientSearch = true,
  onRowsScrollEnd,
  maxHeight,
  sortModel = [],
  deleteToolbarAction,
  onRowClick,
  showActiveFilters = false,
  loading = false,
  minHeight,
  headingActions,
  highlightHeader = false,
  grouping,
  hide,
  disable,
  selection,
  customColumnMenu = undefined,
}: MuiDataGridProps<T>) => {
  const [density, setDensity] = useState<GridDensity>("compact");
  const apiRef = useGridApiRef();

  const { selectedDataView, setSelectedDataView } = useMuiTableContext();
  const {
    handleColumnVisibilityChange,
    handleFiltersChange,
    handleOnSortModelChange,
    handleRowGroupingChange,
    handleChangePinnedColumns,
  } = useDataGridHandlers(); // Using controlled state set initial view configuration

  useEffect(() => {
    setSelectedDataView({
      ...emptyDataView,
      configuration: {
        ...emptyDataView.configuration,
        sortModel,
        rowGroupingModel: grouping ? [grouping?.leafField] : [],
        pinnedColumns: {
          left: columns
            .filter((column) => column.stickyHeaderLeft?.length)
            .map((column) => column.field),
          right: columns
            .filter((column) => column.stickyHeaderRight?.length)
            .map((column) => column.field),
        },
      },
    });
  }, []);

  const { showPreview, muiSearchField, resetSelectedRows, selectedRows } =
    useMuiTableContext<any>();

  const disableRowGrouping = grouping?.disableRowGrouping ?? false;
  const multipleRowsSelection = selection?.multipleRows ?? false;
  const checkboxSelection = !!(selection?.checkboxes && data.length);
  const preSelectedRows = selection?.preSelectedRows ?? [];
  const disabledRows = disable?.rows ?? [];
  const disableRowClickOnCheckbox = disable?.rowClickOnCheckbox ?? false;

  const { columns: columnsPrepared } = useConvertForDataGrid<T>({
    columns,
    selectedRows,
    columnsOrder: selectedDataView.configuration.columnsOrder,
  });

  const onceRef = useRef(false);
  const updateRef = useRef(false); //workaround for sticky columns misaligned with header

  useEffect(() => {
    if (apiRef.current?.autosizeColumns) {
      if (!onceRef.current) {
        apiRef.current.autosizeColumns({
          includeHeaders: true,
          expand: true,
        });
      }
    }
  }, [apiRef.current?.autosizeColumns]);

  const getRowIdCallback = useCallback(
    (row: any) => (rowId ? row[rowId] : (row as any)._id),
    [rowId]
  );

  useEffect(() => {
    if (!updateRef.current && preSelectedRows.length > 0) {
      resetSelectedRows(
        data.filter((row) =>
          preSelectedRows.some(
            (preselectRow) =>
              getRowIdCallback(preselectRow) === getRowIdCallback(row)
          )
        )
      );
      updateRef.current = true;
    }
  }, [preSelectedRows, resetSelectedRows, data, getRowIdCallback]);

  const onRowSelectionModelChange = useCallback(
    (rowSelectionModel: string[]) => {
      const newSelectedRows = getSelectedRows(
        data,
        selectedRows,
        rowSelectionModel,
        !!(checkboxSelection || preSelectedRows.length > 0),
        getRowIdCallback
      );
      resetSelectedRows(newSelectedRows);
      if (!disableRowClickOnCheckbox) {
        const row = getCurrentRow(
          newSelectedRows,
          rowSelectionModel,
          !!(checkboxSelection || preSelectedRows.length > 0),
          getRowIdCallback
        ) as T;
        if (row) {
          onRowClick?.(row, newSelectedRows);
        }
      }
    },
    [
      resetSelectedRows,
      onRowClick,
      getCurrentRow,
      getRowIdCallback,
      selectedRows,
      data,
      checkboxSelection,
      disableRowClickOnCheckbox,
      preSelectedRows.length,
    ]
  );

  const rows = useMemo(
    () => (clientSearch ? getFilteredRows(data, muiSearchField) : data),
    [data, muiSearchField, clientSearch]
  );

  const columnVisibilityModel = useMemo(() => {
    return {
      id: false,
      _id: false,
      _primaryKey: false,
      ...Object.assign(
        {},
        ...(hide?.fields ?? []).map((field) => ({ [field]: false }))
      ),
      ...selectedDataView.configuration.columnsVisibility,
    };
  }, [selectedDataView.configuration.columnsVisibility, hide?.fields]);

  const sxProps = useMemo(
    () => ({
      "& .MuiDataGrid-virtualScroller": {
        overflow: hide?.scrollbar ? "hidden" : "auto",
      },
    }),
    [hide?.scrollbar]
  );

  const slots = useMemo(
    () => ({
      columnMenu: grouping?.leafField ? customColumnMenu : undefined,
      toolbar: () => (
        <MuiTableToolbar
          hideEmptyValuesSwitch={hide?.emptyValuesSwitch ?? false}
          hideToolbar={hide?.toolbar ?? false}
          selectedRows={selectedRows}
          deleteToolbarAction={deleteToolbarAction}
          getRowId={getRowIdCallback}
        />
      ),
      ...toolbarIcons,
    }),
    [
      selectedRows,
      deleteToolbarAction,
      hide?.toolbar,
      hide?.emptyValuesSwitch,
      grouping?.leafField,
    ]
  );

  const slotProps = useMemo(
    () => ({
      toolbar: {
        showQuickFilter: false,
        excelOptions: {
          disableToolbarButton: disable?.export ?? false,
        },
      },
    }),
    [disable?.export]
  );

  return (
    <>
      {headingActions?.show && (
        <MuiTableHeading {...headingActions} resultsCount={data.length} />
      )}
      <ThemeProvider theme={dataGridTheme}>
        {showActiveFilters && data.length > 0 && (
          <ActiveFilters
            activeFitlers={
              selectedDataView.configuration.filterModel ?? {
                items: [],
              }
            }
            rowGroupingFilters={selectedDataView.configuration.rowGroupingModel}
          />
        )}
        <StyledMuiDataGrid
          getRowId={getRowIdCallback}
          columns={columnsPrepared}
          rows={rows}
          apiRef={apiRef}
          maxHeight={maxHeight}
          minHeight={minHeight}
          highlightHeader={highlightHeader}
          groupingColDef={groupingColDef}
          sx={sxProps}
          disableRowGrouping={disableRowGrouping}
          rowSelectionModel={selectedRows.map((row) => getRowIdCallback(row))}
          onRowSelectionModelChange={(rowSelectionModel) => {
            if (checkboxSelection && apiRef.current) {
              onRowSelectionModelChange(rowSelectionModel as string[]);
            }
          }}
          isRowSelectable={(params) =>
            !disabledRows.some((disabledRowId) => disabledRowId === params.id)
          }
          getCellClassName={(params) =>
            disabledRows.some((disabledRowId) => disabledRowId === params.id)
              ? "disabled"
              : "active"
          }
          columnVisibilityModel={columnVisibilityModel}
          onColumnVisibilityModelChange={handleColumnVisibilityChange}
          slots={slots}
          slotProps={slotProps}
          autosizeOptions={autosizeOptions}
          onRowsScrollEnd={(params, event, details) =>
            onRowsScrollEnd?.(params, event, details)
          }
          autosizeOnMount
          checkboxSelection={checkboxSelection}
          hideFooter={hide?.footer ?? true}
          initialState={initialState}
          density={density}
          onDensityChange={(newDensity) => setDensity(newDensity)}
          showCellVerticalBorder
          showColumnVerticalBorder
          onRowClick={(params, event) => {
            const rowId = getRowIdCallback(params.row);
            if (grouping?.rowClick) {
              const rowNode = apiRef.current.getRowNode(params.id);
              const rowsIds = apiRef.current.getRowGroupChildren({
                groupId: params.id,
              });
              if (rowNode && rowNode.type === "group") {
                grouping?.rowClick(rowsIds as string[]);
              }
              return;
            }

            const isValid =
              rowId &&
              showPreview &&
              !disabledRows.some((disabledRowId) => disabledRowId === rowId);

            if (isValid && multipleRowsSelection) {
              onRowSelectionModelChange([rowId]);
              return;
            }

            if (isValid) {
              onRowClick?.(params.row, selectedRows, event);
            }
          }}
          filterModel={selectedDataView.configuration.filterModel}
          onFilterModelChange={handleFiltersChange}
          defaultGroupingExpansionDepth={-1}
          onRowGroupingModelChange={handleRowGroupingChange}
          loading={loading}
          disableVirtualization={disable?.virtualization ?? false}
          disableRowSelectionOnClick={checkboxSelection}
          sortModel={selectedDataView.configuration.sortModel as any}
          onSortModelChange={handleOnSortModelChange}
          onColumnOrderChange={handleColumnOrderChange}
          rowGroupingModel={selectedDataView.configuration.rowGroupingModel}
          pinnedColumns={selectedDataView.configuration.pinnedColumns}
          onPinnedColumnsChange={handleChangePinnedColumns}
        />
      </ThemeProvider>
    </>
  );
};

```

**Comment by michelengelen** [comment]
Without a reproduction we cannot really help you in your specific usecase, sry.

I have no performance problems with my local instance (in dev mode) running 50_000 rows on 30 columns with pinned rows and columns. In order to help you optimize we need a reproduction.

As for the cell renders: there are a few ways to customize them.
1. [using slotProps](https://mui.com/x/react-data-grid/components/#cell)
2. using [renderCell](https://mui.com/x/react-data-grid/faq/#rendercell)

**Comment by igortas** [comment]
@michelengelen 
I'm get slite better performance, i will try to use slotProps for mouse hover as last thing for conditional rendering. 
```renderCell``` I'm using that prop in very rare ocasions, but in those instances I have very small sets of data, which for now is not problem.

I have question is component as part of the shared wrapper around the x grid also very problematic that force the x grid to rerender?

I have code like this (I have this toolbar on top, in some instances I have the same type of toolbar, so I'm reusing it just providing some basic props)....
Sonarcube, gives me this error: ```Move this component definition out of the parent component and pass data as props.```
I'm not sure really how to put the toolbar outside of the x grid wrapper, because I have some dependencies from the props, but even I will extract it outside, is there some performance gain?

```
		toolbar: () => (
Move this component definition out of the parent component and pass data as props.

				<MuiTableToolbar
					hideEmptyValuesSwitch={hide?.emptyValuesSwitch ?? false}
					hideToolbar={hide?.toolbar ?? false}
					selectedRows={selectedRows}
					deleteToolbarAction={deleteToolbarAction}
					getRowId={getRowIdCallback}
				/>

                               <MuiTable ... />
```

**Comment by michelengelen** [comment]
> @michelengelen I've started getting slite better performance (but still on localhost is laggish, but I've managed to fix some other instances), i will try to use slotProps for mouse hover as last thing for conditional rendering. `renderCell` I'm using that prop in very rare ocasions, but in those instances I have very small sets of data, which for now is not problem.

That's good to hear. 👍🏼 

> I have a question about the snippet below. Sonarcube, complains about the toolbar and gives me this error: `Move this component definition out of the parent component and pass data as props.` I'm not sure really how to put the toolbar outside of the x grid wrapper, because I have some dependencies from the props from the shared wrapper, but even I will extract it outside, is there really some performance gain, as sonarcube is complaining?

Snippets won't do the trick. We need the full (stripped down) and working code in a sandbox to debug. Otherwise we are not able to help very effectively.
 
> Also one more question, what is so specific about the examples from the docs and how the data is prepared so the examples are blazing fast? I know in real scenario u have some other components on top of mui x grid, but if per docs stable references and memoization is the key to prevent rerenders and that is done, how than the scroll is lagging, which is happening inside the x grid? What is the first thing to look for slow scrolling?

The first things to look for are expensive components and functions, if everything is memoized correctly and there are no frequent state updates re-rendering the whole component tree. 

Be assured that we did not do any specific adjustments to the docs examples, we just follow the best practices. The scroll lag you experience has to come from your specific implementation. Sry!

**Comment by igortas** [comment]
@michelengelen I've improved the performance too on localhost. Def sticky columns were the one lagish, but the problem was that I was using ```getActions``` for ```pinned``` columns. When ```pinned``` columns are part of the ```rows``` scrolling is smooth. I think I can still improve the components that are used as ```pinned``` columns, but this performance is waaay better.
