### ISSUE TITLE
[data grid] How to programmatically expand rows

### ISSUE THREAD

**Issue by shoxter** [mui/mui-x#15518]
### The problem in depth

There is currently an example for master detail that shows how to expand/collapse all in a custom header component ([here](https://mui.com/x/react-data-grid/row-recipes/#expand-or-collapse-all-detail-panels)). I want to do the same but for row groupings (expand/collapse all the groupings) but I can't find any selectors that would allow for this or any functions in the API itself as all of the expansion state functions are concerned with master/detail from what I can tell. How can I achieve what I'm looking to do?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: row grouping selector api
**Order ID**: 96266

**Comment by michelengelen** [comment]
You can use the [`setRowChildrenExpansion`](https://mui.com/x/react-data-grid/row-grouping/#group-expansion) on the apiRef for that.

**Comment by shoxter** [comment]
> You can use the [`setRowChildrenExpansion`](https://mui.com/x/react-data-grid/row-grouping/#group-expansion) on the apiRef for that.

For clarity, I think what I was looking for is something similar to the behavior of the recipe for the master/detail expand/collapse all. That being, a way to know what rows are currently collapsed/expanded so I know what type of button I need to display (collapse all vs expand all).

**Comment by michelengelen** [comment]
you can get the current grouping rows with this:
```tsx
// on the root level
const groups = apiRef.current.getRowNode<GridGroupNode>(GRID_ROOT_GROUP_ID)!.children;
```
if you want deeper levels you would need to run this for the respective parent rows.

With this you get the groupIds (rowIds from the grouping rows), with which you can check the current expansion state:
```tsx
const areSomeRowsExpanded = groups.some((groupId) => apiRef.current.getRowNode<GridGroupNode>(groupId)!.childrenExpanded);
```

**Comment by shoxter** [comment]
One issue, my render header component (screenshot below) is still showing that the `.some` is returning children even though every row is collapsed. Why would this be?

![image](https://github.com/user-attachments/assets/6cff5145-995f-49a3-a676-bde101a8f7c7)
![image](https://github.com/user-attachments/assets/fbdad058-b0ef-4542-b2da-354180de583f)
