### ISSUE TITLE
[tree view] Dragging out all child nodes leaves the parent with expanded/collapsed indicator

### ISSUE THREAD

**Issue by arminmeh** [mui/mui-x#15527]
### Steps to reproduce

Steps:
1. Open [Enable drag & drop re-ordering](https://mui.com/x/react-tree-view/rich-tree-view/ordering/#enable-drag-amp-drop-re-ordering)
2. Drag one parent's children out of that parent

### Current behavior

Expanded/Collapsed indicator stays with the former parent even when it becomes a regular item

### Expected behavior

Expanded/Collapsed indicator should be removed once there are no children left

**Search keywords**: tree-view, drag-and-drop, ordering

**Comment by flaviendelangle** [comment]
Thanks for the bug report :pray: 
It seems to work fine after #14210 ([doc preview](https://deploy-preview-14210--material-ui-x.netlify.app/x/react-tree-view/rich-tree-view/ordering/)) which will be released this week.
