### ISSUE TITLE
[tree view] `groupTransition` slot prop doesn't accept transition props

### ISSUE THREAD

**Issue by cemreyavuz** [mui/mui-x#15526]
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/sharp-river-xl9n2k
2. Open `Demo.tsx` file
3. Check L20-23

### Current behavior

I cannot use transition props like `enter` and `exit` as part of `slotProps.groupTransition` for `TreeView` or `TreeItem`.

For `TreeItem`, it's typed as `groupTransition?: SlotComponentProps<'div', {}, {}>;`:
https://github.com/mui/mui-x/blob/6e21fb6e34dbf60f01c24b089c4e2d4c19758647/packages/x-tree-view/src/TreeItem/TreeItem.types.ts#L56

It probably should be sth like `groupTransition?: SlotComponentPropsFromProps<TransitionProps, {}, {}>;` (at least this was working fine in older versions).

### Expected behavior

I expect to use transition props like `enter` and `exit` as part of `slotProps.groupTransition`.

### Your environment

```
"dependencies": {
    "@emotion/react": "latest",
    "@emotion/styled": "latest",
    "@mui/material": "latest",
    "@mui/x-tree-view": "8.0.0-alpha.0",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "react": "latest",
    "react-dom": "latest",
    "typescript": "latest"
  },
```

**Search keywords**: TreeView, TreeItem, groupTransition

**Comment by michelengelen** [comment]
Hey @cemreyavuz 
Thanks for opening this issue. I'll leave this one to @flaviendelangle as he is the master of types on the tree view components! 🥷
