### ISSUE TITLE
[data grid] Insufficient top padding in toolbarContainer Component When Displaying Filter Badge

### ISSUE THREAD

**Issue by michGreg** [mui/mui-x#15550]
### Steps to reproduce

Steps:
1. Open this link to live example: https://mui.com/x/react-data-grid/filtering/
2. Set any filter

![image](https://github.com/user-attachments/assets/79c82ee6-b450-4079-9b6a-c486655a7abf)

### Expected behavior

Display the entire badge component in the default setting

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid, toolbarContainer, toolbar, filter, badge

**Comment by michelengelen** [comment]
@KenanYusuf aren't you currently working on a toolbar rebrush?

For a workaround you can use this:
```tsx
slotProps={{ baseBadge: { overlap: 'circular' } }}
```

**Comment by KenanYusuf** [comment]
Yes, this won't be a problem with the redesigned toolbar. I've created a PR #15556 which will allow you to override the props for the filter badge in the meantime.
