### ISSUE TITLE
[TreeView] Text input inside TreeItem loses focus

### ISSUE THREAD

**Issue by bryanwalthall** [mui/mui-x#15600]
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/kzfc33
2. Type "Hello World" in input - yields no space between words
3. Type "tree" in input - input loses focus

### Current behavior

When typing "Hello World" the space is missing.
When typing "tree" (lowercase is required) the input loses focus and the next tree item gains focus. The input is blank.

### Expected behavior

Focus should stay on the input when changing the value. The final input value should be exactly what the user typed.

### Context

Suspect handler: [useTreeViewKeyboardNavigation -> handleItemKeyDown](https://github.com/mui/mui-x/blob/master/packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts#L106)

Suspect original PR: #11452

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Linux 6.1 Ubuntu 20.04.6 LTS (Focal Fossa)
  Binaries:
    Node: 20.12.1 - /home/codespace/nvm/current/bin/node
    npm: 10.5.0 - /home/codespace/nvm/current/bin/npm
    pnpm: 8.15.6 - /home/codespace/nvm/current/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react:  11.13.5 
    @emotion/styled:  11.13.5 
    @mui/core-downloads-tracker:  6.1.8 
    @mui/icons-material: 6.1.8 => 6.1.8 
    @mui/material: 6.1.8 => 6.1.8 
    @mui/private-theming:  6.1.8 
    @mui/styled-engine:  6.1.8 
    @mui/system:  6.1.8 
    @mui/types:  7.2.19 
    @mui/utils:  6.1.8 
    @mui/x-internals:  7.21.0 
    @mui/x-tree-view: 7.22.1 => 7.22.1 
    @types/react: 18.3.12 => 18.3.12 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1
```
</details>

**Search keywords**: tree view treeitem focus input textfield keyboard navigation

**Comment by michelengelen** [comment]
Hey @bryanwalthall ... from your screenshot there is no hierarchy visible ... Just a suggestion that maybe make your life easier: Would [an accordion](https://mui.com/material-ui/react-accordion/) be a good solution for your use case?

**Comment by michelengelen** [comment]
> Do you anticipate more features like this to be added to the TreeView components? Or would it be more future-proof to use customized Accordion components instead? Thanks for the input!

Reminder to myself: Always read to the bottom of each comment! 🤦🏼

**Comment by bryanwalthall** [comment]
That answers my question then haha. It seems that my "bug" reported is actually due to using TreeView outside of its intended use case. I'll go ahead and close this issue.
