### ISSUE TITLE
[pickers] Theme augmentation for DatePicker missing styleOverrides

### ISSUE THREAD

**Issue by markedwards** [mui/mui-x#15654]
### Steps to reproduce

Steps:
1. Follow steps here: https://mui.com/x/react-date-pickers/base-concepts/#typescript
2. Remove `x-date-pickers-pro`

### Current behavior

TypeScript raises an error and the style overrides do nothing.

<img width="1276" alt="Screenshot 2024-11-28 at 13 40 52" src="https://github.com/user-attachments/assets/365adb92-76be-4239-8e05-e56b423705b6">

### Expected behavior

Theme augmentation should work.  Is this restricted to the pro component for some reason?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.18.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react:  11.13.3 
    @emotion/styled:  11.13.0 
    @mui/core-downloads-tracker:  6.1.6 
    @mui/icons-material:  6.1.6 
    @mui/material:  6.1.6 
    @mui/material-nextjs:  6.1.6 
    @mui/private-theming:  6.1.6 
    @mui/styled-engine:  6.1.6 
    @mui/system:  6.1.6 
    @mui/types:  7.2.19 
    @mui/utils:  6.1.6 
    @mui/x-date-pickers:  7.22.2 
    @mui/x-internals:  7.21.0 
    @types/react:  18.3.12 
    react:  18.3.1 
    react-dom:  18.3.1 
    typescript:  5.6.3 
```
</details>

**Search keywords**: augmentation

**Comment by michelengelen** [comment]
Strange ... it works for me.
Where did you see this? During build time (`tsc`) or in your IDE through IntelliSense?

<img width="604" alt="Screenshot 2024-11-29 at 09 04 41" src="https://github.com/user-attachments/assets/48645566-108b-4ddd-b44e-1507037a03ff">

**Comment by markedwards** [comment]
Both, and the style is not overridden at runtime.

Will see if I can create a minimal reproduction.

**Comment by markedwards** [comment]
The `styleOverrides` does not exist here: https://www.npmjs.com/package/@mui/x-date-pickers?activeTab=code

TypeScript is looking at that file for the `MuiDatePicker` type.

**Comment by LukasTy** [comment]
> I'm following exactly what is in this documentation though: https://mui.com/x/react-date-pickers/base-concepts/#typescript
> 
> So is that documentation wrong?

Sorry for not spotting this inconsistency before. 🙈 
Yes, that piece of information in the documentation is outdated.
Such a snippet should have never done anything in any version of the package.

We will address this error. 👌

**Comment by markedwards** [comment]
I see now, makes sense.  We want to actually do overrides that are specific to the `TextField` only for the `DatePicker`, so not global to `TextField`.  So I guess we cannot do this in the theme, but only in a custom component.

**Comment by LukasTy** [comment]
> We want to actually do overrides that are specific to the `TextField` only for the `DatePicker`, so not global to `TextField`. So I guess we cannot do this in the theme, but only in a custom component.

Are you using the new [accessible DOM structure](https://mui.com/x/react-date-pickers/fields/#accessible-dom-structure) by any chance?
If yes, you could use the new `PickersTextField` entry: https://github.com/mui/mui-x/blob/72926cb030bbe8c2cfb56b3a5c95fe96c9291f1f/packages/x-date-pickers/src/themeAugmentation/components.d.ts#L171-L175

Otherwise, you can create a nested theme wrapping only Picker components, but that might not be as elegant.
Or go for `sx` prop or creating a `TextField` wrapped in `styled` as shown in this video:

https://github.com/user-attachments/assets/f8a8cacd-e96e-49a6-9077-08f0efaa2b25

**Comment by markedwards** [comment]
Yeah I think for our case we'll just do the overrides in a wrapper component.  Thanks for the info though!
