### ISSUE TITLE
[data grid] Make value and colDef accessible in actions column

### ISSUE THREAD

**Issue by aress31** [mui/mui-x#15667]
### Summary

The params in `getActions` are only `row`, `id` and and `columns`; there is no information about the currently processed column or value which is quite restrictive when using type mappings. Addin them would improve DX and remove boilerplate code.

### Examples

```js
const getTypeMappings = (field) => ({
  // --- SNIP ---
  bytea: {
    headerName: undefined,
    type: "actions",
    getActions: ({ row }) => {
      const dataUrl = hexStringToDataUrl(row[field]);
      return [
        <GridActionsCellItem
          onClick={() => downloadFile(dataUrl)}
          icon={<Download />}
          label="Download"
          disabled={!dataUrl}
        />,
      ];
    },
  },
  // --- SNIP ---
});
```

Note: Also, transformations within `valueGetter` don't seem accessible to `getActions` too.

### Motivation

Improve the DX and provide contextual info to `getActions`.

**Search keywords**: actions

**Comment by michelengelen** [comment]
Hey @aress31 ... why would you need a value or valueGetter in getActions? The actions col is a special column which purpose is simply to render a series of buttons that perform actions on the row in question. That's exactly why we pass the row as a property to it.

Could you explain your specific use case please?

**Comment by michelengelen** [comment]
> @michelengelen simply because my action column need contextual information such as the current value/column name to process the action logic. See the code snippet in my opening message.

I got that ... but how do you determine "current column"? Is it the selected one? Is it all of them? Without knowing this its hard to tell what you are trying to achieve.

You can always use the selectionModel to get the currently selected cell/row to process that. 🤷🏼

**Comment by aress31** [comment]
@michelengelen I would just expect the `getAction` column to have access to the same prop than when calling `renderCell`, I would also expect the `valueGetter` transformation to also transform the value in the `getAction`.

**Comment by michelengelen** [comment]
But the actions column does not have any value that could be transformed by a `valueGetter` ... and why would it receive the same parameters as within the `renderCell` method? It's different by definition. There is a `renderCell` method present for the actions column as well.

If you really need the value form another column within the getActions you can use the `apiRef` to look for it. Again, if you want us to help you please explain the use case you have in more detail. There is a way to do that, but in order for us to come up with something we need to know! 🙇🏼
