### ISSUE TITLE
[pickers][DatePicker] End icon on Custom Text Field after mui v6 adoption doesn't appear on the DatePicker 

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#15663]
### Steps to reproduce

Steps:
1. Open this link to live example: ([required](https://stackblitz.com/edit/react-36hrf8?file=DatePicker.tsx,RenderInput.tsx,common.ts,commonInterfaces.ts,Demo.tsx))

2. Try to see the the endAdorment being passed to slotProps and input and endAdorment as per new changes mentioned in the migration v6 page of mui/material it doesn't pass the icons

3. When the icon is passed to InputProps interface it works but my build fails for the deprecation warning

### Expected behavior

End Icon should work according to the changes mentioned on the MUI v6 migration page.

### Context

Trying to adopt MUI V6

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DatePicker

**Comment by michelengelen** [comment]
To change the icon for the DatePicker you can just use `slots.openPickerIcon` like this:
```tsx
<DatePicker
  label="Basic date picker"
  slots={{
    openPickerIcon: DateRangeIcon,
  }}
  slotProps={{
    openPickerButton: {
      onClick: () => setOpen(true),
    },
  }}
/>
```

**Comment by noobDev31** [comment]
thanks @michelengelen works , do you think there are slots for Date Time Range Picker and Date Range Picker as well?

**Comment by michelengelen** [comment]
> thanks @michelengelen works , do you think there are slots for Date Time Range Picker and Date Range Picker for the endIcon as well?

[DateTimePicker](https://mui.com/x/api/date-pickers/desktop-date-time-picker/#DesktopDateTimePicker-css-openPickerIcon) and [DatePicker](https://mui.com/x/api/date-pickers/date-picker/#DatePicker-css-openPickerIcon) 👍🏼 

Just search for 'openPickerIcon' in the docs

**Comment by LukasTy** [comment]
> do you think there are slots for Date Time Range Picker and Date Range Picker for the endIcon as well?

For now, range pickers do not have an open icon, because their opening behavior is different.
We plan to change this behavior on v8.
In the meantime, you can [mimic an icon](https://mui.com/x/react-date-pickers/custom-field/#use-single-input-fields-on-range-pickers) if you need to.

**Comment by noobDev31** [comment]
> mimic an icon

![image](https://github.com/user-attachments/assets/e859806e-c036-4b3b-9172-045ef6a9337f)
look I am able to show the icon with **InputProps: { endAdorment }** but I get the above build failure.

**Comment by noobDev31** [comment]
> > look I am able to show the icon with **InputProps: { endAdorment }** for the **Date Time Range Picker** and **Date Range Picker** but I get the above build failure.
> > **slotProps: {input: {endAdorment }}** doesn't work for my custom TextField.
> > So do you think I have a way out from this
> 
> Until we solve #14284 I can only offer to ignore/disable this deprecation. 🙈

That'll be great because it was working for me and it's now a regression for us.

**Comment by LukasTy** [comment]
> because it was working for me and it's now a regression for us.

Could you clarify what was working before and is no longer now?
Do you mean that such usage was not throwing a deprecation warning before upgrading to `@mui/material` v6?
If that is the case, I wouldn't call it a regression. 🤔

**Comment by LukasTy** [comment]
Thank you for clarifying. 🙏 
Yes, the scenario you described refers to the problem mentioned in https://github.com/mui/mui-x/issues/14284.
`@mui/material` changed the API and deprecated the previous one, but we currently only support the old API in our code.
