### ISSUE TITLE
[data grid] How to get filters value using apiRef?

### ISSUE THREAD

**Issue by achoud444** [mui/mui-x#15696]
### Steps to reproduce

Steps:
1. Open this link to live example: (required)
2.
3.

### Current behavior

I am using the premium version of DataGrid and have a header filter with a Select component that allows multiple values. You can find the implementation here: [link](https://codesandbox.io/p/sandbox/stupefied-sound-d5nr99?from-embed=).

Currently, I am storing the selected values in the state, but the issue is that I have to include this state in the useMemo dependency array, which causes unnecessary re-renders of the component and the useMemo hook.

Is there a way to directly use apiRef to retrieve the selected filter values? I am already using apiRef.current.setFilterModel to apply the filter, so I would like something similar to apiRef.current.getFilterModel to access the current selected values without triggering re-renders.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: How to get filters value using apiRef?

**Comment by michelengelen** [comment]
Hey @achoud444 ... there is no live example to view for us, just a sandbox of a docs demo.

Could you implement what you want to achieve in a minimal way so we can have a look?

Also the problem you are describing is covered in the docs. Just use the [controlled filterModel](https://mui.com/x/react-data-grid/filtering/#controlled-filters).
