### ISSUE TITLE
[charts] Support for patterns in coloring `PieChart`

### ISSUE THREAD

**Issue by ZaidLinkEZ** [mui/mui-x#15706]
### The problem in depth

I wanted to know if the color palettes and colors that are supported in charts support patterns, for example the usage of lines that work as a pattern inside a pie chart.

![chart](https://github.com/user-attachments/assets/19d2339b-3421-4b0a-bd5e-8bcb90b212cf)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: PieChart, Charts, Colors
**Order ID**: 95670

**Comment by michelengelen** [comment]
Hey @ZaidLinkEZ ... I don't think that this is possible at the moment, but it would be a great addition to the feature set. @JCQuintas how hard would it be to allow the `fill` to accept a predefined `<pattern>...</pattern>` element?

**Comment by JCQuintas** [comment]
Patterns currently don't work on the `PieChart` only, because we use `style={{fill: "${color}"}}` which overrides any changes.

For the other chart types you can simply follow the [gradient example](https://mui.com/x/react-charts/lines/#css) and use a pattern instead of gradient.

As seen here:
https://stackblitz.com/edit/react-4k6xke?file=Demo.tsx

**Comment by ZaidLinkEZ** [comment]
> Patterns currently don't work on the `PieChart` only, because we use `style={{fill: "${color}"}}` which overrides any changes.
> 
> For the other chart types you can simply follow the [gradient example](https://mui.com/x/react-charts/lines/#css) and use a pattern instead of gradient.
> 
> As seen here: https://stackblitz.com/edit/react-4k6xke?file=Demo.tsx

Okay, thanks! I'll look it up.
