### ISSUE TITLE
[data grid] Type error Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by 93carlosmesa** [mui/mui-x#15716]
### Steps to reproduce

Steps:
1. i'm not sure
2.
3.

### Current behavior

i don't know.

### Expected behavior

I understand that a undefined arrives, and you should control it in ‘nextRow’.

### Context

We are using an error handler called Sentry, and it has indicated that you have an error in ./node_modules/@mui/x-data-grid/hooks/features/focus/useGridFocus.js in handleRowSet at line 338:29.
<img width="837" alt="Screenshot 2024-12-03 at 15 29 48" src="https://github.com/user-attachments/assets/75206a3b-d694-48e9-8caf-4dafff823168">

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
System:
    OS: macOS 14.6.1
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.70
    Safari: 17.6
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/base: ^5.0.0-beta.40 => 5.0.0-dev.20240529-082515-213b5e33ab 
    @mui/core-downloads-tracker:  5.16.6 
    @mui/icons-material: ^5.16.6 => 5.16.6 
    @mui/lab: ^5.0.0-alpha.173 => 5.0.0-alpha.173 
    @mui/material: ^5.16.6 => 5.16.6 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/styled-engine-sc: ^6.0.0-alpha.18 => 6.0.0-dev.20240529-082515-213b5e33ab 
    @mui/styles: ^5.16.6 => 5.16.6 
    @mui/system: ^5.16.6 => 5.16.6 
    @mui/types:  7.2.15 
    @mui/utils:  6.1.4 
    @mui/x-data-grid:  7.23.0 
    @mui/x-data-grid-generator: ^7.23.0 => 7.23.0 
    @mui/x-data-grid-premium: ^7.23.0 => 7.23.0 
    @mui/x-data-grid-pro: ^7.23.0 => 7.23.0 
    @mui/x-date-pickers: ^7.23.0 => 7.23.0 
    @mui/x-internals:  7.23.0 
    @mui/x-license:  7.23.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.3.3 => 18.3.3 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
    styled-components: ^6.1.12 => 6.1.12 
    typescript: ^5.6.3 => 5.6.3 
</details>

**Search keywords**: Type error undefined nextRow
**Order ID**: #1061-3100

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by 93carlosmesa** [comment]
Hi, thanks for the reply, we will try to get more information as we have not detected the error in which case it appears, it has happened to a customer, and sentry has notified us where it comes from.

**Comment by arminmeh** [comment]
Hey @93carlosmesa 

This looks like [this issue](https://github.com/mui/mui-x/issues/15145)
Issue was fixed a while ago, but in your environment it is stated that you are using latest data-grid package.
Can you confirm if that is also the case on the customer's environment?
