### ISSUE TITLE
[docs] Which license key should I use in a build pipeline ?

### ISSUE THREAD

**Issue by tedwelles-mitratech** [mui/mui-x#15713]
### Related page

https://mui.com/x/introduction/licensing/

### Kind of issue

Unclear explanations

### Issue description

After reading the license documentation, I am still not clear about one thing. To be fair it may just be me misunderstanding the documentation.

I understand that if in my team there are N frontend / full-stack developers loading MUI commercial components in developer mode then I must purchase N licenses. That's all fine.
But what about the license that is injected at build time by a pipeline agent ?
Am I supposed to purchase 1 additional license, 1 additional license per build agent, or no additional license (and re-use one of those allocated to the developers) ? 

### Context

I am trying to figure out if I need to purchase extra licenses for pipeline agents.

**Search keywords**: license pipeline

**Comment by michelengelen** [comment]
Hey @tedwelles-mitratech you can just use the license you got provided with in your build pipeline.

@samuelsycamore we could probably do a bit better on the [licensing page](https://mui.com/x/introduction/licensing/) for this case. Would you mind taking a look?

**Comment by tedwelles-mitratech** [comment]
Awesome thank you for getting back to me.
Not sure what's the process here, do you want me to close the issue or are you now using it to track future potential documentation update ?

**Comment by michelengelen** [comment]
I'll close it! thanks! 👍🏼
