### ISSUE TITLE
[data grid] How to update state update when using apiRef

### ISSUE THREAD

**Issue by entaildevops** [mui/mui-x#15730]
### The problem in depth

The [docs](https://mui.com/x/react-data-grid/row-updates/) suggest that the apiRef.current.updateRows() should be used when updating row data. But it looks like doing it only updates the internal state of the DataGrid - and not the rows in state. This leads to all sorts of problems when the rows collection is not in sync with the internal state of DataGrid. 

I am using treedata and I do want to avoid collapsing the expanded state of the rows whenever their data changes. 

Codesandbox to illustrate the issue: https://codesandbox.io/p/sandbox/alert-weirdness-5zvf64

The first button uses apiref which updates the internal state of datagrid and does not collapse the grid, but does not update the rows collection in state. The second button uses setRows() directly, but it causes DataGrid to collapse - which leads to really bad UX. 

So what is the correct way to update the rows when I want to a) NOT collapse the expanded state b) also update the rows in state

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: treedata apiref
**Order ID**: 98745

**Comment by michelengelen** [comment]
Well, the easy solution is to store the updatedRows in a state that's not being passed to the grid.

```tsx
export default function MyGrid() {
  const [rows, setRows] = useState<Person[]>(initialRows);
  const apiRef = useGridApiRef();

  const handleClick1 = () => {
    const updatedRows = rows.map((row) => (row.id === 1 ? { ...row, age: row.age + 1 } : row));

    apiRef.current.updateRows(updatedRows); //does not collapse datagrid, but does not update state
    setRows(updatedRows); //updates state, but causes datagrid to collapse
  };

  console.log('rows', rows);

  return (
    <Stack>
      <DataGridPro
        apiRef={apiRef}
        treeData
        rows={initialRows}
        columns={columns}
        getTreeDataPath={getTreeDataPath}
      />
      <Button onClick={handleClick1}>Update using apiref</Button>
    </Stack>
  );
}
```

The question though: why would you need a separate state for the rows?

**Comment by entaildevops** [comment]
@michelengelen Thanks for the swift reply. Ah, I somehow thought that you are supposed to have the rows that are passed in the rows prop of the DataGrid in the react state. Most examples seem to do so. So is it so that when using apiRef.current to update/delete rows, you are NOT supposed to have rows in state and only pass the **initial** rows to DataGrid. 

If so, the how does DataGrid handle the rows={initialRows} prop on consecutive renders of the component? Does it ignore the prop or something?

> The question though: why would you need a separate state for the rows?

Well, it looks like it is needed in this example. I need to access the current rows (to get the age prop of the row with id=1). How would one achieve this without having rows in the state?
