### ISSUE TITLE
[question][data grid]  Maximum update depth

### ISSUE THREAD

**Issue by suhanahussainn** [mui/mui-x#15761]
### The problem in depth

  
<img width="884" alt="image" src="https://github.com/user-attachments/assets/1f120ee9-38da-4c52-9f34-a3caee710dd8">

```
const CustomFilterPanel = () => {
    return (
      <Box>
        <GridFilterPanel />
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            padding: "8px",
          }}
        >
          <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
            {/* Custom Button */}
            <Button variant="contained"
              sx={{
                backgroundColor: "#216c98",
                color: "#fff",
              }}
            >APPLY
            </Button
>
             </Box>
        </Box>
      </Box
    );
  };
<DataGridPremium
rows={isloading ? [] : rows}
 columns={columns}
 rowHeight={35}
columnHeaderHeight={40}
apiRef={apiRef}
onStateChange={saveSnapshot}
 loading={false}
initialState={{ ...initialState, }}
slots={{ columnMenu: CustomColumnMenu,
                      footer: CustomFooter,
                      filterPanel: CustomFilterPanel, }}
pagination
 paginationMode={paginationModes}
paginationModel={paginationModel}
onPaginationModelChange={setPaginationModel}
 rowCount={rowCountData}
 pageSizeOptions={[25, 100, 150, 200, 250, 300]}
filterMode="server"
onFilterModelChange={isloading ? undefined : onFilterChange} // Disable filter changes
disableAggregation={true}
columnVisibilityModel={columnVisibilityModel}
onColumnVisibilityModelChange={
isloading ? undefined : handleColumnVisibilityChange
 } 
 />
```
                 
                 
   when i am trying to implement the Custom Filter Panel then i am getting this error Maximum update depth exceeded.
   
   
   kindly provide me solution for this
   
                  
                  
                  
                  

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: filter panel
**Order ID**: 98327

**Comment by alexfauquette** [comment]
Could it be because you define your `CustomFilterPanel` inside another component?

You can check this docs page for common errors: https://mui.com/x/common-concepts/custom-components/#correct-usage

If it does not help, providing a minimal reproduction in codesandbox or stackblitz would help the team to provide better support

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by suhanahussainn** [comment]
![image](https://github.com/user-attachments/assets/a9b91d45-53b6-4c91-8987-96ee59d1a5b7)
I attempted to replicate the same issue in the sandbox, but I was unable to reproduce it. However, I would like to add a button inside the filter panel, similar to the one shown in the image provided above. Could you please provide me a alternative solution for this
