### ISSUE TITLE
[data grid] Examples in docs result in react error in code sandbox

### ISSUE THREAD

**Issue by M-sleeper** [mui/mui-x#15765]
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/embed/y7jsy6?module=/src/Demo.tsx&fontsize=12

or
1.  go to https://mui.com/x/react-data-grid/row-grouping/ 
2. Click to edit in code sandbox in the first example

### Current behavior

there's an error: "Rendered fewer hooks than expected. This may be caused by an accidental early return statement."

### Expected behavior

example works as in the docs

### Context

Not tested too many examples, but it seems to be that quite a lot of examples are broken. Maybe an issue with the latest release?

**Search keywords**: react docs code sandbox
**Order ID**: 101072

**Comment by arminmeh** [comment]
Thanks for reporting @M-sleeper 

We will check this out.

In the meantime, as a workaround you can either use StackBlitz or you can make any change in the `Demo.tsx` file. This will trigger a reload which will render the grid without the error.

**Comment by arminmeh** [comment]
An issue has been opened [upstream](https://github.com/codesandbox/codesandbox-client/issues/8673)
