### ISSUE TITLE
[data grid] React 19 - everything that depends on `GridRootPropsContext` re-renders on every state change (or root re-render) if the ref prop is present

### ISSUE THREAD

**Issue by lauri865** [mui/mui-x#15770]
### Search keywords

N/A

### Latest version

- [X] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Steps:
1. Generic – https://github.com/facebook/react/issues/31613
2. Datagrid specific – https://github.com/mui/mui-x/pull/15549#issuecomment-2493523350

### Current behavior

Read more about on the links above.

Found in the midst of another PR, so opening an issue so it doesn't go overlooked, especially now that there's official React 19 support and React 19 is stable. 

Worth noting that it can also affect instances where developers don't actually provide a ref, but have created an abstracted component over the Datagrid which passes forward the ref prop by explicitly naming it as `ref={ref}` even if `ref={undefined}`. This was the case for us. Which means that the potential share of users affected is much wider.

Not sure if the problem affects any other areas of the DataGrid as well, but probably not as critical as this.

cc @arminmeh, since you worked on the React 19 support

**Comment by michelengelen** [comment]
Thanks for opening it @lauri865 ... you're adopting R19 pretty swiftly, very nice!

I'll forward it to the team and add it to the board! 👍🏼

**Comment by cherniavskii** [comment]
It looks like there's nothing we can do about it on our side until it's fixed in React 😕

**Comment by lauri865** [comment]
Alternatively, maybe something like that could work?
```typescript
const forwardRefBackwardsCompatible = <T, P>(
  render: React.ForwardRefRenderFunction<T, P>,
) => {
  if (React.version.startsWith("19")) {
    const Component = (props: any) => render(props, props.ref ?? null);
    return Component;
  }

  return React.forwardRef(render);
};
```

**Comment by dmytro-shchurov** [comment]
> And a reason why I wouldn't count on an upstream change is that the fix would likely mean breaking the below pattern:
I would call this an antipattern, cause this is quite naive to specify overrides prior to a spread operator. If such exists in mui code it must be refactored IMHO

**Comment by lauri865** [comment]
> > And a reason why I wouldn't count on an upstream change is that the fix would likely mean breaking the below pattern:
> 
> 
> 
> I would call this an antipattern, cause this is quite naive to specify overrides prior to a spread operator. If such exists in mui code it must be refactored IMHO
> 
> 

Well, prior to React 19 it wasn't an override, as props could never contain a ref. Now it is. Which is the core reason why this change exists in React. Agree that it should be removed in Mui if it exists going forward, but doesn't change anything for upstream and the issue remains so long as forwardRef is used within React 19.

**Comment by romgrk** [comment]
> Alternatively, maybe something like that could work?

I'm happy with that solution, and yes considering the facts it's likely React won't fix it, so we can go ahead with that.
