### ISSUE TITLE
[docs] Demo ResponsiveDateRangePickers crashes

### ISSUE THREAD

**Issue by samuelfound92** [mui/mui-x#15781]
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20ResponsiveDateRangePickers%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-date-pickers/date-range-picker/
2. ??
3. demo *ResponsiveDateRangePickers* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v7.23.1  |
| Netlify deploy | https://6751c6b3afd46f00088dcc5b--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 |

**Search keywords**:

**Comment by LukasTy** [comment]
Hello @samuelfound92, could you provide a more detailed explanation of how it crashes?
- Does it happen after doing some action?
- Could you provide a video of the crash happening?
- Does it happen after a hard reload (clearing the cache) or using private browsing mode?
