### ISSUE TITLE
Scatter chart shows nothing if dataset array haves objects do not contains all series points

### ISSUE THREAD

**Issue by masoud-keykha** [mui/mui-x#15801]
### Steps to reproduce

Steps:
1. Open this link to live example: (required)
2. https://codesandbox.io/embed/ct9yqx?module=/src/Demo.js&fontsize=12
3.

### Current behavior

Scatter chart shows nothing if dataset array haves objects do not contains all series points.
Scatter chart shows nothing if dataset array haves just one object

### Expected behavior

We expect scatter chart shows the points of series even there was not all of points in every objects. or even there was just on index inside dataset array

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: scatter chart dataset

**Search keywords**:

**Comment by alexfauquette** [comment]
Thanks for the nice reproduction.

The missing values were breaking the computation of the axes min/max. Then axes could not map data to coordinates
