### ISSUE TITLE
[docs] Document how DataGrid and DataGridPro are interdependent

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#1580]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

There are no documentations about how DataGrid relates to XGrid, API-wise.

## Examples 🌈

We have seen a couple of occurrences of this problem, from developers:

1. "Clicking through the XGrid API -- just wondering, is the "editable" property for cell editing specific to DataGrid, or can XGrid use this as well?"
2. "I didn’t realize the DataGrid docs applied to the XGrid component. That’s good to know!"

## Motivation 🔦

Clarity, clarity, clarity.

## Solutions 🧩

One possible solution is to add a `### DataGrid vs. XGrid` in https://material-ui.com/components/data-grid/#overview to explain how one has almost a superset of the API of the other.

**Comment by flaviendelangle** [comment]
In #3965 I am adding a "pro" icon on the properties only available on the pro plan 

![image](https://user-images.githubusercontent.com/3309670/154942730-7f1b3151-9e92-4b20-9b3f-2d0528227455.png)


The exact UI is open to discussion of course, the main goal was to improve the scripts to have the information necessary.
