### ISSUE TITLE
[data grid] Wrong position for Checkbox column after unpinning other column

### ISSUE THREAD

**Issue by dashasm** [mui/mui-x#15808]
### Issue Description

The issue arises when grouping is enabled, and at least one column is grouped. If another column is pinned to the left and then unpinned, the `Checkbox` column does not return to its original position. Instead, it is placed after the grouped column.

---

### Steps to Reproduce

1. Use the first example from the [documentation](https://mui.com/x/react-data-grid/row-grouping/) [codesandbox](https://codesandbox.io/embed/y7jsy6?module=/src/Demo.tsx&fontsize=12).  
2. Add the prop `checkboxSelection={true}` to the table.  
3. For a different column (not the grouped one), select **"Pin to left"** and then **"Unpin"**.

---

### Actual Behavior

The `Checkbox` column does not return to its original position but is placed after the grouped column.
<img width="1070" alt="Знімок екрана 2024-12-09 о 15 09 55" src="https://github.com/user-attachments/assets/072133e4-f33f-4bd6-9aa1-12e0c12375e1">

### Expected Behavior

The `Checkbox` column should remain located **before the grouped column** after unpinning.
<img width="1066" alt="Знімок екрана 2024-12-09 о 15 09 45" src="https://github.com/user-attachments/assets/aebe7701-2826-45a8-8632-bb81cda4a501">

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
"@mui/x-data-grid-premium": "^7.22.2",
```
</details>

**Search keywords**: DataGrid Pinned Columns Checkbox
**Order ID**: 82865

**Comment by michelengelen** [comment]
Confirmed the bug ... i could not find a quick solution to this.
Moving it to the board! 👍🏼
