### ISSUE TITLE
[data grid] rowSpanning makes group header disappear [#2]

### ISSUE THREAD

**Issue by vanyadymousky** [mui/mui-x#15819]
### Steps to reproduce

Steps:
1. Open this link to live example: [(required)](https://stackblitz.com/edit/react-kxed37-apfujuua?file=Demo.tsx,index.html)
On the example provided, press **UPDATE THE DATA** twice so second row is rendered while first is not

### Current behavior

**alias** field is not being rendered: empty

### Expected behavior

 **alias** field should render: rowSpanning should render **alias** value always even there's only one row of a kind. 

### Context

Related issue: https://github.com/mui/mui-x/issues/15261
Please don't close this one! The issue is obvious: alias column value not being rendered. 
Otherwise, if you exactly see how can this issue be resolved. Previous issue didn't help at all. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: macOS 15.1.1
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 131.0.6778.109
    Edge: Not Found
    Safari: 18.1.1
  npmPackages:
    @emotion/react: ^11.4.1 => 11.11.4 
    @emotion/styled: ^11.3.0 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.7 
    @mui/icons-material: ^5.0.1 => 5.15.20 
    @mui/lab: ^5.0.0-alpha.49 => 5.0.0-alpha.170 
    @mui/material: ^5.0.2 => 5.16.7 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.7 
    @mui/types:  7.2.17 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.23.1 
    @mui/x-data-grid-pro: ^7.6.2 => 7.23.1 
    @mui/x-date-pickers: ^7.6.2 => 7.7.0 
    @mui/x-internals:  7.23.0 
    @mui/x-license:  7.23.0 
    @types/react: ^18.0.25 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: 5.2.2 => 5.2.2 
```

Used: Chrome: 131.0.6778.109
</details>

**Search keywords**: rowSpanning
**Order ID**: 60827

**Comment by michelengelen** [comment]
Got you @vanyadymousky ... There seems to be a bug in the rowSpanning feature. This occurs when there is the same amount of rows updated, since the useCallback reference values are only shallow compared.

There may be a different cause as well, so no guarantee for precise investigation here.

I'll add it to the board!

cc @MBilalShafi

**Comment by MBilalShafi** [comment]
Thank you @vanyadymousky for providing a reproduction example.
I can reproduce the issue on it.
Will try to raise a fix soon.
