### ISSUE TITLE
[data grid]  Question about filter function

### ISSUE THREAD

**Issue by Yuki-Hiramatsu** [mui/mui-x#15827]
### The problem in depth

When using the filter function of MUI's DataGrid with a TextField placed inside a cell,
the filter function in the header does not work.
In case of bellow, I think “data6” is filtered because 6 is input in Value.
But “No results found” is shown.
Could you show me what measures I should take? 

![image](https://github.com/user-attachments/assets/ae74398a-a6f2-4d1a-9d98-3d1599dcd1bf)
![image](https://github.com/user-attachments/assets/d3508717-8891-4354-81bb-37f539dce758)

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>
<markdown-accessiblity-table data-catalyst=""><table role="table">
<thead>
<tr>
<th>OS</th>
<th>Linux(Debian12)</th>
</tr>
</thead>
<tbody>
<tr>
<td>development   language</td>
<td>Next.js(TypeScript)</td>
</tr>
<tr>
<td>x-data-grid-pro   Version</td>
<td>7.2.0</td>
</tr>
</tbody>
</table></markdown-accessiblity-table>
```

```
</details>

**Search keywords**: data grid, filter
**Order ID**: 86901

**Comment by cherniavskii** [comment]
Hi @Yuki-Hiramatsu 
Please provide a minimal reproduction example so we can take a look.
