### ISSUE TITLE
[data grid] Is it possible to unit test DataGrid's onRowsScrollEnd?

### ISSUE THREAD

**Issue by luisabtrace** [mui/mui-x#15825]
### The problem in depth

I'm trying to write a unit test to make sure that the `DataGrid` fetches more pages when scrolling down. Unfortunately, I haven't been able to do this so far. The `DataGrid` is working perfectly fine with `onRowsScrollEnd={() => { ... }}`, but I'd like to write a unit test for this, to guarantee it doesn't break in the future.

I'm using React Testing Library. I'm not sure it's related or not, but I had to mock `IntersectionObserver` because I run into this issue: https://github.com/mui/mui-x/issues/12983.

Is there any way to achieve this?

Thanks

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.7.1
  Binaries:
    Node: 20.18.1 - ~/.nvm/versions/node/v20.18.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.1/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 131.0.6778.109
    Edge: Not Found
    Safari: 18.1.1
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.6
    @mui/icons-material: ^5.16.5 => 5.16.6
    @mui/lab: ^5.0.0-alpha.173 => 5.0.0-alpha.173
    @mui/material: ^5.16.5 => 5.16.6
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system: ^5.16.5 => 5.16.6
    @mui/types:  7.2.15
    @mui/utils:  5.16.6
    @mui/x-data-grid:  7.23.1
    @mui/x-data-grid-pro: ^7.23.1 => 7.23.1
    @mui/x-date-pickers: ^7.11.1 => 7.12.0
    @mui/x-internals:  7.23.0
    @mui/x-license:  7.23.0
    @types/react: 18.3.3 => 18.3.3
    react: ^18.2.0 => 18.3.1
    react-dom: ^18.2.0 => 18.3.1
    typescript: 5.5.4 => 5.5.4
```
</details>

**Search keywords**: onRowsScrollEnd test
**Order ID**: 52434

**Comment by michelengelen** [comment]
@romgrk would you be able to help here?

**Comment by romgrk** [comment]
It sounds like you're trying to trigger the function in an environment that doesn't support standard browser capabilities. You need to be aware that jsdom (or HappyDOM) are not complete browser implementation, so you cannot get all the DataGrid features working in them. If you want proper testing, you should use a framework that uses an actual production-like environment (aka an headless browser) like karma or cypress.

**Comment by luisabtrace** [comment]
That's what I thought. Thanks.
