### ISSUE TITLE
[data grid] Enable pagination

### ISSUE THREAD

**Issue by Mikele98** [mui/mui-x#15831]
### The problem in depth

I was implementing the Pagination feature of DataGrid in my custom project, but it doesn't work with DataGridPremium. It works with base DataGrid (as shown in documentation), so I'm writing here since I cannot use premium plan on StackBlitz or similar to show you. If you have any heads up about this issue, please let me know asap.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGrid Premium, Pagination
**Order ID**: 93630

**Comment by michelengelen** [comment]
Did you enable pagination?
This needs to be opted-in for Pro and Premium data grids according to the docs: [Enabling pagination](https://mui.com/x/react-data-grid/pagination/#enabling-pagination)
