### ISSUE TITLE
[tree view] Treeview item grouping 

### ISSUE THREAD

**Issue by Matt-Butler** [mui/mui-x#15834]
### Summary

I would like the ability to have tree item grouping or tree item categories.

Thank you!

### Examples

I want to group tree items in a way similar to how items are grouped in select or autocomplete components. The group headers, unlike regular tree items, should remain non-expandable and non-selectable.

https://mui.com/material-ui/react-autocomplete/#grouped
https://mui.com/material-ui/react-select/#grouping

**Comment by michelengelen** [comment]
This should be doable already with a custom TreeItem. Did you check the [useTreeItem2](https://mui.com/x/react-tree-view/tree-item-customization/#usetreeitem2) hook for customization?
