### ISSUE TITLE
[data grid] type="number" column uses <input type="number"> even though it is deprecated

### ISSUE THREAD

**Issue by zdonner100** [mui/mui-x#15841]
### Steps to reproduce

Steps:
1. Open this link to live example: https://mui.com/x/react-data-grid/editing/#row-editing
2. Double click to edit "Age" column 
3. Input uses type='number' even though this is deprecated in mui's own docs
![image](https://github.com/user-attachments/assets/fff682ed-8c8a-4aa2-b7f2-377df86d16c6)

![image](https://github.com/user-attachments/assets/1b5bdc1c-0689-464c-b13c-a50aeedb545c)

### Current behavior

type="number" default column editor uses <input type="number">

### Expected behavior

number column default editor should use the recommended best practice of the baseui "Number Input" component.

### Context

Editing data grid number column

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.20.3 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD   
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (131.0.2903.70)
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base:  5.0.0-beta.60
    @mui/core-downloads-tracker:  5.16.7
    @mui/icons-material: ^5.16.5 => 5.16.7
    @mui/material: ^5.16.5 => 5.16.7
    @mui/material-nextjs: ^5.15.11 => 5.16.6
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.18
    @mui/utils:  5.16.6
    @mui/x-data-grid:  7.22.0
    @mui/x-data-grid-premium: ^7.7.1 => 7.22.0
    @mui/x-data-grid-pro:  7.22.0
    @mui/x-date-pickers: ^6.16.3 => 6.20.2
    @mui/x-internals:  7.21.0
    @mui/x-license: ^7.7.1 => 7.21.0
    @types/react: 18.3.3 => 18.3.3
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.0 => 18.3.1
    typescript: ^5.4.5 => 5.6.3
```
</details>

**Search keywords**: Number column datagrid

**Search keywords**:

**Comment by michelengelen** [comment]
Hey @zdonner100 ... it is true that we don't recommend using it, but ...
1. this is the best choice as it stands
2. we will adapt base UI number input once it is fully released.

Thanks anyways for opening an issue here and using our produccts!
I'll close this one as there is no action to take!
