### ISSUE TITLE
[data grid] We are encountering an issue with filtering in Data Grid Premium

### ISSUE THREAD

**Issue by JimmySVENSSON** [mui/mui-x#15844]
### The problem in depth

We are encountering an issue with filtering in Data Grid Premium.

**Context:**
Our setup includes a mix of hardcoded and dynamically generated columns.
We use the following code to allow filtering only with the ‘contains’ operator:
const filterOperators = getGridStringOperators().filter(
  (operator) => operator.value === 'contains'
);

**Problem:**

- When filtering on dynamically generated columns, the Data Grid does not display any rows, despite receiving the correct data from the backend.
- If I remove the filter, I briefly see the correct rows before the grid resets to its initial state.
- This issue does not occur with hardcoded columns; filtering works as expected there.

**Observations:**

- If I change the operator to 'doesNotContain', the filtering works perfectly even for dynamically generated columns.
- The backend request is identical for both operators (contains and doesNotContain).
- This behavior seems to point to a possible timing or synchronization issue.

**Questions:**

- Is there a known bug with filtering dynamically created columns?
- Could this issue be related to the timing of dynamically creating columns during an API call?
- As a workaround, using doesNotContain works for now. Is this a safe and supported approach?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>
```
this gives me 1000 rows of code and then error messege
  code: 2147749902,
  stdout: '',
  stderr: 'ERROR:\r\r\nDescription = Invalid namespace\r\r\n',
  failed: true,
  signal: null,
  cmd: 'wmic os get Caption',
  timedOut: false
  
  but im using:
		"@mui/x-data-grid-premium": "^7.23.1",
                "@emotion/react": "^11.14.0",
		"@emotion/styled": "^11.14.0",
		"@mui/icons-material": "^6.2.0",
		"@mui/material": "^6.2.0",
		"@mui/styles": "^6.1.1",
		"@mui/system": "^6.2.0",
		
  Windows 10 and windows 11
  Node.js v18.19.0
  
  we have tested in Chorme 131.0.6778.86  and in OperaGX
```
</details>

**Search keywords**: Data Grid premium, filtering, server-side
**Order ID**: 101282

**Comment by michelengelen** [comment]
To help us diagnose the issue efficiently, could you provide a **stripped-down** reproduction test case using the latest version? A live example would be fantastic! ✨ 

For your convenience, our documentation offers templates and guides on creating targeted examples: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions)

Just a friendly reminder: clean, functional code with minimal dependencies is most helpful. Complex code can make it tougher to pinpoint the exact issue.  Sometimes, simply going through the process of creating a minimal reproduction can even clarify the problem itself!

Thanks for your understanding! 🙇🏼

**Comment by JimmySVENSSON** [comment]
Codesandbox: https://codesandbox.io/p/sandbox/2j6gyl

Filtering works as expected for static columns like "Column1".
However, when attempting to filter on dynamically added columns (e.g., 'Question 1'), the filtering does not function correctly.
The dynamically added columns are generated based on data transformations, and their values are included in the rows array.

**Comment by JimmySVENSSON** [comment]
done :)

**Comment by michelengelen** [comment]
All right ... The problem with your example is that the filterOperator receives an object with the type `{ name: string; answers: { value: string }[] }`. This object cannot be used to filter and needs to be processed first.

You can do this in 2 ways:

1. use a [`valueGetter`](https://mui.com/x/react-data-grid/column-definition/#value-getter) to allow the data grid internals to get the value directly. In this case you would need to adjust your `renderCell` as well, as the value there is also received from the `valueGetter`
2. Provide a [custom filter operator](https://mui.com/x/react-data-grid/filtering/customization/#create-a-custom-operator). With this option you would not need to adjust the rendering and can just use it as is, but it is also pretty single use

**Comment by JimmySVENSSON** [comment]
The filter function is one part I can't recreate in a CodeSandbox, since, the project uses server-side filtering.

I have implemented a filter function that generates a URL for the API. The URL is correct, and the backend returns the expected results. However, I am encountering an issue with how the Data Grid renders the filtered rows.

When using the operator 'contains', the backend returns the correct results, but the Data Grid does not render any rows.
When using 'doesNotContain', the same URL is sent to the backend, and the backend returns the same correct results. This time, the Data Grid renders the rows as expected.
It seems like filtering is working correctly on the backend, but the Data Grid behaves differently depending on the operator used.

Questions:

Could this be a timing issue or related to how the grid processes state updates?
Is there an additional check or behavior in the background when using 'doesNotContain' compared to 'contains' that might explain this discrepancy?

Additional Context:

I cannot use valueGetter because I need to use renderCell to return custom HTML for the cells.

**Comment by michelengelen** [comment]
Can you maybe fake the filtering with a setTimeout in CSB?
The strange thing here is: the server returns a set of rows, but the grid does not show any of them. This is what we need to investigate here.

cc @MBilalShafi
