### ISSUE TITLE
PickersCalendarHeader slotProps not working for icons on DateCalander

### ISSUE THREAD

**Issue by xxKeefer** [mui/mui-x#15842]
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/upbeat-wozniak-446v7j?from-embed=&workspaceId=ws_MWFq6XXHYUmvGrte6LWBTo
2. Note that the slot props for the `calendarHeader` have not been applied to the icons

### Current behavior

it doesn't replace the icons of the calendar header

### Expected behavior

the icons should use what is provided in the slot props

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (129.0.2792.89)
  npmPackages:
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
```
</details>

**Search keywords**: PickersCalendarHeader slotProps not working for icons on DateCalander
**Order ID**: 89424

**Comment by michelengelen** [comment]
You should use the slots prop for that:

```tsx
<DateCalendar
  slots={{
    switchViewIcon: () => <span>X</span>,
    leftArrowIcon: () => <span>Y</span>,
    rightArrowIcon: () => <span>Z</span>,
  }}
/>
```

This works!
