### ISSUE TITLE
[data grid] Is it possible to update the grid package independently of @mui/x-data-pickers  and @mui/x-tree-view

### ISSUE THREAD

**Issue by theobrasseurbentley** [mui/mui-x#15852]
### The problem in depth

Given the following package.json: 

1. @mui/x-data-grid-premium": "^6.16.3"
2. @mui/x-tree-view": "^6.0.0-alpha.1
3. @mui/x-date-pickers": "^6.11.0"
4. @mui/x-license-pro": "^6.0.0-beta.3"

Wondering whether it's possible to update the grid to v7 separately.

### Your environment

 System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 22.4.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: 131.0.6778.139
    Edge: Chromium (131.0.2903.70)
  npmPackages:
    @emotion/react:  11.11.4
    @emotion/styled:  11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.16.4
    @mui/icons-material:  5.16.4
    @mui/material: ^5.10.15 => 5.10.15
    @mui/private-theming:  5.16.4
    @mui/styled-engine:  5.16.4
    @mui/system:  5.16.4
    @mui/types:  7.2.15
    @mui/utils: ^5.16.0 => 5.16.4
    @mui/x-data-grid:  6.16.3
    @mui/x-data-grid-premium: ^6.16.3 => 6.16.3
    @mui/x-data-grid-pro:  6.16.3
    @mui/x-date-pickers: ^6.11.0 => 6.20.2
    @mui/x-license-pro: ^6.0.0-beta.3 => 6.10.2
    @mui/x-tree-view: ^6.0.0-alpha.1 => 6.0.0-alpha.1
    @types/react: ^18.0.21 => 18.2.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^5.3.3 => 5.3.3

**Search keywords**: update grid package
**Order ID**: 95099

**Comment by flaviendelangle** [comment]
Hi,

It is possible to update them independently as long as you are not using a commercial package.
All the commercial packages relyu on `@mui/x-license` (or `@mui/x-license-pro` for older versions) which has a singleton (it can't be bundled several time with different versions).

I think it would be nice to work on removing this singleton, I think it's doable and it would help migrating incrementally.
