### ISSUE TITLE
[data grid] Using columnGroupHeaderHeight property causes toolbar panels to be misaligned with table header

### ISSUE THREAD

**Issue by mike-paretos** [mui/mui-x#15874]
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/optimistic-sea-xgtjg9
2. Try to open the toolbar menu like filters
3. Observe that it is misaligned when columnGroupHeaderHeight is provided

### Current behavior

The toolbar panels (filters, columns) are misaligned when tables with column grouping  are using columnGroupHeaderHeight property.

<img width="1108" alt="Screenshot 2024-12-13 at 15 41 20" src="https://github.com/user-attachments/assets/09ab773a-4da7-4eb0-a4f9-9dd91d754553" />

### Expected behavior

The toolbar panels (filters, columns) are aligned with table header.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: column grouping, columnGroupHeaderHeight

**Order ID**: 82474

**Comment by michelengelen** [comment]
> Seems like [getTotalHeaderHeight](https://github.com/mui/mui-x/blob/374b96db9006e70fd8c7b6a25a05e65901297020/packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts#L441) does not reflect columnGroupHeaderHeight in calculations at all.

Thanks for taking a look into this. You are indeed correct. The `columnGroupHeaderHeight` prop is not taken into account while calculating it.

This diff will fix it:

```diff
--- a/packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
+++ b/packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
@@ -442,7 +442,7 @@ export function getTotalHeaderHeight(
   apiRef: React.MutableRefObject<GridApiCommunity>,
   props: Pick<
     DataGridProcessedProps,
-    'columnHeaderHeight' | 'headerFilterHeight' | 'unstable_listView'
+    'columnHeaderHeight' | 'headerFilterHeight' | 'unstable_listView' | 'columnGroupHeaderHeight'
   >,
 ) {
   if (props.unstable_listView) {
@@ -454,9 +454,16 @@ export function getTotalHeaderHeight(
   const isHeaderFilteringEnabled = gridHeaderFilteringEnabledSelector(apiRef);

   const columnHeadersHeight = Math.floor(props.columnHeaderHeight * densityFactor);
+  const columnGroupHeadersHeight = Math.floor(
+    (props.columnGroupHeaderHeight || props.columnHeaderHeight) * densityFactor,
+  );
   const filterHeadersHeight = isHeaderFilteringEnabled
     ? Math.floor((props.headerFilterHeight ?? props.columnHeaderHeight) * densityFactor)
     : 0;

-  return columnHeadersHeight * (1 + (maxDepth ?? 0)) + filterHeadersHeight;
+  if (props.columnGroupHeaderHeight != null) {
+    return columnHeadersHeight + columnGroupHeadersHeight * maxDepth + filterHeadersHeight;
+  }
+
+  return columnHeadersHeight * (1 + maxDepth) + filterHeadersHeight;
 }
```

I'll open this up as a good first issue, since the fix is fairly simple.

Thanks for opening it @mike-paretos  🙇🏼
