### ISSUE TITLE
[data grid] docs demo `BasicDetailPanels` crashes

### ISSUE THREAD

**Issue by ErickSLuna** [mui/mui-x#15877]
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20BasicDetailPanels%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://mui.com/x/react-data-grid/master-detail/
2. ??
3. demo *BasicDetailPanels* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v7.23.2  |
| Netlify deploy | https://675b0b63df2c980008712f78--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 |

**Comment by michelengelen** [comment]
Hey @ErickSLuna ... I am not able to reproduce the crash.
Could you add the full details from `npx @mui/envinfo` here so we can check the specifics?
Thanks!
