### ISSUE TITLE
[pickers] `DatePicker` placeholder localization issue

### ISSUE THREAD

**Issue by ribasr** [mui/mui-x#15905]
### Summary

The image below shows the component input's placeholder:

![image](https://github.com/user-attachments/assets/d132ae4e-3358-48b4-8ca5-15f8dbd316b7)

Now, when the user clicks on the input, it changes to this format:

![image](https://github.com/user-attachments/assets/fa768f97-1521-4bfb-857a-8cc59d8927bc)

All I need is to adapt the display format to the Brazilian style, so it becomes easier for Brazilian users who will use my platform to understand what each field stands for.

dd -> day -> dia (correct)
MM -> month -> mês (correct, but I'd need it to be lowercase)
yyyy -> year -> ano (I need it to be "aaaa" in this case, which stands for "ano")

### Examples

Link of documentation: https://mui.com/x/react-date-pickers/date-picker/

**Search keywords**: display format, date picker

**Comment by noraleonte** [comment]
Hey @ribasr 👋 

I think what you are trying to achieve is a localized placeholder. Maybe this[ section in the docs](https://mui.com/x/react-date-pickers/adapters-locale/#custom-field-placeholder) could be useful?

**Comment by ribasr** [comment]
Morning @noraleonte. That was exactly what I needed! Sorry for the lack of attention 😅 and thanks for the quick response
