### ISSUE TITLE
Bump x-license-pro package peerDependency to accept React 19

### ISSUE THREAD

**Issue by damischa1** [mui/mui-x#15907]
x-license-pro has peer dependency as follows peer react@"^17.0.0 || ^18.0.0".

React 19 is not accepted but it is already stable.

Please update dependencies to accept React 19.

**Comment by cherniavskii** [comment]
Hi @damischa1 
Are you using v6 of MUI X packages?
We have added React 19 support in https://github.com/mui/mui-x/releases/tag/v7.23.0 since v7 is the latest major and we're working on v8 alpha.

**Comment by damischa1** [comment]
Hello,

in my package json I have. For the license package the 6.x is latest:
    "@mui/icons-material": "^6.2.0",
    "@mui/material": "^6.2.0",
    "@mui/x-data-grid": "^7.23.2",
    "@mui/x-data-grid-pro": "^7.23.2",
    "@mui/x-license-pro": "^6.10.2",

**Comment by LukasTy** [comment]
@damischa1 Starting with v7 we have renamed the [license package](https://www.npmjs.com/package/@mui/x-license?activeTab=versions) to resemble its intent better.
Please follow [this migration section](https://mui.com/x/migration/migration-data-grid-v6/#update-the-license-package) to complete your upgrade to v7. 😉

**Comment by damischa1** [comment]
Closed
