### ISSUE TITLE
[data grid] Agreggation of values in group rows

### ISSUE THREAD

**Issue by berko-cymphony** [mui/mui-x#15904]
### The problem in depth

Is there a way to show aggregated values of non-grouped columns in the group row?
Meaning, suppose for the example shown in [row-grouping](https://mui.com/x/react-data-grid/row-grouping/#grouping-criteria), in each row of a group, show for example the total sum of all movie budget under the Gross column, that is now empty.

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGrid row grouping aggregation

**Order ID**: 101752

**Comment by michelengelen** [comment]
You mean like this: [Usage with row grouping](https://mui.com/x/react-data-grid/aggregation/#usage-with-row-grouping)?

**Comment by oliviertassinari** [comment]
A prior Zendesk ticket, with some context https://mui.zendesk.com/agent/tickets/24440.
