### ISSUE TITLE
[question] I am having trouble integrating TimePicker into Joy MUI theme.  I like the look and feel of JOY but need TimePickers for my app.  The issue seems to be theme related.

### ISSUE THREAD

**Issue by xylocodestack** [mui/mui-x#15911]
### The problem in depth

Theme Inegrations not matching, wondering if JOY UI will get Native Time Pickers

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: TimePicker JOY UI Integration

**Order ID**: #92973

**Comment by michelengelen** [comment]
We did halt development of Joy UI for the time being. I don't think we will get native support soon.

**Comment by michelengelen** [comment]
In fact we are removing the Joy UI implementation. But we are also currently working on a design-agnostic approach which would make it easy to theme just as Joy UI was before.

I'll close this one as we won't be doing anything on it. Sry!

**Comment by xylocodestack** [comment]
Awesome thanks for the update.  Any timeline for when the design agnostic
approach will get launched?
