### ISSUE TITLE
[data grid] Sorting on grouped row sorts within groups, not globally

### ISSUE THREAD

**Issue by eslachance** [mui/mui-x#15922]
### The problem in depth

I am grouping data we receive by *date* and within each date, rows are displayed with the time only. However, when sorting this column, instead of sorting the whole data and showing the oldest date first, it instead sorts the times inside each day, which isn't what I'm expecting or desire.

I have actually seen sorting work with groups, however, it seems to only happen if the group is separate from an existing data row. I don't want to show the date twice, so this solution wouldn't work for me.

There is an entire example of this issue on stackblitz: https://stackblitz.com/edit/react-yxuyax?file=Demo.tsx 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
```
</details>

TS config
```
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2023"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,

    /* Linting */
    "strict": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": "",
    "paths": {
      "@components/*": ["src/common/components/*"],
      "@api/*": ["src/common/api/*"],
      "@services/*": ["src/common/services/*"],
      "@util/*": ["src/util/*"],
      "@rbac": ["constants.js"],
      "@assets/*": ["src/assets/*"],
    }
  },
  "include": ["vite.config.ts"]
}
```

**Search keywords**: grid, row grouping, sorting

**Order ID**: 100631

**Comment by michelengelen** [comment]
Hey @eslachance ... adding `mainGroupingCriteria: 'creationDate',` to the `groupingColDef` fixes this. Is that a sufficient solution for you?

**Comment by eslachance** [comment]
> Hey @eslachance ... adding `mainGroupingCriteria: 'creationDate',` to the `groupingColDef` fixes this. Is that a sufficient solution for you?

That indeed does the trick. I'm pretty sure I didn't see this option used in any of the examples in the docs where grouping worked, so I assume there's some odd mix of things I'm doing that might affect the default sorting? Either way... yes that does indeed solve the problem, thank you!
