### ISSUE TITLE
[data grid] Switching From DataGrid Community to DataGrid Premium

### ISSUE THREAD

**Issue by charlie-robison** [mui/mui-x#15932]
### The problem in depth

Hello support team. Our development team just purchased MUI DataGrid premium and switched from the community version.  I was just wondering if you guys had some type of tutorial or guide on how to integrate our old DataGrid implementations to the premium. It seems there are some differences, and since we have DataGrid implemented in many places, we think it would be best to have some kind of guide to easily transition to the premium. Please let me know if it is possible to get a hold of one of these.

**Search keywords**: Guide, Tutorial

**Order ID**: 104232

**Comment by michelengelen** [comment]
Hey @charlie-robison ... the Data Grid Pro and -Premium are based on the MIT version, so there is no need for a migration procedure. The only thing you need to do is enable pagination, as it is disabled by default on the Pro and Premium versions ([doc reference](https://mui.com/x/react-data-grid/pagination/#pro-and-premium))

Is there anything else we can assist you with?

**Comment by charlie-robison** [comment]
Thank you @michelengelen I appreciate it. I will look more into this. But I was facing issues with new prop names, and different ways things were implemented for example, instead of "component" and "componentProps" props I had to change it to "slot" and "slotProps". Is there some guide out there that highlights these differences and which ones to change? Also it seems I cannot have the old DataGrid component in the same project as the new one. Is there a way to keep the old DataGrid implementation and just add on new DataGrid Premium implementations so that we do not have to go back and change those? I appreciate your help.

**Comment by michelengelen** [comment]
@charlie-robison going up a version is a whole different point 😆 

We have some detailed migration guides on that in the docs:
- [Migration from v5 to v6](https://mui.com/x/migration/migration-data-grid-v5/)
- [Migration from v6 to v7](https://mui.com/x/migration/migration-data-grid-v6/)

On your other question: It should be no problem to have a community data grid besides a premium one in your application side by side. Even different versions shouldn't be a problem.

**Comment by charlie-robison** [comment]
Oh perfect thank you! I will read up on these and leave my existing data grids with just new implentations for the premium. Sorry one more question, when I leave the datagrid community component there after I uninstall datagrid community and install datagrid premium it say Deprecated on the import, im guessing this is ok to have and will work properly? Also if there are other components that are part of data grid community package such as the toolbar, will those components also be part of the premium package when importing?

**Comment by charlie-robison** [comment]
Ok I did this and there are no errors for DataGridPremium tables, but I get errors for other imports from premium such as GridColDef,  GridToolbarContainer, and GridToolbarQuickFilter. Can't seem to find a replacement on the version migration documentation too (in case that was a version change). Here is my error: Module '"@mui/x-data-grid-premium"' has no exported member 'GridToolbarContainer', when I do: 

```
import {
  DataGridPremium,
  GridToolbarContainer,
  GridToolbarQuickFilter,
} from "@mui/x-data-grid-premium";
```
