### ISSUE TITLE
[data grid] DataGridPremium crashes when grouping columns with valueGetters

### ISSUE THREAD

**Issue by hdale94** [mui/mui-x#15935]
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/p9p2dk
2. Group name column
3. Application will crash

### Current behavior

Crashes instantly when grouping name column.

### Expected behavior

Should not crash, because it didn't crash when starting the application.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DataGridPremium, Crash, Grouping

**Order ID**: 83335

**Comment by michelengelen** [comment]
@hdale94 could you make the sandbox public please?

**Comment by hdale94** [comment]
> @hdale94 could you make the sandbox public please?

Yep, just did that now.

**Comment by michelengelen** [comment]
All right ... It's the same problem as with your other issue #15940 ... see [this comment](https://github.com/mui/mui-x/issues/15940#issuecomment-2554223826).

Closing this as it is fixed with the mentioned comment! 👍🏼
