### ISSUE TITLE
DatePicker missing onValidDate prop

### ISSUE THREAD

**Issue by david-ic3** [mui/mui-x#15951]
When using the DatePicker I'm missing a callback property that will only be called when the date is valid :

- Manually entered date is a valid date
- Date is inbounds (min,max), if defined

What i get is, onChange called with invalid dates and dates out of bounds. onAccept is called when a date is clicked in the popper calendar. 

The second parameter of onChange is returning the input value (not the pickerSelectionState)

You can check console logs using this demo (demo.tsx)

https://codesandbox.io/s/basicdatepicker-material-demo-forked-izqnh

**Comment by flaviendelangle** [comment]
On the pickers in `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` you can look at the 2nd param of `onChange` which tells you if the value is valid or not.
