### ISSUE TITLE
[DatePicker] Replace type="tel" with inputMode="numeric"

### ISSUE THREAD

**Issue by barrymichaeldoyle** [mui/mui-x#15954]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I add `InputProps={{ inputMode: 'numeric' }}` to a `KeyboardDatePicker` and try to access the keyboard via my iPhone XR, the default keyboard shows up.

## Expected Behavior 🤔

I expect the keyboard to be a simple numeric input (just numbers 1-9) to show up for the native ios keyboard here.

## Steps to Reproduce 🕹

https://qsqn5.csb.app/

Steps:

1. Open Example using an iPhone on Chrome or Safari
2. Focus on the "Working Example" TextField to see what is expected.
3. Focus on the "Not Working iPhone Input" KeyboardDatePicker example to see the bug in action.

## Context 🔦

Some users that we have are used to using keyboard input for typing in a date and it would give them a significant user experience quality boost if we could get their keyboards to show up as purely numeric inputs instead of the generic text input.

## Your Environment 🌎

iPhone XR using Chrome (Safari also doesn't work)

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.12.2  |
| @material-ui/pickers | v3.3.10  |
| React       | 17.0.2  |
| Browser     | Chrome |
| TypeScript  | 4.1.2 |

**Comment by flaviendelangle** [comment]
We have `inputMode="numeric"` now
