### ISSUE TITLE
Dependency conflict date-fns version 4.x in @mui/x-date-pickers

### ISSUE THREAD

**Issue by GabbereX** [mui/mui-x#15987]
### Steps to reproduce

Steps:
1. Installed dependency date-fns 3.6.0
2. npm i date-fns@latest

### Current behavior

```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: project@0.0.0
npm warn Found: date-fns@3.6.0
npm warn node_modules/date-fns
npm warn   peerOptional date-fns@"^2.25.0 || ^3.2.0" from @mui/x-date-pickers@7.16.0
npm warn   node_modules/@mui/x-date-pickers
npm warn     peer @mui/x-date-pickers@">=7.15" from material-react-table@3.0.3
npm warn     node_modules/material-react-table
npm warn   1 more (the root project)
npm warn
npm warn Could not resolve dependency:
npm warn peerOptional date-fns@"^2.25.0 || ^3.2.0" from @mui/x-date-pickers@7.16.0
npm warn node_modules/@mui/x-date-pickers
npm warn   peer @mui/x-date-pickers@">=7.15" from material-react-table@3.0.3
npm warn   node_modules/material-react-table
```

### Expected behavior

There are no warnings

### Context

Update Dependencies

### Your environment

>   System:
>     OS: Windows 11 10.0.26100
>   Binaries:
>     Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
>     npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
>     pnpm: Not Found
>   Browsers:
>     Chrome: Not Found
>     Edge: Chromium (131.0.2903.70)
>   npmPackages:
>     @emotion/react: ^11.14.0 => 11.14.0
>     @emotion/styled: ^11.14.0 => 11.14.0
>     @mui/core-downloads-tracker:  6.2.1
>     @mui/icons-material: ^6.2.1 => 6.2.1
>     @mui/material: ^6.2.1 => 6.2.1
>     @mui/private-theming:  6.2.1
>     @mui/styled-engine:  6.2.1
>     @mui/system:  6.2.1
>     @mui/types:  7.2.20
>     @mui/utils:  6.2.1
>     @mui/x-date-pickers:  7.16.0
>     @types/react: ^19.0.2 => 19.0.2
>     react: ^18.3.1 => 18.3.1
>     react-dom: ^18.3.1 => 18.3.1
>     typescript: ^5.7.2 => 5.7.2

**Search keywords**: date-fns, @mui/x-date-pickers, dependencies

**Comment by LukasTy** [comment]
Hello @GabbereX, you can find the [adapter setup guide](https://mui.com/x/react-date-pickers/getting-started/#date-library-adapter-setup) in the docs. 😉
