### ISSUE TITLE
Pro license during development

### ISSUE THREAD

**Issue by elawad** [mui/mui-x#15997]
### The problem in depth

Hi, I have a Pro license that expired on Nov 17, 2024.

During development the application throws an error and does not render.
I haven not upgraded any mui/mui-x versions.

But if I comment out `LicenseInfo.setLicenseKey("...");` the app will render with a watermark and error in console.

What is the approach to continue in development with an expired license?
Do I simply comment out the `setLicenseKey` call?

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
  OS: macOS 14.7.1
Binaries:
  Node: 22.11.0 - ~/.local/state/fnm_multishells/21097_1734992237780/bin/node
  npm: 10.9.0 - ~/.local/state/fnm_multishells/21097_1734992237780/bin/npm
  pnpm: Not Found
Browsers:
  Chrome: 131.0.6778.205
  Edge: Not Found
  Safari: 18.2
npmPackages:
  @emotion/react: ^11.11.0 => 11.13.3
  @emotion/styled: ^11.11.0 => 11.13.0
  @mui/core-downloads-tracker:  5.16.7
  @mui/icons-material: ^5.15.0 => 5.16.7
  @mui/material: ^5.15.0 => 5.16.7
  @mui/private-theming:  5.16.6
  @mui/styled-engine:  5.16.6
  @mui/styles: ^5.15.0 => 5.16.7
  @mui/system:  5.16.7
  @mui/types:  7.2.16
  @mui/utils:  5.16.6
  @mui/x-data-grid:  7.15.0
  @mui/x-data-grid-pro: ^7.3.1 => 7.15.0
  @mui/x-internals:  7.15.0
  @mui/x-license:  7.15.0
  @types/react: ^18.3.0 => 18.3.12
  react: ^18.3.0 => 18.3.1
  react-dom: ^18.3.0 => 18.3.1
  typescript: ^5.6.3 => 5.6.3
```
</details>

**Search keywords**: expired license development

**Order ID**: 79011

**Comment by michelengelen** [comment]
If you want to keep developing with the Pro version you absolutely need a new license ... otherwise you would need to use the community version. Keep in mind that the current implementation will still work in production.

For a renewal reach out to the sales team under sales@mui.com or visit this [site](https://mui.com/pricing/).
