### ISSUE TITLE
Missing functions `{setRow, setRowModesModel}`  from GridToolbarProps TypeScript definition

### ISSUE THREAD

**Issue by pattrickrice** [mui/mui-x#15993]
### Steps to reproduce

Steps:
1. Open this link to live example: (required) https://github.com/mui/mui-x/blob/4a649f2b9fc3229a8fb1eba8593f3c27a2cc9b27/docs/data/data-grid/editing/FullFeaturedCrudGrid.tsx#L73-L80

### Current behavior

GridToolbarProps is missing these two functions. If there's a reason the interface doesn't have them, it's not documented.

### Expected behavior

I would expect to not have to declare these types myself. I would assume we should be able to add these to GridToolbarProps and remove the unnecessary complication of needing to have users extend the declaration. 

### Context

I'm trying to upgrade to v7 and encountered this as a typescript error and had to search through the docs thinking I was doing something wrong. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
  Binaries:
    Node: 16.20.2 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm
    pnpm: 8.15.6 - /usr/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.108
```
</details>

**Search keywords**: data-grid

**Order ID**:

**Comment by MBilalShafi** [comment]
@pattrickrice Do you intend to receive `setRows` and `setRowModesModel` by default in `GridToolbarProps`?

The example you quoted is just a recipe where these props are passed as additional props using module augmentation to extend the existing functionality of the `toolbar` slot, could you expand on why do you expect them in the toolbar props by default?

A supporting live minimal reproduction example would be helpful to relate with the issue, here's a quick guide on preparing a reproduction: https://mui.com/x/introduction/support/#bug-reproductions
