### ISSUE TITLE
[pickers] Update peer dependency for `date-fns-jalali` to v4

### ISSUE THREAD

**Issue by ahmadi3d** [mui/mui-x#15995]
### Summary

Hello,
I would like to request an update to the peer dependency in x-date-pickers to support date-fns-jalali version 4. Based on my testing, date-fns-jalali version 4 works seamlessly without requiring any changes, indicating that updating the peer dependency should be safe and trouble-free.

Thank you!

### Motivation

I do not wish to get the following warning:
├─┬ @mui/x-date-pickers 7.23.3
│ └── ✕ unmet peer date-fns-jalali@"^2.13.0-0 || ^3.2.0-0": found 4.1.0-0

**Search keywords**: x-date-pickers peer dependency date-fns-jalali

**Comment by michelengelen** [comment]
Hey @ahmadi3d ... I've added this to the board for the team to pick up. Thanks for raising this! 🙇🏼
