### ISSUE TITLE
Cannot find module '@mui/x-internals/forwardRef'

### ISSUE THREAD

**Issue by samausir** [mui/mui-x#16007]
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/nrphd5?file=%2Fsrc%2FApp.tsx%3A11%2C1
2. Observe the error on the right-hand side.

### Current behavior

An error appears when importing from @mui/x-data-grid:

> Cannot find module '@mui/x-internals/forwardRef' from '/node_modules/@mui/x-data-grid/components/GridPagination.js'

### Expected behavior

Imports from @mui/x-data-grid should not throw errors.

### Context

This has only started to happen with the new 7.23.4 package. Specifically https://github.com/mui/mui-x/pull/15984 seems to be the culprit.

**Search keywords**: grid forwardref

**Comment by mhalikosen** [comment]
Same problem

**Comment by LukasTy** [comment]
Well, it looks like https://github.com/mui/mui-x/pull/15984 has not been picked up for the `@mui/x-internals` release.
@DanailH did Lerna not suggest bumping it? 🙈 😢

**Comment by DanailH** [comment]
Ok, that was fast. I'm aware of the problem. We will push just that package and it should fix the problem.

**Comment by vladyakubets** [comment]
same issue

**Comment by DanailH** [comment]
The problem should be fixed with the latest release.
