### ISSUE TITLE
[website] Move EULA to a plain page on mui.com

### ISSUE THREAD

**Issue by wattry** [mui/mui-x#1668]
When trying to take a look at the x-grid license the link to https://mui.com/x/license/ returns a 404.

Also, is a Google Docs the best format for a EULA?

**Comment by oliviertassinari** [comment]
For the others that might when where did @wattry found the link, the answer is: https://unpkg.com/browse/@material-ui/x-grid@4.0.0-alpha.28/LICENSE.md.

In the meantime, the information can be found in the EULA of https://material-ui.com/store/items/material-ui-pro/

**Comment by ZeeshanTamboli** [comment]
@oliviertassinari Can I fix the URLs or do I need sign a CLA for licensing reasons as this is license based.

**Comment by oliviertassinari** [comment]
@ZeeshanTamboli We plan to move the content of the license from Google Docs to a plain page. A temporary fix could be to alias the URL in the _redirect in the master branch of main repo.

**Comment by ZeeshanTamboli** [comment]
Then better to add the URL when we shift it to it's own page.

**Comment by oliviertassinari** [comment]
We did a few iterations with #127.
