### ISSUE TITLE
[data grid] Implement Column spanning

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#192]
<img width="138" alt="Capture d’écran 2021-06-10 à 16 08 32" src="https://user-images.githubusercontent.com/3165635/121539636-225bfb00-ca06-11eb-832b-e3fb829ebb5a.png">

### Benchmark

- https://www.w3schools.com/tags/att_td_colspan.asp
- https://material-ui.com/components/tables/#spanning-table
- https://ant.design/components/table/#components-table-demo-colspan-rowspan
- https://ej2.syncfusion.com/react/demos/#/material/grid/column-spanning
- https://ag-grid.com/javascript-grid-column-spanning/
- https://adazzle.github.io/react-data-grid/#/column-spanning

**Comment by DarioG** [comment]
Any update on this issue?

**Comment by amanmahajan7** [comment]
Updated link 
https://adazzle.github.io/react-data-grid/#/column-spanning

**Comment by lizsaloka1** [comment]
Hi, I work for a company which has obtained a Material UI Pro License (can give additional details privately). We are looking for a DataGrid feature that will enable us to have 3 table cells under 1 table header. 

This would be similar to modifying a TH to have colspan=”3”, so it spreads across three control cells, and add a scope=”colgroup” to make it apply to the group of columns below it.

Both this issue and https://github.com/mui/mui-x/issues/195 caught my eye, as a potential solution for what we are trying to do. Thanks!
