### ISSUE TITLE
[data grid] Implement Excel export

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#198]
### Benchmark

- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/export/
- https://www.telerik.com/kendo-react-ui/components/grid/excel-export/
- https://demos.telerik.com/kendo-ui/grid/excel-export
- https://ag-grid.com/javascript-grid-excel/
- http://tabulator.info/docs/4.7/download#xlsx
- https://ej2.syncfusion.com/react/demos/#/material/grid/default-exporting
- https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features

**Comment by msagerup** [comment]
any way to use an build that is not "realeased" to support excel download? Is there anyway to get this working now ?

**Comment by mayank-mundhra-2012** [comment]
Can pro version support export as excel instead of premium. This feature shouldn't be a major effort.
https://www.npmjs.com/package/xlsx 
https://www.npmjs.com/package/excel-export
https://www.npmjs.com/package/react-export-excel

**Comment by MBecerram** [comment]
with all due respect. you may consider to export the data to a created template, that would be nice !

**Comment by chaitanyaarige** [comment]
That's great ..soon we are going to see in premium plan

**Comment by stamahto** [comment]
So I´m confused. Will this feature be available in pro plan? We would appreciate it 🙏

**Comment by emadaliny** [comment]
Is this included with @mui/x-data-grid-pro V5.6.1 ?

**Comment by alexfauquette** [comment]
This feature is for the premium plan. If it is released in pro package it would be like the grouping, under experimental context.

For nox, I can not say which release will contain the feature

**Comment by LOOPING-AL** [comment]
+1

**Comment by mouadovic22** [comment]
+1

**Comment by Jfish-mastt** [comment]
+1

**Comment by lauren-o** [comment]
+1

**Comment by tristramjones** [comment]
+1
