### ISSUE TITLE
[DataGrid] Implement Quick filter

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#202]
### Benchmark

- https://ag-grid.com/javascript-data-grid/filter-quick/
- https://material-table.com/#/docs/features/search
- https://demos.telerik.com/kendo-ui/grid/search-panel
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/searching/
- https://ej2.syncfusion.com/react/demos/#/material/grid/searching
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/searching/

**Comment by singhdeepanshu** [comment]
i want to see it faster

**Comment by moishinetzer** [comment]
Quick filter looks amazing :)

**Comment by oliviertassinari** [comment]
It's to be noted that we have a quick demo for it now: https://material-ui.com/components/data-grid/filtering/#quick-filter.

**Comment by missbruni** [comment]
How will you handle quick filter search on editable fields ? So you search for a value, try to edit that value, search will then no longer match and the record would disappear.

**Comment by oliviertassinari** [comment]
@missbruni This sounds like the expected behavior, what's the issue?

**Comment by m4theushw** [comment]
In the [demo](https://material-ui.com/components/data-grid/filtering/#quick-filter) it only filters when the input field is changed. So if you search for a value, edit a field so it doesn't match the search, the record will stay visible until the search value is changed.

**Comment by ngelotte** [comment]
One reason having the Quick filter built into the grid would be really helpful is that it could use the valueFormatters to filter on the formated version of the data. I do a lookup to get a more descriptive name when displaying it in the grid. But this info does not exist on the raw data so using the example to prefilter the data it does not filter based on what is display which is confusing to the user. I am also using Xgrid so the virtualization might also cause problems here as well even when it is implemented.

**Comment by oliviertassinari** [comment]
@ngelotte the column filter is not using the value formatter because searching on the value "works better".
For the quick filter, I assume that we will need to match different parts of the search query on different columns of the rows, so I guess that a concat of each column into on string representation of the row is valuable, where we could use the valueFormatter.
