### ISSUE TITLE
[data grid] Implement Row spanning

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#207]
## TODO

- [x] ~~Clarify the scope with @joserodolfofreitas~~ Scope mentioned in https://www.notion.so/mui-org/xGrid-Row-Spanning-b178fd43907146799eb7a57d9330b68b?pvs=4#160e28c1b4b247d7befe0cbf44acd475

### Benchmarks

- https://www.telerik.com/kendo-react-ui/components/knowledge-base/merge-row-in-the-grid/

<img width="413" alt="Screenshot 2023-03-02 at 01 02 57" src="https://user-images.githubusercontent.com/3165635/222295180-dacecb00-280d-47e1-aaf3-60addf2b8c09.png">

- https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/multi-row-layout

<img width="530" alt="Screenshot 2023-03-02 at 01 05 48" src="https://user-images.githubusercontent.com/3165635/222295560-1636167b-a7d1-4dbf-9af6-ece470143e69.png">

- https://ag-grid.com/javascript-grid-row-spanning/

<img width="450" alt="Screenshot 2023-03-02 at 00 58 57" src="https://user-images.githubusercontent.com/3165635/222294470-597bcbd5-8b66-4744-b134-daa73a4215db.png">

- https://ej2.syncfusion.com/react/demos/#/material/grid/row-spanning

<img width="355" alt="Screenshot 2023-03-02 at 00 59 59" src="https://user-images.githubusercontent.com/3165635/222294977-5b43d4b9-2222-4f3a-9218-e79c95f66248.png">

- https://ant.design/components/table/#components-table-demo-colspan-rowspan

<img width="474" alt="Screenshot 2023-03-02 at 01 00 26" src="https://user-images.githubusercontent.com/3165635/222294982-21a28040-5f04-4006-8e52-1146a7699e1b.png">

### User requests

- https://mui.zendesk.com/agent/tickets/14601

**Comment by reginaldosantarosa** [comment]
yes

**Comment by daniel-refahi** [comment]
yes, please. such a useful feature

**Comment by as1265513** [comment]
Yes please we need this

**Comment by olavfosse** [comment]
(When) will this be implemented?

**Comment by olavfosse** [comment]
Also, will this be "Pro" or "Premium" feature?

**Comment by flaviendelangle** [comment]
According to our [Pricing page](https://mui.com/pricing/) it will be available on all plan, including the Community (MIT) plan.

We did not plan this feature yet. 
The Column Spanning has recently been released by the way.

**Comment by stellaliao01** [comment]
would be a very useful feature! upvote :D

**Comment by fpiaggio-ms** [comment]
This feature will be very useful! upvote!

**Comment by Bindeep** [comment]
Will be very useful! upvote!

**Comment by flaviendelangle** [comment]
I would be interested to have a few examples of the use cases around row spanning

**Comment by ayaviri** [comment]
> I would be interested to have a few examples of the use cases around row spanning

i might have misunderstood the question, but one use case be to prevent the need for tool tip hovers such as [these](https://mui.com/x/react-data-grid/column-definition/#expand-cell-renderer), which aren't accessible to keyboard users

**Comment by flaviendelangle** [comment]
But in this example, there is no cell that spans across several rows.
Like on [this example](https://ag-grid.com/javascript-data-grid/row-spanning/#row-spanning-simple-example)
Do we agree that the spanning would not only occur on interaction but would always take place ?

Otherwise, you are probably looking for [variable row height](https://mui.com/x/react-data-grid/rows/#variable-row-height) or [dynamic row height](https://mui.com/x/react-data-grid/rows/#dynamic-row-height)

**Comment by BatgerelBill** [comment]
This feature will be very useful! upvote!

**Comment by maxpham97** [comment]
!!!!

**Comment by stbaione** [comment]
Any updates on this feature? Would be very useful and is a pretty common table feature

**Comment by Rearden21M** [comment]
Upvoted — I needed this feature so I searched for it, only to find out that it's a long-awaited feature that has been "coming Soon™" for over 2 years. 🥲

**Comment by miguelpalacio** [comment]
@flaviendelangle, I believe this is a use case:

![CleanShot 2022-09-13 at 19 12 16@2x](https://user-images.githubusercontent.com/815325/190031150-28e70548-70b6-423e-bcec-0352c35fd4bb.png)

You guys actually have a very similar example for column spanning in your docs.

**Comment by dilipcm** [comment]
yes please add it soon..............................

**Comment by Crhist0** [comment]
Hello, I'm also waiting for this. We already use the pro version and this would be essential to our application.

**Comment by BrianSparr** [comment]
this is needed ... upvote

**Comment by hyukkyukang** [comment]
Strongly desired, upvote!

**Comment by mamodev** [comment]
This feature will be very useful! upvote!

**Comment by Di-Nazavr** [comment]
necessary feature! upvote!

**Comment by drjele** [comment]
upvote

**Comment by vcarazza** [comment]
upvote!!

**Comment by aneeq-ur-rehman4** [comment]
Will be very useful! upvote!

**Comment by devcomrenato** [comment]
upvote

**Comment by rajat153** [comment]
we need row spanning

**Comment by vinnn** [comment]
please row spanning would be great!

**Comment by Crhist0** [comment]
still waiting for it, would be a nice addition 🙏😊

**Comment by Filipe-Bacof** [comment]
i'm still waiting for it

**Comment by stic-lab** [comment]
When will this feature be available, please? I am looking for a solution for spanning grids in a row but the only way I can do it, for now, is to use CSS. But I think it will be good if this feature is natively supported by mui.

**Comment by olavfosse** [comment]
j;kldffadsjkfdjs;afadjsifiudswq82376eqw8rueqwry7;

**Comment by sagetamerta** [comment]
upvote

**Comment by megaacheyounes** [comment]
Upvote
![](https://media.giphy.com/media/YZOsKxJfmvzG0/giphy.gif)

**Comment by nick-winter-vector** [comment]
Upvote

**Comment by Newbeecoderreal** [comment]
We need this. Upvote for this <3

**Comment by vpwang** [comment]
upvote

**Comment by sharmishthavirgo** [comment]
> use CSS.

do you have solution that so we can look as we are also having trouble implementing on data-grid

**Comment by Rajesh-shetty** [comment]
any solution in css to make row span in datagrid

**Comment by stic-lab** [comment]
> any solution in css to make row span in datagrid

Hey @Rajesh-shetty, if you want to do this in css, you can use library such [tailwindcss](https://tailwindcss.com/docs/grid-column) or also you can ispire from tailwind and write your  own css.

**Comment by MarioStipetic** [comment]
Upvote!

**Comment by jmelendez-cbs** [comment]
upvote

**Comment by narang874** [comment]
> > Also, will this be "Pro" or "Premium" feature?
> 
> According to our [Pricing page](https://mui.com/pricing/) it will be available on all plans, so open source.
> 
> > (When) will this be implemented?
> 
> We did not plan this feature yet. The Column Spanning has recently been released by the way.

could you please give us an update on this? really looking forward to it

**Comment by oliviertassinari** [comment]
Does someone have another example (the first one being https://github.com/mui/mui-x/issues/207#issuecomment-1246078217) of how this feature would be used? This could help us once we need to create a demo in the docs. Thanks

**Comment by Luv-m** [comment]
Hello :), 
Is there any update about when this feature will be ready? 
Thanks !

**Comment by rajat153** [comment]
how to pass a Total sum row at bottom of material UI datagrid table without purchase premium plan??

**Comment by pikitgb** [comment]
any updates on this ?

**Comment by Volodymyr1Korol** [comment]
Hello from Ukraine! Upvoting this beutifull feature! Be safe and happy ;)

**Comment by ganeshkarthik-natarajan** [comment]
Hi Team, Upvoting this feature.

**Comment by oliviertassinari** [comment]
@cherniavskii Did we consider to implement this in two steps? A first quick and dirty, like AG Grid uses, and then a proper solution in v6?

**Comment by cherniavskii** [comment]
@oliviertassinari Yes, that's the plan - see https://www.notion.so/mui-org/xGrid-Support-new-use-cases-with-new-features-d05424cedf6f490eb547e6802c5f4a30

**Comment by moumine9** [comment]
Hello Everyone, upvotting this feature again.

**Comment by barrykaplan** [comment]
From a paying customer (yes, there are some of us), some insight the scheduling would be very helpful. We are running out of time and need to make a call whether to swap over to ag-grid or some such.

**Comment by jithinvariyar** [comment]
I needed this feature so I searched for it, only to find out that it's a long-awaited feature that has been "coming Soon™" for over 3 years. 🥲

**Comment by dzinreach** [comment]
Seems like this feature is still not implemented, even for the paid plans, right? 
So, is there a hack to make row spanning for one-to-many record relationships work on the data grid?

**Comment by oliviertassinari** [comment]
A quick workaround: https://codesandbox.io/p/sandbox/romantic-joji-7hhvfx?file=%2Fsrc%2FDemo.tsx%3A71%2C61

https://github.com/mui/mui-x/assets/3165635/6b073ed2-630b-4cdd-bcc0-e311ee85c4b1

The API looks like this:

```jsx
const rows = [
  {
    id: 1,
    lastName: "Snow",
    firstName: "Jon",
    age: 35,
    rowSpan: { age: 2 },
  },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
```

It's implemented with a `cell` slot.

```jsx
function MyCell(props: GridCellProps) {
  let style = {
    // TODO, shouldn't be needed, fix in the core.
    minWidth: props.width,
    maxWidth: props.width,
    minHeight: props.height,
    maxHeight: props.height === "auto" ? "none" : props.height,
    ...props.style,
  };
  const apiRef = useGridApiContext();
  const row = apiRef.current.getRow(props.rowId);
  if (row && row.rowSpan && row.rowSpan[props.column.field]) {
    const span = row.rowSpan[props.column.field];
    style = {
      ...style,
      minHeight: props.height * span,
      maxHeight: props.height * span,
      backgroundColor: "#fff",
      zIndex: 1,
    };
  }
  return <GridCell {...props} style={style} />;
}
```

**Comment by yehudamakarov** [comment]
everyone give kudos to @joserodolfofreitas for getting this on the roadmap!

**Comment by yehudamakarov** [comment]
> Does someone have another example (the first one being [#207 (comment)](https://github.com/mui/mui-x/issues/207#issuecomment-1246078217)) of how this feature would be used? This could help us once we create a demo in the docs. Thanks

- Like @Legys 's use case, we need to have a few columns in the row render multiple cells per row.
see this example of an array-type column rendering 3 elements in a cell:
![example of an array type column rendering x3 in a cell](https://github.com/mui/mui-x/assets/27930483/954e1af3-c4e9-4fd8-a6e6-6d7b64136790)

- Here I'm using @oliviertassinari 's workaround above but I don't know how to finish the row hovering for the spanned cells
see the workaround example:
![example of spanning rows and rendering cells instead of an array type](https://github.com/mui/mui-x/assets/27930483/23fcf3c0-09d2-4e20-b0a4-358ec9a88fb6)

- I looked at the Tree Data and Row Grouping features to achieve this, but I want a different `parent` vs `child` row. 
- to work with the floor & room example above, then the "grouping column" would need to be more like a "grouping row."
see a grouping example:
![example of the grouping column](https://github.com/mui/mui-x/assets/27930483/45d6c8aa-2e6a-4cc2-8c93-5a9ddb4be8bd)


## for now
If someone can help get a cell to look like it is holding multiple cells that would be really special

**Comment by dzinreach** [comment]
My use case for the row spanning is for 1:Many record relationships on a report.

Think: Contacts < Cases < Documents

So the rowspan is based on checking the table id/key and the record id, so if the previous record has the same table id and record id, then it should be combined together into one row and rowspan for all of the other columns.

The real challenge is knowing the relationships between columns, and being able to have multiple tables with 1:Many relationships on the same data grid. 

Imagine a Contact record spans 4 rows, because they have 4 Document Records, and the Document Records are spread over 2 Cases. So, each Case would have a rowspan of 2.

I’ve set this up in a custom .NET C# reporting platform, which checks the parent_table_id on each column and then the table_id and rec_id on each row.

**Comment by oliviertassinari** [comment]
Regarding the behavior with filtering, we might want the same as with Excel:

https://github.com/mui/mui-x/assets/3165635/3b925c17-64aa-47ec-8601-e9cb2d10bf33

**Comment by Katsuchiyo** [comment]
Any estimation on timeline of the feature?

**Comment by jeffreyschultz** [comment]
Bumping. This feature would great as we are trying to replicate a real-world form within the data grid, and it has extreme row nesting under parent call values to aggregate the children under the same group.

Would anyone from the team be willing to drop some thoughts about how this would be implemented if someone from the community would like to work on a PR? @flaviendelangle

**Comment by jeffreyschultz** [comment]
@flaviendelangle @joserodolfofreitas 

Is there someone that I need to email or call because I pay for the premium license, and for my comment to not even so much as get a response is not acceptable.

**Comment by joserodolfofreitas** [comment]
@jeffreyschultz, I will reach out to arrange a short user interview. We'd love to better understand your use case.

@Katsuchiyo, we're wrapping up [pivoting](#214), and after that, we'll tackle Row spanning, so we're loosely talking about the possibility of releasing it next quarter (Q3 2024).

**Comment by jeffreyschultz** [comment]
@joserodolfofreitas 

I believe that my use case is a bit more advanced that row spanning, but it is needed none the less. Here is an excel mockup of a current process artifact that is captured within the security field. We are attempting to convert a manual process that is captured on paper into a more automated workflow, and are attempting to replicate the original form as much as possible to ease adoption.

![image](https://github.com/mui/mui-x/assets/479560/680efd19-ffb7-46b1-b103-c55db1664dad)

You will notice that Events aggregate Indicators, and Indicators aggregate Actions. Every action is essentially its own row, however, they are nested under their parent which groups them together. _The odd column you will probably notice is `Decision`, and this is scoped to the entire Indicator--a specific decision needs to be made once an Indicator has been confirmed._

We also dynamically build the columns under `Assets` based on what is available to that team. So the number of columns is determined by backing data elsewhere in the app.

I believe that the following is beyond the scope of row spanning, however, I am providing it for completeness to give you better insight into what we would be trying to achieve.

1. We want to provide the ability to directly add/remove new Events, Indicators, and Actions within this grid, which almost seems as though a tree data structure would be best for easier management of the backing data.

2. We want to support drag and drop of nested Indicators and Actions to new parents; in the event of Indicators, that would be another Event, and for Actions, that would be another Indicator.

Can this visual design be easily achieved with what is available in the Data Grid at this time? If so, would you be able to point me to someone that could provide some advice?

**Comment by joserodolfofreitas** [comment]
@jeffreyschultz, thank you very much for sharing your use case!

> 1. We want to provide the ability to directly add/remove new Event, Indicator, and Action rows within this grid, which almost seems as though a tree data structure would be best for easier management of the backing data.

We initially thought about the idea that row spanning is reflected in the data with repeated values on each row, like in the following example:

<img width="605" alt="x-ray-rowspanning" src="https://github.com/mui/mui-x/assets/550141/93c57175-12a8-4c70-ac28-f61cd3ed56f1">

But we may indeed need a way to define the hierarchy of cells to support your following described scenarios.

> 2. We want to support drag and drop of nested Indicator and Action rows to new parents; in the event of Indicator, that would be another Event, and for Action, that would be another Indicator.

That's an interesting use case, unfortunately, outside the scope of the initial version, but we'll keep an eye out for a workaround (It's a tough one though).

> 3. It would be great if sorting honored the nesting of the rows, so that Action rows sorted under its' Indicator, and Indicator rows sorted under its' Event.

That's also an interesting use case. We're not planning to constrain sorting like this by default, but we can likely provide a recipe using a [custom comparator](https://mui.com/x/react-data-grid/sorting/#custom-comparator).  

> Can this visual design be easily achieved with what is available in the Data Grid at this time? If so, would you be able to point me to someone that could provide some advice?

That's not supported at this time, and although Row spanning is one of the highest priorities for the next quarter, I'm afraid the initial version won't have out-of-the-box support for these most advanced use cases based on a defined hierarchy. Even the bolder borders on the created groups might be challenging. 
But as mentioned before, we'll try to find workarounds within the initial implementation so your use case can be unblocked. And we'll certainly consider a follow-up to support such use cases out-of-the-box. Thanks again for sharing it.

**Comment by jeffreyschultz** [comment]
> @jeffreyschultz, thank you very much for sharing your use case!
> 
> > 1. We want to provide the ability to directly add/remove new Event, Indicator, and Action rows within this grid, which almost seems as though a tree data structure would be best for easier management of the backing data.
> 
> We initially thought about the idea that row spanning is reflected in the data with repeated values on each row, like in the following example:

Yeah, that was one of my thoughts as well. It would certainly make it easier from your side to handle that. You mark which columns are to group, and then the cell renders a `rowspan` attribute for that number of rows along with ensuring the sort brings those rows together.

It seems to me that a combination of styling changes, row grouping, and row spanning could possibly get me most of the way there? The row grouping layout is different than what I am looking for, but is it possible change the rendering to something more like this? Instead of a dropdown, you get a row spanned cell?

**Comment by joserodolfofreitas** [comment]
> It seems to me that a combination of styling changes, row grouping, and row spanning could possibly get me most of the way there? The row grouping layout is different than what I am looking for, but is it possible change the rendering to something more like this? Instead of a dropdown, you get a row spanned cell?

@jeffreyschultz, yeah, maybe you can use [multiple grouping columns](https://mui.com/x/react-data-grid/row-grouping/#multiple-grouping-columns-2). Now, honestly, I think it seems close enough, but it's deceivingly hard to move from the drop-down to the row-spanning display. We'll discuss some alternatives and let you know.
