### ISSUE TITLE
[DataGrid] Double-clicking a portaled cell doesn't trigger the edit mode

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#2170]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Double-clicking a cell that is portaled doesn't trigger the edit mode.

## Expected Behavior 🤔

It should trigger the edit mode when clicking in any part of a cell that is portaled.

## Steps to Reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/expandcelldemo-forked-iqp33?file=/src/App.tsx
2. Hover the mouse over any cell that has ellipsis "..."
3. Double-click the cell to enter the edit mode

## Context 🔦

Noticed in https://github.com/mui-org/material-ui-x/issues/417#issuecomment-882386846
Support for edit components that use Portal was added in #1772

**Comment by flaviendelangle** [comment]
It's no longer the case: https://codesandbox.io/p/sandbox/data-grid-community-forked-sdfmvd?file=%2Fsrc%2FApp.tsx%3A13%2C4
