### ISSUE TITLE
[DataGridPro] Add the ability to pass a method to updaters

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#2234]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The update methods (`setEditRowsModel`, `setFilterModel`, ...) could handle a method like `setGridState` to help updating part of them without fetching the rest of the model manually.

## Examples 🌈

To update a cell edit props we could to the following

```diff
+apiRef.current.setEditRowsModel(oldModel => ({
+  ...oldModel,
+  [id]: {
+    ...oldModel[id],
+    [field]: { ...oldModel[id][field], error: true },
+  },
+}));
-const oldModel = apiRef.current.getEditRowsModel();
-apiRef.current.setEditRowsModel({
-  ...oldModel,
-  [id]: {
-    ...oldModel[id],
-    [field]: { ...oldModel[id][field], error: true },
-  },
-});
```

## Motivation 🔦

We have several situations where we modified / will modify our public API to create more generic methods in order to avoid creating new ones.
As we move forward, I expect it the happen again whenever we started with a method that update a single cell / single row / single filter etc... and we start wanting to be able to update several at once.

For instance

- A single method `setEditRowsModel` to set the whole row value or a single cell value

To update a single cell
```diff
-apiRef.current.setEditCellProps({ id, field, props: { ...props, error: true } });
+const oldModel = apiRef.current.getEditRowsModel();
+apiRef.current.setEditRowsModel({
+  ...oldModel,
+  [id]: {
+    ...oldModel[id],
+    [field]: { ...oldModel[id][field], error: true },
+  },
+});
```

See #2220 

- A single method `setVisibleColumns` to set all the columns visibility or a single column visibility 

// To hide a single column (just an example of the behavior we could have, not implemented yet)
```diff
-apiRef.current.setEditCellProps({ id, field, props: { ...props, error: true } });
+const oldModel = apiRef.current.getVisibleColumns();
+apiRef.current.setVisibleColumns(oldModel.filter(oldModel !== column.field))
```

See https://github.com/mui-org/material-ui-x/issues/1412#issuecomment-860935241

It's a very common pattern in React which makes it intuitive for the users.

**Comment by DanMHammer** [comment]
I would also really like this feature. 

However, the getter/setter model is used extensively internally and would be much less clean if it were replaced, so what about providing an "update" method instead that accepts a predicate and relies on the setter/getter. This would be simple to implement without a breaking change. The downside would be that it would provide multiple ways to accomplish the exact same task, which may not be desirable in the long run.

```jsx
  const updateEditRowsModel = React.useCallback(
    (predicate: Function) => setEditRowsModel(predicate(getEditRowsModel())),
    [setEditRowsModel, getEditRowsModel],
  );
```

**Comment by flaviendelangle** [comment]
@DanMHammer I don't think we should remove the existing API format.
Like for `React.useState`, I propose to handle both the method and the direct value.

```ts
// Method
apiRef.current.setEditRowsModel(oldModel => ({
  ...oldModel,
  [id]: {
    ...oldModel[id],
    [field]: { ...oldModel[id][field], error: true },
  },
}));

// Direct value
const oldModel = apiRef.current.getEditRowsModel();
apiRef.current.setEditRowsModel({
  ...oldModel,
  [id]: {
    ...oldModel[id],
    [field]: { ...oldModel[id][field], error: true },
  },
});
```

It keeps us close to React approach without breaking any existing code.

**Comment by DanMHammer** [comment]
You are correct. I got caught up in the typescript of it all and didn't think of the simple fact that useState is already capable of this and is used that way frequently.

**Comment by oliviertassinari** [comment]
AFAIK, the problem that React solved with the setState callback is hard to access previous values, e.g. hoisting yielding outdated references. We already solved this problem with the apiRef. I don't see the pros.
On the cons, It's growing the API surface.

I think that we could handle this issue with the "waiting for upvotes" label.
