### ISSUE TITLE
[DataGrid] `autoHeight` + `hideFooter` results in double bottom border

### ISSUE THREAD

**Issue by lgeiger** [mui/mui-x#2315]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Enabling both `autoHeight` and `hideFooter` in the data grid renders a double border on the bottom of data grid:
<img width="579" alt="Screenshot 2021-08-10 at 00 28 45" src="https://user-images.githubusercontent.com/13285808/128787595-2521cce8-3862-4c36-9fa8-b8d6edf05147.png">

This is very minor, but it looks like the bottom border of the last grid row shouldn't be rendered in this case to avoid this.

## Expected Behavior 🤔

No double border should appear on the bottom of the grid.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-3ndjy?file=/demo.tsx

Steps:

1. Zoom in and look at the bottom of the data grid

## Context 🔦

This is a small, but noticeable layout bug. This is especially noticeable if the border size of the columns doesn't match the root border color of the grid.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.5.1
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @material-ui/core: ^5.0.0-beta.2 => 5.0.0-beta.2
    @material-ui/data-grid: ^4.0.0-alpha.35 => 4.0.0-alpha.35
    @material-ui/icons: ^5.0.0-beta.1 => 5.0.0-beta.1
    @material-ui/private-theming:  5.0.0-beta.2
    @material-ui/styled-engine:  5.0.0-beta.1
    @material-ui/styles: ^5.0.0-beta.2 => 5.0.0-beta.2
    @material-ui/system:  5.0.0-beta.2
    @material-ui/types:  6.0.1
    @material-ui/unstyled:  5.0.0-alpha.41
    @material-ui/utils:  5.0.0-beta.1
    @types/react: 17.0.15 => 17.0.15
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: 4.3.5 => 4.3.5
```
</details>

**Comment by DanailH** [comment]
Ok, yes it's not technically a double border. It's the bottom border of the grid and the bottom border of the last row. This issue is not visible when you have a footer because the footer doesn't have a top border.

**Comment by oliviertassinari** [comment]
It makes me think of an older issue I tried to fix but fail: https://github.com/mui-org/material-ui-x/pull/271

**Comment by ZeeshanTamboli** [comment]
I looked into this. As @lgeiger said, I think not applying the cell bottom border for last row if `hideFooter` is true is the solution.
