### ISSUE TITLE
[SvgIcon] wrong css width/height attributes

### ISSUE THREAD

**Issue by cedricb-obs** [mui/mui-x#2331]
- [x] The issue is present in the latest release. ([here](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/SvgIcon/SvgIcon.js#L38))
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When i use [`DataGrid` with **Toolbar** component](https://material-ui.com/components/data-grid/components/#toolbar), the `Filters` icon size isn't the same as the others.

## Expected Behavior 🤔

Same sizes of the toolbar icons.

## Steps to Reproduce 🕹

Sample code:

```js
import { DataGrid, GridToolbar } from '@material-ui/data-grid';

const MyTable = ({ columns, rows }) => (<DataGrid columns={columns} rows={rows} components={{ Toolbar: GridToolbar }} />)
```

## Your Environment 🌎

Tested with Chrome `Version 92.0.4515.131 (Build officiel) (64 bits)`

## Solution

Use `rem` instead of `em`

## Captures
[![mui-svgicon-filters-size.png](https://i.postimg.cc/gxKV9nzX/mui-svgicon-filters-size.png)](https://postimg.cc/gxKV9nzX)
[![mui-svgicon-density-size.png](https://i.postimg.cc/hXnL39BR/mui-svgicon-density-size.png)](https://postimg.cc/hXnL39BR)
[![mui-svgicon-quickfix.png](https://i.postimg.cc/GBhkbdtM/mui-svgicon-quickfix.png)](https://postimg.cc/GBhkbdtM)

**Comment by cedricb-obs** [comment]
@eps1lon hi ✋ 
why you transferred my issue inside this project ? 🤔 

i pushed a [quickfix](https://github.com/mui-org/material-ui/pull/27716) with the [initial issue](https://github.com/mui-org/material-ui/issues/27715) to switch `SvgIcon` css witdh/height to `rem` instead of `em`

With the transfer, we lost the fix and `DataGrid` Toolbar component work properly, so i don't understand..

**Comment by cedricb-obs** [comment]
ok u comment my PR in same time.. 🙄 😉

**Comment by m4theushw** [comment]
Could you provide a live example? [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point.

Looking at the demo in https://material-ui.com/components/data-grid/demo/ the icons are at the correct size:

<img width="300" src="https://user-images.githubusercontent.com/42154031/129366120-0db5a29d-b859-4b15-899e-24d8518bff82.png" alt="image" style="max-width:100%;">

**Comment by cedricb-obs** [comment]
> Could you provide a live example? [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point.
> 
> Looking at the demo in https://material-ui.com/components/data-grid/demo/ the icons are at the correct size:
> 
> <img alt="image" width="300" src="https://user-images.githubusercontent.com/42154031/129366120-0db5a29d-b859-4b15-899e-24d8518bff82.png">

You can see sample [here](https://codesandbox.io/s/peaceful-browser-ov843) and after more research, it seems to come from another deps (boosted and/or admin-lte) CSS conflict.  
Sorry for the inconvenience.. but i think using `rem` is better than `em` 🤔 😜

**Comment by cedricb-obs** [comment]
i add another info, in this GridToolbar, all icons are in 18x18 px except this Filter icon (24x24). 🤔

**Comment by oliviertassinari** [comment]
Ok, so we only need to fix the font size to be 18x18 and we are good?

```diff
diff --git a/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx b/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
index ff5439e7..838572b4 100644
--- a/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
+++ b/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
@@ -115,7 +115,7 @@ export const GridToolbarFilterButton = React.forwardRef<
         aria-label={apiRef!.current.getLocaleText('toolbarFiltersLabel')}
         startIcon={
           <Badge badgeContent={counter} color="primary">
-            <OpenFilterButtonIcon />
+            <OpenFilterButtonIcon fontSize="inherit" />
           </Badge>
         }
         {...buttonProps}
```

**Comment by m4theushw** [comment]
The filter icon becomes too small with `fontSize="inherit"`. The problem with this icon in particular is that it has more padding than the others.

<img width="350" src="https://user-images.githubusercontent.com/42154031/129611689-3099bf7f-4833-4669-a5e8-8016d7d78598.png" alt="image" style="max-width:100%;">

**Comment by oliviertassinari** [comment]
@m4theushw I didn't shock me, I guess we can explore other options

**Comment by cherniavskii** [comment]
The icons indeed might have a different size, but it looks fine in v6:

<img width="411" src="https://github.com/mui/mui-x/assets/13808724/eb18130c-9198-4479-8e18-a6b026749b5f">

We don't have any actions to take here.
