### ISSUE TITLE
[DataGrid] Add API to style even and odd rows differently

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#2334]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Some might want to style even and odd rows slightly differently to help end-users navigate a data table. It's usually when there is no hover style on the rows. When there is a hover style, it's not recommended.

## Examples 🌈

An example with TablePlus, a SQL client

<img width="572" alt="Capture d’écran 2021-08-13 à 19 00 59" src="https://user-images.githubusercontent.com/3165635/129394248-9d9b2afb-3e6f-44c4-a4ab-a26d232dcf40.png">

## Details

It's a follow-up #2327 where we break this feature. A possible solution is shared in https://github.com/mui-org/material-ui-x/pull/2327#pullrequestreview-728769169. If too many developer complain, we can revert too.

**Comment by m4theushw** [comment]
If we add the row index suggested in https://github.com/mui-org/material-ui-x/pull/2327#pullrequestreview-728769169, we have to be careful because the value returned by `apiRef.current.getRowIndex` is relative to all rows, not the visible rows. Depending if there's a filter applied, two records could have both an even id and be one immediately next to the other.

I noticed this problem in #2335.

**Comment by shoxter** [comment]
Is there any update on this? I was using `Mui-odd` and `Mui-even` in `4.0.0-alpha27` and I effectively have no way to do this after upgrading to `4.0.2` forcing me to revert back to an older version. Is there something I'm missing?

**Comment by m4theushw** [comment]
@shoxter You can use the `components` prop and pass a custom row. In this new row, you add the right class depending on the index. Here's how to do it:

```tsx
import { DataGrid, GridRow } from "@mui/x-data-grid";

function CustomRow(props) {
  const { className, index, ...other } = props;

  return (
    <GridRow
      index={index}
      className={clsx(className, index % 2 === 0 ? "odd" : "even")}
      {...other}
    />
  );
}

<DataGrid {...data} rowHeight={35} components={{ Row: CustomRow }} />
```

CodeSandbox: https://codesandbox.io/s/rowcontextmenu-material-demo-forked-9vhsx?file=/demo.tsx:94-147

**Comment by shoxter** [comment]
> @shoxter You can use the `components` prop and pass a custom row. In this new row, you add the right class depending on the index. Here's how to do it:
> 
> ```tsx
> import { DataGrid, GridRow } from "@mui/x-data-grid";
> 
> function CustomRow(props) {
>   const { className, index, ...other } = props;
> 
>   return (
>     <GridRow
>       index={index}
>       className={clsx(className, index % 2 === 0 ? "odd" : "even")}
>       {...other}
>     />
>   );
> }
> 
> <DataGrid {...data} rowHeight={35} components={{ Row: CustomRow }} />
> ```
> 
> CodeSandbox: https://codesandbox.io/s/oddevenrows-material-demo-forked-9vhsx?file=/demo.tsx

Isn't this still subject to not accounting for filtered rows since it's intrinsic to the row index?

If not, it looks like it should work. I was however under the impression that there wasn't a way to get the true index accounting for both sort and filter internally.

**Comment by m4theushw** [comment]
> If not, it looks like it should work. I was however under the impression that there wasn't a way to get the true index accounting for both sort and filter internally.

What do you mean by "true index accounting for both sort and filter internally"? The `index` prop supplied to the row is sufficient to apply odd-even classes on rows.

**Comment by shoxter** [comment]
> > If not, it looks like it should work. I was however under the impression that there wasn't a way to get the true index accounting for both sort and filter internally.
> 
> @shoxter What do you mean by "true index accounting for both sort and filter internally"? The `index` prop supplied to the row is sufficient to apply odd-even classes on rows.

Okay -- it's a little misleading since `getRowIndex` from the GridAPI is described as "getting the row index of a row with a given id. **The index is based on the sorted but unfiltered row list.**" In my mind, the index supplied by the Grid will then never be taking filters into consideration which wouldn't suffice. What you're saying is the `index` prop supplied above accounts for both filtering and sorting, not just sorting like the `getRowIndex` return value?



> It is the index of the row post sorting + filtering yes.
> 
> ```ts
> // currentPage.range.firstRowIndex = index of the 1st row of the page in the row list post filtering + sorting
> // renderContext.firstRowIndex = index of the 1st row to render relative to the current page (or to all rows if pagination disabled)
> // i = index of the current row relative to the rendered rows
> // so index = index of the current row in the row list post filtering + sorting
> index={currentPage.range.firstRowIndex + renderContext.firstRowIndex! + i}
> ```
> 
> So:
> 
> 1. If you don't change the rows / the sorting or the filtering, a row should keep the same index. Scrolling / changing page size / changing page won't change the row index even with the virtualization.
> 2. The 1st row of a page can have an even or odd index if the pageSize is odd, for some usecase, you may want the index relative to the current page. You can achieve it with `gridPageSelector` and `gridPageSizeSelector` to substract the previous pages.
> 3. When using tree features (Tree Data or Row Grouping that are coming soon), it won't work since the index will depend on the expansion of the rows above. But otherwise, it should be a good solution.

The 1st exclusion, "if you don't change the filtering/sorting" is exactly my problem. I want to be able to use sorting/filtering while still styling the rows by even/odd of the current displayed values (ignoring virtualization). This was how the class implementation of `Mui-odd` and `Mui-even` worked. I didn't have to avoid filtering or sorting because it still worked.

**Comment by m4theushw** [comment]
> Okay -- the term index is a little misleading since getRowIndex from the GridAPI is described as "getting the row index of a row with a given id. The index is based on the sorted but unfiltered row list." In my mind, the index supplied by the Grid will then never be taking filters into consideration which wouldn't suffice. 

We're aware and agree when you say that this method is confusing. It's not great. You can use the selectors `gridVisibleSortedRowEntriesSelector` or `gridPaginatedVisibleSortedGridRowEntriesSelector` (if pagination is enabled) to get the same rows that are rendered. Once you have the rows, you get them by the same index of the row element. When pagination is enabled, you need to subtract the index as said in https://github.com/mui-org/material-ui-x/issues/2334#issuecomment-982615118.

**Comment by oliviertassinari** [comment]
I have tried https://github.com/mui-org/material-ui-x/issues/2334#issuecomment-982160492, while it's close to get the job done. I don't think that it's flying, see the UX when scrolling: 

![Dec-09-2021 15-20-44](https://user-images.githubusercontent.com/3165635/145413596-647b0450-007a-4149-989c-115f5bb4adc8.gif)

There is an index shift, it's not stable.

Apart from this bug, I think that it could make sense to have a demo for it. It's how macOS finder grid displays the information: 

<img width="903" alt="Screenshot 2021-12-09 at 15 10 13" src="https://user-images.githubusercontent.com/3165635/145412854-2bffefc3-7df7-4820-b90f-5d025e0d27ad.png">
 
 https://mui.com/components/data-grid/style/#styling-rows

**Comment by shoxter** [comment]
> I have tried [#2334 (comment)](https://github.com/mui-org/material-ui-x/issues/2334#issuecomment-982160492), while it's close to get the job done. I don't think that it's flying, see the UX when scrolling:
> 
> ![Dec-09-2021 15-20-44](https://user-images.githubusercontent.com/3165635/145413596-647b0450-007a-4149-989c-115f5bb4adc8.gif)
> 
> there is an index shift, it's not stable.
> 
> Apart from this bug, I think that it could make sense to have a demo for it. It's how macOS finder grid displays the information:
> 
> <img alt="Screenshot 2021-12-09 at 15 10 13" width="903" src="https://user-images.githubusercontent.com/3165635/145412854-2bffefc3-7df7-4820-b90f-5d025e0d27ad.png">
> 
> https://mui.com/components/data-grid/style/#styling-rows

I haven't had a chance to try the above suggestions yet as I immediately reverted to an old version of XGrid upon seeing the issue.

I just want to make sure I'm understanding -- currently there is no way on newer XGrid versions to utilize striped rows without the visual glitch of the index adjusting, is that correct?

**Comment by mtshv** [comment]
I am also looking for good solution for striped rows
