### ISSUE TITLE
[DataGrid] onColumnVisibilityChange doesn't fire when using show all columns

### ISSUE THREAD

**Issue by isaiah-j** [mui/mui-x#2506]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current Behavior 😯

When clicking on "show all" from the columns menu the onColumnVisibilityChange event  doesn't fire off

![showall](https://user-images.githubusercontent.com/66272034/131383738-26abcecf-3555-4647-bed3-7fb2119a5e37.png)
__

### Expected Behavior 🤔

onColumnVisibilityChange should be called

### Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

I'm trying to persist column changes using this event handler

### Order id 💳

27855

**Comment by joserodolfofreitas** [comment]
I'm reopening the issue because it's indeed expected that the callback is called when clicking "show all" or "hide all".
for reproduction, please check [the codesandbox example](https://codesandbox.io/s/datagrig-oncolumnvisibilitychange-09ehk5?file=/src/App.tsx).
