### ISSUE TITLE
Documentation for editRowsModel and onEditRowsModelChange

### ISSUE THREAD

**Issue by tayden** [mui/mui-x#2727]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

There are very few details in the documentation about how to use the `editRowsModel` prop for the DataGrid component. It's not entirely clear how this data object differs from the data passed in by the `rows` prop, or how to use it to e.g. update some data located behind a server API.

Currently, the only documentation for each of these props is self referencing. On https://mui.com/api/data-grid/data-grid/, the documentation for `editRowsModel` is "Set the edit rows model of the grid.", while the related `onEditRowsModelChange` is "Callback fired when the editRowsModel changes."

I would propose that a section of documentation on these two props, which are seemingly central to the editing capabilities of DataGrid, have a dedicated section on the [DataGrid Editing documentation page](https://mui.com/components/data-grid/editing/#main-content)

### Examples 🌈

Add "Editing Model" section to the DataGrid Editing documentation that provides information about what these props are doing.

### Motivation 🔦

I haven't been able to figure out how to use the table editing functionality to do anything beyond what the examples provide, such as updating data located behind an API.

**Comment by flaviendelangle** [comment]
@m4theushw

**Comment by m4theushw** [comment]
We don't have a section specifically for the `editRowsModel` prop. However, there're several demos that use it. In practice, users should not have to worry about this prop for simple use cases. It must only be used to validate the data, which is documented [here](https://mui.com/components/data-grid/editing/#client-side-validation) and [here](https://mui.com/components/data-grid/editing/#server-side-validation). I think what we miss is to show the actual value of the prop when doing the validation.

**Comment by oliviertassinari** [comment]
#3006 is pushing for removing the `editRowsModel` prop

**Comment by flaviendelangle** [comment]
@m4theushw can we close this one since we intend to deprecate and remove these props ?
