### ISSUE TITLE
[DataGridPro] Footer in "grid" zone/container

### ISSUE THREAD

**Issue by clmntrss** [mui/mui-x#2795]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello, I'm currently using the Datagrid on a project and I use a **custom Footer** to get total of each columns if its a number or whatever. The issue i've came when the minimal size of the table is bigger than the current window width. I've 2 different scrollbar 

I've been able to "fix" this issue with but it's breaks the flex ability of the grid and create sometime kind of infinite resizing on certain devices

` minWidth: 'fit-content',`

### Initial behavior

![image](https://user-images.githubusercontent.com/28146493/136209721-a0ef5c93-9cf5-46e0-9d7b-55e0dbb9e20c.png)

![image](https://user-images.githubusercontent.com/28146493/136210966-78594d3f-42e8-4969-9546-a973801eec55.png)

### With custom fix 

![image](https://user-images.githubusercontent.com/28146493/136210486-ff5a5406-e300-45fe-9ab8-f82342c4f5de.png)

### Motivation 🔦

I would be able to put the footer in the data grid window container or to have a **synced scroll** between both the footer row and the grid container.

**Comment by clmntrss** [comment]
@DanailH 

You can find it here : 
https://codesandbox.io/s/romantic-dijkstra-7s3o2?file=/src/Demo.tsx


I would like to add that the behavior I've in mind is more like the summary on Antd table 
https://ant.design/components/table/#components-table-demo-summary

**Comment by oliviertassinari** [comment]
I think that @clmntrss could implement this with #1251 + #192.

@mui-org/x This makes me wonder, shouldn't #1251 (row pinning) be in the Pro plan? #193 (column pinning) is.

**Comment by cherniavskii** [comment]
The data grid now supports [row pinning](https://mui.com/x/react-data-grid/row-pinning/) and [aggregation](https://mui.com/x/react-data-grid/aggregation/) features
