### ISSUE TITLE
Can not install new MUI datagrid without material-ui/core

### ISSUE THREAD

**Issue by carl-meyer-paxton** [mui/mui-x#2806]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I try to npm run start after installing @mui\x-data-grid I get the following error:

Module not found: Can't resolve '@material-ui/core/Badge' in 'C:\Users\Carl\Documents\workspace\entry-portal-ui\node_modules\@mui\x-data-grid\dist'

## Expected Behavior 🤔

Should be able to install mui/x-data-grid and run npm run start without issues

## Steps to Reproduce 🕹

npm install @mui\x-data-grid
npm run start

## Context 🔦

I am migrating from @meterial-ui (v4) to @mui. I have followed the migration instructions and everything seems to be running and working fine. I want to migrate to new data grid on mui but I get the following issue. 

## Your Environment 🌎
<details>
  <summary>`npx @mui/envinfo`</summary>
  
 System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.50
    @mui/icons-material: ^5.0.3 => 5.0.3
    @mui/material: ^5.0.3 => 5.0.3
    @mui/private-theming:  5.0.1
    @mui/styled-engine:  5.0.1
    @mui/system:  5.0.3
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: ^4.0.1 => 4.0.1
    @types/react: ^17.0.27 => 17.0.27
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.4.3 => 4.4.3
</details>

**Comment by m4theushw** [comment]
@dryhurst Which version of @mui/x-data-grid-pro you are using? If you're using v5, then @material-ui/core is not necessary, but @mui/material instead. Could you share the package.json?

**Comment by Janushan** [comment]
Installing @next worked for me `npm install @mui/x-data-grid@next`
This should give you the beta
