### ISSUE TITLE
Data-Grid page

### ISSUE THREAD

**Issue by WCN-llc** [mui/mui-x#2868]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

https://mui.com/components/data-grid/getting-started/  - does not work. The site page is constantly reloading.

### Expected behavior 🤔

Correct work of your site.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Is the language of your browser "Russian"?
