### ISSUE TITLE
[DataGridPro] Hiding a column while it's being dragged causes the focus to switch to its neighbor

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#2923]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I noticed it while developing the panel of the row grouping.
If we hide update a column while we are dragging it, then the focus switches to the column right of it.
The reason it probably that #2673 uses the col index as the key for performances reasons. So when we hide a column, React thinks keeps the same DOM element for the column right of it.

### Expected behavior 🤔

The focus should be reset when the visibility of a column changes and the focus is in this column.

Side note : Using the index as the key also causes that when we hide a column, React will recompute all the rendered visible columns right of it since their keys are shifted.
But the use-case being a lot less common that scrolling, I think the optimization we currently have is worth it.

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/great-pine-1z01q
2. Drag the "Commodity" column down (not on another col to avoid focus switch)
3. Wait 1sec for the auto col hide added in the demo
4. The focus has switched to "Trader name"
This does not occurs if you do the same on a demo prior to the new virtualization https://codesandbox.io/s/loving-grass-1th5o

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 4.14 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Managers:
    Apt: 2.2.4 - /usr/bin/apt
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 10.3.0 - /usr/bin/gcc
    Git: 2.30.2 - /usr/bin/git
    FFmpeg: 4.3.2 - /usr/bin/ffmpeg
  IDEs:
    Nano: 5.4 - /usr/bin/nano
  Languages:
    Bash: 5.1.4 - /usr/bin/bash
    Perl: 5.32.1 - /usr/bin/perl
    Python3: 3.9.5 - /usr/bin/python3
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0
  Monorepos:
    Yarn Workspaces: 1.22.10
    Lerna: 4.0.0

```
</details>

**Comment by flaviendelangle** [comment]
@oliviertassinari why do we put the "waiting for :+1: " on every issue like this ?
For features I agree that it is interesting, but I don't see the goal on small fixes like this one. I highly doubt we will have  more than a few upvotes. And if we stop doing any improvement not asked by the community we won't improve a lot of points.

For this specific issue, it is a non problem today and will become problematic when releasing the row grouping drag&drop panel.
So nobody will complain before and we would have to wait for the bug to become problematic before fixing it (even though we detected it before, we know how to solve it and we know it will be problematic).

**Comment by oliviertassinari** [comment]
@flaviendelangle I was replacing all "priority: low" labels with "waiting for 👍". 

Did we explore removing of all `useLayoutEffect -> focus` logic instances? Is it me or since Damien introduced this pattern, we have been constantly fighting to make it work? I have always assumed that a focus is not compatible to be managed in a React state.

https://github.com/mui-org/material-ui-x/blob/94325a902e866b11cd31f2a22ce4928a4eec458b/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx#L196-L201

**Comment by flaviendelangle** [comment]
I was against the idea of putting the "Waiting for upvote" label for this reason.
For me this behavior is problematic and when we will create the column grouping panel it will be a visible problem.
So the "Priority - low" had the benefit of keeping track of it even if we don't fix it now.
