### ISSUE TITLE
[DataGrid] `isRowSelectable` not working with controlled selection

### ISSUE THREAD

**Issue by hsklogix** [mui/mui-x#2947]
I am trying to disable some rows which are pre-selected when the DataGrid component renders for the first time. 
<img width="737" alt="Screenshot 2021-10-23 at 9 13 12 PM" src="https://user-images.githubusercontent.com/31209230/138563824-15482e5f-6ed1-4c50-8df9-b95fa9e923ae.png">
I am trying to do this with the isRowSelectable prop but when I add this prop, selectionModel gets empty and I am not able to see even the selected rows then.
Can anyone help out in this regard?

@oliviertassinari I have seen this issue: https://github.com/mui-org/material-ui-x/issues/2136#issuecomment-881928124
But if you'll try to add `isRowSelectable` in this example, the issue can be reproduced.

**Comment by m4theushw** [comment]
> n the example you shared, there's only one bug that I've found where we are setting the selectionModel with [...newSelectionModel, ...preselectedRows], which is resulting to show select-all feature as all selected even when I don't select all the rows.

@hsklogix You can solve that by filtering the new selection and only keeping the unique IDs.

```ts
onSelectionModelChange={(newSelection) => {
  const ids = new Set([...newSelection, ...preSelectedRows]);
  setSelectionModel([...ids.values()]);
}}
```

The only strange behavior left will be that the Select All checkbox will not work as expected because there's always a  selected row so it will try to unselect it. Providing a custom checkbox fixes this too.
