### ISSUE TITLE
[Discussion] Make the Localization work with several X components

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#2989]
## Current behavior

See the full documentation here
https://mui.com/components/data-grid/localization/#locale-text

Currently, the best way to update locals for the DataGrid is to use the global `createTheme`.

```tsx
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { DataGrid, bgBG } from '@mui/x-data-grid';

const theme = createTheme(
  {
    palette: {
      primary: { main: '#1976d2' },
    },
  },
  bgBG,
);

<ThemeProvider theme={theme}>
  <DataGrid />
</ThemeProvider>;
```

##  Limits

How would it work when we will have several X components, each with their own localization object ?
The `bgBG` local from `@mui/x-data-grid` won't contain the strings from the DatePicker for instance.

### One `createTheme` per X component

People could do wrappers on their side on each X component to make sure they are correctly localized ?

```tsx
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { DataGrid, bgBG as bgBGDataGrid} from '@mui/x-data-grid';
import { DatePicker, bgBG as bgBGDatePicker } from '@mui/x-date-picker';

const dataGridTheme = createTheme(
  {},
  bgBGDataGrid,
);

const datePickerTheme = createTheme(
  {},
  bgBGDatePicker,
);

const LocalizedDatePicker = props => (
  <ThemeProvider theme={datePickerTheme}>
    <DatePicker {...props} />
  </ThemeProvider>
)

const LocalizedDataGrid = (props) => (
  <ThemeProvider theme={dataGridTheme}>
    <DataGrid {...props} />
  </ThemeProvider>
);
```

I think this approach would not work well in advanced use cases.
Especially if the DataGrid starts using some X components (the DatePicker for instance) internally. Users would have to override those with a component slot to apply their wrapped version.

## Locale merger method

```tsx
import { createTheme } from '@mui/material/styles';
import { bgBG as bgBGDataGrid} from '@mui/x-data-grid';
import { bgBG as bgBGDatePicker } from '@mui/x-date-picker';
import { mergeLocals } from '@mui/utils' // do not exist today

const theme = createTheme(
  {},
  mergeLocals(bgBGDataGrid, bgBGDatePicker),
);
```

If we do this one, should we still merge with the core on our side ? Probably yes for simplicity.

**Comment by Jimmy-Newtron** [comment]
Closed but what is the choice you took?
