### ISSUE TITLE
[core] Improve publish scripts

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#299]
Raised in https://github.com/mui-org/material-ui-x/pull/298#issuecomment-694790526. This is an extension of #38. There are a couple of opportunities to improve the publish logic:

- We should prune the publish package, there are noisy files. In the [/dist](https://unpkg.com/browse/@material-ui/data-grid@4.0.0-alpha.1/dist/) folder, we don't need:

  - DataGrid.d.ts
  - DataGrid.spec.d.ts
  - DataGrid.test.d.ts
  - data-grid.d.ts

We could solve this by using some of the publish commands of the main repo. 

- The CHANGELOG is wrong, it should copy the main one from the root folder: https://unpkg.com/browse/@material-ui/data-grid@4.0.0-alpha.1/CHANGELOG.md and be updated before publishing. We could also solve this by using some of the publish commands of the main repo.
- The published files should [include a license comment](https://unpkg.com/browse/@material-ui/core@4.11.0/index.js). We could also solve this by using some of the publish commands of the main repo.

**Comment by cherniavskii** [comment]
Fixed by https://github.com/mui/mui-x/pull/3965
