### ISSUE TITLE
[DataGrid] Checkbox ripple not consistent when navigating with arrows

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#2998]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When navigating with arrows on the select column, checkbox's Ripple are not removed when going up

### Steps to reproduce 🕹

Steps:

1. Go on [https://mui.com/x/](https://mui.com/x/)
2. click on a checkbox
3. use arrows to go down, everything is normal
4. use arrows to go up, each checkbox keep its Ripple after being blured
5. repeat up and dow to increase the number of ripples

### Your environment 🌎

Chrome and Firefox

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.50 GB / 15.35 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
  Managers:
    Apt: 2.3.9 - /usr/bin/apt
    Composer: 1.9.0 - /usr/local/bin/composer
    pip2: 19.3.1 - ~/.local/bin/pip2
    pip3: 20.1.1 - ~/anaconda3/bin/pip3
    RubyGems: 3.2.5 - /usr/bin/gem
  Utilities:
    CMake: 3.18.4 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.2.0 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    FFmpeg: 4.4 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 20.10.8 - /usr/bin/docker
  IDEs:
    Nano: 5.6.1 - /usr/bin/nano
    VSCode: 1.61.2 - /snap/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Go: 1.14.1 - /usr/local/go/bin/go
    Java: 1.8.0_302 - /usr/bin/javac
    Perl: 5.32.1 - /usr/bin/perl
    PHP: 8.0.8 - /usr/bin/php
    Python: 3.8.3 - /home/alexandre/anaconda3/bin/python
    Python3: 3.8.3 - /home/alexandre/anaconda3/bin/python3
    Ruby: 2.7.4 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /home/alexandre/anaconda3/bin/sqlite3
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 93.0
  Monorepos:
    Yarn Workspaces: 1.21.1
    Lerna: 4.0.0

```
</details>

**Comment by m4theushw** [comment]
I spent some time trying to find the cause of this bug, but I couldn't fully understand it yet. The most relevant finding is that `rippleRef.current` is null when the focus moves to another cell. This prevents the ripple from being stopped. I don't discard that this could be a bug with `ButtonBase` when it re-renders at the same time that the focus is changed.

https://github.com/mui-org/material-ui/blob/3f58dd9208c5aa8daed74c74d97cd63c2c35a785/packages/mui-material/src/ButtonBase/ButtonBase.js#L146

**Comment by alexfauquette** [comment]
This is definitely not related to DataGrid but Checkbox component. I created a minimal reproduction with only two checkboxes

https://codesandbox.io/s/basicbuttons-material-demo-forked-8rqgv?file=/demo.tsx

**Comment by alexfauquette** [comment]
It seems that due to the `React.useImperativeHandle` in `<TouchRipple />` the ref is called twice, and the first time with `null` https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs

If I remove the `useImperativeHandle` the ref is defined at the rerender

In `ButtonBased` I replaced `useRippleHandler` has follow:

```js
function useRippleHandler(rippleAction, eventCallback, skipRippleAction = disableTouchRipple) {
return useEventCallback((event) => {
  if (eventCallback) {
    eventCallback(event);
  }
  // If the component is rerendering this ref will be null
  console.log(rippleRef.current);
  window.setTimeout(() => {
    // Here the ref is defined
    console.log(rippleRef.current);
    const ignore = skipRippleAction;
    if (!ignore && rippleRef.current) {
      rippleRef.current[rippleAction](event);
    }
  }, 0);
  return true;
});
}
``` 

`rippleRef.current` first log is null when the focus switch from the second to the first checkbox. The `setTimeout` move the execution of the code after the render phase, and so the `rippleRef.current` is now defined. That's dirty and probably buggy, but I do not see overway to do it

@eps1lon Do you have an opinion on this issue?

**Comment by eps1lon** [comment]
>  // If the component is rerendering this ref will be null
>   console.log(rippleRef.current);

`useEventCallback` creates a callback that should be called in an event. It should never be called during rendering.
That a ref (to a component or imperative handle) is null during rendering (or rather stale) is standard React behavior.

> I don't discard that this could be a bug with ButtonBase when it re-renders at the same time that the focus is changed.

Same here. I don't think this is actually what's happening (that focus and rendering are happening in parallel).

With null-references the callsite is probably not the issue. Try to understand when the assumptions about `rippleRef` are broken i.e. consider the full (async) callstack that leads to `rippleRef.current` being null. 

In the end this comes down to creating a minimal reproducible example. Pointing at a line of code with a null-pointer exception isn't helpful.

**Comment by alexfauquette** [comment]
I tried to reduce the minimal example: https://codesandbox.io/s/basicbuttons-material-demo-forked-8rqgv?file=/demo.tsx

To break the ripple of the `<CheckBox />`, the focus must be called into a `useLayoutEffet` of another component. If we use `useEffect` it works. And the other component must be placed before the checkbox.

**Comment by eps1lon** [comment]
> I tried to reduce the minimal example: [codesandbox.io/s/basicbuttons-material-demo-forked-8rqgv?file=/demo.tsx](https://codesandbox.io/s/basicbuttons-material-demo-forked-8rqgv?file=/demo.tsx)

Thanks! Could you describe what the expected and actual behavior is and how I what the steps to reproduce are?

**Comment by alexfauquette** [comment]
## The original bug

In DataGrid, when the focus is on the checkbox selection column (see https://mui.com/x for example) pressing key up move the focus but the ripple is not removed

## How to use the minimal example

There are two elements. When the focus is set on one of them, you can switch the focus to the other one by pressing any key of your keyboard

## Expected behavior

When the focus moves from the checkbox to the input the ripple disappears. It is not the case, and by pressing multiple time a key, you will see ripple accumulation


## With Bug

https://user-images.githubusercontent.com/45398769/145874268-2f38ec23-56d5-4b1a-bd29-cef14b3b99f9.mp4

## Without Bug (by using useEffect instead of useLayoutEffect)

https://user-images.githubusercontent.com/45398769/145874359-d83781c8-900b-4748-a9c6-fbdd299d5bdc.mp4

**Comment by alexfauquette** [comment]
<table>
<tr>
	<td>A</td>
	<td>B</td>
	<td>C</td>
<tr>
	<td>
input container did unmount
TouchRipple did unmount
ButtonBase did unmount
CheckboxContainer did unmount
App did unmount

input container did mount

callback called with null rippleRef
after getFocus
  
TouchRipple did mount
ButtonBase did mount
CheckboxContainer did mount
App did mount

TouchRipple did unmount
ButtonBase did unmount
TouchRipple did mount
ButtonBase did mount
</td>
	<td>
Key Pressed

input container did unmount
TouchRipple did unmount
ButtonBase did unmount
CheckboxContainer did unmount
App did unmount

input container did mount
TouchRipple did mount
ButtonBase did mount
CheckboxContainer did mount
App did mount

before getFocus
callback called with exisiting rippleRef
after getFocus
  
TouchRipple did unmount
ButtonBase did unmount
TouchRipple did mount
ButtonBase did mount
</td>
	<td>
Key Pressed

TouchRipple did unmount
ButtonBase did unmount
CheckboxContainer did unmount
input container did unmount
App did unmount

TouchRipple did mount
ButtonBase did mount
CheckboxContainer did mount
input container did mount

before getFocus
callback called with exisiting rippleRef
after getFocus
  
App did mount

TouchRipple did unmount
ButtonBase did unmount
TouchRipple did mount
ButtonBase did mount
</td>
</table>

**Comment by m4theushw** [comment]
Could you open an issue in https://github.com/mui-org/material-ui with the minimal reproduction? I still can't understand why this bug only occurs when the `blur` event is caused by a keyboard event. In theory, the ref should also be null when the blur is caused by a click in another component, since both event listeners have the same callback. Regarding a potential solution, the diff below also works:

```diff
diff --git a/packages/mui-material/src/ButtonBase/ButtonBase.js b/packages/mui-material/src/ButtonBase/ButtonBase.js
index 2d0c5591cb..aab40880b3 100644
--- a/packages/mui-material/src/ButtonBase/ButtonBase.js
+++ b/packages/mui-material/src/ButtonBase/ButtonBase.js
@@ -336,6 +336,12 @@ const ButtonBase = React.forwardRef(function ButtonBase(inProps, ref) {
 
   const classes = useUtilityClasses(ownerState);
 
+  const handleTouchRippleRef = (el) => {
+    if (el) {
+      rippleRef.current = el;
+    }
+  };
+
   return (
     <ButtonBaseRoot
       as={ComponentProp}
@@ -363,7 +369,7 @@ const ButtonBase = React.forwardRef(function ButtonBase(inProps, ref) {
       {children}
       {enableTouchRipple ? (
         /* TouchRipple is only needed client-side, x2 boost on the server. */
-        <TouchRipple ref={rippleRef} center={centerRipple} {...TouchRippleProps} />
+        <TouchRipple ref={handleTouchRippleRef} center={centerRipple} {...TouchRippleProps} />
       ) : null}
     </ButtonBaseRoot>
   );
```

---

If you log the value of `el` above and add another log before `rippleRef.current[rippleAction](event)`, you will notice that it tries to stop the ripple before the ref has been called with the correct element, so the `null` as value. However, with a click, it stops after the ref has been called with the right element.

Changing the focus with a click:

![image](https://user-images.githubusercontent.com/42154031/146626978-c1c7d4d9-75c4-4aad-aaaf-fc6fb1ba0253.png)

Changing the focus with the keyboard:

![image](https://user-images.githubusercontent.com/42154031/146627010-f401dd52-e07f-4ee8-a86c-8141c9411ee9.png)

**Comment by alexfauquette** [comment]
I assume it is because when you click, the blur is called by the click itself, so the blur appends after the rendering of all the components. Whereas with the keyboard, it is our internal logic that cal focus, and so the blur. SO we are able to call it before all components are rendered.
