### ISSUE TITLE
Customizability of DataGrid's FilterPanel

### ISSUE THREAD

**Issue by jamintz** [mui/mui-x#3082]
### Order ID 💳

21172

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I've implemented a custom FilterPanel, however there is some further customization that I'm not sure is possible (or if it is, how to do it) based on the documentation

### The problem in depth 🔍

Specific things I'd like to be able to customize:
- Order of columns in the columns dropdown (for usability reasons I have a certain column order, however when searching for a column to filter on it'd be easier to be able to eg set it alphabetically)
- Width of operators text field (I have customized various InputComponents for the values field but for some filters with longer text it'd be nice to be able to display it all)
- Overall just documentation of what's customizable / how would be useful

### Context 🔦

Continuing to make use of MUI DataGrid, really like it – this would help us further tune it to our needs

### Your environment 🌎

"@mui/icons-material": "^5.0.4",
"@mui/lab": "^5.0.0-alpha.51",
"@mui/material": "^5.0.4",
"@mui/styles": "^5.0.1",
"@mui/x-data-grid-generator": "^5.0.0-beta.4",
"@mui/x-data-grid-pro": "^5.0.0-beta.4",

**Comment by flaviendelangle** [comment]
The filter panel is probably one of the part of the Grid where the customization will be the most important and we are fully aware of it.

Could you give me more details about which dropdown you want to sort alphabetically ?

Currently, the only way to do advanced customization would be to pass a fully custom filter panel

```tsx
<DataGrid {...otherProps} components={{ FilterPanel: MyCustomFilterPanel }} />
```

This panel could re-use internal components exported from the DataGrid. 
But you would still have to implement a lot of behaviors on your side.

**Comment by jamintz** [comment]
@flaviendelangle in particular in this example I was talking about the "columns" dropdown. The default behavior is the order of the list reflects the order of the columns in the table (including when moving columns around). This may make sense but for me personally I think it'd be nice to be able to have a preset static order (eg alphabetical). I have done a bit of customization with a FilterPanel already but was looking to see if there was potentially a way to adjust just the column dropdown without having to reimplement all the onclick etc behaviors.

**Comment by flaviendelangle** [comment]
For the order of the columns, I don't think their is a clean way of doing it right now without overriding the form.

**Comment by m4theushw** [comment]
Some actions we could take to close this issue:

> Order of columns in the columns dropdown (for usability reasons I have a certain column order, however when searching for a column to filter on it'd be easier to be able to eg set it alphabetically)

A new prop could be added to `GridFilterPanel` to allow to define the order to sort the columns. Users could set this prop through `componentsProps`. It would work like:

```tsx
<DataGrid componenetsProps={{ filterPanel: { columnsSort: 'asc' | 'desc' | undefined } }} />
```

> Width of operators text field (I have customized various InputComponents for the values field but for some filters with longer text it'd be nice to be able to display it all)

This problem was also faced in #2874. The following diff should allow the filter component to expand beyond the default 190px width.

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx b/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
index 2830239ae..61a24d56b 100644
--- a/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
+++ b/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
@@ -47,7 +47,6 @@ const GridFilterFormRoot = styled('div', {
   overridesResolver: (props, styles) => styles.filterForm,
 })(({ theme }) => ({
   display: 'flex',
-  justifyContent: 'space-around',
   padding: theme.spacing(1),
 }));
 
@@ -229,7 +228,7 @@ function GridFilterForm(props: GridFilterFormProps) {
           ))}
         </Select>
       </FormControl>
-      <FormControl variant="standard" sx={{ width: 190 }}>
+      <FormControl variant="standard" sx={{ minWidth: 190 }}>
         {currentOperator?.InputComponent ? (
           <currentOperator.InputComponent
             apiRef={apiRef}
```

> Overall just documentation of what's customizable / how would be useful

Documentation page for GridFilterPanel could be added, as well as, a paragraph in https://mui.com/components/data-grid/filtering/#create-a-custom-operator explaining how to increase the width of the filter component.
