### ISSUE TITLE
[DataGrid] Flex values below 1 cause unwanted horizontal scroll

### ISSUE THREAD

**Issue by Haaxor1689** [mui/mui-x#3091]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I would like to add a column that is always at the right end of the grid containing actions. To achieve this I've defined this column with `flex: 0.0001` (arbitrary small number). So in theory:

1. In tables without flex columns, its width fills the remaining empty space
2. In tables with flex columns, it won't use up any additional width

The problem is that in tables with flex columns I get unexpected horizontal scroll when using this column with flex lower than 1.

### Expected behavior 🤔

There shouldn't be any unwanted horizontal scroll if I have a column with flex value lower than 1.

### Steps to reproduce 🕹

Steps:

1. Create a DataGrid with multiple flex columns where one has flex value below 1

[Live demo](https://codesandbox.io/s/datagridpro-v5-quick-start-forked-id97f?file=/src/App.tsx)

### Context 🔦

I would like to have a column that is always at the right most end of the grid.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor                
    Memory: 1.90 GB / 15.92 GB
  Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Maven: 3.6.3 - C:\Projects\_Tools\apache-maven-3.6.3\bin\mvn.CMD
    pip3: 21.2.3 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    CMake: 3.15.4 - /c/Program Files/CMake/bin/cmake
    Git: 2.33.0. - /cmd/git
  Virtualization:
    Docker: 20.10.7 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.61.2 - C:\Users\betko\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD  
    Visual Studio: 16.3.29324.140 (Visual Studio Community 2019)
  Languages:
    Java: javac 11 - /c/Projects/_Tools/jdk-11/bin/javac
    Perl: 5.34.0 - C:\Program Files\Git\usr\bin\perl.EXE
    PHP: 7.4.10 - C:\Users\betko\AppData\Roaming\php-7.4.10-Win32-vc15-x64\php.EXE
    Python: 3.9.7 - /c/Python39/python
  Browsers:
    Chrome: 95.0.4638.54
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
    Internet Explorer: 11.0.19041.1202
```
</details>

### Order ID 💳 (optional)

#28342

**Comment by flaviendelangle** [comment]
https://drafts.csswg.org/css-flexbox-1/#valdef-flex-flex-grow

![image](https://user-images.githubusercontent.com/3309670/140477698-e3b3adf7-41e8-4d17-b205-635bd1c201c4.png)

According to my understanding of the CSS spec, your `columnsWithoutFlex` should not event fill the remaining space.

Right now we don't handle properly the flex values in `]0, 1[`.

**Comment by Haaxor1689** [comment]
> ![image](https://user-images.githubusercontent.com/3309670/140477698-e3b3adf7-41e8-4d17-b205-635bd1c201c4.png)

Ah yes I see. So if it were to work like css flex it should look like this: [jsfiddle](https://jsfiddle.net/s6vd1nw5/26/)

![image](https://user-images.githubusercontent.com/25706343/140521003-30dedcf1-efd6-4322-8cd0-46bd8f58d965.png)

**Comment by Haaxor1689** [comment]
Hmm and can you suggest some other solution to achieve this behavior I would like (before column pinning is implemented)?

**Comment by flaviendelangle** [comment]
If you can just set flex conditionally it works : https://codesandbox.io/s/datagridpro-v5-quick-start-forked-pokb7 

If not, the following should works but doesn't : https://codesandbox.io/s/datagridpro-v5-quick-start-forked-rb2k4
I will see if it is an easy fix.

**Comment by Haaxor1689** [comment]
Well this solution works until you resize all of the flex columns at which point it no longer sticks to the right
https://codesandbox.io/s/datagridpro-v5-quick-start-forked-p35j9?file=/src/App.tsx

**Comment by flaviendelangle** [comment]
Oh OK I think I understand what you are trying to accomplish.
I think it is to similar to the column pinning to be implemented only with the flex pattern.
The column pinning is under active development, I hope we will be able to release it a few weeks.

**Comment by Haaxor1689** [comment]
> If not, the following should works but doesn't : https://codesandbox.io/s/datagridpro-v5-quick-start-forked-rb2k4 I will see if it is an easy fix.

I feel like the problem here with flex values `1000 1000 1` is the same as was the problem with values `1 1 0.001` and it's what's causing the undesired horizontal overflow. Maybe if the resulting column widths are smaller than the pixel count it overflows?

**Comment by flaviendelangle** [comment]
> Maybe if the resulting column widths are smaller than the pixel count it overflows?

Yes our flex system probably don't like high ratio between the smallest and the biggest flex.

**Comment by Haaxor1689** [comment]
Ah it looks like when the calculated flex width of a column is smaller than it's `minWidth`, it overflows rather then making other flex columns smaller. Here you can easily see it with table with `width: 500`, two flex columns `300 200` and the second column with `minWidth: 250`.

https://codesandbox.io/s/datagridpro-v5-quick-start-forked-p35j9?file=/src/App.tsx

**Comment by flaviendelangle** [comment]
Yes I just saw it, we are not removing the `minWIdth` of the flex columns from the space to allocate between the flex columns.
So when a flex column end up with less than it's `minWidth`, we force its width to equal its minWidth but the other columns did not take that into account.

**Comment by flaviendelangle** [comment]
https://jsfiddle.net/v6khnb9o/

It is a bug, because the following example on the Grid would end up with both flex columns having the same width.

**Comment by m4theushw** [comment]
> I would like to add a column that is always at the right end of the grid containing actions.

Coming back to what the user wants to achieve, does setting `flex: 1` in any of the other columns (not the `actions`) solves the problem? 

Example: https://codesandbox.io/s/columntypesgrid-material-demo-forked-xl1q9?file=/demo.tsx

```tsx
const columns = [
  { field: "name", type: "string", flex: 1 },
  { field: "actions", ... }
]
```

**Comment by flaviendelangle** [comment]
I will create two stand-alone issue, one for fixing the min-width allocation (I have a PR coming) and another for a future handling of the cases where the flex sum is less than 1.

**Comment by Haaxor1689** [comment]
> does setting `flex: 1` in any of the other columns (not the `actions`) solves the problem?

It does until that one flex column is resized.

**Comment by m4theushw** [comment]
> It does until that one flex column is resized. 

Another solution is to add a column to fill the empty space between the last column and the actions. This new column is not resizable nor visible. See https://codesandbox.io/s/columntypesgrid-material-demo-forked-sir4r?file=/demo.tsx

```tsx
const columns = [
  { field: "name", type: "string" },
  {
    field: "filler",
    flex: 1,
    resizable: false,
    headerName: "",
    disableColumnMenu: true,
    sortable: false
  },
  { field: "actions", ... }
]
```
