### ISSUE TITLE
[DataGrid] No rendering with autoHeight + autoPageSize

### ISSUE THREAD

**Issue by ddolcimascolo** [mui/mui-x#3233]
### Current behavior 😯

The grid does not render. Weird `1-0 of XXX` in the footer

### Expected behavior 🤔

The grid renders, filling availble height (because of `autoHeight`) and showing all rows

### Steps to reproduce 🕹

Code sandbox using v5.0.1, exposing the issue: https://codesandbox.io/s/datagrid-v5-0-1-autoheight-autopagesize-9dy64?file=/src/App.tsx

Same one using v5.0.0, rendering normally: https://codesandbox.io/s/datagrid-v5-0-0-autoheight-autopagesize-working-hks4q?file=/src/App.tsx

### Context 🔦

I understand that autoHeight + autoPageSize probably can't work together (or can they?) but if that's the case, can you please just ignore autoPageSize, or log a warning or whatever? Simply failing to render is not a good user experience.

As suggested by @flaviendelangle it might be a regression of #3007 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.13 Linux Mint 20.2 (Uma)
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0

Used browser: Chrome
```
</details>

### Order ID 💳 (optional)

I have a pro plan, but don't have access to the order id right now :)

**Comment by flaviendelangle** [comment]
`autoHeight` and `autoPageSize` can't work correctly together. Or at least we did not define a clean behavior for this scenario.
I would be in favor of adding a clear warning.

**Comment by ddolcimascolo** [comment]
:+1:

**Comment by oliviertassinari** [comment]
Agree, it makes no sense to have `<DataGrid autoHeight={true} autoPageSize={true}>`. 👍 to add a warning so developers are aware that they are doing something wrong.

**Comment by Sboonny** [comment]
How do we want to warn the developers? 🤔

- [ ] make them union type, so TypeScript warn developers before the code is complied
- [ ] Add console warning if the element has both props
- [ ] Add a simple warning in the docs

**Comment by oliviertassinari** [comment]
@Sboonny I was mostly thinking of a custom prop-type rule, so not 2. but close to it.
For 3. it feels disproportionate, creating noise to the docs, it feels intuitive that both can't work together.
For 1. sure why not, but 2. sounds more important for the DX and to be careful not to slow TypeScript too much.

**Comment by Sboonny** [comment]
About making them a union, I thought it's a simple `type` but I can't do that with `interface`. 

Changing the interface to `type`, to add union require refactoring, because the interfaces are used to their full and they allow overwriting the DataGridProps props.

Am I missing a simple way to implement this? my approach is to add the type below, but that require refactoring.

```ts
type ContainerSize =
  | {
      autoHeight: boolean;
      autoPageSize: never;
    }
  | {
      autoPageSize: boolean;
      autoHeight: never;
    };
```
