### ISSUE TITLE
[docs] Migrate error documentation page

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#337]
Migrate ~https://material-ui-x.netlify.app/storybook/?path=/story/1-docs-13-error-handling--page~ https://material-ui-x.netlify.app/storybook/?path=/story/datagridpro-test-error-handling--throw-exception from Storybook to the documentation.

**Comment by cherniavskii** [comment]
The storybook is gone now, and [the data grid doesn't have an error boundary anymore](https://github.com/mui/mui-x/pull/7579)
