### ISSUE TITLE
[DataGridPro] Hide `OR` operator option from the `linkOperators` in Multi-column filtering

### ISSUE THREAD

**Issue by Beslinda** [mui/mui-x#3386]
### Order ID 💳

25719

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am using Multi-column filtering  on data grid pro but I would like to hide the `OR` option for the time being. Is there a way to do this except with styling ?

### The problem in depth 🔍

Hide GridLinkOperator.Or option from the link operators. 

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 858.14 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    npm: 7.0.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.0 - /usr/local/bin/pod
    Gradle: 6.2.2 - /usr/local/bin/gradle
    Homebrew: 3.2.11 - /usr/local/bin/brew
    pip3: 20.3.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.1 - /usr/bin/git
    Clang: 11.0.0 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
    Nginx: 1.19.5 - /usr/local/bin/nginx
  Virtualization:
    Docker: 20.10.10 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Atom: 1.58.0
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_242 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.0 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /Users/beslinda/Library/Android/sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 74.0
    Safari: 15.1
  Monorepos:
    Lerna: 4.0.0

```
</details>

**Comment by DanailH** [comment]
Hi, @Beslinda thanks for raising this. 

Yes, there is a way to remove the `OR` operator. It's done by extending the filter operators for a given type. You can check more about it here -> https://mui.com/components/data-grid/filtering/#extend-filter-operators.

**Comment by alexfauquette** [comment]
@DanailH I tried to add your explanation in the documentation, but I don't understand what do you want to override.

It seems that the "AND"/"OR" options in filter form are hardcoded

https://github.com/mui-org/material-ui-x/blob/389b9e64bec7b150763c4e23b259bd8e8814b722/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx#L200-L214

**Comment by destegabry** [comment]
Order ID 💳: 29385

I have the same issue. I'm using server side filtering and my API supports only the AND operator, thus I need to remove the OR option.

I suggest adding a prop to list the available filters, something like `gridLinkOperatorList: GridLinkOperator[]`.

**Comment by flaviendelangle** [comment]
#3497 do what you are proposing @destegabry but at the level of the FilterPanel

You could do the following:

```tsx
<DataGrid componentsProps={{ filterPanel: { linkOperators: ['and'] } }} />
```

@alexfauquette correct me if I'm wrong

**Comment by Beslinda** [comment]
Do we know approximately when this #3497  will get merged ?
