### ISSUE TITLE
[DataGrid] Select component in DataGrid column header crashes app

### ISSUE THREAD

**Issue by ETN-Tech** [mui/mui-x#3393]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I tried to implement a Select component in a column header with the column's renderHeader method but it crashes. More precisely when I unfocus from the Select menu.

When the app crashes and I get this error : "TypeError: Node.contains: Argument 1 does not implement interface Node."

### Expected behavior 🤔

The Select should display the selected value and the app should not crash.

### Steps to reproduce 🕹

Here is a stackblitz to illustrate this issue.
[https://stackblitz.com/edit/react-dls8hb?file=demo.js](https://stackblitz.com/edit/react-dls8hb?file=demo.js)

1. Click on the **'select' Button** and select an item, _it works_.
2. Click on the **Select component**, select an item and unfocus from the Select, _the app crashes_.

### Context 🔦

I want to implement a custom filter for a column in a DataGrid and want to display it in the column header.

I didn't find any other way to do this yet. If you know any other way to do this, I'll be interested.

### Your environment 🌎

I used Firefox 95.0.
<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 17.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.43)
  npmPackages:
    @emotion/react: ^11.7.0 => 11.7.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.58
    @mui/icons-material: ^5.2.1 => 5.2.1
    @mui/lab: ^5.0.0-alpha.59 => 5.0.0-alpha.59
    @mui/material: ^5.2.3 => 5.2.3
    @mui/private-theming:  5.2.2
    @mui/styled-engine:  5.2.0
    @mui/styles: ^5.2.3 => 5.2.3
    @mui/system:  5.2.2
    @mui/types:  7.1.0
    @mui/utils:  5.2.2
    @mui/x-data-grid: ^5.2.0 => 5.2.0
    @types/react:  17.0.37
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.2 => 4.5.2
```
</details>

**Comment by m4theushw** [comment]
This is a bug with the Select component. It [overrides](https://github.com/mui-org/material-ui/blob/d69931fd483609dc4d0a60ac5cf4db88644c24e6/packages/mui-material/src/Select/SelectInput.js#L311) the `target` on the `blur` event and doesn't pass a valid element. I think the same [solution](https://github.com/mui-org/material-ui/issues/24740#issuecomment-772796339) done for the `onChange` should be applied to the `onBlur`. 

Could you open a issue in https://github.com/mui-org/material-ui?

---

For now, we could fix it in the DataGrid by checking if it's a valid element before publishing the event. We've done this previously to solve the same problem when the Select is inside a cell.

```diff
diff --git a/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx b/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
index 0b8638e47..96c46ea79 100644
--- a/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
+++ b/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
@@ -102,7 +102,10 @@ function GridColumnHeaderItem(props: GridColumnHeaderItemProps) {
     (eventName: keyof GridColumnHeaderEventLookup) => (event: React.SyntheticEvent) => {
       // Ignore portal
       // See https://github.com/mui-org/material-ui-x/issues/1721
-      if (!event.currentTarget.contains(event.target as Element)) {
+      if (
+        (event.target as any).nodeType === 1 && // The target is not an element when triggered by a Select inside the column header item
+        !event.currentTarget.contains(event.target as Element)
+      ) {
         return;
       }
       apiRef.current.publishEvent(
```

**Comment by jaballogian** [comment]
I also face the same problem here https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-xmwf0?file=/src/App.js

**Comment by jaballogian** [comment]
> I also face the same problem here https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-xmwf0?file=/src/App.js Please click the filter icon (top right of the Data Grid component) to show the `Select` and `Text Field` components ![image](https://user-images.githubusercontent.com/24468466/149745896-234d654d-1189-4131-982c-07cfd27e621f.png)
> 
> The problem might come from the controlled components (the `Select` and `Text Field` components that have value and on change props) inside the header of the `Data Grid` component.
> 
> If my statement above is true, this `renderHeader` case might be similar to this case https://stackoverflow.com/questions/70164306/mui-custom-text-field-loses-focus-on-state-change but I still haven't found the answer yet.
> 
> I have tried to add `onBlur` prop for the `Select` component but still got the same issue.

for the `Text Field` component issue it has been solved using this solution https://github.com/mui-org/material-ui-x/issues/3599#issuecomment-1015009252

I tried to use the same solution to solve the `Select` component issue in `Data Grid` component header

**Comment by kacperkosinski** [comment]
I was able to fix this with stopping event propagation on `Select` component:
`onBlur={(e) => e.stopPropagation()}`

**Comment by MBilalShafi** [comment]
We recently released the Filtering on Header feature. I hope it would address your concerns regarding having out-of-the-box simple-to-use filters.
I'd appreciate your trying it out and possibly providing some feedback.
Here's the documentation link: https://mui.com/x/react-data-grid/filtering/#header-filters

**Comment by Dunky45** [comment]
> 

Bro u are the saviour of the day. Thank you so much

**Comment by Ruslan0111** [comment]
You guys saved me hours, thank you!
