### ISSUE TITLE
DataGrid header cells not scrolling in RTL containers

### ISSUE THREAD

**Issue by alimirmohammad** [mui/mui-x#3435]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When my table have several columns which do not fit in the screen, I scroll the DataGrid horizontally. The table body (its rows) will scroll fine, but the header cells do not scroll horizontally with the rows, they are fixed.

### Expected behavior 🤔

I expect when I scroll horizontally, the header cells scroll together with the rows.

### Steps to reproduce 🕹

Steps:

1. Create a container element for the DataGrid with dir attribute set to rtl
2. Create a DataGrid inside that container
3. Define as many columns that they don't fit in the screen
4. Start scrolling horizontally, the rows scroll but not the header cells

Here is a codesandbox:
https://codesandbox.io/s/modern-mountain-ldisj

### Context 🔦

I spent nearly a day on this bug. At first, I thought there is a bug on my side. After hours of struggling, and by accident I realized that in LTR layout the feature works fine, but not in RTL layout.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Hi, I had a look at this bug. It appears that we block negative scroll values to avoid strange values on ios. Then, the virtualized scroll nether update, due to negative values of RTL scroll.

https://github.com/mui-org/material-ui-x/blob/0b23cdd82d671fa7be52f9622de8cfe0ef1cd747/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx#L191-L194

To solve this issue, we should find a way to distinguish the ios case from the RTL one.

Notice that supporting RTL is still an open issue #230

**Comment by alimirmohammad** [comment]
Hi, thank you for your response. Just out of curiosity, why does the table body scrolls fine, but not the table head? The scroll direction is the same in both cases.

Is there a workaround that I can use so the table head scrolls the same as the table body?

**Comment by alexfauquette** [comment]
That's what I was looking for but I don't think so.

The rows position is provided by the native scroll. We listen at the scroll event to move the column headers. But the code I highlighted in the previous message stops the execution before the update of the column headers.

@m4theushw do you know a workaround I ignore on this topic?

**Comment by m4theushw** [comment]
We don't support RTL yet. For #230 we'll probably need to invert the logic and block positive `scrollLeft` values instead.

> Is there a workaround that I can use so the table head scrolls the same as the table body?

Unfortunately no, as @alexfauquette pointed we block negative values.

**Comment by oliviertassinari** [comment]
I have turned #230 into an umbrella issue.

For the `scrollLeft`, note that for the scroll left, there are 3 different modes in RTL, depending on the browser 😆 

https://github.com/mui-org/material-ui/blob/98c9aad08696f44976f55aa1e254d013df6c38e1/packages/mui-utils/src/scrollLeft.js#L7

**Comment by LironShirazi** [comment]
After many hours of trying a lot of things to fix it, I found a workaround for making the headers work correct with the data table of DataGrid, I just modified the direction of 2 classes to be ltr (assuming that the whole project is wrapped with RTL, in my case with 'stylis' and RTL plugin, using MUI V5).
I modified these classes via makeStyles function:
```
root: {
& .MuiDataGrid-columnsContainer {
 direction: 'ltr'
}
& .MuiDataGrid-virtualScroller {
  direction: 'ltr',
}
}
```

I hope it helps someone :)

**Comment by giladv** [comment]
@LironShirazi dude, would love to get some help on this. your snippet didn't work for me at all.

**Comment by dashty94** [comment]
Anyone yet able to fix the issue of the header cells not scrolling properly on RTL ?

**Comment by alonp-OE** [comment]
> After many hours of trying a lot of things to fix it, I found a workaround for making the headers work correct with the data table of DataGrid, I just modified the direction of 2 classes to be ltr (assuming that the whole project is wrapped with RTL, in my case with 'stylis' and RTL plugin, using MUI V5). I modified these classes via makeStyles function:
> 
> ```
> root: {
>   '& .MuiDataGrid-columnsContainer': {
>    direction: 'ltr'
>   }
>   '& .MuiDataGrid-virtualScroller': {
>     direction: 'ltr',
>   }
> }
> ```
> 
> I hope it helps someone :)

If anyone is still facing the above issue in v6, this answer works, just change columnsContainer to columnHeaders
