### ISSUE TITLE
[data-grid] How to dynamically set valueOption

### ISSUE THREAD

**Issue by kwakky1** [mui/mui-x#3528]
### Order ID 💳

b19f82197c089467ebb7cf5b7fae68a5T1JERVI6MzA3NjMsRVhQSVJZPTE2NjU2MjkwMjIwMDAsS0VZVkVSU0lPTj0x

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

how to dynamically set valueOptions in GridColDef

### The problem in depth 🔍

![image](https://user-images.githubusercontent.com/62980973/147800907-bce40756-6606-4205-8013-ca0c4899952f.png)

I want to set dynamically set valueOption because of filter

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment]
@m4theushw I think that it's about only displaying the options that are available within the filtered rows. So updating the value based on the filtering.

**Comment by cgitosh** [comment]
How do I assign valueoptions from a database? I'm retrieving data from the database and storing to this variable 
`const [Cargo, setCargo] = useState([]);`
Now I need to assign the values in 'Cargo' to valueOptions.. Note that the values include and id..

**Comment by flaviendelangle** [comment]
You can [update the column[https://codesandbox.io/s/datagridpro-v5-quick-start-forked-mmipo4?file=/src/App.tsx] with the new value options.

**Comment by chifaaa** [comment]
Hello you guys!
Can valueOptions be an array of objects?

**Comment by flaviendelangle** [comment]
> Can valueOptions be an array of objects?
Yes, see [this doc section](https://mui.com/components/data-grid/columns/#special-properties)

> And is there a way to add multiple select column?

Yes, what is preventing you from doing it ?

**Comment by chifaaa** [comment]
Hi!
First of all, thank you for your response,
Second, when i asked "Can valueOptions be an array of objects?", I meant dynamic arrays of objects that am fetching, meaning that the objects do not have value and label fields.
Third, when I asked "is there a way to add multiple select column?" I meant to ask if it is possible to have an editable column which cells contain multiple selects. I saw that there is only "singleSelect" type, so I was wondering if there is another way to do it.

**Comment by chifaaa** [comment]
> Could you give me a concrete example ? I don't see the link between the object being fetched dynamically and them not having a value and a field.
I mean that the data is already there, i can not restructure it. 
What i was trying to do is to add a new object by inserting a new row to the datagrid then entering the data, and saving. Some of the field/column types were multiple selects, the select items were an array of objects that i was getting from my database.  
Anyways i decided to enter new object using a form in a modal

**Comment by chifaaa** [comment]
> Could you give me a concrete example ? I don't see the link between the object being fetched dynamically and them not having a value and a field.


I mean that the data is already there, i can not restructure it.
What i was trying to do is to add a new object by inserting a new row to the datagrid then entering the data, and saving. Some of the field/column types were multiple selects, the select items were an array of objects that i was getting from my database.
Anyways i decided to enter new object using a form in a modal

**Comment by m4theushw** [comment]
> I want to set dynamically set valueOption because of filter

Could you confirm if https://github.com/mui/mui-x/issues/3528#issuecomment-1024950354 describes the expected behavior correctly?

> Third, when I asked "is there a way to add multiple select column?" I meant to ask if it is possible to have an editable column which cells contain multiple selects. 

Not natively, although a custom component can be created. You can upvote https://github.com/mui/mui-x/issues/4410

**Comment by flaviendelangle** [comment]
Closing this one from lack of feedbacks
