### ISSUE TITLE
[DataGrid] Text inside the cell is not truncated

### ISSUE THREAD

**Issue by igor-serzhan** [mui/mui-x#3587]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Text is not truncated with the ellipsis inside Data Grid Cell. As I see that happened after updating block model for the Cell (it was switched from `display: block` to `display: flex` in the latest v5.2.2 release.

<img width="702" alt="Screenshot 2022-01-10 at 12 39 36" src="https://user-images.githubusercontent.com/95248354/148719139-5cb2efe7-241b-44f8-80ad-d92de3db7117.png">

### Expected behavior 🤔

Text should be truncated with the ellipsis like it was in the previous releases

<img width="537" alt="Screenshot 2022-01-10 at 12 44 07" src="https://user-images.githubusercontent.com/95248354/148719320-f71b665e-db92-4f7f-ac45-1d549e6854b0.png">

### Steps to reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/datagrid-v5-2-2-truncated-text-7mc4p?file=/src/App.tsx
2. See that the text is not truncated at the first row

### Your environment 🌎

see code sandbox

### Order ID 💳 (optional)

**35653**

**Comment by m4theushw** [comment]
#3446 changed from `display: block` to `display: flex`. You can restore the old truncation by proving a custom cell renderer as below:

```tsx
const columns: GridColDef[] = [
  {
    field: "col2",
    headerName: "Column 2",
    width: 150,
    renderCell: ({ value }) => (
      <span style={{ overflow: "hidden", textOverflow: "ellipsis" }}>
        {value}
      </span>
    )
  },
];
```

Here's the updated CodeSandbox: https://codesandbox.io/s/datagrid-v5-2-2-truncated-text-forked-90bsv?file=/src/App.tsx

**Comment by igor-serzhan** [comment]
@m4theushw yep, this will restore the old behavior, but it will require updating all simple cells in project.

**Comment by m4theushw** [comment]
With a custom cell, you can restore completely the old behavior. It works for every cell.

```tsx
const CustomCell = ({ height, width, ...other }: GridCellProps) => {
  const style = {
    minWidth: width,
    maxWidth: width,
    minHeight: height,
    maxHeight: height,
    lineHeight: `${height}px`,
  };

  return <GridCell {...other} height={height} width={width} style={style} />;
};

export default function App() {
  return (
    <div style={{ height: 300, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        components={{ Cell: CustomCell }}
        sx={{
          '& .MuiDataGrid-cell': {
            display: 'block',
          },
        }}
      />
    </div>
  );
}
```

**Comment by igor-serzhan** [comment]
@m4theushw thanks. I think we can close the issue

**Comment by oliviertassinari** [comment]
I'm reopening it. It's still a regression to fix.
