### ISSUE TITLE
[DatagridPro] Using GraphQl and Apollo Graphql using pagination does not work

### ISSUE THREAD

**Issue by sbitenc** [mui/mui-x#3602]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I set up a paginated server with data and  want to display the data in the grid

When i press the > next page arrow, the page jumps to 0 (even if controlled).

It happens every-time i go to a new page.

### Expected behavior 🤔

I should be able to control pages via page prop.
When clicking next, it should move to the next page

### Steps to reproduce 🕹

Steps:

1.  Create a datagridPro where data can be undefined during searches
2. Set 
  pagination
  paginationMode="server"
  set incoming data with pagination
  OnPageChange callback

  and most importantly
  rowCount={data?.pageInfo.totalCount}

3. Observe the pagination jumping back to page one.

The reason is, because data is undefined between calls, row count is undefined and jumps the page back to 0. This is default Apollo behavior.

Could you add a fix to not change the rowCount until loading is done (if provided), or keep the last known good value.

Another alternative would be to just worn users. I lost a good few hours thinking it was a problem with my pagination call or page setting.
Cheers!

### Context 🔦

Doing a graphql with datagrid pro

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
using Brave

  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 3.1.1 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.64 
    @mui/icons-material: ^5.2.5 => 5.2.5 
    @mui/lab: ^5.0.0-alpha.64 => 5.0.0-alpha.64 
    @mui/material: ^5.2.8 => 5.2.8 
    @mui/private-theming:  5.2.3 
    @mui/styled-engine:  5.2.6 
    @mui/system:  5.2.8 
    @mui/types:  7.1.0 
    @mui/utils:  5.2.3 
    @mui/x-data-grid-pro: ^5.2.2 => 5.2.2 
    @mui/x-license-pro:  5.2.2 
    @types/react: ^17.0.38 => 17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.5.4 => 4.5.4 
```
</details>

### Order ID 💳 (optional)

#35493

**Comment by m4theushw** [comment]
I tried to create a reproduction without using Apollo or GraphQL. Could you check if [this CodeSandbox](https://codesandbox.io/s/serverpaginationgrid-material-demo-forked-xdflz?file=/demo.tsx) reproduces correctly the bug you're facing?

**Comment by sbitenc** [comment]
Hi, yeah that's exactly what it looks like, except sometimes you can move for a page or two!

**Comment by oliviertassinari** [comment]
So, is this a regression?

**Comment by flaviendelangle** [comment]
I doubt it worked at some point.
For me the behavior has always been "current page > last page" => "go to last page"
So if the user provides an empty dataset while loading, we will loose the page.
