### ISSUE TITLE
[question] Show action icons on hover

### ISSUE THREAD

**Issue by wahajStar** [mui/mui-x#3656]
### Order ID 💳

#32742

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want to implement datagridPro with action icons and action icons only appears when hover on row like Google mail functionality.

Is there any way to achieve it?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @wahajStar thanks for raising this!

Unfortunately no, not out of the box at least. You would need a dedicated column for the icons like shown here https://mui.com/components/data-grid/editing/#control-with-external-buttons
You can try and have a column without a header label, hide the actions by default and show them using CSS. You can check an example of how to do that here -> https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-euu9k?file=/demo.tsx

In addition, you can use the `getRowClassName` prop to pass in different classes for different rows if you need to differentiate them. You can find more about it here -> https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-euu9k?file=/demo.tsx

**Comment by wahajStar** [comment]
Thanks for the examples....... @DanailH I'll try this.

**Comment by wahajStar** [comment]
On mouse hover on a row can we open a popup of the height of the row and put Icons in there. width of the popup will depend on the number of icons, the popup can start at the begining of the row

**Comment by DanailH** [comment]
I imagine you can. To achieve this you can check the components `row` slot here https://mui.com/components/data-grid/components/#row. You can also check the `Cell` example below the `Row` as that one I belive showcases exactly what you need.

**Comment by Choudhary022** [comment]
Hello Folks,
         I am facing an issue with this mouse hover effect on DataGrid's row. I am using the menu inside the action's buttons. When I click on the three dots, a menu should render below to that three dots button. But it is rendering to the left side of the screen.
         
         There is no relation between the button and menu in this case. can anyone help me?
         
         
         
         project - https://stackblitz.com/edit/react-bniwyg?file=Demo.tsx

![Screenshot 2024-05-24 102830](https://github.com/mui/mui-x/assets/102318628/55476ed7-02c0-4d91-907c-2e9ba6eabc93)
![Screenshot 2024-05-24 102841](https://github.com/mui/mui-x/assets/102318628/5a532a1c-47db-493d-b9e8-ba12fc0b9f92)


`import * as React from 'react';

import {
  GridRowsProp,
  useGridApiRef,
  DataGridPro,
  GridColDef,
  gridClasses,
} from '@mui/x-data-grid-pro';
import MoreVertIcon from '@mui/icons-material/MoreVert';

import { IconButton, ListItemButton, Menu, Tooltip, Box } from '@mui/material';
import { useState } from 'react';

const rows: GridRowsProp = [
  {
    id: 1,
    name: 'akash',
  },
  {
    id: 2,
    name: 'Ajay',
  },
  {
    id: 3,
    name: 'Rohan',
  },
  {
    id: 4,
    name: 'Rana',
  },
  {
    id: 5,
    name: 'Dev',
  },
];

export default function FullFeaturedCrudGrid() {
  const apiRef = useGridApiRef();

  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);

  const handleClick = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const columns: GridColDef[] = [
    { field: 'name', headerName: 'Name', width: 180, editable: true },
    {
      field: 'actions',
      type: 'actions',
      width: 100,
      cellClassName: 'actions',
      renderCell: ({ id }) => {
        return (
          <>
            <div className="actionButton" key={id}>
              <Tooltip title={'menu'}>
                <IconButton onClick={handleClick}>
                  {' '}
                  <MoreVertIcon />
                </IconButton>
              </Tooltip>
            </div>

            <Menu
              key={'menu'}
              anchorEl={anchorEl}
              open={Boolean(anchorEl)}
              onClose={() => setAnchorEl(null)}
            >
              <ListItemButton key={1}>hi</ListItemButton>
              <ListItemButton key={2}>Hello</ListItemButton>
              <ListItemButton key={3}>Hey</ListItemButton>
            </Menu>
          </>
        );
      },
    },
  ];

  return (
    <Box
      sx={{
        '& .actionButton': {
          display: 'none',
        },
        [`& .${gridClasses.row}:hover`]: {
          '.actionButton': {
            display: 'block',
          },
        },
      }}
    >
      <DataGridPro rows={rows} columns={columns} apiRef={apiRef} />
    </Box>
  );
}
`
