### ISSUE TITLE
[DataGrid] Text alignment is wrong

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#3668]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The horizontal padding in the header is wrong:

<img width="901" alt="Screenshot 2022-01-19 at 19 14 49" src="https://user-images.githubusercontent.com/3165635/150189841-bb0936ca-a872-48f8-84ab-e6a9a51b643c.png">

https://mui.com/components/data-grid/

### Expected behavior 🤔

<img width="452" alt="Screenshot 2022-01-19 at 19 15 12" src="https://user-images.githubusercontent.com/3165635/150189916-1d02a8e2-7918-4a10-9e77-84d67ae18b32.png">

https://material.io/components/data-tables

It's done correctly in https://mui.com/components/tables/ and https://ant.design/components/table/

### Context 🔦

It was raised by a designer on https://mui.zendesk.com/agent/tickets/2094. It's also related it #1623 (about the column resize style)

### Your environment 🌎

v5.2.2

**Comment by oliviertassinari** [comment]
It's a regression introduced in v4.0.0-alpha.29.

**Comment by wahajStar** [comment]
In datagridPro I resove in theme with css...
  "&.MuiDataGrid-root .MuiDataGrid-columnHeaderTitleContainer": {padding:0}

**Comment by DanailH** [comment]
@wahajStar would you be interested in doing a PR with the fix? This looks to be solution:

```diff
--- a/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
+++ b/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
@@ -114,7 +114,6 @@ export const GridRootStyles = styled('div', {
       flex: 1,
       whiteSpace: 'nowrap',
       overflow: 'hidden',
-      padding: '0 6px',
     },
     [`& .${gridClasses.sortIcon}, & .${gridClasses.filterIcon}`]: {
       fontSize: 'inherit',
```

**Comment by wahajStar** [comment]
Hello @DanailH  Actually I am new in mui not getting PR.  
how its work?

**Comment by DanailH** [comment]
@wahajStar you can check the contribution guide for more info on how to open a PR https://github.com/mui-org/material-ui-x/blob/master/CONTRIBUTING.md

**Comment by wahajStar** [comment]
ok thanks
