### ISSUE TITLE
[RFC] Should MUI change its LTS policy? 

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#3753]
I'm starting this issue to get feedback from the community. So if you'd like to rely on LTS versions, please share your thoughts!
 
## Current LTS Policy
To provide **security fixes** https://github.com/mui-org/material-ui/security/policy  and **fix regression from upstream dependencies** (from Chrome, React, etc). 
The LTS policy covers only the previous major version, meaning the support is dropped when a newer major version is released
(e.g. v6 release sets v5 as LTS and v4 won't get any more updates).
More on: https://mui.com/getting-started/support/#supported-versions

## Motivation
In enterprise environments, version stability is an important factor, especially when planning and coordinating dependencies' upgrade efforts, or delivering internal apps that won’t have an active team continuously improving them.
An “LTS” stamp may provide confidence to users to adopt versions according to their plans.

## Proposals

Option 1. No changes, you'd rather have the team focused on the newer features.
Option 2. Keep the same policy, but guarantee support for 1-2 years.
Option 3. Add 6 months of critical bug fixes.

## Benchmark

- AG Grid: No cherry-pick. “We roll bug fixes, performance enhancements and other improvements into new releases; we don't patch, fix or in any way alter older versions.” [https://www.ag-grid.com/license-pricing.php](https://www.ag-grid.com/license-pricing.php). Proven by [https://www.npmjs.com/package/ag-grid-enterprise](https://www.npmjs.com/package/ag-grid-enterprise).
- Kendo UI: No cherry-pick. Proven by [https://www.npmjs.com/package/@progress/kendo-react-grid](https://www.npmjs.com/package/@progress/kendo-react-grid).
- Hightcharts: No cherry-pick. Proven by [https://www.highcharts.com/changelog/](https://www.highcharts.com/changelog/).
- Node.js: maintain older major versions. Proven by [https://github.com/nodejs/node/releases](https://github.com/nodejs/node/releases). Looking at the changelog in detail. They seem to focus on security patches and fixing regressions.
- PrimeNG (Angular): https://www.primefaces.org/primeng-lts-10-1-4-and-11-4-7-released-for-lts-subscribers/. You can see in their changelog, LTS releases. https://npm-stat.com/charts.html?package=primeng-lts&from=2019-01-25&to=2022-01-25.
- MUI Core: Same as Node.js

**Comment by oliviertassinari** [comment]
Here is why we do 1 so far:

1. **opportunity cost**. These y hours we spend on applying the same fix for older users are y hours we don’t spend to push the product forward.
2. **community fragmentation**. We don’t incentive developers to upgrade to the latest major (reporting bugs, asking questions, etc on the latest).

IMHO when the product is young, you want to focus on catching up with competitors, so focusing on the future.
But then, when the product I mature, it's rare that there are major bug fixes that can’t be worked around, so the value of an LTS is increasingly diminishing.

I have added a new benchmark with PrimeNG. At least to bring more examples of the different ends of the spectrum. I also had a closer look at Node, to see what kind of changes they include in the LTS. It seems to be the same kind that we already do.

**Comment by joserodolfofreitas** [comment]
We've shared this RFC with various users that had questions about this topic, and it seems there's no demand to revisit our current approach.

Conclusion: Option 1.
