### ISSUE TITLE
[DataGrid] Horizontal Scrollbar disappears when NoResultsOverlay is used and no results in filter

### ISSUE THREAD

**Issue by Anand24816** [mui/mui-x#3795]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When NoResultsOverlay is set, and no results are given due to preset filter criteria, grid does not show Horizontal Scroll bar.

### Expected behavior 🤔

DataGrid should always show Horizontal Scroll bar. Even when no result/rows, but number of columns exceeds to grid width.

### Steps to reproduce 🕹

Steps:

1. Preset the `filter` value in initialState of grid attribute
2. Load the grid with rows such that no result get rendered, and have numbers of columns with width more than available grid width.
3. No Horizontal bar is shown

https://codesandbox.io/s/fullfeatureddemo-material-demo-forked-0w92k?file=/demo.tsx:288-294

### Context 🔦

As an enterprise application, we have 18 columns to display. our users do use large monitors, but still our grid is wider and needs horizontal bar shown when necessary. 
Right now, if set filter column is around the end, user is not able to unset that filter and stuck with no result.
We use Chrome Browser.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.88 GB / 15.28 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/apra/apra-amcos-apps-distribution-frontend/node_modules/.bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Managers:
    Apt: 2.3.9 - /usr/bin/apt
    Cargo: 1.57.0 - ~/.cargo/bin/cargo
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.2.0 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
  Virtualization:
    Docker: 20.10.12 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
  IDEs:
    Nano: 5.6.1 - /usr/bin/nano
    VSCode: 1.63.2 - /snap/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Java: 1.8.0_312 - /usr/bin/javac
    Perl: 5.32.1 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.9.7 - /usr/bin/python3
    Rust: 1.57.0 - /home/anand/.cargo/bin/rustc
  Databases:
    SQLite: 3.32.2 - /home/anand/Android/Sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0

</details>

### Order ID 💳 (optional)

28914

**Comment by m4theushw** [comment]
@cherniavskii I can see the horizontal scrollbar in both examples. This bug could be related to #3558.

**Comment by cherniavskii** [comment]
> I can see the horizontal scrollbar in both examples

Yes, depending on the OS you might see the scrollbar, but you can't scroll the grid horizontally with a trackpad (or with a mouse that supports horizontal scroll). I've added videos to my previous comment to show the problem

**Comment by m4theushw** [comment]
I managed to reproduce using the mobile mode. We miss setting `minHeight=100%` to the content div in DataGrid. In DataGridPro I added this style because of the column pinning but it seems that both components need it, so makes sense to move it to `useGridVirtualScroller`.

https://github.com/mui-org/material-ui-x/blob/8c1fcc7f4049313807d4141095b32106c5c22ce0/packages/grid/x-data-grid-pro/src/DataGridProVirtualScroller.tsx#L202-L204

DataGrid:

<img width="500" src="https://user-images.githubusercontent.com/42154031/152174132-93e0c6ad-84d3-49f7-9fd4-0715d04ddc4e.png" alt="image" style="max-width: 100%;">

DataGridPro:

<img width="500" src="https://user-images.githubusercontent.com/42154031/152174348-07ef6e2a-60e3-44ed-b5ff-311b4aecacb6.png" alt="image" style="max-width: 100%;">

**Comment by cherniavskii** [comment]
@m4theushw Nice!
I'll open a PR

**Comment by Anand24816** [comment]
Thanks So much for all the help team.
We do use DataGridPro.
Horizontal scrolling not working was consistent when I set  `NoResultsOverlay` , and _intermittent_ when pre-set filter results in no result.

**Comment by cherniavskii** [comment]
@Anand24816 Thanks, I can reproduce it with `DataGridPro` and custom `NoResultsOverlay` component:
https://codesandbox.io/s/fullfeatureddemo-material-demo-forked-0w92k?file=/demo.tsx:288-294

**Comment by cherniavskii** [comment]
@m4theushw I opened a PR on that - IMHO we can improve it by not making users to use `GridOverlay` - https://github.com/mui/mui-x/pull/3832
