### ISSUE TITLE
onCellEnter, onCellLeave, onRowEnter, and onRowLeave props for Data Grid and Data Grid Pro components

### ISSUE THREAD

**Issue by jaballogian** [mui/mui-x#3799]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I saw that there were no `onCellEnter`, `onCellLeave`, `onRowEnter`, and `onRowLeave` props for `Data Grid` and `Data Grid Pro` components https://mui.com/api/data-grid/data-grid-pro/.

Meanwhile, in the previous version of Material UI (Material UI v4), the props were available https://v4.mui.com/api/data-grid/data-grid-pro/.

### Examples 🌈

https://v4.mui.com/api/data-grid/data-grid-pro/

### Motivation 🔦

I'm creating an edit and delete rows feature by using the edit and delete icons that only appear if the user hovers the row inside the `Data Grid`/`Data Grid Pro` component.

Here was the sample I made by using the `Data Grid Pro` component from Material UI v4 (before Material UI v5 was launched).

![Screenshot (50)](https://user-images.githubusercontent.com/24468466/151769788-2223f61a-6668-4eac-828d-c023e370edba.png)

This can be achieved by:
1. adding an action column at the last column that renders edit and delete icons,
2. adding `onRowEnter` and `onRowLeave` props to the `Data Grid Pro` component to control which row is hovered.

Here is the demo: https://codesandbox.io/s/data-grid-material-ui-c01c8?file=/src/App.js

But there is a drawback to this approach. When the user decreases the width of the browser, the action column could be hidden as seen in the image below.

![Screenshot (51)](https://user-images.githubusercontent.com/24468466/151769797-0bf91646-28c5-4334-85a4-d9ff26e84fe7.png)

Now, I'm using Material UI v5 and I want to create a similar feature for another dashboard.

The specification is to show edit and delete icons for the hovered row but not by adding a new column (not adding an action column). I found the example for a private dashboard here.

![Screenshot (49)](https://user-images.githubusercontent.com/24468466/151770974-c282536d-8d6b-4428-993b-fc3b5fa4d80b.png)

So if the user decreases the width of the browser, the edit and delete icons wouldn't be hidden instead it would hide the row as seen in the image below.

![Screenshot (52)](https://user-images.githubusercontent.com/24468466/151771149-065c83e6-cd0d-4dd4-98fd-c84c4acc0b86.png)

![Screenshot (54)](https://user-images.githubusercontent.com/24468466/151771367-d9d2457f-574d-4c25-a5b3-f4ea9cc362d5.png)

So how could I do it with the `Data Grid`/`Data Grid Pro` component from Material UI v5?

### Order ID 💳 (optional)

29446

**Comment by flaviendelangle** [comment]
You can find the new approach [here](https://mui.com/components/data-grid/migration-v4/#removed-props)

We removed those listeners for performances reasons, but you can add them can through the `componentsProps` prop if you need them.

**Comment by jaballogian** [comment]
> You can find the new approach [here](https://mui.com/components/data-grid/migration-v4/#removed-props)
> 
> We removed those listeners for performances reasons, but you can add them can through the `componentsProps` prop if you need them.

Wow great, you're right.
I made it https://codesandbox.io/s/learn-mui-data-grid-hover-row-367vh?file=/demo.js
Thank you.

**Comment by jaballogian** [comment]
> You can find the new approach [here](https://mui.com/components/data-grid/migration-v4/#removed-props)
> 
> We removed those listeners for performances reasons, but you can add them can through the `componentsProps` prop if you need them.

Wow great, you're right.
I made it https://codesandbox.io/s/learn-mui-data-grid-hover-row-367vh?file=/demo.js but I found a drawback.

From my demo above, if we hover our mouse cursor to the `Popper` component, the `Popper` component would fade in and out consecutively. This is not the condition I want.
![image](https://user-images.githubusercontent.com/24468466/151986680-d71ce718-4f9d-47b4-b7e1-aad846eb1b23.png)

I think it happens because:
1. when we enter the `Popper` component, the `onMouseLeave` event from the row is triggered -> this will close the `Popper` component
2. the `Popper` component closes, so our mouse cursor directly hovers the row -> this will trigger `onMouseEnter` event from the row
3. the `onMouseEnter` event from the row will show the `Popper` component
4. back to step 1

If I delete the `onMouseLeave` event from the row, the `Popper` component would stay there forever. This is also not the condition I want.

So now my question is how to make the `Popper` component wouldn't fade in and out consecutively?

**Comment by jaballogian** [comment]
> [This kind of work](https://codesandbox.io/s/learn-mui-data-grid-hover-row-forked-1txi4) You can probably do better by playing with the events but it's not MUI specific 👍

Amazing 👍🏻

Sorry that I forgot to mention something.
After I tested it, I found that the `Popper` component is rendered on top of the `Data Grid` component.
When our mouse cursor hovered the row that was not fully shown, the `Popper` component was shown like these images below.
![Screenshot (57)](https://user-images.githubusercontent.com/24468466/152084513-be7775ca-5f52-4935-a966-7c97cdd7da39.png)
![Screenshot (58)](https://user-images.githubusercontent.com/24468466/152084518-92118769-47cc-4912-b4f3-ef70305d257c.png)

I've tried to add the `disablePortal={true}` prop to the `Popper` component but it would make the `Popper` component rendered outside the row like this image below.
![Screenshot (59)](https://user-images.githubusercontent.com/24468466/152085153-11e81497-d19b-48eb-8836-029f02dff227.png)

I also have tried to change the `zIndex` prop for the column header (became 1000), the row (became 10), and the pagination container (became 1000) of the `Data Grid` component also changed the `zIndex` prop of the `Popper` component (became 100) but still the `Popper` component was rendered on top of the `Data Grid` component like this image below.
![Screenshot (60)](https://user-images.githubusercontent.com/24468466/152085503-de819f26-048b-4aa9-898c-81c84ffd6646.png)

What should I do to make the `Popper` component rendered on the top of the row but still inside the `Data Grid` component like this image below?
![Screenshot (61)](https://user-images.githubusercontent.com/24468466/152085710-43beb550-e679-4d74-bc7a-8c1a180fb8d2.png)

Here is the updated demo https://codesandbox.io/s/learn-mui-data-grid-hover-row-367vh?file=/Demo2.jsx

**Comment by jaballogian** [comment]
Great. I could make it using the column pinning feature here https://codesandbox.io/s/learn-mui-data-grid-column-pinning-gzgn0?file=/demo.js
![Screenshot (69)](https://user-images.githubusercontent.com/24468466/152726674-42e625b2-1177-4c61-8c7f-b3c35145d21e.png)
