### ISSUE TITLE
[DataGrid] CSV export does not work for the `Commodity` and `Employee` data sets `country` column

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#3806]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The `valueFormatter` of a `singleSelect` column can return an object. It is encourage to return one with two properties: value and label such that it works well with `Select` component.

In such case, the csv export display `[object Object]` see [the demo with single select field](https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-3hsfw?file=/demo.js)
```csv
Name,Rating,Country,Created on,Is admin?
George Edwards,4,[object Object],12/3/2021,true
Ruth Simmons,2,[object Object],12/20/2021,true
Barbara Greer,5,[object Object],11/22/2021,false
Daisy Morgan,2,[object Object],1/24/2022,true
```

### Expected behavior 🤔

According to the typescript, `valueFormatter` return type is 
```ts
GridCellValue = string | number | boolean | Date | null | undefined | object; 
```

I propose to add a `valueExportFormatter` which return string. The reason is that `valueFormatter` is made for providing data to a React component, which is more flexible than providing data to a csv file with can only handle string

### Steps to reproduce 🕹

Steps:

1. go to the codesandbox https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-3hsfw?file=/demo.js
2. export csv
3. country column contains `[object Object]`

**Comment by DanailH** [comment]
Nice catch! I'll take this one.

**Comment by m4theushw** [comment]
In the example you gave the "Country" column has a custom cell renderer. As explained in the [docs](https://mui.com/components/data-grid/export/#csv-export) (search for "Exported cells") a `valueFormatter` should also be provided in these cases to avoid exporting the field as "[object]". In this context I don't see a real use case for adding the new formatter prop. I would first fix the generator to add a `valueFormatter` in all columns that have a `renderCell`.

**Comment by alexfauquette** [comment]
My bad I made a confusion when reading singleSelect operators.

I thought it was possible for `valueFormatter` to return the object `{value, label}`. But what appends, is that if `valueFormatter` is defined, single select use objects `{value, label: valueFormatter(value)}` 

Maybe we should modify the typescript definition of `valueFormatter`  to remove `object` from the possible output types.
```ts
type GridCellValue = string | number | boolean | Date | null | undefined | object;
```

https://github.com/alexfauquette/material-ui-x/blob/typo-fixing/packages/grid/_modules_/grid/models/colDef/gridColDef.ts#L149:L154

**Comment by DanailH** [comment]
Let's keep this PR for now. I'll check the demos and fix them.

**Comment by m4theushw** [comment]
> Maybe we should modify the typescript definition of valueFormatter to remove object from the possible output types.

I don't think so. If we remove `object` users can't have a field with object values. It accepts `object` because usually there will be a custom cell renderer to convert from object to the desired presentation.
