### ISSUE TITLE
[DataGridPro] Clicking 'Delete' in filtering panel to remove an applied filter shifts the view to the top of the page

### ISSUE THREAD

**Issue by monicagavril** [mui/mui-x#3809]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Clicking 'Delete' in filtering panel to remove an applied filter shifts the view to the top of the page

https://user-images.githubusercontent.com/98810752/151972725-5dbd15cd-4103-45c9-9c30-0b151244c19c.mp4

### Expected behavior 🤔

Clicking 'Delete' in filtering panel removes an applied filter and view remains on filtering panel

### Steps to reproduce 🕹

Steps:

1. Open [live example](https://codesandbox.io/s/multifilteringgrid-material-demo-forked-x3l5r?file=/demo.tsx)
2. Scroll to the bottom of the page
3. Click 'Filters' to open the filtering panel
4. Click 'X' (Delete) button to remove the filter on column Quantity
5. View jumps to the top of the page

### Context 🔦

We use grids in a view with 2 sections expanded, first containing a form, second a grid. Deleting a filter jumps to the top of the page and the user has to scroll back to see the result of his action, which affects negatively the user experience.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
  npmPackages:
    @emotion/react: ^11.5.0 => 11.5.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/base: ^5.0.0-alpha.67 => 5.0.0-alpha.67
    @mui/core:  5.0.0-alpha.54
    @mui/icons-material: ^5.1.0 => 5.1.0
    @mui/lab: ^5.0.0-alpha.54 => 5.0.0-alpha.54
    @mui/material: ^5.1.0 => 5.1.0
    @mui/private-theming:  5.1.0
    @mui/styled-engine:  5.1.0
    @mui/styles: ^5.1.0 => 5.1.0
    @mui/system:  5.1.0
    @mui/types:  7.1.0
    @mui/utils:  5.1.0
    @mui/x-data-grid-pro: ^5.4.0 => 5.4.0
    @mui/x-license-pro:  5.4.0
    @types/react: ^17.0.0 => 17.0.5
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.1.2 => 4.2.4
```
</details>
Browser: 

- Google Chrome Version 97.0.4692.99 (Official Build) (64-bit)

- Microsoft Edge Version 97.0.1072.76 (Official build) (64-bit)

### Order ID 💳 (optional)

#32346

**Comment by m4theushw** [comment]
I can also reproduce it in https://mui.com/components/data-grid/filtering/.

By adding a breakpoint to the call to `valueRef?.current?.focus` I noticed that, by the time we try to focus the input, the panel is positioned at the top of the page.

https://github.com/mui-org/material-ui-x/blob/1218fb40689f9425ca3ebd51747ba933e419c238/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx#L163

<img width="500" src="https://user-images.githubusercontent.com/42154031/152551028-7a084478-24be-4acd-89f8-f44dbfb0e9d3.png" alt="image" style="max-width: 100%;">
