### ISSUE TITLE
[DataGrid] with editMode="row" when edit finishes faster than current row fetch, it causes error.

### ISSUE THREAD

**Issue by hahmjt** [mui/mui-x#3819]
https://github.com/mui-org/material-ui-x/blob/b249cbdc617ff8f5a963d7b493875e8a3f331a7d/packages/grid/_modules_/grid/hooks/features/editRows/useGridRowEditing.ts#L149-L155

![image](https://user-images.githubusercontent.com/1548763/152149759-a046e897-d09e-4a13-b29f-34fbd5b25b7a.png)

Compiled Code for reference
![image](https://user-images.githubusercontent.com/1548763/152150646-deb40a09-0840-4824-8cea-6a36cb437698.png)

It seems like while using editMode="row", the row in editing mode (current) seems to be determined via a Promise, but if you finish editing before the Promise completes, the **r** value become undefined, hence causing this error.

I am a newbie at Typescript/React etc... please let me know if I made any mistake. Thanks

**Comment by m4theushw** [comment]
> It seems like while using editMode="row", the row in editing mode (current) seems to be determined via a Promise, but if you finish editing before the Promise completes, the r value become undefined, hence causing this error.

Could you detail more which steps I should do to reproduce the bug? If you could also provide a live example it would be even better. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point.

**Comment by CrazyUba** [comment]
Hi, 
I have the same issue. My source-code example to reproduce the error:
`https://github.com/CrazyUba/datagridprotest/blob/main/DataGridProTest.js` 

To reproduce:
1. Click on the button "Get Data"
2. Double-Click into the cell with the value 'Test'

Success-Case:
3. Change the value (e.g. to 'Tests' (add the character 's'))
4. Make a pause (e.g. 1 or 2 seconds)
5. Press the ENTER-Key => Result: OK. Cell-value has been changed, no error.

Error-Case:
3. Change the value (e.g. to 'Tests' (add the character 's'))
4. Press the ENTER-Key immediatelly after 's' has been pressed (no pause)  => Result: ERROR. Cell-value has not been changed. An error occured (the same as described above):
"Uncaught TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>)"

Thanks for your support.
Kind regards
Uli

**Comment by SpainTrain** [comment]
I can corroborate that I am seeing this in my project (including the described behavior that if you wait long enough, the error doesn't throw).  It is a private repo, but it is a personal project and am happy to add mui-x maintainers if helpful.  Thanks!

**Comment by m4theushw** [comment]
@CrazyUba Thanks for providing a reproduction. I noticed that this is the same bug reported in #3729 so I'm closing it. #3825 already fixed it both for cell editing as for row editing. Here's a CodeSandbox with the fix: https://codesandbox.io/s/rxbs3?file=/demo.js

**Comment by CrazyUba** [comment]
Thank you all, I'm glad to read about the fix. Thank you for the informations and thank you very much for your support. 
One stupid question (sorry, I'm not very familiar with github): How can I get the fix? It's not urgent, so just waiting for @mui/x-data-grid-pro version 5.6 to install it via npm? Otherwise, to learn the handling with github: Can I install the current commited version via npm?

**Comment by m4theushw** [comment]
@CrazyUba You can open the CodeSandbox above and copy the URL of the `@mui/x-data-grid` dependency in the `package.json`. If you want `@mui/x-data-grid-pro` only change the last part of the URL.
