### ISSUE TITLE
[DataGrid] Customize Column drag & drop Cursor/Icon

### ISSUE THREAD

**Issue by shadiramadan** [mui/mui-x#3823]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I struggled taking a screenshot of this but this is a very low priority request to allow the ability to customize the drag & drop cursor/icon browsers show.

### Examples 🌈

On chrome you can see a green/white plus sign when dragging a column.
https://mui.com/components/data-grid/columns/#resizing

### Motivation 🔦

With custom themeing it would help for the UI to be consistent and configurable where possible.

### Order ID 💳 (optional)

#23657

**Comment by flaviendelangle** [comment]
Could you give me a screenshot of the icon you are talking about ?
I'm not sure to fully understand.

**Comment by shadiramadan** [comment]
![image](https://user-images.githubusercontent.com/875944/154701031-be22f9fa-4c7e-4e93-af04-528175350232.png)

@flaviendelangle this green/white plus sign.

**Comment by shadiramadan** [comment]
I had to take a video and screenshot the video lol.
