### ISSUE TITLE
[question] I am using Material-UI DataGrid Pro, and customizing the DataGrid component. It was working the last few weeks. And, all of a sudden I am getting the watermark that shows "Invalid License Key". I need help fixing this. 

### ISSUE THREAD

**Issue by kc108** [mui/mui-x#3824]
### Order ID 💳

#35166

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have 2 separate components that use Material-UI I am unable to removed the "Invalid License" key. It was working fine for weeks, and I have not changed or installed anything new since it stopped working. Can someone please help me solve this?

### Your environment 🌎

  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)

**Comment by flaviendelangle** [comment]
Hi,
We did not touche anything on the license checking script for months.
Did the error began after an update of the grid ?
