### ISSUE TITLE
[question] NextJS Upgrade Grid to v5 using MUI V4 Issue

### ISSUE THREAD

**Issue by socramm9** [mui/mui-x#3828]
### Order ID 💳

#26327

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I want to upgrade to v5 so that I can use column pinning. The Issue is that I don't want to spend a lot of time upgrading my project to use v5 so I followed this guid [Using MUI X v5 with MUI Core v4](https://mui.com/components/data-grid/migration-v4/#using-mui-x-v5-with-mui-core-v4)

After doing so I get following error message on some Pages: `Warning: Prop `className` did not match. Server:`

I created a simplified version to reproduce the issue. Here is a step by step guide:

1. `git clone https://github.com/socramm9/mui-grid-upgrade.git`
2. `npm i && npm run dev`
3. open `localhost:3000`
4. You now should be redirected to `/login`. It should look like this:
![Bildschirmfoto 2022-02-03 um 12 19 09](https://user-images.githubusercontent.com/52098754/152333578-5cbf8d3e-2b35-4b99-b924-74c8fa850a0e.png)
5. But now if the page is reloaded, this happens:
![Bildschirmfoto 2022-02-03 um 12 19 17](https://user-images.githubusercontent.com/52098754/152333767-267aa5e5-4a66-48f7-ac3c-46121c669eab.png)

Steps mentioned in [Using MUI X v5 with MUI Core v4](https://mui.com/components/data-grid/migration-v4/#using-mui-x-v5-with-mui-core-v4) can be found under `./context/AppTheme/AppThemeProvider.tsx`

I hope that I did everything right. 
Thanks for the Support.

EDIT:
I Added a new brach named `working` to show a working example without v5 
https://github.com/socramm9/mui-grid-upgrade/tree/working
 
### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.2
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.76
    Firefox: 92.0
    Safari: 15.3
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.67 
    @mui/material: ^5.4.0 => 5.4.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/system:  5.4.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid-pro: 5.4.0 => 5.4.0 
    @mui/x-license-pro:  5.4.0 
    @types/react: ^17.0.5 => 17.0.8 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: ^4.2.2 => 4.3.2 
```
</details>

**Comment by cherniavskii** [comment]
Hey @socramm9 
I've created a fork of your repo in CodeSandbox: https://codesandbox.io/s/stupefied-meninsky-rtbgk
I've cleaned package.json a bit removing unused dependencies.

I wasn't able to reproduce the issue with `className` though.
![Screenshot 2022-02-07 at 11 41 55](https://user-images.githubusercontent.com/13808724/152772870-36780bde-c0eb-4cfc-b353-976bea549714.png)

Also, this example doesn't seem to be using `DataGridPro`. Did you experience any specific issue with data grid?

**Comment by socramm9** [comment]
Hey @cherniavskii, thanks for your help.

I also could not reproduce it directly in CodeSandbox it seams it only happens running locally.
> Also, this example doesn't seem to be using DataGridPro. Did you experience any specific issue with data grid?
Actually not only Styles from MUI V4 seems to missing. 

In the [Using MUI X v5 with MUI Core v4](https://mui.com/components/data-grid/migration-v4/#using-mui-x-v5-with-mui-core-v4) guide is following mentioned:
<img width="623" alt="Bildschirmfoto 2022-02-07 um 13 48 19" src="https://user-images.githubusercontent.com/52098754/152791079-cfc7d3ab-a1ab-46e1-8844-f445478acb81.png">

Non-MUI elements will lose their styles if not wrapped with something like box. But in my case also native MUI Elements from V4 are losing their styles. So I am not sure If the issue is related or I understood it wrong. 

I created a video Debugging my project using the latest version of my master breach. Sorry if It is a little bit slow: 
https://share.icloud.com/photos/0a1_3SbYy5Ax0kUf_dQXL56lw

The issue only occurs by navigating to `/login` directly if navigated to another site and redirected to `/login` the issue does not occur. 

If you also don't have an Idea how to fix this Problem or can Reproduce it, I will just upgrade to V5. I think in the time that I lost trying not to upgrade to V5 I could have upgrade to V5 2 times already. haha

**Comment by cherniavskii** [comment]
I've uncommented v5 styling in your demo and I think I can reproduce it now consistently:
https://codesandbox.io/s/divine-http-yswth?file=/pages/login/index.tsx

**Comment by cherniavskii** [comment]
>  I think in the time that I lost trying not to upgrade to V5 I could have upgrade to V5 2 times already. haha

I you can upgrade to v5 - go for it!

**Comment by socramm9** [comment]
Yes then I will try to upgrade to V5 thanks for your help
