### ISSUE TITLE
DOMnesting validation

### ISSUE THREAD

**Issue by zprpic** [mui/mui-x#3875]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I have used 2 sibling Pagination components in order to create a specific layout where I have click Pages with Arrows on the right and a normal Pagination menu on the left...

To fix the console error, I have tried nesting them inside various <table> elements, but there is always a new error with the nesting...

There needs to be a way to validate DOM nesting in this specific case.

### Examples 🌈

Current code and problem:

```
import {
    Pagination as MUIPagination,
    PaginationItem,
    TablePagination as MUITablePagination,
} from '@mui/material';

 return (
        <div className={PaginationStyles.pagination_container}>
        <MUITablePagination/>
        <Pagination/>
        </div>
             )
...

export default Pagination;
...
import {
    DataGrid as MUIDataGrid,
}
<div>
<MUIDataGrid components={{Pagination: Pagination}}/>
</div>
```
```
Warning: validateDOMNesting(...): <td> cannot appear as a child of <div>.
```

**Comment by cherniavskii** [comment]
Looks like it's not related to `DataGrid`.
Passing `component="div"` to `TablePagination` should solve the issue - see how it's used in this example: https://mui.com/components/tables/#sorting-amp-selecting

Feel free to open a new issue **with minimal reproduction example** if you believe there's an issue with `DataGrid` component.
