### ISSUE TITLE
Menu items in "Action" columns may be open simultaneously for several rows

### ISSUE THREAD

**Issue by trivli** [mui/mui-x#3876]
It should be possible to have only one "context"/action menu open at the time.

This is an image to show the issue (from https://mui.com/components/data-grid/columns/)

![image](https://user-images.githubusercontent.com/15999878/152747863-1b1178f3-3f38-4990-8058-2f33c8a809d3.png)

**Comment by cherniavskii** [comment]
Hey @trivli 
I cannot reproduce the state visible on your screenshot:

https://user-images.githubusercontent.com/13808724/152783424-6def609b-20a5-495b-82ff-ad41a811e4f1.mov

Can you share your system/browser details?

**Comment by m4theushw** [comment]
This was fixed by #3489.

Could you also share a video? I can't reproduce it in https://mui.com/components/data-grid/columns/.

**Comment by trivli** [comment]
Did not see #3489 when I wrote my issue. Will update our app and try again.
