### ISSUE TITLE
[DataGridPro] Wrong column is pinned when `checkboxSelection` is used

### ISSUE THREAD

**Issue by danra2** [mui/mui-x#3885]
### Order ID 💳

32640

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm running into a few issues with trying to pin a data column to either the right or the left. I have reviewed the documentation for such and have implemented the methods. I see that with the alert, the column is pinned in theory, however the data grid does not reflect this pinning. 

https://codesandbox.io/s/0dicv?file=/demo.js
^Demo I've implemented. 

https://codesandbox.io/s/pe8fh?file=/demo.js
^Also tried this implementation to no avail. 

```
<DataGridPro
  rows={rows}
  columns={columns}
  initialState={{ pinnedColumns: { left: ['store'], right: ['actions'] } }}
/>
```

I've also tried enabling the field to be pinnable via:
```
  {
    field: 'store',
    headerName: 'Store',
    editable: true,
    pinnable: true,
    fixed: 'right',
    sortable: true,
    width: 150,
    filterable: true,
    disableColumnMenu: false,
  },
```
DataGrid:
```
      <DataGridPro
          disableSelectionOnClick
          checkboxSelection
          editMode="row"
          pinnedColumns={pinnedColumns}
          onPinnedColumnsChange={handlePinnedColumnsChange}
          columns={columns}
          rows={rows}
          apiRef={apiRef}
          pagination
          pageSize={100}
        >
        </DataGridPro>
```

I'm running a editable datagrid very similar to this example:
https://codesandbox.io/s/8b940?file=/demo.js

*Another question is that I have changed the type of one of my input fields to "number", and while it does only accept numbers and up and down arrows do in fact change the count, it doesn't show the arrow option on the GUI that allows people to click up or down to decrease or increase the value. The arrows do not show for some reason?

### Your environment 🌎

<details>
System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.21.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Not Found
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @emotion/react: ^11.4.1 => 11.7.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/base:  5.0.0-alpha.65 
    @mui/core:  5.0.0-alpha.47 
    @mui/icons-material: ^5.0.0 => 5.3.0 
    @mui/lab: ^5.0.0-alpha.47 => 5.0.0-alpha.47 
    @mui/material: ^5.0.0 => 5.3.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/styles: ^5.0.0 => 5.0.0 
    @mui/system:  5.3.0 
    @mui/types:  7.1.0 
    @mui/utils: ^5.0.0 => 5.3.0 
    @mui/x-data-grid: ^5.0.0-beta.1 => 5.0.0-beta.1 
    @mui/x-data-grid-generator:  5.2.2 
    @mui/x-data-grid-pro: ^5.0.1 => 5.0.1 
    @mui/x-license-pro:  5.0.1 
    @types/react:  17.0.14 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.3.5 => 4.3.5 
</details>

**Comment by danra2** [comment]
Sorry about that, that was the example codesandbox from the documentation. 
Here is my custom codesandbox for my datagrid. Injecting the column pinning inside the datagrid pops doesn't seem to have the desired effect, but it does show when I call to see if any columns are pinned. 
https://codesandbox.io/s/controlpinnedcolumns-material-demo-forked-f89vc?file=/demo.js

**Comment by danra2** [comment]
Okay now it's working including the arrows. My guess is that I need to upgrade my dependencies. lol

**Comment by m4theushw** [comment]
Here's a simplified reproduction: https://codesandbox.io/s/basiccolumnpinning-material-demo-forked-syfy5?file=/demo.tsx

When `checkboxSelection` is present it's pinning the checkbox instead of the specified column. It started after #3676.

For now you can use:

```tsx
import { GRID_CHECKBOX_SELECTION_COL_DEF } from '@mui/x-data-grid-pro';

initialState={{
  pinnedColumns: {
    left: [GRID_CHECKBOX_SELECTION_COL_DEF.field, "name"],
    right: ["actions"]
  }
}}
```

---

> Another question is that I have changed the type of one of my input fields to "number", and while it does only accept numbers and up and down arrows do in fact change the count, it doesn't show the arrow option on the GUI that allows people to click up or down to decrease or increase the value. The arrows do not show for some reason?

It could the browser you're using. In Chrome I see the arrows.

![image](https://user-images.githubusercontent.com/42154031/152833864-ea808960-ffd8-497a-8b7d-cc852902fecd.png)

**Comment by danra2** [comment]
Yep that seems to work, all problems are fixed with a version upgrade on datagrid + your suggestion with the work around. 
https://codesandbox.io/s/controlpinnedcolumns-material-demo-forked-f89vc?file=/demo.js

I did have one last question in terms of serverside persistence. After a cell has been edited / save has been clicked, I would like to persist the data across the original state so that I can search it. The snackbar for some reason doesn't show up, I'm not getting errors, but I don't know if it's actually persistencing my changes to the original data. 

https://codesandbox.io/s/b6t0q?file=/demo.js

**Comment by m4theushw** [comment]
I'm reopening because there's a bug to fix here.

**Comment by danra2** [comment]
So both the fix and the work around don't seem to be compatible with safari? In safari the column headers are the only things being pinned, the fields themselves / data rows are not pinned, only the headers.
