### ISSUE TITLE
[DataGrid] ID selection error on replacing rows

### ISSUE THREAD

**Issue by RunRanger** [mui/mui-x#3888]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have several records that are fed into the DataGrid table as rows depending on the set selection.

If one or more rows were selected in the DataGrid table and then the data of the rows was replaced by completely new set of data with new ids, the error message appears that it can no longer find the ID. This also happens when the selection is cleared. I assume then that a race condition occurs.

`Error in /turbo_modules/@mui/x-data-grid@5.3.0/index-cjs.js (15:197901)
No row with id mui/material-ui#2 found`

When all rows are selected by the header-checkbox-selection, onSelectionModelChange intervenes and clears the selection.

### Expected behavior 🤔

Deselecting the rows and onSelectionModelChange should be called when the row-data is changed should also happen if not all rows are selected via the header-checkbox.

### Steps to reproduce 🕹

https://stackblitz.com/edit/react-znbzu5?file=demo.tsx

Steps:

1. select several rows
2. update all rows (override all rows with new rows with new ids)
3. error appears

For comparison:
1. select all rows by using the checkbox of the header-row
2. update all rows (override all rows with new rows with new ids)
3. selection is cleared successfully

### Context 🔦

I have a large number of people who belong to different groups.
Depending on which group is currently selected, the persons of the respective group should be selected in the data grid.

The filter option is not a good option here, as the user usually only needs 1-2 groups and selecting via the filters makes the UX more difficult.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
   "@mui/x-data-grid": "^5.3.0"
   "@mui/material": "^5.3.1"

   Chrome Version 97.0.4692.99 (Offizieller Build) (64-Bit)
</details>

**Comment by flaviendelangle** [comment]
@cherniavskii did you reproduce the error on the latest version ?
For me it is no longer crashing.

**Comment by cherniavskii** [comment]
@flaviendelangle Right, it's fixed in v5.4.0 and later
