### ISSUE TITLE
[RFC] Print and CSV have same options but different behavior

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#3904]
## The current API 

To select exported columns, developers can use 
- `printOptions.fields` / `csvOptions.fields`
- `printOptions.allColumns` / `csvOptions.allColumns`
- `colDef.disableExport`

And the doc for [csv](https://mui.com/components/data-grid/export/#custom-exported-content) and [print](https://mui.com/components/data-grid/export/#custom-exported-content-2) are the same

## The problem

The way these options are applied is different for print and CSV

### CSV rules

if `csvOptions.fields` is defined, this is the authority. 
if `allColumns=true` we consider all the columns. Otherwise, only visible columns are considered. And from these considered columns, we remove those with `disableExport=true`

### Print rules

if `allColumns=true` all the columns are printed
if `printOptions.fields` is defined we print columns in `printOptions.field` excepted if they have `disableExport=true`
if `printOptions.fields` is not defined, we print visible columns, even if `disableExport=true`

## The questions

- Should we have the same behavior? I think yes, but since print and csv are for different purposes, it's open to debate. 
- If yes which behavior should we use?

@mui/x if you have opinion or related issues

**Comment by alexfauquette** [comment]
I personally prefer the CSV behavior which allows to do whatever a dev wants with `fields` option. Which can be useful when using the api. And after you have two helpers: 
- `disableExport` if the export of a column is meaningless
-  `allColumns` which could be renamed `includesHiddenColumns`

**Comment by flaviendelangle** [comment]
@DanailH if you have reasons for the print differences :+1:

**Comment by cherniavskii** [comment]
+1 for CSV behavior. Print rules resolution seems a bit confusing to me.

**Comment by m4theushw** [comment]
I also agree that the print options should behave as the CSV options, since the print came after.
