### ISSUE TITLE
[DataGridPro] Should take into account custom initialState when exporting pageSize 

### ISSUE THREAD

**Issue by arielger** [mui/mui-x#3905]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If the user selects a differente `pageSize` from the default (100) it won't be exported when using the `apiRef.current.exportState()` method.

If we set a default pageSize different from 100 using the `initialState` prop (take for example 50) the export function will be exporting this

```
pagination: {
    pageSize: 50
}
```

while if we change the pageSize manually to 100 it won't export anything.

See https://github.com/mui/mui-x/pull/3593/files#diff-0284f2cbf3405ea8b1f0ff9c6c16cda41e0e330d1f459b9336e1ab0f3a4c7098R98

### Expected behavior 🤔

`exportState` should export the pageSize prop when it's different from the default but this default shouldn't be hardcoded. It should take into account the `initialState.pagination.pageSize` prop if it's passed.

### Context 🔦

I'm trying to export and import table state to localStorage. Right now if I default my table pageSize to 50 via initialState it will be unnecessarily exported (since it's the default) and it won't be exported if the user change the pageSize to 100.
If the user changed the pageSize to 100 it will be restored to 50 when reading the exported state from localStorage (since the configuration wasn't exported).

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Edge: Not Found
    Firefox: 96.0.3
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.61
    @mui/icons-material: ^5.2.5 => 5.2.5
    @mui/lab: ^5.0.0-alpha.62 => 5.0.0-alpha.62
    @mui/material: ^5.2.5 => 5.2.5
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.5
    @mui/styles: ^5.2.3 => 5.2.3
    @mui/system:  5.2.5
    @mui/types:  7.1.0
    @mui/utils:  5.2.3
    @mui/x-data-grid-pro: ^5.5.0 => 5.5.0
    @mui/x-license-pro:  5.5.0
    @types/react: ^17.0.38 => 17.0.38
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.4.4 => 4.5.2
```
</details>

**Comment by flaviendelangle** [comment]
Interesting edge case
I updated the rule to always export if the page size has been initialized or is being controlled.

**Comment by arielger** [comment]
@flaviendelangle that fix will do it for now, thanks so much for the quick response!
