### ISSUE TITLE
[DataGrid] Columns not correctly restored after printing when `columnVisibilityModel` and `printOptions.fields` is used

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#3906]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After printing a page for the 2nd time I see wrong visible columns in the grid. This seems to only occur if the `columnVisibilityModel` prop is used and custom fields are also specified via `printOptions.fields`.

### Expected behavior 🤔

It should keep the same columns that were visible before printing.

### Steps to reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-39bx2?file=/demo.tsx:740-752
2. Click Export > Print
3. Cancel the print
4. Click again Export > Print
5. Cancel the print
6. It only shows the "id" column, which is hidden according to `columnVisibilityModel`.

![image](https://user-images.githubusercontent.com/42154031/153283900-ee65e338-2943-471f-bb15-ac7ca3ac5ca8.png)

### Context 🔦

I was playing with the options in #3904.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Carefull on this one to test correctly with the old and the new mode :+1:
