### ISSUE TITLE
[DataGrid] Columns in Datagrids get offset when selected for editing

### ISSUE THREAD

**Issue by KxL5376** [mui/mui-x#3909]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

For **Datagrids that have horizontal scrollbars** (big datagrids or datagrids being displayed in small browser windows), columns sometimes get **offset** by 1 or 2 columns when cells are selected for editing. This behaviour is random and unpredictable. As you can see from the video below, the "**Tempest**" column is empty but when a cell in the "**Grant Tempest/Quoll**" column is selected for editing the entire column gets offset.

The columns only return to the correct place when the user scrolls left or right.

https://user-images.githubusercontent.com/99391593/153367632-1c25e83b-eb3c-4548-9751-82c784fed9b1.mp4

### Expected behavior 🤔

When cells are selected to be edited, all columns should stay aligned with their respective headers.

### Steps to reproduce 🕹

Steps:

https://codesandbox.io/s/datagrid-v5-quick-start-forked-c55xv?file=/src/App.tsx

The behaviour is unpredictable but here are some steps to try out:

1. Scroll to end of grid (extreme right)
2. Edit cell in Column 22
3. Edit cell in Column 21. Column may now visibly offset

You may also try editing random cells and scrolling left and right before editing again, the columns will offset at some point.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Looks similar to https://github.com/mui/mui-x/issues/3890

**Comment by KxL5376** [comment]
> Looks similar to #3890

"setting columnBuffer property to a high enough number (number of all columns)" does seem to have fixed the issue! Thanks for the fast reply and for linking that issue @cherniavskii !
