### ISSUE TITLE
[DataGridPro] Am I using what's new in #3687 to export collapsed data correctly?

### ISSUE THREAD

**Issue by lincolnmqs** [mui/mui-x#3913]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to use update #3687 to export even collapsed table data. However, when there are selected checkboxSelection, export only the selected ones. Export all only if all are not selected.

Code: https://codesandbox.io/s/xenodochial-newton-qj6fv?file=/src/App.js:4021-4077

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
![image](https://user-images.githubusercontent.com/3309670/153440735-73c4dd92-66bf-4a2a-9071-3e94fa715654.png)

You are describing the default behavior, you don't have to use #3687  at all.

**Comment by shawnlee-info** [comment]
> ![image](https://user-images.githubusercontent.com/3309670/153440735-73c4dd92-66bf-4a2a-9071-3e94fa715654.png)
> 
> You are describing the default behavior, you don't have to use [#3687](https://github.com/mui/mui-x/pull/3687) at all.

I think you misunderstood his question, he's not affirming your default behavior, he's describing the issue, just another victim. 

I don't get it, why selecting row(s) has anything to do with the export? especially users can easily click a row on the screen, they don't even know they're selecting a row, but Export only gets one row. Watch real users using it you'll know Export means get a copy of ALL data to them in most cases.

I fell into this pitfall too recently, and just for anyone who needs, if selecting a row isn't a necessary feature, you can simply disable it so alwasy exports all rows **disableRowSelectionOnClick**
