### ISSUE TITLE
[DataGridPro] Slow Performances on editing and re-rendering 

### ISSUE THREAD

**Issue by danra2** [mui/mui-x#3916]
### Order ID 💳

32640

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Using the Datagrid pro, occasionally depending on the situation I do notice a decrease in performance or slight lag / delay in terms of editing fields. This is also apparent when using the search-bar. So far I've only been dealing with 20 rows for testing, but concerned about optimization for larger data sets in the hundreds. How can I go about optimizing the performance?

*By disabling a few features like double click to edit, and only activating editing based on clicking the edit icon, I did notice a performance increase and not much delay in terms of editing fields now. 

CodeSandbox Sample Below:
https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-kx6b7?file=/demo.js

Becomes more apparent in performance his when I have multiple components rendering on the same page. Suggestions on optimization would be greatly appreciated. Thanks!

### Your environment 🌎

<details>
System: OS: macOS Mojave 10.14.6 Binaries: Node: 16.9.1 - /usr/local/bin/node Yarn: 1.22.17 - /usr/local/bin/yarn npm: 7.21.1 - /usr/local/bin/npm Browsers: Chrome: 97.0.4692.99 Edge: Not Found Firefox: Not Found Safari: 12.1.2 npmPackages: @emotion/react: ^11.4.1 => 11.7.0 @emotion/styled: ^11.3.0 => 11.3.0 @mui/base: 5.0.0-alpha.65 @mui/core: 5.0.0-alpha.47 @mui/icons-material: ^5.0.0 => 5.3.0 @mui/lab: ^5.0.0-alpha.47 => 5.0.0-alpha.47 @mui/material: ^5.0.0 => 5.3.0 @mui/private-theming: 5.3.0 @mui/styled-engine: 5.3.0 @mui/styles: ^5.0.0 => 5.0.0 @mui/system: 5.3.0 @mui/types: 7.1.0 @mui/utils: ^5.0.0 => 5.3.0 @mui/x-data-grid: ^5.0.0-beta.1 => 5.0.0-beta.1 @mui/x-data-grid-generator: 5.2.2 @mui/x-data-grid-pro: ^5.0.1 => 5.0.1 @mui/x-license-pro: 5.0.1 @types/react: 17.0.14 react: ^17.0.2 => 17.0.2 react-dom: ^17.0.2 => 17.0.2 typescript: ^4.3.5 => 4.3.5
</details>

**Comment by danra2** [comment]
After adding the debouncing / timer delay on rendering new cells it fixed the issue with the lag. However, there is still a search input latency delay. Delay in text appearing in the search box or removal for that matter / lag. Any thoughts on fixing this based on my previous codesandbox? Is it the regex matching of all fields, I would imagine that is much more resource intensive vs just matching one field. 

*In terms of the editing, after disabling double click to edit as well as other props it seems to be okay now, no more latency issues.

**Comment by m4theushw** [comment]
By re-enabling the double click to edit I didn't notice the delay while editing a cell. In v5.3.0 we started to debounce the change events so typing a few characters in a input shouldn't cause a immediate rerender. Could you check if you're using the latest version in the application?

**Comment by danra2** [comment]
Another weird behavior is that the new row upon selecting "add new row", doesn't automatically shift down to the new cell in question. 

Example from Documentation:
https://codesandbox.io/s/8b940?file=/demo.js

*The scroll to index doesn't seem to work on first click, sometimes it takes up to 3 for it to finally scroll to the correct location of the newly added cell.

**Comment by m4theushw** [comment]
I'm closing since the added debounce solved the problem. Feel free to comment here or open another issue if the problem persists.
