### ISSUE TITLE
problems when using filter and valueGetter together.

### ISSUE THREAD

**Issue by JErsoz-Jones** [mui/mui-x#3918]
Hello, I am having problems when using filter and valueGetter together. I am using version "@mui/x-data-grid": "^5.5.0". When applying a filter to a table containing valueGetter I receive an error "An error occurred" where the table should be. I am using Sequelize to include attributes from other tables, when the data is received included attributes are in the form of nested objects. I need to access them via valueGetter: (params) => params.row.item.item. It is not currently possible for me to access a nested object from a field property within the column prop. When using field: "item.item" in the column prop there is a blank value in the corresponding column of the mui table. Please let me know if there is a workaround for this?

_Originally posted by @JErsoz-Jones in https://github.com/mui/mui-x/issues/1615#issuecomment-1034738462_

**Comment by cherniavskii** [comment]
Hey @JErsoz-Jones 
Here's an example that demonstrates how to use `valueGetter` to get value from a nested object: https://codesandbox.io/s/valuegettergrid-material-demo-forked-5r55v?file=/demo.tsx

If there's an issue with `DataGrid` - please provide a minimal example reproducing the issue.
You can start with [this template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) or create one from scratch.
Thank you!
