### ISSUE TITLE
[DataGrid] Don't use `field` to match columns in the columns panel when `headerName` is available

### ISSUE THREAD

**Issue by pkratz** [mui/mui-x#3927]
### Order ID 💳

25274

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We need the ability to limit the search filter in the GridColumnsPanel, that allows for us to search for available columns to hide/show. Currently the filter is performing an OR match on the column's field or the column's header test. In our use case, many of the "field" values for columns are internal names that are not meaningful to an end user. Also, our field names are static regardless of a user's locale, but the heading text will change per locale. It's a bit misleading that the "field" is automatically included in the search.

We'd like the ability to provide a custom filter to the find columns feature, or to simply turn off the "field" name checking logic.

| Field     | Header| Search Text |Current Match | Expected Match |
| ----------- | ----------- |---------- |---------- |---------- |
| internalName1      | Display 1| internal|Yes |No|
| internalName1      | Display 1| display| Yes|Yes|

I know that we can utilize the slots functionality in order to override the ColumnsPanel that is used and we can supply our own, but that's a bit heavy handed for our use case. The default columns panel is great with the exception of including the "field" in the search filter.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Interesting use case. What we can do about is to ignore the value of `field` when there's a `headerName` defined. That way, searching for "internalName1" would have 0 results but "Display 1" would work.

The following diff should be sufficient:

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx b/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
index 988dbd88d..3a056c991 100644
--- a/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
@@ -93,18 +93,16 @@ export function GridColumnsPanel() {
     setSearchValue(event.target.value);
   }, []);
 
-  const currentColumns = React.useMemo(
-    () =>
-      !searchValue
-        ? columns
-        : columns.filter(
-            (column) =>
-              column.field.toLowerCase().indexOf(searchValue.toLowerCase()) > -1 ||
-              (column.headerName &&
-                column.headerName.toLowerCase().indexOf(searchValue.toLowerCase()) > -1),
-          ),
-    [columns, searchValue],
-  );
+  const currentColumns = React.useMemo(() => {
+    if (!searchValue) {
+      return columns;
+    }
+    const searchValueToCheck = searchValue.toLowerCase();
+    return columns.filter(
+      (column) =>
+        (column.headerName ?? column.field).toLowerCase().indexOf(searchValueToCheck) > -1,
+    );
+  }, [columns, searchValue]);
 
   React.useEffect(() => {
     searchInputRef.current!.focus();
```

Feel free to propose this change in a pull request or we can wait for someone from the community.

**Comment by pkratz** [comment]
Thanks @m4theushw. I've proposed the change in a pull request.
