### ISSUE TITLE
[DataGrid] After updating to `5.5.1` from `5.2.2` grid does not render fully

### ISSUE THREAD

**Issue by TriPSs** [mui/mui-x#3928]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Grid does not use the full width

### Expected behavior 🤔

The grid to render in the full width that is available 

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/7668692/153682555-c69d75a8-2a67-41c6-8c24-49278f469ff9.png">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Edge: Not Found
    Firefox: 96.0.3
    Safari: 15.0
  npmPackages:
    @emotion/react: 11.7.1 => 11.7.1
    @emotion/styled: 11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.68
    @mui/icons-material: ^5.4.1 => 5.4.1
    @mui/lab: 5.0.0-alpha.68 => 5.0.0-alpha.68
    @mui/material: ^5.4.1 => 5.4.1
    @mui/private-theming:  5.4.1
    @mui/styled-engine:  5.4.1
    @mui/styles: ^5.4.1 => 5.4.1
    @mui/system:  5.4.1
    @mui/types:  7.1.1
    @mui/utils:  5.4.1
    @mui/x-data-grid: 5.2.2 => 5.2.2
    @types/react: 17.0.39 => 17.0.39
    react: ^17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: 4.5.5 => 4.5.5
```
</details>

**Comment by joserodolfofreitas** [comment]
Hi TriPSs, 
to identify if this is a regression of any sort, we need to understand better what features you're using.
Could you please provide an example at codesandbox displaying your use case?

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by TriPSs** [comment]
Sadly i'm unable to reproduce it with the sandbox. I was able to narrow it down that if I upgrade to 5.3 the problem starts.

**Comment by TriPSs** [comment]
I was finally able to reproduce the error in sandbox, If you place the following code in `App.tsx` you will get the error:

```
import React from "react";
import { DataGrid, GridRowsProp, GridColDef } from "@mui/x-data-grid";

const rows: GridRowsProp = [
  { id: 1, col1: "Hello", col2: "World", col3: new Date() },
  { id: 2, col1: "XGrid", col2: "is Awesome", col3: new Date() },
  { id: 3, col1: "Material-UI", col2: "is Amazing", col3: new Date() },
  { id: 4, col1: "Hello", col2: "World", col3: new Date() },
  { id: 5, col1: "XGrid", col2: "is Awesome", col3: new Date() },
  { id: 6, col1: "Material-UI", col2: "is Amazing", col3: new Date() }
];

const columns: GridColDef[] = [
  { field: "id", minWidth: 125 },
  { field: "col1", headerName: "Column 1", flex: 1},
  { field: "col2", headerName: "Column 2", minWidth: 150 },
  { field: "col3", type: 'date', headerName: "Column 2", width: 225 }
];

export default function App() {
  return (
    <div style={{ height: 700, width: "100%" }}>
      <DataGrid 
      rows={rows} 
      columns={columns}
      columnTypes={{
        date: {
          extendType: 'date',
        }
      }}
      />
    </div>
  );
}

```

Note that in our own code we also overwrite the `valueFormatter` of the date column but the error already occurs without it.

**Comment by TriPSs** [comment]
@m4theushw can we reopen this ticket or is more info needed?

**Comment by m4theushw** [comment]
Thanks for the reproduction. Here's the CodeSandbox: https://codesandbox.io/s/datagrid-v5-quick-start-forked-eq4omf?file=/src/App.tsx

It appears to be a bug with fluid columns. We need to investigate.

**Comment by cherniavskii** [comment]
It's a regression introduced in v5.6.0.
I cannot reproduce the issue with 5.5.1 https://codesandbox.io/s/datagrid-v5-quick-start-forked-4qq4fo

**Comment by joserodolfofreitas** [comment]
> It's a regression introduced in v5.6.0 (https://github.com/mui/mui-x/pull/4006 specifically)

@cherniavskii, in that case, I'm thinking that maybe it makes sense to create another issue to address the regression from 5.6.0.
I'm not sure if this will solve the problem reported by @TriPSs. Regarding this elusive regression from 5.5.1, it seems that we're back on square one.

**Comment by m4theushw** [comment]
> Note that in our own code we also overwrite the valueFormatter of the date column but the error already occurs without it.

I guess `extendType` is used because of this.

**Comment by TriPSs** [comment]
> > Note that in our own code we also overwrite the valueFormatter of the date column but the error already occurs without it.
> 
> I guess `extendType` is used because of this.

We indeed use it to overwrite the `valueFormatter` and the `width`.
