### ISSUE TITLE
DataGrid vs DataGridPro ValueFormatter parameter is different

### ISSUE THREAD

**Issue by all12jus** [mui/mui-x#3950]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

DataGrid: valueFormatter is passed in the same parameters as valueGetter, or renderCell.
DataGridPro: valueFormatter is passed in a reduced amount of information, not including the rest of the values in the row.

### Expected behavior 🤔

I would have expected to be able to change from DataGrid to DataGridPro without having the columns break, after discovering a feature we were asked to include requires DataGridPro. 

This would mean that both versions of valueFormatter should have been passed the same info. 

### Steps to reproduce 🕹

Steps:

1. Make a working value formatter, using datagrid (regular): 

`{ field: 'ship_cost', headerName: 'Planned Ship Cost', width: 200,
            valueFormatter: (cellValues) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(getLocationDefaultTrayFreightCost(cellValues) * cellValues.row.OrderdQty)
        },`

Note: the getLocationDefaultTrayFreightCost uses some other values from cellValues.row to calculate that value.

2. install the upgrade to pro.
3. Change the DataGrid to DataGridPro. 
4. It will break on that column.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 11.6
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.23.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71 (Used in this case)
    Edge: 98.0.1108.51
    Firefox: 94.0.2
    Safari: 15.1

</details>

### Order ID 💳 (optional)

31394

**Comment by m4theushw** [comment]
I'm not sure if I understood. Currently we don't differentiate the params given to `valueFormatter` according to the plan used. If you could detail more about this possible problem it would be nice.

https://github.com/mui/mui-x/blob/5a809ceaa53be51297a460bbad28c108c8f885a0/packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts#L152-L157

However, we do miss the `row` param, which could be added. As a workaround, you can call `apiRef.current.getRow(cellValues.id)` to get the row.
