### ISSUE TITLE
[question] How to use license key in staging & production

### ISSUE THREAD

**Issue by ashwinshekher** [mui/mui-x#3957]
### Order ID 💳

#37441

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have single license and its working fine in my local. After deployment in staging environment it's says "MUI X Invalid License Key". How to get rid of it? 

We are blocked on our deployments. Your prompt response will be highly appreciated.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used. 
  Output from `npx @mui/envinfo` goes here.
```

</details>

**Comment by flaviendelangle** [comment]
Hi,

How are you injecting your license key inside your code ?
Is it hardcoded or are you using an environment variable ?

Can you try to log the license key to see if it is defined before passing it to `LicenseInfo.setLicenseKey` ?

**Comment by ashwinshekher** [comment]
we have hardcoded it and invoked (LicenseInfo.setLicenseKey) before first component render. Local its working without any issues. 

Same key is used in both environment.

**Comment by flaviendelangle** [comment]
OK so you are 100% sure that you are passing your license key to `setLicenseKey` in staging / prod the exact same way your are doing it in your local env ?

If you are using something like Create React App, can you try locally but with the built version instead of the dev version ?

**Comment by cherniavskii** [comment]
@ashwinshekher can you share errors from browser console if any?

**Comment by ashwinshekher** [comment]
It worked. Resolved by hardcoding.

**Comment by christiansaavedra** [comment]
Hey, one question. Isn't it 'dangerous' to put the license key on the client side, on production? I mean other devs can steal it and use it.

**Comment by cherniavskii** [comment]
Hey @christiansaavedra 
License key is designed to be public - see https://mui.com/components/data-grid/getting-started/#license-key
