### ISSUE TITLE
[DataGrid] translation/localization keys not taking effect

### ISSUE THREAD

**Issue by ole-magnus** [mui/mui-x#3958]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

According to docs (https://mui.com/components/data-grid/localization/#locale-text):
_If you want to pass language translations directly to the grid without using createTheme and ThemeProvider, you can directly load the language translations from the @mui/x-data-grid or @mui/x-data-grid-pro package_

However, in my project, setting up a datagrid like this:
```typescript

import { DataGrid, skSKGrid } from '@material-ui/data-grid';

<DataGrid rows={rows} columns={columns} localeText={skSKGrid} />;

```

only takes effect for certain parts of the UI. I.e. the column options are properly localized:

![Skjermbilde 2022-02-15 kl  14 12 24](https://user-images.githubusercontent.com/1662741/154068991-718e3ad2-ece2-48d1-9f8d-1c91109ba840.png)

wheras the footer in the table is not:
![Skjermbilde 2022-02-15 kl  14 13 26](https://user-images.githubusercontent.com/1662741/154069061-cf448e60-7637-4810-95c6-fe19e12b0de5.png)

My code example is using v4 but just tested on v5.4.1 and the latest published on npm and same result experienced there. Either this seems like a bug or documentation is off.

### Expected behavior 🤔

All keys passed to `localeText` take effect. Now only a subset does

### Steps to reproduce 🕹

See "Current behavior"
### Context 🔦

See "Current behavior"

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 Tested on both v4 and v5.4.1 and latest.
```
</details>

**Comment by flaviendelangle** [comment]
The doc example is as follow:

```tsx
import { DataGrid, skSK } from '@material-ui/data-grid';

<DataGrid rows={rows} columns={columns} localeText={skSK.components.MuiDataGrid.defaultProps.localeText} />;
```

`skSKGrid` should not be exported and has been removed in a release (you are probably using a v4 version before it)
It does not contain the `@mui/material` translations.

A working example with v5: https://codesandbox.io/s/datagrid-v5-quick-start-forked-vnevs


For V4, the logic is the same but the path differ `skSK.props.MuiDataGrid.localeText`

**Comment by ole-magnus** [comment]
@flaviendelangle That explains it for me. Thanks a lot! 👍
