### ISSUE TITLE
[question] Use dd/mm/yyyy (British English) date formats within Data Grid Pro

### ISSUE THREAD

**Issue by samfweb** [mui/mui-x#3962]
### Order ID 💳

30466

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm based in Australia and can't seem to find a simple way to set all date formats within the grid to British English format. 

The only English localization seems to be for US english.

I can use valueFormatter to change this on a per-column basis, however this isn't ideal. 

Could you let me know if there's a better way? 

Cheers

**Comment by m4theushw** [comment]
We use `value.toLocaleDateString()` to format the dates so it should be automatically formatted to the date format configured in your operating system or browser. There's no option to convert the dates to another format, unless passing a cell formatter and custom edit input. As example, my OS is configured to format dates also as `dd/mm/yyyy` and this is how it looks when I open https://mui.com/components/data-grid/demo/.

<img width="300" src="https://user-images.githubusercontent.com/42154031/154179998-50e2ddb8-f141-4ade-8c71-4750a59d49af.png" alt="image" style="max-width: 100%;">

**Comment by samfweb** [comment]
Appreciate the quick response. 

Interestingly enough, the example page shows mm/dd/yyyy within the table, but filters have the correct format 

![image](https://user-images.githubusercontent.com/44712417/154181930-c82df7f7-c2a8-4d6d-b560-b31fcdf5c3f7.png)

**Comment by samfweb** [comment]
I've updated my browser language settings to Australian and I'm now seeing dd/mm/yyyy throughout the grid.

Interested to know why the filter's behavior was different to grid cells, otherwise this is solved.

**Comment by m4theushw** [comment]
> Interested to know why the filter's behavior was different to grid cells, otherwise this is solved.

This is weird, it should use the same date format in all places. Could you give us more information about which browser and operating system you're using? Also, the language settings you had before changing to Australian?

**Comment by flaviendelangle** [comment]
Closing this one from lack of feedbacks

**Comment by itaisir** [comment]
I have the same issue, I want to show the date filter format as mm/dd/yyyy instead of dd/mm/yyyy

**Comment by Crhist0** [comment]
I know its closed but I just got the issue here. I think it shouldn't be necessary changing the whole document language to format the date. The doctype language has other effects like changing the decimal separator character that affects float numbers. 

If you could review this I would appreciate, thank you

**Comment by Crhist0** [comment]
Hello, I just got the issue here. I think linking the client browser language to the input is nice but I should be able to control it, I cannot control if my users will have the same settings.

As I'm formatting the value, the edit value become different (dd/mm to mm/dd) if my browser settings is us english, even thou the html lang is different. 

Please considerate reviewing this

**Comment by frontyard** [comment]
I have the same problem. Here's something I noticed while working on internationalizing our app. Results are from Chrome console (today is 6th of September):

> navigator.language
'fr-FR'

> new Date().toLocaleString()
'9/6/2023, 9:46:04 AM'

> new Date().toLocaleString('fr')
'06/09/2023 09:46:10'

> new Date().toLocaleString('fr-FR')
'06/09/2023 09:46:18

So even though my locale is set to fr-FR, using toLocaleString without explicitly passing locale yields en-US formatting.

**Comment by frontyard** [comment]
Don't know if any of these are causing our issues:
https://bugs.chromium.org/p/chromium/issues/list?q=tolocaledatestring+type%3Abug

**Comment by idrisakmal** [comment]
I agree with this https://github.com/mui/mui-x/issues/3962#issuecomment-1322819813

Please give us the flexibility to change the format for the date filters. We need granular control over it

**Comment by vopecula** [comment]
I have the same problem. Even if I add renderCell to a column which has the dateTime type, in the GridFilter menu the date format is still dd/mm/yyyy.

**Comment by adithyabaliga** [comment]
> Closing this one from lack of feedbacks

Still I'm also facing same issue . Tried all sorts of solutions but none worked

**Comment by Sathish1072** [comment]
I’m facing the same issue — I want the date filter to display in dd/mm/yyyy format instead of dd-mm-yyyy. 

<img width="187" height="388" alt="Image" src="https://github.com/user-attachments/assets/28adca77-ae48-4266-82b0-899e08de6dbf" />
