### ISSUE TITLE
[DataGrid] Have to use `import type {}` to import theme augmentation, which is not needed for the core packages

### ISSUE THREAD

**Issue by jannes-io** [mui/mui-x#3967]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

ModuleNotFoundError

Could not find module in path: '@mui/x-data-grid/themeAugmentation' relative to '/src/App.tsx'

### Expected behavior 🤔

Can import TypeScript theme augmentation.

### Steps to reproduce 🕹

[CodeSandbox](https://codesandbox.io/s/datagrid-v5-quick-start-forked-01ktk1?file=/src/App.tsx)

### Context 🔦

Cannot customize data grid in theme. https://github.com/mui/mui-x/issues/1755

If I look at differences between `@mui/lab` and `@mui/x-data-grid`, `@mui/lab` does provide an empty index.js file in `themeAugmentation`, while `@mui/x-data-grid/themeAugmentation` does not. Could be related, could be irrelevant.

### Your environment 🌎

see codesandbox

**Comment by jannes-io** [comment]
So solution is to use `import type {} from '@mui/x-data-grid/themeAugmentation';`  which is quite confusing because @mui/lab theme augmentation just works if you import it like `import '@mui/lab/themeAugmentation';`.

Main issue was that if you work on a custom component library, and do the simple import `import '@mui/x-data-grid/themeAugmentation';` everything is fine. Typescript compiles, rollup compiles, storybook shows changes, no problemo. But then once you install the component library into a cra project (with x-data-grid as peerDependency) it starts throwing errors. Difference in webpack configuration I assume.

So if the consensus is to keep this difference between lab and x-data-grid then it's fine. I suppose the only reason to keep this issue open is to reduce confusion and remove any differences between lab and x-data-grid when it comes to themeAugmentation

**Comment by m4theushw** [comment]
We don't add the empty file because TypeScript ignores `index.js` if there's also a `index.ts`. We might be able to fix this once we adopt the same bundling strategy from the core in #18.

> So solution is to use import type {} from '@mui/x-data-grid/themeAugmentation'; which is quite confusing because @mui/lab theme augmentation just works if you import it like import '@mui/lab/themeAugmentation';.

It works but note that the recommended approach is to use `import type {}` as explained in the docs: https://mui.com/components/about-the-lab/#typescript

**Comment by jannes-io** [comment]
Awesome news!
