### ISSUE TITLE
[DataGrid] renderCell always re-renders and re-fetching image if it use in it 

### ISSUE THREAD

**Issue by timursarvarov** [mui/mui-x#3968]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Look  on [sandbox](https://codesandbox.io/s/datagrid-quick-start-forked-pf2ip0?file=/src/App.tsx) and check console after scrolling

### Expected behavior 🤔

Shouldn't re-render, reload  and refetch image, similar like a mui  [Table  component](https://codesandbox.io/s/custompaginationactionstable-material-demo-forked-up048r?file=/demo.tsx:4620-4625)

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
The grid uses virtualization to make the scrolling faster. One tradeoff is that it removes and re-adds cells, only keeping in the tree the cells from those rows that are currently visible. What explains it rerendering the image, even with `React.memo` being used, is that the [component](https://github.com/mui/mui-x/blob/master/packages/grid/_modules_/grid/components/cell/GridCell.tsx) that wraps `renderCell` has a `rowId` prop which changes as you scroll. If you want a similar behavior to the Table component you can [disable](https://mui.com/components/data-grid/virtualization/#disable-virtualization) the virtualization with the `disableVirtualization` prop.
