### ISSUE TITLE
[license] Side effect issue: The license key is not installed in production

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#3969]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Considering the following configuration:

```jsx
import {} from "./mui"

ReactDOM.render(
    <PreviewComponent>
        <ModalProvider>
            <App />
        </ModalProvider>
    </PreviewComponent>,
    document.getElementById("root")
)
```

**mui.js**

```jsx
import { LicenseInfo } from "@mui/x-data-grid-pro"

LicenseInfo.setLicenseKey("fooo")
```

https://mui.zendesk.com/agent/tickets/2356

When building for production the license key is not installed. 

### Expected behavior 🤔

When building for production, the license key is installed. 

### Context 🔦

We set `sideEffect: false` in https://unpkg.com/browse/@mui/x-data-grid-pro@5.5.1/package.json so in our example, the bundler assumes that that import is dead code, it removes it all when building for production. It's a nasty bug as it works in dev mode.

Now, this side effect false is not true, there is a side effect. I'm not sure how to fix this problem. 

Maybe it would make sense to have `@mui/x-license-pro` as a user facing dependency. @flaviendelangle how do you plan to solving the license key problem with the date picker?

### Your environment 🌎

v5.5.1

**Comment by flaviendelangle** [comment]
Nasty one indeed...
Do you have a reproduction case ? therwise I can try to create one.

I did not work on the licensing of the `DateRangePicker` yet, I'm fully on the bundling rework right now.
But I feel like `@mui/x-license-pro` should be a user facing depency. It may be strange for user to just import `LicenseInfo` from one of our product packages when using several one of them.

**Comment by oliviertassinari** [comment]
> Do you have a reproduction case?

I don't. I have opened this issue to bring visibility to the three shaking issue. I think that we could snooze this side effect issue for some time, wait to see more developers struggling to install the license.

**Comment by cherniavskii** [comment]
As of now, we recommend using the `@mui/x-license-pro` package directly: https://mui.com/x/introduction/licensing/#how-to-install-the-key
Would it make sense to set `sideEffects: true` for the `@mui/x-license-pro` package?

**Comment by oliviertassinari** [comment]
> Would it make sense to set sideEffects: true for the @mui/x-license-pro package?

@cherniavskii I come to this conclusion by reading https://webpack.js.org/guides/tree-shaking/. However, maybe we can be more specific:

```diff
diff --git a/packages/x-license-pro/package.json b/packages/x-license-pro/package.json
index 4bb07f47f..06d37105e 100644
--- a/packages/x-license-pro/package.json
+++ b/packages/x-license-pro/package.json
@@ -9,7 +9,11 @@
     "url": "https://github.com/mui/mui-x/issues"
   },
   "homepage": "https://mui.com/x/introduction/",
-  "sideEffects": false,
+  "sideEffects": [
+    "./utils/licenseInfo.js",
+    "./legacy/utils/licenseInfo.js",
+    "./modern/utils/licenseInfo.js"
+  ],
   "publishConfig": {
     "access": "public"
   },
```

**Comment by cherniavskii** [comment]
Another option is to:
- Mark the `LicenseInfo` in the Data Grid packages as `@deprecated` and recommend using direct import from the license package:
	```js
	import { LicenseInfo } from '@mui/x-license-pro';
	```
- Set `sideEffects: true` in the license package

This would allow keeping `sideEffects: false` in the grid packages.

**Comment by oliviertassinari** [comment]
> Another option is to: 

@cherniavskii This makes sense to me. And instead of making the whole license package to have side effects, we can likely narrow it down to a single file: https://github.com/mui/mui-x/issues/3969#issuecomment-1374926095

**Comment by adityapatil9191** [comment]
Hello,

Please unsubscribe me from your mailing list.

Why am I receiving this email? I should not receive any email apart from my
issue.

Kindly co operate.

**Comment by oliviertassinari** [comment]
> I couldn't reproduce the issue

Interesting (great reproduction BTW). I have to dive a bit deeper, considering that https://mui.zendesk.com/agent/tickets/2356 has no reproduction, I think that it's best not to speculate on it, it's likely that I was hallucinating. The code is kept because there is a function call. I had to do

```diff
diff --git a/components/license.js b/components/license.js
index 41b5b21..b8ccb21 100644
--- a/components/license.js
+++ b/components/license.js
@@ -1,3 +1,3 @@
 import { LicenseInfo } from "@mui/x-license-pro";

-LicenseInfo.setLicenseKey("asdasd");
+/*#__PURE__*/LicenseInfo.setLicenseKey("aaa");
```

to get the behavior.

Now Webpack docs say:

> A "side effect" is defined as code that performs a special behavior when imported, other than exposing one or more exports. An example of this is polyfills, which affect the global scope and usually do not provide an export.

https://webpack.js.org/guides/tree-shaking/ so without #9092, 

https://github.com/mui/mui-x/blob/8937816d8a8067e542e2d22efa8d7012e364a1cb/packages/x-license-pro/src/utils/licenseInfo.ts#L12

would get removed. In practice, it likely doesn't matter, so #9092 or not, I think we are good.
