### ISSUE TITLE
Extra blanks are removed form the string content of a column

### ISSUE THREAD

**Issue by llittlefoxx** [mui/mui-x#3971]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Example content of the column "AB &nbsp; &nbsp; C", is displayed "AB C".
In my application the number of blanks matters. 

### Expected behavior 🤔

Column content should be exactly as provided in the tableData "AB &nbsp; &nbsp; C".

### Steps to reproduce 🕹

Steps:

1. Pass string content to a column with multiple consecutive blanks.
2. Display the table.
3. Notice that the blanks are reduced to 1 blank.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
@llittlefoxx How do you display text with multiple spaces in your app?

It seems that when you display a string with multiple spaces in react, the spaces are not displayed 
https://codesandbox.io/s/awesome-lake-hump2w?file=/src/App.js

![image](https://user-images.githubusercontent.com/45398769/154444624-3ffd66ff-6e23-47dc-8ed9-4a839fa8795d.png)
![image](https://user-images.githubusercontent.com/45398769/154444662-9d2bc3d8-aee3-4ed2-87ac-ea75d3688156.png)

**Comment by alexfauquette** [comment]
Your solution is working with the column header too. I recommend you to use `pre` instead of `pre-wrap` to keep the overflow elipse

https://codesandbox.io/s/antdesigngrid-material-demo-forked-zzk3zc?file=/demo.js

**Comment by flaviendelangle** [comment]
I'm closing this once since a ful explanation has been given and I don't think we have to change the doc
