### ISSUE TITLE
Add italian translation for labelDisplayedRows

### ISSUE THREAD

**Issue by frab90** [mui/mui-x#3974]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

in the footer, the label shows 'of' 

### Expected behavior 🤔

in the footer, the label shows 'di' 
also, the translation of 'more than', is 'più di'

### Steps to reproduce 🕹

https://codesandbox.io/s/datagrid-v5-quick-start-forked-9n0ofr?file=/src/App.tsx

### Context 🔦

same that used to happen here
https://github.com/mui/mui-x/issues/1107

**Comment by frab90** [comment]
I realised this is probably not a `mui-x` problem but a `mui` one. I created a PR that should solve the issue.

https://github.com/mui/material-ui/pull/31131

**Comment by flaviendelangle** [comment]
Indeed
Thanks for the PR on the core !
