### ISSUE TITLE
[DataGridPro] Support `valueFormatter` for the grouping columns

### ISSUE THREAD

**Issue by atillaaliyev** [mui/mui-x#3980]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm making grouping for a field, name of field is **parentCoverageCode**. 
![image](https://user-images.githubusercontent.com/6121871/154708004-f05e1133-2fa5-4c8c-923f-21bf0d88f22a.png)

Everything is good but TRF value is a key, I want to show as  **Traffic(3)** instead of **TRF(3)** for grouping name,  so value of **parentCoverageName** variable.

I used "groupingValueGetter", but it changed grouping field's id , it was **"auto-generated-row-parentCoverageCode/Traffic
"**, i dont want it. Maybe I can use https://mui.com/components/data-grid/group-pivot/#custom-grouping-column but it has high cost for simple process.

I didn't find any solution for this case,  if there isn't, maybe you can add new prop that naming groupingValueFormatter 
Thank you.

### Order ID 💳 (optional)

37219

**Comment by flaviendelangle** [comment]
You can indeed use `renderCell` to customize the whole cell.
But a callback would make it easier.

**Comment by cjsilva-umich** [comment]
@atillaaliyev Would you mind sharing how you accomplished this with rendercell? I'm having a hard time accomplishing this with the proposed solution _or_ rendercell and would benefit from an example.

**Comment by flaviendelangle** [comment]
Could you describe more in details what you are trying to achieve, if possible in a new issue?
I'm not working on the grid anymore so a dedicated issue would help :+1:
