### ISSUE TITLE
[DataGridPro] Phantom Rows from stale state

### ISSUE THREAD

**Issue by shanemiller89** [mui/mui-x#3984]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We have custom server side filtering. When switching between filters, sometimes the rows get "stuck" and still render withing the DataGrid. Even in scenarios where no data is being returned, rows from the previous state are still rendering on top of the `no rows overlay`.

In addition, these clicking any action on a "phantom row" results in an error saying "Row id #### does not exist"

### Expected behavior 🤔

Previous state rows disappear like expected.

### Steps to reproduce 🕹

Currently working on a reliable code sandbox to test with.

### Context 🔦

This issue has caused displayed data after filtering to be unreliable to the user.

Below is an example of these "phantom rows". The rows being displayed are duplicates as well. Consoling this data shows an empty list.

So far refreshing the page has been the only way to "fix" the issue.

![phantom_rows1](https://user-images.githubusercontent.com/2695797/154743831-5e443c78-b5aa-479b-94f0-efb883aab3c1.png)

![phantom_row2](https://user-images.githubusercontent.com/2695797/154743827-a4401e36-5b02-4ef9-a3ce-06e2b68eace0.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
Using Chrome

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.25 GB / 15.44 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 20200816.222424.0 - /usr/local/bin/watchman
  Managers:
    Apt: 2.3.9 - /usr/bin/apt
    Composer: 1.9.1 - /usr/local/bin/composer
    pip3: 20.3.4 - /usr/bin/pip3
    RubyGems: 2.7.6.2 - /usr/local/bin/gem
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.2.0 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    FFmpeg: 4.4 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    VirtualBox: 6.1.26 - /usr/bin/vboxmanage
  IDEs:
    Nano: 5.6.1 - /usr/bin/nano
    VSCode: 1.64.2 - /snap/bin/code
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Elixir: 1.13.1 - /home/shanemiller89/.asdf/shims/elixir
    Erlang: 24.1.1 - /home/shanemiller89/.asdf/shims/erl
    Java: 11.0.13 - /usr/bin/javac
    Perl: 5.32.1 - /usr/bin/perl
    PHP: 8.0.8 - /usr/bin/php
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.9.7 - /usr/bin/python3
    Ruby: 2.5.7 - /usr/local/bin/ruby
  Databases:
    MySQL: 0.21.10.3 - /usr/bin/mysql
    PostgreSQL: 13.4 - /home/shanemiller89/.asdf/shims/postgres
    SQLite: 3.35.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 97.0.1

```
</details>

### Order ID 💳 (optional)

20297

**Comment by shanemiller89** [comment]
I am working on creating a reproducible sandbox. In the meantime I wanted to bring this to y'alls attention and see if a known solution might be out there somewhere. I could not find any existing tickets discussing this bug.

**Comment by m4theushw** [comment]
This is the first time we see this issue. I'll wait for the reproduction. We have a [demo](https://mui.com/components/data-grid/filtering/#server-side-filter) using server-side filtering. By copying the code from it can you see the bug?
