### ISSUE TITLE
[DataGrid] Page auto scroll to top when click on filter icon

### ISSUE THREAD

**Issue by ronakiihglobal** [mui/mui-x#4011]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When we select country "is any of" filter on below documentation page it works first time properly, but then when we click on filter icon for same column the whole page scroll to top when filter panel open.

In firefox scroll is less ( because of focus event i think which is fine) but in chrome it is not looks proper. 

Try second demo from below link in chrome browser.

https://mui.com/components/data-grid/filtering/

### Expected behavior 🤔

Focus is fine but it should not scroll too much so user needs to scroll down again to access filter panel.

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/components/data-grid/filtering/ in chrome browser
2. In second demo select country filter and set some 2-3 countries, then click somewhere so panel will close and it will show filter icon for country column
3. Now click on that filter icon
4. you will see page is scrolled to top 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @ronakiihglobal thanks for raising this. It is a valid bug.

**Comment by ronakiihglobal** [comment]
Thanks @DanailH

**Comment by m4theushw** [comment]
Here's the cause. When `GridFilterPanel` tries to focus the last item, the Popper is not fully positioned yet.

<img width="400" src="https://user-images.githubusercontent.com/42154031/155329223-5b6d772b-bff4-4af1-8565-4b04bb2b591d.png" alt="image" style="max-width: 100%;">

**Comment by ronakiihglobal** [comment]
Amazing, Cheers!
