### ISSUE TITLE
[DataGrid] Highlight a row based on an external event

### ISSUE THREAD

**Issue by nlafleur** [mui/mui-x#4012]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When I hover a feature on a map next to the table I want to highlight the same ID in the datagrid with the "Mui-hovered" class.
I searched for some usefull functions in the datagrid ref but can't seem to find something that adds the "hover" class to the element.

I use the "setSelectionModel" function when you actually click the feature on the map so I can't use the "selected" 

### Examples 🌈

At this time there are 400 rows in my DataGrid, I tried to fix it by using the "rowBuffer" attribute, but this makes the application extremly slow (rowBuffer={data.length}) 

Here are 2 screenshots of my usecase:
Current behaviour:
![image](https://user-images.githubusercontent.com/40174298/155109625-8a5ecc59-aa63-46c4-a0c3-cc1f73d598c5.png)
Expected behaviour:
![image](https://user-images.githubusercontent.com/40174298/155109652-0e607aa0-c9d9-4e97-8d88-912eb67b7b38.png)

Leaflet Feature functions:

```
handleFeatureMouseOver = (layer, tableRef) => {
      const rowIndex = tableRef.getRowIndex(layer.feature.id)
      const columnIndexToScrollTo = { rowIndex: rowIndex, colIndex: 1 }

      tableRef.scrollToIndexes(columnIndexToScrollTo)

      const rowElement = tableRef.getRowElement(layer.feature.id)
      rowElement.classList.add("Mui-hovered")
}
```

The problem with the "rowElement.classList.add" is that the Element does not exist before it is scrolling all the way to the bottom, while this does work with the "setSelectionModel" function in the datagrid reference, like so:

`tableRef.setSelectionModel([layer.feature.id])`

So I was wondering if a function like "setRowHover" could be added to achieve this.

**Comment by DanailH** [comment]
Hi, @nlafleur thanks for raising this.
I'm not sure if I understand the problem completely but as far as I got it you want to highlight (not select) a row in the data grid when you hover on an item in the map next to it. I see that you are already using the `scrollToIndex` to get to that row but, if you haven't checked it already, you can also use `getRowClassName` prop to apply a class to a specific row. You can check more about that prop here https://mui.com/components/data-grid/style/#styling-rows

**Comment by nlafleur** [comment]
Yes thank you 👍 I ended up fixing it with the "getRowClassName" in combination with the "getRow" function for adding a row key which returns "Mui-hovered" thanks to the "getRowClassName" function
