### ISSUE TITLE
[DataGridPro] Custom column pinning with a hovered row is lag with the mouse movement

### ISSUE THREAD

**Issue by jaballogian** [mui/mui-x#4015]
### Order ID 💳

29446

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm creating a custom actions column on the `DataGridPro` component with the column pinning feature. The cell inside the actions column will only be rendered if the row is being hovered like this image below.
![image](https://user-images.githubusercontent.com/24468466/155146931-da7019cf-51ae-46e4-a9fd-5d9b4da53425.png)

Here is the playground https://codesandbox.io/s/github-mui-custom-data-grid-fxqytz.

If we hover the row inside the `DataGridPro` component one by one slowly (like the first 5 seconds in the video below), the actions column is not lagging (it's rendered precisely where the row is being hovered).
But if we hover the row inside the `DataGridPro` component one by one fast, (like the rest of the video below), the actions column is lagging (visually, the speed of rendering each actions column is lagging than the speed of the mouse movement).

https://user-images.githubusercontent.com/24468466/155148773-7e3a376d-4b23-4270-90f0-5414bdfa0dc2.mp4

What I want is the actions column is not lag with the mouse movement like this video below.

https://user-images.githubusercontent.com/24468466/155150540-571b16a3-4768-4ee6-af11-f17e1dea9d30.mp4

What's the problem that makes the actions column on my `DataGridPro` component lags and what's the solution for this?

### Your environment 🌎

<details>
  <summary>Environment</summary>

Browser: Chrome 98
OS: Windows 11
Dependencies: stated in the playground
</details>

**Comment by DanailH** [comment]
Hi, @jaballogian I checked your reproduction and the issue you are describing doesn't seem to be related to the data grid per se but rather the way you are handling the `renderCell` your actions column.
Every time you hover (or `onMouseEnter` and `onMouseLeave`) you are looping over all the columns and updating the `actions` column and adding the `renderCell`. This causes a rerender of the grid and hence the described lag. I would suggest you to optimize your code so that you avoid grid rerendering on each hover - one possible solution would be to show and hide your action buttons using CSS.

**Comment by jaballogian** [comment]
Hello @DanailH 

I tried to simplify the case (by deleting the Filters component and using only the actions column for the Data Grid component) also using CSS to show and hide the actions column but still got lag as seen in the video below.

https://user-images.githubusercontent.com/24468466/155834102-385b085b-0bbd-4e64-8141-8ae7f0df6c18.mp4

If we pause the video to 00:04, we could see that the shown actions column doesn't match with the hovered row.
![image](https://user-images.githubusercontent.com/24468466/155834156-85cff60c-ae98-4431-bb40-f856481c72bd.png)

I tried using CSS to show and hide the actions column:

```javascript
renderCell: (params) => (
        <Box
          className={
            hoveredRow === params.id
              ? classes.columnActions
              : classes.columnActionsHide
          }
        >
          {/* EDIT ICON */}
          <CustomTooltipBlack title="Edit" placement="bottom">
            <IconButton>
              <IconEdit />
            </IconButton>
          </CustomTooltipBlack>

          {/* COPY ICON */}
          <CustomTooltipBlack title="Copy" placement="bottom">
            <IconButton>
              <IconFileCopy />
            </IconButton>
          </CustomTooltipBlack>

          {/* DELETE ICON */}
          <CustomTooltipBlack title="Delete" placement="bottom">
            <IconButton>
              <IconDelete />
            </IconButton>
          </CustomTooltipBlack>
        </Box>
      )
    }
```

or render only the actions columns on the hovered row:
```javascript
  renderCell: (params) =>
          hoveredRow === params.id && (
            <Box className={classes.columnActions}>
              {/* EDIT ICON */}
              <CustomTooltipBlack title="Edit" placement="bottom">
                <IconButton>
                  <IconEdit />
                </IconButton>
              </CustomTooltipBlack>

              {/* COPY ICON */}
              <CustomTooltipBlack title="Copy" placement="bottom">
                <IconButton>
                  <IconFileCopy />
                </IconButton>
              </CustomTooltipBlack>

              {/* DELETE ICON */}
              <CustomTooltipBlack title="Delete" placement="bottom">
                <IconButton>
                  <IconDelete />
                </IconButton>
              </CustomTooltipBlack>
            </Box>
          )
      }
```

Here is the new demo for this case https://codesandbox.io/s/github-mui-custom-data-grid-2-kur1gt

**Comment by DanailH** [comment]
@jaballogian I checked the demo you linked in your second comment (https://codesandbox.io/s/github-mui-custom-data-grid-2-kur1gt) you are still mutating the state causing the grid to rerender on hover. That's why you are experiencing the described lag.

**Comment by m4theushw** [comment]
> I tried using CSS to show and hide the actions column:

> or render only the actions columns on the hovered row:

Both attempts relay on a rerender of your component to work, so you'll still see the lag. As an alternative you can remove all state mutation and use CSS to target the hovered row as below:

```css
[data-field="actions"] {
  display: none;
}
.MuiDataGrid-row.Mui-hovered [data-field="actions"] {
  display: flex;
}
```

Note that for this to work you need to always render the options, not matter if the row is hovered or not. CSS will do the job for you.

**Comment by jaballogian** [comment]
> 
> ```css
> [data-field="actions"] {
>   display: none;
> }
> .MuiDataGrid-row.Mui-hovered [data-field="actions"] {
>   display: flex;
> }
> ```
> 

Oh yes, @m4theushw  you're right.
I placed it inside my `CustomDataGridPro` component and it worked.
```javascript
'[data-field="actions"]': {
    display: 'none'
  },
  '.MuiDataGrid-row.Mui-hovered [data-field="actions"]': {
    display: 'flex'
  },
```

Thank you @m4theushw @DanailH
