### ISSUE TITLE
[DataGrid] Compilation error when trying to import a local from an outdated version of `@mui/material`

### ISSUE THREAD

**Issue by worlderland** [mui/mui-x#4018]
### Order ID 💳

37070

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

My company has recently purchased the licence for MUIX Pro and I'm busy trying to implement it.

I was following the documentation [HERE](https://mui.com/components/data-grid/getting-started/#license-key-installation), and because we were already using MUI I jumped straight into installing MUIX Pro (npm install @mui/x-data-grid-pro) and then I carried on following the instructions, by writing the code to declare assign the license key:

`import { LicenseInfo } from '@mui/x-data-grid-pro';

LicenseInfo.setLicenseKey(
  'process.env.REACT_APP_MUIX_LICENSE_KEY',
);`

I have written the license key itself in our .env file, and then imported using the process.env global variable ). It returns the license key as a string.

After that I saved and start the app, which did not start because the following error appeared in the terminal:
./node_modules/@mui/x-data-grid-pro/index-esm.js
Attempted import error: 'daDK' is not exported from '@mui/material/locale' (imported as 'te').

I have googled it but nothing comes up.

Versions from package.json:
"@mui/core": "^5.0.0-alpha.54",
"@mui/icons-material": "5.1.1",
"@mui/lab": "5.0.0-alpha.55",
"@mui/material": "^5.1.1",
"@mui/styles": "5.1.1",
"@mui/x-data-grid-pro": "^5.5.1",

Thank you in advance.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
  npmPackages:
    @emotion/react: 11.6.0 => 11.6.0
    @emotion/styled: 11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.55
    @mui/core: ^5.0.0-alpha.54 => 5.0.0-alpha.54
    @mui/icons-material: 5.1.1 => 5.1.1
    @mui/lab: 5.0.0-alpha.55 => 5.0.0-alpha.55
    @mui/material: ^5.1.1 => 5.1.1
    @mui/private-theming:  5.2.2
    @mui/styled-engine:  5.2.0
    @mui/styles: 5.1.1 => 5.1.1
    @mui/system:  5.2.2
    @mui/types:  7.1.0
    @mui/utils:  5.2.2
    @mui/x-data-grid-pro: ^5.5.1 => 5.5.1
    @mui/x-license-pro:  5.5.1
    @types/react:  17.0.37
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2

Browsers: Firefox (mainly) and Brave.
```
</details>

**Comment by flaviendelangle** [comment]
Danish has been added on [`@mui/material@5.2.5`](https://github.com/mui/material-ui/blob/master/CHANGELOG.md#muimaterial525) and you are using `@mui/material@5.1.1`
Updating this dep should do the trick. I suggest you update all the `@mui/*` to there latest version if there is nothing blocking you.

According to our dependency list, `@mui/x-data-grid-pro@5.5.1` requires `@mui/material@5.2.8` or higher.

**Comment by rextambua** [comment]
i cant use locale in MUIX Pro, was using comunity version prior and it was working, now i bought the liscence and trying to upgrade to the DatagridPro but it doesnt seem to export my locale 
```import {
  DataGridPro,
  GridColDef,
  GridEditInputCell,
  GridPaginationModel,
  GridRowSelectionModel,
  ruRU,
} from '@mui/x-data-grid-pro';
```
the error TS2305: Module "@mui/x-data-grid-pro" has no exported member ruRU 
my dep versions  
"@mui/material": "^5.15.12",
    "@mui/x-data-grid": "^6.19.2",
    "@mui/x-data-grid-pro": "^7.1.1",
    "@mui/x-license-pro": "^6.10.2",
