### ISSUE TITLE
[DataGrid] Only shows filter icon in column if that column is also sorted

### ISSUE THREAD

**Issue by ffanizzanvisia** [mui/mui-x#4025]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If a filter is applied to a column (which is not the sorting column), you can hover to see the filter icon after. But you cannot see it otherwise. In contrast, when a column is sorted, and has a filter applied, the filter icon is always visible

### Expected behavior 🤔

The filter icon should always appear (or there should at least be some way to enable this behavior easily at the grid level), regardless of whether a column is sorting or not

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/components/data-grid/demo/
2. Apply a filter to the Commodity column (ex: Contains 'Oil'
3. Move focus away. Note how the icon disappears from the column header
4. Sort the Commodity column by clicking the sorting icon
5. Move focus away. Note how the icon remains in the column header

### Context 🔦

In our use case, we don't want to use the grid toolbar. Because of this, an end user may not know which columns are sorted by glancing at the grid header row

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 14.78 GB / 31.73 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.34.1. - /mingw64/bin/git
  Virtualization:
    Docker: 20.10.10 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.64.2 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
    Perl: 5.34.0 - C:\Program Files\Git\usr\bin\perl.EXE
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (98.0.1108.56)
    Internet Explorer: 11.0.19041.1

```
</details>

**Comment by DanailH** [comment]
Hi, @ffanizzanvisia thanks for raising this.
It does seem like a nice improvement (can be a bug I'm not sure if before was working correctly). I'll take a look,

**Comment by m4theushw** [comment]
I see it as a regression from a long time ago. I think it started in #2606. I made a comment about it in https://github.com/mui/mui-x/issues/1712#issuecomment-929165265.
