### ISSUE TITLE
[DataGrid] Troubleshooting 'Each child in a list should have a unique "key" prop'

### ISSUE THREAD

**Issue by Tiberriver256** [mui/mui-x#4029]
### Order ID 💳

#34712

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm using 5.5.1 of the DataGrid and getting the following error:

```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at svg
```

The strange thing is that it only happens when Webpack mode is set to `production`. I can't get a stack trace to work with sourcemaps for some reason but from looking at react dev tools it looks like it's coming from one of the column headers inside the data grid.

![image](https://user-images.githubusercontent.com/6989492/155544336-e89debae-c612-46e3-a8b9-1a9582ef0fca.png)

Do you have any tips for tracking this down? I can't find anywhere in my code that would be creating a loop without a key. My columns are defined inline in the function using `useMemo` for localization support of the header labels.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

https://whatismybrowser.com/w/SYQ48DB

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 16.71 GB / 31.78 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.33.1.
  IDEs:
    VSCode: 1.64.2 - C:\Program Files\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.11.31911.196 (Visual Studio Professional 2019), 17.0.32002.185 (Visual Studio Professional 2022)
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
    Internet Explorer: 11.0.19041.1202
 
</details>

**Comment by Tiberriver256** [comment]
I've trimmed the code down to just this and I'm still getting the issue:

```jsx
import React from 'react'
import { Grid } from '@mui/material'

import {
  GridColDef,
  DataGridPro
} from '@mui/x-data-grid-pro'

const MY_COLUMNS: GridColDef[] = [
    { field: 'id', hide: true },
    {
      field: 'building',
      headerName: 'usersPage.building',
      width: 115,
    },
  ]

export default function UsersPage(): JSX.Element {
  return (
    <Grid
      container
      sx={(theme) => ({
        height: '75vh',
        paddingTop: theme.spacing(2.5),
      })}
    >
      <DataGridPro
        rows={[
          {
            id: '1',
            campus: 'campus',
            building: 'building',
            name: 'name',
            userTypes: 'type',
            email: 'email',
          },
        ]}
        columns={MY_COLUMNS}
      />
    </Grid>
  )
}
```

**Comment by Tiberriver256** [comment]
Seems to be something with my webpack/babel config maybe. I can't seem to reproduce the issue in a react app using create react app.

## babel.config.json

```json
{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-react",
      {
        "runtime": "automatic"
      }
    ],
    "@babel/preset-typescript"
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "useESModules": true,
        "regenerator": false
      }
    ]
  ],
  "env": {
    "test": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "targets": "current node"
          }
        ]
      ]
    }
  }
}
```

## webpack.config.js

```js
const { merge } = require('webpack-merge')
const singleSpaDefaults = require('webpack-config-single-spa-react-ts')
const Dotenv = require('dotenv-webpack')
const ReactRefreshPlugin = require('@pmmmwh/react-refresh-webpack-plugin')

module.exports = (webpackConfigEnv, argv) => {
  let prod = false
  if (argv.mode === 'production') {
    prod = true
  }
  const defaultConfig = singleSpaDefaults({
    orgName: 'midmark',
    projectName: 'users-page',
    webpackConfigEnv,
    argv,
  })

  return merge(defaultConfig, {
    // modify the webpack config however you'd like to by adding to this object
    devServer: {
      https: true,
    },
    plugins: prod
      ? [
          new Dotenv({
            path: './.env',
          }),
        ]
      : [
          new Dotenv({
            path: './.env',
          }),
          new ReactRefreshPlugin(),
        ],
  })
}
```

**Comment by DanailH** [comment]
Hi, @Tiberriver256 thanks for raising this.
Can you please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by Miiiiii7** [comment]
Hi! I have this issue while running the host of a microfrontend application.
When I run the remote app its working.

I'm using:
React: 18.2.0
Vite
Typescript

I created a simple project that reproduces the issue.

https://github.com/Miiiiii7/microfrontend-react-vite
