### ISSUE TITLE
[dataGrid][bug[in onPageChange] next page shows only one row while data will have more rows

### ISSUE THREAD

**Issue by phanvantien270290** [mui/mui-x#4032]
### Latest version

- [x] I have tested the latest version

### Current behavior 😯

https://codesandbox.io/s/datagrid-v5-quick-start-forked-07708w

server-side pagination:
-next page -> get 25 rows  from api  -> dataGrid render only one rows;
the bug  when  I click next page only renders  one row  although pageSize is 25 or more 

### Expected behavior 🤔

render row the same pageSize

**Comment by flaviendelangle** [comment]
In your demo, you only provide 6 rows to the grid, so there is only one page

**Comment by phanvantien270290** [comment]
> In your demo, you only provide 6 rows to the grid, so there is only one page

sorry, I think the link is old, I have updated the new link, hope you can help
