### ISSUE TITLE
Can not download invoice 

### ISSUE THREAD

**Issue by hongyuan1306** [mui/mui-x#4033]
### Order ID 💳

#38583

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi,

I just purchased a pro licence, but I as unable to download the invoice.

The invoice viewer crashes, and no download or print can be performed.

I need the invoice for our accounting.

Thanks.

![image](https://user-images.githubusercontent.com/10390407/155658006-44dd1fff-13e9-46eb-a7c8-edc1eedf38f1.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Could @oliviertassinari or @mbrookes take a look?

**Comment by oliviertassinari** [comment]
@hongyuan1306 Does it work with this one?

[invoice-2022-3156.pdf](https://github.com/mui/mui-x/files/8144981/invoice-2022-3156.pdf)

**Comment by hongyuan1306** [comment]
Yes. I can download the PDF file, though the company name and address in Chinese are not displayed correctly due to incorrect font specification. For our accounting the file would do though.

![image](https://user-images.githubusercontent.com/10390407/155846531-50b1810f-fc80-4bfd-9f50-47afbada2183.png)

I suppose it is these Chinese characters that caused the online pdf reader to crash in the first place. Thanks for your fast response.
