### ISSUE TITLE
[data-grid] Create striped rows

### ISSUE THREAD

**Issue by wahajStar** [mui/mui-x#4054]
### Order ID 💳

#32742

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

For all my Datagrid component I create a theme to show alternate color and pass it to the theme provider it works fine,
but now for just for few screen I dont neend that alternate color.

for alternate blue color I add the below code 
 // color:"blue",
          "& .MuiDataGrid-row": {
            "&:nth-of-type(2n)": {
              backgroundColor: " #EBF0F4 ",//even tealcolor
              '&:hover': {
                background: " #EBF0F4  !important",
             },
            }
          },
I tried to change it with    getRowClassName={(params) => `white`} 

.white{    
  background-color: white !important;

}
it change the backgroud color but nth-of-type(2n) get hover effect.
can u please give minimal solution for this.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
I am working on it on #3882 to give an easy way to do it.
But, you will have to implement the hover and other interaction [that you can find here](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/internals/components/containers/GridRootStyles.ts#L203) to let the grid know which color should be used in each scenario.

**Comment by m4theushw** [comment]
#3882 was merged and released. You can check the demo in https://mui.com/x/react-data-grid/style/#striped-rows to create striped rows.

**Comment by acentrella13** [comment]
Hi this is using @mui/material/styles what if you use emotion?
