### ISSUE TITLE
[DataGrid] `GridFilterPanel` UI Issue

### ISSUE THREAD

**Issue by Hameezr** [mui/mui-x#4061]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Outlined variant doesn't work correctly. 

While setting the variant of linkOperatorInputProps in FilterPanel, as outlined, the label cuts the outlined border. 

### Expected behavior 🤔

The variant outlined should not cut the border for the grid Filter Panel. 

### Steps to reproduce 🕹

Steps:

1. Override componentProps for filter Panel
2. Set variant as outlined for linkOperatorInputProps
3. The label will cut the border

```
componentsProps={{
filterPanel: {
              filterFormProps: {
                linkOperatorInputProps: {
                  variant: 'outlined',
                  size: 'small',
                  sx: {mt: 'auto'},
                },
              },
           }
     }}
```

https://codesandbox.io/s/customfilterpanelcontent-material-demo-forked-948jwd?file=/demo.js:1865-1887

### Context 🔦

I am trying to keep my theme consistent and use outlined textfields all over my app.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 12.0.1
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.1
```
</details>

**Comment by flaviendelangle** [comment]
@alexfauquette it is probably related to #3497

**Comment by Hameezr** [comment]
> @alexfauquette it is probably related to #3497
A screenshot to elaborate the issue
![image](https://user-images.githubusercontent.com/59111588/156129804-fa18eff1-d388-4909-a8e8-8d84bd85ba8c.png)

**Comment by Hameezr** [comment]
> 

Hiding the Label would do the trick! I was curious is there any way to change the icons in the filter panel as well? If not, maybe I can add a contribution for it! 

Thank you for your timely response

**Comment by alexfauquette** [comment]
To update icons, you have the [slot](https://mui.com/api/data-grid/data-grid/#slots) which allows overriding components (including icons)
