### ISSUE TITLE
Pagination on Grid and GridPro is not Aligned

### ISSUE THREAD

**Issue by sarahbumiller** [mui/mui-x#4076]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I had the same problem with DataGrid and DataGridPro. The pagination at the bottom of the grid is not aligned center like it shows in your documentation. This is what the pagination looks like on my grid. I tried wiping out all css in my app to see if it was inheriting something and nothing changed.

<img width="428" alt="Screen Shot 2022-03-02 at 4 47 00 PM" src="https://user-images.githubusercontent.com/69884305/156475093-dd8ab1ba-e9de-4f0a-ac69-ddd4ec740c96.png">
 

### Expected behavior 🤔

I expect the pagination navigation to look like it does in your [documentation](https://mui.com/components/data-grid/pagination/).

![Screen Shot 2022-03-02 at 4 55 37 PM](https://user-images.githubusercontent.com/69884305/156475329-497e0e82-12a4-4e48-b276-fe7a2fd78493.png)

### Context 🔦

I am trying to get the pagination aligned centered.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Hi @sarahbumiller,

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

Without a reproduction, we can not investigate the problem you're facing

**Comment by cmhernandezdel** [comment]
Hello, I am having this same exact problem on Firefox and Safari on the latest macOS. 

I am just doing the following:

```
const [dataError, setDataError] = useState(null);
const [dataLoading, setDataLoading] = useState(false);

const dataGridColumns = [
    { field: 'id', hide: true },
    { field: 'name', headerName: intl.formatMessage({ id: "devices.tableHeaderName" }), width: 200 },
    { field: 'ipAddress', headerName: intl.formatMessage({id: "devices.tableHeaderIpAddress"}), width: 200 },
    { field: 'httpPort', headerName: intl.formatMessage({id: "devices.tableHeaderPort"}), width: 200 },
    { field: 'username', hide: true },
    { field: 'password', hide: true },
    {
        field: 'actions',
        type: 'actions',
        width: 80,
        getActions: (params) => [
            <GridActionsCellItem icon={<EditIcon />} onClick={() => editDeviceClick(params.row.id)} label={intl.formatMessage({ id: "devices.tooltipEdit" })} />,
            <GridActionsCellItem icon={<DeleteIcon />} onClick={() => deleteDeviceClick(params.row.id)} label={intl.formatMessage({ id: "devices.tooltipDelete" })} />,
          ]
    }
];

const handleTablePageSizeChange = (params) => {
    setTablePageSize(params.pageSize);
}

return(
<Grid item xs={12} lg={10} >
    <DataGrid columns={dataGridColumns} rows={data} pageSize={tablePageSize} onPageSizeChange={handleTablePageSizeChange} rowsPerPageOptions={[5, 10, 20, 50]} pagination autoHeight loading={dataLoading} error={dataError} />
</Grid>
);
```

It looks like this:

<img width="352" alt="imagen" src="https://user-images.githubusercontent.com/46526071/176159842-8d3cb9a5-1890-422a-bbd4-37f8a213f8a9.png">


I encountered this problem when upgrading to MUI v5, it didn't happen on v4.

**Comment by alexfauquette** [comment]
@cmhernandezdel I tried to reproduce your problem without success

https://codesandbox.io/s/data-grid-community-forked-cyfzg6?file=/src/App.tsx

Could you write a codesandbox reproducing your bug such that we can have a look?

**Comment by ngocnguyenbk** [comment]
Do you use [Bootstrap](https://getbootstrap.com/)?

![Screenshot from 2022-06-30 20-43-43](https://user-images.githubusercontent.com/22522452/176692897-15d252e1-23b0-475b-a82c-ff86f803f457.png)

**Comment by tomershay** [comment]
If you're using Bootstrap, you can work around the margin issue by adding the custom style mentioned below.
Not the ideal solution, but it will work...

  ```
<DataGrid
  .....
  sx={{
      ".MuiTablePagination-displayedRows": {
        "margin-top": "1em",
        "margin-bottom": "1em"
      }
    }}
   />
```

**Comment by jtgdeb** [comment]
> If you're using Bootstrap, you can work around the margin issue by adding the custom style mentioned below. Not the ideal solution, but it will work...
> 
> ```
> <DataGrid
> .....
> sx={{
>     ".MuiTablePagination-displayedRows": {
>       "margin-top": "1em",
>       "margin-bottom": "1em"
>     }
>   }}
>  />
> ```

This works, but you also want to add ".MuiTablePagination-selectLabel" to the classes.  Otherwise, you'll only align the Pages & back and forth arrows.

      sx={{
          ".MuiTablePagination-displayedRows, .MuiTablePagination-selectLabel": {
            "margin-top": "1em",
            "margin-bottom": "1em"
          }
        }}

**Comment by dougwithseismic** [comment]
Thank you! Consolidating, add both of these to your `sx={...}` property ```
                  '.MuiTablePagination-displayedRows': {
                    'margin-top': '1em',
                    'margin-bottom': '1em'
                  },
                  '.MuiTablePagination-displayedRows, .MuiTablePagination-selectLabel': {
                    'margin-top': '1em',
                    'margin-bottom': '1em'
                  }
```
