### ISSUE TITLE
[DataGrid] Need Handlers for Show All and Hide All Column Options

### ISSUE THREAD

**Issue by Vishal-Patil-Gslab** [mui/mui-x#4085]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

version used
- material ui core - 4.11.0
- x-data-grid-pro - 4.0.2

Currently when changing the visibility of any specific column the `onColumnVisibilityChange` handler is trigger and we are able to track the column visibility and able to store the hide/visible column details.

But on Clicking on `Show All` or `Hide All`  the `onColumnVisibilityChange`  handler is not trigger and we are not able to track the column visibility and are not able to store the hidden/Visible column details.

we check the latest version and saw the `onColumnVisibilityChange` is deprecated but **we can't migrate from v4 to v5 currently**

Can we have any quick workaround for this issue, can we get the handler for  `Show All` or `Hide All`  or any other workaround will work 

![image](https://user-images.githubusercontent.com/100920255/156732991-0224ca6f-2ccd-4ce2-b737-76834d79e048.png)

**Comment by flaviendelangle** [comment]
> we can't migrate from v4 to v5 currently

Why can't you migrate from v4 to v5 ? 
We have a doc section explaining how to use X in v5 and the other packages in v4 (see [this page](https://mui.com/components/data-grid/migration-v4/#using-mui-x-v5-with-mui-core-v4))

We won't bring any new major feature on v4.

You can listen to `onStateChange` and check the columns in the state, but it will be terrible performance-wise.
