### ISSUE TITLE
[data-grid] Setup a package to publish the DataGridPremium.

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#4090]
# Summary 
We'll publish our premium features with a third component on a third package, and so we need to establish the new structure and migrate the experimental features (Row grouping and Excel export) there.

# Objective
Essentially what we're going for is the following import structure:

`import { DataGridPremium } from '@mui/x-data-grid-premium';`

# Why?
It’s very clear, by reading the imports of a demo, which plan the users would need. 
And It's the fastest way to achieve:
* Clear imports
* Clear typing of exported interfaces
* Clear typing of props
* Tree shaking.

**Comment by flaviendelangle** [comment]
- [ ] Add a warning when `props.experimentalFeature.rowGrouping: true` (same for Excel) on `DataGridPro` to say that the feature moved to `@mui/x-data-grid-premium`
