### ISSUE TITLE
[data-grid] Master detail/panel - Height based on the content

### ISSUE THREAD

**Issue by sshty2018** [mui/mui-x#4091]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently when using master detail panel feature in datagrid, the panel height should be provided upfront.
Is there any way workaround to have the master detail panel height the same height as the content in it and also dynamic to the changes in content.

### Motivation 🔦

Example: https://codesandbox.io/s/dazzling-wood-f1w54e?file=/src/App.js

**Comment by m4theushw** [comment]
We don't support yet having an unknown height and calculate it from the content. We may add this with #417.

However, you can implement it in your side by calculating the content size and passing it to `getDetailPanelHeight`. You can take as inspiration https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js. Basically you render the content in a hidden DIV, then get the height of the element.

**Comment by palle-k** [comment]
I've implemented a workaround for this, which measures the dimensions of the detail view after it is rendered. This data is then passed to the data grid through `getDetailPanelHeight`. Here, I'm passing the measured height of the child or a default value, if not yet measured: `() => detailViewBounds?.height ?? 500`

However, this leads to an issue: The change in the detail view height is not correctly applied throughout the entire data grid. While the spacing between the expanded row and the row below it is correctly adjusted, the height of the entire data grid is not - leaving empty space at the bottom if the fallback height (500) is an over-estimate or truncating the bottom end of the data grid if the fallback height is an under-estimate.

**Comment by cherniavskii** [comment]
Hey @palle-k 
Can you open an issue with a minimal reproduction of unexpected layout using `getDetailPanelHeight`?

**Comment by palle-k** [comment]
@cherniavskii #4784

**Comment by alextaymx** [comment]
I saw a Pull Request implementing dynamic height, may i know how do i install this latest feature?

**Comment by flaviendelangle** [comment]
Should be in about 5mn :laughing:
