### ISSUE TITLE
[DataGrid] The `isOverflown` utility function is no longer exported

### ISSUE THREAD

**Issue by manishprivet** [mui/mui-x#4115]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We have been recently migrating from `@material-ui` to `@mui`, and one of our components was using the `isOverflown` function from `@material-ui/data-grid` to check for overflowing cells and displaying a toolbar accordingly. 

However, `@mui/x-data-grid` doesn't seem to have any similar function in it's export.

**Comment by flaviendelangle** [comment]
We removed this export because it is a general purpose utility function not really related to the grid.

You can copy paste its content into your application

```ts
function isOverflown(element) {
  return (
    element.scrollHeight > element.clientHeight ||
    element.scrollWidth > element.clientWidth
  );
}
```
