### ISSUE TITLE
[data grid] How to hide the checkbox selection field from the columns menu panel

### ISSUE THREAD

**Issue by ak-mid** [mui/mui-x#4125]
### Order ID 💳

35878

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm using the data grid with checkboxSelection enabled. That means the first column of my grid are checkbox cells. Now I want to hide that checkbox column from the columns menu panel completely.

![image](https://user-images.githubusercontent.com/60788147/157238007-66a17473-a593-4fd8-8bd5-e92f40641246.png)

The only possible setting I saw was ` hideable: false`, which only deactivates the toggle switch but doesn't hide it. Is there a way to hide (remove) the checkbox field completely from the columns menu panel?

BTW: I tried to use `{ field: '__check__', hideable: false }` which will also remove all checkboxes from the grid cells which looks like a bug to me.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
It is currently not possible to hide instead of disabling the toggle.
We could add a `hideDisableLines` prop to `ColumnsPanel` to customize this behavior.

@alexfauquette what do you think ?

____


> BTW: I tried to use { field: '__check__', hideable: false } which will also remove all checkboxes from the grid cells which looks like a bug to me.

This one is being discussed on https://github.com/mui/mui-x/issues/3420
If you add a `__check__` column, the grid takes for granted that the column you give is a valid selection column and therefore does not add its own.

**Comment by alexfauquette** [comment]
I see a conflict about the future reordering columns feature?

If I have the following columns
- col A
- col B (disabled and hidden)
- col C
- col D

When dragging "col D" between A and C. Should it be placed between A and B or between B and C

**Comment by ak-mid** [comment]
Is there a CSS solution to hide the first row?
I tried to access the columnsPanel via sx prop but failed.

```
componentsProps={{
  columnsPanel: {
    sx: {
      "& .MuiDataGrid-panelContent": { backgroundColor: "blue" }
          }
    }
}}
```

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/datagrid-v5-quick-start-forked-zdrlhv?file=/src/App.tsx

Seems like we aren't passing the props of `GridColumnsPanel` to the DOM
But the following is working because we do pass the props of `GridPanel` to the DOM which is the parent of `GridColumnsPanel`.

```ts
        componentsProps={{
          panel: {
            sx: {
              [`& .MuiDataGrid-columnsPanel > div:first-child`]: {
                display: "none"
              }
            }
          }
        }}
```

**Comment by alexfauquette** [comment]
@ak-mid Seems that it's a bug from our side

The property you specify `componentsProps?.columnsPanel` is passed to the columnPanel: 

https://github.com/alexfauquette/material-ui-x/blob/ab686675f7c25a8dd6099e20f0822bd4a3c265e4/packages/grid/x-data-grid/src/components/panel/GridPreferencesPanel.tsx#L32:L33

But the default `GridColumnsPanel` does not accept props. 
https://github.com/alexfauquette/material-ui-x/blob/ab686675f7c25a8dd6099e20f0822bd4a3c265e4/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx#L61:L61

I'm opening a dedicated issue for that

**Comment by ak-mid** [comment]
@flaviendelangle Thanks for the code snippet. That did work out for me!

**Comment by Ankur-Marwaha** [comment]
This is possible in newer mui version (7.3.1)
This screenshot explains how you can do it.
<img width="646" alt="image" src="https://github.com/mui/mui-x/assets/13932929/4aa52928-8aa7-46f8-9588-387a27468bca">


After doing this, you will not see the option in the columns section.
and still see the checkboxes in the table.

**Comment by surajsingh-accuknox** [comment]
> This is possible in newer mui version (7.3.1) This screenshot explains how you can do it. <img alt="image" width="646" src="https://private-user-images.githubusercontent.com/13932929/326712403-4aa52928-8aa7-46f8-9588-387a27468bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTAwODUsIm5iZiI6MTcxNDQ4OTc4NSwicGF0aCI6Ii8xMzkzMjkyOS8zMjY3MTI0MDMtNGFhNTI5MjgtOGFhNy00NmY4LTk1ODgtMzg3YTI3NDY4YmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE1MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MmY4ODdhMWJlODUyNmUzNGM5NTBiZjhiNjAzNDBjOGUxNWM4OTlkMzQ1ZDgzODkyZWFhNmYyYmY3MWVlYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5a3WVBnqIlcftH1zrm7bt2HISxaDJUC1ppYFA-GP9As">
> 
> After doing this, you will not see the option in the columns section. and still see the checkboxes in the table.

is there a way to implement this in v6 ?

**Comment by flaviendelangle** [comment]
Thanks a lot for your detailed example
It seems that this issue was missed when `getToggableColumns` was introduced
I think we can close the issue @cherniavskii , I let you do it or re-purpose it for doc improvement if the feature is not correctly documented :pray:

**Comment by suretrust** [comment]
For those that have the older version of MUI, you can disable this without breaking the search using:

```css
slotProps={{
  panel: {
    sx: {
      // hide disabled columns from the column panel
      '& .MuiDataGrid-columnsPanel > div:has(input:disabled)': {
        display: 'none',
       },
     }
   },
}}
```

**Comment by michelengelen** [comment]
IMO there is enough information for anyone searching for a solution. I'll close it, but feel free to add comments if you encounter any problems with the solutions provided here! Thanks @all! 🙇
