### ISSUE TITLE
[DataGrid] Add MUI Select component to data grid filter panel 

### ISSUE THREAD

**Issue by erfanansari** [mui/mui-x#4127]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

So what I'm saying is that the select box for choosing columns and operators of the filter panel is not consistent with the rest of the design and uses that native look
I would appreciate it if you add support of [Select](https://mui.com/components/selects/) component to provide a consistent UI

### Examples 🌈

![Screenshot 2022-03-08 192929](https://user-images.githubusercontent.com/64015416/157275758-12347de4-5a64-48dc-a20c-5fa93401b002.png)

**Comment by erfanansari** [comment]
So I added what you said and it now uses the Select component, however, the bug that you mentioned is with it
`   <DataGrid
                rows={rows}
                columns={columns}
                componentsProps={{
                    ...componentsProps,
                    baseSelect: { native: false },
                }}
    />
`
I noticed that you said that using `mouseEvent=onMouseUp‍‍` can prevent this bug from happening
But I didn't understand where/how to use it
Would you please provide an example of it?
It can also be added to the official docs later for those who need it

**Comment by m4theushw** [comment]
> But I didn't understand where/how to use it

We need to make two changes in our side to allow `native=false`. The first is to change `GridPanel` to apply `mouseEvent=onMouseUp`. Then, the Select needs to use `MenuItem` instead of `option` for the options. But this last change should only take effect if `native=false`, to not be a breaking change for users that want the native look. If you want to open a PR with the diff above feel free.

**Comment by m4theushw** [comment]
@iEquos We have not started yet.

**Comment by kyeongsoosoo** [comment]
@m4theushw If someone hasn't started yet, can I take it?

**Comment by m4theushw** [comment]
@kyeongsoosoo Yes, feel free to submit a PR.
