### ISSUE TITLE
[data-grid] getVisibleRowModels not updating on first filterModel interaction, or when clicking a Delete Filter button

### ISSUE THREAD

**Issue by JTAPPSCORE** [mui/mui-x#4131]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In the Data Grid Pro, on the very first interaction with the filter model (i.e. first keystroke in the value field), getVisibleRowModels is not updating to reflect the changes in the table. 

getVisibleRowModels also doesn't update when clicking the 'Delete Filter' (X) button on a specific filter, however it does update if remove the filter by deleting the value using back strokes.

Other than these instances,  getVisibleRowModels return value is in sync with the table data. 

The table itself is updating in these instances, it is just the return value of getVisibleRowModels that does not update. It also appears that apiRef.current.state.filter is not being updated in the described instances either.

I am using this in the onFilterModalChange event handler, which is firing when it is supposed to.

### Expected behavior 🤔

On first interaction with the filter dropdown, and when deleting a filter using the Delete Filter (X) button, getVisibleRowModels should return the updated grid data.

### Steps to reproduce 🕹

Steps:

1. Add an apiRef to DataGridPro component
2. Log either apiRef.current.state.filter.filteredRowsLookup or apiRef.current.getVisibleRowModels()
3. Click on the FILTER button in the toolbar
4. Type one character into the value field OR apply a filter then click the 'Delete filter' (X) button
5. Observe that the returned rows do not reflect the current state of the table 

### Context 🔦

I wanted to use the filtered rows in order to render summary cards whose data only reflects the filtered rows in the data grid in sync with the table. As stated above, this works the majority of the time apart from the aforementioned cases

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 11.6
  Binaries:
    Node: 14.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.53
    @mui/icons-material: ^5.0.3 => 5.0.3
    @mui/material: ^5.0.6 => 5.0.6
    @mui/private-theming:  5.0.1
    @mui/styled-engine:  5.2.4
    @mui/styles: ^5.0.1 => 5.0.1
    @mui/system: ^5.2.4 => 5.2.4
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: ^5.5.1 => 5.5.1
    @mui/x-data-grid-pro: ^5.5.1 => 5.5.1
    @mui/x-license-pro:  5.5.1
    @types/react:  16.9.16
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^4.4.1 => 4.4.1

Using Chrome
```
</details>

**Comment by cherniavskii** [comment]
I can reproduce the issue, here's a demo: https://codesandbox.io/s/basicexampledatagrid-material-demo-forked-4xc2gq?file=/demo.tsx
Open console, apply any filter and see the logs.

As a workaround, you can use `setTimeout`:
```tsx
onFilterModelChange={() => {
  setTimeout(() => {
	apiRef.current.getVisibleRowModels();
  }, 0);
}}
```

I'm adding @flaviendelangle to the discussion - maybe he can shed some light on the origin of this issue.

**Comment by flaviendelangle** [comment]
The update of the filter model and the update of the filtered rows are two different things.
The execution order is as follow:

1. Update the filter model in state
2. Publish `GridEvents.filterModelChange` /  `props.onFilterModelChange`
3. Compute the filtered rows
4. Update the filtered rows in state

Right now the computation of the filtered rows is done synchronously after the update of  the model.
But in the future, we could delay it, or even compute it in chunk, so this separation is very important.

____

We have an internal `visibleRowsSet` (which will be soon renamed `filteredRowsSet` or another naming) that is fired exactly when you need.
I think this event is worth making public.

So you have two solutions:

A: Use `setTimeout` in `onFilterModelChange`
B: Use `GridEvents.visibleRowsSet` (no prop callback associated) and be aware that you will have to rename it in a future version

**Comment by flaviendelangle** [comment]
I am closing this issue for lack of feeback
