### ISSUE TITLE
[Datagrid] The sorting and filtering are not applied to data added with `apiRef.current.updateRows` when `props.filterMode` is "server"

### ISSUE THREAD

**Issue by dangenendt** [mui/mui-x#4135]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Adding data with `apiRef.current.updateRows()` to a datagrid which has the sortmode / filtermode set to "server", will lead to just adding the new rows without checking / applying the current set filter- or sortmodel. 

### Expected behavior 🤔

Adding new rows with `apiRef.current.updateRows()` to a datagrid should check and apply the current set filter- or sortmodel and mui should decide to show or hide the new row. 

### Steps to reproduce 🕹

Steps:

1. Create a new DataGrid with 2 columns like "id" and "name"
2. Set filtermode to "server"
3. Set the filter to "id" => 2
4. trigger a function and use grid apiRef to call "apiRef.current.updateRows([ myNewObject ])"
5. independent of the the set filter, the grid will insert and show the new rows.
6. When you do the same with the filtermode "client", the grid will not show the data when they does not fit into the filtermodel

### Context 🔦

Currently im implementing a feature to update a datagrid via websockets. The grid is subscribed to a topic. When a message of this topic comes in, the grid takes the data from the event and pushes the new row to the datagrid.
I'am not quite sure if this is a bug or a feature. In my opinion there should be nothing against this approach like it is with the filtermode "client" or am i wrong?  

### Your environment 🌎

System:
    OS: macOS 12.1
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Edge: 99.0.1150.36
    Firefox: 92.0
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.8.1 => 11.8.1 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/icons-material: ^5.4.4 => 5.4.4 
    @mui/lab: ^5.0.0-alpha.71 => 5.0.0-alpha.71 
    @mui/material: ^5.4.4 => 5.4.4 
    @mui/styles: ^5.4.4 => 5.4.4 
    @mui/system: ^5.4.4 => 5.4.4 
    @mui/types:  7.1.2 
    @mui/x-data-grid-pro: ^5.5.1 => 5.5.1 
    @types/react: ^17.0.39 => 17.0.39 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.6.2 => 4.6.2 

Browser: current Brave

**Comment by flaviendelangle** [comment]
The server sorting and filtering has been designed so that the grid does not filter or sort the data at all because the server do it.
I don't think we should start filtering / sorting the data injected via `updateRows`, because the server sorting behavior might not be the same than the one of the grid, so using both at the same time will lead to some inconsistent behaviors.

But I am interested in having a reproduction case, I might be missing something.
This [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
