### ISSUE TITLE
[docs] Incorrect import

### ISSUE THREAD

**Issue by jamesdbruner** [mui/mui-x#4144]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Sorry to make a bug ticket for the docs having typos but this is essentially it: Throughout the data grid docs you'll find imports from `@mui/x-data-grid-generator` but that package doesn't exist. `@material-ui/x-data-grid-generator` is the correct import.

To reiterate...
```js
import { useDemoData } from '@mui/x-data-grid-generator';
```

Should be
```js
import { useDemoData } from '@material-ui/x-data-grid-generator';
```

**Comment by flaviendelangle** [comment]
https://www.npmjs.com/package/@mui/x-data-grid-generator

`@mui/x-data-grid-generator` does exist.

Our packages have been renamed from `@material-ui/...` to `@mui/...` last Fall.

**Comment by jamesdbruner** [comment]
Hmm well, I'm having issues installing that package in that case. My first guess would have been that you guys are using something like verdaccio or nexus internally which is why it resolves for you but I'm really not sure. It could just be my machine but other packages download and install just fine. This is the command I ran and the output: `npm i @mui/x-data-grid-generator`

```node
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Desktop/Projects/demo/node_modules/@mui/x-data-grid-generator/bin/data-gen-script.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Desktop/Projects/demo/node_modules/@mui/x-data-grid-generator/bin/data-gen-script.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

This is what my package.json deps looks like 
```json
  "dependencies": {
    "@emotion/react": "^11.8.1",
    "@emotion/styled": "^11.8.1",
    "@fontsource/roboto": "^4.5.3",
    "@mui/icons-material": "^5.5.0",
    "@mui/material": "5.5.0",
    "@mui/system": "^5.2.8",
    "@mui/x-data-grid-pro": "^5.6.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^1.0.7",
    "vite": "^2.8.0"
  },
  "peerDependencies": {
    "@mui/material": "^5.0.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  }
```

**Comment by m4theushw** [comment]
We forgot to update the path to `data-gen-script.js` in #3965. It will be fixed in the next release.

https://github.com/mui/mui-x/blob/949b40a683a19450e7ddab706a67e12ffc0b587b/packages/grid/x-data-grid-generator/package.json#L17

Just out of curiosity, why are you installing this package? It's only used to generate fake data.

**Comment by m4theushw** [comment]
Could you try again changing your `package.json` as bellow?

```diff
-"@mui/x-data-grid-generator": "latest"
+"@mui/x-data-grid-generator": "https://pkg.csb.dev/mui/mui-x/commit/71def566/@mui/x-data-grid-generator"
```

**Comment by jamesdbruner** [comment]
@m4theushw That does fix the initial issue I was having getting the package to install. Obviously I'll just wait until the next release to install it but I wanted to try out the package in the meantime and I ran into this issue below:

 Here's what my import looks like `import { randomTraderName } from '@mui/x-data-grid-generator'` and I'm just calling `randomTraderName()` like in your demos to generate a name for a cell/field but I get this error below:

<img width="611" alt="Screen Shot 2022-03-11 at 6 15 12 PM" src="https://user-images.githubusercontent.com/1911608/157998038-9ae0d65f-55c6-411b-93cc-1535718e4400.png">

<img width="1093" alt="Screen Shot 2022-03-11 at 6 13 31 PM" src="https://user-images.githubusercontent.com/1911608/157998031-661d7de4-e6e5-433f-aea3-e0c5c84832d1.png">

**Comment by m4theushw** [comment]
`process.env` is only available in a Node.js environment. On the web, the bundler usually provides a fallback value to avoid crashing. It appears that Vite doesn't provide one. Can you try https://github.com/vitejs/vite/issues/1973#issuecomment-787571499?

**Comment by jamesdbruner** [comment]
@m4theushw That totally works. Thank you so much for your help!

**Comment by oliviertassinari** [comment]
@m4theushw Should we update https://github.com/mui/material-ui/blob/master/examples/vitejs/vite.config.js?

**Comment by m4theushw** [comment]
@oliviertassinari The DataGrid is compatible with vite. The problem is only `@mui/x-data-grid-generator`. I opened #4193 with a small fix we can do in our side to make this package compatible too.
