### ISSUE TITLE
[Data Grid] Enable double click to activate checkbox

### ISSUE THREAD

**Issue by minhnhat10** [mui/mui-x#4147]
Hello everyone, I'm implementing a data grid and I want with each event like single click, double click on checkbox. It will have color respectively to that event. For example, when user click on checkbox that will have green color and with double click checkbox will have orange color. I'm highly appreciate any help. Thank you very much!

**Comment by minhnhat10** [comment]
@alexfauquette Thank you for the answer. I would like to ask one more question. I need to customize checkbox component in datagrid and I did like this in this sandbox [(sandbox)](https://codesandbox.io/s/datatable-material-demo-with-different-checkbox-mo715?file=/demo.js) . But, when I click on pagination the state of previous checked rows were disappeared. Is this a bug or the lack of in implementation. Thank you very much!

**Comment by alexfauquette** [comment]
That's a bug in your implementation:

Your component does not accept any props
```jsx
function CheckboxWrapper() {
  return (
    <Checkbox
      icon={<CircleUnchecked />}
      checkedIcon={<CircleCheckedFilled />}
    />
  );
}
```

So when internally we pass it `onChange` props, this prop is neither applied and so the component state is updated but not the grid. A solution is to propagate props to the mui component as follow:

```jsx
function CheckboxWrapper(props) {
  return (
    <Checkbox
      {...props}
      icon={<CircleUnchecked />}
      checkedIcon={<CircleCheckedFilled />}
    />
  );
}
```

Here is the proposed fix: https://codesandbox.io/s/datatable-material-demo-with-different-checkbox-forked-qi4cox?file=/Checkbox.js
