### ISSUE TITLE
[DataGridPro] Performance issue with `renderCell`

### ISSUE THREAD

**Issue by pkitcha** [mui/mui-x#4152]
Hello Guys,

When using X-DATAGRID-PRO with 200 rows ++. I found a performance issue with renderCell in column definition 

` const columns = [
    { field: "id", headerName: "ID", width: 60, hide: false },
    {
      field: "orderQty",
      headerName: "orderQty",
      headerClassName: "grid-header",
      headerAlign: "center",
      width: 100,
      hide: false,
      disableColumnMenu: true,
      **renderCell: (params) => (
        <div style={{ width: "100%" }}>
          <TextField
            id="k3"
            inputProps={{ readOnly: true, style: { textAlign: "right" } }}
            value={params.value}
          />
        </div>
      )**
    },`
 
I have created two version of DataGridPro to compare the performance and I can see that RenderCell is an issue when try to scroll down.

[https://codesandbox.io/s/datagridprodemo-material-demo-forked-phk4ju](https://codesandbox.io/s/datagridprodemo-material-demo-forked-phk4ju)

Any suggestion ?

**Comment by flaviendelangle** [comment]
I think the problem here is the amount of `TextField` rendered
If I keep the `renderCell` but just return a div with the value, I got a smooth scrolling (see [this example](https://codesandbox.io/s/datagridprodemo-material-demo-forked-6bjknu?file=/demo.js))

Is it a requirement to have all your cell as input ? 
The grid supports editing (see [the documentation](https://mui.com/components/data-grid/editing/#main-content)) to only render and editing version of a cell / row when it is being edited.

**Comment by m4theushw** [comment]
The TextField is a heavy component. Even with virtualization there're around 40 instances mounted in the grid. Another alternative would be to use the native `<input />`.

**Comment by flaviendelangle** [comment]
Those are fairly light components to render, I don't think we did anything very smart for them :laughing: 

The best you can do to keep your `TextField` is to memoize them to avoid re-render on scrolling 
See [this example](https://codesandbox.io/s/datagridprodemo-material-demo-forked-1z0ov7?file=/demo.js)

You will still have all the cost to mount those components, but it seems to be a lot smoother.

**Comment by pkitcha** [comment]
> Those are fairly light components to render, I don't think we did anything very smart for them 😆
> 
> The best you can do to keep your `TextField` is to memoize them to avoid re-render on scrolling See [this example](https://codesandbox.io/s/datagridprodemo-material-demo-forked-1z0ov7?file=/demo.js)
> 
> You will still have all the cost to mount those components, but it seems to be a lot smoother.

Favien,  

Thank you very much . Can you share me the example of fairly light components for button and progressbar.

**Comment by pkitcha** [comment]
> You can find all the components used in `@mui/x-data-grid-generator` [here](https://github.com/mui/mui-x/tree/master/packages/grid/x-data-grid-generator/src/renderer)
> 
> For instance [here is the progress bar](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid-generator/src/renderer/renderProgress.tsx)

Flavien,

Last question ,is it possible to combine the filter model with AND an OR operator.

**Comment by m4theushw** [comment]
To add the IconButton you can use the `actions` column type: https://mui.com/components/data-grid/columns/#special-properties

**Comment by flaviendelangle** [comment]
> Last question ,is it possible to combine the filter model with AND an OR operator.

Not yet
But it is something that we will need to implement at some point.
