### ISSUE TITLE
[DataGrid] Two rows are deselected when using the shift key

### ISSUE THREAD

**Issue by yami03** [mui/mui-x#4156]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Select multiple rows.
Deselect the last selected row using the Shift key.

Two rows are deselected.

https://user-images.githubusercontent.com/36615680/157634519-97b1c535-c709-4c4d-ac17-769f9008954d.mov

### Expected behavior 🤔

Only one row is deselected.

### Steps to reproduce 🕹

Steps: https://codesandbox.io/s/233v6d?file=/demo.tsx MUI official example

1. Select multiple rows
2. Deselect the last selected row using `shift key + click`.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 12.1
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Not Found
    Firefox: 78.0.2
    Safari: 15.2
  npmPackages:
    @types/react: ^17.0.3 => 16.14.1 
    react: ^17.0.2 => 16.14.0 
    react-dom: ^16.13.1 => 16.14.0 
    styled-components: ^5.2.0 => 5.2.1 
    typescript: ^4.2.3 => 3.8.3 
```
</details>

**Comment by flaviendelangle** [comment]
The new behavior is to not unselect the row at all when pressing it.

Gmail unselects the clicked row
Windows and Google Drive do not unselect the clicked row

We went for the 2nd option

**Comment by yami03** [comment]
I understand. Thanks!
