### ISSUE TITLE
Datagrid pro is not showing the option to select number of rows in footer

### ISSUE THREAD

**Issue by Utkarshk7** [mui/mui-x#4161]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We have started using data grid pro instead of the public data Grid version.
Datagrid pro is not showing the option to select number of rows in footer. We have already followed GIT issues reported for this. This works fine for Datagrid (public version) but not Datagrid Pro version

FYI- We have the pageSize and rowsPerPageOptions set already

### Expected behavior 🤔

We should see the option to select the number of rows in footer for the licensed Datagrid Pro version if pageSize and rowsPerPageOptions is maintained

### Steps to reproduce 🕹

Steps:

1. Use Datagrid pro version
2. Provide PageSize and rowsPerPageOptions in code
3. Test the Data grid
4.

### Context 🔦

Users are unable to select number of rows

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

Order #39429

**Comment by alexfauquette** [comment]
Did you set the `pagination` prop?

As explained in the [doc](https://mui.com/components/data-grid/pagination/), the `DataGridPro` does not set pagination by default, because you do not have the 100 lines limitation, so you can have all your rows in one page

> The default pagination behavior depends on your plan.
>
> On the `DataGrid`, pagination is enabled by default and can't be disabled
> On the `DataGridPro`, pagination is disabled by default, use the `pagination` prop to enable it

**Comment by Utkarshk7** [comment]
Set the pagination prop and all looks good. Thanks!

**Comment by NemanjaTHM** [comment]
> Hey @Utkarshk7 Can you provide an example reproducing the issue?
> 
> Also, make sure to check out [Pagination docs](https://mui.com/components/data-grid/pagination/#size-of-the-page). Remember, that you have to provide `pageSize` and `onPageSizeChange` props, here's a working demo: https://codesandbox.io/s/pagesizecustomoptions-material-demo-forked-w0lclg?file=/demo.tsx

@cherniavskii Your example is not working. You only have 25, 50 and 100. I am facing the same issue right now that custom numbers for page size are not accepted.
