### ISSUE TITLE
Adding renderCell for reducing the value lags the app 

### ISSUE THREAD

**Issue by forjen127** [mui/mui-x#4182]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Adding a rendercell does display the data. However, scrolling to either left or right will lag it so much. I also can't use the filter anymore due to its lags and the page becomes unresponsive. 

### Expected behavior 🤔

Should be able smoothly scroll from the left to right and the page won't become unresponsive.

### Steps to reproduce 🕹

https://codesandbox.io/s/controlledfilters-material-demo-sample-qy2qf7?file=/demo.js)
```

{
      field: "cartItems",
      headerName: "Cart Items",
      type: "number",
      width: 400,
      align: "center",
      renderCell: ({ value }) => {
        const t = Object.entries(
          value.reduce((prev, item) => {
            if (!prev[item.id]) prev[item.id] = { ...item, nest: [] };
            prev[item.id].nest.push(item);
            return prev;
          }, {})
        ).map(([id, obj], idx) => (
          <List key={id + obj.color}>
            <ListItemText primary={obj.name + " " + obj.size} />
            <li>
              {obj.nest.map((nest, idx) => (
                <li key={idx}>
                  <ListItemText
                    secondary={nest.color + " (" + nest.quantity + " pcs)"}
                  />
                </li>
              ))}
            </li>
          </List>
        ));
        console.log(t);
        return t;
      }
    },
```

### Context 🔦

I wanted to display the cart items in a List

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
It seems it is a performance issue in your `renderCell` function

Instead of doing

```jsx
renderCell: ({ value }) => {
	  const t = Object.entries(
		  value.reduce((prev, item) => {
			  ..., {})
	  ).map(([id, obj], idx) => (<List>...</List>))
	  return t
}
```

I did 
```jsx
renderCell: ({ value }) => {
	  const formatedValue = Object.entries(
		  value.reduce((prev, item) => {
			  ..., {})
	  );
	  
	  return <>{formatedValue.map(([id, obj], idx) => (<List>...</List>))}</>
}
```

And it does not lag anymore. Could not explain why

**Comment by cherniavskii** [comment]
I played with it a bit and removing this line fixes the issue:

```ts
console.log(t);
```

Demo: https://codesandbox.io/s/controlledfilters-material-demo-sample-forked-t7b3vs?file=/demo.js

**Comment by cherniavskii** [comment]
I think we can close it now, since I don't see any issues with data grid here.
