### ISSUE TITLE
[DataGridPro] Pinned columns edge overflow with custom borderRadius

### ISSUE THREAD

**Issue by socramm9** [mui/mui-x#4187]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The edge of pinned columns overflow borderRadius of grid:
<img width="1111" alt="Bildschirmfoto 2022-03-14 um 15 42 08" src="https://user-images.githubusercontent.com/52098754/158196543-9ff035d4-9c5b-4b23-a2d6-47a90a0bd171.png">

### Expected behavior 🤔

Edge of pinned rows should not overflow

```
.MuiDataGrid-root {
    overflow: hidden
}
```

### Steps to reproduce 🕹

Steps:

1. https://codesandbox.io/s/datagridpro-v5-quick-start-forked-s581lx?file=/src/App.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#26327

**Comment by cherniavskii** [comment]
Hey @socramm9 
Thanks for opening the issue!
Do you want to submit a pull request?

The `overflow: hidden` should be applied here:
https://github.com/mui/mui-x/blob/ffcc4cf69c0f3cd2df760cb1969d00200f1be65c/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts#L71-L73

**Comment by socramm9** [comment]
I can try. I never did it before so correct me if I do something wrong

**Comment by cherniavskii** [comment]
@socramm9 sure, just let me know if you encounter any issues

**Comment by socramm9** [comment]
Its not that big of a deal but I think my `overflow: hidden` could need some more work

<img width="227" alt="Bildschirmfoto 2022-03-14 um 19 14 32" src="https://user-images.githubusercontent.com/52098754/158235487-0af74a4e-97f9-4e8e-9c66-641c040aca32.png">

The issue now is that the cell active border get cut off.

Its only a minor inconvenience and probably most of Users wont even notice it. But is maybe something to keep in mind

**Comment by m4theushw** [comment]
Note that `outline` doesn't follow the shape of the element. You have to use another approach, e.g. `box-shadow`, and apply the same border radius to the column headers.

**Comment by cherniavskii** [comment]
@m4theushw it seems to work in Chrome, not sure about other browsers though

<img width="495" alt="Screenshot 2022-03-15 at 14 01 18" src="https://user-images.githubusercontent.com/13808724/158383323-d4fba4f9-afb6-43af-8a9a-28346e217542.png">

**Comment by m4theushw** [comment]
@cherniavskii Yeah, I updated my answer. The point was more that `outline` doesn't play with `overflow: hidden` out-of-box.
