### ISSUE TITLE
[data-grid] Focus move back to cell when sorting after focusing a button on a cell

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#4189]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the focus is set on a grouping cell, clicking on the column header moves the focus back to the grouping cell the first time.

![treeFocus](https://user-images.githubusercontent.com/45398769/158227883-438c64fa-97bd-46d0-bd73-79d42203a79a.gif)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Can you give me a reproduction case ?
I tried on the first demos of the doc and was not able to reproduce

**Comment by alexfauquette** [comment]
The native focus must be on the button that expands/retracts the tree. If it is only on the cell it does not appear

The recor comes from this demo:
https://mui.com/components/data-grid/group-pivot/#custom-grouping-column

**Comment by cherniavskii** [comment]
I can no longer reproduce the issue in https://mui.com/x/react-data-grid/tree-data/#custom-grouping-column


https://github.com/mui/mui-x/assets/13808724/c85f4137-0ac3-41eb-aa92-6075dbd84618
