### ISSUE TITLE
Pinned Column tab stop order isn't updated when editMode is "row"

### ISSUE THREAD

**Issue by iluvmemes** [mui/mui-x#4190]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If a column is pinned, it's tab stop order isn't updated to match the location while in row edit mode.

### Expected behavior 🤔

- The tab stop movement should reflect the order of the columns as currently displayed on screen.

### Steps to reproduce 🕹

1. Open a datagrid pro datagrid that allows for pinned columns and row editing.
2. Pin the second column of the datagrid to the right side.  
3. Enter edit mode in a row at the first cell.
4. Press tab to move through all of the columns and watch the cursor jump to the pinned column in it's original tabstop index (1) and then back to the middle of the grid.

Additionally, if you set focus to the third column, and keep pressing tab, the focus will move out of the grid and into other browser controls.

In my sandbox, I have pinned the second column `email` by default.

https://codesandbox.io/s/controlpinnedcolumns-material-demo-forked-gxg2zg?file=/demo.js

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Original column order doesn't matter here - same happens when pinning last column to the right: https://codesandbox.io/s/controlpinnedcolumns-material-demo-forked-bu8qbq?file=/demo.js

I think the issue is column sections rendering order.
Here's the current order: https://github.com/mui/mui-x/blob/ffcc4cf69c0f3cd2df760cb1969d00200f1be65c/packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx#L286-L318

Rendering right columns after main render zone should fix the issue.

**Comment by iluvmemes** [comment]
> Original column order doesn't matter here - same happens when pinning last column to the right: https://codesandbox.io/s/controlpinnedcolumns-material-demo-forked-bu8qbq?file=/demo.js
> 
> I think the issue is column sections rendering order. Here's the current order:
>
> 
> Rendering right columns after main render zone should fix the issue.

Very likely would fix the tab order problem.  However, what about the tab key moving the focus out of the datagrid after the last column?

**Comment by cherniavskii** [comment]
> However, what about the tab key moving the focus out of the datagrid after the last column?

I would suggest to open separate issue and describe expected behavior in this case
