### ISSUE TITLE
[DataGridPro] Column pining issue with showCellRightBorder

### ISSUE THREAD

**Issue by socramm9** [mui/mui-x#4194]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I know the prop is called `showCell'Right'Border` but I think it should also be apply to the left border of columns pinned to the right

It is not that noticeable on light mode because of the shadow:
<img width="677" alt="Bildschirmfoto 2022-03-14 um 23 58 52" src="https://user-images.githubusercontent.com/52098754/158274651-d90db116-aed0-4488-b763-df5c3789c562.png">

But in dark mode you can see that it looks a little bit of:  
<img width="688" alt="Bildschirmfoto 2022-03-14 um 23 58 28" src="https://user-images.githubusercontent.com/52098754/158274907-05ab32a2-f722-42b2-a42c-6d0a5936b120.png">

### Expected behavior 🤔

Pinned columns section to the right should have a border on the right
<img width="659" alt="Bildschirmfoto 2022-03-15 um 00 14 46" src="https://user-images.githubusercontent.com/52098754/158275896-f0e289eb-115f-41a9-914e-841fab5c6147.png">

### Steps to reproduce 🕹

Steps:

1. https://codesandbox.io/s/datagridpro-v5-quick-start-forked-mfmpoy?file=/src/App.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#26327

**Comment by cherniavskii** [comment]
I can confirm the issue.
It's counter-intuitive, but I agree that we should add border-left to the right pinned column section

**Comment by socramm9** [comment]
> It's counter-intuitive, but I agree that we should add border-left to the right pinned column section

Maybe `showCellRightBorder` prop can be renamed to just `showVerticalBorder` or `showCellVerticalBorder`  or something else.

But something like that would probably need to wait for v6
