### ISSUE TITLE
[DataGrid] - GridToolbarExport 'touchRippleRef is missing in type {}' TypeScript Error

### ISSUE THREAD

**Issue by ncasale** [mui/mui-x#4199]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When attempting to create a custom DataGrid toolbar using the code outlined in [the docs](https://mui.com/components/data-grid/export/#custom-toolbar) I'm met with a TypeScript error saying:

`Property 'touchRippleRef' is missing in type '{}' but required in type 'Pick<GridToolbarExportProps, "form" | "slot" | "style" | "title" | "children" | "value" | "className" | "classes" | "color" | "translate" | "sx" | "key" | ... 275 more ... | "printOptions">'.`

It looks like this issue was addressed in [#2393](https://github.com/mui/mui-x/pull/2393) but I am still seeing this issue in the most recent release.

### Expected behavior 🤔

The docs suggest that the GridToolbarExport component should be usable without passing props.

### Steps to reproduce 🕹

Here is a [CodeSandbox Link](https://codesandbox.io/s/datagrid-v5-quick-start-forked-eilwj3?file=/src/App.tsx:27-1013). I attempted to use the TS Playground but kept running into errors.

### Context 🔦

Just trying to use basic export CSV functionality 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Using Chrome Browser 

 System:
    OS: macOS 12.1
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: Not Found
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Not Found
    Firefox: 98.0.1
    Safari: 15.2
```
</details>

<details>
  <summary>`TS Config`</summary>

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext", "es6"],
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"]
}

```
</details>

**Comment by cherniavskii** [comment]
Hey @ncasale 
What is your setup? Are you able to reproduce it locally?
This looks like a problem with our demos in Codesandbox/Stackblitz

**Comment by ncasale** [comment]
Hey @cherniavskii, yeah I was having the issue locally which prompted me to check if the CodeSandbox would also have the issue. I posted my envinfo/TS Config above. Here's my package.json:

<details>
  <summary>`package.json`</summary>

```
 {
  "name": "project-name",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.3.1",
    "@mui/lab": "^5.0.0-alpha.72",
    "@mui/material": "^5.3.1",
    "@mui/x-data-grid": "^5.5.1",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.0",
    "@types/node": "^16.11.21",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "axios": "^0.25.0",
    "date-fns": "^2.28.0",
    "formik": "^2.2.9",
    "immutability-helper": "^3.1.1",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "material-ui-phone-number": "^3.0.0",
    "react": "^17.0.2",
    "react-dnd": "^15.1.1",
    "react-dnd-html5-backend": "^15.1.2",
    "react-dom": "^17.0.2",
    "react-markdown": "^8.0.0",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0",
    "react-window": "^1.8.6",
    "typescript": "^4.5.5",
    "victory": "^36.3.1",
    "web-vitals": "^2.1.4",
    "yup": "^0.32.11"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```
</details>

My project was originally created through create-react-app's TypeScript template, and I've made sure to have the [minimum configuration](https://mui.com/guides/typescript/#minimum-configuration) outlined in the MUI Docs set up in my TS Config. 

As a workaround for now I've just added a ts-ignore to prevent the error from being thrown.


``` 
const ReturnsTableToolbar = () => {
    return (
      <GridToolbarContainer>
        {/* @ts-ignore: */}
        <GridToolbarExport  />
      </GridToolbarContainer>
    );
  };
```

Let me know if I can provide any other info that would be helpful.

**Comment by cherniavskii** [comment]
@ncasale can you try this repo? https://github.com/cherniavskii/cra-data-grid-test
I've started a new CRA typescript project and added data grid example with custom toolbar

**Comment by ncasale** [comment]
@cherniavskii I cloned that repo and it worked. I noticed that I was using @mui/material 5.3.1 in my project so I updated to the most recent version (5.5.1) and that removed the error on my end. Looks like this was user error - sorry for the false alarm, but thanks for the help.

**Comment by jcolvard** [comment]
Yes, thanks for the help. I had upgraded my my `@mui/x-data-grid-pro` package, but not my `@mui/material`. Same error, same solution. Thanks all for sharing and enabling me to find the solution quickly 🙌
