### ISSUE TITLE
DataGrid. Tooltip for boolean-type cell is always in English (true/false)

### ISSUE THREAD

**Issue by kodeschooler** [mui/mui-x#4203]
I'm using the grid locale translation keys and there doesn't seem to be a key to define the content inside the tooltip that's generated for boolean cell. The grid renders this:  ```<title>true | false</title>``` within an svg, and the content is in English even when I specify the localeText using the Spanish translations. I don't think there's a key for this, so how do you control what's displayed in the rendered <title> element? :

```
// define a column with a boolean type and specify the localeText for the DataGrid to use Spanish translations
const columns : GridColumns = [
{field: "enabled", type: "boolean", headerName: "Activado"}
] 

<DataGrid
  rows={rows}
  columns={columns}
  localeText = {esES.components.MuiDataGrid.defaultProps.localeText}
/>
```

It will display either true or false when you hover over the checkbox or x mark, regardless of what translations you use.  Is there a way to control this ? See image:

![BooleanCellTooltip](https://user-images.githubusercontent.com/24487551/158483982-c30cb61a-9eb2-454f-a309-636f6cfdf4eb.jpg)
?

**Comment by cherniavskii** [comment]
Hey @kodeschooler 
We're missing some translations - see https://github.com/mui/mui-x/issues/3211
But good news - you can help us to translate!

`es-ES` translations are located here - https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/locales/esES.ts
The ones you've noticed are `booleanCellTrueLabel` and `booleanCellFalseLabel`, but feel free to add other missing translations
