### ISSUE TITLE
Divider option for `getActions`

### ISSUE THREAD

**Issue by hanselsen** [mui/mui-x#4209]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In our current implementation, we're using `Menu`, `MenuItem` and `Divider` to accomplish the below.
![image](https://user-images.githubusercontent.com/1150323/158622456-cdbb19a9-023e-46ea-ad28-c605295508c3.png)

However, I cannot recreate the divider in the `DataGrid`.
I would suggest either another type to be accepted by `getActions`, or a `showDivider` attribute on the `GridActionsCellItem`.

### Examples 🌈

```C#
{
  field: 'account',
  type: 'actions',
  getActions: ({row}) => ([
    <GridActionsCellItem {...} showInMenu />,
    <GridActionsCellItem {...} showInMenu divider />
  ])
}
```
or 
```C#
{
  field: 'account',
  type: 'actions',
  getActions: ({row}) => ([
    <GridActionsCellItem {...} showInMenu />,
    <GridActionsCellDivider />
    <GridActionsCellItem {...} showInMenu />
  ])
}
```

### Motivation 🔦

Not being able to recreate what we have feels like a little step back instead of forward. 

### Order ID 💳 (optional)

#39643

**Comment by cherniavskii** [comment]
Hey @hanselsen 
Passing `divider` prop to `GridActionsCellItem` actually works - see working demo https://codesandbox.io/s/columntypesgrid-material-demo-forked-5qsn33?file=/demo.tsx:51-70

**Comment by hanselsen** [comment]
Oh boy. That was a tad embarrassing. I missed the fact that the type inherits the properties of `MenuItemProps`

**Comment by hanselsen** [comment]
@cherniavskii still, it is now harding to add a divider because I have to specify which item has to have a divider below it. Yet, I wish to specify the divider on the second last item.
Right now, I have this: 

```C#
const actions = [];
if(condtionA) {
     actions.push(<GridActionsCellItem divider={!conditionB && !conditionC} ... />);
}
if(condtionB) {
     actions.push(<GridActionsCellItem divider{!conditionC} ... />);
}
if(condtionC) {
     actions.push(<GridActionsCellItem divider ... />);
}
actions.push(<GridActionsCellItem ... />);
```

Alternatively, I would like to have the following attribute:

```C#
...
actions.push(<GridActionsCellItem dividerTop ... />);
```
or

```C#
const actions = [];
if(condtionA) {
     actions.push(<GridActionsCellItem ... />);
}
if(condtionB) {
     actions.push(<GridActionsCellItem ... />);
}
if(condtionC) {
     actions.push(<GridActionsCellItem ... />);
}
actions.push(<Divider ... />);
//or actions.push(<GridActionsCellDivider ... />);
actions.push(<GridActionsCellItem ... />);
```
Is this possible?

**Comment by cherniavskii** [comment]
@hanselsen in your case you can use `sx` prop to apply top border instead:

```tsx
<GridActionsCellItem
  sx={{
    borderTop: '1px solid #e0e0e0'
  }}
/>
```

Here's working example: https://codesandbox.io/s/columntypesgrid-material-demo-forked-g1fxwz?file=/demo.tsx

**Comment by chrisch297** [comment]
> Hey [@hanselsen](https://github.com/hanselsen) Passing `divider` prop to `GridActionsCellItem` actually works - see working demo https://codesandbox.io/s/columntypesgrid-material-demo-forked-5qsn33?file=/demo.tsx:51-70

It's working, but it gives a TS error:

```
TS2322: Type
{
    showInMenu: true;
    divider: true;
    icon: Element;
    label: string;
}
is not assignable to type
(IntrinsicAttributes & GridActionsCellItemCommonProps & { showInMenu?: false | undefined; icon: ReactElement<any, string | JSXElementConstructor<...>>; label: string; } & Omit<...> & Omit<...> & RefAttributes<...>) | (IntrinsicAttributes & ... 5 more ... & RefAttributes<...>)

Property divider does not exist on type

IntrinsicAttributes & GridActionsCellItemCommonProps & {
    showInMenu: true;
    closeMenuOnClick?: boolean | undefined;
    closeMenu?: (() => void) | undefined;
    label: ReactNode;
} & Omit<...> & { ...; } & Omit<...> & RefAttributes<...>
```

I'm on MUI material 9 and MUI x-data-grid 9.
