### ISSUE TITLE
[data-grid] Support column spanning in CSV export

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#4213]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Extracted from #4020

**Comment by flaviendelangle** [comment]
Does the CSV format support cell spanning ?

**Comment by cherniavskii** [comment]
> Does the CSV format support cell spanning ?

No, but the closest we can do is to export empty values instead of collapsed cells

**Comment by flaviendelangle** [comment]
We will have to do the same (but probably with real col span) for the Excel Export

**Comment by cherniavskii** [comment]
Created separate issue https://github.com/mui/mui-x/issues/4218

**Comment by cherniavskii** [comment]
I've checked the CSV export on available column spanning demos and it seems to work just fine.

<img width="420" alt="Screenshot 2022-04-12 at 12 47 38" src="https://user-images.githubusercontent.com/13808724/162943961-2bac0828-b2bd-4789-b97d-7fc0101dfd20.png">
<img width="170" alt="Screenshot 2022-04-12 at 12 48 30" src="https://user-images.githubusercontent.com/13808724/162943971-b25a9cff-3927-4d7d-b0e1-ec45d5f06c43.png">

<img width="818" alt="Screenshot 2022-04-12 at 12 47 45" src="https://user-images.githubusercontent.com/13808724/162943966-171a07e9-a83e-4c09-9a1d-e9fb5413a569.png">
<img width="235" alt="Screenshot 2022-04-12 at 12 48 38" src="https://user-images.githubusercontent.com/13808724/162943972-8af42f82-a9ac-4f28-a516-a429ab993ccc.png">

<img width="819" alt="Screenshot 2022-04-12 at 12 47 56" src="https://user-images.githubusercontent.com/13808724/162943968-2040d4e0-103b-462e-994f-bfa43376c0fb.png">
<img width="738" alt="Screenshot 2022-04-12 at 12 48 46" src="https://user-images.githubusercontent.com/13808724/162943974-1eedea0c-5cf6-47c0-8139-347d8b9558dc.png">
