### ISSUE TITLE
[DataGrid] getAllRows method in DataGrid's apiRef

### ISSUE THREAD

**Issue by majdajroudi** [mui/mui-x#4215]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I recently updated the MUI in my project to the latest version (version 5) in order to use new features added to the DataGrid component. 

I am using apiRef prop to manage the editable feature of the grid. It seemed to me that the ref includes many functions regarding rows but is missing  key function which is getAllRows. 

I was wondering if it would be possible to add this function to the ref. It seems like a feature that can be achieved easily and I would be more than happy to work on it.

**Comment by alexfauquette** [comment]
Hi @majdajroudi To get access to state data, we encourage the use of [selectors](https://mui.com/components/data-grid/migration-v4/#state-access)

`gridRowsStateSelector` which returns the rows. You can also get the rows ids with `gridRowIdsSelector` and `gridRowsLookupSelector` which return s an object `{[rowId]: rowModel}`

We are [documenting](https://mui.com/components/data-grid/state/#catalog-of-selectors) them, but there is still some work to do

Does that solves your problem or do you see cases where a new method is needed?

**Comment by flaviendelangle** [comment]
Related to https://github.com/mui/mui-x/issues/3717 which should clearly document how to access the various row listings.

**Comment by flaviendelangle** [comment]
Closing this one, we can continue the discussion on how to document it better in #3717
