### ISSUE TITLE
[DataGridPro] Density specific CSS class

### ISSUE THREAD

**Issue by brentertz** [mui/mui-x#4225]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like the DataGrid/DataGridPro components to include global CSS classes that represent the current density, so that I may easily adjust styles therein by simply using overrides.

e.g.
```
.MuiDataGrid-main--densityCompact
.MuiDataGrid-main--densityStandard
.MuiDataGrid-main--densityComfortable
```

https://mui.com/api/data-grid/data-grid-pro/#css

### Motivation 🔦

Our themed DataGridPro displays the TextField, including borders, etc., inside of cells, whilst editing.  The TextField height however needs adjusted depending on the density.  Below are some examples.

_Standard_
![Screen Shot 2022-03-18 at 10 27 20 AM](https://user-images.githubusercontent.com/202773/159045923-9a03c1be-2bbf-458d-879a-9fc587e223c3.png)
_Compact (broken)_
![Screen Shot 2022-03-18 at 10 27 44 AM](https://user-images.githubusercontent.com/202773/159045943-74e30dd6-408b-48f2-9630-27e4e60a8192.png)
_Compact (desired)_
![Screen Shot 2022-03-18 at 10 44 09 AM](https://user-images.githubusercontent.com/202773/159046074-9967dba6-b8f8-4c59-979f-9172db7831d5.png)

_theme_
```js
...
components: {
  MuiDataGrid: {
    editInputCell: {
      '.MuiDataGrid-main--densityCompact &': {
         height: 'auto',
      }
    }
  }
}
```

Another approach might be to use custom renderer components and read the density from the DataGrid api, but that feels much more heavy-handed, particularly as I am trying to solve this issue with a relatively light touch, for the most common scenarios, and doing so centrally - in an internal component library rather than in a product.

Thanks kindly for your consideration.

### Order ID 💳 (optional)

PO 8813010283

**Comment by flaviendelangle** [comment]
The [following example](https://codesandbox.io/s/datagridpro-v5-quick-start-forked-vrovgg?file=/src/App.tsx:691-692) should work.
It is not as straightforward as a built-in class, but still better than using custom renderer.

**Comment by brentertz** [comment]
@flaviendelangle, I do believe that this will work, though using `getRowClassName` rather than `getCellClassName` to minimize the number of calls a bit further.  Thank you.
