### ISSUE TITLE
[data grid] Change the the value of a filter operator

### ISSUE THREAD

**Issue by Utkarshk7** [mui/mui-x#4226]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently, the label and value for the filter operators are predefined based on the column type.

E.g. if i have a column of type String, i get a set of filter operators which is great. 

The issue is that the values corresponding to the operator labels are  not what my REST API expects. E.g. when i select operator (label) **equals**, i want the value to be **EQ** instead of the default value.

Can you please guide how i can change the default values of filter operators corresponding to the labels? We are fine with the labels.

A code sample will be of great help !

### Steps to reproduce 🕹

Steps:

1. Use data grid pro control
2. Click on filter for a String type column
3. Select equals. The value corresponding to the label equals should be EQ

### Context 🔦

We are unable to use our REST API.

 A code sample will be of great help !

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#39429

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
I think you should be able to just transform the model before sending it to your api endpoint.

**Comment by Utkarshk7** [comment]
Please let me know if we need further information on this issue from my side.

**Comment by flaviendelangle** [comment]
Thanks for the additional information.
I am not familiar with OData, but would you be able to pre-process the model before sending it to the API ?

Something like:

```tsx
const [filterModel, setFilterModel] = React.useState(() => getDefaultGridFilterModel())

const oDataFilterModel = React.useMemo(() => ({
  ...filterModel,
  items: filterModel.items.map(item => ({
    if (item.operatorValue === 'equals') {
      return { ...item, operatorValue: 'EQ' }
    }
    return item
  })),
  [filterModel]
)

React.useEffect(() => {
  fetchFilteredRows(filterModel);
}, [filterModel)
```

Alternatively you can customize the filter operators given to the grid [as displayed here](https://mui.com/components/data-grid/filtering/#wrap-built-in-operators) but I don't think it's the best option.

**Comment by Sathish1072** [comment]
How to change the filter operator from equals to contains when I use the header column filter, and the column type is a number.
