### ISSUE TITLE
No way to open ShowColumns after clicking HideAll Button from SHowColumn Component

### ISSUE THREAD

**Issue by naveenrj98** [mui/mui-x#4228]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

No way to open the ShowColumn Component after clicking HideAll

### Expected behavior 🤔

should have been a way to open the show column
either 
don't hide one column which has the primary key

or 

after clicking HideAll, don't make the user to close the ShowCoulmns Component

### Steps to reproduce 🕹

Steps:

1.https://codesandbox.io/s/datagrid-v5-quick-start-54iz1
2. Click on ShowColumns from anyone column
3. Click on HideAll
4. Click on outside the table
5. Now you don't see any way to open the showColumns

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
For this use case, you have the `hideable` attribute in the column definition. If `false`, clicking **Hide all** won't hide the column.

```ts
const columns: GridColDef[] = [
  { field: "id", hide: true },
  { field: "col1", headerName: "Column 1", hideable: false, width: 150 },
]
```

Does it work for you?

**Comment by KevinKoetz** [comment]
I would argue that the "Show Columns" Option Menu should be a menu on the Grid itself and not on the columns. I expect a menu opening via a column only to act on this particular column. This is not the case for the Show Columns Menu Item. 

Would it be possible to move the Show Columns menu item to the grid itself (right side part of the header, three dots just like on the columns)?

**Comment by flaviendelangle** [comment]
It is accessible in the Toolbar, see [this example](https://codesandbox.io/s/datagrid-v5-quick-start-forked-md2t0l)

**Comment by KevinKoetz** [comment]
Toolbar is good enough for me, thank you for sharing.

**Comment by Allie-Howe** [comment]
Came here to raise the same issue - in my opinion this needs another fix. The toolbar is an extra, optional component that many won't implement, so users will be faced with this bug. The Hide button in menu reacts to this correctly, by greying out if there's only one column:
![image](https://user-images.githubusercontent.com/32961755/183995685-21bb43cb-2dab-48dc-b995-f2852887631e.png)

 I feel like not hiding the first column would be a suitable solution - either that or displaying the triple dots in the top left even if there are no columns.
