### ISSUE TITLE
[DataGrid] Turn off Accessibility keyboard navigation

### ISSUE THREAD

**Issue by flowni** [mui/mui-x#4246]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I render react-bootstrap textareas (yes, shame on me) as cells in a column because I need multiple editable lines for long texts.
However, I can not use the keyboard properly in the textarea because of the accessibility feature keyboard navigation, e.g. the spacebar causes the cell to lose focus.
**Is there any way to disable the keyboard navigation?**

My column:
`{`
`      field: "edit_text",`
`      headerName: "Edit your text",`
`      flex: 1,`
`      renderCell: (params) => (`
`        <Form.Group style={{ width: "100%" }}>`
`          <Form.Control`
`            as="textarea"`
`            value={params.value}`
`            onChange={(e) => updateTextEdited(params.row, e.target.value)}`
`            style={{ resize: "none" }}`
`          />`
`        </Form.Group>`
`      ),`
`},`

It seems to be disabled if I comment the last two lines of the file "useGridKeyboardNavigation.js", but this is not feasible for my CI/CD pipeline:
`  // useGridApiEventHandler(apiRef, GridEvents.cellNavigationKeyDown, handleCellNavigationKeyDown);`
`  // useGridApiEventHandler(apiRef, GridEvents.columnHeaderKeyDown, handleColumnHeaderKeyDown);`

### Motivation 🔦

I want to edit in a multi line cell because of long texts.

**Comment by m4theushw** [comment]
> I render react-bootstrap textareas (yes, shame on me) as cells in a column because I need multiple editable lines for long texts.

Are you using cell editing? We disable keyboard navigation if a cell is in edit mode. See https://mui.com/components/data-grid/editing/

Anyway, you should be able to disable the default of the space bar key by calling `event.stopPropagation()` in the `keydown` of the textarea.

**Comment by flowni** [comment]
Thank you @m4theushw!

I do not set the cell to editable (`editable: true`) because this activates the default editing mode, which only has one editing line (or am I doing something wrong?).

With the `event.stopPropagation()` I can now finally edit the text in the textarea. However, I can't write text in the middle of the textarea as the cursor gets updated after each keystroke to the last char.
I rebuilt it in sandox, do you see anything that I am doing wrongly: [sandbox textarea editing](https://codesandbox.io/s/datagrid-v5-quick-start-forked-wuizy7?file=/src/App.tsx)

**Comment by cherniavskii** [comment]
Hey @flowni 
You should try using custom editing component, see related docs: https://mui.com/components/data-grid/editing/#custom-edit-component

**Comment by flowni** [comment]
Hey @cherniavskii, yes this helps a lot, thanks! 🚀
Together with the `event.stopPropagation()` (otherwise the Enter Key leaves the edit mode) everything seems to work now.

I try to update the sandbox in the upcoming days if anyone wants to do something similar.
