### ISSUE TITLE
[question] How to customise DataGrid Filter Panel to only show filters applied to current column

### ISSUE THREAD

**Issue by joespeargresham** [mui/mui-x#4255]
### Order ID 💳

#27566

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

When a user clicks the Filter icon on a column header, I would like to display a list of filters that are applied to that column only. Currently it shows all filters applied to the grid.

I can override the panel using the `components` prop, but please can you advise how I can determine which column they've opened it against? Can I get access to the field name somehow?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.17134
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Spartan (42.17134.2208.0)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.66
    @mui/icons-material: ^5.3.1 => 5.3.1
    @mui/lab: ^5.0.0-alpha.66 => 5.0.0-alpha.66
    @mui/material: ^5.3.1 => 5.3.1
    @mui/private-theming:  5.3.0
    @mui/styled-engine:  5.3.0
    @mui/styles: ^5.3.0 => 5.3.0
    @mui/system: ^5.2.8 => 5.3.0
    @mui/types:  7.1.0
    @mui/utils:  5.3.0
    @mui/x-data-grid-pro: ^5.5.1 => 5.5.1
    @mui/x-license-pro:  5.5.1
    @types/react: ^17.0.38 => 17.0.38
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.5 => 4.5.5
```
</details>

**Comment by m4theushw** [comment]
We don't keep track of which column caused the panel to open. But you can pass a custom filter icon and get the field clicked looking into the `data-field` attribute of the closest column header. Once you have the field save it in the state and use it in the custom panel. The slot for the icon is `components.ColumnFilteredIcon`.

<img width="500" src="https://user-images.githubusercontent.com/42154031/159600413-7e4abd24-667f-4afc-b031-498e28b44b59.png" alt="image" style="max-width: 100%;">

**Comment by joespeargresham** [comment]
Explored the `onColumnHeaderClick` callback a bit more and found that it gets triggered when clicking the Sort button, but not the Filter button. Seems an odd inconsistency since they are both in the column header. If it could trigger when the Filter button is clicked, I could store the field from that.

**Comment by m4theushw** [comment]
We can't change `onColumnHeaderClick` to be triggered when the filter icon is clicked because this would be a breaking change for other users. I opened #4276 with the purpose of adding a slot to override the entire button. Additionally, the default button now has an `onClick` prop which is called with the clicked field. Could you test in [this](https://codesandbox.io/s/basicexampledatagrid-material-demo-forked-npl7vi?file=/demo.tsx) CodeSandbox if these changes help to achieve what you want? We need to know if it's worth to push #4276 forward.

**Comment by joespeargresham** [comment]
Thanks @m4theushw - I've tested the changes in your CodeSandbox and it will allow me to achieve what I want.
