### ISSUE TITLE
[question] Common theme for multiple Project 

### ISSUE THREAD

**Issue by wahajStar** [mui/mui-x#4256]
### Order ID 💳

#32742

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello,
using createTheme I have created a theme for my project, it works fine.
My question is how can I use that particular theme for my other projects without copying it again n again.
please let me know an efficient way of using it.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Hi, this channel is exclusively for questions related to the DataGridPro. For MUI Core support you can use the StackOverflow community or open an issue in https://github.com/mui/material-ui.

Concerning your question, you can store your theme in a "shared" repository and use this repo as a dependency on all your projects. Once the theme is changed in the shared repo, all other projects would get the changes.

**Comment by wahajStar** [comment]
Thank you
