### ISSUE TITLE
[docs] Missing navigation links

### ISSUE THREAD

**Issue by siriwatknp** [mui/mui-x#4260]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

2 interfaces does not have the navigation links which cause the TOC href to contain `undefined`

- https://migration.mui.com/x/api/data-grid/grid-row-spacing-params/
- https://migration.mui.com/x/api/data-grid/grid-row-class-name-params/

<img width="1698" alt="Screen Shot 2565-03-23 at 11 57 20" src="https://user-images.githubusercontent.com/18292247/159626963-6198c562-1c53-4c42-9d19-fb35c1899fa4.png">

Result from ahrefs https://app.ahrefs.com/site-audit/3276941/8/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&filterCollapsed=true&filterId=fa1aa39a6abc3d35dd334cf84fae62e4&issueId=c64da643-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating

### Expected behavior 🤔

They should exist in the navigation

### Steps to reproduce 🕹

Steps:

1. Open these urls
  1.1. https://mui.com/x/api/data-grid/grid-row-spacing-params/
  1.2. https://mui.com/x/api/data-grid/grid-row-class-name-params/

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Has been fixed in #4164
