### ISSUE TITLE
[data grid] Update selected cells with value pasted

### ISSUE THREAD

**Issue by eebbann** [mui/mui-x#4262]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Ability to group and update : grouped cell which has the same cell details ..instead of editing it one by one .

### Motivation 🔦

was a request from my work team so decided to post here aswell

**Comment by m4theushw** [comment]
I'm not sure if I understood correctly. When you say "grouped date of birth" does it mean that you're using [row grouping](https://mui.com/components/data-grid/group-pivot/#row-grouping)?

> I do is choose multiple update to populate selected column

We don't have a way to select a column. How do you imagine that this feature will work? Could you provide examples of other libraries or tools supporting this behavior? It will be better to understand the new feature.

**Comment by eebbann** [comment]
theres a sample of this on agGrid i may not be explaining this correctly..but in a column which has details (rows ) under u can drag copy a cell under that column to populate (paste) same details..
<img width="1280" alt="Screenshot 2022-03-24 at 6 52 41 AM" src="https://user-images.githubusercontent.com/82966135/159913288-c3294665-a3e1-445b-8d74-ff2316927a0d.png">

**Comment by m4theushw** [comment]
Now I get it. We need #208 to support this use case.

**Comment by eebbann** [comment]
Dear Mui Community,

I apologize if this isn't the appropriate channel, but in desperate times, one must take desperate measures to be heard. I'm actively seeking a front-end developer role and would love to join the Mui team if there are any available positions. I'm willing to go above and beyond to ensure success and I'm open to continuous learning. However, it's often challenging to reach the right channels and make oneself heard. That's why I'm reaching out to the GitHub community for guidance or connections with the relevant individuals at Mui. Any information or suggestions would be greatly appreciated. Please feel free to contact me directly if you can assist me in any way. Thank you for your time and consideration.

Kind regards,
Eban

**Comment by cherniavskii** [comment]
Solved by [Cell selection](https://mui.com/x/react-data-grid/cell-selection/) and [Clipboard paste](https://mui.com/x/react-data-grid/clipboard/#clipboard-paste)
