### ISSUE TITLE
[data-grid] Scroll to top after page change

### ISSUE THREAD

**Issue by ypresto** [mui/mui-x#4263]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Here is 100 rows table with `pageSize={25}`, where some rows are outside of the viewport of the scroll area.
https://codesandbox.io/s/datagrid-no-scroll-to-top-lvd61t

When scrolling to the bottom to show row 25, then click a next page button, scroll position is kept bottom and row 50 (Hello50) is shown.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/400558/159705818-7fcd9acc-0d80-4729-ad93-e2af36e9eb1a.png">

### Examples 🌈

User wants to see the table from first row, which is row 26.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/400558/159706765-f64acc10-2724-4123-9b0f-95118acde8bf.png">

**Comment by m4theushw** [comment]
Interesting. Nobody complained about this so far. I think we can consider this as a "bug" since other libraries scroll to the top when changing the page.

As a workaround, you can set `scrollTop=0` after changing the page:

```ts
document.querySelector('.MuiDataGrid-virtualScroller').scrollTop = 0;
```

**Comment by flaviendelangle** [comment]
I am almost surprised that nobody raised that topic.
But I agree that we should probably scroll top when changing page.

**Comment by rwynn** [comment]
Hi @flaviendelangle thanks for taking a look at this issue.  I ran into a very similiar problem.  

I had one question about the fix for this.  From the commit it looks like this now scrolls to the top for a page change only?  I have a situation where I encounter a very similiar issue when I do the following with server side pagination:

1. Scroll to the last virtual row outside the viewport where `rows` and `rowCount` are e.g. `[...]` and `1000`.
2. Initiate a filter in the application (outside the grid) such that the `rows` and `rowCount` props change to `[]` and `0`. No results. 
3. Remove the filter such that `rows` and `rowCount` return to the values in step 1.

The issue occurs at step 3 where I need to scroll the grid up in order to actually see the rows.  My guess would be that if the grid was scrolled top at step 2 (no rows) this might not occur?

**Comment by flaviendelangle** [comment]
@DanailH I would like your opinion on this one since you worked on the infinite loader feature.

You could indeed do it yourself with the `apiRef`, we will see if it make sense to change it when `rowCount` changes :+1:

**Comment by DanailH** [comment]
Sorry for the delayed response.
In short - We might have a problem if we scroll when the `rowCount` changes as the basic implementation of the infinite loader do change the `rowCount` (user can load additional rows which in turn changes the `rowCount` value).
For the server-side infinite loading (yet to be developed) that wouldn't be a problem as the `rowCount` will be predefined and known from the beginning.

**Comment by Rohit22061999** [comment]
hey i was facing the same issue but after seaching for methods here it is the solution

``` const ref = useRef<HTMLDivElement>(null);```

```const handlePageChange = () => {
    if (ref && ref.current) ref.current.scrollIntoView();
  };
```

```    <DataGrid
      rows={rows}
      columns={columns}
      ref={ref}
      autoHeight={true}
/>
```

just made these changes to your data grid component

**Comment by michael-land** [comment]
@flaviendelangle 

How can I turn off this feature? I prefer to scroll to the top manually once the data has fully loaded, instead of doing it while the data is still being fetched.
```
  useEffect(() => {
    if (!rows.length) return;
    apiRef?.current.scrollToIndexes({ colIndex: 0, rowIndex: 0 });
  }, [rows]);

```

```
  useEffect(() => {
    const onEventChange: GridEventListener<'paginationModelChange'> = (params, event, details) => {
      event.defaultMuiPrevented = true;
    };
    return apiRef.current.subscribeEvent('paginationModelChange', onEventChange);
  }, [apiRef]);

```

**Comment by reihanehaf** [comment]
On my case ,I used server side pagination and grid was my child component which send pageChanged on his father. After each page changed render was called and grid scrolled to top.

**Comment by reihanehaf** [comment]
on my case , I set grid's height (or set grid's parent's height).
