### ISSUE TITLE
[DataGridPro] Performance Tree Data when virtualization is turn off

### ISSUE THREAD

**Issue by fourteenmeister** [mui/mui-x#4268]
Slowly expands heavily nested trees if virtualization is disabled

https://codesandbox.io/s/treedatasimple-material-demo-forked-yt1mnd?file=/demo.tsx

Can this be speeded up somehow?

**Comment by flaviendelangle** [comment]
Hi,

Is there a reasy why you disabled virtualization ?
No virtualization and 2 000 rows can't be performant. You might have ways to speed it up, but it will remain a very bad user experience.

**Comment by fourteenmeister** [comment]
> Is there a reasy why you disabled virtualization ?

I'm not saying virtualization is bad. But when there is relatively little data, I would like to be able to turn off virtualization. Besides at virtualization browser search does not work.

**Comment by flaviendelangle** [comment]
The lack of browser search with virtualization is a limitation I agree.
But with 2 000 rows, you won't have any other efficient solution than virtualization.

**Comment by m4theushw** [comment]
The slowness is not on our side. When a row is expanded, React needs to create thousands of DOM elements if virtualization is off.

![image](https://user-images.githubusercontent.com/42154031/160019173-0e557fc5-2848-4a27-a3c6-fb163245c12f.png)

To work around the browser limitation concerning search, we have a demo showing how to add a search functionality into the DataGrid: https://mui.com/components/data-grid/filtering/#quick-filter

**Comment by fourteenmeister** [comment]
> The slowness is not on our side. When a row is expanded, React needs to create thousands of DOM elements if virtualization is off.

I understand. Thanks!
