### ISSUE TITLE
[question] Support Request

### ISSUE THREAD

**Issue by iEquos** [mui/mui-x#4269]
### Order ID 💳

#37406

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Sorry this might not be the correct place to post this.

But is it possible to get an update on these two issues:
https://github.com/mui/mui-x/issues/4249#issuecomment-1074940388
https://github.com/mui/mui-x/issues/4127#issuecomment-1075351160

And to answer the comments made by us.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Done!
