### ISSUE TITLE
[data-grid] Using `GridCellRenderCell.hasFocus` alongside material UI Tooltips

### ISSUE THREAD

**Issue by VMR998** [mui/mui-x#4277]
We are using material UI's x-data-grid in a react application. Specifically it is a list of search results with icons in one of the columns, The icons are svgs that was wrapped in MUI tooltips. 

By default the tooltips show on mouseover, but we needed them to appear when the user navigated to the icons via keyboard. Our attempted solution was to force focus using the tooltip's 'open' parameter. The _GridRenderCell_ would pass it's _hasFocus_ parameter to the component with the tooltip. 

Here's a minimal example:
`
GridEnrichedColDef[] = [
  {
   ...
    renderCell: (params) => (<Component open={params.hasFocus}/>)
  },
  ...
]
`

This works for getting the tooltip to appear on keyboard navigation. However, setting the tooltip's _open_ parameter disables the default behavior. I've tried to conditionally pass the _hasFocus_ parameter or conditional set the _open_ parameter (leaving it undefined if _hasFocus_ is false), but that only resulted in it default to the tooltip's default behavior. 

I think the issue has to do with the entire column being linked. Even if I only pass the parameter for the cell that has focus, the other cells in the column (not in focus) seem to reset the rendering of the in focus cell.

**Comment by m4theushw** [comment]
This is similar to #3892

If you put focus in the svg icon when `hasFocus=true`, the tooltip will be displayed automatically. No matter if the focus came via click or keyboard. You can check https://github.com/mui/mui-x/issues/3892#issuecomment-1032832863

**Comment by VMR998** [comment]
Thanks for the response. Nesting the svg within <IconButton> seems to solve the problem. This thread can be close.
