### ISSUE TITLE
onColumnOrderChange doesn't make use of onColumnHeaderDragEnd event.

### ISSUE THREAD

**Issue by tielushko** [mui/mui-x#4278]
### Order ID 💳 (optional)

31986

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I recently came across the onColumnOrderChange prop in the DataGridPro which gets triggered on every single rotation of the column perform. I find it to be not extremely performant in regards to when the user drags the column from position 2 to position 12 for example, the event gets triggered 10 times, even though they are doing it in 1 drag interaction. 

As such, in my application that saves the preferences the user has for the order of the columns, I had to utilize the "columnHeaderDragEnd: emitted when dragging of a header cell stops." event as a part of your GridEvents in order to prevent 10 calls to update order preferences.

Would it make sense to implement the onColumnOrder api to be handled in a similar pattern? I was wondering if there was a particular reason for the current implementation when it gets emitted on every column order index change, instead of a bulk change? 

Or would it instead make sense to have an option for an additional prop that could customize the behavior to only trigger at the end of the interaction (sort of like onColumnWidthChange vs onColumnResize).

Thank you for the discussion!

### Examples 🌈

https://codesandbox.io/s/subscribetoevents-material-demo-forked-lq9n8d?file=/demo.js

### Motivation 🔦

Have a similar behavior to the onColumnWidthChange vs onColumnResize props.

**Comment by DanailH** [comment]
Hey, @tielushko thanks for raising this! 
Yes, it seems that the `onCOlumnOrderChange` can be only called when the user stops dragging a column. I'm trying to think of a case where you want to react to each column reorder. I guess it can be useful if you want to overwrite our default behavior when you reorder and then drop the column outside of the grid that it returns to its original position.
For now, as an alternative, you can use the event which you are already doing but for now, I don't think we can change that functionality as it would be a breaking change to the way the API works. We can probably do this in V6.

On another note this is a great thing to keep in mind for the row reorder feature https://github.com/mui/mui-x/pull/4034

**Comment by tielushko** [comment]
@DanailH, I meant the onColumnOrderChange gets triggered every column reorder instead of only once when user stops dragging the column. 

I was wondering if this should be the way? The default behavior in MUI Grid does this on every reorder, I had to add the custom event instead to do it when user ends interaction. 

For row reorder, that's true it would be ideal to trigger that event when user ends interaction too. Thanks for your response!

**Comment by DanailH** [comment]
This PR should fix this issue https://github.com/mui/mui-x/pull/7385.
