### ISSUE TITLE
[DataGrid] Header misalignment when using the "End" key for horizontal scroll

### ISSUE THREAD

**Issue by mbrookes** [mui/mui-x#4279]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We have come across an issue with the alignment of headers when the end key is hit when the focus is in the checkbox select all header.

Notice that the header alignments no longer align with their destination column:

![image](https://user-images.githubusercontent.com/357702/160178359-74c607a7-2df8-484c-b994-59fc66b19885.png)

If this bug has any sort of workaround in the meantime that code would be much appreciated.

### Expected behavior 🤔

Header alignment:

![image](https://user-images.githubusercontent.com/357702/160179102-63896182-c52f-42a9-b3f2-a41e1b7a733d.png)

### Steps to reproduce 🕹

Issue is reproducible in the sandbox code of the examples: https://codesandbox.io/s/pcp9f?file=/demo.js

To reproduce:

1. Shrink the grid area so there is a horizontal scrollbar on the rows.
2. Click on the select all checkbox header.
3. Hit the End keyboard key (Mac: fn right-arrow)

### Context 🔦

https://mui.zendesk.com/agent/tickets/2789

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

34721

**Comment by m4theushw** [comment]
Same bug from #4275

I already have a PR fixing this on the way.

> If this bug has any sort of workaround in the meantime that code would be much appreciated.

Yes, [disable](https://mui.com/components/data-grid/virtualization/#disable-virtualization) virtualization with:

```tsx
<DataGridPro disableVirtualization />
```

Or, if above is not possible, run the code below whenever a key is pressed:

```ts
document.querySelector('.MuiDataGrid-columnHeaders').scrollLeft = 0
```

**Comment by mbrookes** [comment]
Thanks @m4theushw. I did search but missed it, as it doesn't mention keyboard.
