### ISSUE TITLE
[data grid] Reset the state

### ISSUE THREAD

**Issue by ortin779** [mui/mui-x#4301]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am storing the gird PinnedColumns, sort model, visibility model in local storage to persist them between page refreshes. And when the user wants reset all his changes i am providing an option to reset the pinnedColumns, sortModel and visibility to default. When i try to updated the state of the grid, Using apiRef it is not allowing me to update multiple things in one transaction.

<img width="1364" alt="Screenshot 2022-03-29 at 10 43 54 AM" src="https://user-images.githubusercontent.com/58628794/160538110-9ee70474-789b-48f2-ae4b-c330af2d53fb.png">

### Expected behavior 🤔

Expected behaviour is to reset all the customisation (PinnedColumns, SortModel and Visibility Model) to default values.

### Steps to reproduce 🕹

Steps:
[Code Sand Box](https://codesandbox.io/s/datagridpro-v5-quick-start-forked-rk486p?file=/src/App.tsx)
1. Pin column to left / right
2. add sorting option on any column
3. click on the Reset button above the Grid

### Context 🔦

Persisting the state between refreshes and reseting it to default state

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
We strongly advise you against using `apiRef.current.setState`, you will often miss part of the updates (for instance updating the `sortModel` but not updating the row that matches this model).
Instead, you have standalone methods `apiRef.current.setSortModel` / `apiRef.current.setPinnedColumns` / ...

And in the next version, we will open the documentation for two new methods `apiRef.current.exportState` and `apiRef.current.restoreState` that seems to do exactly what you want.

**Comment by jdrucey** [comment]
It would be great to be able to reset a DataGrid instance back to its initial state, clearing user filters, column widths etc. Unless I'm missing something, `apiRef.current.exportState` and `apiRef.current.restoreState` is not enough to achieve this. 

My first thought was to pass `props.initialState` to `apiRef.current.restoreState`, but the state just gets merged into the current state, meaning anything missing from `inititalState` remains in place. Even exporting the state on first render and using that instead of `initialState` has the same problem.

My workaround would be to build the full `GridInitialState` object piece by piece, but this seems very brittle in regards to future updates.

Could we have a second parameter on `apiRef.current.restoreState` to change the behaviour from a "merge" to a "replace"?

**Comment by flaviendelangle** [comment]
If we add an `apiRef.current.resetState` what would be the behavior ?
Would be apply the default value of the grid or the value provided on mount (through the initial state and the controlled states) ?

**Comment by jdrucey** [comment]
Personally, i'd opt for the state provided to `initialState`, or Grid defaults if missing. 

The goal is to get it back to the state it first appeared in on page load, before the user touched anything.

**Comment by flaviendelangle** [comment]
I agree
And I think the use case is common enough for a 1st party integration with a new `apiRef.current.resetState` method.

**Comment by jamesjsewell** [comment]
any updates on this? im trying to reset the state as described above (  export state, then restore it ) the restore method doesn't seem to be affecting the grid at all. "Could we have a second parameter on apiRef.current.restoreState to change the behaviour from a "merge" to a "replace"?" asked by @jdrucey  is there any way to achieve something like this currently?

**Comment by jamesjsewell** [comment]
i must have been doing something wrong with functional component state, the restoreState method works as expected atleast in my case where im passing the entire state object from exportState

**Comment by scordero414** [comment]
> I agree
> 
> We should probably do it, the use case is common enough for a 1st party integration with a new `apiRef.current.resetState` method.

It stills in development?, or we could have some updates to this? Thanks!

**Comment by cherniavskii** [comment]
I stumbled across this issue and I wonder if anyone tried using `initialState` and [changing the `key` prop](https://react.dev/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key) to reset the grid state?
