### ISSUE TITLE
[data grid] `DataGrid` briefly flashes "No rows" after loading

### ISSUE THREAD

**Issue by IgnacioFDM** [mui/mui-x#4309]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Datagrid briefly flashes the "No Rows" overlay when you transition from `loading=true rows=[]` to `loading=false rows=[loaded rows]`

Depending on the code and other things, if multiple (unnecessary) rerenders happen this flash may not be visible.

### Expected behavior 🤔

It should not flash "No rows"

### Steps to reproduce 🕹

Codesandbox: https://codesandbox.io/s/datagriddemo-material-demo-forked-dmwwi3?file=/demo.tsx

Code (mirrored)
```
import * as React from 'react';
import { DataGrid, GridColDef, GridValueGetterParams } from '@mui/x-data-grid';
import { useEffect, useState } from 'react';

const columns: GridColDef[] = [
  { field: 'id', headerName: 'ID', width: 90 },
  {
    field: 'firstName',
    headerName: 'First name',
    width: 150,
    editable: true,
  },
  {
    field: 'lastName',
    headerName: 'Last name',
    width: 150,
    editable: true,
  },
  {
    field: 'age',
    headerName: 'Age',
    type: 'number',
    width: 110,
    editable: true,
  },
  {
    field: 'fullName',
    headerName: 'Full name',
    description: 'This column has a value getter and is not sortable.',
    sortable: false,
    width: 160,
    valueGetter: (params: GridValueGetterParams) =>
      `${params.row.firstName || ''} ${params.row.lastName || ''}`,
  },
];

const baseRows = [
  { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
  { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
  { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
  { id: 4, lastName: 'Stark', firstName: 'Arya', age: 16 },
  { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
  { id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
  { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
  { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
  { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 },
];

export default function DataGridDemo() {
  const [data, setData] = useState({
    loading: true,
    rows: []
  })

  useEffect(() => {
    setTimeout(() => {
      setData({
        loading: false,
        rows: baseRows,
      })
    }, 1000)
  }, []);

  return (
    <div style={{ height: 400, width: '100%' }}>
      <DataGrid
        rows={data.rows}
        columns={columns}
        loading={data.loading}
        pageSize={5}
        rowsPerPageOptions={[5]}
        checkboxSelection
        disableSelectionOnClick
      />
    </div>
  );
}
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
See codesandbox
</details>

**Comment by DanailH** [comment]
Hey, @IgnacioFDM thanks for raising this!
Yes, it is a bit hard to catch but if you do multiple refreshes eventually it will be visible. I think this PR https://github.com/mui/mui-x/pull/4281 fixes this issue as a byproduct but just to be sure I'm tagging @m4theushw to be aware of it.

**Comment by IgnacioFDM** [comment]
By the way the same happens with the "No Results" when switching pages

**Comment by yanfaingoldCell** [comment]
#4334 didn't solve this issue, still blinking data/no data before new data, is there any suggestion for a solution?

**Comment by cherniavskii** [comment]
@yanfaingoldCell 
Cannot reproduce the issue using 5.9.0: https://codesandbox.io/s/datagriddemo-material-demo-forked-x77964?file=/package.json
Can you provide an example?

**Comment by yanfaingoldCell** [comment]
try using NoRowsOverlay with backend pagination because thats what i used

**Comment by lucas-santosP** [comment]
That still happens to me.

As a workaround, I added a delay in the rendering of the `NoRowOverlay` component, so it will have enough time for the rows to be set when the loading becomes false. With 300ms delay worked fine for me.

Would be possible to add this delay in the transitioning state of the loading instead, it may be a good solution to do internally in the lib.

```ts
const CustomDataGridNoRowOverlay: React.FC = () => {
  const [show, setShow] = React.useState(false);

  React.useEffect(() => {
    const timeout = setTimeout(() => setShow(true), 300);
    return () => clearTimeout(timeout);
  }, []);

  if (!show) return null;
  return <p>My custom no row overlay</p>;
};
```

**Comment by lucas-santosP** [comment]
Hi, @cherniavskii I tried to reproduce with a minimal setup however it seems fine there.

On a bigger project that I'm working on still happening but it must be related to something else rather than the `DataGrid` component (probably the sorting and filtering that runs after the loading ends)... but anyway, the delay workaround is fine for me now. 

Thanks for your attention!

**Comment by nhayfield** [comment]
This is happening for me. It only happens when the datagrid is embedded in Mui Tabs and you switch tabs though.
