### ISSUE TITLE
[data grid] Saving and retrieving state does not work with fluid resizable columns

### ISSUE THREAD

**Issue by mtshv** [mui/mui-x#4310]
### Order ID 💳

36792

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi! Here is a summary:
- I have a fluid width DataGrid, where almost all columns have flex property in order to fill the full width of the parent.
- I'd like to use `apiRef.current.exportState()` to save the user's layout changes into storage. This includes: changing column width, reordering columns, and hiding columns.
- I'd like to use the `initialState` prop to restore the previously saved state on a component mount. The idea is to render DataGrid that remembers your customizations since the last time.
----
For some reason, it does not work as expected with my setup:
 1.  Hidden columns are not respected when restoring the state. 
![hide](https://user-images.githubusercontent.com/11422166/160703805-66499292-dc4e-47e4-ac0d-2fa30aa4c44a.gif)

 2. Resized columns width appears broken after state restoration.
![resize](https://user-images.githubusercontent.com/11422166/160702963-02894d49-583e-442b-b487-d4ac8e65566e.gif)

The order of the columns is respected though.

Please help me determine am I hitting limitations of the `apiRef.current.exportState()`/`initialState` in this case, or it is something else.

Here is a demo sandbox: https://codesandbox.io/s/mui-datagrid-retrieve-state-issue-z6sokq?file=/demo.js

**Comment by flaviendelangle** [comment]
Hi,

Thanks for your detailed reproduction case
I see two issues here:

- When a user resizes a column, we set `flex: undefined` on this column. This is to make sure that the column is not automatically resized when we re-run the sizing process of all columns (when a new column is created for instance). But when saving the state, this `flex: undefined` is not stored in the JSON, so when restoring, the columns has flex again.

Solution: Set `flex: 0` instead of `flex: undefined`

- The default `maxWidth` property equals `Infinity`. But `JSON.stringify(Infinity) === 'null'`. So when restoring it, we have `maxWidth: null`, which is handled like `maxWidth: 0`.

Solution: Set `maxWidth: 'Infinity'` in the export and parse in correctly on restore.

**Comment by mtshv** [comment]
@flaviendelangle thanks for the fast response. Looking forward to using the new export/restore state feature.

Can you please also comment on the column's visibility issue when I am saving/restoring the state?
In my repro example columns visibility seems to be ignored. At the same time in this example https://deploy-preview-4028--material-ui-x.netlify.app/components/data-grid/state/#restore-the-state-with-initialstate it seems to be respected. 
So I am confused a bit about the differece.

**Comment by flaviendelangle** [comment]
The new `columnVisibilityModel` is only enabled when the `props.columnVisibilityModel` or `props.initialState.columns.columnVisibilityModel` is enabled.

This is necessary to avoid breaking changes with the legacy api (`GridColDef['hide']`)

To use it in import / export, you can make sure that your `props.initialState` always have this model defined, even if empty.
See [this variation of your example](https://codesandbox.io/s/datagrid-v5-quick-start-forked-5qp36g?file=/src/App.tsx)

**Comment by stamahto** [comment]
@mtshv thanks for opening this issue, I have the same problem with columns width on stringify/parse state.
Can you please share code snippet how you parse the state correctly?

**Comment by mtshv** [comment]
hey @stamahto. You can see this code in the `utils.js` in a codesandbox link that I shared.

```
export const saveTableState = (state) => {
  sessionStorage.setItem("demo", JSON.stringify(state));
};

export const getTableState = () => {
  const stringifiedState = sessionStorage.getItem("demo");
  if (!!stringifiedState) {
    return JSON.parse(stringifiedState);
  }
};

export const resetTableState = () => sessionStorage.removeItem("demo");
```

**Comment by misantronic** [comment]
> Hi,
> 
> Thanks for your detailed reproduction case I see two issues here:
> 
> * When a user resizes a column, we set `flex: undefined` on this column. This is to make sure that the column is not automatically resized when we re-run the sizing process of all columns (when a new column is created for instance). But when saving the state, this `flex: undefined` is not stored in the JSON, so when restoring, the column has flex again.
> 
> Solution: Set `flex: 0` instead of `flex: undefined`
> 
> * The default `maxWidth` property equals `Infinity`. But `JSON.stringify(Infinity) === 'null'`. So when restoring it, we have `maxWidth: null`, which is handled like `maxWidth: 0`.
> 
> Solution: Set `maxWidth: 'Infinity'` in the export and parse in correctly on restore.

I think the `flex: 0` part should be documented in the docs under the fluid-width section. It took me a long time to figure out that flex: undefined wont do anything 😅
