### ISSUE TITLE
Could not find a declaration file for module '@mui/x-data-grid' Could not find declaration file...'

### ISSUE THREAD

**Issue by kodeschooler** [mui/mui-x#4318]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

A co-worker upgraded mui data grid version 5.7.0. Now I'm getting the following red message for any component that uses the datagrid and its types. eg: 

`import {GridColumns, GridValueGetterParams} from "@mui/x-data-grid";`

error is: `Could not find a declaration file for module '@mui/x-data-grid'. C://repos/myapp/node_modules/@mui/x-data-grid/index.js' implicitly has an 'any' type.`

### Expected behavior 🤔

To not suddenly get this error in my IDE. 

### Steps to reproduce 🕹

Steps:

1. Install mui data grid version 5.6.1
2. Import the GridColumns and other types in a component and use them.
3. Have someone upgrade to latest version of mui data-grid
4. pull from remote and see errors in project

### Context 🔦

My app isn't failing, but the error is being highlighted in red in every page that has the data grid. What would cause this to suddenly happen after package upgrades? NPM page says it has TS but it tells you to do npm install @mui/x-data-grid. Are the type definitions supposed to come with it? We didn't have these errors prior to several package upgrades (including data-grid and mui).  Thank you very much

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)
  npmPackages:
    @emotion/react: ^11.6.0 => 11.6.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.73
    @mui/icons-material: ^5.2.4 => 5.2.4
    @mui/lab: ^5.0.0-alpha.60 => 5.0.0-alpha.60
    @mui/material: ^5.5.2 => 5.5.2
    @mui/private-theming:  5.4.4
    @mui/styled-engine:  5.5.2
    @mui/styled-engine-sc: ^5.5.2 => 5.5.2
    @mui/styles: ^5.5.1 => 5.5.1
    @mui/system:  5.5.2
    @mui/types: ^7.1.0 => 7.1.0
    @mui/utils:  5.4.4
    @mui/x-data-grid: ^5.7.0 => 5.7.0
    @types/react: ^17.0.20 => 17.0.20
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.5 => 5.3.5
    typescript: ^4.4.3 => 4.4.3
`
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

**Comment by kodeschooler** [comment]
It was something in our proj env, it's fine now and I could not  reproduce. Thanks

**Comment by flaviendelangle** [comment]
If it is something that could occur in other peoples project, could you please share some details ?

**Comment by cjconaty5** [comment]
> 

I had the same error message show up, but don't think it can be replicated in codesandbox.  It seems to be similar to OP, as in the Version upgrade caused the issue, but I didn't need to change any code for a fix. 


After upgrading the data-grid-x version directly in VSCode Terminal from 5.17.24 to v6_beta `npm install @mui/x-data-grid@next`, the file with the code below in it had the error pop up for the import statement.    

```import type {} from '@mui/x-data-grid/themeAugmentation';```
 
```
const main_theme_extended = extendTheme({
  ...
,
    components: {
      MuiDataGrid: {
        styleOverrides: {
          root: {
            backgroundColor: '#EBEEF1',
          },
        },
      },
    },
  ...
  });
  ```

 Restarted VSCode and once the Project Folder loaded back up the error went away with no other modifications.
