### ISSUE TITLE
[question] MUI X Pro plan features and usage

### ISSUE THREAD

**Issue by sasikaadesh** [mui/mui-x#4321]
I have few questions regarding MUI X Pro license. Please advise at the earliest. Thanks.
- If i get install one developer license on a one developers machine, can another 1-2 QA testers preview those Data Grids & Date range picker on their machines? Which the application code is managed by GIT.
- Is MUI X Pro Data grid and Date range picker compatible with Material UI v4 applications? How do we install the MUI X Pro in a Material UI v4 application? Is it by using the "npm xxx --force" command?
- Does MUI X Pro Data grid has export to CSV and Excel both? Or only to CSV now? Or when can we see the Excel export?

**Comment by DanailH** [comment]
Hi, @sasikaadesh thank you for your questions.
I can answer the last 2 but for the first one I would need help from either @oliviertassinari or @mbrookes 

> Is MUI X Pro Data grid and Date range picker compatible with Material UI v4 applications? How do we install the MUI X Pro in a Material UI v4 application? Is it by using the "npm xxx --force" command?

There is a way to mix and match MUI Core v4 with MUI X v5. There is a guide we have created that explains how this can be done. You can check it here -> https://mui.com/components/data-grid/migration-v4/#using-mui-core-v4-with-v5
However, we strongly recommend you migrate MUI Core to v5 when using MUI X v5.

> Does MUI X Pro Data grid has export to CSV and Excel both? Or only to CSV now? Or when can we see the Excel export?

Both the community and Pro packages of the Data Grid CSV export but only the Premium package will have Excel export. The feature is ready to be released but we are waiting for the Premium package to be done first. You can check which package has which features on the pricing page -> https://mui.com/pricing/

**Comment by flaviendelangle** [comment]
For the DateRange picker, you can use the one from the last v4 release of `@mui/lab`
Migrating to the one in `@mui/x-date-pickers-pro` (released next week) would not be a good idea :+1:

**Comment by mbrookes** [comment]
Hi, for the first question, only developers editing code need to be licensed, so not your QA testers.

**Comment by sasikaadesh** [comment]
> Hi, for the first question, only developers editing code need to be licensed, so not your QA testers.

**Comment by sasikaadesh** [comment]
> Hi, @sasikaadesh thank you for your questions. I can answer the last 2 but for the first one I would need help from either @oliviertassinari or @mbrookes
> 
> > Is MUI X Pro Data grid and Date range picker compatible with Material UI v4 applications? How do we install the MUI X Pro in a Material UI v4 application? Is it by using the "npm xxx --force" command?
> 
> There is a way to mix and match MUI Core v4 with MUI X v5. There is a guide we have created that explains how this can be done. You can check it here -> https://mui.com/components/data-grid/migration-v4/#using-mui-core-v4-with-v5 However, we strongly recommend you migrate MUI Core to v5 when using MUI X v5.
> 
> > Does MUI X Pro Data grid has export to CSV and Excel both? Or only to CSV now? Or when can we see the Excel export?
> 
> Both the community and Pro packages of the Data Grid CSV export but only the Premium package will have Excel export. The feature is ready to be released but we are waiting for the Premium package to be done first. You can check which package has which features on the pricing page -> https://mui.com/pricing/

============================================================

Hi @DanailH 

Thankyou for the quick reply. I have developed the application last year using Material UI v4. It's a quite a large application for a new React developer like my self. So it will be practically difficult to convert the whole application into MUI core v5 now. However I just want to use "@mui/x-data-grid-pro" & "Date range picker". So if i buy the MUI X Pro license and install using "npm i @mui/x-data-grid-pro" without installing MUI core v5, can i use only the x-grid-pro? Please advise.

Thanks and Regards,
Sasika

**Comment by sasikaadesh** [comment]
> Hi, for the first question, only developers editing code need to be licensed, so not your QA testers.

Noted and Thanks @mbrookes  for the quick reply.

Best Regards,
Sasika

**Comment by flaviendelangle** [comment]
You can find the whole documentation of v4 [here](https://v4.mui.com/)
There was no `DateRangePicker` at that point in the MUI packages.

**Comment by sasikaadesh** [comment]
> You can find the whole documentation of v4 [here](https://v4.mui.com/) There was no `DateRangePicker` at that point in the MUI packages.

Hi @flaviendelangle ,

Yes, so does this means if i want to use "date range picker" in my Material UI v4 application i need to buy the "MUI X Pro" extension developer license? Also is it a must to install MUI Core v5 with v4 to use the date range picker in MUI X Pro? Kindly advise both questions. Thanks.

Best Regards,
Sasika

**Comment by flaviendelangle** [comment]
The date range picker in `@mui/x-date-pickers-pro` will not be compatible with MUI v4 out of the box.
If there is enough traction, we could have a look to make a guide like we did for the `DataGrid` but I have  honestly no idea if it will even be doable in the 1st place.

@michaldudak maybe you will have more insight.

**Comment by sasikaadesh** [comment]
> The date range picker in `@mui/x-date-pickers-pro` will not be compatible with MUI v4 out of the box. If there is enough traction, we could have a look to make a guide like we did for the `DataGrid` but I have honestly no idea if it will even be doable in the 1st place.
> 
> @michaldudak maybe you will have more insight.

Noted and thanks @flaviendelangle . Please let me know if any guidance you found for this. Thanks alot.

Dear @michaldudak ,
Please let me know if i want to use a "date range picker" in my Material UI v4 application do i need to buy the "MUI X Pro" extension developer license? If so is it a must to install MUI Core v5 with v4 to use the date range picker in MUI X Pro? Or is there any way I can simply install the MUI X Pro "date range picker" only in my Material UI v4 application? Kindly advise both questions. Thanks alot!

Best Regards,
Sasika

**Comment by sasikaadesh** [comment]
Hi @DanailH

Thankyou for the quick reply. I have developed the application last year using Material UI v4. It's a quite a large application for a new React developer like my self. So it will be practically difficult to convert the whole application into MUI core v5 now. 

However I just want to use "@mui/x-data-grid-pro" & "Date range picker". So if i buy the MUI X Pro license and install using "npm i @mui/x-data-grid-pro" without installing MUI core v5 with v4, can i use only the x-grid-pro? Please advise.

Thanks and Regards,
Sasika

**Comment by DanailH** [comment]
Hey, @sasikaadesh If you are only looking to use the `x-grid-pro` with Material UI v4 then it will be possible but you would need to follow the guide I linked in my previous comment to make it work.
Regarding the Date range picker - as Flavien mentioned it won't be compatible with v4 out of the box.

**Comment by sasikaadesh** [comment]
Noted and Thanks a lot @DanailH . Really appreciate you and your teams quick support. 

Best Regards,
Sasika
