### ISSUE TITLE
[question] Are there plans to implement a DataGridPro footer that doesn't require a finite rowCount

### ISSUE THREAD

**Issue by jorjen** [mui/mui-x#4323]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Say I have no way of knowing the total row count that the server has, thus not being able to provide a definite rowCount, is there a way to display the total rows differently? Similar to a "see more" or have the ">" button clickable until no records can be fetched from the server?

### Examples 🌈

![image](https://user-images.githubusercontent.com/10131508/161109969-3eac8526-ef17-4070-afd2-6b6251f189b0.png)

### Motivation 🔦

I have a use case where the exact total count of data/rows is not known--i.e., DynamoDB table without scanning the whole table.

**Comment by DanailH** [comment]
Hey, @jorjen thanks for raising this!
Yes, there is a way to overwrite the default behavior. You can provide your own translation of the `footerTotalVisibleRows` in the `localeText` prop. It accepts a callback and returns a string. You can check its signature here -> https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/constants/localeTextConstants.ts#L97
You can find more about it here -> https://mui.com/components/data-grid/localization/

Hope that answers your question.

**Comment by jorjen** [comment]
Hi @DanailH,

Thank you for the response. I tried providing a translation for `footerTotalVisibleRows` but for some reason it is not being reflected (_not being overwritten?_). Am I missing something?

Below is when I tried overwriting `footerRowSelected` and `footerTotalVisibleRows` by concatenating `+added text+` to both. `footerRowSelected` seems to reflect the change, but `footerTotalVisibleRows` seems not to.

**CodeSandbox** of [Data Grid - Localization](https://mui.com/components/data-grid/localization/) example...
![image](https://user-images.githubusercontent.com/10131508/161312809-966e2c8b-cc6a-4f02-a9db-0748f3565c9c.png)

**Comment by jorjen** [comment]
Hi @DanailH,

Hoping to get your feedback on above. Thanks.

**Comment by StephenStrickland** [comment]
@jorjen I was running into a similar issue. Seems like the style of paging that we're wanting is currently a low priority item, see [#409](https://github.com/mui/mui-x/issues/409)

I was able to get close to what I need with this example: https://stackblitz.com/edit/react-ujnaza?file=demo.tsx

It looks like `localText.footerTotalVisibleRows` is the wrong approach and you have to override `localText.MuiTablePagination.labelDisplayedRows(from, to, count)`

**Comment by DanailH** [comment]
@jorjen I apologize for misleading you.  @StephenStrickland is correct, that's the way to go if you want to overite that text. I overlooked that you wanted to overwrite the text in the pagination component itself. Because the pagination we use is the core component `TablePagination` you would need to overwrite it using `localText.MuiTablePagination.labelDisplayedRows(from, to, count)`

To prevent this to happen again I will update the docs localization page with this example.

**Comment by msassa** [comment]
I think it's already fixed, but I managed to do it using this code in the localeText

```
    MuiTablePagination: {
        labelDisplayedRows: ({ from, to, count, page }) => {
            return `${from}-${to} de ${count}`;
        },
    },
```

Thanks

**Comment by JoshK2** [comment]
> @jorjen I was running into a similar issue. Seems like the style of paging that we're wanting is currently a low priority item, see [#409](https://github.com/mui/mui-x/issues/409)
> 
> I was able to get close to what I need with this example: https://stackblitz.com/edit/react-ujnaza?file=demo.tsx
> 
> It looks like `localText.footerTotalVisibleRows` is the wrong approach and you have to override `localText.MuiTablePagination.labelDisplayedRows(from, to, count)`

Thank you!
