### ISSUE TITLE
[DateRangePicker] Support month and year edition on the range pickers

### ISSUE THREAD

**Issue by k525710056** [mui/mui-x#4331]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In the regular date picker, users can quickly change the year. Can we also include that feature for the date range picker?

### Examples 🌈

<img width="840" alt="Screen Shot 2022-04-01 at 10 38 15 AM" src="https://user-images.githubusercontent.com/13372519/161314294-b9f5f12c-77c3-4bd7-8cf9-a8e444506846.png">
Our design team did this mock combined date range picker and date picker to allow users easier to change year.

### Motivation 🔦

A good example is that we use this component for users to pull yearly reports as a date filter. It's a common use case for users to change the year they want to generate.

**Comment by m4theushw** [comment]
Looking at the mockup do you want to change the year of each calendar independently? If yes, then it will require deeper changes in the internal logic. I wonder if creating two simple date pickers and display them inside a dialog may not be easier than to use the date range. To better explain why this is complex, internally we only keep track of the current month displayed in the left-most calendar. All other calendars display an increment of this month. We don't have support yet to keep track of two or more current months.

**Comment by k525710056** [comment]
I don’t need those to change independently. If user change the left
calendar and the other one change for users, that works for us as well. Is
there a way to do it?

**Comment by flaviendelangle** [comment]
Duplicates #4546
