### ISSUE TITLE
[data-grid] Edit cell stop when mouse-up event is triggered outside of the cell

### ISSUE THREAD

**Issue by FairyWorld** [mui/mui-x#4333]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

in DataGridPro component, When I want to copy the text in the cell editing, press the left mouse button, move the mouse, select the text, then move the mouse out of the input box or release the left mouse button after the cell, and the cell will be closed automatically, so that copying and copying cannot be carried out

I found that it is caused by the following code. The event is bound in the "rootElementRef", and the click event cannot distinguish between quick click or click and drag to select the text, and then release it. It is recommended to use MouseDown and mouseup events to distinguish according to the position of the mouse and the length of click time
![image](https://user-images.githubusercontent.com/32956212/161369702-5a282cb4-47a6-4aac-8c3f-ce8dd19e4488.png)

### Expected behavior 🤔

In editing mode, clicking the input box and sliding the mouse away from the cell will not automatically close the editing mode

### Steps to reproduce 🕹

Steps:

1. in DataGridPro component,
2. in the cell editing
3. focus cell input
4. press the left mouse button
5. move the mouse, select the text
6. move the mouse out of the input box or release the left mouse button after the cell
7. the cell will be closed

### Context 🔦

Copy text with mouse

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Is that the problem you encounter?
![textselection](https://user-images.githubusercontent.com/45398769/161516606-d1eae8a3-df6b-48e5-a208-c9fe3e5b0cb5.gif)


@m4theushw what about replacing the `cellMouseUp` event used to move the focus by a `cellMouseDown` such as we move the focus only when the click starts and ends in the same cell?

**Comment by m4theushw** [comment]
We can change the focus logic to use `mousedown`. The idea to use `mouseup` came from https://github.com/mui/material-ui/issues/25578 

Using `mousedown` has some implications we need to be aware of. In https://github.com/mui/mui-x/issues/4333#issuecomment-1087333708 the cell leaves the edit mode when the mouse is released outside the cell. With `mousedown` the inverse will occur. If cell A is on edit mode and I select something from another cell B in a way where the mouse is released inside A, the cell A leaves the edit mode.

<img width="500" src="https://user-images.githubusercontent.com/42154031/161573786-351e99e8-971d-47e0-9879-237f0c3755ec.gif" alt="msedge_WdzHklJOpk" style="max-width: 100%;">

**Comment by shelimov** [comment]
Is there any updates regarding this issue?

**Comment by olivierkastel** [comment]
Any news on this one? Lots of my app users are complaining about this.
They are used to Google Sheet where it is working as expected:

https://user-images.githubusercontent.com/13841209/181601792-570ba1dc-5208-4d99-a5b1-1a13d44dcc5f.mov

**Comment by cherniavskii** [comment]
> We can change the focus logic to use `mousedown`. The idea to use `mouseup` came from [mui/material-ui#25578](https://github.com/mui/material-ui/issues/25578) Since the targets between `mousedown` and `mouseup` may differ we use the last because it has the same target as the `click` event.
> 
> Using `mousedown` has some implications we need to be aware of. In [#4333 (comment)](https://github.com/mui/mui-x/issues/4333#issuecomment-1087333708) the cell leaves the edit mode when the mouse is released outside the cell. With `mousedown` the inverse will occur. If cell A is on edit mode and I select something from another cell B in a way where the mouse is released inside A, the cell A leaves the edit mode.
> 
> ![msedge_WdzHklJOpk](https://user-images.githubusercontent.com/42154031/161573786-351e99e8-971d-47e0-9879-237f0c3755ec.gif) 

@m4theushw 
This inverse issue you mentioned seems pretty insignificant to me. Is there a use case where it can be annoying?

**Comment by m4theushw** [comment]
@cherniavskii I don't see any use case but I wanted to show that there's a side effect.
