### ISSUE TITLE
onCellEditCommit event is not fired when newEditingApi is set to true

### ISSUE THREAD

**Issue by July-** [mui/mui-x#4369]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I add "experimentalFeatures={{ newEditingApi: true }}" to DataGrid as suggested in documentation, onCellEditCommit event doesn't run if edit an editable field and press enter:
https://codesandbox.io/s/amazing-hill-7sfk60?file=/src/grid.js

It works when I remove "experimentalFeatures={{ newEditingApi: true }}":

https://codesandbox.io/s/condescending-pare-cgpjvg?file=/src/grid.js

### Expected behavior 🤔

I expect onCellEditCommit to be fired after editing a field when newEditingApi is set to true

### Steps to reproduce 🕹

Steps:

1. Open codesandbox: https://codesandbox.io/s/amazing-hill-7sfk60?file=/src/grid.js
2. Edit any editable field by double-clicking, modifying text and pressing Enter
3. Check console to see there is no logs

```
import * as React from "react";
import { DataGrid } from "@mui/x-data-grid";

const columns = [
  { field: "id", headerName: "ID", width: 90 },
  {
    field: "firstName",
    headerName: "First name",
    width: 150,
    editable: true
  },
  {
    field: "lastName",
    headerName: "Last name",
    width: 150,
    editable: true
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    width: 110,
    editable: true
  }
];

const rows = [
  { id: 1, lastName: "Snow", firstName: "Jon", age: 35 },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  { id: 8, lastName: "Frances", firstName: "Rossini", age: 36 },
  { id: 9, lastName: "Roxie", firstName: "Harvey", age: 65 }
];

export default function DataGridDemo() {
  const handleEdit = (params, event, details) => {
    console.log(params, event, details);
  };

  return (
    <div>
      <div style={{ height: 400, width: "100%" }}>
        <DataGrid
          rows={rows}
          columns={columns}
          pageSize={5}
          rowsPerPageOptions={[5]}
          onCellEditCommit={handleEdit}
          experimentalFeatures={{ newEditingApi: true }}
        />
      </div>
    </div>
  );
}
```

### Context 🔦

I need to save changes to database and I'm trying to use onCellEditCommit event to get and save new values

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.84
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.29)
  npmPackages:
    @emotion/react: ^11.8.2 => 11.8.2
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.74
    @mui/icons-material: ^5.5.1 => 5.5.1
    @mui/material: ^5.5.3 => 5.5.3
    @mui/private-theming:  5.5.3
    @mui/styled-engine:  5.5.2
    @mui/system:  5.5.3
    @mui/types:  7.1.3
    @mui/utils:  5.5.3
    @mui/x-data-grid: ^5.8.0 => 5.8.0
    @types/react:  17.0.43
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
```
</details>

**Comment by m4theushw** [comment]
With the new API, there's a new prop to use to save the row in the database: `processRowUpdate`. See https://mui.com/components/data-grid/editing/#persistence

`onCellEditCommit` will be removed in v6.

**Comment by July-** [comment]
@m4theushw Thank you for the answer, now it's clear for me
