### ISSUE TITLE
[data grid] Disabling virtualization for DataGrid only in tests

### ISSUE THREAD

**Issue by DenisaHalmaghi** [mui/mui-x#4370]
Hello 👋 ,

Thank you for all the work and the amazing components you build! 🎊 

When using jsdom to test my components, not all datagrid columns are rendered. Disabling virtualization seems to solve the issue, but I wonder if there's a way to do it **_only_** in tests such as replacing the component with one with preset props

I tried something like this, but it doesn't seem to render the grid:
```ts
const mockDataGrid = (props: any) => (<DataGrid {...props} disableVirtualization />);

jest.mock('@mui/x-data-grid', () => ({
  DataGrid: () => mockDataGrid,
}));
```

Thanks!

**Comment by m4theushw** [comment]
Trying to mock the `@mui/x-data-grid` module will be tricky since the other exports shouldn't be mocked. I would suggest to create a file re-exporting everything from `@mui/x-data-grid`. In this same file you export your own DataGrid component based on the MUI's DataGrid. In this new component, you set `disableVirtualization` depending on the environment. It would work as follow:

```tsx
// src/DataGrid.tsx
import { DataGrid as MUIDataGrid, DataGridProps } from '@mui/x-data-grid';

export * from '@mui/x-data-grid';

export function DataGrid(props: DataGridProps) {
  return <MUIDataGrid disableVirtualization={process.env.NODE_ENV === 'test'} {...props} />
}
```

```diff
// src/App.tsx
-import { DataGrid } from '@mui/x-data-grid';
+import { DataGrid } from './DataGrid';

function App() {
  return <DataGrid />;
}
```

```diff
// src/App.test.tsx
-import { DataGrid } from '@mui/x-data-grid';
+import { DataGrid } from './DataGrid';

describe('App', () => {
  it('works', () => {
    render(<DataGrid />);
  });
});
```

**Comment by hfurness** [comment]
@DenisaHalmaghi  This is how we disabled virtualization for tests only by mocking using requireActual.

```
const mockDataGridPro = jest.fn();
jest.mock('@mui/x-data-grid-pro', () => {
  const { DataGridPro } = jest.requireActual('@mui/x-data-grid-pro');
  return {
    ...jest.requireActual('@mui/x-data-grid-pro'),
    DataGridPro: (gridProps: DataGridProProps) => {
      mockDataGridPro(gridProps);
      return <DataGridPro {...gridProps} disableVirtualization />;
    },
  };
});
```

**Comment by m4theushw** [comment]
I'll close this issue since it's a not bug. We can continue the discussion.
