### ISSUE TITLE
[data grid] `onRowsScrollEnd` fired without scrolling

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#4371]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

- initial 3 rows are rendered
- `onRowsScrollEnd` is called (even though there was no scroll event)
- newly-added 3 rows are rendered as well
- scroll doesn't trigger `onRowsScrollEnd` anymore

https://user-images.githubusercontent.com/13808724/161784597-0479a931-b345-4e7f-bf3a-87e47491b35b.mov

### Expected behavior 🤔

- initial 3 rows are rendered
- `onRowsScrollEnd` is not called, since there's no scroll event

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/infiniteloadinggrid-material-demo-forked-4uve2q?file=/demo.tsx

### Context 🔦

I've noticed it while investigating #4184

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by liho00** [comment]
https://github.com/mui/mui-x/pull/7416 this pr can solve infinite scroll issue, pls take a look ya.

**Comment by yaredtsy** [comment]
hey @cherniavskii 

there was a problem with scrollEnd detection. `rowsScrollEnd` cant be called multiple times continuously. it has some toggle mechanism. once the event is called it must go to `ScrollBottomArea`. removing it will fix this issue and #4184

```diff
$ git diff 'packages\grid\x-data-grid-pro\src\hooks\features\infiniteLoader\useGridInfiniteLoader.ts'
diff --git a/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts b/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
index fbe62f935..4ebdf2c74 100644
--- a/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
+++ b/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
@@ -43,15 +43,11 @@ export const useGridInfiniteLoader = (

       if (scrollPositionBottom < contentHeight - props.scrollEndThreshold) {
         isInScrollBottomArea.current = false;
       }

-      if (
-        scrollPositionBottom >= contentHeight - props.scrollEndThreshold &&
-        !isInScrollBottomArea.current
-      ) {
+      if (scrollPositionBottom >= contentHeight - props.scrollEndThreshold) {
         const rowScrollEndParam: GridRowScrollEndParams = {
           visibleColumns,
           viewportPageSize,
```

**Comment by liho00** [comment]
> hey @cherniavskii
> 
> there was a problem with scrollEnd detection. `rowsScrollEnd` cant be called multiple times continuously. it has some toggle mechanism. once the event is called it must go to `ScrollBottomArea`. removing it will fix this issue and #4184
> 
> ```diff
> $ git diff 'packages\grid\x-data-grid-pro\src\hooks\features\infiniteLoader\useGridInfiniteLoader.ts'
> diff --git a/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts b/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
> index fbe62f935..4ebdf2c74 100644
> --- a/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
> +++ b/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
> @@ -43,15 +43,11 @@ export const useGridInfiniteLoader = (
> 
>        if (scrollPositionBottom < contentHeight - props.scrollEndThreshold) {
>          isInScrollBottomArea.current = false;
>        }
> 
> -      if (
> -        scrollPositionBottom >= contentHeight - props.scrollEndThreshold &&
> -        !isInScrollBottomArea.current
> -      ) {
> +      if (scrollPositionBottom >= contentHeight - props.scrollEndThreshold) {
>          const rowScrollEndParam: GridRowScrollEndParams = {
>            visibleColumns,
>            viewportPageSize,
> ```

I dont think onRowsScrollEnd callback is a proper way for infinite scroll.
For eg. DataGridPro with height 1000px, calling backend infinite scroll with limit 2 items, hence backend returning 2 items and next cursor, the 2 items are rendered on the DataGrid however unable to scroll, as 1 row took 50px only, hence unable handle next cursor infinite scroll.

https://github.com/mui/mui-x/pull/7416 check this issue's video...

**Comment by yaredtsy** [comment]
hey @liho00 

`handleRowsScrollEnd` will be called every time the `rows.length` is changed. so every time data is fetched from the server it checks if `scrollPositionBottom` is greater than `contentHeight - props.scrollEndThreshold` and publishes the `rowsScrollEnd` event and it continues this loop until `scrollPositionBottom` is not greater than `contentHeight - props.scrollEndThreshold`. the problem was once `rowsScrollEnd` is published. it will be locked until `scrollPositionBottom` is less than `contentHeight - props.scrollEndThreshold`. and this won't happen until the `rows` exceed the Datagrid height.

https://github.com/mui/mui-x/blob/0203346f5cb38b280026326dbd91254d584ecdc6/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts#L46-L50

**Comment by liho00** [comment]
> hey @liho00
> 
> `handleRowsScrollEnd` will be called every time the `rows.length` is changed. so every time data is fetched from the server it checks if `scrollPositionBottom` is greater than `contentHeight - props.scrollEndThreshold` and publishes the `rowsScrollEnd` event and it continues this loop until `scrollPositionBottom` is not greater than `contentHeight - props.scrollEndThreshold`. the problem was once `rowsScrollEnd` is published. it will be locked until `scrollPositionBottom` is less than `contentHeight - props.scrollEndThreshold`. and this won't happen until the `rows` exceed the Datagrid height.
> 
> https://github.com/mui/mui-x/blob/0203346f5cb38b280026326dbd91254d584ecdc6/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts#L46-L50

nope,`onRowsScrollEnd` is not getting called every time when rows.length is changed...

```
    <DataGridPro
          initialState={{
            pinnedColumns: { left: ["email"], right: ["actions"] },
          }}
          rows={users}
          columns={columns}
          hideFooterPagination
          checkboxSelection
          disableSelectionOnClick
          loading={isLoading || isFetching}
          components={{
            LoadingOverlay: LinearProgress,
          }}
          onRowsScrollEnd={() => {
            console.log("sdjfhsiuf");
          }}
        />
```
<video width="320" height="240" src="https://user-images.githubusercontent.com/77238199/211150444-7b469fb4-2fc5-49f0-b836-9e984d537c5a.mov"></video>
the video is the result

**Comment by yaredtsy** [comment]
> nope,onRowsScrollEnd is not getting called every time when rows.length is changed...
 
not `onRowsScrollEnd`,  `handleRowsScrollEnd` will be called but it is not publishing `onRowsScrollEnd`, event every time.

https://github.com/mui/mui-x/blob/0203346f5cb38b280026326dbd91254d584ecdc6/packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts#L74-L79

check this demo,
Demo : https://codesandbox.io/s/elegant-river-kws9h7?file=/demo.tsx
git-commit: https://github.com/mui/mui-x/commit/a3c8faec854eb232725e4c33fd6e4b45f217941e

**Comment by liho00** [comment]
https://codesandbox.io/s/gifted-einstein-o1xc0e?file=/demo.tsx

@m4theushw yes `scrollEndThreshold=1` is not working...

**Comment by liho00** [comment]
> @liho00 You're using `params.viewportPageSize` to load new rows, but its value is zero. In this specific demo, with so little initial rows, using this param doesn't work. If you load a fixed number of rows, then `scrollEndThreshold=1` solves the problem. See the updated demo: https://codesandbox.io/s/eager-mcnulty-x4uwyk
> 
> @yaredtsy You've set the wrong prop.

@m4theushw 
nope u are trying 5 items with 400px heigh thats why no issues, please try load 1 item with 400px or 2items with 800px, 
the problem arise when loaded 3 times of item but still not scrollable, check this codesandbox again! https://codesandbox.io/s/dreamy-haze-r3xs7r?file=/demo.tsx

please also study my PR problem statement, thanks in advance! https://github.com/mui/mui-x/pull/7416

**Comment by yaredtsy** [comment]
Hey @m4theushw, I don't think that changing it to `IntersectionObserver` will solve this specific issue because the problem is caused by the toggle mechanism, the code that checks if the scroll position has left the bottom scroll area before firing the event again, preventing onRowsScrollEnd from being called infinitely. Therefore, even if it's changed to `IntersectionObserver`, this toggle mechanism must still be implemented. otherwise, onLoadMoreRows will be continuously called as long as the last row is in the viewport.

**Comment by DanailH** [comment]
**A quick note**: I've explored the idea of using the `IntersectionObserver` to replace the clunky check. The main issue is that if you go with the solution of adding an empty element (a `div` for example) at the bottom of the `GridVirtualScrollerRenderZone` then the `onLoadMoreRows` will be called on the first render before the rows are created/loaded. As far as I can see this is the only problem because you **do** want the callback to be called when you scroll to the bottom, then scroll up and back to the bottom again.

To avoid this another solution is to add a specific `className` to the last row that is currently loaded but it creates complications with the observable as you need to `observe` only after the rows are loaded and update which row has the distinct `className` once the user loads more rows.

**Comment by liho00** [comment]
> **A quick note**: I've explored the idea of using the `IntersectionObserver` to replace the clunky check. The main issue is that if you go with the solution of adding an empty element (a `div` for example) at the bottom of the `GridVirtualScrollerRenderZone` then the `onLoadMoreRows` will be called on the first render before the rows are created/loaded. As far as I can see this is the only problem because you **do** want the callback to be called when you scroll to the bottom, then scroll up and back to the bottom again.
> 
> To avoid this another solution is to add a specific `className` to the last row that is currently loaded but it creates complications with the observable as you need to `observe` only after the rows are loaded and update which row has the distinct `className` once the user loads more rows.

Not really... You havent explore the power of IntersectionObserver, and the deep of its concept let me show u an example.
There is no need an extra div for the solution of IntersectionObserver. 
Below is the solution that I used to replace onRowScrollEnd, by observing / detecting last visible row to fetch next page, which working as expected. 

```
   <Box sx={{ height: "35rem", width: "100%" }}>
        <DataGridPro
          apiRef={apiRef}
          pinnedColumns={lg ? { left: ["id"], right: ["actions"] } : {}}
          rows={rows}
          columns={columns}
          checkboxSelection={false}
          disableSelectionOnClick
          disableMultipleSelection
          loading={isLoading || isFetching}
          components={{
            LoadingOverlay: LinearProgress,
            Row: (props) => {
              const index = props.index;
              const lastItemIndex = rows.length - 2;
              // console.log("lastItemIndex", lastItemIndex, index);
              if (lastItemIndex === index) {
                return (
                  <div ref={lastOptionElementRef}>
                    <GridRow {...props} className="cursor-pointer"></GridRow>
                  </div>
                );
              }
              return <GridRow {...props} className="cursor-pointer"></GridRow>;
            },
          }}
        />
      </Box>
```
```
        const observer = useRef();

  const lastOptionElementRef = useCallback(
    (node) => {
      if (observer.current) observer.current.disconnect();
      observer.current = new IntersectionObserver(async (entries) => {
        if (isFetching) {
          return;
        }
        const [target] = entries;
        if (target.isIntersecting && hasNextPage) {
          fetchNextPage();
        }
      });
      if (node) observer.current.observe(node);
    },
    [fetchNextPage, hasNextPage, isFetching]
  );

```

**Comment by igortas** [comment]
@cherniavskii 
Scroll still firing in latest x grid without scrolling, and it has much worse problem, when needs to switch between two different values of rows, like 500 and 1500, and when u switching from higher value to smaller value of rows, the table is scrolling as much as it need to rich the higher value.
