### ISSUE TITLE
[data grid] The prop `formattedValue` is marked as required in `GridEditInputCell`, but its value is `undefined`

### ISSUE THREAD

**Issue by tsafadi** [mui/mui-x#4373]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

This issue can be reproduced in the demo: https://mui.com/components/data-grid/editing/#full-featured-crud-component
If you click "Add Record", the error is shown in the console.

### Expected behavior 🤔

No error should be thrown.

### Steps to reproduce 🕹

Steps:

1. Go to official demo https://mui.com/components/data-grid/editing/#full-featured-crud-component
2. Click "Add Record" 
3. Look at console

**Comment by flaviendelangle** [comment]
I noticed that yesterday.
`formattedValue` should accept `undefined` like the other interfaces.

**Comment by cherniavskii** [comment]
Hmm, I cannot reproduce the issue:
<img width="720" alt="Screenshot 2022-04-06 at 12 05 08" src="https://user-images.githubusercontent.com/13808724/161951392-5b09d4e2-94f8-4f92-9890-e79c0e984d4e.png">

**Comment by tsafadi** [comment]
Open it via CodeSandbox and check console.
