### ISSUE TITLE
[data grid] help creating an edit cell where dropdown options depend on selection made in a different edit cell.

### ISSUE THREAD

**Issue by nickraphael** [mui/mui-x#4374]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Lets suppose the first edit cell in my table lets the user choose car manufacturer.  Then, depending on that choice, the available options in the next edit cell are filtered car models.  Also, the whole row is in edit mode (editMode="row").

I've tried coding this manually with renderEditCell and outputting mui-select but the interplay is a nightmare.  Validation becoming super complex.

Has anyone got any advice or code samples?

Many thanks

**Comment by alexfauquette** [comment]
You have a similar example in the demo for single select columns which uses a function to define `valueOptions`, such as depending on the row values, the proposed discount is adapted

https://mui.com/components/data-grid/columns/#special-properties

```jsx
valueOptions: ({ row }) => { 
 if (row === undefined) {
    return ['EU-resident', 'junior'];
  }
  const options = [];
  if (!['United Kingdom', 'Brazil'].includes(row.country)) {
    options.push('EU-resident');
  }
  if (row.age < 27) {
    options.push('junior');
  }
  return options;
},
```

**Comment by nickraphael** [comment]
I’ve tried that approach but the incoming row seems to be the initial model - not the updated row once the first field is updated.

**Comment by alexfauquette** [comment]
Yes, the row is the row before editing. If you use row edit mode, there is no simple way to do that for now

With cell edit mode, you should not have the problem since after editing the first cell the row will be updated

If you really need row editing, a workaround is to use the `apiRef` such that in `valueOptions` you can get access to the editing state
```js
const valueOptions = React.useCallback(({id: rowId, row}) => {
	const editState = gridEditRowsStateSelector(apiRef);
	const constructor = editState[rowId]?.constructor?.value || row.constructor

	return carModels[constructor]
}, [apiRef])
```

**Comment by nickraphael** [comment]
Interesting thank you.  I’ll try that.  I’m still left with the issue of the value of field2 needing to be reset when field1 changes.  Otherwise I get that console warning about the field not being present in the list of options.  
in our example, that might be a row with constructor=Ford and model=Ranger.  User changes constructor to Mazda which changes the model list so that it no longer contains ranger.  If I don’t reset the value of carModel, I get that warning in the console.
Is there any event that fires when an item is selected in a singleSelect cell when in editMode=row?

**Comment by m4theushw** [comment]
> I’ve tried that approach but the incoming row seems to be the initial model - not the updated row once the first field is updated.

I think `valueOptions` should receive the row with the values that are being edited, not the initial row.

> If you really need row editing, a workaround is to use the apiRef such that in valueOptions you can get access to the editing state

This selector will be removed in v6. We should add a `getEditCellValue` method to the API.

> I’m still left with the issue of the value of field2 needing to be reset when field1 changes.

You can call `setEditCellValue` when field1 is changed and reset the value of field2. It can be called inside `preProcessEditCellProps`.

> in our example, that might be a row with constructor=Ford and model=Ranger. User changes constructor to Mazda which changes the model list so that it no longer contains ranger. If I don’t reset the value of carModel, I get that warning in the console.

Similar to that we have a demo showing how to validate the value of one field based on another: https://mui.com/components/data-grid/editing/#conditional-validation

> Is there any event that fires when an item is selected in a singleSelect cell when in editMode=row?

Yes, the `preProcessEditCellProps` prop is called.

**Comment by nickraphael** [comment]
> ```js
> gridEditRowsStateSelector
> ```

gridEditRowsStateSelector doesn't seem to work in DataGridPro...
