### ISSUE TITLE
[DataGridPro]When restoring state from local storage, column widths collapse

### ISSUE THREAD

**Issue by vakha30** [mui/mui-x#4375]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #4310
I will be solved by #4311 in the next release
