### ISSUE TITLE
Pinned columns shift when clicking column underneath

### ISSUE THREAD

**Issue by jdnvn** [mui/mui-x#4382]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when you click a certain area on the column header underneath the right pinned column, both of the pinned columns shift out of line.

https://www.veed.io/view/e9b8c03a-0c82-43b7-80b4-2976e8e0fc01

### Expected behavior 🤔

the pinned columns should stay pinned

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

    System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 14.19.1 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 6.14.16 - /usr/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.7.0 => 11.7.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.58
    @mui/icons-material: ^5.2.0 => 5.2.0
    @mui/lab: ^5.0.0-alpha.58 => 5.0.0-alpha.58
    @mui/material: ^5.2.2 => 5.2.2
    @mui/private-theming:  5.2.2
    @mui/styled-engine:  5.2.0
    @mui/styles: ^5.2.2 => 5.2.2
    @mui/system:  5.2.2
    @mui/types:  7.1.0
    @mui/utils:  5.2.2
    @mui/x-data-grid: ^5.1.0 => 5.8.0
    @mui/x-data-grid-pro: https://pkg.csb.dev/mui-org/material-ui-x/commit/bdbb25f0/@mui/x-data-grid-pro => 5.1.0
    @mui/x-license-pro:  5.1.0
    @types/react:  17.0.43
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
</details>

**Comment by m4theushw** [comment]
Similar to #4300. Will be fixed by #4280
