### ISSUE TITLE
[DataGridPro] Pressing `Space` on detail panel toggle cell doesn't toggle detail panel

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#4387]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`Space` doesn't toggle detail panel and moves focus to the bottom of the page:
https://mui.com/components/data-grid/group-pivot/#master-detail

https://user-images.githubusercontent.com/13808724/162194268-48934ad5-cbe9-4d46-8da6-34584b1ae821.mov

### Expected behavior 🤔

Similar to Row grouping, pressing `Space` on toggle cell should expand/collapse detail panel:
https://mui.com/components/data-grid/group-pivot/#row-grouping

https://user-images.githubusercontent.com/13808724/162194733-6386dda1-6216-4787-a5d4-f706eb902902.mov

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/components/data-grid/group-pivot/#master-detail
2. Focus detail panel toggle cell (the one with `+`)
3. Press `Space` key
4. See that detail panel was not toggled

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
cc @m4theushw

**Comment by m4theushw** [comment]
To toggle the detail panel, use <kbd>Ctrl</kbd> + <kbd>Space</kbd>. We require another key to not override the behavior of <kbd>Space</kbd>, that is [meant](https://mui.com/components/data-grid/accessibility/#navigation) to scroll to the end of the current viewable portion.

**Comment by cherniavskii** [comment]
> To toggle the detail panel, use Ctrl + Space

Yeah, that's supposed to work on every cell in the row, but I see few problems with that:
- Ctrl+Enter shortcut is not obvious. It's great to have it, but it's not sufficient
- Intuitively, users would expect `Space` to toggle detail panel - similar to row grouping feature

> behavior of Space, that is [meant](https://mui.com/components/data-grid/accessibility/#navigation) to scroll to the end of the current viewable portion

Yes, I'm aware of this functionality, but I believe it should toggle detail panel and not scroll to the end in this case

> Is this not a bug for the row grouping?

I believe it's not

**Comment by m4theushw** [comment]
> Intuitively, users would expect Space to toggle detail panel - similar to row grouping feature

You need to consider that master/detail and row grouping might be enabled at the same time. Using <kbd>Space</kbd> for both is problematic.

In v6 we could remove <kbd>Space</kbd> from scrolling the grid.

**Comment by flaviendelangle** [comment]
> In v6 we could remove Space from scrolling the grid.

Yes
This shortcut is very not intuitive for me

**Comment by m4theushw** [comment]
It's problematic if we toggle the detail panel when <kbd>Space</kbd> is pressed in any cell. If require that the detail panel column is focused for it to work then <kbd>Enter</kbd> could also be used.

**Comment by cherniavskii** [comment]
> It's problematic if we toggle the detail panel when Space is pressed in any cell.

I thinks we shouldn't do that

> If require that the detail panel column is focused for it to work then Enter could also be used.

Do you mean to use both `Enter` and `Space`? Makes sense, since that's the default behaviour for buttons: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#keyboard_interactions

**Comment by flaviendelangle** [comment]
I let you keep the behavior coherent between the master detail and the row grouping :+1:
