### ISSUE TITLE
[data-grid] No release note for `@mui/x-data-grid-pro@5.8.0` and documentation is not published

### ISSUE THREAD

**Issue by monicagavril** [mui/mui-x#4389]
### Order ID 💳

#32346

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm a bit confused by the release v5.8.0.
Looking on https://github.com/mui/mui-x/releases v5.7.0 is marked as latest, but in https://github.com/mui/mui-x/blob/master/CHANGELOG.md there is 5.8.0, but all the links to documentation or migration guide are returning 404.
I would like to update from version v5.6.1 to the new edit API and I'm not sure if I should use v5.7.0 or v5.8.0.

Could you please help?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
You can use the 5.7.0 for new editing API. But I would recommend taking the latest version 5.8.0.

Documentation is under refactoring, it should be live in a few days. The release [mui/mui-x/releases](https://github.com/mui/mui-x/releases) will be updated when docs is ready

If you need doc about restore state you can see the preview of v5.8.0: https://deploy-preview-4328--material-ui-x.netlify.app/components/data-grid/state/#save-and-restore-the-state

**Comment by jeveloper** [comment]
@alexfauquette  I get that you guys are updating things. FYI i'm a paid customer and love the product and framework.

Date pickers seem to have broken documentation for now.

**Comment by monicagavril** [comment]
Thank you very much for your answer!

**Comment by alexfauquette** [comment]
@jeveloper which pages seem to be broken?

**Comment by cherniavskii** [comment]
https://github.com/mui/mui-x/releases/tag/v5.8.0

**Comment by siriwatknp** [comment]
The documentation is updated. https://mui.com/x/react-data-grid/
