### ISSUE TITLE
[data grid] Export CSV file changes string values to numbers.

### ISSUE THREAD

**Issue by hayden-ntwglobal** [mui/mui-x#4390]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using this(`https://mui.com/components/data-grid/export/#csv-export`).

The Issue is,
**String value like 033984022515 is changed by force after export to .CSV file as number, so the value shows like 33984022515 this.**

This value's type is `varchar` from DB.
I added this(`type: 'string'`) to DataTable tag's column object.

### Expected behavior 🤔

Even after changing to a CSV file, each column must maintain the type desired by the developer.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

- "@mui/icons-material": "^5.3.0",
- "@mui/material": "^5.3.0",
- "@mui/styles": "^5.4.2",
- "@mui/x-data-grid": "^5.2.2",

**Comment by alexfauquette** [comment]
Hi @hayden-ntwglobal What do you mean by "maintaining the type desired"?

A [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) is a plain text object. There is no way to distinguish the number 42 from the string 42. 

Associating type to value is done by the file reader. For example, LibreOffice with default settings reads `"25,124"` as a number
