### ISSUE TITLE
[DateRangePicker] No errors triggered if user puts all zeroes on the date picker (dayjs)

### ISSUE THREAD

**Issue by abu-shoev** [mui/mui-x#4394]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We are using the DayJs as our date adapter, and that is what seems to cause some issues on the date range picker.  
As a date range picker we have two fields, start and end fields. When we put all zeroes on both fields, we don't get any validation errors, so if we then apply those given values,  then it's just selecting the current date.

### Expected behavior 🤔

It should instead invalidate the input component when the user attempts to apply the given values, since all zeroes are not valid input.

### Steps to reproduce 🕹

Steps:

1. Navigate to the following link: https://codesandbox.io/s/material-ui-dayjs-0-issue-zoghz2
2. Put 00/00/0000 on the date picker field
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Seems this issue has been solved during the migration

Here is thee codesandbox with the `@mui/x-date-pickers` package
https://codesandbox.io/s/material-ui-dayjs-0-issue-forked-9g8xgr?file=/demo.tsx

I'm a bit confused, the title is talking about `DateRangePicker`, but the codesandbox is using a `DateField`

**Comment by flaviendelangle** [comment]
`DatePicker` you mean ?

**Comment by alexfauquette** [comment]
Yes

**Comment by flaviendelangle** [comment]
I'm closing since it seems to now be fixed
