### ISSUE TITLE
[data grid] Column reorder not working

### ISSUE THREAD

**Issue by Hameezr** [mui/mui-x#4440]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After setting the orderedFields in the initialState, the state is still not maintained upon refresh. 

### Expected behavior 🤔

The state of column reorder should be maintained. 

### Steps to reproduce 🕹

Steps:

1. pass the prop of initial state in DataGrid
2. set the orderedFields
3. Refresh the page, the initial state is not mintained.

https://codesandbox.io/s/columnorderinggrid-material-demo-forked-m4zhq5?file=/demo.js

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

System:
    OS: macOS 12.0.1
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.1
  npmPackages:
    @emotion/react: ^11.7.0 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.65 
    @mui/lab: ^5.0.0-alpha.58 => 5.0.0-alpha.65 
    @mui/material: ^5.2.2 => 5.3.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/styles: ^5.2.2 => 5.3.0 
    @mui/system:  5.3.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid:  5.8.0 
    @mui/x-data-grid-pro: ^5.8.0 => 5.8.0 
    @mui/x-license-pro:  5.7.0 
    @types/react:  17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.1 => 5.3.3 
```
</details>

### Order ID 💳 (optional)

40931

**Comment by flaviendelangle** [comment]
I don't see any initial state passed to the grid on your example
Could you update it ?

**Comment by Hameezr** [comment]
> I don't see any initial state passed to the grid on your example Could you update it?

Apologies, the initial demo link wasn't forked! I have updated the link!

**Comment by flaviendelangle** [comment]
On your example I think the problem is that you have the `useDemoData` hook that causes a re-render and your columns are not memoized.

So the following occures

1. Render with `id` => `idBis`
2. Re-render and update columns with `idBis` => `id`

Here is a [working example](https://codesandbox.io/s/columnorderinggrid-material-demo-forked-wdedg4?file=/demo.js)

But if you can reproduce it in a real use case I will investigate :+1:

**Comment by Hameezr** [comment]
@flaviendelangle I was wondering if this will cause an issue whenever data is being fetched from the server side since it will enforce a re-render even if the columns have been memoized! Just curious if this scenario has been tested.

**Comment by flaviendelangle** [comment]
If the columns are memoized, it should not cause any issue.
