### ISSUE TITLE
[data grid] Compatibility of `@mui/x-data-grid` and `@mui/x-data-grid-pro` with React 18

### ISSUE THREAD

**Issue by fahadashiq12** [mui/mui-x#4442]
I am worried about the support of mui/x-data-grid and mui/x-data-grid-pro and mui/x-data-grid-generator are supported in react 18 project or not?

**Comment by flaviendelangle** [comment]
The next release of the `@mui/x-data-grid` and `@mui/x-data-grid-pro` packages should be compatible with React 18.

**Comment by fahadashiq12** [comment]
Thank you for the prompt response, any expected time how long it will take for new versions of @mui/x-data-grid and @mui/x-data-grid-pro to release and make it compatible with React 18?

**Comment by flaviendelangle** [comment]
Most likely at the end of this week

You have more details on https://github.com/mui/mui-x/pull/4332

**Comment by fahadashiq12** [comment]
Thank you will be waiting I am creating a new application in React 18 and these data-rich tables are definitely a great solution team MUI for always being there to help and answer queries promptly, I really appreciate it...

**Comment by m4theushw** [comment]
While a new version is not released you can also use the package generated by #4332. Here's a CodeSandbox using it: https://codesandbox.io/s/datagridprodemo-material-demo-forked-qvr2t0?file=/demo.tsx

**Comment by m4theushw** [comment]
Closed by #4332
