### ISSUE TITLE
[DateTimePicker] `hideTabs` is not working properly on `DesktopDateTimePicker`

### ISSUE THREAD

**Issue by martin-trajanovski** [mui/mui-x#4448]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

There is prop called `hideTabs` on each and every `DateTimePicker` (https://mui.com/api/desktop-date-time-picker/#:~:text=between%20views%20button.-,hideTabs,-bool) variant but it is not working properly (not hiding tabs on the desktop variant at least) when I add it on a plain `DateTimePicker` or `DesktopDateTimePicker`.

### Expected behavior 🤔

When I use the `hideTabs` prop on a `DateTimePicker` I expect that the calendar and time tabs are hidden on the dialog but they are still there.

### Steps to reproduce 🕹

Here is an example: https://codesandbox.io/s/dank-field-3zzvo?file=/src/App.js

### Context 🔦

I am trying to create a custom `DateTimePicker` that should show only `hours` and `minutes` at some condition. For now it works if I try to use the `views` prop and set it to `['hours', 'minutes']` but the calendar tab is still there and date is changeable. I want to prevent ability to change the date at some point.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
   System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99 (Official Build) (64-bit)
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.65
    @mui/icons-material: ^5.3.0 => 5.3.0
    @mui/lab: ^5.0.0-alpha.65 => 5.0.0-alpha.65
    @mui/material: ^5.3.0 => 5.3.0
    @mui/private-theming:  5.3.0
    @mui/styles: ^5.3.0 => 5.3.0
    @mui/system:  5.3.0
    @mui/types:  7.1.0
    @mui/utils:  5.3.0
    @types/react: ^17.0.35 => 17.0.38
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.4 => 4.5.5
```
</details>

**Comment by flaviendelangle** [comment]
Fixed by #5972 
See [this reproduction case](https://codesandbox.io/s/date-and-time-pickers-forked-urf47c)
