### ISSUE TITLE
[pickers] The minutes and seconds default value is taken from current date instead of being 00

### ISSUE THREAD

**Issue by tomas-c** [mui/mui-x#4449]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you go to https://mui.com/components/date-time-picker/#api and try selecting a day on the "Clear Initial State" input you will notice that the minutes are initially set to the minutes of the current hour. The seconds of the Date value will also be set to the current seconds of the minute (althought that is not visible unless you inspect the value object).

This is almost never desired and breaks naive integrations with libraries such as React Final Form or React Hook Form.  

Also, if you have set `minutesStep={5}` it will not be respected.

A similar issue has already been addressed on the TimePicker in mui/material-ui#24887 but was not fixed for DateTimePicker (and maybe even DatePicker and DateRangePicker?).

**Comment by flaviendelangle** [comment]
I agree that we should instead use midnight, like on the time picker.
I don't know why it was explicitly using the current time...
