### ISSUE TITLE
[data grid] Expose `rowNode.childrenExpanded` state to `getRowClassName` function

### ISSUE THREAD

**Issue by joe0BAB** [mui/mui-x#4453]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to be able to style a row based on the collapse/expanded state of it so I can implement a design like this: 
![image](https://user-images.githubusercontent.com/26611551/162767449-5ed7468e-9d03-4cb1-a4df-42882ead4fa0.png)

Eg remove the border so it's more clear expanded rows belong together.

`getRowClassName` already is very useful, it would be convenient if I could access the rows collapsed/expanded state.

**Comment by flaviendelangle** [comment]
Hi,

You should be able to get this information from the `apiRef`

See [this example](https://codesandbox.io/s/data-grid-pro-forked-r5lxbz?file=/src/App.tsx)

We could add it on the params of `getRowClassName`. But it would mean adding a slight computation overhead for every user, even those who will not take advantage of it.

**Comment by joe0BAB** [comment]
Thank you for this quick response! This solves my problem! I wasn't aware of this way to do it. Awesome!! I'll close this issue then.
