### ISSUE TITLE
[DateTimePicker] showToolbar default value is `true`, should be `false`

### ISSUE THREAD

**Issue by timonla** [mui/mui-x#4455]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The default value for `showToolbar` is `true`.

### Expected behavior 🤔

The default value should be `false` like the documentation suggests.

### Steps to reproduce 🕹

1. Look at the documentation of any DateTimePicker component (https://mui.com/api/desktop-date-time-picker/)
2. It says that `showToolbar` is `false` by default
3. See actual default value here: https://codesandbox.io/s/priceless-haslett-vg1bi?file=/src/Demo.tsx

### Context 🔦

This is an issue with `DateTimePicker`, `MobileDateTimePicker` and `DesktopDateTimePicker`. It seems to work as specified in documentation for `DatePicker` and `TimePicker` components.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Sorry for the delay, I applioed your pull request on the new package in #4451
