### ISSUE TITLE
[data grid] Column menu closing when row data is updated

### ISSUE THREAD

**Issue by TeoAvignon** [mui/mui-x#4471]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On each update of the grid data, the column menu closes.
When refreshing with high frequency (let's say every second), it is almost impossible to click in the column menu before it closes.

You can easily test this behaviour in your "high frequency' sandbox: [](https://codesandbox.io/s/32njyv?file=/demo.tsx)

### Expected behavior 🤔

The menu should remain open when the data are changing

### Steps to reproduce 🕹

Steps:

1.Change your grid data with a high frequency
2.click on  a column menu
3. try to catch the filter button (becomes hards with a refresh period of 1s)
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates https://github.com/mui/mui-x/issues/4139

I close thise one and link your example on the main issue
