### ISSUE TITLE
[DateRangePicker] Focusing start date after accept event

### ISSUE THREAD

**Issue by perotta** [mui/mui-x#4476]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After selecting start and end date, Date Range Picker is automatically focusing start date input back, keeping the dialog opened.

Even if you try to control the "openess" state and close the dialog inside "onAccept" (see sandbox demo), it focuses the start date input after the accept event, firing once again "onOpen" callback and giving the impression the dialog was never closed.

### Expected behavior 🤔

On Desktop, I expect the Dialog to close (and stay closed) after the accept event without the Start Date being focused back.  

### Steps to reproduce 🕹

https://mui.com/components/date-range-picker/#basic-usage
or (codesandbox with controlled open state)
https://codesandbox.io/s/basicdaterangepicker-material-demo-forked-j8c0vt?file=/demo.js

Steps:

1. Click on Start Date to open the dialog
2. Select a Start Date
3. Select an End Date greater than the Start Date

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Using Google Chrome v97 on desktop Ubuntu 20.04

  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
I transfered this issue to the MUI X repo (see our [blog post](https://mui.com/blog/lab-date-pickers-to-mui-x/) for context)

I will have a look at this one
