### ISSUE TITLE
[data grid] broken scroll after error (version 4.0.2)

### ISSUE THREAD

**Issue by w3lld1** [mui/mui-x#4477]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Scroll is broken if:
1. we got error in data-grid
2. retry request and get successful response
3. scroll is broken

### Expected behavior 🤔

scroll isn't broken

### Steps to reproduce 🕹

Steps:

1. open [codesandbox](https://codesandbox.io/s/data-grid-scroll-bug-kjy3oj?file=/demo.tsx)
2. block 'users' request in browser devtools
3. see error state in data-grid
4. unblock 'users' request
5. wait for retry request
6. get successful response
7. scroll is broken

### Context 🔦

This bug is reproduced in data-grid v4. It's okay in data-grid v5.

Is it possible to fix this bug in v4? We use data-grid with material-ui v4 and we don't have resources to update mui version to 5

### Your environment 🌎

<details>
  <summary>libraries:</summary>

```
[@emotion/react](https://codesandbox.io/examples/package/@emotion/react)
11.9.0
[@emotion/styled](https://codesandbox.io/examples/package/@emotion/styled)
11.8.1
[@material-ui/core](https://codesandbox.io/examples/package/@material-ui/core)
latest (4.12.4)
[@material-ui/icons](https://codesandbox.io/examples/package/@material-ui/icons)
latest (4.11.3)
[@mui/material](https://codesandbox.io/examples/package/@mui/material)
5.6.0
[@mui/x-data-grid](https://codesandbox.io/examples/package/@mui/x-data-grid)
4.0.2
[@types/react](https://codesandbox.io/examples/package/@types/react)
latest (18.0.2)
[@types/react-dom](https://codesandbox.io/examples/package/@types/react-dom)
latest (18.0.0)
[react](https://codesandbox.io/examples/package/react)
17.0.2
[react-dom](https://codesandbox.io/examples/package/react-dom)
17.0.2
[swr](https://codesandbox.io/examples/package/swr)
1.2.2
[typescript](https://codesandbox.io/examples/package/typescript)
latest (4.6.3)
```
</details>

**Comment by m4theushw** [comment]
The v4 and v5 versions have diverged a lot and it's too time consuming to bring fixes from newer versions back to v4. As alternative, we have a guide explaining how to use DataGrid v5 with MUI v4. https://mui.com/x/react-data-grid/migration-v4/#using-mui-core-v4-with-v5

Does it work for you?

**Comment by w3lld1** [comment]
Yes, it works for project with react v17, but it won't work for legacy project because of requirements to installing MUI v5 (react v17)

**Comment by m4theushw** [comment]
I didn't understand. DataGrid v4 also only works with React 17.

**Comment by w3lld1** [comment]
It's a little bit confusing. I didn't find information that DataGrid v4 works only with React 17.
Could you please attach link to the docs with this information?

**Comment by m4theushw** [comment]
https://v4.mui.com/getting-started/installation/#npm mentions that react >= 16.8.0 is required, but this only applies to `@mui/material`. For the DataGrid v4 we don't really say the version supported in the docs, but it's in `package.json`:

https://github.com/mui/mui-x/blob/e9a6feff73da5bc3943622f82b9a0d62608d323f/packages/grid/data-grid/package.json#L51

The package manager will warn if it's installed without the correct peer dependencies.

**Comment by w3lld1** [comment]
Oh, I see. Thanks.
