### ISSUE TITLE
[DatePicker] input cannot be cleared while focused

### ISSUE THREAD

**Issue by Shrugsy** [mui/mui-x#4485]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If the input is focused, when programatically setting the value for the `DatePicker` component to `null`, the old value remains visible in the input

### Expected behavior 🤔

The input should be cleared when setting the value to `null`, even while focused

### Steps to reproduce 🕹

Steps:

1. Click in the 'name' input and type a valid string
2. Click in the 'Date of birth' input and type a valid date (e.g. type '01021990')
3. While still focused in the 'Date of birth' input, press 'Enter' to submit the form, which clears the values used by both inputs
4. Observe that the old 'Date of birth' remains visible, but the 'name' clears correctly

https://codesandbox.io/s/agitated-snow-p9xb2?file=/src/Demo.tsx

### Context 🔦

I am trying to clear form input after 'submitting' the form. If the user has their focus in the 'date of birth' field while submitting, the input value does not clear correctly after submission. If the user is focused in a normal `TextField`, or otherwise clicks the 'Submit' button directly, all fields clear as expected.

Note: mui/mui-x#4870 is a similar issue, but not the same issue. mui/mui-x#4870 is regarding the input not clearing for 'invalid' dates, while this issue occurs for both 'invalid' and 'valid' dates, as long as the field is focused.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 94.0
```
</details>

**Comment by PatrykFij** [comment]
I have similar problem. It looks like not focus issue but maybe not fully filled mask fields.

Steps:
1. Clear date input using X icon. 
2. Type not completed date and try to clear input again -> characters is still be visible.
3. Complete the date and try to clear input again. Field is cleared.

https://codesandbox.io/s/nostalgic-swirles-23111n

**Comment by flaviendelangle** [comment]
@alexfauquette what is the current state of this issue ?

**Comment by alexfauquette** [comment]
It's an ongoing PR 
https://github.com/mui/mui-x/pull/4486

Globally it works. But for now, it introduces a new bug: If I write a date and then delete some digits, the value is not set back to `null`. Plus failing tests to check

https://codesandbox.io/s/basicdatepicker-material-demo-forked-ni1d6z?file=/demo.tsx

It's on my todo list for next week with the l10n+action slots

**Comment by flaviendelangle** [comment]
OK, can we link the PR to this issue to keep track of it ?
