### ISSUE TITLE
[DateTimePicker] Mask with non numeric data are not applied

### ISSUE THREAD

**Issue by cattre** [mui/mui-x#4487]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using the DateTimePicker component, a warning is displayed in the console about the mask not matching the input value:

`The mask "__/__/____ __:__" you passed is not valid for the format used dd MMMM yyyy HH:mm. Falling down to uncontrolled not-masked input. `

No mask has been provided, so I assume this is using the default one.

The spaces instead of slashes are one issue, but adding a custom mask of '__ __ ____ __:__' resolves this.

It appears there is an issue with the full month name (MMMM) as a numeric month (MM) works fine (and '__ ____ ____ __:__' doesn't help).

### Expected behavior 🤔

Custom date formats do not throw warnings in the console

### Steps to reproduce 🕹

Live example here:

https://codesandbox.io/s/elegant-nobel-lqyol?file=/src/App.js:518-536

### Context 🔦

Similar to issue posted here - https://github.com/mui-org/material-ui-pickers/issues/1776 - but this repo has been archived so I'm unsure if the answers are still relevant with MUI 5.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by nimaes80** [comment]
In my case first I set `LocalizationProvider` in root of peroject
```
import { AdapterMoment } from "@mui/x-date-pickers/AdapterMoment";
import AdapterJalali from "@date-io/date-fns-jalali";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
// ...

<LocalizationProvider dateAdapter={i18n.language === "fa" ? AdapterJalali : AdapterMoment}>
// ...
</LocalizationProvider>
```
then I use `DatePicker` like blow
```
<DatePicker
	mask="____/__/__"
	value={date}
	onChange={(newValue) => setDate(newValue)}
	renderInput={(params) => <TextField {...params} />}
/>
```
note that I use `@date-io/date-fns-jalali` for Jalali Time before that I see that yellow box also time dosnt show correctly with other library's

**Comment by woorykim** [comment]
https://github.com/mui/mui-x/issues/4487#issuecomment-1097731043
Thanks to you, I solved it👍 Thank you!
```js
mask=""
inputFormat="yyyy-MM-dd"
```

**Comment by JackEdwardLyons** [comment]
Seems like the latest may around this is to set `disableMaskedInput` as a prop on your component. In my case it looked like this:

```
<DesktopDatePicker
        disableMaskedInput
        inputFormat='dd MMM yy'
        value={selectedDate}
        onChange={handleDateChange}
        renderInput={(params) => <TextField {...params} variant='standard' />}
      />
```

**Comment by sijinyu** [comment]
@JackEdwardLyons 

You saved my life 👍

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.
