### ISSUE TITLE
[DataGrid] Is it possible to add the same function to "the NumpadEnter key" of the keyboard as "the Enter key" of the keyboard

### ISSUE THREAD

**Issue by FairyWorld** [mui/mui-x#4492]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When I finish editing the cell and save it, if the default cell is used, "numpadenter key" and "enter key" can automatically switch to the next cell, but when I use "rendercell" to customize the cell, "enter key" can automatically switch to the next cell, and "numpadenter key" does not work normally

### Motivation 🔦

When I finish editing the cell and save it, if the default cell is used, "numpadenter key" and "enter key" can automatically switch to the next cell, but when I use "rendercell" to customize the cell, "enter key" can automatically switch to the next cell, and "numpadenter key" does not work normally

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
