### ISSUE TITLE
Incorrect version bump in x-data-grid

### ISSUE THREAD

**Issue by atomicpages** [mui/mui-x#4493]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`@mui/x-data-grid@5.8.0` requires `react@^18` which is a breaking change

### Expected behavior 🤔

MUI data grid should bump to version 6

### Steps to reproduce 🕹

N/A

### Context 🔦

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html there's a migration guide; ergo a breaking change.

### Your environment 🌎

Node 16.13.0
NPM 8.5.4

Not applicable for the browser

**Comment by m4theushw** [comment]
The version `5.8.0` requires `react@^17.0.2`.

https://github.com/mui/mui-x/blob/7f55c6e3d8b620aff49ca7e3ea633583f9f8887f/packages/grid/x-data-grid/package.json#L57

Are you sure that is not another dependency that only works with React 18?

**Comment by atomicpages** [comment]
Whoops, I forgot to update this thread. I saw the peer dep was right. Looks like it might be related to `@mui/material`

```log
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving:my-app@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^17.0.2" from @mui/x-data-grid@5.8.0
npm ERR!   node_modules/@mui/x-data-grid
npm ERR!     @mui/x-data-grid@"^5.8.0" from the root project
npm ERR!   3 more (@mui/material, @emotion/react, @emotion/styled)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from react-dom@18.0.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^17.0.0 || ^18.0.0" from @mui/material@5.6.1
npm ERR!   node_modules/@mui/material
npm ERR!     @mui/material@"^5.5.1" from the root project
npm ERR!     1 more (@mui/x-data-grid)
```

**Comment by m4theushw** [comment]
`@mui/material` works with React 18 but `@mui/x-data-grid` doesn't yet. The release of tomorrow will update the peer dependencies.

**Comment by m4theushw** [comment]
`@mui/x-data-grid@5.9.0` was released. You should be able to install it with React 18 now.
