### ISSUE TITLE
Custom input components data grid pro

### ISSUE THREAD

**Issue by Utkarshk7** [mui/mui-x#4494]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I can see following example for Custom input component which is great-
https://codesandbox.io/s/u69vgq?file=/demo.js

We want a **Select** component instead of **Rating**. 
We would like to have a behavior Similar to country column or Is admin? column.

In the code sample - https://codesandbox.io/s/u69vgq?file=/demo.js , i can not see the code for country or is admin?

Would it be possible to share a reference code for columns country or is admin?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#39429

**Comment by cherniavskii** [comment]
> We want a Select component instead of Rating.

Do you mean filter panel? Something like this? https://codesandbox.io/s/custominputcomponent-material-demo-forked-21lvx1?file=/demo.js

**Comment by Utkarshk7** [comment]
Perfect, thanks :)
