### ISSUE TITLE
[question] Toolbar as menu consuming keyboard input

### ISSUE THREAD

**Issue by linojon** [mui/mui-x#4497]
### Order ID 💳

41465

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am replacing the default toolbar component with a settings menu. The menu adds a new button to Save the current filter model (etc) using a dialog box with an input field. If i close the settings menu first, the dialog box does not open. If i leave the settings menu open, and open the dialog, the settings menu items consume the keyboard keys (eg "f" for Filter, "c" for Columns, "d" for Density, and "s" for Save are not input. I've created an example in codesandbox.

Specifically i have questions:
* if i put onClick={handleClose} on MenuItem, my Save dialog box doesnt open
* if tool menu remains opened, menu captures keyboard input eg can't type "f" "c" "d" "s" keys 
* also how can i to close the tool menu after submenu item is selected?

TIA for any assistance.

https://codesandbox.io/s/datagrid-settings-menu-issue-7u7sjs

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
> if i put onClick={handleClose} on MenuItem, my Save dialog box doesnt open

The save dialog is rendered inside the menu. What happens is that when `onClick` is called, it removes the menu, and also the save dialog. To solve, render the save dialog outside the menu.

> if tool menu remains opened, menu captures keyboard input eg can't type "f" "c" "d" "s" keys

This will be fixed for free if the save dialog is rendered outside the menu.

> also how can i to close the tool menu after submenu item is selected?

You did correctly. Each menu item has to call `onClick` and `onClick` changes `open=false`.

**Comment by linojon** [comment]
ah, works nicely now. Thank you
