### ISSUE TITLE
DateRangePicker clearable does not show clear button

### ISSUE THREAD

**Issue by zigang93** [mui/mui-x#4503]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

no clear button at DateRangePicker
but it work fine with DatePicker

https://codesandbox.io/s/basicdatepicker-material-demo-forked-r6zgui?file=/demo.tsx

### Expected behavior 🤔

have clear button

### Steps to reproduce 🕹

sandbox link: https://codesandbox.io/s/basicdatepicker-material-demo-forked-r6zgui?file=/demo.tsx

**Comment by flaviendelangle** [comment]
Same problem on `DesktopTimePicker`, fixing in #4408
