### ISSUE TITLE
[DatePicker] showTodayButton does not work in v5 DatePicker (desktop)

### ISSUE THREAD

**Issue by jim-moody** [mui/mui-x#4505]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Setting the `showTodayButton` prop to `true` in the DatePicker does nothing

## Expected Behavior 🤔

Setting the the `showTodayButton` prop to `true` in the DatePicker should trigger the Today button
https://next.material-ui.com/api/date-picker/#main-content

## Steps to Reproduce 🕹
https://codesandbox.io/s/angry-tu-yijlx?file=/src/App.js
![Screen Shot 2021-08-23 at 8 57 27 AM](https://user-images.githubusercontent.com/26190589/130451860-206d472b-4fe3-43b6-96f9-377f00fc8f09.png)

## Context 🔦

Our users use the Today button frequently and they will be upset if it is not there

## Your Environment 🌎

N/A

**Comment by flaviendelangle** [comment]
Closes by #4778 
See the following example: https://codesandbox.io/s/date-and-time-pickers-forked-kcctde?file=/src/App.tsx

```tsx
import * as React from "react";
import TextField from "@mui/material/TextField";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DesktopDatePicker } from "@mui/x-date-pickers/DesktopDatePicker";

export default function ResponsiveTimePickers() {
  const [value, setValue] = React.useState<Date | null>(
    new Date("2018-01-01T00:00:00.000Z")
  );

  return (
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <DesktopDatePicker
        label="For desktop"
        value={value}
        onChange={(newValue) => {
          setValue(newValue);
        }}
        renderInput={(params) => <TextField {...params} />}
        componentsProps={{
          actionBar: {
            actions: ["today"]
          }
        }}
      />
    </LocalizationProvider>
  );
}
```
