### ISSUE TITLE
[data grid] valueSetter is called every time value changes while in edit mode (only in 5.9.0)

### ISSUE THREAD

**Issue by amitozalvo** [mui/mui-x#4519]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Defining valueSetter function on an editable column results in it being called every time the value is edited while in edit mode

### Expected behavior 🤔

valueSetter should be called only once, when the cell is no longer in edit mode

### Steps to reproduce 🕹

Steps:

1. Create a string column with a value setter that prints a message to the console
` valueSetter(params) {
       console.log("TEST");
       return params.row;
  }`
2. Run the app
3. Edit a cell of the created column
4. While editing, every change to the input will result in TEST being printed to the console

### Context 🔦

This only happens in 5.9.0
I have downgraded to 5.8.0 and it doesn't happen there.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browser: Chrome
System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.88
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.4.1 => 11.9.0 
    @emotion/styled: ^11.3.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.76 
    @mui/icons-material: ^5.0.1 => 5.6.1 
    @mui/material: ^5.0.2 => 5.6.1 
    @mui/private-theming:  5.6.1 
    @mui/styled-engine:  5.6.1 
    @mui/styles: ^5.0.1 => 5.6.1 
    @mui/system:  5.6.1 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid: 5.8.0 => 5.8.0 
    @mui/x-data-grid-pro: 5.8.0 => 5.8.0 
    @mui/x-date-pickers:  5.0.0-alpha.0 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.0 => 5.0.0-alpha.0 
    @mui/x-license-pro:  5.7.0 
    @types/react: 18 => 18.0.5 
    react: ^18.0.0 => 18.0.0 
    react-dom: ^18.0.0 => 18.0.0 
    typescript: ^4.4.4 => 4.6.3 
```
</details>

### Order ID 💳 (optional)
#31154

**Comment by amitozalvo** [comment]
I'm actually stuck here since 5.8.0 has scrolling bug with React 18...

**Comment by cherniavskii** [comment]
I can reproduce the issue with new editing API, but not with the old one:
- new editing API: https://codesandbox.io/s/valueparsersettergrid-material-demo-forked-tb5mfe?file=/demo.tsx
- old editing API: https://codesandbox.io/s/valueparsersettergrid-material-demo-forked-q65s29?file=/demo.tsx

This is probably a side-effect of https://github.com/mui/mui-x/pull/4392
@m4theushw would you take a look?

**Comment by m4theushw** [comment]
To be able to pass the updated `row` to the edit components we need to call the `valueSetter` again. This is an expected behavior of #4392. I'm interested to understand why this is a problem in your application. Do you do any kind of complex processing in `valueSetter`?

> While editing, every change to the input will result in TEST being printed to the console

This edit component is debounced. `valueSetter` is called after some milliseconds.

**Comment by amitozalvo** [comment]
> To be able to pass the updated `row` to the edit components we need to call the `valueSetter` again. This is an expected behavior of #4392. I'm interested to understand why this is a problem in your application. Do you do any kind of complex processing in `valueSetter`?

I'm sending the update to the server, and this causes a request to be sent every time the value changes (the debouncing is not really solving anything in my case)

I'm not using row editing, and even if I would, I believe it's not really relevant to update if you're still editing a cell (until you press Enter or unfocus the cell)

This is a regression / a breaking change on my end, I would really appreciate a workaround or at least a flag to disable this feature.

**Comment by m4theushw** [comment]
The `valueSetter` is not meant to trigger side effects (e.g. server request). Its purpose is to only process the row and return it transformed. If you need to send the value to the server, you should use `processRowUpdate`. This is the recommended approach according to the docs: https://mui.com/components/data-grid/editing/#persistence

**Comment by amitozalvo** [comment]
But I'm not setting anything in the row. It's a column that reflects an inner object that shouldn't change in the client side, only in the server side.

So where should I store the intermediate value?
For example:
first column: product ({id, name, sku})
second column: sku (just a reflection of product.sku, whene it is committed, I'm going to just update the SKU in the server side and that will update the product object and will also update the SKU because of the valueGetter)

Based on your approach, I'm now going to directly change the SKU of the product even though It's not really a value I'm allowed to change locally.

For more context, I'm using Apollo GraphQL to handle the state of the rows

**Comment by m4theushw** [comment]
From your example I didn't understand which column you're editing. Does the first column has a `valueGetter` and only displays the name? Could you create a CodeSandbox?

> Based on your approach, I'm now going to directly change the SKU of the product even though It's not really a value I'm allowed to change locally.

Based on my previous question I'll assume you're editing only the name. In this case, I keep the same SKU and ID but only change the name in the `valueSetter`. When `processRowUpdate` is called you return the new product object with the updated SKU. This new object will replace the object in the state.

The first demo in https://mui.com/x/react-data-grid/editing/#persistence also shows how to pre-process the row that goes to the state. It always converts the name to uppercase in the server.
