### ISSUE TITLE
[pickers] Clearing TimePicker input value throws an error

### ISSUE THREAD

**Issue by ekoemets** [mui/mui-x#4535]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

TimePicker throws an error when its inserted time is cleared by deleting the value from textfield. I was using date-fns as the date-library but probably could happen also with others.

### Expected behavior 🤔

Expected it to return null as the value after clearing the textfield.

### Steps to reproduce 🕹

This issue can be reproduced using the basic TimePicker example provided by the documentation.
CodeSandbox example: https://codesandbox.io/s/basictimepicker-material-demo-forked-7ht7sp

Steps:

1. Insert valid time into the TimePicker
2. Clear the inserted time by deleting all of its input

### Context 🔦

The error seems to originate from the valueManager.valueReducer function, where the newValue is passed to the mergeDateAndTime function without checking if it is a Date object.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browsers:
    Chrome: 100.0.4896.88
```
</details>

**Comment by flaviendelangle** [comment]
Fixed by #4582
