### ISSUE TITLE
[DateRangePicker] Is it possible to render something in rangePicker modal?

### ISSUE THREAD

**Issue by davidroman-hub** [mui/mui-x#4539]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello! basically i would like to add some components to the date range picker, but i didn't find a render option to add more components... if we have an existing behaviour to do this let me know.. The next example show like different range option that you can modify, it could be nice to have something like this... but i don't know if this is possible. just adding a custom component inside the range picker modal we can implement a lot of this kind of stuff.

### Examples 🌈

https://www.npmjs.com/package/react-date-range

### Motivation 🔦

Different user scenario to just click in a custom data range

**Comment by cherniavskii** [comment]
Hey @davidroman-hub 
Can you clarify what you are trying to achieve? Thanks!

**Comment by flaviendelangle** [comment]
Since the issues were migrated and note answered by our team before weeks, we will of course re-open if you can provide us with the needed information :+1:
