### ISSUE TITLE
[StaticDateRangePicker] Changing the controlled value from outside does not change the visible month

### ISSUE THREAD

**Issue by jdevalez** [mui/mui-x#4542]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Current view of the calendar is current and next month.
Have a preset to select a date range outside of the currently visible months.
Setting this value does select the range in the calendar but does not change the month view to the selected date range, this has to be done manually.

## Expected Behavior 🤔

Setting the value in a controlled StaticDateRangePicker will also update the calendar view to the start of the new date range selection.

## Steps to Reproduce 🕹

https://codesandbox.io/s/display-bug-mui-staticdaterangepicker-p4umz

Steps:

1. Click the "Click Me" button

Nothing seems to happen, but when you manually move to the set date range, you will see it has been set.

**Comment by flaviendelangle** [comment]
Fixed by #6166

**Comment by Pesya1** [comment]
wow, It work! thanks, @michaelpward.
