### ISSUE TITLE
[DateRangePicker] With single input has a bug when manual typing

### ISSUE THREAD

**Issue by bretbas** [mui/mui-x#4548]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello everyone! I have a DateRangePicker with single input:
```
                            <DateRangePicker
                                value={this.state.period}
                                onChange={(newValue) => this.setState({ period: newValue })}
                                renderInput={(startProps, endProps) => {

                                    const startValue = startProps.inputProps?.value;
                                    const endValue = endProps.inputProps?.value;
                                    delete startProps.inputProps?.value

                                    return (<TextField
                                        {...startProps}
                                        inputProps={startProps.inputProps}
                                        value={`${startValue} - ${endValue}`}/>
                                    )
                                }}
                            />
```

The problem is tha I can't clear symbol by symbol from my TextField. 
I want that my users are able to clear(symbol by symbol) my TextField and typing two dates with keyboard.

### Expected behavior 🤔

When I want to delete first symbol from the end, the cursor carret just set on the end of the start date. And I can delete only start date. The end date of the period is not changed.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Do you have an example where the single input for date range works?

As far as I know, having a single input is not supported for now, because the `onChange` contained in the `inputProps` should handle both the start date and the end date

Here is a codesandbox of the proposed code:

https://codesandbox.io/s/basicdaterangepicker-material-demo-forked-qbldyo?file=/demo.js

**Comment by flaviendelangle** [comment]
I'm closing this one
We are currently developing new components with build-in single input date range edition support.
It should be released sometimes by the end of the year 👍
