### ISSUE TITLE
[pickers] Add classes to `DayPicker` sub-components

### ISSUE THREAD

**Issue by bartvanenter** [mui/mui-x#4552]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The header (or row) that contains the week labels should have a className so that it could be styled.

The weekday labels (['S, M, T, W, T, F, S']) should be customizable just like weekdays are.
Now, it is possible to resize the weekdays, but then they have a different size than week labels. 

Also, the rows containing the weekdays should have a className so that these can be customized. 
Now, it contains has margin between rows which can't be removed.

### Motivation 🔦

File: PickersCalendar.tsx

**1. Add className to PickersCalendarDayHeader**

<img width="1026" alt="weekdayrow" src="https://user-images.githubusercontent.com/2277643/148392818-67aa52f5-b30a-4f03-98a4-dd851c275fc3.png">

Problem:  The header containing the week labels can not be styled. This is because the header can not be targeted.
Solution: Add `.MuiPickersCalendar-dayHeader` className to the PickersCalendarDayHeader component

**2. Add className to PickersCalendarWeekDayLabel**

<img width="1012" alt="weekday" src="https://user-images.githubusercontent.com/2277643/148393284-6e874f72-1555-420c-8454-4309d0a402a7.png">

Problem: The size of the weekday labels can't be changed. This is because the weekday labels can not be targeted.
Solution: Add `.MuiPickersCalendar-weekDayLabel` className to the PickersCalendarWeekDayLabel component

**3. Add className to PickersCalendarWeek**

<img width="1609" alt="dayrow" src="https://user-images.githubusercontent.com/2277643/148393447-c02b0bba-a067-4e69-8c73-0bd9d4c0191a.png">

Problem: The margin between week rows can't be removed. This is because the week rows can not be targeted.
Solution: Add `.MuiPickersCalendar-week` className to the PickersCalendarWeek component

**Comment by MateoAV** [comment]
It would be nice to have the year and month picker for the StaticDatePicker also customizable through a class name.

**Comment by LukasTy** [comment]
Fixed with #6156
