### ISSUE TITLE
[pickers] Add classes to `PickersArrowSwitcher` sub-component and don't wrap month title

### ISSUE THREAD

**Issue by bartvanenter** [mui/mui-x#4553]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The PickersArrowSwitcher should have a className on its wrapper and the arrow buttons so that these can be targeted and styled.

Also, it would be nice if the user can decide how the month name (title) is being rendered, instead of always wrapping it in a Typography component with `subtitle1` as variant.

### Motivation 🔦

<img width="1318" alt="arrow switcher" src="https://user-images.githubusercontent.com/2277643/148384061-d3d215e0-d81c-4498-951c-a8d0c431fb52.png">

File: PickersArrowSwitcher.tsx

**1. Add a className to the PickersArrowSwitcherRoot component**

Problem:  The arrow switcher wrapper container can not be styled. This is because the calendar can not be targeted.
Solution: Add `.MuiPickersArrowSwitcher-root` className to the PickersArrowSwitcherRoot component.

**2. Add a className to the PickersArrowSwitcherButton component**

Problem:  Now, the left and right arrows can be replaced but can't be styled. This is because they can not be targeted.
Solution: Add `.MuiPickersArrowSwitcher-button` className to the PickersArrowSwitcherButton component.

**3. Don't wrap the month (title) in a Typography component**

```
{children ? (
     <Typography variant="subtitle1" component="span">
       {children}
     </Typography>
   ) : (
     <PickersArrowSwitcherSpacer ownerState={ownerState} />
)}
```

Problem:  Now, the children are always wrapped in a Typography component with subtitle1 as a variant.  If the user wants to use a different font size this is not possible.
Solution: Don't wrap the children in a Typography component but let the developer decide what should be rendered.

**Comment by alexfauquette** [comment]
About classes, it is possible to fully customize `<PickersArrowSwitcher />` because you can pass `className` for the root compontnet, and for both buttons, you can set props with `componentsProps.leftArrowButton`. So the required classes could be added as follow.

```jsx
<PickersArrowSwitcher 
	className="MuiPickersArrowSwitcher-root"
	componentsProps={{
		leftArrowButton: {className: "MuiPickersArrowSwitcher-button"},
		rightArrowButton: {className: "MuiPickersArrowSwitcher-button"}
	}}
/>
```

From what I understand, the approach used is to avoid putting classes on internal components. 

For example, the `ClockPicker` reuses the `PickersArrowSwitcher` and sets its root class name to `'MuiClockPicker-arrowSwitcher'`.
https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx#L170:L180

I just don't know how to customize classes name according to the `ownerState`

**Comment by alexfauquette** [comment]
Class names have been added in #4672

The remaining part it the `<Typography />` wrapper

**Comment by alexfauquette** [comment]
@bartvanenter About the last point (the font size) you can modify it with styling based on the wrapper class `MuiPickersArrowSwitcher-root`

```jsx
sx={{
  "& .MuiPickersArrowSwitcher-root span": {
    fontSize: "50px"
  }
}}
```

I do not think removing the <Typography/> would help on this topic

I close the issue, feel free to add a comment if you see something missing
