### ISSUE TITLE
[DateRangePicker] Add classNames to DateRangePickerViewDesktop component

### ISSUE THREAD

**Issue by bartvanenter** [mui/mui-x#4554]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The desktop container component in the date range picker should have a className so that it can be targeted and styled.

### Motivation 🔦

<img width="1622" alt="desktopborder" src="https://user-images.githubusercontent.com/2277643/148369919-962f7ff0-5098-4297-97a2-91423f2734cd.png">

File: DateRangePickerViewDesktop.tsx

**1. Add className to DateRangePickerViewDesktopContainer**

Problem:  The border between the calendars can't be removed. This is because the calendar can not be targeted
Solution: Add `.MuiDateRangePicker-desktopContainer` className to the DateRangePickerViewDesktopContainer component

**2. Add className to DateRangePickerViewDesktopCalendar**

Problem: The size of the calendar can't be changed. This is because the calendar can not be targeted.
Solution: Add `.MuiDateRangePicker-desktopCalendar` className to the DateRangePickerViewDesktopCalendar component

**Comment by LukasTy** [comment]
Fixed with #6096
