### ISSUE TITLE
[CalendarPicker] Custom format in header

### ISSUE THREAD

**Issue by watanabeshuji** [mui/mui-x#4558]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Now, CalendarPicker's header contains 2 blocks ( month block and year block) 
It is natural in English (such as 'December 2021')
In Japanese, it is natural '2021年12月'.

So we want to set format at CalendarPicker header.

**Comment by flaviendelangle** [comment]
@watanabeshuji could you give me an example of a picker with the header format your search to achieve ?
