### ISSUE TITLE
[pickers] Can't customize the height and the width of the views

### ISSUE THREAD

**Issue by angel-langdon** [mui/mui-x#4559]
CSS  attribute to specify height and width

- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

**Comment by gerdadesign** [comment]
From the conversation [here](https://github.com/mui/mui-x/pull/6144#issuecomment-1310107099) about how alignment changes with the week column added:  

I put together [this prototype in figma](https://www.figma.com/file/2z9h8rxbPi7rVqChAx8D54/Date-and-Time-pickers?node-id=431%3A8920&t=MDGTIF9xsfTg0c5S-1). All of these adjust layout with width and accommodate spacing & alignment between displaying month with or without a week number as well as the year. 

Below is a quick screen recording.  @alexfauquette  is something like this possible and would it help solve the consistency between month / year views? 

https://user-images.githubusercontent.com/106991024/204381526-9838da8b-5267-44c5-ab62-b444cfa342fa.mov

**Comment by alexfauquette** [comment]
Yes, I think it's possible and a good direction to follow for customizability. It may require to rework most of the CSS but it worths it :)
