### ISSUE TITLE
[DatePicker] Expose more internal states

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#4560]
I think that we should expose more states of the component to the users:

1. `value`/defaultValue/onChange, this is the selected date by the user, it has to be confirmed by an action in the UI, like clicking an OK button. It can be saved in the database. mui/mui-x#5891
2. `displayedValue`/defaultDisplayedValue/onDisplayedValueChange, this is the currently displayed view of the date picker. It can be used to programmatically display a different month or to switch to a different view (year, month, etc). mui/mui-x#4562, mui/material-ui#23957, https://github.com/mui-org/material-ui-pickers/issues/1436, https://github.com/mui-org/material-ui-pickers/issues/1431
3. `view`/defaultView/onViewChange. This already exists, only need to rename `openTo`, defaultView. It works hand in hand with the `displayedValue` state.
4. `selectedValue`/defaultSelectedValue/onSelectedValueChange, this is the currently selected date(s). Meaning shown as selected in the popup but yet to be confirmed by the user. Once confirmed it turns into `value`. mui/mui-x#4593, mui/material-ui#24179

**Comment by flaviendelangle** [comment]
This issue refers common problems and yet I just discovered it today.
I think grouping them here does not make them visible, I prefer to close it and rely on standalone issues for each set of states.

1. Will be done with the new field / pickers components
3. Has been done, people can now control the views

For 2., I will keep the discussion in #4562, it is marked as ready to do on the board
For 4., I created #6161 to centralize the discussions
