### ISSUE TITLE
[DateRangePicker] Day component not supporting DateRange some props 

### ISSUE THREAD

**Issue by bneigher** [mui/mui-x#4566]
I'm implementing a custom Day UI to live in the DateRange picker.  It looks like this:
<img width="458" alt="Screen Shot 2020-07-15 at 12 29 42 PM" src="https://user-images.githubusercontent.com/4627728/87587431-ece44b80-c696-11ea-9f37-7f4c4adf315c.png">
You can see that in this date range, none of the IN RANGE days are highlighted, which is odd.
I'm seeing some errors in the console:
```
React does not recognize the `isEndOfHighlighting` prop on a DOM element
React does not recognize the `isStartOfHighlighting` prop on a DOM element.
React does not recognize the `isHighlighting` prop on a DOM element.
React does not recognize the `isEndOfPreviewing` prop on a DOM element.
React does not recognize the `isStartOfPreviewing` prop on a DOM element.
React does not recognize the `isPreviewing` prop on a DOM element.
```

Which leads me to believe that some of the date range props are not supported in the Day component.  

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Day component not rendering isHighlighting days in the date range

## Expected Behavior 🤔

Day range should render highlighted zone correctly as it does without specifying the custom `renderDay` method:
<img width="453" alt="Screen Shot 2020-07-15 at 12 35 12 PM" src="https://user-images.githubusercontent.com/4627728/87587949-b3601000-c697-11ea-8648-d3396b8a0845.png">

Here is a simplified version of a `renderDay` with shows issue

```
const renderDayInPicker = (day, dateProps) => {
	return <Day {...dateProps} />
}
```

## Steps to Reproduce 🕹

https://codesandbox.io/s/headless-sun-ig04d

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha.9  |
| React       |    16.13.1    |
| Browser     |     Chrome    |
| TypeScript  |    no     |

**Comment by cherniavskii** [comment]
Still an issue with `@mui/x-date-pickers-pro`: https://codesandbox.io/s/ancient-silence-zmpd5p?file=/package.json

**Comment by m4theushw** [comment]
The component used to render days inside DateRangePicker can now be imported as `DateRangePickerDay`:

```ts
import { DateRangePickerDay } from '@mui/x-date-pickers-pro';
```

CodeSandbox: https://codesandbox.io/s/ancient-silence-zmpd5p?file=/src/demo.jsx

We plan to migrate the API to a slot approach, same as the DataGrid, so I'll close this one in favor of #4466
