### ISSUE TITLE
onEditCellCommit -> onEditCellStop

### ISSUE THREAD

**Issue by jcolvard** [mui/mui-x#4568]
### Order ID 💳

#40821

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is `onCellEditCommit` going away with the new editing API?

If so, what is the replacement. I've been spinning my wheels for a full wasted day, I'm missing something here. Please help.

If I:

```<DataGridPro
...
onCellEditCommit={e => console.log(e.value)}
...
>
```
I get the expected output in the console. I type into an editable field, when that field blurs, the input value is spit out into the console. All good. But I'm trying to add some validation now. I'm hoping to take advantage of the new `newEditingAPi`, and I'm having problems just getting that current/updated value of an editable cell input.

If I: 

```<DataGridPro
...
onCellEditStop={e => console.log(e.value)}
experimentalFeatures={{newEditingApi: true}}
...
>
```
The row parm value sent to the console is always one step behind. In other words, I click into the editable cell, and enter: 'Hello'. On blur, console log reads: ' '. I then click in the cell and enter: 'Hello Again'. Console log reads: 'Hello'. I click in again, enter: 'Hello one more time'. Console log reads: 'Hello Again'.

The onCellEditStop fires before the most recently updated input value is set. Why is that happening. Seem like if that's the expected behavior `onCellEditStop` is not a very useful prop

### Your environment 🌎

<details>
 Using

```
"@mui/x-data-grid-pro": "^5.9.0",
```
</details>

**Comment by m4theushw** [comment]
> Is onCellEditCommit going away with the new editing API?

Yes, the alternative is to use `processRowUpdate`. This new prop works correctly with promises. See https://mui.com/x/react-data-grid/editing/#persistence

> But I'm trying to add some validation now. 

You should use `preProcessEditCellProps` for validation. This callback will always be called with the latest value. See https://mui.com/x/react-data-grid/editing/#validation

**Comment by jcolvard** [comment]
Thanks very much for your quick response. I had been using the `preProcessEditCellProps`, but had not thought to add my state setter into it. Now using the `params.props.value` which is working out well.

And thanks for the heads up on the persitence/processRowUpdate stuff, I'll likely move to that 'auto save' approach in the near future.

Again, I appreciate your quick and helpful response

**Comment by jcolvard** [comment]
Hello again @m4theushw, I'm reopening this to bring awareness to a pretty substantial "jitter" that's happening when typing into an editable field that is using the new `preProcessEditCellProps`.

Particularly if you are typing quickly, there is a hiccup, that triggers a backspace/delete within the input as you type.

For example, if I type "h-e-l-l-o" really quicky, I might end up with "helo" or "hell" or "hllo"

Is the `preProcessEditCellProps` feature stable? Is this a known issue? It's causing a really unfavorable UX in my grid

**Comment by m4theushw** [comment]
Can you reproduce this in https://mui.com/x/react-data-grid/editing/#validation? Are you using a custom edit component? `preProcessEditCellProps` should only be called after the debounce.

> Is the preProcessEditCellProps feature stable?

Yes, it's stable. But we could have missed something if you found this bug.

**Comment by Kanish-PP** [comment]
can anyone help me with this
[https://stackoverflow.com/questions/78892607/react-mui-datagrid-cell-update-trigger](https://stackoverflow.com/questions/78892607/react-mui-datagrid-cell-update-trigger)
