### ISSUE TITLE
Render header value returned to the initial state but the rendered header didn't 

### ISSUE THREAD

**Issue by jaballogian** [mui/mui-x#4571]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Render header value returned to the initial state but the rendered header didn't 

### Expected behavior 🤔

The rendered header should return to the initial state

### Steps to reproduce 🕹

Steps:
1. Run this codesandbox https://codesandbox.io/s/github-mui-bug-custom-filter-data-grid-v46c3o
Here is the initial view
![image](https://user-images.githubusercontent.com/24468466/163947675-cbe52155-8f49-40b0-877f-d637534cdb4a.png)
As we could see from the codesandbox console here that the columns don't have any `renderHeader` prop here.
![image](https://user-images.githubusercontent.com/24468466/163949955-b28e4c48-6ddb-443b-8726-a35d55aea1ed.png)

2. Click the filter icon (in the top right corner) to change the render header (from the default text header into an input component)
Here is the screenshot
![image](https://user-images.githubusercontent.com/24468466/163948042-4f3efc5a-3930-4119-989d-1ccd1a976511.png)
Now we could see that some columns have the `renderHeader` prop from the console here
![image](https://user-images.githubusercontent.com/24468466/163950129-ee5cc1fa-f8d9-476e-8058-0751f190d20b.png)

3. Click again the filter icon to change back the render header to the initial state
Here is the screenshot
![image](https://user-images.githubusercontent.com/24468466/163948208-17cb2a0c-466e-47b4-b0da-39373c207d9d.png)
As we can see that the header didn't return to the initial state (the default text header)
If we look at the console here, the columns don't have any `renderHeader` prop
![image](https://user-images.githubusercontent.com/24468466/163950253-faea17d4-0b98-443f-bf06-14d87d74beca.png)

So, the rendered header didn't return to the initial state but the value did

This didn't happen if we use Material UI Data Grid v5.5.1 here https://codesandbox.io/s/github-mui-custom-data-grid-fxqytz

### Context 🔦

I'm creating a custom filter by adding an input component inside the header (using render header prop).
The custom filter feature could be toggled on/off (using the filter icon).
![image](https://user-images.githubusercontent.com/24468466/163948042-4f3efc5a-3930-4119-989d-1ccd1a976511.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

OS: Windows 11
Browser: Chrome 100

### Order ID 💳 (optional)

29446

**Comment by cherniavskii** [comment]
I can't explain this, but as long as you don't use `delete` operator to get rid of `renderHeader` property on the column, it works just fine.

Here's same example using **5.8.0** without `delete` operator: https://codesandbox.io/s/github-mui-custom-data-grid-forked-blzlw7?file=/src/App.jsx:1159-1214

**Comment by cherniavskii** [comment]
@jaballogian 
Does this solve the issue for you?

**Comment by jaballogian** [comment]
Thank you for the answers @cherniavskii 
Let me see the answers first
I will edit this comment later
