### ISSUE TITLE
[pickers] `@mui/x-date-pickers-pro` have the `README.md` from `@mui/x-date-pickers`

### ISSUE THREAD

**Issue by rajzik** [mui/mui-x#4577]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://user-images.githubusercontent.com/10364836/164147890-fd8fec75-442b-49a7-8846-e2a811ca7481.png)

### Expected behavior 🤔

It would be great to have up to date readme and mention requirements of license for this package. 

### Steps to reproduce 🕹

Steps:

1. Go to [npm link](https://www.npmjs.com/package/@mui/x-date-pickers-pro)

**Comment by flaviendelangle** [comment]
Good catch !
I forgot to modify the pro one :facepalm:
