### ISSUE TITLE
[Date Picker] Translations in the calendar

### ISSUE THREAD

**Issue by efattal** [mui/mui-x#4579]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

As it can be seen in this localized example of the calendar, https://mui.com/components/date-picker/#localization, the tooltips displayed on the navigation arrows (Previous month / Next month) aren't not translated as we could expect when we set the locale. 

### Expected behavior 🤔

The translations should respect the locale or it should be possible to provide them.

### Steps to reproduce 🕹

Steps:

1. Go the example https://mui.com/components/date-picker/#localization
2. Select DE (german)
3. Hover the arrows
4. The tooltip is in english instead of german

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicate #4500 

Let's keep a single issue :+1:
