### ISSUE TITLE
Unexpected error when DatePicker is used from @mui/lab

### ISSUE THREAD

**Issue by rajzik** [mui/mui-x#4583]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When 
```tsx
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
```
is used with combination with `import { Datepicker } from '@mui/lab';` this causes error 
`Can not find utils in context. It looks like you forgot to wrap your component in LocalizationProvider, or pass dateAdapter prop directly.`.

### Expected behavior 🤔

It would be great to have compatibility with lab exports.

### Steps to reproduce 🕹

https://codesandbox.io/s/data-grid-community-forked-hf283h?file=/src/App.tsx

Steps:

1. `import { LocalizationProvider } from "@mui/x-date-pickers";`
2. Initialize `LocalizationProvider`
3. Use `Datepicker` from `@mui/lab`

### Context 🔦

I was trying to migrate our repo to `@mui/x-date-pickers` but it failed when used from `@mui/lab`.
Also, it was hard to debug without any indication where the problem is.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22598
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 12.66 GB / 31.91 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 21.2.4 - C:\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.35.3.
  Virtualization:
    Docker: 20.10.12 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0
  IDEs:
    VSCode: 1.66.2 - C:\Users\silha\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.1.32328.378 (Visual Studio Community 2022)
  Languages:
    Bash: 5.0.17 - C:\Windows\system32\bash.EXE
    Python: 3.10.2
    Python3: 3.9.12
  Browsers:
    Edge: Spartan (44.22598.100.0), Chromium (100.0.1185.44)
    Internet Explorer: 11.0.22598.1
  Monorepos:
    Yarn Workspaces: 1.22.18
    Lerna: 3.22.1
```
</details>

**Comment by cherniavskii** [comment]
You should only import either from `@mui/x-date-pickers` or `@mui/lab`.
