### ISSUE TITLE
CSV export with server-side data

### ISSUE THREAD

**Issue by PraveenPeri** [mui/mui-x#4586]
### Order ID 💳

33625

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

My requirement is to export all possible rows from the datagrid where each page is being loaded from the server. Any suggestions on how to get that working?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 4.14 Amazon Linux 2
  Binaries:
    Node: 14.15.4 - /usr/bin/node
    Yarn: Not Found
    npm: 7.10.0 - /usr/bin/npm
  Browsers:
    Edge: 100.0.1185.36
```
</details>

**Comment by cherniavskii** [comment]
Hey @PraveenPeri 
On the data grid side you can just add custom button to the toolbar that will fetch all data as csv file:

```tsx
function CustomToolbar() {
  function fetchCSVDataFromServer() {
    // ...
  }

  return (
    <GridToolbarContainer>
      <Button onClick={fetchCSVDataFromServer}>Export CSV</Button>
    </GridToolbarContainer>
  );
}

// ...

<DataGrid
  components={{
    Toolbar: CustomToolbar
  }}
/>
```

In case you need CSV export to work with sorting and filtering - you can use controlled [sorting](https://mui.com/x/react-data-grid/sorting/#controlled-sort-model) and [filtering](https://mui.com/x/react-data-grid/filtering/#controlled-filters) models and use them when fetching CSV data from server.

**Comment by PraveenPeri** [comment]
@cherniavskii So, a custom method implementation. That was my immediate thought but wanted to run it by you before getting on with it. Thanks!
