### ISSUE TITLE
[DateTimePicker] Uncaught RangeError when Date Time Picker focus changes to a newly opened Dialog

### ISSUE THREAD

**Issue by timmckague** [mui/mui-x#4595]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

"Uncaught RangeError: Maximum call stack size exceeded. " is thrown in the chrome devtools console when TimePicker focus changes to the newly opened Dialog.

### Expected behavior 🤔

I would expect no "Uncaught RangeError"

### Steps to reproduce 🕹

codesandbox: https://codesandbox.io/s/laughing-tharp-k47gd

Steps:

in Chrome...

1. Open the datetimepicker to the timepicker view
2. Click the "click me" button next to the datetimepicker field
3. Notice in the browser devtools console that a "RangeError" is thrown. (You'll have to open the devtools, the codesandbox console doesn't show this error for some reason)

### Your environment 🌎

Chrome

**Comment by flaviendelangle** [comment]
I will close this one in favor of #4653
