### ISSUE TITLE
[DateTimePicker] Cancel and ok button don't work

### ISSUE THREAD

**Issue by ZeroCool-85** [mui/mui-x#4599]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

At the moment everytime you choose something in the picker it changed directly the date in the input.

### Expected behavior 🤔

If cancel- and okay-button appear, it should just change the date by click on the okay-button and discard changes by click on the cancel-button.

### Steps to reproduce 🕹

Steps:

1. Open [MobileDateTimePicker](https://mui.com/components/date-time-picker/#responsiveness)
1. Click on some date fields in the open picker
1. Check the value of the input
1. Click cancel
1. Original date is not restored

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Related to #4408 

Currently, the behavior when using a picker with an input is indeed to update the input on every step, even if the `Cancel` / `OK` buttons are visible.

I am switching from `bug` to `discussion` because the correct behavior is not clear to me.

**Comment by flaviendelangle** [comment]
Closing in favor of https://github.com/mui/mui-x/issues/6161
