### ISSUE TITLE
Max Date breaking when using Luxon

### ISSUE THREAD

**Issue by astreiten** [mui/mui-x#4611]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi, I'm trying to use the React Date Picker component providing it with the Luxon adapter. The thing is that when the picker has a max date, it breaks when clicking on the calendar. It doesn't happen if I use for example the date-fns Adapter.
Here you can see my code:
https://codesandbox.io/s/basicdatepicker-material-demo-forked-dn4b0u?file=/demo.tsx

I'm using the last version of all the dependencies.
Is this a bug?

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/basicdatepicker-material-demo-forked-dn4b0u?file=/demo.tsx
2. Click on the calendar
3. Check that an error is being thrown.

### Context 🔦

I'm trying to set a maxDate in a picker that uses Luxon as utils provider.

### Your environment 🌎

This is happening both in my local and in online sandboxes.

**Comment by alexfauquette** [comment]
You should be consistent with the date object you use. If you want to use `luxon`, dates should be `DateTime` object from luxon


```js
import { DateTime } from 'luxon'

...

maxDate={DateTime.now()}
```

https://codesandbox.io/s/basicdatepicker-material-demo-forked-x7cg7k

**Comment by astreiten** [comment]
Thanks! Yes, I think so, because in the previous versions the props were always a Date object, no matter which Utils library you used. 
Thank you very much!

**Comment by flaviendelangle** [comment]
Duplicates #4474, closing this one
