### ISSUE TITLE
How to pass custom handlers to the renderCell/renderHeader inside GridColDef ?

### ISSUE THREAD

**Issue by mtshv** [mui/mui-x#4616]
### Order ID 💳

36792

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Let's say I have a columns array defined outside of the Datagrid component. And I have a custom DropdownMenu component that I want to render as a custom action button in the last column.

Question: how do I correctly pass the needed handlers to it as props? Initially, I thought that adding these custom props to the `componentsProps={{ cell: {customProp: () => {}} }}` will make it available inside the renderCell params. But I was wrong. 
```
const  columns = [
    {
      headerName: "Title",
      description: "Template",
      field: "title",
    },
    {
      headerName: "Description",
      field: "description",
      flex: 7.5,
    },
    {
      field: "customActions",
      renderCell: params => {
        const { row } = params;
        return  <DropdownMenu
            item={params.row}
            onEdit={handleOnEdit}  // <===== How do I pass these handlers?
            onDelete={handleOnDelete} //  <===== How do I pass  these handlers?
          />;
      },
    },
  ];
 ```
 
I could not find any examples of how handlers, custom data objects, etc are passed to the render functions inside the columns array (if it is declared outside the Datagrid).

Could you please share suggestions on how you would recommend achieving what I want?

----
Another issue I am struggling with is showing the rows count in the first column header:
```
[
    {
      headerName: "Title",
      field: "title",
      renderHeader: params => {
        const headerTitle = params.colDef.field;
        const rowsCount = apiRef?.current?.getRowsCount(); <====== How do I get access to this
        return (
          <div className="MuiDataGrid-columnHeaderTitle">
            {`${headerTitle} (${rowsCount})`}
          </div>
        );
      },
......
]
```
headerParams don't include `apiRef` param as cellParams. Is there any recommended way of getting access to the rowsCount when rendering header for a specific column?

**Comment by cherniavskii** [comment]
Hey @mtshv 
> I could not find any examples of how handlers, custom data objects, etc are passed to the render functions inside the columns array (if it is declared outside the Datagrid).

Currently, you can use a factory pattern for columns: https://codesandbox.io/s/basiccolumnsgrid-material-demo-forked-8utd7x?file=/demo.tsx

> headerParams don't include apiRef param as cellParams. Is there any recommended way of getting access to the rowsCount when rendering header for a specific column?

You can use the same approach as above, passing rowCount to the columns factory deriving rowCount from rows:
https://codesandbox.io/s/basiccolumnsgrid-material-demo-forked-qs0swj?file=/demo.tsx

Would that work for you?

**Comment by mtshv** [comment]
@cherniavskii  hank you, sir, this will work for me 🙇
