### ISSUE TITLE
[data grid] Ensure GridColDef's field is type-safe

### ISSUE THREAD

**Issue by kenberkeley** [mui/mui-x#4623]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://github.com/mui/mui-x/blob/aa630accb0e8c3351d69a4fd72585789dfca30c9/packages/grid/x-data-grid/src/models/colDef/gridColDef.ts#L35-L42

The `field` above does not have any restrictions, see:

<img src="https://user-images.githubusercontent.com/13287948/164892562-de40d3ea-9bb5-47d8-a9fe-2eaa74cbab7e.png">

### Examples 🌈

<img src="https://user-images.githubusercontent.com/13287948/164892625-bb0f194b-6bb6-4fe8-85cc-8e54bb3d7739.png">

### Motivation 🔦

Better type guard.

**Comment by flaviendelangle** [comment]
The field does not have to be a key of the row
It only have to be one when used without `valueGetter`

I know React Table differentiate the typing of columns with and without function getters. But from my experience, it made the typing a lot more complicated, and I spent hours struggling to use it when creating custom plugins because of it.

So for the DataGrid, I preferred to not type more strictly the field. It's a trade-off, I understand that it can be frustrating, but I thing it is preferable, for now at least.

**Comment by kenberkeley** [comment]
Thanks @flaviendelangle 

I might have to rely on [patch-package](https://www.npmjs.com/package/patch-package) to enforce type-safe in my own project then.

**Comment by flaviendelangle** [comment]
If you come with a clean-enough solution on your side, feel free to post it here to help other developers with similar needs and to help us if we want to support it one day :+1:

**Comment by barrettg** [comment]
It may be a little more work, but we use the [ts-nameof](https://github.com/dsherret/ts-nameof) package to help keep our field names in line with our types.  For example:
```
  {
      field: nameof<InvoiceRevisionLineItem>((i) => i.employeeName),
      headerName: 'Employee',
      width: 125,
      sortable: true,
  },
```
In this example `InvoiceRevisionLineItem` is my type and `employeeName` is the field inside that type. `nameof` simply returns a string, but keeps you from making spelling mistake or would throw an error if the type changed.

**Comment by ArmandRedgate** [comment]
As an end-user, you can do this too

```ts
type TypeSafeColDef<T> = GridColDef & { field: keyof T };

const columns: TypeSafeColDef<MyType>[] = [
    {
        field: "Name",
    },
    {
        field: "Size",
        headerName: "Size used (MB)"
    }
];
```

**Comment by dangnhdev** [comment]
@ArmandRedgate Thank you, I added 2 more types:

```typescript
export type TypeSafeColDef<T> = GridColDef & { field: keyof T };
export type TypeSafeColVisibility<T> = GridColumnVisibilityModel & { [K in keyof Partial<T>]: boolean };
export type TypeSafeSortModel<T> = Array<GridSortItem & {'field': keyof T}>
```

**Comment by zzundalek** [comment]
@ArmandRedgate 
Thank you so much! 👍 I've expanded the definition to handle fields with valueGetters as well.
```ts
type TypeSafeColDef<T, ValueGetterFields> = GridColDef & { field: keyof T | ValueGetterFields }
```

Use it simply with:
```ts
const columns: TypeSafeColDef<UserDetail, never>[] = [
   { field: 'name', headerName: 'name'},
]
const columnsWithValueGetters: TypeSafeColDef<UserDetail, 'services' | 'addresses'>[] = [
   { field: 'name', headerName: 'Name'},
   { field: 'services', headerName: 'Services', valueGetter: getValueServiceName },
   { field: 'addresses', headerName: 'Addresses', valueGetter: getValueAddresses },
]
```

**Comment by baharalidurrani** [comment]
```ts
export type TypeSafeColDef<R extends GridValidRowModel = any, F extends string | void = void> = GridColDef<R> & {
  field: keyof R | 'action' | F;
};
```

This allows me to use type safe field names, custom fields as well safety for the `row` prop of
`getActions: ({ id, row }) => []`

Example:
```ts
const columns: TypeSafeColDef<TUser, 'custom1' | 'custom2' | 'fullName'>[] = [
  { field: 'firstName', headerName: 'First Name' },
  { field: 'lastName', headerName: 'Last Name' },
  {
    field: 'fullName',
    headerName: 'Full Name',
    valueGetter: (_, row) => row.firstName + ' ' + row.lastName,
  },
  {
    field: 'action',
    headerName: 'Action',
    type: 'actions',
    getActions: ({ id, row }) => [......], // JSX Actions Here
  },
];
```

PS
I've hardcoded `action` which can be removed and used dynamically using the `F` parameter.
