### ISSUE TITLE
[DatePicker] StaticDatePicker does not auto scroll to selected year when toggled to year view

### ISSUE THREAD

**Issue by ch4rlesyeo** [mui/mui-x#4642]
### Current behavior 😯

StaticDatePicker's year view does not auto scroll to selected year, have to scroll all the way down to find my selected date.

### Expected behavior 🤔

StaticDatePicker should auto scroll to selected year, similar like our [default DatePicker](https://mui.com/components/date-picker/#basic-usage) when toggled to year view.

### Steps to reproduce 🕹

Please refer the official StaticDatePicker demo: https://mui.com/components/date-picker/#static-mode

### Your environment 🌎

@mui/lab - 5.0.0-alpha.54

**Comment by flaviendelangle** [comment]
Duplicates #4601, I close this one to keep a single discussion :+1:
