### ISSUE TITLE
[DatePicker] Picker resets to previous value when opening

### ISSUE THREAD

**Issue by NormanZyq** [mui/mui-x#4643]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

Case 1.
If I delete the content of a DatePicker manually, and then click the calendar icon two times, the earlier date will pop up again.
![iShot2022-04-23_19 38 04](https://user-images.githubusercontent.com/32858941/164893080-7a2c9613-758d-4223-8aa5-4e7f1eb9b8b3.gif)

Case 2.
If I change the content and do the same thing as mentioned above, strange behavior also exists.
![iShot2022-04-23_19 45 53](https://user-images.githubusercontent.com/32858941/164893213-102b9bb0-e473-40e0-9ef6-4a8f6f06640f.gif)

I don't know whether it's designed like this, or it's an unexpected behavior, or I used it in a wrong way. Hope there can be a support for me, thx.

Code sample is here: [MUI-DatePicker](https://mui.com/zh/x/react-date-pickers/getting-started/)

### Expected behavior 🤔

I think after I click the icon two times, the content of the picker should remain empty if I have deleted it, or it should keep the value if I changed it manually.

### Steps to reproduce 🕹

Steps: Please view the gif above

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi, 
Thanks for the reproduction case

This bug will be fixed by #4408
