### ISSUE TITLE
[data grid] Looking for a callback fired on the end of resize

### ISSUE THREAD

**Issue by jesperenglund92** [mui/mui-x#4646]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello! I would like to keep track of column sizes in my redux state and as far as I could tell, I found no other straightforward way of doing this than using "onColumnResize". But as it fires every time there's a new width value, it results in a rather unresponsive experience. So I would like to request the ability to use a prop that fires off a function "onColumnResizeEnd", or something to that effect. Alternatively, I'd be just as happy with a good workaround for this problem. Can anyone help me out here? Thanks in advance.

Similar to, though not quite the same as: https://github.com/mui/mui-x/issues/4278

### Motivation 🔦

Keeping track of the column sizes is helpful from a usability perspective, when the user is switching back and forth between different tables on the page but being able to maintain the same column sizes. We also need to column sizes in our feature to let the user create custom reports as well as sharing and exporting them. Although, admittedly, the latter use cases don't require keeping track "on the fly".

**Comment by flaviendelangle** [comment]
You can use `onColumnWidthChange` which is fired after a resizing ends but also if you resize imperatively a column.
