### ISSUE TITLE
[static pickers] Handle `disable` and `readOnly` on all static pickers

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#4650]
This is a follow up of #4594

What is tested with both `readOnly` and `disabled` on [pickers](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx#L88:L107) is that clicking on the calendar does not open the views.

For now, only calendars apply the `readOnly` with `if (readOnly) { return; }` at the beginning of `handleDaySelect`, `onMonthSelect` and `handleYearSelection`.

You can experiment with them in the following demo

https://codesandbox.io/s/material-ui-issue-forked-0v1z9d?file=/src/demo.js

Noticed inconsistencies

- `StaticTimePicker` are still editable with `disabled` or `readOnly`
- `StaticDateRangePicker` 
	- with `disabled` allows to see next month, but not the previous one
	- start/end dates in the headers are focusable but do nothing

**Comment by flaviendelangle** [comment]
I think it duplicates https://github.com/mui/mui-x/issues/4400
