### ISSUE TITLE
getRowSpacing + theme.spacing

### ISSUE THREAD

**Issue by cliedeman** [mui/mui-x#4652]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Attempting to use `theme.spacing` breaks the grid in a weird way

```tsx
  const getRowSpacing = React.useCallback((params: GridRowSpacingParams) => {
    return {
      top: params.isFirstVisible ? 0 : theme.spacing(1),
      bottom: params.isLastVisible ? 0 : theme.spacing(1)
    };
  }, []);
```

Only 3 rows are displayed

### Expected behavior 🤔

Either document or adjust the types about what can be returned from the function

### Steps to reproduce 🕹

https://codesandbox.io/s/rowmargingrid-material-demo-forked-nohw11?file=/demo.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

39468

**Comment by m4theushw** [comment]
The return value of `getRowSpacing` should be an object that satisfies the following interface:

```ts
interface GridRowSpacing {
  top?: number;
  bottom?: number;
}
```

`theme.spacing(1)` returns the string `8px`. TypeScript warns about the incorrect return type. You can fix it by doing:

```tsx
const getRowSpacing = React.useCallback((params: GridRowSpacingParams) => {
  return {
    top: params.isFirstVisible ? 0 : 1 * 8,
    bottom: params.isLastVisible ? 0 : 1 * 8
  };
}, []);
```

If you use a different layout unit, instead of 8px, then you need to pass it though a variable.

**Comment by cliedeman** [comment]
@m4theushw my mistake. I was sure the type was 

export interface GridRowSpacing {
    top?: number | string;
    bottom?: number | string;
}
