### ISSUE TITLE
[DateTimePicker] Allow to pass props to the `TrapFocus` with `TrapFocusProps`

### ISSUE THREAD

**Issue by Dodie324** [mui/mui-x#4653]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently using the following versions:
```
  "@mui/lab": "^5.0.0-alpha.53",
  "@mui/material": "^5.0.1",
 ```
 I have a form rendered inside of `Dialog` that consists of a couple `TextField` inputs (a mix of 'text' and 'select' types) and a `DesktopDateTimePicker` that's rendered inside of a `LocalizationProvider`.
 
If a user opens the date time picker, navigates between different months using the left and right arrows, and then clicks into a select input field while the date time picker is open a `RangeError: Maximum call stack size exceeded.` error from `Unstable_TrapFocus.js` gets thrown.
 
While this doesn't seem to break the UI functionality it is causing an unhandled error in our Sentry logs and kicks-off a PagerDuty alert.

Seems like it's relevant to https://github.com/mui/material-ui-pickers/issues/1852
 
 

### Expected behavior 🤔

I'd expect a call stack error not to exist.

### Steps to reproduce 🕹

Steps:

1. Open `DesktopDateTimePicker` from within `Dialog`
2. Navigate between months using left and right arrows
3. While date time picker is open click into a select input field
4. Notice the error in the console

### Context 🔦

<img width="462" alt="Screen Shot 2022-04-25 at 16 03 00" src="https://user-images.githubusercontent.com/9405172/165165864-e031606e-bb26-47d3-93d1-f87331d671d2.png">

### Your environment 🌎

```
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@mui/lab": "^5.0.0-alpha.53",
    "@mui/material": "^5.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
```

Tested in Chrome Version 100.0.4896.127 (Official Build) (arm64)

**Comment by Dodie324** [comment]
@m4theushw I hope this example is useful: https://codesandbox.io/s/data-grid-community-forked-8inrq5?file=/src/App.tsx

Steps to reproduce in example:
1. Open up the console once the page loads
2. Toggle through the different months using the left and right arrow in the date picker
3. Click into the select field and the out of the select field
4. Notice the error in the console: `Uncaught RangeError: Maximum call stack size exceeded.`

Here's a GIF reproducing the bug in case the above doesn't work. 
![maximumStackError](https://user-images.githubusercontent.com/9405172/166248205-e9d55deb-ee45-4e14-b7c5-6634c42797f0.gif)

**Comment by luan-hubner** [comment]
I'm with the same problem, my MUI components is inside a generic Dialog component.

![Capturar](https://user-images.githubusercontent.com/63028077/166396431-4c7f9798-6d1e-42a4-9400-1f543f6f9e94.PNG)

 I put my modal body inside the generic Dialog that I created, like this: 

![image](https://user-images.githubusercontent.com/63028077/166396497-7042e105-14fe-480b-b7f2-d5888daaa362.png)

But, when I open the modal and try click or make something in the components the console cry. I tried remove this generic Dialog and put the modal body inside of a normal Dialog like this:

![image](https://user-images.githubusercontent.com/63028077/166396664-e2d5872a-4c73-4bd4-b02f-cc1d975d948c.png)

Cool, everything works, I don't know why and what's happening, but, my issue was fixed.

I'm only sharing my solution, try remove the MUI components out of Dialog component or something, I hope that works to you.

**Comment by m4theushw** [comment]
This happens because both `DesktopDateTimePicker` and the `TextField` have internally a `TrapFocus` and both are trying to put focus on different elements. When the input is clicked, the calendar is supposed to be closed and the focus return to the calendar icon button. In the other hand, clicking on the input should focus the first item. Since both actions happen in parallel and the `TrapFocus` has a logic to enfore focus everytime it's lost it leads to this infinite loop. I see two alternatives:

1. Disable the focus enforcement logic in `DesktopDateTimePicker`

  ```tsx
  <DesktopDateTimePicker TrapFocusProps={{ disableEnforceFocus: true }} />
  ```

  This alternatives comes with a trade-off. `TrapFocusProps` is not supported in the types but works. There's an opportunity for us here to improve the types and include this prop.

2. Use `disableEnforceFocus` in the text input:

  ```tsx
  <TextField
    SelectProps={{
      MenuProps: {
        disableEnforceFocus: true
      }
    }}
  />
  ```

Here's the updated CodeSandbox: https://codesandbox.io/s/data-grid-community-forked-i6jo67?file=/src/App.tsx

**Comment by Dodie324** [comment]
Thanks for looking into this and helping with a fix @m4theushw!
