### ISSUE TITLE
Typing of custom component to render in GridActionsCellItem 

### ISSUE THREAD

**Issue by rafael-zilberman** [mui/mui-x#4654]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Why using version `5.6.1` of `mui-x/data-grid` we were using the `component` prop of the underlying `ButtonBase` component in order to integrate with `react-router` as follows:
```js
<GridActionsCellItem
                        component={RouterLink}
                        to={`/notes`}
                        icon={<NoteIcon/>}
                        label="Notes"
                    />,
```

While Updating to versions older then `5.7.0` we are experiencing typing error stating that `GridActionsCellItem` doesn't have this prop enymore.

I followed the history of this component [here](https://github.com/mui/mui-x/commits/master/packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx) but it seems that nothin relevant has been changed.

I found [this](https://github.com/mui/mui-x/commit/a55478c44364734517f7517072cbba50a9360131) commit containing bundling changes and did manged to find out that the difference between the latest version and the last version that has this feature working is type called `GridActionsCellItem` that has been added to the typing file in addition to `GridActionsCellItemProps`.

**Comment by m4theushw** [comment]
@Janpot is right. The `xxxProps` interfaces of `IconButton` and `MenuItem` don't include `component`. This prop is only available when using the component itself, not when extending it (what we do). The following diff should be sufficient for now:

```diff
diff --git a/packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx b/packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx
index a54b786da..1e6096c64 100644
--- a/packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx
+++ b/packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx
@@ -7,6 +7,7 @@ import ListItemIcon from '@mui/material/ListItemIcon';
 export type GridActionsCellItemProps = {
   label: string;
   icon?: React.ReactElement;
+  component?: React.ElementType;
 } & (
   | ({ showInMenu?: false; icon: React.ReactElement } & IconButtonProps)
   | ({ showInMenu: true } & MenuItemProps)
```

**Comment by dfliess** [comment]
hi! has this been added ?

**Comment by rafael-zilberman** [comment]
> ```diff
> GridActionsCellItem
> ```

Still not fixed.

A nasty workaround for now:
```typescript
import {GridActionsCellItem, GridActionsCellItemProps} from "@mui/x-data-grid";
import React, {RefAttributes} from "react";
import {Link as RouterLink} from "react-router-dom";

type GridLinkActionProps = {to: string} & GridActionsCellItemProps & RefAttributes<HTMLButtonElement>;

const GridLinkAction = ({to, ...props}: GridLinkActionProps) => {
    return (<RouterLink to={to}>
        <GridActionsCellItem {...props} />
    </RouterLink>);
};

export default GridLinkAction;
```

**Comment by baharalidurrani** [comment]
@romgrk `to` is still not defined after providing `component={RouterLink}` although it's working fine if I supress the Typescript check.
Code Snippet:
```tsx
import { Link } from 'react-router';
///////////////
  {
    headerClassName: 'data-grid-header',
    field: 'action',
    headerName: 'Actions',
    type: 'actions',
    getActions: ({ id }) => [
      <GridActionsCellItem showInMenu label="View" component={Link} to={`../view/${id}`} />,
      <GridActionsCellItem showInMenu label="Edit" component={Link} to={`../edit/${id}`} />,
    ],
  }
```
Here's my dependencies list:
```json
    "@emotion/cache": "^11.14.0",
    "@emotion/react": "^11.14.0",
    "@emotion/styled": "^11.14.1",
    "@fontsource/inter": "^5.2.6",
    "@mui/icons-material": "^7.3.1",
    "@mui/material": "^7.3.1",
    "@mui/x-data-grid": "^8.10.1",
    "@mui/x-date-pickers": "^8.10.0",
    "react": "^19.1.1",
    "react-dom": "^19.1.1",
    "react-router": "^7.8.0"
```

<img width="1338" height="613" alt="Image" src="https://github.com/user-attachments/assets/05f69803-49df-4bf0-94fd-6d7880e2fd74" />

**Comment by romgrk** [comment]
The typings are correct, if you want to pass material props you should wrap them in `material={{ component: Link, to: ... }}`. It might work at runtime for some components, but it's not intended to. The `GridActionsCellItem` is not a material-ui component anymore, it goes through a layer of indirection to allow being replaced.

**Comment by antonioValenti-enuan** [comment]
> The typings are correct, if you want to pass material props you should wrap them in `material={{ component: Link, to: ... }}`. It might work at runtime for some components, but it's not intended to. The `GridActionsCellItem` is not a material-ui component anymore, it goes through a layer of indirection to allow being replaced.

I don't think so... It throws error on both `component` and `material` props solutions.

```
material={{
  component: Link,
  to: "/foobar"
}}
```

```
Object literal may only specify known properties, and 'to' does not exist in type 'Partial<IconButtonProps> | Partial<MenuItemProps>'.ts(2353)
augmentation.d.ts(66, 5): The expected type comes from property 'material' which is declared here on type '(IntrinsicAttributes & GridActionsCellItemCommonProps & { showInMenu?: false | undefined; icon: ReactElement<any, string | JSXElementConstructor<...>>; label: string; } & Omit<...> & Omit<...> & RefAttributes<...>) | (IntrinsicAttributes & ... 5 more ... & RefAttributes<...>)'
```
