### ISSUE TITLE
[DataGrid] DataGrid component requires too much props

### ISSUE THREAD

**Issue by Einere** [mui/mui-x#4661]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

<img width="645" alt="스크린샷 2022-04-26 오후 8 33 01" src="https://user-images.githubusercontent.com/8300010/165291075-8ebcb0dc-ef7a-45fd-ae61-2fca8773fcdb.png">

in IDE, DataGrid show warnings that `Element DataGrid doesn't have required attribute <some_props>`...
actually, it is not affect to running app, but it make me annoying.
so i dive into DataGrid types, and found that `DataGridPropsWithDefaultValues` has that props with required.
maybe that type triggers warnings. it need to fix to optional props.

### Expected behavior 🤔

don't warning to optional props.

### Steps to reproduce 🕹

Steps:

1. install `@mui/x-data-grid`
2. code `DataGrid`
3. IDE showing amazing warnings.

### Context 🔦

my package version is below.

```
"@mui/icons-material": "^5.6.2",
"@mui/lab": "^5.0.0-alpha.78",
"@mui/material": "^5.6.2",
"@mui/x-data-grid": "^5.9.0",
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Not Found
    Firefox: 87.0
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.77 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/lab: ^5.0.0-alpha.78 => 5.0.0-alpha.78 
    @mui/material: ^5.6.2 => 5.6.2 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/system:  5.6.2 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid: ^5.9.0 => 5.9.0 
    @mui/x-date-pickers:  5.0.0-alpha.0 
    @types/react: ^18.0.5 => 18.0.5 
    react: ^18.0.0 => 18.0.0 
    react-dom: ^18.0.0 => 18.0.0 
    typescript: ^4.6.3 => 4.6.3 
```
</details>

i'm using 
- chrome 100.0.4896.127 (x86_64)
- WebStorm 2021.2.4

**Comment by cherniavskii** [comment]
Hey @Einere 
All those props are optional.
Note `Partial<DataGridPropsWithDefaultValues>` in `DataGridProps`:
https://github.com/mui/mui-x/blob/ebb0e3b1a4d940b02ca20abd61ade86fce9b6e94/packages/grid/x-data-grid/src/models/props/DataGridProps.ts#L52-L53

Same with propTypes, for example `autoHeight` is not required:
https://github.com/mui/mui-x/blob/ebb0e3b1a4d940b02ca20abd61ade86fce9b6e94/packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx#L68

What IDE are you using? Is it configured to work with TypeScript?

Here's how it looks in VS Code:
<img width="529" alt="Screenshot 2022-04-26 at 13 53 33" src="https://user-images.githubusercontent.com/13808724/165295018-fbc30c9f-cecc-4a33-9416-a195f891986b.png">
And in CodeSandbox:
<img width="528" alt="Screenshot 2022-04-26 at 13 58 06" src="https://user-images.githubusercontent.com/13808724/165295065-593363b9-4161-44f7-9a8f-194432580137.png">

**Comment by flaviendelangle** [comment]
I noticed the same thing on Webstorm
Nothing breaking but I wonder why the IDEA thinks it's required when both the proptypes and typescript says otherwise

**Comment by Einere** [comment]
@cherniavskii 
YEP. I found the latest error report from youtrack. [https://youtrack.jetbrains.com/issue/WEB-50309](https://youtrack.jetbrains.com/issue/WEB-50309)
I recognized the issue is not related with MUI.
JetBrains team just saying "it will fix soon. instead, recommend using EAP version."... 😓
I think there is no action can do... so i will close this issue.
thanks a lot.
