### ISSUE TITLE
[DatePicker] Feed in date in input filed, Select popup without selecting a date click outside. Inputted date is wiped out

### ISSUE THREAD

**Issue by sameswar** [mui/mui-x#4677]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

MUI DatePicker,
Issue 1)  Feed in date in input field, Select popup without selecting a date click outside. Inputed date is wiped out.
Issue 2) Select the date from popup picker. Edit the date using input field. Open the picker again,(You can see the curretly inputted date getting displayed). Click outside the picker to make it close. Now the previously picker selected date come up in the datepicker.

### Expected behavior 🤔

We should see the last edited date in the field. 

### Steps to reproduce 🕹

Steps:

1. Select the date from popup picker
2.  Edit the date using keyboard in input box tpo a different date
3. Open the picker again, and click outside the picker to close it.
4. Edited date is gone, Old selected date get dispaled.

### Context 🔦

It creates inconsistencey  in the functionality. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
This broken behavior will be fixed in #4408 :+1:
