### ISSUE TITLE
[data grid] Focus is not reset when the rows changes due to a change in row grouping model

### ISSUE THREAD

**Issue by jakubchmura** [mui/mui-x#4678]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When we configure a grouping model and expand the generated row and then delete this grouping model, clicking on the column header results in an error:

`Uncaught Error: No row with id #auto-generated-row-company/20th Century Fox-director/James Cameron found`

In the local environment it also throws warnings like this:

`MUI: You are calling getValue("__row_group_by_columns_group__") but the column "__row_group_by_columns_group__" is not defined.
Instead, you can access the data from "params.row.__row_group_by_columns_group__".`

### Expected behavior 🤔

We should be able to freely change the grouping model and use the table without errors

### Steps to reproduce 🕹

I will not publish my example because the problem appears also in the documentation.

Steps:

1. Go to the example in docs: [Row Grouping example](https://mui.com/x/react-data-grid/row-grouping/#RowGroupingCustomGroupingColDefCallback) 
2. Select `Group by company and director` tab
3. Expand auto-generated row `by James Cameron`
4. Select `Group by company` tab
5. Click on any column header
6. Then `Uncaught Error: No row with id #auto-generated-row...` error appear.

### Context 🔦

I have a custom row grouping component where I drag and drop the column header name to input which generates a new grouping model, so when I'm changing the grouping model and expanding an auto-generated row and then trying to set a new model then an error appears. 

### Your environment 🌎

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.2 
    Yarn: 1.22.17 
    npm: 8.1.2 
  Browsers:
    Chrome
  npmPackages:
    @emotion/react: ^11.8.2 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.75
    @mui/icons-material: ^5.5.1 => 5.6.0
    @mui/lab: ^5.0.0-alpha.75 => 5.0.0-alpha.76
    @mui/material: ^5.5.2 => 5.6.0
    @mui/private-theming:  5.6.0
    @mui/styled-engine:  5.6.0
    @mui/system:  5.6.0
    @mui/types:  7.1.3
    @mui/utils:  5.6.0
    @mui/x-data-grid: ^5.8.0 => 5.8.0
    @mui/x-data-grid-generator: ^5.8.0 => 5.8.0
    @mui/x-data-grid-pro:  5.8.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @mui/x-license-pro:  5.7.0
    @types/react:  17.0.43
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript:  4.6.3

**Comment by flaviendelangle** [comment]
Good catch !

The problem comes from the focus plugins which tries to un-focus a cell that does not exist anymore.
We have a check to remove focus when the rows changes but only when `props.rows` changes, not when the change is indirect.

**Comment by jakubchmura** [comment]
Do you have an idea how I can prevent errors temporarily? Or when are you planning to release a fix? Deadline in a moment ... you understand :).

**Comment by flaviendelangle** [comment]
The fix should be released in a few day
But you should be able to do the same fix I did on your component, see [this example](https://codesandbox.io/s/data-grid-pro-forked-y1igd9?file=/src/App.tsx)
