### ISSUE TITLE
I have an issue with the datagrid resetting on hover on Datagrid pro ^5.2.2

### ISSUE THREAD

**Issue by siddharthpandatessell** [mui/mui-x#4686]
### Order ID 💳

#35627

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have customized our datagrid so that we have have a custom column that displays an icon menu on hovering over a row. On clicking the menu, we show the context menu for deleting, modifying etc options.

The issue with the hover listener is it resets the width and order of columns when we hover over any row. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
   System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.18 - ~/Documents/Tessell/tessell-ui/node_modules/.bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Not Found
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.4.1 => 11.9.0 
    @emotion/styled: ^11.3.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.76 
    @mui/icons-material: ^5.2.5 => 5.6.1 
    @mui/lab: ^5.0.0-alpha.61 => 5.0.0-alpha.77 
    @mui/material: ^5.2.5 => 5.6.1 
    @mui/private-theming:  5.6.1 
    @mui/styled-engine:  5.6.1 
    @mui/styles: ^5.2.3 => 5.6.1 
    @mui/system:  5.6.1 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid: ^5.2.1 => 5.9.0 
    @mui/x-data-grid-pro: ^5.2.2 => 5.9.0 
    @mui/x-date-pickers:  5.0.0-alpha.0 
    @mui/x-license-pro:  5.9.0 
    @types/react:  18.0.5 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components:  5.3.5 

Browser: Chrome Version 100.0.4896.127 (Official Build) (arm64) 
```
</details>

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by siddharthpandatessell** [comment]
Sorry about not providing a small sample. Here's a small example of how we customize our datagrid
https://codesandbox.io/s/data-grid-community-forked-gdqwzt

**Comment by siddharthpandatessell** [comment]
As you will see, on changing width or order of columns, when we try to hover over any row, all our settings for the table ie order of appearance of columns, width of columns etc is reset.

**Comment by m4theushw** [comment]
You need to memoize the columns, otherwise they are reset to the given width on each rerender. If you add `rowHover` as dependency of `React.memo` it will still not work, so one solution is to use CSS. I updated the CodeSandbox with a CSS-based alternative: https://codesandbox.io/s/data-grid-community-forked-5zo7cw?file=/src/App.tsx

**Comment by siddharthpandatessell** [comment]
The column width and order are still getting reset on hover. I want the datagrid to maintain it's selected width and column order.

**Comment by m4theushw** [comment]
Inside `src/Datagrid.js` you concat the columns and generates a new array. You also need to memoize it there. I updated the CodeSandbox with this last task.
