### ISSUE TITLE
[DataGrid] Highlight a specific word in a column

### ISSUE THREAD

**Issue by minhnhat10** [mui/mui-x#4690]
Hello everyone, I'm working on a project and I want to highlight a specific word in a column like the image below. I have searched the resolution for this problem but I still can not find out the way to do it. I appreciate for any suggestion.
 
![Screen Shot 2022-04-28 at 11 17 34 PM](https://user-images.githubusercontent.com/33271256/165801438-5aa78422-9169-446e-aaf3-f271a63e04b5.png)

**Comment by m4theushw** [comment]
You can create a custom cell renderer where it highlights the desired word in the cell. See https://mui.com/x/react-data-grid/columns/#render-cell

**Comment by yairEO** [comment]
You can easily do it with https://github.com/yairEO/react-css-highlight

I use it myself for my DataGrid components at my workplace
