### ISSUE TITLE
[DateTimePicker] `minDate` prop on throws error when using `@date-io/moment`

### ISSUE THREAD

**Issue by aadlc** [mui/mui-x#4706]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The `DateTimePicker `  component loads but, but as soon click on the calendar icon, the page the following error: 
TypeError
date.clone is not a function

This error does not happens if you are using the `minDate`  prop and ` @date-io/date-fns` in your `LocalizationProvider`.

### Expected behavior 🤔

The `DateTimePicker` loads, user click on calendar icon, dates are disabled until Dec 19, 2021, the user selects an available date from the calendar drop-down.

### Steps to reproduce 🕹

Steps:
With ` @date-io/moment`
1. Visit this working example [here](https://codesandbox.io/s/responsivedatetimepickers-material-demo-forked-4eft3?file=/demo.js)
2. Click on the calendar icon. (page will fail at this point)

With ` @date-io/moment`
1. Visit this working example [here](https://codesandbox.io/s/responsivedatetimepickers-material-demo-forked-4eft3?file=/demo.js)
2. Uncomment lines 4 and 14
3. Comment lines 3 and 13
2. Click on the calendar icon.
3. Pick and available date from the calendar drop-down

### Context 🔦

I am trying to disable days in the past via `minDate` prop.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Using Chrome
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #4474

I am closing this one to keep a centralized discussion
We are discussing on it to support or not non parsed dates on `minDate` and `maxDate`, but you can easily parse it on your side for now :+1:
