### ISSUE TITLE
[pickers] date picker broken on chrome 101

### ISSUE THREAD

**Issue by BC-M** [mui/mui-x#4710]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On Chrome 101, the date picker seems to be broken. Only a few days of the month are offered for selection. 

![Bildschirmfoto 2022-04-30 um 12 22 57](https://user-images.githubusercontent.com/40334865/166101735-f557bafc-bce9-4943-84e1-1b4f31accbda.png)

### Expected behavior 🤔

Same as in the other browsers (on Safari and Firefox the date picker works as expected).

### Steps to reproduce 🕹

Steps:

1. Open https://mui.com/x/react-date-pickers/date-picker/ on Chrome 101
2. Open picker on "Basic usage"-Demo

### Your environment 🌎

- macOS 12.3.1
- Chrome 101.0.4951.41
- mui-x date pickers v5.0.0-alpha.2

**Comment by BC-M** [comment]
I had a [browser plugin](https://mybrowseraddon.com/change-timezone.html) active that changed the time zone. The MUI calendar didn't seem to like that. 

The problem has therefore resolved itself. 🤦

**Comment by alexfauquette** [comment]
That's a really specific problem. Not sure we should/can solve it
