### ISSUE TITLE
Customize Header cell

### ISSUE THREAD

**Issue by Vladislav747** [mui/mui-x#4724]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello! I try to customize header cell https://prnt.sc/S6LKI2N_ZWzs 

I haven't found anything about it https://mui.com/x/react-data-grid/components/ 

Is there way to customize it? ( For example add my own icons in header cell)

**Comment by socramm9** [comment]
https://mui.com/x/react-data-grid/style/#styling-column-headers



> For example add my own icons in header cel

https://mui.com/x/react-data-grid/columns/#render-header
