### ISSUE TITLE
[DatePicker] Disable mask

### ISSUE THREAD

**Issue by ErnestBrandi** [mui/mui-x#4732]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi, I think there is a lack of documentation about custom masks & inputFormat in Pickers type components.

For instance if I want to use to following format : `"[Day : ] dddd DD MMMM [, time : ] HH:mm"`, mask is irrelevant because I do not expect users to respect any kind of formatting while typing. Which means I expect them to use the picker exclusively.

But it seems like there is no way to disable the mask placeholder when the input value is empty. So if I click the picker's input the first time I see the mask rendering in the input, which seems buggy. 
So is there currently a way to achieve this ?

**Comment by flaviendelangle** [comment]
@alexfauquette since you worked on the mask I let you have a look at this one

**Comment by alexfauquette** [comment]
Yes, this customization is feasible:

You can add `disableMaskedInput` to avoid any check from the input, and override `inputProps` to remove the placeholder and set the input as a `readOnly`

I made a codesandoxwith the customization: https://codesandbox.io/s/basicdatepicker-material-demo-forked-b5qq5b?file=/demo.tsx

But what you try to do looks like a Mobile component:
https://codesandbox.io/s/responsivedatetimepickers-material-demo-forked-421h01?file=/demo.tsx

@ErnestBrandi is the mobile component what you were looking for or is there a use-case I'm missing?

**Comment by flaviendelangle** [comment]
Closing this one from lack of feedback
