### ISSUE TITLE
[DatePicker] does not show weekday text in non-English languages

### ISSUE THREAD

**Issue by DanielManning** [mui/mui-x#4733]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Non-English languages only show the day and the month in the header text of the DatePicker.

### Expected behavior 🤔

If the browser's language is set to English, the date displayed in DatePicker (e.g. StaticDatePicker) is `${dayOfWeek}, ${month} ${day}` (e.g. "Mon, Jan 10").  When switching to another language, I expect the header text to also include the day of the week, following the current language's convention.

Example in English (with day of week):
<img width="1171" alt="Screen Shot 2022-01-10 at 3 01 38 PM" src="https://user-images.githubusercontent.com/5528748/148835508-de050984-b4a7-40a1-8b8e-2d9645099335.png">

Example in French (without day of week):
<img width="1174" alt="Screen Shot 2022-01-10 at 3 00 18 PM" src="https://user-images.githubusercontent.com/5528748/148835604-db35f785-4fe5-4683-b4d3-794830d457c6.png">
Expected text: "lun. 10 janv."

Example in `@material-ui/core` v4.9.14 and `@material-ui/pickers` v3.2.10, with a customization of `MomentUtils.getDatePickerHeaderText` (https://material-ui-pickers.dev/guides/formats) that changes format based on current locale:

<img width="266" alt="Screen Shot 2022-01-10 at 3 45 08 PM" src="https://user-images.githubusercontent.com/5528748/148837277-bbeb0155-a0a2-4b53-9b2e-d733f901be0a.png">

### Steps to reproduce 🕹

Interactive example component: https://codesandbox.io/s/busy-mirzakhani-ez9ix?file=/src/Demo.tsx

Steps:

1. Set language to English.
2. Render a DatePicker wrapped in a LocalizationProvider using `dateAdapter={AdapterMoment}`
3. The header text includes the day of the week.
4. Set language to French in the sandbox (uncomment line 2: `import "moment/locale/fr"`)
5. The header text only includes the day followed by the month in French.

### Context 🔦

If English includes the day of the week, we expect other languages to also include the day of the week.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Not Found
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @emotion/react: 11.7.0 => 11.7.0
    @emotion/styled: 11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.64
    @mui/lab: 5.0.0-alpha.64 => 5.0.0-alpha.64
    @mui/material: 5.2.7 => 5.2.7
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.6
    @mui/styles: 5.2.3 => 5.2.3
    @mui/system:  5.2.8
    @mui/types:  7.1.0
    @mui/utils: 5.2.3 => 5.2.3
    @types/react:  16.9.23
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
```
</details>

**Comment by alexfauquette** [comment]
It seems to be the expected behavior

https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DatePicker/DatePickerToolbar.tsx#L79-L85
```js
// Little localization hack (Google is doing the same for android native pickers):
// For english localization it is convenient to include weekday into the date "Mon, Jun 1".
// For other locales using strings like "June 1", without weekday.
return /en/.test(utils.getCurrentLocaleCode())
  ? utils.format(parsedValue, 'normalDateWithWeekday')
  : utils.format(parsedValue, 'normalDate');
```

But if you prefer another behavior, you can override the toolbar format with `toolbarFormat` prop as follow:
https://codesandbox.io/s/gallant-wozniak-jsj75l?file=/src/Demo.tsx:728-754

**Comment by LukasTy** [comment]
Bumping this issue to understand if it is still a problem.
@DanielManning  In the code, we are still using the same "hack" to have weekday only in the English locale:
https://github.com/mui/mui-x/blob/60d09134e89ec33289b3b973d44234529aa24a94/packages/x-date-pickers/src/internals/utils/date-utils.ts#L184-L191

Is the option to manually override the format work well enough or should we reconsider the approach? 🤔
