### ISSUE TITLE
[pickers] Use UTC instead of current TimeZone

### ISSUE THREAD

**Issue by aFarkas** [mui/mui-x#4734]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Current version of the DateRange picker also includes the time part. 

### Expected behavior 🤔

Due to the fact that it is a date range picker I would assume that it generates dates without using a time + timezone part. 
```js
new Date('2222-11-11') === new Date('2222-11-11T00:00::Z') !== new Date('2222-11-11Tany-thing-else')
```

### Steps to reproduce 🕹

Steps:

1. open https://codesandbox.io/s/date-and-time-pickers-forked-5pqmui?file=/src/App.tsx
2. Compare native datepicker with date-range picker output in console.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

Could you give us a reproduction case of what you exactly mean ?
[This template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) could be a good starting point

**Comment by aFarkas** [comment]
@flaviendelangle 
Thanks for fixing my title.

Here you find a testcase:
https://codesandbox.io/s/date-and-time-pickers-forked-5pqmui?file=/src/App.tsx

**Comment by jonnylink** [comment]
Our team is also finding this behavior very unsatisfactory. Our company does business in ET, so having the date & datetime picker UI using local which is then converted and returned in UTC is quite frustrating. I see the use case for it doing this, but in our case (and I imagine we are not the only ones) it just creates headaches. 

The ask here for our team would be:
a. make timezones optional
or 
b. allow us to explicitly set the timezone of the component (vs what the browser says)

**Comment by flaviendelangle** [comment]
I started working on the UTC support a few weeks ago
For now we have an implementation for [`dayjs`](https://next.mui.com/x/react-date-pickers/adapters-locale/#with-dayjs-2) and `moment` (released this week).

For date-fns, I'll have a check how I can implement it correctly :+1: 

I you could take a look at the `dayjs` behavior and tell me if it matches your need.
I lack feedbacks to confirm that I'm going in the right direction.

**Comment by flaviendelangle** [comment]
Closing this issue in favor of https://github.com/mui/mui-x/issues/8484
