### ISSUE TITLE
[data grid] `apiRef.current.exportState()` does't aways return the entire grid state

### ISSUE THREAD

**Issue by tielushko** [mui/mui-x#4738]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. When pressing "Show All" button in grid toolbar panel, the apiRef.current.exportState() function does not preserve the columnVisibilityModelProperty.
2. After reinserting that exported state into initialState prop, the column visibility preferences will be screwed up as the columnVisibilityModel not set to {} initially.

### Expected behavior 🤔

1. When all columns are shown, I would expect apiRef.current.exportState() to export columnVisibilityModel as {} for proper restore.

### Steps to reproduce 🕹

Steps:

1.https://codesandbox.io/s/initialstate-material-demo-forked-xpeixk?file=/grid.tsx
2. Open column panel.
3. Press Hide All button.
4. Press Show All button
5. Notice the console log of the exported object that's missing the columnVisibilityModel property entirely.

### Context 🔦

I was trying to send the exportedState to the DB for user preferences to be saved and restored later.
When this occurs, we lose the columnVisibilityModel as {}. I have the workaround now, but wanted to report this since I think this might be an undesired behavior.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

31986

**Comment by DanailH** [comment]
Hi, @tielushko thanks for raising this. The way the `apiRef.current.exportState()` works is that when it's called it returns the current state of the grid, or rather the part of the state that differs from the default grid state. If we return an empty object when all the columns are visible we would also have to return empty objects for other parts of the state that don't have a value.
I'm looping in @flaviendelangle since he knows the ins and outs of the stare export.

**Comment by flaviendelangle** [comment]
This topics keeps coming back
I'm wondering if we should add a param `exportState(mode: 'diff' | 'full')` to let the user decide if he wants a smart diff or just the full portable state.

**Comment by tielushko** [comment]
@DanailH @flaviendelangle , thank you guys for reaching back out to me. Just I suppose currently not returning anything causes problems when circling the saved state back where it requires the model value to be set to {} to operate properly. 

I like the idea between the different exportState params, but again, in my workaround, I just insert the {} under columns.columnVisibilityModel if the initialState didn't have anything there, and it works fine.

**Comment by flaviendelangle** [comment]
I think we have 2 topics

If you don't set `initialState.columnVisibilityModel` or `props.columnVisibilityModel`, then the grid uses the legacy `column.hide` property which is not portable. It is an unfortunate limitation until v6 to avoid breaking changes.

**Comment by m4theushw** [comment]
I propose to move this discussion to #4620. #4779 has the same issue.

**Comment by tielushko** [comment]
Feel free to close out this issue. I will monitor the original #4620 issue instead! Sorry for missing that one and creating an extra issue. Thank you for looking!

**Comment by flaviendelangle** [comment]
For me it was a duplicated of #4620 and can be closed
