### ISSUE TITLE
[DateRangePicker] Values entered using TextField disappear (or reset) when calendar is closed

### ISSUE THREAD

**Issue by MarcEspiard** [mui/mui-x#4741]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I try to manually input a start / end date using the textfields, the values are selected in the calendar as I type (expected).   
When the calendar closes these values are reset (either completely cleared or reset to the last value that was clicked on the calendar).  
You can see in the CodeSandbox provided that an onChange triggers with empty values when the calendar closes, even though values were selected with the textfields (and set in state).

This issue is present in current live docs: [https://mui.com/x/react-date-pickers/date-range-picker/#different-number-of-months](https://mui.com/x/react-date-pickers/date-range-picker/#different-number-of-months)

See: 
[https://codesandbox.io/s/calendarsdaterangepicker-material-demo-forked-gbm3p1?file=/demo.tsx](https://codesandbox.io/s/calendarsdaterangepicker-material-demo-forked-gbm3p1?file=/demo.tsx)
![chrome_JxHbhgo6xq](https://user-images.githubusercontent.com/32894646/166323947-71d530bb-9950-42e1-ac9d-62cca7f86d51.gif)

### Expected behavior 🤔

The values are correctly saved in state no matter if I click on calendar or if I input them manually using the textfields.

### Steps to reproduce 🕹

Steps:

1. Input date using TextField input in DateRangePicker component
2. Close calendar by clicking anywhere on the page

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 4.40 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Managers:
    Apt: 2.0.6 - /usr/bin/apt
    Composer: 2.1.9 - /usr/local/bin/composer
    pip3: 20.0.2 - /usr/bin/pip3
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.4.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Servers:
    Apache: 2.4.53 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.7 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.58.2 - /mnt/c/Program Files/Microsoft VS Code/bin/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Perl: 5.30.0 - /usr/bin/perl
    PHP: 8.0.17 - /usr/bin/php
    Python3: 3.8.10 - /usr/bin/python3
  Databases:
    MySQL: 5.7.35 - /usr/bin/mysql
```
</details>
Browser: Chrome 100.0.4896.127 on Windows 10 (up to date)

### Order ID 💳 (optional)

#30097

**Comment by flaviendelangle** [comment]
Fixed by #4408 (see https://codesandbox.io/s/date-and-time-pickers-forked-wfm482?file=/src/App.tsx)

The fix should be released in a few days
