### ISSUE TITLE
[TimePicker] TimePicker with Luxon throws `NaN` when editing via input box

### ISSUE THREAD

**Issue by abs25** [mui/mui-x#4751]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using the TimePicker component with Luxon. When there is an initial time set for the component's value, it's not able to be changed by typing in the input box. It just blows up with a NaN error.

This doesn't appear to happen when the initial value is `null`, only when there is an actual time given.

Using the actual clock UI to change the times works as expected, I'm only seeing this when editing the input directly.

### Expected behavior 🤔

Editing a date shouldn't cause the component to blow up, just validation to fail.

### Steps to reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/luxon-time-picker-example-gp5yjh?file=/src/App.tsx
2. Try to erase a character from the input box using the backspace key on your keyboard
3. Observe NaN error

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 3.10.10 - ~/code/edustaff/node_modules/.bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 99.0.1
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.79 
    @mui/lab: ^5.0.0-alpha.80 => 5.0.0-alpha.80 
    @mui/material: ^5.6.4 => 5.6.4 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/styles: ^5.6.2 => 5.6.2 
    @mui/system:  5.6.4 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.2 
    @types/react: ^17.0.39 => 17.0.39 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    styled-components:  5.3.0 
    typescript: ^4.5.5 => 4.5.5 
```
</details>

**Comment by flaviendelangle** [comment]
Bug introduced in #4398
When the new value is not a valid date, we should not try to merge it with the last valid date.

**Comment by LukasPieger1** [comment]
It seems the DatePicker Component with the LuxonAdapter has a very similar issue. Whenever I remove parts of a date in the input-box I get an Invalid "NaN" luxon-date. It doesn't throw an error right away as described in this issue...so I'm not sure if this is inteded behavior. However I am using typescript and the onChange-value reports to be of type `DateTime<true> | null`. If the behavior is inteded this should be `DateTime | null` instead

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by LukasPieger1** [comment]
Here is a working [example](https://codesandbox.io/p/sandbox/date-and-time-pickers-forked-pg4wxl?file=%2Fsrc%2FApp.tsx%3A12%2C23)

To test this just delete part of the date directly from the inputbox.

**Comment by LukasTy** [comment]
I'm not sure we can do much here, because the component typing comes from the provided value and not the adapter. 🤔 
Correct me if I'm wrong @flaviendelangle.
How I see it, the only improvement we can make is to update documentation to show the proper usage of controlling a value with Luxon adapter in TS environment, which would be:
```diff
- const [value, setValue] = React.useState<DateTime | null>(DateTime.now());
+ const [value, setValue] = React.useState<DateTime<true> | DateTime<false> | null>(DateTime.now());
```
