### ISSUE TITLE
[pickers] AdapterLuxon doesn't provide placeholder text (hh:mm / dd.mm.yy) in Date- or TimePickers

### ISSUE THREAD

**Issue by SO-Eng** [mui/mui-x#4755]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I wrapped TimePicker and also DatePicker in my app with LocalizationProvider.
Both gets the prop: dateAdapter={AdapterLuxon} and locale={string} ("en-US" / "de-DE" ...).

The am/pm behaviour works as expected, but I never get any placeholder text.
I switched from moment library (with AdapterMoment in LocalizationProvider) to Luxon DateTime now and the placeholder disappears.
Will say, with Moment it worked well and also as we can see with DateFNS it work's also like on your documentation:
[LocalizationProvider](https://mui.com/components/time-picker/#localization)

### Expected behavior 🤔

Placeholder textes shoul also appear with AdapterLuxon in all Date- / Timepickers.

### Steps to reproduce 🕹

Showing 2 DateTimes:

upper one with AdapterLuxon,
lower one with AdapterDateFns

[CodeSandbox](https://codesandbox.io/s/localizationprovider-issue-6yepj?file=/src/App.tsx)

### Context 🔦

This problem is a UX requirement in order to quickly and easily convey to the user what needs to be entered into the field. Additionally with the info in which format.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
About the placehoder, it does not seems to be on our side. We rely on `getFormatHelperText` from date-io, and it seems luxon does not allow such a function to work; That's why the placeholder is always empty.

https://github.com/dmtrKovalenko/date-io/blob/2b5f6e17d63cc493e64d066bf1ae5fdcd36580dc/packages/luxon/src/luxon-utils.ts#L98-L101
```js
public getFormatHelperText = (format: string) => {
    // Unfortunately there is no way for luxon to retrieve readable formats from localized format
    return "";
  };
```

I see two solutions:
- You know how to get this information from luxon, please share it such that we can to a PR on date-io
- You set a placeholder for your application as follows `<TimePicker inputProps={{placeholder: 'hh:mm'}} />`

**Comment by SO-Eng** [comment]
Dear @alexfauquette ,

of course the second (hardcoded) solution is definitely not the best case an a cloud based app that is used world wide.
Means, it could also be 'hh:mm a|pm' etc.

So I prefer the first 'solution' and open a ticket at luxon.

Thank you for investigating here!!

**Comment by SO-Eng** [comment]
Issue at Luxon Datetime here:
[Luxon-Issue#1197](https://github.com/moment/luxon/issues/1197)

**Comment by flaviendelangle** [comment]
I gave more detailed on the Luxon issue and will implement it in `@date-io/luxon` (and Luxon with their help if we do need modification there)

**Comment by flaviendelangle** [comment]
It should be supported by the 1st version of `@date-io` based on Luxon 3.
Keeping an eye on it

**Comment by slowWriting** [comment]
@flaviendelangle I have quickly tested the change. It seems that changing prop adapterLocale does not influence the keyboard mask. 
Also FYI in your example date pickers version is still 5.0.4
