### ISSUE TITLE
one error used in Storybook

### ISSUE THREAD

**Issue by Acatworthloving** [mui/mui-x#4757]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://user-images.githubusercontent.com/31841169/166665933-f461e091-f12b-47ee-995d-7af399b3f01b.png)

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

![image](https://user-images.githubusercontent.com/31841169/166666001-18f52577-781f-4e3c-9ec7-b1df51ee5886.png)

**Comment by flaviendelangle** [comment]
Your problem looks like what is described [https://stackoverflow.com/questions/69710576/using-material-ui-component-in-storybook](here) and [https://github.com/mui/material-ui/issues/24282](here)
The fix should look something like:

```tsx
import React from 'react'
import {ThemeProvider} from '@material-ui/core'
import {StylesProvider} from "@material-ui/core";


import theme from '../src/theme'

export const decorators = [
  (Story) => (
    <StylesProvider injectFirst>
      <ThemeProvider theme={theme}>
        <Story />
      </ThemeProvider>
    </StylesProvider >
  ),
]
```

**Comment by Acatworthloving** [comment]
Problem solved, thank you
