### ISSUE TITLE
[data grid] Integration with classname Generator

### ISSUE THREAD

**Issue by MatthewMcP** [mui/mui-x#4767]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We're creating a micro-frontend project with some use of your Datagrid. Due to the micro-frontend nature we would like to use ClassNameGenerator ([ClassName generator](https://mui.com/material-ui/experimental-api/classname-generator/)) however this has issues with the styling within the Datagrid. Is this in the roadmap?

**Comment by siriwatknp** [comment]
@alexfauquette @MatthewMcP Please take a look at this sandbox https://codesandbox.io/s/basiccolumnsgrid-material-demo-forked-m8ns1j?file=/index.tsx.

The catch here is to create an initializer file and import it at the root index.js.

**Comment by MatthewMcP** [comment]
Yes can confirm this fixed my issue. Thank you

**Comment by alexfauquette** [comment]
@siriwatknp Do you want to keep this issue open until you update the doc or can we close it?

**Comment by siriwatknp** [comment]
> @siriwatknp Do you want to keep this issue open until you update the doc or can we close it?

Let's keep this open.
