### ISSUE TITLE
Allow 2 or more DatePicker to be controlled by one state

### ISSUE THREAD

**Issue by jove0610** [mui/mui-x#4773]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Say, you have two (or more) DatePicker and you want it to be controlled only by one state. See example below on problems my encounter implementing this...

### Examples 🌈

We can just use the [responsive](https://mui.com/x/react-date-pickers/date-picker/#responsiveness) example in the docs since it has 3 DatePicker controlled by one state.

1. Change the value of the mobile date picker (ex. May 1, 2022)
2. Change the value of the desktop date picker to a different date than before (ex. May 2, 2022)
3. Change the value of the responsive date picker to a different date than before (ex. May 3, 2022)
 
Now they should all have the same date which is the last date you picked (ex. May 3, 2022).

4. Click the mobile date picker but do not select any date. Just cancel it by clicking escape, cancel button, or clicking outside.
5. Now the date in all date picker changed to the previously selected date of mobile (ex. May 1, 2022)

You can do the same to the other 2 date picker, just open the date picker, don't select date, then close the date picker. The value will change to the previously selected one for that particular date picker..

### Motivation 🔦

I wanted to create a 2 date filter for my form. One is an onChange and the other is onSubmit found on a modal.

**Comment by flaviendelangle** [comment]
Thanks for your detailed report 
This bug has been fixed by #4408 which will be released in a few days
