### ISSUE TITLE
[data grid] Resizing column to a smaller size triggers sorting with the on mouse up event

### ISSUE THREAD

**Issue by DianaSellarova** [mui/mui-x#4777]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I noticed that resizing the grid column e.g. moving the separator to the left and making the column smaller, causes an unwanted trigger for sorting the column. When the resizing ends with the mouse over the column header (to the left of the divider), the mouse up event triggers the sorting as well.

https://user-images.githubusercontent.com/22642474/166916828-f60803ba-8781-4f63-a36e-9b9430d86014.mov

### Expected behavior 🤔

When making a column of Data Grid smaller, the mouse-up event happening after releasing the column divider should not trigger the sorting of the column, only the resize should happen.

### Steps to reproduce 🕹

I double-checked this behavior, it occurs also on the demo page of the grid https://mui.com/x/react-data-grid/columns/#resizing and on the sandbox page

Steps:

1. Click on the resize divider to the right of the column header
2. Make the column smaller by dragging the divider to the left
3. Finish the dragging above the column header
4. Sort gets triggered with the mouse up event

### Context 🔦

Attempting to resize grid column to a smaller size

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browser:
    Chrome: 101.0.4951.54
   
```
</details>

### Order ID 💳 (optional)

#29913

**Comment by mtshv** [comment]
I second this issue. When I drop one column header onto another to reorder columns, this triggers sorting.

**Comment by alexfauquette** [comment]
The problem is that the resize handle is inside the column header. So when you do a `mouseDown` on it, drag and then a `mouseUp` on the column header it is interpreted as a click on the column header.

To solve this problem, the `handleColumnHeaderClick` function should have access to the information "is the column resized" to prevent the sorting


@mtshv I do not manage to reproduce it with drag & drop column

**Comment by evanroane** [comment]
I'm also seeing this issue.


<details>
    <summary> `npx @mui/envinfo` </summary>

```
$ npx @mui/envinfo
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Edge: 103.0.1264.37
    Firefox: 101.0.1
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.67 
    @mui/material: ^5.4.0 => 5.4.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine-sc: npm:@mui/styled-engine-sc@latest => 5.6.1 
    @mui/system:  5.4.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid-pro: ^5.5.1 => 5.5.1 
    @mui/x-license-pro:  5.5.1 
    @types/react: 16.9.45 => 16.9.45 
    react: ^17 => 17.0.2 
    react-dom: ^17 => 17.0.2 
    styled-components: ^5.3.0 => 5.3.3 
    typescript: ^3.9.7 => 3.9.10 
```
</details>
Order ID #37236

**Comment by martin-mael** [comment]
Experiencing the same problem at the moment. Users have not filed issues yet, but we're encountered this behavior in staging and prod environments.

`npx @mui/envinfo` :
```
System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-alpha.128
    @mui/core-downloads-tracker:  5.12.3
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/lab: ^5.0.0-alpha.129 => 5.0.0-alpha.129
    @mui/material: ^5.12.3 => 5.12.3
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.12.3
    @mui/system: ^5.13.1 => 5.13.1
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid:  6.4.0
    @mui/x-data-grid-pro: ^6.4.0 => 6.4.0
    @mui/x-date-pickers: ^6.2.1 => 6.5.0
    @mui/x-date-pickers-pro: ^6.5.0 => 6.5.0
    @mui/x-license-pro:  6.0.4
    @types/react: ^18.0.38 => 18.0.38
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^5.3.10 => 5.3.10
    typescript: ^5.0.4 => 5.0.4
    ```

**Comment by alexfauquette** [comment]
@romgrk I'm just pinging you such that someone in the data grid team gets the notification
