### ISSUE TITLE
[data grid] restoreState doesn't always have same result when passing an exportedState

### ISSUE THREAD

**Issue by MWhiteAFS** [mui/mui-x#4779]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using exportState then passing the returned value to the restoreState function, the resulting DataGrid isn't always the same as when exported.

Currently when you export the state of a table that has all columns visible the ColumnVisibilityModel is not defined as an attribute of the exported State. When performing a restoreState with the returned export, it does not update the visible columns because ColumnVisibilityModel isn't defined unless you manually add it as an empty object in the state structure. 

**All visible**
![image](https://user-images.githubusercontent.com/97128660/166933804-02f68fda-fb66-424a-871a-5e8e9c6de24b.png)

**Columns Hidden**
![image](https://user-images.githubusercontent.com/97128660/166933996-81aab425-fc45-4197-9e2a-20e906a9d352.png)

**All selected but remain hidden**
![image](https://user-images.githubusercontent.com/97128660/166934088-a12cc7e3-7c75-48f6-8158-e296802495ea.png)

### Expected behavior 🤔

When restoring to a state that has all columns visible, it should always restore all columns as visible.
The ColumnVisibilityModel should always be returned when the state is exported, even as an empty object, or the restoreState should interpret an undefined ColumnVisibilityModel to mean all columns are visible.

### Steps to reproduce 🕹

Steps: This can be performed on the website at [Restore The State With Apiref]( https://mui.com/x/react-data-grid/state/#restore-the-state-with-apiref
 )

1. exportState of a DataGrid with all columns visible
2. Hide some columns on the table
3. use restoreState and pass in the previously exported state
4. columns remain hidden

### Context 🔦

I'm attempting to do a multi-view table

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

 System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.9.0 
    @emotion/styled: ^11.6.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.78 
    @mui/icons-material: ^5.3.1 => 5.6.2 
    @mui/lab: ^5.0.0-alpha.67 => 5.0.0-alpha.79 
    @mui/material: ^5.4.0 => 5.6.3 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/styles: ^5.3.0 => 5.6.2 
    @mui/system:  5.6.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid: ^5.10.0 => 5.10.0 
    @mui/x-data-grid-pro: ^5.10.0 => 5.10.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @mui/x-license-pro:  5.10.0
    @types/react: ^17.0.38 => 17.0.38
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.1 => 17.0.2
    styled-components: ^5.2.1 => 5.3.3
    typescript: ^4.1.3 => 4.5.4
</details>

### Order ID 💳 (optional)

#39752

**Comment by m4theushw** [comment]
Similar to #4620
