### ISSUE TITLE
[question] Why does the advanced tree say its released, I cant find it anywhere

### ISSUE THREAD

**Issue by markwindsorr** [mui/mui-x#4782]
### Order ID 💳

#43011

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

[question] Why does the advanced tree say its released, I cant find it anywhere

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by mbrookes** [comment]
@markwindsorr Are you referring to this?

![image](https://user-images.githubusercontent.com/357702/167273148-b90f6857-2178-4622-8c4a-b42838168f6a.png)

If so, I agree. I've raised it in the past. @oliviertassinari's view at the time was that released as alpha is enough to consider it released, but it's a bit misleading. It has also come up recently about the DateRangePicker. 

@danilo-leal Should we add the clock icon to those, or something else to indicate that they're in progress?

**Comment by markwindsorr** [comment]
> @markwindsorr Are you referring to this?
> 
> ![image](https://user-images.githubusercontent.com/357702/167273148-b90f6857-2178-4622-8c4a-b42838168f6a.png)
> 
> If so, I agree. I've raised it in the past. It has also come up recently about the DateRangePicker.
> 
> @danilo-leal Should we add the clock icon to those, or something else to indicate that they're in progress?

yup thats correct

**Comment by danilo-leal** [comment]
> It will probably be moved to our repository

Is it uncertain that Tree View will be part of MUI X? Just double-checking since it seemed that it was a defined thing last year.

**Comment by flaviendelangle** [comment]
I guess it will be part of X at some point, but I don't think we decided when, it could be in 2024.
