### ISSUE TITLE
DataGridPro getDetailPanelHeight changes not consistently applied to grid with autoHeight

### ISSUE THREAD

**Issue by palle-k** [mui/mui-x#4784]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When changing the return value of `getDetailHeight` of an `autoHeight` `DataGridPro`, the total height of the data grid does not change.

### Expected behavior 🤔

The height of the autoHeight DataGridPro should adapt when a different value is returned from `getDetailPanelHeight`.

### Steps to reproduce 🕹

Run the example code below and expand / collapse the detail panel of one of the rows.

```typescript
import React from "react";
import {DataGridPro, GridColumns} from "@mui/x-data-grid-pro";
import {Box, Typography} from "@mui/material";

export interface RowModel {
  id: string
  label: string
  text: string
}

const DetailView = React.forwardRef((props: {text: string}, ref) => <Box ref={ref} sx={{backgroundColor: 'red', width: '100%'}}>
  <Typography>{props.text}</Typography>
</Box>)

function useClientRect(): [DOMRect | undefined, (node: HTMLElement | null) => void] {
  const [rect, setRect] = React.useState<DOMRect | undefined>(undefined);
  const ref = React.useCallback((node: HTMLElement | null): void => {
    if (node) {
      setRect(node.getBoundingClientRect())
    } else {
      setRect(undefined)
    }
  }, []);
  return [rect, ref];
}

export default function Table() {
  const [detailRect, detailRef] = useClientRect()

  const columns: GridColumns<RowModel> = React.useMemo(() => [
    {
      flex: 1,
      editable: false,
      field: 'label',
      headerName: 'Label'
    }
  ], [])

  const rows: RowModel[] = React.useMemo(() => [
    {
      id: 'foo',
      label: 'Foo',
      text: 'I am a small piece of text.'
    },
    {
      id: 'bar',
      label: 'Bar',
      text: 'I am a small piece of text.'
    }
  ], []);

  return <DataGridPro
    autoHeight
    sx={{
      width: '100%',
      backgroundColor: 'green',
    }}
    columns={columns}
    rows={rows}
    getDetailPanelContent={params => <DetailView ref={detailRef} text={params.row.text}/>}
    getDetailPanelHeight={() => detailRect?.height ?? 300}
  />
}
```

### Context 🔦

I am working with the Master/Detail feature of a DataGridPro with autoHeight. I would like to have the detail view to have a dynamic height.
As this is currently unsupported, my workaround is to show the detail view (with an over-estimated default height returned from `getDetailPanelHeight`), measure it and then adapt the `getDetailPanelHeight` function to return the correct height for the detail view.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 17.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.79 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/material: ^5.6.4 => 5.6.4 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/system: ^5.6.4 => 5.6.4 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid:  5.10.0 
    @mui/x-data-grid-pro: ^5.10.0 => 5.10.0 
    @mui/x-license-pro:  5.10.0 
    @types/react: ^18.0.0 => 18.0.8 
    react: ^18.0.0 => 18.1.0 
    react-dom: ^18.0.0 => 18.1.0 
    typescript: ^4.6.3 => 4.6.4
```
</details>

**Comment by cherniavskii** [comment]
Hey @palle-k 
Here's a simplified demo of the issue: https://codesandbox.io/s/basicdetailpanels-material-demo-forked-t604oh?file=/demo.tsx
You can see that `autoHeight` doesn't recalculate grid height when detail panel height changes while detail panel is expanded.
cc @m4theushw 

As a sidenote, in your original example you keep track of one detail panel element at a time, so it works only if you expand one detail panel at a time. How about multiple expanded detail panels?

**Comment by palle-k** [comment]
@cherniavskii yes, I am aware that the example only tracks a single panel at a time; this is sufficient for my use case but if necessary, I guess it would be possible to store a detail panel height for each row. 

Looking at your simplified example, I am seeing further layout issues when multiple open detail panels change height at the same time, in which case, detail panels after the first open panel are pushed further downwards.

**Comment by m4theushw** [comment]
The master/detail feature was not designed to react when an already opened row has its height changed. The value returned by `getDetailPanelHeight` is only used when the row is expanding. In other words, when `detailPanelExpandedRowIds` changes to include a new ID. With that being said, you can, as a workaround, update `detailPanelExpandedRowIds` when the detail panel height is changed. The update I'm referring to could be to only recreate the array, keeping the same values. This will trigger the height calculation because the expanded IDs may have changed. Here's the CodeSandbox provided by @cherniavskii with the fix: https://codesandbox.io/s/basicdetailpanels-material-demo-forked-iilnfr?file=/demo.tsx

---

I agree it should work as expected. For this, we need deeper changes. We should update the cached value when the props changed and also trigger a new `rowHeight` pre-processing. The simplest option is to manually force a recalculation if the cache is updated:

```diff
diff --git a/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanelCache.ts b/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanelCache.ts
index f2b975e3f..3e30d539b 100644
--- a/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanelCache.ts
+++ b/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanelCache.ts
@@ -54,6 +54,7 @@ export const useGridDetailPanelCache = (
       };
     });
     apiRef.current.forceUpdate();
+    apiRef.current.unstable_requestPipeProcessorsApplication('rowHeight');
   }, [apiRef, props.getDetailPanelContent, props.getDetailPanelHeight]);
 
   useGridApiEventHandler(apiRef, 'sortedRowsSet', updateCaches);
```

I don't like too much this alternative because the `rowHeight` recalculation is not reactive. Instead, it's done manually. I think it would be better if we moved the cache computation to inside the pre-processors, as below:

```diff
diff --git a/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts b/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts
index 10f5b0feb..73ae87673 100644
--- a/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts
+++ b/packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts
@@ -98,6 +98,7 @@ export const useGridDetailPanel = (
       if (expandedRowIds.length === 0 || !expandedRowIds.includes(row.id)) {
         return { ...initialValue, detail: 0 };
       }
+      // calculate value and save in the cache
       const heightCache = gridDetailPanelExpandedRowsHeightCacheSelector(apiRef.current.state);
       return {
         ...initialValue,
```

**Comment by cherniavskii** [comment]
@palle-k here's your original example with the workaround suggested by @m4theushw https://codesandbox.io/s/basicdetailpanels-material-demo-forked-b43eh5?file=/demo.tsx

Meanwhile, I think we should wait for dynamic row height and see if it solves the issue

**Comment by johanssazores** [comment]
Hi following up on this for the dynamic row height, each of the data on our rows has different height. 

Thank you
