### ISSUE TITLE
[tests] Add e2e test on pickers components

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#4785]
Some behaviors of Pickers are hard to test correctly because they rely on the clock to wait for focus movement

```ts
export const executeInTheNextEventLoopTick = (fn: () => void) => {
  setTimeout(fn, 0);
};
```

For example, in #4747 to know if the focus moves outside of the `DateRangePicker` we use `executeInTheNextEventLoopTick` because when clicking on the other button, the focus goes to body and on the next tick it is on the input.

Maybe their is a way to avoid that, but for now I do not see other solution than e2e test to test this bug fix

**Comment by LukasTy** [comment]
Also, cover the time section selection management when using `DateTimePicker` without time renderers. Solved by https://github.com/mui/mui-x/pull/9342 (add tests avoiding potential future regressions).
Preferably run tests on all browsers (at least including Safari).
