### ISSUE TITLE
[data grid] NoRows overlay does not appear with loading and row update (broke in 5.9.0)

### ISSUE THREAD

**Issue by matandro** [mui/mui-x#4788]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We have a DataGridPro object that starts with `loading = false` and `rows = []`. In an initial useEffect we call an async function that:
1. sets the loading state variable to true
2. calls axios.get with an await parameter
3. sets the row state variable with the data
4. sets the loading variable to false

We have a test in which we mock the axios call and return `[]` in the data. the test fails when running `expect(getByText('No rows')).toBeInTheDocument();` In 5.5.1 it worked and it fails now. I also looked at the table manually and I don't see the overlay.

### Expected behavior 🤔

I expect the No Rows overlay to appear once the loading is set to false and the data from the axios response is an empty array.

### Steps to reproduce 🕹

I was able to reproduce in a minimal setting
See: https://codesandbox.io/s/data-grid-pro-forked-sh5l0f?file=/src/App.jsx

Things I did that made the "No rows" overlay to appear (each worked separately):
1. remove the loading parameter from the DataGridPro object
2. remove the setLoading(true) call from the async function
3. remove the setRow(response.data) call from the async function
4. Change mui data grid pro to versions before 5.9.0

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 4.73 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Managers:
    Homebrew: 3.3.14 - /usr/local/bin/brew
    pip3: 22.0.4 - ~/Projects/Disco-portal/.venv/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    Clang: 13.0.0 - /usr/bin/clang
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.14 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Erlang: 23.3.2 - /usr/local/bin/erl
    Java: 1.8.0_242 - /usr/bin/javac
    Perl: 5.26.2 - /usr/local/anaconda3/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Protoc: 3.15.8 - /usr/local/bin/protoc
    Python: 3.8.5 - /Users/matan/Projects/Disco-portal/.venv/bin/python
    Python3: 3.8.5 - /Users/matan/Projects/Disco-portal/.venv/bin/python3
    R: 3.6.2 - /usr/local/bin/R
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    MySQL: 10.16 - /usr/local/bin/mysql
    SQLite: 3.36.0 - /usr/local/anaconda3/bin/sqlite3
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.0
</details>

### Order ID 💳 (optional)

#33539

**Comment by alexfauquette** [comment]
Since you pointed out that the bug appears in v5.9.0 It might have been introduced in PR #4334 

@m4theushw From what I understand, you moved the `loading` prop management in the row state. So its modification impact the state when `throttledRowsChange` is called.

It should be called each time the `loading` is modified, but there is an optimization that check if the `rows` prop has been modified

https://github.com/alexfauquette/mui-x/blob/fix-year/packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts#L506-L509


Maybe this early return should be modified to check if `loading` has been modified compared to the last render

**Comment by m4theushw** [comment]
@alexfauquette is correct. If the rows are the same from the previous time the effect was called, we don't update the state. The state corresponding to the `loading` prop should be updated in another effect.

As a workaround, merge the loading and row data in the same state. This way, a single rerender is triggered.

Updated CodeSandbox: https://codesandbox.io/s/data-grid-pro-forked-8ozs26?file=/src/App.jsx
