### ISSUE TITLE
[DayPicker] Excessive empty space at the bottom of the calendar

### ISSUE THREAD

**Issue by efattal** [mui/mui-x#4819]
Hi everyone,

We noticed an empty space at the bottom of the Calendar, everywhere it is used, even when all 6 possible week rows are used.
![image](https://user-images.githubusercontent.com/22234235/153232523-c787f865-955d-4511-b89a-62ae29f867b7.png)

It looks that it comes from the fact that [the minHeight is set here to 288px](https://github.com/mui/material-ui/blob/efa9620d0c4c6ee62076c9592dab5f4e448f7128/packages/mui-lab/src/DateRangePicker/DateRangePickerViewDesktop.tsx#L60
), overriding the 264px that would be enough.

Question: what is the reason of this empty space?

Thanks for your help.

**Comment by flaviendelangle** [comment]
I don't have a backstory for the size of the views.
We could probably reduce the height to match exactly 6 weeks.
