### ISSUE TITLE
[data grid] Allow GridFilterPanel filterFormProps valueInputProps variant customization

### ISSUE THREAD

**Issue by KvnPeters** [mui/mui-x#4822]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi,

I found when customizing the `GridFilterPanel` by setting `filterFormProps` the `variant` prop would not have any effect in the `valueInputProps`, but work for `operatorInputProps` and `columnInputProps`. Since I am not sure if this is by design I set this as a feature request.

### Examples 🌈

```
<GridFilterPanel
  filterFormProps={{
    valueInputProps: {variant: 'outlined'},     // <- Has no effect
    columnInputProps: {variant: 'outlined'},    // <- Works
    operatorInputProps: {variant: 'outlined'},  // <- Works
  }}
/>
```
![Screenshot from 2022-05-10 12-56-10](https://user-images.githubusercontent.com/97105830/167613363-f1a0b44d-35a6-4506-ac27-11c1a0ba9103.png)

### Motivation 🔦

On the `<DataGridPro/>` component we leverage the `components` prop to inject a custom dialog (by replacing the `<GridFooter/>` with `<><GridFooter/><CustomDialog/></>`) in which we want to reuse the `<GridFilterPanel/>` but with different theming. We inject the dialog in the components prop so we have access to the context object which is needed to render the GridFilterPanel. 

### Order ID 💳 (optional)

39800

**Comment by alexfauquette** [comment]
In fact, it is slightly more complicated than just removing `variant="standard"` from the default components, because `TextField` does not hesitate the variant from `FormControl`

I opened an issue+PR to try fixing it
https://github.com/mui/material-ui/issues/32718

**Comment by KjipN** [comment]
![Screenshot_٢٠٢٢٠٥١١-١٥٣٩٢٤.png](https://user-images.githubusercontent.com/105365366/167857244-ac544972-8ea8-4497-8f5f-126deea5628b.png)
