### ISSUE TITLE
DesktopDatePicker not updating value properly

### ISSUE THREAD

**Issue by cati97** [mui/mui-x#4823]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I input date manually (e.g. 06.05.2022) instead of choosing it from the calendar, the proper date 06.05.2022 is selected in the calendar but after clicking anywhere outside the calendar, the date is set to the previous entered date or if nothing was previously chosen - to null.

### Expected behavior 🤔

When I input date manually I would like to have calendar with that date selected on open and if I don't click anywhere on the calendar and I close it (by clicking outside of the calendar) - the date should still be the one I entered manually.

### Steps to reproduce 🕹

Steps:

1. Select a date from the calendar (not manually but from calendar) - e.g. 06.05.2022
2. Change manually the date - to e.g. 10.05.2022
3. Enter calendar (the manually changed date 10.05.2022 is selected properly)
4. Click anywhere outside the calendar (without picking another date).
5. Date will change automatically to the previous value - 06.05.2022 (and it should be current value 10.05.2022)

Link to codesandbox: https://codesandbox.io/s/desktopdatepicker-forked-y3p5h7

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
[Reproduction case without `react-hook-form`](import * as React from "react";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DesktopDatePicker } from "@mui/x-date-pickers/DesktopDatePicker";

export default function MaterialUIPickers() {
  const [value, setValue] = React.useState(new Date());

  return (
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <Stack spacing={3}>
        <DesktopDatePicker
          label="Date desktop"
          inputFormat="dd/MM/yyyy"
          value={value}
          onChange={(date) => {
            console.log(value);
            setValue(date);
          }}
          renderInput={(params) => <TextField {...params} />}
        />
      </Stack>
    </LocalizationProvider>
  );
}
)
