### ISSUE TITLE
[DateTimePicker] minDate maxDate prop on throws error when using @mui/x-date-pickers/MobileDatePicker 

### ISSUE THREAD

**Issue by Shahzaib-ur-Rehman** [mui/mui-x#4824]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Could you provide an example, because it seems to work
https://codesandbox.io/s/responsivedatepickers-material-demo-forked-0vynvs?file=/demo.tsx

**Comment by alexfauquette** [comment]
Your title is talking about `DateTimePicker` your code is using `DatePickerComponent` and there is no `minDate`

Please provide a codesandbox and the instruction we should follow to observe your bug

If in the future you want to share code, please have a look at [github doc ](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
