### ISSUE TITLE
[DateTimePicker] Toolbar should be visible by default on mobile

### ISSUE THREAD

**Issue by pganster** [mui/mui-x#4828]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The TimePicker, DatePicker and DateRangePicker components all show the toolbar on mobile, as expected:
![image](https://user-images.githubusercontent.com/89004989/167670934-0f8d4308-1dde-4ca6-a909-b3081031cb50.png)

But since we migrated from @mui/lab to Mui X, the DateTimePicker is missing that toolbar on mobile:
![image](https://user-images.githubusercontent.com/89004989/167671141-0089ac8e-a807-4671-8616-aad2c79ae3dd.png)

### Expected behavior 🤔

The DateTimePicker should also show that toolbar with the pencil so on mobile, the date time can be entered via Keyboard too.

### Steps to reproduce 🕹

Steps:

1. Open the following codepen: https://codesandbox.io/s/hwqvh0
2. On Chrome, open the DateTimePicker demo https://hwqvh0.csb.app/ and in the Chrome Devtools, enable mobile device simulation:
![image](https://user-images.githubusercontent.com/89004989/167671730-fdf06340-eeab-4958-a91b-2f936520a9cc.png)
3. See that the toolbar is missing

### Context 🔦

Since we use the pencil to set the value of the DateTimePicker in our unit tests, this behavior broke our unit tests after the migration from mui/lab to Mui X. As a current workaround, we set the `showToolbar={!isDesktop}` property of the DateTimePicker via the same media query as MUI does (`const isDesktop = useMediaQuery('@media (pointer: fine)');`).

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Manjaro Linux
  Binaries:
    Node: 17.8.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 99.0.1
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.79 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/lab: ^5.0.0-alpha.80 => 5.0.0-alpha.80 
    @mui/material: ^5.6.4 => 5.6.4 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/system:  5.6.4 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.2 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.2 => 5.0.0-alpha.2 
    @mui/x-license-pro: ^5.10.0 => 5.10.0 
    @types/react: ^18.0.8 => 18.0.8 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript: ^4.6.4 => 4.6.4
```
</details>

Browser: Chrome Version 101.0.4951.41 (Official Build) (64-bit)

### Order ID 💳 (optional)

#43453

**Comment by flaviendelangle** [comment]
Thanks for the detailed report
Bug caused by #4451 

I will do a quick fix :+1:
