### ISSUE TITLE
Changing the input text boxes of DateRangePicker won't update state

### ISSUE THREAD

**Issue by pganster** [mui/mui-x#4829]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

If I type into the text boxes rendered by the DateRangePicker and close the picker (or tab out of the text boxes) the input gets reset. Currently there is no way of entering the date ranges by hand, one must always use the picker dialog.

### Expected behavior 🤔

Changing the date via the text boxes should also change the state. Same as the DatePicker, DateTimePicker and TimePicker behave.

### Steps to reproduce 🕹

Steps:

1. Open the codepen https://codesandbox.io/s/2jvjiz?file=/demo.js
2. Type "01/15/1990" into Check-in
3. Type "01/31/1990" into Check-out
4. Press TAB on your keyboard, or click outside of the picker dialog to close it
5. The entered dates disappear.

### Context 🔦

Comparing the behavior to the DatePicker component https://codesandbox.io/s/nf0p96?file=/demo.js, we can see that the DatePicker accepts the value as expected and that the DateRangePicker behavior is inconsistent and needs to be changed.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
   System:
    OS: Linux 5.15 Manjaro Linux
  Binaries:
    Node: 17.8.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 99.0.1
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.79 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/lab: ^5.0.0-alpha.80 => 5.0.0-alpha.80 
    @mui/material: ^5.6.4 => 5.6.4 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/system:  5.6.4 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.2 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.2 => 5.0.0-alpha.2 
    @mui/x-license-pro: ^5.10.0 => 5.10.0 
    @types/react: ^18.0.8 => 18.0.8 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript: ^4.6.4 => 4.6.4
```
</details>

Browser: Version 101.0.4951.41 (Official Build) (64-bit)

### Order ID 💳 (optional)

#43453

**Comment by flaviendelangle** [comment]
Fixed by #4408
The fix should be released this week
