### ISSUE TITLE
[DatePicker] Clicking outside the popup resets the state to the previous value

### ISSUE THREAD

**Issue by LorhanSohaky** [mui/mui-x#4832]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. Sets a date (e.g. '2022-01-06')
2. Select another year and month (e.g. '2021-05-06'), but not confirm
3. Click outside
4. The value is restored to the previous value

![ezgif com-gif-maker](https://user-images.githubusercontent.com/16273730/167728798-6645432f-6b59-4527-956f-699c6f06add1.gif)

### Expected behavior 🤔

# First option
1. Sets a date (e.g. '2022-01-06')
2. Select another year and month (e.g. '2021-05-06'), but not confirm and automatically update the state
3. Click outside
4. Keep the current value

# Second option
1. Sets a date (e.g. '2022-01-06')
2. Navigates between dates, but not 
2. Select another year and month (e.g. '2021-05-06'), but not confirm and NOT update the state
3. Click outside
4. Keep the previous value

### Steps to reproduce 🕹

Steps:

1. Click on DatePicker
2. Sets a date (e.g. '2022-01-06')
3. Click on DatePicker
4. Select another year and month (e.g. '2021-05-06')
5. Click outside

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.2
    Yarn: 1.22.15
    npm: 8.1.2
  Browsers:
    Chrome: Not Found
    Firefox: 100.0 (64-bits)
  npmPackages:
    @emotion/react: ^11.8.2 => 11.8.2 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.72 
    @mui/icons-material: ^5.5.1 => 5.5.1 
    @mui/material: ^5.5.1 => 5.5.1 
    @mui/private-theming:  5.4.4 
    @mui/styled-engine:  5.4.4 
    @mui/styles: ^5.5.1 => 5.5.1 
    @mui/system:  5.5.1 
    @mui/types:  7.1.3 
    @mui/utils:  5.4.4 
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.2 
    @types/react: ^17.0.40 => 17.0.40 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.6.2 => 4.6.2 
```
</details>

**Comment by flaviendelangle** [comment]
Fixed by #4408
The fix should be released this week
