### ISSUE TITLE
[DateTimePicker] Replace ClockPicker in DateTimePicker

### ISSUE THREAD

**Issue by srohrer** [mui/mui-x#4837]
Working on a styled version of the DateTimePicker component, and my designers don't like the clock UI for the time picker.  I'm trying to find a way to replace it with my own separate UI (something like the native chrome time picker UI) but I don't see any equivalent to the renderInput for the clock view.  

Would it be possible to add something like that?  Or is there a workaround?

**Comment by flaviendelangle** [comment]
@srohrer could you have a look at #4483 ? I think it's the same topic
If you have reference of time UI you like feel free to link them on #4483.
