### ISSUE TITLE
[DatePicker] Weird behavior when typing alphabetical characters into the input field

### ISSUE THREAD

**Issue by ckhuang98** [mui/mui-x#4838]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When typing a alphabetical character into the date picker, the last digit in the date is removed and the rest of the digits shift to the right.

### Expected behavior 🤔

 Nothing happens, this is invalid input

### Steps to reproduce 🕹

1. Click into the middle of a date input
2. Type "g"

### Context 🔦

We are trying to use this component in production and have no work around other than to tell users not to do this. Users are confused by the behavior.

### Your environment 🌎

 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 2.16 GB / 15.72 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.34.1. - C:\Program Files\Git\mingw64\bin\git.EXE
  IDEs:
    VSCode: 1.67.0 - C:\Users\chuang\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.11.31911.196 (Visual Studio Professional 2019)
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
    Perl: 5.34.0 - C:\Program Files\Git\usr\bin\perl.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.39)
    Internet Explorer: 11.0.19041.1566
  Monorepos:
    Yarn Workspaces: 3.2.0
    Lerna: 4.0.0

**Comment by alexfauquette** [comment]
That's a bug in the mask formatter which should be fixed by the PR

Thanks for the clear explanation of the bug
