### ISSUE TITLE
[DatePicker] Does not reset an invalid date, only a valid one in case the initial date is null

### ISSUE THREAD

**Issue by KatsiarynaTatarynovich** [mui/mui-x#4844]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

**Preconditions:**

- We use DesktopDatePicker. The initial date value = null. 
- We also have the function `pickerValueToIsoString` that triggers when we update the value. It checks whether the value is valid or not. `return date?.isValid ? date.toISODate() : null;`
- We have a reset button = set date value as the initial date value;

When I fill in the invalid date as 22/22/2222 and then click on the reset button nothing happens I still can see 22/22/2222, the date field is not reset.

**Note**
When the initial date value is not null, but some valid value everything works correctly.

### Expected behavior 🤔

When I fill in the invalid date and then click on the reset button => the date field is reset with the initial value.

### Steps to reproduce 🕹

Steps:

`const pickerValueToIsoString = (date: DateTime | null): string | null => date?.isValid ? date.toISODate() : null;`

1. DesktopDatePicker. The initial date value = null. 
2. When we update the value with an invalid date (22/22/2222)=> the function `pickerValueToIsoString` is triggered
3. Click on the reset button, it sets date value as the initial date value
4. The date field is not reset, we still see 22/22/2222

**Comment by flaviendelangle** [comment]
I am transferring this issue to the new repository.
But without a reproduction case, we won't be able to work on it @KatsiarynaTatarynovich

**Comment by mc-gorky** [comment]
@flaviendelangle  could you please check this example https://codesandbox.io/s/sweet-zeh-6ouimg
