### ISSUE TITLE
[DatePicker] inconsistency between selecting and typing date

### ISSUE THREAD

**Issue by croraf** [mui/mui-x#4848]
- [x ] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When date is typed it puts time to 00:00 local time. (and timezone)
When date is picked it puts time to current local time. (and timezone)

## Expected Behavior 🤔

The two should be consistent.

## Steps to Reproduce 🕹

https://codesandbox.io/s/basicdatepicker-material-demo-forked-3zowk

Steps:

1. Type date, and check the console.
2. Clear date, pick date, and check the console.

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
The behavior is now coherent between selecting and typing.
Since #4649, in both cases, we use midnight instead of the current time.

Are you sure the whole discussion about the timezone strictly relates to the initial pain of the issue ?

**Comment by flaviendelangle** [comment]
Closing from lack of feedback, and the initial pain has been resolved.
You have issues strictly related to timezone if you want to continue the discussion :+1:
