### ISSUE TITLE
[pickers] Instructions for installing the package are not complete on the README

### ISSUE THREAD

**Issue by anthony-tron** [mui/mui-x#4849]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
$ react-scripts start

./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Can't resolve 'date-fns/_lib/format/longFormatters'
```

### Expected behavior 🤔

Server goes fine.

### Steps to reproduce 🕹

Steps:

1. `npx create-react-app app`
2. `npm i @mui/material @mui/system @mui/x-date-pickers react react-dom`
3. npm start

### Context 🔦

I'm trying to follow the [installation guide of `@mui/x-date-pickers`](https://www.npmjs.com/package/@mui/x-date-pickers) that says these are the peer dependencies : 

```json
"peerDependencies": {
  "@mui/material": "^5.2.3",
  "@mui/system": "^5.2.3",
  "react": "^17.0.2 || ^18.0.0",
  "react-dom": "^17.0.2 || ^18.0.0"
},
```

But I think it's missing `date-fns`.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 99.0
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.76 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/material: ^5.5.3 => 5.6.1 
    @mui/private-theming:  5.7.0 
    @mui/styled-engine:  5.7.0 
    @mui/system: ^5.7.0 => 5.7.0 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.2 
    @types/react:  17.0.43 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 

```
</details>

**Comment by alexfauquette** [comment]
Date pickers allow you to choose the library you use to manage the date

Please refer to the documentation for the installation

https://mui.com/x/react-date-pickers/getting-started/#setup

@samuelsycamore I don't know I we should copy pas the installation guideline of the doc in this page, or just put a redirection to the documentation page

**Comment by anthony-tron** [comment]
Thank you for replying!

In fact I was on [this part of the documentation](https://mui.com/x/react-date-pickers/date-picker/#main-content) so I didn't see the setup part! It's also my bad for reading too fast.

**Comment by alexfauquette** [comment]
@flaviendelangle I'm looking at the installation doc and noticed that some command line contains `-s` and other not

Is their a specific reason or is it a typo I can correct?
```bash
// date-fns
npm install @date-io/date-fns
// or for Day.js
npm install -s @date-io/dayjs
// or for Luxon
npm install -s @date-io/luxon
// or for Moment.js
npm install @date-io/moment
```

**Comment by flaviendelangle** [comment]
I think it is a legacy thing (it meant "save in `package.json`)
We can remove
