### ISSUE TITLE
[DatePicker] date selection not working when only changing the year

### ISSUE THREAD

**Issue by cyrilkyburz** [mui/mui-x#4856]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a date is selected and only the year is changed, the same day can not be selected. 

### Expected behavior 🤔

When a date is selected and only the year is changed, the same day can be selected.

### Steps to reproduce 🕹

Steps:

1. Go to [Mui DatePicker Page](https://mui.com/x/react-date-pickers/date-picker/#main-content)
2. In the Basic usage picker select a date
3. Change only the year
4. Select the same day (not working)

### Context 🔦

If only the birth year is wrong, the user can not directly change it with the picker.

It's definitely an edge case and doesn't need high prio.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Fixed by #4808
The fix will soon be available

**Comment by flaviendelangle** [comment]
It should be fixed in the latest release, if you still have a problem on it could you give me a reproduction case ? Maybe I missed something

**Comment by martin056** [comment]
@flaviendelangle Thank you for your help :bow: My problem came from the package versions. I haven't added 
```
"@mui/x-date-pickers": "^5.0.0-alpha.7"
```
to my `package.json` dependencies. I think I've used the one that comes with `"@mui/material"` by default which apparently is not the latest version which is released by `x-date-pickers`. Sorry for wasting your time.

**Comment by martin056** [comment]
> You were probably using the one from `@mui/lab` indeed +1 This dep will be removed in the next lab release.

That's great news! It'll definitely make things more clear. Thank you once again :)
