### ISSUE TITLE
DataGrid cell value is replacing commas with decimals

### ISSUE THREAD

**Issue by preethunninair** [mui/mui-x#4865]
Even though in the DOM it shows that the cell contains number with comma (eg: 22,67) the UI still shows 22.67. 
![image](https://user-images.githubusercontent.com/66544522/168275177-030f688a-585c-411a-af17-f399e77ee192.png)

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
