### ISSUE TITLE
[data grid] Allow to limit to one filter per column

### ISSUE THREAD

**Issue by landrevj** [mui/mui-x#4872]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Ideally, I would be able to pass in a prop somewhere that would prevent the filter panel from allowing more than one filter per column.

I could see this prop being on the main DataGridPro component, passed to the filter panel through `componentProps`, or as some kind of field as part of a column definition.

When this setting is enabled and a filter is created for a column this could either remove that column as an option from the column select or perhaps simply disable that column's item within the select.

### Examples 🌈

```JSX
<DataGridPro
    ...
    isOneFilterPerColumn
    // or
    componentsProps={{ filterPanel: { isOneFilterPerColumn: true }}}
    ...
/>
```

Something like that anyway.

### Motivation 🔦

The route I hit to get data for this table only allows one filter per column. An example call might look like: `/some/api/route?titleContains=something&appName=somethingElse`... etc. It can do filtering on multiple columns at once but not multiple filters per column.

I can tailor the column filters to match what is available on the route but I can't prevent the user from creating multiple filters for a column unless I restrict them to only one filter in general which doesn't meet the requirements for the feature I'm implementing.

I have tried manually pruning the filterModel but that runs into issues where you either soft lock the filter panel from creating new filters or end up doing something which would end up just looking like a bug to the user.

### Order ID 💳 (optional)

_No response_ (I'll update when I hear back on what ours is.)

**Comment by flaviendelangle** [comment]
Hi,

I don't think we ever had this demand before, but it seems to make sense.
Not sure what the UI should look like to let the user create a new filter but not on already-filtered columns.

**Comment by landrevj** [comment]
Actually, I think our use case would benefit from being able to set a property per column definition as with something like `filterable`, however I'd be able to work around that UX wise if this gets implemented as an setting for the whole table.

**Comment by m4theushw** [comment]
To solve this issue, I think we have two options:

1. Add a prop to limit to only one filter for each column

    It's the easiest solution for developers to use, but we may not allow other customizations.

3. Add callbacks to allow to filter which columns to show

    They could be used as follow::

    ```tsx
    <DataGridProp
      componentsProps={{
        filterPanel: {
          filterFormProps: {
            filterColumns: ({ columnField }) => [...] // Checks the filter model and returns the available columns
          },
          getFieldForNewFilter: () => ... // Returns which field to use when adding a new filter
        }
      }}
    />
    ```

**Comment by landrevj** [comment]
Either of those options would work for our use case, but I definitely like the flexibility of the second option.
