### ISSUE TITLE
[pickers] TimePicker ignoring mask when used AdapterDayjs on `LocalizationProvider`

### ISSUE THREAD

**Issue by josejimenez-swipejobs** [mui/mui-x#4890]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I recently installed the latest version of `@mui/x-date-pickers`(5.0.0-alpha.3) and the latest of dayjs library `1.11.2`. But, when I try to use the component `TimePicker` with the ampm as `true`, it ignores the mask and allows any format on the input.

![Screen Shot 2022-05-16 at 5 28 01 am](https://user-images.githubusercontent.com/58408953/168490506-99d37a69-3e72-421a-b4f0-8b0a338c8d96.png)

I created this CodeSandbox to reproduce the issue https://codesandbox.io/s/input-format-adapter-dayjs-fot7g4?file=/src/App.js.

### Expected behavior 🤔

It will be great that the `TimePicker` works with the adapter: `AdapterDayjs` for the `LocalizationProvider`.

### Steps to reproduce 🕹

Steps:

1. Install the latest `@mui/x-date-pickers`,
2. Use the adapter `AdapterDayjs` on the LocalizationProvider Context,
3. Use the prop `ampm` as true in the component `TimePicker`.

### Context 🔦

Seems to be that this issue comes from here: https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/TimePicker/shared.ts#L81

This is setting the value from the context as `utils.formats.fullTime12h` for `ampm` true. This value comes from as "hh:mm A" rather than "hh:mm a".

I'm currently fixing this issue by forcing the `TimePicker` to use the prop `inputFormat` as "hh:mm a" when `ampm` is true.

```
<TimePicker
  ampm
  inputFormat="hh:mm a"
  value={value}
  onChange={setValue}
  renderInput={(params) => <TextField {...params} />}
/>
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 38.00 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 7.24.2 - ~/Develop/fe-core-elements/node_modules/.bin/npm
  Managers:
    Homebrew: 3.2.15 - /usr/local/bin/brew
    pip3: 19.2.3 - /usr/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  IDEs:
    IntelliJ: 2021.2.2
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.2 - /usr/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 14.1.2
```
</details>

**Comment by alexfauquette** [comment]
That's a good workaround.

The problem seems to come from capitalization. The date-fns library is the only one to use lower case for am/pm. Other libraries are with capital letters. 

![image](https://user-images.githubusercontent.com/45398769/168541692-df49d1ec-0a04-496c-b0c9-24cf197d6c44.png)

I see three options:
- we can prevent similar bugs by comparing lowercased masked with lowered case formatted dates
- we can make a commit on date-io such that 12h format has same capitalization for all
- Generates mask from the inputFormat, see #4756
