### ISSUE TITLE
[DataGrid] add hideColumnsHeader to hide header

### ISSUE THREAD

**Issue by sudokzt** [mui/mui-x#4897]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

hideColumnsHeader option hides header for columns.

### Examples 🌈

```
<DataGrid
  rows={rows}
  columns={columns}
  pageSize={5}
  rowsPerPageOptions={[5]}
  checkboxSelection
  disableSelectionOnClick
  hideColumnsHeader // new option
/>
```

### Motivation 🔦

I would have liked to hide the header for columns.
to achieve it, I added `headerHeight={0}` to DataGrid Component.
it seems to be working fine at first glance. But it has a problem.
this solution affects the performance of rendering.
I don't even want to render the header of the DOM.

**Comment by flaviendelangle** [comment]
Duplicates #3282

I close this one to keep a single discussion
