### ISSUE TITLE
[core] Update l10n script for pickers

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#4914]
Follow up of #4517

The idea is to update #3211 with missing translation from the pickers

I'm wondering if we should include them in the existing issue or rename it

- Help us to translate the data grid
- Help us to translate the pickers

**Comment by flaviendelangle** [comment]
The current data grid issue is very long, I would be in favor of creating a different one for the pickers and rename the existing one as you proposed (@m4theushw)

**Comment by m4theushw** [comment]
We could limit the number of translations missing shown in each locale in #3211. This would help to reduce the noise. There're some locales that are too outdated, e.g. `zh-CN`.

Another option is to not use the permalink as text, but render only the key missing. As example, https://github.com/mui/mui-x/issues/2081 contains as much information as #3211 but doesn't feel overwhelmed.
