### ISSUE TITLE
[pickers] Allows to customize all texts with `localeText`

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#4916]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Followup of #4517

For now only props of type `string` are deprecated. It should also support functions such as `defaultGetClockLabelText`

**Comment by flaviendelangle** [comment]
@alexfauquette do we have locale text to add left ?

**Comment by alexfauquette** [comment]
I think #5143 was the last one. Hard to be sure we catch them all.

**Comment by flaviendelangle** [comment]
It will be easier once we remove the props going to slots and the deprecated one.
