### ISSUE TITLE
[question] csv export Korean broken

### ISSUE THREAD

**Issue by jinow9595** [mui/mui-x#4920]
### Order ID 💳

39248

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

When exporting csv from datagrid pro, English is good, but Korean is broken.
Please check if there is a way to deal with the error.

### Your environment 🌎

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.47)
  npmPackages:
    @emotion/react: ^11.8.2 => 11.8.2
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.74
    @mui/icons-material: ^5.5.1 => 5.5.1
    @mui/lab: ^5.0.0-alpha.75 => 5.0.0-alpha.75
    @mui/material: ^5.5.3 => 5.5.3
    @mui/private-theming:  5.5.3
    @mui/styled-engine:  5.5.2
    @mui/styled-engine-sc: ^5.5.2 => 5.5.2
    @mui/styles: ^5.5.3 => 5.5.3
    @mui/system:  5.5.3
    @mui/types:  7.1.3
    @mui/utils:  5.5.3
    @mui/x-data-grid:  5.8.0
    @mui/x-data-grid-generator: ^5.7.0 => 5.8.0
    @mui/x-data-grid-pro: ^5.7.0 => 5.8.0
    @mui/x-license-pro:  5.7.0
    @types/react: 17.0.43 => 17.0.43
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: ^5.3.5 => 5.3.5
    typescript: 4.6.3 => 4.6.3

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

**Comment by jinow9595** [comment]
That template is an example that does not include the csv export function :(

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/data-grid-community-forked-z2b6jm?file=/src/App.tsx

Here is an example with the CSV button
What is not working as expected ?

**Comment by jinow9595** [comment]
I'm sorry, but I'll explain it again.
![broken-korean](https://user-images.githubusercontent.com/69668970/169464128-0cd015b1-04ee-4612-bc11-945fbb76bb11.png)

If the data in datagrid is Korean, the data in the csv file is broken.

**Comment by flaviendelangle** [comment]
It would be a lot easier if you provided me a reproduction case
I tried with a few Korean words translated with Google Translate and I don't have your problem (the `?` I suppose).
The issue may be obvious to you, but it is not for me.

**Comment by cherniavskii** [comment]
`utf8WithBom` should help - see https://github.com/mui/mui-x/issues/5877#issuecomment-1224834664
