### ISSUE TITLE
DataGridPro - Column Width changes back to default when Menu is opened

### ISSUE THREAD

**Issue by radu-nicoara-bayer** [mui/mui-x#4922]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

You can use this as an example:
https://stackblitz.com/edit/react-ant7kn?file=demo.tsx
Create a DataGridPro, and add a menu item and a button inside of a column (we use this to provide context actions to our items)

1. Resize a column, that has a default width.
2. Press on the button in the cell, to open the menu
3. Once the menu is open, the column resizes to its original value

I have tested it without a default value, and the bug no longer occurs.

### Expected behavior 🤔

After I resize a column, and open a Menu in context to the column, the column width should remain as I have modified it, not go to default.

### Steps to reproduce 🕹

Steps:

1. Resize a column, that has a default width.
2. Press on the button in the cell, to open the menu
3. Once the menu is open, the column resizes to its original value

### Context 🔦

We use DataGridPro to list an array of objects. For each one of them, the user can choose "Rename", "View details", "Delete", for each column.

Since our display needs a certain design, we have default column widths. But the users do move them around and resize them, and once they open the menu, everything resets.

It is not a major bug, but an inconvinience.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
https://stackblitz.com/edit/react-ant7kn?file=demo.tsx
Used Edge
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

You must memoize your columns, otherwise on the next render the grid will update the columns to equal the new value you passed in the props

https://codesandbox.io/s/data-grid-pro-forked-lqi74x?file=/src/App.tsx

**Comment by radu-nicoara-bayer** [comment]
I understand how I over-simplified the example. Sorry about that.
Our menu is actually outside of the column, as it is shared with some other components and modals within the page.
I updated the example, and even with the abstractization suggested, the error persists.

At the moment, we can not put the menu inside the row, but needs to stay outside, as we also have modals, and complex logic related to it, and it inevitably leads to the same bug, just at a different step.
