### ISSUE TITLE
[docs] Codesandbox examples are broken

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#4924]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When opening a codesandbox demo, the following message appears:

```
(0 , $csb___mui_utils.unstable_generateUtilityClasses) is not a function
```

### Expected behavior 🤔

Demo are working

### Steps to reproduce 🕹

Steps:

1. Go on the doc
2. open a demo (for example [this one](https://mui.com/x/react-data-grid/components/#column-menu))

### Context 🔦

First noticed in #4921

The problem seems to come from `@mui/material` v5.8.0 which seems to be incompatible with `@mui/utils` v5.7.0 (the version asked by the data grid) because the problem is solved when setting `@mui/utils` to v5.8.0 in the package.json

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment]
Same as this? https://github.com/codesandbox/codesandbox-client/issues/6484

**Comment by alexfauquette** [comment]
Yes, looks very similar

**Comment by joserodolfofreitas** [comment]
At first, I was concerned this meant that every MUI X user with the latest Material UI v5.8.0 would face this issue.
But I tried it locally and it seems it's a problem in codesandbox only (Stackblitz is also ok).

Perhaps it is indeed the weird cache problem again.

But this issue got me thinking: would it make sense to consider `@mui/utils` as a peer dependency?

**Comment by cherniavskii** [comment]
Yeah, it's a bundling issue in codesandbox.

`@mui/material` files are downloaded from here:
https://prod-packager-packages.codesandbox.io/v2/packages/@mui/material/5.8.0.json

And they contain proper version of `@mui/utils` with `unstable_generateUtilityClasses` exported
 
<img width="421" alt="Screenshot 2022-05-18 at 18 07 14" src="https://user-images.githubusercontent.com/13808724/169090513-7665c3fd-3777-424f-8ecb-77abe630a80b.png">


`@mui/x-data-grid` files include `@mui/utils@5.7.0`:
https://prod-packager-packages.codesandbox.io/v2/packages/@mui/x-data-grid/5.11.0.json

<img width="797" alt="Screenshot 2022-05-18 at 18 07 26" src="https://user-images.githubusercontent.com/13808724/169090769-0f653054-c214-453c-b617-d80e33176465.png">


And then for some reason `@mui/system` tries to import from `@mui/utils@5.7.0`, even though it requires `@mui/utils@5.8.0`

**Comment by oliviertassinari** [comment]
I can confirm the version resolution bug with codesandbox. A local installation doesn't reproduce.

<img width="226" alt="Screenshot 2022-05-19 at 10 29 02" src="https://user-images.githubusercontent.com/3165635/169249123-a01c9ff6-9d47-4c37-8794-3aa0aa0ccabc.png">
 
However, locally, it beaks with 

<img width="1202" alt="Screenshot 2022-05-19 at 10 28 03" src="https://user-images.githubusercontent.com/3165635/169249190-49908b34-9f7e-433e-936b-98dda1636fd4.png">

Which is related to https://github.com/mui/material-ui/pull/32824/files#r876758651

**Comment by m4theushw** [comment]
The CodeSandbox examples are working again.

**Comment by oliviertassinari** [comment]
Perfect

**Comment by jmmwangi007** [comment]
My Datagrid component works fine locally but when I deploy to vercel/netlify, I get a blank page. Is this related, and if so, how do I solve this?

I'm using [mui/x-data-grid](https://www.npmjs.com/package/@mui/x-data-grid) latest version

**Comment by oliviertassinari** [comment]
@jmmwangi007 this is about a bug in Codesandbox, if you have a reproduction, please open a new GitHub issue. If you are commenting on this issue because you see a similar error message, then update ALL your dependencies, lock file included (I would recommend to delete it and regenerate it).
