### ISSUE TITLE
[DataGrid] GridRow throws Hooks exception when I try to edit a custom cell.

### ISSUE THREAD

**Issue by PedroLucasSilva** [mui/mui-x#4925]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I click on an editable cell that has a custom component I get an error in the console about the rendering order of the hooks.

![image](https://user-images.githubusercontent.com/23297731/169042613-43ee88ae-fd6a-4272-bdaa-ae1d7fdce18b.png)

### Expected behavior 🤔

I should be able to edit without any errors being thrown to the console.

### Steps to reproduce 🕹

Steps:

1. Open this example https://codesandbox.io/s/data-grid-community-forked-xmherr?file=/src/App.tsx
2. Try editing a cell from the first column
3. Check the console for errors

### Context 🔦

In our project, we have an input a little more complex than this, made to format dates as the user writes. After switching to mui 5 and the latest version of DataGrid we have faced this problem.

**Comment by flaviendelangle** [comment]
Hi,

I can't reproduce the crash when editing a cell of the 1st column in your example linked above.
Are you sure this example is complete ?

**Comment by PedroLucasSilva** [comment]
Hi @flaviendelangle! Did you double click on the cell and look at the console? I asked other people on my team to test it and the result was the same as mine.

![image](https://user-images.githubusercontent.com/23297731/169105429-258a1d84-71c1-4270-8bea-07cf06aac3fb.png)

**Comment by flaviendelangle** [comment]
I was not looking at the console sorry...

But I agree with the fix proposer by Matheus.
