### ISSUE TITLE
Single Select in GridToolbarFilter

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#4926]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have search for a possible solution/implementation for the single select in GridToolbar but can't find one.

### Expected behavior 🤔

To create a filter in GridToolbarFilter using the singleselect InputComponentProps

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @simbahandiane 
To use Select component for values in filter panel, you have to set column type to `singleSelect`.
See https://mui.com/x/react-data-grid/column-definition/ for column types and this demo for a working example: https://codesandbox.io/s/gtej1q?file=/demo.tsx for a demo (try to filter "Country" column)
