### ISSUE TITLE
[DatePicker] `className`s provided via prop are never applied to root element

### ISSUE THREAD

**Issue by cwwrussell** [mui/mui-x#4942]
Not much more to say; the `className` prop is destructured in preparation to apply to the component but never gets used.

https://github.com/mui-org/material-ui/blob/ad2535a8b15f76355f4559dbac02e9cb379269ba/packages/mui-lab/src/internal/pickers/Picker/Picker.tsx#L77

**Comment by Oz90** [comment]
Same issue here, the styling possibilities for the StaticDatePicker is completely messed up compared to the Desktop and Mobile ones which is rather straight forward. Hope to see a similar solution for the Static.

Side note: I created a similar issue (https://github.com/mui/mui-x/issues/5145) which could maybe be closed if someone takes a look at this existing issue?

**Comment by momentpaul** [comment]
I am also having this issue with `<StaticDatePicker className={xxx}/>`, where `className` is ignored, so I cannot apply styling.

When inspecting the source code, I see:
1. In `StaticDatePicker.tsx:80`, the `className` prop is picked up in `other`.
2. In `StaticDatePicker.tsx:86`, `other` is provided to `DateInputProps`, which we don't care about here. But it's noteworthy that it's a dead end for `className`. A code trace reveals it's not used, which is fine.
3. In `StaticDatePicker.tsx:102`, `other` is provided to `<CalendarOrClockPicker/>`.
4. In `CalendarOrClockPicker.tsx:94`, `className` is picked up, but never used. Shouldn't this be passed to both the `<CalendarPicker/>` and the `<ClockPicker/>` on lines 175 & 188?

Could we add `className` to the two components mentioned in my #4 bullet?

**Comment by jameskyker** [comment]
For those looking for a workaround on StaticDatePicker, you can wrap it in a Stack and use the sx property to override the styles. This is working for me.

**Comment by LukasTy** [comment]
@jameskyker After #6096 is released (should be today) the `className` passed to `StaticDatePicker` will be applied to `MuiPickerStaticWrapper-root` element. 😉

**Comment by segullshairbutt** [comment]
It was still an issue for me at `@mui/x-date-pickers v6.9.2` when I was trying to pass the classname to DateRangePicker. It is working for me by passing it in `slotProps` like the following: 
`slotProps: {field: { className: classes.dateFilterInputContainer }}`

**Comment by LukasTy** [comment]
@segullshairbutt 
Are you using the `DateRangePicker` with separate start and end inputs?
In that case, it looks like the provided `className` is correctly applied to the root (Stack) element.
Where would you expect the class to end up in such a case?
If you need classes on the text fields, then yes, going with your mentioned slot prop, or targeting the `textField` slot is your best answer. 👌

**Comment by segullshairbutt** [comment]
@LukasTy 
> @segullshairbutt Are you using the `DateRangePicker` with separate start and end inputs? In that case, it looks like the provided `className` is correctly applied to the root (Stack) element. Where would you expect the class to end up in such a case? If you need classes on the text fields, then yes, going with your mentioned slot prop, or targeting the `textField` slot is your best answer. 👌

I was trying to target the root by giving the `className` value, (I am calling the root which is a wrapper around both TextFields) but that wasn't successful. The class was visible if I was in **element inspector mode** on Brave browser when I clicked on an element that class was gone. This thing is also confusing for me that the class which I provided to `field` in `slotProps` is getting applied to the root element. 
I shared these details if anybody other than me is also having this problem he can find out that somebody else is also facing the same problem. I am attaching the full code below.

```
<DateRangePicker
      {...datePickerProps}
      value={values}
      onChange={(value) => handleChange(column, value)}
      slotProps={{ fieldSeparator: { children: '' }, field: { className: classes.dateFilterInputContainer } }}
      slots={{
        textField: (props) => (
          <TextField
            {...props}
            className={classes.dateField}
            size="small"
            data-test-id={TestIDs.components.table.startDate}
            inputProps={{
              ...props.inputProps,
              placeholder: '',
            }}
            InputProps={{
              ...props.InputProps,
              endAdornment: (
                <InputAdornment position="end">
                  <IconButton size="small">
                    <CalendarIcon />
                  </IconButton>
                </InputAdornment>
              ),
            }}
          />
        ),
      }}
      />
```

**Comment by LukasTy** [comment]
@segullshairbutt 
1. Please avoid defining your slot comments inline (as render functions). They will be re-rerendered on every parent render. You should create such slot components outside of the main component as pass the function/component reference.
2. `field` slot `className` does get applied to the root of the `MultiInputDateRangeField`, because that's the root Field slot component element. If you were to use a `SingleInputDateRangeField`, the `className` would have been applied to the `TextField` root component. Which element do you want to apply the `classes.dateFilterInputContainer` class to?

**Comment by segullshairbutt** [comment]
@LukasTy  
Thank you for your recommendation on the slot render function. 
Regarding your 2nd point, I want to apply the class to `MultiInputDateRangeField` and it's getting applied by using the method I mentioned above.
