### ISSUE TITLE
[data grid] Filter item created when opening filter panel through a column menu does not contain and id

### ISSUE THREAD

**Issue by maxwilsonpereira** [mui/mui-x#4943]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1- Getting the following warning as soon as I open the filter:
"MUI: One of your filtering item have no `operatorValue` provided.
This property will become required on `@mui/x-data-grid@6.X`."

2- Getting the following error by using the multi filter:
"MUI: The 'id' field is required on `filterModel.items` when you use multiple filters."

![mui error](https://user-images.githubusercontent.com/54604781/169478951-dd1dcd24-e092-4934-9231-467d1e78c4d5.JPG)

### Expected behavior 🤔

No warning / No error

### Steps to reproduce 🕹

Steps:

1. Open the filter from any column (three dots) and write "a", close the modal filter by clicking outside of the modal;
2. Open the filter from another column with the same thee dots. ERROR!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Thanks !
I will do a fix
