### ISSUE TITLE
dayjs updated from 2.13.2 to 2.14.0 requires DateFnsUtils class update

### ISSUE THREAD

**Issue by omar-kk** [mui/mui-x#4944]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Dayjs version is updated to 2.14.0 and LocalizationProvider uses it internally and it is throwing error.
LocalizationProvider does not work with dateAdapter set to DateFnsUtils.

_Type error: Types of construct signatures are incompatible.
  Type 'new ({ locale, formats, }?: { formats?: Partial<DateIOFormats<string>> | undefined; locale?: Locale | undefined; } | undefined) => DateFnsUtils' is not assignable to type 'new (...args: any) => MuiPickersAdapter<unknown>'.
    Type 'DateFnsUtils' is missing the following properties from type 'IUtils<unknown>': startOfYear, endOfYear_

### Expected behavior 🤔

LocalizationProvider should work with dateAdapter set to DateFnsUtils.

### Steps to reproduce 🕹

Steps:

1. Create LocalizationProvider with dateAdapter with dayjs version to v2.14.0.

### Context 🔦

<LocalizationProvider dateAdapter={AdapterDateFns}>
    <CalendarPicker
      minDate={now}
      date={value.date}
      onChange={handleCalendarDateChange}
    />
</LocalizationProvider>

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
From the error message, I assume it is the version of `date-io` which is too low because `startOfYear` and `endOfYear` have been added in  [v2.14.0](https://github.com/dmtrKovalenko/date-io/releases/tag/v2.14.0) 

Without a reproduction, it's hard to find the cause of you problem. Could you provide at least the version of you packages

**Comment by cherniavskii** [comment]
Hey @omar-kk 
Can you provide an example reproducing the issue? You can use this codesandbox to start: https://codesandbox.io/s/materialuipickers-material-demo-forked-lrmdyo?file=/demo.tsx

**Comment by mohsinamjad** [comment]
having the same issue

**Comment by mohsinamjad** [comment]
having same issue with '@mui/x-date-pickers/AdapterDateFns';

**Comment by cherniavskii** [comment]
@mohsinamjad can you open a new issue with a minimal reproduction example? Thanks!

**Comment by flaviendelangle** [comment]
Closing from lack of feedback
