### ISSUE TITLE
export 'onSpaceOrEnter' (imported as 'onSpaceOrEnter') was not found in '@mui/x-date-pickers/internals'

### ISSUE THREAD

**Issue by frontyard** [mui/mui-x#4946]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Upgraded all MUI libraries to their latest versions. Getting a webpack warning now:

`WARNING in ./node_modules/@mui/x-date-pickers-pro/DateRangePicker/DateRangePickerInput.js 131:17-31
export 'onSpaceOrEnter' (imported as 'onSpaceOrEnter') was not found in '@mui/x-date-pickers/internals' (possible exports: DAY_MARGIN, DayPicker, DesktopTooltipWrapper, MobileKeyboardInputView, MobileWrapper, PickerStaticWrapper, PickersArrowSwitcher, PickersCalendarHeader, PickersToolbar, PickersToolbarButton, ResponsiveTooltipWrapper, WrapperVariantContext, areDayPropsEqual, defaultReduceAnimations, executeInTheNextEventLoopTick, useCalendarState, useDefaultDates, useMaskedInput, useNextMonthDisabled, usePickerState, usePreviousMonthDisabled, useUtils, useValidation, validateDate)
 @ ./node_modules/@mui/x-date-pickers-pro/DesktopDateRangePicker/DesktopDateRangePicker.js 9:0-79 15:35-55
 @ ./node_modules/@mui/x-date-pickers-pro/DesktopDateRangePicker/index.js 1:0-66 1:0-66
 @ ./node_modules/@mui/x-date-pickers-pro/index.js 10:0-41 10:0-41`

package.json
...
        "@mui/icons-material": "~5.8.0",
        "@mui/lab": "5.0.0-alpha.82",
        "@mui/material": "~5.8.0",
        "@mui/styles": "~5.8.0",
        "@mui/utils": "~5.8.0",
        "@mui/x-data-grid-pro": "~5.11.0",
        "@mui/x-date-pickers-pro": "5.0.0-alpha.3",
        "react": "~18.1.0",
...

I looked at DateRangePickerInput.js line 6:
import { useUtils, executeInTheNextEventLoopTick, useMaskedInput, onSpaceOrEnter } from '@mui/x-date-pickers/internals';

but internals has no definition for onSpaceOrEnter.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 7.92 GB / 15.34 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.4 - /usr/bin/npm
  Managers:
    Apt: 2.0.6 - /usr/bin/apt
    Gradle: 4.4.1 - /usr/bin/gradle
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.3.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Servers:
    Nginx: 1.18.0 - /usr/sbin/nginx
  SDKs:
    Android SDK:
      API Levels: 25
      Build Tools: 19.1.0
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Java: 1.8.0_292 - /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
    Perl: 5.30.0 - /usr/bin/perl
    Python3: 3.8.10 - /usr/bin/python3
  Databases:
    MongoDB: 3.6.8 - /usr/bin/mongo
```
</details>

**Comment by flaviendelangle** [comment]
`@mui/x-any-package/internals` are not supposed to be used by third party users (that's why they are named `internals`)

We can remove them, rename them, move them at any time.
They are just here to let us share code between `@mui/x-date-pickers` and `@mui/x-date-pickers-pro`

**Comment by flaviendelangle** [comment]
@frontyard the problem is probably that you have `@mui/lab` trying to install `@mui/x-date-pickers@5.0.0-alpha.0` and `@mui/x-date-pickers-pro` trying to install `@mui/x-date-pickers@5.0.0-alpha.3`.

Try to explicitly add `@mui/x-date-pickers-pro@5.0.0-alpha.3`

The problem will go away when we will remove the pickers from the lab (hopefully in July).

**Comment by frontyard** [comment]
Yes, explicitly adding @mui/x-date-pickers@5.0.0-alpha.3 (not -pro as that was already in there) seems to have solved the issue? Thanks!
