### ISSUE TITLE
[TimePicker] Action bar buttons overlap with PM button

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#4947]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using action bar buttons with AM / PM, the two are rendered on top of each other

https://codesandbox.io/s/date-and-time-pickers-forked-9z1n5c?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/3309670/169545882-30a93e53-e297-44fa-993a-a08aa987f2fa.png)

### Expected behavior 🤔

The actions should come below the AM / PM buttons

**Comment by alexfauquette** [comment]
I'm wondering if we should not simply move the AM/PM to an upper position like this

![image](https://user-images.githubusercontent.com/45398769/169549099-f180b1c4-f1c3-4e5a-9c48-d6f7c2d6b5bf.png)

**Comment by flaviendelangle** [comment]
Could we remove to the following ?

1. Remove the `ampmInClock` prop
2. Add an example in the doc adding them in the action bar  (maybe it will require to pass new props to the action bar to make this customization easy)
