### ISSUE TITLE
[DatePicker] Input format not working correctly

### ISSUE THREAD

**Issue by LazeBear** [mui/mui-x#4976]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I set the input format to 'DD-MM-YYYY'
but the date displayed is in 'MM-DD-YYYY' format
when selecting a day greater than 12, it shows the error state (red border)

### Expected behavior 🤔

I expect the date picker to follow the input format I passed

### Steps to reproduce 🕹

[codesandbox](https://codesandbox.io/s/basicdatepicker-material-demo-forked-2p2uw0)
Steps:
1. Set the date to February (3rd)
2. expect to see (03-02-2022)
3. but instead, got (02-03-2022)
4. pick any day greater than 12
5. get red border

### Your environment 🌎

chrome

**Comment by alexfauquette** [comment]
Your state should be an date (either `new Date()` or `dayjsj` date object) not a string.


```diff
onChange={(newValue) => {
-	setValue(newValue.format("DD-MM-YYYY"));
+	setValue(newValue);
}
```

Here is the fix
https://codesandbox.io/s/basicdatepicker-material-demo-forked-je1b68?file=/demo.js

The same code with new version of pickers

https://codesandbox.io/s/basicdatepicker-material-demo-forked-vkiy5y?file=/demo.js

**Comment by flaviendelangle** [comment]
@alexfauquette I let you check if we should close this one :+1:

**Comment by alexfauquette** [comment]
Closing because the error is from a mix between string and date object which will not be possible in v6 because of the enforced type
