### ISSUE TITLE
[DatePicker] Overrides resolver from theme with slot

### ISSUE THREAD

**Issue by igortas** [mui/mui-x#4977]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have styled picker defined with `styled` function from `@mui/material`, I'm using `overridesResolver` as param, so I can override it from `theme`, but nothing changes not `paper`, not `popper` is changed.

### Expected behavior 🤔

I'm expecting that when I apply overrides from `theme`, to be able to change the style of the picker (`popper` or the `paper`) and all other parts like header or content part with the days from the picker. For now this works if I use `MuiPaper` from `theme`, but that is not desired. I like to use `MyCustomDatePicker` key in `theme`, instead `MuiPaper`.

### Steps to reproduce 🕹

Steps:

1. `MyPicker.tsx` component

`const MyDatePickerRoot = styled(
 DatePicker,
  {
    name: "MyDatePicker",
    slot: "Root",
    overridesResolver: (props, styles) => [styles.root],
  }
)``;
`

2. `MyPicker.tsx` component
`
 <MyDatePickerRoot 
        value={value}
        onChange={(newValue) => {
          setValue(newValue);
        }}
        renderInput={(params) => <TextField {...params} />}
      />
`

3. From inside `theme`:
`
const theme = createTheme({
  components: {
    MyDatePicker: {
      styleOverrides: {
        root: {
          background: "red",
        },
      },
    },
  },
});
`
4. Extend the `ThemeOptions`
`
export interface MyTheme extends ThemeOptions {
  components: Components & {
    MyDatePicker?: {
      styleOverrides?: {
        root?: CSSInterpolation;
      };
    };
  }
}
`

### Context 🔦

Custom library component, that needs to follow the rules and structure as any other component, needs to be `styled` with proper `slot`.

### Your environment 🌎

`
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "baseUrl": ".",
    "outDir": "./lib",
    "sourceMap": true,
    "strictNullChecks": true,
    "module": "esnext",
    "jsx": "react-jsx",
    "target": "es5",
    "noImplicitAny": true,
    "allowSyntheticDefaultImports": true,
    "declarationMap": true,
    "declaration": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["./src/**/*"],
  "exclude": [
    "lib",
    "node_modules",
    "setupTests.ts",
    "src/**/.test.*",
    "src/**/.stories.*"
  ]
}
`

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
