### ISSUE TITLE
[DataGridPro] - selectionModel Supercedes Custom Background Color

### ISSUE THREAD

**Issue by gvanriper** [mui/mui-x#4984]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### **Problem:**
I am trying to get a custom background and font color while utilizing the selectionModel, it breaks the row styling.

This is an exact copy of the example MUI provides only with the selectionModel setup (Be patient, it takes awhile for the data to load):

https://codesandbox.io/s/stylingrowsgrid-material-demo-selectionmodel-issue-o1548x?file=/demo.js

This is preventing me from selecting the row upon loading and via an event to switch the selected row and styling the selected row.

### **Workaround:**

For now, I can workaround this by the following:

```
  "& .super-app-theme--Open": {
     "& .MuiDataGrid-cell": {
        bgcolor: "#999AB2",
     },
  },
```

### **Expected:**
I was hoping there would be an override for the selected row. I thought something along these lines would work:

```
"& .MuiDataGrid-root .MuiDataGrid-row .Mui-selected": {
  bgcolor: (theme) =>
    getHoverBackgroundColor(
      theme.palette.info.main,
      theme.palette.mode
    )
}
```

### Steps to reproduce 🕹

Steps:

1. Follow This link: https://codesandbox.io/s/stylingrowsgrid-material-demo-selectionmodel-issue-o1548x?file=/demo.js
2. Upon load, the first row will not be properly stylized.
3. Comment out selectionModel at line # 82 and refresh the screen.
4. Upon refresh and once the data loads, it will stylize correctly. 

### Context 🔦

I'm trying to accomplish the selected row being stylized a certain way upon loading as well as when a user selects a new row.

I was hoping that the override would be more clear than utilizing .MuiDataGrid-cell to accomplish.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 14.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.76 
    @mui/icons-material: ^5.6.1 => 5.6.1 
    @mui/lab: ^5.0.0-alpha.77 => 5.0.0-alpha.77 
    @mui/material: ^5.6.1 => 5.6.1 
    @mui/private-theming:  5.6.1 
    @mui/styled-engine:  5.6.1 
    @mui/styles: ^5.6.1 => 5.6.1 
    @mui/system:  5.6.1 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid:  5.11.1 
    @mui/x-data-grid-generator: ^5.11.1 => 5.11.1 
    @mui/x-data-grid-premium:  5.11.1 
    @mui/x-data-grid-pro: ^5.11.1 => 5.11.1 
    @mui/x-date-pickers:  5.0.0-alpha.0 
    @mui/x-license-pro:  5.11.1 
    @types/react:  18.0.5 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

### Order ID 💳 (optional)

#31980

**Comment by cherniavskii** [comment]
Hey @gvanriper 
I don't think I understand the issue here.
What I see in the demo is that selected row is styled as such when `selectionModel` is provided, and doesn't have "selected" styles when `selectionModel` is missing.

Could you elaborate more on what you're trying to achieve?

**Comment by gvanriper** [comment]
> Hey @gvanriper I don't think I understand the issue here. What I see in the demo is that selected row is styled as such when `selectionModel` is provided, and doesn't have "selected" styles when `selectionModel` is missing.
> 
> Could you elaborate more on what you're trying to achieve?

@cherniavskii , hello. I'm mostly looking for consistency or a way to style the row per the demo MUI provides to work when a selectionModel is present. It looks to me that when selectionModel is present, MUI is assigning a background color that supercedes any styling I try to do.

**Comment by cherniavskii** [comment]
> It looks to me that when selectionModel is present, MUI is assigning a background color that supercedes any styling I try to do.

Right. Are you trying to avoid styles styles applied by `.Mui-selected`?

**Comment by gvanriper** [comment]
> > It looks to me that when selectionModel is present, MUI is assigning a background color that supercedes any styling I try to do.
> 
> Right. Are you trying to avoid styles styles applied by `.Mui-selected`?

@cherniavskii , sorry, yes, I'm trying to see if there is a way to override the .Mui-selected so I can put in my own styles vs what MUI assigns.

**Comment by gvanriper** [comment]
> Ok, I see a CSS issue here. There's no element with `.MuiDataGrid-root` class inside `.super-app-theme--Open` (notice nesting). This should fix the issue:
> 
> ```diff
> "& .super-app-theme--Open": {
>   // ...
> - "& .MuiDataGrid-root .MuiDataGrid-row .Mui-selected": {
> + "&.Mui-selected": {
>     bgcolor: (theme) =>
>       getHoverBackgroundColor(
>         theme.palette.info.main,
>         theme.palette.mode
>       )
>   }
> },
> ```
> 
> Working demo: https://codesandbox.io/s/stylingrowsgrid-material-demo-selectionmodel-issue-forked-uvyu9j?file=/demo.js

@cherniavskii , your example does not work once the data loads, the .Mui-selected is ignored:

![Screen Shot 2022-05-24 at 8 54 19 AM](https://user-images.githubusercontent.com/8250434/170039640-a9f737ea-3689-448c-90e0-1769ae965a53.png)

Commenting out selectionModel:

![Screen Shot 2022-05-24 at 8 55 24 AM](https://user-images.githubusercontent.com/8250434/170039828-dfe970a3-ea67-4749-8c31-1728d742319b.png)

**Comment by cherniavskii** [comment]
Yes, I've updated the demo with increased specificity to override default selected:

```diff
- "& .super-app-theme--Open": {
+ "&& .super-app-theme--Open": {
```
https://codesandbox.io/s/stylingrowsgrid-material-demo-selectionmodel-issue-forked-uvyu9j?file=/demo.js:678-708

Note, that in your demo you only override selected styles for rows with `Open` status.
If first row happens to have different status - default selected styles will be used.

**Comment by gvanriper** [comment]
@cherniavskii , ok, that will work for us. Thanks!
