### ISSUE TITLE
[pickers] Can't fire change events on DesktopDatePicker using testing-library/react

### ISSUE THREAD

**Issue by amjadalasseh** [mui/mui-x#4985]
Current Behavior 

Using fireEvent.change or userEvent.type to simulate changes doesn't trigger the onChange event. The value never changes. But when testing the component manually in the browser, it works fine.

Expected Behavior 

DesktopDatePicker value should change when using fireEvent.change or userEvent.type in tests

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a test example ? With the exact dependencies you are using, so that we can test it and see what is going wrong.

**Comment by amjadalasseh** [comment]
the component what I'm testing is 

`import { useState } from 'react';
import DesktopDatePicker from '@mui/lab/DesktopDatePicker';
import AdapterDateFns from '@mui/lab/AdapterDateFns';
import LocalizationProvider from '@mui/lab/LocalizationProvider';
import TextField from '@mui/material/TextField';
import { Skeleton } from '@mui/material';
import { format } from 'date-fns';

export interface IProps {
  label: string;
  onChange: (arg: Date | null) => void;
  inputFormat?: string;
  value?: Date | null;
  required?: boolean;
  size?: 'medium' | 'small' | undefined;
  maxDate?: Date | undefined;
  minDate?: Date | undefined;
  helperText?: string;
  loading?: boolean;
  defaultDate?: Date;
  disabled?: boolean;
}

const DatePicker = ({
  value,
  onChange,
  label,
  inputFormat,
  required,
  size,
  minDate,
  maxDate,
  helperText,
  loading,
  defaultDate,
  disabled
}: IProps) => {
  const [open, setOpen] = useState(false);

  const handleOpen = () => setOpen(true);

  const handleCloseEvent = () => {
    setOpen(false);
  };

  const inputStyle = disabled
    ? {
        backgroundColor: 'colors.gray',
        cursor: 'unset'
      }
    : {};

  const inputPropsStyle = disabled
    ? {
        color: 'gray',
        cursor: 'unset'
      }
    : {
        color: 'gray',
        cursor: 'pointer'
      };

  return (
    <>
      {loading ? (
        <Skeleton
          data-testid="specDatePickerSkeleton"
          variant="rectangular"
          height={40}
        />
      ) : (
        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <DesktopDatePicker
            label={label}
            open={open}
            defaultCalendarMonth={defaultDate}
            inputFormat={inputFormat}
            value={value}
            onChange={onChange}
            onClose={handleCloseEvent}
            minDate={minDate}
            maxDate={maxDate}
            disabled={disabled}
            renderInput={(params) => (
              <TextField
                {...params}
                fullWidth
                size={size}
                helperText={helperText}
                sx={inputStyle}
                FormHelperTextProps={{
                  sx: {
                    ml: 0,
                    fontWeight: 900
                  }
                }}
                inputProps={{
                  'data-testid': 'specDatePicker',
                  readOnly: true,
                  sx: inputPropsStyle
                }}
                InputLabelProps={{
                  sx: {
                    '& span': {
                      fontSize: '1.5rem'
                    }
                  },
                  shrink: true,
                  required
                }}
                value={value ? format(value, 'dd MMMM yyyy') : 'dd/mm/yyyy'}
                onClick={disabled ? undefined : handleOpen}
              />
            )}
          />
        </LocalizationProvider>
      )}
    </>
  );
};

DatePicker.defaultProps = {
  value: null,
  inputFormat: 'dd/MM/yyyy',
  required: false,
  size: 'medium',
  minDate: undefined,
  maxDate: undefined,
  helperText: '',
  loading: false,
  defaultDate: undefined
};

export default DatePicker;
`
I'm trying to call the trigger with 
` const field = getByTestId("Arrival Date in Area").querySelector('input');
 fireEvent.change(field, { target: { value: "30/06/2022" } })
 but the value is the same and not changing 
`

**Comment by swallowtail62** [comment]
I have the same problem.

Reproduction
https://codesandbox.io/s/mui-datepicker-react-testing-qysgoc?file=/src/DatePick.test.tsx

**Comment by LukasTy** [comment]
@amjadalasseh We have a test in [our codebase](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.test.tsx#L74) testing a very similar case (controlled changing of date).
If you are still having issues - please provide a reproducible live example.

**Comment by JuanSeBestia** [comment]
Hi, I had similar problems with TimePicker described in !5655, Also in my work I need to do some test for DatePicker, but in the test environment render the mobile version, I don't care about what version is rendered so I use the elements rendered in mobile to test my flow, I leave the flow to test it if is helpfully for you

`
    // first date 30 Jun
    getByDisplayValue(/06\/30\//);
    const input = getByRole('textbox');

    await act(async () => {
      fireEvent.click(input);
    })

    await act(async () => {
      const edit = await findByLabelText(/go to text input view/);
      fireEvent.click(edit);
    })

    await act(async () => {
      const newInput = await findByRole('textbox');
      fireEvent.change(newInput, { target: { value: '02/02/2022' } });

      const button = await findByText('OK');
      fireEvent.click(button);
    });

    // end date 02 Feb
    await findByDisplayValue(/02\/02\//);
`

**Comment by LukasTy** [comment]
Thank you @JuanSeBestia for sharing your implementation.

I've created a [PR](https://github.com/mui/mui-x/pull/5684) addressing this exact thing.
What do you think about such a change potentially breaking some tests if they relied on mobile picker version being rendered during tests?
