### ISSUE TITLE
[DataPicker] Add custom component add the bottom of the picker views

### ISSUE THREAD

**Issue by eggplants** [mui/mui-x#4988]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to add some components or tests to the buttom of DatePicker.

### Examples 🌈

![_](https://user-images.githubusercontent.com/42153744/170007786-6f5611a1-149d-4930-8144-669f2dbb2f01.png)

### Motivation 🔦

I've tried to add some tips and legends about the PickersDay's Badge. But there is no proper way to do it.

**Comment by flaviendelangle** [comment]
You can use the new `ActionBar` component slot introduced in the alpha.4

https://codesandbox.io/s/date-and-time-pickers-forked-z78kkl?file=/src/App.tsx

Note that the free space on your screen is here to fit months with up to 6 weeks (and some useless space, see #4819).
So the action bar will add additional space, it will not take the space on which you wrote in your screen.

**Comment by eggplants** [comment]
Thank you so much!

**Comment by eggplants** [comment]
Is it possible to eliminate the space between the ActionBar and the DayPicker?

![スクリーンショット 2022-06-13 15 14 41](https://user-images.githubusercontent.com/42153744/173291242-a1719f81-5b8e-465d-b06a-e3f84a4c2728.png)

**Comment by flaviendelangle** [comment]
You can have a look at https://github.com/mui/mui-x/issues/4819 and the related PR :+1:
