### ISSUE TITLE
[TimePicker] InputValue overwrite when open/close the Time Dialog 

### ISSUE THREAD

**Issue by Ethaan** [mui/mui-x#4996]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Whatever you type, as soon as you open the Dialog and close it (no change or anything) will overwrite to the last value you select on the picker

https://user-images.githubusercontent.com/8289486/160671519-f89748ce-c2c6-4a83-b25d-b30a549a6a87.mov

### Expected behavior 🤔

It should keep the value you type till you actually select another dat

### Steps to reproduce 🕹

Steps:

1. Use TimePicker Example
2. Select `10:22 AM` using the UI
3. Type `10:45 PM` using the input
4. Click Calendar Icon
5. Close Dialog
6. Date will be reverted to `10:22 AM`

### Context 🔦

Simple usage of the dialog UI

### Your environment 🌎

This can be reproduced on the Site too https://mui.com/components/time-picker/

**Comment by flaviendelangle** [comment]
I'll have a look :+1:

**Comment by alexfauquette** [comment]
Sounds like this bug has been fixed. The component in the documentation works as expected, and with the latest version, the code sandbox is working:
https://codesandbox.io/s/basicdatetimepicker-material-demo-forked-lqb9ib?file=/demo.jsx
