### ISSUE TITLE
AdapterLuxon does not work with CalendarPicker

### ISSUE THREAD

**Issue by Jiert** [mui/mui-x#5000]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the Luxon adaptors for the Calendar picker, I receive the following error:

`value.startOf is not a function`

The [demo](https://codesandbox.io/s/h97qxr?file=/demo.js) from the docs uses `date-fns`, which seems to work just fine.

I've replicated the error in a codesandbox here: https://codesandbox.io/s/subcomponentspickers-material-demo-forked-drbiei?file=/demo.js:252-270

### Expected behavior 🤔

I should not receive an error

### Steps to reproduce 🕹

Steps:

See demo: https://codesandbox.io/s/subcomponentspickers-material-demo-forked-drbiei?file=/demo.js:252-270

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: Not Found
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Not Found
    Firefox: 97.0
    Safari: 14.1.1
  npmPackages:
    @emotion/react: ^11.7.1 => 11.9.0 
    @emotion/styled: ^11.6.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.82 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/material: ^5.8.1 => 5.8.1 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.1 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-date-pickers: ^5.0.0-alpha.3 => 5.0.0-alpha.4 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.4 => 5.0.0-alpha.4 
    @mui/x-license-pro:  5.11.1 
    @types/react:  17.0.39 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

**Comment by cherniavskii** [comment]
Hey @Jiert 
If you are using Luxon adapter - you have to use Luxon as date values as well:
```diff
-const [date, setDate] = React.useState(new Date());
+const [date, setDate] = React.useState(DateTime.now());
```

Working example: https://codesandbox.io/s/subcomponentspickers-material-demo-forked-kuv02t

**Comment by Jiert** [comment]
Ah.. thanks @cherniavskii !
