### ISSUE TITLE
[data grid] Start the FAQ page

### ISSUE THREAD

**Issue by OscarDL** [mui/mui-x#5004]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

To summarize with an example situation, my row model has multiple types of data, including an object of a user with different properties (name, age, email, etc).
As per the code below, I'm rendering a cell named `student` that renders the student's name as text only:
```
{
  field: 'student', headerName: t(columnPrefix + 'student'), width: 200,
  renderCell: ({row}) => `${row.User.firstName} ${row.User.lastName}`
}
```

However, with this approach, the filter operator does not work - which makes sense in most situations where `renderCell` is used, but not here. An option on the column definition to tell the filter to search within the renderCell's data with a property would go a long way. For example:
```
{
  field: 'student', headerName: t(columnPrefix + 'student'), width: 200,
  renderCell: ({row}) => `${row.User.firstName} ${row.User.lastName}`,
  filterRenderedCellData: true
}
```

### Examples 🌈

![image](https://user-images.githubusercontent.com/27915933/170116988-e22005ff-03d7-4a88-b485-364a9d8462b3.png)

Current result:
![image](https://user-images.githubusercontent.com/27915933/170117091-8bc75f2b-bc25-4595-9688-bcca3fbfafdc.png)

Expected result:
![image](https://user-images.githubusercontent.com/27915933/170117251-1bbabe25-e1b6-4012-bcaf-5a2fc393cd99.png)

### Motivation 🔦

The goal here is to be able to filter through text-only cells that still have custom rendering (from a logic perspective) easily, without having to define custom filters all over-the-place throughout a web app - since in my case, I'm using this logic at multiple places where my app uses Data Grid.

This lack of functionality completely breaks filtering rows with text-only rendered columns. As stated previously, it makes sense this is how it works in most cases (searching through a star-rating, as one of the docs examples, would definitely make no sense) - but this would come in very useful in situations like mine.

**Comment by cherniavskii** [comment]
Hey @OscarDL 
Good news, you can achieve that by using `valueGetter` instead of `renderCell`:

```diff
- renderCell: ({row}) => `${row.User.firstName} ${row.User.lastName}`,
+ valueGetter: ({row}) => `${row.User.firstName} ${row.User.lastName}`,
```

Here's working example with filtering working out of the box: https://codesandbox.io/s/valuegettergrid-material-demo-forked-8kxts4?file=/demo.tsx

As for `renderCell` - it's designed for rendering custom cells, since it can return a React element.
See more in the docs: https://mui.com/x/react-data-grid/column-definition/#providing-content

**Comment by OscarDL** [comment]
> Hey @OscarDL Good news, you can achieve that by using `valueGetter` instead of `renderCell`:
> 
> ```diff
> - renderCell: ({row}) => `${row.User.firstName} ${row.User.lastName}`,
> + valueGetter: ({row}) => `${row.User.firstName} ${row.User.lastName}`,
> ```
> 
> Here's working example with filtering working out of the box: https://codesandbox.io/s/valuegettergrid-material-demo-forked-8kxts4?file=/demo.tsx
> 
> As for `renderCell` - it's designed for rendering custom cells, since it can return a React element. See more in the docs: https://mui.com/x/react-data-grid/column-definition/#providing-content

Thank you SO MUCH for the quick and useful reply! 🙏

I searched multiple times through the entire Data Grid API docs and asked some external help, but we hadn't found it. Maybe a short section below cell rendering on the filtering page covering this would make it easier to find.

**Comment by cherniavskii** [comment]
There's an opportunity to update docs with a section "When to use `valueGetter`, `valueFormatter`, `renderCell` etc." covering common scenarios.

**Comment by yay** [comment]
What if I want to have both `valueGetter` and `renderCell`? In that case quick filter doesn't work:

```
  const columns: BloomGridColDef[] = [
    {
      field: 'entry',
      flex: 1,
      valueGetter: params => params.row,
      renderCell: (params: GridRenderCellParams<Entry>) => {
        const { value } = params;
        return (
          <div>
            <div>{value.label}</div>
            <div>{value.text}</div>
          </div>
        );
      }
    }
  ];
```

**Comment by nrl240** [comment]
I was struggling on this topic, as well. 

I think it's important to note that if in your `renderCell` function you were accessing data via `props.value` _before_ adding a `valueGetter`, it will need to be refactored to access the data via `props.row[props.field]` _after_.

**Comment by igortas** [comment]
@OscarDL 
I have some similar question to ask;
I need this type of filtering, currently I see it only for the columns, but I need like this to filter rows in and out per cell values
![image](https://user-images.githubusercontent.com/16512083/229312031-df029f64-4ada-4f31-a004-0b86e2e70c34.png)

**Comment by cherniavskii** [comment]
@igortas Currently, you can only select specific values in the `singleSelect` column type, where the available options are known upfront - like the `Country` column in https://codesandbox.io/s/ed65g2?file=/demo.tsx

**Comment by cherniavskii** [comment]
@igortas Can you clarify what you mean by "filter per cell"?
The filters are set per column https://mui.com/x/react-data-grid/filtering/#customize-the-operators

**Comment by igortas** [comment]
Hi @cherniavskii 
I need excel like filters, we like to replace wijmo implementation. As u can can see how different wijmo filters are, not sure how much effort we need to make it custom as it is....
```
https://www.grapecity.com/wijmo/demos/Grid/Overview/react
```

**Comment by cherniavskii** [comment]
This might be a good use case for starting a FAQ page for the data grid, where we will address the most common questions with links to other docs pages and demos.
For this issue specifically, the question might sound like "What is the difference between renderCell and valueGetter? Which one should I use?"
