### ISSUE TITLE
[DataGrid] Jump while scrolling with a cell selected

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#5006]
When scrolling the grid while a cell is selected sometimes there's a jump. Here's one taken from https://mui.com/x/react-data-grid/row-grouping/#full-example

Observe the small jumps when I scroll up:

https://user-images.githubusercontent.com/42154031/169629913-fabbe316-5e81-4b19-bc43-b621e678c96e.mp4

The same happens with the `actions` column type but we don't have a demo with many rows to see it. I don't know why it happens. We already use `HTMLElement.focus({ preventScroll: true })` but it seems that it still tries to scroll to make the element visible. One thing I noticed is that it only occurs if there's a cell focused so it might be coming from the effect inside the cell. I can't reproduce it in Firefox.

https://github.com/mui/mui-x/blob/e5b548f6744f6d000436879839067055205e07db/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L179

_Originally posted by @m4theushw in https://github.com/mui/mui-x/pull/4208#discussion_r878626406_

**Comment by cherniavskii** [comment]
Closed by https://github.com/mui/mui-x/pull/6622
