### ISSUE TITLE
[question] DataGrid-Pro Edit MultiLine Text

### ISSUE THREAD

**Issue by esskar** [mui/mui-x#5007]
### Order ID 💳

210020 - ITB14401

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am having row edit mode on a datagrid pro. On column contains data with multiple lines. I want to be able to inline edit it.
Is this is supported? Is there an example?

![image](https://user-images.githubusercontent.com/65206/170189354-ac76c694-a598-4e67-8b82-e4a532cf1fb9.png)

From the screenshot it works with a custom renderEditCell, but using the ENTER key will always confirm instead of editing a new line; and i also would like to increase the height so that more lines are visible when editing.

Currently using mui 4, but mui 5 is the same behaviour.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
  npmPackages:
    @mui/x-data-grid-pro:  4.0.2
    @mui/x-license-pro:  4.0.2
    @types/react: ^17.0.2 => 17.0.45
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.2.4 => 4.6.4
```
</details>

**Comment by cherniavskii** [comment]
Hey @esskar 
Here's a working demo that utilizes textarea for editing: https://codesandbox.io/s/basiceditinggrid-material-demo-forked-11mjvc?file=/demo.tsx
Also, there's a related issue waiting for upvotes: https://github.com/mui/mui-x/issues/2851
