### ISSUE TITLE
[DataGrid] Add a css classe name to expanded rows with master-details

### ISSUE THREAD

**Issue by benja-M-1** [mui/mui-x#5017]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When expanding a row to display the detail panel, the row should have a CSS class that allows customization of cells in an expanded row.

`<div role="row" class="MuiDataGrid-row" [...]>`

`<div role="row" class="MuiDataGrid-row MuiDataGrid-expandedRow" [...]>`

### Motivation 🔦

I use the DataGrid component to create a log viewer for an application.
Sometimes the log line is too long to fit in the table so I use the master-detail feature to display the whole log line. 
When a user expanded many log lines, I want to change the background color and remove the borders of the cells from the expanded row. I can manage to add a CSS class thanks to the `onDetailPanelExpandedRowIdsChange` event subscriber but having a mui class would make the code way simpler.

### Order ID 💳 (optional)

tbd: we @ Docker have one but I don't know it yet.

**Comment by m4theushw** [comment]
For this one we need to add a pre-processor and call it before rendering the rows. Since `GridRow` is shared between the free and paid versions, the `gridDetailPanelExpandedRowIdsSelector` selector is only available in Pro/Premium.
