### ISSUE TITLE
Set focus to certain row in DataGrid

### ISSUE THREAD

**Issue by ramyab03** [mui/mui-x#5022]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We are using DataGrid community version.  The DataGrid has 100 rows being displayed without paginaton.
When user selects a row in DataGrid and clicks on a cell(with hyperlink) in that row - user is navigated to another page. From this page there is a back button to navigate back to the DataGrid. When coming back to the DataGrid - we would like to set focus on the selected row in DataGrid. Is there a way we can set focus to the selected row?

Found this - [https://mui.com/x/react-data-grid/scrolling/#apiref] but this is only available in the Pro version.

Please let us know if there is a way to do this in Community version.

### Motivation 🔦

When navigating between components - if we are not able to set focus to selected row in DataGrid, user will have to manually scroll to the selected row.

**Comment by cherniavskii** [comment]
Hey @ramyab03 
As you pointed out, scrolling to specific cell is only available in DataGrid Pro and higher.
But you can implement something similar by setting scrollTop on `.MuiDataGrid-virtualScroller` element

**Comment by Dipali-arup** [comment]
hey @cherniavskii can we set .MuiDataGrid-virtualScroller element if we have set disableVirtualization =true?
thanks.

**Comment by cherniavskii** [comment]
@Dipali-arup yes, it should work
