### ISSUE TITLE
[DataGridPro] initialState support for width.

### ISSUE THREAD

**Issue by KhachDavid** [mui/mui-x#5024]
### Order ID 💳

#44112

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Does initialState support setitng a certain width for columns in pixels? In the docs we have filter and sorting. Can we also set up the width of the columns?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @KhachDavid 
Yes, you can set column `width` in the column definition - see https://mui.com/x/react-data-grid/column-dimensions/#main-content for more info
