### ISSUE TITLE
[data grid] Can't use `autoHeight` and `autoPageSize` together

### ISSUE THREAD

**Issue by joznox** [mui/mui-x#5025]
I use the Datagrid in multiple spots throughout my app. After adjusting the setup to allow for a loading spinner, I had 3 of 4 grids go blank. The data is there, the item number on the bottom right of the grid accurately reflected the number of items in the rows array, but nothing would show and no errors given. I had autoPageSize and autoHeight both set to the grids that did not display. Removing autoPageSize fixed the issue. From what I've read through the docs, there shouldn't be any incompatibility with the 2 props, but perhaps I'm approaching it wrong? I anticipate that users will be accessing the app from desktop and mobile interfaces, so I wanted to have the grids render as dynamically as possible. 

The issue can be created on this codesandbox by adding autoPageSize to the props, refreshing the demo, the grid then goes blank.

https://codesandbox.io/s/datagrid-v5-0-1-autoheight-autopagesize-9dy64?file=/src/App.tsx

**Comment by flaviendelangle** [comment]
Duplicates #https://github.com/mui/mui-x/issues/3233


Hi,

`autoHeight` and `autoPageSize` can't be used together.
With `autoHeight`, the height of the grid depends on the size of the page
With `autoPageSize`, the size of the page depends on the height of the grid
If you set both at the same time, we have no way of picking a valid height for the grid.

I'm curious to see what is your use case.

We should add a clear warning in the doc
