### ISSUE TITLE
[DatePicker] reverts to a previous value when the date is changed with the input and the selection box is then opened

### ISSUE THREAD

**Issue by overtone1000** [mui/mui-x#5028]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

When the date in a DatePicker component is modified with the input box and then the selection view is opened, the onChange callback will be called with a previous value for the date.

### Expected behavior 🤔

After the date is changed via the input box, the selection view should only result in a call to the onChange callback function if a different date is selected.

### Steps to reproduce 🕹

Steps:
1. Change the date in a DatePicker via the input box.
2. Open the selection view.

This behavior is evident on the current [documentation page for this component](https://mui.com/x/react-date-pickers/date-picker/).  I was able to replicate this behavior by changing values in the demos. For example, in the **Responsiveness** section, type a new date into the _For desktop_ DatePicker, and then open its selection view by clicking the icon.

### Context 🔦

I noticed this bug when working on the UI for my Web App. At first I wondered whether I was using the component inappropriately. I reproduced it with the following minimal example:

```
import React, { useState } from 'react';
import { TextField, TextFieldProps } from '@mui/material';
import { DatePicker, LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';

export const TestDatePicker = () =>
{
    const [date, changeDate] = useState<Date>(new Date());
    
    const onChange = (newdate:Date, keyboardInputValue?: string) =>
    {
        changeDate(newdate);
    };

    const renderInput = (params:TextFieldProps) => {
        return <TextField {...params} />;
    }

    const retval = (
        <LocalizationProvider dateAdapter={AdapterDateFns}>
            <DatePicker
                label={"Test"} 
                value={date} 
                onChange={onChange}
                renderInput={renderInput}
                inputFormat="MM/dd/yyyy"
                showTodayButton={true}
                />
        </LocalizationProvider>
    );
    console.debug(retval);
    return retval;
}
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
  Binaries:
    Node: 12.22.9 - /usr/bin/node
    Yarn: Not Found
    npm: 8.5.1 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react:  11.9.0 
    @emotion/styled:  11.8.1 
    @mui/base:  5.0.0-alpha.75 
    @mui/icons-material: ^5.3.0 => 5.6.0 
    @mui/material: ^5.3.0 => 5.6.0 
    @mui/private-theming:  5.6.0 
    @mui/styled-engine:  5.6.0 
    @mui/styles: ^5.3.0 => 5.6.0 
    @mui/system:  5.6.0 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.0 
    @mui/x-date-pickers: ^5.0.0-alpha.0 => 5.0.0-alpha.0 
    @types/react:  17.0.44 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2
```
</details>

I was able to replicate this in both Firefox 100.0.2 and Chromium 101.0.4951.64 on Ubuntu 22.04.

**Comment by cherniavskii** [comment]
Hey @overtone1000 
I cannot reproduce the issue with `@mui/x-date-pickers@5.0.0-alpha.4`, here's a codesandbox: https://codesandbox.io/s/responsivedatepickers-material-demo-forked-87cfi7?file=/demo.tsx

I was able to reproduce it on our website first, but after page refresh I cannot longer reproduce it.
Can you confirm it works as expected with latest version?

**Comment by overtone1000** [comment]
@cherniavskii, thanks for looking into this!

I am able to replicate the error in your sandbox, but I now realize it only occurs when a date on or before 12/30/2016 is input! If the input date is 12/31/2016 or after, the component behaves as expected.

**Comment by cherniavskii** [comment]
In the demo, there's `minDate` set:

```tsx
minDate={new Date("2017-01-01")}
```

So I would say it's an expected behavior:

https://user-images.githubusercontent.com/13808724/170764993-35e9824e-4c26-4c10-a675-7b9af0a1f949.mov

**Comment by overtone1000** [comment]
Sorry, I missed the `minDate` prop in your demo. In the `5.0.0-alpha.4` docs, the examples demonstrating this behavior also had this prop set, and I missed it there as well. The erroneous behavior I was observing with version `5.0.0-alpha.0` and the expected behavior with the `minDate` prop set were similar, and I confused the two. I should have run my original test `5.0.0-alpha.4` before creating this issue. My apologies and thanks for your help!
