### ISSUE TITLE
@mui/x-data-grid-premium Error on export as excel

### ISSUE THREAD

**Issue by timur-ul-hasan** [mui/mui-x#5035]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On export as excel in the table following errors are found in the browser console.
```
excelSerializer.js:182 Uncaught (in promise) TypeError: excelJS.Workbook is not a constructor
    at buildExcel (excelSerializer.js:182:20)
    at async Object.exportDataAsExcel (useGridExcelExport.js:41:22)
```

![image](https://user-images.githubusercontent.com/18367278/170823224-4c91c9e5-978c-485a-8faa-d1ff558c90ef.png)

### Expected behavior 🤔

On export as excel in the table file should be properly exported

### Steps to reproduce 🕹

https://codesandbox.io/s/data-grid-pro-forked-oy57pp?file=/src/App.jsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by timur-ul-hasan** [comment]
I am getting this issue using vite.

**Comment by alexfauquette** [comment]
Your reproduction case does not reproduce the bug. I pressed "Download as Excel" and it did no display any error in the console

This could be a problem in ExcelJS itself https://github.com/exceljs/exceljs/issues/960

Without a reproduction of the error, I can not help you

**Comment by destegabry** [comment]
I confirm that this error happens on vite

**Comment by alexfauquette** [comment]
Thanks for the reproduction case @SpiderRam 🙏

I'm not familiar with remix and vite. But from the debugger, I can observe that the excelJs is imported, but set into a `default` property. So the constructor is not `excelJS.Workbook` but `excelJS.default.Workbook`

![Screenshot from 2022-06-15 11-23-26](https://user-images.githubusercontent.com/45398769/173793397-70b6d395-3d00-414c-9bed-c155b85e1755.png)

This seems to be related to some pre-bundling made by vite/remix: https://github.com/vitejs/vite/issues/4553#issuecomment-895812524

**Comment by alexfauquette** [comment]
I tried with the package generated by PR #5207 seems to fix the problem on Remix

@timur-ul-hasan or @destegabry could you check if it solves your's too?

Here is the line to put in package.json to import the fixed version
```js
// package.json
"@mui/x-data-grid-premium": "https://pkg.csb.dev/mui/mui-x/commit/d8b4d000/@mui/x-data-grid-premium",
```
