### ISSUE TITLE
[data grid] Columns disappear after "Hide All" and resize

### ISSUE THREAD

**Issue by Marcin59** [mui/mui-x#5047]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After clicking "Hide All"(in ToolbarColumns) and showing some columns without using the "Show All" button, columns disappear after resizing. It only happens when the columnVisibilityModel is chosen in initialState. Is it a bug or just a problem with my code?  

The problem comes after adding this:

![image_2022-05-29_213609791](https://user-images.githubusercontent.com/53148689/170888460-f3076f9b-2a5c-47ba-beeb-ba7d8883113e.png)

Example(https://stackblitz.com/edit/react-ts-5pfnmd?file=App.tsx): 

https://user-images.githubusercontent.com/53148689/170888472-479eb895-42f5-4300-997f-50411f3983bb.mp4

### Steps to reproduce 🕹

Steps:

1. Open: https://stackblitz.com/edit/react-ts-5pfnmd?file=App.tsx.
2. Click “Columns”
3. Click “Hide All”
4. Click “name” checkbox to show that column
5. Try resize the “name” column

### Context 🔦

I ran into the problem when I tried to do a save and reset of the current state of the grid

### Your environment 🌎

  Opera GX
  "@mui/core": "^5.0.0-alpha.54",
   "@mui/icons-material": "^5.6.2",
   "@mui/material": "^5.5.1",
   "@mui/x-data-grid": "^5.6.1",
   "@mui/x-data-grid-pro": "^5.11.1",

### Order ID 💳 (optional)

240359

**Comment by flaviendelangle** [comment]
Hi,

Thanks for your reproduction case
I think the bug is in our resizing plugin which uses an outdated version of the column.
I'll investigate :+1:
