### ISSUE TITLE
How to implement linked singleSelect while using custom component ( renderEditCell ). 

### ISSUE THREAD

**Issue by adharshmk96** [mui/mui-x#5051]
I've implemented linked singleSelect with the following example https://mui.com/x/react-data-grid/editing/#linked-fields

On top of that, I've tried to make it a custom component by changing the renderEditCell as per, https://mui.com/x/react-data-grid/editing/#create-your-own-edit-component

I'm unable to find a way to find the selected option of another component to calculate and change the available options of second component via renderEditCell method.

example code:

```
{
      field: 'type',
      headerName: 'Type auto',
      type: 'singleSelect',
      editable: true,
      renderEditCell: (params: GridRenderEditCellParams) => {
        const valueOptions = ['Income', 'Expense'] 
        return (
          <Autocomplete
            disablePortal
            options={valueOptions}
            sx={{ width: params.colDef.width }}
            renderInput={(params) => <TextField {...params} label="Type" />}
          />
        )
      }
    },
 
{
      field: 'accounta',
      headerName: 'Account auto',
      type: 'singleSelect',
      valueOptions: ({ row }) => {
        if (!row) {
          return [
            'Sales',
            'Investments',
            'Ads',
            'Taxes',
            'Payroll',
            'Utilities',
            'Marketing',
          ];
        }

        return row.type === 'Income'
          ? ['Sales', 'Investments', 'Ads']
          : ['Taxes', 'Payroll', 'Utilities', 'Marketing'];
      },
      editable: true,
      renderEditCell: (params: GridRenderEditCellParams) => {
        // How to get the options here ? 
       // valueOptions = ???
        return (
          <Autocomplete
            disablePortal
            options={valueOptions}
            sx={{ width: params.colDef.width }}
            renderInput={(params) => <TextField {...params} label="Type" />}
          />
        )
      }
    },
```

**Comment by m4theushw** [comment]
> I'm unable to find a way to find the selected option of another component to calculate and change the available options of second component via renderEditCell method.

You can access the row being edited with the new values by using the `row` prop passed to `renderEditCell`.

**Comment by adharshmk96** [comment]
> > I'm unable to find a way to find the selected option of another component to calculate and change the available options of second component via renderEditCell method.
> 
> You can access the row being edited with the new values by using the `row` prop passed to `renderEditCell`.

I've tried getting the value of linked component via row but, It's not serving my purpose of changing the options for component B depending on the value selected on component A. ( when we change values its not reflecting )

**Comment by m4theushw** [comment]
Could you create a CodeSandbox with what you already achieved?

**Comment by adharshmk96** [comment]
https://codesandbox.io/s/jovial-sunset-t8gzw7?file=/src/App.js

**Comment by joserodolfofreitas** [comment]
Hi @adharshmk96,

You need to update the row data "onChange", so the change on the input impacts the other fields of the row.

I forked your example with a way to achieve it.
https://codesandbox.io/s/linked-autocompletes-o47mk3?file=/src/App.js

I hope this helps.
