### ISSUE TITLE
[pickers] Keyboard based input fields for date format with space not working

### ISSUE THREAD

**Issue by david-ic3** [mui/mui-x#5058]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Define an input format with spaces., i.e.  {"dd MMM yyyy"}. It's not possible to enter manually dates with space characters. 

The initial date is fine if defined, and copy&paste the whole date work as well.

Something like :

```
<MobileDateRangePicker
          inputFormat={"dd MMM yyyy"}
          startText="ic3 rocks !"
          value={value}
          onChange={(newValue) => setValue(newValue) }
          renderInput={(startProps, endProps) => (
            <React.Fragment>
              <TextField {...startProps} />
              <Box sx={{ mx: 2 }}> to </Box>
              <TextField {...endProps} />
            </React.Fragment>
          )}
        />
```

### Expected behavior 🤔

Would expect for the end user to be able to press the space key.

### Steps to reproduce 🕹

Steps:

https://codesandbox.io/s/responsivedaterangepicker-material-demo-forked-nhy628

1. Try to enter in 'ic3 rocks' field a date '23 Feb 2020' with spaces (NO copy & paste)

### Order ID 💳 (optional)

#19458

**Comment by alexfauquette** [comment]
If I get it correctly, what's blocking you from entering the date with a space is that <kbd>Space</kbd> opens the popper. wich make sense on desktop, but not on mobile

By curiosity, I try your code on my smartphone (next QR code if you want to try it too) surprisingly, I can press <kbd>Space</kbd> without opening the popper

![QR code to code sandbox](https://user-images.githubusercontent.com/45398769/171399599-93d73d9d-1472-4ef5-9fb6-757ed52cdc88.png)

**Comment by david-ic3** [comment]
Tried on my iPhone, the position of the Popper it's hidden. It's not in the middle of my screen but the middle of the page. It also opens on space and has the same issue.

To me it's surprising this open Popper on space, click ?

**Comment by alexfauquette** [comment]
Thanks for the clarification, I forget this way of editing.
 
About the accessibility, it is that W3 standard to open the dialogue on <kbd>space</kbd> or <kbd>enter</kbd>
https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190814/examples/dialog-modal/datepicker-dialog.html

For the specific case of "Click on the pencil" we should be able to remove what's blocking (probably a `preventDefault` that should not be set when popper is already open)

On the same topic, the only website using space in date input I know is [google flights](https://www.google.com/travel/flights) but to do that they have a very special behavior: the popper is open as long as the input as the focus. Such that you do not need to press <kbd>space</kbd> to open the popper

**Comment by david-ic3** [comment]
_About the autocomplete, the space does not open the menu. It starts the autocomplete search with the value " "_

you are right. thanks

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.
