### ISSUE TITLE
[pickers] Demo LocalizedTimePicker crashes

### ISSUE THREAD

**Issue by ddiatlov** [mui/mui-x#5075]
- [x] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LocalizedTimePicker%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-date-pickers/time-picker/
2. ??
3. demo *LocalizedTimePicker* crashes
4. Delete every existing digit in the field. This is happens in all time pickers.

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v5.9.0  |
| netlify deploy | undefined |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 |

**Comment by ddiatlov** [comment]
@mui/x-date-pickers@5.0.0-alpha.1

After updating to @5.0.0-alpha.2, I can confirm that the bug is gone.
thanks! :)

**Comment by flaviendelangle** [comment]
The project being a lot more maintained since April, I advise you to upgrade to the last version, or at least the `alpha.3` which has a lot of bug fixes (you can have a look at the changelog for more details) :+1:
