### ISSUE TITLE
Configurable delay or button for "onFilterModelChange" to trigger

### ISSUE THREAD

**Issue by SusiKette** [mui/mui-x#5078]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The DataGrid search bar seems to trigger "onFilterModelChange" when you don't input new character for a short while. Would it be possible to add a custom delay for how long to wait before the event is triggered? Another good option would be to have an "Apply" button to trigger the event.

The main reason I need this is for server side filtering, and doing a new query when "onFilterModelChange" is triggered most likely will result in unnecessary http requests with incomplete filtering begin sent to the backend.

**Comment by alexfauquette** [comment]
When talking about DataGrid search bar, do you talk about the filter panel or the quick filter input?

- For **quick filter** you can pass a prop to modify the delay before updating `onFilterModelChange`

- For **filter panel** only text fields and date fields input have a 500ms delay which is for now hard coded
	- https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx#L53:L53
	- https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputDate.tsx#L12:L12

**Comment by SusiKette** [comment]
I'm working with the `<GridToolbarQuickFilter/>` component.

Is there a way to keep the search term in the search field when the page rerenders (in this case when I do a new query to the database, because we use server side pagination and filtering)? I can keep the value between renders, but setting the default value to the search field (when it is not `undefined`) causes the user not begin able to change it anymore even if the page doesn't rerender.

**Comment by alexfauquette** [comment]
Not sure to understand what you mean.

Some users had a problem due to un-sync between their filter model and the input #4921 maybe the content of this issue could help you.

If your problem is different, could you provide a minimal example because for now, I don't know how to reproduce it

**Comment by SusiKette** [comment]
Right now in my `<DataGrid>` I have the `<GridToolBarQuickFilter>` and a `<Button>` components. When you input value to the quick filter's search bar the `onFilterModelChange` event saves the filter to React's useRef variable. When the button is pressed the useRef variable is copied to useState variable, which causes the page to rerender. During the rerender a http request is sent to a backend with the applied filter to get new data for the grid. However, when the page rerenders, the quick filter's search bar forgets the value it had. This seems to be quite normal with React, however if I try to set the filter back with the `value` prop, it gets stuck to any non-`undefined` value and cannot be changed anymore.

**Comment by cherniavskii** [comment]
Hey @SusiKette 
> However, when the page rerenders, the quick filter's search bar forgets the value it had

Can you open a new issue with a minimal example reproducing the problem?
Thanks!

**Comment by MBilalShafi** [comment]
@SusiKette Are you still facing this issue? We recently introduced a prop called [filterDebounceMs](https://github.com/mui/mui-x/blob/ef40e06213d4721c51d498328f4fadf8e545b3e7/packages/x-data-grid/src/models/props/DataGridProps.ts#L221) which could be used to delay the execution of filtering process after a key stroke.

Could that work for you?
