### ISSUE TITLE
[DateRangePicker] Can't disable dates

### ISSUE THREAD

**Issue by destegabry** [mui/mui-x#5080]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Dates are not being disabled using `minDate`, `maxDate` or `shouldDisableDate` props.

Specified dates are enabled, but selecting them will show the error status on the TextField component.

### Expected behavior 🤔

Disabled dates are disabled

### Steps to reproduce 🕹

Steps:

1. Head to the [DateRangePicker documentation ("Disabling dates" section)](https://mui.com/x/react-date-pickers/date-range-picker/#disabling-dates)
2. Select a start date
3. Dates 4 weeks after the selected start date should be disabled, but they aren't
4. Select a date 5 weeks in the future, the "End" field will display an error state

### Context 🔦

I'm trying to disable unavailable dates.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.83 
    @mui/lab: ^5.0.0-alpha.84 => 5.0.0-alpha.84 
    @mui/material: ^5.8.2 => 5.8.2 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.2 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.12.0 
    @mui/x-data-grid-premium: ^5.12.0 => 5.12.0 
    @mui/x-data-grid-pro:  5.12.0 
    @mui/x-date-pickers: ^5.0.0-alpha.5 => 5.0.0-alpha.5 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.5 => 5.0.0-alpha.5 
    @mui/x-license-pro:  5.12.0 
    @types/react: ^18.0.10 => 18.0.10 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript: ^4.7.2 => 4.7.2 
```
</details>

### Order ID 💳 (optional)

44740

**Comment by flaviendelangle** [comment]
It seems to work in `@mui/x-date-pickers@alpha.4`
The bug was introduced in https://github.com/mui/mui-x/pull/4814

I will do a fix for the next release, sorry for the inconvenience
