### ISSUE TITLE
[DataGrid] tabs switching breaks DataGrid columns.

### ISSUE THREAD

**Issue by ShadiBlitz** [mui/mui-x#5085]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have 3 datagrid, each one is in it's own tab. Sometimes when i switch to a different tab, only 3 columns show up. When i open the 'Show Columns' menu, all the columns appear to be switched on but only 3 can be seen on the data grid.

### Expected behavior 🤔

show all columns normally.

### Steps to reproduce 🕹

[https://codesandbox.io/s/basictabs-demo-material-ui-forked-w0vq5n?file=/demo.tsx](https://codesandbox.io/s/basictabs-demo-material-ui-forked-w0vq5n?file=/demo.tsx)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
We need to investigate a bit more this bug. It only happens with React 18. I noticed that the root div has zero width when the tab is changed, so the only columns rendered are those from the buffer.

![image](https://user-images.githubusercontent.com/42154031/171515853-695b77ba-4a3e-4b5c-91fe-fbbd4faa1e3f.png)

**Comment by ShadiBlitz** [comment]
> It only happens with React 18.

I have react 17 and still having the same issue.

**Comment by m4theushw** [comment]
I tested with React 17 and `ReactDOM.render` and I can't see the bug: https://codesandbox.io/s/basictabs-demo-material-ui-forked-0ukzdz?file=/demo.tsx

Could you provide a new production using React 17? It will be easier to debug and fix the bug in this version.

**Comment by ShadiBlitz** [comment]
Thank you for reply. the bug happens in react 17 but not always, maybe 1 out of every 30 tries or something like that. and sometimes random.
