### ISSUE TITLE
Cannot clear invalid date from Datepicker component

### ISSUE THREAD

**Issue by harshakakumanu** [mui/mui-x#5086]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When you enter the invalid date inside the Datepicker I couldnt clear it by setting it to null. I made a codesandbox. Here is the link

### Expected behavior 🤔

When you set the value to null it should clear the datepicker

### Steps to reproduce 🕹

Please enter the invalid date by keyboard and click on clear button

Code sandbox link  https://codesandbox.io/s/basicdatepicker-material-demo-forked-qf6qzh?file=/demo.js

### Context 🔦

I am trying to clear the datepicker on click of the button

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #https://github.com/mui/mui-x/issues/4870
Fixed by #https://github.com/mui/mui-x/pull/4486

The fix will be released in the next version :+1:
