### ISSUE TITLE
[pickers] Default calendar month does not take `minDate` and `maxDate` into account when `value = null`

### ISSUE THREAD

**Issue by zzlatkov92** [mui/mui-x#5091]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When `minDate` is set to a future date (E.g newDate('2033')) and `value` is set as `null`, when you **open the date picker** the calendar will **render the today date**, instead of moving the calendar to the `minDate`.

### Expected behavior 🤔

Calendar should render the `minDate` instead of the **today date**.

### Steps to reproduce 🕹

Steps:

1. Render DatePicker
2. Set value as null
3. Set minDate as future date (E.g new Date('2033')
4. Open the DatePicker
5. The calendar will render today date as initial view

You can find a codesanbox example [here](https://codesandbox.io/s/basicdatepicker-material-demo-forked-f6tf97?file=/demo.js) 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.30)
```
</details>

**Comment by flaviendelangle** [comment]
You can use the `defaultCalendarMonth` to open your picker to 2033 instead of today's month
See this example https://codesandbox.io/s/date-and-time-pickers-forked-4z6vcc?file=/src/App.tsx

But I agree that the default behavior should probably to open the 1st month after `minDate` / 1st month before `maxDate` 

@alexfauquette do you see a reason not to do this change ?

**Comment by alexfauquette** [comment]
I agree. Opening the closest month to today which is in the valid date range sounds to be a good idea
