### ISSUE TITLE
[data grid] Rows reordering doesn't work when using `getRowId`

### ISSUE THREAD

**Issue by SergeOlabin** [mui/mui-x#5092]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Reordering does NOT work, (`onRowOrderChange` is NOT fired)

### Expected behavior 🤔

Reordering works, (`onRowOrderChange` is fired)

### Steps to reproduce 🕹

Steps:

https://codesandbox.io/s/roworderinggrid-material-demo-forked-gt3qzf?file=/demo.tsx:1618-1634

1. Setup the grid
2. your data rows don't have `id` field
3. set up `getRowId` to use another field
4. set `rowReordering` and `onRowOrderChange`
5. reorder rows

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found // idk why
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
  npmPackages:
    @emotion/react:  11.9.0
    @emotion/styled:  11.8.1
    @mui/base:  5.0.0-alpha.83
    @mui/icons-material:  5.8.2
    @mui/lab:  5.0.0-alpha.84
    @mui/material:  5.8.2
    @mui/private-theming:  5.8.0
    @mui/styled-engine:  5.8.0
    @mui/system:  5.8.2
    @mui/types:  7.1.3
    @mui/utils:  5.8.0
    @mui/x-data-grid:  5.12.0
    @mui/x-data-grid-pro:  5.12.0
    @mui/x-date-pickers:  5.0.0-alpha.1
    @mui/x-license-pro:  5.12.0
    @types/react:  18.0.10
    react:  18.1.0
    react-dom:  18.1.0
    typescript:  4.7.2
```
</details>

### Order ID 💳 (optional)

we have, but can't get atm

**Comment by flaviendelangle** [comment]
We use `params.row.id` instead of `params.id` when publishing the event ...  :grimacing: 
I'll do a quick fix that will be released next week.

**Comment by SergeOlabin** [comment]
thanks @flaviendelangle
