### ISSUE TITLE
Controlled editing using editRowsModel produces an error when you start typing in cell without double click

### ISSUE THREAD

**Issue by symbianm** [mui/mui-x#5094]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The cell editing works but the browser console produces an error:
<img width="409" alt="Screenshot 2022-06-02 at 11 19 59" src="https://user-images.githubusercontent.com/3383599/171598602-ccf632ce-75f9-43b2-b577-c456133071ce.png">

### Expected behavior 🤔

No error.

### Steps to reproduce 🕹

Try it in the official documentation: 
https://mui.com/x/react-data-grid/editing-legacy/#controlled-editing

Steps:
1. Focus on a table row
2. Start typing 
3. See an error in the browser console

### Context 🔦

Getting these errors in my [Sentry](https://sentry.io/) app and it is bugging me.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Browser Google Chrome 102.0.5005.61 on the macOS Monterey 12.3.1
 `npx @mui/envinfo` stuck and doesn't give anything.
```
</details>

**Comment by m4theushw** [comment]
Could you migrate to the [new editing API](https://mui.com/x/react-data-grid/editing/)?

The page you linked is the legacy API, which we want to remove in v6. Its controlled mode is too buggy and we can't fix it without breaking changes so we created a new API.

**Comment by symbianm** [comment]
Yeah, I started the migration. It works better in the new API.

**Comment by m4theushw** [comment]
I'll close this issue. Feel free to open another issue if you find any problem using the new API.
