### ISSUE TITLE
MUI - Strange flashing in DataGrid in some resolutions

### ISSUE THREAD

**Issue by AnastasiiaBardyuzha** [mui/mui-x#5103]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![flashing_DtataGrid](https://user-images.githubusercontent.com/58739526/171813340-974d5118-e92c-4f66-8e0f-dee9ee7455a8.gif)

### Expected behavior 🤔

![image](https://user-images.githubusercontent.com/58739526/171813529-1deac40b-1a28-494b-aed8-f355103fade2.png)

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

I am using a DataGrid component in my application. This works fine. But in some resolutions, I see this strange behavior. Has anyone come across this? Any ideas about what's going on?

### Your environment 🌎

Dependences: 
  "react": "18.1.0", 
  "@mui/lab": "^5.0.0-alpha.75", 
  "@mui/material": "^5.5.2", 
  "@mui/styles": "^5.6.2",

**Comment by m4theushw** [comment]
We only had reports of https://github.com/mui/mui-x/issues/4253, not sure if it's the same problem. Could you provide a minimal reproduction and the resolution where you see the flashing?
