### ISSUE TITLE
[DatagridPro] How to save apiRef.current right before DataGrid component unmounts

### ISSUE THREAD

**Issue by KhachDavid** [mui/mui-x#5109]
### Order ID 💳

#44112

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

As the title says, my goal is to save the apiRef right before DataGridPro component unmounts in the demo linked below. Currently, I am using the fallback function of useEffect in a wrapper component. However, at the time when fallback is being called, apiRef.current is already null (see the console log). 

A solution, I have in mind is using listeners to keep track of the apiRef changes that I care about. A concern about this solution is that it might impact the performance, as callback listeners might be constantly called (e.g. columnWdithResizeListener). 

What might be a better way of keeping track of apiRef? 

[Demo](https://stackblitz.com/edit/react-ts-rce4tb?file=demo.jsx)

<details>
  <summary>Console Log</summary>
<img width="514" alt="image" src="https://user-images.githubusercontent.com/65775837/171881400-3819e486-f530-4a7d-b398-f527e2d67966.png">

</details

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
The `apiRef` is null because it's destroyed even before the unmount function of the effect runs. As alternative I would suggest to not try to track when the grid is unmounted, but instead run the action you want before updating the state that unmounts the grid.

Example: https://stackblitz.com/edit/react-ts-2y46jb?file=demo.jsx,App.jsx

Basically we do:

```tsx
<Button 
  onClick={() => {
    if (isMounted) {
      // access apiRef.current
    }
    setMounted(!isMounted);
  })
/>
```

**Comment by KhachDavid** [comment]
Hey Matheus, 

Thank you for the answer. I think this will work. Do you think this solution is scalable in a big project, when there are multiple buttons that can unmount the DataGrid wrapper component?
