### ISSUE TITLE
[DateRangePicker] Disabled dates are still selectable

### ISSUE THREAD

**Issue by TimESQuit** [mui/mui-x#5111]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. Use the `shouldDisableDate` function or `minDate` & `maxDate` props to create disabled dates. 
2. Choose an intended disabled date as a start or end date.
3. Notice that the calendar shows the date with a normal appearance (not greyed out) and is selectable.
4. After selecting both a start and end date, notice that the textfield with the intended disabled date now has an error state. 

Note: this is the behavior in Alpha.5; Alpha.4 does not seem to have the same problem.

### Expected behavior 🤔

The calendar days should be greyed out and not selectable.

### Steps to reproduce 🕹

https://codesandbox.io/s/daterangepicker-alpha-5-react-17-0-2-d7fp9x

Choose one of the dates from `disableTheseDates`, or outside the bounds of the `minDate` & `maxDate`, as a start or end date. Then follow the steps in 'Current behavior.'

### Your environment 🌎

Accessed the codesandbox above using Chrome: `101.0.4951.64 (Official Build) (arm64)` 

### Order ID 💳 (optional)

39843

**Comment by yujishiramoto-tier4** [comment]
https://github.com/mui/mui-x/issues/5111

issue が上がっているようです。ただこちら最新の alpha.5 のバグのようで alpha.4 では再現しないと記載されています。
issue に貼ってあるサンプルを見ると、 alpha.4 に変更すると機能していそうですが一度見て頂けますでしょうか :bow:
