### ISSUE TITLE
[pickers] Not possible to provide custom styling to the DesktopDatePicker component

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [mui/mui-x#5112]
I have updated to the latest @mui/material v5.0.1, used the DesktopDatePicker component and tried to provide custom styling to it (different background-color, font color, date-selection color and a different input field style).

Using the renderInput to render our custom InputField component was successfull, however I was not able to style the elements from the Modals that show up (a.k.a MuiCalendarPicker).

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I have used the following methods which were unsuccessful:

1. Wrap the DesktopDatePicker or its LocalizationProvider wrapper component with the ThemeProvider using a custom theme.
2. Using the style prop in the DesktopDatePicker
3. Using the sx prop in the DesktopDatePicker (trying to select the MuiCalendarPicker component with `sx={{'& .MuiCalendarPicker-root':{backgroundColor: 'purple'}}}`
4. Using the PopperProps (this only controls an overlay behind the actual MuiCalendarPicker)
5. Using a custom classname and selecting `'& .MuiCalendarPicker-root'` or `'& .MuiCalendarPicker'` to style.

## Expected Behavior 🤔

The styling of the MuiCalendarPicker or the styling of the Modal contents in general should change

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```

   System:
    OS: macOS 11.6
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.1 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.0
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled:  10.0.27 
    @mui/core:  5.0.0-alpha.48 
    @mui/lab: ^5.0.0-alpha.48 => 5.0.0-alpha.48 
    @mui/material: ^5.0.1 => 5.0.1 
    @mui/private-theming:  5.0.1 
    @mui/styled-engine:  5.0.1 
    @mui/styled-engine-sc: ^5.0.0 => 5.0.0 
    @mui/system:  5.0.1 
    @mui/types:  7.0.0 
    @mui/utils:  5.0.1 
    @types/react: 17.0.24 => 17.0.24 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    styled-components: ^5.3.1 => 5.3.1 
    typescript: 4.4.3 => 4.4.3 
    
    The browser used is Google Chrome v94
    Next.js v11.1.2 is also used
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #6218, we are discussing this problem there 👍
