### ISSUE TITLE
'actions' column vs rendering action buttons through renderCell()

### ISSUE THREAD

**Issue by PraveenPeri** [mui/mui-x#5128]
### Order ID 💳

33625

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Just noticed in the documentation that a column definition in the datagrid can be of type 'actions' and you could define a getActions() method on it. Wondering what's advantage of it over rendering action icons through renderCell()

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
The main advantage is the integration with other features:
- do not propose to filter according to the value of this column
- same on sorting
- manage focus inside of the cell

**Comment by PraveenPeri** [comment]
@alexfauquette Thanks for the response! I noticed a couple of things about this. Let me know if I need to open an issue instead.
1. GridActionsCellItem doesn't render buttons with a tooltip - not accessible
2. There is no documentation on this API

**Comment by PraveenPeri** [comment]
@alexfauquette Guess it was hard for me to find it :). I only got to know about `GridActionsCellItem` because I stumbled upon it when looking at the example for columns pinning. Anyway, this is not a pressing issue. Thanks for the pointers!
