### ISSUE TITLE
GridToolbar Quick Filter is not working

### ISSUE THREAD

**Issue by Utkarshk7** [mui/mui-x#5129]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I want a quick filter in datagrid pro. I followed the documentation as per:
https://mui.com/x/react-data-grid/filtering/#quick-filter

However the input search field **does not appear** for **standard GridToolbar**.

Also, i tried using custom toolbar. As per the documentation, i have to use "GridToolbarQuickFilter" component for custom toolbar. I am unable to import it using:
import {
  GridToolbarQuickFilter
} from "@mui/x-data-grid";

### Expected behavior 🤔

1. Search input field should appear in the tool bar
2. Import statement should work

### Steps to reproduce 🕹

Steps:
**Problem 1:**
1. Import DataGridPro in the code
2. Used the below code inside "DataGridPro" component to get quick filter option:

components={{ Toolbar: GridToolbar }}
          componentsProps={{
            toolbar: {
              showQuickFilter: true,
              quickFilterProps: { debounceMs: 500 },
            },
          }}

3. Expected the quick filter input search field in the tool bar. **But nothing appears**

**Problem 2:**
The documentation as per the link https://mui.com/x/react-data-grid/filtering/#quick-filter says that you can add the 
 "GridToolbarQuickFilter" component to your custom toolbar.

When i try to use this component, i have to import it from the mui library. I use below import statement:
import {
  GridToolbarQuickFilter
} from "@mui/x-data-grid";

I however get below error-
**Attempted import error: 'GridToolbarQuickFilter' is not exported from '@mui/x-data-grid'.**

Can you please let me know the correct library for import ?

### Context 🔦

I am trying to show the quick filter in datagrid pro.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#39429

**Comment by Utkarshk7** [comment]
Thanks a ton. The version was the issue!

**Comment by Glaysonvisgueira** [comment]
@alexfauquette thanks, you saved me!

**Comment by sirajalam049** [comment]
I don't know if anybody has that case.
I had to show the cell value by some logic and for that I was using renderCell method. MUI can't find the text to filter in that case. MUI provides as function valueGetter that returns the text that will be displayed, and using that search will work along with render cell.

And if render cell is just returning a text you can simply use only valueGetter and no need to use renderCell for that.
