### ISSUE TITLE
[pickers] How to import `AdapterDateFns` when using pro plan ?

### ISSUE THREAD

**Issue by nandeshwarshubh** [mui/mui-x#5132]
### Order ID 💳

44828

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

From where do I import AdapterDateFns, since we have the pro version I think it should be like - 
`import { AdapterDateFns } from "@mui/x-date-pickers-pro/AdapterDateFns";`

But this is not working.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
You can use the MIT library to import adapter
```js
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
```
 --- 
 
 
The doc probably needs some improvement on this part. The only mention of this point is [here](https://mui.com/x/react-date-pickers/migration-lab/#2-run-the-code-mod) (a small sentence at the end of a migration page)

> Components of the Community Plan such as <DatePicker /> can be imported from both @mui/x-date-pickers-pro and @mui/x-date-pickers. Only [date adapters](https://mui.com/x/react-date-pickers/getting-started/#setup) such as AdapterDayjs can only be imported from @mui/x-date-pickers/[adapterName].

**Comment by flaviendelangle** [comment]
We could probably re-export the Adapters from the pro package with nested import (`import { AdapterDateFns } from '@mui/x-date-pickers-pro/AdapterDateFns'`)

Because, unlike other imports, those are not re-exporter from the root (you can't do `import { AdapterDateFns } from '@mui/date-pickers-pro'` because we don't want to bundle the date libraries when not using the adapter).

**Comment by nandeshwarshubh** [comment]
> You can use the MIT library to import adapter
> 
> ```js
> import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
> ```
> 
> The doc probably needs some improvement on this part. The only mention of this point is [here](https://mui.com/x/react-date-pickers/migration-lab/#2-run-the-code-mod) (a small sentence at the end of a migration page)
> 
> > Components of the Community Plan such as  can be imported from both @mui/x-date-pickers-pro and @mui/x-date-pickers. Only [date adapters](https://mui.com/x/react-date-pickers/getting-started/#setup) such as AdapterDayjs can only be imported from @mui/x-date-pickers/[adapterName].

This worked! But why should we install @mui/x-date-pickers, we should be able to do this from @mui/x-date-pickers-pro package as well. Going ahead with development for now! Thanks!

**Comment by flaviendelangle** [comment]
> But why should we install @mui/x-date-pickers, we should be able to do this from @mui/x-date-pickers-pro package as well. Going ahead with development for now! Thanks!

The basic idea was: we don't want to create dozens of folders inside the pro package just re-exporting the community components just to be able to do `import { DatePicker } from '@mui/x-date-pickers-pro/DatePicker'`. Users could do `import { DatePicker } from '@mui/x-date-pickers-pro'` or if they really want dev tree shaking `import { DatePicker } from '@mui/x-date-pickers/DatePicker'`.

But the adapters (I think they are the only one), we don't export them from the root of `@mui/x-date-pickers` and thus they are not re-exported from the root of `@mui/x-date-pickers-pro`.

I'll add the "enhancement" label for that one

**Comment by noherczeg** [comment]
Creating a dedicated npm package for adapters whould solve the problem, no?

**Comment by flaviendelangle** [comment]
Which problem are you talking about @noherczeg ?
The problem described on this issue has been already solved.
