### ISSUE TITLE
RangeError: Format string contains an unescaped latin alphabet character `f`

### ISSUE THREAD

**Issue by austinjohnson** [mui/mui-x#5134]
**Versions**:
"@mui/x-date-pickers": "^5.0.0-alpha.5",
"@date-io/date-fns": "^1.3.13",
"date-fns": "^2.8.1",

When running jest tests involving DesktopDatePicker or DesktopTimePicker, I'm receiving an error: `RangeError: Format string contains an unescaped Latin alphabet character f.` I tried downgrading the packages, but this did not fix the issue.

**Comment by cherniavskii** [comment]
Hey @austinjohnson 
Can you provide a minimal example reproducing the issue? You can start with this demo: https://codesandbox.io/s/hkfkiu?file=/demo.tsx

Also, might be related: https://github.com/date-fns/date-fns/issues/1857
