### ISSUE TITLE
[data grid] Unable to override the icon in `GridToolbarFilterButton`

### ISSUE THREAD

**Issue by stellaliao01** [mui/mui-x#5136]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I created a custom component for GridToolbar. I am trying to override the icons for GridToolbarColumnsButton, GridToolbarFilterButton, GridToolbarExport, GridToolbarDensitySelector. GridToolbarFilterButton is the only component that isn't allowing the override.

### Expected behavior 🤔

 The expected behavior is for all the icons to be overwritten. 

### Steps to reproduce 🕹

[Here is the codesandbox
](https://codesandbox.io/s/data-grid-pro-forked-8suydg?file=/src/App.tsx)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

**Comment by DanailH** [comment]
Hi @stellaliao01 thanks for raising this. It's not working because the `GridToolbarFilterButton` is wrapped in a `Tooltip` component (this is because if you have active filters there are badges that indicate this).
To overwrite the icon in the actual button you need to use the `componentsProps`.

```tsx
<GridToolbarFilterButton
  componentsProps={{
    button: {
      startIcon: (
        <IconButton>
          <FilterAltIcon />
        </IconButton>
      )
    }
  }}
/>
```

I've also updated your example with the solution -> https://codesandbox.io/s/data-grid-pro-forked-mri2r6?file=/src/App.tsx

**Comment by stellaliao01** [comment]
@DanailH Thank you so much!

**Comment by teresalin** [comment]
> Hi @stellaliao01 thanks for raising this. It's not working because the `GridToolbarFilterButton` is wrapped in a `Tooltip` component (this is because if you have active filters there are badges that indicate this). To overwrite the icon in the actual button you need to use the `componentsProps`.
> 
> ```tsx
> <GridToolbarFilterButton
>   componentsProps={{
>     button: {
>       startIcon: (
>         <IconButton>
>           <FilterAltIcon />
>         </IconButton>
>       )
>     }
>   }}
> />
> ```
> 
> I've also updated your example with the solution -> https://codesandbox.io/s/data-grid-pro-forked-mri2r6?file=/src/App.tsx

Please correct me if I'm wrong, but since GridToolbarFilterButton is a button itself, this code is going to raise a `<button> cannot appear as a descendant of <button>` warning. You can fix the warning by simply passing in the icon without IconButton:
```tsx
<GridToolbarFilterButton
  ref={buttonRef}
  componentsProps={{
    button: {
      startIcon: <FilterListIcon />,
    },
  }}
  sx={{
    padding: 0,
    minHeight: 0,
    minWidth: 0,
    borderRadius: 5,
    "& .MuiButton-startIcon": {
      "& > *:first-of-type": { fontSize: 24 },
      margin: 0,
    },
  }}
/>
```
