### ISSUE TITLE
[data grid] Improve support to dynamic row height with pinned columns

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#5137]
### Current behavior 😯

The measured height of a row with `getRowHeight="auto"` is always based on the center columns (non-pinned columns). If the content in the pinned columns is taller, it's cut.

![image](https://user-images.githubusercontent.com/42154031/172484854-8bb02e9f-b22d-4bfa-a98f-3b8440651c46.png)

https://codesandbox.io/s/dynamicrowheightgrid-material-demo-forked-imnnyy?file=/demo.tsx

### Expected behavior 🤔

It should measure all cells, even those pinned, and use the tallest cell.

>  Yes, this would be the best solution. However, it requires deeper changes to allow a row in rowsHeightLookup to have several base sizes but which only one should be considered. 

From https://github.com/mui/mui-x/pull/4859#issuecomment-1128221774

**Comment by hassaans208** [comment]
https://github.com/mui/mui-x/issues/417#issuecomment-1456228312
