### ISSUE TITLE
[data grid] Single click cell edition + validation

### ISSUE THREAD

**Issue by Zenoo** [mui/mui-x#5148]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Clicking on a checkbox in a cell representing a boolean value activates the edit mode.

### Expected behavior 🤔

Clicking on a checkbox in a cell representing a boolean should act as a normal checkbox: Change the value server-side, and never enter edit mode. (or at least enter it, edit the value and exit it so fast it shouldn't matter)

### Steps to reproduce 🕹

[Live Example](https://codesandbox.io/s/data-grid-community-forked-nc18wh?file=/src/RenderBoolean.tsx)

Steps:

1. Set a render component with an onClick handler like

```ts

      if (api.current.getCellMode(id, field) !== "edit") {
        api.current.startCellEditMode({ id, field });
      }
      await api.current.setEditCellValue(
        { id, field, value: event.target.checked },
        event
      );
      api.current.stopCellEditMode({ id, field });
```

### Context 🔦

I just want a way for the user to only have to click once on a checkbox and have the checkbox change its value, and propagate the change server-side like if it was edited in the edit mode.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
```
</details>

Using Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by m4theushw** [comment]
If you want to click the checkbox and make the request, then you don't need to use the editing API. The editing API is for when you need to put the cell in edit mode first. In your case, a call to `apiRef.current.updateRows` is sufficient to update the row. I made an example: https://codesandbox.io/s/data-grid-community-forked-w4u9fo?file=/src/RenderBoolean.tsx

**Comment by Zenoo** [comment]
In addition, this was easily done with the previous API with:

```js
api.setEditCellValue({ id, field, value: event.target.value }, event);
api.commitCellChange({ id, field });
api.setCellMode(id, field, 'view');
```

It would trigger the correct callback and update the server.

**Comment by m4theushw** [comment]
Could you give an example with the previous API?

> I don't have access to the server from the render component, only from the processRowUpdate callback. Is there anyway for me to trigger it programmatically ?

I didn't understand. You can put the column definitions inside the component, you just need to memoize it.

```tsx
function App() {
  const processRowUpdate = React.useCallback(() => ...);

  const columns = React.useMemo(() => [
    {
      field: "active",
      headerName: "Active",
      width: 150,
      renderCell: (params) => <RenderBoolean processRowUpdate={processRowUpdate} {...params} />,
      renderEditCell: (params) => <RenderBoolean {...params} />,
      editable: true
    }
  ], [processRowUpdate]);

  return <DataGrid columns={columns} processRowUpdate={processRowUpdate} />
}
```

**Comment by Zenoo** [comment]
[Here is a working example with the previous API](https://codesandbox.io/s/data-grid-community-forked-1qbnjk?file=/src/RenderBoolean.tsx). It was really handy.

**Comment by m4theushw** [comment]
Yeah, it works because the previous API is very buggy. The column doesn't even have the `editable` properly set. I still think you don't need the editing API here and `updateRows` is sufficient. The editing API is for when you want to start the edit mode, change the input, review the input and stop the edit mode (a.k.a commit). Here's a single click does everything. If I would update the demo to work with the new API it would require a lot of workarounds because `startCellEditMode` triggers a rerender and anything called after it will use an outdated state. The previous API doesn't always trigger the rerender so your example works.

Wrapping the columns in `React.useMemo`, like explained in https://github.com/mui/mui-x/issues/5148#issuecomment-1150482801, is not possible?

**Comment by Zenoo** [comment]
I was hoping to be able to avoid having to handle the server side of things in the render component, since it's an UI component more than a logic one.  

I basically have a component that handles everything `Datagrid` related, which handles initialization and database synchronisation on edit.  
The `RenderBoolean` component was simply supposed to be an UI adjustment, which shouldn't contain server syncing logic.  
But if there is no other way around in the new API, I will manually trigger the sync after the `updateRows`.

**Comment by m4theushw** [comment]
If you don't mind using a `setTimeout`, you can make it work in a similar way as the old API: https://codesandbox.io/s/data-grid-community-forked-giiqyu?file=/src/RenderBoolean.tsx

**Comment by Zenoo** [comment]
Thanks, it's almost perfect.  
I'm guessing there is no way to prevent the cell edition rerender?  
The edit render is flashing for a few milliseconds on click.

**Comment by m4theushw** [comment]
No, because it's changing from view to edit mode. However, you can use CSS to remove the shadow and adjust the paddings to make it look like if there was no transition between the modes.

**Comment by geobde** [comment]
Hello @m4theushw i have this hook

 `export const useDataGrid = (props) => {
  const { id, value, field, cellMode } = props;
  const apiRef = useGridApiContext();

  const setValue = useCallback(
    async (newValue) => {
      const isValid = await apiRef.current.setEditCellValue({
        id,
        field,
        value: newValue,
        debounceMs: 1
      });

      if (isValid && cellMode === "edit") {
        apiRef.current.stopCellEditMode({ id, field });
      }
    },
    [apiRef, field, cellMode, id]
  );

  return [value, setValue];
};`  and sometimes for no reason my cell stay in. editMode any idea?
