### ISSUE TITLE
Quick Filter issue - Uncaught TypeError: values is not iterable

### ISSUE THREAD

**Issue by Utkarshk7** [mui/mui-x#5150]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Following the link below to implement Quick filter -
https://mui.com/x/react-data-grid/filtering/

I am referring to the section "Quick filter" in the link.

Below is my code for custom toolbar:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/80442043/172728718-463e9126-4cc0-4a23-a753-3cfd386b209a.png">

Everything works fine, but when user types in the quick filter field, we can see following error in the console:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/80442043/172727084-c42a9105-18f1-434a-a240-dc71506c590b.png">

As a result, code review/ code quality check has failed in my project and we are unable to move the code to prod. Inputs in this regard will be of great help !

### Expected behavior 🤔

No error in the console

### Steps to reproduce 🕹

Steps:

1. Type in the quick filter input field
2. Check console
3. Error below appears
<img width="764" alt="image" src="https://user-images.githubusercontent.com/80442043/172727860-9972aa2e-5cf3-4071-b8e3-d546550cd041.png">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

Latest version of data-grid-pro

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

Browsers:
    Chrome: 102.0.5005.61
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.8.1 => 11.8.1 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.71 
    @mui/icons-material: ^5.2.4 => 5.2.4 
    @mui/lab: ^5.0.0-alpha.70 => 5.0.0-alpha.70 
    @mui/material: ^5.5.0 => 5.5.0 
    @mui/private-theming:  5.4.4 
    @mui/styled-engine:  5.4.4 
    @mui/styles: ^5.2.3 => 5.2.3 
    @mui/system:  5.5.0 
    @mui/types:  7.1.2 
    @mui/utils:  5.4.4 
    @mui/x-data-grid: ^5.2.2 => 5.12.0 
    @mui/x-data-grid-pro: ^5.12.0 => 5.12.0 
    @mui/x-license-pro:  5.12.0 
    @types/react:  17.0.37 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.5 => 5.3.5 
    typescript:  4.6.3 
```
</details>

### Order ID 💳 (optional)

#39429

**Comment by alexfauquette** [comment]
From the error message, I assume that `requestSearch` return something which is not iterable. But without the code to this function, I can not be sure.

Could you please provide a minimal reproduction. You can start from [this codesandbox](https://codesandbox.io/s/j6d2gn?file=/demo.tsx) and add the parser of your codebase
