### ISSUE TITLE
DataGridPro delay to display records sometimes

### ISSUE THREAD

**Issue by pkitcha** [mui/mui-x#5152]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am using DataGridPro(@mui/x-data-grid-pro": "^4.0.2") to display the data from SignalR, I can see that data-grid delay 2-3 seconds before display the result but if I click at checkbox header(Select all). Result will be displayed correctly. Any suggestion ?

I created data grid with coding below and passing rows as collection data to be displayed.

<DataGridPro rows={props.rows} columns={columns} rowHeight={22} headerHeight={50} textAlign={'center'} 
        checkboxSelection
        disableSelectionOnClick
        disableColumnMenu
        density="compact"     
 />

### Expected behavior 🤔

DataGridPro should display data instantly

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

@mui/x-data-grid-pro": "^4.0.2"

### Order ID 💳 (optional)

42094

**Comment by DanailH** [comment]
Hi, @pkitcha thanks for raising this!
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!
