### ISSUE TITLE
[pickers] DateTimePicker crashes when using Day.js with UTC timezone

### ISSUE THREAD

**Issue by saschametz** [mui/mui-x#5154]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using a Day.js object with "UTC" timezone, the DateTimePicker crashes with the error:
"Too many re-renders. React limits the number of renders to prevent an infinite loop."

When using the timezone "Europe/Berlin" the DateTimePicker works correctly.

### Expected behavior 🤔

It should work regardless of the timezone.

### Steps to reproduce 🕹

https://codesandbox.io/s/agitated-dew-76s1r?file=/src/Demo.tsx
_Note: Uncomment lines in CodeSandbox to test UTC (doesn't work) and Europe/Berlin (works)_

**Comment by artzub** [comment]
My fork of the above example with fixes:
https://codesandbox.io/s/broken-framework-srrh6e?file=/src/Demo.tsx
```javascript
...
import advancedFormat from "dayjs/plugin/advancedFormat";
dayjs.extend(advancedFormat);
...
function Adapter(props) {
  Object.assign(this, new AdapterDayjs(props));

  const tzOrUtc = (date) => (date?.$u ? this.dayjs.utc : this.dayjs)(date);

  this.date = (value) => {
    if (value === null) {
      return null;
    }

    return tzOrUtc(value);
  };

  return this;
}
...
<LocalizationProvider dateAdapter={Adapter} dateLibInstance={dayjs}>
...
```
Possibly you will be needed to override other methods, but for the case above these changes are enought.

**Comment by flaviendelangle** [comment]
Thanks for the workaround and sorry for the delay.

Duplicates #5876
I'm going to close this one, feel free to comment the other one if you want.
