### ISSUE TITLE
Datepicker currently opens to todays date, even when minDate and maxDate are both set in the past

### ISSUE THREAD

**Issue by deansimcox** [mui/mui-x#5155]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The Datepicker currently always opens to todays date (as far as I can tell), and in some scenarios this doesn't make sense.

## Screen recording of current behaviour
![](https://media1.giphy.com/media/uRMDrl7bEzvUWZzt67/giphy.gif?cid=790b7611d7a63e7316fe96fd2973bea65ec634481e068225&rid=giphy.gif&ct=g)

## Sandbox link
[https://codesandbox.io/s/basicdatepicker-material-demo-forked-04ntmv?file=/demo.tsx](https://codesandbox.io/s/basicdatepicker-material-demo-forked-04ntmv?file=/demo.tsx )

### Expected behavior 🤔

I can think of a few solutions, I'm not sure which would be best, if any.
Potential solutions:

1. Show the month from the maxDate prop
2. Provide a separate prop to control which month is opened to

### Steps to reproduce 🕹

Steps:

1. Open this sandbox link - [https://codesandbox.io/s/basicdatepicker-material-demo-forked-04ntmv?file=/demo.tsx](https://codesandbox.io/s/basicdatepicker-material-demo-forked-04ntmv?file=/demo.tsx )
2. Observe the the minDate and maxDate props are both in the past
3. Click on calendar icon to open Datepicker
4. Observe that the month shown is the current month, even though none of it is selectable

### Context 🔦

I am trying to use the Datepicker as a date of birth selector, and I'm trying to exclude children that are under 16 years of age.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #5091

> Provide a separate prop to control which month is opened to

The prop `defaultCalendarMonth` should fix your problem
But as discussed in #5091, we should improve the default behavior

**Comment by deansimcox** [comment]
Hi @flaviendelangle , I really appreciate the quick reply!
I think you're right, `defaultCalendarMonth` does seem to be what I need, thanks for that.
I might be wrong, but I think there may still be a bug even when using that prop, specifically when used with `openTo="year"` and `views={["year", "month", "day"]}`, I experience similar behaviour to my initial bug report

### New sandbox link
[https://codesandbox.io/s/basicdatepicker-material-demo-forked-lzqycs?file=/demo.tsx:1051-1105](https://codesandbox.io/s/basicdatepicker-material-demo-forked-lzqycs?file=/demo.tsx:1051-1105)

### Gif
![](https://media1.giphy.com/media/NbI2W2nSDD9mnojsfA/giphy.gif?cid=790b7611a51110e7ce214b81e1a180c38eb9a52305be8d13&rid=giphy.gif&ct=g)
