### ISSUE TITLE
[DataGrid] `GridColTypeDef` type issue

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#5165]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I've noticed that `GridColTypeDef` generic doesn't handle value type (`V`) properly:

```ts
const usdPrice: GridColTypeDef<number, string> = {
  type: 'number',
  valueFormatter: ({ value }) => '', // <= `value` is of `any` type here
};
```

### Expected behavior 🤔

I expect `value` to be typed as `number`

```ts
const usdPrice: GridColTypeDef<number, string> = {
  type: 'number',
  valueFormatter: ({ value }) => '', // <= `value` should be of `number` type here
};
```

It works as expected when using `GridColDef`:

```ts
const usdPrice2: GridColDef<any, number, string> = {
  field: 'field',
  type: 'number',
  valueFormatter: ({ value }) => '', // <= `value` is of `number` type here
};
```

### Steps to reproduce 🕹

Steps:

1. Go to https://stackblitz.com/edit/react-6lcl9t?file=demo.tsx,tsconfig.json
2. Hover `value` param and see its type

### Context 🔦

Given `GridColDef` signature:

https://github.com/mui/mui-x/blob/3be50cc8bbc760e76d5b8fdae14894be8d866b4a/packages/grid/x-data-grid/src/models/colDef/gridColDef.ts#L39

it looks like generic type params have wrong order:

https://github.com/mui/mui-x/blob/3be50cc8bbc760e76d5b8fdae14894be8d866b4a/packages/grid/x-data-grid/src/models/colDef/gridColDef.ts#L273

Should it be like this instead?

```diff
- export type GridColTypeDef<V = any, F = V> = Omit<GridColDef<V, any, F>, 'field'> & {
+ export type GridColTypeDef<V = any, F = V> = Omit<GridColDef<any, V, F>, 'field'> & {
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
@flaviendelangle What do you think?

**Comment by flaviendelangle** [comment]
Yes I agree with the fix :+1:

**Comment by sgoodrow-zymergen** [comment]
Any particular reason that `R` is passed in as any, rather than exposed as a generic on `GridColTypeDef`?
