### ISSUE TITLE
[DataGrid] Stick to bottom if new rows are added and scroll position is at the bottom

### ISSUE THREAD

**Issue by joe0BAB** [mui/mui-x#5168]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We have a use case, where constantly new rows are added to the end. It would be very convenient, if they newest added rows would stay in the view port or if there would be an option to enable 'stick to bottom' behaviour.

Related to https://github.com/mui/mui-x/issues/4160

### Examples 🌈

Eg terminals, when you run a command and it prints output, the terminal will stick to bottom so users can see the latest output.

### Motivation 🔦

I try to build a log view. As there can be a large number of log lines, the Datagrid virtualisation is very handy. It would be convenient if there's a way to keep Datagrid scroll position at the bottom to see latest log lines.

### Order ID 💳 (optional)

41693

**Comment by DanailH** [comment]
Hi @joe0BAB thanks for raising this!
Did you try using `apiRef.current.scrollToIndexes` to scroll to the newly created row? That can be one way to achieve that. I'm not sure how the practice would be to add an option to stick the scroll top of the grid to always be at the bottom.

**Comment by flaviendelangle** [comment]
If you have another grid with this behavior feel free to add a link.

But yes, I would first try to do it in user-land before creating a new option.

**Comment by joe0BAB** [comment]
Closing the issue as we discovered even if it would work (by adding a feature to MUI or by using an alternative way), we would run into performance issues. Ie. we cannot use Datagrid for our use-case.

**Comment by flaviendelangle** [comment]
@joe0BAB if you could take the time to describe which limitations make the Datagrid not suitable for your use-case, it would help us a lot
