### ISSUE TITLE
[docs] Wrong installs, incomplete imports

### ISSUE THREAD

**Issue by DarkTrick** [mui/mui-x#5171]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

[Getting started guide](https://mui.com/x/react-date-pickers/getting-started/) says to 
- run `npm install @date-io/date-fns`
- import via `import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';`
- does not mention how to import LocalizationProvider.
- [later](https://mui.com/x/react-date-pickers/date-picker/) the docs don7t mention how to import TextField. (The example only shows a drop of code, which is very difficult to apply to newcomers)
However, this resulted in errors and a non working solution

### Expected behavior 🤔

The following worked, so I guess it's the right way to setup
- run `npm install @mui/lab` (← very important, otherwise the LocalizationProvider is not found)
- run `npm install date-fns @date-io/date-fns` (added `date-fns`)
- import LocalizationProvider: `import { LocalizationProvider } from '@mui/lab';`
- import Adapter with `import AdapterDateFns from '@mui/lab/AdapterDateFns';`
- import TextField with `import { TextField } from '@mui/material';`

### Steps to reproduce 🕹

See documenation

### Context 🔦

I'm trying to get started.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 12.4
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Edge: Not Found
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.78 
    @mui/envinfo: ^2.0.6 => 2.0.6 
    @mui/icons-material: ^5.8.0 => 5.8.0 
    @mui/material: ^5.6.2 => 5.6.3 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/system:  5.6.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @types/react:  18.0.8 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript: ^4.6.3 => 4.6.3 
```
</details>

**Comment by flaviendelangle** [comment]
In our doc we don't import from the lab, those imports are deprecated.

We could indeed add the `LocalizationProvider` import in this example:


![image](https://user-images.githubusercontent.com/3309670/173102223-711fd83d-70e1-4e81-aa62-0b17fa24abe0.png)


For the `TextField`, which demo / example are you talking about ? 
You can expand the demo code and it should always contain all the imports used.

**Comment by DarkTrick** [comment]
Thank you very much for the reply!

> You can expand the demo code and it should always contain all the imports used.

I rechecked in the docs and indeed you can expand the demo code! Very nice function! 
I didn't perceive the icons down there in the right.
 
Maybe this is just a very personal problem or preference, but I would expect any actions in the top right corner. In the bottom right corner, I would expect *the least important information, that could even be skipped*.

**Example**
・・・・・・・・・・・・・・・・・・・・・・・・
![image](https://user-images.githubusercontent.com/46980694/173237256-8503d360-221e-472c-a2cb-d06920240f33.png)
・・・・・・・・・・・・・・・・・・・・・・・・

What do you think about that?

↑ 
 **guess this turned into an RFC** for now :)

**Comment by siriwatknp** [comment]
I like what @DarkTrick propose. cc @danilo-leal @oliviertassinari for more comments.

**Comment by joserodolfofreitas** [comment]
I like the proposal too. Including a specific title for the example - Maybe with a lighter, smaller font. (For mobile screens we'd probably need to keep the action bar below the content.) 
Happy to see this moving forward.

**Comment by oliviertassinari** [comment]
Form what I understand, #5242 is trying to solve this wrong installation instructions.

**Comment by DarkTrick** [comment]
@oliviertassinari 
> Which UI library were you using before MUI?

GTK (on C)
