### ISSUE TITLE
Possible bug in DatePicker / react-hook-form interaction

### ISSUE THREAD

**Issue by SpainTrain** [mui/mui-x#5175]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

DatePicker (and friends) are broken using Luxon

EDIT: When Luxon DateTime is being provided via RHF

### Expected behavior 🤔

Previous versions worked with the same code.  ~Docs say behavior didn't change (not correct).~

EDIT: This indeed worked previously in an existing codebase, however the issue seems fairly nuanced and related to DatePicker/RHF interaction.

### Steps to reproduce 🕹

Steps:

1. Use DatePicker (and friends), react-hook-form, and Luxon
2. See repro at https://codesandbox.io/s/materialuipickers-demo-mui-x-forked-vqxsod?file=/demo.tsx

### Context 🔦

~Was previously working, recent update broke this working functionality.~

EDIT: Existing codebase using DatePicker, RHF, and Luxon quit working correctly.  

### Your environment 🌎

```
<Controller
                  name="startDateTime"
                  control={control}
                  defaultValue={DateTime.fromISO('2022-09-10')}
                  rules={{ required: true }}
                  render={({ field }) => (
                    <DateTimePicker
                      renderInput={(props) => (
                        <TextField
                          margin="dense"
                          size="small"
                          fullWidth
                          name={field.name}
                          {...props}
                        />
                      )}
                      label="Start Date/Time"
                      value={field.value}
                      onChange={(newValue) => {
                        if (newValue !== null) {
                          setValue('startDateTime', newValue)
                        }
                      }}
                    />
                  )}
                />
```

### Order ID 💳 (optional)

37302

**Comment by cherniavskii** [comment]
Hey @SpainTrain 
It seems like `DatePicker` works just fine with Luxon - see this codesandbox: https://codesandbox.io/s/materialuipickers-demo-mui-x-forked-mqw0ic?file=/demo.tsx

Can you provide a minimal example that would allow us to reproduce the issue?
Thanks!

**Comment by SpainTrain** [comment]
Thanks for the quick reply and sandbox!

In the example, I notice it is using a native `Date` rather than a Luxon `DateTime`.  However, even after updating to use Luxon DateTime, it indeed works - https://codesandbox.io/s/materialuipickers-demo-mui-x-forked-vqxsod?file=/demo.tsx

This is pretty confounding because the code was previously working (I even have data that was persisted via the UI which no longer loads properly in production).  The repro demonstrates that this isn't the Luxon Provider.  I can continue digging and see if this is related to some change in the date adapter / RFH interaction.  If I find anything, I can post here again in case helpful for someone else.  However, since the bug report was false positive, I will close the issue.  

Thanks again for your help!

**Comment by SpainTrain** [comment]
I do have a clue in the console and would love any hypotheses on cause:

```
react_devtools_backend.js:4026 Mask does not support numbers with variable length such as 'M'.
Either use numbers with fix length or disable mask feature with 'disableMaskedInput' prop
Falling down to uncontrolled no-mask input. 
    at KeyboardDateInput (webpack-internal:///./node_modules/@mui/x-date-pickers/internals/components/KeyboardDateInput.js:31:5)
    at DesktopWrapper (webpack-internal:///./node_modules/@mui/x-date-pickers/internals/components/wrappers/DesktopWrapper.js:22:5)
    at DesktopDateTimePicker (webpack-internal:///./node_modules/@mui/x-date-pickers/DesktopDateTimePicker/DesktopDateTimePicker.js:45:106)
    at DateTimePicker (webpack-internal:///./node_modules/@mui/x-date-pickers/DateTimePicker/DateTimePicker.js:40:84)
```

I have confirmed that it is a Luxon `DateTime` object being provided to the `value` prop of the `DateTimePicker`

**Comment by SpainTrain** [comment]
Ok, here is a minimal repro of what I am experiencing in codesandbox- https://codesandbox.io/s/materialuipickers-demo-mui-x-forked-vqxsod?file=/demo.tsx

Watching the console, we see DatePicker is receiving a valid Luxon DateTime object, but for some reason is rendering as though it has received no value.

**Comment by SpainTrain** [comment]
Figured this out - RHF clones the `defaultValue` objects.  It appears that the Luxon Adapter is happy to acknowledge the original DateTime object as valid, but doesn't appear to recognize the cloned object as a Luxon DateTime.  

I suspect that I was previously relying on unintended behavior of the Luxon Adapter being more permissive, but it makes sense that the adapter would expect a real DateTime instance, not a clone (that lacks e.g., constructor).  It's still somewhat confounding because Luxon seems to use a flag field to determine whether something is a DateTime (https://github.com/moment/luxon/blob/abe9bdfd7224a3e240a24be80bf8abb731900a51/src/datetime.js#L485) and that field was present.  Regardless, I've confirmed that the real DateTime vs. cloned object was the issue, and IMO that is reasonable behavior.

Thanks again for the support and apologies for the distraction!

**Comment by cherniavskii** [comment]
@SpainTrain This is why we ask for minimal reproduction example

**Comment by lazyboy1** [comment]
@SpainTrain could you please elaborate on how you solved your issue? 
I think I am seeing the same issue or a similar one, also with RHF and Luxon: https://codesandbox.io/s/mui-x-date-pickers-with-react-hook-form-66vcuu?file=/src/App.js

**Comment by SpainTrain** [comment]
@lazyboy1 Definitely!

I updated my code to use native JavaScript Date objects with RHF and used the `AdapterDateFns` localization provider.  This is consistent with RHF's docs https://react-hook-form.com/api/useform : 

> Avoid including custom object into the defaultValues. eg: moment, luxon as those will lead to unexpected result during internal object clone process.

YMMV, but I was able to surgically use `fromJSDate` and `toJSDate` in my codebase to minimize the refactor and maximize the use of Luxon elsewhere.

**Comment by cherniavskii** [comment]
@lazyboy1 you can also downgrade react-hook-form: https://github.com/react-hook-form/react-hook-form/issues/6523#issuecomment-1063457797

**Comment by lazyboy1** [comment]
Thanks, I opted to convert to and from ISO strings, as I read from and write to strings anyways when talking to my API.

**Comment by lookfirst** [comment]
I'm seeing this error: `Mask does not support numbers with variable length such as 'M'.`

My code uses:

`inputFormat="yyyy-MM-dd h:mm a"`

My initialValue is a js Date object.

The problem as I see it is that the parser isn't looking at the fact that I've got `MM`. It just `sees` the first M and barfs, despite `MM` being valid. If I put `MMM`, the problem goes away, but the format is not correct now.

**Comment by cherniavskii** [comment]
Hey @lookfirst 
Could you open a new issue with a minimal reproduction example?
Thanks!

**Comment by samayer12** [comment]
@lookfirst , I've also encountered a similar warning issue with `inputFormat="dd MMM yyy"` when running my test suite.

**Comment by cherniavskii** [comment]
It looks like you just stopped using `inputFormat` prop as a workaround.
But feel free to open an issue if you believe there's a bug that should be fixed on our side :)

**Comment by lookfirst** [comment]
@cherniavskii Well, I stopped using it because it is buggy. You asked for a simple testcase... add it back and see the output failure. =)

MUI-RFF has a hard dependency on this project and has a decent number of users as well as long multi-year history of depending on MUI in general, so it seems time well spent to help figure it out.
