### ISSUE TITLE
Broken link to valueParser

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#5176]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The valueParser link is a 404

<img width="778" alt="Screenshot 2022-06-11 at 14 14 12" src="https://user-images.githubusercontent.com/3165635/173187482-cee2b4d3-8e09-4bde-9a70-68e8523dc797.png">

https://mui.com/x/react-data-grid/column-definition/#value-formatter

### Expected behavior 🤔

200

### Context 🔦

I could only find https://mui.com/x/react-data-grid/editing/#value-parser-and-value-setter as a potential link target but this only covers the use of `valueParser` for the editing feature. I'm not sure that it's good enough, the property is also used for the filtering feature.

**Comment by joserodolfofreitas** [comment]
Closing the issue. 
The [link](https://mui.com/x/react-data-grid/column-definition/#value-formatter) in question is working again.

**Comment by oliviertassinari** [comment]
It links to https://mui.com/x/react-data-grid/cells/#value-parser, which is a 404, even on master https://master--material-ui-x.netlify.app/x/advanced-components/x/react-data-grid/cells/#value-parser

**Comment by joserodolfofreitas** [comment]
Ah I see, thanks for the clarification!
