### ISSUE TITLE
[data grid] Custom footer component to display two pagination components

### ISSUE THREAD

**Issue by ShadiBlitz** [mui/mui-x#5184]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
components={{
     Footer: CustomPagination,
}}
```
Unable to add extra left footer. The current method overrides default footer.

### Expected behavior 🤔

I would like to achieve the following result, having the custom pagination on the left and the default pagination on the right.

![Screenshot from 2022-06-13 09-38-06](https://user-images.githubusercontent.com/101566855/173294602-ba805340-4ed2-487f-bf22-577322a45f8f.png)

I tried to do the following but it is not the correct way to do it (needs to select a row)
[https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-p6ctf9?file=/demo.tsx](https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-p6ctf9?file=/demo.tsx)

Any idea how can I achieve this?

### Steps to reproduce 🕹

Steps:

check [sandbox](https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-p6ctf9?file=/demo.tsx)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
You can override the `Pagination` slot, in which case it will replace the pagination on the right (https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-obgvs5?file=/demo.tsx)

But if you want to override the whole footer, you have to use the `Footer` slot and handle both paginations yourself (https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-f014gk?file=/demo.tsx)

**Comment by TamirCode** [comment]
> @flaviendelangle What do you think about splitting the [components page](https://mui.com/x/react-data-grid/components/) with the following structure:
> 
> * overview (which explains the concept of the slot with the simple example of icons)
> * grid
>   
>   * row
>   * cell
>   * overlay
> * toolbar
>   
>   * remove/add a button
>   * rewrite menu options
>   * customizing panel
> * column menu
> * Footer
>   
>   * row count
>   * selected row count
>   * pagination
> * Filter
>   the content from the filtering page

yes pls
the footer section in docs lacks a lot of information because there is no example on how to use the default items but only to override them completely

**Comment by Kris-D** [comment]
> You can override the `Pagination` slot, in which case it will replace the pagination on the right (https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-obgvs5?file=/demo.tsx)
> 
> But if you want to override the whole footer, you have to use the `Footer` slot and handle both paginations yourself (https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-f014gk?file=/demo.tsx)

The solution has an error of Cannot read properties of undefined (reading 'row')

**Comment by AshhadUllah** [comment]
> > You can override the `Pagination` slot, in which case it will replace the pagination on the right (https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-obgvs5?file=/demo.tsx)
> > But if you want to override the whole footer, you have to use the `Footer` slot and handle both paginations yourself (https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-f014gk?file=/demo.tsx)
> 
> The solution has an error of Cannot read properties of undefined (reading 'row')

Exactly I am facing the same issue can anyone please look into this? or guide us to updated solution.
