### ISSUE TITLE
setEditCellValue hangs in pending state

### ISSUE THREAD

**Issue by vinayak-bldeng** [mui/mui-x#5186]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Facing the issue with API Ref setEditCellValue , which hangs in the pending state and the never reaches to fulfilled or rejected.

As conveyed in the subject matter, for one of the use case we are making use of setEditCellValue to update the cell field in mui data grid pro. The API seems to work seamlessly in one of our local environment machine, but not with others. When troubleshooted we found that it always hangs in the pending state. 

### Expected behavior 🤔

It has to update the cell field.

### Steps to reproduce 🕹

Steps:

Access the link https://codesandbox.io/s/data-grid-pro-forked-u3pkuo?file=/src/App.tsx 

1.  Try to click on update cell value, internally i want to update the cell value of column 2 of row 2.
2. I have hardcoded the value in handleUpdate method, to update the cell value.
3. Initially the api ref make the cell field to edit mode and then setEditCellValue hangs in pending state. 
4. It never reaches the fulfilled state.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

31586

**Comment by alexfauquette** [comment]
@m4theushw I think the debounce strategy is failing when parameter `debounceMs` is not provided.

Adding it to the codesandbox makes it works:
https://codesandbox.io/s/data-grid-pro-forked-b586zh?file=/src/App.tsx
  
and debounce must be treated than 0 (1 is working)

**Comment by vinayak-bldeng** [comment]
Thanks it's working with the workaround solution.
