### ISSUE TITLE
How to change the color of native date/time picker in MUI-X?

### ISSUE THREAD

**Issue by nandeshwarshubh** [mui/mui-x#5188]
### Order ID 💳

44828

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

How to change the color of native date/time picker in MUI-X?

When I add color prop on Textfield, it changes the Textfield border and color but not the date picker color

<img width="232" alt="Screenshot 2022-06-13 at 6 28 42 PM" src="https://user-images.githubusercontent.com/47517129/173359066-c1afbb99-1ec8-43bb-a838-e473c6a2d522.png">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Since it is a native component, you should use native CSS selectors 

What you want to customize is the `input` component, One of many ways to add style is the following
```jsx
sx={{ '& input': {color: 'red'} }}
```
https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-ohjg51?file=/demo.tsx

**Comment by nandeshwarshubh** [comment]
Sorry for not being specific, but I meant the date color and 'Clear' and 'Today' text colors.
<img width="198" alt="Screenshot 2022-06-13 at 8 18 40 PM" src="https://user-images.githubusercontent.com/47517129/173381133-fc7e2915-7989-44a6-8dfe-6d14f18ee021.png">

**Comment by alexfauquette** [comment]
I don't know know how to style native components, that's a browser-specific component that is not related to MUI

Here is an example, without even importing MUI-core or MUI-X
https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-sj94iy?file=/demo.tsx

Maybe someone on StackOverflow knows how to do
