### ISSUE TITLE
[DateRangePicker] Support single input in the date range picker / date range field

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#5193]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Make date range feel like one input.

The date range is displayed as a single input, internally it's still based on two inputs.

### Examples 🌈

<img width="325" alt="image" src="https://user-images.githubusercontent.com/550141/173533842-7f70c8f2-a257-48a4-a682-a68d2a1655b6.png">

<img width="570" alt="date-range-single-input" src="https://user-images.githubusercontent.com/550141/173528248-ccfdb210-d000-4a4e-8175-565943e25a43.png">

## Benchmarks

- https://retool.com/components/date-range
- https://next.material.angular.io/components/datepicker/overview
- https://www.daterangepicker.com/
- https://react-dates.github.io/react-dates/?path=/story/daterangepicker-drp--default
- https://wakirin.github.io/Lightpick/#examples (Option: single:false) - deprecated in favor of easepick -
- https://easepick.com/examples/hotel.html 

### Motivation 🔦

We already have users that requested this feature once:
https://github.com/mui/material-ui-pickers/issues/1637

And users are trying to customize it:
https://github.com/mui/mui-x/issues/4548

it's also a common use case in multiple sites.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/550141/173534611-7e1c99ca-3c37-42e3-a907-94a313dab7f9.png">

<img width="220" alt="image" src="https://user-images.githubusercontent.com/550141/173535429-381c7bfb-d2b5-4617-b726-fab6efb71930.png">

**Comment by flaviendelangle** [comment]
For you, should we provide both solutions (two inputs AND single input)
Or should we migrate everything to single input ?

**Comment by flaviendelangle** [comment]
All we need to do now is to be able to pass the `SingleInputDateRangeField` to the new date range picker.

**Comment by flaviendelangle** [comment]
I'm closing in favor of #7606
I totally forgot about this one, sorry :grimacing:
