### ISSUE TITLE
After setting loading to false, DataGrid resets to the initial row status

### ISSUE THREAD

**Issue by ohechtl** [mui/mui-x#5208]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In version 5.11.1, a bug appeared. 
In our use case of datagrid, I'm updating the row data with `updateRows`, getting the data from async network requests.
I also set the loading status to true while it's loading, and set it to false when the data is loaded.
The bug happens when when I set the loading prop of DataGrid to false, and this causes a rerender and a reset of datagrid data to the original `row` prop's status, thus removing what is updated with the `updateRows` method.

Link to codesandbox:
https://codesandbox.io/s/updaterowsapiref-demo-mui-x-forked-j116r2?file=/demo.tsx

### Expected behavior 🤔

Before 5.11.1, it works just fine, and the data is not being reset when I change the loading status of the DataGrid.

### Steps to reproduce 🕹

Link to codesandbox:
https://codesandbox.io/s/updaterowsapiref-demo-mui-x-forked-j116r2?file=/demo.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
I've used Firefox.
  System:
    OS: Linux 5.18 Arch Linux
  Binaries:
    Node: 18.3.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 7.14.0 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 101.0.1
  npmPackages:
    @emotion/react: ^11.8.2 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base:  5.0.0-alpha.84 
    @mui/icons-material: ^5.5.0 => 5.8.3 
    @mui/lab: ^5.0.0-alpha.72 => 5.0.0-alpha.85 
    @mui/material: ^5.5.0 => 5.8.3 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system: ^5.5.1 => 5.8.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.12.1 
    @mui/x-data-grid-pro: ^5.12.1 => 5.12.1 
    @mui/x-date-pickers: ^5.0.0-alpha.0 => 5.0.0-alpha.6 
    @mui/x-license-pro:  5.12.1 
    @types/react: ^17.0.40 => 17.0.45 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.0 => 5.3.5 
    typescript: ^4.5.4 => 4.7.3 
```
</details>

### Order ID 💳 (optional)

#30627
Hiya Inc.

**Comment by ohechtl** [comment]
I suspect this dependency made this bug, but I'm far from being an expert here: https://github.com/mui/mui-x/compare/v5.11.0...v5.11.1#diff-d532ec5fe9d114abde2c562fba223d2b89db89a9e269f64a12800af824c3b43aR145

**Comment by flaviendelangle** [comment]
It is probably due to the adding of `loadingPropBeforePartialUpdates` in https://github.com/mui/mui-x/pull/4910

**Comment by ohechtl** [comment]
You're right, I've changed the `rows` object to be in a `useMemo`, and the bug is still visible. Although it looks flakier now, once working, once not.

**Comment by flaviendelangle** [comment]
@ohechtl if you want to test it a little I added Codesandbox links in #5213 
I think the bug is gone
And we also gain a performance improvement on large datasets

**Comment by ohechtl** [comment]
thanks for the quick fix, it looks great indeed!
