### ISSUE TITLE
DataGrid filterPanel - cancel/confirm button

### ISSUE THREAD

**Issue by michGreg** [mui/mui-x#5209]
### Order ID 💳

44899

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello. I use server filtering and need confirm filter selection after click on confirm button or cancel selection after click on button. Is there any way how to add buttons to filterPanel and handle filters via close/confirm buttons?
![img](https://user-images.githubusercontent.com/106229368/173824390-c31ca328-4c72-4a0f-b6a8-09fdadc1f05e.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
It's possible but not that easy.

You can use the slot `FilterPanel` to replace the default filter panel by a custom one

I copy-pasted the filter panel [in the code base](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx) and added a button in the footer

https://codesandbox.io/s/basicexampledatagridpro-demo-mui-x-forked-ux150s?file=/CustomFilterPanel.tsx

**Comment by michGreg** [comment]
Thanks. I understand. My solution should be custom filter panel component where I will use buttons with apiRef.current methods and datagrid onPreferencePanelClose prop for click away the panel.

**Comment by alexfauquette** [comment]
Yes. For closing the filter panel you might want to use the method `apiRef.current.hideFilterPanel();`
