### ISSUE TITLE
[DataGridPremium] Row grouping column does not dissapear when restoring state.

### ISSUE THREAD

**Issue by toinhao1** [mui/mui-x#5211]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When grouping by a certain column and then restoring the state to a previously exported state that does not include the grouping column the, grouping column is pushed to the end of the grid. 

### Expected behavior 🤔

If I export a state with 2 columns which are not grouped then the state should restore it to these 2 columns regardless of the current state.

### Steps to reproduce 🕹

Steps: This is a copy from the mui state export and restore demo
https://codesandbox.io/s/inspiring-tess-z5qr34?file=/src/App.tsx

1. Create a view with all cols
2. Create a view with just 2 cols
3. Group the rows by Commodity
4. Select one of the previously created views 
5. Look at the last column and the grouped column will be there.

### Context 🔦

I'm attempting to do a multi-view table. 

This is a similar issue to [#4779 ](https://github.com/mui/mui-x/issues/4779)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
The problem seems to come from the restoration of `orderedFields` because [columns that are not ordered are placed at the end](https://github.com/alexfauquette/mui-x/blob/master/packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts#L232-L235)

@flaviendelangle I assume the fix would be to do an exception for specific columns such as grouping, checkbox selection, row reorder

**Comment by flaviendelangle** [comment]
Yes
I wonder how to do it cleanly
We probably don't want to export the columns created by `hydrateColumns` since they depends on other props.

**Comment by toinhao1** [comment]
Any update on this? Or any way I can assist?

The ability to use/create multiple views was a key reason we went with this datagrid.

**Comment by flaviendelangle** [comment]
I don't see how to remove rows to do your step 2.
Can you check if the following works ? https://codesandbox.io/s/sad-firefly-qi5w82
I am removing manually the grouping columns from the exported state

**Comment by toinhao1** [comment]
Apologies,  it is supposed to be cols not rows. 

Yes, it seems to work, thank you.

 I guess, i can use this workaround for now. 

Any idea how to solves this also: https://github.com/mui/mui-x/issues/4779

**Comment by alexfauquette** [comment]
@flaviendelangle My apologies, I forget to fork when experimenting with your codesandbox 😓

I was still able to see the grouping column at the end after restoring a state which do not contain grouped column

I've done a workaround to save and restore the grouping model
https://codesandbox.io/s/trusting-cloud-9kdntn?file=/src/CustomToolbar.tsx

```jsx
// Save the grid state and the grouping model
const groupingModel = gridRowGroupingSanitizedModelSelector(apiRef);
dispatch({
  type: "createView",
  value: { ...apiRef.current.exportState(), groupingModel }
});

//  Restore the state and the grouping model
const { groupingModel, ...restoreState } = state.views[viewId].value;
apiRef.current.restoreState(restoreState);
apiRef.current.setRowGroupingModel(groupingModel);
```

**Comment by toinhao1** [comment]
In case anyone else is looking for this.

The below seems to solve all of the issues with exporting and restoring the state of the grid.

// Save the grid state and the grouping model
const groupingModel = gridRowGroupingSanitizedModelSelector(apiRef);
const columnModel = gridColumnVisibilityModelSelector(apiRef);
const pinnedColumns = apiRef.current.getPinnedColumns();
dispatch({
  type: "createView",
  value: { ...apiRef.current.exportState(), groupingModel, columnModel, pinnedColumns }
});

//  Restore the state and the grouping model
const { groupingModel, columnModel, pinnedColumns, ...restoreState } = state.views[viewId].value;
apiRef.current.restoreState(restoreState);
apiRef.current.setRowGroupingModel(groupingModel);
apiRef.current.setColumnVisibilityModel(columnModel);
apiRef.current.setPinnedColumns(pinnedColumns || {});
