### ISSUE TITLE
[DesktopDatePicker] Display CANCEL/OK buttons to use onAccept callback

### ISSUE THREAD

**Issue by gutakeda** [mui/mui-x#5220]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

There is an onAccept callback on the documentation for the DesktopDatePicker (https://mui.com/pt/x/api/date-pickers/desktop-date-picker/). On the current component it is called when onChange is called. But there is no way to display CANCEL and OK buttons to use this onAccept callback as it is used on MobileDatePicker for example.

### Expected behavior 🤔

Props to display CANCEL/OK buttons should exist to be able to use onAccept callback.

### Steps to reproduce 🕹

Codesandbox: https://codesandbox.io/s/determined-field-3knq45?file=/src/App.tsx

Steps:
1. Select a date
2. Check console.log

Result: onAccept and onChange are called
Expected result: a way to display CANCEL/OK buttons to call onAccept when clicking on OK button.

### Context 🔦

I need to apply custom logic before applying the date from onChange. Like adding a checkbox on the bottom of the calendar to apply or not this custom logic.
So the user could select the date, check or not the checkbox and then confirm clicking OK. For the MobileDatePicker there is these CANCEL/OK buttons, the onAccept/onChange is not fired automatically.

On the documentation it shows there is an onAccept callback as well but I think there is no difference between the onChange since there is no actually a "accept" button, so both are called when a date is selected. So right now I was only able to use onChange callback and there is no way to display these buttons to use onAccept callback. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
In the new versions of `@mui/x-date-pickers`, you have the ability to configure the actions displayed on the action bar

See [this example](https://codesandbox.io/s/romantic-christian-0mciot?file=/src/App.tsx) and our [CHANGELOG](https://github.com/mui/mui-x/blob/master/CHANGELOG.md#muix-date-pickers500-alpha4--muix-date-pickers-pro500-alpha4).

A detailed doc page should be released shortly.

**Comment by gutakeda** [comment]
I found the prop to prevent the close of the calendar
closeOnSelect={false}

Thanks for the help!
