### ISSUE TITLE
[DataGridPro] Tree Data doesn't work with checkboxSelection or rowReordering

### ISSUE THREAD

**Issue by teenguyen** [mui/mui-x#5224]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm not sure if this is a bug or a feature request, but it looks like some of the DataGrid functionality doesn't work with some others; e.g. tree data with `checkboxSelection` or `rowReordering`

### Expected behavior 🤔

I expect `checkboxSelection` to also check child rows.
I expect `rowReordering` to be able to work with tree data rows and correctly nest them in the right layer.

### Steps to reproduce 🕹

I duplicated the tree data example and added the two props to test them out:
https://codesandbox.io/s/treedatafullexample-material-demo-forked-izdzo5?file=/demo.js

It looks like the checkbox doesn't check the nested child rows, and row reordering does not work at all.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

LiveRamp

**Comment by flaviendelangle** [comment]
> I expect rowReordering to be able to work with tree data rows and correctly nest them in the right layer.

![image](https://user-images.githubusercontent.com/3309670/174033936-9350b2f8-9b0e-49ca-9af0-a1ec01655764.png)

You have a warning in the doc saying that for now it's not compatible
We will work on it at some point

> It looks like the checkbox doesn't check the nested child rows

There is indeed no notion of parent-child relation-ship during selection.
You can implement one on your side see https://github.com/mui/mui-x/issues/4248.
We will probably add a prop to enable automatic children selection at some point

**Comment by flaviendelangle** [comment]
I am closing this one since both topics have a dedicated issue
