### ISSUE TITLE
[data grid] What is correct way of getting selected items?

### ISSUE THREAD

**Issue by kasteckis** [mui/mui-x#5226]
Hello,

my goal is to select X amount of rows and send them to backend server.

As I see in documentation, there is an API for that `getSelectedRows: () => Map<GridRowId, GridRowModel>`.

How would I access this API? 

I have something like this in my component function class.

```
  <DataGrid
      onCellEditStop={(params: GridCellParams, event: MuiEvent<MuiBaseEvent>) => {
          console.log(params);
          console.log(event);
      }}
      experimentalFeatures={{ newEditingApi: true }}
      rows={rows}
      columns={columns}
      checkboxSelection
  />
```

**Comment by flaviendelangle** [comment]
Hi,

You have an explanation about the usage of the api in a class component in https://github.com/mui/mui-x/issues/4776#issuecomment-1119558082

Note that it is only available for pro and premium users for now
