### ISSUE TITLE
[data grid] Default filter operator fallback does not work on state initialization

### ISSUE THREAD

**Issue by rtucker-dw** [mui/mui-x#5229]
### Order ID 💳

33590

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

The error apiRef.current.getColumn is not a function is being thrown from mui/x-data-grid/hooks/features/filter/gridFilterUtils.js:17:35. I was able to create a minimally reproducible test case at https://codesandbox.io/s/wizardly-taussig-oozpm8. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Seems that adding `operatorValue` to itmes of your filter models as solves the problem

https://codesandbox.io/s/sharp-snowflake-2ktefi?file=/src/App.js

**Comment by flaviendelangle** [comment]
I'll consider that one as a bug even though it is highly encouraged to provide the `operatorValue` rather than letting the grid choose a default one.
