### ISSUE TITLE
[StaticTimePicker] CANCEL/OK buttons can't be removed or customized

### ISSUE THREAD

**Issue by Mae623** [mui/mui-x#5233]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

hello.I have add two dialog action buttons  as below. 
![2041655433672_ pic](https://user-images.githubusercontent.com/38620932/174214200-036bb9ce-1f0a-42a4-bbe8-190082477c1e.jpg)

Today, I find that CANCEL/OK buttons displayed on StaticTimePicker. I can't find a suitable prop to customized them. I also can't remove them by using code as below.
` sx={{ '& .MuiPaper-root':
         { '& .MuiPickerStaticWrapper-root':
         { '& .MuiDialogActions-root': { display: 'none' } } } }}`

### Expected behavior 🤔

I hope I can remove CANCEL/OK buttons, or customized them. Thank you very much~

### Steps to reproduce 🕹

codesandbox: https://codesandbox.io/s/nice-rumple-n3fy5r?file=/src/App.js

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
If by customizing you mean modifying text, the doc you are looking for is here: https://mui.com/x/react-date-pickers/localization/

If it is about modifying which button is displayed in the action bar, you can specify which of the 4 default buttons would want and their order as follow:
```jsx
componentsProps={{ actionBar: { actions: [ 'today', 'accept', 'cancel', 'clear'] } }}
```

You can also completely override the `ActionBar` with 
```jsx
components={{ ActionBar: MyCustomActionBar}}
```
you will get `onAccept`, `onClear`, `onCancel`, and `onSetToday` methods in the props of your custom action bar

Here is you example with the two solutions

https://codesandbox.io/s/distracted-aryabhata-sqy111?file=/src/App.js

---

Regarding translations, the support of translation is quite new, and we do not have `"zh-cn"` translations. If you want to open a PR  to share translations with the community

https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/locales/enUS.ts

**Comment by Mae623** [comment]
Very glad for your reply! I solve my problem by the first way as below:
` componentsProps={{ actionBar: { actions: [] } }}`
I'd like to share "zh-cn" translations (*^▽^*)
