### ISSUE TITLE
[data grid] Quick filter is not working with row grouping

### ISSUE THREAD

**Issue by mormir2** [mui/mui-x#5234]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I noticed that QuickFilter does not work with row grouping: when typing anything into the QuickFilter input, an error will be thrown saying: "Cannot destructure property 'value' of 'undefined' as it is undefined." and no filter will be applied.

I created a demo codesandbox starting with the basic example for row grouping from the documentation (https://mui.com/x/react-data-grid/row-grouping/) and added the toolbar with QuickFilter: https://codesandbox.io/s/rowgroupingbasicexample-with-quickfilter-oblz92?file=/demo.tsx

### Expected behavior 🤔

QuickFilter should filter elements also if row grouping is applied.

### Steps to reproduce 🕹

Steps:

1. Create a simple data grid with row grouping
2. Add a toolbar with QuickFilter
3. Type anything into the QuickFilter input and an error will be thrown

See demo: https://codesandbox.io/s/rowgroupingbasicexample-with-quickfilter-oblz92?file=/demo.tsx

**Comment by mojsicaIcentic** [comment]
@mormir2 Thanks for posting this. I have just wanted to write about the same problem.

**Comment by alexfauquette** [comment]
Thanks for the reproduction example. It sounds like I forget to deal with autogenerated row

I'm looking for fixing it

**Comment by mormir2** [comment]
@alexfauquette First of all I wanted to thank you all for all the work you do!I tested the new version 5.12.3 that was just published and wanted to ask you for a quick clarification: is the quickfilter in combination with row grouping supposed to only filter the group rows? I was expecting the filter to also show children, not only to apply the filter to the grouping rows. I forked my original demo and upgraded the package version: https://codesandbox.io/s/rowgroupingbasicexample-with-quickfilter-v5-12-3-wmws5f

**Comment by alexfauquette** [comment]
@mormir2 The PR fixed the error, but the filter logic needs to be improved. I opened an issue to track progress #5278
