### ISSUE TITLE
[DatePicker] MuiPickerDays has type error inside createTheme to override styles

### ISSUE THREAD

**Issue by jano-gazashvili-axon** [mui/mui-x#5236]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I want to rewrite styles into `createTheme` and try to add `MuiPickerDays` in components list to make some changes, but i had type error like that ` 'MuiPickersDay' does not exist in type 'Components<BaseTheme>`

### Expected behavior 🤔

Expected behavior is that i want to override styles for `PickerDay` components in `DesktopDatePicker`

### Steps to reproduce 🕹

Steps:

![image](https://user-images.githubusercontent.com/90605572/174120300-8b14fa20-bc30-440d-9589-c5a5a6c8e3cb.png)

There is problem if i want to override styles for `MuiPickersDay`, strange is that it has type error but it works, just what i saw is that in modules Mui doesn't have types for `MuiPickersDay`, maybe it's an issue or it was renamed?

![image](https://user-images.githubusercontent.com/90605572/174120389-0e643098-5339-43b2-a538-9d0be6ef1748.png)
If add this in modules (how it shown on the screen) it has no type errors more. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by jano-gazashvili-axon** [comment]
Last version

**Comment by jano-gazashvili-axon** [comment]
> using ?

Last version

**Comment by flaviendelangle** [comment]
Are your importing the theme augmentation ? 
We are probably missing a doc paragraph since the migration out of the lab
With this import it's working fine on my machine 

![image](https://user-images.githubusercontent.com/3309670/174746754-313e7635-2596-4150-9e24-ad37f38ff3c9.png)

**Comment by jano-gazashvili-axon** [comment]
> Are your importing the theme augmentation ? We are probably missing a doc paragraph since the migration out of the lab With this import it's working fine on my machine
> 
> ![image](https://user-images.githubusercontent.com/3309670/174746754-313e7635-2596-4150-9e24-ad37f38ff3c9.png)

after importing i got some errors 
![image](https://user-images.githubusercontent.com/90605572/174965773-bc9fde50-f737-4eb8-b65f-1b5c248313d8.png)

**Comment by flaviendelangle** [comment]
You can try `import type {] from '@mui/x-date-pickers/themeAugmentation'`
I added some doc that will be available soon, you can find the preview [here](https://deploy-preview-5276--material-ui-x.netlify.app/x/react-date-pickers/getting-started/#typescript)
