### ISSUE TITLE
[data grid] How to limit the number of checkbox selected ? 

### ISSUE THREAD

**Issue by AdamGaoua** [mui/mui-x#5241]
Hello, 

in this project, I use DataGrid Component with CheckBox Selection. I want to limit at 5 the number of the checkbox could be check at the time. I don't find how to create this limitation with the event of DataGrid component. 

If you can help me, it will be appreciate.

**Comment by flaviendelangle** [comment]
Hi

You could control the model and decide to update it or not depending on the size of the existing model
https://codesandbox.io/s/data-grid-community-forked-3l4y9d?file=/src/App.tsx

**Comment by AdamGaoua** [comment]
Hello, 

Thank's for helping. I have an error: DataGridProps, GridRowId was not found in  @mui/x-data-grid.

**Comment by flaviendelangle** [comment]
It's a type, if you are using JavaScript instead of TypeScript you can remove it
