### ISSUE TITLE
[data grid] Row reorder pinned rows

### ISSUE THREAD

**Issue by kenklin** [mui/mui-x#5256]
### Order ID 💳

45624

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Given the published DataGridPro rowReordering [example](https://mui.com/x/react-data-grid/rows/#row-reorder), I'd like to prevent its bottom-most row from being reordered - e.g., disable its reorder handle and prevent other rows from being dragged to the bottom.

I've thought about moving this last row out of the DataGridPro as a possible approach, however that would cause it to have a different appearance from the other rows, so I am not pursing that approach.  

I'd be grateful for any suggestions on an approach to take.  Thanks in advance.

(I searched for `row reorder` and did not see any relevant posts as to how to prevent specified row(s) from being reordered.)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.6.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 97.28 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 4.1.0 - /usr/local/bin/watchman
  Managers:
    Gradle: 2.8 - /usr/local/bin/gradle
    Homebrew: 3.4.5 - /usr/local/bin/brew
    Maven: 3.3.3 - /usr/local/bin/mvn
    pip2: 7.1.0 - /usr/local/bin/pip2
    pip3: 22.0.4 - /Library/Frameworks/Python.framework/Versions/3.10/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    Clang: 1300.0.29.30 - /usr/bin/clang
    FFmpeg: 3.3.4 - /usr/local/bin/ffmpeg
  Servers:
    Apache: 2.4.53 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.12 - /usr/local/bin/docker
    VirtualBox: 5.1.2 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 15, 23, 28
      Build Tools: 19.1.0, 23.0.1, 23.0.2, 25.0.0, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 2.3 AI-162.3764568
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.5.3 - /usr/local/go/bin/go
    Java: 1.8.0_121 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.29 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.10.4 - /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
    R: 3.3.3 - /usr/local/bin/R
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 102.0.5005.115
    Chrome Canary: 105.0.5127.0
    Firefox: 101.0
    Safari: 15.5```
</details>

**Comment by flaviendelangle** [comment]
I think it relates a lot with https://github.com/mui/mui-x/pull/4863

**Comment by cherniavskii** [comment]
Hey @kenklin 
I've created this demo: https://codesandbox.io/s/rowpinningwithvirtualization-demo-mui-x-forked-e91yc1?file=/demo.tsx
It uses [Row Pinning](https://github.com/mui/mui-x/pull/4863) (not released yet) to pin a row on the bottom.

**Comment by kenklin** [comment]
@cherniavskii @flaviendelangle Thanks for your responses.  I had seen the row pinning PR but wasn't 100% certain it would cover reordering.  The demo is useful!

**Comment by flaviendelangle** [comment]
I'll close this one in favor of #1251 then

Duplicate #1251
