### ISSUE TITLE
Styled components as styled engine in CRA app with craco and react scripts 5

### ISSUE THREAD

**Issue by PrimulaX** [mui/mui-x#5261]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using `styled-components` as styled engine which needs alias and `craco` is used to override `webpack` configs which only supports `react-script 4*` (plus `craco-alias` plugin is already deprecated), meanwhile I need to update `react-scripts`, can I use `styled-components` as styled engine without `craco`?

### Expected behavior 🤔

So I need to use `styled-components` as styled engine without craco because craco doesn't support react-scripts 5.
Sorry for create this issue as bug report.

**Comment by PrimulaX** [comment]
I was able to override `style-engine` with npm override that way: 
```
"overrides": {
    "@mui/styled-engine": "https://registry.npmjs.org/@mui/styled-engine-sc/-/styled-engine-sc-5.6.1.tgz" 
  },
  ```
  
 But I was unable to reference it to the existing `style-engine-sc` pgk.

**Comment by flaviendelangle** [comment]
I am closing this one in favor of https://github.com/mui/material-ui/issues/33222
