### ISSUE TITLE
[DataGrid] MasterDetail grid inside tab throws error on tab switch

### ISSUE THREAD

**Issue by mormir2** [mui/mui-x#5262]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the DataGrid's MasterDetail is used inside Tabs, the page will crash when trying to access the tab containing the master detail.
The following error is thrown when switching from any tab to the tab with the master detail grid:
**`apiRef.current.getRowParams is not a function`**

With "regular" grids, this error doesn't occur.

I created a sandbox to reproduce this error: https://codesandbox.io/s/masterdetailgrid-tabs-7tlzx7

(The MasterDetailGrid component content was taken from the first example on https://mui.com/x/react-data-grid/master-detail/, the simple DataGrid example from https://mui.com/x/react-data-grid/getting-started/)

### Expected behavior 🤔

When switching between tabs, grids containing master details should be rendered correctly.

### Steps to reproduce 🕹

Demo: https://codesandbox.io/s/masterdetailgrid-tabs-7tlzx7
Steps:
1. switch from any tab to the "MasterDetail Grid" tab
2. the error will be thrown

### Context 🔦

I am using various grids in tabs (which don't cause any problems) and in one specific case, I need a grid containing master detail. When switching from any tab to the master detail grid tab, an error will be thrown which causes the whole page to crash.

**Comment by flaviendelangle** [comment]
Hi

The problem is not related to the Tabs
It was introduced on #5110 only on premium plan, we will release a fix in a few days
Sorry for the inconvenience

**Comment by mormir2** [comment]
@flaviendelangle thanks a lot for your quick reply!
