### ISSUE TITLE
[data grid] How to instanciate the api object

### ISSUE THREAD

**Issue by giladv** [mui/mui-x#5269]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
const apiRef = useRef<GridApiPro>();

<DataGridPro apiRef={apiRef} ....... />
```
produces an TS error 
```
TS2322: Type 'MutableRefObject<GridApiPro | undefined>' is not assignable to type 'MutableRefObject<GridApiPro>'.   Type 'GridApiPro | undefined' is not assignable to type 'GridApiPro'.     Type 'undefined' is not assignable to type 'GridApiPro'. 
```

essentially, as far as i understand it is impossible to create the required type without the correct initial ref value or forcing it with casting.

### Expected behavior 🤔

apiRef prop type should be 
```
MutableRefObject<GridApiPro | undefined>
```

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
HI
You should import `useGridApiRef` and do the following:

```ts
const apiRef = useGridApiRef();
```

We clearly miss a doc section for this subject

**Comment by flaviendelangle** [comment]
Here is the doc (work in progress) around this topic: https://deploy-preview-5273--material-ui-x.netlify.app/x/react-data-grid/api-object/
