### ISSUE TITLE
[data grid] Grid resizing/flashing in some screen resolutions

### ISSUE THREAD

**Issue by ramyab03** [mui/mui-x#5270]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

DataGrid - Single row select 

In some screen resolutions (example - 1680x1050, 1920x1080) whenever we select a row the DataGrid resizes itself. We are using 'flex' width for some of the columns in the DataGrid.  This resizing does not happen for smaller resolutions like 1440x900, 1024x768.

Attached is the recording from developer tools.

https://user-images.githubusercontent.com/44844109/174656900-de4acb0a-dcb9-431e-a71f-91d95da072e5.mp4

### Expected behavior 🤔

The DataGrid should not resize 

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

**Comment by cherniavskii** [comment]
@ramyab03 
In your recording you can see scroll bar appearing and disappearing, which changes window width and therefore may impact grid width (depending on your layout).

If you believe there's a bug in Data Grid - please provide a minimal example reproducing the issue.
Screen recording is not enough and we cannot proceed further if we cannot reproduce the issue.
