### ISSUE TITLE
[docs] Add npm/yarn tabs to installation pages.

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#5272]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We recently [split](https://github.com/mui/mui-x/pull/4692) the npm and yarn instructions to improve DX when copying the installation block.

But we have a lot of instructions to install different packages and a page like the new [/x/introduction/installation/](https://mui.com/x/introduction/installation/) can get crowded and even intimidating at a first glance (although with repetitive information).

My initial suggestion is to add a tab for yarn, ideally holding state (so other installation blocks can also reflect its value).

### Examples 🌈

<img width="518" alt="image" src="https://user-images.githubusercontent.com/550141/174757558-c67a6664-17ac-4c49-959f-78bd2646eece.png">

https://reactflow.dev/docs/getting-started/installation/

### Motivation 🔦

- Improve DX further
- Make the installation page feel cleaner.

**Comment by alexfauquette** [comment]
Doing that can lead to another pain point: having to modify every tab

To have a perfect experience, we should store the package manager of the dev in a global state such that if you click on npm all the doc switch es to npm

**Comment by flaviendelangle** [comment]
Related to #36766

We will basically have to use what @siriwatknp is implemening
