### ISSUE TITLE
[data grid] Filter value with trailing spaces

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#5275]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently, filter value with trailing spaces doesn't remove the trailing spaces like below.

1. "sampl3e " passed as "sample " and not "sample"
2. "sample filter value" passed as "sample filter value" which is the expected behavior

### Expected behavior 🤔

Filter value for string should removed the trailing space when filtering.

1. "sample " should pass "sample" as value
2. "sample filter value" passed as "sample filter value" which is the expected behavior

### Steps to reproduce 🕹

Steps:

1. Choose any string filter
2. try to put "sample " as the filter value
3. The filter value "sample " doesn't remove the trailing space
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

33625

**Comment by flaviendelangle** [comment]
I agree that we could probably trail the filtering value by default
Any opinion @m4theushw @alexfauquette ?

**Comment by alexfauquette** [comment]
I do not see objections on my side
