### ISSUE TITLE
[data grid] How allign works with columns?

### ISSUE THREAD

**Issue by kasteckis** [mui/mui-x#5280]
Hi,

How do I make "Actions" tab stick to the right side?
![image](https://user-images.githubusercontent.com/41127259/174799373-8746d075-7fea-4f16-aa95-bc2359c7dd38.png)

**Comment by socramm9** [comment]
The First column has to be set to `flex: 1`

**Comment by cherniavskii** [comment]
Hey @kasteckis 
https://github.com/mui/mui-x/issues/5280#issuecomment-1161833420 @socramm9 is right
