### ISSUE TITLE
Hidding/showing columns issue

### ISSUE THREAD

**Issue by deepen77** [mui/mui-x#5281]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have state in react to track resolution on the screen all the time using useEffect hook
`const [resolution, setResolution] = React.useState<number>(window.innerWidth);`

```
const handleResize = () => {
    setResolution(window.innerWidth)
  };

  React.useEffect(() => {
    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('resize', handleResize)
    };
  }, []);
```

Unfortunatelly the columns loosing the state set up by user for property  hide (true/false) and back to default state set up when screen is resized because the resolution is using and cause rerender the grid

### Expected behavior 🤔

Column property hide should keep the state set up by user and not changing if screen is resized

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

System:
OS: Windows 10 10.0.19044
Binaries:
Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
Yarn: Not Found
npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
Browsers:
Chrome: Not Found
Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.39)
npmPackages:
@emotion/react: ^11.9.0 => 11.9.0
@emotion/styled: ^11.8.1 => 11.8.1
@mui/base: 5.0.0-alpha.83
@mui/icons-material: ^5.8.2 => 5.8.2
@mui/material: ^5.8.2 => 5.8.2
@mui/private-theming: 5.8.0
@mui/styled-engine: 5.8.0
@mui/system: 5.8.2
@mui/types: 7.1.3
@mui/utils: 5.8.0
@mui/x-data-grid: ^5.12.0 => 5.12.0
@types/react: 18.0.10
react: ^18.1.0 => 18.1.0
react-dom: ^18.1.0 => 18.1.0
typescript: 4.7.2

**Comment by toinhao1** [comment]
Probably be good to have a codesandbox to easily show what the issue is.

But, this is the same as this issue: https://github.com/mui/mui-x/issues/970

Which isn't an issue, you need to memoize your columns otherwise they will reset to the initial state on each re render of the grid.

**Comment by alexfauquette** [comment]
@deepen77 You maybe forgotten to save your codesandbox I can only see the default demo from the doc (no `.hide` or stuff related to column visibility, or resizing)

**Comment by deepen77** [comment]
applogies for it, this shoud work now?:

[https://codesandbox.io/s/valuegettergrid-demo-mui-x-forked-dijg7x?file=/demo.tsx](url)

**Comment by alexfauquette** [comment]
Ho I see, of course, if you update the `columns` the component takes into account the new values

Controlling the column visibility model fix it because the visible/hide is not anymore dependent on the resolution
https://codesandbox.io/s/valuegettergrid-demo-mui-x-forked-x6onhb?file=/demo.tsx

A better solution for pro user is to use the API to update the with directly in the state avoiding a all rerender
https://codesandbox.io/s/valuegettergrid-demo-mui-x-forked-9sn5ml?file=/demo.tsx:1177-1631
```jsx
const handleResize = React.useCallback(() => {
    setResolution((prevResolution) => {
      const newResolution = window.innerWidth;
      const newLastNameWidth = newResolution > 1000 ? 300 : 100;
      const prevLastNameWidth = prevResolution > 1000 ? 300 : 100;
      if (newLastNameWidth !== prevLastNameWidth) {
        apiRef.updateColumn({ field: "lastName", width: newLastNameWidth });
      }
      return newResolution;
    });
  }, [apiRef]);
```

**Comment by alexfauquette** [comment]
You forget again to save your sandbox, because it does not contain any visibility model. initializing the `columnVisibilityModel` works on my side

https://codesandbox.io/s/valuegettergrid-demo-mui-x-forked-ui0vi0?file=/demo.tsx

**Comment by deepen77** [comment]
saved now :)
[https://codesandbox.io/s/valuegettergrid-demo-mui-x-forked-dijg7x?file=/demo.tsx](url)

**Comment by alexfauquette** [comment]
You're mixing `.hide` and `columnVisibilityModel` that's why it fails. You can see in my example bellow that I only use `columnVisibilityModel`
