### ISSUE TITLE
[StaticDateRangePicker] Mobile Date inputs add leading zeros to the year. 

### ISSUE THREAD

**Issue by Heartland-React** [mui/mui-x#5284]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the StaticDateRangePicker width displayStaticWrapperAs={"mobile"}, typing in a date on the mobile inputs works up until typing the year. The cursor seems to throw the user to the end of the year and doesn't allow for typing in an entire year. The component will then trigger the error state. For example, trying to type 06/05/2020 would result in 06/05/0002 and an invalid field message.

### Expected behavior 🤔

The StaticDateRangePicker mobile view should allow typing of a full date without injecting leading zeros into the YYYY part of the date.

### Steps to reproduce 🕹

Steps:
[CodeSandbox](https://codesandbox.io/s/staticdaterangepickerdemo-demo-mui-x-forked-heur0p?file=/demo.tsx)

1. Open the CodeSandbox
2. Click the pencil icon to change to the mobile input view.
3. Click in the first input and type a full date that has 4 digits in the year.

Component will switch focus out of the input and not allow the full typing of a year in YYYY format.

### Context 🔦

We are developing a graph date range selection tool for our product and noticed this issue when QA ran across it in testing.
Tested in Safari iOS and Chrome 102.0.5005.61.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

 System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Not Found
    Firefox: 87.0
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base:  5.0.0-alpha.84 
    @mui/icons-material: ^5.5.1 => 5.8.3 
    @mui/lab: ^5.0.0-alpha.74 => 5.0.0-alpha.85 
    @mui/material: ^5.8.1 => 5.8.3 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.12.1 
    @mui/x-data-grid-pro: ^5.11.1 => 5.12.1 
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-license-pro: ^5.12.2 => 5.12.2 
    @types/react: ^18.0.9 => 18.0.12 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript: ^4.7.2 => 4.7.3 
</details>

### Order ID 💳 (optional)

39694

**Comment by alexfauquette** [comment]
Related to #5231 and should be fixed by #5265

Here is the codesandbox using the package with the fix. I can not reproduce the bug on it 

https://codesandbox.io/s/staticdaterangepickerdemo-demo-mui-x-forked-q1z2yp?file=/package.json
