### ISSUE TITLE
[data grid] Allow disabling multiple row selection with checkbox selection enabled

### ISSUE THREAD

**Issue by swsvindland** [mui/mui-x#5286]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently you can do single line selection with no checkbox, and multiline selection with no checbox. But when checkbox is enabled you only get multiline checkbox. 

I would like to be able to specify that, even with checkbox turned on, that I only wanna select one row. 
https://codesandbox.io/p/sandbox/polished-flower-jknwps?file=%2Fpackage.json%3A11%2C23

### Examples 🌈

Current
<img width="783" alt="image" src="https://user-images.githubusercontent.com/11298356/174882389-04fb2cef-6f61-43df-b688-7c8b34f6b991.png">

Proposed
![Frame 1](https://user-images.githubusercontent.com/11298356/174882724-1670e4d6-4103-4744-a3b4-c413208fca6c.png)

Proposed interface
```
<DataGrid 
    rows={rows} 
    columns={columns} 
    checkboxSelection={true}
    maxSelected={1} // can select only one, no top select all box
    maxSelected={3} // can select up to 3, no top select all
    maxSelected={undefined} // current behavior
/>
```

### Motivation 🔦

Trying to have a page in my app that allows the user to select multiple entities from separate data grids, but can only select one from each. Currently doing a hack to just only take the first from each list and disabling selection of any new items.

**Comment by alexfauquette** [comment]
It's surprizing that `disableMultipleSelection=true` does not do that. The reason is that `checkboxSelection` removes its effect
https://codesandbox.io/s/checkboxselectiongrid-demo-mui-x-forked-6meyoi?file=/demo.tsx

You can do it on your side by controlling the selection model as follow:
https://codesandbox.io/s/checkboxselectiongrid-demo-mui-x-forked-q55wzt?file=/demo.tsx
```jsx
onSelectionModelChange={(newSelectionModel) => {
  setSelectionModel((prevModel) =>
    newSelectionModel.filter((newId) => !prevModel.includes(newId))
  );
  }
}
selectionModel={selectionModel}
```

The only draw back I see is the select all checkbox wich is still working

**Comment by flaviendelangle** [comment]
What should be the exact behavior ?

Right now on `DataGrid` you can't set `disableMultipleSelection`
`checkboxSelection` is indeed handle differently.

Maybe we could open `disableMultipleSelection` on `DataGrid` instead of forcing its value (and set it to `false` by default)
And in `useGridSelection`do

```diff
- const canHaveMultipleSelection = !disableMultipleSelection || checkboxSelection;
+ const canHaveMultipleSelection = disableMultipleSelection == null ?  checkboxSelection : !disableMultipleSelection;
```

And if `disableMultipleSelection === true`, hide the select all checkbox of course

**Comment by conerye** [comment]
we are running into this issue as well. any update?

**Comment by flaviendelangle** [comment]
@cherniavskii I'll that one to you, should probably go to the board

**Comment by PlxntKid** [comment]
I solved it:

  const [selectionModel, setSelectionModel] = useState([]);
  const [previousSelection, setPreviousSelection] = useState([]);

  const handleSelectionModelChange = (newSelection) => {
      setSelectionModel(newSelection)
      setPreviousSelection(newSelection)
      const newSelectionSet = newSelection.filter((element) => !previousSelection.includes(element));
      setSelectionModel(newSelectionSet)
      console.log(newSelectionSet)
      setPreviousSelection(newSelectionSet)
    }

**Comment by noghartt** [comment]
Any update on this issue?
If not, I can send a PR trying to fix it.

**Comment by 1pharaxh** [comment]
I was able to fix this by 
```
<DataGrid
checkboxSelection
onRowSelectionModelChange={(params) => {
  if (params.length > 1) {
    params.shift();
  }
}}
/>
```

**Comment by Skoob1905** [comment]
@1pharaxh, I tried this myself but for some reason if you select 2 they both stay checked, but if you select 3, then it will remove the last one. something weird is happening. but I've had this problem and still no reliable solution.

**Comment by PieterRomeyns** [comment]
Is there a way to be able to select multiple rows with the checkboxes,  but only one row at a time on rowclick?
