### ISSUE TITLE
[DatePicker] Property 'clearable' does not exist on type 'IntrinsicAttributes & DatePickerProps<Date, Date> & RefAttributes<HTMLDivElement>'

### ISSUE THREAD

**Issue by zigang93** [mui/mui-x#5287]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

not sure why `clearable` props is not found in `<DatePicker>` components.

env: I am using react 18
<img width="819" alt="Screenshot 2022-06-22 at 3 46 28 PM" src="https://user-images.githubusercontent.com/11520821/174974203-7ed8b685-b213-4649-97b2-4f4466d17025.png">

### Expected behavior 🤔

should be able to use `clearable` props

### Steps to reproduce 🕹

https://github.com/zigang93/mui-datepicker-reproduce-error <-- reproduce repo.. 
try uncomment line 13 of `BasicDatePicker.tsx` under the components folder

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
It has been removed in [`alpha.4`](https://github.com/mui/mui-x/releases/tag/v5.11.1) in favor of an `actionBar` slot

We have an ongoing PR to document this #5267 ([doc preview](https://deploy-preview-5267--material-ui-x.netlify.app/x/react-date-pickers/custom-components/)) if some stuff are unclear in the doc preview don't hesitate to ask
