### ISSUE TITLE
[data grid] "Hide all" hides `hideable: false` columns when `columnVisibilityModel` is passed via `initialState`

### ISSUE THREAD

**Issue by martin056** [mui/mui-x#5297]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I can hide columns that have `hideable: false` using the `Hide all` button. This makes the whole Data Grid blank.

https://user-images.githubusercontent.com/12865325/175250152-830598d9-2804-4982-ba42-7ecf306f4d6a.mp4

### Expected behavior 🤔

Columns that have `hideable: false` should always be visible.

### Steps to reproduce 🕹

Steps:

1. Create a new Data Grid
2. Pass `hideable: false` to some of the `columns`
3. Pass `initialState` with `columnVisibility` (NOTE: The issue can be reproduced even if you pass `columnVisibility: {}`)
4. Go to your component and press the `Hide all` button

The issue is reproduced here: https://codesandbox.io/s/data-grid-community-forked-5q7ikp

### Context 🔦

I'm trying to achieve the following:

* I don't want to display some of the columns by default. I control this by passing `initialState`
* I want to have columns that cannot be hidden. I control this by passing `hideable: false` when I define the `columns` object

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
  Binaries:
    Node: 17.5.0 - ~/.nvm/versions/node/v17.5.0/bin/node
    Yarn: 3.1.1 - ~/.yarn/bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 101.0.1
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.85 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.86 => 5.0.0-alpha.86 
    @mui/material: ^5.8.4 => 5.8.4 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.4 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.4 
    @mui/x-data-grid: ^5.12.2 => 5.12.2 
    @mui/x-date-pickers:  5.0.0-alpha.1 
    @types/react: ^18.0.7 => 18.0.7 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.7.4 => 4.7.4
```
</details>

**Comment by flaviendelangle** [comment]
RIght now `hideable` is only used during interaction
Meaning that if a column is set as hidden, `hideable` will not prevent that.

But `groupable` is preventing the grouping of columns present in the model, same for `aggregable`.
So I think the behavior change you are proposing make sense.

**Comment by martin056** [comment]
Thank you for your quick response :bow:
