### ISSUE TITLE
[data grid] Access parent / grouped row from children

### ISSUE THREAD

**Issue by ErnestBrandi** [mui/mui-x#5300]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi, I would like to access the parent row from a child row in order for that parent row to display an average (numeric) value of children ones. Puts differently I would like the opposite of `getRowGroupChildren`.

I tried retrieving parents rows using `getAllRowIds` and comparing row's `areaName` and `name`, but that function only return ids for children rows.

**Comment by flaviendelangle** [comment]
>  for that parent row to display an average (numeric) value of children ones

This looks a lot like #213

But if you want to build something today manually, your can access the id of the parent with `rowNode.id`
Here is [an example](https://codesandbox.io/s/data-grid-premium-forked-72n3ct?file=/src/App.tsx)

**Comment by ErnestBrandi** [comment]
Thanks for the example. I think I had a problem with my `apiRef` not being properly forwarded to my child comp, and therefore returning inconsistent values.
