### ISSUE TITLE
[data grid] How to use `apiRef.current.setColumnWidth`

### ISSUE THREAD

**Issue by JvilleDjango** [mui/mui-x#5306]
### Order ID 💳

0a4021c75b50bbacdd188d93399d3373T1JERVI6MzE4MzksRVhQSVJZPTE2Njc0MjA0NzgwMDAsS0VZVkVSU0lPTj0x

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am trying to persist columns widths in the table so, I am storing all colDefs of the columns that have changed using the "onColumnWidthChange()" in an array and then on load I want to set the widths to the values I stored using "setColumnWidth" .

example: apiRef.current.setColumnWidth([{ field: "wave", width: 400 }]);

I keep getting this error: TypeError: operand.replace is not a function

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Chrome

 System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.2.0 - C:\IDentify\Identify.Client\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.83
    @mui/icons-material: ^5.8.1 => 5.8.2
    @mui/lab: ^5.0.0-alpha.84 => 5.0.0-alpha.84
    @mui/material: ^5.8.2 => 5.8.2
    @mui/private-theming:  5.8.0
    @mui/styled-engine:  5.8.0
    @mui/styles: ^5.8.0 => 5.8.0
    @mui/system:  5.8.2
    @mui/types:  7.1.3
    @mui/utils:  5.8.0
    @mui/x-data-grid: 5.12.0 => 5.12.0
    @mui/x-data-grid-generator: 5.12.0 => 5.12.0
    @mui/x-data-grid-premium:  5.12.0
    @mui/x-data-grid-pro: ^5.12.0 => 5.12.0
    @mui/x-date-pickers:  5.0.0-alpha.1
    @mui/x-license-pro:  5.12.0
    @types/react:  17.0.5
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript:  4.7.2
```
</details>

**Comment by flaviendelangle** [comment]
![image](https://user-images.githubusercontent.com/3309670/175490144-db71e33e-a094-43e0-b92e-7b3b38b7bc51.png)

You are not giving it the right arguments
If you don't have intellisense or TypeScript, you can always take a look at [the GridApi doc page](https://mui.com/x/api/data-grid/grid-api/#main-content) if you have a doubt about a function signature
