### ISSUE TITLE
[DateRangePicker] Drag date marker to edit a range

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#5311]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

If you can pick the right dates in the first three clicks everything is perfect. 

The pain starts when you want to edit the `To` date.
On the current behavior, the 4th click is considered a new `From` date, and now you have to fix `From` and `To`, which would require again 2 more clicks. Basically to edit the `To` date, you need to reset the full range.

https://mui.com/x/react-date-pickers/date-range-picker/#static-mode

### Examples 🌈

https://react-spectrum.adobe.com/react-spectrum/RangeCalendar.html

### Motivation 🔦

Smoothier user experience.

**Comment by LukasTy** [comment]
Hi @gerdadesign 
It would be nice to have your input on the design and possibly UX part of this issue.
I've started the implementation of selected range editing by dragging the start or end date buttons.

The current implementation uses `preview selection` styles—they were created to allow for easy range extending selection, but they don't work at all when trying to shrink the selected range.

- What kind of styling ideas would you have for the drag range selection preview—while the dragging is in process
- Do you think it still makes sense to have this range extending/preview behaviour?
  - it only lets the user extend the range in one direction at a time (the current active selection position)
  - it works only in desktop mode—on mobile it's impossible to trigger it

**Initial drag selection implementation:**

https://user-images.githubusercontent.com/4941090/197788580-52cc3a8b-7273-49b9-a1a2-b12d062a39f6.mov

**Current range extending/preview implementation:**

https://user-images.githubusercontent.com/4941090/197788946-9bccbe21-55e6-4e21-922d-bf8f11d856c7.mov

[Spectrum is simply](https://react-spectrum.adobe.com/react-spectrum/RangeCalendar.html) moving the selected date while dragging without a separate styling

**Comment by LukasTy** [comment]
Hello @gerdadesign @joserodolfofreitas 
I've gone with a similar approach to Spectrum. Below is a demonstration of the current behaviour. Do you have any insights on it? Things you'd like to improve, add or change? 🤔 

I've tried going with a different styling only for the dragging part—but both the styles and code was becoming spaghetti with no tangible benefits.

https://user-images.githubusercontent.com/4941090/199935900-23b1b71e-749b-4507-9d43-1c283e86f02a.mov

**Comment by joserodolfofreitas** [comment]
That's great work, @LukasTy (and apologies for my late reply)!
Really nice that you put effort into styling the initial value of the dragging marker. I think it clearly has a positive impact on UX;

> Do you think it still makes sense to have this range extending/preview behavior?

I think both behaviors complement each other, and it's fine that it works only on desktops. Is it becoming a burden to maintain together with dragEditing?

**Comment by LukasTy** [comment]
> I think both behaviors complement each other, and it's fine that it works only on desktops. Is it becoming a burden to maintain together with dragEditing?

Nope, I don't see any issues in maintaining both behaviours. The only issue is the increase in computations (date comparisons) we need to do when rendering calendar.
The biggest issue would be (was when I did experiment with it) styling only the dragging range differently to the highlighted/selected range—hence my decision to go the simple route and use same styling.
