### ISSUE TITLE
Is there a github issue for building a file upload button?

### ISSUE THREAD

**Issue by PraveenPeri** [mui/mui-x#5334]
### Order ID 💳

33625

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Trying to find the issue for building file upload button and the proposed features. Looking for a tentative release timeline. I can see it in the [roadmap here](https://mui.com/material-ui/discover-more/roadmap/#new-components) but not on github

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Thanks for opening this issue. We don't have a date to release the file upload component. It won't receive focus too soon due to the community asking for other components, e.g. [charts](https://github.com/mui/mui-x/issues/1408).
