### ISSUE TITLE
Getting invalid license message on the component. 

### ISSUE THREAD

**Issue by CodesOf-Partha** [mui/mui-x#5337]
### Order ID 💳

45790

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Initialised the license in high level component. Still getting invalid license issue. Verified multiple times for typo.
<img width="873" alt="Screenshot 2022-06-28 at 2 48 48 PM" src="https://user-images.githubusercontent.com/37892718/176142797-0be022c8-b1b2-46ae-8958-496b2f2dcb08.png">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  **Brave Browser**

  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.4.0 => 11.9.3 
    @emotion/styled: ^11.3.0 => 11.9.3 
    @mui/base:  5.0.0-alpha.64 
    @mui/icons-material: ^5.0.3 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.50 => 5.0.0-alpha.64 
    @mui/material: ^5.0.3 => 5.8.5 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/styles: ^5.0.1 => 5.2.3 
    @mui/system: ^5.0.3 => 5.8.5 
    @mui/types:  7.1.4 
    @mui/utils: ^5.0.1 => 5.8.4 
    @mui/x-data-grid: ^5.0.0-beta.3 => 5.12.3 
    @mui/x-data-grid-generator: ^5.12.3 => 5.12.3 
    @mui/x-data-grid-premium: ^5.12.3 => 5.12.3 
    @mui/x-data-grid-pro:  5.12.3 
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-license-pro: ^5.12.3 => 5.12.3 
    @types/react:  17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.5 => 5.3.5

```
</details>

**Comment by m4theushw** [comment]
Could you verify if you're using the latest version of `@mui/x-license-pro`? If you bought the license recently it will only work with recent versions.

**Comment by CodesOf-Partha** [comment]
@m4theushw I got the issue. I was trying to implement the premium design with pro plan. Pro plan design works fine in website. Thanks for the immediate response!
