### ISSUE TITLE
Quick filter substring search is inconsistent

### ISSUE THREAD

**Issue by majaSKIL** [mui/mui-x#5338]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The Quick filter demo here exhibits inconsistent behaviour: https://mui.com/x/react-data-grid/filtering/#quick-filter

Searching for "French" will return countries starting with "French" and names containing "French": this is expected. 
**Filtering often succeeds for names and does not for countries:**

- Searching for "oo" will return "Susan Cook" in the results, but not "Cameroon".
- Searching for "Island" does not return "Bouvet Island".
- Searching for "Marie Brown" returns "Marie Brown", but searching for "French Guiana" does not return "French Guiana".

### Expected behavior 🤔

Filtering should be consistent across text fields.

- Searching for "oo" should return "Susan Cook" and "Cameroon".
- Searching for "Island" should return "Bouvet Island".
- Searching for a full country name should return that country, e.g. "French Guiana". (I realize this filters on "French" and "Guiana", but both of those are substrings of "French Guiana", so it shouldn't matter.)

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/x/react-data-grid/filtering/#quick-filter
2. Use the search input to run the examples detailed above

Please note: I haven't tried using the quick filter in our project yet, but I don't see the point in trying if the demo in the docs is so buggy 😅

### Context 🔦

Was testing out the Quick Filter demo and discovered these bugs by accident, just testing out the basic functionality.

### Your environment 🌎

N/A

### Order ID 💳 (optional)

34039

**Comment by cherniavskii** [comment]
Closing as I can no longer reproduce the issue using the latest v6 version of the Data Grid: https://codesandbox.io/p/sandbox/white-lake-2pszdx?file=%2Fpackage.json%3A11%2C23
