### ISSUE TITLE
Support from clipboard paste (copy/paste from excel, for example)

### ISSUE THREAD

**Issue by bggoxp** [mui/mui-x#5342]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I was wondering if there are any plans to support pasting from the clipboard across multiple cells, just like in excel or ag-grid, where you can copy from an excel document and paste on the data grid.

### Examples 🌈

https://ag-grid.com/javascript-data-grid/clipboard/

**Comment by flaviendelangle** [comment]
Duplicates https://github.com/mui/mui-x/issues/199

It's a major feature we are planning to build.
But it has not been prioritized yet.
