### ISSUE TITLE
[DatePicker] Cannot Distribute Date/Time Pickers as Part of Shared Component Library

### ISSUE THREAD

**Issue by BenByrdInMarket** [mui/mui-x#5349]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

My organization (InMarket Media LLC) has begun using a shared React component library to develop its UI, which is essentially an extension of MUI v5 with a custom theme. The vast majority of our components are simply aliases of MUI components. Users of the UI Kit wrap their <App /> component in MUI's ThemeProvider and StyledEngineProvider components, which are also exported directly from our shared library.

This architecture has worked well, until I tried incorporating the DatePicker components (https://mui.com/x/react-date-pickers/getting-started/). I was able to get DatePickers functioning in our UI Kit storybook (at least locally), but as soon as I tried to share these components via our UI Kit, I began seeing errors like the following:

"**_Uncaught Error: MUI: Can not find utils in context. It looks like you forgot to wrap your component in LocalizationProvider, or pass dateAdapter prop directly. at useLocalizationContext (useUtils.js:32:1)_**"

I have tried directly wrapping our components in the <LocalizationProvider> wrapper. I have also tried exporting LocalizationProvider as part of the UI Kit, and then wrapping the component in the child application. Finally, I tried importing <LocalizationProvider> directly from MUI in the child application, and wrapping the shared component that way. All of these approaches yielded the error above. 

Is there a way to distribute the DatePicker components from MUI-X as part of a shared component library? If not, are plans for this tentatively on the development roadmap?

Thanks!

### Expected behavior 🤔

I would expect to be able to distribute MUI-X's DatePicker components as part of a shared component library.

### Steps to reproduce 🕹

Steps:

1. Create a simple Shared Component Library in React, which offers the DatePicker components from MUI-X 
2. Create a child application (create-react-app will do) and try importing and using the DatePicker components from the shared library. A simple development build (npm install, npm start) should be sufficient.
3. Observe behavior, check the console for the error I described.

### Context 🔦

I am trying to offer DatePickers as part of an MUI v5-based Shared Component Library. Currently, all of our applications will need to import the DatePickers themselves and add an MUI dependency, or we will need to hand-roll our own.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 12.4
  Binaries:
    Node: 12.22.11 - ~/Apps/InMarKit/node_modules/.bin/node
    Yarn: 3.0.2 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/Apps/InMarKit/node_modules/.bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Edge: Not Found
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.83 
    @mui/icons-material: ^5.8.2 => 5.8.2 
    @mui/lab: ^5.0.0-alpha.84 => 5.0.0-alpha.84 
    @mui/material: ^5.8.2 => 5.8.2 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine: ^5.8.0 => 5.8.0 
    @mui/system: ^5.8.2 => 5.8.2 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-data-grid: ^5.8.0 => 5.11.1 
    @mui/x-date-pickers: ^5.0.0-alpha.7 => 5.0.0-alpha.7 
    @types/react: ^17.0.41 => 17.0.45 
    react:  17.0.2 
    react-dom:  17.0.2 
    styled-components: ^5.3.3 => 5.3.5 
    typescript: >=3.5 => 4.7.2
```
</details>

**Comment by flaviendelangle** [comment]
Hi

It would be a lot easier for us to find what's wrong with a reproduction case.
If your shared component library is public, can you link it ? If it's not but you agree to give access to one of us, we can go have a look. If not, you can try to create a new public repo with just your datepicker wrapper and see if you still have the problem.

The cause of your error might be that you are bundling several versions of `@mui/x-date-pickers`, one is creating the context and another one consuming it so it does not find it and the library is not a singleton.

**Comment by BenByrdInMarket** [comment]
Thanks so much for the quick response @flaviendelangle. Our shared component library is a private NPM package. I would be happy to grant access, but first, I'll try a smaller use case, with @mui/x-date-pickers as a singleton as you mentioned.

**Comment by jlaurelli** [comment]
> Was able to solve this. Thanks!

I know this is closed, but @BenByrdInMarket, what was your strategy for doing so? I've been stuck on a similar situation for a little while now.

**Comment by Fafruch** [comment]
Alright, we were able to fix that by making sure that our bundle uses exactly the same version for `@mui/x-date-pickers` + `@mui/lab` (the difference in the `@mui/lab` versions caused other errors). 

In other words, all packages that were in dependencies (also the private packages shared by our private registry) had to use the same above-mentioned packages. After we unified them, it could have been verified in the `yarn.lock` they are resolving to exactly the same versions - and now the error is gone. 🎉

**Comment by LukasTy** [comment]
@Fafruch @jlaurelli Maybe you both are experiencing the issue because of the same reason?
If you have `@mui/lab` as a dependency (do you use anything from it?) and `@mui/x-date-pickers`—you have to make sure that the `lab` package is at least somewhat new—with pickers code removed from it.
In any case, anytime you have a problem—it would be best if you could provide at least a minimal reproduction sample (codesandbox or any other way) or at least list your package versions (`npx @mui/envinfo` can help here) you are using.

**Comment by maxmann74** [comment]
I am having this same issue, but we are not using @lab at all since the datepicker is moved to @mui/x-date-pickers. Are there any restrictions to exporting this component in our own private package? 

So I have packageA, and appA. They both use the exact same versions of @mui/x-date-pickers

packageA exports "MyCustomDateComponent", which uses @mui/x-date-picker DatePicker.  

In appA, if I do this, I get the error: MUI: Can not find the date and time pickers localization context.
<LocalizationProvider dateAdapter={AdapterDayJs}>
   <MyCustomDateComponent/>
 </LocalizationProvider>

If I DIRECTLY use @mui/x-date-pickers DatePicker in appA, it works..  
<LocalizationProvider dateAdapter={AdapterDayJs}>
   <DatePicker/>
 </LocalizationProvider>

So seems there is some restriction around exporting DatePicker in a package?  If not, I have no idea what to try next. Thanks

**Comment by davemanroth** [comment]
Having the exact same issue as @maxmann74 with the exact same set of criteria. Not using @mui/lab, exact same versions of @mui/x-date-picker on both package and app, same error message. 

Any suggestions would be greatly appreciated. Thank you!

**Comment by maxmann74** [comment]
Fyi for now I simply wrapped our  custom date component in the LocalizationProvider. I know this isn't a great solution as every instance will have a provider.. but it works.

**Comment by KartheekJavvaji** [comment]
Module federation wont work over here because of the way of importing the provider. 
We have imports such as `../../LocalizationProvider/LocalizationProvider` or `../../../LocalizationProvider` in 4 different files. For the `ConsumeSharedPlugin` to be able to understand whether or not to create a shareable singleton, it should be able to match the import references. 

Its internal logic `request.startsWith(prefix)` will translate to `'../../LocalizationProvider/LocalizationProvider'.startsWith('@mui/x-date-pickers/')` , which will not match.

This will be fixed once these import statements change to `@mui/x-date-pickers/LocalizationProvider`

@flaviendelangle ^

**Comment by LukasTy** [comment]
> I can raise a PR for these changes

We'd love it if you could raise a PR fixing this case, especially when you seem to understand the problem and have a possible reproduction that you can test the temporary release on. 👌 💯

**Comment by flaviendelangle** [comment]
I'm not sure this will be enough
The core is doing the same in all their components:

https://github.com/mui/material-ui/blob/a731e863cb13c83f4d6b9b4c7dd3633fad8f1ed4/packages/mui-material/src/Autocomplete/Autocomplete.js

So I would expect the problem to remain even if we change all the import on our side.

And I would not be surprised if absolute imports were problematic in some scenario, but maybe @mnajdova or @oliviertassinari knows why we are not using them throughout the codebase.

**Comment by mnajdova** [comment]
I would be curious to see a reproduction repository first, in my opinion, if someone is still experiencing this it could be a mismatched version, and hence ending up with two versions of the context provider, or some misconfiguration on client's side. Emotion also has a global context provider and they have local imports, and this has never been an issue.

**Comment by KartheekJavvaji** [comment]
So, we have a monorepo that has a component library, which internally uses mui and mui-x libs. A root application, which is responsible for creating common instances (like context providers, redux setup) and sharing dependencies across federated applications/modules. So there is no possibility of having a duplicate version of lib.

When I tried to replicate the same scenario in a fresh setup, the issue was not reproducing. Seems like there is some other issue present(webpack setup? although I tried to put the exact config) and not any issue with the code of mui-x-date-picker. I will soon post the code of the fresh setup to serve as a working example for other devs, who are looking to share date-picker-related context providers with module federation. 

Thank you @mnajdova , @flaviendelangle and @LukasTy for your inputs.

I will update here if I am able to find anything else on why this happens with certain (webpack?) setup. For now, I am using patch-package for changing the import statements and it works.

**Comment by KartheekJavvaji** [comment]
here is the [codesandbox](https://codesandbox.io/p/github/KartheekJavvaji/mfe/MFE-with-mui-x-date-pickers?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo4qwtez00073b6mb2xst04s%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo4qwtez00033b6majuyfgtg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo4qwtez00053b6mbzlqas3t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo4qwtez00063b6mzqcqfrm1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo4qwtez00033b6majuyfgtg%2522%253A%257B%2522id%2522%253A%2522clo4qwtez00033b6majuyfgtg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clo4qwtez00063b6mzqcqfrm1%2522%253A%257B%2522id%2522%253A%2522clo4qwtez00063b6mzqcqfrm1%2522%252C%2522activeTabId%2522%253A%2522clo4r8bak01ts3b6mz3x29ohi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A8080%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clo4r8bak01ts3b6mz3x29ohi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Froute1%2522%257D%255D%257D%252C%2522clo4qwtez00053b6mbzlqas3t%2522%253A%257B%2522id%2522%253A%2522clo4qwtez00053b6mbzlqas3t%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo4qwtez00043b6maj7jhjsa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo4qwtui002jehgu3hvg4bi5%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clo4qwv2n006x3b6moi64uewx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clo4qwv2n006x3b6moi64uewx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) link

**Comment by LukasTy** [comment]
@KartheekJavvaji If you no longer have an issue in a fresh setup, maybe your actual application initially had an older version of the library, where singleton `LocalizationProvider` was necessary for proper `localeText` management?
Could you clarify what was the root problem your were having with module federation? 🤔 

For quite some time now we support nested `LocalizationProvider` instances and even our exported components have a wrapping `LocalizationProvider` to handle `localeText` merging.

Correct me if my memory serves me wrong @flaviendelangle. 🤔

**Comment by flaviendelangle** [comment]
I confirm that we did not support nested `LocalizationProvider` before.
So the following example would have removed all the `frFR` translations in `WrappedPicker`.

```tsx
const WrappedPicker = (props) => (
  <LocalizationProvider localeText={{ confirmLabel: 'Hello' }}>
    <DatePicker {...props}
  <LocalizationProvider />
)

export default function App() {
  return (
    <LocalizationProvider localeText={frFR}>
      <WrappedPicker />
    <LocalizationProvider />
  )
}
```

But I don't think a singleton was necessary, setting a `LocalizationProvider` on top of each picker should work fine, unless I'm missing something.

But in any case, I totally agree that we need an example with a recent version of the pickers in order to understant what the problem is.

**Comment by KartheekJavvaji** [comment]
@LukasTy , I tried debugging why webpackRequire is trying to get a new copy of the localization provider in my above monorepo setup. 
It's very strange, but it works when I change the value of `output.uniqueName` to a different value. I was unable to find any reasoning/logic behind it yet. But with just this one change, my existing setup is working as expected wrt singleton 🫠. Maybe there is some logic connecting the name I provide to the federationConfig and this `output.uniqueName` key.

**Comment by LukasTy** [comment]
@KartheekJavvaji Thank you for confirming your use case details.
We are glad to hear that you were able to resolve the problem by altering the configuration. 👍 
Module federation is still a somewhat fresh feature that probably has negligible usage as compared to regular setups, hence, it's logical that various edge case issues and strange behaviors might pop up. 🙈 

If you experience any other problem, don't hesitate to open a new issue. 😉

**Comment by guicara** [comment]
I have exactly the same issue described by @BenByrdInMarket on his initial message.

I will try to create a small reproduction case.

In the meantime, the _only_ solution I have is to wrap my design system components in a `LocalizationProvider` and to pass `dateAdapter` and `adapterLocale` as props. It's not great however.

e.g.

**On my design system side:**

```ts
import { DatePickerProps } from '@mui/x-date-pickers-pro';
import { PickerValidDate } from '@mui/x-date-pickers/models';

interface CustomDatePicker extends DatePickerProps<TDate, TEnableAccessibleFieldDOMStructure> {
  dateAdapter?: any;
  adapterLocale?: any;
}
```

```ts
import { DatePicker, LocalizationProvider } from '@mui/x-date-pickers-pro';

function CustomDatePicker<TDate extends PickerValidDate, TEnableAccessibleFieldDOMStructure extends boolean = false>(props: CustomDatePicker<TDate, TEnableAccessibleFieldDOMStructure>) {
  const { dateAdapter, adapterLocale, ...rest } = props;

  return (
    <LocalizationProvider dateAdapter={dateAdapter} adapterLocale={adapterLocale}>
      <DatePicker ... />
    </LocalizationProvider>
  );
}
```

**On my app side (that consume the design system):**

```ts
import { AdapterDateFns } from '@mui/x-date-pickers-pro/AdapterDateFns';
import { fr } from 'date-fns/locale';

<CustomDatePicker dateAdapter={AdapterDateFns} adapterLocale={fr} />
```

**Comment by Shelrothman** [comment]
Any updates on this? Same issue here as @maxmann

**Comment by michelengelen** [comment]
> I have exactly the same issue described by @BenByrdInMarket on his initial message.
> 
> I will try to create a small reproduction case.
> 
> In the meantime, the _only_ solution I have is to wrap my design system components in a `LocalizationProvider` and to pass `dateAdapter` and `adapterLocale` as props. It's not great however.
> 
> e.g.
> 
> **On my design system side:**
> 
> ```ts
> import { DatePickerProps } from '@mui/x-date-pickers-pro';
> import { PickerValidDate } from '@mui/x-date-pickers/models';
> 
> interface CustomDatePicker extends DatePickerProps<TDate, TEnableAccessibleFieldDOMStructure> {
>   dateAdapter?: any;
>   adapterLocale?: any;
> }
> ```
> 
> ```ts
> import { DatePicker, LocalizationProvider } from '@mui/x-date-pickers-pro';
> 
> function CustomDatePicker<TDate extends PickerValidDate, TEnableAccessibleFieldDOMStructure extends boolean = false>(props: CustomDatePicker<TDate, TEnableAccessibleFieldDOMStructure>) {
>   const { dateAdapter, adapterLocale, ...rest } = props;
> 
>   return (
>     <LocalizationProvider dateAdapter={dateAdapter} adapterLocale={adapterLocale}>
>       <DatePicker ... />
>     </LocalizationProvider>
>   );
> }
> ```
> 
> **On my app side (that consume the design system):**
> 
> ```ts
> import { AdapterDateFns } from '@mui/x-date-pickers-pro/AdapterDateFns';
> import { fr } from 'date-fns/locale';
> 
> <CustomDatePicker dateAdapter={AdapterDateFns} adapterLocale={fr} />
> ```
> 
> PS: @flaviendelangle this issue has been closed. is it possible to reopen it? Do you need my reproduction case? Can I create a support ticket with my premium support subscription?

If you could open up a new ticket and include your specific reproduction that would help a lot. 
This issue is kind of old and also has unrelated information. So it would be best to start a fresh issue and link this (or specific comments) for reference.

If you can include the premium order-id that would be great as well.

Thanks! 🙇🏼

**Comment by stefba** [comment]
I solved my issue by changing the import from

`import { DatePicker } from '@mui/x-date-pickers/DatePicker';`

to

`import { DatePicker } from '@mui/x-date-pickers';`

**Comment by guicara** [comment]
> > I have exactly the same issue described by @BenByrdInMarket on his initial message.
> > I will try to create a small reproduction case.
> > In the meantime, the _only_ solution I have is to wrap my design system components in a `LocalizationProvider` and to pass `dateAdapter` and `adapterLocale` as props. It's not great however.
> > e.g.
> > **On my design system side:**
> > ```ts
> > import { DatePickerProps } from '@mui/x-date-pickers-pro';
> > import { PickerValidDate } from '@mui/x-date-pickers/models';
> > 
> > interface CustomDatePicker extends DatePickerProps<TDate, TEnableAccessibleFieldDOMStructure> {
> >   dateAdapter?: any;
> >   adapterLocale?: any;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ts
> > import { DatePicker, LocalizationProvider } from '@mui/x-date-pickers-pro';
> > 
> > function CustomDatePicker<TDate extends PickerValidDate, TEnableAccessibleFieldDOMStructure extends boolean = false>(props: CustomDatePicker<TDate, TEnableAccessibleFieldDOMStructure>) {
> >   const { dateAdapter, adapterLocale, ...rest } = props;
> > 
> >   return (
> >     <LocalizationProvider dateAdapter={dateAdapter} adapterLocale={adapterLocale}>
> >       <DatePicker ... />
> >     </LocalizationProvider>
> >   );
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **On my app side (that consume the design system):**
> > ```ts
> > import { AdapterDateFns } from '@mui/x-date-pickers-pro/AdapterDateFns';
> > import { fr } from 'date-fns/locale';
> > 
> > <CustomDatePicker dateAdapter={AdapterDateFns} adapterLocale={fr} />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PS: @flaviendelangle this issue has been closed. is it possible to reopen it? Do you need my reproduction case? Can I create a support ticket with my premium support subscription?
> 
> If you could open up a new ticket and include your specific reproduction that would help a lot. This issue is kind of old and also has unrelated information. So it would be best to start a fresh issue and link this (or specific comments) for reference.
> 
> If you can include the premium order-id that would be great as well.
> 
> Thanks! 🙇🏼

Hi @michelengelen,

We have created a specific reproduction case that you can find here:

https://github.com/Seb-GRAF/design-system-consumer
https://github.com/Seb-GRAF/design-system

We have a MUI X Premium license. Here is our support key / order ID: 96178

Best,

**Comment by Lieblein** [comment]
I had the same issue (a custom `DatePicker` in my UI kit + `LocalizationProvider` in my app). I resolved it by moving all imports of `@mui/x-date-pickers` to my UI kit and placing the `LocalizationProvider` in the layout component. This way, I no longer need to wrap every `DatePicker` in a `LocalizationProvider`.
