### ISSUE TITLE
[data grid] ColSpan undefined if allColumns: true Excel Export

### ISSUE THREAD

**Issue by PrimulaX** [mui/mui-x#5353]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you have more than one column hide and `allColumns: true` in excel options there is an error:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/16132259/176623004-fbdb33a3-1c0b-41f6-a135-5cbaeb9b44b3.png">

CSB: https://codesandbox.io/s/excelcustomexport-demo-mui-x-forked-lmqsv7?file=/demo.tsx

### Expected behavior 🤔

Export should work with hiding columns

### Steps to reproduce 🕹

Steps:

1. Hide more than one column
2. Pass excel options with `allColumns: true`
3. Press Excel Export

**Comment by cherniavskii** [comment]
I can reproduce it with this codesandbox by just clicking "Download as Excel": https://codesandbox.io/s/excelcustomexport-demo-mui-x-forked-jjn3j5
