### ISSUE TITLE
[data grid] Data flickering issue while vertical scroll when column span is enabled in mui x-data-grid

### ISSUE THREAD

**Issue by vishnuchaitanyadeevi** [mui/mui-x#5354]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the column span is used in the x-data-grid to display huge data(20+ rows), when we scroll, then the data is flickering(empty rows are visible in between).

It is getting scrolled up and down by itself.

please refer the added video below.

https://user-images.githubusercontent.com/86829812/176627296-9d4d408a-21d9-4f45-b272-bf44acf4c743.MOV

my package.json is below
![image](https://user-images.githubusercontent.com/86829812/176628135-a0ddaaa1-2647-4118-b04b-e7575bc28d21.png)

.

### Expected behavior 🤔

When using the column span feature, when we scroll, the data should be visible without flickering.

### Steps to reproduce 🕹

Steps:

1.Add x-data-grid to the react application.
2. Add the column span to alter the columns.
3.Add 50+ records to it.
4.Try to scroll, the table starts flickering.

### Context 🔦

We are unable to display the table with column span. It is flickering automatically.

Please find the demo of the issue here.
https://codesandbox.io/s/oov6iu?file=/src/datagrid.js

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @vishnuchaitanyadeevi 
Can you create a minimal example reproducing the issue? You can start with this demo https://codesandbox.io/s/o74koo?file=/demo.tsx or any other demo you can find in our docs.
Thanks!

**Comment by VaibhavLande12** [comment]
https://codesandbox.io/s/oov6iu?file=/src/datagrid.js

we have added the code in the above sandbox link and are also able to replicate the issue.

attaching video for the same

**Comment by vishnuchaitanyadeevi** [comment]
Please Re-open the issue.

**Comment by cherniavskii** [comment]
Thanks @VaibhavLande12 for the demo!
I can reproduce it even without `colSpan` https://codesandbox.io/s/quiet-fire-l6ll5f?file=/src/App.js

https://user-images.githubusercontent.com/13808724/178214680-10f7a929-15a9-4510-8c39-53e690919df8.mov

I will look into it

**Comment by cherniavskii** [comment]
I've created this simplified example: https://codesandbox.io/s/quiet-fire-l6ll5f?file=/src/datagrid.js
The root cause of the issue seems to be `<TextField multiline />` used in `renderCell`.
Seems to work fine without `multiline`: https://codesandbox.io/s/empty-fire-fo1q52?file=/src/datagrid.js

What is the purpose of using `TextField` in `renderCell`?

**Comment by VaibhavLande12** [comment]
we need a big text box size to show more contents.Thats why we added mutilne

**Comment by cherniavskii** [comment]
> we need a big text box size to show more contents.Thats why we added mutilne

But why use `TextField` for displaying data? Are you implementing data editing?

**Comment by PrasadLondhe** [comment]
Yes, We do have data edition on grid and requirement is to view more data on grid in first glance

**Comment by cherniavskii** [comment]
You should use `renderEditCell` for editing functionality and `renderCell` for displaying data. You shouldn't use inputs in `renderCell`

**Comment by VaibhavLande12** [comment]
with renderEditCell nothing is getting rendered like textbox and Checkbox.

Also tried removing multiline still flickering.
Please find screenshot.
![image](https://user-images.githubusercontent.com/87651391/178470916-e8c1cd22-57ac-4112-b278-52f95cca7407.png)

**Comment by cherniavskii** [comment]
> with renderEditCell nothing is getting rendered like textbox and Checkbox.

It will be rendered once you enter edit mode - see [Editing docs](https://mui.com/x/react-data-grid/editing/)

> Also tried removing multiline still flickering.

Cannot reproduce it with this sandbox https://codesandbox.io/s/empty-fire-fo1q52?file=/src/datagrid.js
Can you provide a reproduction example?

**Comment by PrasadLondhe** [comment]
With RenderEditCell user need to double click to enable text field and type.. So not userful and its rejected by stakeholder

we will need some fix on flickering issues with multiline

**Comment by cherniavskii** [comment]
@PrasadLondhe Using `renderCell` for editing is not recommended, therefore this issue will a low priority for us to investigate.
I would suggest either using our editing API or avoid using `multiline` to avoid flickering.

**Comment by cherniavskii** [comment]
I tried to reproduce the issue with proper editing API using `renderEditCell` and there is an issue with scrolling:
https://codesandbox.io/s/priceless-darkness-lup4pv?file=/src/datagrid.js:391-405

https://user-images.githubusercontent.com/13808724/179557244-93e61b8c-0957-4e85-9291-bad0309d7564.mov

It's not flickering, because there's only one `TextField` rendered at a time, but the issue is not reproducible without `multiline` prop:
https://codesandbox.io/s/laughing-sunset-si8he7?file=/src/datagrid.js

**Comment by cherniavskii** [comment]
And with multiple cells being edited at the same time I can reproduce the flickering as well:
https://codesandbox.io/s/vigorous-clarke-wseeff?file=/src/datagrid.js

https://user-images.githubusercontent.com/13808724/179559617-0832a5ea-fc9b-45b4-b206-da34427664c2.mov

**Comment by arthurix** [comment]
@vishnuchaitanyadeevi I had the same issue. All my tables were flickering from nothing, but only on Chrome. The fix in my case was remove the element `Fade` above my custom `GridRow`.

**Comment by cherniavskii** [comment]
> And with multiple cells being edited at the same time I can reproduce the flickering as well: [codesandbox.io/s/vigorous-clarke-wseeff?file=/src/datagrid.js](https://codesandbox.io/s/vigorous-clarke-wseeff?file=/src/datagrid.js)
> 
>  Screen.Recording.2022-07-18.at.18.33.53.mov

This issue is still reproducible with the latest version of DataGrid (5.17.14): https://codesandbox.io/s/crazy-pond-reu568?file=/src/datagrid.js

**Comment by ithrforu** [comment]
Hello, @cherniavskii. I faced similar issue and found that the issue is only reproducible in Chrome.

**Comment by samihamine** [comment]
Hello, I am also experiencing the same problem on the latest version 5.17.17.
If you have a workaround, I would appreciate it until the fix is released. Thank you.

**Comment by waynea-bdlabs** [comment]
i added the prop disableVirtualization to DataGrid in it fixed it
