### ISSUE TITLE
[data grid] How to get updated values from custom component within `processRowUpdate`

### ISSUE THREAD

**Issue by adharshmk96** [mui/mui-x#5356]
I'm trying to use autocomplete as a custom component for editing cell, 
I'm unable to reflect changes within processRowUpdate method
Here's an example.

https://codesandbox.io/s/dreamy-tree-f0grx6?file=/src/App.js

**Comment by alexfauquette** [comment]
Two points about your custom edit cell:

```jsx
renderEditCell: (params) => {
        const valueOptions = stepData;

        return (
          <Autocomplete
            disablePortal
            options={valueOptions}
            value={params.row.stepName}
            onChange={(_, value) => {
              params.row.stepId = value.id;
              params.row.stepName = value.label;
            }}
            sx={{ width: params.colDef.width }}
            renderInput={(params) => <TextField {...params} />}
          />
        );
      }
```

First, you are using multiple times `params` to get values. One time to get the `renderEditCell` parameters and one time for the `renderInput` parameters. It's a good practice to avoid reusing the same naming in nested function to avoid being confused by scops

Second, you are mutation the parameters received by the `renderEditCell` when doing the following: `params.row.stepId = value.id;`. In react you should avoid mutating objects. To update the content of a row we provide some methods such as `apiRef.current.setEditCellValue`. Please see the following [documentation](https://mui.com/x/react-data-grid/editing/#create-your-own-edit-component):

> Once a new value is entered into the input, it must be sent to the grid. To do this, pass the row ID, the column field, and the new cell value to a call to `apiRef.current.setEditCellValue`. The new value will be parsed and validated, and the value prop will reflect the changes in the next render.

**Comment by adharshmk96** [comment]
hello @alexfauquette  I tried the suggestion given by you but, It is showing some errors 
```
React has detected a change in the order of Hooks called by GridRow. This will lead to bugs and errors if not fixed.
```
and it had no effect on my issue. The cell is now rendering empty.

**Comment by alexfauquette** [comment]
That's a point of the doc we are improving, could you have a look at the modification in #5158 to see if it solves your problem?

**Comment by himanshushukla31** [comment]
@adharshmk96 can you share the solution for this  (can access value inside processRowUpdate). Thanks
