### ISSUE TITLE
[pickers] Provide an ability to customise PickersYear (of YearsPicker)

### ISSUE THREAD

**Issue by amok** [mui/mui-x#5357]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Provide an ability to overwrite/decorate PickersYear props/behaviour/etc.

 It's possible to [use `renderDay` for customizing `Day`](https://github.com/mui/mui-x/blob/90d98c131d182bbb9a4ca11e3dd6398559525c0d/packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx#L212-L214) component, but PickersYear is not customizable 

### Examples 🌈

It could be done something like:

```jsx
const renderYear = args => {
    ...
}

<DatePicker renderDay={renderDay} renderYear={renderYear} />
```

### Motivation 🔦

We're trying to make our app compatible with US a11y law and requirements. It appears that neither `Day` nor `Year` are completely accessible. F.e. one of our requirements is to have `disabled` day/year/etc. focusable and navigatable (with keyboard). Unfortunately `tabIndex`/`selected`/`focus`/`disabled`/`aria-disabled` logic is hard-coded and there is no convenient way to overwrite it, for now we use dirty monkey-parching with `document.querySelector().setAttribute()` etc.

Examples of hard-coded logic:
- ["hard-coded" `disabled` logic, no way to use aria-disabled instead](https://github.com/mui/mui-x/blob/90d98c131d182bbb9a4ca11e3dd6398559525c0d/packages/x-date-pickers/src/YearPicker/YearPicker.tsx#L170)
- [no way to decorate/extend PickersYear (but there is renderDay for Day which allows to decorate Day)](https://github.com/mui/mui-x/blob/90d98c131d182bbb9a4ca11e3dd6398559525c0d/packages/x-date-pickers/src/YearPicker/YearPicker.tsx#L162)
- ["hard-coded" `tabIndex` logic, no way to make PickersDay keyboard-navigatable](https://github.com/mui/mui-x/blob/90d98c131d182bbb9a4ca11e3dd6398559525c0d/packages/x-date-pickers/src/YearPicker/PickersYear.tsx#L136)

**Comment by alexfauquette** [comment]
Hi, thanks for reporting this issue. I think we should do two things.

Allows to customize the Year buttons, but also do the accessibility fixes like moving from `disabled` to [`aria-disabled`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled)

**Comment by flaviendelangle** [comment]
Duplicates #4662
