### ISSUE TITLE
CalendarPicker props: renderDay

### ISSUE THREAD

**Issue by NinaFan0824** [mui/mui-x#5366]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using CalendarPicker components, the users can select multiple dates in my app. I used renderDay to meet the requirements, and this function is like`(date: Date, selectedDays: Array<Date | null>, pickersDayProps: PickersDayProps<Date>) => EmotionJSX.Element`
I tried to use the selectedDays prop, but it's always null. 

How can I use this to allow multiple dates selected?

### Expected behavior 🤔

Users select multiple dates.

### Steps to reproduce 🕹

Steps:

```
  const customDayRenderer = (
    date: Date,
    selectedDays: Array<Date | null>,
    pickersDayProps: PickersDayProps<Date>
  ) => {
    let selected = false
    dates?.forEach((dateInArray) => {
      if (isSameDay(dateInArray, date)) {
        selected = true
      }
    })

    return (
      <PickersDay
        {...pickersDayProps}
        selected={selected}
      />
    )
  }
```

```
 <CalendarPicker
        onChange={updateDates}
        date={null}
        renderDay={customDayRenderer}
      />
```

**Comment by alexfauquette** [comment]
The `selectedDays` is an array to support both the calendar and the date range picker.

- calendar sets `selectedDays={[date]}`
- date range picker set `selectedDays={[start, end]}`

For now the calendar is maint to select only one day. To support multiple day selection, you should maybe manage the array of selected dates on your own state (could be done by wrapping `Calendar` in a Provider) and use those data to set the `PickerDay`'s `selected` prop correctly

**Comment by NinaFan0824** [comment]
Thanks for your quick reply. and that's exactly what I did.

**Comment by noumanzahid047** [comment]
> The `selectedDays` is an array to support both the calendar and the date range picker.
> 
> * calendar sets `selectedDays={[date]}`
> * date range picker set `selectedDays={[start, end]}`
> 
> For now the calendar is maint to select only one day. To support multiple day selection, you should maybe manage the array of selected dates on your own state (could be done by wrapping `Calendar` in a Provider) and use those data to set the `PickerDay`'s `selected` prop correctly
> 
> To get more context about this customization, could you explain in which situation you need to be able to select multiple dates?

I am getting dates from Database and highlighting them on the calendar but I want to highlight the current date in a different style. Any Help?

const renderPickerDay = (date, selectedDates, pickersDayProps) => {
        if (!value) {
          return <PickersDay {...pickersDayProps} />;
        }
      const selected = findDate(value, date); 
  
      return (
        <>
        <CustomPickersDay
          {...pickersDayProps}
          disableMargin
          selected={selected}
        />
        </>
      );
    }
this function is working perfectly and highlights all desired dates but My need is to also highlight the current date differently.
my custom date picker in staticdatepicker renderInput.


const CustomPickersDay = styled(PickersDay, {
    shouldForwardProp: (prop) => prop !== "selected"
  })(({ theme, selected}) => ({
     
    ...(selected && {
      backgroundColor: "red",
      color: "white",
      "&:hover, &:focus": {
        backgroundColor: "#38A585",
      },
      borderTopLeftRadius: "50%",
      borderBottomLeftRadius: "50%",
      borderTopRightRadius: "50%",
      borderBottomRightRadius: "50%"
    }),
  }));

**Comment by LukasTy** [comment]
@noumanzahid047 Isn't `today` already styled differently than the `selected` day?
In any case, if you still need to override the style, have you tried using `&.MuiPickersDay-today` class?

**Comment by noumanzahid047** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/49652568/184361561-5032d0bf-191f-46a7-a835-66dc9eed5799.png)
I tried to override today's class but still got the same results.

**Comment by LukasTy** [comment]
Could you provide a reproduction codesandbox for easier understanding?
Maybe the `.selected` style overrides are placed lower than the `.today` and any styles rules in common do get applied from `selected` styles in this case?

**Comment by noumanzahid047** [comment]
**Maybe the .selected style overrides are placed lower than the .today and any styles rules in common do get applied from selected styles in this case**
That was the actual reason. Now I am getting desired results. thankyou Lukas for helping me out. It means a lot.
