### ISSUE TITLE
[TimePicker] Crash on clear

### ISSUE THREAD

**Issue by ScRalP** [mui/mui-x#5371]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi,
TimePicker component return an error as I manually clear the input.
_Error : Cannot read properties of null (reading 'getMinutes')_

### Expected behavior 🤔

After clearing the input the field should be blank

### Steps to reproduce 🕹

Steps:

1. Select the time field
2. Press backspace or delete
3. Get the error in your console

Example on sandbox : [TimePicker example](https://codesandbox.io/s/timepicker-clear-crash-nqhxgl?file=/src/App.tsx)

### Context 🔦

I was working with time picker with a locale "fr" when I tried to clear the value manually. The whole page became white and I had the error mentionned above in the browser console.
I first looked for a solution, and by removing the "fr" locale, the page would not turn white and crash but the error stays.

### Your environment 🌎

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD  
    npm: 7.20.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    **Chrome: Not Found (I used Chrome)**
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37)
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.87 
    @mui/core: ^5.0.0-alpha.54 => 5.0.0-alpha.54 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.87 => 5.0.0-alpha.88 
    @mui/material: ^5.8.5 => 5.8.6 
    @mui/private-theming:  5.8.6 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.6 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.6 
    @mui/x-date-pickers:  5.0.0-alpha.1 
    @types/react: ^18.0.14 => 18.0.14 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.7.4 => 4.7.4

**Comment by alexfauquette** [comment]
You are using an old version. The bug can not be reproduced with the last version of `@mui/x-date-pickers` (v5.0.0-alpha.7)
https://codesandbox.io/s/timepicker-clear-crash-forked-xowqf4?file=/src/App.tsx
