### ISSUE TITLE
[data grid] How to set `minWidth` on the grouping column of tree data

### ISSUE THREAD

**Issue by konstantinos-kafkas-cko** [mui/mui-x#5379]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have noticed there isn’t a way to specify the minWidth of the group/path column of the DataGridPro TreeTable. For the user specified columns you can define the minWidth, Field etc but it’s not possible for the group column that is generated based on the path. Is this something we missed to add? How can I override the existing  behaviour of that column 

### Expected behavior 🤔

We should have had the option to override that column by specifying different title and props. Couldn’t find anything in the docs please assist 

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
You can pass custom properties to your grouping column as [described here](https://mui.com/x/react-data-grid/tree-data/#custom-grouping-column)

Here is [an example](https://codesandbox.io/s/treedatacustomgroupingcolumn-demo-mui-x-forked-9pjqus?file=/demo.js) with the `minWidth` property
