### ISSUE TITLE
[data Grid] Thousand Separator for Numbers while in edit mode

### ISSUE THREAD

**Issue by capsloq** [mui/mui-x#5381]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Numbers do get formatted **after** an edit was made.
However it would be more convenient to get a thousand separator while typing in numbers in edit mode
![image](https://user-images.githubusercontent.com/73945900/177059854-791bd29e-0a25-4a42-a513-5ff8ba198fd2.png)

### Examples 🌈

![image](https://user-images.githubusercontent.com/73945900/177059855-ce85641a-2878-4de4-9e2a-d1e10d478126.png)

### Motivation 🔦

Typing in a Number: 100000. Is it 100.000 or 1.000.000 ? Inline formatting would show the user right away

**Comment by cherniavskii** [comment]
Hey @capsloq 
You can achieve that by using a third-party library to format an input: https://mui.com/material-ui/react-text-field/#integration-with-3rd-party-input-libraries
Then you can use this input component as a custom edit component: https://mui.com/x/react-data-grid/editing/#create-your-own-edit-component

As for supporting thousand separator out of the box in the Data Grid - there are few issues related:
- thousand separator differs depending on the country https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping
- we should rather avoid bundling formatting library by default

**Comment by capsloq** [comment]
Gosh, i thought i read the entire documentation but i must have missed the #create-your-own-edit-component part entirely. This of course provides all the functionality needed. Thank you @cherniavskii

**Comment by Qadir134** [comment]
> Gosh, i thought i read the entire documentation but i must have missed the #create-your-own-edit-component part entirely. This of course provides all the functionality needed. Thank you @cherniavskii

can you provide the source code

**Comment by Qadir134** [comment]
@cherniavskii  @capsloq  i am able to type the value but it does not shows on the DataGrid,the default value is not changed

 Updated Value:
![image](https://github.com/mui/mui-x/assets/121789134/5b7f4d2c-3f74-49b8-ad86-59b0ba916ca8)

Default Value:
![image](https://github.com/mui/mui-x/assets/121789134/21dd5aca-00ce-475d-976f-5c6eb668497e)

**Comment by qadir1020** [comment]
> @cherniavskii @capsloq i am able to type the value but it does not show the changed value when i hit enter on the DataGrid cell,the default value is not changing
> 
> Updated Value: ![image](https://private-user-images.githubusercontent.com/121789134/276934979-c083266e-44c6-4e7e-9c72-38f2ed403dc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDkxMTUsIm5iZiI6MTcwMTUwODgxNSwicGF0aCI6Ii8xMjE3ODkxMzQvMjc2OTM0OTc5LWMwODMyNjZlLTQ0YzYtNGU3ZS05YzcyLTM4ZjJlZDQwM2RjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQwOTIwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDg2NmRhNWY3ZDMzMTU1YjViZWIzOGJjNjdhODUwMTQ1MDIzNjYwOWFhZGYyNjAwMWQwY2ZiYmJiMzU0MGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GiGPr_8Mh_SfmovgKXhNuvnErPKIz59MNZy09CxasnE)
> 
> Default Value: ![image](https://private-user-images.githubusercontent.com/121789134/276934807-595cae36-f2c0-4e0f-9794-3d51e193a3f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDkxMTUsIm5iZiI6MTcwMTUwODgxNSwicGF0aCI6Ii8xMjE3ODkxMzQvMjc2OTM0ODA3LTU5NWNhZTM2LWYyYzAtNGUwZi05Nzk0LTNkNTFlMTkzYTNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQwOTIwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhmN2EwM2U1ODBkOWZiZTBhNjYxNDA2MTBmMjJlNmFiM2YxOWQ3NGZhNzQyYmRlYzY5YzgxZmE3YzI2NWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1hSacrsgVUHSZlQH8NYN6ve7hcAbPdHqOvfwmmQAjXY)
> 
> i am using the same approach discussed above

has anyone find out the solution?

**Comment by cherniavskii** [comment]
@qadir1020 Did you try following the steps in https://github.com/mui/mui-x/issues/5381#issuecomment-1173601642?

**Comment by qadir1020** [comment]
Yes,but the defualt value is not changing

**Comment by cherniavskii** [comment]
@qadir1020 Can you open an issue with a minimal reproduction example so we can investigate?
Thanks!

**Comment by qadir1020** [comment]
sure
