### ISSUE TITLE
[pickers] Allow props spreading to dialog action buttons

### ISSUE THREAD

**Issue by gabrielmmontenegro** [mui/mui-x#5385]
Hey maintainers,

Thank you so much for all your efforts in the DatePicker project. You guys are doing an amazing job!

I just discovered some limitations regarding action buttons. Their props are currently hard-coded. Although there are ways to change some styling properties by overriding material-ui theming, its a very limited solution. 

Currently it does not allow developers to change important buttons properties such as "color" (primary, secondary, default), "variant" (outlined, contained, etc) or even "classes" (to override the styles directly on the DatePicker's action buttons). Also, there is no way to change properties individually for each action button.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Current [PickersModalDialog.tsx](https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/_shared/PickersModalDialog.tsx) code:

```js 
<DialogActions
  className={clsx(classes.dialogAction, {
    [classes.withAdditionalAction]: clearable || showTodayButton,
  })}
>
  {clearable && (
    <Button data-mui-test="clear-action-button" color="primary" onClick={onClear}>
      {clearText}
    </Button>
  )}
  {showTodayButton && (
    <Button data-mui-test="today-action-button" color="primary" onClick={onSetToday}>
      {todayText}
    </Button>
  )}
  {cancelText && (
    <Button color="primary" onClick={onDismiss}>
      {cancelText}
    </Button>
  )}
  {okText && (
    <Button color="primary" onClick={onAccept}>
      {okText}
    </Button>
  )}
</DialogActions>
```

## Examples 🌈

A simple solution is by adding new props to KeyboardDatePicker to spread them on each respective action button.

```js
<KeyboardDatePicker
  ActionButtonOkProps={}
  ActionButtonCancelProps={}
  ActionButtonClearProps={}
  ActionButtonSetTodayProps={}
/r>
```

```js 
<DialogActions
  className={clsx(classes.dialogAction, {
    [classes.withAdditionalAction]: clearable || showTodayButton,
  })}
>
  {clearable && (
    <Button data-mui-test="clear-action-button" color="primary" {...ActionButtonClearProps} onClick={onClear}>
      {clearText}
    </Button>
  )}
  {showTodayButton && (
    <Button data-mui-test="today-action-button" color="primary" {...ActionButtonSetTodayProps}  onClick={onSetToday}>
      {todayText}
    </Button>
  )}
  {cancelText && (
    <Button color="primary" {...ActionButtonCancelProps} onClick={onDismiss}>
      {cancelText}
    </Button>
  )}
  {okText && (
    <Button color="primary" {...ActionButtonOkProps} onClick={onAccept}>
      {okText}
    </Button>
  )}
</DialogActions>
```

## Motivation 🔦

Our project's UX/UI team defined outlined buttons for dialogs, having cancel buttons the default color (gray) and confirmation button the primary (red) or secondary (blue) colors. There is no way to implement this as it is.

**Comment by Gonzalogauze** [comment]
@oliviertassinari https://for-loop652.github.io/XF26O9P0pom9PeA58LwdlxzzgIlvtusDoO3yovxmPAVi5XpSil4wTywhMVpX67a7x9DDRw/
