### ISSUE TITLE
[MobileDatePicker] Cancel button does not restore original value

### ISSUE THREAD

**Issue by robcaldecott** [mui/mui-x#5386]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using mobile variants of the date/time pickers an OK and Cancel button is displayed in the popup. However, due to the new pickers being fully controlled (with the app supplying the `value` and `onChange` handler) I cannot see how the Cancel button is meant to work. Once you pick a date/time the `onChange` function is called and you need to update the local state accordingly.

This means that clicking Cancel has no effect: the date stays to the last value selected in the picker.

Digging into the new API I see no obvious way to revert the controlled value back. There is an `onApply` function available that is only called when the OK button is clicked but no corresponding `onCancel` function. There is an `onClose` but this is called regardless of how the dialog was dismissed with no reason code supplied. The source also mentions `onDismiss` but it does not work when added as a prop. And I cannot see any other way to customise the props for the Cancel button that is enabled when using the mobile pickers: this would at least let me revert the state back.

## Expected Behavior 🤔

There should be a way to support the Cancel button, especially as the old v4 pickers worked like this by default. I am struggling to find an elegant way of doing this as there's no way to "know" Cancel was clicked.

## Steps to Reproduce 🕹

Here's a sandbox: https://codesandbox.io/s/red-bash-o5ncq?file=/src/App.js

1. Click on the first picker
2. Select a date
3. Hit Cancel
4. The date is not reverted

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Not Found
    Firefox: 92.0.1
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.50 
    @mui/icons-material: ^5.0.3 => 5.0.3 
    @mui/lab: ^5.0.0-alpha.50 => 5.0.0-alpha.50 
    @mui/material: ^5.0.3 => 5.0.3 
    @mui/private-theming:  5.0.1 
    @mui/styled-engine:  5.0.1 
    @mui/system:  5.0.3 
    @mui/types:  7.0.0 
    @mui/utils:  5.0.1 
    @types/react:  17.0.20 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.4.3 ```
</details>

**Comment by flaviendelangle** [comment]
Fixed by #4408

https://codesandbox.io/s/date-and-time-pickers-forked-uy0u47
