### ISSUE TITLE
Pressing ESC doesn't close DateTimePicker if it is in a Drawer

### ISSUE THREAD

**Issue by Krijovnick** [mui/mui-x#5389]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Pressing ESC key does not close the DateTimePicker

### Expected behavior 🤔

Pressing ESC key should close the DateTimePicker

### Steps to reproduce 🕹

https://codesandbox.io/s/temporarydrawer-demo-material-ui-forked-zsk1te?file=/demo.tsx:183-197
Steps:

1. Open the example
2. Open DateTimePicker
3. Press Escape key

**Comment by alexfauquette** [comment]
It is not reproducible with the last version:
https://codesandbox.io/s/temporarydrawer-demo-material-ui-forked-vljyjo?file=/demo.tsx

To upgrade to `@mui/x-date-pickers` you can follow the [migration guide](https://mui.com/x/react-date-pickers/migration-lab/)

**Comment by alexfauquette** [comment]
Don't hesitate to re-open the issue if you manage to reproduce the bug with the last version
