### ISSUE TITLE
[TimePicker] `onAccept` not called after entering valid time with keyboard input

### ISSUE THREAD

**Issue by oscar-b** [mui/mui-x#5391]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When entering a time value using keyboard input, `onChange` is called on each key stroke. However, once the time is correctly entered, `onAccept` is not called.

### Expected behavior 🤔

I expected `onAccept` to be called when a valid time was entered.

### Steps to reproduce 🕹

https://codesandbox.io/s/basicdatepicker-material-demo-forked-2dpm33?file=/demo.js

Steps:

1. Enter `1`, see that `onChange` is triggered
1. Enter `1`, see that `onChange` is triggered
1. Enter `2`, see that `onChange` is triggered
1. Enter `2`, see that `onChange` is triggered, however `onAccept` is not even though the time is now valid

### Context 🔦

I would like to be able to trigger auto-submit of the time, when a date is selected.

Using `onAccept`, this is possible when the user selects using the popup. However, this is not possible when they enter it manually using keyboard.

To solve this, I have to look at `onChange` instead, but this is triggered with a valid date, after selecting the hour, when using the popup, resulting in a double submit of the time in that case (first with an "invalid" time as the user only selected the hour).

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @oscar-b 
Wouldn't `onChange` + `newValue.isValid` check be enough for your use case?

Looking at the codebase, `onAccept` seems to be there to be called when user clicks "Accept" button in picker modal, or when selecting date with `closeOnSelect=true`. I don't think `onAccept` was meant to be called on keyboard input.

**Comment by oscar-b** [comment]
Hey @cherniavskii 

> Wouldn't onChange + newValue.isValid check be enough for your use case?

That's what I'm currently doing, but the issue is that when selecting the time using the popup, when you select the hour it also calls `onChange` with a valid `DateTime` (for instance `11:00` if selecting 11). And then you get a second `onChange` when selecting the minute.

The only idea I have otherwise is to make the `open` state controlled, so that I know when it is open and can ignore the `onChange` in that case, but that feels like a quite clunky workaround.

Another parameter to `onChange`, indicating where the change is coming from, would work fine as well and make sense perhaps?

**Comment by cherniavskii** [comment]
> the issue is that when selecting the time using the popup, when you select the hour it also calls onChange with a valid DateTime (for instance 11:00 if selecting 11). And then you get a second onChange when selecting the minute.

Right, I didn't notice this at first.

@alexfauquette @flaviendelangle any ideas?

**Comment by ahurlburt** [comment]
can this be reopened, it is not completed.

**Comment by alexfauquette** [comment]
This got closed more than a year ago. I assume the user found a solution to his problem. If it does not solve your, pleas open a new issue linkin to this one and explaining your issue
