### ISSUE TITLE
[CalendarPicker] Date resets to `minDate` if `minDate` is set programmatically 

### ISSUE THREAD

**Issue by saadhashmi** [mui/mui-x#5393]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Select a date lets say today's date in the datepicker. 
Set the minDate value to a date in the future e.g. 2018-02-01. 
The Datepicker goes into error state(with red border)
Open the datepicker to select another date, the date will reset to the minDate -1. 

### Expected behavior 🤔

The minDate should be independent of the datepicker initialValue. Basically i have  a case in which i have to trigger an error which states that initialDate is after than minDate which is not allowed, hence allowing user to select a correct date but here the initial value of date changes when i set a minDate that is coming from database for the check. And setting error flag from outside the date component is not triggering the Mui-Error because handleError is not getting triggered.

### Steps to reproduce 🕹

Steps:

1. Select a date lets say today's date in the datepicker. 
2. Set the minDate value to a date in the future e.g. 2018-02-01. 
3. The Datepicker goes into error state(with red border)
4. Open the datepicker to select another date, the date will reset to the minDate -1. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Here is a reproduction example of the reported bug
https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-s3k3sf?file=/demo.tsx

**Comment by flaviendelangle** [comment]
That is the "expected behavior

https://github.com/mui/mui-x/blob/22567ed5e99639f61ccaa543a913febd538daff8/packages/x-date-pickers/src/CalendarPicker/CalendarPicker.tsx#L339-L350

**Comment by flaviendelangle** [comment]
@alexfauquette What do you think about removing this behavior ?

I am working on #6064 and this behavior feels super weird.

**Comment by alexfauquette** [comment]
No problem for removing it 👍

I assume it was because selecting the day and setting the focus on the button was a unique action. If I'm right, now the focus will have similar behavior (go to closest available date)
