### ISSUE TITLE
[Datagrid] AutoHeight + pinned right column = column header misplaced

### ISSUE THREAD

**Issue by lauri865** [mui/mui-x#5398]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When Datagrid has props set to autoHeight={true} and has a right pinned column, the header of the pinned column is misplaced (has paddingRight="15px" style).

### Expected behavior 🤔

Since autoHeight Datagrid has no scrollbar, the pinned column should not have any padding.

### Steps to reproduce 🕹

Reproduction on CodeSandbox:
https://codesandbox.io/s/basiccolumnpinning-demo-mui-x-forked-wk6coy

**Comment by cherniavskii** [comment]
I can reproduce the issue on MacOS with "Show scroll bars" set to "Always":
<img width="489" alt="Screenshot 2022-07-05 at 13 21 46" src="https://user-images.githubusercontent.com/13808724/177317096-0cbd4fbf-2968-4755-9624-641978e96315.png">
<img width="567" alt="Screenshot 2022-07-05 at 13 21 53" src="https://user-images.githubusercontent.com/13808724/177317124-5cb86327-3bb1-4972-aa25-3cc3015f5ab2.png">

**Comment by flaviendelangle** [comment]
Probably introduced by #5201 and #5164 combined

**Comment by flaviendelangle** [comment]
```diff
--- a/packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
@@ -27,19 +27,22 @@ const hasScroll = ({
   content,
   container,
   scrollBarSize,
+  autoHeight,
 }: {
   content: ElementSize;
   container: ElementSize;
   scrollBarSize: number;
+  autoHeight: boolean;
 }) => {
   const hasScrollXIfNoYScrollBar = content.width > container.width;
-  const hasScrollYIfNoXScrollBar = content.height > container.height;
+  const hasScrollYIfNoXScrollBar = !autoHeight && content.height > container.height;
 
   let hasScrollX = false;
   let hasScrollY = false;
   if (hasScrollXIfNoYScrollBar || hasScrollYIfNoXScrollBar) {
     hasScrollX = hasScrollXIfNoYScrollBar;
-    hasScrollY = content.height + (hasScrollX ? scrollBarSize : 0) > container.height;
+    hasScrollY =
+      !autoHeight && content.height + (hasScrollX ? scrollBarSize : 0) > container.height;
 
     // We recalculate the scroll x to consider the size of the y scrollbar.
     if (hasScrollY) {
@@ -101,8 +104,13 @@ export function useGridDimensions(
       content: { width: Math.round(columnsTotalWidth), height: rowsMeta.currentPageTotalHeight },
       container: viewportOuterSize,
       scrollBarSize,
+      autoHeight: props.autoHeight,
     });
 
+    if (hasScrollX && props.autoHeight) {
+      viewportOuterSize.height += scrollBarSize;
+    }
+
```
