### ISSUE TITLE
[data grid] Uncaught Error when @mui/x-date-pickers used @date-io/date-fns

### ISSUE THREAD

**Issue by Medkhat** [mui/mui-x#5408]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Compiled with problems:

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js 1:0-39

Module not found: Error: Can't resolve 'date-fns/addDays' in '/Users/medkhat/Desktop/Projects/podcast-admin/node_modules/@date-io/date-fns/build'

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js 2:0-45

Module not found: Error: Can't resolve 'date-fns/addSeconds' in '/Users/medkhat/Desktop/Projects/podcast-admin/node_modules/@date-io/date-fns/build'

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js 3:0-45

Module not found: Error: Can't resolve 'date-fns/addMinutes' in '/Users/medkhat/Desktop/Projects/podcast-admin/node_modules/@date-io/date-fns/build'

...

![image](https://user-images.githubusercontent.com/42961493/177623193-ce96a56e-4342-469d-a744-ffeb8653a66a.png)

**Comment by cherniavskii** [comment]
Hey @Medkhat 
Looks like you forgot to install `date-fns` peer dependency

**Comment by Medkhat** [comment]
@cherniavskii  Hi, Thank you for your reply. But I have installed the latest version of date-fns dependency

**Comment by Medkhat** [comment]
Thank you! I have installed date-fns by @date-io. I deleted this package and reinstalled just date-fns package. Fixed:)

**Comment by rwieruch** [comment]
I mean you were right @Medkhat Documentation https://www.npmjs.com/package/@mui/x-date-pickers says installing it from the @date-io organization. Ran into the same problem.

**Comment by cherniavskii** [comment]
@flaviendelangle you're right.
Initially I thought that `@date-io` lib should be installed explicitly, but that's not the case since it's already a dependency, not peerDependency 👍

**Comment by cherniavskii** [comment]
Fixed by https://github.com/mui/mui-x/pull/5293 then
