### ISSUE TITLE
DataGrid getActions automatically executing onClick code

### ISSUE THREAD

**Issue by kbessemer** [mui/mui-x#5409]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On page render, the code inside onClick in getActions for every rendered element in the DataGrid is executing automatically without pressing the action button.

### Expected behavior 🤔

console.log(params.row.macid) should only execute when the GO button is pressed for each item in DataGrid

### Steps to reproduce 🕹

Steps:

1. Create a datagrid
2. Have one column be for actions
3. Set one action button's onClick to console.log("something")
4. Verify code is not automatically executing console log messages on page render

### Context 🔦

I am building a device list that fetches from a API, and have a device profile I am trying link my getActions to for each item in the DataGrid.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.114 (used)
    Edge: Not Found
    Firefox: 102.0
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.8.1 => 11.8.1 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.71 
    @mui/icons-material: ^5.5.0 => 5.5.0 
    @mui/lab: ^5.0.0-alpha.76 => 5.0.0-alpha.76 
    @mui/material: ^5.5.0 => 5.5.0 
    @mui/private-theming:  5.6.0 
    @mui/styled-engine:  5.6.0 
    @mui/system:  5.6.0 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.0 
    @mui/x-data-grid: ^5.6.1 => 5.6.1 
    @mui/x-date-pickers:  5.0.0-alpha.0 
    @types/react:  17.0.39 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.5 => 5.3.5 
    typescript:  4.6.2 

```
</details>

**Comment by cherniavskii** [comment]
Hey @kbessemer 
Can you provide a minimal example reproducing the issue? You can start with this demo https://codesandbox.io/s/dmos3e

**Comment by kbessemer** [comment]
`import * as React from 'react';
import SERVERIP from '../constants';
import MyAppBar from './AppBar';
import StatsWidget from './widgets/StatsWidget';
import Devices from './widgets/DevicesList';
import OnlineDevices from './widgets/OnlineDevices';
import TopUsage from './widgets/TopUsage';
import RecentUpdates from './widgets/RecentUpdates';
import MyFooter from './widgets/Footer';
import AlertSnackbar from './alerts/AlertSnackbar';
import OpenTicketsAPI from './api/OpenTickets';
import StatisticsAPI from './api/Statistics';
import ReactLoading from 'react-loading';
import VerifySessionAPI from './api/Verify';
import { useNavigate } from "react-router-dom";

export default function StatsScreen(props) {
  const [errorMsg, setErrorMsg] = React.useState({Status: false, Msg: ""});
  const [openTickets, setOpenTickets] = React.useState(0);
  const [statsData, setStatsData] = React.useState([]);
  const [isLoading2, setIsLoading2] = React.useState(true);
  let navigate = useNavigate();

  // Do this on screen load
  React.useEffect(() => {
    HandleOpenTickets();
    HandleStatistics();
    HandleVerifySession();
  }, [])

  async function HandleOpenTickets() {
    var call = await OpenTicketsAPI();
    if (call.Success) {
      setOpenTickets(call.Data);
    } else {
      setErrorMsg({Status: true, type: "error", Msg: call.Errors})
    }
  }

  async function HandleVerifySession() {
    var call = await VerifySessionAPI();
    if (call.Success) {
    
    } else {
      navigate("../invalid", { replace: true });
    }
  }

  async function HandleStatistics() {
    var call = await StatisticsAPI();
    setStatsData(call);
    setIsLoading2(false);
  }

  return (
    <div className="App">
      <MyAppBar openTickets={openTickets} errorMsg={setErrorMsg} setTheme={props.setTheme} theme={props.theme}/>
      <AlertSnackbar status={errorMsg.Status} setStatus={setErrorMsg} message={errorMsg.Msg} severity={errorMsg.type}/> 
      <header className="App-header">
        <div className="Main">
          {isLoading2
              ? <ReactLoading type='spinningBubbles' className='loading-circle' color='#358d1c9e' height={100} width={100} />
              : <div className="Content-Row"><StatsWidget theme={props.theme} statsData={statsData} screenWidth={props.screenWidth} errorMsg={setErrorMsg}/></div>
          }  
          <Devices screenWidth={props.screenWidth}/>
          <div className="Content-Row">
            <OnlineDevices theme={props.theme} screenWidth={props.screenWidth}/>
            <TopUsage screenWidth={props.screenWidth}/>
            {props.screenWidth === "big" ? <RecentUpdates/> : null}
          </div>
          <div className="Content-Row">
            <MyFooter />
          </div>
        </div>
      </header>
    </div>
  );
}`

`import * as React from 'react';
import { DataGrid, GridActionsCellItem } from '@mui/x-data-grid';
import { useNavigate } from "react-router-dom";

export default function DeviceList(props) {
  let navigate = useNavigate();

  const columns = [
    { field: 'macid', headerName: 'MACID', width: 250 },
    { field: 'cpu', headerName: 'CPU (%)', width: 150 },
    { field: 'ram', headerName: 'RAM (%)', width: 150 },
    { field: 'disk', headerName: 'Disk (%)', width: 150 },
    { field: 'temperature', headerName: 'Temperature (° C)', width: 250 },
    { field: 'actions', width: 150, type: 'actions',
        getActions: (params) => [
          <GridActionsCellItem onClick={console.log(params.row.macid)} label="GO" showInMenu/>,
        ]
    },
  ];

  const rows = [];

  var cpu = 0;
  var ram = 0;
  var disk = 0;
  var temp = 0;

  function createData(id, macid, cpu, ram, disk, temperature) {
    return {
      id,
      macid,
      cpu,
      ram,
      disk,
      temperature,
    };
  }

  var counter = 1;

  for (var x in props.statsData) {
        if (props.statsData[x].cpu_us === null) {
            cpu = 0;
        } else {
            cpu = parseInt(props.statsData[x].cpu_us);
        }
        if (props.statsData[x].ramused === null) {
            ram = 0;
        } else {
            ram = parseInt(props.statsData[x].ramused);
        }
        if (props.statsData[x].disk1used === null) {
            disk = 0;
        } else {
            disk = parseInt(props.statsData[x].disk1used);
        }
        if (props.statsData[x].temperature === null) {
            temp = 0;
        } else {
            temp = parseInt(props.statsData[x].temprature);
        }
      rows.push(createData(counter, props.statsData[x].deviceID, cpu, ram, disk, temp))
      counter += 1;
  }

  function HandleDeviceClick(macid) {
    localStorage.setItem('macid', macid);
    navigate("../search", { replace: true });
  }

  return (
    <div style={{ height: 800, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        pageSize={25}
        rowsPerPageOptions={[25]}
      />
    </div>
  );
}`

**Comment by kbessemer** [comment]
The problem was I needed my onClick like this: onClick={() => HandleDeviceClick(params.row.macid)}

Instead of: onClick={HandleDe...}
