### ISSUE TITLE
[data grid] Freezing the rows in dev mode does not work well with MobX

### ISSUE THREAD

**Issue by jpmtrabbold** [mui/mui-x#5411]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I pass an array of rows to the DataGridPro component it gets frozen, which is a problem when working with observability libraries (MobX).

### Expected behavior 🤔

I understand the reasoning around using `Object.freeze` - but there should be a way of opting out of that. A simple `dontFreezeRows` would suffice.

### Steps to reproduce 🕹

Steps:

1. Run the following sandbox: https://codesandbox.io/s/data-grid-pro-forked-nr3d9y?file=/src/App.tsx

### Context 🔦

The message given on the error is `[MobX] Observable arrays cannot be frozen. If you're passing observables to 3rd party component/function that calls Object.freeze, pass copy instead: toJS(observable)`, so an obvious "solution" would be just to use `toJS` - and it works. The problem is that, with massive amounts of data, calling toJS on every render becomes an unwelcome overhead.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Used Chrome.

System:
    OS: macOS 12.0.1
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v14.18.0/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: 91.0.2
    Safari: 15.1
  npmPackages:
    typescript: ^4.4.4 => 4.6.2 
```
</details>

**Comment by flaviendelangle** [comment]
Hi, thanks for your feedback.

I am not very familiar with MobX.
Is there no problem passing an observable arrays to our component ? The behavior is 100% like passing a real array ?

To be honest this `freeze` only occur in dev mode and is only here to prevent users from doing mistakes in there code.
I'm not even sure we should have it in the first place.

**Comment by jpmtrabbold** [comment]
@flaviendelangle thanks for such a prompt response!

Yes, observable arrays have the same api as a normal array, I’ve been using them for 4 years now with a number of different components that accept arrays as props and it has always worked as expected.

It would be much appreciated if the freezing behavior were removed from the production release. This is the only thing that is preventing us from actually buying the pro version at the moment.

thanks!!

**Comment by flaviendelangle** [comment]
@cherniavskii @m4theushw what are your thoughts on this ?

**Comment by cherniavskii** [comment]
+1 for removing `Object.freeze` completely

**Comment by jpmtrabbold** [comment]
safe to say that this change should be applied to all three offers? (free, pro and premium)

**Comment by oliviertassinari** [comment]
For context, we have `Object.freeze` since #1661, it was introduced to help developers make mistakes like #1491 and #1553.

**Comment by jpmtrabbold** [comment]
@oliviertassinari you have a point there - it helps to prevent unnecessary tickets. So, maybe a simple `doNotFreezeRows` prop to opt-out from it?

**Comment by jpmtrabbold** [comment]
@DanailH thanks for your response. 

It is possible, and that's what I was doing to test it. There are some problems though:
- every time the component renders we would unnecessarily be creating a new array;
- sure, we can memo it, but that would put us off of using the data-grid as it is not a good devx
- yes I'm aware of the limitations you mentioned. In those scenarios, we'd either change the array reference (as needed - not on every render), or we'd put observers inside the cells that we want to be reactive - which is something we lose by having to convert the object to a non-observable.

Not trying to force you guys' hand to do what we want, by any means! Just being straightforward in saying that having to convert the array to a non-observable every time would be a bit of an unnecessary hassle that would potentially put us off from using it, especially because we know the implications of what we are doing. Hence the suggestion of having a prop to `opt-out` from that behavior. 

thank you!

**Comment by DanailH** [comment]
I'm starting to think that maybe we can have an option to disable the freezing but as I explained before it might be a double edge sword.
If we are to allow for devs to disable rows freezing how would the api look? will a simple prop do the trick? What do you think @m4theushw?

**Comment by cherniavskii** [comment]
> yes I'm aware of the limitations you mentioned. In those scenarios, we'd either change the array reference (as needed - not on every render),

@jpmtrabbold If you know when you need a new array reference, what's stopping you from calling `toJS` when needed and storing the reference in the state? That would work with `Object.freeze`

**Comment by jpmtrabbold** [comment]
> At the root, the problem is that we are trying to freeze the rows to improve the DX but the rows provided by some developers don't support freezing. It sounds like the solution is it to give up on trying to freeze when it's not supported. Was this path explored?


great solution with no overhead

**Comment by jpmtrabbold** [comment]
@flaviendelangle do you think you would incorporate Olivier's suggestion into your PR? Don't want to hurry you guys, but at this point our company is keen on going premium, while still depending on the outcome of this ticket
