### ISSUE TITLE
[data grid] Formating column data scape html

### ISSUE THREAD

**Issue by wahajStar** [mui/mui-x#5412]
### Order ID 💳

#32742

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello, I have a use case where service is sending the html formate in row data. Is it possible to escape html and render what ever we are getting..
I create a small scenaio [example](https://codesandbox.io/s/datagridprodemo-demo-mui-x-forked-noybjg?file=/demo.tsx)

I go through the doc. 
"If an unsupported column type is used, the string column type will be used instead."
please let me know if its possible to achive this 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

You can use the `renderCell` to call the `dangerouslySetInnerHTML` of React.
Or create a custom column type to avoid adding this `div` to the DOM but not sure it's worth the complxity.

https://codesandbox.io/s/datagridprodemo-demo-mui-x-forked-i8qphy?file=/demo.tsx

**Comment by wahajStar** [comment]
Thanks @flaviendelangle its work fine.
