### ISSUE TITLE
[DataGrid] horizontal scrolling doesn't work over column headers

### ISSUE THREAD

**Issue by MatejBransky** [mui/mui-x#5416]
### Current behavior 😯

You can't use horizontal scrolling over column headers via Shift key + scroll wheel or directly with the Mac's trackpad.

[screen recording](https://youtu.be/te9dox2cpHs)

### Expected behavior 🤔

You can use horizontal scrolling over column headers.

![image](https://user-images.githubusercontent.com/20944757/181486282-be3e1600-42c7-4e64-a758-38db25395848.png)

### Steps to reproduce 🕹

Steps:

1. navigate with your mouse over column headers
2. try horizontal scrolling

### Context 🔦

We have a use case where we want to create a table with columns first and then the data. In this case, we cannot scroll to the part of the table that does not fit into the page.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Used Chrome.

@mui/envinfo doesn't work so here is manually gathered info:

System:
  OS: Windows 10 Pro 21H2 (19044.1415) / Mac OS Monterey (tested both of them)
  Binaries:
    Node: 16.3.0
    Yarn: 1.22.18
    npm: 7.8.0
  Browsers:
    Chrome: 103.0.5060.114
```
</details>

### Order ID 💳 (optional)

48059

**Comment by cherniavskii** [comment]
Hey @MatejBransky 
Can you provide a minimal example reproducing the issue? You can start with this demo: https://codesandbox.io/s/columnvirtualizationgrid-demo-mui-x-forked-94c90e

**Comment by MatejBransky** [comment]
@cherniavskii 
You can reproduce it on almost every horizontally scrollable table so what I can do is just to record the current behavior: https://youtu.be/te9dox2cpHs

Is that enough?

**Comment by cherniavskii** [comment]
@MatejBransky Yes, scrollable rows area doesn't include column headers. So you cannot scroll when hovering over column headers. But you can scroll when hovering over the rows container - even when there's no rows. See https://codesandbox.io/s/columnvirtualizationgrid-demo-mui-x-forked-v2robz

**Comment by cherniavskii** [comment]
Is there a case where you end up in a situation where you can not scroll horizontally, even thought there's more columns that grid could fit?

**Comment by MatejBransky** [comment]
> Yes, scrollable rows area doesn't include column headers. So you cannot scroll when hovering over column headers. But you can scroll when hovering over the rows container - even when there's no rows.

Like yes you can, thanks for the advice, but it still doesn't make sense that you can't scroll the column headers. 

We are trying to create a customizable datagrid and this "feature" is missing for our users, so we would like to fix it, unfortunately this is not a problem on our side, but more on the MUI DataGrid side. 

I would be glad if it could be fixed/added this..quite expected behavior. Is there any reason why it doesn't work right now?

**Comment by cherniavskii** [comment]
> Is there any reason why it doesn't work right now?

The main reason is the way our virtualization works.

I'm adding "waiting for upvotes" label to see if there's a demand for this feature in community.

I was able to achieve the behavior you mentioned by applying these changes in our codebase (although a bit hacky):

```diff
diff --git a/packages/grid/x-data-grid/src/components/DataGridColumnHeaders.tsx b/packages/grid/x-data-grid/src/components/DataGridColumnHeaders.tsx
index 5ceac2efb..4724f40fe 100644
--- a/packages/grid/x-data-grid/src/components/DataGridColumnHeaders.tsx
+++ b/packages/grid/x-data-grid/src/components/DataGridColumnHeaders.tsx
@@ -16,6 +16,27 @@ export const DataGridColumnHeaders = React.forwardRef<HTMLDivElement, DataGridCo
       innerRef,
     });
 
+    const rootElement = ref?.current;
+
+    React.useEffect(() => {
+      if (!rootElement) {
+        return undefined;
+      }
+      const callback = (event: WheelEvent) => {
+        if (event.deltaX !== 0) {
+          event.preventDefault();
+          const virtualScroller = rootElement.parentElement.querySelector(
+            '.MuiDataGrid-virtualScroller',
+          );
+          virtualScroller.scrollLeft += event.deltaX;
+        }
+      };
+      rootElement.addEventListener('mousewheel', callback);
+      return () => {
+        rootElement.removeEventListener('mousewheel', callback);
+      };
+    }, [rootElement]);
+
     return (
       <GridColumnHeaders ref={ref} {...getRootProps(other)}>
         <GridScrollArea scrollDirection="left" />
```

**Comment by MatejBransky** [comment]
Thank you for your time spent on it. 🙏 Let's wait for upvotes then.

**Comment by MatejBransky** [comment]
I've added "order ID" so it get a little bit more attention.

**Comment by patrik-meixner** [comment]
Any update on this? It's been a while now without any real activity on this topic. Is 5 upvotes enough or are we waiting to get more?...

**Comment by cherniavskii** [comment]
Two things we can do to solve the pain points of this issue:
1. When scrolling on the columns header, call preventDefault to prevent triggering page change (this happens on MacOS for example)
2. Explore possibilities to forward `scroll` or `mousewheel` events from the columns header to the virtual scroller. Also, worth checking https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-x

**Comment by Triton-Halley** [comment]
I don't know how this datagrid component scroll work correctly on mui website , but not in our case 
https://mui.com/x/react-data-grid/#mit-version

**Comment by Triton-Halley** [comment]
the solution that I found you can just add these css into a css file and import the css file inside that component you use datagrid 

`.muirtl-204u17-MuiDataGrid-main {
  overflow: scroll !important;
}
.muirtl-f3jnds-MuiDataGrid-columnHeaders {
  overflow: unset !important;
}
`
after that your horizontally scroll work for both of it header and row

**Comment by Triton-Halley** [comment]
I fixed this problem on react developer mode but when I build the application all of my changes gone

**Comment by patrik-meixner** [comment]
Bump

**Comment by noanflaherty** [comment]
I too would love this feature and fear I may not be able to use datagrid without support for this or some workaround (despite having paid for the pro version of it).

**Comment by cherniavskii** [comment]
Hi there!
We have reworked the column headers and improved the horizontal scrolling experience in v7, which is [currently in beta](https://github.com/mui/mui-x/releases)! 🎉
You can try out the new Data Grid in the v7 beta docs: https://next.mui.com/x/react-data-grid/

Upgrading from Data Grid v6? Follow our [migration guide](https://next.mui.com/x/migration/migration-data-grid-v6/).
New to the Data Grid? Follow our [installation guide](https://next.mui.com/x/react-data-grid/getting-started/#installation).
Let us know what you think!
