### ISSUE TITLE
[DateTimePicker] Ignored formatting after removing characters

### ISSUE THREAD

**Issue by tobymoore164** [mui/mui-x#5424]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When backspacing inside the Date Time Picker it ignonres some characters, in addition any characters you enteter will now ignore validation.

### Expected behavior 🤔

You should be able to remove and add characters in the Date Time Picker with input validation and no skipping of characters or spaces.

### Steps to reproduce 🕹

Steps: This can actually be reproduced in the docs online: https://mui.com/x/react-date-pickers/date-time-picker/ 

1. Locate the Basic Usage section.
2. Click on the Date Time Picker.
3. Press backspace to remove some characters (you'll see the error reproducing).
4. Try and add some characters to the field, you can add letters and numbers.

### Context 🔦

This component should work correctly, but it currently doesn't.

I've found a similar thread, but it was closed with no resolution. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
@alexfauquette I think it's related to some work you did recently

**Comment by alexfauquette** [comment]
> Press backspace to remove some characters (you'll see the error reproducing).

I can reproduce this problem whicc seems to only occur with am/pm. I struggle to find why the cursor moves like this. The only cursor manager I found in the codebase is `rifm` so we should try to make small reproduction example to get why removing the last character move the cursor 3 step before it instead of one.

> you can add letters and numbers

I can only add letters `a` and `p` which are here for allowing the am/pm

**Comment by tobymoore164** [comment]
> Could you share the link, I would be interested to see what was the discussion?
Sure, here's the link: https://github.com/mui/material-ui/issues/29190

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.
