### ISSUE TITLE
Compress GridFilterToolbar into single button

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#5426]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently, the GridFilterToolbar button is scattered into one line. Is there a way to compress it to a button? Then after clicking the button, a menu of the GridFilterToolbar will apprear.

### Expected behavior 🤔

Currently, the GridFilterToolbar button is scattered into one line. Is there a way to compress it to a button? Then after clicking the button, a menu of the GridFilterToolbar will apprear.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

Currently, the GridFilterToolbar button is scattered into one line. Is there a way to compress it to a button? Then after clicking the button, a menu of the GridFilterToolbar will apprear.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

33625

**Comment by cherniavskii** [comment]
Hey @simbahandiane 
You can import separate toolbar buttons: https://codesandbox.io/s/6pqi09
Then you can replace `GridToolbarContainer` with a menu or something else.

You can also create custom toolbar implementation using toolbar slot:
```tsx
<DataGrid
  components={{
    Toolbar: CustomToolbar
  }}
```
