### ISSUE TITLE
[data grid] valueSetter assumes row is returned, but no field context is provided

### ISSUE THREAD

**Issue by mainfraame** [mui/mui-x#5430]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

There is a bug in the columnDef value setters where it assumes you are returning the entire row, but provides you no context of what field you're updating.  It's possible to get this using Object.keys() + find to determine the field name, but this is detrimental to performance.  

`userGridRowEditing.new.js:555`:

```    
Object.entries(editingState[id]).forEach(([field, fieldProps]) => {
      const column = apiRef.current.getColumn(field);

      if (column.valueSetter) {
        rowUpdate = column.valueSetter({        // <-----------------------------------
          value: fieldProps.value,
          row: rowUpdate
        });
      } else {
        rowUpdate[field] = fieldProps.value;
      }
    });
```

### Expected behavior 🤔

add the available field property to the valueSetter OR make change `rowUpdate` to `rowUpdate[field]`

**_Option 1:_**
```    
Object.entries(editingState[id]).forEach(([field, fieldProps]) => {
      const column = apiRef.current.getColumn(field);

      if (column.valueSetter) {
        rowUpdate = column.valueSetter({
          value: fieldProps.value,
          row: rowUpdate,
          field
        });
      } else {
        rowUpdate[field] = fieldProps.value;
      }
    });
```

**_Option 2:_**
```    
Object.entries(editingState[id]).forEach(([field, fieldProps]) => {
      const column = apiRef.current.getColumn(field);

      if (column.valueSetter) {
        rowUpdate[field] = column.valueSetter({
          value: fieldProps.value,
          row: rowUpdate
        });
      } else {
        rowUpdate[field] = fieldProps.value;
      }
    });
```

### Steps to reproduce 🕹

Steps:

1. set up a basic editor grid
2. add column definitions
3. apply a valueSetter to any column def
4. try and return a formatted value

### Context 🔦

I'm unable to use valueFormatter on a date editor column to coerce the string value into a date object

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
I'm closing since we've not received feedback.
