### ISSUE TITLE
[data grid] Column Headers lag on horizontal scroll

### ISSUE THREAD

**Issue by colespencer1453** [mui/mui-x#5433]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Column headers lag column cells when using horizontal scroll. This can be observed in a grid I'm developing locally as well as on the main MUI demo: https://mui.com/x/react-data-grid/demo/. This is not a smooth user experience and is visually unsettling.

Uploading Screen Recording 2022-07-08 at 3.47.14 PM.mov…

### Expected behavior 🤔

I would expect column headers to be fixed during scroll with the cells beneath them. Almost every data grid component I use the column headers scroll in sync with the column's cells. Wanted to check in whether this was 

### Steps to reproduce 🕹

Steps:

1. Go to MUI demo and drag horizontal scroll quickly left and right

### Context 🔦

I am currently using MUI's data grid component to build an enterprise application. Clean user experiences are key. This issue is not a deal breaker for me, but I do think that this could be improved and would love to know what constraints are causing the performance lag here. 

### Your environment 🌎

My local machine is a macbook pro and I'm using google chrome.

**Comment by m4theushw** [comment]
The recording was not uploaded correctly. Could you verify?

Anyway, are you talking about the same bug in the video in https://github.com/mui/mui-x/pull/2673#issue-1004950963 (scroll to "Trade-off")?.
