### ISSUE TITLE
[data grid] Warnings with the Validation Demo in the docs

### ISSUE THREAD

**Issue by TurtIeSocks** [mui/mui-x#5457]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Implementing [this example](https://mui.com/x/react-data-grid/editing/#validation) produces a couple of React errors.

> Warning: Failed prop type: Invalid prop `children` supplied to `ForwardRef(Tooltip2)`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead? For more information see https://mui.com/r/caveat-with-refs-guide

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `ForwardRef(Tooltip2)`.
    at GridEditInputCell 

> MUI: The `children` component of the Tooltip is not forwarding its props correctly.
Please make sure that props are spread on the same element that the ref is applied to. 
    at Tooltip2

Things I've tried:
- I initially got this error when replacing the `DataGridPro` components with the standard `DataGrid` component but later confirmed that I still received the error with `DataGridPro` as well
- Read through the `caveat-with-refs-guide` link provided in the error log but as far as I can tell, this should be valid? 
- My own implementation that simplifies the check a bit with local variables / doesn't use a promise
- Using a stock Tooltip component instead of a styled
- Wrapping the component in Fragments, this removed the error but resulted in the Tooltip not showing at all
- I used a stock MUI `Input` component instead of the `GridEditInputCell` component, no error was produced but not ideal

### Expected behavior 🤔

No React errors produced.

### Steps to reproduce 🕹

Steps:
1. Run the [example code](https://mui.com/x/react-data-grid/editing/#validation) from the docs with non-production React
2. Double click a cell to edit it
3. See errors in browser console

### Context 🔦

I'm trying to setup a validation system, if there's a better way to do this than the examples in the documentation then I'm open to alternatives!

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Using Chrome for this specific example
  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.23.0-20220130.1630 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: 91.7.1
    Safari: 15.3
  npmPackages:
    @emotion/react:  11.9.0 
    @emotion/styled:  11.8.1 
    @mui/base:  5.0.0-alpha.82 
    @mui/icons-material:  5.8.4 
    @mui/material:  5.8.1 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.1 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.13.0 
    @mui/x-data-grid-pro:  5.13.0 
    @mui/x-license-pro:  5.12.3 
    @types/react:  17.0.45 
    react:  17.0.2 
    react-dom:  17.0.2 
    typescript: ^4.4.3 => 4.6.4 ```
</details>


### Order ID 💳 (optional)

_No response_

**Comment by m4theushw** [comment]
Thanks for warning us. Unfortunately one of the errors we can't fix in our side, it's part of Tooltip's behavior. I opened https://github.com/mui/material-ui/issues/33476 to see what can be done about it. The other error can be fixed by passing `ref` to the root element, as below:

```diff
diff --git a/packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx b/packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx
index 2e63156ca..cb60f7e8e 100644
--- a/packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx
+++ b/packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx
@@ -39,7 +39,7 @@ const GridEditInputCellRoot = styled(InputBase, {
 
 export interface GridEditInputCellProps
   extends GridRenderEditCellParams,
-    Omit<InputBaseProps, 'id' | 'value' | 'tabIndex'> {
+    Omit<InputBaseProps, 'id' | 'value' | 'tabIndex' | 'ref'> {
   debounceMs?: number;
   /**
    * Callback called when the value is changed by the user.
@@ -53,7 +53,10 @@ export interface GridEditInputCellProps
   ) => Promise<void> | void;
 }
 
-function GridEditInputCell(props: GridEditInputCellProps) {
+const GridEditInputCell = React.forwardRef<
+  React.HTMLAttributes<HTMLDivElement>,
+  GridEditInputCellProps
+>(function GridEditInputCell(props, ref) {
   const rootProps = useGridRootProps();
 
   const {
@@ -109,6 +112,7 @@ function GridEditInputCell(props: GridEditInputCellProps) {
 
   return (
     <GridEditInputCellRoot
+      ref={ref}
       inputRef={inputRef}
       className={classes.root}
       fullWidth
@@ -119,7 +123,7 @@ function GridEditInputCell(props: GridEditInputCellProps) {
       {...other}
     />
   );
-}
+});
 
 GridEditInputCell.propTypes = {
   // ----------------------------- Warning --------------------------------
```

**Comment by tnoetzel** [comment]
In case anybody else is struggling with this, here's a temporary workaround until `GridEditInputCell` and `Tooltip` play nicely together:

```
    function renderMyCustomEditComponent(props: GridRenderEditCellParams) {
        return (
            <div>
                <div>
                    <GridEditInputCell {...props} />
                </div>
                <Box sx={{ width: '100%' }}>
                    <Tooltip open={!!props.error} title={props.errormessage || ''} arrow>
                        <div></div>
                    </Tooltip>
                </Box>
            </div>
        );
    }
```

All those extra divs are there to make sure that the tooltip stacks directly under the Input cell...
