### ISSUE TITLE
Can't resolve 'date-fns/addDays

### ISSUE THREAD

**Issue by richardHaggioGwati** [mui/mui-x#5460]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am getting an uncaught type error while trying to create a duplicate of the date picker provided by the docs at (date picker)[https://mui.com/x/react-date-pickers/date-time-picker/].

### Expected behavior 🤔

I am expecting an output similar to the docs

### Steps to reproduce 🕹

Link to live example:

Steps:
1.import AdapterDateFns from '@mui/x-date-pickers/AdapterDateFns'
2. Add AdapterDateFns as a prop to LocalizationProvider dateAdapter

### Context 🔦

I was trying to add a date picker for the particular application that I am working on.

### Your environment 🌎

<details>
  <summary>
<code>
npm @mui/x-date-pickers/AdapterDateFns
Visual Studio code v1.6.9
OS: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.60 GHz
Browser Chrome
</code>
</summary>

</details>

**Comment by m4theushw** [comment]
I didn't understand what is the problem. Could you provide a reproduction? [This **codesandbox.io** template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) _may_ be a good starting point.

**Comment by richardHaggioGwati** [comment]
Thanks after attempting to reproduce the same error on the code sandbox provided, I discovered that the error was a result of a missing module, the date-fns module.
