### ISSUE TITLE
[data grid] During initialization, the column order respected the initial state but after a second it changes to the order put in the column prop

### ISSUE THREAD

**Issue by LuisVelica** [mui/mui-x#5461]
### Order ID 💳

Order #46536

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Could you provide a minimal reproduction? [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point.

By looking at the title, it might be that the columns are not memoized, so related to https://github.com/mui/mui-x/issues/4950. But sending a reproduction is better for us to help you.
