### ISSUE TITLE
[RFC] Differentiate unstable and private apis

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#5463]
## Current nomenclature

We currently use the prefix `unstable_` for any api we don't want user to use without a second look.
This cover a lot of very different use cases:

1. Core APIs of the grid that will probably never go public (`api.unstable_registerControlState`, `api.unstable_applyPipeProcessors`, ...)

2. Internal APIs of some grid plugins, used in other plugins or in the rendering phase (`api.unstable_calculateColSpan`, `api.unstable_getRowWithUpdatedValuesFromCellEditing`, ...)

3. APIs / props / column properties of features non released yet (`api.unstable_setAggregationModel`,  `props.unstable_disableAggregation`, `colDef.unstable_availableAggregationFunctions`, ...)

4. Recent APIs on which we must be able to make breaking change if need be (`api.unstable_getViewportPageSize`, unstable_applyFilters`, ...)

## Problem

We are using this prefix for use-cases so different that it is not clear what is the privacy status of an api method is (same for props or column properties but the api methods represents the vast majority of the prefixed elements).

For instance, if needed we could document `unstable_getViewportPageSize` in the documentation. For this method, the `unstable_` prefix really means "not stable, be careful when using it".
But for other methods like `unstable_registerControlState`, the `unstable_` means "private, if you use it you are doing something wrong".

This can be problematic for both our users on internally in our team.
For our users, because if I see `unstable_` methods documented or recommended in GitHub issues, I can think that all `unstable_` methods have the same privacy status.

For our team, because when breaking an `unstable_`, it is hard to know how much effort to put in the migration:
- if it's an internal method we can break every week if we want.
- if it's an unstable method used by our users we avoid doing to many breaking changes when not needed (unstable methods would be an equivalent of a beta phase here, break only if needed and add a not in the changelog).

For our team, it is also hard to track the unstable methods that should go stable because they are lost among a lot of internals methods.
We add those methods as `unstable_`, don't talk about them anywhere and therefore have no feedbacks. It makes the testing phase of those methods very ineffective.

## Solution

Introduce a new prefix `private_` (or `internal_`) that would only be used for methods that users should use under no circumstances (points 1., 2. and 3 above).
The methods (and props / col def properties) could be automatically ignored by the documentation, and we could at any point in time move them to a private and inaccessible api object in the future).

The `unstable_` would then only be used for public apis that are not stable enough yet.
They should be documented and could be used in the solutions we give to GitHub issues.
All new methods with a non-trivial signature could first start with an `unstable_` prefix is we feel the need (maybe not for every method, for instance a model setter like `setRowGroupingModel` has a very standarized signature).

## Do we need `experimentalFeatures`?

The `experimentalFeatures` props is meant to flag a whole feature as experimental, including behavior enabled by default once the feature will be fully released.
For instance, users can group rows through the column menu without any explicit props passed to the grid, the experimental feature was also removing this behavior when it was in place.
Which means that the `experimentalFeatures` are not something that can be replaced just by a prefix.

Those two systems need to work together.
If we take the release cycle of a new major feature, here is how it could work:

1. We release the feature as private (only use this step if something prevents from making the feature public right-away, for instance if we need a follow-up PR)

All the api methods, props, column properties are prefixed with `private_`.
The experimentation feature is needed for the feature to work (otherwise the grid works as if the feature did not exist).
Even the experimental feature is prefixed wit `private_`.
The documentation page is not accessible, and we don't advertise about this feature in the release notes highlights or on a blog post.

2. We publish the feature as experimental

Remove the `private_` prefix from the api methods, props, column properties and experimental feature.
The experimentation feature is needed for the feature to work (otherwise the grid works as if the feature did not exist).
The documentation page is accessible and contains a clear warning that this feature is experimental.
We add a highlight in the release notes, and we publish a blog post.

Some methods can an `unstable_` prefix if we are unsure about there behavior or signature (maybe the `unstable_` is not useful here and could be added when we remove the feature from the experimental features).

3. We mark the feature as stable

Remove the feature from the experimental features. It can now have behavior applied by default (some column menu for instance).
Remove the warning in the documentation.
If we are still unsure about the behavior or signature of some api methods, keep the `unstable_` prefix on them (or add it).

4. We mark the api method as stable

This step can easily be forgotten and the api method be kept `unstable_` forever.
I don't know if it is something we want.
Is the `unstable_` prefix purely for something the might change between minors versions because it's not stabilized yet.
Or is it also a way of reducing the size of the stable api to make breaking change easier even for very old methods.

**Comment by oliviertassinari** [comment]
> private_ (or internal_)

npm package.json uses private, TypeScript uses private for classes, React Native uses private, React uses internal, we have started to use private in `@mui/private-theming`. So :+1: for private.

> Problem

I think that we can widen the RFC to also encompass @mui/core. `unstable_createChainedFunction`, I don't see why we would ever make it public, it could be `private_createChainedFunction`. Same for `unstable_capitalize`, `unstable_debounce`. Looking at the other modules, like `unstable_useForkRef`, this is interesting, it's a module that many other developers could benefit from so we could make it public, so `private_` doesn't work, but we don't want to commit to semver so might stay `unstable_` for a long time. 

I think that we could also ban this prefix: `experimental_`.

**Comment by siriwatknp** [comment]
Agree with `private` prefix.

For the `experimental_` vs `unstable_`, I lean toward `experimental_` because it is more friendly and has closer meaning to what we want to communicate.

Those APIs are exposed as an experiment to get feedback from the community. Maybe the difference between is:
- `experimental_`: "We are quite sure that CSS variables will be heavily adopted, so we expose `Experimental_CssVarsProvider`, some props and some behavior might change based on the feedback and will be stable at some point in the near future.
- `unstable_`: "We want to try the CSS Grid but we are not sure if it is going to work, so we expose `Unstable_CssGrid`. If it does not work, we will remove it."

> Note: this is just an example of `unstable_` meaning, I understand that we have the lab package.

**Comment by joserodolfofreitas** [comment]
+1 for the `private_` prefix.

As for `experimental_` vs `unstable_` API prefixes: 
I haven't seen this in other projects, but could it make sense to rename the prefix to `beta_` ? 
As more I think about it, it's an option that seems to be the most friendly (in terms of encouraging usage) and unambiguous to what we want to use it for (to use features that might still need some polishing on the API before the next major).

**Comment by mnajdova** [comment]
+1 for using `private_` & `unstable_`, it resonates mostly with what other packages are doing. React uses `unstable_` - https://reactjs.org/docs/faq-versioning.html#what-counts-as-a-breaking-change btw @oliviertassinari didn't you created a similar page like this for MUI Core, or did we just discuss it?

**Comment by oliviertassinari** [comment]
> didn't you created a similar page like this for MUI Core, or did we just discuss it?

It reminds me https://github.com/mui/material-ui/pull/32850#discussion_r880508552 and https://mui-org.notion.site/Feature-release-strategy-52260e10c4cf4f898dcc10cd98fb23e5

**Comment by m4theushw** [comment]
I agree with `private_`. Basically everything we have as `unstable_` will be renamed to `private_` and **some** API methods, per user request, will have the unstable prefix.

> Is the unstable_ prefix purely for something the might change between minors versions because it's not stabilized yet.
> Or is it also a way of reducing the size of the stable api to make breaking change easier even for very old methods.

I believe it's both. We keep old methods with `unstable_` because we can't easily find a scenario where would make sense to make them public.

**Comment by cherniavskii** [comment]
Yes, we don't need the `private_` prefix anymore - private methods were introduced in https://github.com/mui/mui-x/pull/6388
