### ISSUE TITLE
GRID_DETAIL_PANEL_TOGGLE_FIELD field not sorting

### ISSUE THREAD

**Issue by bc4253** [mui/mui-x#5472]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

A custom detail panel toggle field with column definition field: GRID_DETAIL_PANEL_TOGGLE_FIELD is not sorting when the sort icon in the header is clicked.  The sort icon flips state when clicked, but the sortComparator function is not called.

### Expected behavior 🤔

Sorting should be allowed on a GRID_DETAIL_PANEL_TOGGLE_FIELD field.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/vibrant-shaw-mcfyn6?file=/src/App.tsx

Steps:
1. click the Job Title field and see the sorting work
2 click the Toggle Field field and see the sorting not working

### Your environment 🌎
Chrome 103.0.5060.114 (Official Build) (arm64)
npx @mui/envinfo does hangs running on M1 Macbook Pro

### Order ID 💳 (optional)

29981

**Comment by m4theushw** [comment]
You're using the ID from the 1st row to get the 2nd value to compare. The ID from the 2nd row should be passed to the 2nd `getRow(id)` call. Here's the updated CodeSandbox: https://codesandbox.io/s/sparkling-dust-h5xh4p?file=/src/App.tsx

**Comment by bc4253** [comment]
I totally missed that, thank you.
