### ISSUE TITLE
DatePicker onAccept not working in mobile view.

### ISSUE THREAD

**Issue by nikhilthakur001** [mui/mui-x#5474]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I've used onAccept to set the date value to a state. onAccept works fine in web browser. But on mobile view, it does not let me select any date. It shows a grey circle on selecting a date but on 'OK' click, onAccept is not fired.

**Comment by zulianAdryan** [comment]
I have the same issue here and still haven't solved the problem, the error is date picker wont select the picked date when we assign more than 1 value in views props e.g. ['month', 'year']. The onAccept props still works fine if its in desktop view mode, but if it changed to mobile view it won't work. any help?
