### ISSUE TITLE
[data grid] Make GridPreProcessEditCellProps generic

### ISSUE THREAD

**Issue by YunosukeY** [mui/mui-x#5488]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Make `GridPreProcessEditCellProps` generic.

I expect to use as both `GridPreProcessEditCellProps` and `GridPreProcessEditCellProps<Value, Row>`, even though now we can only use it as `GridPreProcessEditCellProps`.

### Examples 🌈

In packages/grid/x-data-grid/src/models/params/gridCellParams.ts,
```diff
-export interface GridPreProcessEditCellProps {
+export interface GridPreProcessEditCellProps<V = any, R extends GridValidRowModel = any> {
    /**
     * The grid row id.
     */
    id: GridRowId;
    /**
     * The row that is being edited.
     */
-    row: GridRowModel;
+    row: GridRowModel<R>;
    /**
     * The edit cell props.
     */
-    props: GridEditCellProps;
+    props: GridEditCellProps<V>;
    /**
     * Whether the new value is different from the stored value or not.
     */
    hasChanged?: boolean;
    /**
     * Object containing the props of the other fields.
     * Only available for row editing and when using the new editing API.
     */
-    otherFieldsProps?: Record<string, GridEditCellProps>;
+    otherFieldsProps?: Record<string, GridEditCellProps<V>>;
}
```

### Motivation 🔦

`GridPreProcessEditCellProps` is not generic.
Even though `GridRowModel` and `GridEditCellProps` are generic, `GridPreProcessEditCellProps["row"]` and `GridPreProcessEditCellProps["props"]["value"]` become `any`.
To type, we need to override the `GridPreProcessEditCellProps`.

**Comment by m4theushw** [comment]
Thanks for the suggestion. Do you want to submit a PR with the diff?

**Comment by YunosukeY** [comment]
Sure!
