### ISSUE TITLE
[data grid] Customizing the detail panel toggle ( gridDetailPanelExpandedRowsContentCacheSelector , useGridSelector )

### ISSUE THREAD

**Issue by alextaymx** [mui/mui-x#5489]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

<img width="811" alt="image" src="https://user-images.githubusercontent.com/58934562/178898049-89c4c404-0f6f-43b7-aa64-d2c3cb9cb1f4.png">

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/58934562/178898063-db343e21-d40b-40e5-a8f1-d65ee5ddc52a.png">

Exact same code from documentation : https://mui.com/x/react-data-grid/master-detail/#customizing-the-detail-panel-toggle

This code does not work with typescript, with the error as shown above. 

### Expected behavior 🤔

How do I solve Property 'acceptsApiRef' is missing in type '(state: GridStatePro) => Record<GridRowId, ReactNode>' but required in type 'OutputSelector<GridStateCommunity, Record<GridRowId, ReactNode>>' ? 

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Latest MUI-X     "@mui/x-data-grid": "^5.13.0",
2. Follow documentation from link above
3. Problem arise with Typescript project

### Context 🔦

1. Latest MUI-X     "@mui/x-data-grid": "^5.13.0",
2. Follow documentation from link above
3. Problem arise with Typescript project

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
 System:
    OS: macOS 12.4
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: Not Found
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.83 
    @mui/lab: ^5.0.0-alpha.83 => 5.0.0-alpha.84 
    @mui/material: ^5.8.1 => 5.8.2 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system: ^5.8.2 => 5.8.2 
    @mui/types:  7.1.3 
    @mui/utils: ^5.8.0 => 5.8.0 
    @mui/x-data-grid: ^5.13.0 => 5.13.0 
    @mui/x-data-grid-pro: ^5.13.0 => 5.13.0 
    @mui/x-date-pickers:  5.0.0-alpha.1 
    @mui/x-license-pro:  5.12.3 
    @types/react: 18.0.9 => 18.0.9 
    react: 18.1.0 => 18.1.0 
    react-dom: 18.1.0 => 18.1.0 
    typescript: 4.6.4 => 4.6.4 
```
</details>

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!
