### ISSUE TITLE
[Data Grid] With custom position filter panel is shown outside table view

### ISSUE THREAD

**Issue by konrazem** [mui/mui-x#5491]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When placing filter button on the right side, and anchor the filter panel to the toolbar button instead of the column header, makes filter panel be shown outside table view. 

By placing button on the right side of the table, after panel is opened it breaks application layout.

![1](https://user-images.githubusercontent.com/19363700/178938666-9302d692-eec1-4791-a362-1d13aa0e19a1.PNG)

Maybe related to this issue: https://github.com/mui/mui-x/issues/5183 
 

### Expected behavior 🤔

I would like to show filter panel under the filter button and filter panel to be inside table view. Moreover I would like to have custom position for filter panel AND column panel. Setting anchorEl for each one is not working 
```
  componentsProps={{
          filterPanel: {
            anchorEl: filterButtonEl,
          },
          columnsPanel: {
            anchorEl: filterButtonEl,
          },
  }}
``` 
To avoid this issue, the best in my case would be to make filter panel as draggable dialog, but I think this is feature request. Dragging would allow to filter and see specific cell values.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/customfilterpanelposition-demo-mui-x-forked-ml97n0?file=/demo.tsx 

Steps:
1. Move filter button to the table right side (toolbar)
2. Anchor the filter panel to the toolbar button (see docs here: https://mui.com/x/react-data-grid/filtering/#customize-the-filter-panel-position)
3. Open filter panel

### Context 🔦

I want to show panel under filter and column button, there where user is clicking not to making him/her searching for a panel. I want this panel to be inside table view. 

### Your environment 🌎

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 11.26 GB / 39.78 GB
  Binaries:
    Node: 16.14.0  
    Yarn: 1.22.15 
    npm: 8.3.1  
  Utilities:
    Git: 2.34.1.
  Virtualization:
    Docker: 20.10.12  
  IDEs:
    VSCode: 1.69.1 
  Languages:
    Bash: 4.4.20  
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.1566

### Order ID 💳 (optional)

46820

**Comment by m4theushw** [comment]
The default placement of the panel is `bottom-start`. If it's moved to the right, "start" doesn't work because there's no room for it. Changing to `bottom-end` solves the problem:

```tsx
<DataGrid
  componentsProps={{
    panel: {
      anchorEl: filterButtonEl,
      placement: "bottom-end"
    },
  }}
/>
```

Updated CodeSandbox: https://codesandbox.io/s/customfilterpanelposition-demo-mui-x-forked-67l2qr?file=/demo.tsx:1171-1404

> To avoid this issue, the best in my case would be to make filter panel as draggable dialog, but I think this is feature request. Dragging would allow to filter and see specific cell values.

You can make it draggable if you pass a custom panel, but it involves overriding completely the built-in panel component. See https://mui.com/x/react-data-grid/components/#components

**Comment by umeshjain1999** [comment]
Hey @m4theushw I have tried the same solution but for some reason I am getting this error on my local setup not on codesandbox though. 

**Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.**

**The above error occurred in the <button> component:
    at button**
