### ISSUE TITLE
[pickers] MUI X Date Picker - Out of Alpha?

### ISSUE THREAD

**Issue by detrio** [mui/mui-x#5497]
Hello,

I have a series of teams using MUI-X and they are currently blocked by the date picker being listed as being in an alpha state.  Is there any ETA as to when the date picker will be completed, or has it been de-prioritized?

**Comment by joserodolfofreitas** [comment]
Hello @detrio,

Thanks for asking that.
We haven't de-prioritized the date-pickers. In fact, it's the opposite.

From the latest release (v5.13), the date-pickers packages are already released as betas and are quite stable, and we'll likely release the first "official" version (non-prerelease) in about a month.

**Comment by danielgebhardt** [comment]
Just following up on this. Any update on when the first "official" version will be released? We're about to hit a pretty hard deadline to move to another datepicker component due to the beta tag, but we'd prefer to use yours in all of our apps. Hopefully a stable release in the next week or so?

**Comment by flaviendelangle** [comment]
The first stable version has been released on the 2nd of September 2022.
@danielgebhardt I hope it was soon enough.

Closing this issue.
