### ISSUE TITLE
Add prop "okLabel" and "cancelLabel" to MobileDatePicker, MobileDateTimePicker and MobileTimePicker

### ISSUE THREAD

**Issue by VityaSchel** [mui/mui-x#5500]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently `okLabel` and `cancelLabel` are not working in these components. There is also no alternatives to pass custom text or custom components to replace these buttons.

### Expected behavior 🤔

I expect these components to have these props: `{ okLabel: React.ReactNode | string, cancelLabel: React.ReactNode | string }`. And if they're passed, replace default "CANCEL" and "OK" buttons with these components or replace text on these buttons.

### Steps to reproduce 🕹

N/A

### Context 🔦

N/A

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Brower: Chrome

  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: 102.0
    Safari: 15.3
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.85
    @mui/lab: ^5.0.0-alpha.82 => 5.0.0-alpha.86
    @mui/material: ^5.7.0 => 5.8.4
    @mui/private-theming:  5.8.4
    @mui/styled-engine:  5.8.0
    @mui/system:  5.8.4
    @mui/types:  7.1.4
    @mui/utils:  5.8.4
    @mui/x-date-pickers: ^5.0.0-alpha.7 => 5.0.0-alpha.7
    @types/react: 18.0.9 => 18.0.9
    react: 18.1.0 => 18.1.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 4.6.4 => 4.6.4
```
</details>

**Comment by m4theushw** [comment]
These props existed in the past and, since they are also used for localization, they were removed in favor of using the theme to provide the strings to use in the UI. This new approach centralizes in a single place all strings for all MUI components. You can find more information in https://mui.com/x/react-date-pickers/localization/#translation-keys

Here's an example of how to override these two buttons:

```ts
import { enUS as coreEnUS } from "@mui/material/locale";
import { enUS } from "@mui/x-date-pickers/locales";

const theme = createTheme(
  { ... },
  {
    components: {
      MuiLocalizationProvider: {
        defaultProps: {
          localeText: {
            ...enUS.components.MuiLocalizationProvider.defaultProps.localeText,
            okButtonLabel: "ACCEPT",
            cancelButtonLabel: "DISMISS"
          }
        }
      }
    }
  },
  coreEnUS
);
```

You can also provide these overrides directly to `LocalizationProvider` to the `localeText` prop.
