### ISSUE TITLE
disable the date change onClose this is more troubling the users ,problem is the state and newValue changing after the user click outside .

### ISSUE THREAD

**Issue by reddy-sravan12** [mui/mui-x#5501]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Thanks for opening this issue. Could you provide a reproduction and fill the sections about current and expected behavior. I didn't understand the problem being reported. You can use [this **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) as a starting point.
