### ISSUE TITLE
[data grid] Using singleSelect with cell edit mode

### ISSUE THREAD

**Issue by cliedeman** [mui/mui-x#5502]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When combining singleselect with cell edit mode the selects are open when a record is added. This is okay with one but if you have 2 they both pop open after clicking add

<img width="483" alt="image" src="https://user-images.githubusercontent.com/3578740/179167289-7c98518a-0c55-4ec3-a25b-6139113bdd00.png">

### Expected behavior 🤔

singleselects stay closed. Row edit mode works correctly

### Steps to reproduce 🕹

https://codesandbox.io/s/fullfeaturedcrudgrid-demo-mui-x-forked-dv48zi?file=/demo.tsx

1. Click Add Record

### Your environment 🌎

 System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: 94.0.1
    Safari: 15.4
  npmPackages:
    @emotion/react: 11.9.0 => 11.9.0 
    @emotion/styled: 11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.76 
    @mui/icons-material: 5.6.1 => 5.6.1 
    @mui/lab: 5.0.0-alpha.77 => 5.0.0-alpha.77 
    @mui/material: 5.6.1 => 5.6.1 
    @mui/private-theming:  5.1.1 
    @mui/styled-engine:  5.6.1 
    @mui/styles: 5.6.1 => 5.6.1 
    @mui/system:  5.6.1 
    @mui/types:  7.1.3 
    @mui/utils: 5.6.1 => 5.6.1 
    @mui/x-data-grid: 5.12.3 => 5.12.3 
    @mui/x-data-grid-generator: 5.12.3 => 5.12.3 
    @mui/x-data-grid-premium:  5.12.3 
    @mui/x-data-grid-pro: 5.12.3 => 5.12.3 
    @mui/x-date-pickers:  5.0.0-alpha.0 
    @mui/x-license-pro:  5.12.3 
    @types/react: ^17.0.19 => 17.0.35 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: 4.4.4 => 4.4.4 

### Order ID 💳 (optional)

39468

**Comment by cherniavskii** [comment]
Hey @cliedeman 
Did you consider using `row` editing mode?
In `row` editing mode select is initially closed, but in `cell` editing mode it's a desirable behaviour to open it when editing starts:

https://github.com/mui/mui-x/blob/a3bb2ca59decc6accae980612478366563acd65e/packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx#L70

**Comment by cliedeman** [comment]
Hi @cherniavskii 
My use case needs cell editing mode.

**Comment by cherniavskii** [comment]
We can add `initialOpen` prop to `GridEditSingleSelectCell`:

```diff
diff --git a/packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx b/packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx
index ad46d8610..011a02f2d 100644
--- a/packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx
+++ b/packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx
@@ -38,9 +38,12 @@ export interface GridEditSingleSelectCellProps
    * @returns {Promise<void> | void} A promise to be awaited before calling `apiRef.current.setEditCellValue`
    */
   onValueChange?: (event: SelectChangeEvent<any>, newValue: any) => Promise<void> | void;
+  initialOpen?: boolean;
 }
 
 function GridEditSingleSelectCell(props: GridEditSingleSelectCellProps) {
+  const rootProps = useGridRootProps();
+
   const {
     id,
     value,
@@ -60,14 +63,14 @@ function GridEditSingleSelectCell(props: GridEditSingleSelectCellProps) {
     isProcessingProps,
     error,
     onValueChange,
+    initialOpen = rootProps.editMode === 'cell',
     ...other
   } = props;
 
   const apiRef = useGridApiContext();
   const ref = React.useRef<any>();
   const inputRef = React.useRef<any>();
-  const rootProps = useGridRootProps();
-  const [open, setOpen] = React.useState(rootProps.editMode === 'cell');
+  const [open, setOpen] = React.useState(initialOpen);
 
   const baseSelectProps = rootProps.componentsProps?.baseSelect || {};
   const isSelectNative = baseSelectProps.native ?? false;
```

Then it will be possible to override it through `renderEditCell`:
```tsx
renderEditCell: (params) => (
  <GridEditSingleSelectCell {...params} initialOpen={false} />
),
```

**Comment by shapaaa** [comment]
Hi @cherniavskii,
Can I take this issue to contribute?

**Comment by cherniavskii** [comment]
> Hi @cherniavskii,
> 
> Can I take this issue to contribute?

Sure, go ahead!

**Comment by m4theushw** [comment]
> My use case needs cell editing mode.

Note that the demo provided won't work with `editMode="cell"`. We can go forward and merge #5646 but this specific demo needs `editMode="row"` to work correctly. It could be converted to use cell editing mode, however, after editing the first cell of the newly added row it will save it and go back to view mode. For `editMode="cell"`, the equivalent props must be used, e.g. `cellModesModel`: https://mui.com/x/react-data-grid/editing/#controlled-mode
