### ISSUE TITLE
[data grid]onSortModelChange callback sometimes can not return GridSortModel

### ISSUE THREAD

**Issue by sudokzt** [mui/mui-x#5509]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello! I ran into an unexpected bug in using the DataGrid sort function.
When I click the sortable icon, it doesn't return a GridSortModel as a callback parameter.

The following movie is the actual situation.

https://user-images.githubusercontent.com/35422367/179348590-aed7e802-e5bf-4c9a-8563-981dfffddb7c.mov

I just used the Datagrid component in a basic way. The following is actually code.
```
<DataGrid
  columns={columns}
  getRowId={(row) => row.key}
  rows={roles}
  onSortModelChange={(model) => console.log(model)}
/>
```

Versions: 

```
react: 17.0.2
@mui/material: 5.4.1
@mui/x-data-grid: 5.13.1
```

### Steps to reproduce 🕹

Link to live example:

Steps:
1. print the Datagrid component 
2. click continuously the sortable icon

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @sudokzt thanks for raising this!
To be honest I'm struggling to understand the problem. In the video you have attached the `onSortModelChange` behaves as expected - if there is a sorting applied then the `onSortModelChange` returns that sort model. Basically, on every 3rd click, it will return an empty array because the 3rd click resets the sorting of that column.

Maybe there is something else that I'm missing?

**Comment by m4theushw** [comment]
I'm closing since we had no feedback.

**Comment by RoryH** [comment]
I have just encountered this also. I did not expect the third click to reset to no/default sorting. I went back a read the documentation and if you need to change this behaviour see the `sortingOrder` prop: https://mui.com/x/react-data-grid/sorting/#custom-sort-order

**Comment by cjauvin** [comment]
Wow just stumbled on this, many thanks @RoryH !!
