### ISSUE TITLE
DataGridPro/Premium newEditingApi doesn't have an onCellEditCommit? Looking for a method to confirm if a cell has been changed after editing.

### ISSUE THREAD

**Issue by camnealie** [mui/mui-x#5526]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We recently upgraded to the Premium plan, but have been using Pro for the last year.

When a user edits a cell in a datagrid, we capture that edit using the onCellEditCommit prop and immediately send it to the backend where it updates the database. That works great, except there doesn't appear to be an easy way to check if the user actually MADE a change or not. There are several cases where a user might start editing a cell, and trigger onCellEditCommit without having made any changes to the cell value.

I was hoping that using the experimentalFeatures={{ newEditingApi: true }} prop would offer some different tools to tackle this problem - but it seems that there isn't an onCellEditCommit prop available at all when I use that prop. There IS a onCellEditStop, but that offers ONLY the pre-edited value of the cell.

I feel I must be missing something obvious. There's no point in presenting editable cells if you can't see the values after they've been edited? 

### Examples 🌈

https://mui.com/x/react-data-grid/editing/#value-parser-and-value-setter

https://mui.com/x/react-data-grid/editing-legacy/

### Motivation 🔦

I'm a little worried that v6 of the datagrid won't have a method for us to capture cell changes...?

### Order ID 💳 (optional)

47345

**Comment by cliedeman** [comment]
Also looking for this

My case is slightly different. 

I have an autocomplete rendered into an edit cell. When the user clicks the clear icon I want to commit the change so I can re-add the option the user cleared to the list of options - The options are filtered by which ones are already being used

**Comment by m4theushw** [comment]
> When a user edits a cell in a datagrid, we capture that edit using the onCellEditCommit prop and immediately send it to the backend where it updates the database.

You can use `processRowUpdate` now to achieve that. See https://mui.com/x/react-data-grid/editing/#persistence

**Comment by camnealie** [comment]
processRowUpdate doesn't quite fit what I'm after, but thank you for pointing me in that direction. 

I need a processCellUpdate - something specific to the cell with the old value and new value. Any chance that's in the works?

**Comment by m4theushw** [comment]
`processRowUpdate` is called with both the updated row and the old row. You can check each key to discover which one was changed. Or, listen first for `onCellEditStart` to know which cell entered the edit mode. What you're trying to implement that needs the field in `processRowUpdate`?
