### ISSUE TITLE
[data grid] Grid cells inconsistent state when trying to edit cell validating it with a server

### ISSUE THREAD

**Issue by nicmesan2** [mui/mui-x#5540]
### Duplicates

- [X] I have tested the latest version
- [X] I have searched the existing issues

### Current behavior 😯

If we go to the documentation example https://mui.com/x/react-data-grid/editing/#persistence and edit a cell, and immediately before the server responds try to edit another one, the second cell will remain in edit mode forever (until the Datagrid component is unmounted and mounted again).

### Expected behavior 🤔

The second cell should not be able to become editable or it should become editable but behave as the first one (don't remain in editable mode forever).

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Go to the https://mui.com/x/react-data-grid/editing/#persistence example
2. Double click in one cell, edit it a lose focus.
3. Immediately after that (and before the server responded the first request) double click in another cell.
4. The second cell remains in edit mode forerever.

**Comment by DanailH** [comment]
Hi @nicmesan2 thanks for raising this!
I'm able to reproduce the issue. It's clearly visible in our docs.
