### ISSUE TITLE
[pickers] Month picker should close upon selecting a month

### ISSUE THREAD

**Issue by sam22** [mui/mui-x#5546]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Relevant configuration:

      <LocalizationProvider dateAdapter={AdapterDateFns}>
        <DatePicker
          views={['month','year']}
          .....
        />
      </LocalizationProvider>

1. Click datepicker
2. Opens to month
3. Select month
4. Opens to year
5. Select year
6. Datepicker closes

### Expected behavior 🤔

1. Click datepicker
2. Opens to month
3. Select month
4. Datepicker should close

Note: user has option to select year in order to change. Default behavior and what the expected normal use case should be that the picker closes after month selection

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Add datepicker with month, year view config
2. Click
3. Will be forced to choose year

### Context 🔦

Unwanted behavior which adds steps for user. Creates poor user experience.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
- Chrome 
-   "_from": "@mui/x-date-pickers",
- "_id": "@mui/x-date-pickers@5.0.0-beta.1",
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by sam22** [comment]
Here is example. The preferable behavior is to not have the year option show after choosing a month.

https://codesandbox.io/s/date-and-time-pickers-forked-wu12uy?file=/src/App.tsx

**Comment by flaviendelangle** [comment]
Sorry for the delay
If you want to have an optional view that is not in the default workflow, you should put it before and use `openTo`.
That way, the pickers consider the `month` view as the last view and close after it.

https://codesandbox.io/s/date-and-time-pickers-forked-i08qfl?file=/src/App.tsx
