### ISSUE TITLE
[DataGrid] Can I change the options in filter column?

### ISSUE THREAD

**Issue by momolly1024** [mui/mui-x#5553]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi, Does any api for DataGrid can change the options in filter column?
( Now the options default is all my data )
 

### Examples 🌈

For example 
If I want to remove 'ERP ID' , how can i do ?

![image](https://user-images.githubusercontent.com/61406208/180117487-efec44b2-60a6-4acf-9f77-2b923e5dbba4.png)

**Comment by DanailH** [comment]
Hi @momolly1024 thanks for raising this!
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

That being said what is displayed under the columns selected in the filter panel is the columns `headerName` if that is being provided. If not the `field` value will be used.

**Comment by momolly1024** [comment]
Hi @DanailH :) Thanks for replying.
For example, [In this codesandbox](https://codesandbox.io/s/data-grid-community-forked-nsp9qf?file=/src/App.tsx),
If i don't want "col3" in filter panel, How can I do to hide that?
 
As the meaning is,  Is there any way to change the option in filter panel ?


![image](https://user-images.githubusercontent.com/61406208/180338767-ee190fc8-4924-4ea7-8b8e-eb89072b0864.png)


Thank you very much :)
Have a nice day!

**Comment by momolly1024** [comment]
LOL, I found the solution.
Just add ' filterable:false ' in colunm!

thx :)

**Comment by DanailH** [comment]
@momolly1024 I'm happy that you were able to find the solution. Now that I read your response it seems that I misunderstood your question.

**Comment by momolly1024** [comment]
@DanailH  Yap but no problem :)
