### ISSUE TITLE
[pickers] Responsive time pickers demo crashes

### ISSUE THREAD

**Issue by natac13** [mui/mui-x#5554]
- [ ] I have [searched for similar issues](https://github.com/mui-org/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20ResponsiveTimePickers%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://v5-0-6.mui.com/components/time-picker/#responsiveness
2. Clear the desktop value and open the mobile time field and select the am pm first
3. demo *ResponsiveTimePickers* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v5.0.6  |
| netlify deploy | https://618a6bdbda63e90008f31636--material-ui-docs.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36 |

**Comment by flaviendelangle** [comment]
Hi,

I can reproduce your bug on the old documentation you linked, but not on the last one ([here](https://mui.com/x/react-date-pickers/time-picker/#responsiveness))

Can you reproduce it on the last version ?

**Comment by natac13** [comment]
I was worried about that. As I see the time picker and date picker have moved from the free package to the pro package. And not even a breaking change in the version!! 
I do not have time to upgrade the packages right now. For now I have hidden the am pm buttons until a time vale is set.


However I would like to express the frustration in see Mui move a component and not even do a breaking change version bump.

**Comment by flaviendelangle** [comment]
The time picker and date picker moved to `@mui/x-date-pickers` which is steal MIT and free.
They were in the lab which, by nature, is unstable and allows breaking change in minor. Breaking changes that we prepared for months with warning both in the doc and in the code.

**Comment by natac13** [comment]
I guess I should mention we do PAY for MUI x-data-grid-pro. In the early bird access at my request as I have enjoyed working with and also contributing to MUI. 

However things feel very corporate now. Just fyi

**Comment by natac13** [comment]
Can you share the link to the warning about the Time picker being moved. I am not able to find in in the older docs when viewing the TimePicker Demo page or the About the Lab page.

Also, I am not trying to fight with you.

**Comment by flaviendelangle** [comment]
You have

- The blog post explaining why the components are moving: https://mui.com/blog/lab-date-pickers-to-mui-x/
- The warning when calling the components introduced in `@mui/lab@5.0.0-alpha.85` by https://github.com/mui/material-ui/pull/31831
- The "Date & Time pickers" documentation page on the core demo briefly explaining what was going on and redirecting to the new doc and to the blog post: https://deploy-preview-32638--material-ui.netlify.app/material-ui/lab-date-and-time-pickers/ (it has been removed since to finalize the migration, maybe this page should have stayed longer)

**Comment by natac13** [comment]
So yeah I am not able to keep up with the numerous blogs being posted on the internet. 
I am currently on alpha.78
And I never saw that page as I was not doing much MUI development for the last little while as everything was GREAT!

So sorry about not knowing but I think there should be some understanding from MUI in the fact not everyone can keep up to the numerous changes happening across the 100s of dependencies that make up a react project these days. 

Yes I know the Lab is subject to breaking changes and it was in a Alpha state. 
But again I am a team of 1 developer building an entire app which has now just purchased by a larger company. But still only a team of 1 here. 

Just some understanding was all I was looking for....
