### ISSUE TITLE
[pickers] Time in DateTimePickerToolbar is backwards in RTL theme

### ISSUE THREAD

**Issue by noam7700** [mui/mui-x#5561]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

It should display the time correctly (hh:mm)

### Expected behavior 🤔

It displays the time in reverse (mm:hh)

### Steps to reproduce 🕹

Link to live example (2 live examples):
- go to docs [DateTimePicker mobile example](https://mui.com/x/react-date-pickers/date-time-picker/#responsiveness) and change to RTL in options.
- [sandbox](https://codesandbox.io/s/responsivedatetimepickers-demo-mui-x-forked-pwdtlk?file=/demo.tsx). copied sandbox from DOCS and added RTL ([guide in docs](https://mui.com/material-ui/guides/right-to-left/))

Steps (same for the above live examples):
1. Create MobileDateTimePicker
2. add RTL
3. Open it

### Context 🔦

Im trying to use MobileDateTimePicker with RTL. the time seems to be revesered.

I saw the same issue in the old Material UI [here](https://github.com/mui/material-ui-pickers/issues/1071). Also, I saw code that is supposed to handle this in the new Mui [TimePickerToolbar.tsx#L30](https://github.com/mui/mui-x/blob/0a0235b7b47d7854f79e54d3c8ce8ec3c42b3d18/packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx#L30). but somehow the bug still exists

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: Not Found
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.41
  npmPackages:
    @emotion/react: ^11.7.1 => 11.9.3 
    @emotion/styled: ^11.6.0 => 11.9.3 
    @mui/base:  5.0.0-alpha.86 
    @mui/icons-material: ^5.4.1 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.70 => 5.0.0-alpha.87 
    @mui/material: ^5.2.6 => 5.8.5 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/styles: ^5.2.3 => 5.8.4 
    @mui/system:  5.8.5 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.4 
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-alpha.1 
    @types/react: ^17.0.11 => 17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.3.4 => 4.7.4
```
</details>

**Comment by noam7700** [comment]
Here's a screenshot of the bug (the time is 12:30, but it shows 30:12):

![image](https://user-images.githubusercontent.com/41344731/180222099-1caf42cf-25ac-48c7-ad01-e444ac25d18a.png)

**Comment by noam7700** [comment]
Here's a workaround:
```typescript
import { DateTimePickerToolbar, dateTimePickerToolbarClasses } from '@mui/x-date-pickers/DateTimePicker/DateTimePickerToolbar';
import { BaseToolbarProps } from '@mui/x-date-pickers/internals';

const CustomDateTimePickerToolbar = styled(DateTimePickerToolbar)({
    [`& .${dateTimePickerToolbarClasses.timeContainer}`]: {
        display: 'flex',
        flexDirection: 'row-reverse', // support rtl! see issue https://github.com/mui/mui-x/issues/5561
    },
}) as (props: BaseToolbarProps<Date, Date | null>) => JSX.Element;
```

**Comment by alexfauquette** [comment]
Thanks for the detailed issue.

The fix you found in the code works, but it only applies to the TimePicker. The same code should be written for the other toolbars (not sure DatePickerToolbar needs it)

Here is a comparison between LTR and RTL mobile components
https://codesandbox.io/s/responsivedatetimepickers-demo-mui-x-forked-ogp73b?file=/demo.tsx

**Comment by galdahan** [comment]
Same problem with the StaticDateTimePicker

**Comment by alexfauquette** [comment]
@galdahan Yes, all the DateTime (`StaticDateTimePicker`, `MobileDateTimePicker`, `DesktopDateTimePicker`, `DateTimePicker`) are using the same default toolbar, so have the same behavior

If you want to open a PR to fix it, the [TimePickerToolbar](https://github.com/mui/mui-x/blob/0a0235b7b47d7854f79e54d3c8ce8ec3c42b3d18/packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx#L30) already have a fix for it to copy past

**Comment by galdahan** [comment]
@alexfauquette I tried to paste code from here [TimePickerToolbar](https://github.com/mui/mui-x/blob/0a0235b7b47d7854f79e54d3c8ce8ec3c42b3d18/packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx#L30) into [DateTimePickerToolbar](https://github.com/mui/mui-x/blob/0a0235b7b47d7854f79e54d3c8ce8ec3c42b3d18/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx) but with no luck. 
I am new to react so this syntax is very confusing me. 
As I understanding right now - making the change in [DateTimePickerToolbar](https://github.com/mui/mui-x/blob/0a0235b7b47d7854f79e54d3c8ce8ec3c42b3d18/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx) will fix all those cases (StaticDateTimePicker, MobileDateTimePicker, DesktopDateTimePicker, DateTimePicker).
If someone more familiar with this react syntax can help me solve this, it will be great.
Thanks in advance

**Comment by alexfauquette** [comment]
@galdahan I just opened a PR to fix if, if you want to have a look

By the way, we are working on supporting other adapters, and I was wondering, if this is the correct way to display a date-time in right to left
![image](https://user-images.githubusercontent.com/45398769/197969689-2896c22c-3ec2-46d1-a1eb-2146196935ec.png)

**Comment by Eliav2** [comment]
are we sure this is fixed?

![image](https://github.com/mui/mui-x/assets/47307889/c5a9e410-33f5-4691-82a1-ce5bbc723bd9)

we can see that the minutes seconds are swapped.

**Comment by alexfauquette** [comment]
@Eliav2 this component did not even exist at that time ;)

Could you open an new issue?

**Comment by Eliav2** [comment]
haha sorry for that. opened an issue for that
