### ISSUE TITLE
[discussion] New doc structure for the pickers

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#5565]
Related to #5539

The goal is to really start improving the pickers documentation in depth, both for the basic and the advanced use cases.

## Naming convention

I think this new doc structure should come with some components renaming in v6.

I tried to apply the new naming from https://github.com/mui/mui-x/issues/4484 for the `Static` components.
They are a good start, but I still struggle to clarify between: 

- a static picker like `StaticDatePicker`, which has a toolbar and a header to switch views
- a composite view like `CalendarPicker`, which has no toolbar but a header to switch views
- a granular view like `MonthPicker`, which has no toolbar and no header

I would like your opinion on this, for now I named all of them `XXXView` below.
I will try to do a full summary on #4484

## Proposal

- *Date and Time pickers*
  - *Introduction*
    - Overview (part of the current *Getting started*)
    - Installation (part of the current *Getting started*)
    - Migrating from the lab (current *Migration from the lab*)

  - *Pickers* (a field + a view inside a popper)
    - Date picker
    - Date range picker
    - Date time picker
    - Date time range picker
    - Time picker
    - Time range picker
  
  - *Fields* 
    - Date field (see #5531)
    - Date range field

  - *Standalone views*
    - Date picker view (current `StaticDatePicker`)
    - Date time picker view (current `StaticDateTimePicker`)
    - Time picker view (current `StaticTimePicker`)
    - Calendar picker view (current `CalendarPicker`)
    - Day picker view (current `DayPicker`)
    - Month picker view (current `MonthPicker`)
    - Year picker view (current `YearPicker`)

  - *Custom behaviors*
    - *Validation* (see #5539)
    - *Localization* (not sure where to put that one, maybe at the root instead of in a group of pages)

  - *Visual customization*
    - *Custom components* (will probably be splitted in the future) 

  - *Typescript*

  - *API Reference*
    - ...

**Comment by alexfauquette** [comment]
For clarification, I assume ùitalic* titles are pages/subpages and normal text sections in the page

- *Date and Time pickers*
  - *Introduction*
    - Overview (part of the current *Getting started*)
    - Installation (part of the current *Getting started*)
    - Migrating from the lab (current *Migration from the lab*)
  
	> Maybe this page can be very small, just two demos. One for community, the other for pro
	> It could also contain section "Structure overview" to share some vocabulary about view, fields, static
  - *Pickers* (a field + a view inside a popper)
  	- Single picker 
    	- Date picker
    	- Time picker
    	- DateTime picker
  	- Range picker (pro)
    	- Date range picker
	    - Time range picker
    	- Date time range picker
  
  - *Fields* 
    - Date field (see #5531)
    - Date range field

  - *Standalone views*
    - Date picker view (current `StaticDatePicker`)
    - Date time picker view (current `StaticDateTimePicker`)
    - Time picker view (current `StaticTimePicker`)
    - Calendar picker view (current `CalendarPicker`)
    - Day picker view (current `DayPicker`)
    - Month picker view (current `MonthPicker`)
    - Year picker view (current `YearPicker`)

	> Those pages could be root like for the data grid features are root
  - *Custom behaviors*
    - *Date validation* (see #5539)
    - *Localization* (not sure where to put that one, maybe at the root instead of in a group of pages)
    - *State management* (control open and view state)

  - *Visual customization*
    - *Custom components* (will probably be splitted in the future) 


  - *Typescript*

  - *API Reference*
    - ...


-----


About renaming everything with `View` at the end, I'm a bit concerned by the inconsistency it brings with `views=['year', 'month']` But I do not find a naming for `StaticDatePicker`

**Comment by samuelsycamore** [comment]
> For clarification, I assume *italic* titles are pages/subpages and normal text sections in the page

I assumed that this is what @flaviendelangle intended:

<img width="215" alt="Screen Shot 2022-07-29 at 9 24 36 AM" src="https://user-images.githubusercontent.com/71297412/181781279-906e1777-2715-4e31-ba59-c85a8d37d25b.png">

- _Date and Time pickers_
  - _Introduction_
    - Overview (part of the current Getting started)
    - Installation (part of the current Getting started)
    - Migrating from the lab (current Migration from the lab)

**Comment by flaviendelangle** [comment]
My proposal was what @samuelsycamore is describing

**Comment by samuelsycamore** [comment]
I like this new structure overall! I think we should go ahead and move forward with this. I don't have any strong opinions about the naming conventions.

**Comment by alexfauquette** [comment]
> About renaming everything with View at the end, I'm a bit concerned by the inconsistency it brings with views=['year', 'month'] But I do not find a naming for StaticDatePicker

I remove what I said, I've been confused about what `Static...Picker` is doing. I'm fine with the naming convention

**Comment by joserodolfofreitas** [comment]
+1 one for the new structure.
I'm only considering if it'd make sense to have a "customization" section instead of custom behaviors and visual customizations, because for instance I think "custom components" fit both.

But overall the structure seems very clear to me.

Another thing I was wondering if it makes sense:
Should we have a "Core concepts" section? Where we perhaps explain the integrations with the date libraries and the overall architecture of the components? (What's a view, a field, and etc?)

**Comment by flaviendelangle** [comment]
> I'm only considering if it'd make sense to have a "customization" section instead of custom behaviors and visual customizations, because for instance I think "custom components" fit both.

I see your points
Maybe we could create a collapsible *Customization* section (like for *Advanced* on the grid doc)
And when we split the current *Custom components* page, we create a "sub-section" (not sure how it's called), like "Inputs" below:

![image](https://user-images.githubusercontent.com/3309670/192767922-fac806aa-898c-4b90-a069-4ec9217ff9e7.png)

**Comment by flaviendelangle** [comment]
All the steps described in this issue have been done :partying_face:
