### ISSUE TITLE
[DatePicker] showDaysOutsideCurrentMonth unexpected behaviour

### ISSUE THREAD

**Issue by DavidJohnWilliams** [mui/mui-x#5570]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When `showDaysOutsideCurrentMonth` is true. If you select a date outside of the current month then it moves the view to the corresponding month.

If you then move back to the month you moved from and select the day again it picks the date.

### Expected behavior 🤔

Selecting a day from outside the current month should select the date.

If the behavior of switching to the view is desired then it should be configurable.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-vj66gc

Steps:
1. Open the picker
2. Click on the 1st of August (without changing month)
3. Click the back arrow to return to June
4. Click on the 1st of August again.
5. Observe that the date is now selected and the picker closes.

### Context 🔦

It is fairly standard behavior when selecting a date outside the current month is to simply select that date. This is the behavior for most UI libraries.

As a consequence using the MUI date picker can be slightly confusing and ultimately requires additional clicks to achieve the same thing.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 11.42 GB / 31.73 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.36.0.
  IDEs:
    VSCode: 1.69.0 - C:\Users\{user}\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.2.32616.157 (Visual Studio Enterprise 2022)
  Languages:
    Python: 3.10.4
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.22000.120
</details>

**Comment by DavidJohnWilliams** [comment]
Update: I have noticed that sometimes the expected behavior actually does work. If you click enough times (refreshing between each attempt) you will eventually get it to work. Seems to be something to do with state.

**Comment by alexfauquette** [comment]
@DavidJohnWilliams If you click fast (fast enough to have mousse down and up on the button, the selection is correctly set)

I put more details in the PR

**Comment by DavidJohnWilliams** [comment]
@alexfauquette  ahh yes, that makes a lot of sense. I had a hacky workaround to override the `onDayFocus` to check `mouseDown` but a proper fix will be welcome :)
