### ISSUE TITLE
5.14.0 overlay change adds `pointerEvents: none` which breaks buttons inside no rows overlay

### ISSUE THREAD

**Issue by philjones88** [mui/mui-x#5590]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

This change:

https://github.com/mui/mui-x/commit/aef8033fdaa0012a7eb4751cc5604333b46f3f63

Impacts our custom `components` `NoRowsOverlay` component that has a button in it to trigger the filter panel to show.

With `pointer-events: none` and I can't see a way to customize it, it is a breaking change in functionality for us from 5.13.x

### Expected behavior 🤔

Not have `pointer-events: none` or a way to customize the behaviour.

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 11.6.6
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Not Found
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.8.2 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/icons-material: ^5.8.4 => 5.8.4
    @mui/lab: ^5.0.0-alpha.91 => 5.0.0-alpha.91
    @mui/material: ^5.9.1 => 5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/utils:  5.9.1
    @mui/x-data-grid:  5.14.0
    @mui/x-data-grid-pro: ^5.14.0 => 5.14.0
    @mui/x-license-pro: ^5.14.0 => 5.14.0
    @types/react: ^17.0.39 => 17.0.47
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.6.3 => 4.7.4
```
</details>

### Order ID 💳 (optional)

44827

**Comment by alexfauquette** [comment]
I do not see a way to override the props of the wrapper overlay and the style is hardcoded in the element.

@DanailH is the pointer event property necessary for fixing the position?

**Comment by DanailH** [comment]
@alexfauquette I don't think so, we can do it without it.

**Comment by philjones88** [comment]
@alexfauquette @DanailH do you want me to raise a PR to remove that pointer event css?

**Comment by DanailH** [comment]
@philjones88 that would be great, thank you!
