### ISSUE TITLE
[data grid] Support pinned rows editing

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#5591]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Extracted from https://github.com/mui/mui-x/pull/4863
Editing pinned rows is not supported yet, but can be implemented.
Editing API uses `updateRows` method to store new model in the state:
https://github.com/mui/mui-x/blob/06bd76e94fba3476fece63399ca28c84d6ed3a8b/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts#L397-L405

But pinned rows are stored separately in the state.
One possible solution is to create `private_updatePinnedRows` method and use it when editing pinned rows.

**Comment by ryanjpaul** [comment]
Is there any update on this? Would be very useful for the product we are building

**Comment by b-d-m-jones** [comment]
I would also like row editing for pinned rows. :)

**Comment by koalex** [comment]
Any updates?

**Comment by jason-kwon-oneoncology** [comment]
I would also find this useful because when the table is sorted(asc or desc) and a user adds a new row in edit mode, it could result in the new row being added to the end of the table so not only does it seem like nothing happens, but the user has to navigate the table in order to edit the new row.

**Comment by cah-reeja-mathew** [comment]
hi is there a way to changed pinned row to another row?

**Comment by putnamn21** [comment]
@BLiAlPx  - i am setting a private property on the row data `_isNew: boolean` and then if a new row has been added to the grid, i set the grid sort model to sort on that property first. Once i detect there are no longer any added rows i remove sorting on _isNew.
```
 React.useEffect(() => {
    const currentSorting = apiRef.current?.getSortModel()
    const hasNewRow = rows.some((r) => r._isNew)
    const currentlySortingOnNew = currentSorting?.some(
      (v) => v.field === '_isNew',
    )

    if (hasNewRow && !currentlySortingOnNew) {
      apiRef.current?.setSortModel([
        { field: '_isNew', sort: 'desc' },
        ...currentSorting,
      ])
    } else if (!hasNewRow && currentlySortingOnNew) {
      apiRef.current?.setSortModel(
        currentSorting.filter((v) => v.field !== '_isNew'),
      )
    }
  }, [rows, apiRef])
```

**Comment by BLiAlPx** [comment]
@putnamn21 That's clever! Thank you.
