### ISSUE TITLE
Attempting to import @mui/x-date-pickers/themeAugmentation throws type errors

### ISSUE THREAD

**Issue by cjones26** [mui/mui-x#5593]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When attempting to utilize the theme augmentation to override global date picker styles as shown in the documentation[here](https://mui.com/x/react-date-pickers/getting-started/#typescript), we receive the following errors:

```
> npx tsc -p tsconfig.build.json --incremental --watch
[11:56:34 AM] Starting compilation in watch mode...

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:24:18 - error TS2314: Generic type 'DatePickerProps<TInputDate, TDate>' requires 2 type argument(s).

24   MuiDatePicker: DatePickerProps;
                    ~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:25:22 - error TS2314: Generic type 'DateTimePickerProps<TInputDate, TDate>' requires 2 type argument(s).

25   MuiDateTimePicker: DateTimePickerProps;
                        ~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:26:29 - error TS2314: Generic type 'DesktopDateTimePickerProps<TInputDate, TDate>' requires 2 type argument(s).

26   MuiDesktopDateTimePicker: DesktopDateTimePickerProps;
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:27:25 - error TS2314: Generic type 'DesktopTimePickerProps<TInputDate, TDate>' requires 2 type argument(s).

27   MuiDesktopTimePicker: DesktopTimePickerProps;
                           ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:28:24 - error TS2314: Generic type 'MobileDatePickerProps<TInputDate, TDate>' requires 2 type argument(s).

28   MuiMobileDatePicker: MobileDatePickerProps;
                          ~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:29:28 - error TS2314: Generic type 'MobileDateTimePickerProps<TInputDate, TDate>' requires 2 type argument(s).

29   MuiMobileDateTimePicker: MobileDateTimePickerProps;
                              ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:30:24 - error TS2314: Generic type 'MobileTimePickerProps<TInputDate, TDate>' requires 2 type argument(s).

30   MuiMobileTimePicker: MobileTimePickerProps;
                          ~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:33:24 - error TS2314: Generic type 'StaticDatePickerProps' requires 2 type argument(s).

33   MuiStaticDatePicker: StaticDatePickerProps;
                          ~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:34:28 - error TS2314: Generic type 'StaticDateTimePickerProps' requires 2 type argument(s).

34   MuiStaticDateTimePicker: StaticDateTimePickerProps;
                              ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:35:24 - error TS2314: Generic type 'StaticTimePickerProps' requires 2 type argument(s).

35   MuiStaticTimePicker: StaticTimePickerProps;
                          ~~~~~~~~~~~~~~~~~~~~~

node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts:36:18 - error TS2314: Generic type 'TimePickerProps<TInputDate, TDate>' requires 2 type argument(s).

36   MuiTimePicker: TimePickerProps;
                    ~~~~~~~~~~~~~~~

[11:56:41 AM] Found 11 errors. Watching for file changes.
```

### Expected behavior 🤔

We should not receive any type errors when attempting to import the augmentation types.

### Steps to reproduce 🕹

Link to live example: https://github.com/cjones26/datepicker-type-issue

Steps:
1. Clone the repo from the link above.
2. Run `npm run watch`

### Context 🔦

We are attempting to style our date picker after our upgrade to MUI 5 and are running into severe issues where global CSS styles are not applied, for example, something simple like the below code is not respected:

```
const theme = createTheme({
  palette: {
    primary: {
      main: red[600]
    }
  },
  components: {
    MuiCalendarPicker: {
      styleOverrides: {
        root: ({ theme }) => ({
          backgroundColor: theme.palette.primary.main
        })
      }
    }
  }
});
```

The documentation is extremely sparse in regards to styling the DatePicker, especially when it comes to the mobile date picker & potential ways to style the popper dialog.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Not Found
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @emotion/react: 11.9.3 => 11.9.3
    @emotion/styled: 11.9.3 => 11.9.3
    @mui/base: 5.0.0-alpha.91 => 5.0.0-alpha.91
    @mui/icons-material: 5.8.4 => 5.8.4
    @mui/material: 5.9.2 => 5.9.2
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/styled-engine-sc: 5.8.0 => 5.8.0
    @mui/system:  5.9.2
    @mui/types:  7.1.5
    @mui/utils:  5.9.1
    @mui/x-date-pickers: 5.0.0-beta.2 => 5.0.0-beta.2
    @types/react: 17.0.39 => 17.0.39
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: 5.3.5 => 5.3.5
    typescript: 4.7.4 => 4.7.4
```
</details>

**Comment by alexfauquette** [comment]
About the typescript error, it seems to be a regression on our side.

By looking at the git history, the problematic types `StaticTimePickerProps` for example have been transformed to generic only one month after the creation of the `themeAugmentation`. So I assume using `StaticTimePickerProps<unknown, unknown>` would solve the typing problem. 

However, I struggle to add a test to prevent that kind of problems

@cherniavskii do you have an idea about the testing? I tried the following but it does not work, maybe because tests are tuned with node and ignore all the typing

```ts
import { expect } from 'chai';
import { createTheme } from '@mui/material/styles';
import type { } from './index';


describe.only('pickers themeAugmentation', () => {
  it('should create theme without warning', function test() {
    const theme = {
      components: {},
    };

    const createdTheme = createTheme(theme);
    expect(createdTheme).not.to.equal(null)
  }
  )
});
```

---

> The documentation is extremely sparse in regards to styling the DatePicker, especially when it comes to the mobile date picker & potential ways to style the popper dialog.

Thanks for the feedback. When trying to customize the mobile component how did you expect to be able to do it?

On my side, I'm mostly using the props `paperProps={{sx: {} }}` which could be added by default, but that's not fully satisfying. We should do an overview of how to customize those components

**Comment by cherniavskii** [comment]
@alexfauquette Would same thing that we do in data grid work?
https://github.com/mui/mui-x/blob/06bd76e94fba3476fece63399ca28c84d6ed3a8b/packages/grid/x-data-grid/src/tests/themeAugmentation.spec.ts#L1-L22

```diff
diff --git a/packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts b/packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
new file mode 100644
index 0000000..d0f7724
--- /dev/null
+++ b/packages/x-date-pickers/src/themeAugmentation/themeAugmentation.spec.ts
@@ -0,0 +1,13 @@
+import { createTheme } from '@mui/material/styles';
+
+createTheme({
+  components: {
+    MuiDatePicker: {
+      defaultProps: {
+        toolbarTitle: 'Title',
+        // @ts-expect-error invalid MuiDatePicker prop
+        someRandomProp: true,
+      },
+    },
+  },
+});

```

**Comment by cjones26** [comment]
@alexfauquette, I actually ended up utilizing `DialogProps={{sx:{}}` in order to modify what we needed (the DialogActions section), though I don't think this is a great solution.  The two things which we are really seeking are:

- The ability to properly override the date picker specific dialog & paper from our theme `components` override section.  We were properly able to override `MuiCalendarPicker`, `MuiYearPicker`, `MuiMonthPicker` and `MuiPickersDay` but no luck with the dialog & paper.  It may be possible but I wasn't able to find a way to get it working.
- Slots in order to customize things like action header, main calendar section, and action buttons.

Thanks for the quick response, let me know if anything needs clarification!
