### ISSUE TITLE
[pickers] Breaking changes introduced in alpha are not in the migration guide

### ISSUE THREAD

**Issue by ChrisVesters** [mui/mui-x#5599]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

As mentioned in the documentation, there is no clearable or clearText property.
These properties do exist on the mui-lab versions.

https://mui.com/x/api/date-pickers/date-picker/
https://v5-0-6.mui.com/api/date-picker/

### Expected behavior 🤔

The migration guide does not mention this.
Moreover anyone using these properties now have to remove them.
There is no alternative provided.

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Hi @ChrisVesters 

Sorry for the difficulty with the migration. The guide only contains instructions to move from the lab to the alpha.0 version

We made two breaking changes during this phase:

- [modify auto closing behavior](https://github.com/mui/mui-x/releases/tag/v5.11.0)
- [modify action bar customization](https://github.com/mui/mui-x/releases/tag/v5.11.1) (the one you are looking for)
- [some props renaming for consistency across components](https://github.com/mui/mui-x/releases/tag/v5.12.0)

About modifying button text, the v5 supports [translations](https://mui.com/x/react-date-pickers/localization/#translation-keys)

We should add a section with the breaking change migration added during the alpha phase

**Comment by ChrisVesters** [comment]
Am I correct when I say that the clearText option is gone and now relies on the locale that you set?
So this means that I can't have custom text messages?

**Comment by alexfauquette** [comment]
Do you mean a custom `clearText` for a specific picker? Like most of the pikers have a clear button with "Clear" and a specific picker has "Revert Changes"?

If it's what you mean, there is a hack to do it which is to wrap this specific component in a `<LocalizationProvider/>` with `localeText`.

We had the idea to wrap components such that it would be possible to do `<DatePicker localeText={{clearButtonLabel: 'Revert'}} />` But that's not yet implemented

**Comment by ChrisVesters** [comment]
Ok, thanks for the information. Things are clear to me now.
