### ISSUE TITLE
[pickers] Popper placement relative to the input

### ISSUE THREAD

**Issue by netgfx** [mui/mui-x#5600]
Hello, I've tried to implement the solution shown here: https://github.com/mui/material-ui-pickers/issues/1115

But `PopoverProps` are no longer supported, I've tried with 
```
PopperProps={{
    placement: "right-end",
}}
```
but that moves the datepicker outside of the input bounds, I was trying to position the datepickers' right side on the right-bound of the input thus "aligning right" over the icon. This is doable with the old syntax via
```
PopoverProps={{
   anchorOrigin: { horizontal: "right", vertical: "bottom" }
}}
```
how could I achieve the same effect now?

**Comment by joserodolfofreitas** [comment]
Could you please provide a reproduction step, @netgfx ?

As a starting point, we recommend you [browse the documentation](https://mui.com/x/introduction/), and [select](https://mui.com/static/docs/forking-an-example.png) the closest example to your use case.
Or you can use a [basic template](https://mui.com/r/x-issue-template) to build your reproduction case.

**Comment by netgfx** [comment]
@joserodolfofreitas There you go https://codesandbox.io/s/materialuipickers-demo-mui-x-forked-pj38hj?file=/demo.tsx

**Comment by alexfauquette** [comment]
Effectively `PopoverProps` is not supported. Now you have 
- `PopperProps` for the desktop component
- `DialogProps` from the mobile component 

With those props, you can customize the Popper/Dialog placement as you would do with any Popper/Dialog.

I do not understand what you want to achieve. The issue you are referring to ask center the calendar below the input, which is now the default behavior.

**Comment by flaviendelangle** [comment]
Closing this one from lack of feedbacks
