### ISSUE TITLE
Does not fully translate the component

### ISSUE THREAD

**Issue by eugenestepanyuk** [mui/mui-x#5601]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

https://codesandbox.io/s/locales-demo-material-ui-forked-owmsxi?file=/demo.tsx
here is my example.
When selecting a row in the DataGrid does not translate "1 row selected", by default always English. How to make a translate?

### Expected behavior 🤔

Full translation of the components

### Steps to reproduce 🕹

Steps:

1. Choose any language in select component
2. Click on any row in DataGrid

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD    
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.18362.1533.0)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.88
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.7
    @mui/private-theming:  5.8.6
    @mui/styled-engine:  5.8.7
    @mui/system:  5.8.7
    @mui/types:  7.1.4
    @mui/utils:  5.8.6
    @mui/x-data-grid: ^5.12.2 => 5.13.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.1
    @types/react: 18.0.9 => 18.0.9
    react: 18.1.0 => 18.1.0
    react-dom: 18.1.0 => 18.1.0
    typescript: 4.6.4 => 4.6.4
```
</details>

**Comment by ConcernedHobbit** [comment]
@eugenestepanyuk did you close this as it is fixed locally? The workaround shouldn't be required and there might be a root issue in MUI X that is causing the unintended behavior. I'm not a MUI X user and will not progress this issue further, just wondering why it was closed.
