### ISSUE TITLE
[data grid] Consider using generic parameter as `unknown` instead of `any` in GridCellParams

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#5614]
# Summary

Consider using `V = unknown` instead of `V = any` in `GridCellParams` (as per https://github.com/mui/mui-x/pull/4774#issuecomment-1118462629)
https://github.com/mui/mui-x/blob/936655f43787892d8168ae87b0879968d38247fb/packages/grid/x-data-grid/src/models/params/gridCellParams.ts#L9

# Motivation

**Comment by TheRealCuran** [comment]
Personal opinion: please never use `any`, `unknown` is just strictly better. If you need to ensure a certain type at any point, use a type guard. See https://typescript-eslint.io/rules/no-explicit-any/ for additional information, why `any` is usually not a good idea.
