### ISSUE TITLE
[data grid] Manage server errors for sorting

### ISSUE THREAD

**Issue by shazebCeloxis** [mui/mui-x#5628]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

if i want to do sorting from server side and if the response gets rejected my sorting indicator doesnt change

### Expected behavior 🤔

i want the sorting indicator to change if the response gets rejected from the server as we are making the request to server on sortModelChange callback

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
You can control the [sort model](https://mui.com/x/react-data-grid/sorting/#controlled-sort-model) and then reset it to its previous value if server failed

DOes it solves your problem, or I missed something?

**Comment by shazebCeloxis** [comment]
thanks it worked
