### ISSUE TITLE
[DataGridPro] Column resize resets after re-render

### ISSUE THREAD

**Issue by pipje2001** [mui/mui-x#5633]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Resizing a column that has a "width" defined in the column definition will reset to that size once a re-render occurs, this also happens when a custom width is set via initialState

### Expected behavior 🤔

It should keep the width set by the user or initialState (if existing)

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/frosty-flower-jsxlfo?file=/src/App.tsx

Steps:
1. Have any kind of dataGrid
2. Cause a rerender, no matter if its related to the datagrid or not

### Context 🔦

I am keeping the current date at the top of the page (not in the same component) which causes a rerender every minute, but this also resets the column width even though the rerender is not related.

I am also saving the column width in localstorage so I can restore it via initialState after a reload of the page but this too doesn't work

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.22000 (I run windows 11, don't know why it says 10)
  Binaries:
    Node: 16.13.1 - c:\program files\nodejs\node.EXE
    @mui/x-date-pickers:  5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.2 => 5.0.0-beta.2
    @mui/x-license-pro:  5.12.1
    @types/react: ^18.0.9 => 18.0.9
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.7.4 => 4.7.4
```
</details>

I am unsure why @mui/x-data-grid-pro is missing, but its: @mui/x-data-grid-pro: "^5.14.0"

Tested on Vivaldi and Edge

### Order ID 💳 (optional)

#28117

**Comment by alexfauquette** [comment]
That's because `columns` should not be modified. Overwise the data grid will generate new columns (with the provided width)

You use the following line of code. The problem is that at each rendering, JS will generate a new array. So the Component will think that `columns` props have changed.

```jsx
<DataGrid columns={[column1, column2]} />
```

Either use a memorization or define the columns outside of the component.

Here is the fixed version: https://codesandbox.io/s/confident-leakey-kgim4x?file=/src/App.tsx

**Comment by pipje2001** [comment]
Oh that makes a lot of sense!

Thank you
