### ISSUE TITLE
[DataGrid] D&D column beyond visible part of the table doesn't work correctly with pinned columns

### ISSUE THREAD

**Issue by MatejBransky** [mui/mui-x#5637]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you want to drag a column beyond the visible part of the table with pinned columns, you must move the column to the pinned column area (near the edge of the table). See the recording: https://youtu.be/DGshcYanmfw

### Expected behavior 🤔

As a user, I would like to drag the column header and I expect that area activating the table's horizontal move will be somewhere between pinned columns and regular columns.

![image](https://user-images.githubusercontent.com/20944757/181486282-be3e1600-42c7-4e64-a758-38db25395848.png)

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Create so many columns that the table will show the horizontal scrolling
2. Pin some columns
3. Drag regular column (via column header)
4. Move with it to the part which is beyond the currently visible part

### Context 🔦

It relates to the overall problem that we can't easily move columns beyond the screen ([another issue is the inability to move columns over column headers row - for moving beyond the screen you have to move with the draggable column header to the data rows area](https://github.com/mui/mui-x/issues/5416)).

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: Google Chrome 103.0.5060.134 (Official Build) (64-bit)
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 42.40 GB / 63.61 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Cargo: 1.56.0 - ~\.cargo\bin\cargo.EXE
    Gradle: 6.8.3 - C:\Gradle\gradle-6.8.3\bin\gradle.BAT
    pip3: 21.2.3 - C:\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.29.2.
  Virtualization:
    Docker: 20.10.16 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    VSCode: 1.69.2 - C:\Users\matej.bransky\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.1.32407.343 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.12
    Python: 3.10.0
    Rust: 1.56.1
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
    Internet Explorer: 11.0.19041.1202
```
</details>

### Order ID 💳 (optional)

48059

**Comment by alexfauquette** [comment]
Effectively, it seems counter intuitive with the current behavior

**Comment by cherniavskii** [comment]
This has been solved in the Data Grid v7 https://stackblitz.com/edit/react-ekd188?file=Demo.tsx
