### ISSUE TITLE
Access to switches for columns visibilty (events)

### ISSUE THREAD

**Issue by deepen77** [mui/mui-x#5640]
Hi 
Is there a way to get the access to events under the switchers of columns. I would like to send request to API to recieve or not content of particular column ?

![image](https://user-images.githubusercontent.com/58135902/181508960-2f5720f2-c328-4f75-b285-7ab061ee6cd4.png)

Thanks in advance ...

**Comment by cherniavskii** [comment]
Hey @deepen77 
You can use controlled column visibility model and `onColumnVisibilityModelChange`: https://mui.com/x/react-data-grid/column-visibility/#controlled-visible-columns
Alternatively, you can use `columnVisibilityChange` event: https://mui.com/x/react-data-grid/events/
