### ISSUE TITLE
Tree data grid server side loading

### ISSUE THREAD

**Issue by shazebCeloxis** [mui/mui-x#5641]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently on the expansion of icon in tree data grid the entire data is getting loaded.

### Expected behavior 🤔

I want only the data which will be seen after expanding only that data to be loaded or if not possible not the entire data but only the data which is to be seen on the particular page to be loaded

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Could you provide a reproduction example, like a codesandbox such that we can investigate from how you manage data loading?

**Comment by shazebCeloxis** [comment]
i saw in your docs that there is children lazy loading in tree data grid section so in that i saw that that when the rows are expanded the entire data will get load again . So if i want not the entire data to be loaded but only the data which will be shown upon row expanding or the entire data of that particular page only to be loaded how will i achieve that

**Comment by alexfauquette** [comment]
Why do you think it's fetching all the rows at the same time?

This [doc example](https://mui.com/x/react-data-grid/tree-data/#children-lazy-loading) only load the children of the expended row. As you can see, when extending a row, there is a delay between opening it and seeing the content (time to fetch data)
And if you close/open data are immediately here because they get saved

Here is the example code with some comments

```jsx
const handleRowExpansionChange = async (node) => {
	// This is the row that is tggle (so we want to fetch its children)
      const row = apiRef.current.getRow(node.id);

      if (!node.childrenExpanded || !row || row.childrenFetched) {
		// Early return if we already fetched them in the past
        return;
      }

      apiRef.current.updateRows([
        {
          id: `placeholder-children-${node.id}`,
          hierarchy: [...row.hierarchy, ''],
        },
      ]);

		// Here we fetch only the children of the open row
      const childrenRows = await fakeDataFetcher(row.hierarchy);

		// We add the new fetched rows to the data grid
      apiRef.current.updateRows([
        ...childrenRows,
        { id: node.id, childrenFetched: true },
        { id: `placeholder-children-${node.id}`, _action: 'delete' },
      ]);

      if (childrenRows.length) {
        apiRef.current.setRowChildrenExpansion(node.id, true);
      }
    };
```

**Comment by shazebCeloxis** [comment]
Thanku my problem got sorted out.

**Comment by shazebCeloxis** [comment]
Can we achieve same thing in case of row grouping

**Comment by alexfauquette** [comment]
For now, row grouping is not made to be server side, and will be more complicated to hack than the tree data example
