### ISSUE TITLE
TimePicker (and DateTimePicker) with AMPM turned on - backspace leaves trailing "a" or "p"

### ISSUE THREAD

**Issue by mattdemichele-pearson** [mui/mui-x#5642]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

This is reproducible on the documentation page using latest version - https://mui.com/x/react-date-pickers/getting-started/#react-components

Enter any time in the TimePicker (or DateTimePicker). Then focus the TextField and hit backspace twice. You will see that an "a" or "p" depending on am or pm is left behind in front of the cursor. You need to move forward to manually delete it again.

![image](https://user-images.githubusercontent.com/73609677/181522872-5bf1cbbb-a644-4cef-b849-c4d5f3f6f624.png)

### Expected behavior 🤔

Backspace on the time should clear the AM/PM completely. This used to work

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Navigate to https://mui.com/x/react-date-pickers/getting-started/#react-components
2. Enter a time in the TimePicker (make sure AMPM is enabled. As of now, it is enabled on the example page)
3. Click on TextField, with cursor at the end of the value
4. Hit backspace twice, and you will see an "a" or "p" is left behind

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.
