### ISSUE TITLE
[TimePicker] Doesn't allow editing even on the official sandbox

### ISSUE THREAD

**Issue by brenozuko** [mui/mui-x#5643]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Whenever I try to edit the field on the Time Picker component, it simply doesn't allow if a value is previously passed through the component.

### Expected behavior 🤔

We should be able to update through the input field

### Steps to reproduce 🕹

Link to live example: https://mui.com/pt/x/react-date-pickers/time-picker/

Just try and editing through the official sandbox. 

### Context 🔦

Whenever you have a default value on the component, it doesn't work properly. Even on the live doc.

### Your environment 🌎

I have "@mui/x-date-pickers": "^5.0.0-beta.0",
And   "react": "^16.14.0",

**Comment by alexfauquette** [comment]
I do not manage to reproduce your issue, could you provide a recoding of your screen when editing?

[Screencast from 28. 07. 22 19:22:32.webm](https://user-images.githubusercontent.com/45398769/181599448-20edebc8-ffed-4ebc-8f59-6f58e3a1b11e.webm)

**Comment by brenozuko** [comment]
You see, I try repeatedly to edit the field and it simply doesn't work!
https://user-images.githubusercontent.com/65123413/181604927-ec5dc16c-a7c6-4eb2-a06b-04aef5a57bd3.mp4

**Comment by brenozuko** [comment]
This is my component usage:

```
                <LocalizationProvider dateAdapter={AdapterDateFns}>
                  <TimeDatePickerContainer disableButton={true}>
                    <TimePicker
                      label={t('offer-modal.final-hour')}
                      ampm={false}
                      inputFormat="HH:mm"
                      value={dateTime.ends_at_time}
                      onChange={(value) => handleChangeDateTime(ACTIONS.SET_ENDS_AT_TIME, value)}
                      renderInput={(params) => <TextField {...params} />}
                    />
                  </TimeDatePickerContainer>
                </LocalizationProvider>
```

**Comment by brenozuko** [comment]
The same goes for the DesktopTimePicker and MobileTimePicker edit fields.

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.
