### ISSUE TITLE
[data grid] Add event callback on density change

### ISSUE THREAD

**Issue by shazebCeloxis** [mui/mui-x#5647]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

i am unable to find event related to the density change in premium data grid.there is a onStatechange but it is called on every state change

### Expected behavior 🤔

so can i get an event related to density change in data grid

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
For which use case do you need an event for density? 

I agree for consistency, managing everything with events can be interesting. But the only native way to modify the density of the grid is the density select in the toolbar so the main behavior are:

- You want to customize grid content depending on the density. Thes `gridDensityValueSelector` can be used
- You want to move the density selector outside of the grid. Then you do not need the toolbar density selector

**Comment by destegabry** [comment]
@alexfauquette I would need a controlled density to let an user save its preference for all further visit on a DataGrid. 

Don't you think it would be useful as lot of DataGrid behavior is already controlled?

My MUI-X Premium order number is:  #44740

**Comment by alexfauquette** [comment]
> I would need a controlled density to let a user save its preference for all further visit on a DataGrid

Would it be better to export state density to be able to restore the default grid state with `initialState`?
https://mui.com/x/react-data-grid/state/#restore-the-state-with-initialstate

@cherniavskii

**Comment by destegabry** [comment]
Ok but how can I get density state change events?

**Comment by alexfauquette** [comment]
You mean how can you know you have to re-export the state? Hard question. Maybe the team working on the data grid will have more insights 🤔

**Comment by destegabry** [comment]
I would like to do something like this:

```jsx
function MyDatagrid(props) {
  const [userPreferences, saveUserPreferences] = useUserPreferences();

  return (
    <DataGridPremium
      density={userPreferences.gridDensity}
      onDensityChange={(gridDensity) => saveUserPreferences({ gridDensity })}
      {...props}
    />
  );
}
```

Like what I can already do with, for example,

**Comment by cherniavskii** [comment]
Hi @destegabry 
You can use this workaround to subscribe to the density change: https://codesandbox.io/s/strange-goldstine-jwcns6?file=/demo.tsx
We will consider adding controlled density support to the grid.

**Comment by destegabry** [comment]
Hi @cherniavskii,
thank you for the workaround, will you update this issue if it will be implemented?

**Comment by cherniavskii** [comment]
Yes, you will get a GitHub notification when the issue is closed

**Comment by jadzeino** [comment]
he is a simple work a round
create this simple Density component that looks and behave the same as the built in one
`const CustomDensityMenuButton = ({ setDensity }) => {
  const [anchorEl, setAnchorEl] = useState(null);

  const handleOpenMenu = (event) => {
    setAnchorEl(event.currentTarget);
  };

  const handleCloseMenu = () => {
    setAnchorEl(null);
  };

  const handleDensityChange = (newDensity) => {
    setDensity(newDensity);
  };

  // Map density options to their corresponding icons
  const densityIcons = {
    standard: <MenuIcon />,
    compact: <FilterListIcon />, // Use Material UI icons for Standard and Compact
    comfortable: <MoreVertIcon />,  // Use Material UI icons for Standard and Comfortable
  };

  return (
    <>
      <Tooltip title="Density">
        <IconButton onClick={handleOpenMenu}>
          {/* Use the corresponding icon based on selected density */}
          {densityIcons[density]}
          <Typography variant="button" sx={{ ml: 1 }}>
            Density
          </Typography>
        </IconButton>
      </Tooltip>
      <Menu
        anchorEl={anchorEl}
        open={Boolean(anchorEl)}
        onClose={handleCloseMenu}
      >
        <MenuItem onClick={() => handleDensityChange('standard')}>
          <ListItemIcon>{densityIcons.standard}</ListItemIcon>
          Standard
        </MenuItem>
        <MenuItem onClick={() => handleDensityChange('compact')}>
          <ListItemIcon>{densityIcons.compact}</ListItemIcon>
          Compact
        </MenuItem>
        <MenuItem onClick={() => handleDensityChange('comfortable')}>
          <ListItemIcon>{densityIcons.comfortable}</ListItemIcon>
          Comfortable
        </MenuItem>
      </Menu>
    </>
  );
};`

on your usages for the Datagrid create this state
`const [density, setDensity] = useState('standard');`
const densityMapper = ['compact':28  , 'standard':37 , 'comfortable':49]
and then replace the density button that u use in the toolbar  with the one u create
`<DataGrid
        // ... other props
        rowHeight={densityMapper[density]}
        toolbar={(<GridToolbarContainer><CustomDensityMenuButton setDensity={setDensity} /></GridToolbarContainer>) }
        />`
