### ISSUE TITLE
[dataigrd] Filter numbers in localized format

### ISSUE THREAD

**Issue by Mexanik2003** [mui/mui-x#5648]
### Order ID 💳

37162

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Now, if datagrid includes a numeric data, i can show it in localized format (i. e. 1,234,567.89), but when i using a filter with operator =, !=, >, < etc. i must use only 1234567.89 format
Is there a way of using localized formats in number filtering?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
I do not think it's possible. The fact you can not add a `,` seems to come from  the `type="number"`

Of course you can remove `type="number"` and add a valueParser, but not sure it's a good idea

**Comment by flaviendelangle** [comment]
Closing this one from lack of feedback
