### ISSUE TITLE
Export to CSV exports empty rows instead of content 

### ISSUE THREAD

**Issue by innellea** [mui/mui-x#5671]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When clicking on the export button, some rows are empty in the exported CSV file.

Here is a sample content of the DataGrid:
<img width="863" alt="gridcontent" src="https://user-images.githubusercontent.com/43180177/182037220-e626b354-5589-4b50-9bdd-1f593fd148bc.png">

Here is the exported CSV:
<img width="873" alt="csvresult" src="https://user-images.githubusercontent.com/43180177/182037259-acdb1cc5-3b9a-431d-a084-dd55f33ef39f.png">

As you can see, all rows are exported in columns 2-5, but under the first column, only three are exported. The rest is empty.

### Expected behavior 🤔

When clicking to export button in DataGrid, it should export all the rows found in the grid.

### Steps to reproduce 🕹

Link to live example: https://tineye-next.vercel.app/

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.10 Ubuntu Kinetic Kudu (development branch) 22.10 (Kinetic Kudu)
  Binaries:
    Node: 18.3.0 - ~/.nvm/versions/node/v18.3.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v18.3.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v18.3.0/bin/npm
  Browsers:
    Chrome v103.0.5060.134
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.90 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/material: ^5.9.1 => 5.9.1 
    @mui/private-theming:  5.9.1 
    @mui/styled-engine:  5.8.7 
    @mui/system:  5.9.1 
    @mui/types:  7.1.4 
    @mui/utils:  5.9.1 
    @mui/x-data-grid: ^5.14.0 => 5.14.0 
    @mui/x-data-grid-generator: ^5.14.0 => 5.14.0 
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0 
    @mui/x-data-grid-pro: ^5.14.0 => 5.14.0 
    @mui/x-license-pro:  5.14.0 
    @types/react: 18.0.14 => 18.0.14 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 4.7.4 => 4.7.4 

```
</details>

**Comment by cherniavskii** [comment]
Cannot reproduce it
<img width="1164" alt="Screenshot 2022-08-01 at 12 56 38" src="https://user-images.githubusercontent.com/13808724/182133542-23bec2a6-74f1-4fd7-b138-67d991693812.png">

Can you share a codesandbox demo to reproduce the issue? You can start with a demo from our docs https://mui.com/x/react-data-grid/export/#default-toolbar

**Comment by innellea** [comment]
sure, I can do it @cherniavskii, but it seems like it only occurs if I get the data from the database (only tried with firestore)

**Comment by innellea** [comment]
Thank you for your help, @cherniavskii.
The issue was on my side. For some reason, the URLs stored in firestore start with \n, and the data exported, but I could not see the value because of the control character.
