### ISSUE TITLE
Tabbing issue

### ISSUE THREAD

**Issue by VaibhavLande12** [mui/mui-x#5672]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when using the tabs in the value cells, it should be going down, however, when a value is typed and a tab is pressed the cursor is going back to the initially selected cell.

Please refer attached video

https://user-images.githubusercontent.com/87651391/182077041-7783689d-8141-4fa6-b0bd-689bf4a711be.mp4

### Expected behavior 🤔

 It should just proceed to go to the following cell at the bottom

### Steps to reproduce 🕹

Link to live example:

Steps:
1.Add x-data-grid to the react application.
2. Add textbox in render cell method
3. add Value in first row textbox and tab after that again add some value in second row textbox
4. with second row tab click it should go down instead again to first row textbox

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @VaibhavLande12 

> 2. Add textbox in render cell method

You are not supposed to render a textbox in `renderCell`. For editing you should use our Editing feature https://mui.com/x/react-data-grid/editing/.
For your use case you might find Controlled mode useful: https://mui.com/x/react-data-grid/editing/#controlled-mode

Feel free to open an issue if you encounter similar problem using Editing feature.
