### ISSUE TITLE
`process.env` is undefined

### ISSUE THREAD

**Issue by ar7casper** [mui/mui-x#5673]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently, under `envConstants.ts`, the following code is checking whether `GRID_EXPERIMENTAL_ENABLED` is present.

A check is done whether `process` is defined or not, and if it is, it assumes it has `env` property on it.
That's not always the case, it could be undefined which makes the code break.

### Expected behavior 🤔

It should be able to cope and acknowledge that `process.env` is not always defined.

### Context 🔦

I'm running `cypress` component testing via `vite` and it doesn't inject `env` to `process` as one would expect. 
In such a case, the app crashes and I'm not able to test my code.

**Comment by ar7casper** [comment]
I've created #5669

**Comment by cherniavskii** [comment]
@ar7casper While removing `process.env.GRID_EXPERIMENTAL_ENABLED` in https://github.com/mui/mui-x/pull/5669 would solve your original issue, there are multiple other places where we check `process.env`, like this one:
https://github.com/mui/mui-x/blob/689cbfcaf676fabac5f02fcad46982c6965b4291/packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts#L64-L67

So we might need to work on it a bit more.
I tried using vite in Stackblitz to reproduce the issue, but it works just fine with the latest version of data grid: https://stackblitz.com/edit/vitejs-vite-icjkyu

Can you point me to an example that exposes the issue with `process.env`?

**Comment by ar7casper** [comment]
@cherniavskii 

What you tried would work just fine.
My case is a bit different.

I'm using nx, where I have a UI lib. 
Then, I've added cypress component testing using vite.

What happens is, that for some reason, and here I'm assuming that I miss something on vite config, the process object is empty when the test is running.

I'm still investigating this issue, and why it happens, will report back once I get any conclusions.

Generally, if we change all -
```diff
- process.env.FOO
+ process?.env?.Foo
```

Then it will make MUI agnostic to who is using it and how.

**Comment by LukasTy** [comment]
Vite is a bit different from other environments as it doesn't expose `process.env`, but instead uses `import.meta.env`
@ar7casper Could you check whether defining `process.env` by [loading the env variables](https://github.com/vitejs/vite/issues/1930#issuecomment-783747858) via vite fixes your issue with `cypress`?

I'd reckon that if we wan't to explicitly depend on `process.env` in our code - we should mention it in documentation that the consuming environment has to provide it.
Because if we'd go with null-safe accessing of `process?.env?.NODE_ENV` then using the library would cause inconsistent behaviour based on the environment used.

**Comment by ar7casper** [comment]
@LukasTy 
Ye, I'm trying several variants of this solution, but nothing works, I'm confused af.

It seems like mui is not being built beforehand, my expectation is that it will build the packages and then load them in cypress browser. 
But I'm getting my problem on the browser, he can't find `process.env` in the runtime.
I'm probably missing something, would love some more ideas if you have them :)

**Comment by LukasTy** [comment]
@ar7casper Cypress is probably not exposing any env variables by itself as well.
Could you try [defining the variables](https://docs.cypress.io/api/cypress-api/env#Name-and-Value) manually to see if it helps?
```ts
// cypress.config.ts
import { defineConfig } from 'cypress';

export default defineConfig({
  env: {
    NODE_ENV: 'production',
  },
});
```

**Comment by ar7casper** [comment]
@LukasTy one of the first things I tried, didn't work

**Comment by LukasTy** [comment]
@ar7casper Have you looked into [this issue](https://github.com/nrwl/nx/issues/10392) and possible workaround with environment variable loading in nx/cypress workspace?

**Comment by cherniavskii** [comment]
>Generally, if we change all -
>```diff
>- process.env.FOO
>+ process?.env?.Foo
>```
>Then it will make MUI agnostic to who is using it and how.

I don't think it's necessary - after revisiting the topic I've noticed that all references to `process.env` left are referring to `process.env.NODE_ENV` specifically.
It should work with any bundler.
If it doesn't - "fixing" it in MUI X won't solve the problem for you, since [React uses `process.env.NODE_ENV` as well](https://unpkg.com/browse/react@18.2.0/index.js)

**Comment by ar7casper** [comment]
> 

Thing is, that it only fails with MUI-X.
If I remove it, everything works fine.

**Comment by ar7casper** [comment]
> > Generally, if we change all -
> > ```diff
> > - process.env.FOO
> > + process?.env?.Foo
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then it will make MUI agnostic to who is using it and how.
> 
> I don't think it's necessary - after revisiting the topic I've noticed that all references to `process.env` left are referring to `process.env.NODE_ENV` specifically. It should work with any bundler. If it doesn't - "fixing" it in MUI X won't solve the problem for you, since [React uses `process.env.NODE_ENV` as well](https://unpkg.com/browse/react@18.2.0/index.js)

@cherniavskii 
Thing is, that it only fails with MUI-X.
If I remove it, everything works fine.

**Comment by cherniavskii** [comment]
> Thing is, that it only fails with MUI-X.
> If I remove it, everything works fine.

Are you talking about `process.env.GRID_EXPERIMENTAL_ENABLED` or `process.env.NODE_ENV`?

**Comment by ar7casper** [comment]
GRID_EXPERIMENTAL_ENABLED

**Comment by cherniavskii** [comment]
Then we are good - https://github.com/mui/mui-x/pull/5669 is merged and will be included in the next release
