### ISSUE TITLE
[ClickAwayListener] - Enclosing GridToolbarContainer inside another button causes the ClickAwayListener to close the GridToolbarMenu

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#5677]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have put the GridToolbarContainer inside a button to make it another menu. 

![image](https://user-images.githubusercontent.com/24405994/182200354-43a019c1-1d2f-4fa8-97b6-babf16bbff35.png)

1. Click the gear icon button to open the GridToolbar menu.
2. Click on **columns** button.
3. Click something inside the columns menu
4. The ClickAwayListener forces the GridToolbar Menu to closed.

### Expected behavior 🤔

I have put the GridToolbarContainer inside a button to make it another menu. 

![image](https://user-images.githubusercontent.com/24405994/182200354-43a019c1-1d2f-4fa8-97b6-babf16bbff35.png)

1. Click the gear icon button to open the GridToolbar menu.
2. Click on **columns** button.
3. Click something inside the columns menu
4. The GridToolbar Menu **should not** close. It should only close if clicked outside the Column and GridToolbar Menu.

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Context 🔦

<GridPanelRoot>
  <GridPaperRoot>
  <ClickAwayListener onClickAway={}>
         <List sx={{ width: "100%" }} dense>
               <GridToolbarContainer ref={}>

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

33625

**Comment by cherniavskii** [comment]
Hey @simbahandiane 
Could you provide a minimal example reproducing the issue?
You can start with creating a Codesandbox demo from one of our demos in the docs: https://mui.com/x/react-data-grid/components/#toolbar
Thanks!

**Comment by cherniavskii** [comment]
Hey @simbahandiane 
`GridToolbarContainer` is not a generic component and does not support multiple levels of nesting.
Here's a simpler demo that uses `Menu` component from `@mui/material`: https://codesandbox.io/s/youthful-gagarin-727y1r?file=/demo.tsx
I don't think there's something on our side to fix.
