### ISSUE TITLE
[DateRangePicker] - onClose callback is stale when triggered via selection of second date. 

### ISSUE THREAD

**Issue by dwjohnston** [mui/mui-x#5680]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When selecting two dates using the DateRangePicker, default behaviour is that selecting that second date is considered 'complete' and on desktop will close the picker. 

Currently the onClose fires before the onChange, meaning that it will fire with stale data. 

### Expected behavior 🤔

In a basic usage of the date range picker, the onClose that is triggered by selection of the second item should fire following any onChange behaviour. 

### Steps to reproduce 🕹

https://codesandbox.io/s/basicdaterangepicker-demo-mui-x-forked-hy5wwo?file=/demo.tsx

Open the picker and select two dates. 
An alert will show. 
This alert shows `null` as the second argument. The onClose prop is aware of the updated callback. 

If you click the background again, the alert will fire again with the correct data. 

### Context 🔦

I only want to apply the changes of my date picker when they close it. 

### Your environment 🌎

See repro

**Comment by alexfauquette** [comment]
The `onChange` is called before the `onClose`. But your `setState` is applied in the next rendering loop, so the `onClose` is called with "outdated" data

What you are looking for is maybe the `onAccept` prop

https://codesandbox.io/s/basicdaterangepicker-demo-mui-x-forked-bkdyi5?file=/demo.tsx

The code responsible of this behavior is [here](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/hooks/usePickerState.ts#L216:L232)

**Comment by dwjohnston** [comment]
@alexfauquette  That looks right. Thanks. :)
