### ISSUE TITLE
[DataGridPro] Facing issue with setting cell CSS after adding new row record

### ISSUE THREAD

**Issue by shetamitesh** [mui/mui-x#5681]
### Order ID 💳

46861

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am trying to make a stock watchlist using DataGridPro and I am facing this issue.

https://user-images.githubusercontent.com/6822256/182344127-52391730-4c31-41db-b241-a4a14db58fcd.mp4

Watchlist is working properly with default state but as soon as new record is added, it just updates css of newly added row. However, it still able to update data of all rows.

In the similar issue, after row reordering, all rows stops applying css. See below video.

https://user-images.githubusercontent.com/6822256/182345734-e8fd5b21-98ad-48f2-b60c-8edec3bc106a.mp4

See below how I have given css classname to column. It is same as example in docs.
```javascript
        {
            field: 'buyqty', headerName: 'BuyQty', type: 'number', cellClassName: (params) => {
                if (!params.row.prevbuyqty || params.row.prevbuyqty === params.row.buyqty) {
                    return '';
                }
                return clsx('super-app', { negative: params.row.prevbuyqty < params.row.buyqty, positive: params.row.prevbuyqty >= params.row.buyqty })
            }, renderCell: (params) => (<>{params.value ? params.value : '0.00'}</>)
        }
```

Rows are updated using apiRef.

```javascript
apiRef.current.updateRows(records);
```

Let me know if you need any further information from me. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Firefox: 103.0
</details>

**Comment by cherniavskii** [comment]
Hey @shetamitesh 
Can you provide a minimal example reproducing the issue?
I've created this sandbox and cannot reproduce the issue: https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-g1rph5?file=/demo.tsx

I would also suggest to check the data source to make sure everything looks good on the data source layer.

Thanks!

**Comment by shetamitesh** [comment]
@cherniavskii 
Thanks for your fast reply. I really appreciate it.

I've just forked your sandbox and made the changes as I did in my original code.
https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-yhd9vk?file=/demo.tsx

In the sandbox everything is working as I need. I have made some changes in my original code using this sandbox example. I will update you tomorrow with results after testing it with live market data feed.

**Comment by shetamitesh** [comment]
This problem still exist with live data. Spent whole day to identify the problem but couldn't. 

Only difference between my code and sandbox is that I am connecting to socket for newly added symbol in useEffect. See below.

```javascript
React.useEffect(() => {
    if (wl.length > 0) {
      // connect to socket
      connect()
      const subscription = interval(100).subscribe(() => {
        updateRows();
      });

      return () => {
        subscription.unsubscribe();
      };
    }
  }, [wl]);
```

**Comment by shetamitesh** [comment]
@cherniavskii 

Thanks for your support. The problem has been resolved. 
It was problem with React strictMode, which was rendering the UI multiple times. Removing it solved my problem.
