### ISSUE TITLE
[StaticDatePicker] `DatePicker` includes `ClockPicker` in tree shaken built bundle

### ISSUE THREAD

**Issue by anderskiaer** [mui/mui-x#5687]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It would be nice if usage of `StaticDatePicker from '@mui/x-date-pickers/StaticDatePicker'` did not include (unused) clock picker code in built production bundle.

### Motivation 🔦

In our use case, we only use the date picker (no clock picker, and also no month/year picker). Analyzing built bundle, it appears that an unused `ClockPicker` component is included in the bundle. 

The simple downstream workaround/hack of commenting out `import { ClockPicker } from '../../../ClockPicker/ClockPicker';` in `[...]/internals/CalendarOrClockPicker/CalendarOrClockPicker.js` appears to not break the date picker usage and alone saves 12 KB of JavaScript in built bundle (see right snippet below compared to the left one):
![image](https://user-images.githubusercontent.com/9577823/182368755-53ab113d-b9ef-4094-b717-70a8ec5cbf4b.png)

I guess the reason `ClockPicker` is able to bypass tree shaking is the pattern used here: https://github.com/mui/mui-x/blob/bc263d50b42ed2a068024a6d773f0efc0ac8d808/packages/x-date-pickers/src/internals/components/CalendarOrClockPicker/CalendarOrClockPicker.tsx#L173-L200 conditionally includes `ClockPicker`, and as far as I can see `StaticDatePicker from '@mui/x-date-pickers/StaticDatePicker'` (which we know by definition not will include time/clock picker) still goes through `CalendarOrClockPicker` function, and then also `ClockPicker` is picked up (despite never being used by `StaticDatePicker`).

**Comment by flaviendelangle** [comment]
I think that's something we should be able to work on for the v6 major version.
It will require breaking the `CalendarOrClockPicker` abstraction.

**Comment by flaviendelangle** [comment]
The new pickers no longer bundled unused views
You can have a look at the [new documentation](https://next.mui.com/x/react-date-pickers/date-picker/)

Note that they are only available on v6 alpha releases.
