### ISSUE TITLE
[pickers] When changing value to null or "" the pickers don't clear their contents.

### ISSUE THREAD

**Issue by tobyzerapix** [mui/mui-x#5688]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Changing the value of a date or time picker to null or "" does nothing.  Whatever date was present in the field is still there.

### Expected behavior 🤔

Date or Time should be cleared from the box as if the 'clear' button had been clicked.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-forked-46c1li

Steps:
1. Create a controlled date picker and wire it up to use data from useState.
2. Create a button that resets the value of the picker to null or "".
3. Open the picker and choose a date.
4. Click the reset button

### Context 🔦

I need the component to be fully controllable.  I have a data structure that can either have a valid date, or no value at all.  If the date is there, it should display.  If it isn't the field should be blank.  I have ui that can remove the value using other parts of the UI and I need the changes reflected in this field.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.14.2 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.5.0 => 11.9.0
    @emotion/styled: ^11.3.0 => 11.8.1
    @mui/base:  5.0.0-alpha.76
    @mui/icons-material: ^5.0.4 => 5.6.1
    @mui/lab: ^5.0.0-alpha.71 => 5.0.0-alpha.77
    @mui/material: ^5.0.4 => 5.6.1
    @mui/private-theming:  5.6.1
    @mui/styled-engine:  5.6.1
    @mui/styles: ^5.0.1 => 5.6.1
    @mui/system:  5.6.1
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-data-grid:  5.8.0
    @mui/x-data-grid-pro: ^5.0.0-beta.7 => 5.8.0
    @mui/x-date-pickers: ^5.0.0-alpha.7 => 5.0.0-alpha.1
    @mui/x-license-pro:  5.7.0
    @types/react:  18.0.5
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```
</details>

**Comment by alexfauquette** [comment]
You're using an old version of the package
```jsx
import { DatePicker, MuiPickersUtilsProvider } from "@material-ui/pickers";
```
The current one is `@mui-x/date-pickers`

Could you update your codesandbox? We fixed a similar issue few month ago so your should be fixed to by using the last version of `@mui-x/date-pickers`

---

You have a migration guide [here](https://mui.com/x/react-date-pickers/migration-lab/) to migrate from `@mui/lab` to the new package, but I assume your version is older than the lab
