### ISSUE TITLE
[pickers] `LocalizationProvider` is missing in x-date-pickers-pro ^5.0.0-beta.3

### ISSUE THREAD

**Issue by SirAndrii** [mui/mui-x#5691]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

As described on [https://mui.com/x/api/date-pickers/localization-provider/#heading-import](https://mui.com/x/api/date-pickers/localization-provider/#heading-import) and [https://www.npmjs.com/package/@mui/x-date-pickers-pro](https://www.npmjs.com/package/@mui/x-date-pickers-pro)
LocalizationProvider can be imported from pro version, but it is missed in the folder tree [https://github.com/mui/mui-x/tree/master/packages/x-date-pickers-pro/src](https://github.com/mui/mui-x/tree/master/packages/x-date-pickers-pro/src)

![image](https://user-images.githubusercontent.com/24919819/182601710-6ab5758c-bc32-45fd-92f3-327ac59c313d.png)

### Expected behavior 🤔

LocalalizationProvider should be imported from @mui/x-date-pickers-pro version without installing @mui/x-date-pickers as described in documentation https://www.npmjs.com/package/@mui/x-date-pickers-pro. 

### Steps to reproduce 🕹

Link to live example:

Steps:
1. intstall only @mui/x-date-pickers-pro 
2. try to import {LocalizationProvider} from '@mui/x-date-pickers-pro';

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @SirAndrii 
What version of the package are you using?
Here's a working demo with the latest version of the package: https://codesandbox.io/s/staticdaterangepickerdemo-demo-mui-x-forked-neu0yi?file=/demo.tsx
