### ISSUE TITLE
(Safari) TimePicker > All hours showing focus on open

### ISSUE THREAD

**Issue by mogrady88** [mui/mui-x#5694]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently in your Date / Time pickers demos if you open a `TimePicker` in Safari every hour looks like its focused. I checked through any issues and didnt see it reported. This can be seen in your current demos (see below):

![FA0892FC-1C17-4830-BCE9-60D40DD42B1B](https://user-images.githubusercontent.com/35465181/182676139-915af19e-e664-4bfb-a1a1-86b7e3712215.png)

### Expected behavior 🤔

Expected behavior is that none of that focus should be there

### Steps to reproduce 🕹

Link to live example:

Open Safari and go to:

https://mui.com/x/react-date-pickers/getting-started/#main-content > React components demo > TimePicker

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
@LukasTy Can you reproduce this issue on safari?

**Comment by LukasTy** [comment]
Yes, I was able to reproduce it. But it is a strange one as it only happens when the url contains `#main-content`.
Also, it only happens for the first time after page load.

https://user-images.githubusercontent.com/4941090/182777479-dbfa0dd6-9a1d-4916-ae37-e6cb68b3ad82.mov

**Comment by alexfauquette** [comment]
Thanks for the recording 👍

**Comment by LukasTy** [comment]
@mogrady88 Could you confirm if [this fix](https://deploy-preview-5758--material-ui-x.netlify.app/x/react-date-pickers/getting-started/) solves your mentioned case?

**Comment by mogrady88** [comment]
Yes, it looks like that clears up the focus issue 👍
