### ISSUE TITLE
Getting  "Cannot read properties of undefined (reading 'keyboardDate')"

### ISSUE THREAD

**Issue by sameswar** [mui/mui-x#5696]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have created a component using Datepicker and using the same in my other application. When I try to render it getting  "Cannot read properties of undefined (reading 'keyboardDate')" error. 

<ThemeProvider theme={evergreen}>
      <LocalizationProvider dateAdapter={AdapterDateFns}>
        {margin === Margin.SuperDense && labelPosition !== LabelPosition.None && (
          <InputLabel
            id={rest.id && `${rest.id}-label`}
            htmlFor={rest.id}
            required={required}
            error={hasError || isExternalError}
            disabled={disabled}
            className={clsx(
              baseClasses.label,
              baseClasses.labelSuperDense,
              margin === Margin.SuperDense &&
                labelPosition === LabelPosition.Left
                ? baseClasses.leftLabel
                : baseClasses.topLabel,
            )}
          >
            {label}
          </InputLabel>
        )}
        <DatePicker
          onChange={handleChange}
          views={[PickerView.Year, PickerView.Month, PickerView.Day]}
          inputFormat={renderFormat()}
          disableMaskedInput
          PopperProps={{
            placement: 'bottom-start',
            sx: {
              '& .css-dhopo2': { minHeight: '230px' },
              '& .PrivatePickersYear-yearButton.Mui-selected': {
                color: evergreen.palette.text.white.highEmphasis,
                backgroundColor: evergreen.palette.primary.dark,
              },
              '& .PrivatePickersMonth-root.Mui-selected': {
                color: evergreen.palette.text.white.highEmphasis,
                backgroundColor: evergreen.palette.primary.dark,
              },
              '& .MuiButtonBase-root.Mui-selected': {
                color: evergreen.palette.text.white.highEmphasis,
                backgroundColor: evergreen.palette.primary.dark,
              },
              '& .MuiButtonBase-root.MuiPickersDay-today': {
                color: evergreen.palette.text.black.highEmphasis,
                backgroundColor: evergreen.palette.primary.light,
                border: 'transparent',
              },
              '& .MuiButtonBase-root.MuiPickersDay-today.Mui-selected': {
                color: evergreen.palette.text.white.highEmphasis,
                backgroundColor: evergreen.palette.primary.dark,
              },
            },
          }}
          renderInput={(params: any) => (
            <TextField
              id={rest.id}
              className={rest.className}
              onBlur={handleBlur}
              onKeyDownCapture={handleKeyChange}
              margin={density}
              required={required}
              helperText={errorMessage || helperText}
              sx={handleStyle}
              {...params}
              error={hasError || isExternalError}
              size={density === 'dense' ? 'small' : 'normal'}
            />
          )}
          {...datePickerProps}
        />
      </LocalizationProvider>
    </ThemeProvider>

Here is the stack trace:
react-dom.development.js:12056 Uncaught TypeError: Cannot read properties of undefined (reading 'keyboardDate')
    at getFormatAndMaskByViews (shared.js:25:1)
    at useDatePickerDefaultizedProps (shared.js:45:4)
    at DesktopDatePicker (DesktopDatePicker.js:26:46)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)

### Expected behavior 🤔
I should be able to use the customized datepicker that use base as @mui Datepicker.
_No response_

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
@sameswar Can you provide a minimal example reproducing the issue?
You can start from this [codesandbox](https://codesandbox.io/s/396gfn?file=/demo.tsx)

**Comment by sameswar** [comment]
Hi Alex, I am not sure how to provide my scenario in this Sandbox. But here is the think, I have this BasicDatePicker component that you defined in Sandbox bundled and used in another workspace by adding this as one of the depenedency., That is when, I got this error.

**Comment by alexfauquette** [comment]
It sounds like a problem with the localization provider. Is the imported DatePicker wrapped in a localization provider. what if the provider is exported from your package?

**Comment by sameswar** [comment]
I am using <LocalizationProvider dateAdapter={AdapterDateFns}> 
from 
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
import { DesktopDatePicker, LocalizationProvider } from '@mui/x-date-pickers';

**Comment by flaviendelangle** [comment]
We let this issue die, not cool :grimacing: 

Could you provide a working reproduction case using https://codesandbox.io/s/date-and-time-pickers-uj6btq ?
This should pretty straightforward to know if it's a problem in your imports.
