### ISSUE TITLE
[docs] Add a migration guide with codemod for v5 -> v6

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#5698]
# Summary 

Following what we did from [v4-v5](https://mui.com/x/react-data-grid/migration-v4/), we need to create a migration page for **v6** and feed it as we progress on the development.

This issue creates the initial page with the initial changes.

However, each PR introducing a breaking change in v6, should also:

1. In the PR’s description describe it. So we can then copy & paste the content into the changelog and the community understands what’s going on.
2. Update the migration guide with a new entry
3. Ideally add a codemod if possible, otherwise, skip it.

An example of what looks great: https://github.com/mui/material-ui/pull/26186.  

Following there's a list of changes done before the migration guide 

# Date pickers PRs
- 
# Data Grid PRs
-

**Comment by flaviendelangle** [comment]
Closing it, we have the [migration guide](https://next.mui.com/x/migration/migration-pickers-v5/) and a standalone issue for the codemods (#6997)
