### ISSUE TITLE
labelFunc prop in @mui/x-date-pickers

### ISSUE THREAD

**Issue by ErikaAhlstrom** [mui/mui-x#5703]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We are now using material UI (v5) and @mui/x-date-pickers. In the previous version of material UI (v4), there seemed to have been a way to have another text displayed in the textField of the date picker than the actual value with the help of the labelFunc prop. For example, one might want to print "Today 4 August" in the textField but still have the value being "2022-08-04". 

I can't seem to find a way to accomplish this without the labelFunc prop and am grateful for all the help I can get.

### Examples 🌈

Here's one example of how it worked in the previous version (v4). Sorry for the Swedish but I think you'll see the point.

<img width="1275" alt="Screenshot 2022-08-04 at 17 49 38" src="https://user-images.githubusercontent.com/70745151/182890999-63b3982d-5e26-4cc9-9ff1-bd9e720fea78.png">

### Motivation 🔦

This would be really great since it would let our users have a better experience using the datePicker and it would also make it easier for the developers in our team working with this component.

**Comment by alexfauquette** [comment]
Would the `rifmFormatter` prop be what you are looking for?

**Comment by ErikaAhlstrom** [comment]
Thank you so much!! The `rifmFormatter` prop seems to do the trick perfectly! 🙏

Much appreciated!

**Comment by alexfauquette** [comment]
@ErikaAhlstrom Could you share a code sample about how you use it?

**Comment by ErikaAhlstrom** [comment]
Yes, of course! We're using the `displayDateFormat ` function as `rifmFormatter`.

## How it works now

https://user-images.githubusercontent.com/70745151/183364707-32ca8406-a4dd-46e4-9017-8d40e1c55001.mov




## Code
### DatePicker.tsx

`
import React, { useState } from "react";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import svLocale from "date-fns/locale/sv";
import enLocale from "date-fns/locale/en-US";
import { isValid, getWeek, getDay, isToday, isTomorrow } from "date-fns";
import format from "date-fns-tz/format";
import { isMobileOnly } from "react-device-detect";
import { IconButton, InputAdornment, useMediaQuery } from "@mui/material";
import { PickersDay, PickersDayProps } from "@mui/x-date-pickers";
import { MuiTextFieldProps } from "@mui/x-date-pickers/internals/components/PureDateInput";
import { DatePickerSkeleton } from "./DatePickerSkeleton";
import MobileDatePicker from "./MobileDatePicker/MobileDatePicker";
import DesktopDatePicker from "./DesktopDatePicker/DesktopDatePicker";
import StaticDatePicker from "./StaticDatePicker/StaticDatePicker";
import StaticDatePickerSkeleton from "./StaticDatePicker/StaticDatePickerSkeleton";
import { rgba } from "../../styles/colors";
import TextField from "../TextField";
import Typography from "../Typography";
import {
  Calendar,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
} from "../Icon";
import {
  dateStringToLocalDate,
  dateToLocalISO8601DateString,
  getLocalizationDateUtil,
  getLocale,
} from "./LocalizationUtil";

export interface Translation {
  sv: {
    today: string;
    tomorrow: string;
    okText: string;
    cancelText: string;
    week: string;
    weekAbbreviation: string;
    calendarButtonAriaLabelPart1: string;
    calendarButtonAriaLabelPart2: string;
    selectedDatePrefix: string;
    changeToYearView: string;
    changeToCalendarView: string;
    leftArrowButtonAriaLabel: string;
    rightArrowButtonAriaLabel: string;
    minDateError: string;
    maxDateError: string;
    invalidDateError: string;
    dateFormatError: string;
  };
  en: {
    today: string;
    tomorrow: string;
    okText: string;
    cancelText: string;
    week: string;
    weekAbbreviation: string;
    calendarButtonAriaLabelPart1: string;
    calendarButtonAriaLabelPart2: string;
    selectedDatePrefix: string;
    changeToYearView: string;
    changeToCalendarView: string;
    leftArrowButtonAriaLabel: string;
    rightArrowButtonAriaLabel: string;
    minDateError: string;
    maxDateError: string;
    invalidDateError: string;
    dateFormatError: string;
  };
}
// A helper to create a deep partial version of another type
type DeepPartial<T> = {
  [P in keyof T]?: DeepPartial<T[P]>;
};

export interface DatePickerProps {
  /** ID for the input field inside the DatePicker, passed down through the renderInput. Make label and helperText accessible for screen readers. */
  id: string;
  /** Language used for localization and date formatting. */
  lang?: "sv" | "nb" | "en";
  /** Translation object used for screen reader texts. */
  customTranslation?: DeepPartial<Translation>;
  /** Visible label text. */
  label: string;
  /** Optional helper text. */
  helperText?: string;
  /** Earliest date to display in the format yyyy-MM-dd. */
  minDate?: string;
  /** Latest date to display in the format yyyy-MM-dd. */
  maxDate?: string;
  /** Callback to handle change of date. */
  onChange: (date?: string) => void;
  /** Date value of the datepicker, in yyyy-MM-dd format. */
  value?: string;
  /** If true, disables all date buttons after today's date LOCALLY. To make the disablbed dates follow swedish timezone make this false and pass today's date swedish time to maxDate instead. */
  disableFuture?: boolean;
  /** If true, disables all date buttons before today's date LOCALLY. To make the disablbed dates follow swedish timezone make this false and pass today's date swedish time to minDate instead. */
  disablePast?: boolean;
  /** If true, the inputfield will take up the parent elements full width. */
  fullWidth?: boolean;
  /** If true, the picker and text field are disabled. */
  disabled?: boolean;
  /** The inputformat we want to use for our date */
  inputFormat?: string;
  /** If true, the picker shown will be the StaticDatePicker */
  staticPicker?: boolean;
  /** Choose DatePicker variant, defaults to "automatic" */
  variant?: "static" | "automatic" | "mobile" | "desktop";
  /** Add this for testing. Clickable and requested subcomponents will get suffixed with "-[ComponentName]" */
  customAttribute?: { attribute: string; value: string | number };
  /** If loading is true the skeleton for DatePickers will be shown. */
  isLoading?: boolean;
  /** If the StaticDatePicker should draw focus immediately when rendered. Should be true when static datepicker is shown in popup or modal. If false, this prop will be set programmatically on first focus. */
  autoFocus?: boolean;
  /** Set this to true the picker should show the week numbers next to dates. */
  hasWeekNumbers?: boolean;
  /** Let's us display custom date format instead of value in the DatePicker TextField. Example: "2022-08-06" => "Tomorrow 6 August" */
  rifmFormatter?: (string: string) => string;
}

const localeMap = {
  en: enLocale,
  sv: svLocale,
};

const maskMap = {
  sv: "____-__-__",
  en: "____-__-__",
};

const defaultTranslations: Translation = {
  sv: {
    today: "Idag",
    tomorrow: "Imorgon",
    okText: "Klar",
    cancelText: "Avbryt",
    week: "Vecka",
    weekAbbreviation: "v",
    calendarButtonAriaLabelPart1: "Valt datum är ",
    calendarButtonAriaLabelPart2: "Klicka för att öppna kalendern ",
    selectedDatePrefix: "Valt datum. ",
    changeToYearView: "Kalendern visas, byt till årsvy",
    changeToCalendarView: "Årsvy visas, byt till kalendern",
    leftArrowButtonAriaLabel: "Föregående månad",
    rightArrowButtonAriaLabel: "Nästa månad",
    minDateError: "Fyll i ett datum efter",
    maxDateError: "Fyll i ett datum före",
    invalidDateError: "Kontrollera att datumet stämmer",
    dateFormatError: "Prova välja ett annat datum",
  },
  en: {
    today: "Today",
    tomorrow: "Tomorrow",
    okText: "OK",
    cancelText: "Cancel",
    week: "Week",
    weekAbbreviation: "wk",
    calendarButtonAriaLabelPart1: "The selected date is ",
    calendarButtonAriaLabelPart2: "Click to open the calendar ",
    selectedDatePrefix: "Selected date. ",
    changeToYearView: "Calendar is shown, switch to year view",
    changeToCalendarView: "Year view is shown, switch to calendar view",
    leftArrowButtonAriaLabel: "Previous month",
    rightArrowButtonAriaLabel: "Next month",
    minDateError: "Enter a date after",
    maxDateError: "Enter a date before",
    invalidDateError: "Check that the date is correct",
    dateFormatError: "Try picking another date",
  },
};

export const DatePicker = React.forwardRef<HTMLDivElement, DatePickerProps>(
  (
    {
      id,
      lang = "sv",
      customTranslation,
      label,
      helperText,
      minDate,
      maxDate,
      onChange,
      isLoading = false,
      value,
      fullWidth,
      disabled,
      variant = "automatic",
      hasWeekNumbers = false,
      customAttribute,
      autoFocus,
      disableFuture = false,
      disablePast = false,
    },
    ref
  ) => {
    const currentTranslation = {
      ...defaultTranslations[lang],
      ...(customTranslation !== undefined ? customTranslation[lang] : {}),
    };

    const [disableFormatter, setDisableFormatter] = useState(false);
    const [open, setOpen] = useState(false);
    const [error, setError] = useState(false);
    const [shouldAutoFocus, setShouldAutoFocus] = useState(false);
    const handleOpen = () => setOpen(true);
    const handleClose = () => setOpen(false);
    const [errorText, setErrorText] = useState<string | undefined>(undefined);

    const shouldReduceAnimations = useMediaQuery(
      "(prefers-reduced-motion: reduce)"
    );

    const customAttributeSuffixInput = "-Input";
    const customAttributeSuffixCalendarButton = "-CalendarButton";
    const customAttributeSuffixChevronButton = "-ChevronButton";

    const getViewSwitchingButtonText = (view: "year" | "month" | "day") => {
      return {
        year: currentTranslation.changeToCalendarView,
        month: "",
        day: currentTranslation.changeToYearView,
      }[view];
    };

    function generateCalendarButtonAriaLabel() {
      return value !== undefined
        ? `${currentTranslation.calendarButtonAriaLabelPart1} ${format(
            new Date(value),
            "EEEE d MMMM yyyy",
            {
              locale: getLocale(lang),
            }
          )}, ${currentTranslation.calendarButtonAriaLabelPart2}`
        : currentTranslation.calendarButtonAriaLabelPart2;
    }

    function renderDay(
      day: Date,
      _selectedDates: Array<unknown | null>,
      pickersDayProps: PickersDayProps<Date>
    ): JSX.Element {
      // Function to position week numbers correctly based on language.
      const checkLanguageAndDayIndex = (language: string) => {
        if (language === "sv") return 1;
        return 0;
      };

      function generateAriaLabel() {
        const isFirstDayInWeek = getDay(day) === checkLanguageAndDayIndex(lang);
        let labelText = "";
        if (isFirstDayInWeek)
          labelText += `${currentTranslation.week} ${getWeek(day)}, `;
        if (pickersDayProps.selected)
          labelText += currentTranslation.selectedDatePrefix;
        if (pickersDayProps.today) labelText += `${currentTranslation.today}, `;
        labelText += format(day, "EEEE d MMMM yyyy", {
          locale: getLocale(lang),
        });
        return labelText;
      }

      return (
        <>
          {hasWeekNumbers ? (
            <>
              {getDay(day) === checkLanguageAndDayIndex(lang) && (
                <div role="rowheader" aria-hidden>
                  <Typography
                    variant="caption"
                    aria-hidden
                    sx={{
                      fontSize: "14px",
                      color: rgba(105, 107, 87, 1),
                    }}
                  >
                    {currentTranslation.weekAbbreviation}
                    {getWeek(day)}
                  </Typography>
                </div>
              )}
            </>
          ) : undefined}
          <div role="cell">
            <PickersDay
              aria-hidden={pickersDayProps.disabled || undefined}
              aria-pressed={pickersDayProps.selected || undefined}
              aria-label={generateAriaLabel()}
              onFocus={() => {
                return variant === "static" && setShouldAutoFocus(true);
              }}
              {...pickersDayProps}
            />
          </div>
        </>
      );
    }

    const validateInput = (
      val: string,
      validationType: "onBlur" | "onChange"
    ) => {
      // Remove error messages when in the process of typing.
      if (validationType === "onChange" && val?.length < 10) {
        setErrorText(undefined);
        return setError(false);
      }
      // Skip validation if field is empty
      if (!val?.length) {
        setError(false);
        return setErrorText(undefined);
      }
      // Check if the date is valid
      if (!isValid(new Date(val)) || val?.length < 10) {
        setError(true);
        return setErrorText(currentTranslation.invalidDateError);
      }
      // Check if date is within bounds
      if (minDate && new Date(val) < new Date(minDate)) {
        setError(true);
        const minDateMinusOne = new Date(minDate);
        minDateMinusOne.setDate(minDateMinusOne.getDate() - 1);
        return setErrorText(
          `${currentTranslation.minDateError} ${dateToLocalISO8601DateString(
            minDateMinusOne
          )}`
        );
      }
      // Check if date is within bounds
      if (maxDate && new Date(val) > new Date(maxDate)) {
        const maxDatePlusOne = new Date(maxDate);
        maxDatePlusOne.setDate(maxDatePlusOne.getDate() + 1);
        setError(true);
        return setErrorText(
          `${currentTranslation.maxDateError} ${dateToLocalISO8601DateString(
            maxDatePlusOne
          )}`
        );
      }
      setError(false);
      return setErrorText(undefined);
    };

    function renderInput(params: MuiTextFieldProps): JSX.Element {
      return (
        <TextField
          {...(params as Record<string, unknown>)}
          label={label}
          /* eslint-disable-next-line react/jsx-no-duplicate-props */
          inputProps={{
            ...params.inputProps,
            onFocus: () => {
              setDisableFormatter(true);
            },
            onBlur: (event: React.FocusEvent<HTMLInputElement>) => {
              setDisableFormatter(false);
              // Call the passed-down onBlur event first
              if (params.inputProps && params.inputProps.onBlur) {
                const onBlur = params.inputProps?.onBlur;
                onBlur(event);
              }
              validateInput(event.target.value, "onBlur");
            },
          }}
          onChange={(event) => {
            validateInput(event.target.value, "onChange");
          }}
          /* eslint-disable-next-line react/jsx-no-duplicate-props */
          InputProps={{
            ...(customAttribute && {
              [customAttribute.attribute]: `${customAttribute.value}${customAttributeSuffixInput}`,
            }),
            sx: (theme) => ({
              // Remove hover effect to make click targets more clear
              ...theme.mixins.hover({
                backgroundColor: !isMobileOnly
                  ? "initial!important"
                  : undefined,
              }),
            }),
            startAdornment: (
              <InputAdornment position="start">
                <IconButton
                  {...(customAttribute && {
                    [customAttribute.attribute]: `${customAttribute.value}${customAttributeSuffixCalendarButton}`,
                  })}
                  onClick={handleOpen}
                  aria-label={generateCalendarButtonAriaLabel()}
                >
                  <Calendar />
                </IconButton>
              </InputAdornment>
            ),
            endAdornment: (
              <InputAdornment position="end">
                <IconButton
                  {...(customAttribute && {
                    [customAttribute.attribute]: `${customAttribute.value}${customAttributeSuffixChevronButton}`,
                  })}
                  onClick={handleOpen}
                  tabIndex={-1}
                  aria-hidden
                  component="div"
                >
                  {open ? <ChevronUp /> : <ChevronDown />}
                </IconButton>
              </InputAdornment>
            ),
          }}
          error={error}
          autoComplete="off"
          color="primary"
          id={id}
          helperText={helperText}
          fullWidth={fullWidth}
          errorHelperText={errorText}
          /* eslint-disable-next-line react/jsx-no-duplicate-props */
        />
      );
    }

    const displayDateFormat = (date: string) => {
      if (isValid(dateStringToLocalDate(value))) {
        if (isToday(dateStringToLocalDate(value))) {
          return `${currentTranslation.today}${
            lang === "en" ? "," : ""
          } ${format(dateStringToLocalDate(value), "d MMMM", {
            locale: getLocale(lang),
          })}`;
        }
        if (isTomorrow(dateStringToLocalDate(date))) {
          return `${currentTranslation.tomorrow}${
            lang === "en" ? "," : ""
          } ${format(dateStringToLocalDate(value), "d MMMM", {
            locale: getLocale(lang),
          })}`;
        }

        const weekdays = [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
          "Sunday",
        ];

        const dateLabel: string =
          lang === "en"
            ? `${weekdays[dateStringToLocalDate(value).getDay()]}, ${format(
                dateStringToLocalDate(value),
                "d MMMM",
                {
                  locale: getLocale(lang),
                }
              )}`
            : format(dateStringToLocalDate(value), "EEEE d MMMM", {
                locale: getLocale(lang),
              });

        return `${dateLabel.charAt(0).toUpperCase()}${dateLabel.slice(1)}`;
      }
      return "";
    };

    const sharedDatePickerProps = {
      mask: maskMap[lang],
      label,
      hasWeekNumbers,
      renderDay,
      value: dateStringToLocalDate(value),
      onChange: (date: Date | null): void => {
        onChange(dateToLocalISO8601DateString(date));
      },
      onAccept: () => {
        setError(false);
        setErrorText(undefined);
      },
      reduceAnimations: shouldReduceAnimations,
      components: {
        OpenPickerIcon: Calendar,
        RightArrowIcon: ChevronRight,
        LeftArrowIcon: ChevronLeft,
        SwitchViewIcon: ChevronDown,
      },
      leftArrowButtonText: currentTranslation.leftArrowButtonAriaLabel,
      rightArrowButtonText: currentTranslation.rightArrowButtonAriaLabel,
      minDate: dateStringToLocalDate(minDate),
      maxDate: dateStringToLocalDate(maxDate),
      disabled,
      open,
      onOpen: handleOpen,
      onClose: handleClose,
      inputFormat: "yyyy-MM-dd",
      renderInput,
      getViewSwitchingButtonText,
      currentTranslation,
      customAttribute,
      disablePast,
      disableFuture,
      rifmFormatter: disableFormatter ? undefined : displayDateFormat,
    };

    const renderDatePickerType = () => {
      if (variant === "mobile") {
        return isLoading ? (
          <DatePickerSkeleton />
        ) : (
          <MobileDatePicker {...sharedDatePickerProps} ref={ref} />
        );
      }
      if (variant === "static") {
        return isLoading ? (
          <StaticDatePickerSkeleton />
        ) : (
          <StaticDatePicker
            {...sharedDatePickerProps}
            autoFocus={autoFocus || shouldAutoFocus}
            ref={ref}
          />
        );
      }
      if (variant === "desktop") {
        return isLoading ? (
          <DatePickerSkeleton />
        ) : (
          <DesktopDatePicker {...sharedDatePickerProps} ref={ref} />
        );
      }
      // Render automatic variant
      if (isMobileOnly && isLoading) return <DatePickerSkeleton />;
      if (isMobileOnly) return <MobileDatePicker {...sharedDatePickerProps} />;
      return isLoading ? (
        <DatePickerSkeleton />
      ) : (
        <DesktopDatePicker {...sharedDatePickerProps} ref={ref} />
      );
    };

    return (
      <LocalizationProvider
        dateAdapter={getLocalizationDateUtil(lang)}
        locale={localeMap[lang]}
      >
        {renderDatePickerType()}
      </LocalizationProvider>
    );
  }
);

export default DatePicker;
`



### DesktopDatePicker

`
import React from "react";
import { DesktopDatePicker as MuiDesktopDatePicker } from "@mui/x-date-pickers";
import { DesktopDatePickerProps as MuiDesktopDatePickerProps } from "@mui/x-date-pickers/DesktopDatePicker";
import { useTheme } from "@mui/material";
import { DatePickerProps } from "../DatePicker";
import { SJSansBold, SJSans } from "../../../styles/themes/standardTheme";
import colors from "../../../styles/colors";

export interface DesktopDatePickerProps extends MuiDesktopDatePickerProps {
  /** Visible label text. */
  label: DatePickerProps["label"];
  /**
   * Add this for testing.
   * Clickable and requested subcomponents will get suffixed with "-[ComponentName]" */
  customAttribute?: { attribute: string; value: string | number };
  /** Set this to true the picker should show the week numbers next to dates. */
  hasWeekNumbers: DatePickerProps["hasWeekNumbers"];
  /** Let's us display custom date format instead of value in the DatePicker TextField. Example: "2022-08-06" => "Tomorrow 6 August" */
  rifmFormatter?: DatePickerProps["rifmFormatter"];
}

export const DesktopDatePicker = React.forwardRef<
  HTMLDivElement,
  DesktopDatePickerProps
>(
  (
    {
      label,
      onChange,
      renderInput,
      renderDay,
      value,
      customAttribute,
      hasWeekNumbers,
      rifmFormatter,
      ...other
    },
    ref
  ) => {
    const theme = useTheme();
    const DesktopPaperStyles = {
      marginTop: theme.spacing(1),
      boxShadow: "0px 2px 12px rgba(0, 0, 0, 0.1)",

      // Dialog container
      "&.MuiPaper-root > div > div": {
        width: hasWeekNumbers ? "395px" : "375px",
        overflow: "visible",
        minHeight: "416px",
        maxHeight: "416px",
        border: `solid ${colors.SJLightGranite} 1px`,
        borderRadius: "4px",
      },
      "& .MuiCalendarPicker-root": {
        width: hasWeekNumbers ? "395px" : "375px",
        minHeight: "416px",
        maxHeight: "416px",
        padding: theme.spacing(2),
        paddingBottom: theme.spacing(3),
        overflow: "visible",
      },

      // Calendar heading
      [`& .MuiCalendarPicker-root > div:first-of-type`]: {
        padding: "unset",
        margin: "unset",
        minHeight: theme.spacing(6),
        maxHeight: theme.spacing(6),
        height: theme.spacing(6),

        // Calendar heading date
        "&:first-of-type > div:first-of-type > div": {
          ...SJSansBold,
          fontSize: theme.typography.pxToRem(24),
          lineHeight: 32 / 24,
          textTransform: "capitalize",
        },

        // Calendar heading chevron
        ".MuiIconButton-root": {
          padding: 0,
          "&:first-of-type": {
            marginLeft: theme.spacing(1),
          },
        },

        // Empty div between chevron icons
        ".css-18puooo": {
          width: theme.spacing(3.5),
        },
      },

      // HANDLES MOST STYLING FOR WHEN WEEK NUMBERS ARE SHOWN
      // Grid Row with Date Numbers (1, 2, 3, 15, 16, 24, 31 etc)
      ".css-mvmu1r": {
        gridTemplateColumns: hasWeekNumbers ? "repeat(8, 1fr)" : undefined,
        gridColumnGap: hasWeekNumbers ? "1px" : undefined,
        justifyContent: "space-between",
        "& > div": {
          width: hasWeekNumbers ? "12.5%" : undefined,
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        },
      },
      // First div in the grid row with the week number
      ".css-mvmu1r > div:first-of-type": {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      },

      // Grid Row with Day Names (m, t, o, t, f, l, s)
      ".css-1n2mv2k": {
        justifyContent: "space-between",
        "&::before": {
          content: hasWeekNumbers ? "''" : undefined,
          display: hasWeekNumbers ? "block" : undefined,
          width: hasWeekNumbers ? "12.5%" : undefined,
          height: hasWeekNumbers ? "100%" : undefined,
        },
        "& > p": {
          width: hasWeekNumbers ? "12.5%" : undefined,
        },
      },

      // Calendar heading chevron
      "& .MuiIconButton-root": {
        margin: "0px",
        width: "24px",
        height: "24px",
        padding: "0px",
      },

      "& .MuiIconButton-root > svg": {
        margin: "0px",
        width: "100%",
        height: "100%",
      },

      // Calendar grid
      [`& .MuiCalendarPicker-root > div:last-of-type`]: {
        // Calendar grid weekday wrapper
        "div:first-of-type > div:first-of-type": {},
      },

      // Rows in calendar grid
      [`& .MuiCalendarPicker-root > div > div:last-of-type > div > div > div`]: {
        margin: "unset",
        marginTop: theme.spacing(1),
        // justifyContent: "space-between",
      },

      // Calendar days container
      [`& .PrivatePickersSlideTransition-root`]: {
        minHeight: "288px",
        overflow: "hidden",
      },

      // Day button
      [`.MuiPickersDay-root`]: {
        width: theme.spacing(5),
        height: theme.spacing(5),
      },

      // Style of years in calendar header
      "& .MuiYearPicker-root": {
        margin: "unset",

        "& .PrivatePickersYear-yearButton": {
          "&:not(.Mui-selected)": {
            ...SJSans,
            fontSize: theme.typography.pxToRem(16),
            lineHeight: 24 / 16,
          },
        },
      },

      "& .PrivatePickersYear-root": {
        marginTop: theme.spacing(2),

        "&:first-of-type": {
          "& .PrivatePickersYear-yearButton:not(.Mui-selected)": {
            outline: `1px solid ${colors.SJBlack}`,
          },
        },
      },

      "& .PrivatePickersYear-yearButton": {
        margin: "0 auto",
      },
    };
    return (
      <MuiDesktopDatePicker
        rifmFormatter={rifmFormatter}
        ref={ref}
        onChange={onChange}
        renderDay={renderDay}
        renderInput={renderInput}
        // Needed in newer mui alpha versions.
        // componentsProps={{
        //   actionBar: {
        //     actions: [],
        //   },
        // }}
        value={value}
        PaperProps={{
          role: "presentation",
          sx: DesktopPaperStyles,
        }}
        PopperProps={{
          ...(customAttribute && {
            [customAttribute.attribute]: `${customAttribute.value}`,
          }),
          "aria-label": label,
          sx: { marginRight: theme.spacing(2) },
        }}
        InputAdornmentProps={{
          sx: { marginLeft: theme.spacing(2) },
        }}
        {...other}
      />
    );
  }
);

export default DesktopDatePicker;


`

**Comment by alexfauquette** [comment]
Thanks, I made a simple codesandbox demo from your code. Hope it will help others 

https://codesandbox.io/s/basicdatepicker-demo-mui-x-forked-i48dsj?file=/demo.tsx
