### ISSUE TITLE
[question] Pass params to custom valueFormatter

### ISSUE THREAD

**Issue by Mattc1221** [mui/mui-x#5706]
### Order ID 💳

44112

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is there any way to pass a parameter to a custom value formatter?

I have a toggle in the column menu to switch between scientific and non-scientific mode for numbers. However, I would like to add another option to toggle between high and low precision while keeping scientific and non-scientific mode

For example lets say we have value 98765432.557243843. Currently I can click an option to toggle between the formats 98765432.557243843 and 9.87e+7. However If I have the format 98765432.557243843, I also want to be able to toggle between 98765432.56 and 98765432.557243843.

I think this can be done with setting up 4 different value formatters, but as I may want to add more format options in the future, I think adding a small bit of logic in the custom value formatter would be cleaner than writing a bunch of them

Here's a sandbox highlighting my issue:
https://codesandbox.io/s/late-silence-obbj9q?file=/src/GridColumnOptionsMenu.jsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
@Mattc1221 
Would factory for `valueFormatter` work in your use case?

```ts
const createVf1 = (digits) => (params) => {
  // TODO: Add toggle between showing 2 and 10 digits
  return Number(params.value).toExponential(2);
};

const createVf2 = (precision) => (params) => {
  // TODO: Add toggle between no precision and high precision
  return params.value;
}
```
