### ISSUE TITLE
How to set correctly visibility for selection column

### ISSUE THREAD

**Issue by michGreg** [mui/mui-x#5708]
### Order ID 💳

44899

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I use checkboxSelection prop to enable selection column as first column in datagrid. The issue is when i use it together with GridToolbar. I don't want disable the selection column but when i set ```__check__```column to { field: ```__check__```, hideable: false } then column design is broken and i have to set sortable, resizable, width, alignment...... and it is complicated to aling header chechkbox with row checkboxes. So is there any way how to set checkbox selection correctly together with GridToolbar and with hideable prop without column design changes?

https://codesandbox.io/s/visiblecolumnsbasicexample-material-demo-forked-rkn44k?file=/demo.js

```
import * as React from "react";
import { DataGrid, GridToolbar } from "@mui/x-data-grid";

const rows = [
  {
    id: 1,
    username: "@MUI",
    age: 38,
    desk: "D-546"
  },
  {
    id: 2,
    username: "@MUI-X",
    age: 25,
    desk: "D-042"
  }
];

export default function VisibleColumnsBasicExample() {
  return (
    <div style={{ height: 250, width: "100%" }}>
      <DataGrid
        columns={[
          {
            field: "__check__",
            hideable: false,
            resizable: false,
            sortable: false,
            width: 40,
            align: "left"
          },
          { field: "username", hideable: false },
          { field: "age" },
          { field: "desk" }
        ]}
        rows={rows}
        checkboxSelection
        components={{
          Toolbar: GridToolbar
        }}
      />
    </div>
  );
}
```
![image](https://user-images.githubusercontent.com/106229368/183012092-5e461cb3-2332-484b-9fd7-1af5debfc836.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by michGreg** [comment]
I used headerAlign: 'left' instead of align: 'left' and align is correct now. Could you add any info about ```__check__``` field to documentation?

**Comment by cherniavskii** [comment]
Hey @michGreg 
You can use `GRID_CHECKBOX_SELECTION_COL_DEF` to customize __check__ column like this:

```ts
columns={[
  {
    ...GRID_CHECKBOX_SELECTION_COL_DEF,
    hideable: false
  }
]}
```

Here's a working demo: https://codesandbox.io/s/visiblecolumnsbasicexample-material-demo-forked-be22wn?file=/demo.js

In our docs there's a section on checkbox column customization: https://mui.com/x/react-data-grid/selection/#custom-checkbox-column
