### ISSUE TITLE
[DataGridPro] Facing problem with Row reorder with fast updating data

### ISSUE THREAD

**Issue by shetamitesh** [mui/mui-x#5710]
### Order ID 💳

46861

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have made a sandbox to show my problem.
https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-yhd9vk?file=/demo.tsx

I am not able to reorder my rows because of fast updates(states are overwritten). 
In the example, I have set 100ms but in my actual code it is 10ms because of fast updating stock prices.

Please let me know if you need more information from my side.

I am facing one another problem too with Rows master detail. All master details are being rendered at the time of table render. Is it possible to fetch details from API when particular row is expanded and then based on API response?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
```
</details>

**Comment by cherniavskii** [comment]
Hey @shetamitesh 
It looks like you don't handle row reorder properly - I've commented out row updates, but still cannot reorder rows in your demo: https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-411l7s
You should fix this first to proceed.

> I am facing one another problem too with Rows master detail.

Please open a separate issue with a minimal reproduction example and steps to reproduce the issue.
Thanks!

**Comment by shetamitesh** [comment]
Sorry, I have fixed it now. Please check again.

**Comment by cherniavskii** [comment]
> Sorry, I have fixed it now. Please check again.

Could you double check? I don't see any change in behaviour

**Comment by shetamitesh** [comment]
Please check this link
https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-ch6nxg?file=/demo.tsx

I think there are multiple copies of code with same name.

**Comment by cherniavskii** [comment]
Thanks, it works now.
I've removed state update from `updateRows` function, since it's unnecessary: https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-x6ttz9?file=/demo.tsx
Row reorder seems to work fine (considering high-frequency updates):

https://user-images.githubusercontent.com/13808724/183076584-67f20c0b-6acc-4455-a16a-77d565153dc3.mov

Also, did you consider [throttling high-frequency updates](https://mui.com/x/react-data-grid/row-updates/#high-frequency)?
You can use `throttleRowsMs` prop: https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-3qjpky?file=/demo.tsx

**Comment by shetamitesh** [comment]
@cherniavskii 
Thanks, demo is working fine. However, still having same problem with my actual code.
See below video.

https://user-images.githubusercontent.com/6822256/183084076-7bd3b26b-d60b-44a2-bd12-b8128388756e.mp4

**Comment by cherniavskii** [comment]
@shetamitesh You'll have to make sure you are handling row reorder correctly, as in a working demo.
If you think there's an issue in Data Grid - feel free to open a new issue with a minimal reproduction example.

> Is it possible to get drag start event? Then I can stop updates temporary.

Yes, see https://mui.com/x/react-data-grid/row-ordering for `rowDragStart`
