### ISSUE TITLE
[data grid] Treeview drag & drop

### ISSUE THREAD

**Issue by jinow9595** [mui/mui-x#5737]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want the drag & drop function of treview.
Please check if there is a function provided.

### Order ID 💳 (optional)

39248

**Comment by flaviendelangle** [comment]
Hi,

Are you talking about the [Tree view component](https://mui.com/material-ui/react-tree-view/#main-content) or the [Tree data feature of the data grid](https://mui.com/x/react-data-grid/tree-data/#main-content) ?

In both case, we do not support drag & drop.

For the Tree view, I don't know the component but I guess it should be doable on your side if you need it right now
For the Tree data, you can have a look at https://github.com/mui/mui-x/issues/4821

**Comment by Ut1998** [comment]
Hi, 
Need this feature to implement row reordering in tree data grid, currently it is not supported.

**Comment by Ut1998** [comment]
> Hi,
> 
> Are you talking about the [Tree view component](https://mui.com/material-ui/react-tree-view/#main-content) or the [Tree data feature of the data grid](https://mui.com/x/react-data-grid/tree-data/#main-content) ?
> 
> In both case, we do not support drag & drop.
> 
> For the Tree view, I don't know the component but I guess it should be doable on your side if you need it right now For the Tree data, you can have a look at #4821

Hi @flaviendelangle, is this feature implemented in MUI data grid premium or not.
We need this feature on urgent basis.
Can you please suggest an alternate solution for this.

Thanks
