### ISSUE TITLE
[data grid] `GridBooleanCell` props are not passed to the icon

### ISSUE THREAD

**Issue by giladv** [mui/mui-x#5738]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

on GridBooleanCell, "other" props are not propagated anymore.
so wrapping it with Tooltip for instance doesn't work anymore.

### Expected behavior 🤔

triggers like Tooltip should work

### Context 🔦

```
<Tooltip title="hello">
  <GridBooleanCell {...params} />
</Tooltip>
```

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

On the version `5.15.1` the `other` are spread to the icon.
