### ISSUE TITLE
Style the Calendar/Clock icon for StaticDate/TimePicker

### ISSUE THREAD

**Issue by kingedward35** [mui/mui-x#5746]
I am currently trying to update the icons for the various MUI Pickers components with custom icons and was able to do this with the `DatePicker`, `TimePicker`, `DateTimePicker` and `StaticDateTImePicker` components. However when I try to update the same icons for the `StaticDatePicker` and `StaticTimePicker` components I am unable to do this. Does anyone know how to update the clock and calendar icons in the toolbar for these components? Thanks.

**Comment by LukasTy** [comment]
@kingedward35 
Could you please clarify which components are you referring to specifically?

**Comment by kingedward35** [comment]
I am referring to the calendar and clock icons that appear after you click on the pen icon.

**Comment by LukasTy** [comment]
I take it you are referring to these icons visible in the toolbar when manual input mode is toggled in the toolbar?
![Screenshot 2022-08-15 at 11 07 55](https://user-images.githubusercontent.com/4941090/184599628-127ba0fc-9547-40f4-ad76-34c11611cdcd.png)
![Screenshot 2022-08-15 at 11 08 19](https://user-images.githubusercontent.com/4941090/184599633-1bce3d5d-877b-4b42-a7fb-21d706c2b00a.png)
I don't see any option to override these in any of the picker components.
[Here is the code](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/components/PickersToolbar.tsx#L70) deciding which icon to render in these cases.
Could you show an example (codesandbox would be best - you can use any of our examples as a base) of how you are overriding these icons?

In any case, what do @alexfauquette @flaviendelangle think of this case? Should we add option to change these icons as well?

**Comment by kingedward35** [comment]
You are correct about the icons in the pictures above. We are currently overriding the icons in the non-static date pickers using the `OpenPickerIcon` , `timeIcon`, and `dateRangeIcon` props. It would be nice to be able to use a similar API to custom all of the icons in the various pickers. Thanks.

**Comment by nazarukroman** [comment]
@kingedward35 Could you please tell me how I can pass custom props to custom Icon `OpenPickerIcon` ?
My case:
I pass this props to use custom calendar icon
```   
       components={{
          OpenPickerIcon: CalendarIcon,
        }}
```

And I want to pass some props to CalendarIcon, but `componentsProps={{ OpenPickerIcon: { some: 'prop' } }}` or `OpenPickerButtonProps={{ some: 'prop' }}` doesn't work.

**Comment by flaviendelangle** [comment]
> And I want to pass some props to CalendarIcon, but componentsProps={{ OpenPickerIcon: { some: 'prop' } }} or OpenPickerButtonProps={{ some: 'prop' }} doesn't work.

You should be able to do `componentsProps={{ OpenPickerIcon: { some: 'prop' } }}` but has not been implemented yet
I will add them quickly because this inconsistency is problematic...

**Comment by LukasTy** [comment]
The original issue is no longer relevant because the toolbar no longer contains the input type switching icons starting v6.
The problem raised here: https://github.com/mui/mui-x/issues/5746#issuecomment-1219168221 is already solved as well.
