### ISSUE TITLE
Mui data grid footer table alignment  with the table header as it is marked as a 

### ISSUE THREAD

**Issue by sunilsr1986** [mui/mui-x#5749]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Mui data grid footer is not in alignment with the table header without the use of aggregation.

### Examples 🌈

Mui data grid footer is not in alignment with the table header without the use of aggregation function. Could you please suggest is there a way to do this , not finding anything on the doc.

https://codesandbox.io/s/customfooter-demo-mui-x-forked-1upfmt?file=/demo.js:1386-1413
![image](https://user-images.githubusercontent.com/39674643/183924439-3ce2a938-144a-4e42-873a-9669e4b74788.png)

**Comment by DanailH** [comment]
Hi, @sunilsr1986 it looks like want to aggregate the column values, why not use the aggregation feature we have recently released - https://mui.com/x/react-data-grid/aggregation/#main-content?
Another way is to have a custom row with your and then pin it to the bottom - https://mui.com/x/react-data-grid/row-pinning/#main-content.
The footer is independent of the columns so there isn't a way to align the items correctly.

**Comment by sunilsr1986** [comment]
Thanks for letting me know..

**Comment by sunilsr1986** [comment]
Could you please let me know a way that I could refer column header / cell properties in the footer ?

**Comment by sunilsr1986** [comment]
I figured this out with the gridColumnDefinitionsSelector in the footer and that had access to computed width. Thanks
