### ISSUE TITLE
[DataGrid] Keyboard navigation doesn't respect last not spanned column

### ISSUE THREAD

**Issue by shelimov** [mui/mui-x#5751]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am not sure if its by design, but here is the problem:
When the table has columns that colSpan by certain criteria, whenever I try to focus not spanned columns, DataGrid focuses the cell that had colSpan and not the one, that was focused, before entering the spanned one. (I know, it's easier to show.)

https://user-images.githubusercontent.com/4550843/183944209-03e2ab7c-7567-48af-88f6-cc20f6d1bc36.mov

### Expected behavior 🤔

I wanted to find where it works as I expect, but unfortunately, ag-grid has the same issue. :(
Google Sheets behaves the way I expect it to.

https://user-images.githubusercontent.com/4550843/183946195-b3d8ea69-b5a4-4c0d-86be-541d67fbc423.mov

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/datagridprodemo-demo-mui-x-forked-8fx35l?file=/demo.ts

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @shelimov 
Thanks for opening as issue.
This is indeed by design and this behavior is expected.
