### ISSUE TITLE
[RFC] Should we keep the different between `TInputDate` and `TDate` in v6

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#5759]
## Context

Currently, all the picker components have two different formats:

- `TDate`: the date representation of the adapter (`Date` for `date-fns`, `DayJs` for `dayjs`, etc...)

- `TInputDate`: the date format that the parsing method of the adapter can understand (usually it is something like `string | null | Date | TDate`)

Depending on what prop you are looking at, you might pass / receive one or the other.

Here are a few example:

- `props.value` takes a `TInputDate`
- `props.minDate` takes a `TDate`
- `props.onChange` receives a `TDate`
- `props.getOpenDialogAriaText` receives a `TInputDate` (no idea why)
- `props.isDateDisabled` receives a `TDate`
- etc...

`TDate` and `TInputDate` exact format depends on the adapter being used, which is why I am using the generic name and not an actual interface name.

## Why do we have this behavior

The clear benefit of this behavior is that developers don't have to parse there date before passing it to the pickers.
For instance, when using `dayjs`, any of the following is valid:

```tsx
<DatePicker value={dayjs()} />
<DatePicker value={new Date()} />
<DatePicker value="2022-08-11T09:49:30.347Z" />
```

### It is hard to understand when to use one format or the other

Some people passes a `string` in `props.value` so they think they must convert the date received in `onChange` to a `string` (#4976)

Some people passes a `Date` in `props.minDate` / `props.maxDate`, thinking it works just like `props.value` (#4474)

### It does not follow the classic controlled input format

Usually, when we have a controlled input, it has the following format:

```ts
interface MyComponentProps {
  value: A,
  onChange: (newValue: A) => void, // Or some event containing the value in the `A` format`
}
```

Right now we basically have:

```ts
interface MyComponentProps {
  value: A,
  onChange: (newValue: B) => void,
}
```

### Benchmark

Alternatives are not doing it:

- [Spectrum](https://react-spectrum.adobe.com/react-spectrum/DateField.html#value): both `value` and `onChange` uses a custom `CalendarDate` format (equivalent to our `TDate` with an adapter for there `@internationalized/date` package) 

- [Telerik](https://www.telerik.com/kendo-react-ui/components/dateinputs/api/DatePickerChangeEvent/): both `value` and `onChange` uses `Date` (equivalent to our `TDate` for the `date-fns` adapter)

- [Retool](https://retool.com/components/date): `value` uses `Date`, I did not find information about the format used by `onChange`

**Comment by LukasTy** [comment]
This does make total sense to me. 👍 
Having less burden on our side managing dates is better for code stability and clarity.
As mentioned in the RFC - developers already had issues understanding the correct types needed for various props.

**Comment by flaviendelangle** [comment]
@alexfauquette @joserodolfofreitas if we can close this discussion soon that would be perfect.
I am building the new picker without `TInputDate` for now.

**Comment by alexfauquette** [comment]
+1 for removing the `TInputDate` The less type with have the less confusing it is for developers and us

**Comment by joserodolfofreitas** [comment]
Yeah, it makes sense to drop TInputDate. 💯
