### ISSUE TITLE
[DateTimePicker] onChange doesn't fire reliably on time selection

### ISSUE THREAD

**Issue by TheRealCuran** [mui/mui-x#5762]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I noticed, that the `onChange` of the `DateTimePicker` doesn't seem to fire reliably for the time component. Basic reproducer code: https://codesandbox.io/s/green-cloud-p62c3k?file=/src/App.tsx (most common error case I am seeing is with just changing the time, but again: doesn't happen always, which makes this annoying to debug; I can reproduce it more reliably with my "big" application, the reproducer code seems sadly more stable)

### Expected behavior 🤔

Once the full date and time is entered, the `onChange` event must be fired/the callback invoked.

### Steps to reproduce 🕹

Since it is a bit flaky: run https://codesandbox.io/s/green-cloud-p62c3k?file=/src/App.tsx often enough. In a bigger local application I see this more often.

### Context 🔦

I have several date fields on a page. One is a global setting the other individual for the shown items. When the global date is changed, the dates of the items should be updated (at least when certain conditions are met, but those are checked inside the `onChange` handler).

### Your environment 🌎

- Latest `@mui/*` packages (in fact all packages are on their latest version, we run Renovate to keep the packages recent)
- Latest TypeScript
- Browsers tested: Firefox and Chromium (both in their latest versions)
- `tsconfig.json`:
    ```json
    {
      "compilerOptions": {
        "outDir": "./dist/",
        "noImplicitAny": true,
        "module": "ES2020",
        "target": "ES2020",
        "lib": ["ES2020", "DOM", "DOM.Iterable", "WebWorker"],
        "jsx": "react",
        "allowJs": true,
        "strict": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "alwaysStrict": true,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "noImplicitThis": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "importHelpers": true
      },
      "include": [
        "src/**/*"
      ],
      "compileOnSave": false
    }
    ```

### Order ID 💳 (optional)

47016

**Comment by LukasTy** [comment]
Hello @TheRealCuran 
Thank you for creating a detailed issue, but as you mentioned, it's hard to understand when (doing what exactly) does the issue actually happen.
Could you maybe provide a step by step instruction on how to reproduce the mentioned issue?
Or maybe provide a video of issue happening?

**Comment by TheRealCuran** [comment]
Here you go: [muix_no_onchange.webm](https://user-images.githubusercontent.com/3419202/184303467-0dff1df2-93fa-4e4b-9467-6ad346785d2e.webm), I would expect the `onChange` at the end of the complete selection. Nothing happening there though. Also happens if you change the time, but less often then.

**Comment by LukasTy** [comment]
Ahh, I see your issue.
The conundrum is that you expect the `onChange` to be fired when the same date is selected.
Because you are not selecting a different time, the change was already fired when you have changed the date.
When you confirmed time selection - the actual `Date` did not change and in such cases we do not fire a change event.
Is it still a problem for you case?
Or did clearing things up resolve you issue?

**Comment by TheRealCuran** [comment]
I could have sworn I had this on picking different times too, but fail to reproduce that at the moment. Which would make this issue a duplicate of #4473 

I am closing for now and see how I can work around this.

**Comment by JonathanMiner1** [comment]
https://codesandbox.io/p/sandbox/datetimefield-no-onchange-38ktkh

It seems like when changing between two times that are year 0099 or less, onChange will not fire.

**Comment by LukasTy** [comment]
@JonathanMiner1 as seen from [this example](https://codesandbox.io/p/sandbox/datetimefield-no-onchange-forked-r7jyxm?file=%2Fsrc%2FApp.tsx%3A19%2C37) behavior with such dates (years) is adapter dependent.
With `date-fns` such modifications work fine, whereas `dayjs` struggles. 🙈
