### ISSUE TITLE
[question] Mixing and sorting grouped and ungrouped DataGrid rows -- advice?

### ISSUE THREAD

**Issue by subvertallchris** [mui/mui-x#5763]
### Order ID 💳

Not available

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Before I start, I should clarify: I'm a Pro user but plan on upgrading to Premium once I've proven that I can build out the feature that I need! I don't have the order ID cause I didn't make the purchase, it was handled by our accounting department.  I hope this is in the spirit of the form! 🤞

----

I've got a DataGrid instance where I need to group some rows but not others. The rows, both grouped and ungrouped, need to sorted based on the date of either the ungrouped row or the first record of the group. So for instance, we'd have something like...

```
Row 1 - 08/11/2022
Row 2 - 08/10/2022
Row 3 - GROUPED
    Row 3a - 08/09/2022
    Row 3b - 08/07/2022
Row 4 - 08/09/2022
Row 5 - GROUPED
    Row 5a - 08/08/2022
    Row 5b - 08/07/2022
    Row 5c - 08/06/2022
Row 6 - 08/07/2022
```

I hacked in a blend of grouped/ungrouped rows by having the `groupingValueGetter` return null when records shouldn't be grouped and then using `groupingColDef` with `leafField` to pull the ungrouped records to the left so everything stays aligned. But I'm struggling with the sorting. Instead of what's described above, I've got this:

```
Row 1 - 08/11/2022
Row 2 - 08/10/2022
Row 3 - 08/09/2022
Row 5 - 08/07/2022
Row 6 - GROUPED
    Row 6a - 08/09/2022
    Row 6b - 08/07/2022
Row 7 - GROUPED
    Row 7a - 08/08/2022
    Row 7b - 08/07/2022
    Row 7c - 08/06/2022
```

This is a problem because it doesn't put rows in the order that they've come to expect from the interface we're replacing.

I seem to have solved it by using a very complicated `sortComparator` on the sorting column. It looks like this:

```typescript
  sortComparator: (date1, date2, grouped1, grouped2) => {
    // A missing date tells us that we're comparing a grouped row
    if (!date1 || !date2) {
      // We use the api to find a complete row using the first child of the grouped row. `api` is marked deprecated but we can't use the hook in this context.
      const api = grouped1.api as GridApiPremium;
      const comparableDate1 =
        date1 ||
        (grouped1.rowNode.children
          ? api.getRow<OrderTableRow>(grouped1.rowNode.children[0])?.date
          : undefined);
      const comparableDate2 =
        date2 ||
        (grouped2.rowNode.children
          ? api.getRow<OrderTableRow>(grouped2.rowNode.children[0])?.date
          : undefined);

      // At this point, we should have two reliable dates so we can compare as normal
      if (!comparableDate1 || !comparableDate2) {
        return 0;
      }

      if (comparableDate1 === comparableDate2) {
        return 0;
      }

      return comparableDate1 > comparableDate2 ? -1 : 1;
    }

    if (date1 === date2) {
      return 0;
    }

    return date1 > date2 ? -1 : 1;
  },
```

This appears to solve it but it seems extremely complicated and more than a little brittle. I also don't like that I have to rely on the deprecated `api` field, we're setting us up for pain. Is there a better approach here?

Really appreciate your help here!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @subvertallchris thanks for raising this!
You have a very specific case. I think doing a custom sort compartior is the way to go as you need only the first row in a group to be taken into account when sorting. You said you are already using the `groupingValueGetter` right, if you set it to return the date of the first row in the group this might work. I'm not that familiar with the row grouping yet but if @flaviendelangle can give a hand that would be great.

**Comment by flaviendelangle** [comment]
> I hacked in a blend of grouped/ungrouped rows by having the groupingValueGetter return null when records shouldn't be grouped

That's indeed how you are supposed to say that a row is not grouped :+1: 

> and then using groupingColDef with leafField to pull the ungrouped records to the left so everything stays aligned

Same, that feels coherent to me

>  I also don't like that I have to rely on the deprecated api field

You can use `useGridApiRef` to get the api

Something like:

```tsx
const apiRef = useGridApiRef();
const columns = useCustomHookToGenerateMyColumns(apiRef);

return <DataGridPremium {...otherProps} apiRef={apiRef} />
```

Other than that, your sorting comparator seems coherent to me.

Our current built in behavior for the sorting of groups vs leaves is not very flexible
I don't see how we could improve it to be honest

**Comment by subvertallchris** [comment]
@flaviendelangle, what's the right way to make sure that `apiRef.current` exists? I don't think the type for `useGridApiRefPremium` is quite right. It comes up with `MutableRefObject<GridApiPremium>` but it's more like `<MutableRefObject<GridApiPremium | object>`, which is leading to errors dynamically building columns. 

I've seen this come up before, like [here](https://github.com/mui/mui-x/issues/2904). `useEffect` naturally doesn't see changes to the ref because _ref_. I think I hacked it in by using a `useMemo` keyed to our loading state. Is there something more precise? Maybe a callback `onGridApiReady`?

**Comment by flaviendelangle** [comment]
>  don't think the type for useGridApiRefPremium is quite right

Stricly speaking yes, the `apiRef` can be undefined.
It is populated during the 1st render of the grid.
It should be ready in any `useEffect`, `useLayoutEffect` or event listener.

If you have a concrete example where the apiRef is not ready, feel free to put it here and I'll have a look.
