### ISSUE TITLE
[docs] Apply style guide and consistent formatting to all X docs

### ISSUE THREAD

**Issue by samuelsycamore** [mui/mui-x#5764]
## The problem

The MUI X documentation contains inconsistent formatting and grammar, and only spotty application of the company [Style guide](https://mui-org.notion.site/Style-guide-2a957a4168a54d47b14bae026d06a24b). I'd like to begin the process of editing and revising all pages, and establishing some templates for creating new pages and sections as we've done with the [MUI Base](https://mui.com/base/getting-started/overview/) and [Joy UI](https://mui.com/joy-ui/getting-started/overview/) docs.

## Scope

The primary goal is _consistency_. I'm less concerned with adding new content except where I find gaps that need to be covered.

I intend to review each page individually. Most pages will get their own PR, but some may be grouped together if the edits are minimal. I'll edit as needed for grammar, style, page formatting, content clarity, and completeness. I'm sure I'll have clarifying questions along the way that I'll need help addressing.

After the first round of revisions, I'll split the pages up into groups and do a second pass to ensure consistency across the docs.

I will exclude the Introduction section which was created recently, and the API Reference sections which are a different kind of page and I think should be reviewed separately.

We also need to work on the navigation menu. We have #5565 to get the ball rolling on the date and time pickers.

This is a BIG project, so I expect it to be ongoing for quite some time. This issue is where we can keep track of the progress.

### Data Grid
- [ ] [Overview](https://mui.com/x/react-data-grid/)
- [ ] [Demo](https://mui.com/x/react-data-grid/demo/)
- [ ] [Getting started](https://mui.com/x/react-data-grid/getting-started/)
- [ ] [Migration from v4](https://mui.com/x/react-data-grid/migration-v4/)
- [ ] [Layout](https://mui.com/x/react-data-grid/layout/)
- [ ] Columns
  - [ ] [Column definition](https://mui.com/x/react-data-grid/column-definition/)
  - [ ] [Column dimensions](https://mui.com/x/react-data-grid/column-dimensions/)
  - [ ] [Column visibility](https://mui.com/x/react-data-grid/column-visibility/)
  - [ ] [Column header](https://mui.com/x/react-data-grid/column-header/)
  - [ ] [Column ordering](https://mui.com/x/react-data-grid/column-ordering/)
  - [ ] [Column pinning](https://mui.com/x/react-data-grid/column-pinning/)
  - [ ] [Column spanning](https://mui.com/x/react-data-grid/column-spanning/)
  - [ ] [Column groups](https://mui.com/x/react-data-grid/column-groups/)
- [ ] Rows
  - [ ] [Row definition](https://mui.com/x/react-data-grid/row-definition/)
  - [ ] [Row updates](https://mui.com/x/react-data-grid/row-updates/)
  - [ ] [Row height](https://mui.com/x/react-data-grid/row-height/)
  - [ ] [Master detail](https://mui.com/x/react-data-grid/master-detail/)
  - [ ] [Row ordering](https://mui.com/x/react-data-grid/row-ordering/)
  - [ ] [Row pinning](https://mui.com/x/react-data-grid/row-pinning/)
  - [ ] [Row spanning](https://mui.com/x/react-data-grid/row-spanning/)
- [ ] [Editing](https://mui.com/x/react-data-grid/editing/)
- [ ] [Sorting](https://mui.com/x/react-data-grid/sorting/)
- [ ] [Filtering](https://mui.com/x/react-data-grid/filtering/)
- [ ] [Pagination](https://mui.com/x/react-data-grid/pagination/)
- [ ] [Selection](https://mui.com/x/react-data-grid/selection/)
- [ ] [Export](https://mui.com/x/react-data-grid/export/)
- [ ] [Components](https://mui.com/x/react-data-grid/components/)
- [ ] [Style](https://mui.com/x/react-data-grid/style/)
- [ ] [Localization](https://mui.com/x/react-data-grid/localization/)
- [ ] [Scrolling](https://mui.com/x/react-data-grid/scrolling/)
- [ ] [Virtualization](https://mui.com/x/react-data-grid/virtualization/)
- [x] [Accessibility](https://mui.com/x/react-data-grid/accessibility/) - #5780 
- [ ] Group & Pivot
  - [ ] [Row grouping](https://mui.com/x/react-data-grid/row-grouping/)
  - [ ] [Tree data](https://mui.com/x/react-data-grid/tree-data/)
  - [x] [Aggregation](https://mui.com/x/react-data-grid/aggregation/) - #5781 
  - [ ] [Pivoting](https://mui.com/x/react-data-grid/pivoting/)
- [x] Advanced - #6331
  - [API object](https://mui.com/x/react-data-grid/api-object/)
  - [Events](https://mui.com/x/react-data-grid/events/)
  - [State](https://mui.com/x/react-data-grid/state/)
- [ ] [API Reference](https://mui.com/x/api/data-grid/)

### Date and Time Pickers
- [ ] [Getting started](https://mui.com/x/react-date-pickers/getting-started/)
- [ ] [Migration from the lab](https://mui.com/x/react-date-pickers/migration-lab/)
- [ ] [Date picker](https://mui.com/x/react-date-pickers/date-picker/)
- [ ] [Date range picker](https://mui.com/x/react-date-pickers/date-range-picker/)
- [ ] [Date time picker](https://mui.com/x/react-date-pickers/date-time-picker/)
- [ ] [Time picker](https://mui.com/x/react-date-pickers/time-picker/)
- [ ] [Localization](https://mui.com/x/react-date-pickers/localization/)
- [ ] [Custom components](https://mui.com/x/react-date-pickers/custom-components/)
- [ ] [Date time range picker](https://mui.com/x/react-date-pickers/date-time-range-picker/)
- [ ] [Time range picker](https://mui.com/x/react-date-pickers/time-range-picker/)

**Comment by samuelsycamore** [comment]
We still have not come to a consensus about the capitalization of "data grid" and "date and time pickers." I think it's very awkward (at least in US English) to apply sentence case to these names, as we often seem to do. I would much prefer to always treat them as proper nouns: Data Grid, Date and Time Pickers. The (rare) exception would be when referring to the general concept of one of these components.

**Comment by oliviertassinari** [comment]
> We still have not come to a consensus about the capitalization of "data grid" and "date and time pickers."

Discussed a bit in https://github.com/mui/mui-x/pull/5754#discussion_r953014989.

**Comment by samuelsycamore** [comment]
This umbrella issue is now very outdated, but https://github.com/mui/mui-x/pull/9673 is a part of the ongoing effort here.

**Comment by richbustos** [comment]
Awesome! For companies I've been in where we didn't have a Voice and Tone team, I typically use this for reference:

https://developers.google.com/style/

It's awesome we are thinking this ahead of time!

**Comment by samuelsycamore** [comment]
> Awesome! For companies I've been in where we didn't have a Voice and Tone team, I typically use this for reference:
> 
> https://developers.google.com/style/
> 
> It's awesome we are thinking this ahead of time!

@richbustos [This is MUI's company style guide](https://mui-org.notion.site/Writing-style-guide-2a957a4168a54d47b14bae026d06a24b) that I assembled based primarily on the Google docs guide (so at least some of it should look familiar) combined with Mailchimp's style guide. It also covers voice and tone as well as a styling conventions for MUI products. This is what I use as the source of truth for all writing and editing. Let me know if you have any questions about it, or if you come across a situation that it doesn't cover.
