### ISSUE TITLE
[DatePicker] Export MuiTextFieldProps

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#5765]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In order to type the `renderInput` prop of a `DatePicker`:
```tsx
renderInput={(params: MuiTextFieldProps) => { ... }}
```

I need a `MuiTextFieldProps` type.

That's can be imported only like this:
```tsx
import { MuiTextFieldProps } from "@mui/x-date-pickers/internals";
```

which is a bit scary given that it says `internals`.

**Comment by LukasTy** [comment]
Hello.
Why do you need the `params` in the example to be explicitly typed?
If you are not passing a function as a prop, then the type is inferred inside the function declared as prop.
The `MuiTextFieldProps` is just an alias for `TextFieldProps` from `@mui/material/TextField`.
Does it solve your issue?

**Comment by MonstraG** [comment]
In my real case I do pass the function in, and I had to do
```tsx
import type { MuiTextFieldProps } from "@mui/x-date-pickers/internals";

params: Omit<MuiTextFieldProps, "value"> & { value: DateTime }
```
(I'm using `AdapterLuxon`).

If using normal `TextFieldProps`:
```tsx
import { TextFieldProps } from "@mui/material";

params: Omit<TextFieldProps, "value"> & { value: DateTime }
```
, this happens:
```tsx
TS2322: Type '(params: Omit<TextFieldProps, "value"> & { value: DateTime; }) => JSX.Element' is not assignable to type '(props: TextFieldProps) => ReactElement<any, string | JSXElementConstructor<any>>'. 
  Types of parameters 'params' and 'props' are incompatible.
     Type 'TextFieldProps' is not assignable to type 'Omit<TextFieldProps, "value"> & { value: DateTime; }'.
       Type 'StandardTextFieldProps' is not assignable to type 'Omit<TextFieldProps, "value"> & { value: DateTime; }'.
         Type 'StandardTextFieldProps' is not assignable to type '{ value: DateTime; }'.
           Types of property 'value' are incompatible.
             Type '{}' is missing the following properties from type 'DateTime': get, isValid, invalidReason, invalidExplanation, and 66 more.  

PureDateInput.d.ts(77, 5): The expected type comes from property 'renderInput' which is declared here on type 'IntrinsicAttributes & DatePickerProps<DateTime, DateTime> & RefAttributes<HTMLDivElement>'
```

**Comment by LukasTy** [comment]
Are you using a custom `DatePicker` component, which behaves differently?
If not, our component never exposes `params.value` field, it does only expose `params.inputProps.value` and it is of `string` type as it is intended to be used as a value for `input` HTML element.
Could you double check if you are not trying to incorrectly create too strict types without no reason?

**Comment by MonstraG** [comment]
Yep, I'm bumb.

had `value` variable, confused that with what I got from params, `TextFieldProps` works, closing.
