### ISSUE TITLE
DataGrid print export ignoring 'fields' parameter

### ISSUE THREAD

**Issue by adovzhanyn** [mui/mui-x#5775]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When passing a list of fields when calling `exportDataAsPrint` directly, the `fields` key is ignored and all fields are included in the print. This functionality works as expected when calling `exportDataAsCsv`.

### Expected behavior 🤔

When I pass a list of `fields` to export, it should export only those fields, as stated in the documentation.

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Have any grid with data set up
2. Create an apiRef using `useGridApiRef()` and pass it to the grid as the `apiRef` prop.
3. Have a button, which onClick, calls 
```javascript
  gridApiRef.current.exportDataAsPrint({
          fields: [ some subset of fields here ]
  })
```
4. The print export that is generated will include all fields in the grid, not only the ones you passed in

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
I tried to reproduce the issue but I couldn't. If you have set the `columnVisibilityModel` prop it may break the print export. Could you provide a **minimal** reproduction test case with the latest version? A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point.
