### ISSUE TITLE
DatePicker does not allow inputProps of any kind in renderInput

### ISSUE THREAD

**Issue by thecristopherofficial** [mui/mui-x#5776]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello!

I'm trying to use the inputProps property inside the TextField of  the renderInput of my DatePicker.

If I set any value to that inputProps the DatePicker wont show the selected Date:

![image](https://user-images.githubusercontent.com/62439469/184415465-f2c6a3ab-b6f7-468b-a320-10d644701b1c.png)

Here's an example of it with the autoComplete property:

` renderInput: (params) => (
      <TextField
        size="small"
        {...params}
        InputLabelProps={{
          required: required,
        }}
        style={{ width: width ? width : "100%" }}
        inputProps={{
          autoComplete: "off"
        }}
      />
    ),`

I also tried to add the property to its params:

`renderInput: (params) => {
      let newParams = { ...params, autoComplete: autoComplete || "off" };
      return (
        <TextField
          size="small"
          {...newParams}
          style={{ width: width ? width : "100%" }}
          onFocus={(e) => e.target.select()}
          InputLabelProps={{
            required: required,
          }}
        />
      );
    },`

But had no result :(

### Expected behavior 🤔

The TextField inside de DatePicker should be able to recognize its inputProps if they exist!

**Comment by LukasTy** [comment]
Hello @thecristopherofficial 
Could you provide a codesandbox with the case you are trying to reproduce and having issues with?

I was able to pass the listed props to `TextField` without problems. 🤔 
[Here are](https://codesandbox.io/s/mui-x-date-picker-overriding-input-props-b1wn9c?file=/demo.tsx) a couple of examples I've tried.

Feel free to close the issue if the examples help you resolve your issue.

**Comment by thecristopherofficial** [comment]
Hello @LukasTy !

Thank you for your response, I upgraded the version of MUI and the props are passed to the TextField with no problems!

Also with the help of your examples I validated that there are some compatibility issues with Dashlane:

![image](https://user-images.githubusercontent.com/62439469/186041371-6e5afd04-2c3b-489a-8977-e9f905ad2bd5.png)

So in conclusion the autoComplete prop does work, it's just that Dashlane doesnt recognize it! 

Thanks!

**Comment by LukasTy** [comment]
Yeah, password managers are a whole different story altogether.
It seems that `dashlane` refuses to respect `autocomplete="off"`.
You could consider [adding `data-form-type="other"`](https://stackoverflow.com/a/69190988/3303436) to also disable `Dashlane` from trying to save such fields.

I'm glad we could work it out. 🤞
