### ISSUE TITLE
datetimepicker should accept the `required` prop

### ISSUE THREAD

**Issue by sirpy** [mui/mui-x#5794]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when adding the `required` prop to datetimepicker it doesnt add asterix `*` next to the field name

### Expected behavior 🤔

should add asterix next to field name when adding the required prop

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Hello @sirpy 
Picker components do not support validation out of the box.
If you need to specify a field as required, you will need to take care of the validation part yourself, but the `required` flag can easily be applied to the `TextField` component.

```tsx
renderInput={(props) => <TextField {...props} required />}
```
