### ISSUE TITLE
[data grid] Grid panel buttons accessibility issues

### ISSUE THREAD

**Issue by aaarichter** [mui/mui-x#5796]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

**Issue 1 - density button**

When showing the filter panel and running the Chrome plugin "Accessibility Insights for Web" Fastpass mode, the density buttons `aria-controls` property is highlighted due to its menu not being mounted in the DOM

![Screenshot 2022-08-15 at 07 11 14](https://user-images.githubusercontent.com/2707029/184580403-9381afb1-d32b-42b8-b84b-4388b2dda988.png)

When opening the density menu & running the plugin again, there is no issue, because the menus id is present in the DOM

**Issue 2 - export button**

When clicked, `aria-controls` is not set
![Screenshot 2022-08-15 at 07 24 24](https://user-images.githubusercontent.com/2707029/184581548-b2eac008-c38a-482b-aff3-62ae845d5d15.png)

**Issue 3 - filter & columns button**

After clicking the filter or the columns button, the `aria-controls` and `aria-haspopup` attributes are not set to the button props
![Screenshot 2022-08-15 at 07 25 43](https://user-images.githubusercontent.com/2707029/184581344-9689740a-f1f3-408d-8da4-d9d7bf301ff1.png)

### Expected behavior 🤔

For issue 1,   the `aria-controls` property could be set only when the menu is opened

see https://www.w3.org/WAI/ARIA/apg/patterns/menubutton/ states 

> Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element with role menu.

For issue 2, set `aria-controls` when the menu is open

For issue 3, set `aria-controls` and `aria-haspopup=true` when the filter panel is open

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-data-grid/demo/

Steps:
1. inspect filter buttons
2.click filter buttons

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.5
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Edge: Not Found
    Firefox: 101.0.1
    Safari: 15.6
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled:  11.9.3 
    @mui/base:  5.0.0-alpha.92 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.94 => 5.0.0-alpha.94 
    @mui/material: ^5.10.0 => 5.10.0 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine:  5.10.0 
    @mui/system: ^5.10.0 => 5.10.0 
    @mui/types:  7.1.5 
    @mui/utils:  5.9.3 
    @mui/x-data-grid: ^5.15.2 => 5.15.2 
    @types/react: 17.0.45 => 17.0.45 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    styled-components: ^5.3.5 => 5.3.5 
    typescript: ^4.7.4 => 4.7.4 
```
</details>

**Comment by m4theushw** [comment]
For the density and the export button, we could fix with the diff below:

```diff
diff --git a/packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx b/packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
index 0238da753..fdfe2ceb6 100644
--- a/packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
+++ b/packages/grid/x-data-grid/src/components/toolbar/GridToolbarDensitySelector.tsx
@@ -109,7 +109,7 @@ export const GridToolbarDensitySelector = React.forwardRef<HTMLButtonElement, Bu
           aria-label={apiRef.current.getLocaleText('toolbarDensityLabel')}
           aria-expanded={open ? 'true' : undefined}
           aria-haspopup="menu"
-          aria-controls={densityMenuId}
+          aria-controls={open ? densityMenuId : undefined}
           id={densityButtonId}
           {...other}
           onClick={handleDensitySelectorOpen}
diff --git a/packages/grid/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx b/packages/grid/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
index 03f78ac1d..692751d7f 100644
--- a/packages/grid/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
+++ b/packages/grid/x-data-grid/src/components/toolbar/GridToolbarExportContainer.tsx
@@ -62,6 +62,7 @@ export const GridToolbarExportContainer = React.forwardRef<HTMLButtonElement, Bu
           aria-label={apiRef.current.getLocaleText('toolbarExportLabel')}
           aria-haspopup="menu"
           aria-labelledby={menuId}
+          aria-controls={open ? menuId : undefined}
           id={buttonId}
           {...other}
           onClick={handleMenuOpen}
```

For the filter and columns button, however, it's a bit more complicated to do because we don't give an ID for the panel. It would be more or less like the diff below:

```diff
diff --git a/packages/grid/x-data-grid/src/components/panel/GridPreferencesPanel.tsx b/packages/grid/x-data-grid/src/components/panel/GridPreferencesPanel.tsx
index fb2ce0bfe..6136fb10d 100644
--- a/packages/grid/x-data-grid/src/components/panel/GridPreferencesPanel.tsx
+++ b/packages/grid/x-data-grid/src/components/panel/GridPreferencesPanel.tsx
@@ -26,6 +26,7 @@ export const GridPreferencesPanel = React.forwardRef<
       ref={ref}
       as={rootProps.components.BasePopper}
       open={columns.length > 0 && preferencePanelState.open}
+      id={preferencePanelState.id}
       {...rootProps.componentsProps?.panel}
       {...props}
       {...rootProps.componentsProps?.basePopper}
diff --git a/packages/grid/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx b/packages/grid/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx
index 3206f2833..e97f0b580 100644
--- a/packages/grid/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx
+++ b/packages/grid/x-data-grid/src/components/toolbar/GridToolbarFilterButton.tsx
@@ -127,6 +127,7 @@ const GridToolbarFilterButton = React.forwardRef<HTMLButtonElement, GridToolbarF
           }
           {...buttonProps}
           onClick={toggleFilter}
+          aria-controls={preferencePanel.open ? preferencePanel.id : undefined}
           {...rootProps.componentsProps?.baseButton}
         >
           {apiRef.current.getLocaleText('toolbarFilters')}
diff --git a/packages/grid/x-data-grid/src/hooks/features/preferencesPanel/useGridPreferencesPanel.ts b/packages/grid/x-data-grid/src/hooks/features/preferencesPanel/useGridPreferencesPanel.ts
index 473a2634d..1deed8b0a 100644
--- a/packages/grid/x-data-grid/src/hooks/features/preferencesPanel/useGridPreferencesPanel.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/preferencesPanel/useGridPreferencesPanel.ts
@@ -60,9 +60,10 @@ export const useGridPreferencesPanel = (
     (newValue) => {
       logger.debug('Opening Preferences Panel');
       doNotHidePanel();
+      const id = ...; // Random ID
       apiRef.current.setState((state) => ({
         ...state,
-        preferencePanel: { ...state.preferencePanel, open: true, openedPanelValue: newValue },
+        preferencePanel: { ...state.preferencePanel, open: true, openedPanelValue: newValue, id },
       }));
       apiRef.current.publishEvent('preferencePanelOpen', {
         openedPanelValue: newValue,
```

And the same for the columns button.

Do you want to submit a PR with any of the diffs above?

**Comment by chaiwattsw** [comment]
I would like to take if author unavailable to do but I still not clear about the id, Could you give me more details since its doesn't provide an id

> ```diff
> +      const id = ...; // Random ID
> ```

**Comment by aaarichter** [comment]
> ```diff
> GridToolbarFilterButton
> ```

Hey @chaiwattsw  - I'm almost done with implementing it ;)
 
regarding the random ID - this can be done with the new `useId` hook from react 18

**Comment by chaiwattsw** [comment]
> Hey @chaiwattsw - I'm almost done with implementing it ;) but thanks for wanting to step in
> 
> regarding the random ID - this can be done with the new `useId` hook from react 18

Ah I see, Thank you.

**Comment by aaarichter** [comment]
PR https://github.com/mui/mui-x/pull/5806

**Comment by romgrk** [comment]
After checking with the ARIA group, it seems that this issue is a false positive from the report tool used here, "Accessibility insights for web". I've poked around to find where to file an issue with them but I haven't, but this is a problem on their side.

Details: https://github.com/w3c/aria/issues/1956#issuecomment-1593796396

We could revert this change our initial implementation was correct.
