### ISSUE TITLE
[Datagrid] selectionModel in initialValues

### ISSUE THREAD

**Issue by AnvarAka1** [mui/mui-x#5807]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am trying to set initial selection model in the datagrid and initial `selectionModel` is in the url query parameters. So I get this value and put it to the `selectionModel` initial state in `useState` hook. 
The problem is that it initially works, but in between renders, the `onSelectionModel` function is invoked. The `newSelectionModel` value is empty array, which means, that even though the url still has items selected in query params, the datagrid does not. It resets `selectionModel` state to empty array.

I have tried using `refs`, but that also didn't work well. So, I guess, that functionality of initial `selectionModel` is missing inside `initialValues` prop in the datagrid. 

If anyone has solution, that would be helpful

### Examples 🌈

**Datagrid.js:**
```
const checkbox = useCheckbox()
.
.
.
<DataGridPro
    getRowId={row => row[primaryKey]}
    rows={rows}
    columns={columns}
    rowCount={count}
    rowHeight={rowHeight}

    checkboxSelection={checkboxSelection}
    selectionModel={selectionModel}
    onSelectionModelChange={checkbox.onSelectionModelChange}

    initialState={{
      pagination: { page: pagination.page > 0 ? pagination.page : 0 },
      sorting: { sortModel }
    }}
  />
```

**useCheckbox hook:**
```
function useCheckbox ({ prefix = '' } = {}) {
  const { replaceParams } = useRoute()
  const params = useAllSearchParams()

  const urlKey = `${prefix}select`

  const mySelectionModel = pipe(
    propOr('', urlKey),
    split(','),
    filter(pipe(isEmpty, not))
  )(params)

  const [selectionModel, setSelectionModel] = useState(mySelectionModel)

  const selectionModelMemoized = useMemo(() => selectionModel, [selectionModel])

  const onSelectionModelChange = useCallback(newSelectionModel => {
    setSelectionModel(newSelectionModel)
    replaceParams({ ...params, [urlKey]: newSelectionModel.join(',') })
  }, [params, replaceParams, urlKey])

  return {
    selectionModel: selectionModelMemoized,
    onSelectionModelChange
  }
}

export default useCheckbox

```

### Order ID 💳 (optional)

47534

**Comment by m4theushw** [comment]
> The problem is that it initially works, but in between renders, the onSelectionModel function is invoked. 

Could you describe better in which situation `onSelectionModel` is called?

---

Apart from that, if the passed `selectionModel` contains IDs for rows that are not in `rows`, the grid will sanitize the IDs and call the callback with only IDs for existing rows. You can disable this behavior by enabling the `keepNonExistentRowsSelected` prop. Does it work?

**Comment by AnvarAka1** [comment]
> > The problem is that it initially works, but in between renders, the onSelectionModel function is invoked.
> 
> Could you describe better in which situation `onSelectionModel` is called?
> 
> Apart from that, if the passed `selectionModel` contains IDs for rows that are not in `rows`, the grid will sanitize the IDs and call the callback with only IDs for existing rows. You can disable this behavior by enabling the `keepNonExistentRowsSelected` prop. Does it work?

Thanks a lot. That worked well!

**Comment by ozanmanav** [comment]
@m4theushw MUI v4 does not have keepNonExistentRowsSelected. Do you know a workaround for this?
