### ISSUE TITLE
[question] Sorting via back-end

### ISSUE THREAD

**Issue by noghartt** [mui/mui-x#5814]
### Order ID 💳

49216

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

My sorting columns comes from back-end, when we press the header cell, we do a fetch that handle the sort for me.

Is there any example where I could reach this behavior using the sorting API from DataGrid?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Linux 5.18 NixOS 22.11 (Raccoon) 22.11 (Raccoon)
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 4.51 GB / 14.87 GB
    Container: Yes
    Shell: 5.1.16 - /nix/store/fcd0m68c331j7nkdxvnnpb8ggwsaiqac-bash-5.1-p16/bin/bash

  Binaries:
    Node: 16.14.2 - /nix/store/zl4bvsqfxyx5vn9bbhnrmbmpfvzqj4gd-nodejs-16.14.2/bin/node
    Yarn: 1.22.19 - ~/entria/nix-env/woovi-admin/node_modules/.bin/yarn
    npm: 8.5.0 - /nix/store/zl4bvsqfxyx5vn9bbhnrmbmpfvzqj4gd-nodejs-16.14.2/bin/npm

  Utilities:
    Make: 4.3 - /nix/store/jm3nxvmxcm5nvalbv28acvygismcykvj-gnumake-4.3/bin/make
    GCC: 11.2.0 - /nix/store/58pwclg9yr437h0pfgrnbd0jis8fqasd-gcc-wrapper-11.2.0/bin/gcc
    Git: 2.37.1 - /etc/profiles/per-user/noghartt/bin/git
    Clang: 11.1.0 - /etc/profiles/per-user/noghartt/bin/clang

  Virtualization:
    Docker: 20.10.14 - /nix/store/5a5i251w81licm57ikbiysc9fcpw391s-docker-20.10.14/bin/docker

  IDEs:
    Emacs: 28.1.91 - /etc/profiles/per-user/noghartt/bin/emacs
    Nano: 6.3 - /run/current-system/sw/bin/nano
    VSCode: 1.70.0 - /etc/profiles/per-user/noghartt/bin/code
    Vim: 9.0 - /run/current-system/sw/bin/vim

  Languages:
    Bash: 5.1.16 - /nix/store/fcd0m68c331j7nkdxvnnpb8ggwsaiqac-bash-5.1-p16/bin/bash
    Perl: 5.34.1 - /run/current-system/sw/bin/perl
    Python: 3.9.12 - /nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/bin/python
    Python3: 3.9.12 - /nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/bin/python3

  Databases:
    MongoDB: 3.6.23 - /nix/store/yslpc5lnli8kc71lw5ixm3q4hq5dpfcv-mongodb-3.6.23/bin/mongo

  Browsers:
    Firefox: 103.0.2

  Monorepos:
    Yarn Workspaces: 1.22.19
    Lerna: 5.4.2
</details>

**Comment by alexfauquette** [comment]
Is there something missing in the [server side sorting demo](https://mui.com/x/react-data-grid/sorting/#server-side-sorting)?

**Comment by flaviendelangle** [comment]
@alexfauquette should we close this one since we did not have any feedback ?
