### ISSUE TITLE
[data grid] Add slot for the column header sort icon

### ISSUE THREAD

**Issue by Tucker-Gilligan** [mui/mui-x#5815]
### Order ID 💳

48138

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm currently working on creating custom column headers in a MUI DataGridPremium component, and encountering some challenges achieving certain features.

- I would like to disable clickable column headers, so sort functionality only works when pressing the sort button (rather than sorting on header click). This is important because I am adding a custom button into the header which will open a dialog
- I would like to add a custom tooltip for the sort button for each column, which includes the header name i.e. `Sort by ${column.headerName}`, however it seems i cannot customize this tooltip per-column.
<img width="186" alt="Screen Shot 2022-08-16 at 3 21 09 PM" src="https://user-images.githubusercontent.com/72029209/184965421-97637c85-d8ba-44b1-bb8d-5510a5bea9f1.png">

I'd like to know if this is achievable, and if there are any additional resources / examples that can help me to achieve this.

Thank you for your time!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 12.5
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Edge: Not Found
    Firefox: 95.0.2
    Safari: 15.6
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.79
    @mui/envinfo: ^2.0.6 => 2.0.6
    @mui/icons-material: ^5.6.1 => 5.6.2
    @mui/material: ^5.6.1 => 5.6.4
    @mui/private-theming:  5.6.2
    @mui/styled-engine:  5.6.1
    @mui/styles: ^5.6.1 => 5.6.2
    @mui/system:  5.6.4
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-data-grid:  5.15.1
    @mui/x-data-grid-premium: ^5.15.1 => 5.15.1
    @mui/x-data-grid-pro:  5.15.1
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.2
    @mui/x-license-pro: ^5.15.0 => 5.15.0
    @types/react: 17.0.2 => 17.0.2
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.6.3 => 4.6.4

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
> I would like to disable clickable column headers, so sort functionality only works when pressing the sort button (rather than sorting on header click). This is important because I am adding a custom button into the header which will open a dialog

You can do this by disabling the default behavior of the `columnHeaderClick` event. We have the `onColumnHeaderClick` prop tied to this event. You can see more information in https://mui.com/x/react-data-grid/events/#disabling-the-default-behavior

> I would like to add a custom tooltip for the sort button for each column, which includes the header name i.e. Sort by ${column.headerName}, however it seems i cannot customize this tooltip per-column.

For this, we'll need to add a slot to allow to customize the sort button. We already have a slot for the filter button: https://github.com/mui/mui-x/blob/323a33a98fb67d1a3f8f70703f6357281e7aa854/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx#L196-L200

**Comment by josebui** [comment]
We need this too, we have the need to define a "aria-describedby" in the sort button for accessibility purposes

**Comment by MBilalShafi** [comment]
@m4theushw Should we also shift `rootProps.componentsProps?.columnHeaderFilterIconButton` to `<rootProps.components.ColumnHeaderFilterIconButton />` for consistency?
