### ISSUE TITLE
Grid Aggregation Row - How can I update the aggregation model programmatically after the intialState has been read?

### ISSUE THREAD

**Issue by mschaefer-gresham** [mui/mui-x#5819]
### Order ID 💳

45466

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

There does not appear to be a way to update the aggregation model programmatically after the initialState has been read for the first time. Trying to update the initialState has no effect on subsequent renders.

In our use case, we determine whether a column should be aggregated based on a property of the column object. Since the columns are fetched from the api, this implies that we can't build the intialState until the columns are returned. This is turn implies that we can't render the grid until the columns are returned. 

But this is not what we want - we currently render the grid with empty column and data properties so that the grid is rendered while we are waiting for the columns and data to be returned. 

So how can I update the aggregation model once the grid has been rendered. I can't seem to find a way to do it. Since it's possible to change the model via the column menu, it should be possible right?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.5
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.20.0 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: 86.0.1
    Safari: 15.6
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.86 
    @mui/envinfo: ^2.0.6 => 2.0.6 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.87 => 5.0.0-alpha.87 
    @mui/material: ^5.8.5 => 5.8.5 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/styles: ^5.8.4 => 5.8.4 
    @mui/system: ^5.8.5 => 5.8.5 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.15.2 
    @mui/x-data-grid-premium: ^5.15.1 => 5.15.2 
    @mui/x-data-grid-pro:  5.15.2 
    @mui/x-date-pickers: ^5.0.0-beta.0 => 5.0.0-beta.0 
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.0 
    @mui/x-license-pro:  5.15.0 
    @types/react: ^17.0.38 => 17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: <4.5.5 => 4.5.4 
```
Using Chrome.
</details>

**Comment by cherniavskii** [comment]
Hey @mschaefer-gresham 

What you are looking for is controlled aggregation model - see https://mui.com/x/react-data-grid/aggregation/#controlled-aggregation
