### ISSUE TITLE
[DataGrid] Performance issue when combined with react-grid-layout

### ISSUE THREAD

**Issue by shetamitesh** [mui/mui-x#5829]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am developing functionality where I can create widgets and drag and drop wherever I like on screen. For this purpose, I am using react-grid-layout and my widgets are created using MUI.

https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-gu8uez?file=/index.tsx

See the demo link above. It works perfectly. However, right clicking info column opens context menu at wrong position and then it is rendered at right position.

Also, in my project, right clicking opens context menu after a delay of 2-3 seconds. Same happens with opening Dialog on button click.

See the video below.

https://user-images.githubusercontent.com/6822256/185316877-a6d91533-40bd-47a6-bcf2-212dc16bfc4a.mp4

Same button click problem is not there in demo link above so not able to understand the problem. Please help me find the solution.

### Expected behavior 🤔

- Context menu should appear from click location without delay.
- Dialog should appear on button click without delay.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-gu8uez?file=/index.tsx

Steps:
1. Click on Add Item
2. Resize grid to show last info column
3. Right click on empty area of info column
4. Click on B or S button to check delay issue

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
```
</details>

### Order ID 💳 (optional)

46861

**Comment by m4theushw** [comment]
> However, right clicking info column opens context menu at wrong position and then it is rendered at right position.

I fixed this by moving the Menu out from `renderCell`. Here's the updated CodeSandbox: https://codesandbox.io/s/throttledrowsgrid-demo-mui-x-forked-q9nfre

> Also, in my project, right clicking opens context menu after a delay of 2-3 seconds. Same happens with opening Dialog on button click.

I couldn't reproduce this. Are you sure this is not the transition time?
