### ISSUE TITLE
[data grid] Add prop to customize sort order in the columns panel

### ISSUE THREAD

**Issue by gavbrennan** [mui/mui-x#5830]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm using Mui DataGrid-Pro/X and have a request to make the column chooser menu appear in alphabetical order. So far, the only way I can see to do this is to change the order of the columns in the grid or to write a whole new column panel element. Is there a more practical / simple way to do this? Or is there a way to access the code for the default component to perform some light customization without reinventing the wheel?

### Motivation 🔦

User requests that the column picker show columns in alphabetical order

**Comment by m4theushw** [comment]
The only way we have is to override the columns panel.

> Or is there a way to access the code for the default component to perform some light customization without reinventing the wheel?

The component is https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx. You can just duplicate it and pass the custom one to the `ColumnsPanel` slot.

To make things easier we could add a prop to customize the order. Then you should be able to do:

```tsx
<DataGrid componentsProps={{ columnsPanel: { sort: 'asc' } }} />
```

For it to work we need to make the following modification:

```diff
diff --git a/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx b/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx
index 1b2c7c585..cc18ea220 100644
--- a/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx
+++ b/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx
@@ -70,6 +70,20 @@ export function GridColumnsPanel(props: GridColumnsPanelProps) {
   const ownerState = { classes: rootProps.classes };
   const classes = useUtilityClasses(ownerState);
 
+  const sortedColumns = React.useMemo(() => {
+    if (rootProps.componentsProps?.columnsPanel.sort === 'asc') {
+      return columns.sort((a, b) =>
+        (a.headerName || a.field) > (b.headerName || b.field) ? 1 : -1,
+      );
+    } else if (rootProps.componentsProps?.columnsPanel.sort === 'desc') {
+      return columns.sort((a, b) =>
+        (a.headerName || a.field) < (b.headerName || b.field) ? 1 : -1,
+      );
+    } else {
+      return columns;
+    }
+  }, [columns, rootProps.componentsProps?.columnsPanel.sort]);
+
   const toggleColumn = (event: React.MouseEvent<HTMLButtonElement>) => {
     const { name: field } = event.target as HTMLInputElement;
     apiRef.current.setColumnVisibility(field, columnVisibilityModel[field] === false);
@@ -112,14 +126,14 @@ export function GridColumnsPanel(props: GridColumnsPanelProps) {
 
   const currentColumns = React.useMemo(() => {
     if (!searchValue) {
-      return columns;
+      return sortedColumns;
     }
     const searchValueToCheck = searchValue.toLowerCase();
-    return columns.filter(
+    return sortedColumns.filter(
       (column) =>
         (column.headerName || column.field).toLowerCase().indexOf(searchValueToCheck) > -1,
     );
-  }, [columns, searchValue]);
+  }, [searchValue, sortedColumns]);
 
   React.useEffect(() => {
     searchInputRef.current!.focus();
```

Do you want to submit a PR?

**Comment by gavbrennan** [comment]
Thanks Matheus.  Makes perfect sense, but is it ok to call .sort() on the columns array directly, as I believe that will re-order the columns object, or should it take a copy of the array first?

**Comment by m4theushw** [comment]
> Makes perfect sense, but is it ok to call .sort() on the columns array directly, as I believe that will re-order the columns object, or should it take a copy of the array first?

Good question. It seems that `.sort` changes the cached value for the selector, so creating a copy of it first is better.
