### ISSUE TITLE
[Datagrid Pro v4] Cannot mix server-side and client-side pagination

### ISSUE THREAD

**Issue by MadalenaPavao** [mui/mui-x#5831]
I am using Datagrid Pro v4 and I want to implement pagination.
I have the component as such:

`<DataGridPro
            apiRef={apiRef}
            rows={rows}
            columns={columns}
            loading={loading}
            rowHeight={37}
            disableSelectionOnClick
            pagination
            autoPageSize
            rowCount={rowCount}
            //paginationMode="server"
            //page={page}
            onPageChange={handlePageChange}
            filterMode="server"
            onFilterModelChange={handleFilterModelChange}
          />`

I want to show an N number of rows per page (autoPageSize). Since I have many rows to be displayed, I want to call the back-end every 100 rows. 
So, imagining I have 10 rows per page, I would only want to call the back-end on the 11th page for more 100 rows, and so on.

But so far I haven't managed to do so. I tried to use paginationMode="server", but it forces me to call the back-end at each page change. Is there a solution for this?

**Comment by cherniavskii** [comment]
Hey @MadalenaPavao 

In `server` pagination mode `onPageChange` is called on every page change.
But it's up to you what to do when it's called - you can update state with the data that you've fetched before, or fetch new data and update the state.

Our of curiosity, what is the reasoning behind this approach to pagination?

**Comment by MadalenaPavao** [comment]
@cherniavskii thanks for your answer. 
The reason is that I don't want to call the BE every 10 or 20 rows. That would make way too many calls. We have established that every 100 rows is the best approach.

While I understand that it's up to me to do what I want when onPageChange is called, the truth is that when I am able to call the BE when I establish, the data won't change on page change until the BE is called.

**Comment by cherniavskii** [comment]
> the truth is that when I am able to call the BE when I establish, the data won't change on page change until the BE is called.

I'm not sure I'm following the problem here.
Here's a demo to show the idea: https://codesandbox.io/s/busy-shape-qjblqd?file=/demo.tsx
You can see that `fetchRows` either fetches rows from backend or returns rows from previously cached batch of fetched rows.
Hope it helps.
