### ISSUE TITLE
[data grid] Update cell/row model if attempt to stop edit mode was not successful

### ISSUE THREAD

**Issue by BrandonVanZyl** [mui/mui-x#5832]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. Forked the full crud example
2. Added a preProcessEditCellProps to require non empty names

```
      preProcessEditCellProps(params) {
        const hasError = params.props.value === "";
        return { ...params.props, error: hasError };
      }
```
3. Edit any row empty the name value click save and click away and the edit state gets reverted
![MuiDataGridIssue](https://user-images.githubusercontent.com/82510816/185363126-6cd9271f-2e48-4bd3-80aa-bea015d9c878.gif)

### Expected behavior 🤔

1. When clicking save the edit state is immediately reverted

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/fullfeaturedcrudgrid-demo-mui-x-forked-vusdb6?file=/demo.tsx:4073-4225

Steps:
1. Edit first row
2. Delete name
3. Click save
4. click on a different row

### Context 🔦

trying to use validation with row editing

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

39468

**Comment by m4theushw** [comment]
The following diff should fix this bug:

```diff
diff --git a/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts b/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
index df5faed34..afcc6764e 100644
--- a/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/editRows/useGridCellEditing.new.ts
@@ -383,6 +383,7 @@ export const useGridCellEditing = (
         // Attempt to change cell mode to "view" was not successful
         // Update previous mode to allow another attempt
         prevCellModesModel.current[id][field].mode = GridCellModes.Edit;
+        updateFieldInCellModesModel(id, field, { mode: GridCellModes.Edit });
         return;
       }
 
diff --git a/packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts b/packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts
index 571470108..ec114a29e 100644
--- a/packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/editRows/useGridRowEditing.new.ts
@@ -475,6 +475,7 @@ export const useGridRowEditing = (
 
       if (hasSomeFieldWithError) {
         prevRowModesModel.current[id].mode = GridRowModes.Edit;
+        updateRowInRowModesModel(id, { mode: GridRowModes.Edit });
         return;
       }
```

**Comment by cliedeman** [comment]
@m4theushw thanks for the reply.
Should we treat these patches are the fix that you expect to go in or should we wait for a PR?

**Comment by m4theushw** [comment]
This diff is the fix we need to put in a PR. It will be released this or next week.
