### ISSUE TITLE
[data grid] onRowModelChange prop missing from full crud datagrid documentation

### ISSUE THREAD

**Issue by BrandonVanZyl** [mui/mui-x#5834]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Where rowModesModel is passed in , onRowModesModelChange is not in the full crud editing example.

1.https://github.com/mui/mui-x/blob/master/docs/data/data-grid/editing/FullFeaturedCrudGrid.js#L208

### Expected behavior 🤔

Expect to find onRowModelChange to receive the incoming changes to the state

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

39468

**Comment by m4theushw** [comment]
We can add `onRowModelChange` but it's not necessary for this demo. It's not there because we want to fully control the row modes and never the grid send changes. But if we add validation, like in #5832, then it needs to be passed.

**Comment by cliedeman** [comment]
Hi @m4theushw its probably safe to pass both because I actually didn't realize I never passed the setState function and spent some time trying to track down why it wasn't working. Just a small footgun
