### ISSUE TITLE
x-date-pickers: how to change the color of the selected item?

### ISSUE THREAD

**Issue by MaximeMathyCarne** [mui/mui-x#5836]
### Order ID 💳

41229

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to change colors into the DatePicker component.
I found some similar issue but nothing with a solution working for me.

Here is my current DatePicker (year and month enabled):
![image](https://user-images.githubusercontent.com/55590929/185382597-c0d3bf86-a677-48cc-a089-e47cf3f9a321.png)
![image](https://user-images.githubusercontent.com/55590929/185382649-5c840d52-49a1-4d03-b214-1ee156d94f6a.png)

I would like to change the background color of the selected year/month (or the color of the text).   

Here is the code I use without styling attemp:

```
<LocalizationProvider dateAdapter={AdapterDateFns}>
      <DatePicker
        label={label}
        views={["year", "month"]}
        value={date}
        minDate={minDate}
        maxDate={maxDate}
        onChange={onDateChange}
        renderInput={(props) => (
          <TextField {...props} size="small" InputLabelProps={{ shrink: true }} id={id + "-field"} />
        )}
      />
    </LocalizationProvider>
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.13.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.82
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0
    @emotion/styled: ^11.10.0 => 11.10.0
    @mui/base:  5.0.0-alpha.91
    @mui/icons-material: ^5.8.4 => 5.8.4
    @mui/lab: ^5.0.0-alpha.92 => 5.0.0-alpha.92
    @mui/material: ^5.9.2 => 5.9.2
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/styles: ^5.9.2 => 5.9.2
    @mui/system:  5.9.2
    @mui/types:  7.1.5
    @mui/utils:  5.9.1
    @mui/x-data-grid:  5.15.0
    @mui/x-data-grid-pro: ^5.15.0 => 5.15.0
    @mui/x-date-pickers:  5.0.0-beta.3
    @mui/x-date-pickers-pro: ^5.0.0-beta.3 => 5.0.0-beta.3
    @mui/x-license-pro: ^5.15.0 => 5.15.0
    @types/react: ^17.0.43 => 17.0.43
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.7.4 => 4.7.4
```
</details>

**Comment by LukasTy** [comment]
Hello @MaximeMathyCarne 

- If you want to change style of all the pickers in the application, feel free to [override the needed styles via theme](https://mui.com/material-ui/customization/theme-components/#global-style-overrides).
- If you want to change style only for particular cases, without changing globals, you can refer to [customising day rendering](https://mui.com/x/react-date-pickers/date-picker/#customized-day-rendering) example.

Does it help you solve your case?
If you need a more concrete example, please confirm the approach you want to take from the two listed above.

**Comment by MaximeMathyCarne** [comment]
Hello @LukasTy 

Thanks for your answer.

I prefer to use the theme. However, I don't know which class to override.
I don't find any css info on that page: https://mui.com/x/api/date-pickers/date-picker/

With the browser inspector, I can see an element with the class "MuiYearPicker-root" containing one element per year and the selected year has the class "Mui-selected".

However, those classes don't appear as possible choice in the createTheme.
Example of error with MuiYearPicker:
![image](https://user-images.githubusercontent.com/55590929/185392388-584344a0-df20-45bc-9482-b4b9e9500733.png)

**Comment by LukasTy** [comment]
@MaximeMathyCarne Sorry for not pointing to the last piece of the puzzle.
You need to [import theme augmentation](https://mui.com/x/react-date-pickers/getting-started/#typescript) type to get the `mui-x` component type inference.

**Comment by MaximeMathyCarne** [comment]
Ok, it solved the building issue and I can change the text color !
BEFORE:
https://user-images.githubusercontent.com/55590929/185382597-c0d3bf86-a677-48cc-a089-e47cf3f9a321.png

AFTER:
![image](https://user-images.githubusercontent.com/55590929/185397525-8db1e0e4-0215-4994-9b67-5156a5b7ed88.png)

However, I am still not able to change the background one :-(
That is not really important since I can change the text color to make it readable. But I wonder why it doesn't work.
Here is the code I used:

```
 MuiYearPicker: {
      styleOverrides: {
        root: {
          "& .Mui-selected": {
            backgroundColor: "red", // the background is still black so ti doesn't work
            color: "white", // The text color is white now so it works
          },
        },
      },
    },
```

**Comment by LukasTy** [comment]
Have you tried the following selector instead: `&.Mui-selected`?
Spacing matters as these are css selectors.

**Comment by MaximeMathyCarne** [comment]
I tried but id doesn't work.
With the space it overrides the text color (but now the background one).
Without the space I doesn't override anything.

**Comment by LukasTy** [comment]
Does the following example help you?
```ts
const theme = createTheme({
  components: {
    MuiYearPicker: {
      styleOverrides: {
        root: {
          '& .PrivatePickersYear-yearButton': {
            backgroundColor: '#000',
            color: '#fff',
            '&.Mui-selected': {
              backgroundColor: 'red',
            }
          }
        },
      },
    },
  },
});
```

**Comment by MaximeMathyCarne** [comment]
Almost !

This becomes red only if i focus another element.
Here is the final solution:

```
MuiYearPicker: {
      styleOverrides: {
        root: {
          "& .PrivatePickersYear-yearButton": {
            "&.Mui-selected": {
              backgroundColor: "red",
              "&:focus": {
                backgroundColor: "red",
              },
            },
          },
        },
      },
```
