### ISSUE TITLE
How to use grid cell as link without using renderCell prop

### ISSUE THREAD

**Issue by michGreg** [mui/mui-x#5837]
### Order ID 💳

44899

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is there any way how to set cell component as link? I use datagrid as list of devices and after mouse click by middle (scroll) button i want open the dataGrid list item into item detail in a new browser tab. I use something like cell wrapper and renderCell prop but i have to use cellWraper for every cell. I think that is not best solution because of dataGrid performance. Is there any better solution?

cell wrapper
```
function cellWrapper(cellParams, children) => {
    return (<DataGridCellLinkWrapper
      link={
        ITEM_DETAIL
          .replace(':id', params.id)
          .replace(':itemId', cellParams.row.sn)
      }
    >
      {children}
    </DataGridCellLinkWrapper>)
  };

function DataGridCellLinkWrapper({ children, link }) {
  return (
    <Box
      component={Link}
      sx={{
        '&.text-link': {
          color: 'inherit',
          textDecoration: 'inherit',
        },
        alignItems: 'center',
        color: 'inherit',
        display: 'flex',
        height: '100%',
        textDecoration: 'none',
        width: '100%',
      }}
      to={link}
    >
      {children}
    </Box>
  );
}
```

renderCell prop
```
renderCell: (cell) => cellWrapper(
      cell,
      <DataGridDeviceNameItem deviceData={cell.value} />
    ),
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @michGreg 

> I use something like cell wrapper and renderCell prop but i have to use cellWraper for every cell.

I'm not sure I understand the idea of `cellWrapper` in your code snippet. `renderCell` that returns custom component with a link should be enough. https://codesandbox.io/s/relaxed-newton-iop57p?file=/demo.tsx
