### ISSUE TITLE
[DataGrid] - Expand group on row click

### ISSUE THREAD

**Issue by mormir2** [mui/mui-x#5838]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Would it be possible to add a feature where a grouped row would expand when clicking anywhere on the row, not only on the expand arrow?

### Examples 🌈

E.g. When clicking on the area marked with X in the screenshot, the grouped row "Disney Studios (20)" should expand.
![image](https://user-images.githubusercontent.com/107024062/185402531-09b50e58-5271-4341-899a-80bab90cd654.png)

(Screenshot taken from https://mui.com/x/react-data-grid/row-grouping/#group-expansion)

**Comment by alexfauquette** [comment]
Here is a simple example, using `onClickRow` method. You can use [other `clickRow` event](https://mui.com/x/react-data-grid/events/#catalog-of-events) to detect when a row is clicked

Then you can test if the row has been generated by the group structure thanks to it's id starting with `auto-generated`

The API to toggle the expansion is not defined in the row grouping page, but it's the same as the one used in [tree structure](https://mui.com/x/react-data-grid/tree-data/#children-lazy-loading)

https://codesandbox.io/s/rowgroupingbasicexample-demo-mui-x-forked-f1eotz?file=/demo.tsx

**Comment by mormir2** [comment]
@alexfauquette thank you very much for your suggestion, it works great!

**Comment by john1625b** [comment]
@alexfauquette This solution works but its giving the type error:

`TS2339: Property 'childrenExpanded' does not exist on type 'GridTreeNode'.   Property 'childrenExpanded' does not exist on type 'GridLeafNode'.`

I am on     `"@mui/x-data-grid-premium": "^6.0.4"` and using the <DataGridPremium/> component.

**Comment by cherniavskii** [comment]
@john1625b Can you open a new issue with a reproduction example?
I cannot reproduce it with https://codesandbox.io/s/jnt9ow?file=/demo.tsx

<img width="1007" alt="Screenshot 2023-04-11 at 11 24 54" src="https://user-images.githubusercontent.com/13808724/231116480-15632732-b059-4871-ae6d-c0a7bb3f49c2.png">

**Comment by TheTempest7** [comment]
God bless you, your condition with rowNode.type halped me out a lot!!!!
