### ISSUE TITLE
[StaticDateTimePicker] Show DateTimeToolbar when showToolbar is true and wrapperVariant is 'desktop'

### ISSUE THREAD

**Issue by EsoterikStare** [mui/mui-x#5841]
https://github.com/mui/mui-x/blob/b5111dd5bc8677b1e0135f14c91124586106b0ec/packages/x-date-pickers/src/internals/components/CalendarOrClockPicker/CalendarOrClockPicker.tsx#L114

Due to the line of code linked above, it doesn't seem possible to get a `StaticDateTimePicker` to show it's toolbar when `displayStaticWrapperAs="desktop"`. I'd like to do exactly that, but I can't see a way to do that via the props API.

This feels like an oversight since `showToolbar` works as expected on `StaticDatePicker` and `StaticTimePicker` while in desktop mode. Since there is a `DateTimePicker` `toolbarComponent` that's set on the prop interface of `StaticDateTimePicker` [here](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/StaticDateTimePicker/StaticDateTimePicker.tsx#L77) I'm not sure why it's only allowed when the `wrapperVariant !== 'desktop'`.

Could that additional condition be removed or modified in some way to allow showing the toolbar regardless of `wrapperVariant`?

**Comment by EsoterikStare** [comment]
Potentially also worth noting is that the tabs that switch between date and time modes are rendered below the calendar/clock section when in desktop mode instead of on top. This results in some (I would say) undesirable shifting of that part of the UI when switching back and forth between modes on top of just being different for no apparent reason. Not sure if that's also something to improve, but I can create a separate issue for that if anyone thinks it's worth handling separately, or at all.

**Comment by alexfauquette** [comment]
The line you're pointing at is not responsible for this behavior. It means: 
- If `showToolbar` is defined use it's value
- If `showToolbar` is `undefined` the default value is `wrapperVariant !== 'desktop'`
```jsx
const toShowToolbar = showToolbar ?? wrapperVariant !== 'desktop'; 
```

The difference between mobile and desktop is in the definition of the default Toolbar

https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx#L112:L112

**Comment by EsoterikStare** [comment]
Ah, yup. My bad. Thanks for taking a look and confirming the odd behavior all the same!

**Comment by EsoterikStare** [comment]
@alexfauquette Do you think the tabs positioning I mentioned after the main issue description is worth splitting off into a separate issue? I just realized it's kind of muddying the water on this one.

**Comment by alexfauquette** [comment]
@EsoterikStare Yes, the tabs positioning could have its own issue
