### ISSUE TITLE
[pickers] Allow to override some local texts directly on a picker component

### ISSUE THREAD

**Issue by oliviernt** [mui/mui-x#5844]
### Order ID 💳

46586

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello,

We're using the new DateRangePicker with LocalizationProvider but are now encountering some unexpected behavior regarding labeling.

We want to be able to label different pickers with different labels depending on their form context. For example one will have a start label "Absence from" while another might only have "From" or "Start at".

From what I understand, this currently required multiple LocalizationProviders as it's where the labels currently are defined. See https://mui.com/x/react-date-pickers/localization/

Is there a way to do this without defining multiple LocalizationProviders or it that the way to go? It feels counter intuitive to us at the moment.

Our preferred way of doing this would be to use the `startText` and `endText` props but those are deprecated. See https://mui.com/x/api/date-pickers/date-range-picker/#props

Thank you for your help on this issue.

Best regards
Olivier

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
  npmPackages:
    @emotion/react: ^11.7.1 => 11.9.3 
    @emotion/styled: ^11.6.0 => 11.9.3 
    @mui/base:  5.0.0-alpha.86 
    @mui/icons-material: ^5.2.5 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.54 => 5.0.0-alpha.87 
    @mui/material: ^5.2.7 => 5.8.5 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/styles: ^5.2.3 => 5.8.4 
    @mui/system: ^5.2.6 => 5.8.5 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.4 
    @mui/x-date-pickers:  5.0.0-beta.1 
    @mui/x-date-pickers-pro: ^5.0.0-beta.1 => 5.0.0-beta.1 
    @mui/x-license-pro:  5.12.1 
    @types/react: ^17.0.38 => 17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.4.4 => 4.7.4 
```
</details>

**Comment by LukasTy** [comment]
Hello @oliviernt 
Have you considered creating a wrapper component to which you would pass the overrides you need?
[Here is a basic example](https://codesandbox.io/s/mui-date-range-picker-wrapper-vwm8up?file=/demo.tsx) of the idea.

**Comment by oliviernt** [comment]
Hello @LukasTy 

Thank you for your answer. 

Yes, this is exactly what we're currently doing. But this redefines a new LocalizationProvider for every component.

Is this how it's meant to be used?

My understanding was that the LocalizationProvider should be defined higher up in the component tree. I always thought this as a global app configuration.

The next issue with this approach would be that we're providing an in house component library where we want to add our DateRangePicker wrapping the MUI picker. With the LocalizationProvider wrapping every DateRangePicker we would not only need to pass the DateRangePicker props but also the LocalizationProvider props through our component in order to keep this flexible.

**Comment by alexfauquette** [comment]
Hi @oliviernt yes for now the customization of labels is not satisfying. With the new localization management, we simplified translation but lost some flexibility about customization.

For now the approach proposed by @LukasTy is the only one I'm aware of and we should provide a simpler option

What would you think if you could write `<DateRangePicker localeText={{ start: 'Check-in', end: 'Check-out'}} />`. Such syntax would override the `localeText` provided by the `<LocalizationProvider />`? Or do you have another idea about the API interface that could simplify the customization?

**Comment by oliviernt** [comment]
Hi @alexfauquette 

the solution proposed by @LukasTy is fine for now.

Your proposed way to do this with a direct `localeText` prop would be much simpler and IMO also more in sync with what is expected from the MUI component APIs.

We probably won't expose the `LocalizationProvider` props in our own library component until someone really needs it and hope that way that we can ditch the provider once your solution is implemented.

Just out of curiosity: what was the reason to deprecate the existing label props on the `DateRangePicker`?

**Comment by alexfauquette** [comment]
We moved all the `xxxText` props to `localeText` such that you can translate all your components in a single place (same behavior as data grid and other MUI-core components). It also allows to the community to share their translations

Most of the texts are global. For example "next month" will not change from one picker to another. But for `startText` and `startText` we did not know if dev needs to have different ones for each picker, or if page have only one range picker and so the translation can be done in the global `localeText`

In which case do you need to put multiple `DateRangePickers` without the same labels?

**Comment by oliviernt** [comment]
Thank you for the explanation regarding the deprecation. :+1: 

Regarding our use: as the component library provider we have multiple apps with different use cases we need to account for but one for example is to manage employee absences. The absences may have different types (sickness, vacation, parental leave, etc...) and we want to reflect that in the labels as depending on the language and type there might be better suited wordings for start and end of those absences. For example, in German, we would have "Krank seit" (sick since) and for vacations we would have "Urlaub ab" (vacation from).

**Comment by oliviernt** [comment]
Awesome, thank you all! :+1: :1st_place_medal:
