### ISSUE TITLE
How to remove hide option of one column in '@material-ui/data-grid'

### ISSUE THREAD

**Issue by ShreyaNandi2022** [mui/mui-x#5846]
### Order ID 💳

0000

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am using '@material-ui/data-grid' and now i want to remove 'hide' option for only one column. Please help me to do the same. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
You have `hideable` params. For more details, see the first demo of [column visibility page](https://mui.com/x/react-data-grid/column-visibility/)
