### ISSUE TITLE
Can't implement custom filter for column in dataGrid 

### ISSUE THREAD

**Issue by lrfrryr** [mui/mui-x#5847]
I have a column (DataGrid) with a renderCell needed for a Link, and also a valueGetter. The problem here is that renderCell uses the value from valueGetter, so I need to return an object to be able to use id, name and lastName in renderCell. At the same time, if I return an object in valueGetter, the filter property does not work. I wanted to customize a specific filter for this column, but I think it's not possible. How can I solve this? Is there other way to have a working filter and a renderCell with a link in a DataGrid column?  (can't use valueFormatter because it doesn't support links)
{
      field: "client",
      headerName: "Client",
      width: 200,
      renderCell: (params) => (
        <Link
          underline="hover"
          sx={{ display: "flex", alignItems: "center" }}
          color="inherit"
          component={RouterLink}
          to={params.value ? `/clients/${params.value.id}` : ""}
        >
          {`${params.value.name} ${params.value.lastName}`}
        </Link>
      ),
      valueGetter: getClient,
      sortComparator: (v1, v2) =>
        compareStrings(v1 ? v1.name : null, v2 ? v2.name : null),
    },

**Comment by m4theushw** [comment]
In the params passed to `renderCell` you have the full row object available in the `row` param. You could use the value getter only to return the full name, then get the ID from `row` to build the path for the link. What do you think?

**Comment by lrfrryr** [comment]
I don't know how I didn't think of that, but it worked. Thank you!
