### ISSUE TITLE
[Data Grid] Field as path of object in case of nested structures

### ISSUE THREAD

**Issue by konrazem** [mui/mui-x#5852]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When I have complex data I would like to define field with path to a given value of neseted object.  For example in such case I want to show car.mark and car.model without value getter:
```
function getFullName(params: GridValueGetterParams) {
  return `${params.row.firstName || ""} ${params.row.lastName || ""}`;
}

function getCarModel (params: GridValueGetterParams) {
  return `${params.value}`;
}

const columns: GridColDef[] = [
  { field: "firstName", headerName: "First name", width: 130 },
  { field: "lastName", headerName: "Last name", width: 130 },
  {
    field: "fullName",
    headerName: "Full name",
    width: 160,
    valueGetter: getFullName
  },
  { field: "car.mark", headerName: "Car", width: 130 },
  { field: "car.model", headerName: "Car Model", width: 130, valueGetter: getCarModel }
];

```
(I want GridValueGetterParams.value to be defined. For now this value is undefined)

![image](https://user-images.githubusercontent.com/19363700/185734698-9cb4ce7f-c3c9-4712-8eec-f6ca90eb72e8.png)

Field path structure can be taken from https://lodash.com/docs/4.17.15#get
https://codesandbox.io/s/data-grid-nested-structures-forked-bzsllu?file=/demo.tsx

### Motivation 🔦

Speed up development time

**Comment by flaviendelangle** [comment]
Probably duplicates https://github.com/mui/mui-x/issues/2852 @cherniavskii 
I let you close it unless you see a difference between the two :+1:

**Comment by cherniavskii** [comment]
@konrazem feel free to upvote #2852 and join discussion if you have some input

**Comment by konrazem** [comment]
I am sorry for late answer. Yes it looks like duplicate of  #2852 sorry for that. I upvoted thank you @cherniavskii. 
For now I did custome DataGrid component that add valueGetter if it is undefined:
```typescript
  const renderCol = (col: ColType): ColType => {
    if (col.field.includes('.') && !col.valueGetter) {
      col.valueGetter = (params) => get(params.row, col.field);
    }
  }
```
