### ISSUE TITLE
[pickers] Hydration mismatch

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#5856]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

<img width="600" alt="Screenshot 2022-08-20 at 20 22 04" src="https://user-images.githubusercontent.com/3165635/185761180-f12116fc-8a92-4c82-884b-e59dbabced92.png">

https://reactjs.org/docs/error-decoder.html/?invariant=425

### Expected behavior 🤔

No hydration error, like in v5.15.1.

### Steps to reproduce 🕹

Steps:
1. Open the [v5.15.2](https://app.netlify.com/sites/material-ui-x/deploys/62f50b1265a7ea0008f60dad) permalink release https://62f50b1265a7ea0008f60dad--material-ui-x.netlify.app/x/react-date-pickers/date-picker/
2. Open the dev tools

### Context 🔦

Looking at the diff https://github.com/mui/mui-x/compare/v5.15.1...v5.15.2, I suspect it's related to React 18.

### Your environment 🌎

v5.15.2

**Comment by oliviertassinari** [comment]
I had a quick look at what's going on. It seems that React 18 is more strict when it comes to hydration mismatches. As of today, in https://62f50b1265a7ea0008f60dad--material-ui-x.netlify.app/x/react-date-pickers/date-picker/#custom-input-component, I see the following

Before hydration:

<img width="541" alt="Screenshot 2022-08-20 at 21 33 15" src="https://user-images.githubusercontent.com/3165635/185763438-c1ca5f10-b2ef-44e8-ad45-0e3ae957d553.png">

After hydration:

<img width="498" alt="Screenshot 2022-08-20 at 21 32 56" src="https://user-images.githubusercontent.com/3165635/185763432-256e6ac4-bda7-4212-bc6a-3974062e89d0.png">

Changing my macOS clock to the August 11th, 2022 resolves the hydration mismatch.

**Comment by flaviendelangle** [comment]
Closing it
We no longer have this demo and we try to never rely on the current date-time to avoid this kind of problems

**Comment by oliviertassinari** [comment]
> we try to never rely on the current date-time

Ok, so option 2. from the list above. Fair enough, simple.
