### ISSUE TITLE
[question] Is using Pro-plan elements in an electron app without disclosing the license key possible?

### ISSUE THREAD

**Issue by TheRealCuran** [mui/mui-x#5857]
### Order ID 💳

47016

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I maintain an Electron application for the company related to the order ID mentioned above. The app is distributed to customers and not just some internal tool. How can I prevent a user from extracting the license key provided under the order while still being able to use Pro features in the Electron app? According to the documentation, the key has to appear in the code or there would be the watermarks visible (I mean theoretically I could remove those, but that would certainly be a copyright violation and therefore out of the question).

I'd be grateful for any guidance on this issue. I did search the documentation, but I couldn't find anything on this topic (or my search foo failed me).

### Your environment 🌎

not relevant

**Comment by alexfauquette** [comment]
I do not think it's a problem, in the security [section](https://mui.com/x/introduction/licensing/#security) it's written that the licence can be bundled in the project.

> The license key is checked without making any network requests—it's designed to be public. It's expected that the license key will be exposed in a JavaScript bundle; we simply ask licensed users not to actively publicize their license key.

The point is that the legal aspect is the license. The peace of contract the company bought. The key is a way to check the licence you bought and it's validity.

> The license key is meant to help you [stay compliant](https://mui.com/legal/mui-x-eula/#license-key) with the EULA of the commercial licenses. While each developer needs to be licensed, the license key is set once per project, where the components are used.

**Comment by TheRealCuran** [comment]
OK, thanks! Then I will not worry about the exposure. Probably not many people anyway who'd go through the generated JS.
