### ISSUE TITLE
[question] [DataGridPro] Is there an option to pin column values (ie. not have DataGridPro forget them once they are out of view)?

### ISSUE THREAD

**Issue by TheRealCuran** [mui/mui-x#5863]
### Order ID 💳

47016

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a `DataGridPro` which loads a column (informational only), that is basically a class component, that is passed some ID value. That component loads its data on first view (the calculations required for this column are expensive, which is the reason for this column). The component caches the response from the server to render the proper value all the time, but I noticed that when a column goes out of the active view area and comes back in again – ie. scrolling – the loading animation will show for a short moment, indicating that the class is recreated with the initial date.

The `render()` method in my component class (that is the only thing displayed in that column) looks like this:
```typescript
render() {
  const data = this.props.infoColumn
  const specialCol = this.state.specialColInfo
  if (specialCol === undefined) {
    return <CircularProgress key={`specialColInfo_loading_${data.id}`} />
  }

  if (specialCol === null) {
    return <Typography key={`specialColInfo_none_${data.id}`}>—</Typography>
  }

  let iconColour = 'primary.main'
  if (
    Object.values(specialCol.warnings)
    .map((val) => {
      return val.warn
    })
    .includes(true)
  ) {
    iconColour = deepOrange[500]
  }

  return (
    <Tooltip
      key={`specialColInfo_Tooltip_${data.id}`}
      arrow={true}
      placement="left-start"
      title={
        <Container key={`specialColInfo_Frag_${data.id}`}>
          <img loading="lazy" src={specialCol.url} width="98%" />
          <Typography
            key={`specialColInfo_WarnTxt_${data.id}`}
            sx={{ fontSize: '12px', '& .ul_specialCol': { marginTop: '-5px' } }}
          >
        Status:
      </Typography>
      <ul key={`specialColInfo_WarnUl_${data.id}`} className="ul_specialCol">
        {Object.entries(specialCol.warnings).map(([warnType, warnState]) =>
          this.#genWarnListItem(data.id, warnType, warnState),
        )}
      </ul>
      </Container>
    }
    >
    <IconButton
      key={`specialColInfo_IcoBtn_${data.id}`}
      size="small"
      sx={{ color: iconColour }}
    >
      <ImageRounded key={`specialColInfo_Icon_${data.id}`} />
    </IconButton>
    </Tooltip>
  )
}
```

Since I know the general amount of rows my users will encounter (and there is no need for streaming in the rows dynamically, the amount almost never changes between viewings), it would be nice if I could prevent the loading animation to show up, when a column is viewed a second time. Especially since it seems that the backing class will lose its state/info if it scrolls out of view "too quickly" (especially on devices with small screens/lower resolution) and enter a sort of undefined state, where the flag "loaded date from the server" is set, but the date is no longer available. On quick scrolling operations I have manged to get the `DataGridPro` into a state where it won't (re-)trigger the loading but apparently also lost the data from its first request (the data was loaded successfully according to the Web Developer Tools of Firefox/Chromium, but probably not in time for the column to move out of view, especially on devices with comparatively small screens).

So the question would be: is there any way I can force `DataGridPro` to maintain the full state of all rows at all time. Again we are talking about 50-100 columns, which all modern browsers handle easily, if I load the whole thing as a `<Table>` instead of a `<DataGridPro>`.

### Your environment 🌎

Latest versions of MUI/MUIX, TypeScript. All kept up-to-date by Renovate. Execution is done in the browser, so no Node version is relevant here. I've tested the most recent versions of Firefox and Chromium to verify the issue persists.

**Comment by alexfauquette** [comment]
In the [virtualization doc](https://mui.com/x/react-data-grid/virtualization/), you will find a way to either diable the virtualization (remove both column and row virtualization) or modifying the column buffer

> You can disable column virtualization by setting the column buffer to a higher number than the number of rendered columns, e.g. with `columnBuffer={columns.length}` or `columnBuffer={Number.MAX_SAFE_INTEGER}`.

**Comment by TheRealCuran** [comment]
Indeed! Thanks!
