### ISSUE TITLE
[question] How to hide "empty" child rows when grouping rows

### ISSUE THREAD

**Issue by jvskriubakken** [mui/mui-x#5868]
### Order ID 💳

44972

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I cannot hide "empty" child row a group row.

I am using row grouping on some table data, where one column group (or parent row) and the rest of the columns represent properties of the child rows. The data we have might contain rows without any values in the columns representing the child properties. 

```
| Parent   | Child prop A  | Child prop B   |
---------------------------------------------
| P-1      |  a            | x              |
| P-1      |  b            | y              |
| P-2      |  a            | x              |
| P-2      |  b            | y              |
| P-2      |  c            | x              |
| P-3      |  <null>       | <null>         |
```

This causes the table to be render an empty row below the parent. I am looking for a solution for hiding such rows. Is that possible?

Here you also the issue in the application, where "Tower 3" has all columns representing the "child row" as null and is then rendered as an empty row.
<img width="519" alt="unwanted child rows" src="https://user-images.githubusercontent.com/353738/185903322-fc2b2628-2310-4d22-852a-dbd809277f33.png">

**Comment by cherniavskii** [comment]
Hey @jvskriubakken 
Is there any value of having "empty" rows in your dataset at all?
You can filter them on server/client before passing to the data grid - would that work for you?

**Comment by jvskriubakken** [comment]
Yes, the value of having "empty" rows in the grid table, is that we want to display the "parent row" with a column that displays a status about why there was no child rows of the parent. In the example picture above, you see the column "Inspection Status" displays the text "Unable to inspect" when there is no child rows of the Tower. Technically we are doing a "left outer join" between the two tables Tower and Observation, so that we get a row representing every tower even if there is no observations related to it. 

If had filtered the "empty rows away, I guess I would also loose the generated group row representing the Tower. So that is no option either.

A more generic example would be a table displaying persons with children. You would then like to list all persons even though they had no children (and also without an "empty" child row).

**Comment by cherniavskii** [comment]
@jvskriubakken Thanks for the details!
Looking at the picture in the issue description, it looks like you are using Tree Data feature, not Row Grouping. Can you confirm that?

> A more generic example would be a table displaying persons with children. You would then like to list all persons even though they have no children (and also without an "empty" child row).

Using Tree Data feature, rows that have no children won't be expandable, see https://mui.com/x/react-data-grid/tree-data/
Does it make sense for this use case?

**Comment by jvskriubakken** [comment]
No, I am not using the Tree Data feature. I am using row grouping for sure.

However, I will look into using tree-data if that will solve my case.

**Comment by cherniavskii** [comment]
Please do!
I think Tree data makes more sense in your case, since you have a clear hierarchy of Observations inside a Tower.
If I understand correctly, Tower status is somewhat derived from Observations. If there's no Observations - the Tower status is "Unable to inspect".
This should be possible to reflect with Tree Data as far as I can tell.

For the Row grouping, the group is only created when there are rows inside. There's no way to hide "empty" rows.
You can have rows with missing groups, but not the other way around: https://mui.com/x/react-data-grid/row-grouping/#rows-with-missing-groups

**Comment by cherniavskii** [comment]
I've created this simplified example with Tree Data: https://codesandbox.io/s/competent-river-g2luxo?file=/demo.tsx

**Comment by jvskriubakken** [comment]
Thanks a lot for the example @cherniavskii
