### ISSUE TITLE
[data grid] Invalid Focus Field hard to debug error

### ISSUE THREAD

**Issue by cliedeman** [mui/mui-x#5870]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. Insert a new editing row
2. Use invalid column name
3. Throws confusing error

```
TypeError
Cannot read properties of undefined (reading 'valueFormatter')
```

### Expected behavior 🤔

1. Insert a new editing row
2. Use invalid column name
3. Error column x does not exist

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Forked full crud example
2. Changed field to focus to invalid value 'name1'
3. https://codesandbox.io/s/fullfeaturedcrudgrid-demo-mui-x-forked-61rvcj
4. Click Add

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

39468

**Comment by cherniavskii** [comment]
Hey @cliedeman 
Thanks for raising this!
There's a warning for missing column already:
```
You are calling getValue('name1') but the column `name1` is not defined.
```
After we fix TypeError you mentioned, it should be enough
