### ISSUE TITLE
Ability to resize DataGrid column widths to the max content of their corresponding cells

### ISSUE THREAD

**Issue by TamirCode** [mui/mui-x#5875]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The same thing has been mentioned in other issues however I am not sure if they are exactly same thing and I am not sure where these issues stand and if this has been implemented already or not. Other issues have been closed and confused with maxHeight, which is not what I am here for. Currently this feature does not exist as far as I'm aware https://mui.com/x/react-data-grid/column-dimensions/
https://github.com/mui/mui-x/issues/1241
https://github.com/mui/mui-x/issues/2174

**Feature Request:**
I want the ability to resize or set the column widths to fit the max content, not of the column names, but rather it will find the biggest width of all the rendered values in that column, including the column name itself.

### Examples 🌈

Here is an example where I've manually resized the column widths of one of the demos. They will be max-content considering all its values. The feature I am requesting will do exactly this, it will set the column widths to their cell that has the biggest width
![image](https://user-images.githubusercontent.com/66864667/186109128-d31f5e89-731e-42f3-aa1d-8f8642a80e1f.png)

### Motivation 🔦

In order to write this myself I would have to write a lot of ugly code and calculations, I prefer MUI to add this feature as a function or something. This has gotten 30+ upvotes on other issues and has a lot of similar issues open, it is a common feature that people want, and it makes sense to have it, it seems like a very fundamental feature in my opinion.

**Comment by cherniavskii** [comment]
Hey @TamirCode 
It sounds exactly like https://github.com/mui/mui-x/issues/1241

> They will be max-content considering all its values

Did you consider row virtualization in this case? Not all cells are rendered, therefore it will only be possible to measure those that are rendered.
We will be able to expose a method to trigger auto sizing programatically, but only for the cells and columns that are currently rendered in the viewport

**Comment by cherniavskii** [comment]
> I was also confused because one of the linked issues was this question https://github.com/mui/mui-x/issues/4648
but it was closed because the person said its been worked on in https://github.com/mui/mui-x/pull/4859
though that pull request is actually working on row heights and not column widths from what I've understood

Seems like a misunderstanding on our side.

> and I am not sure if column widths are being worked on or not

Not yet, it's still in our backlog

> Hopefully the header cells will be considered as well :)

I've #1241 to reflect your feedback
