### ISSUE TITLE
Export to csv with cyrillic data causes unicode issue

### ISSUE THREAD

**Issue by AbuSM** [mui/mui-x#5877]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I export to csv my datatable which contains cyrillic data it don't show it correctly
<img width="483" alt="image" src="https://user-images.githubusercontent.com/44544330/186154690-ae819d3c-5b06-447c-bbe2-0855455c450b.png">

### Expected behavior 🤔

Should show all columns with all rows correctly 

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @AbuSM
I cannot reproduce the issue using this demo: https://codesandbox.io/s/silent-worker-3tezok?file=/demo.tsx
I tried both Apple Numbers and Google Sheets to open the exported csv file, but it seems to work just fine.
Can you reproduce it?

**Comment by AbuSM** [comment]
Hi @cherniavskii, I've also tried with Google Sheets and its worked, but doesn't in Microsoft Excel. Is there a way how to fix it for this MS Excel?

**Comment by cherniavskii** [comment]
@AbuSM Can you try setting `utf8WithBom` option to `true`?
You can find more info here https://mui.com/x/react-data-grid/export/#file-encoding

**Comment by AbuSM** [comment]
Thank you for your reply! Yes, I tried with `utf8WithBom` option but unfortunately it didn't help(

**Comment by cherniavskii** [comment]
Hey @AbuSM 
I can reproduce the issue with Microsoft 365 Excel for web:
<img width="519" alt="Screenshot 2022-08-25 at 19 19 14" src="https://user-images.githubusercontent.com/13808724/186729777-291c16f1-6858-4fd1-b727-6b5dbb8dac48.png">

But `utf8WithBom` option seems to fix the issue:
<img width="383" alt="Screenshot 2022-08-25 at 19 20 49" src="https://user-images.githubusercontent.com/13808724/186729956-0bf4f676-ec6d-423b-83d3-cbfb3d4de3d5.png">

Can you double check with this demo: https://codesandbox.io/s/reverent-goldstine-mvg8qx?file=/demo.tsx:427-438

Thanks!

**Comment by cherniavskii** [comment]
I started to think about setting this flag to `true` by default in v6, but then found this https://github.com/mui/mui-x/pull/1695#discussion_r643825846
