### ISSUE TITLE
[question] Dynamic row height with autoHeight

### ISSUE THREAD

**Issue by angel75013** [mui/mui-x#5884]
### Order ID 💳

46943

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

using data grid pro, with large rows per page (ex 100) and grid with autoHeight and getRowHeight={() => 'auto'} cause the last page not being rendered correctly. We have only a few records displayed . In the same time virtualScrollerRenderZone height seems to be calculated correctly to fit all the content, which results in white page. 
The issue is observed only on the last page, and rows per page > 100. 

![image](https://user-images.githubusercontent.com/23128422/186184461-599fc105-1d59-4074-9f14-de3b971a84e6.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Chrome
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    @mui/x-date-pickers:  5.0.0-alpha.1
    @mui/x-license-pro:  5.12.3
    @types/react: ^18.0.9 => 18.0.9
    react: ^18.1.0 => 18.1.0
    react-dom: ^18.1.0 => 18.1.0
    typescript: ^4.5.5 => 4.7.2
```
</details>

**Comment by cherniavskii** [comment]
Hey @angel75013 
What version of the `@mui/x-data-grid-pro` are you using?
I cannot reproduce it with the latest version (5.15.3) https://codesandbox.io/s/wonderful-sun-1ejxj3?file=/demo.tsx

**Comment by angel75013** [comment]
hey @cherniavskii , I tested with the latest version and still got the problem. I think that using ExportToolbar may be the issue.
 <AppDataGrid
      apiRef={apiRef}
      pagination
      sx={{
        '&.MuiDataGrid-root--densityCompact .MuiDataGrid-cell': { py: '8px' },
        '&.MuiDataGrid-root--densityStandard .MuiDataGrid-cell': { py: '15px' },
        '&.MuiDataGrid-root--densityComfortable .MuiDataGrid-cell': { py: '22px' },
      }}
      autoHeight
      columns={columns}
      disableSelectionOnClick
      rows={props.orderLines}
      paginationMode={'server'}
      disableColumnMenu
      onPageChange={(x) => handleFilterChange({ ...filter, page: x })}
      onPageSizeChange={(x) => handleFilterChange({ ...filter, pageSize: x, page: 0 })}
      page={filter.page}
      rowsPerPageOptions={[10, 25, 50, 100]}
      sortModel={filter.sort}
      rowCount={filter.totalCount}
      pageSize={filter.pageSize}
      getRowHeight={() => 'auto'}
      onSortModelChange={(x) => handleFilterChange({ ...filter, sort: x })}
      components={{ Toolbar: ExportToolbar }}
      componentsProps={{ toolbar: { apiRef } }}
    />
    where the export toolbar is
    ```
    export const ExportToolbar = ({ apiRef }: Props) => {
  const onExportClick = () => apiRef.current.exportDataAsCsv();

  return (
    <GridToolbarContainer>
      <Button startIcon={<SaveAltIcon />} onClick={onExportClick}>
        Export
      </Button>
    </GridToolbarContainer>
  );
};```

but still couldn't replicate it in codesandbox. Meanwhile removing it from the grid, removes the display problem.

**Comment by cherniavskii** [comment]
@angel75013 we will need a reproduction demo to be able to take an action.
Let me know if you have a reproduction example.
Thanks!
