### ISSUE TITLE
[DataGridPro] - Replacing hide with columnVisibility prop throws an error

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#5885]
### Order ID 💳

33625

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have replaced the hide prop with columnVisibility prop since hide is already deprecated but it throws an error. See screenshot below. Is there any additional change that should be done other than replacing the prop with columnVisibility?

![image](https://user-images.githubusercontent.com/24405994/186185599-7e0f21f4-4b78-4ed4-9f2c-e9273ccc048d.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @simbahandiane 
To replace `hide` option you will have to use the following:

```tsx
<DataGrid
  initialState={{
    columns: {
      columnVisibilityModel: {
        // Hide columns status and traderName, the other columns will remain visible
        status: false,
        traderName: false,
      },
    },
  }}
/>
```

See the docs for more info: https://mui.com/x/react-data-grid/column-visibility/#initialize-the-visible-columns

**Comment by simbahandiane** [comment]
Oh, I think, the change is easy as just replacing the prop. Thanks for this.

**Comment by cherniavskii** [comment]
@simbahandiane 
I've opened https://github.com/mui/mui-x/pull/5886 to make it less confusing.
Does it help?
