### ISSUE TITLE
[data grid] disableVirtualization state can't be updated via prop

### ISSUE THREAD

**Issue by gidztech** [mui/mui-x#5887]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am trying to conditionally set `disableVirtualization` based on whether I have a panel displayed in the row I have selected (positioned to remain in place as you scroll). The issue I am having is that with virtualization on, it will result in the panel disappearing as the DOM node get recycled. 

If I set `disableVirtualization` prop based on React state, the virtualization functionality doesn't update. The only way I have been able to achieve this is to call `apiRef.current.unstable_disableVirtualization()` when the panel is opened and `apiRef.current.unstable_enableVirtualization()` when closed. However, given the name of the function, it's clearly not meant to be used.

I did some digging and it looks like the virtualization state is set internally in the `GridBody` component, with the prop supplied as the initial value. There is no effect to sync the prop and local state (though I don't necessarily recommend that be the solution).

Is there any reason the functions mentioned above are marked as "unstable"? 

If `disableVirtualization` component prop is not designed to be updated, I think the documentation needs updating to clearly indicate that it's behaving as initial state only.  

**Reference:** https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/base/GridBody.tsx#L34

### Expected behavior 🤔

I expect the virtualization state to update when `disableVirtualization` is updated or I expect a hook with stable functions to update the state

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Context 🔦

https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/base/GridBody.tsx#L34

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 6.15 GB / 12.17 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Managers:
    Apt: 2.0.4 - /usr/bin/apt
    Maven: 3.6.3 - /usr/bin/mvn
    pip3: 20.0.2 - /usr/bin/pip3
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.3.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Virtualization:
    Docker: 20.10.16 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.69.2 - /home/<user>/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/bin/remote-cli/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Java: 1.8.0_292 - /usr/bin/javac
    Perl: 5.30.0 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.8.10 - /usr/bin/python3
  Browsers:
    Chrome: 95.0.4638.54
```
</details>

**Comment by cherniavskii** [comment]
Hey @gidztech 
Indeed, looks like a bug. Here's a reproduction: https://codesandbox.io/s/winter-cloud-5817yc?file=/demo.tsx

**Comment by flaviendelangle** [comment]
> If disableVirtualization component prop is not designed to be updated, I think the documentation needs updating to clearly indicate that it's behaving as initial state only.

If allowing the update of this prop is to hard, we could indeed update the doc and add a clean error inside the code if users try to update ti

**Comment by cherniavskii** [comment]
> If allowing the update of this prop is to hard, we could indeed update the doc and add a clean error inside the code if users try to update it

I don't think it's hard - we're just missing an effect that would synchronize prop value with the state
