### ISSUE TITLE
[pickers] DateTimePicker mui component - onChange is trigger each time it detect minDateTime.

### ISSUE THREAD

**Issue by ccmarcosa** [mui/mui-x#5896]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

onChange event is trigger each time it detect a minDateTime.

### Expected behavior 🤔

onChange should not be triggered every time a minDateTime is detected.

### Steps to reproduce 🕹

Steps:

1. Use two DateTimePicker component to represent Start Date Time and End Date Time
2. The Start Date Time is the minDateTime of the End Date Time Picker component
3. Change the Start Date Time to whatever date you want.
4. When click on the End Date Time component (event icon) the onChange event is trigger, it is because detect the new minDateTime based on the Start Date Time.

### Context 🔦

When the onChange is triggered the values that the End Date Time component had are updated with the minDateTime detected, but what I expect is that the data is not updated automatically and that should only happen if the user update manually the End Date Time picker component.

### Your environment 🌎

<details>
  <summary><code>Environment info</code></summary>

```
  I am using MUI-V5 and react^18 
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates https://github.com/mui/mui-x/issues/5393

Feel free to describe your expected behavior there
I think removing the automatic date change altogether is a good solution here
And provide an easy utility method if users want to automatically move to the closest valid date whenever a date is invalid.

**Comment by flaviendelangle** [comment]
[Reproduction case](https://codesandbox.io/s/date-and-time-pickers-forked-jxdzoi)
