### ISSUE TITLE
[pickers] utils.date is not a function

### ISSUE THREAD

**Issue by DCosti** [mui/mui-x#5900]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After upgrading to latest version of `@mui/x-date-pickers`, v5.0.0-beta.6 and `@mui/lab` at v5.0.0-alpha.96 I am getting the following error in the DateTime component where I am using the LocalizationProvider:
![image](https://user-images.githubusercontent.com/41594981/186618462-354bc931-25ea-4b72-983b-32da8f41a7e7.png)

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-template-forked-u5f0zb?file=/src/App.tsx

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
  npmPackages:
    @emotion/react:  11.10.0
    @emotion/styled:  11.10.0
    @mui/icons-material:  5.8.4
    @mui/lab:  5.0.0-alpha.96
    @mui/material:  5.10.2
    @mui/x-date-pickers:  5.0.0-beta.6
    @types/react:  17.0.48
    react:  17.0.2
    react-dom:  17.0.2
    typescript:  4.7.4
```
</details>

**Comment by flaviendelangle** [comment]
You should import your adapter from `@mui/x-date-pickers` not from `@mui/lab`.
Otherwise you will have an outdated adapter and I can cause all sort of problem.

Does it solve your issue ?

**Comment by DCosti** [comment]
Hi @flaviendelangle ! Thanks for your response. I changed the import for `AdapterDateFns` from `@mui/lab/AdapterDateFns` to `@mui/x-date-pickers`: 
`import { TimePicker, LocalizationProvider, DatePicker, DateTimePicker, AdapterDateFns } from '@mui/x-date-pickers'`
Now the error that I am getting is: `Uncaught [TypeError: Utils is not a constructor`

**Comment by flaviendelangle** [comment]
`import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns`

Like for the lab, we did not export it from the root of the package, otherwise you would have to install `date-fns`, `dayjs`, `moment`, `luxon`, etc... because all the adapters would be in the root.

See https://codesandbox.io/s/mui-x-issue-template-forked-p0jiuj?file=/src/DateTime.js

**Comment by DCosti** [comment]
It works now. Thanks for your help!
