### ISSUE TITLE
[GridApi] Please add getEditingCells() to GridApi.

### ISSUE THREAD

**Issue by TNohSam** [mui/mui-x#5904]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Please add getEditingCells() to GridApi.

( ) => [ { 
id : EditingRowID:GridRowId,
field : EditingRowField:string},
 ... ]

### Examples 🌈

const Rows = [
{id:1, name: 'Jim', age: 26} ,
{id:2, name: 'Sam', age: 25} 
]

If "Jim" cell is in EditMode and "Sam's age" cell is in EditMode, call getEditingCells()
Return "[ {id:1, field:'name'}, {id:2, field:'age'} ] "

### Motivation 🔦

This function is required to control the entire cell being modified at once.

**Comment by cherniavskii** [comment]
Hey @TNohSam 

> This function is required to control the entire cell being modified at once.

Can you elaborate on your use case? It's not clear what you're trying to achieve.
Maybe [controlled editing](https://mui.com/x/react-data-grid/editing/#controlled-mode) is what you're looking for?

**Comment by TNohSam** [comment]
> Hey @TNohSam
> 
> > This function is required to control the entire cell being modified at once.
> 
> Can you elaborate on your use case? It's not clear what you're trying to achieve. Maybe [controlled editing](https://mui.com/x/react-data-grid/editing/#controlled-mode) is what you're looking for?

Thank you @cherniavskii 

Controlled editing is convenient when using the beginning and end of a modification as an external button.
However, I would like to use the default modification method (Double-clicking a cell, Pressing Enter, Backspace or Delete...).

For example, even if a user modifies multiple cells and does not exit EditMode,
pressing the "Save" button will cause all cells in EditMode to change to ViewMode.

The RowID being modified in apiRef.current.state.editRows was found,
 but it was not available because there was no field name.

So I want to get an array of [ {rowIDs and field names} ] in EditMode with apiRef.

**Comment by m4theushw** [comment]
> Controlled editing is convenient when using the beginning and end of a modification as an external button.
However, I would like to use the default modification method (Double-clicking a cell, Pressing Enter, Backspace or Delete...).

You can still use controlled editing and have the default start edit mode and end edit mode interactions. The only difference now is that you have the cell modes available in a prop. If we add a `getEditingCells` method it will return the same thing from the prop.

**Comment by TNohSam** [comment]
> > Controlled editing is convenient when using the beginning and end of a modification as an external button.
> > However, I would like to use the default modification method (Double-clicking a cell, Pressing Enter, Backspace or Delete...).
> 
> You can still use controlled editing and have the default start edit mode and end edit mode interactions. The only difference now is that you have the cell modes available in a prop. If we add a `getEditingCells` method it will return the same thing from the prop.

**Comment by TNohSam** [comment]
> > Controlled editing is convenient when using the beginning and end of a modification as an external button.
> > However, I would like to use the default modification method (Double-clicking a cell, Pressing Enter, Backspace or Delete...).
> 
> You can still use controlled editing and have the default start edit mode and end edit mode interactions. The only difference now is that you have the cell modes available in a prop. If we add a `getEditingCells` method it will return the same thing from the prop.

You're right. I didn't know I could get a "CellModel" with "onCellModelChange" prop. I will close the issue. Thank you.
