### ISSUE TITLE
[TimePicker] Issue

### ISSUE THREAD

**Issue by Rajat-Bhatt** [mui/mui-x#5914]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Here I attached a video link to the current behavior of the time picker. The Time picker automatically gets the current date and time even if I do not select any of these.

https://screenrec.com/share/CEuelVBgSh

### Steps to reproduce 🕹

Steps:

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-forked-r9j9xf) might be a good starting point.
