### ISSUE TITLE
[question] How to use custom component autocomplete in mui datagrid such that it can be controlled using keyboard.

### ISSUE THREAD

**Issue by adharshmk96** [mui/mui-x#5915]
### Order ID 💳

45398

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

How to make the dropdown appear in the MUI autocomplete custom component attached to mui datagrid using keyboard.

I have an app using mui datagrid and it has the autocomplete, 
If I press enter highlighting the autocomplete and then press space the dropdown options are not coming out.

https://codesandbox.io/s/linked-autocompletes-forked-xqs11d?file=/src/App.js

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.79
    @mui/icons-material: ^5.6.2 => 5.6.2
    @mui/lab: ^5.0.0-alpha.80 => 5.0.0-alpha.80
    @mui/material: ^5.6.4 => 5.6.4
    @mui/private-theming:  5.6.2
    @mui/styled-engine:  5.6.1
    @mui/system:  5.6.4
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-data-grid:  5.12.1
    @mui/x-data-grid-pro: ^5.12.1 => 5.12.1
    @mui/x-date-pickers:  5.0.0-alpha.0
    @mui/x-license-pro:  5.12.1
    @types/react: ^18.0.2 => 18.0.2
    react: ^18.0.0 => 18.0.0
    react-dom: ^18.0.0 => 18.0.0
    typescript: ~4.5.4 => 4.5.5
```
</details>

**Comment by cherniavskii** [comment]
Hey @adharshmk96 
When you start editing, Autocomplete input is not focused and therefore doesn't capture keyboard events. You can pass `autoFocus` to fix it:
```tsx
<Autocomplete
  renderInput={(params) => <TextField {...params} autoFocus />}
/>
```

As a side note, you should never mutate `params.row` object, but rather use editing API.
You can read more about creating custom edit components in https://mui.com/x/react-data-grid/editing/#create-your-own-edit-component
Also, you can take a look at one of our custom `Autocomplete` components that we use in our demos: https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid-generator/src/renderer/renderEditCountry.tsx

**Comment by adharshmk96** [comment]
Hey @cherniavskii Thanks for helping out.
Could you also help me on how to make the dropdown list appear when the cell is empty ? 
Right now the cursor is on the input box but I have to press space and then backspace again to see the list of dropdown. ( i now have to begin typing for options to show ) 
here's updated example 
https://codesandbox.io/s/linked-autocompletes-forked-x52wdj?file=/src/App.js

**Comment by cherniavskii** [comment]
@adharshmk96 `openOnFocus` prop is what you're looking for - see Autocomplete API docs here https://mui.com/material-ui/api/autocomplete/
