### ISSUE TITLE
[data grid] Passing Empty Object to groupingColDef Causes Custom Aggregation Function to Exceed Maximum Call Stack

### ISSUE THREAD

**Issue by mschaefer-gresham** [mui/mui-x#5918]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We created a "common" component wrapper around DataGridPremium. The wrapper sets defaults for several DataGridPremium property values that can be overrridden. 

The default value we use for groupingColDef is an empty object since it expects an object when it's being used.

However, this causes a strange error when used in conjunction with aggregation. If the custom aggregation function has a dependency on local state, and groupingColDef is set to an empty object, it causes the the aggregation function to be called repeatedly until the call stack is exceeded.

 Here is a working demo:

https://codesandbox.io/s/aggregationinitialstate-demo-mui-x-forked-5m7x5q?file=/demo.tsx

If groupingColDef is defaulted to undefined, then there is no problem. Likewise, if there is no dependency there is no problem. 

### Expected behavior 🤔

It should be possible to default groupingColDef to an empty object since it expects an object. We currrently provide an empty object as default for initialState, columnVisibilityModel, aggregationFunctions, and aggregationModel with no issue.

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/aggregationinitialstate-demo-mui-x-forked-5m7x5q?file=/demo.tsx

Steps:
1. Click on a row in the grid
2.
3.
4.

### Context 🔦

Aggegration using a common Grid component that wraps DataGridPremium and must provide sensible defaults for DataGridPremium properties. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.20.0 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: 86.0.1
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0 
    @emotion/styled: ^11.10.0 => 11.10.0 
    @mui/base:  5.0.0-alpha.92 
    @mui/envinfo: ^2.0.6 => 2.0.6 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.93 => 5.0.0-alpha.93 
    @mui/material: ^5.9.3 => 5.9.3 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine:  5.8.7 
    @mui/system: ^5.9.3 => 5.9.3 
    @mui/types:  7.1.5 
    @mui/utils:  5.9.3 
    @mui/x-data-grid:  5.15.0 
    @mui/x-data-grid-generator: ^5.15.0 => 5.15.0 
    @mui/x-data-grid-premium: ^5.15.0 => 5.15.0 
    @mui/x-data-grid-pro:  5.15.0 
    @mui/x-license-pro:  5.15.0 
    @types/react: ^18.0.15 => 18.0.15 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.7.4 => 4.7.4 

```
</details>

### Order ID 💳 (optional)

45466

**Comment by flaviendelangle** [comment]
>  it causes the the aggregation function to be called repeatedly until the call stack is exceeded.

I don't have this behavior in your reproduction case
Can you confirm me that the reproduction case is up to date and contain your issue ?

**Comment by mschaefer-gresham** [comment]
Sorry, you need to click on a row. This updates the local state which the aggregation function depends on.

**Comment by flaviendelangle** [comment]
I recommend you to always memoize `groupingColDef`
An update in this object forces us to recompute the grouping rows because it might change the output.

This should fix your problem: https://codesandbox.io/s/aggregationinitialstate-demo-mui-x-forked-oejs51?file=/demo.tsx

**Comment by mschaefer-gresham** [comment]
Thank you. The memoizing groupingColDef does work in the example. Our use case is slightly different though. We have wrapped the grid component in order to provide a "common" grid component with a limited interface. Our issue was related to providing the empty object as a default value for groupingColDef. It's not possible to memoize it in this context. However, we can use undefined as a default value and we don't experience this problem.

Can you confirm that undefined is a valid default value for groupingColDef? If so then there doesn't seem to be an issue here.

**Comment by flaviendelangle** [comment]
> It's not possible to memoize it in this context.

I don't understand why you can't memoize the value, can't you define your empty object outside of your component to make sure it is always the same ?

> Can you confirm that undefined is a valid default value for groupingColDef? If so then there doesn't seem to be an issue here.

Yes, it would be 100% equivalent to not passing anything to the prop
And it's probably slightly better because it's easier to do early opt-out when the prop is not defined at all

**Comment by mschaefer-gresham** [comment]
Well, one of the objectives of the wrapper is to provide default values for the properties it exposes so the code using the wrapper doesn't have define these defaults for unused properties. But using `undefined` is perfect. Thank you.
