### ISSUE TITLE
[pickers] Missing `sx` prop on `CalendarPicker`

### ISSUE THREAD

**Issue by cgarrovillo** [mui/mui-x#5921]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

sx is not a valid prop for CalendarPicker

### Expected behavior 🤔

sx should be an available prop as I can target it inside theming

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Use `<CalendarPicker>` component
2. Add `sx` prop
3. See linting error

### Context 🔦

I'm trying to target the internal CSS of `<CalendarPicker>` but sx is unavailable
![image (1)](https://user-images.githubusercontent.com/6688713/186978149-0ad14740-c09d-4132-9770-fbbba9f95ac5.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Used Chrome


 System:
    OS: macOS 12.5
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3
    @emotion/styled: ^11.9.3 => 11.9.3
    @mui/base:  5.0.0-alpha.91
    @mui/core-downloads-tracker:  5.10.2
    @mui/icons-material: ^5.8.4 => 5.8.4
    @mui/lab: ^5.0.0-alpha.92 => 5.0.0-alpha.92
    @mui/material: ^5.10.2 => 5.10.2
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system:  5.9.2
    @mui/types:  7.1.5
    @mui/utils:  5.9.1
    @mui/x-date-pickers: ^5.0.0-beta.5 => 5.0.0-beta.5
    @types/react: 18.0.15 => 18.0.15
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4
```
</details>

**Comment by LukasTy** [comment]
@cgarrovillo Thank you for opening this issue.
We definitely missed `sx` prop handling on this particular component.
