### ISSUE TITLE
[DataGridPro] prop rowsPerPageOptions seem to be not working properly 

### ISSUE THREAD

**Issue by NicoMoli** [mui/mui-x#5922]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Actually if we want to use this property `rowsPerPageOptions` with DataGridPro, the component in the footer of DataGrid doesn't appear, if we inspect the HTML we can find an empty `<div></div>`.
But, if you use a free version of DataGrid, this feature works properly.

### Expected behavior 🤔

The expected behavior based on oficial documentation is that ComboBox with options to modify the amount of rows per page should be present by default inside a footer of DataGrid.

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi @NicoMoli, thanks for raising this!
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by NicoMoli** [comment]
Hi @DanailH thanks for your response! Here I share with you a codesanbox (https://codesandbox.io/s/data-grid-community-forked-55urz7?file=/src/App.tsx:1145-1163) where I am using DataGrid (free) and DataGridPro, and so you can see that `rowsPerPageOptions` not working on DataGridPro

Screen shot:

![Captura de Pantalla 2022-08-31 a la(s) 10 17 34](https://user-images.githubusercontent.com/24553547/187687664-6259aa5a-7455-4e6b-9b03-9a9f5398f536.png)

Please tell me if you need more information! thanks!

**Comment by MBilalShafi** [comment]
@NicoMoli Are you still facing the issue?
I can see that rows per page could be seen fine in DataGridPro, here's the example: https://stackblitz.com/edit/react-uuc1bb?file=package.json,Demo.tsx
