### ISSUE TITLE
[data grid] Aggregated tree data row columns with non empty aggregated values not overridden by their aggregated values

### ISSUE THREAD

**Issue by kcoop** [mui/mui-x#5923]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The docs [here](https://mui.com/x/react-data-grid/aggregation/#usage-with-tree-data) say the following:

"If the aggregated value is displayed in the grouping row, it will always have priority over the row data.

This means that the data from groups explicitly provided in your dataset will be ignored in favor of their aggregated values."

But after editing the demo values in the associated code sandbox here: https://codesandbox.io/s/43vkyl?file=/demo.tsx to explicitly add a group value for 'pages', like this:

```ts
...
  {
    hierarchy: ['pages' ],
    size: 1105,
    updatedAt: '2022-03-28T11:53:29.298Z',
  },
...
```
the value of the size column for the pages row shows the explicit value 1.1 Kb, rather than the expected summed value 5.7 Kb:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/761190/187004903-d0f8bccd-976e-4d6e-9e00-01041c0c20b9.png">

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
I do have 5.7kb on the codesandbox you sent

![image](https://user-images.githubusercontent.com/3309670/187170808-01611509-ced9-472d-8a64-26683208b62f.png)

That's weird...

**Comment by kcoop** [comment]
Sorry, the code sandbox I sent is the original, without change. Here's a fork with the change made. The difference is that it adds a grouping row element with an explicit value for `size` (that should be overridden by the sum of its children).

https://codesandbox.io/s/naughty-mountain-fb2tto?file=/demo.tsx
