### ISSUE TITLE
rowsCount prop changes, table only updates on next render

### ISSUE THREAD

**Issue by sagi-rika** [mui/mui-x#5940]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Initially, I am setting `rowsCount` to 0. Then, after data returns from the server, I set it to a number (count is a state in my code), but the displayed count is only the number of current "page" (I'm using infinite scroll with server pagination). After another render, no matter how its triggered, the numbers gets changed correctly.

I know that this is a duplicate of https://github.com/mui/mui-x/issues/1614 and its supposedly fixed, but we are using the latest version and the bug still occurs (@mui/x-data-grid-pro@5.16.0)

### Expected behavior 🤔

The displayed rows number should update when the prop updates, and not on next render.w

### Steps to reproduce 🕹

Steps:
1. Initialize a count state with 0
2. Render the data grid, set `rowsCount` to be the state from step 1
3. Update the state to any number
4. See that rowsCount displays the number of visible rows, instead of the passed number.

### Context 🔦

We are trying to display the total number of rows in the server instead of the visible rows count. For example, when passing 10028, I expect to see "100 out of 10028".

As said above, on next render it does indeed display correctly.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Google Chrome
  
  System:
    OS: macOS 11.4
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.1
  npmPackages:
    @emotion/react:  11.10.0 
    @emotion/styled: ^11.10.0 => 11.10.0 
    @mui/base:  5.0.0-alpha.93 
    @mui/core-downloads-tracker:  5.10.1 
    @mui/material: ^5.10.0 => 5.10.1 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine: ^5.10.1 => 5.10.1 
    @mui/styled-engine-sc: ^5.10.0 => 5.10.1 
    @mui/system:  5.10.1 
    @mui/types:  7.1.5 
    @mui/utils:  5.9.3 
    @mui/x-data-grid:  5.16.0 
    @mui/x-data-grid-pro: ^5.16.0 => 5.16.0 
    @mui/x-license-pro:  5.16.0 
    @types/react: ^18.0.17 => 18.0.17 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    styled-components: ^5.3.5 => 5.3.5 
    typescript: ^4.7.4 => 4.7.4
```
</details>

### Order ID 💳 (optional)

We want to buy when it's fixed :)

**Comment by cherniavskii** [comment]
Hey @sagi-rika 
Can you provide an example reproducing the issue?
I cannot reproduce it with this demo: https://codesandbox.io/s/reverent-rui-ny6x8v?file=/demo.tsx

**Comment by sagi-rika** [comment]
I see that its working in your example, yet we made sure that our rowCount is never undefined, and it still isn;t working for us. Could it be related to the fact that we are using infinite scroll, and not pagination?

**Comment by sagi-rika** [comment]
> codesandbox.io/s/reverent-rui-ny6x8v?file=/demo.tsx

I think it has to do with the pro version, since on the regular version it works. Have a look at this demo:

https://codesandbox.io/s/optimistic-curran-6z8fl0?file=/demo.tsx

**Comment by cherniavskii** [comment]
By default `DataGrid` has pagination enabled, while `DataGridPro` doesn't - hence the difference.

We use `rowCount` to calculate the number of available pages. It doesn't make a lot of sense without pagination.
What behaviour do you expect when passing `rowCount` when not using pagination? Or what problem are you trying to solve?

**Comment by sagi-rika** [comment]
On initial load, we are getting the number of rows in the backend (even if I'm displaying 100 rows at first, I get that the total number is 11000).

I wanted to use this number with rowCount, so the user will always know the actual number of rows that exist.

**Comment by cherniavskii** [comment]
I've created a demo with infinite loading and custom `Footer` to override row count: https://codesandbox.io/s/laughing-goldberg-dpp3m3?file=/demo.tsx
Is this what you're looking for?

**Comment by sagi-rika** [comment]
@cherniavskii This is exactly what we needed, thanks!
