### ISSUE TITLE
Can not add a second filter for a

### ISSUE THREAD

**Issue by cesarve78** [mui/mui-x#5942]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When an "any of" filter is added (and the value shown in more than one line), and you click on "add filter" the popover is got closed.

https://www.icloud.com/iclouddrive/043_qoOIRTjtfpjzNgpLmaZSg#mui_grid_pro_x_filter_bug

### Expected behavior 🤔

When "add filter" is clicked the popover should stay open and add a new row to create the new filter.

### Steps to reproduce 🕹

Link to live example:
https://www.icloud.com/iclouddrive/043_qoOIRTjtfpjzNgpLmaZSg#mui_grid_pro_x_filter_bug

Steps:
1. in the grid go to a column with statuses
2. create an "any of" filter for the column with more than the 3 possible values
3. without close the filter popover click on "add filter"
4. the popover now is closed

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser:
    Google Chrome
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 12.22.6 - ~/.nvm/versions/node/v12.22.6/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v12.22.6/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: 102.0
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.8.2 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base:  5.0.0-alpha.92 
    @mui/codemod: ^5.9.3 => 5.9.3 
    @mui/core-downloads-tracker:  5.10.1 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.94 => 5.0.0-alpha.94 
    @mui/material: ^5.10.0 => 5.10.1 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine:  5.10.1 
    @mui/styled-engine-sc: ^5.10.0 => 5.10.1 
    @mui/styles: ^5.9.3 => 5.9.3 
    @mui/system: ^5.10.0 => 5.10.1 
    @mui/types:  7.1.5 
    @mui/utils: ^5.9.3 => 5.9.3 
    @mui/x-data-grid: ^5.15.2 => 5.15.2 
    @mui/x-data-grid-pro: ^5.15.2 => 5.15.2 
    @mui/x-date-pickers: ^5.0.0-beta.5 => 5.0.0-beta.5 
    @mui/x-license-pro:  5.15.0 
    @types/react: ^17.0.4 => 17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.5 => 5.3.5 
    typescript: ^4.2.4 => 4.7.4 

```
</details>

### Order ID 💳 (optional)

[Order #45855] (June 17, 2022)

**Comment by alexfauquette** [comment]
Is it the same problem as #4116 ?

**Comment by cesarve78** [comment]
It is sorry

**Comment by alexfauquette** [comment]
No problem, I close this one to avoid duplicate
