### ISSUE TITLE
[data grid] custom column header

### ISSUE THREAD

**Issue by m-zaharieva** [mui/mui-x#5946]
Hello, 
I want to add a new icon in each column's header to reset applied filter and I prefer it to look like this - reset icon to be after the filter icon: 
![gh-1](https://user-images.githubusercontent.com/22787907/187199444-413d24b0-8965-460f-ab8d-75bf00fb02a7.jpg)

Currently, I manage to add it by using renderHeader property of the column. But the required icon is located right after the header name. 
![gh-2](https://user-images.githubusercontent.com/22787907/187200836-7ca1b202-f067-4dba-821b-a76a09331c84.jpg)

And that simple issue is kind of tricky since I cannot swap their places. 
The only way I could think of is by adding the filter button to my custom header, hide the default and write down the logic for filtering myself. This, on the other hand, require to customize the menu panel so I can add the filter option again.  
 
Is there a better way to reorder header components? 

Thank you!

**Comment by alexfauquette** [comment]
Maybe by creating a custom [`GridColumnHeaderFilterIconButton`](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/columnHeaders/GridColumnHeaderFilterIconButton.tsx)

```jsx
components={{
	ColumnHeaderFilterIconButton: CustomColumnHeaderFilterIconButton
}}
```

Instead of returning an  icon button, you could return the default and your custom button

**Comment by m4theushw** [comment]
Following @alexfauquette's idea I created a CodeSandbox with an example: https://codesandbox.io/s/determined-paper-nfxsz0?file=/demo.tsx:0-2626

```tsx
import { DataGrid, GridColumnHeaderFilterIconButton } from "@mui/x-data-grid";

const CustomColumnHeaderFilterIconButton = (props) => {
  return (
    <React.Fragment>
      <IconButton onClick={...} size="small" tabIndex={-1}>
        <FilterAltOffIcon fontSize="small" />
      </IconButton>
      <GridColumnHeaderFilterIconButton {...props} />
    </React.Fragment>
  );
};

<DataGrid
  components={{
    ColumnHeaderFilterIconButton: CustomColumnHeaderFilterIconButton
  }}
/>
```

To add the action for the new button you can [modify](https://mui.com/x/react-data-grid/filtering/#controlled-filters) the `filterModel` prop or call `apiRef.current.setFilterModel()`.
