### ISSUE TITLE
[MobileDateTimePicker] showToolbar prop not working correctly

### ISSUE THREAD

**Issue by andriipashko** [mui/mui-x#5959]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm trying to hide only Toolbar with `showToolbar={false}` but this prop hides also tabs even if I add `hideTabs={false}`

### Expected behavior 🤔

`showToolbar={false}` hides only Toolbar

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
The tabs are currently part of the toolbar from what I saw, so the behavior make sense to me
Could this be improved using the component slots instead of a basic boolean ?
