### ISSUE TITLE
[data grid] Handling valueFormetter and renderer for grouped columns

### ISSUE THREAD

**Issue by matandro** [mui/mui-x#5964]
### Order ID 💳

47166

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Not a problem, more of an approach.

We are not sure what is the best way to handle custom renders and formatters when using grouping.
In those cases we get empty renders, is there a way to know that the row is a grouped row?

e.g.
```js
// Before - crash as value is undefined and cannot used toFixed
valueFormatter: (params) => Number((params.value).toFixed(2)),
// After 
valueFormatter: (params) => (params.value && Number((params.value).toFixed(2))),
```

What about renders? same idea? do I always need to check for params.value being defined?
Is there a way to ask "am I a grouped row?"

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
> Is there a way to ask "am I a grouped row?"

The two following code are different when using tree data because with tree data some groups can be provided as real rows.
Depending on which behavior you want to have for these real groups, you can pick one or the other.

```tsx
valueFormatter: (params) => {
  const rowNode = apiRef.current.getRowNode(params.id)!
  if (rowNode.children.length) {}
}
```


```tsx
valueFormatter: (params) => {
  const rowNode = apiRef.current.getRowNode(params.id)!
  if (rowNode.children.length && rowNode.isAutoGenerated) {}
}
```

We could add the `rowNode` to the `params` here to avoid having to use the `apiRef` (@m4theushw)
The doc about how to use the `apiRef` is [here](https://mui.com/x/react-data-grid/api-object/#use-it-outside-the-grid)

**Comment by matandro** [comment]
Thanks, this makes sense (the auto generated + children relationship).
Last thing is that it seems that `params` does have a `params.rowNode` for itself. is there any reason not to use it directly?
I did use the `apiRef` version of it to get the `rowNode`'s of other rows when I needed to grab children values.

**Comment by flaviendelangle** [comment]
> Last thing is that it seems that params does have a params.rowNode for itself. is there any reason not to use it directly?

In `valueFormatter` you should not have it (if you have then our typing is wrong or I misread it)
In `valueGetter` and `renderCell` you should have it, feel free yo use it :+1:
