### ISSUE TITLE
[pickers] `@mui/x-date-pickers-pro` themeAugmentation does not include `@mui/x-date-pickers` types

### ISSUE THREAD

**Issue by lenzi-erickson** [mui/mui-x#5965]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I only use the `@mui/x-date-pickers-pro` package with this line `import type {} from "@mui/x-date-pickers-pro/themeAugmentation";` then I get errors when trying to modify `MuiClockPicker` in the theme file: `Object literal may only specify known properties, and 'MuiClockPicker' does not exist in type 'Components<Omit<Theme, "components">>'.`

If I use the `@mui/x-date-pickers-pro` and `@mui/x-date-pickers` packages with this line `import type {} from "@mui/x-date-pickers-pro/themeAugmentation";` and this line `import type {} from "@mui/x-date-pickers/themeAugmentation";` then I do not get errors when I modify `MuiClockPicker` in the theme file.

### Expected behavior 🤔

(If I understand the packages correctly, please let me know if I am wrong!) We should be able to use only the @mui/x-date-pickers-pro package and exclude the @mui/x-date-pickers package when using the pro plan.

If I only use the `@mui/x-date-pickers-pro` package with this line `import type {} from "@mui/x-date-pickers-pro/themeAugmentation";` then I should be able to modify `MuiClockPicker` in the theme file without getting typescript errors or using the `@mui/x-date-pickers` package.

### Steps to reproduce 🕹

1. Create a project using @mui/x-date-pickers-pro and typescript (do not use @mui/x-date-pickers)
2. Add `import type {} from "@mui/x-date-pickers-pro/themeAugmentation";` to theme file
3. Modify styles for MuiClockPicker using styleOverrides
```
    MuiClockPicker: {
      styleOverrides: {
        root: {
          position: "relative",
        },
      },
    },
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 17.9.0 - /usr/local/bin/node
    Yarn: 3.2.3 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Edge: Not Found
    Firefox: 103.0
    Safari: 15.6.1
```
</details>

### Order ID 💳 (optional)

We pay for the PRO account, but I don't know how to find my order ID.

**Comment by lenzi-erickson** [comment]
I found this [in the docs](https://mui.com/x/react-date-pickers/getting-started/#typescript):

> You don't have to import the theme augmentation from both @mui/x-date-pickers and @mui/x-date-pickers-pro when using @mui/x-date-pickers-pro. Importing it from @mui/x-date-pickers-pro is enough.

So it appears my assumptions are correct. Maybe some types are missing in the -pro package?

**Comment by LukasTy** [comment]
@lenzi-erickson You are correct on the existing misunderstanding.
Documentation states one thing, while actual `themeAugmentation` in `pro` package does not include types from non-pro package.

**Comment by lenzi-erickson** [comment]
> @lenzi-erickson You are correct on the existing misunderstanding. Documentation states one thing, while actual `themeAugmentation` in `pro` package does not include types from non-pro package.

Thank you so much for the speedy resolution!
