### ISSUE TITLE
[DataGridPro] Warnings in multiple places: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by cbichis** [mui/mui-x#5968]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi, I am noticing multiple annoying occurences for Datagrid of unique key prop warning (see below)

Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information. Tooltip@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:75:435458 GridColumnHeaderTitle@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:46027 div div div div GridGenericColumnHeaderItem@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:47233 GridColumnHeaderItem@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:48632 div 4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:2:11811 div 4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:2:11811 GridColumnHeadersInner@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:55716 div 4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:2:11811 GridColumnHeaders@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:54936 DataGridProColumnHeaders@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:57129 div 4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:2:11811 GridMainContainer@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:75:40759 GridBody@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:75:49392 ErrorBoundary@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:75:40848 GridErrorHandler@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:75:41374 div 4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:2:11811 GridRoot@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:75:39396 GridContextProvider@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:75:20426 DataGridPro@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:65467 ProductsOnCategoryBackendPage@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:89366 BackendApp@https://project/backendV3/js/backendV3.js?34f8429ebe382dd4d3d4:102:90745

Also, this on occurs when clicking the selector for number of rows (pageSize):

 Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
TrapFocus@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:389735
div
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
Portal@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:120591
ModalUnstyled@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:394065
Modal@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:400095
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
Popover@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:402283
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
Menu@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:405845
SelectInput@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:411677
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
div
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
InputBase@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:75215
Select@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:416533
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
div
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
Toolbar@https://project/backendV3/js/backendV3.js?0887e481865157f72869:102:5740
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
div
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
TablePagination@https://project/backendV3/js/backendV3.js?0887e481865157f72869:102:10210
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
GridPagination@https://project/backendV3/js/backendV3.js?0887e481865157f72869:102:12484
div
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
GridFooterContainer@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:453867
GridFooter@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:454150
div
GridFooterPlaceholder@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:50409
ErrorBoundary@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:40848
GridErrorHandler@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:41374
div
4880/withEmotionCache/<@https://project/backendV3/js/backendV3.js?0887e481865157f72869:2:11811
GridRoot@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:39396
GridContextProvider@https://project/backendV3/js/backendV3.js?0887e481865157f72869:75:20426
DataGridPro@https://project/backendV3/js/backendV3.js?0887e481865157f72869:102:65467
ProductsOnCategoryBackendPage@https://project/backendV3/js/backendV3.js?0887e481865157f72869:102:89366
BackendApp@https://project/backendV3/js/backendV3.js?0887e481865157f72869:102:90765

### Expected behavior 🤔

No warnings on console.

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Context 🔦

Just doing dummy setup of some datagrids.

The configuration is quite dummy:

columns = [
   {
      //key: 'id',
      field: 'id',
      headerName: 'ID Produs',
      flex: 1,
      headerAlign: 'center',
      align: 'center'
   },
   {
      //key: 'photo',
      field: 'photo',
      headerName: 'Foto',
      flex: 1,
      headerAlign: 'center',
      align: 'center',
      renderCell: (params) => (
         (params.value == null) ? '' : <img alt="produs" src={'/upload/thumbs/5/' + params.value}/>
      ),
   },
   {
      //key: 'sku',
      field: 'sku',
      headerName: 'SKU',
      flex: 1,
      headerAlign: 'center',
      align: 'center',
   },
   {
      //key: 'name',
      field: 'name',
      headerName: 'Nume',
      flex: 1,
      headerAlign: 'center',
      align: 'center',
   },
   {
      //key: 'dimension',
      field: 'dimension',
      headerName: 'Dimensiuni',
      flex: 1,
      headerAlign: 'center',
      align: 'center',
   },
   {
      //key: 'fragility',
      field: 'fragility',
      headerName: 'Fragilitate',
      flex: 1,
      headerAlign: 'center',
      align: 'center',
      //editable: true
   },
   {
      //key: 'price',
      field: 'price',
      headerName: 'Pret',
      flex: 1,
      headerAlign: 'center',
      align: 'center',
   },
   {
      //key: 'stock',
      field: 'stock',
      headerName: 'Stoc catalog',
      flex: 1,
      headerAlign: 'center',
      align: 'center',
   },
   {
      //key: 'actions',
      field: 'actions',
      type: 'actions',
      headerName: 'Actiuni',
      getActions: (params) => [
         <GridActionsCellItem icon={<VisibilityIcon title="Vezi produs" color="primary" key="view" />} onClick={(e) => {window.location.href = '/admin/product/edit-form/id/' + params.id}} label="Vezi produs" />,
      ]
   }
];

<DataGridPro
   rows={this.state.data}
   columns={this.columns}
   pagination
   pageSize={this.state.pageSize}
   rowsPerPageOptions={[25, 50, 100, 200, 500]}
   onPageSizeChange={(pageSize) => this.setState({pageSize: pageSize})}
   autoHeight

   getRowClassName={(params) =>
      params.indexRelativeToCurrentPage % 2 === 0 ? 'bg-light' : 'bg-white'
   }

   experimentalFeatures={{ newEditingApi: true }}
   processRowUpdate={this.updateRow}
   onProcessRowUpdateError={this.updateRowError}
/>

### Your environment 🌎

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 104.0
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.4 
    @emotion/styled: ^11.10.0 => 11.10.4 
    @mui/base:  5.0.0-alpha.95 
    @mui/core-downloads-tracker:  5.10.3 
    @mui/icons-material: ^5.8.4 => 5.10.3 
    @mui/material: ^5.10.0 => 5.10.3 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine: ^5.10.0 => 5.10.3 
    @mui/system:  5.10.3 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.3 
    @mui/x-data-grid:  5.16.0 
    @mui/x-data-grid-pro: ^5.16.0 => 5.16.0 
    @mui/x-license-pro: ^5.16.0 => 5.16.0 
    @types/react:  18.0.18 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.7.4 => 4.8.2 

### Order ID 💳 (optional)

48905

**Comment by DanailH** [comment]
Hi @cbichis, thanks for raising this!
I'm sorry but what you have provided doesn't really help us identify the issue.
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by shrikantpardhi** [comment]
Same issue when  we use DataGrid. 

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `GridRow`. See https://reactjs.org/link/warning-keys for more information.
    at IconButton (http://localhost:3000/static/js/2.chunk.js:34335:85)
    at GridRow (http://localhost:3000/static/js/2.chunk.js:84490:24)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridVirtualScrollerRenderZone (http://localhost:3000/static/js/2.chunk.js:95059:25)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridVirtualScrollerContent (http://localhost:3000/static/js/2.chunk.js:94986:25)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridVirtualScroller (http://localhost:3000/static/js/2.chunk.js:94920:25)
    at DataGridVirtualScroller (http://localhost:3000/static/js/2.chunk.js:83714:25)
    at div
    at AutoSizer (http://localhost:3000/static/js/2.chunk.js:83921:24)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridMainContainer (http://localhost:3000/static/js/2.chunk.js:89550:105)
    at GridBody (http://localhost:3000/static/js/2.chunk.js:85199:24)
    at ErrorBoundary (http://localhost:3000/static/js/2.chunk.js:83768:173)
    at GridErrorHandler (http://localhost:3000/static/js/2.chunk.js:85313:24)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at GridRoot (http://localhost:3000/static/js/2.chunk.js:89714:106)
    at GridContextProvider (http://localhost:3000/static/js/2.chunk.js:95436:21)
    at DataGrid (http://localhost:3000/static/js/2.chunk.js:81496:89)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at Box (http://localhost:3000/static/js/2.chunk.js:76268:74)
    at div
    at http://localhost:3000/static/js/2.chunk.js:969:73
    at Box (http://localhost:3000/static/js/2.chunk.js:76268:74)
    at ExamsPage (http://localhost:3000/static/js/main.chunk.js:3417:75)
    at Routes (http://localhost:3000/static/js/2.chunk.js:171488:24)
    at Router (http://localhost:3000/static/js/2.chunk.js:171413:30)
    at BrowserRouter (http://localhost:3000/static/js/2.chunk.js:170139:23)
    at ThemeProvider (http://localhost:3000/static/js/2.chunk.js:71776:24)
    at App (http://localhost:3000/static/js/main.chunk.js:126:73)
```

and My code is 
```
<DataGrid
          rows={rows}
          columns={columns}
          pageSize={5}
          rowsPerPageOptions={[5]}
          checkboxSelection
          disableSelectionOnClick
          experimentalFeatures={{ newEditingApi: true }}
        />
```

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
