### ISSUE TITLE
[DataGrid] Header quick filter

### ISSUE THREAD

**Issue by cbichis** [mui/mui-x#5973]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi,

I think the current way of filtering is complicated for end user. Coming from jQuery I noticed how much the end user likes the direct filtering from header columns (no modals to open, less clicks). By comparing with current MUIX Datagrid filtering this looks much better for the most used cases.

I am aware I can create a custom component for this. However, I think this is a feature which is really needed for a large number of customers.

The current way to filter should stay of course. But quick filter is a must to.

![header-sample](https://user-images.githubusercontent.com/6471173/187658634-3b311646-15f0-4e85-9492-a8b9c1da171a.png)

### Order ID 💳 (optional)

48905

**Comment by DanailH** [comment]
Hi @cbichis, thanks for raising this!
I struggle to understand what you are requesting here. There is a quick filter that we added recently to the Data Grid. You can check it here -> https://mui.com/x/react-data-grid/filtering/#quick-filter

**Comment by cbichis** [comment]
The easiest to use for end-user are filter controls on column headers (a filter boolbar basically). See on the image I posted.

See also this: http://www.guriddo.net/demo/bootstrap/searching/toolbar/index.html

The quick filter you mentioning I find hard to use.

**Comment by flaviendelangle** [comment]
@DanailH for me its the header filtering in #3719.
The behavior of those column-based filters could be either operator filter or quick filter, but in the screen provided we clearly see that there is one filter input per column in the header.

**Comment by cbichis** [comment]
@DanailH basically we need filters easy to use. Most of users (not the developers) using datagrids need mostly a tool to do very easy a simple filtering not complicated filterings.

The MUIX Datagrid current Quick filter is for experts not for most of users. Also the normal filter is harder to use as requires more clicks to set and also a lot of attention when setting up the filters. I suggest to review what jqGrid is doing in terms of filtering, they are much more oriented to normal users...

**Comment by cbichis** [comment]
Thanks, it will be used a lot. I'll come back with feedback.
