### ISSUE TITLE
[data grid] DataGridPremuim using Aggregation and Row Grouping ignores hide prop in Column Definitions

### ISSUE THREAD

**Issue by Nick6464** [mui/mui-x#5985]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

All columns are shown that are in the Column definition regardless of "hide: true" being present.

### Expected behavior 🤔

Columns with hide: true should hide as they do for a standard DataGrid

### Steps to reproduce 🕹

Steps:

1. Sandbox the Aggregation and Row grouping example
2. Add "hide: true," to the title object in the Column Definition 

https://codesandbox.io/s/quirky-bose-ocq4tu?file=/demo.js

### Context 🔦

I want to have some columns be in the column definition so a user can chose to unhide them if they need to see a field that isn't used as often.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.70)
  npmPackages:
    @emotion/react:  11.10.0
    @emotion/styled: ^11.3.0 => 11.8.1
    @mui/base:  5.0.0-alpha.74
    @mui/icons-material: ^5.0.1 => 5.5.1
    @mui/lab: ^5.0.0-alpha.48 => 5.0.0-alpha.75
    @mui/material: ^5.0.1 => 5.5.3
    @mui/private-theming:  5.5.3
    @mui/styled-engine:  5.5.2
    @mui/styles: ^5.0.1 => 5.5.3
    @mui/system:  5.5.3
    @mui/types:  7.2.0
    @mui/utils:  5.10.3
    @mui/x-data-grid:  5.16.0
    @mui/x-data-grid-generator: ^5.16.0 => 5.16.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.16.0
    @mui/x-data-grid-pro:  5.16.0
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.0
    @mui/x-license-pro:  5.16.0
    @types/react:  17.0.43
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```

Chrome is being used, so odd that it hasn't come through?
</details>

**Comment by flaviendelangle** [comment]
Duplicates https://github.com/mui/mui-x/issues/5967
