### ISSUE TITLE
[data grid] Rows do not render after changing data and resizing with animation.

### ISSUE THREAD

**Issue by Marcin59** [mui/mui-x#5987]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Added Accordion to DataGrid flex container(no difference if it is passing as a Toolbar component or it is above DataGrid)  and unfolded with animation after change data (rows parameter) causes lower rows don’t render. I tried apiRef.forceUpdate() after animation, but lower rows still don’t render.

Example(https://stackblitz.com/edit/react-ts-kqudbv?file=App.tsx):

https://user-images.githubusercontent.com/53148689/187897109-fdffbed1-3e4a-4b45-8f58-a027ab1cd890.mp4

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open: https://stackblitz.com/edit/react-ts-kqudbv?file=App.tsx.
2. Open Accordion.
3. Click “Change rows”
4. Hide Accordion
5. Lower rows don't render and appear after scrolling.

### Context 🔦

I ran into the problem when I tried to use Accordion in a custom toolbar.

### Order ID 💳 (optional)

240359

**Comment by m4theushw** [comment]
When the grid is resized, the `resize` event is fired and only the new width is used in https://github.com/mui/mui-x/blob/7e3c97ac7de7a283be7f79f4a7437ee4867373de/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx#L221-L223

For the grid to react also to height changes, it's necessary to store the container height in the state, similar to what we have for `containerWidth`. The following diff is an example of how this could be done:

```diff
diff --git a/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx b/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
index 4b720107f..493c62fdb 100644
--- a/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
+++ b/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
@@ -113,6 +113,7 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
   const prevRenderContext = React.useRef<GridRenderContext | null>(renderContext);
   const scrollPosition = React.useRef({ top: 0, left: 0 });
   const [containerWidth, setContainerWidth] = React.useState<number | null>(null);
+  const [containerHeight, setContainerHeight] = React.useState<number>(null);
   const prevTotalWidth = React.useRef(columnsTotalWidth);
 
   const getNearestIndexToRender = React.useCallback(
@@ -161,7 +162,7 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
 
     const lastRowIndex = rootProps.autoHeight
       ? firstRowIndex + currentPage.rows.length
-      : getNearestIndexToRender(top + rootRef.current!.clientHeight!);
+      : getNearestIndexToRender(top + containerHeight);
 
     let hasRowWithAutoHeight = false;
     let firstColumnIndex = 0;
@@ -216,10 +217,12 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
 
   React.useEffect(() => {
     setContainerWidth(rootRef.current!.clientWidth);
+    setContainerHeight(rootRef.current!.clientHeight!);
   }, [rowsMeta.currentPageTotalHeight]);
 
   const handleResize = React.useCallback<GridEventListener<'resize'>>((params) => {
     setContainerWidth(params.width);
+    setContainerHeight(params.height);
   }, []);
 
   useGridApiEventHandler(apiRef, 'resize', handleResize);
```
