### ISSUE TITLE
[DataGridPremium] Multi filtering on premium data grid 

### ISSUE THREAD

**Issue by toinhao1** [mui/mui-x#5989]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

One filter filled out:

![Screenshot 2022-09-01 at 14 35 50](https://user-images.githubusercontent.com/41380451/187915074-c4d9c835-174b-433b-af38-bdb417ff543e.png)

When clicking "Add Filter" all rows disappear before filling out the filter inputs.

![Screenshot 2022-09-01 at 14 36 21](https://user-images.githubusercontent.com/41380451/187915171-d2868e54-af0b-413e-905e-e129106325d6.png)

### Expected behavior 🤔

The new filter field would not take effect until all fields of the filter are filled.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/customfilterpanelposition-demo-mui-x-forked-cdbxjb?file=/demo.tsx
Pro Grid: https://codesandbox.io/s/3hky0w?file=/demo.tsx

Steps:
1. Fill in first filter
2. Click Add Filter
3. All rows disappear

### Context 🔦

Have multiple filters with a good user experience.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

46557

**Comment by alexfauquette** [comment]
The problem also occurs also on Pro component.

The problem comes from the new filtering engine that do not manage the early return when the filter item is not activated
