### ISSUE TITLE
Selection of grouped row should behave as the parent selector for child values

### ISSUE THREAD

**Issue by matandro** [mui/mui-x#5995]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently when pressing the checkbox on a grouped row it only marks that row which is very confusing.

What I feel is a correct behavior:
When pressing the checkbox select on the group parent, it should select all children. When unselecting it should unselect all children. There is a question about the best mark and behavior when only some of the child rows are selected, I would go for not marked, same as checkbox column current behavior, to keep it consistent.

Another way to handle it:
Block selection on auto generated rows. This removed the confusion but reduces usefulness.

Workaround:
Implement a custom selection model to maintain that logic.
Point of interaction:
1. when grouping changes: each auto generated group row should get it state set by the state of it's children
2. when selection model changes: if a child is selected, its parent groups need to be checked. if a parent is selected it children need to be updated.

### Motivation 🔦

This feature is mainly to keep the behavior of checkbox selection consistent with the parent. Our clients are confused why selecting a group doesn't select its children. Is the row is collapsed you don't really see that nothing is checked unless you actively look at the counter in the button.

### Order ID 💳 (optional)

47166

**Comment by flaviendelangle** [comment]
Duplicates #4248

We discussed the topic and we fully agree that users should be able to easily enable children selection when selecting a group.
