### ISSUE TITLE
Can we set data-grid's table cell width dynamically based on the width of the text inside of?

### ISSUE THREAD

**Issue by ClickHere0521** [mui/mui-x#5998]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The question is: **_Can we set data-grid's table cell width dynamically based on the width of the text inside of?_**

I do believe that `text-overflow: ellipsis` is a good approach to show the table but some people don't feel comfortable with that kind of clipping...

They want to show all the contents of data-table apparently instead of clipped texts.

Now the text shown in a red rectangular has a larger width than commodity column's width.

So, can we make commodity column's width dynamically? Ideally, its width can be set as larger than the text in the red rectangular's width.

Any thoughts?

![image](https://user-images.githubusercontent.com/78680958/188027913-5b87f737-3094-4653-95bc-78cbb2d5f4eb.png)

### Examples 🌈

Expected behavior:

![image](https://user-images.githubusercontent.com/78680958/188028820-0e4f71ca-253a-4beb-b2f5-f692c58ff15d.png)

**Comment by flaviendelangle** [comment]
Duplicates #1241

**Comment by flaviendelangle** [comment]
The `maxWidth` does not solve your problem.

As you saw, you have custom solutions trying to work around your problem.
But those are users solutions and we don't take responsibility for there compatibility with the rest of the feature, so I would advise you to test it before using it in production.

We will probably support a built-in solution in the future.
I am closing your issue to keep a single discussion about this future solution on #1241 :+1:
