### ISSUE TITLE
[pickers] Missing clarity/documentation regarding connection between `openTo` and `views` props

### ISSUE THREAD

**Issue by nrathi** [mui/mui-x#6010]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

<img width="347" alt="image" src="https://user-images.githubusercontent.com/3291034/188170857-6296a125-02a0-4f6d-9409-6405f8644b26.png">

This is the behavior for both `openTo="month"` and `openTo="year"`.

### Expected behavior 🤔

The views should be different.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/reverent-sanne-n1mdf7?file=/demo.tsx

Steps:
1. Try `openTo="month"`
2. Try `openTo="year"` 
3. Observe they are the same

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Could we add a running time warning when `openTo` is defined to a value not present in the views ?
