### ISSUE TITLE
[DataGrid] GridToolbarFilterButton component don't work with prop "size" set to "medium" | "large"

### ISSUE THREAD

**Issue by ImReyon** [mui/mui-x#6013]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

GridToolbarFilterButton is sticking to default small even when passing different size prop .

### Expected behavior 🤔

GridToolbarFilterButton should resize accordingly to the passed "size" prop

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Context 🔦

got some hints from #2083 which was fixed in #2084 ,somehow overriding is not working for the size prop .

### Your environment 🌎

System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.70)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base:  5.0.0-alpha.95
    @mui/core-downloads-tracker:  5.10.3
    @mui/icons-material: ^5.10.3 => 5.10.3
    @mui/material: ^5.10.3 => 5.10.3
    @mui/private-theming:  5.10.3
    @mui/styled-engine:  5.10.3
    @mui/system:  5.10.3
    @mui/types:  7.2.0
    @mui/utils:  5.10.3
    @mui/x-data-grid: ^5.16.0 => 5.16.0
    @types/react:  18.0.18
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript:  4.8.2

**Comment by ImReyon** [comment]
looks like I need to use "componentProps" prop and under "button" key I have to pass the "ButtonBase" props . It got me off because of the other GridToolbarButtons like "Export" | "Columns" which take "ButtonBase" props directly in the Component .

**Comment by dangnhdev** [comment]
> looks like I need to use "componentProps" prop and under "button" key I have to pass the "ButtonBase" props . It got me off because of the other GridToolbarButtons like "Export" | "Columns" which take "ButtonBase" props directly in the Component .

For anyone checking this issue:
```tsx
 <GridToolbarFilterButton componentsProps={{button: {size: 'medium'}}}/>
```
