### ISSUE TITLE
[TreeView] Add checkbox support

### ISSUE THREAD

**Issue by cpdwyer** [mui/mui-x#6019]
Thanks for the Component, it works really well. Unfortunately I have come across on problem in the implementation which I can't seem to find a workaround for.

- [X] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I am looking to use the TreeView / TreeItem components with a check box on each row. Ideally I would like a prop to suppress the event that expands and collapses the tree if the CheckBox is clicked. Or maybe a prop to enable a checkbox with a prop to set the value and a call back when clicked that also avoids the list toggle.

At the moment when a check box is toggled it also expands and collapses the tree when the node has children. 

Thank You.

## Examples 🌈

![image](https://user-images.githubusercontent.com/18459691/64793229-a56ec980-d572-11e9-80d9-7c464ac4cde4.png)

This is the current code...
```jsx
const checkBoxClicked = (event, checked, id) => {
   setOrgStructureElement(checked, id, selected, orgStructure);
};

const createOrgStructureLevel = orgStructureElement => {
   const elements = [];

    orgStructureElement.forEach((v, k) => {
      const { id, children } = v;
      if (k.length !== 0) {
        const label = (
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <Checkbox
              id={`checkbox-${k}`}
              className={classes.globalFilterCheckbox}
              checked={selected.has(id)}
              onChange={(event, checked) => checkBoxClicked(event, checked, id)}
              color="primary"
            />
            <Typography variant="caption">{k}</Typography>
          </div>
        );
        elements.push(
          children && children.length > 0 ? (
            <TreeItem key={id} nodeId={id} label={label}>
              {createOrgStructureLevel(children)}
            </TreeItem>
          ) : (
            <TreeItem key={id} nodeId={id} label={label} />
          ),
        );
      } else if (children) {
        elements.push(createOrgStructureLevel(children));
      }
    });
    return elements;
  };

  const handleExpanded = (nodeId, nodeExpanded) => {
    // cache expanded nodes
    if (nodeExpanded) {
      addOpenOrgStructurePanel(nodeId);
    } else {
      removeOpenOrgStructurePanel(nodeId);
    }
  };

  return (
    <TreeView
      defaultExpanded={openOrgStructurePanels}
      onNodeToggle={(nodeId, nodeExpanded) => handleExpanded(nodeId, nodeExpanded)}
      defaultCollapseIcon={<ExpandMoreIcon />}
      defaultExpandIcon={<ChevronRightIcon />}>
      {orgStructure.length !== 0 ? createOrgStructureLevel(orgStructure) : null}
    </TreeView>
  )
};
```

## Motivation 🔦
see above

**Comment by Shivraj97** [comment]
> Added auto selection for parent when children are selected. And the same for deselection. Improved a bit search for selected node. @dnquang1996vn Thank you for your example! https://codesandbox.io/s/edeyu

Hi @hamsishe  Can you please tell me what to do when I don't have a root parent node? I mean the structure of data is an array of objects and not an object. I don't want the Parent label to render

**Comment by Kavan72** [comment]
Guys, any update here, i would like this see checkbox tree with some advance features

**Comment by MrPoint1400** [comment]
+1

**Comment by srgg** [comment]
+1

**Comment by zhangjianrencai** [comment]
> Added auto selection for parent when children are selected. And the same for deselection. Improved a bit search for selected node. @dnquang1996vn Thank you for your example! https://codesandbox.io/s/edeyu

@hamsishe  Do you know how to resolve this issue when the data's length === 200, the error will happen
![image](https://github.com/mui/mui-x/assets/4982796/277d31e9-7867-423b-b016-13b4233c0864)

**Comment by truongnt27** [comment]
> > Added auto selection for parent when children are selected. And the same for deselection. Improved a bit search for selected node. @dnquang1996vn Thank you for your example! https://codesandbox.io/s/edeyu
> 
> Hi @hamsishe Can you please tell me what to do when I don't have a root parent node? I mean the structure of data is an array of objects and not an object. I don't want the Parent label to render
Just use data.map(item => renderTree(item))

**Comment by truongnt27** [comment]
@Shivraj97 Just use data.map(item => renderTree(item))

**Comment by oliviertassinari** [comment]
See #12883 for the continuation of this issue, to get to the right checkbox selection behavior.
