### ISSUE TITLE
[question] columns aren't appearing while I'm testing

### ISSUE THREAD

**Issue by noghartt** [mui/mui-x#6027]
### Order ID 💳

49216

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I was trying to test a component that is using `DataGridPro` but I was having a weird behavior on it: I have 7 columns declared on it, but for some reason it only appears 3 of it (including the checkbox column from the DataGrid). Could it be a bug? Any idea about how I could solve it and get all my columns to test?

#### Some details about it:

- I'm using Jest + RTL + JSDOM to test it.
- I tried to trigger a `fireEvent` with scroll event on virtual scroller `div` element to trigger a rerender on DataGrid, but it doesn't work.
- I tried to find this column in some ways, e.g.: `getByRole` + find by `aria-label`, and other ways too, all of it unsuccessfully.
- If I remove these columns that appears (except checkbox), the remaining columns appears.
- Following the docs, I'm using custom datepicker from `@mui/x-date-pickers` to handle a specific editable cell.
- I tried to force a rerender on the component, triggering it via `waitFor`, but it doesn't work too.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.19 NixOS 22.11 (Raccoon) 22.11 (Raccoon)
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 4.19 GB / 14.87 GB
    Container: Yes
    Shell: 3.5.1 - /nix/store/ph9xmnlkzjgr22c920zgdyxxhbwrp4kp-fish-3.5.1/bin/fish
  Binaries:
    Node: 16.14.2 - /nix/store/zl4bvsqfxyx5vn9bbhnrmbmpfvzqj4gd-nodejs-16.14.2/bin/node
    Yarn: 1.22.19 - ~/entria/nix-env/woovi-admin/node_modules/.bin/yarn
    npm: 8.5.0 - /nix/store/zl4bvsqfxyx5vn9bbhnrmbmpfvzqj4gd-nodejs-16.14.2/bin/npm
  Utilities:
    Make: 4.3 - /nix/store/jm3nxvmxcm5nvalbv28acvygismcykvj-gnumake-4.3/bin/make
    GCC: 11.2.0 - /nix/store/58pwclg9yr437h0pfgrnbd0jis8fqasd-gcc-wrapper-11.2.0/bin/gcc
    Git: 2.37.2 - /etc/profiles/per-user/noghartt/bin/git
    Clang: 11.1.0 - /etc/profiles/per-user/noghartt/bin/clang
  Virtualization:
    Docker: 20.10.14 - /nix/store/5a5i251w81licm57ikbiysc9fcpw391s-docker-20.10.14/bin/docker
  IDEs:
    Emacs: 28.1.91 - /etc/profiles/per-user/noghartt/bin/emacs
    Nano: 6.4 - /run/current-system/sw/bin/nano
    VSCode: 1.70.2 - /etc/profiles/per-user/noghartt/bin/code
    Vim: 9.0 - /run/current-system/sw/bin/vim
  Languages:
    Bash: 5.1.16 - /nix/store/fcd0m68c331j7nkdxvnnpb8ggwsaiqac-bash-5.1-p16/bin/bash
    Perl: 5.36.0 - /run/current-system/sw/bin/perl
    Python: 3.9.12 - /nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/bin/python
    Python3: 3.9.12 - /nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/bin/python3
  Databases:
    MongoDB: 3.6.23 - /nix/store/yslpc5lnli8kc71lw5ixm3q4hq5dpfcv-mongodb-3.6.23/bin/mongo
  Browsers:
    Firefox: 104.0.1
  Monorepos:
    Yarn Workspaces: 1.22.19
    Lerna: 5.5.0
```
</details>

**Comment by alexfauquette** [comment]
This sounds like a virtualization problem. If yes, the easiest fix would be to disable virtualization in test env with the `disableVirtualization`.

Without a reproduction of the bug, we could not do better than supposition. Please provide a minimal reproduction of your failing test in code sandbox, such that we could investigate

**Comment by noghartt** [comment]
> This sounds like a virtualization problem. If yes, the easiest fix would be to disable virtualization in test env with the [`disableVirtualization`](https://mui.com/x/react-data-grid/virtualization/#disable-virtualization).
> 
> Without a reproduction of the bug, we could not do better than supposition. Please provide a minimal reproduction of your failing test in code sandbox, such that we could investigate

Oh, I tried now the `disableVirtualization` prop and it's working! Seems to be an error with virtualization. Thank you so much!
