### ISSUE TITLE
[data grid] Pinned column doesn't have bottom border in header 

### ISSUE THREAD

**Issue by saatchiy** [mui/mui-x#6044]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

For pinned columns, bottom border of the header cell is hidden.

![current](https://user-images.githubusercontent.com/25288496/188639684-92fb392d-699e-496f-b1ae-457151b1e61f.jpg)

### Expected behavior 🤔

Bottom border of pinned columns header cell should be visible, just like other header cells.

![expected](https://user-images.githubusercontent.com/25288496/188640045-d5ee63fb-aecb-4d66-ada0-69719488afdf.jpg)

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/m3qpkd?file=/demo.tsx

This is an example from the MUI documentation.

Steps:
1. Open the CodeSandbox project.
2. You can see that the first and last column are pinned and the bottom border of the header cell on those two columns are missing.

### Context 🔦

Without the bottom border, pinned columns look inconsistent with other columns.

### Order ID 💳 (optional)

45010

**Comment by m4theushw** [comment]
It's interesting that in https://mui.com/x/react-data-grid/column-pinning/ there's the bottom border:

<img width="400" src="https://user-images.githubusercontent.com/42154031/188912212-efaa8b14-945c-41fd-b936-1307a6577b0f.png" alt="image" style="max-width: 100%;">

It might be related to the custom theme used by the docs. We need to investigate more.

**Comment by cherniavskii** [comment]
Fixed by https://github.com/mui/mui-x/pull/7399

**Comment by cherniavskii** [comment]
@m4theushw 
> It's interesting that in [mui.com/x/react-data-grid/column-pinning](https://mui.com/x/react-data-grid/column-pinning/) there's the bottom border:

See https://github.com/mui/mui-x/pull/7001#discussion_r1048406008
