### ISSUE TITLE
[DataGrid] Inline editing on landing page freezes demo.

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#6047]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

A user reported a bug in the live preview demo on MUI X landing page (https://mui.com/x/).
It freezes the demo if the user tries to edit the status field with a double click.

### Expected behavior 🤔

Inline editing should work on the landing page.

### Steps to reproduce 🕹

Link to live example:[mui.com/x/](http://mui.com/x/) 

Steps:
1. Scrolled to the Status column on the demo
2. Double click (to edit) any cell on the Status column 
3. This freezes the screen, and you can't close the editing cell or interact with anything else on the demo.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by joserodolfofreitas** [comment]
On an extra note: We should probably update the demo on the landing page to display a more current state of affairs

**Comment by m4theushw** [comment]
Will be fixed by https://github.com/mui/material-ui/pull/34220

Initially I'd open this PR to test the CodeSandbox build.
