### ISSUE TITLE
[data grid] Can't import `DataGrid` from `@mui/x-data-grid-premium`

### ISSUE THREAD

**Issue by cannontechnology** [mui/mui-x#6051]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

CustomToolbar breaks in x-data-grid-premium but works in x-data-grid

### Steps to reproduce 🕹

Link to live example:   https://codesandbox.io/s/material-demo-forked-uhejqd?file=/demo.js

Steps:
1.  Switch to the import from from "@mui/x-data-grid-premium" to from "@mui/x-data-grid" and it will work.

### Context 🔦

I just upgraded from the base version to premium and my grid no longer works.  

It breaks differently in CodeSandbox.  Locally I get:

GridErrorHandler - An unexpected error occurred. Error: MUI: useGridRootProps should only be used inside the DataGrid, DataGridPro or DataGridPremium component..

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

2022-13366

**Comment by flaviendelangle** [comment]
The data grid component is named after it's package

- `@mui/x-data-grid` => `DataGrid`
- `@mui/x-data-grid-pro` => `DataGridPro`
- `@mui/x-data-grid-premium` => `DataGridPremium`

Here is your example fixed: https://codesandbox.io/s/material-demo-forked-pbs6dx?file=/demo.js

**Comment by cannontechnology** [comment]
Thanks @flaviendelangle that was a silly mistake in the codesandbox, however the issue locally was I had to clean up my node_modules.  There was duplicate modules.  Thanks for the quick reply!
