### ISSUE TITLE
Opening popups in React 18 can result in the popup initially opening in the wrong location and then snapping back to its anchor.

### ISSUE THREAD

**Issue by mschaefer-gresham** [mui/mui-x#6053]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

NOTE:  This issue was originally opened as as a non-premium plan user [here](https://github.com/mui/material-ui/issues/34208).

When using MUI together with React 18, popups that have longer render times can open in the wrong location on the screen, then snap back to their anchor.

This behavior appears to be related to strict mode. 

### Expected behavior 🤔

The popup should open in the correct location by respecting its anchor.

### Steps to reproduce 🕹

Steps:

1. Open the following CodeSandbox [example](https://codesandbox.io/s/data-grid-community-forked-dflf95?file=/src/index.tsx)
2. Click on the button FOUR.
3. Notice that the popup initially opens on the far left, then snaps back to the button.

Now try the same example in React 17 mode:

1. Open the file index.tsx.
2. Comment out the React 18 section, and un-comment the React 17 section.
3. Repeat the test.
4. See that the popup opens in the correct location.

### Context 🔦

Opening popups that result in longer render times.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

45466

**Comment by joserodolfofreitas** [comment]
Hi @mschaefer-gresham, the premium technical support only covers [MUI X components](https://mui.com/x/introduction/support/#technical-support).
The maintenance of the Core components is exclusively community driven at this point in time. 

We'll keep the conversion on the original issue.
