### ISSUE TITLE
How do I make the scrollbar always visible for the datagrid?

### ISSUE THREAD

**Issue by ahmetcaglayan** [mui/mui-x#6056]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

it only becomes visible when you move it

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/13018803/188804904-7f733ef6-9f7b-4d31-aebc-2830126127cb.png">

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/13018803/188804821-3278422e-331e-46c8-9bc5-8569e821df01.png">

**Comment by flaviendelangle** [comment]
Duplicates #6035
