### ISSUE TITLE
MUI datagrid Pro with multiple autocompletes, autofocus focuses only on last autocomplete on keyboard actions.

### ISSUE THREAD

**Issue by Cooper1596** [mui/mui-x#6058]
### Order ID 💳

45398

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

While using mui datagrid Pro with multiple autocompletes in a row, when we go into edit mode and try to edit the first autocomplete using keyboard actions(by using enter/space) the focus just jumps from the 1st autocomplete in the row to the 2nd autocomplete in that same row. 
This happened when I gave the autoFocus prop to the TextField in the autocomplete as previously I wasn't able to enter the edit mode for autocompletes using keyboard actions(only way to edit it was by clicking it)

I have further provided a code sand box link of an example for this issue.
[exampleLink](https://codesandbox.io/s/linked-autocompletes-forked-xqs11d?file=/src/App.js)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
You can't use `autoFocus` in multiple elements at the same time, only the last will get focus. You need to manually focus the input when the `hasFocus` prop is changed to true. Also, in the demo, the `editMode` and `processRowUpdate` props were used incorrectly. They must be added to the grid component, like so:

```tsx
<DataGrid
  editMode="row"
  rows={rows}
  columns={columns}
  processRowUpdate={processRowUpdate}
  experimentalFeatures={{ newEditingApi: true }}
/>
```

Don't miss to turn on the new editing API.

Since you want to use an Autocomplete as edit component please check https://github.com/mui/mui-x/issues/5506#issuecomment-1189729426. It contains fully working demo showing how to integrate this component into the grid.

**Comment by Cooper1596** [comment]
I tried using the issue [#5506 (comment)](https://github.com/mui/mui-x/issues/5506#issuecomment-1189729426) which you linked showing how to integrate the autocomplete into the Grid , by using `hasFocus` just like in the example you linked but when I tried implementing the same I got an error while trying to go into the edit mode. 
This was the error` Rendered more hooks than during the previous render`.
I have provided my code below for reference

```
export const CustomAutoComplete = (editParams: GridRenderEditCellParams, valueOptions: string[], onChangeHandler?: onChangeHandler) => {
    const { id, field, value, hasFocus } = editParams;
    const apiRef = useGridApiContext();

    const ref = useRef<HTMLDivElement>();
    
    useLayoutEffect(() => {
        if (hasFocus) {
            ref.current!.querySelector<HTMLInputElement>("input")!.focus();
        }
    }, [hasFocus]);
    

    return (
        <Autocomplete
            ref={ref}
            openOnFocus
            disablePortal
            options={valueOptions}
            value={value}
            isOptionEqualToValue={(option, selectedValue) => option === selectedValue || "" === selectedValue}
            onChange={(event, changedValue, reason) => {
                onChangeHandler ? onChangeHandler(event, changedValue, reason) : apiRef.current.setEditCellValue({ id, field, value: changedValue });
            }}
            sx={{
                width: editParams.colDef.width,
                '.MuiOutlinedInput-notchedOutline': {
                    border: 'none'
                }
            }}
            renderInput={(inputParams) => <TextField {...inputParams} />} />
    );
}
```

**Comment by m4theushw** [comment]
Usually this error occurs when a component returns early before a hook is executed. Could you create a CodeSandbox with all code? Only with the block you pasted I can't see anything wrong.

**Comment by Cooper1596** [comment]
@m4theushw I have provided a code sand box example with my custom autocomplete and it's use in a data grid.
I am able to reproduce the error. Like when you go into row edit mode it throws an error.
I hope this example is sufficient for you to debug the issue.
[example](https://codesandbox.io/s/linked-autocompletes-forked-x5bxc1?file=/src/App.js:540-544)

**Comment by m4theushw** [comment]
The problem was here:

```ts
renderEditCell: (editParams) => {
  const valueOptions = ["Income", "Expense"];

  return CustomAutoComplete(editParams, valueOptions);
}
```

This doesn't work because `CustomAutoComplete` is used as a render function, but it's a component. It needs to be:

```tsx
renderEditCell: (editParams) => {
  const valueOptions = ["Income", "Expense"];

  return (
    <CustomAutoComplete
      editParams={editParams}
      valueOptions={valueOptions}
    />
  );
}
```

Here's the fixed CodeSandbox: https://codesandbox.io/s/linked-autocompletes-forked-khfyfi?file=/src/App.js

**Comment by Cooper1596** [comment]
@m4theushw your solution worked and it helped me solve 3 potential issues. Thank You for your time and efforts.
