### ISSUE TITLE
[data grid] Row reorder with getRowHeight=()=>'auto' leads to visual glitching (?) 

### ISSUE THREAD

**Issue by camnealie** [mui/mui-x#6079]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Not sure what else to call it, so I'm calling it glitching.

When using the drag reorder function, if you're interacting with a row that has a height of 'auto', the rows swap back and forth underneath your cursor without you using them, as if they're in a render loop.

### Expected behavior 🤔

Regardless of row height, drag reorder should work the same

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-row-reorder-glitching-odfrqk?file=/src/App.tsx

Steps:
1. Follow steps in example
2.
3.
4.

### Context 🔦

I have a datagrid with varying row sizes, that needs to be able to handle row reordering. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.3
  npmPackages:
    @emotion/react:  11.10.0 
    @emotion/styled: ^11.3.0 => 11.8.1 
    @mui/base:  5.0.0-alpha.74 
    @mui/icons-material: ^5.0.1 => 5.5.1 
    @mui/lab: ^5.0.0-alpha.48 => 5.0.0-alpha.75 
    @mui/material: ^5.0.1 => 5.5.3 
    @mui/private-theming:  5.5.3 
    @mui/styled-engine:  5.5.2 
    @mui/styles: ^5.0.1 => 5.5.3 
    @mui/system:  5.5.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.10.3 
    @mui/x-data-grid:  5.17.1 
    @mui/x-data-grid-premium: ^5.14.0 => 5.17.1 
    @mui/x-data-grid-pro:  5.17.1 
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.0 
    @mui/x-license-pro:  5.17.0 
    @types/react:  17.0.43 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
</details>

### Order ID 💳 (optional)

47345

**Comment by m4theushw** [comment]
I checked and it also doesn't work with rows of different sizes, so not only dynamic row height. For instance, if one row has size of 50px and the next one is 100px it doesn't work, because when dragging the 50px to the bottom, the 100px goes to the top and if the 50px row is not moved very far away it's stays on top of the 100px row. @DanailH maybe row reordering only works with fixed row height.

CodeSandbox: https://codesandbox.io/s/mui-x-issue-row-reorder-glitching-forked-uhxxvi?file=/src/App.tsx

**Comment by DanailH** [comment]
@m4theushw I'll take a look.

**Comment by thefenry** [comment]
Any updates on this? We have this issue and it is affecting our grids really bad

**Comment by yaredtsy** [comment]
hey @DanailH 

I have e experimented with react-beautiful-dnd and they won't reorder the same rows that were reordered if the scroll direction is not changed. I apply the same logic and it works. I can create PR if no one is working on this. 

@camnealie  Demo Fix: https://codesandbox.io/s/mui-x-issue-row-reorder-glitching-forked-glvcjc?file=/src/App.tsx
@m4theushw  Demo Fix: https://codesandbox.io/s/mui-x-issue-row-reorder-glitching-forked-gklqzq?file=/src/App.tsx:624-635
