### ISSUE TITLE
[data grid] Print export without text

### ISSUE THREAD

**Issue by bowann** [mui/mui-x#6080]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When we print the data grind in a dialog, the text disappears, we have tries to override the css, but nothing works, any idea to why this happens, in the datagrid not opened in a dialog, the text is shown.
<img width="1432" alt="Screenshot 2022-09-08 at 10 58 34" src="https://user-images.githubusercontent.com/7488687/189081705-f94b3c2f-4054-4c6e-a405-c2d99a1a363b.png">

### Expected behavior 🤔

print with text shown

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
uses chrome
System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6.1
```
</details>

### Order ID 💳 (optional)

49270

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!
