### ISSUE TITLE
onColumnVisibilityModelChange is trigger when show hide column and then change the column Size

### ISSUE THREAD

**Issue by edenmeshulam** [mui/mui-x#6081]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

onColumnVisibilityModelChange is triggered when i clicking on showing hide column and then change the column Size,
Its not happend when the column is showed by default.  

### Expected behavior 🤔

onColumnVisibilityModelChange will not triggered at that situation.

### Steps to reproduce 🕹

Link to live example:

https://user-images.githubusercontent.com/20186807/189083580-693d100f-7422-4341-af71-c6b5c88bb677.mp4

### Your environment 🌎

<details>
  <summary><code> "@mui/x-data-grid-pro": "^5.17.1" </code></summary>

```
React JS V 17.0.2
Chrome browser

```
</details>

**Comment by m4theushw** [comment]
Could you provide a reproduction? I can't see how you're setting the column to be hidden as default. The `initialState` prop should be used. You can use [this **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) as starting point.
