### ISSUE TITLE
[question] Change a cell with a type of 'number' to a type of 'singleSelect' based on value in another cell (retry)

### ISSUE THREAD

**Issue by hutchhicken** [mui/mui-x#6084]
### Order ID 💳

50090

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

The reply to https://github.com/mui/mui-x/issues/6052#issue-1363767461 didn't actually answer the question posed, but the issue was closed (hence the resubmit here).

> I would like to change a cell with a type of 'number' to a type of 'singleSelect' (as well as setting an appropriate valueOptions) depending on the value set in another cell on the same row. Is this possible?

> Yes, you can check the example in https://mui.com/x/react-data-grid/editing/#linked-fields

> The example cited sets the value of a linked cell, which is not what is needed. What I need is to be able to change the type of the cell from 'number' to 'singleSelect'. The apiRef function used for changing the value is `setEditCellValue()`. Looking at https://mui.com/x/react-data-grid/editing/#apiref, I can't see any equivalent `setEditCellType()`.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 104.0.1
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0 
    @emotion/styled: ^11.10.0 => 11.10.0 
    @mui/base:  5.0.0-alpha.94 
    @mui/core-downloads-tracker:  5.10.2 
    @mui/icons-material: ^5.10.2 => 5.10.2 
    @mui/material: ^5.10.2 => 5.10.2 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine:  5.10.2 
    @mui/system:  5.10.2 
    @mui/types:  7.1.5 
    @mui/utils:  5.9.3 
    @mui/x-data-grid: ^5.16.0 => 5.16.0 
    @mui/x-data-grid-pro: ^5.16.0 => 5.16.0 
    @mui/x-license-pro: ^5.16.0 => 5.16.0 
    @types/react:  18.0.17 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.8.2 

```
</details>

**Comment by VZahTeck** [comment]
@zannager I have got the solution 
so here we have column with single select which has one row for text input
`
{
    field: 'abc'
    type: 'singleSelect',
    renderEditCell: (params) => {
      return params.row.name === 'text input row' ? (
        <GridEditInputCell {...params} />
      ) : (
        <GridEditSingleSelectCell {...params} />
      );
    },

    valueOptions: ({ row }) => {
      if (row?.name !== 'text input row') {
        return [
          { value: 'Normal', label: 'Normal' },
          { value: 'Warning', label: 'Warning' },
          { value: 'Caution', label: 'Caution' },
          { value: 'Alert', label: 'Alert' },
        ];
      }
      return [];
    },
}
`
