### ISSUE TITLE
[TimePicker] Make clock face background themable

### ISSUE THREAD

**Issue by marek-mihok** [mui/mui-x#6094]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The clock watch face has hardcoded background color value of `rgba(0,0,0,.07)` which is not visible on dark themed backgrounds:
```js
const ClockClock = styled('div')({
  backgroundColor: 'rgba(0,0,0,.07)',
  borderRadius: '50%',
  height: 220,
  width: 220,
  flexShrink: 0,
  position: 'relative',
  pointerEvents: 'none'
});
```
It should be themable similar to other sub-components, such as clock pin which has defined background as a theme color `theme.palette.primary.main`:
```js
const ClockPin = styled('div')(({
  theme
}) => ({
  width: 6,
  height: 6,
  borderRadius: '50%',
  backgroundColor: theme.palette.primary.main,
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)'
}));
```
A temporary workaround could be a style override, but it is also currently not possible (#4669) without an ugly selector.

### Examples 🌈

![image](https://user-images.githubusercontent.com/23740173/189304564-94a04401-79ca-4383-a0ff-b240b2d25e36.png)

![image](https://user-images.githubusercontent.com/23740173/189304696-48b0e1fb-6626-40ef-a401-48e1abd27f02.png)

### Motivation 🔦

The clock appearance is not consistent between light and dark themes.

**Comment by LukasTy** [comment]
Fixed with #6156
