### ISSUE TITLE
[Pickers] PickersDay selected prop doesn't work

### ISSUE THREAD

**Issue by vicodinvic1** [mui/mui-x#6095]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I use CalendarPicker and PickersDay component, and `selected` prop is always `false`, so it doesn't add .Mui-selected className as well.

<img width="1440" alt="Screenshot 2022-09-08 at 15 51 17" src="https://user-images.githubusercontent.com/13731447/189140041-facc693d-c55d-40f0-832c-28382f25df85.png">
<img width="1079" alt="Screenshot 2022-09-08 at 15 51 39" src="https://user-images.githubusercontent.com/13731447/189140050-432946a2-a930-4afc-9707-46d15cfbbf20.png">

### Expected behavior 🤔

This prop should works properly.

**Comment by vicodinvic1** [comment]
> @vicodinvic1 I do not manage to reproduce your bug. Could you provide a minimal reproduction example.
> 
> Here is starting point where I tried to log custom day `isSelected`: https://codesandbox.io/s/sharp-tess-6z1jq3?file=/demo.tsx

Thank you for the involvement, but had tested it on StaticDatePicker instead of CalendarPicker :)
But it doesn't matter actually.

I figured out what is the issue, when you use CalendarPicker you must pass not only the `value` prop but `date` prop as well, otherwise component can not recognise which day is actually selected.

So the solution it to provide `date` prop to CalendarPicker besides the `value` prop.

**Comment by alexfauquette** [comment]
@flaviendelangle Sounds like an inconsistency between `Calendar` and the other components.

What about renaming `date` by `value` to get the same naming for all MUI input components? It's on the same idea that we renamed `onChangeMonth` by `onChange` on `<MontPicker />`

**Comment by flaviendelangle** [comment]
Yes, I fully agree with this

@vicodinvic1 for legacy reason the prop holding the value is named `date` on the inner components.
