### ISSUE TITLE
[pickers] Ensure internal component use `value` prop the the selected date

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#6104]
From #6095

> Sounds like an inconsistency between `Calendar` and the other components.
>
> What about renaming `date` by `value` to get the same naming for all MUI input components? It's on the same idea that we renamed `onChangeMonth` by `onChange` on `<MontPicker />`
>
> _Originally posted by @alexfauquette in https://github.com/mui/mui-x/issues/6095#issuecomment-1241889306_

**Comment by flaviendelangle** [comment]
Adding it to the board
