### ISSUE TITLE
Datepicker (MM/YYYY) cannot choose month

### ISSUE THREAD

**Issue by audreynmy** [mui/mui-x#6106]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Integrating with moment.js date adapter, and using the following code: 

```
const App = () => {
  const [month, setMonth] = useState(moment())
  
  const DatePickerComponent = () => {
    <DatePicker
              views={['year', 'month']}
              label="Year and Month"
              value={month}
              onChange={(value) => {
                setMonth(value);
              }}
              renderInput={(params) => <TextField {...params} helperText={null} />}
            />
  }
  
  return (
<DatePickerComponent />
)
}
```

The Month/Year Datepicker closes upon selecting the year.

### Expected behavior 🤔

After selecting the year, the Datepicker should allow for month selection.

### Context 🔦

Am I missing out anything?
If I try to put state into the DatePickerComponent itself, the datepicker works correctly.
But once I move it into App.js itself, I cannot select the month. Seems like DatePicker only allows for one onClick selection?

I have to use state in the App.js file as the state will be used by other components also.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by yaredtsy** [comment]
@audreynmy it has nothing to do with mui. It's how you declared the nested component. every time you update the state the parent component re-renders every function are re declare this will re-render DatePickerComponent function also. so you have to use useCallback or put DatePickerComponent out of the App function

**Comment by audreynmy** [comment]
@yaredtsy 
Hmm. Not quite sure if I am following. So, you mean I have to put DatePickerComponent in a useCallback hook?

Something like: 
```
const DatePickerComponent = useCallback(() => {
// return DatePicker
},[month]) 
```
?

**Comment by yaredtsy** [comment]
@audreynmy yes or move it out of App

**Comment by flaviendelangle** [comment]
In 99.99% of the use cases, if you are creating a component inside another component, you are doing something wrong.
For example:

```tsx
// Bad pattern, will very often cause bugs
const ComponentA = () => {
  const ComponentB = () => <div>HELLO</div>

  return <ComponentB />
}

export default ComponentA
```

```tsx
// Bad pattern, might work, but still ugly unless necessary, can cause bug depending on the params of the callback
const ComponentA = () => {
  const ComponentB = React.useCallback(() => <div>HELLO</div>, []);

  return <ComponentB />
}

export default ComponentA
```

```tsx
// Good pattern
const ComponentB = () => <div>HELLO</div>

const ComponentA = () => {
  return <ComponentB />
}

export default ComponentA
```

Thanks @yaredtsy for the answer

**Comment by audreynmy** [comment]
Thanks everyone for the input. Managed to get it working now :)
