### ISSUE TITLE
[date picker] Invalid licence key 

### ISSUE THREAD

**Issue by dzined** [mui/mui-x#6115]
### Order ID 💳

50655

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I've installed the licesne key in _app.js (as running a next app) - but i still get the missing license key

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Edge: 105.0.1343.33
    Firefox: 102.0.1
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.96 
    @mui/core-downloads-tracker:  5.10.4 
    @mui/material: ^5.10.4 => 5.10.4 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine:  5.10.4 
    @mui/styles: ^5.10.3 => 5.10.3 
    @mui/system:  5.10.4 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.3 
    @mui/x-date-pickers:  5.0.1 
    @mui/x-date-pickers-pro: ^5.0.1 => 5.0.1 
    @mui/x-license-pro: ^5.17.0 => 5.17.0 
    @types/react:  18.0.15 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
</details>

**Comment by dzined** [comment]
(browser is chrome on osx)

**Comment by alexfauquette** [comment]
Hi @dzined That's strange because the documentation is using next, so if it was a bug in the licence validation it would be visible in the doc too.

Does the bug persist after [restarting the development server](https://nextjs.org/docs/advanced-features/custom-app#caveats)?

**Comment by dzined** [comment]
@alexfauquette thanks for the reply. Yes i tried restarting the dev server a number of times and it's still showing the watermark on the calendar.

**Comment by dzined** [comment]
@alexfauquette I'm officially an idiot

missed of a character from the license key 🤦‍♂️

Sorry to have wasted your time!!

**Comment by alexfauquette** [comment]
Happy to know it's working :) Enjoy your dev
