### ISSUE TITLE
[question] Some doubts while testing editable cells

### ISSUE THREAD

**Issue by noghartt** [mui/mui-x#6116]
### Order ID 💳

49216

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

It's a simple doubt about tests, but I have a simple cell that have a validation process + custom edit cell (via `renderEditCell`) and after it I format it.

But, my doubt is: is there any issue when try to test the validation of some row? My test is following something like it:

<details>
<summary>Custom edit input cell</summary>

```tsx
const CustomEditCell = () => {
  const apiRef = useGridApiContext();

  const handleOnChange = ({ value }) => {
    apiRef.current.setEditCellValue(
      // magic here...
    );
  }

  return (
    <CustomInputThatFormatThings onChange={handleOnChange} />
  );
}
```
</details>

<details>
<summary>And my tests is following something like that:</summary>

```ts
// ...

  await userEvent.dblClick(valueCell);

  const valueInput = screen.getByTestId('datagrid-input');

  await userEvent.type(valueInput, '1{enter}');

  expect(valueCell).not.toHaveClass('MuiDataGrid-cell--error');

// ....
```
</details>

The class `MuiDataGrid-cell--error` is just an injected class that I created to handle custom style to wrong cells. Both errors and data from these cells are stored on a `useState`.

For some reason, this `useState` isn't updating in the right way, but everywhere I put a `console.log`, the values are updated with the new cell value. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.19 NixOS 22.11 (Raccoon) 22.11 (Raccoon)
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 4.19 GB / 14.87 GB
    Container: Yes
    Shell: 3.5.1 - /nix/store/ph9xmnlkzjgr22c920zgdyxxhbwrp4kp-fish-3.5.1/bin/fish
  Binaries:
    Node: 16.14.2 - /nix/store/zl4bvsqfxyx5vn9bbhnrmbmpfvzqj4gd-nodejs-16.14.2/bin/node
    Yarn: 1.22.19 - ~/entria/nix-env/woovi-admin/node_modules/.bin/yarn
    npm: 8.5.0 - /nix/store/zl4bvsqfxyx5vn9bbhnrmbmpfvzqj4gd-nodejs-16.14.2/bin/npm
  Utilities:
    Make: 4.3 - /nix/store/jm3nxvmxcm5nvalbv28acvygismcykvj-gnumake-4.3/bin/make
    GCC: 11.2.0 - /nix/store/58pwclg9yr437h0pfgrnbd0jis8fqasd-gcc-wrapper-11.2.0/bin/gcc
    Git: 2.37.2 - /etc/profiles/per-user/noghartt/bin/git
    Clang: 11.1.0 - /etc/profiles/per-user/noghartt/bin/clang
  Virtualization:
    Docker: 20.10.14 - /nix/store/5a5i251w81licm57ikbiysc9fcpw391s-docker-20.10.14/bin/docker
  IDEs:
    Emacs: 28.1.91 - /etc/profiles/per-user/noghartt/bin/emacs
    Nano: 6.4 - /run/current-system/sw/bin/nano
    VSCode: 1.70.2 - /etc/profiles/per-user/noghartt/bin/code
    Vim: 9.0 - /run/current-system/sw/bin/vim
  Languages:
    Bash: 5.1.16 - /nix/store/fcd0m68c331j7nkdxvnnpb8ggwsaiqac-bash-5.1-p16/bin/bash
    Perl: 5.36.0 - /run/current-system/sw/bin/perl
    Python: 3.9.12 - /nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/bin/python
    Python3: 3.9.12 - /nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/bin/python3
  Databases:
    MongoDB: 3.6.23 - /nix/store/yslpc5lnli8kc71lw5ixm3q4hq5dpfcv-mongodb-3.6.23/bin/mongo
  Browsers:
    Firefox: 104.0.1
  Monorepos:
    Yarn Workspaces: 1.22.19
    Lerna: 5.5.0
```
</details>

**Comment by DanailH** [comment]
Hi, @noghartt thanks for raising this!
I'm struggling to understand the problem you are having - is it that the class you inject `MuiDataGrid-cell--error` is still present even tho it shouldn't be? 
@m2mathew has more knowledge related to the editing feature, maybe he will be able to understand the problem you are having.
