### ISSUE TITLE
[question] Clearing the selection doesn't de-select row on grid

### ISSUE THREAD

**Issue by DCMattyG** [mui/mui-x#6117]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using a controlled selection with single select, if you clear the selection programmatically, the last selected row retains the "Mui-selected" styling, which can be confusing to users who believe they just un-selected everything.

### Expected behavior 🤔

When using controlled selection, resetting the selection to and empty array should also removing the highlighting for all items on the grid.

### Steps to reproduce 🕹

See Code Sandbox:

https://codesandbox.io/s/clever-snowflake-bzi17i?file=/demo.tsx

### Context 🔦

The reason for highlighting this bug it to help clearly reflect on the grid what is selected, and what is not. If clearing the selection programmatically doesn't visually remove the styling from the grid, users will likely get confused as to what is "selected" and what isn't.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.70)

npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.19.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.19.1
npm notice Run npm install -g npm@8.19.1 to update!
npm notice
```
</details>

**Comment by flaviendelangle** [comment]
The prop to pass the model is `selectionModel` not `setSelectionModel`. Did you see this somewhere ?

**Comment by DanailH** [comment]
@DCMattyG thanks for raising this!
@flaviendelangle is right the correct prop is `selectionModel`. Changing this fixes your issue -> https://codesandbox.io/s/flamboyant-aj-jkgrf6
The question is where did you see the `setSelectionModel` prop?
