### ISSUE TITLE
[pickers] Switch `localeText` based on `adapterLocale`

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#6119]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Basically, switching `adapterLocale` to, say, `nb-NO` changes all of the dates within datePicker, but not the action bar buttons.

Kinda same as https://github.com/mui/mui-x/issues/5601

Looking at [useLocaleText](https://github.com/mui/mui-x/blob/3e7bfb2a3b11d3728892b245e70928c7669a0bd6/packages/x-date-pickers/src/internals/hooks/useUtils.ts#L9) or [LocalizationContext](https://github.com/mui/mui-x/blob/3e7bfb2a3b11d3728892b245e70928c7669a0bd6/packages/x-date-pickers/src/LocalizationProvider/LocalizationProvider.tsx#L54), none of them change anything like `localeText ?? localeTexts[adapterLocale]`, and one of them probably should.

### Examples 🌈

Norwegian months and english "Clear"
![image](https://user-images.githubusercontent.com/17963791/189589508-6fcf1e42-a2b3-444d-acb3-2d17189878ff.png)

### Motivation 🔦

I don't want to pass `localeText` from mui to mui myslef, it feels like mui should do it already.

**Comment by flaviendelangle** [comment]
If I understand correctly, you would like our component, to automatically set the translations (`localeText`) to the same locale as the date locale (`adapterLocale`).

I see one major problem doing it: we would have to bundle all translations, which is not something we want. By having the import on your side, we are able to tree-shake the unused locals.

**Comment by MonstraG** [comment]
Okay, you understood me correctly, gonna pass them manually then.
