### ISSUE TITLE
[DatePicker] Disabled month is selected by default

### ISSUE THREAD

**Issue by wscourge** [mui/mui-x#6121]
## Steps to reproduce

It is important to understand, that at the time of writing it's July 2019.

1. Create picker with:
```
maxDate={moment().add(6, 'months')
views={['year', 'month']}
openTo="year"
```
2. Open the picker and select next year
3. Selected month is `July`, althought it is disabled

## Expected behavior

No month should be selected - guess that's going to be hard, as it is not valid date due to moment deprecation warning.

An acceptable solution would be to set the selected month to anything that is not disabled.

## Actual behavior

Selected month is one of the disabled months.

## Live example

https://codesandbox.io/s/basicdatepicker-material-demo-forked-5czq6?file=/demo.tsx

Due to better `active` month visibility, I'm attaching the screenshot of my custom date picker as well:

![image](https://user-images.githubusercontent.com/16985871/61371065-2d4a9700-a894-11e9-8dec-dbc1aa451045.png)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/lab | v5.0.0-alpha.16  |

**Comment by flaviendelangle** [comment]
Fixes by https://github.com/mui/mui-x/pull/4814
