### ISSUE TITLE
[DataGrid] RTL Support

### ISSUE THREAD

**Issue by dashty94** [mui/mui-x#6130]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have several columns in the table, but when using the table on RTL mode, and scrolling the table, the table body scrolls fine but the headers are fixed and they do not scroll. 

Also, when the table content is scrolled and scrolling to the end of the table, the `onRowsScrollEnd` function does not get triggered.

The component has yet another issue with pinning the columns, but this one has a lower priority.

### Expected behavior 🤔

I expected the table headers to scroll normally on RTL as scrolling the table body. The `onRowsScrollEnd` function needs to work with the expected behavior.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/zealous-sinoussi-v8lbey

Steps:

1. Create a container element for the DataGrid with dir attribute set to RTL
2. Create a DataGrid inside that container
3. Define a few columns as that they do not fit the screen and need to scroll
4. Start scrolling the table, the rows scroll but the headers are fixed.

### Context 🔦

I have been using the Mui x Data Grid for a while and I am using the rest of the features extensively in my project. I have even purchased the pro version so that I get the support I need. My main use case is on RTL and needs to configure the component accordingly.

I have tried some other workaround mentioned in other GitHub issues, but none of them worked for me.

The following issues have already been mentioned that are quite the same:

- [ ]  #3435
- [ ] #230
- [ ] #4954
- [ ] #4990
- [ ] #5063

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#49921

**Comment by DanailH** [comment]
Hi, @dashty94 thanks for raising this!
I think we can revisit the RTL topic for v6. It would match the timing if we have to do any breaking changes to achieve this.

I will close this issue. You can use #230 to track the progress.
