### ISSUE TITLE
DatePicker accepting wrong date when typing 2 for year

### ISSUE THREAD

**Issue by oe-bayram** [mui/mui-x#6139]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I try to type in 13.09.2 (for the date 13.09.2022) the date picker is then taking the date 13.09.1902 as value.
The reason for this could be that 13.09.2 is being accepted as a valid date.

### Expected behavior 🤔

When typing in 13.09.2 the date picker should wait for the full date input to be typed.

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

```
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import deLocale from "date-fns/locale/de";
import { DatePicker } from "@mui/x-date-pickers";
import { TextField } from "@mui/material";
```

```
<LocalizationProvider dateAdapter={AdapterDateFns} locale={deLocale}>
        <DatePicker<Date>
          openTo="day"
          inputFormat="dd.MM.yyyy"
          mask="__.__.____"
          views={["year", "month", "day"]}
          value={value}
          onChange={onChange}
          renderInput={(params: TextFieldProps) => (
            <TextField
              {...params}
              variant="standard"
              inputProps={{
                ...params.inputProps,
                placeholder: "TT.MM.JJJJ",
              }}
            />
          )}
        />
</LocalizationProvider>
```

**Comment by oe-bayram** [comment]
This seems to be an issue with the use Adapter.
I was able to fix this by using AdapterMoment as adapter:

`import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment';`

**Comment by thibaultadet** [comment]
I'm having the same issue.
@oe-bayram Why would you use `AdapterMoment` if you're using `deLocale` from `dateFns` ?
