### ISSUE TITLE
Allow ability to not open the next view in DatePicker after the first view is selected

### ISSUE THREAD

**Issue by NiharR27** [mui/mui-x#6149]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Version:  `"@mui/x-date-pickers": "^5.0.0"`
Browser: **Firefox / Chrome**

I am currently using the `@mui/x-date-pickers/DatePicker` for the calendar Month view purpose for the user to select 'Month' and then year (if they want to)...

With the current code:
```
<DatePicker
              open={isPickerOpen}
              disabled={isLoading}
              openTo="month"
              views={['month', 'year']}
              onOpen={handleOpenPicker}
              onClose={handleClosePicker}
              value={new Date(currentMonth)}
              onChange={handleChangeDate}
              renderInput={(params) => (
                <MuiButton
                  ref={params.inputRef}
                  disabled={isLoading}
                  style={{ padding: 5 }}
                  onClick={handleOpenPicker}>
                  {format(new Date(currentMonth), 'MMMM yyyy')}
                </MuiButton>
              )}
            />
```

The issue that I am facing is whenever I choose the Month (the first view that it opens), it goes to show the year view.... This get's quite annoying for users if they don't wanna really change the year and I kinda feel like there should be a way to optionally turn off the other views to popup after first view is selected.

### Examples 🌈

https://user-images.githubusercontent.com/52943748/190120329-26389428-e1e7-4d27-adae-dfb2d7522206.mov

**Comment by LukasTy** [comment]
Hey @NiharR27 
Have you tried switching the order of `views`? The order does matter as the views are presented in the order they are provided via this prop.
Specifying `views=['year', 'month']` should close the picker after selecting month and only allow to go into year view if the user wants.

**Comment by NiharR27** [comment]
@LukasTy  Legend!!! that works thanks. I am closing this issue and marking as solved. Thanks again.
