### ISSUE TITLE
Data grid conditional editing

### ISSUE THREAD

**Issue by ARCRM** [mui/mui-x#6150]
### Order ID 💳

48127

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have one column in my DataGridPro which have an "editable " column  property equal to false at the initial state (when the row is in the view mode).
I have an option to create new rows in my DataGrid.
I want when I create a new row (the row switches to edit mode) that the property "editable" is equal to true and to have the possibility to enter a value.

When I add a new row I add a property isNew to true and I try to update the "editable" column property if the row contain the isNew property equal to true by the renderCell function but it's not working.

```
renderCell: params => {
                if(params.row.isNew){
                    params = {...params, isEditable: true}
                }
                return params.formattedValue;
}
```

I tried also this:

```
renderCell: params => {
                if(params.row.isNew){
                    params = {...params, colDef: {
                        ...params.colDef, editable: true
                    }};
                }
                return params.formattedValue;
}
```

Tell me if you want all my code.

### Your environment 🌎
```
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.10.0
    @emotion/styled: ^11.6.0 => 11.10.0
    @mui/base:  5.0.0-alpha.69
    @mui/icons-material: ^5.4.1 => 5.4.2
    @mui/lab: ^5.0.0-alpha.68 => 5.0.0-alpha.69
    @mui/material: ^5.4.1 => 5.4.2
    @mui/private-theming:  5.4.2
    @mui/styled-engine:  5.4.2
    @mui/styles: ^5.4.1 => 5.4.2
    @mui/system: ^5.4.1 => 5.4.2
    @mui/types:  7.1.2
    @mui/utils: ^5.4.1 => 5.4.2
    @mui/x-data-grid: ^5.5.0 => 5.14.0
    @mui/x-data-grid-pro: ^5.14.0 => 5.14.0
    @mui/x-date-pickers:  5.0.0-beta.3
    @mui/x-date-pickers-pro: ^5.0.0-beta.3 => 5.0.0-beta.3
    @mui/x-license-pro: ^5.14.0 => 5.14.0
    @types/react:  17.0.48
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.5 => 4.5.5
```

**Comment by alexfauquette** [comment]
You have a [doc example](https://mui.com/x/react-data-grid/editing/#disable-editing-of-specific-cells-within-a-row) about disabling editing on specific cells.

Another solution (more hacky) could be to prevent the default behavior when starting the edit: `event.defaultMuiPrevented` 
```jsx
onRowEditStart={(params, event) => {
      if (params.row.notEditable) {
        event.defaultMuiPrevented = true;
      }
    }}
```
https://codesandbox.io/s/eager-northcutt-s1uzfj?file=/demo.tsx

**Comment by ARCRM** [comment]
Thank you for the doc link !
My cell when I was editing the whole row have to only be editable if it was a new row and I used the "isCellEditable" function like this :
```
isCellEditable={(params) => {
            if(params.field === 'MyColumn' && !params.row?.isNew){
                        return false;
                    }
                    return true;
           }}
```
