### ISSUE TITLE
Add File Manager component

### ISSUE THREAD

**Issue by arvind-v97** [mui/mui-x#6152]
### Summary 💡

I want to work on a feature to add 'File Manager' Component in MUI. The component will allow users to browse files and folders and perform basic file operations. It will use existing MUI components.

### Examples 🌈

<img width="1149" alt="Screenshot 2022-09-14 at 7 19 49 PM" src="https://user-images.githubusercontent.com/82647893/190172543-c90ee00b-e990-4b3b-a404-bcdef72a14f2.png">

### Motivation 🔦

A lot of ERP applications we are developing requires some kind of file storage system embedded into the React app. Example: One of the app we are developing requires users to upload and track shipment files.

### Benchmark

- https://webix.com/filemanager/
- https://ckeditor.com/ckfinder/

**Comment by arvind-v97** [comment]
We are actually a development team using MUI-X. We plan to add this feature directly in MUI-X so other users who requires this component can import it their projects.

**Comment by alexfauquette** [comment]
@joserodolfofreitas That sounds like an enhancement but not for the coming months

**Comment by oliviertassinari** [comment]
I'm closing to signal that it's unlikely. Still, the "waiting for upvotes" label is still applied, so up for considerations.
