### ISSUE TITLE
[DataGrid] checkboxSelection not visible

### ISSUE THREAD

**Issue by jinow9595** [mui/mui-x#6154]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In datagrid, the checkbox selection option does not function normally with the error below.

MUI: The column type "checkboxSelection" you are using is not supported.
Column type "string" is being used instead.

I am using master detail with datagrid's checkbox selection option. The checkbox selection is not visible inside the grid.
Also, is there a way to move the check box selection to the left rather than the master detail?

![화면 캡처 2022-09-15 111326](https://user-images.githubusercontent.com/69668970/190297197-835237d8-31f7-4f68-86ca-c97f9224e603.png)

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

39248

**Comment by alexfauquette** [comment]
`checkboxSelection` is a boolean prop. From the message error, I guess you are trying to introduce a column with `type: "checkboxSelection"` which does not exist.

To show checkbox selection you have [this demo](https://mui.com/x/react-data-grid/selection/#checkbox-selection).

Does it solves you problem, and if yes which part of the doc leads you to put the `"checkboxSelection"` in the column type?
