### ISSUE TITLE
[DataGrid] Server side validation causes infinite update loop since 5.17.1

### ISSUE THREAD

**Issue by dsimon-dev** [mui/mui-x#6160]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm pretty sure the changes in ~~#5897~~ *somewhere else, see edit section at the bottom* broke server side validation ([Persistence](https://mui.com/x/react-data-grid/editing/#persistence) in the docs).

Please take a look at this sandbox, forked from the linked "After" sandbox in the PR: https://codesandbox.io/s/fullfeaturedcrudgrid-demo-mui-x-forked-y1s7le?file=/demo.tsx

I have removed the client side validation, modified `processRowUpdate`, added `onProcessRowUpdateError` and added an `errors` array. Try updating a row with an empty name, you will see how it causes an infinite loop.

In a local project I have tried making the callbacks stable references, this fixes the infinite loop but causes another bug where the row incorrectly switches to view mode.

### Expected behavior 🤔

No infinite loop, row stays in edit mode. This worked in ~~5.17.1~~ 5.17.0.

### Steps to reproduce 🕹

See sandbox

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

<br>
Firefox 104.0.2

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

  System:
    OS: Linux 5.19 Arch Linux
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 104.0.2
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.97 
    @mui/core-downloads-tracker:  5.10.5 
    @mui/icons-material: ^5.10.3 => 5.10.3 
    @mui/lab: ^5.0.0-alpha.85 => 5.0.0-alpha.99 
    @mui/material: ^5.10.5 => 5.10.5 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine:  5.10.5 
    @mui/system:  5.10.5 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.3 
    @mui/x-data-grid: ^5.17.2 => 5.17.2 
    @mui/x-date-pickers: ^5.0.1 => 5.0.1 
    @types/react: ^18.0.19 => 18.0.19 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.8.3
```
</details>

### Edit

I just tested it on older versions and it seems it was already broken in 5.17.1, with 5.17.0 I had no issues.

**Comment by alexfauquette** [comment]
@m4theushw could you have a look to this issue?

**Comment by m4theushw** [comment]
Same as #6183. You need to memoize the callbacks passed to `processRowUpdate` and `onProcessRowUpdateError`. See https://github.com/mui/mui-x/issues/6183#issuecomment-1249937490
