### ISSUE TITLE
[Data Grid Premium] Export GridRowGroupableColumnMenuItems 

### ISSUE THREAD

**Issue by passpe** [mui/mui-x#6169]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Please export GridRowGroupableColumnMenuItems to customize column menu

### Order ID 💳 (optional)

50416

**Comment by cherniavskii** [comment]
Hey @passpe 
Can you share more details on what kind of customization you are trying to achieve?
Thanks!

**Comment by passpe** [comment]
I have a custom GridColumnMenuContainer with standard and custom MenuItem. I need to ad d Grouping MenuItem to it.

**Comment by cherniavskii** [comment]
Closed by https://github.com/mui/mui-x/pull/7308
