### ISSUE TITLE
[data grid] Enable indeterminate state for row checkboxes

### ISSUE THREAD

**Issue by tommcquarrie** [mui/mui-x#6177]
### Summary 💡

This is somewhat related to this request but not necessarily dependent on it: https://github.com/mui/mui-x/issues/4248

We need the ability to select all/deselect all children based on a parent group selection. We've achieved this via our own selection state calculation.  What we would also like to do though is show the group checkbox as indeterminate if you've only selected some of the children.  it's possible that if you implement a solution for issue 4248, to make it consistent with the select all checkbox behaviour, indeterminate state might be supported out of the box.  If not, there might be some other changes that could be made which might enable us to add this behaviour.

One option might be to enable the selectionModel to accept an array of strings or objects, and if it's an object, you can pass an id and an indeterminate flag: `selectionModel={[{id: 1, indeterminate: true]}`.

Another option we tried was to actually implement our own checkbox component wrapper and pass that as the base checkbox component used by the grid.  We could control the indeterminate state ourselves if the checkbox was passed the row data as a prop, but currently it isn't.

### Examples 🌈

<img src="https://user-images.githubusercontent.com/3905175/190575301-e6622405-d70f-4cfa-bc56-f11f7661e693.png" width="449">

### Motivation 🔦

The select all checkbox already incorporates this behaviour, so not being able to replicate that for selecting a group makes the UX inconsistent for the user.

### Order ID 💳 (optional)

45574

**Comment by HansBrende** [comment]
FYI @tommcquarrie I was able to accomplish this using the following hack: https://github.com/mui/mui-x/issues/4248#issuecomment-1272452965

**Comment by shahidify** [comment]
Any update on this issue/feature ?
