### ISSUE TITLE
[data grid] Ability to customise the indent of group expansion toggles

### ISSUE THREAD

**Issue by tommcquarrie** [mui/mui-x#6178]
### Order ID 💳

45574

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We've received feedback that users find it difficult to visually differentiate different levels in our tree grids. We would like to increase the indent, but so far I haven't found any mechanism to do so.  I see there's a hard coded left margin which is calculated based on the rowNode.depth here: https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx#L68

I'm wondering if we can enable a multiplier prop or a theme variable which could be used to increase this indent?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @tommcquarrie 
There are few options:
- Change `spacing` on theme level:
  ```tsx
  const theme = createTheme({
    spacing: 16 // default is 8
  });
  ```
  ⚠️ This might impact other parts of the grid
  **Demo**: https://codesandbox.io/s/eloquent-shadow-voi215?file=/index.tsx
- Customize grouping cell by wrapping it with additional `div` with a margin:
  **Demo**: https://codesandbox.io/s/tender-pare-vwub8t?file=/demo.tsx

On our side, we can improve the DX by adding a prop to `GridTreeDataGroupingCell`:
```diff
--- a/packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx
+++ b/packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx
@@ -29,10 +29,11 @@ const useUtilityClasses = (ownerState: OwnerState) => {
 
 interface GridTreeDataGroupingCellProps extends GridRenderCellParams {
   hideDescendantCount?: boolean;
+  offsetMultiplier?: number;
 }
 
 const GridTreeDataGroupingCell = (props: GridTreeDataGroupingCellProps) => {
-  const { id, field, formattedValue, rowNode, hideDescendantCount } = props;
+  const { id, field, formattedValue, rowNode, hideDescendantCount, offsetMultiplier = 2 } = props;
 
   const rootProps = useGridRootProps();
   const apiRef = useGridApiContext();
@@ -65,7 +66,7 @@ const GridTreeDataGroupingCell = (props: GridTreeDataGroupingCellProps) => {
   };
 
   return (
-    <Box className={classes.root} sx={{ ml: rowNode.depth * 2 }}>
+    <Box className={classes.root} sx={{ ml: rowNode.depth * offsetMultiplier }}>
       <div className={classes.toggle}>
         {filteredDescendantCount > 0 && (
           <IconButton
```

Then developers can do this:
```tsx
const groupingColDef = {
  renderCell: (params) => <GridTreeDataGroupingCell {...params} offsetMultiplier={4} />
};

<DataGridPro
  groupingColDef={groupingColDef}
/>
```
