### ISSUE TITLE
[license] Getting an Error checking license. Sales model not found or invalid!

### ISSUE THREAD

**Issue by jalehoux** [mui/mui-x#6182]
### Order ID 💳

99994487

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Current behavior 😯
Shows invalid license key with following error in console.
`verifyLicense.js:118 Error checking license. Sales model not found or invalid!`

```
MUI: Invalid license key.

Your MUI X license key isn't valid. Please check your license key installation https://mui.com/r/x-license-key-installation.

To purchase a license, please visit https://mui.com/r/x-get-license.
```

Expected behavior 🤔
Validate the license correctly and remove watermark and console errors.

Context 🔦
Currently trying to get pro license working.  We were told we were given a temporary 60 day license so not sure if this is an issue with the license or the implementation.  It appears to be missing the LM when decoding. 

Seems to be getting stuck at 
```
  if (license.licensingModel == null || !LICENSING_MODELS.includes(license.licensingModel)) {
    console.error('Error checking license. Sales model not found or invalid!');
    return LicenseStatus.Invalid;
  }
```

To be clear we bootstrap our app in a separate library and then we export that package to be used in the main app. The environment below is that package which is where we set the License which appears to work.  In the main app we have datagrid pro at version ^5.17.2

`LicenseInfo.setLicenseKey(LICENSE_KEY);`

I tried running the npx @mui/envinfo on main app but it hangs.   The below is for the bootstrap app where the license is being set.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6.1
  npmPackages:
    @mui/icons-material: ^5.5 => 5.8.2 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.11.1 
    typescript:  4.2.3 
```
</details>

**Comment by flaviendelangle** [comment]
>  In the main app we have datagrid pro at version ^5.17.2

In your :`@mui/envinfo` I see `@mui/x-data-grid:  5.11.1`
Can you confirm me that you don't have multiple version of the grid and/or of the license package in your bundle ? That could cause issues.

**Comment by jalehoux** [comment]
This is all set.  Received a new license key.  The old was missing a License Mode and was failing due to it.
