### ISSUE TITLE
[DataGrid/Docs] In the Restore the state example, CustomToolbar was hidden behind the pinned-column.

### ISSUE THREAD

**Issue by heyfirst** [mui/mui-x#6190]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When you `Save current view` then you pin the column on the example, the custom config dropdown was in behind the pinned column.

![data-grid-state-apiref-bug](https://user-images.githubusercontent.com/4945174/190875662-c1475e94-416b-42de-a265-3b0197f97211.gif)

### Expected behavior 🤔

![expected-data-grid](https://user-images.githubusercontent.com/4945174/190875907-1685df61-ad78-426b-a73d-ddbef296fca3.gif)

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-data-grid/state/#restore-the-state-with-apiref

Steps:
1. Click on `Save current view` and named it "custom view name" (if it's not long enough, it will completed hide by pinned column)
2. Save the view
3. Click Dropdown on **Desk** column and choose **Pin to left**
4. Click **Custom View** to open dropdown and you will see it

### Context 🔦

This caused because the pinned column has `z-index:1` but Popper itself has no `z-index`. I personally don't think this is big issue because developer can figure it out themselves as well but having the document that works with all edge cases would be good 😄 

I can open the PR for fix this really small stuff. 🙇🏻

**Comment by alexfauquette** [comment]
Yes, sound that for other menu items in the toolbar we use a component [`GridMenu`](https://github.com/alexfauquette/mui-x/blob/master/packages/grid/x-data-grid/src/components/menu/GridMenu.tsx#L48) with `zIndex: theme.zIndex.modal`

@heyfirst if you want to fix it, the code demo is [here](https://github.com/mui/mui-x/blob/master/docs/data/data-grid/state/RestoreStateApiRef.tsx)

**Comment by heyfirst** [comment]
@alexfauquette I had made change on this #6191 PR (https://github.com/mui/mui-x/pull/6191/files). I will refactor to use `sx: 'modal'` instead of `sx: 1`
