### ISSUE TITLE
[pickers] The keyboard editing loses the timezone (tested with `dayjs`)

### ISSUE THREAD

**Issue by rottabonus** [mui/mui-x#6208]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Use DateTimePicker or DatePicker and dayjs-date with timezone applied
2. Change the datetime-value with the UI-selectors and see that the timezone works properly
3. Now change the datetime-value with keyboard and see that the timezone is dropped from the datetime-value
4. [Here is a codesandbox](https://codesandbox.io/s/fancy-smoke-otsmh9?file=/demo.tsx) to reproduce the issue

### Current behavior 😯

When user changes the date with keyboard and there is a dayjs-date object with timezone in the picker, then the timezone is dropped out of the value

### Expected behavior 🤔

The timezone should stay in the value.
It should work like when changing the value with the graphical user interface by clicking. (it works)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: 
    Chrome Version 105.0.5195.125 (Official Build) (arm64)
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/NordSafety.Portal/NordSafety.Portal/quentic-app-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base: ^5.0.0-alpha.95 => 5.0.0-alpha.95
    @mui/core-downloads-tracker:  5.10.3
    @mui/icons-material: ^5.8.4 => 5.10.2
    @mui/lab: ^5.0.0-alpha.97 => 5.0.0-alpha.97
    @mui/material: ^5.10.3 => 5.10.3
    @mui/private-theming:  5.10.3
    @mui/styled-engine:  5.10.3
    @mui/system:  5.10.3
    @mui/types:  7.2.0
    @mui/utils:  5.10.3
    @mui/x-data-grid:  5.17.1
    @mui/x-data-grid-pro:  5.17.1
    @mui/x-date-pickers: ^5.0.2 => 5.0.2
    @mui/x-date-pickers-pro: ^5.0.2 => 5.0.2
    @mui/x-license-pro:  5.17.0
    @types/react: 18.0.17 => 18.0.17
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: ^5.3.5 => 5.3.5
    typescript: ^4.7.4 => 4.7.4

```
</details>

**Comment by flaviendelangle** [comment]
Indeed...

We are currently working on new keyboard editing components and I worked on an implementation not loosing the timezone.
I will mark this issue as solved by my PR because we won't be able to push a fix that important to the current mask implementation.

**Comment by rottabonus** [comment]
Thank you @flaviendelangle, great work!
