### ISSUE TITLE
[data grid] singleSelect multiple values, filter closes on outside click

### ISSUE THREAD

**Issue by bowann** [mui/mui-x#6213]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When selecting multiple values in a "Is any of" filter, and click Add filter button, the filter modal closes

### Expected behavior 🤔

When selecting multiple values in a "Is any of" filter, and click Add filter button, the filter modal stays open.

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-data-grid/filtering/#multi-filtering

Steps:
1. select contry prop
2. select "Is any off"
3. select more the 3 countries 
4. click Add filter button

### Context 🔦

We cant give the user the option to use Is any off, we know that tab fises the issue og a fine click in the same "row" but we cant teach our users how to, and have to turn off the feature for now.

see. example video from documentation https://mui.com/x/react-data-grid/filtering/#multi-filtering

https://user-images.githubusercontent.com/7488687/191011224-0cc7311e-42fb-474b-ab2a-998df2c6c8f3.mov

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

49270

**Comment by katielbarker** [comment]
Hi, we are also facing this issue and it's a common workflow for our customers. Order number 47839

**Comment by cherniavskii** [comment]
Same issue reported in https://github.com/mui/mui-x/issues/6854

**Comment by nazariykcap** [comment]
@cherniavskii Do you have any updates on this? or at least is it planned to be fixed?
