### ISSUE TITLE
Incorrent props type for GridPagination

### ISSUE THREAD

**Issue by scott-avery** [mui/mui-x#6231]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Wrong definition for GridPagination props, see 
https://github.com/mui/mui-x/blob/d94c20e7471ca9b3bb4e889cd2e907868b942434/packages/grid/x-data-grid/src/components/GridPagination.tsx#L27-L29

now it's `React.HTMLAttributes<HTMLDivElement>`, wrong generic type for `forwardRef`

### Expected behavior 🤔

it should be subtype of props type of TablePagination

### Steps to reproduce 🕹

not needed

### Your environment 🌎

not needed

**Comment by cherniavskii** [comment]
Hey @scott-avery 
Indeed, it should use `TablePaginationProps` instead:

```diff
- React.HTMLAttributes<HTMLDivElement>
+ Partial<TablePaginationProps>
```

Are you using `GridPagination` directly for some kind of customization?
Can you share more details about your use case?

**Comment by scott-avery** [comment]
@cherniavskii yes, I have to wrap the `GridPagination` to add a page select, allowing user to go to specific page quickly. Currently that function is not available in official library.

**Comment by cherniavskii** [comment]
@scott-avery Thanks for the details!
By the way, there's a demo using [Material UI `Pagination`](https://mui.com/material-ui/react-pagination/) component instead of default `TablePagination`: https://mui.com/x/react-data-grid/components/#pagination
Maybe you'll find it useful as well
