### ISSUE TITLE
[question] Cell Menu

### ISSUE THREAD

**Issue by MoonSulong** [mui/mui-x#6237]
### Order ID 💳

40719

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Just wondering if it is possible to add a cell menu like the column menu in the header? More specifically, hover the cell will show a button at the end, click that button will open a menu listing options for cell.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @MoonSulong 
Sure, you can create custom cell component using `renderCell` https://mui.com/x/react-data-grid/column-definition/#rendering-cells

If you're looking for per-row actions menu - check out `actions` column type: https://mui.com/x/react-data-grid/column-definition/#special-properties
