### ISSUE TITLE
[data grid] How Should I implement a paste csv row action.

### ISSUE THREAD

**Issue by jalehoux** [mui/mui-x#6241]
### Order ID 💳

4720

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a workflow that requires users to enter in a lot of csv data into an editable datagrid. We have a Datagrid that has editable fields.  We also are following the Full-Crud example where have an actions column where we set RowMode to edit or view based on button click.  I am trying to understand the flow to programmatically set the rows from pasted values.  As of now I was considering for simplicity a paste button that will automatically set the single row based on clipboard values. I am using rowMode for editing.         

There are a lot of API's and I managed to get this working with the processRowUpdate api however this completely bypasses any validations that are linked to the column and so causes some bad data that is allowed in the cells.  What api's should I be calling for programmatically updating all cells in a row, running it through validations, then committing the data if successful.  If it fails validation it should show in edit mode in uncommitted state, success.

Here is a super basic sandbox of what I am doing: https://codesandbox.io/s/wizardly-murdock-oz2156?file=/demo.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6.1
  npmPackages:
    @mui/icons-material: ^5.5 => 5.8.2 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.11.1 
    typescript:  4.2.3 
```
</details>

**Comment by cherniavskii** [comment]
Hey @jalehoux 

I think the general idea would be to use `apiRef.current.setEditCellValue` to set the edit value for each columns:
```tsx
const csvLine = `1,whatever,2,CARTON`;
const values = csvLine.split(',');
const visibleColumns = apiRef.current.getVisibleColumns();
visibleColumns.forEach(({ field, type }, index) => {
  if (type === 'actions') {
    return;
  }
  const value = values[index];
  apiRef.current.setEditCellValue({
    id,
    field,
    value,
  });
});
```

The mapping between csv string and columns is kind of fragile, but I don't see how this can be improved.

Here's a basic demo: https://codesandbox.io/s/modern-violet-knhk0u

What do you think?

**Comment by jalehoux** [comment]
Great thanks.  So it looks like setEditCellValue is there way to go here.  Great.   This will work.  

Though I agree with you that the mapping between clipboard and the cells is sketchy at best.  

Follow up.  Is there any plan to add excel like copy and pasting.  For example you can highlight multiple cells and copy or paste into those cells.  As seen here on the AG Datagrid. https://www.ag-grid.com/example

**Comment by cherniavskii** [comment]
Yes, we plan to add both [Range selection](https://mui.com/x/react-data-grid/selection/#range-selection) and [Clipboard](https://mui.com/x/react-data-grid/export/#clipboard) features
