### ISSUE TITLE
[DataGridPro] - Filter Toolbar tooltip shows 'undefined' for 'is Empty' and 'is Not Empty' operators

### ISSUE THREAD

**Issue by putnamn21** [mui/mui-x#6246]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

in the datagrid toolbar filters button, the tooltip that displays a summary of filters applied to the grid will display `[column title] is empty undefined` if you picked a is empty or is not empty filter operator

### Expected behavior 🤔

it just displays [column] is empty in the tooltip

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/x/react-data-grid/filtering/
2. Filter a column with isEmpty or isNotEmpty operator
3. hover over the filter button in the toolbar to see the tooltip
4. note that 'undefined' is displayed in the tooltip

### Order ID 💳 (optional)

44631

**Comment by putnamn21** [comment]
it seems uploading a image is currently broken on github else i would include a screenshot. My console shows `POST https://github-production-user-asset-6210df.s3.amazonaws.com/ net::ERR_CERT_COMMON_NAME_INVALID` when attempting to upload a jpg or png

**Comment by cherniavskii** [comment]
Thanks @putnamn21 
I can confirm it's a bug.

<img width="422" alt="Screenshot 2022-09-22 at 16 43 22" src="https://user-images.githubusercontent.com/13808724/191778047-41958272-a803-4447-892d-fdf00078cfba.png">
