### ISSUE TITLE
[data grid] Cannot read properties of undefined (reading 'groupId') when hiding all columns in a data-grid with a column group

### ISSUE THREAD

**Issue by Olimarrex** [mui/mui-x#6255]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The grid throws the error:
```
Error in /turbo_modules/@mui/x-data-grid@5.17.3/node/hooks/features/columnHeaders/useGridColumnHeaders.js (377:71)
Cannot read properties of undefined (reading 'groupId')
```

### Expected behavior 🤔

All columns should be hidden, and no error thrown.

### Steps to reproduce 🕹

[Link to live example](https://codesandbox.io/s/spring-wildflower-h15cuh?file=/demo.tsx)

Steps:
1. Open Burger Menu
2. Open Show Columns
3. Press Hide All

This does not occur when hiding each column individually, so long as the last hidden column is not part of a column group.

### Context 🔦

x

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 927.42 MB / 15.79 GB
  Binaries:
    Node: 18.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 20.2.3 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    Git: 2.25.1.
    FFmpeg: 4.3.1 - C:\ProgramData\chocolatey\bin\ffmpeg.EXE
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom    
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.11.32106.194 (Visual Studio Professional 2019), 17.2.32519.379 (Visual Studio Professional 2022)
  Languages:
    Java: 1.8.0_282
    Python: 3.9.4
  Databases:
    SQLite: 3.32.2 - C:\Users\Max\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
```
</details>

**Comment by cherniavskii** [comment]
Hey @Olimarrex 
I can reproduce it with this demo: https://codesandbox.io/s/spring-wildflower-h15cuh?file=/demo.tsx


https://user-images.githubusercontent.com/13808724/191808653-13a08f42-4f1b-4be5-a03b-e21bbf6fc292.mov

cc @alexfauquette

**Comment by alexfauquette** [comment]
Yes, I did not consider the case of a grid with no column.

I assume it's [this line](https://github.com/mui/mui-x/blob/999d681583639805239b8bd290d146121f682a7c/packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L449:L449) the problem. 

The best fix could be to do an early return if there is no column to display

**Comment by Abhimanyuv92** [comment]
Is there any fix for this ? I am blocked with this hide all issue in grouped columns from long time.

**Comment by alexfauquette** [comment]
This issue was closed 2 years ago. Please consider opening a [new issue](https://github.com/mui/mui-x/issues/new/choose) instead of leaving a comment here.

This will help the team to track progress on fixing your issue
