### ISSUE TITLE
Selecting a year or a month changes the date value before selecting the day

### ISSUE THREAD

**Issue by Asghwor** [mui/mui-x#6258]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In a `DesktopDatePicker` with the year, month and day views, selecting a year will change the date before the user can select a month or a day. Selecting a month will also change the date before the user is able to select the day.

https://user-images.githubusercontent.com/30949004/191771586-849f5900-cb79-4255-86a3-35d361410003.mp4

This can be particularly bad when the datepicker is used to generate content that's expensive to render.

### Expected behavior 🤔

Selecting the year and the month would not change the date. It would only change when selecting the day.

If the views were different like, say, month and year, only selecting the month would change the date.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/gracious-darkness-txjdo1?file=/demo.tsx

Steps:
1. Open datepicker.
2. Select year.
3. Notice date has changed based on the year.
4. Select month.
5. Notice date has changed again to reflect the selection.
6. Select day.
7. Notice date has changed one last time.

### Context 🔦

I have a component that's generated based on a range between dates, and having the date change multiple times on selection causes stutters and delays while selecting a date.

**Comment by flaviendelangle** [comment]
Duplicates #6161

You can listen to `onChange` to update a state only passed to the picker and listen to `onAccept` for your expensive work (it will be fired when the change comes from the last step of the selection).
But I agree that we should provide a better out of the box behavior.
