### ISSUE TITLE
[pickers] How to set `styleOverrides` on the calendar icon

### ISSUE THREAD

**Issue by Balour** [mui/mui-x#6260]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The elements with slot names of DatePicker do not reflect the CSS given by the theme

### Expected behavior 🤔

CSS given to styleOverrides in the theme config should be passed and applied to the DatePicker element

In this specific case, all I want is for the Calendar Icon to be green (the other properties are attempts to get some CSS to apply somewhere

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/pensive-cache-ru3k3m?file=/demo.tsx 

Steps:
1. Simply viewing the result

### Context 🔦

We have wanted to color the Icon since we upgraded to mui 5 but couldn't because there were no overrides. Saw that they were added with https://github.com/mui/mui-x/pull/6156 so figured I'd get that working but couldn't in our project.

I grabbed the codesandbox from here https://github.com/mui/mui-x/issues/6218#issuecomment-1251993485 as a base, made sure everything was "latest" and used the Component name and Slot name found in the doc https://mui.com/x/api/date-pickers/date-picker/#slots

Surely I must be missing something here, MuiPickersCalendarHeader is working right beside it... Am I using the wrong name for something?

Thank you for your time

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser:
    Brave
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.13.2 - ~\Desktop\isovision-web-ui-mui5\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3
    @emotion/styled: ^11.9.3 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.4 => 5.8.4
    @mui/lab: ^5.0.0-alpha.88 => 5.0.0-alpha.88
    @mui/material: ^5.8.6 => 5.8.6
    @mui/private-theming:  5.8.6
    @mui/styled-engine:  5.8.0
    @mui/styles: ^5.8.6 => 5.8.6
    @mui/system:  5.8.6
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-date-pickers: ^5.0.2 => 5.0.2
    @types/react:  17.0.47
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript:  4.8.3

```
</details>

**Comment by flaviendelangle** [comment]
Hi

You can style the `button` not the `icon`.
[Here is a working example](https://codesandbox.io/s/dry-cherry-ms6de0?file=/demo.tsx)

Right now, you don't have a class specific for the left and right icon.
But you can use the `:first-child` and `:last-child` selector [as displayed here](https://codesandbox.io/s/wonderful-sea-mhh68x?file=/demo.tsx)

I how it answers your question.

I agree that for now this is poorly documented, we wanted to release the feature quickly but we will have to improve it in the future.

**Comment by Balour** [comment]
> You can style the `button` not the `icon`. [Here is a working example](https://codesandbox.io/s/dry-cherry-ms6de0?file=/demo.tsx)

As long as I can apply color I'm a happy camper

> Right now, you don't have a class specific for the left and right icon. But you can use the `:first-child` and `:last-child` selector [as displayed here](https://codesandbox.io/s/wonderful-sea-mhh68x?file=/demo.tsx)
> 
> I how it answers your question.

Unfortunately no, you missed applying CSS to the only element I need to change, the calendar button. I shouldn't have left the other bits of CSS and kept exclusively the CSS for the calendar Icon, the rest acted a bit like a red herring haha. Is there a component name  that refers to that button? Or is there no way to put color on the calendar button?

It should look like this:
![image](https://user-images.githubusercontent.com/10344265/191958324-4f8f432b-48ee-4ec0-a489-7205013499e7.png)

giving it our app's color accent

thanks for looking into it

**Comment by flaviendelangle** [comment]
You are right, I don't see any class passed to that element

**Comment by LukasTy** [comment]
Hello @Balour
I see that you are using TS, hence, you should be able to see that `styleOverrides` for `MuiDatePicker` has type of `never`.
In other words, such components don't have any `styled` components in them that we could allow overriding the styles of.

With #6156 we only fixed inconsistencies with which `styled` components were overridable and their `themeAugmentation` typings.

In your mentioned case - indeed, there is no clear way to override styles of the button/icon via `styleOverrides`.
What do you think about using `OpenPickerButtonProps` in the mean time?
You can pass it either from theme (if you don't set this prop on the component itself anywhere):
```tsx
MuiDatePicker: {
  defaultProps: {
    OpenPickerButtonProps: {
      sx: {
        color: '#47aa42'
      }
    }
  },
},
```
Or, you can also set it directly on a `DatePicker` component—as I imagine you might have your own DatePicker component in the app—wrapping the MUI component.
```tsx
<DatePicker
  ...
  OpenPickerButtonProps={{
    sx: {
      color: '#47aa42'
    }
  }}
/>
```

**Comment by Balour** [comment]
> Hello @Balour I see that you are using TS, hence, you should be able to see that `styleOverrides` for `MuiDatePicker` has type of `never`. In other words, such components don't have any `styled` components in them that we could allow overriding the styles of.

Unfortunately no not in our project, the TS is from the original codesandbox

> With #6156 we only fixed inconsistencies with which `styled` components were overridable and their `themeAugmentation` typings.
> 
> In your mentioned case - indeed, there is no clear way to override styles of the button/icon via `styleOverrides`. What do you think about using `OpenPickerButtonProps` in the mean time? You can pass it either from theme (if you don't set this prop on the component itself anywhere):
> 
> ```tsx
> MuiDatePicker: {
>   defaultProps: {
>     OpenPickerButtonProps: {
>       sx: {
>         color: '#47aa42'
>       }
>     }
>   },
> },
> ```

That's a hole in one for us, thanks a lot! We only have one theme for now so it fits our use case

I get to learn about "defaultProps" so that's cool, I thought all overrides went through styleOverrides so my bad on that though those classes like "OpenPickerButtonProps" are hard to find in the documentation, I guess that's where TS helps bridge the 2

Thanks again for your time!

**Comment by LukasTy** [comment]
Glad we could find a working middle ground for you. 👍 

>  I thought all overrides went through styleOverrides so my bad on that though those classes like "OpenPickerButtonProps" are hard to find in the documentation

`OpenPickerButtonProps` is not a class/style, but a property allowing to pass props to the button you want to style.
All the props of the components are documented in their respective [API pages](https://mui.com/x/api/date-pickers/date-picker/).
`styleOverrides` are for overriding styles of `styled` components, whereas `defaultProps` allows for default component props initialisation based on your app needs.

Although you are correct, without TS you would need to experiment to see what actually works. 😃

**Comment by Balour** [comment]
Ahhh I see it now, thanks for the clarification 

Have a nice day 😄

**Comment by DonikaV** [comment]
Doesnt work in the latest version, is anybody know how to add ID to the calendar button?

**Comment by LukasTy** [comment]
> Doesnt work in the latest version.
> So now it should be like this

You are correct! Thank you for clarifying. 🙏 
On v6 we dropped most of the props that were being passed down to certain sub-components. Starting v6, most of those cases are handled by providing a `slotProps` for a certain slot. 👌

**Comment by LukasTy** [comment]
> May I ask why is DatePicker not a styled component? Is it by choice, or by lack of time to implement it? Is it also true for all other mui x components?

All the components that have any styling applied to them or do support style overriding are `styled` components.
Root components such as the `Mobile`, `Desktop`, and `Static` pickers are not styled, because they only exist to compose all the necessary defaults and call the pickers rendering.

What would you expect to solve/achieve by having the root component possible to receive style overrides?

**Comment by PierreTurnbull** [comment]
Why can't we use the theme's style overrides?

**Comment by LukasTy** [comment]
You can, it's just that these styles are applied by specifying the `Paper` component props in our codebase, hence, altering them is the cleanest solution.
If you prefer, you can specify them using the theme like [in this example](https://codesandbox.io/s/smoosh-water-24qn4t).
You can also achieve similar result by uncommenting `styleOverrides`.

**Comment by LukasTy** [comment]
Paper is the parent element of all the rendered picker content, if you'd apply `display: 'none'` to it, you'd hide everything inside of it.

> instead of having to either modify the Paper style (which is not what I want since it has an impact on other components) 

Could you clarify what more does my suggest snippet impact? It specifically targets props or style only on the `desktopPaper` used in pickers. 🤷 

> Btw I could not make work your example, even with the style override :(

Could you provide a reproduction example? I'm not sure that there is any more clear way to show, how to implement a certain case than a live working example. 🤔

**Comment by LukasTy** [comment]
> The reason I could not make your example work in my code was that I was applying this V5 code to my V4 theme, which of course does not support it.

Clarification: my example uses v6 (latest) version of pickers, but it did not introduce any major styling paradigm differences from v5. 👌 



> Until we do a proper migration, I wrapped the app with a V5 theme, on top of the V4 theme, and it works fine:

Glad you were able to resolve your concern and technically already started the migration towards v5. 👍
