### ISSUE TITLE
[data grid] forwardRef on GridRow

### ISSUE THREAD

**Issue by nickbar86b** [mui/mui-x#6262]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We are trying to override DataGridPro Row using 
```
  components={{
    Row: TootlipedRow,
  }}
  const TootlipedRow = (
    params: React.HTMLAttributes<HTMLDivElement> & GridRowProps
  ) => {
    return (
      <Tooltip placement={'bottom'} title={'Transfer details'}>
         <GridRow {...props} />
      </Tooltip>
    );
  };
```
The above is generating the following error
_"Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?"_
According to documentation any MUI component can be used https://mui.com/material-ui/guides/composition/#caveat-with-refs.

### Expected behavior 🤔

Errors should not be raised when using Composition with Mui components

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

50436

**Comment by nickbar86b** [comment]
In addition we have noticed that enclosing GridRow in a tooltip breaks scrolling behaviour and some other functionalities. Is there any api documentation describing how we can override Row component?

**Comment by m4theushw** [comment]
Forwarding the ref to the root element of `GridRow` is also part of #6008

> In addition we have noticed that enclosing GridRow in a tooltip breaks scrolling behaviour and some other functionalities. Is there any api documentation describing how we can override Row component?

What do you mean by "breaks scrolling behavior"? Without the ref being forwared the Tooltip doesn't work correctly.

**Comment by nickbar86b** [comment]
> Forwarding the ref to the root element of `GridRow` is also part of #6008
> 
> > In addition we have noticed that enclosing GridRow in a tooltip breaks scrolling behaviour and some other functionalities. Is there any api documentation describing how we can override Row component?
> 
> What do you mean by "breaks scrolling behavior"? Without the ref being forwared the Tooltip doesn't work correctly.

Yeah, you are right about the ref. Practically, when scrolling down while pointer is on the grid, if tooltip is activated scrolling becomes flunky and the grid is scrolling up to put into view the tooltip
