### ISSUE TITLE
scrollToIndexes does not work with pagination

### ISSUE THREAD

**Issue by jorgenhovind** [mui/mui-x#6290]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Have a paginated table
2. run `scrollToIndexes` on a table where the indexed row is not on the current page

### Current behavior 😯

Nothing happens

### Expected behavior 🤔

Should navigate to the relevant page and scroll to the row

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 8.13.1 - ~/development/chainalysis/storyline/node_modules/.bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6.1
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4
    @emotion/styled: 11.10.4 => 11.10.4
    @mui/base:  5.0.0-alpha.84
    @mui/icons-material: 5.8.3 => 5.8.3
    @mui/lab: 5.0.0-alpha.85 => 5.0.0-alpha.85
    @mui/material: 5.8.3 => 5.8.3
    @mui/private-theming:  5.8.6
    @mui/styled-engine:  5.8.0
    @mui/system:  5.8.6
    @mui/types:  7.1.4
    @mui/utils:  5.10.3
    @mui/x-data-grid:  5.17.1
    @mui/x-data-grid-pro: 5.17.1 => 5.17.1
    @mui/x-date-pickers:  5.0.0-alpha.1
    @mui/x-license-pro:  5.17.0
    @types/react: ^17.0.30 => 17.0.47
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: 5.3.5 => 5.3.5
    typescript: 4.6.4 => 4.6.4
```
</details>

**Comment by m4theushw** [comment]
`apiRef.current.scrollToIndexes` doesn't work that way. Its job is to only scroll to a row in the current page. You need to manually change the page before calling it to achieve the behavior you described.
