### ISSUE TITLE
[data grid] Possible to Persist row collapse/expansion when data changes?

### ISSUE THREAD

**Issue by tnoetzel** [mui/mui-x#6314]
### Order ID 💳

51562

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I've been playing with row grouping, and I've noticed that if the data updates (via updating the `rows` prop) , rows will collapse or expand back to their default state (based on `defaultGroupingExpansionDepth`).

While there's a way to control the grouping _model_, I can't find a way to control the grouping state.

Is there a way to force the data-grid to remember / persist the state of the expanded / collapsed rows?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.9.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Edge: Not Found
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.6.0 => 11.6.0 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.92 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/material: ^5.1.0 => 5.10.0 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine:  5.10.0 
    @mui/system:  5.10.0 
    @mui/types:  7.1.5 
    @mui/utils:  5.10.6 
    @mui/x-data-grid:  5.17.4 
    @mui/x-data-grid-premium: ^5.17.4 => 5.17.4 
    @mui/x-data-grid-pro: ^5.15.2 => 5.17.4 
    @mui/x-license-pro:  5.17.0 
    @types/react: ^17.0.20 => 17.0.20 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.4.2 => 4.4.2 
```
</details>

**Comment by flaviendelangle** [comment]
Hi

If you update the `rows` prop, the grid will update all its rows and loose there state.
If you want to add / remove / update some rows, you can use the `apiRef.current.updateRows` method.

Here is a working example, if you open any group, is should state opened after adding "Toy Story 4": https://codesandbox.io/s/data-grid-premium-forked-4de8zr?file=/package.json

**Comment by tnoetzel** [comment]
Super helpful!

That said, it'd still be nice to preserve which groups are open/closed for a user between sessions. Any way to do this?

**Comment by flaviendelangle** [comment]
You have a temporary solution in https://github.com/mui/mui-x/issues/4930#issuecomment-1131853289
Maybe we could improve the built in solution at some point
