### ISSUE TITLE
[LocalizationProvider] changing locale doesn't update GridToolbarFilterButton

### ISSUE THREAD

**Issue by samordoch** [mui/mui-x#6326]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

i have a custom toolbar 
![image](https://user-images.githubusercontent.com/61991734/193032132-2e69abee-0d9f-4190-a401-b5777afc63b2.png)
that is under themeProvider with local 
![image](https://user-images.githubusercontent.com/61991734/193032414-6ba3a75e-e1db-431b-a298-60ed953d2bde.png)
when I change locale the filter button title and text is not affected 
![image](https://user-images.githubusercontent.com/61991734/193033070-04f88496-e9df-4a60-bad4-a3fcd373316a.png)

### Expected behavior 🤔

button text should be translated as in the row count below 

### Steps to reproduce 🕹

Link to live example:

Steps:
1. use a custom toolbar with GridToolbarFilterButton
2. surround with theme provider 
3. change local
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.53)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.75
    @mui/core-downloads-tracker:  5.10.4
    @mui/icons-material: ^5.8.2 => 5.8.2
    @mui/lab: ^5.0.0-alpha.76 => 5.0.0-alpha.76
    @mui/material: ^5.6.0 => 5.10.4
    @mui/private-theming:  5.10.3
    @mui/styled-engine:  5.10.4
    @types/react: ^17.0.43 => 17.0.43
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.5 => 5.3.5
    typescript: ^4.5.5 => 4.5.5
```
</details>

**Comment by alexfauquette** [comment]
Could it be linked to  #4119

I don't see a specific problem on filtering button. It is just late of 1 rendering loop like others in this demo
https://codesandbox.io/s/elegant-sea-1x5fxj?file=/demo.tsx
