### ISSUE TITLE
[pickers] Allow replacing input with anything (not just a custom input)

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#6330]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I had to do this ugly-looking workaround to achieve this:

```tsx
renderInput={({ inputRef, inputProps, InputProps }) => {
	return (
		<Button
			ref={inputRef}
			onClick={InputProps.endAdornment.props.children.props.onClick}
		>
			I want this button to open the calendar
		</Button>
	);
}}
```

And I think there should be a better way of doing this

### Examples 🌈

![image](https://user-images.githubusercontent.com/17963791/193077958-538b85ed-d0cb-409e-be59-436a736bdcc9.png)

### Motivation 🔦

For me, value selection value is shown in a completely different way, and I just need a button to host the datePicker.

**Comment by alexfauquette** [comment]
Wha about using the `open` `onOpen` `onClose` props to control the opening state?

**Comment by MonstraG** [comment]
Well, I need to "attach" the picker to the button, and manually control the open state, so this is less convinient than the hack.
