### ISSUE TITLE
DateRangePicker: Selecting days in week which span over month result in highlighting blank columns in other month. 

### ISSUE THREAD

**Issue by Ambrish-git** [mui/mui-x#6332]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I select dates of last week of Sep 2022, it also get highlighted in month of Oct with blank days. I have attached the screenshot from the MUI example for more clarity.
Customized day rendering section: https://mui.com/x/react-date-pickers/date-range-picker/#customized-day-rendering

<img width="506" alt="image" src="https://user-images.githubusercontent.com/51455372/193117844-64f4f090-cd3c-4e64-9910-7e089ba72ca2.png">

### Expected behavior 🤔

it should not highlight the days which are not displayed in other month.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/date-range-issue-o3z7cc

Steps:
1. Select dates from from 25th Sep 2022 to 30th Sep 2022.
2. Blank days will be highlighted in the month of Oct 2022 1st week.

### Context 🔦

I was exploring the features provided by date range picker and found this issue.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
The component you override has [a prop `outsideCurrentMonth`](https://mui.com/x/api/date-pickers/pickers-day/#props) that allows you to know if the day is outside of the current month. 

Not overriding styles when `outsideCurrentMonth===true` should solve your issue

**Comment by Ambrish-git** [comment]
@alexfauquette Thanks, it worked.
