### ISSUE TITLE
[DatePicker] Add standard and filled variants

### ISSUE THREAD

**Issue by Nic-S** [mui/mui-x#6334]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Add standard and filled variant like other Mui inputs

### Motivation 🔦

To maintain consistency with applications that use standard and filled variants for other inputs (select, textField, etc.).

**Comment by alexfauquette** [comment]
I don't understand what you mean. You can already customize the input as you want

https://codesandbox.io/s/tender-lovelace-pe3wng?file=/demo.tsx
