### ISSUE TITLE
[data grid] Row Grouping need event for expanding/collapsing

### ISSUE THREAD

**Issue by scott-avery** [mui/mui-x#6335]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently there is not event defined when row group expanded or collapsed.

### Motivation 🔦

We need to know that state change signal to cached the expand state and restore it when data refresh.

**Comment by flaviendelangle** [comment]
You can use the `rowExpansionChange` event
It is marked as internal but if there is a use case for it we could totally make it public and document it.

**Comment by scott-avery** [comment]
cool, I've managed to subscribe the event via `GridApi`

**Comment by AndreSilva1993** [comment]
We would definitely benefit from this event as well!
