### ISSUE TITLE
StaticDateTimePicker AM/PM buttons display outside container

### ISSUE THREAD

**Issue by tomvrampio** [mui/mui-x#6338]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

AM/PM buttons display outside container, positioned bottom left/right of the page, like little FABs.

### Expected behavior 🤔

AM/PM buttons to be inside the card, just underneath the clock. Or in the clock, if prop 'ampmInClock' is true - but this just moves them up slightly.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/staticdatetimepickerampm-xdz8fu?file=/demo.js

This is forked from the demo in the docs

### Context 🔦

Content of the card needs to be inside the card, or a user isn't going to see it as related.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Windows 11, Chrome
```
</details>

### Order ID 💳 (optional)

49717

**Comment by alexfauquette** [comment]
Sounds related to #4947

The time we fix the bug, you can use the following code to fix in in your codebase

```
sx={{
  "& .MuiClock-root ": { position: "relative" },
  "& .MuiClock-pmButton": {
    bottom: 0,
    right: 0
  },
  "& .MuiClock-amButton": { bottom: 0, left: 0 }
}}
```

**Comment by tomvrampio** [comment]
Thanks for the workaround, and apologies that I didn't find that other issue

**Comment by alexfauquette** [comment]
No problem I'm closing this issue to avoid duplication
