### ISSUE TITLE
[DataGrid] Hidden columns

### ISSUE THREAD

**Issue by atomcorp** [mui/mui-x#6340]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When hiding a column using both the `initialState` and `columns` props, showing that column then resizing it makes it hide again.

### Expected behavior 🤔

It should just resize and remain visible.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/thirsty-bassi-mm7zz6?file=/demo.tsx

Steps:
1. Use the Show columns option to show the `ID` column
2. Resize the `ID` column

### Context 🔦

I want to use the initialState prop so users can save their config. However I also want a default configuration.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
This `hide` property [is deprecated](https://mui.com/x/react-data-grid/column-visibility/#column-hide-property-deprecated) and has already been removed in v6 alpha.

If you want to have a default setting and restore the user state, it may be better to do it as follow than mixing two source of truth

```jsx
const initState = {
  columns: {
    columnVisibilityModel: userSavedColumnVisibility ?? defaultColumnVisibility
      id: false
    }
  }
};
```

**Comment by atomcorp** [comment]
Thank you for the quick response! That's useful to know it's getting removed, appreciate it.

**Comment by alexfauquette** [comment]
@atomcorp Is their a doc/tutorial introducing the `hide` without warning it will be deprecated?
