### ISSUE TITLE
[docs] Layout shift due to initial focus on StaticDatePicker

### ISSUE THREAD

**Issue by siriwatknp** [mui/mui-x#6343]
The date picker auto-focus causes the home page layout to shift.

https://user-images.githubusercontent.com/18292247/193400051-22fb3c26-a007-4853-9783-c1544350e0e8.mov

> Note: I [temporarily removed the date picker](https://github.com/mui/material-ui-docs/commit/ea1a6ae7064436bfdf159345af1c697603d3dd30) from the homepage, so you won't be able to test the production.

I have checked the [date picker](https://mui.com/x/react-date-pickers/date-picker/) page, the first visit also focuses on the `StaticDatePicker`.

Step to reproduce:
1. Go to https://mui.com/x/react-date-pickers/date-picker/
2. You will initially see `Static mode` instead of the top of the page.
3. Press the key left, right.

**Comment by flaviendelangle** [comment]
I'd say that https://github.com/mui/mui-x/pull/6304 fixed it (@alexfauquette)

**Comment by siriwatknp** [comment]
> I'd say that #6304 fixed it (@alexfauquette)

Is the autofocus enabled by default?

**Comment by siriwatknp** [comment]
Another question, what's the version that will include the fix?

**Comment by flaviendelangle** [comment]
> Is the autofocus enabled by default?

No it should not
But we had a bug that focused the view even without `props.autoFocus === true` (fixed in #6304)

> Another question, what's the version that will include the fix?

Should be on `@mui/x-date-pickers@v6.0.0-alpha.1`
But we can back-port it to v5 if necessary :+1:

**Comment by alexfauquette** [comment]
But the fix was for year pikers. I'm surprized it does the same for calendar
