### ISSUE TITLE
Date Picker Calendar Icon Disappear when InputProps added to render TextField

### ISSUE THREAD

**Issue by syazwanz** [mui/mui-x#6363]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I am using mui-x date picker with the render input using TextField https://mui.com/x/react-date-pickers/date-picker/#main-content

When I added InputProps at the TextField, the calendar icon disappear. 

### Expected behavior 🤔

The calendar icon should still appear at the date picker.

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/autumn-sea-r8wz9l

### Context 🔦

I am building form using mui-x date picker. I try to change the input font size by adding the InputProps at the TextField.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
I am using Google Chrome
  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.17.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.99 
    @mui/core-downloads-tracker:  5.10.7 
    @mui/icons-material: ^5.10.6 => 5.10.6 
    @mui/lab: ^5.0.0-alpha.101 => 5.0.0-alpha.101 
    @mui/material: ^5.10.7 => 5.10.7 
    @mui/private-theming:  5.10.6 
    @mui/styled-engine:  5.10.7 
    @mui/styles: ^5.10.7 => 5.10.7 
    @mui/system:  5.10.7 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.6 
    @mui/x-date-pickers: ^5.0.3 => 5.0.3 
    @types/react:  18.0.21 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

**Comment by alexfauquette** [comment]
### Why

Yes, that's because by setting your own `InputProps` you override our default ones. If you have a look into `params` you will see it contains a property `InputProps` that define the `endAdorment` which is adding the calendar icon

For example is you put your `InputProps` before the  `{...params}` the calendar will be back but your customization will be removed (It's the last definition of the props that is applied).

## How to fix

If you want to customize some input props and keep some of the default, you should restructure it as follow
```jsx
renderInput={({InputProps, ...params}) => <TextField 
	InputProps={...InputProps, ...myInputPropsOveride}
	{...params} 
/>}

// or

renderInput={(params) => <TextField 
	{...params} 
	InputProps={...params?.InputProps, ...myInputPropsOveride}
/>}
```

**Comment by syazwanz** [comment]
thanks alot @alexfauquette . that clarifies. I will closed this. Thanks again.
