### ISSUE TITLE
[pickers] Support to paste on the field components (when selecting one section)

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#6367]
### Summary 💡

When clicking on a section then doing `Ctrl + V`, the field should try to set the string you are pasting inside this section (and apply the same behavior as in the `onChange`).

**Comment by flaviendelangle** [comment]
Yes, I created this issue before https://github.com/mui/mui-x/pull/6422 but we forgot to link it

**Comment by alexfauquette** [comment]
Fixed by #6422
