### ISSUE TITLE
[DataGridPro] locale text does not set the filter format to the chosen locale

### ISSUE THREAD

**Issue by MyGuyCai** [mui/mui-x#6373]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Setting the locale to US
`<DataGridPro localeText={enUS.components.MuiDataGrid.defaultProps.localeText} />
`

Setting the formatter to use the US date format
```
columns = [        
        {
            field: 'aired.from',
            headerName: 'Flight Start',
            type: 'date',
            valueFormatter: ({ value }) => formatToUSDate(value),
            valueGetter: ({ row }) => row.aired.from,
        },
]
```
All data grid date filters display dd/mm/yyyy
![Screenshot 2022-10-03 at 16 13 33](https://user-images.githubusercontent.com/90213392/193613583-3ebfa0d8-ecad-4e53-a3fe-0ca544c7899b.png)

### Expected behavior 🤔

The data grid filter should be set the locale date format (ie mm/dd/yyyy for America)

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Set locale for DataGridPro
2. Select filter on date object
3. View wrong format

### Context 🔦

Attempting to hardcode the date format for filters in data grid.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browsers:
    Chrome: 106.0.5249.91
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.68 
    @mui/icons-material: ^5.4.1 => 5.4.1 
    @mui/lab: ^5.0.0-alpha.68 => 5.0.0-alpha.68 
    @mui/material: ^5.4.1 => 5.4.1 
    @mui/private-theming:  5.4.1 
    @mui/styled-engine:  5.4.1 
    @mui/styles: ^5.4.1 => 5.4.1 
    @mui/system:  5.4.1 
    @mui/types:  7.1.1 
    @mui/utils:  5.4.1 
    @mui/x-data-grid:  5.12.1 
    @mui/x-data-grid-pro: ^5.17.2 => 5.12.1 
    @mui/x-license-pro:  5.12.1 
    @types/react:  17.0.19 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.3.5 => 4.4.2 
```
</details>

**Comment by DanailH** [comment]
Hi @MyGuyCai please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!
