### ISSUE TITLE
[data grid]  DataGridPro - Multi Filtering

### ISSUE THREAD

**Issue by xnukes** [mui/mui-x#6398]
### Order ID 💳

51934

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello, we have purchased a datagrid pro license and I have a problem with filtering. I have created filtering outside the datagrid and I use setFilters from the merge type datagrid. If I only send one filter, that's fine. If two parameters are sent, a request to the api with these filters is made, and a second request without parameters is made immediately. Could you give me an advice please ?

### Your environment 🌎

  System:
    OS: macOS 12.6
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 106.0.5249.91
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.0
  npmPackages:
    @emotion/react:  11.10.4 
    @emotion/styled:  11.10.4 
    @mui/base:  5.0.0-alpha.97 
    @mui/core-downloads-tracker:  5.10.5 
    @mui/icons-material: ^5.8.3 => 5.10.3 
    @mui/lab:  5.0.0-alpha.99 
    @mui/material:  5.10.5 
    @mui/private-theming:  5.10.3 
    @mui/styled-engine:  5.10.5 
    @mui/system:  5.10.5 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.3 
    @mui/x-data-grid:  5.17.5 
    @mui/x-data-grid-pro: ^5.17.5 => 5.17.5 
    @mui/x-date-pickers: ^5.0.0-beta.5 => 5.0.2 
    @mui/x-license-pro:  5.17.0 
    @types/react: ^17.0.2 => 17.0.50 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.2.4 => 4.8.3

**Comment by yaredtsy** [comment]
@xnukes if I understand your question correctly. the issue you are facing is when you add a new filter onFilterModelChange is triggered immediately and the values fields are not there in the item. I have tried to reproduce your issue https://codesandbox.io/s/elated-http-6l5y8v?file=/demo.tsx:487-498.  is this the issue you facing?

**Comment by alexfauquette** [comment]
Thanks @yaredtsy for the example. I'm not sure to understand what is the bug. It make sens to call the onChnage with he `undefined` value, because for some filters (for example `'isEmpty'`) it's the only value it could get

**Comment by alexfauquette** [comment]
Thanks @yaredtsy for the example. I'm not sure to understand what is the bug. It make sens to call the onChnage with he `undefined` value, because for some filters (for example `'isEmpty'`) it's the only value it could get

**Comment by yaredtsy** [comment]
@alexfauquette I think he wants, the cell to look editable and wants to enable edit mode with a single click
