### ISSUE TITLE
[data grid] Data Grid Premium with Master-Detail and autoHeight has a missing border on last row

### ISSUE THREAD

**Issue by trorud** [mui/mui-x#6407]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using Master-Detail with autoHeight in Mui Data Grid Premium, the last row misses a border. All rows except the last one show a double border in between the tables - Chrome, latest version.

![image](https://user-images.githubusercontent.com/107988397/194318698-cd3f2f11-3d51-41c4-b815-2eaf5c46131e.png)

### Expected behavior 🤔

Consistent layout with 2 borders in between the master table row and the detail table.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/distracted-chatelet-55ju3p?file=/demo.tsx

Steps:
1. Open all the rows detail
2. See the missing border on the last row like in the screenshot attached

### Context 🔦

Building a business application using Mui Data Grid Premium with many Master-Detail-structures

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: master_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.53)
</details>

**Comment by MBilalShafi** [comment]
I can see a consistent behavior for all the rows with current version: https://codesandbox.io/p/sandbox/clever-architecture-w3zlyw

@trorud Could you confirm if that's the required behavior?
