### ISSUE TITLE
How to use filtering and sorting with row pinning.

### ISSUE THREAD

**Issue by omaratta212** [mui/mui-x#6414]
### Order ID 💳

50940

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm using pinned rows prop to pin some important rows to the top.
Problem is when I sort or filter on the data grid, these rows are not affected, I still need these rows to be pinned, but only the ones matching the current filter and I need them to be sorted just like the rest of the grid.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.6
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.7.1 => 11.9.3 
    @emotion/styled: ^11.6.0 => 11.9.3 
    @mui/base:  5.0.0-alpha.88 
    @mui/icons-material: ^5.2.5 => 5.8.4 
    @mui/material: ^5.2.7 => 5.8.7 
    @mui/private-theming:  5.8.6 
    @mui/styled-engine:  5.8.7 
    @mui/styles: ^5.2.3 => 5.8.7 
    @mui/system:  5.8.7 
    @mui/types:  7.1.4 
    @mui/utils:  5.10.6 
    @mui/x-data-grid: ^5.10.0 => 5.17.3 
    @mui/x-data-grid-pro: ^5.17.3 => 5.17.3 
    @mui/x-license-pro: ^5.17.0 => 5.17.0 
    @types/react: ^17.0.37 => 17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.5.3 => 4.7.4 

```
</details>

**Comment by yaredtsy** [comment]
@omaratta212 it's not supported yet. 
![image](https://user-images.githubusercontent.com/34584266/194504538-4766717f-45ed-4879-b761-c03c15a54d4f.png)
you can try a workaround here is an example https://codesandbox.io/s/sweet-swanson-k6hu8h?file=/demo.tsx

**Comment by omaratta212** [comment]
@yaredtsy Thanks for your reply, It would be awesome if that was supported inside MUI. 

I thought about this workaround, it's great for small set of features, but I'm actually using the multi sorting feature and also multi filtering, in order to make this workaround work I will kinda re-write a lot of the functionality that's already in MUI. So let's consider this a feature request, it would be really helpful.

**Comment by yaredtsy** [comment]
@omaratta212 I think there is already a ticket for it. @DanailH does this feature has an issue where we can upvote?

**Comment by cherniavskii** [comment]
Hey @omaratta212 
Pinned rows are not impacted by sorting or filtering by design, since they are not part of the row model (`rows` prop).
Can you share more details about your use case?
What are you trying to achieve by pinning the rows?
Thanks!

**Comment by omaratta212** [comment]
Hey @cherniavskii , Thanks for replying.

The business use case is that I need to show some rows first to get the user's attention as there is an action required for this rows. So even if the user sorted the list I need to have these rows first but I need them sorted. 

Think of it as 2 lists but in one view, each one needs to be filtered and sorted separately.
It would be great if we add some prop like `sortPinnedRows` and `filterPinendRows`.

**Comment by cherniavskii** [comment]
@omaratta212 
Interesting.
How many pinned rows can you have? I'm asking, because eventually you might get out of space for unpinned rows.

Did you consider using controlled sorting with a permanent sort criteria?
Here's a demo: https://codesandbox.io/s/musing-brook-0purob?file=/demo.tsx
You can see that the rows that have `isAdmin: true` are always at the top and you cannot change that. But you can sort using other columns, as well as filtering.
What do you think?

**Comment by omaratta212** [comment]
I think this covers my use case, the number of the rows aren't always constant it can be 2 or 20 or number of rows, that's why I wanted them filtered.

Thank you!
