### ISSUE TITLE
[pickers] Some methods don't use the locale passed to the adapter

### ISSUE THREAD

**Issue by shaliake** [mui/mui-x#6415]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.Import several moment locales e.g. ("moment/locale/lt", moment/locale/en-gb")
2.Create datetimepicker  localization provider and simple datetimepicker
3.Switch between locales using some trigger.

### Current behavior 😯

On locale change in datetimepicker **_Month_** labels changes, but **_Days_** abbreviations (M,T,...S) stays for lastly imported moment locale

### Expected behavior 🤔

**_Month_** and **_Day_** labels should switch to appropriate language/locale

### Context 🔦

Reproduced case can be found here:
[CodeSanbox](https://codesandbox.io/s/bold-feather-ri1ohw)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base:  5.0.0-alpha.100
    @mui/core-downloads-tracker:  5.10.8
    @mui/icons-material: ^5.10.3 => 5.10.3
    @mui/lab: ^5.0.0-alpha.102 => 5.0.0-alpha.102
    @mui/material: ^5.10.8 => 5.10.8
    @mui/private-theming:  5.10.6
    @mui/types:  7.2.0
    @mui/utils:  5.10.3
    @mui/x-date-pickers: ^5.0.3 => 5.0.3
    @types/react:  18.0.19
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0

```
</details>

**Comment by flaviendelangle** [comment]
This usage of moment locale is indeed problematic because some methods can't use a non-global local.
It is the case for `moment.weekdaysShort` which creates the day you mentionned.

One workaround would be to manually set moment local on your side every time it changes [like on this example](https://codesandbox.io/s/sweet-williams-ytlown?file=/demo.js).
That's not very satisfying but I don't see a better solution for now.

That's clearly something we should at least mention in the doc.

**Comment by shaliake** [comment]
No worries, I have switched to dayjs. But I am using both moment and dayjs atm so think I will have to stay with dayjs to drop a bit bundle size. Right now it's 650 kB :(

**Comment by flaviendelangle** [comment]
Having `moment` if you don't really need it is indeed very heavy.
Good luck for your migration to `dayjs` !
