### ISSUE TITLE
[pickers] New Date field components - Why doesn't onChange receive the error string?

### ISSUE THREAD

**Issue by rodrigofariow** [mui/mui-x#6421]
### Order ID 💳

33240

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hey there!

I have been playing with the new field components, mainly `DateField`, and I would like to understand the technical decision behind having the validation `error` string only available `onError`.

**Why do I find it difficult to work with?**
In some cases, mostly when using date pickers/fields to do searching on a table or list, I would like to only set the value `onChange` in case it is valid ("valid" meaning it respects validation of `maxDate`, `minDate`, etc).

Right now, I'm kind of forced to either:
- Always set the value `onChange`, regardless of it being valid (and thus I have to validate the changed value before, for instance, calling an endpoint)
   - Although this is achievable, it's not great because I have already passed the `maxDate`, `minDate`, etc props. Having to do that again through some other way is redundant.
- Try to do a mix of `onError` and `onChange` to try to get what I want which is not a reliable way to do it.

If `onChange` signature could become:
```tsx
onChange?: (value: TValue, error: TError) => void;
```
It would allow developers for all kinds of use cases.

What do you think about this?

Cheers!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.0
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4 
    @emotion/styled: 11.10.4 => 11.10.4 
    @mui/icons-material: 5.10.6 => 5.10.6 
    @mui/lab: 5.0.0-alpha.102 => 5.0.0-alpha.102 
    @mui/material: 5.10.8 => 5.10.8 
    @mui/system: 5.10.8 => 5.10.8 
    @mui/x-data-grid: 6.0.0-alpha.2 => 6.0.0-alpha.2 
    @mui/x-data-grid-generator: 6.0.0-alpha.2 => 6.0.0-alpha.2 
    @mui/x-data-grid-pro: 6.0.0-alpha.2 => 6.0.0-alpha.2 
    @mui/x-date-pickers: 6.0.0-alpha.2 => 6.0.0-alpha.2 
    @mui/x-date-pickers-pro: 6.0.0-alpha.2 => 6.0.0-alpha.2 
    @types/react: 18.0.21 => 18.0.21 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components: 5.3.5 => 5.3.5 
    typescript: 4.9.0-dev.20221007 => 4.9.0-dev.20221007 
```
</details>

**Comment by yaredtsy** [comment]
@rodrigofariow you can also check if its valid or not in the onChange event
`<TimePicker ...... onChange={(newValue) => { console.log(newValue?.isValid()); }} />`
check this example https://codesandbox.io/s/practical-ardinghelli-0jtct9?file=/demo.tsx

**Comment by rodrigofariow** [comment]
Hi @yaredtsy!

Thanks for the response!
I see. I assume this works for all supported date adapters right? I'm currently using luxon and indeed `DateTime` implements an `isValid` boolean.

Does not seem supported yet though but I'm happy if all date libs are supported when date fields reach stable 😄  ⏬ 
https://codesandbox.io/s/sad-estrela-tuseeu?file=/demo.tsx

**Comment by rodrigofariow** [comment]
> @rodrigofariow you can also check if its valid or not in the onChange event `<TimePicker ...... onChange={(newValue) => { console.log(newValue?.isValid()); }} />` check this example https://codesandbox.io/s/practical-ardinghelli-0jtct9?file=/demo.tsx

I actually tested with a `maxDate` and it's still considered valid. I think most libs just verify if it is a valid standardized date object and nothing else:
https://codesandbox.io/s/cold-bash-yg45hh?file=/demo.tsx

**Comment by LukasTy** [comment]
Hey @rodrigofariow 
Thank you for bringing this issue.

I'd agree, the current API is hard to work with.
I've tried creating a wrapper component storing `error` state and emitting that together with value change, but it's not trivial to implement correctly.
This is a very similar topic as the one we also currently have on when we should actually emit `onChange` event.

But with the current API a combination of validation and controlled value handling seems cumbersome on both current DatePicker components as well as new Field components.

What do you @flaviendelangle @alexfauquette think about this suggestion?
On the one hand, it would make sense to NOT emit `onChange` when validation fails (basically same as with DateField, while the input is not a complete or valid date).

What does seem a better DX for you @rodrigofariow in case a validation error is active on a date picker component?
- no `onChange` emitted
- like you suggested—`onChange` with an `error` parameter is emitted

**Comment by rodrigofariow** [comment]
Hey @LukasTy 

Thanks for the in depth feedback.

> What does seem a better DX for you @rodrigofariow in case a validation error is active on a date picker component?
no onChange emitted
like you suggested—onChange with an error parameter is emitted

I would rather have `onChange be called with an `error` parameter when there was an actual change on the date ( regardless of it respecting `maxDate` or not, for instance).

This allows developers to still have the option to  run another layer of validation themselves where needed (e.g - in a form through a zod schema).
I could probably do a mix of `onError` with `onChange`, if `onChange` was only emited on fully valid dates, but it gives more room to sneaky bugs IMO.

**Comment by alexfauquette** [comment]
I don't get for which use case you want to mix the `onChange` and `onError`. Are you trying to mix error message with the current date? or is it about knowing when the new date is in an invalid format?

> I see. I assume this works for all supported date adapters right? I'm currently using luxon and indeed DateTime implements an isValid boolean.

All adapter support that with `adapter.isValid(dateToTest)`

---

The idea behind this choice is to distinguish the value control and the error control
https://codesandbox.io/s/weathered-monad-uozg83

By the way, it seems there is some inconsistency between `onError` and `onChange` when the date is incomplete. If `onChange` is not called I would expect `onError` to be not called.

When entering the first sections, the error is called without the change. When I delete some sections, the error is not triggered

**Comment by flaviendelangle** [comment]
@rodrigofariow I'm curious, how did you end up using the field components ?
We did not document them publicly yet, did you look at the release notes ? Or played with your IDE autocompletion ?

In any case, I fully agree that for your use case, the current approach is not optimal.
I copied the logic from the existing pickers but we can have a look at if we want to improve it.

On the fields, `onChange` is called whenever it is possible to generate a date from the sections.

Small side note about that:
If you have `01/01/yyyy` and you press `2` in the `yyyy` section, it will fire `onChange` with the date `01/01/0002`.
I think that at some point we will have a discussion about the notion of filled section because in this scenario, it is quite obvious that the year is not filled. But I think it's good to always fire for now because it is simpler.


Back to our errors.
The fields have an internal state and do not need to be controlled, therefore if you ignore some `onChange` event, everything should be fine.
And I think that passing a 2nd argument with some context about the current date (for instance with an `didPassValidation`) can make sense.
It would not replace the `onError` which can be used independently like @alexfauquette pointed out, but for me `onError` is more useful to display the error on screen, not to decide if the date should be stored somewhere for instance.

**Comment by rodrigofariow** [comment]
>I don't get for which use case you want to mix the onChange and onError. Are you trying to mix error message with the current date? or is it about knowing when the new date is in an invalid format?

@alexfauquette  Sorry, my first comment when talking about `isValid` was a bit off topic.
What I really want is to know on `onChange` is if the new value respects all restrictions imposed on the field. 
These restrictions include stuff like the `maxDate` passed in as props and other restrictions of that kind. I don't care particularly if the date is `invalidDate` although that would be covered if you passed the same `error` string of type `DateValidationError` as you pass to `onError`.

**Comment by rodrigofariow** [comment]
Hey @flaviendelangle 

I have been keeping an eye on release notes and PRs on that subject :P 
But they are available when installing the 6 alpha version. For example, I can import:
```tsx
import {
  Unstable_DateField as DateField,
} from '@mui/x-date-pickers/DateField'
```

I'm fully aware they are not production ready or stable yet but I'm super interested on this topic. 

>Back to our errors.
The fields have an internal state and do not need to be controlled, therefore if you ignore some onChange event, everything should be fine.

I see. I prefer to use the controlled version whenever possible, though.

As for a possible introduction of a `didPassValidation`, it would be pretty nice. As I mentioned in https://github.com/mui/mui-x/issues/6421#issuecomment-1271817366 having an actual `error` string of type `DateValidationError`, or a subset of it, would allow for more use cases. If, for a technical reason, this is not possible, a flag like `didPassValidation` would do the trick though.

>It would not replace the onError which can be used independently like @alexfauquette pointed out, but for me onError is more useful to display the error on screen, not to decide if the date should be stored somewhere for instance.

Fully agree. I think some people will find `onError` more than enough for their use cases and don't need to control the field components value.

**Comment by flaviendelangle** [comment]
> I see. I prefer to use the controlled version whenever possible, though.

What I meant is that, even if you control, you could choose to ignore some `onChange` events (the one not passing the validation) without our component stop functioning ?

> having an actual error string of type DateValidationError, or a subset of it, would allow for more use cases.

It would probably be more versatile you are right.
If we know that if does not pass the validation, we also now the error so no problem forwarding it.

**Comment by rodrigofariow** [comment]
Awesome stuff @flaviendelangle!!
Thank you 🙏
