### ISSUE TITLE
[Feature] Ability to Reorder Columns through the GridToolbar Columns Menu. 

### ISSUE THREAD

**Issue by tielushko** [mui/mui-x#6426]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello MUI team, 

In addition to being able to switch the visibility of each of the columns with the switch buttons, I would like to have some sort of draggable list with an indicator that could propagate to the order of the grid columns. 

For our application, the grids are very wide, and sometimes dragging the column from one end to another could prove to be difficult.  

I was thinking when the menu "Columns" is open, the user can drag and drop the rows for each of the column name and that will change the order of the columns on the grid. 

Draggable list example: https://shopify.github.io/draggable/examples/simple-list.html

### Examples 🌈

Draggable list
https://shopify.github.io/draggable/examples/simple-list.html

AG Grid example (look at the right-hand side where you can use the column menu to drag and drop the columns.
https://www.ag-grid.com/example

### Motivation 🔦

Users have to take time and scroll from one end of a wide grid to another. 

Sometimes they feel frustrated when they end up dropping the column altogether.

### Order ID 💳 (optional)

31986

**Comment by yaredtsy** [comment]
@tielushko this is this small demo I have tried https://codesandbox.io/s/focused-nova-5fz8yc?file=/demo.js.

**Comment by DanailH** [comment]
Hi, @tielushko thanks for raising this!
We have an issue tracking this. It's been on the list for a while but we haven't seen much demand for it. We can see if it is time to add it. This is the original issue - https://github.com/mui/mui-x/issues/839. I'll close this one as it is a duplicate but you can upvote the linked issue so we know that there is demand for it.

@yaredtsy thanks for the example! One problem with this approach is that on each reorder you are rerendering the entire grid. It is a valid workaround but it won't work that well for grids with a lot of data. You can still use this approach but instead. of providing a new set of columns every time you reorder you can use the built-in API to change the position of just a single column - `setColumnIndex`.

**Comment by tielushko** [comment]
@yaredtsy Thank you for your example, I will make sure to check it out. 

@DanailH Thank you for your comment about the feature, my apologies for raising a duplicate issue. I will make sure to upvote the feature for it to be added in the future.
