### ISSUE TITLE
[data grid] Pressing arrow down and page down on an empty grid throws exception.

### ISSUE THREAD

**Issue by mbiggs-gresham** [mui/mui-x#6446]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Selecting a column header and then pressing cursor down on an empty grid causes an exception. 

### Expected behavior 🤔

No exception should be thrown.

### Steps to reproduce 🕹

Steps:
1. Create a grid with columns but no row data.
2. Click a column header so it becomes outlined.
3. Press cursor down.
4. Exception is thrown:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at useGridKeyboardNavigation.js:71:1
    at Object.current (useGridKeyboardNavigation.js:246:1)
    at EventManager.enhancedHandler (useGridApiEventHandler.js:39:1)
    at EventManager.emit (EventManager.js:71:1)
    at Object.publishEvent (useGridApiInitialization.js:36:1)
    at apiRef.current.<computed> [as publishEvent] (useGridApiMethod.js:14:1)
    at GridColumnHeaderItem.js:87:1
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
```

### Context 🔦

Simple keyboard navigation.

### Order ID 💳 (optional)

45466

**Comment by MBilalShafi** [comment]
Thanks @mbiggs-gresham for reporting, this indeed seems an issue, here's the sandbox link where I was able to reproduce it: https://codesandbox.io/s/test-mui-xgrid-crash-kqrlhd?file=/src/demo.js

The solution would be to add a safety check in `useGridKeyboardNavigation.ts` to handle no rows available scenario.

```tsx
  const getRowIdFromIndex = React.useCallback(
    (rowIndex: number) => {
      return currentPageRows[rowIndex]?.id;
    },
    [currentPageRows],
  );

```

**Comment by oliviertassinari** [comment]
@MBilalShafi We try to use `!.` as much as possible, as opposed to `?.`. We might have a better option in https://github.com/mui/mui-x/pull/6535#issuecomment-1280063571.

**Comment by jthom330** [comment]
We're experiencing the same issue as well.
