### ISSUE TITLE
[pickers] Calendar doesn't circle today's date

### ISSUE THREAD

**Issue by duliduliduduli** [mui/mui-x#6447]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. open calendar by click the icon
2. I see only the default select date which is today + 7 days in blue circle.
3. I don't see today's date with a white circle

### Current behavior 😯

I don't see today's date with a white circle
![Screenshot 2022-10-10 at 13 54 43](https://user-images.githubusercontent.com/60844935/194860887-31ad4b84-9637-46d3-9457-9fafc12110e2.png)

### Expected behavior 🤔

see both today's date (white circle) and the default selected date (blue circle)

![image (1)](https://user-images.githubusercontent.com/60844935/194860901-c69eb0fc-6216-4e19-b927-a88c74316870.png)

### Context 🔦

I wish I know what is today's date so I know which date to select.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: Not Found
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Not Found
    Firefox: 105.0.1
    Safari: 15.2
```
</details>

I'm using chrome

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.
