### ISSUE TITLE
 The plan of mui/x-data-grid-pro is free to use without any key

### ISSUE THREAD

**Issue by devops-sunny** [mui/mui-x#6450]
DO SOME CHANGES BEFORE BUILD:

```
 "@mui/material": "^5.8.7",
 "@mui/x-data-grid": "^5.13.0",
 "@mui/x-data-grid-pro": "^5.13.0"
```
1. GO TO THE BELOW PATH

```
node_modules/@mui/x-license-pro/verifyLicense/verifyLicense.js
```
```
import { base64Encode } from '../encoding/base64';
import { LicenseStatus } from '../utils/licenseStatus';


const getDefaultReleaseDate = () => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return today;
};

export function generateReleaseInfo(releaseDate = getDefaultReleaseDate()) {
  return base64Encode(releaseDate.getTime().toString());
}

export function verifyLicense() {
  return LicenseStatus.Valid;
}
```

3. save changes and make a build.

**Comment by joserodolfofreitas** [comment]
Thanks for your report, @devops-sunny. 

The license key is not meant as a security measurement, it's a way to help our customers stay compliant with our [End Users License Agreement](https://mui.com/legal/mui-x-eula/#license-key).  We trust that our community members are well-intentioned and that they also see this relationship as a long-term collaboration.

The mentioned vulnerability hardly allows scaling in any enterprise environment, and it's simply not worth the legal risk.

**Comment by oliviertassinari** [comment]
@devops-sunny I'm not sure to follow, what's the issue?
