### ISSUE TITLE
[data grid] How to set up grid footer columns like <tfoot> in DataGrid Pro?

### ISSUE THREAD

**Issue by aravindpanicker** [mui/mui-x#6454]
### Order ID 💳

40973

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is it possible to set up a footer row in the DataGrid Pro in the following format? I am trying to have the Data Grid to display the grand totals for some of the columns in the footer (Like `<tfoot>`)

| Month      | Income | Expense     |
| :---        |    ----:   |          ---: |
| Jan        | 10000   | 5000       |
| Feb       | 4000     | 2300       |
| Mar       | 14000     | 5300       |
| **Total**     | **28000**   | **12600**      |

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 105.0.5195.127 (Official Build) (64-bit)
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.37)
  npmPackages:
    @emotion/react: ^11.9.3 => 11.10.4
    @emotion/styled: ^11.9.3 => 11.10.4
    @mui/base:  5.0.0-alpha.99
    @mui/core-downloads-tracker:  5.10.7
    @mui/icons-material: ^5.8.4 => 5.10.6
    @mui/material: ^5.8.4 => 5.10.7
    @mui/private-theming:  5.10.6
    @mui/styled-engine:  5.10.7
    @mui/system:  5.10.7
    @mui/types:  7.2.0
    @mui/utils:  5.10.6
    @mui/x-data-grid:  5.17.5
    @mui/x-data-grid-pro: ^5.12.3 => 5.17.5
    @mui/x-date-pickers:  5.0.3
    @mui/x-date-pickers-pro: ^5.0.0-alpha.7 => 5.0.3
    @mui/x-license-pro:  5.17.0
    @types/react:  18.0.21
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.8.4
```
</details>

**Comment by yaredtsy** [comment]
@aravindpanicker if you want to compute the total on the table you can use Data grid - **Aggregation**. if you want to add the 'Total' label text check this example https://codesandbox.io/s/cool-greider-3q9i43?file=/demo.js.
If the total is already computed and already in the data you can use **Row pinning**.

**Comment by aravindpanicker** [comment]
> @aravindpanicker if you want to compute the total on the table you can use Data grid - **Aggregation**. if you want to add the 'Total' label text check this example https://codesandbox.io/s/cool-greider-3q9i43?file=/demo.js.
> 
> If the total is already computed and already in the data you can use **Row pinning**.

First of all, thanks for the quick response.

I have already managed to do this using row pinning which  seems like a hack rather than a proper solution. Unfortunately, we don't have a premium license to use the aggregation feature. I want to know if there's another way to define/configure footer columns like in a table footer.

If this functionality is not available, it would be nice to have it.

**Comment by cherniavskii** [comment]
Hey @aravindpanicker 
Row pinning seems like a proper solution for your use case.
Moreover, aggregation uses pinned row for the root-level aggregation footer.
