### ISSUE TITLE
[pickers] LocalizationProvider and Theme not changing

### ISSUE THREAD

**Issue by n1xn** [mui/mui-x#6455]
I want my users to be able to read the text displayed in mui components in their language. I am extracting the language from the url and setting it to the `sessionStore` with MobX. My problem is that the all MUI components are displaying in default english instead of the set language. The described [localization docs](https://mui.com/material-ui/guides/localization/) are not working.

**app.tsx**
```
import React from 'react';
import { Route, Routes } from 'react-router-dom';
import { createTheme, ThemeProvider } from '@mui/material';
import { observer } from 'mobx-react-lite';
import { useStore } from './lib/hooks/useStore';
import * as locales from '@mui/material/locale';

const muiTheme = {
	palette: {
		primary: {
			main: '#ccb076',
			dark: '#ccb076',
			contrastText: '#fff',
		},
	},
	components: {
		MuiOutlinedInput: {
			styleOverrides: {
				root: {
					borderRadius: '0px',
				},
			},
		},
	},
};

const App = observer(() => {
	const { language } = useStore('uiStore');

	const themeWithLocale = React.useMemo(
		// @ts-ignore
		() => createTheme(muiTheme, locales[language.muiImport]), // equals to locales['deDE']
		[language],
	);

	return (
		<React.Fragment>
			<ThemeProvider theme={themeWithLocale}>
				<Routes>
                                    ...
				</Routes>
			</ThemeProvider>
		</React.Fragment>
	);
});

export default App;

```

**MyComponent.tsx**
```
import { observer } from 'mobx-react-lite';
import { useStore } from '../lib/hooks/useStore';
import { TextField, TextFieldProps } from '@mui/material';
import { LocalizationProvider, MobileDatePicker } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

const FilterPanel = observer(() => {
        const uiStore = useStore('uiStore');
	const { language } = uiStore;

	return (
		<LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale={'de-DE'}> // tried all variations like de, de-DE, deDE...
			<MobileDatePicker
				//shouldDisableDate={disableUnavailableDates}
				disablePast
				inputFormat={language.dateFormat}
				label={'Test'}
				value={activeDate}
				onChange={(selDate: Date | null) => {
					uiStore.setActiveDay(selDate);
				}}
				renderInput={(params: JSX.IntrinsicAttributes & TextFieldProps) => (
					<TextField {...params} />
				)}
			/>
		</LocalizationProvider>
	);
});

export default FilterPanel;

```

**versions:**
```
    "@mui/material": "^5.6.4",
    "@mui/x-date-pickers": "^5.0.0-alpha.2",

```

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by n1xn** [comment]
Thanks for the fast answer. I created a reproduction like you mentioned. Bare in mind you have to append the language in the url, by either adding `/de` or `/en`. Unfortunately `MobileDatePicker` will not open anymore because of scrollToTop missing reference issue. This issue is not present in my codebase and just appears on codesandbox, which I guess have to do something with the current version as codesandbox has `latest` set for all mui dependencies added.

https://codesandbox.io/s/date-and-time-pickers-forked-2t9sk7?file=/src/App.tsx

**Comment by Dekshut** [comment]
![image](https://user-images.githubusercontent.com/77440017/196046381-0bef012c-9fb0-425b-98c7-7993437264ab.png)
@flaviendelangle I reproduced this issue. I will take it. Please assign it on me

**Comment by flaviendelangle** [comment]
@n1xn where are you passing your `localeText` to the pickers ?
I see that you are passing the locale for `@mui/material` through the theme and the date locale (to have your german date formats) to the `LocalizationProvider`.
But unless I am missing something, you are never passing any `localeText` to the pickers as described [in the doc](https://mui.com/x/react-date-pickers/localization/#translation-keys)
