### ISSUE TITLE
[pickers] Contrast-ratio issues for focused date in `DayCalendar`

### ISSUE THREAD

**Issue by caub** [mui/mui-x#6456]
With some theme main color, the calendar focused day can be hard to read

![2022-01-03-161143_306x138_scrot](https://user-images.githubusercontent.com/3134574/147947266-acbb4ca3-d58f-4ab7-a5d1-0b494f6a6e3c.png)

Demo: https://codesandbox.io/s/mui-datepicker-w6rk8 (note: initially the selected day is not hovered or focused, and contrast ratio is fine there, try to hover or focus it to get it like the screenshot above

Is there either a workaround, to make the focused background closer to the main, to avoid this issue, or maybe the text color needs to switch to white in those cases, but that might be overkill

**Comment by alexfauquette** [comment]
The easiest solution is maybe to add a `contrastText` in your palette such that the button text appears white when selected
```js
palette: {
    primary: { main: "#1CA6D1", contrastText: "#fff" }
},
``` 

https://codesandbox.io/s/mui-datepicker-forked-mmwqmn?file=/src/index.js:432-502

**Comment by flaviendelangle** [comment]
I'm adding `needs more information` in case @alexfauquette answer does not solve the problem.
Otherwise I fear that we keep this kind of old issue solved but opened for ages.

**Comment by caub** [comment]
@alexfauquette ok thanks, good enough, and as the theme color is dynamic we can do

```js
primary: { main: primaryColor, contrastText: getLuminance(primaryColor) < .5 ? "#fff" : "#000" }
```

thanks
