### ISSUE TITLE
[DesktopDatePicker] className props does not appear in root element 

### ISSUE THREAD

**Issue by jasonalexander-ja** [mui/mui-x#6457]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Giving a `className` prop to the `DesktopDatePicker` component does not pass the attribute to the root element of the component, see in code sandbox [here](https://codesandbox.io/s/vibrant-maxwell-ruyjj?file=/src/Demo.tsx).

## Expected Behavior 🤔

As listed in the component API documentation the ["className applied to the root component."](https://mui.com/api/desktop-date-picker/#main-content)
## Steps to Reproduce 🕹

Steps:

1. Using dependancies `@emotion/react` `@emotion/styled` `@mui/lab` `@mui/material` `date-fns`
2. At the root, import and wrap the app with the component `LocalizationProvider` from `@mui/lab/LocalizationProvider`, import `AdapterDateFns` from `@mui/lab/AdapterDateFns` and pass that into `LocalizationProvider` as a props `dateAdapter` 
3. Import `TextField` from `@mui/material/TextField` and `DesktopDatePicker` from `@mui/lab/DesktopDatePicker` and use that within the app as a component with no children (a self closed tag), pass 2 functions to the mandatory props named `onChange` and another to `renderInput`, the latter should take one argument and return an instance of `TextField`, destructuring the argument within the returned textField `renderInput={props => <TextField {...props} />}`.
4. Pass in a string to a prop on the `DesktopDatePicker` named `className`, then check the root of that component using the element selector in the web browser, the specified class name is not appended to the root elements class attribute. 

## Context 🔦

I was tring to apply some styles to the outer element of the `DesktopDatePicker` via a class. 

### Work around

Adding the className to the element returned in `renderInput` will create the desired functionlity (the class name is appended to the root element).

```tsx
<DesktopDatePicker
  ...
  renderInput={(props) => (
    <TextField
      {...props}
      className="HelloWorld"
    />
  )}
/>
```

### Investigation

I have delved into this, it seems that the prop `className` cascades down into the component [KeyboardDateInput](https://github.com/mui-org/material-ui/blob/master/packages/mui-lab/src/internal/pickers/KeyboardDateInput.tsx) on line [25](https://github.com/mui-org/material-ui/blob/master/packages/mui-lab/src/internal/pickers/KeyboardDateInput.tsx#L25) within the variable `other`, this is then passed to the function [useMaskedInput](https://github.com/mui-org/material-ui/blob/master/packages/mui-lab/src/internal/pickers/hooks/useMaskedInput.tsx) on line [28 of KeyboardDateInput](https://github.com/mui-org/material-ui/blob/master/packages/mui-lab/src/internal/pickers/KeyboardDateInput.tsx#L28) where it isn't returned from that function, one [quick hack](https://github.com/jasonalexander-ja/material-ui/blob/desktop-date-picker-classname/packages/mui-lab/src/internal/pickers/KeyboardDateInput.tsx#L32) where I just appended a className prop from `other` to the return variable of `useMaskedInput` before it is passed into the call to `renderInput` (I assume this is the same function passed down from `DesktopDatePicker`) does cause the passed class name to appear in the root elements prop.

I appreciate that this is just a quick poke around that I did and by no means a fix, I also appreciate that it is up to the maintainers to make the decision whether or not to expose className at all (in this case it would be preferable if the API documentation was updated) since passing the className to the returned `TextField` does provide a sufficient workaround however I am conscious that with this component being in the lab it's structure could change I.E. an extra element could be added by `DesktopDatePicker` to the element returned by `renderInput` and that would no longer be the root. 

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  System:

    OS: Linux 5.14 Fedora 34 (Workstation Edition) 34 (Workstation Edition)

  Binaries:

    Node: 14.18.1 - /usr/bin/node

    Yarn: Not Found

    npm: 6.14.15 - /usr/bin/npm

  Browsers:

    Chrome: 95.0.4638.69

    Firefox: 94.0
```  
</details>

**Comment by LukasTy** [comment]
Hello @jasonalexander-ja @sdzaveri 
Sorry for taking so long to reply to your issue—it got lost in `material-ui` repository, whereas `date-pickers` is currently maintained under `mui-x` repository.

We have quite recently released changes fixing known `className` application problems.
Could you double check if you are still experiencing issues using the latest release of `@mui/x-date-pickers` or `@mui/x-date-pickers-pro` and if so—reopen this issue. 😉
