### ISSUE TITLE
MUI datagrid-pro RTL - grid body is scrolling horizontally left without their column headers while in RTL mode

### ISSUE THREAD

**Issue by IsmatAyash** [mui/mui-x#6464]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Two days ago, and upon reading the article about RTL support, I bought the MUI "DatagridPro" license because currently I am developing a multi-lingual web application using NextJS includes Arabic language (RTL is required). I am facing a problem with the scrolling while in RTL mode. The body of the grid (rows) is scrolling incorrectly without the column headers, while in the LTR mode the grid is behaving correctly.

I kindly seek your support to solve this urgent issue as heavily I am using the data grid throughout the app.

I look forward to receiving your reply soon,
Thank you
Ismat Ayash

### Expected behavior 🤔

It should behave exactly like in LTR mode

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Context 🔦

Developing a web application and heavily using the data grid throughout the app to manage datatables CRUD operations

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

I am using the following:
1) NEXTJS with next-i18next as locales library
2) MUI version 5 the latest
3) Prisma ORM
4) Chrome browser and safari
```
</details>

### Order ID 💳 (optional)

52265

**Comment by yaredtsy** [comment]
@IsmatAyash I think there is already a discussion about this issue at https://github.com/mui/mui-x/issues/230. i have some workarounds I used for this issue. You can check it out if it helps: https://codesandbox.io/s/nice-frost-5vuf86?file=/demo.js.

**Comment by IsmatAyash** [comment]
Thank you dear yared the workaround has worked

**Comment by bendan7** [comment]
We’re in mid-2025 and I encountered the same issue.

If you happen to land here and face the same problem, a possible workaround is to try disabling the virtualization mechanism like so:

`<DataGridPro disableVirtualization={isRtl} ... />`

This resolved the issue in my case when isRtl is true.

Hope this helps someone!
