### ISSUE TITLE
[data grid] GridToolbarFilterButton doesn't have medium or large size like it's brother buttons

### ISSUE THREAD

**Issue by jordanlun1** [mui/mui-x#6468]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The GridToolbar has four buttons available out of the box. GridToolbarExport, GridToolbarDensitySelector, GridToolbarFilterButton,  GridToolbarColumnsButton. 

1. three of them have a working size prop (small medium large), and the GridToolbarFilterButton does not have a working size prop. So it doesn't resemble the other brothers unless all four buttons are set to small. 

### Expected behavior 🤔

GridToolbarFilterButton should have a size prop (small medium and large) that works just like the other three do.

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Make a simple DataGrid or DataGridPro with a custom toolbar
2. Put all four buttons in this toolbar
3. Give them all a size prop and set them to medium or large
4. Watch how the Filter one doesn't not resize

Sandbox:
https://codesandbox.io/s/gridtoolbarfilterbutton-size-issue-forked-pdxuul

![image](https://user-images.githubusercontent.com/48939720/195293921-1a347ce1-1287-41a8-804d-aa7178f6222f.png)

### Context 🔦

Would like the option of making all the toolbar buttons small medium or large. Consistent behaviour and choice.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Google Chrome
  @mui/envinfo@2.0.6
```
</details>

### Order ID 💳 (optional)

We have DataGridPro license but can't find order number

**Comment by MBilalShafi** [comment]
@jordanlun1 You can leverage componentProps exposed by `GridToolbarFilterButton`

```
<GridToolbarFilterButton
    componentsProps={{ button: { size: "large" } }}
/>
```

Here's a working version: https://codesandbox.io/s/gridtoolbarfilterbutton-size-issue-forked-8gnygl?file=/src/App.tsx:338-427

**Comment by jordanlun1** [comment]
Alright I can live with that.
