### ISSUE TITLE
[data grid] unnecessary column width resetting when changing unrelated state

### ISSUE THREAD

**Issue by jordanlun1** [mui/mui-x#6469]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Manually adjusted column widths are getting reset whenever unrelated state changes

### Expected behavior 🤔

I don't want column widths reset when changing a totally unrelated state

### Steps to reproduce 🕹

Link to live example:

Steps:
1. https://codesandbox.io/s/datagridpro-column-widths-resetting-unnecessarily-with-state-change-forked-2ix6pe
2. Adjust the width of either column with mouse
3. Press the Change Unrelated State button to change the state value.
4. The Typography will re-render to show that new state, but the DataGridPro will also resize the columns back to the starting width.

### Context 🔦

I want the manually adjusted column withs to stay put when I change a completed unrelated state that has no connection to the DataGridPro.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Google Chrome
  @mui/envinfo@2.0.6
```
</details>

### Order ID 💳 (optional)

8301052219-26999

**Comment by MBilalShafi** [comment]
@jordanlun1 You can use the columns outside the component to have the reference not change on every render, or you can possibly memoize them if dependent on some other variables.

Here's the updated code: https://codesandbox.io/s/datagridpro-column-widths-resetting-unnecessarily-with-state-change-forked-6gtk2j

**Comment by aaronucsd** [comment]
I had this issue where i resize the column with and when my data refetches to update the cells the resizing gets resets. Basically the whole datagrid resets. If the column has custom rendering cells and need to reference variables you can't have it outside the component. SO you need to memoize it or useMemo. Adding dependency in the useMemo array will trigger a re-rendering. 

```
const columns: GridColDef[] = useMemo(() => [  
  ... //dynamic renderCell
// eslint-disable-next-line react-hooks/exhaustive-deps
  ], []);
```

**Comment by igortas** [comment]
> I had this issue where i resize the column width and when my data refetches to update the cells the resizing gets resets. Basically the whole datagrid resets. If the column has custom rendering cells and need to reference variables you can't have it outside the component. SO you need to memoize it or useMemo. Adding dependency in the useMemo array will trigger a re-rendering.
> 
> ```
> const columns: GridColDef[] = useMemo(() => [  
>   ... //dynamic renderCell
> // eslint-disable-next-line react-hooks/exhaustive-deps
>   ], []);
> ```

And this is terrible, because sometimes u have dynamic columns, and even u ommit them from the dependecy array, u have problem if u update some server state that affectes them (removing, adding...)
