### ISSUE TITLE
[DataGrid] showInMenu property of GridActionsCellItem open menu in wrong position.

### ISSUE THREAD

**Issue by Nic-S** [mui/mui-x#6473]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Action menu is opened in the upper left corner instead of under the icon

### Expected behavior 🤔

Action menu is opened under the icon

### Steps to reproduce 🕹

Link to live example: [Link](https://codesandbox.io/s/action-menu-position-bug-5ddgkk?file=/demo.tsx)

Steps:
1. click on "more actions" icon

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by yaredtsy** [comment]
@Nic-S I think it's only on codesandbox only, there are also other features that are not working like a filter. use stackblitz 
![image](https://user-images.githubusercontent.com/34584266/195596152-4dad39ef-c5b7-41ff-9df7-b927adf124d1.png)

**Comment by alexfauquette** [comment]
I do not manage to reproduce your bug. In the link you provided, when clicking on show more action, the menu opens correctly.

![image](https://user-images.githubusercontent.com/45398769/196138939-fe2392a2-735e-4374-a572-247699b6ccbb.png)

**Comment by yaredtsy** [comment]
I think its fixed it was acting strange on codesandbox.
