### ISSUE TITLE
[pickers] AdapterDateFns mask for some locales broken: Mask does not support numbers with variable length such as 'M'.

### ISSUE THREAD

**Issue by rottabonus** [mui/mui-x#6479]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using a [date-fns locale](https://github.com/date-fns/date-fns/tree/main/src/locale) such as _fi_, _el_, _en-GB_, _fr_ .. just to name a few will not work well with the AdapterDateFns when set as the locale.

There will be a warning in the development console:

```
Mask does not support numbers with variable length such as 'M'.
Either use numbers with fix length or disable mask feature with 'disableMaskedInput' prop
Falling down to uncontrolled no-mask input. 
```

### Expected behavior 🤔

The mask should work with the locales from date-fns

## Codesandbox reproduction
[Here is a codesandbox reproduction](https://codesandbox.io/s/gracious-heisenberg-3xz6j4?file=/demo.tsx)

### Context 🔦

Trying to use an application with multiple locales@

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: Not Found
    npm: 6.14.17 - ~/NordSafety.Portal/NordSafety.Portal/quentic-app-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Not Found
    Firefox: 105.0.1
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base: 5.0.0-alpha.95 => 5.0.0-alpha.95
    @mui/core-downloads-tracker:  5.10.7
    @mui/icons-material: ^5.8.4 => 5.10.6
    @mui/lab: 5.0.0-alpha.97 => 5.0.0-alpha.97
    @mui/material: 5.10.3 => 5.10.3
    @mui/private-theming:  5.10.6
    @mui/styled-engine:  5.10.7
    @mui/system:  5.10.7
    @mui/types:  7.2.0
    @mui/utils:  5.10.6
    @mui/x-data-grid:  5.17.4
    @mui/x-data-grid-pro:  5.17.4
    @mui/x-date-pickers: ^5.0.0-beta.7 => 5.0.3
    @mui/x-date-pickers-pro: ^5.0.0-beta.7 => 5.0.3
    @mui/x-license-pro:  5.17.0
    @types/react: 18.0.21 => 18.0.21
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: ^5.3.6 => 5.3.6
    typescript: ^4.8.4 => 4.8.4

```
</details>

**Comment by flaviendelangle** [comment]
Unless I'm missing something, the warning message is expected, the mask approach can't be compatible with this kind of mask.
We are currently building new components to bypass this limitation (and other limitations).
They should be officially announced in a few days.

**Comment by rottabonus** [comment]
Ok, that is clear then. I did not see anywhere a mention about that some of the masks are not supported.
Nice that it is going to be supported soon.

**Comment by PCOffline** [comment]
> Unless I'm missing something, the warning message is expected, the mask approach can't be compatible with this kind of mask. We are currently building new components to bypass this limitation (and other limitations). They should be officially announced in a few days.

Hey, any updates on that?

**Comment by LukasTy** [comment]
> Hey, any updates on that?

It already had a "soft" announcement in the [v6 blog post](https://mui.com/blog/mui-x-v6-alpha-zero/#date-and-time-pickers). If you are eager to learn about the components or test them sooner—here is the [documentation and demos](https://next.mui.com/x/react-date-pickers/date-field/).
Do note that components are still in alpha phase and we are currently working on implementing them inside all of the picker components instead of usual `renderInput/TextField` as well as some improvements/tweaks following after that.

**Comment by flaviendelangle** [comment]
I am closing this issue.

We recently launched the first beta of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` v6.x.
This new version contains a full rework of the input editing.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/).

We won't apply complicated (and not always doable) fixes to the v5 version, I hope this new version solves your problem.

**Comment by rottabonus** [comment]
Thanks, Ill be sure to check v6 soon😎
