### ISSUE TITLE
[pickers] Support keyboard typing in Mobile Pickers

### ISSUE THREAD

**Issue by EhsanSaberian** [mui/mui-x#6481]
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Keyboard input for mobile date pickers.

Mobile (dialog) date, time and dateTime pickers can have a prop to allow keyboard input for them.

## Examples 🌈
Previous version of pickers allowed keyboard control in both dialog and inline date pickers:

https://codesandbox.io/embed/clever-architecture-qiqkp?fontsize=14&hidenavigation=1&theme=dark

## Motivation 🔦
We're using datePickers in a form in our project and based of our design principles, we need dialog version of pickers in desktop mode that user can interact with it with keyboard. In the previous version of "material-ui/pickers" this was supported in dialog mode, but in the current mui/lab version the feature has been removed and there's no way to enter the date via keyboard in the TextField, which is essential in desktop mode.

**Comment by flaviendelangle** [comment]
Closing because our new field component support mobile edition
The doc should be published in the coming days
