### ISSUE TITLE
Material UI Datepicker Validation

### ISSUE THREAD

**Issue by Hummel37** [mui/mui-x#6482]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The validation for dates fails on the datepickers

![image](https://user-images.githubusercontent.com/54278236/113318736-0efb2800-9311-11eb-9079-f74e02381efc.png)
![image](https://user-images.githubusercontent.com/54278236/113318858-2afec980-9311-11eb-97be-7db1fc44cf9b.png)
![image](https://user-images.githubusercontent.com/54278236/113319267-8cbf3380-9311-11eb-93b3-5741430839e3.png)

## Expected Behavior 🤔

Valid dates are accepted. Invalid dates are red.

## Steps to Reproduce 🕹

Tested local and on the page
https://next.material-ui.com/components/date-picker/

If you are changing the months on the mobile picker the validation is always accepted.
If you are just entering normal dates, sometimes it works... Sometimes not.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 15.5.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
  npmPackages:
    @emotion/react: ^11.1.5 => 11.1.5 
    @emotion/styled: ^11.1.5 => 11.1.5 
    @material-ui/core: ^5.0.0-alpha.28 => 5.0.0-alpha.28  
    @material-ui/icons: ^4.9.1 => 4.11.2 
    @material-ui/lab: ^5.0.0-alpha.28 => 5.0.0-alpha.28   
    @material-ui/pickers: ^3.2.10 => 3.3.10 
    @material-ui/styled-engine:  5.0.0-alpha.25 
    @material-ui/styles:  5.0.0-alpha.28 
    @material-ui/system:  5.0.0-alpha.28 
    @material-ui/types:  5.1.7
    @material-ui/unstyled:  5.0.0-alpha.28
    @material-ui/utils:  5.0.0-alpha.28
    @types/react: ^16.9.41 => 16.14.5
    react: 17.0.0 => 17.0.0
    react-dom: ^16.14.0 => 16.14.0
    typescript: ^3.9.6 => 3.9.9
```
</details>

**Comment by flaviendelangle** [comment]
For me the validation now correctly triggers on invalid month / day numbers
Please give an up to date reproduction case if you still have issue :+1:

**Comment by omerbrandis** [comment]
Hello I'm using 
@mui/x-date-pickers  "^6.0.1"

and it looks like I'm still encountering the same error as reported by prokkyb 3 years ago , 
In my case minDate only restricts values when using the popup, 
it does not prevent setting an invalid date directly with the keyboard.

I was wondering if there's been any progress with this?

thanks
:-)

**Comment by LukasTy** [comment]
> I was wondering if there's been any progress with this?

@omerbrandis Your described behavior [is working](https://v6.mui.com/x/react-date-pickers/validation/#minimum-and-maximum-date) as far as the latest v6 release (v6.20.2).
