### ISSUE TITLE
[Pickers] Add ability to pass props to the open picker button icon

### ISSUE THREAD

**Issue by BrianWhiting** [mui/mui-x#6483]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The only way to modify the look and feel of the open picker button icon is by adding custom styles through a class on any of the parent components of the icon. This is due to the lack of any props being passed down to the icon itself.

## Examples 🌈

[Code Example](https://codesandbox.io/s/fast-haze-dy8l0?file=/src/Demo.tsx)
[Source Code](https://github.com/mui-org/material-ui/blob/9a367d5da295d170d314e1dc201e71126360ea05/packages/mui-lab/src/internal/pickers/KeyboardDateInput.tsx#L48)

## Motivation 🔦

I am trying to make the open picker button smaller. I can make the `IconButton` component small using the `OpenPickerButtonProps`, but I cannot change the font size (or any other property) of the icon except through manually styling the icon by using a CSS selector to get at the `svg` component with a `MuiSvgIcon-root` class.

**Comment by flaviendelangle** [comment]
Duplicates #4466
