### ISSUE TITLE
[pickers] Label not shrunk before hydration

### ISSUE THREAD

**Issue by eps1lon** [mui/mui-x#6484]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

A controlled picker with an initial value has a label that is not shrunk before hydration. This creates a UI that looks broken before hydration completes

<img width="627" alt="Capture d’écran 2020-12-29 à 13 46 01" src="https://user-images.githubusercontent.com/3165635/103284699-3a9e0780-49dc-11eb-9de6-ed62512189de.png">

## Expected Behavior 🤔

Label is shrunk before hydration

## Steps to Reproduce 🕹

Steps:

1. disable javascript
2. visit https://next.material-ui.com/components/pickers/#react-components

Label overlaps value. Only after hydration does it shrink

## Context 🔦

Switched to v4 on material-ui.com in https://github.com/mui-org/material-ui/pull/22023

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v5.0.0-alpha.20  |
| React       | 16.13.1 |
| Browser     | Chrome 83 |
| TypeScript  | N/A |

**Comment by flaviendelangle** [comment]
Can still reproduce the problem on the pickers
Not on the new fields for some reason

**Comment by flaviendelangle** [comment]
Can't reproduce it anymore on the v6 pickers
Closing, if somebody can reproduce please let me know,
