### ISSUE TITLE
YearPicker does not trigger onChange with latest changed value

### ISSUE THREAD

**Issue by raymondsze** [mui/mui-x#6485]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The YearPicker trigger onChange with the original value in the latest version.

### Expected behavior 🤔

The YearPicker should trigger onChange with the latest changed value.

### Steps to reproduce 🕹

```tsx
// onChange is always triggered with old value....
<YearPicker
      date={date}
      onChange={(date) => setDate(date)}
      minDate={minDate}
      maxDate={maxDate}
      isDateDisabled={() => true}
/>
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Not Found
    Firefox: 82.0
    Safari: 14.1.2
  npmPackages:
    @mui/base: ^5.0.0-alpha.60 => 5.0.0-alpha.60 
    @mui/icons-material: ^5.2.0 => 5.2.0 
    @mui/lab: ^5.0.0-alpha.60 => 5.0.0-alpha.60 
    @mui/material: ^5.2.4 => 5.2.4 
    @mui/private-theming:  5.2.3 
    @mui/system:  5.2.4 
    @mui/types:  7.1.0 
    @types/react: ^17.0.37 => 17.0.37 
```
</details>

**Comment by flaviendelangle** [comment]
I think this bug has been fixed.

Note that the `date` prop is now called `value` for consistency

Here is [a reproduction case](https://codesandbox.io/s/date-and-time-pickers-forked-sz9f5y?file=/src/App.tsx)
