### ISSUE TITLE
[pickers] Month and Year picker are effected by typography customization

### ISSUE THREAD

**Issue by israelKusayev** [mui/mui-x#6486]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Year and month pickers are effected by subtitle1 customization in createTheme -> typography -> subtitle1

![image](https://user-images.githubusercontent.com/42112796/139585031-9e051e3f-d187-4783-9a8e-7e214e67136d.png)
 
Is there any way to override it? 

## Steps to Reproduce 🕹

check codesandbox 
https://codesandbox.io/s/materialuipickers-material-demo-forked-2tgqx?file=/index.tsx
## Context 🔦

As I see in the code here we just take subtitle1 and I don't find any way to override it

https://github.com/mui-org/material-ui/blob/4b28fa117550e4e5ac97e831bd3011ddffa88ecb/packages/mui-lab/src/YearPicker/PickersYear.tsx#L76

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates https://github.com/mui/mui-x/issues/5465, has been fixed
