### ISSUE TITLE
Date Picker: Custom input component (renderInput) doesn't work with month view

### ISSUE THREAD

**Issue by simondriesen** [mui/mui-x#6487]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Using a `input` element for my `renderInput` together with the 'month' view results in errors.

Errors:
`React does not recognize the 'renderInput' prop on a DOM element.`
`React does not recognize the 'inputFormat' prop on a DOM element.`

## Expected Behavior 🤔

No errors.

## Steps to Reproduce 🕹

Steps:

1. Use a `input` element as custom renderInput:
```
renderInput={({ inputRef, inputProps, InputProps }) => (
  <div className="date-period__start">
    <input ref={inputRef} {...inputProps} />
    {InputProps?.endAdornment}
  </div>
)}
```

2. Enable the month view by adding this: 
`views={['year', 'month', 'day']}`
3.  Run the code and you should get some error messages.

I did some minimal changes to `Custom input component` sandbox example from next material-ui docs to recreate this issue: https://codesandbox.io/s/custominput-material-demo-forked-8i50g

## Context 🔦

I want to use the 'month' view with a custom 'renderInput' without getting errors.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.13.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @material-ui/core: ^5.0.0-beta.0 => 5.0.0-beta.0
    @material-ui/icons:  4.11.2
    @material-ui/lab: ^5.0.0-alpha.39 => 5.0.0-alpha.39
    @material-ui/pickers:  3.3.10
    @material-ui/private-theming:  5.0.0-beta.0
    @material-ui/styled-engine:  5.0.0-beta.0
    @material-ui/styles:  4.11.4
    @material-ui/system:  5.0.0-beta.0
    @material-ui/types:  6.0.1
    @material-ui/unstyled:  5.0.0-alpha.39
    @material-ui/utils:  5.0.0-beta.0
    @types/react:  17.0.13
    react: ^16.13.0 => 16.14.0
    react-dom: ^16.13.0 => 16.14.0
```
</details>

**Comment by flaviendelangle** [comment]
Has probably been fixed
Here is an [update to date reproduction case](https://codesandbox.io/s/custominput-material-demo-forked-mnxu1s?file=/demo.js)
