### ISSUE TITLE
[DatePicker] Allow to customize the rendered month 

### ISSUE THREAD

**Issue by bentaylorhk** [mui/mui-x#6488]
Is there any possibility of an implementation of a renderMonth function? This would work very similarly to how the `renderDay` function works, although allowing custom rendering for different selected months. 

<img width="364" alt="Capture d’écran 2020-11-15 à 00 02 13" src="https://user-images.githubusercontent.com/3165635/99158695-dc3ff280-26d5-11eb-842b-bb2baa01f740.png">

https://next.material-ui.com/components/date-picker/#views-playground

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/lab | v5.0.0-alpha.16  |

**Comment by flaviendelangle** [comment]
Duplicates #4662
