### ISSUE TITLE
[pickers] Add a way to show 1st week of next month

### ISSUE THREAD

**Issue by ideoclickVanessa** [mui/mui-x#6494]
Today, the calendar view looks like this:

![image](https://user-images.githubusercontent.com/44000426/66237115-22d8b600-e6a9-11e9-9b17-47b8de5b5829.png)

Could an option be added (or does one already exist) so that it looks more like this?

![image](https://user-images.githubusercontent.com/44000426/66237189-561b4500-e6a9-11e9-84e3-dc8e2a736bd6.png)

Plainly, the ask is for a way to add the last week of the previous month and the first week of the next month to the existing calendar view.

**Comment by flaviendelangle** [comment]
Has been fixed by #6299
