### ISSUE TITLE
Uncaught TypeError: apiRef.current.setRowMode is not a function

### ISSUE THREAD

**Issue by dstawiarski** [mui/mui-x#6496]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version, in fact did npm update few days ago.

### Current behavior 😯

ApiRef is populated across the component and used in many cases before, above error reports only when using setRowMode. Parameters are provided based on documentation. 

Currently using Data Grid Pro

### Expected behavior 🤔

Being able to set row mode with said function "apiRef.current.setRowMode"

### Context 🔦

React 18

```
 const apiRef = useGridApiRef();

  const applyChanges = (currentId: any, cancel: boolean) => {
    console.log(currentId);
    console.log(apiRef.current.getRow(currentId as GridRowId));    
    if (cancel) {
      apiRef.current.stopRowEditMode({
        id: currentId,
        ignoreModifications: true,
      });
    } else {
      apiRef.current.stopRowEditMode({
        id: currentId,
        ignoreModifications: false,
      });
      apiRef.current.setRowMode(currentId, "view");
    }
  };

```

Data Grid component 

```
<DataGridPro
          disableSelectionOnClick
          apiRef={apiRef}
          rows={JSON.parse(dataset)}
          columns={columns}
          editMode="row"
          processRowUpdate={processRowUpdate}
          onProcessRowUpdateError={handleProcessRowUpdateError}
          pageSize={pageSize}
          onPageSizeChange={(newPageSize) => setPageSize(newPageSize)}
          pagination
          rowsPerPageOptions={[5, 10, 20]}
          components={{ Toolbar: ToolbarOutside, NoRowsOverlay: NoDataOverlay }}
          disableColumnFilter
          disableColumnSelector
          experimentalFeatures={{ newEditingApi: true }}
          paginationMode="client"
          disableDensitySelector
          componentsProps={{
            toolbar: {
              showQuickFilter: true,
              quickFilterProps: { debounceMs: 0 },
            },
          }}
        />
```

### Order ID 💳 (optional)

Can provide if needed, working in corporate infrastructure with no ad-hoc access to it.

**Comment by yaredtsy** [comment]
@dstawiarski you do not need to use ` apiRef.current.setRowMode(currentId, "view")`. `apiRef.current.stopRowEditMode` is enough it changes the mode also.

**Comment by dstawiarski** [comment]
@yaredtsy not in my case, when I am firing `stopRowEditMode` with `ignoreModifications: false` flag is does not change the "edit" state

**Comment by dstawiarski** [comment]
Closing the ticket for now, it might have been temporary compiling/cache issue as today I ran the project from scratch and it's working.

**Comment by yaredtsy** [comment]
@dstawiarski it has nothing to do with `ignoreModifications: false`. it's async you might not see the change when you log it but if you delay it you can see it https://codesandbox.io/s/awesome-joji-80orbq?file=/demo.js.
