### ISSUE TITLE
[data grid] Why is this header not visible? 

### ISSUE THREAD

**Issue by pjwise-korio** [mui/mui-x#6498]
### Order ID 💳

50140

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Currently utilizing the custom detail panel expansions with `field: GRID_DETAIL_PANEL_TOGGLE_FIELD` in my column definitions. 

My approach seems to work fine for absolutely every other column in this specific grid along with other grids within our platform.

trouble column(should be to the right of 'Next Visit window'): 
```
columns.push({
        field: GRID_DETAIL_PANEL_TOGGLE_FIELD, flex: 2, headerName: 'Take Action', sortable: true, align: 'right', headerAlign: 'center',
   ...
}
```
![image](https://user-images.githubusercontent.com/110843415/195726163-25f88b04-2c3d-43a1-acba-fe6a564f82e3.png)

### Your environment 🌎
<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 14.19.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /workspaces/portal-spa/node_modules/.bin/npm
  Browsers:
    Chrome
    Firefox
  npmPackages:
    @emotion/react: ^11.8.1 => 11.10.4 
    @emotion/styled: ^11.8.1 => 11.10.4 
    @mui/base:  5.0.0-alpha.99 
    @mui/core-downloads-tracker:  5.10.7 
    @mui/icons-material: ^5.4.4 => 5.10.6 
    @mui/lab: ^5.0.0-alpha.92 => 5.0.0-alpha.101 
    @mui/material: ^5.10.3 => 5.10.7 
    @mui/private-theming:  5.10.6 
    @mui/styled-engine:  5.10.7 
    @mui/styles: ^5.10.7 => 5.10.7 
    @mui/system:  5.10.7 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.6 
    @mui/x-data-grid:  5.17.7 
    @mui/x-data-grid-pro: ^5.16.0 => 5.17.7 
    @mui/x-date-pickers: ^5.0.0-alpha.4 => 5.0.3 
    @mui/x-date-pickers-pro: ^5.0.0-beta.7 => 5.0.3 
    @mui/x-license-pro: ^5.16.0 => 5.17.0 
    @types/react: ^17.0.39 => 17.0.50 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.6.2 => 4.8.4 
```
</details>

**Comment by yaredtsy** [comment]
@pjwise-korio use `    apiRef.current.updateColumn({
        field: GRID_DETAIL_PANEL_TOGGLE_FIELD, flex: 2, headerName: 'Take Action', sortable: true, align: 'right', headerAlign: 'center',
   ...
})`.

**Comment by cherniavskii** [comment]
Hey @pjwise-korio 
Please refer to https://mui.com/x/react-data-grid/master-detail/#customizing-the-detail-panel-toggle for detail panel toggle customizations.
In case you experience a bug - please provide a minimal example reproducing the issue.
Thanks!
