### ISSUE TITLE
[docs] Broken links on field pages

### ISSUE THREAD

**Issue by Semigradsky** [mui/mui-x#6500]
From page https://next.mui.com/x/react-date-pickers/date-time-field/ I can't open links "[localization documentation page](https://next.mui.com/react-date-pickers/localization/)" and "[validation documentation page](https://next.mui.com/react-date-pickers/validation/)".

Looks like `href`s should be changed from `/react-date-pickers/*/` to `/x/react-date-pickers/*/`

**Comment by flaviendelangle** [comment]
:see_no_evil: 

I'll do a quick fix
You can access the page through the navbar

**Comment by flaviendelangle** [comment]
The fixed doc is online, thanks for the report !
