### ISSUE TITLE
[pickers][fields] Selected date section on click

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#6507]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When clicking on the input outside of the date sections, the last section gets selected.

### Expected behavior 🤔

Specific date section should be selected only on direct click on the section, otherwise first section should be selected.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/sleepy-elbakyan-1r7zzu?file=/demo.tsx:363-372

Steps:
1. Go to https://codesandbox.io/s/sleepy-elbakyan-1r7zzu?file=/demo.tsx:363-372
2. Click on the field in a place where there's no value under the cursor
(also see screen recording below)

### Context 🔦

I've noticed, that when click is close to the upper edge of the field, it behaves as expected and first section is selected.
The difference seems to be clicking on the `<input/>` element vs clicking on other elements of the field.

https://user-images.githubusercontent.com/13808724/195852071-2f29867b-85a5-4ebd-992f-2aab71a75c49.mov

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Turns out current behavior is consistent with regular [`TextField`](https://mui.com/material-ui/react-text-field/).
I still find this behavior undesirable for date/time fields specifically, because unlike in regular text fields, you cannot type more text at the end of the input value.

**Comment by flaviendelangle** [comment]
We will probably be limited by the information available to us
We use the selection cursor of the input, and I don't think we will be able to do much better
But we can investigate of course

**Comment by flaviendelangle** [comment]
We got a new issue about this very behavior, we had a fix on the way :+1: 

Closing this one
Duplicates #9005
