### ISSUE TITLE
[data grid] [question] 

### ISSUE THREAD

**Issue by rgavrilov** [mui/mui-x#6509]
### Order ID 💳

52426

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is there a way to provide custom column types?

I see `columnTypes` is one of the properties accepted by useDataGridProComponent but it doesn't look like it is intended to be used by meer mortals. Is it?	

This is clarification on this issue: https://github.com/mui/mui-x/issues/242

I see that it is intentionally undocumented, but I would like to use it.

### Your environment 🌎

The question is about API, not sure env is relevant

<details>
  <summary>`npx @mui/envinfo`</summary>
```

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 35.44 GB / 63.74 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.36.1.
  Virtualization:
    Docker: 20.10.17 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.72.1 - C:\Users\Roman Gavrilov\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.3.32922.545 (Visual Studio Community 2022)
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
```
</details>

**Comment by cherniavskii** [comment]
Hey @rgavrilov 
For custom columns please refer to https://mui.com/x/react-data-grid/column-definition/#custom-column-types
`columnTypes` indeed might be removed in the next major version.
