### ISSUE TITLE
[data grid] GroupBy issues with complex data using renderCell

### ISSUE THREAD

**Issue by cannontechnology** [mui/mui-x#6512]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The definition below throws an error in the valueGetter which is needed for filtering and sorting.  I'm also wondering why grouping does not work by default using the valueGetter.  Why is it necessary to add a groupingValueGetter?

{
      field: "type",
      headerName: "Type",
      width: 170,
      minWidth: 170,
      groupingValueGetter: (params) => DataClassUtils.dataClassTypes.find(o => o.value === params.row.type).name,
      valueGetter: (params) => DataClassUtils.dataClassTypes.find(o => o.value === params.row.type).name,
      renderCell: (params) => {
        return (
          <customComponent value={DataClassUtils.dataClassTypes.find(o => o.value === params.row.type).name}/>
)
}
    },

### Expected behavior 🤔

GroupBy should work without errors

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

10004760

**Comment by cherniavskii** [comment]
@flaviendelangle Could you take a look? Thanks

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.
