### ISSUE TITLE
[data grid] Rows ordering reverted after finishing cell editing

### ISSUE THREAD

**Issue by thuatole** [mui/mui-x#6520]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Rows ordering reverted after enabling cell edit mode

### Expected behavior 🤔

Keep the order after finishing cell editing

### Steps to reproduce 🕹

Link to live example: [https://www.loom.com/share/12c438f1a1b34568a178c3d00a836d23](https://www.loom.com/share/12c438f1a1b34568a178c3d00a836d23)

Steps:
1. Change the order of rows number 1 and 2
2. Edit column name of row number 2
3. Click outside to finish editing
4. See the order has been reverted

### Your environment 🌎

[https://codesandbox.io/s/pensive-mcnulty-efdyxo?file=/demo.tsx](https://codesandbox.io/s/pensive-mcnulty-efdyxo?file=/demo.tsx)

### Order ID 💳 (optional)

46630

**Comment by yaredtsy** [comment]
@thuatole I think it's fixed on 'v6' or 'next', this is the doc https://next.mui.com/x/react-data-grid/editing/, and this is the demo link https://codesandbox.io/s/optimistic-williams-qtm6ye

**Comment by thuatole** [comment]
thanks @yaredtsy

**Comment by yaredtsy** [comment]
@alexfauquette this is not fixed on master. `setRowIndex` is not updating caches.rows , every time `updateRows` is called it is reverting row orders.

**Comment by alexfauquette** [comment]
@yaredtsy Thanks for your investigation, but I'm not working on this part of the data grid

**Comment by cherniavskii** [comment]
Closed by https://github.com/mui/mui-x/pull/6544?
For some reason, the issue wasn't closed automatically 🤷‍♂️
