### ISSUE TITLE
[data grid] Dynamic row height does not shrink back to smaller height when content height is reduced.

### ISSUE THREAD

**Issue by alextaymx** [mui/mui-x#6536]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Dynamic row height does not shrink back to smaller height when content height is reduced.

When the row content is resized to a bigger height, the row actually expand, but it does not go back to original size when the content is shrinked to a smaller size.

**Comment by alextaymx** [comment]
Is it true that i need to manually call dataGridRef to force resize all row heights?

**Comment by yaredtsy** [comment]
@alextaymx it seems to work on my side, check this demo https://codesandbox.io/s/proud-tdd-zrry22?file=/demo.tsx. bio column is editable you can remove add text and check

**Comment by cherniavskii** [comment]
I cannot reproduce the issue either - after column resizing and editing the row height adjusted properly https://codesandbox.io/s/kind-ride-ftwwfv?file=/demo.tsx
