### ISSUE TITLE
[pickers] When using DatePicker and LuxonAdapter, changing prop adapterLocale does not influence the keyboard mask. 

### ISSUE THREAD

**Issue by slowWriting** [mui/mui-x#6540]
## Duplicates
- [x] I have searched the existing issues

## Latest version
- [x]  I have tested the latest version (alpha-3)

## Current behavior 😯
When DatePicker is used together with LuxonThere there is a problem with using adapterLocale to influence the placeholder. It does not work. Additionally warning is shown:
`Mask does not support numbers with variable length such as 'M'.
Either use numbers with fix length or disable mask feature with 'disableMaskedInput' prop
Falling down to uncontrolled no-mask input. `

Context - https://github.com/mui/mui-x/issues/4755#issuecomment-1280636612

## Expected behavior 🤔
Placeholder text should react to changing locale. Additionally no warnings in console would be nice.

## Steps to reproduce 🕹
https://codesandbox.io/s/date-and-time-pickers-forked-fdfsxx?file=/src/App.tsx

Sorry for formatting, I created an issue from existing comment and there was template, my bad.

**Comment by alexfauquette** [comment]
Not necessary to open an issue. It works because the french format is `dd/mm/yyyy` which is supported by mask For deutsh the default is `d.mm.yyyy`

For example, the 1st of October will be:
- fr: `01/10/2022`
- de: `1.10.2022`

The mask does not support this day format. If you used `format="dd.mm.yyyy"` the mask will be available

**Comment by slowWriting** [comment]
Indeed I have tested this on Edge using Hungarian locale - "hy" and as you say the masking works.
Strangely enough I have used Chrome first, but the browser is using wrong date formats, when using Intl.DateTimeFormat.
