### ISSUE TITLE
[data grid] Allow to apply quick filter on visible columns only

### ISSUE THREAD

**Issue by PrimulaX** [mui/mui-x#6559]
### Order ID 💳

47966

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I want to search with a quick filter only in visible rows, right now it searches in every column even if it's hidden.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
That sounds like an interesting parameter to add.

For now, you can do it but it will require some work with the [custome logic](https://mui.com/x/react-data-grid/filtering/#custom-filtering-logic). The `getApplyQuickFilterFn` accept 3 parameters: `value, column, apiRef`. Thanke to `apiRef` and `column` you can know if the column is hidden or not.

[here is an example](https://codesandbox.io/s/festive-brown-so7rrx?file=/demo.tsx)


Notice that the quick filter is independent of the visibility model. So showing/hidding column will not trigger the quick filter

**Comment by PrimulaX** [comment]
Hi @alexfauquette, thanks for your answer, I did manage to achieve it the way you describe it.
It would be really good if there was one parameter, can I make a feature request for that?

**Comment by alexfauquette** [comment]
🧙‍♂️ Your question magically became a feature request

I let the status need triage to be sure someone working on the data grid read the request

**Comment by PrimulaX** [comment]
@alexfauquette Thanks.

**Comment by alexfauquette** [comment]
By the way, depending on the chosen API, it can simple to do

In the [`buildAggregatedQuickFilterApplier`](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts#L223:L236) you have the array of fields on which quick filters will be applied:
```js
  const columnsFields = gridColumnFieldsSelector(apiRef);
```

Using `gridVisibleColumnFieldsSelector` instead would limit the applies to the visible columns.

If the parameter is into the `filterModel`, easy because the `buildAggregatedQuickFilterApplier` receives it in its parameters. Otherwise, there is some pipeline to build.

**Comment by cherniavskii** [comment]
We should consider changing the default behavior to look only through those columns that are visible.
This would be a breaking change.

**Comment by cherniavskii** [comment]
> Adding an option to filterModel is indeed the most straightforward solution, but it has a downside - you will be forced to use filterModel if you want to use this option, even if you don't really need controlled filtering.
We might want to explore other ways to customize it.

On second thought, this is what we already do with `quickFilterLogicOperator`, and controlled filter model is not required since it's possible to pass it through `initialState`:

```tsx
initialState={{
  filter: {
    filterModel: {
      items: [],
      quickFilterLogicOperator: GridLogicOperator.Or,
    },
  },
}}
```
