### ISSUE TITLE
DataGrid custom filter cannot set value

### ISSUE THREAD

**Issue by Dregorio1** [mui/mui-x#6565]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have code:
```
function MyFilterPanel() {
  const apiRef = useGridApiContext();
 
  const handleDateChange = () => {
    const { state, setState, forceUpdate } = apiRef.current;
    setState({
        filterModel: {
          items: [{ columnField: 'quantity', operatorValue: '>', value: 10000 }],
        },
    });
  };
  return (
    <DateRangePicker
      onChange={handleDateChange}
    />
  );
}
 // and
<DataGrid
	...
        filterMode="server"
        onFilterModelChange={(newValue) => {
            console.log(newValue);
        }}
        components={{
            FilterPanel: MyFilterPanel,
        }}
/>
```
I have got error:
```TypeError: Cannot read properties of undefined (reading 'columnVisibilityModel')```

### Expected behavior 🤔

Here:
```          
onFilterModelChange={(newValue) => {
            console.log(newValue);
}}
```
print for me `{... value = 10000}`;

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>  
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Binaries:
    Node: 16.16.0 - /opt/node-v16.16.0-linux-x64/bin/node
    Yarn: 3.2.1 - /opt/node-v16.16.0-linux-x64/bin/yarn
    npm: 8.11.0 - /opt/node-v16.16.0-linux-x64/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 106.0
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base:  5.0.0-alpha.86 
    @mui/icons-material: ^5.8.2 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.84 => 5.0.0-alpha.87 
    @mui/material: ^5.8.2 => 5.8.5 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/styles: ^5.8.0 => 5.8.4 
    @mui/system: ^5.8.2 => 5.8.5 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.4 
    @mui/x-data-grid: ^5.17.2 => 5.17.2 
    @mui/x-date-pickers: ^5.0.0-alpha.5 => 5.0.0-alpha.6 
    @types/react:  18.0.14 
    react: ^17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: ^4.7.3 => 4.7.
</code></summary>
</details>

**Comment by cherniavskii** [comment]
Hey @Dregorio1 
What are you trying to achieve?
Are you looking for [controlled filtering](https://mui.com/x/react-data-grid/filtering/#controlled-filters)?

Note, that `apiRef.current.state` contains the state of the whole grid, not only filtering.
You're effectively erasing state of the grid, hence the error.

**Comment by Dregorio1** [comment]
@cherniavskii Hello. I want to create my own custom filter as DataRangePicker. I want to pick range of data and base on it fetch data from api. But right now I do not know how to get proper value in `onFilterModelChange`.

**Comment by cherniavskii** [comment]
Then controlled filters is what you're looking for: https://mui.com/x/react-data-grid/filtering/#controlled-filters

**Comment by cherniavskii** [comment]
You can pass props to `MyFilterPanel` using `componentsProps`:

```tsx
componentsProps={{
  filterPanel: {
    setFilterModel: setFilterModel
  }
}}
```

**Comment by Dregorio1** [comment]
@cherniavskii But I want to get data from my component which is DateRangePicker and pass it to `onFilterModelChange` because here

**Comment by cherniavskii** [comment]
@Dregorio1 
Please take a look at our docs covering custom filter operators: https://mui.com/x/react-data-grid/filtering/#create-a-custom-operator
