### ISSUE TITLE
[data grid] Cannot Scroll to Right-Pinned Column in mobile view

### ISSUE THREAD

**Issue by alextaymx** [mui/mui-x#6581]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Let say i have 5 columns in datagrid, in mobile view, it just couldn't scroll to the right most pinned column , I'm not sure why it happens, is this a bug? horizontal scroll works for a certain width only? 

### Expected behavior 🤔

Let user scroll horizontally across all columns?  

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @alextaymx 

I assume the grid width is smaller than the total width of pinned columns. 
If that's the case, indeed you cannot scroll pinned columns, as [noted in our docs](https://mui.com/x/react-data-grid/column-pinning):
> You may encounter issues if the sum of the widths of the pinned columns is larger than the width of the grid. Make sure that the grid can accommodate properly, at least, these columns.

How would you expect for scroll to work, given that you have columns that should always be pinned to the right?

**Comment by alextaymx** [comment]
let me reproduce this again , will revert in awhile

**Comment by alextaymx** [comment]
https://user-images.githubusercontent.com/58934562/197688512-0d345e83-2871-4add-9686-8e1168c49ab2.mp4

@cherniavskii  The screen record above shows the issue , the pinned column is not too big actually , i tried to disable the pin feature, and still cannot scroll to the right.

**Comment by cherniavskii** [comment]
@alextaymx Are you sure the grid container is not wider than the viewport on mobile?

I cannot reproduce the issue with demos on https://mui.com/x/react-data-grid/column-pinning/
Can you provide a minimal example reproducing the issue?
