### ISSUE TITLE
[DataGrid] On Firefox, when a row is selected (via the checkbox) copying a cell (Cmd+C) selects and copies the whole row

### ISSUE THREAD

**Issue by AdamMurray** [mui/mui-x#6588]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On Firefox, when I select any row(s) using the checkbox, and I double-click on an editable cell any other row, and then I copy using Cmd+C, and then I paste the copied contents, they contain a combination of the data from the selected rows and, depending on the selected, also the highlighted content.

### Expected behavior 🤔

On Firefox, when I select any row(s) using the checkbox, and I double-click on an editable cell any other row, and then I copy using Cmd+C, and then I paste the copied contents, I should see only the highlighted/selected content from the editable row in the pasted output.

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-data-grid/#mit-version

Steps:
1. Open Firefox (tested on version 105.0) on macOS v12.5.1
2. Load https://mui.com/x/react-data-grid/#mit-version
3. Select the checkboxes to the left of rows 1 and 2
4. Double click on row 3 ("Jamie") until it becomes editable
5. Double-click on the text, "Jamie", and press Cmd+C
6. Open a new tab and paste it into the address bar
7. Confirm that the pasted content is "1	Jon	Snow	35	Jon Snow 2	Cersei	Lannister	42	Cersei Lannister"

### Context 🔦

I'm trying to ensure that copy pasting behaviour in the data grid works as expected for end users.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used: Tested on Firefox

  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Not Found
    Firefox: 105.0
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.7.1 => 11.10.4 
    @emotion/styled: ^11.6.0 => 11.10.4 
    @mui/icons-material: ^5.10.9 => 5.10.9 
    @mui/lab: 5.0.0-alpha.104 => 5.0.0-alpha.104 
    @mui/material: ^5.10.10 => 5.10.10 
    @mui/system: ^5.10.10 => 5.10.10 
    @mui/x-data-grid: ^5.17.8 => 5.17.8 
    @types/react: ^17.0.0 => 17.0.50 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ~4.5.5 => 4.5.5 
```
</details>

**Comment by cherniavskii** [comment]
Thanks @AdamMurray 
I can confirm the issue is reproducible in Firefox:

https://user-images.githubusercontent.com/13808724/197229100-03c7cf93-b6ab-45fa-8df0-1430d10e3374.mov

Works as expected in other browsers (tested in Chrome and Safari)
