### ISSUE TITLE
[data grid pro] columnVisibilityModel not exported using `apiRef.current.exportState()` if not set in initial state

### ISSUE THREAD

**Issue by dc-sts** [mui/mui-x#6589]
### Duplicates

- [X] I have searched the existing issues
- [4738](https://github.com/mui/mui-x/issues/4738)
- [4620](https://github.com/mui/mui-x/issues/4620)
- [PR 5390](https://github.com/mui/mui-x/pull/5390)

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When calling `apiRef.current.exportState()` in my `onColumnVisibilityModelChange` handler, the columnVisibilityModel is missing, unless it was initialised using `initialState` 

### Expected behavior 🤔

Unless I'm using the `exportOnlyDirtyModels` param, I expect a "full" state model to be exported, even if they weren't initialised with `initialState`

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-grid-pro-colvismissing-smus71?file=/demo.tsx:787-907

Steps:
1. Call `apiRef.current.exportState()` in `onColumnVisibilityModelChange` without initialising the `columnVisibilityModel` in `initialState`
2. Observe missing state model

Workaround:
Initialise state with empty `columnVisibilityModel`

### Context 🔦

I'm only using the `exportState` method as grid selectors are not available for all state models (ColumnOrderChange and ColumnResize if I recall correctly). I'd much prefer to control and extract only what I need. Adding the missing gridselectors would be a preferred solution.

### Your environment 🌎

Using Chrome: Version 106.0.5249.119 (Official Build) (64-bit)
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: Not Found
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.7.1 => 11.9.3 
    @emotion/styled: ^11.6.0 => 11.9.3 
    @mui/base:  5.0.0-alpha.89 
    @mui/icons-material: ^5.2.5 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.75 => 5.0.0-alpha.90 
    @mui/material: ^5.2.6 => 5.9.0 
    @mui/private-theming:  5.9.0 
    @mui/styled-engine:  5.8.7 
    @mui/system:  5.9.0 
    @mui/types:  7.1.4 
    @mui/utils:  5.10.3 
    @mui/x-data-grid:  5.13.0 
    @mui/x-data-grid-generator: ^5.10.0 => 5.13.0 
    @mui/x-data-grid-pro: ^5.17.8 => 5.17.8 
    @mui/x-date-pickers:  5.0.4 
    @mui/x-date-pickers-pro: ^5.0.4 => 5.0.4 
    @mui/x-license-pro:  5.12.3 
    @types/react: ^17.0.39 => 17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.5.5 => 4.7.4 
```
</details>

### Order ID 💳 (optional)

43201

**Comment by cherniavskii** [comment]
Hey @dc-sts 
Thanks for reporting this!

This behaviour is already fixed in v6 alpha: https://codesandbox.io/s/mui-grid-pro-colvismissing-forked-2t0fni?file=/demo.tsx
But it has to stay in v5 because of legacy `hide` column option https://mui.com/x/react-data-grid/column-visibility/#column-hide-property-deprecated
I would recommend to use workaround with `columnVisibilityModel` for v5
