### ISSUE TITLE
[DateRangePicker] Limiting maximum date span

### ISSUE THREAD

**Issue by githorse** [mui/mui-x#6597]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I can set minimum and maximum dates globally, but what if I want to limit the total number of days in the span selected by the user? I.e., if the user selects a start date, how can I disable any dates more than N (e.g., 30) days in the future?

### Motivation 🔦

I have lots of use cases where I want my users to be able to scroll back through months or years of possible dates, but I need to throttle the maximum amount of data requested by the API. The obvious way to do this would be to limit the user to downloading only a maximum number of days at a time (e.g. 90). It's not obvious how to enforce / communicate this limit without something like this feature.

### Order ID 💳 (optional)

46840

**Comment by LukasTy** [comment]
Hello @githorse 
Thank you for opening this issue.
What do you think, would using `shouldDisableDate` [in this way](https://codesandbox.io/s/zealous-dew-xlsld0?file=/demo.tsx) solve your case? 🤔

**Comment by flaviendelangle** [comment]
You could also implement if with `minDate` and `maxDate`
This will be more flexible when the range pickers will have a month / year selection UI.

**Comment by yaredtsy** [comment]
I think `minDate` and `maxDate` do the job well.
```javascript
maxDate={value[0] ? value[0].add(30, "day") : value[1] ? value[1] : null}
minDate={value[1] ? value[1].subtract(30, "day") : value[0] ? value[0] : null}
```
Demo: https://codesandbox.io/s/youthful-hertz-thsryj?file=/demo.tsx

**Comment by githorse** [comment]
Thank you @yaredtsy @LukasTy et al. The `minDate` / `maxDate` solution is promising, but once I pick a date range, it's difficult and unintuitive to then change it to a date outside the range. (For instance, I might want to click the arrows and select a completely different month.) The only way I can see to do it is to click inside one or both input fields and manually delete the values there to unset them. So unfortunately I don't think this will create an acceptable user experience, at least for my application.

I definitely don't really know the right way to solve this problem and communicate clearly to the user what's going on. In light of the above problem, I'm thinking I'll try allowing the user to select whatever they want, but outlining the inputs in red and displaying an error help text (and refusing to fire `onChange`) while the range exceeds the maximum. I'll play with that but anyone is more than welcome to try first if they want to take a stab at it. (I don't offhand know how to turn on the built-in `error` mode (red outline) for the input fields, among other problems.)

**Comment by LukasTy** [comment]
@githorse [Here is a codesanbox](https://codesandbox.io/s/headless-lake-tdexeb) with a rough implementation of your idea.
As you have mentioned—such a prop/requirement would not be trivial to implement as everyone might have different requirements on this matter.

If you still see that the current API is stopping you from achieving the desired effect—you are open to propose any improvement, which would aid your case. 😉

**Comment by Primajin** [comment]
Hey folks, we would also be very much interested in showing a warning when the minimum duration is not selected (before the user clicks)

Something like in AirBnB
![Screenshot 2022-11-02 at 11 11 39](https://user-images.githubusercontent.com/1742115/199463182-5fc8d743-73dc-4190-b344-706011a81477.png)

So we have min and max date - PLUS on top min and max duration that gives a little popup if the user wants to select outside of the allowed range.

Order ID 💳
48838 / 25229

**Comment by LukasTy** [comment]
@Primajin I feel that such custom behaviours are easier to achieve using custom components rather than a prop based implementation in the library.
What do you think about [this example](https://codesandbox.io/s/stoic-chaum-5fmd97?file=/demo.tsx) as a starting point for your use case?

**Comment by Primajin** [comment]
@LukasTy OK this is pretty cool! 🎉

**Comment by flaviendelangle** [comment]
I'm closing this one, looks like the answers provided are solving the initial pain
