### ISSUE TITLE
Rendering DataGrid under React testing library does not render more than 3 columns

### ISSUE THREAD

**Issue by sap-dshapovalov** [mui/mui-x#6601]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

This is bizarre one. I have DataGrid with 4 columns, and it works fine in runtime. But if I run test, it renders only first three columns under test renderer. Please, run _npm test_ this repo, last test in _Issue.test.tsx_.

https://github.com/sap-dshapovalov/datagrid-test-issue

### Expected behavior 🤔

Should render all defined columns when tests are ran

**Comment by 99yazel** [comment]
me,too

**Comment by charles-stuart-appdetex** [comment]
I think you need to set the `disableVirtualization` to `true` while testing.

See https://mui.com/x/react-data-grid/virtualization/#disable-virtualization.
