### ISSUE TITLE
How to fix DataGrid pinned column positioning?

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#6602]
### Order ID 💳

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have a couple of pages with form data. User needs to input some info and then select some options from a table. There is a fixed position bar on the bottom of the page with buttons, so they are always visible, even on long forms. All works great as long as there are no pinned columns in the table. If a column is pinned, that pinned column is positioned over bottom/button bar on the page. How do we change this behavior?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.6
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-data-grid: ^5.13.1 => 5.14.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0
    @mui/x-data-grid-pro:  5.14.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.2
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.14
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript:  4.7.4
```
</details>

**Comment by conerye** [comment]
![columnNotPinned](https://user-images.githubusercontent.com/39837891/197363358-af5c0a58-7473-4513-8ba2-672a0caeca84.png)

**Comment by conerye** [comment]
![columnPinned](https://user-images.githubusercontent.com/39837891/197363373-4be34da7-d841-4146-9da2-78d7c1c53db4.png)

**Comment by conerye** [comment]
first image shows scrolling through the form, the table is under the button bar; second image shows how it looks when there is a pinned column, it is positioned above the button bar.

**Comment by yaredtsy** [comment]
Hi @conerye i think increasing z-index of bottom bar will fix it

**Comment by conerye** [comment]
yes, increasing the z-index fixed this. thank you.
