### ISSUE TITLE
[pickers] Trying to run the x-date-pickers example within a Next.js 12.3.1 app leads to TypeError

### ISSUE THREAD

**Issue by grssnbchr** [mui/mui-x#6614]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Having a file `pages/test.js`:

```
import * as React from 'react';

import TextField from '@mui/material/TextField';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';

export default function BasicDatePicker() {
  const [value, setValue] = React.useState(null);

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DatePicker
        label="Basic example"
        value={value}
        onChange={(newValue) => {
          setValue(newValue);
        }}
        renderInput={(params) => <TextField {...params} />}
      />
    </LocalizationProvider>
  );
}
```

results in the following error message on localhost:3000/test

```
Server Error
TypeError: Cannot read properties of undefined (reading 'create')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
REDACTED/node_modules/@mui/material/InputLabel/InputLabel.js (96:33)
```

### Expected behavior 🤔

I would like to see the date picker, just as in the stack blitz example: https://stackblitz.com/edit/react-xn3pk6

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Copying [this example code](https://stackblitz.com/edit/react-xn3pk6) to my Next.js project
2. Trying to run it
3.
4.

### Context 🔦

Just want to run the BasicDatePicker example

### Your environment 🌎

System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.101 
    @mui/core-downloads-tracker:  5.10.10 
    @mui/icons-material: ^5.10.9 => 5.10.9 
    @mui/joy: ^5.0.0-alpha.49 => 5.0.0-alpha.49 
    @mui/material: ^5.10.10 => 5.10.10 
    @mui/private-theming:  5.10.9 
    @mui/styled-engine:  5.10.8 
    @mui/system:  5.10.10 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.9 
    @mui/x-date-pickers: ^5.0.5 => 5.0.5 
    @types/react:  18.0.21 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 

npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.19.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.19.2
npm notice Run npm install -g npm@8.19.2 to update!

**Comment by flaviendelangle** [comment]
Hi, 

I tried to reproduce your bug with a fresh NextJS install and everything worked fine.
Could you please provide a reproduction case (it can be an archive, or a Codesandbox with NextJS for instance).
The problem may only occur with some TypeScript config.
