### ISSUE TITLE
[docs] Typo in landing page

### ISSUE THREAD

**Issue by davidnagli** [mui/mui-x#6615]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

<img width="1244" alt="Screen Shot 2022-10-23 at 18 34 20" src="https://user-images.githubusercontent.com/6759650/197421474-cb290af9-1a97-4edd-ae68-37c60e6691c5.png">

### Expected behavior 🤔

It should say fetch

### Steps to reproduce 🕹

Link to live example:

Steps:
1. [Click here](https://mui.com/x/react-data-grid/demo/)
2.
3.
4.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Hello @davidnagli 
Thank you for opening this issue.
Maybe you would be interested in fixing it?
It looks like only fixing the typo and running `yarn docs:typescript:formatted` would be enough. 🤔

**Comment by banoth-ravinder** [comment]
@davidnagli I have fixed this issue. Can you please review my PR? 
Thanks in advance.

**Comment by banoth-ravinder** [comment]
@LukasTy @flaviendelangle can you please review my PR? I have fixed this issue.  
https://github.com/mui/mui-x/pull/6632
Thanks in advance.

From my side, I'm not able to set the reviewers and add labels to my PR. so, I'm requesting it here in the comment section.
