### ISSUE TITLE
[DateRangePicker] on mobile opens keyboard after selecting date

### ISSUE THREAD

**Issue by parvusville** [mui/mui-x#6627]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Selecting the date range from the calendar and pressing "OK" automatically focuses to the input and opens keyboard on my Android mobile device. 

### Expected behavior 🤔

Keyboard should not automatically open up. This is the behavior with DatePicker component for example. 

### Steps to reproduce 🕹

Link to live example:
Any example from the documentation: https://mui.com/x/react-date-pickers/date-range-picker/

Steps:
1. Open date selection from the input
2. Select dates and press OK

### Context 🔦

Automatically opening the keyboard after selecting date range is bad UX. 

### Order ID 💳 (optional)

51665

**Comment by LukasTy** [comment]
Thank you for opening this issue. 🙏 
Seems like we have an inconsistency in implementations for mobile behaviours.
- Where `MobileDatePicker` uses readonly inputs—which essentially act as buttons for opening modal
- `MobileDateRangePicker` uses same bare inputs as in desktop mode—which results in this unwanted behaviour
