### ISSUE TITLE
[DatePicker] Trying to type date into DesktopDatePicker automatically fills date based on first character

### ISSUE THREAD

**Issue by sheuertz** [mui/mui-x#6633]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When trying to type a date into the DesktopDatePicker, it is filling the date based on the first entered character. For example, trying to enter today's date 10/25/2022, when the 1 is entered, it is processed and parsed to be 01/01/2001 and that is put into the datepicker. It's currently unable to manually type in the date. This is a new development, as it was working previously.

### Expected behavior 🤔

You should be able to type a date into the date picker.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/sleepy-tom-c5eibg

Steps:
1. Try to enter a date manually

### Context 🔦

Trying to enter a date manually vs requiring the user to always use the picker popper.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 Using Chrome 106.0.5249.119

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.52)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base:  5.0.0-alpha.103
    @mui/core-downloads-tracker:  5.10.11
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.11 => 5.10.11
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system: ^5.10.10 => 5.10.10
    @mui/types:  7.2.0
    @mui/utils:  5.10.9
    @mui/x-data-grid:  5.17.8
    @mui/x-data-grid-pro: ^5.17.8 => 5.17.8
    @mui/x-date-pickers:  5.0.5
    @mui/x-date-pickers-pro: ^5.0.5 => 5.0.5
    @mui/x-license-pro:  5.17.0
    @types/react: ^18.0.21 => 18.0.21
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.8.4
```
</details>

### Order ID 💳 (optional)

40227

**Comment by sheuertz** [comment]
Here is a simpler example based on the MUI example: https://codesandbox.io/s/pensive-heyrovsky-h2qvp8?file=/src/App.js

**Comment by LukasTy** [comment]
I can confirm that on `v5.0.0-alpha.5` it is working as expected.
After `v5.0.0-alpha.6` it is behaving like mentioned in the issue.

**Comment by LukasTy** [comment]
[The PR](https://github.com/mui/mui-x/pull/4486) introducing this "regression".

**Comment by LukasTy** [comment]
@sheuertz I've created the [following sandbox](https://codesandbox.io/s/muddy-cdn-1js4m5?file=/src/App.js).
Ideally, we shouldn't add custom event handlers to the `renderInput` as it might cause unwanted behaviour—like in this case. It's best to try achieve your desired result using the first level (DatePicker) API and rely on it passing required props to the `renderInput`.
Could you confirm if it does solve/cover your requirement, but with a different implementation than the one you provided?

**Comment by sheuertz** [comment]
Alrighty, looks good with the latest version with our workarounds removed. Thanks for your help!
