### ISSUE TITLE
[data grid] Grouped Grids Not Sorting Correctly when using "original" column

### ISSUE THREAD

**Issue by tnoetzel** [mui/mui-x#6641]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you have column grouping turned on for a column and then sort by the original column (not the grouped version), sorting doesn't work properly.

Clicking on the sorting button either does nothing, or sorts improperly, depending on your setup. 

### Expected behavior 🤔

This is extremely confusing to end users. Even if you use the `useKeepGroupedColumnsHidden` hook, users can still unhide that column if you have the toolbar enabled.

The column sorting should work properly, _or_ at the very least you should be able to totally hide the row.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/nostalgic-cookies-zdql2s

Steps:
1. In the example, click "columns" and enable the "original" company column.
2. Sort by that column
3. Note that nothing happens.

### Context 🔦

Users are confused by this and report it as a bug. Since there's no way to permanently hide the grouped column, this keeps cropping up.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.0
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.9.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.62
    Edge: Not Found
    Firefox: 104.0.2
    Safari: 16.1
  npmPackages:
    @emotion/react: ^11.6.0 => 11.6.0 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.92 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/material: ^5.1.0 => 5.10.0 
    @mui/private-theming:  5.9.3 
    @mui/styled-engine:  5.10.0 
    @mui/system:  5.10.0 
    @mui/types:  7.1.5 
    @mui/utils:  5.10.6 
    @mui/x-data-grid:  5.17.6 
    @mui/x-data-grid-premium: ^5.17.6 => 5.17.6 
    @mui/x-data-grid-pro: ^5.17.6 => 5.17.6 
    @mui/x-license-pro:  5.17.0 
    @types/react: ^17.0.20 => 17.0.20 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.4.2 => 4.4.2 
```
</details>

### Order ID 💳 (optional)

51562

**Comment by cherniavskii** [comment]
Hey @tnoetzel 
Thanks for reporting this, indeed it looks like a bug.

**Comment by cherniavskii** [comment]
For v5, the fix seems to be pretty straightforward - we can store a grouping value in group row model (currently it's an empty  object):

```diff
diff --git a/packages/grid/x-data-grid-pro/src/utils/tree/buildRowTree.ts b/packages/grid/x-data-grid-pro/src/utils/tree/buildRowTree.ts
index a38188e..29a71d4 100644
--- a/packages/grid/x-data-grid-pro/src/utils/tree/buildRowTree.ts
+++ b/packages/grid/x-data-grid-pro/src/utils/tree/buildRowTree.ts
@@ -150,7 +150,7 @@ export const buildRowTree = (params: BuildRowTreeParams): GridRowTreeCreationVal
         };
 
         if (isAutoGenerated) {
-          idRowsLookup[nodeId] = {};
+          idRowsLookup[nodeId] = { [node.groupingField!]: node.groupingKey };
           ids.push(nodeId);
         }
 
```

For v6 it gets more complex, since we don't store data model for groping rows anymore.
But this seems to work:
```diff
diff --git a/packages/grid/x-data-grid/src/hooks/features/sorting/gridSortingUtils.ts b/packages/grid/x-data-grid/src/hooks/features/sorting/gridSortingUtils.ts
index e3ab32c..90d56c0 100644
--- a/packages/grid/x-data-grid/src/hooks/features/sorting/gridSortingUtils.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/sorting/gridSortingUtils.ts
@@ -70,13 +70,24 @@ const parseSortItem = (
     ? (...args) => -1 * column.sortComparator!(...args)
     : column.sortComparator!;
 
-  const getSortCellParams = (id: GridRowId): GridSortCellParams => ({
+  const getSortCellParams = (id: GridRowId): GridSortCellParams => {
+    const rowNode = apiRef.current.getRowNode(id)!;
+    let value = apiRef.current.getCellValue(id, column.field);
+
+    if (rowNode.type === 'group' && rowNode.groupingField === column.field) {
+      if (typeof value === 'undefined') {
+        value = rowNode.groupingKey;
+      }
+    }
+
+    return {
       id,
       field: column.field,
-    rowNode: apiRef.current.getRowNode(id)!,
-    value: apiRef.current.getCellValue(id, column.field),
+      rowNode,
+      value,
       api: apiRef.current,
-  });
+    };
+  };
 
   return { getSortCellParams, comparator };
 };
```

cc @flaviendelangle does the above make sense to you?

**Comment by tnoetzel** [comment]
@cherniavskii @flaviendelangle - Any update on this?

**Comment by tnoetzel** [comment]
@cherniavskii  @flaviendelangle  - Just following up on this!

**Comment by flaviendelangle** [comment]
For the v5 fix.
I fear that the fix you propose @cherniavskii has unwanted side effect.
How would it work with `valueGetter` and / or `groupingValueGetter` ?
And don't we risk to have unwanted rendered values if we start to inject some custom data inside the auto generated row models ?

**Comment by flaviendelangle** [comment]
For the v6 fix.
I seems to work fine in most scenarios.
But it will not work in some edge case with `groupingValueGetter` (if the user provides a `groupingValueGetter` and some custom sorting for the grouping column, then sorting the grouping column value with the original column comparator  won't work).

Maybe the clean solution would be to apply the grouping column sorting to the groups instead of tweaking the original column sorting.
But that's probably a deeper change in the sorting architecture to be able to apply different sorting comparator depending on the row we are comparing.

**Comment by tnoetzel** [comment]
@flaviendelangle @cherniavskii - Possible to get this fixed?

**Comment by cherniavskii** [comment]
Hey @tnoetzel 
We'll need more time to investigate this as the solution I proposed earlier isn't a proper one as pointed out by Flavien.

> Since there's no way to permanently hide the grouped column

I think we can make this possible, I'll look into it.
Would it work as a workaround?

**Comment by tnoetzel** [comment]
@cherniavskii - Yeah, I think the ability to permanently hide the original column from users would solve this "enough" for now!

**Comment by cherniavskii** [comment]
@tnoetzel Great, I created this demo: https://codesandbox.io/s/mystifying-thompson-o8nizm?file=/demo.tsx
The only issue is that it's still possible to show the grouped column using the "Show all"/"Hide all" buttons in the column menu. This will be fixed in https://github.com/mui/mui-x/pull/7637

**Comment by tnoetzel** [comment]
@cherniavskii - Ideally the hidden column wouldn't show up with a switch in the show/hide columns list at all... my guess is showing it and having it totally disabled is likely to confuse users even more.

**Comment by cherniavskii** [comment]
> @cherniavskii - Ideally the hidden column wouldn't show up with a switch in the show/hide columns list at all... my guess is showing it and having it totally disabled is likely to confuse users even more.

We will track this request in a separate issue: https://github.com/mui/mui-x/issues/7534
