### ISSUE TITLE
[data grid] components override - input focus lost on each Event

### ISSUE THREAD

**Issue by DaCastle** [mui/mui-x#6642]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When trying to override one of the DataGrid default components via:

`
<DataGrid
        {...data}
        components={{ COMPONENT: MY_COMPONENT  }}
      />
`

If you try to use a controlled input (TextField for example) as part of MY_COMPONENT, focus is lost on each input (Event). The result is that after each keystroke, focus is lost on the input, and must be refocused via mouse click.

### Expected behavior 🤔

I would expect focus to remain in the input field until the user clicks out of the input.

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/pensive-hypatia-bgvz67?file=/demo.tsx

Steps:
1. Try typing multiple keystrokes into the `Search For...` input that is contained in the footer.

### Context 🔦

The DataGrid Footer section would be a great spot for me to add a text input to use to custom-filter the data rows supplied to the grid. My users currently (legacy app, not using MUI) have the ability to immediately click into an input field and search fields by value, and from what I've found so far,  the only way to filter fields by value (via DataGrid) is by either an individual fields popper/modal if the ColumnMenu is enabled, or using the Toolbar, which again, utilizes a popper/modal.

### Your environment 🌎

reference codesandbox utilized for reproduction.

**Comment by DaCastle** [comment]
@m4theushw Thanks for the reply!

The problem I had with that approach is that then the searchValue state is not accessible to the component that creates the data grid, which is necessary in order to utilize it.

I'm seeing the same issue if I try to keep the searchValue & setSearchValue data grid level and pass them as props to the custom footer component, and the same issue if I try to lift the state to the level above the component that renders the data grid.

I'm guessing I'm missing something obvious, but from what I'm seeing, these approaches don't allow the searchValue state to be managed at or above the component level that renders the data grid, as these all lead to re-renders.

**Comment by yaredtsy** [comment]
Hi @DaCastle , move the state with `MyFotter`. you can access DataGrid with `useGridApiContext` . you can read about it here https://mui.com/x/react-data-grid/components/

**Comment by DaCastle** [comment]
Hey @yaredtsy,

From the docs and trying to implement, it looks like this only allows access to the datagrid api state values, not custom state that might be used by the overridden Footer component in my situation.

**Comment by yaredtsy** [comment]
anything related to the Fotter move it to `MyFooter` component. why do you want `searchValue` to be in `ToolbarGrid`?

**Comment by DaCastle** [comment]
> You can use `componentsProps.footer` to pass props to component you passed in `components.Footer`. I updated the CodeSandbox with an example: https://codesandbox.io/s/loving-archimedes-tslvoz?file=/demo.tsx
> 
> Note that, since on each keystroke the state is updated, this causes the component wrapping the DataGrid to be re-rendered also on each keystroke. I recommend to add a debounce to `setSearchValue` to reduce the number of re-renders.

@m4theushw this is exactly what I was looking for, thank you!

I was missing the pairing of the `components` with the `componentsProps` - I had been trying to do it all-in-one, like:

`
          components={{
            Footer: () => {
              return (
                <MyFooter
                  searchValue={searchValue}
                  setSearchValue={setSearchValue}
                />
              );
            },
          }}
`

Which I think was passing a new instance of the component on each state update, as opposed to your example of just passing a reference to my custom footer via `component` prop and passing it's desired props via `componentProps`

And yep, my plan was to debounce the input for the reasons you mentioned! (:
