### ISSUE TITLE
[data grid] Column dragging behavior isnt ideal - columns jumping back to position if users mouse leaves the header?

### ISSUE THREAD

**Issue by gavbrennan** [mui/mui-x#6644]
### Order ID 💳

50374

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Users are complaining that when dragging columns into position if their mouse pointer has stayed outside of the header, the column snaps back to its original location.    Is there a way this can be fixed?  Column appears to end in the right place with the pointer outside the header, just on releasing the mouse button it jumps back.

(Using chrome latest)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\GIT\Pltfm\client\pltfm\node_modules\.bin\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.754.0), Chromium (106.0.1370.52)
  npmPackages:
    @emotion/react: ^11.5.0 => 11.9.0
    @emotion/styled: ^11.3.0 => 11.8.1
    @mui/base:  5.0.0-alpha.100
    @mui/core-downloads-tracker:  5.10.8
    @mui/icons-material: ^5.10.6 => 5.10.6
    @mui/lab: ^5.0.0-alpha.98 => 5.0.0-alpha.98
    @mui/material: ^5.10.8 => 5.10.8
    @mui/private-theming:  5.10.6
    @mui/styled-engine: ^5.10.8 => 5.10.8
    @mui/styles: ^5.10.8 => 5.10.8
    @mui/system: ^5.10.8 => 5.10.8
    @mui/utils:  5.10.3
    @mui/x-data-grid:  5.17.6
    @mui/x-data-grid-generator: ^5.17.6 => 5.17.6
    @mui/x-data-grid-premium:  5.17.6
    @mui/x-data-grid-pro: 5.17.6 => 5.17.6
    @mui/x-date-pickers: 5.0.4 => 5.0.4
    @mui/x-date-pickers-pro: 5.0.4 => 5.0.4
    @mui/x-license-pro:  5.17.0
    @types/react: ^17.0.2 => 17.0.45
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.3.5 => 4.6.4
</details>

**Comment by gavbrennan** [comment]
Ok, I see the reason for the behaviour now, but several users have highlighted it as a negative UX factor so I would appreciate it if we can get that switch in place.  Is there a way to get ctrl-z bound to undo the last action on the control (as a fallback to the existing behaviour being turned off)?  Not a big deal (I know our users would prefer just to drag the column back into place vs the existing behaviour) but just a thought.

**Comment by cherniavskii** [comment]
Closed by https://github.com/mui/mui-x/pull/6697
