### ISSUE TITLE
[data grid] Remove `React.memo` from `GridCellCheckboxRenderer`

### ISSUE THREAD

**Issue by mattcorner** [mui/mui-x#6646]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The disabled/enabled state of checkboxes on the table renders one action behind the users interaction. 

### Expected behavior 🤔

The disabled/enabled state of the checkboxes should reflect the existing state. The user should not see out of data states.

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-data-grid-selectable-row-issue-4f2k1q

Steps:
1. Make a row selection via a checkbox.
2. All rows that do not have the same commodity should be disabled, but are not.
3. Deselect the selection made in step 1. All rows should be enabled, but the expected state from step 2 is instead rendered.

https://user-images.githubusercontent.com/27866636/198279727-04a41a18-bf8a-440e-93a7-6cb7919a14d1.mov

### Context 🔦

Trying to implement selection logic where users can only select items that have the same value for a column. In the provided example, if a selection is made, then the user may only select additional rows that have the same commodity value.

### Your environment 🌎

Browser: Arc Browser

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by mattcorner** [comment]
Forcing a complete rerender by supplying a full copy of the rows on each render shows the expected behaviour from a UI perspective.

https://codesandbox.io/s/mui-x-data-grid-selectable-row-issue-workaround-kf5dcg

**Comment by richie1720** [comment]
I believe I'm experiencing the same issue. See my post on StackOverflow [here](https://stackoverflow.com/questions/74211820/material-ui-datagrid-selectable-rows-not-updating-after-state-change)

Adding a video to demostrate:

https://user-images.githubusercontent.com/94348185/198315714-9ea40d30-0b4c-4783-bfb2-9988c12026b5.mp4

**Comment by romgrk** [comment]
Is it the same issue as #9720 or #9889?

**Comment by mattcorner** [comment]
> Is it the same issue as #9720 or #9889?

Both cover the same issue I think. The checkbox rendering lags behind until clicked on.

**Comment by romgrk** [comment]
Ok, you can subscribe to those issues to track it then, no need to reopen.

**Comment by miguelfreitasiit** [comment]
Any updates?
