### ISSUE TITLE
[data grid] What is the purpose of initialState? Is it more performant than regular controlled state?

### ISSUE THREAD

**Issue by Richard87** [mui/mui-x#6654]
### Order ID 💳

34039

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi!

We are currently using initialState and api.restoreState to preset filters (we have a few "quick-filter" buttons).

But it feels wrong, it would feel better to use just a state property directly, but I assume initialState is not there for no reason (also since there is so many model state it seems easy to forget some!)

I also tried setting the initialState directly, but changing the key prop to force a rerender when changing. It forced a rerender, but the new initialState was not used...

So my question:
- Is there some documentation why initialState is used?

**Comment by flaviendelangle** [comment]
You have several benefits:

1. Simpler for basic use cases

The `initialState` is here to allow you to set initial value without caring about when they update.
If you don't want to persist those models or apply any logic when they update, then it is simpler to use the `initialState`

```tsx
<DataGrid initialState={{ filter: { filterModel: DEFAULT_FILTER_MODEL } }} />
```

Is simpler than:

```tsx
const [filterModel, setFilterModel] = React.useState(DEFAULT_FILTER_MODEL);

<DataGrid filterModel={filterModel} onChange={setFilterModel} />
```

2. Performances

You don't have to re-render your component whenever a model change.
If rendering the component calling the data grid is not light, then it is interesting to keep those state updates internal, your component will render a lot less.

3. Import / Export of the state without caring about the structure of the state

In the doc about the [state import / export](https://mui.com/x/react-data-grid/state/#restore-the-state-with-initialstate), you can see that we don't care about which models are saved.
If tomorrow we add a new feature with a new model (which happens several time a year), then it will automatically be exported without you needing to see which models it must be bound to.


____

But if you are only persistent 1-2 states, maybe using controlled models will be easier to implement and to maintain.
The initial state import / export has mostly been design for full import / export.

**Comment by flaviendelangle** [comment]
Closing this one for lack of feedbacks

**Comment by Richard87** [comment]
Thank you for your answers! And I'm sorry for not getting back and closing it myself sooner :)
