### ISSUE TITLE
`meterial-ui/icons` installation fails with network error

### ISSUE THREAD

**Issue by sagardeshraj** [mui/mui-x#6687]
meterial icon is not installing... 
datagram is not adding to my components.. 
please resolve it... so annoying

**Comment by LukasTy** [comment]
Could you please provide more information about your problem?
If possible—a live reproduction example would be best. You could use [this codesandbox](https://codesandbox.io/s/90oi2r?file=/demo.tsx) as a starting point.

**Comment by sagardeshraj** [comment]
sure,

![aa](https://user-images.githubusercontent.com/115701072/199055687-cc470be9-30b6-4d6e-bd8a-d187d637a3c1.png)

sure, as far as codesandbox is concerned, @mui/icons-material is adding but not in my local machine, via yarn or official website!
please try to do it from your end and let me know if it works.

**Comment by LukasTy** [comment]
<img width="1000" alt="Screenshot 2022-10-31 at 18 17 33" src="https://user-images.githubusercontent.com/4941090/199057023-e5871844-1400-4e34-8031-daf4c51616f5.png">
Just added this dependency in a local test project without issues. 🤔 

FYI, consider using https://www.npmjs.com/package/@mui/icons-material if you have upgraded to @mui v5. 😉 

Based on you error message—I'd suggest looking at your network status.
- Try different connection
- Try manually going to the mentioned URL

In any case—it's clearly not a code related problem. 😉

**Comment by sagardeshraj** [comment]
certainly it was issue with my wi-fi , sometimes it's frustrating. Thanks for the direction sir.
