### ISSUE TITLE
[DataGridPremium] Custom cell component is not used for grouping cell

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#6689]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Go to https://codesandbox.io/s/elastic-jackson-ofe8v4?file=/demo.tsx
2. Open the column menu on the "Plan" column
3. Click the "Group by plan" button

### Current behavior 😯

If column has `renderCell` defined, it's not being used for grouping cell
<img width="785" alt="Screenshot 2022-10-31 at 11 17 41" src="https://user-images.githubusercontent.com/13808724/198985770-3535163b-1d2d-4f99-b996-c638d4b06ce1.png">

### Expected behavior 🤔

If column has `renderCell` defined, it should be used for grouping cell

### Context 🔦

You don't have a lot of options to make it work:
1. `renderCell` on the column is not being used
2. `renderCell` on `groupingColDef` replaces the whole cell and you loose the group expansion button
3. @joserodolfofreitas used `valueFormatter` on `groupingColDef` and returned custom component there:
https://github.com/mui/mui-x/blob/8e256d165caf700f3e63cd8a8d8b6f204b453332/docs/data/data-grid/demo/PopularFeaturesDemo.tsx#L361-L365
	  There are a few issues with this approach though:
	  - it's not a default behavior
	  - it's a hack and it's not obvious you can make it work like this
	  - `valueFormatter` wasn't designed to return a `ReactNode` - `renderCell` is supposed to do that

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
I agree that using `valueFormatter` is a hack

I would prefer to use the column render cell or the `groupingColDef.renderCell` and try to make it smarter (pass the extension button as a `ReactNode` that the user can render if he wants ?

**Comment by cherniavskii** [comment]
@flaviendelangle I think the best DX would be if it works out of the box and custom cell component is used in grouping cell by default

**Comment by joserodolfofreitas** [comment]
Using `groupingColDef.renderCell` doesn't feel intuitive in this case, unless you want to replace/extend the default behavior of the whole column (Show a different icon, interaction, count, etc.)
But the GroupingColDef is responsible for rendering multiple columns (in case you're grouping by more than one field), so whenever it's rendering the value of a particular field, I believe it should do with that fields renderCell.

**Comment by joserodolfofreitas** [comment]
For example:
Consider the following use case: 

<img width="840" alt="image" src="https://user-images.githubusercontent.com/550141/199054298-8129c900-614e-4992-858b-107d43f389eb.png">

If instead of displaying the company and directors as strings, we had a render cell to display a company logo and the directors name and profile picture, I believe developers would expect that both custom renders are contemplated when grouping those columns. 
I believe that'd be the expected out-of-the-box experience.

**Comment by jfsaman** [comment]
I still have this problem. Has it been resolved?

**Comment by AdamJPcars** [comment]
I am having the same issue.
In my opinion the renderCell shouldn't take away the collapsing functionality, because it defeats the whole purpose of using the treedata.

**Comment by alipalvane** [comment]
you can use this for exapmle:
```
 renderCell: (params) => (
      <a target="_blank" href={params.row.name}>
        {params.row.name}
      </a>
    ),
```

**Comment by YosefSchwartz** [comment]
@cherniavskii 

You can use both, `renderCell` and `valueFormatter` to achieve your goal.

For example, to add a checkbox inside the grouping column (to use the indent also on this checkbox) 

```
groupingColDef={{
    valueFormatter: (params: any) => {
        return(
            <div style={{display:'flex', gap:'4px'}}>
                <CustomCheckboxComponent/>
                <p>{params.value}</p>
              </div>
            );
    },
     renderCell : (params : any) => <GridTreeDataGroupingCell {...params} offsetMultiplier={5} hideDescendantCount/>
```

<img width="775" alt="Screenshot 2024-06-20 at 14 43 42" src="https://github.com/mui/mui-x/assets/73064850/99f5761e-c4c7-4b48-9286-82ad2b89f31f">
}}
