### ISSUE TITLE
[data grid] Add slot for the column header

### ISSUE THREAD

**Issue by mwardGresham** [mui/mui-x#6691]
### Order ID 💳

45466

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I cant find a way to get access to the anchored cell (blue outlined selected cell) in the datagrid e.g. onAnchorCellChange

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @mwardGresham 
Could you describe what you're trying to achieve?
Thanks!

**Comment by mwardGresham** [comment]
Hello
We are looking to get an event when a cell is focused, to then get the column and row position and value. You have onCellFocusOut but no onCellFocus, is there a reason for this?

We're trying to get a context menu on our grid, it has to work for both the cells and header cells, but right clicking on cells doesn't cause onCellClick or onColumnHeaderClick to fire, we've seen the demo provided here (https://mui.com/x/react-data-grid/components/#row) but couldn't get it to work for cell headers and also doesn't return the row/header position of the selection.

Thanks

**Comment by mwardGresham** [comment]
Any update on this so we can progress?

**Comment by cherniavskii** [comment]
Hey @mwardGresham 
> We are looking to get an event when a cell is focused, to then get the column and row position and value

You can use `componentsProps.cell.onFocus`:
https://codesandbox.io/s/modest-nova-bih4ch?file=/demo.tsx

> but right clicking on cells doesn't cause onCellClick or onColumnHeaderClick to fire

This is expected. You have to use `componentsProps.cell.onContextMenu` to get the context menu event on the cells:
https://codesandbox.io/s/serverless-snow-2qgtec?file=/demo.tsx
For the column headers, I'm afraid it's not possible to subscribe to the contextMenu event right now.
We can add `onColumnHeaderContextMenu` prop to support it

**Comment by mwardGresham** [comment]
A slot for the column header in components props would solve our issue I think, if that could be added?
The row position is no longer an issue thanks

**Comment by mwardGresham** [comment]
Hello, is it possible for us to get any ETA on this?

**Comment by cherniavskii** [comment]
Hey @mwardGresham 
Could you try using `renderHeader` for capturing the context menu event in the column header?
https://codesandbox.io/s/relaxed-minsky-yl8tws?file=/demo.tsx
Would that work for you?
