### ISSUE TITLE
[docs] The nested imports from X should be named imports on api page

### ISSUE THREAD

**Issue by Victor-Ek** [mui/mui-x#6695]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/spring-wind-zmu7ud?file=/src/index.tsx

Steps:
1. Try to import LocalizationProvider by `import LocalizationProvider from '@mui/x-date-pickers/LocalizationProvider';`
2. Error

### Current behavior 😯

Using this type of import gives `JSX element type 'LocalizationProvider' does not have any construct or call signatures.ts(2604)`

### Expected behavior 🤔

No ts error

### Context 🔦

According to best practices here https://mui.com/x/api/date-pickers/localization-provider/#main-content and here https://mui.com/material-ui/guides/minimizing-bundle-size/ I should use default import.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 1.00 GB / 31.08 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.13.1 - /run/user/530602374/fnm_multishells/8486_1666680570802/bin/node
    Yarn: 3.2.3 - ~/repos/antura-projects/Frontend/node_modules/.bin/yarn
    npm: 8.1.2 - /run/user/530602374/fnm_multishells/8486_1666680570802/bin/npm
  Managers:
    Apt: 2.4.8 - /usr/bin/apt
    RubyGems: 3.3.5 - /usr/bin/gem
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.3.0 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
  Virtualization:
    Docker: 20.10.20 - /usr/bin/docker
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    VSCode: 1.72.2 - /snap/bin/code
    Vim: 0.6.1 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Perl: 5.34.0 - /usr/bin/perl
    Python3: 3.10.6 - /usr/bin/python3
    Ruby: 3.0.2 - /usr/bin/ruby
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 106.0.2
  Monorepos:
    Yarn Workspaces: 3.2.3

```
</details>

**Comment by LukasTy** [comment]
Thank you for raising this issue.
This seems to be a more general issue/topic in regards to `@mui/x-` packages.
As far as I've tested—we've got a lot of cases of exports, which are not in line with the documentation and `@mui/material` exports.
We currently mainly only support `named` exports both from root package level, as well as, component level:

```js
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
// or
import { LocalizationProvider } from '@mui/x-date-pickers';
```

whereas based on our docs we ought to support the following export style:

```js
// default
import LocalizationProvider from '@mui/x-date-pickers/LocalizationProvider';
// named
import { LocalizationProvider } from '@mui/x-date-pickers';
```

@alexfauquette @flaviendelangle Was there any particular reason our package strayed away from the recommended export approach?
Or is it just an inconsistency we should work on fixing?
