### ISSUE TITLE
[DateRangePicker] `DateRangePickerDay` sx prop not forwarded to DateRangePickerDayRoot

### ISSUE THREAD

**Issue by lildesert** [mui/mui-x#6699]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-template-forked-7y5mkg?file=/src/App.tsx

Steps:
1. Pick a date range
2. The `rangeIntervalDayHighlight` should have an orange background

Note that if I had the following code into the `sx` prop, it styles the button correctly
```
[`&&.${pickersDayClasses.selected}`]: {
          backgroundColor: colors.primary,
        },
```

### Current behavior 😯

No style is applied to the component.

### Expected behavior 🤔

Custom style is taken into account.

### Context 🔦

I'm trying @mui/x-date-pickers-pro to see if it could fit my use case and if I can customise the UI easily.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4 
    @emotion/styled: 11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.102 
    @mui/core-downloads-tracker:  5.10.10 
    @mui/material: 5.10.10 => 5.10.10 
    @mui/private-theming:  5.10.9 
    @mui/styled-engine:  5.10.8 
    @mui/system:  5.10.10 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.9 
    @mui/x-date-pickers:  5.0.5 
    @mui/x-date-pickers-pro: 5.0.5 => 5.0.5 
    @mui/x-license-pro:  5.17.0 
    @types/react: 18.0.8 => 18.0.8 
    react: 18.1.0 => 18.1.0 
    react-dom: 18.1.0 => 18.1.0 
    typescript: 4.6.2 => 4.6.2
```
</details>

**Comment by LukasTy** [comment]
Hello @lildesert 
This is indeed an error on our side.
But have you [tried using `theme` to achieve the same](https://codesandbox.io/s/mui-x-issue-template-forked-5yjbtu?file=/src/App.tsx) thing without the need of custom `renderDay` just to apply styles? 🤔

**Comment by LukasTy** [comment]
We have this issue already resolved in the [alpha v6 releases](https://github.com/mui/mui-x/pull/5944)
Would the ☝️ suggested approach suffice until v6?
Because technically—such change is a breaking one. It might break someone else's implementation where they rely on `sx` being applied to the `button` element. 🤔

**Comment by lildesert** [comment]
Hi @LukasTy and thanks for the fast answer!

So I didn't try anything else yet. I'm using tailwind to style my app and build a design system so I just followed Mui docs to see how I could customize the components and if it was easy to do so.

I aim to have a nice date range picker with our style on top that I could use anywhere. I thought the `sx` way was interesting because it seemed only to change the style for this specific component but I didn't realize it was a breaking change.

For me, the ideal approach would be to use tailwind classes to style any Mui components, including their different states but I don't know if it's realistic.

By looking at v6-alpha code, I came to [this example](https://github.com/flaviendelangle/material-ui-x/blob/3006cab0e0f9c1afcde486fbcc866904013fcd25/docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.js) so I guess I could do something like that.

I also went through [this doc](https://mui.com/base/guides/working-with-tailwind-css/) but I'm not sure it would work to style "highlighted" states etc.

**Comment by LukasTy** [comment]
> but I didn't realize it was a breaking change.

I meant that if we would apply the required fix to cover your mentioned case—the change could possibly be a breaking one to someone else using `sx` prop and expecting to be applied where it is currently being applied.

> By looking at v6-alpha code, I came to [this example](https://github.com/flaviendelangle/material-ui-x/blob/3006cab0e0f9c1afcde486fbcc866904013fcd25/docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.js) so I guess I could do something like that.

I'm not very familiar with the capabilities of tailwind, but the example you are referring to uses [our internal](https://mui.com/system/styled/) approach.

> I also went through [this doc](https://mui.com/base/guides/working-with-tailwind-css/) but I'm not sure it would work to style "highlighted" states etc.

This doc explains usage of `@mui/base` (a headless component library) with tailwind. In case of `@mui/x-date-pickers` — we already have material-ui styles coming with it.

___

Have you considered looking [at `classes` prop](https://codesandbox.io/s/mui-x-issue-template-forked-9ugv50?file=/src/App.tsx)? it would allow passing any additional classes on certain cases/elements that you'd want. But, as you can see in the example—we would encounter CSS specificity issue with tailwind utility classes as our own classes would take precedence over it.

**Comment by lildesert** [comment]
Okay, thanks for the answers, much clear now.

> Have you considered looking [at classes prop](https://codesandbox.io/s/mui-x-issue-template-forked-9ugv50?file=/src/App.tsx)?

I didn't know about that, it looks (almost) perfect but this precedence thing is a real blocker.

> But have you [tried using theme to achieve the same](https://codesandbox.io/s/mui-x-issue-template-forked-5yjbtu?file=/src/App.tsx) thing

I think I'll try this solution then. Will it overrides only the specified properties without altering the rest or do I have to worry about that?

> but the example you are referring to uses [our internal](https://mui.com/system/styled/) approach

I've tried this approach but I couldn't manage to style the button as well.

**Comment by lildesert** [comment]
> Could you maybe share a codesandbox with your code that didn't work and we can look into what could be missing?

I updated the [first sandbox](https://codesandbox.io/s/mui-x-issue-template-forked-7y5mkg?file=/src/App.tsx) to include the example with `v6-alpha`. The thing is I don't know if it's possible to style the inner button as well. It's not done in the [example](https://github.com/flaviendelangle/material-ui-x/blob/3006cab0e0f9c1afcde486fbcc866904013fcd25/docs/data/date-pickers/date-range-picker/CustomDateRangePickerDay.js)

> No need to worry, that's only going to override what you specify. Just don't forget that quite often there might be different colors in need of overriding for different states (selected, hover, focus and etc.) 😉

So I tried the two solutions with the style override and also the classes one (even with the `!important` flag) and I couldn't manage to achieve the desired result 😞 

Here's a [fork of your sandbox](https://codesandbox.io/s/mui-x-issue-template-forked-x0f7nl?file=/src/App.tsx) to highlight what I'm trying to achieve

+ a screenshot ->

<img width="611" alt="image" src="https://user-images.githubusercontent.com/5688850/200390320-7f8ecf9e-0718-4921-a565-65b67c8e7d0c.png">

**Comment by lildesert** [comment]
Hey!

Thanks to a warning message in the console I achieved the desired result. See this updated [sandbox](https://codesandbox.io/s/mui-x-issue-template-forked-x0f7nl?file=/src/App.tsx).

I wish it would be easier to customize the component with tailwind for example. But so far Mui has the best `DateRangePicker` in terms of UX for both mobile and desktop so I guess it's worth taking some time to understand how to customize it.

Thanks a lot for your help!

**Comment by LukasTy** [comment]
Hey @lildesert 
I'm glad you were able to achieve what you wanted.
Here are examples with a bit more robust code:
- [theme overriding example](https://codesandbox.io/s/mui-x-issue-template-forked-5ez238?file=/src/App.tsx)
- [styled example](https://codesandbox.io/s/mui-x-issue-template-forked-gr8ru9?file=/src/App.tsx)—in this case the hard-coded classes were replaced by variables

In any case—we still have places for improvement in regards to styling. I'll look into whether we could improve the theme overriding to avoid the need of this cumbersome overrides—where both `picker day` and `date range day` overriding is needed to achieve what we wanted, because we currently can't override styles of selected date range day through it's API. 😞
