### ISSUE TITLE
[question] subscribeEvent('rowsScroll') invokes handler function infinitely within useEffect

### ISSUE THREAD

**Issue by AnvarAka1** [mui/mui-x#6712]
### Order ID 💳

47534

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I want to use the 'rowsScroll' event to identify whether scroll was used or not. If there was a scroll, then it should make scrollbar in the table visible. After several seconds, I want to make it invisible again. So, that is simplified code without setTimeout, to make it more specific to this case, as it works the same with setTimeout. 

Whenever I get this hook inside my Table.jsx file, it:
1) fires `console.log(params)` twice
2) fires `console.log('setting to false')` once
3) again 1 and 2 infinitely and etc

```
function useScroll (apiRef) {
  const [isScrolling, setIsScrolling] = useState(false)

  useEffect(() => {
    if (isScrolling) {
      console.log('setting to false')
      setIsScrolling(false)
    }
  }, [isScrolling])

  useEffect(() => {
    const handleScroll = params => {
      console.log(params)
      setIsScrolling(true)
    }

    return apiRef.current.subscribeEvent('rowsScroll', handleScroll)
  }, [apiRef])

  return { isScrolling }
}
```

I do not know the reason for this, as useEffect with `[apiRef]` dependency fires only once and subscription starts, but it is used twice in a row for some reason as if there are 2 subscribers and whenever useEffect with `[isScrolling]` dependency fires, and isScrolling becomes false, that `rowsScroll` event fires again. No idea why that happens.

What I expect:
- `rowsScroll` event fires only when I scroll the table, not depending on `isScrolling` state

**Comment by AnvarAka1** [comment]
> Could you provide a **minimal** reproduction test case with the latest version. I tested with the code provided and I can't reproduce the infinite behavior of the event listener. A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) may help.

Okay, sorry for not providing the link. Try [this link](https://codesandbox.io/s/data-grid-community-forked-0xmvex?file=/src/App.tsx)

After some changes, I got the reason of the problem. Adding fixedColumns somehow leads to infinite rerun of `rowsScroll` event. How to solve it?

**Comment by yaredtsy** [comment]
hey @AnvarAka1 
there is a workaround. you can directly listen for `scroll` event from `windowRef`

```javascript
  useEffect(() => {
    setTimeout(() => {
      apiRef.current.windowRef.current.addEventListener("scroll", handleScroll);
    }, 0);
    return () => {
      apiRef.current.windowRef.current.removeEventListener(
        "scroll",
        handleScroll
      );
    };
  }, [apiRef]);
```

**Comment by yaredtsy** [comment]
or use `initialState={{ pinnedColumns: { left: ["col1"] } }}` insted of  `pinnedColumns={{ left: ["col1"] }}`

**Comment by AnvarAka1** [comment]
> or use `initialState={{ pinnedColumns: { left: ["col1"] } }}` insted of `pinnedColumns={{ left: ["col1"] }}`

You really saved me a lot of time and effort! Thank you very much. 
But I am curious, why do we have `pinnedColumns={{ left: ["col1"] }}`, if `initialState={{ pinnedColumns: { left: ["col1"] } }}` works and it also accepts new columns to be pinned in the UI.

**Comment by yaredtsy** [comment]
`initialState` can not be controlled. if once set, changing the state won't update the Datagrid. but `pinnedColumns` can be controlled with states. 

```javascript
 const [pin,setPinned] = React.useState<any>({ left: ["col1"] })
 <DataGridPro
        apiRef={apiRef}
        pinnedColumns={pin}
        rows={rows}
        columns={columns}
      />
```
