### ISSUE TITLE
Header's column has no left margin when column has low wight

### ISSUE THREAD

**Issue by taraskondratjuk** [mui/mui-x#6713]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/ehj8dz?file=/demo.js

Steps:
1. Try to make minimus size "Trader email" and "Quantity" columns
2. One column has a left margin from the left side to column's name another has not

![datagrid](https://user-images.githubusercontent.com/57403805/199491029-bbc1be04-d1c7-4c4b-bdd2-536c6f81839c.jpg)

### Expected behavior 🤔
I want to have a left margin from the left side to the column's name

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

52031

**Comment by DanailH** [comment]
Interesting. We are currently setting the `padding` on the `.MuiDataGrid-columnHeader`, maybe we should move it to the `.MuiDataGrid-columnHeaderTitleContainerContent`. It's likely that this will solve the issue.
Regarding a workaround - @taraskondratjuk you can overwrite the padding we are setting and set one directly on the `.MuiDataGrid-columnHeaderTitleContainerContent`.
