### ISSUE TITLE
[pickers] `inputFormat` syntax (e.g. `YYYY-MM-DD`) differs across adapters

### ISSUE THREAD

**Issue by githorse** [mui/mui-x#6717]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

See [stackblitz demo](https://stackblitz.com/edit/react-pe5kx2-cewr9o?file=demo.tsx).

### Current behavior 😯

With `AdapterDayjs`, the input format `YYYY-MM-DD` is valid. This format throws an error with `AdapterDateFns`, which expects `yyyy-MM-dd` instead.

### Expected behavior 🤔

I would expect the input format to be a property of the date picker itself, not the adapter, and thus be consistent across any adapter. (Perhaps I'm wrong and there are reasons for it to work this way.)

If we pick a consistent format, it would be good to go with the most standard version possible, but I'm not sure what that is. The Javascript Date object is a good place to start, or maybe even MS Excel, for the `YYYY-MM-DD` style formats? Personally I would probably vote for the Unix `strftime` conventions. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Linux 5.4 Linux Mint 20.3 (Una)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 913.10 MB / 15.33 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.4 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 20210409.063814.0 - /usr/local/bin/watchman
  Managers:
    Cargo: 1.51.0 - ~/.cargo/bin/cargo
    pip3: 20.0.2 - /usr/bin/pip3
    RubyGems: 3.1.2 - /usr/bin/gem
  Utilities:
    CMake: 3.16.3 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.4.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
    FFmpeg: 4.2.7 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 20.10.21 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    Vim: 0.4.3 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Java: 11.0.11 - /home/rct/.sdkman/candidates/java/current/bin/javac
    Perl: 5.30.0 - /usr/bin/perl
    Protoc: 3.17.0 - /usr/local/bin/protoc
    Python3: 3.8.10 - /usr/bin/python3
    Ruby: 2.7.0 - /usr/bin/ruby
    Rust: 1.51.0 - /home/rct/.cargo/bin/rustc
    Scala: 2.12.12 - /home/rct/.sdkman/candidates/scala/current/bin/scalac
  Databases:
    SQLite: 3.32.2 - /home/rct/Android/Sdk/platform-tools/sqlite3
  Browsers:
    * Chromium: 106.0.5249.119
    Firefox: 106.0.3
  Monorepos:
    Yarn Workspaces: 3.2.4
    Lerna: 5.6.2


```
</details>

### Order ID 💳 (optional)

46840

**Comment by flaviendelangle** [comment]
The `inputFormat` prop uses the format of the date library currently being used inside the pickers.
So if `dayjs` and `date-fns` have different way of representing a 4 digits year (for instance), then this different will end up visible in the `inputFormat` prop.

The adapters contains a list of unified formats (you can find the one of [date-fns](https://github.com/dmtrKovalenko/date-io/blob/master/packages/date-fns/src/date-fns-utils.ts#L59) here).

Internally, we never hardcode a string format, we always rely on this list to make sure that it will work with every adapter.
We could export a hook to easily access those unified formats if it helps in some way.

___

What is your pain point with the `inputFormat` prop ?
Are you trying to use several date libraries inside your app ?
Or are you struggling to copy doc examples due to this different between `dayjs` and the one you use ?
Or something else ?

**Comment by githorse** [comment]
I found this issue while switching adapters due to [an issue with AdapterDateFns](https://github.com/mui/mui-x/issues/6716). And yes, also trying to adapt the Dayjs examples from the docs.

I'll admit, the pain point is pretty minor here. It's easy enough to follow the error message and change the format. To me the adapter is an afterthought and I found it surprising that the format syntax would change between adapters. It would seem ideal if there were a consistent, unified format to handle all cases, but maybe there is a place for each adapter to define its own format? Not sure.

The [documentation on Localization / adapters](https://mui.com/x/react-date-pickers/date-picker/#localization) is a little skimpy (the link just leads back to itself). If the syntax can't be unifed, some additional info there, maybe with pointers to each library's `inputFormat` syntax, would be helpful.

**Comment by flaviendelangle** [comment]
> The [documentation on Localization / adapters](https://mui.com/x/react-date-pickers/date-picker/#localization) is a little skimpy 

I have a full rework of this doc in progress (https://github.com/mui/mui-x/pull/6625).
I will make sure to add what is needed for this specific topic into it :+1: 

And I do agree that the `inputFormat` prop description could be a lot better.

> To me the adapter is an afterthought

In a perfect world it would be.
The reality is, the adapter has a unified API for the internal methods we use, but when we export a format / a date, it is exposed in the format of your library.

This would be worth describing a lot better in the doc.

> It would seem ideal if there were a consistent, unified format to handle all cases

It is technically not doable (or not without re-implementing the whole parsing logic of the date library on our side, which would defeat the purpose or having a date library).
I think this variation across adapters is the best trade-off we have.
We could also support formats like `<DatePicker inputFormat="monthAndYear" />` which would use the format list of the adapter, if we want to abstract slightly more.

**Comment by githorse** [comment]
> It is technically not doable (or not without re-implementing the whole parsing logic of the date library on our side, which would defeat the purpose or having a date library).

Makes sense. This date stuff is complicated enough already.

> We could also support formats like `<DatePicker inputFormat="monthAndYear" />` which would use the format list of the adapter, if we want to abstract slightly more.

It would definitely be cool if the most common patterns could be expressed in a unified way that could translate to each adapter. Personally I would vote against [inventing a new DSL/format syntax](https://xkcd.com/927/) like "monthAndYear" to what seem to be too many competing standards already.

(Personally I use [`strftime`](https://thdoan.github.io/strftime/) because I find the Javascript Date `.toLocaleString(format)`-style syntax poorly-documented and difficult to work with, and the `YYYY` stuff inconsistent across vendors. WIth `strtime` the format is unambiguous, flexible, and the documention is right at my fingertips anytime on the command line. I see that this may not be the best choice if all the vendors use `YYYY` style, however. It would be pretty cool to support both :))

**Comment by flaviendelangle** [comment]
> Personally I would vote against [inventing a new DSL/format syntax](https://xkcd.com/927/) like "monthAndYear" to what seem to be too many competing standards already.

`monthAndYear` is the name of the format inside the adapter.
If we use a date format to close from the one a date library, you could have conflict.
But I would most be in favor of something like

```tsx
const formats = useDateFormats();

return <DatePicker inputFormat={formats.monthAndYear} />
```

To avoid adding some magic and clearly show that the format comes from a lookup.
