### ISSUE TITLE
[data grid] How to disable the checkbox selection field from the columns menu panel

### ISSUE THREAD

**Issue by markand911** [mui/mui-x#6720]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] I have tested the latest version

### Summary 💡

I am using checkboxSelection property to show checkboxes in the first column of data grid. I want to disable hiding of this column. Gone through the documentation, found hideable: false property, but its for custom columns. Is there a way to disable hiding of checkBoxSelection column?

<img width="305" alt="Screenshot 2022-11-03 at 11 40 11 am" src="https://user-images.githubusercontent.com/8840155/199629004-4eb87652-867c-4a61-9479-9556af2c4621.png">

### Examples 🌈

```
<DataGridPro
                sortingOrder={['asc', 'desc']} 
                checkboxSelection
                disableColumnMenu
                disableSelectionOnClick
                columnBuffer={Number.MAX_SAFE_INTEGER}
                />
```

**Comment by yaredtsy** [comment]
Hey @markand911 
try this
```javascript
const columns =    {
        ...GRID_CHECKBOX_SELECTION_COL_DEF,
        hideable: false
      }
     ....
]
```
Demo : https://codesandbox.io/s/empty-butterfly-nfhlhw?file=/demo.tsx

**Comment by markand911** [comment]
I tried this, it works. However the name is different. Somehow its "__check__"
<img width="303" alt="image" src="https://user-images.githubusercontent.com/8840155/199673539-0fe64254-c468-499b-8cd9-1ece8a6c7f72.png">

**Comment by yaredtsy** [comment]
did you override the `headerName` ? 
![image](https://user-images.githubusercontent.com/34584266/199679321-4cc61ed0-8e22-4bfb-8835-e04aacdd0a16.png)

**Comment by DanailH** [comment]
@markand911 it should still work. The name you are seeing is the default internal name we have for the checkbox column. Try doing what @yaredtsy suggested (this way you will create your own custom checkbox column) and overwrite the `headerName` property.

```
const columns =   [{
        ...GRID_CHECKBOX_SELECTION_COL_DEF,
        hideable: false,
        headerName: 'My Checkbox Selection'
      }
]
```

**Comment by markand911** [comment]
Thanks, it worked.
