### ISSUE TITLE
[data grid] Mui Datagrid does not have numbered pagination?

### ISSUE THREAD

**Issue by AkshayGadekar** [mui/mui-x#6721]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://codesandbox.io/s/f7t5uf?file=/demo.tsx

### Current behavior 😯

In DataGrid, for pagination there is only left and right arrow. I needed complete numbered pagination with arrows, but it seems like there is no option for it.

### Expected behavior 🤔

https://codesandbox.io/s/2slrb5?file=/demo.tsx
In this demo, there is way to have numbered pagination, but here total number of pages and records count information is missing.
What I want is usual information like total number of pages and records count with numbered pagination.
Is there any way for this?

**Comment by yaredtsy** [comment]
Hey @AkshayGadekar 
you to customize the `Pagination` component. check this demo: https://codesandbox.io/s/optimistic-tristan-q5cilm?file=/demo.tsx:1436-1446.

**Comment by AkshayGadekar** [comment]
Thanks @yaredtsy and @m4theushw for urgent help, appreciated.

**Comment by HiteshRajpal** [comment]
Hi @yaredtsy ,
Can we use the same with paginationMode="server" and sortingMode="server" ?
