### ISSUE TITLE
DataGrid with custom renderCell for <Dialog> with <DataGrid> inside creates event-click-error

### ISSUE THREAD

**Issue by rompeldunk** [mui/mui-x#6730]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/p/github/rompeldunk/react-nk4pce/draft/happy-moon?file=%2Fsrc%2FSettingsDialog.js&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A5%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cla13cwqo0009l0hn12qn1fau%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fsrc%252FSettingsDialog.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cla13cyb8000m356habn48opt%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Atrue%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cla13elme00ei356h5uws7oaw%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cla13ejej00bt356h3sfq8tq9%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

![image](https://user-images.githubusercontent.com/11426361/199915727-41eeaea1-d2a0-42b7-804e-a1bad1a6ad10.png)

Steps:
1. Open Cog Button
2. Open Cog again in 
3. Click edit/double click any table cell.
4. Type-errors shows in console

### Current behavior 😯

Gives error. Crashes nextjs.

### Expected behavior 🤔

Expects no error on the "top" dialog with DataGrid inside it.
Seems that the onClick-event from the top dialog with DataGrid propagates down to the dialog with Datagrid below.

### Your environment 🌎

<details>
  <summary><code>
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.26)
  npmPackages:
    @emotion/react: ^11.8.2 => 11.10.4
    @emotion/styled: ^11.8.1 => 11.10.4
    @mui/base:  5.0.0-alpha.103
    @mui/core-downloads-tracker:  5.10.11
    @mui/icons-material: ^5.5.1 => 5.10.9
    @mui/lab: ^5.0.0-alpha.86 => 5.0.0-alpha.105
    @mui/material: ^5.5.3 => 5.10.11
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system: ^5.8.3 => 5.10.10
    @mui/types:  7.2.0
    @mui/utils:  5.10.9
    @mui/x-data-grid: ^5.17.9 => 5.17.9
    @mui/x-data-grid-generator: ^5.17.9 => 5.17.9
    @mui/x-data-grid-premium:  5.17.9
    @mui/x-data-grid-pro: ^5.17.9 => 5.17.9
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.5
    @mui/x-license-pro:  5.17.0
    @types/react: ^18.0.21 => 18.0.23
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.6.4 => 4.8.4
</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#28570

**Comment by akshaylive** [comment]
Solution ^^ doesn't work for editable grids as stopping event propagation will mess up editable columns in the child `DataGrid`. As mentioned in #4243 , here's an alternative solution to fix this:

```tsx
onClick={(event) => event.target = document.body}
```
