### ISSUE TITLE
[data grid]: Customizing the filter menu position places other menus under the filter button

### ISSUE THREAD

**Issue by jmkanagy** [mui/mui-x#6734]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/customize-the-filter-panel-position-540rxi

Steps:
1. Go to the "Country" column header and select its menu
2. Choose "Columns" from that menu
3. Notice that the columns menu appears under the filter button
4. Click the "Columns" button in the toolbar
5. Notice that the columns menu also appears just under the filter button.

Hi! First of all, thank you for creating this awesome and complicated widget!

I copied the code example directly from the documentation at https://mui.com/x/react-data-grid/filtering/#customize-the-filter-panel-position and pasted it into the codesandbox link above. Then, I just added the GridToolbarColumnsButton to the CustomToolbar. 

### Current behavior 😯

Currently, the columns menu appears underneath the filter button when the filter button position is customized in the way it is shown in the documentation.  Also, the columns menu of each column header menu appears under the toolbar's filter button. 

### Expected behavior 🤔

I would like the ability to customize the position of the columns button menu so that it appears under the columns button, not under the filter button. But the api to do this doesn't appear to be present. For example, the componentsProp property of the DataGrid in the example looks like this:

```
componentsProps={{
      panel: {
        anchorEl: filterButtonEl
      },
      toolbar: {
        setFilterButtonEl
      }

```
I'm not sure what the "panel" property refers to, as I can not find documentation for it. But there should be an option to set an anchorEl for each button, or at least separate anchorEl's for the Columns and Filter buttons Also, this should not disrupt the positioning of menus accessed via the column headers.

### Context 🔦

The **default** positioning of the Filter and Columns menus made my users unhappy, because they hide the first row of data in the DataGrid. So, I would like to position those menus up a bit higher, directly under the buttons themselves, as the example shows for the filter button. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
I am mostly using Chrome, and my users are mostly using Chrome or Safari.

```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/code/data-engineering/Telemetry/services/hrr/highres-recorder-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: latest => 11.9.0 
    @emotion/styled: latest => 11.8.1 
    @mui/base:  5.0.0-alpha.83 
    @mui/icons-material: ^5.8.2 => 5.8.2 
    @mui/lab: ^5.0.0-alpha.84 => 5.0.0-alpha.84 
    @mui/material: ^5.8.2 => 5.8.2 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system: ^5.8.2 => 5.8.2 
    @mui/types:  7.1.3 
    @mui/utils:  5.10.9 
    @mui/x-data-grid: ^5.17.10 => 5.17.10 
    @mui/x-date-pickers:  5.0.0-alpha.1 
    @types/react:  18.0.10 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript:  4.7.2 
```
</details>

**Comment by MBilalShafi** [comment]
You can set the positioning of the columns selection menu as mentioned in the example you quoted, so `componentsProps.panel.achorEl` can receive a reference to the node next to which you need to show your column selection menu.

Extending your sandbox, I've added a columns button and placed the menu next to it:
https://codesandbox.io/s/serene-keller-qgquno

Please check it out and see if it resolves your issue.

**Comment by jmkanagy** [comment]
> You can set the positioning of the columns selection menu as mentioned in the example you quoted, so `componentsProps.panel.achorEl` can receive a reference to the node next to which you need to show your column selection menu.
> 
> Extending your sandbox, I've added a columns button and placed the menu next to it: https://codesandbox.io/s/serene-keller-qgquno
> 
> Please check it out and see if it resolves your issue.

Thanks for trying it out, but this does not resolve my issue. In your example, BOTH the columns menu AND the filter menu pop up aligned just under the COLUMNS BUTTON. What I'm asking is that the columns menu is aligned underneath the columns button and the filter menu is aligned under the filter button. Any drop down menu should appear under the button that was clicked, not under some other button on the DataGrid. This seems like common sense to me.

**Comment by jmkanagy** [comment]
Sorry for the delay! Thank you so much @MBilalShafi - I took a look at your example and it now solves the issue perfectly! I haven't had a chance to try it out, as I'm on to other work, but will revisit.

**Comment by woodreamz** [comment]
@MBilalShafi Your workaround is working when the panel is open by clicking on the button in the Toolbar but if you use the column menu, it uses the last anchor :/ Same thing if we open the panel using the api.

Is there another solution?
