### ISSUE TITLE
[docs] Broken localization link in date-picker

### ISSUE THREAD

**Issue by kb54** [mui/mui-x#6758]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Clicking on **about localization** in localization anchor [Localization](https://mui.com/x/react-date-pickers/date-picker/#localization) redirects to the same link.

### Expected behavior 🤔

It should be pointing to [Localization Page](https://mui.com/x/react-date-pickers/localization/).

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Thanks for the report, the fix will be deployed at the end of the week :)
