### ISSUE TITLE
[pickers] Unintuitive behavior when changing date with keyboard

### ISSUE THREAD

**Issue by TamirCode** [mui/mui-x#6762]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Using example of Desktop DatePicker in docs :  https://mui.com/x/react-date-pickers/getting-started/

![chrome-capture-2022-10-7 (1)](https://user-images.githubusercontent.com/66864667/200265013-434fce0f-c2bb-4af1-8b6b-7c8df8b36b6d.gif)

The number I press should replace only the digit after the cursor, but as you can see in the gif, it also changes the digit that comes after it to the digit I pressed minus 1. Sometimes changing a single digit also changes the rest of the digits, and I can't imagine why, I think this is unintuitive and unexpected behavior, and I believe its a root issue that leads to overall poor user experience. 

For example if you change the first digit of the year, month or day, then it changes the entirety of everything else. And so in this way it doesn't make sense and I think it could use an improvement: the digit I change by pressing a key should only change that digit and not affect the rest of the digits.

The same behavior occurs with my controlled input.

### Context 🔦

Datepickers are weird overall and I can imagine their complexity. When creating a custom datepicker to replace the native one I expect a better user experience and not any weird unexpected behavior. Everyone in my company and my clients too are complaining about the datepicker behavior and I can understand why, it doesn't have intuitive and sensical behavior, and we work a lot with date inputs so it can be pretty painful.
Thank you very much for your work , greatly appreciated :)

**Comment by alexfauquette** [comment]
HI @TamirCode The root cause of this is the mask strategy. The UX works when you enter a date from scratch, or when yoou delete a character to replace it bu another, but inserting a new one is not well supported

To solve this issue we are working on a new field component for v6

You can find them in the [v6 documentation](https://next.mui.com/x/react-date-pickers/fields/)

For now they are in alpha. Would they solve your issue?

**Comment by githorse** [comment]
@TamirCode if you're using `AdapterDateFns`, you may be seeing a variant of [this problem](https://github.com/mui/mui-x/issues/6716) (not sure).

**Comment by TamirCode** [comment]
Thanks for the info
