### ISSUE TITLE
[data grid] Row pinned is not working in row grouping

### ISSUE THREAD

**Issue by fatih-mdous** [mui/mui-x#6782]
### Order ID 💳

51399

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I try to do rowpinned in row grouping using using your example  https://codesandbox.io/s/data-grid-premium-forked-w904zw?file=/src/App.tsx. 
but getting an error which is about not exporting issue

### Your environment 🌎

<details>
  <summary>`row pinned issue`</summary>

```
src/components/DataGridPro/DataGridPro.js (11:2)
 9:   useGridApiRef,
10:   gridVisibleSortedRowIdsSelector,
11:   useKeepGroupedColumnsHidden,
      ^
12: } from '@mui/x-data-grid-pro';
Error: 'useKeepGroupedColumnsHidden' is not exported by node_modules/@mui/x-data-grid-pro/index.js, imported by src/components/DataGridPro/DataGridPro.js
    at error (/Users/mydigitaloffice/Documents/mdo-react-components/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/Users/mydigitaloffice/Documents/mdo-react-components/node_modules/rollup/dist/shared/rollup.js:12560:16)
    at Module.traceVariable (/Users/mydigitaloffice/Documents/mdo-react-components/node_modules/rollup/dist/shared/rollup.js:12919:29)
    at Module.getVariableForExportName (/Users/mydigitaloffice/Documents/mdo-react-components/node_modules/rollup/dist/shared/rollup.js:12728:35)
    at Graph.warnForMissingExports (/Users/mydigitaloffice/Documents/mdo-react-components/node_modules/rollup/dist/shared/rollup.js:23170:47)
    at Graph.sortModules (/Users/mydigitaloffice/Documents/mdo-react-components/node_modules/rollup/dist/shared/rollup.js:23164:14)
    at Graph.build (/Users/mydigitaloffice/Documents/mdo-react-components/node_modules/rollup/dist/shared/rollup.js:23040:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
</details>

**Comment by alexfauquette** [comment]
In the [documentation of row pinning](https://mui.com/x/react-data-grid/row-pinning/#usage-with-other-features), you can find the list of features with with the row pinning is not compatible yet

> Pinned rows do not support the following features:
> 
> - editing ([issue #5591](https://github.com/mui/mui-x/issues/5591))
> - selection
> - row grouping
> - tree data
> - row reordering
> - master detail

**Comment by fatih-mdous** [comment]
I asked @oliviertassinari he send me https://codesandbox.io/s/data-grid-premium-forked-w904zw?file=/src/App.tsx.

**Comment by oliviertassinari** [comment]
> he send me

https://mui.zendesk.com/agent/tickets/5620

@fatih-mdous The codesandbox that I shared uses MUI X Premium, but you have a MUI X Pro license, hence the error, and hence why it runs in the codesandbox.

> you can find the list of features with with the row pinning is not compatible yet

@alexfauquette Do we know what's missing for the row pinning + row grouping to work in conjunction? I didn't see limitations in  https://codesandbox.io/s/data-grid-premium-forked-w904zw?file=/src/App.tsx.

**Comment by cherniavskii** [comment]
> Do we know what's missing for the row pinning + row grouping to work in conjunction? I didn't see limitations in https://codesandbox.io/s/data-grid-premium-forked-w904zw?file=/src/App.tsx.

Row grouping and pinned rows work together just fine.
The only limitation is that you cannot group pinned rows.

**Comment by oliviertassinari** [comment]
Then would this change make sense?

```diff
diff --git a/docs/data/data-grid/row-pinning/row-pinning.md b/docs/data/data-grid/row-pinning/row-pinning.md
index 5a3bc982a..7da614a28 100644
--- a/docs/data/data-grid/row-pinning/row-pinning.md
+++ b/docs/data/data-grid/row-pinning/row-pinning.md
@@ -67,7 +67,9 @@ Pinned rows do not support the following features:
 - tree data
 - row reordering
 - master detail
-  :::
+
+but you can still use these features with the rows that aren't pinned.
+:::

 ## API
```

<img width="566" alt="Screenshot 2022-11-10 at 19 47 10" src="https://user-images.githubusercontent.com/3165635/201180534-16c8f68c-2665-437d-915e-89911a13a9f5.png">

**Comment by yaredtsy** [comment]
the first cell is empty. is it intended or is it a bug?
![image](https://user-images.githubusercontent.com/34584266/201284805-f159bd56-40f3-4600-907f-c3220d2bea50.png)

shouldn't it be like this? 
![image](https://user-images.githubusercontent.com/34584266/201285205-3d4031d8-ed9b-40be-a7be-fb3a9b8a708a.png)

fix-Demo: https://codesandbox.io/s/data-grid-premium-forked-2v9g7v?file=/src/App.tsx

**Comment by cherniavskii** [comment]
> the first cell is empty. is it intended or is it a bug?

I believe this behavior is expected.
In the grouping column, you see the grouping value. And since pinned rows are not grouped, there's no grouping value for pinned rows.
So it's consistent with the rows inside row groups - they also have an empty cell instead of a value.
<img width="602" alt="Screenshot 2022-11-15 at 12 04 23" src="https://user-images.githubusercontent.com/13808724/201904405-629a5a84-dcc2-4869-a43c-4469efa52ed9.png">

You can use `groupingColDef.leafField` to [show values for the leaves](https://mui.com/x/react-data-grid/row-grouping/#show-values-for-the-leaves):
https://codesandbox.io/s/data-grid-premium-forked-yid7k8?file=/src/App.tsx

---

> shouldn't it be like this? 
![image](https://user-images.githubusercontent.com/34584266/201285205-3d4031d8-ed9b-40be-a7be-fb3a9b8a708a.png)

While it makes sense for this specific use case, what value would you expect to see there if you group rows by more than one field? Like in this example:
https://codesandbox.io/s/interesting-bose-8ejxtd?file=/demo.tsx

**Comment by yaredtsy** [comment]
> So it's consistent with the rows inside row groups - they also have an empty cell instead of a value.

but for the pinned row you can not tell to which group it belongs. does it not feel like some info is missing when it's pinned? 

> While it makes sense for this specific use case, what value would you expect to see there if you group rows by more than one field? Like in this example:

at least the first one, in this case, 'company' would be better than nothing.

**Comment by yaredtsy** [comment]
what about something like this?
```diff
--- a/packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
+++ b/packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
@@ -337,7 +337,7 @@ export const createGroupingColDefForAllGroupingCriteria = ({
         params.rowNode.type === 'footer' ||
         params.rowNode.type === 'pinnedRow'
       ) {
-        return undefined;
+        return params.row[rowGroupingModel[0]];
       }


```
and when a user clicks on the pinned row it will also scroll the main group into view.
Demo: https://codesandbox.io/s/data-grid-premium-forked-2v9g7v?file=/src/App.tsx

**Comment by yaredtsy** [comment]
Hey @cherniavskii 
what about something like this, for multiple-row groups.
[Screen Recording - Made with FlexClip (2).webm](https://user-images.githubusercontent.com/34584266/202654402-2f32f8bf-f152-46b3-819f-76953c507f44.webm)
Demo: https://codesandbox.io/s/flamboyant-swanson-gt5mbj?file=/demo.tsx

**Comment by cherniavskii** [comment]
Hey @yaredtsy 
We can create a feature request issue and see if there's a demand from the community, so we can prioritize this.
