### ISSUE TITLE
MUI Datagrid issue

### ISSUE THREAD

**Issue by akshaykn0797** [mui/mui-x#6788]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1.Install MUI data grid to your application
2.
3.

### Current behavior 😯

I am trying to use MUI datagrid in my nextJs app, But multiple undefined errors are thrown

it says theme.palette.mode not defined

![image](https://user-images.githubusercontent.com/84860331/200736073-53a7b912-e7c9-40cb-8021-492f1fc1541c.png)

### Expected behavior 🤔

All required dependencies should be installed

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Is your app wrapped into a `ThemeProvider`?

**Comment by akshaykn0797** [comment]
import '../styles/globals.css'
import { SessionProvider } from 'next-auth/react';
import { ChakraProvider } from '@chakra-ui/react'
import 'bootstrap/dist/css/bootstrap.css'
import { ProSidebarProvider } from 'react-pro-sidebar';
import Head from 'next/head';
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { CacheProvider, EmotionCache } from "@emotion/react";
import theme from "@mui/utils";




function MyApp({ Component, pageProps: { session, ...pageProps } }) {

  return (
    <SessionProvider session={session}>
      <ProSidebarProvider>
        <ChakraProvider>
        <Head>
          <title>Taste Of India</title>
        </Head>
        <ThemeProvider theme={theme}>
          <Component {...pageProps} /></ThemeProvider>
        </ChakraProvider></ProSidebarProvider>
    </SessionProvider>)
}

export default MyApp



Yeah, Its wrapped in a ThemeProvider , But I doubt if the way I import 'theme' prop is right. Additionally after I wrap the components in _ap.js file in a ThemeProvider , The error changes to this :

![image](https://user-images.githubusercontent.com/84860331/200804406-026f5a01-d0b9-4f43-a619-032a9eae644f.png)
![image](https://user-images.githubusercontent.com/84860331/200804464-a5ac6323-ba93-43da-bc90-27be22f404a8.png)

This is the first time I am using MUI , Please guide If I missed installing any packages

    "@mui/material": "^5.10.13",
    "@mui/styled-engine-sc": "^5.10.6",
    "@mui/system": "^5.10.13",
    "@mui/utils": "^5.10.9",
    "@mui/x-data-grid": "^5.17.10",
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",

**Comment by akshaykn0797** [comment]
<SessionProvider session={session}>
      <ProSidebarProvider>
        <ChakraProvider>
        <Head>
          <title>Taste Of India</title>
        </Head>
        <ThemeProvider theme={theme}>
          <Component {...pageProps} /></ThemeProvider>
        </ChakraProvider></ProSidebarProvider>
    </SessionProvider>

**Comment by alexfauquette** [comment]
That might be a wrong usage of the `theme`, I'm not sure about why you import `theme` from `@mui/utils` The [documentation](https://mui.com/material-ui/customization/theming/#theme-provider) recommend to use the `createTheme`

That does not look like a bug. Here is a codesandbox with only the data grid and the libraries indicated in the [getting started](https://mui.com/x/react-data-grid/getting-started/) and their is not error message
https://codesandbox.io/s/new-firefly-i1ipi7?file=/demo.tsx

I can only recommend you to add your wrappers progressively, to find where is the problem. For more questions about "how to debug", please refers to stackoverflow, or open an issue with a minimal reproduction of your bug
