### ISSUE TITLE
[DateTimePicker] minTime does not work

### ISSUE THREAD

**Issue by PCOffline** [mui/mui-x#6813]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-date-picker-min-time-bug-i6j360

Steps:

1. Create a DateTimePicker component with `DateFnsAdapter` and any locale
2. Attempt to set `minTime` and/or `maxTime`

### Current behavior 😯

The date picker allows you to select any time, regardless of the values in `minTime` and `maxTime`

### Expected behavior 🤔

The DatePicker should allow you to pick times within the range of `minTime` and `maxTime`

### Context 🔦

I want people to choose a time between 8 AM and 8 PM, regardless of the date. That means that any ISO date that follows the format `YYYY-MM-DDT08:00:00.000Z` to `YYYY-MM-DDT20:00:00.000Z` should be valid, and the DatePicker will not allow any other times to be selected.

Generally, the documentation about minTime and maxTime is very hard to find and the usage of `dayjs` is left unexplained. The types in the DateTimePicker API are also not explained, and the entire approach is very unintuitive. In my honest opinion, it could be simplified to a `HH:mm:ss` format or a numeric value.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Used Browser: Opera GX LVL4 (core: 91.0.4516.106)
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.105
    @mui/core-downloads-tracker:  5.10.13
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.13 => 5.10.13
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system:  5.10.13
    @mui/types:  7.2.0
    @mui/utils:  5.10.9
    @mui/x-date-pickers: ^5.0.7 => 5.0.7
    @types/react:  18.0.25
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript:  4.8.4
```
</details>

**Comment by LukasTy** [comment]
Hello @PCOffline 
Please consider using the appropriate adapter for the date you are working with.
[Here is](https://codesandbox.io/s/mui-date-picker-min-time-bug-forked-819iye?file=/src/App.js) a working example by passing the correct adapter.
