### ISSUE TITLE
[data grid] Lazy loading: colSpan and getRowClassName functions throws error at skeleton rendering, and breaks the data-grid

### ISSUE THREAD

**Issue by r-engel** [mui/mui-x#6814]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
The demo is based on the lazzy loading example [ mui.com lazy-loading](https://mui.com/x/react-data-grid/row-updates/#lazy-loading).
https://codesandbox.io/s/data-grid--skeleton-bug-u9rssh?file=/demo.js:2771-2786

Steps:
1. Open the live demo
2. Scroll the data grid to load new data
=> exception: 
MUI: GridErrorHandler - An unexpected error occurred. Error: No row with id **#auto-generated-skeleton-row-root-0** found.  Error: No row with id #auto-generated-skeleton-row-root-0 found
    at Object.eval [as getCellValue]  .....

This exception occurs if i either define a function to set the className of the row, using: getRowClassName (line 113 in the live demo), or if i define a function that sets the colSpan based on some rowdata (line 23 in the live demo) 

If you remove both of these the example works fine. 

### Current behavior 😯

The data grid breaks when its trying to access row data on skeleton rows. At least that's my interpretation of the exception.

### Expected behavior 🤔

During the skeleton rendering phase i think it's not necessary to to apply these special rendering functions as the data is not loaded, but it should not break. 
As soon the data is loaded the functions should apply as intend.

### Context 🔦

I have various kind of data that I have to render different. 
Some rows need a different background color based on row data.
Some rows have one big string field but no data other columns therefore this field should span multiple columns.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
I used Chrome.

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
  npmPackages:
    @emotion/react: ^11.7.0 => 11.7.1
    @mui/x-data-grid-generator: ^5.17.10 => 5.17.10
    @mui/x-data-grid-pro: ^5.17.10 => 5.17.10
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  17.0.39
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2

```
</details>

### Order ID 💳 (optional)

52843

**Comment by r-engel** [comment]
Hi @m4theushw,
I am sorry for being a little impatient, but when do you think there will be a fix available?

**Comment by cherniavskii** [comment]
I can no longer reproduce the issue in the latest version of the Data Grid (6.17.0): https://codesandbox.io/s/data-grid--skeleton-bug-forked-s7dtz5
