### ISSUE TITLE
[data grid] Single click editing not working

### ISSUE THREAD

**Issue by xo7397** [mui/mui-x#6843]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. After upgrading version of MUI data grid 
2. Adding new feature and console is getting an error for api.commitCellChange while trying to make single click edit functionality for the application. 
3. We're on "@mui/x-data-grid": "^5.0.0-beta.6", which is working fine for double click edit functionality.  
4. Tried with these version too 5.17.8, 5.17.9, 6.0.0-alpha.4. for single click edit functionality and Still having same issue on api.commitCellChange for above mentioned versions 
5. I'm using Google chrome with Version 107.0.5304.88 to run my application.

### Current behavior 😯

api.commitCellChange is throwing an error while upgrade of mui data grid version while adding any new features. Which is single click edit functionality After adding that feature and trying to edit the fields with single click that the error occurs for api.commitCellChange

### Expected behavior 🤔

api.commitCellChange should not throw any error if we upgrade to latest version in addition of new editing feature thru out the application 

### Context 🔦

As a user I need to edit the fields with in single click as per the functionality but I need to do double click on the filed which is not expected after upgrading this mui data grid to latest version. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by xo7397** [comment]
This the error I'm getting from console 

<img width="530" alt="image" src="https://user-images.githubusercontent.com/118190981/201699477-e1cb58a4-6ae2-49cf-830d-efdcb548bed7.png">

**Comment by cherniavskii** [comment]
Hey @xo7397 
Can you provide a minimal example reproducing the issue?
You can start with this codesandbox: https://codesandbox.io/s/14ojlc?file=/demo.tsx

**Comment by xo7397** [comment]
> The `commitCellChange` method is part of the legacy editing API. Could you try migrating to the newer API, following https://mui.com/x/react-data-grid/editing/?

I Also tried this way <DataGrid experimentalFeatures={{ newEditingApi: true }} />

**Comment by cherniavskii** [comment]
`commitCellChange` should be available in both the old and new editing API in v5.
@xo7397 We still need a reproduction example in order to proceed with your issue.

**Comment by xo7397** [comment]
import React from 'react';
import PropTypes from 'prop-types';
import NumberInput from '../../shared/components/inputs/NumberInput';

export const DataGridEditNumberCell = (props) => {
  const { id, api, field, value } = props;
  const handleChange = (event) => {
    api.setEditCellValue({ id, field, value: event.target.value }, event);
    api.commitCellChange({ id, field });
  };

  return <NumberInput name={id} value={value} onChange={handleChange} />;
};

DataGridEditNumberCell.propTypes = {
  /**
   * GridApi that let you manipulate the grid.
   */
  api: PropTypes.object.isRequired,
  /**
   * The column field of the cell that triggered the event.
   */
  field: PropTypes.string.isRequired,
  /**
   * The grid row id.
   */
  id: PropTypes.oneOfType([PropTypes.number, PropTypes.string]).isRequired,
  /**
   * The cell value, but if the column has valueGetter, use getValue.
   */
  value: PropTypes.instanceOf(Date).isRequired,
};

export default DataGridEditNumberCell;

**Comment by xo7397** [comment]
import React, { useState } from 'react';
import { Box, Grid } from '@mui/material';
import { DataGrid, GridCellModes, GridToolbar } from '@mui/x-data-grid';
import DataGridEditNumberCell from './DataGridEditNumberCell';

export const ViewGrid = () => {
  const [editRowsData, setEditRowsData] = useState({});
  const [pageSize, setPageSize] = useState(10);
  const [editedData, setEditedData] = useState({});

  const numberWithCommas = (x) => {
    return parseFloat(x)
      .toFixed(2)
      .toString()
      .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  };

  const columns = [
    {
      field: 'weeklyFund',
      headerName: 'Weekly Fund',
      width: 190,
      type: 'string',
      headerAlign: 'left',
      editable: true,
      renderCell: (params) => numberWithCommas(params.value),
      renderEditCell: DataGridEditNumberCell,
    }
  ];

  const mockData = [{ weeklyFund: 120}, {weeklyFund: 200}];
  let gridData = _.cloneDeep(mockData || []);
  Object.entries(editedData).forEach(([id, values]) => {
    const rowData = {};
    Object.entries(values).forEach(([key, { value }]) => {
      rowData[key] = value;
    });
    const index = gridData.findIndex((row) => row.id === id);
    gridData[index] = _.merge(gridData[index], rowData);
  });
  

  const handleEditRowsChange = (data) => {
    setEditRowsData(data);
    setEditedData(_.merge(editedData, data));
  };

  const [cellModesModel, setCellModesModel] = React.useState({});

  const handleCellClick = React.useCallback((params) => {
    setCellModesModel((prevModel) => {
      return {
        ...Object.keys(prevModel).reduce(
          (acc, id) => ({
            ...acc,
            [id]: Object.keys(prevModel[id]).reduce(
              (acc2, field) => ({
                ...acc2,
                [field]: { ...editRowsData[field],mode: GridCellModes.View }
              }),
              {}
            )
          }),
          {}
        ),
        [params.id]: {
          ...Object.keys(prevModel[params.id] || {}).reduce(
            (acc, field) => ({ ...acc, [field]: { ...editRowsData[field], mode: GridCellModes.View } }),
            {}
          ),
          [params.field]: { mode: GridCellModes.Edit }
        }
      };
    });
  }, [editRowsData]);

  const handleCellModesModelChange = React.useCallback((newModel) => {
    setCellModesModel(newModel);
  }, []);
  return (
    <div data-testid="view-change-fund-grid">
        <Box>
          <Grid container item xs={12} sm={12} lg={12}>
            <div
              data-testid="view-change-funds-grid"
            >
              <DataGrid
                rows={gridData}
                pageSize={pageSize}
                onPageSizeChange={setPageSize}
                rowsPerPageOptions={[5, 10]}
                columns={columns}
                columnBuffer={columns.length}
                editRowsModel={editRowsData}
                onEditRowsModelChange={handleEditRowsChange}
                rowHeight={92}
                components={{ Toolbar: GridToolbar }}
                cellModesModel={cellModesModel}
                onCellModesModelChange={handleCellModesModelChange}
                onCellClick={handleCellClick}
                experimentalFeatures={{ newEditingApi: true }}
              />
            </div>
          </Grid>
        </Box>
    </div>
  );
};

export default ViewGrid;

**Comment by xo7397** [comment]
@cherniavskii This is Minimalist code of ours. You cant try to reproduce by executing these 2 files. Here the Numbercell need to be rendered after change. But after changing error shows up on this api.commitCellChange.

**Comment by cherniavskii** [comment]
Hey @xo7397 
I've created a sandbox from the code above (without `experimentalFeatures={{ newEditingApi: true }}` flag) and I don't see any errors: https://codesandbox.io/s/divine-wildflower-rmzj6c?file=/demo.tsx
