### ISSUE TITLE
Mui tooltip with Mui datagrid row hover

### ISSUE THREAD

**Issue by vishal-kadmos** [mui/mui-x#6849]
### Order ID 💳

52198

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have a use case where we would like to show Mui Tooltip on datagrid row hover action.

I went through the documentation and the code but I didn't find any way to achieve it.
As Mui Tooltip expects children wrapped inside it and there is no way to wrap Mui datagrid row with parent element (_Mui Tooltip in this case_).

Highly appreciate if it is achievable with Tooltip component.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Output from `npx @mui/envinfo` goes here.
  
  System:
    OS: macOS 12.6
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.19.2 - ~/kadmos/customer-portal/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.5
    @emotion/styled: ^11.10.4 => 11.10.5
    @mui/base:  5.0.0-alpha.102
    @mui/core-downloads-tracker:  5.10.10
    @mui/material: ^5.10.10 => 5.10.10
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/styled-engine-sc: ^5.10.6 => 5.10.6
    @mui/system:  5.10.10
    @mui/types:  7.2.0
    @mui/utils:  5.10.9
    @mui/x-data-grid:  5.17.7
    @mui/x-data-grid-pro: ^5.17.7 => 5.17.7
    @mui/x-license-pro:  5.17.0
    @types/react: ^18.0.21 => 18.0.21
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^5.3.6 => 5.3.6
    typescript: ^4.8.4 => 4.8.4
```
</details>

**Comment by cherniavskii** [comment]
Hey @vishal-kadmos 
You can use `Row` slot to wrap the `GridRow` component with a `Tooltip`: https://codesandbox.io/s/agitated-resonance-04ib9l?file=/demo.tsx
