### ISSUE TITLE
[pickers] The `fixedWeekNumber` is not available on v5 pickers

### ISSUE THREAD

**Issue by yomnashaban** [mui/mui-x#6860]
Trying to fix number of rows shown following [6299](https://github.com/mui/mui-x/pull/6299) using `"@mui/x-date-pickers": "^5.0.8"`

```
<LocalizationProvider dateAdapter={AdapterDayjs}>
      <StaticDatePicker
        displayStaticWrapperAs="desktop"
        openTo="day"
        value={value}
        onChange={(newValue) => {
          setValue(newValue);
        }}
        renderInput={(params) => <> </>}
        showDaysOutsideCurrentMonth
        fixedWeekNumber={6}
      />
</LocalizationProvider>
```

but i'm getting `Property 'fixedWeekNumber' does not exist on type 'IntrinsicAttributes & StaticDatePickerProps<Dayjs, Dayjs> & RefAttributes<HTMLDivElement>'`

**Comment by flaviendelangle** [comment]
We are currently releasing both v5 as stable and v6 as alpha 
To use the alpha, you just need to install the `next` version in your `package.json` or a specific version 

```json
"@mui/x-date-pickers": "next",
// or
"@mui/x-date-pickers": "^6.0.0-alpha.7`
```

Note that the alpha is by definition unstable, we advise you not to use it in production for now.
The stable release should occur in Q1 2023.
