### ISSUE TITLE
[docs] Stop the Sidebar-anity!

### ISSUE THREAD

**Issue by paulhoule** [mui/mui-x#6861]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Visit https://mui.com/x/api/data-grid/data-grid-pro/ with Firefox or Edge.  Can't read the documentation because half of it is covered up with a sidebar promoting your opinion about the war in Ukraine.

![2022-11-15_15-14-21](https://user-images.githubusercontent.com/2703649/202017123-d5586d61-4334-4711-9e24-cc463b3246cc.png)

### Current behavior 😯

It's like most sites on the web.  The ads are important,  the copy is beside the point.

### Expected behavior 🤔

Sidebars **never** cover content

### Context 🔦

Read the f-n docs.  I guess I should just read the source code instead.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
> Can't read the documentation because half of it is covered up with a sidebar promoting your opinion about the war in Ukraine.

If you refer to the right side bar (where our "opinion about the war in Ukraine" is displayed), then on your screen all the items are correctly visible on screen.
Not sure to understand the problem, how would removing / moving this item help ?
