### ISSUE TITLE
Make DatePicker Header customizable / make it possible to hide the year.

### ISSUE THREAD

**Issue by itshallrun** [mui/mui-x#6880]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

For season selection, it is necessary to select a year-independent date, e.g. day and month.
We can change the input format to `dd/MM`, but it is not possible to hide the year in the DatepickerHeader.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/21173275/202237693-a4a4f572-1bb4-49c1-b034-090103aae2f5.png">

This could be solved by splitting the Month and Year into two components with different classes. Then it would be possible to hide one of both.

**Comment by flaviendelangle** [comment]
Duplicates https://github.com/mui/mui-x/issues/6653

Not sure how we will solve that one but there is definitely something to do
