### ISSUE TITLE
[question] How can I upgrade from Pro to Premium?

### ISSUE THREAD

**Issue by ekimga** [mui/mui-x#6882]
### Order ID 💳

52456

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We need to upgrade our 10 MUI X Pro license to Premium.
How can we upgrade?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by joserodolfofreitas** [comment]
Hi @ekimga,

We offer an upgrade discount based on the remaining time that your Pro license is valid.

We're sending you a coupon code to the email that purchased the license. You can use this code during [checkout](https://mui.com/store/items/mui-x-premium/) to apply your discount.

If you need further assistance on this topic, please get in touch with us at [sales@mui.com](mailto:sales@mui.com).

Thank you.
