### ISSUE TITLE
[data grid] How to set minimal/maximal row height?

### ISSUE THREAD

**Issue by konrazem** [mui/mui-x#6887]
### Order ID 💳

46820

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am not sure how I can set minimal row height. I want my rows to be dynamic height but not thiner then given value i.e 40px.

### Problem 
This is my issue. One row is too thin.
https://codesandbox.io/s/elegant-david-6u2df4?file=/demo.tsx
![1](https://user-images.githubusercontent.com/19363700/202398359-a4277196-94fb-4dc9-abab-e07c334edfd4.png)

### Solution
- I connot find how to do it in the documentation: https://mui.com/x/react-data-grid/row-height/#dynamic-row-height. 
- I am not sure what "getEstimatedRowHeight" should do.
- In getRowHeight params there is no height value given, and it would solve my problem i.e in a way: 
```javascript
getRowHeight: (params) => params.height < 40 ? 40 : 'auto'
```
- It would be nice to have prop minRowHeight and maxRowHeight

NOTE
I have houndreds of tables that alrady has (or not) renderCell prop. I want to have more generic solution.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by konrazem** [comment]
There was such issue mentioned  https://github.com/mui/mui-x/issues/5695. Solution was to set padding on MuiDataGrid-cell

**Comment by konrazem** [comment]
Of course, thank you @m4theushw, silly me. I have not thought about this solution.

**Comment by Fernichter** [comment]
Hi, @@m4theushw's solution does not work (anymore?). Is there any other workaround? 

Thanks!

**Comment by teshnizi** [comment]
This worked for me:
```tsx
 <DataGrid
        ...
        rows={rows}
        columns={columns}
        sx={{
          "& .MuiDataGrid-cell": {
            minHeight: "2rem",
          },
        }}
/>
```
