### ISSUE TITLE
DatePicker/TimePicker : renderInput is not a function

### ISSUE THREAD

**Issue by neholouis** [mui/mui-x#6889]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Hello there (general kenobi)

I want to implement the DatePicker on my app, but it seems there's a little issue :/ 

Steps:
1. Copy the code provided in the MUI X documentation
2. Refresh
4. Cry

```
import {LocalizationProvider, StaticDatePicker} from "@mui/lab";
import AdapterDayjs from "@mui/lab/AdapterDayjs";
import TextField from '@mui/material/TextField';
import {DatePicker, TimePicker} from '@mui/x-date-pickers';
import * as React from "react";
import {useState} from "react";
import {useController} from 'react-hook-form';

const DatePickerInput = ({name,label}) =>  {
    const [value,setValue] = useState(null);
    return (
        <LocalizationProvider dateAdapter={AdapterDayjs}>
            <TimePicker
                label="Basic example"
                value={value}
                onChange={(newValue) => {
                    setValue(newValue);
                }}
                renderInput={(params) => <TextField {...params} />}
            />
        </LocalizationProvider>
    );
}
```

export default DatePicker;`

### Current behavior 😯

The app crashed with the following error : 

### Expected behavior 🤔

Can I get an "amen" for the datetimepickers ?

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.0
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: Not Found
    Firefox: 105.0.1
    Safari: 16.1
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.106 
    @mui/core-downloads-tracker:  5.10.14 
    @mui/icons-material: ^5.10.3 => 5.10.14 
    @mui/lab: ^5.0.0-alpha.99 => 5.0.0-alpha.108 
    @mui/material: ^5.10.14 => 5.10.14 
    @mui/private-theming:  5.10.14 
    @mui/styled-engine:  5.10.14 
    @mui/styles: ^5.10.3 => 5.10.14 
    @mui/system:  5.10.14 
    @mui/types:  7.2.1 
    @mui/utils:  5.10.14 
    @mui/x-date-pickers: ^5.0.8 => 5.0.8 
    @types/react: ^18.0.19 => 18.0.25 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.8.3 => 4.9.3 


```
</details>

**Comment by LukasTy** [comment]
Hello @neholouis 
Could you provide a live reproduction example? You can use [this codesandbox](https://codesandbox.io/s/sgyh0f?file=/demo.tsx) as a base.

In your code example I see that you are mixing imports from both `@mui/lab` as well as `@mui/x-date-pickers`.
Do you use `@mui/lab` for anything else? We have moved pickers from `@mui/lab` quite some time ago and they are no longer maintained there, if you are not using anything else from that package—you are free to remove it from dependencies. 😉

**Comment by neholouis** [comment]
Deeply sorry...

It seems i had a typo somewhere, when i took the codesandbox, it worked... 😢 

Thanks 👍  😄
