### ISSUE TITLE
[TimePicker] Ability to change width and height of the clock

### ISSUE THREAD

**Issue by dlaskovkodar** [mui/mui-x#6897]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It would be nice to have the ability to change the height and width of the ClockPicker in the TimePicker component.
Currently, there's no such thing as making the clock smaller for instance.

### Examples 🌈

Here's one example of a smaller clock:
![image](https://user-images.githubusercontent.com/101200414/202495392-e9cd6980-7325-4cf6-9826-02e3ed608b5e.png)

### Motivation 🔦

Is there a way to accomplish the above example? Because I didn't find a way to do that. 
It would be nice if we have the option to change the overall style of the clock face.

**Comment by LukasTy** [comment]
Hello @dlaskovkodar 
I do agree that such changes are not straight-forward to do on the clock component.
I've done some tinkering around and was able to come up with [this example](https://codesandbox.io/s/divine-pine-uff2cm?file=/demo.tsx).
Would it help in solving your problem?

But do note, that we are currently working on v6 and with it our plan is to drop the clock picker on desktop mode.

**Comment by dlaskovkodar** [comment]
Hi @LukasTy, **thank you very much** for your detailed explanation on the matter.

Do you have any ideas on what would replace the current **TimePicker**? Is it some of the other non-desktop pickers available at the moment or is it going to be a whole new design?

**Comment by LukasTy** [comment]
> Do you have any ideas on what would replace the current **TimePicker**? Is it some of the other non-desktop pickers available at the moment or is it going to be a whole new design?

It will probably end up being only this https://next.mui.com/x/react-date-pickers/time-field/ behaviour on desktop for the time being, depending on how the community reacts.
But in the future we have ideas of opting for an approach more in line with other libraries and some native implementations like https://ant.design/components/time-picker

**Comment by dlaskovkodar** [comment]
Thanks for the answer. ^_^
