### ISSUE TITLE
Consider supporting non-order number based prioritized support to more easily support intermediate-based purchasing in enterprises

### ISSUE THREAD

**Issue by kkirsche** [mui/mui-x#6899]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, the way that you associate a purchaser in Github to a purchased license is via order number. In large enterprises, we often are not allowed to purchase directly from you, instead having to purchase through an intermediate in order to comply with corporate purchasing requirements. As such, enterprise customers may not actually have access to the order number in order to request the support being paid for.

I'd recommend providing a support key in addition to the license key to help facilitate to intermediates that this data is important / critical to the end user / party.

### Examples 🌈

N/A

### Motivation 🔦

Ability to request support being paid for

**Comment by kkirsche** [comment]
Course, I only realized it as we're working through purchasing, but I realized while filing #6877 that I wouldn't have the MUI order number, only the intermediate one. 

Using the same number works perfectly fine from my perspective, it's simply a matter of making sure that it's clear it's a piece of information that should be delivered to the final customer 👍  thanks for your time and consideration

**Comment by oliviertassinari** [comment]
> I realized while filing https://github.com/mui/mui-x/issues/6877 that I wouldn't have the MUI order number, only the intermediate one.

@kkirsche How did you get the license key?

**Comment by kkirsche** [comment]
> > I realized while filing https://github.com/mui/mui-x/issues/6877 that I wouldn't have the MUI order number, only the intermediate one.
> 
> 
> 
> @kkirsche I'm curious, how did you get the license key? 

I'm not 100% sure I know what aspect you are curious about, so I'll share an overview of the process as I understand it. I do not have the key in hand at this moment. 

To purchase a key we must use a third-party vendor. I'm not in front of my work machine to know which vendor, but I know we've purchased software like this before through companies like ePlus and SHI. These vendors are why allow the price to come out of the correct budget as the correct type of line item (capital or expense purchase).

Basically, we request a product, they provide an invoice, we submit a purchase order, finance cuts a check to the vendor, the vendor purchases the key from the company, the vendor prepares it for delivery to the sourcing teams which we then work with to get the product keys.

The process of getting the license key has been a quarter-long process so far. My understanding is, though I could be wrong as I know the vendor had to make a new product in their catalog for us, that the purchase order was cut, the vendor purchased the key, the key was delivered to the business, and now our team is still working with the teams on the finance side to get the actual license key delivered to us. 

I know the vendor / purchase order process this time included a lot of back and forth, so that's the area that it may have gotten stuck with the holidays.

In the end, I expect I'll be given a photo of the original invoice with a new line added which includes the license key directly below the purchased line item, which allows the vendor to do deliveries of keys from multiple vendors at once.

This is based off of my understanding as a developer not as the purchaser (that's being handled by my manager)

**Comment by oliviertassinari** [comment]
@kkirsche Thanks, awesome.

**Comment by kkirsche** [comment]
Course, we just got the key, we only got:

> Hi Name,
> Thanks for your order. Here are the license details below:
> Your MUI X Pro license key: REDACTED
>
> Development use, support, and updates expiry date: Wed Nov 29 2023
>
> Installation instructions: https://mui.com/r/x-license-key-installation
Technical support: https://mui.com/r/x-technical-support
>
>
>
> Thank you,


So we don't have an order number :(

**Comment by oliviertassinari** [comment]
@kkirsche You could extract the order ID from the license key with: https://demo.toolpad.io/deploy/clb2iwfh50004qp6vrmggzo80/pages/l436pcq.

<img width="508" alt="Screenshot 2022-11-29 at 19 01 47" src="https://user-images.githubusercontent.com/3165635/204608676-37b6aabb-7295-405b-928f-12b354923e9c.png">

cc @prakhargupta1 (I had to use the demo env, until we have a cloud)

---

@m4theushw @joserodolfofreitas Using the order ID isn't a very secure way to guarantee that the person has a valid order. A developer without a license could copy the order ID from another open GitHub issue.

In the future, maybe we should:

- make the support key a private token
- provide a form like https://issues.vuetifyjs.com/ to create issues
- in the form, ask the developer to input the support key (or use the license key, it might be enough).
- have the form create a new GitHub issue 

This way, impossible to open a support GitHub issue without a valid license. No

**Comment by kkirsche** [comment]
Thanks, @oliviertassinari. I really appreciate your time and assistance.

**Comment by oliviertassinari** [comment]
I have created an RFC https://mui-org.notion.site/RFC-MUI-X-paid-support-form-b8fa22d65bb2437c8d6beab5b7f29b5a with a possible solution to the current trust based verification. It can help once we feel that we spend more time answering illegitimate GitHub issues vs. the time it would take to make it impossible.
