### ISSUE TITLE
[data grid] How do I create rows(cells) with multiple line text?

### ISSUE THREAD

**Issue by betoab** [mui/mui-x#6901]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am wondering what the best way could be to have a two-line text in a single cell. I need to have in my table a couple of columns with two lines of text. See the image below. Each line is a different field from the database. 

### Examples 🌈

![image](https://user-images.githubusercontent.com/15186553/202505718-579b5258-9dbe-45a8-ae08-01a76e1e4531.png)

### Motivation 🔦

Is there a way to accomplish the above example? Because I didn't find a way to do that.

**Comment by cherniavskii** [comment]
Hey @betoab 
You can use `GridColDef['renderCell']` to render custom cell component: https://mui.com/x/react-data-grid/column-definition/#rendering-cells
You might also want to change the row height (52px by default): https://mui.com/x/react-data-grid/row-height/
