### ISSUE TITLE
[pickers] How to set a global timezone on the pickers with `dayjs` 

### ISSUE THREAD

**Issue by d-s-j** [mui/mui-x#6948]
### Order ID 💳

50497

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi there 👋 My team and I are currently trying to set a global timezone (UTC 00:00) for our entire React application. This is due to how the backend handles and serves dates: no times are included and is assumed to be UTC 00:00.

The expectation would be that regardless of your local timezone, a user interacting with the [DateRangePicker](https://mui.com/x/api/date-pickers/date-range-picker/) from Tokyo should see the same highlighted `today` date as a user in San Francisco, as well as any dates selected.

Current behaviour viewing from San Francisco:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/48658041/203185489-bc587e3a-33fe-4b23-b7dd-711a3c3445f2.png">

Current behaviour viewing from Tokyo:
<img width="300" alt="Screenshot 2022-11-21 at 4 30 33 PM" src="https://user-images.githubusercontent.com/48658041/203185552-5a5005cc-5429-48fc-9bdc-11e925de89c1.png">

I've provided a [codebox demo](https://codesandbox.io/s/daterangepicker-set-global-timezone-ez6ojp?file=/src/App.js) of roughly how we're attempting to accomplish this, using the `LocalizationProvider` and passing `dayjs.utc` as the instance, which I understand is what the `DateRangePicker` will base it's dates from, but this raises the `TypeError`: `Cannot read properties of undefined (reading 'en')`. Any suggestions/feedback would be appreciated 🙏

### Your environment 🌎

[Codesandbox Demo](https://codesandbox.io/s/daterangepicker-set-global-timezone-ez6ojp?file=/src/App.js)

**Comment by flaviendelangle** [comment]
```diff
```

**Comment by Semigradsky** [comment]
I have the same issue (incorrect `today` highlight) and I 'fixed' it by overriding `renderDay` for passing my calculated `today` value to `PickersDay`. But it doesn't work for `month`/`year` because we can't customize them yet - https://github.com/mui/mui-x/issues/4662
