### ISSUE TITLE
[pickers] `inputFormat` don't work properly

### ISSUE THREAD

**Issue by Chintankuma** [mui/mui-x#6967]
In DateRangePicker inputFormat Didn't Work Properly.

try inputFormat="dd/MM/yyyy" and its shows like Fr/12/yyyy

**Comment by LukasTy** [comment]
Hello @Chintankuma 
Please follow the bug creation template to provide the necessary information in order for us to help you.

At the very least—we need a minimal reproduction sample which you can build by starting [with this](https://codesandbox.io/s/rt16np?file=/demo.tsx).

**Comment by flaviendelangle** [comment]
If you are using `dayjs`, `dd` is the name of the week day so it is the expected behavior (see https://day.js.org/docs/en/display/format)
You probably want to use `DD` instead.

If you are using another library, it would indeed be easier with a reproduction case to see which one.
