### ISSUE TITLE
[data grid] GridActionsCellItem last version of @mui/x-data-grid so '5.17.12' has some problems with props

### ISSUE THREAD

**Issue by Dani-dema** [mui/mui-x#6978]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. install the latest version of @mui/x-data-grid so '5.17.12'
2.Create some colums and one of them create type:'actions'
{
        field: 'actions',
        type: 'actions',
        width: 80,
        getActions: (params) => [
          <GridActionsCellItem
            icon={<DeleteIcon />}
            label="Delete"
            onClick={deleteUser(params.id)}
            showInMenu
          />,

],
}
3.

### Current behavior 😯

Expect to run the DataGrid with actions buttons.

### Expected behavior 🤔

Type '{ icon: Element; label: string; onClick: () => void; showInMenu: true; }' is missing the following properties from type 'Pick<{ label: string; icon?: ReactElement<any, string | JSXElementConstructor> | undefined; } & { showInMenu: true; } & { autoFocus?: boolean | undefined; ... 6 more ...; sx?: SxProps<...> | undefined; } & Omit<...> & CommonProps & Omit<...>, "label" | ... 276 more ... | "divider">': nonce, onResize, onResizeCapture .

### Context 🔦

import * as React from 'react';
import {
  DataGrid,
  GridActionsCellItem,
  GridRowId,
  GridColumns,
} from '@mui/x-data-grid';
import DeleteIcon from '@mui/icons-material/Delete';
import SecurityIcon from '@mui/icons-material/Security';
import FileCopyIcon from '@mui/icons-material/FileCopy';
import { randomCreatedDate, randomUpdatedDate } from '@mui/x-data-grid-generator';

const initialRows = [
  {
    id: 1,
    name: 'Damien',
    age: 25,
    dateCreated: randomCreatedDate(),
    lastLogin: randomUpdatedDate(),
    isAdmin: true,
    country: 'Spain',
    discount: '',
  },
  {
    id: 2,
    name: 'Nicolas',
    age: 36,
    dateCreated: randomCreatedDate(),
    lastLogin: randomUpdatedDate(),
    isAdmin: false,
    country: 'France',
    discount: '',
  },
  {
    id: 3,
    name: 'Kate',
    age: 19,
    dateCreated: randomCreatedDate(),
    lastLogin: randomUpdatedDate(),
    isAdmin: false,
    country: 'Brazil',
    discount: 'junior',
  },
];

type Row = typeof initialRows[number];

export default function ColumnTypesGrid() {
  const [rows, setRows] = React.useState<Row[]>(initialRows);

  const deleteUser = React.useCallback(
    (id: GridRowId) => () => {
      setTimeout(() => {
        setRows((prevRows) => prevRows.filter((row) => row.id !== id));
      });
    },
    [],
  );

  const toggleAdmin = React.useCallback(
    (id: GridRowId) => () => {
      setRows((prevRows) =>
        prevRows.map((row) =>
          row.id === id ? { ...row, isAdmin: !row.isAdmin } : row,
        ),
      );
    },
    [],
  );

  const duplicateUser = React.useCallback(
    (id: GridRowId) => () => {
      setRows((prevRows) => {
        const rowToDuplicate = prevRows.find((row) => row.id === id)!;
        return [...prevRows, { ...rowToDuplicate, id: Date.now() }];
      });
    },
    [],
  );

  const columns = React.useMemo<GridColumns<Row>>(
    () => [
      { field: 'name', type: 'string' },
      { field: 'age', type: 'number' },
      { field: 'dateCreated', type: 'date', width: 130 },
      { field: 'lastLogin', type: 'dateTime', width: 180 },
      { field: 'isAdmin', type: 'boolean', width: 120 },
      {
        field: 'country',
        type: 'singleSelect',
        width: 120,
        valueOptions: [
          'Bulgaria',
          'Netherlands',
          'France',
          'United Kingdom',
          'Spain',
          'Brazil',
        ],
      },
      {
        field: 'discount',
        type: 'singleSelect',
        width: 120,
        editable: true,
        valueOptions: ({ row }) => {
          if (row === undefined) {
            return ['EU-resident', 'junior'];
          }
          const options: string[] = [];
          if (!['United Kingdom', 'Brazil'].includes(row.country)) {
            options.push('EU-resident');
          }
          if (row.age < 27) {
            options.push('junior');
          }
          return options;
        },
      },
      {
        field: 'actions',
        type: 'actions',
        width: 80,
        getActions: (params) => [
          <GridActionsCellItem
            icon={<DeleteIcon />}
            label="Delete"
            onClick={deleteUser(params.id)}
            showInMenu
          />,
          <GridActionsCellItem
            icon={<SecurityIcon />}
            label="Toggle Admin"
            onClick={toggleAdmin(params.id)}
            showInMenu
          />,
          <GridActionsCellItem
            icon={<FileCopyIcon />}
            label="Duplicate User"
            onClick={duplicateUser(params.id)}
            showInMenu
          />,
        ],
      },
    ],
    [deleteUser, toggleAdmin, duplicateUser],
  );

  return (
    <div style={{ height: 300, width: '100%' }}>
      <DataGrid columns={columns} rows={rows} />
    </div>
  );
}

### Your environment 🌎

browser: Chrome
@mui/x-data-grid: 5.17.12

**Comment by Dani-dema** [comment]
> I copy-pasted the code provided in a [CodeSandbox](https://codesandbox.io/s/recursing-meitner-v83092?file=/demo.tsx) and I didn't see any error. Could you provide a live example?

Please can you try the latest version of @mui/x-data-grid

**Comment by Dani-dema** [comment]
![image](https://user-images.githubusercontent.com/67050351/203866580-297c0de8-0471-4843-8b12-c641c9ce9254.png)

Also here is my [CodeSandBox](https://codesandbox.io/s/keen-blackwell-c5ti60?file=/src/App.tsx):

**Comment by Dani-dema** [comment]
I have the last version which is 18.0.25

**Comment by Dani-dema** [comment]
@m4theushw  yeah when i update that version works fine. Thanks

**Comment by chrishawn** [comment]
I'm seeing the same... deleted node_modules reinstalled... same behavior
if I roll back data-grid to 5.16.0 it goes away

```  "react": "^17.0.2",
    "react-dom": "^17.0.2",    
    "@types/react": "^17.0.52",
    "@types/react-dom": "^17.0.18",
    "@mui/x-data-grid-premium": "^5.17.14",
    
    
Type '{}' is missing the following properties from type 'Pick<ButtonProps<"button", {}>, "form" | "slot" | "title" | "children" | "href" | keyof CommonProps | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 277 more ... | "onResizeCapture">': onResize, onResizeCapture

**Comment by chrishawn** [comment]
specifically the causing code is the custom toolbar
```
		<GridToolbarContainer>
			<GridToolbarColumnsButton/>
			<GridToolbarFilterButton/>
		</GridToolbarContainer>
