### ISSUE TITLE
[DateRangePicker] Strange selected days highlighting with `showDaysOutsideCurrentMonth`

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#6982]
### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/amazing-mendeleev-j1tyyw?file=/demo.tsx

Steps:
1. set `showDaysOutsideCurrentMonth`
2. select date range spanning two months

### Current behavior 😯

The selected days outside of current month are not highlighted correctly.

![Screenshot 2022-11-24 at 10 52 00](https://user-images.githubusercontent.com/4941090/203736447-fef2074e-9dd1-4f79-bc21-8e6af171a5eb.png)

### Expected behavior 🤔

The selected days outside of current month should receive a "stable" highlighting style.
Either:
- mimic same style from the other month (in the above examples case—provide highlighting style to day 31 in November calendar)
- have only one start and end marker in calendars (both 30 and 31 days in November calendar would receive generic highlighting style)

**Comment by flaviendelangle** [comment]
I think nobody had the multiple calendar in mind when adding `showDaysOutsideCurrentMonth` :grimacing: 

An easy fix should be to remove this prop from the range pickers.

**Comment by LukasTy** [comment]
I would agree that it does not make much sense in case of 2 calendars, but if only one is present (mobile)? 🤔

**Comment by flaviendelangle** [comment]
We could keep the prop and ignore it if `calendars > 1` (and update the JSDoc of course)
Even on desktop we can only show 1 calendar if we want, so we can't remove it from it either if we keep it on mobile.

Both can make sense
