### ISSUE TITLE
[pickers] Localization doesn't work

### ISSUE THREAD

**Issue by niklasarnitz** [mui/mui-x#6988]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Use the following component inside of a [react-hook-form](https://react-hook-form.com/)
```typescript
import {TextField} from '@mui/material';
import {DatePicker, LocalizationProvider} from '@mui/x-date-pickers';
import React from 'react';
import {AdapterMoment} from '@mui/x-date-pickers/AdapterMoment';

export type LocalizedDatePickerFormFieldProps = {
    field: any;
    label: string;
}

export const LocalizedDatePickerFormField = React.memo(
	(
		{
			field,
			label,
		}: LocalizedDatePickerFormFieldProps,
	) => {
		return <LocalizationProvider dateAdapter={AdapterMoment} adapterLocale='de'>
			<DatePicker
				label={label}
				renderInput={(params) =>
					<TextField
						{...params}
					/>
				}
				{...field}
			/>
		</LocalizationProvider>;
	});
```
2. View that form
![Screenshot 2022-11-24 at 12 46 09](https://user-images.githubusercontent.com/24507162/203776861-b16bc104-e94b-468e-a518-b8e84ad4c633.png)

### Current behavior 😯

The date is formatted as 'MM/DD/YYYY'.

### Expected behavior 🤔

The date should be formatted 'DD.MM.YYYY' as per the german locale.

### Context 🔦

I'm trying to implement a date picker inside of a react-hook-form.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

System:
    OS: macOS 11.6.1
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/dev/kassenbuch/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: Not Found
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.106 
    @mui/core-downloads-tracker:  5.10.14 
    @mui/icons-material: ^5.10.9 => 5.10.9 
    @mui/material: ^5.10.14 => 5.10.14 
    @mui/private-theming:  5.10.14 
    @mui/styled-engine:  5.10.14 
    @mui/system:  5.10.14 
    @mui/types:  7.2.1 
    @mui/utils:  5.10.14 
    @mui/x-data-grid: ^5.17.8 => 5.17.8 
    @mui/x-date-pickers: ^5.0.8 => 5.0.8 
    @types/react: ^18.0.21 => 18.0.21 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.6 => 5.3.6 
    typescript: ^4.8.4 => 4.8.4 
</details>

I used Chrome and Firefox.

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by LukasTy** [comment]
Adding the below line fixes your problem.
```tsx
import 'moment/locale/de';
```

**Comment by niklasarnitz** [comment]
Thank you. That did it.
It would propably nice to add that part to the documentation.

**Comment by LukasTy** [comment]
Glad to hear it. We [are working on it](https://github.com/mui/mui-x/pull/6625)—the docs will receive a huge overhaul with v6 (next). 😉

**Comment by LukasTy** [comment]
By the way, you might need to add `moment.locale('de)` call somewhere in your app if you still don't have it, otherwise you might encounter certain cases where localisation would work incorrectly.
It's [mentioned here](https://deploy-preview-6625--material-ui-x.netlify.app/x/react-date-pickers/adapters-locale/#with-moment).
