### ISSUE TITLE
Incorrect Year population (x-date-pickers-pro)

### ISSUE THREAD

**Issue by cosmictoby** [mui/mui-x#6996]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/date-picker-issue-j91q5j

Steps:
1. Start typing a date such as 03/05/2025
2. Year component will instantly autocorrect to the incorrect value. 

![2022-11-25_13-29-11](https://user-images.githubusercontent.com/83679486/203888402-13222f68-b344-4701-a25c-d02a87f8b0ce.gif)

### Current behavior 😯

Year component will instantly autocorrect to the incorrect value. 

### Expected behavior 🤔

The user should have the ability to enter the year instead of being forced into a state of having the incorrect year.

### Context 🔦

I might have stuffed something up with the configuration of the moment adapter, I'm not sure. It just feels a little strange. Any help would be greatly appreciated.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.107 
    @mui/core-downloads-tracker:  5.10.15 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/lab: ^5.0.0-alpha.109 => 5.0.0-alpha.109 
    @mui/material: ^5.10.15 => 5.10.15 
    @mui/private-theming:  5.10.15 
    @mui/styled-engine:  5.10.14 
    @mui/styles: ^5.10.15 => 5.10.15 
    @mui/system:  5.10.15 
    @mui/types:  7.2.1 
    @mui/utils:  5.10.15 
    @mui/x-date-pickers:  5.0.9 
    @mui/x-date-pickers-pro: ^5.0.9 => 5.0.9 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react: ^17.0.33 => 17.0.43 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.7.3 => 4.7.3 
```
</details>

### Order ID 💳 (optional)

54996

**Comment by LukasTy** [comment]
Hello @cosmictoby 
Please use correct tokens for `inputFormat` as per used [date library](https://momentjs.com/docs/#/displaying/format/).

Applying the following change to your example fixes the issue:
```diff
-inputFormat="DD/MM/yyyy"
+inputFormat="DD/MM/YYYY"
```
