### ISSUE TITLE
Can MUI TablePagination be used as the CustomizedPagination for the MUI DataGrid Premium??

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#7033]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Basically I am trying to achieve a particular design for the DataGrid I need to make - 
**
![image](https://user-images.githubusercontent.com/109504204/204357979-6e4de9e2-b380-4513-9f27-e494c02dafbc.png)
**

I have tried using the **TablePagination** like in the following sandbox but I am getting really confused as to how the props need to be mapped. Also maybe something is wrong with my **onPageChange** 

CodeSandbox Link - https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-wfb9rm?file=/demo.tsx:3212-3236

I am thinking there is no prop as **rowsPerPage** in **MUI DataGrid** but its is one of the required prop in **MUI TablePagination** also the **onPageChange** doesn't seem to work correctly for some reason

Is this even possible to do so??
FYI - I have the **premium** version of MUI-X can I use the **apiRef** to get a particular value correctly??

### Examples 🌈

Reproduction Link - https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-wfb9rm?file=/demo.tsx:3212-3236

**Comment by noobDev31** [comment]
I think there is some issue with the way its done in the **DataGridPremium** props that it always shows - 
**Total Rows: 20** or maybe I am missing something - 

I made it work with the community version of MUI-X - 

https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-zg7f0o?file=/demo.tsx:5049-5090

But in my codebase with the premium version its somehow not working - 

https://codesandbox.io/s/datagriddemo-demo-mui-x-forked-wfb9rm?file=/index.tsx

**Comment by yaredtsy** [comment]
Hey @noobDev31 
you forgot to add `pagination`, you need to set `pagination` to true to enable pagination on the premium version.
```jsx
<DataGridPremium
   ...
   pagination
/>
```

**Comment by noobDev31** [comment]
Hi @yaredtsy  
I did add it 

![image](https://user-images.githubusercontent.com/109504204/204542895-254b5e39-e582-4811-90da-acdf000a810d.png)

**Comment by yaredtsy** [comment]
i think there is a problem with `paginationMode`

**Comment by noobDev31** [comment]
You know even when I am doing a **paginationMode="client"** and the **rowsPerPageOptions** doesn't work

**Comment by yaredtsy** [comment]
use ` paginationMode={paginationMode ?? "client"}`

**Comment by yaredtsy** [comment]
> If I give pageSize, i need to make a state and add an onPageSizeChange in the index.tsx file??

you can use  `pageSize={localPageSize}` since you initialized it with `pageSize`  when you create the state you do not need do `pageSize={pageSize?? localPageSize}`

**Comment by noobDev31** [comment]
Thanks a lot @yaredtsy
