### ISSUE TITLE
[pickers] Type 'AdapterDateFns' is missing the following properties from type

### ISSUE THREAD

**Issue by drastiK91** [mui/mui-x#7050]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

hello, i'm facing an issue once implemented LocalizationProvider,
according to the docs i import:

import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";

```
function App() {
...
 <LocalizationProvider dateAdapter={AdapterDateFns}>
   //  stuff
</LocalizationProvider>
...
```

### Current behavior 😯

Failed to compile.

/home/v14gr4/proj/test_app/src/App.tsx
TypeScript error in /home/v14gr4/proj/test_app/src/App.tsx(47,35):
Types of construct signatures are incompatible.
  Type 'new ({ locale, formats, }?: { formats?: Partial<DateIOFormats<string>> | undefined; locale?: Locale | undefined; } | undefined) => AdapterDateFns' is not assignable to type 'new (...args: any) => MuiPickersAdapter<unknown>'.
    Type 'AdapterDateFns' is missing the following properties from type 'IUtils<unknown>': getDate, setDate  TS2419

             <Provider store={store}>
               <ApiProvider>
               <LocalizationProvider dateAdapter={AdapterDateFns}>
                                          ^
                   <MuiThemeProvider theme={createTheme(theme)}>
                     <LayoutProvider>
                       <SnackbarProvider maxSnack={3}>

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.0 Fedora Linux 36 (Workstation Edition)
  Binaries:
    Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.71
    Firefox: 107.0
  npmPackages:
    @emotion/react: 11.9.3 => 11.9.3 
    @emotion/styled: 11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.98 
    @mui/icons-material: 5.8.4 => 5.8.4 
    @mui/lab: 5.0.0-alpha.100 => 5.0.0-alpha.100 
    @mui/material: 5.9.3 => 5.9.3 
    @mui/private-theming:  5.10.15 
    @mui/styled-engine:  5.10.14 
    @mui/styles: 5.9.3 => 5.9.3 
    @mui/system: 5.9.3 => 5.9.3 
    @mui/types:  7.2.1 
    @mui/utils:  5.10.15 
    @mui/x-data-grid: 5.12.3 => 5.12.3 
    @mui/x-date-pickers: ^5.0.0-alpha.7 => 5.0.9 
    @types/react: 17.0.47 => 17.0.47 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.4.4 => 4.4.4 

```
</details>

**Comment by LukasTy** [comment]
Hello @drastiK91 
Thank you for creating this issue.
Could you provide a working example for us to check?
You can use [this codesandbox](https://codesandbox.io/s/hidden-night-1z9z0c?file=/demo.tsx) as a base for you example.

**Comment by johnflux** [comment]
I had this exact error when I still had the old

`import DateAdapter from '@mui/lab/AdapterDateFns';`
which I had to change to:

`import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';`
