### ISSUE TITLE
[docs] Document the need for `WrapperVariantContext`

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#7064]
### Problem

Certain pickers components expect `React.useContext(WrapperVariantContext)` to exist in the parent scope.
Some of these components might end up being used standalone and would not behave as expected if the mentioned context is not provided.

### Suggestion
Add a warning/info section (preferably in API docs page) mentioning that this component expects `WrapperVariantContext` to be provided if used standalone for components having this dependency.

**Comment by flaviendelangle** [comment]
`WrapperVariantContext` is private API
If we have a public component that expect a parent `WrapperVariantContext`, I think we should modify the behavior to remove this requirement.
Either by adding a prop similar to the `displayStaticWrapperAs` prop or by having a decent fallback on the components themselves.

Which components do you have in mind ?

**Comment by LukasTy** [comment]
> Which components do you have in mind ?

- Clock
- YearCalendar
- DateRangeCalendar

They seem like possible candidates that could be used standalone by someone. 🤔

**Comment by flaviendelangle** [comment]
`Clock` is not public
Could be at some point, but not currently

For `YearCalendar` and `DateRangeCalendar` they are public so we clearly need to make sure the behavior is correct.

**Comment by flaviendelangle** [comment]
Super-seeded by https://github.com/mui/mui-x/issues/7372
