### ISSUE TITLE
[docs] Column types: native column types missing one

### ISSUE THREAD

**Issue by elmirmahmudev** [mui/mui-x#7088]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-data-grid/column-definition/#column-types

### Kind of issue

Missing information

### Issue description

Column types: native column types missing one "action". Naming column field as "action" caused issue for me while positioning master detail icon column. Please provide this also in the list.

**Comment by cherniavskii** [comment]
Hey @elmirmahmudev 

> native column types missing one "action"

There's no column type called "action". There's an "actions" column type though and it is already included in the list.

> Naming column field as "action" caused issue for me while positioning master detail icon column.

You shouldn't need to change the column field when customizing the detail panel toggle column. See this demo: https://mui.com/x/react-data-grid/master-detail/#customizing-the-detail-panel-toggle

Let me know if I'm missing something, and please provide a reproduction example if you experience unexpected behavior.
Thanks!

**Comment by elmirmahmudev** [comment]
Hi @cherniavskii . Thanks for replying. 
We can reproduce it by naming one column fieldName as "action" and it will move master detail toggle column to the end of the grid. It took time to realize. Hope it's clear. Thanks!

**Comment by cherniavskii** [comment]
@elmirmahmudev I can't reproduce it with this demo: https://codesandbox.io/s/gracious-tamas-pw6uro?file=/demo.tsx
Can you provide a reproduction example? Thanks!
