### ISSUE TITLE
[data grid] About rowChange event

### ISSUE THREAD

**Issue by atillaaliyev** [mui/mui-x#7089]
### Order ID 💳

49721

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi,
I created library based on MUI/X and MUI. And I have a problem for DataGrid server pagination.
I added **useFetchTable**  hook and I binded it with gridApiRef and lazyQuery from RTK.

```
import { gridPageCountSelector, useGridSelector } from '@mui/x-data-grid-premium'
import { QueryDefinition } from '@reduxjs/toolkit/dist/query'
import { UseLazyQuery } from '@reduxjs/toolkit/dist/query/react/buildHooks'
import { RefObject, useCallback, useEffect, useState } from 'react'
import { DataGridRef } from '../components'
import { useMessage } from '../message'

type UseFetchTableOptions = {
  fetchAll?: boolean
  initialPageSize?: number
  initialRowData?: unknown
  preProcessResponse?: (data: unknown) => unknown
}

export const useFetchTable = <QueryArg,>(
  gridApiRef: RefObject<DataGridRef>,
  lazyQuery: unknown,
  key: string,
  options: UseFetchTableOptions,
) => {
  const { fetchAll = false, initialPageSize = 3, preProcessResponse, initialRowData = [] } = options
  const [trigger] = (
    lazyQuery as UseLazyQuery<
      QueryDefinition<Partial<QueryArg>, never, '', { data: unknown; next: boolean }, 'api'>
    >
  )()

  const [next, setNext] = useState(false)
  const [serverPage, setServerPage] = useState(1)
  const [pageCount, setPageCount] = useState(0)
  const [pageSize, setPageSize] = useState(gridApiRef.current?.pagination.getPageCount())
  const [page, setPage] = useState(0)
  const [args, setArgs] = useState<Partial<QueryArg>>()
  const [preferCacheValue, setPreferCacheValue] = useState(false)
  const { showMessage } = useMessage()

  const refetch = useCallback(() => {
    if (!gridApiRef) throw new Error('Grid ref boş olamaz.')
    if (!trigger) throw new Error('Trigger boş olamaz.')
    gridApiRef.current.pagination.setLoading(true)
    trigger({ ...args, [key]: serverPage }, preferCacheValue)
      .unwrap()
      .then((response) => {
        gridApiRef.current.pagination.setLoading(false)
        if (!Object.prototype.hasOwnProperty.call(response, 'data', 'next'))
          throw new Error("Trigger'ı için uyumsuz object tipi.(Beklenen: data ve next )")

        const { data, next } = response
        setServerPage((prev) => prev + 1)
        setNext(Boolean(next))
        if (preProcessResponse) {
          gridApiRef.current.row.addRows(
            [...((preProcessResponse(data) as Array<unknown>) ?? [])],
            false,
          )
        } else {
          gridApiRef.current.row.addRows([...((data as Array<unknown>) ?? [])], true)
        }
      })
      .catch(({ message, transactionId }) => {
        setServerPage((prev) => prev - 1)
        gridApiRef.current.pagination.setLoading(false)
        showMessage(
          `Veri getirme esnasında bir hata oluştu: ${message} (Transaction Id: ${transactionId})`,
        )
      })
  }, [args, key, next, preferCacheValue, preProcessResponse, serverPage, trigger])
  
  const fetch = useCallback(
    (args: Partial<QueryArg> = {}, preferCacheValue = false) => {
      if (!gridApiRef) throw new Error('Grid ref boş olamaz.')
      if (!trigger) throw new Error('Trigger boş olamaz.')
      gridApiRef.current.row.deleteRows()
      gridApiRef.current.pagination.resetPage()
      gridApiRef.current.pagination.setLoading(true)
      setServerPage(1)
      setArgs({ ...args })
      setPreferCacheValue(preferCacheValue)
      trigger({ ...args, [key]: 1 }, preferCacheValue)
        .unwrap()
        .then((response) => {
          gridApiRef.current.pagination.setLoading(false)
          if (!Object.prototype.hasOwnProperty.call(response, 'data', 'next'))
            throw new Error("Trigger'ı için uyumsuz object tipi.(Beklenen: data ve next )")

          const { data, next } = response
          setServerPage((prev) => prev + 1)
          setNext(Boolean(next))
          if (preProcessResponse) {
            gridApiRef.current.row.addRows(
              [...((preProcessResponse(data) as Array<unknown>) ?? [])],
              false,
            )
          } else {
            gridApiRef.current.row.addRows([...((data as Array<unknown>) ?? [])], true)
          }
        })
        .catch(({ message, transactionId }) => {
          gridApiRef.current.pagination.setLoading(false)
          showMessage(
            `Veri getirme esnasında bir hata oluştu: ${message} (Transaction Id: ${transactionId})`,
          )
        })
    },
    [key, trigger, preProcessResponse],
  )

  useEffect(() => {
    gridApiRef.current?.subscribeEvent('pageChange', (params: number) => setPage(params))
    gridApiRef.current?.subscribeEvent('pageSizeChange', (params) => {
      setPageSize(params)
      gridApiRef.current.pagination.resetPage()
    })
  }, [gridApiRef])

  /**
   *  If page or page count change, do last page control.
   *  If it's last page, do refetch.
   */
  useEffect(() => {
    const isLastPage = pageCount - 1 === page
    if (next && (isLastPage || serverPage <= initialPageSize || fetchAll)) refetch()
  }, [page, pageCount])

  /**
   * If row data change (add,delete), pageCount change.
   */
  useEffect(() => {
    if (gridApiRef.current.row.getRows().length > 0) {
      const newPageCount = Math.ceil(gridApiRef.current.row.getRows().length / pageSize)
      setPageCount(newPageCount)
    } else {
      setPageCount(0)
    }
  }, [gridApiRef.current?.row.getRows, pageSize])

  useEffect(() => {
    gridApiRef.current.row.addRows([...((initialRowData as Array<unknown>) ?? [])], false)
  }, [])

  return { fetch, serverPage }
}

```

I have problem "If row data change (add,delete), pageCount change.". I want to listen row change event but I didn't find there: https://mui.com/x/react-data-grid/events/

Because for example, I have 250 record and page size is 50. page count is 5. If someone would add record anywhere, page count will be 6. I should listen it and if the cursor page is 6 , I should refetch, But i couldn't catch.

We have any solution or event about this?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @atillaaliyev 

> I have problem "If row data change (add,delete), pageCount change.". I want to listen row change event but I didn't find there: [mui.com/x/react-data-grid/events](https://mui.com/x/react-data-grid/events/)

So you want to be notified that the user removed or added a new row, right?
I suppose there's some UI element that allows performing that action, so you can use it as a source of row addition/removal events, right?

**Comment by yaredtsy** [comment]
I have been using `rowsSet` event to detect if the rows are changed. it has not been included in the documentation, I found it going throw the code.

https://github.com/mui/mui-x/blob/a6c96b35cf09d9f7132774197fad480cd9bf90fc/packages/grid/x-data-grid/src/models/events/gridEventLookup.ts#L380-L385

**Comment by atillaaliyev** [comment]
> Hey @atillaaliyev
> 
> > I have problem "If row data change (add,delete), pageCount change.". I want to listen row change event but I didn't find there: [mui.com/x/react-data-grid/events](https://mui.com/x/react-data-grid/events/)
> 
> So you want to be notified that the user removed or added a new row, right? I suppose there's some UI element that allows performing that action, so you can use it as a source of row addition/removal events, right?

@cherniavskii Yes of course, but i don't want to use source it :) Api ref should be enough for me. Otherwise, of course, I can pass parameter when rows are added or removed by users.

Frankly, I need to page count change listener, End of day I'm using row data for finding page count. I noticed `gridPageCountSelector` while coded custom pagination. Maybe listening page count change event is easier than other. I have already listened page size and page.



>I have been using rowsSet event to detect if the rows are changed. it has not been included in the documentation, I found it 
>going throw the code.

@yaredtsy Thank you for solution, I looked source code  before  and tried it, It didn't work some cases. 
 @m4theushw Did I understand right, rowset event listener is wrong for this case?

**Comment by cherniavskii** [comment]
> for example, I have 250 record and page size is 50. page count is 5. If someone would add record anywhere, page count will be 6. I should listen it and if the cursor page is 6 , I should refetch, But i couldn't catch.

I assume you are using cursor server-side pagination, is it correct?
When a new record is added to the grid, you have to reflect it in the `rowCount` prop change.
After the `rowCount` change the pagination will update accordingly.

What exactly do you want refetch after the rowCount change?
