### ISSUE TITLE
[data grid] Wrong types in the GridActionsCellItem props

### ISSUE THREAD

**Issue by senseibarni** [mui/mui-x#7090]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Nothing special is needed. Just use GridActionsCellItem like in the docs:
https://mui.com/x/react-data-grid/column-definition/#special-properties

### Current behavior 😯

TypeScript error:
Type '{ icon: Element; label: string; onClick: () => void; showInMenu: true; }' is not assignable to type 'IntrinsicAttributes & ((Pick<{ label: string; icon?: ReactElement<any, string | JSXElementConstructor<any>> | undefined; } & ... 4 more ... & Omit<...>, "type" | ... 283 more ... | "showInMenu"> | Pick<...>) & RefAttributes<...>)'.
  Type '{ icon: Element; label: string; onClick: () => void; showInMenu: true; }' is missing the following properties from type 'Pick<{ label: string; icon?: ReactElement<any, string | JSXElementConstructor<any>> | undefined; } & { showInMenu: true; } & { autoFocus?: boolean | undefined; ... 6 more ...; sx?: SxProps<...> | undefined; } & Omit<...> & CommonProps & Omit<...>, "key" | ... 276 more ... | "showInMenu">': nonce, onResize, onResizeCapture ts(2322)

Adding 3 props: nonce, onResize, onResizeCapture helps.

### Expected behavior 🤔

No TypeScript error

### Context 🔦

Error appeared after updating to the newest version: 5.17.14.
Is present also in 5.17.13, 5.17.12
5.17.11 seems to be OK.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.62)
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4
    @emotion/styled: 11.10.4 => 11.10.4
    @mui/base:  5.0.0-alpha.92
    @mui/core-downloads-tracker:  5.10.16
    @mui/icons-material: ^5.10.15 => 5.10.15
    @mui/lab: ^5.0.0-alpha.87 => 5.0.0-alpha.94
    @mui/material: ^5.10.16 => 5.10.16
    @mui/private-theming:  5.10.16
    @mui/styled-engine:  5.10.16
    @mui/system: ^5.10.16 => 5.10.16
    @mui/types:  7.2.2
    @mui/utils:  5.10.16
    @mui/x-data-grid-pro: ^5.17.14 => 5.17.14
    @mui/x-date-pickers: ^5.0.7 => 5.0.7
    @mui/x-license-pro:  5.17.11
    @types/react: 18.0.20 => 18.0.20
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```
</details>

**Comment by jbaccarelli-equinix** [comment]
Similar issues are happening for the following components:

GridToolbarFilterButton
GridToolbarColumnsButton
GridToolbarDensitySelector
Popper
GridToolbarExportContainer
