### ISSUE TITLE
[DataGrid] `getCellElement` does not work with `pinnedColumns`.

### ISSUE THREAD

**Issue by yaredtsy** [mui/mui-x#7093]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/zen-benz-e7bky2?file=/demo.tsx

Steps:
1. click on one of the cells that are not in the pinned column section.
2. click on `print active element` button.
3. check the log, its logging null

### Current behavior 😯

`getCellElement` is returning null when I use it with `pinnedColumns`. 

### Expected behavior 🤔

it should return an HTML element.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Thanks @yaredtsy

Given that the row is rendered by multiple DOM elements when using pinned columns, we should use a combined query selector rather than two separate selectors when querying the DOM node:
```diff
diff --git a/packages/grid/x-data-grid/src/utils/domUtils.ts b/packages/grid/x-data-grid/src/utils/domUtils.ts
index d27463a..1357bff 100644
--- a/packages/grid/x-data-grid/src/utils/domUtils.ts
+++ b/packages/grid/x-data-grid/src/utils/domUtils.ts
@@ -35,18 +35,18 @@ export function getGridColumnHeaderElement(root: Element, field: string) {
   );
 }
 
+function getGridRowElementSelector(id: GridRowId): string {
+  return `.${gridClasses.row}[data-id="${escapeOperandAttributeSelector(String(id))}"]`;
+}
+
 export function getGridRowElement(root: Element, id: GridRowId) {
-  return root.querySelector<HTMLDivElement>(
-    `.${gridClasses.row}[data-id="${escapeOperandAttributeSelector(String(id))}"]`,
-  );
+  return root.querySelector<HTMLDivElement>(getGridRowElementSelector(id));
 }
 
 export function getGridCellElement(root: Element, { id, field }: { id: GridRowId; field: string }) {
-  const row = getGridRowElement(root, id);
-  if (!row) {
-    return null;
-  }
-  return row.querySelector<HTMLDivElement>(
-    `.${gridClasses.cell}[data-field="${escapeOperandAttributeSelector(field)}"]`,
-  );
+  const rowSelector = getGridRowElementSelector(id);
+  const cellSelector = `.${gridClasses.cell}[data-field="${escapeOperandAttributeSelector(
+    field,
+  )}"]`;
+  return root.querySelector<HTMLDivElement>(`${rowSelector} ${cellSelector}`);
 }

```

**Comment by yaredtsy** [comment]
do you mean something like this? https://codesandbox.io/s/zen-benz-e7bky2?file=/demo.tsx. `apiRef.current.getGridCellElement` is returning null.

**Comment by yaredtsy** [comment]
it's returning the first element when I change the order of age and email column it's returning the first element that comes first. could this be solved by generating a unique id every time a Datagrid is created. and store it in `row` and `cell` elements like `data-parentId`.

**Comment by cherniavskii** [comment]
Right, we can exclude elements from nested grids with something like this:

```tsx
const selector = `${rowSelector} ${cellSelector}`;
return root.querySelector(`${selectorQuery}:not(${gridClasses.root} ${gridClasses.root} ${selectorQuery})`);
```

**Comment by yaredtsy** [comment]
> return root.querySelector(`${selectorQuery}:not(${gridClasses.root} ${gridClasses.root} ${selectorQuery})`);

 this means that's not in nested DataGrid right? what if I am working in the nested DataGrid

**Comment by yaredtsy** [comment]
using the unique id for Datagrid also solves the datagrid in datagrid problem #4243
Before: https://codesandbox.io/s/icy-flower-h047x1

After: https://codesandbox.io/s/festive-hypatia-y96003?file=/demo.tsx
Demo from 4243 https://codesandbox.io/s/debug-modal-with-datagrid-forked-2lb9ge?file=/src/TinyInfo.tsx.

should I create a PR for it?

**Comment by cherniavskii** [comment]
> I have exposed `gridId` API you can change it

**Comment by cherniavskii** [comment]
Also, [`TreeWalker`](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) might be useful here

**Comment by yaredtsy** [comment]
> If an user has passed a custom cell component, and it doesn't add this attribute, then everything relying on `getCellElement` won't work

what about passing the `apiRef.current.instanceId` to Row's. and the cell must be a direct descendent of that row

```jsx
 const cell = (event.target as HTMLDivElement).closest(
        `[data-parentid="${apiRef.current.instanceId}"] > .${gridClasses.cell}`,
      );
```

or add the id to `virtualScroller` and the cell must be a direct child of the row which is a direct child of the virtualScoller with the grid instance id. 

```
const cell = (event.target as HTMLDivElement).closest(
      `[data-parentid="${apiRef.current.instanceId}"] > .${gridClasses.row} > .${gridClasses.cell}`,
);
```

> Something similar could be done in findParentElementFromClassName.

`findParentElementFromClassName` is using `closest()` . I do not know if it's possible to apply the same logic. if we did not modify the selector it always returns the cell element.

**Comment by yaredtsy** [comment]
I found another way. if we calculate the exact depth of the Datagrid we can query for cells in that depth only. bt excluding the datagrids that are above and below

```jsx
  let depth = 0;
  let current: Element = root;
  while (current?.parentElement != null) {
    if (current?.parentElement?.classList.contains(gridClasses.root)) {
      depth += 1;
    }
    current = current?.parentElement;
  }
```
we can query `getGridCellElement` only in grid that is `depth` number of `gridClasses.root` child and childs morethan `depth + 1` .

```jsx
  let parent = `.${gridClasses.root}`;

  for (let i = 0; i < depth; i += 1) {
    parent += ` .${gridClasses.root}`;
  }

  return root.querySelector<HTMLDivElement>(
    `${parent} ${selector}:not(${parent}  .${gridClasses.root} ${selector})`,
  );
}
```

and for `findParentElementFromClassName` query for ancestor elements that do not have `depth + 1` of `gridClasses.root` parents
```jsx
let rootClass = `.${gridClasses.root} .${gridClasses.root}`;
  for (let i = 0; i < depth; i += 1) {
    rootClass += ` .${gridClasses.root}`;
  }
  return elem.closest(`.${className}:not( ${rootClass} .${className})`);
```

I have tested it out everything works.

**Comment by yaredtsy** [comment]
Here are the Demos

Nested DataGrid :  https://codesandbox.io/s/festive-hypatia-y96003?file=/demo.tsx
Popup DataGrid: https://codesandbox.io/s/debug-modal-with-datagrid-forked-2lb9ge?file=/src/BasicModal.tsx

**Comment by yaredtsy** [comment]
should I create a PR as a draft so you can guys can review the implementation?

**Comment by cherniavskii** [comment]
@yaredtsy are there some specific use cases where you could reproduce this issue?
If not - it's not a high priority and we can address it later after releasing the v6 stable

**Comment by yaredtsy** [comment]
hey @cherniavskii , no I do not have any use cases for it. it can wait

**Comment by cherniavskii** [comment]
We just got the first report for this issue in https://github.com/mui/mui-x/issues/7819
