### ISSUE TITLE
[docs] Module `@mui/x-date-pickers` has no exported member `bgBG`

### ISSUE THREAD

**Issue by johnflux** [mui/mui-x#7096]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I'm doing:

I have: "@mui/x-date-pickers": "5.0.9" installed.

`import { bgBG } from '@mui/x-date-pickers';`

But I get: 

`Module "@mui/x-date-pickers" has no exported member 'bgBG'`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by johnflux** [comment]
OH!

The docs are very confusing!

They say to do:

`import bgLocale from 'date-fns/locale/bg';`

But if you do, you'll get Bulgarian!   If you want english you actually have to do:

`import enUSLocale from 'date-fns/locale/en-US';
     <LocalizationProvider
          dateAdapter={AdapterDateFns}
          adapterLocale={enUSLocale} // use locale for date parser/formatter
        >
`

And instead of `bgBG` you have to do:

`import { enUS } from '@mui/x-date-pickers';
export const theme = createTheme({...}, enUS)
`

**Comment by LukasTy** [comment]
Hello @johnflux 
Thank you for opening this issue.
Do I understand correctly that the doc suggesting to use `bg` locale got you confused, because `x-date-pickers` does not actually have this locale yet? Or was it something else?
We will address this inconsistency. 👌

**Comment by flaviendelangle** [comment]
Closing this issue, the linked PR resolves the problem :+1:

**Comment by johnflux** [comment]
But all you did was change it from Bulgarian to German!

Can you please state in the docs that that is for German (just saying de isn't enough. I thought that was the variable name).  And state to replace de with the language that you want. 

And can you show how to use the default American English locale please. I couldn't figure out how and the docs don't say how to do it at all. Typescript makes the parameter required, is that correct?

**Comment by LukasTy** [comment]
@johnflux 
Are we in some sort of misunderstanding?
![Screenshot 2022-12-07 at 17 17 50](https://user-images.githubusercontent.com/4941090/206218063-1485eb6c-7394-4e04-a195-b32b7cf3636b.png)
It's stated in the docs that if you are fine with English (US) locale—you don't need to make any changes.

All the following documentation is for those, who need a different locale.
All the supported locales with their import keys are listed [at the bottom of the page](https://mui.com/x/react-date-pickers/localization/#supported-locales).

**Comment by johnflux** [comment]
I got typescript errors if I didn't specify the locale. Something broke there. I

**Comment by LukasTy** [comment]
> I got typescript errors if I didn't specify the locale. Something broke there. There is no example for having the default locale.

Could you please provide a working example (you can use any pickers codesandbox as a base) or a code snippet resulting in your mentioned issue?

**Comment by johnflux** [comment]
Just as a quick aside:

https://mui.com/x/api/date-pickers/desktop-date-picker/#main-content

This says:

```import DesktopDatePicker from '@mui/x-date-pickers/DesktopDatePicker';```

But it actually needs to be:

```import { DesktopDatePicker } from '@mui/x-date-pickers/DesktopDatePicker';

Or am I missing something?

**Comment by flaviendelangle** [comment]
Yes, these imports are wrong, they are fixed on the new version but I will back-port the fix on the main doc, it's not great to have misleading information like this...

**Comment by johnflux** [comment]
Is it intentional that when the DesktopDatePicker was removed from labs, it isn't removed from the typescript?  So it compiles and appears to all work, but the date picker itself just does not appear?

The only way I found out was that the date pickers suddenly weren't appearing anymore.

**Comment by flaviendelangle** [comment]
What do you mean by "isn't removed from the typescript" ?
When we remove a component from a package, we replace it with an empty one which throw a warning, that way your whole application is not entirely broken.
But this can make the discovery of this change harder.

You are the first one to report it to us, so hopefully it was not to much of a pain for the community, but that's something we can reconsider for the next migrations away from the lab.

____

For the broken import #7134
