### ISSUE TITLE
[docs] Improve supported localization table

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#7101]
Follow up of #7002

> I was also wondering about using % to make it easier to process the information, but we would indeed lose the information oh how many keys there is missing. So maybe not better.
>
>The only feedback I would have is that it's not easy to make the difference between what's fully translated, and what has a few keys missing. Developers might miss that they could complete the translations. Maybe green should be reserved for 100% not sure.
>
>In any case, it's a great step forward.

_Originally posted by @oliviertassinari in https://github.com/mui/mui-x/issues/7002#issuecomment-1334208719_

The current design of the progress bar is derived from the main demonstration of the Data Grid. It has been done to test if such a table would encourage l10n contribution.

![](https://user-images.githubusercontent.com/3165635/204865157-5d37c6cc-77df-463a-a76a-c6cb4d32eac2.png)

If it does impact contribution, we could consider improving it with a better design

For example, modifying colors, or having a different text displayed

![](https://user-images.githubusercontent.com/45398769/205251534-cf714f5b-b3d2-4995-af02-e2b74afa89a4.png)

**Comment by alexfauquette** [comment]
Definitely looks better 👌🎨 

I have two points of improvement in mind:

- It's still hard to distinguish 35/36 from 36/36. Maybe replacing the digits with "done" or a celebration emoji would solve the problem without impacting colors.

- I don't know why but with red I feel like it could be the number of missing translations. Maybe only using orange and green

**Comment by noraleonte** [comment]
Awesome, thanks for the feedback! 🎉 

I think the emoji could be a really cool idea 🤔 
I am not sure about making the background red. It might prove to be a strange contrast between yellow-red/green-red. Not sure if that is the way to go, but I'll try exploring that area a little 🛩️
