### ISSUE TITLE
Data grid cell sx prop

### ISSUE THREAD

**Issue by martinsvb** [mui/mui-x#7106]
### Order ID 💳

54652

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We need customize data grid cell based row values and MUI theme.
We are adding for this reason Box component with sx property into our custom cell's renderers.
This additional Box component is basically just wrapper under the data grid's cell wrapper.
It would be great, if it's possible to set sx property to column definition like [cellClassName](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/models/colDef/gridColDef.ts#L158) is already possible.
But just className isn't sufficient for our use case.
Is it possible add sx prop into GridColDef interface working?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by martinsvb** [comment]
Hello Andrew,
yes, I tried create some className similarly to example in documentation.
Our problem is unfortunately more complicated.
We are getting dynamic styles from the BE, which can contains many settings.
Of course, set for example alignment dynamically is possible by classNames, but there are also values like padding and so on.
We achieve to set cell design properly by Box component with sx prop in cell renderer.
But it would be much better to be able to set this sx prop to data grid cell's wrapper.
I think this sx prop would be use full anyway in library.
Thank you,
Martin

**Comment by martinsvb** [comment]
Hello @cherniavskii,
I checked [GridCell](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L258) component and as I understand sx can't be used there because of simple div.
I see, [style](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L177) object on this div, is it possible update it for using style prop like:
```
  const style = {
    ...style, // style prop
    minWidth: width,
    maxWidth: width,
    minHeight: height,
    maxHeight: height === 'auto' ? 'none' : height, // max-height doesn't support "auto"
  };
```
It should help us.
I again checked our code and we are really need set concrete CSS values, not just select predefined classes conditionally.
Thank you,
Martin

**Comment by martinsvb** [comment]
Hello, is it some progress in this question?
For our use case is really important possibillity to set custom style on data grid cell.
Is it possible open PR for data grid about it?
I don't know what is your process to do it and if it's allowed for anybody.

**Comment by martinsvb** [comment]
Hello @cherniavskii, please can you check my question above.
I think, I can try to open pull request for style property change.
We really need it.
Thank you,
Martin

**Comment by cherniavskii** [comment]
Hey @martinsvb 
Sorry for taking so long to respond.
I'll take a look at it again today!

**Comment by cherniavskii** [comment]
Hey @martinsvb 
I've created this demo that allows using both `sx` and row data by wrapping the `Cell` component slot with a `Box` component:
https://codesandbox.io/s/hopeful-wing-d4ty06?file=/demo.tsx
Is this what you currently do?

> I see, [style](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/components/cell/GridCell.tsx?rgh-link-date=2022-12-07T09%3A01%3A56Z#L177) object on this div, is it possible update it for using style prop

Would passing `style` prop to a grid cell solve your problem though? You mentioned that you want to access both row data and the theme when applying dynamic styles to the cell.

**Comment by cherniavskii** [comment]
Also, could you take a look at this snippet?
Is this the kind of styling you're looking for?

```tsx
import * as React from 'react';
import { DataGrid, GridColDef } from '@mui/x-data-grid';

const columns: GridColDef[] = [
  { field: 'username', getSx: (params) => params.row.sx },
  { field: 'age' },
];

const rows = [
  {
    id: 1,
    username: '@MUI',
    age: 20,
    sx: { backgroundColor: 'primary.main' },
  },
];

export default function BasicColumnsGrid() {
  return (
    <div style={{ height: 250, width: '100%' }}>
      <DataGrid columns={columns} rows={rows} />
    </div>
  );
}
```

**Comment by martinsvb** [comment]
Hello @cherniavskii ,
last snippet is what we are looking for.
Similarly to function callback, which can be passed to 'cellClassName' GridColDef property would be great for us to set style property mentioned in my comment above or also sx would be good.
Something named like getCellStyle.

**Comment by martinsvb** [comment]
> Hey @martinsvb I've created this demo that allows using both `sx` and row data by wrapping the `Cell` component slot with a `Box` component: https://codesandbox.io/s/hopeful-wing-d4ty06?file=/demo.tsx Is this what you currently do?
> 
> > I see, [style](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/components/cell/GridCell.tsx?rgh-link-date=2022-12-07T09%3A01%3A56Z#L177) object on this div, is it possible update it for using style prop
> 
> Would passing `style` prop to a grid cell solve your problem though? You mentioned that you want to access both row data and the theme when applying dynamic styles to the cell.

Hi @cherniavskii, we are using custom renderers by renderCell for each column.
So, this general cell doesn't helps us.
Some of them are just style formatted cells.
But at all data grid is slow with all custom renderers.
We fixed some performance issues with our renderers, but performance still isn't sufficient.
I realized, that just display the data through your native cell (not use renderCell) callback makes it faster.
So, we would like to display some of the columns by data grid's native cell, but we need to set up styling mentioned above.

**Comment by martinsvb** [comment]
Hello @cherniavskii,
we still not have satisfy performance solution for our data grid use case.
During investigation, I found, that getRowHeight callback with 'auto' value prolong rendering of rows.
We have performance issue with scrolling.
So, I'm always testing one row scroll down after load to compare results.
In case of getRowHeight callback with 'auto' value it takes around 10 cycles in Profiler, without that it's usually around 6 cycles and performance is much better.
Isn't it doing some operation which is causing rows re-rendering?
It seems to me like yes.

**Comment by cherniavskii** [comment]
Hi @martinsvb 

> we are using custom renderers by renderCell for each column.
So, this general cell doesn't helps us.
Some of them are just style formatted cells.

Could you clarify why the solution described in https://github.com/mui/mui-x/issues/7106#issuecomment-1360468042 won't work for you?

**Comment by cherniavskii** [comment]
> But at all data grid is slow with all custom renderers.
We fixed some performance issues with our renderers, but performance still isn't sufficient.

> we still don't have satisfy performance solution for our data grid use case.
During investigation, I found, that getRowHeight callback with 'auto' value prolong rendering of rows.
We have performance issue with scrolling.

Could you open a new issue with a reproduction example of performance issues?

**Comment by cherniavskii** [comment]
> In case of getRowHeight callback with 'auto' value it takes around 10 cycles in Profiler, without that it's usually around 6 cycles and performance is much better.
Isn't it doing some operation which is causing rows re-rendering?


The [dynamic row height](https://mui.com/x/react-data-grid/row-height/#dynamic-row-height) feature does additional work of measuring the rows and rerendering them.
But it shouldn't have a huge impact on performance.
Is virtualization enabled in your grid? (it's enabled by default unless you pass `disableVirtualization={true}` to the data grid)
