### ISSUE TITLE
DataGrid will flash/blink when a new item is added into it, using inside a styled() component

### ISSUE THREAD

**Issue by linkfang** [mui/mui-x#7107]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/vigorous-albattani-4qxlvi?file=/src/App.js

Steps:
1. Click on the "Add New Item" button
2. The table above the button will flash once when a new item is added

### Current behavior 😯

When put the table in a `styled()` component, it will flash/blink when a new item is added into it. See the table above button.

It will not flash/blink if we use a `div` instead of `CustomCard`. See the table below the button.

### Expected behavior 🤔

The table will not flash or blink inside a `styled()` component.

I tried the table component from Ant Design and it doesn't have the issue in the same condition.

### Context 🔦

I would like to have a CustomCard component and will put different things into it. And only the table will flash/blink, all other components I use don't have the issue.

I can avoid using `styled()` as a work around. But it would be better if it simply work well with DataGrid.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  It happens on both Chrome and Edge.

```
  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Edge: Not Found
    Firefox: 105.0.1
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.108 
    @mui/core-downloads-tracker:  5.10.16 
    @mui/material: ^5.10.16 => 5.10.16 
    @mui/private-theming:  5.10.16 
    @mui/styled-engine:  5.10.16 
    @mui/system:  5.10.16 
    @mui/types:  7.2.2 
    @mui/utils:  5.10.16 
    @mui/x-data-grid: ^5.17.14 => 5.17.14 
    @types/react:  18.0.26 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
```
</details>

**Comment by cherniavskii** [comment]
Hey @linkfang 
Is there a reason why the `CustomCard` component is defined inside the react component?
There's no flash after I've moved it out: https://codesandbox.io/s/goofy-browser-mfebi5?file=/src/App.js

Also, memoizing `columns` would be a good idea too:
> The columns prop should keep the same reference between two renders. The columns are designed to be definitions, to never change once the component is mounted. Otherwise, you take the risk of losing elements like column width or order. You can create the array outside the render function or memoize it.

Source: https://mui.com/x/react-data-grid/column-definition/

**Comment by cherniavskii** [comment]
You're welcome!

> I am still wondering why it will flash in that situation while others won't.

The reason is that each time `CustomCard` gets recreated it has a different type. And therefore React tears down the whole tree starting from the `CustomCard` component and creates it again.
DOM elements like `diff` do not expose this issue (see https://reactjs.org/docs/reconciliation.html for more info)
Also, `styled` has nothing to do here - see this demo: https://codesandbox.io/s/vigorous-albattani-4qxlvi?file=/src/App.js

**Comment by linkfang** [comment]
@cherniavskii , Sorry, I didn't realize the demo link you shared was my previous link, and I already edited it so I can't see your version now...

Yeah, I was thinking it's because of re-render stuff, but my question is more on why Ant Design doesn't have the flash behaviour in the same situation, which made me think it was a bug on MUI side... 
See demo here: https://codesandbox.io/s/vigorous-albattani-4qxlvi?file=/src/App.js

The table below the button is from Ant Design.

**Comment by linkfang** [comment]
And I think the same thing happened in this issue: https://github.com/mui/mui-x/issues/6595

When we switch tabs, the table will flash. Example from the issue: https://codesandbox.io/s/laughing-hopper-0mv8ll
But the Ant Design table will not flash. Example: https://codesandbox.io/s/dry-platform-xgvdu0?file=/src/App.js

Is this because of performance?

**Comment by cherniavskii** [comment]
> my question is more on why Ant Design doesn't have the flash behaviour in the same situation, which made me think it was a bug (or a performance issue) on MUI side...
See demo here: [codesandbox.io/s/vigorous-albattani-4qxlvi?file=/src/App.js](https://codesandbox.io/s/vigorous-albattani-4qxlvi?file=/src/App.js)

Thanks for the demo!
Indeed, the Ant Design Table doesn't flash.
I believe it's because the Ant Design Table doesn't have a built-in virtualization feature, while DataGrid does.
I've checked their [Virtual list example](https://ant.design/components/table#components-table-demo-virtual-list) and created a similar demo with virtualization where you can see the flash as well: https://codesandbox.io/s/virtual-list-antd-5-0-5-forked-mfjcjf?file=/demo.tsx

**Comment by cherniavskii** [comment]
> And I think the same thing happened in this issue: https://github.com/mui/mui-x/issues/6595

Yes, this is the same issue. I'll take a look, maybe there's something we can do to avoid the flickering 👍

**Comment by cherniavskii** [comment]
@linkfang 
Here's a PR with the fix: https://github.com/mui/mui-x/pull/7155
And a working demo: https://codesandbox.io/s/jolly-leakey-h8b3jq

Thanks for your time spent on this issue! 🎉

**Comment by linkfang** [comment]
@cherniavskii , awesome! Thanks for the explanation and the speedy fix! 🎉
