### ISSUE TITLE
[pickers] Time taken from the current date instead of being zeroed

### ISSUE THREAD

**Issue by vocko** [mui/mui-x#7114]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Enter a random invalid date into the DesktopPickerField (possibly other ones, I have tested on this) - ie. 89/89
2. Click calendar icon
3. Change year
4. Select data
5. OnChange callback returns date with time set to the current time

### Current behavior 😯

As per the steps above, the date returned has time set to the current time in the local timezone.

I have found this [issue](https://github.com/mui/mui-x/issues/4449) which has been fixed a few months ago, but it seems some cases still slipped through the cracks.

### Expected behavior 🤔

The date returned will be set to the midnight (zero time).

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
   System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.95
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.42)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.109
    @mui/core-downloads-tracker:  5.10.17
    @mui/icons-material: ^5.10.16 => 5.10.16
    @mui/lab: ^5.0.0-alpha.111 => 5.0.0-alpha.111
    @mui/material: ^5.10.17 => 5.10.17
    @mui/private-theming:  5.10.16
    @mui/styled-engine:  5.10.16
    @mui/styles: ^5.10.16 => 5.10.16
    @mui/system:  5.10.17
    @mui/types:  7.2.2
    @mui/utils:  5.10.16
    @mui/x-data-grid:  5.17.14
    @mui/x-data-grid-premium: ^5.17.14 => 5.17.14
    @mui/x-data-grid-pro:  5.17.14
    @mui/x-date-pickers:  5.0.9
    @mui/x-date-pickers-pro: ^5.0.9 => 5.0.9
    @mui/x-license-pro:  5.17.12
    @types/react: 18.0.26 => 18.0.26
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
```
</details>

### Order ID 💳 (optional)

ZD362901

**Comment by LukasTy** [comment]
@vocko Thank you for creating this issue and noticing the inconsistency.
I've been able to reproduce your mentioned issue.
The issue lies in the `YearCalendar` component and a more minimal reproduction example is as follows:
- open calendar
- switch to year view
- select year (date with current time is selected)
- selecting any date after this will not change the time
