### ISSUE TITLE
[data grid] Double Click on row not working on mobile view

### ISSUE THREAD

**Issue by dennisobel** [mui/mui-x#7117]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Add MUI DataGrid or DataGrid pro
2. Add doubleclick event handler (onRowDoubleClick)
3. Test on desktop
4.Test on mobile (doesn't respond)

### Current behavior 😯

Double click works only on desktop view but not on mobile view

### Expected behavior 🤔

Double click should work on mobile

### Context 🔦

I'm trying to display a modal on double clicking a row

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by Revolt9k** [comment]
Same problem here. It doesnt fires when users taps instead of click.  Latest chrome.

**Comment by BlerionMuco** [comment]
> Hi @dennisobel I just tested it on Safari iOS with this demo: https://codesandbox.io/s/nice-tereshkova-y9ix83?file=/demo.tsx Seems to work fine. Can you try the demo and let me know if it works for you?

No it isnt working. You still has that on dektopn view despite that you has choosen a mobile for sandbox.
![image](https://user-images.githubusercontent.com/66955735/208617690-c640f290-dafa-4ec1-ba96-1745f7c0fc4b.png)
in this format that will not work

**Comment by cherniavskii** [comment]
> > Hi @dennisobel I just tested it on Safari iOS with this demo: [codesandbox.io/s/nice-tereshkova-y9ix83?file=/demo.tsx](https://codesandbox.io/s/nice-tereshkova-y9ix83?file=/demo.tsx) Seems to work fine. Can you try the demo and let me know if it works for you?
> 
> No it isnt working. You still has that on dektopn view despite that you has choosen a mobile for sandbox. ![image](https://user-images.githubusercontent.com/66955735/208617690-c640f290-dafa-4ec1-ba96-1745f7c0fc4b.png) in this format that will not work

This is not a mobile device, it's just a device screen simulation.
On mobile Safari it works:

https://user-images.githubusercontent.com/13808724/208931774-76686657-1069-453e-b0d2-986214fe3852.mov

**Comment by Misiu** [comment]
@cherniavskii on Windows 10 open code sandbox with preview link (https://y9ix83.csb.app/) in Google Chrome (111.0.5563.65), then hit F12 and turn on responsive view.
When in the "standard" view you get a mouse cursor and double click works, but in the responsive view, you get a grey circle instead of the cursor, which doesn't work (no alert)

BTW: this works fine on android phones, but not in Chrome responsive view (on Windows). During development, I use Chrome's responsive view, making testing my app difficult.

**Comment by cherniavskii** [comment]
@Misiu Is doesn't seem to be an issue with the data grid - see this demo from w3schools which behaves exactly the same:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_ondblclick
