### ISSUE TITLE
[pickers] The placeholder of the masked-based pickers are not localized (shows `yyyy` for year, even in Portuguese)

### ISSUE THREAD

**Issue by Asghwor** [mui/mui-x#7126]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
[demo](https://codesandbox.io/s/small-bird-msf0qt)

Steps:
1. Create a React project and setup Material UI and `@mui/x-date-pickers`
2. Use the pt-br (Brazilian Portuguese) locale for both the `LocalizationProvider` and the `ThemeProvider`
3. Notice the placeholder of the date picker is `dd/mm/yyyy` instead of `dd/mm/aaaa`

### Current behavior 😯

The letter used for the date picker's placeholder for the year is "y" instead of "a" in Brazilian Portuguese.
E.g.: `dd/mm/yyyy` instead of `dd/mm/aaaa`, `mm/yyyy` instead of `mm/aaaa`, etc.

### Expected behavior 🤔

The letter used for the year should be "a".
E.g.:  `dd/mm/aaaa` instead of `dd/mm/yyyy`, `mm/aaaa` instead of `mm/yyyy`, etc.

### Context 🔦

The word for "year" in Portuguese is "ano", starting with an "a", so the placeholders showcasing the mask to be used in a given date picker (day/month/year, month/year, day/year, year, etc) needs to use this letter to be readily understood by Portuguese speakers.

### Your environment 🌎

- @mui/material 5.10.17
- @mui/x-date-picker 5.0.9

**Comment by flaviendelangle** [comment]
On the new pickers that will be released on v6, we are applying localization on the placeholders.
But for the v5 pickers, the placeholders is pretty-much the format from the date library, and the date libraries don't apply any localization on the format itself.

**Comment by LukasTy** [comment]
> On the new pickers that will be released on v6, we are applying localization on the placeholders.

But the result for v6 will be the same? Or am I missing something?
![Screenshot 2022-12-08 at 09 46 19](https://user-images.githubusercontent.com/4941090/206388828-f8146075-ae78-433f-b612-38ea463a71e0.png)

**Comment by flaviendelangle** [comment]
On v6 pickers, the placeholders are generated using the following locale keys:

```ts
  // Field section placeholders
  fieldYearPlaceholder: (params) => 'Y'.repeat(params.digitAmount),
  fieldMonthPlaceholder: (params) => (params.contentType === 'letter' ? 'MMMM' : 'MM'),
  fieldDayPlaceholder: () => 'DD',
  fieldHoursPlaceholder: () => 'hh',
  fieldMinutesPlaceholder: () => 'mm',
  fieldSecondsPlaceholder: () => 'ss',
  fieldMeridiemPlaceholder: () => 'aa',
```

But right now, nobody translated them (because nobody uses the alpha :laughing: )

**Comment by LukasTy** [comment]
> But right now, nobody translated them (because nobody uses the alpha 😆 )
> 
> The PR introducing it is #6337

Well, sorry for a dumb question then. I haven't reviewed the mentioned PR, that's why I was not aware of this detail. 🙈

**Comment by flaviendelangle** [comment]
No dumb question :angel: , we have so much going on, we all miss some

@Asghwor I hope this answer your question
In v5 we basically can't do anything with the current implementation due to how the date-libraries (date-fns, dayjs, moment, luxon) behaves.
In v6 it will work out of the box

**Comment by Asghwor** [comment]
@flaviendelangle No, I think that answers my question. Thanks for the help!

I managed to make it show

**Comment by is-paranoia** [comment]
> @flaviendelangle No, I think that answers my question. Thanks for the help!
> 
> I managed to make it show the desired placeholder by using a `replace('y', 'a')` in the render component.

@flaviendelangle hello! I understand that it's been quite a while 😅. I need to implement a feature in one of our legacy projects, but we can't upgrade to a higher version. Could you explain how you did it with `replace` on version 5?

**Comment by LukasTy** [comment]
@is-paranoia could you clarify the version of the package you are trying to use?
With the latest version (and v6.x if my memory serves me well) you can utilize the [component localization](https://mui.com/x/react-date-pickers/adapters-locale/#custom-field-placeholder) to achieve the desired placeholder.
In custom cases, if the values provided by the localization are insufficient, you can pass a custom `localeText` value for specific sections to achieve your result. 😉
