### ISSUE TITLE
Why client side rendering is required in nextjs 13 for mui use

### ISSUE THREAD

**Issue by alexk345** [mui/mui-x#7128]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Why i have to use "use client" on all mui components in nextjs 13?
I did x-datagrid with my own crud api. I used "use client" directive. Its ok for that.

But i am trying to create dashboard layout and its asking "use client" on all mui libraries.

If we render all on client side ? its very bad practice and slow.

https://levelup.gitconnected.com/using-material-ui-with-next-js-13-and-tailwind-css-41c201855dcf
that is example. it has only 3 buttons. Why it need client side rendering?

I am new to react/nextjs/mui .... i am kinda stuck. Whole idea of using react is server side render everything except few which needed client side.

Who can help? I searched discord , gitter channels. No one responding.

Do you guys forum so i can follow up my question?

### Examples 🌈

https://levelup.gitconnected.com/using-material-ui-with-next-js-13-and-tailwind-css-41c201855dcf

**Comment by cherniavskii** [comment]
Hey @alexk345 
Please refer to https://github.com/mui/material-ui/issues/34905 where the topic has been discussed, and https://github.com/mui/material-ui/issues/34905#issuecomment-1326535989 specifically
