### ISSUE TITLE
How to get or move aggregation value of a column from footer to another places (like header)

### ISSUE THREAD

**Issue by 7ruth** [mui/mui-x#7129]
### Order ID 💳

53455

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

How to take a column aggregation value and render it in another place (not footer). Ideally I just have access to that value once its calculated and I render it inside a custom Toolbar by passing that value to components={{Toolbar:CustomToolbar}} and there I'll have this aggregated value for several of the columns that are important to us. Example I am looking at: https://codesandbox.io/s/4g56gf?file=/demo.tsx:938-1028

![8D996818-B3A6-4418-8D16-5757F1A97ED3](https://user-images.githubusercontent.com/10719152/206305966-46f80bb9-1a59-4dfa-bc61-d350bdf09ddc.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 104.0
    Safari: 14.1.2
```
</details>

**Comment by cherniavskii** [comment]
Hey @7ruth 
To get the aggregation value, you can use the `gridAggregationLookupSelector` state selector.
Here's a demo: https://codesandbox.io/s/cocky-fermat-0qmes4?file=/demo.tsx
I'll submit a PR to make sure aggregation selectors are listed on the State page https://mui.com/x/react-data-grid/state/

**Comment by 7ruth** [comment]
This is exactly what I am looking for, thank you so much!!!
