### ISSUE TITLE
I am looking for filtering field for each column. current dialog design is bad.

### ISSUE THREAD

**Issue by alexk345** [mui/mui-x#7150]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

My users  are simple minded people.  They need filter field under each column. do you have way to do it now? i searched i cant find.  i think bootstrap datatable has it. please add that feature . tks much.

**Comment by cherniavskii** [comment]
Duplicate of https://github.com/mui/mui-x/issues/4934?
