### ISSUE TITLE
[DateTimePicker] Dynamic date and time disabling

### ISSUE THREAD

**Issue by yuribertoli** [mui/mui-x#7167]
I'm trying to disable the times that can't be used to make an appointment, so far I've managed to disable the days but not the precise times. Basically I would like to keep active the ability to click on the desired day but then I don't want to give the possibility to book at a time already taken (preferably marked in red). Appointments can be made between 09:00 and 17:30 Monday to Friday

ps: I have disabled the possibility of inserting the time via text, it is only possible by clicking on the calendar (it's not visible here)

This is the component:

```
<DateTimePicker
                    disablePast
                    inputFormat="DD/MM/YYYY HH:mm"
                    minutesStep={30}
                    minTime={dayjs('2018-01-01T09:00')}
                    maxTime={dayjs('2018-01-01T17:30')}
                    renderDay={disableSpecificDays}
                    shouldDisableDate={disableWeekends}
                    shouldDisableTime={disableSpecificTimes}
                    value={booking.bookingDate}
                    onChange={(newValue) => { dispatch(b.setBookingDate(newValue)) }}
                    renderInput={(params) => <TextField {...params} />}
                />
```
these are the days to disable:
```
const datesToDisable= ["2022-12-19T00:00:00.000Z", "2022-12-27T00:00:00.000Z", "2022-12-22T00:00:00.000Z", "2022-12-28T00:00:00.000Z"]
```

this is the function to disable the days (dunno if I can add here the possibility to disable times):
```
const disableSpecificDays = (date: dayjs.Dayjs, selectedDates: dayjs.Dayjs[], pickersDayProps: PickersDayProps<dayjs.Dayjs>
    ): JSX.Element => {
        const stringifiedDate = dayjs(date).format('YYYY-MM-DD')
        const dates = datesToDisable.map((day) => { return day.slice(0, 10) })
        if (dates.includes(stringifiedDate)) {
            return <PickersDay {...pickersDayProps} disabled />
        }
        return <PickersDay {...pickersDayProps} />
    }
```

these are the times booked:
```
const timesBooked= ["2022-12-30T15:30:00.000Z", "2023-01-03T10:30:00.000Z", "2023-01-04T17:00:00.000Z", "2023-01-05T09:00:00.000Z"]
```

Should I disable the times of those specific days by using this function called in "shouldDisableTime"? If I can, I have no idea how to do it...

```
const disableSpecificTimes = (timeValue: number, clockType: ClockPickerView): boolean => {
         //something here maybe?
    }
```

**Comment by yuribertoli** [comment]
Thank you so much for your reply @LukasTy !

You gave me the right direction for completing my task, your solution was nearly working except for one thing that I've changed. I replaced this part that you wrote:

`
if (clockType === "hours") {
          return disabledTimes.some(
            (disabledTime) =>
              disabledTime.date() === selectedDay &&
              disabledTime.hour() === time &&
              disabledTime.minute() === value.minute()
          );
        } else if (clockType === "minutes") {
          return disabledTimes.some(
            (disabledTime) =>
              disabledTime.date() === selectedDay &&
              disabledTime.hour() === value.hour() &&
              disabledTime.minute() === time
          );
        }
`

With that: 
`
if (clockType === "minutes" || clockType === "hours") {
                return disabledTimes.some(
                    (disabledTime) =>
                        disabledTime.date() === selectedDay &&
                        disabledTime.hour() - 1 === value.hour() &&
                        disabledTime.minute() === time
                )
            }
`
Otherwise the function was stopping when finding a match in "hours" and never entering in the minutes section, plus it was selecting the next hour so I added  -1 to disabledTime.hour().

However, I would never have been able to get to the solution without your support, thank you very much again

**Comment by LukasTy** [comment]
> However, I would never have been able to get to the solution without your support, thank you very much again

I'm glad to hear that we could help you continue development, but we'll keep this case in mind and consider improving the existing dynamic time disabling API. 👌

**Comment by LukasTy** [comment]
Hello @yuribertoli 
I've experimented with refactoring `shouldDisableTime` for the next version.
The idea is to align it with other `shouldDisable` props and pass `TDate` value instead of currently selected clock view value.
Do you think that [such API](https://codesandbox.io/s/custom-day-and-time-disabling-refactored-g8gy8f?file=/demo.tsx) would be more DX friendly and also allow you to achieve your goal easier? 🤔

**Comment by yuribertoli** [comment]
Ciao @LukasTy !
The solution you propose seems to me much clearer than the previous one we discussed. But unfortunately, I could not get it to work for the times I had selected. So I thought of starting from your project and modifying your function a bit in order to also consider minutesStep value (clearly everything happens manually now, it would be nice to be able to connect the values of minutesStep with shouldDisableTime automatically), I thought this was important because otherwise all solutions where working with just one minutesStep value at a time.
However, now it should correctly disable the hour present in the clock if all minutes can't be clicked, regardless of minutesStep's value.
Let me know what you think about it!
I leave your [here](https://codesandbox.io/s/custom-day-and-time-disabling-refactored-forked-j1x4bo?file=/demo.tsx) the code so you can test it.
Take care

**Comment by LukasTy** [comment]
> The solution you propose seems to me much clearer than the previous one we discussed

Hey, excuse me if I did not make myself clear. My example/suggestion was not to provide a solution covering all cases, but to ask you to look into the new API for `shouldDisableTime` and understand if receiving `value` (date object in adapters format), instead of `timeValue` (minute number) provides a better DX and allows for a more concise/complete solution? 🤔 
If that would be the case, we could refactor this API in this way for v6 release. 👍

**Comment by yuribertoli** [comment]
> > The solution you propose seems to me much clearer than the previous one we discussed
> 
> Hey, excuse me if I did not make myself clear. My example/suggestion was not to provide a solution covering all cases, but to ask you to look into the new API for `shouldDisableTime` and understand if receiving `value` (date object in adapters format), instead of `timeValue` (minute number) provides a better DX and allows for a more concise/complete solution? 🤔 If that would be the case, we could refactor this API in this way for v6 release. 👍

Oh sorry, I misunderstood the question. However yes I think it is much better to interpret the data in the new case and also the code necessary seems to me much clearer this way.  That would be a good upgrade!
