### ISSUE TITLE
[pickers] Using a `Drawer` instead of a `Dialog` on MobileDatePicker 

### ISSUE THREAD

**Issue by triglian** [mui/mui-x#7183]
### Order ID 💳

4514724970

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello and thanks for the great library!

I have the objective of using a `SwipeableDrawer` that displays a `StaticDatePicker` as shown in the example here: https://codesandbox.io/s/long-pond-02jww2?file=/src/App.tsx

The drawer is being opened when clicking the calendar icon on the `TextField`.

My problem is how to keep the Textfield (the one outside of the `SwipeableDrawer` not the one that we pass in the `renderInput()`) and the StaticDatePicker value connected while at the same time exposing only one "outer" value from the component. The combined component is called "MobileDatePicker" : https://codesandbox.io/s/long-pond-02jww2?file=/src/MobileDatePicker.tsx

We would like the user to be able to set the textfield manually with their keyboard. It would also be great if the field had a mask to format the date.

I've seen in the source code of mui-x that you have some components like `KeyboardDateInput` or the `useDateField` hook that seem to satisfy our requirements. It's my understanding that you don't expose those.

Do you have any suggestions?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Hello @triglian 
That is an interesting use case you are trying to achieve there. 🤔 
I've tinkered around and was able to come up with a rough and a bit hacky (would need a bit of type casting) [solution](https://codesandbox.io/s/bold-snowflake-eh0d96?file=/src/MobileDatePicker.tsx).
What do you think about it? Does it seem close enough?
The idea is to use the picker component as a base and try using the Drawer component instead of the Dialog as the root.

**Comment by triglian** [comment]
Hello @LukasTy 

Thanks a lot for the swift response and the smart solution. It looks solid, I'm trying to fix some type issues and forwardRef issues. If it works I will close the issue.

Thanks for your patience.

**Comment by triglian** [comment]
Hello @LukasTy I had a more detailed look and the proposed solution creates two backdrops and two paper roots as seen in the attached screenshot.

<img width="1339" alt="Screenshot 2022-12-19 at 14 43 25" src="https://user-images.githubusercontent.com/573280/208441519-e125ff4e-50e5-4a9c-a029-44b57aded85b.png">

Moreover, I think that the `TransitionComponent` and `TransitionProps` are only needed as properties of `DialogProps` not `PaperProps`. Maybe I'm wrong about that.

I used your solution as a starting point, then remove the `MobileSwipeableDrawer` from the `DialogProps` `slot` to avoid having two dialogs. I changed the position of the paper to be `absolute` and set the `bottom` to be `0` : https://codesandbox.io/s/prod-platform-843ljs?file=/src/MobileDatePicker.tsx

The problem is that once the user clicks away the first time then a dialog stays in the window. Then the user cannot open the date picker again.

Moreover this approach doesn't allow us to use the swipe gesture.

What do you think?

**Comment by triglian** [comment]
Thanks @LukasTy it's way more elegant indeed.

I can definitely consider v6 if  you provide support  for it as you do for stable. 

When are you planning to make it stable?

**Comment by LukasTy** [comment]
> I can definitely consider v6 if you provide support for it as you do for stable.

We will provide support the same way we do for current stable release.



> When are you planning to make it stable?

It is currently in the final stages of alpha and most if not all breaking changes are almost done. We'll probably be in the beta at least for the month of January. Naively we hope to release stable on February, but we all know how software development estimates go and we might encounter something unknown/unexpected, so, a safer bet would be to assume having stable v6 by the end of Q1. 😃

**Comment by triglian** [comment]
ok then, when 6 goes into beta we will use that one with the `next` pickers.

Thanks for all the help!

**Comment by LukasTy** [comment]
> and we have similar problems when trying to pass custom components in slots. Do you have any suggestion?

@triglian I'm sad to let you know that for now we don't have a working clean TS solution when using complex/different components than the ones we would expect to see in their place.
We are working on a unified solution among all the libraries to allow `slot` type overrides and it will be introduced in the future.
For now, your best bet is to just use `as any` or other types of casting that work.
Does it answer your question? Or are you having other problems with v6 as well?

**Comment by triglian** [comment]
yes it does, thank you
