### ISSUE TITLE
[RFC] Improve grid column definition typing

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#7188]
### What's the problem? 🤔

I usually use the `GridColDef` interface when defining grid columns:
```tsx
const columns: GridColDef[] = [];
```

But I've noticed that it doesn't work with the `actions` column type. In this case, different interfaces should be used instead:
```tsx
// This doesn't work:
// Type '{ field: string; type: string; getActions: () => JSX.Element[]; }' is not assignable to type 'GridColDef<any, any, any>'.
// Object literal may only specify known properties, and 'getActions' does not exist in type 'GridColDef<any, any, any>'.
const columns: GridColDef[] = [
  {
    field: 'actions',
    type: 'actions',
    getActions: () => [<GridActionsCellItem icon={<DeleteIcon />} label="Delete" />],
  },
];

// This works
const columns: GridEnrichedColDef[] = [
  {
    field: 'actions',
    type: 'actions',
    getActions: () => [<GridActionsCellItem icon={<DeleteIcon />} label="Delete" />],
  },
]

// This works
const columns: GridColumns = [
  {
    field: 'actions',
    type: 'actions',
    getActions: () => [<GridActionsCellItem icon={<DeleteIcon />} label="Delete" />],
  },
]
```

We use both `GridColDef` and `GridColumns` in our demos, so it's not clear which one should be used and what is the difference between them.
This is confusing - see https://github.com/mui/mui-x/issues/7115#issuecomment-1347735578 for example.

### What are the requirements? ❓

Ideally, we should expose a single interface that would work for every column type.

### What are our options? 💡

Currently, the `GridEnrichedColDef` should work for every column type, but the interface name is not straightforward and we don't use it in our demos - so it's almost impossible to discover.

### Proposed solution 🟢

1. Rename `GridEnrichedColDef` to `GridColDef`
2. Rename `GridColDef` to `GridBaseColDef`
3. Remove the `GridColumns` interface and use `GridColDef[]` instead

**Comment by cjsilva-umich** [comment]
In [this demo in the documentation](https://mui.com/x/react-data-grid/editing/#FullFeaturedCrudGrid.tsx) it shows to use GridColDef as the type and getActions should work, but it doesn't, as shown above.

**Comment by cjsilva-umich** [comment]
@cherniavskii Didn't realize there was a new major version out. You're right, w/ v6 GridColDef no longer complains about getActions 👍
