### ISSUE TITLE
[data grid] GridToolbarQuickFilter does not working with the default value

### ISSUE THREAD

**Issue by mntky** [mui/mui-x#7192]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Codesandbox ->  https://codesandbox.io/s/intelligent-cori-im6ddk?file=/src/Grid.tsx

Steps:
1. Put a value in the Quickfilter (ex: hog).
2. Check if "filter=hog" is added to the url parameter.
3. Reload page.

### Current behavior 😯

Quickfilter has a urlParam value but is not filtered.

### Expected behavior 🤔

Filtering by urlParam value after page reload.

### Your environment 🌎

https://codesandbox.io/s/intelligent-cori-im6ddk?file=/src/Grid.tsx

**Comment by MBilalShafi** [comment]
`GridToolbarQuickFilter` doesn't support controlled value. You can update the quick filter value imperatively using `apiRef.current.setQuickFilterValues`

```tsx
apiRef.current.setQuickFilterValues(["value"]);
```

Here's the working [example](https://codesandbox.io/s/blissful-http-b3neng?file=/src/Grid.tsx:648-670).

Sidenote: [apiRef](https://github.com/mui/mui-x/pull/6773) is coming to the community package soon too.

**Comment by cherniavskii** [comment]
It's possible to pass the quick filter value using `initialState`:
```tsx
initialState={{
  filter: {
    filterModel: {
      items: [],
      quickFilterValues: ["hog"]
    }
  }
}}
```
See a working demo: https://codesandbox.io/s/thirsty-ardinghelli-gs1c1t?file=/src/Grid.tsx

We should document this.

**Comment by mntky** [comment]
I added 'initialState', it worked well!!
Thank you for the solution.

I also look forward to the addition of the apiRef package.
