### ISSUE TITLE
[data grid] Imports from models are not available - GridDensityTypes is undefined

### ISSUE THREAD

**Issue by joerg3011** [mui/mui-x#7196]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. installed mui/x-data-grid in the latest version 5.17.14
2. when running the data grid is not loaded as in the source code all imports from ../models are not loaded (undefined error), see attachments

![error](https://user-images.githubusercontent.com/120564369/207577648-065ffc47-56dc-4166-a1f2-50cccb3f158c.png)
![debugger](https://user-images.githubusercontent.com/120564369/207577692-05269114-ed90-461e-b6af-5ac9a98148b2.png)

### Current behavior 😯

DataGrid is not loading due to an internal error

### Expected behavior 🤔

DataGrid is loading

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser on the test environment: Firefox 102.5.0esr
  Output from `npx @mui/envinfo` goes here.
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 10.23.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.99
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.46)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.110
    @mui/core-downloads-tracker:  5.11.0
    @mui/material: ^5.11.0 => 5.11.0
    @mui/private-theming:  5.11.0
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.0
    @mui/types:  7.2.3
    @mui/utils:  5.11.0
    @mui/x-data-grid: ^5.17.14 => 5.17.14
    @types/react: 16.8.19 => 16.8.19
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 3.7.5 => 3.7.5
```
</details>

**Comment by MBilalShafi** [comment]
Can you provide a link to live example where the error is being reproduced?
The mentioned version works fine in this [codesandbox](https://codesandbox.io/s/error-reproduce-try-e0khqu?file=/demo.tsx).

**Comment by joerg3011** [comment]
Unfortunately this is not so easily possible as it is part of a larger customer app hosted on the customer's system. Do you have any idea, what could be the cause, that everything in the source code imported from models is undefined?
