### ISSUE TITLE
[data grid] Infinite Re-rendering while Scrolling

### ISSUE THREAD

**Issue by jinpan** [mui/mui-x#7204]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/divine-frost-1pl6uf?file=/src/App.js

Steps:
1.  Scroll on the grid

### Current behavior 😯

https://www.loom.com/share/68399afaa42b4f359e7ea2f66c7e77b8

### Expected behavior 🤔

There should not be the janky scrolling and re-rendering loop.

### Context 🔦

I want to create a datagrid with some ECharts graph cells.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.110 
    @mui/core-downloads-tracker:  5.11.0 
    @mui/material: ^5.11.0 => 5.11.0 
    @mui/private-theming:  5.11.0 
    @mui/styled-engine:  5.11.0 
    @mui/system:  5.11.0 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.0 
    @mui/x-data-grid: ^5.17.14 => 5.17.14 
    @mui/x-data-grid-pro: ^5.17.15 => 5.17.15 
    @mui/x-license-pro:  5.17.12 
    @types/react: 18.0.26 => 18.0.26 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 4.9.4 => 4.9.4 
```
</details>

### Order ID 💳 (optional)

55880

**Comment by cherniavskii** [comment]
Might be the same as https://github.com/mui/mui-x/issues/5354
