### ISSUE TITLE
Datagrid [@mui/x-data-grid-pro]  loading overlay is not showing for pinned columns

### ISSUE THREAD

**Issue by Parthan-Akon** [mui/mui-x#7206]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

![image](https://user-images.githubusercontent.com/50884766/207792435-0c475eb4-6e21-488e-84b3-f92a3187af57.png)
this is not showing for the entire header column.

### Expected behavior 🤔

![image](https://user-images.githubusercontent.com/50884766/207792592-5dfb1f16-f6a3-4465-ab49-6a6223700181.png)
it should cover the pinned columns header too...

### Context 🔦

Front end : React js
Description:
The loading overlay Linear progress is not showing for the pinned columns
`initialState={{ pinnedColumns: { right: ['actions'] } }}`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
That's because the `z-index` of pinned column is higher than that of circular progress.

One way to fix it it to override the z-index of progress bar. Here is a working sandbox [example](https://codesandbox.io/s/elastic-banach-rxxj78?file=/demo.tsx).

**Comment by Parthan-Akon** [comment]
Thanks @MBilalShafi .. worked like a charm...And thank u for the quick reply.
