### ISSUE TITLE
Provide UMD bundles for mui-x components

### ISSUE THREAD

**Issue by noherczeg** [mui/mui-x#7248]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Based on what I saw in the latest packages, I couldn't find any UMD bundles/modules for mui-x components. @mui/material has a umd package therefore I hope this is not impossible.

### Motivation 🔦

In our current setup we'd like to use SystemJS with external UMD packages, but sadly @mui/x-data-grid, and @mui/x-date-pickers don't have such packages therefore we need to bundle these into our artifact instead of loading it externally (saving precious build time).

**Comment by oliviertassinari** [comment]
> @mui/material has a umd package

Which we should have already removed by now but we didn't have the bandwidth. What's your use case?

**Comment by noherczeg** [comment]
> > @mui/material has a umd package
> 
> Which we should have already removed by now but we didn't have the bandwidth.

Please don't remove them! I know that it's not hip any more, but this is a really nice feature of the library.

**Comment by flaviendelangle** [comment]
@oliviertassinari do we have a discussion about this removal ?

Duplicates #3608, let's continue the discussion there
