### ISSUE TITLE
Rename `GridFilterModel['linkOperator']` to `GridFilterModel['logicOperator']` and same for translations

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#7270]
Context: https://github.com/mui/mui-x/pull/3915#discussion_r806044919

**Comment by cherniavskii** [comment]
I think "linkOperator" is more explicit as it has the notion of "linking" multiple filters.

**Comment by kkirsche** [comment]
> I think "linkOperator" is more explicit as it has the notion of "linking" multiple filters.

I would disagree. For me, it implies that it is composable. There can't be multiple operators between filters to do a `((x AND y) or z)` to my knowledge. So it's composing a single large filter, not linking anything per se.

**Comment by cherniavskii** [comment]
The "logicOperator" seems to be more explicit than the generic "operator". I don't think we should aim to map everything to server-side naming or conventions.
For example, MongoDB uses "Logical Query Operators" naming: https://www.mongodb.com/docs/manual/reference/operator/query-logical/

**Comment by kkirsche** [comment]
That's fair.

I don't view it as catering only to server-side as you state, in client-only mode you aren't adding any unique functionality that differs from server-side to say that this is making it about the server-side only.

If you'd like to follow Mongo though, have at it, nothing I will really be able to say to change your thoughts on an opinion-only topic, just weighing in that at least one customer disagrees with this change. 🤷‍♂️

**Comment by cherniavskii** [comment]
Naming things is hard 🙂
The team has already agreed on the `logicOperator`, so we'll proceed with it.
Thanks for sharing your opinion though!

**Comment by kkirsche** [comment]
> Naming things is hard 🙂
> 
> The team has already agreed on the `logicOperator`, so we'll proceed with it.
> 
> Thanks for sharing your opinion though!

Understood and no worries. It is hard to name things. 

As a piece of feedback, I would recommend not justifying the choice with the sunk-cost fallacy. Simply because the team agreed does not increase the validity of the choice.

Thanks for the hard work you all do and hope you have a great weekend.
