### ISSUE TITLE
How to pin checkbox selection column?

### ISSUE THREAD

**Issue by elkins2k** [mui/mui-x#7274]
I'd like the ability to pin the checkboxSelection to the left, but I'm not seeing where/how to do this with x-data-grid-pro.

**Comment by MBilalShafi** [comment]
Hey @elkins2k, can you try this demo: https://mui.com/x/react-data-grid/column-pinning/#pinning-the-checkbox-selection-column

**Comment by elkins2k** [comment]
ACK! How is it I missed this when searching for this EXACT THING? This is why I don't open issues or post things in forums - so I don't look like a buffoon!

**Comment by elkins2k** [comment]
thank you
