### ISSUE TITLE
[DateTimePicker] Fully support Toolbar in landscape mode

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#7279]
### Summary 💡

Follow up of #6900

For consistency, the Toolbar of `DateTimePicker` has been added in landscape mode. However, it's support is still incomplete.

To add:
- Better width to let every date fit in it
- Add AM/PM selector when `ampmInClock` is `false`

**Comment by LukasTy** [comment]
This commit (change) https://github.com/mui/mui-x/pull/8083/commits/a9b1611d02c85997325ee98bc4238640d0d7e959 should be reverted when "`Add AM/PM selector when ampmInClock is false`" is implemented.
