### ISSUE TITLE
[question] Data Grid Restore State Not Restoring Columns dimensions and orderedFields When columnVisibilityModel is Controlled

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#7287]
### Order ID 💳

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Our app has many tables for which we save the state. The state is saved to a database, using the apiRef to export the state:
const gridState = apiRef.current.exportState();
and restored with (we only restore some of it):
 apiRef.current.restoreState({
    columns: gridState.columns,
    pinnedColumns: gridState.pinnedColumns,
    sorting: gridState.sorting,
});
This works for all the previously implemented code, with tables that do not have a controlled columnVisibilityModel. Now we are adding a table where we need to control the columnVisibilityModel. This save/restore does not restore the column dimensions and order in that scenario (it does restore the column visibility and sorting). I am unable to create a code sandbox to show this... Here are the relevant props we are passing to data grid premium:
apiRef={apiRef}
columns={defaultColumns}
columnVisibilityModel={defaultColVisModel}
onColumnVisibilityModelChange={(newModel) => {
    setDefaultColVisModel(newModel);
}}
rows={devices}
// save grid state on the following changes
onColumnOrderChange={!disableGridSaving ? handleGridStateChange : undefined}
onColumnResize={!disableGridSaving ? handleGridStateChange : undefined}
onColumnVisibilityModelChange={(model, details) => {
    if (!disableGridSaving) {
         handleGridStateChange();
    }
    handleColumnVisibilityModelChange(model, details);
}}
onColumnWidthChange={!disableGridSaving ? handleGridStateChange : undefined}
onPinnedColumnsChange={!disableGridSaving ? handleGridStateChange : undefined}
onSortModelChange={!disableGridSaving ? handleGridStateChange : undefined}

For the tables without the controlled columnVisibilityModel, I also pass in:
initialState={{ columns: { columnVisibilityModel: {} } }}
Is there something that I need to pass in for the controlled columnVisibilityModel scenario in order for the column dimensions and order to be restored?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.6
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-data-grid: ^5.13.1 => 5.14.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0
    @mui/x-data-grid-pro:  5.14.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.2
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.14
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript:  4.7.4
```
</details>

**Comment by conerye** [comment]
I will try to create a codesandbox. but if I am not able to, is it possible to share my code in a private forum?

**Comment by conerye** [comment]
I was out on vacation and am back now. I am working on creating a codesandbox. Please reopen, as this is still an issue.

**Comment by conerye** [comment]
I'm having a lot of trouble creating the codesandbox, will share what I have so far...
First, let me explain what we are trying to do... I had previously opened question 7109 about this...
We are developing an app that manages many devices. there is an overview page were a table of the devices is displayed. The table on the overview page contains all columns (20+ columns, though some columns apply only to certain devices)... We would like to allow the user the change the 'view' based on a device type/grouping selection so that type specific data can be displayed in the table (so if only 10 columns apply to the selected type, then a table with those 10 specific columns will be displayed). I tried making the columns a state variable and setting it when the user selected the device type/grouping but this did not work. In online searches, I came across a couple sources that state the column definitions can't change once the component is mounted. So, I implemented it with a table per device type/grouping that can be selected. In the codesandbox linked below, you can see there is the select and a table displayed below it. The table displayed varies with the select value. In this code sandbox, I did not yet get to the part of adding the controlled column visibility, because I first decided to just provide column visibility in the initial state. I had not done that in developing the real code. What I realized, is that the initial state was being ignored(?) and the column visibility is not being stored in the state at all!

https://codesandbox.io/s/practical-ramanujan-03t42z?file=/src/SaveGridState.jsx

Please check it out. Currently, grid state is only being saved for selection = Type 1... So, select Type 1 and change column sizing, order, visibility and pin a column. Change the selection to Type 2 or All and then try clicking Restore Grid state button.

I do realize that this is showing a little different than my initial question but it does sort of demonstrate the issue... I'm thinking there is something wrong with the way I have multiple tables but conditionally render just one at a time?

**Comment by conerye** [comment]
any thoughts on this issue yet?

**Comment by conerye** [comment]
We have changed our design and are no longer controlling the columnVisibilityModel, so I am going to close this.
However, I am still having an issue and have opened a new question (#8678) with a code sandbox to show the problem.

**Comment by claudioctonha** [comment]
I am having this issue too in dataGridPro. I had to use 
`apiRef?.current?.restoreState({
          columns: { dimensions: state.columns.dimensions },
        });`

after restoring the state to restore the dimensions.

But I moved to datagrid premium and now this doesn't work anymore
