### ISSUE TITLE
[docs] Are column groups part of the community or pro license?

### ISSUE THREAD

**Issue by ASchwad** [mui/mui-x#7301]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-data-grid/column-groups/

### Kind of issue

Unclear explanations

### Issue description

The documentation does not mark this feature explicitly as Pro feature, however, regarding the actual package it should be imported from it is included in the Pro package. It is also listed as community feature [here](https://mui.com/x/react-data-grid/demo/)

I noticed the `gridColumnGroupSelector` as an experimental feature in the community package, but it did not yield any results for me so far.

Thanks in advance!

**Comment by alexfauquette** [comment]
It's a community feature.

Effectively, having demonstrations with Data Grid imported from pro package can be confusing.

The reason behind this choice is that to experiment with column grouping, it's nice to be able to resize/reorder columns. It's for the resizing feature that we import from the pro package. Not for column grouping itself

**Comment by ASchwad** [comment]
Thanks for clarifying and your efforts in this powerful library!

Yes, using it actually from the community package could help. Got it working now :)
