### ISSUE TITLE
[data grid] Add component slot for MUI `<IconButton />` component

### ISSUE THREAD

**Issue by 123joshuawu** [mui/mui-x#7312]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As a developer, I want to provide a custom IconButton component in the DataGrid so I can apply custom behavior/styles to all IconButtons in the DataGrid component.

The `BaseButton` component slot allows overriding text buttons. Icon buttons like the filter panel delete button, column header menu button, quick filter input clear button, etc. are implemented using the MUI `IconButton` component. 

Overriding each individual icon allows us to control the style to a certain extent, however the parent `IconButton` component from MUI is imposing interaction behaviors that are difficult to customize. 

Adding a `BaseIconButton` component slot would provide an easy interface for consistent override of the `IconButton` component.

```jsx
<DataGrid 
  ...
  components={{
    BaseIconButton: CustomIconButtonComponent
  }}
  componentsProps={{
    baseIconButton: customIconButtonComponentProps
  }}
/>
```

### Motivation 🔦

We are trying to apply a custom UX design library/component library to the DataGrid component using the base component slots and styles.

**Comment by 123joshuawu** [comment]
A quick search for `<IconButton` in the latest master:

<img width="485" alt="Screen Shot 2022-12-23 at 2 35 29 PM" src="https://user-images.githubusercontent.com/9285017/209410856-a574d408-dcf9-4cc3-92e0-20cc4bd5d013.png">

**Comment by MBilalShafi** [comment]
Thanks for posting the concern @123joshuawu, this could be a helpful customization. Please feel free to open a pull request if you'd like.
