### ISSUE TITLE
[docs] Codesandbox link broken for some demonstrations

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#7325]
The codesandbox link returns an error in [Jalali demonstration](https://next.mui.com/x/react-date-pickers/calendar-systems/#jalali)

> Uncaught TypeError: Can't determine required npm package for adapter 'x-date-pickers'
https://next.mui.com/x/react-date-pickers/calendar-systems/#jalali

**Comment by LukasTy** [comment]
@alexfauquette Could you double-check if this is still an issue?
The problem with Jalali demo has been fixed with https://github.com/mui/mui-x/pull/8006.

**Comment by alexfauquette** [comment]
Yes, seems to be fixed 👌
