### ISSUE TITLE
[data grid] Changing page size updates the starting row for current page

### ISSUE THREAD

**Issue by ygohil2350** [mui/mui-x#7335]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Give Pagination and change page in middle of records 
2.then change pagination again.
3.and check the same record is not at the top.

### Current behavior 😯

its  not 

https://user-images.githubusercontent.com/69479202/209840238-f9b1ed69-badc-4cfb-a728-33c783896dbe.mp4

give the same record will was there on top and from there it should give records per pagination

### Expected behavior 🤔

its should give the same record will was there on top and from there it should give records per pagination

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
If I understand your concern correctly, you would like to change the page size but start the new page from the same row that was previously on top.
That's not the intended behavior of pagination, when you change page size, it keeps the user on the same page with respect to the new page size.

Think of this like working with two variables `page` and `pageSize`.
When clicking twice on the next page with `pageSize=5`, you are now on page 3 with rows 11-15 shown. On changing `pageSize=10`, the grid recalculates the rows for `pageSize=10` and `page=3`and shows rows 21-30.

Can you explain more about your use-case user experience wise, is there a specific reason you want to show the same row on the page size change?

**Comment by ygohil2350** [comment]
Hi @MBilalShafi 
page number is temp variable and its not show to user.
so can we not mange that thing at grid level .

**Comment by yaredtsy** [comment]
hi @ygohil2350 
you can customize the pagination as you want it. if you want the page number to be visible you can override the `Pagination` component with your own pagination component, you can check the example here https://next.mui.com/x/react-data-grid/components/#pagination.
