### ISSUE TITLE
[docs] Missing docs about localizing pickers with `date-fns`

### ISSUE THREAD

**Issue by ericsj** [mui/mui-x#7336]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/pt/x/react-date-pickers/localization/

### Kind of issue

Missing information

### Issue description

The way to translate Datepickers of the docs didn't work for me, I had to search through stackoverflow and ended up finding [this solution](https://stackoverflow.com/questions/51776032/how-can-i-change-material-ui-datepicker-language-and-default-timezone). So [this](https://mui.com/pt/x/react-date-pickers/localization/) page needs some updates (at least for Portuguese language it doesn't work, the month names are not translated)

Date picker version: @mui/x-date-pickers": "^5.0.11"

**Comment by LukasTy** [comment]
Hello @ericsj 

Thank you for opening this issue.
Could you clarify your case with a codesandbox example or specifying, which date library you are using?
Stable (v5) docs are indeed lacking examples for other libraries than `dayjs`, but that is already addressed [in next (v6)](https://next.mui.com/x/react-date-pickers/adapters-locale/). If you think that it is still not clear enough—we'd love to hear feedback. 😉 

> at least for Portuguese language it doesn't work

The documentation pages have no translations. Only API pages do still have translations provided.

**Comment by ericsj** [comment]
I'm not referring to docs translation, I'm referring to translation of the DatePicker component, how to enable translation through code. Code that doesn't worked for me (from the docs, instead of deDE I used ptBr): 
```
import 'dayjs/locale/de';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { DataGrid, deDE as dataGridDeDE } from '@mui/x-data-grid';
import { deDE as coreDeDE } from '@mui/material/locale';
import { CalendarPicker, LocalizationProvider, deDE } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

const theme = createTheme(
  {
    palette: {
      primary: { main: '#1976d2' },
    },
  },
  deDE, // x-date-pickers translations
  dataGridDeDE, // x-data-grid translations
  coreDeDE, // core translations
);

<ThemeProvider theme={theme}>
```
The way I found to translate the month names to portuguese:
...
```
import {
  LocalizationProvider,
  DatePicker as ImportedDatePicker,
} from "@mui/x-date-pickers";
import { Control, Controller } from "react-hook-form";
import { IClientEditableData } from "../../../interfaces";
import { StyledTextField } from "../StyledTextField";
import { ptBR } from "date-fns/locale";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
```
...
```
export const DatePicker = ({ control, label, name }: DatePickerProps) => (
  <Grid item xs={12} sm={6}>
    <LocalizationProvider locale={ptBR} dateAdapter={AdapterDateFns}>
      <Controller
        control={control}
        name={name}
        render={({ field }) => (
          <ImportedDatePicker
            label={label}
            inputFormat="dd/MM/yyyy"
            onChange={(date) => field.onChange(date)}
            value={field.value}
            renderInput={(params) => {
              return <StyledTextField fullWidth {...params} />;
            }}
          />
        )}
      />
    </LocalizationProvider>
  </Grid>
```

**Comment by LukasTy** [comment]
> I'm referring to translation of the DatePicker component, how to enable translation through code. Code that doesn't worked for me (from the docs, instead of deDE I used ptBr):

It seems that the issue you might have had is not knowing that for `date-fns` adapter the imported locale has to be passed down to the localization provider instead of only passing in a string? 🤔 
As I mentioned, in the [next version docs](https://next.mui.com/x/react-date-pickers/adapters-locale/#with-date-fns) we've already addressed this issue by providing examples of how to handle localization using each of the date libraries. 😉

**Comment by ericsj** [comment]
> It seems that the issue you might have had is not knowing that for date-fns adapter the imported locale has to be passed down to the localization provider instead of only passing in a string?
It's not the problem. I went back some commits in my source code so I can show you the broken code. Here it is the source code:
```
import React from "react";
import { Grid, TextField } from "@mui/material";
import { LocalizationProvider, MobileDatePicker } from "@mui/x-date-pickers";
import { Control, Controller } from "react-hook-form";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

type DatePickerProps = {
  control: Control;
  label: string;
  name: string;
};
export const DatePicker = ({ control, label, name }: DatePickerProps) => (
  <Grid item xs={12} sm={6}>
    <LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale="ptBr">
      <Controller
        control={control}
        name={name}
        render={({ field }) => (
          <MobileDatePicker
            label={label}
            inputFormat="MM/DD/YYYY"
            onChange={(date) => field.onChange(date)}
            value={field.value}
            renderInput={(params) => {
              return <TextField margin="normal" size="small" fullWidth {...params} />;
            }}
          />
        )}
      />
    </LocalizationProvider>
  </Grid>
);
```
The theme file:
```
import { createTheme } from "@mui/material/styles";
import { ptBR } from "@mui/material/locale";
import { ptBR as pickersPtBR } from "@mui/x-date-pickers";
import { ptBR as corePtBR } from "@mui/material/locale";

export const theme = createTheme(
  {
    palette: {
      primary: { main: "#1976d2" },
    },
    components: {
      MuiButton: {
        styleOverrides: {
          root: {
            width: "200px",
          },
        },
      },
    },
  },
  ptBR,
  pickersPtBR,
  corePtBR
);
```

How the DatePicker looks:
![calendar](https://user-images.githubusercontent.com/47046552/209955113-6b3198af-5a69-4ea3-a499-92f47d63196b.png)


> As I mentioned, in the [next version docs](https://next.mui.com/x/react-date-pickers/adapters-locale/#with-date-fns) we've already addressed this issue by providing examples of how to handle localization using each of the date libraries. wink
It would be awesome, but it seems there is something wrong with AdapterDayjs

**Comment by LukasTy** [comment]
> It's not the problem.

From the looks of it, it seems that it is the problem.
There are two localisations: 
- date (format) localisation —> handled by the selected date library
- component labels localisation (aria labels for buttons, toolbar buttons and etc.) -> handled by importing the locale from `@mui/x-date-pickers` into the theme or `localeText` prop on `LocalizationProvider` component

In your provided example I don't see you importing the date library locale, which is responsible for the `December` not being localized.

Adding 
```js
import 'dayjs/locale/pt-br';
```
in your `DatePicker` component should solve your issue 🤔

**Comment by ericsj** [comment]
Adding this import line and changing the adapterLocale attribute to "pt-br" made it work. Tks!

**Comment by LukasTy** [comment]
Closing it as the mentioned shortcoming in the docs is going to be addressed when next becomes stable.
