### ISSUE TITLE
[pickers] Date range component

### ISSUE THREAD

**Issue by pzejer** [mui/mui-x#7340]
I'm looking for component which help me to make UI for yacht chartres service.
I want to set up component that in some period of time user can choose only weeks (from saturday to saturday) and in other period only days (as many as wishes).
Is it possible to make it via this component ?

**Comment by LukasTy** [comment]
Hello @pzejer 

Could you clarify your request? Do you need the ability to allow user selecting some date range as well as some other dates on top of that? Something like this? If yes, there is no option to do it out of the box, you'd need to your logic on top of existing day component logic.
![Screenshot 2022-12-30 at 15 53 07](https://user-images.githubusercontent.com/4941090/210131983-27b623d6-4121-4e42-8946-c14c88ee0ea4.png)

Or do you simply need to disable different dates (not allow their selection) depending on certain criteria? If this is the case, then consider reaching for [shouldDIsableDate](https://mui.com/x/api/date-pickers/date-range-picker/#:~:text=aria%2Dlabel%20text.-,shouldDisableDate,-func) function. 😉

**Comment by flaviendelangle** [comment]
For the 1st point, `DayPicker` could easily be tweaked to handle it, but it is a private component for now.
