### ISSUE TITLE
[data grid] Changing `rows` causes triple rerender

### ISSUE THREAD

**Issue by GideonMax** [mui/mui-x#7366]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/mui-x-issue-template-forked-y3iu74?file=/src/App.tsx
Steps:
1. press `Open In New Window` (button in the sandbox's toolbar)
2. in devtools open the performance tab and start recording
3. press the `current set` button (it will switch between sets of rows)
4. after you stop recording, you will notice 3 large tasks (rerenders) per time you switch sets, on good computers you might need to throttle your cpu (through the performance tab) to see the tasks.
I personally validated that each task really is a rerender by making a local copy and modifying the node modules to log rerenders (something I can't do in code-sandbox), each of those tasks is a rerender of the datagrid

### Current behavior 😯

Datagrid rerenders 3 times.

### Expected behavior 🤔

only one rerender

### Context 🔦

We've encountered this issue when trying to filter the input data.
Due to certain constraints, we can't use the filters provided by the data grid and must provide filtered data to the data grid.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
  npmPackages:
    @emotion/react:  11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.112
    @mui/core-downloads-tracker:  5.11.2
    @mui/material: ^5.11.2 => 5.11.2
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.2
    @mui/types:  7.2.3
    @mui/utils:  5.11.2
    @mui/x-data-grid: ^5.17.17 => 5.17.17
    @types/react: ^18.0.26 => 18.0.26
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.4 => 4.9.4
</details>
I used Chrome Version 108.0.5359.125, which for a reason unknown to me, is being reported as "not found".

**Comment by cherniavskii** [comment]
Hey @GideonMax 
Is there a specific issue you're having with the `rows` prop change?

Note that when you change the `rows` prop, there are multiple internal grid state changes (for filtering, sorting, row height, etc.). Multiple rerenders are expected in this case.

**Comment by GideonMax** [comment]
> Note that when you change the `rows` prop, there are multiple internal grid state changes (for filtering, sorting, row height, etc.). Multiple rerenders are expected in this case.

I know, but it still causes horrible performance issues.
Also, those multiple state changes could be done on one single rerender if batched correctly.

**Comment by flaviendelangle** [comment]
The 3rd render is caused by a single `setState` inside `useGridRowsMeta`, we should be able to improve it by listening to events instead of using an `useEffect`.

For the two remaining renders, we have the one caused by the `props` update then the one caused by the `state` update (in your example we update the `rows` / `filter` / `sorting` sub-states).
We are not moving very fast on it, but at some point our state should be an actual React state to allow using `React.memo` and skip the rendering of the cells during the 1st render of the grid when the rows changes (since we don't have the state yet).

**Comment by cherniavskii** [comment]
We can check if there are places where `forceUpdate` is called unnecessarily.
We should batch the state updates as much as possible.

**Comment by romgrk** [comment]
We've done a lot of optimization on rerendering, @GideonMax could you confirm if you're still seeing this issue with the latest version? Here is the flamecharts I get for the current version for your codesandbox. It runs in about 125ms, which seems acceptable considering codesandbox runs in dev mode (where react does a ton of JSX checking & validation):

![Image](https://github.com/user-attachments/assets/d7f7ea93-5323-462b-b084-333b092afdd5)
