### ISSUE TITLE
Please consider adding the ability to pass variables in the <Datagrid  /> component tag 

### ISSUE THREAD

**Issue by Birddle** [mui/mui-x#7377]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Since I want to add the action after selection in GridHeader, I am following the tutorial to try to put them together:
https://mui.com/x/react-data-grid/selection/#controlled-selection
https://mui.com/x/react-data-grid/column-visibility/#column-visibility-panel
I believe this is a very common and universal requirement. When I select a row or rows, I can't pass the resulting data to the GridToolbar subcomponent. It seems that it does not support passing properties.

### Examples 🌈
```
export defualt function App(props: any){
    const {rows, columns} = props;
    const [selectionModel, setSelectionModel] = useState<GridSelectionModel>([]);
    return (
      <DataGrid components={{ Toolbar: DataToolbar }}
         onSelectionModelChange={(newSelectionModel) => {
                    setSelectionModel(newSelectionModel);
                }}
         selectionModel={selectionModel} 
         {...others} />
    );
}

function DataToolbar (){
    <GridToolbarContainer>    
        <Auctions />               
        <GridToolbarQuickFilter />             
        <GridToolbarColumnsButton />           
        <GridToolbarDensitySelector />
    </GridToolbarContainer>
}
function Auctions (){
    const apiRef = useGridApiContext();
    const [selected, setSelected] = useState(false);
    const handleSelected: GridEventListener<'rowSelectionCheckboxChange'> = (
        params, event, details) => {
        //Processing Event
        setSelected(!selected);
    };
    useGridApiEventHandler(apiRef, 'rowSelectionCheckboxChange', handleSelected);
    return (
        <Fragment>           
            <IconButton disabled={!selected}><DeleteIcon color={selected? "error" : "disabled"} /></IconButton>
        </Fragment>
    );
}
```

**Comment by cherniavskii** [comment]
Hey @Birddle 
You can pass props to the Toolbar component using `componentsProps`:

```tsx
<DataGrid
  rows={rows}
  columns={columns}
  components={{
    Toolbar: GridToolbar,
  }}
  componentsProps={{
    toolbar: { showSelectionAction: true },
  }}
/>
```
See https://mui.com/x/react-data-grid/components/#overriding-components

Is this what you're looking for?

**Comment by Birddle** [comment]
> 

Hi @cherniavskii ,

Thank you for help. To better describe this requirement, I added an example. How to pass the selectionModel to the Auctions component this is what I need.
The toolbar that comes with the MUI is more oriented towards manipulating the dataset as a whole, while the functionality I wanted to add was for manipulating specific rows. I believe this is a very common requirement.

**Comment by cherniavskii** [comment]
Once you pass the props to the toolbar, it's up to you what to do with them. You can pass the props to the `Auctions` component.
See this demo: https://codesandbox.io/s/sleepy-lehmann-vgvlq8?file=/demo.tsx

**Comment by cherniavskii** [comment]
I'm closing the issue since there are no actions needed on our side.
