### ISSUE TITLE
TypeError: date.getFullYear is not a function     at excelSerializer.js:125:1

### ISSUE THREAD

**Issue by arifannosh** [mui/mui-x#7391]
### Order ID 💳

54600

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

the issue with exporting Excel 
when I try to export data as Excel nothing happens and it gives a console error for a date or DateTime field. value of the date field is a **string** and it's not a **date/DateTime object.**
plz, suggest a solution or you have to fix that issue like adding another conduction to check dataType also.
![muidateTimeError](https://user-images.githubusercontent.com/35531768/210722567-ce598ba0-d8eb-4034-baf6-3fa64713c710.PNG)

### Your environment 🌎

<details>
  "@mui/x-data-grid-premium": "^5.17.13",
  npm 6.14.15

```
 chrome
```
</details>

**Comment by cherniavskii** [comment]
Hey @arifannosh 
> value of the date field is a string and it's not a date/DateTime object

You should pass a `Date` object to `date`/`dateTime` column values.
Then the Excel export works correctly - see https://mui.com/x/react-data-grid/export/#excel-export
Alternatively, you can use `valueGetter` to convert the value to the correct type: https://mui.com/x/react-data-grid/column-definition/#converting-types

**Comment by arifannosh** [comment]
@cherniavskii  yes, I know its works fine when a pass Date object is in the date column . but when I pass it as a string it works fine everywhere Only creates an issue for exporting excel .
why not add only one check for type also in this Case

**Comment by cherniavskii** [comment]
I looked into it and it looks like string values are supported intentionally, for example here: https://github.com/mui/mui-x/blob/1f244b9ddaac51764169376b68b2ab0def35fab9/packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx#L79

So it makes sense to also support it in excel serializer

**Comment by arifannosh** [comment]
@cherniavskii when it will merge into the master branch

**Comment by cherniavskii** [comment]
@arifannosh I'll backport it to the `master` branch once it's merged into the `next` branch

**Comment by arifannosh** [comment]
@cherniavskii sounds good, but its almost 4 working days, and I'm still  waiting

**Comment by cherniavskii** [comment]
You can use this workaround until it's merged and released: https://github.com/mui/mui-x/issues/7391#issuecomment-1372081865

**Comment by arifannosh** [comment]
@cherniavskii is merged into next when it is released ?

**Comment by cherniavskii** [comment]
We'll release it today

**Comment by arifannosh** [comment]
Does it still not release? @cherniavskii

**Comment by cherniavskii** [comment]
v5 was released today: https://github.com/mui/mui-x/releases/tag/v5.17.19
