### ISSUE TITLE
[data grid] Hideable column property is not honored with columnVisibilityModel

### ISSUE THREAD

**Issue by Arkamit** [mui/mui-x#7393]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/practical-frost-wp2ttc?file=/demo.tsx

Steps:

1. Within a set of columns, add one column as hideable: false and hide: true. This will make the column hidden and cannot be toggled to unhide.
2. Set the initialState of DataGrid and initialize columnVisibilityModel.
3. Now finally click on the Show All columns under the Columns option.

### Current behavior 😯

The column which is set to hideable to false is visible in the table and on Hide All, it still remains there. In other words, the hideable property is not honored when Show All is executed.

### Expected behavior 🤔

The column where the property is set to hideable: false and hide: true, should not become visible when Show All is clicked. Rather it should be skipped since the hideable property is set to false and it is not possible to manually toggle it.

### Context 🔦

Although I'm not sure but looking into the below code might be helpful.

[toggleAllColumns](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx#L139)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browser: Google Chrome (108.0.5359.125)
System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 AMD EPYC 7571
    Memory: 12.17 GB / 15.52 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Managers:
    pip2: 18.0 - /usr/bin/pip2
    pip3: 20.2.2 - /usr/bin/pip3
    Yum: 3.4.3 - /usr/bin/yum
  Utilities:
    Make: 3.82 - /usr/bin/make
    Git: 2.32.0 - /usr/bin/git
  Virtualization:
    Docker: 20.10.13 - /usr/bin/docker
  IDEs:
    Nano: 2.9.8 - /usr/bin/nano
    VSCode: 1.74.2 - /home/adutta@huronconsultinggroup.com/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/remote-cli/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.7.10 - /usr/bin/python3
  Databases:
    SQLite: 3.7.17 - /usr/bin/sqlite3
```
</details>

**Comment by Arkamit** [comment]
@cherniavskii Thanks for explaining it more simply. I also do think that the Show All and Hide All functions should skip the columns for which hideable: false is set.

@sadiki-o I do understand you point but there might be a need to have the column but its property is set to hideable: false and when Show All is clicked it should not be shown in any case. @cherniavskii have explained it wonderfully.

**Comment by kkirsche** [comment]
Potentially a subtle message in the Columns dropdown menu before it's closed or a prop that would allow us to feed a message in. If using a default message, maybe something like "Not all columns could be hidden because their configuration prevents it".

If going the prop route, I'd have it be something like a `hiddenPreventedMessage?: string` and with undefined the existing behavior continues and if the prop is provided than an alert is displayed. This helps downstream devs from avoiding the need to extend various internal components and replace the defaults simply for a user-facing message

**Comment by Arkamit** [comment]
@kkirsche Thanks for sharing this idea but my concern is that the column is already hidden and is in a disabled state such that manually it won't be possible for anyone to show it. My idea was that if the Show All button just skips this kind of columns then it would work as expected. As of now Hide All does the same thing but the other way round i.e. when a person clicks on Hide All then it checks if there are any columns with hideable: false then it skips it. We just some how need to replicate this same logic in Show All where it will skip the columns with hideable: false and doesn't make it visible.

Hope I was able to explain it properly.
