### ISSUE TITLE
Data Grid Pro height property issue causing problems with row rendering

### ISSUE THREAD

**Issue by clarkOake13** [mui/mui-x#7398]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Please note, this issue is inconsistent despite being implemented the same way across our production application.

We use several instances of the data grid throughout our app, mostly in administrative views for displaying multiple rows which represent things like orders, products, users, etc. We have followed the guidelines in the documentation to ensure that the grid is rendered with a height value provided by a parent container, however, we occasionally get warnings that this height value isn't being applied. Further to the issue of getting these warnings, we also experience an intermittent issue where the grid will successfully render, but only display a portion of the available rows until a scroll event is triggered, at which time it will render the remaining rows after flashing once or twice.

### Expected behavior 🤔

We would expect the Data Grid pro to reliably receive a height value from the parent div and properly render all available rows each time without issue, as this is what is outlined in the docs and seems to be resolved within the Mui-core base component according to this ticket: [Issue](https://github.com/mui/mui-x/issues/1825)

### Context 🔦

As previously mentioned, we use several instances of the Data Grid throughout our app for displaying bulk data. The Data Grid Pro works great and has a ton of awesome features, unfortunately, this issue has some pretty severe impact on usability and we would love to see a solution implemented

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.18.0 - ~\Documents\GitHub\broadside\node_modules\.bin\npm.CMD
  Browsers:
--> Not sure why this is showing that Chrome isn't installed on my machine. Issue is present in Chrome
--> Chrome Version(Version 108.0.5359.125 (Official Build) (64-bit))
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)

</details>

### Order ID 💳 (optional)

54082

**Comment by cherniavskii** [comment]
Hey @clarkOake13 
This sounds similar to https://github.com/mui/mui-x/issues/5987
We've released a fix today in https://github.com/mui/mui-x/releases/tag/v5.17.18

Could you check if it solves the issue you're facing? Thanks!

**Comment by clarkOake13** [comment]
Updating to version 5.17.18 of Mui-x has resolved this issue for us! I am marking this ticket as resolved, thanks for your help @cherniavskii

**Comment by cherniavskii** [comment]
@clarkOake13 Great!
