### ISSUE TITLE
[DataGridPro] Print

### ISSUE THREAD

**Issue by younusrahman2022** [mui/mui-x#7400]
### Order ID 💳

MUI 3320221249

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello,
         I have purchased a pro license from ATEA which in turn was purchased via Softmizer.

- https://github.com/mui/mui-x/issues/7402

- https://github.com/mui/mui-x/issues/7403

- https://github.com/mui/mui-x/issues/7404 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @younusrahman2022 
I've extracted the issues you mentioned into separate issues and updated the description linking to them since it's easier to track them like that.

**Comment by cherniavskii** [comment]
I'm closing this issue since we now have separate issues

**Comment by younusrahman2022** [comment]
Thanks @cherniavskii
