### ISSUE TITLE
DataGrid Pro watermark appearing in production environment

### ISSUE THREAD

**Issue by ranzis** [mui/mui-x#7409]
### Order ID 💳

55617

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

.

We have purchased a license for DataGrid Pro and have been using it successfully in our local environment without any issues. However, when we deploy it to preprod/prod, the watermark appears.
Could you please provide assistance in troubleshooting this issue and helping us to use DataGrid Pro in our production environment without the watermark?

Thank you in advance for your help.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by joserodolfofreitas** [comment]
Could it be related to https://github.com/mui/mui-x/issues/3969?

**Comment by ranzis** [comment]
@cherniavskii  Thank you for your response 
1. I don't get any errors: not "Missing license key" or "Invalid license key".  ( in opposite to local env where i am getting errors if the key is not valid )  
The way I am getting the license key is similar to this:  LicenseInfo.setLicenseKey(process.env.REACT_APP_MATERIAL_KEY) before the loading of the app component ( like in the example)
2. The data grid package version is : 5.17.14

**Comment by ranzis** [comment]
@joserodolfofreitas  I think it is similar in some aspect (I am using Datagrid and not a date picker). I didn't see any solutions for that.

**Comment by cherniavskii** [comment]
@ranzis 
> I don't get any errors: not "Missing license key" or "Invalid license key". 

But you do see the watermark, right? What does it say? Here's an example:
<img width="434" alt="Screenshot 2023-01-06 at 18 07 10" src="https://user-images.githubusercontent.com/13808724/211061971-21d07856-a406-4e44-926f-671a15945586.png">

**Comment by ranzis** [comment]
@cherniavskii  I am getting: Missing license key

![image](https://user-images.githubusercontent.com/10484008/211062451-5a0d96ba-6f9a-44bc-9eea-c7a4cd864c05.png)

**Comment by cherniavskii** [comment]
Could you double-check if the `REACT_APP_MATERIAL_KEY` env variable is defined in the production environment?

**Comment by ranzis** [comment]
@cherniavskii  I will check it again and will update you if it solved the problem or if there is another issue with that.
