### ISSUE TITLE
[DataGridPremium] Print export customization

### ISSUE THREAD

**Issue by zunaid2998** [mui/mui-x#7411]
### Order ID 💳

48138

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Issue 1:
While printing, When the contents span over multiple pages, can we display the column names on each page ? Its standard behaviour that currently we are not getting.
https://stackblitz.com/run?file=demo.tsx

Issue 2:
When we have lesser number of columns, while printing, we have to make the columns take up the full width of the table. Right now, the look and feel is not so great when printing a grid with 3 columns
https://stackblitz.com/run?file=demo.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 12.5
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Edge: Not Found
    Firefox: 95.0.2
    Safari: 15.6
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.79
    @mui/envinfo: ^2.0.6 => 2.0.6
    @mui/icons-material: ^5.6.1 => 5.6.2
    @mui/material: ^5.6.1 => 5.6.4
    @mui/private-theming:  5.6.2
    @mui/styled-engine:  5.6.1
    @mui/styles: ^5.6.1 => 5.6.2
    @mui/system:  5.6.4
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-data-grid:  5.15.1
    @mui/x-data-grid-premium: ^5.15.1 => 5.15.1
    @mui/x-data-grid-pro:  5.15.1
    @mui/x-date-pickers: ^5.0.0-alpha.2 => 5.0.0-alpha.2
    @mui/x-license-pro: ^5.15.0 => 5.15.0
    @types/react: 17.0.2 => 17.0.2
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.6.3 => 4.6.4

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Hi @zunaid2998, thanks for raising the issue, the stackblitz links provided with the description seem to be broken, can you update with the working live examples?

**Comment by zunaid2998** [comment]
@MBilalShafi 
For some reason, the stackblitz link is re-routing to the homepage.
Anyway, same link can be found in the MUI Export documentation page- https://mui.com/x/react-data-grid/export/
You can consider the first example and then try 'export' -> 'print'
In issue 1, When the table contents span over multiple pages, can we display the column header names on each page ?
In issue 2, Can we make the columns take up the full width of the table ?

**Comment by zunaid2998** [comment]
@MBilalShafi Any update on the above mentioned issues ?

**Comment by zunaid2998** [comment]
@MBilalShafi Hey! any update on the above issues mentioned ?
We figured out an workaround for issue 2. But for issue 1, we are still looking for any help you guys can provide ?
thanks!

**Comment by cherniavskii** [comment]
Hey @zunaid2998
