### ISSUE TITLE
[data grid premium] How to pin a column that is using row grouping?

### ISSUE THREAD

**Issue by karaholinski** [mui/mui-x#7412]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹
    const initialState = useKeepGroupedColumnsHidden({
          apiRef,
          initialState: {
          rowGrouping: {
              model: ['classification'],
          },
          aggregation: {
              model: getColMonths()[0],
          },
          },
    });

      <DataGridPremium
        rows={rowData}
        apiRef={apiRef}
        columns={overallColumns.concat(getColMonths()[1])}
        disableSelectionOnClick
        initialState={initialState}
        experimentalFeatures={{ aggregation: true }}
       pinnedColumns={{
            left: ['category', 'reason'],
        }}
      />

### Current behavior 😯

Reason will pin but category will not pin because category has rowGrouping enabled

### Expected behavior 🤔

Classification and reason should pin

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
You need to use `GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD` constant to pin a rowGrouped column.

```tsx
<DataGridPremium
  {...data}
  initialState={{
    rowGrouping: {
      model: ["category"]
    },
    pinnedColumns: { left: [GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD] }
  }}
/>
```

The same will hold true for controlled models.

I guess we can improve documentation in this area.

**Comment by karaholinski** [comment]
Thank you! Works great 👍
