### ISSUE TITLE
[question] Using `DateRangePicker` without `renderInput`

### ISSUE THREAD

**Issue by noghartt** [mui/mui-x#7413]
### Order ID 💳

49216

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to use the `DateRangerPicker` with an `Autocomplete` option, but seems to be a required prop the `renderInput` of this component.

Is there any way where could I use only the `DateRangerPicker` modal to select a range of dates?

**Comment by LukasTy** [comment]
Hello @noghartt 
Have you tried using [Static mode](https://mui.com/x/react-date-pickers/date-range-picker/#static-mode)?
It does still require `renderInput` prop as it's used to render the inputs when toolbar is shown and the edit button is clicked in it.

**Comment by noghartt** [comment]
> In v6, it should be fairly easy to override the field with an `Autocomplete`. In v5, the static pickers are probably the way to go.

Hmm, any idea about how could I override the field with an `Autocomplete` in this case? It's because I have some dynamics value inside the `Autocomplete` options + `customized` option per se.
