### ISSUE TITLE
[data grid] Won't build when using actions

### ISSUE THREAD

**Issue by wills01** [mui/mui-x#7415]
if i use the following

`    const columns = React.useMemo(
        () => [
            { field: 'avatar', headerName: '', width: 20, editable: false },
            { field: 'name', headerName: 'Name', flex: 1, minWidth: 180, editable: false },
            {
                field: 'grouprole', type: 'singleSelect', headerName: 'Role', width: 150, valueOptions: [
                    'Member',
                    'Admin',
                ], editable: true
            },
            {
                field: 'actions',
                type: 'actions',
                width: 80,
                getActions: (params: { id: string; }) => { <GridActionsCellItem label='Delete' icon={<DeleteIcon />} onClick={deleteUser(params.id)} showInMenu={false} /> }
            },
        ],
        [deleteUser],
    );`

i get the following error:

`/src/sections/group/groupmembersadmin.tsx:229:61
Type error: Type '{ label: string; icon: Element; onClick: () => void; showInMenu: false; }' is not assignable to type 'IntrinsicAttributes & ((Pick<{ label: string; icon?: ReactElement<any, string | JSXElementConstructor<any>> | undefined; } & ... 4 more ... & Omit<...>, "name" | ... 283 more ... | "showInMenu"> | Pick<...>) & RefAttributes<...>)'.
  Type '{ label: string; icon: Element; onClick: () => void; showInMenu: false; }' is missing the following properties from type 'Pick<{ label: string; icon?: ReactElement<any, string | JSXElementConstructor<any>> | undefined; } & { showInMenu?: false | undefined; icon: ReactElement<...>; } & { ...; } & Omit<...> & CommonProps & Omit<...>, "name" | ... 283 more ... | "showInMenu">': nonce, onResize, onResizeCapture

  227 |                 type: 'actions',
  228 |                 width: 80,
> 229 |                 getActions: (params: { id: string; }) => { <GridActionsCellItem label='Delete' icon={<AddIcon />} onClick={deleteUser(params.id)} showInMenu={false} /> }
      |                                                             ^
  230 |             },
  231 |         ],
  232 |         [deleteUser],`

if i omit the field 'actions' all builds ok

Using Typescript 4 and React 18 and MUI-X v6 (but problem persists with v5

**Comment by MBilalShafi** [comment]
`getActions` function must return an array of actions, you are providing an object instead. Refer to this [documentation](https://mui.com/x/react-data-grid/column-definition/#special-properties) link to know more about it.

I was able to update your example and get it running in this [live example](https://codesandbox.io/s/gifted-resonance-ty9nx8?file=/demo.tsx).

**Comment by wills01** [comment]
So changed this. Still get the error. but is apparent in 5.17.18, but works fine in 5.17.11. It is a build error, when i "npm run dev" it works, in both cases its a Type error

**Comment by BrentFarese** [comment]
I can confirm that I get this same type error on 5.17.24.  I believe this is still an open issue/bug.

**Comment by BrentFarese** [comment]
I can also confirm as @wills01 said that it works fine on `5.17.11` but upgrading beyond that version causes a type error.
