### ISSUE TITLE
Unable to render row data in MUIX Data Grid

### ISSUE THREAD

**Issue by Swarupa567** [mui/mui-x#7417]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

### Current behavior 😯

 I have started implementing a data grid (Mui-x-Datagrid)  for developing a financial admin dashboard. we are fetching the data from API and constructing the dynamic column headers(only a few columns have to be shown based on the condition) and row data. I'm able to render the column data and while rendering row Data, it is not showing any row data or row data is empty If I use the renderCell property, it is showing the same row data for all the columns. Can I render the row data specific to column headers by using any GridProps?

### Expected behavior 🤔

I need to render the row data specific to column headers.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
I am not able to understand your context well, can you provide a live example where the issue could be reproduced?
You can use this [codesandbox](https://codesandbox.io/s/gracious-dhawan-p3eb4e) as a starting point.

**Comment by Swarupa567** [comment]
Below is the screenshot of datagrid we have implemented till now
![image](https://user-images.githubusercontent.com/22514881/211244205-fa0488dd-0a95-4771-a63c-a8e9e23cbead.png)

I have linked the https://codesandbox.io/s/admiring-alex-t8xyom?file=/demo.tsx codesandbox with the APiData, we are using it to render the data in dataGrid.
