### ISSUE TITLE
[pickers] Hydration crash

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#7439]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open http://0.0.0.0:3001/x/react-date-pickers/date-picker/

### Current behavior 😯

<img width="1164" alt="Screenshot 2023-01-08 at 16 54 23" src="https://user-images.githubusercontent.com/3165635/211206328-0f2a9fc4-ca24-4654-b940-250dad29a0c5.png">

### Expected behavior 🤔

No errors

### Context 🔦

I'm working on the mobile experience. It's different from #5856. This time, it's not the time that changes. It fails in localhost and with the id.

### Your environment 🌎

v6.0.0-alpha.14

**Comment by flaviendelangle** [comment]
I could not reproduce your error
Could you check that you have the latest version and say if you are using the dev or the production doc ?

**Comment by oliviertassinari** [comment]
I can reproduce it on this page from HEAD (ad24863662f029319d0f03f3dec5e81c054b21c3) http://0.0.0.0:3001/x/react-date-pickers/base-concepts/

<img width="1167" alt="Screenshot 2023-01-27 at 16 05 57" src="https://user-images.githubusercontent.com/3165635/215118864-801c0277-4c8c-4eef-8f55-2fbd51aa6e64.png">
