### ISSUE TITLE
[data grid] is there a way to format numbers(with comma) in pagination?

### ISSUE THREAD

**Issue by NareshMurthy** [mui/mui-x#7457]
### Order ID 💳

56539

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a data grid pro, and I am trying to add commas,i.e. format the numbers in the datagrid pagination, attached snip below
trying to change  `1-100 of 5749854`  to  `1-100 of 5,749,854`.
Is there a way to do this, i have tried custom pagination component, and no luck yet.

<img width="267" alt="Screenshot 2023-01-09 at 9 42 41 PM" src="https://user-images.githubusercontent.com/29588037/211480751-447d9250-338a-4a07-8b40-a7bcb2cf9693.png">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

Yes, you can override the label like [on this example](https://codesandbox.io/s/data-grid-community-forked-bmp6nw?file=/src/App.tsx)

@mnajdova would it make sense to change the default label to correctly support long numbers like this ?
Or would it cause issues with SSR ?

**Comment by NareshMurthy** [comment]
Thanks @flaviendelangle

**Comment by mnajdova** [comment]
> @mnajdova would it make sense to change the default label to correctly support long numbers like this? Or would it cause issues with SSR?

@flaviendelangle have you seen a lots of requests for this? We could create an issue with "waiting for upvotes" label and decide based on that.

**Comment by flaviendelangle** [comment]
No, it's the first feedback I noticed :+1:
