### ISSUE TITLE
How can i get data in Autocomplete ? 

### ISSUE THREAD

**Issue by fdurna** [mui/mui-x#7479]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

My Autocomplete there is here.

![image](https://user-images.githubusercontent.com/15355851/211920858-5e68d6af-0902-4c51-b673-dffc7e695b64.png)

and UI is here

![image](https://user-images.githubusercontent.com/15355851/211921050-37520ed6-0534-48b8-a7b1-b49943e21050.png)

I want when i click Save button , not coming here (console.log(data)), and my selections to come as an array

![image](https://user-images.githubusercontent.com/15355851/211921244-a542b6f3-279f-4131-acc7-5ff8d268b794.png)

Could you help me please ? @m4theushw

**Comment by DanailH** [comment]
Hi, @fdurna Unfortunately it looks that this is the wrong place to open this ticket. Unless your issue is related to the DataGrid or any of the Pickers components you need to ask in the https://github.com/mui/material-ui repo.
