### ISSUE TITLE
[DatePicker] `defaultCalendarMonth` does not work for `year` and `month` views

### ISSUE THREAD

**Issue by sam-woodridge** [mui/mui-x#7480]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-datepicker-view-issue-l1kkpd?file=/src/App.tsx

Steps:
1. Create a `DatePicker` that opens to the `year` or `month` view
2. Give it a `defaultCalendarMonth` date other than today
3. Open the DatePicker UI

### Current behavior 😯

The DatePicker year or month view will show the date from the `defaultCalendarMonth`, but the year or month selection defaults to today's year/month:

Example:
Current date is January 11, 2023. 
Set `defaultCalendarMonth` to `dayjs('2012-03-23')`

Opening to `year` view, label shows correct month/year (March 2012), but default selection is current year (2023):
<img width="320" alt="Screenshot 2023-01-11 at 1 27 10 PM" src="https://user-images.githubusercontent.com/69694651/211927416-bd223df0-cb1d-4135-8675-752329b5b96c.png">

Opening to `month` view, label shows correct month/year (March 2012), but default selection is current month (January):
<img width="323" alt="Screenshot 2023-01-11 at 1 27 32 PM" src="https://user-images.githubusercontent.com/69694651/211927136-c7352df4-89df-434f-8793-b82b808ca2b5.png">

### Expected behavior 🤔

The year and month views default to the correct year/month selection supplied by `defaultCalendarMonth`.

### Context 🔦

I would like to have the DatePicker use the year and month views, but be able to control which specific year/month is selected by default when the user has not yet filled out the input. This is based on a business requirement to default the year to something in the past for a birthday field.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Browser: Chrome

```
System:
    OS: macOS 13.1
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Edge: Not Found
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.98 
    @mui/core-downloads-tracker:  5.10.6 
    @mui/material: ^5.10.6 => 5.10.6 
    @mui/private-theming:  5.10.6 
    @mui/styled-engine:  5.10.6 
    @mui/system:  5.10.6 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.6 
    @mui/x-date-pickers: ^5.0.10 => 5.0.10 
    @types/react: ^18.0.0 => 18.0.17 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.4.2 => 4.7.4 
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #5702
