### ISSUE TITLE
return initialFocusedDate to set default date in MUI-X MobileDatePicker

### ISSUE THREAD

**Issue by sohaibnajjar** [mui/mui-x#7499]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

in our system we migrate from using { DatePicker, DatePickerProps } from "material-ui-pickers-mui5" 
to use { MobileDatePicker, MobileDatePickerProps } from "@mui/x-date-pickers"

### Examples 🌈

  import { DatePicker, DatePickerProps, MuiPickersUtilsProvider } from "material-ui-pickers-mui5";

<MuiPickersUtilsProvider utils={overrideMomentUtils}>
        <div className={classes.root} data-testid="ISEDatePicker">
          <DatePicker
            {...datePickerProps}
            onChange={this.handleDatePickerChange}
            value={this.getSelectedDate()}
            renderDay={this.renderDay}
            rightArrowIcon={this.rightArrow}
            leftArrowIcon={this.leftArrow}
            variant="static"
            initialFocusedDate={moment().add(1, "day")}
          />
      </MuiPickersUtilsProvider>

### Motivation 🔦

we have a property called `initialFocusedDate`, I tried to use it and there is no property like that in the new MUI-X date pickers.

how can I set an `initial date` for the new MUI-X date pickers?

**Comment by flaviendelangle** [comment]
Duplicates #issues
