### ISSUE TITLE
[DataGrid] How to hide grouped column from visible columns panel

### ISSUE THREAD

**Issue by toinhao1** [mui/mui-x#7534]
### Order ID 💳

46557

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is it possible to hide the hidden column of a grouped column?
![Screenshot 2023-01-13 at 14 02 40](https://user-images.githubusercontent.com/41380451/212326285-41b1e3dc-f74a-43c4-a631-492b55cd14e0.png)

We have a column grouped by default, asset class. We use the useKeepGroupedColumnsHidden hook like this: 

```
const initialState = useKeepGroupedColumnsHidden({
    apiRef,
    initialState: {
      rowGrouping: {
        model: ['grouping'],
      },
    },
  });
```

Which hides the column from the table, but it is still available for a user to unhide via the columns visibility menu.

Ideally, the option would not be there in the columns visibility menu and then if a user stops grouping then it would revert to being in the table.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by toinhao1** [comment]
Yes, but we want it hidden and Removed from this panel.

But it is not possible, okay, thanks.

**Comment by cherniavskii** [comment]
This was also requested in https://github.com/mui/mui-x/issues/6641#issuecomment-1398694661

We can make it customizable through a function that would return a list of columns/column fields that should be rendered in the columns panel.

**Comment by xdebbie** [comment]
I was looking for the same thing -- I would like to completely hide the 'actions' and the '__detail_panel_toggle__' columns. It would be very nice if we could have a prop that would allow us to select certain columns to be completely hidden on this panel. Right now all I can is to find a css workaround

![Screenshot 2023-03-08 at 18 03 01](https://user-images.githubusercontent.com/57162213/223780529-782665a3-b669-4dc1-a56f-9f42d351506b.png)

**Comment by xdebbie** [comment]
In case someone ends up in this thread looking for how to hide the columns from the panel with CSS, this is my workaround:

```typescript
type PropTypes<T> = {
  // ... Your props here
  // Define how many columns to hide from the columns panel, starting from the last one
  hideColumnsPanel?: number;
};

export default function DataGrid<T extends object>({ hideColumnsPanel }: PropTypes<T>) {
  return (
    <DataGrid
      // ... Your props
      components={{
        Toolbar: GridToolbar
      }}
      componentsProps={{
        panel: {
          sx: {
            '& .MuiDataGrid-columnsPanel': {
              [`div:nth-last-of-type(-n+${hideColumnsPanel})`]: {
                display: 'none'
              }
            }
          }
        }
      }}
    />
  );
}

```

I used a prop here to pass the number of columns I want to hide starting from the last column, but ofc you can also just input the number directly if your DataGrid is not a reusable component. In my example, I used the number `2` because I wanted to hide the 2 last columns.

![Screenshot 2023-03-10 at 20 04 31](https://user-images.githubusercontent.com/57162213/224404158-2ec45d9a-9c2b-4194-be8f-89e1dc60ac39.png)

**Comment by MBilalShafi** [comment]
@xdebbie Just a heads up - we recently [added](https://github.com/mui/mui-x/pull/8401) a new callback `getTogglableColumns`  to the `ColumnsPanel` to handle this use-case, it should be available in the next release. 🎉 

I am curious though about your expectation when the user presses the `Hide all` or `Show all` buttons, do you expect these buttons to honor the `getTogglableColumns` callback i.e. not toggle status of columns that are not returned by `getTogglableColumns` or behave like what it is today?
Context: https://github.com/mui/mui-x/pull/8496

**Comment by cpolanish** [comment]
> I am curious though about your expectation when the user presses the `Hide all` or `Show all` buttons, do you expect these buttons to honor the `getTogglableColumns` callback i.e. not toggle status of columns that are not returned by `getTogglableColumns` or behave like what it is today? Context: #8496

@MBilalShafi just to add my own two cents, I know in my use case, I have a handful of columns that are set to hideable: false, hide: true (so that they are hidden and cannot be shown, things like ID's and whatnot that the user doesn't need to see). These are the ones that I would be targeting with this new getTogglableColumns callback to be able to hide them in the visibility panel. So in my use case, I would not want the show/hide all buttons to have any effect on these columns (so I guess honor the getTogglableColumns callback). Thanks!

**Comment by cherniavskii** [comment]
@cpolanish 

> I have a handful of columns that are set to hideable: false, hide: true
> I would not want the show/hide all buttons to have any effect on these columns

Non-hideable columns are not impacted by "Show all"/"Hide all" buttons even if they are visible in the columns panel - this was fixed in https://github.com/mui/mui-x/pull/7637

**Comment by MBilalShafi** [comment]
Thanks @cherniavskii for updating with the change and providing PR link.

I think then, to avoid confusion and be more consistent with the `hideable: false` columns, we can apply the same to those columns which _are_ hideable by `colDef.hideable` attribute but configured to be not togglable using `getTogglableColumns` callback. 

It makes sense too because the hideable columns may be shown in the panel but those which are not togglable will not, so IMO it doesn't make a lot of sense to toggle something that's even not shown.

What do you think?

**Comment by cherniavskii** [comment]
@cpolanish 
> I have a handful of columns that are set to hideable: false, hide: true (so that they are hidden and cannot be shown, things like ID's and whatnot that the user doesn't need to see).

Thinking about this more, if you want these columns to be hidden everywhere, wouldn't it make sense to just not include them in the `columns` definition? Is there any reason to keep them defined?

**Comment by toinhao1** [comment]
@MBilalShafi  premium user here and @SamuelEls identified a hole in the implementation.

Order id# 71629

**Comment by cherniavskii** [comment]
@SamuelEls 
> With your approach hiding that column will remove it from my stored order and showing it back will put the col 'a' to first place but i would expect it to have as last col

Not sure I follow this. My suggestion was to not include hidden columns in the `columns` prop if you don't want them to be available in the columns panel. Is this what you are referring to?

**Comment by toinhao1** [comment]
@cherniavskii what @SamuelEls is trying to say is No, it does not make sense to just not define them.

For example we have 20 columns in our table, 5 of them we allow the user to group the table by them. We dont want the 2nd column of the grouped column in any menu as was the original reason for this issue.

What was implemented solves the case for the columns menu, but there are still double of the same column in the filter column.

**Comment by MBilalShafi** [comment]
@toinhao1 From what I understood, you also want to hide the columns from the filter panel, although you can do that by using [filterColumns](https://mui.com/x/react-data-grid/filtering/multi-filters/#one-filter-per-column) callback, but if that's the case then doesn't it make more sense to not include them in the columns object on the first place?
I didn't understand the reason to still keep them in columns prop but hide from everywhere. 🤔

**Comment by toinhao1** [comment]
@MBilalShafi awesome, we hadn't seen filterColumns before. 

Just like the original reason for this issue, if you group columns, even if you hide the 2nd column in the table it still shows in these columnMenu and filterMenu.

**Comment by damiangreen** [comment]
For those arriving at this issue you can hide this column using `getTogglableColumns` and adding `GRID_ROW_GROUPING_SINGLE_GROUPING_FIELD` from the array.
Imported from ` '@mui/x-data-grid-premium'`

**Comment by Navin-Gelot** [comment]
This worked for me:

`groupingColDef={(params) => ({
                        cellClassName: 'hide-header-cell'
                    })}
                    sx={{
                        '& .MuiDataGrid-cell.hide-header-cell': {
                            display: 'none'
                        }
                    }}`
