### ISSUE TITLE
[DataGrid] Sticky headers to the document instead of the grid container

### ISSUE THREAD

**Issue by NjegosR** [mui/mui-x#7588]
### Order ID 💳

46083

### The problem in depth 🔍

We use DataGridPremium to display our data and we would like to have a fixed (sticky) header, while we scroll we want to see column names all the time. In MUI documentation we found out that this is possible if we have a fixed height for the DataGrid but this is not what we are looking for, we want to have a dynamic height (based on the number of rows).

Currently, we use `autoHeight` prop and we like how DataGrid works and looks, we want to keep that and add a sticky header to it. The ideal solution for us would not include our calculation of height every time when the number of rows is changed.

Any solution for this?

**Comment by cherniavskii** [comment]
Hey @NjegosR 
If I understood correctly, you're using the `autoHeight` prop and the grid height exceeds the screen height. When you scroll the page to see the rows at the bottom, the column header is not visible. Is this correct?

**Comment by NjegosR** [comment]
@cherniavskii  Yes, that is the problem. Here is a [link](https://codesandbox.io/s/weathered-https-c10f09?file=/demo.js&fbclid=IwAR3c38uig3pmfNC8EaURedEyagK-LwU8nYOIMkBi-4ORa8I-2EypV8XssDM) for CodeSandbox example.

**Comment by cherniavskii** [comment]
Did you consider using `height: 100vh` instead of `autoHeight={true}`?
Here's a demo: https://codesandbox.io/s/nice-bhabha-kp9e6d?file=/demo.js

**Comment by NjegosR** [comment]
That doesn't solve the issue. Let's say I set `height: 100vh` and if I turn on some filter, and that filter returns just one row I get this
<img width="552" alt="Screenshot 2023-01-17 at 18 05 01" src="https://user-images.githubusercontent.com/33623900/212965457-629abb69-5e05-44d6-bd8e-7192b5ae286d.png">

but I want DataGrid to adjust its height based on the number of rows, like this
<img width="547" alt="Screenshot 2023-01-17 at 18 11 21" src="https://user-images.githubusercontent.com/33623900/212966233-e3fd0f1b-0309-4254-ac74-2ee3df216109.png">

The second image is with `autoHeight` prop

**Comment by NjegosR** [comment]
@cherniavskii This will help, thank you.

**Comment by LucidityDesign** [comment]
Has anyone found a solution for v7?

**Comment by TylerNRobertson** [comment]
> Has anyone found a solution for v7?

Also looking for a solution for V7.

I have tried a few things but since the component hierarchy changed, its a bit difficult  to achieve now due to how the `overflow` is now getting handled, beforehand it seemed the column headers were outside the `virtualScroller` but now since they are within it, the sticky breaks if there's ever another wrapper element with `overflow`.  I'm assuming its for the performance benefits talked about with the column headers scroll in the v7 launch blog post.

If a page only has a `DataGrid` on it then it seems to work with `sticky` but if the `DataGrid` is a smaller piece of a page or a sub-section to a page that has its own overflow due to other content, it seems to break.

**Comment by jnalbert** [comment]
I'm facing the same issue with V7. I would love to know if anyone finds a solution 🙏

**Comment by sagrawal-code** [comment]
Would be awesome to have this feature out of the box!


Order ID 💳
90016

**Comment by Milind-Mohapatra** [comment]
Facing the same issue with data-grid-premium in v7. Any solutions or workarounds?

**Comment by ternala** [comment]
Also need this feature.
At least for not-free plans

**Comment by romgrk** [comment]
In v7 the column headers are sticky inside the scroll container, which helps UX, performance and accessibility. But this means that any previous workarounds that could enable sticking to the document body are now impossible. I would recommend using a layout that allows the grid itself to be the scroll container as it's designed to be.

I'll convert this to a feature request, for anyone interested please upvote the top comment, that's how we prioritize new features.

**Comment by romgrk** [comment]
@mui/xgrid I think this could be implemented if the grid has an option specific for this that makes it use a different DOM layout, but that could be a bit complex to implement. If anyone has objections to this feature request please comment.

**Comment by zhongfeiqian** [comment]
I have to revert to v6 at the moment, would like a solution to be implemented!

Order ID 💳
80936

**Comment by cherniavskii** [comment]
Using `autoHeight` with sticky column headers has a big downside – no virtualization.
It seems to me that the use case described in this issue can be solved by applying `autoHeight` conditionally – only when the total row height is small enough not to require a vertical scroll.
I've explored this in https://github.com/mui/mui-x/pull/9274, and I'm going to pick it up soon.
Let me know if there are use cases that are not addressed by the PR linked above.

**Comment by zhongfeiqian** [comment]
> Using `autoHeight` with sticky column headers has a big downside – no virtualization. It seems to me that the use case described in this issue can be solved by applying `autoHeight` conditionally – only when the total row height is small enough not to require a vertical scroll. I've explored this in #9274, and I'm going to pick it up soon. Let me know if there are use cases that are not addressed by the PR linked above.

Not sure what you're describing would be a solution for let's say I'm building a page with a max-width container, the top section is a search form, followed by the results table. The desired effect is to retain the normal document flow, where the user can scrolldown to see the table, and there's a FAB to go back to top. Having the header be sticky greatly increases the usability. 

I think this type of layout is actually quite common, an example would be the Google Flight search results page, the difference is it's using a list layout instead of a data grid.

**Comment by zhongfeiqian** [comment]
> > Having the header be sticky greatly increases the usability.
> 
> Does this demo explain this? @zhongfeiqian https://codesandbox.io/p/sandbox/ag-grid-sticky-header-2s4cx
> 
> This demo is using ag-grid, not built by me.

Pretty much, although in this example it's using position fixed, which ruined the header when scrolling.

**Comment by johnnyperkins-st** [comment]
+1

**Comment by KenanYusuf** [comment]
For those still interested in this feature, we have [an open issue](https://github.com/mui/mui-x/issues/15466) with a `waiting for 👍` label - please add a thumbs up reaction there if you would like to see it prioritized.
