### ISSUE TITLE
[data grid] How to detect if the scroll exist in table

### ISSUE THREAD

**Issue by fatih-mdous** [mui/mui-x#7590]
### Order ID 💳

#51399

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I need an api it is checking if a scroll exist on datagrid or not 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @fatih-mdous 
Could you provide more details about your use case? What are you trying to achieve?
Thanks!
