### ISSUE TITLE
Permanently display FilterPanel component outside of datagrid

### ISSUE THREAD

**Issue by gpspake** [mui/mui-x#7591]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The FilterPanel component included with data grid is a great feature that's impressive even as a standalone filtering UX.
Currently, the Filter Panel is coupled to the datagrid and only appears as a panel that hovers over the datagrid. 

### Examples 🌈

Here's an example of a requirements doc that shows the filter panel above the datagrid
<img width="422" alt="image" src="https://user-images.githubusercontent.com/3385690/212961984-59966252-bf0b-41d8-9f7e-ab7c334d609a.png">

Here's an example of what the filterpanel looks like by default
<img width="838" alt="image" src="https://user-images.githubusercontent.com/3385690/212963207-08455d45-fbde-4a5f-9b6c-ac04ef7b54f4.png">

Here's kinda what we're going for
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/3385690/212964918-da90c024-c637-44f9-a5ed-f002e7145908.png">

### Motivation 🔦

Our application requires the filters applied to the datagrid to be visible at all times. Instead of taking advantage of the existing feature-rich FilterPanel component, we will need to essentially rebuild it from scratch so it can be used outside of the data grid component. If we could just display the filterpanel permanently above the datagrid, we wouldn't need to do any additional work and we would be finished.

**Comment by cherniavskii** [comment]
Hey @gpspake 
Please take a look at https://github.com/mui/mui-x/issues/2522#issuecomment-1275409509
Is this what you are looking for?

**Comment by gpspake** [comment]
@cherniavskii That looks exactly like what we're looking for!! 🤗🤗🤗🤗
We'll give it a shot. I'll go ahead and close this for now.
Thanks! 🎉
