### ISSUE TITLE
[DateRangePicker] Support single input field on range pickers

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#7606]
All the fields for range editing are available in two versions:

- a multi input component with 1 input for the start date and 1 input for the end date
- a single input component with a single input for both dates

![image](https://user-images.githubusercontent.com/3309670/213160567-82d3f24e-f690-46c1-befa-627188096ae5.png)

For now, the range pickers (e.g. `DateRangePicker`) only support the multi input version.
But we want to provide support for single input fields in the range pickers at some point.

**Comment by Nic-S** [comment]
Totally agree, I expected that the dateRangePicker had already been updated with the single input possibility.
