### ISSUE TITLE
Readonly TextField but not the Calender

### ISSUE THREAD

**Issue by NishargShah** [mui/mui-x#7621]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/eloquent-snowflake-5sf8q0?file=/src/App.js

Steps:
1. Please open the URL

### Current behavior 😯

If I am giving the `readOnly: true` prop to the main `DatePicker` component, it also disabled the calendar icon, and specifying the `readOnly` prop into the `inputProps` removes the value.

My main goal is that users can not edit the date by themself, they need to select calendar icon for changing the value.

### Expected behavior 🤔

Giving `readOnly: true` prop needs to add `readonly` attribute in the `input` tag.

If I am adding `readonly` attribute into `input` manually from dev tools, it's working but adding from `inputProps` its not working.

### Context 🔦

My main goal is that users can not edit the date by themself, they need to select calendar icon for changing the value.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 12.3
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.112 
    @mui/core-downloads-tracker:  5.11.3 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.3 => 5.11.3 
    @mui/private-theming:  5.11.2 
    @mui/styled-engine:  5.11.0 
    @mui/styles: ^5.11.2 => 5.11.2 
    @mui/system:  5.11.2 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.2 
    @mui/x-date-pickers: ^5.0.12 => 5.0.13 
    @types/react:  18.0.26 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.9.4 
```
</details>

**Comment by alexfauquette** [comment]
> specifying the readOnly prop into the inputProps removes the value.

I guess this will solve your problem
```diff
-inputProps={{ readOnly: true }}
+inputProps={{ ...params.inputProps, readOnly: true }}
```
https://codesandbox.io/s/bold-mcclintock-ch0gps?file=/src/App.js

**Comment by NishargShah** [comment]
What a silly mistake, thanks @alexfauquette
