### ISSUE TITLE
[data grid] `singleSelect` with objects values for `valueOptions` shows no value initially when activating edit mode

### ISSUE THREAD

**Issue by jaa-itminds** [mui/mui-x#7623]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: ~~https://next.mui.com/x/react-data-grid/recipes-editing/#conditional-validation~~
https://codesandbox.io/s/determined-lumiere-n59opr?file=/demo.tsx

<details>
  <summary><code>Example code</code></summary>

```
const valueOptions = [
  { id: 0, name: "Wire Transfer" },
  { id: 1, name: "Cash" },
  { id: 2, name: "Credit Card" }
]

const rows: GridRowsProp = [
  {
    id: 1,
    expense: 'Car Insurance',
    price: randomPrice(0, 1000),
    dueAt: new Date(2021, 4, 8),
    isPaid: true,
    paymentMethod: [valueOptions[0]],
  },
]

const columns: GridColDef[] = [
  { field: 'expense', headerName: 'Expense', width: 160, editable: true },
  {
    field: 'price',
    headerName: 'Price',
    type: 'number',
    width: 120,
    editable: true,
  },
  {
    field: 'dueAt',
    headerName: 'Due at',
    type: 'date',
    width: 120,
    editable: true,
  },
  {
    field: 'isPaid',
    headerName: 'Is paid?',
    type: 'boolean',
    width: 140,
    editable: true,
  },
  {
    field: 'paymentMethod',
    headerName: 'Payment method',
    type: 'singleSelect'
    valueOptions: valueOptions.map(opt => ({ value: opt.id, label: opt.name })),
    valueFormatter: (params) => params.value[0]?.name,
    width: 160,
    editable: true,
  },
  {
    field: "actions",
    type: "actions",
    headerName: "Actions",
    width: 100,
    cellClassName: "actions",
    getActions: ({ id }) => {
      const isInEditMode = rowModesModel[id]?.mode === GridRowModes.Edit;

      if (isInEditMode) {
        return [
          <GridActionsCellItem
            icon={<SaveIcon />}
            label="Save"
            onClick={handleSaveClick(id)}
          />,
          <GridActionsCellItem
            icon={<CancelIcon />}
            label="Cancel"
            className="textPrimary"
            onClick={handleCancelClick(id)}
            color="inherit"
          />
        ];
      }

      return [
        <GridActionsCellItem
          icon={<EditIcon />}
          label="Edit"
          className="textPrimary"
          onClick={handleEditClick(id)}
          color="inherit"
        />,
        <GridActionsCellItem
          icon={<DeleteIcon />}
          label="Delete"
          onClick={handleDeleteClick(id)}
          color="inherit"
        />
      ];
    }
  }
]
return (
   <DataGrid rows={rows} columns={columns} editMode="row" />
)
```
</details>

Steps:
1. Use `valueOptions` containing of objects with `value` and `label` fields for a `singleSelect` column, as described in documentation of column definitions (https://next.mui.com/x/react-data-grid/column-definition/#special-properties)
2. `valueFormatter` extracts name from array, since `valueOptions` is array of objects
3. DataGrid uses `editMode="row"`

### Current behavior 😯

When in view mode:
![image](https://user-images.githubusercontent.com/90377552/213445520-bfceb282-89ec-4eb1-8f39-9b50e4096275.png)

After double-clicking to activate edit mode:
![image](https://user-images.githubusercontent.com/90377552/213445389-71557190-4a0b-4dd5-bcc7-b3aa95e6eb4b.png)

As shown, no value is displayed initially when activating edit mode, even though the cell contains a value.

### Expected behavior 🤔

The initial (already selected) value of a `singleSelect` cell should be displayed when activating edit mode

### Context 🔦

Our users are confused about the status of the dropdown cell, since no value is shown initially, leading them to think that the value is overwritten/deleted.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
  npmPackages:
    @emotion/react:  11.10.5
    @emotion/styled:  11.10.5
    @mui/base:  5.0.0-alpha.109
    @mui/core-downloads-tracker:  5.10.17
    @mui/icons-material:  5.10.16
    @mui/material:  5.10.17
    @mui/private-theming:  5.10.16
    @mui/styled-engine:  5.10.16
    @mui/system:  5.10.17
    @mui/types:  7.2.2
    @mui/utils:  5.10.16
    @mui/x-data-grid:  5.17.14
    @mui/x-data-grid-pro:  5.17.14
    @mui/x-license-pro:  5.17.12
    @types/react: ^18.0.21 => 18.0.26
    react:  18.2.0
    react-dom:  18.2.0
    typescript: ^4.8.4 => 4.9.4
```
</details>

And I used Chrome (version: 109.0.5414.75) for testing.

**Comment by cherniavskii** [comment]
Hi @jaa-itminds 
I've updated the issue description with a link to a Codesandbox demo based on your code snippet.

I've noticed that you are setting `paymentMethod` value to an array:
```js
paymentMethod: [valueOptions[0]]
```
Is this intentional?

Generally, the cell value is compared to a `value` property of value options.
In your example, the original value options are mapped to match the `{ value, label }` format:
```js
valueOptions.map((opt) => ({
  value: opt.id,
  label: opt.name
}));
```
This means that the cell value should contain the `id`:
```js
paymentMethod: valueOptions[0].id
```
Here's an updated demo: https://codesandbox.io/s/suspicious-tess-r7xdcz?file=/demo.tsx

For the `valueFormatter`, we've added a default one in https://github.com/mui/mui-x/pull/7290
With this change, the default `valueFormatter` would be used automatically, see this demo preview: https://codesandbox.io/s/serverless-water-c4zuy1?file=/demo.tsx
The v6 beta containing this change will be released tomorrow.

---

With that being said, we plan to improve the support for `valueOptions` to make it easier to integrate with custom data structures (we had a discussion about it recently https://github.com/mui/mui-x/pull/7290#discussion_r1058480564).

We would love to learn more about your use case and main struggles when working with the `singleSelect` column type.
