### ISSUE TITLE
Rows Per Page goes away after using Print

### ISSUE THREAD

**Issue by TanujSinghal** [mui/mui-x#7631]
In MUI Data-Grid **Export** once 'Print' option is selected, Rows per page option goes away and does not reappear even after print popup is closed.

This is happening in Chrome browser only.

Is this a know issue? are we going to fix it in future release anytime soon?
![dataGridErrorAfter](https://user-images.githubusercontent.com/25480290/213625226-79d9df3b-ae36-494a-a15c-4debc0a4d049.PNG)
![dataGridErrorBefore](https://user-images.githubusercontent.com/25480290/213625354-67cfeab4-5b67-4fb8-ae55-de7294e12012.PNG)

**Comment by alexfauquette** [comment]
Duplicate with #7630

Closing to keep only one issue to track
