### ISSUE TITLE
[data grid] API is not designed for immutable data

### ISSUE THREAD

**Issue by babyfish-ct** [mui/mui-x#7665]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

React application often uses immutable data types.

- For object
  ```ts
  interface Point {
     readonly x: number;
     readonly y: number;
  }
  ```
  is better than
  ```ts
  interface Point {
     x: number;
     y: number;
  }
  ```
- For array
   `ReadonlyArray<T>` is better than `Array<T>` or `T[]`
 

### Current behavior 😯

The typescript API cannot work with immutable data types.

### Expected behavior 🤔

For example:
 
- The
   ```ts
  export declare type GridValidRowModel = {
    [key: string]: any;
  };
  ```

  of 'gridRow.d.ts' should be changed to

  ```ts
  export declare type GridValidRowModel = {
    [readonly key: string]: any;
  };
  ```

- The
  
  ```ts
  export declare type GridColumns<R extends GridValidRowModel = any> = GridEnrichedColDef<R>[]
  ```
of 'gridColDef.d.ts' should be changed to

  ```ts
  export declare type GridColumns<R extends GridValidRowModel = any> = ReadonlyArray<GridEnrichedColDef<R>>;
  ```

### Context 🔦

NA

### Your environment 🌎

NA

**Comment by oliviertassinari** [comment]
@babyfish-ct Do you have a simple codesandbox where we can see the current types causing an issue?

**Comment by babyfish-ct** [comment]
@oliviertassinari 

I haven't read the source code of mux, so I don't know where the types I use are defined, I can only give the ".d.ts" file name.

When using DataGrid to find a problem, the generic parameter representing row does not accept read-only object, and the column collection cannot accept read-only array.

In fact, this is not limited to the details I found. Maybe mux has this problem in many places, and even the more basic mui also has this problem. This is a global problem, and I hope to do a systematic investigation on this.

**Comment by babyfish-ct** [comment]
@m4theushw 

This is a good habit, please refer to https://github.com/immerjs/immer.

This is a good solution, recommending that users write immutable data structures, mutable types `Draft<T>` are automatically generated by immer (draft is only used for accepting "modifications" to create new objects)

in the file "https://github.com/immerjs/immer/blob/main/src/types/types-external.ts"
- `Draft<T>` and `WritableDraft<T>`: developers define immutable types, immer deduces mutable types.
- `Immutable<T>`: Developers define mutable types, immer deduces immutable types.

In fact, for react, except for special solutions like mobx, it can almost be considered that react is designed for immutable data, but developers don't pay much attention to this issue (they only guarantee that no object modification at runtime, but there are no typescript compile-time guarantees).

Note: I don't mean that this problem is caused by integrating immer, I mean that immer has made me develop a good habit of always using immutable data types in react code.

Improving this API will have no effect on the mux, because

- Mutable object can be automatically converted to immutable object
- Mutable array can be automatically converted to mutable array

**Comment by babyfish-ct** [comment]
Suggestion:

- For object, it's generic parameter, let it extend `{readonly [key:string]: any}`, not `{[key:string]: any}`; otherwise, the generic parameter cannot be replaced by user's immutable object type.

- For array, input array should be `ReadonlyArray<T>` and output array should be `Array<T>`.

  - For input array, it often is simple react prop, like `DataGrid.rows`, accept `ReadonlyArray<T>`; 
     otherwise, it cannot accept user's immutable array.
     
  - For output array, it often is parameter of callback prop, such as `onSelectionChange`, give user `Array<T>`;
     otherwise, user cannot assign the callback parameter to another mutable array.

**Comment by oliviertassinari** [comment]
If feel that we are going off-topic, I don't see any problem described.

Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷. A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by babyfish-ct** [comment]
Can't reproduce the problem now, maybe I'm wrong in judgment.

Sorry
