### ISSUE TITLE
[data grid] Aggregating rows with a column type boolean or when a valueGetter is defined always shows value in footer row

### ISSUE THREAD

**Issue by fpizzinicce** [mui/mui-x#7673]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

How can i hide the aggregated value for the boolean type or when a valueGetter is defined?

Link to live example:

https://codesandbox.io/s/busy-https-wrside

### Current behavior 😯

In the footer row the value is shown

### Expected behavior 🤔

In the footer row the value is hidden

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by arifannosh** [comment]
I'm also facing the same  issue .

**Comment by cherniavskii** [comment]
The bug with the boolean column is fixed in v6.
We can update the docs for `valueGetter` and `renderCell` to mention the necessary checks when aggregation or row grouping features are being used.

**Comment by romgrk** [comment]
@cherniavskii I'll update the docs to include this but I'm not sure where to place that information in [this page](https://mui.com/x/react-data-grid/column-definition/#value-formatter). I was thinking a section at the end, and a warning in each of `valueGetter` and `renderCell` section to link to that last section on autogenerated rows?

**Comment by romgrk** [comment]
Closing in favor of #8933
