### ISSUE TITLE
[MobileDatePicker] a type error when define the defaultProps for MobileDatePicker

### ISSUE THREAD

**Issue by shestakova1806** [mui/mui-x#7674]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/keen-carlos-pp0pih?file=/demo.tsx

Steps:
1. Define `defaultProps` for `MuiMobileDatePicker` via `createTheme`.
2. Use MobileDatePicker.

### Current behavior 😯

There is an error:
`Type '{ MuiMobileDatePicker: { defaultProps: { showToolbar: false; }; }; }' is not assignable to type 'Components<Omit<Theme, "components">>'.`

### Expected behavior 🤔

There is no TS error.

### Context 🔦

I want to define defaultProps to MobileDatePicker and then use this component in my app with definite configuration of props and don't define them each time.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
@shestakova1806 
I can confirm that this is an issue on our side, themeAugmentation definition is not conclusive.
Working on a fix. 😉

**Comment by shestakova1806** [comment]
Thank you! So, I'm looking forward to get this fix soon :)

**Comment by LukasTy** [comment]
> Thank you! So, I'm looking forward to get this fix soon :)

[Here is](https://codesandbox.io/s/kind-water-jx017e?file=/demo.tsx) a working example using the pre-release package.
If the PR get's approved, it should be included in this week's release. 😉
