### ISSUE TITLE
[data grid] Hardcoded className strings in the utilities in PRO version of DataGrid

### ISSUE THREAD

**Issue by ruslanvyaznikov** [mui/mui-x#7675]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I use [ClassNameGenerator](https://mui.com/material-ui/experimental-api/classname-generator/) and should add a specific prefix, have an issue with utils

Not fully fixed hardcoded strings classNames in the package:

Should be gotten from the 
import { gridClasses } from '@mui/x-data-grid';

The list of the files where I found the issue:

'MuiDataGrid-root' => gridClasses.root

- node_modules/@mui/x-data-grid-pro/modern/utils/domUtils.js
- node_modules/@mui/x-data-grid-pro/legacy/utils/domUtils.js
- node_modules/@mui/x-data-grid-pro/modern/utils/domUtils.js
- node_modules/@mui/x-data-grid-pro/node/utils/domUtils.js
- node_modules/@mui/x-data-grid-pro/utils/domUtils.js

'MuiDataGrid-row--detailPanelExpanded' => gridClasses['row--detailPanelExpanded']

- node_modules/@mui/x-data-grid-pro/hooks/features/detailPanel/useGridDetailPanelPreProcessors.js
- node_modules/@mui/x-data-grid-pro/legacy/hooks/features/detailPanel/useGridDetailPanelPreProcessors.js
- node_modules/@mui/x-data-grid-pro/modern/hooks/features/detailPanel/useGridDetailPanelPreProcessors.js
- node_modules/@mui/x-data-grid-pro/node/hooks/features/detailPanel/useGridDetailPanelPreProcessors.js

![image](https://user-images.githubusercontent.com/30044390/214053238-1480b83a-cd30-4a12-b045-7850dac53046.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

56113

**Comment by ruslanvyaznikov** [comment]
any updates?

**Comment by MBilalShafi** [comment]
@ruslanvyaznikov This has been fixed and should be shipped with the next release.
