### ISSUE TITLE
[docs] Teach API slots documentation

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#7683]
The page https://mui.com/x/react-date-pickers/custom-components/ could have a section to explain that API pages list elements such as: https://mui.com/x/api/date-pickers/date-picker/#slots

From slack message

>	Please declare all the components that are customizable.
	sent from https://mui.com/x/react-date-pickers/custom-components/ (from section Component)

**Comment by Vivek-Prajapatii** [comment]
Hi @alexfauquette, can you please provide more details ? as i'm new to this project and i'm interested in this issue

**Comment by alexfauquette** [comment]
Yes, the idea is to add a message on the [next.mui.com/x/react-date-pickers/custom-components](https://next.mui.com/x/react-date-pickers/custom-components/) to say that the list of elements customizable are available in all API page in section `slots`

The text of the page is here
https://github.com/mui/mui-x/blob/next/docs/data/date-pickers/custom-components/custom-components.md

But not sure for now where to put it and how to highlight it
