### ISSUE TITLE
[DateRangePicker] switch position when entering date manually

### ISSUE THREAD

**Issue by agnenevulyte** [mui/mui-x#7686]
### Steps to reproduce 🕹

Link to live example:

Steps:
1. type the start date manually
2. we can see that the focus is still on the start date
3. pick the start date from the calendar
4. the focus appears on the end date

### Current behavior 😯

- When we type the start date manually in the DateRangePicker, the focus stays on the start date.
- When we pick the start date in the DateRangePicker from the calendar, the focus is switched to the end date.

### Expected behavior 🤔

We expect the typed-in date to behave the same way as the one picked from the calendar.

**Comment by agnenevulyte** [comment]
Thank you both @LukasTy & @m4theushw for responding so quickly. I've realized that I jumped to conclusions too quickly and have not explained the real issue I am facing. I thought that focusing on the end date would solve my problem, however,  the real issue I added to the sandbox [here](https://codesandbox.io/s/silly-artem-buxkut?file=/demo.tsx). I am setting the maxDate here.
When the user uses the calendar, it restricts them from picking up more than 31 days from the start date (or even less if there are less than 31 days from the start day till today's date). Because after choosing the start date in the calendar, the focus goes directly to the end date and only the end date is restricted.
When the user tries to type in the start date input (e.g. change the by -1), it starts restricting the start date by 31 days, though my goal is to restrict just the end date here. The start date should be available to pick any date until today's date.

Hope it's clearer now. And my apologies for the confusion. Thanks!

**Comment by LukasTy** [comment]
@agnenevulyte Have you considered using [`shouldDisableDate`](https://mui.com/x/api/date-pickers/date-range-picker/#:~:text=aria%2Dlabel%20text.-,shouldDisableDate,-func) to achieve this behaviour? It receives `position` as the second argument and so you should be able to only execute your logic for `position === 'end'`. 🤔

**Comment by agnenevulyte** [comment]
Thank you @LukasTy ! Have not thought of that :)

**Comment by agnenevulyte** [comment]
Closing the issue as this has been resolved.
