### ISSUE TITLE
`DataGridPremium` with row grouping and `valueGetter` doesn't show `valueGetter` value

### ISSUE THREAD

**Issue by WiXSL** [mui/mui-x#7720]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/dreamy-bush-jl4ulj?file=/src/components/Table1.jsx

### Current behavior 😯

The text on the `User name` group is the value of the `userName` field (plus the group count)

### Expected behavior 🤔

The text on the `User name` group is the value returned by `userName`'s `valueGetter` function (plus the group count)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Can you explain more about what you want to achieve?

If I understand your intention right, you want to customize the grouping column cell value, to customize anything related to the grouping column you can use the `groupingColDef` prop, see [this](https://mui.com/x/react-data-grid/row-grouping/#custom-grouping-column) demo for an example.

Note that in `groupingColDef.valueGetter` params, you will not receive row values as it refers to the grouping row and not the child rows, if you want to show a field or custom value as leaf though, you can use `groupingColDef.leafField` as mentioned [here](https://mui.com/x/react-data-grid/row-grouping/#show-values-for-the-leaves).

```tsx
<DataGrid
  groupingColDef={{
    valueGetter: (params) => {
      console.log(params.row); // {}
      return `Custom value`;
    },
    leafField: "userName"
  }}
/>
```

I've also added `groupingColDef.leafField` and `groupingColDef.valueGetter` to [this](https://codesandbox.io/s/cold-wildflower-qeim52?file=/src/components/Table1.jsx) codesandbox to visualize.

**Comment by WiXSL** [comment]
Hi @MBilalShafi,
Thanks for taking the time to look into this.

Yes, I want to set the leaf cell value to the `userName` field.
Since I'm only grouping by `userName` field, and `userName` has a `valueGetter` set, I would expect the `valueGetter` to be used for the leaf cell.
Using `leaffield: "userName"` doesn't make use of the `valueGetter` either.

I tried using `params.api` but I couldn't have access to the fields values.
I don't know if this can be achieved, or maybe it could be set as a feature request instead of a bug.

**Comment by MBilalShafi** [comment]
>  Using leaffield: "userName" doesn't make use of the valueGetter either.

I can see the same value getter set for `userName` being used for leaf field in this [codesandbox](https://codesandbox.io/s/cold-wildflower-qeim52?file=/src/components/Data1.jsx), can you check if that is what you are trying to achieve?

<img width="226" alt="image" src="https://user-images.githubusercontent.com/12609561/215102688-378fc356-4c02-4cb3-8e81-9908e3626d75.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/12609561/215102768-90c5aef4-284a-48fa-8734-98bb2e7ee5fe.png">

**Comment by WiXSL** [comment]
Ok, I wasn't clear about what I want to achieve.
What I want is not the leaf cell to be set, but the group cell. Something like this:

![screen](https://user-images.githubusercontent.com/8268610/215107589-51eff403-0912-416a-b0d8-6ddbe4640a43.png)
