### ISSUE TITLE
[TimePicker] not included in `themeAugmentation`

### ISSUE THREAD

**Issue by jdpst** [mui/mui-x#7730]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Try to add `MuiTimePicker` to theme.

https://codesandbox.io/s/eloquent-wildflower-c7m4ts?file=/demo.tsx

### Current behavior 😯

```
 Object literal may only specify known properties, but 'MuiTimePicker' does not exist in type 'Components<Omit<Theme, "components">>'. Did you mean to write 'MuiDatePicker'?ts(2322)
```

<img width="479" alt="image" src="https://user-images.githubusercontent.com/63979647/215079165-49abb724-7040-4363-940c-6de1a362f154.png">

### Expected behavior 🤔

`MuiTimePicker` should be defined in the types as with the other pickers.

### Context 🔦

Related to #7674

**Comment by LukasTy** [comment]
Sorry for managing to miss this while fixing the previous issue. 🤦 
@jdpst Will it not cause too much issues if it will be delivered in the next weeks release (probably v5.0.17)?

**Comment by jdpst** [comment]
> Sorry for managing to miss this while fixing the previous issue. 🤦
> @jdpst Will it not cause too much issues if it will be delivered in the next weeks release (probably v5.0.17)?

@LukasTy None at all, we have had a comment to disable typescript for it for some time already.

No need to apologise, we are very thankful for the efforts of everyone involved in building and maintaining these epic libraries!
