### ISSUE TITLE
[DateCalendar] Cannot change month and year

### ISSUE THREAD

**Issue by grzegorzCieslik95** [mui/mui-x#7755]
Hi, i have a simple component with a calendar picker

```
function DatePicker({date, setDate, className}) {
    return (
        <LocalizationProvider dateAdapter={AdapterDateFns} adapterLocale={plLocale} >
            <CalendarPicker
                date={date}
                onChange={(newDate) => setDate(newDate)}
                className={className}
                disablePast
                minDate={new Date()}
                onMonthChange={() => console.log('on month change cb')}
                onYearChange={() => console.log('on month change cb')}
            />
        </LocalizationProvider>
    )
}
```

On my localhost, everything works very well, but when I deployed this project to the test environment I have a problem like in video bellow. Do you have any idea what happens here?

https://user-images.githubusercontent.com/22835944/215342266-52622b94-f941-4749-9ee5-048c84b7bf5c.mov

**Comment by LukasTy** [comment]
Hello @grzegorzCieslik95 
This looks like a really interesting issue you are having.
But I'm afraid that the given context is not enough to provide any meaningful suggestion.

- Is the problem reproducible in a codesandbox?
- if not, how does your environment look like? Could you provide a GitHub repo with the minimal code allowing to reproduce your issue?
- have you tried other browsers (and/or incognito mode)?
- have you tried different library versions or even v6-beta (we changed the name of this component to `DateCalendar`)?
