### ISSUE TITLE
[pickers] Jittery behavior of calendar component

### ISSUE THREAD

**Issue by placidp** [mui/mui-x#7756]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://www.loom.com/share/0936c470f8164dc1b17a71865ece2100

Steps:

1. Open the https://mui.com/
2. Find the calendar component (on the right )
3. Choose any year

### Current behavior 😯

Right now it feels buggy and jittery

### Expected behavior 🤔

It should be smooth, without the appearance of 2 scrolls in the middle of the animation

**Comment by Vivek-Prajapatii** [comment]
Hi @m4theushw can you assign this to me

**Comment by placidp** [comment]
> The following diff seems enough to fix this bug:
> 
> ```diff
> diff --git a/packages/x-date-pickers/src/internals/components/PickerViewRoot/PickerViewRoot.tsx b/packages/x-date-pickers/src/internals/components/PickerViewRoot/PickerViewRoot.tsx
> index 4b2d25230..0fb7abdd9 100644
> --- a/packages/x-date-pickers/src/internals/components/PickerViewRoot/PickerViewRoot.tsx
> +++ b/packages/x-date-pickers/src/internals/components/PickerViewRoot/PickerViewRoot.tsx
> @@ -2,7 +2,7 @@ import { styled } from '@mui/material/styles';
>  import { DIALOG_WIDTH, VIEW_HEIGHT } from '../../constants/dimensions';
>  
>  export const PickerViewRoot = styled('div')({
> -  overflowX: 'hidden',
> +  overflow: 'hidden',
>    width: DIALOG_WIDTH,
>    maxHeight: VIEW_HEIGHT,
>    display: 'flex',
> ```
> 
> Do you want to submit a PR with it?

@Vivek-Prajapatii wants to do it, so assign it to him
