### ISSUE TITLE
[pickers] Custom toolbar is not overriding the header label and arrow icons in date-picker

### ISSUE THREAD

**Issue by venkateshpullaganti** [mui/mui-x#7763]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I searched the docs and issues but not able to find a solution. I might be missing something. 

```
import React from 'react';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import enLocale from 'date-fns/locale/en-US';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
import { FormControl, TextField } from '@material-ui/core';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import styled from 'styled-components';
import css from './styles.module.scss';

const CustomToolbar = (props) => {
    console.log('TCL: CustomToolbar -> props', props);
    return (
        <div>
            Custom Toolbar:
            <button onClick={() => props.setOpenView('year')}>Year</button>
            <button onClick={() => props.setOpenView('month')}>Month</button>
            <button onClick={() => props.setOpenView('day')}>Day</button>
        </div>
    );
};

export default function index() {
    return (
        <Wrapper className={css.wrapper}>
            <LocalizationProvider
                dateAdapter={AdapterDateFns}
                adapterLocale={enLocale}
            >
                <DatePicker
                    value={new Date()}
                    closeOnSelect
                    views={['year', 'month', 'day']}
                    onChange={console.log}
                    renderInput={(params: any) => (
                        <FormControl fullWidth>
                            <TextField {...params} fullWidth />
                        </FormControl>
                    )}
                    showToolbar
                    ToolbarComponent={CustomToolbar}
                />
            </LocalizationProvider>
        </Wrapper>
    );
}

const Wrapper = styled.div`

`;

```

### Current behavior 😯

<img width="325" alt="Screenshot 2023-01-30 at 6 16 15 PM" src="https://user-images.githubusercontent.com/38013987/215484004-0a9ef026-b2e8-4886-9ab6-bef8198e3f98.png">

### Expected behavior 🤔

The Month name, year and the arrow buttons should not be visible.

### Context 🔦

I am trying to achieve the 
<img width="325" alt="Screenshot 2023-01-30 at 6 16 15 PM" src="https://user-images.githubusercontent.com/38013987/215484658-896a0bd6-0ae2-436f-a90e-691011ca00d6.png">

### Your environment 🌎

Environment Details: 
- Mac book pro m1
- Chrome 109
- Node : 18.8.0
- Ts : 4.8.4
- Next js : 12.13.1
- React 18.2.0

**Comment by flaviendelangle** [comment]
The header you are referring to is not the toolbar but the header of the date views (`day`, `month` and `year`).
The toolbar is common to any view whereas this header will not appear on the time views.

We have the issue #6653 which focuses on the override of this part of the UI.
I think it would solve your problem as well. 
Once this slot is implemented, you would just have to pass a component returning `null` to it (or we would support the value  `null` like we do on the grid to say to render nothing.
