### ISSUE TITLE
[data grid] Translation error

### ISSUE THREAD

**Issue by bart1485** [mui/mui-x#7773]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

There are a translation mistake in frFR (x-data-grid/locales/frFR.js)
`  filterOperatorIsAnyOf: 'fait parti de',`
Expected:
`  filterOperatorIsAnyOf: 'fait partie de',`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by Vivek-Prajapatii** [comment]
Hi @m4theushw can you assign this to me? i can fix this up
