### ISSUE TITLE
[pickers] TypeScript compilation errors in @mui/x-date-pickers@6.0.0-beta.1 themeAugmentation

### ISSUE THREAD

**Issue by petermikitsh** [mui/mui-x#7779]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: can provide on request

Steps:
1. Create a custom theme overriding Mui Date picker:

```tsx
export const getTheme = (mode: PaletteMode) => {
  return createTheme({
    components: {
      MuiDatePicker: {
        defaultProps: {
          showDaysOutsideCurrentMonth: true,
        },
      },
    },
  });
};
```

2. Compile using `tsc`

### Current behavior 😯

Typescript compilation fails when `skipLibCheck: false`.

```
node_modules/@mui/x-date-pickers/themeAugmentation/overrides.d.ts(38,26): error TS2304: Cannot find name 'DateTimePickerTabsClassKey'.
node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts(15,3): error TS2305: Module '"../internals"' has no exported member 'CalendarOrClockPickerProps'.
node_modules/@mui/x-date-pickers/themeAugmentation/props.d.ts(66,51): error TS2344: Type 'unknown' does not satisfy the constraint 'DateOrTimeView'.
```

### Expected behavior 🤔

Typescript compilation succeeds when `skipLibCheck: false`,

### Context 🔦

I package MUI components in my own npm package (distributing them as ESM/CJS/etc bundles) and I use the typescript compiler (`tsc`) to generate my build artifacts.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:vinf
    OS: macOS 12.4
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.18.0 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Edge: Not Found
    Firefox: 102.5.0
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.115 
    @mui/core-downloads-tracker:  5.11.6 
    @mui/icons-material: ^5.10.14 => 5.11.0 
    @mui/material: ^5.10.14 => 5.11.6 
    @mui/private-theming:  5.11.2 
    @mui/styled-engine:  5.11.0 
    @mui/system:  5.11.5 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.2 
    @mui/x-date-pickers: 6.0.0-beta.1 => 6.0.0-beta.1 
    @types/react:  18.0.27 
    react: ^17 => 17.0.2 
    react-dom: ^17 => 17.0.2 
    typescript: 4.7 => 4.7.4 
```
</details>

**Comment by flaviendelangle** [comment]
@LukasTy that's my bad...
I'll try to look at the core approach to test the built packages this week :+1:

**Comment by LukasTy** [comment]
> that's my bad... I'll try to look at the core approach to test the built packages this week 👍

I'll look into feasibility of generating those files to avoid such mistakes as we have already made too many. 😢 
But from my initial look it might be way easier to come up with a test approach, rather than generation.
In any case, if we don't think of something before this weeks release, we can go with just a fix for the issues themselves. 🤞
