### ISSUE TITLE
[pickers] - selection of year and month in daterange picker (MUI X v6)

### ISSUE THREAD

**Issue by pabadm** [mui/mui-x#7780]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently it is only possible with too much control over calendar as i did in my example (unmounting and mounting calendar is the best). You just have not provided any other solution.
It would be nice to add something like headerCalendar slot with handleMonthChange prop or have month picker like in datepicker.

### Examples 🌈

Expected Behaviour. https://codesandbox.io/s/agitated-rgb-cuyd6z?file=/DateRangePickerTest.tsx

**Comment by flaviendelangle** [comment]
You did some heavy customization here !

This feature is being discussed in #4546 and taken care of in the #7071 umbrella issues.
It's one of the main ongoing topic for 2023 :+1:
