### ISSUE TITLE
[pickers] TimePicker with AM/PM – editing AM/PM from keyboard leads to invalid values

### ISSUE THREAD

**Issue by iliaznk** [mui/mui-x#7783]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Navigate to https://mui.com/x/react-date-pickers/time-picker/#basic-usage.
2. Enter a full time in the picker (make sure AMPM is enabled), e.g. "12:12 AM". Notice that letters must be in upper case.
3. Place the cursor right in front of "A" and type "P" – the value will change, but it will be invalid. The value will be valid only if the cursor is placed right after the last digit.

### Current behavior 😯

Reproducible on the documentation page https://mui.com/x/react-date-pickers/time-picker/

If you put the cursor next to "PM" like on the screenshot:

![CleanShot 2023-02-01 at 10 34 08](https://user-images.githubusercontent.com/6253368/215979658-f03f59cf-7e3e-4760-8dba-e2994a74cd3e.png)

An type in "A", the value will change, but it will be invalid:

![CleanShot 2023-02-01 at 10 35 24](https://user-images.githubusercontent.com/6253368/215979837-c4245f98-90d4-4aff-9f97-093dd3e40d89.png)

I've also tested it in my local application and noticed that the `keyboardValue` in that case will be `12:12 AMP` – so that must be what's causing it.

### Expected behavior 🤔

The value should be valid regardless of where you put the cursor, or it should be impossible to place the cursor in the "invalid" position. By the way, it will also accept low case letters but they will be invalid. Maybe it should accept any case and automatically switch letters to upper case?

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
:thinking: Indeed that's a weird behavior.
This is tightly linked to how editing work on v5.
The new version reworked in depth the input editing and you should no longer have related problems.
You can have a look at [the v6 doc](https://next.mui.com/x/react-date-pickers/time-picker/) which is currently in beta and the [related blog post](https://mui.com/blog/v6-beta-pickers/)
