### ISSUE TITLE
Data Grid flickering twice on new grid rows input

### ISSUE THREAD

**Issue by harvey56** [mui/mui-x#7792]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

I have a DataGrid whose data content (rows) is regularly updated (with a timer) via a prop of its parent component.

When new data (rows in the DataGrid componenent) comes in, <DataGrid /> will first re-render with empty content (including row ids), then with the updated content, then with empty content again, then with the updated content again. 

So it appears as if the grid content flickers twice before persistently showing. 

### Expected behavior 🤔

Expected behavior is that nothing flickers.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.9.0/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.106 
    @mui/core-downloads-tracker:  5.10.14 
    @mui/icons-material: ^5.10.9 => 5.10.14 
    @mui/material: ^5.10.13 => 5.10.14 
    @mui/private-theming:  5.10.14 
    @mui/styled-engine:  5.10.14 
    @mui/system:  5.10.14 
    @mui/types:  7.2.1 
    @mui/utils:  5.10.14 
    @mui/x-data-grid: ^5.17.12 => 5.17.14 
    @types/react: ^18.0.11 => 18.0.25 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.7.3 => 4.9.3
```
</details>

**Comment by harvey56** [comment]
Looks like problem is solved 👌. I was using version 5.17.12. Upgrading to version 5.17.21 helped fixing it. There must have been some commit about this bug sometime between 5.17.12 and 5.17.21

There was no mention of flickering in the issue reporting history, that's why I thought it was still an issue today.

**Comment by cherniavskii** [comment]
Hi Harvey,
Indeed, this was fixed in https://github.com/mui/mui-x/pull/7155 and released in https://github.com/mui/mui-x/releases/tag/v5.17.16
I'm glad the upgrade helped!
