### ISSUE TITLE
[data grid] Improve Performance of Master Detail on Datagrid with Lots of Rows

### ISSUE THREAD

**Issue by honeycomb-cheesecake** [mui/mui-x#7811]
### Order ID 💳

54524

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have a table that will likely be used to display thousands of rows of data, and for the most part, the performance of the MUI X Data grid is great. We are however noticing a performance issue with the **Master Detail / Detail Panel Content**. Understanding that table rows are virtualized, and data is only rendered as it is visible, this explains the fast speed on table load but I'm not sure this is being applied to your Detail Panel Content.

Looking at the screenshot provided, I've loaded in 4058 data rows into the table, and I've chosen to display 100 rows per page. Despite only having a small number of rows visible, the `getDetailPanelContent` callback is fired for all of the 4058 rows, and this happens on every re-render, and significantly slows down load for larger amounts of data.

![performance](https://user-images.githubusercontent.com/92522547/216574089-c5d75c53-9530-44a1-a1bb-6ee9b11f93e1.png)

Some important information:

* `getDetailPanelContent` and `getDetailPanelHeight` are memoized using `React.useCallback(...)` as recommended by the docs.
* `get` is set to a fixed height of 42 using: `const getDetailPanelHeight = React.useCallback<NonNullable<DataGridProProps['getDetailPanelHeight']>>(() => 42 as const, []);`
* We make the detail panel display by default for every row, by mapping the row data ids into a `new Array<number>` and pass it into the `detailPanelExpandedRowIds` props, as our users expect this data based on what this table is replacing.

Things that I've already tried:

* Returning `undefined` on the `getDetailPanelContent` callback: leads to significant performance increase
* Slicing the `detailPanelExpandedRowIds` into a much smaller sample of 30: No change in performance, the table iterates on all 4058 items but correctly shows the detail panel for the 30.
* Setting `detailPanelExpandedRowIds` to `undefined`: No change in performance, the table iterates on all 4058 items but correctly doesn't show any detail panels.
* Setting `getDetailPanelContent` to `undefined`: Table is smooth and performance is optimal.

Any help with this would be greatly appreciated. If there's another prop available that helps or if you need further details or a demo, please let me know.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Using Brave -> Chromium Browser, and Chrome Browser.
  System:
    OS: Linux 5.14 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 14.17.3 - ~/Programs/node/node-v14.17.3-linux-x64/bin/node
    Yarn: 1.22.19 - ~/Programs/node/node-v14.17.3-linux-x64/bin/yarn
    npm: 6.14.13 - ~/Programs/node/node-v14.17.3-linux-x64/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
  npmPackages:
    @mui/base:  5.0.0-alpha.116 
    @mui/core-downloads-tracker:  5.11.7 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.7 => 5.11.7 
    @mui/private-theming:  5.11.7 
    @mui/styled-engine-sc:  5.11.0 
    @mui/system: ^5.11.7 => 5.11.7 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.7 
    @mui/x-data-grid: ^5.17.22 => 5.17.22 
    @mui/x-data-grid-pro: ^5.17.22 => 5.17.22 
    @mui/x-license-pro:  5.17.12 
    @types/react: ^18.0.26 => 18.0.26 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    styled-components: ^5.3.6 => 5.3.6 
    typescript: 4.9.4 => 4.9.4 
```
</details>

**Comment by honeycomb-cheesecake** [comment]
Hi @m4theushw, thank you for getting back to me. Please find my [example code on code sandbox](https://codesandbox.io/s/hopeful-mountain-8ccovn). I've provided a whole bunch of toggle settings to demonstrate the performance issues that we are having. You'll see that there is an `Elements` input which allows you to specify how many elements to render in the table, with some presets (10,000 50,000 and 100,000) underneath. Also you'll see a button `UNDEFINED DETAIL PANEL` that lets you set the detail panel elements to `undefined` which results in a HUGE increase in performance, as well as the ability to toggle on/off the detail panel using `SHOW DETAIL PANEL`.

The application also prints the number of times the detail panel is rendered to the console using a `console.warn(...)`. If you need any further information, please let me know.

**Comment by cherniavskii** [comment]
I think we can optimize this by rendering a detail panel only if its row is rendered (basically reuse the rows virtualization).

**Comment by yaredtsy** [comment]
I have tried to fix it by only rendering the detail panel if the row is rendered. 

Demo: https://codesandbox.io/s/flamboyant-noyce-z6iv77
PR: #7969

**Comment by honeycomb-cheesecake** [comment]
Hi, with the submitted PR, is there any movement with this ticket?
