### ISSUE TITLE
I want to use search feature in Data grid pro

### ISSUE THREAD

**Issue by swathign-sbdinc** [mui/mui-x#7812]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. open _https://codesandbox.io/s/3c0lnz?file=/demo.js:1301-1317_
2. observe user can able to search inside of the table
3. the question is can we do the same in **Data grid pro** ?
4. Please share a codesandbox it would help

### Current behavior 😯

No documentation available

### Expected behavior 🤔

It should search anything we type in data grid pro table

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @swathign-sbdinc 
All the features available in the Community plan are also available in the Pro plan.

> open [codesandbox.io/s/3c0lnz?file=/demo.js:1301-1317](https://codesandbox.io/s/3c0lnz?file=/demo.js:1301-1317)
> observe user can able to search inside of the table
> the question is can we do the same in Data grid pro ?

The only thing you have to do is to use `@mui/x-data-grid-pro` package instead of `@mui/x-data-grid`:

```diff
- import { DataGrid, GridToolbarQuickFilter, GridLinkOperator } from '@mui/x-data-grid';
+ import { DataGridPro, GridToolbarQuickFilter, GridLinkOperator } from '@mui/x-data-grid-pro';
// ...

- <DataGrid
+ <DataGridPro
    {...data}
```
