### ISSUE TITLE
DatagridPro Restore state fails when there is restore of page involved

### ISSUE THREAD

**Issue by seemX17** [mui/mui-x#7818]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

**Steps to reproduce**
1) Have a table of more than 16 rows
2) Display 15 rows per page
3) go to the next page 
4) save the state
5) move to a different component/page 
6) come back to the page where we render the table

State data

```
const dummyState = {
  columns: {
    columnVisibilityModel: { jobTitle: false },
    dimensions: {
      firstName: {
        maxWidth: -1,
        minWidth: 120,
        width: 155.25,
        flex: 0,
      },
      lastName: { maxWidth: -1, minWidth: 140, width: 140, flex: 0 },
      email: { maxWidth: -1, minWidth: 120, width: 278.5, flex: 0 },
      telephoneNumber: { maxWidth: -1, minWidth: 170, width: 100 },
      jobTitle: {
        maxWidth: -1,
        minWidth: 130,
        width: 100,
        flex: 0.1,
      },
      groups: { maxWidth: -1, minWidth: 115, width: 237.25, flex: 0 },
      status: { maxWidth: -1, minWidth: 220, width: 100 },
    },
    orderedFields: ['__check__', 'firstName', 'lastName', 'email', 'telephoneNumber', 'jobTitle', 'groups', 'status'],
  },
  filter: { filterModel: { items: [] } },
  pinnedColumns: { left: [], right: [] },
  sorting: { sortModel: [] },
  pagination: { page: 1, pageSize: 100 },
  rowGrouping: { model: [] },
};
```
![image](https://user-images.githubusercontent.com/8757624/216663386-3a00a6e5-18cd-40e6-a679-620803da9346.png)

### Current behavior 😯

When I try to restore a state using `gridApiRef.current.restoreState()` it fails when I try to restore data which involves page

### Expected behavior 🤔

When I render the table it should not break the table

**Comment by cherniavskii** [comment]
Hi @seemX17 
Could you provide a reproduction example?
I cannot reproduce it with this sandbox: https://codesandbox.io/s/priceless-resonance-gon3lj?file=/demo.tsx
1. Go to the next page
2. Click "Save state"
3. Click "Hide grid"
4. Click "Show grid"
5. The grid state is restored.
