### ISSUE TITLE
Unable to access the HTML Cell Element with a Pinned Column using the apiRef `getCellElement`

### ISSUE THREAD

**Issue by tjgibbs92** [mui/mui-x#7819]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/admiring-rubin-6wgxjx?file=/index.js

Steps:
1. Double Click the first cell and hit tab in each grid

### Current behavior 😯

When hitting tab with pinned columns, the apiRef is not returning the HTML Cell Element.

### Expected behavior 🤔

Hitting Tab will return the HTML element of the next cell.

### Context 🔦

In the first grid, hitting Tab will return the HTML element of the next cell as expected.
In the second grid however, with the pinned columns, the HTML cell element is not returned.

We are trying to focus custom inputs of the next editable column using the keyboard.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
System:

    OS: Windows 10 10.0.19045

  Binaries:

    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE

    Yarn: Not Found

    npm: 8.15.0 - ~\AppData\Roaming\npm\npm.CMD

  Browsers:

    Chrome: Not Found

    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.70)

  npmPackages:

    @emotion/react: ^11.9.3 => 11.9.3

    @emotion/styled: ^11.9.3 => 11.9.3

    @mui/base:  5.0.0-alpha.107

    @mui/core-downloads-tracker:  5.10.15

    @mui/material: ^5.10.15 => 5.10.15

    @mui/private-theming:  5.10.15

    @mui/styled-engine:  5.10.14

    @mui/system:  5.10.15

    @mui/types:  7.2.1

    @mui/utils:  5.10.15

    @mui/x-data-grid:  5.17.20

    @mui/x-data-grid-premium: ^5.17.20 => 5.17.20

    @mui/x-data-grid-pro:  5.17.20

    @mui/x-license-pro:  5.17.12

    @types/react:  18.0.15

    react: ^17.0.1 => 17.0.2

    react-dom: ^17.0.1 => 17.0.2
</details>

### Order ID 💳 (optional)

58533

**Comment by cherniavskii** [comment]
Hey @tjgibbs92 
Thanks for opening this issue and providing the reproduction example!
This was reported previously in https://github.com/mui/mui-x/issues/7093, we will track it there.
I'll close this one as a duplicate, thanks again!
