### ISSUE TITLE
[pickers] Support `dayjs.tz`

### ISSUE THREAD

**Issue by rodrigofariow** [mui/mui-x#7832]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Motivation 🔦

My team is currently considering moving from luxon to dayjs due to [this issue](https://github.com/mui/mui-x/issues/7615).

Luxon is great because it allows us to globally set the default timezone and it works very well with mui pickers.
So, for instance, if I'm currently in Europe/Lisbon(currently, UTC+00) at Feburary 5th 8PM and I set globally the default timezone to be Asia/Singapore(UTC+08), mui pickers will correctly infer that the "today" date is Feburary 6th, not 5th.

We are trying to replicate this behaviour when using dayjs. However we noticed it doesn't work like that out of the box, even when [setting globally the default timezone](https://day.js.org/docs/en/timezone/set-default-timezone).

From my understanding, this is because in order to use the default timezone, we need to create dates using `dayjs.tz`.
I noticed you recently added support for utc dates [using dayjs.utc ](https://next.mui.com/x/react-date-pickers/adapters-locale/#use-utc-dates) and I was wondering if adding support for dayjs.tz is on the roadmap?

Thank you!

### Order ID 💳 (optional)

54728

**Comment by flaviendelangle** [comment]
Yes, the `dayjs.tz` usage is on the roadmap.
Unfortunately the API changes are bigger compared to `dayjs.utc` (the argument order of `dayjs.parse` is not the same for example), so the work will take more time.

**Comment by flaviendelangle** [comment]
I played with the `dayjs.tz` plugin and I think that I have something that works.
@rodrigofariow could you have a look at [this codesandbox](https://codesandbox.io/s/date-and-time-pickers-forked-rxwfi5?file=/src/App.tsx), maybe replicate the same logic in your application and tell me if it works as expected.

I'm creating a custom instance to pass to the adapter (like for `dayjs.utc`) that automatically sets the default timezone.
The field editing seems to work correctly and if you pass a date built from `utc`, you have the correct date of the singapore timezone.

**Comment by rodrigofariow** [comment]
Hi @flaviendelangle 
The date looks like is being correctly selected but there are subtle things that don't work as I expect (that work with Luxon).
For instance, the current day on the UI is using my local timezone, not singapore's.

Here is my local time (Europe/Lisbon):
<img width="125" alt="image" src="https://user-images.githubusercontent.com/22502084/223198959-0f932f21-85ab-41a0-a99f-6bc190c1d946.png">

At this time, Singapore is already 7th March but on the component UI I see 6th:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/22502084/223198735-e41f0c0d-96b9-4cba-b742-bd1004d45959.png">

That's the only thing I found so far.

**Comment by flaviendelangle** [comment]
Thanks to take time testing it !
I'll have a look :+1: , it's probably something that can be fixed.

**Comment by flaviendelangle** [comment]
The problem seems to come from https://github.com/iamkun/dayjs/issues/1189
Which looks a lot like #5876

[This fixed version](https://codesandbox.io/s/date-and-time-pickers-forked-rxwfi5?file=/src/App.tsx) seems to work for your use case, but I suspect that it will fail if we pass dates from various timezones.

**Comment by flaviendelangle** [comment]
Closing this issue in favor of #8484
