### ISSUE TITLE
[DatePicker] All months disabled in month view, when using maxDate and defaultCalenderMonth

### ISSUE THREAD

**Issue by svenhorner** [mui/mui-x#7852]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/mui-x-issue-template-forked-72hy9d?file=/src/App.tsx

Steps:
1. open Date Picker
2. switch to month view by clicking on the header in the Date Picker

### Current behavior 😯

Months are disabled when going to months view directly, although they are in the range of not disabled dates, that is < maxDate

### Expected behavior 🤔

Months that are in the range of not disabled dates should be selectable right away

### Context 🔦

Ruins UX (as DatePickers like to do :P), as the user either thinks he is stuck or will have to click on the header again, and select the year, then click on the header again, to come back to the month selection, then select the year AGAIN (which he as previously selected), so he can finally select the day. 💩 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    Browser: Chromium 109.0.5414.119 snap
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: Not Found
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 109.0.1
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.114
    @mui/core-downloads-tracker:  5.11.5
    @mui/lab: ^5.0.0-alpha.116 => 5.0.0-alpha.116
    @mui/material: ^5.11.5 => 5.11.5
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.5
    @mui/types:  7.2.3
    @mui/utils:  5.11.2
    @mui/x-date-pickers: ^5.0.17 => 5.0.17
    @types/react: ^18.0.9 => 18.0.9
    react: ^18.1.0 => 18.1.0
    react-dom: ^18.1.0 => 18.1.0
    typescript: ^4.6.4 => 4.6.4
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

`defaultCalendarMonth` is only used in the `day` view.
That's something we indeed need to improve. In #5702 we are discussing how it would help focus a date on the other views.
But your use case is slightly different and is probably more urgent.

If you can, avoid setting `null` as a value and initialize it to your `defaultCalenderMonth` instead.
But that's clearly not a perfect fix.

I'll up the priority of #5702 and close this one to keep a single source of truth :+1:
