### ISSUE TITLE
MUI DataGrid Premium - Can the export button in the custom toolbar be disabled when rows are empty?

### ISSUE THREAD

**Issue by noobDev31** [mui/mui-x#7860]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I have seen the existing issues and I do see that the export button in a custom toolbar can be removed completely. But I have a requirement to disable it whenever the row length is 0. Is it possible to do so?

### Examples 🌈

The following sandbox completely removes the button - 

https://codesandbox.io/s/epic-framework-hqddfr

**Comment by cherniavskii** [comment]
Hi @noobDev31 
You can pass a `disable` prop to the `GridToolbarExport` component.
Here's a working demo: https://codesandbox.io/s/youthful-butterfly-h2e4ob?file=/demo.tsx:283-300
