### ISSUE TITLE
[data grid] is there a way to export datagrid state on unload event?

### ISSUE THREAD

**Issue by NareshMurthy** [mui/mui-x#7876]
### Order ID 💳

56539

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a data grid pro, and am trying to store the datagrid state on component unload event(user navigates to another page), and restore the datagrid state once the user comes back the page again. 
Is there a recommended way to do this?

Thanks!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by NareshMurthy** [comment]
@cherniavskii  Thanks this helped a lot

**Comment by michelengelen** [comment]
Hey @NareshMurthy ... we recently added a recipe that handles your use-case. Check out this part of the docs: [Save and restore the state from external storage](https://mui.com/x/react-data-grid/state/#save-and-restore-the-state-from-external-storage).

I am closing this issue now as per the reasoning above! :shipit: 

If this is not sufficient or when you have follow-up questions please feel free to re-open this issue and tag me! Glad to help you!
