### ISSUE TITLE
[question] How To Change COlor of MUI Icon?

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#7879]
### Order ID 💳

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We would like to use the MUI WarningIcon with yellow and black colors. I can change the triangle to yellow, that is easy. I would like to make the exclamation point black, since it is very hard to see a white exclamation point. I've searched everywhere, but haven't been able to figure out how to change it. It will be in a data grid cell...

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @conerye 
Please see the Material UI's Icon docs at https://mui.com/material-ui/icons/#color

**Comment by conerye** [comment]
well, that was not helpful...
I had already seen the documentation. I guess I was hoping for a response such as the only way to do it is to create a custom svg icon or you could do blah, blah, blah.
:-(
