### ISSUE TITLE
[docs] Hidden Columns are not visible AND the horizontal scroll bar is all the way at the bottom of the screen

### ISSUE THREAD

**Issue by BenGardiner123** [mui/mui-x#7880]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/api/data-grid/data-grid-premium/#props

### Kind of issue

Other

### Issue description

It feels insanely poor UX that you can't side scroll the data here ? If you want to see the last column you have to scroll...scroll..scroll..side scroll.. scroll..scroll.. oh wait where was I ?

### Context 🔦

I want to be able to scroll the hidden columns at any position on the page.

![image](https://user-images.githubusercontent.com/61527372/217973372-ff76cf2f-7faa-48dc-bee0-05fe8217cda2.png)

**Comment by cherniavskii** [comment]
Thanks @BenGardiner123 
This has been reported in https://github.com/mui/material-ui/issues/34085
I'm closing this issue as a duplicate
