### ISSUE TITLE
[RFC][charts] Pie charts

### ISSUE THREAD

**Issue by alexfauquette** [mui/mui-x#7884]
Pie charts are a bit unique from other charts since they behave in radial coordinates (instead of cartesian)

## Examples

- [nivo](https://nivo.rocks/pie/)
- [Echarts](https://echarts.apache.org/examples/en/editor.html?c=pie-nest)
- [Recharts](https://recharts.org/en-US/examples/TwoLevelPieChart) 
- [Highcharts](https://www.highcharts.com/demo/pie-donut?_gl=1*1h0pc1p*_up*MQ..&gclid=CjwKCAiArY2fBhB9EiwAWqHK6k81XolnkNa07Q9BlK5AgCNYJeLeCmmTvvjrbCa3yhJMws4B9MYJkxoC5tEQAvD_BwE)

## Topics

- How to handle nested pie charts (one into the other one)
- The label placement to avoid overlapping: https://github.com/recharts/recharts/issues/490
- Slice management: being able to select (highlight) a slice or hide them

## Value format

- **Nivo**: `[ {id, value } , ...]`. For nested pie charts named [sunburst](https://nivo.rocks/sunburst/) they add a property `children` to each objects

- **Echarts**: `[{ value, name }, ...]` For nesrted charts, they simply add distinct series and keep them distinct with `radius: [0, '30%']` `radius: ['45%', '60%']`

- **Recharts**: `[{ value, name }, ...]` For nested pie, you declare multiple objects and manage their radius ` <Pie data={data1}/><Pie data={data1}/>`

- **Highcharts**: multiple series displayed with `size` and `innerSize` properties

**Comment by bluepenit** [comment]
I am using @mui PieChart. Although the data type is correct, an error occurs in the console when I mouse over the chart.

`Warning: Failed prop type: Invalid prop series.data[0] of type object supplied to DefaultChartsItemTooltipContent, expected number.`

**Comment by alexfauquette** [comment]
@bluepenit Your issue is a duplicate of #11679

Please avoid commenting closed issue if the topic is not closely related
