### ISSUE TITLE
 Boolean filter is not working without "generateData" [question] 

### ISSUE THREAD

**Issue by konrazem** [mui/mui-x#7889]
### Order ID 💳

46820

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I do not understant what "**generateData**" method do in boolean filter. Looks like I cannot make it work without it.  Is there any documentation about boolean filter? 
https://codesandbox.io/s/nervous-cori-57viye?file=/demo.tsx

My walkaround was to change boolean to number (0, 1) filter.

**Comment by cherniavskii** [comment]
Hey @konrazem 
Could you clarify your question? What are you trying to achieve?
Thanks!

**Comment by konrazem** [comment]
Hello. @cherniavskii cherniavskii I want to make filter of boolean values working. If boolean columns has conifguration: 
``` 
{
  field: "isAdmin",
  headerName: "Is admin?",
  type: "boolean",
  width: 150
}
```
filter is NOT working for this column correctly. I need to give also generateData property. So my question is why and how can I do it? 
Please check codesandbox example in my post. Try to set filter for "isAdmin" column

**Comment by cherniavskii** [comment]
The example you linked seems to be working correctly.
Here's a simplified one with a single boolean column: https://codesandbox.io/s/hungry-heisenberg-i8rmf3?file=/demo.tsx
Again, filtering seems to work just fine - all 3 filter values work as expected.

Can you double-check?
