### ISSUE TITLE
DATA grid allows editing even if loader is showing

### ISSUE THREAD

**Issue by amal1994** [mui/mui-x#7891]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Goto this sandbox link -> https://codesandbox.io/s/stupefied-lamport-9tsxzq?file=/demo.tsx
2. Just refresh the browser window in codesandbox if it shows some error on first load.

### Current behavior 😯

Editing is enabled when loader overlay is showing

### Expected behavior 🤔

Editing should be disabled when loader overlay is showing

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @amal1994 
This issue is fixed in v6 of the data grid (currently in beta). See this demo: https://codesandbox.io/s/nifty-zeh-nwxlgl?file=/demo.tsx

For the v5, you can fix it with snippet:
```tsx
<DataGridPro
  componentsProps={{
    loadingOverlay: {
      sx: { pointerEvents: "auto" }
    }
  }}
/>
```
See a working demo: https://codesandbox.io/s/long-cookies-h4hzos?file=/demo.tsx:393-543

**Comment by amal1994** [comment]
thanks for the input @cherniavskii , will keep in mind
