### ISSUE TITLE
[Data Grid] multi filter unexpected behavior when overriding `filterOperators` 

### ISSUE THREAD

**Issue by JohnMusleh** [mui/mui-x#7901]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-data-grid-filteroperators-bug-femx8o

Steps:
1. Click on the three dots menu on column `name` and then select "Filter"
2. Click anywhere else to close the filter (without putting a value in the filter)
3. Click on the three dots menu on any other column, and you should see there are two lines of filters (both with empty values) 
<img width="595" alt="Screen Shot 2023-02-11 at 13 24 11" src="https://user-images.githubusercontent.com/17234162/218255622-c12b3e98-7501-4083-af1c-dea7e2d4f7f7.png">

### Current behavior 😯

Opening the filter menu for column `name` saves the "empty" filter on the column 

so when opening the filter menu on any other column, we see this:
<img width="595" alt="Screen Shot 2023-02-11 at 13 24 11" src="https://user-images.githubusercontent.com/17234162/218255727-58c90876-4846-4700-801a-f1c1a5708bb3.png">

### Expected behavior 🤔

Opening the filter menu for column `name` should not save the "empty" filter , and opening the filter menu after that on any other column, should only show the column that the user clicked on : 
<img width="573" alt="image" src="https://user-images.githubusercontent.com/17234162/218255794-ea7b6f02-c5d4-4d45-b97b-aed88d2cc198.png">

### Context 🔦

I'm trying to simply change the `filterOperators` on a column, either to change the order of the default operators or only allow certain operators. 

I noticed that the bug only happens when playing with the `filterOperators`  ( for column `name` in my example )
When using the default `filterOperators` this bug does not reproduce 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: latest => 11.10.5 
    @emotion/styled: latest => 11.10.5 
    @mui/base:  5.0.0-alpha.117 
    @mui/core-downloads-tracker:  5.11.8 
    @mui/icons-material: latest => 5.11.0 
    @mui/material: latest => 5.11.8 
    @mui/private-theming:  5.11.7 
    @mui/styled-engine:  5.11.8 
    @mui/system:  5.11.8 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.7 
    @mui/x-data-grid: ^5.0.0 => 5.17.23 
    @mui/x-data-grid-generator: ^5.0.0 => 5.17.23 
    @mui/x-data-grid-premium:  5.17.23 
    @mui/x-data-grid-pro: ^5.0.0 => 5.17.23 
    @mui/x-license-pro:  5.17.12 
    @types/react: latest => 18.0.27 
    react: latest => 18.2.0 
    react-dom: latest => 18.2.0 
    typescript: latest => 4.9.5 
```
Browser used is google chrome
</details>

### Order ID 💳 (optional)

39595

**Comment by cherniavskii** [comment]
Hey @JohnMusleh 
Could you clarify your intention of using `getGridSingleSelectOperators` for the `string` column type?
Using `getGridStringOperators` seems to work as expected: https://codesandbox.io/s/mui-data-grid-filteroperators-bug-forked-5ew8n8?file=/demo.tsx

**Comment by JohnMusleh** [comment]
Hi @cherniavskii , I found this bug while trying to override operators for `singleSelect` type, I just fixed my example and changed the `name` column type to `singleSelect`  
https://codesandbox.io/s/mui-data-grid-filteroperators-bug-femx8o?file=/demo.tsx:755-767

I guess the bug only occurs for `singleSelect`

**Comment by cherniavskii** [comment]
Thanks, @JohnMusleh!
I can reproduce it with `is any of` filter operator (no need to override `filterOperators` for reproduction):
https://codesandbox.io/s/mui-data-grid-filteroperators-bug-forked-pu66qd?file=/demo.tsx

https://user-images.githubusercontent.com/13808724/218319756-63d9ba71-9276-4aee-9edc-996386a57c31.mov
