### ISSUE TITLE
[pickers] Time Picker / Date Time Picker do not include a UI view

### ISSUE THREAD

**Issue by sphinx9** [mui/mui-x#7919]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://next.mui.com/x/react-date-pickers/time-picker/
Link to live example: https://next.mui.com/x/react-date-pickers/date-time-picker/

### Current behavior 😯

The desktop variation of TimePicker does not include any form of picker for selecting a time - it's basically the same as the new 'Field component'. Additionally, the desktop variation of the DateTimePicker component includes a date picker, but not a time picker. The mobile and static variations of the aforementioned components are fine and include a time picker, as expected.

### Expected behavior 🤔

...there should be a time picker in the Date Time Picker and Time Picker components.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

Thanks for your feedback
You have more context [on the migration guide](https://next.mui.com/x/migration/migration-pickers-v5/#stop-rendering-a-clock-on-desktop) and on #4483

**Comment by flaviendelangle** [comment]
Maybe we should add a note on the `TimePicker` and `DateTimePicker` v6 pages to briefly explain that

**Comment by oliviertassinari** [comment]
If I understand the use case correctly, it's meant for end-users that are using their mouse pointer, but are either:

1. too lazy to use the keyboard to input the form. It makes sense, it can be more effort to move its hand to input than click a bit.
2. are used to this UX pattern they don't even think about using their keyboard. 

?

**Comment by LukasTy** [comment]
> If I understand the use case correctly, the "popover" is meant for end-users that are using their mouse pointer, but are either:
> 
> 1. too lazy to switch to the keyboard. It makes sense, it can be more effort to move its hand to press a keystroke than moving the cursor and clicking a bit.
> 2. are used to the popover UX pattern. They don't even think about using their keyboard.
> 
> ?

Yes, I'd agree with both of your assumptions. We need to take care of as many possible use cases as possible and it's probably only a small percentage of power users, who, would be very happy with the approach of the new field and use only it to enter data, but the majority of casual users are probably used to having some sort of mouse/view based behaviors of interacting with data. 👍

**Comment by oliviertassinari** [comment]
@sphinx9 So to be clear, we moved the discussion to https://github.com/mui/mui-x/issues/4483, you can subscribe to this issue close event.

<img width="865" alt="Screenshot 2023-02-14 at 12 51 43" src="https://user-images.githubusercontent.com/3165635/218730449-83e72e2b-4143-40fb-a8f8-cc613084e94b.png">
