### ISSUE TITLE
[DataGrid] Checkbox selection works inconsistently

### ISSUE THREAD

**Issue by SusiKette** [mui/mui-x#7932]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I'm using a "custom" DataGrid that basically just implements some basic features the same way across all places where the DataGrid is used. Through props you give the row data, column config, etc. that may be dependent on the actual data that is shown. I tried simplifying the DataGrid all the way down to a very basic form that uses const data instead of getting data from a backend and it still is happening.

Here is the simplified DataGrid code that still caused the issue for me:
```import React from "react";
import {DataGrid} from "@mui/x-data-grid";


const cols = [
    {field: "object_id", headerName: "ID", minWidth: 50, editable: false, hide: true},
    {field: "name", headerName: "Name", minWidth: 155, flex: 1, editable: false},
    {field: "type", headerName: "Type", minWidth: 155, flex: 1, editable: false},
]

const rows = [
    {"object_id": 31351813958, "name": "A", "type": "1"},
    {"object_id": 31557357357, "name": "B", "type": "2"},
    {"object_id": 78456746068, "name": "C", "type": "3"},
]

export function CustomDataGrid(): JSX.Element {
    return(
        <DataGrid
            columns={cols}
            rows={rows}
            checkboxSelection
            getRowId={(row) => row.object_id}
        />
    );
}
```

Just add that component anywhere.

### Current behavior 😯

Clicking on any of the selection checkboxes sometimes works (mostly doesn't do anything). Clicking anywhere else in the row works just fine.

EDIT: Probably should mention that the checkbox ripple animation does play even if the actual select/deselect event doesn't happen

### Expected behavior 🤔

Clicking the checkbox should select/unselect the row or all rows if the checkbox in the column header was clicked.

### Context 🔦

I'm trying to implement multi-row selection (probably obvious).

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
  npmPackages:
    @emotion/react: 11.10.5 => 11.10.4
    @emotion/styled: 11.10.5 => 11.10.4
    @mui/base:  5.0.0-alpha.96
    @mui/core-downloads-tracker:  5.10.4
    @mui/icons-material: 5.10.9 => 5.10.3
    @mui/material: 5.10.13 => 5.10.4
    @mui/private-theming:  5.10.3
    @mui/styled-engine:  5.10.4
    @mui/system:  5.10.4
    @mui/types:  7.2.0
    @mui/utils:  5.10.3
    @mui/x-data-grid: 5.17.11 => 5.17.1
    @types/react: 18.0.25 => 18.0.18
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: 5.3.6 => 5.3.5
    typescript: 4.8.4 => 4.8.2
```
</details>

I was using Chrome while testing the page
EDIT: Tried Edge as well and this happens on that browser too

**Comment by MBilalShafi** [comment]
Hey @SusiKette I tried to reproduce it in this [codesandbox](https://codesandbox.io/s/data-grid-community-forked-flfwto?file=/src/App.tsx) with the steps you mentioned but not able to do it. (Working fine for me on Firefox and Chrome browsers)

Can you try reproducing it in some live example and share the link? Feel free to use the above codesandbox as a starting point.

**Comment by SusiKette** [comment]
I'm not sure why, but this doesn't happen anywhere else.

Something I did figure out is that this also happens on the `<Checkbox/>` component. Logging the `onClick` event target, did tell me that on clicks where the checkbox state doesn't change, the target is a `<path>` element, instead of `<input>` element that is logged on clicks where the state does change.

Do you have any idea on what could cause that? Even if this was a rare issue, it would still be nice to solve.

**Comment by MBilalShafi** [comment]
The issue might be related to the state or other external factors causing some re-renders or some positioning issues. It will be great if you provide a minimal reproduction of the issue in a live codesandbox so that it could be analyzed better.

You can use [this example](https://codesandbox.io/s/data-grid-community-forked-flfwto?file=/src/App.tsx) as a starting point.
If the production on codesandbox is not possible due to complexity, may be you can push it on a public git repo and share the URL.

**Comment by akshaygdhole** [comment]
Hey @SusiKette I'm having same issue did you got any solution ?

**Comment by vanta240i** [comment]
> I'm not sure why, but this doesn't happen anywhere else.
> 
> Something I did figure out is that this also happens on the `<Checkbox/>` component. Logging the `onClick` event target, did tell me that on clicks where the checkbox state doesn't change, the target is a `<path>` element, instead of `<input>` element that is logged on clicks where the state does change.
> 
> Do you have any idea on what could cause that? Even if this was a rare issue, it would still be nice to solve.
> 
> EDIT: I think I figured out what causes the issue, but not why it happens. The `<input>` tag for some reason only covers the [top left quarter of the checkbox](https://i.imgur.com/k74CIYy.png). So only clicking on that area toggled the checkbox. In all other places, the `<input>` tag covers the entire checkbox area

I have the same issue, clicking the top left corner works, anything else doesn't.
