### ISSUE TITLE
[fields] Editing a section value using `ArrowDown` / `ArrowUp` should not impact other section's value

### ISSUE THREAD

**Issue by OctoberJemini** [mui/mui-x#7934]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/krz4s0?file=/demo.tsx

Steps:
1. Click on AM/PM, minutes, or Hour
2. Press and hold the up arrow (or down arrow)

### Current behavior 😯

Notice the date changes when cycling through AM/PM or Hours and the hour changes when cycling over the minutes from 59 -> 00 or 00 -> 59

### Expected behavior 🤔

The date and hours should stay the same when rolling over those fields. 

### Context 🔦

For non-sighted users, changing the value in a field they have already completed is a terrible experience. Even sighted users may have yet to notice that date/time changes, which can cause invalid or unwanted times/dates to be entered.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
Run via codesandbox from the Beta Site
Chrome Version 109.0.5414.120 (Official Build) (64-bit)
</details>

**Comment by OctoberJemini** [comment]
Would also like to point out that this breaks an already known paradigm established by the HTML5 date time picker: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

The Minutes, Hours, and AM/PM do NOT cycle time or dates forwards or backward

**Comment by flaviendelangle** [comment]
Hi,

If I correctly understand your point, you would prefer each time section (hours, minutes, seconds and meridiem) to be independent.
In other word, pressing `ArrowUp` on the minutes should set the increment the minute value, but if it does from 59 to 0, then it should not increment the hours (same for the other sections).

If we have a look at our two main competitors which have similar field components, Spectrum does what you say and Telerik does what we currently do.

Changing to an independent sections behavior is totally doable if that's what we want to do.
Would you say the same applies to date sections ? (it does on the HTML5 date time picker).

**Comment by LukasTy** [comment]
Great observation! 👌 
Indeed, based on native implementations as well as how the suggested ["spin button" example](https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/examples/datepicker-spinbuttons/) behaves, I'd agree that our default behavior should be the same, with maybe an option to toggle the current behavior, but it's a very big BUT if that's worth the extra effort. 🙈

**Comment by flaviendelangle** [comment]
Not sure how much work it would be to switch to the proposed implementation in this issue and how much more to have both supported.

I can have a look and we can base our decision on the amount of code required to keep both

**Comment by flaviendelangle** [comment]
I need to do more check but the change seems to be trivial.
We just have to force the usage of `setSectionValueOnSections` instead of `setSectionValueOnDate`.
If we don't want to support interdependent sections, we could even drop the `setSectionValueOnDate` logic. Because it would only be used in `useFieldCharacterEditing` which would work great without it (to be tested more thoroughly but all the tests pass).

```diff
diff --git a/packages/x-date-pickers/src/internals/hooks/useField/useField.ts b/packages/x-date-pickers/src/internals/hooks/useField/useField.ts
index 1827d949c..17e7213a1 100644
--- a/packages/x-date-pickers/src/internals/hooks/useField/useField.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useField/useField.ts
@@ -297,6 +297,7 @@ export const useField = <
 
         updateSectionValue({
           activeSection,
+          hasIndependentSections: true,
           setSectionValueOnDate: (activeDate) => {
             let date = adjustDateSectionValue(
               utils,
diff --git a/packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts b/packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
index f454b09e9..9eb509e79 100644
--- a/packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts
@@ -29,6 +29,11 @@ export interface UpdateSectionValueParams<TDate, TSection extends FieldSection>
    * The section on which we want to apply the new value.
    */
   activeSection: TSection;
+  /**
+   * If `true`, the value will always be updated using `setSectionValueOnSections` even if there is a valid date.
+   * @default false
+   */
+  hasIndependentSections?: boolean;
   /**
    * Function called if the current date is valid.
    * It must return a new date with the value of the active section updated.
@@ -276,6 +281,7 @@ export const useFieldState = <
     activeSection,
     setSectionValueOnDate,
     setSectionValueOnSections,
+    hasIndependentSections = false,
   }: UpdateSectionValueParams<TDate, TSection>) => {
     const commit = (
       commitParams: {
@@ -317,7 +323,11 @@ export const useFieldState = <
     };
 
     const activeDateManager = fieldValueManager.getActiveDateManager(utils, state, activeSection);
-    if (activeDateManager.activeDate != null && utils.isValid(activeDateManager.activeDate)) {
+    if (
+      !hasIndependentSections &&
+      activeDateManager.activeDate != null &&
+      utils.isValid(activeDateManager.activeDate)
+    ) {
       const validDateResponse = setSectionValueOnDate(
         activeDateManager.activeDate,
         sectionsValueBoundaries,
```

**Comment by flaviendelangle** [comment]
I propose we discuss this behavior next Monday because it's an important decision on the editing behavior :+1: 
The technical aspect seems to be negligible compared to the product decision.

**Comment by OctoberJemini** [comment]
Thank you for looking into this quickly; it is great to see such a quick turnaround. You are spot on with your assessment of the problem that each section (not just the time) scrolls independently of the others.

Along with a small A/B sample test, independent scrolling was **much** more of expected behavior as well as preferred, with one participant saying, and I quote: 

> oh ... that AM/PM thing is not ... what I expected
> no
> that is not right
> that's making me angry

This was an honest response, and I thought a little levity would help :).
