### ISSUE TITLE
When using day.js, the datetimepicker component won't show the correct day of the week

### ISSUE THREAD

**Issue by matiasfacio** [mui/mui-x#7941]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.use day.js and pass it ont he LocalizationProvider
2. open DateTimePicker
3. go to today's day

### Current behavior 😯

I see today's day (all of them) on the wrong day column. For example, 14.Feb is in the Wednesday column.

### Expected behavior 🤔

Today's day should be on the right column. eg.: 14th Feb should be on the Tuesday column

### Context 🔦

I need a date and time picker

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
   System:
    OS: macOS 13.1
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.2.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.96
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    @emotion/react: ^11.8.2 => 11.8.2 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.72 
    @mui/icons-material: ^5.5.1 => 5.5.1 
    @mui/lab: ^5.0.0-alpha.73 => 5.0.0-alpha.73 
    @mui/material: ^5.5.1 => 5.5.1 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system: ^5.8.0 => 5.8.0 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-date-pickers: ^5.0.0-alpha.4 => 5.0.0-alpha.4 
    @types/react: ^17.0.40 => 17.0.40 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.0 => 17.0.0 
    styled-components: ^5.3.1 => 5.3.6 
    typescript: ^4.6.2 => 4.8.4 
```
</details>

**Comment by LukasTy** [comment]
Could you please provide a working example showcasing the issue you are talking about?
I take it you might be interested in `de` locale. I've created [an example](https://codesandbox.io/s/date-time-picker-de-296d3x) that seems to work completely fine in regards to weekday placement.
