### ISSUE TITLE
v6.0.0-beta.3 TimePicker doesn't display pop-out on desktop

### ISSUE THREAD

**Issue by scottlamb** [mui/mui-x#7948]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: happens on the demo site itself, https://next.mui.com/x/react-date-pickers/time-picker/

Steps:
1. look at the component
2. maybe click on it...? I tried near the rightmost edge, where I'd expect the popout's icon to be (but don't see it)

### Current behavior 😯

I don't see a way to display the pop-out clock on desktop. There's no icon for it, and clicking on the field doesn't display it either. In fact, on desktop I don't see any difference between `TimePicker` and `TimeField`.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/8949524/219235751-db248780-ab4f-4785-880c-a539d26f509f.png">

On mobile, clicking on the picker brings up the clock, which sounds about right.

### Expected behavior 🤔

The demo's text says "The time picker is rendered as a modal dialog on mobile, and a textbox with a popup on desktop." I'd expect the behavior to match that.

I see a little clock icon on the right as in the [v5 `TimePicker`](https://mui.com/x/react-date-pickers/time-picker/), which currently looks like this for me...

<img width="273" alt="image" src="https://user-images.githubusercontent.com/8949524/219235591-cf9e5d3b-d930-4c0b-87e0-8f6d44672a7b.png">

...as well as the fields for typing in hour/minute/second/ampm, so a user can do either.

### Context 🔦

allow a desktop user to either type a time or pick it from the clock pop-out.

### Your environment 🌎

Chrome Version 110.0.5481.77 (Official Build) (arm64), on macOS

**Comment by LukasTy** [comment]
Thank you for opening this issue and sorry for the unnecessary confusion caused. 🙈 

This is only a temporary solution, which we [already made clear](https://deploy-preview-7933--material-ui-x.netlify.app/x/react-date-pickers/time-picker/) and the docs will be updated to reflect it with the next release (probably today).
Fixed by #7933
