### ISSUE TITLE
params.hasFocus does not work for row grouping leaf fields

### ISSUE THREAD

**Issue by ryancogswell** [mui/mui-x#7949]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/hasfocus-for-row-grouping-leaves-tuw57o?file=/demo.tsx

Steps:
1. Click on one of the values in the "Focus Test" column.

### Current behavior 😯

The `renderCell` function for the focusTest and focusTest2 columns is defined as:

`renderCell: (params) => "hasFocus=" + JSON.stringify(params.hasFocus)`

Clicking on one of the cells in the "Focus Test 2" column (which is not a row grouping leaf field), flips the value from "hasFocus=false" to "hasFocus=true", but clicking on one of the cells in the "Focus Test" column has no effect -- the value remains "hasFocus=false".

Interestingly, if you show the "Focus Test" column such that it actually displays twice (once under the "Last Name" grouping as the leaf field and then again as the first column after the leaf field), clicking on the second one (the non-leaf rendering of the field) causes both cells to flip to "hasFocus=true".

### Expected behavior 🤔

Clicking on one of the cells in the "Focus Test" column should flip the value from "hasFocus=false" to "hasFocus=true" (i.e. should have same behavior as the "Focus Test 2" column).

### Context 🔦

In my actual code, I have a navigation button/link in the leaf field and I'm trying to use `params.hasFocus` to flip its `tabIndex`, but it doesn't work so the button is not keyboard accessible.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.17763
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Not Found
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4
    @emotion/styled: 11.10.4 => 11.10.4
    @mui/base:  5.0.0-alpha.98
    @mui/core-downloads-tracker:  5.11.9
    @mui/icons-material: 5.10.6 => 5.10.6
    @mui/lab: 5.0.0-alpha.100 => 5.0.0-alpha.100
    @mui/material: 5.10.6 => 5.10.6
    @mui/private-theming:  5.11.9
    @mui/styled-engine:  5.11.9
    @mui/system:  5.11.9
    @mui/types:  7.2.3
    @mui/utils:  5.11.9
    @mui/x-data-grid:  5.17.23
    @mui/x-data-grid-generator: 5.17.23 => 5.17.23
    @mui/x-data-grid-premium: 5.17.23 => 5.17.23
    @mui/x-data-grid-pro:  5.17.23
    @mui/x-date-pickers: 5.0.3 => 5.0.3
    @mui/x-date-pickers-pro: 5.0.3 => 5.0.3
    @mui/x-license-pro: 5.17.12 => 5.17.12
    @types/react: 18.0.28 => 18.0.28
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```
</details>

I have tried this on both Chrome and Firefox.

### Order ID 💳 (optional)

51199

**Comment by MBilalShafi** [comment]
Thanks for reporting the issue.

The reason why the `hasFocus` was not becoming true for focused grouping leaf cells is the focus was being borrowed from the target column being passed in `groupingColDef.leafField`.

I've raised a PR for the fix. It should be available in the next release. You can also check the [updated codesandbox](https://codesandbox.io/s/hasfocus-for-row-grouping-leaves-forked-359w8j?file=/demo.tsx) running on the updated code.
