### ISSUE TITLE
x-codemod unable to migrate any files + missing renameCSSClasses in "preset-safe"

### ISSUE THREAD

**Issue by rompeldunk** [mui/mui-x#7951]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. npx @mui/x-codemod v6.0.0/preset-safe .\PMP\src\

### Current behavior 😯

```
Error: Cannot find module 'packages/x-codemod/src/util/renameCSSClasses'
Require stack:
- C:\Users\MyComputerUser\AppData\Roaming\npm-cache\_npx\13512\node_modules\@mui\x-codemod\v6.0.0\data-grid\rename-linkOperators-logicOperators\index.js
- C:\Users\MyComputerUser\AppData\Roaming\npm-cache\_npx\13512\node_modules\@mui\x-codemod\v6.0.0\data-grid\preset-safe\index.js
- C:\Users\MyComputerUser\AppData\Roaming\npm-cache\_npx\13512\node_modules\@mui\x-codemod\v6.0.0\preset-safe\index.js
- C:\Users\MyComputerUser\AppData\Roaming\npm-cache\_npx\13512\node_modules\@mui\x-codemod\node_modules\jscodeshift\src\Worker.js
```

Results:
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 3.667seconds

### Expected behavior 🤔

No errors and able to transform v5.15.5 <DataGridPro params

Note: Is this tool only searching for <DataGrid /> components and not <DataGridPro />?

### Context 🔦

Quick convert old v5 props to v6

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
npx: installed 2 in 4.216s

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.18.3 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.46)
  npmPackages:
    @emotion/react:  11.9.0
    @emotion/styled:  11.8.1
    @mui/base:  5.0.0-alpha.79
    @mui/icons-material:  5.6.2
    @mui/lab:  5.0.0-alpha.80
    @mui/material:  5.6.4
    @mui/private-theming:  5.6.2
    @mui/styled-engine:  5.6.1
    @mui/system:  5.6.4
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-data-grid:  6.0.0-beta.3
    @mui/x-data-grid-pro:  6.0.0-beta.3
    @mui/x-date-pickers:  6.0.0-beta.3
    @mui/x-license-pro:  6.0.0-beta.3
    @types/react:  17.0.20
    react:  17.0.2
    react-dom:  17.0.2
    typescript:  4.4.2

```
</details>

**Comment by LukasTy** [comment]
Thank you for opening this issue. 🙏 And also trying out the `v6-next`! 🙇 
That is a silly issue on our side. PR fixing it is ready.

**Comment by rompeldunk** [comment]
> 

Do the @mui/x-codemod have a `v6-next` ?
I'm already on:
```
"@mui/x-data-grid-pro": "next",
"@mui/x-date-pickers": "next",
```

Hence, the guide from https://next.mui.com/x/migration/migration-data-grid-v5/

I've already tried using one and one conversion rule to mitigate the css-rule error, but no get detected nor props replaced.
So technically this is a dual-issue.

**Comment by LukasTy** [comment]
> Do the @mui/x-codemod have a `v6-next` ?

When I mentioned my gratitude for trying out `v6-next`—I meant what you are already doing—trying out the current v6 beta release of pickers and data grid packages. 👌 

`@mui/x-codemod` is a package introduced only in v6, hence, we are releasing and tagging it both as `latest` as well as `next`. So, no matter if you'd include the `@next` suffix or not, the latest available `codemod` package would be used. 😉
