### ISSUE TITLE
Migration docs contradiction

### ISSUE THREAD

**Issue by rompeldunk** [mui/mui-x#7955]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Error in the migration docs
https://next.mui.com/x/migration/migration-data-grid-v5/#apiref-methods

### Current behavior 😯

The apiRef.current.getVisibleRowModels method was removed. Use _gridVisibleSortedRowEntriesSelector_ selector instead.

✅ The gridVisibleSortedRowEntriesSelector selector was renamed to gridExpandedSortedRowEntriesSelector.

### 

### Expected behavior 🤔

The apiRef.current.getVisibleRowModels method was removed. Use **gridExpandedSortedRowEntriesSelector** instead.

✅ The gridVisibleSortedRowEntriesSelector selector was renamed to gridExpandedSortedRowEntriesSelector.

### Context 🔦

--

### Your environment 🌎

--

**Comment by MBilalShafi** [comment]
Thanks for reporting @rompeldunk, I've raised a [PR](https://github.com/mui/mui-x/pull/7963) to fix it.
