### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by moshemo613** [mui/mui-x#7961]
### Order ID 💳

60041

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to be able to set filters using checkboxes that are NOT in the filter panel.  I.e., in the sidebar, I have some checkboxes, and I want those checkboxes to set certain filters when checked.  I have been trying to figure out how to do this, but keep running into problems.

My thought was that I should use the apiRef as follows (this example using a Button instead of a checkbox):

```
import { useGridApiRef } from "@mui/x-data-grid-pro";
export default function Sidebar({) {
  const apiRef = useGridApiRef();

 <DataGridPro
    apiRef={apiRef}
    components={{ Toolbar: GridToolbar }}
    rows={rowsData}
    columns={columnsData}
  />

  <Button
    variant="contained"
    onClick={() =>
      apiRef.current.setFilterModel([
        {
          id: 1,
          columnField: "roic10y",
          operatorValue: ">=",
          value: 10,
        },
      ])
    }
  >
    Set Filter Model
  </Button>
  );
}
```

However, when I click on this button, I get the following error:  `TypeError: Cannot read properties of undefined (reading 'length')`

![image](https://user-images.githubusercontent.com/110940244/219395483-672c3162-4dd8-4e10-8e8e-e2094898c08e.png)

Am I doing this the right way?  I.e., should I be using setFilterModel?  If so, what am I doing wrong and how can I fix it?  If not, what should I be doing?

Thanks :).

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
You are not passing the filter model in the correct format, you can see the correct format of GridFilterModel [here](https://mui.com/x/api/data-grid/grid-filter-model/).

I've prepared a codesandbox with correct usage of `apiRef.current.setFilterModel()` method: https://codesandbox.io/s/data-grid-community-forked-l1g6vw?file=/src/App.tsx

> should I be using setFilterModel

That totally depends on the goal you want to achieve. If you want to programmatically update filterModel, you can use this method or you can also:
1. [Initialize filterModel](https://mui.com/x/react-data-grid/filtering/#initialize-the-filters)
2. [Make filterModel controlled.](https://mui.com/x/react-data-grid/filtering/#controlled-filters)

For more information and code examples, please read through the filtering [documentation](https://mui.com/x/react-data-grid/filtering/).

**Comment by moshemo613** [comment]
Thanks, this was very helpful.  Much appreciated :).
