### ISSUE TITLE
[docs] How to access right part of the API docs 

### ISSUE THREAD

**Issue by rockfight** [mui/mui-x#7962]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/api/data-grid/data-grid/

### Kind of issue

Other

### Issue description

The API page document is cut off on the right and there is no way to scroll to the right. I tried on different browsers and monitors. All of them had this problem. You can see the page here.
![image](https://user-images.githubusercontent.com/902571/219430949-e3c281a1-3730-4e3b-a8e5-ff5b6ec60aa6.png)

### Context 🔦

I was trying to read the documentation.

**Comment by MBilalShafi** [comment]
Can you try scrolling the page right/left like so?

![scroll](https://user-images.githubusercontent.com/12609561/219446145-13c65a2a-bcf4-41c4-8b7b-05c1adaed9c7.gif)

**Comment by rockfight** [comment]
Nop. Neither I can scroll, nor can I drag. I am not sure how you are scrolling.

**Comment by LukasTy** [comment]
Could you try scrolling down to the bottom of the "Props" table and checking if you can see a scrollbar at the bottom of it?
If not, we'd need a bit more information about the system you are running on and the browsers you have tried.
