### ISSUE TITLE
[pickers] The `error` and `slotProps.textField.error` are not applied

### ISSUE THREAD

**Issue by sebastian-ludwig** [mui/mui-x#7966]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I would like to have custom error-handling for the DatePicker Textfield-Component, but it seems to ignore the `error`-prop (`helperText` is working)

```
<DatePicker
        slotProps={{ textField: { error: true, helperText: 'Error' } }}
 />
 ```
 

### Current behavior 😯

No error indication with red border and color.

**Comment by LukasTy** [comment]
Thank you for opening this issue and trying out a v6 pre-release! 🙏 
We currently are indeed not allowing the `error` flag to be overridden. 🙈

**Comment by sebastian-ludwig** [comment]
Thx @LukasTy, will this be supported this in the future? 
Is there any workaround to support an error highlighting right now? (probably adding the error-class manually?)

**Comment by LukasTy** [comment]
It was possible previously, we'll fix it to be possible in v6 as well. 👌 
If you really need it ASAP, you could go with a somewhat hacky solution like [this one](https://codesandbox.io/s/hacky-error-override-hj9o7m).
