### ISSUE TITLE
[pickers] Hide the toggleMobileKeyboardView button in Mobile Date picker in the DatePickerToolbar

### ISSUE THREAD

**Issue by sohaibnajjar** [mui/mui-x#7989]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

in the previous version of the date pickers we didn't have the button to toggle between the dialog view and keyboard view 

I searched on the website and there is no way to hide it and keep the default component 

if you want to hide this button you have to create new DatePickerToolbar

![image](https://user-images.githubusercontent.com/43302694/220105272-98ad91e6-4a90-47ab-9e7f-69bd2bb2f040.png)

### Examples 🌈

i tried to use the default DatePickerToolbar and pass props to it but it didn't work for me 

```
     ToolbarComponent={(props) => <DatePickerToolbar  
     toggleMobileKeyboardView={() => { }}
      isLandscape 
      onChange={() => { }} 
      openView='day' 
      setOpenView={() => { }} 
      toolbarTitle="hello" 
      views={['year', 'day', 'month']}
      parsedValue={""} 
      isMobileKeyboardViewOpen={true}
       />
      }
 
```
 

### Motivation 🔦

is there is a way to hide the title or this button?
or I have to create new component ?

**Comment by LukasTy** [comment]
Hello @sohaibnajjar 
In v5 there is no option to override/hide just the toggle button. The only option would be to hide the toolbar (`showToolbar={false}`) altogether, which is not the most optimal solution on mobile.
[On v6](https://next.mui.com/x/react-date-pickers/date-picker/#available-components) we are straying away from material design guidelines and have decided to no longer have the input toggle button in the toolbar.
Maybe it would be possible for you to use v6 pickers, which are closely approaching a stable release (in 1-2 weeks)?

**Comment by flaviendelangle** [comment]
Closing it since the new version we solve this problem :+1:
