### ISSUE TITLE
[pickers] Disable the Text Feild in the MobileKeyboardView in Mobile Date picker is not working 

### ISSUE THREAD

**Issue by sohaibnajjar** [mui/mui-x#7990]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: from mui-x page 

https://codesandbox.io/s/keen-sound-ls070w?file=/demo.tsx

Steps:
1. add disabled to the TextField in renderInput
2.click on the date picker modal 
3. change to the MobileKeyboardView
4. type something it will change the value 

### Current behavior 😯

changeing disabled input

### Expected behavior 🤔

not to change disabled input

**Comment by LukasTy** [comment]
@sohaibnajjar Could you explain what are you trying to achieve by specifying `disabled` only on the rendered `input`?
Doing this only the rendered input is aware, that it should be disabled.
If you want to conditionally disable the picker, consider just using the `disabled` prop on the Picker component.
