### ISSUE TITLE
[question] Editing a boolean column with Datagridpro

### ISSUE THREAD

**Issue by dpreuitt** [mui/mui-x#8003]
### Order ID 💳

59537

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I've got a datagridpro with an editable boolean column. How do I know when the value has changed? I'm trying onCellEditStop which doesn't have the updated value when it's called and also onCellEditCommit, which doesn't seem to trigger the  handler when the check is changed or the cell loses focus.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
Using Microsoft Edge

 System:
    OS: Windows Server 2016 10.0.14393
  Binaries:
    Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Not Found
  npmPackages:
    @emotion/react: ^11.7.1 => 11.10.4
    @emotion/styled: ^11.6.0 => 11.10.4
    @mui/base:  5.0.0-alpha.98
    @mui/core-downloads-tracker:  5.10.6
    @mui/icons-material: ^5.4.1 => 5.10.6
    @mui/lab: ^5.0.0-alpha.68 => 5.0.0-alpha.100
    @mui/material: ^5.4.1 => 5.10.6
    @mui/private-theming:  5.10.6
    @mui/styled-engine:  5.10.6
    @mui/styles: ^5.4.1 => 5.10.6
    @mui/system: ^5.4.1 => 5.10.6
    @mui/types:  7.2.0
    @mui/utils: ^5.4.1 => 5.10.6
    @mui/x-data-grid: ^5.5.0 => 5.17.23
    @mui/x-data-grid-pro: 5.17.23 => 5.17.23
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.18
    @mui/x-date-pickers-pro: ^5.0.18 => 5.0.18
    @mui/x-license-pro:  5.17.12
    @types/react:  17.0.50
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.5 => 4.8.3
</details>

**Comment by dpreuitt** [comment]
Using processRowUpdate seems to work with regard to persisting the data, but when I've changed the value of the boolean field by clicking on it (and checking/unchecking the box) the column seems to stay in Edit mode even when I press Enter or Tab (and I can't drag-reorder the rows). Only Esc brings it out of edit mode _but_ resets the checkbox to the original state.

**Comment by cherniavskii** [comment]
Hi @dpreuitt 
I cannot reproduce the issue you describe, feel free to provide a minimal reproduction example so we can investigate.
Thanks!
