### ISSUE TITLE
[data grid] Row is not able to display after unpinned

### ISSUE THREAD

**Issue by cugbjing** [mui/mui-x#8013]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/withered-cache-5pvjk5?file=/demo.tsx
Steps:
1. pin a row
2. unpin a row

### Current behavior 😯

After unpin the row, the row is gone from the datagrid

### Expected behavior 🤔

The unpinned row should show up at previous location and unpinned

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cugbjing** [comment]
I just found working example in the documentation. I would like to know why current method wouldn't work. Thanks!

**Comment by andreac92** [comment]
Is this on the roadmap to be fixed? Would be great if after unpinning, the row state could be moved back to the main state!

**Comment by cherniavskii** [comment]
I believe this demo covers how the controlled row pinning should be handled: https://mui.com/x/react-data-grid/row-pinning/#controlling-pinned-rows
Here is a working demo based on the example provided by the issue author: https://codesandbox.io/p/sandbox/awesome-sound-fymzmn
