### ISSUE TITLE
[pickers] ClockPicker's ArrowSwitcher Overlays PenIcon in DateTimePicker when showToolbar is true

### ISSUE THREAD

**Issue by lrtoenjes** [mui/mui-x#8015]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/vigilant-babbage-6nfbvk

The above sandbox was forked from the basic usage of the [DateTimePicker](https://mui.com/x/react-date-pickers/date-time-picker/#basic-usage) in the docs. Outside of upping the version to the latest, the only code change I made was add the `showToolbar` prop to the last `DateTimePicker` in the `Stack`.

Steps:
1. Open the date picker of the 3rd input
![image](https://user-images.githubusercontent.com/15257697/220774266-f45f51d9-e69e-421e-9498-1a665d39ad88.png)
2. Click on the time button in the popper
![image](https://user-images.githubusercontent.com/15257697/220774428-de210fcf-9168-4ad5-847a-1b865204cdb6.png)
3. Notice the `PickersArrowSwitcher` is displayed over the `PenIcon`
![image](https://user-images.githubusercontent.com/15257697/220774899-983cf166-28e7-4533-b9c6-1af0f1694785.png)

### Current behavior 😯

The `PickersArrowSwitcher` is displayed in an absolute position over the `PenIcon` in the `DateTimePicker` when the `showToolbar` prop is true:
![image](https://user-images.githubusercontent.com/15257697/220775428-58f5b6c4-0de1-4da9-997f-fdaf7ff7672e.png)

The `PickersArrowSwitcher` is a child of the `ClockPicker`, and neither the `ClockPicker` or its parent div have a defined `position` so the `PickersArrowSwitcher` gets rendered at the top of the popper.

### Expected behavior 🤔

I'd expect either the `ClockPicker` or it's parent div to at least have a `position` of `relative` so that the `PickersArrowSwitcher` displayed properly inside those. Otherwise, I'd expect the `ClockPicker` to be targetable from the `DateTimePicker` component so that I could customize its styling to control the positioning of the `PickersArrowSwitcher` in the popper. But that slot isn't available on the `DateTimePicker`.

Currently, my workaround is to define a style override in the theme for the `MuiClockPicker`:

```
MuiClockPicker: {
    styleOverrides: {
      root: {
        marginTop: theme.spacing(-2)
      },     
      arrowSwitcher: {
        alignSelf: 'flex-end',
        position: 'relative'
      }
    }
 },
```

This was easier than using CSS selectors and drilling down the child divs of the `DateTimePicker` itself in my component... But this workaround will not be sufficient if I use the `ClockPicker` anywhere else explicitly in my app.

Here's the result of my workaround:

![image](https://user-images.githubusercontent.com/15257697/220782493-d9a95234-ea20-475e-a494-bf77bce2f089.png)

### Context 🔦

The requirements of the project I'm working on, is that the date picker shows toolbar so that a user can see both the date and the time in the popper at the same time. It's not entirely necessary for me to have the `PickersArrowSwitcher` displayed... Perhaps there's a way to hide it?

**Comment by flaviendelangle** [comment]
@alexfauquette can I let you handle that one since you worked on improving the position of the icon ?

**Comment by flaviendelangle** [comment]
Hi,

The new major release (`6.0`) is currently in beta and should solve your problem because we no longer have this pen icon and because we have a new layout that should handle the position of this kind of elements correctly.

We are also working on a brand new UI for time picking on desktop.
You can have a look at #4483

**Comment by lrtoenjes** [comment]
@flaviendelangle We've only just migrated to MUI-X Pickers from the old MUI Pickers package. When is the `6.0` version slated for a release we can use in our production code? The replacement of the clock in #4483 is a much welcomed change for the desktop control 👍 Will either of those updates allow us to target new slots on the `DateTimePicker` for custom styling?

**Comment by flaviendelangle** [comment]
The v6.0 should become stable next week (or the week after if we have a last minute fix to apply).
Note that this major is nothing compared to the migration you just did, with only a few breaking change that impact a lot of users and codemods for most of them (see [the migration guide](https://next.mui.com/x/migration/migration-pickers-v5/) for more information).

> Will either of those updates allow us to target new slots on the DateTimePicker for custom styling?

The new architecture of the picker will allow you to totally override a view to build your own UI if you don't like the default one.
And inside the default views, we have a few slots, but we intend to add more in the near future (one for the header of the `day` view for example has been requested several time and is being implemented).
