### ISSUE TITLE
[TimePicker] Using moment doesn't call onChange on arrow keys

### ISSUE THREAD

**Issue by nphmuller** [mui/mui-x#8025]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/eloquent-sammet-1xnjnp?file=/demo.tsx

Steps:
1. Open console
1. Change the value via arrow keys up and down for all 3 pickers

### Current behavior 😯

Only the TimeField and the DateTimePicker call onChange (see console logs).
So TimePicker doesn't.

### Expected behavior 🤔

TimePicker should also call onChange when changing its value via the arrow keys.

### Context 🔦

The issue doesn't occur when using Day.js to construct the value. Other supported datetime adapters might have the same issue, but I only tested moment.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

2208761

**Comment by flaviendelangle** [comment]
Hi,

Thanks for testing our beta
I can reproduce the bug on your demo but not on `next`, I think #7993 fixed it.

**Comment by nphmuller** [comment]
That's great news. Thank you so much for the fast response!
