### ISSUE TITLE
[pickers] Reading slotProps is difficult due to typescript error

### ISSUE THREAD

**Issue by nphmuller** [mui/mui-x#8026]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/boring-currying-ehbf8t?file=/demo.tsx

The code example has the following typescript error:
> Property 'helperText' does not exist on type 'SlotComponentProps<(props: TextFieldProps) => Element, {}, Record<string, any>>'.

As you can see based on the result it is working, however.

Probably due to the usage of `Record` the usage of certain slotProps (like helperText) cannot be inferred properly.
This makes wrapping the pickers with our own components a lot harder.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

2208761

**Comment by flaviendelangle** [comment]
Hi,

What is your use case ?
Why do you need to access `props.slotProps?.textField?.helperText` ?

We plan on reworking the typing of our slots soon.
But we have a complex trade-off between typing them strictly (which solves your problem) and not throwing errors whenever people want to create custom text field that can actually receive props we don't expect.
