### ISSUE TITLE
[Pickers] v6 beta - Only show format placeholder on focus

### ISSUE THREAD

**Issue by nphmuller** [mui/mui-x#8027]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The current Pickers use a now format default value. While I like this a lot, in my opinion it looks a bit too aggressive. Especially with multiple date selectors in a single form. 

Would it be possible to only show this default format when the input has focus? So by default (just like the other fields) show the label over the input. And when the picker has a value, or focus, show the value or formatted placeholder.

So instead of this:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/3781551/220961107-11ad392d-7782-4f75-96ac-3ae1bc499121.png">

It would look like this:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3781551/220961680-ebd4d1c1-dc80-4c44-b7b4-1d3ff7deac50.png">

And it would only look like the 1st screenshot when the user has focus on the input.

This behaviour already existed the MUI 5 date picker. Although a lot has changed in v6 of course.

### Order ID 💳 (optional)

2208761

**Comment by LukasTy** [comment]
Thank you for trying out the beta and reporting this finding @nphmuller! 🙏 
We've also recently identified this inconsistency and [decided to proceed](https://github.com/mui/mui-x/issues/4592#issuecomment-1438514712) with your described solution.
Closing this as a duplicate. Feel free to follow the linked issue if you want to follow the progress on it. 😉
