### ISSUE TITLE
[question] Editing Data Grid Date - Day goes back one day

### ISSUE THREAD

**Issue by TaylorBruening** [mui/mui-x#8065]
### Order ID 💳

58019

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Putting Material Data Grid cells of column type: "date" into mode: "Edit" with a date format of: "yyyy-mm-dd", _always moves the date back one day when in edit mode_.

For example, a cell in the grid contains the date: "2021-08-27", putting the cell into edit mode will always move the date back one day, in this case to: "2021-08-26". Discarding the changes of the edit will set the date back to the original: "2021-08-27".

Here are some image examples:
before:
![image](https://user-images.githubusercontent.com/31892579/221616356-e30fca37-c148-45e7-a37c-edc771d792ce.png)

after:
![image](https://user-images.githubusercontent.com/31892579/221616491-80a3732d-e89b-4a18-ab48-d0a8e36e21cd.png)

I am just using the default code via this example: 
https://next.mui.com/x/react-data-grid/editing/#full-featured-crud-component

My column definition for these dates is:
` {
        field: 'Date',
        headerName: 'Date',
        type: 'date',
        editable: true,
        flex: 1,
    },`

The date object is coming into the grid data as string, no special formatting, so just:  "2021-08-27" for example

### Your environment 🌎
Using Chrome browser
<details>
  <summary>`npx @mui/envinfo`</summary>
  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 16.19.0 - /usr/bin/node
    Yarn: Not Found
    npm: 8.19.3 - /usr/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.5 
    @emotion/styled: ^11.10.4 => 11.10.5 
    @mui/base:  5.0.0-alpha.113 
    @mui/core-downloads-tracker:  5.11.4 
    @mui/icons-material: ^5.10.3 => 5.11.0 
    @mui/lab: ^5.0.0-alpha.115 => 5.0.0-alpha.115 
    @mui/material: ^5.10.5 => 5.11.4 
    @mui/private-theming:  5.11.2 
    @mui/styled-engine:  5.11.0 
    @mui/system:  5.11.4 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.2 
    @mui/x-data-grid: ^5.17.25 => 5.17.25 
    @mui/x-data-grid-premium: ^5.17.25 => 5.17.25 
    @mui/x-data-grid-pro:  5.17.25 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react:  18.0.26 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.9.5 
</details>

**Comment by alexfauquette** [comment]
This looks like a timezone problem.

I'm nor sure to get what you mean by "a cell in the grid contains the date: `2021-08-27`". If you provide a string "yyyy-mm-dd" instead of a `Date` object, it can lead to some timezone problems depending on the browser you're using. 

Could you provide a reproduction example of your bug? The code sandbox of the demo you linked might be a good starting point.
https://codesandbox.io/s/tt1roz?file=/demo.tsx

**Comment by TaylorBruening** [comment]
Yes it appears Material UI default behavior when trying to process a string like: "2022-05-03", when converted to a date under the hood will default to date object like this: `Mon May 02 2022 19:00:00 GMT-0500 (Central Daylight Time)`
Solution for me at least, is to not rely on Material UI grid to figure out I want a date that is May 3rd, and instead manually make a date object from my data retrieved from the database, and specify a timezone in the date object that puts it to the correct date...

Like so: 
`const newData = items.map(item => ({
  ...item,
  date: item.date ? new Date(Date.parse(item.date + 'T00:00:00')) : ''
}));`


For the Material UI team, data grid should definitely be able to figure this out. I find it a bit ridiculous that a simple string like: '2022-05-03' needs to be processed into a date object with a timezone before getting passed into the grid.
It should go without explanation that string should be automatically get converted to a date with the same month/day/year

**Comment by alexfauquette** [comment]
I recommend you to add the timezone in your date parser: 

```diff
-Date(Date.parse(item.date + 'T00:00:00')) 
+Date(Date.parse(item.date + 'T00:00:00Z')) 
```

> Note: When parsing date strings with the Date constructor (and Date.parse, they are equivalent), always make sure that the input conforms to the ISO 8601 format (YYYY-MM-DDTHH:mm:ss.sssZ) — the parsing behavior with other formats is implementation-defined and may not work across all browsers. Support for [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822) format strings is by convention only. A library can help if many different formats are to be accommodated.
>
>Date-only strings (e.g. "1970-01-01") are treated as UTC, while date-time strings (e.g. "1970-01-01T12:00") are treated as local. You are therefore also advised to make sure the input format is consistent between the two types.

From: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

---

> data grid should definitely be able to figure this out


In v6 the grid will enforce the use of `Date` object to avoid hidden problems with timezone
