### ISSUE TITLE
GridPrintExportOptions 

### ISSUE THREAD

**Issue by 21Ovi** [mui/mui-x#8101]
### Duplicates

- [x] I have searched the existing issues

### Related page

https://mui.com/x/api/data-grid/grid-print-export-options/

### Kind of issue

Missing information

### Issue description

need more ways how to use this prop or is this a component?

**Comment by MBilalShafi** [comment]
Please refer to this [documentation page](https://mui.com/x/react-data-grid/export/#print-export) to know more about how to use Print export functionality.

In next release the documentation for interfaces will be [updated](https://deploy-preview-8028--material-ui-x.netlify.app/x/api/data-grid/grid-print-export-options/) to reflect the related demos.
