### ISSUE TITLE
LoadingButton within DataGrid Pro  renderCell function changes loading state of every row button 

### ISSUE THREAD

**Issue by rainabozhi** [mui/mui-x#8124]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. specify data grid row definition with a field containing a LoadingButton
2. render LoadingButton within renderCell field function 
3. change loading state of button on click 

### Current behavior 😯

Instead of updating the loading state of the clicked button only to true, every button on each cell gets the loading state. 

### Expected behavior 🤔

only the clicked LoadingButton changes loading state 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.0.1
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Edge: Not Found
    Firefox: 110.0
    Safari: 16.1
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.117 
    @mui/core-downloads-tracker:  5.11.8 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/lab: ^5.0.0-alpha.119 => 5.0.0-alpha.119 
    @mui/material: ^5.11.8 => 5.11.8 
    @mui/private-theming:  5.11.7 
    @mui/styled-engine:  5.11.8 
    @mui/system: ^5.11.8 => 5.11.8 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.7 
    @mui/x-data-grid:  5.17.23 
    @mui/x-data-grid-pro: ^5.17.23 => 5.17.23 
    @mui/x-date-pickers: ^5.0.18 => 5.0.18 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react: ^18.0.28 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 

```
</details>

**Comment by rainabozhi** [comment]
After some research I was able to find a solution- 
so whenever using a LoadingButton within the renderCell function, one needs to set the loading state of the button to the params.row.id so that the state isn't shared all over the data grid.

**Comment by mfalthaw** [comment]
> ... one needs to set the loading state of the button to the params.row.id so that the state isn't shared all over the data grid.

Hi @rainabozhi, can you elaborate more, how did you achieve the desired behaviour? Thanks!

**Comment by rainabozhi** [comment]
@mfalthaw  hey sorry for the late reply - I was away for the holidays. 

So basically what we did was in the gridColumnDefinition (where you define what your columns are)- we set one of the columns to display a button via the renderCell prop like so- 

 renderCell: (params: GridRenderCellParams) => {
        return (
            <ButtonPrimaryLoading
              loading={fetchDataIsLoading === params.row.id}
              disabled={fetchDataIsLoading !== null }
              onClick={() => {
                handleDownloadData(params.row.name, params.row.id);
              }}
            >
              {t('retrieveData')}
            </ButtonPrimaryLoading>
        );
      },
      
      
      In more detail what happens here is that the onClick function gets executed with the params.row.id as a second parameter- within that function we update the useState for setFetchDataIsLoading(params.row.id) (where fetchDataIsLoading is string || null - and is initially set to null. 
      
      So that then when loading={fetchDataIsLoading === params.row.id} resolves to true - that is the only button to get the loading state updated based on that row id. 
      
      
 I hope this helps!

**Comment by mfalthaw** [comment]
> @mfalthaw hey sorry for the late reply - I was away for the holidays.
> 
> So basically what we did was in the gridColumnDefinition (where you define what your columns are)- we set one of the columns to display a button via the renderCell prop like so-
> 
> ```
>  renderCell: (params: GridRenderCellParams) => {
>         return (
>             <ButtonPrimaryLoading
>               loading={fetchDataIsLoading === params.row.id}
>               disabled={fetchDataIsLoading !== null }
>               onClick={() => {
>                 handleDownloadData(params.row.name, params.row.id);
>               }}
>             >
>               {t('retrieveData')}
>             </ButtonPrimaryLoading>
>         );
>       },
>       
>       
> ```
> 
> In more detail what happens here is that the onClick function gets executed with the params.row.id as a second parameter- within that function we update the useState for setFetchDataIsLoading(params.row.id) (where fetchDataIsLoading is string || null - and is initially set to null.
> 
> So that then when loading={fetchDataIsLoading === params.row.id} resolves to true - that is the only button to get the loading state updated based on that row id.
> 
> I hope this helps!

@rainabozhi thank you for responding, idk how I missed your notification, funnily enough, landed on this page when I was searching for inspiration on how to tackle this :)
