### ISSUE TITLE
[pickers]: onAccept not triggered if value is not modified and component is not controlled

### ISSUE THREAD

**Issue by BC-M** [mui/mui-x#8129]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: 
- https://codesandbox.io/s/pedantic-sun-5enosl?file=/demo.tsx
- https://codesandbox.io/s/sweet-cherry-65t3pg?file=/demo.tsx

Steps:
1. Open picker
2. Press "OK" without select other date/time
3. See that onAccept not triggered

### Current behavior 😯

If the user opens the picker and accepts the default value by pressing OK, onAccept will not be triggered. If the user changes the date/time and then presses OK, onAccept is triggered.

### Expected behavior 🤔

Trigger onAccept even if default date/time is not updated.

### Context 🔦

We open the picker automatically so that the client can select and confirm an appointment. In doing so, we hide the input field. If the user cancels the date selection by simply closing the picker without making a selection, the entire process is cancelled. Now we want to pre-select a specific date so that the customer can simply continue with "OK" if necessary. Unfortunately, in this problem we cannot distinguish between "Date selection closed / cancelled" and "Date selection made".

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
 System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react: 11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.119 
    @mui/core-downloads-tracker:  5.11.11 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/material: ^5.11.11 => 5.11.11 
    @mui/private-theming:  5.11.11 
    @mui/styled-engine:  5.11.11 
    @mui/system: ^5.11.11 => 5.11.11 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.11 
    @mui/x-date-pickers: ^6.0.0 => 6.0.0 
    @types/react: ^18.0.28 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 

</details>

**Comment by BC-M** [comment]
In the [second example](https://codesandbox.io/s/sweet-cherry-65t3pg?file=/demo.tsx), onAccept is not called even if I open the picker, click on another date, select the original date again and confirm the picker with "OK".

**Comment by LukasTy** [comment]
> Shouldn't `onAccept` be called in any scenario? Currently, it's behaving more or less like `onChange`, however, the user only wants to trigger an action when "OK" is pressed.

That's a good point worth investigating. This could be the case, or maybe not always, but at least with a different rule than not being equal to the previous value. 👍

**Comment by karthik199801** [comment]
Is there any possible way to trigger the onChange and onAccept event without choosing the time and date, on the onaccept event I am handling the custom Function in the onAccept event in the mobiletimepicker, is there any possibility to trigger the onChange and onAccept event?. Can you give me the solution

**Comment by alexfauquette** [comment]
@karthik199801 Please open an issue with an example of what you're trying to achieve, such that the team can track progress on answering your issue
