### ISSUE TITLE
[docs] Specify type for `ownerState` (instead of any)

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#8149]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-date-pickers/date-picker/#custom-input-component

### Kind of issue

Missing information

### Issue description

I'm migrating from v5, and trying replace `renderInput`.

In order to render my custom input correctly, I need stuff from `ownerState`, and I follow the example linked above, but `ownerState` is typed as `any` which is not very nice.

```tsx
type BrowserInputProps = TextFieldProps & {
  ownerState?: any;
};
```

**Comment by flaviendelangle** [comment]
I'm building better examples with custom fields in https://github.com/mui/mui-x/pull/8034

If you can describe me what your trying to achieve, I can give you some help.
The ownerstate is equal to the props received by the field.
So for a `DateField` it will equal `DateFieldProps`.

**Comment by MonstraG** [comment]
Yea, so `DateFieldProps<Dayjs>` or something like that.

**Comment by MonstraG** [comment]
Btw, if you are working on custom fields examples, I found it very tricky to replace the  `textField` slot with a <Button/> in v6 compared to v5.

For context, I am trying to implement something like this:
![image](https://user-images.githubusercontent.com/17963791/223227556-89278af7-bcab-40ff-a08f-f3a55a086b38.png)

But it seems that in v6 it's kind of hard coded to look for selection position in the input.

**Comment by flaviendelangle** [comment]
> Btw, if you are working on custom fields examples, I found it very tricky to replace the textField slot with a in v6 compared to v5.


The paradigm changed a lot before v5 and v6.
You should probably look into overriding `field` if you are doing structural changes (like it seems you are).
If you can have a look at my PR and maybe try an implementation, that would help me building the best examples possible (and I can of course help you if something is not clear).

Basically what we will recommend:

- `textField` is to do small customization on the input (change the `variant` or the `size`)
- `field` is to do structural changes
