### ISSUE TITLE
[docs] inaccuracies in v6 migration guide componentsProps

### ISSUE THREAD

**Issue by lnhrdt** [mui/mui-x#8151]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/migration/migration-pickers-v5/#input-renderer-required-in-v5

### Kind of issue

Broken demonstration

### Issue description

I noticed an inaccuracy in the v6 migration guide for pickers. The object passed to componentProps doesn't have an `input` property. Based on my experimentation I believe it should be `textField` instead.

In the diff, the `componentsProps` lines are also missing a closing `}`.

https://mui.com/x/migration/migration-pickers-v5/#input-renderer-required-in-v5

https://github.com/mui/mui-x/blob/67cffb1cf5fec20361faffde92020d208849d901/docs/data/migration/migration-pickers-v5/migration-pickers-v5.md?plain=1#L422-L442

CC: @LukasTy & @flaviendelangle

**Comment by flaviendelangle** [comment]
Thanks !
We renamed this slot some weeks ago and missed this occurence in the doc, I'll do a quick fix, it's indeed `textField`
