### ISSUE TITLE
[data grid] Incorrect `pageSizeOptions` warning in the console

### ISSUE THREAD

**Issue by yudielcurbelo** [mui/mui-x#8153]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/elastic-haslett-yc1p45?file=/demo.tsx

Steps:
1. set pageSizeOptions to zero as default and wait for data to be loaded
2. once the page is loaded set pageSizeOptions to the amount of items in the response
3. check console got a warning

```
MUI: The page size `0` is not preset in the `pageSizeOptions`
Add it to show the pagination select.
```

### Current behavior 😯

A warning is being thrown.

### Expected behavior 🤔

There should not be a warning since the pageSizeOptions state is being updated and both the pageSizeOptions and paginationModel are referencing the same state.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 14.21.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 110.0.5481.178 (Official Build) (64-bit)
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.57)
```
</details>

**Comment by MBilalShafi** [comment]
It's because when the `paginationModel.pageSize` prop is updated, it's not reflected in paginationModel until the next render so when the comparison is made between `pageSizeOptions` prop and `pageSize` state, it throws a warning.

One way to fix it could be to do a comparison with  `paginationModel.pageSize` prop if it exists, or otherwise use the normal comparison, following diff shows that in a code change:

```diff
diff --git a/packages/grid/x-data-grid/src/components/GridPagination.tsx b/packages/grid/x-data-grid/src/components/GridPagination.tsx
index 2271ca3d5..8eba341b8 100644
--- a/packages/grid/x-data-grid/src/components/GridPagination.tsx
+++ b/packages/grid/x-data-grid/src/components/GridPagination.tsx
@@ -61,11 +61,11 @@ export const GridPagination = React.forwardRef<HTMLDivElement, Partial<TablePagi
     if (process.env.NODE_ENV !== 'production') {
       // eslint-disable-next-line react-hooks/rules-of-hooks
       const warnedOnceMissingInPageSizeOptions = React.useRef(false);
-
+      const pageSize = rootProps.paginationModel?.pageSize ?? paginationModel.pageSize;
       if (
         !warnedOnceMissingInPageSizeOptions.current &&
         !rootProps.autoPageSize &&
-        !rootProps.pageSizeOptions.includes(paginationModel.pageSize)
+        !rootProps.pageSizeOptions.includes(pageSize)
       ) {
         console.warn(
           [
```

This should be fixed in the next release or feel free to open up a PR if you want.

**Comment by yudielcurbelo** [comment]
> It's because when the `paginationModel.pageSize` prop is updated, it's not reflected in `pageSize` state until the next render so when the comparison is made between `pageSizeOptions` prop and `pageSize` state, it throws a warning.
> 
> One way to fix it could be to do a comparison with `paginationModel.pageSize` prop if it exists, or otherwise use the current comparison, following `diff` shows that in code:
> 
> ```diff
> diff --git a/packages/grid/x-data-grid/src/components/GridPagination.tsx b/packages/grid/x-data-grid/src/components/GridPagination.tsx
> index 2271ca3d5..8eba341b8 100644
> --- a/packages/grid/x-data-grid/src/components/GridPagination.tsx
> +++ b/packages/grid/x-data-grid/src/components/GridPagination.tsx
> @@ -61,11 +61,11 @@ export const GridPagination = React.forwardRef<HTMLDivElement, Partial<TablePagi
>      if (process.env.NODE_ENV !== 'production') {
>        // eslint-disable-next-line react-hooks/rules-of-hooks
>        const warnedOnceMissingInPageSizeOptions = React.useRef(false);
> -
> +      const pageSize = rootProps.paginationModel?.pageSize ?? paginationModel.pageSize;
>        if (
>          !warnedOnceMissingInPageSizeOptions.current &&
>          !rootProps.autoPageSize &&
> -        !rootProps.pageSizeOptions.includes(paginationModel.pageSize)
> +        !rootProps.pageSizeOptions.includes(pageSize)
>        ) {
>          console.warn(
>            [
> ```
> 
> This should be fixed in an upcoming patch or feel free to open up a PR if you want.

pageSize is updated and passed to paginationModel and pageSizeOptions; it should update both in the same render.

**Comment by MBilalShafi** [comment]
> pageSize is updated and passed to paginationModel and pageSizeOptions; it should update both in the same render.

That is true for the `paginationModel.pageSize` prop, but the comparison was made with the internal state, not the prop. The value of the internal state gets updated on the next render due to which the comparison is already made.

The diff I shared above should address that issue.

**Comment by romgrk** [comment]
@MBilalShafi want me to open a PR for this? Is there anything else to do other than apply the patch you posted above?

**Comment by MBilalShafi** [comment]
Sure, feel free to open up a PR.

**Comment by royyoung388** [comment]
I found another way to fix this problem after `patch-package` doesn't work for me.
The only thing need to do is set `pageSizeOptions = [0]` when there is no data in Grid, and modify back to `[pageSize]` when data is ready.
```
pageSizeOptions = [data.length === 0 ? 0 : pageSize],
```
