### ISSUE TITLE
[DataGridPro] - What to do when you want to display a horizontal scroll bar at the top of a table

### ISSUE THREAD

**Issue by GunjiKamiya** [mui/mui-x#8154]
### Order ID or Support key 💳 (optional)

57585

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

This is not necessary when using a trackpad on a Mac.
They are needed when using a regular mouse on Windows.

Currently, the horizontal scrolling displayed in DataGridPro is at the bottom of the table.
However, if one wants horizontal scrolling from the beginning, the user has to go all the way to the bottom of the table.

Is there a way for the community to solve these?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
I'd like to know more about the concern other than going all the way to the bottom, (which I believe you can resolve with fixed height like [this example](https://codesandbox.io/s/44y8m0?file=/demo.tsx))

By the way, a similar request is already made and discussed in this issue: https://github.com/mui/mui-x/issues/6131

Feel free to upvote the issue or share your concerns there, I'll close this one to avoid scattering information on multiple issues.

**Comment by GunjiKamiya** [comment]
Thank you very much.
The problem I was having could be solved in the way you have presented it.
