### ISSUE TITLE
[fields] Token `do` is not supported using the `date-fns` adapter

### ISSUE THREAD

**Issue by jfsimon** [mui/mui-x#8157]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Use the `DatePicker` component
2. Use `eeee, LLLL do, yyyy` or `PPPP` as `format`

### Current behavior 😯

The date picker throws the following error:

```
Error: MUI: The token "do" is not supported by the Date and Time Pickers.
Please try using another token or open an issue on https://github.com/mui/mui-x/issues/new/choose if you think it should be supported.
```

### Expected behavior 🤔

Format the date using the documented `do` token.
See: https://date-fns.org/v2.29.3/docs/format

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177 <-- I use this browser
    Edge: Not Found
    Firefox: 110.0.1
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.119
    @mui/core-downloads-tracker:  5.11.12
    @mui/icons-material: ^5.11.11 => 5.11.11
    @mui/material: ^5.11.12 => 5.11.12
    @mui/private-theming:  5.11.12
    @mui/styled-engine:  5.11.11
    @mui/system: ^5.11.12 => 5.11.12
    @mui/types:  7.2.3
    @mui/utils:  5.11.12
    @mui/x-date-pickers: ^6.0.0 => 6.0.0
    @types/react: 18.0.28 => 18.0.28
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

We indeed don't support digits with letter at the end (`1st` / `2nd` in english `1er` / `2ème` in french for example).
That's probably the biggest family of format we have to add support for.

Is this format a custom one you are passing to your library, or is it a default format the picker is putting by itself ?
