### ISSUE TITLE
[DataGrid] Controlled `checkboxSelection` query

### ISSUE THREAD

**Issue by 21Ovi** [mui/mui-x#8158]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

suppose we have a datagrid and we want to select few rows which will be stored in some kind of form management system in my case Formik, so after selecting certain data rows currently we can access id from checkboxSelection props but when we make changes and give id in initial values of that checkbox where we are storing it won't be checked if we come to page next time because checkboxSelection is just giving us id of a selected cell rather then that I suggest a new row so that we can access modified state with checked

### Examples 🌈

![image](https://user-images.githubusercontent.com/92392084/223348213-7a509d47-a6ac-484d-9fae-1def83ddb5a2.png)
this is how DataGrid should render if there is checked values

**Comment by MBilalShafi** [comment]
It seems like you are looking for controlled row selection, I've added a controlled row selection scenario with `checkboxSelection` enabled in this [codesandbox](https://codesandbox.io/s/fervent-ritchie-k1t9ml?file=/demo.tsx).

Let me know if this is something you are looking for, if not, it'll be helpful if you provide a minimal reproduction of the issue in some codesandbox example, you can use [this codesandbox](https://codesandbox.io/s/data-grid-community-forked-0cwynf) as the starting point.

**Comment by 21Ovi** [comment]
![image](https://user-images.githubusercontent.com/92392084/223379262-42d29580-4631-47f0-aa28-25942fcbea12.png)
I need to get selected cells even after using as u used I am not getting cells selected am I missing something, and thanks by the way, really appricieated

**Comment by 21Ovi** [comment]
![image](https://user-images.githubusercontent.com/92392084/223379668-4a60ab47-ed4b-4397-ba09-436643c362de.png)
here is the rowSelectionModel useState, i am not using typescript and I tested in your sandbox it only requires rowId which I am passing

**Comment by 21Ovi** [comment]
Thank you for your concern, but it worked with selectionModel I don't know why it didn't worked with rowSelectionModel.

![image](https://user-images.githubusercontent.com/92392084/223401779-d1f68e66-9404-48c3-9b03-2ecab74355b7.png)

**Comment by 21Ovi** [comment]
Now I am not able to select (check other checkbox)

**Comment by MBilalShafi** [comment]
Glad it worked out 🎉, just to let you know why it didn't work with `rowSelectionModel` is because it was [renamed](https://mui.com/x/migration/migration-data-grid-v5/#%E2%9C%85-renamed-props) from `selectionModel` in v6, and you must be using v5 (where it was called `selectionModel`).

I'd recommend you to upgrade to v6 for [more features](https://mui.com/x/whats-new/) and bug fixes and meanwhile you can consult [v5 documentation](https://v5.mui.com/x/react-data-grid/) to avoid such issues and another tweak would be to start using TypeScript which gives type intellisense to avoid such issue.
