### ISSUE TITLE
[pickers] DateTimePicker: Re-enabling clock on desktop not working; missing type definitions

### ISSUE THREAD

**Issue by kas1337** [mui/mui-x#8161]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

In the migration docs from v5 to v6 it says that you can re-enable the display of the clock by edititing the theme. See https://mui.com/x/migration/migration-pickers-v5/#stop-rendering-a-clock-on-desktop.

However, when you do this you get a type error since `MuiDesktopTimePicker` and `MuiDesktopDateTimePicker` are not defined in the type definitions

**Comment by flaviendelangle** [comment]
Hi,

Does following [this section](https://mui.com/x/react-date-pickers/base-concepts/#typescript) fix your problem ?

**Comment by kas1337** [comment]
Hi,

yes, it does. Thank you very much! I did not know about that necessary import.
