### ISSUE TITLE
disableRowSelectionOnClick prop is not working on DataGrid Component

### ISSUE THREAD

**Issue by 21Ovi** [mui/mui-x#8163]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/92392084/223419038-3e9eabe4-a866-4341-902a-6ebe652a5382.png)
![image](https://user-images.githubusercontent.com/92392084/223419072-70b429ec-7180-4ab9-ab21-91608e8580d3.png)

on clicking on anywhere on a cell the checkbox is getting selected even after applying this prop

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Please check [v5 docs](https://v5.mui.com/x/react-data-grid/selection/#disable-selection-on-click) if you are on v5.

Also check https://github.com/mui/mui-x/issues/8158#issuecomment-1457968043 for more information.
