### ISSUE TITLE
[question] Can the DataGrid Column Header 'kebab' Menu be Defined as Always Visible?

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#8172]
### Order ID or Support key 💳 (optional)

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Currently, the DataGrid column header 'kebab' menu is only visible on hover. Would like it to always be visible. Is it possible to do this?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
You can `gridClasses.menuIcon` to achieve that.

```tsx
<DataGrid
  rows={rows}
  columns={columns}
  sx={{
    [`& .${gridClasses.menuIcon}`]: {
       visibility: "visible",
       width: "auto"
    }
  }}
/>
```

I've added the change to a [codesandbox](https://codesandbox.io/s/data-grid-community-forked-k0v935?file=/src/App.tsx) to reflect the change. (You may also need to do the same for `gridClasses.columnSeparator` for a more aligned UI)
