### ISSUE TITLE
DataGrid not displaying horizontal scrollbar anymore when nested in Grid

### ISSUE THREAD

**Issue by JeremyKj87** [mui/mui-x#8175]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/datagrid-6-0-0-in-grid-70lzhp?file=/demo.tsx

Steps:
1. In this Code Sandbox, we have a wide DataGrid with columns using `minWidth` and `flex` contained in a Grid layout. The DataGrid is cut off at the end of the Card and no horizontal scrollbar appears.
2. Change the version of the @mui/x-datagrid dependency to 5.17.26 to see the previous, correct behaviour.
3. If you change the version back to 6.0.0 and remove the Grid around the DataGrid, it behaves correctly as well.

### Current behavior 😯

My application is built with a Grid layout, therefore I have several wide DataGrids (many columns) contained in Grid items.
After upgrading to @mui/x-datagrid 6.0.0, DataGrids that are wider than the screen are cut off at the edge of the container and do not display a horizontal scrollbar anymore.
If I remove the Grid so that the DataGrid sits directly in the CardContent, it behaves correctly.

### Expected behavior 🤔

DataGrids that are wider than the screen should fit in their surrounding Grid layout and display a horizontal scrollbar for accessing the rightmost columns.

**Comment by MBilalShafi** [comment]
We [improved](https://github.com/mui/mui-x/pull/7001) virtual scroller and column headers positioning logic in v6, this issue might be produced as a side effect. 

A quick workaround could be to define a width for the parent `Grid` of `DataGrid` component. I tried to do that in this [codesandbox](https://codesandbox.io/s/datagrid-6-0-0-in-grid-forked-dr6fd3?file=/demo.tsx) and scroll seems to show up now as before.

**Comment by JeremyKj87** [comment]
The workaround helps for now, thanks!

**Comment by cherniavskii** [comment]
@JeremyKj87 Thanks for reporting this!
I think it's expected behavior though - see this example that uses the wide scrollable element instead of the grid.
It won't scroll unless you set `sx={{ width: "100%" }}` to `Grid` item component:
https://codesandbox.io/s/datagrid-6-0-0-in-grid-forked-hjxcun?file=/demo.tsx

**Comment by luan-dang-techlabs** [comment]
@MBilalShafi - Is there known issue of having <DataGridProp> inside "display: 'grid" containers? I noticed when I add <DataGridProp> inside "display: grid" the grid will stretch the width especially when I have columns with 'minWidth' properties. 

```
 <Box sx={{display: 'grid', gridTemplateColumns: '1fr'}}>
    <DataGridPro/>
</Box>
```
