### ISSUE TITLE
Not able to use disbale editable with props

### ISSUE THREAD

**Issue by 21Ovi** [mui/mui-x#8185]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1.
2.
3.

### Current behavior 😯

![image](https://user-images.githubusercontent.com/92392084/223934735-5862a99e-2863-453d-99cf-5d50a8933e9e.png)
![image](https://user-images.githubusercontent.com/92392084/223934784-f79227a4-a562-4da2-8792-e59568d0c37c.png)
![image](https://user-images.githubusercontent.com/92392084/223934829-f78a220c-1de4-4904-9620-2c8d7dd9d065.png)

All I want to achieve is to make that ediable box enable when the checkbox is checked but not able to do, can u please help me out on that

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
If you want to make certain cells belonging to a row editable only if the row is selected (checkbox is checked), you can use `isCellEditable` prop and `apiRef.current.isRowSelected`.

Here's a codesandbox where I tried to do it: https://codesandbox.io/s/thirsty-grass-8csndr?file=/demo.tsx

**Comment by 21Ovi** [comment]
thanks
