### ISSUE TITLE
[question] How to use pagination with `treeData`?

### ISSUE THREAD

**Issue by kari-j** [mui/mui-x#8190]
### Order ID or Support key 💳 (optional)

59097

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

https://mui.com/x/react-data-grid/tree-data/
i try pagination same datagrid in treedata, but not work.

<DataGridPro 
  treeData
  rows={rows}
  columns={columns}
  getTreeDataPath={getTreeDataPath}
  groupingColDef={groupingColDef}
  components={{
    Pagination: <Pagination  color="primary"
            variant="outlined"
            shape="rounded"
            page={page}
            count={pageTotal} />
  }} 
/>

How can I apply pagination to treedata?

### Your environment 🌎

<details>
   
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/base": "^5.0.0-alpha.118",
    "@mui/icons-material": "^5.11.9",
    "@mui/lab": "^5.0.0-alpha.120",
    "@mui/material": "^5.11.11",
    "@mui/system": "^5.8.2",
    "@mui/x-data-grid": "^5.17.25",
    "@mui/x-data-grid-pro": "^5.17.24",

    "react": "18.2.0",
    "react-dom": "18.2.0",
</details>

**Comment by MBilalShafi** [comment]
You need to add a `pagination` prop and define the correct pagination options. 
I was able to use pagination with the basic [example](https://mui.com/x/react-data-grid/tree-data/) of treedata in this [codesandbox](https://codesandbox.io/s/lucid-sound-kg1uif?file=/demo.tsx).

Let me know if that is similar to what you are trying to achieve.

**Comment by kari-j** [comment]
@MBilalShafi thanks you so much,  your examples very useful for me. 
update data-grid version v6, pagination option worked

**Comment by MBilalShafi** [comment]
@kari-j Glad it helped 🎉
