### ISSUE TITLE
Numbers in a "number" columns are rounded to 3 decimal places. How can I change it to 4 decimal places?

### ISSUE THREAD

**Issue by armendo** [mui/mui-x#8195]
### Order ID or Support key 💳 (optional)

53035

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I work with small numbers. I realized that the grid rounds numbers to 3 decimal places. Is there a way to change it to 4 decimal places?

Example:
https://codesandbox.io/s/serene-wu-czl5jo?file=/demo.js

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
With the following column definition
```js
valueFormatter: ({ value }) => value.toString()
```

Here is the docs about `valueFormatter`
https://mui.com/x/react-data-grid/column-definition/#value-formatter

Your codesandbox fixed:
https://codesandbox.io/s/reverent-gates-i06g88?file=/demo.js:375-435
