### ISSUE TITLE
[pickers] Can't change the size of the previous / next icons

### ISSUE THREAD

**Issue by stevus** [mui/mui-x#8206]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to be able to control the size of the next / previous buttons in the StaticDateRangePicker date range calendar selection.

![image](https://user-images.githubusercontent.com/1261603/224377069-e7425cff-96bd-4e78-9522-199e3ddc9946.png)

right now these are forced to `fontSize` of "small"

https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.tsx#L111

https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.tsx#L128

### Examples 🌈

https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.tsx#L111

https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/components/PickersArrowSwitcher/PickersArrowSwitcher.tsx#L128

### Motivation 🔦

I have a custom date picker component where I use the standard StaticDateRangePicker w/ no modifications beyond the spec, with the "small" right icon showing (example here)

![image](https://user-images.githubusercontent.com/1261603/224377754-ad279608-9869-4063-8f3d-6a8483fc6eee.png)

and a custom component to the right using a icon w/ a medium font size (example here)

![image](https://user-images.githubusercontent.com/1261603/224378232-365932b1-ec57-4921-86a8-aa20bce02991.png)

I've also indicated the icon DOM for the icon in the date range component.

The differences in sizes is causing a layout issue and I don't have a way to control the padding of the date range icon.

**Comment by flaviendelangle** [comment]
Hi,

We have a small bug, our icons don't have `fontSize: 'inherit'`, so changing the size on the button won't have any effect.
The current size is equivalent to "medium".

I'll do the fix, and once it's done, you'll be able to change the size using the slot as follow:

```tsx
      <StaticDateRangePicker
        slotProps={{
          previousIconButton: { size: 'large' },
          nextIconButton: { size: 'large' },
        }}
      />
```

**Comment by flaviendelangle** [comment]
Yes it will :+1:

**Comment by LukasTy** [comment]
I'm looking into aligning the DateCalendar header based on the updated design and I feel that the change that was made here was not correct, even based on the MUI Material doc.
The [`IconButton doc`](https://mui.com/material-ui/react-button/#sizes-2) clearly shows examples of changing both (IconButton and Icon) as well as separate sizes.
Based on our design we'd need to go with the previous solution: small `IconButton` with `medium` -> default Icon size.

The icon props can easily be overridden as per request using:
```tsx
slotProps={{
  leftArrowIcon: {
    fontSize: 'inherit',
  },
  rightArrowIcon: {
    fontSize: 'inherit',
  },
}}
```
