### ISSUE TITLE
date-pickers

### ISSUE THREAD

**Issue by arshak-grigoryan** [mui/mui-x#8216]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
![image](https://user-images.githubusercontent.com/52595017/224571002-e8368b16-0178-4496-90a5-3424d319b83e.png)

version - "@mui/x-date-pickers-pro": "^6.0.1",
Steps:
1.
2.
3.

### Current behavior 😯

in local mode everything works fine,
but in the build I'm getting this
![image](https://user-images.githubusercontent.com/52595017/224571087-ba853418-258e-4697-8d76-b526a613ee62.png)

### Expected behavior 🤔

there should not be errors

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: Windows 10 10.0.22621
    @mui/styled-engine: ^5.11.11 => 5.11.11
    @mui/system:  5.11.12
    @mui/types: ^7.2.3 => 7.2.3
    @mui/utils:  5.11.12
    @mui/x-data-grid: ^6.0.1 => 6.0.1
    @mui/x-date-pickers:  6.0.1
    @mui/x-date-pickers-pro: ^6.0.1 => 6.0.1
    @mui/x-license-pro:  6.0.1
    @types/react: ^18.0.24 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^5.3.8 => 5.3.8
    typescript: ^4.6.4 => 4.9.5
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq?file=/src/App.tsx) might be a good starting point.
