### ISSUE TITLE
[data grid] Total Line Row Becomes Offset with Column Pinning

### ISSUE THREAD

**Issue by tjgibbs92** [mui/mui-x#8237]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/nice-matan-q96dyo?file=/src/App.jsx

This happens when the System Display Scale is set to 125% or higher, which is the default setting for the laptops.

Steps:
1.  Resize the first column to trigger the labels to wrap text
2.  The Total row, first column jumps outside of the pinned column area.

We notice this is caused when we apply a `sx` of `py` to the rows to give them a little more breathing room.
Commenting out the `Box sx` property works as expected. But I wouldn't expect a vertical padding to cause the entire row to become offset.

### Current behavior 😯

When the first column's text wraps, it causes the total row to offset and not show the proper aggregations in the row. It hides behind the first columns box.

### Expected behavior 🤔

The total row should match the size of the column and not become offset when the first column wraps size.

### Context 🔦

We are attempting to show a summary table of all our costs with about 25 columns and the first few column summaries cannot be read due to the total box covering the values of them.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Running on Chrome

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.15.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 111.0.5563.65
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.69)
  npmPackages:
    @emotion/react: ^11.9.3 => 11.10.5
    @emotion/styled: ^11.9.3 => 11.10.5
    @mui/base:  5.0.0-alpha.121
    @mui/core-downloads-tracker:  5.11.13
    @mui/material: ^5.11.13 => 5.11.13
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.11
    @mui/system:  5.11.13
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-data-grid:  6.0.1
    @mui/x-data-grid-premium: ^6.0.1 => 6.0.1
    @mui/x-data-grid-pro:  6.0.1
    @mui/x-license-pro:  6.0.1
    @types/react:  18.0.28
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript:  3.9.10
```
</details>

### Order ID or Support key 💳 (optional)

58533

**Comment by tjgibbs92** [comment]
@m4theushw Have you guys been able to identify the issue with dynamic row height?

**Comment by cherniavskii** [comment]
I cannot reproduce the issue with the latest v6 version: https://stackblitz.com/edit/react-y6g7sf?file=package.json
Feel free to reopen if the issue is still reproducible.
