### ISSUE TITLE
[DataGrid] `slotProps`'s `noRowsOverlay` cannot pass custom props.. typescript not happy

### ISSUE THREAD

**Issue by zigang93** [mui/mui-x#8242]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/reverent-james-b1epmz?file=/demo.tsx

![Screenshot 2023-03-15 at 9 23 58 AM](https://user-images.githubusercontent.com/11520821/225180236-d4bb0fb9-3176-4cbf-b116-96b8d2c022bf.png)

### Current behavior 😯

it still working, but ts not happy

### Expected behavior 🤔

should be able to accept custom props

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
You need to use typescript module augmentation to be able to pass on extra props in `slotProps`, please refer to this [guide](https://mui.com/x/react-data-grid/components/#custom-slot-props-with-typescript) on how to do that.

I have updated the codesandbox to be able to pass `msg` prop: https://codesandbox.io/s/ancient-sunset-ubxqwi
