### ISSUE TITLE
Datagrid - Fetching a lot of data instantly 

### ISSUE THREAD

**Issue by ysnbas** [mui/mui-x#8248]
There are 6 thousand data and the data in the datagrid loads late when the page is opened. Do you have anything for it?

#8236

**Comment by joserodolfofreitas** [comment]
Hi @ysnbas, 
Six thousand rows should not be a problem at all, so we need more information about your use case.

Could you provide a live reproduction case?
You can use our [basic template](https://codesandbox.io/s/mui-x-issue-template-qtf00h) to get started.
