### ISSUE TITLE
[fields] Cannot enter the date via keyboard in DatePicker field rendered inside shadow-dom

### ISSUE THREAD

**Issue by vladnkolesnikov** [mui/mui-x#8249]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/weathered-tree-7zt09g?file=/src/App.js

Steps:
1.  Try to enter date in the field using numeric keypad

### Current behavior 😯

Not possible to enter a date in the datepickers' field using the numeric keypad. You can only use arrows. Date can be changed with keyboard only after date is selected from the calendar

### Expected behavior 🤔

Date can be changed via keyboard

### Context 🔦

This behavior is observed only inside shadow-dom

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
   System:
    OS: macOS 13.2.1
  Binaries:
    Node: 16.17.1 - ~/.volta/tools/image/node/16.17.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.15.0 - ~/.volta/tools/image/node/16.17.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: Not Found
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.4 => 11.10.5 
    @mui/icons-material: ^5.10.9 => 5.10.9 
    @mui/material: ^5.11.5 => 5.11.5 
    @mui/styles: ^5.11.2 => 5.11.2 
    @mui/x-date-pickers: 6.0.1 => 6.0.1 
    @types/react: ^17.0.50 => 18.0.28 
    react: ^17.0.2 => 18.2.0 
    react-dom: ^17.0.2 => 18.2.0 
    typescript: ^4.8.4 => 4.9.4 

```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for the reproduction case !

I was able to edit with the keyboard, but only once there is a default value.
When there is no default value, it looks like our `placeholder` HTML attribute is never replaced by the `value` HTML attribute when focusing, which breaks the keyboard edition.

I'll have a look :+1:

**Comment by vladnkolesnikov** [comment]
Thank you @flaviendelangle
