### ISSUE TITLE
[DataGrid] Column menu reopens when clicking on the kebab icon

### ISSUE THREAD

**Issue by felxb** [mui/mui-x#8251]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://mui.com/x/react-data-grid/row-definition/#feeding-data
Steps:

1. Click on colum menu toggle button next to column header "name". Column menu opens.
2. Click again on column menu toggle button next to column header "name". Column menu closes and reopens.

### Current behavior 😯

If a column menu is already open and someone clicks on the associated toggle button, the menu closes and reopens.

### Expected behavior 🤔

If a column menu is open and someone clicks on the associated toggle button, the menu should close instead of reopening. Happens in chrome and safari latest versions.

### Context 🔦

I am simply trying to make a user-friendly filterable table. The problem seems to exist on the most basic implementation of data grid and data grid pro.

### Your environment 🌎

  System:
    OS: macOS 13.1
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.118 
    @mui/core-downloads-tracker:  5.11.9 
    @mui/icons-material: ^5.11.9 => 5.11.9 
    @mui/material: ^5.11.9 => 5.11.10 
    @mui/private-theming:  5.11.9 
    @mui/styled-engine:  5.11.9 
    @mui/styles: ^5.11.9 => 5.11.9 
    @mui/system: ^5.11.9 => 5.11.9 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.9 
    @mui/x-data-grid:  6.0.1 
    @mui/x-data-grid-pro: ^6.0.0 => 6.0.1 
    @mui/x-date-pickers: ^5.0.19 => 5.0.19 
    @mui/x-date-pickers-pro: ^5.0.19 => 5.0.19 
    @mui/x-license-pro:  5.17.12 
    @types/react: 17.0.2 => 17.0.2 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.1.3 => 4.1.3

**Comment by mrishabh062** [comment]
So basically where can I implement the solution given by you? I also want to avoid this behavior.

**Comment by MBilalShafi** [comment]
@mrishabh062 The fix is already merged and it will be available in the latest release later this week.
