### ISSUE TITLE
[docs] Demo AdapterHijri crashes

### ISSUE THREAD

**Issue by lufke** [mui/mui-x#8252]
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20AdapterHijri%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-date-pickers/calendar-systems/
2. Click on Jalali calendar icon from date picker component
3. demo *AdapterHijri* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.0.1  |
| Netlify deploy | https://640a2a1f4874c30008aa2914--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41 |

**Comment by LukasTy** [comment]
Thank you for opening this issue.
There is indeed an issue in the demo itself, we'll fix it, but do note the red callout mentioning issues about the month parsing—that will still cause issues when using this adapter until the issue is resolved.
