### ISSUE TITLE
[MobileDateRangePicker] Setting `SingleInputDateRangeField` as the `slots.field` component results in buggy behavior

### ISSUE THREAD

**Issue by triglian** [mui/mui-x#8266]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/lucid-fermat-zlfd3b?file=/demo.tsx

Steps:
1. Open Date range picker by clicking on the input textfield
2. Select a date
3. Click "Cancel"

### Current behavior 😯

- End date is selected first
- Clicking "Cancel" doesn't clear the field

### Expected behavior 🤔

- Start date is selected first
- Clicking "Cancel" should clear the field

### Context 🔦

We're trying to pass a single field for the two text inputs. The plan is to use a custom field that matches our design requirements.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.6.3
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6.1
  npmPackages:
    @emotion/react: 11.10.5 => 11.10.5
    @emotion/styled: 11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.116
    @mui/core-downloads-tracker:  5.11.9
    @mui/icons-material: ^5.11.0 => 5.11.11
    @mui/lab: 5.0.0-alpha.118 => 5.0.0-alpha.118
    @mui/material: 5.11.7 => 5.11.7
    @mui/private-theming:  5.11.7
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.7
    @mui/types:  7.2.3
    @mui/utils:  5.11.7
    @mui/x-date-pickers:  6.0.0
    @mui/x-date-pickers-pro: 6.0.0 => 6.0.0
    @mui/x-license-pro:  6.0.0
    @types/react: 18.0.25 => 18.0.25
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ~4.8.2 => 4.8.4
```
</details>

### Order ID or Support key 💳 (optional)

4514724970

**Comment by flaviendelangle** [comment]
Unfortunately you can't just set `field: SingleInputDateRangeField` because the picker still passes callback made for 2 inputs.

We have #7606 which keeps track of the work to support it and #7927 which is my PR for it.
Feel free to have a look at the doc linked in my PR to see if the behavior seems coherent to you.

I'm closing it to keep a single source of truth :+1:
