### ISSUE TITLE
[pickers] Picker forces focus in MacOS Safari

### ISSUE THREAD

**Issue by rusted-love** [mui/mui-x#8283]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://codesandbox.io/s/hardcore-wing-tupxmr?fontsize=14&hidenavigation=1&theme=dark

Just click different date inputs. To see problem faster click many times different inputs.

### Current behavior 😯

It's flickering and sometimes you need 5 clicks to change a focus.
Also, if you click outside of input focus will be forced to some of them.

Important!
IOS Safari, and MacOS chrome works well. Reproduce it only with MacOS Safari.

### Expected behavior 🤔

There should be no "infinity focus prison"

### Your environment 🌎

Safari MacOS browser.
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/WebstormProjects/ladyboom_static/node_modules/.bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react:  11.10.6 
    @emotion/styled:  11.10.6 
    @mui/base:  5.0.0-alpha.121 
    @mui/core-downloads-tracker:  5.11.13 
    @mui/icons-material:  5.11.11 
    @mui/lab:  5.0.0-alpha.123 
    @mui/material:  5.11.13 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.13 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-date-pickers:  6.0.2 
    @types/react:  18.0.28 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  5.0.2 

```
</details>

**Comment by oliviertassinari** [comment]
Confirmed, it's unusable

**Comment by flaviendelangle** [comment]
@LukasTy I think your the one using MacOS, if you can have a look :pray:

**Comment by LukasTy** [comment]
The issue is related to the fact that we are using `setSelectionRange` and changing it after blur, which "should"/does re-focus the input where this change is being made.
Here is [a WebKit issue](https://bugs.webkit.org/show_bug.cgi?id=224425), where they resolved it as "Works as expected".
