### ISSUE TITLE
Fields components ways reverse in RTL

### ISSUE THREAD

**Issue by fakhamatia** [mui/mui-x#8284]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Click month in input
2. Press Left Arrow Key and Date input select
3. Cursor move to right and year selected

### Your environment 🌎

[codesandbox](https://codesandbox.io/p/github/fakhamatia/material-dashboard-react/main?file=%2Fsrc%2FApp.js&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A175%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A175%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clfqnyuhz00cug4j9cylxfk85%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252FApp.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfqnvwng00112g6huhwnuk1j%2522%253A%257B%2522key%2522%253A%2522clfqnvwng00112g6huhwnuk1j%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clfqnvwng00122g6ho7mtvlnk%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Frtl%2522%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfqnvwng00112g6huhwnuk1j%2522%252C%2522spacesOrder%2522%253A%255B%2522clfqnvwng00112g6huhwnuk1j%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)
`/rtl` route

**Comment by alexfauquette** [comment]
@fakhamatia You forget to copy the link to your live example. Could you provide a codesandbox such that we are sure we discuss the same issue?

**Comment by fakhamatia** [comment]
> @fakhamatia You forget to copy the link to your live example. Could you provide a codesandbox such that we are sure we discuss the same issue?

I added the link

**Comment by alexfauquette** [comment]
Seems their is some issue about private repo 

![image](https://user-images.githubusercontent.com/45398769/227779052-28190734-0918-4af7-9e7a-a2725edc508d.png)

**Comment by fakhamatia** [comment]
> Seems their is some issue about private repo
> 
> ![image](https://user-images.githubusercontent.com/45398769/227779052-28190734-0918-4af7-9e7a-a2725edc508d.png)

I think it was fixed this time

**Comment by alexfauquette** [comment]
Thanks, The problem seems to occur when setting the `direction: 'rtl'` in the Theme provider

Here is a simpler reproduction: https://codesandbox.io/s/small-snowflake-83q1fv?file=/index.tsx

**Comment by alexfauquette** [comment]
You can not, it's a bug on our side, I'm going to fix

**Comment by alexfauquette** [comment]
It's not the same bug.

Here is a smaller reproduction. The first DateTimePicker has the format of your example. Notice that tokens are displayed in the field, even if you provided a `defaultValue` (we should see the value, not the token in such case)

https://codesandbox.io/s/small-snowflake-83q1fv?file=/demo.tsx

The adapter does not handle those tokens, so it assumes they are text to display (not tokens). By replacing `yyyy` by `iYYYY` and `MM` by `iMM` the keyboard navigation get fixed

Supported tokens are defined by `formatTokenMap` in [`AdapterMomentHijri/index.ts`](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/AdapterMomentHijri/index.ts). Maybe they should be merged with [`AdapterMoment/index.ts`](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/AdapterMoment/index.ts)

**Comment by fakhamatia** [comment]
> It's not the same bug.
> 
> Here is a smaller reproduction. The first DateTimePicker has the format of your example. Notice that tokens are displayed in the field, even if you provided a `defaultValue` (we should see the value, not the token in such case)
> 
> https://codesandbox.io/s/small-snowflake-83q1fv?file=/demo.tsx
> 
> The adapter does not handle those tokens, so it assumes they are text to display (not tokens). By replacing `yyyy` by `iYYYY` and `MM` by `iMM` the keyboard navigation get fixed
> 
> Supported tokens are defined by `formatTokenMap` in [`AdapterMomentHijri/index.ts`](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/AdapterMomentHijri/index.ts). Maybe they should be merged with [`AdapterMoment/index.ts`](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/AdapterMoment/index.ts)
> 
> Are they you have use-cases where you need to access both `YYYY` and `iYYYY`?

I don't understand.
My problem is not adapter, it is Field order move.`iYYYY` not support by Jalali.

Format : `yyyy/MM/dd EEEE HH:mm:ss`

[Screencast from 04-11-2023 06:35:07 PM.webm](https://user-images.githubusercontent.com/20030910/231205899-751ef8c1-403f-4405-a790-9d2658f516c4.webm)

Theme is `direction: "rtl"` but I set `direction: "ltr"` for date input

**Comment by alexfauquette** [comment]
Effectively, `date-fns-jalali` adapter suport those tokens. 

I don't understand what you mean by 

>Theme is `direction: "rtl"` but I set `direction: "ltr"` for date input


Here is a codesandbox with the working eqmple. I guess you forget to set the attribute `dir=rtl` (that's why test is left aligned in the input of your video)

https://codesandbox.io/s/condescending-roentgen-f2flfo?file=/demo.tsx

If it's not the case, could you provide a reproduction with the code of the codesandbox above. Their is a lot of useless elements in your examples (routing, other fields, ...) and it takes time to find relevant information for the debug in it
