### ISSUE TITLE
[DatePicker] value is not reset correctly

### ISSUE THREAD

**Issue by sodenn** [mui/mui-x#8285]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/reset-mui-datepicker-v6-fyrxxu?file=/demo.tsx

Steps:
1. Press Reset
2. Focus the DatePicker field

### Current behavior 😯

When using the DatePicker as a controlled component and reset the value via state update, the old value will remain when the picker is focused.

### Expected behavior 🤔

In v5 the value can be reset programmatically. This made it easy to reset forms, for example. https://codesandbox.io/s/reset-mui-datepicker-v5-fkle7i?file=/demo.tsx

### Your environment 🌎

@mui/x-date-pickers: 6.0.2

**Comment by sodenn** [comment]
The clear button in popover also doesn't completely reset the value to MM/DD/YYYY
![2023-03-19 19 36 31](https://user-images.githubusercontent.com/232054/226199480-b858d878-a8ac-452a-93fb-d0feef9a7534.gif)

**Comment by flaviendelangle** [comment]
Hi, 

Thanks for your feedback ! 
I'm opening a PR, it will be live by the end of the week.
