### ISSUE TITLE
[docs] DataGrid CRUD editing example has code that produces a TS2322 error when implemented

### ISSUE THREAD

**Issue by SusiKette** [mui/mui-x#8294]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-data-grid/editing/#full-featured-crud-component

### Kind of issue

Broken demonstration

### Issue description

I was looking at the DataGrid CRUD editing example, where in the `GridColDef[]` it has a field `getActions: ({ id }) => {}`, but when I add it to my `GridColDef[]`, I get the following error:

`TS2322: Type '{ field: string; type: string; headerName: string; width: number; cellClassName: string; getActions: ({ id }: { id: any; }) => never[]; }' is not assignable to type 'GridColDef<any, any, any>'.   Object literal may only specify known properties, and 'getActions' does not exist in type 'GridColDef<any, any, any>'.`

EDIT: It looks like `getActions` doesn't exist in the [GridColDef Interface](https://mui.com/x/api/data-grid/grid-col-def/) (anymore?). If `getActions` is older implementation, how should this be implemented now?

**Comment by SusiKette** [comment]
I did have `type: "action"` just like the example code did

**Comment by thenoakes** [comment]
I just had this issue and I ended up defining the definition for my actions column as a separate `GridActionsColDef`, (which behaved as expected) and then dropped it into the other definitions, in case that's helpful?
