### ISSUE TITLE
[pickers] Unfocused field appears blank when partial date input is provided

### ISSUE THREAD

**Issue by bengunther1997** [mui/mui-x#8296]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
This can be reliably reproduced with any of the desktop variant examples: https://mui.com/x/react-date-pickers/date-picker/

Steps:
1. Populate the desktop date picker field with a valid date.
2. Delete any part of the date to make the input incomplete. Eg: 04 / DD / 2020
3. Unfocus the field - Notice the field goes blank, even though the date is partially provided.

### Current behavior 😯

When unfocused, the input field hides the partially populated date.
The issue only seems to happen after the field has first been filled with a full and valid date. It works as expected if the field hasn't previously been populated with a valid date.
Focusing the field again causes the partially filled date to re-appear.
I tested the DateField (https://mui.com/x/react-date-pickers/date-field/) following the same steps to reproduce and it doesn't have the issue.

### Expected behavior 🤔

Partially filled dates like "04 / DD / 2020" should always be visible in the DesktopDatePicker's input field even when the field is unfocused; consistent with the behaviour of the DateField (https://mui.com/x/react-date-pickers/date-field/).

### Context 🔦

Trying to use the component in a production setting. This behaviour results in an unintuitive and jarring user experience.
I haven't been able to find a workaround yet, so any advice on what I might be able to do in the meantime is much appreciated.

### Your environment 🌎

Issue can be reproduced in the examples in the MUI docs: https://mui.com/x/react-date-pickers/date-picker/
Using latest version of Chrome at time of posting (Version 111.0.5563.65).

**Comment by flaviendelangle** [comment]
Thanks for the detailed report, I'll do a fix :+1:

**Comment by flaviendelangle** [comment]
The next release should be at the end of the week (Thursday, Friday)
And the fix seems easy enough to be in it
