### ISSUE TITLE
Show all/ hide all buttons don't work when both columnVisibilityModel with columnGroupingModel are applied

### ISSUE THREAD

**Issue by dzyubadmytro** [mui/mui-x#8305]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-data-grid-visibility-grouping-conflict-kfk0wp

Steps:
1. Hide some columns by default with `columnVisibilityModel`
2. Apply `columnGroupingModel` to DataGrid
3. Click Toolbar -> Columns -> Show all(Hide all)

### Current behavior 😯

Nothing happens. No errors in the console

### Expected behavior 🤔

All columns are shown(hidden)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - ~\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
  npmPackages:
    @emotion/react:  11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.121
    @mui/core-downloads-tracker:  5.11.13
    @mui/icons-material: ^5.11.11 => 5.11.11
    @mui/material:  5.11.13
    @mui/material-next: ^6.0.0-alpha.78 => 6.0.0-alpha.78
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.11
    @mui/system:  5.11.13
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-data-grid:  6.0.2
    @mui/x-data-grid-premium: ^v6.0.2 => 6.0.2
    @mui/x-data-grid-pro:  6.0.2
    @mui/x-license-pro:  6.0.2
    @types/react: ^18.0.28 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components:  5.3.9
    typescript: ^5.1.0-dev.20230320 => 5.1.0-dev.20230320
```
</details>

**Comment by yaredtsy** [comment]
hey @dzyubadmytro 

The columnVisibilityModel is used by users to manage the visibility of columns. To modify the visibility model, you can add or remove column fields from the columnVisibilityModel object. The columnVisibilityModel is used in conjunction with onColumnVisibilityModelChange function. For more information, please refer to this article: https://mui.com/x/react-data-grid/column-visibility/#controlled-visible-columns.

```jsx
  const [columnVisibilityModel, setColumnVisibilityModel] = React.useState({
    german: false,
    english: false
  })

 <DataGridPremium
        columnVisibilityModel={columnVisibilityModel}
        onColumnVisibilityModelChange={(newModel) => setColumnVisibilityModel(newModel)}
        ...
/>
```
Demo: https://codesandbox.io/s/mui-data-grid-visibility-grouping-conflict-forked-h2rdkh?file=/src/App.tsx
