### ISSUE TITLE
[docs] Demo LazyLoadingGrid crashes

### ISSUE THREAD

**Issue by brodysean18** [mui/mui-x#8309]
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LazyLoadingGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/row-updates/
2. ??
3. demo *LazyLoadingGrid* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.0.2  |
| Netlify deploy | https://64131c023038f300086d3cdc--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0 |

**Comment by oliviertassinari** [comment]
Duplicate of #10047
