### ISSUE TITLE
[pickers] Current year is used, when format does not contain year

### ISSUE THREAD

**Issue by itshallrun** [mui/mui-x#8311]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:  [stackblitz](https://stackblitz.com/edit/react-nwmz14?file=demo.tsx,index.html)

Steps:
1. On a DatePicker set  `inputFormat="dd/MM"` and set a min and max date to         
```
minDate={new Date('2020-01-01')}
maxDate={new Date('2020-12-31')}
```
To get a leap year and be able to select the 29th of February

2. type in any date
3. the date picker is broken

### Current behavior 😯

The day selection in the dialog works fine.

The problem is with **_typing in_** the day.
E.g. when typing 01/01 then `onChange` gets the date of the current year, which is outside of the min/max range.
The date picker is broken then.

![image](https://user-images.githubusercontent.com/21173275/226590567-eb37de4f-2a2d-44b0-a84f-19be4f00a698.png)

### Expected behavior 🤔

When typing in the date, the `onChange` should provide a date, that is within the min/max range.

instead of `2023-01-01T23:00:00.000Z` it should be `2020-01-01T23:00:00.000Z`

Or is there any other workaround, maybe a possibility to provide a default year?

### Context 🔦

I need a year independent day Picker, for season selection.

I use `import { DatePicker } from '@mui/x-date-pickers/DatePicker';`
With a min and max date set to `2020-01-01` till `2020-12-31`.
**This is a leap year so I can select the 29th of February.**

If I would use the current year instead of the leap year, then I lose the 29th of February.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

@mui/x-date-pickers: 5.0.20
Chrome/Firefox/Edge
</details>

**Comment by LukasTy** [comment]
Thank you for opening this issue. 🙏 
It does seem like a problem that we don't have a clean solution for but it is already known.
I do not see options to cleanly support our use case in v5.
The only compromise I have found is using [v6 and specifying an initial value](https://codesandbox.io/s/summer-darkness-q5botq?file=/demo.tsx).
Would it be possible for you to use v6 with the mentioned compromise instead?

**Comment by flaviendelangle** [comment]
Conclusions from yesterday's meeting:

On the field, we are internally using a `referenceValue`, which avoid loosing the information not present in the input itself (the time when using a date format, the timezone, the date when using a time format, etc...).

This `referenceValue` is updated whenever we have a valid value and is initialized to `now()` if we never have one (which explains the behavior described in this issue).

We could expose it in a `referenceValue` prop.

People directly using the field could use it.
And the picker could automatically generate it based on the validation props.

___

In the future, we could also expose it on the picker to solve #5702

The naming of this prop need to be determined.
We would expect `defaultCalendarDate` to only be applied to date views, whereas something like `referenceValue` can be used for all the views.
