### ISSUE TITLE
Datepicker keeps focus on Safari

### ISSUE THREAD

**Issue by arnaudbrowet** [mui/mui-x#8320]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Tested on local environment with a simple component
```
<LocalizationProvider dateAdapter={AdapterDayjs} >
    <DatePicker label="Basic date picker" />
</LocalizationProvider>
```

The bug is also heavily visible on the official documentation page (when opened with safari of course)
https://mui.com/x/react-date-pickers/date-picker/

### Current behavior 😯

When putting focus on a datePicker element (either by clicking the calendar icon or the textfield),  the focus is hard or impossible to remove (keyboard escape not working, click anywhere not working)

It seems that the focus can be freed by click a select element

### Expected behavior 🤔

The focus should be release when clicking away

### Context 🔦

simple date selection

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 11.7.3
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: Not Found
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.115
    @mui/core-downloads-tracker:  5.11.6
    @mui/icons-material: ^5.11.0 => 5.11.0
    @mui/material: ^5.11.6 => 5.11.6
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.5
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-date-pickers: ^6.0.2 => 6.0.2
    @types/react:  18.0.27
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.9.4
```
</details>

**Comment by LukasTy** [comment]
Thank you for reporting this issue! 🙏 
It has already been solved via https://github.com/mui/mui-x/issues/8283 and will be fixed with this week's release on Thursday or Friday.
