### ISSUE TITLE
[fields] Scroll jumps when editing the field value on iOS Safari

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#8321]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open https://mui.com/x/react-date-pickers/fields/#fields-to-edit-a-single-element in iOS Safari
2. Edit the field value

### Current behavior 😯

The page is scrolled to the very top

https://user-images.githubusercontent.com/13808724/226720682-5e28d47b-9dce-4393-b82e-d29bad5aad53.mp4

### Expected behavior 🤔

No scroll

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
@LukasTy is it the same issue as #8283 ?

**Comment by LukasTy** [comment]
> LukasTy is it the same issue as #8283 ?

Nope. It's a different thing. I'm not sure if it's an actual issue and if we'll even be able to do something about it. 🤔 
It just seems that iOS Safari is not only doing focus, but also scrolling the selected input section into view using some sort of logic to calculate offset, and that calculation must probably be very wrong. 🙈 

I'll investigate the possible cause a bit.
