### ISSUE TITLE
When using row grouping with data-grid-premium, is there a way to display some columns in the auto-generated row (the parent row that is shown as collapsed by default)?

### ISSUE THREAD

**Issue by tomer-communix** [mui/mui-x#8332]
### Order ID or Support key 💳 (optional)

62332

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a grid in which I am grouping rows by a property that comes from an API (all rows that should be grouped together have the same value for a certain property).
However, all of these rows have some duplicate properties (such as 'name' for example) and I would like those properties to be shown on the parent auto-generated row without forcing the user to expand in order to see them.
I would like the user to expand only to see the real differences between the rows, and because the name is the same for all of them I would like it to appear in the aggregated parent row.
Is that possible? None of the examples shows this and I couldn't find anything similar online.
Thanks

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 13.0
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Edge: Not Found
    Firefox: 110.0.1
    Safari: 16.1
```
</details>

**Comment by tomer-communix** [comment]
This is a dataset for example:
`[{"id": 1, "groupId": 1, "name": "Test 1", "Description": "Some description", "tier": 0, "day": 1, "amount": 100},{"id": 2, "groupId": 1, "name": "Test 1", "Description": "Some description", "tier": 0, "day": 2, "amount": 200},{"id": 3, "groupId": 1, "name": "Test 1", "Description": "Some description", "tier": 1, "day": 1, "amount": 300}]`

In the example above the grouping is based on the property 'groupId' but some properties (such as 'name' and 'description') are duplicated. Therefore I would like to have the option to display these duplicated properties in the aggregated row and give the user the option to see their values without expending the grouping row.

**Comment by noanflaherty** [comment]
I also would love this feature. My use case is that I'd like to show aggregate values (i.e. an average) in the parent row, and then the individual values that make up the aggregate in each row once expanded.

**Comment by cherniavskii** [comment]
@tomer-communix I think you can use a [custom aggregation function](https://mui.com/x/react-data-grid/aggregation/#create-custom-functions) to put the duplicated property values inline in the grouping row - see this demo https://codesandbox.io/s/zen-boyd-evu1u7?file=/demo.tsx

**Comment by cherniavskii** [comment]
@noanflaherty You can use the Aggregation feature with `inline` position - see https://mui.com/x/react-data-grid/aggregation/#usage-with-row-grouping

**Comment by tomer-communix** [comment]
Thanks @cherniavskii!
Is there a way to remove the 'EQUALVALUES' label that is being automatically added under the column label?

**Comment by cherniavskii** [comment]
@tomer-communix The aggregation label is always displayed for now, but you can hide it with CSS - see https://github.com/mui/mui-x/issues/5682#issuecomment-1225857991
