### ISSUE TITLE
DateTimePicker throw error 'too many renders' when use timezone with 00:00 offset

### ISSUE THREAD

**Issue by mgprieto-soincon** [mui/mui-x#8334]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Case A: using defaultTimeZone (currentDate2 crash)
[https://codesandbox.io/s/blazing-dawn-7ph7kx?file=/demo.tsx:1608-1617](url)

Case B: specifing timeZone (currentDate2 and currentDate4 crash, timezones with 00 offset)
[https://codesandbox.io/s/restless-silence-iwbg43?file=/demo.tsx](url)

Case C: when using default and open de calendar, it makes transitions from current month until November
[https://codesandbox.io/s/old-cloud-k54gne?file=/demo.tsx](url)

### Current behavior 😯

When use a timezone with 0 offset, the aplication crash because Calendar throws "too many renders" error.
Only happens with 0 offset timezones, maybe this issue at dayjs affects to current behavior. [https://github.com/iamkun/dayjs/issues/1675](url)

### Expected behavior 🤔

Prevent crashing application 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.116 
    @mui/core-downloads-tracker:  5.11.7 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/lab: ^5.0.0-alpha.118 => 5.0.0-alpha.118 
    @mui/material: ^5.11.7 => 5.11.7 
    @mui/private-theming:  5.11.7 
    @mui/styled-engine:  5.11.0 
    @mui/styled-engine-sc: ^5.11.0 => 5.11.0 
    @mui/styles: ^5.11.7 => 5.11.7 
    @mui/system:  5.11.7 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.7 
    @mui/x-data-grid:  5.17.21 
    @mui/x-data-grid-pro: ^5.17.21 => 5.17.21 
    @mui/x-date-pickers:  5.0.16 
    @mui/x-date-pickers-pro: ^5.0.16 => 5.0.16
    @mui/x-license-pro: ^5.17.12 => 5.17.12
    @types/react: 17.0.30 => 17.0.30
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: ^5.3.5 => 5.3.5
    typescript: ~4.3.5 => 4.3.5
```
</details>

Launch at Google Chrome version 111.0.5563.65

### Order ID or Support key 💳 (optional)

44269

**Comment by flaviendelangle** [comment]
May be related to https://github.com/mui/mui-x/issues/5876

I'll try to investigate

**Comment by mgprieto-soincon** [comment]
Any progress on the issue?

**Comment by mgprieto-soincon** [comment]
@flaviendelangle ??

**Comment by flaviendelangle** [comment]
Here is a [smaller reproduction case](https://codesandbox.io/s/vigilant-tom-w3h72y?file=/demo.tsx) for the automatic navigation to November

I could not reproduce the crash
Is it when opening the picker? 

For the navigation to November, it's related to https://github.com/iamkun/dayjs/issues/1189
We should give proper support for timezones in #8261 :+1:
