### ISSUE TITLE
Uncontrolled column resizing

### ISSUE THREAD

**Issue by ridwannizam** [mui/mui-x#8338]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
- Press mouse left button and resize the column Folder
- Stop for a few seconds, keep pressing on the left button
- Move the mouse while the left button is pressed and stop again, keep the left-button pressed.
- You will see the width of the column description increasing

https://user-images.githubusercontent.com/84927690/226919749-59ce21b2-d1be-472f-8d28-c953525c317b.mp4

### Expected behavior 🤔

The width of the column description should not change at all
The width of any column should not change if the mouse is not moving

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

62375

**Comment by cherniavskii** [comment]
Hi @ridwannizam 
Could you provide a reproduction example?
