### ISSUE TITLE
Horizontal scroll bar is invisible

### ISSUE THREAD

**Issue by ridwannizam** [mui/mui-x#8339]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

The horizontal scrollbar is invisible, you should click on the grid or scroll to the end of the page many times so the grid show it. 

https://user-images.githubusercontent.com/84927690/226920833-73149113-d739-4462-9b4a-b5c2d4eef58b.mov

### Current behavior 😯

The horizontal scrollbar is invisible

### Expected behavior 🤔

The scrollbar should be visible if the grid doesn't fit all columns 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

62375

**Comment by cherniavskii** [comment]
Hi @ridwannizam 
This seems to be an expected scrollbar behavior on MacOS - see this pure HTML/CSS demo:
https://codesandbox.io/s/infallible-chatterjee-etq6pe?file=/src/App.js

It is configurable in the system settings:
<img width="698" alt="Screenshot 2023-03-22 at 14 55 01" src="https://user-images.githubusercontent.com/13808724/226926575-fb2c3508-6522-4105-bee5-e7ff89ccfaf7.png">

**Comment by cherniavskii** [comment]
You can customize it with CSS: https://codesandbox.io/s/inspiring-snow-0k8jfk?file=/demo.tsx
Although, it's a non-standard feature (see https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)
