### ISSUE TITLE
Datepicker flickers on Safari

### ISSUE THREAD

**Issue by christianhultin** [mui/mui-x#8342]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Open Safari (I'm using Version 16.3)
2. Go to https://mui.com/x/react-date-pickers/date-picker/ (I'm assuming this is @mui/x-date-pickers:6.0.2 since this is where I found the issue myself in our project)
3. Fiddle with the controlled Datepicker

### Current behavior 😯

It flickers and it seems like the autofocus is constantly interrupting the expected behavior of being able to select individual portions of the date

### Expected behavior 🤔

- No flickering when selecting individual portions
- Being able to type individual portions of the date

### Your environment 🌎

```
- MacOs Ventura 13.2.1
- Safari Version 16.3
- @mui/x-date-pickers: 6.0.2
```

**Comment by christianhultin** [comment]
https://user-images.githubusercontent.com/6624600/226949412-45982fa6-9723-45d2-822c-bf1ecb619156.mov

**Comment by LukasTy** [comment]
This problem is already resolved via https://github.com/mui/mui-x/issues/8283 and will be released this week on Thursday or Friday. 😉
