### ISSUE TITLE
[pickers] End adornment is not rendered if you pass `InputProps`  on the `textField` slot via the theme

### ISSUE THREAD

**Issue by baileypownell** [mui/mui-x#8345]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Customize the MUI theme with `createTheme()`.
2. Customize `MuiDateTimePicker` as follows:
```jsx
MuiDateTimePicker: {
      defaultProps: {
            slotProps: {
                  textField: {
                        InputProps: {
                              sx: {
                                    color: 'red',
                               },
                          },
                  },
           },
      },
}}
```
3. Observe that the OpenPickerIcon is not rendered.
![broken](https://user-images.githubusercontent.com/44715325/227010451-bf7bea57-9394-49fb-8861-d3cf1bb5b2a6.png)
4. Remove `InputProps` from the customization.
5. Observe that the OpenPickerIcon renders as expected.
![working](https://user-images.githubusercontent.com/44715325/227010540-6e4f3345-0aa3-47e3-af4d-584abb5578b5.png)

### Current behavior 😯

The OpenPickerIcon button is not rendered if you customize the `InputProps` for the `textField` slotProp. 

### Expected behavior 🤔

The OpenPickerIcon button is rendered if you customize the `InputProps` for the `textField` slotProp. 

### Context 🔦

We are ultimately trying to properly style a "small" sized `TextField` rendered by the `DateTimePicker` component.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browser: Chrome

System:
    OS: macOS 13.0.1
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: 111.0.1661.51
    Firefox: 110.0.1
    Safari: 16.1
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.121 
    @mui/core-downloads-tracker:  5.11.13 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/lab: ^5.0.0-alpha.123 => 5.0.0-alpha.123 
    @mui/material: ^5.11.13 => 5.11.13 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system: ^5.11.13 => 5.11.13 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-date-pickers:  6.0.2 
    @mui/x-date-pickers-pro: ^6.0.0 => 6.0.2 
    @mui/x-license-pro: ^6.0.0 => 6.0.2 
    @types/react: ^18.0.28 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 4.9.5 => 4.9.5 
```
</details>

**Comment by flaviendelangle** [comment]
Might be related to https://github.com/mui/material-ui/pull/35088
I suspect the theme logic do not merge the objects deep enough

**Comment by LukasTy** [comment]
@baileypownell Are you having issues applying the change you listed or just wanted to illustrate the issue?
If it's the former, then try using `inputProps` instead of `InputProps` to achieve your desired effect without the unwanted issue. 😉

**Comment by baileypownell** [comment]
@LukasTy The rule above is only for illustration purposes; we actually have more complex styles we want to apply.

**Comment by flaviendelangle** [comment]
Yes, but for this one, I think we a stuck :/

**Comment by oliviertassinari** [comment]
@baileypownell I'm curious:

1. Why customize the date picker's text field rather than the text field in general?
2. Why not create a wrapper component?

**Comment by baileypownell** [comment]
We have moved forward in a different direction. I am closing this issue now. Thanks.
