### ISSUE TITLE
[question] - DataGrid Tree Data - Is filtering supported on the grouping cell?

### ISSUE THREAD

**Issue by rodrigofariow** [mui/mui-x#8357]
### Order ID or Support key 💳 (optional)

54728

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello 👋 
I'm trying to add simple filtering on a group cell used in a Tree Data DataGrid.
In plain [Row Grouping](https://mui.com/x/react-data-grid/row-grouping/#group-expansion) I can see it is possible.
However, when looking at the [docs](https://mui.com/x/react-data-grid/tree-data/#filtering) for Tree Data, I couldn't find any example where it is filterable.

For instance, here, I would like to use filters to search for the employee's name.
<img width="702" alt="image" src="https://user-images.githubusercontent.com/22502084/227199952-345873c2-e69f-499d-b34e-b1dce55f420c.png">

Could you guide me toward a solution, please?
I'm aware that I can probably make the group col def filterable and play a bit with the filter operators, perhaps.
However, official guidance would be ideal to avoid possible filtering misbehaviors.

Thank you

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Here's how to get `rowNode` in v7 and above:

```tsx
valueGetter: (value, row, column, apiRef) => {
  const rowId = apiRef.current.getRowId(row);
  const rowNode = apiRef.current.getRowNode(rowId);
  // ...
}
```

**Comment by michelengelen** [comment]
Thanks @cherniavskii 

So the updated example would look like this:
```tsx
<DataGridPro
  groupingColDef={{
    filterable: true,
    disableColumnMenu: false,
    valueGetter: (value, row, column, apiRef) => {
      const rowId = apiRef.current.getRowId(row);
      const rowNode = apiRef.current.getRowNode(rowId);
      return rowNode?.groupingKey ?? '';
    },
  }}
/>
```
