### ISSUE TITLE
DataGrid throw error "root.getElementById is not a function" from version 5.17.21

### ISSUE THREAD

**Issue by mgprieto-soincon** [mui/mui-x#8359]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Case A:  data-grid version 5.17.20 work fine
https://codesandbox.io/s/serverless-cookies-mzwsk8?file=/src/App.tsx

Case B: data-grid version 5.17.21 throw error
https://codesandbox.io/s/romantic-napier-lhr605?file=/src/App.tsx:376-380

### Current behavior 😯

When update data-grid version to a higher version than 5.17.20 the same code, throws an uncontrolled error on execution. 

### Expected behavior 🤔

Prevent crashing application

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4 
    @emotion/styled: ^11.10.4 => 11.10.4 
    @mui/base:  5.0.0-alpha.116 
    @mui/core-downloads-tracker:  5.11.7 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/lab: ^5.0.0-alpha.118 => 5.0.0-alpha.118 
    @mui/material: ^5.11.7 => 5.11.7 
    @mui/private-theming:  5.11.7 
    @mui/styled-engine:  5.11.0 
    @mui/styled-engine-sc: ^5.11.0 => 5.11.0 
    @mui/styles: ^5.11.7 => 5.11.7 
    @mui/system:  5.11.7 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.7 
    @mui/x-data-grid:  5.17.21 
    @mui/x-data-grid-pro: ^5.17.21 => 5.17.21 
    @mui/x-date-pickers:  5.0.16 
    @mui/x-date-pickers-pro: ^5.0.16 => 5.0.16
    @mui/x-license-pro: ^5.17.12 => 5.17.12
    @types/react: 17.0.30 => 17.0.30
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: ^5.3.5 => 5.3.5
    typescript: ~4.3.5 => 4.3.5
```
</details>

Launch at Google Chrome version 111.0.5563.65

### Order ID or Support key 💳 (optional)

44269

**Comment by cherniavskii** [comment]
@mgprieto-soincon Could you double-check the demos that you have linked in this issue?
In both, I see an empty screen and no error you mentioned.

The issue description reminds me of a similar issue reported in https://github.com/mui/mui-x/issues/7875, so it might be helpful here.

**Comment by mgprieto-soincon** [comment]
Yes, we now that is not the best practice. We are trying to pass the DataGrid to a 3rd party library which does not accept a React.node, this is the reason why we are calling Rect.render during the render.

We have found a workaround solution for the case that caused the issue, by creating a ref, getting its innerHTML and passing it to the library.

So we are going to close the issue, thank you so much for you time and attention.

**Comment by b-codex** [comment]
can you provide the actual code on how you solved the problem please? thank you.
