### ISSUE TITLE
[DataGrid] - Master detail column resize causes detail rows to resize

### ISSUE THREAD

**Issue by mormir2** [mui/mui-x#8366]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/c8t2ko?file=/demo.tsx

Steps:
1. Expand a master detail
2. Resize e.g. the second column of the parent table
3. Detail rows are resized too but not their header column

### Current behavior 😯

(Tested with @mui/x-data-grid v5.17.26)

Resizing some of the parent's columns causes the resizing of the detail component's row too.
As you can test in the example provided in the documentation for the master detail (https://v5.mui.com/x/react-data-grid/ => https://codesandbox.io/s/c8t2ko?file=/demo.tsx) the detail's rows with the same data-colindex as the resized master column will be resized too but the detail component's column header remains the same size.
When changing a detail row column's data-colindex to some other value, that row will remain unaffected when resizing the parent column.

### Expected behavior 🤔

Only the columns of the parent should be resized, the detail component should remain the same.

### Your environment 🌎

@mui/x-data-grid: ^5.17.26

**Comment by cherniavskii** [comment]
Hi @mormir2 
While the demo you provided doesn't use Master/detail feature, I think you're describing the same issue as https://github.com/mui/mui-x/issues/5493
Let me know if I misunderstood the issue you were describing.

**Comment by mormir2** [comment]
@cherniavskii sorry, yes you're right, I linked the wrong example. This would be the correct one https://codesandbox.io/s/mhdvip?file=/demo.tsx taken from https://v5.mui.com/x/react-data-grid/master-detail/. I'll update the issue right away.

While searching through the issues before creating this one, for some reason I didn't see the one you mentioned.
So I figure this issue is being worked on already?

Thanks a lot!

**Comment by cherniavskii** [comment]
@mormir2 Thanks for the clarification!
I have added the issue to our backlog.

**Comment by mormir2** [comment]
Thanks!!
