### ISSUE TITLE
[pickers] Weekday support for `AdapterDateFnsJalali`

### ISSUE THREAD

**Issue by fakhamatia** [mui/mui-x#8376]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I Want To Add Weekday in input but `AdapterDateFnsJalali` not support `EEEE`.

### Examples 🌈

[https://codesandbox.io/s/summer-butterfly-kng9l6](https://codesandbox.io/s/summer-butterfly-kng9l6)

```javascript
import * as React from 'react';
import { AdapterDateFnsJalali } from '@mui/x-date-pickers/AdapterDateFnsJalali';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';

export default function AdapterJalali() {
  return (
    <LocalizationProvider dateAdapter={AdapterDateFnsJalali}>
      <DatePicker format="yyyy/MM/dd EEEE" label="Date Picker" defaultValue={new Date(2022, 1, 1)}/>
    </LocalizationProvider>
  );
}
```

**Comment by flaviendelangle** [comment]
Hi,

They are supported by `AdapterDateFns`, I'll add them the `AdapterDateFnsJalali` for the next release :+1:
