### ISSUE TITLE
SlotProps Typing issue with MUIX Datagrid V6

### ISSUE THREAD

**Issue by PraveenVerma17** [mui/mui-x#8400]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/winter-moon-zevzbw?file=/demo.tsx

### Current behavior 😯

Typescirpt error comes with custom type props.

Type '{ data: number; }' is not assignable to type 'Partial<HTMLAttributes<HTMLDivElement> & { sx?: SxProps<Theme>; } & FooterPropsOverrides>'.
  Object literal may only specify known properties, and 'data' does not exist in type 'Partial<HTMLAttributes<HTMLDivElement> & { sx?: SxProps<Theme>; } & FooterPropsOverrides>'

### Expected behavior 🤔

Typescript error should not appear.

### Context 🔦

Trying to create a custom footer with custom footer component with props

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
You need to augment the types of slotProps if you want to pass some custom props in the Grid Slots. This has been explained in this documentation page: https://mui.com/x/react-data-grid/components/#custom-slot-props-with-typescript

I updated your codesandbox example to do that: https://codesandbox.io/s/gallant-brook-rry1l5?file=/demo.tsx
