### ISSUE TITLE
[DataGrid] Need access to updated row without clicking outside the row or without calling processRowUpdate callback

### ISSUE THREAD

**Issue by supsinha92** [mui/mui-x#8404]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://github.com/mui/mui-x

### Kind of issue

Unclear explanations

### Issue description

We have a scenario where a particular cell is updated in a row in DataGrid and Save button is then clicked to save the updated data.

But everytime the user needs to click outside the cell for the change to be effective in react state thorugh processRowUpdate callback and only then the Save gets called with updated data.

If user directly clicks  the SAVE button without first clicking anywhere outside the cell, the save is called with stale data as processRowUpdate was not called till that time. 

Even if we control this condition to disable save until processRowUpdate has not completed, still there can be a scenario where user does not update any data and wishes to save directly. In that case since there is no involvement of processRowUpdate, the SAVE button would remain disabled.

Hence, is there any way we can get access to updated row besides, the processRowUpdate method? Like a mouseOut event or something?

**Comment by HawaiianBBQ** [comment]
-    "@mui/x-data-grid": "^6.0.1",
+   "@mui/x-data-grid": "^6.0.4",
That package update seems to have broken the row update sequence for me.  handleClickSave in an actions cell is firing before processRowUpdate.  If I am paying for the pro version what do you need from me to elevate this priority beyond what it currently is?

**Comment by MBilalShafi** [comment]
Thank you @supsinha92 for providing the code example. To understand this problem better you have to first understand that both [setState](https://react.dev/reference/react/useState#ive-updated-the-state-but-logging-gives-me-the-old-value) and processRowUpdate are asynchronous operations and it is not guaranteed that you will get the updated values immediately after the callbacks are fired. 

Some rationale about how `processRowUpdate` works is explained in the [editing section](https://mui.com/x/react-data-grid/editing/#persistence) of the documentation.

If your rationale is to always provide updated value when the user clicks Save button, I think one way to achieve it is to use events `onCellEditStart` and `onCellEditStop` and disable the save button during edit phase.

I've tried to do that in this [codesandbox](https://codesandbox.io/s/data-grid-community-forked-z3sj2u?file=/src/App.tsx:1610-1625), let me know if it solves your problem.

@Steve2724214 Kindly check and let me know if yours is a similar use-case.
