### ISSUE TITLE
[Datagrid] Not able to close menu option in case of getGridSingleSelectOperators() in datagrid

### ISSUE THREAD

**Issue by mrishabh062** [mui/mui-x#8405]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Image
![image](https://user-images.githubusercontent.com/112873983/227978388-0e41bfc6-3fb7-4469-b23b-fb6ef69d5bc8.png)

### Current behavior 😯

I have implemented a filter in my table in which I have provided a drop down from where user can select any option he want and I am using getGridSingleSelectOperators() in that case to select single single value. 

But what I am seeing, after clicking X close button I am not able to close that tab but for other columns I can close the tab. While same close button is able to remove value which is selected from dropdown, but not able to close that option.

### Expected behavior 🤔

When user click close (X) button then he should be able to close that filter which is popped up by clicking kebab button.

### Your environment 🌎

<details>
 dependencies {
"@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.10.4",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.10.4",
    "@mui/icons-material": "^5.5.1",
    "@mui/material": "^5.10.4",
    "@mui/x-data-grid": "^5.8.0",
</details>

**Comment by MBilalShafi** [comment]
Hey @mrishabh062, could you provide a minimal reproduction example to better understand the problem?

You can use this [codesandbox](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) as a starting point.

**Comment by mrishabh062** [comment]
It's hard to replicate everything on codesand box, but still I have added code at [Codesandbox](https://codesandbox.io/s/data-grid-community-forked-oxv88y?file=/src/App.tsx)

Added 2 files App.tsx (For datagrid) , AppMeta.tsx (For getting columns)

Context: -
1. I am using a filter in therapeutic area column in my result table, it's type is "singleSelect" and filterOperators is "getGridSingleSelectOperators()" I have provided a drop down menu whose data I am fetching from API, so that user can select from the list of menu. Here user can selection multiple values and based upon that data will be filtered.
2. Now when I am clicking (X) close button so it delete value one by one and when all value is deleted so ideally it should close that filter tab which is opened, but it does not close it (Image I have shared above)
3. But when I remove that drop down, so it started working correctly.
4. What can be the possible reason for that?

**Comment by MBilalShafi** [comment]
The provided codesandbox has errors and it doesn't work for me, we can not understand your problem correctly until you provide a working example with the issue reproducing.

If it's difficult to reproduce on codesandbox, could you add the reproducing code to a public git repo and share the URL here?
