### ISSUE TITLE
onColumnVisibilityModelChange is trigger when show hide column and then change the column Size 

### ISSUE THREAD

**Issue by ukOlya** [mui/mui-x#8407]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/data-grid-community-forked-rh3go6?file=/src/App.tsx

Used @mui/x-data-grid-premium v5. In v6 it work correctly
Steps:
1. show id column
2. resize id column

Result: 
onColumnVisibilityModelChange  triggered and id column becomes hide

### Current behavior 😯

onColumnVisibilityModelChange is triggered when i clicking on showing hide column and then change the column Size,
Its not happend when the column is showed by default.

### Expected behavior 🤔

onColumnVisibilityModelChange will not triggered at that situation and id is visible

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by ukOlya** [comment]
https://user-images.githubusercontent.com/102224041/228003690-79193842-acee-4df2-bffa-a30983aa939d.mp4

**Comment by MBilalShafi** [comment]
@ukOlya Thanks for reporting the issue, this issue has already been reported here: https://github.com/mui/mui-x/issues/7947, can you try the [solution](https://github.com/mui/mui-x/issues/7947#issuecomment-1433230613) suggested by @m4theushw or you can also consider updating to v6 to have this fixed and get more stable code generally.

If you need to follow up on this, you can do it on the mentioned issue, I'm closing this one.
