### ISSUE TITLE
[DataGrid] Scrolling does not works correctly when add new row

### ISSUE THREAD

**Issue by nathanKith** [mui/mui-x#8410]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/affectionate-breeze-rd2fkp?file=/demo.tsx

Steps:
1. Add row by clicking button at toolbar
2. Add row again

### Current behavior 😯

First time everything going like as i expected. But second time it just add new row and scroll up. And every next click on button "Add row" does not scrolling down.

### Expected behavior 🤔

First time I expect it add new row, go to the last page and scroll down. Second time the same, but without going to the last page.

### Context 🔦

I try to create CRUD table that go to the last page and scroll down when new row is added. I attached the link in "steps to reproduce". Maybe i just doing something wrong, but please explain me what.

I think it looks like React fire useEffect before new row added to DOM.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Thanks for providing the reproduction example 🙂 

You might use the internal grid method [`updateRows`](https://mui.com/x/react-data-grid/row-updates/#the-updaterows-method) to add the rows to the grid, doing that, you can utilize grid selectors and doesn't necessarily need to maintain the rows state outside the grid. You can also prevent the grid from re-rendering and recompute the state on each row addition thus improving performance.

I've tried to achieve that in the codesandbox you provided, here's the updated [codesandbox](https://codesandbox.io/s/dry-grass-3qetq2?file=/demo.tsx). Let me know if it addresses your concerns or you need to maintain the state externally for some reason.

**Comment by nathanKith** [comment]
First of all thank you very much for the answer in such a short time.

I still need maintain the state externally, because in my project i use the DataGrid like one of the many inputs in external form.

**Comment by yaredtsy** [comment]
hey @nathanKith, 
the problem is you are trying to scroll to index when `rows` state changes. the data grid takes more time after the state changes to add the new row, so when you try to scroll to the newly added row. it has not been added to the grid yet. so you need to scroll when the row is added to the grid. you can `subscribe` to `virtualScrollerContentSizeChange` event to detect when the new row is added.

```jsx
  React.useEffect(() => {
    return apiRef.current.subscribeEvent(
      "virtualScrollerContentSizeChange",
      () => {
        if (apiRef.current == null) return;
        const pageSize = gridPageSizeSelector(apiRef);
        const length = apiRef?.current?.getAllRowIds().length;

        const pagesNumber = Math.ceil(length / pageSize);
        apiRef?.current?.setPage(pagesNumber);
        apiRef?.current?.scrollToIndexes({
          rowIndex: length - 1
        });
      }
    );
  }, [apiRef.current]);
```

**Comment by nathanKith** [comment]
@yaredtsy Hi! Sorry for the late answer. I understand the problem, and appreciate for the example that you give, but it does not work correctly. When i add new row it does not jump to the last page, because virtual scroll size does not change when reach the rows limit on page.
So here's the sandbox example: https://codesandbox.io/s/optimistic-pare-e4hy34?file=/demo.tsx

I try to set page in other useEffect, but now i see blink. The scroll quickly jump up and down, so there's the blink. I don't really have an idea how can i resolve this issue.
There is the example of blinking one: https://codesandbox.io/s/restless-grass-vt161g

**Comment by yaredtsy** [comment]
> When i add new row it does not jump to the last page, because virtual scroll size does not change when reach the rows limit on the page.

ya, it only works on if you are on the last page. but its the only effective way that i found. this event gets triggered when the new row is added to the dom and its garrented it will be there when you try to scroll to it or access it.

> I try to set page in other useEffect, but now i see blink. The scroll quickly jump up and down, so there's the blink. I don't really have an idea how can i resolve this issue.

you do not have to change the page every time. you only need to change if its not on the last page.

```jsx
 React.useEffect(() => {
    if (addedRow) {
      const pageSize = gridPageSizeSelector(apiRef);
      const page = apiRef.current.state.pagination.paginationModel.page + 1;
      const { length } = apiRef.current.getAllRowIds();
      const pagesNumber = Math.ceil(length / pageSize);
      if (page != pagesNumber) {
        apiRef.current.setPage(pagesNumber);
      }
    }
  }, [addedRow, apiRef]);


```

**Comment by yaredtsy** [comment]
hey @nathanKith , i was trying to see if there is any event related to the number of pages being changed but i could find any. i also have looked into the [pagination](https://mui.com/material-ui/react-pagination/) component and there is no event being fired. the only way I found is delaying it.

```jsx
  React.useEffect(() => {
    setTimeout(() => {
      if (addedRow) {
        const pageSize = gridPageSizeSelector(apiRef);
        const page = apiRef.current.state.pagination.paginationModel.page + 1;
        const { length } = apiRef.current.getAllRowIds();
        const pagesNumber = Math.ceil(length / pageSize);
        if (page !== pagesNumber) {
          apiRef.current.setPage(pagesNumber);
        }
      }
    });
  }, [addedRow, apiRef]);
```

@MBilalShafi, is there a way to know when the no of pages is changed?

**Comment by nathanKith** [comment]
@MBilalShafi @yaredtsy hi! is there any updates?

**Comment by nathanKith** [comment]
@yaredtsy yeah, there is a reason. I write about it above.

> I still need maintain the state externally, because in my project i use the DataGrid like one of the many inputs in external form.

**Comment by yaredtsy** [comment]
in that case you can `forceUpdate` the grid. before you move try to scroll to the new row added.

```jsx
     const handleClick = () => {
    const id = randomId();
    const added = { id, name: "blabla", age: "18", isNew: true };

    const page = apiRef.current.state.pagination.paginationModel.page + 1;

    flushSync(() => {
      setRows((oldRows) => [...oldRows, added]);
    });
    flushSync(() => apiRef.current.forceUpdate());


    const { length } = apiRef.current.getAllRowIds();
    const pageSize = gridPageSizeSelector(apiRef);
    const pagesNumber = Math.ceil(length / pageSize);
    if (page !== pagesNumber) {
      apiRef.current.setPage(pagesNumber);
    }
    apiRef.current.scrollToIndexes({
      rowIndex: length - 1
    });
  };
```
