### ISSUE TITLE
[DatePicker] Bug when selecting year and using a custom TextField slot

### ISSUE THREAD

**Issue by RyanRickert** [mui/mui-x#8411]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Create a date picker utilizing a textField slot
2. Click on the year changer
3. Select a year other than the currently selected year

### Current behavior 😯

When a different year than the currently selected year is selected the calendar view snaps to top left of the page.

### Expected behavior 🤔

The year selector should not move to a new location.

### Context 🔦

While this is happening with a styled TextField that I have created, just using a basic import of TextField also causes this error.

### Your environment 🌎

```
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns'
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'
import { DatePicker } from '@mui/x-date-pickers/DatePicker'
import TextField from '@mui/material/TextField'
```

```
<LocalizationProvider dateAdapter={AdapterDateFns}>
  <DatePicker
    value={*my const*}
    onChange={(newValue: Date) => {
      setValue('someValue', newValue, {
        shouldValidate: true,
        shouldDirty: true
      })
    }}
    slots={{
      textField: (props) => <TextField {...props} />
    }}
  />
</LocalizationProvider>
```

This is an example of what my code resembles and it is worth noting that it works fine if the slot is not provided.

**Comment by flaviendelangle** [comment]
The slots receives components, not render function.
Passing a render function like that will cause the field to remount of every render, which may be causing your problem.

```diff
  slots={{
-   textField: (props) => <TextField {...props} />
+  textField: TextField,
  }}
```

You can find more information [on this doc page](https://mui.com/x/react-date-pickers/custom-field/) for the custom fields.

**Comment by RyanRickert** [comment]
You are absolutely correct and it is what was causing the error.  Thank you for enlightening me.  Closing this issue as it was a usage problem and not an actual bug.

**Comment by mf0548414295** [comment]
Hello, I have customized the datepicker and the popper moved to the upper left side, the solution you wrote above: "textField: TextField," is not good for me since I do need to customize the text field

**Comment by LukasTy** [comment]
> Hello, I have customized the datepicker and the popper moved to the upper left side, the solution you wrote above: "textField: TextField," is not good for me since I do need to customize the text field

Hello, have you referenced the [doc regarding the usage](https://mui.com/x/react-date-pickers/custom-field/#using-another-input) of custom inputs? 🤔

**Comment by mf0548414295** [comment]
yes' can i write in hebrew?

**Comment by LukasTy** [comment]
> yes' can i write in hebrew?

I'll only be able to use translate in that case, but if it will do a good job, there shouldn't be much problem understanding it. 👍

**Comment by mf0548414295** [comment]
אוקיי, אז אני לא יודעת אם הסברתי את עצמי טוב, השתמשתי ב-DatePicker של mui, הייתי צריכה להתאים את textField וברגע שמתאימים אותו - הpopper של הלוח שנה זז לצד השני של המסך

**Comment by LukasTy** [comment]
> אוקיי, אז אני לא יודעת אם הסברתי את עצמי טוב, השתמשתי ב-DatePicker של mui, הייתי צריכה להתאים את textField וברגע שמתאימים אותו - הpopper של הלוח שנה זז לצד השני של המסך


It seems that you have [opened a separate issue](https://github.com/mui/mui-x/issues/9078) for this concern, hence, there is no need to answer this question here. 👌
