### ISSUE TITLE
Row Grouping, Aggregation, and Filters applied through initial state break the grid on load. 

### ISSUE THREAD

**Issue by tielushko** [mui/mui-x#8419]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/aggregation-grouping-quick-filter-broken-09nu8h

Sandbox example is running the latest 6.0.3. In our application, we are still on version 5.17.25 and haven't made the migration. The error is reproducible in both.

Steps:
1. Open the codesandbox.
2. Take a look at the initialState prop with three types of grid manipulations applied at the same time: row grouping, aggregation, and filters. 
3. TypeError: Cannot read properties of 'undefined' is observed. 

### Current behavior 😯

A breaking error message appears, and the grid doesn't display. 

### Expected behavior 🤔

The grid applies all the properties listed in the initial state and does not error out. 

### Context 🔦

We are storing the filters (including quick filters) the user inserted into the grid in session storage, for them to be able to use later as a part of their session, and if they want to open a new tab and apply different filters in the application in a different tab, they still can. 

When we render the grid, we extract those filters from session storage and insert them into the initialState prop.

when resetting and applying the steps one by one in any combination (grouping, then aggregation, then filters) the error does not occur. after the state is saved and reapplied as initial state on the reload of the page in our application, the 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
 System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.4.1 => 11.10.4 
    @emotion/styled: ^11.3.0 => 11.10.4 
    @mui/base:  5.0.0-alpha.99 
    @mui/core-downloads-tracker:  5.10.7 
    @mui/icons-material: ^5.0.1 => 5.10.6 
    @mui/lab: ^5.0.0-alpha.48 => 5.0.0-alpha.101 
    @mui/material: ^5.0.1 => 5.10.7 
    @mui/private-theming:  5.10.6 
    @mui/styled-engine:  5.10.7 
    @mui/styles: ^5.0.1 => 5.10.7 
    @mui/system: ^5.0.1 => 5.10.7 
    @mui/types:  7.2.0 
    @mui/utils:  5.10.6 
    @mui/x-data-grid:  5.17.25 
    @mui/x-data-grid-premium: 5.17.25 => 5.17.25 
    @mui/x-data-grid-pro:  5.17.25 
    @mui/x-date-pickers: ^5.0.0-alpha.1 => 5.0.3 
    @mui/x-license-pro:  5.17.12 
    @types/react: ^17.0.21 => 17.0.50 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.3.2 => 4.8.4 

</details>

### Order ID or Support key 💳 (optional)

62502

**Comment by MBilalShafi** [comment]
@tielushko Thanks for reporting. The issue has been fixed, and released on [v6.0.4](https://github.com/mui/mui-x/releases/tag/v6.0.4).

**Comment by tielushko** [comment]
@MBilalShafi, thank you for getting back and fixing it so quickly. Would it be able to be backported to the v5 of the Data Grid? We haven't migrated yet due to some breaking changes in v6.

**Comment by MBilalShafi** [comment]
> Would it be able to be backported to the v5 of the Data Grid

Since v6 is a stable release now, we don't anymore have the plan to release non-critical patches or bug fixes on v5.

> We haven't migrated yet due to some breaking changes in v6.

Yes, there are breaking changes but we tried to make them as few as possible and to make the migration easier we introduced `codemods` [[about codemods](https://mui.com/x/migration/migration-data-grid-v5/#run-codemods), [list of codemods](https://github.com/mui/mui-x/tree/master/packages/x-codemod#data-grid-codemods)] that transform the bulk of code automatically to the new version.

For more information about v6 in general, see this [blog post](https://mui.com/blog/mui-x-v6/), and here's the [data grid migration guide](https://mui.com/x/migration/migration-data-grid-v5/) to help you started with the migration process.
