### ISSUE TITLE
[question] How to formatting in TextField without spaces?

### ISSUE THREAD

**Issue by TheBox193** [mui/mui-x#8422]
### Order ID or Support key 💳 (optional)

60415

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

With both the `AdapterDateFns` and `AdapterLuxon` the placeholder and formatted date presents incorrectly with additional paces around ` / `.  Desired result is `03/29/2023` instead of `03 / 29 / 2023`. 

Is there a better way to configure the placeholder / display format of a the date?

| format | result |
| --- | --- |
| format="MM/dd/yyyy" 🔴  | ![image](https://user-images.githubusercontent.com/220755/228450322-b8bbc86f-24d3-4da7-8283-3e8c7aebf5be.png) |
| format="MM /dd/ yyyy" ✅  | ![image](https://user-images.githubusercontent.com/220755/228451226-1e13f5eb-d9dd-407f-bb98-824ddf9ec8c9.png) |
| format="MM / dd / yyyy" ✅  | ![image](https://user-images.githubusercontent.com/220755/228450845-c0e9db77-70b1-4438-a980-f52bea15cec2.png) |
| format="MM-dd-yyyy" ✅  | ![image](https://user-images.githubusercontent.com/220755/228451490-c5c9afab-78b7-483a-9efa-e1a004dc0436.png) |

Thanks!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  ```
  Browser:
    Chrome 110.0.5481.177
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.18 - ~/Code/waterly-workspace/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.7.0 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.119 
    @mui/core-downloads-tracker:  5.11.12 
    @mui/icons-material: ^5.5.1 => 5.5.1 
    @mui/lab: ^5.0.0-alpha.73 => 5.0.0-alpha.122 
    @mui/material: ^5.8.4 => 5.11.12 
    @mui/private-theming:  5.11.12 
    @mui/styled-engine:  5.11.11 
    @mui/styles:  5.11.12 
    @mui/system:  5.11.12 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.12 
    @mui/x-date-pickers: ^6.0.1 => 6.0.1 
    @types/react: ^17.0.3 => 17.0.37 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ~4.9.4 => 4.9.4 
```

</details>

**Comment by flaviendelangle** [comment]
We are discussing this topic in #8243

I'm closing this one :+1:

**Comment by TheBox193** [comment]
@flaviendelangle Thank you 👍🏻
