### ISSUE TITLE
Ordering rows by dragging the entire row rather than the dedicated icon

### ISSUE THREAD

**Issue by tomwhale** [mui/mui-x#8435]
### Order ID or Support key 💳 (optional)

57717

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We are looking to re-order rows by dragging the entire row, rather than using the dedicated re-ordering drag icon. We feel that this is not obvious enough to less technical users from our user research. 

Is this possible?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: macOS 13.2.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.54
    Firefox: 111.0.1
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.112
    @mui/core-downloads-tracker:  5.11.3
    @mui/icons-material: ^5.11.0 => 5.11.0
    @mui/lab: ^5.0.0-alpha.66 => 5.0.0-alpha.114
    @mui/material: ^5.0.4 => 5.11.3
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.2
    @mui/types:  7.2.3
    @mui/utils:  5.11.2
    @mui/x-data-grid:  5.17.18
    @mui/x-data-grid-premium: ^5.17.18 => 5.17.18
    @mui/x-data-grid-pro:  5.17.18
    @mui/x-date-pickers: ^5.0.13 => 5.0.13
    @mui/x-license-pro:  5.17.12
    @types/react: 17.0.2 => 17.0.2
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components:  5.3.3
    typescript: ^4.7.4 => 4.7.4
```
</details>

**Comment by MBilalShafi** [comment]
This is not supported by default as it does not work great with multiple selected rows. I've added a waiting for upvotes to see if it's requested by other users too.

Meanwhile, a possible workaround could be to override the `slots.row` with a custom row component with the logic to handle row drag events.

I've built a small prototype in this codesandbox: https://codesandbox.io/s/datagridpremium-rowreordering-demo-with-draggable-row-8uwenv?file=/src/App.tsx
