### ISSUE TITLE
Allow showing the month preceding the range when using 2 calendars

### ISSUE THREAD

**Issue by michal-perlakowski** [mui/mui-x#8437]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm using a DateRangeCalendar with 2 calendars and `disableFuture={true}`. My default range starts and begins in the current month. The component shows the range in the first calendar, and the next month in the second calendar, where all dates are disabled. In this use case, it would make more sense to show the month preceding the range in the first calendar, and the range in the second calendar. This could either be controlled via a prop, or decided automatically based on disabled dates.

### Order ID 💳 (optional)

61560

**Comment by LukasTy** [comment]
Thank you for opening this issue.

Do you have a requirement to have some initial (default) dates pre-selected?
If you don't, then [using `defaultCalendarMonth` could help](https://codesandbox.io/s/default-calendar-month-with-disabled-future-zwof96) with your case in the meantime. 😉 

There is already an issue https://github.com/mui/mui-x/issues/4562 discussing this concern and suggesting a solution.
We'll be closing this one as a duplicate.
