### ISSUE TITLE
Material UI DataGrid v6 column minWidth issue and horizontal scrollbar

### ISSUE THREAD

**Issue by Adam15-byte** [mui/mui-x#8440]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I work at a company where we use multiple DataGrids that include many columns with a minWidth property. The columns are so numerous that they would easily push outside the viewport, but this did not happen because they were inside containers. As a result, the DataGrids had horizontal scroll bars.

Steps:
1. Upon upgrading to MUI DataGrids Pro v6, all of these DataGrids suddenly stretched their parents to fit them in full capacity without the horizontal scrollbar, or to fit the width of grandparent component. These data grids were children of containers with "width: "100%"".
2. Here is a sample code to compare between Data-Grid-Pro v5 and v6. @mui/material is at version 5.11.15. Just make sure that there are many columns, all with the minWidth property.
3. ` <Box
      sx={{
        display: "flex",
        flexDirection: "row",
        height: 520,
        width: "100%",
      }}
    >
      <Box
        sx={{
          width: "100%",
          backgroundColor: "#fff",
        }}
      >
        <DataGridPro rows={rows} columns={columns} />
      </Box>
      <Box
        sx={{
          width: "100%",
          backgroundColor: "#fff",
        }}
      >
        <DataGridPro rows={rows} columns={columns} />
      </Box>
    </Box> `
The same happens when divs are used. The code is also posted here: https://stackoverflow.com/questions/75884242/material-ui-datagrid-v6-column-minwidth-issue-and-horizontal-scrollbar

### Current behavior 😯

In new version Data Grid Pro v6 it will look like this: https://i.stack.imgur.com/KlwHS.png
Data grids are pushed to with 100% of granparent component.

### Expected behavior 🤔

In new version Data Grid Pro v5 it will look like this: https://i.stack.imgur.com/GPinU.png
Data grids are pushed to width 100% of parent components, each trying to fill as much as possible of their parents. 

### Context 🔦

Versions:
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/material": "^5.11.15",
    "@mui/styled-engine-sc": "^5.11.11",

Data grid versions compared:
    "@mui/x-data-grid": "^6.0.3",
    "@mui/x-data-grid-pro": "^6.0.3",

Data grid versions compared:
    "@mui/x-data-grid": "^5.15.0",
    "@mui/x-data-grid-pro": "^5.15.0",
vs
    "@mui/x-data-grid": "^6.0.3",
    "@mui/x-data-grid-pro": "^6.0.3",

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
It looks related to #8175.

You can set the width of the inner elements to `50%` to achieve the desired behavior.
Something like this: https://codesandbox.io/s/withered-dawn-71leuv?file=/demo.tsx
