### ISSUE TITLE
DataGrid with "autoHeight" infinite re-renders and keeps increasing width

### ISSUE THREAD

**Issue by altechzilla** [mui/mui-x#8447]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Use a `<DataGrid />` with autoHeight

### Current behavior 😯

The DataGrid keeps expanding width

### Expected behavior 🤔

It shouldn't

### Context 🔦
"@mui/x-data-grid": "^6.0.3",

https://user-images.githubusercontent.com/8274669/228874264-04d0cb92-4a32-49d4-b376-4319b51a6ab0.mov

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
```
</details>

**Comment by altechzilla** [comment]
Just tested with 5.17.26 and it doesn't happen. But with anything newer than that it does.

**Comment by MBilalShafi** [comment]
It looks related to https://github.com/mui/mui-x/issues/8182 which has been fixed and released in [v6.0.4](https://github.com/mui/mui-x/releases/tag/v6.0.4). Can you try using v6.0.4 and see if the issue is still reproducible?

If it is, it will be great to have a minimal reproduction in a codesandbox. You can use this as a starting point: https://codesandbox.io/s/datagrid-v5-quick-start-54iz1

**Comment by Deraen** [comment]
Here is one related example with 6.0.4 and what I'm seeing in a project, though this doesn't use `autoHeight`, so maybe this is a separate problem?

https://codesandbox.io/s/data-grid-community-forked-3ctumy

- flex container
- border on the MuiDataGrid-main
- container height so big that the table doesn't have a vertical scroll

**Comment by yaredtsy** [comment]
the `style` is glitching.

https://user-images.githubusercontent.com/34584266/229577516-b51dc6e5-f5ff-42d0-b02a-802eaa40cd73.mp4

give the data grid a width.

```jsx
<DataGridPro
        sx={{
          width: "100%"
        }}
      ....
<DataGridPro/>
```

**Comment by houman-sanati** [comment]
set its parent display property to `grid` : 
```
sx={{display: 'grid'}}
```

**Comment by steckdev** [comment]
> set its parent display property to `grid` :
> 
> ```
> sx={{display: 'grid'}}
> ```

This worked perfectly for us. Simple fix to ensure the the infinite horizontal growth went away. We only had 1/2 of the browsers affected by this issue.

**Comment by pwuk** [comment]
display: grid fixed a weird issue for me too.
I have a grid, which when the rows array is empty causes the grid to constantly expand, 1px at a time
Actually, it fixed two issues ! 
Second, my grid colums are all flex: N and would grow when expanding the width but would not shrink this also fixed that!

**Comment by jandresfg** [comment]
> set its parent display property to `grid` :
> 
> ```
> sx={{display: 'grid'}}
> ```
 It works! https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeHEwMXM4MW9zdWZ5NjY3OTc1MnZ1NXZtYXozMGZpMjhwdnN3cjliOCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1M9fmo1WAFVK0/giphy.gif

**Comment by Sadiqshah94** [comment]
Im facing the same issue 
Now I fixed with using 


sx={{display: 'grid'}}

  <DataGrid
      rows={rows}
      sx={{display: 'grid'}}
      columns={columns}
      checkboxSelection
      onRowSelectionModelChange={(selectionModel) =>
        handleRowSelectionChange(selectionModel as GridRowId[]) 
        
      }
      slots={{
        toolbar: () => (
          <CustomToolbar
            exportToPDF={exportToPDF}
          />
        ),
        noRowsOverlay: NoRowsOverlay,
      }}
      disableRowSelectionOnClick
      density='compact'
      pagination
      paginationModel={paginationModel}
      rowCount={rowCount}
      paginationMode={paginationMode}
      pageSizeOptions={[5, 10, 20, 50]}
      onPaginationModelChange={handlePaginationModelChange}
    />

**Comment by pedrofsmartins3** [comment]
https://mui.com/x/react-data-grid/layout/#flex-parent-container

mui material also adressed that issue.

**Comment by konstantinpadamass** [comment]
For others, look into this solution, it worked for me.  https://github.com/mui/mui-x/issues/8895#issuecomment-1793433389
