### ISSUE TITLE
DataGridPro columns reorder on refresh data

### ISSUE THREAD

**Issue by pczuba** [mui/mui-x#8448]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Connect some data to `DataGridPro` (`rows` property).
2. Reorder colums by drag&drop.
3. Connect other datato grid (fror example on button click).
4. Columns reorder to the default state (1).

### Current behavior 😯

Grid columns reorder to then previous (default) state on data refresh.

### Expected behavior 🤔

Grid columns should not reorder to then previous (default) state on data refresh.

### Context 🔦

I'm trying to store grid state and restore it, but colums order changes to the default state each time I refresh data in grid. 

### Your environment 🌎

{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    },
    {
      "path": "./.storybook/tsconfig.json"
    }
  ]
}

Browsers:
  * Chrome
  * Firefox

**Comment by MBilalShafi** [comment]
Can you expand more on how you are trying to store and restore the grid state? If you are using `apiRef.current.exportState()` and `apiRef.current.restoreState()`, you can retain the column reorder state as observed in this demo example: https://mui.com/x/react-data-grid/state/#restore-the-state-with-initialstate

If your use-case is different, could you provide a minimal reproduction example for the problem to be understood better. If you want, you can use this codesandbox as starting point: https://codesandbox.io/s/datagridpro-basic-gzmv9c

**Comment by pczuba** [comment]
I've tried to write some code to confirm that problem, but in codesandbox everything works fine.
It looks like there is a problem in my REACT application code.
Thanks a lot for your help.

**Comment by pczuba** [comment]
It looks like there is a problem, when grid columns definitions are returned from REACT hook.
I have hook with grid functions and it returns columns definitions, too.
In this case, each data (rows) refresh change columns state (order, width, etc.) to the default. 

Here is an example from CodeSandbox:
[datagridpro-basic-forked.zip](https://github.com/mui/mui-x/files/11125756/datagridpro-basic-forked.zip)

**Comment by MBilalShafi** [comment]
That is the required behavior, it's also mentioned on https://mui.com/x/react-data-grid/column-definition/ page:

> The columns prop should keep the same reference between two renders. The columns are designed to be definitions, to never change once the component is mounted. Otherwise, you take the risk of losing elements like column width or order. You can create the array outside the render function or memoize it.

If you still want to update the value of columns prop after the component is mounted for some reason, one direction to look into for persisting/restoring some of the grid state is using `apiRef.current.exportState()` and `apiRef.current.restoreState()` methods.

**Comment by pczuba** [comment]
Thanks for your explanation.

**Comment by scott-avery** [comment]
@MBilalShafi The localization support of Datagrid doesn't affect column names. So we have to implement our own translation flow.

The case is when the translation change, it will throw the order state. However, it would be more reasonable to reuse the data from initial state after columns changed.

**Comment by MBilalShafi** [comment]
Hey @scott-avery, kindly open a [new issue](https://github.com/mui/mui-x/issues/new/choose) and provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
