### ISSUE TITLE
after toggling mui datagrid checkboxSelection one row remans selected

### ISSUE THREAD

**Issue by DGeretz** [mui/mui-x#8455]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

[Link to live example:](https://stackblitz.com/edit/react-waxfez?file=demo.tsx) 

Steps:

1. select a few checkboxes
2. toggle checkboxes to hide them
3. notice how the top checkbox remains selected
4. toggle the checkbox selection on again and viola you get a bonus checkbox selected for you (because it was selected from before)

### Current behavior 😯

the top selected  checkbox remains selected

### Expected behavior 🤔

when toggling off checkbox selection either keep all or remove all by default only the highest is "staying selected" 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Chrome browser
 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.101
    @mui/core-downloads-tracker:  5.11.9
    @mui/lab: ^5.0.0-alpha.103 => 5.0.0-alpha.103
    @mui/material: ^5.11.10 => 5.11.10
    @mui/private-theming:  5.11.9
    @mui/styled-engine:  5.11.9
    @mui/system:  5.11.9
    @mui/types:  7.2.3
    @mui/utils:  5.11.9
    @mui/x-data-grid: ^5.17.25 => 5.17.25
    @types/react:  18.0.21
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.8.4
```
</details>
*updated link to problem

**Comment by MBilalShafi** [comment]
@DGeretz Thanks for reporting the issue.
The issue has been fixed and should be available in the next release.
