### ISSUE TITLE
[pickers] DateRangePicker responsive field layout 

### ISSUE THREAD

**Issue by david-ic3** [mui/mui-x#8456]
### Order ID or Support key 💳 (optional)

#19458

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is there an easy way to have automatically the range date picker in 3 rows if container is too narrow ?

**Comment by LukasTy** [comment]
If I understand your problem correctly, you'd like to have the `DateRangePicker` root `MultiInputDateRangeField` element responsive and use column `direction` in certain cases.
If that's a correct assumption, you could try applying the following prop to achieve this:
```tsx
<DateRangePicker
  slotProps={{
    fieldRoot: {
      direction: { xs: "column", sm: "row" },
    },
  }}
/>
```
If you had something else in mind, please be more detailed in your question.
- What package version are you using (v5 or v6)?
- Providing a codesandbox with minimal reproduction example goes a long way in helping us understand the problem better.

**Comment by david-ic3** [comment]
Thanks for the quick turnaround, it's the latest v6.

I see, the switch should be based on the width of the container div not the page 

https://codesandbox.io/s/empty-cache-5ugkql?file=/demo.tsx

**Comment by LukasTy** [comment]
> I see, the switch should be based on the width of the container div not the page
> 
> The current solution is using a useResizeObserver and switch colum/row depending on height/width ratio. For the look we included a class so we can change css depending on row/column mode.

As far as I'm aware, MUI does not yet have a component working with container-responsive design in mind.
For now, as you mentioned, going with ResizeObserver or CSS container queries (if the supported browser version matches your requirements) are the best choices to achieve the desired result. 👌
