### ISSUE TITLE
[DatePicker] Incorrectly import `dialogClasses` from "@mui/material/Dialog"

### ISSUE THREAD

**Issue by claudio-destro** [mui/mui-x#8459]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I have an _micro frontend_ SPA which is sharing MUI and other frameworks among each component modules of the same application.

The mechanism implemented for sharing those frameworks is exactly the same as if the hosting HTML page is loading the frameworks and MUI from a public CDN (like jsdelivery) by using a simple `<script>` tag: see [@mui/material](https://www.jsdelivr.com/package/npm/@mui/material) for more.

Using the `<DatePicker>` component I get the following `TypeError` in `PickersModalDialog`:
```
Cannot read properties of undefined (reading 'container')
```
It seems `PickersModalDialog` is importing `dialogClasses` directly from `"@mui/material/Dialog"`, not `"@mui/material"`.

This is totally fine if `"@mui/x-date-pickers"` and `"@mui/material"` are packed together is a "monolithic" application.

However if MUI is __externalized__ by webpack and later loaded using a public CDN I got the same error. Therefore I think it's a bug.

Am I correct? Any hints how to deal with this? I hope I was clear enough...

C

### Current behavior 😯

No error should be thrown.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: Not Found
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: Not Found
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.7.1 => 11.10.6 
    @emotion/styled: ^11.6.0 => 11.10.6 
    @mui/base: ^5.0.0-alpha.122 => 5.0.0-alpha.122 
    @mui/icons-material: ^5.3.0 => 5.11.11 
    @mui/lab: ^5.0.0-alpha.124 => 5.0.0-alpha.124 
    @mui/material: ^5.3.0 => 5.11.14 
    @mui/styles: ^5.3.0 => 5.11.13 
    @mui/system: ^5.3.0 => 5.11.14 
    @mui/x-date-pickers: ^6.0.3 => 6.0.3 
    @types/react: ^17.0.38 => 17.0.53 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.3 => 5.3.9 
    typescript: ^4.5.4 => 4.9.5 
```
</details>

**Comment by alexfauquette** [comment]
I would say that if your application download `@mui/material` after the `@mui/x-date-pickers` It seems logical that they fail. But without a minimal reproduction example to experiment, it's hard to give you an answer.

**Comment by claudio-destro** [comment]
I am 99% sure that `@mui/material` is __not__ loaded after `@mui/x-date-pickers`.
It's pretty difficult to extract a working example from our code, but I'm going to provide it ASAP.

**Comment by alexfauquette** [comment]
> It's pretty difficult to extract a working example from our code

Yes, that kind of bug is often complicated to reproduce. Usually, people create a new repository with only  `@mui/material` after the `@mui/x-date-pickers` and add the needed part to mak it fail

**Comment by claudio-destro** [comment]
That's the example.
There's a precompiled version under `public` directory.
The key point is MUI `externals` entry in `webpack.config.js`: if you comment it out, there will be no errors.

[date-picker-test.tgz](https://github.com/mui/mui-x/files/11126884/date-picker-test.tgz)

**Comment by alexfauquette** [comment]
OK, I better understand your problem.

Effectively when using CDN Every thing is exported as root. There are no nested imports. For example, the provided example in [documentation](https://mui.com/material-ui/getting-started/installation/#cdn) is doing the following import

```js
const {
        colors,
        CssBaseline,
        ThemeProvider,
        Typography,
        Container,
        createTheme,
        Box,
        SvgIcon,
        Link,
      } = MaterialUI;
```

In such a case, would it is possible to run a step in the build process that does the following transformation?

```diff
-import DialogActions, { DialogActionsProps } from '@mui/material/DialogActions';
+import { DialogActions, DialogActionsProps } from '@mui/material/DialogActions';
```

**Comment by claudio-destro** [comment]
exactly

AFAIK there is no such possibility in `webpack`: the function used in `webpack.config.js` to _munge_ the `imports` has no access to the left side of the `from`.

Maybe there is some kind of plugin for doing this, I will investigate even though I don't think so.

However I see only two possibilities now:

1. you change your imports
2. I monkey patch our shared component module: `MaterialUI.Dialog.dialogClasses = MaterialUI.dialogClasses;`

**Comment by claudio-destro** [comment]
just a side note: 
we are not currently sharing icons in our app, but we change all our imports from `@mui/icons-material` due to the _opposite_ problem: importing an icon from root cause all the icons to be included in our package, not only the specific icon ;(

```
import {Abc} from "@mui/icons-material"; // All icons included

import Abc from "@mui/icons-material/Abc"; // Only Abc included
```

**Comment by claudio-destro** [comment]
Hey, first of all thank you for the hints!

I totally understand and agree with you about *not* using MUI provided by CDN, but:

- we need to share dependencies (such as MUI and React) between multiple modules of our app
- we need also to share those dependencies between 3rd party modules loaded by our app

We decided to use this approach:
https://single-spa.js.org/docs/recommended-setup/#utility-modules-styleguide-api-etc

However, our missing point is delegating babel the correct import syntax: I will try it as soon as possibile.

**Comment by claudio-destro** [comment]
I didn't have time to try the suggested fix 😓

However it seems you changed something in date picker or whatever: the problem disappeared. 

Anyway I will strive to follow the suggestions hopefully in the close future.

**Comment by LukasTy** [comment]
I'm closing this issue as it seems to have been resolved.
@claudio-destro if you think that there is still something missing here, please feel free to comment here or open a new issue. 👌
