### ISSUE TITLE
Hide column from "Columns" menu when hideable is set to false

### ISSUE THREAD

**Issue by Mikilll94** [mui/mui-x#8481]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

<img width="1061" alt="Screenshot 2023-04-02 at 19 45 17" src="https://user-images.githubusercontent.com/17653648/229369815-dd3c7906-6a5a-4a23-93ad-9ca8def4851b.png">

I don't see what's the point of displaying the column as disabled when setting `hideable` to `false`. Instead IMO the column should not be present in "Columns" menu.

### Motivation 🔦

I often have column with action buttons which does not have a title. I don't want to display this column in "Columns" menu.

**Comment by MBilalShafi** [comment]
@Mikilll94 It's debatable whether or not these columns should be hidden by default from the Columns Panel, I'd keep showing them to get the overall overview of the columns (hideable + not hideable).

Regarding the possibility of hiding them though, with [this recent enhancement](https://github.com/mui/mui-x/pull/8401), it will be possible to control the togglable columns shown in the Panel.

An example code snippet:
```tsx
<DataGrid
  slotProps={{
    columnsPanel: {
      // only show `age` and `desk` columns
      getTogglableColumns: () => ['age', 'desk']
    }
  }}
/>
```

It's not yet released (expected in the next release), but you can check out the preview [here](https://deploy-preview-8401--material-ui-x.netlify.app/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel).

**Comment by MBilalShafi** [comment]
I am closing the issue, if needed, please proceed with the conversation on the linked PR/issue (where the problem was fixed), or if needed feel free to reopen it.

**Comment by afternoon2** [comment]
Hey! Should this feature be described in the docs for v. 6.2.1 if it's still not released? 

I found it quite misleading while getting typescript errors about the method not present in the `columnsPanel` interface 😅
