### ISSUE TITLE
[pickers] UTC and timezone support

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#8484]
## Proposed API

```tsx
<DatePicker timezone="UTC" />
<DateTimePicker timezone="America/New_York" />
<TimeClock timezone="locale" />
```

### Choose in the timezone used for the rendered values / values passed to `onChange`

- If a `timezone` prop is passed, then we use this timezone
- If no `timezone` prop is passed and a `value` / `defaultValue` is provided, then we use the timezone of this value 
- If no `timezone` prop is passed an no `value` / `defaultValue` is provided, then we use the default timezone (and `locale` if the adapter do not support timezone out of the box like on dayjs or moment, and the timezone plugin is not enabled)

## Issues duplicating this one

#7832 (dayjs timezone)
#8461 (date-fns timezone)
#5689 (moment UTC)
#4734 (date-fns, don't want time part in a picker without time picking UI)

**Comment by PraveenPeri** [comment]
@flaviendelangle What is the ETA of this enhancement?

**Comment by flaviendelangle** [comment]
In the coming months
I hope that it wont take more than 2 months from now, but it's a very sensitive topic and I need to test it thoroughly before publishing anything.

**Comment by dmitri-anchorzero** [comment]
> By the way, we are highly interested in people's use cases with timezones / UTC. To make sure that we build something that correctly supports those use cases.

Thanks for your work here. Picking a date (e.g. a user's birthday) without any time component is the use-case that led me to this set of GH issues.

**Comment by flaviendelangle** [comment]
If I understand correctly, your main challenge is to make sure that the birthday is rendered the same regardless of your locale timezone (someone in New York using the application should see the same date as someone in London or Beijing is the value provided is the same).

This will be supported by the component after the PR linked in this issue.

I think the clean way of doing it would be to provide a UTC date.
The picker will then automatically use the UTC zone for the rendering and pass a UTC date to `onChange`.

But it should also work if you pass the date in the timezone of your organization. 

Note that timezone and UTC may not be supported by date-fns (I did not investigate how we can support it for this date library at least).
We plan to support Luxon, Moment and Dayjs with my PR.

**Comment by PraveenPeri** [comment]
> In the coming months I hope that it won't take more than 2 months from now, but it's a very sensitive topic and I need to test it thoroughly before publishing anything.
> 
> By the way, we are highly interested in people's use cases with timezones / UTC. To make sure that we build something that correctly supports those use cases.
We are a multi-tenant application and each tenant can choose to set a timezone and all the dates should be displayed in that timezone no matter what the browser location is.

**Comment by knutmarius** [comment]
I would also like to be able to lock the time zone for the date picker. In our application we are dealing with business in the Nordics, and users are supposed to set an "expiry date" on certain objects. We need to store a datetime with the time component, so as of default the DatePicker gives us local midnight. If the user goes on vacation to Japan and sets the expiry date to 1st of May, and then goes back to Norway, he/she will see that the expiry date now shows 30th of April. Even though this could be considered to be theoretically correct, we would like to be able to lock our date picker time zone so that it always treats dates as if in the CET time zone.

**Comment by flaviendelangle** [comment]
Thanks for your feedback!

I am checking if my implementation supports all the use cases people might need.
If you could have a look and tell me if I'm missing anything or if looks like your use case will work fine :+1: 
The demos are using `dayjs` but the exact same behavior will be possible using Moment or Luxon.

@dmitri-anchorzero I did [a playground](https://codesandbox.io/s/date-and-time-pickers-forked-hfueow?file=/src/App.tsx) to replicate what I understand from your use case.
The dates are rendered and stored in UTC, which means no matter where they are displayed, you will always have the same date and the time should always be at midnight with the `DatePicker`.

@PraveenPeri I did two playgrounds to replicate what I understand of your use case.
In the [first one](https://codesandbox.io/s/date-and-time-pickers-forked-4y6zjb?file=/src/App.tsx), I am storing the value in the rendered timezone.
In the [second one](https://codesandbox.io/s/date-and-time-pickers-forked-qhhg5b), I am storing the value in UTC but rendering them in the timezone chosen by the user (which would have to be stored in DB with the value and passed manually to the pickers).

@knutmarius I did [a playground](https://codesandbox.io/s/date-and-time-pickers-forked-fk3qcw?file=/src/App.tsx
) to replicate what I understand of your use case.
The dates are stored in the `Europe/Oslo` timezone (could be another one).

If you could also have a look at the [documentation](https://deploy-preview-8261--material-ui-x.netlify.app/x/react-date-pickers/timezone/) that would be great!

**Comment by PraveenPeri** [comment]
@flaviendelangle Thanks for the sandbox link. I think our requirement aligns more with that of @knutmarius. Our tenants will configure the time zone in settings somewhere in the application and all the date pickers for that tenant are now locked to that time zone. Your code seems to handle that. Thanks for the enhancement!

**Comment by SHergibo** [comment]
@flaviendelangle Thanks for the implementation of the UTC/timezone support, are we gonna see this change in the next version? And if yes, what is the ETA of the next version?

Thanks again.

**Comment by flaviendelangle** [comment]
It will be in the next release, which should be today or tomorrow :+1:

**Comment by oliviernt** [comment]
@flaviendelangle is a date-fns implementation of this feature still in the books?

**Comment by flaviendelangle** [comment]
I need to see what's doable with https://www.npmjs.com/package/date-fns-tz, but if possible yes it would be an important addition :+1:

**Comment by oliviernt** [comment]
That'd be great! Thank you :+1:

**Comment by LukasTy** [comment]
> Any news in regards to supporting date-fns adapter?

Thank you for bringing it up! 🙏
I've updated the relevant issue: https://github.com/mui/mui-x/issues/10573 and moved it to grooming so that we can prioritize.
[Date-fns v3](https://blog.date-fns.org/v3-is-out/#support-for-date-extensions) released some extensions that might increase the likelihood of coming up with an implementation that could work.

Feel free to subscribe to the mentioned issue to get notified about its progress. 😉 

I can only confirm that it currently isn't our top priority, so, don't expect it before the release of v7 stable. 🙈

**Comment by srinivaassunil** [comment]
Any updates or eta on timezone support for date-fns with pickers. I will have to plan to switch to dayjs if it takes longer.

**Comment by flaviendelangle** [comment]
We did not prioritize the support for date-fns for now given the expected complexity, we prefer to work on features that people cannot support on their side.
But hopefully we will have the bandwidth to do it at some point.

Migrating to dayjs is probably the best solution here
