### ISSUE TITLE
[DataGrid] Resize is breaking page

### ISSUE THREAD

**Issue by gabriel-rodriguess** [mui/mui-x#8488]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example in DataGrid v6: https://codesandbox.io/s/datagrid-v6-resize-bug-tolm65

### Current behavior 😯

On DataGrid v6 when you have a Side Drawer, the DataGrid doesn't resize to fit the page if the columns have "flex:1" when Side Drawer open and close.

### Expected behavior 🤔

The same behavior that happen on DataGrid v5, I created a sandbox exactly equal but using v5 and the DataGrid correctly resize and fit the page width.

Link to live example in DataGrid v5: https://codesandbox.io/s/datagrid-v5-resize-test-7f8jxp

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by tregoning** [comment]
@m4theushw the above statement does not seem to be correct, it's still broken

https://user-images.githubusercontent.com/160072/229900181-0b10bd19-1cc8-47c0-a9e2-378216ad5f38.mov
