### ISSUE TITLE
`Grouping` + `Column Group` cause runtime error

### ISSUE THREAD

**Issue by michael-land** [mui/mui-x#8492]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/datagrid-forked-s9np3z

Steps:
1. Group by column 1
2. Ungroup by column 1

https://user-images.githubusercontent.com/33362998/229628968-0c894ff9-a640-49ff-a5cf-32e90377d995.mov

### Current behavior 😯

throw runtime exception

### Expected behavior 🤔

no exception

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
@m4theushw Is that patch good to be applied as-is?

**Comment by edecarlini** [comment]
Any updates about this issue? I got the same trouble and i'm stuck with this right now

**Comment by romgrk** [comment]
I think you could submit a PR with the patch above. The task is in our backlog so we'll get around to it at some point soon-ish.

**Comment by claudioctonha** [comment]
I'm also waiting for this fix. Thanks.

**Comment by edecarlini** [comment]
> For anyone else coming here, the current version at the time of this is "@mui/x-data-grid-premium": "^6.16.2", the fix for us was just to send it an empty column, i.e. TableColumn.name_of_your_column('name_of_your_group_field', ''); This seems to have gotten rid of the error.

Hi Jonathan, could you share a screenshoot about the example that you said before?. It would be very useful if it's works.

Thanks.

**Comment by cherniavskii** [comment]
Is this issue still reproducible?
I cannot reproduce it in the demo in the issue description.
It seems to work fine with the latest version (6.17.0) of the data grid: https://codesandbox.io/s/datagrid-forked-rnsgs6
