### ISSUE TITLE
[data grid] Sorting row groups in DataGrid with custom groupingValueGetter

### ISSUE THREAD

**Issue by john1625b** [mui/mui-x#8493]
### Order ID or Support key 💳 (optional)

61801

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi, my project has a date column which I use to group the rows, it is of format "2023-04-01". The caveat is that I want to group by month ( and eventually year, quarter and week through a dropdown). 

My issue is that when I try to sort the values, it only sorts within the group rather than sorting the groups themselves. As you can see in the sandbox I've linked below, sorting by date only sorts within the groups (months in this case).

https://codesandbox.io/s/festive-satoshi-fmszwu?file=/demo.tsx:445-892

I'd expect the under-the-hood sorting to work by first sorting every row in the table and then grouping them when you click the sorting arrow. 

the relevant column:
```
    {
      field: "datetime",
      headerName: "Datetime",
      width: 200,
      type: "datetime",
      valueFormatter: (params) => new Date(params.value).toLocaleDateString(),
      groupingValueGetter: (params) =>
        new Date(params.row.datetime).toLocaleString("default", {
          month: "short"
        }),
      hide: true
    },
```

I have read this article on sorting within row grouping and I tried adding `  rowGroupingColumnMode="single"` and it didn't fix the issue, but I'm probably misreading that article. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.113 
    @mui/core-downloads-tracker:  5.11.4 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.4 => 5.11.4 
    @mui/private-theming:  5.11.2 
    @mui/styled-engine:  5.11.0 
    @mui/system:  5.11.4 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.2 
    @mui/x-data-grid: ^5.17.21 => 5.17.21 
    @mui/x-data-grid-generator: ^5.17.20 => 5.17.20 
    @mui/x-data-grid-premium: ^6.0.4 => 6.0.4 
    @mui/x-data-grid-pro: ^5.17.20 => 5.17.20 
    @mui/x-license-pro:  5.17.12 
    @types/react: ^16.9.49 => 16.9.49 
    react: ^16.13.1 => 16.14.0 
    react-dom: ^16.13.1 => 16.14.0 
    typescript: ^4.9.4 => 4.9.4 

</details>

**Comment by joserodolfofreitas** [comment]
Hi @john1625b, in this case, you'll need to set up a [custom sortComparator](https://mui.com/x/react-data-grid/sorting/#custom-comparator) on your column definition. Does that help you solve your issue?

**Comment by john1625b** [comment]
Hi @joserodolfofreitas , thanks for the response. I will look into the custom sortComparator but how come the sorting doesn't work out-of-the-box? I see on the example of row grouping on the MUI docs that sorting the groups themselves works without any custom sortComparator.

I have `type: "datetime"` in the Datetime column and also `valueGetter: params => params.row.datetime`  to give it the proper underlying value to sort by. So you'd think that DataGrid could just infer how to sort the groups.

**Comment by yaredtsy** [comment]
hey @john1625b 

its Because you are rendering leaves with the `leafField` property of `groupColDef`, the sorting and filtering will be applied on the leaves based on the sortComparator and filterOperators of their original column. you can read about it more at [here](https://mui.com/x/react-data-grid/row-grouping/#sorting-filtering).  use `mainGroupingCriteria`

**Comment by john1625b** [comment]
@yaredtsy 
I commented out the `groupingColDef` prop on the component and now the groups themselves are now indeed sorting. However, the group seems to be sorting in random order. I would like for the months to sort chronologically (Jan, Feb, Mar etc). I have the `valueGetter` to use the proper timestamp value but it's still not working. 

As you can see, ASC is set but the order seems random:
![Screenshot 2023-04-09 at 5 38 54 PM](https://user-images.githubusercontent.com/17265085/230797669-3bcd8a87-c162-4f53-a646-5ec679ee65d5.png)

**Comment by yaredtsy** [comment]
`new Date(params.row.datetime).toLocaleString("default", {
          month: "short"
        }),` this is changes the date to `string` so its sorting them as a string. you have to use custom `sortComparator`

**Comment by john1625b** [comment]
@yaredtsy @joserodolfofreitas 
I've added a custom sortComparator to my example: https://codesandbox.io/s/festive-satoshi-fmszwu?file=/demo.tsx

However it's not working and when I log `v1` and `v2`, it's logging the months "Jan", "Feb" so I suspect this is why its not working. Instead of comparing the time stamp, it comparing the month values. 

However I tried using valueFormatter, valueGetter and valueParser and all of them do not give the sortComparator the proper timestamp value. It seems like groupingValueGetter overrides all those values and gives the sortComparator the month value. 

Thanks in advance for any help and sorry if the docs mention the solution but I couldn't find it perusing through it.

**Comment by yaredtsy** [comment]
@john1625b you need to set the order of the month yourself. so that it can sort with the order of the month.

```jsx
const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];

const dateSorter = (v1, v2) => {
  const v1index = months.findIndex((mon) => v1 === mon);
  const v2index = months.findIndex((mon) => v2 === mon);
  return v1index - v2index;
};
```

**Comment by cherniavskii** [comment]
I believe the proper way to handle this use case is to return a number from `groupingValueGetter`.
Depending on the use case, it could be:
- month index, if the year doesn't matter:
    ```js
	groupingValueGetter: (params) => {
	  return params.value.getMonth(); // returns month index, from 0 to 11
	},
	```
- timestamp of the date containing only year and month (the day and time is zeroed), if the year matters

This would allow grouping the rows **and** properly sorting them (since you don't want to sort them alphabetically):

Here's a demo with a month index, where you can see that the rows are properly grouped and the groups are sorted as expected: https://codesandbox.io/s/tender-bohr-3ned48?file=/demo.tsx 

To show the month name in the group instead of the month index, you can use `groupingColDef.valueFormatter`:
```tsx
function getMonthName(monthIndex: number) {
  return new Date(1970, monthIndex, 1).toLocaleString('default', {
    month: 'short',
  });
}
// ...
<DataGridPremium
	groupingColDef={{
	  valueFormatter: (params) => {
	    return getMonthName(params.value);
	  },
	}}
/>
```

Here is a full working demo: https://codesandbox.io/s/elastic-stonebraker-8mdzsf?file=/demo.tsx

The same approach could be used for grouping by month, quarter, year, etc.
Is this what you were looking for?
