### ISSUE TITLE
[pickers] `componentsProps.dialog` not being applied

### ISSUE THREAD

**Issue by adaaaam7777** [mui/mui-x#8506]
Hi!

Recently migrated from v4 to v6 and my custom styling for the Dialog part is broken, can't figure out how to solve it.

I used it like this before:
```
<MobileDatePicker
    value={productDate}
    onChange={(newValue) => dateChanged(newValue, index)}
    renderInput={(params) => <TextField {...params} />}
    DialogProps={customcss}
    components={{ActionBar: MyActionBar}}
											/>
```

where the customcss is:
   customcss= {
```
	sx: {
		'& .MuiPaper-root': {
			width: '95%',
			margin: '0',
			height: '880px',
			maxWidth: '95%',
			'& .MuiDialogContent-root': {

				'& > div': {
					flexDirection: 'column',

					'& > div:nth-of-type(2)': {
						width: 'calc(100% - 48px)',
						maxHeight: 'calc(1000px - 32px)'
					},
				},
				'& .MuiPickersToolbar-root.MuiDatePickerToolbar-root': {
					padding: '16px 50px',
					maxWidth: '100%',
					width: 'calc(100% - 100px)',

					'& .MuiGrid-root.MuiGrid-container': {
						flexDirection: 'row',
						display: 'flex',
						alignItems: 'flex-start',
						width: 'auto',

						'& .MuiGrid-root.MuiPickersToolbar-content': {

						}
					}
				} ,......
```

Now I tried like these: 

```
<MobileDatePicker
  value={productDate}
  onChange={(newValue) => {dateChanged(newValue);}}
  textField={(params) => <TextField {...params} />}
  slotProps={{
	  Dialog: {
		  backgroundColor: 'red',
		  sx: {
			  backgroundColor: 'red',
			  '.MuiDialog-root': {
				  backgroundColor: 'red'
			  }
		  }
	  }
  }}
  components={{ActionBar: MyActionBar}}
  />
```

But none has any effect. Thanks!

**Comment by LukasTy** [comment]
Hello! There is a small issue with how `dialog` props are applied that needs to be fixed.
Based on the provided snippet I take that you are not using TS, in that case, be sure to remember that `slotProps` or `componentsProps` (deprecated in v6) fields are lowercased.
But in any case, if you do not need to style the Dialog itself (the backdrop or something like that), consider using the `mobilePaper` slot to target the `Paper` component itself. At least based on your previous styles, it seems that this is actually your main concern. 🤔 
```diff
slotProps = {{
-  Dialog: {
+  mobilePaper: {
    sx: {
      backgroundColor: 'red',
    }
  }
}}
```

You can find all the [available slots here](https://mui.com/x/api/date-pickers/mobile-date-picker/#slots).
