### ISSUE TITLE
[pickers] PickersDay's disableMargin prop does not disable the margin in the Calendar's Week Day Label

### ISSUE THREAD

**Issue by laichak** [mui/mui-x#8507]
### Duplicates

- [X] I have searched the existing issues
- 
May related to https://github.com/mui/mui-x/issues/5366

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

When PickersDay's disableMargin is true, the Calendar's week day label does not align with the content below.

The coding is referencing https://mui.com/x/react-date-pickers/date-calendar/#custom-day-rendering

My workaround is to use padding in PickersDay to counteract disableMargin, in order for the Days to align with the Week Day Labels:

`<CustomPickersDay`
 `     {...other}`
`      day={day}`
`      disableMargin`
`      dayIsBetween={dayIsBetween}`
`      isFirstDay={isFirstDay}`
`      isLastDay={isLastDay}`

`     sx={{ px: 2.5 }} `

`    />`

### Current behavior 😯

![image](https://user-images.githubusercontent.com/3492871/229871457-a3592b37-a90d-433a-bf8b-06cd84adcc8b.png)

### Expected behavior 🤔

![image](https://user-images.githubusercontent.com/3492871/229871329-097d2710-3de2-47ea-8551-4604ec2df319.png)

### Your environment 🌎

MUI-X 6.0.4

**Comment by LukasTy** [comment]
Hello, let me first clarify that there is no reason for the `disableMargin` prop on `PickersDay` to take effect on the Week Day label, those are totally separate components in the context of the `DateCalendar`.
If you specifically need to remove the margin from the "week day" label elements, consider adding the following prop to the `DateCalendar` component:
```tsx
sx={{
  [`.${dayPickerClasses.header} .${dayPickerClasses.weekDayLabel}`]: {
    margin: 0
  }
}}
```

In regards to your solution for aligning spacing to the existing week header layout, I'd say it needs a few fine-tuning tweaks to avoid issues when the month doesn't start on the first day of the week:
```diff
sx={{
-  px: 2.5
+  [`&:not(.${pickersDayClasses.hiddenDaySpacingFiller})`]: {
+    px: 2.5
+  },
+  [`&.${pickersDayClasses.hiddenDaySpacingFiller}`]: {
+    px: .25
+  }
}}
```
Let me know if you are still having issues coming up with a working solution.

**Comment by laichak** [comment]
Okay, I can get the code run, here is the result for using the pickersDayClasses.hiddenDaySpacingFiller appoach:

`import { PickersDay, pickersDayClasses } from '@mui/x-date-pickers/PickersDay';`

`<CustomPickersDay`
`            {...pickersDayProps}`
`            day={day}`
`            disableMargin`
`            dayIsBetween={dayIsBetween}`
`            selected={dayIsBetween}`
`            isFirstDay={isFirstDay}`
`            isLastDay={isLastDay}`
`            sx={{`
`                [`&:not(.${pickersDayClasses.hiddenDaySpacingFiller})`]: {`
`                    px: 2.5`
`                },`
`                [`&.${pickersDayClasses.hiddenDaySpacingFiller}`]: {`
`                    px: .25`
`                }`
`            }}`
`        />`


![image](https://user-images.githubusercontent.com/3492871/230477145-bb995b81-2282-4136-b87a-0ef659ae68ef.png)

**Comment by laichak** [comment]
Just found out an alternative without PickersDay's disableMargin props.
Thanks for your help.

`<CustomPickersDay`
`            {...pickersDayProps}`
`            day={day}`
`            dayIsBetween={dayIsBetween}`
`            selected={dayIsBetween}`
`            isFirstDay={isFirstDay}`
`            isLastDay={isLastDay}`
`            sx={ dayIsBetween ? { px: 2.5, mx: 0 } : { } }`
`        />`

**Comment by LukasTy** [comment]
> Just found out an alternative without PickersDay's disableMargin props.

That is a really good and clean solution! Thanks. 🙏 
I think we should update our demo to use it instead to avoid the misalignment between week day labels and the week days. 👌
