### ISSUE TITLE
`renderDay` does not execute within `StaticDateRangePicker`

### ISSUE THREAD

**Issue by gudlyf** [mui/mui-x#8517]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/modest-jasper-4nq6vs?file=/src/App.js:498-519

Steps:
1. Updated to v6 from v5 of `@mui/x-date-pickers-pro`
2. Calendar formatting for days no longer renders
3. Adding simple test to see if `renderday` gets called via `console.log`. Confirmed not being called.

### Current behavior 😯

There is no evidence that `renderDay` gets called at all.

### Expected behavior 🤔

`renderDay` gets called, so formatting within the calendar can be achieved, as was possible in v5.

### Context 🔦

I use this functionality to apply Tooltip and styling to the days within the date range. This is no longer possible if `renderDay` is not called.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: Not Found
    Firefox: 110.0.1
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.124 
    @mui/core-downloads-tracker:  5.11.16 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.125 => 5.0.0-alpha.125 
    @mui/material: ^5.11.16 => 5.11.16 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.16 
    @mui/styles: ^5.11.16 => 5.11.16 
    @mui/system:  5.11.16 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-date-pickers:  6.0.4 
    @mui/x-date-pickers-pro: ^6.0.4 => 6.0.4 
    @mui/x-license-pro:  6.0.3 
    @types/react:  17.0.50 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.0.3 => 5.0.3 
```
</details>

### Order ID or Support key 💳 (optional)

58246

**Comment by LukasTy** [comment]
Hello @gudlyf 
Please follow [the migration guide section](https://mui.com/x/migration/migration-pickers-v5/#day-renderday) to learn how to migrate `renderDay` to the new `day` component slot. 😉 
Do note that you can use either the old and now deprecated `components.Day` or the newly introduced `slots.day` to pass your custom component. 👍
