### ISSUE TITLE
DatePicker not rendering below the custom textField component

### ISSUE THREAD

**Issue by jordanshardy** [mui/mui-x#8521]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-v6-date-picker-ej19ur?file=/app.tsx

Steps:
1. Upgraded `DatePicker` to v 6.0.1
2. Refactored deprecated use of components to slots
3. rendering custom button on `textField`

### Current behavior 😯

The DatePicker is rendering on the top left of the screen. 

![Screenshot 2023-04-06 at 1 57 21 pm](https://user-images.githubusercontent.com/42752264/230268445-8f942753-ee52-4bb4-84c2-a1c0bc55d836.png)

### Expected behavior 🤔

Given I'm passing `ref={params.inputRef}` to the custom button ref, I'd expect the `DatePicker` to be rendered below the button. 

If I pass a custom button using `inputAdornment` on `slots`  the picker renders below the button/input as expected. 

### Context 🔦

The DatePicker should be rendering below the custom button. Am I not using the slots prop with textField correctly or is this a bug? Furthermore, I'm curious how can I further customize where on the page the DatePicker is rendered. But this may be a different question.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Hello @jordanshardy 
We have recently updated the customization documentation including an example just for such a case.
Please [follow the provided example](https://mui.com/x/react-date-pickers/custom-field/#using-a-button) for guidance on how to fix your case. 😉

**Comment by jordanshardy** [comment]
> Hello @jordanshardy We have recently updated the customization documentation including an example just for such a case. Please [follow the provided example](https://mui.com/x/react-date-pickers/custom-field/#using-a-button) for guidance on how to fix your case. 😉

@LukasTy Thank you for the response and direction. 

Appreciate your work.
