### ISSUE TITLE
Setting DatePicker format to DD MMM YYYY but deleting the MMM will make the textfield shows MMMM (Long Month format)

### ISSUE THREAD

**Issue by kianjun0929** [mui/mui-x#8526]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Use the basic date picker
2. Make the format to 'DD MMM YYYY'
3. Select any date from Date Picker or enter from keyboard
4. Manual delete the MMM
5. The preview will show 'DD MMMM YYYY'

### Current behavior 😯

![image](https://user-images.githubusercontent.com/41623077/230328222-e5347c66-7ea0-48b0-bd02-7efc6dcdbe3b.png)
![image](https://user-images.githubusercontent.com/41623077/230328273-259f0722-550f-4759-a115-8588991d65e4.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
That's the expected behavior. When a section is empty, it shows a placeholder which is not necessarily the format token. Here for month, the default is 4 letters for words and 2 letters for numbers

```
// From src/locales/enUS.ts
fieldMonthPlaceholder: (params) => (params.contentType === 'letter' ? 'MMMM' : 'MM'),
```

You can modify this behavior by providing custom `localeText`:
```ts
// Field section placeholders
fieldYearPlaceholder: (params) => 'Y'.repeat(params.digitAmount),
fieldMonthPlaceholder: (params) => (params.contentType === 'letter' ? 'MMMM' : 'MM'),
fieldDayPlaceholder: () => 'DD',
fieldWeekDayPlaceholder: (params) => (params.contentType === 'letter' ? 'EEEE' : 'EE'),
fieldHoursPlaceholder: () => 'hh',
fieldMinutesPlaceholder: () => 'mm',
fieldSecondsPlaceholder: () => 'ss',
fieldMeridiemPlaceholder: () => 'aa',
```

This information could be added in the base [concept pages](https://mui.com/x/react-date-pickers/base-concepts/)

**Comment by kianjun0929** [comment]
Thanks Alex for the input, it works now.

**Comment by alexfauquette** [comment]
@flaviendelangle What do you think about?

> This information could be added in the base [concept pages](https://mui.com/x/react-date-pickers/base-concepts/)

**Comment by flaviendelangle** [comment]
They are documented [here](https://mui.com/x/react-date-pickers/adapters-locale/#custom-field-placeholder)

I think it's too specific to be in the *Base concept*

**Comment by alexfauquette** [comment]
Ok, it appears in algolia, so might be enough, will see it this issue arrive back

![image](https://user-images.githubusercontent.com/45398769/230587329-7e09fb64-bd70-4881-b2fc-0cb1d7e2af82.png)

**Comment by AkshayHere** [comment]
> That's the expected behavior. When a section is empty, it shows a placeholder which is not necessarily the format token. Here for month, the default is 4 letters for words and 2 letters for numbers
> 
> ```
> // From src/locales/enUS.ts
> fieldMonthPlaceholder: (params) => (params.contentType === 'letter' ? 'MMMM' : 'MM'),
> ```
> 
> You can modify this behavior by providing custom `localeText`:
> 
> ```ts
> // Field section placeholders
> fieldYearPlaceholder: (params) => 'Y'.repeat(params.digitAmount),
> fieldMonthPlaceholder: (params) => (params.contentType === 'letter' ? 'MMMM' : 'MM'),
> fieldDayPlaceholder: () => 'DD',
> fieldWeekDayPlaceholder: (params) => (params.contentType === 'letter' ? 'EEEE' : 'EE'),
> fieldHoursPlaceholder: () => 'hh',
> fieldMinutesPlaceholder: () => 'mm',
> fieldSecondsPlaceholder: () => 'ss',
> fieldMeridiemPlaceholder: () => 'aa',
> ```
> 
> This information could be added in the base [concept pages](https://mui.com/x/react-date-pickers/base-concepts/)

Any ideas on how to use the `fieldMonthPlaceholder` ? 
There are no examples there where I can see how this is used.

**Comment by flaviendelangle** [comment]
You have the answer just above :+1: 

https://github.com/mui/mui-x/issues/8526#issuecomment-1500117848

**Comment by Shekiel** [comment]
@flaviendelangle I agree with @AkshayHere, could you please provide an example of how this can be used?

**Comment by Shekiel** [comment]
@LukasTy Thanks, just checked checked this, and this worked for me: Changing the fieldMonthPlaceholder as shown in the example to get the correct format:
` <LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale="en-gb" localeText={{ fieldMonthPlaceholder: (params) =>
      params.contentType === 'digit' ? 'MM' : params.format,}}>`
