### ISSUE TITLE
[DataGrid] Alternative filter row 

### ISSUE THREAD

**Issue by MieleVL** [mui/mui-x#8529]
### Order ID or Support key 💳 (optional)

33929

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm looking for a way to insert an extra header row to render simple filter controls. Filters can be updated using the DataGrid API, but adding an extra header row doesn't seem possible at this time.

I saw this draft PR where this feature was partially implemented:  https://github.com/mui/mui-x/pull/7760
Is this a feature that is already available, actively working on, or should I use the `renderHeader` function on each column to implement it ourselves. Or maybe there is an alternative way?

I'm looking for something like below:

![image](https://user-images.githubusercontent.com/7256772/230378271-c31cac37-9067-4c0b-9ab7-5a55c9657945.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Hey @MieleVL, Filtering on Header feature is actively under development and we are trying to pull the initial working version as soon as possible.
This has previously been requested previously multiple times, you can check the issues linked on the [main issue](https://github.com/mui/mui-x/issues/6247) to check any previous discussions on the topic.

Meanwhile, if you want to try the [WIP Preview](https://deploy-preview-7760--material-ui-x.netlify.app/x/react-data-grid/filtering/#header-filtering) and possibly provide some early feedback, you are most welcome to do so.

**Comment by MBilalShafi** [comment]
I am closing this one, please followup on the PR or main issue related to this.
