### ISSUE TITLE
[pickers] package is incompatible with @mui/material for versions equal to or lower than 5.8.x

### ISSUE THREAD

**Issue by Nic-S** [mui/mui-x#8530]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/exciting-snyder-56xih1

### Current behavior 😯

build error

### Expected behavior 🤔

fix ir or upgrade peer dependency of pikers and documentation

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Thank you very much for opening this issue and reporting stale `peerDeps`! 🙏

**Comment by Nic-S** [comment]
@LukasTy Another point to watch out for is the **@mui/base** dependency, as it is not among the _peer dependencies_ and if an older version of **npm such as 8.1** is used for package installation, it causes problems as the dependencies of downloaded packages are not installed in the root of the project's node_modules.

**Comment by LukasTy** [comment]
@Nic-S Thank you for the heads-up. We'll look into it. 👌

**Comment by LukasTy** [comment]
> if an older version of **npm such as 8.1** is used for package installation, it causes problems as the dependencies of downloaded packages are not installed in the root of the project's node_modules.

I've tried experimenting with your provided problematic scenario.
I've downgraded npm to `8.1.0`, created an empty project, added the necessary dependencies, installed everything and successfully ran an app having a `DatePicker`. The `@mui/base` has been installed on the root __node_modules__ level. 🤔 
Maybe there is something I'm missing? A different __npm__ version? 🤔

**Comment by Nic-S** [comment]
> > if an older version of **npm such as 8.1** is used for package installation, it causes problems as the dependencies of downloaded packages are not installed in the root of the project's node_modules.
> 
> I've tried experimenting with your provided problematic scenario. I've downgraded npm to `8.1.0`, created an empty project, added the necessary dependencies, installed everything and successfully ran an app having a `DatePicker`. The `@mui/base` has been installed on the root **node_modules** level. 🤔 Maybe there is something I'm missing? A different **npm** version? 🤔

Very strange 🤔. I use node version 16.13.0 with its version of npm i.e. 8.1.0, and as you can see from the screen i don't have @mui/base in the root of @mui's node_modules and this causes me errors in the build.

(I have the minors installed right)
<img width="310" alt="Screenshot 2023-04-11 alle 11 25 38" src="https://user-images.githubusercontent.com/18029425/231116719-4a9c1220-aeba-4545-9fd4-ddb219bc2b91.png">
<img width="260" alt="Screenshot 2023-04-11 alle 11 25 46" src="https://user-images.githubusercontent.com/18029425/231116747-0566a01a-2821-4b18-a101-7c3b0463ce4b.png">
<img width="453" alt="Screenshot 2023-04-11 alle 11 28 41" src="https://user-images.githubusercontent.com/18029425/231117430-eac27a6b-a0ce-4ab2-96e0-704a4b664ae5.png">

**Comment by LukasTy** [comment]
I have only downgraded `npm`. Will try looking if downgrading `node` has an effect (even though it would be super strange).
By the way: What kind of bundler are you using?
Having a minimal repo where it would be possible to reproduce the issue would go a long way. 🙈

**Comment by Nic-S** [comment]
Honestly I am surprised, I also did a test from scratch and I have packages like yours that are different from my project. 

<img width="1678" alt="Screenshot 2023-04-11 alle 18 24 27" src="https://user-images.githubusercontent.com/18029425/231228579-07eb6c67-7357-4844-9788-9d7f08990b9d.png">

I investigate better but at this point it is a problem with my project, I have of course already tried to re-install from scratch including the clean npm cash.

Right now I feel a little bit like this:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/18029425/231229314-8d68310c-c5e8-4f72-b546-19cf01986662.png)

**Comment by Nic-S** [comment]
OK, with node 16.13.0 and npm 8.1.0 and react 17, we have the package problem. (why we don't have the problem with react 18 I still don't understand)

<img width="1067" alt="Screenshot 2023-04-11 alle 20 31 42" src="https://user-images.githubusercontent.com/18029425/231259559-4bef68d3-f192-47a1-a15e-73edac4009e7.png">

if we upgrade to node 16.14.0 and use its npm 8.3.1 also with react 17 we no longer have the problem.

<img width="1011" alt="Screenshot 2023-04-11 alle 20 41 46" src="https://user-images.githubusercontent.com/18029425/231259889-de977043-f1f9-422c-9eab-374725aaaa7a.png">

**Comment by LukasTy** [comment]
@Nic-S I can confirm that your use case is reproducible.
Seeing this case, IMHO, it makes sense to add `@mui/base` as a `peerDependency` and avoid such a case. 👌 
P.S. I've tested locally that adding `@mui/base` as peer dep to `@mui/x-date-pickers` solves this issue. 😉

**Comment by Nic-S** [comment]
> @Nic-S I can confirm that your use case is reproducible. Seeing this case, IMHO, it makes sense to add `@mui/base` as a `peerDependency` and avoid such a case. 👌 P.S. I've tested locally that adding `@mui/base` as peer dep to `@mui/x-date-pickers` solves this issue. 😉

Yes because peer dependencies are downloaded differently than dependencies. Thank you for your availability!
