### ISSUE TITLE
[DataGridPro] Want to restrict some cols to 1 filter, having trouble implementing #4872 fix

### ISSUE THREAD

**Issue by aka5050** [mui/mui-x#8534]
### Order ID or Support key 💳 (optional)

2d006ee30b111b6f9087eb2345ced98eTz01NjQzMyxFPTE3MDMxNTgyMDU1MzcsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI=

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Working with x-data-grid-pro version 5.17.18

filterMode='server'

For one of our tables where we use multi filtering I want to limit 2 of the columns to only 1 filter which can be applied.
I attempted to use the approach suggested in #4872, `filterColumns: ({ columnField }) => [...]`, but getting browser error ***"Warning: React does not recognize the 'filterColumns' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'filtercolumns' instead. If you accidentally passed it from a parent component, remove it from the DOM element."***

my implementation:
```
<DataGridPro
    ...
    componentsProps={{
        filterPanel: {
            filterFormProps: {
                ....
                filterColumns: ['test']
            }
        }
    }}
    ...
/>

```

This had no effect on the column options which appear in the filter menu. The Goal is to have a function for filterColumn which will return available column options based on current filters.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 13.3
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: Not Found
    npm: 9.6.2 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: Not Found
    Firefox: 102.9.0
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.122 
    @mui/core-downloads-tracker:  5.11.14 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/material: ^5.11.13 => 5.11.14 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.14 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-data-grid:  5.17.18 
    @mui/x-data-grid-pro: ^5.17.18 => 5.17.18 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react: ^17.0.53 => 17.0.53 
    react: ^17.0.0 => 17.0.2 
    react-dom: ^17.0.0 => 17.0.2 
    typescript: ^4.9.4 => 4.9.5 
```
</details>

**Comment by MBilalShafi** [comment]
Can you confirm if you are using `filterColumns` as an array (as shown in your code footprint)? It should be a function returning an array, so this might be the issue.

I couldn't reproduce the console error in [this codesandbox](https://codesandbox.io/s/black-thunder-goh1l5?file=/demo.tsx) which uses `filterColumns`.

Could you try reproducing the issue in the above-mentioned codesandbox and attach the uodated sandbox link here?

**Comment by aka5050** [comment]
I had the array plugged in as a test. I plugged in the filterColumns and getColumnForNewFilter functions from the sandbox but still getting  ***React does not recognize...***. Also when attempting to import `FilterColumnsArgs` and `GetColumnForNewFilterArgs` from **@mui/x-data-grid-pro** I get: ***Module '"@mui/x-data-grid-pro"' has no exported member 'FilterColumnsArgs'/'GetColumnForNewFilterArgs'***. I used a type "any" temporarily.

```
componentsProps={{
                        filterPanel: {
                            linkOperators: [],
                            filterFormProps: {
                                operatorInputProps: {
                                    disabled: true,
                                    sx: { display: 'none' }
                                },
                                filterColumns
                            },
                            getColumnForNewFilter
                        }
                    }}
```

**Comment by MBilalShafi** [comment]
Can you confirm the package version you are using?

**Comment by aka5050** [comment]
Version 5.17.18

**Comment by MBilalShafi** [comment]
@aka5050 This enhancement is released on [v6 only](https://github.com/mui/mui-x/pull/6333#issuecomment-1433453986) which is why you are not able to import it from the package.

You can see the documentation [here](https://mui.com/x/react-data-grid/filtering/#one-filter-per-column) or playaround with it in this codesandbox [example](https://codesandbox.io/s/sc5p1e?file=/demo.tsx).

MUI-X v6 stable release is already released, I encourage you to upgrade to enjoy exciting [new features](https://mui.com/x/whats-new/) and a more stable grid experience.

For more information on how to migrate, you can check out the [migration guide](https://next.mui.com/x/migration/migration-data-grid-v5/).
