### ISSUE TITLE
[pickers] Some demos miss `dayjs` in Codesandbox

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#8536]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-date-pickers/date-range-picker/#basic-usage

Steps:
1. Open the demo in Codesandbox
2.
```
DependencyNotFoundError
Could not find dependency: 'dayjs' relative to '/node_modules/@mui/x-date-pickers/AdapterDayjs/index.js'
```

### Context 🔦

The `dayjs` dependency is added automatically if dayjs adapter is detected in:
https://github.com/mui/material-ui/blob/9f5ae34c2454b600347417bf3d6037d1390df9d0/docs/src/modules/sandbox/Dependencies.ts#L132
One possible solution is to update the regex to detect the adapter imported from the pro package:
```diff
const dateAdapterMatch = fullName.match(
-        /^@mui\/(lab|x-date-pickers)\/(?<adapterName>Adapter.*)/,
const dateAdapterMatch = fullName.match(
+        /^@mui\/(lab|x-date-pickers|x-date-pickers-pro)\/(?<adapterName>Adapter.*)/,
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Another possible solution is mentioned here: https://github.com/mui/mui-x/pull/8535/files#r1160455906 👌
