### ISSUE TITLE
[fields] issue when entering a date from the keyboard on an existing date

### ISSUE THREAD

**Issue by david-ic3** [mui/mui-x#8542]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

A little variation of your localization example : https://codesandbox.io/s/inspiring-benz-6sgsle

1. Enter a valid date in April , i.e. 07/04/2022
2. Go to the start of the input and try entering 31/03/2020. ( March has 30 days ) 

### Current behavior 😯

The Picker doesn't allow to enter 31 as March has only 30 days, so you end up with another date (if you are using MMMM for months you actually will enter 30 March 2020)

### Expected behavior 🤔

Even though 31 is an invalid date for March it should be possible to enter invalid days through the keyboard as we can't expect a user to go to the month and after to change the day when days are before month.  

### Order ID or Support key 💳 (optional)

#19458

**Comment by LukasTy** [comment]
Thank you for creating this issue! 🙏 

> * Enter a valid date in April , i.e. 07/04/2022
> * Go to the start of the input and try entering 31/03/2020. ( March has 30 days )

Could you please confirm the steps to reproduce the issue or maybe create a video displaying the issue?
Because AFAIK, March does have 31 days. 🤷

**Comment by david-ic3** [comment]
@Lukas , the user tries to enter 31 03 2020, that is a valid date.  But he can't enter 31 as a day.

Please, let me know if you still need a video

**Comment by LukasTy** [comment]
Ah, gotcha, the missing explicit `dd/MM/yyyy` format in the linked example has confused me.
Do note that the fields behave differently depending on whether they have a valid value already or not.
- In case the field would not have a valid value yet-it would allow user entering `31/04` and would update the day only when the date entering is complete (produces a valid date)
- In case the field does already have a valid value, then making any changes always invokes the input "fixing" to produce a valid date if it's possible, that's essentially a must given the need for auto section switching

I'm not sure about what would be the best solution for such cases...
Maybe providing an option to toggle the auto section switching and in turn the input validity "fixing" would be an option to allow users to opt-out for such cases? 🤔 

FYI, [Kendo](https://www.telerik.com/kendo-react-ui/components/dateinputs/dateinput/formats/) does also have the same problem.

**Comment by flaviendelangle** [comment]
The browser input allows to enter `31/04/2022`

The change would be very simple on our size if we wanted to do it:

```tsx
--- a/packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts
@@ -686,10 +686,7 @@ export const getSectionsBoundaries = <TDate>(
     }),
     day: ({ currentDate }) => ({
       minimum: 1,
-      maximum:
-        currentDate != null && utils.isValid(currentDate)
-          ? utils.getDaysInMonth(currentDate)
-          : maxDaysInMonth,
+      maximum: maxDaysInMonth,
       longestMonth: longestMonth!,
     }),
     weekDay: ({ format, contentType }) => {
```

Not sure this behavior is worth adding a prop to toggle between the two.
Otherwise, I fear that we end up with a ton of boolean prop to tweak the editing behaviors and with a poor DX overall.
I'd be in favor of just changing the default behavior or do nothing.

**Comment by david-ic3** [comment]
my two cents, I'd allow entering temporary invalid days (for months and years it's different as changing the other subfields are never going to make them valid), looks more as what a end user would expect

**Comment by LukasTy** [comment]
> The change would be very simple on our size if we wanted to do it:

FYI: As far as I've tested, the suggested change does not seem to be enough and causes side effects. 🙈

**Comment by flaviendelangle** [comment]
Could you describe the side effects please ?

**Comment by LukasTy** [comment]
> Could you describe the side effects please ?

The field behave a bit unexpectedly: it triggers an error state, but moves to the next section (day in the example) and also keeps the visible month value the same as before the modification. 🤷 
https://user-images.githubusercontent.com/4941090/231105730-fac44c1d-3e8d-4a41-8217-dfa8035f3809.mov

**Comment by flaviendelangle** [comment]
> To be fair, we would also have to make sure that all date libraries at displaying an error when this invalid date is entered.
If I recall, some consider that 31/04 === 01/05, so we might have to trigger a manual error, which increases the complexity o the change.

May be related to this point

**Comment by McGern** [comment]
I have a related issue (I think the same issue), which isn't so much to do with overwriting existing dates but has the same outcome.

If you an empty date picker, and try entering (US format) 02/29/2000 (valid leap year) by typing the keys in this order (as you would do if typing manually) "2" => "2" => "9" => "2 => "0" => "0", validation will kick in and start correcting the date to the 28th Feb. You can see this in the vanilla demo on https://mui.com/x/react-date-pickers/date-picker/ using adapterDayJs.

Hitting the 3rd digit in the year might be the trigger for adapterDayJs, with my local version using date-fns it seems to trigger as soon as you hit the "2" in 2000 (but might be something else, it's wrapped in RHF etc so could be something else).

This seems to be linked to this issue https://github.com/mui/mui-x/issues/6716

**Comment by flaviendelangle** [comment]
@LukasTy could you double check? For me the problem no longer exists
