### ISSUE TITLE
Data grid action cell handleClickSave firing before processRowUpdate

### ISSUE THREAD

**Issue by Steve2724214** [mui/mui-x#8546]
### Order ID or Support key 💳 (optional)

62734

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

See this issue: https://github.com/mui/mui-x/issues/8404
Experiencing this on chrome

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 11.7.4
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.10.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: Not Found
    Firefox: 104.0.2
    Safari: 16.3
  npmPackages:
    @emotion/react: 11.10.6 => 11.10.6 
    @emotion/styled: 11.10.6 => 11.10.6 
    @mui/base: 5.0.0-alpha.124 => 5.0.0-alpha.124 
    @mui/icons-material: 5.11.16 => 5.11.16 
    @mui/lab: 5.0.0-alpha.125 => 5.0.0-alpha.125 
    @mui/material: 5.11.16 => 5.11.16 
    @mui/system: ^5.11.16 => 5.11.16 
    @mui/types:  7.2.3 
    @mui/x-data-grid: 6.0.4 => 6.0.4 
    @mui/x-data-grid-generator: 6.0.4 => 6.0.4 
    @mui/x-data-grid-pro: ^6.0.4 => 6.0.4 
    @mui/x-date-pickers: ^6.0.4 => 6.0.4 
    @mui/x-date-pickers-pro: ^6.0.4 => 6.0.4 
    @mui/x-license-pro: ^6.0.3 => 6.0.3 
    @types/react: 18.0.33 => 18.0.33 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.3 => 5.0.3
</details>

**Comment by MBilalShafi** [comment]
This one seems related to the mentioned issue. I'll close this one, you can follow up on the discussion there.
