### ISSUE TITLE
@mui/x-date-pickers Datepicker | not supports Date type as value

### ISSUE THREAD

**Issue by nospoon27** [mui/mui-x#8566]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example for (v6.0.3 not supports Date type):
https://codesandbox.io/s/mui-datepicker-date-type-unsupp-sci604

Link to live example for v5.0.20 (5.0.20 supports Date type):
https://codesandbox.io/s/mui-datepicker-5v-example-r7cr9b

### Current behavior 😯

I'm catching error: date.isBefore is not a function

### Expected behavior 🤔

It seems to me that the Date type should be supported and work correctly as in version 5

### Context 🔦

In my projects I use the Date type everywhere as default
I don't want to get tied up specifically with the dayjs library

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
<details>
  <summary><code>tsconfig.ts</code></summary>

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}

```
</details>

**Comment by LukasTy** [comment]
Just adding a comment if someone else also bumps into a similar issue.

[This migration section](https://mui.com/x/migration/migration-pickers-v5/#update-the-format-of-the-value-prop) should help bring some light as to what has changed and what you need to account for when migration.

- In v5 it was possible to have a misalignment between the adapter used and the format that you are passing the date in.
- In v6 we expect props (value, defaultValue, etc.) to be of the same type as the used adapter (i.e. `Date` for `AdapterDateFns`, `dayjs` for `AdapterDayjs`, etc.).
