### ISSUE TITLE
How can I apply custom styles to the grouping row header in MUI DataGrid?

### ISSUE THREAD

**Issue by john1625b** [mui/mui-x#8567]
### Order ID or Support key 💳 (optional)

61801

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I would like to apply custom styles to the grouping row header in MUI DataGrid. Specifically, I want to change the background colour, the cursor a pointer and make the text within the row blue to indicate it is clickable. 

However, when I looked through the [API](https://mui.com/x/api/data-grid/data-grid/#CSS), I only found the `.MuiDataGrid-row` class, which is applied to all rows rather than just the grouping row header. Is there a way to specifically target and style the grouping row header?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: Not Found
    Firefox: 106.0.5
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.113 
    @mui/core-downloads-tracker:  5.11.4 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.4 => 5.11.4 
    @mui/private-theming:  5.11.2 
    @mui/styled-engine:  5.11.0 
    @mui/system:  5.11.4 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.2 
    @mui/x-data-grid: ^5.17.21 => 5.17.21 
    @mui/x-data-grid-generator: ^5.17.20 => 5.17.20 
    @mui/x-data-grid-premium: ^6.0.4 => 6.0.4 
    @mui/x-data-grid-pro: ^5.17.20 => 5.17.20 
    @mui/x-license-pro:  5.17.12 
    @types/react: ^16.9.49 => 16.9.49 
    react: ^16.13.1 => 16.14.0 
    react-dom: ^16.13.1 => 16.14.0 
    typescript: ^4.9.4 => 4.9.4 

</details>

**Comment by yaredtsy** [comment]
hey @john1625b 
when you define your column you can set `headerClassName` and `cellClassName` props to set custom CSS for header and cells, you can read about it at [here](https://mui.com/x/react-data-grid/style/#styling-column-headers) for more information.

Demo: https://codesandbox.io/s/async-meadow-0ek4hf?file=/demo.tsx:811-825

**Comment by john1625b** [comment]
@yaredtsy 
is there any future plans to add a CSS selector specifically for the whole row of the grouping row header? 

Styling only the column of the grouping column doesn't fit my design requirements.

**Comment by yaredtsy** [comment]
you can use `getCellClassName` ,

```jsx
      getCellClassName={(props) => {
          if (props.rowNode.type == "group") return "cell";
        }}
```

**Comment by john1625b** [comment]
@yaredtsy This solved my issue. Thank you, closing as completed.
