### ISSUE TITLE
How to configure pagination on DataGrid Premium?

### ISSUE THREAD

**Issue by john1625b** [mui/mui-x#8568]
### Order ID or Support key 💳 (optional)

61801

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I tried using the `pageSizeOptions` prop and `paginationModel` within `initialState` on `DataGridPremium` but it's not working (the selected page size doesn't change):

https://codesandbox.io/s/winter-wind-01dtvj?file=/demo.tsx

However those exact same props and prop values do work on `DataGrid` (non premium):

https://codesandbox.io/s/determined-ben-xhyj16?file=/demo.tsx:501-516

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 13.2.1
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: Not Found
    Firefox: 106.0.5
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.113 
    @mui/core-downloads-tracker:  5.11.4 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.4 => 5.11.4 
    @mui/private-theming:  5.11.2 
    @mui/styled-engine:  5.11.0 
    @mui/system:  5.11.4 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.2 
    @mui/x-data-grid: ^5.17.21 => 5.17.21 
    @mui/x-data-grid-generator: ^5.17.20 => 5.17.20 
    @mui/x-data-grid-premium: ^6.0.4 => 6.0.4 
    @mui/x-data-grid-pro: ^5.17.20 => 5.17.20 
    @mui/x-license-pro:  5.17.12 
    @types/react: ^16.9.49 => 16.9.49 
    react: ^16.13.1 => 16.14.0 

```
</details>

**Comment by MBilalShafi** [comment]
As mentioned in the [documentation](https://mui.com/x/react-data-grid/pagination/)

```
The default pagination behavior depends on your plan.
- On the DataGrid, pagination is enabled by default and can't be disabled
- On the DataGridPro, pagination is disabled by default, use the pagination prop to enable it
```

So for Pro and Premium packages you have to pass `pagination` prop to enable it.

**Comment by john1625b** [comment]
@MBilalShafi That fixed my issue, thanks. 

Just a side question out of curiosity: why is it disabled by default on DataGridPro?

**Comment by MBilalShafi** [comment]
Glad it worked out. 🎉 

> why is it disabled by default on DataGridPro?

The `pagination` is kept opt-in because the Pro version of the Grid doesn't have a limit of 100 rows per page and data of fairly large data size could performantly be displayed on a single page thanks to advanced concepts like virtualization and lazy loading.

You can visualize 100,000 rows on a single page in this [Pro demo](https://mui.com/x/react-data-grid/#commercial-version).

**Comment by john1625b** [comment]
@MBilalShafi Ahh that makes sense. So the best practice is actually to disable pagination and have the rows load as you scroll. This provides a better UX since the user doesn't have to manually click "next" each time they get to the bottom. I will speak to my design/product team about switching to this patten. cheers

**Comment by PayalVerma21** [comment]
Hi @john1625b @MBilalShafi 

I am working on a project with MUI DataGrid.
I am using pagination with DataGridPro and the issue is **"If I am in second page of pagination and clicking on a button to go the next link then cancel or browser back button is pushing it back to pagination 1st page but I had clicked the button from second page"**

If have any answer to resolve this. That would be a great help.
Thank You!

**Comment by MBilalShafi** [comment]
> I am using pagination with DataGridPro and the issue is "If I am in second page of pagination and clicking on a button to go the next link then cancel or browser back button is pushing it back to pagination 1st page but I had clicked the button from second page"

Hey @PayalVerma21, kindly open a [new issue](https://github.com/mui/mui-x/issues/new/choose) and provide a **minimal** reproduction test case with the latest version. This would help a lot 👷.

A live example would be perfect. You can find examples and guides on how to find templates in our docs with which you can provide examples for your specific use-case: [Support - Bug reproduction](https://mui.com/x/introduction/support/#bug-reproductions).

Thank you! 🙇🏼
