### ISSUE TITLE
Export option in data table component - https://mui.com/x/react-data-grid/tree-data/ does not show names of child rows

### ISSUE THREAD

**Issue by indiadatahub** [mui/mui-x#8571]
### Order ID or Support key 💳 (optional)

52154

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We are using the data table component - https://mui.com/x/react-data-grid/tree-data/
The export is not showing the child rows. 

Below is the simulated example-

https://codesandbox.io/s/treepathdatagrid-vodr2n

In the above example, Capital & Reserve has two child components - capital and reserves but these are not shown on downloaded csv.  

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by AmandaCarvalho1989** [comment]
Hello! 

Is there any update about this issue?

Facing this problem using DataGridPremium as well, exporting CSV and Excel files :cry:

**Comment by Gaurav-IndiaDataHub** [comment]
Hi @AmandaCarvalho1989, 

We are not using DataGridPreminum but we are using DataGridPro. We did a workaround to solve this. What we did was when the export button is clicked it calls an API request to a Python (fast API) backend and that downloads a CSV of that table data.

**Comment by AmandaCarvalho1989** [comment]
Hi @Gaurav-IndiaDataHub, thanks for your reply! It's a good workaround! 

Searching yesterday about this problem, I found this other [github issue](https://github.com/mui/mui-x/issues/9344) and the suggested solution worked for me!

```jsx
const groupingColDef = {
    headerName: "Column grouping name",
    valueGetter: (params) =>
      params.rowNode.type === "group" || params.rowNode.type === "leaf"
        ? params.rowNode.groupingKey
        : undefined
  };
```
And then you just pass this prop (**groupingColDef**) to DataGrid (Premium or Pro)

```jsx
<DataGridPremium
  treeData
  rows={rows}
  columns={columns}
  getTreeDataPath={getTreeDataPath}
  groupingColDef={groupingColDef}
/>
```

Maybe it help's someone too :smile:
