### ISSUE TITLE
Components containing DataGridPro halt Jest test runner

### ISSUE THREAD

**Issue by dep** [mui/mui-x#8572]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Create a jest test that tests a component containing `DataGridPro`
2. Expect the test runner to complete
3. Test hangs indefinitely

### Current behavior 😯

Test hangs indefinitely

### Expected behavior 🤔

Test should finish

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Edge: Not Found
    Firefox: 109.0
    Safari: 16.3
```
</details>

### Order ID or Support key 💳 (optional)

[53240](https://store-wp.mui.com/my-account/view-order/53240/)

**Comment by dep** [comment]
I've tried downgrading `@testing-library/react` from `14.0` to `13.4.0`, and downgrading `@mui/x-data-grid-pro` from `16.x` to `5.17.24` with no luck

**Comment by dep** [comment]
I also tried reverting the codebase back to Thursday when my test suites were passing just fine.  I wonder if this is perhaps related to a licensing key issue?

**Comment by lounsbrough** [comment]
I can also confirm this issue. Will share any more details if/when I figure out what's going on.

**Comment by lounsbrough** [comment]
Reproduction repo added here to illustrate the issue: https://github.com/lounsbrough/muix-jest-babel-issue.

**Comment by dep** [comment]
Thanks for the extra detail @lounsbrough !

**Comment by dep** [comment]
Thanks @m4theushw I can confirm that your workaround works for me, though would prefer a formal patch to the library. At least this unblocks me for now.

**Comment by ricardasjak** [comment]
Same issue on non pro version DataGrid, when upgraded local Node from v16.x to v18.15.0. 

```
	window.getComputedStyle = function getComputedStyleMock() {
		return {
			getPropertyValue: () => {
				return undefined;
			},
		};
	};
```
seems to help

**Comment by agrauch** [comment]
I encountered this issue when updating to jest and jest-environment-jsdom 29.5.0.  The tests ran fine with 28.1.2.

@m4theushw's solution works for now.

**Comment by sagar1111212121** [comment]
I am also facing same issue from last 3 4 days. Tried everything I can think of to resolve this issue but wasn't able to do that. Tried above solution and it works fine now so that for the solution.

But is there any proper solution for this?

**Comment by dep** [comment]
I did see datagridpro just updated to `6.2.0`. I wonder if anyone has tried upgrading and if that helped?

**Comment by lounsbrough** [comment]
Here is the issue, at least for my case: https://github.com/dperini/nwsapi/issues/80

I don't believe this is caused by `DataGrid`. Check your package lock file and if you have `nwsapi` version `2.2.3` that is likely the issue.

**Comment by dep** [comment]
@lounsbrough 
I tried upgrading to `nwsapi` version `2.2.4` and it did not help

**Comment by lounsbrough** [comment]
@dep - Can you confirm that there are no references in your lock file to `2.2.3`? `package-lock.json` or `yarn.lock` or`pnpm-lock.yaml`

**Comment by lounsbrough** [comment]
What package manager do you use, npm? You can run `npm ls nwsapi` or `yarn why nwsapi` or `pnpm why nwsapi` and it should tell you anywhere that dependency is installed and at what version. Beyond that I don't know what the issue would be.

**Comment by dep** [comment]
@lounsbrough This is all I get with `npm ls nwsapi`

```
▶  npm ls nwsapi
repo@0.0.0
├─┬ jsdom@11.12.0 extraneous
│ └── nwsapi@2.2.4 deduped
```

**Comment by lounsbrough** [comment]
Yeah looks right to me, not sure what the issue is then, sorry.

**Comment by lounsbrough** [comment]
I guess one thing I see is that you're on an old version of jsdom.

Here's ours for example:

jest-environment-jsdom 29.5.0
└─┬ jsdom 20.0.3
  └── nwsapi 2.2.4
jsdom 21.1.1
└── nwsapi 2.2.4

**Comment by sagar1111212121** [comment]
Not similar, but after upgrading to latest **2.2.6,** JEST + RTL test cases started failing which were working just fine before sometime. Anyone else facing this issue?

**Comment by Matt-Tranzact** [comment]
Still not working with RTL + Jest
```
import React from 'react'
import { render } from '@testing-library/react'
import { DataGrid } from '@mui/x-data-grid'

describe('Table Component', () => {
  describe('Rendering', () => {
    it('should match snapshot', () => {
      expect(
        render(
          <DataGrid
            checkboxSelection
            columns={[]}
            pageSizeOptions={[5]}
            paginationModel={{ page: 1, pageSize: 5 }}
            rows={[]}
          />
        )
      ).toMatchSnapshot()
    })
  })
})
```

![image](https://github.com/mui/mui-x/assets/93609201/585f5d3a-5a49-46ae-8f1e-62f641a3e05b)

**Comment by dep** [comment]
Yes I am seeing an issue today:

```
 FAIL  src/components/App.test.js
  ● renders the App component
    SyntaxError: Illegal break statement
        at Function (<anonymous>)

      10 |
      11 | test("renders the App component", () => {
    > 12 |   render(<App />);
         |         ^
      13 |   expect(
      14 |     screen.queryByText("No data has been loaded.", { exact: false })
      15 |   ).toBeInTheDocument();

      at compile (node_modules/jest-environment-jsdom/node_modules/nwsapi/src/nwsapi.js:760:17)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
      at ../../../../node_modules/@mui/x-data-grid/node/hooks/features/dimensions/useGridDimensions.js:165:31
      at Proxy.computeSizeAndPublishResizeEvent (../../../../node_modules/@mui/x-data-grid/node/hooks/utils/useGridApiMethod.js:22:20)
      at ../../../../node_modules/@mui/x-data-grid/node/components/base/GridBody.js:52:20
```

**Comment by dep** [comment]
Related: https://github.com/dperini/nwsapi/issues/90
