### ISSUE TITLE
[DataGrid] Container with 100% width and rows overflowing its height, shows jumpy behavior

### ISSUE THREAD

**Issue by belenmartinez08** [mui/mui-x#8574]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/mui-x-issue-template-forked-e2m06l?file=/src/App.tsx

### Current behavior 😯

DataGrid jumps horizontally

### Expected behavior 🤔

DataGrid should show an horizontal scroll and don't jump
Exactly the same code worked fine with DataGrid v5

### Context 🔦

The same code worked fine with DataGrid v5

### Your environment 🌎

  Binaries:                                                  
    Node: 18.13.0 
    Yarn: 1.22.19
    npm: 6.14.11
  Browsers:
    Chrome: 112.0.5615.50
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.34)
  npmPackages:
    @emotion/react:  11.10.5 
    @emotion/styled:  11.10.5 
    @mui/base:  5.0.0-alpha.123 
    @mui/core-downloads-tracker:  5.11.15 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/material: ^5.11.15 => 5.11.15 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11                             
    @mui/styles: ^5.11.13 => 5.11.13                         
    @mui/system:  5.11.15                                    
    @mui/types:  7.2.3                                       
    @mui/utils:  5.11.13                                     
    @mui/x-data-grid: ^6.1.0 => 6.1.0
    @mui/x-data-grid-premium: ^6.1.0 => 6.1.0
    @mui/x-data-grid-pro:  6.1.0
    @mui/x-date-pickers: ^6.1.0 => 6.1.0
    @mui/x-license-pro:  6.0.4
    @types/react:  18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0

**Comment by cherniavskii** [comment]
Thanks, @belenmartinez08 
I've created this simplified reproduction example based on the one that you provided: https://codesandbox.io/s/mui-x-issue-template-forked-u5htr1?file=/src/App.tsx

**Comment by belenmartinez08** [comment]
Thank you!

**Comment by sjungling** [comment]
Hi @cherniavskii, 👋  

I believe this is the same issue I reported via https://github.com/mui/mui-x/issues/8182 which we thought had been resolved.

I finally got around to testing your fix with our upgrade branch (apologies for the lag in testing, it's been hectic few weeks) and was still encountering this behavior.

I created a new sandbox to better represent the context in which we're experiencing this issue. https://codesandbox.io/s/czgh8u?file=/demo.tsx

Seems to be present in 6.2.0. Oddly, I can readily replicate by expand/collapsing the drawer on Chrome / Edge, but Safari and Firefox seem to not be susceptible to this issue.

**Comment by cherniavskii** [comment]
@belenmartinez08
I cannot reproduce the issue anymore with the latest version of the data grid (v6.2.1)
Can you confirm it's fixed?
Here is your demo using data grid v6.2.1: https://codesandbox.io/s/mui-x-issue-template-forked-0niitm?file=/src/App.tsx

**Comment by cherniavskii** [comment]
@sjungling I cannot see any jumpy behavior in your reproduction example.
Can you reproduce it with v6.2.1?

**Comment by sjungling** [comment]
> @sjungling I cannot see any jumpy behavior in your reproduction example. Can you reproduce it with v6.2.1?

Ah, version changed on my sandbox code. Yes, it appears to be resolved in `6.2.1`

Broken (6.2.0) -> https://codesandbox.io/s/mui-x-issue-template-forked-ks3u3d?file=/package.json
Fixed (6.2.1) -> https://codesandbox.io/s/mui-x-issue-template-forked-0niitm?file=/package.json

I'm guessing [this changeset](https://github.com/mui/mui-x/pull/8091) was what lead to the resolution?

**Comment by belenmartinez08** [comment]
@cherniavskii
Yes, I've tried it with version 6.3.0 and I can't reproduce it anymore. I'm closing.

Thank you again!
