### ISSUE TITLE
[pickers] DatePicker not accepting html name attribute

### ISSUE THREAD

**Issue by OZZlE** [mui/mui-x#8595]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

	import { DatePicker } from '@mui/x-date-pickers/DatePicker';

	function Page() {
	  return (
		<form method="post">
		  <DatePicker name="lorem" />
                  <button type="submit">Send</button>
		</form>
	  )
	}

### Current behavior 😯

The name attribute is not used/accepted so it doesn't do anything

### Expected behavior 🤔

At least under the hood there should be a `<input name="lorem" value="[stringified-date-format-as-an-option]" />`

so you can pick up the date form the form submission, see: 

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.208
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.69)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.124
    @mui/core-downloads-tracker:  5.11.16
    @mui/material: ^5.11.16 => 5.11.16
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.16
    @mui/system:  5.11.16
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @types/react: 18.0.29 => 18.0.29
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.0.2 => 5.0.2
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

You can pass custom props directly to the textfield as follow:

```tsx
<DatePicker slotProps={{ textField: { name: 'test' }}} />
```

I don't think we should pass the name to the field out of the box because the field can have several HTML input or non.

**Comment by OZZlE** [comment]
Great! Perhaps it could be mentioned here? https://mui.com/x/react-date-pickers/date-picker/
