### ISSUE TITLE
[question] Why is it only possible to sort by columns that are configured?

### ISSUE THREAD

**Issue by litera** [mui/mui-x#8599]
### The problem in depth 🔍

If you have a model type i.e.

```
interface Model {
  id: number;
  created: Date;
  name: string;
  ...
}
```

I would like to order my data according to the `created` property, but **I don't want to configure this property as a column**(and then hiding it via the `initialState.columns.columnVisibilityModel` or the matching prop).

Why is it not possible to sort by grid row data that is not configured as a column, since grid row data has the value just fine?

If this is not planned for implementation it would be great **if this was clearly stated in the documentation** on the [Sorting page](https://mui.com/x/react-data-grid/sorting/), that one can only sort by configured columns (this is completely understandable when a user clicks within the UI, because they can only manipulate visible columns, but not clear when a developer sets sorting order programmatically using the sort model).

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
This is irrelevant of the browser or environement.
```
</details>

**Comment by litera** [comment]
@m4theushw Even if we configure a column, we don't provide the comparator manually unless we want something specific. Why would sorting by a non-configured property be any different? You'd check its type and use the default for the type. If one wanted a different comparator, then they would define the column.

**Comment by ziflex** [comment]
I'm facing the same issue. The limitation makes sense (at some degree) for the client-side sorting mode, but what about when it's in the server mode? The initial/default sorting is done against a non-column property.

**Comment by romgrk** [comment]
@ziflex Have you tried sorting your rows according to your needs before passing them to the grid?

@mui/xgrid This issue is in the backlog but I'm not sure what's the expected resolution. Thoughts?

**Comment by cherniavskii** [comment]
> Have you tried sorting your rows according to your needs before passing them to the grid?

Yes, this is the recommended approach.

> This issue is in the backlog but I'm not sure what's the expected resolution

I don't see any actions for us to take here, I think we can close the issue.
