### ISSUE TITLE
 [data grid pro] Updating `columns` and `columnGroupingModel` at once throws error

### ISSUE THREAD

**Issue by Gabriel-Silverio-96** [mui/mui-x#8602]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

When using a generator to dynamically create the columnGroupingModel, this exception is thrown

![issue](https://user-images.githubusercontent.com/53228013/231549997-78b84905-0d9a-4f01-a6a7-b5c881600a6d.PNG)

### Current behavior 😯

Link to live example: https://codesandbox.io/s/data-grid-pro-version-6-1-0-bp39li?file=/demo.js

Versions - in these versions the problem appears
@mui/x-data-grid-pro - 6.1.0
@mui/x-license-pro - 6.1.0

**Suggestion:**
In the file [useGridColumnHeaders.tsx ](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx)

Adding an optional chaining to `firstVisibleColumnIndex`, `hiddenGroupColumns`, and `leftOverflow` solves the problem

```js
const firstVisibleColumnIndex = visibleColumnGroupHeader[0]?.columnFields.indexOf(firstColumnFieldToRender);

const hiddenGroupColumns = visibleColumnGroupHeader[0]?.columnFields.slice(0, firstVisibleColumnIndex);

const leftOverflow = hiddenGroupColumns?.reduce((acc, field) => {
  const column = apiRef.current.getColumn(field);
  return acc + (column.computedWidth ?? 0);
}, 0);
```

### Expected behavior 🤔

Link to live example: https://codesandbox.io/s/data-grid-pro-version-5-17-25-srizjm?file=/demo.js

Versions - in these versions the problem does not appear
@mui/x-data-grid-pro - 5.17.25
@mui/x-license-pro - 5.17.12

### Order ID or Support key 💳 (optional)
58931

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
```
System:<br>
    OS: Linux 5.15 Linux Mint 20.2 (Uma)<br>
  Binaries:<br>
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node<br>
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn<br>
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm<br>
  Browsers:<br>
    Chrome: 109.0.5414.74<br>
    Firefox: 89.0.2<br>
  npmPackages:<br>
    @emotion/react:  11.10.4 <br>
    @emotion/styled:  11.10.4 <br>
    @mui/base:  5.0.0-alpha.98 <br>
    @mui/core-downloads-tracker:  5.10.6 <br>
    @mui/lab:  5.0.0-alpha.100 <br>
    @mui/material:  5.10.6 <br>
    @mui/private-theming:  5.10.6 <br>
    @mui/styled-engine:  5.10.6 <br>
    @mui/styles:  5.10.6 <br>
    @mui/system:  5.10.6 <br>
    @mui/types:  7.2.0 <br>
    @mui/utils:  5.10.6 <br>
    @mui/x-data-grid:  6.1.0<br> 
    @mui/x-data-grid-pro:  6.1.0 <br>
    @mui/x-date-pickers:  5.0.3 <br>
    @mui/x-license-pro: ^6.0.3 => 6.0.3 <br>
    @types/react:  17.0.26 <br>
    react: ^17.0.2 => 17.0.2 <br>
    react-dom: ^17.0.2 => 17.0.2<br> 
    styled-components:  5.3.1 <br>
    typescript:  4.7.4 <br>
```
</details>

**Comment by cherniavskii** [comment]
The regression was introduced in `6.0.0-alpha.4`, probably in https://github.com/mui/mui-x/pull/5947

**Comment by Gabriel-Silverio-96** [comment]
Hey @cherniavskii, thanks for update the labels.

Here is our order id if it helps something: #58931

We are migrating our DataGrid components to v6 but because we have this issue we need to wait the fix before merge our migration.

Thanks again.
