### ISSUE TITLE
[data grid] Cannot add data attributes to data-tables, their rows, page buttons, etc

### ISSUE THREAD

**Issue by djtobia** [mui/mui-x#8605]
Adding a data attribute to a DataGrid does not render on the DOM. On top of that, there is no way to add data attributes to the rows of the table, or any of the interactable elements generated for the table. Data attributes are often used as identifiers for automation, and I am sure I am not the only one that could use it. This issue was already closed, but doesn't seem to have been fixed? mui/material-ui#5711 
```typescript
<DataGrid 
    rows={rows}
    columns={columns}
    pageSize={5}
    rowsPerPageOptions={[5]}
    checkboxSelection
    data-whatever="this does not render"
/>
```

**Comment by djtobia** [comment]
> The solution for this is the item 3 from [#6008 (comment)](https://github.com/mui/mui-x/issues/6008#issuecomment-1240051359)
> 
> Do you want to submit a PR?

So I have to break down my DataGrid to its separate pieces? Doesn't that kind of defeat the point?

**Comment by romgrk** [comment]
I'll pick up this ticket.

@djtobia Beyond rows & page buttons, are there any more places where you see data attributes being useful?

**Comment by djtobia** [comment]
> I'll pick up this ticket.
> 
> @djtobia Beyond rows & page buttons, are there any more places where you see data attributes being useful?

The column header filter button, and the drop-down associated with them. But that's all I can think of at this moment.

**Comment by romgrk** [comment]
Got it. Anyone has a favourite API to expose data-attributes on subcomponents?

**Comment by romgrk** [comment]
@djtobia For the row data-attributes, do you have an example use-case in mind? We already have `data-id` and `data-rowindex` by default, I'm wondering if we really need any other custom data attributes.

If we do, I was thinking about adding something like `getRowProps: (row: GridRowPropsParam) => Record<string, any>` as a new prop on the `DataGrid` component.

**Comment by romgrk** [comment]
I've opened the PR linked above for this issue.

AFAICT, because we already have identifying data attributes on rows, and we have `slotProps` for the other subcomponents, the only missing thing is data attributes on the root element.

**Comment by samanthajuniper** [comment]
Thank you for raising this issue--the support for data attributes is critical to my organization's implementation of the data grid, and we would really benefit from this PR going through as soon as possible!

**Comment by cjenkscybercom** [comment]
We also need this feature to be able to use libraries such as react data tour that operate on-top-of the DOM by their nature: https://www.npmjs.com/package/reactour
