### ISSUE TITLE
[data grid pro] DataGrid rendered in detail panel content affected by column resize of parent grid

### ISSUE THREAD

**Issue by gidztech** [mui/mui-x#8613]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/bitter-http-5oj1iq?file=/demo.tsx

### Current behavior 😯

My project involves rendering a basic DataGrid inside the detail panel content of a row of the parent grid. However, when I resize the parent grid columns, it's moving the columns data in the detail panel grid. The column headers aren't affected, just the row cells. These are completely unrelated tables, so it's surprising that they are interacting with one another.

I modified a MUI Codesandbox to demonstrate the issue:

![nested-data-grid](https://user-images.githubusercontent.com/15942538/231821592-61c964c1-650e-45c2-88a9-660d45038e77.png)

https://codesandbox.io/s/bitter-http-5oj1iq?file=/demo.tsx

If I collapse the detail panel and re-expand it, the columns in the detail panel grid are reset to the correct position. I suspect that the MUI resizing hook is globally looking at DOM elements instead of it being constrained by a particular context. 

### Expected behavior 🤔

I would expect the 2 grids to not interact with one another, in this case column sizing, but this could affect other interactions.

### Context 🔦

I'm trying to render a basic DataGrid inside the detail panel content of a row of the parent grid.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: Not Found
    npm: 9.1.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.124 
    @mui/core-downloads-tracker:  5.11.16 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/material: ^5.12.0 => 5.11.16 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.16 
    @mui/system:  5.11.16 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-data-grid:  6.0.4 
    @mui/x-data-grid-pro: ^6.1.0 => 6.0.4 
    @mui/x-license-pro:  6.0.3 
    @types/react: ^18.0.16 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.7.4 => 4.9.5 
```
</details>

**Comment by cherniavskii** [comment]
I believe this was fixed by https://github.com/mui/mui-x/pull/9670
