### ISSUE TITLE
Is there a way to restrict width of the table?

### ISSUE THREAD

**Issue by zainfarpoint** [mui/mui-x#8615]
### Order ID or Support key 💳 (optional)

62910

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I understand that the width is intrinsic, but is there any way to restrict width (via CSS for example) such that overall table width doesn't extend beyond the viewport (without hardcoding width) on resizing columns?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Yes, setting `width: 100%` on the grid container should do the job - see https://codesandbox.io/s/j884p1?file=/demo.tsx
