### ISSUE TITLE
[pickers] `DateField` should not have today's time set by default when initializing a date

### ISSUE THREAD

**Issue by exequiel22** [mui/mui-x#8616]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-template-forked-tffojd?file=/src/App.tsx

Steps:
1. Select the date 04/13/2023 from the calendar and see that the date does not contain a time.
2. Refresh the page and enter the date 04/13/2023 in the input by typing with the keyboard and we see that now it includes time.

### Current behavior 😯

For the same date we have different behaviors according to how it is selected

### Expected behavior 🤔

The resulting date is expected to be the same whether typed by keyboard or selected by calendar.

### Your environment 🌎

Browser: Google Chrome
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: Not Found
    npm: 8.19.4 - ~/projects/../node_modules/.bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.123 
    @mui/core-downloads-tracker:  5.11.15 
    @mui/material: ^5.11.15 => 5.11.15 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.15 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-date-pickers: ^6.1.0 => 6.1.0 
    @types/react:  17.0.54 
    react:  16.14.0 
    react-dom:  16.14.0 
    typescript: ^5.0.2 => 5.0.2 
```
</details>

**Comment by LukasTy** [comment]
Thank you for opening this issue! 🙏 
There indeed is a difference in which time is being used when entering manually and selecting a date in the calendar.
We'll need to unify this inconsistency.
Which one do you think would be the more correct behavior? 🤔 

By the way, in your codesandbox you have `dayjs(null)` as an initial value—that's incorrect as also denoted by the TextField in an error state, an empty value should just simply be a `null`. 😉

**Comment by exequiel22** [comment]
> Thank you for opening this issue! 🙏 There indeed is a difference in which time is being used when entering manually and selecting a date in the calendar. We'll need to unify this inconsistency. Which one do you think would be the more correct behavior? 🤔
> 
> By the way, in your codesandbox you have `dayjs(null)` as an initial value—that's incorrect as also denoted by the TextField in an error state, an empty value should just simply be a `null`. 😉

Thanks for your answer, @LukasTy 

In my opinion, the correct behavior is that if the date is selected from the calendar or if the date is selected by entering the value by keyboard, the value of the date in this case the value of Dayjs should be the same.


I will correct the error you mentioned in the codesandox. Thanks

**Comment by LukasTy** [comment]
> In my opinion, the correct behavior is that if the date is selected from the calendar or if the date is selected by entering the value by keyboard, the value of the date in this case the value of Dayjs should be the same.

Agreed, the idea is to unify the behaviors, but I was clarifying which of the following behaviors would seem more correct:
- always set time to midnight (start of the day);
- always set time to `current` (whatever time was then the component was rendered);

**Comment by exequiel22** [comment]
> > In my opinion, the correct behavior is that if the date is selected from the calendar or if the date is selected by entering the value by keyboard, the value of the date in this case the value of Dayjs should be the same.
> 
> Agreed, the idea is to unify the behaviors, but I was clarifying which of the following behaviors would seem more correct:
> 
> * always set time to midnight (start of the day);
> * always set time to `current` (whatever time was then the component was rendered);

I'm sorry, I didn't quite understand that.

In my opinion, the time should be set to zero when the format does not include the time. In case the format does include the time it may be beneficial to set the current time by default.
