### ISSUE TITLE
[question]  Help with building a autocomplete component

### ISSUE THREAD

**Issue by NareshMurthy** [mui/mui-x#8623]
### Order ID or Support key 💳 (optional)

56539

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am trying to use the Autocomplete component something similar to this [checkbox](https://mui.com/material-ui/react-autocomplete/#checkboxes), but has a tree view (parent-child) checkboxes
Is there an example around this? 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @NareshMurthy 
I don't recall seeing examples like this.
But you might find `useAutocomplete` hook useful for building one: https://mui.com/material-ui/react-autocomplete/#useautocomplete

**Comment by NareshMurthy** [comment]
@cherniavskii I did try the useAutoComplete hook, but no luck. is there a component something like  
this https://www.npmjs.com/package/react-dropdown-tree-select ?

**Comment by cherniavskii** [comment]
I just found this feature request - https://github.com/mui/mui-x/issues/514
Feel free to upvote it :)
Also, you might find this comment useful: https://github.com/mui/mui-x/issues/514#issuecomment-1141765715

**Comment by NareshMurthy** [comment]
Thanks
