### ISSUE TITLE
[data grid] Children of role="grid" aren't allowed

### ISSUE THREAD

**Issue by estrizhiver** [mui/mui-x#8624]
### Order ID or Support key 💳 (optional)

8005

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

If filters are siblings of the grid, no such problem exists, and the filters/grid pass accessibility.

Here is the error:
<img width="1508" alt="process-unity" src="https://user-images.githubusercontent.com/7647075/232059955-832665e8-34c6-4cb3-8348-278fafdafd1b.png">

You can also reproduce on https://mui.com/x/react-data-grid/filtering/

![233083287-d47f717d-cdcb-4319-995e-82ede58e2d41](https://github.com/mui/mui-x/assets/3165635/3225e5d1-dbb9-45f9-8543-6d3885852e04)

This is due to filters (and pagination in some cases) being children of role="grid", which isn't allowed. When they are siblings of the grid, no errors exist.

### Zendesk ticket

- https://mui.zendesk.com/agent/tickets/8307

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @estrizhiver 
Is this issue reproducible with the default filtering panel?
It seems like the "Related notes" point to the custom part of the interface.

**Comment by estrizhiver** [comment]
Thanks for the reply. The issue is reproducible even from the mui site: https://mui.com/x/react-data-grid/filtering/Best,EddieSent from my iPhoneOn Apr 14, 2023, at 3:49 PM, Andrew Cherniavskii ***@***.***> wrote:﻿
Hi @estrizhiver
Is this issue reproducible with the default filtering panel?
It seems like the "Related notes" point to the custom part of the interface.

**Comment by cherniavskii** [comment]
We can start by adding a test case to cover this issue, similarly to https://github.com/mui/mui-x/blob/c098a8007fe11e14450da1e883ed792e1f31dbe0/packages/grid/x-data-grid-pro/src/tests/accessibility.DataGridPro.test.tsx#L17

**Comment by oliviertassinari** [comment]
@cherniavskii Would it make sense to do?

```diff
diff --git a/packages/grid/x-data-grid-generator/src/hooks/useDemoData.ts b/packages/grid/x-data-grid-generator/src/hooks/useDemoData.ts
index 677ff89be..0d2760375 100644
--- a/packages/grid/x-data-grid-generator/src/hooks/useDemoData.ts
+++ b/packages/grid/x-data-grid-generator/src/hooks/useDemoData.ts
@@ -1,5 +1,6 @@
 import * as React from 'react';
 import LRUCache from 'lru-cache';
+import { GridExperimentalFeatures } from '@mui/x-data-grid/internals';
 import { GridColumnVisibilityModel } from '@mui/x-data-grid-premium';
 import { GridDemoData, getRealGridData } from '../services/real-data-service';
 import { getCommodityColumns } from '../columns/commodities.columns';
@@ -22,6 +23,7 @@ export type DemoDataReturnType = {
   loading: boolean;
   setRowLength: (count: number) => void;
   loadNewData: () => void;
+  experimentalFeatures: Partial<GridExperimentalFeatures>;
 };

 type DataSet = 'Commodity' | 'Employee';
@@ -213,5 +215,6 @@ export const useDemoData = (options: UseDemoDataOptions): DemoDataReturnType =>
     loadNewData: () => {
       setIndex((oldIndex) => oldIndex + 1);
     },
+    experimentalFeatures: { ariaV7: true },
   };
 };
```

This would fix more of the demos of the docs, and https://pagespeed.web.dev/analysis/https-mui-com-x/3to8uohj1f?form_factor=desktop.

**Comment by cherniavskii** [comment]
@oliviertassinari Interesting idea, my only doubt is that it's implicit and might be confusing for developers to see different layout/ARIA attributes in the docs compared to their environment.
I'll open a PR

**Comment by oliviertassinari** [comment]
True, but everyone should use these values, it's buggy without.

Otherwise, I like the idea to change the default value in a minor, selling it as an a11y bug fix 😁, and then in the next major, to remove the option to opt out.
