### ISSUE TITLE
[data grid] Updating grouped rows results in infinite loop

### ISSUE THREAD

**Issue by gavbrennan** [mui/mui-x#8626]
### Order ID or Support key 💳 (optional)

50374

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I update a grid in high-frequency, using the api call apiRef.current.updateRows(rowsToUpdate) and this works fine.  However, when I turn on row grouping, i dont see any of the aggregated values in the grid updating, nor the values on the leaf nodes.  I've tried calling apiRef.current.forceUpdate() to see if that produced a recalculation of the aggregated node values, but it does not.  Please advise, in v5 this worked.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Windows 10 10.0.22624
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 24.58 GB / 63.89 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Cargo: 1.65.0 - ~\.cargo\bin\cargo.EXE
    pip3: 21.2.3 - C:\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.29.2.
  Virtualization:
    Docker: 20.10.17 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.16299.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    VSCode: 1.77.3 - C:\Users\gavbr\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 16.11.33130.400 (Visual Studio Community 2019), 17.5.33424.131 (Visual Studio Enterprise 2022)
  Languages:
    Bash: 5.0.17 - C:\Windows\system32\bash.EXE
    Python: 3.10.0
    Rust: 1.65.0
  Browsers:
    Edge: Spartan (44.22621.1610.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.22621.1

</details>

**Comment by cherniavskii** [comment]
Hi @gavbrennan 
Can you provide a reproduction example for this issue? Thanks!

**Comment by gavbrennan** [comment]
I'm struggling to create an example to demonstrate the issue, but it seems that my code works fine for a single level of row grouping, but upon adding a second grouping parameter the error below is spammed into the logs:

ils.js:85 Uncaught RangeError: Maximum call stack size exceeded
    at removeNodeFromTree (utils.js:85:1)
    at removeNodeAndCleanParent (removeDataRowFromTree.js:9:1)
    at removeNodeAndCleanParent (removeDataRowFromTree.js:26:1)
    at removeNodeAndCleanParent (removeDataRowFromTree.js:26:1)
    at removeNodeAndCleanParent (removeDataRowFromTree.js:26:1)
    at removeNodeAndCleanParent (removeDataRowFromTree.js:26:1)
    at removeNodeAndCleanParent (removeDataRowFromTree.js:26:1)
    at removeNodeAndCleanParent (removeDataRowFromTree.js:26:1)

**Comment by cherniavskii** [comment]
Thanks, @gavbrennan!
I can reproduce the issue.
Here's a simplified version of your demo: https://codesandbox.io/s/competent-neumann-kx9weo
It works fine in v5: https://codesandbox.io/s/elegant-currying-7sov77

We will investigate it.
