### ISSUE TITLE
[test] Replace `componentsProps` with `slotProps`

### ISSUE THREAD

**Issue by m4theushw** [mui/mui-x#8629]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The test files are using the deprecated `componentsProps` instead of `slotProps`.

https://github.com/mui/mui-x/blob/0acb52fded2ac70f2d86752c0f5f0abaa638ad00/packages/grid/x-data-grid/src/tests/components.DataGrid.test.tsx#L52-L60

**Comment by MBilalShafi** [comment]
Done as part of #10911
