### ISSUE TITLE
[pickers] docs `DateCalendar` import issue

### ISSUE THREAD

**Issue by Adnane-Louardi-dev** [mui/mui-x#8630]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-date-pickers/date-calendar/

### Kind of issue

Broken demonstration

### Issue description

when I import DateCalendar component this error pops up for no reason:

> Can't resolve '@mui/x-date-pickers/DateCalendar' 

but after many tries I figure out that I suppose to do as above:

> import { CalendarPicker } from "@mui/x-date-pickers/CalendarPicker";

but the probleme is the documentation implements the wrong code.

**Comment by LukasTy** [comment]
Could you provide a screenshot of the problem/mistake you see in the docs with the documentation version visible in the corner?
It could be a problem of docs caching and you might be on an old version of documentation (the current is v6.2.0).

If `import { CalendarPicker } from "@mui/x-date-pickers/CalendarPicker";` has worked for you, then you are probably on the legacy (v5.x) version and you should jump to https://v5.mui.com/x/react-date-pickers/getting-started/ to check correct documentation. 👌
