### ISSUE TITLE
[docs] Demo AdapterHijri crashes

### ISSUE THREAD

**Issue by UsefSalim** [mui/mui-x#8650]
- [x] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20AdapterHijri%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-date-pickers/calendar-systems/
2. ??
3. demo *AdapterHijri* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.2.0  |
| Netlify deploy | https://6438f3f365517700086de206--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 |

**Comment by UsefSalim** [comment]
https://user-images.githubusercontent.com/76592466/233511758-654d698f-7fb3-4d8a-95fa-f10a7bcef9b5.mov

**Comment by alexfauquette** [comment]
Thanks for the reproduction. It seems the date library does not accept an infinite range of dates. It can be fixed with following props

```jsx
minDate={moment(new Date(1938, 0, 1))}
maxDate={moment(new Date(2075, 0, 1))}
```
