### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by tomwhale** [mui/mui-x#8655]
### Order ID or Support key 💳 (optional)

57717

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We use both CSV and Excel export. It sees that the CSV export uses the ValueFormatter to displays values that are exported in the CSV. However, the Excel does not, and outputs an object instead. Is there anything we can do to prevent this happening?

An example of a cell being:

```
{"amount":5000000000,"currency":"GBP"}
```

Whereas this should be: £50000000

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: macOS 13.2.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.54
    Firefox: 111.0.1
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.112
    @mui/core-downloads-tracker:  5.11.3
    @mui/icons-material: ^5.11.0 => 5.11.0
    @mui/lab: ^5.0.0-alpha.66 => 5.0.0-alpha.114
    @mui/material: ^5.0.4 => 5.11.3
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.2
    @mui/types:  7.2.3
    @mui/utils:  5.11.2
    @mui/x-data-grid:  5.17.18
    @mui/x-data-grid-premium: ^5.17.18 => 5.17.18
    @mui/x-data-grid-pro:  5.17.18
    @mui/x-date-pickers: ^5.0.13 => 5.0.13
    @mui/x-license-pro:  5.17.12
    @types/react: 17.0.2 => 17.0.2
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components:  5.3.3
    typescript: ^4.7.4 => 4.7.4
```
</details>

**Comment by MBilalShafi** [comment]
@tomwhale Thanks for reporting, the issue has already been reported [here](https://github.com/mui/mui-x/issues/6664), and a few possible fixes and discussions are made there.

I am closing this one to avoid duplication, please check out the linked issue feel free to follow-up the discussion there.
