### ISSUE TITLE
[DataGridPro] `onColumnWidthChange` doesn't get fired on touch devices on column resize

### ISSUE THREAD

**Issue by e12879** [mui/mui-x#8658]
### Order ID or Support key 💳 (optional)

58043

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am using mui/x-data-grid-pro.
I am using onColumnWidthChange of DataGridPro API,
onColumnWidthChange is not called on tablets.

onColumnWidthChange is called correctly on PC.
navigator.userAgent and navigator.userAgentData.platform are used for tablet device detection.

Does the DataGridPro API's onColumnWidthChange not work on tablets?
Please let me know if there is a way to make onColumnWidthChange work on tablets.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by e12879** [comment]
@MBilalShafi 
thank you for your reply.
My environment is as follows.

■npx @mui/envinfo
  System:
   OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)

■ChromeDevTools
　　Chrome-Android Tablet
　　Safari-iPad iOS 13.2

■Actual machine environment in use
　　Ipad 6 iOS：15.7.1
　　iPad Pro iOS：16.3.1
　　Galaxy Tab A8：Android11

**Comment by MBilalShafi** [comment]
Thanks for providing the additional information, actually, on mobile devices the event fired on resize is `touchStart` and `touchEnd` instead of `mouseDown` and `mouseUp`, and they were not properly emitting the `columnWidthChange` event. I have raised a [PR](https://github.com/mui/mui-x/pull/8669) which should fix the issue.
