### ISSUE TITLE
[pickers] Controlled DatePicker resets to first value set on popover close.

### ISSUE THREAD

**Issue by mike-klem** [mui/mui-x#8663]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/romantic-spence-3l6fvs?file=/demo.tsx

Steps:
1. Load the example. Notice the date picker has a date populated. It is a controlled input.
2. Click the calendar icon to open the date picker popover, but **do not select a date**
3. Click away from the popover to close it.
4. Notice that the date is cleared.

### Current behavior 😯

This demo creates a controlled input with `null` as it's initial value. When the component mounts, setState is called to set a date value. It seems like the DatePicker memoizes the first value it received (null). If the picker is opened, then closed without selecting a value, the picker is reset to null, instead of the `value` prop that is being passed in.

### Expected behavior 🤔

If I have a fully controlled input, I would expect it to always display the value being passed in as the `value` prop.

### Context 🔦

I'm using the DatePicker as a controlled input in a form. When we initially display the form, we don't have all the data to populate it, so we initialize the form inputs with empty values. In the case of the DatePicker, that is `null`. Once the data is fetched, the DatePicker's value prop will be updated to show the currently selected date. If the user opens the popover, then closes it again without selecting a value, the date value gets cleared.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Edge: Not Found
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.5
    @emotion/styled: ^11.10.4 => 11.10.5
    @mui/base: ^5.0.0-alpha.103 => 5.0.0-alpha.104
    @mui/core-downloads-tracker:  5.10.12
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.11 => 5.10.12
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system:  5.10.12
    @mui/types:  7.2.0
    @mui/utils:  5.10.9
    @mui/x-date-pickers:  6.2.0
    @mui/x-date-pickers-pro: ^6.2.0 => 6.2.0
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react: ^18.0.24 => 18.0.24
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```
</details>

### Order ID or Support key 💳 (optional)

16787

**Comment by alexfauquette** [comment]
Indeed, the problem comes from the management of controlled values. The update of the internal state does not take into account this scenario.

Such that when you open and close the view, the internal state is still such as the last committed value is `null` so it clears the field.

Trying a fix at #8674
