### ISSUE TITLE
[data grid] Table pagination arrows are reversed in RTL

### ISSUE THREAD

**Issue by OmerMessing** [mui/mui-x#8665]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Make use of Data Grid as a component in your React application and install the required libraries.
2. Add the necessary adjustments to support RTL and language localization.
3. Add dir="rtl" to the HTML tag

### Current behavior 😯

![datagrid example](https://user-images.githubusercontent.com/76533808/229794673-8d7ef2dc-d2e0-4ad2-93d9-6d4005f40f56.png)

### Expected behavior 🤔

![correct example](https://user-images.githubusercontent.com/76533808/229794855-5362a166-6f97-4f1d-8e90-b7d512c906d9.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

I use Chrome browser.

```
  System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.119 
    @mui/core-downloads-tracker:  5.11.12 
    @mui/icons-material: ^5.10.15 => 5.10.15 
    @mui/lab: ^5.0.0-alpha.110 => 5.0.0-alpha.110 
    @mui/material: ^5.11.12 => 5.11.12 
    @mui/private-theming:  5.11.12 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.12 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.12 
    @mui/x-data-grid: ^6.0.1 => 6.0.1 
    @mui/x-data-grid-generator: ^5.17.13 => 5.17.13 
    @mui/x-data-grid-premium:  5.17.13 
    @mui/x-data-grid-pro:  5.17.13 
    @mui/x-date-pickers: ^5.0.9 => 5.0.9 
    @mui/x-license-pro:  5.17.12 
    @types/react:  18.0.25 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
```
</details>

**Comment by oliviertassinari** [comment]
So, it's a support question. Developers can solve this by following https://mui.com/material-ui/guides/right-to-left/.

Now, I noticed something that we forgot when we closed #230: https://mui.com/x/react-data-grid/localization/#rtl-support

<img width="818" alt="Screenshot 2023-04-18 at 23 44 30" src="https://user-images.githubusercontent.com/3165635/232912051-29998fba-f7a6-47fa-a7ee-fdd64f6ef862.png">

This is solved now (what the issue closed signal) so the docs should be updated (more likely), or the issue reopened.

**Comment by oliviertassinari** [comment]
Another case of a user being confused about the outdated docs of the data grid regarding RTL: https://mui.zendesk.com/agent/tickets/9360

> Is there any way to solve the support for RTL?

**Comment by MBilalShafi** [comment]
Since the docs are [updated](https://github.com/mui/mui-x/issues/9552) now, this issue could be closed.
Feel free to reopen if you find docs confusing or find another issue related to the discoverability or RTL in the data grid.
