### ISSUE TITLE
Unable to Customize Toolbar of MUI DataGrid

### ISSUE THREAD

**Issue by starboyvarun** [mui/mui-x#8666]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.Create a new MUI DataGrid component.
2.Pass the toolbar configuration props by importing the GridToolbarContainer, GridToolbarExport and GridToolbarColumnsButton from @mui/x-data-grid-pro.
3.Configure the toolbar buttons and actions.
4.Render the MUI DataGrid with the new customized toolbar.

### Current behavior 😯

The toolbar of MUI DataGrid remains unchanged, even though the configuration options have been passed in the props.

### Expected behavior 🤔

The toolbar of MUI DataGrid should be customized according to the configuration options passed in the props.

### Context 🔦

Also guide whether this can be done in normal MUI Datagrid.

### Your environment 🌎

Version of MUI used: 5.0.0-alpha.51
Browser used: Chrome 96.0.4664.93
Operating System: Windows 10

**Comment by MBilalShafi** [comment]
Hey @starboyvarun, thank you for using MUI X DataGrid.

Could you provide a minimal reproduction of the problem being faced in order to understand it better?
You can start with this simple codesandbox example: https://codesandbox.io/s/datagrid-v5-quick-start-54iz1

**Comment by AndieBird92** [comment]
- Originally it was set like this:

```
return (
        <>
            <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
                Page Title
            </Typography>
            <Grid container sx={{ margin: 0, width: '100%' }}>
                <Grid item xs={12}>
                    <DataGrid
                        columns={columns}
                        rows={users}
                        pageSizeOptions={[10, 25]}
                        initialState={{
                            pagination: {
                                paginationModel: { pageSize: 10, page: 0 },
                            },
                        }}
                        slots={{ toolbar: GridToolbar }}
                        slotProps={{
                            toolbar: {
                                showQuickFilter: true,
                            },
                        }}
                    ></DataGrid>
                </Grid>
            </Grid>
        </>
```
and would render:
![image](https://github.com/mui/mui-x/assets/110256232/b44151ed-7763-485f-b925-34e280ff6ce6)
which isnt correct also since the expected behaviour is (from mui) 
![image](https://github.com/mui/mui-x/assets/110256232/7ef30693-d513-4e7a-a504-6700140df8ff)


- Setting up the Custom tool bar as follows, according to docs gives me this result:

```
function CustomToolbar() {
        return (
            <GridToolbarContainer>
                <GridToolbarColumnsButton />
                <GridToolbarFilterButton />
                <GridToolbarDensitySelector />
                <GridToolbarExport />
            </GridToolbarContainer>
        );
    }

 return (
        <>
            <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
                Page Title
            </Typography>
            <Grid container sx={{ margin: 0, width: '100%' }}>
                <Grid item xs={12}>
                    <DataGrid
                        columns={columns}
                        rows={users}
                        pageSizeOptions={[10, 25]}
                        initialState={{
                            pagination: {
                                paginationModel: { pageSize: 10, page: 0 },
                            },
                        }}
                        slots={{ toolbar: CustomToolbar }}
                        slotProps={{
                            toolbar: {
                                showQuickFilter: true,
                            },
                        }}
                    ></DataGrid>
                </Grid>
            </Grid>
        </>
```
![image](https://github.com/mui/mui-x/assets/110256232/3877888f-147a-4c65-843d-560df455c31d)
