### ISSUE TITLE
[pickers] Date Calendar block entire browser tap on pass value

### ISSUE THREAD

**Issue by PinoFlores** [mui/mui-x#8667]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

    <Popover
          id={id}
          open={open}
          anchorEl={anchorEl}
          onClose={handleClose}
          anchorOrigin={{
            vertical: 'bottom',
            horizontal: 'left',
          }}
        >
          <LocalizationProvider dateAdapter={AdapterMoment}>
            <DateCalendar value={moment(props.value)}  onChange={(date: moment.Moment) => props.onChange(moment(date).toString())} />
          </LocalizationProvider>
        </Popover>

### Current behavior 😯

Blocking the browser tap

### Expected behavior 🤔

Render the date

### Context 🔦

I just want to using it as a input, value onChange

### Your environment 🌎

    <Popover
          id={id}
          open={open}
          anchorEl={anchorEl}
          onClose={handleClose}
          anchorOrigin={{
            vertical: 'bottom',
            horizontal: 'left',
          }}
        >
          <LocalizationProvider dateAdapter={AdapterMoment}>
            <DateCalendar value={moment(props.value)}  onChange={(date: moment.Moment) => props.onChange(moment(date).toString())} />
          </LocalizationProvider>
        </Popover>

**Comment by PinoFlores** [comment]
Only happening in `DateCalendar` in `StaticDateCalendar` all is ok, but as you know the `Static` has some header and footer, so that is force me to use css to hiden those unneeded components. So good be nice to use `DateCalendar` as it has not include those footer and header.


This is the how we solved my needs, but check that I need to hiden toolbars and actions. This in the `DateCalendar` is not needed by have some bug in when I pass the value, I mean when I used it as a controlled input.

```js
         <LocalizationProvider dateAdapter={AdapterMoment}>
              <StaticDatePicker
                sx={{
                  '.MuiPickersToolbar-root, .MuiDialogActions-root': {
                    display: 'none',
                  },
                }}
                orientation="portrait"
                defaultValue={moment()}
                value={props.value ? moment(props.value) : null}
                onChange={(date) => {
                  if (date) props.onChange(moment(date).toString());
                  handleClose();
                }}
              />
            </LocalizationProvider>
```

**Comment by LukasTy** [comment]
Regarding the toolbar and actions hiding, you can consider using the following prop to achieve a more correct result of them not being rendered.
```tsx
slotProps={{
  toolbar: {
    hidden: true,
  },
  actionBar: {
    actions: [],
  },
}}
```

**Comment by alexfauquette** [comment]
I tried to reproduce your code, but did not succeed. Could you have a look at this codesandbox, and either do a screen recording of the bug, or fork it to reproduce it
https://codesandbox.io/s/hopeful-swirles-k2qj78?file=/demo.tsx
