### ISSUE TITLE
CheckboxSelection column's position vs orderedFields (initialState)

### ISSUE THREAD

**Issue by pczuba** [mui/mui-x#8673]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Enable checkboxSelection in DataGridPro.
2. Set `initialState` in DataGridPro with columns.orderedFields.

### Current behavior 😯

CheckboxSelection column was moved from left to right. 

### Expected behavior 🤔

CheckboxSelection column should be on the left side of the grid.
When I set initialState.columns.orderedFields it shouldn't change position of the column.
It should be still on the left side of the grid.

### Context 🔦

I'm trying to set an initial state for my DataGridPro inculding columns order.

**Comment by pczuba** [comment]
import React from "react";
import { DataGridPro } from "@mui/x-data-grid-pro";

const rows = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "XGrid", col2: "is Awesome" },
  { id: 3, col1: "Material-UI", col2: "is Amazing" },
  { id: 4, col1: "Hello", col2: "World" },
  { id: 5, col1: "XGrid", col2: "is Awesome" },
  { id: 6, col1: "Material-UI", col2: "is Amazing" }
];

const columns = [
  { field: "id" },
  { field: "col1", headerName: "Column 1", width: 150 },
  { field: "col2", headerName: "Column 2", width: 150 }
];

const initialState = {
  columns: {
    columnVisibilityModel: {
      id: false
    },
    orderedFields: ["col2", "col1"]
  }
};

export default function App() {
  return (
    <div style={{ height: 300, width: "100%" }}>
      <DataGridPro
        checkboxSelection
        rows={rows}
        columns={columns}
        initialState={initialState}
      />
    </div>
  );
}

**Comment by pczuba** [comment]
What shoud I do?
Should I add this CheckboxSelection column to mu orderedFields?
I don't know, how to do this.

**Comment by alexfauquette** [comment]
columns that are not in the ordered list are added at the end

[Checkbox columns](https://mui.com/x/react-data-grid/row-selection/#custom-checkbox-column) default definition (which includes its `field`) is available in the constant `GRID_CHECKBOX_SELECTION_COL_DEF`.

Maybe the https://mui.com/x/react-data-grid/column-ordering could get a section with the field of special columns, such that a dev customizing the columns order can find each of them at the same place

**Comment by pczuba** [comment]
Thanks a lot for your help.
