### ISSUE TITLE
[pickers] How to customize the view

### ISSUE THREAD

**Issue by srbadni** [mui/mui-x#8675]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/snowy-rain-ol72oh

### Current behavior 😯

Currently, it offers me a series of properties that I need to fully customize the Paper component, such as onClick, onChange and...
But unfortunately, as you can see in the live example I posted, the props I get have a series of completely different fields.

### Expected behavior 🤔

I want to have access to all the methods needed to render and customize the paper

### Context 🔦

I want to completely change the paper, but I need its functionalities
For example, the default paper changes the months with the left and right arrow buttons.
I want to make an infinite scroll in general so that the months are placed under each other and loaded with the scrolling of the months under one another.

**Comment by alexfauquette** [comment]
If I understand correctly, you are trying to create a completely new view for date pickers.

`mobilePaper` slot is made such that you can override the paper component wrapping the view. But not to override the entire content. Basically, it expects a component accepting children.

For your use case, the `viewRenderers` prop seems more adapted. But it's not fully documented yet
