### ISSUE TITLE
[DataGridPro] Keep row children expansion state on CRUD operation

### ISSUE THREAD

**Issue by taiwoladipo** [mui/mui-x#8676]
### Order ID or Support key 💳 (optional)

2950157729

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am implementing a CRUD use case for the tree data. If a row is expanded while a new child row is created, the new row is created but the parent row gets collapsed. With a huge dataset it makes it difficult to track where the new row was inserted. 
I have tried to programatically toggle the expansion using `apiRef.current.setRowChildrenExpansion(id, true)` with no luck. Can you advise on how to achieve this?

**Steps to reproduce**
Link to live example: https://codesandbox.io/s/thirsty-matan-k00vn4?file=/src/TreeData.tsx
Reproducible on Chrome and Safari.

1. Click the plus icon on the US row.
2. Expand the US row to see the inserted row.

**Expected behaviour**
The US row should remain expanded after the new row is inserted.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
The issue seems similar to https://github.com/mui/mui-x/issues/7771
Can you check [this](https://github.com/mui/mui-x/issues/7771#issuecomment-1410218395) comment and see if it could be a potential fix for you?

**Comment by taiwoladipo** [comment]
Yes, `updateRows` preserves the expansion state. Thanks for the suggestion.
