### ISSUE TITLE
When I try to resize my column, I get the error shown below.

### ISSUE THREAD

**Issue by SAMBIT20** [mui/mui-x#8680]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/50833547/233139178-980712cb-c998-48e6-b65a-1450e8dfafb5.png">

Steps:
1.
2.
3.

### Current behavior 😯

<img width="197" alt="image" src="https://user-images.githubusercontent.com/50833547/233139266-6e81b65a-651b-4ce6-9406-b2f3e77f7f5a.png">

### Expected behavior 🤔

<img width="690" alt="image" src="https://user-images.githubusercontent.com/50833547/233139315-010e9289-8b09-40c7-8185-ec4f45d3a4dc.png">

### Context 🔦

unable to drag the column it's throw 
`eGridColumnResize.js:181 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '[data-field="system milk production
(litres / year)"]' is not a valid selector.
 `

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

62159

**Comment by MBilalShafi** [comment]
Can you provide a minimal reproduction example in codesandbox to better debug the problem?
You can start with this codesandbox: https://codesandbox.io/s/datagridpro-basic-gzmv9c?file=/src/App.tsx

**Comment by SAMBIT20** [comment]
@MBilalShafi I just updated the codesandbox kindly check

**Comment by MBilalShafi** [comment]
When you update and save, a new fork is generated, you have to share that 🙂

**Comment by SAMBIT20** [comment]
@MBilalShafi  Link : https://codesandbox.io/s/datagridpro-basic-forked-5jk1u9?file=/src/App.tsx

**Comment by yaredtsy** [comment]
hey @SAMBIT20

`field` prop is used to identify the column, so do not insert escape sequences like `\n` .  escape sequences can't be used as valid `querySelector`, `field` prop does not have to match with `headerName` you can use small simpler text for `field`.

**Comment by SAMBIT20** [comment]
@MBilalShafi @yaredtsy Thanks for your support `.replace(/(\r\n|\n|\r)/gm, "")` fix my issue .
