### ISSUE TITLE
How to get Row Grouping to work when I render a cell with a React Element>

### ISSUE THREAD

**Issue by jjspierx** [mui/mui-x#8681]
### Order ID or Support key 💳 (optional)

63696

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

When using "renderCell" of a column, if render a React Element, instead of a value (which is the intent of renderCell), it causes grouping to combine all values.

Here is an example of a column definition:

`{
			groupingValueGetter: (groupingData) => groupingData.row.Case.Client,
			renderCell: (params) => (
				<DataTableLinkValue value={params.value._FullName} link={`/client/${params.value.Id}`} />
			),
			field: 'client',
			headerName: 'Client',
			width: 200,
		}`

Without the renderCell, my grouping for Client works just fine.  When adding renderCell, all Clients are collapsed into the row of the top Client.  This only happens if renderCell returns a React Element (component).  If renderCell returns just a value (in which case I wouldn't need renderCell at all), the grouping works just fine.  Here is an example that works:

`{
			groupingValueGetter: (groupingData) => groupingData.row.Case.Client,
			renderCell: (params) => params.value._FullName,
			field: 'client',
			headerName: 'Client',
			width: 200,
		}`

Is this a bug, or am I doing something wrong? How can I get grouping to work when rendering a cell with a React Element.  Thank you.

### Your environment 🌎

 System:
    OS: Windows 10 10.0.25330
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.25330.1000.0), Chromium (112.0.1722.48)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.123
    @mui/core-downloads-tracker:  5.11.15
    @mui/icons-material: ^5.11.11 => 5.11.11
    @mui/material: ^5.11.15 => 5.11.15
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.16
    @mui/styles: ^5.11.13 => 5.11.13
    @mui/system: ^5.4.1 => 5.11.16
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-data-grid:  6.0.4
    @mui/x-data-grid-premium: ^6.0.4 => 6.0.4
    @mui/x-data-grid-pro:  6.0.4
    @mui/x-date-pickers: ^6.0.4 => 6.0.4
    @mui/x-date-pickers-pro: ^6.0.4 => 6.0.4
    @mui/x-license-pro:  6.0.3
    @types/react:  18.0.20
    react: ^17.0.1 => 17.0.2
    react-dom: ^17.0.1 => 17.0.2
    typescript: ^4.1.3 => 4.8.3

**Comment by jjspierx** [comment]
Ok, I've narrowed down the problem a little.  The reason the grouping is lost, is because the groupingValueGetter is getting an object, not a string, int, etc...  However, the problem I run into, is I need access to that object in the renderCell, and I lose that by grouping on a value in the object.

For instance, in the example below, I am grouping by the `Client` object.  This breaks grouping, however, I need access to both `Client.Id` and `Client.Name` in `renderCell`, however, if I specify `Client.Name` for the groupingValueGetter, I no longer have access to `Client.Id` in the renderCell, which I need to generate a link in that cell.

``groupingValueGetter: (groupingData) => groupingData.row.Case.Client``

**Comment by jjspierx** [comment]
I found a workaround to my problem by concatenating a string, and then splitting the string in `renderCell`

```
groupingValueGetter: (groupingData) => `${groupingData.row.Case.Client.Id} ${groupingData.row.Case.Client._FullName}`,
renderCell: (params) => {
    const client = params.value.split(' '); 
    return (<DataTableLinkValue value={client[1]} link={`/client/${client[0]}`} />);
}
```
Is there any other way to access an objects properties inside `renderCell`, even if the `groupingValueGetter` value is a child of the object I want to get data from in `renderCell`?

**Comment by MBilalShafi** [comment]
Can you explain the shape of your data, by description, you have an object and deduce the grouping value using groupingValueGetter from some keys of that object, if you want to access that value, did you check `params.row` in `renderCell` if it contains the information you need?

Also, it will be easier to debug if we can reproduce the pain point in some code example. Could you use this [codesandbox](https://codesandbox.io/s/datagridpremium-basic-ovlrkm?file=/src/App.tsx) as starting point, reproduce the problem you are facing and share the modified codesandbox here?

**Comment by jjspierx** [comment]
The problem is that `params.row` is an empty object.

https://codesandbox.io/s/datagridpremium-basic-forked-seov8u

You can see the data structure from the codesandbox above.  In `renderCell`, `params.row` is an empty object, and `params.value` is `Client._FullName`.  I need access to `Client.Id` in renderCell in order for me to generate a link that is dependent on the Id.  I think maybe it is a bug that somehow `params.row` is empty when using `renderCell` after a using `groupingValueGetter`?

Thank you for the help.

**Comment by jjspierx** [comment]
Any update on this? Thanks.

**Comment by MBilalShafi** [comment]
Hey @jjspierx, sorry about the delay.

I am glad you have one workaround. Why `params.row` is empty in `renderCell` is, because the control is currently in a grouped row, which is an autogenerated row and not one of the actual rows, (to confirm, you can log the `params.id`, it should have `auto-generated-row` in the beginning) and does not belong to an actual `data` row provided by you.

Here are the possible options:

1. Using `groupingValueGetter` and then splitting the values could be one workaround. 
2. Another option if you want the `row` value of one of a child rows in a `group` row, you can use the `params.api` to get the required value.

I tried to do it in this codesandbox example: https://codesandbox.io/s/datagridpremium-basic-forked-kclhic?file=/src/App.tsx

Let me know if you have further questions. Thanks
