### ISSUE TITLE
Theme needs to be defined for Data Grid

### ISSUE THREAD

**Issue by rishabmahesh-umass** [mui/mui-x#8683]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-data-grid/

### Kind of issue

Missing information

### Issue description

I am using MUI v5 and saw DataGrid in the documentation here (https://mui.com/material-ui/react-table/#data-table). I downloaded the relevant packages and tried the example in the docs. However, I was seeing a blank page in my react app. 

I saw this error initially: -

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/40054912/233178550-0b3ba1de-69e6-4217-a1d1-b21e83f792d3.png">

After 2 hours of breaking my head, I saw a particular TS error: -

<img width="519" alt="image" src="https://user-images.githubusercontent.com/40054912/233178701-285e29f6-3219-4ad4-ab00-4b568cff3512.png">

It was then I realized that I had not defined the theme for the app. 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/40054912/233179397-f002164a-75d3-4f4c-92a1-ac56e11d68a4.png">

Only after defining the theme was I able to actually see the example. 

I did not see this mentioned in the docs anywhere that theme NEEDS to be defined and passed in my entry file. 

Please mention that theme needs to be defined or change the code to use a default if not defined.

**Comment by MBilalShafi** [comment]
Hey @rishabmahesh, thanks for using the MUI-X DataGrid.

Could you provide a minimal reproduction in codesandbox to be able to better debug it? You can use this codesandbox as a starting point: https://codesandbox.io/s/datagrid-v5-quick-start-54iz1

**Comment by rishabmahesh** [comment]
I was unable to reproduce the error in a new react app or in code sandbox. However, I have made a part of my personal project public on this link: https://github.com/rishabmahesh/DataGrid

Concentrate on Commit 3. In commit 3, I used theme provider, while in commit 2, I had not used theme provider. 

If you were to run the app on commit 2, you would see the same error as said above. However, if you were to use themeProvider as done in commit 3, the error goes away. 

Relavant files in link: -
- index.js
- website.js

I am calling DataGrid in website.js: -
<img width="351" alt="image" src="https://user-images.githubusercontent.com/40054912/234763616-f841da30-4310-4f67-9c8c-b1a414f29f46.png">


Error occurs when: - (file name: index.js)
<img width="611" alt="image" src="https://user-images.githubusercontent.com/40054912/234763777-749c942d-709d-4732-b791-404e32bf5b85.png">

Error goes away when: - (file name: index.js)
<img width="617" alt="image" src="https://user-images.githubusercontent.com/40054912/234763831-f10ed0fc-7565-4c9c-9b90-fafa2b24e3cf.png">

**Comment by rishabmahesh** [comment]
Any status on this @MBilalShafi ?

**Comment by MBilalShafi** [comment]
@rishabmahesh It seems like when using `<ChakraProvider />`, to provide correct styles to the Grid, you have to wrap the Grid in `<ThemeProvider />`, this has been faced by another user too in https://github.com/mui/mui-x/issues/6788, and the same solution was suggested there too, feel free to check it out.
