### ISSUE TITLE
[question] Multiple date ranges in DateRangeCalendar

### ISSUE THREAD

**Issue by rogulskizbyszek** [mui/mui-x#8687]
### Order ID or Support key 💳 (optional)

64682

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

HI, 

my order id is 64682

The question is:

I want to use Calendar component and pass as a value a list of ranges, so I want to display multiple dates ranges on to the calendar:

values={[[range1], [range2], etc]}

Code bellow is just a example, dates should be a real ranges.
 

Is this possible be default or if not do you have any suggestion how to do that?

I'm using MUI with React and TypeScript.

### Your environment 🌎

const value = [[dayjs(), dayjs()], [dayjs(), dayjs()], [dayjs(), dayjs()]]

<DateRangeCalendar
  calendars={1}
  value={value}
  onChange={(newValue: DateRange<Dayjs>) => setValue(newValue)}
/>

**Comment by alexfauquette** [comment]
For now, it's not supported, and not in our backlog. The main problem of such interface would be to create a consistent UX when editing the ranges. When clicking on a date, should it: start a new range, or edit an existing one? And in the second scenario which range should be edited

**Comment by flaviendelangle** [comment]
Regarding internal infra, the solution would probably be to expose `DayCalendar` to handle several day selections.
And to expose a `DayRangeCalendar` which wraps `DayCalendar` and supports several day-range selections.

`DateRangeCalendar` would then use `DayRangeCalendar` for the day view like `DateCalendar` uses `DayCalendar` for the day view.

**Comment by rogulskizbyszek** [comment]
> For now, it's not supported, and not in our backlog. The main problem of such interface would be to create a consistent UX when editing the ranges. When clicking on a date, should it: start a new range, or edit an existing one? And in the second scenario which range should be edited

For now it will be great to just have "display" option, for disabled calendar. 
I understand your concerns but as I mentioned I need some solution which will satisfied acceptance criteria for end product.

If you have any ideas how to workaround for now it would be great :)

**Comment by alexfauquette** [comment]
If you only want to display the data and not interact with them you can save range data outside of the component and use them to create custom day rendering

- [example on date calendar](https://mui.com/x/react-date-pickers/date-calendar/#custom-day-rendering)
- [example on date range calendar](https://mui.com/x/react-date-pickers/date-range-calendar/#custom-day-rendering)

**Comment by rogulskizbyszek** [comment]
Thx, i'm closing :)
