### ISSUE TITLE
[pickers] MuiDatePicker ' is not assignable to type 'Components<Omit<Theme, "components">>'.   Object literal may only specify known properties, and 'MuiDatePicker' does not exist in type 'Components<Omit<Theme, "components">>

### ISSUE THREAD

**Issue by b235423534** [mui/mui-x#8695]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

My theme utilises components.ts like so:

```
...
import type {} from "@mui/x-date-pickers/themeAugmentation";
....

export const components = {


MuiLink: {
...
},
  MuiDatePicker: {
    styleOverrides: {
      root: {
        backgroundColor: "red",
      },
    },
  },
}
```

```
const theme = createTheme({
...
components,
...
})
```
Unfortunately, I get a TypeScript error:

```
Type '{ MuiFab: { styleOverrides: { root: { textTransform: "none"; }; }; }; MuiButton: { defaultProps: { variant: "contained"; disableElevation: true; disableRipple: true; }; styleOverrides: { root: ({ theme, ownerState: { color, size } }: any) => { ...; }; }; }; MuiDialogTitle: { ...; }; MuiLink: { ...; }; MuiDatePicker:...' is not assignable to type 'Components<Omit<Theme, "components">>'.
  Object literal may only specify known properties, and 'MuiDatePicker' does not exist in type 'Components<Omit<Theme, "components">>'.ts(2322)
```

### Current behavior 😯

Type '{ MuiFab: { styleOverrides: { root: { textTransform: "none"; }; }; }; MuiButton: { defaultProps: { variant: "contained"; disableElevation: true; disableRipple: true; }; styleOverrides: { root: ({ theme, ownerState: { color, size } }: any) => { ...; }; }; }; MuiDialogTitle: { ...; }; MuiLink: { ...; }; MuiDatePicker:...' is not assignable to type 'Components<Omit<Theme, "components">>'.
  Object literal may only specify known properties, and 'MuiDatePicker' does not exist in type 'Components<Omit<Theme, "components">>'.ts(2322'

### Expected behavior 🤔

No typescript errors

### Your environment 🌎

    "typescript": "^4.5.2"

**Comment by LukasTy** [comment]
Hello @b235423534 
Have you followed [the typescript setup guide](https://mui.com/x/react-date-pickers/base-concepts/#typescript)?
Based on the error, you might be missing the `themeAugmentation` import. 🤔 

If you are still having issues, please provide a reproduction example, preferably in the form of a codesandbox. 😉
