### ISSUE TITLE
[DataGrid] All JSDOM tests fail with v6.2.1

### ISSUE THREAD

**Issue by ddolcimascolo** [mui/mui-x#8697]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Not required

### Current behavior 😯

All tests fail.

### Expected behavior 🤔

All tests pass, or @mui explain what needs to be changed

### Context 🔦

In JSDOM, we historically need to mock stuff to make the grid render (see https://github.com/mui/mui-x/issues/2945 for instance).
Starting with v6.2.1 grids do not render the "virtual scroller" area anymore, and having a look at the code does not tell me why. I need your help in fixing this and I'm totally open to mocking more stuff, it's just unclear what :)

Premium customer here

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.19 Linux Mint 21.1 (Vera)
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: Not Found
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Firefox: 112.0.1
```
</details>

### Order ID or Support key 💳 (optional)

31461

**Comment by ddolcimascolo** [comment]
Adding Mocks for ResizeObsever that was added in this version did not help. I understand that it's used for resize detection but it's non availability should not prevent the virtual scroller from rendering

**Comment by ddolcimascolo** [comment]
OK, finally it did help to add mocks for `ResizeObserver`. Here's how I got my tests back

```javascript
beforeEach(mockResizeObserver);

function mockResizeObserver() {
  window.ResizeObserver = class ResizeObserver {
    constructor(callback) {
      this.callback = callback;
    }

    observe(target) {
      setTimeout(() => this.callback([{ target }]), 0);
    }

    unobserve() {}

    disconnect() {}
  };
}
```
You'll notice the ugly `setTimeout` in the observe method to call the listener. My initial tentative was calling the listener directly, and apparently the main div of the grid is not rendered yet at that time, or any other side-effect I'm not aware of was preventing the grid from rendering :sweat: Calling the listener in the next tick works.

I hope it helps other JSDOM users out there.

Cheers,
David

**Comment by dnikhila** [comment]
Still I do face same issue suddently -> previously I sorted out using disableVirtualization, using datagridpro - ^6.1.0, rows and columns were not rendering in test cases - jest with react testing

**Comment by dnikhila** [comment]
This is how snapshot renders  it includes col and row count but it was not rendering -> 
```
  <div
            aria-colcount="4"
            aria-multiselectable="true"
            aria-rowcount="3"
            class="MuiDataGrid-root-czaLuz bmEiLl MuiDataGrid-root MuiDataGrid-autoHeight MuiDataGrid-root--densityStandard MuiDataGrid-withBorderColor"
            role="grid"
          >
            <div
              class="MuiDataGrid-main-gYeYdy hGlvJW MuiDataGrid-main"
            >
              <div
                class="MuiDataGrid-columnHeaders-hmyAqf joUSja MuiDataGrid-columnHeaders MuiDataGrid-withBorderColor"
                style="min-height: 56px; max-height: 56px; line-height: 56px;"
              >
                <div
                  class="MuiDataGrid-columnHeadersInner-dYCRFF gMqqpv MuiDataGrid-columnHeadersInner"
                  role="rowgroup"
                />
              </div>
            </div>
            <div
              class="MuiDataGrid-footerContainer-PALYL hAmnMh MuiDataGrid-footerContainer MuiDataGrid-withBorderColor"
            >
              <div />
            </div>
```

**Comment by p-m-p** [comment]
> Hi everyone, We use this mock for `ResizeObserver` in our test environment:
> 
> https://github.com/mui/mui-x/blob/aba4549d3d7ad1b8025d7f69247756439c8f3189/packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx#L52-L68
> 
> If this doesn't help, please provide a minimal reproduction example (could be a repo on GitHub) and we will look into it.

Thanks, I can confirm this does work but does require you use an `findBy` or `waitFor` in testing library where before `getBy` was working.

**Comment by dnikhila** [comment]
@cherniavskii  @p-m-p I tried above solution, still same can you please see this comment https://github.com/mui/mui-x/issues/1151#issuecomment-1520182742

**Comment by ddolcimascolo** [comment]
Yeah, testing the grid in JSDOM has always been a pain, see my OP

**Comment by Lori-Becker** [comment]
We are also using react-testing-library and JSDOM. Tests verifying the content inside the Data Grid were passing for me in 6.0.4, but I was having issues testing a column with `type="actions"`. The actions buttons were not rendering in my tests, even though the row data was there. I thought if I upgraded to 6.3.0, that might fix it, but now all tests fail.

**Comment by sanderkoenders** [comment]
I am facing the same issues when testing DataGrid. The issues have appeared in version `6.2.0` for me.

**Comment by Nic-S** [comment]
Also the same in DataGridPro from version 6.2.1 .
Moreover, I don't think it's a good thing that a minor one creates these compatibility problems with tests.

**Comment by brunomendola** [comment]
Hi all. Here is a minimal example of this bug (there's a failing test):
https://codesandbox.io/s/react-ts-mui-x-data-grid-9rojxn
Works with `"@mui/x-data-grid": "6.2.0"` but stops working from `"@mui/x-data-grid": "6.2.1"` (also 6.3.0).

**Comment by Nic-S** [comment]
> @brunomendola You need to mock `ResizeObserver` before the JSDOM instance is created. In CodeSandbox this can't be done.
> 
> > Moreover, I don't think it's a good thing that a minor one creates these compatibility problems with tests.
> 
> @Nic-S We recommend using a real browser to run tests, otherwise, problems like these may happen. We can't guarantee that a change we release won't break tests. We aim to guarantee that the APIs will be compatible, but tests is a different world.

Within the MUI documentation we have this:
[Testing](https://mui.com/material-ui/guides/testing/)

Instead in the MUI-X package, we only have within virtualization a paragraph about [testing](https://mui.com/x/react-data-grid/virtualization/#disable-virtualization).
Nowhere in the documentation is it recommended to use a real browser for testing.

**Comment by fjAtEab** [comment]
> @Nic-S We recommend using a real browser to run tests, otherwise, problems like these may happen. We can't guarantee that a change we release won't break tests. We aim to guarantee that the APIs will be compatible, but tests are a different world.

Are you suggesting that developers forego unit testing components that use Material UI?  I am shocked to read this.

**Comment by DavidArmendariz** [comment]
None of the solutions worked for me.

**Comment by joaosousafranco** [comment]
Same issue but with version 6.3.1

**Comment by joaosousafranco** [comment]
@cherniavskii it works but forces some dirty type cast when using typescript, anyway is better then nothing, thank you

**Comment by rafaelcmm** [comment]
> I created this repo with a basic DataGrid test using React Testing Library and JSDOM: https://github.com/cherniavskii/data-grid-testing Adding `ResizeObserver` makes the test pass: [cherniavskii/data-grid-testing@0da89b5](https://github.com/cherniavskii/data-grid-testing/commit/0da89b5a5ec620af00b2a19c7f9c3c2be2015ca1) Can you try using this mock?

In our case the solution was pretty inconsistent. Making it works at some test cases, but not in others, so I don't see this as a permanent solution, specially for bigger projects.

**Comment by cherniavskii** [comment]
> In our case the solution was pretty inconsistent. Making it work at some test cases, but not in others, so I don't see this as a permanent solution, specially for bigger projects.

Could you provide a test case where it's not working? I will look into it.

> I've identified two PR's that changed things related to what is probably causing the issue, that were added after the last known working version v6.1.0 to the latest one v6.3.1

Yes, we changed the implementation of the internal auto sizer in https://github.com/mui/mui-x/pull/8091 
While it's not a breaking change in terms of API or behavior in the browser (it actually fixed a few bugs), this caused the tests to fail in non-browser environments that do not have ResizeObserver available.

**Comment by Lori-Becker** [comment]
> I created this repo with a basic DataGrid test using React Testing Library and JSDOM: https://github.com/cherniavskii/data-grid-testing Adding `ResizeObserver` makes the test pass: [cherniavskii/data-grid-testing@0da89b5](https://github.com/cherniavskii/data-grid-testing/commit/0da89b5a5ec620af00b2a19c7f9c3c2be2015ca1) Can you try using this mock?

I tried using the ResizeObserver mock (converted to TS -  see [this gist](https://gist.github.com/Lori-Becker/48b6968b84ed820f1c8e7e899fbce9fe) for a TS version) and it generally worked! 2 out of 3 of my tests passed. The third test that did not pass is trying to target an Actions button when a column is `type: actions`. This still does not reveal that column in JSDOM for some reason.

**Comment by ddolcimascolo** [comment]
About that, keep in mind that by default the grid uses virtualization for rows AND columns, and you have to make it think there's more space available so that all your columns are rendered. From the top of my head, the usual defaults you get in JSDOM are 15-ish rows and 3 columns.

I linked an issue in my OP, and especially this note https://github.com/mui/mui-x/issues/2945#issuecomment-975715794 might be helpful.

I have tens of tests rendering grids in various conditions in our main project, using extra features like aggregations and grouping, and they all pass fine using the ResizeObsever mock I posted above.

Cheers,
David

**Comment by cherniavskii** [comment]
Hey everyone,
I had an idea that could make the `ResizeObserver` mock unnecessary in JSDOM and opened a draft PR: https://github.com/mui/mui-x/pull/8961

I tested a build from that PR in https://github.com/cherniavskii/data-grid-testing/tree/without-mock
And the test passes without a mock.

Does this build fix failing tests in your testing env?
https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid
https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid-pro
https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid-premium

**Comment by rafaelcmm** [comment]
> Hey everyone, I had an idea that could make the `ResizeObserver` mock unnecessary in JSDOM and opened a draft PR: #8961
> 
> I tested a build from that PR in https://github.com/cherniavskii/data-grid-testing/tree/without-mock And the test passes without a mock.
> 
> Does this build fix failing tests in your testing env? https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid-pro https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid-premium

@cherniavskii in the project that I work on, this build made all tests pass 🥳 

900+ test cases.

**Comment by cherniavskii** [comment]
@rafaelcmm Thanks for your feedback!
We will address this issue, so that the `ResizeObserver` mock will not be required in JSDOM 👍

**Comment by emildudnyk** [comment]
> Hey everyone, I had an idea that could make the `ResizeObserver` mock unnecessary in JSDOM and opened a draft PR: #8961
> 
> I tested a build from that PR in https://github.com/cherniavskii/data-grid-testing/tree/without-mock And the test passes without a mock.
> 
> Does this build fix failing tests in your testing env? https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid-pro https://pkg.csb.dev/mui/mui-x/commit/8695c6af/@mui/x-data-grid-premium

@cherniavskii all failure tests passed. Thank you, it's awesome 😃
