### ISSUE TITLE
[data grid] Styling of GridFilterInputSingleSelect is not correctly applied

### ISSUE THREAD

**Issue by Jul13nT** [mui/mui-x#8703]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

This issue is visible directly on the documentation.

- Use this codesandbox: https://codesandbox.io/s/khcbxs?file=/demo.js
- Open the filter panel
- Add a filter on the column Country
- The singleSelect label is not correctly positioned

### Current behavior 😯

When using a variant other than `standard` for styling singleSelect inputs in Data Grid filter panel using the following code:

```javascript
filterFormProps: {
  valueInputProps: {
    InputComponentProps: {
      variant: 'outlined',
      size: 'small',
    },
  },
},
```

The variant is not applied to the label:

![image](https://user-images.githubusercontent.com/2983260/233663357-2438404f-cad0-4c96-bde6-0b39e7bb8096.png)

### Expected behavior 🤔

The label should be correctly positioned.

### Context 🔦

I think this is due to this line: https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterInputSingleSelect.tsx#L132

The prop spreading should be below `variant="standard"`.

The label was correctly positioned in MUI-X 5.

### Order ID or Support key 💳 (optional)

#49931

**Comment by Jul13nT** [comment]
An additional symptom of this issue (I think) is the absence of `for` accessibility tag on the label. This can cause tools relying on this for selecting fields (like e2e testing with Playwright) to fail.

**Comment by Jul13nT** [comment]
Is there a fix planned for this issue? I'm stuck upgrading to v6 because my Playwright tests are failing due to this issue.

**Comment by Jul13nT** [comment]
Done ! Thanks for the patches !

**Comment by FreakDroid** [comment]
Hello. I have the same problem so I think this issue hasn't been resolved yet.

Do you have any workaround for this?

**Comment by FreakDroid** [comment]
Hey @m4theushw this issue is blocking my team. I opened a PR which is fixing this issue. Can you take a look at please?
