### ISSUE TITLE
renderDay to Day migration: no longer supports custom inner component

### ISSUE THREAD

**Issue by kuhiga** [mui/mui-x#8725]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. migrate from @material-ui/pickers to @mui/x-date-pickers.
2. import { DatePicker as DatePickerInternal } from '@mui/x-date-pickers/DatePicker';
3. use DatePicker component and use renderDay to replace day component with custom component
4. [replace `renderDay` prop with `Day` component slot ](https://github.com/mui/mui-x/blob/2d977dc9224d841a33915c664f7306d2df63424d/docs/data/migration/migration-pickers-v5/migration-pickers-v5.md#day-renderday)

### Current behavior 😯

before migration:
```
 <DatePicker
                    ...
                    value={selectedDate}
                     renderDay={(
                        day,
                        highlightedDate,
                        _dayInCurrentMonth,
                        DayComponent
                    ) =>
                        customDayRenderer({
                            DayComponent,
                            selectedDate,
                            day: day ?? null,
                            highlightedDate: highlightedDate ?? null,
                        })
                    }
                />
```
after migration:
```
 <DatePicker
                    ...
                    value={selectedDate}
                    slots={{
                        day: (day, { highlightedDate, DayComponent }) =>
                            customDayRenderer({
                                DayComponent,
                                selectedDate,
                                day
                                highlightedDate: highlightedDate ?? null,
                            }),
                    }}
                />
```
It is not behaving the same way as before the migration when component would be replaced.
`day ` component slot expects `React.ComponentType<PickersDayProps<Date>> | undefined` instead of jsx element

### Expected behavior 🤔

There should be a way to replace inner components with custom ones directly like what renderDay was doing.

### Context 🔦

I am in the process of migrating from `@material-ui/pickers` to `@mui/x-date-pickers`.
Previously I was able to replace the `day` sub component within `DatePicker` by using the `renderDay` prop that accepted a JSX element. I read in the migration that the `renderDay` prop has been replaced by a `Day` component slot.
However, the Day component slot expects type ` React.ComponentType<PickersDayProps<Date>>`.

Is this the intended behavior to only be able to modify the existing day component and not be able to replace it with a custom one like in `@material-ui/pickers`? Same thing with TextFieldComponent. What is the best alternative way to achieve the old behavior of being able to directly pass components in as a prop instead of just being to adjust existing prop ?  Thank you.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: Not Found
    Firefox: 112.0
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.126 
    @mui/core-downloads-tracker:  5.12.1 
    @mui/lab: ^5.0.0-alpha.127 => 5.0.0-alpha.127 
    @mui/material: ^5.12.1 => 5.12.1 
    @mui/private-theming:  5.12.0 
    @mui/styled-engine:  5.12.0 
    @mui/styled-engine-sc: ^5.12.0 => 5.12.0 
    @mui/styles: ^5.12.0 => 5.12.0 
    @mui/system:  5.12.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.0 
    @mui/x-date-pickers: ^6.2.1 => 6.2.1 
    @types/react: ^16.9.56 => 16.14.2 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.9 => 5.3.9 
    typescript: 4.7.4 => 4.7.4 
```
</details>

**Comment by alexfauquette** [comment]
As described in [the mentionned section](https://mui.com/x/migration/migration-pickers-v5/#day-renderday) the diff is the following

```diff
 <DatePicker
-  renderDay={(_, dayProps) => <CustomDay {...dayProps} />}
+  components={{ Day: CustomDay }}
 />
```

So you should replace the `renderDay` function `(day, { highlightedDate, DayComponent }) => customDayRenderer({ ... })` by a component.

```jsx
const CustomComponent = (props) => { ... return (...)}

/** ... */

slots={{ day: CustomComponent }}
```

About the props type of `React.ComponentType<PickersDayProps<Date>>` it's a helper.

`PickersDayProps<Date>` are all the props we will internally pass to the component. You are not forced to implement all the behaviors

**Comment by alexfauquette** [comment]
> the props are passed in as undefined

Since the definition of your functional component start as follow `(day, { highlightedDate, DayComponent }) =>` all the pros will be passed to `day`

```diff
- (day, { highlightedDate, DayComponent }) =>
+ ({ highlightedDate, DayComponent }) =>
```

would do the job.

By the way, it's recommended to declare your components outside. Otherwise, at each render your component will be a new one. Which implies it lost it's internal state

**Comment by kuhiga** [comment]
@alexfauquette I tried that but getting complaints that` Property 'highlightedDate' does not exist on type 'PickersDayProps<Date> & { children?: ReactNode; }'.ts(2339)` and `Property 'DayComponent' does not exist on type 'PickersDayProps<Date> & { children?: ReactNode; }'.ts(2339)`
````
day: ({ day, highlightedDate, DayComponent }) => <CustomComponent ... />
````
By the way, I appreciate your quick responses!

**Comment by LukasTy** [comment]
> I tried that but getting complaints that` Property 'highlightedDate' does not exist on type 'PickersDayProps<Date> & { children?: ReactNode; }'.ts(2339)` and `Property 'DayComponent' does not exist on type 'PickersDayProps<Date> & { children?: ReactNode; }'.ts(2339)`

What do you expect the `highlightedDate` and `DayComponent` to be? Are those props that you are passing?
In which case, you'd need to pass them via `slotProps={{ day: { highlightedDate, DayComponent } }}`.
Do note that we currently do not support `slotProps` typing extension beyond what those slots were designed for, so, in such case, you'd need to avoid the TS error the ugly way - by casting your props (i.e. `as any`).
