### ISSUE TITLE
[pickers] Missing he-IL inside package '@mui/x-date-pickers'  (DateTimePicker Control)

### ISSUE THREAD

**Issue by jamesDin** [mui/mui-x#8729]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Include this line in your project:

> import { enUS , **heIL**  } from '@mui/x-date-pickers';

### Current behavior 😯

"**heIL**" does not exist, even though I have seen it in your master branch for a long time already.

### Expected behavior 🤔

To have **heIL** inside DateTimePicker controls

### Context 🔦

50% of my product is based on Hebrew localization.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Chrome (latest)
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.126
    @mui/core-downloads-tracker:  5.12.1
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/lab: 5.0.0-alpha.127 => 5.0.0-alpha.127
    @mui/material: ^5.12.1 => 5.12.1
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.4
    @mui/utils:  5.12.0
    @mui/x-data-grid:  6.2.1
    @mui/x-data-grid-pro: ^6.2.1 => 6.2.1
    @mui/x-date-pickers:  5.0.20
    @mui/x-date-pickers-pro: ^6.2.1 => 6.2.1
    @mui/x-license-pro:  6.0.4
    @types/react: ^18.0.35 => 18.0.38
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```
</details>

### Order ID or Support key 💳 (optional)

62336

**Comment by LukasTy** [comment]
Hello,
could you provide some sort of a reproduction example (codesandbox or a minimal repository) detailing your problem?
I've [tried using `heIL` locale](https://codesandbox.io/s/dazzling-shannon-3lucvt?file=/demo.tsx:958-1013) and it seems to work without problems both from the top level import as well as from the `locales` directory. 🤷

**Comment by flaviendelangle** [comment]
```
    @mui/x-date-pickers:  5.0.20
    @mui/x-date-pickers-pro: ^6.2.1 => 6.2.1
```

That's maybe not related to your bug, but you have a version mis-match that could lead to some problems.

**Comment by jamesDin** [comment]
I did a clean ```npm install``` (after deleting the "**node_modules**" folder).
When I check the installed package folder, I see no "**he-IL**" inside:

Here I can see the ```heIL```:
```typescript
import { enUS, heIL, ruRU } from '@mui/material/locale';
import { enUS, heIL, ruRU } from '@mui/x-data-grid';
```

But here I can NOT see the ```heIL```:
```typescript
import { enUS, heIL, ruRU } from '@mui/x-date-pickers';  // heIL is missing, typescript is shouting.
```
I tried to ```ts-ignore``` this line, but it didn't help.

I saw @LukasTy's Codesandbox example, and I've noticed it's working there, but not for me, and I have no clue what it can be  :-(

**Comment by LukasTy** [comment]
> I saw Codesandbox example, and I've noticed it's working there, but not for me, and I have no clue what it can be :-(

Have you aligned your `x-date-pickers` dependency version with the `x-date-pickers-pro` to v6? Because, as Flavien mentioned, in your provided `@mui/envinfo` it's shown that you have a locked v5 version of `x-date-pickers`. 🙈

**Comment by jamesDin** [comment]
Yes.
Everything is the latest:

        "@mui/icons-material": "^5.11.16",
        "@mui/lab": "5.0.0-alpha.128",
        "@mui/material": "^5.12.2",
        "@mui/x-data-grid-pro": "^6.2.1",
        "@mui/x-date-pickers-pro": "^6.2.1",

**Comment by LukasTy** [comment]
This locale has only been added in `6.0.2`, are you sure that the typescript is also complaining about this issue?
Or is it only IDE? If it's IDE, maybe it has cached the old TS types and you just need to reload the IDE (TS linter). 🤷 
I've tried locally and it of course was a problem on 6.0.0, after installing 6.1.0 the TS linter is happy. 🤔

**Comment by jamesDin** [comment]
It's not only typescript; I don't even see the file physically on the drive.
```..\node_modules\@mui\x-date-pickers\locales\heIL.js```
And the file ```index.js``` in that folder has this content:
```typescript
export * from './nlNL';
export * from './plPL';
export * from './ptBR';
export * from './trTR';
export * from './deDE';
export * from './esES';
export * from './faIR';
export * from './fiFI';
export * from './csCZ';
export * from './frFR';
export * from './huHU';
export * from './enUS';
export * from './nbNO';
export * from './svSE';
export * from './itIT';
export * from './zhCN';
export * from './koKR';
export * from './isIS';
export * from './jaJP';
export * from './ukUA';
export * from './urPK';
export * from './beBY';
export * from './ruRU';
export * from './utils/pickersLocaleTextApi';
```

I understand what you are saying about ```@mui/x-date-pickers:  5.0.20``` (and I don't know where it stuck), but it still should be on the system file, no?

**Comment by jamesDin** [comment]
btw, I just tried to uninstall ```npm uninstall @mui/x-date-pickers-pro``` and when I go to ```package-lock.json``` I still see this part:

```
"node_modules/@mui/x-date-pickers": {
            "version": "5.0.20",
            "resolved": "https://registry.npmjs.org/@mui/x-date-pickers/-/x-date-pickers-5.0.20.tgz",
            "integrity": "sha512-ERukSeHIoNLbI1C2XRhF9wRhqfsr+Q4B1SAw2ZlU7CWgcG8UBOxgqRKDEOVAIoSWL+DWT6GRuQjOKvj6UXZceA==",
            "peer": true,
            "dependencies": {
                "@babel/runtime": "^7.18.9",
                "@date-io/core": "^2.15.0",
                "@date-io/date-fns": "^2.15.0",
                "@date-io/dayjs": "^2.15.0",
                "@date-io/luxon": "^2.15.0",
                "@date-io/moment": "^2.15.0",
                "@mui/utils": "^5.10.3",
                "@types/react-transition-group": "^4.4.5",
                "clsx": "^1.2.1",
                "prop-types": "^15.7.2",
                "react-transition-group": "^4.4.5",
                "rifm": "^0.12.1"
            },
...
```

Maybe something else has dependencies on it?

**Comment by jamesDin** [comment]
Btw, I'm using ```@devexpress/dx-react-scheduler-material-ui@4.0.3```
and somehow I uninstalled ```@mui/x-date-pickers-pro``` and installed it again, and now I see that the ```@devexpress/dx-react-scheduler-material-ui@4.0.3``` has a dependency that it installed before and now it fails:

```npm
npm ERR! While resolving: @devexpress/dx-react-scheduler-material-ui@4.0.3
npm ERR! Found: @mui/x-date-pickers@6.2.1
npm ERR! node_modules/@mui/x-date-pickers
npm ERR!   @mui/x-date-pickers@"^6.2.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @mui/x-date-pickers@"^5.0.15" from @devexpress/dx-react-scheduler-material-ui@4.0.3
npm ERR! node_modules/@devexpress/dx-react-scheduler-material-ui
npm ERR!   @devexpress/dx-react-scheduler-material-ui@"4.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @mui/x-date-pickers@5.0.20
npm ERR! node_modules/@mui/x-date-pickers
npm ERR!   peer @mui/x-date-pickers@"^5.0.15" from @devexpress/dx-react-scheduler-material-ui@4.0.3
npm ERR!   node_modules/@devexpress/dx-react-scheduler-material-ui
npm ERR!     @devexpress/dx-react-scheduler-material-ui@"4.0.3" from the root project
```

only when I delete ```package-lock.json``` and run ```npm install``` again, the error disappears but again, I don't find the ```heIL``` file :-(

So... why only the ```heIL``` is ruined ?? Why not other languages?? :-D

**Comment by jamesDin** [comment]
Well, after playing a lot with the packages, I guess somehow this ```@devexpress/dx-react-scheduler-material-ui@4.0.3``` is making all the mess.  If I remove it, all is working well and I can see this ```heIL```.
Thank you for your help and guidelines :-)

**Comment by LukasTy** [comment]
Yes, your root cause was the `@devexpress/dx-react-scheduler-material-ui@4.0.3`, because as you've shown in the error—it expects a peer dependency of the pickers v5. So, you either have to install it or this package might not function as expected.
Given your case, I'd say, that the safest bet would be to either ditch this `devexpress` dependency if you can and want to use pickers v6, or stick with v5 pickers until `devexpress` releases a version supporting v6. 🤔
