### ISSUE TITLE
[data grid] Adding border to grid main element causes infinite rerender

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#8737]
Demo: https://codesandbox.io/s/data-grid-community-forked-3ctumy

- flex container
- border on the `.MuiDataGrid-main`
- container height so big that the table doesn't have a vertical scroll

(this one can be fixed by moving the border from main container element to root)

_Originally posted by @Deraen in https://github.com/mui/mui-x/issues/8447#issuecomment-1491813888_

**Comment by cherniavskii** [comment]
I cannot reproduce it in v5: https://codesandbox.io/s/data-grid-community-forked-7rtqzc?file=/src/App.tsx

**Comment by cherniavskii** [comment]
https://github.com/mui/mui-x/pull/8577 fixes it, but with a side-effect of horizontal scroll bar:
https://codesandbox.io/s/data-grid-community-forked-b8d17d


<img width="780" src="https://user-images.githubusercontent.com/13808724/233984969-a724e41f-f906-48ed-827e-cd536be0f368.png">

**Comment by lroos** [comment]
I've run into a related issue with the upgrade to v6 - the horizontal scrollbar appears while scrolling the list. I forked a demo sandbox here to illustrate. 
https://codesandbox.io/s/sparkling-waterfall-3sdhkk?file=/demo.tsx 
Only seems to happen when 

- border on `.MuiDataGrid-main`
- at least 1 column is has `flex: 1`

Also if you set the Box to `display: 'flex'` then the whole grid slowly grows horizontally, as shown in #8447 which is trippy.

**Comment by Luv-m** [comment]
Hello :), 



> Also if you set the Box to `display: 'flex'` then the whole grid slowly grows horizontally, as shown in #8447 which is trippy.

I still see this issue in 6.8.0. Is your fix going to go in the next release @cherniavskii ?

**Comment by adarshmohan-vegapay** [comment]
Hey, this issue is reproducible on v6.18.5.
