### ISSUE TITLE
[docs] error in minDateTime prop documentation

### ISSUE THREAD

**Issue by LMott** [mui/mui-x#8743]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-date-pickers/validation/

### Kind of issue

Other

### Issue description

Word change needed in statement:

"Minimum and maximum date time
The minDateTime prop prevents the selection of all values _after_ props.minDateTime."

Should say "all values _before_ props.minDateTime'

**Comment by LukasTy** [comment]
Thank you for having a keen eye! 🙏 
Maybe you'd be interested in fixing it and creating a PR? 🤔
