### ISSUE TITLE
[question] onRowSelectionModelChange only selects last item in the list on every page except the first one

### ISSUE THREAD

**Issue by KarloStarcevicGenerali** [mui/mui-x#8749]
### Order ID or Support key 💳 (optional)

60125

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Rough explanation
MuiDatagridPro is server sided.
Every time page is changed a new request is sent and table is filled with new data with specific page parameter and size parameter.
While selecting all rows on the first page, all of the rows are selected.
While selecting all rows on the second page and any other page, only last row is selected (check pictures).
Manual selection of every row works normally.
Problem seems to be there only if I use select all checkbox on any other page than the first one.
![selectallpageone](https://user-images.githubusercontent.com/114663611/234263475-e245b6e0-9c77-44fc-9af5-06b83cf2c676.png)
![selectallpagetwo](https://user-images.githubusercontent.com/114663611/234263490-8ad207e7-3cf7-4eed-9bcc-0ea3f26d7c42.png)

### **CODE DETAILS:**
While using " onRowSelectionModelChange={(id) => onRowsSelectionHandler(id)}" I take the object and send it to the function called "onRowsSelectionHandler that takes that object.

After that I have a empty array which will take the id's that are selected if they match the row.id from rowData.
rowData is just an object that has all the row data.

let selectedRowsData = []; **//empty array that will get filled with ids that are selected**
  const onRowsSelectionHandler = (ids) => { **//function that takes ids (object from onRowSelectionModelChange)**
    console.log("IDS: ", ids); //just console logging ids
    selectedRowsData = ids.map((id) => { //mapping out data to array if they fit the right id (worked before)
      rowData.find((row) => row.id === id);
    });
  };

Example of rowData:
if (items && items.content && items.content.length !== 0) { //checks if items exists in case I get undefined..
    rowData = items.content.map((e) => { //maps out e object (items.content)
      return {
        id: e.id,
        username: e.username,
        caseType: e.caseType,
        created: e.created,
        updated: e.updated,
        status: e.status,
        message: e.message,
        priority: e.priority,
        mainDoc: e.mainDoc,
        action: e.action,
      };
    });
    totalElements = items.totalElements;
  }

This code worked before and suddenly stopped.
Is this due to some update?
I have read the documentation and I feel like I am missing something.
Also I can not find any fix for this online.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 Google chrome / Edge
  Output from `npx @mui/envinfo`

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base:  5.0.0-alpha.101
    @mui/core-downloads-tracker:  5.10.9
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.9 => 5.10.9
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system:  5.10.9
    @mui/types:  7.2.0
    @mui/utils:  5.11.13
    @mui/x-data-grid: ^5.17.7 => 5.17.24
    @mui/x-data-grid-pro: ^6.0.3 => 6.0.3
    @mui/x-license-pro:  6.0.3
    @types/react: ^18.0.26 => 18.0.26
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
```
</details>

**Comment by KarloStarcevicGenerali** [comment]
> I can't see how you're passing the value to the `rowSelectionModel` prop. Could you provide a CodeSandbox with a minimal reproduction? You can use [this template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) as starting point.

It seems like the issue really was the "checkboxSelectionVisibleOnly={true}" part.
It works now and selection is working perfectly.

**Comment by wcao226** [comment]
I am facing the same issue and want to know what solution you had for your issue.
