### ISSUE TITLE
DataGrid Pro Horizontal Scroll issue

### ISSUE THREAD

**Issue by jimidoshi** [mui/mui-x#8750]
I am facing issue with DataGrid pro is when the number of columns exceeds screen width, last few columns are not visible.

To fix this problem, I have tried adding style maxWidth to 3000px and it is not applicable. If I set style width to 3000px, then columns are visible but not looks good for the table having less number of columns.

```
import { DataGridPro} from '@mui/x-data-grid-pro';

<div style={{maxWidth: '3000px'}}>
        <DataGridPro
          autoHeight
          rows={rows} 
          columns={columns}
          getRowId={(row) => row._id}
          checkboxSelection
          disableSelectionOnClick
         />
</div>
```

Here I attached video link for reference
https://www.awesomescreenshot.com/video/16448683?key=f991b77508f3e1b6469bf5a903770fe0

**Comment by yaredtsy** [comment]
hey @jimidoshi 

It is difficult to determine why it is not working without examining the code. Have you tried adding `overflow: auto` to the `DataGridPro`?

```jsx
<div style={{width: '100%'}}>
    <DataGridPro
          sx={{overflow:'auto'}}
          autoHeight
          rows={rows} 
          columns={columns}
          getRowId={(row) => row._id}
          checkboxSelection
          disableSelectionOnClick
     />
</div>
```

**Comment by jimidoshi** [comment]
Hello @yaredtsy 
Yes. I have tried it but it is not working
