### ISSUE TITLE
[pickers] DateRangePicker doesn't work as in docs

### ISSUE THREAD

**Issue by suenot** [mui/mui-x#8751]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

- Copy code of components in this https://mui.com/x/react-date-pickers/date-range-picker/#use-a-single-input-field
```
import * as React from 'react';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { DateRangePicker } from '@mui/x-date-pickers-pro/DateRangePicker';
import { SingleInputDateRangeField } from '@mui/x-date-pickers-pro/SingleInputDateRangeField';
import { DemoContainer } from '@mui/x-date-pickers/internals/demo';

export default function SingleInputDateRangePicker() {
  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DemoContainer components={['SingleInputDateRangeField']}>
        <DateRangePicker slots={{ field: SingleInputDateRangeField }} />
      </DemoContainer>
    </LocalizationProvider>
  );
}
```
- Import component in my project:

### Current behavior 😯

Error: 
```
Server Error
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/root/fbot/denis/centrum/centrum-nextjs/node_modules/ (mui/x-date-pickers/internals/demo/index.js (1)
Object.compileFunction
node:vm (360:18)
wrapSafe
node:internal/modules/cjs/loader (1119:15)
Module._compile
node:internal/modules/cjs/loader (1155:27)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1245:10)
Module.load
node:internal/modules/cjs/loader (1069:32)
Function.Module._load
node:internal/modules/cjs/loader (904:12)
Module.require
node:internal/modules/cjs/loader (1093:19)
```

### Expected behavior 🤔

Renering components without errors.

### Context 🔦

Problem in `import { DemoContainer } from '@mui/x-date-pickers/internals/demo';`

I tried to create my own DemoContainer
```
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { DateRangePicker } from '@mui/x-date-pickers-pro/DateRangePicker';
import { SingleInputDateRangeField } from '@mui/x-date-pickers-pro/SingleInputDateRangeField';
// import { DemoContainer } from '@mui/x-date-pickers/internals/demo';

const DemoContainer = () => <></>;

export default function SingleInputDateRangePicker() {
  return (
    <>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DemoContainer components={['SingleInputDateRangeField']}>
          <DateRangePicker slots={{ field: SingleInputDateRangeField }} />
        </DemoContainer>
      </LocalizationProvider>
    </>
  );
}
```

In this case no errors, but component not rendering also.

### Your environment 🌎

  "dependencies": {
    "@deep-foundation/store": "^0.0.18",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/lab": "^5.0.0-alpha.127",
    "@mui/material": "^5.12.1",
    "@mui/styled-engine-sc": "^5.12.0",
    "@mui/x-date-pickers": "^6.2.1",
    "@mui/x-date-pickers-pro": "^6.2.1",
    "@svgr/webpack": "^7.0.0",
    "bootstrap": "^5.3.0-alpha3",
    "dayjs": "^1.11.7",
    "moment": "^2.29.4",
    "next": "13.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sass": "^1.62.0",
    "styled-components": "^5.3.10"
  },

- node v16.19.1
- npm 8.19.3

**Comment by LukasTy** [comment]
Hello @suenot 
The `DemoContainer` and `DemoItem` components are in examples only for the documentation examples layout/styling purposes, they serve no functional meaning. You can safely remove them from your code and use your own preferred way of controlling spacing and layout. 😉 
Does it solve your problem? Or are there any other problems?

**Comment by suenot** [comment]
Thank you, it helped me.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/1426876/234319951-b264eafe-30cc-4c0c-a804-5efab91050ec.png">

```
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { DateRangePicker } from '@mui/x-date-pickers-pro/DateRangePicker';
import { SingleInputDateRangeField } from '@mui/x-date-pickers-pro/SingleInputDateRangeField';
// import { DemoContainer } from '@mui/x-date-pickers/internals/demo';

export default function SingleInputDateRangePicker() {
  return (
    <>
      <div>SingleInputDateRangePicker</div>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        {/* <DemoContainer components={['SingleInputDateRangeField']}> */}
          <DateRangePicker slots={{ field: SingleInputDateRangeField }} />
        {/* </DemoContainer> */}
      </LocalizationProvider>
    </>
  );
}

```

**Comment by LukasTy** [comment]
I'm closing this issue as it seems that the problematic case has been clarified. 👌
