### ISSUE TITLE
Apply the Filter Model Manually to a Row

### ISSUE THREAD

**Issue by jmsims2** [mui/mui-x#8755]
### Order ID or Support key 💳 (optional)

62675

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have an infinite scroll grid with server side filtering. We also have some editable cells in our grid. When a user edits a cell, we want to check if that row meets the filter criteria and if not, remove it. The simplest option was to refetch the pages of data where the row was, but this ultimately proved to be not a great user experience and ended with a lot of refetching. Instead, we'd like to check client side if the row should be filtered out or not.

My initial thought was to take advantage of the `getApplyFilterFn` for each column included in the filter and then apply each function to the row in question and then return a result to either keep or remove the row. If we need to remove it, we remove it from our react-query cache. This all initially worked great, however I'm noticing that I wasn't understanding how the `getApplyFilterFn` actually worked. 

For starters, here is what I had so far:
```
const shouldFilterRow = (row: GridCellParams) => {
    const filters = apiRef.current.state.filter.filterModel;

    const columnFilterFunctions = filters.items
      .map((item) => {
        const colDef = apiRef.current.getColumn(item.field);
        return colDef?.filterOperators
          ?.find((op) => op.value === item.operator)
          ?.getApplyFilterFn(item, colDef);
      })
      .filter(Boolean);

    const result = columnFilterFunctions.map((fn) => fn?.(row));

    return filters.logicOperator === 'or'
      ? result.some((r) => r)
      : result.every((r) => r);
  };
```

Our grid initially loads where a column called `STATUS` is not `DELETE`. When I edit a row to be status = `DELETE`, the function above returns true and we remove the record. 

Where this breaks down is when I change the filter to be `STATUS` is `DELETE`.  I edit a cell from `DELETE` to `AVAILABLE` instead and the function above returns false because `DELETE` === `AVAILABLE` is false.

So my question is, is there any way to take advantage of the filter functionality locally to determine if a row does/does not apply to the current filter model without turning on client side filtering? Or a semi-related question, how does the grid manage this internally to determine if a row should show or not? I couldn't really follow how the differences between the various operator functions were handling when it came to showing/hiding a given row.

Thanks for any help!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.5
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.4.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.121 
    @mui/core-downloads-tracker:  5.11.13 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.13 => 5.11.13 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.13 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-data-grid:  6.0.3 
    @mui/x-data-grid-pro: ^6.0.3 => 6.0.3 
    @mui/x-date-pickers: ^5.0.18 => 5.0.18 
    @mui/x-license-pro:  6.0.3 
    @types/react: 18.0.25 => 18.0.25 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ~4.8.2 => 4.8.4 
```
</details>

**Comment by yaredtsy** [comment]
I had the same problem, and the way I approached it was to toggle from 'server' mode to 'client' mode when the user starts editing. Then, I change it back to 'server' mode when the user finishes editing. This way, I do not have to handle the filter logic myself.

Demo: https://codesandbox.io/s/nostalgic-galois-5so678?file=/demo.tsx:991-1380

**Comment by jmsims2** [comment]
@m4theushw Thanks for pointing me to those files, super helpful and was able to get it working.

@yaredtsy Interesting approach, appreciate the response!
