### ISSUE TITLE
[DataGrid] Pagination props are ignored on DataGridPremium

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#8756]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/intelligent-fire-pxi6lz?file=/demo.tsx

Steps:
1. Look on the data grid on top, which is rendered with a `<DataGrid />`
2. Look the one the bottom, which is rendered `<DataGridPremium />`
3. You can try with other pagination props, none of them seem to be working

### Current behavior 😯

The Data Grid Premium seems to ignore the pagination props. I tried with initialState, paginationModel and autoPageSize.

### Expected behavior 🤔

Pagination props are respected on DataGridPremium. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Pagination is enabled by default only in the Community package - see https://mui.com/x/react-data-grid/pagination/#size-of-the-page
For Pro and Premium packages, you have to explicitly enable it using the `pagination` prop:
https://codesandbox.io/s/frosty-sanne-s8qplz
