### ISSUE TITLE
[Accessibility] Consider changing the aria label for the delete button in Filters to "Clear Filters"

### ISSUE THREAD

**Issue by Stuthineal** [mui/mui-x#8757]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Screen Readers announce the button to clear filters as "Delete Button". It would be helpful if this is read out as "Clear Filters" instead. 

### Examples 🌈

Start NVDA Screen reader. Click on Filters in the given example and tab to the Delete button
https://mui.com/x/react-data-grid/filtering/
![image](https://user-images.githubusercontent.com/47873381/234339982-65ff5ed0-ae76-4f93-9253-7cf6502313cb.png)

### Motivation 🔦

Announcing the button as the "Delete Button" could be misleading and users may assume that the data from the table is being deleted. It may be more helpful to announce it as "Clear Filters" instead.

**Comment by alexfauquette** [comment]
I don't know if it is safe to modify this translation since English aria might be used by users to implement tests. But you can customize this text in your project with the [localeText](https://mui.com/x/react-data-grid/localization/) key `filterPanelDeleteIconLabel`

**Comment by Stuthineal** [comment]
ok that makes sense. I will update it in our project. Thank you @alexfauquette and @m4theushw
