### ISSUE TITLE
[question] [DataGridPro]About Sorting on iPad

### ISSUE THREAD

**Issue by e12879** [mui/mui-x#8762]
### Order ID or Support key 💳 (optional)

58043

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am using mui/x-data-grid-pro.
Please tell me about the sort function of DataGridPro on iPad (Safari).
Android tablet (Google Chrome) sorts with 1Tap.
On the other hand, iPad sorts with 2Tap. Is this the specification?
If possible, I would like to sort with 1Tap even on iPad (Safari). Is there a way?

supplementary explanation:
Column headers only have sort functionality.

### Your environment 🌎

My environment is as follows.
■npx @mui/envinfo
  System:
   OS: Windows 10 10.0.19044
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)

 

■Actual machine environment in use
　　Ipad 6 iOS：15.7.1
　　iPad Pro iOS：16.3.1
　　Galaxy Tab A8：Android11

**Comment by cherniavskii** [comment]
I can reproduce this on iOS simulator:


https://user-images.githubusercontent.com/13808724/235095380-46f05c73-ac28-4e4b-8da1-b73964b39e13.mov

**Comment by cherniavskii** [comment]
Apparently, this is how iOS handles the elements with `:hover`:
https://humanwhocodes.com/blog/2012/07/05/ios-has-a-hover-problem/
https://css-tricks.com/annoying-mobile-double-tap-link-issue/

**Comment by cherniavskii** [comment]
I'm not sure there's an easy fix here. To make sorting work on the first click, we have to get rid of hover styles on mobile, therefore it will be impossible to open the column menu (column menu icon is only showed on hover)

**Comment by e12879** [comment]
@cherniavskii 
thank you for your reply.
Do you have any plans to fix it in DataGridPro?
If it doesn't, I'm aware that I need to remove the hover.

**Comment by cherniavskii** [comment]
@e12879 We do not have plans for a fix yet, as it's unclear how to make the column menu work without hover.

cc @gerdadesign Maybe we can reconsider how column headers work on touch devices? E.g. show them in "hovered" state by default, so that you always see the icons in the column headers, as well as resize handles?

**Comment by romgrk** [comment]
An alternative I sometimes see on mobile is to use a long press to replace the hover trigger.

**Comment by gerdadesign** [comment]
+1 for showing on mobile what is typically reserved for hover on desktop.
