### ISSUE TITLE
[pickers] Wrong color of the number when selected date is disabled

### ISSUE THREAD

**Issue by Nic-S** [mui/mui-x#8763]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://stackblitz.com/edit/react-brtvzx?file=demo.tsx

### Current behavior 😯

The number of the date selected in the past with the past disabled takes the colour of disabled instead of selected.

### Expected behavior 🤔

The number of the date selected in the past, must have the colour of the selection instead of disabled.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
If I understand correctly, in the following screen shot the 23 should be white instead of gray
![image](https://user-images.githubusercontent.com/45398769/234591479-73a781ef-9b22-4a03-afd9-36a60ed14062.png)

**Comment by Nic-S** [comment]
> https://stackblitz.com/edit/react-brtvzx?file=demo.tsx

yes, here are some screens from the codeSandbox live example:

Here I have changed the primary colour in the theme to make the problem more apparent.
<img width="822" alt="Screenshot 2023-04-26 alle 15 36 24" src="https://user-images.githubusercontent.com/18029425/234593314-8df69ab6-7dc5-4de1-bdbe-d87ed0e73b53.png">

<img width="816" alt="Screenshot 2023-04-26 alle 15 36 34" src="https://user-images.githubusercontent.com/18029425/234593348-793d2d2e-e386-40e4-a698-e56c8564170b.png">

<img width="829" alt="Screenshot 2023-04-26 alle 15 36 42" src="https://user-images.githubusercontent.com/18029425/234593402-a0ae9472-712f-4c80-b70a-81d405c0f514.png">
