### ISSUE TITLE
[Datagrid]: After I have hidden all the columns from the menu, I cannot make any of them reappear.

### ISSUE THREAD

**Issue by Nic-S** [mui/mui-x#8767]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/fervent-aryabhata-6f245u

Steps:
1. click on menu of one column
2. click on hide all column
3. click outside for close menu

<img width="1677" alt="Screenshot 2023-04-26 alle 15 27 00" src="https://user-images.githubusercontent.com/18029425/234591029-4ba77803-9b19-4859-ba9a-29cb69be6d4d.png">

<img width="1676" alt="Screenshot 2023-04-26 alle 15 27 15" src="https://user-images.githubusercontent.com/18029425/234591119-1644f7ce-ca5e-4f75-9b8e-6358f3f0c335.png">

### Context 🔦

A possible solution could be how it is handled when hiding the single column, if it is the last column the button is disabled; then also within the column visibility menu it could be handled that if it is the last one the switch is disabled and if instead the "hideAll" button is clicked it can be an heuristic that the first column is not hidden.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
One way to avoid this is by using [`slotProps.columnsPanel.getTogglableColumns`](https://mui.com/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel) function to disable hiding of one or more columns.

```tsx
<DataGrid
  {...otherProps}
  slotProps={{
    columnsPanel: {
      getTogglableColumns: () => ['age', 'desk'] // only allow toggling `age` and `desk` columns
    }
  }}
/>
```

I tried it in the provided codesandbox, here's the updated version: https://codesandbox.io/s/jolly-varahamihira-zenlpe

Does this handle your use-case?

**Comment by Nic-S** [comment]
yes it can work, but it is a terrible DX as you have to declare all columns except one and all this just to avoid a very strange behaviour which to me honestly seems to be a bug.

**Comment by TonyBrobston** [comment]
We are also experiencing this issue. 

It is interesting that when you hide columns one-by-one using the "Hide column" on the column header, when you get to the last visible column, "Hide column" is disabled. This seems to imply that the developer didn't intend for all columns to be hidden.
<img width="278" alt="image" src="https://github.com/mui/mui-x/assets/4724577/efc1ea8a-4bd1-4fb4-a628-97e06abdbc1d">

**Comment by Nic-S** [comment]
[MBilalShafi](https://github.com/MBilalShafi)
so to recap:

1. by hiding the column punctually, the last one is disabled

<img width="532" alt="Screenshot 2023-10-03 alle 16 25 07" src="https://github.com/mui/mui-x/assets/18029425/d2a42db2-041b-41db-b72f-709d70baf511">

2. with the switch instead no you can hide the last one as well

<img width="394" alt="Screenshot 2023-10-03 alle 16 26 34" src="https://github.com/mui/mui-x/assets/18029425/aa1c7764-6ceb-4200-8aba-7e9a4bca3097">

3. with hideAll the same but you can in case remove it easily.

I believe in general it's a bug that once the columns are hidden there is no possibility to go back, but if at least the usual logic of point 1 is implemented also in point 2 for me we will be well on our way, since the buttone is possible to remove it through the defaultProp of the theme.

**Comment by DanailH** [comment]
@Nic-S Have you considered adding the columns menu button via the toolbar? I'm not sure what the use case is to hide all columns and then try and make them appear but if you expect such interactions I would suggest utilizing the toolbar. 

https://mui.com/x/react-data-grid/components/#toolbar

**Comment by MBilalShafi** [comment]
Totally agree with adding a toolbar if such situations are likely. 👍 

> but it is a terrible DX as you have to declare all columns except one and all this just to avoid a very strange behaviour which to me honestly seems to be a bug

Have you looked at the API of [slotProps.columnsPanel.getTogglableColumns](https://mui.com/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel), you can avoid declaring all columns except one by doing something like:

```tsx
const theColumnIWantToBeNotTogglable = 'age';

const getTogglableColumns = (columns: GridColDef[]) => columns.filter(field => field !== theColumnIWantToBeNotTogglable);
```

So you have both choices, if there are a few columns that are togglable, you can hardcode them like `getTogglableColumns: () => ['age', 'desk']` but if there are a few columns that are **_not_** togglable, you can use the argument `columns` and just filter out those you don't want to be togglable.

Does that make sense?

**Comment by Nic-S** [comment]
Hello everyone, I am resuming this issue without creating another one.

Even in version 7 we have the same problem.
If I hide all the columns from the panel that opens by clicking "manage columns" and do not use the toolbar, there is no way to return to a usable version of the grid.

<img width="875" alt="Screenshot 2024-07-11 alle 13 06 28" src="https://github.com/mui/mui-x/assets/18029425/577dd998-4591-4316-8805-ac72b9b2e15b">
<img width="834" alt="Screenshot 2024-07-11 alle 13 06 37" src="https://github.com/mui/mui-x/assets/18029425/7241718d-f357-4e40-a17e-54d51255166d">
<img width="861" alt="Screenshot 2024-07-11 alle 13 06 45" src="https://github.com/mui/mui-x/assets/18029425/43c59853-41a3-4f70-a83b-60736f4933e7">


There is also an inconsistency, as instead if I use the "Hide column" button on the panel it is disabled for the last column.
In my opinion, this behaviour should be consistent between the two ways of hiding columns.

<img width="848" alt="Screenshot 2024-07-11 alle 13 06 56" src="https://github.com/mui/mui-x/assets/18029425/5ed5d734-2a6a-44d5-98cf-f0f8a4d5e919">
<img width="956" alt="Screenshot 2024-07-11 alle 13 07 11" src="https://github.com/mui/mui-x/assets/18029425/f620db27-7476-47ca-811d-fd820e9314e1">

**Comment by romgrk** [comment]
Have you looked at the toolbar component? It sounds like it does what you want.

https://mui.com/x/react-data-grid/components/#toolbar

**Comment by konrazem** [comment]
You can create button in toolbar however there is one method only to open it api.showColumnMenu(field) where you need to give a field of column that is visible (wasn't hidden). The problems is I need to find such column field and if all are hidden I cannot open it 😔
Can you just make this parameter optional? Panel is attached always to the left upper corner as I see so why you need this field? 🤔

```typescript
// gridColumnMenuApi.d.ts'
export interface GridColumnMenuApi {
    /**
     * Display the column menu under the `field` column.
     * @param {string} field The column to display the menu.
     */
    showColumnMenu: (field?: string) => void; // <------- (?)
    /**
     * Hides the column menu that is open.
     */
    hideColumnMenu: () => void;
    /**
     * Toggles the column menu under the `field` column.
     * @param {string} field The field name to toggle the column menu.
     */
    toggleColumnMenu: (field: string) => void;
}
```
