### ISSUE TITLE
[data grid] CSV Export does not include columnGrouping

### ISSUE THREAD

**Issue by kaela** [mui/mui-x#8768]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

- `columnGrouping` should be displayed in the CSV export (e.g., "Full Name" from the example below should display above "First Name" and "Last Name")
- This feature is available by default for the Excel export:  [premium codesandbox with excel export](https://codesandbox.io/s/cool-hill-6ssuco?file=/demo.tsx:1031-1075) _(note that the column group name is available with Excel export and not with CSV export)_

### Examples 🌈

1. Go to [pro codesandbox with csv export only](https://codesandbox.io/s/polished-firefly-hg9z54?file=/demo.tsx)
2. Select 'Export'
3. See that "Full Name" is not included in the CSV export

===================
- Docs for Export: https://mui.com/x/react-data-grid/export/
- Docs for `columnGrouping`: https://mui.com/x/react-data-grid/column-groups/#define-column-groups

### Motivation 🔦

The CSV should match what is displayed in the UX

### Order ID 💳 (optional)

55283

**Comment by saikumarf9** [comment]
Any temporary work around for this?
