### ISSUE TITLE
[pickers] TimePicker's minutesStep prop is not working (v6)

### ISSUE THREAD

**Issue by xdebbie** [mui/mui-x#8774]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/clever-ishizaka-d3mljd?file=/demo.tsx

Steps:
1. Change the time input to any minute you like. It will go from 00 to 59 when it should be blocked to work only on 30-minute steps.

### Current behavior 😯

The `minutesStep` prop used to work fine on v5, and now after upgrading to v6 it seems to have no effect on the TimePicker. With a `minutesStep={30}` prop the expected behaviour would be for the picker to only accept the minutes `00` and `30`, but I can keep on moving all the way from `00`, `01`, `02` ... to `59`, with both the keyboard input and the arrows.

v6 demo (not working!): https://codesandbox.io/s/clever-ishizaka-d3mljd?file=/demo.tsx
v5 demo (working): https://codesandbox.io/s/quizzical-architecture-ypcmpt?file=/demo.tsx

### Expected behavior 🤔

The TimePicker @ v6 should only accept the minute values as set by the `minutesStep` prop.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.0
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: 112.0.1722.58
    Firefox: Not Found
    Safari: 16.1
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base: ^5.0.0-alpha.127 => 5.0.0-alpha.127 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/material: ^5.6.0 => 5.8.5 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.5 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.0 
    @mui/x-data-grid-pro: ^5.17.14 => 5.17.14 
    @mui/x-date-pickers:  6.2.1 
    @mui/x-date-pickers-pro: ^6.0.0 => 6.2.1 
    @mui/x-license-pro:  5.17.12 
    @types/react: ^18.0.15 => 18.0.15 
    react: ^18.0.0 => 18.2.0 
    react-dom: ^18.0.0 => 18.2.0 
    typescript: ^4.6.3 => 4.7.4 
```
</details>

**Comment by LukasTy** [comment]
Thank you for opening this issue! 🙏 
It indeed seems that this is a regression and in v6 we should at least get the same behavior—an error in case of value not conforming to the `minuteStep` validation.
