### ISSUE TITLE
[pickers] Localization provider (PtBR) is not translating correctly

### ISSUE THREAD

**Issue by Tiagofsant** [mui/mui-x#8787]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

# As you can see in the image below, the calendar doesn't return the translated months.
<br></br>

![image](https://user-images.githubusercontent.com/79919984/234994207-4d1e7fae-e1ee-46a9-9491-56aad40bfdc5.png)

<br></br>

# I also send the source code used to return the calendar

<br></br>

![image](https://user-images.githubusercontent.com/79919984/234994638-336ab7ab-75e5-4f67-9ebf-1bc8a8901f2f.png)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
In your code example, you are never importing the `dayjs` locale

**Comment by Tiagofsant** [comment]
Really....

Issue solved! I imported the
 <b> "dayjs/locale/pt-br" </b> and it solved. 😎
 
 Thank you very much for your promptness and speed in meeting this demand! 😁
