### ISSUE TITLE
[pickers] DatePicker doesn't take into account formats with one digit days [daysjs-regression]

### ISSUE THREAD

**Issue by david-ic3** [mui/mui-x#8820]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Check example in sandbox 

https://codesandbox.io/s/currying-smoke-wqu8d1?file=/demo.tsx

or : 

```
export default function DatePickerValue() {

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DemoContainer components={['DatePicker', 'DatePicker']}>
        <DatePicker label="Uncontrolled picker" format={"D MMMM YYYY"} defaultValue={dayjs('2022-04-1')} />
      </DemoContainer>
    </LocalizationProvider>
  );
}

```

### Current behavior 😯

Single days are show with 2 digits when using D for day formatting, "01"

### Expected behavior 🤔

Single days are show with 1 digits , "1"

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

#19458

**Comment by LukasTy** [comment]
Hello @david-ic3 
This was a recent change done to avoid the issue of having unwanted invisible characters in the value.
This [can be configured](https://mui.com/x/react-date-pickers/adapters-locale/#respect-leading-zeros-in-fields) if you are fine with having value containing invisible characters (i.e. you are not using the `FormData` directly, but rely on the value controlled through onChange).

TL.DR.: Adding `slotProps={{ field: { shouldRespectLeadingZeros: true } }}` returns the previous behavior of respecting the zeros in the format.

Does it solve your problem? 🤔

**Comment by david-ic3** [comment]
Works, strange that is not the default behaviour.  merci

**Comment by LukasTy** [comment]
> Works, strange that is not the default behaviour. merci

It is not default, because in order to achieve it we need to introduce extra characters, which do impact users that would expect the components to work correctly without being controlled (i.e. by using the `FormData` API).
Going with the suggested default goes against how you would expect native input to behave.
We tried making it more transparent from native components PoV. 🤔
