### ISSUE TITLE
TimeField - minutesStep

### ISSUE THREAD

**Issue by JasonColeyNZ** [mui/mui-x#8824]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/jolly-joliot-6jgif8

Steps:

1.Make a TimeField
2.Set minutesStep={15}
3. select a time using the up down arrows

### Current behavior 😯

At present the TimeField shows the border in red if for instance the time isn't acceptable, i.e. if I have set the minutesStep to 15 and I have a minute number from 1-14.

Okay, this works fine, but why am I having to press the up/down buttons in between the valid numbers, why isn't the time flicking between the allowed numbers? 

Seems like this really isn't user friendly in this situation?

### Expected behavior 🤔

Why not jump between the increments as set in minutesStep??

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Thank you for opening the issue @JasonColeyNZ.
It has already been reported and is resolved via https://github.com/mui/mui-x/pull/8794.
It will be shipped with the next release. 😉
