### ISSUE TITLE
[DataGridPro] Multi-column filtering breaks when changing filter value of the second filter (version 4.x)

### ISSUE THREAD

**Issue by vongruenigen** [mui/mui-x#8831]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Go to the [multi-filtering section of the v4 documentation of the DataGrid](https://v4.mui.com/components/data-grid/filtering/#multi-column-filtering) and do the following steps:

1. Delete all the preconfigured filters.
2. Add a filter `Commodity contains "rice"`.
3. Note down the values of the `Desk` column of the first two rows shown.
4. Add a filter `Desk contains "<your-first-noted-value>"`.
5. Close the filter panel.
6. Open the filter panel again and replace the filter value for `Desk` with the second value you noted down earlier.

### Current behavior 😯

Currently it works the first time when a second filter is added, but as soon as the filter value for the second filter is changed the filtering doesn't work anymore and instead just shows an empty data grid.

I also recorded the behaviour in a video, you can download that video [here](https://www.dropbox.com/s/0x8d49ze8fbx08e/Screen%20Recording%202023-05-02%20at%2015.44.33.mov?dl=0).

### Expected behavior 🤔

It should also filter the data correctly when changing the filter value of the second filter.

### Context 🔦

Just trying to get multi-column filtering to work in 4.x. The problem is not present anymore in 5.x, but we currently can't upgrade to 5.x since we're still using `material-ui` version 4.x

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/path/to/my/local/project/node_modules/.bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: Not Found
    Firefox: 110.0
    Safari: 15.3
  npmPackages:
    @mui/x-data-grid-pro: ^4.0.2 => 4.0.2 
    @mui/x-license-pro: ^4.0.2 => 4.0.2 
    @types/react: 17.0.0 => 17.0.0 
    react: 17.0.0 => 17.0.0 
    react-dom: 17.0.0 => 17.0.0 
    typescript: 4.9.5 => 4.9.5 
```
</details>

### Order ID or Support key 💳 (optional)

64623

**Comment by cherniavskii** [comment]
Hi @vongruenigen 
Unfortunately, we don't deliver updates for v4 anymore.
Since you cannot upgrade Material UI to v5, consider using both Material UI v4 and v5 following this guide: https://v5.mui.com/x/react-data-grid/migration-v4/#using-mui-core-v4-with-v5
Hope this helps!

**Comment by vongruenigen** [comment]
Hey @cherniavskii, thanks for the swift response, I'll check it out 👍
