### ISSUE TITLE
[pickers] module DateCalendar is not found

### ISSUE THREAD

**Issue by Mikmoal** [mui/mui-x#8841]
When i try to use DateCalendar i get an error: Module not found: Can't resolve '@mui/x-date-pickers/DateCalendar'
I already installed the dependencies.

`error - ./src/sections/calendar/calendar.js:20:0
Module not found: Can't resolve '@mui/x-date-pickers/DateCalendar'
  18 | import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
  19 | import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
> 20 | import { DateCalendar } from "@mui/x-date-pickers/DateCalendar";`

**Comment by Mikmoal** [comment]
Thanks i already fixed it uninstalling and then installing the x-date-pickers package ;)

**Comment by s1alpha** [comment]
I had this same problem.

Was fixed by a quick reinstallation. Not sure if this is a reoccurring issue?

**Comment by LukasTy** [comment]
> Was fixed by a quick reinstallation. Not sure if this is a reoccurring issue?

Did it happen after upgrading from v5 to v6?
There could be some problems with the installation process or lock file condition. 🤔 🤷

**Comment by swimnz** [comment]
> > Was fixed by a quick reinstallation. Not sure if this is a reoccurring issue?
> 
> Did it happen after upgrading from v5 to v6? There could be some problems with the installation process or lock file condition. 🤔 🤷

Yes, I was upgrading to v6
