### ISSUE TITLE
[DesktopDateTimePicker] Make extra non-space characters separating date and time values optional

### ISSUE THREAD

**Issue by davakos** [mui/mui-x#8843]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
Unable to get a stand-alone react-testing-library unit test running in CodeSandbox, but can describe basic test setup below.
Tests are using react-testing-library: https://testing-library.com/docs/react-testing-library/intro, versions:
```
@testing-library/react: 14.0.0
@testing-library/jest-dom: 5.16.5
```
I'm using a Luxon date adapter, versions:
```
@date-io/luxon: 2.16.1
luxon: 3.3.0
```

Steps (in test):
1. Render a DesktopDateTimePicker:
```
const DATE_FORMAT = "yyyy/LL/dd HH:mm";
const dt = DateTime.now();
render(<DesktopDateTimePicker label="Enter Date" defaultValue={dt.toUTC().toISO()} format={DATE_FORMAT} ampm={false} />);
```
2. Check for a form element in the DOM with the expected value:
```
screen.getByDisplayValue(dt.toFormat(DATE_FORMAT));
```

### Current behavior 😯

Test is unable to find a field in the DOM with the test value, example error:
```
TestingLibraryElementError: Unable to find an element with the display value: 2023/04/20 15:54.
```

A snippet of the DOM where this value was searched is logged to the console after this error.
I can see an element with the date/time value expected in the DOM output, but when I save this to a log file and open in the vi editor I see what appears to be additional non-whitespace characters between the date and time values:
```
"2023/04/20<2069> <2066>15:54"
```

### Expected behavior 🤔

User can control additional non-whitespace characters separating date and time values in DesktopDateTimePicker component, perhaps following:  https://github.com/mui/mui-x/issues/8243

### Context 🔦

Tests that passed in x-date-pickers v5 are now breaking in v6.
I have a large number of tests that check scenarios where date/time values are entered into form fields.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Used Chrome web browser on MacOS.

  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: Not Found
    npm: 9.6.5 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.63
```
</details>

**Comment by LukasTy** [comment]
Hello, thank you for opening this issue! 🙏 
Could you clarify the package version that you are using?
We have removed any unexpected white-space characters by default on v6.3.0 via https://github.com/mui/mui-x/pull/8527
Could you confirm if you still have this issue if you are using the latest package version?

**Comment by davakos** [comment]
Thank you for the quick response.
I am using the latest version of `@mui/x-date-pickers`, `6.3.0`.

Testing on all versions since 6.1.0 yield the same results:
expected in DOM:  `'2023/05/03 06:25'`
in DOM, not found by test (I think because of the additional characters around the space separating date from time fields): `value="2023/05/03<2069> <2066>06:25"`

I also see that placeholder=`"YYYY/MM/DD<2069> <2066>hh:mm"`, so it also has those additional characters.

In versions 6.1.0 and prior there was additional spacing around the date field separators, e.g.,
`"2023 / 05 / 03<2069> <2066>06:35"`
but this was addressed in 6.2.0 release via https://github.com/mui/mui-x/pull/8425.

Note: my runtime and testing locale is `en-us`. I was not passing this into the `<LocalizationProvider />` directly per the setup example for luxon here:
https://mui.com/x/react-date-pickers/getting-started/#setup-your-date-library-adapter

When I do add an `adapterLocale` attribute, I get the same results with the additional characters.
```
<LocalizationProvider dateAdapter={AdapterLuxon} adapterLocale="en-us">
  {children}
</LocalizationProvider>
```

**Comment by davakos** [comment]
I just noticed this comment from https://github.com/mui/mui-x/pull/8527/files#diff-caffa005c10972326cbfacd263f9931e9671dd821031675bafd26091a7ec2bafR165:
> Luxon is not able to respect the leading zeroes when using macro tokens (e.g: "DD"), so `shouldRespectLeadingZeros={true}` might lead to inconsistencies when using `AdapterLuxon`.

I am not using the `shouldRespectLeadingZeros` option.
The Luxon format I am using is: `"yyyy/LL/dd HH:mm"`
According to the [Luxon formatting table of tokens](https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens), I don't see that this should be adding extra characters between date and time values.

in my test I am using `DateTime.now().toFormat("yyyy/LL/dd HH:mm")` for the field value I am looking for, which does not introduce the additional characters between date+time values, e.g., `2023/04/20 15:54`.

**Comment by alexfauquette** [comment]
> We have removed any unexpected white-space characters by default on v6.3.0 via https://github.com/mui/mui-x/pull/8527

Seems two of them survived:
- One only about range pickers: https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts#L589
- This on is the problematic one: https://github.com/mui/mui-x/blob/master/packages/x-date-pickers-pro/src/internal/utils/valueManagers.ts#L84

I will add a fix

**Comment by alexfauquette** [comment]
No worries, it's a nice issue, when I saw `<2069> <2066>` I directly searched for `\u2069` in the code base

> I wrote a small wrapper function around DesktopDateTimePicker that will convert the value to a Luxon DateTime given a date string in ISO format.

Just to better understand how our components fit in your codebase: Are they specific reasons why manipulating dates as an ISO string instead of using the luxon date object in your codebase?

**Comment by davakos** [comment]
The preview works and resolves my issue! Thank you! 🎉 

Regarding my use of the DateTimePicker:
I have an application that requires date/time input in several web forms.
The app is backed by RESTful APIs that expect and return date-time data in ISO 8601 format (UTC time zone).
I am using Luxon for date translation between user time and UTC, but since dates are ISO 8601-formatted strings, I was passing these strings to the date/time picker and allowing the picker to handle the conversion to/from Luxon format.

Since v6 requires the value passed to DateTimePickers be an adapter format and I have a lot of pickers throughout the app, I decided that the quickest way to accomplish this (and a few other minor tasks) was with a small wrapper component around DateTimePicker that handles the translation. I could have also introduced a model that performs the translation between ISO and Luxon formats as middleware surrounding API calls, but thought the former approach kept the code closer to prior uses and would hopefully therefore reduce potential bugs and downstream changes.

**Comment by LukasTy** [comment]
Your solution sounds solid. 👌 
It's pretty common to have wrappers around more complex components of used libraries handling certain custom configurations in one place.
In MUI's case, there is the ability to provide default props via theme, but in your case, that would not be enough. 😃
