### ISSUE TITLE
Mutliple Edit bulk functionality using MUI datagrid with single save button

### ISSUE THREAD

**Issue by krishnachoudhary274** [mui/mui-x#8846]
Hi Team,

We are working on MUI datagrid where we are trying to implement bulk edit and delete functionality using MUI datagrid.
We don't see any reference so far for bulk crud operation. We are ready to opt pro and premium if this feature allows to do the buld edit and delete operation on a signle save operation.

Technical flow:

user selects the one or more checkbox and click on edit button.
User get allowed to edit the field on selected rows and click on save button.
once users clicks on save button, datagrid must have updated records.

**Comment by MBilalShafi** [comment]
Closing in favor of duplicate #8844

**Comment by krishnachoudhary274** [comment]
Can you please provide an update on this?
