### ISSUE TITLE
[pickers] AdapterDayjs Module not found 

### ISSUE THREAD

**Issue by rafshawn** [mui/mui-x#8849]
### Duplicates

    * [x]  I have searched the existing issues

### Latest version
 
    * [x]  I have tested the latest version

### Current behavior 😯

Error on compile, AdapterDayjs module not found, causing breaking issues.

### Context 🔦

Been having trouble with this module every time I compile. AdapterDayjs is not exported from the `@mui/x-date-pickers` module, even though its been imported. Tried searching up the issue and thought it might be an issue with dependency but I'm not entirely sure how to check whether I need to upgrade or downgrade anything. Tried uninstalling and reinstalling `x-date-pickers`

I get an import error:

    Attempted import error: 'AdapterDayjs' is not exported from '@mui/x-date-pickers' (imported as 'AdapterDayjs').
Which then causes an issue in exporting the module:

    export 'AdapterDayjs' (imported as 'AdapterDayjs') was not found in '@mui/x-date-pickers'Attempted import error: 'AdapterDayjs' is not exported from '@mui/x-date-pickers' (imported as 'AdapterDayjs').

 For context, these are my dependencies:

    "dependencies": {
        "@date-io/dayjs": "^2.16.0",
        "@emotion/react": "^11.10.8",
        "@emotion/styled": "^11.10.8",
        "@mui/icons-material": "^5.11.11",
        "@mui/lab": "^5.0.0-alpha.129",
        "@mui/material": "^5.12.3",
        "@mui/styles": "^5.5.0",
        "@mui/x-data-grid": "^6.3.0",
        "@mui/x-date-pickers": "^6.3.0",
        "dayjs": "^1.11.7",
        "material-table": "^2.0.3",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-router-dom": "^6.3.0",
        "react-scripts": "5.0.0",
        "web-vitals": "^2.1.0"
    },

**Comment by rafshawn** [comment]
> Hello, have you tried importing directly from `@mui/x-date-pickers/AdapterDayjs`? I can't see any reference in docs suggesting a root import is possible. 🤔
> 
> Suggestion: Consider dropping `@date-io/dayjs` dependency as all the adapters are shipped internally starting v6.3.0 😉

Thank you for the suggestion! Tried doing that and I only installed the `dayjs` module based off a suggestion I found on the internet. I get the same error importing directly, I was thinking if it could be an issue with the project itself?

**Comment by LukasTy** [comment]
> I get the same error importing directly, I was thinking if it could be an issue with the project itself?

Could you please provide a code snippet or a "codesandbox" demo with the code that is causing issues?
I'll remind you that root-level imports are not supported for the adapters.
❌ `import { AdapterDayjs } from '@mui/x-date-pickers'`
✅ `import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'`

**Comment by IvanAlcuinoAxpara** [comment]
I have the same issue. Can anybody help?

**Comment by LukasTy** [comment]
> I have the same issue. Can anybody help?

Could you please provide a reproduction example or at least the import you are using and the version of the package?

**Comment by LukasTy** [comment]
@IvanAlcuinoAxpara This looks like an environment setup issue.
1. Have you tried `Node 18`?
2. Have you tried updating the import path as suggested? For example, update it to `@mui/x-date-pickers/AdapterDayjs/index.js`.

**Comment by IvanAlcuinoAxpara** [comment]
Yap I did both but still having the same issue. I updated my original post.

**Comment by LukasTy** [comment]
@IvanAlcuinoAxpara I've setup a fresh Remix project with the default recommended template, installed `@mui/x-date-pickers`, and did not see any issues in both `dev` and `build`.
Could you please provide more information on your setup?
Ideally we'd like to see a minimal repository or a `StackBlitz` or `CodeSandbox` demo. 😉

**Comment by shish-ko** [comment]
@IvanAlcuinoAxpara, @LukasTy, [this is](https://stackoverflow.com/questions/78017516/vite-ssr-build-fails-with-mui-icons-and-date-time-picker) my problem (and possible solution for your problem). It can be solved by importing from `node` subfolder. I can hardly axplain why, but it works for me.

**Comment by LukasTy** [comment]
@shish-ko Could you please provide a reproduction example or repository for us to test? 🤔 
I have tried running the Pickers package in a Vite project without problems, maybe in your case, there is some conflict with the setup. 🤔 🤷

**Comment by shish-ko** [comment]
@LukasTy  https://github.com/shish-ko/mui_vite 
'npm i' -> 'npm run dev' works
'npm i' -> 'npm run build' -> 'npm run preview' fails

**Comment by sriram-balaganeshan** [comment]
i couldn't import DayCalendarSkeleton if i import it will error shows export 'DayCalendarSkeleton' (imported as 'DayCalendarSkeleton') was not found in '@mui/x-date-pickers'

**Comment by dev-scripts** [comment]
`// with date-fns v2.x
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
// with date-fns v3.x
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';
// with date-fns v2.x
import de from 'date-fns/locale/de';
// with date-fns v3.x
import { de } from 'date-fns/locale/de';
 <LocalizationProvider dateAdapter={AdapterDateFns} adapterLocale= {de}>
                                                <DatePicker
                                                    label="Controlled picker"
                                                    
                                                />
`

**Comment by shish-ko** [comment]
@LukasTy Hi! Is there any updates?

**Comment by synle** [comment]
@LukasTy @rafshawn 

I managed to get this operational. Essentially, what I did was implement lazy loading for this particular component.

To elaborate, there's a component named DateTimeInput.tsx that utilizes these adapters. The initial import lines resemble the following:


```tsx
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment';
import { DateTimePicker } from '@mui/x-date-pickers/DateTimePicker';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';

export default function DateTimeInput(){
  return //... your code here
}
```

Subsequently, there's another component, `Form.tsx`, which utilizes the aforementioned component:

Instead of directly importing `DateTimeInput` which does not work, as shown below:
```tsx
import { DateTimeInput } from 'src/component/input/DateTimeInput';

function Form() {
  return <>
    <DateTimeInput />
  </>
}
```

I changed it to `lazy` loading and `Suspense`, resulting in successful execution. This code works for me.

```tsx
import { Suspense, lazy, useState } from 'react';

const DateTimeInput = lazy(() => import(`~/src/component/input/DateTimeInput`));

function Form() {
  return <Suspense>
    <DateTimeInput />
  </Suspense>
}
```

**Comment by maximemarc** [comment]
Hello if you use quickly delete the cache vite in the node module

**Comment by yukiyokotani** [comment]
I encountered the same issue when trying to use the Luxon Adapter. 
I'm not sure why Rollup resolves the module on the CJS side, but since the Adapter itself exists as an ESM, I explicitly wrote the path resolution settings for the Adapter, and for now, it's working well. 
Below is the vite.config.ts for that.

```ts
import { vitePlugin as remix } from '@remix-run/dev';
import { installGlobals } from '@remix-run/node';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import path from 'path';

installGlobals();

export default defineConfig({
  plugins: [
    remix({
      ssr: false,
    }),
    tsconfigPaths(),
  ],
  resolve: {
    alias: {
      '@mui/x-date-pickers/AdapterLuxon': path.resolve(
        __dirname,
        'node_modules/@mui/x-date-pickers/AdapterLuxon/AdapterLuxon.js',
      ),
    },
  },
  optimizeDeps: {
    include: [
      '@mui/material',
      '@mui/icons-material',
      '@emotion/react',
      '@emotion/styled',
    ],
    force: true,
  },
});

```

**Comment by mahmoudmoravej** [comment]
For DayJs, I exacyly followed @yukiyokotani solution and it worked. Thanks!
```vite.config.ts

export default defineConfig({
 //...
  resolve: {
    alias: {
      "@mui/x-date-pickers/AdapterDayjs": path.resolve(
        __dirname,
        "node_modules/@mui/x-date-pickers/AdapterDayjs/AdapterDayjs.js"
      ),
    },
  },
 //...
});


```

**Comment by denisw** [comment]
With version 7.21.0 of `mui/x-date-pickers`, I had to add a second alias to the solution posted by @yukiyokotani and @mahmoudmoravej. Then it worked!

```typescript
    resolve: {
        alias: {
            '@mui/x-date-pickers/AdapterDayjs': path.resolve(
                import.meta.dirname,
                'node_modules/@mui/x-date-pickers/AdapterDayjs/AdapterDayjs.js'
            ),
            '@mui/x-internals/warning': path.resolve(
                import.meta.dirname,
                'node_modules/@mui/x-internals/warning/warning.js'
            ),
        },
    },
```
