### ISSUE TITLE
[pickers] DatePicker / DateRangePicker / DateTimePicker losing focus after onChange (v6)

### ISSUE THREAD

**Issue by xdebbie** [mui/mui-x#8850]
I have a little question regarding the use of `onChange` as a prop. In my use case, I have a custom DatePicker component ( https://codesandbox.io/s/friendly-kilby-s42wp7?file=/DatePicker.tsx ) with `onChange` and `value` as props. On my `demo.tsx` file ( https://codesandbox.io/s/friendly-kilby-s42wp7?file=/demo.tsx ) I use my DatePicker with the `onChange` prop and `useState` to set the new `selectedDate`. The problem is that, as you can see on the demo, on every onChange my input will lose focus. Am I doing something terribly wrong? Have I missed something on the v6 update? It used to work on v5, but since I've upgraded to v6 this implementation is not working anymore.

Live examples (try typing a date, e.g. 05/17/2023 or use the up/down arrows on v6)
v6 - https://codesandbox.io/s/friendly-kilby-s42wp7?file=/DatePicker.tsx
v5 - https://codesandbox.io/s/naughty-bassi-tsi0ji?file=/DatePicker.tsx

```typescript
import dayjs, { Dayjs } from "dayjs";
import { DemoContainer } from "@mui/x-date-pickers/internals/demo";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";

import { TextField } from "@mui/material";
import styled from "@emotion/styled";

type DatePickerProps = {
  onChange?: (date: Date | null) => void;
  value?: Dayjs | null;
};

export const TextInput = styled(TextField)`
  input {
    color: blueviolet;
    font-size: 20px;
  }
  svg {
    color: blueviolet;
  }
`;

export default function BasicDatePicker({ onChange, value }: DatePickerProps) {
  const handleChange = (newValue: Dayjs | null) => {
    onChange(dayjs(newValue).toDate());
  };

  const CustomTextField = (params: any) => {
    return <TextInput {...params} />;
  };

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DemoContainer components={["DatePicker"]}>
        <DatePicker
          value={value}
          onChange={handleChange}
          slots={{ textField: CustomTextField }}
          slotProps={{
            textField: {
              InputProps: { sx: { height: 40, backgroundColor: "white" } }
            }
          }}
        />
      </DemoContainer>
    </LocalizationProvider>
  );
}

```

```typescript
import { useState } from "react";
import dayjs, { Dayjs } from "dayjs";
import BasicDatePicker from "./DatePicker";

export default function Demo() {
  const [selectedDate, setSelectedDate] = useState<Dayjs>(dayjs());
  const handleDateSelect = (newValue: Date | null) => {
    setSelectedDate(dayjs(newValue));
  };

  return (
    <div>
      <BasicDatePicker value={selectedDate} onChange={handleDateSelect} />
      <div>Second element</div>
    </div>
  );
}
```

Now another bizarre "fix" for the loss of focus problem: if I simply comment out the `// slots={{ textField: CustomTextField }}`  line from the DatePicker, then it will also work... So I am actually even failing to see where exactly the problem is! 🤯

Thank you!

**Comment by alexfauquette** [comment]
That's because your 

```jsx
const CustomTextField = (params: any) => {
  return <TextInput {...params} />;
};
```

is defined inside the components, so when `onChange` is called, the state get updated, then React does a rerender, and so the text files is a new components (all internal state are deleted)

Here is the fix

```diff
+ const CustomTextField = (params: any) => {
+  return <TextInput {...params} />;
+ };

 export default function BasicDatePicker({ onChange, value }: DatePickerProps) {
   const handleChange = (newValue: Dayjs | null) => {
     onChange(dayjs(newValue).toDate());
   };

-  const CustomTextField = (params: any) => {
-   return <TextInput {...params} />;
-  };
```
https://codesandbox.io/s/lucid-fire-lttkzz?file=/DatePicker.tsx:663-925
