### ISSUE TITLE
[pickers] Allow specifying the current year in `<MonthCalendar />`

### ISSUE THREAD

**Issue by githorse** [mui/mui-x#8852]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Is there some way to change the year on the `MonthCalendar`? Without it the component is pretty unusable without extra effort to build a year picker around it. Or maybe I'm unclear on how the component is intended to be used -- could someone provide an example?

### Motivation 🔦

I'm attempting to build a custom [modal date range picker](https://github.com/mui/mui-x/issues/8838) around MUI components, but I can't use the `MonthPicker` without a way to adjust the year on it.

### Order ID 💳 (optional)

46840

**Comment by alexfauquette** [comment]
This issue is similar to https://github.com/mui/mui-x/issues/8837

The MonthCalendar would need a new prop similar to `currentMonth`. Something like that should do the job

```diff
--- a/packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx
+++ b/packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx
@@ -77,6 +77,7 @@ export const MonthCalendar = React.forwardRef(function MonthCalendar<TDate>(
   const {
     className,
     value: valueProp,
+    currentMonth,
     defaultValue,
     disabled,
     disableFuture,
@@ -108,8 +109,8 @@ export const MonthCalendar = React.forwardRef(function MonthCalendar<TDate>(
   const todayMonth = React.useMemo(() => utils.getMonth(now), [utils, now]);
 
   const selectedDateOrStartOfMonth = React.useMemo(
-    () => value ?? utils.startOfMonth(now),
-    [now, utils, value],
+    () => value ?? currentMonth ?? utils.startOfMonth(now),
+    [now, currentMonth, utils, value],
   );
 
   const selectedMonth = React.useMemo(() => {
```

**Comment by flaviendelangle** [comment]
`currentMonth` or `referenceValue` is we go for this comment solution: https://github.com/mui/mui-x/issues/8311#issuecomment-1497009120

**Comment by githorse** [comment]
If I'm understanding correctly, `currentMonth` obviously gets me part of the way there, but I would still have to provide my own dropdown or whatever to select a different year, yes? This seems inconsistent with `DateCalendar` and `YearCalendar`, which let the user essentially pick any value without having to be "refreshed" with a new range from outside.

**Comment by alexfauquette** [comment]
The `<MonthCalendar />` is only here to pick a month. If you want to have the view management part you should use *

```jsx
<DateCalendar views={["year", "month"]} />
```

https://codesandbox.io/s/wonderful-boyd-yu9qse?file=/demo.tsx

**Comment by flaviendelangle** [comment]
As @alexfauquette said:

- `MonthCalendar` => month
- `YearCalendar` => year
- `DateCalendar` => year + month + day (uses `MonthCalendar` and `YearCalendar` behind the scene, as well as the private `DayCalendar`)
