### ISSUE TITLE
[MUI Data Grid] Row group row moves to the end of group when row data is updated

### ISSUE THREAD

**Issue by sagarchoudhary96** [mui/mui-x#8853]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/loving-wilson-55r2oy?file=/demo.tsx
<img width="598" alt="Screenshot 2023-05-03 at 10 57 16 PM" src="https://user-images.githubusercontent.com/16102594/235995375-1876e057-3e7a-470e-85d6-1f984cda0adb.png">

Steps:
1. try to edit a row column when grouped.

### Current behavior 😯

The row being edited moves to the bottom of the group.

### Expected behavior 🤔

The row index should be preserved and be at same place.

### Context 🔦

When having a large set of data and trying to visualise with grouping enabled, and editing data, This current behaviour of moving the edited row to the bottom in the group makes it difficult to know the edited row and for the user to find that row as they lose context and expects the row to stay at the same position.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.121
    @mui/core-downloads-tracker:  5.11.13
    @mui/material: ^5.11.13 => 5.11.13
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.11
    @mui/system:  5.11.13
    @mui/types:  7.2.3
    @mui/utils:  5.11.12
    @mui/x-data-grid:  6.0.1
    @mui/x-data-grid-premium: 6.0.1 => 6.0.1
    @mui/x-data-grid-pro:  6.0.1
    @mui/x-date-pickers: ^6.0.1 => 6.0.1
    @mui/x-license-pro:  6.0.1
    @types/react: 18.0.24 => 18.0.24
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components:  5.3.6
    typescript: ^4.8.4 => 4.8.4
```
</details>

### Order ID or Support key 💳 (optional)

55516

**Comment by cherniavskii** [comment]
Hi @sagarchoudhary96 
This looks like another symptom of https://github.com/mui/mui-x/issues/8580

I've forked your demo and tried to use the version of the data grid from the [PR that is supposed to fix the linked issue](https://github.com/mui/mui-x/pull/8823) and it seems to be fixed:
https://codesandbox.io/s/frosty-bassi-1hwexf

Note, that the row can still be moved after editing if sorting is applied to the grid.
