### ISSUE TITLE
[data grid] Trying to put space between columns and rows.

### ISSUE THREAD

**Issue by jmsims2** [mui/mui-x#8858]
### Order ID or Support key 💳 (optional)

62675

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am trying to have some space between all cells. I'm able to use classes just fine but I cannot get the columns to line up with their underlying cells. I'm also not able to target a pinned column header, I'd like to change it's color, but can't quite get it to work.

Here is a sandbox demonstrating what I have thus far: https://codesandbox.io/s/loving-dew-nln5du?file=/src/App.tsx

Any help would be appreciated!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
The datagrid determines the cell positions programatically, so you can't set the spacing with CSS.

For the row spacing, you should check out the [row spacing documentation](https://mui.com/x/react-data-grid/row-height/#row-spacing).

For column spacing, there isn't an equivalent API, but you could instead replicate the spacing visually by:
 - making `.MuiDataGrid-cell` have a transparent background, with an inner padding corresponding to the spacing you want
 - making `.MuiDataGrid-cellContent` have an opaque background and fill the available space

**Comment by jmsims2** [comment]
@romgrk Thanks for the advice! I'm trying out `getRowSpacing` but it doesn't seem to be spacing out rows in columns that are pinned. Updated sandbox: https://codesandbox.io/s/loving-dew-nln5du?file=/src/App.tsx

Is that expected?

**Comment by jmsims2** [comment]
@m4theushw Hey, that worked great! Thanks, appreciate the help!

**Comment by yaredtsy** [comment]
hey @jmsims2 

why not just use a margin to give space between all the cells? It seems to be working for me.

![image](https://user-images.githubusercontent.com/34584266/236392803-d6a5e549-6c85-4176-b60d-73b378cc491b.png)

```jsx
   sx={{
          backgroundColor: (theme) => "gray",
          width: "80%",
          "& .MuiDataGrid-columnHeader:not(:first-child):not(:last-child)": {
            mx: 3
          },
          "& .MuiDataGrid-columnHeader:first-child:not(:last-child)": {
            mr: 3
          },
          "& .MuiDataGrid-columnHeader:last-child:not(:first-child)": {
            ml: 3
          },
          "& .MuiDataGrid-cell:not(:first-child):not(:last-child)": {
            mx: 3
          },
          "& .MuiDataGrid-cell:first-child:not(:last-child)": {
            mr: 3
          },
          "& .MuiDataGrid-cell:last-child:not(:first-child)": {
            ml: 3
          },
          "& .MuiDataGrid-row": {
            mt: 3
          }
        }}
```
Demo:https://codesandbox.io/s/relaxed-surf-yhp4oo?file=/src/App.tsx:3095-3854

**Comment by RyanGundu** [comment]
you can use the prop `getRowSpacing` for row spacing. For example: 
```
getRowSpacing={() => ({ top: 12, bottom: 12 })}
```
manually applying margin to the rows can cause weird behavior with the virtualScroll

**Comment by xiaominzhu88** [comment]
> hey @jmsims2
> 
> why not just use a margin to give space between all the cells? It seems to be working for me.
> 
> ![image](https://user-images.githubusercontent.com/34584266/236392803-d6a5e549-6c85-4176-b60d-73b378cc491b.png)
> 
> ```js
>    sx={{
>           backgroundColor: (theme) => "gray",
>           width: "80%",
>           "& .MuiDataGrid-columnHeader:not(:first-child):not(:last-child)": {
>             mx: 3
>           },
>           "& .MuiDataGrid-columnHeader:first-child:not(:last-child)": {
>             mr: 3
>           },
>           "& .MuiDataGrid-columnHeader:last-child:not(:first-child)": {
>             ml: 3
>           },
>           "& .MuiDataGrid-cell:not(:first-child):not(:last-child)": {
>             mx: 3
>           },
>           "& .MuiDataGrid-cell:first-child:not(:last-child)": {
>             mr: 3
>           },
>           "& .MuiDataGrid-cell:last-child:not(:first-child)": {
>             ml: 3
>           },
>           "& .MuiDataGrid-row": {
>             mt: 3
>           }
>         }}
> ```
> 
> Demo:https://codesandbox.io/s/relaxed-surf-yhp4oo?file=/src/App.tsx:3095-3854

Well, if you try to pin some columns to the right, the position will break

**Comment by xiaominzhu88** [comment]
Well, if you pin columns to the right, horizontal scrolling will eventually break, maybe try something like this to adjust the spacing between columns? ( cell borders are displayed with spacing )

```
[`.${gridClasses['cell']}`]: {
              paddingRight: `${spacing(2)}`,
              borderColor: 'transparent',
              [`.${gridClasses['cellContent']}`]: {
                height: '100%',
                width: '100%',
                alignItems: 'center',
                display: 'flex',
                borderBottom: `1px solid ${palette.grey[200]}`
              },
           }
```
