### ISSUE TITLE
Showing action button on row hover with pinned columns 

### ISSUE THREAD

**Issue by GlutVonSmark** [mui/mui-x#8860]
### Order ID or Support key 💳 (optional)

#32742

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

In our data table we have icons in the action column hidden using css. When user hovers over a row they are shown to the user

![image](https://user-images.githubusercontent.com/33777882/236141771-30d58671-098e-4cda-9681-5950dd032c5c.png)

This was achieved using those css rules:

      ` '& .actionButton': {
              opacity: 0,
          },

       `[`& .${gridClasses.row}:hover, & .${gridClasses.row}:focus-within`]: {
        '.actionButton': {
            opacity: 1,
        },
        cursor: 'pointer',
       },`

Now we want to have the action column pinned to the right so it's always shown.

After we add pinnedColumns: { left: [], right: ['action'] },

The showing of action buttons on a row hover no longer works. You have to hover on the cell in the pinned column.
Seems that the cells in  pinned column are "taken out" of the table row. (or have different css classes)

Could you point us to what modifications should make to the css code to make this work?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @GlutVonSmark 
You're right, with pinned columns, the row is split into multiple parts.
You can use this instead:
```js
[`& .${gridClasses.row}`]: {
  "&:hover, &.Mui-hovered": {
    ".actionButton": {
      opacity: 1
    }
  }
}
```

Here's a working demo: https://codesandbox.io/s/romantic-firefly-bko84c?file=/demo.js

Is this what you are looking for?

**Comment by GlutVonSmark** [comment]
Thanks. That solved the problem
