### ISSUE TITLE
[pickers] Provide the ability to add custom ids to the DatePicker

### ISSUE THREAD

**Issue by victorbadila** [mui/mui-x#8864]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In one of my projects I use some MUI components with custom labels, as opposed to MUI provided labels, the ones htat float around on input interaction. For example for a `Select` component I can do this:
```
<label htmlFor={id} id={labelId}>{label}</label>
<Select  id={id} labelId={labelId} ...>
  ...
</Select>
```
This way I can customize the label however I want and I know that it will still point to the input (for accessibility purposes).
I haven't found this option on the `DatePicker` component, it does not allow "id" attributes, I was at most able to make it not have the standard label by not giving the prop and make my custom label, however I found no ways to bind them together. I see that the input in the `DatePicker` does get some random ids assigned though.

### Examples 🌈

https://mui.com/x/api/date-pickers/date-picker. <-- no "id" or related properties I could find that helps me solve my problem.

### Motivation 🔦

Can't use custom labels for `DatePicker` components

**Comment by LukasTy** [comment]
Have you considered using `slotProps.textField.id` to achieve your desired result?
The `DatePicker` component accepts props that are relevant to the whole picker, but such props are only related to the input element.
[Here is an example codesandbox](https://codesandbox.io/s/date-picker-custom-label-id-61xb0v?file=/demo.tsx) with the mentioned idea.
Does it solve your issue?

**Comment by victorbadila** [comment]
Works very well, thank you
