### ISSUE TITLE
[question] Data Grid Premium combining onStateChange with filterChanges and sortChanges

### ISSUE THREAD

**Issue by randr44** [mui/mui-x#8873]
### Order ID or Support key 💳 (optional)

Premium Plan (But shouldn't this be kept secret)

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [ ] I have tested the latest version

### The problem in depth 🔍

I'm able to persist state to local storage, retrieve and restore the grid columns via the onStateChange prop with a implementation that closely mimics https://codesandbox.io/s/datagrid-v5-quick-start-forked-5qp36g?file=/src/App.tsx. However when clearing saved storage, the filtering applied to the grid, the column filters applied and possibly the sorting remain. (From my understanding, I am aware that I am not utilizing any api props to the handle the changes to the filtering, column visibility and sorting), So my question is how should I go about resetting even those grid edits from the state, while still utilizing onStateChange to handle the bulk of the saving/restoring? 

To Replicate go to the sandbox and add a filter, or remove a column from visibility then clear saved state. The filter and columns are still there.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: (113.0.5672.63)
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.68)
  npmPackages:
    @emotion/react: 11.10.6 => 11.10.6
    @emotion/styled: 11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.126
    @mui/core-downloads-tracker:  5.12.1
    @mui/icons-material: 5.11.16 => 5.11.16
    @mui/lab: 5.0.0-alpha.75 => 5.0.0-alpha.75
    @mui/material: 5.12.1 => 5.12.1
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/styles: 5.12.0 => 5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.4
    @mui/utils:  5.12.0
    @mui/x-data-grid:  6.0.0-alpha.2
    @mui/x-data-grid-generator: 5.10.0 => 5.10.0
    @mui/x-data-grid-premium: 6.0.0-alpha.2 => 6.0.0-alpha.2
    @mui/x-data-grid-pro:  5.10.0
    @mui/x-date-pickers: 5.0.17 => 5.0.17
    @mui/x-license-pro:  6.0.0-alpha.2
    @types/react:  18.0.37
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 5.0.4 => 5.0.4
```
</details>

**Comment by cherniavskii** [comment]
Hi @randr44 
A few things here:
1. *CLEAR SAVED STATE* button only clears the session storage, but doesn't trigger any rerender, so the component doesn't even know something has changed. You probably need to clear the saved state: `setSavedState({})`
2. The `initialState` prop is only used once during state initialization (when the component mounts). After the component is mounted, it won't react to the `initialState` prop changes - see https://mui.com/x/react-data-grid/state/#initialize-the-state
If you want to reset the grid and initialize it with a new initial state - the go-to approach in React is using `key` - see https://react.dev/reference/react/useState#resetting-state-with-a-key

Here is a working demo: https://codesandbox.io/s/datagrid-v5-quick-start-forked-5qp36g?file=/src/App.tsx
