### ISSUE TITLE
[DataGrid] Issues with controlled filterModel in GridToolbarQuickFilter

### ISSUE THREAD

**Issue by federico-ntr** [mui/mui-x#8876]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/p/sandbox/jolly-rosalind-gembee (not pretty but reproduces the issue)

Steps:
1. Write something in the search input field
2. Place the cursor in any position of the string
3. You'll find out the cursor goes at the end of the string after typing one character

### Current behavior 😯

- The cursor always goes to the end of the string which is being typed
- The [debounce](https://codesandbox.io/p/sandbox/jolly-rosalind-gembee?file=/src/Table.tsx&selection=%5B%7B%22endColumn%22:13,%22endLineNumber%22:116,%22startColumn%22:13,%22startLineNumber%22:116%7D%5D) seems to have no effect 
- Typing seems a bit laggy, which brings to lost characters when you type fast

### Expected behavior 🤔

The input with controlled filterModel should work fine like the uncontrolled one in the docs does.

### Context 🔦

I'm controlling the filterModel in my project because I have another filtering strategy which requires the filterModel to be controlled.

### Your environment 🌎

Tested on Arc (chromium-based), Firefox and Safari
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.63
    Edge: 112.0.1722.39
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @emotion/react: 11.10.8 => 11.10.8 
    @emotion/styled: 11.10.8 => 11.10.8 
    @mui/base:  5.0.0-alpha.128 
    @mui/core-downloads-tracker:  5.12.3 
    @mui/icons-material: 5.11.16 => 5.11.16 
    @mui/lab: 5.0.0-alpha.129 => 5.0.0-alpha.129 
    @mui/material: 5.12.3 => 5.12.3 
    @mui/private-theming:  5.12.3 
    @mui/styled-engine:  5.12.3 
    @mui/system:  5.12.3 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.3 
    @mui/x-data-grid: 6.3.0 => 6.3.0 
    @mui/x-date-pickers: 6.3.0 => 6.3.0 
    @types/react: 18.2.5 => 18.2.5 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.4 => 5.0.4 
```
</details>

**Comment by cherniavskii** [comment]
Hi @federico-ntr 
I have created this simplified example for better understanding what is going on: https://codesandbox.io/s/infallible-elion-jpddf8?file=/demo.tsx
Can you clarify why you're not using `onFilterModelChange`?
