### ISSUE TITLE
Attempted import error: 'useGridApiMethod' is not exported from '../../utils' (imported as 'useGridApiMethod').

### ISSUE THREAD

**Issue by BurakFurkan** [mui/mui-x#8877]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://github.com/BurakFurkan/admin-dashboard
![useGridStatePersistance js](https://user-images.githubusercontent.com/100779018/236413694-22b4ee69-1c9d-4726-b695-0e6fd88e2acd.png)
![2023-05-05 11_44_20-Ayarlar](https://user-images.githubusercontent.com/100779018/236414614-d9f724ad-0167-4778-bef2-8f271a6bd321.png)

### Current behavior 😯

Didn't even use these apis  but still get an error message. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.127
    @mui/core-downloads-tracker:  5.12.2
    @mui/material: ^5.12.0 => 5.12.2
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system: ^5.12.0 => 5.12.1
    @mui/types:  7.2.4
    @mui/utils: ^5.12.0 => 5.12.0
    @mui/x-data-grid: ^6.3.0 => 6.3.0
    @types/react: 18.0.38 => 18.0.38
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.0.4 => 5.0.4
    "next": "13.3.1",
    "eslint": "8.39.0",
    "eslint-config-next": "13.3.1",
```
</details>

Browser : Chrome

**Comment by cherniavskii** [comment]
Hi @BurakFurkan 
It seems to work fine unless I'm missing something:
<img width="993" alt="Screenshot 2023-05-05 at 20 45 36" src="https://user-images.githubusercontent.com/13808724/236542882-19d08dfa-04b4-4bb8-8d82-339cd463c5a3.png">

**Comment by BurakFurkan** [comment]
It works but I got these "Attempted import error"s  even though I didn't use these apis. Did you get these error messages at browser console or vs code console?

**Comment by cherniavskii** [comment]
@BurakFurkan Nope, I don't see the error you mentioned.
