### ISSUE TITLE
MUI Dropdowns not working inside a bootstrap modal

### ISSUE THREAD

**Issue by LeonSa2404** [mui/mui-x#8878]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-template-forked-51hpvw

Steps:
1. Open the filter menu
2. Click on the columns or operator dropdown

### Current behavior 😯

The dropdown flickers but does not open.

### Expected behavior 🤔

The dropdown should open on click.

### Context 🔦

I am trying to display the DataGrid inside a bootstrap modal with working filter functionality.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
 System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.50
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)

Browser: Chrome
</details>

### Order ID or Support key 💳 (optional)

65695

**Comment by cherniavskii** [comment]
Hi @LeonSa2404 
It seems like the default behavior of react-bootstrap's Modal is taking over the focus - see https://github.com/react-bootstrap/react-bootstrap/issues/6420
Adding `enforceFocus={false}` to `Modal` fixes the issue:
https://codesandbox.io/s/mui-x-issue-template-forked-bcqgji?file=/src/App.tsx

**Comment by LeonSa2404** [comment]
Hi, this works. Thanks a lot!
