### ISSUE TITLE
DataGrid german translation not complete

### ISSUE THREAD

**Issue by LeonSa2404** [mui/mui-x#8879]
### Order ID or Support key 💳 (optional)

65695

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

![1](https://user-images.githubusercontent.com/63504232/236422255-b726286f-d7ff-4ded-b362-4e55cddbfa5c.png)
![2](https://user-images.githubusercontent.com/63504232/236422332-f02f7de7-3e39-4b78-b4fa-8fbfaa63bce4.png)
![3](https://user-images.githubusercontent.com/63504232/236422793-6ef44341-8392-4cae-a229-d19f71f16666.PNG)

Is there a reason these two keys are commented out?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
These keys were recently added as part of new features and awaiting some kind person from community to translate them 🙂 

Fee free to open a PR with translations if you want. You can check out the [callout issue](https://github.com/mui/mui-x/issues/3211) or already translated [PRs](https://github.com/mui/mui-x/pulls?q=is%3Apr+is%3Aclosed+label%3Al10n) to see about the format.
