### ISSUE TITLE
Ability to edit column panel footer for the data grid

### ISSUE THREAD

**Issue by arjot-rai** [mui/mui-x#8887]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It will be great if there was a way to edit the footers of the column panel. For instance in the following screenshot, be able to replace the 'Hide All' button with some other custom button we would like to use. Currently we have to use the ColumnsPanel slot to override the whole pane, possibly having a 'slot' for ColumnPanelFooter would solve this issue.

![image](https://user-images.githubusercontent.com/51229812/236373442-549ee7d5-ce09-4c5d-aeb7-03dbd74fe943.png)

### Motivation 🔦

In particular be able to replace the 'Hide All' button with some other button such as a 'Default Columns' which allows one to switch to the initially default columns, particularly where the default columns is not the complete set of columns.

### Order ID 💳 (optional)

45835

**Comment by cherniavskii** [comment]
Hi @arjot-rai 
You can create a custom columns panel: https://codesandbox.io/s/dreamy-turing-irj9xn?file=/demo.tsx

**Comment by arjot-rai** [comment]
This fails if you increase the number of columns to more than 15

**Comment by cherniavskii** [comment]
Answered in https://github.com/mui/mui-x/issues/8896#issuecomment-1537437621
