### ISSUE TITLE
[pickers] v6 removed the ability to remove the separator between pickers in DateRangePicker

### ISSUE THREAD

**Issue by ArthurNRL** [mui/mui-x#8889]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. import DateRangePicker
2. try to change any prop related to the separator(slots.fieldSeparator, slotProps.fieldSeparator)
3. space between start and end date is still there.

### Current behavior 😯

The space between the two fields should be gone(the top ones are actually two separated DatePickers)
![image](https://user-images.githubusercontent.com/63674393/236526424-aae021b1-a452-43f3-b4a5-583503039e64.png)

### Expected behavior 🤔

Before we could do something like 
```
renderInput={(startProps, endProps) => (
          <Stack direction="row" spacing={2} sx={{ width: '100%' }}>
            <CustomInput inputProps={startProps} />
            <CustomInput inputProps={endProps} />
          </Stack>
      )}
```
and customize how the inputs looked

### Context 🔦

I'm trying to migrate a project but this makes the visual of the app look out of standard

### Your environment 🌎

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.65 GB / 31.84 GB
  Binaries:
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 22.0.4 - C:\Python38\Scripts\pip3.EXE
  Utilities:
    Git: 2.35.1. - /cmd/git
    Ninja: 1.11.0 - /c/ProgramData/chocolatey/bin/ninja
  Virtualization:
    Docker: 20.10.21 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.74.3 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\Windows\system32\bash.EXE
    Perl: 5.34.0 - C:\Program Files\Git\usr\bin\perl.EXE
    Python: 3.8.0 - /c/Python38/python
  Databases:
    MySQL: 5.7.35 - C:\mysql-5.7.35-winx64\bin\mysql.EXE
    PostgreSQL: 14.1 - C:\Program Files\PostgreSQL\14\bin\postgres.EXE
    SQLite: 3.32.2 - C:\platform-tools\sqlite3.EXE
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1

### Order ID or Support key 💳 (optional)

48634

**Comment by LukasTy** [comment]
Hello, what do you think about using `slots={{ fieldSeparator: React.Fragment }}`?
[Here](https://codesandbox.io/s/serene-galileo-pw6eoe?file=/demo.tsx) is a live example.

**Comment by ArthurNRL** [comment]
Ended up going the 
```
slotProps={{
                fieldSeparator: { sx: { display: "none" } },
}}
```
route, For some reason using React.Fragment kept the same space with the '-' gone. Maybe because I'm using a grid and react-hook-form's controller around the range picker

**Comment by LukasTy** [comment]
It's strange, passing a `React.Fragment` should avoid rendering anything in case of a separator. We'd need a minimal reproduction example to fully understand the issue.
Feel free to provide it or close the issue if you think that you are satisfied with the solution. 😉

**Comment by ArthurNRL** [comment]
I can try to create an example later if I get some time

**Comment by cloetensbrecht** [comment]
```javascript
slots={{
	fieldSeparator: () => null
}}
```
