### ISSUE TITLE
[question] Is there a way to use Master Detail on pinned Rows?

### ISSUE THREAD

**Issue by melbahysa** [mui/mui-x#8891]
### Order ID or Support key 💳 (optional)

55371

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm trying to use the Master-Detail feature of Material-UI's DataGridPro component in my React application, but I'm running into an issue when I enable pinned rows. According to the documentation, Master-Detail is not supported for Pinned Rows.

This is a problem for my use case, as I need to display some rows at the top of the table that are always visible while scrolling through the rest of the data. However, I also need to show additional information to the user when the ExpandIcon is clicked, which I was planning to do using the Master-Detail feature.

I believe that many users would benefit from being able to combine pinned rows and master-detail, so I'm opening this issue to request support for this use case. Alternatively, if there's a workaround that I can use to achieve the desired behavior, please let me know.

Thank you for your attention to this matter. Let me know if you need any further information from me.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

  System:
    OS: macOS 12.6.5
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.8.1/bin/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v19.8.1/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 109.0.1
    Safari: 15.6.1
  npmPackages:
    @emotion/react: 11.10.6 => 11.10.6 
    @emotion/styled: 11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.90 
    @mui/icons-material: ^5.8.4 => 5.10.3 
    @mui/lab: ^5.0.0-alpha.96 => 5.0.0-alpha.99 
    @mui/material: ^5.8.6 => 5.9.1 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system: ^5.4.1 => 5.11.15 
    @mui/types:  7.2.1 
    @mui/utils:  5.10.15 
    @mui/x-data-grid:  5.17.8 
    @mui/x-data-grid-pro: ^5.17.8 => 5.17.8 
    @mui/x-date-pickers: ^5.0.0-alpha.7 => 5.0.1 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react: 18.0.38 => 18.0.38 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.4 => 5.0.4 
```
</details>

**Comment by cherniavskii** [comment]
Hey @melbahysa 
Curious to learn what behavior you expect when pinned row is expanded.

Consider this example: https://codesandbox.io/s/gracious-ritchie-474ey4?file=/demo.tsx
Would you expect the top pinned rows container to grow and potentially cover the non-pinned rows area? Something like this?
<img width="778" src="https://user-images.githubusercontent.com/13808724/237054586-096ee9c7-8c17-4ad5-a457-d22f5b3b284a.png">

**Comment by melbahysa** [comment]
hello @cherniavskii 

In our use case we have only one pinnedRow in the top of the data grid and our expected behaviour is exactly the one you mentioned. When we click the ExpandIcon, we would want the pinnedRow container to grow and cover the non-pinned rows area, so that on the top of the grid we have the pinnedRow and the DetailPanel of that PinnedRow.

**Comment by yaredtsy** [comment]
hey @cherniavskii 

what if the grid height grows when the detail panel expands. in this way, it will remove the possibility of covering the whole table.

https://github.com/mui/mui-x/assets/34584266/6b0f2899-0011-4507-8b6a-585d16290380

**Comment by djorgji** [comment]
> hey @cherniavskii
> 
> what if the grid height grows when the detail panel expands. in this way, it will remove the possibility of covering the whole table.
> 
>  simplescreenrecorder-2023-05-17_08.02.32.mp4

The solution seems intuitive to me, grow the pinned row panel to show the detail. Maybe if the grid as a whole has a fixed height then the overflow just becomes scrollable.

**Comment by melbahysa** [comment]
hey @yaredtsy Could you please let me know if you are utilising pinnedRows for the grey row in the screen recorded example? If so, would you mind sharing the workaround?

**Comment by yaredtsy** [comment]
hey @melbahysa , yes i am utilising the pinnedRows, and this is not actually a woraround i am modifing the internal code, just to show how it can be implemted,if you think the demo is useable i can try a make a workaround for it.

**Comment by melbahysa** [comment]
hey @yaredtsy Thank you for informing me. I must say, the demo appears to be quite usable and seems to be a suitable approach for our use case. It would be highly appreciated if you could make an attempt to create a workaround.

**Comment by yaredtsy** [comment]
hey @melbahysa i have tried to make a simple workaround you can check it out https://codesandbox.io/s/affectionate-aj-h4p686?file=/demo.tsx.

**Comment by melbahysa** [comment]
hey @yaredtsy I implemented the workaround you provided and it works perfectly. Thank you! 🙏🏼
