### ISSUE TITLE
GridToolbarQuickFilter not filtering numeric values

### ISSUE THREAD

**Issue by JonathanTaylor9** [mui/mui-x#8892]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I'm using a GridToolbarQuickFilter component within a DataGrid component.  I'm trying to use it to filter rows containing data as follows:

Member 1
Member 2
Member 3
Person 1

### Current behavior 😯

If I search for the string 'member' it filters only rows containing that string.  If I search for 'Member 1' it still returns all rows that contain the string 'Member'.

### Expected behavior 🤔

Filtering with the string 'Member 1' should filter out all other rows, leaving just the 'Member 1' row

### Your environment 🌎

System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 19.4.0 - ~\node_modules\.bin\node.CMD
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.64)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.115
    @mui/core-downloads-tracker:  5.11.6
    @mui/icons-material: ^5.11.0 => 5.11.0
    @mui/material: ^5.11.6 => 5.11.6
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.5
    @mui/types:  7.2.3
    @mui/utils:  5.11.2
    @mui/x-data-grid: ^5.17.21 => 5.17.21
    @mui/x-data-grid-pro: ^5.17.20 => 5.17.20
    @mui/x-license-pro:  5.17.12
    @types/react:  18.0.26
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.9.4

Issue spotted in latest Firefox browser.

**Comment by MBilalShafi** [comment]
Can you provide a reproduction example? For me it works fine: https://codesandbox.io/s/data-grid-community-forked-vdc2ot?file=/src/App.tsx
