### ISSUE TITLE
DataGrid v 6.3.1 breaks flexbox layout

### ISSUE THREAD

**Issue by mitya555** [mui/mui-x#8895]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

```
import * as React from "react";
import { DataGrid, GridRowsProp, GridColDef } from "@mui/x-data-grid";

const rows: GridRowsProp = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "MUI X", col2: "is awesome" },
  { id: 3, col1: "Material UI", col2: "is amazing" },
  { id: 4, col1: "MUI", col2: "" },
  { id: 5, col1: "Joy UI", col2: "is awesome" },
  { id: 6, col1: "MUI Base", col2: "is amazing" },
  { id: 7, col1: "Hello", col2: "World" },
  { id: 8, col1: "MUI X", col2: "is awesome" },
  { id: 9, col1: "Material UI", col2: "is amazing" },
  { id: 10, col1: "MUI", col2: "" },
  { id: 11, col1: "Joy UI", col2: "is awesome" },
  { id: 12, col1: "MUI Base", col2: "is amazing" }
];

const columns: GridColDef[] = [
  { field: "id", hide: true },
  { field: "col1", headerName: "Column 1", width: 150 },
  { field: "col2", headerName: "Column 2", width: 150 }
];

export default function App() {
  return (
    <div
      style={{
        height: 300,
        width: "100%",
        display: "flex",
        flexDirection: "column"
      }}
    >
      <button style={{ minHeight: "40px" }}>Button</button>
      <div style={{ flex: 1 }}>
        <DataGrid rows={rows} columns={columns} />
      </div>
    </div>
  );
}
```
v 6.0.3 works properly:
https://codesandbox.io/s/datagrid-forked-14pj7n?file=/src/App.tsx

v 6.3.1 won't assume size (height) of the flex-container (<div style={{ flex: 1 }}>...</div>):
https://codesandbox.io/s/datagrid-forked-ckdmve?file=/src/App.tsx

### Current behavior 😯

DataGrid v 6.3.1 won't assume height of its flex-container, which causes scrollbar appearing on the external container or the entire page. I tested 6.2.1 as well and it has the same bug

### Expected behavior 🤔

DataGrid should have height of its flex-container, data rows scrolling should occur inside the DataGrid. Works properly in DataGrid v 6.0.3

### Context 🔦

This issue breaks layout of my pages when I update DataGrid to v 6.3.1

### Your environment 🌎

Please refer to:
v 6.0.3: https://codesandbox.io/s/datagrid-forked-14pj7n?file=/src/App.tsx
v 6.3.1: https://codesandbox.io/s/datagrid-forked-ckdmve?file=/src/App.tsx

**Comment by boldurean** [comment]
@mitya555 noticed same behaviour for v6.2.1. 

As a short term solution I would recommend you to add additional min-height: 0, min-width: 0 to the *flex: 1* element. As flex item (if it is container) by default have min-height/min-width properties as "auto" and if children takes more space then it wouldn't stop them to grow parent container. 

How it helps.

**Comment by scamden** [comment]
> t's actually not a bug. This is correct behaviour.

Hi @boldurean! Premium customer here. Seems like you have exposed our bad flex layouts because this correct behavior is breaking all over the place for us and often these flex layouts are quite nested. I'm trying to migrate us to v6 and the idea of manually debugging each of 130 (!!!) DataGrid usages is pretty daunting. Is there any workaround I can apply to our core wrapper around this component to make it behave as it did?

**Comment by boldurean** [comment]
> > t's actually not a bug. This is correct behaviour.
> 
> Hi @boldurean! Premium customer here. Seems like you have exposed our bad flex layouts because this correct behavior is breaking all over the place for us and often these flex layouts are quite nested. I'm trying to migrate us to v6 and the idea of manually debugging each of 130 (!!!) DataGrid usages is pretty daunting. Is there any workaround I can apply to our core wrapper around this component to make it behave as it did?

Hi Scamden!

When you have flex child with `flex: 1` property, this container doesn't have **defined** height, respectively if you don't specify height to it or any nested flex children DataGrid will raise an error as _by default, the Data Grid has no intrinsic dimensions. Instead, it takes up the space given by its parent._

I could suggest you a little hack for nested `flex: 1` containers which will force browser to calculate dimensions of grid's wrapper. Consider next example: 

```JavaScript
  <Box sx={{ flex: 1, position: 'relative' }}>
    <Box sx={{ position: 'absolute', inset: 0 }}>
      <DataGrid
         columns={columns}
         rows={rows}
         loading={isFetching}
         disableRowSelectionOnClick
         pagination
         getRowHeight={() => 'auto'}
         slots={{ toolbar: CustomToolbar }}
         slotProps={{
           toolbar: {
             refetch,
             isLoading: isFetching,
             printOptions: { disableToolbarButton: true },
             showQuickFilter: true,
             quickFilterProps: { debounceMs: 500 },
           },
         }}
      />
    </Box>
  </Box>
```

**Comment by scamden** [comment]
Alright thanks @boldurean! I'll give it a whirl. 

(Out of curiosity what exactly changed here? Did Grid used to use this absolute inset positioning before?)

**Comment by boldurean** [comment]
> Alright thanks @boldurean! I'll give it a whirl.
> 
> (Out of curiosity what exactly changed here? Did Grid used to use this absolute inset positioning before?)

I'm not a maintainer so it's hard to tell. I believe there was a reasons for this change or old layout settings/styles produced many other bugs 🤔

**Comment by scamden** [comment]
Ya I agree I think about it behaving correctly. Just tough when so many wind up relying on the incorrect. Either way was just curious, thanks for the throng to try :)

**Comment by cherniavskii** [comment]
Thanks @boldurean for your input!
While I still believe the Data Grid should behave as any other element, we might consider changing the default behavior if we see many users having trouble with it 🙂

Up until now, I think the issues are mostly coming from users upgrading to a newer version with a behavior fixed, which often looks like a regression to them.
@scamden was this the case for you as well?

**Comment by cherniavskii** [comment]
Regarding `position: 'absolute', inset: 0` - interesting, I have never seen this before.
Feels super hacky though 😅

**Comment by boldurean** [comment]
> Regarding `position: 'absolute', inset: 0` - interesting, I have never seen this before.
> 
> Feels super hacky though 😅

Yeah that's a common way to force browser to calculate container dimensions  😅 it works when app doesn't have too many layers which usually is true in case of using grid in their layouts. It's still weird for me that flex-grow/grid fr doesn't get defined dimensions to rely to. It would simplify so many dev pain. Anyway, one day css will be easy.

**Comment by scamden** [comment]
> It's still weird for me that flex-grow/grid fr doesn't get defined dimensions to rely to. It would simplify so many dev pain

ya in my case, i have generally needed to set a width and height on some parent element (can be done with flex, grid or explicitly) and then ensure that none of the children overflow it (cascading flex display through many layers and putting `min-width: 0` on items in flex rows and `min-height: 0` on items in flex columns)

**Comment by scamden** [comment]
@cherniavskii cherniavskii
>  we might consider changing the default behavior if we see many users having trouble with it

fwiw we've seen this on 5 grids so far, it's definitely not 100% of uses but it's probably more than half of the grids I've checked

**Comment by scamden** [comment]
@cherniavskii fyi about 4 more cases. This is extremely pervasive for us
