### ISSUE TITLE
Ability to edit column panel footer for the data grid

### ISSUE THREAD

**Issue by arjot-rai** [mui/mui-x#8896]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

https://github.com/mui/mui-x/issues/8887 -> the solution suggested here causes issues if you have more than 15 columns. As far as I understand this, the only way currently to fix this is recreate the whole gridcolumnpanel from scratch.
![image](https://user-images.githubusercontent.com/51229812/236599521-83dbe017-de6b-4169-a162-3a68a858a465.png)

### Order ID 💳 (optional)

45835

**Comment by yaredtsy** [comment]
hey @arjot-rai 

it is b/c `GridColumnPanel` is taking the full height. set the height of `GridColumnPanel` to less than 100% percent depending on what you need.

![image](https://user-images.githubusercontent.com/34584266/236679253-5f03b5a9-3b83-4ccc-b0e5-d39783a4b154.png)

Demo: https://codesandbox.io/s/suspicious-parm-rxhrws?file=/demo.tsx:440-554

**Comment by arjot-rai** [comment]
thanks that fixed it, can be closed
