### ISSUE TITLE
The Data Grid only shows one row after navigating to next page

### ISSUE THREAD

**Issue by Louai99k** [mui/mui-x#8897]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://stackblitz.com/edit/nextjs-qbczoq

Steps:
1. Just visit the link above to see the full details

Note: I simulated the pagination behavior in the `fetcher` function

### Current behavior 😯

Only shows one row when navigating to next page.

### Expected behavior 🤔

It should show all the rows related to the current page.

### Context 🔦

I'm trying to fetch only necessary data until I go to next page in the table so that I don't need to get all the rows at once.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.68)
  npmPackages:
    @emotion/react: ^11.9.3 => 11.10.6
    @emotion/styled: ^11.9.3 => 11.10.6
    @mui/base:  5.0.0-alpha.127
    @mui/core-downloads-tracker:  5.12.2
    @mui/icons-material: ^5.8.4 => 5.11.16
    @mui/lab: ^5.0.0-alpha.86 => 5.0.0-alpha.128
    @mui/material: ^5.8.4 => 5.12.2
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.4
    @mui/utils:  5.12.0
    @mui/x-data-grid:  5.17.26
    @mui/x-data-grid-pro: ^5.17.26 => 5.17.26
    @mui/x-date-pickers:  5.0.20
    @mui/x-date-pickers-pro: ^5.0.20 => 5.0.20
    @mui/x-license-pro: ^5.17.12 => 5.17.12
    @types/react: ^18.0.21 => 18.2.0
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: ^4.8.4 => 4.9.5
```
</details>

**Comment by yaredtsy** [comment]
hey @Louai99k 

By default, the pagination is handled on the `client`. if you want to handle it on server you have to set the prop `paginationMode` to `server`. you can refer this [Link](https://mui.com/x/react-data-grid/pagination/#server-side-pagination) for more information.

**Comment by Louai99k** [comment]
@yaredtsy thanks for the answer and yes this worked. but now I counter this issue:
Just for the first time when I click on next and then click it again it returns me to first page instead of the third. I did this in the code:
```js
if (isLoading) return <div>loading...</div>;
return (
          <DataGridPro
          // ....
```
and removed `loading` from `DataGridPro` and it worked. in the v6 I didn't saw this problem but if you head to the link you provided and change the version to v5 then try to change the page then defocus it will return to the first page automatically. this is not so critical but still annoying to handle the loading outside while there is one inside.
