### ISSUE TITLE
[pickers] Unable to use custom input field for DatePicker (`slots.textField`)

### ISSUE THREAD

**Issue by MichaelSemchenko** [mui/mui-x#8925]
### Order ID or Support key 💳 (optional)

65703

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

After moving to `@mui/x-date-pickers-pro` I found using `renderInput` no longer possible.

So I've tried to replace 

```
<DatePicker
    renderInput={({ inputRef, inputProps, InputProps }) => (
      <div>
        <input id={id} ref={inputRef} {...inputProps} placeholder={placeholder} />
      </div>
    )}
  />
```

with

```
 const CustomTextInput = (props: TextFieldProps) => {
    const { inputProps, InputProps, inputRef } = props;
    
    return (
      <div ref={InputProps.ref}>
        <input id={id} ref={inputRef} {...inputProps} placeholder={placeholder} />
      </div>
    );
  };

<DatePicker
   slots={{
     textField: CustomTextInput,
   }}
  />
```

After that input looks fine but I met several issues:

1. After I pick the value calendar popup blinking in the top left corner before closing. I suspect this happens because popup positioning relative to the element, what replaced on new value selection
2. Selected value not displayed in input
3. Mask inside the custom input not works

<img width="249" alt="issue2" src="https://user-images.githubusercontent.com/8709333/236923887-3fd788d3-9900-4a70-95b3-87b44c0d0532.png">
<img width="830" alt="issue1" src="https://user-images.githubusercontent.com/8709333/236923895-bd51724c-0268-4fcb-9870-550c82f3fa86.png">

I guess it's not a bug, most likely I'm doing something wrong with `slots` or refs. Unfortunately I found documentation described slots not enough for me. I would be very grateful if someone could assist with this issue

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 113.0.5672.63 (Official Build) (64-bit)
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.35)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base: ^5.0.0-alpha.128 => 5.0.0-alpha.128
    @mui/core-downloads-tracker:  5.12.3
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/lab: ^5.0.0-alpha.129 => 5.0.0-alpha.129
    @mui/material: ^5.12.3 => 5.12.3
    @mui/private-theming:  5.12.3
    @mui/styled-engine:  5.12.3
    @mui/system:  5.12.3
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-date-pickers: ^5.0.20 => 5.0.20
    @mui/x-date-pickers-pro: ^6.3.1 => 6.3.1
    @mui/x-license-pro:  6.0.4
    @types/react: ^18.0.12 => 18.2.5
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ~4.7.4 => 4.7.4
```
</details>

**Comment by ArtHell** [comment]
Maybe this documentation will help a bit https://mui.com/x/react-date-pickers/custom-field/

**Comment by LukasTy** [comment]
Based on your `npx @mui/envinfo` data it looks like you have out-of-sync dependencies. Please update the `@mui/x-date-pickers` and check if the problem still exists.
And as @ArtHell mentioned, consider referencing the `customField` doc page. 🤔

**Comment by MichaelSemchenko** [comment]
@LukasTy @ArtHell thank you for your responses.
I've read the mentioned article and found a [case](https://mui.com/x/react-date-pickers/custom-field/#using-another-input) close to mine ("with the browser input"). As the result I was able to set up what I need but still have an issue with type
```
interface BrowserDateFieldProps
  extends UseDateRangeFieldProps<string>,
    BaseSingleInputFieldProps<string | null, RangeFieldSection, DateRangeValidationError> {}
```

![image](https://github.com/mui/mui-x/assets/8709333/3cdb4199-7720-4072-aa88-c54822d1280a)

I guess I'm wrong with generic type definition. But it's not a big deal, the main issue was solved.

Thank you one more time!

**Comment by LukasTy** [comment]
@MichaelSemchenko [Here is a minimal reproduction](https://codesandbox.io/s/browser-input-example-6kcxj0?file=/demo.tsx) example for you to reference without TS errors. 😉

**Comment by LukasTy** [comment]
Could you elaborate on your expectation?

The `input` component will always receive a string value representation of the date formatted based on the selected format.
But the component itself (DatePicker) has to operate with date objects.
You can select any of the desired adapters, but the value passed in and received (i.e. `onChange`) from pickers will be an object of the used adapter.

Are you by any chance expecting the picker component to work with string values?
If you were relying on this side-effect present in v5, please refer to [this section](https://mui.com/x/migration/migration-pickers-v5/#update-the-format-of-the-value-prop) in the migration guide for more information.

**Comment by MichaelSemchenko** [comment]
@LukasTy yes, I'm a bit confused by returned format (date string vs date object). 

Actually I have a wrapper around the picker that takes string values aka `24/07/2023` and trigger changes in the same format. Honestly I can't understand why we need any adapter here. What is the goal of generic type where we pass `Dayjs`?

**Comment by LukasTy** [comment]
Components API uses generics so that it would function correctly given any of the adapters being used (Date-fns, Moment, Luxon, or Dayjs).
If you need, then by no means, you can build a component wrapper and ensure that on your end the component provides an API functioning with `string` values. 😉

**Comment by MichaelSemchenko** [comment]
I understand **what** is generic, but I can't understand **why** we have to pass an adapter on the level "datepicker->custom input". What if I want to use custom inputs in vanilla without any date utils libraries? The only thing my custom input should know is the format of data (what is actually date string)

**Comment by LukasTy** [comment]
> but I can't understand **why** we have to pass an adapter on the level "datepicker->custom input"

Date needs to be managed and localized internally in many ways, hence, we need some sort of sane API to do that.
If your application needs an API working with string, you are free to implement it on your side knowing your requirements (format and locale).
Are you concerned with the need for a `LocalizationProvider` wrapping your component? If that's the case—don't forget that your provider can wrap your entire application.

Otherwise, please explain your point in more detail, because I fail to understand your expectation.

**Comment by lamhungypl** [comment]
Hi @MichaelSemchenko, 
I face the same issue when replacing `slots: {textfield: CustomizedField}`. 
Debugging what is wrong with those refs and my CustomizedField is hard. Could you share your implementation?

**Comment by jalalbmnf** [comment]
Hi i have same issue also, i used like this:

`       <LocalizationProvider dateAdapter={AdapterDayjs}>
          <DatePicker
            value={value}
                onChange={(newValue:any) => setValue(newValue)}
            slots={{
              field: (params) => (
                <Input
                variant="filled"
                {...params}

                placeholder="date"
                  inputProps={{
                    disableUnderline: true,
                  }}
                  InputLabelProps={{
                    shrink:value ? true : undefined,
                  }}

                />
              ),
            }}

          />
        </LocalizationProvider>` , and it returns these errors
        
        `Type '{ placeholder: string; inputProps: { disableUnderline: boolean; }; InputLabelProps: { shrink: true | undefined; }; label?: ReactNode; id?: string | undefined; inputRef?: Ref<HTMLInputElement> | undefined; ... 22 more ...; variant: "filled"; }' is not assignable to type 'IntrinsicAttributes & ((TextFieldProps & MUIStyledCommonProps<Theme>) & {})'.
  Type '{ placeholder: string; inputProps: { disableUnderline: boolean; }; InputLabelProps: { shrink: true | undefined; }; label?: ReactNode; id?: string | undefined; inputRef?: Ref<HTMLInputElement> | undefined; ... 22 more ...; variant: "filled"; }' is not assignable to type 'FilledTextFieldProps'.
    Types of property 'onChange' are incompatible.
      Type 'FieldChangeHandler<any, any> | undefined' is not assignable to type 'ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement> | undefined'.
        Type 'FieldChangeHandler<any, any>' is not assignable to type 'ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement>'.
          Target signature provides too few arguments. Expected 2 or more, but got 1.`

**Comment by LukasTy** [comment]
> Hi i have same issue also, i used like this

Could you please provide a working example (in codesandbox or any other tool) so that we can see the issue?
From the first look at the solution I can say this:
- it's unclear why the `slot` is being overridden, it would seem that all that is necessary is to change certain props on the `TextField`, for that you can simply pass `slotProps.textField` values and call it a day;
- the `slot` is passed as a render function, which will cause issues. Please [read the documentation](https://mui.com/x/react-date-pickers/custom-components/#overriding-components) on the proper usage of slots.

**Comment by jalalbmnf** [comment]
> > Hi i have same issue also, i used like this
> 
> Could you please provide a working example (in codesandbox or any other tool) so that we can see the issue? From the first look at the solution I can say this:
> 
> * it's unclear why the `slot` is being overridden, it would seem that all that is necessary is to change certain props on the `TextField`, for that you can simply pass `slotProps.textField` values and call it a day;
> * the `slot` is passed as a render function, which will cause issues. Please [read the documentation](https://mui.com/x/react-date-pickers/custom-components/#overriding-components) on the proper usage of slots;

There has not `slot` props

**Comment by jalalbmnf** [comment]
Also i want to customize Input and that is why i used Input component on textField

**Comment by LukasTy** [comment]
> Also i want to customize Input and that is why i used Input component on textField

Please follow the https://mui.com/x/react-date-pickers/custom-field/ documentation with examples on how to provide certain styles to the existing `TextField` component or you can also find examples of using a custom input component instead of the `TextField` from `@mui/material`.

**Comment by jalalbmnf** [comment]
@LukasTy https://codesandbox.io/s/react-typescript-forked-hhx4wp?file=/src/App.tsx it is example, it works like that, does not matter it is Textfield component or Input

**Comment by LukasTy** [comment]
I'm not sure what you are calling working fine. 🤔 
IMHO, your example has multiple problems:
- the initial value is incorrect (empty string is not a correct empty default value, it's supposed to be `null`)
- you are overriding the `field` slot with a `TextField` thus losing all the https://mui.com/x/react-date-pickers/fields/ functionality
- you are defining your slot as a render function, causing your `TextField` to be remounted and thus the popper moving after a selection is done

I'm really not sure why you can't simply do: 
```tsx
slotProps={{
  textField: {
    variant: 'filled',
    placeholder: 'date',
    disableUnderline: true,
  }
}}
```
