### ISSUE TITLE
Programmatically preselecting a row in the DataGrid MUI did not work in JavaScript JSX but it does in typescript TSX version

### ISSUE THREAD

**Issue by luissilvari** [mui/mui-x#8931]
### Order ID or Support key 💳 (optional)

64926

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

# About

Hello there we discover this issue working with the javascript version. Essentially, we need to programmatically preselect a row in the grid using the `selectionModel` and `onSelectionModelChange` functions. but this is not working in the jsx version but it does on tsx... 
Can you guys help us to see what the issue is? or how we can fix it? 
Side note: We are trying to avoid switching to typescript since we have a lot of components already built in the jsx version, and ideally this preselecting feature should works in jsx too...

Here are some sandboxes created to facilitate this.

## Javascript version
https://stackblitz.com/edit/react-ktyrnm?file=demo.js
![preseliting jsx](https://github.com/mui/mui-x/assets/108472015/524a9f01-370d-4971-a66f-49365754e770)

## Typescript version
https://codesandbox.io/s/64104554-can-i-initialize-the-checkbox-selection-in-a-material-ui-datagrid-forked-vxucpj?file=/demo.tsx

![preseletion tsx](https://github.com/mui/mui-x/assets/108472015/83e0b8c4-745e-441f-b592-67ffdcc9592c)

Here are resources we follow to try to fix but none of them works in the js version.
* https://www.appsloveworld.com/reactjs/200/97/programmatically-preselecting-a-row-in-material-uis-data-gridreact 
* https://stackoverflow.com/questions/66399667/material-ui-datagrid-checkbox-row-selection-is-not-working

### Your environment 🌎

<details>

`npx @mui/envinfo` goes here.
Here is the info in our current local machine!

info  - Checking the validity of types
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1635.0), Chromium (113.0.1774.35)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.121
    @mui/core-downloads-tracker:  5.11.16
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/lab: 5.0.0-alpha.123 => 5.0.0-alpha.123
    @mui/material: ^5.11.13 => 5.11.13
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.16
    @mui/system: 5.11.13 => 5.11.13
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-data-grid: 6.0.1 => 6.0.1
    @mui/x-data-grid-pro: ^6.2.1 => 6.2.1
    @mui/x-license-pro:  6.0.4
    @types/react:  18.0.33
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
```
</details>

**Comment by cherniavskii** [comment]
Hey @luissilvari 
You're using different versions of the data grid in provided demos - `6.3.1` in the JS demo and `5.0.0-beta.6` in the TS demo. Both JS and TS should behave identically when the same version is used.

**Comment by luissilvari** [comment]
Ok, I have a feeling the issue may remain on js version, I will give another shot... and creating same env in multiples places....Thanks for quick response!

**Comment by luissilvari** [comment]
yep!. You were always correct. I completely ignore the versions and the type of methods I have to work with, I was expecting to use a method from the v5 in a v6...I need to work wiht `rowSelectionModel` and `onRowSelectionModelChange`

  ```
    // selectionModel={selectionModel}  version 5
     rowSelectionModel={selectionModel} // version 6
    // onSelectionModelChange={(e) => { version 5
     onRowSelectionModelChange={(e: any) => {   // version 6

```

Type script version
https://codesandbox.io/p/sandbox/vxucpj

![typescrio v2](https://github.com/mui/mui-x/assets/108472015/b3dc896a-6a7e-4f78-a731-fa525efc559d)


Javascript version
https://stackblitz.com/edit/react-ktyrnm?file=demo.js
![javascripv2](https://github.com/mui/mui-x/assets/108472015/6696dc39-77e8-440b-ab8e-c50be30308a4)

I really appreciated helping me to solve this issue! Moving to implementing it!
