### ISSUE TITLE
[docs] Update `renderCell`

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#8933]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-data-grid/column-definition/#rendering-cells

### Kind of issue

Unclear explanations

### Issue description

- Have a more meaningful example (maybe a Rating component?)
- Explain that `renderCell` is also being used for autogenerated rows and show a way to opt out of using `renderCell` for autogenerated rows

**Comment by romgrk** [comment]
Also update `valueGetter` as described in https://github.com/mui/mui-x/issues/7673.

**Comment by romgrk** [comment]
@cherniavskii I could replace by a Rating component but I find the current example very clear. Do you still think we should update the example?
