### ISSUE TITLE
[DatePicker]Calendar render error after changed views

### ISSUE THREAD

**Issue by Ardear** [mui/mui-x#8941]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/condescending-ardinghelli-u4d9x3?file=/demo.tsx

I created a variable named views, which is mapped to the prop views of DatePicker. However, I noticed that once I set a new value to views, the current calendar was unable to switch to other calendars. It seems that the calendar was being re-rendered, causing it to display the default view

**Comment by alexfauquette** [comment]
The regression seems to apear between `v6.0.3` and `v6.0.4`

**Comment by Ardear** [comment]
> https://codesandbox.io/s/condescending-ardinghelli-u4d9x3?file=/demo.tsx
The calendar render error seems only happen in `v6.3.1`,and it work between `v6.0.0` and `v6.0.3`.
However,the prop view seems not work between `v6.0.0` and `v6.0.3`,you can try it:
https://codesandbox.io/s/zealous-resonance-brypnx?file=/demo.tsx

**Comment by Ardear** [comment]
> The regression seems to apear between `v6.0.3` and `v6.0.4`

The calendar render error seems only happen in `v6.3.1`,and it work between `v6.0.0` and `v6.0.3`.
However,the prop view seems not work between `v6.0.0` and `v6.0.3`,you can try it:
https://codesandbox.io/s/zealous-resonance-brypnx?file=/demo.tsx

**Comment by Ardear** [comment]
@alexfauquette ,is it fixed? I try the latest version `v6.4.0` in https://codesandbox.io/s/zealous-resonance-brypnx?file=/demo.tsx , it seems still happen ...

**Comment by alexfauquette** [comment]
On GitHub you can see which PR closed the issue

![image](https://github.com/mui/mui-x/assets/45398769/6898c581-0bfc-49af-84d9-9ec99b6980cd)

It has been fixed by a PR merged 2 hours ago, so it will be added in the next release. We usually release on Thursday.

If you want, you can use the package generated by the PR to test your usecase is fixed: https://pkg.csb.dev/mui/mui-x/commit/8e898b0b/@mui/x-date-pickers

Here is your codesandbox with the package generated by the PR. Don't hesitate if you still see the bug on it
https://codesandbox.io/s/muddy-frost-jfwelq?file=/package.json

**Comment by Ardear** [comment]
> On GitHub you can see which PR closed the issue
> 
> ![image](https://user-images.githubusercontent.com/45398769/238594387-6898c581-0bfc-49af-84d9-9ec99b6980cd.png)
> 
> It has been fixed by a PR merged 2 hours ago, so it will be added in the next release. We usually release on Thursday.
> 
> If you want, you can use the package generated by the PR to test your usecase is fixed: https://pkg.csb.dev/mui/mui-x/commit/8e898b0b/@mui/x-date-pickers
> 
> Here is your codesandbox with the package generated by the PR. Don't hesitate if you still see the bug on it https://codesandbox.io/s/muddy-frost-jfwelq?file=/package.json

Ok, thank you
