### ISSUE TITLE
State function not working while assigning the filter row using GridRowsProp with checkboxselection 

### ISSUE THREAD

**Issue by krishnachoudhary274** [mui/mui-x#8944]
Hi Team,

The below code is not working however we don't use GridRowsProp is working fine. Please help us to solve it.\

  const [permissionRows, setPermissionRows] = useState<GridRowsProp>([]);
    const [cellModesModel, setCellModesModel] = useState<GridCellModesModel>({} );
    const [filterRows, setFilterRows] = useState<GridRowsProp>([]);
    const [checkboxSelection, setCheckboxSelection] = useState(false);

const onRowSelectionModelChange = (ids: any) => {
        console.log('handleRowEditStart');
        const selectedIDs = new Set(ids);
        console.log('selectedIDs :' + selectedIDs);
        const selectedRows = permissionRows.filter((row: any) => {
            return selectedIDs.has(row.id);
        });
        console.log(selectedRows);  //getting selected rows
        setFilterRows(selectedRows);
        console.log(filterRows);  //not getting selected rows Issue is here--------------
    };

<DataGrid
                rows={permissionRows}
                columns={columns}
                editMode="cell"
                cellModesModel={cellModesModel}
                checkboxSelection={checkboxSelection}
                disableRowSelectionOnClick
                onRowSelectionModelChange={onRowSelectionModelChange}
                isRowSelectable={(params) =>
                 params.row.Role !== 'Administrator'
                }
                onCellModesModelChange={handleCellModesModelChange}
                onCellEditStart={handleCellEditStart}
                onCellEditStop={handleCellEditStop}
                processRowUpdate={processRowUpdate}
                slots={{
                    toolbar: EditToolbar,
                }}
                slotProps={{
                    toolbar: {
                        permissionRows,
                        cellModesModel,
                        setCellModesModel,
                        setPermissionRows,
                    },
             }}
            />
        </Grid>
    );
}

**Comment by jdeca-decat** [comment]
Hey @krishnachoudhary274 ! In some case, React not update the state immediately. Maybe you should try this solution instead of setFilterRows(selectedRows):

try this in your function:
...
setFilterRows(() => {
console.log(selectedRows);
return selectedRows;
});

or:
...
setFilterRows(selectedRows);
setFilterRows((freshRows) => {
console.log(freshRows);
return freshRows;
});

And for save the selection model normally there is a greater alternative, don't hesitate to ask !
