### ISSUE TITLE
[pickers] Populate DatePicker from Axios[question] 

### ISSUE THREAD

**Issue by jmawebtech** [mui/mui-x#8952]
### Order ID or Support key 💳 (optional)

870e7c4953fecc5d10d5f45487a2fd64Tz01OTUxMixFPTE3MDc1Njk1NDM0OTQsUz1wcmVtaXVtLExNPXN1YnNjcmlwdGlvbixLVj0y

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi,

I am trying to populate the date of a MUI date picker. Please review the screenshot. I am sending a valid date, but the date picker is still blank. values.LastDownloadUtc has a date. Am I setting the wrong property?

![image](https://github.com/mui/mui-x/assets/1679993/22be7305-8789-44a4-8a0e-08b97afbec70)

Here is my code:

`import styled from "@emotion/styled";
import { Save as SaveIcon } from "@mui/icons-material";

import {
    Alert as MuiAlert,
    Box,
    Breadcrumbs as MuiBreadcrumbs,
    Button as MuiButton,
    Card as MuiCard,
    CardContent,
    Checkbox,
    CircularProgress,
    Divider as MuiDivider,
    FormControl as MuiFormControl,
    FormControlLabel,
    Grid,
    IconButton,
    Paper as MuiPaper,
    TextField as MuiTextField,
    Tooltip,
    Typography,
} from "@mui/material";
import { spacing } from "@mui/system";
import { Form, Formik } from "formik";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { RefreshCw } from "react-feather";
import { ConnectionSettingsDto } from "../../../Models/dto/ConnectionSettingsDto";
import agent from "../../../utils/axiosAgent";
import DeleteConnectionAlert from "../../addconnection/DeleteConnectionAlert";
const Divider = styled(MuiDivider)(spacing);
const FormControlSpacing = styled(MuiFormControl)(spacing);
const Breadcrumbs = styled(MuiBreadcrumbs)(spacing);
const Paper = styled(MuiPaper)(spacing);
const Card = styled(MuiCard)(spacing);

const Alert = styled(MuiAlert)(spacing);

const FormControl = styled(FormControlSpacing)`
  min-width: 148px;
`;
const Button = styled(MuiButton)(spacing);
const TextFieldSpacing = styled(MuiTextField)(spacing);

const TextField = styled(TextFieldSpacing)`
  width: 500px;
`;

import * as React from 'react';
import { Dayjs } from 'dayjs';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';

const timeOut = (time: number) => new Promise((res) => setTimeout(res, time));

const userTimeZone: number = (new Date().getTimezoneOffset() / 60) * -1;
function ConnectionSettings() {
    const router = useRouter();
    const { id } = router.query;
    const [values, setValues] = useState<ConnectionSettingsDto>({
        Id: "0",
        UserConnectionId: id as string,
        UserTimeZoneOffset: userTimeZone,
        AddBillOfMaterialsAsLineItems: false,
    });
    useEffect(() => {

        if (!id) {
            return;
        }

        agent.Settings.getSettingsByUserConnectionId(id)
            .then((res) => {
                alert(JSON.stringify(res.data));
                setValues(res.data);
                alert(values.LastDownloadUtc);
            })
            .catch((error) => {
                console.log(error);
            });
    }, [id]);
    const handlePairingFileDownload = () => {
        const userName = window.localStorage.getItem("user");
        agent.QuickBooks.DownloadQwc(userName as string).then();
    };
    const handleSubmit = async ({
        resetForm,
        setErrors,
        setStatus,
        setSubmitting,
    }: any) => {
        try {
            await timeOut(1500);
            values.UserConnectionId = id as string;
            agent.Settings.saveSettings(values);
            await Promise.all([
                resetForm(),
                setStatus({ sent: true }),
                setSubmitting(false),
            ]);
        } catch (error: any) {
            setStatus({ sent: false });
            setErrors({ submit: error.message });
            setSubmitting(false);
        }
    };

    const handleZoneChange = (timezone: number) => {
        setValues({
            ...values,
            UserTimeZoneOffset: timezone,
        });
    };

    const handleLastDownloadUtcChange = (e: any) => {
        setValues({
            ...values,
            LastDownloadUtc: e,
        });
    };

    const handleLastDownloadUtcEndChange = (e: any) => {
        setValues({
            ...values,
            LastDownloadUtcEnd: e,
        });
    };

    const handleLastProductDownloadUtcChange = (e: any) => {
        setValues({
            ...values,
            LastProductDownloadUtc: e,
        });
    };

    const handleLastProductDownloadUtcEndChange = (e: any) => {
        setValues({
            ...values,
            LastProductDownloadUtcEnd: e,
        });
    };

    const handleSelectChange = (e: any) => {
        const val = e.target.checked;
        setValues({
            ...values,
            AddBillOfMaterialsAsLineItems: val,
        });
    };

    const defaultTimeZone = () => {
        setValues({
            ...values,
            UserTimeZoneOffset: userTimeZone,
        });
    };

    const AutoTimeZoneButton = () => (
        <Tooltip title="Get default timezone from Web Browser">
            <IconButton onClick={defaultTimeZone}>
                <RefreshCw />
            </IconButton>
        </Tooltip>
    );

    return (
        <>
            <Formik onSubmit={handleSubmit} initialValues={values}>
                {({ errors, touched, isSubmitting, status, handleChange }) => (
                    <Card mb={6}>
                        <CardContent>
                            <Typography variant="h6" gutterBottom mb={5}>
                                Connection Settings
                            </Typography>
                            <Typography variant="body2" gutterBottom></Typography>

                            {status && status.sent && (
                                <Alert severity="success" my={3}>
                                    Your settings have been saved successfully!
                                </Alert>
                            )}
                            <Button
                                sx={{
                                    marginTop: 5,
                                }}
                                variant="contained"
                                size="large"
                                onClick={handlePairingFileDownload}
                            >
                                <SaveIcon /> Download Pairing File
                            </Button>
                            {isSubmitting ? (
                                <Box display="flex" justifyContent="center" my={6}>
                                    <CircularProgress />
                                </Box>
                            ) : (
                                <Form>
                                    <Grid container spacing={12}>
                                        <Grid item xs={8}>

                                            <Paper mt={3}>
                                                <Grid item xs={8}>
                                                    <FormControl m={2}>
                                                        <TextField
                                                            id="standard-number"
                                                            label="Time Zone Offset"
                                                            type="number"
                                                            value={values.UserTimeZoneOffset}
                                                            onChange={(e) => {
                                                                handleZoneChange(parseInt(e.target.value));
                                                            }}
                                                            InputProps={{
                                                                endAdornment: <AutoTimeZoneButton />,
                                                            }}
                                                            m={2}
                                                        />
                                                    </FormControl>
                                                </Grid>
                                                <Grid item xs={8}>
                                                        <FormControlLabel
                                                        control={
                                                                <Checkbox
                                                                name="AddBillOfMaterialsAsLineItems"
                                                                onChange={handleSelectChange}
                                                                sx={{ "& .MuiSvgIcon-root": { fontSize: 28 } }}
                                                                checked={values.AddBillOfMaterialsAsLineItems}
                                                            />
                                                        }
                                                        label="Bill of Materials Added as Line Items"
                                                    />
                                                    </Grid>
                                                    <Grid container spacing={12}>
                                                <Grid item xs={6}>
                                                        <FormControl m={2}>
                                                            <LocalizationProvider dateAdapter={AdapterDayjs}>
                                                                <DatePicker

                                                                    label="Last Download Date"
                                                                    value={values.LastDownloadUtc ? values.LastDownloadUtc : ""}
                                                                    onChange={(newValue) => {
                                                                        handleLastDownloadUtcChange(newValue)
                                                                    }}
                                                                />
                                                            </LocalizationProvider>
                                                        </FormControl>
                                                        
                                                </Grid>
                                                <Grid item xs={6}>
                                                        <FormControl m={2}>
                                                            <LocalizationProvider dateAdapter={AdapterDayjs}>
                                                                <DatePicker

                                                                    label="Last Download Date End"
                                                                    value={values.LastDownloadUtcEnd}
                                                                    onChange={(newValue) => {
                                                                        handleLastDownloadUtcEndChange(newValue)
                                                                    }}
                                                                />
                                                            </LocalizationProvider>
                                                        </FormControl>
                                                        </Grid>
                                                    </Grid>
                                                    <Grid container spacing={12}>
                                                <Grid item xs={6}>
                                                        <FormControl m={2}>
                                                            <LocalizationProvider dateAdapter={AdapterDayjs}>
                                                                <DatePicker

                                                                    label="Last Product Download"
                                                                    value={values.LastProductDownloadUtc}
                                                                    onChange={(newValue) => {
                                                                        handleLastProductDownloadUtcChange(newValue)
                                                                    }}
                                                                />
                                                            </LocalizationProvider>
                                                       </FormControl>
                                                </Grid>
                                                <Grid item xs={6}>
                                                        <FormControl m={2}>
                                                            <LocalizationProvider dateAdapter={AdapterDayjs}>
                                                                <DatePicker

                                                                    label="Last Product Download End"
                                                                    value={values.LastProductDownloadUtcEnd}
                                                                    onChange={(newValue) => {
                                                                        handleLastProductDownloadUtcEndChange(newValue)
                                                                    }}
                                                                />
                                                            </LocalizationProvider>
                                                        </FormControl>
                                                </Grid>
</Grid>
                                            </Paper>
                                                <Grid container spacing={12} mt={3}>
                                                <Grid item xs={6}>
                                                    <Button
                                                        type="submit"
                                                        variant="contained"
                                                        color="primary"
                                                        disabled={isSubmitting}
                                                    >
                                                        Save changes
                                                    </Button>
                                                </Grid>
                                                <Grid item xs={6}>
                                                    <DeleteConnectionAlert userConnection={id} />
                                                </Grid>
                                            </Grid>
                                        </Grid>
                                    </Grid>
                                </Form>
                            )}
                        </CardContent>
                    </Card>
                )}
            </Formik>
        </>
    );
}

export default ConnectionSettings;
`

### Your environment 🌎

I used Edge version 44.

![image](https://github.com/mui/mui-x/assets/1679993/fdb2e360-0ed5-4a37-996e-7c9df31d1e30)

**Comment by LukasTy** [comment]
Hello, I can stop two potential issues in `value={values.LastDownloadUtc ? values.LastDownloadUtc : ""}`:
1. `""` is not a valid empty date (dayjs) value. An empty value is `null`.
2. I can not see any place where the resolved date value (from axios response) is being transformed into a `dayjs` object. It's unclear which version of `@mui/x-date-pickers` you are using, but if it's v6, then we [no longer handle prop transformation](https://mui.com/x/migration/migration-pickers-v5/#update-the-format-of-the-value-prop) if they are not in the format expected by the chosen adapter.

Please test the ideas and update the issue accordingly. 🙏
