### ISSUE TITLE
[pickers] Add styling customization doc examples

### ISSUE THREAD

**Issue by xdebbie** [mui/mui-x#8962]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-date-pickers/date-range-picker/

### Kind of issue

Missing information

### Issue description

I have been looking for a way to customise the Calendar on the Pickers components (`DatePicker`, `DateTimePicker`, `TimePicker` and `DateRangePicker`), more specifically I would like to change the background colour of the highlighted start and end dates (default: dark blue) and the background colour of the range (default: light blue). 

I have trying to modifying it directly through its class name but unsuccessfully. I then imagined that maybe the right way to do it is through some `slotProps` but it's not clear at all which one is it, or how? Whilst trying things I've noticed that I can access the calendar sx styles through `desktopPaper` and `layout`, but then I have no idea on how to change the colours. I found nothing on the docs regarding that.

Here is my codesandbox:
https://codesandbox.io/s/boring-keldysh-b0ge1f?file=/demo.tsx

 I am on `v6.3.1`.

### Context 🔦

I've been trying to find a way to customise the Pickers' calendar colours, but there are no docs and no examples on how to do it on v6.

**Comment by LukasTy** [comment]
Hey, thank you for creating this issue! 🙏 
It's clear that we could use some more customization examples in regard to styling. 🙈 
It depends on what is the expected result:
- Do you want to change the overall application color scheme? In that case, consider just changing the primary palette color and calendar will adapt using that color
- Do you want custom styling just for the date range calendar? In that case, opt for either a `theme.components` styling overriding (it provides the most intellisense for available styling slot options) or go with `slotProps.sx` if you know what is your particular target.

The reason why `styled` on `DateRangePicker` doesn't work is because it's a complex composed component with multiple subcomponents. To achieve something similar with `styled` API, you'd need to create a `styled` `DateRangePIckerDay` component and pass it to the `slots.day`.

[Here is a demo](https://codesandbox.io/s/epic-fermat-ft1gcg?file=/demo.tsx) combining all three most effective styling options: changing primary palette color, overriding particular component styles via theme `components` and just using the `sx` prop via `slotProps`. 😉

**Comment by LukasTy** [comment]
This issue also already has an RFC created for it: https://github.com/mui/mui-x/issues/6221.

We discussed the feasibility of having demo(s) like the one shown in this chart: 
![pickers-styling-docs-demo drawio](https://github.com/mui/mui-x/assets/4941090/091395bc-de05-4cb9-b6f9-faa8cf18e8ae)
https://drive.google.com/file/d/15Du0RxiYHNFLSSih2Z85OuILg3m4Cgpn/view

In this example, we'd have:
- the components showcased on the left
- all the subcomponents (styleable) listed on the right
- hovering any of the subcomponents could highlight a certain part of the picker component (i.e. hovering `PickersCalendarHeader` would highlight it on the relevant components)
- clicking on the subcomponents would result in the same result as hovering + showing a code snippet of possible ways to override the particular component

This is just a proposal and the best design as well as UX should be the result of @gerdadesign and @noraleonte investigation on this topic in more depth. 🤞

**Comment by noraleonte** [comment]
### Design
I created a [Figma prototype](https://www.figma.com/proto/2z9h8rxbPi7rVqChAx8D54/Date-and-Time-pickers?page-id=1716%3A57674&type=design&node-id=1754-71904&viewport=698%2C218%2C0.11&scaling=min-zoom&starting-point-node-id=1754%3A71904) with a potential solution for this. 

The main idea here is to have a rendered example for a component (`DateTimePicker` in the prototype - but it can be any component) and a list of its subcomponents we support customization/we have examples to show. The user can highlight a subcomponent by either hovering/clicking on the rendered picker, or by selecting something from the menu that's on the left side. 
_I introduced the menu as an alternative selection method because_
- _if the list is longer, it's easier to look at the menu and choose from there_
- _In time, we might think about supporting nested subcomponent examples, and maybe selecting them from the menu could be easier_

Most components can be customized in different ways (either by customizing the theme globally or with styled components, etc) - but usually when a user wants to customize something, they are not looking to see all approaches, but rather for a **specific approach** based on their needs. Delivering information that is actually relevant for a user in a more atomic way leads to better UX. To achieve this, we would have a dropdown that switches the code example shown based on the selected value. 🛩️ 

I also explored a few other variations for how this can look with different companies - you can check them out in [this Figma file](https://www.figma.com/file/2z9h8rxbPi7rVqChAx8D54/Date-and-Time-pickers?type=design&node-id=1716%3A57674&t=jsQ6K9DjBZouvRuy-1)

### Implementation

An idea for the implementation could be this
- create a **new** wrapper component (similar approach to the current demo container - but this version would not support tweaking the code and demoing simultaneously - at least in the first iteration, until we have a solid ground and user feedback)
- this component would receive 
    - a child component (the one that is rendered and supports highlighting on hover/click)
    - a list of subcomponent names that have examples
Having the list of subcomponent names, and knowing that our css classes are pretty consistent with the names, we can check if a hovered subcomponent is in the list, and if so, we parse a code example for that subcomponent from a config file. 


Some subcomponents are really nested, but for the first iteration it would be best to stick to giving examples for just the first level of subcomponents. Later on, we can think about supporting nested examples.

**Comment by oliviertassinari** [comment]
> Your demo is also quite nice and it'd be really cool if we could have something as well explained as this in the docs since unfortunately I don't think it's very intuitive as it is right now for anyone trying to customise the Pickers (specially when you do not intend to change the whole theme's primary colours and so)

This sounds like a global MUI issue, applying to all the components: how to customize the UI? I can make the connection to:

- What @DavidCnoops was working on the idea of a component customizer, a theme builder on steroids.
- @samuelsycamore and the idea to create a tutorial to train developers on how to use the Chrome dev tools & the class names to know where to customize what.
- We talked briefly about the idea to train an AI to do this. https://www.notion.so/mui-org/AI-for-creating-UIs-a003ff4505ec4133b77d607e24f0b425?pvs=4#39ae27c9f9f4400b92991185f5b5ea9f
- @danilo-leal exploration on how to documenting the anatomy of Core components https://www.figma.com/file/MfirV6NOFAp2xxAZX1QU1V/Documentation?type=design&node-id=1329-16687&t=XqSIECrWXRzfJIiX-0

<img width="474" alt="Screenshot 2023-06-17 at 21 19 39" src="https://github.com/mui/mui-x/assets/3165635/a8fa786a-d7ed-4f07-8f13-332c8203a656">

Other similar implementations:

- https://baseweb.design/components/file-uploader/

<img width="617" alt="Screenshot 2023-06-17 at 21 13 35" src="https://github.com/mui/mui-x/assets/3165635/02779cd3-52b7-4824-a067-aa9a5be901cf">

**Comment by danilo-leal** [comment]
Really enjoyed @noraleonte's prototype there! 🙌  It's something that y'all could start here with the Pickers but it is certainly an approach that can be used for all components moving forward ⎯ it'd be particularly sweet for those that share the same characteristic of being built out of a bunch of nested subcomponents.

**Comment by LukasTy** [comment]
I'm listing all the relevant issues just to have some back-links into problems that are already clear with styling customization.

- https://github.com/mui/mui-x/issues/6221 an RFC about the improvement and addition of the documentation for missing `styled` components;
- https://github.com/mui/mui-x/issues/9508 problems styling the selected date range days;
- https://github.com/mui/mui-x/issues/5232 issues applying styling to date range calendar, but they are mostly solved already;
- https://github.com/mui/mui-x/issues/4559 changing dimensions of the popper container (paper);
- https://github.com/mui/mui-x/issues/4565 changing dimensions of the range calendar;
- https://github.com/mui/mui-x/issues/4669 styling subcomponents (codesandbox examples in comments);
- https://github.com/mui/mui-x/issues/4553 desire to style arrows switcher/header;
- https://github.com/mui/mui-x/issues/4552 desire to style date calendar subcomponents (parts of it);
- https://github.com/mui/mui-x/issues/5779 styling action bar
- https://github.com/mui/mui-x/issues/6218 styling month calendar and header;
- https://github.com/mui/mui-x/issues/6897 changing dimensions of the `TimeClock`;
- https://github.com/mui/mui-x/issues/8506 styling the `dialog`;
- https://github.com/mui/mui-x/issues/8507 customizing the day (having a custom week picker);
