### ISSUE TITLE
Datagrid PRO error - Cannot read properties of null (reading 'scrollHeight')

### ISSUE THREAD

**Issue by radu-nicoara-bayer** [mui/mui-x#8966]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
I could only reproduce with our own backend

Steps:

1. Set a datagrid with server-side pagination
2. change the pages
3. After a few pages of scrolling, the error will appear:
`Cannot read properties of null (reading 'scrollHeight')`

![image](https://github.com/mui/material-ui/assets/98585495/d90842f4-ebae-451f-8f7c-41be2340f6ee)

### Current behavior 😯

An error is thrown during the page navigation on server-side rendering

### Expected behavior 🤔

No weeo should be thrown

### Context 🔦

I am trying to add server-side pagination to our project

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by gajanandk** [comment]
add captureMenuScroll={false}

**Comment by gajanandvrm** [comment]
add captureMenuScroll={false}
<ReactMultiSelectCheckboxes captureMenuScroll={false} options={options}/>
