### ISSUE TITLE
[fields] Should select 1st section instead of last when clicking on the right of the content

### ISSUE THREAD

**Issue by MathieuUrstein** [mui/mui-x#8967]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-date-pickers/date-field/#uncontrolled-vs-controlled

Steps:
If you click on the following area:
![image](https://github.com/mui/mui-x/assets/3322861/2fd3a6db-5d3e-4037-9d24-3b9f7b9d4004)

### Current behavior 😯

You get the last field selected:
![image](https://github.com/mui/mui-x/assets/3322861/2e1fa92e-8493-4fcd-a91c-5bb8d1458dea)

### Expected behavior 🤔

When clicking on the blank area, I expect to be able to fill the field from left to right. In this case, I expect the month to be selected

**Comment by flaviendelangle** [comment]
The follow diff seems to work:

```tsx
diff --git a/packages/x-date-pickers/src/internals/hooks/useField/useField.ts b/packages/x-date-pickers/src/internals/hooks/useField/useField.ts
index 3b1824886..9db35ec1e 100644
--- a/packages/x-date-pickers/src/internals/hooks/useField/useField.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useField/useField.ts
@@ -84,12 +84,20 @@ export const useField = <
       return;
     }
     const browserStartIndex = inputRef.current!.selectionStart ?? 0;
-    const nextSectionIndex =
-      browserStartIndex <= state.sections[0].startInInput
-        ? 1 // Special case if browser index is in invisible characters at the beginning.
-        : state.sections.findIndex(
-            (section) => section.startInInput - section.startSeparator.length > browserStartIndex,
-          );
+
+    let nextSectionIndex: number;
+    if (browserStartIndex <= state.sections[0].startInInput) {
+      // Special case if browser index is in invisible characters at the beginning
+      nextSectionIndex = 1;
+    } else if (browserStartIndex >= state.sections[state.sections.length - 1].endInInput) {
+      // If the click is after the last character of the input, then we want to select the 1st section.
+      nextSectionIndex = 1;
+    } else {
+      nextSectionIndex = state.sections.findIndex(
+        (section) => section.startInInput - section.startSeparator.length > browserStartIndex,
+      );
+    }
+
     const sectionIndex = nextSectionIndex === -1 ? state.sections.length - 1 : nextSectionIndex - 1;
 
     setSelectedSections(sectionIndex);
```

I'm putting the "good first issue" label, it can be an easy one for @noraleonte

**Comment by yamatohagi** [comment]
Hi there,

I'm fairly new to contributing to open-source projects and I'm eager to give it a shot with this issue. I noticed that @noraleonte was mentioned as a potential person to tackle this. However, I'm interested in taking this on if it's okay.

Thank you for your consideration.

**Comment by flaviendelangle** [comment]
Hi,

Thanks for your interest in this issue.
I will keep that one for @noraleonte, but feel free to look for another issue, I can help you with the fix if needed :+1:
