### ISSUE TITLE
license key problem in dynamic build in containers 

### ISSUE THREAD

**Issue by dizag** [mui/mui-x#8972]
### Order ID or Support key 💳 (optional)

65798

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello ,
I bought a one-year license for your product, but the question arose as to how I would implement the license for the specific project.
Because the frontend I make includes microfrontends that are built dynamically in containers (the build source is taken from git). Accordingly, I would not like the license to be in git, besides, after a year, how will the client use it, since I am a contractor.
Reading the EULA agreement, I got the impression that the customer must also purchase a license and while using this frontend must pay for it. Considering that everything is built dynamically, the license should be for life time, which is extremely unacceptable.

Is there a way out of this situation?

### Your environment 🌎

SingleInputDateTimeRangeField 
and
StaticDateRangePicker

**Comment by oliviertassinari** [comment]
I answered this on Sunday at https://mui.zendesk.com/agent/tickets/8511.

**Comment by dizag** [comment]
hey, i received your responce but isn't satisfying at all from main point

**Comment by dizag** [comment]
i'll ask my money back

**Comment by oliviertassinari** [comment]
Please, let's continue over the sales support channel (Zendesk). It doesn't seem that the issue is technical. I'm locking this thread.
