### ISSUE TITLE
[pickers] stop month switch transition

### ISSUE THREAD

**Issue by srbadni** [mui/mui-x#8993]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I use the Datepicker component, by default a transition happens between switching months, which i add its image in below.

![Screenshot 2023-05-15 153533](https://github.com/mui/mui-x/assets/77675736/34af5432-ac39-4246-bda3-99baf91a7dca)

### Expected behavior 🤔

I want to prevent this transition somehow

**Comment by LukasTy** [comment]
Consider using [the `reduceAnimations` prop](https://mui.com/x/api/date-pickers/date-picker/#:~:text=in%20particular%20orientation.-,reduceAnimations,-bool). 😉
