### ISSUE TITLE
[DataGridPro] aggregations blow up exponentially

### ISSUE THREAD

**Issue by githorse** [mui/mui-x#8999]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

[CodeSandbox demo](https://codesandbox.io/p/sandbox/8t1722)

### Current behavior 😯

I've performed an informal grouping-and-aggregation benchmark across several popular grids (MUI, [Material React Table](https://www.material-react-table.com/), [Tanstack](https://tanstack.com/table/v8), and AG Grid) in the [above example](https://codesandbox.io/p/sandbox/8t1722?file=%2Fsrc%2FMUI.tsx%3A1%2C1). MUI's performance seems to degrade exponentially:

**Rough Loading Time (ms)[^1]**

|Rows|MUI    |MRT      |Tanstack  |AG     | Best Possible|
|--------|---------|-----------|------------|----------|-------------------|
|1k      | 250   |500        |250        |50        |50                  |
|10k    | 1000 | 1000     |500        |250      |50                  |
|50k    | 13000|2000     |1500      |800      |150                |  
|100k  |💣*    |2500      |2500      |1200    |250                |

*Somewhere between 50k and 100k records the MUI grid blows up and kills the whole browser tab. 

The expected computational complexity for this group-and-sum operation is linear (which is what we see, roughly, with the other solutions) so there seems to be a problem with the MUI algorithm.

[^1]: Most grids don't have a good way to instrument the exact loading time, so these are basically eyeballed and not very accurate. Obviously they'll be different on different machines. Nevertheless the overall trends are clear enough.

### Expected behavior 🤔

Clearly the MUI grid can't be quite as fast as the optimized custom aggregation, but at 50k+ records, the grid should still perform an aggregation in a reasonable amount of time (and not blow up).

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 4.98 GB / 15.32 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.4 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Managers:
    Cargo: 1.51.0 - ~/.cargo/bin/cargo
    pip3: 22.0.2 - /usr/bin/pip3
  Utilities:
    CMake: 3.22.1 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.3.0 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
    Ninja: 1.10.1 - /usr/bin/ninja
    FFmpeg: 4.4.2 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 23.0.6 - /usr/bin/docker
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    Vim: 0.10.0 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Perl: 5.34.0 - /usr/bin/perl
    Protoc: 3.17.0 - /usr/local/bin/protoc
    Python3: 3.10.6 - /usr/bin/python3
  Databases:
  Browsers:
    *Chromium: 113.0.5672.63
  Monorepos:
    Yarn Workspaces: 3.2.4
    Lerna: 5.6.2


```
</details>

### Order ID or Support key 💳 (optional)

46840

**Comment by cherniavskii** [comment]
Also reported in https://github.com/TanStack/table/discussions/4860
