### ISSUE TITLE
Possibility to memoize rows when pinnedColumns are set

### ISSUE THREAD

**Issue by martinhonza** [mui/mui-x#9013]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi, 
would it be possible to implement row memoization also if there are columns that are pinned ?
We currently pin by default the checkbox column and it causes the row memoization to fail, it fails at comparing renderedColumns although if I put into memo deepEqual it passes as equal.

### Examples 🌈

https://codesandbox.io/s/strange-shadow-717s3z?file=/demo.tsx

### Order ID 💳 (optional)

#54652

**Comment by romgrk** [comment]
I'll cover this as part of #9001 work.
