### ISSUE TITLE
[DateTimePicker] Space sets subfield value to 00

### ISSUE THREAD

**Issue by davakos** [mui/mui-x#9014]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/nifty-knuth-sk51n1

This is the same code as in [Date Time Picker Basic usage](https://mui.com/x/react-date-pickers/date-time-picker/#basic-usage), I have just added `ampm={false}` to `DateTimePicker` so that typing `<space>` between date and time subfields sets the `hh` subfield to `00`. 

Steps:
1. Enter the following values into the Date time picker: `05/05/2023<space>05:05` - ensure that you enter all characters, including the slashes, colons, and space characters separating date fields 
2. Note that when you type a field separator, such as a slash `/` or colon `:`, the input is ignored and the separator is automatically added as part of the field value

### Current behavior 😯

Some field separators, such as slashes `/` and colons `:`, are ignored when they are entered as field input.
However, `<space>` is not ignored and will instead make the current focused subfield value `00` (in this example, the `hh` subfield).

Following the steps above, the input will show `05/05/2023 00:05` instead of the intended input of `05/05/2023 05:05`.

### Expected behavior 🤔

Typing `<space>` in field input should be ignored, like other separator characters.

Following the steps above, I would expect the input to display the value `05/05/2023 05:05` instead of `05/05/2023 00:05`.

### Context 🔦

There are 2 instances where I can see this causing confusion:

1. If the user is manually entering input into the field and they are not watching the component to see that it is automatically entering the field separators for them (e.g., `/`, `:`, `<space>`), so they manually enter space to separate date and time subfields and this inadvertently sets the field after the space to `00`.
2. When performing automated testing, such as via [react-testing-library's user-event type()](https://testing-library.com/docs/user-event/utility#type), e.g.,
```
const { user } = render(
    <DateTimePicker label="Basic date time picker" ampm={false} />
);

const inputField = screen.getByRole("textbox", { name: /basic date time picker/i });
await user.type(inputField, "05/05/2023 05:05");
expect(inputField).toHaveDisplayValue("05/05/2023 05:05");
```

test fails:
    Expected element to have display value:
      `05/05/2023 05:05`
    Received:
      `["05/05/2023 00:05"]`

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: Not Found
    npm: 9.6.6 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
  npmPackages:
    @mui/x-date-pickers: ^6.4.0 => 6.4.0
```
</details>

**Comment by flaviendelangle** [comment]
Maybe pressing `Space` should open the picker (like on the browser native input).

**Comment by davakos** [comment]
Since space can be a valid date/time input character, I think using space to open the picker's calendar popover could be confusing unless the cursor is currently focused on the calendar icon input adornment

**Comment by flaviendelangle** [comment]
It would mimic the behavior of [the native input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) which has (at least on Chrome) an opening when clicking on the end adornment AND when pressing Space.
So I suspect it would follow the ARIA rules.

But indeed, unlike the browser input, we have formats with spaces.

**Comment by alexfauquette** [comment]
For splitting works, we will only remove the space interaction to solve this issue and open a new one fro add keyboard interaction with <kbd>Space</kbd>

**Comment by LukasTy** [comment]
Minor note: <kbd>Space</kbd> to open the widget is not specified in [ARIA example](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/) or date picker guidelines, but IMHO it makes sense starting v6, where we ditched the regular plain `input` element in favor of the smart field.

**Comment by flaviendelangle** [comment]
I don't think we created the issue to open when pressing <kbd>Space</kbd> :grimacing: 
I'm taking care of the "00" value being applied

**Comment by LukasTy** [comment]
> I don't think we created the issue to open when pressing Space 😬
> I'm taking care of the "00" value being applied

@flaviendelangle We've discussed this option here: https://github.com/mui/mui-x/issues/13446
