### ISSUE TITLE
[pickers] Using custom input field for SingleInputDateRangeField defined as slot field for DatePicker

### ISSUE THREAD

**Issue by MichaelSemchenko** [mui/mui-x#9016]
### Order ID or Support key 💳 (optional)

65703

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I found in [documentation](https://mui.com/x/react-date-pickers/custom-field/#use-single-input-fields-on-range-pickers) a nice ability to use combined input field for a _DateRangePicker_:
```
<DateRangePicker slots={{ field: SingleInputDateRangeField }} />
```

But in the same time I would like to use my own-styled input for SingleInputDateRangeField component, defined as a slot field for _DateRangePicker_.

There is a [good example](https://mui.com/x/react-date-pickers/custom-field/#using-another-input) ("With the browser input" section) how to use native inputs for date range pickers:
![image](https://github.com/mui/mui-x/assets/8709333/406ccbd2-4733-4b35-952b-d093e61bb8c5)

But I would like to keep start and end dates combined same with _SingleInputDateRangeField_. As I see from API _SingleInputDateRangeField_ also support `slots`. So I need a kind of nested structure where _DateRangePicker_ has a _SingleInputDateRangeField_ as a slot field, but _SingleInputDateRangeField_ has my custom input component as a slot field in the same time.  In a perfect case this would be something like:
```
<DateRangePicker slots={{ field: SingleInputDateRangeField }} slotProps={{ field: MyCustomInput }} />
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 113.0.5672.93 (Official Build) (64-bit)
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.42)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base: ^5.0.0-beta.0 => 5.0.0-beta.1
    @mui/core-downloads-tracker:  5.13.1
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/lab: ^5.0.0-alpha.129 => 5.0.0-alpha.129
    @mui/material: ^5.13.0 => 5.13.1
    @mui/private-theming:  5.12.3
    @mui/styled-engine:  5.12.3
    @mui/system:  5.12.3
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-date-pickers: ^5.0.20 => 5.0.20
    @mui/x-date-pickers-pro: ^6.4.0 => 6.4.0
    @mui/x-license-pro:  6.0.4
    @types/react: ^18.0.28 => 18.2.6
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ~4.7.4 => 4.7.4
```
</details>

**Comment by MichaelSemchenko** [comment]
Thank you @flaviendelangle! That's exactly what I need.
I found only 1 issue: `endAdornment` not works in exoected way: icon displaying but not clickable
```
<DateRangePicker
    slots={{ field: BrowserSingleInputDateRangeField }}
    slotProps={{ field: { InputProps: { endAdornment: <CalendarIcon /> } } }}
    {...props}
  />
```

**Comment by LukasTy** [comment]
> I found only 1 issue: `endAdornment` not works in exoected way: icon displaying but not clickable

It's because we do not support adornment-click opening for range pickers. The range pickers open on input click.
If you need/want, you can control the range picker opening behavior and add the icon click open behavior on your side.

**Comment by flaviendelangle** [comment]
I'm closing it since the question is answered :+1:

**Comment by MichaelSemchenko** [comment]
Thank you for the answer @LukasTy. 
As I see from the API we're able to control open state with `open` param. But for this purposes I have to trigger the event from my `SingleInputDateRangeField` to the upper level. Is any way to get the reference to `DatePicker` inside the `SingleInputDateRangeField`? Or perhaps there is another way to control the datepicker state from the component defined as `slot.field`?
