### ISSUE TITLE
[pickers] Date Time Picker onChange - seconds and ms from nowhere

### ISSUE THREAD

**Issue by ArtHell** [mui/mui-x#9023]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/wkurwia-mnie-to-forked-sw3xvr?file=/src/App.test.tsx

Steps:
1. Write a test on DateTimePicker wrapped in LocalizationProvider with any adapter.
2. Try to type new date and time with fireEvent or user-event.
3. Spy on onChange and check the date parameter.

### Current behavior 😯

onChange fires with Date object that has seconds and milliseconds. They appear from nowhere.
![image](https://github.com/mui/mui-x/assets/10870902/f93ff5a6-4d87-4c18-9c42-350bd6bef139)

### Expected behavior 🤔

I expect to receive date and time with 00.000 seconds and milliseconds.

### Context 🔦

I'm trying to write some tests for my code.

### Your environment 🌎

Look at sandbox https://codesandbox.io/s/wkurwia-mnie-to-forked-sw3xvr?file=/src/App.test.tsx

**Comment by Escalion86** [comment]
Same issue

**Comment by alexfauquette** [comment]
> don't show clock for choose time

It has been removed on desktop. More info in migration guide: https://mui.com/x/migration/migration-pickers-v5/#stop-rendering-a-clock-on-desktop

**Comment by flaviendelangle** [comment]
I will handle it in #9019

**Comment by ArtHell** [comment]
thank you @flaviendelangle

**Comment by Escalion86** [comment]
> > don't show clock for choose time
> 
> It has been removed on desktop. More info in migration guide: https://mui.com/x/migration/migration-pickers-v5/#stop-rendering-a-clock-on-desktop

Actually component don't show any popup for choosing time.. clock or list...
