### ISSUE TITLE
How to add file tree? 

### ISSUE THREAD

**Issue by yitao-mutable** [mui/mui-x#9025]
### Order ID or Support key 💳 (optional)

66654

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I cannot figure out how to use the file tree in the demo: 
![image](https://github.com/mui/mui-x/assets/106548387/cf059937-e96c-4ddf-9e15-699adc8abf4f)

I know its status is experimental but I think I can still use it somehow right?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
The component you mentioned actually uses the [`TreeView`](https://mui.com/material-ui/react-tree-view/) component from **material-ui**, here's its [source file](https://github.com/mui/material-ui/blob/master/docs/src/components/showcase/FolderTreeView.tsx) if you need to check out the code.
