### ISSUE TITLE
[docs] Variant not passed to DateField

### ISSUE THREAD

**Issue by roli93** [mui/mui-x#9038]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Include a DatePicker
2. Pass `variant="standard"`
3. verify the prop is not passed down to DateField nor applied

The prop is passed down to DatePicker:

<img width="488" alt="image" src="https://github.com/mui/mui-x/assets/4173986/cd5ca869-33e9-4cb5-8dd2-1efeb4539271">

Not present in DateField:

<img width="490" alt="image" src="https://github.com/mui/mui-x/assets/4173986/336faf4d-c180-4e33-b4fa-85c823c3f0d6">

Not applying variant to datefield input:

<img width="262" alt="image" src="https://github.com/mui/mui-x/assets/4173986/acb570b8-85c7-4d05-8ccd-d8eab8d77456">

### Current behavior 😯

When passing `variant` to DatePicker, the `variant` prop is not passed down to de `DateField` sub-component and therefore not applied

```
                <DatePicker
                  value={this.selectedDate}
                  format="MM/DD/YYYY"
                  onChange={this.onDateChange}
                  maxDate={moment().add(payment.allowedPaymentDateRange, 'days')}
                  disablePast
                  minDateMessage={payment.dateErrorMessage}
                  maxDateMessage={payment.dateErrorMessage}
                  fullWidth
                  disabled={this.submitting}
                  variant="standard"
                />
```

### Expected behavior 🤔

According to https://mui.com/x/react-date-pickers/date-picker/#component-composition, the documented props for DateField, when passed to the DatePicker, should be passed down to the DateField

### Context 🔦

I want to style a DatePicker using the "standard" variant. If I manually pass the prop using React DevTools it works.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Using Chrome

  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.10.8 => 11.10.8 
    @emotion/styled: ^11.10.8 => 11.10.8 
    @mui/base:  5.0.0-alpha.128 
    @mui/core-downloads-tracker:  5.12.3 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.129 => 5.0.0-alpha.129 
    @mui/material: ^5.12.3 => 5.12.3 
    @mui/private-theming:  5.12.3 
    @mui/styled-engine:  5.12.3 
    @mui/styles: ^5.12.3 => 5.12.3 
    @mui/system:  5.12.3 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.3 
    @mui/x-date-pickers: ^6.4.0 => 6.4.0 
    @types/react: ^18.0.33 => 18.0.33 
    react: ^17.0.0 => 17.0.2 
    react-dom: ^17.0.0 => 17.0.2 
    typescript: ^3.9.10 => 3.9.10 

```
</details>

**Comment by roli93** [comment]
The result can be achieved by using `slotProps`:

```                  slotProps={{textField: {variant: "standard"}}}
```
However this is at odds with the stated docs above. At the very least I thinks docs could be updated to reflect this.

**Comment by flaviendelangle** [comment]
All the props **documented** for the field are also available at the picker level for simplicity.
But we don't handle all the props that are extended from the `TextField`, because they depend on the UI implementation of the field.


We can improve the wording @richbustos maybe we can discuss this
The problematic part is this section

![image](https://github.com/mui/mui-x/assets/3309670/4a676cd9-e645-4876-acd4-7f3c3ad1a417)
