### ISSUE TITLE
[pickers] DateRangePicker popup with calendar positioned incorrectly (if we're using custom input field)

### ISSUE THREAD

**Issue by MichaelSemchenko** [mui/mui-x#9040]
### Order ID or Support key 💳 (optional)

65703

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

This question is a continuation of this [task](https://github.com/mui/mui-x/issues/9016): calendar popup opening not works for range pickers if we're using custom input field. There was a [working example provided](https://codesandbox.io/s/date-and-time-pickers-forked-bxyefo?file=/src/App.tsx) in ticket above. 

I found 2 issues with this example.
1. Input click also does not lead to opening a popup with calendar as was mentioned.
2. If I open calendar manually popup field wrongly positioned in the left top corner (I suspect this happens because of wrong ref relative to which the popup is positioned).

There is [my code example](https://codesandbox.io/s/date-and-time-pickers-forked-pyx8kz?file=/src/App.tsx) with open logic  based on initial code example. You can see issue there.

P.S. If someone know more fancy way to make adornment clickable please let me know :)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 113.0.5672.93 (Official Build) (64-bit)
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.42)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base: ^5.0.0-beta.0 => 5.0.0-beta.1
    @mui/core-downloads-tracker:  5.13.1
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/lab: ^5.0.0-alpha.129 => 5.0.0-alpha.129
    @mui/material: ^5.13.0 => 5.13.1
    @mui/private-theming:  5.12.3
    @mui/styled-engine:  5.12.3
    @mui/system:  5.12.3
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-date-pickers: ^5.0.20 => 5.0.20
    @mui/x-date-pickers-pro: ^6.4.0 => 6.4.0
    @mui/x-license-pro:  6.0.4
    @types/react: ^18.0.28 => 18.2.6
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ~4.7.4 => 4.7.4
```
</details>

**Comment by LukasTy** [comment]
Hello @MichaelSemchenko 
[I've tried making adjustments](https://codesandbox.io/s/date-and-time-pickers-forked-vgnis5?file=/src/App.tsx) to your demo in order for refs to work correctly (InputProps.ref) was always empty.
You were also missing the necessary `fieldType = 'single-input'` prop on the component to ensure correct field state management.
Let me know if you still see any issues.

P.S. Do you think it would be useful having a demo overriding the single input date range picker input with browser input [alongside the DatePicker and DateRangePicker with multi-input fields](https://mui.com/x/react-date-pickers/custom-field/#using-another-input)?

**Comment by MichaelSemchenko** [comment]
Hello @LukasTy,
Thank you very much, it works perfect.
Yes, I think having such demo would be great!
