### ISSUE TITLE
[question] How execute a method after clicking on Show All and Hide All button in GridToolbarColumnsButton component

### ISSUE THREAD

**Issue by Arkamit** [mui/mui-x#9044]
### Order ID or Support key 💳 (optional)

59954

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is there a way to execute a custom method after Show All or Hide All is clicked and their respective work is done?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    Browser: Google Chrome version: 113.0.5672.94
    System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 AMD EPYC 7571
    Memory: 11.63 GB / 15.52 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Managers:
    pip2: 18.0 - /usr/bin/pip2
    pip3: 20.2.2 - /usr/bin/pip3
    Yum: 3.4.3 - /usr/bin/yum
  Utilities:
    Make: 3.82 - /usr/bin/make
    Git: 2.32.0 - /usr/bin/git
  Virtualization:
    Docker: 20.10.13 - /usr/bin/docker
  IDEs:
    Nano: 2.9.8 - /usr/bin/nano
    VSCode: 1.78.2 - /home/adutta@huronconsultinggroup.com/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.7.10 - /usr/bin/python3
  Databases:
    SQLite: 3.7.17 - /usr/bin/sqlite3
```
</details>

**Comment by MBilalShafi** [comment]
I think you are looking for `onColumnVisibilityModelChange` prop.
It gets fired once column visibility model changes, which happens when the visibility of some column changes (which also happens on `Show All` or `Hide All` click)

Here's a codesandbox showing that: https://codesandbox.io/s/column-visibility-model-change-k480lg?file=/src/App.tsx

**Comment by Arkamit** [comment]
@MBilalShafi Thank you for your response. I guess this will work but I cannot test it right now as I am out of office. I will get back to you once I try this solution out. Thanks again.

**Comment by Arkamit** [comment]
Thank you @MBilalShafi for your answer, the property seems to work the way you mentioned.
