### ISSUE TITLE
QuickFilter loses focus on remote pagination

### ISSUE THREAD

**Issue by jakeleventhal** [mui/mui-x#9047]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

```tsx
components={{
  Toolbar: () => quickFilter ? (
    <Box>
      <GridToolbarQuickFilter debounceMs={300} size="small" variant="outlined" />
    </Box>
  ) : null}
}
```

### Current behavior 😯

![May-19-2023 11-32-47](https://github.com/mui/mui-x/assets/15133828/b96f29c3-e458-4bc2-ae32-c18d37bd5936)

### Expected behavior 🤔

Focus should not be lost after server-side query

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.9.1 - ~/.nvm/versions/node/v18.9.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v18.9.1/bin/npm
  Browser:
    Safari: 16.5
```
</details>

### Order ID or Support key 💳 (optional)

66251

**Comment by oliviertassinari** [comment]
This looks expected. In your code, a new component is created at render time. So in the next render, a new component is provided, React unmount the DOM and mounts it again, which drops any UI states like focus.

The solution is to create the component outside of the render.

**Comment by jakeleventhal** [comment]
This doesn't really address the issue. My toolbar component is actually more complicated than that and takes in several props.
```tsx
<Box
  alignItems="center"
  display="flex"
  justifyContent="space-between"
  sx={{ padding: (theme) => `${theme.spacing(1)} ${theme.spacing(1)}` }}
>
  <Box alignItems="center" display="flex" mt={1}>
    {title ? (
      <Box mr={2}>
        <Typography variant="h6">{title}</Typography>
      </Box>
    ) : null}
    {quickFilter ? (
      <Box>
        <GridToolbarQuickFilter debounceMs={300} size="small" variant="outlined" />
      </Box>
    ) : null}
  </Box>
  <Box alignItems="center" display="flex" ml={1}>
    {actionsBar}
    {showColumnsButton ? (
      <Box ml={1}>
        <GridToolbarColumnsButton />
      </Box>
    ) : null}
    {showFiltersButton ? (
      <Box ml={1}>
        <GridToolbarFilterButton />
      </Box>
    ) : null}
    {showDensitySelector ? (
      <Box ml={1}>
        <GridToolbarDensitySelector />
      </Box>
    ) : null}
    {exportCsv ? (
      <Box ml={1}>
        <GridToolbarExport csvOptions={{ fileName: exportedTitle || title || document.title }} />
      </Box>
    ) : null}
  </Box>
</Box>
```
The toolbar component needs props that are not known at compile time so it will have to re-render. is there a better pattern for this

**Comment by oliviertassinari** [comment]
You can use the `componentsProps` to provide these props to the component.

**Comment by jakeleventhal** [comment]
Got it. Is `components` a deprecated prop? should slots be used instead?

**Comment by oliviertassinari** [comment]
@jakeleventhal Correct
