### ISSUE TITLE
Changing the sort order on a DataGrid programmatically

### ISSUE THREAD

**Issue by eide-1** [mui/mui-x#9048]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Add a DataGrid on a page
2. Use `apiRef.current.setSortModel([
        {
            field: 'processed.datetime',
            sort: sortOrder
        }
    ])` to set the sort model
3. The sort order is not changed

### Current behavior 😯

I have a page with a toggle that switches between a "Cards" view and a "Grid" view of items. There is a sort button on the cards view and I am trying to sync up the sort state between the two views. When the user clicks the sort button on the cards view, I used  `apiRef.current.setSortModel()` to update the sort order on the grid, but it does not seem to work.

### Expected behavior 🤔

setSortModel() should update the sort order of the DataGrid.

### Context 🔦

It would great if there was a way to programmatically control the state of the DataGrid including the sort order

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
</details>

**Comment by yaredtsy** [comment]
hey @eide-1

The documentation includes a topic on controlling sort mode from the code, which you can check out [here](https://mui.com/x/react-data-grid/sorting/#controlled-sort-model).

If you're providing a field that exists in the Datagrid, apiRef.current.setSortModel([{ field: 'processed.datetime', sort: sortOrder }]) should work as well.

Demo:https://codesandbox.io/s/hungry-microservice-n2yzor?file=/demo.tsx:637-801.
