### ISSUE TITLE
[DataGridPro] Filtering on Header — improve icons

### ISSUE THREAD

**Issue by gerdadesign** [mui/mui-x#9049]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Following up on #7760. 
---
- Most people don't understand math symbols beyond introductory arithmetic. There aren't great default icon options provided by [Material Icons or Symbols](https://fonts.google.com/icons?icon.set=Material+Symbols). 
- I've created some custom icons to try to show these operations in a more understandable way. Some of the math symbols have also been converted from a font to a icon following more of the Material guidelines for size. 

- Here is a proposed option for the text menu + numbers menu: 
<img width="785" alt="Text" src="https://github.com/mui/mui-x/assets/106991024/51de9317-ea74-4d61-a18e-6d006c809f07">
<img width="785" alt="Numbers" src="https://github.com/mui/mui-x/assets/106991024/3228cb92-9325-4508-8117-19b114da1cf5">

I'm not 100% sure about some of these (empty, not empty, any of) and would love some feedback about what symbols more clearly communicate the operations! 
I also increased the size of the symbol inside the icon container, but this is flexible. 

### Examples 🌈

Fuller exploration in [Figma](https://www.figma.com/file/W6TItYkiGJZjL5zLnfeSjy/Data-grid?type=design&node-id=2065%3A67977&t=mnjviadVLqyPpieO-1).

**Comment by oliviertassinari** [comment]
I feel that the "Design" version is the best all the 3 options listed.

**Comment by gerdadesign** [comment]
The icons are there since they are shown as a button to change to operator. 

The "Design" version is what was created in Figma, but there was a change in what was implemented. 

In the "Design" version of the Text menu, I still feel like `Contains`, and `Is any of` are not very clear. Out of curiosity, are you familiar with what they mean (prior to working with a data grid)?

**Comment by oliviertassinari** [comment]
What I like the most about the "Design" version is the font size, these icons are smaller, hence get less in my way, as my go to is to read the label

> Out of curiosity, are you familiar with what they mean (prior to working with a data grid)?

From Math classes, we would write this one https://en.wikipedia.org/wiki/Universal_quantification all the time post high-school. But I don't think that most people will understand them, another argument to not have any 😁

**Comment by MBilalShafi** [comment]
Thanks for the exploration and proposal. 

> I feel that it's mostly distracting

I also tend more toward the smaller (less distracting) icons. As for showing them or not, I think showing them makes the UI a little bit more intuitive and related to the icons on the button in the Header filter cell. 🤷‍♂️ 

> The "Design" version is what was created in Figma, but there was a change in what was implemented.

You are right, I tried to use those which were available in unicode, and the funny thing is, these were suggested by copilot and they kinda made sense to me so I kept using them. 😄 

@gerdadesign Should we explore a bit more on **Contains** or **Is any of** or do you think the Design variant makes sense to be replaced with the current one? We can possibly see what the community has to say about the currently released icons.

**Comment by gerdadesign** [comment]
Thanks for the inputs! @joserodolfofreitas and I initially discussed having an icon vs not and ultimately went with one due to the need for a button and to easily read things like < > ≥ ≤. However, the other symbols (based on [set notation](https://en.wikipedia.org/wiki/Set_(mathematics))) aren't easily understood (and I'm not sure they are actually accurate in our current implementation, so we may want to increase priority so that we're not putting out wrong info). 

There's a couple immediately apparent options: 

1. change the icons to something custom that make more sense for these operations (I've decreased the sizes). Still would like something different for "Any of" and "Empty" / "Not Empty". 
• This solution would likely require a custom icon for each new operator.  
• We do gain some immediate legibility & scannability 
<img width="240" alt="Words" src="https://github.com/mui/mui-x/assets/106991024/91d58d06-5579-42b0-9add-c6ca5dec85cb">
<img width="240" alt="Numbers" src="https://github.com/mui/mui-x/assets/106991024/4840502e-d5fd-45e8-8276-c5a34a1e06c2">


2. Make the icon generic & keep the button functionality, but move it outside of the field value. This also helps align the text for legibility. It would be more scalable with different operators and languages since it relies on text. For this exploration, I used a dropdown icon to help indicate there are options:
<img width="240" alt="Generic" src="https://github.com/mui/mui-x/assets/106991024/2372f689-b4a9-48f5-b066-d528528a5e43">

This is also related to the discussions around the syncing + clear icons. 
- the clear icon should match the clear icon in the filter panel (X instead of X inside a circle)
- in order to keep things tidy and less confusing, we could show the syncing icon within the field only when actively syncing (as it currently is) 
- and we can move “Clear” from being persistent in the field into the menu 

Compare showing the persistent "Clear" option… 
<img width="1245" alt="ShowClear" src="https://github.com/mui/mui-x/assets/106991024/0e10ac3a-e9a1-4964-b6a5-3dd17cd68e59">
…with moving it into the operator menu.
<img width="1246" alt="HideClear" src="https://github.com/mui/mui-x/assets/106991024/8f3d5e3b-99c5-42c5-9da1-9f2de1a09fb3">

(Happy to split this second part into a new issue if that's better).

**Comment by oliviertassinari** [comment]
> 2. Make the icon generic & keep the button functionality, but move it outside of the field value. This also helps align the text for legibility. 

This one makes a lot more sense to me. I love how it solves:

1. Relative noise when I'm trying to pick a menu item

<img width="184" alt="Screenshot 2023-05-31 at 16 32 21" src="https://github.com/mui/mui-x/assets/3165635/2d6dfdc4-3481-491e-a70c-dae92b452f8b">

2. Clearer affordance, between these two, which one is clearer on the next action to take to customize the filter?

<img width="189" alt="Screenshot 2023-05-31 at 16 33 41" src="https://github.com/mui/mui-x/assets/3165635/a4c23efc-d282-41bc-ba51-696a6b03aa86">

vs. 

<img width="190" alt="Screenshot 2023-05-31 at 16 34 14" src="https://github.com/mui/mui-x/assets/3165635/52517a17-b163-4546-882a-2b30dc18f747">

3. How the input is simpler, playing better with developers using their custom design system.

4. How we can now use the normal text field label shrink animation, as well as only trigger it on input focus. We couldn't before because of point 2 https://github.com/mui/mui-x/pull/7760#issuecomment-1546931388 
 
5. How it simplify the custom filter creation process for developers, no need to come up with an icon.

**Comment by MBilalShafi** [comment]
Thanks @gerdadesign and @oliviertassinari for the proposal and feedback, I tried to [visualize](https://deploy-preview-9181--material-ui-x.netlify.app/x/react-data-grid/filtering/#header-filters) the idea, let me know how you feel about it, we might have to change the icon we use as the icon collides with the one on singleSelect or boolean type columns.
![image](https://github.com/mui/mui-x/assets/12609561/15ed69f0-73c5-4fdc-a744-a15164bedbea)

**Comment by gerdadesign** [comment]
Good point @MBilalShafi! What about the [FilterList](https://fonts.google.com/icons?selected=Material%20Icons%3Afilter_list%3A) icon? 

Also, I'm noticing that if you write in a value, and then switch to a boolean filter, it keeps the value visible, even though it's not being used. To reduce confusion, should we just have one way of showing these types of filters (without showing the previous value)? Is it possible to still store the value if people switch back, but don't show it when it's not relevant? 
![Screen Shot 2023-06-01 at 12 45 43 AM](https://github.com/mui/mui-x/assets/106991024/16ff5241-8d72-4f6d-9d17-6a99a5b3ff30)

**Comment by MBilalShafi** [comment]
Yeah, FilterList definitely [looks](https://deploy-preview-9181--material-ui-x.netlify.app/x/react-data-grid/filtering/#header-filters) better, a little heavier than dropdown icon though.
![image](https://github.com/mui/mui-x/assets/12609561/0a2c901b-e4df-492c-8a48-29f0b82f6391)

> Is it possible to still store the value if people switch back, but don't show it when it's not relevant?

Totally, thanks for pointing it out. Updated the behavior. 👍

**Comment by oliviertassinari** [comment]
I think to consider if the icon should be on the left side or right side.  

Left side pros:

- More logical filtering order, first type, second value.

Right side pros:

- Closer to the UX end-users learned from Excel.
- Considering it's common to see data grids with a column filter without the choice of filtering, this resonates with the idea that the ability to select a different filter type is secondary.

--- 

Benchmarks

Excel macOS

<img width="428" alt="Screenshot 2023-06-01 at 10 03 23" src="https://github.com/mui/mui-x/assets/3165635/8641d91d-91e7-4dbd-8abe-0fddc9e5d8af">

Google Sheet

<img width="322" alt="Screenshot 2023-06-01 at 10 07 34" src="https://github.com/mui/mui-x/assets/3165635/d6b13ef0-a9f0-43d1-8fe1-e3a2d66e9be4">

**Comment by MBilalShafi** [comment]
Here's a comparison:
Menu icon on left side: https://codesandbox.io/s/u2jyfg?file=/demo.tsx
Menu icon on right side: https://deploy-preview-9181--material-ui-x.netlify.app/x/react-data-grid/filtering/#header-filters

My personal favorite is the right-side one, as mostly I've seen (in material design too and generally too) main content on the left and action button that opens a floating menu on the rightmost (comparatively, a drawer is mostly coming from the left side). So most users might be wired to this convention. [Examples: [1](https://m3.material.io/components/cards/overview), [2 (kebab icon)](https://m3.material.io/components/top-app-bar/overview), 3: column menu in grid header cell]

What do you think?

CC @gerdadesign

**Comment by gerdadesign** [comment]
👍 Agreed on moving the icon to the right — feels more natural in this new iteration.  

Now that it's sitting next to the clear button, I'm noticing a couple things: 
1. Can we move it down so that it aligns with the Value field? 
![Screen Shot 2023-06-01 at 10 23 41 AM](https://github.com/mui/mui-x/assets/106991024/e1d2e1fa-059e-4b9d-9a14-89d99cf77576)
2. What do you all think about the [clear option being visible the whole time in the header vs the option to place Clear into the menu](https://github.com/mui/mui-x/issues/9049#issuecomment-1558522644)? It's more clicks, but cleaner and less confusing. 


![persistent](https://github.com/mui/mui-x/assets/106991024/329aa4fd-a67b-4f43-89f7-87299b9c6640)
![hidden](https://github.com/mui/mui-x/assets/106991024/85bc76a9-c40b-4856-ae38-fe3e2e6a3d16)

**Comment by MBilalShafi** [comment]
> Can we move it down so that it aligns with the Value field?

Sure 👍 

> the option to place Clear into the menu

That's a good question. I'm not sure how others feel about it but I personally prefer the inline (current) variant of the clear icon, mainly because:
1. The one on the menu is not easily discoverable, as I have to open menu to access it.
2. If I am not mistaken, the user that @joserodolfofreitas interviewed also specifically asked for the clear button in the header, so more users prefer easily accessible action buttons.
