### ISSUE TITLE
[Data Grid] Data tree - How do I make parent rows editable

### ISSUE THREAD

**Issue by matrixersp** [mui/mui-x#9050]
### Order ID or Support key 💳 (optional)

0

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is it possible to make parent rows editable?

Can I use the id instead of name, and display the name in the group column instead? So that names can be duplicated
 ```js
const rows = [{
  path: [1],
  name: "Thomas",
  id: 1
},
{
  path: [1, 2],
  name: "Robert",
  id: 2
}];
  ```

### Your environment 🌎

 System:
    OS: Linux 6.2 Fedora Linux 38 (Workstation Edition)
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
  npmPackages:
    @emotion/react: ^11.10.5 => 11.11.0 
    @emotion/styled: ^11.10.5 => 11.11.0 
    @mui/base:  5.0.0-beta.1 
    @mui/core-downloads-tracker:  5.13.1 
    @mui/icons-material: ^5.11.0 => 5.11.16 
    @mui/material: ^5.11.2 => 5.13.1 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.12.3 
    @mui/system:  5.13.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-data-grid:  5.17.26 
    @mui/x-data-grid-pro: ^5.17.17 => 5.17.26 
    @mui/x-date-pickers: ^5.0.12 => 5.0.20 
    @mui/x-license-pro:  5.17.12 
    @types/react:  18.2.6 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0

**Comment by romgrk** [comment]
> Can I use the id instead of name

What for?

Could you also show me a live example of what you're trying to do? You can fork any example from [the docs](https://mui.com/x/react-data-grid/editing/) into a codesandbox live example.

**Comment by matrixersp** [comment]
@romgrk Here's the codesandbox https://codesandbox.io/s/headless-brook-11i51y?file=/demo.tsx

The following image could help you understand what I exactly want to achieve
![Screenshot from 2023-05-24 16-21-30](https://github.com/mui/mui-x/assets/19875946/4fef3950-c410-4e16-b60b-92238284a163)

**Comment by romgrk** [comment]
We don't have an option for that, but I think it would be possible to achieve with a custom cell renderer. Have you looked at the [custom grouping column](https://mui.com/x/react-data-grid/tree-data/#custom-grouping-column) example in our docs? It shows how to replace the grouping cell with a custom component, you could use it as a base and use an input component instead of a button. You'd need to implement the editing logic by yourself though.
