### ISSUE TITLE
[data-grid] Changing the popper position for GridColumnsPanel

### ISSUE THREAD

**Issue by mikolajbogusz-they** [mui/mui-x#9066]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently, the Popper for GridColumnsPanel is displayed in the upper left corner of DataGrid. However, in my custom GridToolbar, the button for columns panel is on the right side. Therefore, I am trying to find the possibility of moving the Popper also to the right corner of data grid. Is there a solution for this or is it planned?
![image](https://github.com/mui/mui-x/assets/88504484/cd2a4fc8-91e4-44b9-aff9-f3e1754ffade)

**Comment by MBilalShafi** [comment]
You might want to use the `anchorEl` prop of `basePopper` slot.

Something like this: https://codesandbox.io/s/determined-spence-nfjp2k?file=/demo.tsx:634-928

Is that what you are looking for?

**Comment by mikolajbogusz-they** [comment]
I understand, that was the intention. Thanks a lot!

**Comment by mikolajbogusz-they** [comment]
I understand, that was the intention. Thanks a lot!

**Comment by mikolajbogusz-they** [comment]
Hello @MBilalShafi 
thanks for your help. However, the problem with this solution is that all poppers will now be under this button and this is what we are trying to avoid (e.g. column filters poppers). Targeting only GridColumnsPanel

**Comment by yaredtsy** [comment]
There is also another, simpler way by creating a CustomFilter and wrapping it in a GridPanel. This allows it to be anchored anywhere.

```jsx

const CustomeFilter = (props) => {
  return (
    <GridPanel
      open={true}
      anchorEl={props.anchorEl.current}
      placement="bottom-end"
    >
      <GridFilterPanel />
    </GridPanel>
  );
};
```
Demo: https://codesandbox.io/s/distracted-sun-n6hr4z?file=/demo.tsx

**Comment by aress31** [comment]
@yaredtsy everything that adds additional boilerplate code or require creating new custom component is not in my book the best dx. Using the slots we should be able to pass the anchor for individual components that would be the best native approach.

**Comment by MBilalShafi** [comment]
@mikolajbogusz-they Does the alternative mentioned in https://github.com/mui/mui-x/issues/9066#issuecomment-1557936282 work for you?

**Comment by webeli** [comment]
> There is also another, simpler way by creating a CustomFilter and wrapping it in a GridPanel. This allows it to be anchored anywhere.
> 
> ```js
> const CustomeFilter = (props) => {
>   return (
>     <GridPanel
>       open={true}
>       anchorEl={props.anchorEl.current}
>       placement="bottom-end"
>     >
>       <GridFilterPanel />
>     </GridPanel>
>   );
> };
> ```
> 
> Demo: https://codesandbox.io/s/distracted-sun-n6hr4z?file=/demo.tsx

This was the best solution i found, works great! <3

**Comment by Rabeet-5** [comment]
Was stuck in this issue for couple of hours , finally i was able to change the position of the popper.

 
![image](https://github.com/mui/mui-x/assets/133810435/9b95dc4b-f683-4c66-9b3e-955b3b00cb14)

here is the code snippet .

![image](https://github.com/mui/mui-x/assets/133810435/1d6e70d2-f3b5-49a0-b8ba-51873260527b)
