### ISSUE TITLE
[DataGrid] Column ordering is not applying while restore state

### ISSUE THREAD

**Issue by Laxman2015** [mui/mui-x#9070]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.Reorder the column
2.getting the current state and store somewhere in app state(oldState)// Getting correct value
  `  const newViewData = apiRef?.current?.exportState();`
3.Again re-applying/restore the same state, All state is applied except column reorder.
apiRef?.current?.restoreState(oldState);

### Current behavior 😯

Again re-applying/restore the same state, All state is applied except column reorder.

### Expected behavior 🤔

after re-applying/restore the same state,  column reorder also should be applied

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
apiRef?.current?.restoreState(oldState);
```
</details>

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by rosasynstylae** [comment]
Any update here? I'm running into the same issue
