### ISSUE TITLE
'Select all' checkbox in DataGrid header ignores the first tap in iOS Safari.

### ISSUE THREAD

**Issue by studnik18** [mui/mui-x#9073]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/9pslke?file=demo.tsx

It's reproducible in the official mui documentation sandbox related to checkbox selection feature for DataGrid.

Steps:
1. Use iPad or open xcode iPad emulator.
2. Open the sandbox in Safari browser
3. Let the DataGrid component mount.
4. Tap the  'select all' checkbox in the grid header.

### Current behavior 😯

The 'select all' checkbox doesn't work on first tap. From the second tap on, it works as expected, selecting and deselecting all rows.

### Expected behavior 🤔

It works as expected even on first tap.

### Context 🔦

It may be misleading for user if he/she tries to select all rows to no avail at the first try.

### Your environment 🌎

Please note, that the output of the envinfo command comes from the machine used for development, where only the npmPackages versions have diagnostic value.

The testing device is:
- iPad 10th Gen
- iPadOS / Safari: 16.3.1
- GC: 110.0.5481.114

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1

  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm

  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.4

npmPackages:
    @emotion/react: 11.10.6 => 11.10.6 
    @emotion/styled: 11.10.6 => 11.10.6 
    @mui/base:  5.0.0-beta.1 
    @mui/core-downloads-tracker:  5.13.1 
    @mui/icons-material: 5.11.16 => 5.11.16 
    @mui/material: 5.13.1 => 5.13.1 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.12.3 
    @mui/system: 5.13.1 => 5.13.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-data-grid: 6.5.0 => 6.5.0 
    @mui/x-date-pickers: 6.5.0 => 6.5.0 
    @types/react: 18.0.21 => 18.0.21 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 4.8.4 => 4.8.4 

```
</details>

**Comment by cherniavskii** [comment]
Looks similar to https://github.com/mui/mui-x/issues/8762
