### ISSUE TITLE
[question] AdapterDateFns and AdapterDayjs appear to have slightly different validation behaviour

### ISSUE THREAD

**Issue by robashcroft-rac** [mui/mui-x#9077]
### Order ID or Support key 💳 (optional)

66287

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm noticing that when I enter a date into a MUI DateField (version 6.4.0 of @mui/x-date-pickers), the validation logic kicks in at a different point depending on the date adapter I'm using (AdapterDateFns vs AdapterDayjs). It's an edge case, but the issue is that the 29th Feb is reverted to 28th before a full year (potentially a valid leap year) is entered (with AdapterDateFns). Some users may not see this date change, and submit an incorrect date.

When populating the DateField with 29th February on a valid leap year, the DateField reverts the day to the 28th after entering the first character of the year e.g. ('1' of 1988) when using AdapterDateFns so it appears to be attempting to validate the date as '29/02/0001' (with 0001 not being a leap year).

The behaviour with AdapterDayjs is different, and retains the date (29th) until a four-digit year has been entered.

Is there a way I can configure AdapterDateDns to behave in the same way as AdapterDayjs, or is this a bug?  

Sandbox with box examples here:  https://codesandbox.io/s/mui-datefield-leap-year-issue-6hj5ys?file=/demo.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.126 
    @mui/core-downloads-tracker:  5.12.1 
    @mui/icons-material: ^5.11.11 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.124 => 5.0.0-alpha.127 
    @mui/material: ^5.11.14 => 5.12.1 
    @mui/private-theming:  5.12.0 
    @mui/styled-engine:  5.12.0 
    @mui/system:  5.12.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-date-pickers: ^6.0.3 => 6.4.0 
    @types/react: ^17.0.42 => 17.0.58 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.6.2 => 4.9.5 

```
</details>

**Comment by flaviendelangle** [comment]
Hi,

We are discussing this behavior in #8221

I'm closing that one as duplicate :+1:
