### ISSUE TITLE
[pickers] The popper direction changes when customize the textField

### ISSUE THREAD

**Issue by mf0548414295** [mui/mui-x#9078]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1  I customize the textField :    slots={{textField:(props)=><TextField {...props}/>}}
2.  click on the icon of open picker
3. datepicker is opening on top left corner of page

![צילום מסך 2023-05-23 073115](https://github.com/mui/mui-x/assets/111738676/cc9b1def-8d30-4daa-a2c6-60f2f1881d8e)

### Current behavior 😯

datepicker is opening on top left corner of page

### Expected behavior 🤔

datepicker should open below the texrfield

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

google chrome
  
   System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.16.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - C:\Program Files (x86)\nodejs\npm.CMD 
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.125
    @mui/core-downloads-tracker:  5.12.0
    @mui/icons-material:  5.11.16
    @mui/material: ^5.11.9 => 5.12.0
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system:  5.12.0
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-date-pickers: ^6.0.1 => 6.3.1
    @types/react: ^18.0.25 => 18.0.35
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.3 => 4.9.5
```
</details>


### Order ID or Support key 💳 (optional)

0548414295

**Comment by mf0548414295** [comment]
I changed it to component and still datepicker is opening on top left corner of page...

**Comment by flaviendelangle** [comment]
OK, can you give me a reproduction case ?
[This template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) should be a good start

**Comment by flaviendelangle** [comment]
You are still using the render prop pattern

```tsx
          slots={{
            textField: ({ InputProps, onKeyDown, ...props }) => (
              <DatePickerTextField
                props={props}
                hoveredDatePicker={hoveredDatePicker}
                InputProps={InputProps}
                setFocused={setFocused}
                setHoveredDatePicker={setHoveredDatePicker}
              />
            )
          }}
```

Your slots should always look like;

```tsx
slots={{ textField: MyTextField }}
```

Not

```tsx
slots={{ textField: (props) => <MyTextfField {...props} />}}
```

Internally, we do `const TextField = props.slots.textFIeld`
So if you have a render function, the component will change it's reference on every render and React will remount it.

**Comment by mf0548414295** [comment]
how do i define the MyTextField and send it parameters?

**Comment by flaviendelangle** [comment]
[Here is a working example](https://codesandbox.io/s/determined-leaf-v8ptu4?file=/src/CustomDatePicker/CustomDatePicker.tsx)

Not sure what you are trying to achieve, but your component now receives your props through `slotProps` and the `other` contains everything the pickers are passing him.

**Comment by mf0548414295** [comment]
Thank you very much!!! it solved my problem
how can i open another bag?

**Comment by flaviendelangle** [comment]
Another bag ?

**Comment by mf0548414295** [comment]
no,I don`t have another bag,but I want that I will have option to open another bug in mui, if I have it

**Comment by flaviendelangle** [comment]
If you have another topic at some point, you can create a new issue :+1:

**Comment by LukasTy** [comment]
Closing the issue as there does not seem to be any more open questions left to answer.
