### ISSUE TITLE
[data grid] https://mui.com/x/ UX regression

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#9083]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Compare how it was better before vs. after:

Before: https://deploy-preview-36000--material-ui.netlify.app/x/
After: https://deploy-preview-37001--material-ui.netlify.app/x/

https://github.com/mui/material-ui/pull/37001#issuecomment-1546767710 covers in more depth what's are the issue, the quick version:

1. **performance**. The time to load the page, and to respond to interactions on the grid. Also, the JavaScript thread seems to freeze on mobile.
2. **viewport**. The viewport is smaller, and the rows are bigger, we used to be able to see 7 rows, but we are down to 3.5. It feels hard to use, I'm afraid it won't leaving a great first impression to new visitors on the page.

**Comment by cherniavskii** [comment]
I believe the performance issue was addressed by @MBilalShafi in the latest data grid release (see https://github.com/mui/mui-x/pull/8990) and it's much better now:
https://master--material-ui.netlify.app/x/

**Comment by cherniavskii** [comment]
Addressed in https://github.com/mui/material-ui/pull/37387

**Comment by cherniavskii** [comment]
I think we can close it now since performance and UX issues have been addressed - see https://mui.com/x/

**Comment by oliviertassinari** [comment]
All fixed 👌
