### ISSUE TITLE
[DataGrid] Edit all row at once

### ISSUE THREAD

**Issue by Miri121** [mui/mui-x#9089]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

I use rowModelType='serverSide' and I want to move all the rows in the table to editing mode with the click of a button, how do I do that?

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by Miri121** [comment]
I use more or less the language examples:

https://www.ag-grid.com/react-data-grid/server-side-model-tree-data/

 I want that when I click the update button (which I created) all the cells that allow editing in the table will go into editing mode and I will be able to edit them...

**Comment by Miri121** [comment]
I check tomorrow and We will update you thank you!!!

**Comment by romgrk** [comment]
You've sent a link to AG Grid docs but this is the MUI X repo. Are you sure you're using the MUI X DataGrid?

**Comment by Miri121** [comment]
I use the link I sent you in this example "Selection with tree data".
I want that when I click the update button (which I created) all the cells that allow editing in the table will go into editing mode and I will be able to edit them... how I did it please!

**Comment by romgrk** [comment]
You haven't provided an example yet. Could you provide a minimal example? [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) is a good starting point.

**Comment by Miri121** [comment]
You can use the link I sent you... this is an example of the table I have, I just changed the data, you can copy code to codesandbox and add code of
example:
  how to add a button and when I click on it all the cells of the table go into edit mode... so that I can edit all the cells of the table together! ?
