### ISSUE TITLE
[pickers] Import custom holiday for date picker

### ISSUE THREAD

**Issue by fakhamatia** [mui/mui-x#9091]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want import Jalali holidays to date picker and mark them red in view. It is possible ?

Source: [Persian Calendar](https://github.com/persian-calendar/persian-calendar/blob/main/PersianCalendar/data/events.json)

**Comment by alexfauquette** [comment]
Yes you can. With `slotPorps` you can override day props.

https://codesandbox.io/s/angry-ully-sw8goj?file=/demo.tsx

This king of behavior could be interesting gin the docs

**Comment by alexfauquette** [comment]
I took the calendar for simplicity, but you should have access to the same `slotProps` in other components

For more advanced customization, you have https://mui.com/x/react-date-pickers/custom-layout/ and https://mui.com/x/react-date-pickers/custom-components/ docs pages

**Comment by isrezaei** [comment]
Hey, I am using the AdapterDateFnsJalali in LocalizationProvider, but when I use this , I get a full date like this , why ?


AdapterDateFnsJalali : 
day: Tue Jun 20 2023 00:00:00 GMT+0330 (Iran Standard Time) {}

AdapterDayjs : 
day: M2
$D: 1
$H: 0
$L: "en"
$M: 5
$W: 4
$d: Thu Jun 01 2023 00:00:00 GMT+0330 (Iran Standard Time) {}
$m: 0
$ms: 0
$s: 0
$u: undefined
$x: {}
$y: 2023


 <DatePicker
                    label="date"
                    clearable
                    slotProps={{
                        day: (ownerState) => {

                            console.log(ownerState)

                            const DATES = {
                                month : ownerState.day['$M'],
                                day : ownerState.day['$D'],
                            }
                            console.log(DATES) // in AdapterDateFnsJalali  i got undefined becuse i got a full date not month  and  day data
                        
                    }}
                />
            </DemoContainer>

**Comment by isrezaei** [comment]
Hi , i got a issue ! 
why when i use   dateAdapter={AdapterDateFnsJalali} in LocalizationProvider , in <DatePicker/> slotProps={{day : (ownerState)}}, 
data of ownerState , part day object , i got a full data time string ! 
but when i use AdapterDayjs in dateAdapter , in <DatePicker/> slotProps={{day : (ownerState)}} part of day , i got information about every day month and years ! why ?

in this case i got full string time stamp :
        <LocalizationProvider
            dateAdapter={AdapterDateFnsJalali} // i use AdapterDateFnsJalali
            adapterLocale={faJalali}
            localeText={faIR.components.MuiLocalizationProvider.defaultProps.localeText}
        >
            <DemoContainer components={['DatePicker']}>
                <DatePicker
                    label="date"
                    clearable
                    slotProps={{
                        day: (ownerState) => {

                            console.log(ownerState)

                            const DATES = {
                                month : ownerState.day['$M'], //i got string time stamp !!
                                day : ownerState.day['$D'], //i got string time stamp !!
                            }
                        }
                    }}
                />
            </DemoContainer>
        </LocalizationProvider>

but in this case i got full info about date


        <LocalizationProvider
            dateAdapter={AdapterDayjs} //i use AdapterDayjs
        >
            <DemoContainer components={['DatePicker']}>
                <DatePicker
                    label="date"
                    clearable
                    slotProps={{
                        day: (ownerState) => {

                            console.log(ownerState)

                            const DATES = {
                                month : ownerState.day['$M'], courrect info
                                day : ownerState.day['$D'], courrect info
                            }
                        }
                    }}
                />
            </DemoContainer>
        </LocalizationProvider>

help me thanks !

**Comment by alexfauquette** [comment]
@isrezaei could you open a new issue, with a codesandbox containing the two example? 

This issue is dedicated to improving the documentation of day customization which is not related to your message
