### ISSUE TITLE
Expanded Capabilities of the Filter Function

### ISSUE THREAD

**Issue by yoangeltb** [mui/mui-x#9093]
### Order ID or Support key 💳 (optional)

53586

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Dear customer representative

We are currently undergoing a technical challenge while using Datagrid Premiun. We are trying to implement a filter that will be applied only on parent rows(see the attachment). 

 We are wondering if any of the following solutions are attainable:

A) To have access to modify the native filter function in Datagrid Primium.

B) To be able to control the rows that are passed to the filter function and receive a Call-back with the filtered results of such function.

Sincerely,
![MicrosoftTeams-image (5)](https://github.com/mui/mui-x/assets/134401181/9a6d7abe-708a-44d3-8cef-829184e56c3b)

Yoangel Torres

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
Could you provide a minimal example? This would help a lot 👷. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) is a good starting point, I'm not sure I understand your use case precisely.

Note that it would be possible to do filtering outside the grid, and pass the filtered results to the grid.

**Comment by yoangeltb** [comment]
Hello Rom or MUI representative

We have gone ahead and built a minimal example as per your request. Below see the link to the minimal example on codesandbox.io

https://codesandbox.io/s/data-grid-community-forked-3fkt8l?file=/src/App.tsx

What we are attempting to do:

On an expandable style of table, where parent rows contain children rows, we are attempting to apply a filter function only to the parent rows but preserving its children in the end.


  *   On the given example please proceed to set “Column 2” filter to “contains” value of “Row 5”, this will yield “Row 3” as the filtered results because it has “Row 5” as a “child”. We envision for this filtering use case to return nothing due to the fact that “Row 5” is not a “Parent”.


  *   Alternatively, if you were to set “Column 2” filter to “contains” value of “Row 3” , this will now yield “Row 3” by itself. We intend to have “Row 3” returned along with its original children.

Please advise on our quest for such functionality.


Best Regards,

Yoangel Torres, CTO
BOMNIN AUTOMOTIVE
Dadeland * West Kendall * Homestead * Manassas
11701 SW 152 St Miami Fl 33177
Mobile: 305.803.3201 ***@***.******@***.***>
This message and any attachments are intended only for the use of the addressee and may contain information that is privileged and confidential. If the reader of the message is not the intended recipient or an authorized representative of the intended recipient, you are hereby notified that any dissemination of this communication is strictly prohibited. If you have received this communication in error, notify the sender immediately by return email and delete the message and any attachments from your system.

**Comment by yaredtsy** [comment]
i  believe that this can be achieved by setting the `disableChildrenFiltering` props to true. there is a section about it at [Doc](https://mui.com/x/react-data-grid/tree-data/#filtering).

Demo: https://codesandbox.io/s/data-grid-community-forked-p2vej8?file=/src/App.tsx
