### ISSUE TITLE
[pickers] Reset the field internal state

### ISSUE THREAD

**Issue by kawazoe** [mui/mui-x#9098]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/hardcore-smoke-5lu8xx

Steps:
1. Notice how the component initially displays a date at 4:00 PM.
2. Click on the minutes section, and type 1.
3. Notice how the time is now 04:01 PM.
4. Click on the CHANGE button, which will set the time to 4:44 PM
5. Click on the minutes section, and type 1.

### Current behavior 😯

The time is set to 04:11 PM.

### Expected behavior 🤔

The time should be set to 04:01 PM again.

In other words, the picker holds an internal state of what has been typed for each section. It should reset this state when the value is changed externally, as the old state doesn't necessarily makes sense with the new value.

### Context 🔦

I noticed this issue when trying to augment a DateTimePicker so that it automatically rounded its value according to the minuteStep property when blurred. My solution was to monitor the onChange event, and use it to store the last value of the component, then when textField is blurred, attempt to round it, and update the value if necessary. I was testing with a 30 minutes interval, so entering 5 rounded down the first time, as expected, but up the second time, as the value was now 55 instead.

### Your environment 🌎

The sandbox is a fork of the "Basic usage" demo on the site for v6.5.0.

**Comment by alexfauquette** [comment]
Thanks for reporting this interesting issue. Mayb einsted of when value is modified (which means all the time with a controlled filed) it could be more interesting to do this reset when the section loose selection.

For example, if I press <kbd>1</kbd> for days, switch to month, and go back to days. When pressing <kbd>2</kbd> it should display `02` and not `12`

**Comment by alexfauquette** [comment]
In the native date input, the moving to another section even if you d not modify it reset the editing internal state.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

press <kbd>1</kbd>, <kbd>arrow right</kbd>, <kbd>arrow left</kbd>, <kbd>1</kbd> and the digit will still be `01`, not `11`

**Comment by kawazoe** [comment]
Interesting. Then this is also a difference in behaviour with MUI's DateTimePicker. I don't know how much you try to mimic the native picker, but personally, I think your current behaviour is more intuitive. It would be a shame to change it just to match the native bahaviour, if it isn't a requirement.

**Comment by flaviendelangle** [comment]
This has been fixed, you can check the demo linked in the 1st message,, we end up with `04:01` as expected.

I'm closing :+1:
