### ISSUE TITLE
[data grid] Clipboard paste adds an empty cell

### ISSUE THREAD

**Issue by simonesanna1983** [mui/mui-x#9103]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Copy from MS Excel a column with 3 values 
2. Paste into the datagrid in a random position
3. We have our 3 values copied successfully, but we have another blank cell (it happens with a rectangle selection as well)

attached a gif.

![IssueDataGridMUI](https://github.com/mui/mui-x/assets/35135396/756ba96c-afbf-43bc-b5e5-4b44e64e5d7c)

### Current behavior 😯

Another cell is added when the values are copied and pasted from MS Excel

### Expected behavior 🤔

The paste feature should only copy  the affected cell(s)

### Context 🔦

I would like to copy from MS Excel and paste into the data grid. In the Excel is a simple copy, there are not strange characters involed.

**Comment by MBilalShafi** [comment]
@simonesanna1983 It seems like the copied data includes a `\n` in the end.

For me though, it worked fine with Excel (web version)
![clipboard-paste](https://github.com/mui/mui-x/assets/12609561/d9aab5d8-08e4-46f8-89c9-b44c8d06e8e1)

Can you provide the data being copied when you hit Ctrl+C on Excel?

**Comment by simonesanna1983** [comment]
It's just a copy and paste, with MS Excel (office 365) desktop version.

Attached a gif.

![IssueDataGridMUIExample](https://github.com/mui/mui-x/assets/35135396/63521de0-9b27-43b9-b001-60e8c0a47847)

**Comment by simonesanna1983** [comment]
Hi @MBilalShafi, attached an example with a copy of an empty cell. 
As you can see in the datagrid, 2 rows has been pasted instead of 1, if the intention is to copy 1 cell, it will be "\n" and not "\n\n". At least the last \n should be removed. 
Alternatively a new parameter could be added to specify this behavior (I would say a boolean parameter). 

![IssueDataGridMUIExample2](https://github.com/mui/mui-x/assets/35135396/170d925d-0a84-4b3f-b167-1ac8dfd747c9)

**Comment by cherniavskii** [comment]
It seems like Excel on Windows intentionally adds a line break when copying: https://stackoverflow.com/questions/14695836/ms-excel-adds-line-break-when-copying-a-cell

@simonesanna1983 Can you try this demo? https://codesandbox.io/s/stupefied-sunset-ylghrg?file=/demo.tsx
It overrides the default function that is used to split the pasted string:
```ts
const splitClipboardPastedText = (pastedText: string) => {
  // remove the last empty line break
  const text = pastedText.replace(/\r?\n$/, "");
  return text.split(/\r\n|\n|\r/).map((row) => row.split("\t"));
};
```

**Comment by cherniavskii** [comment]
BTW, AG Grid has an option for this: https://ag-grid.com/javascript-data-grid/grid-options/#reference-clipboard-suppressLastEmptyLineOnPaste

**Comment by simonesanna1983** [comment]
Hi @cherniavskii,
yes I've tried and it seems to be working fine. Yes your solution looks good :)
With the possibility to customise the clipboard data should be fine helpful to prevent side effects.

Attached a gif.
![LooksGood](https://github.com/mui/mui-x/assets/35135396/e075d341-31e5-4585-967e-b447a1049293)

**Comment by cherniavskii** [comment]
@simonesanna1983 Thanks!
I think we should remove the last line break by default

**Comment by simonesanna1983** [comment]
Yes it is a good idea, otherwise a dedicated parameter in order to specify the behavior. But don't keep it without solution as it MS Excel is very famous and it might be a common operation.
