### ISSUE TITLE
[data grid] translate3d makes columns header lighter

### ISSUE THREAD

**Issue by claudioctonha** [mui/mui-x#9111]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Open chrome console
2. Find for MuiDataGrid-columnHeadersInner element in your datagrid
3. Disable transform: translate3d(0px, 0px, 0px) and enable again

### Current behavior 😯

translate3d is making the color lighter.

### Expected behavior 🤔

it could be used translate or translateX instead

### Context 🔦

I am not sure if it's possible to change it, but it's an issue since the component is not following the system theme.

**Comment by romgrk** [comment]
I can't reproduce the issue. Can you provide the details about your environment? Look at the new issue template, the instructions for what we need are there.

**Comment by claudioctonha** [comment]
Ignore that. Optical illusion. We are using another font-family, font-size, color, etc.
