### ISSUE TITLE
webpack failing with unstable_generateUtilityClasses is not a function

### ISSUE THREAD

**Issue by pedaars** [mui/mui-x#9115]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: 
I am unable to reproduce this outside of my company stack

Steps:

Using Chrome 113.0.5672.126

installed dataGrid from npm following the instructions here [https://mui.com/x/react-data-grid/getting-started/#installation]

copied the example given for dataGrid from the above link into my companies system

on running our app I get the following error 
![Screenshot 2023-05-24 at 15 39 18](https://github.com/mui/material-ui/assets/11647950/fadc0f67-e8be-4fb0-8d79-70fb176dbb5f)

I also tried adding the example into our storybook but also receive the above error

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 13.3
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: 113.0.1774.50
    Firefox: 113.0.2
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.2 
    @mui/core-downloads-tracker:  5.13.2 
    @mui/envinfo: ^2.0.8 => 2.0.8 
    @mui/icons-material:  5.11.16 
    @mui/material: ^5.13.2 => 5.13.2 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/styled-engine-sc: ^5.12.0 => 5.12.0 
    @mui/styles: ^5.13.2 => 5.13.2 
    @mui/system:  5.13.2 
    @mui/types:  7.2.4 
    @mui/utils: ^5.13.1 => 5.13.1 
    @mui/x-data-grid:  6.5.0 
    @mui/x-data-grid-generator: ^6.5.0 => 6.5.0 
    @mui/x-data-grid-premium:  6.5.0 
    @mui/x-data-grid-pro: ^6.5.0 => 6.5.0 
    @mui/x-license-pro:  6.0.4 
    @types/react:  17.0.37 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.10 => 5.3.10 
    typescript:  4.9.5
```
</details>

**Comment by cherniavskii** [comment]
Hi @pedaars 
What version of `@mui/material` and `@mui/system` you are using?

**Comment by pedaars** [comment]
Hello @cherniavskii we are using

@mui/material =  "version": "5.13.2",
@mui/system =  "version": "5.13.2",

**Comment by cherniavskii** [comment]
Thanks, I just noticed that you included your environment info 👍
I can see that the `@mui/utils` package (the one that exports `unstable_generateUtilityClasses`) is up to date:
```
@mui/utils: ^5.13.1 => 5.13.1 
```
And it definitely exports `unstable_generateUtilityClasses` - see https://unpkg.com/browse/@mui/utils@5.13.1/index.js

This is probably a bundling-related issue. We have seen this before in our demos in Codesandbox - https://github.com/mui/mui-x/issues/4924. But it wasn't reproducible outside of Codesandbox.

I cannot reproduce this issue locally with `react-scripts`.
Do you use `react-scripts` for bundling?

**Comment by pedaars** [comment]
we use an internal (company) configuration with webpack for bundling

**Comment by pedaars** [comment]
![Screenshot 2023-05-25 at 18 19 05](https://github.com/mui/mui-x/assets/11647950/603cb2c1-dd36-49cd-ac21-c7c6acae8101)

no extra node_modules

**Comment by arvindkannan** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Latest version
> * [x]  I have tested the latest version
> 
> ### Steps to reproduce 🕹
> Link to live example: I am unable to reproduce this outside of my company stack
> 
> Steps:
> 
> Using Chrome 113.0.5672.126
> 
> installed dataGrid from npm following the instructions here [https://mui.com/x/react-data-grid/getting-started/#installation]
> 
> copied the example given for dataGrid from the above link into my companies system
> 
> on running our app I get the following error ![Screenshot 2023-05-24 at 15 39 18](https://user-images.githubusercontent.com/11647950/240851613-fadc0f67-e8be-4fb0-8d79-70fb176dbb5f.png)
> 
> I also tried adding the example into our storybook but also receive the above error
> 
> ### Current behavior 😯
> _No response_
> 
> ### Expected behavior 🤔
> _No response_
> 
> ### Context 🔦
> _No response_
> 
> ### Your environment 🌎
> `npx @mui/envinfo`

I'm also getting similar error in latest version(6.5.0) of date-picker control as per MUI-X documentation. Working perfectly as expected in development(typescript) environment but the moment we will react.js and deploy the app crashes with below error message in console.

Not sure what's root cause of the issue but the moment I comment out the localization HOC and date picker the error vanishes in built version.



![image](https://github.com/mui/mui-x/assets/26468070/7b294ced-d71d-41d0-a72c-412f5b51ac06)

**Comment by cherniavskii** [comment]
@arvindkannan This is not related to this issue, unless you see `unstable_generateUtilityClasses is not a function` error.
Can you open a new issue with a reproduction example? Thanks!
