### ISSUE TITLE
[DataGrid] Using `mouseup` event for focus affects performance

### ISSUE THREAD

**Issue by romgrk** [mui/mui-x#9118]
After the change in #6489, the grid focus now happens on the `mouseup` event. Unfortunately, this means that react can't batch the updates that happen during the `click` event, so it needs to render twice whenever there is a focus change.

https://github.com/mui/mui-x/blob/463de84d54ff65d91a2f58585ecde7d2b7d77410/packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts#L440-L447

<img src="https://github.com/mui/mui-x/assets/1423607/ff040350-3601-41b9-8b77-2d5dbd4df2c2" width="500" />

We should revert that change and fix the demo issue otherwise.

**Comment by romgrk** [comment]
cc @cherniavskii

**Comment by cherniavskii** [comment]
@romgrk I don't think I understand the batching issue here.
I tried both `mouseup` and `click`, and the task takes roughly the same time in both cases:

**mouseup**
<img width="862" alt="mouseup" src="https://github.com/mui/mui-x/assets/13808724/39f6798c-70df-4078-bba9-1a6b5a5d9728">

**click**
<img width="909" alt="click" src="https://github.com/mui/mui-x/assets/13808724/0bd6dbc9-859d-48a4-8820-a4c6157bb5af">

Am I missing something?

**Comment by romgrk** [comment]
Closing, stale.
