### ISSUE TITLE
With x-data-grid-pro 6.5.0 how do you programmatically clear the rowSelectionModel?

### ISSUE THREAD

**Issue by jsimpson-www** [mui/mui-x#9130]
### Order ID or Support key 💳 (optional)

66874

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

In x-data-grid-pro 5.*.* I was able to clear the selectionModel with ... `setSelectionModel([])` for `selectionModel` 

With the advent of 6.5.0 the new function is `setRowSelectionModel([])` for `rowSelectionModel` does not clear `rowSelectionModel`

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.5 - ~\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
  npmPackages:
    @emotion/react: ^11.9.3 => 11.11.0
    @emotion/styled: ^11.9.3 => 11.11.0
    @mui/base:  5.0.0-alpha.128
    @mui/core-downloads-tracker:  5.12.3
    @mui/icons-material: ^5.8.4 => 5.11.16
    @mui/lab: ^5.0.0-alpha.104 => 5.0.0-alpha.129
    @mui/material: ^5.8.4 => 5.12.3
    @mui/private-theming:  5.12.3
    @mui/styled-engine:  5.12.3
    @mui/system: ^5.12.3 => 5.12.3
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-data-grid:  6.5.0
    @mui/x-data-grid-pro: ^6.5.0 => 6.5.0
    @mui/x-date-pickers:  6.5.0
    @mui/x-date-pickers-pro: ^6.5.0 => 6.5.0
    @mui/x-license-pro:  6.0.4
    @types/react:  18.2.6
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.9.5

Google Chrome
Chrome is up to date
Version 113.0.5672.127 (Official Build) (64-bit)

```
</details>

**Comment by jsimpson-www** [comment]
Hello, certainly!

Objective: toggle row selection with a single-click in any cell of a row. Click on Column 2 of row 1, World, the row selects and turns blue.  Click the same cell again, it unselects and the blue background is gone. This is perfect and meets the business requirement.

Pass: Example _working_ with v5.12.1, https://codesandbox.io/p/sandbox/sweet-julien-13094j

`import * as React from "react";
import { DataGridPro } from "@mui/x-data-grid-pro";

const rows = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "MUI X", col2: "is awesome" },
  { id: 3, col1: "Material UI", col2: "is amazing" },
  { id: 4, col1: "MUI", col2: "" },
  { id: 5, col1: "Joy UI", col2: "is awesome" },
  { id: 6, col1: "MUI Base", col2: "is amazing" },
];

const columns = [
  { field: "id" },
  { field: "col1", headerName: "Column 1", width: 150 },
  { field: "col2", headerName: "Column 2", width: 150 },
];

export default function App() {
  const [selectionModel, setSelectionModel] = React.useState([]);

  const handleRowClick = (params) => {
    if (selectionModel.length > 0 && params.id === selectionModel[0]) {
      setSelectionModel([]);
    }
  };

  return (
    <div style={{ height: 500, width: "100%" }}>
      <DataGridPro
        rows={rows}
        columns={columns}
        onRowClick={handleRowClick}
        onSelectionModelChange={setSelectionModel}
        selectionModel={selectionModel}
        disableMultipleRowSelection
      />
    </div>
  );
}
`

Fail: Example _not_ working in v6.5.0, https://codesandbox.io/p/sandbox/kind-tess-gdghzc

`import * as React from "react";
import { DataGridPro } from "@mui/x-data-grid-pro";

const rows = [
  { id: 1, col1: "Hello", col2: "World" },
  { id: 2, col1: "MUI X", col2: "is awesome" },
  { id: 3, col1: "Material UI", col2: "is amazing" },
  { id: 4, col1: "MUI", col2: "" },
  { id: 5, col1: "Joy UI", col2: "is awesome" },
  { id: 6, col1: "MUI Base", col2: "is amazing" },
];

const columns = [
  { field: "id" },
  { field: "col1", headerName: "Column 1", width: 150 },
  { field: "col2", headerName: "Column 2", width: 150 },
];

export default function App() {
  const [rowSelectionModel, setRowSelectionModel] = React.useState([]);

  const handleRowClick = (params) => {
    if (rowSelectionModel.length > 0 && params.id === rowSelectionModel[0]) {
      setRowSelectionModel([]);
    }
  };

  return (
    <div style={{ height: 500, width: "100%" }}>
      <DataGridPro
        rows={rows}
        columns={columns}
        onRowClick={handleRowClick}
        onRowSelectionModelChange={setRowSelectionModel}
        rowSelectionModel={rowSelectionModel}
        disableMultipleRowSelection
      />
    </div>
  );
}
`

Thank you

**Comment by jsimpson-www** [comment]
Hi Bilal,

Thank you for your response. Only listening to `onRowClick` works fine for my use case. Checkboxes are not desired from a UX perspective.

I was able to apply the sandbox example to my project and things are working as expected.  

In the initial response, you mentioned this is a 'hacky' way of doing this.  Without checkboxes, how would you prescribe doing this? I don't want to do things 'hacky' I want to do them correctly, but that was the best I came up with.

I consider this resolved, but very much welcome your / or other's approach at doing this in a non-hacky way.

Thank you

**Comment by MBilalShafi** [comment]
I considered it hacky initially because another handler (onRowClick) is used to set a different controlled state (rowSelectionModel). Ideally, onRowSelectionModelChange should be used to manipulate rowSelectionModel, but its good to know the solution worked for you.

I'll close the issue, meanwhile if someone wants to share another way to achieve this, they are most welcome to share it.

**Comment by agirgol** [comment]
Hello, using checkboxSelection, I take the selected row ids and pass them to another component. However, when each row is selected, it closes the open trees. How can I prevent this?```
 import * as React from 'react';
import { DataGridPro, GridColDef, GridPaginationModel, GridRowId } from '@mui/x-data-grid-pro';
import axios from 'axios';
import CompanyClaimTableListTopBar from './CompanyClaimTableListTopBar';
import { Box } from '@mui/material';

interface Item {
  id: string;
  companyClaimCode: string;
  companyClaimName: string;
  status: number;
  level: number;
  upperCompanyClaimId: string | null;
};

const status = [
  {
    value: 0,
    label: 'Active',
  },
  {
    value: 1,
    label: 'Inactive',
  },
  {
    value: 2,
    label: 'Archive',
  },
  {
    value: 3,
    label: 'Cancel',
  },
];

const transformData = (items: Item[]): { path: string; id: string; companyClaimCode: string; companyClaimName: string; status: number; }[] => {
  items.sort((a, b) => {
    if (a.level !== b.level) {
      return a.level - b.level;
    } else {
      return a.companyClaimName.localeCompare(b.companyClaimName);
    }
  });

  const transformedData: { path: string; id: string; companyClaimCode: string; companyClaimName: string; status: number; }[] = [];

  const map: { [id: string]: { path: string; id: string; companyClaimCode: string; companyClaimName: string; status: number; } } = {};

  items.forEach((item) => {
    map[item.id] = {
      path: item.companyClaimName,
      id: item.id,
      companyClaimCode: item.companyClaimCode,
      companyClaimName: item.companyClaimName,
      status: item.status
    };

    if (item.upperCompanyClaimId) {
      const upperItem = map[item.upperCompanyClaimId];
      map[item.id].path = `${upperItem.path}/${map[item.id].path}`;
    }

    transformedData.push(map[item.id]);
  });

  return transformedData;
};


function getStatusLabel(value: number): string {
  const statusObj = status.find((s) => s.value === value);
  return statusObj ? statusObj.label : 'Unknown';
};

const columns: GridColDef[] = [
  { field: 'companyClaimCode', headerName: 'Company Claim Code', width: 150 },
  { field: 'companyClaimName', headerName: 'Company Claim Name', width: 250 },
  { 
    field: 'status', 
    headerName: 'Status', 
    width: 150,
    renderCell: (params) => getStatusLabel(params.value as number)
  }
];

export default function TreeDataGrid() {
  const [rows, setRows] = React.useState<{ path: string; id: string; companyClaimName: string; }[]>([]);
  const [loading, setLoading] = React.useState<boolean>(true);
  const [paginationModel, setPaginationModel] = React.useState<GridPaginationModel>({
    page: 0,
    pageSize: 5,
  });
  const [rowCount, setRowCount] = React.useState<number>(0);
  const [selectedRowIds, setSelectedRowIds] = React.useState<Set<GridRowId>>(new Set());

  const fetchData = async (page: number, pageSize: number) => {
    setLoading(true);
    try {
      const response = await axios.get('/api/CompanyClaims', {
        params: { page, pageSize },
      });
      const { items, count } = response.data;
      const transformedRows = transformData(items);
      setRows(transformedRows);
      setRowCount(count);
    } catch (error) {
      console.error('Failed to fetch data', error);
    } finally {
      setLoading(false);
    }
  };

  const handlePaginationModelChange = (newModel: GridPaginationModel) => {
    setPaginationModel(newModel);
  };

  const handleRowSelectionChange = (newSelection: GridRowId[]) => {
    setSelectedRowIds(new Set(newSelection));
  };

  const handleDelete = () => {
    const idsArray = Array.from(selectedRowIds);
    const requestBody = { ids: idsArray };

    axios.delete('/api/CompanyClaims', {
      data: requestBody,
    })
    .then(response => {
      console.log('API Response:', response.data);
      fetchData(paginationModel.page, paginationModel.pageSize);
    })
    .catch(error => {
      console.error('Error:', error);
    });
  };

  React.useEffect(() => {
    fetchData(paginationModel.page, paginationModel.pageSize);
  }, [paginationModel]);

  return (
    <Box>
      <CompanyClaimTableListTopBar numSelected={selectedRowIds.size} selectedIds={selectedRowIds} onDelete={handleDelete} />
      <DataGridPro
        treeData
        getTreeDataPath={(row) => row.path.split('/')}
        rows={rows}
        columns={columns}
        loading={loading}
        pagination
        paginationMode="server"
        rowCount={rowCount}
        pageSizeOptions={[5, 10, 20]}
        paginationModel={paginationModel}
        onPaginationModelChange={handlePaginationModelChange}
        checkboxSelection
        onRowSelectionModelChange={handleRowSelectionChange}
      />
    </Box>
  );
}

```
