### ISSUE TITLE
[pickers] MonthPicker doesn't re-render on `minDate` or `maxDate` change

### ISSUE THREAD

**Issue by AlexKrupko** [mui/mui-x#9133]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: [https://codesandbox.io/s/vigorous-resonance-jp7r9z?file=/src/App.tsx](https://codesandbox.io/s/vigorous-resonance-jp7r9z?file=/src/App.tsx)

Steps:
1. Open codesandbox link above
2. Jun-Dec months are disabled because `maxDate` props is provided (see console log)
3. Click prev arrow button 
4. Jun-Dec months are still disabled, but `maxDate` props is `null` now
5. Click on any month to trigger rerender
6. All months are enabled now 

The same behavior with `minDate` and `shouldDisableMonth` props 

x-date-pickers version 6.0.3 on codesandbox and the same behavior in the lates 6.5.0 on my local

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Thank you for opening this issue. 🙏 
I can confirm that there is a problem here. 👌 
Looking for a fix.
