### ISSUE TITLE
date picker in tablet will be excatly in desktop

### ISSUE THREAD

**Issue by mf0548414295** [mui/mui-x#9148]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I want to do datepicker in hebrew,is it possible?

additionally, I want the date picker in tablet will be excatly in desktop, how do I do it?

thanks

### Current behavior 😯

1. the date picker in tablet different from datePicker in desktop
2. datepicker in english

### Expected behavior 🤔

1. the date picker in tablet will be excatly in desktop
2. datepicker in hebrew

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

google chrome

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.16.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.7 - ~\Desktop\HAMATZ-1\client\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.57)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.125
    @mui/core-downloads-tracker:  5.12.0
    @mui/material: ^5.11.9 => 5.12.0
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/system:  5.12.0
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-date-pickers: ^6.0.1 => 6.3.1
    @types/react: ^18.2.6 => 18.2.6
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.3 => 4.9.5

</details>

**Comment by noraleonte** [comment]
Regarding the language of the `DatePicker` component, if you need to change the translation of the Gregorian calendar from English to Hebrew, please refer [to this page in the documentation](https://mui.com/x/react-date-pickers/localization/). 

However, if you are looking for the Hebrew calendar system, I am unsure if any of our adapters have support for it at the moment - but a new adapter can be created. You can check [this page](https://mui.com/x/react-date-pickers/calendar-systems/) for supported calendar systems 😄 

Regarding the usage of the `DatePicker` in desktop/tablet, the default behavior (which is to render the `DesktopDatePicker` if this [`@media (pointer: fine)`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer) css media query passes) can be overridden with the `desktopModeMediaQuery` prop. You can change this prop to a different css media query that targets both desktop and tablet. More on this [here](https://mui.com/x/react-date-pickers/date-picker/#available-components)

Let me know if this answers your questions 😄
