### ISSUE TITLE
[question] datagrid rendering

### ISSUE THREAD

**Issue by NareshMurthy** [mui/mui-x#9156]
### Order ID or Support key 💳 (optional)

56539

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have a data grid with 100 rows each has an image tag, at once viewport renders 10 rows, upon scrolling the datagrid to the bottom, the network call for image is made to fetch the image that's ok, but upon scrolling back again to the records which were visible earlier the network call made again for the image.

Is it possible to fetch the image only once when it's in view?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @NareshMurthy 
The images are usually cached by the browser and served from the cache on subsequent requests:
See this example: https://mui.com/x/react-data-grid/sorting/

<img width="649" alt="Screenshot 2023-05-30 at 22 12 47" src="https://github.com/mui/mui-x/assets/13808724/4cddfb7a-1c93-4374-97ed-d228f369ecc6">

**Comment by cherniavskii** [comment]
Also, this is not specific to the DataGrid - the same applies to other libraries that use virtualization 🙂
I'm closing this issue since we have no actions to take.
