### ISSUE TITLE
In grouping columns, need a column freezing feasibility without pro version

### ISSUE THREAD

**Issue by AshNiz24** [mui/mui-x#9158]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Here is a sample grouping column example. 
I have attached the link below
Can anyone help using CSS or any properties to freeze the first two columns without using a pro or premium version

Thanks in advance

### Examples 🌈

https://codesandbox.io/embed/modest-kowalevski-xwox7r?fontsize=14&hidenavigation=1&theme=dark

**Comment by alexfauquette** [comment]
Your link is not working. It redirects to stackblitz.com without any code

**Comment by AshNiz24** [comment]
I have updated the link. I am looking for column pinning in MIT version when the columns are grouped.

**Comment by alexfauquette** [comment]
For 1 column you can use `position: 'relative'` on the row and `position: 'sticky', left: 0px`. It could do the job, for more than 1 column, I don't know how to set the `left` property.
