### ISSUE TITLE
[question] How can I add a custom attribute to each row of a MUI DataGrid (pro) table?

### ISSUE THREAD

**Issue by clarabesset** [mui/mui-x#9160]
### Order ID or Support key 💳 (optional)

666a2feaef4969afd3756507435f17d2T1JERVI6NDIyNzgsRVhQSVJZPTE2ODIxODAxNTIwMDAsS0VZVkVSU0lPTj0x

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello! 

I need to add the attribute 'data-testid' to each row of a table, but I cannot figure out how to do so using MUI DataGrid Pro. Adding classNames is possible (using [getRowClassName](https://mui.com/x/api/data-grid/data-grid-pro/)), but adding an attribute, along with its value (something like `data-testid='row-{key}`, seems more complicated.

I tried using getRowClassName and [slotProps](https://mui.com/x/react-data-grid/components/), with no success. I saw [this recent PR](https://github.com/mui/mui-x/pull/8845) added `data-` attributes at the root level, but not on the row level. I know  `data-id` and `data-rowindex` are available by default but unfortunately cannot use these. 

Thank you for your help!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 12.3
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/base:  5.0.0-alpha.113 
    @mui/core-downloads-tracker:  5.11.4 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/lab: ^5.0.0-alpha.115 => 5.0.0-alpha.115 
    @mui/material: ^5.11.4 => 5.11.4 
    @mui/private-theming:  5.11.2 
    @mui/styled-engine:  5.11.0 
    @mui/styles: ^5.11.2 => 5.11.2 
    @mui/system: ^5.11.4 => 5.11.4 
    @mui/types:  7.2.3 
    @mui/utils: ^5.11.2 => 5.11.2 
    @mui/x-data-grid: ^5.17.18 => 5.17.18 
    @mui/x-data-grid-pro: ^5.17.18 => 5.17.18 
    @mui/x-date-pickers: ^5.0.19 => 5.0.19 
    @mui/x-license-pro: ^5.17.12 => 5.17.12 
    @types/react: ^18.0.21 => 18.0.25 
    react: ^18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.8.4 
```
</details>

**Comment by clarabesset** [comment]
> Have you tried using a custom row?
> 
> ```tsx
> import { GridRow } from '@mui/x-data-grid'
> 
> function CustomGridRow(props) {
>   return (
>     <GridRow
>       {...props}
>       data-testid='abc'
>     />
>   )
> }
> 
> const slots = {
>   row: CustomGridRow,
> }
> ```
> 
> https://mui.com/x/api/data-grid/data-grid/#slots

No actually! Thank you for your quick response, I'll try this now 😊

**Comment by romgrk** [comment]
Cool, let us know if it doesn't work.

**Comment by gooddevil79** [comment]
Hey, could you find any solution for this ? I'm trying to write BDD test, and i need to pass test id like this.
