### ISSUE TITLE
MUI Tooltip is multiplying on MUI Datagrid update (Firefox only)

### ISSUE THREAD

**Issue by Mexanik2003** [mui/mui-x#9161]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/infallible-violet-ccwxqd?file=/demo.tsx

Steps:
1. Place mouse cursor on any cell in First name column
2. Wait until the tooltip appears 
3. Don't move the mouse cursor

### Current behavior 😯

Only in Firefox, Chrome is ok:
After some seconds, you will see a lot of tooltips in some rows:
<img width="524" alt="image" src="https://github.com/mui/mui-x/assets/77839322/1af761e6-9c4b-4fbf-b71c-2274c4ebc70c">

### Expected behavior 🤔

Only one tooltip under the cursor
<img width="515" alt="image" src="https://github.com/mui/mui-x/assets/77839322/434d0b95-258f-439b-8e62-64d677ba821a">

### Context 🔦

Don't mind the letter "A" near cursor - it is macOS tooltip, not MUI's

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

48449

**Comment by cherniavskii** [comment]
Interesting, this looks like an issue with the Tooltip in Firefox - I can reproduce it without the data grid: https://codesandbox.io/s/young-morning-uf7hnq?file=/demo.tsx


https://github.com/mui/mui-x/assets/13808724/88bf58a6-5631-43af-ba9b-42a32aadc41a

I'll open an issue for it in the Core repo.

**Comment by cherniavskii** [comment]
https://github.com/mui/material-ui/issues/37454
