### ISSUE TITLE
[question] Single Grouping Column sorting applied to all levels.

### ISSUE THREAD

**Issue by tielushko** [mui/mui-x#9177]
### Order ID or Support key 💳 (optional)

62502

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I was looking for a way to have the members of the single grouping column (including sub-groups) have the sorting applied to them. 

Currently from the docs, I can only infer that I need multiple sorting group columns along with multiple sorting criteria to achieve the nested rows grouping. https://mui.com/x/react-data-grid/row-grouping/#single-grouping-column-2

see the sandbox here as well: https://codesandbox.io/s/nested-grouping-level-not-sorted-sjnuki?file=/demo.tsx

From what I can tell right now, I can only pick the single sortComparator. Is there a way to apply the same sort comparator (alphanumerical string sort) to the inner grouping as the outer grouping? 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by tielushko** [comment]
I would like the grouping column ( where it is a "single grouping column" with 2 or more groups applied). In the sandbox example, the rowGrouping model consists of [company, director], where when I sort the grouping column, it not only sorts on the "company" field, but also applies the same sort comparator to the director field. 

See screenshots:
Actual case: DESC sort applied only to the outer group. The inner group is not sorted in desc order: David Yates appears in front of James Wan.

![Uploading image.png…]()

Desired case for my purposes: 
>Warner Bros. 
      >Todd Philips
      >James Wan
      >David Yates
      >Christopher Nolan
>Universal Pictures

(Notice how both outer grouping and inner grouping level have the sorting applied).

**Comment by tielushko** [comment]
@m4theushw, do you happen to have any updates regarding this issue?

**Comment by cherniavskii** [comment]
@tielushko Could you check this demo? https://codesandbox.io/s/heuristic-drake-fjynzs?file=/demo.tsx
Is this what you're looking for?

**Comment by cherniavskii** [comment]
On second thought, I think I misunderstood this statement:

> When using rowGroupingColumnMode = "single", the default behavior is to apply the sortComparator and filterOperators of the top-level grouping criteria.
http://localhost:3001/x/react-data-grid/row-grouping/#single-grouping-column-2

What I thought it means is that only the top-level group values will be sorted.
What it means is that `sortComparator` and `filterOperators` of the main grouping criteria will be used to sort and filter all the group values.

I believe the fact that not all group values are being sorted is a bug.
I also think that values from each group criteria should be using `sortComparator` from their column definition, not the one defined by `mainGroupingCriteria` - this is what I did in https://github.com/mui/mui-x/issues/9177#issuecomment-1589744400
```diff
diff --git a/packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx b/packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
index d5a771204..1b42685fa 100644
--- a/packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
+++ b/packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/createGroupingColDef.tsx
@@ -99,11 +99,11 @@ const getGroupingCriteriaProperties = (groupedByColDef: GridColDef, applyHeaderN
       // We only want to sort the groups of the current grouping criteria
       if (
         cellParams1.rowNode.type === 'group' &&
-        cellParams1.rowNode.groupingField === groupedByColDef.field &&
         cellParams2.rowNode.type === 'group' &&
-        cellParams2.rowNode.groupingField === groupedByColDef.field
+        cellParams1.rowNode.groupingField === cellParams2.rowNode.groupingField
       ) {
-        return groupedByColDef.sortComparator!(v1, v2, cellParams1, cellParams2);
+        const colDef = cellParams1.api.getColumn(cellParams1.rowNode.groupingField);
+        return colDef.sortComparator(v1, v2, cellParams1, cellParams2);
       }
 
       return groupingFieldIndexComparator(v1, v2, cellParams1, cellParams2);
```
The diff above will make the `mainGroupingCriteria` irrelevant for sorting.

**Comment by tielushko** [comment]
@cherniavskii the demo example in the link is exactly the behavior I was looking for. I think I can attach the sort comparator to my grouping ColDef and run with it until the resolution. Thank you for your suggestion!

**Comment by cherniavskii** [comment]
@tielushko Great!
