### ISSUE TITLE
[DataGridPremium] gridExpandedRowCountSelector showing count for previously applied filters

### ISSUE THREAD

**Issue by tielushko** [mui/mui-x#9178]
### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/gridexpandedrowcountselector-showing-old-filter-count-ytlugm

Steps:
1. Type "James" in the quick filter window.
2. Note how the count of the filtered rows is 6 (out of total of 6 rows) when in reality only 3 rows are shown (displayed by the footer).
3. Hit "X" to clear the quick filter. 
4. note how the quick filter items got cleared, but the count of filtered rows is still 3 (when it should be 6). 

### Current behavior 😯

gridExpandedRowCountSelector stores the count when the previous filter model applied to the data grid rows 

### Expected behavior 🤔

I expect the gridExpandedRowCountSelector to show the count of filtered rows after the filters were applied. I understand that there's a debounce happening before the model changed and the filter got implemented, however then the count of rows should change accordingly as it does with the footer. 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

62502

**Comment by cherniavskii** [comment]
To explain the current behavior - the `filterModelChange` event is fired when the filter model changes before the rows state is recalculated with the new filtering model.

**Comment by m4theushw** [comment]
Internally we have the `filteredRowsSet` event that is fired after the filtering process is done, however, it's not documented because we may change or remove it in the future. For now, you can use a workaround which is to wrap the selector call in `setTimeout` ([example](https://codesandbox.io/s/gridexpandedrowcountselector-showing-old-filter-count-forked-jd8ljb?file=/demo.tsx)). This will ensure that it's called after all computations.

>  I was just under the impression that the selector will work since the documentation mentioned it's applied after the filtering process.

What we want to mean is that the returned rows are those that survived the filtering process, not that the selector will react to model changes.

**Comment by cherniavskii** [comment]
I'll look into it later to see how we can support `autoHeight` with max height limit

**Comment by tielushko** [comment]
> Internally we have the `filteredRowsSet` event that is fired after the filtering process is done, however, it's not documented because we may change or remove it in the future. For now, you can use a workaround which is to wrap the selector call in `setTimeout` ([example](https://codesandbox.io/s/gridexpandedrowcountselector-showing-old-filter-count-forked-jd8ljb?file=/demo.tsx)). This will ensure that it's called after all computations.
> 
> > I was just under the impression that the selector will work since the documentation mentioned it's applied after the filtering process.
> 
> What we want to mean is that the returned rows are those that survived the filtering process, not that the selector will react to model changes.

@m4theushw setTimeout functionality is not ideal because the autoHeight property is still applied, meaning it will attempt to draw all of my rows first, then setState will be triggered for the autoHeight. I will try to provide an example of what I mean soon
