### ISSUE TITLE
How to dynamically update renderEditCell content based on new values?

### ISSUE THREAD

**Issue by CypherRat** [mui/mui-x#9185]
### Order ID or Support key 💳 (optional)

65748

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm trying to use renderEditCell to show an AutoComplete component with options that is dynamically retrieved from the backend, my problem is that the values are not getting updated when I get the data from the backend, it shows the same values that was provided initially. 

columns.tsx
```typescript
{
      field: "name",
      headerName: "Name",
      flex: 1,
      minWidth: 192,
      editable: published ? false : true,
      valueGetter: (params) => params?.row?.name,
      renderEditCell: (params) => (
        <AutocompleteEditCell
          {...params}
          options={options}
          freeSolo={false}
          multiple={false}
          disableClearable
        />
      ),
    },
```

AutocompleteEditCell Component
```typescript
function AutocompleteEditCell<
  T extends { value: string; label: string },
  Multiple extends boolean = false,
  DisableClearable extends boolean = false,
  FreeSolo extends boolean = false
>({
  id,
  value,
  field,
  options,
  disableClearable,
  multiple,
  freeSolo,
}: GridRenderEditCellParams & {
  options: UseAutocompleteProps<T, Multiple, DisableClearable, FreeSolo>["options"];
  disableClearable: DisableClearable;
  multiple: Multiple;
  freeSolo: FreeSolo;
}) {
  const apiRef = useGridApiContext();
  const handleValueChange = (
    _: any,
    newValue: AutocompleteValue<T, Multiple, DisableClearable, FreeSolo>
  ) => {
    apiRef.current.setEditCellValue({
      id,
      field,
      // @ts-expect-error i can't figure out how to use AutocompleteValue
      value: typeof newValue === "string" ? value : newValue?.value || "",
    });
  };

  return (
    <Autocomplete<T, Multiple, DisableClearable, FreeSolo>
      fullWidth
      disableClearable={disableClearable}
      multiple={multiple}
      options={options}
      freeSolo={freeSolo}
      // @ts-expect-error i can't figure out how to use AutocompleteValue
      value={options.find((o) => o.value === value)?.label || ""}
      onChange={handleValueChange}
      renderInput={(params) => <TextField {...params} />}
    />
  );
}
```

### Your environment 🌎

System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)

**Comment by m4theushw** [comment]
Where are you storing `options`? Do you have a CodeSandbox with a full example, showing also the retrieval of the new options? You can mock the server requests.

**Comment by nyxfor13days** [comment]
> Where are you storing `options`? Do you have a CodeSandbox with a full example, showing also the retrieval of the new options? You can mock the server requests.

The options are being stored in a useState after we make an api call to the backend using apolloClient. We will post a codeSandbox soon once we are ready with it.
