### ISSUE TITLE
[pickers] Can't change DesktopDateTimePicker vertical scrollbar

### ISSUE THREAD

**Issue by ChineseOuchie** [mui/mui-x#9193]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

```
<DateTimePicker
	timeSteps={{
		hours: 1,
		minutes: 1,
		seconds: 1,
	}}
	sx={{
		"ul": {
			"::-webkit-scrollbar": {
				width: "2px"
			}
		}
	}}
	ampm={false}
	views={["year", "month", "day", "hours", "minutes", "seconds"]}
	slotProps={{
		actionBar: {
			actions: ["clear"],
		},
		textField: {
			variant: "standard",
			helperText: `Filter Mode: ${filterName}`,
			sx: {
				width: "100%"
			},
			InputProps: {
				startAdornment: <ClearButton column={column} />
			},

		},
		openPickerButton: {
			sx: {
				marginRight: 0
			},
			size: "small"
		}

	}}
	format={"DD-MM-YYYY HH:mm:ss"}
/>
```

### Current behavior 😯

The vertical scrollbar remains the same size.

### Expected behavior 🤔

Vertical scrollbar should be smaller in width, but is still the same size: 
![image](https://github.com/mui/mui-x/assets/10912994/f1ab94e3-9238-4ae1-83b2-a98a9904ffe8)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.14.0 - 
    Yarn: Not Found
    npm: 9.3.1 -
  Browsers:
    Chrome: Version 113.0.5672.127 (Official Build) (64-bit)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/styled: ^11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.118
    @mui/core-downloads-tracker:  5.11.9
    @mui/icons-material: ^5.11.9 => 5.11.9
    @mui/material: ^5.11.10 => 5.11.10
    @mui/private-theming:  5.11.9
    @mui/styled-engine:  5.11.9
    @mui/system:  5.11.9
    @mui/types:  7.2.3
    @mui/utils:  5.13.1
    @mui/x-data-grid: ^6.2.1 => 6.2.1
    @mui/x-date-pickers: ^6.6.0 => 6.6.0
    @types/react: ^18.0.27 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.3 => 4.9.5
```
</details>

**Comment by LukasTy** [comment]
Hello @ChineseOuchie 

Thank you for being so quick to adopt new features! 🎉 

The reason why referenced style override doesn't work is because the `sx` prop applied to the `DateTimePicker` component is passed down to the `TextField` component.

Your best option would be to apply the mentioned style to `slotProps.layout`:
```tsx
slotProps={{
  layout: {
    sx: {
      ul: {
        '::-webkit-scrollbar': {
          width: '2px',
        },
      },
    },
  }
}}
```
Although, be careful with this particular style, because it hides the scrollbar on MacOS altogether. 🙈 
You'll probably need to work way harder with custom styles to achieve anything close to what the built-in scrollbar delivers.

**Comment by ChineseOuchie** [comment]
> Thank you for being so quick to adopt new features! 🎉

Yes, I was waiting for this feature. Great that it's ready.😄 


```
slotProps={{
  layout: {
    sx: {
      ul: {
        '::-webkit-scrollbar': {
          width: '2px',
        },
      },
    },
  }
}}
```

This works, thanks!

**Comment by buigabor** [comment]
@LukasTy Is there any way to use a custom component for the scrollbar? Like so:
`slots={{
    scrollbar: CustomScrolbar,
  }}`

**Comment by buigabor** [comment]
We'd prefer using our custom scrollbar component to maintain consistency for the DateTimePicker's vertical scrollbar. Alternatively, we can manually apply the styles as mentioned in the previous answer, which suits our use case. I was just curious if there's a possibility of using it as a slot somehow.

**Comment by LukasTy** [comment]
> I was just curious if there's a possibility of using it as a slot somehow.

No, we did not try to push a certain OS-specific design detail onto our users and settled on using the default scrollbar that the OS/browser combination provides.
For anyone wanting to maintain their own custom design style, it shouldn't be too much trouble to override it. 👌

**Comment by ThreeCrown** [comment]
> Hello @chineseouchie
> 
> Thank you for being so quick to adopt new features! 🎉
> 
> The reason why referenced style override doesn't work is because the `sx` prop applied to the `DateTimePicker` component is passed down to the `TextField` component.
> 
> Your best option would be to apply the mentioned style to `slotProps.layout`:
> 
> ```tsx
> slotProps={{
>   layout: {
>     sx: {
>       ul: {
>         '::-webkit-scrollbar': {
>           width: '2px',
>         },
>       },
>     },
>   }
> }}
> ```
> 
> Although, be careful with this particular style, because it hides the scrollbar on MacOS altogether. 🙈 You'll probably need to work way harder with custom styles to achieve anything close to what the built-in scrollbar delivers.

I tried this as well as with the toolbar and neither seemed to work with me for my scrollbar styling:
```
'&::-webkit-scrollbar': {
    width: '5px',
    height: '5px',
  },
  '&::-webkit-scrollbar-track': {
    background: 'rgb(0,73,130)',
    borderRadius: '10px',
  },
  '&::-webkit-scrollbar-thumb': {
    borderRadius: '20px',
    background: 'rgb(24,252,252)',
  },
  ```
  it could be because I am forcing it to render as one column for the digital clock using the threshold:
  `thresholdToRenderTimeInASingleColumn={300}` and I'm not sure what to target specifically in the layout prop.

**Comment by LukasTy** [comment]
> I tried this as well as with the toolbar and neither seemed to work with me for my scrollbar styling:
> 
> ```
> '&::-webkit-scrollbar': {
>     width: '5px',
>     height: '5px',
>   },
>   '&::-webkit-scrollbar-track': {
>     background: 'rgb(0,73,130)',
>     borderRadius: '10px',
>   },
>   '&::-webkit-scrollbar-thumb': {
>     borderRadius: '20px',
>     background: 'rgb(24,252,252)',
>   },
> ```
> 
> it could be because I am forcing it to render as one column for the digital clock using the threshold: `thresholdToRenderTimeInASingleColumn={300}` and I'm not sure what to target specifically in the layout prop.

@ThreeCrown Forcing the single-column clock renders a different component, which has a scrollbar on the root `div` element, not the `ul`.
[Here is](https://stackblitz.com/edit/react-du4tut?file=Demo.tsx) a working demo with your desired styles. 😉

**Comment by ThreeCrown** [comment]
> > I tried this as well as with the toolbar and neither seemed to work with me for my scrollbar styling:
> > ```
> > '&::-webkit-scrollbar': {
> >     width: '5px',
> >     height: '5px',
> >   },
> >   '&::-webkit-scrollbar-track': {
> >     background: 'rgb(0,73,130)',
> >     borderRadius: '10px',
> >   },
> >   '&::-webkit-scrollbar-thumb': {
> >     borderRadius: '20px',
> >     background: 'rgb(24,252,252)',
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it could be because I am forcing it to render as one column for the digital clock using the threshold: `thresholdToRenderTimeInASingleColumn={300}` and I'm not sure what to target specifically in the layout prop.
> 
> @ThreeCrown Forcing the single-column clock renders a different component, which has a scrollbar on the root `div` element, not the `ul`. [Here is](https://stackblitz.com/edit/react-du4tut?file=Demo.tsx) a working demo with your desired styles. 😉

You are extremely helpful!

**Comment by raychunghk** [comment]
> ```tsx
>  '::-webkit-scrollbar'
> ```

This will result in vanished scrollbar.
My version below add styling to the hour and minutes list to have padding for the scrollbar.
`
slotProps={{
                  layout: {
                    sx: {
                      ul: {
                        "::-webkit-scrollbar": {
                          width: "8px",
                          color: "white",
                          background: "#e8e8e8",
                        },
                        "::-webkit-scrollbar-thumb": {
                          background: "#3c698b",
                        },
                        paddingRight: "62px", // Set padding to accommodate the scrollbar
                      },
                      "& li": {
                        position: "relative", // Ensure list items are positioned correctly
                      },
                    },
                  },
                  textField: {
                    sx: {
                      "& .MuiInputBase-root": {
                        height: "40px", // Set the desired height for the input box
                        padding: "0 14px", // Adjust horizontal padding
                      },
                      "& input": {
                        padding: "8px 0", // Adjust input padding for vertical centering
                      },
                    },
                  },
                }}
`
