### ISSUE TITLE
[data grid] Cell clipboard paste, leading "v"

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#9195]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open https://master--material-ui-x.netlify.app/x/react-data-grid/#mit-version

### Current behavior 😯

<kbd>Enter</kbd>+<kbd>v</kbd> is adding a leading "v"

https://github.com/mui/mui-x/assets/3165635/9b266b37-4565-4fc0-abba-1a122406b144

### Expected behavior 🤔

No leading "v"

### Context 🔦

I was doing a demo during React Summit

### Your environment 🌎

MUI X v6.6.0
mac OS v13.2.1
React 18.2.0

**Comment by oliviertassinari** [comment]
This reminds me a bit of #5729

**Comment by LumaKernel** [comment]
👍 little upvote with pro plan: 67619
