### ISSUE TITLE
DatePicker/DateField shows incorrect placeholder for format

### ISSUE THREAD

**Issue by agonzalezjr** [mui/mui-x#9198]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://codesandbox.io/s/mui-x-issue-template-forked-g38txl?file=/src/App.tsx

```
      <DateField label="date" format="DD/MMM/YYYY" />
```

### Current behavior 😯

Placeholder is: `DD/MMMM/YYYY`

### Expected behavior 🤔

Since the month will have 3 letters, placeholder should match format: `DD/MMM/YYYY`

Or is there an exposed way to customize the placeholder used for each of the field's parts?

### Context 🔦

I would like to be able to customize the placeholder if it won't be displayed matching the format.

### Your environment 🌎

Using `Chrome: 114.0.5735.90`

```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/code/bluejay/bluejay-amplify/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/base:  5.0.0-alpha.116 
    @mui/core-downloads-tracker:  5.11.7 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.7 => 5.11.7 
    @mui/private-theming:  5.11.7 
    @mui/styled-engine:  5.11.0 
    @mui/system:  5.11.7 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.7 
    @mui/x-date-pickers: ^6.4.0 => 6.4.0 
    @types/react: ^18.0.0 => 18.0.26 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.4.2 => 4.9.4 
```
</details>

**Comment by alexfauquette** [comment]
We define only one placeholder per time section (year, month, ...). You can override them by updating the [locale text](https://mui.com/x/react-date-pickers/localization/)

https://mui.com/x/react-date-pickers/adapters-locale/#custom-field-placeholder

**Comment by agonzalezjr** [comment]
Great, thanks!

This is how I did it:

```
<DateField 
    label="date" 
    format="DD/MMM/YYYY" />
    localeText={{
        fieldMonthPlaceholder: () => "MMM"
    }}
/>
```
