### ISSUE TITLE
Can we control the Vertical Alignment of a column?

### ISSUE THREAD

**Issue by benjimac93** [mui/mui-x#9199]
### Order ID or Support key 💳 (optional)

59265

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We'd like to have the highlighted columns to be vertically aligned, due to the sometimes VERY large contents in the notes column, but can't find anything in the docs to support this

Is this currently possible?

![image](https://github.com/mui/mui-x/assets/33694220/912437e3-f975-40e3-a560-00a64bb3ec96)

### Your environment 🌎

  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 19.6.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.4.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react: 11.11.0 => 11.11.0 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-alpha.128 
    @mui/core-downloads-tracker:  5.12.3 
    @mui/icons-material: 5.11.16 => 5.11.16 
    @mui/material: 5.13.3 => 5.12.3 
    @mui/private-theming:  5.12.3 
    @mui/styled-engine:  5.12.3 
    @mui/system:  5.12.3 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.3 
    @mui/x-data-grid:  5.17.26 
    @mui/x-data-grid-premium: 5.17.26 => 5.17.26 
    @mui/x-data-grid-pro:  5.17.26 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-date-pickers-pro: 5.0.20 => 5.0.20 
    @mui/x-license-pro:  5.17.12 
    @types/react: 17.0.60 => 17.0.59 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.9.5 => 4.9.5

**Comment by AmeliaIsCoding** [comment]
is this possible?
