### ISSUE TITLE
[question] How to prevent expanded rows from being contracted on rows updation?

### ISSUE THREAD

**Issue by BrianSHenderson** [mui/mui-x#9201]
### Order ID or Support key 💳 (optional)

8879

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

With the Grouping option I would like to be able to select a group then add a new record.  The code adds a new record to the db then I refetch the table data.  However all the expanded rows are then contracted.  Is there any way to stop this?

Is it possible to get a list of all expanded nodes?

Thanks 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
Chrome
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 6.8.0 - ~/Documents/Documents/Repositories/node_modules/.bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: Not Found
    Firefox: 110.0
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.3 
    @mui/core-downloads-tracker:  5.13.3 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/material: ^5.12.1 => 5.13.3 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.2 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-data-grid:  6.5.0 
    @mui/x-data-grid-premium: 6.5 => 6.5.0 
    @mui/x-data-grid-pro:  6.5.0 
    @mui/x-license-pro: ^6.6.0 => 6.6.0 
    @types/react: 18.0.28 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 4.9.5 => 4.9.5 
</details>

**Comment by cherniavskii** [comment]
Hey @BrianSHenderson 
Could you try using [`updateRows` method](https://mui.com/x/react-data-grid/row-updates/#the-updaterows-method) to update the rows? It should persist the expansions state.

**Comment by cherniavskii** [comment]
Similar issue https://github.com/mui/mui-x/issues/9101

**Comment by BrianSHenderson** [comment]
I had a look through those issues but I cannot see any example code of using processRowUpdate to add a new row to the collection.  Are there any examples I can look at?

Thanks

**Comment by cherniavskii** [comment]
Do you mean to add a new row while editing a different one? From the issue description, I thought you had a functioning grid and the problem was that the groups collapse when you update the rows. Is that right?

**Comment by BrianSHenderson** [comment]
Basically I have a Grid with school students in a school and I am grouping by year group and class name.  I want the user to be able to add a new student to a class as well as edit & delete students.  Is this possible?

**Comment by cherniavskii** [comment]
> Basically I have a Grid with school students in a school and I am grouping by year group and class name. I want the user to be able to add a new student to a class as well as edit & delete students. Is this possible?

Something like this? https://codesandbox.io/s/sweet-moon-jjyfj9?file=/demo.tsx

**Comment by flaviendelangle** [comment]
Could someone edit the title of this issue please?
