### ISSUE TITLE
[pickers] Show `TimeClock` instead of `DigitalClock` in DesktopDateTimePicker

### ISSUE THREAD

**Issue by FranciscoFerreiraXS** [mui/mui-x#9202]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am currently working in a project where the DatePicker in version 5.11 had a few issues and had to update MaterialUI to version 6.6.

In doing so, the other component (DateTimePicker) that was made to select the date through a calendar and the time with an actual clock stopped working.

Selecting through the calendar is fine, but we would like to keep the DateTimePicker with the TimeClock component instead of the digital one.

Is it possible to add something like a boolean to give more freedom to the users to choose which clock they want? Or is there an actual way to replace the digital clock with the time one in the desktop version?

**Comment by LukasTy** [comment]
> Or is there an actual way to replace the digital clock with the time one in the desktop version?

Yes, there is a way to revert the UI to the `TimeClock` one and it is pretty easy, just not well documented. 🙈 
Try passing the following prop to the `DateTimePicker` component or define it via `theme` through `defaultProps`:
```tsx
viewRenderers={{
  hours: renderTimeViewClock,
  minutes: renderTimeViewClock,
  seconds: renderTimeViewClock
}}
```

This issue just shows that we should provide this information in the documentation. 👌 💡
