### ISSUE TITLE
Dynamically updating DataGrid columns fires erroneous sortModelChange event with an empty model

### ISSUE THREAD

**Issue by alexgonch** [mui/mui-x#9204]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/sharp-violet-e7q8fd?file=/demo.tsx

Steps:
1. Open "Console" view
2. Click "Toggle columns" button
3. Notice that `newSortModel` in the `onSortModelChange` handler is empty

### Current behavior 😯

When dynamically switching `sortModel` and `columns`, DataGrid generates a sortModelChange event that contains an empty model despite the fact that the model is never actually empty in the process. Please note that `onFilterModelChange` is affected in an identical way but I chose not to add it to this issue for brevity.

### Expected behavior 🤔

Either this event should not be fired at all, or it should contain the new `sortModel` that matches the new columns. I imagine the latter is desirable for consistency sake.

### Context 🔦

We've had troubles due to this issue for a while but it has become a major roadblock in our upcoming release. We are relying heavily on a controlled server-side DataGrid implementation for one of the key parts of the app. One of the primary use-cases involves switching columns on the fly and the erroneously empty models from `onSortModelChange` and `onFilterModelChange` are picked up by the handlers and override non-empty models that we provide from our central storage.

### Your environment 🌎

My sandbox uses latest React, MUI base and DataGrid libraries.

### Order ID or Support key 💳 (optional)

30376

**Comment by cherniavskii** [comment]
Hey @alexgonch 
Thanks for opening this issue!

This looks like a bug.
When the `columns` are changed, we update the sort model by excluding columns that do not exist anymore:
https://github.com/mui/mui-x/blob/8201d0c6a70ea9ed89fbe44d5c60ecca7956ee40/packages/grid/x-data-grid/src/hooks/features/sorting/useGridSorting.ts#L326-L337

In your example, the `sortModel` also changes, but the grid reacts to this change in `useEffect`, which happens after the sort model is updated:
https://github.com/mui/mui-x/blob/8201d0c6a70ea9ed89fbe44d5c60ecca7956ee40/packages/grid/x-data-grid/src/hooks/features/sorting/useGridSorting.ts#L369-L373

We can try using `useLayoutEffect` instead of `useEffect` so that the sort model is updated before `handleColumnsChange` is called.

**Comment by cherniavskii** [comment]
For a workaround, you can keep the sorting model in the state and update it in `useEffect`:
```tsx
const [sortModel, setSortModel] = React.useState<GridSortModel>();

React.useEffect(() => {
  setSortModel(sortModels[mode]);
}, [sortModels, mode]);
```
Demo: https://codesandbox.io/s/friendly-rain-e5lksr?file=/demo.tsx

Would that work for you?

**Comment by alexgonch** [comment]
@cherniavskii thank you very much for getting back to me!

Unfortunately, the workaround is not going to work. Here's a forked sandbox example that shows a more accurate reproduction of a typical use-case for us and how it malfunctions due to the bug: https://codesandbox.io/s/suspicious-dubinsky-cthyku?file=/demo.tsx

Notice that the `sortModels` record is no longer static. We want to collect all of user-initiated sorting changes in our external storage and re-apply the updated model whenever columns change. Our users need to be able to switch between multiple modes (i.e. sets of columns) and we want to store their sorting & filtering states for each mode separately.

Another theoretical solution would be to make use of the `reason` parameter of the `onSortModelChange` callback, which would be set for all user interactions and undefined otherwise (currently it's undefined for all events). This would be similar to how `onFilterModelChange` works, except unfortunately that callback is missing the reasons for some of the events as well, but that's a story for another issue. If sorting `reason` was set appropriately, we could ignore all events with undefined reason and not sync them up to the external storage as a workaround.

I will look into forking mui-x and trying your suggested approach with `useLayoutEffect` in the meantime. Thank you again!

**Comment by cherniavskii** [comment]
Fixed by https://github.com/mui/mui-x/pull/9239
