### ISSUE TITLE
[data grid] Scrollbar is always shown if any column set to flex of any value

### ISSUE THREAD

**Issue by quantumwebco** [mui/mui-x#9219]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: coming soon

Steps:
1. Create a data grid using the example from the docs https://mui.com/x/react-data-grid/column-dimensions/#fluid-width
2. Set any column to flex with any value and all other columns to an arbitrary pixel value that in sum is less than the total width of the table

### Current behavior 😯

Horizontal scrollbar shows if any column is set to flex of any value. e.g. having 4 columns and setting width to 100 for 3 and flex: 1 for the last one shows the scrollbar even though there is no overflow

It's something to do with the 'virtualScroller'. When flex isn't set on any of the columns it has ```overflow-x: hidden``` and then set to auto if there are flex columns. I notice that when loading, before the rows have loaded the scrollbar is scrollable and the table is wider than the container but as soon as the rows have loaded it snaps back to being 100% width and the scrollbar not scrolling. Also when loading new rows by changing page or page length the scrollbars show and are scrollable suggesting the table has overflowed. Is it something to do with the loading spinner? 

### Expected behavior 🤔

Scrollbar should only show if columns are wider than table

### Context 🔦

I want columns to expand to fill available space like a normal HTML table but without horizontal scrollbars where there is no overflow

### Your environment 🌎

Browser: Chrome/Edge
IDE: PHPStorm  
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 2.54 GB / 5.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Managers:
    Apt: 2.0.9 - /usr/bin/apt
    Composer: 2.4.1 - /usr/local/bin/composer
  Utilities:
    CMake: 3.16.3 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.4.0 - /usr/bin/gcc
    Git: 2.37.3 - /usr/bin/git
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 23.0.5 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.78.2 - /mnt/c/Users/Rusty/AppData/Local/Programs/Microsoft VS Code/bin/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Go: 1.13.8 - /usr/bin/go
    Perl: 5.30.0 - /usr/bin/perl
    PHP: 8.1.9 - /usr/bin/php
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.8.10 - /usr/bin/python3
  Databases:
    MySQL: 0.20.04.2 - /usr/bin/mysql

**Comment by quantumwebco** [comment]
The issue is there in sandbox you just posted 
<img width="1756" alt="image" src="https://github.com/mui/mui-x/assets/12368817/72e8a88d-96b8-456c-ae7f-802a0bca2130">

**Comment by quantumwebco** [comment]
I can confirm it doesn't appear in Firefox. It seems to be chromium based browsers (Chrome/Edge/Brave etc.)

**Comment by quantumwebco** [comment]
Ah yes, didn't think of that. Monitors are 28" 4K (3840 x 2160) @ 150% scale

**Comment by appinsource2021** [comment]
> I submitted a fix. For now you can use the following workaround:
> 
> ```tsx
> <DataGrid
>   sx={{
>     '.MuiDataGrid-virtualScroller': {
>       overflow: 'hidden'
>     }
>   }}
> />
> ```

If use this option, scrollbar will not more show, problem is add prop flext: 1 to any column insert new columnt to end
