### ISSUE TITLE
with dayjs en-gb locale (which weekStart is monday), calendar renderDay is not align with weekday column

### ISSUE THREAD

**Issue by ericfong** [mui/mui-x#9223]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

@mui/x-date-pickers  6.6.0
dayjs  1.11.7

### Current behavior 😯

```js
import 'dayjs/locale/en-gb'
dayjs.locale('en-gb')
```

<img width="315" alt="image" src="https://github.com/mui/mui-x/assets/237028/ef73ef29-2810-4bb3-bc63-52f2ebd36071">

'en-gb' weekStart is 1 in https://github.com/iamkun/dayjs/blob/dev/src/locale/en-gb.js#L11
which make the weekday bar shift to the left, and which is what we want.

BUT

2023-06-05 is Monday and is under 'T' Tuesday now.

### Expected behavior 🤔

2023-06-05 is under 'M' Monday

### Your environment 🌎

<details>
```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.14.2 - /opt/homebrew/opt/node@18/bin/node
    Yarn: Not Found
    npm: 9.5.0 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.109
    @mui/core-downloads-tracker:  5.10.17
    @mui/icons-material: ^5.10.16 => 5.10.16
    @mui/lab: ^5.0.0-alpha.111 => 5.0.0-alpha.111
    @mui/material: ^5.10.17 => 5.10.17
    @mui/private-theming:  5.10.16
    @mui/styled-engine:  5.10.16
    @mui/styles: ^5.10.16 => 5.10.16
    @mui/system:  5.10.17
    @mui/types:  7.2.2
    @mui/utils:  5.13.1
    @mui/x-date-pickers: ^6.6.0 => 6.6.0
    @types/react:  17.0.44
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 5.0.4 => 5.0.4
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by LukasTy** [comment]
@ericfong Have you by any chance forgotten to provide `adapterLocale="en-gb"` to the `LocalizationProvider` component?
