### ISSUE TITLE
[pickers] Open Picker Icon for the Date Range Component 

### ISSUE THREAD

**Issue by CountrySmooth** [mui/mui-x#9233]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

For the Date Range Picker can we add an open picker Icon. Don't see the calendar icon for the Date Range Component but I do see it for the standard Date Picker component

**Comment by LukasTy** [comment]
Have you seen [this documentation example](https://mui.com/x/react-date-pickers/custom-field/#using-another-input) of adding a toggle icon to either Joy or native pickers using `SingleInputDateRangeField`?

Is it a DateRangePicker with `SingleInputDateRangeField` that you want to add an icon to?
In this case, the mentioned example should have sufficient information to do it.

Or do you want to add an icon to the regular DateRangePicker using separate start and end fields?
In this case, could you provide and example or a mockup of how you expect it to look like? 🤔
