### ISSUE TITLE
[RFC] Better isolate DataGridPro from DataGrid

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#924]
## Summary 💡

The two components should be better isolated. `XGrid` should be able to grow in complexity and package size without harming the bundle size of `DataGrid`. In the current configuration, both packages have the exact same size

## Motivation 🔦

- `DataGrid` is in competition in the space of a similar open-source data grid. The bundle size is one of the dimensions developers look at. I think that the biggest decision influence happens when one package looks disproportionally bigger than an equivalent solution. So this issue might be the one that has the most influence on this matter. I'm not sure that we will need to the same depth as we did in the main repository.

  If you look at the bundle size of ag-Grid, you can see that it can quickly get out of hand: [ag-grid-community](https://bundlephobia.com/result?p=ag-grid-community): 193 kB gzipped. They have tried to isolate features, but the core seems to be about the same size: [@ag-grid-community/core](https://bundlephobia.com/result?p=@ag-grid-community/core): 191 kB gzipped (it's only with the enterprise features that it seems to make a difference).

- The license should be better isolated. It's not OK to have all the content of `/packages/grid/_modules_` exported under an MIT licensed package.
- This effort should allow us to make the grid, and its feature more composable. It would be great to invest time in a plugin system. Some prior-arts: https://datatables.net/manual/plug-ins/.

**Comment by oliviertassinari** [comment]
@dtassone Has made a quick-win proposal to initiate this direction. We could create two `GridComponent`

https://github.com/mui-org/material-ui-x/blob/a0b719281f82460d0e7f829af40add2538c0e46e/packages/grid/_modules_/grid/GridComponent.tsx#L48

This won't solve the problem but put us in a better place. It will force us to start handling the matter as we build new features, in order to identify ways to reduce the duplication.

**Comment by oliviertassinari** [comment]
@mbrookes How important do you think this is? Would it make sense to do it post v5.0.0 stable?

I would personally advocate doing it before the Premium features, regardless of the stable nature. For the Pro features, IMHO, the main value is about forcing us to isolate features (tree shaking, code isolation, etc.)

**Comment by mbrookes** [comment]
It's important, but it can wait if there are other priorities.

**Comment by oliviertassinari** [comment]
Regarding sharing code, we might want to have `@material-ui/x-grid` depending on `@material-ui/data-grid`. It would have the following advantages:

1. Progressive migration, people adding XGrid in a few cases don't pay the bundle size overhead twice
2. Social proof, people using the premium version contributes to the downloads of the community version
3. Code structure. We would be able to kill the `grid/_module_` structure. Instead we can default to the approach we use in the core components, share the same bundling approach.

**Comment by flaviendelangle** [comment]
I think it will be hard to remove 100% of the XGrid-only code from the DataGrid bundle. Especially when this code is in the middle of a more generic hook / component that is also used by the DataGrid.

For instance everything related to those forced props :+1: 
```ts
  disableMultipleColumnsFiltering?: true;
  disableMultipleColumnsSorting?: true;
  disableMultipleSelection?: true;
```

But if we agree that the goal is to isolate as much as possible, then I agree that a structure like you describe would be better.

Maybe some advanced hooks like sorting / filtering will diverge between DataGrid and XGrid and justify having two distincts `useGridSorting`, one in DataGrid and one in XGrid importing some common utils methods from the one in DataGrid.
But I don't think it should be done only for bundle separation reasons, as it increase the codebase complexity.

___

Some non trivial examples:

### Selectors from XGrid used in a DataGrid component

The component `GridColumnHeadersItemCollection` (that is used in DataGrid) imports the selector  `gridColumnReorderDragColSelector` from the `useGridColumnsReorder` folder. Which is an XGrid-only feature and should be in the `@material-ui/x-grid` folder in the end.


### State initialization methods

Right now, the state from DataGrid also have the XGrid only default values which are defined in XGrid-only files (`getInitialGridColumnReorderState` for instance).

____

For the types, if we keep a shared `models` folder then the issue won't happen.
If we want to split the `models` folder into `data-grid/src/models` and `x-grid/src/models` then the same problem will occur.

But in both cases, having all the types in the `models` folder(s) will help avoid cases where we import types of XGrid in the DataGrid module from a XGrid file that is not type-only.

**Comment by oliviertassinari** [comment]
@flaviendelangle Agree, I think that we could work iteratively on this problem, focus where a separation/modularity would make the most sense. 

> The component GridColumnHeadersItemCollection (that is used in DataGrid) imports the selector gridColumnReorderDragColSelector

We could categories this as a leaky abstraction. The logic could have very well been reverse. The drag hook could use the `componentsProps` prop to inject props on the slots it needs to access, instead of the slot pulling in values from the hook.

> State initialization methods

We could move the initial state to the hook level, instead of having a centralized place.

> For the types, if we keep a shared models folder 

We could use module augmentation for the shared data structures. For instance: https://github.com/mui-org/material-ui/blob/40d9587f653a6e431f5ff0e3a2ca6cb0a3b8aba7/packages/material-ui-lab/src/themeAugmentation/props.d.ts#L67.

**Comment by flaviendelangle** [comment]
> We could move the initial state to the hook level, instead of having a centralized place.

I don't have the whole pictures of the impacts this change would have.
But conceptually, having something like the following could be interesting


```ts
const useGridPageSize = (apiRef, props) => {
  useGridStateInit(apiRef, state => ({ ...state, pagination: { page: props.page ?? 0 }}));
}

const useGridPage = (props) => {
  useGridStateInit(state => ({ ...state, pagination: { ...state.pagination, pageSize: props.pageSize }}));
}
```

```ts
const useGridStateInit = (apiRef, callback: (state: Partial<GridState>): Partial<GridState>)) => {
  const isInitialized = React.useRef(false);
  const [, setGridState] = useGridState(apiRef);

  if (!isInitialized.current) {
    setGridState(callback);
  }
} 
```

We would have a synchronous state initialization with the value from the props and the hook being responsible for its own state.
But the typing `Partial<GridState>` is not very precise since its relying on the hook order.

I think it tightly related to the prop-to-state pattern (https://github.com/mui-org/material-ui-x/issues/1562#issuecomment-860247688) and we may want to first take a deeper look at the approach we want to have for the update part.

In summary, maybe its better to wait to have a cleaner view of the approach we want to take.

**Comment by flaviendelangle** [comment]
> We could categories this as a leaky abstraction. The logic could have very well been reverse. The column reorder hook could use the componentsProps prop to inject props on the slots it needs to access, instead of the slot pulling in values from the hook.

I propose we start by reducing as much import from the XGrid part to the DataGrid part 
And then see how much of those scenarios we find. 
Because I agree that we may be able to fix all of them by changing the logic.

**Comment by oliviertassinari** [comment]
> Would it allow us to have the DataGrid state typing on the DataGrid folder in our codebase and the XGrid state typing on the XGrid folder?

@flaviendelangle No

**Comment by aderchox** [comment]
Not directly relevant to this issue, but I just wanted to also suggest better isolating them in the documentations. Currently as you read the docs, there's just a blue cube near each title which indicates that that feature belongs to the pro version, however, some of these features are vague and seem to have overlaps with the free features. For example consider this one: [Control with external buttons](https://mui.com/components/data-grid/editing/#control-with-external-buttons). When you check the source code, some JSX is wrapped in DataGrid, and some in DataGridPro, and yet it's not quite clear for a beginner like me which exact parts are pro and which are free. So I may decide to think better of using MUI's DataGrid free completely only because I can't have its doc separately.

**Comment by flaviendelangle** [comment]
Pining @joserodolfofreitas
