### ISSUE TITLE
How can I MuiMultiSectionDigitalClockSection

### ISSUE THREAD

**Issue by mariojsnunes** [mui/mui-x#9240]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Override  Mui X components with createTheme.
I'm on latest versions.
"@mui/material": "^5.13.4",
"@mui/x-date-pickers": "^6.6.0",

### Current behavior 😯

Overriding Mui X components with the theme causes build error.

![image](https://github.com/mui/mui-x/assets/8073622/3ccde10f-a4f2-48b7-b8cb-6932d2110dcd)

### Expected behavior 🤔

Should be able to override.

### Your environment 🌎

System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1702.0), Chromium (114.0.1823.37)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.4
    @mui/core-downloads-tracker:  5.13.4
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/material: ^5.13.4 => 5.13.4
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-date-pickers: ^6.6.0 => 6.6.0
    @types/react: ^18.0.28 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.6.4 => 4.8.4

**Comment by alexfauquette** [comment]
You miss the following line 

```ts
import type {} from "@mui/x-date-pickers/themeAugmentation";
```

[docs explainations](https://mui.com/x/react-date-pickers/base-concepts/#typescript)

**Comment by mariojsnunes** [comment]
Awesome, thanks!
