### ISSUE TITLE
[DatePicker] aesthetic problem if replace TextField

### ISSUE THREAD

**Issue by yamildiego** [mui/mui-x#9268]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/dazzling-allen-uxcf0h?file=/demo.tsx

Steps:

1. Change the date to another date, it works, but in the upper left corner the date panel opens and closes for less that a second, It happens very quickly, but when the button is further away from that corner, it becomes more noticeable.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by yamildiego** [comment]
Hello @flaviendelangle!

Thanks you so much for your answer.

My mistake, you are right I need something like componentsProps. but I still trying without success.

What I need is to be able to use the props required, error, helpertext, and label of the TextField.

Y tried this  way
              componentsProps ={{
                  inputProps: {
                    required: true,
                    error: true,
                    helperText: "some text",
                    label: "namee",
                  },
                }}
                and this way
                              slotProps={{
                  inputProps: {
                    required: true,
                    error: true,
                    helperText: "some text",
                    label: "namee",
                  },
                }}
                
I hardcoded the values for the example. 

In these ways are not working even I have a ts error.
sorry I read the documentations, there are examples how to use them

thank u so much

**Comment by flaviendelangle** [comment]
[Here is a working example](https://codesandbox.io/s/lucid-frost-9tdvhv?file=/demo.tsx)

Not sure why you tried to pass them to `inputProps`

I'm passing each prop to the highest element possible in the hierarchy.
For instance, the `label` is passed to the picker which will forward it to the field.

**Comment by yamildiego** [comment]
thanks you soo much for the example now is working, I am soo happy...  
sorry if I didnt explain myself properly, english is not my first lenguge I am still learning
thanks
