### ISSUE TITLE
[question] Unable to find GridSelectionModel related documentation while migrating from V5 to V6

### ISSUE THREAD

**Issue by Arkamit** [mui/mui-x#9271]
### Order ID or Support key 💳 (optional)

59954

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We are in the process of migrating Datagrid from V5 to V6 but couldn't find any relevant information for the same.

The error shows `'"@mui/x-data-grid-pro"' has no exported member named 'GridSelectionModel'. Did you mean 'GridRowSelectionModel'?`

Are we supposed to use GridRowSelectionModel instead?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Have you already checked the [v6 migration guide](https://mui.com/x/migration/migration-data-grid-v5/) especially the portion of [renamed props](https://mui.com/x/migration/migration-data-grid-v5/#%E2%9C%85-renamed-props)?

**Comment by Arkamit** [comment]
@MBilalShafi Yes, I have checked both the places but unfortunately couldn't find any reference for GridSelectionModel. Please let me know if I need to go through any other documentation.

**Comment by MBilalShafi** [comment]
I think `GridSelectionModel` refers to the typescript type of `selectionModel` (listed at the very top of the section I linked above) which was renamed to `rowSelectionModel` with the type `GridRowSelectionModel` in v6.

**Comment by Arkamit** [comment]
I understand your point. I will use GridRowSelectionModel as you mentioned. Thanks for your quick response.
