### ISSUE TITLE
[question]  is it possible to override null sort order? 

### ISSUE THREAD

**Issue by Jaryt** [mui/mui-x#9275]
### Order ID or Support key 💳 (optional)

N/A

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello again!

I have a row that's editable, but that I want pinned to the bottom. The first thing I needed to do was at least have this row pinned to the bottom when sorting. Here's my implementation 

```
  return (a, b, param1, param2) => {
    const aNew = isNewRow(param1.id);
    const bNew = isNewRow(param2.id);

    const sortModel = apiRef.current?.state?.sorting?.sortModel;
    const sort = sortModel?.find((model) => model.field === key).sort;
    const dir = sort === 'asc' ? 1 : -1;

    // handle sorting new rows
    if (aNew || bNew) {
      // multiply result by direction to reverse sort if needed
      return compareBooleans(aNew, bNew) * dir;
    }

    if (col.sortComparator) {
      return col.sortComparator(a, b, param1, param2);
    }

    // either use the col def type, or infer it from one of the values
    const type = col.type || typeof (a ?? b);

    switch (type) {
      case 'number':
        return b - a;
      case 'date':
        return new Date(b).getTime() - new Date(a).getTime();
      case 'string':
        return b?.localeCompare?.(a);
      case 'boolean':
        return compareBooleans(a, b);
      default:
        break;
    }
  };
```

(one improvement that could probably be made is to not handle the other types myself, feel free to provide input there if there's a global sort function I could reference instead of this manual implementation, but it does the trick at least.)

This seemed like a good solution, since our implementation only allows one new row at a time, it was only the last row. That was true up until we added a grouping column to our data grids. Since they're auto-generated rows, they get added at the bottom of the grid, underneath my new row, which is unfortunate. Of course, if a sorting model is applied, it's fine. It also seems that we could remove the `null` option from the sort order, but that's not a desirable solution since forcing sorting on our users would leave to unexpected jumpiness after a new row is applied. 

I'm wondering if there's anyway to get the `sortComparator` to be called even when it's null? Unfortunately, it seems as if we can't add custom sorting to the `sortingOrder` list. If that was possible, I could add my own custom nullish sort to the list and achieve that. Dipping my toes in the feature request direction a little bit, but perhaps that could be done by adding a `getSortIcon(sortOrder) => ...`  and opening up the `sortingOrder` array to accept `string | null | undefined`.

Cheers!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 3.3.0 - /mnt/c/Program Files/nodejs/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Firefox: 113.0.2 
  npmPackages:
    @emotion/react:  11.10.6 
    @emotion/styled:  11.10.6 
    @mui/base:  5.0.0-alpha.121 
    @mui/core-downloads-tracker:  5.11.13 
    @mui/icons-material:  5.11.11 
    @mui/lab:  5.0.0-alpha.123 
    @mui/material:  5.11.13 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.13 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-data-grid:  5.17.26 
    @mui/x-data-grid-premium:  5.17.26 
    @mui/x-data-grid-pro:  5.17.26 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-date-pickers-pro:  5.0.20 
    @mui/x-license-pro:  5.17.12 
    @types/react:  18.0.28 
    react:  17.0.2 
    react-dom:  17.0.2 
    typescript:  4.9.5 
```
</details>

**Comment by MBilalShafi** [comment]
If you need one or more rows pinned to the bottom, I guess you could use [row pinning](https://mui.com/x/react-data-grid/row-pinning/). Have you checked that already?

**Comment by Jaryt** [comment]
> P.S We recently https://github.com/mui/mui-x/pull/8921 editing on the pinned rows.

Oh sweet! The added support of row editing solves my problem. Thank you 🙏
