### ISSUE TITLE
[question] showing Popover on Cell stops editing at all

### ISSUE THREAD

**Issue by Kohei909Otsuka** [mui/mui-x#9278]
### Order ID or Support key 💳 (optional)

68257

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

https://mui.com/x/react-data-grid/components/#cell
https://codesandbox.io/s/lfs9ik?file=/demo.tsx

On example above,  I can't edit cell because of Popover.

I'm trying to render err msgs per Cell before submit DataGrid like this.

![全画面_2023_06_09_13_53](https://github.com/mui/mui-x/assets/11783802/7f208ce2-c2ca-40b2-8d24-e4df3b18c58e)

But with Popover, I can not edit the cells  at all, or move cell target by arrow keys.

How can I do "showing popover" and "cell editing" at the same time?

### Your environment 🌎

  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: Not Found
    npm: 9.6.7 - ~/develop/nitoel/tenant/supplier-frontend/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/core-downloads-tracker:  5.10.13
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.13 => 5.10.13
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/utils:  5.13.1
    @mui/x-data-grid:  6.6.0
    @mui/x-data-grid-premium: ^6.6.0 => 6.6.0
    @mui/x-data-grid-pro:  6.6.0
    @mui/x-license-pro:  6.6.0
    @types/react: 18.0.14 => 18.0.14
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4

**Comment by MBilalShafi** [comment]
Correct, in this demo, cell editing doesn't work properly and cell focus also gets disturbed when hovering over a cell.

Till we do a proper fix, could you have something like this for making editing usable? https://codesandbox.io/s/nifty-tdd-x3jd5l?file=/demo.tsx

**Comment by Kohei909Otsuka** [comment]
@MBilalShafi 


Thanks for your reply.

Your demo does not have all functionalities which we have without Popover, 
But OK I got it .

Thanks for your help.


Let me know when it fixed if possible.
