### ISSUE TITLE
How to show only default column in MUI v6 datagrid

### ISSUE THREAD

**Issue by pinak3748** [mui/mui-x#9289]
I have multiple column to show in a datagrid which but all of them can't fit into the screen so I want to show some column by default and other other but user can toggle them true through Column option field in **_toolbar: GridToolbar filters_**.

I am using react for so I even tried the return column approach where I had my columns in a usestate and I have a list of default column array so user I can use to filter out the columns but in this approach the the options in the column are the once which are already displaced so user do not get the option to toggle the hidden one.

The default column option should be like this but if I try to do it using my approach the column option is

![image](https://github.com/mui/mui-x/assets/59458280/43e33438-6b84-436f-9e3b-1092054c56ec)
![image](https://github.com/mui/mui-x/assets/59458280/405dfffd-58d1-49e0-afb4-29a66c305edc)

is their any default property in data grid for column where I can just set hide: true something so the the column will be hidden by default but the user can toggle it true in toolbar: GridToolbar, columns option. I was not able to find this in the [documentation](https://mui.com/x/react-data-grid/column-visibility/)

Here is the stackoverflow [link](https://stackoverflow.com/questions/76449400/how-to-show-only-default-column-in-mui-v6-datagrid)

**Comment by MBilalShafi** [comment]
I think you are looking for [this](https://mui.com/x/react-data-grid/column-visibility/#initialize-the-visible-columns), in this example the `initialState.columns.columnVisibilityModel` is used to initialize some columns to be hidden by default.

```tsx
<DataGrid
  initialState={{
    columns: {
      columnVisibilityModel: {
        blogDetection: false,
        // other columns that you want to initialize as hidden
        // Note: by default all of them are `visible`, you must add all those you want to hide in `columnVisibilityModel` as `false`
      }
    }
  }}
  {...otherProps}
/>
```

Updating the columns' state from the outside is not a good solution as it will cause the grid to unnecessarily re-render thus affecting the performance.
