### ISSUE TITLE
v6.7.0 DatePickers views prop causes component to ignore locale when year is omitted

### ISSUE THREAD

**Issue by sphinx9** [mui/mui-x#9291]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/stupefied-greider-jgltqt

Steps:
1. Select dates using the pickers
2. Observe bugged behaviour in first two fields

### Current behavior 😯

Leaving ['year'] out of the views prop causes the component to ignore locale specified using LocalizationProvider

### Expected behavior 🤔

Leaving ['year'] out of the views prop shouldn't cause the component to ignore locale specified using LocalizationProvider

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: Not Found
    npm: 9.6.1 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.11 => 11.11.1
    @emotion/styled: ^11.11 => 11.11.0
    @mui/base:  5.0.0-beta.4
    @mui/core-downloads-tracker:  5.13.4
    @mui/icons-material: ^5 => 5.11.16
    @mui/lab: ^5.0.0-alpha.124 => 5.0.0-alpha.133
    @mui/material: ^5.13 => 5.13.4
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid: ^6 => 6.7.0
    @mui/x-date-pickers: ^6 => 6.7.0
    @types/react:  18.2.11
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  5.1.3

```
</details>

**Comment by alexfauquette** [comment]
I don't get your point. I changed the locale to `'fr'` and all the fields moved to french

https://codesandbox.io/s/intelligent-gauss-vykjrt?file=/src/App.js

![image](https://github.com/mui/mui-x/assets/45398769/cc758b1e-1670-4482-ac21-ce50b301bb38)

What result would you expect for `views=['month', 'day']` ?

**Comment by sphinx9** [comment]
Hi, I'm not referring to the language that the text is written in. - in my locale, day and month should be represented as `DDo MMMM`, and in yours, after a quick Google, I believe it should be `DD MMMM`. 

So, for the dates you selected in your screenshot, for me they should be written as:
8th September
16th June

And for you, they should be written as:
8 Septembre
16 Juin

As shown in the codesandbox example, when the year is also included in `views`, the date is shown correctly. When the year is omitted, however, the representation of day and month seems to fall back to the default locale (`en-us`) instead of matching the locale specified in `LocalizationProvider`.

**Comment by alexfauquette** [comment]
But there is no locale format that does not show the year (at least in dayjs: https://day.js.org/docs/en/display/format#list-of-localized-formats)

So we can not automatically adapt the format to the locale. If you want a specific format, you need to customize it with `inputFormat='DDo MMMM'`

If you know a way to do that automatically it would be interesting but other than that, I don't think we can improve the default further

**Comment by sphinx9** [comment]
Okay, thank you. I will close this and re-open it if I can figure out something that could be proposed as a fix.
