### ISSUE TITLE
[TimePicker] minTime and maxTime props do not function if `disabled=false`

### ISSUE THREAD

**Issue by sphinx9** [mui/mui-x#9294]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-template-forked-52t642

Steps:
1. Interact with the clock icon on each component to show the time pickers

### Current behavior 😯

The first TimePicker correctly only allows selection of hours between 19 and 23, as per the props on the component
The second TimePicker does not exhibit the same behaviour, despite the only difference between the two components being that the second one has disabled=false

### Expected behavior 🤔

The first two TimePicker components in the live example should behave identically.

### Context 🔦

I'm using the disabled prop to conditionally enable / disable the component. While this bug exists, I cannot use the minTime or maxTime props, although it is worth noting that using skipDisabled and shouldDisableTime could function as a viable workaround, which seems to be unaffected by the bug and will remove the time options that should have been individually disabled.

Thank you

### Your environment 🌎

<details>
I used the template codesandbox but here's mine anyway:

System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: Not Found
    npm: 9.6.1 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.11 => 11.11.1
    @emotion/styled: ^11.11 => 11.11.0
    @mui/base:  5.0.0-beta.4
    @mui/core-downloads-tracker:  5.13.4
    @mui/icons-material: ^5 => 5.11.16
    @mui/lab: ^5.0.0-alpha.124 => 5.0.0-alpha.133
    @mui/material: ^5.13 => 5.13.4
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid: ^6 => 6.7.0
    @mui/x-date-pickers: 6.7 => 6.7.0
    @types/react:  18.2.11
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.9.5
</details>

**Comment by alexfauquette** [comment]
@LukasTy This diff seems to fix the bug. Is their something I'm missing about this line?

```diff
diff --git a/packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx b/packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx
index 7d52f4466..25418eb6d 100644
--- a/packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx
+++ b/packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx
@@ -186,7 +186,7 @@ export const MultiSectionDigitalClockSection = React.forwardRef(
               key={option.label}
               onClick={() => !readOnly && onChange(option.value)}
               selected={isSelected}
-              disabled={disabled ?? option.isDisabled?.(option.value)}
+              disabled={disabled || option.isDisabled?.(option.value)}
               disableRipple={readOnly}
               role="option"
               // aria-readonly is not supported here and does not have any effect
```

**Comment by LukasTy** [comment]
> @LukasTy This diff seems to fix the bug. Is there something I'm missing about this line? (The bug does not exist with a unique section)

Great observation! 👍 Yup, it seems to be the only issue in this case and your diff should do the trick in solving it. 👌
