### ISSUE TITLE
[DataGrid] DataGrid-Pro does not shrink to fit after resizing larger then smaller

### ISSUE THREAD

**Issue by ThomasGClarity** [mui/mui-x#9297]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Put a data-grid-pro on a page
2. Resize page larger so grid reactively grows
3.  then try to resize back smaller again and columns will not shrink to fit as expected.

(this worked prior to 6.x)

### Current behavior 😯

When using data-grid-pro the grid will grow correctly when the window is resized larger. 
But once grid is larger it will no longer be able to be resized smaller and have the grid shrink to fit.
 (as columns say same size and creates an overflow instead)
This worked prior to version 6.x

### Expected behavior 🤔

As you resize a window smaller the grid should shrink with it and be responsive. (as it did in older versions) and up to a point (min width of columns) not have an overflow/scroll.

### Context 🔦

Im trying to get a responsive datagrid. currently when someone tries shrink the screen there will be an overflow where it is not needed as it could shrink to fit. (this all worked in older version before 6.x)

### Your environment 🌎

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.110
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.41)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.2
    @mui/core-downloads-tracker:  5.13.2
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/material: ^5.13.2 => 5.13.2
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid:  6.7.0
    @mui/x-data-grid-pro: ^6.6.0 => 6.7.0
    @mui/x-date-pickers:  6.7.0
    @mui/x-date-pickers-pro: ^6.6.0 => 6.7.0
    @mui/x-license-pro:  6.6.0
    @types/react:  18.0.37
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.9.5

### Order ID or Support key 💳 (optional)

67285

**Comment by ThomasGClarity** [comment]
turns out it was occurring due to it being in a  "<Box sx={{ flexGrow: 1, p: 3 }}>"  all good now after removing that.

**Comment by gocreating** [comment]
Same issue here. Even when I removed the Box, the issue is still there.

**Comment by DarynHolmes** [comment]
> Same issue here. Even when I removed the Box, the issue is still there.

Try setting  `autoHeight` to true in the `DataGrid`.

**Comment by gocreating** [comment]
Thanks @DarynHolmes . I've set autoHeight to true and the issue has been resolved.

**Comment by dilipBadal** [comment]
Same issue here, even after setting the autoHeight to true.

**Comment by DarynHolmes** [comment]
> Same issue here, even after setting the autoHeight to true.

Can share an example where the issue is reproduced?

**Comment by oliviertassinari** [comment]
It could be about #11295.
