### ISSUE TITLE
[question] Anyway to set a row group default open on datagrid?

### ISSUE THREAD

**Issue by gffhammes** [mui/mui-x#9306]
### Order ID or Support key 💳 (optional)

67563

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### The problem in depth 🔍

I need to restore the state of the datagrid whenever the user returns to the page. Everything works just fine with the `exportState` and `restoreState` methods , but when the user has set a row groupping, when he returns to the page all row groups are default closed, even if the user has left some group open. I need to restore the open groups open too. Are there some way to do this? 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by gffhammes** [comment]
Hey guys, I passed the prop `defaultGroupingExpansionDepth={-1}` which keeps all groups open. While it is functional, it disrupts the user flow in my scenario. When users click on a row and are redirected to another page, upon returning to the datagrid page, all groups are open, unlike when they left the page.

I haven't been able to find a solution to "export" the currently open groups and restore them later. Can anyone assist me with this?

**Comment by romgrk** [comment]
I think we don't have a public way to do that. You could however use the following snippet to save the expanded state:

```ts
Object.values(apiRef.current.state.rows.tree).reduce((acc, node) => { acc[node.id] = Boolean(node.childrenExpanded); return acc }, {})
```

And use [`isGroupExpandedByDefault`](https://mui.com/x/api/data-grid/data-grid-pro/#props) to restore it.
Note that the value of `apiRef.current.state` is not part of our public API, and can change from one minor release to another.
