### ISSUE TITLE
[DataGrid] Getting error in "Download as excel"

### ISSUE THREAD

**Issue by nishantmvt** [mui/mui-x#9308]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

We have a app name accountify and we are using the Mui premium table on our app, but Download in excel is not working

Steps:
1. On our Accountify app we are using material ui premium tree data table when we click on Export button. 
2.When export dropdown opens click on the Download as excel.
3. After that we are getting below error

Uncaught (in promise) ChunkLoadError: Loading chunk 295 failed.
(missing: https://accountifyapps.com/js/295.js)

![image](https://github.com/mui/mui-x/assets/135702956/fd29bb2f-cf0a-4314-80f7-cddf79e080b9)

### Current behavior 😯

On click Download as excel option in material ui premium table we are getting below error in the screenshot.

![image](https://github.com/mui/mui-x/assets/135702956/fb3ad246-b6c8-4441-9b0d-3a02f2e12a14)

### Expected behavior 🤔

It should download the data in excel format. Our MUI X data grid version   "@mui/x-data-grid-premium": "^5.17.20",
![image](https://github.com/mui/mui-x/assets/135702956/5107d88f-68fb-47ac-93ad-fdc53f7ae6e3)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by nishantmvt** [comment]
anyone available for this issue, it's been 8 hours.

**Comment by nishantmvt** [comment]
Hi material ui team thanks for reverting back. To let you guys test the ongoing material ui issue in our app. I have sent the  private information by filling submit a request form.

Subject -:   Login credientials for the staging environment for our ongoing issue in MATERIAL UI  Download as excel.

Thanks

**Comment by nishantmvt** [comment]
I need to solve this today guys, please be quick as soon as possible.

Thanks

**Comment by joserodolfofreitas** [comment]
Hi @nishantmvt, 

Thank you for sharing access to your software. I appreciate getting the chance to see the use cases in action.
But as I mentioned on the private channel, we do need a live reproduction case to try diving into this issue.

As an extra help for debugging the issue, "ChunkLoadError" is thrown when the script file for the chunk cannot be fetched and executed. In your case, it seems like the problem is with `exceljs` library. 

Please check that the `exceljs` is properly installed. Or maybe, if you were using it outside of the Data Grid, there might be some conflicts on the versions.
Also, if you have customizations on your webpack configuration, you may want to check if there's any issue preventing exceljs from being loaded.

If you need a closer starting point for a live reproduction case you can use:
https://codesandbox.io/s/export-excel-with-tree-data-w3y4f9

**Comment by nishantmvt** [comment]
Hi joserodolfofreitas
Thanks for reverting me back. I am not using excel js anywhere, I installed it because when I saw this issue. I thought may be it's because the package is not installed that's why this issue arise, but the error didn't disappear even after installing the excel js version 4.3.0.

Thanks

**Comment by nishantmvt** [comment]
"dependencies": {
        "@date-io/date-fns": "^2.15.0",
        "@emotion/react": "^11.10.5",
        "@emotion/styled": "^11.10.5",
        "@highcharts/map-collection": "^1.1.3",
        "@mui/icons-material": "^5.11.0",
        "@mui/lab": "^5.0.0-alpha.115",
        "@mui/material": "^5.11.4",
        "@mui/styled-engine-sc": "^5.11.0",
        "@mui/styles": "^5.11.2",
        "@mui/x-data-grid": "^5.17.18",
        "@mui/x-data-grid-premium": "^5.17.26",
        "@mui/x-date-pickers": "^5.0.0",
        "anychart-react": "^1.4.1",
        "bootstrap-daterangepicker": "^3.1.0",
        "chart.js": "^2.9.4",
        "clsx": "^1.1.1",
        "date-fns": "^2.29.3",
        "dayjs": "^1.11.7",
        "exceljs": "^4.3.0",
        "formik": "^2.2.6",
        "highcharts": "^9.2.2",
        "highcharts-react-official": "^3.0.0",
        "jspdf": "^1.3.5",
        "moment": "^2.29.3",
        "mui-datatables": "^4.3.0",
        "multiselect-react-dropdown": "^1.6.11",
        "notistack": "^2.0.8",
        "plaid": "^8.5.1",
        "proj4": "^2.7.2",
        "react-bootstrap": "^1.5.2",
        "react-bootstrap-daterangepicker": "^7.0.0",
        "react-chartjs-2": "^2.11.1",
        "react-circular-progressbar": "^2.0.4",
        "react-dom-factories": "^1.0.2",
        "react-dotenv": "^0.1.3",
        "react-dropzone": "^12.0.4",
        "react-dropzone-uploader": "^2.11.0",
        "react-fontawesome": "^1.7.1",
        "react-hook-form": "^7.0.5",
        "react-jsx-highcharts": "^4.2.1",
        "react-loading-skeleton": "^2.2.0",
        "react-middleware-router": "^0.1.4",
        "react-multi-select-component": "^4.0.1",
        "react-plaid-link": "^3.1.0",
        "react-redux": "^7.2.3",
        "react-responsive": "^8.2.0",
        "react-router-bootstrap": "^0.25.0",
        "react-router-dom": "^5.2.0",
        "react-select": "^4.3.1",
        "react-select-2": "^2.0.11",
        "react-selectize": "^3.0.1",
        "react-sweet-progress": "^1.1.2",
        "react-top-loading-bar": "^2.0.1",
        "react-transition-group": "^1.2.1",
        "redux-devtools-extension": "^2.13.9",
        "redux-thunk": "^2.3.0",
        "rsuite": "^4.9.3",
        "styled-components": "^5.3.6",
        "validator": "^13.5.2",
        "yup": "^0.32.9"
    },

**Comment by nishantmvt** [comment]
Hi @joserodolfofreitas 

The excel file is starting downloading now, the issue is that  when we click on download as excel  the which look for the excel js file  is    /js/node_modules_exceljs_dist_exceljs_min_js.js   but our actual path which we set in our app is  public/js/node_modules_exceljs_dist_exceljs_min_js.js  that's why it was giving this error. We have resolved this for now.

Moreover,  we got a another situation here the  tree data is not loading properly  I have attached the file please check.
[Accountify (1).xlsx](https://github.com/mui/mui-x/files/11766543/Accountify.1.xlsx)

**Comment by nishantmvt** [comment]
Issue resolved, Thank you material ui team for your time. I will again contact you if I got any issue.

**Comment by ykrilek-agi** [comment]
> Issue resolved, Thank you material ui team for your time. I will again contact you if I got any issue.

How did you manage to solve the issue in the end?

**Comment by nishantmvt** [comment]
Hi @ykrilek-agi

**Comment by chezkibotwinick** [comment]
Hi @nishantmvt, I'm experiencing the same issue. Can you please share how you managed to solve the issue?

**Comment by michelengelen** [comment]
@joserodolfofreitas do you happen to know how this issue got resolved for @nishantmvt ? It seems we do have several users that experience the same problem.

**Comment by mvtdev1050** [comment]
Hi all

As you see in the above screenshot of mine. Material ui tries to find the 295.js file inside inside root directory /js/295.js folder, as the directory is missing so I created directory name js and inside js created a 295.js file, then i create build in production which resolved the above error.

**Comment by mvtdev1050** [comment]
@lisaWriteJava  In my main root directory.
