### ISSUE TITLE
[question] premium plan user trying to do multi level grouping on the same column

### ISSUE THREAD

**Issue by elizabethtrambulo** [mui/mui-x#9309]
### Order ID or Support key 💳 (optional)

68277

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I want to be able to show a hierarchy of people in an organization using datagrid.  

The organizations themselves can be nested. So an example I could have Military -> Navy -> Navy Seals.

Currently, I'm only seeing them group by the parent organization, which is what I've set it to. How do I achieve multiple nested levels using the same column?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by elizabethtrambulo** [comment]
Hm, I feel like this might be different. The model I'm using allows for
nested groups. So for example,

Commercial

Target
Walmart

Automotive

Military

Army
Navy

Seals

Marines

Civilian
Other

My schema is OrganizationId, Name, ParentOrganizationId.

**Comment by romgrk** [comment]
Maybe you're looking for [tree data](https://mui.com/x/react-data-grid/tree-data/) instead of grouping?

**Comment by romgrk** [comment]
IIRC path should include the row's own id, e.g. `['military', 'air force', 'division 1']`

**Comment by elizabethtrambulo** [comment]
Got it. That's helpful. If I have an action column, how do I get it to not
show on the aggregate row?

**Comment by romgrk** [comment]
I'm not exactly sure, but you could maybe try defining the behavior with [`renderCell`](https://mui.com/x/api/data-grid/grid-col-def/#properties).

**Comment by elizabethtrambulo** [comment]
I get this error when trying to update rows in a grid using the tree data
format.

TypeError: Cannot read properties of undefined (reading 'id')
    at getRowId (organizations.js:204:1)
    at getRowIdFromRowModel (gridRowsUtils.js:31:1)
    at useGridRows.js:122:1
    at Array.forEach (<anonymous>)
    at useGridRows.js:121:1
    at Proxy.updateRows (useGridApiMethod.js:14:1)
    at useGridCellEditing.js:327:1

I suspect it has something to do with the grouped rows. I have this as part
of my grid     getRowId={(row) => row.id}

**Comment by romgrk** [comment]
Is it possible one of your rows is undefined? Note that we can't provide assistance unless you have a live example. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) is a good starting point. Also note that if your row's id is `.id`, you don't need to define `getRowId`.

**Comment by elizabethtrambulo** [comment]
I updated the sandbox with my code. Not sure why the rows aren't rendering.
here's a screenshot of the console log. You'll see the ids are there for
all the rows after the mutation and then immediately when the grid tries to
update, it gets an error.

[image: image.png]

**Comment by romgrk** [comment]
Which sandbox? If you make modifications, you need to share the updated link. Your github message also doesn't include the screenshot, it may be preferable to use github directly, mail replies don't integrate well.

**Comment by elizabethtrambulo** [comment]
Hopefully this works.
![Screenshot 2023-06-20 121257](https://github.com/mui/mui-x/assets/133714249/22f0b3cd-ff0b-423b-8d0d-7a5b5949c717)


https://codesandbox.io/s/modest-frog-qty3v4?file=/index.tsx

**Comment by romgrk** [comment]
The live example you have provided does not work. Make sure to provide a live example where we can reproduce the issue you're experiencing.

![image](https://github.com/mui/mui-x/assets/1423607/2d6be01c-1f88-4d92-be1b-3c97784e17c1)

**Comment by elizabethtrambulo** [comment]
Mine doesn't look like that at all

![image](https://github.com/mui/mui-x/assets/133714249/895a3562-85fc-4f35-84c8-f80ce41f8306)

**Comment by romgrk** [comment]
Where is the code for your `processRowUpdate` in the codesandbox coming from? Did you write it yourself?

From what I can see in our docs, it's supposed to resolve to the updated row: https://mui.com/x/react-data-grid/editing/#server-side-validation

**Comment by elizabethtrambulo** [comment]
That resolved my issue. Thanks.
