### ISSUE TITLE
[docs] Update Date Pickers usage with Title Case

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#9318]
Address https://github.com/mui/mui-x/pull/8261#discussion_r1222909711

**Comment by LukasTy** [comment]
@richbustos, could you clarify if we are on the right path with this one?
We currently have quite a few places, where spelling is the following:
`Date and Time pickers`
The proposal is to unify/align usages to be
`Date and Time Pickers`
Is it the correct approach? 🤔

**Comment by richbustos** [comment]
@LukasTy 
> @richbustos, could you clarify if we are on the right path with this one? We currently have quite a few places, where spelling is the following: `Date and Time pickers` The proposal is to unify/align usages to be `Date and Time Pickers` Is it the correct approach? 🤔

Definitely `Date and Time Pickers`! 

"Time Pickers" is the full name of the feature so Title Case is appropriate. Will work on this!

**Comment by richbustos** [comment]
Fix: https://github.com/mui/mui-x/pull/9680
