### ISSUE TITLE
CSV export adds duplicate double quote character (")

### ISSUE THREAD

**Issue by doylio** [mui/mui-x#9322]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: 
https://codesandbox.io/s/gracious-cookies-j5nv5x?file=/src/App.js

Steps:
1. Click Export CSV
2. Open the CSV file in Excel (Numbers seems to remove the second quote) or inspect the CSV directly

### Current behavior 😯

Anywhere a `"` character exists, it has been doubled.  In the example above, `4"` has become `4""` and `There is a "quote" in here` becomes `There is a ""quote"" in here`

### Expected behavior 🤔

The CSV should contain exactly the same text from the row data

### Context 🔦

I am using DataGrid to display measurements, including inch measurements (ie `4"`, `8 1/2"`) and allow customers to export the data

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

System:
    OS: macOS 13.0
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.1
  npmPackages:
    @emotion/react: 11.11.0 => 11.11.0 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-alpha.124 
    @mui/core-downloads-tracker:  5.13.0 
    @mui/lab: 5.0.0-alpha.125 => 5.0.0-alpha.125 
    @mui/material: 5.13.0 => 5.13.0 
    @mui/private-theming:  5.12.3 
    @mui/styled-engine:  5.12.3 
    @mui/system:  5.12.3 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.3 
    @mui/x-data-grid:  5.17.21 
    @mui/x-data-grid-pro: 5.17.21 => 5.17.21 
    @mui/x-date-pickers:  5.0.19 
    @mui/x-date-pickers-pro: 5.0.19 => 5.0.19 
    @mui/x-license-pro:  5.17.12 
    @types/react: 18.2.8 => 18.2.8 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.4 => 5.0.4 
</details>

### Order ID or Support key 💳 (optional)

Order #58979

**Comment by david0673** [comment]
I'm running into the same issue, where for the following data-grid:
<img width="203" alt="Screenshot 2023-06-13 at 2 52 32 PM" src="https://github.com/mui/mui-x/assets/1468812/301eb3ce-069f-4f61-81ef-907d9f186bc3">

It is exported as
```csv
name,value
First,4""
```

But I'd expect it to be exported with escaping, i.e.,
```csv
name,value
First,"4"""
```

Here is [my code sandbox](https://codesandbox.io/s/nervous-microservice-9vplxh?file=/src/App.js)

**Comment by doylio** [comment]
If there's anything we can do to help, please let us know.  We've got customers complaining about this issue :P

**Comment by alexfauquette** [comment]
I dontt know the state of the data grid backlog, but the easiest to put the fix on top of their priority list is to open a PR with the fix and a test case in `export.DataGrid.test.tsx` 

Maybe mention Math' in the PR description such that someone in the data grid team gets notified by your PR
