### ISSUE TITLE
Locale "pt-BR" by DayJs. The first letter is not capitalized

### ISSUE THREAD

**Issue by Tiagofsant** [mui/mui-x#9323]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

hello,

I am using 'dayjs/locale/pt-br' to return the months and years in the datePicker, but the first letter does not stay capitalized. It appears like this: "junho 2023" instead of "Junho 2023", as shown in the image below. Please help.

![image](https://github.com/mui/mui-x/assets/79919984/bc90979f-039a-4ca0-b82f-4d80ed8caefc)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Hello @Tiagofsant 
I see that you have already opened an issue https://github.com/iamkun/dayjs/issues/2333 in dayjs repo.
There is nothing we can do, we just use the locale that dayjs provides and in this case, it's lower case, everything is.
The [`weekdaysMin`](https://github.com/iamkun/dayjs/blob/dev/src/locale/pt-br.js#L8) is also translated in quite a strange way and produces an interesting result... 🤷 
![Screenshot 2023-06-14 at 09 13 30](https://github.com/mui/mui-x/assets/4941090/2969471f-6e8b-4370-8ccc-ced9a1095bed)
