### ISSUE TITLE
[docs] Demo LazyLoadingGrid crashes

### ISSUE THREAD

**Issue by samR-auxout** [mui/mui-x#9325]
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LazyLoadingGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/row-updates/
2. ??
3. demo *LazyLoadingGrid* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.7.0  |
| Netlify deploy | https://6482fde34837780008f5da8a--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43 |

**Comment by MBilalShafi** [comment]
Hey @samR-auxout, for me it doesn't crash. Could you provide the reproduction steps or perhaps a video showing the crash you mentioned?

**Comment by oliviertassinari** [comment]
Duplicate of #10047
