### ISSUE TITLE
[pickers] Time field sections incorrectly selected after selecting date and having no time renderers

### ISSUE THREAD

**Issue by dcorb** [mui/mui-x#9326]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When using
```
<DesktopDateTimePicker
     views={["year", "month", "day"]}

```        
(aka, not showing time picker), then there is no point on showing an "OK" button, because clicking on a date already will close the popup

**Comment by flaviendelangle** [comment]
Hi,

Why are you using the `DateTimePicker` instead of the `DatePicker` when all the views are date views?

**Comment by dcorb** [comment]
Hi Flavien, We need the time input too. But users prefer to input the time with keyboard

**Comment by LukasTy** [comment]
Using `views` like that technically destroys your mentioned behavior.
If it is no view experience for time picking that you are looking for, consider adding the following prop:
```tsx
viewRenderers={{
  hours: null,
  minutes: null,
  seconds: null
}}
```

**Comment by dcorb** [comment]
Thank you @LukasTy  . That is exactly what I needed it.

There is a small difference with 6.7.0 (before the HH was auto-selected after popup was closed), but in the moment you press arrow up ^  , it works the same way than before. It's just a tiny detail.
![image](https://github.com/mui/mui-x/assets/881333/c99473d2-386e-4f7f-8d11-d1fd721e201b)

You can close this ticket from my point of view.

**Comment by LukasTy** [comment]
> There is a small difference with 6.7.0 (before the HH was auto-selected after popup was closed), but in the moment you press arrow up ^ , it works the same way than before. It's just a tiny detail.

Thank you for spotting this difference, I can confirm that this looks like a regression on our end and should be addressed. 👍

**Comment by flaviendelangle** [comment]
We might be able to use the new `fieldRef` now instead of controlling the selection
Don't know if it helps
