### ISSUE TITLE
TimeField minutesStep up/down arrow keys

### ISSUE THREAD

**Issue by EitanElbaz** [mui/mui-x#9331]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://stackblitz.com/edit/react-9senwc?file=demo.tsx (uses mui-x-datepickers 6.7.0)

The blitzstack example sets the minutesStep prop to 30.

Steps:
1. Press up/down on your arrow keys

### Current behavior 😯

An error (red border) is currently displayed when a minute not conforming to the `minutesStep` prop value are set.

### Expected behavior 🤔

When I press the up/down arrow keys on my keyboard I would expect it to use the `minutesStep` prop value to jump to the next value.

For example, if I set `minutesStep` to 30, I would expect the up button to flick between `00` and `30` minutes.

If it was set to 5, I would expect it to go up in increments of 5 and loop back to `00` at the end.

I've seen these issues https://github.com/mui/mui-x/issues/8824 (and the issue linked within it) and I don't believe it has been resolved, unless it has and just hasn't been released yet in which case I apologise 😬 .

### Context 🔦

I want to limit users to only entering `00` or `30` minutes.

### Your environment 🌎

See stackblitz link

**Comment by alexfauquette** [comment]
@EitanElbaz Thanks for your nice issue message, it simplified the investigation to link to relate issues.

The bug that get fix is not exactly what you are asking for. Those issues are talking about the clock. Here is a demo where as you can see you can drop the minute clock handler only on valid minutes
https://codesandbox.io/s/unruffled-davinci-jj96dt?file=/demo.tsx

But I agree taking into account the `mintesStep` would be interesting

@LukasTy do you have an opinion about how it should behave since we have two distinct step providers (the `minutesStep` for clock and `timeStep`/`timeSteps` for the digital clock?)

**Comment by EitanElbaz** [comment]
Hi @alexfauquette thank you for the speedy reply.

I'm not sure if anyone has suggested it before, but it would be very nice to be able to specify specific allowed hours/minutes/seconds in the TimeField and for it to cycle through those allowed hours/minutes/seconds when using arrow keys.

Happy to make a feature request in a separate issue though.

**Comment by alexfauquette** [comment]
>  we have two distinct step providers (the minutesStep for clock and timeStep/timeSteps for the digital clock?)

My bad, I just realised the `timeStep`/`timeSteps` are only for the digital clock, not the pickers components.

I opened a PR for the `minutesStep` behavior. Yes, allowing to add hours and seconds steps might benefits to be in a dedicated issue

**Comment by LukasTy** [comment]
> I've seen these issues #8824 (and the issue linked within it) and I don't believe it has been resolved, unless it has and just hasn't been released yet in which case I apologise 😬 .

The mentioned issue fixed the issue on TimeField. Previously it would not trigger an error state, when an invalid minute was selected. I've tried replicating this issue on StackBlitz, but it seems bugged and does not allow any older package version (6.3.0 was still bugged) to be installed.

> Those issues are talking about the clock. 

As mentioned ☝️, the referenced issue has changed the TimeField validation behavior to be correct and consistent. 😉 The clock did already work as expected before that.

> LukasTy do you have an opinion about how it should behave since we have two distinct step providers (the `minutesStep` for clock and `timeStep`/`timeSteps` for the digital clock?)

This is a really good question and one that might be relevant for v7.
Maybe we should deprecate the `minutesStep` in favor of using `timeSteps` everywhere consistently? 🤔 
cc @flaviendelangle
