### ISSUE TITLE
How to style the quick filters input, filters and density buttons on DataGrid?

### ISSUE THREAD

**Issue by john1625b** [mui/mui-x#9353]
### Order ID or Support key 💳 (optional)

61801

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍
![Screenshot 2023-06-16 at 12 38 53 AM](https://github.com/mui/mui-x/assets/17265085/a33e27f8-f925-4c7f-9306-e64fc00e0381)

I need to style the quick filter search, the filter button and the density button to look like the above.

https://mui.com/x/api/data-grid/data-grid/#css

I've looked through the CSS classes and couldn't find classes that seem like they would fit like "-quickFilterInput" or "-filtersButton". 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Firefox: 106.0.5
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.4 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/joy: ^5.0.0-alpha.84 => 5.0.0-alpha.84 
    @mui/material: ^5.13.5 => 5.13.5 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.5 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-data-grid: ^6.7.0 => 6.7.0 
    @mui/x-data-grid-pro: ^6.7.0 => 6.7.0 
    @mui/x-license-pro:  6.6.0 
    @types/react: ^18.0.37 => 18.2.12 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.0.2 => 5.1.3 
</details>

**Comment by alexfauquette** [comment]
What about using `.MuiDataGrid-toolbarContainer button` and `.MuiDataGrid-toolbarContainer input` to customize the buttons and the input in the toolbar?

**Comment by john1625b** [comment]
@alexfauquette Thank you! exactly what I needed. 

As a quick side question: when I click on the quick filter input to focus, a blue underline on the bottom border appears. How can I make it so that the whole border (top, bottom, sides) get coloured blue?

Also how does one position the quick filter to be flush to the left like in my screenshot? Is the only way hacky css or can I use something more convenient like a prop?

Thanks again.
