### ISSUE TITLE
[DataGrid] DataGrid infinitely increases horizontally with flex set in any one columns and small screen sizes.

### ISSUE THREAD

**Issue by Luv-m** [mui/mui-x#9362]
Exactly similar to the following issue (I am on v6.8.0) -

 I've run into a related issue with the upgrade to v6 (6.2.0) - the horizontal scrollbar appears while scrolling the list. I forked a demo sandbox here to illustrate. 
https://codesandbox.io/s/sparkling-waterfall-3sdhkk?file=/demo.tsx 
Only seems to happen when 

- border on `.MuiDataGrid-main`
- at least 1 column is has `flex: 1`

Also if you set the Box to `display: 'flex'` then the whole grid slowly grows horizontally, as shown in #8447 which is trippy.

_Originally posted by @lroos in https://github.com/mui/mui-x/issues/8737#issuecomment-1534847935_

**Comment by cherniavskii** [comment]
Hey @Luv-m 
I cannot reproduce the issue with this sandbox:

https://github.com/mui/mui-x/assets/13808724/c9465259-4293-49fd-b7e1-4408268935cf

Am I missing something?

**Comment by Luv-m** [comment]
Hey @cherniavskii :) , 

The issue might be in using `experimentalFeatures={{columnGrouping: true}}`. Sorry for not providing the entire information at the first go.

I am not able to reproduce the issue on codesandbox, but here is a video of what I am seeing. Is there any way that you know of to fix this issue? 

Here is the config I am using for DataGrid - 

```
 <DataGrid
      experimentalFeatures={{columnGrouping: true, ...experimentalFeatures}}
      classes={{
        columnHeaderTitleContainer: styles.columnHeaderTitleContainer,
        columnHeader: styles.columnHeader,
        ...classes,
      }}
      rows={rows}
      columns={columns}
      autoHeight
    />
```

https://github.com/mui/mui-x/assets/103112654/85a373d1-77ff-4d34-88dd-7eec1aca69a1

**Comment by cherniavskii** [comment]
Could you create a sandbox based on your setup? Unfortunately, the video is not enough for investigation.
Also, I would be interested to see the styles applied to the headers.

**Comment by Luv-m** [comment]
Hello @cherniavskii . Sorry for the false alarm. 
Turns out, you were correct. It was one of the styling I was doing indeed. 

I was giving margin to one of my column header groups. Turns out that when DataGrid tries to ender it, it sees that the calculation is off by 4px (the margin I provided). So it expanded. And this keeps happening to keep increasing the size horizontally.
