### ISSUE TITLE
LocalizationProvider DateAdapter from @tarzui/date-fns-be is not working

### ISSUE THREAD

**Issue by eikqzx** [mui/mui-x#9387]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Examples 🌈

I use DateAdapter @tarzui/date-fns-be before but is not working now
![image](https://github.com/mui/mui-x/assets/55727960/60335a2f-f540-4398-966e-22f2529c19fc)

**Comment by flaviendelangle** [comment]
Hi,

If the adapter you are using throws this error, it is outdated and cannot work with the latest version of our pickers.

I recommend against using third-party adapters, which will likely break on future releases.
If this adapter has some specificity (like the support of a specific calendar system), we can work to add it to our repository and make sure it is kept up to date to support future features.
