### ISSUE TITLE
[pickers] Time selection in DateTimePicker only on second click

### ISSUE THREAD

**Issue by pkuenemann** [mui/mui-x#9389]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-date-pickers/

Steps:
1. Go to the overview of that side and entder 06/19/2023 10:00 AM in the DateTimePicker
2. Klick on the picker symbol, move the mouse over the hour column, scroll upward and click on 05
3. The Hour-column scroll back to 10 without selecting the 05
4. Scroll upword again and click on 05 again. Now the change is taken.

### Current behavior 😯

see above.

### Expected behavior 🤔

The change should be accepted by the first click already.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Thank you for reporting this issue!. 🙏 
I can confirm that the issue indeed exists and seems annoying.
Looking for a solution.
