### ISSUE TITLE
Webpack module parse failed

### ISSUE THREAD

**Issue by ivan-po-mars** [mui/mui-x#9391]
We are getting the webpack module parse failed (Unexpected token) issue. What loader do we have to use?
![Screen Shot 2023-06-19 at 14 40 56](https://github.com/mui/mui-x/assets/55884410/abba02e4-67db-4880-a90f-6e4cbe8ea207)
![Screen Shot 2023-06-19 at 14 42 04](https://github.com/mui/mui-x/assets/55884410/12c5dd95-2ac1-428a-8dd4-0c52e2a757ca)
![Screen Shot 2023-06-19 at 14 50 22](https://github.com/mui/mui-x/assets/55884410/9198cf04-ae73-4ef6-a5c3-571d8b722beb)
![Screen Shot 2023-06-19 at 14 50 32](https://github.com/mui/mui-x/assets/55884410/fb7b7246-2f01-421b-9633-7df2d0bd4ab5)

**Comment by LukasTy** [comment]
Have you tried using https://www.npmjs.com/package/@babel/plugin-transform-spread ?
The `rest-spread` plugin does seem very specific. 🤔
