### ISSUE TITLE
[question] Event hook for Row Grouping Expand/Collapse?

### ISSUE THREAD

**Issue by snekse** [mui/mui-x#9392]
### Order ID or Support key 💳 (optional)

68733

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

As an overview, when loading our initial data, pulling everything for every row is just far too much data for use to pull in.  So our plan is to fetch additional detail for our data when a grouping is expended. 

Using the demo data as an example, we might pull just Movie Title, Director, and Company information down to begin with, grouping by `['company','director'].  Only when a user clicks on the `Director` row to expand it would we fetch the Gross $ and other data for the titles by that  Company + Director. 

**Question**
Is there an event or other signal we can use to know when a user has expanded or collapsed a row grouping?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 12.6.6
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Firefox: 114.0.1
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.4 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/material: ^5.13.4 => 5.13.4 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.2 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-data-grid: ^6.6.0 => 6.7.0 
    @mui/x-data-grid-premium: ^6.7.0 => 6.7.0 
    @mui/x-data-grid-pro: ^6.6.0 => 6.7.0 
    @mui/x-date-pickers: ^6.6.0 => 6.6.0 
    @mui/x-date-pickers-pro: ^6.6.0 => 6.6.0 
    @mui/x-license-pro: ^6.6.0 => 6.6.0 
    @types/react: 18.0.28 => 18.0.28 
    react: 18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ~5.0.2 => 5.0.4 
```
</details>

**Comment by romgrk** [comment]
You could redefine the `.renderCell` of the `groupingColDef` and catch the click events: https://mui.com/x/react-data-grid/row-grouping/#customize-grouping-cell-indent
This example is for tree-data (and not row-grouping) but shows a similar pattern: https://mui.com/x/react-data-grid/tree-data/#custom-grouping-column

**Comment by snekse** [comment]
@romgrk It will work in a pinch if there is no other option.  I was hoping to enable the row grouping to expand on row click like your [recipe](https://mui.com/x/react-data-grid/recipes-row-grouping/).  Maybe it's better if I just control the expansion myself with `setRowChildrenExpansion`?  

I don't think either of these are ideal - it would be great if there was an event emitted. 

Is there anything I should be aware of that might prevent calling `setRowChildrenExpansion` inside a `rowClick` handler from working properly?  I'm thinking that I *also* need to redefine the `renderCell` because if a user click the ExpandMore icon, then the `rowClick` event is never fired.

**Comment by romgrk** [comment]
@MBilalShafi you've been working on lazy-loading, maybe you have more context to add here?

@snekse We are working on proper lazy-loading, but for now all we have is work-arounds, as far as I know. You'll indeed need to control the behavior programmatically with `setRowChildrenExpansion`.

**Comment by romgrk** [comment]
You could do it more easily by just re-implementing the icon button slot. Here again, we only have work arounds until we do lazy-loading properly:

```ts
const slots = {
  baseIconButton: function Component(...) { ... },
}
<DataGridPremium
  slots={slots}
/>
```

https://github.com/mui/mui-x/blob/168ba36ba6fdd2e1b73f126a383267749c2f8c93/packages/grid/x-data-grid-pro/src/components/GridTreeDataGroupingCell.tsx#L66-L78

**Comment by snekse** [comment]
Thanks for the guidance.  I was able to fix the expand button behavior by _just_ overriding the `slotProps` 

```
slotProps={{
  baseIconButton: {
    onClick: () => {
      return false; // let the rowClick handler deal with the click
    },
  },
``` 

I think I got what I needed for this issue.  I can now intercept the interactions with the grouping rows (and button) to trigger a hook to enrich the existing data.  

I have some other questions, but I will open a different issue for those as needed.

**Comment by romgrk** [comment]
Yeah that's a better way to do it. You can close this issue if you have no more questions.

Linked discussion on lazy-loading: #9114

**Comment by snekse** [comment]
Yeah, at this point I am thoroughly confused.  I created a super simple component called `Expander` and tried to override the config to use my component instead.  The screen renders with a blank icon, the dom has `<expander></expander>` in it, but the breakpoint I put in my component is never hit.  I don't understand how I can intercept a click on the row grouping icon with these slot props without impacting everything else.

```
slots={{
  treeDataExpandIcon: 'Expander',
}}
slotProps={{
  treeDataExpandIcon: {
    dataFooBar: 'Do we have this prop?',
  },
}}
```

**Comment by romgrk** [comment]
In that case you may need to fork the `GridTreeDataGroupingCell` in full. If you have a link to a live codesandbox with what you have I may be able to assist more.

**Comment by MBilalShafi** [comment]
@romgrk Not sure how I missed your mention. 😕 

@snekse I'm a bit late to the party but I think you can use the grid event `rowExpansionChange` to react to the expansion change the way you want. I updated your codesandbox utilizing the mentioned event to achieve the desired behavior. Here's the updated version: https://codesandbox.io/s/mui-datagrid-row-group-events-forked-2rtwcd?file=/demo.js

Let me know if it addresses your concerns. Thanks!

**Side note:** The event `rowExpansionChange` was previously for internal use that is why it was not documented, but we recently decided to make it public to let the users handle more of the use cases similar to yours.
You can track this update [here](https://github.com/mui/mui-x/pull/9611).
