### ISSUE TITLE
DataGrid pro print export does not export cell background colors in production build

### ISSUE THREAD

**Issue by blasic** [mui/mui-x#9398]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example with a production build https://blasic.github.io/

1. Click export 
2. Click print 
3. In print settings enable "print backgrounds"

Minimal repo with source code to reproduce the issue: https://github.com/blasic/datagridbugdemo

### Current behavior 😯

PDF gets generated without background colors. Even if print settings allow background graphics.

In the development environment everything works as expected. As soon as i create a production build no backgrounds get exported. 

Seems to affect chrome. Safari works, did not test firefox.

### Expected behavior 🤔

Shoud produce print / pdf with background colors

### Context 🔦

Client wants color coding on some cells in the grid. They also want to print the data with color coded background colors.

### Your environment 🌎

  System:
    OS: macOS 13.4
  Binaries:
    Node: 16.20.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.3.0 => 11.11.1 
    @emotion/styled: ^11.3.0 => 11.11.0 
    @mui/base:  5.0.0-beta.4 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material: 5.11.16 => 5.11.16 
    @mui/material: 5.13.5 => 5.13.5 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.5 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-data-grid:  6.8.0 
    @mui/x-data-grid-pro: 6.8.0 => 6.8.0 
    @mui/x-date-pickers:  6.8.0 
    @mui/x-date-pickers-pro: 6.8.0 => 6.8.0 
    @mui/x-license-pro:  6.6.0 
    @types/react:  17.0.62 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.8.4 => 4.9.5 

### Order ID or Support key 💳 (optional)

68951

**Comment by romgrk** [comment]
Using Chrome 114.0.5735.110 on linux, I can't reproduce the issue. Maybe this is chrome-on-macOS specific? Can you reproduce the issue outside macOS?

@mui/xgrid Could someone on macOS confirm this bug?

**Comment by cherniavskii** [comment]
@blasic could you check the print settings? There's the "Background graphics" option:

<img width="1008" src="https://github.com/mui/mui-x/assets/13808724/19d296ea-220c-4055-b847-90387a212711">

**Comment by cherniavskii** [comment]
@blasic Thanks! I can reproduce the issue
