### ISSUE TITLE
Filter and Column Flyout use the same object

### ISSUE THREAD

**Issue by splitloose-earth** [mui/mui-x#9399]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We are trying to have filters flyout display from the filter button, and the column selection flyout display for the column button.

Currently the filter and column selection flyout are leveraging the same object.

<img width="1268" alt="Screenshot 2023-06-20 at 9 36 58 AM" src="https://github.com/mui/mui-x/assets/32595845/5c01f198-fa03-4b3c-ab21-00aed8bdd7d6">
<img width="1216" alt="Screenshot 2023-06-20 at 9 37 28 AM" src="https://github.com/mui/mui-x/assets/32595845/3b4fc919-ec98-45f9-a76e-2dea8ce4d03f">
<img width="1224" alt="Screenshot 2023-06-20 at 9 37 35 AM" src="https://github.com/mui/mui-x/assets/32595845/7a2e9be6-fa1e-49c8-b3fd-d45ce565cedd">

### Motivation 🔦

Trying to keep the users from moving across the data grid to make selections when the button do so is on the opposite site.

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) _may_ be a good starting point. Thank you!

**Comment by stem-ui** [comment]
Here is an example which is a slight variation of the [demo code](https://mui.com/x/react-data-grid/filtering/customization/#customize-the-filter-panel-position) from the MUI docs describing how to customize the position of the filter panel:

https://codesandbox.io/s/async-wildflower-svjynd?file=/demo.tsx

The filterPanel and the columnsPanel components use the same underlying "panel" slot and cannot be independently re-positioned.

**Comment by romgrk** [comment]
@m4theushw Do you know if there is any way to work around this?
