### ISSUE TITLE
MobileDatePicker with custom day element doesn't fire 'onAccept'

### ISSUE THREAD

**Issue by subharb** [mui/mui-x#9401]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Import a MobileDatePicker
2. Add slot to customize the day PickersDay
3. 'onAccept' doesn't execute
https://codesandbox.io/s/mui-5-forked-mhmccl

### Current behavior 😯

The callback added in 'onAccept' is not executed.

### Expected behavior 🤔

The callback should be executed

### Context 🔦

I would like to get the date that was selected by the user when they clicked the "Accept" button, I don't want the date if they clicked on "Cancel" button.

### Your environment 🌎

I have provided a codesandbox, https://codesandbox.io/s/mui-5-forked-mhmccl

**Comment by alexfauquette** [comment]
The `onAccept` is not called if you have no value selected.

To let your button select values, you can use the `onDaySelect` prop. Here is a codesandbox with the `onAccept` being called

https://codesandbox.io/s/mui-5-forked-wkdgjt?file=/src/App.js:1109-1120

**Comment by subharb** [comment]
Also adding a defaultValue={dayjs()} helps on other issues. Like not calling onAccept the first time you select a date.
