### ISSUE TITLE
Unexpected Error: apiRef.current.sortColumn is not a function

### ISSUE THREAD

**Issue by elkind00** [mui/mui-x#9408]
I've edited this comment a few times, but this time I have produced a live example.  

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/pensive-blackwell-2hjnrj

### Current behavior 😯

When the testcase runs it receives the this error:

    "apiRef.current.sortColumn is not a function".

### Expected behavior 🤔

I expect the sortColumn function to be called and the column to be sorted.

### Context 🔦

I want to be able to produce unique filters and sorts from buttons.  The sort icon on the column headers doesn't provide these kinds of functions.

### Your environment 🌎

I use the Chrome browser.

  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Safari: 16.4

**Comment by romgrk** [comment]
This is your code:
```ts
<Button onClick={apiRef.current.sortColumn({field: 'id'}, 'desc', false)}>
    Sort
</Button>
```

The `onClick` property in react takes a function as its value, so you need to write it like this:
```ts
<Button onClick={() => apiRef.current.sortColumn({field: 'id'}, 'desc', false)}>
    Sort
</Button>
```
