### ISSUE TITLE
Extra space in time picker dropdowns

### ISSUE THREAD

**Issue by Bash0017** [mui/mui-x#9410]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
Just open the Timepicker and scroll down. you will notice empty spaces
![image](https://github.com/mui/mui-x/assets/61225819/7d4ff47b-b41f-45bd-bac8-81526e980828)

### Current behavior 😯

Extra spaces

### Expected behavior 🤔

Should not include extra spaces

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
That is a design decision that we took, which allows the selected values to be pinned to the top of the section container.
![Screenshot 2023-06-21 at 15 14 51](https://github.com/mui/mui-x/assets/4941090/25e2d859-b8ca-4e42-8990-fc0476d3951d)

If you don't want this behavior, feel free to [override the styles](https://codesandbox.io/s/nostalgic-solomon-q3lvyl?file=/demo.tsx).

**Comment by LukasTy** [comment]
If you have ideas on how to do it in a clean way - feel free to suggest it. 👌

**Comment by Bash0017** [comment]
@LukasTy We can simply make the selected value stick on top of section container and allow the scroll to pass through

**Comment by devbaji** [comment]
@LukasTy Thats sounds good, but some might not need this "pinned to top" feature. Can we have a cleaner way like a prop or something to disable this feature? Rather than overriding using CSS?

**Comment by LukasTy** [comment]
> Thats sounds good, but some might not need this "pinned to top" feature. Can we have a cleaner way like a prop or something to disable this feature? Rather than overriding using CSS?

@devbaji Do you mean the option to disable the scrolling of the selected item to the top?
There is currently no option to do what you are asking.
Could you create a separate issue for this? 🤔

**Comment by kieferMaland** [comment]
Design i would love to see:
1. have the numbers continuously scroll in a circular array fashion.
2. have selection be whatever number is in the center (or top) and highlight these numbers. 
3. if you click on a number that isn't in the center it goes to the center.

The space at the bottom looks really bad, and is confusing for the user,.
