### ISSUE TITLE
[question] Can't use `updateRows` inside `processRowUpdate` 

### ISSUE THREAD

**Issue by BrianSHenderson** [mui/mui-x#9423]
### Order ID

#67785

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am using Grouping with the DataGrid however when I use:
```
apiRef.current.updateRows
```
to change the grouping for a row the row does not move into the new group.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
System:
OS: macOS 13.4.1
Binaries:
Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
npm: 6.8.0 - ~/Documents/Documents/Repositories/node_modules/.bin/npm
Browsers:
Chrome: 114.0.5735.133
Edge: Not Found
Firefox: 110.0
Safari: 16.5.1
npmPackages:
@emotion/react: ^11.11.0 => 11.11.0
@emotion/styled: ^11.11.0 => 11.11.0
@mui/base: 5.0.0-beta.3
@mui/core-downloads-tracker: 5.13.3
@mui/icons-material: ^5.11.16 => 5.11.16
@mui/material: ^5.12.1 => 5.13.3
@mui/private-theming: 5.13.1
@mui/styled-engine: 5.13.2
@mui/system: 5.13.2
@mui/types: 7.2.4
@mui/utils: 5.13.1
@mui/x-data-grid: 6.5.0
@mui/x-data-grid-premium: 6.5 => 6.5.0
@mui/x-data-grid-pro: 6.5.0
@mui/x-license-pro: ^6.6.0 => 6.6.0
@types/react: 18.0.28 => 18.0.28
react: ^18.2.0 => 18.2.0
react-dom: ^18.2.0 => 18.2.0
typescript: 4.9.5 => 4.9.5
</details>

**Comment by BrianSHenderson** [comment]
System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 6.8.0 - ~/Documents/Documents/Repositories/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Firefox: 110.0
    Safari: 16.5.1
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.3 
    @mui/core-downloads-tracker:  5.13.3 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/material: ^5.12.1 => 5.13.3 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.2 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.1 
    @mui/x-data-grid:  6.5.0 
    @mui/x-data-grid-premium: 6.5 => 6.5.0 
    @mui/x-data-grid-pro:  6.5.0 
    @mui/x-license-pro: ^6.6.0 => 6.6.0 
    @types/react: 18.0.28 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 4.9.5 => 4.9.5

**Comment by BrianSHenderson** [comment]
I'm running my function in a processRowUpdate, seems to work elsewhere in my code but not here??

**Comment by flaviendelangle** [comment]
`processRowUpdate` itself is using `updatreRows` when the row is ready.
I think calling `updateRows` inside it causes the update you are doing to be overriden by our own.
