### ISSUE TITLE
[docs] Demo LazyLoadingGrid crashes

### ISSUE THREAD

**Issue by Surya9263** [mui/mui-x#9425]
- [ ] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LazyLoadingGrid%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-data-grid/row-updates/#lazy-loading
2. ??
3. demo *LazyLoadingGrid* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.8.0  |
| Netlify deploy | https://648c50da0767010008f88860--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

**Comment by romgrk** [comment]
I was able to reproduce once but I haven't since then, the error seemed to be where we have the `!` here:

https://github.com/mui/mui-x/blob/ff53b9261076a82fed5ce4a38f50ea2ad28bdce7/packages/grid/x-data-grid-pro/src/hooks/features/lazyLoader/useGridLazyLoader.ts#L38C1-L41

**Comment by oliviertassinari** [comment]
Duplicate of #10047
