### ISSUE TITLE
Pinned Column Error When Navigating to a Route Link (Within a Grid Column/Row) That Points to a Lazy-Loaded Page

### ISSUE THREAD

**Issue by edeloddernovocure** [mui/mui-x#9440]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: [https://codesandbox.io/s/muidgridpro-pinnedcolumn-lazyloadroute-error-q4k6x5](https://codesandbox.io/s/muidgridpro-pinnedcolumn-lazyloadroute-error-q4k6x5)

<h2>
              Summary:
            </h2>
            <p>
              Upon freshly browser-reloading this page and pinning the "Hi" column to the left, 
              and subsequently navigating to a lazy-loaded page via route link (contained in the grid column/row), 
              an exception is thrown in the file
              <i>".../@mui/x-data-grid-pro/hooks/features/columnPinning/useGridColumnPinning.js"</i>
            </p>

<h3>To reproduce the issue, please refer to the following steps:</h3>
            <ol>
              <li>
                Ensure that you have freshly clicked the browser's reload button, as this 
                issue appears only after a fresh page load.
              </li>
              <li>
                Pin the "Hi" Column to the left.
              </li>
              <li>Click the <i>Test Navigate to Lazy-Loaded Component</i> link, that is present in the 
                "Links column" within the DataGridPro component.
              </li>
              <li>This error should be generated:
                <p><i>(right-click "open image in new tab" to view full-size image)</i></p>
                
<img width="889" alt="issue" src="https://github.com/mui/mui-x/assets/137528405/d1cf1717-1508-4628-a1cb-6f1da9f226f4">

              </li>
            </ol>

### Current behavior 😯

When pinning a column, and subsequently clicking on a Route Link (from within a DataGridPro component's column) that refers to a lazy-loaded page component, an error is generated in the file ".../@mui/x-data-grid-pro/hooks/features/columnPinning/useGridColumnPinning.js"

### Expected behavior 🤔

After pinning data grid column(s), and clicking on Route Links from within the DataGridPro column(s), the given Route Link that refers to a lazy-loaded page component should be successfully navigated to, without error.

### Context 🔦

We are including Route Links within the DataGridPro component, so that for a given row, a user can navigate to a "details" page, to see further details regarding the entity referenced in the grid row. We cannot roll this functionality to production because our users are accustomed to pinning relevant grid columns, and then navigating to the links within the row to access further details.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.104
    @mui/core-downloads-tracker:  5.13.4
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.12 => 5.10.12
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.5
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid:  5.17.9
    @mui/x-data-grid-pro: ^5.17.9 => 5.17.9
    @mui/x-license-pro:  5.17.0
    @types/react:  18.2.13
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript:  4.9.5
</details>

### Order ID or Support key 💳 (optional)

39429

**Comment by romgrk** [comment]
I can reproduce, thanks for the detailed report.

**Comment by edeloddernovocure** [comment]
For sure, thanks for checking this out! Have a good weekend.

**Comment by davidrlarochelle** [comment]
Having the same issue here, even without pinned columns. Thank you for checking this.

**Comment by edeloddernovocure** [comment]
Hi @romgrk , Thank you for writing this fix, it is greatly appreciated! I'm new to MUI and was wondering if you can you tell me when bug fixes like this one usually become available via the usual "npm i @mui/x-data-grid-pro" process? Thanks.

**Comment by romgrk** [comment]
We release once a week, on Thursdays. #9519
