### ISSUE TITLE
Issue when installing modules

### ISSUE THREAD

**Issue by phani351** [mui/mui-x#9443]
### Order ID or Support key 💳 (optional)

68752

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

![error](https://github.com/mui/mui-x/assets/80298266/8259f549-a0c3-413c-934c-08d3d5ca9daf)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) _may_ be a good starting point. Thank you!
