### ISSUE TITLE
[question] How to Customize the DataGrid LoadingOverlay?

### ISSUE THREAD

**Issue by conerye** [mui/mui-x#9445]
### Order ID

331993142

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

The default loading overlay has just a CircularProgress. We would like the include a text message next to the CircularProgress. Is it possible to do that and if yes, would you please provide an example? The demos for v5 only show changing the CircularProgress to a LinearProgress...

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.121
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3
    @emotion/styled: ^11.8.1 => 11.9.3
    @mui/base:  5.0.0-alpha.87
    @mui/icons-material: ^5.8.0 => 5.8.4
    @mui/material: ^5.8.1 => 5.8.6
    @mui/private-theming:  5.9.1
    @mui/styled-engine:  5.8.7
    @mui/system: ^5.9.1 => 5.9.1
    @mui/types:  7.1.4
    @mui/utils:  5.10.6
    @mui/x-data-grid: ^5.13.1 => 5.14.0
    @mui/x-data-grid-premium: ^5.14.0 => 5.14.0
    @mui/x-data-grid-pro:  5.14.0
    @mui/x-date-pickers: ^5.0.0-beta.1 => 5.0.0-beta.2
    @mui/x-date-pickers-pro: ^5.0.0-beta.0 => 5.0.0-beta.2
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react:  18.0.14
    react: ^18.1.0 => 18.2.0
    react-dom: ^18.1.0 => 18.2.0
    typescript:  4.7.4
```
</details>

**Comment by romgrk** [comment]
If you want to replace the loading overlay, you need to replace the whole component.

```ts
<DataGrid
  components={{
    LoadingOverlay: function Component(props) {
      return <span><CircularProgress {...props}> Message</span>
    },
  }}
  loading
  {...data}
/>
```

https://v5.mui.com/x/react-data-grid/components/#loading-overlay

**Comment by conerye** [comment]
hummm... that does not work for me... lots of errors. Here is what I have so far, building from above:
<DataGridPremium
    // other stuff here
    components={{
        // if loadingMessage has been passed in, use custom Loading Overlay
        LoadingOverlay: loadingMessage ? CustomLoadingOverlay : undefined,
    }}
    componentsProps={{
        loadingOverlay: { customLoadingMessage: loadingMessage },
    }}
/>

const CustomLoadingOverlay = ({ customLoadingMessage }) => {
    return (
        <Stack direction="row" height="100%" alignItems="center" justifyContent="center" spacing={1}>
            <CircularProgress />
            <Typography variant="h6">{customLoadingMessage}</Typography>
        </Stack>
    );
};

CustomLoadingOverlay.propTypes = {
    customLoadingMessage: PropTypes.string.isRequired,
};

It kind of works. I say kind of because it does put up the spinner with the message in front of the data grid BUT the data grid is not greyed out like it used to be before I did this to add the message, and also the user can click and select rows while this custom loading overlay is up, which previously was not possible. In addition, there is the following console error:

react_devtools_backend_compact.js:2367 Warning: React does not recognize the `customLoadingMessage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `customloadingmessage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:3000/static/js/bundle.js:114983:66
    at GridOverlay (http://localhost:3000/static/js/bundle.js:175707:5)
    at GridLoadingOverlay
    at div
    at GridOverlayWrapper (http://localhost:3000/static/js/bundle.js:172148:99)
    at GridOverlays (http://localhost:3000/static/js/bundle.js:172189:99)
    at div
    at http://localhost:3000/static/js/bundle.js:114983:66
    at GridMainContainer (http://localhost:3000/static/js/bundle.js:175629:100)
    at GridBody (http://localhost:3000/static/js/bundle.js:171892:5)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:170642:1)
    at GridErrorHandler (http://localhost:3000/static/js/bundle.js:172000:5)
    at div
    at http://localhost:3000/static/js/bundle.js:114983:66
    at GridRoot (http://localhost:3000/static/js/bundle.js:175794:100)
    at GridContextProvider (http://localhost:3000/static/js/bundle.js:180523:5)
    at DataGridPremium (http://localhost:3000/static/js/bundle.js:160602:98)
    at http://localhost:3000/static/js/bundle.js:114983:66
    at div
    . . .

**Comment by romgrk** [comment]
The code I showed is an example of how to build what you want to build, you need to customize it to your needs. If you choose to replace the component, you need to re-implement any feature you want.

If you need further assistance, please provide a live example. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) is a good starting point.

**Comment by conerye** [comment]
ok, here you go:
https://codesandbox.io/s/pensive-breeze-qkn8nh?file=/src/ReplaceLoadingOverlay.jsx

like I said, the only thing I don't know how to do is make the data grid greyed out/disabled/inaccessible like it used to be before I replaced the overlay...

**Comment by romgrk** [comment]
I would recommend to check our [default loading overlay](https://github.com/mui/mui-x/blob/71a8da95af87c4edde1d4e1db38c37eb13cfec31/packages/grid/x-data-grid/src/components/GridLoadingOverlay.tsx#L6-L14) and use it as a starting point to implement the features you want.

**Comment by conerye** [comment]
cool, that worked. thank you.
