### ISSUE TITLE
Datepicker bug on production (vitejs build)

### ISSUE THREAD

**Issue by fatehMohamed14** [mui/mui-x#9450]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

When you build a react app using vitejs, the production build is not working 
![image](https://github.com/mui/mui-x/assets/61423008/2c2b084c-47c3-4c5a-91cf-16c06da35e9e)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Please provide a reproduction example or more information about the used packages and their versions.
Tested build with latest pickers package and vite `4.3.5`, working without issues.
There was already a very similar issue https://github.com/mui/mui-x/issues/8938 that was resolved by updating `vite` version.
