### ISSUE TITLE
[question] Display only month year in the date filter

### ISSUE THREAD

**Issue by tvaughan73** [mui/mui-x#9491]
### Order ID

62910

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is it possible to have a grid date filter display only month and year?  I have a grid column using date type where the value is formatted to show month/Year since the day is always the 1st.
e.g.
```
           {
                type: "date",
                field: "ReturnDate",
                headerName: "Period",
                width: 180,
                valueFormatter: ({ value }) => value && dayjs(value).format('MM/YYYY'),
            },
```
It would be similar to how you can set 
```
                                    views={[
                                        "month",
                                        "year",
                                    ]}
```
on a date picker to just show month and year.
Is there any way to do something like this for a data grid date filter?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
This would be a nice addition to the receipe with our date pickers

**Comment by dtygel** [comment]
Yes, it would be nice to allow for a column type called "month", as in HTML input, without the need to implement a custom input for that.
