### ISSUE TITLE
Performance lag on selection/deselection and scroll

### ISSUE THREAD

**Issue by Suhail-Murtaza** [mui/mui-x#9492]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Add around 500 rows. 
2. Add three custom rendered cells and one custom rendered header in the ColDef. 
3. Define onRowSelectionModelChange to map over selectedRows and set values to a state variable.

### Current behavior 😯

Selection/deselection and click actions experience a delay. 
Console shows following warnings: 

[Violation] 'scroll' handler took 657ms (While scrolling) 
[Violation] 'mouseup' handler took 632ms (on row select) 
[Violation] 'click' handler took 570ms (on row select) 

All these violations are reported in useGridFocus as shown is screenshot below:
<img width="1057" alt="Screenshot 2023-06-27 at 1 11 48 PM" src="https://github.com/mui/mui-x/assets/26179938/13b89cd5-5b7e-4915-8a8e-4ca9ff8e2f09">

The media is attached herewith to further assist you. Media shows the activities that are taking most of the time.

https://github.com/mui/mui-x/assets/26179938/e2011d5a-c975-4f77-ae55-e219694c870b

The react dev tools is unable to inspect DataGridPremiumForwardRef:

<img width="1302" alt="Screenshot 2023-06-27 at 12 30 50 PM" src="https://github.com/mui/mui-x/assets/26179938/9aa5feac-5881-40cf-b2fe-63bd6b1c9e22">

### Expected behavior 🤔

Should work smoothly without any lag as shown in demo on mui grid demos.

### Your environment 🌎

System:
    OS: macOS 13.4
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.4.1 => 11.10.6 
    @emotion/styled: ^11.3.0 => 11.10.6 
    @mui/base: ^5.0.0-beta.3 => 5.0.0-beta.3 
    @mui/core-downloads-tracker:  5.13.3 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.132 => 5.0.0-alpha.132 
    @mui/material: ^5.13.3 => 5.13.3 
    @mui/styled-engine:  5.13.2 
    @mui/system: ^5.13.2 => 5.13.2 
    @mui/utils:  5.13.1 
    @mui/x-data-grid:  6.6.0 
    @mui/x-data-grid-premium: ^6.6.0 => 6.6.0 
    @mui/x-data-grid-pro:  6.6.0 
    @mui/x-date-pickers: ^6.6.0 => 6.6.0 
    @mui/x-license-pro:  6.6.0 
    @types/react: ^17.0.0 => 17.0.53 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.3.2 => 4.9.5

### Order ID or Support key 💳 (optional)

67941

**Comment by romgrk** [comment]
You've checked the checkbox "I've tested with the latest version" but your reported grid version is `6.6.0` (latest is `6.9.0`). Can you confirm which version you've tested with? If it's not the latest, could you confirm the issue is present in `6.9.0`?

**Comment by Suhail-Murtaza** [comment]
Updated to 6.9.0. Still facing the same issue. 

Here is the definition of my onRowSelectionModelChange.

onRowSelectionModelChange = () => {
   const selectedUsers = Array.from(
      apiRef.current.getSelectedRows().values(),
    ).map((row) => row.userInfo);
    setUsers(selectedUsers);
}

**Comment by romgrk** [comment]
Is there any way you can put that code in a shareable live example? You can fork [this codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1). It would help us a lot to have that. Thanks!

**Comment by haseebq** [comment]
It'll be difficult to reproduce this in the sandbox because we have alot of other dependencies. Chances really are that soemthing in our code is triggering this weird behaviour. Do you have any advice on how to debug this? What should we look for in the profiles for example?

**Comment by romgrk** [comment]
It's hard to say without looking at the code. You need to focus the profile on a single event/call and walk back the stack to whatever is calling the most expensive entries in the log.

Otherwise, you need to reduce your test case until it's small enough to be shared in a live example. This is also likely to show you where the problem is coming from.

**Comment by Suhail-Murtaza** [comment]
@romgrk  
We have a maxHeight set on parent div and autoHeight set to true on DataGrid.
Here is the live example: 
https://codesandbox.io/s/data-grid-community-forked-3s2jqk?file=/src/App.tsx

Lag on selection/deselection and vertical/horizontal scrolling is evident. 

When a fixed height is set to the parent and autoHeight is false on DataGrid, it works smoothly.

Also, it crashed the browser when 100000 rows were used with autoHeight set to true.

**Comment by romgrk** [comment]
If you're setting `autoHeight` to `true`, you're disabling virtualization and rendering all N rows to the DOM (where N is 1,000 in your codesandbox). It's expected that a browser can't handle that many rows, and it's the problem solved by virtualization. You need to disable `autoHeight` if you have a large number of rows, there is no way around that. If other reasons prevent you from disabling `autoHeight`, open issues specific to your problem.
