### ISSUE TITLE
[DataGridPro] Column header borders misaligned when using header filters and pinned columns

### ISSUE THREAD

**Issue by traverse** [mui/mui-x#9495]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

To reproduce you need both `unstable_headerFilters` enabled and have some pinned columns.

You can find an example of it in this sandbox: https://codesandbox.io/s/youthful-nightingale-zxm6zc?file=/demo.tsx.

### Current behavior 😯

This image demonstrates the current behavior.

![image](https://github.com/mui/mui-x/assets/7240988/4667e2da-5f84-4910-a1d9-35cfe7e2f492)

### Expected behavior 🤔

I would expect the borders to align like the following image.

![image](https://github.com/mui/mui-x/assets/7240988/359cb730-0c9c-49d2-9b49-b226f5428a85)

### Context 🔦

It's not a huge issue but I noticed there's already some effort going on in regards to the header filters (https://github.com/mui/mui-x/issues/9034). I'm not sure if this issue might already be fixed by the aforementioned effort.  Otherwise it would be nice if it could be included in https://github.com/mui/mui-x/issues/9034.

### Order ID or Support key 💳 (optional)

2208761

**Comment by MBilalShafi** [comment]
@traverse Is this still an issue on your end?
I can't reproduce with the latest version.
Example: https://stackblitz.com/edit/react-vccnqh?file=Demo.tsx
