### ISSUE TITLE
[DataGridPro] Crash when removing a row below any treeData parent when checkbox selection enabled

### ISSUE THREAD

**Issue by MikeRippon** [mui/mui-x#9503]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/grid-bug-no-hide-5n7csf?file=/demo.jsx

Steps (live example):
1. Click the remove button on the "Can't remove" row

(I've added some extra controls to allow testing different scenarios, as the bug is only triggered under these specific circumstances as far as I can tell).

Steps (full description):
1. Set up a grid with treeData
3. Enable checkbox selection (bug only appears with checkbox selection enabled)
4. Ensure the grid contains:
  a. A parent row and child row
  b. A "trigger parent row" anywhere below the parent & child (rows above the parent/child won't trigger the bug)
5. Remove (only) the "trigger" row by removing it from the `rows` property (removing the parent & child rows at the same time will not trigger bug, e.g. clearing all rows does not trigger it)

Suboptimal workaround: Alter the `key` property when the rows change (e.g. `key={rows.length}` to force the grid to fully reset.

### Current behavior 😯

Crash: `rowTree[row.id] is undefined` (firefox)
Crash: `Cannot read properties of undefined (reading 'depth')` (chrome)

### Expected behavior 🤔

Row should be removed without error

### Context 🔦

I have a data grid that displays tree data, and these rows can be selected using checkbox selection. The `rows` property is changed when a row is deleted by the user. This worked previous in 5.17.2

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.51)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.9.3
    @emotion/styled: ^11.6.0 => 11.9.3
    @mui/base:  5.0.0-alpha.104
    @mui/core-downloads-tracker:  5.10.12
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/lab: 5.0.0-alpha.106 => 5.0.0-alpha.106
    @mui/material: ^5.10.12 => 5.10.12
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system:  5.10.12
    @mui/types:  7.2.0
    @mui/utils:  5.13.6
    @mui/x-data-grid:  6.9.0
    @mui/x-data-grid-pro: ^6.9.0 => 6.9.0
    @mui/x-date-pickers: ^6.9.0 => 6.9.0
    @mui/x-license-pro:  6.9.0
    @types/react:  18.0.14
    react: ^18.0.0 => 18.2.0
    react-dom: ^18.0.0 => 18.2.0
    typescript: ^4.9.4 => 4.9.5
```

</details>

**Comment by romgrk** [comment]
Closed by #9418, will be release at the end of the week.
