### ISSUE TITLE
Custom column keep rerendering

### ISSUE THREAD

**Issue by SimonStAmand** [mui/mui-x#9504]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/react-mui-forked-fmrc4r?file=/index.js 

Steps:
1. Open column menu for column 'max'
2. Type anything in the Textfield

Focus for Textfield will be lost due to rerender

### Current behavior 😯

When user types anything in a Textfield in a custom column menu, the menu keeps rerendering

![image](https://github.com/mui/mui-x/assets/39802631/85faf188-863b-4fe0-9922-986286d22187)

### Expected behavior 🤔

The component should need only to render once and stay stable afterwards

### Context 🔦

I want a Textfield in column menu. The value in the Textfield is then replicate in every selected rows of the DataGrid.

I am using the regular version of x-data-grid

Finally, while my npx @mui/envinfo does not show the lastest version of x-data-grid, the sandbox I created does use the latest version

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Safari: 16.5.1
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1
    @emotion/styled: 11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.4
    @mui/core-downloads-tracker:  5.13.4
    @mui/icons-material: 5.11.16 => 5.11.16
    @mui/lab: 5.0.0-alpha.129 => 5.0.0-alpha.129
    @mui/material: 5.13.5 => 5.13.5
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/styles: 5.13.1 => 5.13.1
    @mui/system:  5.13.6
    @mui/types:  7.2.4
    @mui/utils:  5.13.6
    @mui/x-data-grid: 6.4.0 => 6.4.0
    @mui/x-date-pickers: 6.4.0 => 6.4.0
    @types/react: 18.2.14 => 18.2.14
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.5.2 => 4.5.2

  The browser I use is chrome
```
</details>

**Comment by alexfauquette** [comment]
## Why it appends

You define your custom column menu inside the main component

```jsx
const App = () => {
 const [value, setValue] = React.useState('');

 const MyMenu = () => <input onChange={event => setValue(event.target.value)}/>

  return <DataGrid slots={{ columnMenu: MyMenu }} />
}
```

So when you modify the text field, the following append:

1. Call `setValue`
2. Update the state of `App`
3. `App` rerender, which create an new definition of `MyMenu`
4. The `DataGrid` rerender the new columnMenu which lost all it's internal state

## How to solve it

Your custom component should be define outside of the main components. It's a react concept, your components should not be defined inside another one.

Since you need to pass custom props, you can use `slotProps` (or `componentsProps`)

```jsx
const MyMenu = () => <input onChange={event => setValue(event.target.value)}/>

const App = () => {
 const [value, setValue] = React.useState('');

  return <DataGrid 
    slots={{ columnMenu: MyMenu }} 
    slotProps={{ columnMenu: {
      theMaxValue: value,
      setTheMaxValue: setValue,
    }
  }} />
}
```
