### ISSUE TITLE
[pickers] Style customization on StaticDateRangePicker

### ISSUE THREAD

**Issue by MarianaKWork** [mui/mui-x#9508]
### Order ID or Support key 💳 (optional)

69565

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I have just started setting up mui pro, so there is a chance I have not set it up correctly. I have set up the license key in _app.tsx like so:

import { LicenseInfo } from '@mui/x-license-pro'

LicenseInfo.setLicenseKey('LICENSE_KEY')

and I am now trying to install a date range picker by running 'yarn add @mui/x-date-pickers-pro/StaticDateRangePicker'

This returns the error that you can see in the screenshot.

<img width="1405" alt="Screenshot 2023-06-28 at 08 45 24" src="https://github.com/mui/mui-x/assets/115994019/d8fbc8a3-8db5-4abf-9409-1774fc8cc051">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 13.4
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-alpha.95 
    @mui/core-downloads-tracker:  5.11.12 
    @mui/icons-material: 5.10.3 => 5.10.3 
    @mui/material: 5.10.3 => 5.10.3 
    @mui/private-theming:  5.11.12 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.12 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.12 
    @mui/x-date-pickers: ^5.0.10 => 5.0.20 
    @mui/x-date-pickers-pro: ^6.9.0 => 6.9.0 
    @mui/x-license-pro: ^6.9.0 => 6.9.0 
    @types/react: 18.2.0 => 18.2.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.9.4 => 4.9.5 
```
</details>

**Comment by LukasTy** [comment]
Hello, could you confirm the reason why you are trying to install a component as a package? 🤔 
Where did you find a suggestion to use this snippet? 🤔 

To install the package you have to run:
```sh
yarn add @mui/x-date-pickers-pro
```

**Comment by MarianaKWork** [comment]
> Hello, could you confirm the reason why you are trying to install a component as a package? 🤔 Where did you find a suggestion to use this snippet? 🤔
> 
> To install the package you have to run:
> 
> ```shell
> yarn add @mui/x-date-pickers-pro
> ```

Thank you! I couldn't find anywhere at the time how to use it, but figured it out in the end. I also have some questions about how to customise the css of the dates selected in the date range. Shall I open up a new request for this?

I would like to change the styles of very specific elements, like the start date for the date range if this is possible?

![Uploading Screenshot 2023-06-28 at 10.53.19.png…]()

**Comment by LukasTy** [comment]
> I would like to change the styles of very specific elements, like the start date for the date range if this is possible?

It depends. How much customization do you plan to do?
- If it's only some minor CSS tweaks, you are probably better with either `styleOverrides` or passing `sx` prop to the relevant slot.
- If you are considering making quite significant changes, maybe even some functional ones, then you can consider [overriding the `day` slot](https://mui.com/x/react-date-pickers/date-range-calendar/#custom-day-rendering).

Here is [a codesandbox](https://codesandbox.io/s/date-range-picker-day-style-override-j9hf3w?file=/demo.tsx) to get you started.

**Comment by MarianaKWork** [comment]
> > I would like to change the styles of very specific elements, like the start date for the date range if this is possible?
> 
> It depends. How much customization do you plan to do?
> 
> * If it's only some minor CSS tweaks, you are probably better with either `styleOverrides` or passing `sx` prop to the relevant slot.
> * If you are considering making quite significant changes, maybe even some functional ones, then you can consider [overriding the `day` slot](https://mui.com/x/react-date-pickers/date-range-calendar/#custom-day-rendering).
> 
> Here is [a codesandbox](https://codesandbox.io/s/date-range-picker-day-style-override-j9hf3w?file=/demo.tsx) to get you started.

Thank you! That's what I've been doing, but I'm looking to style more specific classes and I don't know how to target them. For instance, the background color of the date range selected. For a bit more info, here is a screenshot of what I need to the component to look like (as much as possible)

<img width="442" alt="Screenshot 2023-06-29 at 08 38 22" src="https://github.com/mui/mui-x/assets/115994019/1975c660-7cf2-4c1a-9f48-0c72b6a2ef08">

**Comment by MarianaKWork** [comment]
It might not be possible, or too complex, in which case I am happy to tell my designer we can't do this.

**Comment by LukasTy** [comment]
> That's what I've been doing, but I'm looking to style more specific classes and I don't know how to target them. For instance, the background color of the date range selected without affecting the background color of the dates that haven't been selected.

Have you tried looking [through the API](https://mui.com/x/api/date-pickers/date-range-picker-day/) of specific components to identify the possible class names (style override slots) that you can target? 🤔 
This component should have most of the slots you need to override.

**Comment by MarianaKWork** [comment]
> through the API

Thank you, didn't realise there was an API specific just for the day component. I was looking at the API for the date range picker

**Comment by LukasTy** [comment]
When looking at styling certain components, try targeting the most specific component you can (without bleeding the styles into unwanted components).
The date range picker will not support any styling overrides, because it doesn't have any slots to override the styles.
The most top-level components that you might be interested in are [DateRangeCalendar](https://mui.com/x/api/date-pickers/date-range-calendar/) and [PickersLayout](https://mui.com/x/api/date-pickers/pickers-layout/).

**Comment by MarianaKWork** [comment]
Damn, I didn't even realise there were these components, thank you for your help!

**Comment by LukasTy** [comment]
Closing this issue as there does not seem to be any more open questions to solve.
As for the improvements to styling customization documentation—we are working on it. 👌
