### ISSUE TITLE
Dayjs dateAdapter is not compatible with Dayjs ObjectSupport Plugin

### ISSUE THREAD

**Issue by JerryTheIntern** [mui/mui-x#9524]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

```
import './App.css';

import { DateField } from '@mui/x-date-pickers/DateField';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import * as React from 'react';
import { useEffect, useState } from 'react';
import Dayjs from 'dayjs'

var objectSupport = require("dayjs/plugin/objectSupport"); //Remove this to solve the issue
Dayjs.extend(objectSupport); //Remove this to solve the issue

function App() {
  const [since, setSince] = useState(0)

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DateField
          label="Full letter month"
          value={Dayjs(since)}
          onChange={(newValue) => {
              setSince(newValue.valueOf())
          }}
          format="LL"
        />
    </LocalizationProvider>
  );
}

export default App;

```

### Current behavior 😯

When adding the `objectSupport` plugin to Dayjs, in the presence of the Localization Adapter, this error is displayed:
Uncaught TypeError: Cannot read properties of null (reading 'constructor')
    at M.r (objectSupport.js:1:1)
    at i.parse (objectSupport.js:1:1)
    at new M (dayjs.min.js:1:1)
    at AdapterDayjs.w (dayjs.min.js:1:1)
    at DayjsUtils.isValid (index.esm.js:98:1)
    at Object.getSectionsFromValue (valueManagers.js:14:1)
    at useFieldState.js:29:1
    at mountMemo (react-dom.development.js:17225:1)
    at Object.useMemo (react-dom.development.js:17670:1)
    at Object.useMemo (react.development.js:1650:1)

### Expected behavior 🤔

The ObjectSupport Plugin should work in the presence of a localization adapter

### Context 🔦

It's not possible to use the localization adapter alongside the objectsupport plugin

### Your environment 🌎

Tested on Chrome

System:
    OS: macOS 13.4.1
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: Not Found
    Safari: 16.5.1
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.5 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/material: ^5.13.6 => 5.13.6 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.6 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.6 
    @mui/x-date-pickers: ^6.9.0 => 6.9.0 
    @types/react:  18.2.14 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.9.5

**Comment by flaviendelangle** [comment]
Duplicates #7571 
Feel free to upvote / comment the issue on the dayjs repo to try to get a fix from there side :+1:
