### ISSUE TITLE
Data Grid column fluid width: resizing not working properly based on the window size

### ISSUE THREAD

**Issue by xli12** [mui/mui-x#9532]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/bold-browser-wwchj4

```
"@mui/material": "^5.13.6",
"@mui/x-data-grid-pro": "^6.9.0",
```

Steps:
1. Implement the application based on the code given in the sandbox above 👆.
2. Click the button "change bar open status".
    - Expected behaviour: the bar slides in.
    - Actual behaviour: the bar does not slide in; instead, it appears and stays at the right.
3. Resize the browser window.
    - Expected behaviour: the data grid resizes based on the window size.
    - Actual behaviour: the data grid does not shrink properly.

Note:

In line 35:

```
<DataGridPro rows={rows} columns={columns} autoHeight />
```

you may replace `columns={columns}` to `columns={columnsWithWidth}`, and you'll see the behaviour I expect.

The only difference between `columns` and `columnsWithWidth` is using `flex` or `width` in specifying the width of a column.

### Current behavior 😯

1. When resizing the browser window, the data grid does not resize (shrink to be precise) properly.
2. The side bar do not slide in properly.

https://github.com/mui/mui-x/assets/1527106/1768fe9e-6228-4f39-a816-ead93265b42c

### Expected behavior 🤔

1. When resizing the browser window, the data grid should be resized properly.
2. The side bar slides in properly.

### Context 🔦

The screen recording below (almost) shows what I want to achieve:

1. When clicking the button, the side bar slides in or out, and the data grid can be resized properly.
2. When resizing the browser window, the data grid can be resized properly.

This is the case if I set the column width using the `width` property; unfortunately this is not the case when I use `flex`.

I do want to use `flex` so that the columns doesn't have a fixed with; instead, the width will be adjusted based on the window size.

https://github.com/mui/mui-x/assets/1527106/dc0de88b-e4a7-4cb3-bb0d-c1b397855c6b

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: Version 114.0.5735.198 (Official Build) (arm64)
  npmPackages:
    typescript: ^4.8.3 => 4.8.3
```
</details>

**Comment by cherniavskii** [comment]
Hey @xli12 
It looks like the issue is caused by the parent layout, not the data grid itself.
Applying `min-width: 0` to the grid parent element gives the expected behavior: https://codesandbox.io/s/condescending-noyce-w2dknc
You can learn more about `min-width: 0` here: https://css-tricks.com/preventing-a-grid-blowout/

**Comment by xli12** [comment]
Hi @cherniavskii, thank you for your help and the reference to the blog post! It indeed works with the magic of `min-width: 0`.
