### ISSUE TITLE
[TimePicker] It is disabling all hour if minute 00 needs to be disabling

### ISSUE THREAD

**Issue by HenriqueBarucco** [mui/mui-x#9534]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using TimePicker's "shouldDisableTime" function to disable a certain time, if the minute of that time is 00, it will disable the entire time (however, if the value of the time is inserted in the hand, it is possible to see the values of the minute that was not blocked)

```
const shouldDisableTime = (time) => {
    if (time.hours() == 5) {
        return true;
    }
    for (let interval of times) {
        if (
            time.isSame(moment(interval.start, 'HH:mm')) ||
            time.isSame(moment(interval.end, 'HH:mm')) ||
            time.isBetween(
                moment(interval.start, 'HH:mm'),
                moment(interval.end, 'HH:mm')
            )
        ) {
            return true;
        }
    }
    return false;
};

<TimePicker
    label="Início"
    onChange={handleTimeChange('start')}
    value={time.start ? moment(time.start, 'HH:mm') : null}
    inputFormat="HH:mm"
    views={['hours', 'minutes']}
    minutesStep={5}
    minTime={moment().set('hour', 6).set('minute', -1)}
    maxTime={moment().set('hour', 18).set('minute', 0)}
    emptyLabel="Selecione uma hora"
    shouldDisableTime={shouldDisableTime}
    disableIgnoringDatePartForTimeValidation
    skipDisabled
/>
```

### Expected behavior 🤔

I believe the expected behavior is that only the 00th minute is disabled, keeping the time still active, unless all internal minutes of a given hour are disabled

### Context 🔦

I'm doing a project for college and I came across this problem

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.58)
  npmPackages:
    @emotion/react:  11.10.8 
    @emotion/styled:  11.10.8 
    @mui/base:  5.0.0-alpha.127 
    @mui/core-downloads-tracker:  5.12.2 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.127 => 5.0.0-alpha.128 
    @mui/material: ^5.12.0 => 5.12.2 
    @mui/private-theming:  5.12.0 
    @mui/styled-engine:  5.12.0 
    @mui/system:  5.12.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.12.0 
    @mui/x-data-grid: ^6.3.0 => 6.3.0 
    @mui/x-date-pickers: ^6.2.1 => 6.3.0 
    @types/react:  18.2.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by HenriqueBarucco** [comment]
I made this example to show how the error is occurring:

[Code Sandbox - Time Picker](https://codesandbox.io/s/date-and-time-pickers-forked-qvymzf?file=/src/App.tsx)

As you can see, I put time intervals to be deactivated in the time picker, but I purposely left a few minutes in certain hours, but if the hour with minute 00 is deactivated, it ends up disappearing too.

But if you put PM in the time and manually type 04, the minutes that were not deactivated will appear.

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/date-and-time-pickers-forked-6xd833?file=/src/App.tsx:588-605

`shouldDisableTime` receives a 2nd argument with the view you are validating.
I tried to update your example to have a better behavior.

@LukasTy The DX may not be great here, not sure how we could improve it.

**Comment by HenriqueBarucco** [comment]
Thankss, that's exactly what I was needing, I appreciate it a lot.

**Comment by LukasTy** [comment]
> The DX may not be great here, not sure how we could improve it.

I have a few points floating in my head that could help in one way or another:
1. We could provide the currently selected value in the `shouldDisableTime` so that it would be easier to provide a function without having to recreate the function on every value change if the end user wants to also depend on a controlled selected value;
2. We could have the option to control when or which views should have their disabled values skipped to allow for more freedom (i.e. more powerful `skipDisabled`)
3. Actually really consider the option to support the `disabled` ranges prop, where the end user would only need to provide the slots that should be disabled and then it would be easier for us to actually control when to disable what. 🤔
