### ISSUE TITLE
Problem with Picker View Box in Low Height

### ISSUE THREAD

**Issue by fakhamatia** [mui/mui-x#9535]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

If the height is not enough for show picker view box, picker goes top of input and it's ok.
But the year picker height is lower than picker view, then it does not know where to be up or down.
I can't choose the year, year picker close itself.

### Expected behavior 🤔

Year picker show in position of main view and not jumping.

### Context 🔦

[Screencast from 2023-07-01 12-28-09.webm](https://github.com/mui/mui-x/assets/20030910/b17ee511-7596-477d-bb34-b696320cdf24)

### Your environment 🌎

[https://codesandbox.io/s/wonderful-rgb-ff9vfr?file=/demo.js](https://codesandbox.io/s/wonderful-rgb-ff9vfr?file=/demo.js)

**Comment by LukasTy** [comment]
Thank you for opening this issue with a detailed example. 🙏 
We already have an open issue regarding this #9288, closing this one as it's a duplicate.
Feel free to follow the linked issue to get notified of its progress. 😉
