### ISSUE TITLE
Incorrect Arabic characters when exporting data as CSV UTF-8 in datagrid

### ISSUE THREAD

**Issue by ShaalanMarwan** [mui/mui-x#9545]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

1- Install datagrid version ^5.3.0 and create a data grid with Arabic language data.
2- Export the data grid as a CSV file using the UTF-8 encoding.
3- Open the exported CSV file in Excel and verify that the Arabic characters are displayed correctly.

### Current behavior 😯

After upgrading to datagrid version v6.6.0, the exported CSV file in Excel shows incorrect characters "ÿßŸÑ" instead of the correct Arabic characters.

### Expected behavior 🤔

Arabic language characters should be displayed correctly in the exported CSV file when using datagrid version v6.6.0.

### Context 🔦

I am currently using datagrid version ^5.3.0, and the Arabic language characters were displaying correctly when exporting data as CSV UTF-8. However, after upgrading to version v6.6.0, I noticed that the exported CSV file in Excel shows characters like "ÿßŸÑ" instead of the correct Arabic characters.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
 System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.6.1 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Safari: 16.5.1
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.5 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/material: ^5.13.3 => 5.13.6 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.6 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.6 
    @mui/x-data-grid: ^5.3.0 => 5.17.26 
    @types/react: ^18.0.25 => 18.2.14 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.3 => 4.9.5 
```
</details>

**Comment by MBilalShafi** [comment]
Could you provide a live reproduction on codesandbox?
For me, it's working fine on this codesandbox example: https://codesandbox.io/s/data-grid-community-forked-wy5mlr?file=/src/App.tsx

**Comment by ShaalanMarwan** [comment]
@MBilalShafi Hello Sir , 
When exported your data that within the link that you shared , it shows me symbols too
<img width="456" alt="Screenshot 2023-07-04 at 10 32 08 AM" src="https://github.com/mui/mui-x/assets/26276966/a6a6bfc0-a1de-45c7-9fa3-d1f7db476bd4">

**Comment by MBilalShafi** [comment]
Seems like Excel is not reading the exported file correctly. Can you check if you can open the exported CSV file in any other application (a good choice could be a plain text editor like Notepad) and see the characters fine?
Or you can give this [guide](https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-open-utf-8-csv-file-in-excel-without-mis/1eb15700-d235-441e-8b99-db10fafff3c2) a go to make it work in Excel.
Let me know if one of these options works for you.

**Comment by ShaalanMarwan** [comment]
the problem is only with Excel and with the version newer than the **^5.3.0** version. 
I used several laptops with different Excel apps also with mobile versions and all of them had the same problem with the latest versions. it works working correctly with the 5.3.0 and I had not any kind of problem before that.

**Comment by ShaalanMarwan** [comment]
the problem is only with Excel and with the version newer than the ^5.3.0 version.
I used several laptops with different Excel apps also with mobile versions and all of them had the same problem with the latest versions. it works working correctly with the 5.3.0 and I had not any kind of problem before that.

**Comment by ShaalanMarwan** [comment]
when i open it with numbers(Mac) , preview as CSV it working correctly

**Comment by MBilalShafi** [comment]
Since the issue doesn't comes from the `DataGrid` itself but a specific version of Excel, I don't think we can do much here. You can refer to a guide or the Excel support about how to import the unicode spreadsheets in Excel.

**Comment by tomnattle** [comment]
Hi, Bro ，the code below can solve my issue, but i dont know how enmerge into  mui datagrid
 
 
 const csvContent = "\ufeff" + dataArray.join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv,charset=UTF-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'data.csv';

> Since the issue doesn't comes from the `DataGrid` itself but a specific version of Excel, I don't think we can do much here. You can refer to a guide or the Excel support about how to import the unicode spreadsheets in Excel.

**Comment by Wael-dukhan** [comment]
customize: function (csv) {
                        // إضافة BOM قبل محتوى CSV لضمان دعم اللغة العربية
                        return '\uFEFF' + csv; // يضيف BOM إلى بداية الملف
                    }
