### ISSUE TITLE
[docs] Demo LocalizationDayjs crashes

### ISSUE THREAD

**Issue by olifrieda** [mui/mui-x#9547]
- [x] I have [searched for similar issues](https://github.com/mui/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20LocalizationDayjs%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/x/react-date-pickers/adapters-locale/
2. in first (!) demo *double click* on one of the locale select buttons
3. demo *LocalizationDayjs* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v6.9.1  |
| Netlify deploy | https://649edb90afee2f0008fd1c66--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15 |

**Comment by flaviendelangle** [comment]
Thanks for your feedback :+1:
