### ISSUE TITLE
[docs] Update RTL Support section of the Localization docs

### ISSUE THREAD

**Issue by MBilalShafi** [mui/mui-x#9552]
Since #230 is already done, it needs to be reflected on https://mui.com/x/react-data-grid/localization/#rtl-support section so that people start using it and providing feedback.

**Comment by richbustos** [comment]
@MBilalShafi Should I simply update the docs by removing the callout?

**Comment by richbustos** [comment]
https://github.com/mui/mui-x/pull/9710

**Comment by MBilalShafi** [comment]
@richbustos Thanks for the PR. IMO, removing the callout and adding a demo like [this](https://mui.com/material-ui/guides/localization/#example) (with RTL) for the Grid will make the feature more accessible and easier to use.

**Comment by richbustos** [comment]
> @richbustos Thanks for the PR. IMO, removing the callout and adding a demo like [this](https://mui.com/material-ui/guides/localization/#example) (with RTL) for the Grid will make the feature more accessible and easier to use.

Sweet. Thats what i did in my PR. When you have the chance (after you come back from vacation), can you review?  https://github.com/mui/mui-x/pull/9710

**Comment by oliviertassinari** [comment]
> what do you think about the demo https://deploy-preview-9710--material-ui-x.netlify.app/x/react-data-grid/localization/#rtl-support I added?

@MBilalShafi A couple of the styles is wrong on this demo, e.g. footer pagination next and previous page icons. I think it's because it's missing the CacheProvider, as in https://mui.com/material-ui/guides/right-to-left/#demo.

**Comment by MBilalShafi** [comment]
@oliviertassinari Thanks for the feedback, I'll open up a PR with the plugin added.

**Comment by MBilalShafi** [comment]
@oliviertassinari rtl plugin (stylis) is not playing well with the existing theme, i.e. it messes with the dark mode styling, this is how [right-to-left docs demo](https://mui.com/material-ui/guides/right-to-left/) looks in dark mode:
![image](https://github.com/mui/mui-x/assets/12609561/6ec57d81-f05a-47d8-90b3-2adaf2ca23b6)

The same is the case when I try to use this plugin with the grid [demo](https://deploy-preview-10561--material-ui-x.netlify.app/x/react-data-grid/localization/#rtl-support).

Making use of `useTheme` like the following fixes the dark mode styling issue, but then the RTL plugin starts to break as in https://github.com/mui/mui-x/issues/9552#issuecomment-1703370425.

```tsx
function DataGridRTL() {
  const existingTheme = useTheme();
  const theme = React.useMemo(
    () => createTheme({ direction: 'rtl' }, existingTheme, arSD),
    [existingTheme],
  );
  return (
    <ThemeProvider theme={theme}>
      <CacheProvider value={cacheRtl}>
        <div dir="rtl" style={{ height: 400, width: '100%' }}>
          <DataGrid rows={rows} columns={columns} />
        </div>
      </CacheProvider>
    </ThemeProvider>
  );
}
```

Any idea if this is a known issue on core side?
