### ISSUE TITLE
[question] Filter panel allowing to filter by custom fields

### ISSUE THREAD

**Issue by rony-arnac** [mui/mui-x#9553]
### Order ID or Support key 💳 (optional)

69416

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am trying to add filter options that are not dependent on the fields that exist in my `GridColDef`.

For example, I have a grid with the following interface:

```
interface MyData {
  name: string;
  value: number;
}
```
I'd like to filter by `otherValue`, which isn't one of the fields in my data.

Is there a way to define custom filter configurations that include `field`, `filterOperators` and any other fields that are necessary to maintain a filter model for them?

We use server-side filtering.

Thanks!

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /nix/store/fm7h9gy4yzkymdkys1wz005m738qn68q-yarn-1.22.19/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.4 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material:  5.11.16 
    @mui/lab:  5.0.0-alpha.134 
    @mui/material:  5.13.6 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/styles:  5.13.2 
    @mui/system:  5.13.6 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.6 
    @mui/x-data-grid:  6.9.0 
    @mui/x-data-grid-pro:  6.9.0 
    @mui/x-license-pro:  6.9.0 
    @types/react:  17.0.62 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^5.1.3 => 5.1.5 
```
</details>

**Comment by rony-arnac** [comment]
Thank you @m4theushw for answering!
The think is, if I use hideable, then there's also a way to make the fake column visible, which I won't want to happen.
If there was a third option of having a fake column that is never visible and is just for storing the required information, that would be awesome!

**Comment by cherniavskii** [comment]
I've added a demo with filtering by a hidden field in https://github.com/mui/mui-x/issues/11355#issuecomment-1866856637
