### ISSUE TITLE
v6 DateTimePicker limits keyboard hours to 1-4 in Chrome

### ISSUE THREAD

**Issue by AidenMead** [mui/mui-x#9557]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://mui.com/x/react-date-pickers/date-time-picker/ - use any of the example DT pickers with a default time set. Only an issue in Chrome (Firefox allows changes)

Chrome v

Steps:
1. Go to DateTimePickers in a Chrome browser
2. Select Hour field
3. Use any of the 1-4 digits to change the time
4. Attempt any 5-9 digit to change hour and note no change

### Current behavior 😯

When using Chrome 113.0.5672.92, attempting to use the keyboard to update the hour within a DateTimePicker, the DateTime picker will not accept input from any of the number keys aside from 1-4, this eliminates the ability to also create double digit hours (10, 11, 12).

Tested in Firefox, and issue was not present.
Note: Chrome v114.0.5735.133 does not seem to have this issue either, this is limited to the specific version as far as I can tell.

### Expected behavior 🤔

User should be able to use all numbers to input the time across Chrome versions.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Thank you for opening this issue.
As you have mentioned, you are only able to reproduce an issue in one specific version of one specific browser.
If that was an issue in Chrome's release, we can't really do anything, just say sorry, but it's an external dependency concern. 🤷 
I wasn't able to reproduce the mentioned issue in any of the major browsers' latest versions.

**Comment by LukasTy** [comment]
> Not sure that changes anything, since you can't reproduce, but I felt it might be worth documenting.

Thank you for clarifying the issue peculiarity.
Would you be able to record a video showcasing the problem?
