### ISSUE TITLE
Some API documentation pages cut description column even on wide screen

### ISSUE THREAD

**Issue by namiskuukkel** [mui/mui-x#9558]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps to reproduce:

1. Visit the following pages on Chrome using a normal or wide desktop screen and pay attention to description column of props table
https://mui.com/x/api/date-pickers/date-picker/
https://mui.com/x/api/date-pickers/date-time-field/

2. Compare to the same column on these pages
https://mui.com/x/api/date-pickers/month-calendar/
https://mui.com/x/api/date-pickers/pickers-day/

### Current behavior 😯

Props table doesn't fit the page layout fully, hiding part of description chapter and causing table to become sideways scrollable. Screenshot taken on ultra wide screen to emphasize there would be space for a wider table.
![image](https://github.com/mui/mui-x/assets/5670621/5a804a15-f487-419b-b7c5-977c92724e06)

### Expected behavior 🤔

The page should render similar to DateCalendar API
![image](https://github.com/mui/mui-x/assets/5670621/42f6ae13-1be2-44f5-b142-81032735f15c)

### Context 🔦

I noticed this difference on API documentation page rendering when visiting DatePicker documentation and comparing it to some other pages. I didn't go through every API page so these four aforementioned pages are just examples.
The side scroll is especially difficult to handle as the side scrollbar appears only on the very bottom of the long table so it isn't obvious that it is actually possible to get rest of the description column to show, although it is impossible to get the whole table to show at the same time.

### Your environment 🌎

Browser used Google Chrome version 114.0.5735.199

**Comment by alexfauquette** [comment]
Closing this one since it will be solved on the same time #9559 will be

About the following sentence, Are you reading text that fills your screen? It seems impossible to follow a line of text from far teft to far right

> there would be space for a wider table.

**Comment by namiskuukkel** [comment]
I just meant that I wanted to emphasize that the description column wasn't cut due to screen size not being wide enough to fit the whole table at once. I'm sorry for being unclear.

**Comment by alexfauquette** [comment]
Thanks for the clarification. I keep the issue closed since the fix for one of them will also fix the other one
