### ISSUE TITLE
[pickers] Setting the textfield to readonly no longer works

### ISSUE THREAD

**Issue by seferturan** [mui/mui-x#9560]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/nostalgic-meninsky-6tvqft?file=/src/App.tsx

Steps:
1. Click on the date picker
2. Before the dropdown opens, the text is selected

Tried using a custom field also, but that results in an error. Example: https://codesandbox.io/s/flamboyant-cdn-2tvsfj?file=/src/App.tsx

Steps:
1. Click on the date picker
2. Error

### Current behavior 😯

The text in the date picker gets selected, even though it should be readonly.

### Expected behavior 🤔

I'd expect the same behavior as in v5, where text doesn't get selected and all interaction can be done through the dropdown.

### Context 🔦

We want the user to only interact with the dropdown without being able to enter values in the text field.

### Your environment 🌎

See sandbox also. Below is the envinfo from my local machine. Which does not seem 100% correct, since I also have Chrome, Firefox, and Edge.

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Safari: 16.5.1
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.5
    @mui/core-downloads-tracker:  5.13.4
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/material: ^5.13.6 => 5.13.6
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.6
    @mui/types:  7.2.4
    @mui/utils:  5.13.6
    @mui/x-date-pickers: ^6.9.1 => 6.9.1
    @types/react: ^18.2.14 => 18.2.14
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.1.6 => 5.1.6
```
</details>

**Comment by LukasTy** [comment]
With [a few tweaks](https://codesandbox.io/s/boring-williamson-39drt8?file=/src/App.tsx) to the provided example (removing redundant parts and adding more correct `open` state controlling), everything seems to work as expected and I do not notice any sections being selected. 🤔 
Could you confirm if you are still having this issue?
And if yes, maybe you could provide a video showcasing the problem? 🙏

**Comment by seferturan** [comment]
> With [a few tweaks](https://codesandbox.io/s/boring-williamson-39drt8?file=/src/App.tsx) to the provided example (removing redundant parts and adding more correct `open` state controlling), everything seems to work as expected and I do not notice any sections being selected. 🤔 Could you confirm if you are still having this issue? And if yes, maybe you could provide a video showcasing the problem? 🙏

@LukasTy, here's a small recording on the version with your tweaks:
![picker](https://github.com/mui/mui-x/assets/62908992/329f2519-78c5-4e58-9c17-20f008607f4b)

Even though it's set to readonly, it is still possible to select & highlight the text. Which was not the case in v5 iirc.

**Comment by LukasTy** [comment]
@seferturan I misunderstood the problem you were facing.
Thank you for sharing a video, it makes things a lot more clear. 👍 
From the video and your description, it seems that you want to make only the `field` read-only, while keeping the picker functionality intact.

Consider making the following change:
```diff
- textField: {
-   inputProps: { readOnly: true },
+ field: {
+   readOnly: true, 
}
```
Does it help you achieve your desired result? 🤔

**Comment by seferturan** [comment]
> @seferturan I misunderstood the problem you were facing. Thank you for sharing a video, it makes things a lot more clear. 👍 From the video and your description, it seems that you want to make only the `field` read-only, while keeping the picker functionality intact.
> 
> Consider making the following change:
> 
> ```diff
> - textField: {
> -   inputProps: { readOnly: true },
> + field: {
> +   readOnly: true, 
> }
> ```
> 
> Does it help you achieve your desired result? 🤔

@LukasTy, thanks, it does :D
