### ISSUE TITLE
When using a ButtonField via forwardRef for DatePicker, PickersPopper doesn't close properly

### ISSUE THREAD

**Issue by pganster** [mui/mui-x#9565]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I've taken the demo from [the documentation](https://mui.com/x/react-date-pickers/custom-field/#using-a-button) to replace the input field with a button and adapted it, so the button accepts the `ref` directly via `forwardRef`.

It nearly works, but the problem persists, that when the date picker is closed, the PickersPopper behaves weird, which can be seen in [the live example](https://codesandbox.io/s/forward-ref-datepicker-popper-close-animation-broken-h7tlqp?file=/demo.tsx).

Steps:
1. Click on the button to choose a date
2. Close the dialog (e.g. by clicking outside of it)

### Current behavior 😯

The PickersPopper loses its anchor, its moved to the top left of the screen, then its moved back to the button, when finally transitioning away 

### Expected behavior 🤔

The PickersPopper should stick to the button when being closed until it has completely transitioned away.

### Context 🔦

I want to get rid off the `any` casting on this line of the demo in the documentation: `slotProps={{ field: { setOpen } as any }}`. To circumvent the limitation of `slotProps` not being able to accept typed custom properties (which was possible with `renderInput`), I supplied my custom component with its properties directly whilst _forwarding_ the `ref`:

```typescript
<DatePicker
      slots={{
        field: (fieldProps) => (
          <ButtonField
            setOpen={setOpen}
            ref={fieldProps.InputProps?.ref}
            {...fieldProps}
          />
        ),
        ...props.slots
      }}
    />
```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Manjaro Linux
  Binaries:
    Node: 20.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 114.0.1
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.6 
    @mui/core-downloads-tracker:  5.13.7 
    @mui/icons-material: ^5.13.7 => 5.13.7 
    @mui/lab: ^5.0.0-alpha.135 => 5.0.0-alpha.135 
    @mui/material: ^5.13.7 => 5.13.7 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.7 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.7 
    @mui/x-date-pickers: ^6.9.1 => 6.9.1 
    @mui/x-date-pickers-pro: ^6.9.1 => 6.9.1 
    @mui/x-license-pro: ^6.9.0 => 6.9.0 
    @types/react: ^18.2.14 => 18.2.14 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.1.6 => 5.1.6 
```
</details>

### Order ID or Support key 💳 (optional)

64616

**Comment by flaviendelangle** [comment]
Hi,

You should never create your `slot` component inside a React component.
Because otherwise, a new component is created on every render and so your field will remount (which may be what's causing your issue).

As for the typing issue, we are trying to find a solution, but it's a complicated topic.

**Comment by pganster** [comment]
I see, since `slot` is not a callable anymore, it will be recreated on every render which is not desired. Yeah the typing issue is really suboptimal, especially if you have more props. But since it's being worked on, I guess this issue can be closed.
Is there any other issue where this problem is being tracked?

**Comment by LukasTy** [comment]
> Is there any other issue where this problem is being tracked?

I couldn't find one. Do we have an issue for it @flaviendelangle and I simply failed to find it?

**Comment by flaviendelangle** [comment]
I don't think we do

**Comment by LukasTy** [comment]
Created #9775 for that very reason.
@pganster feel free to track the referenced issue in order to be notified about our progress on the slot props overrides typing. 😉
