### ISSUE TITLE
How to change The Sorting Label of Column menu for Only Single Column

### ISSUE THREAD

**Issue by KamalEgon** [mui/mui-x#9568]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

<img width="426" alt="QuickNumber" src="https://github.com/mui/mui-x/assets/123153866/51daf7f8-6cff-4a10-b364-63d60f5a3ffa">
<img width="514" alt="Company" src="https://github.com/mui/mui-x/assets/123153866/f242120b-66d5-47f4-a5ea-d4116f555de8">

I want to change the sorting label for single column i have set the locale but it is changing the sorting label for all the column. For Company column attached in screenshot which is string we need to sort it by A to Z  (ASC)and  Z to A (DES) but for Quick Number which is integer value we need to change the text of sorting label column menu to 1 to 100 and 100 to 1 . Kindly provide solution.

**Comment by JerryWu1234** [comment]
let me try it

**Comment by JerryWu1234** [comment]
So do I contribute before have to buy license  if I use pro component?

**Comment by JerryWu1234** [comment]
@m4theushw

**Comment by cherniavskii** [comment]
Hi @JerryWu1234 
You can contribute regardless of whether you have a license or not 🙂
Feel free to open a pull request 👍🏻

**Comment by JerryWu1234** [comment]
> Hi @JerryWu1234 You can contribute regardless of whether you have a license or not 🙂 Feel free to open a pull request 👍🏻

I want to verify if my code has resolved that bug in my local .

**Comment by genepaul** [comment]
Could this approach be applied to the `columnHeaderSortIconLabel` as well? Currently it defaults to `Sort`, and can't be customized per column. It'd be helpful to be able to include the column's header in the title text for accessibility purposes.

**Comment by cherniavskii** [comment]
@genepaul Sure, why not!
Wanna open a PR?

**Comment by genepaul** [comment]
@cherniavskii - I'd love to, but when I try to run `pnpm install` as called out in the contribution guide, I'm getting errors. Is there documentation somewhere about the environment setup I should have?
