### ISSUE TITLE
[pickers] Timezone with Day.js requires to extend dayjs in the same file

### ISSUE THREAD

**Issue by Arkamit** [mui/mui-x#9569]
### Order ID or Support key 💳 (optional)

59954

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We want to introduce the timezone feature in our DatePicker/DateTimePicker component but I am getting the below mentioned error.

![image](https://github.com/mui/mui-x/assets/18526842/0c126bd5-6b66-417f-9a73-6a981d3fefce)

I followed the steps mentioned in the link for Day.js adapter and plugins but still it is throwing the same error. Please find my code below and let me know if I'm missing anything.

```jsx
...
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import dayjs, { Dayjs } from "dayjs";
import utc from "dayjs/plugin/utc";
import timezone from "dayjs/plugin/timezone";
...

dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.tz.setDefault('America/Los_Angeles');

export default function MyTestFunction(): JSX.Element => {
    return (
      return (
        <LocalizationProvider dateAdapter={AdapterDayjs}>
            <Component
                slotProps={{
                    toolbar: {
                        toolbarFormat: includeTime ? "M/d/yyyy hh:mm a" : "M/d/yyyy",
                        hidden: false
                    },
                    popper: popperProps,
                    textField: (props: TextFieldProps) => 
                                    <TextField 
                                        {...props}
                                        .....
                                    />
                }}
                value={value ?? ""}
                ...
                timezone={timeZone ?? 'America/Los_Angeles'}
            />
        </LocalizationProvider>
    )
}

```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    Browser: Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)
    System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 AMD EPYC 7571
    Memory: 12.32 GB / 15.52 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Managers:
    pip2: 18.0 - /usr/bin/pip2
    pip3: 20.2.2 - /usr/bin/pip3
    Yum: 3.4.3 - /usr/bin/yum
  Utilities:
    Make: 3.82 - /usr/bin/make
    Git: 2.32.0 - /usr/bin/git
  Virtualization:
    Docker: 20.10.13 - /usr/bin/docker
  IDEs:
    Nano: 2.9.8 - /usr/bin/nano
    VSCode: 1.79.2 - /home/adutta@huronconsultinggroup.com/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/remote-cli/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.7.10 - /usr/bin/python3
  Databases:
    SQLite: 3.7.17 - /usr/bin/sqlite3
```
</details>

**Comment by alexfauquette** [comment]
@Arkamit Could you provide a reproduction codesandbox of your issue?

I tried from your code example but the issue does not shows up: https://codesandbox.io/s/determined-cdn-3l6ps8?file=/demo.tsx

By the way, I can already spot the `value={value ?? ""}` which should be replaced by a `value={value ?? null}`

**Comment by Arkamit** [comment]
Thanks @alexfauquette for your response. I tried to reproduce this in the codesandbox but couldn't do it like you. But this is happening while running my application locally. So I thought I might be missing any additional configuration which would solve this out.

One thing to mention over here that we are calling this component from another component. Do we need to add the day.js plugins there as well?

`import dayjs, { Dayjs } from "dayjs";
import utc from "dayjs/plugin/utc";
import timezone from "dayjs/plugin/timezone";
...

dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.tz.setDefault('America/Los_Angeles');`

**Comment by Arkamit** [comment]
We had to add the same imports in the place from where we are calling the component from and it fixed the issue.

**Comment by alexfauquette** [comment]
@Arkamit Thanks for the update, when you say

> where we are calling the component from

Is it the file with the `<DatePicker />` or the `<LocalizationProvider />`?

I reopen the issue since it could be interesting that we simplify the fix of this issue with either a more explicit warning or a docs message

**Comment by Arkamit** [comment]
@alexfauquette Sorry I was away for a couple of days. We had to mention it in the file from where we were calling the component.

For example we had to add the below lines in our DatePickerComponent which internally calls MUI's DatePicker
```
import dayjs from 'dayjs';
import utc from "dayjs/plugin/utc";
import timezone from "dayjs/plugin/timezone";
…
export default function DatePickerComponent(…)JSX.Element {
    dayjs.extend(utc);
    dayjs.extend(timezone);
    dayjs.tz.setDefault('America/Los_Angeles');
```


And we had to add the same lines in the test.tsx file from where we are calling the component. If not done it will throw value.isBefore or value.isUTC is not a function.

**Comment by garyb01** [comment]
This sandbox replicates the issue https://codesandbox.io/s/upbeat-hertz-98jqlc?file=/DateField.tsx

**Comment by garyb01** [comment]
Looks like this is the simplest solution, just wrap the `DateTimePicker` with `LocalizationProvider` and use that Component rather than having to chain dayjs calls: https://codesandbox.io/s/pensive-architecture-qmm8r2

**Comment by garyb01** [comment]
Setting the value to an empty string or new Date.toISOString() breaks this sandbox https://codesandbox.io/s/blazing-dream-ytgy2g

**Comment by alexfauquette** [comment]
@Arkamit 
I tried to define component in two files, but it does not reproduce the issue
https://codesandbox.io/s/patient-fog-qyjr5f?file=/demo.tsx

Could you share the lock file of your app? We are wondering if the problem would not be due to duplicate dayjs versions

**Comment by Arkamit** [comment]
@alexfauquette sorry we have already started using the Luxon adapter for timezone handling and this adapter doesn't throw any such issues. But thanks for looking into it.
