### ISSUE TITLE
On disableColumnResize the SVG icon is still visible

### ISSUE THREAD

**Issue by aashay28** [mui/mui-x#9570]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

![Screenshot 2023-07-05 at 12 18 54 PM](https://github.com/mui/mui-x/assets/108337259/af621ee8-6761-49d2-89ab-5fce80823039)

While using disableColumnResize the SVG icon must hide.

```
<DataGridPro
rows={UsersData}
columns={columns}
checkboxSelection
disableColumnResize
/>
```

Right now user feels like, the columns are resizable.

### Current behavior 😯

On disableColumnResize the SVG icon is still visible

### Expected behavior 🤔

On disableColumnResize the SVG icon get hidden

**Comment by MBilalShafi** [comment]
We show header separator in disabled state on hover to let user be aware of the boundaries of a column, you can hide this by [targeting](https://codesandbox.io/s/datagridpremium-basic-forked-84gyxh?file=/src/App.tsx) `gridClasses.columnSeparator`.

```tsx
<DataGridPremium
  rows={rows}
  columns={columns}
  disableColumnResize
  sx={{
    [`.${gridClasses.columnSeparator} svg`]: {
      visibility: "hidden"
    }
  }}
/>
```

Does this serve your need?

**Comment by aashay28** [comment]
@MBilalShafi Yes absolutely correct, but i think the column separator must be hidden when the disableColumnResize option is used.

**Comment by MBilalShafi** [comment]
Thanks for the recommendation, we are already exploring this topic at https://github.com/mui/mui-x/issues/7268 and you are most welcome to share your opinion there. Regarding the current ticket, since you have a workaround for your problem, I'll close this.
