### ISSUE TITLE
Quick filter breaking on grouped rows & some rows with random ids in 6.9.1

### ISSUE THREAD

**Issue by mbond-SCW** [mui/mui-x#9586]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/competent-wiles-yvykm5?file=/demo.tsx

Steps:
1. Use the quick filter box to search any value
2. Observe error: 

<img width="834" alt="Screenshot 2023-07-05 at 11 22 39 AM" src="https://github.com/mui/mui-x/assets/110430690/7a16ed6f-a0ce-41cb-aedb-9810e0f660c0">

Up to version 6.9.0, this behavior wasn't occurring.  The only indication I can see of what might have caused it is possibly the optimizations to filtering https://github.com/mui/mui-x/pull/9254, but I'm not sure.

### Current behavior 😯

Current behavior *appears* to be that when applying a quick (text) filter onto the table, rows that have derived ids (specified by a `getRowId` function) seem to cause issues, resulting in a  'no row found' error.  The two cases where I noticed it happening were:

-  when searching on rows where the id was a UUID generated by a `getRowId` function,
- when searching on rows in a table with some grouping applied, and a composite ID in `getRowId` (e.g [row.userId, row.cid].join('/')

### Expected behavior 🤔

I would expect that quick filtering should still (and always) work with any rows that have valid ids generated either by default (from the row.id field) or by the getRowId function.

### Context 🔦

This popped up as a bug ticket after we updated from 6.9.0 to 6.9.1.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 3.5.1 - ~/.asdf/installs/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.asdf/installs/nodejs/18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: Not Found
    Firefox: 114.0
    Safari: 16.4
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.4 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.134 => 5.0.0-alpha.134 
    @mui/material: ^5.13.6 => 5.13.6 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.5 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.6 
    @mui/x-data-grid:  6.9.1 
    @mui/x-data-grid-premium: ^6.9.1 => 6.9.1 
    @mui/x-data-grid-pro:  6.9.1 
    @mui/x-date-pickers: ^6.9.1 => 6.9.1 
    @mui/x-license-pro: ^6.9.0 => 6.9.0 
    @types/react: ^18.2.7 => 18.2.7 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.1.6 => 5.1.6 
```
</details>

Bug occurred while using Chrome

**Comment by romgrk** [comment]
We are passing autogenerated rows to the user provided `getRowId`, which fails.
