### ISSUE TITLE
[question] Filter and Column Flyout use the same object 

### ISSUE THREAD

**Issue by splitloose-earth** [mui/mui-x#9587]
### Order ID

58632

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I opened another ticket because I forgot to add my order ID and the ticket was auto closed.

https://github.com/mui/mui-x/issues/9399

Ticket 9399 had all the details, but basically The Filter Flyout and Column flyout leverage the same component, which we are trying to separate them, I am unsure if it this was a conscience decision for MUI or oversight... By having them linked, we cannot have the filter open on the filter button and the column select open on the column selection button.

There is code demonstrating this on ticket 9399. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
A related problem has been discussed previously in https://github.com/mui/mui-x/issues/6734, does the [workaround](https://github.com/mui/mui-x/issues/6734#issuecomment-1305461177) mentioned work for you?
