### ISSUE TITLE
Example for non empty DatePicker with validation error message.

### ISSUE THREAD

**Issue by Shawful** [mui/mui-x#9596]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I just don't see one.

### Examples 🌈

-

### Motivation 🔦

-

**Comment by LukasTy** [comment]
Could you clarify what exactly is missing in the documentation?
There [is an example](https://mui.com/x/react-date-pickers/validation/#show-the-error) of how to display an error message. 🤔
