### ISSUE TITLE
[pickers] Add a way to know the hovered day

### ISSUE THREAD

**Issue by jove4015** [mui/mui-x#9599]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to have a new prop on the DateRangePickerDay and PickerDay components, with signature:

dayUnderCursor: TDate | null;

This prop should contain the date that is currently under the mouse cursor.

### Motivation 🔦

Just a small ask - working on some customizations for the DatePicker and I would like to customize the background colors of the Day component based on what date is currently being hovered by the cursor.  

There is already a great example of something similar on the Date Calendar documentation:

https://mui.com/x/react-date-pickers/date-calendar/#custom-day-rendering

This works well but the full week is only selected once you click the date, and that's based on a date passed from outside the component.  I would like the whole week to be highlighted as you hover over it with a more muted color and then have the full highlight once selected.  However, I don't have any way to pass through the current hovered date to the custom day component (at least not that I'm aware of).  **Still, this information seems to be available internally to the component since it must use this information to calculate the value of other props passed through PickerDay.**

This example is for selecting one whole week at a time.  In another use case, we want to be able to select a range of whole weeks.  We plan on using the upcoming MonthRangePicker on your roadmap for the months version of this, but I don't think any week version is forthcoming.    So it would be helpful to have this on DateRangePickerDayProps as well.

If our custom day component could just have the current hovered date passed through as a prop, then I think we could take care of the rest using customization.

### Order ID 💳 (optional)

67744

**Comment by alexfauquette** [comment]
I'm not sure about the props solution since it means updating every button props when the user moves his mouse over the calendar.

Maybe using the `.MuiDayCalendar-weekContainer:hover` selector could be a good start

I also think it's kind o linked with #8868 Especially if instead of `minRange`/`maxRange` it also includes a `fixRange`

**Comment by jove4015** [comment]
Well, from what I can tell there are already props being updated on this Day component when a user mouses over the calendar, so I'm just requesting one more prop so that I can replicate behavior that's only possible internally right now.

It absolutely is related to #8868 for my use case, but there's arguably more that could be done with this.   We also wanted to lock this in to a particular range of week days (M-F), at least in some cases.

**Comment by flaviendelangle** [comment]
In #8257, I'm trying to achieve something similar using `onMouseEnter` and `onMouseLeave`
Would that work for you?

**Comment by jove4015** [comment]
@flaviendelangle your example actually looks a lot closer to what I was aiming for.  Personally, I am skeptical of using the mouseEnter/mouseLeave events, because it can't always be guaranteed that those events will always fire precisely - but it works really well in your example.  Thanks for the tip!!

**Comment by flaviendelangle** [comment]
We are using `onMouseEnter` / `onMouseLeave` internally for the hover behavior of the range components.
So even if we make this information public, it would have the same level of reliability :+1:
