### ISSUE TITLE
Data Grid Pro, We are unable to do the column resizing in our project we can not see any border to increase or decrease the column width.

### ISSUE THREAD

**Issue by 19mohsin58** [mui/mui-x#9600]
### Order ID or Support key 💳 (optional)

#9309

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello Everyone
We are using Data grid pro Licensed we have implemented all the functionalities of data grid pro but we are unable to add the column resizing which is most important for our project. We can't see any option to make it resizeable or any border to increase or decrease the width of column we will be thankfull if we get any solution to this problem.

Mohsin Ali
AliTech Solutions

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
Hi Mohsin,
Have you tried hovering over the header and dragging the resize handle?

![resize](https://github.com/mui/mui-x/assets/12609561/9388515f-7751-4617-9321-3803ed0813b9)

**Comment by 19mohsin58** [comment]
Yeah I've tried that but unable to see any border

**Comment by MBilalShafi** [comment]
Can you share your environment details and shre a codesandbox where the issue is being reproduced? (Output of `npx @mui/envinfo`)
