### ISSUE TITLE
Premium plan user: Aggregation of certain rows in DataGrid table[question] 

### ISSUE THREAD

**Issue by bojanmitic** [mui/mui-x#9602]
### Order ID

69131

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi,

I would like to sum only certain rows in DataGrid table. So I would have couple of rows then sum of those displayed in a row under, and possible one more set with couple of rows and sum. See photo for more details. How to achieve that. I'm using DataGrid premium. 
![Screenshot 2023-07-07 at 8 01 32](https://github.com/mui/mui-x/assets/19996589/af189c45-ec46-4a74-9b46-8cdfeaf11473)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by MBilalShafi** [comment]
This is not possible for the plain data, you can group your data on certain criteria and then you can have aggregation applied on certain groups.

For example, in this demo https://mui.com/x/react-data-grid/aggregation/#usage-with-row-grouping, the movie data is grouped by the Company, and each Group row (under Gross SUM column) shows the Sum of Gross for all the movies produced by that company.

Does this work your way? If not, could you explain your rationale for applying the aggregation on a certain set of rows? A code-sandbox example would be great.
