### ISSUE TITLE
[pickers] There is a transform bug when using TimerPicker and the controller of react-hook-form.

### ISSUE THREAD

**Issue by park-siwan** [mui/mui-x#9603]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://github.com/mui/mui-x/assets/39171933/b355ad57-f1de-42f2-a7ce-ef77b0a7b9a1

### Current behavior 😯

Occurs when used with the controller of the react-hook-form library.
@mui/x-date-pickers-pro": "I'm using ^6.9.2.
The transform of the Digital Clock is set to zero.

Occurs when used with the controller of the react-hook-form library.
![스크린샷 2023-07-07 오후 2 59 07](https://github.com/mui/mui-x/assets/39171933/4c64b5ac-828c-4998-9e98-e619a727572b)

### Expected behavior 🤔

@mui/x-date-pickers-pro": "I'm using ^6.9.2.

### Context 🔦

React-hook-form Controller Application Code
```jsx      
<Controller
        control={control}
        name={'time'}
        render={({ field }) => (
          <TimePicker
            {...field}
            defaultValue={time}
            slots={{
              textField: (props) => (
                <TextField sx={{ width: 100 }} {...props} size='small' />
              ),
            }}
          />
        )}
 />
``` 

It works well when writing as below.
```jsx      
  <TimePicker
    defaultValue={time}
    slots={{
      textField: (props) => (
        <TextField sx={{ width: 100 }} {...props} size='small' />
      ),
    }}
  />

```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: Not Found
    npm: 9.6.4 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-alpha.124 
    @mui/core-downloads-tracker:  5.11.16 
    @mui/icons-material: ^5.10.3 => 5.10.3 
    @mui/material: ^5.11.16 => 5.11.16 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.16 
    @mui/system:  5.11.16 
    @mui/types:  7.2.3 
    @mui/utils:  5.13.6 
    @mui/x-data-grid:  5.17.12 
    @mui/x-data-grid-pro: ^5.17.12 => 5.17.12 
    @mui/x-date-pickers:  6.9.2 
    @mui/x-date-pickers-pro: ^6.9.2 => 6.9.2 
    @mui/x-license-pro: ^5.17.0 => 5.17.12 
    @types/react: 18.0.19 => 18.0.19 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.0.4 => 5.0.4 ```
</details>


### Order ID or Support key 💳 (optional)

#53316

**Comment by LukasTy** [comment]
Hello, could you please double-check if the underlying issue is not the same as https://github.com/mui/mui-x/issues/8850?
It looks like you are defining your `textField` slot component as a render function and thus it is re-created on every render.
Please try defining the slot component outside of your main component and pass it to the slot, it should resolve your problem.

**Comment by park-siwan** [comment]
@LukasTy Thank you for your quick reply. I solved it using slotProps.
```jsx
      <Controller
        control={control}
        name={'time'}
        render={({ field }) => (
          <TimePicker
            {...field}
            label='시간'
            localeText={{ okButtonLabel: '확인' }}
            slotProps={{
              textField: {
                InputProps: { sx: { width: 150 }, size: 'small' },
              },
            }}
          />
        )}
      />
```

**Comment by LukasTy** [comment]
> Thank you for your quick reply. I solved it using slotProps.

Glad to hear it. That's an even better solution! 👌
