### ISSUE TITLE
Datepicker calender background scroll and mouse pointer issue

### ISSUE THREAD

**Issue by sovanjana** [mui/mui-x#9605]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

inspect the page so that part of calendar goes out viewport and then try to change month or click on year selector, then hover over the calendar.

### Current behavior 😯

when datepicker is clicked and calendar popped up, if part of calendar bottom is outside of viewport then on click of year selector or next / prev month button , background is scrolling up continuously. transform of the mentioned tag below is increasing continuously. And mouse hover pointing to different positions on the calendar.

`transform: translate3d(139px, 49437px, 0px);`

within a few seconds it changes from **100px** to **49437px**. 

`<div role="dialog" class="MuiPickersPopper-root css-1anqmj6-MuiPopper-root-MuiPickersPopper-root MuiPopper-root" data-popper-placement="bottom-start" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(139px, 49437px, 0px);">`

### Expected behavior 🤔

when a datepicker is selected even if some part of calender is outside of viewport, calender behaviour should create any issue and mouse hover should point to exact position.

### Your environment 🌎

Google Chrome [last 1 chrome version]

### Order ID or Support key 💳 (optional)

66278

**Comment by alexfauquette** [comment]
Could you provide a recording of the bug if visible on the docs, or a minimal reproduction if not?

I scrolled such that the day picker could not appear at the bottom, but the behavior seems to be expected
https://github.com/mui/mui-x/assets/45398769/0b598e5e-7795-4369-9537-6a374a6ef387
