### ISSUE TITLE
MUI pickers v6 with MUI v5 ?

### ISSUE THREAD

**Issue by Azcanba** [mui/mui-x#9638]
Greetings,

I have a situation where we are using currently in our project MUI v5+. I want to use a digital clock from the date pickers version 6+.

Is it ok to use MUI v5 together with MUI pickers v6 ? Does anyone using it like this ? Or does it break some features from the pickers when there is a version mismatch ?

Thanks for the answer

**Comment by LukasTy** [comment]
Yes, it is completely fine to use `@mui/material@5.x` with `@mui/x-date-pickers@6.x`. 👌 
It's listed in the [peer dependencies](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/package.json#L54).
