### ISSUE TITLE
@mui/x-date-pickers-pro - date range picker flickering

### ISSUE THREAD

**Issue by arjaym-dev** [mui/mui-x#9641]
### Order ID or Support key 💳 (optional)

70493

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I've already search the existing issues but there's nothing like my issues in date picker wherein,

I tried to use the default config of date range picker on local its working, but when its already in dev staging;

- Every time the picker has open it flickers
- Every time of selection date is flickers
- Every time of changing date through manual input it flickers

Why is that happening, 

- There's this case where i let it open then after a seconds it close then open again

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Hello @arjaym-dev 
I'm unable to reproduce the mentioned flickering problem.
What OS and browser are you experiencing it on?
Please provide a minimal reproduction example. A codesandbox would be ideal, you could use [this examle](https://codesandbox.io/s/xlkwjf?file=/demo.tsx) as a base for your demo.
If that's not possible, please at least attach a video and a code snippet of your implementation that you are having problems with. 🙏

**Comment by arjaym-dev** [comment]
I am using macOs and it's happening on chrome, mozilla. i've tested it already with this browser. Though here's the video using browser of chrome https://drive.google.com/file/d/1JJgyd0ZAla7KA0szDl2F2S8zdIFfHGih/view?usp=sharing

But for some reason after reproducing it in codesandbox cant replicate it. Though i'll provide what its look like and behavior on my local it seems perfect https://drive.google.com/file/d/1msNaqle5-UmhuhQWAl5A9KBk9ShxbB0Q/view?usp=sharing


I wasnt able to disclose the code but here's the config props that i've been using 

`let dateRangerPickerProps = {
    open: state.dateRangeOpen,
    sx: {
      width: 355
    },
    localeText: {
      start: ObjCollect.extract( 'start', t ),
      end: ObjCollect.extract( 'end', t )
    },
    value: dateRangePickerValue,
    formatDensity: 'dense',
    format: 'MMM-DD HH:mm',
    currentMonthCalendarPosition: state.dateRangePos,
    maxDate: moment( maxDateSelectable ),
    minDate: moment( threeMonthMinDateSelectable ),
    closeOnSelect: false,
    slotProps: {
      shortcuts: {
        items: DateRangeShortcuts( t )
      },
      actionBar: {
        actions: [ 'cancel' ],
      }
    },
    slots: {
      shortcuts: ( value ) => CustomDateRangeShortcuts( value, shortcutActive ),
      toolbar: () => DateRangePickerToolbar( t ),
      actionBar: ( value ) => CustomActionBar( value, t )
    },
    onChange: ( value ) => dateRangePickerHandleOnChange( value, props, add, state ),
    onAccept: ( value ) => dateRangePickerOnAccept( value, props ),
    onOpen: () => dateRangeOnOpen( state ),
    onClose: () => dateRangeOnClose( state )
  }`

**Comment by LukasTy** [comment]
@arjaym-dev It looks like you are defining your slot components as render functions (they are defined inline). It causes your component to be re-rendered on each render.
Please refactor your code such that your slots would receive a component (function reference), all the extra props that you need can be passed through the appropriate `slotProps` option.

Please let me know if making the above changes fixes your problem. 👍

**Comment by arjaym-dev** [comment]
That doesn't make sense, since as you can see on the video that i've attach there's a date range picker in which its completely no props config no shortcuts, no action bar, no toolbar as is was on the docs. And still it's flickering.

Maybe you can provide an example on codesandbox https://codesandbox.io/s/mui-date-range-8hh684 that can be a reference on proper way of using the slotProps with slots overridable.

Thank you, i'll try to refactor my code base on as what you said.

**Comment by arjaym-dev** [comment]
Hello, it's really hard to reproduce it even in codesandbox and i've also tested it with the same dependency even the version also same on newly created local but its working perfectly fine. Though i also find the same issues way back 2021 and the issue has been close due to lack of information for reproducing the said issues here's the link https://github.com/mui/material-ui/issues/29166

**Comment by arjaym-dev** [comment]
I'll now close this issues, as i also don't have/able to produce the said issues to support my reports.

But i've come to conclusion, to anyone out there experiencing this. You may still achieve the date range picker through picking outs the component used for the date range. 

All you need is;
- Date range field -> MultiInputs for start date and end date
- The static date range
- You're now responsible for the behavior of visibility of it by using the Popper and Fade components they had
