### ISSUE TITLE
[pickers] Failed to resolve import "dayjs/locale/{localeUsed}" from "node_modules/.vite/deps/@mui_x-date-pickers-pro_AdapterDayjs.js?v=90316200"

### ISSUE THREAD

**Issue by FairouzBF** [mui/mui-x#9642]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

I'm using the latest version of dayjs ^1.11.9 and @mui/x-date-pickers-pro ^6.9.2 on react 18.2.0
Testing on localhost in Chrome (Macbook)
I recently changed to using vite (vitejs.dev) so i tried running my existing code but i now get the following error

<img width="1202" alt="Screenshot 2023-07-11 at 11 41 46" src="https://github.com/mui/mui-x/assets/60386124/cb5ca475-6361-4381-b0cb-0e06184b7745">

It's a bug related to packages so i'm not showing my code, but let me know if it's needed.
I tried reverting to older version such as @mui/x-date-pickers-pro 6.6.0, the one that used to have but still got the same issue.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 12.6.7
  Binaries:
    Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
    Yarn: Not Found
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: Not Found
    Safari: 16.5.1
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.6 
    @mui/core-downloads-tracker:  5.13.7 
    @mui/icons-material: ^5.13.7 => 5.13.7 
    @mui/material: ^5.13.7 => 5.13.7 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/styles: ^5.13.7 => 5.13.7 
    @mui/system:  5.13.7 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.7 
    @mui/x-date-pickers:  6.9.2 
    @mui/x-date-pickers-pro: ^6.9.2 => 6.9.2 
    @mui/x-license-pro:  6.9.0 
    @types/react: ^18.0.25 => 18.0.25 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.1.6 => 5.1.6
```
</details>

**Comment by LukasTy** [comment]
Hello @FairouzBF 
Could you please clarify the version of "vite" that you are using?
We've been receiving multiple issues with people running vite v3.x regarding the building and/or bundling.
I was unable to reproduce your issue locally running vite v4.x
If you are on v4, could you please provide a minimal reproduction example?
If it's possible, a codesandbox would be ideal, but a minimal repository is also a great option. 👌

**Comment by FairouzBF** [comment]
Hi @LukasTy thanks for answering so fast,
I'm using vite@4.3.3
I made a quick repo with the packages i'm currently using since codesandbox didn't seem to have the versions of the ones i use : [https://github.com/FairouzBF/test.git](url)

**Comment by LukasTy** [comment]
This is a very peculiar problem that you've caught @FairouzBF
I've managed to identify that the issue coming from the Vite side, so, I'm not sure if we must make a change for this case, but it would definitely make sense to open an issue on their side.
The problem is that Vite identifies a `require` listed in a comment as an actual "require". 🙈 

P.S. A build is working fine, it's just the development run that is bogged, hence, it's not a problem with Rollup.

In the meantime, feel free to use https://www.npmjs.com/package/patch-package to avoid this issue.
You can open the `AdapterDayjs` file in your node_modules, and make the following change (or any other to avoid the `require` in there):
```diff
diff --git a/node_modules/@mui/x-date-pickers/AdapterDayjs/AdapterDayjs.js b/node_modules/@mui/x-date-pickers/AdapterDayjs/AdapterDayjs.js
index b1a0c42..0b442fa 100644
--- a/node_modules/@mui/x-date-pickers/AdapterDayjs/AdapterDayjs.js
+++ b/node_modules/@mui/x-date-pickers/AdapterDayjs/AdapterDayjs.js
@@ -9,7 +9,7 @@ import { buildWarning } from '../internals/utils/warning';
 defaultDayjs.extend(customParseFormatPlugin);
 defaultDayjs.extend(localizedFormatPlugin);
 defaultDayjs.extend(isBetweenPlugin);
-const localeNotFoundWarning = buildWarning(['Your locale has not been found.', 'Either the locale key is not a supported one. Locales supported by dayjs are available here: https://github.com/iamkun/dayjs/tree/dev/src/locale', "Or you forget to import the locale with `require('dayjs/locale/{localeUsed}')`", 'fallback on English locale']);
+const localeNotFoundWarning = buildWarning(['Your locale has not been found.', 'Either the locale key is not a supported one. Locales supported by dayjs are available here: https://github.com/iamkun/dayjs/tree/dev/src/locale', "Or you forget to import the locale from 'dayjs/locale/{localeUsed}'", 'fallback on English locale']);
 const formatTokenMap = {
   // Year
   YY: 'year',
```
And go with the suggested workflow on the `patch-package` doc. 😉

**Comment by LukasTy** [comment]
> Thank you for taking the time to look through this 😄 i'll follow the issue from vite side

Just a heads-up that Vite maintainers have answered and it seems that the issue is originating from your used `commonjs` Vite plugin: https://github.com/vitejs/vite/issues/13831#issuecomment-1635905999.
The open issues seem stale, hence, I've made a fix on our end, which will be released this week.
