### ISSUE TITLE
Dayjs Adapter is showing one day prior in the DatePicker component when default value is set

### ISSUE THREAD

**Issue by Arkamit** [mui/mui-x#9649]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/date-and-time-pickers-forked-f9dqzz?file=/src/App.tsx

Steps:
1. Add dayjs adapter and set a timezone.
2. Add a default value for the date.
3. The component shows 1 day before.

![image](https://github.com/mui/mui-x/assets/18526842/7a1dfc05-40aa-414c-b8cd-0d7a8ea6dc04)

### Current behavior 😯

The date in the component shows 1 day prior to the date set in the default.

### Expected behavior 🤔

The component should show the same date as of the default value.

### Context 🔦

I faced this issue while setting up the timezone for DatePicker component

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: Google Chrome
    System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 AMD EPYC 7571
    Memory: 11.99 GB / 15.52 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Managers:
    pip2: 18.0 - /usr/bin/pip2
    pip3: 20.2.2 - /usr/bin/pip3
    Yum: 3.4.3 - /usr/bin/yum
  Utilities:
    Make: 3.82 - /usr/bin/make
    Git: 2.32.0 - /usr/bin/git
  Virtualization:
    Docker: 20.10.13 - /usr/bin/docker
  IDEs:
    Nano: 2.9.8 - /usr/bin/nano
    VSCode: 1.80.0 - /home/adutta@huronconsultinggroup.com/.vscode-server/bin/660393deaaa6d1996740ff4880f1bad43768c814/bin/remote-cli/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.7.10 - /usr/bin/python3
  Databases:
    SQLite: 3.7.17 - /usr/bin/sqlite3
```
</details>

### Order ID or Support key 💳 (optional)

59954

**Comment by lemmylem** [comment]
When you instantiate the dayjs object, you should either use `dayjs.tz` or use an 8601 ISO string, not just a an arbitrary date string. Doing `dayjs.tz("07/24/2023")`  will solve your issue. If you don't do this, the offset will be of your local time zone instead of the one you specified as default.

I know you use the `timezone` prop here assuming it will do the same thing, but I have personally noticed some weirdness with it.

**Comment by Arkamit** [comment]
Thanks for your response @lemmylem but even after initializing the default value with dayjs.tz it is still showing one day prior in the component. Please see the screenshot below. You can refer to this sandbox as well https://codesandbox.io/s/date-and-time-pickers-forked-f9dqzz?file=/src/App.tsx

![image](https://github.com/mui/mui-x/assets/18526842/0a7a04b0-aee2-4e33-9903-796354127c8c)

**Comment by lemmylem** [comment]
> Thanks for your response @lemmylem but even after initializing the default value with dayjs.tz it is still showing one day prior in the component. Please see the screenshot below. You can refer to this sandbox as well https://codesandbox.io/s/date-and-time-pickers-forked-f9dqzz?file=/src/App.tsx

The sandbox you linked works fine for me:

![eeeface39ba6e3c34bf520d5d549c0ca](https://github.com/mui/mui-x/assets/139143259/b5bd1c12-b990-4370-8707-7d277fe7eae7)

What does it say for "stored value" in your instance?

**Comment by Arkamit** [comment]
@lemmylem 

Stored value: Mon, 24 Jul 2023 01:30:00 GMT

Ah I see why it is different in my system than yours. Actually my system's timezone is in IST and when I changed it to Pacific time it started working like you mentioned above. Can you please change the timezone in your system and confirm me if it can be recreated?

**Comment by lemmylem** [comment]
> @lemmylem
> 
> Stored value: Mon, 24 Jul 2023 01:30:00 GMT
> 
> Ah I see why it is different in my system than yours. Actually my system's timezone is in IST and when I changed it to Pacific time it started working like you mentioned above. Can you please change the timezone in your system and confirm me if it can be recreated?

That's weird. I changed my time zone to `Asia/Calcutta` and it works just fine. Your local browser settings should have no impact on this.

![3cf6242cf8d0959feaf8bf7ad676b8fd](https://github.com/mui/mui-x/assets/139143259/a7ac66a0-847e-4a23-8134-ac9846c4a556)

Also, I would rewrite `07/24/2023` to `2023-07-24` to follow proper ISO 8601 format. Perhaps that could be an issue? I would always input the date value as either a unix or ISO 8601 string.

**Comment by Arkamit** [comment]
Rewriting the date in ISO 8601 format indeed fixed the issue. Thanks @lemmylem
