### ISSUE TITLE
[DataGrid] Exclude hidden columns from quick filtering by default

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#9655]
When using [quick filter](https://mui.com/x/react-data-grid/filtering/quick-filter/), it searches through hidden columns by default.
Sometimes it could be confusing to a user searching for a value:

Why does this row pass the filter?
<img width="613" src="https://github.com/mui/mui-x/assets/13808724/0e65b76e-f0a8-451e-85b7-93e946975b19">

Because it has a hidden column with a matching value:
<img width="613" src="https://github.com/mui/mui-x/assets/13808724/48ca1181-3b9d-4d5e-9c09-d0af664b88de">

In https://github.com/mui/mui-x/pull/9610 we added an option to exclude hidden columns in quick filter.
I think we should do this by default in v7.

**Comment by YawHB** [comment]
How do I include hidden field now, then?
I want to be able to search on the row "nickname", without showing the column. 

I added filter.filterModel.quickFilterExcludeHiddenColumns, and set it to be false, but nothing seems to happen.
Could it be because i've implemented a costum datagrid? 
```

 initialState={{
            filter: {
              filterModel: {
                items: [],
                quickFilterExcludeHiddenColumns: false,
              },
            },
          }}
```

**Comment by YawHB** [comment]
Never mind. I found out that, because I use the custom usehook, "`useLocalStorage`" from TS, i needed to set `quickFilterExcludeHiddenColumns` to false as part of the initial state. 
Then I of course have to apply onFilterModelChange, in order to update the state of local storage: ```
onFilterModelChange={(filterModel) => {
            setFilterModel(filterModel)
          }}
```
And that should be it :)
