### ISSUE TITLE
[pickers] Year/Month button locale issue

### ISSUE THREAD

**Issue by erkamdemirci** [mui/mui-x#9663]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

![Screenshot 2023-07-13 121234](https://github.com/mui/mui-x/assets/5718991/ec5282a8-fef0-4095-b9c4-306dc749e355)

As seen in the picture, when I change the language from TR to EN, the letters showing the days of the week are updated, but the text of the button does not change until I refresh the page. 

I use dayjs with next-i18next and this is my language switching function; 

const handleLanguageChange = (newLanguage) => {
    i18n.changeLanguage(newLanguage);
    dayjs.locale(newLanguage);
  };

### Current behavior 😯

When the application language is changed, the Year/Month button text is not updated without refreshing the page.

### Expected behavior 🤔

When the locale changes, the letters showing the days of the week change and the Year/Month button text needs to be updated.

### Your environment 🌎

 @mui/core-downloads-tracker:  5.13.0
    @mui/icons-material: ^5.11.16 => 5.11.16
    @mui/material: ^5.12.3 => 5.13.0
    @mui/private-theming:  5.12.3
    @mui/styled-engine:  5.12.3
    @mui/system:  5.12.3
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-date-pickers: ^6.3.1 => 6.4.0
    @types/react:  17.0.59
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: ^5.3.10 => 5.3.10
    typescript:  5.0.4

**Comment by LukasTy** [comment]
Could you please provide a reproduction example showcasing the problem you are having?
Maybe you are forgetting to update the `adapterLocale` on the `LocalizationProvider` component?
[Here is](https://codesandbox.io/s/xenodochial-williams-f5c8sf?file=/demo.tsx) a bit modified working example from our doc.

**Comment by erkamdemirci** [comment]
I apologise for keeping you busy. I had a LocalisationProvider definition in _app.js;
`<LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale={router.locale}>...</LocalizationProvider>`

but I redefined the component where I used it;
`<LocalisationProvider dateAdapter={AdapterDayjs}>...</LocalizationProvider>`

when I deleted it. Thanks for making me pay attention to **LocalisationProvider**.

Have a good work.
