### ISSUE TITLE
[DataGrid] No row with id # found when quick filter used and row deleted

### ISSUE THREAD

**Issue by AkitoItashi** [mui/mui-x#9666]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

EDIT: simplified example: https://codesandbox.io/s/practical-pasteur-hlknzw?file=/src/demo.tsx
Link to live example: https://codesandbox.io/s/fervent-rain-whg9tt

Steps:
1. Search for "TEST" in the quick search and hit the ENTER key
2. Delete one of the entries and it will crash
3.

### Current behavior 😯

After the row got removed from the "rows"-prop, the whole projects crashes with the error: "No row with id # found".
But this only happens, when you have applied a quick filter...without a quick filter it will work...

That didn't happen in version 6.9.1, which I had installed before

### Expected behavior 🤔

It should work ;)

### Context 🔦

We use the DataGrid for showing, editing and handling data for cars...
The use case is, that you can search for an accessoire and then edit or delete it...

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  Browser used: Chrome (arm64) 114.0.5735.198

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 18.16.1 - /usr/bin/node
    Yarn: 3.6.1 - /usr/bin/yarn
    npm: 9.5.1 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.7 
    @mui/core-downloads-tracker:  5.14.0 
    @mui/icons-material: ^5.14.0 => 5.14.0 
    @mui/lab: ^5.0.0-alpha.136 => 5.0.0-alpha.136 
    @mui/material: ^5.14.0 => 5.14.0 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/styles: ^5.14.0 => 5.14.0 
    @mui/system:  5.14.0 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.7 
    @mui/x-data-grid:  6.10.0 
    @mui/x-data-grid-pro: 6.10.0 => 6.10.0 
    @mui/x-date-pickers:  6.10.0 
    @mui/x-date-pickers-pro: 6.10.0 => 6.10.0 
    @mui/x-license-pro: ^6.10.0 => 6.10.0 
    @types/react:  18.2.14 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.1.6 => 5.1.6
</details>

### Order ID or Support key 💳 (optional)

51673

**Comment by romgrk** [comment]
I wanted to avoid having a call to `Object.values(...)` inside the filter function, it's an expensive operation.

@cherniavskii Do you see any place where we could keep a ref to the original list of items? I had it in the caches [here](https://github.com/mui/mui-x/pull/9254#discussion_r1236760224).

**Comment by cherniavskii** [comment]
@romgrk What do you think about this?

```diff
diff --git a/packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx b/packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
index 653a289f3..ba05660aa 100644
--- a/packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
+++ b/packages/grid/x-data-grid/src/hooks/features/filter/useGridFilter.tsx
@@ -1,5 +1,6 @@
 import * as React from 'react';
 import { unstable_useEnhancedEffect as useEnhancedEffect } from '@mui/utils';
+import { defaultMemoize } from 'reselect';
 import { GridEventListener } from '../../../models/events';
 import { DataGridProcessedProps } from '../../../models/props/DataGridProps';
 import { GridPrivateApiCommunity } from '../../../models/api/gridApiCommunity';
@@ -389,10 +390,14 @@ export const useGridFilter = (
     [props.slots.filterPanel, props.slotProps?.filterPanel],
   );
 
-  const dataRowIdToIdLookup = apiRef.current.state.rows.dataRowIdToModelLookup;
-  const rows = React.useMemo(() => Object.values(dataRowIdToIdLookup), [dataRowIdToIdLookup]);
   const { getRowId } = props;
 
+  const getRowsRef = React.useRef(
+    defaultMemoize((lookup: typeof apiRef.current.state.rows.dataRowIdToModelLookup) => {
+      return Object.values(lookup);
+    }),
+  );
+
   const flatFilteringMethod = React.useCallback<GridStrategyProcessor<'filtering'>>(
     (params) => {
       if (props.filterMode !== 'client' || !params.isRowMatchingFilters) {
@@ -412,6 +417,8 @@ export const useGridFilter = (
         passingQuickFilterValues: null,
       };
 
+      const rows = getRowsRef.current(apiRef.current.state.rows.dataRowIdToModelLookup);
+
       for (let i = 0; i < rows.length; i += 1) {
         const row = rows[i];
         const id = getRowId ? getRowId(row) : row.id;
@@ -440,7 +447,7 @@ export const useGridFilter = (
         filteredDescendantCountLookup: {},
       };
     },
-    [apiRef, rows, props.filterMode, getRowId],
+    [apiRef, props.filterMode, getRowId],
   );
 
   useGridRegisterPipeProcessor(apiRef, 'columnMenu', addColumnMenuItem);

```

**Comment by romgrk** [comment]
> I tested the diff below and it also works:

One of the performance optimizations in the filtering work is to avoid `dataRowIdToModelLookup[rowId]`, because for a large object the performance quickly gets bad. We iterate rows directly to avoid that cost.
