### ISSUE TITLE
[DataGridPro] Custom cell component is not used for grouping cell

### ISSUE THREAD

**Issue by jfsaman** [mui/mui-x#9669]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm having the same issue that was resolved for this topic for DataGrid Premium, is there any solution planned for Datagrid Pro as well?

Related issue: https://github.com/mui/mui-x/issues/6689

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @jfsaman 
Can you provide a minimal reproduction example?
Thanks!

**Comment by AdamJPcars** [comment]
@cherniavskii Could you please have a look at https://github.com/mui/mui-x/issues/6689
this problem is explain for good there. and it still hasn't been resolved

**Comment by cherniavskii** [comment]
@AdamJPcars Could you open a new issue with a minimum reproduction example? Thanks!

**Comment by AdamJPcars** [comment]
@cherniavskii the minimum reproduction is already described in https://github.com/mui/mui-x/issues/6689
