### ISSUE TITLE
[DatePicker] Error when using with AdapterMoment

### ISSUE THREAD

**Issue by matpag** [mui/mui-x#9683]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Hello everyone,
we have a problem with `DatePicker` used with `AdapterMoment`.
I've cloned a MUI sample took directly from the page and just changed to use the AdapterMoment.

This is the link: https://codesandbox.io/s/priceless-shtern-lyd738?file=/demo.tsx

The error I got is: `value.isUTC is not a function`

Are we doing something wrong? If not, is there a way to solve this for moment or we just have to switch to another adapter?

Thank you,
Mat

### Your environment 🌎

libraries:

```
"@mui/material": "^5.14.0",
"@mui/x-date-pickers": "^6.10.0",
"moment": "^2.29.4"
```

**Comment by LukasTy** [comment]
Everything seems to be working as expected. 👌 
You have changed the adapter, but forgot to update the values to be created with the `moment` constructor instead of `dayjs`. 😉

**Comment by matpag** [comment]
Sorry, i was so dumb to miss that :(

Thank you
