### ISSUE TITLE
[DataGridPro] DataGridPro, I want to display three level data from the API response.

### ISSUE THREAD

**Issue by niralivasoya** [mui/mui-x#9719]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Expected behavior 🤔

I am using DataGridPro for displaying nested-level data. I want to show three-level data. I want a structure like, when I click on any row it will display data the same as the data grid and in that table again I want again nesting on row expansion. something like this,

![image](https://github.com/mui/mui-x/assets/32123446/fc2f5b9b-be63-4362-a01f-bd3144b56d6c)

How can I do this using DataGridPro? Can anyone please help me with this?

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by niralivasoya** [comment]
@flaviendelangle Can you look into this, if possible can you please provide an example for this? Thanks

**Comment by romgrk** [comment]
Duplicate of #9718. Can you close one of the issues?

**Comment by romgrk** [comment]
Do you have a live example? [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) _may_ be a good starting point. Thank you!

**Comment by niralivasoya** [comment]
@romgrk Thank you for your help. I find the solution for this type of structure. I used `getDetailPanelContent` to show related tables, it helps to design a structure of nested level.
