### ISSUE TITLE
[DataGrid] How to use MUI X DataGrid without React?

### ISSUE THREAD

**Issue by doberkofler** [mui/mui-x#9721]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to also use the MUI X DatGrid in a TypeScript web application that is not fully react based but sometimes only uses stand-alone React components.

Unfortunately I did not find any specific documentation on how to use the MUI X DatGrid as a stand-alone React component and would suggest to improve this use case.

The following [example code][1] shows a prototype on how to create a functional API that does seem to work but is neither very clean (setTimeout) nor very self explanatory.

The idea is to use the GridApi to functionally interact with the grid component but the solution I came up with seems pretty ugly and I'm wondering:
- is this use case documented somewhere and i just missed it?
- is there a cleaner way to do this?
- do i really need setTimeout before I can retrieve the `GridApi` or did i misunderstand the API?

  [1]: https://codesandbox.io/s/mystifying-hill-kgrh25?file=/demo.tsx

### Examples 🌈

```typescript
import * as React from 'react';
import ReactDOM from 'react-dom/client';
import {StyledEngineProvider} from '@mui/material/styles';
import {DataGrid, useGridApiRef} from '@mui/x-data-grid';

import type {GridApi} from '@mui/x-data-grid';
export type apiRefType = React.MutableRefObject<GridApi>;

type GridPropsType = {
  hideFooter: boolean,
  setApiRef: (ref: apiRefType) => void,
};


const Grid = ({setApiRef}: GridPropsType): JSX.Element => {
	const apiRef = useGridApiRef();

	setApiRef(apiRef);

	return (
		<React.StrictMode>
			<StyledEngineProvider injectFirst>
				<div style={{height: '100%', width: '100%'}}>
					<DataGrid columns={[]} rows={[]}apiRef={apiRef} />
				</div>
			</StyledEngineProvider>
		</React.StrictMode>
	);
};

export const renderGrid = async (target: HTMLElement, hideFooter: boolean): Promise<apiRefType> => {
	let apiRef: apiRefType | null = null;
	const setApiRef = (ref: apiRefType): void => {
		apiRef = ref;
	};

	return new Promise((resolve) => { // eslint-disable-line promise/avoid-new
		ReactDOM.createRoot(target).render(<Grid hideFooter={hideFooter} setApiRef={setApiRef}/>);
		setTimeout(() => {
			if (apiRef === null) {
				throw new Error('apiref was not initialized');
			}

			resolve(apiRef);
		}, 0);
	});
};

```

### Motivation 🔦

I would like to also use MUI X DatGrid as a stand-alone React component in a non-React application.

**Comment by oliviertassinari** [comment]
> I would like to also use the MUI X DatGrid in a TypeScript web application that is not fully react based but sometimes only uses stand-alone React components.

@doberkofler What technology is the rest of your page built with? Do you plan to migrate to a specific technology in the future?

> do i really need setTimeout before I can retrieve the GridApi or did i misunderstand the API?

This is a ref, implemented with useImperativeHandle

---

For MUI, I have added this input to 
https://www.notion.so/mui-org/Other-framework-Angular-Vue-Svelte-b3473f1dae484ae59b708569b1fd6e8b

**Comment by doberkofler** [comment]
@m4theushw
Very clean solution.
Maybe it would help to have this use case documented.
Thank you!

**Comment by oliviertassinari** [comment]
I have tweaked a bit the example to support all the props as options: 

```jsx
import { renderGrid } from "./demo";

const cols = [{ field: "username" }, { field: "age" }];
const rows = [{ id: 1, username: "@MUI", age: 20 }];

(async () => {
  const target = document.getElementById("root");
  const gridApi = await renderGrid(target, {
    hideFooter: true
  });
  gridApi.current.updateColumns(cols);
  gridApi.current.updateRows(rows);
})();
```

https://codesandbox.io/s/nifty-gauss-w3p3qx?file=/demo.tsx:0-1303

```jsx
import * as React from "react";
import * as ReactDOM from "react-dom/client";
import { StyledEngineProvider } from "@mui/material/styles";
import { DataGrid, DataGridProps, useGridApiRef } from "@mui/x-data-grid";
import type { GridApi } from "@mui/x-data-grid";

type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;

export type apiRefType = React.MutableRefObject<GridApi>;

type GridPropsType = {
  options: Optional<DataGridProps, "rows" | "columns">;
  setApiRef: (ref: apiRefType) => void;
};

const Grid = ({ setApiRef, options }: GridPropsType): JSX.Element => {
  const apiRef = useGridApiRef();

  React.useLayoutEffect(() => {
    setApiRef(apiRef);
  }, [setApiRef, apiRef]);

  return (
    <React.StrictMode>
      <StyledEngineProvider injectFirst>
        <div style={{ height: "100%", width: "100%" }}>
          <DataGrid columns={[]} rows={[]} apiRef={apiRef} {...options} />
        </div>
      </StyledEngineProvider>
    </React.StrictMode>
  );
};

export const renderGrid = async (
  target: HTMLElement,
  options: GridPropsType["options"]
): Promise<apiRefType> => {
  return new Promise((resolve) => {
    // eslint-disable-line promise/avoid-new
    ReactDOM.createRoot(target).render(
      <Grid options={options} setApiRef={resolve} />
    );
  });
};
```

This makes it closer to the use like this: https://ag-grid.com/javascript-data-grid/getting-started/

---

> Maybe it would help to have this use case documented

I have changed the title so it will better surface when developers search on Google. Personally, I think that we could close this issue, waiting for more users asking about it.

**Comment by doberkofler** [comment]
Very nice. I think this could help others and you might want to include it in your official documentation.

**Comment by tispratik** [comment]
I am sorry, I did not understand the conversation technicality completely. Does this mean that the MUI Data Grid can be used as a standalone to be embedded inside another app like Angular/Svelte?

**Comment by doberkofler** [comment]
Yes, although I wanted to use it in a vanilla JavaScript application.
