### ISSUE TITLE
[data grid] Cell selection cursor issue

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#9726]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://mui.com/x/react-data-grid/cell-selection/

Unless the cell is editable `editMode="row"`or column with `editable: true`, when `unstable_cellSelection` is enabled, seeing the text cursor is confusing: <img width="64" alt="Screenshot 2023-07-18 at 23 30 50" src="https://github.com/mui/mui-x/assets/3165635/f28bedb9-0c3c-4217-a300-54294c341f1b">

It feels like I can act on this as a text, no I can't.

https://github.com/mui/mui-x/assets/3165635/9ce8ae18-accd-4866-a825-699a0e67a1f4

### Expected behavior 🤔

I would expect `cursor: default`.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by gitstart** [comment]
@oliviertassinari we would like to pick this up
