### ISSUE TITLE
Clipboard import cuts off at 100 rows.

### ISSUE THREAD

**Issue by itsjaked** [mui/mui-x#9732]
### Order ID

67770

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm pasting from an Excel file, and when selecting the first row and pasting, only 100 entries are pasted in. If I CTR-A and then paste, they all come in. Here's a quick video example: https://www.loom.com/share/64e5508ca48c4b27a65cbde2fb5377a4

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by gitstart** [comment]
@itsjaked @gzrae @m4theushw we would like to pick this up
