### ISSUE TITLE
[DataGrid] Improve typing of `GridColDef['type']`

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#9735]
# The problem

From https://github.com/mui/mui-x/issues/4769#issuecomment-1642592703

> There's a suggestion to remove the columnTypes prop which would make the warning useless

I think that we should stay attentive in cases where developers have typos in their `type` property, trying to use one of https://mui.com/x/react-data-grid/column-definition/#column-types

<img width="346" alt="Screenshot 2023-07-19 at 20 42 34" src="https://github.com/mui/mui-x/assets/3165635/e44943d5-8a9c-43f4-b656-58043e85c879">

If we assume that TypeScript is meant to give coverage, then indeed, the warning has the potential to be useless. However, TypeScript doesn't fail today:

<img width="352" alt="Screenshot 2023-07-19 at 20 52 56" src="https://github.com/mui/mui-x/assets/3165635/775e5841-e7cb-4561-8c08-b7a961717092">

https://codesandbox.io/s/happy-wood-mp3mt6?file=/demo.tsx

I imagine because of the permissive type (`string`):

https://github.com/mui/mui-x/blob/6894da161a915847e7a635f5cd9266d6a2cba7c5/packages/grid/x-data-grid/src/models/colDef/gridColType.ts#L1-L13

Should we narrow it down?

**Comment by cherniavskii** [comment]
> I imagine because of the permissive type (string):

Yes, this is exactly the reason.

> Should we narrow it down?

I think we can change this in v7. The challenge here is that we use custom column types internally for column identification, like here:
https://github.com/mui/mui-x/blob/62725ed4ba26788f454e93a73c7273ac54d762fd/packages/grid/x-data-grid/src/hooks/features/keyboardNavigation/useGridKeyboardNavigation.ts#L633

I imagine we could use `field` instead in the use case above, but custom column types could still be useful.

Maybe Instead of accepting any `string` we could use TS module augmentation?

```ts
export interface GridColTypeOverrides {}
export type GridColType = GridNativeColTypes | keyof GridColTypeOverrides;

declare module '@mui/x-data-grid' {
  export interface GridColTypeOverrides {
    customType: string;
  }
}

```

**Comment by cherniavskii** [comment]
@oliviertassinari Yes, that would work for our custom types. We can add support for user-defined custom types later if needed 👍

**Comment by oliviertassinari** [comment]
> We can add support for user-defined custom types later if needed

Is this still possible? I thought it got discontinued with https://github.com/mui/mui-x/pull/7309

**Comment by cherniavskii** [comment]
You can still do this:

```ts
const column: GridColDef = {
  type: 'customType',
  field: 'someField',
  editable: true,
}
```

But I don't think that our users do this often.

**Comment by oliviertassinari** [comment]
> You can still do this:

Oh, I see. I didn't realize this. Module augmentation sounds nice 👍.
