### ISSUE TITLE
React does not recognize the `setRowModesModel` and `setRows` prop on a DOM element 

### ISSUE THREAD

**Issue by varndellwagglebee** [mui/mui-x#9739]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://codesandbox.io/s/v6x2dc?file=/demo.tsx

Steps:
1. Create a custom toolbar and pass the columns and groups
2. include full CRUD

### Current behavior 😯

The custom toolbar works but get react warnings:

Warning: React does not recognize the `setRowModesModel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setrowmodesmodel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

AND

Warning: React does not recognize the `setRows` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setrows` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Expected behavior 🤔

No react warnings.

### Context 🔦

Clearing up react warnings.

### Your environment 🌎

<details>
  ```
OS: windows 11
Chrome: Version 114.0.5735.199

   @mui/material: ^5.12.0 => 5.13.6
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.6
    @mui/types:  7.2.4
    @mui/utils:  5.13.6
    @mui/x-data-grid:  6.9.2
    @mui/x-data-grid-premium: ^6.9.2 => 6.9.2
    @mui/x-data-grid-pro:  6.9.2
    @mui/x-license-pro:  6.9.0
    @types/react: ^18.2.14 => 18.2.14
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.1.6 => 5.1.6
```
</details>

**Comment by varndellwagglebee** [comment]
Hello,

 

Here is the error message.

**Comment by romgrk** [comment]
@varndellwagglebee Your answer doesn't include the error message. If you have trouble answering by email, use the github web interface.

**Comment by varndellwagglebee** [comment]
react-dom.development.js:86 Warning: React does not recognize the `setRowModesModel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setrowmodesmodel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at GridToolbarContainer2 (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:4604:5)
    at CustomToolbar
    at GridHeader (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:8943:21)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at GridRoot2 (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:4418:21)
    at GridContextProvider (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:9692:3)
    at DataGridPremium (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:25997:17)
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Box2 (https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:6956:19)
    at DynamicGrid (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:27197:26)
    at DataGridProvider (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:27525:3)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Grid2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:12807:22)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Grid2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:12807:22)
    at TemplatePreview (https://localhost:3000/build/routes/glyphs.$templateId.details.preview-IOWO2EK4.js:27547:26)
    at RemixRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:4690:3)
    at RenderedRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:2978:5)
    at Outlet (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3233:26)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Grid2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:12807:22)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Grid2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:12807:22)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Grid2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:12807:22)
    at TemplateDetail (https://localhost:3000/build/routes/glyphs.$templateId.details-2CZNAOWN.js:47:17)
    at RemixRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:4690:3)
    at RenderedRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:2978:5)
    at RenderErrorBoundary (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3380:9)
    at Outlet (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3233:26)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Paper2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:6631:17)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Grid2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:12807:22)
    at div
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at Grid2 (https://localhost:3000/build/_shared/chunk-IDKR6RYS.js:12807:22)
    at SidebarOverview (https://localhost:3000/build/_shared/chunk-ZBOVODCB.js:62:3)
    at FunctionOverview (https://localhost:3000/build/routes/glyphs-H5VXYQYQ.js:55:26)
    at RemixRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:4690:3)
    at RenderedRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:2978:5)
    at RenderErrorBoundary (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3380:9)
    at Outlet (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3233:26)
    at main
    at div
    at div
    at Main
    at body
    at html
    at https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:1646:49
    at App
    at RemixRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:4690:3)
    at RenderedRoute (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:2978:5)
    at RenderErrorBoundary (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3380:9)
    at DataRoutes (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3227:5)
    at Router (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3237:15)
    at RouterProvider (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:3176:5)
    at RemixErrorBoundary (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:4284:5)
    at RemixBrowser (https://localhost:3000/build/_shared/chunk-HVSEUK3S.js:6085:40)
    at ThemeProvider2 (https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:7501:5)
    at ThemeProvider3 (https://localhost:3000/build/_shared/chunk-MJECW6Z7.js:7586:5)

**Comment by romgrk** [comment]
Is the live example an accurate reproduction of your code? Can you reproduce the same issue with the live example? If you can't, then it probably means that the live example doesn't reproduce the issue and you'll need to adjust it before we can help.

**Comment by varndellwagglebee** [comment]
I didn't save it.  Let me create the code in the codesandbox.

**Comment by varndellwagglebee** [comment]
Here is the link https://codesandbox.io/s/material-example-35qtql?file=/demo.tsx:0-8152

Just in case, here is the code:

import * as React from "react";
import Box from "@mui/material/Box";
import { alpha, Button, ButtonProps, styled } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import EditIcon from "@mui/icons-material/Edit";
import DeleteIcon from "@mui/icons-material/DeleteOutlined";
import SaveIcon from "@mui/icons-material/Save";
import CancelIcon from "@mui/icons-material/Close";
import {
  GridRowsProp,
  GridRowModesModel,
  GridRowModes,
  GridColDef,
  GridToolbarContainer,
  GridActionsCellItem,
  GridEventListener,
  GridRowId,
  GridRowModel,
  GridRowEditStopReasons,
  GridCsvExportOptions,
  DataGridPremium,
  GridCsvExportMenuItem,
  GridToolbarExportContainer,
  gridClasses,
  useGridApiRef
} from "@mui/x-data-grid-premium";
import {
  randomCreatedDate,
  randomTraderName,
  randomId,
  randomArrayItem
} from "@mui/x-data-grid-generator";

const roles = ["Market", "Finance", "Development"];
const randomRole = () => {
  return randomArrayItem(roles);
};

const initialRows: GridRowsProp = [
  {
    id: randomId(),
    name: randomTraderName(),
    age: 25,
    joinDate: randomCreatedDate(),
    role: randomRole()
  },
  {
    id: randomId(),
    name: randomTraderName(),
    age: 36,
    joinDate: randomCreatedDate(),
    role: randomRole()
  },
  {
    id: randomId(),
    name: randomTraderName(),
    age: 19,
    joinDate: randomCreatedDate(),
    role: randomRole()
  },
  {
    id: randomId(),
    name: randomTraderName(),
    age: 28,
    joinDate: randomCreatedDate(),
    role: randomRole()
  },
  {
    id: randomId(),
    name: randomTraderName(),
    age: 23,
    joinDate: randomCreatedDate(),
    role: randomRole()
  }
];
interface ToolbarPropsOverrides {
  columns: string[];
  setRows: (newRows: (oldRows: GridRowsProp) => GridRowsProp) => void;
  setRowModesModel: (
    newModel: (oldModel: GridRowModesModel) => GridRowModesModel
  ) => void;
  grouping: string[];
}

const csvOptions: GridCsvExportOptions = {
  delimiter: ",",
  fileName: "testData",
  includeHeaders: true
};

function CsvExportButton(props: ButtonProps) {
  return (
    <GridToolbarExportContainer {...props}>
      <GridCsvExportMenuItem options={csvOptions} />
    </GridToolbarExportContainer>
  );
}

function EditToolbar(props: ToolbarPropsOverrides) {
  const { setRows, setRowModesModel, columns } = props;
  const id = Math.floor(Math.random() * 10000);

  let newRow: any = [];
  Array.from(columns).map(function (x) {
    newRow.push({ [x]: "" });
  });

  const handleClick = () => {
    setRows((oldRows) => [
      ...oldRows,
      {
        id,
        ...newRow,
        isNew: true
      }
    ]);
    setRowModesModel((oldModel) => ({
      ...oldModel,
      [id]: { mode: GridRowModes.Edit }
    }));
  };

  return (
    <Button size="small" startIcon={<AddIcon />} onClick={handleClick}>
      Add record
    </Button>
  );
}

function CustomToolbar(props: ToolbarPropsOverrides) {
  return (
    <GridToolbarContainer {...props}>
      <CsvExportButton />
      <EditToolbar {...props} />
    </GridToolbarContainer>
  );
}

const ODD_OPACITY = 0.1;

const StripedDataGrid = styled(DataGridPremium)(({ theme }) => ({
  [`& .${gridClasses.row}.odd`]: {
    backgroundColor: theme.palette.grey[200],
    "&:hover, &.Mui-hovered": {
      backgroundColor: alpha(theme.palette.primary.main, ODD_OPACITY),
      "@media (hover: none)": {
        backgroundColor: "transparent"
      }
    },
    "&.Mui-selected": {
      backgroundColor: alpha(
        theme.palette.primary.main,
        ODD_OPACITY + theme.palette.action.selectedOpacity
      ),
      "&:hover, &.Mui-hovered": {
        backgroundColor: alpha(
          theme.palette.primary.main,
          ODD_OPACITY +
            theme.palette.action.selectedOpacity +
            theme.palette.action.hoverOpacity
        ),
        // Reset on touch devices, it doesn't add specificity
        "@media (hover: none)": {
          backgroundColor: alpha(
            theme.palette.primary.main,
            ODD_OPACITY + theme.palette.action.selectedOpacity
          )
        }
      }
    }
  }
}));

export default function FullFeaturedCrudGrid() {
  const [rows, setRows] = React.useState(initialRows);
  const [rowModesModel, setRowModesModel] = React.useState<GridRowModesModel>(
    {}
  );
  const apiRef = useGridApiRef();

  const handleRowEditStop: GridEventListener<"rowEditStop"> = (
    params,
    event
  ) => {
    if (params.reason === GridRowEditStopReasons.rowFocusOut) {
      event.defaultMuiPrevented = true;
    }
  };

  const handleEditClick = (id: GridRowId) => () => {
    setRowModesModel({ ...rowModesModel, [id]: { mode: GridRowModes.Edit } });
  };

  const handleSaveClick = (id: GridRowId) => () => {
    setRowModesModel({ ...rowModesModel, [id]: { mode: GridRowModes.View } });
  };

  const handleDeleteClick = (id: GridRowId) => () => {
    setRows(rows.filter((row) => row.id !== id));
  };

  const handleCancelClick = (id: GridRowId) => () => {
    setRowModesModel({
      ...rowModesModel,
      [id]: { mode: GridRowModes.View, ignoreModifications: true }
    });

    const editedRow = rows.find((row) => row.id === id);
    if (editedRow!.isNew) {
      setRows(rows.filter((row) => row.id !== id));
    }
  };

  const processRowUpdate = (newRow: GridRowModel) => {
    const updatedRow = { ...newRow, isNew: false };
    setRows(rows.map((row) => (row.id === newRow.id ? updatedRow : row)));
    return updatedRow;
  };

  const handleRowModesModelChange = (newRowModesModel: GridRowModesModel) => {
    setRowModesModel(newRowModesModel);
  };

  const columns: GridColDef[] = [
    { field: "name", headerName: "Name", width: 180, editable: true },
    {
      field: "age",
      headerName: "Age",
      type: "number",
      width: 80,
      align: "left",
      headerAlign: "left",
      editable: true
    },
    {
      field: "joinDate",
      headerName: "Join date",
      type: "date",
      width: 180,
      editable: true
    },
    {
      field: "role",
      headerName: "Department",
      width: 220,
      editable: true,
      type: "singleSelect",
      valueOptions: ["Market", "Finance", "Development"]
    },
    {
      field: "actions",
      type: "actions",
      headerName: "Actions",
      width: 100,
      cellClassName: "actions",
      getActions: ({ id }) => {
        const isInEditMode = rowModesModel[id]?.mode === GridRowModes.Edit;

        if (isInEditMode) {
          return [
            <GridActionsCellItem
              icon={<SaveIcon />}
              label="Save"
              sx={{
                color: "primary.main"
              }}
              onClick={handleSaveClick(id)}
            />,
            <GridActionsCellItem
              icon={<CancelIcon />}
              label="Cancel"
              className="textPrimary"
              onClick={handleCancelClick(id)}
              color="inherit"
            />
          ];
        }

        return [
          <GridActionsCellItem
            icon={<EditIcon />}
            label="Edit"
            className="textPrimary"
            onClick={handleEditClick(id)}
            color="inherit"
          />,
          <GridActionsCellItem
            icon={<DeleteIcon />}
            label="Delete"
            onClick={handleDeleteClick(id)}
            color="inherit"
          />
        ];
      }
    }
  ];

  return (
    <Box
      sx={{
        height: 500,
        width: "100%",
        "& .actions": {
          color: "text.secondary"
        },
        "& .textPrimary": {
          color: "text.primary"
        }
      }}
    >
      <StripedDataGrid
        apiRef={apiRef}
        rows={rows}
        columns={columns}
        editMode="row"
        filterMode="client"
        experimentalFeatures={{ columnGrouping: true }}
        onRowModesModelChange={handleRowModesModelChange}
        onRowEditStop={handleRowEditStop}
        processRowUpdate={processRowUpdate}
        slots={{
          toolbar: CustomToolbar
        }}
        slotProps={{
          toolbar: { setRows, setRowModesModel, columns }
        }}
      />
    </Box>
  );
}

**Comment by romgrk** [comment]
It seems like you're passing custom proos in `slotProps` and you're then passing them directly to the original component. You need to destructure them out of props before passing the props.

![image](https://github.com/mui/mui-x/assets/1423607/fee60c5c-2040-4d43-a0e7-540658efe727)
