### ISSUE TITLE
[charts] Wrap `Legend` labels to avoid overlapping when displaying multiple categories

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#9743]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/legend-labels-4kh7r8

Steps:
1. Check live demo to see labels overlapping

### Current behavior 😯

The Legend components try to display all categories in the same row with equally-divided widths.
<img width="514" alt="image" src="https://github.com/mui/mui-x/assets/550141/7e11489c-ae78-4435-aecc-bc9cda56e555">

### Expected behavior 🤔

Ideally, the `Legend` component could deal with this issue by:
- Automatically breaking lines on the text categories to match legend width.
- (and/or) Setting custom Item width for single legends, and automatically breaking to the next row if the legends don't fit the current one.
- (or) Dynamically auto-size legends based on the label width and consider row width to use multiple rows.

Other open-source libraries don't provide this feature out-of-the-box, so you have to build your own CustomLegend component, but some commercial libraries do.

### Benchmark
[Highcharts](https://jsfiddle.net/t7ep0weq/1/) have a property called `itemWidth` and it's used as a kind of `flexBasis`

```
legend: {
    enabled: true,
    itemWidth: 200, //Essentially sets two columns for legends in this case
    width:400,
    align: 'center'
  },
```

Recharts does it automatically, and have a property on Legend called wrapperStyle where you can define further styling.

```
<Legend verticalAlign="bottom" wrapperStyle={{ lineHeight: "40px" }} />
```

**Comment by Dimatymoshchenko** [comment]
Hey guys, how to achieve 2 columns legend?
