### ISSUE TITLE
[question] flash datagrid cells on update

### ISSUE THREAD

**Issue by acentrella13** [mui/mui-x#9748]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello,

For a datagridpremium, how can I flash a colored change when a cell updates, like a stock price (green if up, red if down, only for a few seconds then returns to normal), and again just simply flash when updated not conditionally up or down, just flash a color when updated. 

Thank you

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
"@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@mui/x-data-grid-premium": "^6.10.0"

**Comment by romgrk** [comment]
Priority support is an addon on premium. If you haven't purchased priority support specifically it's not included in the premium license.

Have you looked at [this example](https://mui.com/x/react-data-grid/performance/#visualization)? You could use it as a starting point to flash cells. You'll need to add the conditional logic for the color. You may also need the `onCellEditStop` event.

**Comment by romgrk** [comment]
Alright, if you hit any blocking issue with your use-case you can comment back here. AFAICT you should have all the pieces to implement that functionality.

If you don't have any more questions, you can close the issue.
