### ISSUE TITLE
DataGrid keeps displaying values in footer for non-aggregable fields 

### ISSUE THREAD

**Issue by nessj1994** [mui/mui-x#9749]
### Order ID

70732

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I could use some help fixing my setup of a table for some quote data that contains 2 Date columns, and a total column among other fields. I turned on SUM aggregation for the quote total col, but for some reason despite setting aggregable to false on both date columns in my column definition, the two date fields, and my action column for deleting rows still have some form of value in the footer as well. The action column is also set to false for aggregable. It’s very weird and misleading. It seems like it is simply showing today’s date because the two columns have wildly different values among their rows, but both seem to be showing today's date in the footer. Is there any way that I can just manually disable the aggregation values / footer display for those columns such as returning a null for those values somehow. Any method will suffice really. I tried searching the issues, and other places online to see if I could just make a custom render function for the aggregate cell, or any other methods of messing with the aggregation model, but I had no success.  Below is a screenshot of the values populating in the footer. 
![image](https://github.com/mui/mui-x/assets/9426931/1961c867-46f3-4c1b-87f2-61a8c0cb22d8)

Side note that I ran the requested npx @mui/envinfo command and pasted my results below. It says Chrome wasn't found, but I am in fact using Chrome in my development. The About Chrome info shows:  Version 114.0.5735.248 (Official Build) (64-bit) I am also updating this now as it seems a newer version is available, but I don't believe that will resolve the issue.

Thank you for any help you're able to provide.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1928.0), Chromium (114.0.1823.79)
  npmPackages:
    @emotion/react: ^11.10.0 => 11.10.0
    @emotion/styled: ^11.9.3 => 11.9.3
    @mui/base: ^5.0.0-alpha.91 => 5.0.0-alpha.91
    @mui/core-downloads-tracker:  5.10.17
    @mui/icons-material: ^5.10.16 => 5.10.16
    @mui/material: ^5.8.6 => 5.10.17
    @mui/private-theming:  5.10.16
    @mui/styled-engine:  5.10.16
    @mui/system:  5.10.17
    @mui/types:  7.2.2
    @mui/utils:  5.10.16
    @mui/x-data-grid:  6.10.0
    @mui/x-data-grid-premium: ^6.10.0 => 6.10.0
    @mui/x-data-grid-pro:  6.10.0
    @mui/x-date-pickers: ^5.0.0 => 5.0.0
    @mui/x-license-pro:  6.10.0
    @types/react: ^18.0.15 => 18.0.15
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: 4.4.4 => 4.4.4

```
</details>

**Comment by nessj1994** [comment]
I do see another issue that mentions something that seems like it could be similar to my action column issues, but the date fields I couldn't find anything else.

**Comment by romgrk** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) _may_ be a good starting point. Thank you!

**Comment by nessj1994** [comment]
> Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 . A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) _may_ be a good starting point. Thank you!

Thank you for the template link. I'm working on setting up a test case now.

**Comment by nessj1994** [comment]
> Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 . A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) _may_ be a good starting point. Thank you!

https://codesandbox.io/s/winter-architecture-p57jkf?file=/demo.tsx

Here's a basic reproduction of the problem. My real setup is definitely more in depth, but I hope this will do given that it does demonstrate the issue.

**Comment by romgrk** [comment]
The `valueGetter` is called for aggregation rows, so you need to add a condition to return an empty value in those cases.

![image](https://github.com/mui/mui-x/assets/1423607/542ef1a0-b4b4-45d0-8e72-bcd799406f32)

**Comment by nessj1994** [comment]
Do you happen to have any quick suggestions on how I might determine if it's the aggregation cell or not so I can return that empty value? If not I can go digging, but I see in the sandbox that commenting out my value getter does indeed instantly remove the problem.

**Comment by nessj1994** [comment]
Thank you for the assistance. I fixed all 3 columns. For anyone else that might come across this, I was indeed able to simply remove the valueGetter from the date columns and use the valueFormatter alone. If for some reason one did also need the getter I'm not sure how they would do it exactly. It might be similar to how I ended up fixing my action cell footer though. For that one I managed to fix it by simply adding a check for row id in my renderCell function.  If the id matched 'auto-generated-group-footer-root' which seems to be the automatically set value for anything in the aggregated footer cells, I simply returned null instead of the display html.

**Comment by nessj1994** [comment]
Thank you for the assistance. I fixed all 3 columns. For anyone else that might come across this, I was indeed able to simply remove the valueGetter from the date columns and use the valueFormatter alone. If for some reason one did also need the getter I'm not sure how they would do it exactly. It might be similar to how I ended up fixing my action cell footer though. For that one I managed to fix it by simply adding a check for row id in my renderCell function. If the id matched 'auto-generated-group-footer-root' which seems to be the automatically set value for anything in the aggregated footer cells, I simply returned null instead of the display html.

**Comment by sterlingdcs-damian** [comment]
I'm also getting this with a date field

e.g.
```
   {
        field: 'lastModified',
        headerName: t({ id: 'projects_list.grid.header.lastModified', message: 'Last Modified' }),
        width: 100,
        valueFormatter: ({ value }: GridValueFormatterParams<TRow['lastModified']>) => formatDate(value),
        groupable: false,
        aggregable: false,
  
      },
      ```
      I also tried 
        {
        field: 'lastModified',
        headerName: t({ id: 'projects_list.grid.header.lastModified', message: 'Last Modified' }),
        width: 100,
        valueFormatter: ({ value }: GridValueFormatterParams<TRow['lastModified']>) => formatDate(value),
        groupable: false,
        aggregable: false,
        // Hack because aggregable doesnt seem to be working
        renderCell: ({ value, aggregation }: GridRenderCellParams<TRow, TRow['totalCo2']>) => {
          return aggregation ? `` : value
        },
      },
      ```
      
      but it appears valueFormatter is being called before aggregable is checked and somehow rendering a value 
      In my case I see 'Wrong date format.'
      I'm on the latest :     "@mui/x-data-grid-premium": "^6.12.1",

**Comment by sterlingdcs-damian** [comment]
ok so seems i can work around it by checking if the value is defined in `valueFormatter` 

`        valueFormatter: ({ value }: GridValueFormatterParams<TRow['lastModified']>) => (value ? formatDate(value) : ''),`

**Comment by dkv-predrag-kondic** [comment]
That might be helpful for some cases: https://github.com/mui/mui-x/issues/9196
