### ISSUE TITLE
GridToolbarQuickFilter search bar just readonly i try to search some value cannot type why?

### ISSUE THREAD

**Issue by Mohan3298** [mui/mui-x#9750]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-data-grid/filtering/server-side/

### Kind of issue

Unclear explanations

### Issue description

I was looking for ... and it appears that ...

**Comment by romgrk** [comment]
Can't reproduce. Can you provide clear reproduction steps and a clear description of the issue you're having?
