### ISSUE TITLE
[pickers] With the new Date Range Picker getting a object is not a function on getTodayVaue using date-fns

### ISSUE THREAD

**Issue by CountrySmooth** [mui/mui-x#9752]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

When upgrading to the latest version Of @mui/x-date-pickers-pro
Getting an error on Object.getTodayValue when using date-fns AdapterDateFns

![image](https://github.com/mui/mui-x/assets/48653831/6d111c54-c15c-425d-b653-e5001320d4c5)

![image](https://github.com/mui/mui-x/assets/48653831/8097a170-b5f3-469f-8aa1-c5d0a2b45c0a)

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by LukasTy** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot. 👷
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/wizardly-carlos-rccdwl?file=/demo.tsx) _may_ be a good starting point. Thank you!

**Comment by CountrySmooth** [comment]
It's a very interesting bug that I can only reproduce by using docker to build our library. Also getting a type error when using `changeImportance` prop for the shortcuts 

error TS2322: Type '{ items: any; changeImportance: string; }' is not assignable to type 'SlotComponentProps<ComponentType<PickersShortcutsProps<DateRange<unknown>>>, {}, PickersShortcutsOwnerState<DateRange<unknown>>> | undefined'.

  Object literal may only specify known properties, and 'changeImportance' does not exist in type 'SlotComponentProps<ComponentType<PickersShortcutsProps<DateRange<unknown>>>, {}, PickersShortcutsOwnerState<DateRange<unknown>>>'.

**Comment by LukasTy** [comment]
Maybe you could provide a minimal reproduction repository with the setup that is producing this issue? 🤔 

In regards to the `changeImportance`, which version of the package are you using?
This prop has been added quite recently, maybe you haven't updated the package to the version that adds this property?

**Comment by CountrySmooth** [comment]
Got the issue resolved it was some dependency issue with the docker container
