### ISSUE TITLE
[pickers] How to set initial values in time picker and  what date format?

### ISSUE THREAD

**Issue by Mohan3298** [mui/mui-x#9755]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/react-date-pickers/time-picker/

### Kind of issue

Unclear explanations

### Issue description

I was looking for ... and it appears that ...

**Comment by Mohan3298** [comment]
Any solution

**Comment by LukasTy** [comment]
Could you clarify what information you weren't able to find in the documentation? 🤔 
The [uncontrolled demo](https://mui.com/x/react-date-pickers/time-picker/#:~:text=uncontrolled%20or%20controlled) shows an example with only the default (initial) value.
The [views section](https://mui.com/x/react-date-pickers/time-picker/#views) contains examples in custom format.
