### ISSUE TITLE
DataGrid quick filter in CustomToolbar loses focus while typing with server-side-filtering

### ISSUE THREAD

**Issue by agsmithus** [mui/mui-x#9756]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/elegant-artem-627ddh?file=/demo.js:890-891

Steps:

1. Codesandbox example taken from the server side filtering page example and added quick filter in custom toolbar
2.  Quick filter works fine if passed directly to the slots toolbar prop
3. If wrapped in the custom toolbar container, then quick search loses focus while typing
4.

### Current behavior 😯

If the toolbar is passed like this: 

```
  function CustomToolbar() {
    return (
      <GridToolbarContainer>
        <GridToolbarQuickFilter />
      </GridToolbarContainer>
    );
  }
```

 ...

 slots={{ toolbar: CustomToolbar }} // quickfilter fails

then focus is lost while typing.

Simple change to not use a customtoolbar wrapper and it suddenly works:
slots={{ toolbar: GridToolbarQuickFilter }} // quickfilter works

### Expected behavior 🤔

Search input should not ever lose focus while typing

### Context 🔦

DataGrid server-side-filtering with the quick filter

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Could it be because your custom quick filter is defined in the root component as explained here: https://mui.com/x/react-date-pickers/custom-components/#recommended-usage (it's pickers docs, but behavior is the same for data grid)

**Comment by cherniavskii** [comment]
Hey @agsmithus,
Alex is right - the `CustomToolbar` component should not be defined inside another component, you should move it outside.
Here is a working demo: https://codesandbox.io/s/priceless-hodgkin-zlmj3d

**Comment by agsmithus** [comment]
Oh okay, my fault. Thank you!

**Comment by subashthiru3** [comment]
Still I'm facing this issue
When the GridToolbarQuickFilter search input loses focus in a TypeScript application
