### ISSUE TITLE
Mui Datepicker sets incorrect date for format yy

### ISSUE THREAD

**Issue by psr323** [mui/mui-x#9773]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: [https://codesandbox.io/s/t8pzn7](codesandbox)

Steps:
1. Set input format as "MM/dd/yy
2. Pass `minDate={new Date()}` prop
3. Pass `disablePast` prop
4. Type a date far in the future (10/10/99)

### Current behavior 😯

The onChange function sets the date as 10/10/1999

### Expected behavior 🤔

It should set the date as 2099 as I am disabling the past.

<img width="620" alt="image" src="https://github.com/mui/mui-x/assets/39456712/427bb0cf-d3de-48e3-90f6-bfd66326749f">

### Context 🔦

I would like to use MM/dd/yy as the date format. But when I type in 10/30/99, it returns a date 10/30/1999. I would like it to return 10/30/2099. It is happening because the library is trying to predict the nearest year to 99 from the current date.

```
 <LocalizationProvider dateAdapter={AdapterDateFns}>
      <DatePicker
        inputFormat="MM/dd/yy"
        value={date}
        minDate={new Date()}
        disablePast
        onChange={(newValue) => {
          console.log("new value", newValue)
          setDate(newValue);
        }}
        renderInput={(props) => (
          <TextField
            autoFocus
            size="small"
            {...props}
            inputProps={{
              ...props.inputProps,
              autocomplete: 'off',
              placeholder: 'MM/DD/YY',
            }}
          />
        )}
      />
    </LocalizationProvider>

```

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.4.1
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: Not Found
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Safari: 16.5.1
  npmPackages:
    @emotion/react: ^11.9.0 => 11.10.5 
    @emotion/styled: ^11.8.1 => 11.10.5 
    @mui/base: 5.0.0-alpha.64 => 5.0.0-alpha.64 
    @mui/core-downloads-tracker:  5.11.0 
    @mui/icons-material: 5.2.1 => 5.2.1 
    @mui/lab: 5.0.0-alpha.59 => 5.0.0-alpha.59 
    @mui/material: ^5.4.1 => 5.11.0 
    @mui/private-theming:  5.11.0 
    @mui/styled-engine:  5.11.0 
    @mui/styles: 5.2.3 => 5.2.3 
    @mui/system:  5.11.0 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.0 
    @mui/x-date-pickers: ^5.0.0-beta.0 => 5.0.0-beta.0 
    @types/react: 16.14.21 => 17.0.50 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: 4.5.4 => 4.5.4 
```
</details>

**Comment by flaviendelangle** [comment]
This behavior would be nice to have, but unfortunately the date library like `date-fns` doesn't allow us to be that smart.
