### ISSUE TITLE
DatePicker, errror value.isAfter is not a function after update @mui/x-date-pickers to ^6.10.1

### ISSUE THREAD

**Issue by BlackWolf00** [mui/mui-x#9777]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Create a React application
2. Install @mui/x-date-pickers 6.10.1
3. Create a component to Filter by date with two DatePicker from '@mui/x-date-pickers/DatePicker' (one to filter after the selected date and one to filter befor the selected date)
4. Launch the application
5. Choose the first date (to filter after the selected date)
6. Choose the second date (to filter befor the selected date)

### Current behavior 😯

When the user clicks the button to choose the second date, the application crashes with this message: 

Uncaught runtime errors:
ERROR
value.isAfter is not a function
./node_modules/@mui/x-date-pickers/AdapterDayjs/AdapterDayjs.js/AdapterDayjs/this.isAfterDay@http://localhost:3000/static/js/bundle.js:51953:22
getDefaultReferenceDate@http://localhost:3000/static/js/bundle.js:62751:38
getInitialReferenceValue@http://localhost:3000/static/js/bundle.js:63053:93
./node_modules/@mui/x-date-pickers/DateCalendar/useCalendarState.js/useCalendarState/referenceDate<@http://localhost:3000/static/js/bundle.js:53919:95
mountMemo@http://localhost:3000/static/js/bundle.js:99888:23
useMemo@http://localhost:3000/static/js/bundle.js:100273:20
useMemo@http://localhost:3000/static/js/bundle.js:122332:25
useCalendarState@http://localhost:3000/static/js/bundle.js:53911:60
DateCalendar@http://localhost:3000/static/js/bundle.js:52339:75
renderWithHooks@http://localhost:3000/static/js/bundle.js:99116:31
updateForwardRef@http://localhost:3000/static/js/bundle.js:101687:24
beginWork@http://localhost:3000/static/js/bundle.js:103734:20
callCallback@http://localhost:3000/static/js/bundle.js:88708:18
invokeGuardedCallbackDev@http://localhost:3000/static/js/bundle.js:88752:20
invokeGuardedCallback@http://localhost:3000/static/js/bundle.js:88809:35
beginWork$1@http://localhost:3000/static/js/bundle.js:108683:32
performUnitOfWork@http://localhost:3000/static/js/bundle.js:107930:16
workLoopSync@http://localhost:3000/static/js/bundle.js:107853:26
renderRootSync@http://localhost:3000/static/js/bundle.js:107826:11
performSyncWorkOnRoot@http://localhost:3000/static/js/bundle.js:107518:38
flushSyncCallbacks@http://localhost:3000/static/js/bundle.js:95548:26
./node_modules/react-dom/cjs/react-dom.development.js/ensureRootIsScheduled/<@http://localhost:3000/static/js/bundle.js:107149:17
VoidFunction*ensureRootIsScheduled@http://localhost:3000/static/js/bundle.js:107141:30
scheduleUpdateOnFiber@http://localhost:3000/static/js/bundle.js:107037:30
dispatchSetState@http://localhost:3000/static/js/bundle.js:100144:32
./node_modules/@mui/x-date-pickers/internals/hooks/useOpenState.js/useOpenState/setIsOpen<@http://localhost:3000/static/js/bundle.js:61486:21
./node_modules/@mui/x-date-pickers/internals/hooks/usePicker/usePickerValue.js/usePickerValue/handleOpen<@http://localhost:3000/static/js/bundle.js:61919:109
./node_modules/@mui/utils/esm/useEventCallback/useEventCallback.js/useEventCallback/<@http://localhost:3000/static/js/bundle.js:51270:19
callCallback@http://localhost:3000/static/js/bundle.js:88708:18
invokeGuardedCallbackDev@http://localhost:3000/static/js/bundle.js:88752:20
invokeGuardedCallback@http://localhost:3000/static/js/bundle.js:88809:35
invokeGuardedCallbackAndCatchFirstError@http://localhost:3000/static/js/bundle.js:88823:29
executeDispatch@http://localhost:3000/static/js/bundle.js:92967:46
processDispatchQueueItemsInOrder@http://localhost:3000/static/js/bundle.js:92993:26
processDispatchQueue@http://localhost:3000/static/js/bundle.js:93004:41
dispatchEventsForPlugins@http://localhost:3000/static/js/bundle.js:93013:27
./node_modules/react-dom/cjs/react-dom.development.js/dispatchEventForPluginEventSystem/<@http://localhost:3000/static/js/bundle.js:93173:16
batchedUpdates$1@http://localhost:3000/static/js/bundle.js:107565:16
batchedUpdates@http://localhost:3000/static/js/bundle.js:88556:16
dispatchEventForPluginEventSystem@http://localhost:3000/static/js/bundle.js:93172:21
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay@http://localhost:3000/static/js/bundle.js:90678:42
dispatchEvent@http://localhost:3000/static/js/bundle.js:90672:88
dispatchDiscreteEvent@http://localhost:3000/static/js/bundle.js:90649:22
EventListener.handleEvent*addEventBubbleListener@http://localhost:3000/static/js/bundle.js:90871:14
addTrappedEventListener@http://localhost:3000/static/js/bundle.js:93095:33
listenToNativeEvent@http://localhost:3000/static/js/bundle.js:93039:30
./node_modules/react-dom/cjs/react-dom.development.js/listenToAllSupportedEvents/<@http://localhost:3000/static/js/bundle.js:93050:34
listenToAllSupportedEvents@http://localhost:3000/static/js/bundle.js:93045:25
createRoot@http://localhost:3000/static/js/bundle.js:110328:33
createRoot$1@http://localhost:3000/static/js/bundle.js:110674:14
./node_modules/react-dom/client.js/exports.createRoot@http://localhost:3000/static/js/bundle.js:110750:16
./src/index.jsx@http://localhost:3000/static/js/bundle.js:11479:60
options.factory@http://localhost:3000/static/js/bundle.js:137122:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:136515:33
@http://localhost:3000/static/js/bundle.js:137768:56
@http://localhost:3000/static/js/bundle.js:137770:12

### Expected behavior 🤔

The application should work without problem.
Before the @mui/x-date-picker update to ^6.10.1 this feature worked fine.

### Context 🔦

Example of the second component used to choose the date to filter before the selected date.
```
<DatePicker
        label=...
        value={createdBefore}
        onChange={(newValue) => {
          onCreatedBeforeChange(newValue?.isValid() ? newValue.toISOString() : null);
        }}
        minDate={createdAfter}
        disableFuture
      />
```

### Your environment 🌎

  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by BlackWolf00** [comment]
Sorry it was a bug in my code, I managed to fix it.

**Comment by VadimTikh** [comment]
> Sorry it was a bug in my code, I managed to fix it.

Hello. Could you please share your solution?

**Comment by LukasTy** [comment]
@VadimTikh Take especial care to [this step](https://mui.com/x/migration/migration-pickers-v5/#update-the-format-of-the-value-prop) if you are migrating from v5.
In v5 it was possible to provide date values to the props in various formats (even a string) and the package took care of converting it.
This behavior proved problematic and did not bring enough value to justify its maintenance.
If you have the same issue, pay close attention if you are not passing date props (`value`, `minDate`, etc.) as strings or objects of a different type than the used Adapter (i.e. passing `new Date()` when using `AdapterDayjs`).

**Comment by baharalidurrani** [comment]
The fix worked in my case:
```tsx
import dayjs, { Dayjs } from 'dayjs';

<DatePicker
  minDate={minDate && dayjs(minDate)}
  maxDate={dayjs()}
  // format="MM/dd/yyyy"
  label="End Date"
  value={endDate ? dayjs(endDate) : null}
  onChange={(value: Dayjs | null) => {}}
/>
```
