### ISSUE TITLE
[question] unique `id` error but one exists

### ISSUE THREAD

**Issue by acentrella13** [mui/mui-x#9778]
### Order ID

70942

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello,

My datagrid contains a field 'id', and this component works fine when i'm on the page containing it, using useQuery it refetches data every few seconds.  However, when I try to navigate to a different page, I get the uinique 'id' error (shown at bottom).

Here is my code:

**NotificationSummary.js**
```
import React, { useState, useEffect } from 'react';
import { useQuery } from 'react-query'

import Card from 'react-bootstrap/Card';

import { DataGridPremium } from '@mui/x-data-grid-premium';
import { LicenseInfo } from '@mui/x-license-pro';

import fetchNotificationSummary from './fetchNotificationSummary';
LicenseInfo.setLicenseKey('xxxx');

const columns = [
    { field: 'notification_text', headerName: 'notification_text', width: 300 },
    { field: 'symbol', headerName: 'symbol', width: 75 },
    { field: 'side', headerName: 'side', width: 75 },
    { field: 'shares', headerName: 'shares', type: 'number', width: 75 },
    { field: 'price', headerName: 'price', type: 'number', width: 75 },
    { field: 'notional', headerName: 'notional', type: 'number', width: 175 },
    { field: 'oms_bid', headerName: 'oms_bid', type: 'number', width: 75 },
    { field: 'oms_ask', headerName: 'oms_ask', type: 'number', width: 75 },
    { field: 'client_view_code', headerName: 'client_view_code', width: 75 },
    { field: 'notification_status', headerName: 'notification_status', width: 150 },
    { field: 'id', headerName: 'id', width: 100 }
]

function NotificationSummary() {
    const { data, error, isError, isLoading } = useQuery([],
        () => fetchNotificationSummary(),
        { refetchInterval: 3000 });

    if (isLoading) {
        return <div>Loading notifications...</div>
    }
    if (isError) {
        return <div>Error! Unable to retrieve orders {error.message}</div>
    }

    return (
        <div className="p-3">
            <br />
            <Card border="info" bg="light">
                <Card.Body as="h3">Notifications</Card.Body>
            </Card>
            <br />
            <Card border="info" className="main-card mb-3" bg="light" style={{ width: '90rem' }}>
                <Card.Header>Active Notifications:</Card.Header>
                <Card.Body>
                    <Card.Title></Card.Title>
                    <div>
                        <div className="table-responsive">
                            <DataGridPremium
                                rowHeight={15}
                                rows={data}
                                columns={columns}
                                getRowId={row => row.id}
                                pageSize={12}
                                sx={{
                                    bgcolor: 'white',
                                    boxShadow: 2,
                                    border: 2,
                                    borderColor: 'primary.light',
                                    '& .MuiDataGrid-cell:hover': {
                                        color: 'primary.main',
                                    },
                                    "& .MuiDataGrid-columnHeaderTitle": {
                                        fontSize: 12,
                                        fontWeight: 'bold !important',
                                    }
                                }}
                                pagination
                            />
                        </div>
                    </div>
                </Card.Body>
            </Card>
        </div>
    );
}
export default NotificationSummary;
```

**fetchNotificationSummary.js**
```
import axios from "axios";

async function fetchNotificationSummary() {
    const { data } = await axios.get('https://localhost:7048/api/notifications/NotificationSummary');
    return data;
}

export default fetchNotificationSummary;
```

**Error when navigating to a _different_ page**
MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{"notification_text":"Price_Limit_Exceeds_10x_Last","symbol":"TEST","side":"S","shares":70,"price":2030,"notional":142100,"oms_bid":6.08,"oms_ask":6.09,"client_view_code":"TEST","notification_status":"STATUS_ACTIVE","id":1}
Error: MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{"notification_text":"Price_Limit_Exceeds_10x_Last","symbol":"TEST","side":"S","shares":70,"price":2030,"notional":142100,"oms_bid":6.08,"oms_ask":6.09,"client_view_code":"TEST","notification_status":"STATUS_ACTIVE","id":1}
    at checkGridRowIdIsValid (http://localhost:3000/static/js/bundle.js:61598:11)
    at getRowIdFromRowModel (http://localhost:3000/static/js/bundle.js:61603:3)
    at createRowsInternalCache (http://localhost:3000/static/js/bundle.js:61620:16)
    at rowsStateInitializer (http://localhost:3000/static/js/bundle.js:62075:103)
    at useGridInitializeState (http://localhost:3000/static/js/bundle.js:64339:35)
    at useDataGridPremiumComponent (http://localhost:3000/static/js/bundle.js:32143:90)
    at DataGridPremium (http://localhost:3000/static/js/bundle.js:31104:114)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:100705:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:103276:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:105323:20)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @acentrella13 
The error appears when the data grid unmounts, right?
Can you specify which version of the `@mui/x-data-grid-premium` package you are using?

**Comment by acentrella13** [comment]
it is version 6.10.0

**Comment by cherniavskii** [comment]
@acentrella13 Can you provide a reproduction example? I cannot reproduce it with this demo: https://codesandbox.io/s/affectionate-jasper-fpw3rt?file=/demo.tsx

**Comment by acentrella13** [comment]
I'm not sure how I could as it is accessing company's databases..  however, it does not happen when I navigate to a plain html page, it happens when i nav to another page doing almost the same thing (similiar datagrid, with data fetch) if that helps

**Comment by acentrella13** [comment]
Any thoughts here... thank you

**Comment by acentrella13** [comment]
I just upgraded npm install '@mui/x-data-grid-premium'
and got a slew of errors...please help?

Here's a quarter of them:
ERROR in ./node_modules/@mui/x-data-grid-premium/DataGridPremium/DataGridPremium.js 18:24-39
export 'useGridSelector' (imported as 'useGridSelector') was not found in '@mui/x-data-grid-pro' (possible exports: DATA_GRID_PRO_PROPS_DEFAULT_VALUES, DataGrid, DataGridPremium, DataGridPro, GRID_COLUMN_MENU_SLOTS, GRID_COLUMN_MENU_SLOT_PROPS, GRID_DETAIL_PANEL_TOGGLE_COL_DEF, GRID_DETAIL_PANEL_TOGGLE_FIELD, GRID_REORDER_COL_DEF, GRID_TREE_DATA_GROUPING_FIELD, GridColumnHeaders, GridColumnMenu, GridColumnMenuPinningItem, GridDetailPanelToggleCell, GridHeaderFilterCell, GridHeaderFilterMenu, GridHeaderFilterMenuContainer, GridPinnedPosition, GridPushPinLeftIcon, GridPushPinRightIcon, GridTreeDataGroupingCell, LicenseInfo, getGroupRowIdFromPath, gridColumnReorderDragColSelector, gridColumnReorderSelector, gridColumnResizeSelector, gridDetailPanelExpandedRowIdsSelector, gridDetailPanelExpandedRowsContentCacheSelector, gridDetailPanelExpandedRowsHeightCacheSelector, gridPinnedColumnsSelector, gridResizingColumnFieldSelector, useGridApiContext, useGridApiRef, useGridRootProps)
ERROR in ./node_modules/@mui/x-data-grid-premium/DataGridPremium/DataGridPremium.js 19:27-46
export 'GridContextProvider' (imported as 'GridContextProvider') was not found in '@mui/x-data-grid-pro' (possible exports: DATA_GRID_PRO_PROPS_DEFAULT_VALUES, DataGrid, DataGridPremium, DataGridPro, GRID_COLUMN_MENU_SLOTS, GRID_COLUMN_MENU_SLOT_PROPS, GRID_DETAIL_PANEL_TOGGLE_COL_DEF, GRID_DETAIL_PANEL_TOGGLE_FIELD, GRID_REORDER_COL_DEF, GRID_TREE_DATA_GROUPING_FIELD, GridColumnHeaders, GridColumnMenu, GridColumnMenuPinningItem, GridDetailPanelToggleCell, GridHeaderFilterCell, GridHeaderFilterMenu, GridHeaderFilterMenuContainer, GridPinnedPosition, GridPushPinLeftIcon, GridPushPinRightIcon, GridTreeDataGroupingCell, LicenseInfo, getGroupRowIdFromPath, gridColumnReorderDragColSelector, gridColumnReorderSelector, gridColumnResizeSelector, gridDetailPanelExpandedRowIdsSelector, gridDetailPanelExpandedRowsContentCacheSelector, gridDetailPanelExpandedRowsHeightCacheSelector, gridPinnedColumnsSelector, gridResizingColumnFieldSelector, useGridApiContext, useGridApiRef, useGridRootProps)
ERROR in ./node_modules/@mui/x-data-grid-premium/DataGridPremium/DataGridPremium.js 22:33-41
export 'GridRoot' (imported as 'GridRoot') was not found in '@mui/x-data-grid-pro' (possible exports: DATA_GRID_PRO_PROPS_DEFAULT_VALUES, DataGrid, DataGridPremium, DataGridPro, GRID_COLUMN_MENU_SLOTS, GRID_COLUMN_MENU_SLOT_PROPS, GRID_DETAIL_PANEL_TOGGLE_COL_DEF, GRID_DETAIL_PANEL_TOGGLE_FIELD, GRID_REORDER_COL_DEF, GRID_TREE_DATA_GROUPING_FIELD, GridColumnHeaders, GridColumnMenu, GridColumnMenuPinningItem, GridDetailPanelToggleCell, GridHeaderFilterCell, GridHeaderFilterMenu, GridHeaderFilterMenuContainer, GridPinnedPosition, GridPushPinLeftIcon, GridPushPinRightIcon, GridTreeDataGroupingCell, LicenseInfo, getGroupRowIdFromPath, gridColumnReorderDragColSelector, gridColumnReorderSelector, gridColumnResizeSelector, gridDetailPanelExpandedRowIdsSelector, gridDetailPanelExpandedRowsContentCacheSelector, gridDetailPanelExpandedRowsHeightCacheSelector, gridPinnedColumnsSelector, gridResizingColumnFieldSelector, useGridApiContext, useGridApiRef, useGridRootProps)
ERROR in ./node_modules/@mui/x-data-grid-premium/DataGridPremium/DataGridPremium.js 28:35-45
export 'GridHeader' (imported as 'GridHeader') was not found in '@mui/x-data-grid-pro' (possible exports: DATA_GRID_PRO_PROPS_DEFAULT_VALUES, DataGrid, DataGridPremium, DataGridPro, GRID_COLUMN_MENU_SLOTS, GRID_COLUMN_MENU_SLOT_PROPS, GRID_DETAIL_PANEL_TOGGLE_COL_DEF, GRID_DETAIL_PANEL_TOGGLE_FIELD, GRID_REORDER_COL_DEF, GRID_TREE_DATA_GROUPING_FIELD, GridColumnHeaders, GridColumnMenu, GridColumnMenuPinningItem, GridDetailPanelToggleCell, GridHeaderFilterCell, GridHeaderFilterMenu, GridHeaderFilterMenuContainer, GridPinnedPosition, GridPushPinLeftIcon, GridPushPinRightIcon, GridTreeDataGroupingCell, LicenseInfo, getGroupRowIdFromPath, gridColumnReorderDragColSelector, gridColumnReorderSelector, gridColumnResizeSelector, gridDetailPanelExpandedRowIdsSelector, gridDetailPanelExpandedRowsContentCacheSelector, gridDetailPanelExpandedRowsHeightCacheSelector, gridPinnedColumnsSelector, gridResizingColumnFieldSelector, useGridApiContext, useGridApiRef, useGridRootProps)
ERROR in ./node_modules/@mui/x-data-grid-premium/DataGridPremium/DataGridPremium.js 28:70-78
export 'GridBody' (imported as 'GridBody') was not found in '@mui/x-data-grid-pro' (possible exports: DATA_GRID_PRO_PROPS_DEFAULT_VALUES, DataGrid, DataGridPremium, DataGridPro, GRID_COLUMN_MENU_SLOTS, GRID_COLUMN_MENU_SLOT_PROPS, GRID_DETAIL_PANEL_TOGGLE_COL_DEF, GRID_DETAIL_PANEL_TOGGLE_FIELD, GRID_REORDER_COL_DEF, GRID_TREE_DATA_GROUPING_FIELD, GridColumnHeaders, GridColumnMenu, GridColumnMenuPinningItem, GridDetailPanelToggleCell, GridHeaderFilterCell, GridHeaderFilterMenu, GridHeaderFilterMenuContainer, GridPinnedPosition, GridPushPinLeftIcon, GridPushPinRightIcon, GridTreeDataGroupingCell, LicenseInfo, getGroupRowIdFromPath, gridColumnReorderDragColSelector, gridColumnReorderSelector, gridColumnResizeSelector, gridDetailPanelExpandedRowIdsSelector, gridDetailPanelExpandedRowsContentCacheSelector, gridDetailPanelExpandedRowsHeightCacheSelector, gridPinnedColumnsSelector, gridResizingColumnFieldSelector, useGridApiContext, useGridApiRef, useGridRootProps)
ERROR in ./node_modules/@mui/x-data-grid-premium/DataGridPremium/DataGridPremium.js 37:28-49
export 'GridFooterPlaceholder' (imported as 'GridFooterPlaceholder') was not found in '@mui/x-data-grid-pro' (possible exports: DATA_GRID_PRO_PROPS_DEFAULT_VALUES, DataGrid, DataGridPremium, DataGridPro, GRID_COLUMN_MENU_SLOTS, GRID_COLUMN_MENU_SLOT_PROPS, GRID_DETAIL_PANEL_TOGGLE_COL_DEF, GRID_DETAIL_PANEL_TOGGLE_FIELD, GRID_REORDER_COL_DEF, GRID_TREE_DATA_GROUPING_FIELD, GridColumnHeaders, GridColumnMenu, GridColumnMenuPinningItem, GridDetailPanelToggleCell, GridHeaderFilterCell, GridHeaderFilterMenu, GridHeaderFilterMenuContainer, GridPinnedPosition, GridPushPinLeftIcon, GridPushPinRightIcon, GridTreeDataGroupingCell, LicenseInfo, getGroupRowIdFromPath, gridColumnReorderDragColSelector, gridColumnReorderSelector, gridColumnResizeSelector, gridDetailPanelExpandedRowIdsSelector, gridDetailPanelExpandedRowsContentCacheSelector, gridDetailPanelExpandedRowsHeightCacheSelector, gridPinnedColumnsSelector, gridResizingColumnFieldSelector, useGridApiContext, useGridApiRef, useGridRootProps)
ERROR in ./node_modules/@mui/x-data-grid-premium/DataGridPremium/useDataGridPremiumComponent.js 11:24-45
export 'useGridInitialization' (imported as 'useGridInitialization') was not found in '@mui/x-data-grid-pro/internals' (possible exports: DATA_GRID_PRO_DEFAULT_SLOTS_COMPONENTS, DataGridProVirtualScroller, GridColumnHeaders, TREE_DATA_STRATEGY, addPinnedRow, columnPinningStateInitializer, columnReorderStateInitializer, columnResizeStateInitializer, createRowTree, detailPanelStateInitializer, getVisibleRowsLookup, insertNodeInTree, removeNodeFromTree, rowPinningStateInitializer, sortRowTree, updateRowTree, useGridColumnHeaders, useGridColumnPinning, useGridColumnPinningPreProcessors, useGridColumnReorder, useGridColumnResize, useGridDetailPanel, useGridDetailPanelPreProcessors, useGridInfiniteLoader, useGridLazyLoader, useGridLazyLoaderPreProcessors, useGridRowPinning, useGridRowPinningPreProcessors, useGridRowReorder, useGridRowReorderPreProcessors, useGridTreeData, useGridTreeDataPreProcessors)

**Comment by acentrella13** [comment]
I just went back to version 6.10.0 and now am still getting all of those errors

**Comment by cherniavskii** [comment]
@acentrella13 That's odd, do you have `@mui/x-data-grid-pro` as a dependency as well? You can check the installed versions of the packages by running
```bash
npm ls @mui/x-data-grid-premium @mui/x-data-grid-pro @mui/x-data-grid
```

**Comment by acentrella13** [comment]
I do not

**Comment by cherniavskii** [comment]
I recommend checking the installed versions using the command from https://github.com/mui/mui-x/issues/9778#issuecomment-1650357580

**Comment by acentrella13** [comment]
the results of that & my package.json are as follows

```
``-- @mui/x-data-grid-premium@6.10.0
  +-- @mui/x-data-grid-pro@6.10.0
  | `-- @mui/x-data-grid@6.10.0 deduped
  `-- @mui/x-data-grid@6.10.0`
```

**package.json**
```
{
  "name": "portal",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@mui/material": "^5.14.1",
    "@mui/styled-engine-sc": "^5.12.0",
    "@mui/x-data-grid-premium": "^6.10.0",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.4.0",
    "bootstrap": "^5.3.0",
    "react": "^18.2.0",
    "react-bootstrap": "^2.8.0",
    "react-dom": "^18.2.0",
    "react-query": "^3.39.3",
    "react-router-dom": "^6.14.2",
    "react-scripts": "5.0.1",
    "styled-components": "^5.3.11",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint-config-react-app": "^7.0.1",
    "jest-editor-support": "^31.1.0"
  }
}

```

**Comment by cherniavskii** [comment]
Yeah, looks good to me. This might be an issue with the package manager, I recommend deleting `node_modules` and installing them again.

**Comment by acentrella13** [comment]
Sorry would you mind elaborating specifically what to do?

How could this happen by merely installing the new version ?

**Comment by cherniavskii** [comment]
> would you mind elaborating specifically what to do?

```
rm -rf node_modules
npm install
```

> How could this happen by merely installing the new version ?

I don't know for sure, but I had some random package manager issues like this in the past 🤷‍♂️

**Comment by acentrella13** [comment]
I will try. Thank you

**Comment by acentrella13** [comment]
> rm -rf node_modules

-rf?

**Comment by acentrella13** [comment]
> I recommend deleting `node_modules` and installing them again.

Ok I have reinstalled them and am back to my original error of the OP, please advise

**Comment by cherniavskii** [comment]
@acentrella13 Could you try using version `6.10.1` again?

**Comment by acentrella13** [comment]
Same error:
    "@mui/x-data-grid-premium": "^6.10.1",

**Comment by acentrella13** [comment]
I have found the error, it was in my use of the useQuery call where it did not have a query key, so when navigating to the other page it was not caching independently and the grid was getting confused I suppose.  Thank you for your time

**Comment by cherniavskii** [comment]
Alright, so the issue is solved and can be closed now?

**Comment by acentrella13** [comment]
Yes, it is working. thank you very much
