### ISSUE TITLE
Placing grouping column in the last for tree data in data grid pro

### ISSUE THREAD

**Issue by everybytecounts** [mui/mui-x#9780]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

How can we move the grouping column to the last position instead of the first position? Currently, I have customized the grouping column to display a button for expanding children. However, it appears at the beginning of the grid, and I would like it to be the last column instead.

### Examples 🌈

In the example on the MUI documentation page for tree data and custom grouping column (https://mui.com/x/react-data-grid/tree-data/#custom-grouping-column),  how can I place the custom grouping column as the last column instead of the first column

**Comment by cherniavskii** [comment]
Hi @everybytecounts 
You can use the `GRID_TREE_DATA_GROUPING_FIELD` constant:
```diff
import { GRID_TREE_DATA_GROUPING_FIELD } from '@mui/x-data-grid-pro';

const columns: GridColDef[] = [
// ...
+  { field: GRID_TREE_DATA_GROUPING_FIELD }
];
```

Here's a demo: https://codesandbox.io/s/condescending-phoebe-2f2hqq?file=/demo.tsx
