### ISSUE TITLE
[DataGrid] Completely customised UI for (server-based) filterering

### ISSUE THREAD

**Issue by doberkofler** [mui/mui-x#9782]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The DataGrid offers an impressive list of options to customise filtering, but unfortunately sometimes a completely customised UI is needed. I'm looking for a way to intercept the actual entry points into the filtering to use my existing filtering solution.

I have a use case where the filtering is done on the server using a custom filter UI for each individual data set.
The filter UI is completely externalised and does already exist and I would need to make the DataGrid use the existing filter dialogs.

Assuming that only the UI to invoke filtering offered by the DataGrid is used and the rest is custom implemented , only two callbacks (that I cannot find) would be needed:
- a callback when the filter option from the column menu is clicked
- a callback when the filter icon on column header when there are active filters

Additionally it would only be needed to set the number of active filters for each column, so the UI can be initialised whin the predefined filter definition.

Assuming that the DataGrid would allow me call my custom code when the user invokes the above functions, it should be possible to add a customised filtering logic in a very generic way.

### Examples 🌈

1) Allow to intercept when the user wants to set a new filter for a column:

![image](https://github.com/mui/mui-x/assets/1009585/0ce9794b-75b9-4b89-a2a4-c40514436757)

2) Allow to intercept when to user wants to modify an existing filter:

![image](https://github.com/mui/mui-x/assets/1009585/fbace106-a1d6-4464-8a4a-ea67e7650ecf)

### Motivation 🔦

I have spend quite some time investigating all the available customisation options in DataGrid and am quite impressed.
Unfortunately when a completely customised filter UI is needed this currently does not seem to be possible.
As far as I understand it should be possible to completely customise the filtering by simply hooking into the entry points when setting or changing a filter.

**Comment by doberkofler** [comment]
Thank you very much for the example. I will test this for my use cases and post the results.

**Comment by doberkofler** [comment]
I now tested your example for my use cases and it works very well.
Sorry, I must somehow have overlooked the concept of "Overwriting components".

Currently I only miss the information about what column was actually interacted with in the `showFilterPanel` function.
I traced the arguments provided to `showFilterPanel` but it only seems to get the `SynthecticBaseEvent` but no column definition. I'm sure (the native implementation does it) this must be possible, but could you point me in the right direction?

Given that it is not trivial to customise the Grid, it might still be worth exploring a simpler API to fully customise the filter panel. I imagine a single optional `filterPanel` property on the Grid allowing a callback like `(colDef: GridColDef) => Promise<void>` could be an interesting customisation feature.

**Comment by MBilalShafi** [comment]
Glad it worked for you.

Thanks for the suggestion about the API. What would you think the purpose would be for the `onFilterPanel` property you mentioned and how could it address your specific use case?

**Comment by doberkofler** [comment]
Although the customization of column filters in the ˋDataGridˋ is quite extensive, there are situation when a completely customized UI for filtering is needed. In my use case we only filter on the backend and allow complex column specific filtering including boolean operators, ranges, validations and so on.
A ´onFilterPanel´ property should allow to simply interface with an externally designed filter dialog when setting or changing a column filter.

**Comment by doberkofler** [comment]
Thank you for the feedback!
The solution provided by [m4theushw](https://github.com/m4theushw) did work for me but requires quite a bit of custom code and I just wanted to suggest that there might be an clean and easy solution when someone needs full control over the filtering.

**Comment by MBilalShafi** [comment]
Thank you for the clarification. Yes we do recognize that customizing the current filter panel isn't a piece of cake right now. We have this in our roadmap to make it possibly make it a bit easier to do so.
