### ISSUE TITLE
[pickers] Header customization for year and month selection

### ISSUE THREAD

**Issue by matheus1lva** [mui/mui-x#9783]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to implement something that gives me control over the navigation, i.e:

![image](https://github.com/mui/material-ui/assets/831308/8271b47f-2e3b-4de5-a472-9e47f25cfdeb)

instead of having 
![image](https://github.com/mui/material-ui/assets/831308/6a12db79-74dc-40ac-af37-def3969c94f8)

### Examples 🌈

added previously

### Motivation 🔦

Being able to customize the selectors

**Comment by DiegoAndai** [comment]
We transferred your issue to the MUI X repo, so that the @mui/x team can help you sort it out 😊

**Comment by LukasTy** [comment]
Hello @matheus1lva 
We currently do not have a way—slot to override this part of the pickers.
There is a pending PR to add such functionality: https://github.com/mui/mui-x/pull/7784.
Do you think that it would cover your use case?

**Comment by matheus1lva** [comment]
@LukasTy yes, i also commented on that PR

**Comment by LukasTy** [comment]
So, this is partially related to #6653 and could be solved with #7784.
