### ISSUE TITLE
[pickers] MUI Time Picker w/ AdapterMoment returning wrong unix timestamp values when typing time values via input

### ISSUE THREAD

**Issue by lemmylem** [mui/mui-x#9789]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/objective-pascal-tyc2mv?file=/src/DateTimePicker.js

In the live sample I have several different adapters, but let's focus on the Moment Date Time picker. I have the date and time pickers set up and I print the unix timestamp printed when making changes. The reason I believe this is a MUI picker problem is because this behavior is **NOT** an issue when you select time from the time picker selection popover. The issue happens when a user manually types the time in the input field.

Steps:
1. Download time zone switching plugin https://chrome.google.com/webstore/detail/change-timezone-for-googl/cejckpjfigehbeecbbfhangbknpidcnh
2. Make sure you install and activate the plugin and select a time zone (let's select `Pacific/Apia`) and click "Save"
3. Go to the sandbox above, and change the time in the first (Moment) time picker to `20:05` by typing it out
4. You will see the timestamp printed being `1689588300000`
5. Head over to https://www.epochconverter.com/timezones?q=1689588300000&tz=Europe%2FVolgograd, and see that the unix time actually translates to `13:05:00` on the same day
6. Choose the same time again, but this time select it from the time picker popover
7. See timestamp value is `1689613500000`
8. Go to epoch converter, see that the value is **correct**

Conclusion: For the exact same time input, the time picker returns DIFFERENT values between inputting the time value manually and selecting the time value from the time picker popover.

### Current behavior 😯

When activating the time zone changing plugin, manually inputting time, results in the wrong unix stamp being printed in the output (which means, it has a moment object with the wrong time zone configuration or that there are locale specific time conversions happening that is outside moment, or other potential issues). **Selecting the exact same time from the time picker selection popover results in the correct value**.

### Expected behavior 🤔

Whether I select from the time picker or manually type in my value, the output should be exactly the same.

### Context 🔦

I'm trying to update to the newest version of MUI, that includes the date time picker.

I have a custom date/time range picker solution for previous MUI version and trying to integrate the new time picker with the custom built one. One of the things that MUI has done is now with the new version, only the date time object is accepted. Before, it would accept strings and unix stamps.

The above plugin has no effect on Moment, except for when user provide a time value via the time picker input element. For some reason, the moment object coming back from the time picker when a user types out a time gives back a moment object that when computed, outputs wrong time values.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Linux 4.18 Rocky Linux 8.7 (Green Obsidian)
  Binaries:
    Node: 18.14.0 - ~/.asdf/installs/nodejs/18.14.0/bin/node
    Yarn: Not Found
    npm: 9.3.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.4 
    @mui/lab:  5.0.0-alpha.134 
    @mui/material: 5.13.6 => 5.13.6 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.6 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.6 
    @mui/x-date-pickers:  6.5.0 
    @types/react: 18.2.14 => 18.2.14 
    react: 18.2.0 => 18.2.0 
    react-dom:  18.2.0 
    typescript: 5.1.3 => 5.1.3 
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

I can reproduce your problem with the extension you provided.
But do you have a problem without this extension?
It looks like it messes with the timezone and causes several bugs inside our components.

**Comment by lemmylem** [comment]
> Hi,
> 
> I can reproduce your problem with the extension you provided. But do you have a problem without this extension? It looks like it messes with the timezone and causes several bugs inside our components.

Nope, I can't replicate that behavior without that time zone settings plugin. But moment itself doesn't have these issues with or without this plugin. I know this doesn't matter for most applications, but for our application, where users can select their time zone via app and have to have their data displayed correctly (irrespective of external browser influence), it becomes important.

I'm not exactly sure why the Time Picker returns different unix values or even core moment objects when the exact same time input is chosen. I'll take a look into the code to see if I can find what exactly the issue is here, but at least I  believe that part is a legitimate bug.

**Comment by flaviendelangle** [comment]
The reason why I'm asking for the Chrome extension is because I have very weird behaviors with it even at the moment level.

If I set the timezone to `Pacific/Honolulu`, then `moment('2022-04-17T15:30').hour()` returns `3`, when it should return `15`
So for me, the extension is changing your timezone in a way that is not equivalent to actually having a computer in this timezone. And I think that's the root of your bug.
