### ISSUE TITLE
Add Tree Select component

### ISSUE THREAD

**Issue by NareshMurthy** [mui/mui-x#9790]
### Order ID or Support key 💳 (optional)

56539

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is there a way to achieve tree select using autocomplete?
I have already gone through https://github.com/mui/mui-x/issues/514

Is there a recommended way to implement this feature, using autocomplete?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment]
Duplicate of #514
