### ISSUE TITLE
[data grid pro] indication(badge) not showing when custom icon added in GridToolbarFilterButton

### ISSUE THREAD

**Issue by manu-058** [mui/mui-x#9791]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/data-grid-pro-forked-kh8lq2?file=/src/App.tsx:2476-2487
Steps:
1. In the Custom toolbar override the default filter icon of DataGridPro with any other icon .
2. Click on the filter button at the top and add some filter values.

### Current behavior 😯

Once the filter is added there is no badge indicator on how many filters are added.

### Expected behavior 🤔

Once the filter is added badge indicator should show how many filters the user has added.

### Context 🔦

We are using fontawesome icons in Our application, This is the place where if we try to replace the icon, we are losing that badge indicator.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @manu-058 
If you want to only change the icon, we recommend using the component slot for this purpose:

```tsx
<DataGridPro
  slots={{
    toolbar: GridToolbar,
    openFilterButtonIcon: FilterAltIcon
  }}
/>
```

Here's a working demo: https://codesandbox.io/s/data-grid-pro-forked-ng5ccc?file=/src/App.tsx
You can read more about component slots in our docs https://mui.com/x/react-data-grid/components/#overriding-components

**Comment by manu-058** [comment]
@cherniavskii , That 's Great
Thank you for the Solution, 😄

**Comment by manu-058** [comment]
Closing issue.
