### ISSUE TITLE
is there a way to make the header sticky?

### ISSUE THREAD

**Issue by ltassoneVisua** [mui/mui-x#9792]
### Order ID or Support key 💳 (optional)

64854

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I cannot find anyway to make the header sticky. I tried:

- Using sx on columnHeaders but it's not applying anything
- Using slots to set columnHeaders  but I have no way to generate the headers myself. I tried using children, but it's not passing anything.
- Using enableStickyHeader   property on DataGridPro is not doing anything either. Not sure if deprecated or if it's just a big

Reproduction:

https://github.com/lcoenenvisua/datagrid-sticky-repro

### Your environment 🌎

  System:
    OS: macOS 13.4.1
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/code/sandbox/datagrid-sticky-repro/node_modules/.bin/npm
  Browsers:
    Chrome: 115.0.5790.98
    Edge: Not Found
    Safari: 16.5.2
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/material: ^5.14.2 => 5.14.2 
    @mui/x-data-grid: ^6.10.1 => 6.10.1 
    @mui/x-data-grid-pro: ^6.10.1 => 6.10.1 
    @mui/x-license-pro: ^6.10.0 => 6.10.0 
    @types/react: ^18.2.15 => 18.2.15 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0

**Comment by cherniavskii** [comment]
Hi @ltassoneVisua 
Could you provide more information about your use case and the behavior you are trying to achieve?
Thanks!

**Comment by romgrk** [comment]
[This codesandbox.io template](https://codesandbox.io/s/7tyjsv?file=/demo.tsx) is also a better way to share your use-case with us.

**Comment by lcoenenvisua** [comment]
Hi @cherniavskii thanks for answering. @ltassoneVisua is my colleague and I'll be taking over :)

I found a solution. I needed to wrap my `<DataGrid>` in a `<Box` with a set height.

This is solved.
