### ISSUE TITLE
[pickers] add an option to not include the end of day time option for DigitalClock

### ISSUE THREAD

**Issue by tran-simon** [mui/mui-x#9794]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When using the `DigitalClock` component with `views: ['hours']` and `timeStep: 60`, only times on the hours should be displayed.

Currently, because of [this line in `timeOptions` in `DigitalClock.tsx`](https://github.com/mui/mui-x/blob/020884a3bc8a03087a242a9f58902df24c0deffb/packages/x-date-pickers/src/DigitalClock/DigitalClock.tsx#L271), the end of day time is included no matter what. This means that all hours are currently rendered (12:00 AM, 01:00 AM ... 11:00 PM), but at the very end `11:59 pm` is included.

### Examples 🌈

<img width="136" alt="image" src="https://github.com/mui/mui-x/assets/8755930/afc0c419-9994-4699-a14f-e1a9851c3e2d">

### Motivation 🔦

I want a list of times on the hours (so a list of 0 to 23). `11:59` is invalid

**Comment by noraleonte** [comment]
Hey, @tran-simon! 👋 
Thanks for raising this! Have you tried adding a `maxTime` and `skipDisabled`? I think that should fix your issue. You can check out the documentation for that [here](https://mui.com/x/react-date-pickers/digital-clock/#skip-rendering-disabled-options). Let me know if that helps 🎉

**Comment by tran-simon** [comment]
>  Have you tried adding a `maxTime` and `skipDisabled`? 

Hi, yes I've tried, but it doesn't work for me because I have other entries that are disabled, but I still want to show them. For example, in a scheduling app, I would want to make clear to the user that the hours "2:00 pm" is already occupied (so not available, but still in the list as a disabled menuitem). But I don't want to show "11:59pm" at all, since it's not ever available.

in fact, it would be great to have a prop to overwrite the `timeOptions` array entirely. I can see other cases where you might want a custom list

**Comment by noraleonte** [comment]
I see 😄 I created a [PR](https://github.com/mui/mui-x/pull/9800) for this, and your issue should be fixed after the next release 🚀
