### ISSUE TITLE
DataGrid: Strange behavior when width is undefined

### ISSUE THREAD

**Issue by Janpot** [mui/mui-x#9797]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/zealous-carlos-w8jjx4

Steps:
1. add `width: undefined` to a column definition

### Current behavior 😯

The line under the row is cut short

<img width="466" alt="Screenshot 2023-07-26 at 09 32 00" src="https://github.com/mui/mui-x/assets/2109932/24d5ec5b-f2c3-4fb3-9940-3b0064d126ac">

### Expected behavior 🤔

The line spanning the full width

<img width="465" alt="Screenshot 2023-07-26 at 09 32 10" src="https://github.com/mui/mui-x/assets/2109932/deb3d418-6b2e-4e96-85e1-3caa2961258a">

### Context 🔦

This is a bit of an edge case, but I ran into it

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by gitstart** [comment]
@Janpot @m4theushw we would like to pick this up

**Comment by Janpot** [comment]
👍  Go for it
