### ISSUE TITLE
[DataGridPro] - Is there a way to access object column and include it in the quick search filter?

### ISSUE THREAD

**Issue by simbahandiane** [mui/mui-x#9806]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1.
2.
3.

### Current behavior 😯

Is there a way to access a column object in DataGridPro and include it in the quick search? The object structure is as below:

[{ Id: "xxx", obj: [{ objId: "1", somethingInside: "" }, { objId: "2", somethingInside: "" }] }]

I've tried declaring the column for the obj as below but no luck.

{ align: "left", 
headerAlign: "left", f
ield: "obj.objId", 
headerName: "Object", 
description: "Object", 
type: "string", 
flex: 1, 
width: UNDEFINED, 
minWidth: 0, 
filterable: TRUE, 
sortable: false
 }

### Context 🔦

I need a way to include the object in the quick search.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hi @simbahandiane 
Could you provide more details about your use case and the desired behavior?
Thanks!

**Comment by simbahandiane** [comment]
> Hi @simbahandiane Could you provide more details about your use case and the desired behavior? Thanks!

This is a sample code or reproduction of the code i'm using. https://codesandbox.io/s/headless-fog-z46kkc?file=/src/App.tsx

Desired behavior is that I should see the comment column. and can also filter the Comments.comment column

**Comment by cherniavskii** [comment]
You can use [`valueGetter`](https://mui.com/x/react-data-grid/column-definition/#value-getter) to access nested object values. This value will be used for quick filtering.
In your case, you have HTML, if you want to render it as HTML you need to use [`renderCell`](https://mui.com/x/react-data-grid/column-definition/#rendering-cells).

Here's a working demo: https://codesandbox.io/s/intelligent-williamson-zdcmtw

Is this what you are looking for?
