### ISSUE TITLE
Issue with GridApiContext in MUI v6

### ISSUE THREAD

**Issue by nsmolczyk** [mui/mui-x#9809]
### Order ID or Support key 💳 (optional)

51619

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Using the gridAPI context, I added a button that expanded/collapsed all rows in the DataGridPro using tree data. But when I upgraded to v6, this no longer worked. What changes do I need to make this work for v6? I can run the command without error, but the rows aren't expanded or collapsed like they do when I use v5.

Here's my relevant component code: 

`
 const CustomToolbar = () => {

        const apiRef = useGridApiContext();

        const handleExport = (options) => apiRef.current.exportDataAsCsv(options);

        const buttonBaseProps = {
            color: 'primary',
            size: 'small',
            startIcon: <FileDownloadIcon />,
        };

        const allIds = apiRef.current.getAllRowIds();

        return (
            <GridToolbarContainer>
                <Button
                    {...buttonBaseProps}
                    onClick={() => handleExport({ getRowsToExport: getRowsFromCurrentPage, allColumns: true, fileName: "PCModHierarchy" })}
                >
                    Export CSV
                </Button>
                <span title={allIds.length >= 5000 ? 'Apply a filter to enable' : ""}>
                    <Button
                        disabled={allIds.length >= 5000}
                        onClick={() => {

                            for (let id of allIds) {
                                try {
                                    apiRef.current.setRowChildrenExpansion(id, true)
                                } catch (err) {
                                    console.log(id)
                                }
                            }

                            setExpanded(!expanded)
                        }}
                    >{expanded ? 'Collapse All' : 'Expand All'}
                    </Button>
                </span>
            </GridToolbarContainer>
        );
    };

...

  return (
        <div style={{ height: 700, width: '100%' }}>
            <DataGridPro Pro
                treeData
                groupingColDef={{ disableExport: true, width: 300, renderCell: (params) => <CustomGridTreeDataGroupingCell hideDescendantCount {...params} /> }}
                components={{ Toolbar: CustomToolbar }}
                rowHeight={35}
                rows={rows}
                columns={columns}
                getTreeDataPath={getTreeDataPath}
                initialState={{
                    columns: {
                        columnVisibilityModel: {
                            'Initiative Milestone': false,
                            'Enterprise Milestone': false,
                            'Functional Milestone': false,
                            'Organization': false,
                            'Dev/Del Milestone': false,
                            'Product Suite': false,
                            'Feature': false,
                        },
                    },
                }}
            />
        </div>
    )

`

### Your environment 🌎

{
  "private": true,
  "license": "UNLICENSED",
  "name": "dashboard",
  "dependencies": {
    "@date-io/date-fns": "^2.11.0",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/icons-material": "^5.2.5",
    "@mui/lab": "^5.0.0-alpha.63",
    "@mui/material": "^5.2.7",
    "@mui/styles": "^5.2.3",
    "@mui/x-data-grid-pro": "^6.0.0",
    "@mui/x-date-pickers": "^5.0.7",
    "@mui/x-date-pickers-pro": "^6.0.0",
    "@testing-library/react": "^12.1.2",
    "anychart": "^8.11.0",
    "anychart-react": "^1.4.1",
    "babel-jest": "^27.4.6",
    "date-fns": "^2.28.0",
    "dayjs": "^1.11.6",
    "graphql": "^16.6.0",
    "graphql-tag": "^2.12.6",
    "material-ui-popup-state": "^4.0.2",
    "query-string": "^8.0.3",
    "react": "^17.0.2",
    "react-csv": "^2.2.1",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.2.1",
    "urql": "^3.0.3"
  },
  "overrides": {
    "yaml": "2.2.2",
    "semver": "^7.5.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "test-ci": "jest --ci --reporters=default"
  },
  "jest": {
    "transform": {
      "^.+\\.(js|jsx)$": "babel-jest"
    },
    "collectCoverage": true,
    "coverageReporters": [
      "html"
    ]
  },
  "babel": {
    "presets": [
      "@babel/preset-react",
      "@babel/preset-env"
    ],
    "plugins": [
      "@babel/plugin-syntax-jsx"
    ]
  },
  "eslintConfig": {
    "extends": [
      "plugin:testing-library/react",
      "react-app",
      "plugin:jest-dom/recommended"
    ],
    "rules": {
      "testing-library/prefer-screen-queries": "error"
    }
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "homepage": ".",
  "devDependencies": {
    "@babel/preset-env": "^7.16.8",
    "@testing-library/dom": "^8.11.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/user-event": "^13.5.0",
    "copy-modules-webpack-plugin": "^2.2.1",
    "eslint-plugin-jest-dom": "^4.0.2",
    "jest-junit": "^13.0.0",
    "react-scripts": "^5.0.0",
    "react-test-renderer": "^17.0.2"
  }
}

**Comment by cherniavskii** [comment]
Hi @nsmolczyk 
This seems to work fine in v6: https://codesandbox.io/s/cocky-kowalevski-fq8vg8?file=/demo.tsx
Can you provide a demo reproducing the issue?

**Comment by nsmolczyk** [comment]
Sure, here is a demo https://codesandbox.io/s/long-worker-zftjjf?file=/src/App.js

The main difference is that I'm providing a custom grouping cell. The titles in the group column of my table are long, so this custom cell allows me to display the full text on mouse hover. I'm also using JavaScript instead of TypeScript

**Comment by cherniavskii** [comment]
Thanks, @nsmolczyk!
Starting from the data grid v6, updating the `rows` will now reset the expansion state of the grid. See https://mui.com/x/migration/migration-data-grid-v5/#rows for more information.

In the example provided, the `rows` variable reference changes on each render. In this case, moving the `rows` variable outside of the component fixes the issue: https://codesandbox.io/s/holy-rgb-4yckht?file=/src/DemoTable.jsx
In a real-world scenario, you should either persist the reference to your data or use the `updateRows` method if you want to keep the expansion state.
