### ISSUE TITLE
[question] sortingState is undefined

### ISSUE THREAD

**Issue by lcoenenvisua** [mui/mui-x#9812]
### Order ID or Support key 💳 (optional)

64854

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hello there,

**Description**

I'm trying to implement keyboard navigation through selection (pushing the up arrow would select the previous row, the down arrow would select the next row, and so on). 

For this, I'm trying to use this selector: `gridPaginatedVisibleSortedGridRowIdsSelector()`

But I'm getting this error:
```
TypeError
sortingState is undefined
$csb$eval/gridSortedRowIdsSelector<@https://8vk89j.csb.app/node_modules/
mui/x-data-grid/6.10.1/hooks/features/sorting/gridSortingSelector.js:9:118
selector@https://8vk89j.csb.app/node_modules/
mui/x-data-grid/6.10.1/utils/createSelector.js:71:14
dependenciesChecker
https://8vk89j.csb.app/node_modules/reselect/es/index.js:66:37
memoized
https://8vk89j.csb.app/node_modules/reselect/es/defaultMemoize.js:100:20
selector@https://8vk89j.csb.app/node_modules/
mui/x-data-grid/6.10.1/utils/createSelector.js:95:91
dependenciesChecker
https://8vk89j.csb.app/node_modules/reselect/es/index.js:66:37
```

Is there anything I'm doing wrong or is it a bug?

Thanks for your work and kind regards

**Reproduction**

https://codesandbox.io/s/adoring-tdd-8vk89j?file=/demo.tsx:0-810

**Reference**

https://mui.com/x/react-data-grid/state/
https://mui.com/x/react-data-grid/filtering/#selectors

### Your environment 🌎

_See codesandbox_

### Edit

 I'm getting the same error with `gridFilteredSortedRowIdsSelector`

**Comment by cherniavskii** [comment]
Hi @lcoenenvisua 
The `apiRef` is initialized with an empty object, and only gets populated with state and methods after the grid is initialized. Checking for the `state` property helps:
```diff
-const visibleSorted = apiRef.current
+const visibleSorted = apiRef.current.state
  ? gridPaginatedVisibleSortedGridRowIdsSelector(apiRef)
  : null;
```

Here's updated demo: https://codesandbox.io/s/pedantic-forest-s2jhhs?file=/demo.tsx
