### ISSUE TITLE
[pickers] Is there a way for a certain shortcuts such as a "reset" shortcut to not close the date range picker when selected. 

### ISSUE THREAD

**Issue by CountrySmooth** [mui/mui-x#9815]
### Order ID or Support key 💳 (optional)

68583

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

This is with the latest version @mui/x-date-pickers-pro with the default changeImportance being "accept". Wondering if clicking on a certain shortcut we can set the `changeImportance` to "set"

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by noraleonte** [comment]
Hey @CountrySmooth! 👋 

You can check out the documentation for the shortcuts [here](https://mui.com/x/react-date-pickers/shortcuts). You can customize your items and even the actual shortcut slot. 

I am not entirely sure I understood correctly what you are trying to accomplish, but [here](https://codesandbox.io/s/shortcuts-changeimportance-overall-58q5gk) is an example for how to change the `changeImportance` of all the shortcuts to `set`, and [here](https://codesandbox.io/s/shortcuts-changeimportance-individual-2qcjs8) is another one where only the 'Reset' shortcut has the `changeImportance: 'set'`. Please let me know if this is what you were looking for 😄 🚀

**Comment by CountrySmooth** [comment]
Hi yes! That was exactly what I was looking for! Thanks for the assist 🏀
