### ISSUE TITLE
How can i ignore in filter diacritics? For example Apă i want to filter Apa (in data grid pro)

### ISSUE THREAD

**Issue by bogdancbs** [mui/mui-x#9817]
### Order ID or Support key 💳 (optional)

68255

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I am using unstable_headerFilters i want to know if there are any props witch can ignore diacritics.
 For example Apă i want to filter Apa: https://codesandbox.io/s/upbeat-wind-j6z8zc

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.248
    Edge: Spartan (44.22621.2070.0), Chromium (115.0.1901.183)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.1
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.4
    @mui/core-downloads-tracker:  5.14.0
    @mui/icons-material: ^5.11.11 => 5.13.7
    @mui/lab: ^5.0.0-alpha.133 => 5.0.0-alpha.134
    @mui/material: ^5.14.0 => 5.14.0
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/styled-engine-sc: ^5.11.11 => 5.12.0
    @mui/styles: ^5.14.1 => 5.14.1
    @mui/system:  5.13.5
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid: ^6.0.1 => 6.9.2
    @mui/x-data-grid-pro: ^6.6.0 => 6.8.0
    @mui/x-license-pro:  6.6.0
    @types/react:  18.2.14
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    styled-components: ^5.3.9 => 5.3.11
</details>

**Comment by cherniavskii** [comment]
Hi @bogdancbs 
You can [wrap built-in filter operators](https://mui.com/x/react-data-grid/filtering/customization/#wrap-built-in-operators) to achieve this behavior.
Here's a working demo: https://codesandbox.io/s/blissful-haibt-ptyrkx?file=/Demo.tsx
Is this what you are looking for?

**Comment by cherniavskii** [comment]
We might want to provide this functionality out of the box (opt-in) since it might be a common requirement in some languages.

**Comment by bogdancbs** [comment]
Great! thanks

**Comment by bogdancbs** [comment]
And if i want to filter table with diacritics? for example if i search "apă" no results returning, only for "apa"
It must work with or without diacritics

**Comment by cherniavskii** [comment]
@bogdancbs Right, here's a fixed version: https://codesandbox.io/s/quirky-sinoussi-hn97wj?file=/Demo.tsx

**Comment by bogdancbs** [comment]
great

**Comment by UmutKDev** [comment]
@cherniavskii not working in 7.x datagrid

**Comment by cherniavskii** [comment]
@UmutKDev It seems to work in https://mui.com/x/react-data-grid/filtering/quick-filter/#ignore-diacritics-accents
Can you open an issue with a reproduction example? Thanks!
