### ISSUE TITLE
[fields] Clearing a section clears the entier field when `props.timezone` is defined

### ISSUE THREAD

**Issue by morgluc** [mui/mui-x#9818]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
_I do not have a live example, but I've uploaded a zipped react project which describe steps on how to reproduce._

Steps:
1. _Unzip mui-dayjs-bug.zip and navigate to the unzipped folder._
2. _`npm install`_
3. _`npm start`_
4. _Follow the instructions on the home page:_
![image](https://github.com/mui/mui-x/assets/63873395/8ebe789d-613a-48f7-8aa9-ce55c40e19f7)

[mui-dayjs-bug.zip](https://github.com/mui/mui-x/files/12187837/mui-dayjs-bug.zip)

### Current behavior 😯

After pressing backspace with only one date part selected, the whole date is deleted.
![image](https://github.com/mui/mui-x/assets/63873395/94b2c544-9bc7-469a-9796-b8da5d91b484)

### Expected behavior 🤔

After pressing backspace with only one date part selected, all other date parts remain unchanged while the selected part is deleted.
![image](https://github.com/mui/mui-x/assets/63873395/147c641f-e86c-466c-896d-cb316976a4f9)

### Context 🔦

I am trying to use timezones to solve some 3PL freight container tracking and would like a consistent experience across date inputs which render for specific timezones vs date inputs which render for the user's timezone.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

I was using Firefox 115.0.2 64-bit

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

PS C:\Users\morgluc\source\repos\mui-dayjs-bug> npx @mui/envinfo
Need to install the following packages:
  @mui/envinfo
Ok to proceed? (y) y

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)

PS C:\Users\morgluc\source\repos\mui-dayjs-bug>
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

Thanks for the feedback !
Here is [the same bug on codesandbox](https://codesandbox.io/s/date-and-time-pickers-forked-hmq5x9?file=/src/App.tsx)
