### ISSUE TITLE
[DataGrid] Memory usage grows consistently when updating data

### ISSUE THREAD

**Issue by abryzak** [mui/mui-x#9828]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/xwkhq9

Steps:
1. Open the example in a new window
2. Wait for page to finish loading
3. Open Chromium DevTools & go to memory tab
4. Take a heap snapshot
5. Click the Start button in the example
6. Wait 30+ seconds
7. Click the stop button in the example
8. Take another heap snapshot in DevTools
9. Make sure Snapshot 2 is selected in the memory tab
10. In the toolbar of DevTools, switch from "All object" to "Objects allocated between Snapshot 1 and Snapshot 2"
11. Expand the (closure) item in the memory tree view
12. Select the 4th item under (closure) and note the retainers has a cycle of two different functions creating closures of each other

### Current behavior 😯

Currently the memory usage will keep growing as the data is updated.

### Expected behavior 🤔

Memory usage should stay relatively consistent when updating the rows of the table with similar-size data.

### Context 🔦

I noticed this behavior when leaving a page open overnight that had a few data tables on it and the next day the page became less responsive.

### Your environment 🌎

Using Ungoogled Chromium. The memory usage also grows in Firefox but the memory debugging tools aren't as extensive so it's easier to reproduce & investigate in a Chromium-based browser.

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 16.19.0 - ~/bin/node
    Yarn: 1.22.19 - ~/bin/yarn
    npm: 8.19.3 - ~/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
  npmPackages:
    @mui/base:  5.0.0-beta.8 
    @mui/core-downloads-tracker:  5.14.2 
    @mui/material: ^5.14.2 => 5.14.2 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine-sc:  5.12.0 
    @mui/system:  5.14.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.1 
    @mui/x-data-grid: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.15 => 18.2.17 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    styled-components: ^6.0.5 => 6.0.5
```
</details>

**Comment by cherniavskii** [comment]
Thanks, @abryzak!
I can reproduce it.

@romgrk Wanna take a look at this one? 🙂

**Comment by romgrk** [comment]
Yes, I'll look at this one.

**Comment by romgrk** [comment]
Continued in #12006
