### ISSUE TITLE
[pickers] access to responsive dialog box component in v5

### ISSUE THREAD

**Issue by srbadni** [mui/mui-x#9832]
### Order ID or Support key 💳 (optional)

#59340

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I use the `<DatePicker />` component in version 5 of mui and in responsive size this dialog box is displayed like this.

![Screenshot 2023-07-29 162351](https://github.com/mui/mui-x/assets/77675736/0b642e59-c8bc-4815-87d4-92ecce4ecdd9)

I want customize that, But I can't find any props related to this dialog box. Even the PaperContent field of components props is related to desktop paper

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
     System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.8
    @emotion/styled: ^11.10.6 => 11.10.8
    @mui/base:  5.0.0-alpha.127
    @mui/core-downloads-tracker:  5.12.2
    @mui/icons-material: ^5.11.11 => 5.11.16
    @mui/lab: ^5.0.0-alpha.121 => 5.0.0-alpha.128
    @mui/material: ^5.11.11 => 5.12.2
    @mui/private-theming:  5.12.0
    @mui/styled-engine:  5.12.0
    @mui/styles: ^5.11.11 => 5.12.0
    @mui/system:  5.12.1
    @mui/types:  7.2.4
    @mui/utils:  5.12.0
    @mui/x-date-pickers: ^6.0.0 => 6.3.0
    @mui/x-date-pickers-pro: ^5.0.20 => 5.0.20
    @mui/x-license-pro: ^5.17.12 => 5.17.12
    @types/react: 18.0.28 => 18.0.28
    react: ^18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5

```
</details>

**Comment by LukasTy** [comment]
Could you clarify what part exactly you want to customize?
Is [this](https://codesandbox.io/s/eloquent-proskuriakova-r299hj?file=/Demo.tsx) something that you want to achieve?
Also, do note, that you have mismatched versions of `@mui/x-date-pickers` and `@mui/x-date-pickers-pro` installed, please be sure to align the versions to avoid any unwanted behaviors. 😉
