### ISSUE TITLE
[pickers] The `slotProps.textField.InputProps.endAdornment`  prop is not overridable on pickers

### ISSUE THREAD

**Issue by zigang93** [mui/mui-x#9844]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

v6.10.x
https://codesandbox.io/s/clear-date-picker-v6-10-x-sfndfg

### Current behavior 😯

not able to replace the icon base on condition

### Expected behavior 🤔

working example with v6.0.1
https://codesandbox.io/s/clear-date-picker-v6-0-1-htyyjj

![test1](https://github.com/mui/mui-x/assets/11520821/a09da663-c975-4ae7-a3fd-84b40b684c53)

should work same as `v6.0.1`, 
please provide clear instruction to alternative solution.

### Context 🔦

Please don't try make any breaking changes for v6.. it had been very frustrated to maintain our code. 
Documentation of migration didn't mention on this changes.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
@LukasTy for me the issue here is that the `InputProps` from the picker takes precedence over the `InputProps` from the use `textField` slot.

The following change should fix the issue:

```diff
--- a/packages/x-date-pickers/src/DateField/DateField.tsx
+++ b/packages/x-date-pickers/src/DateField/DateField.tsx
@@ -33,8 +33,8 @@ const DateField = React.forwardRef(function DateField<TDate>(
   });
 
   // TODO: Remove when mui/material-ui#35088 will be merged
-  textFieldProps.inputProps = { ...textFieldProps.inputProps, ...inputProps };
-  textFieldProps.InputProps = { ...textFieldProps.InputProps, ...InputProps };
+  textFieldProps.inputProps = { ...inputProps, ...textFieldProps.inputProps };
+  textFieldProps.InputProps = { ...InputProps, ...textFieldProps.InputProps };
 
   const {
     ref: inputRef,
```

I don't see any downside to it but I'd like a 2nd look

**Comment by LukasTy** [comment]
> I don't see any downside to it but I'd like a 2nd look

I can't think and/or see any as well. Makes sense by the looks of it, we should allow overriding such things. 👌

**Comment by rotembarsela** [comment]
Try the following:
![image](https://github.com/mui/mui-x/assets/44998514/2c00d072-097f-4cf4-b975-f2d7376bfc40)

**Comment by flaviendelangle** [comment]
Your example will not change the behavior when clicking on the icon

**Comment by rotembarsela** [comment]
> Your example will not change the behavior when clicking on the icon

He suppost to create a custom Icon and import it, might work

**Comment by zigang93** [comment]
> Your example will not change the behavior when clicking on the icon

yes, you are right. 
Thanks for hot fix. :)
