### ISSUE TITLE
[pickers] Allow for Calendars  `2` in `MobileDateRangePicker`. 

### ISSUE THREAD

**Issue by PupoSDC** [mui/mui-x#9850]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Please allow us to configure the mobile date picker to show 2 calendars, using the already existed, but ignored prop `calendars={2}`.

### Examples 🌈

Here is what our UI would look like. 

<img width="1511" alt="image" src="https://github.com/mui/mui-x/assets/9625304/9e5a0148-0400-4f36-8eb7-9de4248c90a3">

neat right? Sure some CSS is missing to make sure the calendars don't overflow but that we can easily fix with the slotProps.

### Motivation 🔦

I understand you envision this component being used only for mobile displays, but for our product needs, we have decided to stick to mobile pickers even on large desktops because they provide a much more robust UX (no weird placement of calendars using poppers).

However, we have plenty of real estate and would like to set the range picker to show 2 calendars. I can achieve this by overriding the props in the dev tools... but i can't find a way to do it using "normal means" 

I would say that using `slots` / `slotProps` would be ok for this as well. Alternatively adding an option for the desktop picker to use a dialog instead of a popper would be fine as well. The trick used [here](https://github.com/mui/mui-x/issues/9850) sadly does not work on the range picker.

### Order ID 💳 (optional)

70604

**Comment by flaviendelangle** [comment]
The mobile component do not forward the prop to the view because as you said we built it for the mobile.
But you can still manually pass it at the renderer level ([example](https://codesandbox.io/s/date-and-time-pickers-forked-q5rksm?file=/src/App.tsx))

You would still have to handle the overflow.

I'm not sure we should support it out of the box, since the vast majority of users will only use this component on mobile.

**Comment by PupoSDC** [comment]
@flaviendelangle all right. That fixes my immediate needs. Thank you very much! 

I can agree with the statement that this does not make sense to be supported out of the box. But If we are asking for features, what I'm really concluding from these past few days working with pickers, is that it would be nice to have an out of the box choice if the picker pops as a `popper` or as a `dialog` without that making any other changes to the setup of the component. 

Closing this issue as a solution to the problem has been given!

Thank you very much!

**Comment by flaviendelangle** [comment]
> it would be nice to have an out of the box choice if the picker pops as a popper or as a dialog 

It's something we would like to give at some point
But we never truly prioritized it :+1:
