### ISSUE TITLE
[charts] re-export AxisConfig on top level, like SeriesTypes are exported

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#9852]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

```diff
import type { BarSeriesType } from "@mui/x-charts";
-import type { AxisConfig } from "@mui/x-charts/models/axis";
+import type { AxisConfig } from "@mui/x-charts";
```

### Motivation 🔦

Docs [state](https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports) that 
> we only support first and second-level imports. Anything deeper is considered private and can cause issues

So I've added the recommended no-restricted-imports rule from there, and it errors on current import of AxisConfig.

**Comment by flaviendelangle** [comment]
It should be re-exported from `@mui/x-charts/models` (which is always re-exported from the root)

**Comment by MonstraG** [comment]
![image](https://github.com/mui/mui-x/assets/17963791/89b98f3a-e28a-458d-a9b7-7dd8bb8539d8)


I'm on pnpm, for me `@mui/x-charts/models/index.d.ts` looks like this:
```ts
export * from './seriesType';
```
(that's the entire file)

**Comment by flaviendelangle** [comment]
Yes, it's not re-exported and it should be
