### ISSUE TITLE
[docs] DataGrid slots seem to be missing

### ISSUE THREAD

**Issue by developenguin** [mui/mui-x#9857]
### Duplicates

- [X] I have searched the existing issues

### Related page

https://mui.com/x/api/data-grid/data-grid/#slots

### Kind of issue

Missing information

### Issue description

I was looking for a list of all the slots I can customize in the Data Grid, including the types of the params that are passed to the custom components. In the old docs format, there was a separate table for this between the component API and the CSS classes. But it seems to have gone missing, or at least I can't find it anymore. All the references in the other docs I can find link to the 'related page' above, but that link just documents the prop which has type `object`.

**Comment by MBilalShafi** [comment]
This is a regression, it is likely be [fixed](https://deploy-preview-9866--material-ui-x.netlify.app/x/api/data-grid/data-grid/#slots) with https://github.com/mui/mui-x/pull/9866
