### ISSUE TITLE
[license] Getting `MUI License Expired` watermark with a valid license

### ISSUE THREAD

**Issue by tierneynr** [mui/mui-x#9860]
### Order ID or Support key 💳 (optional)

Order ID:  36286

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We continue to get the MUI License Expired watermark when we in fact have a valid license.
I suspect there is some combination of versions that we are not getting correct.  Could we get some support to figure out why we are getting this watermark?

We're using x-data-grid-pro.

We're setting the license prior to rendering the grid...

LicenseInfo.setLicenseKey(
  "****"
);

Here are our versions...
    "@mui/icons-material": "^5.4.4",
    "@mui/lab": "^5.0.0-alpha.51",
    "@mui/material": "^5.4.4",
    "@mui/styled-engine-sc": "^5.4.2",
    "@mui/styles": "^5.4.4",
    "@mui/x-data-grid-generator": "^5.17.20",
    "@mui/x-data-grid-pro": "^5.17.20",
    "@mui/x-date-pickers": "^5.0.0-alpha.6",
    "@mui/x-license-pro": "^5.11.0",

### Your environment 🌎

System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: Not Found
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.8.1 => 11.11.1 
    @emotion/styled: ^11.8.1 => 11.11.0 
    @mui/base:  5.0.0-beta.8 
    @mui/core-downloads-tracker:  5.14.2 
    @mui/icons-material: ^5.4.4 => 5.14.1 
    @mui/lab: ^5.0.0-alpha.51 => 5.0.0-alpha.137 
    @mui/material: ^5.4.4 => 5.14.2 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/styled-engine-sc: ^5.4.2 => 5.12.0 
    @mui/styles: ^5.4.4 => 5.14.1 
    @mui/system:  5.14.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.1 
    @mui/x-data-grid:  5.17.26 
    @mui/x-data-grid-generator: ^5.17.20 => 5.17.26 
    @mui/x-data-grid-pro: ^5.17.20 => 5.17.26 
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.20 
    @mui/x-license-pro: ^5.11.0 => 6.10.2 
    @types/react:  18.2.17 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components:  5.3.11 
    typescript:  5.1.6

**Comment by LukasTy** [comment]
Your resolved `@mui/x-license-pro` version seems strange and improper given the requested version. 🤔 
You seem to be using the old v5 version of packages in combination with the latest license verification package.
This should never bump to a new major.
```
@mui/x-license-pro: ^5.11.0 => 6.10.2
```
Try installing the latest v5 version (5.17.12) and please report if it helps. 👌
