### ISSUE TITLE
Not able to override `openDatePickerDialogue` locally

### ISSUE THREAD

**Issue by dhenneke** [mui/mui-x#9867]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-opendatepickerdialogue-l6fyyt

Steps:
1. Create a `DatePicker`.
2. Override `openDatePickerDialogue` with the `localText` property.

### Current behavior 😯

The original text is used as a label.

### Expected behavior 🤔

The provided text is used as a label.

### Context 🔦

We want to migrate to v6 of the date pickers and follow this [migration guide](https://mui.com/x/migration/migration-pickers-v5/#%E2%9C%85-rename-localization-props). While the other local localization overrides work, this one doesn't.

I think this is because the value of `localeText.openDatePickerDialogue` is read from the context and not from the props.

https://github.com/mui/mui-x/blob/081228ea4b681f8a77dd099a5cfed150e51a91e9/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx#L70

The `LocalizationProvider` is only set later during the `renderPicker()` and ensures that all other texts are read from the updated context. So the calling component reads it from the wrong context.

https://github.com/mui/mui-x/blob/081228ea4b681f8a77dd099a5cfed150e51a91e9/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx#L171-L194

---

A solution might be calling `getOpenDialogAriaText: props.localText.openDatePickerDialogue ?? localeText.openDatePickerDialogue`? I assume that the same problem appears in the `DesktopTimePicker`.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Hi,

Thanks for your detailed feedback.
I totally agree that the solution you are proposing works

```diff
diff --git a/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx b/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx
index f3705cb52..6f2e49a64 100644
--- a/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx
+++ b/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.tsx
@@ -67,7 +67,8 @@ const DesktopDatePicker = React.forwardRef(function DesktopDatePicker<TDate>(
     props,
     valueManager: singleItemValueManager,
     valueType: 'date',
-    getOpenDialogAriaText: localeText.openDatePickerDialogue,
+    getOpenDialogAriaText:
+      props.localeText?.openDatePickerDialogue ?? localeText.openDatePickerDialogue,
     validator: validateDate,
   });
```
