### ISSUE TITLE
Datagrid Nested Functionality

### ISSUE THREAD

**Issue by lisaWriteJava** [mui/mui-x#9872]
### Order ID

2023-7934

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Entered the invoice #. 

Ok Here's the issue: 

Hello, 

 

I'm developing a few datagrids and ran into a few questions on getting things set up. Below are the questions. 

I have a row that's nested. I need to display in 2 separated columns a information from within the column, how do I do that? My understanding is that the field column maps to 1 item in the row.

How to Handle filtering a nested value in the table table?

ie: {rowInfo.row.person.dob ? moment(rowInfo.row.person.dob).format('MMM. Do Y, h:mm a') : ''}. This is used for the valueGetter but the filtering won't work, can't use date as type and filtering won't work using renderCell

3. How to determine a field based upon the value in a row id

i.e.

      field: 'male_female', //doesn't exist in the row but, made up a field since it's doesn't really exist

   

 field: d => {(d.ismale ? "Male" : "Female")},  = This is what I want to do

//tried the below but I don't have row data so I can't do it here  

 renderHeader: (params) => { //This will only get the the name of the field I put in and not the other values from the row.

       if (params.ismale) {

         return "Male"

       } else {         return "Female"

       }     },  

  headerName: 'Male or Female', This works but I don't want it as it, I want it based upon a row value

 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hey @lisaWriteJava thanks for reporting this!

Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v6-quick-start-54iz1) _may_ be a good starting point. Thank you!

Also please add a relevant title to the issue. `[question]` is not really helpful when we do a quick scan of what has been opened recently.

**Comment by lisaWriteJava** [comment]
I am only able to give snippets of coded as in the request. Our code is proprietary and I can't share it. Please let me know if the snippets aren't enough

**Comment by lisaWriteJava** [comment]
Ok, I'll try to mock something up. Also how can I add a co-worker to this ticket so that they can provide info if needed?

**Comment by DanailH** [comment]
Hey, @lisaWriteJava do you try to achieve this https://mui.com/x/react-data-grid/filtering/header-filters/#renderheaderfilter-method by any chance? I don't see any nested rows in your reproduction. In addition, the `filed` from the column definition is of type `string`.
