### ISSUE TITLE
[question] `onRowDoubleClick` does not work when `onRowClick` is used

### ISSUE THREAD

**Issue by oleksandrfomin5995** [mui/mui-x#9873]
### Order ID

67193

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Is there  a way to use both `onRowClick` and `onRowDoubleClick` on `DataGrid` at the same time? 
It seems that `onRowDoubleClick` only works if we remove `onRowClick`

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hey, @oleksandrfomin5995 that is interesting. In this example, both seem to work as expected -> https://codesandbox.io/s/data-grid-community-forked-wkzpvr

**Comment by oleksandrfomin5995** [comment]
@DanailH 
I apologize for the bad title.  Quite frankly, my description was no better :) 

So if we use both methods simultaneously it registers both single click and double click when I do double click. 

Since my goal is to redirect to item page (extended info about item) on single click and redirect to edit page on double click, double-click never fires because that first redirect happens before the 2nd click is registered. 

Is there a way to use both and have correct redirects?

**Comment by DanailH** [comment]
> So if we use both methods simultaneously it registers both single click and double click when I do double click.

Ok, this makes more sense now. Well to be honest I'm not sure what the implications would be if we implement that behavior but you can achieve it myself by using a single handler for both props and counting the clicks within a given timeframe (300ms for example) to determine if someone is single clicking or double clicking. This is one possible solution.

**Comment by oleksandrfomin5995** [comment]
> > So if we use both methods simultaneously it registers both single click and double click when I do double click.
> 
> Ok, this makes more sense now. Well to be honest I'm not sure what the implications would be if we implement that behavior but you can achieve it myself by using a single handler for both props and counting the clicks within a given timeframe (300ms for example) to determine if someone is single clicking or double clicking. This is one possible solution.

Thanks. I'll give it a try

**Comment by oleksandrfomin5995** [comment]
The following implementation worked for me in case anyone runs into a similar issue. 

```
const DOUBLE_CLICK_THRESHOLD_MS = 250;

const CustomDataGrid = (props:  DataGridPremiumProps) => {

const { onRowClick, onRowDoubleClick, ...rest } = props;

const clickTimeout = useRef<NodeJS.Timeout | null>(null);

const handleRowClick: GridEventListener<'rowClick'> = useCallback(
    (
      params: GridRowParams,
      event: MuiEvent<React.MouseEvent<HTMLElement, MouseEvent>>,
      details: GridCallbackDetails<any>,
    ) => {
      if (clickTimeout.current) {
        if (onRowDoubleClick) {
          clearTimeout(clickTimeout.current);
          clickTimeout.current = null;
          onRowDoubleClick(params, event, details);
        }
      } else {
        if (onRowClick) {
          clickTimeout.current = setTimeout(() => {
            clickTimeout.current = null;
            onRowClick(params, event, details);
          }, DOUBLE_CLICK_THRESHOLD_MS);
        }
      }
    },
    [onRowClick, onRowDoubleClick],
  );
  
  return (
      <DataGridStyled
      ...
      onRowClick={handleRowClick}
      {...rest}
    />
  )
}
```

The only minor downside here is that a single click event has that added delay.

**Comment by MBilalShafi** [comment]
Glad it worked for you, I'll close the issue since there are no further action items on it.
Feel free to re-poen in case you have another related query.
