### ISSUE TITLE
DatePicker with Dayjs, utc and timezone does not allow proper date selection

### ISSUE THREAD

**Issue by TheLeggett** [mui/mui-x#9875]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/mui-x-date-pickers-dayjs-issue-forked-cj32qw?file=/src/Example.js

Steps:
1. Use the Dayjs Adapter with the utc and timezone extensions
2. Add a `<DatePicker>` component with a `system` timezone, with no date by default
3. Click the Calendar button, and then attempt to navigate to December 2023.

![image](https://github.com/mui/mui-x/assets/37707/a0d886c0-b789-4945-b1f4-a98d87148bf3)

### Current behavior 😯

Only two days display for the month of December. A similar pattern emerges for December-March for all years. Selecting a date resolves the issue the next time you open the calendar picker.

If instead you attempt to use the keyboard to key in a date in one of these months, the date ends up getting set for one day previous to the date keyed in when attempting from a system on EST.

This issue appears to self-correct after a date has been entered for the first time.

Using a different timezone like "UTC" or "America/New_York" resolves this issue, but presents a new issue when keying in dates. While keying in a date in this manner, the month and day values reset as you begin typing the year.

### Expected behavior 🤔

- A user should be able to click the calendar button and view valid dates for all months of the year
- A user should be able to key in a date when providing a "system" timezone, and the date entered should be reflected in the input.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.2.1
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.8.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base:  5.0.0-beta.6 
    @mui/core-downloads-tracker:  5.13.7 
    @mui/icons-material: ^5.13.7 => 5.13.7 
    @mui/material: ^5.13.7 => 5.13.7 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.7 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.7 
    @mui/x-data-grid:  6.9.2 
    @mui/x-data-grid-pro: ^6.9.2 => 6.9.2 
    @mui/x-date-pickers:  6.10.2 
    @mui/x-date-pickers-pro: ^6.9.2 => 6.10.2 
    @mui/x-license-pro:  6.9.0 
    @types/react: ^18.0.28 => 18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 
```
</details>

### Order ID or Support key 💳 (optional)

61481

**Comment by flaviendelangle** [comment]
Thanks for the detailed report !

I'll create a fix

**Comment by flaviendelangle** [comment]
[Here](https://codesandbox.io/s/mui-x-date-pickers-dayjs-issue-forked-3kmrlh?file=/src/App.js) is the same example but with my proposed fix

**Comment by TheLeggett** [comment]
This appears to address the issue from what I can see. It also addresses the additional issue when using other timezones besides `system` 👍
