### ISSUE TITLE
[question] How to style the datagrid pro detail panel?

### ISSUE THREAD

**Issue by ebo-bpi** [mui/mui-x#9882]
### Order ID or Support key 💳 (optional)

56680

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

I'm using a master / detail datagrid, and have styled the master table with a background etc. 
Now I also want to do this for the detail panel, but I can't find a way to do this. 
in the documentation there is nothing about style on the master / detail panel pages.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 13.5
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base: ^5.0.0-beta.8 => 5.0.0-beta.8 
    @mui/core-downloads-tracker:  5.14.2 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.137 => 5.0.0-alpha.137 
    @mui/material: ^5.14.2 => 5.14.2 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/system: ^5.14.1 => 5.14.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.1 
    @mui/x-data-grid:  6.10.1 
    @mui/x-data-grid-pro: ^6.10.1 => 6.10.1 
    @mui/x-date-pickers:  6.10.1 
    @mui/x-date-pickers-pro: ^6.10.1 => 6.10.1 
    @mui/x-license-pro: ^6.10.0 => 6.10.0 
    @types/react: 18.2.14 => 18.2.14 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.1.5 => 5.1.5 
```
</details>

**Comment by MBilalShafi** [comment]
If you want external styling like changing the background color etc, you can override the `gridClasses.detailPanel` class name, or you can also use your custom classes (used in the component returned by `getDetailPanelContent`).

Here's a small demonstration: https://codesandbox.io/s/cool-sun-cyrvs9?file=/Demo.tsx

Is that something you are looking for?

**Comment by Sainalkk6** [comment]
How to do the same using CSS classnames
