### ISSUE TITLE
[question] [DateRangePicker] Knowing which shortcut was clicked / accepted

### ISSUE THREAD

**Issue by cipherCOM** [mui/mui-x#9897]
### Order ID

68355

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have a similar setup like in the docs seen here (date range picker + shortcuts): https://next.mui.com/x/react-date-pickers/date-range-picker/#add-shortcuts

To allow our users to bookmark the current page as is, we use various URL query keys to store information like the start and end date from the picker. But since we also have shortcuts like "last month" we need to store that last month was chosen and not e.g. 2023-01-01 till 2023-01-31 because this will be different next month.

We can't find anything in the documentation on getting feedback that a specific shortcut element was clicked / accepted. Only place was within the TS definitions where we found `PickersShortcutsProps.onChange` but setting this seems to break the picker (date range isn't applied anymore).

Could you please provide us with any insight on how to tackle this problem?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 13.5
  Binaries:
    Node: 18.14.2 - ~/.asdf/installs/nodejs/18.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1
    @emotion/styled: 11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.4
    @mui/core-downloads-tracker:  5.13.4
    @mui/icons-material: 5.11.16 => 5.11.16
    @mui/material: 5.13.5 => 5.13.5
    @mui/private-theming:  5.13.1
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.5
    @mui/types:  7.2.4
    @mui/utils:  5.13.1
    @mui/x-data-grid: 5.17.26 => 5.17.26
    @mui/x-data-grid-premium: 5.17.26 => 5.17.26
    @mui/x-data-grid-pro:  5.17.26
    @mui/x-date-pickers:  6.7.0
    @mui/x-date-pickers-pro: 6.7.0 => 6.7.0
    @mui/x-license-pro:  5.17.12
    @types/react: 18.2.12 => 18.2.12
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.9.5 => 4.9.5
```
</details>

**Comment by cipherCOM** [comment]
Hmm good question. I always have 4 tabs open. 2 for data grid and 2 for picker with docs and API accordingly. Only the doc picker is of next.mui.com. Don't know anymore how that happened, sorry.

---

Something like that would be wonderful. With this it would be clear where the `newValue` comes from, if it was a shortcut.

Another possibility would be the have any onClick/onChange method on the `shortcutItems` themselves or "fixing" the mentioned `PickersShortcutsProps.onChange` which gives this information. Then you just have to keep track of where the last `onChange` happened and you know if it was just a arbitrary date or a shortcut within `onAccept`

**Comment by flaviendelangle** [comment]
> Don't know anymore how that happened, sorry.

No problem!

> Another possibility would be the have any onClick/onChange method on the shortcutItems themselves or "fixing" the mentioned PickersShortcutsProps.onChange which gives this information. Then you just have to keep track of where the last onChange happened and you know if it was just a arbitrary date or a shortcut within onAccept

Yes, I'll try to create a more hacky reproduction case to see if it's doable with the current API :+1:
