### ISSUE TITLE
[fields] Explore the feasibility of using `event.nativeEvent.data`

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#9904]
Follow-up on https://github.com/mui/mui-x/pull/9896

Maybe using `event.nativeEvent.data` could be the default for editing in order to avoid the need for so much processing of the `event.target.value`.
It would increase the performance for the majority of users and cases.

**Comment by flaviendelangle** [comment]
Closing since we are moving toward a new DOM structure with multi HTML element

Feel free to re-open it if you think we will modify the old implementation 👍
