### ISSUE TITLE
Don't scroll to end date for controlled Date Range Picker after selecting the start date

### ISSUE THREAD

**Issue by sagrawal-code** [mui/mui-x#9906]
### Order ID or Support key 💳 (optional)

65770

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

In our current scenario, say, a controlled Date Range Picker is initially set with the current month. When a user decides to choose a start date from a previous period (for example, a month from two years ago), the Date Range Picker subsequently defaults back to the original end date, representing the current month.

This action compels the user to scroll back through the calendar to the selected start date to specify their desired end date from the same past period.

After the user selects a start date from a previous period, is it possible that the Date Range Picker remains focused on that start date? This change would allow the user to seamlessly select their end date from the same period without having to navigate back from the current month.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 5.19 KDE neon 5.27 5.27
  Binaries:
    Node: 18.17.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.7 - /usr/bin/npm
  Browsers:
    Chrome: 115.0.5790.110
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.5 
    @mui/core-downloads-tracker:  5.13.4 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/material: ^5.13.6 => 5.13.6 
    @mui/private-theming:  5.13.1 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.6 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.6 
    @mui/x-data-grid: ^6.9.1 => 6.9.1 
    @mui/x-data-grid-generator: ^6.9.1 => 6.9.1 
    @mui/x-data-grid-premium:  6.9.1 
    @mui/x-data-grid-pro: ^6.9.1 => 6.9.1 
    @mui/x-date-pickers:  6.9.1 
    @mui/x-date-pickers-pro: ^6.9.1 => 6.9.1 
    @mui/x-license-pro:  6.9.0 
    @types/react: ^18.2.14 => 18.2.14 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 5.1.6 => 5.1.6```
</details>

**Comment by alexfauquette** [comment]
I don't see for now a solution/workaround for this feature. It would require providing one of those options
- an option to block the view-switching when moving from start to end
- a control over the current month displayed with an onCHnage indicating the reason of the month switch

**Comment by alexfauquette** [comment]
> an option to block the view-switching when moving from start to end

I missed it but it seems this option already exists: [disableAutoMonthSwitching](https://mui.com/x/api/date-pickers/date-range-picker/#DateRangePicker-prop-disableAutoMonthSwitching)

Here is an example with it
https://codesandbox.io/s/nifty-wildflower-7d239j?file=/Demo.tsx:576-601

Does it solve your issue?

**Comment by sagrawal-code** [comment]
> Does it solve your issue?

Yes, it does. Thank you!
