### ISSUE TITLE
[pickers] Valid leap year day changing in datefields

### ISSUE THREAD

**Issue by jamaybyrone** [mui/mui-x#9917]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

[Date Pickers](https://mui.com/x/react-date-pickers/)

Steps:
1. Enter 02/29/1988 which is a valid day for a leap year
2. Changes 29th to 28th

### Current behavior 😯

changes the day value for a valid leap year

### Expected behavior 🤔

should not change day value

### Context 🔦

Users entering a date of birth may end up submitting the wrong data if they have not noticed the day changed without there input.

**Comment by alexfauquette** [comment]
I confirm the bug, the reason being the intermediate date `02/29/1988` which is considered valid by the library.

**Comment by Erik844H** [comment]
It's not just about leap year. This also solves the issues when editing datefields in European date-formats DD.MM.YYYY. Trying to edit 30.11 into 31.12 by typing, would give 30.12, due to clamping of the intermediate value 31.11.
