### ISSUE TITLE
[question] How to render a custom row?

### ISSUE THREAD

**Issue by maciej-gurban** [mui/mui-x#9923]
### Order ID or Support key 💳 (optional)

69412

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We're trying to implement the functionality you might be familiar with in Gmail - hover the mouse over a row, and a few action buttons will appear. See screenshot below. We'd like to be able to render those action buttons always on the right side of the row, as an overlay, rather than in any particular cell. This is important as these buttons should be always visible on hover, regardless of how wide or narrow the screen is.

I can see that there's a possibility to override slots.row, however I could not find any documentation, examples or issues which would showcase how to properly override the row slot without entirely erasing what would be rendered there otherwise.

<img width="727" alt="Screenshot 2023-08-04 at 13 52 39" src="https://github.com/mui/mui-x/assets/3663640/87f06b7b-a784-4e4f-b435-7b89469f4039">

I've created this [code sandbox](https://codesandbox.io/s/holy-thunder-ycd59y), where I override the whole row, and log the data that's passed down. I'd like to know what can I do with that data, and with what to render it as a regular row (as it would be otherwise without any slot override). If it's possible to create a wrapper around a row, I'd simply insert some kind of relative positioned wrapper inside a row, and render absolutely positioned node with above mentioned action buttons, and attach onMouseEnter events.

Any help would be appreciated

**Comment by DanailH** [comment]
Hey @maciej-gurban, thanks for raising this!
We have seen this request pop up before. Unfortunately, we don't have the solution out of the box. We have made an example implementation tho. You can check this comment for some inspiration on how you can achieve this https://github.com/mui/mui-x/issues/3656#issuecomment-1015245533.
The main idea is to still use the action column and update the buttons to be shown on hover.
Let me know if this is what you were looking for.

**Comment by maciej-gurban** [comment]
Thanks for the link @DanailH. That's what we did so far, but the issue is that we want actions always visible. If we add them to the last column (or any column), and table container ends up being narrow enough to render actions column beyond what's visible without scrolling, that's not sufficient. I'll try to experiment more, but it looks pretty challenging to do that

**Comment by DanailH** [comment]
You can pin the column to the left (or right)?

**Comment by maciej-gurban** [comment]
Not quite it though, since we want to show this actions column only when user hovers over the row, unless you're saying that it is possible to achieve this using sticky column? I don't suppose there'd be a demo of that anywhere?

**Comment by DanailH** [comment]
Sorry, what I wrote was a bit undescriptive. You can try and achieve your desired functionality by using the column pinning feature, essentially pinning the actions column. You can then hover over the row and call `apiRef.current.setColumnVisibility(field, boolean);` to make the actions column visible.
In addition, you would need to customize the `actions` column and show/hide it using the `slotProps={{
          row: { onMouseOver: handleRowOver },
        }}`

Let me know if this is a bit more clear.
