### ISSUE TITLE
[data grid] No result overlay interferes with grid manipulation

### ISSUE THREAD

**Issue by cotenoni** [mui/mui-x#9927]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/strange-chaum-3znsww

Steps:
1. Pin all 4 rows
2. Try to unpin a row

### Current behavior 😯

When all rows in a grid are pinned, it is impossible to unpin them as the No result overlay block the user from clicking on a row. 

### Expected behavior 🤔

Either no overlay (as rows are presents) or the overlay shouldn't block the user from clicking on the pinned rows.

### Your environment 🌎

System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: 115.0.1901.183
    Safari: 16.5.2

**Comment by DanailH** [comment]
@cotenoni thanks for reporting this. We have missed this corner case 😅

**Comment by yaredtsy** [comment]
hey @DanailH 

why not just show the `Now Rows` overlay on the main row content area only.

<img width="956" alt="image" src="https://github.com/mui/mui-x/assets/34584266/25cfcaa1-98e1-4212-9d7e-0ed751a0c2be">
 
demo: https://codesandbox.io/s/blue-leftpad-3tzf6q

**Comment by DanailH** [comment]
@yaredtsy that is another viable option.
