### ISSUE TITLE
[charts] labels clip into chart on firefox due to `alignment-baseline: hanging;`

### ISSUE THREAD

**Issue by MonstraG** [mui/mui-x#9929]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://mui.com/x/react-charts/areas-demo/

### Current behavior 😯

![image](https://github.com/mui/mui-x/assets/17963791/2940aa6b-eab4-490c-bb34-80d1c9425a71)
Firefox 117.0b2 (64-bit)

Firefox doesn't know about `alignment-baseline: hanging;`

### Expected behavior 🤔

![image](https://github.com/mui/mui-x/assets/17963791/84ae5a91-9c0a-434c-9b5d-28c437aeaf5c)
Chrome 117.0.5929.0

**Comment by LukasTy** [comment]
Thank you for reporting this issue.
It looks like we are applying an incorrect alignment rule on the given element: https://stackoverflow.com/a/21373135/3303436
