### ISSUE TITLE
[pickers] `onChange` not run when `changeImportance: 'set'`

### ISSUE THREAD

**Issue by jjernstrom** [mui/mui-x#9931]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/laughing-lichterman-gmvscf?file=/Demo.tsx

Steps:
1. Set the `changeImportance` flag in the `shortcut` props to 'set'
2. `console.log()` the `onChange` and `onAccept` functions
3. Select a `shortcut` item in the `dateRangePicker`
4. Expect to see a log message in the console for the `onChange` function
5. Select the `OK` button
6. Expect to see a log message in the console for `onAccept` function
7. observe both `onChange` and `onAccept` are not run 

![image](https://github.com/mui/mui-x/assets/121989424/7d0e1fec-38ee-4acf-87d5-19b31baa90b7)

![image](https://github.com/mui/mui-x/assets/121989424/31768653-6878-4dc8-8b53-0ef36a0437ac)

### Current behavior 😯

When setting the `changeImportance` property of the `shortcuts` object to `'set'` in the `DateRangeSelector` the `onChange` function is not run when a shortcut is selected and the `onAccept` function is not run after a shortcut is selected followed by selecting the `OK` button.

### Expected behavior 🤔

- `onChange` is run when a shortcut is selected and `changeImportance: 'set'`
- `onAccept` is run after a shortcut is selected followed by `OK` and `changeImportance: `set` 
 

### Context 🔦

Implementation requirements were:

- Update app state with the `DateRangePicker` `value` if and only if the `OK` button is selected.
- Don't close the component when a shortcut is selected only when `Cancel`, `OK`, or `clickAway` are triggered.

We were unable to satisfy the above requirements.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Browser tested: Chrome

  System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 3.5.1 - ~/.asdf/installs/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.asdf/installs/nodejs/18.16.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: Not Found
    Safari: 16.5.2
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.8 
    @mui/core-downloads-tracker:  5.14.3 
    @mui/icons-material: ^5.14.1 => 5.14.1 
    @mui/lab: ^5.0.0-alpha.137 => 5.0.0-alpha.137 
    @mui/material: ^5.14.2 => 5.14.3 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.14.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.7 
    @mui/x-data-grid:  6.10.2 
    @mui/x-data-grid-premium: ^6.10.2 => 6.10.2 
    @mui/x-data-grid-pro:  6.10.2 
    @mui/x-date-pickers:  6.10.2 
    @mui/x-date-pickers-pro: ^6.10.2 => 6.10.2 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.15 => 18.2.15 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.1.6 => 5.1.6 
```
</details>

**Comment by LukasTy** [comment]
Thank you for reporting this issue. 🙏 
I can confirm that this is an actual bug that needs solving.
