### ISSUE TITLE
@mui/x-tree-view published to npmjs.com as 6.0.0-alpha.0 although 6.11.0 is released

### ISSUE THREAD

**Issue by dawi** [mui/mui-x#9951]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Starting with version [v6.11.0](https://github.com/mui/mui-x/releases/tag/v6.11.0) TreeView should now be accessible from its own package: `@mui/x-tree-view`.

However `@mui/x-tree-view` is currently only available as `6.0.0-alpha.0`: https://www.npmjs.com/package/@mui/x-tree-view.

### Expected behavior 🤔

`@mui/x-tree-view` should be published with version `6.11.0`

**Comment by joserodolfofreitas** [comment]
Thanks for pointing out this misunderstanding, @dawi! 

I think we could improve our changelog to say it's an alpha release.
We'll fix some bugs and iterate over the component a few times before we release a stable package.

**Comment by flaviendelangle** [comment]
@joserodolfofreitas which change do you propose we do to the CHANGELOG?
