### ISSUE TITLE
[pickers] Can't pass the `name` of the field

### ISSUE THREAD

**Issue by thany** [mui/mui-x#9956]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-issue-template-forked-nlyw9x?file=/src/App.tsx
In this example, I placed each of the three attempts below, each in their own DatePicker, so you can see Typescript complaining for all three.

There seems to be no way to pass a `name` property to the underlying HTML element. I tried:

* `<DatePicker name="foo" />` - Property `name` doesn't exist.
* `<DatePicker slotProps={{ field: { name: "foo" } }} />` - Property `name` doesn't exist.
* `<DatePicker slotProps={{ field: { InputProps: { name: "foo" } } }} />` - Property `name` doesn't exist.

### Current behavior 😯

The Typescript typings in all three attempts above, will claim the `name` property just simply doesn't exist.

**However**: in the second and third attempts, the `name` attribute with the correct value does end up in the HTML `input` element, so it _is_ being passed. Seems like the typings are wrong then, maybe, aren't they.

### Expected behavior 🤔

Correct typings, no error, some kind of way to pass the `name` property.

### Context 🔦

The `name` property is neccesary for accessibility reasons. Among others, it enables the browser to maintain historic form values for autofill. It also plays well with other code that might expect a `name` to be there. And also, [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name) to consider it a required attribute, which I'm happy to comply with, if I could.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 115.0.5790.171
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
```

And Firefox 116.0.1, which is never found by this tool!
</details>

**Comment by LukasTy** [comment]
We do not expose the `name` property from the top level, although, that could be a consideration given how important this prop is. 🤔 
The `field` slot has props related to the field behavior mostly and does not expose the underlying `textField` slots at least now.
Consider using the following implementation to unblock you:
```tsx
slotProps={{
  textField: { name: 'foo' }
}}
```

**Comment by thany** [comment]
Hey that works 👍🏻
Interesting. I thought `textField` was used for helper texts/errors as [this bit of the docs](https://mui.com/x/react-date-pickers/date-picker/#helper-text) appears to suggest.

I do wonder what the difference is supposed to be between `field` and `textField` in the `slotProps`. The [docs about slotProps](https://mui.com/x/api/date-pickers/date-picker/#DatePicker-prop-slotProps) is not super elaborate about it, nor does it link to more information. So, that's guesswork then, innit 🤷🏻‍♂️

I think it would be best to expose it from the top level, yes. That would also make it play nicer with React form packages, like React Hook Form (it's certainly possible to integrate the two, though it could be easier).

**Comment by LukasTy** [comment]
We decided to look into exposing a top-level `name` prop on the field components (i.e. `DateField`) and transitively on the picker (i.e. `DatePicker`) components.
The above holds true If our future plans of refactoring the field to contain a hidden input with a value and all the sections as separate elements don't interfere with it.

If we add `name` as a top-level form prop, then it makes sense to document it in the appropriate section: https://mui.com/x/react-date-pickers/date-picker/#form-props

**Comment by gitstart** [comment]
@thany @LukasTy we would like to pick this up
