### ISSUE TITLE
[TreeView] '@mui/x-tree-view/themeAugmentation' missed

### ISSUE THREAD

**Issue by Semigradsky** [mui/mui-x#9957]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Looks like we should have the correct working import for customizing:
```ts
import type {} from '@mui/x-tree-view/themeAugmentation'
```

The same as we have for date pickers:
```ts
import type {} from '@mui/x-date-pickers/themeAugmentation'
```

### Your environment 🌎

> "@mui/x-tree-view": "6.0.0-alpha.0",

**Comment by flaviendelangle** [comment]
Hi,

Thanks for the feedback
This part has indeed not been migrated, I'll add it for the next release :+1:

**Comment by headironc** [comment]
It seems `import type {} from "@mui/x-tree-view-pro/themeAugmentation"` doesn't work

**Comment by LukasTy** [comment]
@headironc thank you for raising the problem. 🙏 
Indeed, the pro package `themeAugmentation` includes only the pro package component and does not import the types for the other components (`SimpleTreeView` and `TreeItem`).
I've created a PR attempting to fix this. 😉
