### ISSUE TITLE
[TreeView] Controlled tree view and shift click does not select range

### ISSUE THREAD

**Issue by DickvdBrink** [mui/mui-x#9963]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/gallant-silence-jrzmj2?file=/demo.tsx

Steps:

1. Open the demo (and do not click any node)
2. Shift click on Webstorm

I used the Chrome browser for this - Version 114.0.5735.199

### Current behavior 😯

The first item, "Applications" stays selected and Webstorm gets a focused color.
But selection is not updated.

### Expected behavior 🤔

I expected it to update the selected items to `[1, 2, 3, 4]` (so the first 4 items).
It does work when you first click the `Applications` node manually and then execute the reproduction steps.

### Context 🔦

I am trying to use the treeview in a controlled manner. 
The selected item(s) can be updated from different components in my application, and the tree might also influence the selection of other components. We also use `multiselect`.

It looks like the `selectRange` method does not call `handleRangeSelect` because the `lastSelectedNode.current` is null - which is causing this issue.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.16.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.79)
  npmPackages:
    @emotion/react: latest => 11.11.1
    @emotion/styled: latest => 11.11.0
    @mui/base:  5.0.0-beta.7
    @mui/core-downloads-tracker:  5.14.0
    @mui/icons-material: latest => 5.14.0
    @mui/lab: latest => 5.0.0-alpha.136
    @mui/material: latest => 5.14.0
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/system:  5.14.0
    @mui/types:  7.2.4
    @mui/utils:  5.13.7
    @types/react: latest => 18.2.15
    react: latest => 18.2.0
    react-dom: latest => 18.2.0
    typescript: latest => 5.1.6
```
</details>

**Comment by flaviendelangle** [comment]
[Demo updated for v7 alpha API](https://codesandbox.io/s/confident-swartz-2gy2wk?file=/demo.tsx)
