### ISSUE TITLE
[DataGrid] Hide '__detail_panel_toggle__' column from the list of columns in toolbar columns popup

### ISSUE THREAD

**Issue by esdee-reign** [mui/mui-x#9968]
### Order ID or Support key 💳 (optional)

69762

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

- I took reference from MUI Data Grid - Master detail example and built a table.
- I added a toolbar that has a 'Columns' and 'Filters' button.
- For each row, there's a toggle that hides/unhides the nested table.
- The toggle appears to be in a column as seen in the list of columns that appear inside 'toolbar columns popup'.
- I want to hide '__detail_panel_toggle__' column in the popup so that the user does not have control to hide/unhide the column
<img width="1397" alt="Screenshot 2023-08-08 at 1 47 51 PM" src="https://github.com/mui/mui-x/assets/56202218/e3c78ede-b417-4e2d-a479-39d7a96bf579">
<img width="329" alt="Screenshot 2023-08-08 at 1 46 44 PM" src="https://github.com/mui/mui-x/assets/56202218/7a67175e-d12e-4ae1-9807-61dc1941da40">

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: Not Found
    Safari: 16.5.2
  npmPackages:
    @emotion/react: ^11.10.5 => 11.11.1 
    @emotion/styled: ^11.10.5 => 11.11.0 
    @mui/base:  5.0.0-beta.6 
    @mui/core-downloads-tracker:  5.13.7 
    @mui/icons-material: ^5.11.0 => 5.13.7 
    @mui/material: ^5.11.2 => 5.13.7 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.13.7 
    @mui/types:  7.2.4 
    @mui/utils:  5.13.7 
    @mui/x-data-grid: ^6.10.1 => 6.10.1 
    @mui/x-data-grid-pro: ^6.11.0 => 6.11.0 
    @mui/x-license-pro:  6.10.2 
    @types/react: 18.0.9 => 18.0.9 
    react: ^18.1.0 => 18.2.0 
    react-dom: ^18.1.0 => 18.2.0 
    typescript: 4.6.4 => 4.6.4
```
</details>

**Comment by MBilalShafi** [comment]
You could use [getTogglableColumns](https://mui.com/x/react-data-grid/column-visibility/#customize-the-list-of-columns-in-panel) prop of `columnsPanel` to configure which columns are togglable in the columns panel.

Here's a codesandbox example where it's being done: https://codesandbox.io/s/floral-fog-q8zhsh?file=/Demo.tsx

**Comment by esdee-reign** [comment]
Yes it works. Thanks!
