### ISSUE TITLE
[TreeView] Icons getting bigger in production environment in safari

### ISSUE THREAD

**Issue by sayinmehmet47** [mui/mui-x#9970]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1. I am using mui tree component to create folder structure. 
2. It is working fine in other then safari browser perfectly in all environments 

<img width="1697" alt="image" src="https://github.com/mui/material-ui/assets/75525090/c57dd380-eefb-41cf-8345-d62370849f60">

### Current behavior 😯

The icons size and the child folders left padding is not correct in safari Version 15.6.1. But it works well in all other browsers and last safari version.

<img width="1420" alt="image" src="https://github.com/mui/material-ui/assets/75525090/22a0ff63-9b81-4078-b266-6c49ab8c6838">

### Expected behavior 🤔

The icons size and left padding of the child folders should shown like in the picture

<img width="921" alt="image" src="https://github.com/mui/material-ui/assets/75525090/8037d6ec-49d4-41ec-af18-90668a5ecd44">

### Context 🔦
seems "css-yuu8jj" missing in styles in safari
<img width="1238" alt="Screenshot 2023-08-09 at 09 01 52" src="https://github.com/mui/mui-x/assets/75525090/cb7551ee-cd27-463c-b080-f18bc2365c8d">

see in chrome it does not 
<img width="1582" alt="Screenshot 2023-08-09 at 09 04 49" src="https://github.com/mui/mui-x/assets/75525090/86a758f9-5de6-4937-89e0-f449c9ca1de9">

want to share some of my code

```js
import cn from 'classnames';
import { forwardRef, type Ref } from 'react';
import { useTreeItem, TreeItemContentProps } from '@mui/lab/TreeItem';

export const TreeViewCustomComponent = forwardRef(function CustomContent(
  props: TreeItemContentProps,
  ref
) {
  const {
    classes,
    className,
    label,
    nodeId,
    icon: iconProp,
    expansionIcon,
    displayIcon,
  } = props;

  const {
    disabled,
    expanded,
    selected,
    focused,
    handleExpansion,
    handleSelection,
    preventSelection,
  } = useTreeItem(nodeId);

  const icon = iconProp ?? expansionIcon ?? displayIcon;

  const handleMouseDown = (
    event: React.MouseEvent<HTMLDivElement, MouseEvent>
  ) => {
    preventSelection(event);
  };

  const handleExpansionClick = (
    event: React.MouseEvent<HTMLDivElement, MouseEvent>
  ) => {
    handleExpansion(event);
  };

  const handleSelectionClick = (
    event: React.MouseEvent<HTMLDivElement, MouseEvent>
  ) => {
    handleSelection(event);
  };

  return (
    // eslint-disable-next-line jsx-a11y/no-static-element-interactions
    <div
      className={cn(className, classes.root, {
        [classes.expanded]: expanded,
        [classes.selected]: selected,
        [classes.focused]: focused,
        [classes.disabled]: disabled,
      })}
      onMouseDown={handleMouseDown}
      ref={ref as Ref<HTMLDivElement>}
    >
      {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events,jsx-a11y/no-static-element-interactions */}
      <div onClick={handleExpansionClick} className={classes.iconContainer}>
        {icon}
      </div>
      {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events,jsx-a11y/no-static-element-interactions */}
      <div onClick={handleSelectionClick} className={classes.label}>
        {label}
      </div>
    </div>
  );
});


```

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    "@mui/base": "5.0.0-beta.8",
    "@mui/lab": "5.0.0-alpha.137",
    "@mui/material": "5.14.2",

Safari

Version 15.6.1 (17613.3.9.1.16)
```
</details>

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.
