### ISSUE TITLE
Mui Tree Viewer component icons getting bigger in production environment in safari

### ISSUE THREAD

**Issue by sayinmehmet47** [mui/mui-x#9972]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:

1. I am using mui tree component to create folder structure. 
2. It is working fine in other then safari browser perfectly in all environments 

<img width="1697" alt="image" src="https://github.com/mui/material-ui/assets/75525090/c57dd380-eefb-41cf-8345-d62370849f60">

### Current behavior 😯

The icons size and the child folders left padding is not correct in safari Version 15.6.1. But it works well in all other browsers and last safari version.

<img width="1420" alt="image" src="https://github.com/mui/material-ui/assets/75525090/22a0ff63-9b81-4078-b266-6c49ab8c6838">

### Expected behavior 🤔

The icons size and left padding of the child folders should shown like in the picture

<img width="921" alt="image" src="https://github.com/mui/material-ui/assets/75525090/8037d6ec-49d4-41ec-af18-90668a5ecd44">

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    "@mui/base": "5.0.0-beta.8",
    "@mui/lab": "5.0.0-alpha.137",
    "@mui/material": "5.14.2",

Safari

Version 15.6.1 (17613.3.9.1.16)
```
</details>

**Comment by flaviendelangle** [comment]
You already opened one yesterday (#9970)

**Comment by sayinmehmet47** [comment]
> You already opened one yesterday (#9970)

thought posted in wrong channel sorry
