### ISSUE TITLE
How to get filter tooltip to use label instead of value

### ISSUE THREAD

**Issue by tvaughan73** [mui/mui-x#9981]
### Order ID

62910

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

When using a grid with a singleSelect field the tooltip displays the value and not the label from valueOptions.

![Screenshot 2023-08-09 103953](https://github.com/mui/mui-x/assets/850122/7834e4f3-9ce5-4742-947e-3dc9dc349375)

Tooltip is displaying the ID of the selected client instead of the client name that is selected in the filter dropdown.

![Screenshot 2023-08-09 104025](https://github.com/mui/mui-x/assets/850122/e92d2709-ee6d-42dd-86be-78f1e08d7d9e)

How do I make this display the client name?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hey @tvaughan73 thanks for raising this!
Yes, the tooltip in the filter button located in the toolbar shows the actual value of the `singleSelect` from the column. This creates problems when you are using a structure where the value shown to the user is different than the one used internally. You make it more readable you can use the `getValueAsString` callback in the filter operator to customize what is being shown in the tooltip.
We have a dedicated example for this use case. You can check it here -> https://mui.com/x/react-data-grid/filtering/customization/#create-a-custom-operator

Let me know if this works for you

**Comment by xav1639** [comment]
This is confusing default behavior inconsistent with similar components.
