### ISSUE TITLE
[DataGridPro] Pinned columns headers covers all other columns if grouped columns exists

### ISSUE THREAD

**Issue by Braidon** [mui/mui-x#9988]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Run demo
https://codesandbox.io/s/patient-haze-533ksl?file=/src/App.js

### Current behavior 😯

Pinned columns headers totaly covers all other columns headers

### Expected behavior 🤔

Pinned column header must be the same width as a column itself

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  System:
    OS: Windows 10 10.0.17763
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 115.0.5790.102
    Edge: Not Found
</details>

**Comment by yaredtsy** [comment]
hey @Braidon 
Empty group headers seem to be adding extra width, which is why they are expanding. You can limit the parent column width as a workaround.

```jsx
<DataGridPro
  sx={{
    ["& .MuiDataGrid-pinnedColumnHeaders--right"]: {
      width: "60px"
    },
    ["& .MuiDataGrid-pinnedColumnHeaders--left"]: {
      width: "270px"
    }
  }}
/>
```
demo: https://codesandbox.io/s/objective-swanson-gwwkl8?file=/src/App.js:19455-19745

**Comment by Braidon** [comment]
Yep, it works. Thanks.

**Comment by cherniavskii** [comment]
I can no longer reproduce the issue in the latest version of the Data Grid: https://codesandbox.io/s/jovial-waterfall-2pfv99
