### ISSUE TITLE
[pickers] PickersToolbarContent is moved left when I set spacing in theme default props

### ISSUE THREAD

**Issue by ErikParso** [mui/mui-x#9990]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. set spacing for grid in theme.MuiGrid.defaultProps
2. use any mobile date picker

![image](https://github.com/mui/material-ui/assets/35962203/5e4be2c8-b311-4cc1-891a-2b3724f30795)

### Current behavior 😯

Because toolbar content component is Grid and items inside are not grid items, whole content is moved left.

### Expected behavior 🤔

Items should be aligned. Use grid items inside toolbar content, or force spacing to be zero here.

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by ErikParso** [comment]
Yes in simple 2 steps
1. set default spacing for grid in theme
2. use any mobile picker that has toolbar inside
https://codesandbox.io/s/date-and-time-pickers-forked-mwjdrd?file=/src/App.tsx

**Comment by LukasTy** [comment]
Thank you for opening this issue.
The usage of `Grid` in the toolbar is indeed incorrect.
IMHO, removing it is easier and easier to maintain, because there is no need to remember that the children of the `PickersToolbarContent` have to be `Grid` items. 👌
