### ISSUE TITLE
[data grid] Selected rows not enforced on Print export

### ISSUE THREAD

**Issue by zreecespieces** [mui/mui-x#9993]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/cocky-booth-mw47xv?file=/Demo.tsx

Steps:
1. Create a basic DataGrid example with columns and some data, this is cloned from a documentation sandbox
2. Select a couple of rows using the selection checkboxes
3. Click export -> Print -> Observe that all rows are exported, not just selected rows, incorrectly
4. Click export -> Download as CSV -> Observe that only the selected rows are exported, as expected

### Current behavior 😯

Selecting rows and then exporting using the 'Print' option results in all rows being exported not just the selected rows.

### Expected behavior 🤔

When selecting rows and then exporting only the selected rows should be exported.

### Context 🔦

I'm working on some educational content for MUI and found this behavior which appears to be a bug

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
Codesandbox, Chrome browser (Version 115.0.5790.114), MUI X Data Grid (Version 6.11.0)

**Comment by zreecespieces** [comment]
[PR submitted](https://github.com/mui/mui-x/pull/10084)

**Comment by cherniavskii** [comment]
I don't think this is a regression, it was an intentional behavior:
https://mui.com/x/react-data-grid/export/#print-export

<img width="827" src="https://github.com/mui/mui-x/assets/13808724/cb0b49ac-3e04-496f-924e-b9921bc9c336">

We can enhance it by allowing to customize the exported rows.
